### PR TITLE
Set the CONFIGURATION_BUILD_DIR in generated xcconfig when debugging core device

### LINKED ISSUE #134186: Xcode 15: Can't run apps in profile mode
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. `flutter create test`
2. `cd test && flutter run --profile`

### Expected results

App runs.

### Actual results

Version 15.0 beta 8 (15A5229m) opens and throws this error message. Happens across multiple projects and persists across restarts.

Works in debug and release mode. Also works on Xcode 14.

```
Failed to install the app on the device.
Domain: com.apple.dt.CoreDeviceError
Code: 3002
User Info: {
    DVTErrorCreationDateKey = "2023-09-07 02:03:41 +0000";
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
    NSURL = "file:///Users/james/Development/test/build/ios/Debug-iphoneos/Runner.app/";
}
--
The item at Runner.app is not a valid bundle.
Domain: com.apple.dt.CoreDeviceError
Code: 3000
Failure Reason: The path to the provided bundle's main executable could not be determined.
User Info: {
    NSURL = "file:///Users/james/Development/test/build/ios/Debug-iphoneos/Runner.app/";
    ProvidedBundle = "file:///Users/james/Development/test/build/ios/Debug-iphoneos/Runner.app/";
}
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_model" = "iPhone14,2";
    "device_osBuild" = "17.0 (21A5326a)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "347.1";
    "dvt_mobiledevice_version" = "1643.2.3";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 61;
    "operation_errorCode" = 3000;
    "operation_errorDomain" = "com.apple.dt.CoreDeviceError.3002.com.apple.dt.CoreDeviceError";
    "operation_errorWorker" = IDEInstallCoreDeviceWorker;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.0";
    "sdk_osVersion" = "17.0";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 13.4.1 (Build 22F82)
Xcode 15.0 (22005) (Build 15A5229m)
Timestamp: 2023-09-06T19:03:41-07:00
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```dart
[  +66 ms]  └─Compiling, linking and signing... (completed in 2,884ms)
[        ] Xcode build done.                                           11.6s
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun xcresulttool get --path
/var/folders/7d/kkdmr73s263gg477ncjwycnm0000gn/T/flutter_tools.NasJy8/flutter_ios_build_temp_dirOWj72b/temporary_xcresult_bundle --format json
[ +167 ms] {
                      "_type" : {
                        "_name" : "ActionsInvocationRecord"
                      },
                      "actions" : {
                        "_type" : {
                          "_name" : "Array"
                        },
                        "_values" : [
                          {
                            "_type" : {
                              "_name" : "ActionRecord"
                            },
                            "actionResult" : {
                              "_type" : {
                                "_name" : "ActionResult"
                              },
                              "coverage" : {
                                "_type" : {
                                  "_name" : "CodeCoverageInfo"
                                }
                              },
                              "issues" : {
                                "_type" : {
                                  "_name" : "ResultIssueSummaries"
                                }
                              },
                              "metrics" : {
                                "_type" : {
                                  "_name" : "ResultMetrics"
                                }
                              },
                              "resultName" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "action"
                              },
                              "status" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "notRequested"
                              }
                            },
                            "buildResult" : {
                              "_type" : {
                                "_name" : "ActionResult"
                              },
                              "coverage" : {
                                "_type" : {
                                  "_name" : "CodeCoverageInfo"
                                }
                              },
                              "issues" : {
                                "_type" : {
                                  "_name" : "ResultIssueSummaries"
                                },
                                "warningSummaries" : {
                                  "_type" : {
                                    "_name" : "Array"
                                  },
                                  "_values" : [
                                    {
                                      "_type" : {
                                        "_name" : "IssueSummary"
                                      },
                                      "documentLocationInCreatingWorkspace" : {
                                        "_type" : {
                                          "_name" : "DocumentLocation"
                                        },
                                        "concreteTypeName" : {
                                          "_type" : {
                                            "_name" : "String"
                                          },
                                          "_value" : "Xcode3ProjectDocumentLocation"
                                        },
                                        "url" : {
                                          "_type" : {
                                            "_name" : "String"
                                          },
                                          "_value" :
                                          "file:\/\/\/Users\/james\/Development\/test\/ios\/Runner.xcodeproj#Timestamp=715748406.200129&XcodeLocation=%7B%22Selection%22:%7B%22Editor%22:%22Xcode3BuildSe
                                          ttingsEditor%22,%22Target%22:%22Runner%22,%22Xcode3BuildSettingsEditorLocations%22:%5B%7B%22Selected%20Build%20Properties%22:%5B%22IPHONEOS_DEPLOYMENT_TARGET%2
                                          2%5D%7D%5D%7D%7D"
                                        }
                                      },
                                      "issueType" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Target Integrity"
                                      },
                                      "message" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.0.99."
                                      }
                                    }
                                  ]
                                }
                              },
                              "logRef" : {
                                "_type" : {
                                  "_name" : "Reference"
                                },
                                "id" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "0~yxbSe3OmjDGxMO41Y_1a9hyFQlFBRidOxRWaGnlVvuR65mMoA2UKK6lUv_ouHrY3N4mjDqFBpsJUQBC97QGq2Q=="
                                },
                                "targetType" : {
                                  "_type" : {
                                    "_name" : "TypeDefinition"
                                  },
                                  "name" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "ActivityLogSection"
                                  }
                                }
                              },
                              "metrics" : {
                                "_type" : {
                                  "_name" : "ResultMetrics"
                                },
                                "warningCount" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "1"
                                }
                              },
                              "resultName" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "build"
                              },
                              "status" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "succeeded"
                              }
                            },
                            "endedTime" : {
                              "_type" : {
                                "_name" : "Date"
                              },
                              "_value" : "2023-09-06T20:00:10.033-0700"
                            },
                            "runDestination" : {
                              "_type" : {
                                "_name" : "ActionRunDestinationRecord"
                              },
                              "displayName" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Apollo"
                              },
                              "localComputerRecord" : {
                                "_type" : {
                                  "_name" : "ActionDeviceRecord"
                                },
                                "busSpeedInMHz" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "cpuCount" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "1"
                                },
                                "cpuKind" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "Apple M1 Pro"
                                },
                                "cpuSpeedInMHz" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "identifier" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "00006000-000E28E90238801E"
                                },
                                "isConcreteDevice" : {
                                  "_type" : {
                                    "_name" : "Bool"
                                  },
                                  "_value" : "true"
                                },
                                "logicalCPUCoresPerPackage" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "10"
                                },
                                "modelCode" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "MacBookPro18,1"
                                },
                                "modelName" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "MacBook Pro"
                                },
                                "modelUTI" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "com.apple.macbookpro-16-2021"
                                },
                                "name" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "My Mac"
                                },
                                "nativeArchitecture" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "arm64e"
                                },
                                "operatingSystemVersion" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "13.4.1"
                                },
                                "operatingSystemVersionWithBuildNumber" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "13.4.1 (22F82)"
                                },
                                "physicalCPUCoresPerPackage" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "10"
                                },
                                "platformRecord" : {
                                  "_type" : {
                                    "_name" : "ActionPlatformRecord"
                                  },
                                  "identifier" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "com.apple.platform.macosx"
                                  },
                                  "userDescription" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "macOS"
                                  }
                                },
                                "ramSizeInMegabytes" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "16384"
                                }
                              },
                              "targetArchitecture" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "arm64"
                              },
                              "targetDeviceRecord" : {
                                "_type" : {
                                  "_name" : "ActionDeviceRecord"
                                },
                                "busSpeedInMHz" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "cpuCount" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "cpuSpeedInMHz" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "identifier" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "00008110-0004752E3AB8801E"
                                },
                                "isConcreteDevice" : {
                                  "_type" : {
                                    "_name" : "Bool"
                                  },
                                  "_value" : "true"
                                },
                                "logicalCPUCoresPerPackage" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "modelCode" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "iPhone14,2"
                                },
                                "modelName" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "iPhone 13 Pro"
                                },
                                "modelUTI" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "com.apple.iphone-13-pro-1"
                                },
                                "name" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "Apollo"
                                },
                                "nativeArchitecture" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "arm64e"
                                },
                                "operatingSystemVersion" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "17.0"
                                },
                                "operatingSystemVersionWithBuildNumber" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "17.0 (21A5326a)"
                                },
                                "physicalCPUCoresPerPackage" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "platformRecord" : {
                                  "_type" : {
                                    "_name" : "ActionPlatformRecord"
                                  },
                                  "identifier" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "com.apple.platform.iphoneos"
                                  },
                                  "userDescription" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "iOS"
                                  }
                                },
                                "ramSizeInMegabytes" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                }
                              },
                              "targetSDKRecord" : {
                                "_type" : {
                                  "_name" : "ActionSDKRecord"
                                },
                                "identifier" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "iphoneos17.0"
                                },
                                "name" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "iOS 17.0"
                                },
                                "operatingSystemVersion" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "17.0"
                                }
                              }
                            },
                            "schemeCommandName" : {
                              "_type" : {
                                "_name" : "String"
                              },
                              "_value" : "Run"
                            },
                            "schemeTaskName" : {
                              "_type" : {
                                "_name" : "String"
                              },
                              "_value" : "Build"
                            },
                            "startedTime" : {
                              "_type" : {
                                "_name" : "Date"
                              },
                              "_value" : "2023-09-06T20:00:00.593-0700"
                            },
                            "title" : {
                              "_type" : {
                                "_name" : "String"
                              },
                              "_value" : "Build \"Runner\""
                            }
                          }
                        ]
                      },
                      "issues" : {
                        "_type" : {
                          "_name" : "ResultIssueSummaries"
                        },
                        "warningSummaries" : {
                          "_type" : {
                            "_name" : "Array"
                          },
                          "_values" : [
                            {
                              "_type" : {
                                "_name" : "IssueSummary"
                              },
                              "documentLocationInCreatingWorkspace" : {
                                "_type" : {
                                  "_name" : "DocumentLocation"
                                },
                                "concreteTypeName" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "Xcode3ProjectDocumentLocation"
                                },
                                "url" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" :
                                  "file:\/\/\/Users\/james\/Development\/test\/ios\/Runner.xcodeproj#Timestamp=715748406.200129&XcodeLocation=%7B%22Selection%22:%7B%22Editor%22:%22Xcode3BuildSettingsEd
                                  itor%22,%22Target%22:%22Runner%22,%22Xcode3BuildSettingsEditorLocations%22:%5B%7B%22Selected%20Build%20Properties%22:%5B%22IPHONEOS_DEPLOYMENT_TARGET%22%5D%7D%5D%7D%7D
                                  "
                                }
                              },
                              "issueType" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Target Integrity"
                              },
                              "message" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.0.99."
                              }
                            }
                          ]
                        }
                      },
                      "metadataRef" : {
                        "_type" : {
                          "_name" : "Reference"
                        },
                        "id" : {
                          "_type" : {
                            "_name" : "String"
                          },
                          "_value" : "0~iMCnekqtyCIujMEwJaBiqIDVvGeNlg2MHaW1EIJ4lRofHJ3eue_KpupTMiTbql1-iLp4DJPKZa8PPSQLd_yaWg=="
                        },
                        "targetType" : {
                          "_type" : {
                            "_name" : "TypeDefinition"
                          },
                          "name" : {
                            "_type" : {
                              "_name" : "String"
                            },
                            "_value" : "ActionsInvocationMetadata"
                          }
                        }
                      },
                      "metrics" : {
                        "_type" : {
                          "_name" : "ResultMetrics"
                        },
                        "warningCount" : {
                          "_type" : {
                            "_name" : "Int"
                          },
                          "_value" : "1"
                        }
                      }
                    }
[   +6 ms] executing: rsync -8 -av --delete /Users/james/Development/test/build/ios/Profile-iphoneos/Runner.app /Users/james/Development/test/build/ios/iphoneos
[  +14 ms] building file list ... done
           Runner.app/
           Runner.app/Info.plist
           Runner.app/Runner
           Runner.app/_CodeSignature/CodeResources

           sent 139298 bytes  received 92 bytes  278780.00 bytes/sec
           total size is 31427512  speedup is 225.46
[   +1 ms] Installing and launching...
[        ] Debugging is enabled, connecting to vmService
[   +2 ms] You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security >
Automation.
[   +1 ms] executing: /usr/bin/xcode-select --print-path
[   +5 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode-beta.app/Contents/Developer
[        ] executing: /usr/bin/arch -arm64e xcrun osascript -l JavaScript /Users/james/Development/flutter/packages/flutter_tools/bin/xcode_debug.js check-workspace-opened --xcode-path
/Applications/Xcode-beta.app --project-path /Users/james/Development/test/ios/Runner.xcodeproj --workspace-path /Users/james/Development/test/ios/Runner.xcworkspace --verbose
[ +119 ms] {"status":false,"errorMessage":"Xcode is not running","debugResult":null}

                    {"command":"check-workspace-opened","xcodePath":"/Applications/Xcode-beta.app","projectPath":"/Users/james/Development/test/ios/Runner.xcodeproj","workspacePath":"/Users/james/Devel
                    opment/test/ios/Runner.xcworkspace","targetDestinationId":null,"targetSchemeName":null,"skipBuilding":null,"launchArguments":null,"closeWindowOnStop":null,"promptToSaveBeforeClose":
                    null,"verbose":true}
[        ] Error checking if project opened in Xcode: Xcode is not running
[        ] executing: open -a /Applications/Xcode-beta.app -g -j /Users/james/Development/test/ios/Runner.xcworkspace
[  +80 ms] executing: /usr/bin/arch -arm64e xcrun osascript -l JavaScript /Users/james/Development/flutter/packages/flutter_tools/bin/xcode_debug.js debug --xcode-path /Applications/Xcode-beta.app
--project-path /Users/james/Development/test/ios/Runner.xcodeproj --workspace-path /Users/james/Development/test/ios/Runner.xcworkspace --device-id 00008110-0004752E3AB8801E --scheme Runner
--skip-building --launch-args ["--enable-dart-profiling"] --verbose
[  +47 ms] stderr:
{"command":"debug","xcodePath":"/Applications/Xcode-beta.app","projectPath":"/Users/james/Development/test/ios/Runner.xcodeproj","workspacePath":"/Users/james/Development/test/ios/Runner.xcworkspace","
targetDestinationId":"00008110-0004752E3AB8801E","targetSchemeName":"Runner","skipBuilding":true,"launchArguments":["--enable-dart-profiling"],"closeWindowOnStop":null,"promptToSaveBeforeClose":null,"v
erbose":true}
[+8646 ms] stderr: Workspace: /Users/james/Development/test/ios/Runner.xcworkspace
[+2831 ms] stderr: Device: My Mac (00006000-000E28E90238801E)
[  +94 ms] stderr: Device: Apollo (00008110-0004752E3AB8801E)
[ +144 ms] stderr: Action result status: running
[ +523 ms] {"status":true,"errorMessage":null,"debugResult":{"completed":true,"status":"succeeded","errorMessage":null}}
[   +1 ms] Unexpected debug results: 
             Status: succeeded
             Completed: true
             Error Message: null
           
[   +1 ms] Could not run build/ios/iphoneos/Runner.app on 00008110-0004752E3AB8801E.
[        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Installing and launching... (completed in 12.5s)
[        ] Error running application on Apollo.
[   +1 ms] "flutter run" took 36,704ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +98 ms] ensureAnalyticsSent: 94ms
[   +2 ms] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 2
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.4.1 22F82 darwin-arm64, locale en-US)
    • Flutter version 3.13.2 on channel stable at /Users/james/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (2 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/james/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5229m
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Apollo (mobile) • 00008110-0004752E3AB8801E • ios            • iOS 17.0 21A5326a
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by vashworth**
Xcode uses the CONFIGURATION_BUILD_DIR build setting to determine the location of the bundle to build and install. When launching an app via Xcode with the Xcode debug workflow (for iOS 17 physical devices), temporarily set the CONFIGURATION_BUILD_DIR to the location of the bundle so Xcode can find it.

Also, added a Xcode Debug version of the `microbenchmarks_ios` integration test since it uses `flutter run --profile` without using `--use-application-binary`.

Fixes https://github.com/flutter/flutter/issues/134186.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/devicelab/bin/tasks/microbenchmarks_ios_xcode_debug.dart [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'package:flutter_devicelab/framework/devices.dart';
+import 'package:flutter_devicelab/framework/framework.dart';
+import 'package:flutter_devicelab/tasks/microbenchmarks.dart';
+
+/// Runs microbenchmarks on iOS.
+Future<void> main() async {
+  // TODO(vashworth): Remove after Xcode 15 and iOS 17 are in CI (https://github.com/flutter/flutter/issues/132128)
```
Comment (christopherfujino) [inline dev/devicelab/bin/tasks/microbenchmarks_ios_xcode_debug.dart:11]: Can you add this TODO to .ci.yaml? much harder to miss there.

File: dev/devicelab/lib/microbenchmarks.dart [hunk 2]
```diff
@@ -64,6 +64,11 @@ Future<Map<String, double>> readJsonResults(Process process) {
       // See https://github.com/flutter/flutter/issues/19208
       process.stdin.write('q');
       await process.stdin.flush();
+
+      // Give the process a couple of seconds to exit and run shutdown hooks
+      // before sending kill signal.
+      await Future<void>.delayed(const Duration(seconds: 2));
```
Comment (christopherfujino) [inline dev/devicelab/lib/microbenchmarks.dart:70]: has this been an issue, or are you adding this just in case?

Comment (christopherfujino) [reply dev/devicelab/lib/microbenchmarks.dart:70]: actually, reading the comment from lines 61-64, I actually fixed that in https://github.com/flutter/flutter/pull/99871.

Were there particular shutdown hooks you were concerned about?

Comment (vashworth) [reply dev/devicelab/lib/microbenchmarks.dart:70]: It was an issue when I ran the test locally because the shutdown hook which kills Xcode wasn't being triggered because the kill signal was sent before the `q` input could even be processed. 

I don't know if it's been an issue in the past

Comment (vashworth) [reply dev/devicelab/lib/microbenchmarks.dart:70]: This is the shutdown hook I was having issues with: https://github.com/vashworth/flutter/blob/master/packages/flutter_tools/lib/src/ios/devices.dart#L868-L871

Comment (christopherfujino) [reply dev/devicelab/lib/microbenchmarks.dart:70]: so actually, do we run the shutdownHooks when we send `q`? Let me check.

Comment (vashworth) [reply dev/devicelab/lib/microbenchmarks.dart:70]: Yes, shutdown hooks are run when we send `q`. 

It seems like shutdown hooks aren't run when you send a sigint kill signal

Comment (christopherfujino) [reply dev/devicelab/lib/microbenchmarks.dart:70]: well, this would be a serious bug, but anyway, this is fine as is for now, i'll file a tracking issue for us not handling SIGINT correctly.

Comment (christopherfujino) [inline dev/devicelab/lib/microbenchmarks.dart:70]:
```suggestion
      // TODO(fujino): https://github.com/flutter/flutter/issues/134566
      await Future<void>.delayed(const Duration(seconds: 2));
```

**Review by christopherfujino — APPROVED** [review]
lgtm

**Review by christopherfujino — APPROVED** [review]
still lgtm

**Comment by XilaiZhang** [comment]
ok great i redeployed frob and Google Testing is now propagating the correct information on merge conflict
