### PR TITLE
Fix crash when disposing nested Scrollables while holding in overscroll position

### LINKED ISSUE #27707: Disposing a (nested) Scrollable while holding in overscroll (iOS) may crash
```dart
void main() {
  runApp(new MaterialApp(
    home: Foo(),
  ));
}

class Foo extends StatefulWidget {
  @override
  FooState createState() => FooState();
}


class FooState extends State<Foo> {

  bool show = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: show ? Demo() : Container(),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            show = !show;
          });
        },
      ),
    );
  }
}

class Demo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: Container(
        width: 500.0,
        child: ListView.builder(
          itemBuilder: (BuildContext context, int index) {
            return Container(
              color: index % 2 == 0 ? Colors.red : Colors.green,
              height: 200.0,
              child: Text('Hello $index'),
            );
          },
        ),
      ),
    );
  }
}
```

Execute this code on iOS (!) and drag the first tile down all the way to the bottom of the screen (this will cause "overscroll"). Let go of the finger that scrolled the tile down. Before the tile can bounce all they way back, press and hold another finger on the screen to prevent the tile from bouncing back to the top. With the finger still down, press the FAB to dispose the scroll view ==> 🔥 🔥 🔥 

```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: 'package:flutter/src/widgets/notification_listener.dart': Failed assertion: line 58 pos 12: 'target
flutter: != null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:58:12)
flutter: #3      ScrollActivity.dispatchScrollStartNotification (package:flutter/src/widgets/scroll_activity.dart:91:65)
flutter: #4      ScrollPosition.didStartScroll (package:flutter/src/widgets/scroll_position.dart:650:14)
flutter: #5      ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:642:7)
flutter: #6      ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:117:11)
flutter: #7      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:149:7)
flutter: #8      HoldScrollActivity.cancel (package:flutter/src/widgets/scroll_activity.dart:204:14)
flutter: #9      ScrollableState._handleDragCancel (package:flutter/src/widgets/scrollable.dart:508:12)
flutter: #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
flutter: #11     DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:242:9)
flutter: #12     OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:249:9)
flutter: #13     DragGestureRecognizer.rejectGesture (package:flutter/src/gestures/monodrag.dart:233:5)
flutter: #14     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:213:14)
flutter: #15     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:52:12)
flutter: #16     OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:184:13)
flutter: #17     OneSequenceGestureRecognizer.dispose (package:flutter/src/gestures/recognizer.dart:189:5)
flutter: #18     DragGestureRecognizer.dispose (package:flutter/src/gestures/monodrag.dart:278:11)
flutter: #19     RawGestureDetectorState.dispose (package:flutter/src/widgets/gesture_detector.dart:705:18)
flutter: #20     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3910:12)
flutter: #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1696:13)
flutter: #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #44     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #47     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #50     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #53     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #56     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #76     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
flutter: #77     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1705:25)
flutter: #78     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2359:27)
flutter: #79     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2191:15)
flutter: #80     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2358:7)
flutter: #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:702:18)
flutter: #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
flutter: #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
flutter: #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
flutter: #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
flutter: #89     _invoke (dart:ui/hooks.dart:195:10)
flutter: #90     _drawFrame (dart:ui/hooks.dart:168:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: Handler: onCancel
flutter: Recognizer:
flutter:   VerticalDragGestureRecognizer#6ce8a(start behavior: down)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/27707, which has a detailed analysis.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/notification_listener.dart [hunk 1]
```diff
@@ -53,10 +53,10 @@ abstract class Notification {
   ///
   /// The notification will be delivered to any [NotificationListener] widgets
   /// with the appropriate type parameters that are ancestors of the given
-  /// [BuildContext].
+  /// [BuildContext]. If the [BuildContext] is null, the notification is
+  /// dropped on the floor.
   void dispatch(BuildContext target) {
-    assert(target != null); // Only call dispatch if the widget's State is still mounted.
-    target.visitAncestorElements(visitAncestor);
+    target?.visitAncestorElements(visitAncestor);
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/notification_listener.dart]: It would be nice to briefly explain why target might be null here.

File: packages/flutter/lib/src/widgets/notification_listener.dart [hunk 2]
```diff
@@ -53,10 +53,10 @@ abstract class Notification {
   ///
   /// The notification will be delivered to any [NotificationListener] widgets
   /// with the appropriate type parameters that are ancestors of the given
-  /// [BuildContext].
+  /// [BuildContext]. If the [BuildContext] is null, the notification is
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/notification_listener.dart]: Although "dropped on the floor" is well understood (and kind of funny) it  might be better to say "then the notification is not dispatched".

**Review by HansMuller — APPROVED** [review]
LGTM
