### PR TITLE
Scrollable should restore its viewport dimensions when it reappears

### LINKED ISSUE #5856: Scrollable fails to restore its viewport dimensions when it reappears after a pop
To reproduce with the gallery:
- tap any demo
- go back to the home page
- scroll past the bottom

### PR DESCRIPTION
**Pull request by HansMuller**
When a scrollable is reactivated its dependenciesChanged() method recreates the scroll behavior.

The new scroll behavior needs to be configured with the viewport's current (contentExtent, containerExtent) dimensions.

Fixes #5856

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 1]
```diff
@@ -267,7 +269,12 @@ class ScrollableState<T extends Scrollable> extends State<T> {
   @override
   void dependenciesChanged() {
     _scrollBehavior = createScrollBehavior();
-    didUpdateScrollBehavior(scrollOffset);
+    final double updatedOffset = _scrollBehavior.updateExtents(
+      contentExtent: _contentExtent,
+      containerExtent: _containerExtent,
+      scrollOffset: scrollOffset
+    );
+    didUpdateScrollBehavior(updatedOffset);
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/scrollable.dart]: why not inline the updatedOffset?

**Comment by Hixie** [comment]
LGTM
