### PR TITLE
Fix a bug in the AnimatedChildSwitcher, add builders.

### LINKED ISSUE #16226: Enhance AnimatedChildSwitcher to animate using a builder
The current AnimatedChildSwitcher will do a cross-fade between two (or more) children as they are replaced during  the build step, but it's fixed to a FadeTransition, and center alignment.

Ideally, the animation that occurs should be determined by a builder that is given to the AnimatedChildSwitcher to animate size, alignment, rotation, etc.

### PR DESCRIPTION
**Pull request by gspencergoog**
This fixes a rendering problem in the AnimatedChildSwitcher where it would add a new "previous" child each time it rebuilt, and if you did it fast enough, all of them would disappear from the page.

It also expands the API for AnimatedChildSwitcher to allow you to specify your own transition and/or layout builder for the transition.

Fixes https://github.com/flutter/flutter/issues/16226

### CODE REVIEW

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 1]
```diff
@@ -10,21 +10,64 @@ import 'framework.dart';
...
+class AnimatedChildSwitcherLayoutData {
+  AnimatedChildSwitcherLayoutData(this.widget, this.animation);
+
+  /// The widget that is currently or used to be set as the widget's child.
+  Widget widget;
+
+  /// The animation describing the child's transition. It is transitioning in
+  /// if the animation is running forwards.
   final Animation<double> animation;
 }
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: You could make the _AnimatedChildSwitcherChildEntry implement AnimatedChildSwitcherLayoutData and then just pass the actual _AnimatedChildSwitcherChildEntry in instead of copying the data over.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 2]
```diff
@@ -10,21 +10,64 @@ import 'framework.dart';
...
+  final Animation<double> animation;
+}
+
+/// Represents a child that used to be set on the [AnimatedChildSwitcher.child]
+/// field, but is now in the process of transitioning out.
+class AnimatedChildSwitcherLayoutData {
+  AnimatedChildSwitcherLayoutData(this.widget, this.animation);
+
+  /// The widget that is currently or used to be set as the widget's child.
+  Widget widget;
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: presumably this should be final?

Comment (Hixie) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: or at least, just a getter?

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 3]
```diff
@@ -10,21 +10,64 @@ import 'framework.dart';
...
+
+  /// The animation describing the child's transition. It is transitioning in
+  /// if the animation is running forwards.
   final Animation<double> animation;
 }
 
-/// A widget that automatically does a [FadeTransition] between a new widget and
+/// The type of the builder used to generate custom transitions for
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Signature for...

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 4]
```diff
@@ -10,21 +10,64 @@ import 'framework.dart';
...
+/// [AnimatedChildSwitcher].
+///
+/// The [child] should be transitioned in when [animation] is running in the
+/// forward direction,
+typedef Widget AnimatedChildSwitcherTransitionBuilder(Widget child, Animation<double> animation);
+
+/// The type of the builder used to generate custom layouts for
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: ditto

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 5]
```diff
@@ -10,21 +10,64 @@ import 'framework.dart';
...
-/// one is fading in if they are swapped fast enough (i.e. before [duration]
-/// elapses).
+/// If they are swapped fast enough (i.e. before [duration] elapses), more than
+/// one previous child can exist and be transitioning out while the newest one
+/// is transitioning in.
+///
+/// If the "new" child is the same widget type as the "old" child, but with
+/// different parameters, then [AnimatedChildSwitcher] will *not* do a
+/// transition between them, since as far as the framework is concerned, they
+/// are essentially the same widget, and the existing widget can be updated with
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: strike "essentially"

Comment (Hixie) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: though then this reads a bit weird, since you are sometimes saying they're the same and sometimes saying they're different.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 6]
```diff
@@ -10,21 +10,64 @@ import 'framework.dart';
...
+/// the new parameters. If you wish to force the transition to occur, set a
+/// [Key] (typically a [UniqueKey] or [ValueKey], depending upon the desired
+/// behavior) on each child widget that you wish to be considered unique.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: probably not a UniqueKey. That would likely trigger the same bug you saw earlier.

Comment (Hixie) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: maybe only mention valuekey.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 7]
```diff
@@ -39,10 +82,14 @@ class AnimatedChildSwitcher extends StatefulWidget {
     this.child,
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: constructor docs are out of date

also constructor docs should say what it does

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 8]
```diff
@@ -62,8 +109,45 @@ class AnimatedChildSwitcher extends StatefulWidget {
   /// The duration over which to perform the cross fade using [FadeTransition].
   final Duration duration;
 
+  /// The builder function used to generate custom transitions for
+  /// [AnimatedChildSwitcher].
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: talk about the default, and maybe something about the contract here?

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 9]
```diff
@@ -62,8 +109,45 @@ class AnimatedChildSwitcher extends StatefulWidget {
...
+  final AnimatedChildSwitcherTransitionBuilder transitionBuilder;
+
+  /// The builder function used to generate custom child layouts for
+  /// [AnimatedChildSwitcher].
+  final AnimatedChildSwitcherLayoutBuilder layoutBuilder;
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: ditto

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 10]
```diff
@@ -125,31 +209,31 @@ class _AnimatedChildSwitcherState extends State<AnimatedChildSwitcher> with Tick
     super.dispose();
   }
 
+  bool get hasNewChild => widget.child != null;
+  bool get hasOldChild => _currentChild?.widget != null;
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: looks like _currentChild can never be false, since we set it in initState, so you can remove the `?`

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 11]
```diff
@@ -10,21 +10,64 @@ import 'framework.dart';
...
+
+  // The animation describing the child's transition, with the controller as
+  // its parent.
+  final Animation<double> animation;
+}
+
+/// Represents a child that used to be set on the [AnimatedChildSwitcher.child]
+/// field, but is now in the process of transitioning out.
+class AnimatedChildSwitcherLayoutData {
+  AnimatedChildSwitcherLayoutData(this.widget, this.animation);
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: missing docs

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 12]
```diff
@@ -10,21 +10,64 @@ import 'framework.dart';
...
   final AnimationController controller;
+
+  // The animation describing the child's transition, with the controller as
+  // its parent.
+  final Animation<double> animation;
+}
+
+/// Represents a child that used to be set on the [AnimatedChildSwitcher.child]
+/// field, but is now in the process of transitioning out.
+class AnimatedChildSwitcherLayoutData {
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: this class should have an opinion about whether widget can be null. if it can, this should be documented with emphasis, since that is likely to cause null derefs.

May be better to not call the callbacks when there's a null child?

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 13]
```diff
@@ -62,8 +109,45 @@ class AnimatedChildSwitcher extends StatefulWidget {
...
+  /// [AnimatedChildSwitcherLayoutBuilder].
+  static Widget defaultLayoutBuilder(List<AnimatedChildSwitcherLayoutData> children) {
+    return new Stack(
+      children: children.map<Widget>((AnimatedChildSwitcherLayoutData child) => child.widget).toList(),
+      alignment: Alignment.center,
+    );
+  }
 }
 
 class _AnimatedChildSwitcherState extends State<AnimatedChildSwitcher> with TickerProviderStateMixin {
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: addEntry's logic is a bit wrong for the case of _currentChild.widget == null. We should probably consider moving to a world where if widget.child is null, we set _currentChild to null rather than setting its widget to null and still creating a (useless) animation controller.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 10 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: unless you change the semantics as suggested above

Comment (Hixie) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: in which case you could just make this _currentChild != null

then you could use it directly in addEntry

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 14]
```diff
@@ -125,31 +209,31 @@ class _AnimatedChildSwitcherState extends State<AnimatedChildSwitcher> with Tick
...
   }
 
+  bool get hasNewChild => widget.child != null;
+  bool get hasOldChild => _currentChild?.widget != null;
+
   @override
   Widget build(BuildContext context) {
-    if (widget.child != _currentChild.widget) {
+    if (hasNewChild != hasOldChild || hasNewChild && !Widget.canUpdate(widget.child, _currentChild.widget)) {
       addEntry(true);
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: this should be in didUpdateWidget

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 15]
```diff
@@ -10,21 +10,64 @@ import 'framework.dart';
...
+///
+/// The [child] should be transitioned in when [animation] is running in the
+/// forward direction,
+typedef Widget AnimatedChildSwitcherTransitionBuilder(Widget child, Animation<double> animation);
+
+/// The type of the builder used to generate custom layouts for
+/// [AnimatedChildSwitcher].
+///
+/// The [children] should be positioned according to their corresponding animation.
+typedef Widget AnimatedChildSwitcherLayoutBuilder(List<AnimatedChildSwitcherLayoutData> children);
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: why isn't this just a list of Widgets?

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 16]
```diff
@@ -125,31 +205,36 @@ class _AnimatedChildSwitcherState extends State<AnimatedChildSwitcher> with Tick
...
     if (_currentChild != null) {
       children.add(
-        new FadeTransition(
-          opacity: _currentChild.animation,
-          child: _currentChild.widget,
+        new AnimatedChildSwitcherLayoutData(
+          widget.transitionBuilder(_currentChild.widget, _currentChild.animation),
+          _currentChild.animation,
         ),
       );
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: something else we need to do here is make sure we put keys on each of these children, otherwise the animations will get all messed up -- e.g. if you have animations A, B, and C running, then A ends and you take it out, without keys, B will be synced with A, C will be synced with B, and all of them will lose the state of any descendants.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 17]
```diff
@@ -125,31 +205,36 @@ class _AnimatedChildSwitcherState extends State<AnimatedChildSwitcher> with Tick
...
   @override
-  Widget build(BuildContext context) {
-    if (widget.child != _currentChild.widget) {
-      addEntry(true);
+  void didUpdateWidget(AnimatedChildSwitcher oldWidget) {
+    super.didUpdateWidget(oldWidget);
+    if (hasNewChild != hasOldChild || hasNewChild && !Widget.canUpdate(widget.child, _currentChild.widget)) {
+      addEntry(animate: true);
     }
-    final List<Widget> children = <Widget>[];
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: you need to update _currentChild.widget to the new widget.child if you don't add an entry.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 7 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Done

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 13 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Fixed.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 8 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Done.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 9 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Done.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 10 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Yeah, I updated it to the new semantics.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 17 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Wait, why? addEntry isn't called if there's not a new widget.child.  Maybe I just misunderstand this comment...

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 16 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: OK, but how can I do that if the transition builder is the one creating the children?  I can add it in the default, but not enforce it.

Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Should I use "KeyedSubtree" to do this?

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 2 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: If you do the thing above with the abstract class bla bla, you'll probably want it to be a getter in this interface, and a mutable field in the concrete subclass.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 16 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Yeah, KeyedSubtree. (Or pass the key to the child and require the contract to be that they must use the key, which is what AnimatedCrossFade does iirc, though that makes the API less nice.)

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 18]
```diff
@@ -10,39 +10,148 @@ import 'framework.dart';
 import 'ticker_provider.dart';
 import 'transitions.dart';
 
-class _AnimatedChildSwitcherChildEntry {
-  _AnimatedChildSwitcherChildEntry(this.widget, this.controller, this.animation);
+/// Represents a child that is, or was previously set on the
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: you either need an extra comma after "previously" or to remove the comma after "is", otherwise the sentence becomes "{Represents a child that is} or {was previously set on the [AnimatedChildSwitcher.child] field that needs to be laid out using a [AnimatedChildSwitcherLayoutBuilder].}", which makes no sense.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 19]
```diff
@@ -10,39 +10,148 @@ import 'framework.dart';
...
+/// [AnimatedChildSwitcher.child] field that needs to be laid out using a
+/// [AnimatedChildSwitcherLayoutBuilder].
+abstract class AnimatedChildSwitcherLayoutData {
+  /// The widget that is currently or previously was set as the widget's child,
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Either add the magic null factory constructor here (see the chip pr i submitted) if you want this to be an interface, or add a const constructor with the const constructor boilerplate if you want this to be a superclass (then use "extends" instead of "implements" below).

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 18 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Fixed.

Comment (Hixie) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: wait, i'm confused. I thought this was the interface you had to pass to the transition builder, but actually you only use it for the layout builder. Why not just pass the layout builder a `List<Widget>`?

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 20]
```diff
@@ -10,39 +10,135 @@ import 'framework.dart';
...
+
+  // The currently built transition for this child.
+  Widget transition;
 
+  // The animation controller for the child's transition.
   final AnimationController controller;
-  final Animation<double> animation;
+
+  // The widget's child at the time this entry was created or updated.
+  Widget widgetChild;
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: please keep the arguments, asserts, and fields in the same order.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 21]
```diff
@@ -10,39 +10,135 @@ import 'framework.dart';
...
+///
+/// The function should return a widget which wraps the given [child]. It may
+/// also use the [animation] to inform its transition. It must not return null.
+typedef Widget AnimatedChildSwitcherTransitionBuilder(Widget child, Animation<double> animation);
+
+/// Signature for builders used to generate custom layouts for
+/// [AnimatedChildSwitcher].
+///
+/// The [children] should be positioned according to their corresponding
+/// animation.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: this paragraph is now moot

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 22]
```diff
@@ -10,39 +10,135 @@ import 'framework.dart';
...
+/// If they are swapped fast enough (i.e. before [duration] elapses), more than
+/// one previous child can exist and be transitioning out while the newest one
+/// is transitioning in.
+///
+/// If the "new" child is the same widget type as the "old" child, but with
+/// different parameters, then [AnimatedChildSwitcher] will *not* do a
+/// transition between them, since as far as the framework is concerned, they
+/// are the same widget, and the existing widget can be updated with the new
+/// parameters. If you wish to force the transition to occur, set a [Key]
+/// (typically a [UniqueKey] or [ValueKey], depending upon the desired behavior)
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: unlikely that a UniqueKey is what one wants

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 23]
```diff
@@ -10,39 +10,135 @@ import 'framework.dart';
...
+///         mainAxisAlignment: MainAxisAlignment.center,
+///         children: <Widget>[
+///           new AnimatedChildSwitcher(
+///             duration: const Duration(milliseconds: 200),
+///             transitionBuilder: (Widget child, Animation<double> animation) {
+///               return new ScaleTransition(child: child, scale: animation);
+///             },
+///             child: new Text(
+///               '$count',
+///               key: new UniqueKey(), // Must have this to build a unique widget.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: This should be a `ValueKey<int>(count)`. Otherwise, rotating the phone (for instance) would cause the text to fade.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 24]
```diff
@@ -10,39 +10,135 @@ import 'framework.dart';
...
+///               textScaleFactor: 3.0,
+///             ),
+///           ),
+///           new RaisedButton(
+///             child: new Text('Click!'),
+///             onPressed: () {
+///               setState(() {
+///                 count++;
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: `+= 1`

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 25]
```diff
@@ -62,8 +158,58 @@ class AnimatedChildSwitcher extends StatefulWidget {
   /// The duration over which to perform the cross fade using [FadeTransition].
   final Duration duration;
 
+  /// The builder function used to generate custom transitions for
+  /// [AnimatedChildSwitcher].
+  ///
+  /// The default is [AnimatedChildSwitcher.defaultTransitionBuilder].
+  ///
+  /// See also:
+  ///   * [AnimatedChildSwitcherTransitionBuilder] for more information about
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: You need a blank line before the list.
Also, only indent the bullet by one, so that the text is indented by 3.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 20 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Sorry, got a little messed up there... Done.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 26]
```diff
@@ -10,39 +10,135 @@ import 'framework.dart';
...
+  // The widget's child at the time this entry was created or updated.
+  Widget widgetChild;
 }
 
-/// A widget that automatically does a [FadeTransition] between a new widget and
+/// Signature for builders used to generate custom transitions for
+/// [AnimatedChildSwitcher].
+///
+/// The [child] should be transitioned in when [animation] is running in the
+/// forward direction,
```
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Fixed.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 21 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Removed.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 22 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: ~~Oh? Why?  Isn't it going to generate a unique key each time, which is what the user might sometimes want here?  I can see cases where it might be onerous to collect all of the "values" and decide if the widget is different visually, and instead they just put a UniqueKey on it each time they swap it out.~~

Edit: I see from below why (fading when rotating, etc.).

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 23 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: OK.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 25 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Fixed, and below.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 27]
```diff
@@ -10,39 +10,134 @@ import 'framework.dart';
...
+/// ```dart
+/// class ClickCounter extends StatefulWidget {
+///   const ClickCounter({Key key}) : super(key: key);
+///
+///   @override
+///   _ClickCounterState createState() => new _ClickCounterState();
+/// }
+///
+/// class _ClickCounterState extends State<ClickCounter> {
+///   int count = 0;
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Convention for State vars is to make them _private.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 28]
```diff
@@ -53,17 +148,69 @@ class AnimatedChildSwitcher extends StatefulWidget {
   /// [duration].
   final Widget child;
 
+  /// The duration over which to perform the cross fade using [FadeTransition].
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: The duration of the transition from the old [child] value to the new one.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 29]
```diff
@@ -53,17 +148,69 @@ class AnimatedChildSwitcher extends StatefulWidget {
...
+  final Duration duration;
+
   /// The animation curve to use when fading in the current widget.
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: The animation curve to use when transitioning in [child].

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 30]
```diff
@@ -53,17 +148,69 @@ class AnimatedChildSwitcher extends StatefulWidget {
...
   final Curve switchInCurve;
 
   /// The animation curve to use when fading out the previous widgets.
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: The animation curve to use when transitioning the previous [child] out.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 31]
```diff
@@ -53,17 +148,69 @@ class AnimatedChildSwitcher extends StatefulWidget {
...
   final Curve switchOutCurve;
 
-  /// The duration over which to perform the cross fade using [FadeTransition].
-  final Duration duration;
+  /// The builder function used to generate custom transitions for
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: It would be more helpful to say what this builder function is for: A function that wraps the new [child] with an animation that transitions the [child] _in_ when the animation runs in the forward direction and _out_ when the animation runs in the reverse direction.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 32]
```diff
@@ -53,17 +148,69 @@ class AnimatedChildSwitcher extends StatefulWidget {
...
   @override
   _AnimatedChildSwitcherState createState() => new _AnimatedChildSwitcherState();
+
+  /// The default transition algorithm used by [AnimatedChildSwitcher].
+  ///
+  /// The new child is given a [FadeTransition] which increases opacity as
+  /// the animation goes from 0.0 to 1.0, and decreases when the animation is
+  /// reversed.
+  ///
+  /// This is the default value for [transitionBuilder]. It implements
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: It doesn't implement anything. If you want to make sure a link to AnimatedChildSwitcherTransitionBuilder ends on in the docs:

The default value for the [transitionBuilder], an [AnimatedChildSwitcherTransitionBuilder] function.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 33]
```diff
@@ -53,17 +148,69 @@ class AnimatedChildSwitcher extends StatefulWidget {
...
+  /// See also:
+  ///
+  ///  * [AnimatedChildSwitcherTransitionBuilder] for more information about
+  ///    how a transition builder should function.
+  final AnimatedChildSwitcherTransitionBuilder transitionBuilder;
+
+  /// The builder function used to generate custom child layouts for
+  /// [AnimatedChildSwitcher].
+  ///
+  /// The default is [AnimatedChildSwitcher.defaultLayoutBuilder].
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: It would be more helpful to say what this builder function is for:  A function that wraps all of the children that are in the midst of transitioning out and the [child] that's transitioning in, with a widget that lays all of them out.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 34]
```diff
@@ -73,10 +220,49 @@ class _AnimatedChildSwitcherState extends State<AnimatedChildSwitcher> with Tick
...
+        setState(() {
+          _children.remove(entry);
+        });
+        controller.dispose();
+      }
+    });
+    return entry;
+  }
+
+  void addEntry({@required bool animate}) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: If _newEntry is private, shouldn't addEntry be _addEntry?

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 35]
```diff
@@ -53,17 +148,69 @@ class AnimatedChildSwitcher extends StatefulWidget {
...
+  /// The default layout algorithm used by [AnimatedChildSwitcher].
+  ///
+  /// The new child is placed in a [Stack] that sizes itself to match the
+  /// largest of the child or a previous child. The children are centered on
+  /// each other.
+  ///
+  /// This is the default value for [layoutBuilder]. It implements
+  /// [AnimatedChildSwitcherLayoutBuilder].
+  static Widget defaultLayoutBuilder(List<Widget> children) {
+    return new Stack(
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Would it be worth special casing children.isEmpty and children.length == 1? Maybe Stack already handles those cases efficiently?

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 36]
```diff
@@ -73,10 +220,49 @@ class _AnimatedChildSwitcherState extends State<AnimatedChildSwitcher> with Tick
...
+        controller.dispose();
+      }
+    });
+    return entry;
+  }
+
+  void addEntry({@required bool animate}) {
+    if (widget.child == null) {
+      if (animate) {
+        if (_currentChild != null) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: I think you could flatten this into one if statement

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart [hunk 37]
```diff
@@ -73,10 +220,49 @@ class _AnimatedChildSwitcherState extends State<AnimatedChildSwitcher> with Tick
...
+          _currentChild.controller.reverse();
+          _children.add(_currentChild);
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Maybe assert that _children doesn't already contain _currentChild here.

**Review by HansMuller — APPROVED** [review]
The changes LGTM (looks like a very useful widget!). 

I have to admit that I couldn't follow all of the logic around _currentChild. A // comment that explained how it was used, what invariants it satisfied, would make it easier to read the code.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 27 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Ok. I didn't think that mattered as much in a private class.  Done.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 28 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Done.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 29 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Done, thanks for catching these.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 30 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Done.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 31 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Done.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 33 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Done.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 32 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Good point.  Done.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 35 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: It appears to be fairly efficient, but it does do some trivial work in the empty case that it could probably avoid. I added a special case inside of Stack for the empty case.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 34 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Done.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 37 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Done, and below.

File: packages/flutter/lib/src/widgets/animated_child_switcher.dart (hunk 36 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/animated_child_switcher.dart]: Done.

File: packages/flutter/lib/src/rendering/stack.dart [hunk 38]
```diff
@@ -480,6 +480,11 @@ class RenderStack extends RenderBox
     assert(_resolvedAlignment != null);
     _hasVisualOverflow = false;
     bool hasNonPositionedChildren = false;
+    if (childCount == 0) {
+      size = constraints.biggest;
+      assert(size.isFinite);
+      return;
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/stack.dart]: did you mean to add this block? it seems to be redundant with the code below, but if you meant it as an optimisation it seems to be in a weird place (since it makes earlier statements redundant in the short-circuited case).

Comment (Hixie) [reply packages/flutter/lib/src/rendering/stack.dart]: oh, i see the comment later about this.

We shouldn't add this kind of thing unless we have benchmarks showing it's actually a benefit.
If we do want to add it we should really do it seriously, which would mean putting it before the hasNonPositionedChildren, at least, and maybe before _resolve (and moving _hasVisualOverflow earlier), assuming _resolve doesn't do anything useful in the case of there being no children.

Also, the assert is redundant with the same assert in box.dart.

Comment (gspencergoog) [reply packages/flutter/lib/src/rendering/stack.dart]: OK, makes sense.  Want me to revert this?

Comment (gspencergoog) [reply packages/flutter/lib/src/rendering/stack.dart]: Or, I can follow up with the yak shave and do a performance analysis of Stack.

Comment (Hixie) [reply packages/flutter/lib/src/rendering/stack.dart]: Unless we have numbers showing that we need this, we should probably revert it, and if there's a performance concern, we can then do the yak shave.
