### PR TITLE
In Gradle Flutter task, correctly replace '\ ' with ' '.

### LINKED ISSUE #174043: Running the project does not compile the latest code version and instead, it shows an older version.
### Steps to reproduce

1. Create a new Flutter project (counter app; it doesn't matter though).
2. Run the project for the first time (Android Studio).
3. Make some changes, like adding new widgets or editing some texts.
4. Save the code so that it hot reloads. The UI is updated accordingly.
5. Close the app either by stopping the process from Android Studio or through the OS.
6. Run the project again.
7. You'll notice that the UI no longer matches the code. If it does match the code, then repeat steps 3-6.

This issue was introduced in version 3.32 and wasn't resolved since. I followed 2 issues, but the OPs didn't come back with more info. They most likely gave up and started running `flutter clean && flutter pub get` every time they re-run the app.
https://github.com/flutter/flutter/issues/169914
https://github.com/flutter/flutter/issues/171507

### Expected results

The app should always displays the latest version of the code irrespective of whether the changes were made during a previous session using hot reload or not.

### Actual results

The app shows a UI resembling an older version of the code.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most codae changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(title: 'Flutter Test page 2'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://drive.google.com/file/d/1Xdq6ww54OfsrlWAANA1hhZjCNeK35q1H/view?usp=drive_link

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...
D/FlutterJNI( 6454): Beginning load of flutter...
D/FlutterJNI( 6454): flutter (null) was loaded normally!
I/flutter ( 6454): [IMPORTANT:flutter/shell/platform/android/android_context_gl_impeller.cc(104)] Using the Impeller rendering backend (OpenGLES).
Debug service listening on ws://127.0.0.1:51111/AYH7KOyLRmg=/ws
Syncing files to device sdk gphone64 arm64...
D/ProfileInstaller( 6454): Installing profile for com.example.testing_app
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.35.1, on macOS 14.7.1 23H222 darwin-arm64, locale en-RO) [2.1s]
    • Flutter version 3.35.1 on channel stable at /Users/mihaiborcan/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 20f8274939 (5 days ago), 2025-08-14 10:53:09 -0700
    • Engine revision 1e9a811bf8
    • Dart version 3.9.0
    • DevTools version 2.48.0
    • Feature flags: enable-web, no-enable-linux-desktop, no-enable-macos-desktop, no-enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-lldb-debugging

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [3.4s]
    • Android SDK at /Users/mihaiborcan/Library/Android/sdk
    • Emulator version 36.1.9.0 (build_id 13823996) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1) [2.9s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [24ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.1) [24ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)

[✓] IntelliJ IDEA Ultimate Edition (version 2025.1.3) [22ms]
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available) [6.3s]
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 15 (API 35) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 139.0.7258.67
    ! Error: Browsing on the local area network for Maricica’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [268ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by mboetger**
Gradle does not like paths with '\ ' in them. 

Fixes: https://github.com/flutter/flutter/issues/174043

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

### CODE REVIEW

**Review by gmackall — APPROVED** [review]
LGTM, I think this should be easy to test by writing another test for `getSourceFiles` in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/src/test/kotlin/tasks/FlutterTaskHelperTest.kt#L106

Also discussed offline that this is a regression because the old groovy logic was using replaceAll which takes a regex
https://github.com/flutter/flutter/blob/ea121f8859e4b13e47a8f845e4586164519588bc/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L1816
and this was mistakenly replaced with a replacement method taking a string, so the escaping was no longer needed, which is the explanation of why this was a regression

**Comment by mboetger** [comment]
> his was mistakenly replaced with a replacement method taking a string, so the escaping was no longer needed, which is the explanation o

Added a test.  PTAL.

**Review by gmackall — APPROVED** [review]
LGTM!

**Review by jmagman — COMMENTED** [review]
Can we also update an existing integration test that create, builds, and validates a project to instead be created in a directory with a space in it?

File: packages/flutter_tools/gradle/src/test/kotlin/tasks/FlutterTaskHelperTest.kt [hunk 1]
```diff
@@ -140,6 +140,42 @@ class FlutterTaskHelperTest {
...
+        val mockFlutterTask = mockk<FlutterTask>()
+
+        every { project.files() } returns mockProjectFileCollection
+        every { project.files(any()) } returns mockProjectFileCollection
+
+        every { mockFlutterTask.intermediateDir } returns tempDir.toFile()
+        every { mockFlutterTask.getDependenciesFiles() } returns mockDependenciesFileCollection
+        val dependenciesFile =
+            tempDir
+                .resolve("${mockFlutterTask.intermediateDir}/flutter_build.d")
```
Comment (ash2moon) [inline packages/flutter_tools/gradle/src/test/kotlin/tasks/FlutterTaskHelperTest.kt]: Should we use File.seperator instead for these?

Comment (reidbaker) [reply packages/flutter_tools/gradle/src/test/kotlin/tasks/FlutterTaskHelperTest.kt]: +1

File: packages/flutter_tools/gradle/src/test/kotlin/tasks/FlutterTaskHelperTest.kt [hunk 2]
```diff
@@ -140,6 +140,42 @@ class FlutterTaskHelperTest {
         verify { project.files("pubspec.yaml") }
     }
 
+    @Test
+    fun `getSourceFiles correctly replaces spaces`(
```
Comment (reidbaker) [inline packages/flutter_tools/gradle/src/test/kotlin/tasks/FlutterTaskHelperTest.kt]:
```suggestion
    fun `getSourceFiles correctly replaces escaped spaces`(
```

**Review by reidbaker — APPROVED** [review]

**Review by gmackall — COMMENTED** [review]
Looks like there is a test actually failing on line 33 of `FlutterTaskHelperTest`, presumably because the method it is testing doesn't actually handle windows slashes properly:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/src/main/kotlin/tasks/FlutterTaskHelper.kt#L22

**Comment by mboetger** [comment]
> y because the method it is testing doesn't

Updated to use File.separator there too.

File: packages/flutter_tools/gradle/src/main/kotlin/tasks/FlutterTaskHelper.kt [hunk 3]
```diff
@@ -38,7 +38,7 @@ object FlutterTaskHelper {
             from("${flutterTask.intermediateDir}")
             if (flutterTask.buildMode == "release" || flutterTask.buildMode == "profile") {
                 flutterTask.targetPlatformValues!!.forEach { targetArch ->
-                    include("${FlutterPluginConstants.PLATFORM_ARCH_MAP[targetArch]}/app.so")
+                    include("${FlutterPluginConstants.PLATFORM_ARCH_MAP[targetArch]}${File.separator}app.so")
```
Comment (mboetger) [inline packages/flutter_tools/gradle/src/main/kotlin/tasks/FlutterTaskHelper.kt:41]: @gmackall - wondering if this should be File.sparator or not.

Comment (gmackall) [reply packages/flutter_tools/gradle/src/main/kotlin/tasks/FlutterTaskHelper.kt:41]: Sorry I didn't see this, I would assume all slashes should be `File.separator` unless it breaks stuff (so yes probably)
