### PR TITLE
Fix DropdownButtonFormField clips text when large text scale is used

### LINKED ISSUE #159971: DropdownButtonFormField clips text when large text scale is used and useMaterial3 is true
### Steps to reproduce

1. Run the code sample.
2. Observe the dropdown button visible text.

### Expected results

image

### Actual results

image

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

const List<String> menuItems = <String>['one', 'two', 'three', 'four'];

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Builder(
          builder: (BuildContext context) => MediaQuery.withClampedTextScaling(
            minScaleFactor: 3.0,
            maxScaleFactor: 3.0,
            child: Material(
              child: Center(
                child: SizedBox(
                  width: 200,
                  child: DropdownButtonFormField<String>(
                    value: 'two',
                    onChanged: (_) {},
                    items: menuItems.map<DropdownMenuItem<String>>((String item) {
                      return DropdownMenuItem<String>(
                        key: ValueKey<String>(item),
                        value: item,
                        child: Text(
                          item,
                          key: ValueKey<String>('${item}Text'),
                        ),
                      );
                    }).toList(),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}



```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel master, 3.27.0-1.0.pre.740, on Ubuntu 24.04.1 LTS 6.8.0-49-generic
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes `DropdownButtonFormField`  text being clipped when using a large text scale.

Before:

image

After:

image

This extend the fix from https://github.com/flutter/flutter/pull/107201 which does not work properly with Material 3 (because of TextStyle.height being set for M3 default text styles).

## Related Issue

Fixes [DropdownButtonFormField clips text when large text scale is used and useMaterial3 is true](https://github.com/flutter/flutter/issues/159971)

## Tests

Adds 1 test.
Updates 1 test.

### CODE REVIEW

**Comment by bleroux** [comment]
@justinmc This fix will help to land https://github.com/flutter/flutter/pull/159328 because part of https://github.com/flutter/flutter/pull/159328 is trying to not break the test that this PR updates.

Despite being titled "DropdownButtonFormField with isDense:true does not clip large scale text", the text in the previous test was clipped because of M3 line height so it leads to potential issues related to baseline (https://github.com/flutter/flutter/issues/159431).

With this fix, https://github.com/flutter/flutter/pull/159328, can be simplified and might be easier to land.

File: packages/flutter/lib/src/material/dropdown.dart [hunk 1]
```diff
@@ -1441,7 +1441,8 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
   // would be clipped.
   double get _denseButtonHeight {
     final double fontSize = _textStyle!.fontSize ?? Theme.of(context).textTheme.titleMedium!.fontSize!;
-    final double scaledFontSize = MediaQuery.textScalerOf(context).scale(fontSize);
+    final double lineHeight = _textStyle!.height ?? Theme.of(context).textTheme.titleMedium!.height ?? 1.0;
+    final double scaledFontSize = MediaQuery.textScalerOf(context).scale(fontSize * lineHeight);
```
Comment (justinmc) [inline packages/flutter/lib/src/material/dropdown.dart:1445]: Good catch, I guess we just missed the lineHeight before.

**Review by justinmc — APPROVED** [review]
LGTM :+1: . Good call doing this separately from https://github.com/flutter/flutter/pull/159328, hopefully it helps.

**Comment by bleroux** [comment]
@justinmc Are there many Google test failures?
My bet is that some existing code is relying on the bug as depending on the font size and the content of the dropdown (for instance no letters such as g,y,j, ect) the rendering might be better before.

**Comment by justinmc** [comment]
The Google test failures are relatively few, all of them are expected improvements that look just like your before/after screenshots, except for one where the dropdown appears to be open now when it was not before! Any thoughts on why that might happen? I wonder if it was a click that previously was outside of the dropdown, but now that the dropdown is slightly taller, the click hits it?

Also of note, I don't see any instances where a reduced horizontal space has resulted in a change in the text displayed in the dropdown, like I noticed in https://github.com/flutter/flutter/pull/159328. That's good.

If you can't think of any reason for the open dropdown, the next step might be for us to get in touch with the team that owns that test.

**Comment by bleroux** [comment]
Many thanks for the feedback. :pray: 

> except for one where the dropdown appears to be open now when it was not before! Any thoughts on why that might happen? I wonder if it was a click that previously was outside of the dropdown, but now that the dropdown is slightly taller, the click hits it?

The only reason which come to my mind is the one you described. This change can impact the dropdown height (normally only when bigger font or scale factor are used) so depending on how the test is written that can be a misclick, especially if there several dropdowns in the same screen and each of them is taller than before.

This is not a high priority issue, so I will mark it as a draft and we can revisit this after the holidays.

**Comment by Piinks** [comment]
@bleroux could you rebase this to fix the current failures? Thanks!

**Comment by justinmc** [comment]
I'm planning to follow up on this next week. I've been trying to track down help and waiting to hear back.

**Comment by justinmc** [comment]
An affected Google test has been updated and I've started a re-run of the Google tests. I still expect the Google tests to fail, but hopefully they will all be expected failures this time.

**Review by justinmc — APPROVED** [review]
All Google test failures are expected, renewing my LGTM here 👍 . @bleroux feel free to merge when you're ready.
