### PR TITLE
Adds sdf rrects (and fixes opacity + color source)

### LINKED ISSUE #183038: Add RRect SDF renderer to uber shader
Implement `drawRRect()` (rounded rectangles) using SDFs to eliminate artifacts when the SDF renderer is enabled.

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/183038

This also fixes a bug in the color source rendering where if the opacity was something other than 1.0 the opacity value would get doubled.  This is avoided by overwriting the opacity value used by the uber sdf.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

If this change needs to override an active code freeze, provide a comment explaining why. The code freeze workflow can be overridden by code reviewers. See pinned issues for any active code freezes with guidance.

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[AI contribution guidelines]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#ai-contribution-guidelines
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/impeller/display_list/canvas.cc [hunk 1]
```diff
@@ -952,6 +960,31 @@ void Canvas::DrawRoundRect(const RoundRect& round_rect, const Paint& paint) {
     }
   }
 
+  const RoundingRadii& radii = round_rect.GetRadii();
+
+  if (renderer_.GetContext()->GetFlags().use_sdfs &&
+      !paint.mask_blur_descriptor.has_value() && AreCornersCircular(radii)) {
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/display_list/canvas.cc:976]: I'll file a followup issue for non-circular corners.  I'm not sure how high of a priority that is though.

**Comment by gaaclarke** [comment]
The crosses in `FilledRoundRectPathsRenderCorrectly` look much more transparent when drawn with the ubersdf shader.

**Comment by gaaclarke** [comment]
The differences in the colors has to do with drawing things when the paint has opacity (ex `paint.setColor(DlColor::kWhite().modulateOpacity(0.5));`)

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag [hunk 2]
```diff
@@ -50,11 +51,20 @@ float distanceFromChamferRect(vec2 p, vec2 b, float chamfer) {
   return length(d);
 }
 
+float distanceFromRoundedRect(in vec2 p, in vec2 b, in vec4 r) {
```
Comment (walley892) [inline engine/src/flutter/impeller/entity/shaders/uber_sdf.frag:143]: Why are these explicitly declared as `in`?

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag [hunk 3]
```diff
@@ -50,11 +51,20 @@ float distanceFromChamferRect(vec2 p, vec2 b, float chamfer) {
...
+  r.xy = (p.x > 0.0) ? r.xy : r.zw;
+  r.x = (p.y > 0.0) ? r.x : r.y;
+  vec2 q = abs(p) - b + r.x;
+  return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r.x;
+}
```
Comment (walley892) [inline engine/src/flutter/impeller/entity/shaders/uber_sdf.frag:148]: I find this difficult to parse - could you add some comments explaining the math here?

File: engine/src/flutter/impeller/display_list/canvas.cc [hunk 4]
```diff
@@ -1949,11 +1961,19 @@ void Canvas::DrawTextFrame(const std::shared_ptr<TextFrame>& text_frame,
...
-    std::shared_ptr<ColorSourceContents> contents) {
+void Canvas::AddRenderSDFEntityToCurrentPass(const Paint& paint,
+                                             UberSDFParameters params) {
+  Entity entity;
+  entity.SetTransform(GetCurrentTransform());
+  entity.SetBlendMode(paint.blend_mode);
+
+  if (paint.color_source) {
+    params.color = Color::White();
+  }
```
Comment (walley892) [inline engine/src/flutter/impeller/display_list/canvas.cc:1987]: Is it possible to instead fix this in the ApplyColorFilter or add a comment here about the dependent logic?

**Review by walley892 — DISMISSED** [review]
Couple of comments

File: engine/src/flutter/impeller/entity/contents/uber_sdf_parameters.cc [hunk 5]
```diff
@@ -47,4 +47,25 @@ UberSDFParameters UberSDFParameters::MakeCircle(
...
+    const Rect& rect,
+    const Vector4& radii,
+    std::optional<StrokeParameters> stroke) {
+  Point size = Point(rect.GetSize() * 0.5f);
+
+  std::optional<StrokeParameters> adjusted_stroke =
+      stroke && stroke->join == Join::kMiter && stroke->miter_limit < kSqrt2
+          ? std::make_optional(StrokeParameters(
+                {.width = stroke->width, .join = Join::kBevel}))
+          : stroke;
```
Comment (b-luk) [inline engine/src/flutter/impeller/entity/contents/uber_sdf_parameters.cc]: I don't think this is needed. Stroke join type isn't applicable for rounded rects, right?

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag (hunk 3 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/shaders/uber_sdf.frag:148]: The formula is exactly from https://iquilezles.org/articles/distfunctions2d/. I think it would be fine to just cite where it came from and document the input parameters, and not have to explain the math.

File: engine/src/flutter/impeller/display_list/canvas.cc (hunk 4 above)
Comment (b-luk) [reply engine/src/flutter/impeller/display_list/canvas.cc:1987]: +1

File: engine/src/flutter/impeller/display_list/canvas.cc [hunk 6]
```diff
@@ -952,6 +956,23 @@ void Canvas::DrawRoundRect(const RoundRect& round_rect, const Paint& paint) {
...
+  const RoundingRadii& radii = round_rect.GetRadii();
+
+  if (renderer_.GetContext()->GetFlags().use_sdfs &&
+      !paint.mask_blur_descriptor.has_value() && AreCornersCircular(radii)) {
+    auto params = UberSDFParameters::MakeRoundedRect(
+        /*color=*/paint.color,
+        /*rect=*/round_rect.GetBounds(),
+        /*radii=*/
+        Vector4(radii.top_left.width, radii.top_right.width,
+                radii.bottom_left.width, radii.bottom_right.width),
```
[the remark this answers is not in the document]
Comment (b-luk) [reply engine/src/flutter/impeller/display_list/canvas.cc]: According to https://www.shadertoy.com/view/4llXD7, the radius order of the shader function is top-right, bottom-right, top-left, bottom-left.

I don't know if our y axis is inverted compared to what that is using, so we may need to switch top/bottom. But either way, the ordering used here seems incorrect.

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag (hunk 3 above)
Comment (walley892) [reply engine/src/flutter/impeller/entity/shaders/uber_sdf.frag:148]: I would prefer to have an understanding of the math here rather than punt and rely on someone else's implementation/documentation

File: engine/src/flutter/impeller/display_list/canvas.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (gaaclarke) [reply engine/src/flutter/impeller/display_list/canvas.cc]: These are correct, otherwise our golden tests would fail.  I've validated it manually too.

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag (hunk 2 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/shaders/uber_sdf.frag:143]: There's no functional reason.  It's just explicit, matching the source, https://iquilezles.org/articles/distfunctions2d/.

File: engine/src/flutter/impeller/entity/contents/uber_sdf_parameters.cc (hunk 5 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/contents/uber_sdf_parameters.cc]: Yea, I think that's right, removed.

File: engine/src/flutter/impeller/display_list/canvas.cc (hunk 4 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/display_list/canvas.cc:1987]: ApplyColorFilter is performing a different transform.  I added a comment.

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag (hunk 3 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/shaders/uber_sdf.frag:148]: Added comment.  Anywhere where the guy has listed "exact" he has a mathmatical proof for the function.

Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/shaders/uber_sdf.frag:148]: > I would prefer to have an understanding of the math here rather than punt and rely on someone else's implementation/documentation

Inigo Quilez is a respected and known graphics engineer.  It's fine to incorporate his work.  I've added his copyright to this function and updated the licenses file.

File: engine/src/flutter/impeller/display_list/canvas.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (b-luk) [reply engine/src/flutter/impeller/display_list/canvas.cc]: I'm still kind of doubtful. The first line of the SDF is `  r.xy = (p.x > 0.0) ? r.xy : r.zw;`. (p is the position relative to center, and r is the vector of radii). So it's mirroring the x < 0 half-plane to the right by swapping r.xy = r.zw when x is negative. This makes sense if r.zw are the left corners and r.xy are the right corners. But if r is TL, TR, BL, BR, this seems like it would be swapping top/bottom corners instead of left/right corners.

I'll think about this some more or try to test it out myself.

[the remark this answers is not in the document]
Comment (b-luk) [reply engine/src/flutter/impeller/display_list/canvas.cc]: Patch to change `CanRenderRoundedRectWithNonUniformRadii` test to use circular radii, so it is compatible with UberSDF:
```
diff --git a/engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc b/engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc
index 707ba046de3..4fc4c9e77a2 100644
--- a/engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc
+++ b/engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc
@@ -463,10 +463,10 @@ TEST_P(AiksTest, CanRenderRoundedRectWithNonUniformRadii) {
   paint.setColor(DlColor::kRed());

   RoundingRadii radii = {
-      .top_left = DlSize(50, 25),
-      .top_right = DlSize(25, 50),
-      .bottom_left = DlSize(25, 50),
-      .bottom_right = DlSize(50, 25),
+      .top_left = DlSize(0, 0),
+      .top_right = DlSize(20, 20),
+      .bottom_left = DlSize(100, 100),
+      .bottom_right = DlSize(200, 200),
   };
   DlRoundRect rrect =
       DlRoundRect::MakeRectRadii(DlRect::MakeXYWH(100, 100, 500, 500), radii);
```

Metal test:
image

MetalSDF test:
image

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag [hunk 7]
```diff
@@ -50,11 +51,48 @@ float distanceFromChamferRect(vec2 p, vec2 b, float chamfer) {
...
+// WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
+// TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
+// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
+// FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
+// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
+// THE USE OR OTHER DEALINGS IN THE SOFTWARE.
+// https://www.youtube.com/c/InigoQuilez
+// https://iquilezles.org
+
+float distanceFromRoundedRect(in vec2 p, in vec2 b, in vec4 r) {
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/shaders/uber_sdf.frag:143]: In a followup PR I think we should sort these out into their own file, sdf.glsl.

File: engine/src/flutter/impeller/display_list/canvas.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (gaaclarke) [reply engine/src/flutter/impeller/display_list/canvas.cc]: Arg, you're right.  My test was falling down the mesh path.  I'll fix it, thanks.

[the remark this answers is not in the document]
Comment (gaaclarke) [reply engine/src/flutter/impeller/display_list/canvas.cc]: Done.

File: engine/src/flutter/impeller/entity/contents/uber_sdf_parameters.h [hunk 8]
```diff
@@ -52,6 +61,10 @@ struct UberSDFParameters {
 
   /// The stroke parameters. If std::nullopt, the shape is filled.
   std::optional<StrokeParameters> stroke;
+
+  /// The corner radii for a rounded rectangle.
+  /// Only used if type is kRoundedRect.
+  Vector4 radii;
```
Comment (b-luk) [inline engine/src/flutter/impeller/entity/contents/uber_sdf_parameters.h]: What do you think about making this a `RoundingRadii`, and having UberSDFContents convert this to fraginfo.radii. This way the specific corner ordering used in the SDF isn't exposed to callers like in canvas.cc

Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/contents/uber_sdf_parameters.h]: I don't imagine there will be any more clients of this API and we have a test for it now so I don't think it's huge risk.  I want `Vector4 radii` to be reusable since it could have other meaning for different shapes.  Somewhere in the middle would be to make the Make() argument be of type `RoundingRadii` but the storage still in `Vector4`.  I can do that if you want.

Comment (b-luk) [reply engine/src/flutter/impeller/entity/contents/uber_sdf_parameters.h]: I'm not that concerned about the risk of the code being used incorrectly. I think the biggest reason to consider this change is to make the code easier to follow and more readable.

A "RoundingRadii" object is self contained and lets me not have to think about its implementation details when using it. A Vector4 on the other hand doesn't have any built in rules on what its different components will be used for. So it's more cognitive load to mentally keep track of what its terms mean depending on where it is eventually used. The shader has a specific parameter ordering that it uses these radii for which is related to its own SDF functions. Surfacing this parameter ordering up to clients in canvas.cc seems like leaking through abstraction layers, and just makes reading through the code a lot more cognitively heavy to me.

I see your point about maybe reusing `Vector4 radii` if we have other shapes in the future that require 4 radii. RoundingRadii would also be able to be reused in the same way, as long as the future shapes' radii correspond to TL/TR/BR/BL. I can't really imagine any shape which would have 4 radii but not have a concept of TL/TR/BR/BL for them. I think if something like that comes up, we can figure out how to implement it based on the specific case, but it shouldn't prevent us from keeping our current code simple.

> Somewhere in the middle would be to make the Make() argument be of type RoundingRadii but the storage still in Vector4

I think that would be a significant improvement. It would keep the radii ordering contained within the UberSDF classes, and not leak it to callers through UberSDFParameters' API.

However, I still prefer converting it in UberSDFContents::Render rather than in UberSDFParameters. UberSDFParameters has no knowledge of the shader code's inputs. It's only responsibility is holding state which can be converted to  shader inputs (FragInfo). UberSDFContents is responsible for converting the UberSDFParameters state to shader inputs.

We do a similar thing for other shader inputs: In UberSDFParameters, type is stored as an enum class, color is stored as a Color object, and stroke is stored as a StrokeParameters object. Then UberSDFContents converts type to a float, Color to a Vector4, and StrokeParameters to 3 floats (stroked, stroke_width, stroke_join) to be inputs to the shader. So UberSDFContents converting a RoundingRadii to the vec4 for FragInfo would be following this same pattern.

File: engine/src/flutter/impeller/display_list/canvas.cc [hunk 9]
```diff
@@ -185,6 +186,13 @@ static std::unique_ptr<EntityPassTarget> CreateRenderTarget(
   );
 }
 
+bool AreCornersCircular(const RoundingRadii& radii) {
+  return ScalarNearlyEqual(radii.top_left.width, radii.top_left.height) &&
+         ScalarNearlyEqual(radii.top_right.width, radii.top_right.height) &&
+         ScalarNearlyEqual(radii.bottom_left.width, radii.bottom_left.height) &&
+         ScalarNearlyEqual(radii.bottom_right.width, radii.bottom_right.height);
+}
+
```
Comment (b-luk) [inline engine/src/flutter/impeller/display_list/canvas.cc:195]: Should this be a method on RoundingRadii like other similar methods?

https://github.com/flutter/flutter/blob/2c50daf9203d714791a320c8c78a928253dff4ab/engine/src/flutter/impeller/geometry/rounding_radii.h#L47-L61?

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag [hunk 10]
```diff
@@ -50,11 +51,48 @@ float distanceFromChamferRect(vec2 p, vec2 b, float chamfer) {
   return length(d);
 }
 
+// Exact math for rounded rect.
+//
+// `p` is position relative to the center of the shape.
+// `b` is size of box with corners at the origin.
```
Comment (walley892) [inline engine/src/flutter/impeller/entity/shaders/uber_sdf.frag]: From https://www.shadertoy.com/view/4llXD7,  I think b is the half-size

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag [hunk 11]
```diff
@@ -50,11 +51,48 @@ float distanceFromChamferRect(vec2 p, vec2 b, float chamfer) {
...
+// `r` is radii for each corner in order [bottom_right, top_right, bottom_left,
+// top_left].
```
Comment (walley892) [inline engine/src/flutter/impeller/entity/shaders/uber_sdf.frag]: From https://www.shadertoy.com/view/4llXD7, I think the order is [top_right, bottom_right, top_left, bottom_left]

Comment (b-luk) [reply engine/src/flutter/impeller/entity/shaders/uber_sdf.frag]: The positive y axis for impeller points down. But on shadertoy it points up. So top/bottom is reversed for our shaders compared to those ones.

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag (hunk 10 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/shaders/uber_sdf.frag]: done, elaborated

File: engine/src/flutter/impeller/entity/contents/uber_sdf_parameters.h (hunk 8 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/contents/uber_sdf_parameters.h]: Done

File: engine/src/flutter/impeller/display_list/canvas.cc (hunk 9 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/display_list/canvas.cc:195]: The rule of thumb I kind of follow is that if there is only one client to a function it's better to keep it a free function, if there are more than one then put it in the class.  That avoids class bloat.

Comment (b-luk) [reply engine/src/flutter/impeller/display_list/canvas.cc:195]: SGTM

**Review by b-luk — DISMISSED** [review]

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag [hunk 12]
```diff
@@ -16,25 +16,14 @@ uniform FragInfo {
...
-}
-
-bool typeIsRect() {
-  return abs(frag_info.type - 1.0) < 0.01;
-}
-
-bool typeIsOval() {
-  return abs(frag_info.type - 2.0) < 0.01;
-}
-
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/shaders/uber_sdf.frag:37]: @walley892 I wasn't on the code review for this but wanted to draw your attention to me removing them.  While the functions remove some duplicate logic and make the code easier to read they are increasing the flop count which is meaningful in the fragment shader world.  You would be able to see the difference in malioc if it was isolated to one PR.  We could make them just do one flop like below but then someone would have to be careful to keep the order the same.  I opted to just keep it inline.

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag [hunk 13]
```diff
@@ -155,9 +182,14 @@ float strokedSDF(vec2 p) {
       outer = distanceFromRect(p, frag_info.size) - half_stroke;
     }
     inner = distanceFromRect(p, frag_info.size - half_stroke);
-  } else {
-    outer = distanceFromOval(p, frag_info.size) - half_stroke;
-    inner = distanceFromOval(p, frag_info.size) + half_stroke;
+  } else if (frag_info.type < 2.5) {  // Oval
+    float outer = distanceFromOval(p, frag_info.size) - half_stroke;
+    float inner = distanceFromOval(p, frag_info.size) + half_stroke;
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/shaders/uber_sdf.frag:187]: This is a little weird integration oddity.  It's not technically wrong but I clean it up in the next PR: https://github.com/flutter/flutter/pull/185160

**Comment by gaaclarke** [comment]
@b-luk I had to merge this to HEAD and resolve conflicts, it's mostly the same.  Please take a look.

File: engine/src/flutter/impeller/entity/shaders/uber_sdf.frag (hunk 13 above)
Comment (b-luk) [reply engine/src/flutter/impeller/entity/shaders/uber_sdf.frag:187]: no action needed, but I think the the correct integration is just using the same two lines from the original code here. There's no need to re-declare outer/inner or to return early here. The old code sets the existing variables, then uses the `return max(outer, -inner);` that's outside of this if/else chain.

You're redoing all of this in the next PR, so no need to change anything here.

**Review by b-luk — DISMISSED** [review]

**Review by walley892 — DISMISSED** [review]

**Comment by gaaclarke** [comment]
One golden looked goofy: `impeller_Play_AiksTest_FilledEllipsesRenderCorrectly_MetalSDF`.  This looks like the problem we had with rrects.  Since we had merge conflicts i can take a quick peek otherwise follow up in a different PR.

## before
984006b9607c8739f9ff557c4468a32e

## after
519a31d30cb23cda4e8ee5931b42abb7

**Comment by gaaclarke** [comment]
> One golden looked goofy: `impeller_Play_AiksTest_FilledEllipsesRenderCorrectly_MetalSDF`. This looks like the problem we had with rrects. Since we had merge conflicts i can take a quick peek otherwise follow up in a different PR.

Okay, turns out this actually is fixing the test.  We previously accepted a failure.  We need to remove that golden after this lands.

**Review by b-luk — APPROVED** [review]

**Comment by gaaclarke** [comment]
@b-luk @walley892 flar's refactor happened to collide with my PR before it landed so I'm coming to you yet again, hat in hand, to ask for a review.  The only difference is it uses flar's GetStroke function.

**Comment by b-luk** [comment]
> Okay, turns out this actually is fixing the test. We previously accepted a failure. We need to remove that golden after this lands.

Yes, all the different positive goldens make the diffs confusing. Should we actively try to mark every previous golden as untriaged whenever we merge a PR that updates a golden?

**Comment by gaaclarke** [comment]
> Yes, all the different positive goldens make the diffs confusing. Should we actively try to mark every previous golden as untriaged whenever we merge a PR that updates a golden?

That's not an absolute rule of thumb.  When the baseline of what is acceptable is changing we should.  For flux like with blurs and gradients where they look the same to the human eye, no.

**Comment by walley892** [comment]
The `impeller_Play_AiksTest_FilledEllipsesRenderCorrectly_MetalSDF` golden was changed by the oval PR https://github.com/flutter/flutter/pull/184903. This PR correctly fixes the alpha.

**Review by walley892 — APPROVED** [review]
