### PR TITLE
Fix autocomplete options height 

### LINKED ISSUE #79227: Autocomplete options widget
## Use case
I noticed that there is a blank space in the autocomplete prompts. It seems to me that this is not correct.
111995133-98a33c80-8b3e-11eb-83ff-06f90144b172
## Proposal
I replaced the widget in optionsViewBuilder with the code:

<details>
<summary>code sample</summary>

```dart
class _AutocompleteOptions<T extends Object> extends StatelessWidget {
  const _AutocompleteOptions({
    Key? key,
    required this.displayStringForOption,
    required this.onSelected,
    required this.options,
  }) : super(key: key);

  final AutocompleteOptionToString<T> displayStringForOption;

  final AutocompleteOnSelected<T> onSelected;

  final Iterable<T> options;

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.topLeft,
      child: Material(
        elevation: 4.0,
        child: ConstrainedBox(
          constraints: BoxConstraints(
            maxHeight: 200,
          ),
          child: SingleChildScrollView(
            child: ListView.builder(
              shrinkWrap: true,
              physics: NeverScrollableScrollPhysics(),
              padding: EdgeInsets.zero,
              itemCount: options.length,
              itemBuilder: (BuildContext context, int index) {
                final T option = options.elementAt(index);
                return InkWell(
                  onTap: () {
                    onSelected(option);
                  },
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Text(displayStringForOption(option)),
                  ),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

Thus, we solve the problem of blank space.

### PR DESCRIPTION
**Pull request by maheshj01**
This pull request fixes the [Autocomplete Widget's](https://api.flutter.dev/flutter/material/Autocomplete-class.html) options height issue https://github.com/flutter/flutter/issues/79227 and adds a ```maxOptionsHeight``` property allowing user to configure the maximum height the  ```optionsViewBuilder``` can take.

Fixes https://github.com/flutter/flutter/issues/79227

### CODE REVIEW

**Comment by maheshmnj** [comment]
@justinmc let me know your thoughts on this PR would be happy to make the changes :)
Also, I couldn't understand from the logs why the flutter-build failed.

**Comment by maheshmnj** [comment]
@shihaohong can you please review this PR

**Review by shihaohong — COMMENTED** [review]
This PR would need tests to verify that the updated, intended behaviors are reflected.

**Comment by maheshmnj** [comment]
> This PR would need tests to verify that the updated, intended behaviors are reflected.

Thanks, I will add the tests to support this PR

**Comment by maheshmnj** [comment]
@shihaohong  I am not sure if I have to write tests in [widgets/autocomplete_test.dart](https://github.com/flutter/flutter/blob/ab5c0a3ad2a6f05bf14e6ed14842c4214af064b8/packages/flutter/test/widgets/autocomplete_test.dart)  as well

File: packages/flutter/lib/src/material/autocomplete.dart [hunk 1]
```diff
@@ -193,6 +194,12 @@ class Autocomplete<T extends Object> extends StatelessWidget {
   /// default.
   final AutocompleteOptionsViewBuilder<T>? optionsViewBuilder;
 
+  /// defines the maximum height the options can take
+  /// if optionsViewBuilder is null
+  ///
+  /// defaults to 200.0
```
Comment (pedromassango) [inline packages/flutter/lib/src/material/autocomplete.dart:200]: Docs should always start with upper case letter.

File: packages/flutter/test/material/autocomplete_test.dart [hunk 2]
```diff
@@ -20,6 +20,21 @@ class User {
   }
 }
 
+/// given a string input this method enters the string in the autocomplete field
```
Comment (pedromassango) [inline packages/flutter/test/material/autocomplete_test.dart:23]: Same here (upper case)

**Comment by pedromassango** [comment]
@maheshmnj It looks like there is some unrelated changes caused by your IDE/code editor, that is causing the analyzer test to fail, you have to revert those changes, it is basicaly remove empty spaces (custom formats) added by your IDE/code editor.

**Review by pedromassango — CHANGES_REQUESTED** [review]
@maheshmnj It looks like there is some unrelated changes caused by your IDE/code editor, that is causing the analyzer test to fail, you have to revert those changes, it is basicaly remove empty spaces (custom formats) added by your IDE/code editor.

File: packages/flutter/lib/src/material/autocomplete.dart (hunk 1 above)
Comment (maheshmnj) [reply packages/flutter/lib/src/material/autocomplete.dart:200]: thanks @pedromassango  by revert do you mean to revert the commit?
And is there any cli tool we can use to format the code  or it has to be done manually seems like we do not use ```dartfmt``` here ?

Comment (pedromassango) [reply packages/flutter/lib/src/material/autocomplete.dart:200]: I would suggest to just go over all the changes you've made and revert each unwanted change, that iw what I've been doing  back in the time (until I disabled auto-format).

Yes, the Flutter source code does not use dartfmt tool. I'm not aware of ny tool that could help with this. Let me know if you find any, I would like to use it as well :).

Comment (maheshmnj) [reply packages/flutter/lib/src/material/autocomplete.dart:200]: Thanks but can you point me to a doc(if any) where I could know what changes to revert (e.g you specified the upper case letter or extra space)?
or are these rules bases on the [Effective Dart](https://dart.dev/guides/language/effective-dart)

Comment (maheshmnj) [reply packages/flutter/lib/src/material/autocomplete.dart:200]: And one more thing is there a way we could run all the tests locally before pushing it here.

File: packages/flutter/test/material/autocomplete_test.dart [hunk 3]
```diff
@@ -254,50 +285,131 @@ void main() {
...
+    /// returns 2 Items (height < `maxOptionsHeight`)
+    /// so options height shrinks to 2 Items combined height
+    final double twoItemsHeight = await getOptionsHeight(tester, 'el');
+    expect(twoItemsHeight, lessThan(maxOptionsHeight));
+
+    /// returns 1 item (height < `maxOptionsHeight`) from `kOptions`
+    /// so options height shrinks to 1 items height
+    final double oneItemsHeight = await getOptionsHeight(tester, 'elep');
+    expect(oneItemsHeight, lessThan(twoItemsHeight));
+    testWidgets('initialValue sets initial text field value',
```
Comment (justinmc) [inline packages/flutter/test/material/autocomplete_test.dart:362]: This test is not formatted correctly, it looks like you're starting a new test within another test (started on line 329).

**Review by justinmc — COMMENTED** [review]
The tests are failing due to an improperly formatted test (see my comment).

For flutter_build, you don't have to worry about it.  It represents the status of the current Flutter build (without this PR).  We only allow PRs to be merged when it is green.  If it's red, someone is working on it, and you can just wait for it to turn green.

File: packages/flutter/test/material/autocomplete_test.dart (hunk 3 above)
Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart]: thanks seems like that nesting of tests happened during resolving the merge conflict

File: packages/flutter/lib/src/material/autocomplete.dart [hunk 4]
```diff
@@ -166,6 +166,7 @@ class Autocomplete<T extends Object> extends StatelessWidget {
     this.displayStringForOption = RawAutocomplete.defaultStringForOption,
     this.fieldViewBuilder = _defaultFieldViewBuilder,
     this.onSelected,
+    this.maxOptionsHeight=200.0,
```
Comment (pedromassango) [inline packages/flutter/lib/src/material/autocomplete.dart:169]: Nit: spacing between the equals sign.

File: packages/flutter/lib/src/material/autocomplete.dart [hunk 5]
```diff
@@ -193,6 +194,12 @@ class Autocomplete<T extends Object> extends StatelessWidget {
   /// default.
   final AutocompleteOptionsViewBuilder<T>? optionsViewBuilder;
 
+  /// Defines the maximum height the options can take
+  /// if optionsViewBuilder is null
+  ///
+  /// Defaults to 200.0
```
Comment (pedromassango) [inline packages/flutter/lib/src/material/autocomplete.dart:200]: Nit: period at the end of each paragraph. The last line could just be `Defaults to 200.`

File: packages/flutter/lib/src/material/autocomplete.dart [hunk 6]
```diff
@@ -193,6 +194,12 @@ class Autocomplete<T extends Object> extends StatelessWidget {
...
+  final double maxOptionsHeight;
```
Comment (pedromassango) [inline packages/flutter/lib/src/material/autocomplete.dart:201]: Suggestion:
What about `maxOptionsViewHeight`? Because it is the size of a widget, just to be more clear.

Cc @justinmc

File: packages/flutter/lib/src/material/autocomplete.dart (hunk 1 above)
Comment (pedromassango) [reply packages/flutter/lib/src/material/autocomplete.dart]: It seems fixed now

File: packages/flutter/lib/src/material/autocomplete.dart (hunk 6 above)
Comment (maheshmnj) [reply packages/flutter/lib/src/material/autocomplete.dart:201]: you mean maxOptionsViewHeight when optionsViewBuilder is assigned a custom widget? if yes
it's a custom widget user can pass  so I believe that should be constraints-free and should be left to user.

Comment (pedromassango) [reply packages/flutter/lib/src/material/autocomplete.dart:201]: Sorry, I meant to just improve the property name. We can leve it as-is (it was just a suggestion).

File: packages/flutter/test/material/autocomplete_test.dart [hunk 7]
```diff
@@ -44,7 +59,8 @@ void main() {
     User(name: 'Charlie', email: 'charlie123@gmail.com'),
   ];
 
-  testWidgets('can filter and select a list of string options', (WidgetTester tester) async {
+  testWidgets('can filter and select a list of string options',
```
Comment (shihaohong) [inline packages/flutter/test/material/autocomplete_test.dart:62]: Please revert these unrelated changed lines of code, here and below.

File: packages/flutter/test/material/autocomplete_test.dart [hunk 8]
```diff
@@ -254,50 +285,132 @@ void main() {
     expect(find.byKey(optionsKey), findsOneWidget);
   });
 
-  testWidgets('initialValue sets initial text field value', (WidgetTester tester) async {
-    late String lastSelection;
-    await tester.pumpWidget(
-      MaterialApp(
+  testWidgets('the options take maxSize as 200.0 if not specified',
```
Comment (shihaohong) [inline packages/flutter/test/material/autocomplete_test.dart:288]: It's not the size, it's the height that defaults to 200. We should be more clear:
```suggestion
  testWidgets('the default Autocomplete options widget has a maximum height of 200',
```

File: packages/flutter/test/material/autocomplete_test.dart [hunk 9]
```diff
@@ -254,50 +285,132 @@ void main() {
...
+      (WidgetTester tester) async {
+    const double defaultHeight = 200.0;
```
Comment (shihaohong) [inline packages/flutter/test/material/autocomplete_test.dart:290]: I don't think that this variable is particularly useful. Just use 200 below
```suggestion
```

File: packages/flutter/test/material/autocomplete_test.dart [hunk 10]
```diff
@@ -254,50 +285,132 @@ void main() {
...
+        optionsBuilder: (TextEditingValue textEditingValue) {
+          return kOptions.where((String option) {
+            return option.contains(textEditingValue.text.toLowerCase());
+          });
+        },
+      ),
+    )));
+
+    final double resultingHeight = await getOptionsHeight(tester, '');
+    expect(resultingHeight, equals(defaultHeight));
```
Comment (shihaohong) [inline packages/flutter/test/material/autocomplete_test.dart:302]:
```suggestion
    expect(resultingHeight, 200);
```

File: packages/flutter/test/material/autocomplete_test.dart [hunk 11]
```diff
@@ -20,6 +20,21 @@ class User {
   }
 }
 
+/// Given a string input this method enters the string in the autocomplete field
+/// and it returns the height of the resulting options
+Future<double> getOptionsHeight(WidgetTester tester, String text) async {
```
Comment (shihaohong) [inline packages/flutter/test/material/autocomplete_test.dart:25]: Make this private
```suggestion
Future<double> _getOptionsHeight(WidgetTester tester, String text) async {
```

Comment (shihaohong) [inline packages/flutter/test/material/autocomplete_test.dart:25]: Use a more specific variable name
```suggestion
Future<double> getOptionsHeight(WidgetTester tester, String enteredText) async {
```

Comment (shihaohong) [inline packages/flutter/test/material/autocomplete_test.dart:25]: More specific
```suggestion
Future<double> getDefaultOptionsHeight(WidgetTester tester, String text) async {
```

Comment (shihaohong) [reply packages/flutter/test/material/autocomplete_test.dart:25]: I'm also not sure if we want to have this function available throughout the entire file. Since this assumes that the default `Autocomplete` settings are used and that its `ListView` and `TextFormField` are the only widgets in the widget tree, this may not work given other widget tree configurations.

Maybe just expose the method in the particular test ('The height of options shrinks to height of resulting items, if less than maxHeight') and then just use the contents of the function directly in 'the default Autocomplete options widget has a maximum height of 200', since that test is already so short anyway.

**Review by shihaohong — CHANGES_REQUESTED** [review]
Some comments about the test file's formatting and the test setup and clarity.

File: packages/flutter/lib/src/material/autocomplete.dart [hunk 12]
```diff
@@ -193,6 +194,12 @@ class Autocomplete<T extends Object> extends StatelessWidget {
   /// default.
   final AutocompleteOptionsViewBuilder<T>? optionsViewBuilder;
 
+  /// Defines the maximum height the options can take
+  /// if optionsViewBuilder is null
+  ///
+  /// Defaults to 200.
+  final double maxOptionsHeight;
```
[the remark this answers is not in the document]
Comment (maheshmnj) [reply packages/flutter/lib/src/material/autocomplete.dart:201]: renamed the property

File: packages/flutter/lib/src/material/autocomplete.dart [hunk 13]
```diff
@@ -193,6 +194,12 @@ class Autocomplete<T extends Object> extends StatelessWidget {
   /// default.
   final AutocompleteOptionsViewBuilder<T>? optionsViewBuilder;
 
+  /// Defines the maximum height the options can take
+  /// if optionsViewBuilder is null
+  ///
+  /// Defaults to 200.
```
[the remark this answers is not in the document]
Comment (maheshmnj) [reply packages/flutter/lib/src/material/autocomplete.dart]: Okay done.

File: packages/flutter/test/material/autocomplete_test.dart (hunk 8 above)
Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart]: added more clear description

File: packages/flutter/test/material/autocomplete_test.dart (hunk 9 above)
Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart]: removed unnecessary variable

File: packages/flutter/test/material/autocomplete_test.dart (hunk 10 above)
Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart]: done

File: packages/flutter/test/material/autocomplete_test.dart [hunk 14]
```diff
@@ -20,6 +20,21 @@ class User {
   }
 }
 
+/// Given a string input this method enters the string in the autocomplete field
+/// and it returns the height of the resulting options
```
[the remark this answers is not in the document]
Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart]: done

File: packages/flutter/test/material/autocomplete_test.dart (hunk 11 above)
Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart]: renamed the variable name to be more specific

Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart]: moved the functional locally within the specific test block('The height of options shrinks to height of resulting items, if less than maxHeight') and for the other two tests copied the content of this method  for 
```the default Autocomplete options widget has a maximum height of 200```
and
```the options height restricts to max desired height```

File: packages/flutter/test/material/autocomplete_test.dart (hunk 14 above)
[the remark this answers is not in the document]
Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart]: using block comments over doc comments any specific reason?

File: packages/flutter/test/material/autocomplete_test.dart (hunk 11 above)
Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart]: done

File: packages/flutter/test/material/autocomplete_test.dart (hunk 7 above)
Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart:47]: @shihaohong  sorry I couldn't understand this change

Comment (shihaohong) [reply packages/flutter/test/material/autocomplete_test.dart:47]: Basically, this change is unrelated to the PR you're making, so please revert it to the original formatting

File: packages/flutter/test/material/autocomplete_test.dart [hunk 15]
```diff
@@ -89,7 +90,8 @@ void main() {
     await tester.pump();
     expect(find.byType(TextFormField), findsOneWidget);
     expect(find.byType(ListView), findsNothing);
-    final TextFormField field = find.byType(TextFormField).evaluate().first.widget as TextFormField;
+    final TextFormField field =
```
Comment (shihaohong) [inline packages/flutter/test/material/autocomplete_test.dart:93]: Here is another example of unrelated formatting change that should be reverted.

File: packages/flutter/test/material/autocomplete_test.dart (hunk 14 above)
[the remark this answers is not in the document]
Comment (shihaohong) [reply packages/flutter/test/material/autocomplete_test.dart]: `///` is usually reserved for doc comments, and since this is just comments in a unit test, it isn't a doc comment

**Comment by shihaohong** [comment]
The analyzer check is also failing:
```
Warning: transitive closure contained non-allowlisted packages:
[frontend_server_client]
See dev/bots/allowlist.dart for instructions on how to update the package allowlist.
```

It might be unrelated to your change, so maybe rebase your branch with the master branch and see if it resolved the error failure.

File: packages/flutter/test/material/autocomplete_test.dart (hunk 14 above)
[the remark this answers is not in the document]
Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart]: okay

File: packages/flutter/test/material/autocomplete_test.dart (hunk 7 above)
Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart]: thanks for clarification

**Comment by maheshmnj** [comment]
Thank you so much for the detailed review @shihaohong

File: packages/flutter/test/material/autocomplete_test.dart [hunk 16]
```diff
@@ -104,14 +104,17 @@ void main() {
     expect(list.semanticChildCount, 6);
   });
 
-  testWidgets('can filter and select a list of custom User options', (WidgetTester tester) async {
+  testWidgets('can filter and select a list of custom User options',
```
Comment (shihaohong) [inline packages/flutter/test/material/autocomplete_test.dart:107]: There are still more unrelated changes in this PR that need to be reverted. This is happening throughout the `autocomplete_test.dart` file probably due to the use of `dartfmt`.

Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart:107]: Ohh okay let  me take a look.
Sorry for all the mess

Comment (maheshmnj) [reply packages/flutter/test/material/autocomplete_test.dart]: Can you please review now.

File: packages/flutter/test/material/autocomplete_test.dart [hunk 17]
```diff
@@ -254,6 +254,104 @@ void main() {
...
+        home: Scaffold(
+      body: Autocomplete<String>(
+        optionsBuilder: (TextEditingValue textEditingValue) {
+          return kOptions.where((String option) {
+            return option.contains(textEditingValue.text.toLowerCase());
+          });
+        },
+        optionsMaxHeight: maxOptionsHeight,
+      ),
+    )));
```
Comment (shihaohong) [inline packages/flutter/test/material/autocomplete_test.dart:334]: indentations are off. we also tend to leave `child` as the last parameter to prevent trailing parameters in a list of parameters, and `optionsBuilder` is sort of the equivalent here.
```suggestion
    await tester.pumpWidget(MaterialApp(
      home: Scaffold(
      body: Autocomplete<String>(
        optionsMaxHeight: maxOptionsHeight,      
        optionsBuilder: (TextEditingValue textEditingValue) {
          return kOptions.where((String option) {
            return option.contains(textEditingValue.text.toLowerCase());
          });
        },
      ),
    )));
```

File: packages/flutter/test/material/autocomplete_test.dart [hunk 18]
```diff
@@ -254,6 +254,104 @@ void main() {
...
+        home: Scaffold(
+      body: Autocomplete<String>(
+        optionsBuilder: (TextEditingValue textEditingValue) {
+          return kOptions.where((String option) {
+            return option.contains(textEditingValue.text.toLowerCase());
+          });
+        },
+        optionsMaxHeight: desiredHeight,
+      ),
+    )));
```
Comment (shihaohong) [inline packages/flutter/test/material/autocomplete_test.dart:290]:
```suggestion
    await tester.pumpWidget(MaterialApp(
      home: Scaffold(
      body: Autocomplete<String>(
        optionsMaxHeight: desiredHeight,      
        optionsBuilder: (TextEditingValue textEditingValue) {
          return kOptions.where((String option) {
            return option.contains(textEditingValue.text.toLowerCase());
          });
        },
      ),
    )));
```

**Comment by maheshmnj** [comment]
@shihaohong I am not exactly sure why the Windows build_tests are failing looks like they are timing out.

**Review by shihaohong — APPROVED** [review]
LGTM

**Comment by shihaohong** [comment]
The windows tests seem to be unrelated to your change and is an infra failure (I think the related issue is https://github.com/flutter/flutter/issues/81837). We'll have to wait for it to be resolved before we can merge this PR

**Comment by maheshmnj** [comment]
> The windows tests seem to be unrelated to your change and is an infra failure (I think the related issue is #81837). We'll have to wait for it to be resolved before we can merge this PR

sure thanks again for the review

**Review by pedromassango — APPROVED** [review]
LGTM

**Comment by maheshmnj** [comment]
@shihaohong  looks like  #81837 is resolved. do I need to merge the latest master? In order for windowsbuild_tests_2_3 to pass

**Comment by pedromassango** [comment]
@maheshmnj  I think so
