### PR TITLE
Verbose process exceptions

### LINKED ISSUE #61486: [flutter_tools] give more verbose error logging when unzip fails
otherwise we don't know why unzip failed.

Related to https://github.com/flutter/flutter/issues/52437

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

Adds a bool parameter `verboseExceptions` to `.runSync()` and use it when calling `unzip` to get more details.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/61486

## Tests

I added a unit test

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/process.dart [hunk 1]
```diff
@@ -449,7 +451,12 @@ class _DefaultProcessUtils implements ProcessUtils {
     }
 
     if (failedExitCode && throwOnError) {
-      runResult.throwException('The command failed');
+      String message = 'The command failed';
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/base/process.dart:454]: Did you mean to check `verboseExceptions` somewhere?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/process.dart:454]: You're right, the `throwOnError` check here is redundant, since we already know it's true from the check on 453. This should be `if (verboseExceptions) {`. Added another unit test.

File: packages/flutter_tools/test/src/common.dart [hunk 2]
```diff
@@ -106,15 +106,17 @@ Matcher throwsToolExit({ int exitCode, Pattern message }) {
 /// Matcher for [ToolExit]s.
 final test_package.TypeMatcher<ToolExit> isToolExit = isA<ToolExit>();
 
-/// Matcher for functions that throw [ProcessExit].
-Matcher throwsProcessExit([ dynamic exitCode ]) {
```
Comment (christopherfujino) [inline packages/flutter_tools/test/src/common.dart:110]: this matcher was never used

**Review by jmagman — APPROVED** [review]
LGTM
