### PR TITLE
Force LANG=en_US.UTF-8 in test runner

### LINKED ISSUE #54475: Force local runs of devicelab tests to use `en_US` locale
Devicelab tests fail locally if the terminal locale isn't set to `en_US` (`export LANG=en_US.UTF-8`).

Updated instructions in https://github.com/flutter/flutter/wiki/Running-and-writing-tests#running-device-lab-tests-locally but it would be better if the tests handled forcing the locale.
See https://github.com/flutter/flutter/pull/51126#issuecomment-612061218.

### PR DESCRIPTION
**Pull request by jmagman**
Don't make the user set `LANG` themselves as instructed in https://github.com/flutter/flutter/wiki/Running-and-writing-tests#running-device-lab-tests-locally.
Add test.  Remove bot_test that's been skipped since #43149 since `BOT` env is tested in the new test.

Validated `LANG=ru_RU.KOI8-R dart bin/run.dart -t hot_mode_dev_cycle_macos_target__benchmark` failed before this PR and passed after.

Fixes https://github.com/flutter/flutter/issues/54475

### CODE REVIEW

File: dev/devicelab/lib/framework/utils.dart [hunk 1]
```diff
@@ -279,10 +279,10 @@ Future<Process> startProcess(
   assert(isBot != null);
   final String command = '$executable ${arguments?.join(" ") ?? ""}';
   final String finalWorkingDirectory = workingDirectory ?? cwd;
-  print('\nExecuting: $command in $finalWorkingDirectory'
-      + (environment != null ? ' with environment $environment' : ''));
   final Map<String, String> newEnvironment = Map<String, String>.from(environment ?? <String, String>{});
   newEnvironment['BOT'] = isBot ? 'true' : 'false';
+  newEnvironment['LANG'] = 'en_US.UTF-8';
+  print('\nExecuting: $command in $finalWorkingDirectory with environment $newEnvironment');
```
Comment (jmagman) [inline dev/devicelab/lib/framework/utils.dart:285]: Print the entire env, including `BOT` and `LANG`.  This makes it testable, and is probably just a good idea for accuracy.

File: dev/bots/test/bot_test.dart [hunk 2]
```diff
@@ -1,13 +0,0 @@
...
-// found in the LICENSE file.
-
-import 'dart:io';
-
-import 'common.dart';
-
-void main() {
-  test('BOT variable is set on bots', () {
-    expect(Platform.environment['BOT'], 'true');
-  }, skip: true);
```
Comment (jmagman) [inline dev/bots/test/bot_test.dart:12]: This has been skipped for awhile #43149.

**Review by CaseyHillers — APPROVED** [review]
LGTM
