### PR TITLE
Draggable feedback positioning

### LINKED ISSUE #145639: Draggable Feedback is positioned incorrectly when the Overlay is scaled
### Steps to reproduce

1. Wrap your entire `MaterialApp` in a transform (`Transform.scale(scale: 0.5, child: ...)` works well) 
2. Try out any `Draggable`

### Expected results

The `Draggable` feedback should still be attached to the pointer, as if the App wasn't transformed at all.

### Actual results

The feedback is offset, because it is positioned in the respective overlay using global coordinates.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:math';

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ColoredBox(
      color: Colors.grey[100]!,
      child: Transform.rotate(
        angle: 0.1 * pi,
        child: Transform.scale(
          scale: 0.5,
          child: Material(
            color: Colors.grey[900],
            elevation: 8,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(
                25,
              ),
            ),
            child: Padding(
              padding: const EdgeInsets.all(50.0),
              child: MaterialApp(
                title: 'Flutter Demo',
                debugShowCheckedModeBanner: false,
                theme: ThemeData(
                  primarySwatch: Colors.blue,
                ),
                home: const MyHomePage(title: 'Flutter Demo Home Page'),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    super.key,
    required this.title,
  });

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Draggable(
              child: FlutterLogo(),
              feedback: FlutterLogo(),
            ),
            Text("Drag this Logo"),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/42270125/0320b6a7-8a30-4d84-acd1-68ceae43ef78

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel master, 3.21.0-13.0.pre.24, on macOS 14.3.1 23D60 darwin-arm64, locale en-DE)
    • Flutter version 3.21.0-13.0.pre.24 on channel master at /Users/tim/Developer/whynotmake.it/flutter
    ! Upstream repository https://github.com/whynotmake-it/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/whynotmake-it/flutter.git to dismiss this error.
    • Framework revision 73e78fd97c (4 hours ago), 2024-03-23 10:18:25 -0400
    • Engine revision 689ea4b10b
    • Dart version 3.4.0 (build 3.4.0-265.0.dev)
    • DevTools version 2.34.0-dev.12
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /Users/tim/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0-rc2
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu11.54+25-CA (build 11.0.14.1+1-LTS)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.13.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.87.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • macOS (desktop)                 • macos                 • darwin-arm64 • macOS 14.3.1 23D60 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin       • macOS 14.3.1 23D60 darwin-arm64
    ! Error: Browsing on the local area network for iPhone von mir. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.
```

</details>

### PR DESCRIPTION
**Pull request by timcreatedit**
We changed the coordinates used to position the `Draggable` feedback by transforming them into the `Overlay`s coordinate space. This has no influence on any untransformed `Overlay`, most Flutter apps should be not affected. 
This PR fixes the positioning of the feedback in transformed context (see #145639 for before video):

https://github.com/flutter/flutter/assets/42270125/df34e198-0667-453d-a27a-a79b2e2825a1

- fixes #145639 

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by goderbauer** [comment]
From triage: @timcreatedit looks like this is failing some checks. Could you take a look? It also appears to be missing a test. Could you please add one? Thank you!

**Comment by timcreatedit** [comment]
I will take a look, yes! I'll add a test for the behaviour, I wasn't sure if that's desired since the class I touched seems to be untested.
Regarding the checks, it seems like these build checks failed for all everybody during the time I opened this, but that means once they re-run they should pass.

**Comment by goderbauer** [comment]
Looks like there are still some failures. Some of them look related to this change, e.g. https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8752209309943481745/+/u/run_test.dart_for_framework_tests_shard_and_subshard_widgets/stdout

**Comment by timcreatedit** [comment]
I can reproduce the test failures in test/widgets/draggable_test.dart, but I'm unsure where they come from. Weirdly enough, running each of the failing tests in isolation doesn't fail, only when the entire file is run. I will investigate, but I'd also be grateful for some input, as I don't see how this change would cause that at the moment.

**Comment by timcreatedit** [comment]
I think I have found the issue, however, I don't really understand why this change triggered the failures.

Some tests in `draggable_test.dart` don't finish their gestures. With the current state of the PR, all tests pass in isolation, but when these tests are run back to back, they fail because resources are not cleaned up properly.

Adding the following lines to the end of these tests resolves all test failures:

```dart
// Finish gesture to release resources.
await gesture.up();
await tester.pump();
```

Finishing gestures like this seems to be common practice anyways, and is done in many other tests within the same file.
3df4223 adds these changes to the tests, although I'm not sure if this should be done within this PR.

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/widgets/draggable_test.dart [hunk 1]
```diff
@@ -3414,6 +3442,34 @@ void main() {
     await tester.pumpAndSettle();
   });
 
+  testWidgets('Drag and drop - feedback matches pointer in scaled MaterialApp', (WidgetTester tester) async {
+    await tester.pumpWidget(Transform.scale(
+      scale: 0.5,
```
Comment (justinmc) [inline packages/flutter/test/widgets/draggable_test.dart:3447]: Nit: Is it worth it to add another test with rotation?

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 2]
```diff
@@ -856,6 +857,10 @@ class _DragAvatar<T extends Object> extends Drag {
 
   void updateDrag(Offset globalPosition) {
     _lastOffset = globalPosition - dragStartPoint;
+    final RenderBox box = overlayState.context.findRenderObject()! as RenderBox;
+    final Offset overlaySpaceOffset = box.globalToLocal(globalPosition);
+    _overlayOffset = overlaySpaceOffset - dragStartPoint;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/drag_target.dart:862]: It seems weird to me that we're subtracting dragStartPoint both from a point in global space (`_lastOffset = globalPosition - dragStartPoint;`) and from a point in local/overlay space (`_overlayOffset = overlaySpaceOffset - dragStartPoint;`). Wouldn't it be in the wrong coordinate space in one of those operations?

I guess based on your test and your video demo it works, though, so maybe I'm misunderstanding what dragStartPoint is.

**Review by justinmc — APPROVED** [review]
LGTM with a nit and a question.

Thanks for fixing this, I was just noticing another place where we weren't doing transforms properly (https://github.com/flutter/flutter/pull/146019).

File: packages/flutter/test/widgets/draggable_test.dart (hunk 1 above)
Comment (timcreatedit) [reply packages/flutter/test/widgets/draggable_test.dart:3448]: Done ✅

File: packages/flutter/lib/src/widgets/drag_target.dart (hunk 2 above)
Comment (timcreatedit) [reply packages/flutter/lib/src/widgets/drag_target.dart:862]: I had the same question at first. This transformation is definitely correct for the purposes `_overlayOffset` and I've added another test to verify that. However, it might be incorrect for `_lastOffset`, which we purposefully haven't touched. We wanted this PR to focus on the visual feedback only, since we thought that would be least likely to break existing Flutter code. Adjusting `_lastOffset_` can be done in another PR, where we could then make sure all `Draggable` callbacks use the Overlay space instead of global coordinates as they do now.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/drag_target.dart:862]: Ok sounds good. I agree that it looks like dragStartPoint is not in the same coordinate space as globalPosition, but _overlayOffset should be right.

**Comment by jmagman** [comment]
```
10:24 +15103 ~145: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/widgets/draggable_test.dart: Drag and drop - DragTarget<Object> can accept Draggable<int> data
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while routing a pointer event:
This widget has been unmounted, so the State no longer has a context (and should be considered
defunct).
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if
the State is still active.

When the exception was thrown, this was the stack:
#0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:951:9)
#1      State.context (package:flutter/src/widgets/framework.dart:957:6)
#2      _DragAvatar.updateDrag (package:flutter/src/widgets/drag_target.dart:862:40)
#3      _DragAvatar.update (package:flutter/src/widgets/drag_target.dart:843:5)
#4      MultiDragPointerState._move (package:flutter/src/gestures/multidrag.dart:100:16)
#5      MultiDragGestureRecognizer._handleEvent (package:flutter/src/gestures/multidrag.dart:267:13)
#6      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#7      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#9      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:11)
#14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#16     TestWidgetsFlutterBinding.handlePointerEventForSource.<anonymous closure> (package:flutter_test/src/binding.dart:662:42)
#17     TestWidgetsFlutterBinding.withPointerEventSource (package:flutter_test/src/binding.dart:672:11)
#18     TestWidgetsFlutterBinding.handlePointerEventForSource (package:flutter_test/src/binding.dart:662:5)
#19     WidgetTester.sendEventToBinding.<anonymous closure> (package:flutter_test/src/widget_tester.dart:868:15)
#22     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#23     WidgetTester.sendEventToBinding (package:flutter_test/src/widget_tester.dart:867:27)
#24     TestGesture.moveTo.<anonymous closure> (package:flutter_test/src/test_pointer.dart:533:27)
#27     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#28     TestGesture.moveTo (package:flutter_test/src/test_pointer.dart:531:27)
#29     main.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/widgets/draggable_test.dart:3246:19)
<asynchronous suspension>
#30     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#31     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

router: Instance of 'PointerRouter'
route: Closure: (PointerEvent) => void from Function '_handleEvent@425470698':.
event: PointerMoveEvent#b34eb(position: Offset(400.0, 98.0))
════════════════════════════════════════════════════════════════════════════════════════════════════
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8749120090464225025/+/u/run_test.dart_for_framework_tests_shard_and_subshard_impeller/stdout

**Comment by justinmc** [comment]
@timcreatedit It looks like that's not a test you touched directly. Is it related to the `gesture.up` calls you were adding?

**Comment by timcreatedit** [comment]
@justinmc I took a look and it seems like this happened because gestures are not correctly ended in other tests that ran before this one. Again, the failed test passes when ran in isolation. I really don't understand why these failures are only on this branch, can anybody help me out?
