### PR TITLE
Fix asserts in Draggable dismounting

### LINKED ISSUE #1927: 'packages/flutter/src/gestures/multidrag.dart': Failed assertion: line 181: 'state != null' is not true.
```dart
android: I/flutter : -- EXCEPTION CAUGHT BY GESTURE LIBRARY ---------------------------------
android: I/flutter : The following exception was raised while dispatching a pointer event:
android: I/flutter : 'packages/flutter/src/gestures/multidrag.dart': Failed assertion: line 181: 'state != null' is not true.
android: I/flutter : Event:
android: I/flutter : PointerUpEvent(Point(1199.5, 158.0))
android: I/flutter : Target:
android: I/flutter : Instance of 'WidgetFlutterBinding'
android: I/flutter : Stack trace:
android: I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
android: I/flutter : #1      MultiDragGestureRecognizer.acceptGesture (packages/flutter/src/gestures/multidrag.dart:181)
android: I/flutter : #2      GestureArena.sweep (packages/flutter/src/gestures/arena.dart:105)
android: I/flutter : #3      BindingBase&Scheduler&Gesturer.handleEvent (packages/flutter/src/gestures/binding.dart:121)
android: I/flutter : #4      BindingBase&Scheduler&Gesturer.dispatchEvent (packages/flutter/src/gestures/binding.dart:96)
android: I/flutter : #5      BindingBase&Scheduler&Gesturer._handlePointerEvent (packages/flutter/src/gestures/binding.dart:71)
android: I/flutter : #6      BindingBase&Scheduler&Gesturer._handlePointerPacket (packages/flutter/src/gestures/binding.dart:43)
android: I/flutter : #7      _dispatchPointerPacket (file:///home/travis/build/flutter/buildbot/src/out/android_Release/gen/sky/bindings/hooks.dart:43)
android: I/flutter : ------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by abarth**
In writing a test for #1927, I found a number of bugs in how Draggable shuts
down. Previously it would leak its recongizer. Now it disposes its recognizer
and the recognizer knows how to be disposed cleanly.

Fixes #1927

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

**Comment by abarth** [comment]
@Hixie

File: packages/flutter/test/widget/draggable_test.dart [hunk 1]
```diff
@@ -871,6 +871,75 @@ void main() {
...
+    await tester.pumpWidget(new Container(key: new UniqueKey()));
+    expect(didTap, isFalse);
+  });
+
+  testWidgets('Draggable plays nice with onTap', (WidgetTester tester) async {
+    await tester.pumpWidget(new Overlay(
+      initialEntries: <OverlayEntry>[
+        new OverlayEntry(
+          builder: (BuildContext context) => new GestureDetector(
+            onTap: () { /* registers a tap recognizer */ },
```
Comment (Hixie) [inline packages/flutter/test/widget/draggable_test.dart]: file a bug if this doesn't work

**Comment by Hixie** [comment]
LGTM

File: packages/flutter/test/widget/draggable_test.dart (hunk 1 above)
Comment (abarth) [inline packages/flutter/test/widget/draggable_test.dart]: Never mind.  I forgot about the other finger down which stops it from being tap.
