### PR TITLE
[flutter_tools] reduce build bundle API

### LINKED ISSUE #66906: "flutter build bundle" outputs a warning that seems wrong
Between flutter versions 1.19.0-0.0.pre (dev) and 1.19.0-4.1.pre (beta), something changed that `flutter build bundle` now outputs: `Font subetting is not supported in debug mode. The --tree-shake-icons flag will be ignored.`

The Dev 1.19.0-0.0.pre version does _not_ do this, but Beta 1.19.0-4.1.pre does.

`flutter build bundle` is only really generating the files needed to build, so can this warning be suppressed in this case?

The problem still exists in the latest Beta 1.22.0-12.2.pre. I'm putting my doctor output using the latest beta.

<details><summary>Flutter doctor</summary>

[✓] Flutter (Channel beta, 1.22.0-12.2.pre, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.22.0-12.2.pre at /Users/danny.valente/Library/flutter/1.22.0-12.2.pre-beta
    • Framework revision 2bafdc8226 (4 days ago), 2020-09-25 12:48:22 -0700
    • Engine revision f763b5b9b9
    • Dart version 2.10.0 (build 2.10.0-110.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Remove outdated API from build bundle usage when it was part of the re-entrant build system. We should consider further reducing the API (target-platform) to make it easier for arbitrary embedders to use this command

Fixes https://github.com/flutter/flutter/issues/66906

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/build_bundle.dart [hunk 1]
```diff
@@ -18,22 +18,9 @@ class BuildBundleCommand extends BuildSubCommand {
     usesTargetOption();
     usesFilesystemOptions(hide: !verboseHelp);
     usesBuildNumberOption();
-    addBuildModeFlags(verboseHelp: verboseHelp);
+    addBuildModeFlags(verboseHelp: verboseHelp, defaultToRelease: false);
     usesExtraDartFlagOptions();
     argParser
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/build_bundle.dart:23]: This flag makes no sense now that the re-entrant build is gone. Before it would essentially tell this command to not generate kernel, because kernel generation would be conditionally performed by build aot

File: packages/flutter_tools/lib/src/commands/build_bundle.dart [hunk 2]
```diff
@@ -18,22 +18,9 @@ class BuildBundleCommand extends BuildSubCommand {
...
-        'precompiled',
-        negatable: false,
-        help:
-          'If not provided, then '
-          'a debug build is always provided, regardless of build mode. If provided '
-          'then release is the default mode.',
-      )
-      // This option is still referenced by the iOS build scripts. We should
-      // remove it once we've updated those build scripts.
-      ..addOption('asset-base', help: 'Ignored. Will be removed.', hide: !verboseHelp)
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/build_bundle.dart:34]: Can't find any more references to this

File: packages/flutter_tools/lib/src/commands/build_bundle.dart [hunk 3]
```diff
@@ -18,22 +18,9 @@ class BuildBundleCommand extends BuildSubCommand {
...
-      ..addOption('manifest', defaultsTo: defaultManifestPath)
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/build_bundle.dart:35]: Not actually configurable anymore

File: packages/flutter_tools/lib/src/commands/build_bundle.dart [hunk 4]
```diff
@@ -18,22 +18,9 @@ class BuildBundleCommand extends BuildSubCommand {
...
-      ..addOption('private-key', defaultsTo: defaultPrivateKeyPath)
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/build_bundle.dart:36]: Not supported since flutter stopped doing its own native builds

File: packages/flutter_tools/lib/src/commands/build_bundle.dart [hunk 5]
```diff
@@ -48,11 +35,7 @@ class BuildBundleCommand extends BuildSubCommand {
           'windows-x64',
         ],
       )
-      ..addOption('asset-dir', defaultsTo: getAssetBuildDirectory())
-      ..addFlag('report-licensed-packages',
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/build_bundle.dart:52]: This flag is not wired up to anything

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
None of these APIs should be used in g3...
