### PR TITLE
[hcpp/hc] Fix talkback for HC and HCPP Android platform views

### LINKED ISSUE #113626: Talkback doesn't always see platform view contents in Hybrid Composition mode
During investigation of https://github.com/flutter/flutter/issues/101887 I'm seeing that platform view accessibility seems to be broken in at least some cases in Hybrid Composition.

Example steps to reproduce:
- Run the example app from `webview_flutter`, making sure it's in HC mode (currently that's true by default because of the transparent background.)
- Run on Android with Talkback enabled, and try to get to the web view contents.

What I'm seeing is that the webview is completely invisible to Talkback (not only tapping, but if I enable the "dump node tree" option in Talkback developer settings, the resulting tree doesn't list the webview). It appears that this is due to the overlay view that displays the widgets that are over the platform view in the Flutter widget tree (in this case the favorites button); if I run with a local engine modified to not add the overlay view to the Flutter view, it's in the a11y node tree and can be inspected by tapping as expected (although of course other things are broken). It may be that this only happens if there are actually overlays, but I haven't investigated that yet.

The same test works fine in TLHC mode, which is not surprising since we don't use an overlay view for TLHC.

I'm not familiar enough with the internals of Android's a11y system to know why this happens; naively I would expect fully transparent view overlays to mask a11y elements that are underneath them. If possible, we need to find a way to have only the opaque parts of the overlay be treated by the a11y system as hiding what is underneath them. (/cc @chunhtai @bparrishMines )

### PR DESCRIPTION
**Pull request by gmackall**
See the description here: https://github.com/flutter/flutter/issues/113626#issuecomment-2884997160

Fixes https://github.com/flutter/flutter/issues/113626

Also, I think we can probably improve the behavior here to respect what the original view's accessibility importance was, by storing what we are overwriting at creation time, and then using that later when we undo what we do at creation time. As is it seems like there would be no way for a developer to _actually_ set their view to be not important for accessibility, we are basically forcing them in to auto. Can look into that in a follow up.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by gmackall** [comment]
@jonahwilliams I still need to figure out how to test this, but does the approach look reasonable (specifically putting a controller in front of the controllers). 

I can name it something else if desired, but also I expect something like this is destined to exist regardless to support the unified PV constructor Reid is working on, which will need to then delegate creation to either PVC1 or 2 depending.

**Review by jonahwilliams — COMMENTED** [review]
Seems like a reasonable approach. Though please name it something besides ControllerController :)

**Comment by jonahwilliams** [comment]
Its more of a delegate perhaps :)

**Comment by gmackall** [comment]
> Its more of a delegate perhaps :)

Renamed to `PlatformViewsControllerDelegator` 😢

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by gmackall** [comment]
Google testing consistently failing on infra issues, and I'm not able to manually run it due to issues with the script, so overriding.

File: engine/src/flutter/shell/platform/android/io/flutter/plugin/platform/PlatformViewsControllerDelegator.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+// found in the LICENSE file.
+
+package io.flutter.plugin.platform;
+
+import android.view.View;
+import androidx.annotation.NonNull;
+import androidx.annotation.Nullable;
+import io.flutter.view.AccessibilityBridge;
+
+public class PlatformViewsControllerDelegator implements PlatformViewsAccessibilityDelegate {
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/plugin/platform/PlatformViewsControllerDelegator.java:12]: Please add a java doc to this class that describes its responsibilities
