### PR TITLE
ensure debug builds are only accessible through run

### LINKED ISSUE #40772: [web] `flutter build web --debug` fails when a plugin is included in the project
I have a Flutter project that includes a web implementation of url_launcher. `flutter build web` succeeds, but `flutter build web --debug` fails with the following error.

```[  +79 ms] FileSystemException: Cannot copy file to 'build/web/main.dart.js.map', path =

'/Users/jkurtw/development/web_plugins/url_launcher_test/.dart_tool/build/flutter_web/url_launcher_test/lib/main_web_entrypoint.dart.js.map
           ' (OS Error: No such file or directory, errno = 2)
[   +9 ms] Compiling lib/main.dart for the Web... (completed in 7.1s)
[   +2 ms] "flutter web" took 7,479ms.
Failed to compile lib/main.dart for the Web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildWeb (package:flutter_tools/src/web/compile.dart:61:5)
<asynchronous suspension>
#2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:47:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

We don't actually allow debug builds to be "built" for flutter for web, because it requires an asset server to work correctly today. Remove the option to reduce confusion.

Fixes https://github.com/flutter/flutter/issues/40772

### CODE REVIEW

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 1]
```diff
@@ -263,12 +263,21 @@ abstract class FlutterCommand extends Command<void> {
             'Normally there\'s only one, but when adding Flutter to a pre-existing app it\'s possible to create multiple.');
   }
 
-  void addBuildModeFlags({ bool defaultToRelease = true, bool verboseHelp = false }) {
+  void addBuildModeFlags({ bool defaultToRelease = true, bool verboseHelp = false, bool excludeDebug = false }) {
+    assert(() {
+      // If we don't default to release, ensure that we support debug mode.
+      if (!defaultToRelease && excludeDebug) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: How about
```dart
// A release build must be the default if a debug build is not possible.
return defaultToRelease || !excludeDebug;
```

**Review by zanderso — COMMENTED** [review]
lgtm
