### PR TITLE
Expose insetPadding and clipBehavior in Dialog and AlertDialog.

### LINKED ISSUE #50757: Content inside Dialog widget does not get clipped when necessary
## Steps to Reproduce
1. Use a `Dialog` widget with custom content that goes to the edges (like an image).
2. Observe that the content does not clip to the set `shape` of the `Dialog`

**Expected results:** 
A way to enable clipping on a `Dialog` widget

**Actual results:** 
No clipping at all

### PR DESCRIPTION
**Pull request by darrenaustin**
## Description

Currently the `Dialog` class has a hard coded padding used for the outer part of the dialog. This makes it hard for large dialogs like the Date Picker to use more of the screen. In addition, there is no way to specify the `clipBehavior` used by the Dialog's internal `Material` widget. This means that there is no way to have the dialog's content clipped to the given shape, as it defaults to `Clip.none`.

This PR exposes new `insetPadding` and `clipBehavior` parameters to the constructors for the `Dialog` and `AlertDialog` classes.

## Related Issues

Closes #50757

## Tests

I added tests to the `dialog_test.dart` that tests both of these parameters.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/dialog.dart [hunk 1]
```diff
@@ -87,6 +90,24 @@ class Dialog extends StatelessWidget {
   /// {@endtemplate}
   final Curve insetAnimationCurve;
 
+  /// {@template flutter.material.dialog.insetPadding}
+  /// The amount of padding added to the outside of the dialog.
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/dialog.dart]: I'm not sure what the right way to describe this is, but I'm assuming this means the padding between the edges of the screen and the dialog itself? I had to think about this for a while and confused between that meaning and the padding between the edges of the dialog and its contents. 

Also, do we only see this when the dialog is expanded to be as large as it can be? If I recall correctly, the dialog will be smaller if there the dialog's contents are small enough

File: packages/flutter/lib/src/material/dialog.dart [hunk 2]
```diff
@@ -49,9 +49,12 @@ class Dialog extends StatelessWidget {
     this.elevation,
     this.insetAnimationDuration = const Duration(milliseconds: 100),
     this.insetAnimationCurve = Curves.decelerate,
+    this.insetPadding = const EdgeInsets.symmetric(horizontal: 40.0, vertical: 24.0),
+    this.clipBehavior = Clip.none,
     this.shape,
     this.child,
-  }) : super(key: key);
+  }) : assert(clipBehavior != null)
+     , super(key: key);
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/dialog.dart]: I think this is typically formatted this way:
```dart
  }) : assert(clipBehavior != null), 
       super(key: key);
```

File: packages/flutter/lib/src/material/dialog.dart [hunk 3]
```diff
@@ -87,6 +90,24 @@ class Dialog extends StatelessWidget {
...
 
+  /// {@template flutter.material.dialog.insetPadding}
+  /// The amount of padding added to the outside of the dialog.
+  ///
+  /// Defaults to `const EdgeInsets.symmetric(horizontal: 40.0, vertical: 24.0)`.
+  /// {@endtemplate}
+  final EdgeInsets insetPadding;
+
+  /// {@template flutter.material.dialog.clipBehavior}
+  /// Controls how the contents of the Dialog are clipped (or not) to the given
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/dialog.dart]:
```suggestion
  /// Controls how the contents of the dialog are clipped (or not) to the given
```

File: packages/flutter/lib/src/material/dialog.dart [hunk 4]
```diff
@@ -229,10 +252,13 @@ class AlertDialog extends StatelessWidget {
...
     this.semanticLabel,
+    this.insetPadding = const EdgeInsets.symmetric(horizontal: 40.0, vertical: 24.0),
+    this.clipBehavior = Clip.none,
     this.shape,
     this.scrollable = false,
-  }) : assert(contentPadding != null),
-       super(key: key);
+  }) : assert(contentPadding != null)
+     , assert(clipBehavior != null)
+     , super(key: key);
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/dialog.dart]:
```dart
  }) : assert(contentPadding != null),
       assert(clipBehavior != null),
       super(key: key);
```

File: packages/flutter/lib/src/material/dialog.dart (hunk 1 above)
Comment (darrenaustin) [reply packages/flutter/lib/src/material/dialog.dart]: Yup. I struggled with that too. I will try come up with a better description.

File: packages/flutter/lib/src/material/dialog.dart (hunk 2 above)
Comment (darrenaustin) [reply packages/flutter/lib/src/material/dialog.dart]: I could have sworn I have seen it this way in other files, but looking at the style guidelines again, you are indeed correct. Thx. I will fix that shortly.

File: packages/flutter/lib/src/material/dialog.dart [hunk 5]
```diff
@@ -91,9 +91,11 @@ class Dialog extends StatelessWidget {
   final Curve insetAnimationCurve;
 
   /// {@template flutter.material.dialog.insetPadding}
-  /// The amount of padding added to the outside of the dialog.
+  /// The amount of padding added to [MediaQueryData.viewInsets] on the outside
+  /// of the dialog. This defines the minimum space between the screen's edges
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/dialog.dart]: Nice, this last sentence makes it very clear!

**Review by shihaohong — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/dialog.dart [hunk 6]
```diff
@@ -229,9 +254,12 @@ class AlertDialog extends StatelessWidget {
     this.backgroundColor,
     this.elevation,
     this.semanticLabel,
+    this.insetPadding = const EdgeInsets.symmetric(horizontal: 40.0, vertical: 24.0),
```
Comment (rami-a) [inline packages/flutter/lib/src/material/dialog.dart]: Wondering if this `const EdgeInsets` should be factored into a constant since its used twice.

**Review by rami-a — APPROVED** [review]

File: packages/flutter/lib/src/material/dialog.dart (hunk 6 above)
Comment (darrenaustin) [reply packages/flutter/lib/src/material/dialog.dart]: Good catch. Just updated to include this.

**Comment by ycherniavskyi** [comment]
@darrenaustin could you please clarify why `insetPadding` and `clipBehavior` were not added to `SimpleDialog` as well?

Because if it was unintended (without any actual reason), I could create PR with such addition. I need to have the possibility to reduce the height of `SimpleDialog` with a large list of `SimpleDialogOption`, and it could be achieved by `insetPadding`.

**Comment by darrenaustin** [comment]
@ycherniavskyi This was just an oversight. A PR to add them to `SimpleDialog` would be welcome. Thanks.
