### PR TITLE
Fix description in index.html / manifest.json getting double quoted

### LINKED ISSUE #131834: [Web][regression] Meta description has double quotes
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports) from 

### Steps to reproduce

1.  Checkout latest `master` channel or the exact commit where this issue is reproduced (https://github.com/flutter/flutter/commit/03749051e89d39b4267b355820e644cac8cced1c)
 https://github.com/flutter/flutter/pull/130096
2. Create new app `flutter create myapp` or regenerate `web` folder with `flutter create .`
3. Inspect `web/index.html` for meta description.
You will see
`<meta name="description" content=""A new Flutter project."">`

### Expected results

`<meta name="description" content="A new Flutter project.">`

#### Chrome Inspector
Screenshot 2023-08-03 at 12 10 26

### Actual results

`<meta name="description" content=""A new Flutter project."">`

#### Chrome Inspector
Screenshot 2023-08-03 at 12 07 28

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.13.0-3.0.pre.46, on macOS 13.4.1 22F770820d darwin-arm64, locale en-EE)
    ! Flutter version 3.13.0-3.0.pre.46 on channel [user-branch] at /Users/tahatesser/Code/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not the same as FLUTTER_GIT_URL
    • FLUTTER_GIT_URL = git@github.com:NevercodeHQ/flutter.git
    • Framework revision 03749051e8 (3 weeks ago), 2023-07-13 15:53:51 -0700
    • Engine revision 1867efbf29
    • Dart version 3.1.0 (build 3.1.0-308.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode-14.3.1.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by navaronbracke**
This PR adjusts the quoting of the project description not not apply twice in the index.html / manifest.json of web builds.

*List which issues are fixed by this PR. You must list at least one issue.*
Fixes https://github.com/flutter/flutter/issues/131834

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/template.dart [hunk 1]
```diff
@@ -328,6 +328,20 @@ class Template {
           context['androidIdentifier'] = _escapeKotlinKeywords(androidIdentifier);
         }
 
+        final bool web = (context['web'] as bool?) ?? false;
+
+        if (web) {
+          // The index.html and manifest.json outputs already have quotes in the template,
+          // so extra quotes are not needed.
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/template.dart:335]: Should we have this comment should explain where the extra quotes came from?

File: packages/flutter_tools/test/commands.shard/permeable/create_test.dart [hunk 2]
```diff
@@ -3384,6 +3384,32 @@ void main() {
     FeatureFlags: () => TestFeatureFlags(),
     Logger: () => logger,
   });
+
+  testUsingContext('Does not double quote description in index.html on web', () async {
+    await _createProject(
+      projectDir,
+      <String>['--no-pub', '--platforms=web'],
```
[the remark this answers is not in the document]
Comment (andrewkolos) [reply packages/flutter_tools/test/commands.shard/permeable/create_test.dart:3391]: You could mark these array literals `const`, though we generally don't worry about hyper-optimizing test code.

> `Linux analyze` does not fail without it, although I'd expected it to?

Are you referring to the [`prefer_const_declarations`](https://dart.dev/tools/linter-rules/prefer_const_declarations) rule? To my knowledge, this rule is only violated if you assign a `const` value to a non-`const` variable (e.g. `final key = 'CONSTANT_STRING_LITERAL'`). I'm assuming the analyzer isn't analyzing the items of the array literals to see if every item is constant (meaning the array literal itself could be constant), so this rule can't be violated when assigning array literals to something. This is just a theory--I don't have much knowledge in regards to the dart analyzer

I'm not worried about it 🤷

File: packages/flutter_tools/lib/src/template.dart [hunk 3]
```diff
@@ -328,6 +328,20 @@ class Template {
...
+          if (finalDestinationFile.basename == 'index.html' || finalDestinationFile.basename =='manifest.json') {
+            final String? description = context['description'] as String?;
+
+            if (description != null && description.isNotEmpty) {
+              context['description'] = description.replaceAll('"', '');
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/template.dart:340]: Note for myself when doing my next review pass:

Is it safe to modify `context` here? Will this result in bugs if we change the rendering order of the template files? Instead of writing to `context['description']`, maybe we should just make a local copy of it.

**Review by andrewkolos — CHANGES_REQUESTED** [review]
I wonder if there's a better way to approach the problem.

Instead of undoing the YAML-string-escaping when writing to a non-YAML file, should we just delay YAML-escaping until we are writing to YAML files?

It seems odd to YAML-escape string items when creating `context`, when these items might not be used for only YAML files.

I will bring this up during weekly tool PR review (Aug 10).

File: packages/flutter_tools/lib/src/template.dart (hunk 3 above)
Comment (navaronbracke) [reply packages/flutter_tools/lib/src/template.dart:340]: Then we'd have to make sure that the template renderer gets the local when calling `renderString()`, which might not be as flexible if other things need to get passed down in the future.

I think your idea of delaying the YAML escaping until we have a YAML file to create makes more sense here.
Then it is up to the template renderer to decide when to escape what.

**Comment by navaronbracke** [comment]
@andrewkolos I had a second look at how the template is rendered.

So we pass things to `mustache`, that takes care of rendering to the template.

Apparently it has a `htmlEscapes` property for the template renderer.

Wouldn't it be better if it did the same for yaml?

Ref: https://github.com/jonahwilliams/mustache/blob/c4344e0dd45f6605758eb11aa4837859e2c055f0/README.md?plain=1#L39

File: packages/flutter_tools/lib/src/template.dart (hunk 1 above)
Comment (navaronbracke) [reply packages/flutter_tools/lib/src/template.dart]: Since the 'extra' quotes have been eliminated from `createTemplateContext()`, I've adjusted the comment to mention why we add quotes instead.

File: packages/flutter_tools/lib/src/template.dart (hunk 3 above)
Comment (navaronbracke) [reply packages/flutter_tools/lib/src/template.dart]: Made a local copy of the context when writing to the pubspec.

File: packages/flutter_tools/lib/src/template.dart [hunk 4]
```diff
@@ -328,7 +328,24 @@ class Template {
...
+            // Grab a copy of the context, since it is used to render other templates as well.
+            localContext = Map<String, Object?>.of(localContext);
+
+            final String? description = localContext['description'] as String?;
+
+            if (description != null && description.isNotEmpty) {
+              localContext['description'] = escapeYamlString(description);
+            }
+          }
+        }
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/template.dart:346]: Is the second condition redundant with the first? Also, consider making the leading comment more concise.

```suggestion
        // Ensure inputs are escaped when necessary.
        if (finalDestinationFile.path.endsWith('.yaml')) {
          // Use copy of the context, since the original is used in rendering other templates.
          localContext = Map<String, Object?>.of(localContext);

          final String? description = localContext['description'] as String?;

          if (description != null && description.isNotEmpty) {
            localContext['description'] = escapeYamlString(description);
          }
        }
```

**Review by andrewkolos — CHANGES_REQUESTED** [review]
Hello, sorry for being absent. I was out of action towards the end of last week. I requested one change.

File: packages/flutter_tools/lib/src/template.dart (hunk 4 above)
Comment (navaronbracke) [reply packages/flutter_tools/lib/src/template.dart]: No worries :)

Yeah, I was a bit conservative about "what if we need to handle other YAML files in the future", but that doesn't happen often.

Adjusted the condition and updated the comment.

**Review by andrewkolos — APPROVED** [review]
LGTM

File: packages/flutter_tools/test/commands.shard/permeable/create_test.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/test/commands.shard/permeable/create_test.dart:3391]: Also note, the analyzer isn't statically checking whether at some point in the future, this value may be pushed to, which wouldn't work for a const list. Thus, the analyzer can't determine if a list literal can safely be made const.

**Comment by navaronbracke** [comment]
Rebased on ToT to kick off the Google testing check again

**Comment by andrewkolos** [comment]
@christopherfujino Are you able to take a look at this?

File: packages/flutter_tools/lib/src/template.dart [hunk 5]
```diff
@@ -361,7 +361,22 @@ class Template {
...
+          // Use a copy of the context,
+          // since the original is used in rendering other templates.
+          localContext = Map<String, Object?>.of(localContext);
+
+          final String? description = localContext['description'] as String?;
+
+          if (description != null && description.isNotEmpty) {
+            localContext['description'] = escapeYamlString(description);
+          }
+        }
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/template.dart:377]: I'm a little worried that we're conditionally mutating the `localContext` variable, and this behavior may be obscured and forgotten in the future. Instead, can you pull the escaping logic into a helper function with a dartdoc, so it's more clear when and why we would be escaping, and with which copy?

```suggestion
        final Map<String, Object?> localContext = finalDestinationFile.path.endsWith('.yaml')
          ? _createEscapedContextCopy(context)
          : context;
```

And then the inner block moved into `Map<String, Object?> _createEscapedContextCopy(Map<String, Object?> oldContext)`

**Review by christopherfujino — APPROVED** [review]
LGTM thanks for this fix!

**Comment by TahaTesser** [comment]
Thanks for the fix @navaronbracke !
