### PR TITLE
Fix dayPeriodColor handling of non-MaterialStateColors

### LINKED ISSUE #139445: The selected and unselected day period box are in same color in TimePicker
### Steps to reproduce

Set themeData in materialApp like this
```
  theme: ThemeData.light(useMaterial3: true).copyWith(
        timePickerTheme: TimePickerThemeData(
          dayPeriodColor:Colors.red,)
```

call the widget
```
 Center(
        child: ElevatedButton(onPressed: ()async{
TimeOfDay initialTime = TimeOfDay.now();
TimeOfDay? pickedTime = await showTimePicker(
    context: context,
    initialTime: initialTime,
);

        }, child: Text("picker")),
      ),
```

  

### Expected results

The unselected day period box foreground color should be in transparent or different color 

### Actual results

The selected and unselected day period box are in same color
Screenshot 2023-12-03 172937

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    // Color getColor(Set<MaterialState> states) {
    //   const Set<MaterialState> interactiveStates = <MaterialState>{
    //     MaterialState.pressed,
    //     MaterialState.hovered,
    //     MaterialState.focused,
    //   };
    //   if (states.any(interactiveStates.contains)) {
    //     return Colors.blue;
    //   }
    //   return Colors.red;
    // }
    bool selected = false;
      final Set<MaterialState> states = <MaterialState>{ if (selected) MaterialState.selected };
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.light(useMaterial3: true).copyWith(
        
           buttonTheme: ButtonTheme.of(context).copyWith(
            disabledColor: Colors.black,
          colorScheme: ColorScheme.light(
            secondary: Colors
                .green, // Color you want for action buttons (CANCEL and OK)
          ),
        ),
primaryColor: Colors.orange,
secondaryHeaderColor: Colors.deepPurpleAccent,
        timePickerTheme: TimePickerThemeData(
          dayPeriodBorderSide: BorderSide(color: Colors.red),
          dayPeriodColor:Colors.red,
                hourMinuteTextColor: Colors.white,
          dayPeriodTextColor: Colors.white,
          // hourMinuteTextStyle: TextStyle(color: ),
          
          backgroundColor: Colors.black.withOpacity(0.2),
    
          dialBackgroundColor: Colors.yellow.withOpacity(0.2),
     
          entryModeIconColor: Colors.green,
          hourMinuteColor: Colors.pink,
          dialHandColor: Colors.purple,
          confirmButtonStyle: ButtonStyle(foregroundColor: MaterialStateProperty.all(Colors.blue)),
          cancelButtonStyle: ButtonStyle(foregroundColor: MaterialStateProperty.all(Colors.red))
        ),
        
      textButtonTheme: TextButtonThemeData(
          style: ButtonStyle(
              // foregroundColor: MaterialStateProperty.resolveWith(getColor)
              ),
        ),
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHome(),
    );
  }
}

class MyHome extends StatelessWidget {
  const MyHome({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(onPressed: ()async{
TimeOfDay initialTime = TimeOfDay.now();
TimeOfDay? pickedTime = await showTimePicker(
    context: context,
    initialTime: initialTime,
);

        }, child: Text("picker")),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[
Screenshot 2023-12-03 172937
]

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

</details>

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This fixes the handling of `dayPeriodColor` on the `TimePicker` so that if it's a non-`MaterialStateColor`, it only applies the color to the selected state, but otherwise uses the given `MaterialStateColor` to get custom behavior.

## Related Issues
 - Fixes https://github.com/flutter/flutter/issues/139445

## Tests
 - Added tests for both non-`MaterialStateColor` and `MaterialStateColor` cases.

### CODE REVIEW

File: packages/flutter/lib/src/material/time_picker_theme.dart [hunk 1]
```diff
@@ -102,7 +103,21 @@ class TimePickerThemeData with Diagnosticable {
...
+      return _dayPeriodColor;
+    }
+    return MaterialStateColor.resolveWith((Set<MaterialState> states) {
+      if (states.contains(MaterialState.selected)) {
+        return _dayPeriodColor;
+      }
+      // The unselected day period should match the overall picker dialog color.
+      // Making it transparent enables that without being redundant and allows
+      // the optional elevation overlay for dark mode to be visible.
+      return Colors.transparent;
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/time_picker_theme.dart:117]: nit: Should we here just provide `return null;` so the unselected `dayPeriodColor` will be the default `dayPeriodColor`? They should have same effect(both transparent), but just in case MaterialDesign tokens are changed in the future:)

**Review by QuncCccccc — APPROVED** [review]
LGTM!

File: packages/flutter/lib/src/material/time_picker_theme.dart (hunk 1 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/material/time_picker_theme.dart:117]: Unfortunately, `resolveWith` requires a non-null return value, so I can't return null here.

Comment (QuncCccccc) [reply packages/flutter/lib/src/material/time_picker_theme.dart:117]: Ah I see. That makes sense:) Thanks!
