### PR TITLE
Temporarily remove a bogus warning until fixed by dwds update

### LINKED ISSUE #109792: Bogus error message when debugging on web
Repro for master channel:

- Debug example/hello_world in VSCode on Chrome
- set a breakpoint at `runApp` ad start debugging
- observe a list of warnings in the debug console window when the breakpoint is hit:

image

### PR DESCRIPTION
**Pull request by annagrin**
Closes: https://github.com/flutter/flutter/issues/109792

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/isolated/devfs_web.dart [hunk 1]
```diff
@@ -1042,7 +1042,9 @@ void log(logging.LogRecord event) {
   if (event.level >= logging.Level.SEVERE) {
     globals.printError('${event.loggerName}: ${event.message}$error', stackTrace: event.stackTrace);
   } else if (event.level == logging.Level.WARNING) {
-    globals.printWarning('${event.loggerName}: ${event.message}$error');
+    if (!event.message.contains('No module for')) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/isolated/devfs_web.dart:1045]: If the need for this check is temporary, please add a TODO with issue/PR after which this can be removed.

Comment (annagrin) [reply packages/flutter_tools/lib/src/isolated/devfs_web.dart:1048]: Done! This already fixed in dwds so I added a link to the "release new version of dwds" issue.

**Review by zanderso — APPROVED** [review]
