### PR TITLE
fix a _DraggableScrollableSheetScrollPosition update bug

### LINKED ISSUE #89681: weird log for DraggableScrollableSheet
this code work in previous flutter version 2.2 but when i upgraded  to v2.5 shows me weird error
the error start shows when i scroll  the sheet to the minchildSize
this is the code 

```dart
Scaffold(
      body: DraggableScrollableSheet(
        initialChildSize: 0.55,
        maxChildSize: 0.65,
        minChildSize: .25,
        expand: true,
        builder: (ctx, sheetController) {
          return ScrollConfiguration(
            behavior: ScrollBehavior().copyWith(
              overscroll: false,
              scrollbars: false,
            ),
            child: SingleChildScrollView(
              controller: sheetController,
              physics: AlwaysScrollableScrollPhysics(),
              child: ConstrainedBox(
                constraints: BoxConstraints(
                  minHeight: 120,
                  maxHeight: MediaQuery.of(context).size.height * 0.65,
                ),
                child: LayoutBuilder(
                  builder: (ctx, constraint) {
                    return Card(
                      color: Colors.red,
                    );
                  },
                ),
              ),
            ),
          );
        },
      ),
    )


```

<details> 
  <summary>Flutter log </summary>
  
```console
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 654 pos 12: '_drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragEnd (package:flutter/src/widgets/scrollable.dart:654:12)
#3      DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:486:47)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#5      DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:486:5)
#6      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:393:9)
#7      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:387:9)
#8      DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:402:5)
#9      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:321:7)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#25     _invoke1 (dart:ui/hooks.dart:185:10)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onEnd"
Recognizer: VerticalDragGestureRecognizer#f6117
  start behavior: start
====================================================================================================

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
A _DraggableScrollableSheetScrollPosition was used after being disposed.

Once you have called dispose() on a _DraggableScrollableSheetScrollPosition, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:114:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:120:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:288:12)
#3      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:968:11)
#4      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:278:9)
#5      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:82:18)
#6      BallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/scroll_activity.dart:566:21)
#7      BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:553:10)
#8      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:155:19)
#9      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:829:5)
#10     Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#12     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1056:11)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#14     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1054:17)
#15     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:975:5)
#19     _invoke1 (dart:ui/hooks.dart:185:10)
#20     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:248:5)
#21     _beginFrame (dart:ui/hooks.dart:116:31)
(elided 3 frames from dart:async)
The AnimationController notifying listeners was: AnimationController#0fd80(▶ -25.516; for BallisticScrollActivity)
```
</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes https://github.com/flutter/flutter/issues/89681

If update the `_DraggableScrollableSheetScrollPosition` during drag will lose `_dragCancelCallback`, and will trigger an assertion.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 1]
```diff
@@ -799,9 +799,14 @@ class _DraggableScrollableSheetScrollPosition extends ScrollPositionWithSingleCo
   _DraggableScrollableSheetScrollPosition({
     required super.physics,
     required super.context,
-    super.oldPosition,
+    ScrollPosition? oldPosition,
     required this.getExtent,
-  });
+  }) : super(oldPosition: oldPosition) {
+    if (oldPosition is _DraggableScrollableSheetScrollPosition
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:805]: Do we know that this will always be true? Since this is private implementation?

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:805]: Actually, this is not always true.
This may be another type of position when the widget type changes.
Make a type check here also cause some tests failed.

Comment (Piinks) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:805]: Hmm, is there another way we could indicate this? Perhaps a flag?
Using `is` here is not congruent with the style guide: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-interleaving-multiple-concepts-together

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:805]: oops, this is a bit stumbling for me.
I took a look and here is the only chance to catch old position information.
I agree with the above guidance, but here is just to distinguish whether the old type is consistent with myself, and does not interleave other concepts, I think it is reasonable, what do you think? ： ）

Comment (Piinks) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:805]: I dunno, tbh I am not very familiar with DraggableScrollableSheet, @dnfield may know more.
All of this is private implementation, so it might be ok to distinguish this case.
What tests failed if the type is assumed to be _DraggableScrollableSheetScrollPosition?

I'll reach out to @Hixie on Discord in case this is a style guide exception.

Comment (Piinks) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:805]: I checked to see what tests failed - mostly  `'ScrollPositionWithSingleContext' is not a subtype of type
'_DraggableScrollableSheetScrollPosition?' in type cast`

(I was adding a type cast in the createPosition function of the controller)

What about adding a copyWith to _DraggableScrollableSheetScrollPosition, that way when it is created, you can copy over any ScrollPosition related info (including subclasses like ScrollPositionWithSingleContext)? Just throwing out ideas.. IIRC the copyWith in ScrollBehavior was due to a similar situation. I saw you landed a fix in that recently by the way - thanks!

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart]: @Piinks Thank you so much for catching this bad smell 😄 
 I think with your ideas I found the perfect solution.

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 2]
```diff
@@ -810,6 +810,21 @@ class _DraggableScrollableSheetScrollPosition extends ScrollPositionWithSingleCo
 
   _DraggableSheetExtent get extent => getExtent();
 
+  @override
+  void absorb(ScrollPosition other) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:814]: I agree this approach looks much cleaner and easier to follow.

**Review by Piinks — APPROVED** [review]
LGTM! Thank @xu-baolin!
