### PR TITLE
Fix crash on two finger selection gesture

### LINKED ISSUE #168578: TextField crashes on two-finger selection gesture
### Steps to reproduce

1. Have a TextField. Enter text into the text field
2. Make a selection
3. Move the two edit handles independently with two fingers, then release

Exception:
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/text_selection.dart': Failed assertion: line 759 pos 12:
'_dragStartSelection != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=02_bug.yml

When the exception was thrown, this was the stack:
#2      TextSelectionOverlay._handleSelectionEndHandleDragUpdate (package:flutter/src/widgets/text_selection.dart:759:12)
#3      SelectionOverlay._handleEndHandleDragUpdate (package:flutter/src/widgets/text_selection.dart:1270:28)
#4      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:868:55)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:345:24)
#6      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:868:7)
#7      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:714:11)
#8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:97:12)
#9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#10     _LinkedHashMapMixin.forEach (dart:_compact_hash:764:13)
#11     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:131:7)
#13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:530:19)
#14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:499:22)
#15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:473:11)
#16     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:437:7)
#17     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:394:5)
#18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:341:7)
#19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:308:9)
#20     _invoke1 (dart:ui/hooks.dart:347:13)
#21     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:467:7)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:282:31)
(elided 2 frames from class _AssertionError)

Handler: "onUpdate"
Recognizer:
  PanGestureRecognizer#8943a
════════════════════════════════════════════════════════════════════════════════════════════════════

```

Observed on Android and iOS.

### Expected results

Selection updates without exception

### Actual results

Crash, seen above

### Code sample

<details open><summary>Code sample</summary>

```dart
Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: TextField()),
    );
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel google3, on macOS 14.7.5 23H527 darwin-arm64 (Rosetta), locale en-US) [2.6s]
    • Framework revision b9e982614b (14 days ago), 2025-04-24T00:00:00.000
    • Engine revision b9e982614b
    • Dart version 88e2c816be
```

</details>

Rest of output contains proprietary information

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This change blocks two selection handles from being able to be dragged simultaneously on iOS and the web, this matches the native behavior. On native Android both handles can still be dragged simultaneously this is the behavior observed on Google Keep/ Google Messages and Android's EditText.

Also fixes an issue on iOS where the magnifier would not return after hiding when double tapping and dragging to select and then dragging outside the TextField area. The cause of this issue was because editableText.showMagnifier decides whether to update the magnifier position or show a new one based on whether it was visible, so when it was hidden and we attempt to update it's position, it would try to show a new magnifier which left the magnifier in a broken state. This change makes editableText.showMagnifier depend on whether a magnifier exists instead of just checking it's visibility. Similarly editableText.hideMagnifier now does not depend on the magnifier visibility, instead it internally (selectionOverlay.hideMagnifier) checks if the magnifier exists.

Fixes #168578

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 1]
```diff
@@ -716,7 +716,10 @@ class TextSelectionOverlay {
     final TextPosition position = renderObject.getPositionForPoint(
       Offset(details.globalPosition.dx, centerOfLineGlobal),
     );
-    _dragStartSelection ??= _selection;
+    _dragStartSelection =
+        defaultTargetPlatform == TargetPlatform.iOS || defaultTargetPlatform == TargetPlatform.macOS
+            ? _selection
+            : null;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:722]: Just double checking a logical difference: after this change, on iOS/macOS, it's possible that _dragStartSelection will be overwritten when it is non-null, but previously it wouldn't have been.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 2]
```diff
@@ -858,7 +873,10 @@ class TextSelectionOverlay {
     final TextPosition position = renderObject.getPositionForPoint(
       Offset(details.globalPosition.dx, centerOfLineGlobal),
     );
-    _dragStartSelection ??= _selection;
+    _dragStartSelection =
+        defaultTargetPlatform == TargetPlatform.iOS || defaultTargetPlatform == TargetPlatform.macOS
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/text_selection.dart:877]: Consider adding a quick comment here. It's not immediately obvious to me why we behave differently here based on the platform.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 3]
```diff
@@ -1267,6 +1330,9 @@ class SelectionOverlay {
       _isDraggingEndHandle = false;
       return;
     }
+    if (_blockEndHandleDrag) {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:1333]: I wonder if you could get rid of the _blockStart/EndHandleDrag booleans by checking something like this here instead:

```dart
_isDraggingStartHandle && defaultTargetPlatform == TargetPlatform.iOS || defaultTargetPlatform == TargetPlatform.macOS || kIsWeb
```

That could be a getter to make things cleaner.

**Review by justinmc — APPROVED** [review]
One idea below to possibly reduce the amount of state, otherwise LGTM 👍

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart:877]: I kinda thought the same thing while reviewing 👍

File: packages/flutter/test/material/selection_area_test.dart [hunk 4]
```diff
@@ -364,4 +364,217 @@ void main() {
...
+          ),
+        ),
+      );
+      await tester.pumpAndSettle();
+      final RenderParagraph paragraph = tester.renderObject<RenderParagraph>(
+        find.descendant(of: find.text('one two three four five'), matching: find.byType(RichText)),
+      );
+      final TestGesture gesture = await tester.startGesture(
+        textOffsetToPosition(paragraph, 11),
+      ); // at the 'a'
```
Comment (loic-sharma) [inline packages/flutter/test/material/selection_area_test.dart:396]: Should this be 'e' pos?

**Review by loic-sharma — APPROVED** [review]
LGTM, nice work!

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/text_selection.dart:722]: Good catch, I didn't notice that.

File: packages/flutter/test/material/selection_area_test.dart (hunk 4 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/material/selection_area_test.dart]: Good catch thanks!

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 5]
```diff
@@ -1235,8 +1316,21 @@ class SelectionOverlay {
...
+  /// Whether the selection end handle is currently being dragged.
+  bool get isDraggingEndHandle => _isDraggingEndHandle;
   bool _isDraggingEndHandle = false;
 
+  // Whether the end handle can be dragged.
+  //
+  // On Apple and web platforms only one selection handle can be dragged
+  // at a time, so when the start handle is being dragged on these platforms
+  // the the end handle cannot be dragged.
+  bool get _canDragEndHandle =>
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:1328]: I think these getters and the early returns are really easy to follow now :+1:

**Review by justinmc — APPROVED** [review]
LGTM :+1:

**Comment by Renzo-Olivares** [comment]
Still looking into an issue with the magnifier after this change.

**Review by justinmc — APPROVED** [review]
LGTM 👍 . The main magnifier fix you mentioned since last time is https://github.com/flutter/flutter/pull/168598/commits/42f1efe6f61894010df722f121294119d5f454d0 right?
