### PR TITLE
Delay win-by-default in gesture arena

### LINKED ISSUE #3183: Exception after tapping repeatedly on Components in Material Gallery
Run the Material Gallery sample and tap on the Components drop-down several times in quick succession.

The framework throws this exception:

```
I/flutter ( 5324): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════════════════════════
I/flutter ( 5324): The following exception was raised during performLayout():
I/flutter ( 5324): 'package:flutter/src/rendering/box.dart': Failed assertion: line 511: 'debugDoingThisResize || debugDoingThisLayout ||
I/flutter ( 5324):                   (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)' is not true.
I/flutter ( 5324): Either the assertion indicates an error in the framework itself, or we should provide substantially more information in
I/flutter ( 5324): this error message to help you determine and fix the underlying cause.
I/flutter ( 5324): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5324):   https://github.com/flutter/flutter/issues/new
I/flutter ( 5324): The following RenderObject was being processed when the exception was fired:
I/flutter ( 5324): RenderViewport NEEDS-LAYOUT
I/flutter ( 5324): This RenderObject had the following creator:
I/flutter ( 5324):   Viewport ← Listener ← _GestureSemantics ← RawGestureDetector-[GlobalKey 498787747] ← ScrollableViewport-['Gallery
I/flutter ( 5324):   List'] ← Block ← TwoLevelList ← LayoutId-['_ScaffoldSlot.body'] ← CustomMultiChildLayout ←
I/flutter ( 5324):   NotificationListener<ScrollNotification> ← ⋯
I/flutter ( 5324): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 5324):   RenderPadding relayoutSubtreeRoot=up1
I/flutter ( 5324):     RenderBlock relayoutSubtreeRoot=up2
I/flutter ( 5324):       RenderDecoratedBox relayoutSubtreeRoot=up3
I/flutter ( 5324):         RenderPadding relayoutSubtreeRoot=up4
I/flutter ( 5324):           RenderFlex relayoutSubtreeRoot=up5
I/flutter ( 5324):       RenderDecoratedBox relayoutSubtreeRoot=up3
I/flutter ( 5324):         RenderPadding relayoutSubtreeRoot=up4
I/flutter ( 5324):           RenderFlex relayoutSubtreeRoot=up5
I/flutter ( 5324):       RenderDecoratedBox relayoutSubtreeRoot=up3
I/flutter ( 5324):         RenderPadding relayoutSubtreeRoot=up4
I/flutter ( 5324):           RenderFlex relayoutSubtreeRoot=up5
I/flutter ( 5324): Stack trace:
I/flutter ( 5324): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter ( 5324): #1      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:511)
I/flutter ( 5324): #2      RenderBox.size (package:flutter/src/rendering/box.dart:501)
I/flutter ( 5324): #3      RenderInkFeatures.splashAt (package:flutter/src/material/material.dart:216)
I/flutter ( 5324): #4      _InkResponseState._handleTapDown (package:flutter/src/material/ink_well.dart:96)
I/flutter ( 5324): #5      TapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:77)
I/flutter ( 5324): #6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:57)
I/flutter ( 5324): #7      GestureArenaManager._tryToResolveArena (package:flutter/src/gestures/arena.dart:138)
I/flutter ( 5324): #8      GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:155)
I/flutter ( 5324): #9      GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:45)
I/flutter ( 5324): #10     OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:77)
I/flutter ( 5324): #11     OneSequenceGestureRecognizer.dispose (package:flutter/src/gestures/recognizer.dart:82)
I/flutter ( 5324): #12     _DragGestureRecognizer.dispose (package:flutter/src/gestures/drag.dart:136)
I/flutter ( 5324): #13     RawGestureDetectorState._syncAll (package:flutter/src/widgets/gesture_detector.dart:381)
I/flutter ( 5324): #14     RawGestureDetectorState.replaceGestureRecognizers (package:flutter/src/widgets/gesture_detector.dart:353)
I/flutter ( 5324): #15     ScrollableState.updateGestureDetector (package:flutter/src/widgets/scrollable.dart:569)
I/flutter ( 5324): #16     _ScrollableViewportState._handlePaintOffsetUpdateNeeded (package:flutter/src/widgets/scrollable.dart:687)
I/flutter ( 5324): #17     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:305)
I/flutter ( 5324): #18     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1100)
I/flutter ( 5324): #19     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:703)
I/flutter ( 5324): #20     BindingBase&Scheduler&Gesturer&Services&Renderer.beginFrame (package:flutter/src/rendering/binding.dart:88)
I/flutter ( 5324): #21     WidgetFlutterBinding.beginFrame (package:flutter/src/widgets/binding.dart:103)
I/flutter ( 5324): #22     BindingBase&Scheduler&Gesturer&Services&Renderer._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:82)
I/flutter ( 5324): #23     BindingBase&Scheduler.invokeFrameCallback (package:flutter/src/scheduler/scheduler.dart:270)
I/flutter ( 5324): #24     BindingBase&Scheduler.handleBeginFrame (package:flutter/src/scheduler/scheduler.dart:247)
I/flutter ( 5324): #25     _beginFrame (file:///ssd2/sky/engine/src/out/android_Debug/gen/sky/bindings/hooks.dart:48)
```

### PR DESCRIPTION
**Pull request by abarth**
Wait until the end of the microtask to tell gesture recognizers that
they've won in the gesture arena. This lets recognizers dispose reject
themselves at arbitrary times without triggering gestures in awkward
call stacks.

Fixes #3183

### CODE REVIEW

**Comment by abarth** [comment]
Not really ready for review.  Definitely needs test.

**Comment by abarth** [comment]
@Hixie Ready for review now.

File: packages/flutter/lib/src/gestures/multidrag.dart [hunk 1]
```diff
@@ -168,7 +168,8 @@ abstract class MultiDragGestureRecognizer<T extends MultiDragPointerState> exten
   void acceptGesture(int pointer) {
     assert(_pointers != null);
     T state = _pointers[pointer];
-    assert(state != null);
+    if (state == null)
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/multidrag.dart]: add a comment saying why it might be null (presumably because it's not in the list, maybe because it's been cancelled already?)

File: packages/flutter/lib/src/gestures/recognizer.dart [hunk 2]
```diff
@@ -57,7 +57,7 @@ abstract class GestureRecognizer extends GestureArenaMember {
 /// which manages each pointer independently and can consider multiple
 /// simultaneous touches to each result in a separate tap.
 abstract class OneSequenceGestureRecognizer extends GestureRecognizer {
-  final List<GestureArenaEntry> _entries = <GestureArenaEntry>[];
+  final Map<int, GestureArenaEntry> _entries = <int, GestureArenaEntry>{};
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/recognizer.dart]: ?

File: packages/flutter/test/gestures/double_tap_test.dart [hunk 3]
```diff
@@ -163,151 +163,145 @@ void main() {
...
     };
 
-    new FakeAsync().run((FakeAsync async) {
-      tap.addPointer(down1);
-      GestureBinding.instance.gestureArena.close(1);
-      expect(doubleTapRecognized, isFalse);
-      GestureBinding.instance.pointerRouter.route(down1);
-      expect(doubleTapRecognized, isFalse);
+    tap.addPointer(down1);
+    GestureBinding.instance.gestureArena.close(1);
```
Comment (Hixie) [inline packages/flutter/test/gestures/double_tap_test.dart]: you could make this tester.closeArena

**Comment by Hixie** [comment]
LGTM

File: packages/flutter/lib/src/gestures/recognizer.dart (hunk 2 above)
Comment (Hixie) [inline packages/flutter/lib/src/gestures/recognizer.dart]: this looks like it was accidental?
