### PR TITLE
Handle trying to upgrade Flutter with no upstream

### LINKED ISSUE #1084: flutter upgrade might want to check that clone is on master branch?
Hi,

I just ran `flutter upgrade` and I got this error:

```
~/flutter/round_band_3980 $ flutter upgrade
From github.com:flutter/flutter
   9487197..a271eb5  alpha      -> origin/alpha
   5af62fa..8e81009  gcm        -> origin/gcm
   9c8c74e..a271eb5  master     -> origin/master
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> embedder-libs
```

I realized that my local clone of flutter was on a custom branch. Once I put my local clone of flutter on the master branch, `flutter upgrade` did the right thing.

This is probably a rare thing, but if the expectation is that `flutter upgrade` requires your clone to be on master, maybe we can check for that?

Thanks!

### PR DESCRIPTION
**Pull request by abarth**
Fixes #1084

### CODE REVIEW

**Comment by abarth** [comment]
@devoncarew @chinmaygarde

**Comment by chinmaygarde** [comment]
lgtm

File: packages/flutter_tools/lib/src/commands/upgrade.dart [hunk 1]
```diff
@@ -14,6 +14,15 @@ class UpgradeCommand extends FlutterCommand {
 
   @override
   Future<int> runInProject() async {
+    try {
+      runCheckedSync([
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/upgrade.dart]: `<String>[...]`
