### PR TITLE
Fixes crash when adding and removing mulitple page-based route

### LINKED ISSUE #177322: LateError at ModalRoute.changedInternalState
### Steps to reproduce

b/423567727

crash observe in logging services

```
(late_helper.dart?cl=813134069:31:3)	throwUnnamedLateFieldNI
(routes.dart?cl=813134069:2324:21)	ModalRoute.changedInternalState
(routes.dart?cl=813134069:2193:5)	ModalRoute.didPopNext
(navigator.dart?cl=813134069:4489:21)	NavigatorState._flushHistoryUpdates
(navigator.dart?cl=813134069:4390:8)	NavigatorState._flushHistoryUpdates[function-entry$0]
(navigator.dart?cl=813134069:4381:5)	NavigatorState._updatePages
(navigator.dart?cl=813134069:4016:7)	NavigatorState.didUpdateWidget
(framework.dart?cl=813134069:5994:49)	StatefulElement.update
(framework.dart?cl=813134069:4037:9)	Element.updateChild
(framework.dart?cl=813134069:5844:7)	ComponentElement.performRebuild
```

no repro available.

### PR DESCRIPTION
**Pull request by chunhtai**
fixes https://github.com/flutter/flutter/issues/177322

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 1]
```diff
@@ -184,6 +184,9 @@ abstract class Route<T> extends _RoutePlaceholder {
   NavigatorState? get navigator => _navigator;
   NavigatorState? _navigator;
 
+  bool get _installed => _navigator != null;
+  bool _installedBy(NavigatorState state) => _navigator == state;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/navigator.dart]: Nit: I'm wondering if there is a better name here because I expected this to be an instance of NavigatorState or something. _isInstalledIn?

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 2]
```diff
@@ -4484,9 +4487,12 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin, Res
           assert(entry.currentState == _RouteLifecycle.remove);
           continue;
         case _RouteLifecycle.remove:
-          if (!seenTopActiveRoute) {
+          // Routes that are not yet added (_installed == false) will exit as if
+          // they have never been on the navigator. They shouldn't announce
+          // their presents.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/navigator.dart]: "presents" => "presence"

**Review by justinmc — APPROVED** [review]
LGTM with nits 👍
