### PR TITLE
Fix extra numbers showing up when enabling VoiceControl

### LINKED ISSUE #158477: iOS Voice Control number label shown on parent widget with Semantic label when child widget is actionable
### Steps to reproduce

1. Create a parent widget, and wrap it in Semantics(label: 'Hello world)
2. Add a child widget with an action, like TextButton
3. Activate Voice Control on iOS
4. Say "Show numbers"
5. Notice a number is shown on the parent, and it has no actions

### Expected results

The parent AND child widgets show a number label, even though the parent has no actions.

### Actual results

Only child widget should show a number label, not the parent

### Code sample

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Repro examples'),
        ),
        body: Semantics(
          label: 'Example',
          container: true,
          child: Center(
            child: TextButton(
              child: const Text('Hello World'),
              onPressed: () {},
            ),
          ),
        ),
      ),
    );
  }
}
```
### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by LouiseHsu**
Fixes https://github.com/flutter/flutter/issues/158477 and https://github.com/flutter/flutter/issues/156368.

The excess numbers in both PRs are caused by all `SemanticObjects` returning `YES` for `accessibilityRespondsToUserInteraction`, even if it has no semantic actions. For example, a SemanticObject with just a label has semantic information (the label) but no action. This PR adds a check, ensuring that an `SemanticObjects` has at least one accessible action before returning `YES`

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm [hunk 1]
```diff
@@ -836,6 +836,22 @@ - (UIAccessibilityTraits)accessibilityTraits {
   return traits;
 }
 
+- (BOOL)accessibilityRespondsToUserInteraction {
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm:839]: @chunhtai I'm worried this logic might break if/when we add more "system" actions. Would you have any recommendations on how to future-proof this method?

For example, should we push `kSystemActions` down to `//flutter/lib/ui/semantics/semantics_node.h`?

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm [hunk 2]
```diff
@@ -756,6 +756,160 @@ - (void)testRadioButtonIsNotSwitchButton {
...
+  nodes[root_node.id] = root_node;
+  bridge->UpdateSemantics(/*nodes=*/nodes, /*actions=*/actions);
+
+  SemanticsObjectContainer* rootContainer = flutterView.accessibilityElements[0];
+  FlutterSemanticsObject* rootNode = [rootContainer accessibilityElementAtIndex:0];
+
+  XCTAssertFalse(rootNode.accessibilityRespondsToUserInteraction);
+}
+
+- (void)testSemanticObjectWithAccessibiltyFlagsMarkedAsResponsiveToUserInteraction {
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm:804]:
```suggestion
- (void)testSemanticObjectWithAccessibilityFlagsMarkedAsResponsiveToUserInteraction {
```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm [hunk 3]
```diff
@@ -756,6 +756,160 @@ - (void)testRadioButtonIsNotSwitchButton {
   XCTAssertNil(rootNode.accessibilityValue);
 }
 
+- (void)testSemanticObjectWithNoAccessibiltyFlagNotMarkedAsResponsiveToUserInteraction {
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm:759]:
```suggestion
- (void)testSemanticObjectWithNoAccessibilityFlagNotMarkedAsResponsiveToUserInteraction {
```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm [hunk 4]
```diff
@@ -756,6 +756,160 @@ - (void)testRadioButtonIsNotSwitchButton {
...
+  nodes[root_node.id] = root_node;
+  bridge->UpdateSemantics(/*nodes=*/nodes, /*actions=*/actions);
+
+  SemanticsObjectContainer* rootContainer = flutterView.accessibilityElements[0];
+  FlutterSemanticsObject* rootNode = [rootContainer accessibilityElementAtIndex:0];
+
+  XCTAssertTrue(rootNode.accessibilityRespondsToUserInteraction);
+}
+
+- (void)testLabeledParentAndChildNotInteractive {
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm:850]: 5 years from now, someone might wonder why we have this hyper specific test and if it can be removed. Leaving a breadcrumb as to why we added this test can make our lives much easier. Consider adding something like:

```suggestion
// Regression test for:
// https://github.com/flutter/flutter/issues/158477
- (void)testLabeledParentAndChildNotInteractive {
```

**Review by loic-sharma — APPROVED** [review]

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm (hunk 1 above)
Comment (chunhtai) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm:839]: yeah, that sounds like a better way of keeping track of this.

Comment (chunhtai) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm:839]: also should we implement this in SemanticsObject class instead? there are subclasses such as switch that extends from SemanticsObject, for example, a disabled switch probability shouldn't responseToUserInteraction as well.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm [hunk 5]
```diff
@@ -756,6 +756,162 @@ - (void)testRadioButtonIsNotSwitchButton {
...
+
+  SemanticsObjectContainer* rootContainer = flutterView.accessibilityElements[0];
+  FlutterSemanticsObject* rootNode = [rootContainer accessibilityElementAtIndex:0];
+
+  XCTAssertTrue(rootNode.accessibilityRespondsToUserInteraction);
+}
+
+// Regression test for:
+// https://github.com/flutter/flutter/issues/158477
+- (void)testLabeledParentAndChildNotInteractive {
```
Comment (chunhtai) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm:852]: Can you also check node with action will return YES for the property?

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm (hunk 1 above)
Comment (loic-sharma) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm:839]: This is a good question. I believe `FlutterSwitchSemanticsObject` works as expected as it overrides traits, and I didn't see any issues Material 3 switches. However, I **_think_** we _might_ need a similar fix for `FlutterScrollableSemanticsObject`.

Voice Control shows incorrect numbers on the Material 3 demo, and I suspected `FlutterScrollableSemanticsObject` but I didn't have the time to root cause it. @LouiseHsu could you check if pushing this logic down to `SemanticsObject` fixes the Material 3 demo app?

Comment (LouiseHsu) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm:839]: I tried this with our fix, and the numbers did change, but not for the number on the grey bar 
| Before Fix | After Fix |
| ------------- | ------------- |
| before_fix |after_fix |

Interestingly if i comment out the other sibling containers the marker disappears. I think the root cause is different than the fix for these two issues. 
just_actions

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm (hunk 5 above)
Comment (LouiseHsu) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/accessibility_bridge_test.mm:852]: i do that in `testSemanticObjectWithAccessibilityFlagsMarkedAsResponsiveToUserInteraction` here!
https://github.com/flutter/flutter/pull/163593/files#diff-b9dacacaa1535aa4dad51d0cf8af7a0c941d8cd7a1193e3769914108f654dea5R839

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm [hunk 6]
```diff
@@ -781,6 +781,18 @@ - (void)accessibilityElementDidLoseFocus {
   }
 }
 
+- (BOOL)accessibilityRespondsToUserInteraction {
+  if ((self.node.actions & flutter::~kSystemActions) != 0) {
```
Comment (chunhtai) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm:785]: I am surprise this works, shouldn't this be `~flutter::kSystemActions`

**Review by chunhtai — APPROVED** [review]
LGTM, just one question

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm (hunk 6 above)
Comment (LouiseHsu) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm]: it doesnt work cuz the tests are failing 😅. My bad I was copy and pasting my changes cuz I had to force push to an earlier commit

File: engine/src/flutter/lib/ui/semantics/semantics_node.h [hunk 7]
```diff
@@ -57,6 +57,10 @@ const int kHorizontalScrollSemanticsActions =
 const int kScrollableSemanticsActions =
     kVerticalScrollSemanticsActions | kHorizontalScrollSemanticsActions;
 
+const int kSystemActions =
```
Comment (loic-sharma) [inline engine/src/flutter/lib/ui/semantics/semantics_node.h:60]: @chunhtai What do you think of a comment like this?

```suggestion
// The following are actions that aren't user-initiated.
const int kSystemActions =
```

Comment (LouiseHsu) [reply engine/src/flutter/lib/ui/semantics/semantics_node.h:60]: Im not @chunhtai but I agree

Comment (chunhtai) [reply engine/src/flutter/lib/ui/semantics/semantics_node.h:60]: SGTM

**Review by cbracken — CHANGES_REQUESTED** [review]

File: engine/src/flutter/lib/ui/semantics/semantics_node.h [hunk 8]
```diff
@@ -57,6 +57,11 @@ const int kHorizontalScrollSemanticsActions =
 const int kScrollableSemanticsActions =
     kVerticalScrollSemanticsActions | kHorizontalScrollSemanticsActions;
 
+/// The following actions are not user-initiated.
+const int kSystemActions =
```
[the remark this answers is not in the document]
Comment (cbracken) [reply engine/src/flutter/lib/ui/semantics/semantics_node.h:61]: (Sorry for the last minute comment / autosubmit removal)

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm [hunk 9]
```diff
@@ -781,6 +781,18 @@ - (void)accessibilityElementDidLoseFocus {
   }
 }
 
+- (BOOL)accessibilityRespondsToUserInteraction {
+  if ((self.node.actions & ~flutter::kSystemActions) != 0) {
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm:785]: a bit hard to read here. mind adding a comment?

Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm:785]: if im reading it right, if a node has actions (other than just system actions), then it should respond to user interaction?

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm [hunk 10]
```diff
@@ -781,6 +781,18 @@ - (void)accessibilityElementDidLoseFocus {
...
+    return true;
+  }
+
+  if (!self.node.customAccessibilityActions.empty()) {
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm:789]: what's the diff between `self.node.actions` vs `self.node.customAccessibilityActions`

Comment (LouiseHsu) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm:789]: iirc `customAccessibilityActions` becomes `CustomSemanticsAction` in the framework. Its basically allows the developer to define more complex interactions like maybe drag and drop. Actions are OS defined actions like tap, scroll, etc

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm (hunk 9 above)
Comment (LouiseHsu) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm:786]: added a comment!

File: engine/src/flutter/lib/ui/semantics/semantics_node.h (hunk 8 above)
[the remark this answers is not in the document]
Comment (LouiseHsu) [reply engine/src/flutter/lib/ui/semantics/semantics_node.h]: updated!

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

Woohoo! Thanks!
