### PR TITLE
Fix directional focus in nested scrollables with different axis

### LINKED ISSUE #160431: Focus traversal into nested scrollable wrongly prevented
### Steps to reproduce

1. Run example with `flutter run -d chrome`
2. Press tab to move focus to the topmost button
3. Move focus down with arrowDown key on your keyboard
Observe focus is moved down 1 row with each press, alternating between the fullwidth buttons and items in horizontal ListViews

4. Scroll down so neither top or bottom is visible
5. Move focus up or down with keys
Observe focus skips over items in the horizontal ListViews

### Expected results

Focus traversal behaves consistently when inside the same scrollable, no matter the scroll position

### Actual results

Focus traversal only enters nested scrollables when at start or end of the outer scollable

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(debugShowCheckedModeBanner: false, home: Test());
  }
}

class Test extends StatelessWidget {
  const Test({super.key});

  @override
  Widget build(BuildContext context) {
    return Shortcuts(
        shortcuts: {
          LogicalKeySet(LogicalKeyboardKey.arrowLeft):
              const DirectionalFocusIntent(TraversalDirection.left),
          LogicalKeySet(LogicalKeyboardKey.arrowRight):
              const DirectionalFocusIntent(TraversalDirection.right),
          LogicalKeySet(LogicalKeyboardKey.arrowUp):
              const DirectionalFocusIntent(TraversalDirection.up),
          LogicalKeySet(LogicalKeyboardKey.arrowDown):
              const DirectionalFocusIntent(TraversalDirection.down),
        },
        child: Center(
            child: ListView.builder(
                scrollDirection: Axis.vertical,
                itemCount: 30,
                itemBuilder: (context, i) {
                  if (i % 2 == 0) {
                    return ElevatedButton(
                        onPressed: () {}, child: Text('Button $i'));
                  } else {
                    return SizedBox(
                        height: 100,
                        child: ListView.builder(
                          scrollDirection: Axis.horizontal,
                          itemCount: 15,
                          itemBuilder: (context, j) {
                            return ElevatedButton(
                                onPressed: () {}, child: Text('Button ${j}'));
                          },
                        ));
                  }
                })));
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/5fee3262-bd52-4e73-aae8-f2e6e2d55982

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.26100.2605], locale en-GB)
    • Flutter version 3.27.1 on channel stable at C:\Baze\deps\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (18 hours ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\emilshes\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:/jdk-17\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.2+8-86)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.12.35506.116
    • Windows 10 SDK version 10.0.20348.0
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at C:\Users\emilshes\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[✓] Connected device (4 available)
    • SML 5051W (mobile) • 10.40.14.111:5555 • android-arm    • Android 9 (API 28)
    • Windows (desktop)  • windows           • windows-x64    • Microsoft Windows [Version 10.0.26100.2605]
    • Chrome (web)       • chrome            • web-javascript • Google Chrome 131.0.6778.140
    • Edge (web)         • edge              • web-javascript • Microsoft Edge 131.0.2903.99

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by romaingyh**
Related issue : #172854 
Fixes #160431

This PR fixes the focus when navigating with keyboard arrows or TV remote d-pad in a nested lists with different axis and a fixed focusable at the top.
It's a common setup for apps that deal with images or videos.

The problem is that when the vertical scrollbar has scrolled and you want to scroll back to the top without the mouse, only using keyboard up arrow to jump from widgets to widgets in the list until reaching the top, the fixed top focusable widget wrongly takes the focus instead of letting the vertical scrollable scroll.

I think the video bellow explain the problem better.

| Before this PR | After this PR |
|--------|--------|
| https://github.com/user-attachments/assets/54160e0c-abe5-4181-9aea-8351ce5f35b5 | https://github.com/user-attachments/assets/eee32175-37eb-44a6-a7c2-a751fc82d592 |

Note that I had to edit two existing tests because they were failing with my edits. However, I think these tests were testing a bad behavior.

For example here is the visualization of the `Focus traversal inside a vertical scrollable scrolls to stay visible` test case before this PR :

https://github.com/user-attachments/assets/be843ae8-a0df-411e-971c-3bf763c457e0

Test was green bug the focus behavior is weird. When pressing arrow down from item 3 we would expect a scroll and item 4 to be focused, here it's footer that is focused and when we press arrow down again item 5 is focused and item 4 is skipped.

Here is the behavior after this PR and the test edited :

https://github.com/user-attachments/assets/b90757a8-042d-4d53-b7e6-19b9141cc83f

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by Piinks** [comment]
Hey @romaingyh it looks like we might have duplicate PRs/Issues here.
Can you see if https://github.com/flutter/flutter/pull/172283 and https://github.com/flutter/flutter/issues/160431 are the same PR/Issue?

File: packages/flutter/test/widgets/focus_traversal_test.dart [hunk 1]
```diff
@@ -2562,14 +2563,14 @@ void main() {
         expect(controller.offset, equals(0.0));
 
         // Go down until we hit the bottom of the visible area.
-        for (int i = 1; i <= 4; ++i) {
+        for (int i = 1; i <= 3; ++i) {
```
Comment (Piinks) [inline packages/flutter/test/widgets/focus_traversal_test.dart:2566]: Can you share why these tests change?

Comment (romaingyh) [reply packages/flutter/test/widgets/focus_traversal_test.dart:2566]: These tests were ok before the PR but they were actually testing a bad behavior. I shared an explaination and two video before/after in the PR description

**Comment by romaingyh** [comment]
> Hey @romaingyh it looks like we might have duplicate PRs/Issues here. Can you see if #172283 and #160431 are the same PR/Issue?

Hello @Piinks, you're right they are totally duplicate, sorry for not catching it before. I don't know which PR do you want to keep, I think this one has better tests and is more complete because without removing `!focusedScrollable.position.atEdge` the bug is not fully fixed.

**Comment by Andro999b** [comment]
@romaingyh @Piinks I think we should prioritize this MR. I also don't have a time to work in my MR for the next couple weeks.

File: packages/flutter/test/widgets/focus_traversal_test.dart [hunk 2]
```diff
@@ -2758,6 +2759,258 @@ void main() {
...
+          await tester.pump();
+          expect(gridNodes[row][focusedColumn].hasPrimaryFocus, isTrue);
+        }
+
+        // Only now should we reach the sticky button
+        await tester.sendKeyEvent(LogicalKeyboardKey.arrowUp);
+        await tester.pump();
+        expect(stickyButtonNode.hasPrimaryFocus, isTrue);
+      },
+      skip: isBrowser,
```
Comment (Piinks) [inline packages/flutter/test/widgets/focus_traversal_test.dart:2885]: Why do these skip on browser? The analyzer failure is due to these not being attributed with comments s to why they are being skipped. See other skips for an example.

**Review by Piinks — COMMENTED** [review]
Closed the other PR per the last comment.
@romaingyh can you confirm if this actually does resolve https://github.com/flutter/flutter/issues/160431 as well since we identified it as a potential dupe?

File: packages/flutter/test/widgets/focus_traversal_test.dart (hunk 2 above)
Comment (romaingyh) [reply packages/flutter/test/widgets/focus_traversal_test.dart:2885]: I copy/pasted the test above which is a bit similar as a base for my test the one above is skipped on browser because of this https://github.com/flutter/flutter/issues/35347

Should I add the same comment ? How can I see If this issue break the new test ?

**Comment by romaingyh** [comment]
@Piinks I confirm #160431 is not reproducible with this PR


https://github.com/user-attachments/assets/5368c6cb-0606-45ca-b8df-d5888491b6ac

File: packages/flutter/test/widgets/focus_traversal_test.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter/test/widgets/focus_traversal_test.dart:2885]: Web tests run in CI here in the PR, if they are affected they should fail without the skip. Otherwise, there has to be a comment there pointing to the reason why the test is skipped, like the others. :)
This should resolve the analyzer failure here.

**Comment by Piinks** [comment]
> I confirm https://github.com/flutter/flutter/issues/160431 is not reproducible with this PR

Thanks! Is it covered by a test here?

**Comment by romaingyh** [comment]
> > I confirm #160431 is not reproducible with this PR
> 
> Thanks! Is it covered by a test here?

Yes I think it's covered with the same test as my issue "Focus traversal with horizontal scrollables inside a vertical scrollable handles vertical navigation correctly"

**Review by Piinks — APPROVED** [review]
LGTM thank you!

File: packages/flutter/test/widgets/focus_traversal_test.dart [hunk 3]
```diff
@@ -2758,6 +2759,256 @@ void main() {
...
+                      );
+                    },
+                  ),
+                ),
+              ],
+            ),
+          ),
+        );
+
+        // Start by focusing the sticky button
```
Comment (justinmc) [inline packages/flutter/test/widgets/focus_traversal_test.dart]: Nit: Periods at the ends of these comments.

**Review by justinmc — APPROVED** [review]
LGTM, thank you for fixing this!

**Comment by romaingyh** [comment]
CI `linux web_canvaskit_tests_0` and `linux web_skwasm_tests_1` are failing on my two new tests. Looking at [stdout](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8706723146079405313/+/u/run_test.dart_for_web_canvaskit_tests_shard_and_subshard_0/stdout?format=raw) it seems we're facing #35347 like the other keyboard focus related tests.

I think it's reasonable to do the same thing on these two tests : skip on web and add a comment referencing the issue
