### PR TITLE
Wrap `ShutdownHook` calls to avoid crashing the tool

### LINKED ISSUE #57351: Shutdown hooks shouldn't crash the tool
We should probably handle a shutdown hook that throws an exception similarly to how we handle exceptions from signal handlers. See shutdown hook processing here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/process.dart#L118

and signal handler processing here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/signals.dart#L134

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/57351.

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/process.dart [hunk 1]
```diff
@@ -65,15 +66,33 @@ class _DefaultShutdownHooks implements ShutdownHooks {
...
-      final List<Future<dynamic>> futures = <Future<dynamic>>[
-        for (final ShutdownHook shutdownHook in registeredHooks)
-          if (shutdownHook() case final Future<dynamic> result) result,
-      ];
-      await Future.wait<dynamic>(futures);
+      final List<Future<void>> futures = <Future<void>>[];
+      for (final ShutdownHook shutdownHook in registeredHooks) {
+        try {
+          final Future<void> future = asyncGuard<void>(
+            () async => shutdownHook(),
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/base/process.dart:76]: Can this just be `shutdownHook` since `ShutdownHook` is just `FutureOr<void> Function()`?

**Review by bkonyi — APPROVED** [review]

File: packages/flutter_tools/lib/src/base/process.dart (hunk 1 above)
Comment (matanlurey) [reply packages/flutter_tools/lib/src/base/process.dart:76]: No, because asyncGuard requires `Future<T>` and `shutdownHook` is `FutureOr<>`.
