### PR TITLE
Prevent looking up inherited widget values from initState()

### LINKED ISSUE #5491: Inherit from widget should throw an exception in initState
If you read an inherited value in initState, you won't get the new value when it changes.  We should throw an exception if you try that to give faster feedback.

See #5483 for what goes wrong otherwise.

/cc @HansMuller @Hixie

### PR DESCRIPTION
**Pull request by HansMuller**
Looking up an inherited widget with `BuildContext.inheritFromWidgetOfExactType()` from an initState() method now causes an assert.

Static methods like Theme.of() use inheritFromWidgetOfExactType(). Using it at initState() time is ill-advised because updates to the inherited widget only cause the dependent widget to rebuild. Initializations based on the inherited widget that occur in initState() will not rerun when the widget is rebuilt.

There were a handful of cases like this in the code base.

Fixes #5491

### CODE REVIEW

**Comment by HansMuller** [comment]
cc @Hixie

File: packages/flutter/lib/src/widgets/framework.dart [hunk 1]
```diff
@@ -1706,7 +1706,7 @@ abstract class Element implements BuildContext {
   void _updateInheritance() {
     assert(_active);
     _inheritedWidgets = _parent?._inheritedWidgets;
-  }
+   }
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: extraneous space

File: packages/flutter/lib/src/widgets/framework.dart [hunk 2]
```diff
@@ -2185,6 +2185,18 @@ class StatefulElement extends ComponentElement {
   }
 
   @override
+  InheritedWidget inheritFromWidgetOfExactType(Type targetType) {
+    assert(() {
+      if (state._debugLifecycleState == _StateLifecycle.ready)
+        return true;
+      throw new FlutterError(
+        'inheritFromWidgetOfExactType($targetType) was called before ${_state.runtimeType}.initState() completed.'
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/framework.dart]: This string should be followed by a newline and then a paragraph explaining the reasoning and what to do about it

File: packages/flutter/lib/src/widgets/image.dart [hunk 3]
```diff
@@ -188,12 +188,6 @@ class _ImageState extends State<Image> {
   ImageInfo _imageInfo;
 
   @override
-  void initState() {
-    super.initState();
-    _resolveImage();
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/image.dart]: this one is wrong. We do want to do this in initState. It's safe to do so because dependenciesChanged takes care of the reevaluation when the inherited values change.

File: packages/flutter/lib/src/widgets/image.dart [hunk 4]
```diff
@@ -240,6 +234,8 @@ class _ImageState extends State<Image> {
 
   @override
   Widget build(BuildContext context) {
+    if (_imageStream == null)
+      _resolveImage();
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/image.dart]: _resolveImage isn't cheap enough to do on every build

**Comment by Hixie** [comment]
Let's talk tomorrow about how to still enable this for the rare cases where it's done right for a good reason...

File: packages/flutter/lib/src/widgets/image.dart (hunk 3 above)
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/image.dart]: Right, the existing code wasn't wrong since subsequent updates to MediaQuery and DefaultAssetBundle were handled by dependenciesChanged().  Moving this one time init to build() avoids the need to define some new way to indicate that an inherited reference widget at initState() time is safe. 

This appears to have been the only example of its kind in our code base. If more cases crop up I suppose we'll need to add a way to defeat the assertion added by this PR.

File: packages/flutter/lib/src/widgets/image.dart (hunk 4 above)
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/image.dart]: Yes it would. In this case it's only happening once, since _resolveImage inits _imageStream.

File: packages/flutter/lib/src/widgets/image.dart [hunk 5]
```diff
@@ -240,6 +234,14 @@ class _ImageState extends State<Image> {
 
   @override
   Widget build(BuildContext context) {
+    // This one-time initialization could have been done in initState() since
+    // changes to the inherited widgets that _resolveImage depends on, notably
+    // DefaultAssetBundle, are handle by the dependenciesChanged() method. We're
+    // doing it here instead to avoid the assert that disallows references to
+    // inherited widgets at initState() time.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/image.dart]: "...because we have found that asserts catches bugs frequently, and is therefore worth this minor inconvenience here."

File: packages/flutter/lib/src/widgets/image.dart [hunk 6]
```diff
@@ -240,6 +234,15 @@ class _ImageState extends State<Image> {
 
   @override
   Widget build(BuildContext context) {
+    // This one-time initialization could have been done in initState() since
+    // changes to the inherited widgets that _resolveImage depends on, notably
+    // DefaultAssetBundle, are handle by the dependenciesChanged() method. We're
+    // doing it here instead to avoid the assert that disallows references to
+    // inherited widgets at initState() time. We've found that assert to be a reliable
+    // source of real bugs, and is therefore worth this minor inconvenience here.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/image.dart]: nitty nit nit: oops, my grammar was bad. "and that it is" rather than "and is".

File: packages/flutter/test/widget/inherited_test.dart [hunk 7]
```diff
@@ -437,4 +460,16 @@ void main() {
...
+  testWidgets('initState() dependency on Inherited asserts', (WidgetTester tester) async {
+    // This is a regression test for https://github.com/flutter/flutter/issues/5491
+    bool exceptionCaught = false;
+
+    TestInherited parent = new TestInherited(child: new ExpectFail(() {
+      exceptionCaught = true;
+    }));
+    await tester.pumpWidget(parent);
+
+    expect(exceptionCaught, isTrue);
```
Comment (Hixie) [inline packages/flutter/test/widget/inherited_test.dart]: fwiw you could also use the widget tester's built-in "takeException" API to do this.

**Comment by Hixie** [comment]
LGTM
