### PR TITLE
180162 fix radio list tile and switch list tile accept widget states controller

### LINKED ISSUE #180162: `RadioListTile`, `CheckboxListTile`, and `SwitchListTile` should accept a `WidgetStatesController` for their backing `ListTile`
### Use case

I would like to listen to the state of a `RadioListTile`, `CheckboxListTile` or `SwitchListTile` (e.g., `pressed` or `hovered`) using a `WidgetStatesController`

### Proposal

Add a `statesController` parameter to `RadioListTile`, `CheckboxListTile`, and `SwitchListTile`, which will be forwarded to the `ListTile`.

### PR DESCRIPTION
**Pull request by AnishTiwari5077**
fixes #180162  
RadioListTile, CheckboxListTile, and SwitchListTile accepts a WidgetStatesController for their backing ListTile

### CODE REVIEW

File: DEPS [hunk 1]
```diff
@@ -988,4 +988,4 @@ hooks = [
       'engine/src/flutter/tools/fuchsia/test_scripts/gen_build_defs.py',
     ],
   },
-]
+]
```
Comment (QuncCccccc) [inline DEPS]: We might want to revert this change.

File: packages/flutter/test/material/switch_list_tile_test.dart [hunk 2]
```diff
@@ -326,6 +326,31 @@ void main() {
     expect(tester.getTopLeft(find.byType(Switch)).dx, 20.0); // contentPadding.end = 20
     expect(tester.getTopRight(find.text('L')).dx, 790.0); // 800 - contentPadding.start
   });
+  testWidgets('SwitchListTile forwards statesController to ListTile', (WidgetTester tester) async {
```
Comment (QuncCccccc) [inline packages/flutter/test/material/switch_list_tile_test.dart:330]:
```suggestion

  testWidgets('SwitchListTile forwards statesController to ListTile', (WidgetTester tester) async {
```

File: packages/flutter/test/material/checkbox_list_tile_test.dart [hunk 3]
```diff
@@ -40,6 +40,28 @@ void main() {
     await tester.tap(find.byType(Checkbox));
     expect(log, equals(<dynamic>[false, '-', false]));
   });
+  testWidgets('CheckboxListTile forwards statesController to ListTile', (
```
Comment (QuncCccccc) [inline packages/flutter/test/material/checkbox_list_tile_test.dart:43]:
```suggestion

  testWidgets('CheckboxListTile forwards statesController to ListTile', (
```

**Review by QuncCccccc — APPROVED** [review]
LGTM with nits. Thanks for your contribution:)

**Review by dkwingsmt — COMMENTED** [review]
LGTM except for reverting the change in `DEPS`

File: DEPS (hunk 1 above)
Comment (AnishTiwari5077) [reply DEPS]: Revert unintended DEPS change

Comment (AnishTiwari5077) [inline DEPS]: Revert unintended DEPS change

**Review by AnishTiwari5077 — COMMENTED** [review]
Revert unintended DEPS change

File: DEPS (hunk 1 above)
Comment (dkwingsmt) [inline DEPS]:
```suggestion
]

```

**Review by dkwingsmt — APPROVED** [review]
