### PR TITLE
Prevent `flutter build ios-framework --xcframework` from copying `Flutter.xcframework.dSYM` into the `App.framework` folder.

### LINKED ISSUE #157359: `flutter build ios-framework --xcframework` incorrectly copies `Flutter.framework.dSYM` into App.xcframework
Add-to-app xcframework generation in release mode produces `App.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM` and `Flutter.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM`.  `App.xcframework` should not contain this dSYM.

This causes the IPA error:
```
error: Multiple commands produce '......./BuildProductsPath/Release-iphoneos/Flutter.framework.dSYM/Contents'
```

## Steps to Reproduce
Checkout https://github.com/flutter/samples
```
$ cd add_to_app/prebuilt_module/flutter_module
$ flutter build ios-framework --xcframework --output=../ios_using_prebuilt_module/Flutter --no-debug --no-profile
```
Observe `ios_using_prebuilt_module/Flutter/Release/App.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM` and `ios_using_prebuilt_module/Flutter/Release/Flutter.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM`.

The workaround is to delete `App.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM`.

### PR DESCRIPTION
**Pull request by LouiseHsu**
Fixes https://github.com/flutter/flutter/issues/157359

Prevents Flutter.xcframework.dSYM from being copied into the App.framework folder. I am not 100% positive if there are cases where it's valid to have multiple dSYMs in that folder, so I'm just string matching and filtering out `Flutter.xcframework.dSYM`

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by jmagman — COMMENTED** [review]
Can you test that if the module has plugins that their dSYMs are not also added to App.xcframework?
From my [steps to reproduce](https://github.com/flutter/flutter/issues/157359) before the xcframework output, run `flutter pub add camera` or some other plugin.

File: dev/devicelab/bin/tasks/build_ios_framework_module_test.dart [hunk 1]
```diff
@@ -197,6 +197,16 @@ Future<void> _testBuildIosFramework(Directory projectDir, { bool isModule = fals
...
     );
     checkDirectoryExists(appFrameworkDsymPath);
+
+    checkDirectoryNotExists(path.join(
+      outputPath,
+      mode,
+      'App.xcframework',
+      'ios-arm64',
+      'dSYMs',
+      'Flutter.framework.dSYM'
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/build_ios_framework_module_test.dart:207]: Instead, test that the _only_ dSYM in this directory is `App.framework.dSYM` to catch the plugin dSYMs sneaking in, too.

**Comment by LouiseHsu** [comment]
> Can you test that if the module has plugins that their dSYMs are not also added to App.xcframework? From my [steps to reproduce](https://github.com/flutter/flutter/issues/157359) before the xcframework output, run `flutter pub add camera` or some other plugin.

I tried adding a couple of plugins and the plugin dSYMs did *not* get copied in, with or without this fix. So that's good!

File: dev/devicelab/bin/tasks/build_ios_framework_module_test.dart [hunk 2]
```diff
@@ -188,15 +188,25 @@ Future<void> _testBuildIosFramework(Directory projectDir, { bool isModule = fals
...
-      'App.xcframework',
-      'ios-arm64',
-      'dSYMs',
-      'App.framework.dSYM'
+        dsymPath,
+        'App.framework.dSYM'
     );
     checkDirectoryExists(appFrameworkDsymPath);
+
+    if (Directory(dsymPath).listSync().length != 1) {
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/build_ios_framework_module_test.dart:206]: Can you filter on directories, I'm afraid this will flake if a `.DS_Store` file sneaks in. Something like:
```suggestion
    if (Directory(dsymPath).listSync().whereType<Directory>().length != 1) {
```

Comment (LouiseHsu) [reply dev/devicelab/bin/tasks/build_ios_framework_module_test.dart:206]: oh fair...

Comment (LouiseHsu) [reply dev/devicelab/bin/tasks/build_ios_framework_module_test.dart]: changed it to prevent sneaky files

**Review by jmagman — APPROVED** [review]
LGTM
