### PR TITLE
Fix Cupertino Context Menu

### LINKED ISSUE #144886: White Corners Issue in Cupertino Context Menu
### Steps to reproduce

1. Use `CupertinoContextMenu` with a Child. 
2. Make the Child have Some Corner Radius.
3. Make the Child have Some Color that is NOT Pure White.
4. Long Press on the Child

### Expected results

The child widget should be animated above without modifying its looks, border radius, or colors on the corners.

The current implementation of `CupertinoContextMenu`, on long press, while animating the child up, it's using a Container Shell in `_buildAnimation` with a pure White Color (0xFFFFFFFF), instead of being Transparent, this causes white corner borders for those developers that use a higher corner radius in child Widget.

## Expected Look
Screenshot 2024-03-10 at 02 44 00

### Actual results

The child widget is getting a modified look by `CupertinoContextMenu`, 
- It's getting a `borderRadius: null`,
- It's getting White colored corners on all 4 corners

## Actual Look
Screenshot 2024-03-10 at 02 41 03

## Problem Detail:

When you long press on the Widget after using this `CupertinoContextMenu` as a parent, it will start animating the child out to occupy half the screen in the top, while this animation happens ( before blur appears on the screen & previewBuilder is rendered), the child is used in a Container with a decoration of pure white color (0xFFFFFFFF), with no border-radius, this will cause inconsistent looks while the child undergoes a transition.

This issue does not exist when using `CupertinoContextMenu.builder`, this is how `CupertinoContextMenu` should also be working.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Cupertino Menu Issue',
      theme: ThemeData.dark(),
      home: const MyHomePage(title: 'Cupertino Menu Issue'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
          child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          CupertinoContextMenu(
            enableHapticFeedback: true,
            actions: [
              CupertinoContextMenuAction(
                child: const Text('Action one'),
                onPressed: () {
                  Navigator.of(context, rootNavigator: true).pop();
                },
              ),
              CupertinoContextMenuAction(
                child: const Text('Action two'),
                onPressed: () {
                  Navigator.of(context, rootNavigator: true).pop();
                },
              ),
            ],
            child: Container(
              decoration: BoxDecoration(
                  color: Colors.green, borderRadius: BorderRadius.circular(20)),
              height: 150,
              width: 150,
              child: const Center(
                child: Padding(
                  padding: EdgeInsets.all(8.0),
                  child: Material(
                      elevation: 0.0,
                      color: Colors.transparent,
                      child: Text(
                        'CupertinoContextMenu',
                        textAlign: TextAlign.center,
                      )),
                ),
              ),
            ),
          ),
          const SizedBox(
            width: 10,
          ),
          CupertinoContextMenu.builder(
            actions: [
              CupertinoContextMenuAction(
                child: const Text('Action one'),
                onPressed: () {
                  Navigator.of(context, rootNavigator: true).pop();
                },
              ),
              CupertinoContextMenuAction(
                child: const Text('Action two'),
                onPressed: () {
                  Navigator.of(context, rootNavigator: true).pop();
                },
              ),
            ],
            builder: (context, animation) => Container(
              decoration: BoxDecoration(
                  color: Colors.brown, borderRadius: BorderRadius.circular(20)),
              height: 150,
              width: 150,
              child: const Center(
                child: Padding(
                  padding: EdgeInsets.all(8.0),
                  child: Material(
                      elevation: 0.0,
                      color: Colors.transparent,
                      child: Text(
                        'CupertinoContextMenu.builder',
                        textAlign: TextAlign.center,
                      )),
                ),
              ),
            ),
          )
        ],
      )),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/59935432/6d7f749c-9929-499a-b0ac-6771a94cda77

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-arm64, locale en-IN)
    • Flutter version 3.19.3 on channel stable at /Users/dhikshithreddy/Developer/Src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (2 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dhikshithreddy/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/dhikshithreddy/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Users/dhikshithreddy/Applications/Android Studio Jellyfish 2023.3.1 Canary 9.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.11-11362436)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/dhikshithreddy/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Users/dhikshithreddy/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.8660.129

[✓] VS Code (version 1.87.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • Dhikshith’s iPhone (mobile) • 00008030-001A68A402DB802E            • ios            • iOS 17.3.1 21D61
    • iPhone 14 Pro (mobile)      • 4C50C415-8F1A-4147-A4C7-88B0B4D84D9C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by drxddy**
## Summary

The current implementation of `CupertinoContextMenu`, on long press, while animating the child up, it's using a Container Shell in `_buildAnimation` with a pure White Color (0xFFFFFFFF), instead of being Transparent, this causes white corner borders for those developers that use a higher corner radius in child Widget, 

## Problem Detail:

When you long press on the Widget after using this `CupertinoContextMenu` as a parent, it will start animating the child out to occupy half the screen in the top, while this animation happens ( before blur appears on the screen & previewBuilder is rendered), the child is used in a Container with a decoration of pure white color (0xFFFFFFFF), with no border-radius, this will cause inconsistent looks while the child undergoes a transition.

This issue does not exist when using `CupertinoContextMenu.builder`, this is how `CupertinoContextMenu` should also be working.

## Video
https://github.com/flutter/flutter/assets/59935432/66a2cb60-b264-4922-b045-374ebf2f643c

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/context_menu.dart [hunk 1]
```diff
@@ -676,11 +676,9 @@ class _DecoyChildState extends State<_DecoyChild> with TickerProviderStateMixin
 
     _boxDecoration = DecorationTween(
       begin: const BoxDecoration(
-        color: Color(0xFFFFFFFF),
```
[the remark this answers is not in the document]
Comment (dhikshith12) [reply packages/flutter/lib/src/cupertino/context_menu.dart:679]: If we need to access the `_boxDecoration` property used in the `_DecoyChild` directly in the tests, I would need to expose it somehow or at least write a public method to validate its state in tests, as it's currently a private property.

It means I would need to
 
- make `_DecoyChild` public to Test its state while the animation is in progress.
- write `validateDecoyColor` public predicate method to use it in tests to verify its state.

I have to introduce a new public class by publicizing `_DecoyChild` or put them in a new file and not export them in Cupertino library.

[the remark this answers is not in the document]
Comment (navaronbracke) [reply packages/flutter/lib/src/cupertino/context_menu.dart:679]: I think you could try finding the `Container` that is built by the ` _buildAnimation()`, using a Finder, in the test?

[the remark this answers is not in the document]
Comment (dhikshith12) [reply packages/flutter/lib/src/cupertino/context_menu.dart:679]: To avoid brittle tests, I prefer making `_DecoyChild` available by putting it in a new file that's not included in the Cupertino library so that it's available in tests but not visible to the library users as before, and now I can find it by Type and find its state & verify its color.

Could you please review my last commit 42b62372fde027f3f0c1c1e319de895abeb0bc38, where I implemented this?

If that looks good, I can follow up with a clean-up commit to fix dart analysis so that it's ready to merge.

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 2]
```diff
@@ -241,27 +241,96 @@ void main() {
...
+      final Finder decoyChildBeforeGesture = find.byWidgetPredicate((Widget w) => '${w.runtimeType}' == 'DecoyChild');
+      expect(decoyChildBeforeGesture, findsNothing);
+
+
+      /// Start press gesture on the child
+      final Rect childRect = tester.getRect(find.byWidget(child));
+      final TestGesture gesture = await tester.startGesture(childRect.center);
+      await tester.pump();
+
+
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:290]: Too much white space here.

File: packages/flutter/lib/src/cupertino/context_menu.dart [hunk 3]
```diff
@@ -601,36 +601,80 @@ class _CupertinoContextMenuState extends State<CupertinoContextMenu> with Ticker
...
-  const _DecoyChild({
+
+/// A floating copy of the CupertinoContextMenu's child.
+///
+/// When the child is pressed, but before the CupertinoContextMenu opens, it does
+/// an animation where it slowly grows. This is implemented by hiding the
+/// original child and placing DecoyChild on top of it in an Overlay. The use of
+/// an Overlay allows the DecoyChild to appear on top of siblings of the
+/// original child.
+class DecoyChild extends StatefulWidget {
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/context_menu.dart:612]: Whoo I never meant for something named "DecoyChild" to end up public haha. I think you can still do your test without making this public. Find the _DecoyChild by runtimeType, find the Container descendant with the BoxDecoration, then read the boxDecoration property.

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 4]
```diff
@@ -241,27 +241,96 @@ void main() {
...
+      ));
+
+      /// test the child's shape and color
+      final BoxDecoration? childDecoration = (tester.firstWidget(find.byWidget(child)) as Container).decoration as BoxDecoration?;
+      expect(childDecoration?.color, equals(CupertinoColors.activeBlue));
+
+      /// expect no DecoyChild to be present before the gesture
+      final Finder decoyChildBeforeGesture = find.byWidgetPredicate((Widget w) => '${w.runtimeType}' == 'DecoyChild');
+      expect(decoyChildBeforeGesture, findsNothing);
+
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:283]: Too much white space.

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 5]
```diff
@@ -241,27 +241,96 @@ void main() {
...
+                  ),
+                ],
+                child: child
+              ),
+            )
+          )
+        ),
+      ));
+
+      /// test the child's shape and color
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:276]: These comments should have only 2 slashes and should start with a capital letter and end with a period.

File: packages/flutter/lib/src/cupertino/context_menu.dart [hunk 6]
```diff
@@ -601,36 +601,80 @@ class _CupertinoContextMenuState extends State<CupertinoContextMenu> with Ticker
...
+class DecoyChildState extends State<DecoyChild> with TickerProviderStateMixin {
+  /// The point at which the CupertinoContextMenu begins to animate
+  /// into the open position.
+  ///
+  /// A value between 0.0 and 1.0 corresponding to a point in the [builder]'s
+  /// animation. When passing in an animation to [builder] the range before
+  /// [animationOpensAt] will correspond to the animation when the widget is
+  /// pressed and held, and the range after is the animation as the menu is
+  /// fully opening. For an example, see the documentation for [builder].
+  static final double animationOpensAt =
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/context_menu.dart:656]: Is this duplicated now?

**Comment by dhikshith12** [comment]
Thanks, I agree with you @justinmc, realized a simpler way to test this is by using `runtimeType`,  of `_DecoyChild`, finding its Descendant Container, and Verifying with its decoration property, after looking at other test examples.

So this latest commit [49ba870](https://github.com/flutter/flutter/commit/49ba870d828a73d670e7fb47ffc1ce8c9bf71f72) simplifies and undoes a lot of workarounds done in previous commits, and reverts to the old version of the file with just removal of white color in `_DecoyChild`.

`_DecoyChild` is kept private now & kept the [overall changes](https://github.com/flutter/flutter/pull/144883/files) minimal, with the changes you suggested in the review.

File: packages/flutter/lib/src/cupertino/context_menu.dart (hunk 6 above)
Comment (dhikshith12) [reply packages/flutter/lib/src/cupertino/context_menu.dart]: Check the latest commit, I cleaned up a lot, I made these changes as a result of making `_DecoyChild` public now they are like before.

File: packages/flutter/test/cupertino/context_menu_test.dart (hunk 5 above)
Comment (dhikshith12) [reply packages/flutter/test/cupertino/context_menu_test.dart]: Used this style with all comments in the latest commit.

File: packages/flutter/lib/src/cupertino/context_menu.dart (hunk 3 above)
Comment (dhikshith12) [reply packages/flutter/lib/src/cupertino/context_menu.dart]: Thanks, this was very helpful in cleaning up a lot of mess I made before 😅, also thanks to @navaronbracke, he also hinted at this but I proceeded with my way, now I realize.

File: packages/flutter/lib/src/cupertino/context_menu.dart [hunk 7]
```diff
@@ -676,11 +676,9 @@ class _DecoyChildState extends State<_DecoyChild> with TickerProviderStateMixin
 
     _boxDecoration = DecorationTween(
       begin: const BoxDecoration(
-        color: Color(0xFFFFFFFF),
         boxShadow: <BoxShadow>[],
       ),
       end: const BoxDecoration(
-        color: Color(0xFFFFFFFF),
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/context_menu.dart:683]: I noticed that this same kind of BoxDecoration with a white color is created in 2 of the code snippets in this file as well. Can you take a look at those too? Maybe the solution is just to remove the color there, too.

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 8]
```diff
@@ -241,6 +241,60 @@ void main() {
       expect(findStatic(), findsOneWidget);
     });
 
+    testWidgets('_DecoyChild preserves the child color', (WidgetTester tester) async {
+      final Widget child = getChild();
+      await tester.pumpWidget(CupertinoApp(
+        home: CupertinoPageScaffold(
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:247]: The indentation should be 2 spaces here in this pumpWidget.

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 9]
```diff
@@ -241,6 +241,60 @@ void main() {
...
+                data: const MediaQueryData(size: Size(800, 600)),
+                child: Center(
+                  child: CupertinoContextMenu(
+                      actions: const <CupertinoContextMenuAction>[
+                        CupertinoContextMenuAction(
+                          child: Text('CupertinoContextMenuAction'),
+                        ),
+                      ],
+                      child: child),
+                ))),
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:259]: I think these closing parentheses should each get their own line.

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 10]
```diff
@@ -241,6 +241,60 @@ void main() {
...
+      // find the Container descendant with the BoxDecoration,
+      // then read the boxDecoration property.
+      final BoxDecoration? boxDecoration = (tester.firstWidget(decoyChildDescendant) as Container).decoration as BoxDecoration?;
+      const List<Color?> expectedColors = <Color?>[null, Color(0x00000000)];
+
+      // Expect the _DecoyChild to have the same color as the child.
+      final bool decoyChildColorMatchesAny = expectedColors
+          .any((Color? testColor) => testColor == boxDecoration?.color);
+
+      expect(decoyChildColorMatchesAny, isTrue);
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:286]: Nit: Could you use `contains` or something here instead of doing the `.any`? [Matcher docs](https://main-api.flutter.dev/flutter/package-matcher_matcher/package-matcher_matcher-library.html).

**Review by justinmc — COMMENTED** [review]
One question about other white colors I found in the file. Otherwise I think this looks good, but @MitchellGoodwin should have the final say as to whether that white color was there for a good reason or not.

**Review by MitchellGoodwin — COMMENTED** [review]
Getting rid of the white color seems to cause no issues. I think it was there from an incorrect assumption that CupertinoContext menu would be used only in a native iOS-like background.

Echoing Justin, it should probably be removed from examples in this file.

File: packages/flutter/lib/src/cupertino/context_menu.dart (hunk 7 above)
Comment (dhikshith12) [reply packages/flutter/lib/src/cupertino/context_menu.dart:683]: Yes, there were similar usages of white color in the same file in 2 instances, one in the doc comments for `CupertinoContextMenuBuilder`, and `kOpenBorderRadius`, and I removed them as well, and there was no other usage of White Color.

File: packages/flutter/test/cupertino/context_menu_test.dart (hunk 8 above)
Comment (dhikshith12) [reply packages/flutter/test/cupertino/context_menu_test.dart:247]: Fixed in 7e80b4f52ec920b301fec11d8ea2371facecec1c

File: packages/flutter/test/cupertino/context_menu_test.dart (hunk 9 above)
Comment (dhikshith12) [reply packages/flutter/test/cupertino/context_menu_test.dart]: Fixed in 7e80b4f52ec920b301fec11d8ea2371facecec1c

File: packages/flutter/test/cupertino/context_menu_test.dart (hunk 10 above)
Comment (dhikshith12) [reply packages/flutter/test/cupertino/context_menu_test.dart]: Fixed in 7e80b4f52ec920b301fec11d8ea2371facecec1c

**Comment by dhikshith12** [comment]
- Added style suggestion made by @justinmc to fix indentation in test, new lines for parenthesis, and use `contains` Matcher instead of doing it in pure dart.
- Removed white color in doc comments in `context_menu.dart` file

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 11]
```diff
@@ -241,6 +241,61 @@ void main() {
...
+          )
+        ),
+      ));
+
+      // Expect no _DecoyChild to be present before the gesture
+      final Finder decoyChild = find
+          .byWidgetPredicate((Widget w) => '${w.runtimeType}' == '_DecoyChild');
+      expect(decoyChild, findsNothing);
+
+      // Start press gesture on the child
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:270]: Nit: Period at the end here.

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 12]
```diff
@@ -241,6 +241,61 @@ void main() {
...
+                    ),
+                  ],
+                child: child
+              ),
+            )
+          )
+        ),
+      ));
+
+      // Expect no _DecoyChild to be present before the gesture
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:265]: Nit: Period at the end here.

**Review by justinmc — APPROVED** [review]
LGTM :+1: . Thanks!

**Review by MitchellGoodwin — APPROVED** [review]
LGTM!

**Comment by dhikshith12** [comment]
Is this ready to merge, or should I change anything else?

**Comment by justinmc** [comment]
Looks like the Google tests are failing, but the failure looks unrelated to me. @dhikshith12 if it doesn't go green, can you try pushing a merge commit?

**Comment by dhikshith12** [comment]
Yes, the Google testing check is failing, just like on some other pull requests that have been approved, I don't know why, and when trying to open the details it is opening, Flutter roll on borg (frob) which is inaccessible to me, I think it's only for Google Employees Internal website.

**Comment by justinmc** [comment]
Thanks for updating the PR. That's right. If it doesn't go green I'll take another look at the failures.

**Comment by dhikshith12** [comment]
All tests are now passing...

**Comment by justinmc** [comment]
Merged! Thanks for fixing this and for all your prompt responses.

**Comment by dhikshith12** [comment]
Thanks for patiently reviewing this along the way, I should have read style guides and written tests before, that would have reduced your time spent on this PR.

I faced this issue while building this feature in my app and thought to make an Issue and a PR, looking forward to contributing more whenever I face more issues that I can help with.
