### PR TITLE
Don't flush touch events during first launch frame pre-warm

### LINKED ISSUE #13950: Touch events before first frame causes errors
```
Caught error: Cannot hit test a render box that has never been laid out.
The hitTest() method was called on this RenderBox:
  RenderCustomPaint#1b696 NEEDS-LAYOUT NEEDS-PAINT
Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested. If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after their layout() method has been called).
Stack track: #0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:1838:11)
#1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1861:6)
#2      RenderView.hitTest (package:flutter/src/rendering/view.dart:162:13)
#3      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:293:16)
#4      BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:86:7)
#5      BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
#6      BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
#7      _rootRunUnary (dart:async/zone.dart:1138)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#10     _invoke1 (file:///Users/xiao/Development/engine/src/flutter/lib/ui/hooks.dart:136)
#11     _<…>
```

is thrown if the screen is touched before the engine calls beginFrame the first time. The screen's widgets are already built at that point but the entire render tree is still in NEEDS-LAYOUT NEEDS-PAINT state. 

The error isn't particularly useful. At best, the user touched the splash screen from his/her perspective and didn't really express intent to touch the widget that threw the error. 

The touch callback still crashes in release mode at https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/box.dart#L1861 since `_size` is null.

### PR DESCRIPTION
**Pull request by xster**
Fixes #13950

I couldn't figure out how to test the production pointer event flushing mechanism though.

### CODE REVIEW

File: packages/flutter/lib/src/scheduler/binding.dart [hunk 1]
```diff
@@ -702,6 +702,21 @@ abstract class SchedulerBinding extends BindingBase with ServicesBinding {
...
+    final Completer<Null> frameCompleter = new Completer<Null>();
+    lockEvents(() => frameCompleter.future);
+
+    scheduleWarmUpFrame();
+
+    endOfFrame.then((_) {
+      frameCompleter.complete();
+      Timeline.finishSync();
+    });
+  }
```
Comment (Hixie) [inline packages/flutter/lib/src/scheduler/binding.dart]: i think this would be clearer like this:

```dart
    Timeline.startSync('Warm-up frame');
    lockEvents(() async {
      scheduleWarmUpFrame();
      await endOfFrame;
      Timeline.finishSync();
    });
 ```

**Comment by Hixie** [comment]
LGTM

I'm sad about adding yet another method instead of just making the existing method lock, and about not removing the existing flag, but I assume you looked into doing that and it wouldn't work for some reason?

File: packages/flutter/lib/src/scheduler/binding.dart (hunk 1 above)
Comment (xster) [reply packages/flutter/lib/src/scheduler/binding.dart]: Tried it initially, though the original semantic was for this method to complete after the frame is scheduled, not after the lock is set. (https://github.com/flutter/flutter/blob/master/packages/flutter/test/scheduler/scheduler_test.dart#L111)

Comment (Hixie) [reply packages/flutter/lib/src/scheduler/binding.dart]: Oh, interesting.

Comment (Hixie) [reply packages/flutter/lib/src/scheduler/binding.dart]: How about:

```dart
    Timeline.startSync('Warm-up frame');
    scheduleWarmUpFrame();
    lockEvents(() async {
      await endOfFrame;
      Timeline.finishSync();
    });
 ```

**Comment by xster** [comment]
Ah, oops, forgot to mention. I did want to remove the _warmUpFrame flag, but it was valid for the lock to be already >0 before entering scheduleWarmUpFrame, so I couldn't gate on that. Not gating (and using the phase only) can still trigger double scheduling since the phase changes asynchronously. 

What did you mean by the existing method lock?

**Comment by Hixie** [comment]
I meant combining lockAndScheduleWarmUpFrame and scheduleWarmUpFrame into one method.

**Comment by xster** [comment]
That might work too. I wasn't confident enough to decide.

Originally, I wanted to do what we looked at together, adding code only to runApp but it implied exposing lockEvents visibility beyond protected. Figured it might be a bigger foot-gun to give to people so I left it inside the binding as a less-open-ended more-goal-specific API. 

We can remove the future flexibility of a non-locking scheduleWarmUpFrame and just add a lock and a `onEndFrame.then` at the bottom which would work double locking with the reassemble case too. I just wasn't sure enough if would never want a non-locking scheduleWarmUpFrame.

**Comment by Hixie** [comment]
scheduleWarmUpFrame should only have two clients: hot reload, and initial startup. There might be other clients in tests but they're not important. I am totally fine with removing all flexibility around this API other than what is necessary to service those two use cases.

**Comment by Hixie** [comment]
Assuming the tests pass, this new approach LGTM.
