### PR TITLE
implicit-casts: false

### LINKED ISSUE #13815: Disable implicit casts
I was just doing some testing and changed the colour in the Stocks app and hot reloaded:

```dart
   switch (_configuration.stockMode) {
      case StockMode.optimistic:
        return new ThemeData(
            brightness: Brightness.light, primarySwatch: Colors.black);// This was Colors.blue
      case StockMode.pessimistic:
        return new ThemeData(
            brightness: Brightness.dark, accentColor: Colors.redAccent);
    }
    assert(_configuration.stockMode != null);
    return null;
```

When I hit hot reload I got this:

```text
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
type 'Color' is not a subtype of type 'MaterialColor' of 'primarySwatch' where
Color is from dart:ui
MaterialColor is from package:flutter/src/material/colors.dart
int is from dart:core
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 13 of 506 libraries in 871ms.
```

I don't know if this is actually a Flutter issue or not, but it seems like if it's not valid to use `Colors.black` that it shouldn't be in the code-completion and it should provide an error in the editor?

### PR DESCRIPTION
**Pull request by a14n**
## Description

Disable `implicit-casts`

## Related Issues

Fixes #13815

## Tests

None because it's a refactoring.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 1]
```diff
@@ -542,7 +541,7 @@ class _DragTargetState<T> extends State<DragTarget<T>> {
       _rejectedAvatars.remove(avatar);
     });
     if (widget.onLeave != null)
-      widget.onLeave(avatar.data);
+      widget.onLeave(avatar.data as T);
```
Comment (a14n) [inline packages/flutter/lib/src/widgets/drag_target.dart]: This one is strange because IIUC avatar could be in `_rejectedAvatars` (see the above assert) and so it could be something that is not a `T`.
Unfortunately I don't have enough context to know if it is really a problem and how to fix it.

File: analysis_options.yaml [hunk 2]
```diff
@@ -20,6 +20,7 @@
 
 analyzer:
   strong-mode:
+    implicit-casts: false
```
Comment (dnfield) [inline analysis_options.yaml]: YES

File: packages/flutter/lib/src/rendering/layer.dart [hunk 3]
```diff
@@ -674,7 +674,7 @@ class PlatformViewLayer extends Layer {
     }
     if (MouseTrackerAnnotation == S) {
```
Comment (dnfield) [inline packages/flutter/lib/src/rendering/layer.dart]: not for this PR but why isn't this `S is MouseTrackerAnimation`? @digiter

File: packages/flutter/lib/src/widgets/drag_target.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/drag_target.dart]: Should this just be `as dynamic` until we determine if the type annotations are correct?

Comment (dnfield) [reply packages/flutter/lib/src/widgets/drag_target.dart]: Hm.  Looks like that won't work.  I strongly suspect we just want the `_rejectedAvatars` collection to be `<T>` instead of `<dynamic>`.

**Review by dnfield — COMMENTED** [review]
@Hixie - do you know about the _rejectedAvatars?  It looks like you're in the blame for it.

File: packages/flutter/lib/src/rendering/layer.dart (hunk 3 above)
Comment (a14n) [reply packages/flutter/lib/src/rendering/layer.dart]: `S` is a `Type` object and will never be a `MouseTrackerAnimation`. I don't think there's a way to test that `S` extends/implements `MouseTrackerAnimation`

File: packages/flutter/lib/src/widgets/drag_target.dart (hunk 1 above)
Comment (a14n) [reply packages/flutter/lib/src/widgets/drag_target.dart]: I initially tried to make some changes (like retype `_rejectedAvatars`) but there was always a test that failed.

**Review by dnfield — APPROVED** [review]
LGTM.  Maybe we should add a TODO to fix the type weirdness around the rejectedAvatars bit.

**Comment by a14n** [comment]
>Maybe we should add a TODO to fix the type weirdness around the rejectedAvatars bit.

The problem is to find the good nickname to use for this TODO :)

**Comment by dnfield** [comment]
You can put me.

File: packages/flutter/lib/src/rendering/proxy_sliver.dart [hunk 4]
```diff
@@ -7,6 +7,7 @@ import 'dart:ui' as ui show Color;
 import 'package:flutter/foundation.dart';
 import 'package:vector_math/vector_math_64.dart';
 
+import '../../rendering.dart';
```
[the remark this answers is not in the document]
Comment (a14n) [reply packages/flutter/lib/src/rendering/proxy_sliver.dart]: Done

**Comment by a14n** [comment]
>You can put me.

Done

File: packages/flutter/lib/src/rendering/proxy_sliver.dart [hunk 5]
```diff
@@ -7,6 +7,7 @@ import 'dart:ui' as ui show Color;
 import 'package:flutter/foundation.dart';
 import 'package:vector_math/vector_math_64.dart';
 
+import '../rendering/layer.dart';
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/proxy_sliver.dart]: SHouldn't this just be 

```suggestion
import 'layer.dart';
```

File: packages/flutter/lib/src/rendering/layer.dart (hunk 3 above)
Comment (Hixie) [reply packages/flutter/lib/src/rendering/layer.dart]: we should probably have it say `S == MouseTrackerAnnotation` to make it clearer that the variable here is `S`.

File: packages/flutter/lib/src/rendering/proxy_sliver.dart (hunk 5 above)
Comment (Hixie) [reply packages/flutter/lib/src/rendering/proxy_sliver.dart]: yes, we should never import with `../foo/bar.dart`

File: packages/flutter/lib/src/widgets/drag_target.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/drag_target.dart]: _rejectedAvatatars might not be T, it could be anything. Imagine you have two drag sources, one with Xs and one with Ys, and two drag targets, one for Xs and one for Ys. Drag from the X source to the Y target and it'll be an X rejected in the Y.

Comment (Hixie) [reply packages/flutter/lib/src/widgets/drag_target.dart]: looks like onLeave is just badly defined, should be types as `<Object>` rather than `T`.

BTW, avoid `dynamic` as much as possible. Prefer `Object`.

File: packages/flutter/lib/src/rendering/layer.dart (hunk 3 above)
Comment (a14n) [reply packages/flutter/lib/src/rendering/layer.dart]: Done

File: packages/flutter/lib/src/rendering/proxy_sliver.dart (hunk 5 above)
Comment (a14n) [reply packages/flutter/lib/src/rendering/proxy_sliver.dart]: Oops. Done

File: packages/flutter/lib/src/widgets/drag_target.dart (hunk 1 above)
Comment (a14n) [reply packages/flutter/lib/src/widgets/drag_target.dart]: Done

**Comment by a14n** [comment]
PTAL

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by chingjun** [comment]
Reverting this commit, it failed analyzer and is blocking engine roll: https://cirrus-ci.com/task/6220779997364224

The failure is probably caused by https://github.com/flutter/flutter/commit/c319f5f8d8950302ea8c69fbb7843ea66344c011
