### PR TITLE
Fix: CupertinoSheetTransition moves SystemUIOverlayStyle to outside of delegatedTransition and only changes top bar

### LINKED ISSUE #164134: [Android] showCupertinoSheet  change navigation theme on android
### Steps to reproduce

When using showCupertinoSheet on Android, the bottom navigation bar's theme changes. To fix this in the implementation, follow these steps:

1️⃣ Locate line 232 (or search for this entry):

SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light);
2️⃣ Modify it as follows to apply the style only on iOS:

if (Platform.isIOS) {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light);
}

### Expected results

Don't change color

### Actual results

on light theme nav bar change to black

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      themeMode: ThemeMode.light,
      darkTheme: ThemeData.dark(),
      theme: ThemeData.light(),
      home: TestWidget(),
    );
  }
}

class TestWidget extends StatelessWidget {
  const TestWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Flutter Demo')),
      body: Center(
        child: OutlinedButton(
          child: const Text('Show Cupertino Dialog'),
          onPressed: () {
            showCupertinoSheet(
              context: context,
              pageBuilder:
                  (context) => Scaffold(
                    body: Center(
                      child: CupertinoButton(
                        child: const Text('Close Dialog'),
                        onPressed: () {
                          Navigator.of(context).pop();
                        },
                      ),
                    ),
                  ),
            );
          },
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### LINKED ISSUE #164633: [iOS] CupertinoSheetRoute doesn't reset SystemUiOverlayStyle when closed
### Steps to reproduce

Push a `CupertinoSheetRoute` and the close it

### Expected results

The `SystemUiOverlayStyle` should return what it was, since `CupertinoSheetRoute` set it to `.light`

### Actual results

The `SystemUiOverlayStyle` remain `.light` causing the status bar being not visibile anymore 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        fontFamily: "CupertinoSystemDisplay",
      ),
      home: const Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: FilledButton(
            onPressed: () {
              showCupertinoSheet(
                context: context,
                pageBuilder: (context) {
                  return const Scaffold(
                    body: Center(
                      child: Text('Sheet'),
                    ),
                  );
                },
              );
            },
            child: const Text("Open Sheet"),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/7c54a0cb-05a8-40f8-ace1-c6827e6569cd

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.30.0-0.1.pre, on macOS 15.3 24D60 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] IntelliJ IDEA Community Edition (version 2024.3.2.2)
[✓] VS Code (version 1.97.2)
[✓] Connected device (5 available)
[✓] Network resources
```

</details>

### PR DESCRIPTION
**Pull request by rkishan516**
Fix: CupertinoSheetTransition should set the SystemUIOverlayStyle in init state
fixes: #164633 
Fixes https://github.com/flutter/flutter/issues/164134

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/sheet.dart [hunk 1]
```diff
@@ -252,11 +252,13 @@ class CupertinoSheetTransition extends StatefulWidget {
     final Animation<double> scaleAnimation = curvedAnimation.drive(_kScaleTween);
     curvedAnimation.dispose();
 
-    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light);
-
     final bool isDarkMode = CupertinoTheme.brightnessOf(context) == Brightness.dark;
     final Color overlayColor = isDarkMode ? const Color(0xFFc8c8c8) : const Color(0xFF000000);
 
+    SystemChrome.setSystemUIOverlayStyle(
+      isDarkMode ? SystemUiOverlayStyle.light : SystemUiOverlayStyle.dark,
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/sheet.dart:259]: This isn't quite the correct function, as the sheet needs to set the SystemUIOverlayStyle to light regardless of theme. Since when the sheet is opened, the system UI overlay is always on a black background.

The problem is that this delegated transition is wrapped around the previous route, and does not go away when the sheet is popped. The delegated transition is waiting to be played again. It might be better to move the call to setSystemUIOverlayStyle to one of the sheet's build methods. Or wrap this call here with `if (!secondaryAnimation.isDismissed)` might work.

Comment (rkishan516) [reply packages/flutter/lib/src/cupertino/sheet.dart]: Ohh, yes correct. So, it should be `SystemUIOverlayStyle.light` when sheet is visible. Otherwise inverse of theme.

**Review by MitchellGoodwin — COMMENTED** [review]
LGTM, but needs a test.

**Comment by rkishan516** [comment]
@MitchellGoodwin Based on changes in #164675, I have also moved SystemChrome changes in sheet transition `didChangeDependencies` and `dispose`.

**Review by MitchellGoodwin — COMMENTED** [review]
If the previous page has a dark navbar, it causes the system UI to flicker, as it's set to dark then back to light.

https://github.com/user-attachments/assets/b155d0f7-3906-4777-b26b-67f03d296d4a

I'm unsure if the sheet route needs to be concerned with the previous page at all. The previous page will set its system UI colors correctly if it uses an appbar or any widget with at the top of the screen AnnotatedRegion<SystemUiOverlayStyle>.

If I push a MaterialPageRoute on top of a screen with no navbar, then I get the same behavior as the sheet.

https://github.com/user-attachments/assets/dd985b3b-7099-450e-95bc-d5380fd2f499

File: packages/flutter/lib/src/cupertino/sheet.dart [hunk 2]
```diff
@@ -363,9 +364,19 @@ class _CupertinoSheetTransitionState extends State<CupertinoSheetTransition> {
     }
   }
 
+  @override
+  void didChangeDependencies() {
+    super.didChangeDependencies();
+    _isDarkMode = CupertinoTheme.brightnessOf(context) == Brightness.dark;
+    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light);
```
[the remark this answers is not in the document]
Comment (rkishan516) [reply packages/flutter/lib/src/cupertino/sheet.dart]: I have pushed this change.

**Comment by rkishan516** [comment]
> If I push a MaterialPageRoute on top of a screen with no navbar, then I get the same behavior as the sheet.
Yaa, make sense.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for the PR.

**Comment by MitchellGoodwin** [comment]
Fixes #164134

File: packages/flutter/lib/src/cupertino/sheet.dart [hunk 3]
```diff
@@ -363,6 +361,17 @@ class _CupertinoSheetTransitionState extends State<CupertinoSheetTransition> {
     }
   }
 
+  @override
+  void didChangeDependencies() {
+    super.didChangeDependencies();
+    SystemChrome.setSystemUIOverlayStyle(
```
Comment (Piinks) [inline packages/flutter/lib/src/cupertino/sheet.dart:367]: Does this need to be called every time the widget rebuilds?

> should change SystemUIOverlayStyle based on theme

How is theme accounted for?

Comment (Piinks) [reply packages/flutter/lib/src/cupertino/sheet.dart:367]: I wonder because it does not look like it changes or depends on anything. Would `initState` one and done be better?

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/cupertino/sheet.dart:367]: > How is theme accounted for?
It was in this PR originally, but that wasn't the correct behavior. It should set a static system overlay style, and leave it up to the previous page to overwrite it. See: https://github.com/flutter/flutter/pull/164680#pullrequestreview-2734079578

Comment (rkishan516) [reply packages/flutter/lib/src/cupertino/sheet.dart:367]: > I wonder because it does not look like it changes or depends on anything. Would initState one and done be better?

Yaa, even i was thinking about it. Because now we don't use theme data for this change.

**Review by Piinks — APPROVED** [review]
LGTM! I updated the PR description to reflect the actual result here.

**Comment by lucasjinreal** [comment]
when will this fix avaliable in flutter stable?

**Comment by rkishan516** [comment]
> when will this fix avaliable in flutter stable?

Hey @lucasjinreal, this is already available in current stable channel i.e. v3.32.7

**Comment by lucasjinreal** [comment]
I still got the status bar color didn't change back in v3.32.7

what am missing further? ( i think this should be a default behavior when use with cupertinosheetroute)

**Comment by MitchellGoodwin** [comment]
If the previous page doesn't set a status bar color in some way, then it won't revert back. This is usually done by app bars, or by setting an AnnotatedRegion. There's no way for a widget like CupertinoSheetRoute to know what the previous systemUI settings were and revert to it when going backwards, the previous page has to set it itself when it returns to being the main page. See https://api.flutter.dev/flutter/services/SystemChrome/setSystemUIOverlayStyle.html

**Comment by lucasjinreal** [comment]
thanks for the reply but i have set the backgroundColor of previous page.

CupertinoNavigationBar(
                        border: null,
                        backgroundColor: PlatformTheme.getMainBkColor(context),
                        previousPageTitle: isOnMobile()
                            ? widget.boardData != null
                                ? widget.boardData!.board.title
                                : "记忆"
                            : null,
                        automaticallyImplyLeading: true,
                        trailing: _buildBarTrailing())

isn't that enough

**Comment by lucasjinreal** [comment]
I tried set the systemUIOverlay, still **can not ** revert back:

```
 AnnotatedRegion<SystemUiOverlayStyle>(
              value: SystemUiOverlayStyle.light,
              child: MyCupertinoScaffold(
                  backgroundColor: PlatformTheme.getMainBkColor(context),
                  mainColor: mainColor ?? tClrPrimary(context),
                  appBar: isOnMobile()
                      ? CupertinoNavigationBar(
                          border: null,
                          backgroundColor:
                              PlatformTheme.getMainBkColor(context),
                          previousPageTitle: isOnMobile()
                              ? widget.boardData != null
                                  ? widget.boardData!.board.title
                                  : "记忆"
                              : null,
                          automaticallyImplyLeading: true,
                          trailing: _buildBarTrailing())
```

Both light and black were tried.

**Comment by MitchellGoodwin** [comment]
Try setting `brightness` of `CupertinoNavigationBar` to the brightness of the `backgroundColor`. It tries to calculate the brightness of the background color when it's not provided, but it may not be correctly getting it. In your second code sample, the `AnnotatedRegion` you are adding is likely being covered up by the `AnnotatedRegion` added by `CupertinoNavigationBar`, so it's not doing anything.

**Comment by lucasjinreal** [comment]
> Try setting brightness of CupertinoNavigationBar to the brightness of the backgroundColor.

Hi, can u kindly give me some example code how to set it? I have set the background color of it. is this correct>?

remove systemOverlayUIStyle
```
CupertinoNavigationBar(
                          border: null,
                          backgroundColor: Colors.white,
                          previousPageTitle: isOnMobile()
                              ? widget.boardData != null
                                  ? widget.boardData!.board.title
                                  : "记忆"
                              : null,
                          automaticallyImplyLeading: true,
                          trailing: _buildBarTrailing())
```

will it revert back?

**Comment by MitchellGoodwin** [comment]
> Hi, can u kindly give me some example code how to set it? I have set the background color of it. is this correct>?

`brightness` is a property on the NavBar. 

```dart
CupertinoNavigationBar(
  border: null,
  backgroundColor: Colors.white,
  brightness: Brightness.light,
  previousPageTitle: isOnMobile()
    ? widget.boardData != null
      ? widget.boardData!.board.title
      : "记忆"
    : null,
  automaticallyImplyLeading: true,
  automaticBackgroundVisibility: false,
  trailing: _buildBarTrailing())
```

If not set it tries and set itself by calculating the luminance of `backgroundColor`, so it works by itself in most cases. `Colors.white` should work as expected. Setting `automaticBackgroundVisibility` to false would also be good just to debug that it's working as expected.

It's worth pointing out that #168182 changes how this logic works again for an improvement, but the system UI still needs to be set back once the sheet closes by the previous page. That PR is currently on the Beta release.
