### PR TITLE
[ Widget Preview ] Use analysis server for widget preview detection

### LINKED ISSUE #179584: Process `dart:flutter_tools.snapshot` and `dart:frontend_server_aot.dart.snapshot` consumes huge memory on macOS when `flutter run` even has stopped
## Steps to reproduce
1. Clean process, no dart or flutter process running in the background
2. Open flutter project with vscode / any other IDE
3. Run `flutter run`

## Expected results
`dart:flutter_tools.snapshot` and `dart:frontend_server_aot.dart.snapshot` processes should not consume huge memory (more that 1GB) or at least after application stopped the consuming memory should be reduced

## Actual results
`dart:flutter_tools.snapshot` is consuming around ±900MB to ±1.36GB, and the `dart:frontend_server_aot.dart.snapshot` is consuming around ±800MB to ±1.5GB but this process sometimes becomes two processes consuming almost the same amount of memory.

## Screenshots or Video
<details>
<summary>Activity Monitor</summary>
Image

Image
</details>

## Flutter Doctor output
<details>
<summary>Output</summary>

```
[✓] Flutter (Channel stable, 3.38.4, on macOS 26.1 25B78 darwin-arm64, locale en-ID) [476ms]
    • Flutter version 3.38.4 on channel stable at /Users/<username>/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 66dd93f9a2 (5 days ago), 2025-12-03 14:56:10 -0800
    • Engine revision a5cb96369e
    • Dart version 3.10.3
    • DevTools version 2.51.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets, omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [1,284ms]
    • Android SDK at /Users/<username>/Library/Android/sdk
    • Emulator version 36.2.12.0 (build_id 14214601) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /opt/homebrew/opt/openjdk@17/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment Homebrew (build 17.0.17+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.1.1) [1,262ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17B100
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [4ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (4 available) [6.5s]
    • iPhone 17 Pro (mobile)             • 8A6EB338-23CC-4A5D-A405-38650C589517 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-26-1 (simulator)
    • macOS (desktop)                    • macos                                • darwin-arm64   • macOS 26.1 25B78 darwin-arm64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 142.0.7444.177

[✓] Network resources [364ms]
    • All expected network resources are available.

• No issues found!
```

</details>

Reproduced on version 3.38.4, MacBook Air M3 with 8GB RAM, macOS 26.1 Tahoe.

### PR DESCRIPTION
**Pull request by bkonyi**
This change ports the `flutter widget-preview start` command to utilize the Dart Analysis Server to detect widget previews in projects. When launched from an IDE, the widget previewer will use the existing DAS and DTD instances, greatly reducing the amount of memory consumed by the widget previewer.

A `--legacy-preview-detection` flag has also been added to fall back to the previous in-process preview detection logic. This flag will be removed in a future release once the DAS implementation is proven to be stable.

Fixes #179584

### CODE REVIEW

File: packages/flutter_tools/lib/src/widget_preview/dtd_types.dart [hunk 1]
```diff
@@ -0,0 +1,262 @@
...
+
+// ignore_for_file: avoid_equals_and_hash_code_on_mutable_classes
+
+import 'dart:convert';
+
+import 'package:collection/collection.dart';
+
+/// The set of widget previews defined in a script of an analyzed Flutter
+/// project.
+class FlutterWidgetPreviews {
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/widget_preview/dtd_types.dart:13]: This file is basically a slightly modified version of the changes made in https://dart-review.googlesource.com/c/sdk/+/478100/11/third_party/pkg/language_server_protocol/lib/protocol_custom_generated.dart

File: packages/flutter_tools/lib/src/widget_preview/preview_code_generator.dart [hunk 2]
```diff
@@ -315,3 +402,50 @@ extension on DartObject {
...
+  }
+
+  void populateKnownImportPrefixes(Map<String, String> imports) {
+    if (_keys != _kInitialKey) {
+      throw StateError(
+        'Attempted to populated known import prefixes when prefixes have been allocated',
+      );
+    }
+    _imports.addAll({
+      for (final MapEntry(:key, :value) in imports.entries) key: int.parse(value.substring(2)),
```
Comment (jyameo) [inline packages/flutter_tools/lib/src/widget_preview/preview_code_generator.dart:431]: nit: it might safer to use tryParse or a check to avoid throwing an exception if `value` doesn't follow the expected format for some reason.

**Review by jyameo — APPROVED** [review]
overall lgtm!

File: packages/flutter_tools/lib/src/widget_preview/preview_code_generator.dart (hunk 2 above)
Comment (bkonyi) [reply packages/flutter_tools/lib/src/widget_preview/preview_code_generator.dart:431]: Normally I'd agree, but in this situation I think it's better to throw an exception so we can get a signal that the analyzer is returning a poorly formatted response since this should always be an integer.
