### PR TITLE
Fix context menu button color on Android when textButtonTheme is set

### LINKED ISSUE #133027: Options (i.e copy,cut,paste) selecting the text from app is not clear in android
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

- In an Android device, go to any text field and select the text, and have a look at the options
- For this, you have to add textButtonTheme, in your ThemeData, it is been observed that this issue is with textButtonTheme, as it is overriding the native Android layer.

### Expected results

textButtonTheme should not impact the text select options.

### Actual results

The text theme color is overriding native Android.
image

### Code sample

<details><summary>Code sample</summary>

```dart
In theme data I have 
ThemeData(
    textButtonTheme: textButtonThemeData,
)

and 
textButtonThemeData => TextButtonThemeData(style: defaultTextButtonStyle);

also,
ButtonStyle get defaultTextButtonStyle => ButtonStyle(
    backgroundColor: Color(0xff05164d),// blue color
),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

image
image

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5.1 22G90 darwin-arm64, locale en-IN)
    • Flutter version 3.10.6 on channel stable at /Users/piyushanand/development/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (6 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/piyushanand/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • iPhone 14 (mobile)         • A0DD9D39-9216-46E2-ADEB-9BA16B42145B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro Max (mobile) • 59B56FAE-81CB-4E0E-B69C-78B29CD00DF2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Fixes #133027

When setting a `textButtonTheme` it should not override the native context menu colors.

```dart
  theme: ThemeData(
    textButtonTheme: const TextButtonThemeData(
      style: ButtonStyle(
        backgroundColor: MaterialStatePropertyAll<Color>(
            Color(0xff05164d)), // blue color
      ),
    ),
  ),
```

Before|After
--|--
Screenshot 2023-08-24 at 1 17 25 PM|Screenshot 2023-08-24 at 1 15 35 PM

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/material/text_selection_toolbar_text_button_test.dart [hunk 1]
```diff
@@ -123,5 +123,105 @@ void main() {
         customForegroundColor,
       );
     });
+
+    testWidgetsWithLeakTracking('background color by default', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/material/text_selection_toolbar_text_button_test.dart:127]: Are we supposed to use testWidgetsWithLeakTracking for everything now?

File: packages/flutter/lib/src/material/text_selection_toolbar_text_button.dart [hunk 2]
```diff
@@ -149,11 +151,26 @@ class TextSelectionToolbarTextButton extends StatelessWidget {
...
+      Brightness.dark => _defaultBackgroundColorDark,
+    };
+  }
+
   @override
   Widget build(BuildContext context) {
     final ColorScheme colorScheme = Theme.of(context).colorScheme;
     return TextButton(
       style: TextButton.styleFrom(
+        backgroundColor: _getBackgroundColor(colorScheme),
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection_toolbar_text_button.dart:173]: What if you just hardcode this backgroundColor to transparent?

[In my context menu color PR](https://github.com/flutter/flutter/pull/131816/files), I set the context menu's background color to `surface` on the TextSelectionToolbar under the assumption that these TextSelectionToolbarButtons would be transparent and so look like the color behind them.  It looks like the problem in this issue is that setting textButtonTheme's backgroundColor changes the buttons to be non-transparent.

Just a hunch, let me know if it works.  If so, maybe it's a preferable solution since the logic about the color of these buttons isn't stored in two places.

**Review by justinmc — COMMENTED** [review]
One idea about how to simplify this, but if I'm wrong then it looks fine as-is.

File: packages/flutter/lib/src/material/text_selection_toolbar_text_button.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/material/text_selection_toolbar_text_button.dart]: That makes sense! Changing the `backgroundColor` to `Colors.transparent` works as expected.

File: packages/flutter/test/material/text_selection_toolbar_text_button_test.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/material/text_selection_toolbar_text_button_test.dart:127]: Not sure about that. @polina-c do you have any thoughts on when we should use `testWidgetsWithLeakTracing`?

**Review by justinmc — APPROVED** [review]
LGTM :+1:
