### PR TITLE
serve correct content type from debug server

### LINKED ISSUE #42612: [web] Ignoring assets MIME type
## Use case
I have a js file that gets loaded from a service worker from the assets, but in debug I get the error that the MIME type is wrong. When running in production the web server handles the MIME type.

## Proposal
Flutter seems to have no way of setting the MIME type of an asset.
Maybe a key like `assets-mime-type` could be added to the `pubspec.yaml` to set the type for every asset file if needed.
But there is the problem that not every character is valid yaml character.

Something like this:
```yaml
flutter:
  assets:
    - image.png
    - test.js
  assets-mime-type:
    image.png: image/png
    test.js: application/javascript
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

We're not providing a content type for assets. Look it up and pass it as a header.

Fixes https://github.com/flutter/flutter/issues/42612

### CODE REVIEW

File: packages/flutter_tools/lib/src/build_runner/web_fs.dart [hunk 1]
```diff
@@ -501,7 +503,14 @@ class DebugAssetServer extends AssetServer {
       final String assetPath = request.url.path.replaceFirst('assets/', '');
       final File file = fs.file(fs.path.join(getAssetBuildDirectory(), assetPath));
       if (file.existsSync()) {
-        return Response.ok(file.readAsBytesSync());
+        final Uint8List bytes = file.readAsBytesSync();
+        // Fallback to back to "application/octet-stream" on null which
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/build_runner/web_fs.dart]: nit: remove "to back"

**Review by yjbanov — APPROVED** [review]

File: packages/flutter_tools/lib/src/build_runner/web_fs.dart [hunk 2]
```diff
@@ -501,7 +503,14 @@ class DebugAssetServer extends AssetServer {
...
+        // makes no claims as to the structure of the data.
+        final String mimeType = mime.lookupMimeType(file.path, headerBytes: bytes)
+          ?? 'application/octet-stream';
+        return Response.ok(file.readAsBytesSync(), headers: <String, String>{
```
Comment (mdebbar) [inline packages/flutter_tools/lib/src/build_runner/web_fs.dart]: Can we use `bytes` here instead of reading the file contents again?

File: packages/flutter_tools/lib/src/build_runner/web_fs.dart [hunk 3]
```diff
@@ -501,7 +503,14 @@ class DebugAssetServer extends AssetServer {
       final String assetPath = request.url.path.replaceFirst('assets/', '');
       final File file = fs.file(fs.path.join(getAssetBuildDirectory(), assetPath));
       if (file.existsSync()) {
-        return Response.ok(file.readAsBytesSync());
+        final Uint8List bytes = file.readAsBytesSync();
+        // Fallback to back to "application/octet-stream" on null which
+        // makes no claims as to the structure of the data.
+        final String mimeType = mime.lookupMimeType(file.path, headerBytes: bytes)
```
Comment (mdebbar) [inline packages/flutter_tools/lib/src/build_runner/web_fs.dart]: The argument seems to be expecting only the header bytes but we are sending the whole file. Is that not an issue?

**Review by mdebbar — APPROVED** [review]

File: packages/flutter_tools/lib/src/build_runner/web_fs.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/web_fs.dart]: Woops, good catch

File: packages/flutter_tools/lib/src/build_runner/web_fs.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/web_fs.dart]: We're already reading the bytes so I was going to reuse the same buffer

**Review by harryterkelsen — APPROVED** [review]
