### PR TITLE
[flutter_tools] cleanups to web runner functionality

### LINKED ISSUE #55084: Web users may be accidentally using the less useful web-server device
`flutter run -d` supports partial matching of device name, so running `flutter run -d web` will match `web-server` if it is enabled. `web` was the old name of the `chrome` device, so users following outdated documentation will end up running a version of flutter that does not support hot restart without refreshing.

We should consider hiding the web-server device, similarly to how the flutter-tester is hidden.

fyi @mdebbar @yjbanov

### LINKED ISSUE #59643: flutter -d web-server (or --debug) silently runs in release mode
@jonahwilliams tells me that -d web-server doesn't support debug.

However if you just run `flutter run -d web-server` (which you would expect to be debug mode) or even explicitly with `--debug` it says it's running debug:
[  +85 ms] Launching lib\main.dart on Web Server in debug mode...

But presumably doesn't?

I only learned this because I was compiling a local engine (host_debug_unopt) and trying to use it with -d web and my changes weren't showing up.

### LINKED ISSUE #60417: Compile failed when main function arguments provided (Flutter Web)
## Steps to Reproduce

``` 
void main(List<String> args) {
  print("Hello World!");
}
```
1. Run `flutter run -d chrome` with above code or use web server.

**Expected results:** 
It should compile successfully on web also as it works on android. 
**Actual results:** 
Failed to compile application.
<details>
  <summary>Logs</summary>

```
[   +8 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +42 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9b9b543d9265484132c798adaab6caca52055b08
[        ] executing: [C:\flutter/] git tag --contains HEAD
[ +222 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.19.0-4.2.pre
[   +9 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +49 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +56 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +39 ms] executing: C:\Users\Sachin\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[+2169 ms] List of devices attached


           * daemon not running; starting now at tcp:5037
           * daemon started successfully
[   +9 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +47 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +16 ms] Web Server • web-server • web-javascript • Flutter Tools
[        ] Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116
[   +7 ms] "flutter run" took 2,331ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:333:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:777:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:694:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZoned (dart:async/zone.dart:1550:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:684:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
#23     _rootRunUnary (dart:async/zone.dart:1198:47)
#24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#30     _rootRun (dart:async/zone.dart:1190:13)
#31     _CustomZone.run (dart:async/zone.dart:1093:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


```

```
No issues found! (ran in 1.6s)
```

```
[√] Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [Version 10.0.19041.329], locale en-IN)
    • Flutter version 1.19.0-4.2.pre at C:\flutter
    • Framework revision 9b9b543d92 (5 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Sachin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\Sachin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Implement some cleanups to web functionality that had been lingering for a while.

1. Skip unnecessary parsing of chrome URI, this was only needed for package:test debugging which we're not going to support.
2. Ensure stack traces are initialized in web server
3. Disclaimer on web server that it does not support debugging and remove help message.
4. Fix generated entrypoint to check for `main(List<String> args)`

Fixes https://github.com/flutter/flutter/issues/59643
Fixes https://github.com/flutter/flutter/issues/55084
Fixes https://github.com/flutter/flutter/issues/60417

### CODE REVIEW

File: packages/flutter_tools/lib/src/test/flutter_web_platform.dart [hunk 1]
```diff
@@ -668,7 +667,7 @@ class BrowserManager {
   /// Loads [_BrowserEnvironment].
   Future<_BrowserEnvironment> _loadBrowserEnvironment() async {
     return _BrowserEnvironment(
-        this, null, _browser.remoteDebuggerUri, _onRestartController.stream);
+        this, null, null, _onRestartController.stream);
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/test/flutter_web_platform.dart:670]: This might have been too breaking. I can updated to a separate lookup so that it does not affect the run workflow

**Comment by jonahwilliams** [comment]
Darn, I guess that was a load-bearing URI.

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 2]
```diff
@@ -189,7 +189,9 @@ abstract class ResidentWebRunner extends ResidentRunner {
     globals.printStatus('');
     globals.printStatus(message);
     const String quitMessage = 'To quit, press "q".';
-    globals.printStatus('For a more detailed help message, press "h". $quitMessage');
+    if (device.device is! WebServerDevice) {
+      globals.printStatus('For a more detailed help message, press "h". $quitMessage');
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart:193]: It might be worth keeping the "h", except that the help message could explain how the server mode is different from the browser mode.

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 3]
```diff
@@ -623,18 +625,24 @@ class _ResidentWebRunner extends ResidentWebRunner {
...
+        "import 'dart:async';",
         '',
         "import '$importedEntrypoint' as entrypoint;",
         if (hasWebPlugins)
           "import 'package:flutter_web_plugins/flutter_web_plugins.dart';",
         if (hasWebPlugins)
           "import '$generatedImport';",
         '',
+        'typedef _UnaryFunction = Function(List<String> args);',
+        'typedef _NullaryFunction = Function();',
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart:637]: Should these have return types?

**Review by yjbanov — APPROVED** [review]

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart:637]: Technically these could return null, void, Future<x>. This is the pattern used by the engine already

Comment (yjbanov) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart:637]: I guess we're not linting generated code. We could make them return `dynamic` for explicitness.

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart:193]: I did add more details in the web server startup below (see web_devices.dart), that way it shows up in IDEs too

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: done

**Comment by jonahwilliams** [comment]
Turns out the URI is the same, but pub run test will fail if we don't wait for devtools to already be started. In the future, this should probably be removed, but I added a comment describing why it is there and reduced the complexity a bit

**Comment by DanTup** [comment]
> Disclaimer on web server that it does not support debugging and remove help message.

```dart
 'The web-server device does not support debugging. Consider using '
      'the Chrome or Edge devices for an improved development workflow.'
```

Web-Service is how we do debugging for remote workspaces (GitPod, Codespaces, SSH etc.) since we can't use Chrome there. I think this message is a bit misleading/confusing - could we change it? (eg. "Debugging with the web-server device requires the Dart Debug extension")
