### PR TITLE
Fix: Ensure Text widget locale is included in semantics language tag

### LINKED ISSUE #162324: Flutter Web: Identify any changes in language on a page by using the lang attribute (Accessibility)
### Use case

The `lang` attribute is used to identify any changes in language on a page to ensure that user agents can correctly present phrases, passages, and in some cases words written in multiple languages.

### Proposal

Add the `lang` attribute to the list of semantics flags on all Flutter component types/widgets. The first two characters of a language code defines the language of the Web page, and the last two characters define the country. For example English and United States are entered as `"en-US"`.

Valid values for language and country codes can be found at [ISO 639-1 Language Codes](https://www.w3schools.com/tags/ref_language_codes.asp) and [ISO Country Codes](https://www.w3schools.com/tags/ref_country_codes.asp).

Example on a page where `<html lang="en-US">`:
`<div>The weather is perfect today, <span lang="es-MX">¡qué bueno!</span></div>`

### PR DESCRIPTION
**Pull request by pedromassango**
Fixes https://github.com/flutter/flutter/issues/162324

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by loic-sharma** [comment]
@pedromassango Hey there, thanks for the wonderful contribution!

Instead of directly assigning folks to the pull request, could you cc them in a comment? This makes sure that the pull request shows up in triage meetings and helps us route it to the best reviewer. Due to vacations we will want someone else to review this PR, which we'll discuss during triage meetings :)

**Comment by yjbanov** [comment]
I unassigned the reviewers, who are not available right now, so the PR goes through the normal triage and finds an active reviewer.

**Comment by pedromassango** [comment]
> Instead of directly assigning folks to the pull request, could you cc them in a comment? This makes sure that the pull request shows up in triage meetings and helps us route it to the best reviewer. Due to vacations we will want someone else to review this PR

Sorry, will keep that in mind for the next ones

**Comment by pedromassango** [comment]
@loic-sharma any clue on why some tests say "all tests passed" but then they end up in failed state?

File: packages/flutter/test/widgets/text_semantics_test.dart [hunk 1]
```diff
@@ -173,4 +173,52 @@ void main() {
     expect(labelToNodeId['has been created.'], '');
     expect(labelToNodeId.length, 3);
   });
+  
+  testWidgets('GIVEN a Text widget with a locale '
```
Comment (victorsanni) [inline packages/flutter/test/widgets/text_semantics_test.dart:177]: This test fails even with the changes in this PR.

Comment (pedromassango) [reply packages/flutter/test/widgets/text_semantics_test.dart:177]: Thanks, do you mind sharing how to properly see the actual error message of failing tests?

Comment (victorsanni) [reply packages/flutter/test/widgets/text_semantics_test.dart:177]: I'm a little confused, do you mean failing tests in CI or locally failing tests? If it's in CI, you can click on the failing test which should take you to the LUCI dashboard. Then clicking on `stdout [raw]` should open the logs where you can search for the failing tests. Locally is trivial, just run the test and the exception throws and the details appear in the logs.

**Review by victorsanni — APPROVED** [review]
LGTM, pending review from others with more knowledge of `SemanticsNode`. cc @hannah-hyj

File: packages/flutter/test/widgets/text_semantics_test.dart (hunk 1 above)
Comment (pedromassango) [reply packages/flutter/test/widgets/text_semantics_test.dart:177]: in CI, whenever I open the logs I only see non-helpful logs. It is hard to know what is wrong, for instance, see

Screenshot 2025-07-17 at 9 08 35 PM

Comment (victorsanni) [reply packages/flutter/test/widgets/text_semantics_test.dart:177]: Is there a link `View more details on flutter-dashboard` just below the `Step failed (retcode: 1)` line?

**Comment by pedromassango** [comment]
> LGTM, pending review from others with more knowledge of `SemanticsNode`. cc @hannah-hyj

Disabling automerge for additional review

File: packages/flutter/test/widgets/text_semantics_test.dart (hunk 1 above)
Comment (pedromassango) [reply packages/flutter/test/widgets/text_semantics_test.dart:177]: I couldn't really find anything useful upon clicking on it. Since the failing test was "analyze", then I figured it might be missing a `dart format` and I was right.

**Comment by loic-sharma** [comment]
Ah this looks good to me, but this is waiting for approval from an accessibility expert. I swapped myself out for @hannah-hyj :)

**Comment by pedromassango** [comment]
Hello @hannah-hyj,
I would like the PR to take the next stable release train... any chance you could find time to review beforehand?

**Review by Piinks — APPROVED** [review]
This LGTM, thank you for contributing @pedromassango. 
I will see if we can CP this into beta. I don't think we can CP it into the current stable.

**Review by hannah-hyj — APPROVED** [review]
This LGTM!

**Comment by pedromassango** [comment]
> I will see if we can CP this into beta. I don't think we can CP it into the current stable.

It is fine, managed to get around it. Ok with it coming on the next non-cherrypick stable release

**Comment by Piinks** [comment]
What was the workaround?
