### PR TITLE
Dismiss the docked search view when the window size is changed

### LINKED ISSUE #125073: SearchAnchor doesn't work if app layout changes
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open M3 demo website and find the search bar.
2. Tap the search bar to open the search view and keep it open.
3. Change the original 2-column layout to 1 column. (If originally it's one column, then change it to two columns).
4. Click back button.

### Expected results

The search view route should either be popped when window size changes or when we click back button.

### Actual results

The search view route doesn't pop.

Use https://flutter-experimental-m3-demo.web.app/#/ to reproduce.

https://user-images.githubusercontent.com/36861262/232919791-4bcbdaa1-3ad9-4e56-8cc9-128195427396.mov

### PR DESCRIPTION
**Pull request by QuncCccccc**
Fixes #125073

This PR is to make an improvement for SearchAnchor. When the window size changes, the search view route should:
* be popped, if search view is docked(not full-screen).
* stay open, if it is a full-screen search view.

https://user-images.githubusercontent.com/36861262/232916814-9d1a78f3-04c3-4d15-b33e-9d8c4b663203.mov

https://user-images.githubusercontent.com/36861262/232916837-fd300036-dbfc-44a6-b857-29013cd3d813.mov

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/search_anchor.dart [hunk 1]
```diff
@@ -672,45 +690,10 @@ class _ViewContentState extends State<_ViewContent> {
...
-              math.max(anchorRect.right - viewWidth, 0.0),
-              anchorRect.top,
-            );
-            if (viewTopToScreenBottom < viewHeight) {
-              topLeft = Offset(topLeft.dx, _screenSize!.height - math.min(viewHeight, _screenSize!.height));
-            }
-            _viewRect = topLeft & updatedViewSize;
-        }
-      });
+      assert(_screenSize != null);
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/search_anchor.dart:695]: It looks like the previous line be 
```dart
_screenSize = updatedScreenSize!;
```

Comment (QuncCccccc) [reply packages/flutter/lib/src/material/search_anchor.dart]: Ah yes. Removed the assert check. Thanks!

**Review by HansMuller — APPROVED** [review]
LGTM
