### PR TITLE
Exclude arm64 if any dependencies do and print warning when using Xcode 26

### LINKED ISSUE #182748: [iOS] - Framework 'Pods_Runner' not found when targeting simulator with dependency that does not support arm64 simulators
### Steps to reproduce

Hi, I've just updated flutter to 3.41.1 but an error is showing now when launching on IOS.

It was running fine before the update

### Actual results

It should work as before

### Logs

```
Error (Xcode): Framework 'Pods_Runner' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 16.
```

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.41.1, on macOS 26.2 25C56 darwin-arm64, locale it-IT) [238ms]
    • Flutter version 3.41.1 on channel stable at /Users/sasoftware/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 582a0e7c55 (10 days ago), 2026-02-12 17:12:32 -0800
    • Engine revision 3452d735bd
    • Dart version 3.11.0
    • DevTools version 2.54.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets, omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2,8s]
    • Android SDK at /Users/sasoftware/Library/Android/sdk
    • Emulator version 36.1.9.0 (build_id 13823996) (CL:N/A)
    • Platform android-36, build-tools 35.0.0
    • ANDROID_HOME = /Users/sasoftware/Library/Android/sdk
    • Java binary at: /Users/sasoftware/Library/Java/JavaVirtualMachines/jbr-17.0.12/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment JBR-17.0.12+1-1207.37-nomod (build 17.0.12+1-b1207.37)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.2) [959ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17C52
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [4ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (3 available) [9,1s]
    • iPhone 16 (mobile) • 0845E509-267D-4F1B-A233-20E3DC802914 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-1 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 26.2 25C56 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 145.0.7632.109

[✓] Network resources [239ms]
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by vashworth**
If any Pod dependencies exclude the arm64 architecture for simulators, Flutter excludes it too. This will force Xcode to build it in an x86 architecture. However, iOS 26 introduced arm-only simulators. So when using Xcode 26, print a warning with the list of plugins/targets that are excluding arm and direct them to request arm support. Then if the build fails due to targeting an arm-only simulator, give a guided message to switch to an x86 simulator.

Fixes https://github.com/flutter/flutter/issues/182748.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 1]
```diff
@@ -1013,6 +1015,18 @@ _XCResultIssueHandlingResult _handleXCResultIssue({
...
+        'Unable to find a destination matching the provided destination specifier',
+      ) &&
+      message.contains('platform:iOS Simulator, arch:x86_64,') &&
+      !message.contains(
+        'The requested device could not be found because no available devices matched the request.',
+      )) {
+    return _XCResultIssueHandlingResult(
+      requiresProvisioningProfile: false,
+      hasProvisioningProfileIssue: false,
+      unableToFindArmDestination: true,
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/ios/mac.dart:1030]: to verify that i understand what it is doing - this is saying unable to find arm destination **in the list of destinations supported by the scheme**, right? (rather than **... in the list of available simulators**).

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 2]
```diff
@@ -1013,6 +1015,18 @@ _XCResultIssueHandlingResult _handleXCResultIssue({
       hasProvisioningProfileIssue: false,
       modifiedPrecompiledSource: true,
     );
+  } else if (message.contains(
+        'Unable to find a destination matching the provided destination specifier',
+      ) &&
+      message.contains('platform:iOS Simulator, arch:x86_64,') &&
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/ios/mac.dart:1022]: should this also check the message does not contain `platform:iOS Simulator, arch:arm64,`?

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 3]
```diff
@@ -489,77 +491,191 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+      // Xcode isn't installed, don't try to check.
+      return true;
     }
     final String? buildSettings = await xcodeProjectInterpreter.pluginsBuildSettingsOutput(
       podXcodeProject,
     );
-
     if (buildSettings == null || buildSettings.isEmpty) {
-      return;
+      return false;
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/xcode_project.dart]: why does this return `false` while the previous 2 return `true`

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 4]
```diff
@@ -489,77 +491,191 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+            })
+            .join('\n');
+        globals.logger.printWarning(
+          'The following target(s) do not support arm64 architecture, which is a requirement for '
+          'Apple Silicon iOS 26+ simulators:\n'
+          '$list\n\n'
+          'Please contact plugin maintainers to request arm64 support to continue to be able to '
+          'use the plugin on a simulator.',
+        );
+        _warnedAboutExcludingArm = true;
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/xcode_project.dart]: why do we need this check? In what scenario will this function be called multiple times?

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 5]
```diff
@@ -489,77 +491,191 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+      } else {
+        // If it's not a plugin, it may de a transitive dependency of a plugin
+        final String? parentPlugin = _pluginUsingDependency(
+          targetName: currentTarget,
+          pluginNames: pluginNames.toList(),
+          cocoapodsTree: cocoapodsTree,
+        );
+        if (parentPlugin != null) {
+          foundTargets.add((target: currentTarget, plugin: parentPlugin));
+        } else if (currentTarget.startsWith('Pods-')) {
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/xcode_project.dart:592]: what does this case mean?

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 6]
```diff
@@ -489,77 +491,191 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+        _warnedAboutExcludingArm = true;
+      }
     }
 
+    return !buildSettings.contains(RegExp('EXCLUDED_ARCHS.*arm64'));
+  }
+
+  /// Returns a list of targets and their associated plugin (if found) that exclude arm64 architecture.
+  Future<List<({String target, String? plugin})>> _targetsExcludingArm(String buildSettings) async {
+    final Map<String, List<String>> cocoapodsTree = _cocoapodTree();
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/xcode_project.dart]: is it only a problem with cocoapods and not swiftpm?

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 7]
```diff
@@ -489,77 +491,191 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+    required String targetName,
+    required List<String> pluginNames,
+    required Map<String, List<String>> cocoapodsTree,
+  }) {
+    final String? pluginName = _findPluginForDependency(targetName, cocoapodsTree, pluginNames);
+    if (pluginName != null) {
+      return pluginName;
+    }
+    if (targetName.contains('-')) {
+      // If the target has a - in the name, the first part is often the pod name
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/xcode_project.dart]: can you give an example of this? and why one search by prefix and the other does not?

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 8]
```diff
@@ -489,77 +491,191 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+    return foundTargets;
+  }
 
-    if (pluginsExcludingArmArch.isNotEmpty) {
-      final String list = pluginsExcludingArmArch.map((String n) => '  - $n').join('\n');
+  /// Returns the plugin that uses the given target.
+  String? _pluginUsingDependency({
+    required String targetName,
+    required List<String> pluginNames,
+    required Map<String, List<String>> cocoapodsTree,
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/xcode_project.dart]: it's a dependency graph (not tree) right?

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 9]
```diff
@@ -489,77 +491,191 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+          if (podsList is List<dynamic>) {
+            // ignore: specify_nonobvious_local_variable_types
+            for (final dynamic pod in podsList) {
+              if (pod is yaml.YamlMap) {
+                final name = pod.keys.first as String;
+                final dynamic value = pod.value[name];
+                if (value is yaml.YamlList) {
+                  podDependencies[name.split(' ').first] = value
+                      .map((dep) => (dep as String).split(' ').first)
+                      .toList();
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/xcode_project.dart:655]: why is it only getting the first token of the name?

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 10]
```diff
@@ -489,77 +491,191 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+          (dep) => dep.startsWith('$transitiveDependency/'),
+        );
+      } else {
+        podHasTransitiveDependency = podDependencies.contains(transitiveDependency);
+      }
+      if (podHasTransitiveDependency) {
+        if (pluginNames.contains(podName)) {
+          return podName;
+        }
+        return _findPluginForDependency(podName, cocoapodTree, pluginNames);
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/xcode_project.dart:689]: should this pass in `searchByPrefix` into the recursion?

**Review by hellohuanlin — COMMENTED** [review]
The overall logic makes sense. Just a few questions since I am not familiar with the details. 

@okorohelijah should also review since you are more familiar

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 3 above)
Comment (okorohelijah) [inline packages/flutter_tools/lib/src/xcode_project.dart]: if the `buildsetting` is null or empty, shouldnt the error message be different?

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 11]
```diff
@@ -489,77 +491,191 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
         continue;
       }
 
-      final Iterable<String> tokens = settingsLine.split(' ');
-      if (tokens.contains('arm64')) {
-        pluginsExcludingArmArch.add(currentTarget);
+      if (pluginNames.contains(currentTarget)) {
+        foundTargets.add((target: currentTarget, plugin: currentTarget));
+      } else {
+        // If it's not a plugin, it may de a transitive dependency of a plugin
```
Comment (okorohelijah) [inline packages/flutter_tools/lib/src/xcode_project.dart]:
```suggestion
        // If it's not a plugin, it may be a transitive dependency of a plugin
```

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 12]
```diff
@@ -489,77 +491,191 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+        }
       }
     }
+    return foundTargets;
+  }
 
-    if (pluginsExcludingArmArch.isNotEmpty) {
-      final String list = pluginsExcludingArmArch.map((String n) => '  - $n').join('\n');
+  /// Returns the plugin that uses the given target.
+  String? _pluginUsingDependency({
```
Comment (okorohelijah) [inline packages/flutter_tools/lib/src/xcode_project.dart:604]: what happens if a dependency that doesnt support ARM is added via spm instead of cocoapods?

**Review by okorohelijah — CHANGES_REQUESTED** [review]

File: packages/flutter_tools/lib/src/ios/mac.dart (hunk 2 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/mac.dart:1022]: This should be sufficient because Xcode does not support x86_64-only simulators anymore, but it's easy to add so sure

File: packages/flutter_tools/lib/src/ios/mac.dart (hunk 1 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/mac.dart:1030]: Correct, the list of destinations provided by the scheme

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 3 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: This is how it was originally, so was just restoring that:

https://github.com/flutter/flutter/blob/2383b644984a4a15595978e0e4be11a2c407dbf2/packages/flutter_tools/lib/src/xcode_project.dart#L501

Considering that Xcode is moving toward not supporting x86, we can probably change this to default to true.

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 4 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: Yes, this is called within `updateGeneratedXcodeProperties`, which can be called multiple times

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 6 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: Yes. SwiftPM does not allow you to exclude architectures

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 5 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart:592]: When a project as CocoaPods integrated, there are a couple Pod targets: `Pods-Runner`, `Pods-RunnerTests`. The Pod targets are generated based on the pod dependencies and therefore the user should not change them.

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 12 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart:604]: SwiftPM does not allow you to exclude arches, so there is not way to verify. It will be caught by `diagnoseXcodeBuildFailure` in mac.dart

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 8 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: Good point, I'll rename

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 7 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: Resource bundles are prefixed with the name of the pod and then the name of the resource

For example, the target for this pod resource is named `PromisesObjC-FBLPromises_Privacy`: https://github.com/google/promises/blob/d6d659a6cbdd4108788781d178a72fd34ce07e6e/PromisesObjC.podspec#L32

Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: I'll add a comment

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 9 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart:655]: It also contains the version info sometimes e.g. `GoogleMLKit/BarcodeScanning (~> 9.0.0)`

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 10 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart:689]: No, it specifically should not. After the initial prefix match, it should match by exact name since it's a valid pod name now

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 3 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: There's nothing really actionable for the user to do, but I added a trace log

**Review by okorohelijah — APPROVED** [review]
LGTM👍🏾

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 9 above)
Comment (hellohuanlin) [reply packages/flutter_tools/lib/src/xcode_project.dart:655]: gotcha. worth adding a comment there since it isn't clear when reading it. probably too late so feel free to ignore.

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 13]
```diff
@@ -489,79 +491,207 @@ def __lldb_init_module(debugger: lldb.SBDebugger, _):
...
+      globals.logger.printTrace('Failed to parse podfile.lock: $e');
+    }
+
+    return podDependencies;
+  }
+
+  /// Recursively searches the pod dependency graph for a Flutter plugin that uses the given target.
+  String? _findPluginForDependency(
+    String targetName,
+    Map<String, List<String>> cocoapodTree,
```
Comment (hellohuanlin) [inline packages/flutter_tools/lib/src/xcode_project.dart:672]: nit: this parameter is still named as a `tree`. 

If it's a graph as you said, does it mean that it's possible to have 2 plugins with the same dependency? for example: 

```
PODS: 
  - plugin_1 (1.0.0)
     - SDK_THAT_EXCLUDES_ARM64
  - plugin_2 (1.0.0)
     - SDK_THAT_EXCLUDES_ARM64
```

In this case, we may wanna report both `plugin_1` and `plugin_2`, rather than just `plugin_1`. 

(it's probably not a common use case, so feel free to ignore)

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 10 above)
Comment (hellohuanlin) [reply packages/flutter_tools/lib/src/xcode_project.dart:689]: I assume the prefix is the pod name, and the suffix is the version number too here?
