### PR TITLE
ExpansionPanel isExpanded callback parameter (Ticket 74114)

### LINKED ISSUE #74114: ExpansionPanelCallback shows incorrect state while opening and closing ExpansionPanelList.
Hello, I might have found a bug/error in the framework. I describe how the actual results differ from the ones I expected.
(copied from where I posted this first https://stackoverflow.com/questions/65743515/flutter-expansionpanellist-radio-callback-returns-wrong-value)

----------------------------------------------------------------

The line I marked with the comment (in CAPS) doesn't do what it's expected to do.

console output when I **toggle** a certain `ExpansionPanelRadio()` (of language `english` for example):  
  - I open the `ExpansionPanelRadio()`: flutter: english false *(<-- should be true, right?)*
  - I close the `ExpansionPanelRadio()`: flutter: english true *(<-- should be false, right?)*  

console output when language `english` is selected, and I click another one (for example `mandarin`):
  1. flutter: mandarin false *(<--this one went from close to open, shouldn't it return `true`??)*
  2. flutter: english false *(<--this one went from open to close)*

Why do they both say `false`, when obviously one opened and the other one closed? Both panels were in different states before, and also after the change.

With this information^^, HOW am I supposed to know WHICH `ExpansionPanelRadio()` just got tapped?

                
                List<String> languages = Languages.languageToImagePath.keys.toList();

                return SingleChildScrollView(
                  child: ExpansionPanelList.radio(
                    initialOpenPanelValue: targetLanguage, //see value in ExpansionPanelRadio
                    expansionCallback: (int panelIndex, bool isExpanded) {
                      print('${languages[panelIndex]} $isExpanded'); //<-- HEEEEEEERRREEEEE
                    },
                    children: languages.map<ExpansionPanel>((language) {
                      return ExpansionPanelRadio(
                        value: language,
                        headerBuilder: (context, bool isExpanded) { //and what's this bool for?
                          return Text(language);
                        },
                        body: Text('Choose writing system(s) todo...'),
                      );
                    }).toList(),
                  ),
                );

I think these might be errors/bugs in the framework, but I wanted to ask here on stackoverflow before reporting it.  
Maybe I just don't understand how these Widgets are supposed to be used.  
Any help is appreciated.  

I first thought ExpansionPanelList.radio might be the perfect Widget for what I intend to do, but it looks like I just have to make my own custom Widget

### PR DESCRIPTION
**Pull request by dleyba042**
Fixes https://github.com/flutter/flutter/issues/74114

This PR addresses the issue detailed here: https://github.com/flutter/flutter/issues/74114 . The boolean isExpanded returned by the expansion panel callback now reflects the state of the panel that the user is seeing. If it's expanded on screen then the callback returns true. When you close the panel the callback returns false. When another panel is open and you open a different one, the callback executes twice. It returns isExpanded == false for the panel you are closing and true for the panel that is being opened.
I had to change the code in a couple existing tests because some tests are using the old behavior of the callback. This PR addresses feedback listed in closed PR -> https://github.com/flutter/flutter/pull/127876 . The reasone the original PR is closed is that I was having some struggles with git. A couple of the commits in this PR are just reverts of commits I meant not to happen.
Pre-launch Checklist

    [ X] I read the [Contributor Guide](https://github.com/flutter/flutter/wiki/Tree-hygiene#overview) and followed the process outlined there for submitting PRs.
    [ X] I read the [Tree Hygiene](https://github.com/flutter/flutter/wiki/Tree-hygiene) wiki page, which explains my responsibilities.
    [ X] I read and followed the [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo), including [Features we expect every widget to implement](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement).
    [ X] I signed the [CLA](https://cla.developers.google.com/).
    [ X] I listed at least one issue that this PR fixes in the description above.
    I updated/added relevant documentation (doc comments with ///).
    [ X] I added new tests to check the change I am making, or this PR is [test-exempt](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests).
    [ X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord](https://github.com/flutter/flutter/wiki/Chat).

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/expansion_panel.dart [hunk 1]
```diff
@@ -313,10 +313,10 @@ class _ExpansionPanelListState extends State<ExpansionPanelList> {
     return widget.children[index].isExpanded;
   }
 
-  void _handlePressed(bool isExpanded, int index) {
-    widget.expansionCallback?.call(index, isExpanded);
+ void _handlePressed(bool isExpanded, int index) {
 
     if (widget._allowOnlyOnePanelOpen) {
+
```
Comment (Piinks) [inline packages/flutter/lib/src/material/expansion_panel.dart:319]: Nit: this extra line can be removed

File: packages/flutter/lib/src/material/expansion_panel.dart [hunk 2]
```diff
@@ -313,10 +313,10 @@ class _ExpansionPanelListState extends State<ExpansionPanelList> {
     return widget.children[index].isExpanded;
   }
 
-  void _handlePressed(bool isExpanded, int index) {
-    widget.expansionCallback?.call(index, isExpanded);
+ void _handlePressed(bool isExpanded, int index) {
```
Comment (Piinks) [inline packages/flutter/lib/src/material/expansion_panel.dart:317]: This extra line can also be removed

File: packages/flutter/lib/src/material/expansion_panel.dart [hunk 3]
```diff
@@ -329,11 +329,17 @@ class _ExpansionPanelListState extends State<ExpansionPanelList> {
           widget.expansionCallback!(childIndex, false);
         }
       }
+        //Because when _handlePressed the state is not yet expanded
+      widget.expansionCallback?.call(index, !isExpanded);
```
Comment (Piinks) [inline packages/flutter/lib/src/material/expansion_panel.dart:333]:
```suggestion
      // Because when _handlePressed the state is not yet expanded
      widget.expansionCallback?.call(index, !isExpanded);
```

File: packages/flutter/lib/src/material/expansion_panel.dart [hunk 4]
```diff
@@ -329,11 +329,17 @@ class _ExpansionPanelListState extends State<ExpansionPanelList> {
...
 
-      setState(() {
+       setState(() {
```
Comment (Piinks) [inline packages/flutter/lib/src/material/expansion_panel.dart:335]:
```suggestion
      setState(() {
```

File: packages/flutter/lib/src/material/expansion_panel.dart [hunk 5]
```diff
@@ -329,11 +329,17 @@ class _ExpansionPanelListState extends State<ExpansionPanelList> {
...
         _currentOpenPanel = isExpanded ? null : pressedChild;
       });
     }
+    else
+    {
+       widget.expansionCallback?.call(index, !isExpanded);
```
Comment (Piinks) [inline packages/flutter/lib/src/material/expansion_panel.dart:341]: Since it looks like this is called either way (in the if or else block), can the else block be removed and it just be called unconditionally after the if statement?

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 6]
```diff
@@ -144,7 +144,7 @@ void main() {
     expect(find.byType(ExpandIcon), findsOneWidget);
     await tester.tap(find.byType(ExpandIcon));
     expect(capturedIndex, 0);
-    expect(capturedIsExpanded, isFalse);
+    expect(capturedIsExpanded, isTrue);
```
Comment (Piinks) [inline packages/flutter/test/material/expansion_panel_test.dart:147]: Since this issue has existed for a while, developers may be broken by this. I am going to run some extra tests internally to see if it breaks anyone.

**Review by Piinks — COMMENTED** [review]
Thanks for the contribution!

File: packages/flutter/lib/src/material/expansion_panel.dart (hunk 5 above)
Comment (dleyba042) [reply packages/flutter/lib/src/material/expansion_panel.dart:341]: Yes, that was an oversight. I refactored and all tests are still passing.

File: packages/flutter/test/material/expansion_panel_test.dart (hunk 6 above)
Comment (dleyba042) [reply packages/flutter/test/material/expansion_panel_test.dart:147]: Ok sounds good, thanks again for the help.

**Comment by dleyba042** [comment]
@Piinks I addressed your feedback, thanks again!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

Still checking a few more test avenues to avoid this potentially getting reverted later, I'll add the autosubmit label once it is ready to go!

**Comment by dleyba042** [comment]
@Piinks sounds good, thanks for checking.

**Comment by Piinks** [comment]
All set, thanks for your patience!

**Comment by dleyba042** [comment]
I left a link to the PR in the Discord channel to see if anyone could review.

**Comment by Piinks** [comment]
Hmm.. likewise. Let me see if I can motivate. :)

**Comment by dleyba042** [comment]
sounds good. :) just figured I would put a request out there.

**Comment by Piinks** [comment]
Oh of course! You are more than welcome too, I just feel bad  no one came around yet. We'll see about getting this checked out.

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 7]
```diff
@@ -639,13 +639,109 @@ void main() {
...
     // Callback is invoked the second time with correct arguments
     callbackResults = callbackHistory[callbackHistory.length - 1];
-    expect(callbackResults['index'], equals(1));
-    expect(callbackResults['isExpanded'], equals(false));
+    expect(callbackResults['index'], equals(2));
+    expect(callbackResults['isExpanded'], equals(true));
+  });
+
+  testWidgets('ExpansionPanelList.radio callback displays true or false based on the visibility of a list item',  (WidgetTester tester) async {
+
```
Comment (justinmc) [inline packages/flutter/test/material/expansion_panel_test.dart:652]: Remove the newline here.

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 8]
```diff
@@ -639,13 +639,109 @@ void main() {
...
+    late int lastExpanded;
+    bool topElementExpanded = false;
+    bool bottomElementExpanded = false;
+
+    final List<ExpansionPanel> demoItemsRadio = <ExpansionPanelRadio>[
+      //topElement
```
Comment (justinmc) [inline packages/flutter/test/material/expansion_panel_test.dart:658]: Space after the slashes: `// topElement`

Here and below.

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 9]
```diff
@@ -639,13 +639,109 @@ void main() {
...
+
+    await tester.pumpWidget(
+      MaterialApp(
+        home: SingleChildScrollView(
+          child: expansionListRadio,
+        ),
+      ),
+    );
+
+    // Initializes with all panels closed
```
Comment (justinmc) [inline packages/flutter/test/material/expansion_panel_test.dart:702]: Periods at the ends of the sentences here and below.

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 10]
```diff
@@ -639,13 +639,109 @@ void main() {
...
+    expect(bottomElementExpanded,true);
+    expect(topElementExpanded,false);
+    expect(find.text('D'), findsOneWidget);
+    expect(find.text('A'), findsOneWidget);
+
+    await tester.tap(find.byType(ExpandIcon).at(1));
+    await tester.pump(const Duration(milliseconds: 200));
+    await tester.pumpAndSettle();
+
+    //close the item that was expanded should now be false
```
Comment (justinmc) [inline packages/flutter/test/material/expansion_panel_test.dart:736]: Space after the slashes and capital letter at the start here.

**Review by justinmc — APPROVED** [review]
LGTM, just some formatting nits.  Thanks for the PR!

**Comment by dleyba042** [comment]
@justinmc thanks for the review. I made the changes you asked for.

**Comment by your-diary** [comment]
After upgrading to Flutter 3.13 today, I encountered an bug due to this PR.
Previously working code doesn't work in Flutter 3.13 at all because this PR flips the flag passed to `expansionCallback()`.

I had very hard time debugging the issue.
This PR introduces a breaking change but where does this referred to in the [changelog](https://docs.flutter.dev/release/breaking-changes)?

**Comment by your-diary** [comment]
@justinmc 
Thank you for your suggestion.
As I believe there is a wider problem rather than one specific to this PR, I submitted #133025.

**Comment by PhilippS93** [comment]
This PR also breaks the flutter documentation, which must be adapted. See here for example: https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html

**Comment by jbryanh** [comment]
@your-diary I saw your https://github.com/flutter/flutter/issues/133025 and that it was dismissed and closed. Thanks for your effort to improve the process.
