### PR TITLE
[flutter_tools/dap] Improve rendering of structured errors via DAP

### LINKED ISSUE #4571: Flutter structured errors aren't formatted well when using SDK DAPs
The console doesn't show the exceptions correctly, links are in red, not clickable, 

[Dart-Code-Log-2023-05-05 19-17-57.txt](https://github.com/Dart-Code/Dart-Code/files/11637349/Dart-Code-Log-2023-05-05.19-17-57.txt)

_______
**with legacy DAPs:**
start of the exception:
image
middle:
image
end:
image

_______
**currently:** all of the console log looks like this with nothing clickable and not clear stacktrace.
image

### PR DESCRIPTION
**Pull request by DanTup**
In the legacy VS Code DAP, we would deserialise the Flutter.Error event and provide some basic colouring (eg. stack frames are faded if not from user code and the text is split between stdout/stderr to allow the client to colour it).

In the new DAPs we originally used `renderedErrorText` which didn't support either of these. This change adds changes to use the structured data (with some basic parsing because the source classes are in package:flutter and not accessible here) to provide a similar experience.

It would be nicer if we could use the real underlying Flutter classes for this deserialisation, but extracting them from `package:flutter` and removing all dependencies on Flutter is a much larger job and I don't think should hold up providing improved error formatting for the new DAPs.

Some comparisons:

1_comparison

2_comparison

(fyi @jacob314 @christopherfujino)

Fixes https://github.com/Dart-Code/Dart-Code/issues/4571.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Abjithwyn — COMMENTED** [review]
everything look fine

**Review by Abjithwyn — COMMENTED** [review]
ok

File: packages/flutter_tools/lib/src/debug_adapters/error_formatter.dart [hunk 1]
```diff
@@ -0,0 +1,187 @@
...
+  void writeln(String output) => _buffer.writeln(output);
+}
+
+enum _DiagnosticsNodeLevel {
+  error,
+  summary,
+}
+
+enum _DiagnosticsNodeStyle {
+  flat,
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/debug_adapters/error_formatter.dart:148]: are there going to be more values later?

**Review by christopherfujino — APPROVED** [review]
LGTM module a few nits

File: packages/flutter_tools/lib/src/debug_adapters/error_formatter.dart (hunk 1 above)
Comment (DanTup) [reply packages/flutter_tools/lib/src/debug_adapters/error_formatter.dart:148]: There are other values in the source enum, but this is the only value we currently use for this formatting, so I trimmed the enums just to the used values (otherwise we'd be needlessly keeping them in-sync with the source).

In future it would be nice to extract these classes/enums from `package:flutter` into a shared package that flutter_tools can use, but I failed to do that cleanly previously because the source types have lots of references to other Flutter framework types.
