### PR TITLE
[Impeller] Workaround for mismatched transform in preroll vs paint for text frames.

### LINKED ISSUE #164606: [Impeller]Impeller errors appear when app opens:`Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.`
### Steps to reproduce

1. Install and run [Wonderous](https://github.com/gskinnerTeam/flutter-wonderous-app) app on Android and iOS, my devices are: `Pixel 7, Android 15` and `iPhone 16 Pro Max (iOS 18.3.1)`.
2. Home page/screen will appear (since the second time open app), and observe Impeller errors appear from the run output log. If you swipe pages, more same errors may appear.

Observing this issue on Flutter master channel `3.30.0-1.0.pre.448`while I don't see it on stable 3.29.0.

### Expected results

No error appear

### Actual results

Multiple same errors are printed out as shared in Logs section.

### Code sample

<details open><summary>Code sample</summary>

https://github.com/gskinnerTeam/flutter-wonderous-app

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/0c3ccff9-cb39-49b9-98f8-a8c19f7c6a79

</details>

### Logs

<details open><summary>Logs</summary>

```console
Connecting to VM Service at ws://127.0.0.1:58613/UshQ4FN6TyY=/ws
Connected to the VM Service.
flutter: bootstrap start...
flutter: Navigate to: /
flutter: Saving...
flutter: setting discoveredCount for home widget 2
flutter: Navigate to: /home
11
[ERROR:flutter/impeller/entity/contents/text_contents.cc(161)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.
2
flutter: Saving...
19
[ERROR:flutter/impeller/entity/contents/text_contents.cc(161)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.
2
flutter: Saving...
24
[ERROR:flutter/impeller/entity/contents/text_contents.cc(161)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel master, 3.30.0-1.0.pre.448, on macOS 15.3.1 24D70 darwin-x64, locale en-VN) [4.1s]
    • Flutter version 3.30.0-1.0.pre.448 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 24418d0d80 (2 hours ago), 2025-03-04 00:04:22 -0500
    • Engine revision 24418d0d80
    • Dart version 3.8.0 (build 3.8.0-133.0.dev)
    • DevTools version 2.43.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [4.5s]
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [1,828ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [27ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [25ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] VS Code (version 1.97.2) [23ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.106.0

[✓] Connected device (4 available) [7.2s]
    • Pixel 7 (mobile)                      • 2B171FDH20084L            • android-arm64  • Android 15 (API 35)
    • iPhone 16 pro max (wireless) (mobile) • 00008140-00194CC23A68801C • ios            • iOS 18.3.1 22D72
    • macOS (desktop)                       • macos                     • darwin-x64     • macOS 15.3.1 24D70 darwin-x64
    • Chrome (web)                          • chrome                    • web-javascript • Google Chrome 133.0.6943.142

[✓] Network resources [477ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/164606

When we preroll the text frame, we record the scale/transform used to compute the size and subpixel position. Use this same size + transform for the subsequent paint so that it is not possible for it to mismatch.

This is not really a fix for the underlying issue where the subpixel position may be mismatched.

### CODE REVIEW

File: engine/src/flutter/impeller/entity/contents/text_contents.cc [hunk 1]
```diff
@@ -105,7 +105,9 @@ void TextContents::ComputeVertexData(
   size_t bounds_offset = 0u;
   for (const TextRun& run : frame->GetRuns()) {
     const Font& font = run.GetFont();
-    Scalar rounded_scale = TextFrame::RoundScaledFontSize(scale);
+    Scalar rounded_scale = frame->GetScale();
+    const Matrix transform =
+        frame->GetTransform() * Matrix::MakeTranslation(offset);
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/contents/text_contents.cc:110]: Should this be `frame->offset` to match `TypographerContextSkia::CollectNewGlyphs`?

File: engine/src/flutter/impeller/typographer/text_frame.cc [hunk 2]
```diff
@@ -101,12 +88,7 @@ void TextFrame::SetPerFrameData(Scalar scale,
                                 Point offset,
                                 const Matrix& transform,
                                 std::optional<GlyphProperties> properties) {
-  if (!transform_.Equals(transform) || !ScalarNearlyEqual(scale_, scale) ||
-      !ScalarNearlyEqual(offset_.x, offset.x) ||
-      !ScalarNearlyEqual(offset_.y, offset.y) ||
-      !TextPropertiesEquals(properties_, properties)) {
-    bound_values_.clear();
-  }
+  bound_values_.clear();
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/typographer/text_frame.cc:91]: How is this supposed to work?  Should bounds_values_ just be added to SetFrameData?

File: engine/src/flutter/impeller/entity/contents/text_contents.cc (hunk 1 above)
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/contents/text_contents.cc:110]: Can we pull this out into a function that could be shared with `TypographerContextSkia::CollectNewGlyphs`?

**Review by gaaclarke — COMMENTED** [review]
This is looking good.  This thing has been a bugger trying to track down.  I wish we could come up with a better solution for the TextFrame PerFrameData.  Keeping that state around is just asking for bugs.

**Comment by jonahwilliams** [comment]
The per frame data is pretty important for performance, independent of bugs.

File: engine/src/flutter/impeller/typographer/text_frame.cc (hunk 2 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/typographer/text_frame.cc:91]: Essentially what bound_values_ does is it lets us do a single lookup for the glyph locations of glyphs (instead of multiple). When we check if the glyph atlas is populated with a glyph, we stuff the resulting data into bound_values so that the text frame can re-use it without doing another slow hash lookup.

File: engine/src/flutter/impeller/entity/contents/text_contents.cc (hunk 1 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/text_contents.cc:110]: Done

Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/text_contents.cc:110]: Done

File: engine/src/flutter/impeller/entity/contents/text_contents.cc [hunk 3]
```diff
@@ -105,7 +105,9 @@ void TextContents::ComputeVertexData(
   size_t bounds_offset = 0u;
   for (const TextRun& run : frame->GetRuns()) {
     const Font& font = run.GetFont();
-    Scalar rounded_scale = TextFrame::RoundScaledFontSize(scale);
+    Scalar rounded_scale = frame->GetScale();
+    const Matrix transform =
+        frame->GetTransform() * Matrix::MakeTranslation(frame->GetOffset());
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/contents/text_contents.cc:110]: `frame->GetOffsetTransform()` right?

File: engine/src/flutter/impeller/typographer/text_frame.cc (hunk 2 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/typographer/text_frame.cc:95]: We don't know the bound_values until after we populate the glyph atlas, which happens necessarily after preroll when this method is called.

File: engine/src/flutter/impeller/entity/contents/text_contents.cc (hunk 3 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/text_contents.cc]: Woops, fixed

**Review by gaaclarke — APPROVED** [review]
LGTM! thanks

This is going to collide with my refactor of scale.  You'll probably get this through first, but heads up.

**Comment by jonahwilliams** [comment]
looks like a real test failure, need to investigate

**Comment by gaaclarke** [comment]
So this is potentially drawing the text wrong though, right?  We have competing ideas about what the subpixel alignment should be.  This code considers the one calculated when creating the glyph atlas is the right one, and the one in TextContents is the wrong one.  This will be very difficult to debug since there seems to be a race condition related to it and it will result in text being drawn a subpixel off.

I'm not saying we shouldn't have the workaround.  I'm just trying to game out trying to track down the root cause.

**Comment by jonahwilliams** [comment]
I don't agree that this is a race condition as this code is all single threaded, its more of a logical invariant error. Currently, we have a need to collect all glyphs (and as such all of their transforms/scales) before we start rasterization. And when we subsequently rasterize, we need the glyph data we ask for to match what is in the atlas.

The atlas is always the correct data, because we can't possibly support anything else - we can't on the fly add to the glyph atlas.

**Comment by gaaclarke** [comment]
> I don't agree that this is a race condition as this code is all single threaded

I don't understand it either but I don't think there is another valid explanation for the fact that if I start adding in print statements I can make the bug unable to be reproduced.

**Comment by jonahwilliams** [comment]
When you added in print statements, were you running the application + interacting with it? If so, is it possible it changed the timing such that *particular* frames weren't rendered?

Imagine a scenario where we have some sort of rounding bug and a scale transform is computed as 0.23 in preroll and 0.24 in paint.

**Comment by gaaclarke** [comment]
Yea, that's plausible.  I can tell you it's not some rounding problem though.  When the bug happens the offsets that are used to calculate the subpixel alignment are wildly different.  Like 10s of pixels different, not some subpixel difference.

**Comment by gaaclarke** [comment]
I wonder if this is a rotation thing.  The matrix used in the `TypographerContextSkia::CollectNewGlyphs` is just the scale * translation.  The matrix used in `TextContents::Render` is the `entity.GetTransform()`.

**Comment by gaaclarke** [comment]
Okay, I've convinced myself this is not a workaround but the fix because the `entity.GetTransform()` is being used as the argument to `TextFrame::ComputeSubpixelPosition`.  That's not what's happening when creating the glyph atlas and it doesn't match how we actually render things for things like rotations.  We render them with the scale+translation, then perform the rotation on that rasterized text.  So this is correct, alternatively we could derive that matrix when rendering, but it already exists on the textframe.
