### PR TITLE
Solve the problem that <Flutter/Flutter.h> cannot be imported when a pod transitive depends on Flutter

### LINKED ISSUE #126251: <Flutter/Flutter.h> cannot be imported when a pod transitive depends on Flutter
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

run the project in bug_demo directory.

### Expected results

Build Success.

### Actual results

Build Failed.

### Code sample

https://github.com/intspt/bug_demo

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

image

</details>

### Logs

<details><summary>Logs</summary>

```console
In file included from /Users/spt/Developer/bug_demo/bug_demo/ios/NativePod/Classes/test.m:1:
/Users/spt/Developer/bug_demo/bug_demo/ios/NativePod/Classes/test.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
        ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.7.12 on channel stable at /Users/spt/.flutterHomeOfficial3.0
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/spt/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_SDK_ROOT = /Users/spt/Library/Android/sdk
    • Java binary at: /Users/spt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/spt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (5 available)
    • M2012K11AC (mobile)        • 3514df5f                             • android-arm64  • Android 13 (API 33)
    • iPhone (mobile)            • 00008020-000954E136A1002E            • ios            • iOS 16.4.1 20E252
    • iPhone 14 Pro Max (mobile) • C247BDBA-F6F2-4DF3-8E25-A511C760D87D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.3.1 22E261 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by intspt**
image
image
If a pod transitive depends on a pod containing a framework, cocoapods will add the path of the framework to its FRAMEWORK_SEARCH_PATHS.
So I modified the relevant logic in podhelper, hoping to be consistent with the behavior of cocoapods.

Fixes https://github.com/flutter/flutter/issues/126251.

### CODE REVIEW

**Comment by jmagman** [comment]
@intspt can you file an issue that describes exactly what you're seeing and how to reproduce it?  I don't understand how you got into the state from those screenshots.

**Comment by intspt** [comment]
> @intspt can you file an issue that describes exactly what you're seeing and how to reproduce it? I don't understand how you got into the state from those screenshots.

I have provided a demo to reproduce this problem: https://github.com/intspt/bug_demo
The dependency tree is the same in the normal_demo and bug_demo scenarios.
```bash
NativePod -> shared_preferences -> Flutter
```

In the normal_demo, cocoapods added the directory of Flutter.framework to the FRAMEWORK_SEARCH_PATHS of NativePod. Because shared_preferences dependencies will be inherited to NativePod.
image

But in the bug_demo, Flutter is a fake pod. FRAMEWORK_SEARCH_PATHS is processed by podhelper, which misses the scenarios of transitive dependencies, so an error will be reported during compilation.
image

**Comment by jmagman** [comment]
Can you file an actual GitHub issue instead of updating this PR?  I am not quite sure the use case of a native pod depending on a Flutter plugin, for example, and it's better to have that conversation documented in an issue since that's generally where folks will look for duplicates, etc.

Additionally, this will need a test.  Unfortunately we don't really have Ruby tests so it would need to be an integration test, see
https://github.com/flutter/flutter/blob/c2022aa5b140544e103025e6995b41c872e39d2c/dev/devicelab/lib/tasks/plugin_tests.dart or https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/build_ios_framework_module_test.dart for an example of where that could live.

**Comment by intspt** [comment]
> Can you file an actual GitHub issue instead of updating this PR? I am not quite sure the use case of a native pod depending on a Flutter plugin, for example, and it's better to have that conversation documented in an issue since that's generally where folks will look for duplicates, etc.
> 
> Additionally, this will need a test. Unfortunately we don't really have Ruby tests so it would need to be an integration test, see https://github.com/flutter/flutter/blob/c2022aa5b140544e103025e6995b41c872e39d2c/dev/devicelab/lib/tasks/plugin_tests.dart or https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/build_ios_framework_module_test.dart for an example of where that could live.

Our app is called Xianyu. This problem was encountered in our own project, and there should be no similar issues.

The most direct solution to this problem is to make the native pod depend on Flutter. But we can't do this in our project.
We put Flutter.framework, App.framework, and framework compiled by plugin into a pod called IdlefishFlutter. The purpose is to allow several scenarios such as local development of Flutter projects, local development of native parts, and remote packaging to be used normally.
image

Therefore, in these scenarios, native pods can only rely on IdlefishFlutter.
Of course, the root cause of this problem is that there are some flaws in the processing of podhelper. I think it is a reasonable solution to keep the processing logic of podhelper consistent with the logic of cocoapods.

**Comment by intspt** [comment]
> Can you file an actual GitHub issue instead of updating this PR? I am not quite sure the use case of a native pod depending on a Flutter plugin, for example, and it's better to have that conversation documented in an issue since that's generally where folks will look for duplicates, etc.
> 
> Additionally, this will need a test. Unfortunately we don't really have Ruby tests so it would need to be an integration test, see https://github.com/flutter/flutter/blob/c2022aa5b140544e103025e6995b41c872e39d2c/dev/devicelab/lib/tasks/plugin_tests.dart or https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/build_ios_framework_module_test.dart for an example of where that could live.

This change is only to add the directory where Flutter.framework is located in the FRAMEWORK_SEARCH_PATHS of the pod that transitive depends on Flutter. This problem may only be encountered in the Add-to-app scenario. So it seems impossible to add this scenario in the integration test.

**Comment by stuartmorgan** [comment]
@intspt as request above:

> Can you file an actual GitHub issue instead of updating this PR

We have a standard process, which includes separating discussion of what the problem is (the issue tracker) and reviewing a fix (PR discussion).

> This problem was encountered in our own project, and there should be no similar issues.

Almost all problems are encountered in developers' projects. That doesn't mean that nobody can ever encounter the same issue.

**Comment by intspt** [comment]
> @intspt as request above:
> 
> > Can you file an actual GitHub issue instead of updating this PR
> 
> We have a standard process, which includes separating discussion of what the problem is (the issue tracker) and reviewing a fix (PR discussion). Following our process will make things go more smoothly
> 
> > This problem was encountered in our own project, and there should be no similar issues.
> 
> Almost all problems are encountered in developers' projects. That doesn't mean that nobody can ever encounter the same issue.

I raised an issue, https://github.com/flutter/flutter/issues/126251.

**Comment by hyiso** [comment]
Tried this PR, causing a long time waiting at 'Generating Pods project' when runniung pod install

**Comment by intspt** [comment]
> Tried this PR, this might cause a long time waiting at 'Generating Pods project' when running pod install.
> 
> Maybe the recursive depth should be limited

Recursive operations increase the time consumption very little. Taking our project as an example, there are about 320+ pods. The total time of flutter_additional_ios_build_settings is about 1s.
now:
image
before:
image

**Comment by christopherfujino** [comment]
I'm going to mark this PR as a draft for now, as it seems per the discussion on https://github.com/flutter/flutter/issues/126251 it is not clear if the issue is one that should be fixed in the Flutter SDK. I think we should resolve that in that issue first, before reviewing this PR.

**Comment by stuartmorgan** [comment]
Apologies for the delay in getting back to this; looking further at the use case, this seems like a reasonable solution. For non-add-to-app cases it seems like this should have minimal impact.

**Comment by stuartmorgan** [comment]
> Tried this PR, this might cause a long time waiting at 'Generating Pods project' when running pod install.
> 
> Maybe the recursive depth should be limited

@hyiso Are you saying you saw actual performance problems with this PR applied? What does your dependency graph look like?

File: packages/flutter_tools/bin/podhelper.rb [hunk 1]
```diff
@@ -19,6 +19,29 @@ def flutter_ios_podfile_setup; end
 # Same as flutter_ios_podfile_setup for macOS.
 def flutter_macos_podfile_setup; end
 
+# Determine whether the target depends on Flutter (including transitive dependency)
+def is_depend_on_flutter(target, platform)
```
Comment (stuartmorgan) [inline packages/flutter_tools/bin/podhelper.rb:23]: Nit: `depends_on_flutter`

File: packages/flutter_tools/bin/podhelper.rb [hunk 2]
```diff
@@ -19,6 +19,29 @@ def flutter_ios_podfile_setup; end
...
+
+  target.dependencies.any? do |dependency|
+    if dependency.name == engine_pod_name
+      return true
+    end
+
+    if is_depend_on_flutter(dependency.target, platform)
+      return true
+    end
+  end
```
Comment (stuartmorgan) [inline packages/flutter_tools/bin/podhelper.rb:42]: Please explicitly `return false` at the end.

File: packages/flutter_tools/bin/podhelper.rb [hunk 3]
```diff
@@ -19,6 +19,29 @@ def flutter_ios_podfile_setup; end
 # Same as flutter_ios_podfile_setup for macOS.
 def flutter_macos_podfile_setup; end
 
+# Determine whether the target depends on Flutter (including transitive dependency)
+def is_depend_on_flutter(target, platform)
+  if platform == 'ios'
+    engine_pod_name = 'Flutter'
+  elsif platform == 'macos'
+    engine_pod_name = 'FlutterMacOS'
```
Comment (stuartmorgan) [inline packages/flutter_tools/bin/podhelper.rb:27]: What is the goal passing `ios` or `macos` only to map back to the framework name, rather than passing the framework name directly? It seems like this just adds complexity.

**Review by stuartmorgan-g — CHANGES_REQUESTED** [review]
As mentioned [above](https://github.com/flutter/flutter/pull/125610#issuecomment-1535161621), this will need an automated test.

**Comment by hyiso** [comment]
> > Tried this PR, this might cause a long time waiting at 'Generating Pods project' when running pod install.
> > Maybe the recursive depth should be limited
> 
> @hyiso Are you saying you saw actual performance problems with this PR applied? What does your dependency graph look like?

Yes, after applying this PR, it stuck at `Generating Pods project` over 10 minutes when running `pod install`.

The host iOS project has a lot of pod dependencies (I don't know how to count the total number).

But I'm not sure whether it is a bug of the PR or just related to the dependencies complication, as @intspt said he does not have this problem.

File: packages/flutter_tools/bin/podhelper.rb (hunk 2 above)
Comment (hyiso) [reply packages/flutter_tools/bin/podhelper.rb:42]: Wow, the stuck problem seems to be here, after adding `return false` at the end, the stuck disappeared

**Comment by hyiso** [comment]
> > > Tried this PR, this might cause a long time waiting at 'Generating Pods project' when running pod install.
> > > Maybe the recursive depth should be limited
> > 
> > 
> > @hyiso Are you saying you saw actual performance problems with this PR applied? What does your dependency graph look like?
> 
> Yes, after applying this PR, it stuck at `Generating Pods project` over 10 minutes when running `pod install`.
> 
> The host iOS project has a lot of pod dependencies (I don't know how to count the total number).
> 
> But I'm not sure whether it is a bug of the PR or just related to the dependencies complication, as @intspt said he does not have this problem.
> 
> BTW, my current workaround is just to comment out this line `next unless target.dependencies.any? { |dependency| dependency.name == 'Flutter' }` in this file

As mentioned here https://github.com/flutter/flutter/pull/125610#discussion_r1275130159, after adding `return false`, the stuck disappeared

**Comment by hyiso** [comment]
> > > > Tried this PR, this might cause a long time waiting at 'Generating Pods project' when running pod install.
> > > > Maybe the recursive depth should be limited
> > > 
> > > 
> > > @hyiso Are you saying you saw actual performance problems with this PR applied? What does your dependency graph look like?
> > 
> > 
> > Yes, after applying this PR, it stuck at `Generating Pods project` over 10 minutes when running `pod install`.
> > The host iOS project has a lot of pod dependencies (I don't know how to count the total number).
> > But I'm not sure whether it is a bug of the PR or just related to the dependencies complication, as @intspt said he does not have this problem.
> > BTW, my current workaround is just to comment out this line `next unless target.dependencies.any? { |dependency| dependency.name == 'Flutter' }` in this file
> 
> As mentioned here [#125610 (comment)](https://github.com/flutter/flutter/pull/125610#discussion_r1275130159), after adding `return false`, the stuck disappeared.
> 
> I'll continue to try this PR to check whether the problem `<Flutter/Flutter.h> not found` is solved

Seems not solved in my host iOS project, I'll keep to use my workaround.

**Comment by christopherfujino** [comment]
@intspt are you still interested in working on this?

**Comment by intspt** [comment]
> @intspt are you still interested in working on this?

I'm sorry for not seeing the previous reply, I'm still interested.
I will modify my code as soon as possible as per stuartmorgan's suggestion.

**Review by stuartmorgan-g — APPROVED** [review]
LGTM. @vashworth, could you do the secondary review?

(Also, it looks like this will need to be synced with main to resolve CI issues.)

**Review by vashworth — CHANGES_REQUESTED** [review]
LGTM, but as @stuartmorgan and @jmagman previously requested, this will need an integration test. See previous comment (https://github.com/flutter/flutter/pull/125610#issuecomment-1535161621) for some examples

**Comment by intspt** [comment]
> LGTM, but as @stuartmorgan and @jmagman previously requested, this will need an integration test. See previous comment ([#125610 (comment)](https://github.com/flutter/flutter/pull/125610#issuecomment-1535161621)) for some examples

ok, I'll add an integration test for this change. But I have been busy recently, so I will be able to provide it later.

**Comment by intspt** [comment]
> @intspt can you file an issue that describes exactly what you're seeing and how to reproduce it? I don't understand how you got into the state from those screenshots.

Hello, I don’t know how to write this integration test task. I need to create a native pod that depends on any Flutter Plugin, but it doesn't seem possible.

**Comment by stuartmorgan** [comment]
> I need to create a native pod that depends on any Flutter Plugin, but it doesn't seem possible.

Why wouldn't that be possible; isn't that exactly the case that this PR is intended to handle?

**Comment by intspt** [comment]
> > I need to create a native pod that depends on any Flutter Plugin, but it doesn't seem possible.
> 
> Why wouldn't that be possible; isn't that exactly the case that this PR is intended to handle?

But I don’t know how to introduce the pod I want in the integration test. Can I write the contents of the podspec and .m file into the dart file?

**Review by jmagman — APPROVED** [review]
Sorry for the long delay on this PR, it shouldn't have been left for this long.

> Additionally, this will need a test.

Okay I looked into this more and oh man would this be tricky to test.  Probably in this code
https://github.com/flutter/flutter/blob/c2022aa5b140544e103025e6995b41c872e39d2c/dev/devicelab/lib/tasks/plugin_tests.dart#L74-L80
we would need to add a `NativePod.podspec` that depends on `plugintest` but _not_ `Flutter`, but does `@import Flutter`.  Then change the `plugintestapp/ios/Podfile` to `pod 'NativePod', :path => right/path/here` in the right spot.  

Or create a new project in  https://github.com/flutter/flutter/tree/master/dev/integration_tests that has this all set up, which is quite a lot of code to test something so obscure that I would say isn't even correct behavior--if you import Flutter you should declare it as a dependency.

However I really don't want to be overly pedantic for such a harmless change (more than I already have been 🙂 ).  Famous last words I guess.  I'm going to approve this and you'll probably be responsible someday for noticing if the behavior broke, and filing a bug, and fixing it.

Apologies again for this hanging out so long, and for this being really tough to test.  We appreciate your contribution!

**Comment by jmagman** [comment]
@vashworth if you want to hold the testing line here I totally understand since you still have this marked as changes requested.  We should either approve it or close it (or write the test ourselves) since it's been hanging out so long.

**Comment by vashworth** [comment]
@intspt Here's how I would add it to the plugin_test_ios integration test. Feel free to use this code in this PR: https://github.com/flutter/flutter/compare/master...vashworth:flutter:flutter_transitive_dependency_test

**Comment by intspt** [comment]
> @intspt Here's how I would add it to the plugin_test_ios integration test. Feel free to use this code in this PR: [master...vashworth:flutter:flutter_transitive_dependency_test](https://github.com/flutter/flutter/compare/master...vashworth:flutter:flutter_transitive_dependency_test)

thx, I'll finish it this weekend

**Review by vashworth — APPROVED** [review]
LGTM. Thanks for adding tests!
