### PR TITLE
Fix and test an edge case in `findPackageConfigFile`.

### LINKED ISSUE #163901: `findPackageConfigFile` crashes when given a missing or deleted `Directory`
I've seen this come up in refactoring tests, but not in real code, and I _think_ it's a bug:

```dart
import 'package:file/file.dart';
import 'package:flutter_tools/src/dart/package_map.dart' show findPackageConfigFile;

void example(FileSystem fileSystem) {
  // Pick a clearly non-existent directory.
  final Directory directory = fileSystem.directory('i/do/not/exist');
  print(findPackageConfigFile(directory)); // Expected: null, but throws
}
```

This is because `fileSystem.identicalSync` throws if one or more of the paths are missing, and is used and I think this can be fixed by ensuring the path being checked actually exists (if it doesn't, then continue looking).

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/163901.

I'm not aware of a case where this causes user crashes, but it could, and seems easy to fix/test.

### CODE REVIEW

File: packages/flutter_tools/lib/src/dart/package_map.dart [hunk 1]
```diff
@@ -34,7 +34,13 @@ File? findPackageConfigFile(Directory dir) {
...
     }
     final Directory parentDir = candidateDir.parent;
-    if (fileSystem.identicalSync(parentDir.path, candidateDir.path)) {
+    // identicalSync requires that both paths exist; if we assume that the
+    // parentDir exists if the candidateDir exists, then we can just check that
+    // the candidate dir exists (if it doesn't, then identicalSync would throw
+    // which is probably not what findPackageConfigFile is intende to do).
+    //
+    // See https://github.com/flutter/flutter/issues/163901.
+    if (candidateDir.existsSync() && fileSystem.identicalSync(parentDir.path, candidateDir.path)) {
```
Comment (sigurdm) [inline packages/flutter_tools/lib/src/dart/package_map.dart:43]: This is just to check if we hit the root directory.

We should probably not need any filesystem access at all.

I think it would be better to do:
```suggestion
    if (fileSystem.path.equals(parentDir.path, candidateDir.path)) {
```

Which just textually compares the paths.

Comment (matanlurey) [reply packages/flutter_tools/lib/src/dart/package_map.dart:43]: Thanks! I wasn't sure if this was load bearing, but it shouldn't be.

As an added bonus I no longer need a comment :)

**Review by sigurdm — APPROVED** [review]
