### PR TITLE
Nav bar back label is not clipped mid-transition

### LINKED ISSUE #149905: CupertinoNavigationBar flickers when previousPageTitle more than 4 characters
Also related to https://github.com/flutter/flutter/issues/90589

### Steps to reproduce

You can see it clearly if you run this code on dartpad:

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
        home: MyHomePage(title: "Home", backButtonText: ""));
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage(
      {super.key, required this.title, required this.backButtonText});

  final String title;
  final String backButtonText;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        previousPageTitle: widget.backButtonText,
        // automaticallyImplyLeading: true,
        middle: Text(widget.title),
        trailing: const Row(
          mainAxisSize: MainAxisSize.min,
          children: [],
        ),
      ),
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              child: const Text("Go"),
              onPressed: () {
                Navigator.of(context).push(CupertinoPageRoute(
                    builder: (c) => MyHomePage(
                          title: "Oh dear",
                          backButtonText: "${widget.backButtonText}Back",
                        )));
              },
            ),
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

### Expected results

I don't expect it to flicker

### Actual results

https://github.com/flutter/flutter/assets/545244/42ec4f04-0b1b-449f-9aaa-c62507c18e9b

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/flutter/flutter/assets/545244/42ec4f04-0b1b-449f-9aaa-c62507c18e9b)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
    • Flutter version 3.22.2 on channel stable at /Users/foobar/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (2 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
```

</details>

### PR DESCRIPTION
**Pull request by victorsanni**
### Before

https://github.com/user-attachments/assets/fe354e67-c36d-4ce6-bf0f-0ca559962bfd

### After

https://github.com/user-attachments/assets/e57b91a0-00ed-493a-92b4-549dc8ab330a

Fixes [CupertinoNavigationBar flickers when previousPageTitle more than 4 characters](https://github.com/flutter/flutter/issues/149905)

### CODE REVIEW

**Comment by dkwingsmt** [comment]
Looking closely at the after video, I think the label is still shortened? 
image

It seems that the label is freed from the constraint, or starts to have a larger constraint midway. I doubt if this is the correct behavior. Have you checked the native behavior?

**Comment by victorsanni** [comment]
> It seems that the label is freed from the constraint, or starts to have a larger constraint midway, since the back label changes from "Back..." to "BackB..." to "BackBack".
> 
This is native behavior: https://github.com/flutter/flutter/issues/40583
With native it should never get clipped. It either is always fully extended or it gets replaced with 'Back'.

**Comment by dkwingsmt** [comment]
Yeah, that's what I typically observe as well. Do you think something like this is achievable?

**Comment by victorsanni** [comment]
> Yeah, that's what I typically observe as well. Do you think something like this is achievable?

Yes, this is fixed now.

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 1]
```diff
@@ -2737,7 +2741,8 @@ class _NavigationBarComponentsTransition {
       offsetAnimation: animation
           .drive(CurveTween(curve: curve))
           .drive(anchorMovementInTransitionBox),
-      size: fromBox.size,
+      width: fromNavBarBox.size.width,
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/cupertino/nav_bar.dart:2744]: Does it mean that the width is allowed to as wide as the entire screen? What happens natively if the title will be clipped after the transition?

Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/nav_bar.dart:2744]: > Does it mean that the width is allowed to as wide as the entire screen?

Yes, but elsewhere the back label is replaced with 'Back' if it is more than a certain number of characters. So it never actually takes up that whole space. Natively, the back label gets replaced if the title/middle doesn't have enough space.

The title/middle starts where the back label ends, and wraps if its too long. So when the back label is also very long, there isn't an overlap:

long back label and middle

**Review by dkwingsmt — APPROVED** [review]
LGTM

File: packages/flutter/test/cupertino/nav_bar_transition_test.dart [hunk 2]
```diff
@@ -1752,4 +1752,32 @@ void main() {
...
+      of: find.text('backbackback'),
+      matching: find.byWidgetPredicate(
+        (Widget widget) => widget is Positioned && widget.width != null,
+      ),
+    );
+    expect(positionedFinder, findsOne);
+
+    // A smaller width clips the back label.
+    final Positioned positionedWidget = tester.widget<Positioned>(positionedFinder);
+    expect(positionedWidget.width, moreOrLessEquals(800.0, epsilon: 0.01));
```
[the remark this answers is not in the document]
Comment (victorsanni) [reply packages/flutter/test/cupertino/nav_bar_transition_test.dart]: Fixed. I wasn't able to test with the text because the previous solution was still incorrect. Now that we are allocating enough space for the text it becomes trivial to test with the text width.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM as well
