### PR TITLE
Fix `--web-header` flag for `flutter drive`

### LINKED ISSUE #159037: [flutter_web] `--web-header` flag does not work for `flutter drive`
### Steps to reproduce

1. Call `flutter drive --help --verbose` to see docs on how to use the `--web-header` flag:

```
   --web-header=<X-Custom-Header=header-value>              Additional key-value pairs that will added by the web server as headers to all responses. Multiple
                                                             headers can be passed by repeating "--web-header" multiple times.
```

2. Clone flutter repository, navigate to [/dev/integration_tests/web_e2e_tests](https://github.com/flutter/flutter/tree/master/dev/integration_tests/web_e2e_tests), run the test with a `--web-header` flag with `--no-headless` so that the browser window appears:
```
chromedriver --port=4444 

flutter drive --target=test_driver/text_editing_integration.dart \
  -d web-server \
  --browser-name=chrome \
  --profile \
  --web-renderer=html \
  --web-header="test-header=test-value" \ 
  --no-headless
```

3. Inspect the headers the index.html and other files are served with.

### Expected results

`test-header` with `test-value` appears as HTTP header for each file served by the server.

Screenshot 2024-11-16 at 22 13 43

### Actual results

The server doesn't add the HTTP header. The `--web-header` flag has no effect.

Screenshot 2024-11-16 at 22 21 36

### Code sample

<details open><summary>Code sample</summary>

No code sample since the issue is reproducible on examples from the flutter repository. Refer to **Steps to reproduce** for details.

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.27.0-1.0.pre.530, on macOS 15.1 24B83 darwin-arm64, locale en-PL)
    ! Flutter version 3.27.0-1.0.pre.530 on channel [user-branch] at /Users/shemhazai/Projects/GitHub/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.95.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

### PR DESCRIPTION
**Pull request by dt-iohk**
This PR makes sure that `--web-header` flag works together with the `flutter drive` command. Currently the flag is correctly parsed but it is not properly propagated and ends up being unused when running the web server for tests.

I have validated the fix by following the steps to reproduce from: https://github.com/flutter/flutter/issues/159037.

#### Before the fix

No custom HTTP header in test run:
Screenshot 2024-11-16 at 22 21 36

#### After the fix

Correct HTTP headers in test run:
Screenshot 2024-11-16 at 22 13 43

Fixes #159037

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/drive/web_driver_service.dart [hunk 1]
```diff
@@ -78,6 +78,7 @@ class WebDriverService extends DriverService {
           hostname: debuggingOptions.hostname,
           webRenderer: debuggingOptions.webRenderer,
           webUseWasm: debuggingOptions.webUseWasm,
+          webHeaders: debuggingOptions.webHeaders,
```
Comment (navaronbracke) [inline packages/flutter_tools/lib/src/drive/web_driver_service.dart:81]: This change is going to need a test, that verifies that any headers that are passed to the web runner's debugging options are correct. Unfortunately https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/web.shard/web_driver_service_test.dart only contains a single test, which uses `startTest()` and not the `start()` method of the service

Comment (dtscalac) [reply packages/flutter_tools/lib/src/drive/web_driver_service.dart:81]: What do you think about adding the test to https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/drive/web_driver_service_test.dart since it already contains other tests that validate the behavior of the `start()` method of the service?

I have added a test there to validate that correct webHeaders are passed.

Comment (navaronbracke) [reply packages/flutter_tools/lib/src/drive/web_driver_service.dart:81]: That test seems reasonable to me!

**Review by eyebrowsoffire — APPROVED** [review]
LGTM! Thanks for the fix!

**Review by ditman — APPROVED** [review]
LGTM! Thanks! Keep them coming!
