### PR TITLE
Fix SliverResizingHeader semantic focus

### LINKED ISSUE #179687: [Accessibility] SliverResizingHeader captures semantic focus before list is fully scrolled
### Links

This issue is similar to #179022 and will be fixed once PR #179023 is merged.

FYI @Renzo-Olivares .

### Steps to reproduce

1. Enable accessibility services (TalkBack or VoiceOver) on the device.
2. Open a screen containing a `CustomScrollView` with a `SliverResizingHeader` and a list of items (e.g., SliverList).
3. Scroll down the list so that the top items are off-screen.
4. Navigate backwards (swipe left / previous item gesture) to scroll up toward the top of the list.

### Expected results

The list should be fully scrolled to the top (displaying the very first item) before the semantic focus moves to the widget preceding the list or the pinned header. The user should be able to navigate through all remaining list items before leaving the list context.

### Actual results

The PinnedHeaderSliver takes the semantic focus immediately when navigating up, effectively "skipping" the remaining items at the top of the list or preventing the list from scrolling all the way back to the start.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: MyApp()));

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          const SliverAppBar(
            pinned: true,
            expandedHeight: 100.0,
            title: Text('Sample App'),
            backgroundColor: Colors.blue,
          ),
          const SliverResizingHeader(
            minExtentPrototype: SizedBox(height: 50),
            maxExtentPrototype: SizedBox(height: 150),
            child: ColoredBox(
              color: Colors.green,
              child: ListTile(title: Text('Resizable Header')),
            ),
          ),
          // The List
          SliverList(
            delegate: SliverChildBuilderDelegate((BuildContext context, int index) {
              return ListTile(title: Text('Item $index'), subtitle: const Text('Scroll down then navigate back up'));
            }, childCount: 50),
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/58dc7bda-4563-4e18-a88e-c2a1ef4d814b

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.40.0-1.0.pre-105, on macOS 15.7.2 24G325 darwin-arm64, locale fr-FR) [4,7s]
    • Flutter version 3.40.0-1.0.pre-105 on channel master at /Users/emmanuel_lefebvre/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6519f99911 (10 hours ago), 2025-12-10 00:18:27 -0500
    • Engine revision 6519f99911
    • Dart version 3.11.0 (build 3.11.0-227.0.dev)
    • DevTools version 2.53.0
    • Pub download mirror https://artifact.socrate.vsct.fr/artifactory/api/pub/all-pub
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations,
      enable-native-assets, omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [4,5s]
    • Android SDK at /Users/emmanuel_lefebvre/Library/Android/sdk
    • Emulator version 36.2.12.0 (build_id 14214601) (CL:N/A)
    • Platform android-36, build-tools 35.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.8+-14196175-b1038.72)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.1.1) [3,8s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17B100
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (3 available) [14,3s]    
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 15 (API 35) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 15.7.2 24G325 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 143.0.7499.41

[✓] Network resources [581ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by zemanux**
Fix #179687

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/widgets/sliver_resizing_header_test.dart [hunk 1]
```diff
@@ -407,4 +410,76 @@ void main() {
     await tester.pumpAndSettle();
     expect(getHeaderHeight(), 100);
   });
+
+  testWidgets(
+    'SliverResizingHeader: presence of RenderViewport.excludeFromScrolling tag when pinned',
+    (WidgetTester tester) async {
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/sliver_resizing_header_test.dart:404]: I would add the following to the top of this test.

```
// Regression test for https://github.com/flutter/flutter/issues/179687.
```

Comment (zemanux) [reply packages/flutter/test/widgets/sliver_resizing_header_test.dart:404]: Done.

File: packages/flutter/test/widgets/sliver_resizing_header_test.dart [hunk 2]
```diff
@@ -395,4 +397,61 @@ void main() {
...
+      expect(
+        semantics,
+        isNot(
+          includesNodeWith(
+            tags: {RenderViewport.excludeFromScrolling, RenderViewport.useTwoPaneSemantics},
+          ),
+        ),
+      );
+
+      await tester.drag(find.byType(CustomScrollView), const Offset(0, -300));
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/sliver_resizing_header_test.dart:445]: Similar to this comment here https://github.com/flutter/flutter/pull/179023/changes#r2816227601, I think it would be useful to verify the sliver stays pinned to the top after the drag.

File: packages/flutter/test/widgets/sliver_resizing_header_test.dart [hunk 3]
```diff
@@ -395,4 +397,61 @@ void main() {
...
+        isNot(
+          includesNodeWith(
+            tags: {RenderViewport.excludeFromScrolling, RenderViewport.useTwoPaneSemantics},
+          ),
+        ),
+      );
+      await tester.drag(find.byType(CustomScrollView), const Offset(0, -100));
+      await tester.pumpAndSettle();
+
+      expect(
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/sliver_resizing_header_test.dart:439]: I think the below would be more correct, here and elsewhere in this test.

```dart
expect(semantics, includesNodeWith(tags: <SemanticsTag>{RenderViewport.useTwoPaneSemantics}));
expect(
  semantics,
  isNot(includesNodeWith(tags: <SemanticsTag>{RenderViewport.excludeFromScrolling})),
);
```

File: packages/flutter/lib/src/widgets/sliver_resizing_header.dart [hunk 4]
```diff
@@ -227,8 +231,8 @@ class _RenderSliverResizingHeader extends RenderSliver
 
   @override
   void applyPaintTransform(RenderObject child, Matrix4 transform) {
-    final childParentData = child.parentData! as SliverPhysicalParentData;
-    childParentData.applyPaintTransform(transform);
+    assert(child == this.child);
+    applyPaintTransformForBoxChild(child as RenderBox, transform);
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/sliver_resizing_header.dart]: I don't think this change is needed to fix the issue, can you explain further why we are changing the logic here?

**Review by Renzo-Olivares — COMMENTED** [review]
Hi @zemanux, mostly looks good just had a few small comments. Thank you for your patience!

File: packages/flutter/test/widgets/sliver_resizing_header_test.dart (hunk 3 above)
Comment (zemanux) [reply packages/flutter/test/widgets/sliver_resizing_header_test.dart:439]: Good catch ! I fixed it.

File: packages/flutter/test/widgets/sliver_resizing_header_test.dart (hunk 2 above)
Comment (zemanux) [reply packages/flutter/test/widgets/sliver_resizing_header_test.dart:445]: Done.

File: packages/flutter/lib/src/widgets/sliver_resizing_header.dart (hunk 4 above)
Comment (zemanux) [reply packages/flutter/lib/src/widgets/sliver_resizing_header.dart]: My bad, I reverted this modification.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM, thank you for your patience and contribution @zemanux! This will need a secondary review before landing.

**Review by Piinks — APPROVED** [review]
LGTM

**Comment by Piinks** [comment]
Manually kicked google testing to run
