### PR TITLE
SingleChildScrollView does not clip semantics child

### LINKED ISSUE #113615: [iOS] [a11y] Unable to fully navigate page using talkback when using nested scroll views
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Enable iOS VoiceOver
3. Use VoiceOver to change focus from the top app bar to the scroll view elements.
4. Use VoiceOver to focus successive elements until the view port moves down the scroll view.
5. Use VoiceOver to focus previous elements, causing the view port to scroll back up.
6. Observe that there are elements at the top of the page that cannot be focused.

Expected:
VoiceOver should be able to access all elements on the screen. It should be able to tab through to the bottom and then tab back up to the top of the scroll view.

Actual:
VoiceOver is unable to return to elements at the initial top of the scroll view.

Code Sample:
```dart
import 'package:mobile.flutter.google_material.material2/google_material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: LongColumnContainer(),
    );
  }
}

class LongColumnContainer extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('A11y Repro App'),
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            SizedBox(
              height: 16,
            ),
            Icon(
              Icons.favorite,
              size: 14,
            ),
            SizedBox(
              height: 16,
            ),
            Text(
              'Page title',
              textAlign: TextAlign.center,
            ),
            SizedBox(
              height: 16,
            ),
            Text(
              'Page subtitle',
              textAlign: TextAlign.center,
            ),
            SizedBox(
              height: 20,
            ),
            Text(
              'Title1',
            ),
            cardCarousel(),
            SizedBox(
              height: 20,
            ),
            Text(
              'Title2',
            ),
            SizedBox(height: 16),
            Text(
              'subtitle2',
            ),
            SizedBox(height: 16),
            cardCarousel(),
            SizedBox(
              height: 20,
            ),
            Icon(
              Icons.favorite,
              size: 100,
            ),
            SizedBox(
              height: 20,
            ),
            Text(
              'end of carousel',
              textAlign: TextAlign.center,
            ),
            Icon(
              Icons.favorite,
              size: 100,
            ),
            SizedBox(
              height: 20,
            ),
            Text(
              'end of page',
              textAlign: TextAlign.center,
            ),
            SizedBox(
              height: 20,
            ),
          ],
        ),
      ),
      drawer: Drawer(child: Text('drawer tile')),
    );
  }
}

Widget cardCarousel() {
  return SingleChildScrollView(
    scrollDirection: Axis.horizontal,
    child: IntrinsicHeight(
      child: Padding(
        padding: EdgeInsets.symmetric(horizontal: 14),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            card(Icons.favorite, 'calendar', 'some small text'),
            SizedBox(width: 10),
          ],
        ),
      ),
    ),
  );
}

Widget card(IconData iconData, String title, String body) {
  return Semantics(
    container: true,
    explicitChildNodes: true,
    child: Container(
      width: 304,
      foregroundDecoration: BoxDecoration(
          borderRadius: BorderRadius.circular(8),
          border: Border.all(color: Colors.red)),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(8),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            SizedBox(
              height: 210,
              child: Icon(
                iconData,
                size: 200,
              ),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 24),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text(
                    title,
                  ),
                  SizedBox(
                    height: 8,
                  ),
                  Text(
                    body,
                  ),
                ],
              ),
            ),
            Container(
              padding: const EdgeInsetsDirectional.fromSTEB(16, 0, 16, 24),
              alignment: Alignment.centerLeft,
              child: Text('View details'),
            ),
          ],
        ),
      ),
    ),
  );
}
```

flutter doctor:
```
[✓] Flutter (Channel google3, on Debian GNU/Linux rodete 5.18.16-1rodete1-amd64, locale
    en_US.UTF-8)
    • Framework revision fe9b598c12 (9 days ago), 2022-10-09T00:00:00.000
    • Engine revision ac1fec6367
    • Dart version 2f0c186d3b

[✓] Android toolchain - develop for Android devices (Android SDK version Stable)
    • Android SDK at google3
    • Platform Stable, build-tools Stable
    • Java binary at: /opt/android-studio-with-blaze-2021.3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 4.2)
    • Android Studio at /opt/android-studio-with-blaze-4.2
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8443
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio-with-blaze-2020.3
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio-with-blaze-2021.3
    • Flutter plugin version 69.0.3
    • Dart plugin version 213.7371
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /opt/intellij-ce-stable

[✓] VS Code (version 1.69.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Debian GNU/Linux rodete 5.18.16-1rodete1-amd64

[✓] Google3 (on linux)
    • KVM enabled

• No issues found!
```

repro video attached:

https://user-images.githubusercontent.com/37954976/196496889-c911f183-e106-4af5-8868-a9381a36279f.mp4

### PR DESCRIPTION
**Pull request by chunhtai**
Fixes https://github.com/flutter/flutter/issues/113615

I can't find a reason to clip it since it was laid out just to be thrown away during the semantics gathering stage.
The original issue is because some children are too far away from cache extent and gets throw away. the voiceover then think there is no child.

The alternative is to expose cache extent in single child scroll view, but it doesn't make sense as an API because everything will be laid out regardlessly.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
Looks like some tests are failing on this?

File: packages/flutter/lib/src/widgets/single_child_scroll_view.dart [hunk 1]
```diff
@@ -700,19 +685,34 @@ class _RenderSingleChildViewport extends RenderBox with RenderObjectWithChildMix
...
+          semanticBounds.top,
+          semanticBounds.right + remainingOffset,
+          semanticBounds.bottom,
+        );
+      case AxisDirection.down:
+        return Rect.fromLTRB(
+          semanticBounds.left,
+          semanticBounds.top - offset.pixels,
+          semanticBounds.right,
+          semanticBounds.bottom + remainingOffset,
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/single_child_scroll_view.dart:709]: Isn't this making the semantics clip larger than necessary? AFAK, "remainingOffset" is the distance from the top of the viewport to the end of the scrollable content, so the semantics clip here would be one viewport height to tall, no?

Not that it matters in practice, but may cause confusion in the future...

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/single_child_scroll_view.dart:709]: Could we actually add a test for this? The height of the semanticsClip rect should be exactly the height of the scrollable content, right?

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/single_child_scroll_view.dart:709]: Ah, wait: `_maxScrollExtent` is already accounting for the viewport width. Still, I think adding a test like I described above would be great.

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/widgets/single_child_scroll_view_test.dart [hunk 2]
```diff
@@ -460,6 +379,85 @@ void main() {
...
+    }
+    scrollRenderObject.visitChildren(findsRenderViewPort);
+    expect(viewport, isNotNull);
+    final RenderObject childRenderObject = tester.renderObject(find.byKey(childBox));
+    Rect semanticsClip =  viewport!.describeSemanticsClip(childRenderObject)!;
+    expect(semanticsClip.size.height, length);
+
+    controller.jumpTo(2000);
+    await tester.pump();
+    semanticsClip =  viewport!.describeSemanticsClip(childRenderObject)!;
```
Comment (goderbauer) [inline packages/flutter/test/widgets/single_child_scroll_view_test.dart:417]: nit: here and below are some extra whitespaces after the "="

**Review by goderbauer — APPROVED** [review]
LGTM

THanks for the test!

File: packages/flutter/test/widgets/single_child_scroll_view_test.dart (hunk 2 above)
Comment (chunhtai) [reply packages/flutter/test/widgets/single_child_scroll_view_test.dart:417]: Although we don't use fmt in flutter, I think should have lint or autoformat on indent at least.

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Comment by chunhtai** [comment]
besides the expected scuba the other test failure doesn't seem related
