### PR TITLE
Fix velocity_tracker_test.dart

### LINKED ISSUE #22460: _checkVelocity call in velocity_tracker_test.dart doesn't actually check velocity
The _checkVelocity function returns a bool to indicate whether the check passed but the caller ignores the bool:

https://github.com/flutter/flutter/blob/master/packages/flutter/test/gestures/velocity_tracker_test.dart

/cc @Hixie

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/22460.

The test never verified that the velocity actually matched expectations because the return value of `_checkVelocity` was just ignored. Because of this, the recored expectations were also slightly outdated.

### CODE REVIEW

File: packages/flutter/test/gestures/velocity_tracker_test.dart [hunk 1]
```diff
@@ -42,7 +42,7 @@ void main() {
         tracker.addPosition(event.timeStamp, event.position);
       }
       if (event is PointerUpEvent) {
-        _checkVelocity(tracker.getVelocity(), expected[i]);
+        expect(_checkVelocity(tracker.getVelocity(), expected[i]), isTrue);
```
Comment (chunhtai) [inline packages/flutter/test/gestures/velocity_tracker_test.dart:45]: Not necessary needed to merge this pr, we may also consider move the expect to _checkVelocity function directly.

**Review by chunhtai — APPROVED** [review]
LGTM, nice catch
