### PR TITLE
Reland: Switch to assemble API for dart2js

### LINKED ISSUE #40463: Issues in release mode when running Flutter Web
## Steps to Reproduce

running: flutter run -d chrome --release --local-engine=host_debug_unopt --web-port=8080

We saw two issues running in release mode today:
1) The runner doesn't use the given web-port put uses a random port.
2) After making a change, to make it visible, I needed to run flutter clean to remove the cache. Otherwise my change didn't took effect.

Thanks!

### PR DESCRIPTION
**Pull request by jonahwilliams**
Use flutter tools to build with dart2js directly instead of build through build runner. Updates resident web runner to serve from build/web. Should fix cases where local updates to dart2js or dart SDK does not result in correct rebuild through build_runner. Removes cases where multiple entrypoints are compiled with build runner.

Reland: Includes fix that avoids creating a new Pool for each invocation of hash computation

Fixes #40463

### CODE REVIEW

File: packages/flutter_tools/lib/src/build_system/file_hash_store.dart [hunk 1]
```diff
@@ -143,24 +135,28 @@ class FileHashStore {
...
-  // isolates. This also related to the current performance issue with checking
-  // APKs before installing them on device.
   Future<List<File>> hashFiles(List<File> files) async {
     final List<File> dirty = <File>[];
-    for (File file in files) {
-      final String absolutePath = file.resolveSymbolicLinksSync();
-      final String previousHash = previousHashes[absolutePath];
-      final List<int> bytes = file.readAsBytesSync();
-      final String currentHash = md5.convert(bytes).toString();
+    final Pool openFiles = Pool(kMaxOpenFiles);
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/build_system/file_hash_store.dart]: The fix was moving this up here instead of declaring it inline. That had caused one to be created for each call to `_hashFile`, making it ineffective at limiting the number of open files

File: packages/flutter_tools/lib/src/build_system/targets/dart.dart [hunk 2]
```diff
@@ -140,6 +124,28 @@ class CopyFlutterBundle extends Target {
   ];
 }
 
+/// A helper function to copy an [assetBundle] into an [environment]'s output directory,
+/// plus an optional [pathSuffix]
+Future<void> copyAssets(AssetBundle assetBundle, Environment environment, [String pathSuffix = '']) async {
+  final Pool pool = Pool(kMaxOpenFiles);
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/build_system/targets/dart.dart]: If the goal is to limit the number of simultaneous file operations by the `flutter_tools` process, we should have one global `Pool` object used by everything (perhaps stored inside the `AppContext`). Perhaps it could even be built into `fs`.

File: packages/flutter_tools/lib/src/build_system/file_hash_store.dart (hunk 1 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/build_system/file_hash_store.dart]: See comment below. I'm wondering if one global pool with a bigger limit is the way to go.

**Review by yjbanov — APPROVED** [review]

File: packages/flutter_tools/lib/src/build_system/targets/dart.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/targets/dart.dart]: That sounds like a good enhancement here, but I'm a bit worried about last minute changes. I'll open a separate PR to do that with more testing
