### PR TITLE
Fix project name fallback

### LINKED ISSUE #53106: flutter create uses directory name rather than package name to check name validity
I tried to add web support to an existing mobile app. The name of the app in the `pubspec.yaml` is a valid package name. However, the _directory_ that contains the package (which is derived from a git repository name) contains a dash "-" in the name. Running `flutter create .` in the package results in:

```
"xxxxx-xxxxxx" is not a valid Dart package name.

See https://dart.dev/tools/pub/pubspec#name for more information.
```

/cc @jonahwilliams

### PR DESCRIPTION
**Pull request by navaronbracke**
This PR changes the project name logic for `flutter create` to look for the name in the pubspec.yaml `name` field,
before falling back to the directory name.

Fixes https://github.com/flutter/flutter/issues/53106 

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by andrewkolos** [comment]
Does this need a merge or rebase with `master`?

**Comment by navaronbracke** [comment]
Seems all the check pass now? I didn't merge in master or rebase onto it, though.

**Comment by andrewkolos** [comment]
Ah, my mistake—I didn't notice that the checks were falling victim to https://github.com/flutter/flutter/issues/150642

**Review by andrewkolos — APPROVED** [review]
Thanks for fixing this!

File: packages/flutter_tools/lib/src/commands/create_base.dart [hunk 1]
```diff
@@ -319,13 +319,40 @@ abstract class CreateBase extends FlutterCommand {
...
-        stringArg('project-name') ?? globals.fs.path.basename(projectDirPath);
+    String? projectName = stringArg('project-name');
+
+    if (projectName == null) {
+      final File pubspec = globals.fs
+        .directory(projectDirPath)
+        .childFile('pubspec.yaml');
+
+      if (pubspec.existsSync()) {
+        final RegExp nameRegex = RegExp('^name: ([a-z0-9_]+)');
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/commands/create_base.dart:339]: @andrewkolos should we not be parsing the pubspec here, rather than just doing a regex?

Comment (navaronbracke) [reply packages/flutter_tools/lib/src/commands/create_base.dart:339]: I was thinking of that, too, but isn't that a bit too much work for what is needed here?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/create_base.dart:339]: For example, consider the following, valid yaml:

```yaml
name:                 my_app_name
```

This would fail this regex.

Comment (navaronbracke) [reply packages/flutter_tools/lib/src/commands/create_base.dart:339]: Fair point, I can either adjust the regex to include whitespace, or we can parse the YamlMap

Comment (navaronbracke) [reply packages/flutter_tools/lib/src/commands/create_base.dart]: Added parsing the YamlMap in https://github.com/flutter/flutter/pull/150614/commits/176693e94b3a599854516d2342580d0baf694787

**Review by christopherfujino — APPROVED** [review]
LGTM, thanks!
