### PR TITLE
Methods in build_ios_framework for universal and XCFrameworks

### LINKED ISSUE #63508: flutter build ios-framework Some plugin debug framework creation failing
## Issue
So after tons of debugging, I figured out that some plugin packages (native iOS pods) fail to properly create their respective frameworks (in debug) if in their Podspec their name differs from their module name. An example would be a pod with the following spec:

```swift
Pod::Spec.new do |s|
s.name = 'Mixpanel-swift'
s.module_name = 'Mixpanel'
```

## Steps to Reproduce

1. Create a new flutter module: `flutter create --template module my_flutter`
2. In the modules `pubspec.yaml` add the following dependency: `native_mixpanel: ^0.1.2` (this uses the `Mixpanel-swift` pod which has the module/name differences)
3. Run `flutter pub get`
4. Because this package requires target `9.0` and `Swift 5.0` isnt declared we have to make some small modifications (step 5 and step 6)
5. Edit `.ios/Podfile` and change `platform :ios, '8.0'` to `platform :ios, '9.0'`.
6. Open the demo project in Xcode `open .ios/Runner.xcworkspace/`. Click on the `Runner` project on the left, then click on the `Runner` target. From there click `Build Settings` and click on the `+` to add a new `Add User-Defined Setting`. Type in `SWIFT_VERSION` for the property and `5.0` for the value.
7. Run `flutter build ios-framework --no-release --no-profile --no-universal --xcframework --verbose`

## Logs

```bash
[   +1 ms] executing: [/my_flutter/build/ios/framework/] xcrun xcodebuild -create-xcframework -framework
/my_flutter/build/ios/framework/Debug/iphoneos/Debug-iphoneos/Mixpanel-swift/Mixpanel.framework -framework
/my_flutter/build/ios/framework/Debug/iphonesimulator/Debug-iphonesimulator/Mixpanel/Mixpanel.framework -output
/my_flutter/build/ios/framework/Debug/Mixpanel.xcframework
[ +467 ms] error: unable to read the file at '/my_flutter/build/ios/framework/Debug/iphonesimulator/Debug-iphonesimulator/Mixpanel/Mixpanel.framework/Mixpanel'
```

You can see that `Debug-iphonesimulator/Mixpanel/Mixpanel.framework/Mixpanel` doesnt exist because it actually exists at path: `Debug-iphonesimulator/Mixpanel-swift/Mixpanel.framework/Mixpanel` instead.

## Solution
This problem occurs because when building debug frameworks, it assumes the Pod name and module name match, which causes the file to not be found. This happens in 2 spots in this file `build_ios_framework.dart` here:
```dart
if (mode == BuildMode.debug)
    simulatorBuildConfiguration
        .childDirectory(binaryName)
        .childDirectory(podFrameworkName)
        .childFile(binaryName)
        .path,
```

A fix would be adding this variable:
```dart
final String frameworkDir = globals.fs.path.basename(podProduct.dirname);
```
and using it in the debug path:
```dart
if (mode == BuildMode.debug)
    simulatorBuildConfiguration
        .childDirectory(binaryName)
        .childDirectory(frameworkDir)
        .childFile(binaryName)
        .path,
```

Here is a diff on the file changes:
Screen Shot 2020-08-11 at 11 58 27 AM

## Flutter Doctor
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)

• No issues found!
```

### PR DESCRIPTION
**Pull request by jmagman**
## Description

https://github.com/flutter/flutter/pull/69731 and the next "Remove lipoing from debug stub framework step" PR were too big to review together.

Refactoring part of `build_ios_framework` to keep the reviews for https://github.com/flutter/flutter/issues/69334 small.

1. Rename `_produceXCFramework` to `_produceXCFrameworkFromUniversal`.  This existing method took a universal (fat) framework, split it into `iphoneos` and `iphonesimulator` frameworks, then turned them into an xcframework.
2. Pull logic to create an xcframework from non-fat frameworks out of  `_producePlugins`, combine with logic from `_produceNonDebugXCFramework`, and call the new method `_produceXCFramework`.  This method will be used in the next PR.
3. Pull logic to `lipo` together non-fat frameworks into a universal framework out of  `_producePlugins` and call it `_produceUniversalFramework `.  This method will also be used in the next PR.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/63508, will supersede https://github.com/flutter/flutter/pull/66541

## Tests

`build_ios_framework_module_test` thoroughly tests the output bundles.   My test suggestion in https://github.com/flutter/flutter/pull/66541#pullrequestreview-495991300 wasn't a great one and it didn't work.  `build_ios_framework_module_test` will confirm it doesn't regress the more normal case that the module and framework are named the same thing.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 1]
```diff
@@ -494,77 +494,25 @@ end
...
-              if (mode == BuildMode.debug)
-                '-framework',
-              if (mode == BuildMode.debug)
-                simulatorBuildConfiguration
-                  .childDirectory(binaryName)
+          final List<Directory> frameworks = <Directory>[
+            podProduct as Directory,
+            if (mode == BuildMode.debug)
+              simulatorBuildConfiguration
+                  .childDirectory(builtProduct.basename)
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart:502]: @1amageek This is the line that is similar to your suggestion in https://github.com/flutter/flutter/pull/66541, though I used an existing local instead of making a new one.

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 2]
```diff
@@ -494,77 +494,25 @@ end
             continue;
           }
           final String binaryName = globals.fs.path.basenameWithoutExtension(podFrameworkName);
-          if (boolArg('universal')) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart:497]: This logic is now in `_produceUniversalFramework`.

File: packages/flutter_tools/lib/src/commands/build_ios_framework.dart [hunk 3]
```diff
@@ -494,77 +494,25 @@ end
...
-            );
-
-            if (pluginsLipoResult.exitCode != 0) {
-              throwToolExit(
-                'Unable to create universal $binaryName.framework: ${buildPluginsResult.stderr}',
-              );
-            }
-          }
 
-          if (boolArg('xcframework')) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/build_ios_framework.dart:530]: This logic is now in `_produceXCFramework`

**Review by jonahwilliams — APPROVED** [review]
LGTM
