### PR TITLE
Don't strip symbols from `libapp.so` on android by default

### LINKED ISSUE #170664: [android] Generate symbol files for AOT snapshots even without split-debug-info
Currently when building for AOT snapshots we usually [strip](https://github.com/flutter/flutter/blob/d9c63168c8d232e3232a3c1af3393b45db4c6cf8/packages/flutter_tools/lib/src/base/build.dart#L179-L183) them by default loosing all native symbolic information - because we don't expect this information to be useful. Dart runtime symbolizes stack traces it produces using information embedded into snapshot itself.

However native symbols can still come useful: consider for example a case when user hits an ANR due to long running Dart code (see https://github.com/flutter/flutter/issues/169906 as example). In this case they will be left with a stack trace in Android native format which they can't read[^1]. 

There is however a way to improve this experience: Android implementation should follow iOS one (which makes an effort to produce `dSYM`). Instead of stripping snapshots right away at generation time, it should produce unstripped snapshot and then split symbolic information out (e.g. using `llvm-objcopy`). The symbolic information could be then included in the app bundle - in which case it will be [automatically picked up by Play Store](https://developer.android.com/build/include-native-symbols#agp-4.1). When building APKs native symbols should be split into a separate archive to simplify subsequent upload to Play Store.

@jmagman @reidbaker 

[^1]: We could actually provide tooling to symbolize them using `analyze_snapshot`, but I think a better solution is to have Play Console symbolize them.

### PR DESCRIPTION
**Pull request by gmackall**
Fixes https://github.com/flutter/flutter/issues/170664

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by gmackall** [comment]
cc again @johnmccutchan @jason-simmons @jonahwilliams, because you all had input on the [original pr](https://github.com/flutter/engine/pull/50443) to get debug symbols included in app bundles a year ago (this is the last piece, if it lands)

File: packages/flutter_tools/lib/src/build_system/targets/android.dart [hunk 1]
```diff
@@ -247,6 +247,10 @@ class AndroidAot extends AotElfBase {
       extraGenSnapshotOptions.add('--trace-precompiler-to=${precompilerTraceFile.path}');
     }
 
+    // AGP handles stripping debug symbols from native libraries, so we default
+    // to not stripping on Android.
+    extraGenSnapshotOptions.add('--no-strip');
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/build_system/targets/android.dart:252]: I don't think this is the right change to make. stripping dart shouldn't be related to stripping the native code

Comment (gmackall) [reply packages/flutter_tools/lib/src/build_system/targets/android.dart:252]: Hmm, I agree they are two different tasks. But do you think these symbols are not useful to play stores?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/targets/android.dart:252]: not sure I understand, libapp.so isn't really a native library. You should leave this as is.

**Comment by gmackall** [comment]
Summarizing offline discussion with @jonahwilliams - `libapp.so` isn't a true native library, and app stores would therefore not be able to make use of `libapp.so.sym`. By default the dart stack traces are not obfuscated (so the symbols are useless). 

There is an opt in feature that developers can use (`--split-debug-info`) which removes this information from libapp.so. But even in this case, the app store wouldn't be able to understand the produced symbol file, because libapp.so is not a true native library. So the file would be useless in either case.

**Comment by gmackall** [comment]
Reopening based on discussion in https://github.com/flutter/flutter/issues/170664

**Comment by gmackall** [comment]
Looks like getting this into a working state by resolving conflicts in the ui was optimistic, will get this out of draft when the tools tests are passing

File: packages/flutter_tools/lib/src/build_system/targets/android.dart (hunk 1 above)
Comment (mraleph) [inline packages/flutter_tools/lib/src/build_system/targets/android.dart]: I wonder if this decision should happen on the layer below: e.g. `build` has Apple specific logic for producing `dSYM`s already, so maybe that's the place for Android target as well e.g. if targeting Android don't strip by default? Or are there codepath where we build for Android but not via AGP?

**Review by mraleph — APPROVED** [review]
Looks reasonable to me, with a minor question.

**Review by bkonyi — APPROVED** [review]
RSLGTM for the tool changes.

File: packages/flutter_tools/lib/src/build_system/targets/android.dart (hunk 1 above)
Comment (gmackall) [reply packages/flutter_tools/lib/src/build_system/targets/android.dart]: Moved to the suggested layer, adjacent to the apple specific logic

**Review by mraleph — APPROVED** [review]
LGTM

**Comment by gmackall** [comment]
Reason for revert: Failing `Linux_pixel_7pro android_obfuscate_test` (https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20android_obfuscate_test/8088/overview)

**Comment by gmackall** [comment]
Will investigate why the test is failing and get a reland up
