### PR TITLE
Remove unused FlutterErrorDetails subclasses

### LINKED ISSUE #27695: Deprecate or delete unused FlutterErrorDetails subclasses
`FlutterErrorDetailsForPointerRouter` and `FlutterErrorDetailsForRendering` aren't currently providing real value as the extra fields stored with the classes appear to always be ignored.

These two classes are only used in a few spots in the framework and the additional fields of these classes are never read anywhere in `package:flutter` or in other places I can locate.

As far as I can tell, these classes were intended to store extra metadata about where certain types of  errors occurred but due to layering, it is impossible to read those fields from `dumpErrorToConsole` in `assertions.dart`. Once `FlutterError` and `FlutterErrorDetails` are refactored to use `DiagnosticsNode` objects there is no real need to introduce extra subclasses for this sort of case.

For example:
`FlutterErrorDetailsForPointerRouter` contains useful information on the router, route, and event
that occurred but it appears we just drop that information on the ground as it isn't possible to use it
from assert.dart as part of `dumpErrorToConsole` due to layering and I can't find any uses of the class outside of `package:flutter`. The simplest solution would be to eliminate these classes and switch the few uses to use `FlutterErrorDetails` adding `DiagnosticsProperty` object describing the extra information.

`FlutterErrorDetailsForPointerRouter` unused fields:
```dart

  /// The pointer router that caught the exception.
  ///
  /// In a typical application, this is the value of [GestureBinding.pointerRouter] on
  /// the binding ([GestureBinding.instance]).
  final PointerRouter router;

  /// The callback that threw the exception.
  final PointerRoute route;

  /// The pointer event that was being routed when the exception was raised.
  final PointerEvent event;

### PR DESCRIPTION
**Pull request by Piinks**
## Description

This removes unused `FlutterErrorDetails` subclasses `FlutterErrorDetailsForPointerRouter` and `FlutterErrorDetailsForRendering`. 
I may deprecate them instead, checking to see if these uncommon classes are actually breaking.

## Related Issues

Fixes #27695

## Tests

Just re-factoring.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Piinks** [comment]
@jacob314 is this what you had in mind for #27695? I'm checking now to see if it is breaking to remove these classes, otherwise I'll deprecate.

**Comment by Piinks** [comment]
Removing these classes is non-breaking ✅

File: packages/flutter/lib/src/gestures/pointer_router.dart [hunk 1]
```diff
@@ -80,18 +80,17 @@ class PointerRouter {
       InformationCollector collector;
       assert(() {
         collector = () sync* {
-          yield DiagnosticsProperty<PointerEvent>('Event', event, style: DiagnosticsTreeStyle.errorProperty);
+          yield DiagnosticsProperty<PointerRouter>('PointerRouter', this, style: DiagnosticsTreeStyle.errorProperty);
```
Comment (jacob314) [inline packages/flutter/lib/src/gestures/pointer_router.dart:83]: by convention property names should typically lower case. So perhaps
'router', 'route', and 'event' instead of PointerRouter, PointerRoute, and PointerEvent.

File: packages/flutter/lib/src/rendering/debug_overflow_indicator.dart [hunk 2]
```diff
@@ -242,14 +242,14 @@ mixin DebugOverflowIndicatorMixin on RenderObject {
...
-      FlutterErrorDetailsForRendering(
+      FlutterErrorDetails(
         exception: FlutterError('A $runtimeType overflowed by $overflowText.'),
         library: 'rendering library',
         context: ErrorDescription('during layout'),
-        renderObject: this,
         informationCollector: () sync* {
           if (debugCreator != null)
             yield DiagnosticsDebugCreator(debugCreator);
+          yield DiagnosticsProperty<RenderObject>('RenderObject', this, style: DiagnosticsTreeStyle.errorProperty);
```
Comment (jacob314) [inline packages/flutter/lib/src/rendering/debug_overflow_indicator.dart:252]: similarly, renderObject instead of `RenderObject`.

Comment (jacob314) [reply packages/flutter/lib/src/rendering/debug_overflow_indicator.dart:252]: for this one you should give the property a lower priority level as you don't want it to actually show up as that will make the error confusing to read. I think `level: DiagnosticsLevel.debug` is what you want. https://api.flutter.dev/flutter/foundation/DiagnosticLevel-class.html

**Review by jacob314 — COMMENTED** [review]
That is what I had in mind with the exception that we need to make sure the error messages don't become harder to read so some or all of the properties added should be given a a low priority level.

**Comment by Piinks** [comment]
Awesome. Thank you for the feedback! I'll update this with your suggestions and add some tests to make sure the output is nice and readable.

**Review by jacob314 — APPROVED** [review]
lgtm
