### PR TITLE
Trim any text before osascript JSON response

### LINKED ISSUE #164772: .osascript returned non-JSON response: start | iOS
I have been facing this issue for months. I had reinstalled macos multiple times, it works properly for sometime after reinstall then again same issue.

Fixes I have tried:

1. Reinstall mac, xcode, flutter
2. Upgrade to latest flutter

I have attached flutter run --verbose file.

[flutter_run_output.txt](https://github.com/user-attachments/files/19123154/flutter_run_output.txt)

Steps to reproduce:

1. flutter run to an iOS device - Doesn't matter wireless or wired.

Alternate step to develop:

1. flutter run (it'll fail, but open xcode and xcode will continue and install the app)
2. flutter attach -d device-id

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.3.1 24D70 darwin-arm64, locale en-IN)
    • Flutter version 3.27.1 on channel stable at /Users/tilak/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (3 months ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
    • Android SDK at /Users/tilak/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3.4.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 243.23654.44

[✓] Connected device (4 available)
    • Tilak’s iPhone (mobile)         • 00008120-000814860131A01E • ios            • iOS 18.3.1 22D72
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.3.1 24D70 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.3.1 24D70 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 134.0.6998.45

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
flutter run
Connected devices:
macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.3.1 24D70 darwin-arm64
Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.3.1 24D70 darwin-arm64
Chrome (web)                    • chrome                • web-javascript • Google Chrome 134.0.6998.45

Wirelessly connected devices:
Tilak’s iPhone (mobile) • 00008120-000814860131A01E • ios • iOS 18.3.1 22D72

[1]: macOS (macos)
[2]: Mac Designed for iPad (mac-designed-for-ipad)
[3]: Chrome (chrome)
[4]: Tilak’s iPhone (00008120-000814860131A01E)
Please choose one (or "q" to quit): 4
Launching lib/main.dart on Tilak’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: DS9S458A25
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         8.3s
Xcode build done.                                           31.5s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
osascript returned non-JSON response: start process_extensions{"status":true,"errorMessage":null,"debugResult":{"completed":false,"status":"running","errorMessage":null}}
Could not run build/ios/iphoneos/Runner.app on 00008120-000814860131A01E.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Installing and launching...                                        11.9s
Error launching application on Tilak’s iPhone.
```

### PR DESCRIPTION
**Pull request by vashworth**
Fixes https://github.com/flutter/flutter/issues/164772.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/xcode_debug.dart [hunk 1]
```diff
@@ -269,8 +269,19 @@ class XcodeDebug {
 
   @visibleForTesting
   XcodeAutomationScriptResponse? parseScriptResponse(String results) {
+    // Some users reported text before the json. Trim any text before the opening
+    // curly brace.
+    // Example: `start process_extensions{"status":true,"errorMessage":null,"debugResult":{"completed":false,"status":"running","errorMessage":null}}`
+    final String trimmedResults;
+    final int jsonBeginIndex = results.indexOf('{');
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/ios/xcode_debug.dart:276]: Is it possible to have a `{` in the reported text before the JSON? If so, this will still cause decoding to fail. If we're concerned that this is a possibility, we might want to put this into a loop that trims the results further if we fail to decode.

Comment (vashworth) [reply packages/flutter_tools/lib/src/ios/xcode_debug.dart:276]: I highly doubt there will be a `{` before the JSON. The results here are a response from a `osascript` command. I can add the loop, though, if you think that's better

**Review by bkonyi — APPROVED** [review]
LGTM!

**Comment by dado3212** [comment]
@Quelaan1 and @vashworth FYI this is because of MacForge (potentially because of installing as part of SpacesRenamer). You can fix it by disabling injection after the Dock is restarted, or downloading a fixed version from [spaces-renamer.zip](https://github.com/user-attachments/files/20972723/spaces-renamer.zip).

**Comment by dado3212** [comment]
@Quelaan1 and @vashworth FYI this is because of MacForge (potentially because of installing as part of SpacesRenamer). You can fix it by disabling injection after the Dock is restarted, or downloading a fixed version from [spaces-renamer.zip](https://github.com/user-attachments/files/20972723/spaces-renamer.zip) (original issue flagged by #164772).
