### PR TITLE
Fix issue with stack traces getting mangled

### LINKED ISSUE #59893: Stack frame parser is crashing with malformed asynchronous gap lines
## Description

When running tests, exceptional behavior sometimes causes the diagnostics to crash with an exception similar to the following:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Expected ===== asynchronous gap =========================== to match RegExp: pattern=^(.+)
(\d+):(\d+)\s+(.+)$ flags=.
'package:flutter/src/foundation/stack_frame.dart':
Failed assertion: line 115 pos 12: 'match != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      StackFrame._parseWebDebugFrame (package:flutter/src/foundation/stack_frame.dart:115:12)
#3      StackFrame._parseWebFrame (package:flutter/src/foundation/stack_frame.dart:101:14)
#4      StackFrame.fromStackTraceLine (package:flutter/src/foundation/stack_frame.dart:195:14)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#7      SkipWhileIterator.moveNext (dart:_internal/iterable.dart:680:22)
#8      new List.from (dart:core-patch/array_patch.dart:50:19)
#9      new List.of (dart:core-patch/array_patch.dart:68:17)
#10     Iterable.toList (dart:core/iterable.dart:404:12)
#11     StackFrame.fromStackString (package:flutter/src/foundation/stack_frame.dart:96:10)
#12     FlutterError.defaultStackFilter (package:flutter/src/foundation/assertions.dart:945:54)
#13     new DiagnosticsStackTrace (package:flutter/src/foundation/assertions.dart:1088:59)
#14     FlutterErrorDetails.debugFillProperties (package:flutter/src/foundation/assertions.dart:650:22)
#15     DiagnosticableNode.builder.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:2944:18)
#16     DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2947:8)
#17     _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1126:55)
#18     DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:2961:105)
#19     TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1250:63)
#20     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1128:14)
#21     FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:900:11)
#22     TestWidgetsFlutterBinding._runTest.<anonymous closure> (package:flutter_test/src/binding.dart:618:24)
#23     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1032:14)
#24     TestWidgetsFlutterBinding._runTest.handleUncaughtError (package:flutter_test/src/binding.dart:690:20)
#25     TestWidgetsFlutterBinding._runTest.<anonymous closure> (package:flutter_test/src/binding.dart:714:28)
#30     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart)
```

This crash can be reproduced with the following test:

```dart
  testWidgets('async gap', (tester) async {
    final ctrl = Completer<String>();

    ctrl.future.then((value) {}, onError: (dynamic err, StackTrace bt) {
      FlutterError.reportError(FlutterErrorDetails(
        exception: err,
        stack: bt,
      ));
    });

    ctrl.completeError('Test');
  });
```

## Version

```
Flutter 1.20.0-1.0.pre • channel master • https://github.com/flutter/flutter
Framework • revision 401690a64f (7 days ago) • 2020-06-12 19:45:48 -0700
Engine • revision 965fbbed17
Tools • Dart 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)
```

### PR DESCRIPTION
**Pull request by dnfield**
## Description

Certain types of async errors can get through with a mangled stack trace today, which causes a failure noted in the linked bug - the stack frame parser does not want stack traces as they come from package:stack_trace, we want the raw ones.

## Related Issues

Fixes #59893

## Tests

I added the following tests:

Test that throws that kind of error and then that we don't run into issues trying to parse it. Also adds an assertion that we don't get an unmangled trace.

/cc @PixelToast 

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by dnfield** [comment]
(original commit was missing the newly added test file)

**Comment by PixelToast** [comment]
Instead of dealing with the mangled stack traces in onError, I think it would be more beneficial to avoid non-vm stack traces being propagated in the first place because this may still crop up in other places.

In my minimal repo, the problematic trace comes from the `ZoneSpecification` `errorCallback` defined here: https://github.com/dart-lang/stack_trace/blob/4d1ef4eddcd9b18c23bf19fd9d37245d3c81fa2e/lib/src/stack_zone_specification.dart#L172

What we could do is define an errorCallback in our own flutter_test zone which demangles it, and then just replace the FlutterErrorDetails copy in onError with an assertion.

Alternatively, we could modify `package:stack_trace` to make sure implementers of `StackTrace` only produce traces consistent with the current platform, requiring anyone that depended on mangled traces to call a separate method.

**Comment by dnfield** [comment]
I think the probem with setting up another zone for this is that the test, as written, is directly calling FlutterError.reportError with a mangled stack trace. It's not going through the zone error handling mechanism - it's created and caught in the test itself. This is a constructed case, but it matches what I've seen in some nested network exceptions elsewhere.

It's not clear to me where or why the package:stack_trace types are getting introduced. Perhaps from package:test? 

I also wouldn't bank on getting package:stack_trace changed here - part of the point of that package is to make traces look more human friendly, as defined by that package.

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 1]
```diff
@@ -379,6 +379,9 @@ class FlutterErrorDetails with Diagnosticable {
   /// The [exception] must not be null; other arguments can be left to
   /// their default values. (`throw null` results in a
   /// [NullThrownError] exception.)
+  // If you add a property to this class, do not forget to update _runTest in
```
Comment (PixelToast) [inline packages/flutter/lib/src/foundation/assertions.dart:382]: It might be better to implement a copyWith instead of forcing us to go into flutter_test to make changes.

File: packages/flutter_test/lib/src/binding.dart [hunk 2]
```diff
@@ -579,6 +579,10 @@ abstract class TestWidgetsFlutterBinding extends BindingBase
       // our main future completing.
       assert(Zone.current == _parentZone);
       if (_pendingExceptionDetails != null) {
+        assert(
+          _unmangle(_pendingExceptionDetails.stack) == _pendingExceptionDetails.stack,
+          'The test binding presented an unmangled a test stack trace to the framework.',
```
Comment (PixelToast) [inline packages/flutter_test/lib/src/binding.dart:584]: Change to `The framework was provided a mangled stack trace by a test binding`, the convention for assertion messages is to describe a true but unexpected state, afaik.

File: packages/flutter_test/test/bindings_async_gap_test.dart [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+    };
+
+    final AutomatedTestWidgetsFlutterBinding binding = AutomatedTestWidgetsFlutterBinding();
+    await binding.runTest(() async {
+      final Completer<String> completer = Completer<String>();
+
+      completer.future.then(
+        (String value) {},
+        onError: (dynamic error, StackTrace stack) {
+          FlutterError.reportError(FlutterErrorDetails(
```
Comment (PixelToast) [inline packages/flutter_test/test/bindings_async_gap_test.dart:32]: We should assert that the stack trace is actually mangled here.

File: packages/flutter_test/test/bindings_async_gap_test.dart [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+            stack: stack,
+          ));
+        }
+      );
+
+      completer.completeError(const CustomException());
+    }, null);
+
+    final FlutterErrorDetails details = await errorCompleter.future;
+    expect(details, isNotNull);
```
Comment (PixelToast) [inline packages/flutter_test/test/bindings_async_gap_test.dart:43]: This test can't fail, perhaps you forgot to assert `details.stack` is unmangled.

**Review by pingbird — CHANGES_REQUESTED** [review]

**Comment by PixelToast** [comment]
This is my first review, so please tell me if I'm doing anything wrong 😰 

Yes, package:test is the one applying the zone to flutter tests: https://github.com/dart-lang/test/blob/658e47e99c170605f7ab7502c556aae295ed9f46/pkgs/test_api/lib/src/backend/invoker.dart#L386

I think the approach of demangling in onError will work to address any current bugs. The reason for my concerns about them being propagated to error handlers is that a few different places in flutter still make the assumption that a stack trace isn't mangled (and we could make it again in the future).

After some digging it looks like the only uses of `StackFrame` parsing outside of `FlutterError.onError` are in some tests that call `toDiagnosticsNode` directly:

https://github.com/flutter/flutter/blob/4d7525f05c05a6df0b29396bc9eb78c3bf1e9f89/packages/flutter/test/foundation/assertions_test.dart#L340

These will throw if a mangled stack is ever passed to them in the future.

All three of us (!) originally thought this was coming from the vm, so at the very least `StackFrame.fromStackTraceLine` should throw a better error message when given a mangled stack.

**Comment by PixelToast** [comment]
I found another place this could fail, `TestRenderingFlutterBinding`:

https://github.com/flutter/flutter/blob/9de8bfe61062ff167224fa67e8e5b445e67291d1/packages/flutter/test/rendering/rendering_tester.dart#L29-L34

File: packages/flutter_test/lib/src/binding.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter_test/lib/src/binding.dart:584]: This part isn't the framework though - it's in the test binding code.

File: packages/flutter_test/test/bindings_async_gap_test.dart (hunk 3 above)
Comment (dnfield) [reply packages/flutter_test/test/bindings_async_gap_test.dart:32]: Done

File: packages/flutter_test/test/bindings_async_gap_test.dart (hunk 4 above)
Comment (dnfield) [reply packages/flutter_test/test/bindings_async_gap_test.dart:43]: It fails without the change to the test binding - it just not on this expectation. This is just here to make sure the test is doing what we think it's supposed to do.

The failure would come in the framework code where we get a Chain instead of a StackTrace.

Comment (PixelToast) [reply packages/flutter_test/test/bindings_async_gap_test.dart:43]: Ahh, my bad, it fails in the reportError

File: packages/flutter_test/lib/src/binding.dart (hunk 2 above)
Comment (PixelToast) [reply packages/flutter_test/lib/src/binding.dart:584]: I was just confused by the grammar then, specifically the `a` after `unmangled`

Comment (dnfield) [reply packages/flutter_test/lib/src/binding.dart:584]: Ahh I see I'll clean that up

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/lib/src/foundation/assertions.dart:382]: Done

**Comment by dnfield** [comment]
A lot of those other areas are more specialized and not exposed for use in end-users tests. I think we should fix them because it could be confusing for framework developers, but probably do so in another patch - unless you think there's a generalized solution for them.

One thing I don't think we can do is have this check exist in the stack filter, since we don't want to add a dependency on package:stack_trace to the framework.

**Review by pingbird — APPROVED** [review]

**Comment by PixelToast** [comment]
Yeah, I couldn't come up with a good way for these to be filtered in the framework either (w/o the added dependency), maybe hix or goderbaur knows more.

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 5]
```diff
@@ -379,6 +379,7 @@ class FlutterErrorDetails with Diagnosticable {
   /// The [exception] must not be null; other arguments can be left to
   /// their default values. (`throw null` results in a
   /// [NullThrownError] exception.)
+  // If you add a property to this class, do not forget to update [copyWith].
```
Comment (Hixie) [inline packages/flutter/lib/src/foundation/assertions.dart:382]: should we say this on every class with a copyWith?

**Comment by Hixie** [comment]
We now call _unmangle in three places; does this make any of the preexisting ones redundant?

**Review by goderbauer — APPROVED** [review]
LGTM modulo Hixie's comment about redundancy.

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 5 above)
Comment (dnfield) [reply packages/flutter/lib/src/foundation/assertions.dart:382]: That's fair, I had this in here before adding copy with. Removing.

**Comment by dnfield** [comment]
AFAICT, we could reduce the calls to _unmangle in `handleUncaughtError`, but that's a different path than `FlutterError.reportError`, at least potentially. 

Basically, we have to deal with the case where an uncaught exception (sync or async) is thrown in the test, _and_ we have to deal with the case where `FlutterError.reportError` is called directly. Either one can happen in a test, and they go through two different paths here.

**Comment by dnfield** [comment]
To explain - we could reassing the `stack` variable using `_unmangle` instead of calling `_unmangle` on it in two places. But we'd still have two distinct places in real code (plus one in the assert I added).

**Comment by Hixie** [comment]
I've no problem it being in three places so long as we're confident that none of those places are entirely redundant (i.e. are entirely subsumed by one of the others). Test frameworks are inherently pretty crazy because they have to deal with unpredictable failures almost by definition.

**Comment by flutter-github-sync** [comment]
Google testing passed!
