### PR TITLE
Mac Page Up / Page Down in text fields

### LINKED ISSUE #77611: Page up/down support on desktop text fields
When focused on a multiline text field, pressing page up/down should scroll the text field but not move the cursor (tested on a native Mac, unsure of other platforms).

Related? https://github.com/flutter/flutter/issues/70553

### LINKED ISSUE #105448: PageUp/PageDown in a text field
The PageUp/PageDown keys should move the cursor up/down by a bunch of lines.  Currently, they don't do any thing at all.

### To reproduce

  1. Run any app with a multiline text field, such as the one below.
  2. Focus the field and enter a couple of lines of text.
  3. Press PageUp.

Expected: The cursor jumps up by one page, or to the top.
Actual: Nothing happens.

Vice versa for PageDown.

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(minLines: 4, maxLines: 4),
          ],
        ),
      ),
    );
  }
}
```

</details>

Related: It also looks like our scrollables don't properly respond to pageup/down either: https://github.com/flutter/flutter/issues/93521

### PR DESCRIPTION
**Pull request by justinmc**
This PR implements the Mac page up/down keyboard shortcuts, which scroll by page.  The selection changing behavior of pageup/down and shift + pageup/down were handled by @tgucio in https://github.com/flutter/flutter/pull/107602.

out

Closes https://github.com/flutter/flutter/issues/105448
Closes https://github.com/flutter/flutter/issues/77611

### CODE REVIEW

File: packages/flutter/lib/src/widgets/text_editing_intents.dart [hunk 1]
```diff
@@ -234,6 +234,23 @@ class ScrollToDocumentBoundaryIntent extends DirectionalTextEditingIntent {
   }) : super(forward);
 }
 
+/// Scrolls up or down by page depending on the [forward] parameter.
+class ScrollByPageIntent extends DirectionalTextEditingIntent {
+  /// Creates a [ScrollByPageIntent].
+  const ScrollByPageIntent({
+    required bool forward,
+  }) : super(forward);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_editing_intents.dart:242]: I thought we had the super parameter lint enabled?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -3292,6 +3293,80 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     }
   }
 
+  /// Scrolls down by page if the `forward` parameter is true, or up by page
+  /// otherwise.
+  void _scrollByPage(ScrollByPageIntent intent) {
```
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:3298]: If the scroll physics disallows implicit scrolling should the scroll view sill scroll?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -3292,6 +3293,80 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    final Rect extentRect = renderEditable.getLocalRectForCaret(
+      _value.selection.extent,
+    );
+    if (intent.forward) {
+      if (_value.selection.extentOffset >= _value.text.length) {
+        return;
+      }
+      final Offset nextExtentOffset =
+          Offset(extentRect.left, extentRect.top + position.viewportDimension);
+      final double height = _scrollController.position.maxScrollExtent + renderEditable.size.height;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3338]: This assumes the text field scrolls vertically?

**Comment by knopp** [comment]
What about `ScrollIntent`? It's already used in default app shortcuts (with `type: ScrollIncrementType.page`)

**Comment by Piinks** [comment]
I think @knopp is right about ScrollIncrementType.page, we use the same distance determination for page scrolling on scrollbar and keyboard scroll actions. It may be a good idea to centralize that logic so it is easier to re-use.

File: packages/flutter/lib/src/widgets/text_editing_intents.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_intents.dart:242]: This confused me for a second.  It looks like the `forward` param is positional in DirectionalTextEditingIntent ([code](https://github.com/flutter/flutter/blob/a494a12bb0c42b05d110dc7d3082ca6585f1c6ff/packages/flutter/lib/src/widgets/text_editing_intents.dart#L23-L25)).  Is that intentional?  I guess I will make this one positional too, but tell me if you think there is a better approach.  Making this positional is a departure from the other Intens in DefaultTextEditingIntents that all have a `forward` named parameter.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_editing_intents.dart]: Actually this is obsolete if we replace this with ScrollIntent as in https://github.com/flutter/flutter/pull/105497/commits/d4bbc340023000765222983b17ec53709024cf37.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -3292,6 +3294,86 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    if (widget.maxLines == 1) {
+      return;
+    }
+
+    final TextSelection nextSelection;
+    final Rect extentRect = renderEditable.getLocalRectForCaret(
+      _value.selection.extent,
+    );
+    final ScrollableState? state = _scrollableKey.currentState as ScrollableState?;
+    final double increment = ScrollAction.calculateScrollIncrement(
```
Comment (tgucio) [inline packages/flutter/lib/src/widgets/editable_text.dart:3334]: Since this is only used for vertically scrolled / multi-line fields, I wonder if using state.renderEditable.size.height instead of adding ScrollAction.calculateScrollIncrement() would be sufficient?

**Review by tgucio — COMMENTED** [review]
Added review comments suggesting an alternative approach to keep vertical runs and not require ScrollAction changes.

Published https://github.com/flutter/flutter/pull/107602 with those changes.

**Comment by justinmc** [comment]
@tgucio It looks like the scroll-only behavior that I implemented in this PR is specific to MacOS.  I tried gedit on Linux and Notepad on Windows and both of them move the cursor, as you described.

How about we keep both of our PRs?  I'll do the Mac behavior in this one and leave Linux and Windows unimplemented, and you fill that in on your PR.

**Comment by justinmc** [comment]
@Piinks Let me know what you think of this approach of sharing some code with ScrollAction.

I'm also interested in what you and @LongCatIsLooong think about my making ScrollIntent overridable to get this to work.

**Comment by tgucio** [comment]
@justinmc just tried a bunch of different apps on macOS (long form fields on Chrome, Notes, TextEdit) and I find it almost fascinating that indeed page up/down scrolls without moving the caret :). Let me continue the caret movement implementation in #106484 then and we can differentiate in default_text_editing_shortcuts.dart.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 5]
```diff
@@ -3292,6 +3294,87 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+      state!,
+      type: ScrollIncrementType.page,
+    );
+    final ScrollPosition position = _scrollController.position;
+    if (intent.forward) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/editable_text.dart:3340]: Since `forward` determines how to apply the value returned from `calculateScrollIncrement`, maybe it can actually determined in `getIncrement` so you only have to expose/call that one method.

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 6]
```diff
@@ -1628,10 +1628,10 @@ class ScrollAction extends Action<ScrollIntent> {
     }
   }
 
-  // Find out how much of an increment to move by, taking the different
-  // directions into account.
-  double _getIncrement(ScrollableState state, ScrollIntent intent) {
-    final double increment = _calculateScrollIncrement(state, type: intent.type);
+  /// Find out how much of an increment to move by, taking the different
+  /// directions into account.
+  static double getIncrement(ScrollableState state, ScrollIntent intent) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scrollable.dart:1633]: Maybe this could be `getDirectionalIncrement` in the public space? It already call on calculateScrollIncrement. Could you incorporate the logic for a forward intent or translate forward into `intent.direction`?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 4 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/editable_text.dart:3335]: > I wonder if using state.renderEditable.size.height instead of adding ScrollAction.calculateScrollIncrement() would be sufficient

It could be for this specific use case, but for consistency across the framework, we should probably establish a pattern. :)

**Review by Piinks — COMMENTED** [review]
I think that making some of the ScrollAction public is a good idea. Scrollbar uses this too, but instead it just duplicates the logic. With more use cases now, I think making it accessible to other widgets makes sense. After this lands, I can go clean up the Scrollbar logic so we are consistent.

**Comment by justinmc** [comment]
Planning to return to this once I finish [ContextMenu](https://github.com/flutter/flutter/pull/107193).

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 7]
```diff
@@ -3292,6 +3294,86 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+    );
+    if (destination == position.pixels) {
+      return;
+    }
+    _scrollController.jumpTo(destination);
+  }
+
+  /// Extend the selection down by page if the `forward` parameter is true, or
+  /// up by page otherwise.
+  void _extendSelectionByPage(ExtendSelectionByPageIntent intent) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:3636]: This PR now handles vertical runs.  Let me know if I've missed anything though.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Now only one method is exposed, `getDirectionalIncrement`.  It just uses a ScrollIntent like usual, which I create here.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 5 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:3654]: I've updated this to only expose getDirectionalIncrement 👍

File: packages/flutter/lib/src/widgets/scrollable.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/scrollable.dart]: Translated to intent.direction and renamed to getDirectionalIncrement 👍

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 7 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:3636]: Actually I was mistaken and it doesn't, but maybe it doesn't need to because it only moves the cursor during selection.  Let me know what you think.

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 8]
```diff
@@ -1647,9 +1647,9 @@ class ScrollAction extends Action<ScrollIntent> {
     }
   }
 
-  // Find out how much of an increment to move by, taking the different
-  // directions into account.
-  double _getIncrement(ScrollableState state, ScrollIntent intent) {
+  /// Find out how much of an increment to move by, taking the different
+  /// directions into account.
+  static double getDirectionalIncrement(ScrollableState state, ScrollIntent intent) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scrollable.dart:1652]: Nice!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
This is awesome! I'll file an issue to update scrollbar now that the increment logic is accessible. Thank you!

**Comment by justinmc** [comment]
No problem!

This PR should wait for https://github.com/flutter/flutter/pull/107602 and then I'll address any conflicts before merging.

**Comment by Piinks** [comment]
https://github.com/flutter/flutter/pull/107602 landed, would you like to update here so this can be merged @justinmc?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 7 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:3986]: To explain this here for anyone that reads this thread: We decided to not handle shift + pageup/down in this PR, so it only does scrolling and does not need vertical runs.  That is handled in another PR by @tgucio that has since been merged.

**Comment by justinmc** [comment]
@Piinks Yes thanks, I've updated this to no longer handle shift + pageup/down (which was taken care of in https://github.com/flutter/flutter/pull/107602).  Now it does only Mac and iOS pageup/down scrolling.

You're welcome to re-review if you want!  Otherwise I'll merge this later assuming it goes green.

**Comment by justinmc** [comment]
Google testing has been pending for days, I'm going to go ahead and merge as it should be very low risk for breakages.  I'll monitor it after merge.
