### PR TITLE
Fixes zero route transition duration crash

### LINKED ISSUE #86604: Navigator 2.0: zero route transition duration crashes
When using Navigator 2.0 on web, using `Duration.zero` for a route's `transitionDuration` crashes.

This comes from a pretty common use case of wanting to have no pop animation on the web. I believe this is only on web, no other platforms.

Tested on Flutter stable 2.2.3 and dev 2.4.0-4.0.pre.

## Steps to Reproduce

1. Run the below example app in Chrome
2. Click "Show page two"
3. Click the browser's back button, crashes

This only happens when clicking the browser's back button, not for instance via an `AppBar` back button.

A workaround is to use `Duration(microseconds: 1)` for `transitionDuration`.

## Example app

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerDelegate: MyRouterDelegate(),
      routeInformationParser: MyRouteInformationParser(),
    );
  }
}

class AppRoute {
  AppRoute({required this.showSubPage});

  final bool showSubPage;
}

class MyRouteInformationParser extends RouteInformationParser<AppRoute> {
  @override
  Future<AppRoute> parseRouteInformation(
      RouteInformation routeInformation) async {
    return AppRoute(showSubPage: routeInformation.location! == '/two');
  }

  @override
  RouteInformation? restoreRouteInformation(AppRoute path) {
    return RouteInformation(location: path.showSubPage ? '/two' : '/');
  }
}

class MyRouterDelegate extends RouterDelegate<AppRoute>
    with ChangeNotifier, PopNavigatorRouterDelegateMixin<AppRoute> {
  final GlobalKey<NavigatorState> navigatorKey;

  bool _showSubPage = false;

  MyRouterDelegate() : navigatorKey = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return Navigator(
      key: navigatorKey,
      pages: [
        NoAnimationPage(
          child: Scaffold(
            body: ElevatedButton(
              child: Text('Show page two'),
              onPressed: () {
                _showSubPage = true;
                notifyListeners();
              },
            ),
          ),
        ),
        if (_showSubPage)
          NoAnimationPage(
            child: Scaffold(body: Text('Page two')),
          ),
      ],
      onPopPage: (route, result) {
        if (!route.didPop(result)) {
          return false;
        }

        _showSubPage = false;
        notifyListeners();
        return true;
      },
    );
  }

  @override
  AppRoute? get currentConfiguration {
    return AppRoute(showSubPage: _showSubPage);
  }

  @override
  Future<void> setNewRoutePath(AppRoute path) async {
    _showSubPage = path.showSubPage;
    notifyListeners();
  }
}

class NoAnimationPage<T> extends Page<T> {
  const NoAnimationPage({required this.child});

  final Widget child;

  @override
  Route<T> createRoute(BuildContext context) {
    return NoAnimationPageRoute<T>(page: this);
  }
}

class NoAnimationPageRoute<T> extends PageRoute<T> {
  NoAnimationPageRoute({required NoAnimationPage<T> page})
      : super(settings: page);

  // This is what causes the bug - using Duration(milliseconds: 1) works okay
  @override
  Duration get transitionDuration => Duration.zero;

  NoAnimationPage<T> get _page => settings as NoAnimationPage<T>;

  @override
  Widget buildPage(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation) {
    return _page.child;
  }

  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation, Widget child) {
    return child;
  }

  @override
  bool get maintainState => false;

  @override
  Color? get barrierColor => null;

  @override
  String? get barrierLabel => null;
}
```

## Crash log

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Builder:
Assertion failed:
_debugLocked && !_debugUpdatingPage
is not true


The relevant error-causing widget was
MaterialApp MaterialApp:file:///Users/tom/temp/zero_duration_crash/lib/main.dart:10:24
When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
packages/flutter/src/widgets/navigator.dart 3955:29                           [_flushHistoryUpdates]
packages/flutter/src/widgets/navigator.dart 5235:7                            finalizeRoute
packages/flutter/src/widgets/routes.dart 72:7                                 didPop
packages/flutter/src/widgets/routes.dart 245:18                               didPop
packages/flutter/src/widgets/routes.dart 650:18                               didPop
packages/flutter/src/widgets/navigator.dart 3096:15                           pop
packages/flutter/src/widgets/navigator.dart 3250:5                            markForPop
packages/flutter/src/widgets/navigator.dart 1002:27                           handleExitingRoute
packages/flutter/src/widgets/navigator.dart 1041:7                            resolve
packages/flutter/src/widgets/navigator.dart 818:53                            [_transition]
packages/flutter/src/widgets/navigator.dart 3935:9                            [_updatePages]
packages/flutter/src/widgets/navigator.dart 3621:7                            didUpdateWidget
packages/flutter/src/widgets/framework.dart 4855:57                           update
packages/flutter/src/widgets/framework.dart 3412:14                           updateChild
packages/flutter/src/widgets/framework.dart 4690:16                           performRebuild
packages/flutter/src/widgets/framework.dart 4355:5                            rebuild
packages/flutter/src/widgets/framework.dart 4746:5                            update
packages/flutter/src/widgets/framework.dart 3412:14                           updateChild
packages/flutter/src/widgets/framework.dart 4690:16                           performRebuild
packages/flutter/src/widgets/framework.dart 4355:5                            rebuild
packages/flutter/src/widgets/framework.dart 5020:5                            update
packages/flutter/src/widgets/framework.dart 3412:14                           updateChild
packages/flutter/src/widgets/framework.dart 4690:16                           performRebuild
packages/flutter/src/widgets/framework.dart 4355:5                            rebuild
packages/flutter/src/widgets/framework.dart 5020:5                            update
packages/flutter/src/widgets/framework.dart 3412:14                           updateChild
packages/flutter/src/widgets/framework.dart 4690:16                           performRebuild
packages/flutter/src/widgets/framework.dart 4840:11                           performRebuild
packages/flutter/src/widgets/framework.dart 4355:5                            rebuild
packages/flutter/src/widgets/framework.dart 2620:31                           buildScope
packages/flutter/src/widgets/binding.dart 877:9                               drawFrame
packages/flutter/src/rendering/binding.dart 330:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1143:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1080:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 996:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 974:13                            invoke
lib/_engine/engine/platform_dispatcher.dart 151:5                             invokeOnDrawFrame
lib/_engine/engine.dart 445:45                                                <fn>
════════════════════════════════════════════════════════════════════════════════
```

<details>
  <summary>Logs</summary>

```
[+14516 ms] Waiting for connection from debug service on Chrome... (completed in 15.6s)
[        ] Synced 28.2MB.
[        ] <- accept
[        ] Caching compiled dill
[  +72 ms] Using Google Chrome 91.0.4472.114 

[+1245 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:55609/devtools/browser/c0532913-52ba-4384-bfbb-63d34be0a339
[ +794 ms] DwdsInjector: Received request for entrypoint at http://localhost:55388/main_module.bootstrap.js
[   +4 ms] MetadataProvider: Loading debug metadata...
[  +11 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +6 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:55388/main_module.bootstrap.js
[+1275 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +83 ms] DevHandler: Debug service listening on ws://127.0.0.1:55635/Y4f94HioD5c=/ws

[  +26 ms] This app is linked to the debug service: ws://127.0.0.1:55635/Y4f94HioD5c=/ws
[   +7 ms] Debug service listening on ws://127.0.0.1:55635/Y4f94HioD5c=/ws
[        ] 💪 Running with sound null safety 💪
[   +2 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+17259 ms] ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] The following assertion was thrown building Builder:
[        ] Assertion failed:
[        ] file:///Users/tom/fvm/versions/stable/packages/flutter/lib/src/widgets/navigator.dart:3921:12
[        ] _debugLocked && !_debugUpdatingPage
[        ] is not true
[        ] The relevant error-causing widget was:
[        ]   MaterialApp file:///Users/tom/temp/zero_duration_crash/lib/main.dart:10:24
[        ] When the exception was thrown, this was the stack:
[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
[        ] packages/flutter/src/widgets/navigator.dart 3921:29                           [_flushHistoryUpdates]
[        ] packages/flutter/src/widgets/navigator.dart 5204:7                            finalizeRoute
[        ] packages/flutter/src/widgets/routes.dart 69:7                                 didPop
[        ] packages/flutter/src/widgets/routes.dart 242:18                               didPop
[        ] packages/flutter/src/widgets/routes.dart 646:18                               didPop
[        ] packages/flutter/src/widgets/navigator.dart 3085:15                           pop
[        ] packages/flutter/src/widgets/navigator.dart 3239:5                            markForPop
[        ] packages/flutter/src/widgets/navigator.dart 1002:27                           handleExitingRoute
[        ] packages/flutter/src/widgets/navigator.dart 1041:7                            resolve
[        ] packages/flutter/src/widgets/navigator.dart 818:53                            [_transition]
[        ] packages/flutter/src/widgets/navigator.dart 3901:9                            [_updatePages]
[        ] packages/flutter/src/widgets/navigator.dart 3606:7                            didUpdateWidget
[        ] packages/flutter/src/widgets/framework.dart 4761:57                           update
[        ] packages/flutter/src/widgets/framework.dart 3350:14                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4599:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4267:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 4655:5                            update
[        ] packages/flutter/src/widgets/framework.dart 3350:14                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4599:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4267:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 4922:5                            update
[        ] packages/flutter/src/widgets/framework.dart 3350:14                           updateChild
[        ] packages/flutter/src/widgets/framework.dart 4599:16                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4746:11                           performRebuild
[        ] packages/flutter/src/widgets/framework.dart 4267:5                            rebuild
[        ] packages/flutter/src/widgets/framework.dart 2582:31                           buildScope
[        ] packages/flutter/src/widgets/binding.dart 875:9                               drawFrame
[        ] packages/flutter/src/rendering/binding.dart 328:5                             [_handlePersistentFrameCallback]
[        ] packages/flutter/src/scheduler/binding.dart 1144:15                           [_invokeFrameCallback]
[        ] packages/flutter/src/scheduler/binding.dart 1082:9                            handleDrawFrame
[        ] packages/flutter/src/scheduler/binding.dart 998:5                             [_handleDrawFrame]
[        ] lib/_engine/engine/platform_dispatcher.dart 963:13                            invoke
[        ] lib/_engine/engine/platform_dispatcher.dart 152:5                             invokeOnDrawFrame
[        ] lib/_engine/engine.dart 262:45                                                <fn>
[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
None
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-FI)
    • Flutter version 2.2.3 at /Users/tom/fvm/versions/stable
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tom/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tom/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • macOS (desktop)                       • macos         • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
If the page update pop a page with zero duration, the Route.didPop will call Navigator.finalizeRoute synchronously which calls _flushHistoryUpdates before the _updatePage finishes. This pr defers didPop call in markForPop during TransitionDelegate.resolve and only call didpop during the _flushHistoryUpdates.

fixes https://github.com/flutter/flutter/issues/86604

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chunhtai** [comment]
Hi @goderbauer  this is ready for review

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 6.
View them at https://flutter-gold.skia.org/cl/github/90461

**Comment by chunhtai** [comment]
@Piinks can you help me triage the skia gold? the link contains only an empty list

**Comment by Piinks** [comment]
There is nothing to triage.  The flutter-gold check is green. :)
The skia bot may be a bit mixed up because this is an older PR, but the flutter-github-bot/flutter-dashboard-bot is the source of truth. It would comment if there were image chnages, and the check would not be green. Thanks for double checking!

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 1]
```diff
@@ -3828,21 +3846,37 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin, Res
           canRemoveOrAdd = true;
           break;
         case _RouteLifecycle.pop:
+          entry.handlePop(
+            navigator: this,
+            previousPresent: _getRouteBefore(index, _RouteEntry.willBePresentPredicate)?.route,
+          );
+          if (entry.currentState == _RouteLifecycle.idle) {
+            // The route rejects the pop.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:3854]: rejects -> rejected

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 2]
```diff
@@ -3828,21 +3846,37 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin, Res
...
             poppedRoute = entry.route;
           }
-          entry.handlePop(
-            navigator: this,
-            previousPresent: _getRouteBefore(index, _RouteEntry.willBePresentPredicate)?.route,
+          _observedRouteDeletions.add(
+            _NavigatorPopObservation(entry.route, _getRouteBefore(index, _RouteEntry.willBePresentPredicate)?.route),
           );
+          if (entry.currentState == _RouteLifecycle.dispose) {
+            // The pop finishes synchronously. This can happen if transition
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:3866]: finishes -> finished

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 3]
```diff
@@ -2875,9 +2879,24 @@ class _RouteEntry extends RouteTransitionRecord {
...
-      _NavigatorPopObservation(route, previousPresent),
-    );
+    if (route._popCompleter.isCompleted) {
+      // This is a page-based route popped through the Navigator.pop. The
+      // didPop should have been called. No further action is needed.
+      assert(hasPage);
+      assert(pendingResult == null);
+      return;
+    }
+    if (!route.didPop(pendingResult)) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:2889]: before this if: `assert(!hasPage)` ? We should not be calling didPop on a page-based route right?

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 4]
```diff
@@ -3828,21 +3846,37 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin, Res
           canRemoveOrAdd = true;
           break;
         case _RouteLifecycle.pop:
+          entry.handlePop(
+            navigator: this,
+            previousPresent: _getRouteBefore(index, _RouteEntry.willBePresentPredicate)?.route,
+          );
+          if (entry.currentState == _RouteLifecycle.idle) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:3853]: Maybe instead of inferring this from the state, make handlePop return true/false indicating whether the pop was successful?

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 5]
```diff
@@ -4844,19 +4878,24 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin, Res
       _debugLocked = true;
       return true;
     }());
-    final _RouteEntry entry = _history.lastWhere(_RouteEntry.isPresentPredicate);
-    if (entry.hasPage) {
-      if (widget.onPopPage!(entry.route, result))
+    final int index = _history.lastIndexWhere(_RouteEntry.isPresentPredicate);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:4881]: Why the change from lastWhere to lastIndexWhere? Looks like you need to look up the entry anyways and don't need the index really?

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 6]
```diff
@@ -4844,19 +4878,24 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin, Res
...
+    final _RouteEntry entry = _history[index];
+    if (entry.hasPage && widget.onPopPage!(entry.route, result)) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:4883]: if the entry has a page and widget.onPopPage denied the pop, we shouldn't be executing the else branch and call pop on the entry?

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 7]
```diff
@@ -4844,19 +4878,24 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin, Res
...
-      // wasn't handled internally).
+    if (entry.currentState == _RouteLifecycle.pop)
       _flushHistoryUpdates(rearrangeOverlay: false);
-      assert(entry.route._popCompleter.isCompleted);
-    }
+    assert(() {
+      if (entry.currentState != _RouteLifecycle.idle)
+        assert(entry.route._popCompleter.isCompleted);
+      return true;
+    }());
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:4898]:
```suggestion
    assert(entry.currentState == _RouteLifecycle.idle || entry.route._popCompleter.isCompleted);
```

File: packages/flutter/lib/src/widgets/routes.dart [hunk 8]
```diff
@@ -129,7 +129,8 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
   //
   // This situation arises when dealing with the Cupertino dismiss gesture.
   @override
-  bool get finishedWhenPopped => _controller!.status == AnimationStatus.dismissed;
+  bool get finishedWhenPopped => _controller!.status == AnimationStatus.dismissed && !_popFinalized;
+  bool _popFinalized = false;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/routes.dart:133]: nit: separate by one empty line

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/routes.dart:133]: What is _popFinalized guarding against?

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 3 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/navigator.dart:2889]: the transitiondelegate not longer calls didpop on the page.
it instead will mark the page-based route for pop and will come to here

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 4 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/navigator.dart:3853]: Sounds good

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 6 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/navigator.dart:4883]: nice catch

File: packages/flutter/lib/src/widgets/routes.dart (hunk 8 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/routes.dart:133]: cupertino back swipe gesture will make finishedWhenPopped return true if user swipe all the way to the right but not lifting its finger which causes the page to be disposed twice

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 5 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/navigator.dart:4881]: oops it looks like i forgot to clean this up

**Comment by chunhtai** [comment]
PTAL :)

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 3 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/navigator.dart:2896]: OK, so pages that went through `Navigator.onPopPage` will always go through the first if then? Should/can we assert in line 4891 that the completer is complete to ensure that that path is choosen?

File: packages/flutter/lib/src/widgets/routes.dart (hunk 8 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/routes.dart:134]: Just to double-check: Do we have test cases covering that scenario?

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/routes.dart (hunk 8 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/routes.dart:134]: yes, I figure this out because an existing test failed without this patch
