### PR TITLE
Pass the local engine config through Xcode

### LINKED ISSUE #4186: flutter build ios --local-engine workflow broken
```
~flutter $ git clean -fdx
...
~flutter $ cd examples/hello_world/
~flutter/examples/hello_world $ flutter upgrade
...
~flutter/examples/hello_world $ pub get
...
~flutter/examples/hello_world $ flutter build aot --target-platform=ios --release
Missing files: [~flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot, ~flutter/bin/cache/artifacts/engine/ios-release/dart_vm_entry_points.txt, ~flutter/bin/cache/artifacts/engine/ios-release/snapshot.dart]
```

### PR DESCRIPTION
**Pull request by abarth**
This passes the information through Xcode to the `flutter build aot` call via
the environment so that it picks up the right artifacts.

Fixes #4186

### CODE REVIEW

**Comment by abarth** [comment]
@tvolkert

**Comment by abarth** [comment]
@chinmaygarde

**Comment by abarth** [comment]
@devoncarew

**Comment by tvolkert** [comment]
LGTM

File: packages/flutter_tools/lib/src/base/process.dart [hunk 1]
```diff
@@ -10,6 +10,8 @@ import '../globals.dart';
 
 typedef String StringConverter(String string);
 
+final Map<String, String> childEnvironmentOverrides = new Map<String, String>();
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/base/process.dart]: I'm worried that this won't act as overrides but will entirely replace the env vars. Perhaps init it to a copy of the current env. vars?

Comment (devoncarew) [inline packages/flutter_tools/lib/src/base/process.dart]: Reading this: https://api.dartlang.org/stable/1.16.1/dart-io/Process/run.html, it looks like it defaults to just overridding the specified vars, so looks ok.

Comment (tvolkert) [inline packages/flutter_tools/lib/src/base/process.dart]: docs say that if `incldeParentEnvironment` is true (default), it will include the parent process' environment, giving precedence to the overrides for name conflicts -- so we should be good.
