### PR TITLE
fix ink feature tries to get parent transformations when it is in the…

### LINKED ISSUE #57662: Crash when using KeepAliveClientMixin with Ink as child in TabBarView
After upgrade v1.17.1, following sample cause crash.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: TabBarDemo(),
    );
  }
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(text: 'Page 1'),
                Tab(text: 'Page 2'),
                Tab(text: 'Page 3'),
              ],
            ),
          ),
          body: TabBarView(
            children: [
              Page1(),
              Page2(),
              Page3(),
            ],
          ),
        ),
      ),
    );
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text("Page 1");
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text("Page 2");
  }
}

class Page3 extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _Page3State();
  }
}

class _Page3State extends State<Page3> with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Ink(
      child: Text("Page3"),
    );
  }

  @override
  bool get wantKeepAlive => true;
}
```

## Steps to Reproduce

1. Tap the tab of page 3
2. Then tap the tab of Page1 to crash

- Not reproduced if `wantKeepAlive => false`.
- Not reproduce if it is not an `Ink` Widget.

<details>
  <summary>Logs</summary>

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during paint():
The method '-' was called on null.
Receiver: null
Tried calling: -(0.0)

The relevant error-causing widget was: 
  Scaffold file:///Users/rls01031792/Desktop/keepAliveInTab/lib/main.dart:21:16
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:573:37)
#2      RenderSliverHelpers.applyPaintTransformForBoxChild (package:flutter/src/rendering/sliver.dart:1695:20)
#3      RenderSliverMultiBoxAdaptor.applyPaintTransform (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:586:5)
#4      InkFeature._paint (package:flutter/src/material/material.dart:623:26)
...
The following RenderObject was being processed when the exception was fired: _RenderInkFeatures#607fd
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=414.0, h=896.0)
...  size: Size(414.0, 896.0)
RenderObject: _RenderInkFeatures#607fd
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=414.0, h=896.0)
  size: Size(414.0, 896.0)
...  child: RenderCustomMultiChildLayoutBox#5b907 NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=414.0, h=896.0)
...    size: Size(414.0, 896.0)
...    child 1: _RenderScrollSemantics#e0c14 relayoutBoundary=up1
...      needs compositing
...      parentData: offset=Offset(0.0, 148.0); id=_ScaffoldSlot.body (can use size)
...      constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=748.0)
...      semantics node: SemanticsNode#5
...        Rect.fromLTRB(0.0, 148.0, 414.0, 896.0)
...      semantic boundary
...      size: Size(414.0, 748.0)
...      child: RenderPointerListener#3dbf9 relayoutBoundary=up2
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=748.0)
...        size: Size(414.0, 748.0)
...        behavior: deferToChild
...        listeners: signal
...        child: RenderSemanticsGestureHandler#d2ebf relayoutBoundary=up3
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=748.0)
...          size: Size(414.0, 748.0)
...          gestures: horizontal scroll
...    child 2: RenderConstrainedBox#ba7a3 relayoutBoundary=up1 NEEDS-PAINT
...      needs compositing
...      parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.appBar (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=896.0)
...      size: Size(414.0, 148.0)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=148.0)
...      child: RenderSemanticsAnnotations#0a7ec relayoutBoundary=up2 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, 0.0<=h<=148.0)
...        semantics node: SemanticsNode#8
...          Rect.fromLTRB(0.0, 0.0, 414.0, 148.0)
...          thickness: 4.0
...        semantic boundary
...        size: Size(414.0, 148.0)
...        child: RenderAnnotatedRegion<SystemUiOverlayStyle>#458db relayoutBoundary=up3 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, 0.0<=h<=148.0)
...          size: Size(414.0, 148.0)
...    child 3: RenderStack#7d661 relayoutBoundary=up1
...      parentData: offset=Offset(398.0, 880.0); id=_ScaffoldSlot.floatingActionButton (can use size)
...      constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=896.0)
...      size: Size(0.0, 0.0)
...      alignment: centerRight
...      textDirection: ltr
...      fit: loose
...      overflow: clip
...      child 1: RenderTransform#2d482 relayoutBoundary=up2
...        parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=896.0)
...        size: Size(0.0, 0.0)
...        transform matrix: [0] 0.0,0.0,0.0,0.0
[1] 0.0,0.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: center
...        textDirection: ltr
...        transformHitTests: true
...        child: RenderTransform#fe635 relayoutBoundary=up3
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=896.0)
...          size: Size(0.0, 0.0)
...          transform matrix: [0] 0.7,0.7,0.0,0.0
[1] -0.7,0.7,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...          origin: null
...          alignment: center
...          textDirection: ltr
...          transformHitTests: true
...    child 4: RenderPointerListener#d6424
...      parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.statusBar (can use size)
...      constraints: BoxConstraints(w=414.0, h=44.0)
...      size: Size(414.0, 44.0)
...      behavior: opaque
...      listeners: down
════════════════════════════════════════════════════════════════════════════════════════════════════

```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
… kept alive bucket

## Description

Material widget will actively paint ink features in its subtree. If the ink feature is kept alive under render sliver multibox adapter, it does not have a valid scroll offset and the ink feature will crash because it cannot get a transformation. This pr makes the sliver multibox adapter returns a zero transformation if the child is currently kept alive.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/57662

## Tests

I added the following tests:

See files

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/rendering/sliver.dart [hunk 1]
```diff
@@ -1690,11 +1690,16 @@ abstract class RenderSliverHelpers implements RenderSliver {
   /// [childCrossAxisPosition]for the child in question into a translation that
   /// it then applies to the given matrix.
   ///
-  /// Calling this for a child that is not visible is not valid.
+  /// Calling this for a child that is not visible will return a zero matrix.
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/sliver.dart:1693]: This method doesn't return a value

File: packages/flutter/lib/src/rendering/sliver.dart [hunk 2]
```diff
@@ -1396,13 +1396,13 @@ abstract class RenderSliver extends RenderObject {
...
   ///
-  /// Calling this for a child that is not visible is not valid.
+  /// Calling this for a child that is not visible should return null.
   @protected
   double childMainAxisPosition(covariant RenderObject child) {
     assert(() {
       throw FlutterError('${objectRuntimeType(this, 'RenderSliver')} does not implement childPosition.');
     }());
-    return 0.0;
+    return null;
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/sliver.dart:1405]: This isn't a safe change; most callers assume that the return-value is non-null.

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/sliver.dart:1405]: The other way will be somehow prevent everything below the kept alive child from being paint. Let me scratch my head a bit...

**Comment by chunhtai** [comment]
@HansMuller refined a little bit, same idea but safer. ready for review

File: packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart [hunk 3]
```diff
@@ -584,8 +584,13 @@ abstract class RenderSliverMultiBoxAdaptor extends RenderSliver
   }
 
   @override
-  void applyPaintTransform(RenderObject child, Matrix4 transform) {
-    applyPaintTransformForBoxChild(child as RenderBox, transform);
+  void applyPaintTransform(RenderBox child, Matrix4 transform) {
+    if (_keepAliveBucket.containsKey(indexOf(child))) {
+      // The children that are kept alive can't be drawn.
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart:589]: This looks OK to me although it would help if the comment explained how we end up applying a paint transform to a child that's not laid out or painted.

FWIW, I noticed that RenderFittedBox's applyPaintTransform() also uses transform.setZero() to defeat painting a child.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

**Comment by flutter-github-sync** [comment]
Google testing passed!

File: packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart [hunk 4]
```diff
@@ -586,7 +586,10 @@ abstract class RenderSliverMultiBoxAdaptor extends RenderSliver
   @override
   void applyPaintTransform(RenderBox child, Matrix4 transform) {
     if (_keepAliveBucket.containsKey(indexOf(child))) {
-      // The children that are kept alive can't be drawn.
+      // It is possible that widgets under kept alive children want to paint
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart:589]: It is possible that children in the keepAlive list will want to paint themselves.

File: packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart [hunk 5]
```diff
@@ -586,7 +586,10 @@ abstract class RenderSliverMultiBoxAdaptor extends RenderSliver
...
+      // themselves. For example, the Material widget tries to paint all
+      // InkFeatures under its subtree as long as they are not disposed. In
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart:591]: In such case, we give it => For cases like that, we give the InkFeature children a zero

**Review by HansMuller — APPROVED** [review]

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR
