### PR TITLE
Minimal implementation of FlutterError.toString for release mode

### LINKED ISSUE #54038: FlutterError.toString empty in release mode
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files to trigger a FlutterError (e.g., try Scaffold.of() on context that does not have a Scaffold):

```dart
try {
  Scaffold.of(context);
} on FlutterError catch (e) {
  print(e.toString());
}
```

3. Run in release mode (`flutter run --release`).

**Expected results:**

```
Scaffold.of() called with a context that does not contain a Scaffold.
```

**Actual results:** 

```



```

(yes, 4 empty lines).

## Details

I believe the culprit is here:

https://github.com/flutter/flutter/blob/b336452cdec8bb1d63f31ddadf35f05ae55ef361/packages/flutter/lib/src/foundation/diagnostics.dart#L1113-L1115

While it makes sense that we don't want to spend too much time analyzing the diagnostics tree / be too verbose in release mode, this significantly hinders troubleshooting when an error is reported to the server via generic `toString()`.

Since the 1st diagnostics node is always (?) an `ErrorSummary`, would it make sense to return `ErrorSummary`'s `value` at least?

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/54038

### CODE REVIEW

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 1]
```diff
@@ -890,6 +890,10 @@ class FlutterError extends Error with DiagnosticableTreeMixin implements Asserti
 
   @override
   String toString({DiagnosticLevel minLevel = DiagnosticLevel.info}) {
+    if (kReleaseMode) {
+      final Iterable<_ErrorDiagnostic> errors = diagnostics.whereType<_ErrorDiagnostic>();
```
Comment (dnfield) [inline packages/flutter/lib/src/foundation/assertions.dart:894]: How much does this increase binary size?  That was the primary driver of this change

Comment (dnfield) [reply packages/flutter/lib/src/foundation/assertions.dart:894]: Ideally we want to completely avoid retaining the diagnostics related classes

Comment (jason-simmons) [reply packages/flutter/lib/src/foundation/assertions.dart:894]: This will slightly reduce the binary size.  For the sample app in https://github.com/flutter/flutter/issues/54038 the total size of the segments in libapp.so is:
  * 3611038 with this patch
  * 3613222 without

The diagnostics classes are present in the release build, but their `toString` methods return an empty string.  `FlutterError.toString` was passing the diagnostics nodes to the `TextTreeRenderer`, which just yields a series of empty strings.  With this patch `FlutterError.toString` will return the value of the `ErrorSummary`, and the compiler can eliminate the `TextTreeRenderer` invocation.

Comment (dnfield) [reply packages/flutter/lib/src/foundation/assertions.dart:894]: Ahh ok nice

**Review by dnfield — APPROVED** [review]
LGTM
