### PR TITLE
Fix Color Scheme Defaults in Material 3

### LINKED ISSUE #111520: `ThemeData.light()/ThemeData.dark()` in M3 doesn't generate correct colors for some components.
If the `ThemeData` is set to `ThemeData.light(useMaterial3: true)`, the colors in some components are not correct.

`ThemeData.light(useMaterial3: true)` and `ThemeData.dark(useMaterial3: true)`:
Screen Shot 2022-09-13 at 3 59 00 PMScreen Shot 2022-09-13 at 3 57 49 PM

`ThemeData(colorSchemeSeed: Colors.blue, useMaterial3: true)`:
Screen Shot 2022-09-13 at 3 31 23 PM

### PR DESCRIPTION
**Pull request by QuncCccccc**
Fixes: #111520

This PR is to create a default light color scheme and a default dark color scheme for `ThemeData` when the `ThemeData.useMaterial3` is set to be true.

To get a M3 light color scheme without setting a seed color, use `ThemeData(useMaterial3: true)`, or `ThemeData.light(useMaterial3: true)`.
To get a M3 dark color scheme, use `ThemeData(useMaterial3: true, brightness: Brightness.dark)`, or `ThemeData.dark(useMaterial3: true)`.
Screen Shot 2022-09-29 at 2 39 01 PMScreen Shot 2022-09-29 at 2 39 18 PM

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by QuncCccccc** [comment]
> Golden file changes have been found for this pull request. Click [here to view and triage](https://flutter-gold.skia.org/cl/github/112666) (e.g. because this is an intentional change).
> 
> If you are still iterating on this change and are not ready to resolve the images on the Flutter Gold dashboard, consider marking this PR as a draft pull request above. You will still be able to view image results on the dashboard, commenting will be silenced, and the check will not try to resolve itself until marked ready for review.
> 
> For more guidance, visit [Writing a golden file test for `package:flutter`](https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter).
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.
> 
> _Changes reported for pull request #112666 at sha [a3e0252](https://github.com/flutter/flutter/commit/a3e0252a1784d3ad4e4b63d5d6669def71faa3c8)_

Marked them as positive because the surface color changes a little after we use the default m3 ColorScheme

File: dev/tools/gen_defaults/lib/color_scheme_template.dart [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+  surfaceVariant: Color(${tokens[colorTokensLight['md.sys.color.surface-variant']]}),
+  onSurfaceVariant: Color(${tokens[colorTokensLight['md.sys.color.on-surface-variant']]}),
+  outline: Color(${tokens[colorTokensLight['md.sys.color.outline']]}),
+  outlineVariant: Color(${tokens[colorTokensLight['md.sys.color.outline-variant']]}),
+  shadow: Color(${tokens[colorTokensLight['md.sys.color.shadow']]}),
+  scrim: Color(${tokens[colorTokensLight['md.sys.color.scrim']]}),
+  inverseSurface: Color(${tokens[colorTokensLight['md.sys.color.inverse-surface']]}),
+  onInverseSurface: Color(${tokens[colorTokensLight['md.sys.color.inverse-on-surface']]}),
+  inversePrimary: Color(${tokens[colorTokensLight['md.sys.color.inverse-primary']]}),
+  surfaceTint: Color(${tokens[colorTokensLight['md.sys.color.primary']]}),
```
Comment (darrenaustin) [inline dev/tools/gen_defaults/lib/color_scheme_template.dart:49]: Is this a typo? Shouldn't this be:

```suggestion
  surfaceTint: Color(${tokens[colorTokensLight['md.sys.color.surface-tint']]}),
```

File: dev/tools/gen_defaults/lib/color_scheme_template.dart [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+  surfaceVariant: Color(${tokens[colorTokensDark['md.sys.color.surface-variant']]}),
+  onSurfaceVariant: Color(${tokens[colorTokensDark['md.sys.color.on-surface-variant']]}),
+  outline: Color(${tokens[colorTokensDark['md.sys.color.outline']]}),
+  outlineVariant: Color(${tokens[colorTokensDark['md.sys.color.outline-variant']]}),
+  shadow: Color(${tokens[colorTokensDark['md.sys.color.shadow']]}),
+  scrim: Color(${tokens[colorTokensDark['md.sys.color.scrim']]}),
+  inverseSurface: Color(${tokens[colorTokensDark['md.sys.color.inverse-surface']]}),
+  onInverseSurface: Color(${tokens[colorTokensDark['md.sys.color.inverse-on-surface']]}),
+  inversePrimary: Color(${tokens[colorTokensDark['md.sys.color.inverse-primary']]}),
+  surfaceTint: Color(${tokens[colorTokensDark['md.sys.color.primary']]}),
```
Comment (darrenaustin) [inline dev/tools/gen_defaults/lib/color_scheme_template.dart:83]: Same here?

File: packages/flutter/lib/src/material/theme_data.dart [hunk 3]
```diff
@@ -476,15 +476,18 @@ class ThemeData with Diagnosticable {
...
+      }
+      colorScheme ??= isDark ? _colorSchemeDarkM3 : _colorSchemeLightM3;
 
       // For surfaces that use primary color in light themes and surface color in dark
       final Color primarySurfaceColor = isDark ? colorScheme.surface : colorScheme.primary;
       final Color onPrimarySurfaceColor = isDark ? colorScheme.onSurface : colorScheme.onPrimary;
 
       // Default some of the color settings to values from the color scheme
-      primaryColor = primarySurfaceColor;
+      primaryColor ??= primarySurfaceColor;
```
Comment (darrenaustin) [inline packages/flutter/lib/src/material/theme_data.dart:490]: This is a little tricky here. We are setting up the color scheme as needed, but then trying to patch ThemeData colors to match the scheme as best we can. This got us into a[ bit of trouble](https://github.com/flutter/flutter/issues/107105) as this only happens if the ThemeData constructs the color scheme and not if the color scheme is created and passed to the constructor. I wonder if we should try to address that with this PR, as it will already be changing the default colors for M3.

File: packages/flutter/test/material/banner_theme_test.dart [hunk 4]
```diff
@@ -67,11 +67,11 @@ void main() {
   });
 
   testWidgets('Passing no MaterialBannerThemeData returns defaults', (WidgetTester tester) async {
-    final ThemeData theme = ThemeData();
+    final ThemeData theme = ThemeData(useMaterial3: true);
```
Comment (darrenaustin) [inline packages/flutter/test/material/banner_theme_test.dart:70]: Very odd that this was still being used for some of the test values when it was an M2 theme, but the test was using M3. Nice fix.

File: packages/flutter/test/material/checkbox_test.dart [hunk 5]
```diff
@@ -1587,6 +1587,7 @@ void main() {
 
   testWidgets('Checkbox has default error color when isError is set to true - M3', (WidgetTester tester) async {
     final FocusNode focusNode = FocusNode(debugLabel: 'Checkbox');
+    final ThemeData themeData = ThemeData(useMaterial3: true);
```
Comment (darrenaustin) [inline packages/flutter/test/material/checkbox_test.dart:1590]: Should use this themeData as the theme parameter in the MaterialApp below.

**Review by darrenaustin — CHANGES_REQUESTED** [review]
Nice work @QuncCccccc. Just a couple of small issues to be resolved and I need to think more about whether we want to try and address https://github.com/flutter/flutter/issues/107105 at the same time.

File: dev/tools/gen_defaults/lib/color_scheme_template.dart (hunk 1 above)
Comment (QuncCccccc) [reply dev/tools/gen_defaults/lib/color_scheme_template.dart:49]: Thanks a lot for the suggestions! Fixing others, and for this one, in the token files(color_light and color_dark), the "md.sys.color.surface-tint" is mapped to "primary" and I'm not able to find a "primary" color value in palette.json. So I thought the surfaceTint color here should be the same as the primary color?

Comment (darrenaustin) [reply dev/tools/gen_defaults/lib/color_scheme_template.dart:49]: Oh, I see. I vaguely remember something about this when they introduced the surfaceTint. Not sure why they aren't have it it be a full reference to 'md.sys.color.primary'. That said, your solution looks right. We might want to put a comment in the template as to why this is so that future us will know this was intentional and not an oversight.

File: packages/flutter/lib/src/material/theme_data.dart (hunk 3 above)
Comment (QuncCccccc) [reply packages/flutter/lib/src/material/theme_data.dart:490]: I see. This change is to fix the failing test in G3. Some apps have already set useMaterial3 to be true and used the primaryColor for Image color in the dark mode, which caused some missing images in the apps after I used the default colorScheme. Do you have any suggestions on how to fix this issue? Or should I make some code changes in the apps?

File: dev/tools/gen_defaults/lib/color_scheme_template.dart (hunk 1 above)
Comment (QuncCccccc) [reply dev/tools/gen_defaults/lib/color_scheme_template.dart:49]: Got it! Adding a comment here:)

File: packages/flutter/test/material/checkbox_test.dart (hunk 5 above)
Comment (QuncCccccc) [reply packages/flutter/test/material/checkbox_test.dart:1590]: Fixed! Thanks:)

**Review by darrenaustin — APPROVED** [review]
Actually I think this does address the issue in #107105 at least for the case where they have specified `useMaterial3: true`, it will get the same results whether they create the color scheme with a seed in ThemeData or via `ColorScheme.fromSeed`.  It doesn't fix the case where `useMaterial3` is false, but I think that is ok for now.

LTGM. Thx and sorry for the delay on this. 

We might want to advertise this change in discord to make sure people are aware that the default M3 color schemes will be changed with this PR. Speaking of which, can we add something to the `useMaterial3` flag's docs that describes this new behaviour? Or perhaps something in the constructor for `ThemeData`?

File: packages/flutter/lib/src/material/theme_data.dart [hunk 6]
```diff
@@ -1243,8 +1246,10 @@ class ThemeData with Diagnosticable {
   /// A temporary flag used to opt-in to Material 3 features.
   ///
   /// If true, then widgets that have been migrated to Material 3 will
-  /// use new colors, typography and other features of Material 3.
-  /// If false, they will use the Material 2 look and feel.
+  /// use new colors, typography and other features of Material 3. A new
+  /// purple-based [ColorScheme] will be created and applied to the updated
+  /// widgets, as long as this is set to true. If false, they will use the
+  /// Material 2 look and feel.
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/theme_data.dart:1252]: @darrenaustin Thanks a lot for the suggestions! I just added a comment here. Does this look okay? Wondering if I should add more details.

**Comment by rydmike** [comment]
@darrenaustin and @QuncCccccc I agree that this merge improves the situation in Material 3, and I do like the new M3 default scheme. However, it does not completely fix the difference between `ThemeData`, `ThemeData.from` and `ThemeData(colorSchemeSeed)` even in Material 3.

Yes the `ColorScheme`s are now the same in M3 (hooray), but you still get differences in old `ThemeData.dividerColor` when using `ThemeData` factory versus `ThemeData.from`, that causes some minor differences in style, also in M3. This can be tested and seen in the demo app in this issue https://github.com/flutter/flutter/issues/117755, that also proposes minor changes to fix this in M3 and keep as is in M2.
