### PR TITLE
Make disposing a ScrollPosition with pixels=null legal

### LINKED ISSUE #44269: [TabBar] Setting isScrollable in TabBar to true causes exception when navigating between pages
Steps to reproduce
==============
(this is on the master branch of flutter)

1. Create an app with a start page and a main page with a TabBar that has isScrollable set to true (see this gist: https://gist.github.com/perclasson/912d072cdb9cd17e0fb837d9afe0b309).

2. Go from the start page (by clicking on the button) and you will get an exception on the tab bar page.

Logs 
=====
    
    [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 696 pos 12: 'pixels != null': is not true.
    #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
    #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
    #2      ScrollPosition.dispose (package:flutter/src/widgets/scroll_position.dart:696:12)
    #3      ScrollPositionWithSingleContext.dispose (package:flutter/src/widgets/scroll_position_with_single_context.dart:256:11)
    #4      _rootRun (dart:async/zone.dart:1120:38)
    #5      _CustomZone.run (dart:async/zone.dart:1021:19)
    #6      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    #7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    #8      _rootRun (dart:async/zone.dart:1124:13)
    #9      _CustomZone.run (dart:async/zone.dart:1021:19)
    #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    #11     _CustomZone.bindCallbackGuarded.<anonymous closure<…>

Flutter Doctor
==========
    [✓] Flutter (Channel master, v1.10.1-pre.867, on Mac OS X 10.14.6 18G95, locale en-DE)
        • Flutter version 1.10.1-pre.867 at /Users/perc/development/flutter
        • Framework revision 289b4588f4 (6 hours ago), 2019-11-06 02:51:17 -0500
        • Engine revision 9726b4cb99
        • Dart version 2.7.0

    [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
        • Android SDK at /Users/perc/Library/Android/sdk
        • Android NDK location not configured (optional; useful for native profiling support)
        • Platform android-stable, build-tools 29.0.2
        • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
        • All Android licenses accepted.

    [✓] Xcode - develop for iOS and macOS (Xcode 11.0)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Xcode 11.0, Build version 11A420a
        • CocoaPods version 1.7.5

    [✓] Chrome - develop for the web
        • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

    [✓] Android Studio (version 3.5)
        • Android Studio at /Applications/Android Studio with Blaze.app/Contents
        • Flutter plugin version 40.2.2
        • Dart plugin version 191.8593
        • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

    [✓] Android Studio (version 3.5)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin version 40.2.2
        • Dart plugin version 191.8593
        • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

    [!] VS Code (version 1.39.2)
        • VS Code at /Applications/Visual Studio Code.app/Contents
        ✗ Flutter extension not installed; install from
          https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

    [✓] Connected device (4 available)
        • iPhone 11 Pro Max • 787077DE-9BAA-449A-B911-80F95A3FCD2A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
        • macOS             • macOS                                • darwin-x64     • Mac OS X 10.14.6 18G95
        • Chrome            • chrome                               • web-javascript • Google Chrome 78.0.3904.87
        • Web Server        • web-server                           • web-javascript • Flutter Tools

### PR DESCRIPTION
**Pull request by goderbauer**
## Description

Certain subclass of ScrollPosition (namely _TabBarScrollPosition and _PagePosition) are initialized with initialPixels = null because the initial scroll offset cannot be determined when the ScrollPosition is first constructed. To determine the scroll offset for these subclasses, the viewport dimensions need to be known. Therefore, determining the initial pixels value is deferred until layout when applyViewportDimension is called.

This creates a problem when such a ScrollPosition is disposed without ever doing a layout run: Prior to this change, ScrollPosition.dispose used to assert(pixels != null), which would fire for the aforementioned ScrollPosition if their associated Viewport has never been layed out.

There's a common scenario for this situation: A (scrollable) TabBar or PageView is part of an OverlayEntry that's covered by another opaque OverlayEntry. The covered OverlayEntry is never layed out because its not visible on screen (it is considered to be offstage). When the covering OverlayEntry is removed, the other OverlayEntry is moved in the RenderTree from its offstage to the onstage position. Since the content of the moved OverlayEntry is associated with a global key the containing Scrollable is deactivated at the old position and re-activated at the new position in the RenderTree. This reactivation at a new position in the tree causes didUpdateDependencies to be called on the State of Scrollable, which calls ScrollableState._updatePosition [1]. This method builds a new ScrollPosition based on ScrollConfiguration and ScrollPhysics inherited from the new position in the RenderTree. The old ScrollPosition is disposed (which used to throw since it still has pixels set to null, see above).

This change makes it legal to dispose a ScrollPosition that has pixels still set to null.

Alternatives considered:
 - Just initialize the subclasses with a non-null initial pixels value. This seems less then ideal as this would indicate that the ScrollPosition is valid when in fact it is not until first layout.
 - Defer creation/recreation of ScrollPosition until layout when initial value for pixels is known. This adds a lot of complexity and also breaks the current contract of the Scrollable API, which currently makes the ScrollPosition available before layout.

Side node: For the _PagePosition a work-around for this problem had been implemented in https://github.com/flutter/flutter/pull/31581. This change makes the work-around unnecessary and its therefore removed.

[1] https://github.com/flutter/flutter/blob/35de8d527842f99e30240a7fbf08cd4638ba7a5d/packages/flutter/lib/src/widgets/scrollable.dart#L314-L333

## Related Issues

Fixes https://github.com/flutter/flutter/issues/44269.

## Tests

I added the following tests:

* Can dispose ScrollPosition when pixels is null
* Scrollable in hidden overlay does not crash when unhidden

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by shihaohong** [comment]
Unrelated to the PR, you will probably need to merge with master to pass the failing macos tests. I think there was some [changes](https://github.com/flutter/flutter/pull/44576) to the Cirrus macos images.

**Comment by goderbauer** [comment]
Thanks for the heads-up. Merged with master.

**Comment by shihaohong** [comment]
The rationale looks good to me. I think that we would probably have to remove the [regression test](https://github.com/flutter/flutter/pull/31581/files#diff-bd590aaab05740efbb0c054e46b324e0R981) for the workaround. That test relies on the fact that the `assert(pixels != null)` would throw, but with this update, this would no longer be the case. 

The underlying issue that the tab that was warped over would still be built would still be a problem, but there are already issues to track each situation

**Comment by goderbauer** [comment]
Why do we have to remove the test? It should still pass even with this change?

**Comment by shihaohong** [comment]
It’s more so that the test will never fail now, since it used to check for that assert. However, now that the assert is removed, the test no longer has any purpose

**Comment by goderbauer** [comment]
The test ensures that we never add that assert back, so it still has a purpose :)

After syncing offline we decided to rename it to better reflect its purpose.

File: packages/flutter/test/widgets/scrollable_in_overlay_test.dart [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+        return TabBar(
+          isScrollable: true,
+          controller: controller,
+          tabs: const <Tab>[
+            Tab(text: 'Main'),
+          ],
+        );
+      }
+    );
+    final OverlayEntry entry2 = OverlayEntry(
```
Comment (shihaohong) [inline packages/flutter/test/widgets/scrollable_in_overlay_test.dart]: nit: 
```
    final OverlayEntry entry2 = OverlayEntry(
      maintainState: true,
      opaque: true,
      builder: (BuildContext context) {
        return const Text('number2');
      },
    );
```

**Review by shihaohong — APPROVED** [review]
LGTM!
