### PR TITLE
When resized network image has error, all future unrelated images using the same url will fail, even if the network becomes OK

### LINKED ISSUE #127265: (Will PR) When resized network image has error, all future unrelated images using the same url will fail, even if the network becomes OK
### Some possible approaches

Approach 1: Add `ImageCache.evictWhere((key) => ...)` in addition to `evict(...)`.

Approach 2: Let ImageCache automatically evict failed caches.

Approach 3: Add a cache key in addition to the current key.

---

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

(I will PR for this bug)

Hi thanks for the Flutter framework! When resized network image has error, all future unrelated images using the same url will fail, even if the network becomes OK.

After digging into source code, the cause is as follows: Even if NetworkImage does call `imageCache.evict()`, it is using the *wrong* key when it is wrapped with a ResizedImage. In other words, it is `imageCache.evict(instanceOfNetworkImage)`, while the real key is an instance of the ResizedImage.

The following reproducible sample, though seemingly quite lengthy, is indeed very simple: Copy-and-paste (and slightly simplify) the https://github.com/flutter/flutter/blob/master/packages/flutter/test/painting/image_provider_network_image_test.dart. Then, just modify one line:

```dart
    // final ImageProvider imageProvider = NetworkImage(nonconst('testing.url'));
    final ImageProvider imageProvider = ResizeImage(NetworkImage(nonconst('testing.url')), width: 5, height: 5);
```

i.e. Add a `ResizeImage`. Then the tests fail.

Run test.

### Expected results

no error.

### Actual results

has error.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:async';
import 'dart:io';
import 'dart:ui' show Codec, FrameInfo;

import 'package:flutter/painting.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late _FakeHttpClient httpClient;

  setUp(() {
    httpClient = _FakeHttpClient();
    debugNetworkImageHttpClientProvider = () => httpClient;
  });

  tearDown(() {
    debugNetworkImageHttpClientProvider = null;
    PaintingBinding.instance.imageCache.clear();
    PaintingBinding.instance.imageCache.clearLiveImages();
  });

  test('Expect thrown exception with statusCode - evicts from cache and drains', () async {
    const int errorStatusCode = HttpStatus.notFound;
    const String requestUrl = 'foo-url';

    httpClient.request.response.statusCode = errorStatusCode;

    final Completer<dynamic> caughtError = Completer<dynamic>();

    // final ImageProvider imageProvider = NetworkImage(nonconst(requestUrl));
    final ImageProvider imageProvider = ResizeImage(NetworkImage(nonconst(requestUrl)), width: 5, height: 5);

    expect(imageCache.pendingImageCount, 0);
    expect(imageCache.statusForKey(imageProvider).untracked, true);

    final ImageStream result = imageProvider.resolve(ImageConfiguration.empty);

    expect(imageCache.pendingImageCount, 1);
    expect(imageCache.statusForKey(imageProvider).pending, true);

    result.addListener(
        ImageStreamListener((ImageInfo info, bool syncCall) {}, onError: (dynamic error, StackTrace? stackTrace) {
      caughtError.complete(error);
    }));

    final dynamic err = await caughtError.future;

    expect(imageCache.pendingImageCount, 0);
    expect(imageCache.statusForKey(imageProvider).untracked, true);

    expect(
      err,
      isA<NetworkImageLoadException>()
          .having((NetworkImageLoadException e) => e.statusCode, 'statusCode', errorStatusCode)
          .having((NetworkImageLoadException e) => e.uri, 'uri', Uri.base.resolve(requestUrl)),
    );
    expect(httpClient.request.response.drained, true);
  }, skip: isBrowser); // [intended] Browser implementation does not use HTTP client but an <img> tag.

  test('NetworkImage is evicted from cache on SocketException', () async {
    final _FakeHttpClient mockHttpClient = _FakeHttpClient();
    mockHttpClient.thrownError = const SocketException('test exception');
    debugNetworkImageHttpClientProvider = () => mockHttpClient;

    // final ImageProvider imageProvider = NetworkImage(nonconst('testing.url'));
    final ImageProvider imageProvider = ResizeImage(NetworkImage(nonconst('testing.url')), width: 5, height: 5);

    expect(imageCache.pendingImageCount, 0);
    expect(imageCache.statusForKey(imageProvider).untracked, true);

    final ImageStream result = imageProvider.resolve(ImageConfiguration.empty);

    expect(imageCache.pendingImageCount, 1);
    expect(imageCache.statusForKey(imageProvider).pending, true);
    final Completer<dynamic> caughtError = Completer<dynamic>();
    result.addListener(ImageStreamListener(
      (ImageInfo info, bool syncCall) {},
      onError: (dynamic error, StackTrace? stackTrace) {
        caughtError.complete(error);
      },
    ));

    final dynamic err = await caughtError.future;

    expect(err, isA<SocketException>());

    expect(imageCache.pendingImageCount, 0);
    expect(imageCache.statusForKey(imageProvider).untracked, true);
    expect(imageCache.containsKey(result), isFalse);

    debugNetworkImageHttpClientProvider = null;
  }, skip: isBrowser); // [intended] Browser does not resolve images this way.
}

class _FakeHttpClient extends Fake implements HttpClient {
  final _FakeHttpClientRequest request = _FakeHttpClientRequest();
  Object? thrownError;

  @override
  Future<HttpClientRequest> getUrl(Uri url) async {
    if (thrownError != null) {
      throw thrownError!;
    }
    return request;
  }
}

class _FakeHttpClientRequest extends Fake implements HttpClientRequest {
  final _FakeHttpClientResponse response = _FakeHttpClientResponse();

  @override
  Future<HttpClientResponse> close() async {
    return response;
  }
}

class _FakeHttpClientResponse extends Fake implements HttpClientResponse {
  bool drained = false;

  @override
  int statusCode = HttpStatus.ok;

  @override
  int contentLength = 0;

  @override
  HttpClientResponseCompressionState get compressionState => HttpClientResponseCompressionState.notCompressed;

  late List<List<int>> content;

  @override
  StreamSubscription<List<int>> listen(void Function(List<int> event)? onData,
      {Function? onError, void Function()? onDone, bool? cancelOnError}) {
    return Stream<List<int>>.fromIterable(content).listen(
      onData,
      onDone: onDone,
      onError: onError,
      cancelOnError: cancelOnError,
    );
  }

  @override
  Future<E> drain<E>([E? futureValue]) async {
    drained = true;
    return futureValue ?? futureValue as E; // Mirrors the implementation in Stream.
  }
}

class FakeCodec implements Codec {
  @override
  void dispose() {}

  @override
  int get frameCount => throw UnimplementedError();

  @override
  Future<FrameInfo> getNextFrame() {
    throw UnimplementedError();
  }

  @override
  int get repetitionCount => throw UnimplementedError();
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by fzyzcjy**
Close #127265

The CI fails because of simple analyzer errors. Thus, I would like to hear your opinions first!

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/painting/image_cache.dart [hunk 1]
```diff
@@ -200,6 +200,13 @@ class ImageCache {
     _currentSizeBytes = 0;
   }
 
+  /// All keys inside the current cache.
+  Set<Object> get keys => <Object>{
+    ..._liveImages.keys,
+    ..._pendingImages.keys,
+    ..._cache.keys,
+  };
```
Comment (dnfield) [inline packages/flutter/lib/src/painting/image_cache.dart:208]: I'd rather not expose this API. Partly because it's a getter that does a lot of work,and partly because it exposes lots of objects to external classes that they shouldn't have access to.

Can we instead make the `key` object on `NetworkImage` return the right key?

**Review by dnfield — CHANGES_REQUESTED** [review]
See comment in code.

File: packages/flutter/lib/src/painting/image_cache.dart (hunk 1 above)
Comment (fzyzcjy) [reply packages/flutter/lib/src/painting/image_cache.dart:208]: > Can we instead make the key object on NetworkImage return the right key?

I'm afraid it is not very easy without breaking changes.

Currently, ResizeImage:

```dart
  ImageStreamCompleter load(ResizeImageKey key, DecoderCallback decode) {
...
    imageProvider.load(key._providerCacheKey, decodeResize);
```

and NetworkImage:

```dart
  ImageStreamCompleter load(image_provider.NetworkImage key, image_provider.DecoderCallback decode) {
...
```

Given that, a ResizeImage can be combined with *any* other image providers (e.g. the popular CachedNetworkImage in https://pub.dev/packages/cached_network_image which I use), I guess we should not change the API of `load` function.

**Comment by fzyzcjy** [comment]
> See comment in code.

I have replied ;)

File: packages/flutter/lib/src/painting/image_cache.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/lib/src/painting/image_cache.dart:208]: But this fix won't help other wrapping image providers inthe framework or out in the wild either. We shouldn't have NetworkImage know anything about ResizeImage to fix this bug.

Comment (dnfield) [reply packages/flutter/lib/src/painting/image_cache.dart:208]: For example, perhaps ResizeImage should listen to the completer returned by its wrapped provider and evict itself if the wrapped provider's `ImageStreamCompleter` calls the listener with `onError`.

I'm not sure if we'd need some kind of error-only listening API to make sure we don't dispose the stream when the resize completer stops listening to it.

Comment (fzyzcjy) [reply packages/flutter/lib/src/painting/image_cache.dart:208]: > But this fix won't help other wrapping image providers inthe framework or out in the wild either. We shouldn't have NetworkImage know anything about ResizeImage to fix this bug.

I agree, I also do not like the current fix :(

> For example, perhaps ResizeImage should listen to the completer returned by its wrapped provider and evict itself if the wrapped provider's ImageStreamCompleter calls the listener with onError.

Good idea!

> I'm not sure if we'd need some kind of error-only listening API to make sure we don't dispose the stream when the resize completer stops listening to it.

I will try and see.

Comment (fzyzcjy) [reply packages/flutter/lib/src/painting/image_cache.dart:208]: But here is a problem: When shall we dispose the listener if we call ImageStreamCompleter addListener inside ResizedImage?

I checked ImageProvider's API, and there is no dispose, so we cannot call it there.

In addition, if the image is a infinitely-playing gif, we cannot simply removeListener when seeing the first frame of image, since there are infinitely many frames.

Comment (fzyzcjy) [reply packages/flutter/lib/src/painting/image_cache.dart:208]: Another possibility: Breaking change the `loadImage(key)`, into something like `loadImage(keyToLoadImage, keyThatIsUsedInImageCache)`. Then,

```dart
class ResizedImage {
  loadImage(keyToLoadImage, keyThatIsUsedInImageCache, ...) {
    imageProvider.load(keyToLoadImage: key._providerCacheKey, keyThatIsUsedInImageCache: key, decodeResize);
  }
}

class NetworkIMage {
  loadImage(keyToLoadImage, keyThatIsUsedInImageCache, ...) {
    // Use keyToLoadImage like the old code, except that we use keyThatIsUsedInImageCache to call `ImageCache.evict`
  }
}
```

Comment (dnfield) [reply packages/flutter/lib/src/painting/image_cache.dart:208]: I think if there's been at least one frame we can remove the listener. Evicting a multi-frame image because one frame causes an exception isn't really the main concern here, it's about if the provider itself fails to acquire the data.

Comment (fzyzcjy) [reply packages/flutter/lib/src/painting/image_cache.dart:208]: I see. I will try to implement that and see!

Comment (fzyzcjy) [reply packages/flutter/lib/src/painting/image_cache.dart]: Implemented, and CI is green now

image

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Tagging @goderbauer for secondary review

File: packages/flutter/lib/src/painting/image_stream.dart [hunk 2]
```diff
@@ -519,6 +520,18 @@ abstract class ImageStreamCompleter with Diagnosticable {
     _checkDisposed();
     _hadAtLeastOneListener = true;
     _listeners.add(listener);
+    _synchronouslyCallAddedListener(listener);
+  }
+
+  /// Add a listener for errors. It is similar to [addListener], but see
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/image_stream.dart:526]: Why is the method called "peek" listener, but the description says it is for listening to errors? Should it be called error listener then? Or the doc should describe what a "peek" is.

Overall, this doc is lacking, see https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#writing-prompts-for-good-documentation. Questions that should be answered here: When should I add a peek listener? How is it different from a regular listener (document that here, don't just link to it, it is important information to use this method, if necessary use a macro to avoid repetition)? Can the listener be called synchronously? When does this happen? etc. Also compare this to the existing docs on addListener and see what is useful here: https://master-api.flutter.dev/flutter/painting/ImageStream/addListener.html

File: packages/flutter/lib/src/painting/image_stream.dart [hunk 3]
```diff
@@ -519,6 +520,18 @@ abstract class ImageStreamCompleter with Diagnosticable {
...
+  /// [removePeekListener] for a comparison of the behaviors.
+  void addPeekListener(ImageStreamListener listener) {
+    _checkDisposed();
+    _peekListeners.add(listener);
+    _synchronouslyCallAddedListener(listener);
+  }
+
+  void _synchronouslyCallAddedListener(ImageStreamListener listener) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/image_stream.dart:534]: nit: rename this method to something to imply that the listener is _only_ called when certain conditions are fulfilled, not unconditionally.

File: packages/flutter/lib/src/painting/image_stream.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/lib/src/painting/image_stream.dart:526]: What happens if I add the same listener multiple times?

File: packages/flutter/lib/src/painting/image_stream.dart [hunk 4]
```diff
@@ -587,6 +600,20 @@ abstract class ImageStreamCompleter with Diagnosticable {
     }
   }
 
+  /// Remove a listener for errors.
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/image_stream.dart:603]: Same for this doc.

File: packages/flutter/lib/src/painting/image_stream.dart [hunk 5]
```diff
@@ -587,6 +600,20 @@ abstract class ImageStreamCompleter with Diagnosticable {
...
+  /// This is similar to [removeListener]. However, even if all listeners have
+  /// been removed and all [keepAlive] handles have been disposed, this image
+  /// stream will not be automatically disposed.
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/image_stream.dart:606]: I am not sure what this "however" sentence is supposed to tell me. I expected an explanation of how this is different from removeListener, but removeListener (or anything else on this class) doesn't document anything about automatic disposal of the image stream. I am not even sure what is meant by automatic disposal...

File: packages/flutter/lib/src/painting/image_stream.dart [hunk 6]
```diff
@@ -468,6 +468,7 @@ class ImageStreamCompleterHandle {
 /// configure it with the right [ImageStreamCompleter] when possible.
 abstract class ImageStreamCompleter with Diagnosticable {
   final List<ImageStreamListener> _listeners = <ImageStreamListener>[];
+  final List<ImageStreamListener> _peekListeners = <ImageStreamListener>[];
   ImageInfo? _currentImage;
   FlutterErrorDetails? _currentError;
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/image_stream.dart:474]: Github isn't letting me comment on the line below directly, but there is a `hasListeners` getter. we need to document how these _peekListeners are treated with regards to hasListeners.

File: packages/flutter/test/painting/image_provider_network_image_test.dart [hunk 7]
```diff
@@ -70,6 +70,42 @@ void main() {
...
+    expect(imageCache.statusForKey(imageProvider).untracked, true);
+
+    final ImageStream result = imageProvider.resolve(ImageConfiguration.empty);
+
+    expect(imageCache.pendingImageCount, 1);
+
+    result.addListener(ImageStreamListener((ImageInfo info, bool syncCall) {
+    }, onError: (dynamic error, StackTrace? stackTrace) {
+      caughtError.complete(error);
+    }));
```
Comment (goderbauer) [inline packages/flutter/test/painting/image_provider_network_image_test.dart:92]: nit: indentation

File: packages/flutter/test/painting/image_provider_network_image_test.dart [hunk 8]
```diff
@@ -70,6 +70,42 @@ void main() {
...
+
+    final dynamic err = await caughtError.future;
```
Comment (goderbauer) [inline packages/flutter/test/painting/image_provider_network_image_test.dart:94]: Please don't use dynamic. Use `Object` or `Object?`

**Review by goderbauer — COMMENTED** [review]
With the documented information I do not quite understand what the purpose of a peek listener is. They seem to fire at the exact same moments as the regular listeners. Why add this?

File: packages/flutter/lib/src/painting/image_stream.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/lib/src/painting/image_stream.dart:526]: Ideally, addListener would also link back to this listener (e.g. in a "see also" section) with a short statement about its purpose.

Comment (goderbauer) [inline packages/flutter/lib/src/painting/image_stream.dart:526]: > Add a listener for errors

From the looks of the code this listener doesn't just fire for errors. It also fires for onImage and onChunk events. Is that intentional? Should it only fire on errors? Again, this behavior needs to be properly documented!

Comment (dnfield) [reply packages/flutter/lib/src/painting/image_stream.dart:526]: FWIW, I think it would be fine if this API was modified so that it _only_ fired on errors, and if it dropped all these listeners once the stream succeeded in producing an image.

We'd just hav eto edocument it that way.

Also, sorry @fzyzcjy - I didn't do a very close pass on documentation when I was reviewing :(

Comment (fzyzcjy) [reply packages/flutter/lib/src/painting/image_stream.dart:526]: Thanks for spotting the outdated doc! It is not a listener for errors, but for (at least) onImage and onError. I will add more doc.

File: packages/flutter/test/painting/image_provider_network_image_test.dart (hunk 8 above)
Comment (fzyzcjy) [reply packages/flutter/test/painting/image_provider_network_image_test.dart:94]: I copy-paste-modified it from the existing test https://github.com/fzyzcjy/flutter/blob/ccac069c5bc4392e6c23281f2432b50b3f7e6d59/packages/flutter/test/painting/image_provider_network_image_test.dart#L59. Shall I change that as well?

File: packages/flutter/lib/src/painting/image_stream.dart (hunk 2 above)
Comment (fzyzcjy) [reply packages/flutter/lib/src/painting/image_stream.dart:526]: > FWIW, I think it would be fine if this API was modified so that it only fired on errors, and if it dropped all these listeners once the stream succeeded in producing an image.

That looks like another possible approach! So now I have two different ways in my mind:

1. (What is currently implemented) Let ResizeImage remove the (peek) listener when `onImage`, see https://github.com/fzyzcjy/flutter/blob/ccac069c5bc4392e6c23281f2432b50b3f7e6d59/packages/flutter/lib/src/painting/image_provider.dart#L1450
2. (What @dnfield suggests here) Let ImageStreamCompleter does the job.

Approach 1 has pros that it is more flexible for users of ImageStreamCompleter, and peek listener is symmetric to the normal listener.

Approach 2 has pros that ImageStreamCompleter expose a smaller API.

I am happy to implement either thing. I will just wait for your opinions before continuing!

**Comment by fzyzcjy** [comment]
(See https://github.com/flutter/flutter/pull/127456#discussion_r1210929710 - I will wait which option I should implement)

File: packages/flutter/lib/src/painting/image_stream.dart (hunk 2 above)
Comment (fzyzcjy) [reply packages/flutter/lib/src/painting/image_stream.dart:526]: So... Which one should I implement? :eyes:

Comment (dnfield) [reply packages/flutter/lib/src/painting/image_stream.dart:526]: I'd favor the one that exposes less new API surface. A peek listener might be easier to misuse. Something that listens either for an error or until an image is completed seems easier to think about when to use.

Comment (fzyzcjy) [reply packages/flutter/lib/src/painting/image_stream.dart:526]: I see. I will implement that!

**Comment by fzyzcjy** [comment]
Done (will wait and fix CI, but it works well locally)

File: packages/flutter/lib/src/painting/image_stream.dart [hunk 9]
```diff
@@ -548,6 +557,57 @@ abstract class ImageStreamCompleter with Diagnosticable {
     }
   }
 
+  /// Adds a error listener callback that is called when the first error is reported.
+  /// The callback will be removed automatically after the first successful
```
Comment (dnfield) [inline packages/flutter/lib/src/painting/image_stream.dart:561]: Newline above this.

**Comment by dnfield** [comment]
This looks better to me, docs too with a nit.

File: packages/flutter/lib/src/painting/image_stream.dart (hunk 9 above)
Comment (fzyzcjy) [reply packages/flutter/lib/src/painting/image_stream.dart:561]: done

**Comment by fzyzcjy** [comment]
It has been a week :eyes:

**Comment by fzyzcjy** [comment]
Well, one more week :eyes:

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by fzyzcjy** [comment]
Everything seems green now :)

image
