### PR TITLE
Remove web, fuchsia, and unsupported devices from all

### LINKED ISSUE #35652: 'all' devices should only include project-supported devices
STR:
- Run `flutter run -d all` in a standard (mobile-only) project on master.

It will attempt to run on the desktop host device and fail, because there's not desktop support in the project. I can't think of a scenario where interpreting `all` as meaning all available devices rather than all supported devices would be desirable, so I think we can just always filter by project support.

See #35605 for an example of a case where this caused issues.

CC @jonahwilliams

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

when running with -d all we should not attempt to run with unsupported device types.

Fixes https://github.com/flutter/flutter/issues/35652

### CODE REVIEW

File: packages/flutter_tools/lib/src/device.dart [hunk 1]
```diff
@@ -175,11 +175,27 @@ class DeviceManager {
...
+          && await device.targetPlatform != TargetPlatform.web_javascript)
+            device
+      ];
+    }
+
+    // Remove unsupported devices for project.
+    if (devices.length > 1 && !hasSpecifiedDeviceId) {
+      devices = <Device>[
+        for (Device device in devices)
+          if (device.isSupportedForProject(flutterProject))
```
Comment (blasten) [inline packages/flutter_tools/lib/src/device.dart]: why not check if the device is supported in `device.isSupportedForProject` ?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/device.dart]: I'm not sure what you mean - we do check if the device is supported in `device.isSupportedForProject` ?

Comment (blasten) [reply packages/flutter_tools/lib/src/device.dart]: I was wondering why not using `device.isSupportedForProject` to skip `web` and `fuchsia`.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/device.dart]: We only remove `web` and `fuchsia` when `hasSpecifiedAllDevices` is true. This is because the all devices flag will attempt to share a frontend_server instance, which may fail with these devices since they require differently configured compilers than mobile or desktop.

File: packages/flutter_tools/lib/src/device.dart [hunk 2]
```diff
@@ -175,11 +175,27 @@ class DeviceManager {
...
-    if (devices.length > 1 && !deviceManager.hasSpecifiedAllDevices && !deviceManager.hasSpecifiedDeviceId) {
-      devices = devices
-          .where((Device device) => isDeviceSupportedForProject(device, flutterProject))
-          .toList();
+    // Always remove web and fuchsia devices from `--all`.
+    if (hasSpecifiedAllDevices) {
+      devices = <Device>[
+        for (Device device in devices)
+          if (await device.targetPlatform != TargetPlatform.fuchsia
+          && await device.targetPlatform != TargetPlatform.web_javascript)
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/device.dart]: Nit: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#align-expressions

File: packages/flutter_tools/lib/src/device.dart [hunk 3]
```diff
@@ -175,11 +175,27 @@ class DeviceManager {
...
+    // Remove unsupported devices for project.
+    if (devices.length > 1 && !hasSpecifiedDeviceId) {
+      devices = <Device>[
+        for (Device device in devices)
+          if (device.isSupportedForProject(flutterProject))
+            device
+      ];
+    }
 
+    // If we did not specify all devices, prefer ephemeral devices.
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/device.dart]: Nit: I'm not sure who "we" is here. (go/avoidwe)

File: packages/flutter_tools/lib/src/device.dart (hunk 1 above)
Comment (blasten) [reply packages/flutter_tools/lib/src/device.dart]: Thanks for the clarification. maybe that can be in comment? 🙂

File: packages/flutter_tools/lib/src/device.dart [hunk 4]
```diff
@@ -175,11 +175,27 @@ class DeviceManager {
   Future<List<Device>> findTargetDevices(FlutterProject flutterProject) async {
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/device.dart]: The method comment needs updating; the part about only filtering if --all is not specified is out of date.

**Review by stuartmorgan-g — APPROVED** [review]
LGTM with nits.

That said, at a slightly larger scope I think the code flow related to this method would benefit a lot from refactoring. The comment for the method doesn't really explain what it's supposed to do, and I'm not sure I could clearly articulate to someone what its purpose is. The fact that it conflates multi-device and single devices cases, as well as explicit specification and heuristic choice, makes it very confusing to me.

**Comment by jonahwilliams** [comment]
I've rewritten the doc and inline comments. The conflation between single device and all device cases is an unfortunate consequence of how `-d all` was originally implemented. I have some rough ideas on how to refactor this, but not anytime soon.
