### PR TITLE
Fix DragTarget not being rebuilt when a rejected Draggable enters #38786

### LINKED ISSUE #31659: When the DragTarget`s builder rejectedData is not null?Mine is always [].
```
DragTarget(
                builder: (context, List<int> candidateData,
                    List<dynamic> rejectedData) {
                  print("----candidateData" + candidateData.toString());
                  print("----rejectedData" + rejectedData.toString());
                  return Center(
                    child: Text(candidateData.toString() +
                        "----" +
                        rejectedData.toString()),
                  );
                },

```

### LINKED ISSUE #35662: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
I'm using last version of flutter and dart.
When I installed my app from play store and when I attached my device(Samsung S8+ with android 9) for debugging and it showed me this error:
`Failure [INSTALL_FAILED_VERSION_DOWNGRADE]`
After some searches I did theses staffs:
> - uninstall from all user the currently installed copy
> - adb uninstall "Package name"
> - downgrade android:version from manifest.xml

and they didn't work!
I realized my app version from app manager and then I edited version:
`version: 0.1.0+62` -> `version: 3.11.0+66` 
from pubspec.yaml, it showed me this:
`signatures do not match previously installed version; ignoring!`

What should I do?

### LINKED ISSUE #38786: DragTarget doesn't rebuild when a rejected Draggable enters
When a Draggable enters a DragTarget which is then rejected by its onWillAccept the DragTarget will not rebuild itself. 

This means that the builder function supplied to the DragTarget by the user will not be called with anything in the rejectedData list. 

This list is supposed to contain: "the list of drag data that is hovering over this DragTarget and that will not be accepted by the DragTarget".

```
DragTarget<int>(
  // Reject all data given to this target
  onWillAccept: (int data) => false,
  builder: (BuildContext context, List<int> data, List<dynamic> rejects) {
    // Rejects should contain anything dragged over this target
    // but rejected by onWillAccept.
    // Due to the bug rejects will always be empty as the
    // DragTarget will not rebuild if a rejected Draggable enters the target.
    // Only accepted Draggables will cause a rebuild.
    if(rejects.isNotEmpty) {
      return Text("Reject data is $rejects");
    } else {
      return const Text('Target');
    }
  }
}
```

This makes it harder to say build a DragTarget which shows an error when an invalid Draggable is dragged on top of it. 

See https://gist.github.com/nigel-gott/68f60a53785e02a71499de5cfe5db0bb for a minimal 
application showing the bug.

## The cause
_DragTargetState doesn't wrap its update the rejectedData in a setState call. I have raised the following PR to fix this #38789 . 

```
class _DragTargetState<T> extends State<DragTarget<T>> {
  final List<_DragAvatar<T>> _candidateAvatars = <_DragAvatar<T>>[];
  final List<_DragAvatar<dynamic>> _rejectedAvatars = <_DragAvatar<dynamic>>[];

  bool didEnter(_DragAvatar<dynamic> avatar) {
    assert(!_candidateAvatars.contains(avatar));
    assert(!_rejectedAvatars.contains(avatar));
    if (avatar.data is T && (widget.onWillAccept == null || widget.onWillAccept(avatar.data))) {
      setState(() {
        _candidateAvatars.add(avatar);
      });
      return true;
    }
    // This state mutation needs to occur inside a setState call to trigger a rebuild showing the rejected data!
      _rejectedAvatars.add(avatar);
    return false;
  }
```

## Related Issues
* https://github.com/flutter/flutter/issues/31659 is a result of this bug. 
* If rejectedData was populated it could be used in some situations instead of the onReject callback requested in https://github.com/flutter/flutter/issues/37053. 

## Steps to Reproduce

1. Drag a Draggable over a DragTarget which rejects the Draggable's data by returning false in onWillAccept.
2. The DragTargets builder method will not be called with the rejected data in its rejectedData argument. 

## Flutter Doctor etc
```

flutter analyze
Analyzing drag_target_bug_example...                                    
No issues found! (ran in 1.4s)


[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/nigel/bin/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/nigel/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/77/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /snap/android-studio/77/android-studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /snap/intellij-idea-community/163
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6459

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /snap/intellij-idea-community/152
    • Flutter plugin version 36.2.1
    • Dart plugin version 191.7830

[✓] Connected device (1 available)
    • Pixel 2 XL • 802KPUU1525790 • android-arm64 • Android 9 (API 28)

• No issues found!

```

### PR DESCRIPTION
**Pull request by nigel-gott**
## Description

Currently, DragTarget doesn't rebuild if a rejected Draggable enters. This is because in _DragTargetState.didEnter it updates its list of rejected data _rejectedAvatars outside of a setState call. This results in the user supplied builder function not being called with any rejected data, so they can't rebuild accordingly. This PR wraps the rejectedAvatars state mutation in a setState call so this bug is fixed. Issue #38786 contains further details and an example showing the bug. 

## Related Issues

* Fixes #31659
* Fixes #38786 

## Tests

I added the following tests:
* 'Drag and drop - builder called with reject data if dragged over non-accepting target' 

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 1]
```diff
@@ -524,9 +524,12 @@ class _DragTargetState<T> extends State<DragTarget<T>> {
         _candidateAvatars.add(avatar);
       });
       return true;
+    } else {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/drag_target.dart]: Should we also then remove the rejected avatar in `didDrop` (l#547)? It looks like `didLeave` (l#535) removes the avatar from rejected and candidates, but only candidates are removed in `didDrop`. 
This might result in an assert being thrown if you drag and drop a rejected avatar once, and then again since the assert above (l#521) checks that it is not already in the list.

Comment (Piinks) [reply packages/flutter/lib/src/widgets/drag_target.dart]: If that is the case I would add another test that drags and drops rejected targets twice, as well as drags and leaves for good measure, to check that doesn't trigger the assertion.

**Review by Piinks — COMMENTED** [review]
Hi @nigel-gott! 
Welcome  🎉  and thank you for the contribution!

File: packages/flutter/lib/src/widgets/drag_target.dart (hunk 1 above)
Comment (nigel-gott) [reply packages/flutter/lib/src/widgets/drag_target.dart]: Thanks for the review! 

So didDrop is never called with an avatar in _rejectedAvatars, only ones in _acceptedAvatars, hence this assertion will never fail. This is because didDrop is only called on _DragAvatar._activeTarget (#690) and _activeTarget is guaranteed to be a target which is accepting the avatar as it is only ever a target which returns true on _DragTargetState.didEnter (#661, #666), which only returns true if it is accepted (#526). Phew. 

Given this long chain of reasoning closely tied to maintaining internal state in multiple widgets I agree it's prudent to introduce some extra tests.

I've updated my original test to be the two you suggested:
* Check that DragTarget rebuilds correctly when the same rejected Draggable is dropped two times in a row.
* Check that DragTarget rebuilds correctly when a rejected Draggable leaves then enters.

Comment (Piinks) [reply packages/flutter/lib/src/widgets/drag_target.dart]: Ah! Thank you for being so thorough! 
I think I mixed up a re-factor I've been looking into to address #37053 that would involve `didDrop`. 😜 
Thank you for adding the additional test as well. This is a great fix - which I see you mentioned (in #38786) may eradicate the need for exposing another callback in #37053. I'd be interested to see feedback there after this lands.

**Review by Piinks — APPROVED** [review]
LGTM

Cheers!  🎉
