### PR TITLE
Fix `StretchingOverscrollIndicator` not handling directional changes correctly

### LINKED ISSUE #88741: Stretching overscroll keeps stretching when change overscroll direction
## Steps to Reproduce

Run the code sample and drag the list up and down so the overscroll direction constantly changes

**Expected results:** list stretches in one direction, then in the opposite. I didn't actually check how it's in Android 12 since I didn't set up the distro yet, but I think this is how it would look like.

**Actual results:** list jumps when drag direction changes, and constantly keeps stretching

<details>
  <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        androidOverscrollIndicator: AndroidOverscrollIndicator.stretch,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SafeArea(
          child: Center(
            child: MyWidget(),
          ),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (context, index) => Container(
        height: 50,
        color: Colors.amber[(index % 9 + 1) * 100],
        child: const Center(child: Text('Entry A')),
      ),
      itemCount: 10,
      padding: const EdgeInsets.all(8),
    );
  }
}
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.5.0-7.0.pre.83, on Microsoft Windows [Version 10.0.19041.1110], locale ru-RU)
    • Flutter version 2.5.0-7.0.pre.83 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision 06be7e5392 (4 hours ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (4 available)
    • Redmi Note 5 (mobile)   • 40c9f14       • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1110]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.
```

</details>

https://user-images.githubusercontent.com/39104740/130516265-83a212b9-1712-4c7b-8673-c852c33a2ff5.mp4

### LINKED ISSUE #116522: `StretchingOverscrollIndicator` with `AlwaysScrollableScrollPhysics`  jumps when changing direction
I observed some weird behaviour with the `StretchingOverscrollIndicator`, which doesn't look right to me. When changing the scroll direction while scrolling, there is a sudden jump - most likely caused by the transform origin of the indicator changing from `topCenter` to `bottomCenter`.

I observed this problem only when the content of the Scrollable doesn't fill the Scrollable completely. This is very noticeable when using `ListView.builder`, or when explicitly setting `AlwaysScrollableScrollPhysics` on a `SingleChildScrollView`.

## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Trigger the `StrechingOverscrollIndicator` by pulling your finger down a reasonable distance
3. Move finger slightly up

**Expected results:** I expect the overscroll indicator not to jump suddenly. I would have assumed, when moving the finger up again after moving the finger down, it should just do the same but in reverse.

**Actual results:** There is a sudden jump, which makes the first item in the list display partly outside the bounds of the Scrollable.

https://user-images.githubusercontent.com/1659532/205665058-e602a2be-66d1-4e61-96b6-fecc8a86b387.mov

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        // Need to set `useMaterial3` to true so we use the stretching overscroll
        // indicator.
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text("StrechingOverscrollIndicator"),
        ),
        body: ListView.builder(
          physics: const AlwaysScrollableScrollPhysics(),
          itemBuilder: (context, index) {
            return Container(
              height: 50,
              color: index % 2 == 0
                  ? const Color(0xFFEEEEEE)
                  : const Color(0xFFCCCCCC),
              child: Text("Index $index"),
            );
          },
          itemCount: 7,
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Analyzing strech_overscroll_always_scrollable_physics...                
No issues found! (ran in 1.0s)
```

```
[✓] Flutter (Channel master, 3.7.0-2.0.pre.40, on macOS 12.2 21D49 darwin-arm64, locale en-DE)
    • Flutter version 3.7.0-2.0.pre.40 on channel master at /Users/kuss/Documents/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4ec4401338 (5 hours ago), 2022-12-05 05:29:27 -0500
    • Engine revision 4de358e2f0
    • Dart version 2.19.0 (build 2.19.0-444.0.dev)
    • DevTools version 2.20.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/kuss/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone 13 (mobile)          • 4F1B2857-3967-4F27-B976-B99A7A41AB96 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.2 21D49 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### LINKED ISSUE #118145: Unexpected behavior CustomScrollView with a short list, list jumps up and down with material 3
Hi,

I found a unexpected behavior with CustomScrollView and material 3 when the list is very short (shorter than the viewport). If the view is overscrolled, the list starts to stretch as expected with M3. However if the direction is changed the opposite way even slightly, the view jumps back. This feels strange and unnatural, especially in combination with NestedScrollView. 

**Steps to Reproduce**
1. Scroll down and up  (fling up and down), do not end the scroll.
2. The list starts to jump up and down

**Expected results:** 
I expect the same behavior with a list longer than the viewport. If the direction of the overscroll (short list) is the opposite of the initial overscroll then the stretch should be gradually disappear and not jump.

**Actual results:** 
The list starts to jump up and down.

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(const AppBarApp());

class AppBarApp extends StatelessWidget {
  const AppBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const AppBarExample(),
    );
  }
}

class AppBarExample extends StatelessWidget {
  const AppBarExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SafeArea(
            top: false,
            bottom: false,
            child: CustomScrollView(
              slivers: <Widget>[
                SliverPadding(
                  padding: const EdgeInsets.all(8.0),
                  sliver: SliverFixedExtentList(
                    itemExtent: 48.0,
                    delegate: SliverChildBuilderDelegate(
                      (BuildContext context, int index) {
                        return ListTile(
                          title: Text('Item $index'),
                        );
                      },
                      childCount: 2,
                    ),
                  ),
                ),
              ],
            )));
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on openSUSE Tumbleweed 6.1.2-1-default, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

[example jump up and down 2.webm](https://user-images.githubusercontent.com/32017307/211412456-e4c0d7be-7a89-4e48-b9ae-4bdd681aa847.webm)

### PR DESCRIPTION
**Pull request by jankuss**
This PR fixes #116522
Fixes https://github.com/flutter/flutter/issues/88741
Fixes https://github.com/flutter/flutter/issues/118145

When using a `StrechingOverscrollIndicator` in combination with `AlwaysScrollableScrollPhysics`, in the case the content doesn't fill the viewport, there is some kind of jump when changing the scroll direction while overscrolling.

This video shows this unwanted behaviour:

https://user-images.githubusercontent.com/1659532/205745277-52c70354-153e-4569-849f-a9e5254d4cda.mov

This PR makes changes on how `distanceForPull` is calculated, as well as how the alignment for the transform is determined.

After this change is made, the `StrechingOverscrollIndicator` will behave like this:

https://user-images.githubusercontent.com/1659532/205746098-56cd77b7-c89d-44c8-95a8-64d7540af098.mov

This behaves much smoother, and is much more in line with how it works in native android apps on Android 12.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/overscroll_indicator.dart [hunk 1]
```diff
@@ -612,6 +612,11 @@ class _GlowingOverscrollIndicatorPainter extends CustomPainter {
   }
 }
 
+enum _StretchDirection {
+  down,
+  up
```
Comment (jankuss) [inline packages/flutter/lib/src/widgets/overscroll_indicator.dart:617]: I'm not entirely sure about the naming here (`up` and `down`), since this implies verticality, even though it applies to vertical **and** horizontal scrolling. Any suggestions?

Comment (Piinks) [reply packages/flutter/lib/src/widgets/overscroll_indicator.dart:617]: Typically we use terms like leading and trailing so it can describe both vertical and horizontal cases.

**Review by Piinks — COMMENTED** [review]
Thanks for the PR, and for your patience! Can you update the up/down to use leading and trailing terms?

File: AUTHORS [hunk 2]
```diff
@@ -100,4 +100,5 @@ Jingyi Chen <jingyichen@link.cuhk.edu.cn>
 Junhua Lin <1075209054@qq.com>
 Tomasz Gucio <tgucio@gmail.com>
 Jason C.H <ctrysbita@outlook.com>
-Hubert Jóźwiak <hjozwiakdx@gmail.com>
\ No newline at end of file
+Hubert Jóźwiak <hjozwiakdx@gmail.com>
+Jan Kuß <jan@kuss.dev>
```
Comment (Piinks) [inline AUTHORS:104]: Nit: There should be a newline here at the end of the file.

File: packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart [hunk 3]
```diff
@@ -770,4 +773,74 @@ void main() {
     await pointer4.up();
     await tester.pumpAndSettle();
   });
+
+  testWidgets('Stretch overscroll vertically, change direction mid scroll', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart:777]: Can you add a test for horizontal as well?

**Comment by Piinks** [comment]
It looks like this also fixes https://github.com/flutter/flutter/issues/88741 :)

**Comment by jankuss** [comment]
Thanks for the review! I added a test for horizontal scrolling, feel free to check again.

**Review by Piinks — APPROVED** [review]
LGTM, thank you! This will need a second review, I will see about finding someone. :)

**Review by Piinks — CHANGES_REQUESTED** [review]
Marking for changes here to just hold this for a sec while we investigate https://github.com/flutter/flutter/issues/118145. This PR may already resolve that issue, I'd like to check.

**Comment by JoanSchi** [comment]
@jankuss  Issue #104798  also happens only with material 3 overscroll. Is this issue also solved with this fix. (I tried to test it, but I was not able to get it right.)

**Comment by elliotkhd** [comment]
It seems there comes up another issue with this commit, when swiping up a list and let the list auto scroll to the end, the stretch direction goes oppesite.

https://user-images.githubusercontent.com/26217279/215256186-f3a833aa-fbfe-437d-81b1-5015cae561ce.mp4

**Comment by jankuss** [comment]
> It seems there comes up another issue with this commit, when swiping up a list and let the list auto scroll to the end, the stretch direction goes oppesite.
> 
>  screen-20230128.mp4

Thanks for the info! I will check this out

**Comment by elliotkhd** [comment]
> > It seems there comes up another issue with this commit, when swiping up a list and let the list auto scroll to the end, the stretch direction goes oppesite.
> > screen-20230128.mp4
> 
> @elliotkhd I believe I found the problem - could you check if the issue is fixed for you in my latest commit?
> 
> In the meantime, I'll try writing tests to cover this.

It works for me now!

**Review by Piinks — COMMENTED** [review]
Hey @jankuss thank you for your patience, I was out of town for Flutter Forward. The failing checks here appear unrelated to your change.
Can you update your branch with the latest from the master branch? That should resolve the failures.

**Comment by jankuss** [comment]
@Piinks I rebased the branch and added two more tests covering the bug @elliotkhd found. Feel free to review again

**Review by Piinks — APPROVED** [review]
Flutter_LGTM 
Thank you for contributing! I will need to find another reviewer for a second approval. Seeking one out now.

File: packages/flutter/lib/src/widgets/overscroll_indicator.dart [hunk 4]
```diff
@@ -784,7 +802,7 @@ class _StretchingOverscrollIndicatorState extends State<StretchingOverscrollIndi
           }
 
           final AlignmentGeometry alignment = _getAlignmentForAxisDirection(
-            _lastOverscrollNotification?.overscroll ?? 0.0
+            _stretchDirection
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/overscroll_indicator.dart:805]: Nit: There should be a trailing comma here.

File: packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart [hunk 5]
```diff
@@ -387,7 +391,7 @@ void main() {
     expect(box3.localToGlobal(Offset.zero).dx, 500.0);
   });
 
-  testWidgets('Stretch overscroll horizontally RTl', (WidgetTester tester) async {
+  testWidgets('Stretch overscroll horizontally RTL', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart:394]: 😎

File: packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart [hunk 6]
```diff
@@ -770,4 +774,238 @@ void main() {
...
+    final RenderBox box2 = tester.renderObject(find.byKey(box2Key));
+    final RenderBox box3 = tester.renderObject(find.byKey(box3Key));
+
+    expect(controller.offset, 0.0);
+    expect(box1.localToGlobal(Offset.zero), Offset.zero);
+    expect(box2.localToGlobal(Offset.zero), const Offset(0.0, 100.0));
+    expect(box3.localToGlobal(Offset.zero), const Offset(0.0, 200.0));
+
+    final TestGesture gesture = await tester.startGesture(tester.getCenter(find.byType(CustomScrollView)));
+    // Overscroll the start
```
Comment (justinmc) [inline packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart:810]: Nit: missing period at the end of the sentence here and in a few other comments below.

File: packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart [hunk 7]
```diff
@@ -770,4 +774,238 @@ void main() {
...
+    // The boxes should now be at different locations because of the scaling.
+    expect(box1.localToGlobal(Offset.zero), Offset.zero);
+    expect(box2.localToGlobal(Offset.zero).dy, greaterThan(103.0));
+    expect(box3.localToGlobal(Offset.zero).dy, greaterThan(206.0));
+
+    // Move the pointer up a miniscule amount to trigger a directional change.
+    await gesture.moveBy(const Offset(0.0, -20.0));
+    await tester.pumpAndSettle();
+
+
```
Comment (justinmc) [inline packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart:823]: Remove the extra newline here.

File: packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart [hunk 8]
```diff
@@ -770,4 +774,238 @@ void main() {
...
+    // The boxes should now be at different locations because of the scaling.
+    expect(box1.localToGlobal(Offset.zero), Offset.zero);
+    expect(box2.localToGlobal(Offset.zero).dx, greaterThan(102.0));
+    expect(box3.localToGlobal(Offset.zero).dx, greaterThan(205.0));
+
+    // Move the pointer up a miniscule amount to trigger a directional change.
+    await gesture.moveBy(const Offset(-20.0, 0.0));
+    await tester.pumpAndSettle();
+
+
```
Comment (justinmc) [inline packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart:894]: Another newline to remove.

File: packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart [hunk 9]
```diff
@@ -770,4 +774,238 @@ void main() {
...
+    await gesture.up();
+    await tester.pumpAndSettle();
+
+    // Now the boxes should be back to their original locations.
+    expect(box1.localToGlobal(Offset.zero), Offset.zero);
+    expect(box2.localToGlobal(Offset.zero), const Offset(100.0, 0.0));
+    expect(box3.localToGlobal(Offset.zero), const Offset(200.0, 0.0));
+  });
+
+
```
Comment (justinmc) [inline packages/flutter/test/widgets/overscroll_stretch_indicator_test.dart:919]: One more newline to remove.

**Review by justinmc — APPROVED** [review]
LGTM with nits 👍 

Thanks for improving this!

**Comment by elliotkhd** [comment]
Hello again @jankuss , I might have found another bug, when the list is a little bit longer than its parent widget, the stretch effect gets weird when change swipe direction.

https://user-images.githubusercontent.com/26217279/216510534-a9580831-5f16-437e-bf64-8a297fdbac5b.mp4

**Review by Piinks — CHANGES_REQUESTED** [review]
@elliotkhd is this a bug that exists currently, or only with this PR? Can you also provide sample code? Thanks for testing and flagging this.

**Comment by jankuss** [comment]
It appears the simple fix I attempted doesn't quite work in the scenario @elliotkhd provided.

I'm guessing the problem occurs because the recede animation is playing, while we change the overscroll and thus the stretch direction. Because we just naively change the stretch direction once the overscroll changes from positive to negative and vice versa, the recede animation is possibly still playing, causing this visual abnormality.

I'm able to reproduce this issue with the following sample code:
<details>
  <summary>Sample Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        // Need to set `useMaterial3` to true so we use the stretching overscroll
        // indicator.
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text("Stretch visual bug"),
        ),
        body: SizedBox(
          height: 545,
          child: Center(
            child: ListView.builder(
              itemBuilder: (context, index) {
                return Container(
                  height: 50,
                  color: index % 2 == 0
                      ? const Color(0xFFEEEEEE)
                      : const Color(0xFF000000),
                );
              },
              itemCount: 11,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>


I will check how this case is handled in native android apps, and will adjust this PR accordingly.
I have the feeling it will involve a minor refactoring, moving our `_stretchDirection` state into our `_StretchController`, and manage it there. Right now the `_stretchDirection` is determined by looking at the total overscroll amount, but it doesn't take into account the state within the `_StretchController`.

@Piinks does this sound right to you?

**Review by Piinks — COMMENTED** [review]
Hey @jankuss thanks for your detailed investigation. It looks like we did not have the test coverage in place for the case @elliotkhd pointed out. I agree with your assessment and approach. The stretch should recede before applying to the other direction, maybe resetting it to 0 below is what subverted that receding animation? Thanks again for your attention to this.

**Comment by jankuss** [comment]
I was able to investigate how native android handles it. For Flutter, the implementation of the stretch effect differs slighty, which is why we ran into this problem.

For Android, when the overscroll is started, it remains "captured". Only after reaching the initial start of the overscroll, the actual scroll is performed. The recede is only played when the user actually stops scrolling when in an overscrolled state.

https://user-images.githubusercontent.com/1659532/217398172-047d714d-0c28-48a8-a5e0-6200b8033427.mov

In Flutter, when the overscroll is started, it instantly gets stopped once moved in the opposite direction (a `ScrollUpdateNotification` is received). This in turn causes `scrollEnd` to get called, which plays our recede animation, while the user is actually still scrolling.

https://user-images.githubusercontent.com/1659532/217397995-efcca446-76f1-4728-bc08-6ccda37a7775.mov

Ideally, this "capturing" of the overscroll would also happen in Flutter. Since this is a more fundamental issue in the current implementation and scrolling in general, I believe it makes sense to leave it out of this ticket.

@Piinks @elliotkhd In my latest commit, I tried to mitigate the issue. When we are in the receding state and the direction changes, we prevent any changes to the `stretchDirection` and the stretch animation. Please test with the sample code (https://github.com/flutter/flutter/pull/116548#issuecomment-1416550067) if this solution is satisfactory for now. I'm open for any other suggestions how we could solve this.

If we've decided on a solution, I will write an additional test to cover this.

**Comment by Piinks** [comment]
Thank you for the update! I have not been able to check it out yet locally, but will do so tomorrow. This is at the front of my list. :+1:

**Review by Piinks — COMMENTED** [review]
Thanks for embracing the yak shave! This is great. I have tried it out on a combination of devices, with differing list lengths and scroll physics. Thanks very much! Can you add the final test case you mentioned? Then we can finally land this. 🎉

**Review by Piinks — APPROVED** [review]
Excellent, thank you! LGTM - again. :)

**Comment by Piinks** [comment]
As far as the test failures, I have seen this happen before. Rebasing with the master branch (not merging) should resolve the issue.

**Comment by nbnD** [comment]
Still issue on **_`SingleChildScrollView`_** only on android
