### PR TITLE
Fix drawer Semantics for mismatched platforms

### LINKED ISSUE #177005: [a11y] Use defaultTargetPlatform instead of platform from the theme for Drawer's semantics
### Use case

https://github.com/flutter/flutter/blob/1280fad73f1979ecb5ce88f1206a1370349dd1dc/packages/flutter/lib/src/material/drawer.dart#L253

https://github.com/flutter/flutter/blob/1280fad73f1979ecb5ce88f1206a1370349dd1dc/packages/flutter/lib/src/material/drawer.dart#L688

In case users explicitly configure a specific platform (let's give it as Android for eg), but run on another platform (let's give it as iOS for eg), accessibility might work incorrectly.

### Proposal

Use defaultTargetPlatform instead of using platform from the theme.

### PR DESCRIPTION
**Pull request by huycozy**
- Address a partial issue within https://github.com/flutter/flutter/issues/176566
- Fix  https://github.com/flutter/flutter/issues/177005
- In this PR:
    - proposes using `defaultTargetPlatform` instead of platform from theme for Semantics label in Drawer widget  
    -  add some new tests

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/drawer_test.dart [hunk 1]
```diff
@@ -969,6 +969,152 @@ void main() {
...
+        final SemanticsTester semantics = SemanticsTester(tester);
+
+        await pumpDrawer(tester: tester, themePlatform: themePlatform);
+
+        expect(semantics, expected);
+
+        semantics.dispose();
+      }
+
+      testWidgets(
```
Comment (chunhtai) [inline packages/flutter/test/material/drawer_test.dart]: you can combine this and the next by update the expect to be defaultTargetPlatform adaptive

**Review by chunhtai — COMMENTED** [review]
LGTM

File: packages/flutter/test/material/drawer_test.dart (hunk 1 above)
Comment (huycozy) [reply packages/flutter/test/material/drawer_test.dart]: done! I combined label and barrier tests into one. Let me know if it's good enough now. Thanks!

**Review by chunhtai — APPROVED** [review]
LGTM
