### PR TITLE
Fix physics with NestedScrollView

### LINKED ISSUE #11322: NestedScrollView should allow overriding the physics of the outer scroll view
Right now if you pass a custom `ScrollPhysics` to a `NestedScrollView` it'll override some of the interesting methods with a `ClampingScrollPhysics` implementation. I think the `physics` parameter of `NestedScrollView` should override the default (`ClampingScrollPhysics`), so instead of 

    return new CustomScrollView(
      // ...
      physics: new ClampingScrollPhysics(parent: widget.physics),
    );

it would be

    return new CustomScrollView(
      // ...
      physics: widget.physics ?? new ClampingScrollPhysics(),
    );

/cc @Hixie @HansMuller

### PR DESCRIPTION
**Pull request by collinjackson**
Fixes #11322 

Makes custom physics work with @HansMuller's new `NestedScrollView` demo.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 1]
```diff
@@ -135,7 +135,7 @@ class _NestedScrollViewState extends State<NestedScrollView> {
     return new CustomScrollView(
       scrollDirection: widget.scrollDirection,
       reverse: widget.reverse,
-      physics: new ClampingScrollPhysics(parent: widget.physics),
+      physics: widget.physics ?? new ClampingScrollPhysics(),
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: We need the clamping physics to make nested scroll view work. If you turn off the clamping, it'll go crazy.

Comment (collinjackson) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: What if I want to provide my own class that extends `ClampingScrollPhysics`? Should we require that the `physics` argument be a `ClampingScrollPhysics`?

Comment (collinjackson) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: Specificially, this is the class I'd like to pass: https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/animation/home.dart#L371

Comment (Hixie) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: Yeah we could just require that the physics extend ClampingScrollPhysics for this subclass.

@abarth may have opinions, the crazy physics inheritance magic is his baby. ;-)

**Comment by collinjackson** [comment]
I've updated `NestedScrollView` to take a `ClampingScrollPhysics`.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 2]
```diff
@@ -70,13 +70,14 @@ class NestedScrollView extends StatefulWidget {
   /// Defaults to false.
   final bool reverse;
 
-  /// How the scroll view should respond to user input.
+  /// How the outer scroll view should respond to user input.
   ///
-  /// For example, determines how the scroll view continues to animate after the
-  /// user stops dragging the scroll view.
+  /// The physics should clamp so that the extra pixels can be given to the
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: this sentence's grammar got garbled, not sure what you meant exactly

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 3]
```diff
@@ -70,13 +70,14 @@ class NestedScrollView extends StatefulWidget {
...
+  /// inner scrollables can scroll. Passing a custom class that extends
+  /// [ClampingScrollPhysics] is allowed.
   ///
-  /// Defaults to matching platform conventions.
-  final ScrollPhysics physics;
+  /// Defaults to `const ClampingScrollPhysics()`.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: `Defaults to [ClampingScrollPhysics].` is probably better.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 4]
```diff
@@ -70,13 +70,14 @@ class NestedScrollView extends StatefulWidget {
...
   final bool reverse;
 
-  /// How the scroll view should respond to user input.
+  /// How the outer scroll view should respond to user input.
   ///
-  /// For example, determines how the scroll view continues to animate after the
-  /// user stops dragging the scroll view.
+  /// The physics should clamp so that the extra pixels can be given to the
+  /// inner scrollables can scroll. Passing a custom class that extends
+  /// [ClampingScrollPhysics] is allowed.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: `Passing a custom class that extends [ClampingScrollPhysics] is allowed.` is probably self-evident so I would omit it.
Maybe instead say something like `The value must inherit from [ClampingScrollPhysics] and its [ScrollPhysics.applyBoundaryConditions] implementation should not allow scrolling outside the scroll extent range described by the [ScrollMetrics.minScrollExtent]/[ScrollMetrics.maxScrollExtent] properties passed to that method. If that invariant is not maintained, the nested scroll view may respond to user scrolling erratically.` or some such.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 5]
```diff
@@ -70,13 +70,14 @@ class NestedScrollView extends StatefulWidget {
   /// Defaults to false.
   final bool reverse;
 
-  /// How the scroll view should respond to user input.
+  /// How the outer scroll view should respond to user input.
   ///
-  /// For example, determines how the scroll view continues to animate after the
-  /// user stops dragging the scroll view.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: You removed this sentence. Maybe consider bringing it back but having it point explicitly to [ScrollPhysics.createBallisticSimulation], which is the main method that one might want to override.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 6]
```diff
@@ -135,7 +136,7 @@ class _NestedScrollViewState extends State<NestedScrollView> {
     return new CustomScrollView(
       scrollDirection: widget.scrollDirection,
       reverse: widget.reverse,
-      physics: new ClampingScrollPhysics(parent: widget.physics),
+      physics: widget.physics ?? const ClampingScrollPhysics(),
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: Thinking about it, a better fix (which would allow us to skip all the stuff about forcing the user to use ClampingScrollPhysics et al) would be to just use `const ClampingScrollPhysics().applyTo(physics)` in the case where `physics` is non-null.

Comment (Hixie) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: er, other way around I guess. `physics.applyTo(const ClampingScrollPhysics())`. Whichever way makes the physics that was passed in take priority. You'd still need to explicitly call out that you shouldn't override the clamping method, though.

Comment (collinjackson) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: This works, so I made the change and reverted my other changes to documentation

**Comment by Hixie** [comment]
LGTM
