### PR TITLE
Fix an exception being thrown when focus groups are empty.

### LINKED ISSUE #86706: [desktop] `FocusTraversalPolicy._sortAllDescendants` crashes/throws error when tab to focus on unfocusable widgets
### Description
When running the app on desktop or web on desktop, if you press tab to focus on widget without focusability, app fatally crashes on `windows` with 
```console
                    ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
                    The following _CastError was thrown during a platform message callback:
                    Null check operator used on a null value
                    
                    When the exception was thrown, this was the stack:
                    #0      FocusTraversalPolicy._sortAllDescendants (package:flutter/src/widgets/focus_traversal.dart:340:52)
```
Meanwhile on `macOS` and `linux`, the error is thrown but no fatal crash.

After looking into the issue, I see the under `_sortAllDescendants` in `focus_traversal.dart`, `groups = <FocusNode?, _FocusTraversalGroupInfo>{};` has no data but  `visitGroups` is trying to access it anyway and throws `Null check operator used on a null value`. You can add a simple print statment to see if groups is empty or not.
```dart
    print('groups - $groups');
    // Visit the children of the scope.
    visitGroups(groups[scopeGroupMarker?.focusNode]!);
```

To make it easier to reprdouce here I've created a minimal sample 
### Steps to reproduce 

1. Run the code sample on any desktop environment on desktop app or web 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: const Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
      ),
      body:  ListTile(title: Text('title'),
        // onTap: () {}, // Uncomment to get rid of the error
      ), // Error if the ListTile has no onTap or no focusability
      // body: const ElevatedButton(
      //   child: Text('Button'),
      //   onPressed:
      //       null, // Error if the button has no onPressed or no focusability
      // ),
      // floatingActionButton: FloatingActionButton(
      //   child: Icon(Icons.add),
      //   // onPressed: () {}, // Focus is moved here hence no error
      //   onPressed: null, // Provide null here to reproduce the issue
      // ),
    );
  }
}

``` 

</details>

2. Tab to focus

## Actual results:
When you tab to focus on a widget that can't focus, 
ex: A ListTile without `onTap` 
`body: ListTile(title: Text('title'),), `

When tab to focus
`final Map<FocusNode?, _FocusTraversalGroupInfo> groups = <FocusNode?, _FocusTraversalGroupInfo>{};`  returns `{}`;
Error is thrown at `visitGroups(groups[scopeGroupMarker?.focusNode]!);` in `focus_traversal.dart`

Print statement with `groups` returns
```console
flutter: groups - {}
```

## Expected results:
Doesn't crash or throw any error 

3. if you provide `onTap` to `ListTitle` or `onPressed` to `ElevatedButton` in the code sample

4. Run the app again on desktop and tab to focus

## Actual results:
Print statement with `groups` returns
```console
flutter: groups - {FocusNode#e3df3(FocusTraversalGroup [IN FOCUS PATH])(context: Focus, NOT FOCUSABLE, IN FOCUS PATH): Instance of '_FocusTraversalGroupInfo'}
```
App doesn't crash or throw any error 

### Logs (windows- fatal crash with error)

<details> 
<summary>logs</summary> 
	
```console
C:/Users/Taha/StudioProjects/master_flutter/build/windows/runner/Debug/data/flutter_assets/fonts/MaterialIcons-Regular.otf     
[   +5 ms]   -- Installing:
C:/Users/Taha/StudioProjects/master_flutter/build/windows/runner/Debug/data/flutter_assets/kernel_blob.bin
[ +120 ms]   -- Installing:
C:/Users/Taha/StudioProjects/master_flutter/build/windows/runner/Debug/data/flutter_assets/NOTICES.Z
[   +1 ms]   -- Installing: C:/Users/Taha/StudioProjects/master_flutter/build/windows/runner/Debug/data/flutter_assets/packages
[        ]   -- Installing:
C:/Users/Taha/StudioProjects/master_flutter/build/windows/runner/Debug/data/flutter_assets/packages/cupertino_icons
[        ]   -- Installing:
C:/Users/Taha/StudioProjects/master_flutter/build/windows/runner/Debug/data/flutter_assets/packages/cupertino_icons/assets     
[   +1 ms]   -- Installing:
C:/Users/Taha/StudioProjects/master_flutter/build/windows/runner/Debug/data/flutter_assets/packages/cupertino_icons/assets/Cupe
rtinoIcons.ttf
[  +15 ms] FinalizeBuildStatus:
[        ]   Deleting file "x64\Debug\INSTALL\INSTALL.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Debug\INSTALL\INSTALL.tlog\INSTALL.lastbuildstate".
[        ] Done Building Project "C:\Users\Taha\StudioProjects\master_flutter\build\windows\INSTALL.vcxproj" (default targets).
[        ] Build succeeded.
[        ]     0 Warning(s)
[        ]     0 Error(s)
[        ] Time Elapsed 00:00:21.83
[  +15 ms] Building Windows application... (completed in 22.6s)
[ +425 ms] Observatory URL on device: http://127.0.0.1:51904/051-RwIn5ck=/
[   +4 ms] Caching compiled dill
[  +31 ms] Connecting to service protocol: http://127.0.0.1:51904/051-RwIn5ck=/
[ +113 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:51904/051-RwIn5ck=/.
[  +72 ms] DDS is listening at http://127.0.0.1:51908/m59vPYTY6xI=/.
[  +56 ms] Successfully connected to service protocol: http://127.0.0.1:51904/051-RwIn5ck=/
[  +16 ms] DevFS: Creating new filesystem on the device (null)
[  +18 ms] DevFS: Created new filesystem on the device
(file:///C:/Users/Taha/AppData/Local/Temp/master_flutter695fc225/master_flutter/)
[   +4 ms] Updating assets
[  +69 ms] Syncing files to device Windows...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +3 ms] <- recompile package:master_flutter/main.dart c268f178-5fa6-42e9-bc6f-cd75af9b45c4
[        ] <- c268f178-5fa6-42e9-bc6f-cd75af9b45c4
[  +78 ms] Updating files.
[   +1 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device Windows... (completed in 87ms)
[   +1 ms] Synced 0.0MB.
[   +2 ms] <- accept
[   +3 ms] Connected to _flutterView/0x1e2e896a550.
[   +4 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 
[   +1 ms] R Hot restart.
[   +1 ms] h List all available interactive commands.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[   +1 ms]  Running with sound null safety 
[   +1 ms] An Observatory debugger and profiler on Windows is available at: http://127.0.0.1:51908/m59vPYTY6xI=/
[ +277 ms] DevTools activation throttled until 2021-07-21 01:02:31.495488.
[ +438 ms] The Flutter DevTools debugger and profiler on Windows is available at:
                    http://127.0.0.1:9101?uri=http://127.0.0.1:51908/m59vPYTY6xI=/
[ +739 ms] Unable to parse JSON message:
[   +1 ms] The document is empty.
[  +11 ms]
           ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
           The following _CastError was thrown during a platform message callback:
           Null check operator used on a null value

           When the exception was thrown, this was the stack:
           #0      FocusTraversalPolicy._sortAllDescendants (package:flutter/src/widgets/focus_traversal.dart:340:52)
           #1      FocusTraversalPolicy._findInitialFocus (package:flutter/src/widgets/focus_traversal.dart:167:42)
           #2      FocusTraversalPolicy.findFirstFocus (package:flutter/src/widgets/focus_traversal.dart:139:55)
           #3      FocusTraversalPolicy._moveFocus (package:flutter/src/widgets/focus_traversal.dart:381:47)
           #4      FocusTraversalPolicy.next (package:flutter/src/widgets/focus_traversal.dart:223:39)
           #5      FocusNode.nextFocus (package:flutter/src/widgets/focus_manager.dart:1153:56)
           #6      NextFocusAction.invoke (package:flutter/src/widgets/focus_traversal.dart:1885:19)
           #7      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:520:21)
           #8      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:834:38)
           #9      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:1175:20)
           #10     FocusManager._handleRawKeyEvent (package:flutter/src/widgets/focus_manager.dart:1681:50)
           #11     RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:682:69)
           #12     BasicMessageChannel.setMessageHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:73:49)
           #13     BasicMessageChannel.setMessageHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:72:47)
           #14     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
(package:flutter/src/services/binding.dart:359:35)
           #15     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
(package:flutter/src/services/binding.dart:356:46)
           #16     _invoke2.<anonymous closure> (dart:ui/hooks.dart:203:15)
           #20     _invoke2 (dart:ui/hooks.dart:202:10)
           #21     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
           #22     _Channel.push (dart:ui/channel_buffers.dart:132:31)
           #23     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
           #24     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:536:22)
           #25     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
           (elided 3 frames from dart:async)
           ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +514 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device
(file:///C:/Users/Taha/AppData/Local/Temp/master_flutter695fc225/master_flutter/)
[ +262 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +6 ms] "flutter run" took 28,314ms.
[  +76 ms] ensureAnalyticsSent: 73ms
[   +1 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

</details>

### Logs (macOS -  no fatal crash with error)

<details> 
<summary>logs</summary> 
	
```console
[  +81 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device macOS... (completed in 88ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +2 ms] Connected to _flutterView/0x7fb00d863220.
[   +3 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on macOS is available at:
           http://127.0.0.1:50301/c2bLnT1Z0zk=/
[ +296 ms] DevTools activation throttled until 2021-07-20 22:07:27.896527.
[ +585 ms] The Flutter DevTools debugger and profiler on macOS is available at:

http://127.0.0.1:9100?uri=http://127.0.0.1:50301/c2bLnT1Z0zk=/
[+5945 ms] flutter: groups - {}
[  +84 ms] 
           ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY
           ╞══════════════════════════════════════════════════════════
           The following _CastError was thrown during a platform message
callback:
           Null check operator used on a null value
           
           When the exception was thrown, this was the stack:
           #0      FocusTraversalPolicy._sortAllDescendants
           (package:flutter/src/widgets/focus_traversal.dart:341:52)
           #1      FocusTraversalPolicy._findInitialFocus
           (package:flutter/src/widgets/focus_traversal.dart:167:42)
           #2      FocusTraversalPolicy.findFirstFocus
           (package:flutter/src/widgets/focus_traversal.dart:139:55)
           #3      FocusTraversalPolicy._moveFocus
           (package:flutter/src/widgets/focus_traversal.dart:382:47)
           #4      FocusTraversalPolicy.next
           (package:flutter/src/widgets/focus_traversal.dart:223:39)
           #5      FocusNode.nextFocus
           (package:flutter/src/widgets/focus_manager.dart:1153:56)
           #6      NextFocusAction.invoke
           (package:flutter/src/widgets/focus_traversal.dart:1886:19)
           #7      ActionDispatcher.invokeAction
           (package:flutter/src/widgets/actions.dart:520:21)
           #8      ShortcutManager.handleKeypress
           (package:flutter/src/widgets/shortcuts.dart:834:38)
           #9      _ShortcutsState._handleOnKey
           (package:flutter/src/widgets/shortcuts.dart:1175:20)
           #10     FocusManager._handleRawKeyEvent
           (package:flutter/src/widgets/focus_manager.dart:1681:50)
           #11     RawKeyboard._handleKeyEvent
           (package:flutter/src/services/raw_keyboard.dart:682:69)
           #12     BasicMessageChannel.setMessageHandler.<anonymous closure>
           (package:flutter/src/services/platform_channel.dart:73:49)
           #13     BasicMessageChannel.setMessageHandler.<anonymous closure>
           (package:flutter/src/services/platform_channel.dart:72:47)
           #14     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
           (package:flutter/src/services/binding.dart:359:35)
           #15     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
           (package:flutter/src/services/binding.dart:356:46)
           #16     _invoke2.<anonymous closure> (dart:ui/hooks.dart:203:15)
           #20     _invoke2 (dart:ui/hooks.dart:202:10)
           #21     _ChannelCallbackRecord.invoke
(dart:ui/channel_buffers.dart:42:5)
           #22     _Channel.push (dart:ui/channel_buffers.dart:132:31)
           #23     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
           #24     PlatformDispatcher._dispatchPlatformMessage
           (dart:ui/platform_dispatcher.dart:536:22)
           #25     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
           (elided 3 frames from dart:async)

════════════════════════════════════════════════════════════════════════════════
           ════════════════════

```

</details>

|  `stable`  |  `beta`  | `dev` | `master` |
| :---: | :---: | :---: |:---: |
|  ❌  |   ❌  |  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

Note: Same Flutter version applies to `windows` and app crashes

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5284e darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5284e darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!
```

```console
[✓] Flutter (Channel beta, 2.3.0-24.1.pre, on macOS 12.0 21A5284e darwin-x64, locale en-GB)
    • Flutter version 2.3.0-24.1.pre at /Users/tahatesser/Code/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 615957513e (4 weeks ago), 2021-06-25 09:24:44 -0700
    • Engine revision 9d517f475b
    • Dart version 2.14.0 (build 2.14.0-188.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5284e darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!

```

```console
[✓] Flutter (Channel dev, 2.4.0-4.0.pre, on macOS 12.0 21A5284e darwin-x64, locale en-GB)
    • Flutter version 2.4.0-4.0.pre at /Users/tahatesser/Code/flutter_dev
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cc00e7e6bc (9 days ago), 2021-07-11 18:21:02 -0400
    • Engine revision ed25e8f01e
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5284e darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.4.0-5.0.pre.105, on macOS 12.0 21A5284e darwin-x64, locale en-GB)
    • Flutter version 2.4.0-5.0.pre.105 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a5b9b5774a (10 hours ago), 2021-07-19 20:23:45 -0700
    • Engine revision 9edde7423f
    • Dart version 2.14.0 (build 2.14.0-332.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5284e darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!
```
		
</details>

✅ : No Issue ❌: Issue reproduced

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

When a focus traversal group has no entries, but traversal is requested, we were throwing an exception because we couldn't find the group marker's scope in the list of candidates.  This fixes that, and adds a test.

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/86706

## Tests

- Added a test to make sure that an empty group doesn't throw when traversal is requested.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/86734

File: packages/flutter/test/widgets/focus_traversal_test.dart [hunk 1]
```diff
@@ -2015,6 +2015,11 @@ void main() {
       expect(events.length, 2);
     });
 
+    testWidgets('Focus traversal does not throw when no focusable is available in a group', (WidgetTester tester) async {
+      await tester.pumpWidget(const MaterialApp(home: Scaffold(body: ListTile(title: Text('title')))));
+      await tester.sendKeyEvent(LogicalKeyboardKey.tab);
```
Comment (goderbauer) [inline packages/flutter/test/widgets/focus_traversal_test.dart:2020]: Can we assert somehow that "nothing" has focus or that the focus stayed where it was even after the tab was send?

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/widgets/focus_traversal_test.dart (hunk 1 above)
Comment (gspencergoog) [reply packages/flutter/test/widgets/focus_traversal_test.dart:2021]: Sure.  Done.

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/86734
