### PR TITLE
bubble up fragment shader errors

### LINKED ISSUE #176593: impeller: shader failures should be surfaced to dart
## observed

There are a handful of ways loading shaders can go wrong and we don't communicate it back to the user.

Example: https://github.com/flutter/flutter/blob/04f323450df4f282387f709db2da1ea10dae4e99/engine/src/flutter/lib/gpu/shader_library.cc#L176

Sometimes we have VALIDATION_LOGs which will only be present in debug builds of the engine.

More failures were added in https://github.com/flutter/flutter/pull/175470

## expected

I'd expect these failures to surface up to Dart exceptions so users developing with shaders get meaningful errors.  Users may be developing shaders in non-debug build engines.

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/176593
That issue was really fixed in https://github.com/flutter/flutter/pull/175470 but this is extra cleanup for error handling with shaders, including better error messages when loading them in tests.

changes:
- Removes RuntimeStage::IsValid to statically assert that we only ever have valid runtime stages
- Finally introduces ASSERT_OK which should have been added long ago

This doesn't propagate up shaderlibrary errors since that's flutter_gpu.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/testing/assert_ok.h [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+// found in the LICENSE file.
+
+#ifndef FLUTTER_TESTING_ASSERT_OK_H_
+#define FLUTTER_TESTING_ASSERT_OK_H_
+
+#include "gtest/gtest.h"
+
+// Asserts that the given absl::Status or absl::StatusOr is OK.
+// If it is not OK, the status error message is printed.
+#ifdef ASSERT_OK
```
Comment (jason-simmons) [inline engine/src/flutter/testing/assert_ok.h]: Abseil provides matchers for `absl::StatusOr`:

```
#include "third_party/abseil-cpp/absl/status/status_matchers.h"
using ::absl_testing::IsOk;

ASSERT_THAT(stages, IsOk());
```

The latest Abseil also defines `ABSL_ASSERT_OK`/`ABSL_EXPECT_OK` macros similar to this header
(see https://github.com/abseil/abseil-cpp/commit/2487de07)

These macros landed shortly after Flutter's most recent Abseil roll.  I can do another roll of Abseil to get this update.

Comment (gaaclarke) [reply engine/src/flutter/testing/assert_ok.h]: sgtm, i'll rebase once that lands

File: engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc [hunk 2]
```diff
@@ -12,23 +14,32 @@
...
     AiksTest* test,
     std::string_view name,
     const std::shared_ptr<std::vector<uint8_t>>& uniform_data = {},
     const std::vector<std::shared_ptr<DlColorSource>>& samplers = {}) {
-  auto runtime_stages = test->OpenAssetAsRuntimeStage(name.data());
+  auto runtime_stages_result = test->OpenAssetAsRuntimeStage(name.data());
+  if (!runtime_stages_result.ok()) {
+    return runtime_stages_result.status();
+  }
+  auto runtime_stages = runtime_stages_result.value();
```
Comment (walley892) [inline engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc]: Instead of having two separate variables `runtime_stages_result` and `runtime_stages=runtime_stages_result.value()`, I think it's more idiomatic to just have one variable called `runtime_states` and use the `*` operator to get the value. 

go/totw/181#avoiding-the-or-suffix
go/totw/181#recommendation

File: engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc [hunk 3]
```diff
@@ -48,8 +59,10 @@ TEST_P(AiksTest, CanRenderClippedRuntimeEffects) {
   memcpy(uniform_data->data(), &frag_uniforms, sizeof(FragUniforms));
 
   DlPaint paint;
-  paint.setColorSource(
-      MakeRuntimeEffect(this, "runtime_stage_example.frag.iplr", uniform_data));
+  auto effect =
+      MakeRuntimeEffect(this, "runtime_stage_example.frag.iplr", uniform_data);
+  ASSERT_OK(effect);
+  paint.setColorSource(effect.value());
```
Comment (walley892) [inline engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc:65]: Same comment about the * operator

File: engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc [hunk 4]
```diff
@@ -71,8 +84,9 @@ TEST_P(AiksTest, DrawPaintTransformsBounds) {
   memcpy(uniform_data->data(), &frag_uniforms, sizeof(FragUniforms));
 
   DlPaint paint;
-  paint.setColorSource(
-      MakeRuntimeEffect(this, "gradient.frag.iplr", uniform_data));
+  auto effect = MakeRuntimeEffect(this, "gradient.frag.iplr", uniform_data);
+  ASSERT_OK(effect);
+  paint.setColorSource(effect.value());
```
Comment (walley892) [inline engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc:89]: * operator

File: engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc [hunk 5]
```diff
@@ -84,8 +98,10 @@ TEST_P(AiksTest, DrawPaintTransformsBounds) {
 }
 
 TEST_P(AiksTest, CanRenderRuntimeEffectFilter) {
-  auto runtime_stages =
+  auto runtime_stages_result =
```
Comment (walley892) [inline engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc:101]: Same comment about naming and the * operator

Comment (walley892) [reply engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc:101]: Same comment throughout this file

File: engine/src/flutter/impeller/display_list/aiks_dl_vertices_unittests.cc [hunk 6]
```diff
@@ -477,8 +478,10 @@ TEST_P(AiksTest, DrawVerticesTextureCoordinatesWithFragmentShader) {
   flutter::DlPaint rect_paint;
   rect_paint.setColor(DlColor::kBlue());
 
-  auto runtime_stages =
+  auto runtime_stages_result =
```
Comment (walley892) [inline engine/src/flutter/impeller/display_list/aiks_dl_vertices_unittests.cc:481]: Same comment about * operator and naming in this file

File: engine/src/flutter/impeller/display_list/canvas_unittests.cc [hunk 7]
```diff
@@ -327,8 +328,10 @@ TEST_P(AiksTest, DrawVerticesLinearGradientWithEmptySize) {
 }
 
 TEST_P(AiksTest, DrawVerticesWithEmptyTextureCoordinates) {
-  auto runtime_stages =
+  auto runtime_stages_result =
```
Comment (walley892) [inline engine/src/flutter/impeller/display_list/canvas_unittests.cc:331]: same comments here about * and naming

File: engine/src/flutter/impeller/entity/entity_unittests.cc [hunk 8]
```diff
@@ -1752,8 +1753,10 @@ TEST_P(EntityTest, YUVToRGBFilter) {
 }
 
 TEST_P(EntityTest, RuntimeEffect) {
-  auto runtime_stages =
+  auto runtime_stages_result =
```
Comment (walley892) [inline engine/src/flutter/impeller/entity/entity_unittests.cc:1756]: Same comment about * and naming in this file

File: engine/src/flutter/impeller/golden_tests/golden_playground_test.h [hunk 9]
```diff
@@ -10,11 +10,14 @@
...
+#include "flutter/impeller/golden_tests/golden_digest.h"
 #include "flutter/impeller/golden_tests/screenshot.h"
-#include "flutter/impeller/playground/playground.h"
 #include "flutter/impeller/renderer/render_target.h"
 #include "flutter/testing/testing.h"
+#include "gtest/gtest.h"
+#include "impeller/playground/playground.h"
 #include "impeller/typographer/typographer_context.h"
+#include "third_party/abseil-cpp/absl/status/statusor.h"
 #include "third_party/imgui/imgui.h"
```
Comment (walley892) [inline engine/src/flutter/impeller/golden_tests/golden_playground_test.h]: Are all of these new imports used?

File: engine/src/flutter/impeller/runtime_stage/runtime_stage_unittests.cc [hunk 10]
```diff
@@ -338,7 +339,9 @@ TEST_P(RuntimeStageTest, CanRegisterStage) {
 }
 
 TEST_P(RuntimeStageTest, CanCreatePipelineFromRuntimeStage) {
-  auto stages = OpenAssetAsRuntimeStage("ink_sparkle.frag.iplr");
+  auto stages_result = OpenAssetAsRuntimeStage("ink_sparkle.frag.iplr");
```
Comment (walley892) [inline engine/src/flutter/impeller/runtime_stage/runtime_stage_unittests.cc:342]: Same annoying comment in this file about naming and * operator

**Review by walley892 — COMMENTED** [review]
A couple of comments mostly about cpp style

File: engine/src/flutter/testing/assert_ok.h (hunk 1 above)
Comment (gaaclarke) [reply engine/src/flutter/testing/assert_ok.h]: done

File: engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc (hunk 2 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/display_list/aiks_dl_runtime_effect_unittests.cc]: done, and below

File: engine/src/flutter/impeller/golden_tests/golden_playground_test.h (hunk 9 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/golden_tests/golden_playground_test.h]: some of them! done

**Review by jason-simmons — APPROVED** [review]
