### PR TITLE
Accessibility: repeated label on BottomNavigationBar fixed

### LINKED ISSUE #71543: Accessibility: repeated label on BottomNavigationBarItem
## Steps to Reproduce

1. Run `flutter create bug`.
2. Modify main.dart like this:
``` dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      bottomNavigationBar: BottomAppBar(
        child: BottomNavigationBar(
          currentIndex: _currentIndex,
          onTap: (i) {
            setState(() {
              _currentIndex = i;
            });
          },
          items: [
            BottomNavigationBarItem(
              icon: Icon(Icons.bluetooth_searching),
              label: "Dog",
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.star_border),
              label: "Cat",
            )
          ],
        ),
      ),
    );
  }
}
```
3. Enable TalkBack on Android and select one of the bottom navigation tabs

(Should be similar on iOS VoiceOver)

**Expected results:** 

TalkBack should say something like "Selected dog tab one of two"

**Actual results:** 

Instead it says "Selected dog dog tab one of two"

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale es_ES.UTF-8)
    • Flutter version 1.22.4 at /home/angel/flutter/soft/flutter
    • Framework revision 1aafb3a8b9 (hace 3 semanas), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/angel/android/soft/sdk/
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /home/angel/android/soft/sdk/
    • ANDROID_SDK_ROOT = /home/angel/android/soft/sdk/
    • Java binary at: /home/angel/android/soft/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/angel/android/soft/android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Pixel 3a (mobile) • 93JAY0BMB2 • android-arm64 • Android 11 (API 30)

• No issues found!
```

</details>

You can fix this problem editing bottom_navigation_bar.dart and replacing:

``` dart
    if (item.label != null) {
      result = Tooltip(
        message: item.label,
        preferBelow: false,
        verticalOffset: selectedIconSize + selectedFontSize,
        child: result,
      );
    }
```

with this:

``` dart
    if (item.label != null) {
      result = Tooltip(
        message: item.label,
        preferBelow: false,
        verticalOffset: selectedIconSize + selectedFontSize,
        child: ExcludeSemantics(child: result), // <-- FIX HERE
      );
    }
```

### PR DESCRIPTION
**Pull request by yash1200**
## Description

Fixes repeated label by Talkback in bottomNavigationBar.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/71543

## Tests

I added the following tests:

No tests failed.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 1]
```diff
@@ -492,7 +492,7 @@ class _BottomNavigationTile extends StatelessWidget {
         message: item.label!,
         preferBelow: false,
         verticalOffset: selectedIconSize + selectedFontSize,
-        child: result,
+        child: ExcludeSemantics(child: result),
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart:495]: instead of excluding the the result entirely, we should set excludeFromSemantics to true for tooltip

**Review by chunhtai — COMMENTED** [review]
We also need a test

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 1 above)
Comment (yash1200) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart]: I have added tests as well as did the changes.

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by yash1200** [comment]
@chunhtai I think this should be merged now.
