### PR TITLE
Fix the NestedScrollView exception when rebuilding during scheduleWarmUpFrame

### LINKED ISSUE #72257: Issue while using NestedScrollView as Page-based route.
## Description
Using `NestedScrollView` as pages throws assertion error.
```
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 805 pos 14: 'position.hasContentDimensions && position.hasPixels': is not true.
```

## Steps to Reproduce
Code snippet to reproduce the issue.

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Navigator(
        pages: [
          MaterialPage(
            key: ValueKey(1),
            child: SampleWidget(number: 1),
          ),
          MaterialPage(
            key: ValueKey(2),
            child: SampleWidget(number: 2),
          ),
        ],
        onPopPage: (route, result) => route.didPop(result),
      ),
    );
  }
}

class SampleWidget extends StatelessWidget {
  final int number;

  const SampleWidget({Key key, this.number}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return NestedScrollView(
      headerSliverBuilder: (context, _) => [
        SliverAppBar(
          title: Text('Sample $number'),
        ),
      ],
      body: Scaffold(
        body: ListView(
          children: [
            Center(child: Text('Body $number')),
          ],
        ),
      ),
    );
  }
}
```
**Expected results:** 
Navigates to **Page 2** without any issue.

**Actual results:** 
Page 2 is in the top of the navigation stack but Page 1 will have assertion error.
```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 805 pos 14: 'position.hasContentDimensions && position.hasPixels': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      _NestedScrollCoordinator.hasScrolledBody (package:flutter/src/widgets/nested_scroll_view.dart:805:14)
#3      NestedScrollViewState._handleHasScrolledBodyChanged (package:flutter/src/widgets/nested_scroll_view.dart:609:51)
#4      _NestedScrollCoordinator.updateShadow (package:flutter/src/widgets/nested_scroll_view.dart:813:50)
#5      _NestedScrollController._scheduleUpdateShadow.<anonymous closure> (package:flutter/src/widgets/nested_scroll_view.dart:1310:21)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1119:15)
...
====================================================================================================
```

<details>
  <summary>flutter doctor output</summary>

```
[✓] Flutter (Channel dev, 1.25.0-8.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.25.0-8.0.pre at ...
    • Framework revision a12e2a473a (5 days ago), 2020-12-08 23:13:04 -0500
    • Engine revision df39e5c515
    • Dart version 2.12.0 (build 2.12.0-133.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at ...
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Linux
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.88
```

</details>

### LINKED ISSUE #75107: Failed assertion using a NestedScrollView
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update `main.dart` with code bellow:

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      theme: CupertinoThemeData(),
      home: CupertinoTabScaffold(
        tabBar: CupertinoTabBar(items: [
          BottomNavigationBarItem(
            icon: Icon(CupertinoIcons.waveform),
            label: '1',
          ),
          BottomNavigationBarItem(
            icon: Icon(CupertinoIcons.app),
            label: '2',
          )
        ]),
        tabBuilder: (context, index) {
          return TabPage();
        },
      ),
    );
  }
}

class TabPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return [
            CupertinoSliverNavigationBar(
              largeTitle: Text('Large Title'),
            )
          ];
        },
        body: CustomScrollView(
          slivers: [
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (context, index) {
                  return Text('');
                },
                childCount: 10,
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

**Expected results:**
The app running after first build.

**Actual results:**
Crashes on the first run, right after a build. A hot reload hides the issue, but every time the app is built again, it will show this error.

**Observations:**
Bug might be related to issue #72257

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Builder(dirty):
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 805 pos 14: 'position.hasContentDimensions && position.hasPixels': is not true.
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
NestedScrollView
lib/main.dart:37
When the exception was thrown, this was the stack
#2      _NestedScrollCoordinator.hasScrolledBody
package:flutter/…/widgets/nested_scroll_view.dart:805
#3      NestedScrollViewState.build.<anonymous closure>
package:flutter/…/widgets/nested_scroll_view.dart:627
#4      Builder.build
package:flutter/…/widgets/basic.dart:7555
```

<details>
  <summary>Doctor output</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-arm, locale en-PT)
    • Flutter version 1.25.0-8.3.pre at /Users/delta/Development/flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/delta/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPhone 12 mini (mobile) • AA46B792-422D-4099-8663-FA128A11DAAD • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
### How does it happen
1. `scheduleAttachRootWidget` will call `_firstBuild` and new a `_NestedScrollPosition` with null pixels.
2. The `FocusManager` will schedule a microTask.
3. Finish fistBuild and then flush the microTask. The `NestedScrollView` dirty again.
4. `scheduleWarmUpFrame` will rebuild the dirty node and trigger the exception(`_NestedScrollPosition` only available after layout).

### Reproduce Steps
See the unit test.

Fixes #75107 
Fixes #72257

### CODE REVIEW

**Comment by Arthursolo** [comment]
Հ

**Review by Arthursolo — COMMENTED** [review]
Accidentally commented, can't now delete it, sorry ))

**Review by chunhtai — COMMENTED** [review]
do you know what micro task is scheduled by focus manager? I am surprised at that the widget is able to interrupt the warm up phase. I have seen this issue before, and the way to fix it is to make sure the tree cannot be dirty during the warm up frame. Otherwise, we are wasting time to build the tree twice.

**Comment by xu-baolin** [comment]
https://github.com/flutter/flutter/blob/998d1c6523513c15c58d5b66f01dffcc381ddf54/packages/flutter/lib/src/widgets/focus_manager.dart#L1735

**Comment by xu-baolin** [comment]
not interrupt. The warm up phase will flush micro task first. 
The micro task scheduled during first build at scheduleAttachRootWidget.

**Comment by chunhtai** [comment]
Hi @xu-baolin 

> not interrupt. The warm up phase will flush micro task first.
> The micro task scheduled during first build at scheduleAttachRootWidget.

Thanks for explanation. I wonder if we have a way to avoid this? The attachRootWidget will build the tree, and then focus manager comes in and dirty it, the handle drawframe will then build the tree again because it was dirty.

In this scenario, built twice and is not necessary. Is it possible to avoid the focus manager from dirty it in the middle?

**Comment by xu-baolin** [comment]
Is it possible that the tree is really dirty? For example, in a unit test case, the user can change the properties of the tree at the onfocuschange, so we can't ignore it.

**Comment by chunhtai** [comment]
Either the attached root widget does not build a tree for it to dirty (i don't think this is possible?)
or the onfocuschange came after the warm up frame has been drawn.

any reason why we uses scheduleMicrotask instead a postframecallback? cc @gspencergoog may know

**Comment by xu-baolin** [comment]
> Either the attached root widget does not build a tree for it to dirty (i don't think this is possible?)


It must be a huge change, but I think we can investigate the feasibility first.

**Comment by xu-baolin** [comment]
@chunhtai Hi,
I tried to found why use scheduleMicrotask instead a postframecallback, and found this #9074
```
Focus notifications trigger by tree mutations are now delayed by one
frame, which is necessary to handle certain complex tree mutations. In
the common case of focus changes being triggered by user input, the
focus notificiation still arives in the same frame.
```
Use micro task to ensure that the focus change triggered by the input arrives in the same frame.

Also, I tried to use post callback instead of micro task, which cause hundreds of tests to fail.

**Comment by xu-baolin** [comment]
Back to this issue, the current implementation proves that the exception is a normal or legal scenario. 
As for trying to optimize the build process, I think we can create a new topic, right?

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 1]
```diff
@@ -795,8 +795,9 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
 
   bool get hasScrolledBody {
     for (final _NestedScrollPosition position in _innerPositions) {
-      assert(position.hasContentDimensions && position.hasPixels);
-      if (position.pixels > position.minScrollExtent) {
+      if (!position.hasContentDimensions || !position.hasPixels) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:798]: Can you add a comment explain why this can happen?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:798]: also we should skip this position instead of returning false

**Review by chunhtai — COMMENTED** [review]
If the reason for microtask is to deal with user input, it does not have to use microtask for first build.

**Comment by xu-baolin** [comment]
> If the reason for microtask is to deal with user input, it does not have to use microtask for first build.

That is true, do you think it is necessary to create a new topic to track this?

**Comment by xu-baolin** [comment]
@googlebot I fixed it.

**Comment by xu-baolin** [comment]
Sorry that I change a computer with a different email and cause the bot cla check failed.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 2]
```diff
@@ -795,8 +795,14 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
...
+        // It's possible that NestedScrollView built twice before layout phase
+        // in a same frame.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:800]: in the same frame

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 3]
```diff
@@ -795,8 +795,14 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
...
+        // This happens for example when FocusManager schedule a microTask
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:801]: This can happen when the FocusManager schedules..

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 4]
```diff
@@ -795,8 +795,14 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
...
+        // that mark NestedScrollView dirty during `scheduleAttachRootWidget`.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:802]: that markes ... during the warm up frame

**Review by chunhtai — APPROVED** [review]
LGTM, modulo nits.

yes we should have an issue to track the focus manager issue

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 4 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:802]: Thank you for your detailed grammar guide. : )

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 5]
```diff
@@ -795,8 +795,14 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
 
   bool get hasScrolledBody {
     for (final _NestedScrollPosition position in _innerPositions) {
-      assert(position.hasContentDimensions && position.hasPixels);
-      if (position.pixels > position.minScrollExtent) {
+      if (!position.hasContentDimensions || !position.hasPixels) {
+        // It's possible that NestedScrollView built twice before layout phase
+        // in the same frame.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:800]: nit: no new line, we should merge them in one paragraph.
