### PR TITLE
Make sure _handleAppFrame is only registered once per frame

### LINKED ISSUE #30340: MultiFrameImageStreamCompleter null dereference
Got reports from the wild with the following stack trace:
```
2019-04-01 20:27:21.453 8085-8351/com.google.android.apps.mediashell I/flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
2019-04-01 20:27:21.474 8085-8351/com.google.android.apps.mediashell I/flutter: The following NoSuchMethodError was thrown during a scheduler callback:
2019-04-01 20:27:21.475 8085-8351/com.google.android.apps.mediashell I/flutter: The getter 'image' was called on null.
2019-04-01 20:27:21.475 8085-8351/com.google.android.apps.mediashell I/flutter: Receiver: null
2019-04-01 20:27:21.475 8085-8351/com.google.android.apps.mediashell I/flutter: Tried calling: image
2019-04-01 20:27:21.475 8085-8351/com.google.android.apps.mediashell I/flutter: When the exception was thrown, this was the stack:
2019-04-01 20:27:21.492 8085-8351/com.google.android.apps.mediashell I/flutter: #0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
2019-04-01 20:27:21.493 8085-8351/com.google.android.apps.mediashell I/flutter: #1      MultiFrameImageStreamCompleter._handleAppFrame (package:flutter/src/painting/image_stream.dart:548:46)
2019-04-01 20:27:21.493 8085-8351/com.google.android.apps.mediashell I/flutter: #2      __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
2019-04-01 20:27:21.493 8085-8351/com.google.android.apps.mediashell I/flutter: #3      __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:928:11)
2019-04-01 20:27:21.493 8085-8351/com.google.android.apps.mediashell I/flutter: #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/lib/compact_hash.dart:367:8)
2019-04-01 20:27:21.493 8085-8351/com.google.android.apps.mediashell I/flutter: #5      __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:926:17)
2019-04-01 20:27:21.493 8085-8351/com.google.android.apps.mediashell I/flutter: #6      __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:856:5)
2019-04-01 20:27:21.493 8085-8351/com.google.android.apps.mediashell I/flutter: #10     _invoke1 (dart:ui/hooks.dart:233:10)
2019-04-01 20:27:21.493 8085-8351/com.google.android.apps.mediashell I/flutter: #11     _beginFrame (dart:ui/hooks.dart:172:3)
2019-04-01 20:27:21.493 8085-8351/com.google.android.apps.mediashell I/flutter: (elided 3 frames from package dart:async)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: This exception was thrown in the context of a scheduler callback. When the scheduler callback was
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: _registered_ (as opposed to when the exception was thrown), this was the stack:
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: #0      new _FrameCallbackEntry.<anonymous closure> (package:flutter/src/scheduler/binding.dart:112:33)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: #1      new _FrameCallbackEntry (package:flutter/src/scheduler/binding.dart:115:6)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: #2      __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:448:49)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: #3      MultiFrameImageStreamCompleter._decodeNextFrameAndSchedule (package:flutter/src/painting/image_stream.dart:592:31)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: <asynchronous suspension>
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: #4      MultiFrameImageStreamCompleter._handleAppFrame (package:flutter/src/painting/image_stream.dart:554:9)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: #5      __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: #6      __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:928:11)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: #7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/lib/compact_hash.dart:367:8)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: #8      __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:926:17)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: #9      __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:856:5)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: #13     _invoke1 (dart:ui/hooks.dart:233:10)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: #14     _beginFrame (dart:ui/hooks.dart:172:3)
2019-04-01 20:27:21.505 8085-8351/com.google.android.apps.mediashell I/flutter: (elided 3 frames from package dart:async)
```

After some analysis of the code I see how this can happen if `_handleAppFrame` is added multiple times as a frame callback. 2 ways in which this can happen:

*Scenario 1*
  1. A GIF frame is decoded and a Flutter frame is executed before it's time to show the next GIF frame.
  2. The timer that's waiting for enough time to elapse is invoked, and schedules a callback for the next Flutter frame([here](https://github.com/flutter/flutter/blob/99f1e507c9fe198fbdccdf8a2b6af63dc010736c/packages/flutter/lib/src/painting/image_stream.dart#L560)).
  3. Before the next Flutter frame is executed, `MultiFrameImageStreamCompleter#removeListener` is called followed by ``MultiFrameImageStreamCompleter#addListener` that is invoking `_decodeNextFrameAndSchedule` which is adding `_handleAppFrame` again as a next frame callback.

*Scenario 2*
removeListener and addListener are called multiple times in succession, every call to addListener can result in another registration of `_handleAppFrame` to the next Flutter frame callbacks list.

### PR DESCRIPTION
**Pull request by amirh**
## Description

There were 2 possible scenarios in which `_handleAppFrame` is added more than once as a frame callback. When this happens it is possible that the second invocation will try to access `_nextFrame.image` when `_nextFrame` is null and crash. The 2 scenarios are:

*Scenario 1*
  1. A GIF frame is decoded and a Flutter frame is executed before it's time to show the next GIF frame.
  2. The timer that's waiting for enough time to elapse is invoked, and schedules a callback for the next Flutter frame([here](https://github.com/flutter/flutter/blob/99f1e507c9fe198fbdccdf8a2b6af63dc010736c/packages/flutter/lib/src/painting/image_stream.dart#L560)).
  3. Before the next Flutter frame is executed, `MultiFrameImageStreamCompleter#removeListener` is called followed by ``MultiFrameImageStreamCompleter#addListener` that is invoking `_decodeNextFrameAndSchedule` which is adding `_handleAppFrame` again as a next frame callback.

*Scenario 2*
removeListener and addListener are called multiple times in succession, every call to addListener can result in another registration of `_handleAppFrame` to the next Flutter frame callbacks list.

This patch fixes the issue by guarding against a second registration of _handleAppFrame.

## Related Issues

fixes #30340

## Tests

I added the following tests:

* A test that follows scenario 2 above.
* [temporarily disabled] A test that follows scenario 1 above.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by amirh** [comment]
cc @xster

File: packages/flutter/lib/src/painting/image_stream.dart [hunk 1]
```diff
@@ -557,7 +562,7 @@ class MultiFrameImageStreamCompleter extends ImageStreamCompleter {
     }
     final Duration delay = _frameDuration - (timestamp - _shownTimestamp);
     _timer = Timer(delay * timeDilation, () {
```
Comment (dnfield) [inline packages/flutter/lib/src/painting/image_stream.dart]: Would it make sense guarding the timer with this check too, so that you don't even register the timer if it's already been registered?

Could you possibly achieve this same effect by just doing something like `_timer ??=`?

Comment (amirh) [reply packages/flutter/lib/src/painting/image_stream.dart]: I don't see how guarding just against double timer registration fixes the described issue (e.g in the addListener,removeListener,addListener scenario).

I'm not sure I see a scenario where we will have double timer registration with the current guard given that `removeListener` cancels the timer after removing all listeners.

Can you describe the scenario you're thinking about in which there will be double timer registration?

Comment (dnfield) [reply packages/flutter/lib/src/painting/image_stream.dart]: I may be misreading something here, but it looks like this timer can get created multiple times without getting cancelled, which could be leading to multiple registration.

**Comment by amirh** [comment]
I'm probably missing what you see, can you please describe the sequence of
events that leads to multiple timer registration?

File: packages/flutter/lib/src/painting/image_stream.dart (hunk 1 above)
Comment (amirh) [reply packages/flutter/lib/src/painting/image_stream.dart]: I'm probably missing what you see, can you please describe the sequence of events that leads to multiple timer registration?

Comment (dnfield) [reply packages/flutter/lib/src/painting/image_stream.dart]: It looks like the constructor of this class calls `_handleAppFrame` when the codec is ready (https://github.com/flutter/flutter/blob/44c127024d1cddcbf0e63652cbf36ba22d6384f1/packages/flutter/lib/src/painting/image_stream.dart#L515), and when the first listener is added it's also called (https://github.com/flutter/flutter/blob/44c127024d1cddcbf0e63652cbf36ba22d6384f1/packages/flutter/lib/src/painting/image_stream.dart#L616).  It seems entirely possible that the `Image` widget ends up making a new image stream which ends up creating a timer and then adding a listener which creates a second timer before the first has finished.

Comment (amirh) [reply packages/flutter/lib/src/painting/image_stream.dart]: Good catch!
The scenario you describe can actually result in the first frame being skipped(as `_nextFrame` can be set to the second codec frame before the next flutter frame is executed).

Fixed it by only starting to decode after both the codec is ready and a frame listener is added.
In practice I'd imagine that this was very unlikely to happen as the first frame listener was likely to be added synchronously right after creating the stream completer at which point `_codec` is still null (as the async call had no chance to complete) thus the second `_decodeNextFrameAndSchedule` will not be invoked (it's guarded by a check that `_codec` is not null).

Anyway with this fixed I don't see a scenario where the timer is registered multiple times simultaneously.

File: packages/flutter/lib/src/painting/image_stream.dart [hunk 2]
```diff
@@ -510,7 +510,8 @@ class MultiFrameImageStreamCompleter extends ImageStreamCompleter {
        _informationCollector = informationCollector,
        _scale = scale,
        _framesEmitted = 0,
-       _timer = null {
+       _timer = null,
+       _frameCallbackScheduled = false {
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/image_stream.dart]: nit: It reads a little cleaner to me if you would just initialize the member with false in line 539 instead of doing it here.

**Review by goderbauer — APPROVED** [review]
LGTM

Thanks for debugging and fixing!

File: packages/flutter/lib/src/painting/image_stream.dart (hunk 2 above)
Comment (amirh) [reply packages/flutter/lib/src/painting/image_stream.dart]: done
