### PR TITLE
#163840 - CupertinoButton cursor doesn't change to clickable on desktop

### LINKED ISSUE #163840: CupertinoButton cursor doesn't change to clickable on desktop
### Steps to reproduce

Run the provided code below

### Expected results

Expected a way to change cursor on desktop

### Actual results

No way to change the cursor on the desktop.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

void main() async{
  await appInitializer();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      theme: const CupertinoThemeData(
        brightness: Brightness.light,
      ),
      home: CupertinoPageScaffold(
        child: Center(
          child: CupertinoButton(
            onPressed: (){},
            child: Text("Click Me"),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/user-attachments/assets/1f9a8eb0-3f18-4171-8744-4cc7eacff5fc)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.3.1 24D70 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 16.2)
    ! CocoaPods 1.15.2 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.97.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by srivats22**
This PR addresses Issue number: 163840, where when hovering over a Cupertino button the mouse cursor wouldn't switch to clickable and there wasn't any option to configure it.

Adds Mouse cursor to CupertinoButton, CupertinoButton.Filled and CupertinoButton.Tinted

Fixes https://github.com/flutter/flutter/issues/163840
Part of https://github.com/flutter/flutter/issues/58192

Demo of the changes

https://github.com/user-attachments/assets/2e5d874e-cdfe-44bf-9710-bbbde99be3f7

Code snippet showing new behavior

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(
  // const Center(child: Text('Hello, world!', key: Key('title'), textDirection: TextDirection.ltr)),
  CupertinoApp(
    theme: const CupertinoThemeData(
      brightness: Brightness.light,
    ),
    home: Center(
      child: Column(
        spacing: 5.0,
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: <Widget>[
          CupertinoButton(
            onPressed: (){},
            child: const Text('Default Cursor'),
          ),
          CupertinoButton(
            onPressed: (){},
            mouseCursor: SystemMouseCursors.grab,
            child: const Text('Custom Cursor'),
          ),
          CupertinoButton.filled(
            onPressed: (){},
            mouseCursor: SystemMouseCursors.copy,
            child: const Text('Custom Cursor 2'),
          ),
          CupertinoButton.tinted(
            onPressed: (){},
            mouseCursor: SystemMouseCursors.help,
            child: const Text('Custom Cursor 2'),
          ),
        ],
      )
    ),
  ),
);
```

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by dkwingsmt** [comment]
@srivats22 I've pushed the code that uses a WidgetStateProperty default cursor to your branch. In short:
* The default cursor keeps the current behavior under all states.
* The `build` method parses `mouseCursor` by default and fall back to the default behavior.

File: packages/flutter/lib/src/cupertino/button.dart [hunk 1]
```diff
@@ -257,6 +260,12 @@ class CupertinoButton extends StatefulWidget {
   /// {@macro flutter.widgets.Focus.autofocus}
   final bool autofocus;
 
+  /// The cursor that will be shown when hovering over the button.
+  ///
+  /// If null, defaults to [SystemMouseCursors.click] on web and
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/cupertino/button.dart:265]: Can you follow https://github.com/flutter/flutter/pull/151788/files#diff-edc7ce14e5b80bcb5bdc49661ad33df8bd3ade5c903468e8cf39c5291d79228aR154 and mention that the cursor parses with only the `[WidgetState.disabled]` state? (No selected or focused state.)

**Comment by srivats22** [comment]
Thank you @dkwingsmt will keep this for reference so from next time I will use this if I am working with anything related to mouse Cursor

File: packages/flutter/test/cupertino/button_test.dart [hunk 2]
```diff
@@ -885,6 +885,90 @@ void main() {
...
+    );
+    // Get the center of the CupertinoButton to ensure the pointer is over it
+    final Offset buttonCenter = tester.getCenter(find.text('Tap Me'));
+    await gesture.addPointer(location: buttonCenter);
+    await tester.pumpAndSettle();
+
+    // Expect the custom cursor to be active when the mouse is over the button
+    expect(RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1), customCursor);
+  });
 }
```
Comment (dkwingsmt) [inline packages/flutter/test/cupertino/button_test.dart:972]: Can you follow https://github.com/flutter/flutter/pull/151788/files#diff-6c819d3ed61b4436b70dc3d4cbeac15e24bc3705d0c3acf7761e58bcece5cf29R509 and add a test for a `WidgetStateMouseCursor` that uses the disabled state? (again, no selected and focused states)

**Comment by dkwingsmt** [comment]
@victorsanni Can you verify my implementation and direction?

File: packages/flutter/lib/src/cupertino/button.dart (hunk 1 above)
Comment (srivats22) [reply packages/flutter/lib/src/cupertino/button.dart:265]: sure will update the comment and push it

**Comment by dkwingsmt** [comment]
@srivats22 Thank you for understanding. I think the WidgetStateProperty is needed because otherwise your newly added `mouseCursor` property wouldn't be able to control the diabled cursor, and if we ever wants to do it in the future it will be a breaking change.

File: packages/flutter/test/cupertino/button_test.dart (hunk 2 above)
Comment (srivats22) [reply packages/flutter/test/cupertino/button_test.dart:1049]: Resolved in recent PR

File: packages/flutter/lib/src/cupertino/button.dart (hunk 1 above)
Comment (srivats22) [reply packages/flutter/lib/src/cupertino/button.dart]: Resolved in recent PR

File: packages/flutter/lib/src/cupertino/button.dart [hunk 3]
```diff
@@ -257,6 +260,26 @@ class CupertinoButton extends StatefulWidget {
   /// {@macro flutter.widgets.Focus.autofocus}
   final bool autofocus;
 
+  /// The cursor for a mouse pointer when it enters or is hovering over the widget
+  ///
+  /// If [mouseCursor] is a [WidgetStateMouseCursor],
+  /// [WidgetStateProperty.resolve] is used for the following [WidgetState]:
+  /// * [WidgetState.pressed].
```
Comment (piedcipher) [inline packages/flutter/lib/src/cupertino/button.dart:267]:
```suggestion
  ///  * [WidgetState.pressed].
```

File: packages/flutter/lib/src/cupertino/button.dart [hunk 4]
```diff
@@ -257,6 +260,26 @@ class CupertinoButton extends StatefulWidget {
...
   final bool autofocus;
 
+  /// The cursor for a mouse pointer when it enters or is hovering over the widget
+  ///
+  /// If [mouseCursor] is a [WidgetStateMouseCursor],
+  /// [WidgetStateProperty.resolve] is used for the following [WidgetState]:
+  ///  * [WidgetState.pressed].
+  ///  * [WidgetState.hovered].
+  ///  * [WidgetState.focused].
+  ///  * [WidgetState.disabled].
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/cupertino/button.dart:270]:
```suggestion
  ///  * [WidgetState.disabled].
```

File: packages/flutter/lib/src/cupertino/button.dart [hunk 5]
```diff
@@ -257,6 +260,26 @@ class CupertinoButton extends StatefulWidget {
...
+  ///
+  /// If null, then [MouseCursor.defer] is used when the button is disabled.
+  /// When the button is enabled, [SystemMouseCursors.click] is used on Web
+  /// and [MouseCursor.defer] is used on other platformss
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/cupertino/button.dart:274]:
```suggestion
  /// and [MouseCursor.defer] is used on other platforms.
```

File: packages/flutter/test/cupertino/button_test.dart [hunk 6]
```diff
@@ -885,6 +885,167 @@ void main() {
...
+    // Get the center of the CupertinoButton to ensure the pointer is over it
+    final Offset buttonCenter = tester.getCenter(find.text('Tap Me'));
+    await gesture.addPointer(location: buttonCenter);
+    await tester.pumpAndSettle();
+
+    // Expect the custom cursor to be active when the mouse is over the button
+    expect(RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1), customCursor);
+  });
+
+  testWidgets('CupertinoButton.Tinted.mouseCursor behavior', (WidgetTester tester) async {
```
Comment (dkwingsmt) [inline packages/flutter/test/cupertino/button_test.dart:945]:
```suggestion
  testWidgets('CupertinoButton.tinted.mouseCursor behavior', (WidgetTester tester) async {
```

File: packages/flutter/test/cupertino/button_test.dart [hunk 7]
```diff
@@ -885,6 +885,167 @@ void main() {
...
+    // Get the center of the CupertinoButton to ensure the pointer is over it
+    final Offset buttonCenter = tester.getCenter(find.text('Tap Me'));
+    await gesture.addPointer(location: buttonCenter);
+    await tester.pumpAndSettle();
+
+    // Expect the custom cursor to be active when the mouse is over the button
+    expect(RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1), customCursor);
+  });
+
+  testWidgets('CupertinoButton.Filled.mouseCursor behavior', (WidgetTester tester) async {
```
Comment (dkwingsmt) [inline packages/flutter/test/cupertino/button_test.dart:917]:
```suggestion
  testWidgets('CupertinoButton.filled.mouseCursor behavior', (WidgetTester tester) async {
```

**Review by dkwingsmt — APPROVED** [review]
LGTM, thank you!

File: packages/flutter/lib/src/cupertino/button.dart [hunk 8]
```diff
@@ -257,6 +260,23 @@ class CupertinoButton extends StatefulWidget {
   /// {@macro flutter.widgets.Focus.autofocus}
   final bool autofocus;
 
+  /// The cursor for a mouse pointer when it enters or is hovering over the widget
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/button.dart:263]:
```suggestion
  /// The cursor for a mouse pointer when it enters or is hovering over the widget.
```

File: packages/flutter/lib/src/cupertino/button.dart [hunk 9]
```diff
@@ -500,4 +525,11 @@ class _CupertinoButtonState extends State<CupertinoButton> with SingleTickerProv
       ),
     );
   }
+
+  static final WidgetStateProperty<MouseCursor> _defaultCursor =
+      WidgetStateProperty.resolveWith<MouseCursor>((Set<WidgetState> states) {
+        return !states.contains(WidgetState.disabled) && kIsWeb
+            ? SystemMouseCursors.click
+            : MouseCursor.defer;
+      });
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/button.dart:534]: Wondering why this code block is after `build` instead of before.

Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/button.dart:534]: Also, why is it `static` instead of a getter?

File: packages/flutter/lib/src/cupertino/button.dart [hunk 10]
```diff
@@ -430,8 +450,13 @@ class _CupertinoButtonState extends State<CupertinoButton> with SingleTickerProv
           textStyle.fontSize != null ? textStyle.fontSize! * 1.2 : kCupertinoButtonDefaultIconSize,
     );
 
+    final Set<WidgetState> states = <WidgetState>{if (!enabled) WidgetState.disabled};
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/button.dart:453]: Since this is a button, shouldn't it be possible to also track the `pressed` state using the `_handleTapX` callbacks?

File: packages/flutter/lib/src/cupertino/button.dart (hunk 9 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/cupertino/button.dart:534]: I wrote this file for the author and can answer the questions.

> Wondering why this code block is after build instead of before.

I think we usually place static elements at the last.

> Also, why is it static instead of a getter?

A static member should be preferred over a getter since it doesn't need to be generated each time to be used.

File: packages/flutter/lib/src/cupertino/button.dart (hunk 10 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/cupertino/button.dart:453]: Yes it is, but I think we don't need to implement everything in this PR. For now we can only make the custom cursor change what's available currently (which only counts disabled or not).

File: packages/flutter/lib/src/cupertino/button.dart (hunk 9 above)
Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/button.dart:534]: > I think we usually place static elements at the last.

I searched through the framework code: https://github.com/search?q=repo%3Aflutter%2Fflutter+%2Fstatic+final+%28.*%29%3D%2F+path%3A%2F%5Epackages%5C%2Fflutter%5C%2Flib%5C%2Fsrc%5C%2F%2F&type=code

Typically `static final` variables were in the same place as State class instance variables, before any methods. And I couldn't find an instance where `build` wasn't the last method in a class.

Comment (dkwingsmt) [reply packages/flutter/lib/src/cupertino/button.dart:534]: Ok that makes sense. Thanks for searching. Shall we move it to after `  late bool isFocused;`?

File: packages/flutter/lib/src/cupertino/button.dart (hunk 10 above)
Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/button.dart:453]: @srivats22 can we file an issue to track adding a `pressed` state and possible other states?

Comment (srivats22) [reply packages/flutter/lib/src/cupertino/button.dart:453]: Sure will open a new issue and tag the issue to this PR...

if I can get more details on what needs to be addressed in that issue I can work on it as well

Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/button.dart:453]: The mouse cursor should track other `WidgetState`s alongside the `enabled` state. So other states like `focused`, `pressed`, etc. Except `hovered`, since the mouse cursor is only useful when the button is hovered.

Comment (srivats22) [reply packages/flutter/lib/src/cupertino/button.dart:453]: understood will open one and it can be assigned to me will work on it thank you

File: packages/flutter/lib/src/cupertino/button.dart [hunk 11]
```diff
@@ -257,6 +260,23 @@ class CupertinoButton extends StatefulWidget {
...
+  ///
+  /// If null, then [MouseCursor.defer] is used when the button is disabled.
+  /// When the button is enabled, [SystemMouseCursors.click] is used on Web
+  /// and [MouseCursor.defer] is used on other platforms.
+  ///
+  /// See also:
+  ///
+  ///  * [WidgetStateMouseCursor], a [MouseCursor] that implements
+  ///    [WidgetStateProperty] which is used in APIs that need to accept
+  ///    either a [MouseCursor] or a [WidgetStateProperty].
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/button.dart:277]: I wonder why the syntax highlighting works for line 275 but not line 276 and 277. Maybe the correct docimports are needed?

File: packages/flutter/test/cupertino/button_test.dart [hunk 12]
```diff
@@ -885,6 +885,167 @@ void main() {
...
+    final Offset buttonCenter = tester.getCenter(find.text('Tap Me'));
+    await gesture.addPointer(location: buttonCenter);
+    await tester.pumpAndSettle();
+
+    // Expect the custom cursor to be active when the mouse is over the button
+    expect(RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1), customCursor);
+  });
+
+  testWidgets('CupertinoButton.mouseCursor in disabled state', (WidgetTester tester) async {
+    const SystemMouseCursor customCursor = SystemMouseCursors.forbidden;
```
[the remark this answers is not in the document]
Comment (victorsanni) [reply packages/flutter/test/cupertino/button_test.dart:974]: So to test other `WidgetState`s that are added in the future, these tests would just add the added state and trigger the action that would activate that state.

File: packages/flutter/lib/src/cupertino/button.dart (hunk 9 above)
Comment (srivats22) [reply packages/flutter/lib/src/cupertino/button.dart]: addressed in recent pr thanks

File: packages/flutter/lib/src/cupertino/button.dart (hunk 11 above)
Comment (srivats22) [reply packages/flutter/lib/src/cupertino/button.dart:277]: let me double check and will push one more if format changes... will wait for current builds to finish if it fails for format will fix it (dont want to push too many)

File: packages/flutter/test/cupertino/button_test.dart (hunk 12 above)
[the remark this answers is not in the document]
Comment (srivats22) [reply packages/flutter/test/cupertino/button_test.dart:974]: Oh ok so I will add tests similar to this pr:

https://github.com/flutter/flutter/pull/151788/files#diff-6c819d3ed61b4436b70dc3d4cbeac15e24bc3705d0c3acf7761e58bcece5cf29R509

File: packages/flutter/test/cupertino/button_test.dart [hunk 13]
```diff
@@ -941,8 +941,75 @@ void main() {
...
+    await tester.pump();
+    await gesture.moveTo(tester.getCenter(find.byType(CupertinoButton)));
+    expect(
+      RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1),
+      SystemMouseCursors.basic,
+    );
+    await gesture.removePointer();
+
+    // Test disabled state mouse cursor
+    await tester.pumpWidget(buildButton(enabled: false, cursor: SystemMouseCursors.forbidden));
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/button_test.dart:974]: If the goal here is to test that the mouse cursor is resolved in different widget states, why is the cursor passed here a MouseCursor instead of _ButtonMouseCursor?

File: packages/flutter/test/cupertino/button_test.dart [hunk 14]
```diff
@@ -941,8 +941,75 @@ void main() {
...
+    await tester.pump();
+    await gesture.moveTo(tester.getCenter(find.byType(CupertinoButton)));
+    expect(
+      RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1),
+      SystemMouseCursors.forbidden,
+    );
+    await gesture.removePointer();
+
+    // Test clicked state mouse cursor
+    await tester.pumpWidget(buildButton(enabled: true, cursor: SystemMouseCursors.click));
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/button_test.dart:985]: Same here. But currently only enabled/disabled states are resolved so I'm not sure this entire block should exist. There is no 'clicked' state.

File: packages/flutter/test/cupertino/button_test.dart [hunk 15]
```diff
@@ -941,8 +941,75 @@ void main() {
     await gesture.up();
     expect(value, isTrue);
   });
+
+  testWidgets('Mouse cursor resolves in pressed/disabled states', (WidgetTester tester) async {
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/button_test.dart:945]: The mouse cursor doesn't resolve the pressed state yet. Maybe change to enabled/disabled states?

File: packages/flutter/test/cupertino/button_test.dart [hunk 16]
```diff
@@ -941,8 +941,75 @@ void main() {
...
 }
+
+class _ButtonMouseCursor extends WidgetStateMouseCursor {
+  const _ButtonMouseCursor();
+
+  @override
+  MouseCursor resolve(Set<WidgetState> states) {
+    if (states.contains(WidgetState.hovered) || states.contains(WidgetState.pressed)) {
+      return SystemMouseCursors.click;
+    }
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/button_test.dart:1006]: This is currently a no-op/dead code since those states are not resolved.

Comment (srivats22) [reply packages/flutter/test/cupertino/button_test.dart:1006]: Would this code be better based on the comments just want to confirm before I push the changes the first test and the last test are the same and I can remove it if required:

```dart
testWidgets('Mouse cursor resolves in enabled/disabled states', (WidgetTester tester) async {
    Widget buildButton({required bool enabled, MouseCursor? cursor}) {
      return CupertinoApp(
        home: Center(
          child: CupertinoButton(
            onPressed: enabled ? () {} : null,
            mouseCursor: cursor,
            child: const Text('Tap Me'),
          ),
        ),
      );
    }

    // Test default mouse cursor
    final TestGesture gesture = await tester.createGesture(
      kind: PointerDeviceKind.mouse,
      pointer: 1,
    );
    await tester.pumpWidget(buildButton(enabled: true, cursor: const _ButtonMouseCursor()));
    await gesture.addPointer(location: tester.getCenter(find.byType(CupertinoButton)));
    await tester.pump();
    await gesture.moveTo(tester.getCenter(find.byType(CupertinoButton)));
    expect(
      RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1),
      SystemMouseCursors.basic,
    );
    await gesture.removePointer();

    // Test disabled state mouse cursor
    await tester.pumpWidget(buildButton(enabled: false, cursor: const _ButtonMouseCursor()));
    await gesture.addPointer(location: tester.getCenter(find.byType(CupertinoButton)));
    await tester.pump();
    await gesture.moveTo(tester.getCenter(find.byType(CupertinoButton)));
    expect(
      RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1),
      SystemMouseCursors.forbidden,
    );
    await gesture.removePointer();

    // Test clicked state mouse cursor
    await tester.pumpWidget(buildButton(enabled: true, cursor: const _ButtonMouseCursor()));
    await gesture.addPointer(location: tester.getCenter(find.byType(CupertinoButton)));
    await tester.pumpAndSettle();
    expect(
      RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1),
      SystemMouseCursors.basic,
    );
  });
```

File: packages/flutter/test/cupertino/button_test.dart [hunk 17]
```diff
@@ -941,8 +941,75 @@ void main() {
...
+            onPressed: enabled ? () {} : null,
+            mouseCursor: cursor,
+            child: const Text('Tap Me'),
+          ),
+        ),
+      );
+    }
+
+    // Test default mouse cursor
+    final TestGesture gesture = await tester.createGesture(
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/button_test.dart:959]: Remove the gesture at the end of the test (`gesture.up()`).

File: packages/flutter/test/cupertino/button_test.dart [hunk 18]
```diff
@@ -941,8 +941,75 @@ void main() {
...
+    await gesture.removePointer();
+
+    // Test clicked state mouse cursor
+    await tester.pumpWidget(buildButton(enabled: true, cursor: const _ButtonMouseCursor()));
+    await gesture.addPointer(location: tester.getCenter(find.byType(CupertinoButton)));
+    await tester.pumpAndSettle();
+    expect(
+      RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1),
+      SystemMouseCursors.basic,
+    );
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/button_test.dart:991]: I'm still wondering what the difference is between this and the default. Is this meant to check for the `pressed` state? But this PR doesn't already handle that state.

File: packages/flutter/test/cupertino/button_test.dart [hunk 19]
```diff
@@ -941,8 +941,75 @@ void main() {
...
 Widget boilerplate({required Widget child}) {
   return Directionality(textDirection: TextDirection.ltr, child: Center(child: child));
 }
+
+class _ButtonMouseCursor extends WidgetStateMouseCursor {
+  const _ButtonMouseCursor();
+
+  @override
+  MouseCursor resolve(Set<WidgetState> states) {
+    if (states.contains(WidgetState.hovered) || states.contains(WidgetState.pressed)) {
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/button_test.dart:1004]: Mouse cursors are always `hovered`, and this PR doesn't handle the `pressed` state. Should this if-block exist?

File: packages/flutter/test/cupertino/button_test.dart (hunk 18 above)
Comment (srivats22) [reply packages/flutter/test/cupertino/button_test.dart:991]: Understood... so should I remove it all together? or work on addressing the other states? open to suggestions

File: packages/flutter/test/cupertino/button_test.dart (hunk 19 above)
Comment (srivats22) [reply packages/flutter/test/cupertino/button_test.dart:1004]: so we can just limit it to these 2 then:

```dart
if (states.contains(WidgetState.disabled)) {
      return SystemMouseCursors.forbidden;
}
return SystemMouseCursors.basic;
```

File: packages/flutter/test/cupertino/button_test.dart (hunk 18 above)
Comment (victorsanni) [reply packages/flutter/test/cupertino/button_test.dart:991]: I'd remove for this PR then add new tests for other states when working on them in subsequent PRs.

Comment (srivats22) [reply packages/flutter/test/cupertino/button_test.dart:991]: Thank you so final test would be just these 2:

```dart
    final TestGesture gesture = await tester.createGesture(
      kind: PointerDeviceKind.mouse,
      pointer: 1,
    );
    await tester.pumpWidget(buildButton(enabled: true, cursor: const _ButtonMouseCursor()));
    await gesture.addPointer(location: tester.getCenter(find.byType(CupertinoButton)));
    await tester.pump();
    await gesture.moveTo(tester.getCenter(find.byType(CupertinoButton)));
    expect(
      RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1),
      SystemMouseCursors.basic,
    );
    await gesture.removePointer();

    // Test disabled state mouse cursor
    await tester.pumpWidget(buildButton(enabled: false, cursor: const _ButtonMouseCursor()));
    await gesture.addPointer(location: tester.getCenter(find.byType(CupertinoButton)));
    await tester.pump();
    await gesture.moveTo(tester.getCenter(find.byType(CupertinoButton)));
    expect(
      RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1),
      SystemMouseCursors.forbidden,
    );
    await gesture.removePointer();
```

File: packages/flutter/test/cupertino/button_test.dart (hunk 17 above)
Comment (victorsanni) [reply packages/flutter/test/cupertino/button_test.dart:959]: If the gesture is started (so `tester.startGesture`), then it would be down (and need a `gesture.up`), but since it is just created, I think this should be fine.

File: packages/flutter/test/cupertino/button_test.dart (hunk 18 above)
Comment (srivats22) [reply packages/flutter/test/cupertino/button_test.dart]: addressed making as resolved

**Review by victorsanni — APPROVED** [review]
LGTM! Thanks for the PR.
