### PR TITLE
Fix multiple calls to Slider's onChanged.

### LINKED ISSUE #143524: Slider's onChanged callback is fired several times under certain condition
### Steps to reproduce

1. Run the provided code sample;
2. Place the cursor/finger between the thumb and previous division (exactly between, as seen on the attached video)
3. Drag the cursor/finger to the left with a fast swing in such a way that the value is changed by 1;
4. Inspect the output in the debug console.

### Expected results

Well, it's pretty straightforward. onChanged callback should only be fired once. That is a serious bug that has been there, idk, forever?

### Actual results

onChanged callback fired twice under certain condition.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: SliderBug(),
        ),
      ),
    );
  }
}

class SliderBug extends StatefulWidget {
  const SliderBug({super.key});

  @override
  State<SliderBug> createState() => _SliderBugState();
}

class _SliderBugState extends State<SliderBug> {
  double sliderValue = 10;
  final double minValue = 2;
  final double maxValue = 12;
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Text('${sliderValue.round()}'),
        Slider(
          min: 2,
          max: 12,
          divisions: (maxValue - minValue).round(),
          value: sliderValue,
          onChanged: (value) {
            print('onChanged');
            setState(() {
              sliderValue = value;
            });
          },
        ),
      ],
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Here is the video:

https://github.com/flutter/flutter/assets/54116985/80badfcc-191c-4f23-8368-ffc708d2764c

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1.2 23B92 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.86.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by yiiim**
Fixes #143524 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/slider_test.dart [hunk 1]
```diff
@@ -4251,4 +4251,34 @@ void main() {
       );
     });
   });
+
```
Comment (TahaTesser) [inline packages/flutter/test/material/slider_test.dart:4254]:
```suggestion

  // This is a regression test for https://github.com/flutter/flutter/issues/143524.
```

File: packages/flutter/test/material/slider_test.dart [hunk 2]
```diff
@@ -4251,4 +4251,34 @@ void main() {
...
+  testWidgets('Slider.onChanged is called only once', (WidgetTester tester) async {
```
Comment (TahaTesser) [inline packages/flutter/test/material/slider_test.dart:4255]:
```suggestion
  testWidgets('Slider.onChanged with divisions is called only once', (WidgetTester tester) async {
```

File: packages/flutter/test/material/slider_test.dart [hunk 3]
```diff
@@ -4251,4 +4251,34 @@ void main() {
...
+                value: 0,
+                onChanged: (double newValue) {
+                  onChangeCallbackCount++;
+                },
+              ),
+            );
+          }),
+        ),
+      ),
+    );
```
Comment (TahaTesser) [inline packages/flutter/test/material/slider_test.dart:4276]:
```suggestion
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Center(
            child: Slider(
              max: 5,
              divisions: 5,
              value: 0,
              onChanged: (double newValue) {
                onChangeCallbackCount++;
              },
            ),
          ),
        ),
      ),
    );

```

File: packages/flutter/test/material/slider_test.dart [hunk 4]
```diff
@@ -4251,4 +4251,34 @@ void main() {
...
+    final TestGesture gesture = await tester.startGesture(tester.getTopLeft(find.byType(Slider)));
+    await tester.pump(kLongPressTimeout);
+    await gesture.moveBy(Offset(screenWidth / 5, 0));
+    await gesture.moveBy(const Offset(1, 0));
+    await gesture.moveBy(const Offset(1, 0));
```
Comment (TahaTesser) [inline packages/flutter/test/material/slider_test.dart:4281]:
```suggestion
    await gesture.moveBy(const Offset(160.0, 0.0));
    await gesture.moveBy(const Offset(1.0, 0.0));
    await gesture.moveBy(const Offset(1.0, 0.0));
```

**Review by TahaTesser — CHANGES_REQUESTED** [review]
Nice fix, thanks for the contribution.

File: packages/flutter/test/material/slider_test.dart (hunk 3 above)
Comment (TahaTesser) [reply packages/flutter/test/material/slider_test.dart:4276]: We can omit `LayoutBuilder` layout and add a new line at the bottom. between this and `gesture` line.

File: packages/flutter/test/material/slider_test.dart (hunk 2 above)
Comment (TahaTesser) [reply packages/flutter/test/material/slider_test.dart:4255]: Since the fix is for discrete `Slider`.

File: packages/flutter/lib/src/material/slider.dart [hunk 5]
```diff
@@ -612,6 +612,11 @@ class _SliderState extends State<Slider> with TickerProviderStateMixin {
 
   bool _dragging = false;
 
+  // For discrete sliders, [_handleChanged] might receive the same value
```
Comment (TahaTesser) [inline packages/flutter/lib/src/material/slider.dart:615]: The variable and _handleChanged are private so we don't need the brackets.

File: packages/flutter/lib/src/material/slider.dart [hunk 6]
```diff
@@ -612,6 +612,11 @@ class _SliderState extends State<Slider> with TickerProviderStateMixin {
...
+  // multiple times. To avoid calling [widget.onChanged] repeatedly, the
```
Comment (TahaTesser) [inline packages/flutter/lib/src/material/slider.dart:616]: Same here

**Review by TahaTesser — CHANGES_REQUESTED** [review]

**Review by TahaTesser — APPROVED** [review]
LGTM!

**Comment by TahaTesser** [comment]
We'll need a second review from @Piinks before we land this.

**Review by Piinks — COMMENTED** [review]
Flutter_LGTM

Thank you both!
