### PR TITLE
Material banner updates

### LINKED ISSUE #89979: MaterialBanner shows behind the statusbar when there is no AppBar in the scaffold
## Steps to Reproduce

1. Use ScaffoldMessenger.of(context).showMaterialBanner(banner) to show a banner from a Scaffold which doesn't have an appbar 
**Expected results:** 
I expect to see the MaterialBanner below the statusbar.

**Actual results:** 
This banner is shown behind the Appbar(The screenshot is taken from a Pixel 4 xl emulator)
image

<details>

```console
[✓] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.22000.184], locale en-US)
    • Flutter version 2.5.0 at D:\programming\flutter\installs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (5 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\Android
    • Platform android-31, build-tools 31.0.0
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at C:\Users\mdism\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • LDN LX2 (mobile)  • 192.168.0.158:5555 • android-arm64  • Android 8.0.0 (API 26)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.22000.184]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 93.0.961.44

• No issues found!
```
</details>

### PR DESCRIPTION
**Pull request by Calamity210**
This PR better aligns the MaterialBanner with its [material specs](https://material.io/components/banners).

- Changed animation to slide instead of fading in to place.
- Added elevation.
- The Scaffold's body is now pushed down by the MaterialBanner if its elevation is 0.
- Wrapped in a SafeArea to avoid system intrusions at the top of the screen.

https://user-images.githubusercontent.com/50059339/134091114-317fb8e2-318f-480f-930e-22966f8b84ad.mp4

#60024
Fixes #89979

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/banner.dart [hunk 1]
```diff
@@ -120,6 +123,14 @@ class MaterialBanner extends StatefulWidget {
   /// Typically this is a list of [TextButton] widgets.
   final List<Widget> actions;
 
+  /// The z-coordinate at which to place the material banner. This controls the size of the shadow below the material banner.
+  ///
+  /// Defines the banner's [Material.elevation].
+  ///
+  /// If this property is null, then [MaterialBannerThemeData.elevation] of [ThemeData.bannerTheme] is used, if that is also null, the default value is 0.
+  /// If the elevation is 0, the Scaffold's body will be pushed down by the MaterialBanner.
```
Comment (rami-a) [inline packages/flutter/lib/src/material/banner.dart:131]: We generally keep documentation to 80 chars per line. Could you rework this to match that?

File: packages/flutter/lib/src/material/banner.dart [hunk 2]
```diff
@@ -270,42 +282,50 @@ class _MaterialBannerState extends State<MaterialBanner> {
...
-                  ),
-                Expanded(
-                  child: DefaultTextStyle(
-                    style: textStyle!,
-                    child: widget.content,
-                  ),
+    Widget materialBanner = SafeArea(
+      top: true,
+      child: Container(
+        margin: EdgeInsets.only(bottom: elevation > 0 ? 10.0 : 0.0),
```
Comment (rami-a) [inline packages/flutter/lib/src/material/banner.dart:296]: Is this necessary? I think it should be left to the scaffold body to inset its own content appropriately

File: packages/flutter/lib/src/material/banner.dart [hunk 3]
```diff
@@ -270,42 +282,50 @@ class _MaterialBannerState extends State<MaterialBanner> {
...
+                  ],
                 ),
-                if (isSingleRow)
-                  buttonBar,
-              ],
-            ),
+              ),
+              if (!isSingleRow)
+                buttonBar,
+              const Divider(height: 0),
```
Comment (rami-a) [inline packages/flutter/lib/src/material/banner.dart:325]: I wonder if the Divider should be conditional on the elevation. Maybe if elevation>0 then we don't have a divider, since it seems weird to have both

File: packages/flutter/lib/src/material/banner_theme.dart [hunk 4]
```diff
@@ -2,6 +2,8 @@
 // Use of this source code is governed by a BSD-style license that can be
 // found in the LICENSE file.
 
+import 'dart:ui';
```
Comment (rami-a) [inline packages/flutter/lib/src/material/banner_theme.dart:5]: Why is this import needed?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 5]
```diff
@@ -866,7 +872,8 @@ class _BodyBuilder extends StatelessWidget {
           : metrics.padding.bottom;
 
         final double top = extendBodyBehindAppBar
-          ? math.max(metrics.padding.top, bodyConstraints.appBarHeight)
+          ? math.max(metrics.padding.top,
+            bodyConstraints.appBarHeight + bodyConstraints.materialBannerHeight)
```
Comment (rami-a) [inline packages/flutter/lib/src/material/scaffold.dart:876]: Fix the indentation to something like:

```suggestion
          ? math.max(metrics.padding.top,
              bodyConstraints.appBarHeight + bodyConstraints.materialBannerHeight)
```

File: packages/flutter/lib/src/material/scaffold.dart [hunk 6]
```diff
@@ -2927,8 +2933,13 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
       );
     }
 
+    bool extendBodyBehindMaterialBanner = false;
     // MaterialBanner set by ScaffoldMessenger
     if (_messengerMaterialBanner != null) {
+      final MaterialBannerThemeData bannerTheme = MaterialBannerTheme.of(context);
+      final double elevation = _messengerMaterialBanner?._widget.elevation ?? bannerTheme.elevation ?? 0.0;
+      extendBodyBehindMaterialBanner = elevation != 0;
```
Comment (rami-a) [inline packages/flutter/lib/src/material/scaffold.dart:2941]: Nit:
```suggestion
      extendBodyBehindMaterialBanner = elevation != 0.0;
```

**Review by rami-a — COMMENTED** [review]
Great update to the Material Banner, just left a few comments/remarks

File: packages/flutter/lib/src/material/banner.dart (hunk 2 above)
Comment (Calamity210) [reply packages/flutter/lib/src/material/banner.dart:296]: This shouldn't affect the Scaffold body actually, its only to allow the Banners shadow to show.

You'll find widgets such as the snackbar doing something [similar](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/snack_bar.dart#L554) as well

File: packages/flutter/lib/src/material/banner_theme.dart (hunk 4 above)
Comment (Calamity210) [reply packages/flutter/lib/src/material/banner_theme.dart:5]: It's needed for lerpDouble.

I've changed it to `import 'dart:ui' show lerpDouble;`

File: packages/flutter/lib/src/material/banner.dart [hunk 7]
```diff
@@ -120,6 +123,16 @@ class MaterialBanner extends StatefulWidget {
...
   final List<Widget> actions;
 
+  /// The z-coordinate at which to place the material banner.
+  /// This controls the size of the shadow below the material banner.
+  ///
+  /// Defines the banner's [Material.elevation].
+  ///
+  /// If this property is null, then [MaterialBannerThemeData.elevation] of
+  /// [ThemeData.bannerTheme] is used, if that is also null, the default value is 0.
+  /// If the elevation is 0, the Scaffold's body will be pushed down by the MaterialBanner.
```
Comment (rami-a) [inline packages/flutter/lib/src/material/banner.dart:133]: Nit: Modify this sentence with something like
```suggestion
  /// If the elevation is 0, the [Scaffold]'s body will be pushed down by the MaterialBanner when used with [ScaffoldMessenger].
```

File: packages/flutter/lib/src/material/banner.dart (hunk 2 above)
Comment (Calamity210) [reply packages/flutter/lib/src/material/banner.dart:298]: Same with the SafeArea insets, the MaterialBanner should be the one to handle that. The AppBar is a [perfect example](https://github.com/flutter/flutter/blob/ffb2ecea52/packages/flutter/lib/src/material/app_bar.dart#L1082) for this.

**Comment by Calamity210** [comment]
Thanks, I've left comment on some of the remarks. The rest should be resolved though

File: packages/flutter/lib/src/material/banner.dart [hunk 8]
```diff
@@ -120,6 +123,16 @@ class MaterialBanner extends StatefulWidget {
   /// Typically this is a list of [TextButton] widgets.
   final List<Widget> actions;
 
+  /// The z-coordinate at which to place the material banner.
+  /// This controls the size of the shadow below the material banner.
```
Comment (rami-a) [inline packages/flutter/lib/src/material/banner.dart:127]: Nit: We always put a new line between the first sentence and any other documentation for a property
```suggestion
  ///
  /// This controls the size of the shadow below the material banner.
```

**Review by rami-a — APPROVED** [review]
Tested it out and it looks great! Just a couple minor doc nits and then this should be good to merge!

**Comment by Calamity210** [comment]
Sounds good, Ive applied the suggestions

File: packages/flutter/lib/src/material/banner.dart [hunk 9]
```diff
@@ -120,6 +123,17 @@ class MaterialBanner extends StatefulWidget {
...
 
+  /// The z-coordinate at which to place the material banner.
+  ///
+  /// This controls the size of the shadow below the material banner.
+  ///
+  /// Defines the banner's [Material.elevation].
+  ///
+  /// If this property is null, then [MaterialBannerThemeData.elevation] of
+  /// [ThemeData.bannerTheme] is used, if that is also null, the default value is 0.
+  /// If the elevation is 0, the [Scaffold]'s body will be pushed down by the MaterialBanner when used with [ScaffoldMessenger].
```
Comment (rami-a) [inline packages/flutter/lib/src/material/banner.dart:134]: Sorry, I forgot to use the 80 chars in my own suggestion, should be:

```suggestion
  /// If the elevation is 0, the [Scaffold]'s body will be pushed down by the
  /// MaterialBanner when used with [ScaffoldMessenger].
```

Comment (Calamity210) [reply packages/flutter/lib/src/material/banner.dart]: 😅 Looks good

**Comment by rami-a** [comment]
Looks good to me now! Will merge once all checks pass :)

**Comment by rami-a** [comment]
Hmm looks like this breaks some internal tests, let me investigate and see what's going on

**Comment by Calamity210** [comment]
Yeah, I'm assuming its the color thats breaking it([I had moved it from the Container to the Material](https://github.com/flutter/flutter/blob/62b16d23d19c454cf22c3ecf1e49933661e4781b/packages/flutter/lib/src/material/banner.dart#L301)).

**Comment by rami-a** [comment]
Looks like the breakages are acceptable, merging now
