### PR TITLE
Positioning IME bars on iOS

### LINKED ISSUE #9344: Multi-step input candidate view position incorrect when using physical keyboard
## Steps to Reproduce

1. Open *Flutter Gallery* and open the *Text Fields* demo.
1. Using an iPad with a physical keyboard attached, tap on the *Name* field.
1. Switch to Japanese text input and enter some text (e.g., `kannji`).

The conversion candidates view is located at 0,0 instead of near the composing region.

## Current Flutter behaviour
img_1484

## Expected behaviour (Google Inbox)
img_1485

## Flutter Doctor

Running a local engine with iOS text editing patches applied to enable multi-stage text entry. Base Flutter SDK is:

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision c12c019bcc (6 hours ago), 2017-04-11 13:48:04 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.6
```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

Engine: https://github.com/flutter/engine/pull/19929

Keep sending marked text rect / caret rect information for the iOS text input plugin to consume.
Turning this into a real PR when https://github.com/flutter/flutter/pull/61940 is merged .

ime

## Related Issues

Depends on https://github.com/flutter/flutter/pull/61940
Fixes https://github.com/flutter/flutter/issues/9344

## Tests

I added the following tests:

- the "setMarkedTextRect" group

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

### CODE REVIEW

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -2165,6 +2166,29 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+      Rect composingRect = renderEditable.getRectForComposingRange(composingRange);
+      // Send the caret location instead if there's no marked text yet.
+      if (composingRect == null) {
+        assert(!composingRange.isValid || composingRange.isCollapsed);
+        final int offset = composingRange.isValid ? composingRange.start : 0;
+        composingRect = renderEditable.getLocalRectForCaret(TextPosition(offset: offset));
+      }
+      assert(composingRect != null);
+      _textInputConnection.setComposingRect(composingRect);
+      SchedulerBinding.instance
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:2187]: Why is a 1 frame delay needed here?

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 2]
```diff
@@ -3101,6 +3125,107 @@ void main() {
...
+      (WidgetTester tester) async {
+        controller.value = TextEditingValue(text: 'a' * 100);
+        await tester.pumpWidget(builder());
+        await tester.showKeyboard(find.byType(EditableText));
+
+        expect(log, contains(
+          matchesMethodCall(
+            'TextInput.setMarkedTextRect',
+            args: allOf(
+              // No composing text so the width should not be too wide becomes
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:3174]:
```suggestion
              // No composing text so the width should not be too wide because
```

**Review by justinmc — APPROVED** [review]
LGTM, super excited for this.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2187]: The information is sent to the platform every frame if needed.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -2165,6 +2166,29 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     }
   }
 
+  // Sends the current composing rect to the iOS text input plugin via the text
+  // input channel. We need to keep sending the information even if no text is
+  // currently marked, as the information usually lags behind. The text input
+  // plugin needs to estimate the composing rect based on the latest caret rect,
```
Comment (GaryQian) [inline packages/flutter/lib/src/widgets/editable_text.dart:2172]: Can this lag cause jitter when the true information is received? 1 frame swapping between an estimate and true info may be a source of jank.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 4]
```diff
@@ -1547,6 +1547,35 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+    assert(constraints != null);
+    if (!range.isValid || range.isCollapsed)
+      return null;
+    _layoutText(minWidth: constraints.minWidth, maxWidth: constraints.maxWidth);
+
+    final List<ui.TextBox> boxes = _textPainter.getBoxesForSelection(
+      TextSelection(baseOffset: range.start, extentOffset: range.end),
+    );
+
+    final ui.TextBox firstBox = boxes.first;
```
Comment (GaryQian) [inline packages/flutter/lib/src/rendering/editable.dart:1568]: For multiline text, first and last may not get you the bounding boxes you expect for the left and right positions

Comment (GaryQian) [reply packages/flutter/lib/src/rendering/editable.dart:1568]: We should add a test for this case as well.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2172]: The "true" information does not trigger a UI update of any sort when it's sent to the platform. It will be used as an estimate the next time iOS requests this information.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 4 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:1568]: Could you elaborate a bit on this? I would expect the marked text to be continuous and has a consistent writing direction, because it's produced by the same IME. Is it because the text within the given `TextRange` could be using different fonts so they might be grouped in different `TextBox`es even if they are on the same line?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:1568]: I guess the line can have more than 1 runs.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart]: updated

**Comment by LongCatIsLooong** [comment]
@GaryQian @justinmc updated. Should be ready for review now.

File: packages/flutter/test/rendering/editable_test.dart [hunk 5]
```diff
@@ -1003,6 +1003,56 @@ void main() {
...
+      textSelectionDelegate: delegate,
+      startHandleLayerLink: LayerLink(),
+      endHandleLayerLink: LayerLink(),
+    );
+
+    test('returns null when no composing range', () {
+      editable.text = const TextSpan(text: '123');
+      editable.layout(const BoxConstraints.tightFor(width: 200));
+
+      // invalid range.
```
Comment (justinmc) [inline packages/flutter/test/rendering/editable_test.dart:1023]:
```suggestion
      // Invalid range.
```

File: packages/flutter/test/rendering/editable_test.dart [hunk 6]
```diff
@@ -1003,6 +1003,56 @@ void main() {
...
+      expect(editable.getRectForComposingRange(const TextRange(start: -1, end: 2)), isNull);
+      // collapsed range.
```
Comment (justinmc) [inline packages/flutter/test/rendering/editable_test.dart:1025]:
```suggestion
      // Collapsed range.
```

**Review by justinmc — APPROVED** [review]
LGTM 👍

**Review by GaryQian — APPROVED** [review]
LGTM, thanks!

**Comment by LongCatIsLooong** [comment]
Waiting for the release to be cut.

**Comment by skia-gold** [comment]
Gold has detected about 3 untriaged digest(s) on patchset 16.
View them at https://flutter-gold.skia.org/cl/github/61981

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 7]
```diff
@@ -2304,7 +2328,7 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
   ///
   /// This property is typically used to notify the renderer of input gestures
   /// when [RenderEditable.ignorePointer] is true.
-  RenderEditable? get renderEditable => _editableKey.currentContext!.findRenderObject() as RenderEditable?;
+  RenderEditable get renderEditable => _editableKey.currentContext!.findRenderObject()! as RenderEditable;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:2331]: Nice way of getting rid of all of the exclamation marks elsewhere in the file.  I'm still figuring out all of the NNBD stuff but it's looking pretty slick.

**Review by justinmc — APPROVED** [review]
New changes LGTM 👍
