### PR TITLE
Remove chmod to make Flutter framework headers unwritable

### LINKED ISSUE #40146: `flutter run` failed due to 'Permission denied' when replacing signature of 'Flutter.framework' in module-type Flutter project
## Steps to Reproduce

1. Upgrade flutter to 1.9.1+hotfix.2
2. Run `flutter create -t module --org com.test test1`
3. Enter the `test1` project: `cd test1` 
4. Start the ios simulator
5. Run `flutter run`, everything works fun at this time.
6. Add the plugin `device_info` in pubspec.yaml:
```
dependencies:
  device_info: ^0.4.0
```
7. Run `flutter packages get`
8. Run `flutter run`... failed!

Or clone the test project: https://github.com/yrom/test1
1. git clone https://github.com/yrom/test1.git
2. cd test1
3. flutter packages get
4. flutter run

## Logs

```
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running pod install...                                              0.9s
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           5.3s
 └─Compiling, linking and signing...                         2.3s
Xcode build done.                                            9.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    mkdir -p /Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
    rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter
    "- Modules" "/Users/yrom/Downloads/test1/.ios/Pods/../Flutter/engine/Flutter.framework"
    "/Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks"
    building file list ... done
    Flutter.framework/
    Flutter.framework/Flutter
    Flutter.framework/Info.plist
    Flutter.framework/icudtl.dat
    Flutter.framework/_CodeSignature/
    Flutter.framework/_CodeSignature/CodeResources

    sent 94440045 bytes  received 120 bytes  62960110.00 bytes/sec
    total size is 94428117  speedup is 1.00
    Stripped /Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework/Flutter of architectures: armv7 arm64
    Code Signing /Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework with Identity -
    /usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements
    '/Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework'
    /Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework: replacing existing signature
    /Users/yrom/Downloads/test1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework: Permission denied
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build systemnote: Planning buildnote: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.
```

Check out the full verbose log file: https://raw.githubusercontent.com/yrom/test1/master/1.log 

Flutter doctor: 
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.2 at /Users/yrom/Library/flutter
    • Framework revision 2d2a1ffec9 (3 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

...

[✓] Connected device (1 available)
    • iPhone Xʀ • 00D207ED-8863-48FA-ACE7-061D13525B03 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

```

### PR DESCRIPTION
**Pull request by jmagman**
## Description

I believe code signing issues are being manifested as permission errors on these files.  Remove the chmod--it's become more problematic than helpful (it was trying to give a gentle hint to not edit those header files) and is hiding potentially actionable code signing error messages.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/40146.
Also see https://github.com/flutter/flutter/issues/39507.
Originally introduced with https://github.com/flutter/flutter/pull/8748

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

File: packages/flutter_tools/bin/xcode_backend.sh [hunk 1]
```diff
@@ -142,14 +142,10 @@ BuildApp() {
     mkdir "${derived_dir}/engine"
     RunCommand cp -r -- "${flutter_podspec}" "${derived_dir}/engine"
     RunCommand cp -r -- "${flutter_framework}" "${derived_dir}/engine"
-    # Make headers, plists, and modulemap files read-only to discourage editing.
-    RunCommand find "${derived_dir}/engine/Flutter.framework" -type f \( -name '*.h' -o -name '*.modulemap' -o -name '*.plist' \) -exec chmod a-w "{}" \;
```
Comment (zanderso) [inline packages/flutter_tools/bin/xcode_backend.sh]: Could we prepend a warning message onto the file if there isn't one there already? Like:
```
... -exec cat <(echo "DO NOT EDIT") "{}" \;
```
Or maybe put a message there directly in the engine repo.

**Comment by cbracken** [comment]
Post-submit lgtm. It's worth noting that this was less a gentle hint, and more us spending a fairly large amount of time dealing with confusing bug reports that we eventually got traced to developers having unintentionally edited the headers in ways that caused compile errors (typically through jump to header in Xcode then accidentally typing/deleting things).

If this is causing issues with code signing though, an alternative would be to check for changes in the tool (e.g. verify shas or check diffs against the SDK version, etc.). I'm not super convinced that adding "DO NOT EDIT" will solve the issue (though it can't hurt!) since several of these turned out to be developers who could verify the headers had diffs, but had no recollection of editing them. Maybe accidental keypresses or something.

**Review by cbracken — COMMENTED** [review]
LGTM!

It's worth noting that this was less a gentle hint, and more us spending a fairly large amount of time dealing with confusing bug reports that we eventually got traced to developers having unintentionally edited the headers in ways that caused compile errors (typically through jump to header in Xcode then accidentally typing/deleting things).

If this is causing issues with code signing though, an alternative would be to check for changes in the tool (e.g. verify shas or check diffs against the SDK version, etc.). I'm not super convinced that adding "DO NOT EDIT" will solve the issue (though it can't hurt!) since several of these turned out to be developers who could verify the headers had diffs, but had no recollection of editing them. Maybe accidental keypresses or something.

**Comment by jmagman** [comment]
> LGTM!
> 
> It's worth noting that this was less a gentle hint, and more us spending a fairly large amount of time dealing with confusing bug reports that we eventually got traced to developers having unintentionally edited the headers in ways that caused compile errors (typically through jump to header in Xcode then accidentally typing/deleting things).

I wish `chflags nouchg` let you delete the file, just not edit it.  That would solve the problem!
I don't any special flags are on the SDK headers, my guess is that the path is whitelisted by Xcode to be locked, since you can edit them in any other editor you want.
