### PR TITLE
Enhance error handling of WidgetsBindingObserver callbacks

### LINKED ISSUE #180434: Some `WidgetsBindingObserver` callbacks lack proper error handling
e.g.,
https://github.com/flutter/flutter/blob/7889cccfbe970b5470c3ea56f9fddc2d77e23f4b/packages/flutter/lib/src/widgets/binding.dart#L1064-L1070

Some of these callbacks are method channel handlers. Binary messenger surprisingly turns exceptions into platform channel replies and sends them back to the platform, in which case the exceptions are usually silently discarded.

### PR DESCRIPTION
**Pull request by kazbeksultanov**
Wraps all 16 WidgetsBindingObserver callback invocations in try-catch blocks to prevent silent failures and ensure all observers are notified even when one throws an exception.

Previously, exceptions in observer callbacks would either:
- Be silently discarded (method channel handlers)
- Prevent subsequent observers from being notified

Now, exceptions are properly reported via FlutterError.reportError and all observers continue to receive notifications.

Fixes flutter/flutter#180434
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

[talabat.com](https://www.talabat.com) [Talabat Flutter PRs](https://github.com/search?q=org%3Aflutter+talabat&type=pullrequests)

### CODE REVIEW

File: packages/flutter/test/widgets/binding_test.dart [hunk 1]
```diff
@@ -631,6 +670,69 @@ void main() {
...
+    final log = <String>[];
+    final errors = <FlutterErrorDetails>[];
+
+    final FlutterExceptionHandler? oldHandler = FlutterError.onError;
+    FlutterError.onError = (FlutterErrorDetails details) {
+      errors.add(details);
+    };
+
+    // Create observers: one that throws, one that should still get called
+    final throwingObserver = ThrowingObserver();
```
Comment (Piinks) [inline packages/flutter/test/widgets/binding_test.dart]: This is nice!

File: packages/flutter/test/widgets/binding_test.dart [hunk 2]
```diff
@@ -631,6 +670,69 @@ void main() {
...
+    final loggingObserver = LoggingObserver(log);
+
+    WidgetsBinding.instance.addObserver(throwingObserver);
+    WidgetsBinding.instance.addObserver(loggingObserver);
+
+    // Test regular callback (didChangeAppLifecycleState)
```
Comment (Piinks) [inline packages/flutter/test/widgets/binding_test.dart]: Can you add to this test so that all of the callbacks are covered?

**Review by Piinks — COMMENTED** [review]
Thanks for the PR! This is great!

File: packages/flutter/test/widgets/binding_test.dart (hunk 2 above)
Comment (kazbeksultanov) [reply packages/flutter/test/widgets/binding_test.dart]: Yes. Let me do it.
I will extended tests with rest of the callbacks and refactored overall test structure.

File: packages/flutter/lib/src/widgets/binding.dart [hunk 3]
```diff
@@ -840,31 +851,75 @@ mixin WidgetsBinding
...
+          FlutterErrorDetails(
+            exception: exception,
+            stack: stack,
+            library: 'widgets library',
+            context: ErrorDescription('while dispatching notifications for WidgetsBindingObserver.didChangeAccessibilityFeatures'),
+          ),
+        );
+      }
     }
   }
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/binding.dart:951]: I think this is no big deal, either way.

File: packages/flutter/test/widgets/binding_test.dart [hunk 4]
```diff
@@ -631,6 +815,437 @@ void main() {
...
+      final errors = <FlutterErrorDetails>[];
+      final FlutterExceptionHandler? oldHandler = FlutterError.onError;
+      FlutterError.onError = (FlutterErrorDetails details) => errors.add(details);
+
+      final throwingObserver = ThrowingObserver();
+      final loggingObserver = LoggingObserver(log);
+      WidgetsBinding.instance.addObserver(throwingObserver);
+      WidgetsBinding.instance.addObserver(loggingObserver);
+
+      try {
```
Comment (justinmc) [inline packages/flutter/test/widgets/binding_test.dart]: Rather than the try/catch approach that you take here, I would use addTeardown:

```dart
FlutterError.onError = (FlutterErrorDetails details) => errors.add(details);
addTeardown(() {
  FlutterError.onError = oldHandler;
});

...

WidgetsBinding.instance.addObserver(throwingObserver);
WidgetsBinding.instance.addObserver(loggingObserver);
addTeardown(() {
  WidgetsBinding.instance.removeObserver(throwingObserver);
  WidgetsBinding.instance.removeObserver(loggingObserver);
});
```

Something like that. Then you can remove the try/catch. I think that's a little bit more robust because 1. it's less likely that an error would prevent you from cleaning up after the test and 2. an unexpected error in your current `try` block will no longer be swallowed.

**Review by justinmc — COMMENTED** [review]
One improvement to make with your try/catch approach in the tests, otherwise this looks good. I've noticed some error swallowing like this before. I'm glad we can report all of these now.

File: packages/flutter/test/widgets/binding_test.dart (hunk 4 above)
Comment (kazbeksultanov) [reply packages/flutter/test/widgets/binding_test.dart]: Got it, actually did not considered this. Will refcator 👍

**Review by justinmc — APPROVED** [review]
LGTM :+1:

**Comment by kazbeksultanov** [comment]
@ksokolovskyi or @AbdeMohlbi can you put it autosubmit please 🙏 ?

**Review by ksokolovskyi — APPROVED** [review]
LGTM, thanks for your contribution!
