### PR TITLE
Fix `ExcludeFocus` so it won't refocus a sibling of the focused node.

### LINKED ISSUE #61700: ExcludeFocus can still allow focus
## Steps to reproduce

1. Run the following app:

```dart
import 'dart:ui' show window;

import 'package:flutter/material.dart';

void main() {
  runApp(BugReport());
}

class BugReport extends StatefulWidget {
  @override
  _BugReportState createState() => _BugReportState();
}

class _BugReportState extends State<BugReport> {
  bool blockFocus = false;

  _toggleBlockFocus() {
    setState(() {
      blockFocus = !blockFocus;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Actions(
      actions: WidgetsApp.defaultActions,
      child: Localizations(
        locale: Locale('en', 'US'),
        delegates: [
          DefaultWidgetsLocalizations.delegate,
          DefaultMaterialLocalizations.delegate,
        ],
        child: MediaQuery(
          data: MediaQueryData.fromWindow(window),
          child: Navigator(
            onGenerateRoute: (RouteSettings settings) {
              return MaterialPageRoute<void>(
                settings: settings,
                builder: (BuildContext context) {
                  return Material(
                    child: ExcludeFocus(
                      excluding: blockFocus,
                      child: Column(
                        children: [
                          TextField(),
                          TextField(),
                          OutlineButton(
                            onPressed: () => _toggleBlockFocus(),
                            child: Text(blockFocus ? 'Allow focus' : 'Block focus'),
                          ),
                        ],
                      ),
                    ),
                  );
                },
              );
            },
          ),
        ),
      ),
    );
  }
}
```

2. Focus the second text field.
3. Click the button to turn on excluding of focus

## Expected behavior

You expect focus to be lost completely, since all three UI elements are wrapped in a `ExcludeFocus` with `excluding` set to true.

## Actual behavior

The focus transfers from the second text field to the first one.

## Other info

This was spawned from https://github.com/flutter/flutter/issues/61659 and is observable on Android, iOS, and macOS, but it doesn't reproduce on web.  Here's what versions I'm synced to:

```
$ flutter doctor -v
[✓] Flutter (Channel master, 1.21.0-2.0.pre.51, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.21.0-2.0.pre.51 at /Users/tvolkert/project/flutter/flutter
    • Framework revision df542b6831 (5 hours ago), 2020-07-16 18:32:46 -0700
    • Engine revision d3b81f19fc
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 06183779d7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tvolkert/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode_11.4.1.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.3 19D76
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This changes `FocusNode.descendantsAreFocusable` so that it doesn't allow the enclosing scope to re-focus a node that is a descendant of the node with `descendantsAreFocusable` set to false.

Because of the order in which the internal state for `descendantsAreFocusable` was being set, setting it to false was causing a sibling node to be focused when `descendantsAreFocusable` of the parent was set to false, even though it shouldn't have been focusable, because the enclosing scope would search for a candidate to be focused before the internal state was set to false.

Instead of looping over the children and telling them all to unfocus (and select the previously focused node), this unfocuses the node that has `descendantsAreFocusable` set to false, with the disposition `UnfocusDisposition.previouslyFocusedChild`, so that its enclosing scope will look for a previously focused child that isn't part of the subtree being excluded.

This affects how the `ExcludeFocus` widget behaves when turning on `exclude`.

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/61700

## Tests

- Added a regression test.

## Breaking Change

- [X] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 1]
```diff
@@ -864,19 +867,19 @@ class FocusNode with DiagnosticableTreeMixin, ChangeNotifier {
         while (!scope.canRequestFocus) {
           scope = scope.enclosingScope ?? _manager?.rootScope;
         }
-        scope?._doRequestFocus(findFirstFocus: false);
+        scope._doRequestFocus(findFirstFocus: false);
```
Comment (darrenaustin) [inline packages/flutter/lib/src/widgets/focus_manager.dart:870]: Are these changes here related to the fix, or just cleaning up something? I assume scope can no longer be null when it might have before?

**Review by darrenaustin — APPROVED** [review]
LGTM.

File: packages/flutter/lib/src/widgets/focus_manager.dart (hunk 1 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: Actually, I made those changes thinking that these couldn't ever be null, because the `rootScope` can't be null, but if the `_manager` is null, it still could be.  I reverted these.
