### PR TITLE
fix `DropdownMenu` keyboard navigation when entries are filtered empty

### LINKED ISSUE #154532: DropdownMenu throws RangeError when no matching results are found in DropdownMenuEntries
### Steps to reproduce

Problem can be reproduced using code in flutter docs.
( https://api.flutter.dev/flutter/material/DropdownMenu-class.html )

When you search the icon using TextField of `DropdownMenu` and you enter a icon name which is not present in IconLabel enum but matches a few characters, it shows a RangeError.

### Expected results

An Example Usage: Filter through existing users from database using `DropdownMenu` and if user does not exist add it into database.

So expected result should be filter the entries and if found nothing then don't throw an error, just show empty list or show no Dropdown below textfield.

It was working perfectly fine a couple of flutter versions back. Request you to look at this immediately as live apps are using it.

### Actual results

The error thrown is 
RangeError (index): Index out of range: no indices are valid: 0

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

// Flutter code sample for [DropdownMenu]s. The first dropdown menu
// has the default outlined border and demos using the
// [DropdownMenuEntry] style parameter to customize its appearance.
// The second dropdown menu customizes the appearance of the dropdown
// menu's text field with its [InputDecorationTheme] parameter.

void main() {
  runApp(const DropdownMenuExample());
}

// DropdownMenuEntry labels and values for the first dropdown menu.
enum ColorLabel {
  blue('Blue', Colors.blue),
  pink('Pink', Colors.pink),
  green('Green', Colors.green),
  yellow('Orange', Colors.orange),
  grey('Grey', Colors.grey);

  const ColorLabel(this.label, this.color);
  final String label;
  final Color color;
}

// DropdownMenuEntry labels and values for the second dropdown menu.
enum IconLabel {
  smile('Smile', Icons.sentiment_satisfied_outlined),
  cloud(
    'Cloud',
    Icons.cloud_outlined,
  ),
  brush('Brush', Icons.brush_outlined),
  heart('Heart', Icons.favorite);

  const IconLabel(this.label, this.icon);
  final String label;
  final IconData icon;
}

class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});

  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  final TextEditingController colorController = TextEditingController();
  final TextEditingController iconController = TextEditingController();
  ColorLabel? selectedColor;
  IconLabel? selectedIcon;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Colors.green,
      ),
      home: Scaffold(
        body: SafeArea(
          child: Column(
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 20),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    DropdownMenu<ColorLabel>(
                      initialSelection: ColorLabel.green,
                      controller: colorController,
                      // requestFocusOnTap is enabled/disabled by platforms when it is null.
                      // On mobile platforms, this is false by default. Setting this to true will
                      // trigger focus request on the text field and virtual keyboard will appear
                      // afterward. On desktop platforms however, this defaults to true.
                      requestFocusOnTap: true,
                      label: const Text('Color'),
                      onSelected: (ColorLabel? color) {
                        setState(() {
                          selectedColor = color;
                        });
                      },
                      dropdownMenuEntries: ColorLabel.values
                          .map<DropdownMenuEntry<ColorLabel>>(
                              (ColorLabel color) {
                        return DropdownMenuEntry<ColorLabel>(
                          value: color,
                          label: color.label,
                          enabled: color.label != 'Grey',
                          style: MenuItemButton.styleFrom(
                            foregroundColor: color.color,
                          ),
                        );
                      }).toList(),
                    ),
                    const SizedBox(width: 24),
                    DropdownMenu<IconLabel>(
                      controller: iconController,
                      enableFilter: true,
                      requestFocusOnTap: true,
                      leadingIcon: const Icon(Icons.search),
                      label: const Text('Icon'),
                      inputDecorationTheme: const InputDecorationTheme(
                        filled: true,
                        contentPadding: EdgeInsets.symmetric(vertical: 5.0),
                      ),
                      onSelected: (IconLabel? icon) {
                        setState(() {
                          selectedIcon = icon;
                        });
                      },
                      dropdownMenuEntries:
                          IconLabel.values.map<DropdownMenuEntry<IconLabel>>(
                        (IconLabel icon) {
                          return DropdownMenuEntry<IconLabel>(
                            value: icon,
                            label: icon.label,
                            leadingIcon: Icon(icon.icon),
                          );
                        },
                      ).toList(),
                    ),
                  ],
                ),
              ),
              if (selectedColor != null && selectedIcon != null)
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Text(
                        'You selected a ${selectedColor?.label} ${selectedIcon?.label}'),
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 5),
                      child: Icon(
                        selectedIcon?.icon,
                        color: selectedColor?.color,
                      ),
                    )
                  ],
                )
              else
                const Text('Please select a color and an icon.')
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on EndeavourOS 6.10.3-arch1-2, locale en_IN)
    • Flutter version 3.24.1 on channel stable at /usr/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (13 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.30.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • EndeavourOS 6.10.3-arch1-2
    • Chrome (web)    • chrome • web-javascript • Chromium 127.0.6533.99 Arch Linux

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by PurplePolyhedron**
fixes https://github.com/flutter/flutter/issues/154532

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 1]
```diff
@@ -1315,6 +1315,28 @@ void main() {
...
+      await tester.tap(find.byType(DropdownMenu<TestMenu>));
+      await tester.pump();
+      await tester.enterText(find.byType(TextField).first, 'No match');
+      await tester.pump();
+      await tester.sendKeyEvent(LogicalKeyboardKey.arrowDown);
+      await tester.pump();
+      await tester.enterText(find.byType(TextField).first, 'No match 2');
+      await tester.pump();
+      expect(tester.takeException(), isNull);
+  }, variant: TargetPlatformVariant.desktop());
```
Comment (bleroux) [inline packages/flutter/test/material/dropdown_menu_test.dart:1338]: Keyboard navigation is also supported on mobile (Android for sure, iOS probably).
I tried changing `TargetPlatformVariant.desktop()` to `TargetPlatformVariant.all()` and the test still passed.

**Review by bleroux — COMMENTED** [review]
Many thanks for this fix :pray: and sorry for the delay.
Some minor comments.

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 1 above)
Comment (PurplePolyhedron) [reply packages/flutter/test/material/dropdown_menu_test.dart]: The different is `requestFocusOnTap` default to false on mobile, The widget won't gain focus and won't receive key event. (I think this might be the reason other keyboard navigation tests used `TargetPlatformVariant.desktop()` )

I can see setting `requestFocusOnTap` to `true` being overall the better solution than setting `TargetPlatformVariant`

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 2]
```diff
@@ -490,13 +490,21 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
...
   int? currentHighlight;
   double? leadingPadding;
   bool _menuHasEnabledItem = false;
   TextEditingController? _localTextEditingController;
 
+  List<DropdownMenuEntry<T>> get filteredEntries => _filteredEntries;
+
+  set filteredEntries(List<DropdownMenuEntry<T>> value) {
+    _filteredEntries = value;
+    buttonItemKeys = List<GlobalKey>.generate(filteredEntries.length, (int index) => GlobalKey());
```
[the remark this answers is not in the document]
Comment (PurplePolyhedron) [reply packages/flutter/lib/src/material/dropdown_menu.dart]: It appears the keys are only used for scrolling, and updating keys is not needed in build, only `_menuHasEnabledItem` needs to updated. I don't think a setter is appropriate any more, instead I just add an update in build.

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Thanks for the explanation. :pray: 
For the moment, it makes sense to do the same as the other existing tests.
We can revisit this on a separate "test only" PR (feel free to ping me if you file one, I like PRs that aim at improving existing tests :fire: ), setting `requestFocusOnTap` to `true` seems to be a nice option (a comment might be interesting to remind why).

**Review by bleroux — APPROVED** [review]
LGTM! Thanks for taking care of this fix

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Oops sorry, I was reading the wrong version. I see now that you applies this change, it is ok to me. Feel free to add a comment if you think it worths it.

Comment (PurplePolyhedron) [reply packages/flutter/test/material/dropdown_menu_test.dart:1338]: Ok, I've changed it back to `TargetPlatformVariant.desktop()` for now.

Comment (PurplePolyhedron) [reply packages/flutter/test/material/dropdown_menu_test.dart:1338]: Oops, it appears to be some delays and I didn't see the new message, I will try to file a PR about overall `requestFocusOnTap` in keyboard navigation in a few days.

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 3]
```diff
@@ -1315,6 +1315,28 @@ void main() {
...
```
Comment (nate-thegrate) [inline packages/flutter/test/material/dropdown_menu_test.dart:1338]: tiny whitespace nit:

```suggestion
    },
    variant: TargetPlatformVariant.desktop(),
  );
```

**Review by nate-thegrate — APPROVED** [review]
LGTM! Great to see a 1-line fix 🙂👍

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 3 above)
Comment (PurplePolyhedron) [reply packages/flutter/test/material/dropdown_menu_test.dart:1338]: Majority of the tests in the framework with `TargetPlatformVariant`  are using 

```}, variant: TargetPlatformVariant.desktop());```

 I want to keep it the same format

Comment (nate-thegrate) [reply packages/flutter/test/material/dropdown_menu_test.dart:1338]: Fair point!

<br>

Here are 2 good options:

```dart
  testWidgets('description', (WidgetTester tester) async {
    // ...
  }, variant: TargetPlatformVariant.desktop());
```

```dart
  testWidgets(
    'description',
    (WidgetTester tester) async {
      // ...
    },
    variant: TargetPlatformVariant.desktop(),
  );
```

I'd be happy with either one.

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 4]
```diff
@@ -1316,8 +1316,7 @@ void main() {
   });
 
   // Regression test for https://github.com/flutter/flutter/issues/154532.
-  testWidgets('Keyboard navigation does not throw when no entries match the filter',
-    (WidgetTester tester) async {
+  testWidgets('Keyboard navigation does not throw when no entries match the filter', (WidgetTester tester) async {
       await tester.pumpWidget(MaterialApp(
         home: Scaffold(
           body: DropdownMenu<TestMenu>(
```
Comment (nate-thegrate) [inline packages/flutter/test/material/dropdown_menu_test.dart:1322]: Looks great. Could we un-indent the function body as well?
```suggestion
  testWidgets('Keyboard navigation does not throw when no entries match the filter', (WidgetTester tester) async {
    await tester.pumpWidget(MaterialApp(
      home: Scaffold(
        body: DropdownMenu<TestMenu>(
```

Comment (PurplePolyhedron) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Got it. Thanks for the review and helping me fixing the format issues.

Comment (nate-thegrate) [reply packages/flutter/test/material/dropdown_menu_test.dart]: No problem, thanks for these updates! I think we're good to merge now, assuming checks pass 👍
