### PR TITLE
[flutter_tools] Catch more general XmlException rather than XmlParserException

### LINKED ISSUE #106365: [flutter_tools] XmlTagException during flutter run
on `beta/3.1.0-9.0.pre`
with command: `flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart`

```
XmlTagException: Expected </application>, but found </activity> at 37:4
at XmlAnnotator.annotate(annotator.dart:88)
at XmlEventIterator.moveNext(iterator.dart:32)
at Iterable.forEach(iterable.dart:325)
at XmlNodeDecoder.convertIterable(node_decoder.dart:53)
at new XmlDocument.parse(document.dart:34)
at AndroidProject.computeEmbeddingVersion(project.dart:649)
at AndroidProject.checkForDeprecation(project.dart:592)
at FlutterProject.checkForDeprecation(project.dart:381)
at FlutterCommand.verifyThenRunCommand(flutter_command.dart:1319)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1195)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:209)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:281)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:229)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:62)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:94)
at <asynchronous gap>(async)
```

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/106365

In package:xml, there are [many possible types of exceptions](https://github.com/renggli/dart-xml/commit/1a699c462f589b84d024acfc965640b0f899833b#diff-8d65dca72338d373d886c6eb3eae4e4af22dca9c15af2d9229a1fa5c30e886bd) that could be thrown from an invalid Xml document; however, historically the tool has only caught XmlParserException. This changes the exception handling to catch instead the abstract parent class, `XmlException`; we want to handle ALL types of invalid XML documents and direct the user to repair it themselves.

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/multidex.dart [hunk 1]
```diff
@@ -93,9 +93,7 @@ bool androidManifestHasNameVariable(final Directory projectDir) {
   XmlDocument document;
   try {
     document = XmlDocument.parse(manifestFile.readAsStringSync());
-  } on XmlParserException {
-    return false;
-  } on XmlTagException {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/multidex.dart:98]: Here I had previously added additional handling for XmlTagException, however this wouldn't have caught an `XmlParentException` or `XmlNodeTypeException`

**Review by Jasguerrero — APPROVED** [review]
LGTM
