### PR TITLE
Underflowing LazyBlock should relayout for additional children

### LINKED ISSUE #5950: Underflowing LazyBlock can fail to re-layout
The following test demonstrates the problem.
```
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter/widgets.dart';

void main() {
  testWidgets('Underflowing LazyBlock should relayout for additional children', (WidgetTester tester) async {
    await tester.pumpWidget(new LazyBlock(
      delegate: new LazyBlockChildren(
        children: <Widget>[
          new SizedBox(height: 100.0, child: new Text('100')),
        ]
      )
    ));

    await tester.pumpWidget(new LazyBlock(
      delegate: new LazyBlockChildren(
        children: <Widget>[
          new SizedBox(height: 100.0, child: new Text('100')),
          new SizedBox(height: 200.0, child: new Text('200'))
        ]
      )
    ));

    expect(find.text('200'), findsOneWidget);
  });
}
```

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes #5950

### CODE REVIEW

File: packages/flutter/lib/src/widgets/lazy_block.dart [hunk 1]
```diff
@@ -597,7 +600,10 @@ class _LazyBlockElement extends RenderObjectElement {
   void performRebuild() {
     IndexedWidgetBuilder builder = widget.delegate.buildItem;
     List<Widget> widgets = <Widget>[];
-    for (int i = 0; i < _children.length; i += 1) {
+    // If the most recent layout didn't fill the viewport but an additional child
+    // is now available, add it to the widgets list which will force a layout.
+    int buildChildCount = _underflow ? _children.length + 1 : _children.length;
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/lazy_block.dart]: final?

File: packages/flutter/lib/src/widgets/lazy_block.dart [hunk 2]
```diff
@@ -737,6 +743,7 @@ class _LazyBlockElement extends RenderObjectElement {
     // viewport. The currentLogicalIndex is the index of the first child that
     // we don't need.
 
+    _underflow = currentLogicalOffset < endLogicalOffset;
     if (currentLogicalOffset < endLogicalOffset) {
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/lazy_block.dart]: I'd change this to `if (_underflow)` rather than repeating the test.

**Review by abarth — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/lazy_block.dart (hunk 1 above)
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/lazy_block.dart]: I actually removed the final qualifier because most of the code in this file doesn't use it for local vars (that are in fact final).

Would be happy to make another pass and finalize things.
