### PR TITLE
Fix refresh cancelation

### LINKED ISSUE #138848: `RefreshIndicator` can end up canceled if the touch point moves upward by even one pixel on touch-up
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When using `RefreshIndicator`, when you release the touch point, sometimes the point jumps upwards a tiny bit (either through inadvertent movement from the user, or because as the finger comes up off the screen, the centroid of the touch point moves upwards slightly).

If the touch point moves even one pixel upwards (back away from the point of maximum drag, when the refresh indicator is "armed"), `RefreshIndicator` cancels the drag.

This can make it maddeningly difficult to actually initiate a refresh, because half the time when you lift your finger, the touch point is canceled, even if it was previously armed.

This is the culprit code, in `refresh_indicator.dart`:

image

These numbers are 0.0, but should be greater than zero.

Setting both numbers to 20.0 mostly solves the "bounce-back and cancel" problem, but then the behavior feels a bit weird, because the spinner doesn't move at all for 20 pixels of vertical movement upwards, and yet the scrollview still refreshes on release.

I would actually prefer that the overscroll distance, beyond the "armed" point, be the distance that you can scroll back upwards by, before the drag is canceled. In other words, if `displacement` is 100, and you drag down 130 pixels, then you can drag back up by 30 pixels before the drag is canceled.

There's another issue here too: sometimes when releasing a drag, even using the emulator, with the mouse held perfectly still, you get not only bounce-back and cancel (with zero movement!), but also the scroll indicator bouncing back *causes the scrollview to scroll back as well*. It's almost like the drag controller of `RefreshIndicator` starts sending scroll events to the scrollview's scroll controller.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel beta, 3.17.0-0.0.pre, on Fedora Linux 38 (Workstation Edition) 6.5.10-200.fc38.x86_64, locale en_US.utf8)
    • Flutter version 3.17.0-0.0.pre on channel beta at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0b591f2c82 (3 weeks ago), 2023-11-02 22:01:10 -0400
    • Engine revision dff66925dc
    • Dart version 3.3.0 (build 3.3.0-91.0.dev)
    • DevTools version 2.29.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.77.20231101

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.5.10-200.fc38.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by lukehutch**
Changes drag release logic so that an armed refresh is only canceled if the user has scrolled back up beyond the point where the refresh indicator was armed. (Fixes https://github.com/flutter/flutter/issues/138848.)

This is the minimal change I found could be made to restore something like the behavior that I would expect.

This may still need a bit of work, because it only masks the second issue I mentioned, that releasing a drag can cause the scroll position to be animated back up from the release point. There is actually a bug about that: https://github.com/flutter/flutter/issues/6052. I would like to see that bug fixed too. This PR doesn't address that, but makes it harder to hit that issue.

@Piinks this is a recreation of #139015 (since I couldn't figure out some issue with a git detached branch, so I fixed the PR and I'm re-submitting it). This version includes one line that was somehow accidentally dropped from the original PR. This will hopefully fix the test failures.

However, I don't have a clue how to write a test for a Flutter UI widget. I'll try to figure that out, but also I don't have a lot of time to work on this. I would appreciate at least some user testing to verify that the new behavior is much more intuitive than the old behavior.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [?] All existing and new tests are passing.

### CODE REVIEW

**Comment by lukehutch** [comment]
@Piinks I went over the test failures, and there's no usable information in the 5 failures, just `Command exited with exit code 1 but expected zero exit code.` 

I suspect this is some failure in CI, and not a failure in the code change I made (which is extremely minimal)...

**Review by Piinks — COMMENTED** [review]
Hi @lukehutch this change still does not have a test.

The CI failures here are legitimate. This breaks existing refresh indicator tests.
Clicking the link to view more details leads to the full tests logs...

Screenshot 2023-12-05 at 11 10 25 AM


This wiki page may also be of interest: https://github.com/flutter/flutter/wiki/Understanding-a-LUCI-build-failure

If you have not already, our contributing guide may also be of some help.
https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md

**Comment by lukehutch** [comment]
@Piinks thanks for providing more links to documentation.

As I mentioned, I looked at the bug dashboard, but the only info I could find was that the code had exited with error code 1.

I finally realized I have to drill down into the raw stdout output to see what actually failed. So now I can see the test that failed (it looks like it was just one test). How to find the source of failures like this is not described in either of the documentation links you sent -- maybe they should be updated.

As I mentioned in the previous version of the PR that I filed, I already followed the contributing guide (and the linked "Setting up the Framework development environment" page) to the letter, in trying to set up my Flutter environment, but even after following all the steps, I get almost 500k build errors in VS Code, when opening `code` at the root of the `flutter` directory. I have no idea what is causing this, but I assume VS Code is popular among the Flutter team, so I'm surprised this doesn't open properly out of the box.

The contributing guide also has no information at all about how to write or run tests (especially individual tests, which is what I need to be able to do here). I tried manually running the test's `main` function, but I get a lot of errors about packages not being available (even after I ran `flutter update-packages`).

I don't really know how to proceed at this point... I need to be able to run the single failing test, so that I can figure out why it's failing.

**Comment by Piinks** [comment]
Hi @lukehutch unfortunately I am not able to debug your local environment. You should be able to run the tests from flutter/packages/flutter with just the `flutter test` command, or `flutter test <path-to-test>` for a specific test file.

**Comment by lukehutch** [comment]
@Piinks OK, I fixed the broken test, and I added two new tests to test the new behavior. PTAL -- thanks.

File: packages/flutter/test/material/refresh_indicator_test.dart [hunk 1]
```diff
@@ -253,14 +253,84 @@ void main() {
       ),
     );
 
-    await tester.fling(find.text('X'), const Offset(0.0, 100.0), 1000.0);
+    await tester.fling(find.text('X'), const Offset(0.0, 200.0), 1000.0);
```
Comment (Piinks) [inline packages/flutter/test/material/refresh_indicator_test.dart:256]: Can you explain why this needed to change?

**Review by Piinks — COMMENTED** [review]
Thanks for the update @lukehutch!

File: packages/flutter/test/material/refresh_indicator_test.dart (hunk 1 above)
Comment (lukehutch) [reply packages/flutter/test/material/refresh_indicator_test.dart:256]: I believe it is because of the bounceback issue that I described in #138848.

Comment (Piinks) [reply packages/flutter/test/material/refresh_indicator_test.dart:256]: It looks like it came from #69783. It seems intentional to match the native behavior, but it may have changed since then.

**Review by Piinks — COMMENTED** [review]
Do we know what the native behavior is? 

I reviewed the issue again and noticed:

> I would actually prefer that the overscroll distance, beyond the "armed" point, be the distance that you can scroll back upwards by, before the drag is canceled. In other words, if displacement is 100, and you drag down 130 pixels, then you can drag back up by 30 pixels before the drag is canceled.

The intention for this widget is to match the native behavior, is this what happens natively on the latest version of Android?

**Comment by lukehutch** [comment]
My patch makes the Flutter behavior match the native behavior on Android, albeit that the native behavior also shows the indicator as armed when it is armed, allowing a further draggable distance in the armed state (which Flutter does not yet support -- #139018).

Native behavior, which you can see by dragging down from the top of the messages list in Gmail for Android:
* While dragging down to some distance X, the refresh indicator has a circular arrow of dark gray color ("unarmed state").
* At distance X, the refresh indicator turns white ("armed state").
* You can then drag the indicator a further distance Y downwards, in armed state.
* Releasing in armed state causes the refresh.
* If you drag down some distance X + b, where b >= 0, then drag back upwards by a distance of at least b + 1, then the refresh indicator goes back to unarmed state, and refreshing it cancels the refresh request.

Current Flutter behavior, before my PR:
* You have to drag a minimum distance X from the top of the screen to arm the refresh indicator.
* There is no indication that the refresh indicator is armed. (#139018)
* Dragging any distance Y > 0 beyond that point does not cause the refresh indicator to be dragged any further down the screen.
* No matter how much further (Y > 0) you drag down beyond the armed point, dragging even one pixel upwards before releasing cancels the refresh operation. (#138848)
* Often there is a "bounceback" effect when you release the touch point that causes a slight upwards scroll, which means that it is annoyingly hard to actually cause the refresh to happen. (I describe this in #138848, although I never actually got to the bottom of what causes this -- it is a separate bug.
  * I did verify that the bounceback even happens with a perfectly still mouse while using the emulator, so it's not a touchpad driver artifact as the touchpoint centroid moves during a touch-up event.

What my PR does:
* Dragging a distance X from the top arms the refresh indicator. (There is no indication of the armed state, because Flutter does not yet support it.)
* When dragging a distance Y > 0 beyond the armed point, the refresh indicator does not move further down the screen (this is different from Android native behavior, because Flutter doesn't yet animate the armed state beyond the arm point, but it's a reasonable halfway step).
* If you drag back any distance b <= Y before releasing, the refresh happens. If you drag back any distance b > Y before releasing, the refresh is canceled.

What my PR accomplishes:
* Refresh can be reliably initiated, even with the slight bounceback effect (which should be separately fixed), because you can drag as far past the armed point as you want, creating a buffer region that is bigger than the bounceback distance.
* Refresh can be reliably canceled, because you can just drag back upwards until you see the refresh indicator moving back upwards again before releasing, since at least this shows you that the indicator is unarmed (even if there is currently no armed indicator).

**Comment by Piinks** [comment]
Thanks very much for the detailed analysis and explanation! 
I think the change to the existing test is fine then. 

> The Flutter refresh indicator really does need an overhaul to make it work like the Android native indicator

I agree! If there is not an open issue for any of the bullet points you listed above, would you mind filing an issue for each one? I see some are already covered in the issues you linked. 

I think all this PR needs then is a rebase, and it looks like there is a merge conflict to  resolve. After that it should be ready to land. 💯

**Comment by lukehutch** [comment]
Rebased and merged.

I will update the relevant issues, and may open one more "umbrella" issue to do a complete audit of the refresh indicator behavior.

Thanks!

**Review by Piinks — APPROVED** [review]
LGTM, this will need a second approval. Seeking a reviewer now. :)

**Review by cbracken — APPROVED** [review]
lgtm. 

@Piinks is there anything remaining that needs to be addressed relative to [this comment](https://github.com/flutter/flutter/pull/139535/files#r1439876549)?

**Comment by Piinks** [comment]
> @Piinks is there anything remaining that needs to be addressed relative to [this comment](https://github.com/flutter/flutter/pull/139535/files#r1439876549)?

Nope! We confirmed it, albeit not in that thread. Thanks for checking!

**Comment by lukehutch** [comment]
Thanks!
