### PR TITLE
Fix ScrollPosition overscroll precision error

### LINKED ISSUE #126561: [Material 3] : Text disappears while navigating between tabs inside of a TabView
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Start new application
2. Inside of a Scaffold, place a Column, with a TabView with 3 tabs. Inside of each tab place a Text.
3. Click on the back and forth on the tabs

### Expected results

The text should render correctly..

### Actual results

Text randomly appears and disappears as you click on the tab headers

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      initialIndex: 0,
      length: 3,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('ListView Text Issue'),
        ),
        bottomNavigationBar: BottomNavigationBar(
          items: const [
            BottomNavigationBarItem(
              icon: Icon(Icons.abc),
              label: 'ABC',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.access_alarm),
              label: 'Alarm',
            ),
          ],
        ),
        body: const Padding(
          padding: EdgeInsets.all(8),
          child: Column(
            children: [
              Text('Click on the tabs and see if the text goes crazy'),
              TabBar(
                tabs: [
                  Tab(
                    text: 'Tab 1',
                  ),
                  Tab(
                    text: 'Tab 2',
                  ),
                  Tab(
                    text: 'Tab 3',
                  ),
                ],
              ),
              Expanded(
                child: TabBarView(
                  children: [
                    Text('Tab 1'),
                    Text('Tab 2'),
                    Text('Tab 3'),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
Full Repo: https://github.com/chanan/listview_text_issue
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/472554/8039f574-fa38-4f2f-a07c-9bb9d42446bf

</details>

### Logs

<details><summary>Logs</summary>

```console
Running directly from Android Studio
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22624.1755], locale en-US)
    • Flutter version 3.10.0 on channel stable at c:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\chana\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.22)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33130.400
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[!] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\android-studio-preview
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at C:\Users\chana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22624.1755]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 113.0.1774.35

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes a precision error in ~~`ClampingScrollPhysics`~~ `ScrollPosition` that leads to `StretchingOverscrollIndicator` stretching its content unexpectedly in some devices (see  https://github.com/flutter/flutter/issues/126561 where this is visible in `TabBarView` and the test added in this PR where it reproduces with a `PageView`).

~~This PR also contains a change to `nested_scroll_view.dart` because the first change (the one in `ClampingScrollPhysics`)  breaks the precision error test added by https://github.com/flutter/flutter/pull/87801.~~

## Related Issue

Fixes https://github.com/flutter/flutter/issues/126561

## Tests

Adds 1 test.

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
I'd like to run this through some extra testing, great find by the way. I was surprised to see this was in ClampingScrollPhysics, originally I thought this would have to do with PageScrollPhysics. cc'd @nt4f04uNd since you noticed this affected a change they made a while back. Thanks for diving into NestedScrollView to prevent a regression here.

File: packages/flutter/lib/src/widgets/scroll_physics.dart [hunk 1]
```diff
@@ -878,7 +878,7 @@ class ClampingScrollPhysics extends ScrollPhysics {
       // Hit top edge.
       return value - position.minScrollExtent;
     }
-    if (position.pixels < position.maxScrollExtent && position.maxScrollExtent < value) {
+    if (position.pixels < position.maxScrollExtent && value - position.maxScrollExtent > precisionErrorTolerance) {
```
Comment (nt4f04uNd) [inline packages/flutter/lib/src/widgets/scroll_physics.dart:881]: Another thing that I'm wondering, why is overflowing by such a small value of `1.1368683772161603e-13` gives us the stetch of `1.440112717630772` and the stretch does not recede?

There might be another deeper problem with the `StretchingOverscrollIndicator`

@Piinks what do you think?

**Review by nt4f04uNd — APPROVED** [review]

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 2]
```diff
@@ -368,7 +368,7 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
         notifyListeners();
         didUpdateScrollPositionBy(pixels - oldPixels);
       }
-      if (overscroll != 0.0) {
+      if (overscroll.abs() > precisionErrorTolerance) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_position.dart:371]: Ah yes, this is a much clearer culprit. 👍  Thank you both for looking into this!

**Review by Piinks — APPROVED** [review]
LGTM!

**Comment by rydmike** [comment]
Wow, nice work all of you 👍🏻 💙 

This was quite a peculiar looking bug, with an effect that looked really strange, making it hard to even first believe it when it was discovered. When @chanan first showed it to me on Twitter, I was like naah, that can be possible, until I tried it, lol. 

Nice to see a speedy resolution, and thanks @bleroux for digging into it so quickly.

**Comment by Piinks** [comment]
Since this wasn't a regression in the release I don't know that we should cherry pick it. Working its way through the release process helps us catch any potential issues with it or other regressions it may introduce, but that's my opinion. I would reach out on discord to see if anyone feels strongly that this should be CP'd. Thanks!

**Comment by absar** [comment]
Its been two months since the fix landed in master but it is still not in stable. Can you please cherry pick it, since it's giving end users very bad UX, the screen stretches and does not come back to original shape. Even if the new flutter stable 3.13/3.14 is being released we cannot risk using that for production until that gains stability
