### PR TITLE
fix(android): add null check for textInputPlugin in FlutterView

### LINKED ISSUE #149792: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.TextInputPlugin.onProvideAutofillVirtualStructure(android.view.ViewStructure, int)' on a null object reference
### Steps to reproduce

1、update flutter version from 3.3.9 to 3.16.9
2、Open the phone settings and turn on the application password book function
3、create a viewpage fragment, one is native fragment and has edit, other is flutter fragment and init
then, 
When you click on the edit box of the native fragment, it will inevitably collapse and appear.

### Expected results

click normal

### Actual results

```console
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.TextInputPlugin.onProvideAutofillVirtualStructure(android.view.ViewStructure, int)' on a null object reference
at io.flutter.embedding.android.FlutterView.onProvideAutofillVirtualStructure(FlutterView.java:1525)
at android.view.View.dispatchProvideStructure(View.java:10364)
at android.view.View.dispatchProvideAutofillStructure(View.java:10356)
at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3708)
at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3728)
at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3728)
at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:527)
at android.app.assist.AssistStructure.<init>(AssistStructure.java:2345)
at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:4101)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2427)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:240)
at android.os.Looper.loop(Looper.java:351)
at android.app.ActivityThread.main(ActivityThread.java:8423)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```
### Code sample

<details open><summary>Code sample</summary>

```java
        fragmentList = new ArrayList<>();
        nativeFragment = new NativeFragment();

        addFragmentThenHide(R.id.fragment_stub, nativeFragment, "tab_" + 0);

        mesFragment = new MsgFlutterFragment
                .CachedEngineFragmentBuilder(MsgFlutterFragment.class)
                .url("tab_message")
                .build();

        addFragmentThenHide(R.id.fragment_stub, mesFragment, "tab_" + 2);

        friendFragment = new FriendFlutterFragment
                .CachedEngineFragmentBuilder(FriendFlutterFragment.class)
                .url("tab_friend")
                .build();
```

```dart

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[mtp_test_demo.zip](https://github.com/user-attachments/files/15604847/mtp_test_demo.zip)

</details>

### Logs

<details open><summary>Logs</summary>

```console
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.editing.TextInputPlugin.onProvideAutofillVirtualStructure(android.view.ViewStructure, int)' on a null object reference
at io.flutter.embedding.android.FlutterView.onProvideAutofillVirtualStructure(FlutterView.java:1525)
at android.view.View.dispatchProvideStructure(View.java:10364)
at android.view.View.dispatchProvideAutofillStructure(View.java:10356)
at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3708)
at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3728)
at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3728)
at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:527)
at android.app.assist.AssistStructure.<init>(AssistStructure.java:2345)
at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:4101)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2427)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:240)
at android.os.Looper.loop(Looper.java:351)
at android.app.ActivityThread.main(ActivityThread.java:8423)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by LailaiMaster**
Prevents NPE in onProvideAutofillVirtualStructure when attachToEngineAutomatically is false and autofill is triggered before manual engine attachment.

Added null safety check with early return and debug warning. Maintains backward compatibility.

Fixes: flutter/flutter/issues/149792、https://github.com/flutter/flutter/issues/180383

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java [hunk 1]
```diff
@@ -1576,12 +1576,16 @@ private void sendViewportMetricsToFlutter() {
   @Override
   public void onProvideAutofillVirtualStructure(@NonNull ViewStructure structure, int flags) {
     super.onProvideAutofillVirtualStructure(structure, flags);
-    textInputPlugin.onProvideAutofillVirtualStructure(structure, flags);
+    if(textInputPlugin != null) {
```
Comment (Mairramer) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java]: I’m not very familiar with the engine itself, only with the Android ecosystem, but from my perspective this solves only half of the problem. It prevents the app from crashing, but the box will never be shown to the user.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java
Comment (Mairramer) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java:1]: Tests are also necessary to ensure that no regressions occur in the future.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java (hunk 1 above)
Comment (LailaiMaster) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java]: Thanks for the review!
I appreciate your concern about the autofill box potentially not being shown to the user. However, this change doesn't introduce that issue—the NPE only occurs during the fragment initialization phase when it's not yet bound to the engine. In this state, the autofill virtual structure isn't requested or expected anyway, so the box wouldn't appear regardless. The null check is purely defensive to prevent the crash without altering any existing behavior or functionality.
Given that, I don't believe additional tests are necessary here, as there are no side effects or regressions introduced. Let me know if you'd like me to clarify further or provide more details!

Comment (LailaiMaster) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java]: In the issue at https://github.com/flutter/flutter/issues/180383, I documented my troubleshooting process and the approach for fixing the problem.

Comment (camsim99) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java]: My first instinct is to agree that this is not fully solving the problem.

@LailaiMaster can you clarify the use case that https://github.com/flutter/flutter/issues/180383 describes where:

1. The host application overrides `attachToEngineAutomatically` to return false and
2. `flutterView.attachToFlutterEngine(flutterEngine)` is not called by the host application (IIUC) before `View.onProvideAutofillVirtualStructure` is invoked for the first time?

I would assume `flutterView.attachToFlutterEngine(flutterEngine)` needs to be called pretty soon after `flutterView` is created to initialize all that the embedding needs to function. I assume doing so would avoid this issue, but please correct me if I'm wrong.

As an aside, if we do move forward with this change, we would need unit tests to test what happens when `textInputPlugin` is null.

Comment (LailaiMaster) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java]: This commit [commit](https://github.com/flutter/flutter/commit/75ac0d39577712c253b5410ac53e55dfd2e5a409) provides the rationale and code for allowing delayed engine attachment. An error caused by the same issue can be seen here: [issue](https://github.com/alibaba/flutter_boost/issues/2062) It's worth noting that a huge number of people use Flutter Boost for hybrid development, and Flutter Boost is a framework that promotes sharing the same engine. As a little joke, if Java were a null-safe language, this problem might not even exist. There's no need to add unit tests, because at this point the code doesn't need to execute at all. Perhaps it could be changed to `if (!isAttachedToFlutterEngine()) {}`, but I think that doesn't intuitively reflect the relationship between the plugin and the engine attachment behavior; instead, directly checking for null is easier to understand.

Comment (camsim99) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java]: From that commit:

> As an example, consider the following scenario: A native page contains multiple tabs, and each tab is a FlutterFragment. During initialization, FlutterFragments of different tabs are created almost simultaneously, but only the one that needs to be displayed currently requires attachment to the engine, while the others need to be attached only when they receive the |onResume| callback.

Thanks for pointing me towards this. That makes sense to me.

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java [hunk 2]
```diff
@@ -1576,12 +1576,16 @@ private void sendViewportMetricsToFlutter() {
...
+      textInputPlugin.onProvideAutofillVirtualStructure(structure, flags);
+    }
   }
 
   @Override
   public void autofill(@NonNull SparseArray<AutofillValue> values) {
-    textInputPlugin.autofill(values);
+    if(textInputPlugin != null) {
```
Comment (camsim99) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java]: Can you leave comments (here and in the null check above) explaining why this check is necessary for clarity?

**Review by camsim99 — COMMENTED** [review]
The case this addresses makes sense to me. We'll need (1) a second review (I'll request) and (2) a unit test to verify that if `textInputPlugin` is null, whichever method does not get called (can test this with [`verify`](https://javadoc.io/doc/org.mockito/mockito-core/latest/org.mockito/org/mockito/Mockito.html#4).

**Review by loic-sharma — COMMENTED** [review]
The solution sounds good to me, but I'll let the Android team do the second approval as I'm not an expert in this area. Please feel free to ping me again here if needed!

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java (hunk 2 above)
Comment (LailaiMaster) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java]: Sure, I've added comments to both null checks (in onProvideAutofillVirtualStructure and autofill) for better clarity. The comments explain that this defensive check prevents a NullPointerException when autofill is triggered and the Flutter engine hasn't been attached yet (e.g., when attachToEngineAutomatically is false). The early return in the null case ensures no further processing occurs in this uninitialized state, avoiding crashes without altering expected behavior. Let me know if you'd like any further adjustments!

**Review by camsim99 — COMMENTED** [review]
Looks good to me but still needs a test in case we accidentally regress this fix--you can use [verify](https://javadoc.io/doc/org.mockito/mockito-core/latest/org.mockito/org/mockito/Mockito.html#4) for this.

**Review by camsim99 — APPROVED** [review]
Thanks for the test--LGTM. Just need to fix formatting + a second review!

**Review by mboetger — APPROVED** [review]
LGTM
