### PR TITLE
RefreshIndicatorState.show()

### LINKED ISSUE #4833: Can I programmatically trigger a RefreshIndicator refresh?
If a refresh fails I want to show a SnackBar that lets the user "Try Again". I would love to be able to trigger the same RefreshIndicator UI when the "Try Again" action is pressed. Is there a straightforward way to accomplish this?

### PR DESCRIPTION
**Pull request by HansMuller**
Show the refresh indicator and run the refresh callback as if it had been started interactively.

Fixes #4833

### CODE REVIEW

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 1]
```diff
@@ -280,36 +282,56 @@ class _RefreshIndicatorState extends State<RefreshIndicator> {
...
 
+  /// Show the refresh indicator and run the refresh callback as if it had
+  /// been started interactively. If this method is called while the refresh
+  /// callback is running, it quietly does nothing.
+  ///
+  /// See also:
+  /// [GlobalKey] (creating the RefreshIndicator with a
+  /// [GlobalKey<RefreshIndicatorState>] will make it possible to refer to
+  /// the [RefreshIndicatorState] later)
+  Future<Null> show() async {
```
Comment (abarth) [inline packages/flutter/lib/src/material/refresh_indicator.dart]: Did you meant to await _show?  Currently you don't await anything so the future returned here isn't that useful.

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 2]
```diff
@@ -280,36 +282,56 @@ class _RefreshIndicatorState extends State<RefreshIndicator> {
...
   }
 
+  /// Show the refresh indicator and run the refresh callback as if it had
+  /// been started interactively. If this method is called while the refresh
+  /// callback is running, it quietly does nothing.
+  ///
+  /// See also:
+  /// [GlobalKey] (creating the RefreshIndicator with a
+  /// [GlobalKey<RefreshIndicatorState>] will make it possible to refer to
+  /// the [RefreshIndicatorState] later)
```
Comment (abarth) [inline packages/flutter/lib/src/material/refresh_indicator.dart]: To make this look pretty on the web site, you'll want a blank line after "see also" and `<space>*<space>` to make a bulleted list.

**Comment by abarth** [comment]
LGTM
