### PR TITLE
Fix native assets failing to build with AGP 8.4 and multiple flavors

### LINKED ISSUE #155038: Native assets fail to build on Android with AGP 8.4 and multiple flavors
Error message:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDevDebugJniLibFolders'.
> [arm64-v8a/libnative_regex_pcre2.so] /Users/Matej/Projects/superlist1/packages/superlist/build/native_assets/android/jniLibs/lib/arm64-v8a/libnative_regex_pcre2.so	[arm64-v8a/libnative_regex_pcre2.so] /Users/Matej/Projects/superlist1/packages/superlist/build/native_assets/android/jniLibs/lib/arm64-v8a/libnative_regex_pcre2.so	[arm64-v8a/libnative_regex_pcre2.so] /Users/Matej/Projects/superlist1/packages/superlist/build/native_assets/android/jniLibs/lib/arm64-v8a/libnative_regex_pcre2.so: Error: Duplicate resources
```

In this case there are three flavors and the library is added three times. I tracked it down to `flutter.groovy` where the `nativeAssetDir` is added to `project.android.sourceSets.main.jniLibs.srcDir` per flavor, even though the directory does not depend on the flavor. Should be easy to fix.

cc @dcharkes

### PR DESCRIPTION
**Pull request by knopp**
The nativeAssetDir is not flavor specific and it should only be added to the jniLibs.scrDir once.

Fixes https://github.com/flutter/flutter/issues/155038

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/gradle/src/main/groovy/flutter.groovy [hunk 1]
```diff
@@ -1430,10 +1430,10 @@ class FlutterPlugin implements Plugin<Project> {
                         }
                     }
                 }
-                // Copy the native assets created by build.dart and placed here by flutter assemble.
-                String nativeAssetsDir = "${project.buildDir}/../native_assets/android/jniLibs/lib/"
-                project.android.sourceSets.main.jniLibs.srcDir(nativeAssetsDir)
             }
+            // Copy the native assets created by build.dart and placed here by flutter assemble.
+            String nativeAssetsDir = "${project.buildDir}/../native_assets/android/jniLibs/lib/"
```
Comment (reidbaker) [inline packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:1435]: Expand the comment that this file is not flavor specific and should be only added once.

**Review by reidbaker — COMMENTED** [review]
Seems reasonable enough for me. This will need a test or test exemption (I would expect  them to say you need a test).

**Comment by knopp** [comment]
What would be a reasonable way to test this?

**Comment by reidbaker** [comment]
> What would be a reasonable way to test this?

Maybe take an existing test* that builds native assets and unzip the apk and verify that one folder is present. 

* @dcharkes or @HosseinYousefi can point you to any existing tests. 

The other option would be to write a groovy unit test. @gmackall who might be able to point out where one of those is already defined.

**Comment by gmackall** [comment]
> The other option would be to write a groovy unit test. @gmackall who might be able to point out where one of those is already defined.

I actually don't think we have any unit tests of groovy code, at least that I'm aware of

File: packages/flutter_tools/gradle/src/main/groovy/flutter.groovy [hunk 2]
```diff
@@ -1430,10 +1430,11 @@ class FlutterPlugin implements Plugin<Project> {
                         }
                     }
                 }
-                // Copy the native assets created by build.dart and placed here by flutter assemble.
-                String nativeAssetsDir = "${project.buildDir}/../native_assets/android/jniLibs/lib/"
-                project.android.sourceSets.main.jniLibs.srcDir(nativeAssetsDir)
             }
+            // Copy the native assets created by build.dart and placed here by flutter assemble.
+            // This path is not flavor specific and must only be added once.
+            String nativeAssetsDir = "${project.buildDir}/../native_assets/android/jniLibs/lib/"
```
Comment (dcharkes) [inline packages/flutter_tools/gradle/src/main/groovy/flutter.groovy:1436]: Add a reference to https://github.com/dart-lang/native/issues/1359, in case we add support for flavors to native assets. (And then we need to figure out how to only add it once per flavor and not duplicate it from all flavors.)

**Review by dcharkes — COMMENTED** [review]
🙏  Thanks for the report and the fix @knopp!

Maybe the integration test can be modified to try another AGP version:

* test/integration.shard/isolated/native_assets_test.dart

Also, we have some AGP version testing in

* test/integration.shard/android_plugin_example_app_build_test.dart

But I don't believe that that covers `package_ffi` yet. Maybe you could grok from that and a test/integration.shard/isolated/native_assets_agp_version_test.dart that combines the concepts of the two tests.

**Comment by reidbaker** [comment]
> > The other option would be to write a groovy unit test. @gmackall who might be able to point out where one of those is already defined.
> 
> I actually don't think we have any unit tests of groovy code, at least that I'm aware of

This is the example I was thinking of https://github.com/flutter/flutter/pull/125998/files#diff-5ecbf5765f9a06d24990a5b5c3cbcfd590b92e2e88f1463f8c4feaf74bea916a 

That said building with agp 8.4 also works for me.

**Comment by bkonyi** [comment]
@reidbaker @gmackall is there any update on this?

**Comment by gmackall** [comment]
> @reidbaker @gmackall is there any update on this?

I believe it still needs either a test or a test exemption.

I don't fully understand what conditions are needed to reproduce the issue that the PR fixes, is it specific to AGP 8.4? Could you build off of a test in `test/integration.shard/isolated/native_assets_test.dart`, as @dcharkes suggested?

**Comment by camsim99** [comment]
Just added a test for this that works for me locally. Looks like I'll need to fix some formatting and figure out why it's failing on CI!

File: packages/flutter_tools/test/integration.shard/isolated/native_assets_agp_version_test.dart [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+        final RegExp androidPluginRegExp =
+            RegExp(r'com\.android\.tools\.build:gradle:(\d+\.\d+\.\d+)');
+        final String newBuildGradle = buildGradle.replaceAll(
+            androidPluginRegExp, 'com.android.tools.build:gradle:$agpVersion');
+        buildGradleFile.writeAsStringSync(newBuildGradle);
+
+        // Use Android app with multiple flavors.
+        final String appBuildGradle = appBuildGradleFile.readAsStringSync();
+        final RegExp buildTypesBlockRegExp = RegExp(r'buildTypes {\n[ \t]+release {((.|\n)*)\n[ \t]+}\n[ \t]+}');
+        final String buildTypesBlock = buildTypesBlockRegExp.firstMatch(appBuildGradle)!.toString();
```
Comment (reidbaker) [inline packages/flutter_tools/test/integration.shard/isolated/native_assets_agp_version_test.dart:74]: On windows this line is failing. The mac failure appears to be infra so I think you can ignore it for now.

File: packages/flutter_tools/test/integration.shard/isolated/native_assets_agp_version_test.dart [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+/// The flow of compiling kernel as well as bundling dylibs can differ based on
+/// build mode, so we should cover this.
+const List<String> buildModes = <String>[
+  'debug',
+  'profile',
+  'release',
+];
+
+void main() {
+  if (!platform.isMacOS && !platform.isLinux && !platform.isWindows) {
```
Comment (reidbaker) [inline packages/flutter_tools/test/integration.shard/isolated/native_assets_agp_version_test.dart:37]: @camsim99 @andrewkolos is this the right way to exclude platforms? I seem to recall a parameter that can be set on pure dart tests but am not sure if we have a documented way in integration tests?

File: packages/flutter_tools/test/integration.shard/isolated/native_assets_agp_version_test.dart [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+          );
+          if (result.exitCode != 0) {
+            throw Exception('flutter build failed: ${result.exitCode}\n${result.stderr}\n${result.stdout}');
+          }
+
+          // Test that the native libraries are included as expected.
+          final Directory nativeAssetsDir = exampleDirectory
+            .childDirectory('build')
+            .childDirectory('app')
+            .childDirectory('..')
```
Comment (reidbaker) [inline packages/flutter_tools/test/integration.shard/isolated/native_assets_agp_version_test.dart:106]: In my experience .. means go up a directory. If that is the case then we can remove app and .. and just have build then native_assets.

File: packages/flutter_tools/test/integration.shard/isolated/native_assets_test_utils.dart [hunk 6]
```diff
@@ -0,0 +1,279 @@
...
+  if (result.exitCode != 0) {
+    throw Exception(
+      'flutter create failed: ${result.exitCode}\n${result.stderr}\n${result.stdout}',
+    );
+  }
+
+  final Directory packageDirectory = tempDirectory.childDirectory(packageName);
+
+  // No platform-specific boilerplate files.
+  expect(packageDirectory.childDirectory('android/'), isNot(exists));
```
Comment (reidbaker) [inline packages/flutter_tools/test/integration.shard/isolated/native_assets_test_utils.dart:34]: Since this is using `childDirectory` can we remove the trailing `/` and have the test have the same meaning? If so lets do that so that we dont have any issues with windows folder paths.

**Review by reidbaker — APPROVED** [review]

**Review by reidbaker — APPROVED** [review]

File: packages/flutter_tools/test/integration.shard/isolated/native_assets_agp_version_test.dart (hunk 4 above)
Comment (reidbaker) [reply packages/flutter_tools/test/integration.shard/isolated/native_assets_agp_version_test.dart:37]: That is good enough for me. If we hear back from the tooling team then we can file a bug and fix it later.
