### PR TITLE
fix(CircularProgressIndicator.adaptive): strokeWidth default value

### LINKED ISSUE #165294: [Material] ProgressIndicatorThemeData value strokeWidth does not work with CircularProgressIndicator.adaptive
### Steps to reproduce

Run MaterialApp with ProgressIndicatorThemeData config 

### Expected results

strokeWidth: 10.0

### Actual results

strokeWidth: 4.0

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: Colors.blue,
        progressIndicatorTheme: ProgressIndicatorThemeData(
          strokeWidth: 10.0,
          strokeCap: StrokeCap.round,
        ),
      ),
      home: const Scaffold(
        body: Center(
          child: CircularProgressIndicator.adaptive(),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

_No response_

### Flutter Doctor output

```
[✓] Flutter (Channel stable, 3.29.2, on Ubuntu 20.04.6 LTS 6.8.0-1021-azure, locale C.UTF-8) [172ms]
    • Flutter version 3.29.2 on channel stable at /home/codespace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (3 days ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Chrome - develop for the web [29ms]
    • CHROME_EXECUTABLE = /usr/bin/www-browser

[!] Flutter IDE Support (No supported IDEs installed) [17ms]
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (1 available) [947ms]
    • Chrome (web) • chrome • web-javascript • Lynx Version 2.9.0dev.5 (27 Feb 2020)
      libwww-FM 2.14, SSL-MM 1.4.1, GNUTLS 3.6.13, ncurses 6.2.20200212(wide)
      Built on linux-gnu.

      Copyrights held by the Lynx Developers Group,
      the University of Kansas, CERN, and other contributors.
      Distributed under the GNU General Public License (Version 2).
      See https://lynx.invisible-island.net/ and the online help for more information.

[✓] Network resources [468ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by StanleyCocos**
fix: https://github.com/flutter/flutter/issues/165294

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by StanleyCocos** [comment]
Could you take some time to review this request? cc @Piinks

File: packages/flutter/test/material/progress_indicator_test.dart [hunk 1]
```diff
@@ -433,6 +433,28 @@ void main() {
     expect(find.byType(CircularProgressIndicator), paints..arc(strokeWidth: 16.0));
   });
 
+  // Regression test for https://github.com/flutter/flutter/issues/165294
+  testWidgets('CircularProgressIndicator.adaptive stroke width', (WidgetTester tester) async {
+    await tester.pumpWidget(const CircularProgressIndicator.adaptive());
+
+    expect(find.byType(CircularProgressIndicator), paints..arc(strokeWidth: 4.0));
+
+    final ThemeData themeData = ThemeData(
```
Comment (vkdubey-google) [inline packages/flutter/test/material/progress_indicator_test.dart:442]: nit: Use theme.copyWith() similar to other such use cases in this file?

File: packages/flutter/test/material/progress_indicator_test.dart [hunk 2]
```diff
@@ -433,6 +433,28 @@ void main() {
...
+      progressIndicatorTheme: const ProgressIndicatorThemeData(strokeWidth: 10.0),
+    );
+    await tester.pumpWidget(
+      Theme(data: themeData, child: const CircularProgressIndicator.adaptive()),
+    );
+
+    expect(find.byType(CircularProgressIndicator), paints..arc(strokeWidth: 10.0));
+
+    await tester.pumpWidget(
```
Comment (vkdubey-google) [inline packages/flutter/test/material/progress_indicator_test.dart:451]: I'm just wondering if checking for multiple strokeWidth here is adding much value. If we already checked for 10, do we really need to check for 16 as well?

File: packages/flutter/test/material/progress_indicator_test.dart (hunk 1 above)
Comment (StanleyCocos) [reply packages/flutter/test/material/progress_indicator_test.dart:442]: sorry, I don’t quite understand what you mean. theme.copyWith() doesn’t seem to be related to this request.

Comment (vikdubey) [reply packages/flutter/test/material/progress_indicator_test.dart:442]: L22 has "final ThemeData theme = ThemeData();", and L92, L311 are the examples how copyWith() is used, instead of creating a new ThemeData object. Can we follow the same here?

File: packages/flutter/test/material/progress_indicator_test.dart (hunk 2 above)
Comment (vikdubey) [reply packages/flutter/test/material/progress_indicator_test.dart:451]: Would it be better to add comments to clarify this in the test body. 

Also, it might be better to remove comment "// Regression test for https://github.com/flutter/flutter/issues/165294", and add the details in the test name or test body so that one reading the test doesn't need to go through the attached issue and figure out the details from there.

IMO test name, comments, and code should suffice, and attaching link to github isssue should not be required.

Comment (StanleyCocos) [reply packages/flutter/test/material/progress_indicator_test.dart:452]: Updated. Thank you.

File: packages/flutter/test/material/progress_indicator_test.dart (hunk 1 above)
Comment (StanleyCocos) [reply packages/flutter/test/material/progress_indicator_test.dart]: Of course, but since I need to use an object twice, I save the object created by copyWith() to avoid duplicate code.

**Comment by StanleyCocos** [comment]
Would you mind taking another look? cc @vikdubey

**Comment by vikdubey** [comment]
> Would you mind taking another look? cc @vikdubey

Hi @StanleyCocos, sorry, I don't have approver rights. I'd request @dkwingsmt to review. Thanks.

**Comment by StanleyCocos** [comment]
> > 你介意再看一眼吗？ cc@vikdubey
> 
> 你好@StanleyCocos，抱歉，我没有批准者权限。我会请求@dkwingsmt以供审核。谢谢。

Thank you very much.

**Review by dkwingsmt — APPROVED** [review]
LGTM. Thank you!

**Review by QuncCccccc — APPROVED** [review]
Nice fix! Thanks for the contribution:) LGTM.

**Comment by StanleyCocos** [comment]
@dkwingsmt When you have time, could you please take a look at the reason for the Google test failure?

**Comment by dkwingsmt** [comment]
It was a flake and it has passed with a rerun.
