### PR TITLE
Replace NavigatorObserver._navigator with a static expando.

### LINKED ISSUE #109237: `NavigatorObserver._navigator` needs reworking due to an upcoming dart language change
The dart language team will soon be changing the behavior of the language so that an invocation of a private class members won't get dispatched to a `noSuchMethod` method in another library; instead an exception will be thrown.  This is a necessary prerequisite to allowing promotion of private fields (https://github.com/dart-lang/language/issues/2020).  It also closes an important privacy loophole in the language, by ensuring that the user can see all the possible behaviors of a private member invocation without having to look outside of the library.

This has an important consequence for tests using mockito, in the scenario where a private class member is referenced from outside of its containing class, and the containing class instance is replaced with a mock, but the reference isn't replaced with a mock.  Previously, in this scenario, the invocation would be dispatched to `Mock.noSuchMethod`; with the upcoming language change it will throw an exception.

This situation arises with `NavigatorObserver._navigator`, which is referenced from the `NavigatorState` class; if a test mocks `NavigatorObserver` but not `NavigatorState`, it will likely fail.  It could be argued that such tests should be rewritten to use a less brittle mocking strategy, but there are enough examples of this pattern in Google's internal code base that it seems likely that it exists in code belonging to other customers too.

After discussion with @goderbauer, we believe the best approach to avoid a widespread breakage is to rework `NavigatorObserver` in a way that preserves its user-facing API, but so that it doesn't contain a private member that's referred to by other classes.

### PR DESCRIPTION
**Pull request by stereotype441**
This change replaces `NavigatorObserver._navigator` (an instance field that points from a `NavigatorObserver` to the `NavigatorState` it's observing) with an expando that maps from `NavigatorObserver` to `NavigatorState`.  There is no change to the public API, and no change to the behavior of users' production code.

The change ensures that if a customer's test replaces an instance of `NavigatorObserver` with a mock, but doesn't replace `NavigatorState` with a mock, the code in `NavigatorState` won't try to access the private `_navigator` field in `NavigatorObserver`.  This is important because an upcoming change to the dart language is going to cause such accesses to throw exceptions (see https://github.com/flutter/flutter/issues/109237 and https://github.com/dart-lang/language/issues/2020 for details).

Fixes https://github.com/flutter/flutter/issues/109237.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 1]
```diff
@@ -619,8 +619,8 @@ abstract class Page<T> extends RouteSettings {
 /// An interface for observing the behavior of a [Navigator].
 class NavigatorObserver {
   /// The navigator that the observer is observing, if any.
-  NavigatorState? get navigator => _navigator;
-  NavigatorState? _navigator;
+  NavigatorState? get navigator => _navigators[this];
+  static final _navigators = Expando<NavigatorState>();
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:623]: Could you leave a comment on this Expando property describing why we are doing this. I am sure the next guy looking at this will be somewhat confused as to why we do this here.

Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:623]: (Also - as the analyzer check will hopefully remind you - this field needs to be typed)

**Review by goderbauer — COMMENTED** [review]
Could you add a test for this that makes sure a class implementing `NavigatorObserver` and `noSuchMethod` can be used as a Navigator.observer without problems? That way, if somebody tries to refactor this back to what it was we will have a failing test to warn them once field promotion lands.

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 1 above)
Comment (stereotype441) [reply packages/flutter/lib/src/widgets/navigator.dart]: Done.

Comment (stereotype441) [reply packages/flutter/lib/src/widgets/navigator.dart]: Done.

**Comment by stereotype441** [comment]
> Could you add a test for this that makes sure a class implementing `NavigatorObserver` and `noSuchMethod` can be used as a Navigator.observer without problems? That way, if somebody tries to refactor this back to what it was we will have a failing test to warn them once field promotion lands.

Ok, done.  I puzzled for a while over what the test should do, and what expectations it should check.  I finally settled on replicating the actions in one of the other simple navigator tests, and testing that the sequence of invocations passed to noSuchMethod is as expected.  Let me know if this seems reasonable.

**Review by goderbauer — APPROVED** [review]
LGTM once the checks are happy.
