### PR TITLE
TextField and last input character should visible on the screen when the cursor is not shown

### LINKED ISSUE #74566: Auto scroll not working with textField when showCursor is false
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:
```dart
return Scaffold(
      appBar: AppBar(
        title: Text('Sample'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            Container(
              height: 600,
              color: Colors.teal,
            ),
            TextField(
              showCursor: false,
              maxLength: 6,
              maxLengthEnforcement: MaxLengthEnforcement.enforced,
            ),
            Container(
              height: 500,
              color: Colors.redAccent,
            )
          ],
        ),
      ),
    );
```
3. Click the textField in the SingleChildScrollView, it would not show the textField

**Expected results:** 
cursor_show

**Actual results:** 
notworking

### PR DESCRIPTION
**Pull request by xu-baolin**
This patch fixes two bugs when setting `showCursor` to false,
1. The `TextField` did not bring into view when it under a scrollable widget.
2. The last input character did not remain on the screen when entering some long text.

Fixes #74566

### CODE REVIEW

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -2182,9 +2182,8 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     _showCaretOnScreenScheduled = true;
     SchedulerBinding.instance!.addPostFrameCallback((Duration _) {
       _showCaretOnScreenScheduled = false;
-      if (_currentCaretRect == null || !_scrollController!.hasClients) {
+      if (!_scrollController!.hasClients || !mounted)
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/editable_text.dart:2185]: When set `showCursor` to false `_currentCaretRect` will always be null because it only is assigned when the cursor is painted.

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:2185]: It is reasonable to add `!mounted` because it will access the RO below, although I haven't thought of what will happen if I don't.

File: packages/flutter/test/material/text_field_test.dart [hunk 2]
```diff
@@ -8574,6 +8574,36 @@ void main() {
...
+      ),
+    ));
+
+    // Tap the TextField to put the cursor into it and bring it into view.
+    expect(scrollController.offset, 0.0);
+    await tester.tapAt(tester.getTopLeft(find.byType(TextField)));
+    await tester.pumpAndSettle();
+
+    // The ListView has scrolled to keep the TextField visible.
+    expect(scrollController.offset, 50.0);
```
Comment (xu-baolin) [inline packages/flutter/test/material/text_field_test.dart:8604]: Please pay attention to the previous test case(line 8574). There are more scrolling by 2 pixels than set `showCursor` to true. It is because of the different algorithms. I did not try to keep them consistent, because I think this is not particularly important, right?

File: packages/flutter/lib/src/rendering/editable.dart [hunk 3]
```diff
@@ -2171,18 +2172,24 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+  }
 
-    if (caretRect != _lastCaretRect) {
-      _lastCaretRect = caretRect;
+  void _updateCaretRect() {
+    if (_currentCaretRect != _lastCaretRect) {
+      _lastCaretRect = _currentCaretRect;
       if (onCaretChanged != null)
-        onCaretChanged!(caretRect);
+        onCaretChanged!(_currentCaretRect);
```
Comment (xu-baolin) [inline packages/flutter/lib/src/rendering/editable.dart:2192]: The root cause of the issues is that the `caretRect` did not update to `EditableTextState._showCaretOnScreen`.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 4]
```diff
@@ -2356,17 +2363,20 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
     if (paintCursorAboveText)
       _textPainter.paint(context.canvas, effectiveOffset);
 
-    if (showCaret) {
+    if (canShowCaret) {
       assert(selection != null);
-      _paintCaret(context.canvas, effectiveOffset, selection!.extent);
+      _tryPaintCaret(context.canvas, effectiveOffset, selection!.extent);
+      _updateCaretRect();
```
Comment (xu-baolin) [inline packages/flutter/lib/src/rendering/editable.dart:2369]: We need the `cartRect` to bring `TextField` into view and scroll the long text although the `showCursor` is false.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart:2192]: What's the reason for splitting this stuff into a new method?  Now you must call both `_paintCaretIfNeeded` and `_updateCaretRect` back-to-back, which I worry someone might forget to do in the future.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 5]
```diff
@@ -2171,18 +2172,24 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
     }
 
     caretRect = caretRect.shift(_getPixelPerfectCursorOffset(caretRect));
+    _currentCaretRect = caretRect;
+
+    if (!_showCursor.value)
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:2177]: It seems simpler to check `_showCursor.value` inside of this method like this instead of outside like it was before 👍 .

**Review by justinmc — COMMENTED** [review]
Only one question to make sure everything is organized well, otherwise this looks great.  Thank you for fixing this!

**Comment by xu-baolin** [comment]
There is no special purpose, painting and updating are two different things and should not be put together, otherwise, the method name should be 'paintCursorAndUpdateCursorRect', but this is not in line with the principle that a function only do one thing. 
Personal opinion, it may not be correct.

**Review by justinmc — APPROVED** [review]
Alright that makes sense to me.  LGTM 👍
