### PR TITLE
Fix version command for certain git workflows

### LINKED ISSUE #15529: For devs who `git pull` instead of `flutter upgrade`, version calculation is wrong
## Steps to Reproduce

```bash
# Fetch remote refs on March 6 and not since
$ git pull upstream master
$ git reset --hard 4c7cc73
$ flutter doctor
```

## Expected Behavior

Because version `0.2.1` has been tagged at 6f5bcb9, the version should be `v0.2.2-pre.45`

## Actual Behavior

The version is reported as `v0.1.9-pre.124`, which indicates that the last tag the tool sees is `v0.1.8`.  Looking at the contents of my local tags confirms this:

```
$ ll .git/refs/tags/
total 224
drwxr-xr-x  30 tvolkert  eng  960 Mar  6 10:35 .
drwxr-xr-x   6 tvolkert  eng  192 Mar  6 10:36 ..
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.10
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.11
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.12
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.13
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.14
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.15
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.16
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.17
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.18
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.19
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.20
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.21
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.22
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.23
-rw-r--r--   1 tvolkert  eng   41 Feb  7 16:52 v0.0.24
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.6
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.7
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.8
-rw-r--r--   1 tvolkert  eng   41 Feb  7 09:41 v0.0.9
-rw-r--r--   1 tvolkert  eng   41 Feb 26 11:38 v0.1.0
-rw-r--r--   1 tvolkert  eng   41 Feb 26 11:38 v0.1.1
-rw-r--r--   1 tvolkert  eng   41 Feb 26 11:38 v0.1.2
-rw-r--r--   1 tvolkert  eng   41 Feb 26 11:38 v0.1.3
-rw-r--r--   1 tvolkert  eng   41 Feb 26 11:38 v0.1.4
-rw-r--r--   1 tvolkert  eng   41 Feb 26 11:38 v0.1.5
-rw-r--r--   1 tvolkert  eng   41 Feb 26 11:38 v0.1.6
-rw-r--r--   1 tvolkert  eng   41 Mar  1 08:25 v0.1.7
-rw-r--r--   1 tvolkert  eng   41 Mar  6 10:35 v0.1.8
```

The only way I see to solve this is to make `flutter doctor` fetch upstream refs, but that could have unintended consequences... @Hixie thoughts?

### PR DESCRIPTION
**Pull request by dnfield**
## Description

Fixes #15529 by running `git fetch https://github.com/flutter/flutter --tags` before trying to use tags to describe the current version.

If there is no network connection, the command just silently fails and we're no worse than we used to be. If there is a network connection, this will end up pulling down tags, and potentially updating the FETCH_HEAD.

## Related Issues

Fixes #15529 
additional context at #50577

## Tests

I added the following tests:

Updated version_test.dart to handle the new invocation of git.
Added a test that asserts we fetch the tags when we try to determine the version.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter_tools/lib/src/version.dart [hunk 1]
```diff
@@ -702,6 +702,7 @@ class GitTagVersion {
   final String hash;
 
   static GitTagVersion determine(ProcessUtils processUtils, [String workingDirectory]) {
+    _runGit('git fetch https://github.com/flutter/flutter --tags', processUtils, workingDirectory);
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/version.dart]: Would you mind making the repo URL a constant and adopting in `fetchRemoteFrameworkCommitDate()`? https://github.com/flutter/flutter/blob/323e8c17edc086b5a36b5c1afed8154a364d9e2e/packages/flutter_tools/lib/src/version.dart#L236

**Review by jmagman — APPROVED** [review]
LGTM with nit

File: packages/flutter_tools/lib/src/version.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter_tools/lib/src/version.dart]: Done
