### PR TITLE
don't resolve symlinks as part of which

### LINKED ISSUE #5164: flutter fails to run at keytool signing stage
## Steps to Reproduce

I am using Gentoo with java version

```
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

if that makes any difference.
.
I installed flutter on my system, ignoring the Atom install part

setup the path to flutter as instructed, and created an app called myapp, again following instructions

attached my android device via usb and made sure flutter could see it by running

```
flutter devices
```
with the output of

```
1 connected device:

Nexus 7 • 09337fc8 • android-arm
```

ran the command

```
flutter run
```

inside the directory where the app lives, as per instructions. 

At that point it seems it fails to run keytool which it uses to sign the generated apk to run on my attached device.  Output pasted below in the log and crash report section of this issue

## Flutter Doctor

[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/terrasea/flutter/flutter
    • Framework revision e42be3c363 (12 days ago), engine revision 3291edef41

[✓] Android toolchain - develop for Android devices (Android SDK 21.1.2)
    • Android SDK at /home/terrasea/Android/Sdk
    • Platform android-22, build-tools 21.1.2
    • Java(TM) SE Runtime Environment (build 1.8.0_77-b03)

[x] Atom - a lightweight development environment for Flutter
    x Atom not installed; download at https://atom.io.

## Logs and Crash Reports

```
Building APK in debug mode (android-arm)...              
Warning: signing the APK using the debug keystore.
* run-java-tool was invoked directly
* run-java-tool should only be used via symlinks to it
Exception from flutter run: Exit code 1 from: /usr/libexec/eselect-java/run-java-tool.bash -keystore /home/terrasea/flutter/flutter/bin/cache/artifacts/engine/android-arm/chromium-debug.keystore -storepass chromium -keypass chromium /tmp/flutter_toolsyXAJ93/app.apk.unaligned chromiumdebugkey
#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:188)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:130)
#2      _ApkBuilder.sign (package:flutter_tools/src/commands/build_apk.dart:125)
#3      _signApk (package:flutter_tools/src/commands/build_apk.dart:386)
#4      _buildApk (package:flutter_tools/src/commands/build_apk.dart:341)
#5      buildAndroid.<buildAndroid_async_body> (package:flutter_tools/src/commands/build_apk.dart:542)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#7      StackZoneSpecification.registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:135)
#8      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206)
#9      StackZoneSpecification.registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:135)
#10     _rootRunUnary (dart:async/zone.dart:1212)
#11     _CustomZone.runUnary (dart:async/zone.dart:1067)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#15     _Future._complete (dart:async/future_impl.dart:467)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#17     buildFlx.<buildFlx_async_body> (package:flutter_tools/src/flx.dart:307)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#19     StackZoneSpecification.registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:135)
#20     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206)
#21     StackZoneSpecification.registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:135)
#22     _rootRunUnary (dart:async/zone.dart:1212)
#23     _CustomZone.runUnary (dart:async/zone.dart:1067)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#25     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#26     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#27     _Future._complete (dart:async/future_impl.dart:467)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#29     assemble.<assemble_async_body> (package:flutter_tools/src/flx.dart:444)
#30     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#31     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206)
#32     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125)
#33     _rootRun (dart:async/zone.dart:1200)
#34     _CustomZone.run (dart:async/zone.dart:1056)
#35     _CustomZone.runGuarded (dart:async/zone.dart:954)
#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:981)
#37     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206)
#38     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125)
#39     _rootRun (dart:async/zone.dart:1204)
#40     _CustomZone.run (dart:async/zone.dart:1056)
#41     _CustomZone.runGuarded (dart:async/zone.dart:954)
#42     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:981)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#45     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

### PR DESCRIPTION
**Pull request by devoncarew**
- don't resolve symlinks as part of our `which` implementation (fix https://github.com/flutter/flutter/issues/5164)
- continue to resolve symlinks when we're looking for binaries in order to locate related SDKs. Some systems, like brew, will put symlinks to the tools in one `bin/` directory, but we want to know where those links resolve to in order to locate their parent SDK (line the Android SDK).

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
CC'ing flutter_tools hackers: @johnmccutchan @danrubel

File: packages/flutter_tools/lib/src/base/os.dart [hunk 1]
```diff
@@ -62,7 +62,7 @@ class _PosixUtils extends OperatingSystemUtils {
     if (result.exitCode != 0)
       return null;
     String path = result.stdout.trim().split('\n').first.trim();
-    return new File(new File(path).resolveSymbolicLinksSync());
+    return new File(path);
```
Comment (danrubel) [inline packages/flutter_tools/lib/src/base/os.dart]: If removing the symbolic link resolution, then the method comment should be updated.

**Comment by danrubel** [comment]
LGTM

File: packages/flutter_tools/lib/src/base/os.dart (hunk 1 above)
Comment (devoncarew) [inline packages/flutter_tools/lib/src/base/os.dart]: done
