### PR TITLE
print the os from flutter doctor

### LINKED ISSUE #2169: flutter and flutter --version keep telling me my atom dev environment and android sdk are good
I feel like that's extraneous information that's not important to flutter.  (ie. what if I'm a  developer that works in vi or emacs or something working on an iOS app, I'd have neither checked ever).

### LINKED ISSUE #2173: doctor and --version should print the platform that it's running on

### LINKED ISSUE #2863: flutterRoot read before being set (I guess?)
```
$ git clone https://github.com/flutter/flutter.git -b master
$ cd flutter/packages/flutter
$ ../../bin/flutter test --flutter-repo --no-current-directory --no-current-package
```
results in:
```
Invalid argument(s): join(null, "bin", "cache", "engine.version"): part 0 was null, but part 1 was not.
package:path/src/context.dart 925                                 _validateArgList
package:path/src/context.dart 220                                 Context.join
package:path/path.dart 244                                        join
package:flutter_tools/src/artifacts.dart 185                      ArtifactStore.engineRevision
package:flutter_tools/src/runner/version.dart 41                  FlutterVersion.engineRevision
package:flutter_tools/src/runner/version.dart 42                  FlutterVersion.engineRevisionShort
package:flutter_tools/src/doctor.dart 183                         _FlutterValidator.validate
package:flutter_tools/src/doctor.dart 59                          Doctor.summaryText
package:flutter_tools/src/runner/flutter_command_runner.dart 131  FlutterCommandRunner.usageFooter
package:args/command_runner.dart 57                               CommandRunner._usageWithoutDescription
package:args/command_runner.dart 86                               CommandRunner.usageException
package:args/command_runner.dart 116                              CommandRunner.parse
package:args/command_runner.dart 103                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 103                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 171  FlutterCommandRunner.run
package:flutter_tools/executable.dart 76                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 103                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 171  FlutterCommandRunner.run
package:flutter_tools/executable.dart 76                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 70                          main.<async>
```

### PR DESCRIPTION
**Pull request by devoncarew**
- print the OS from flutter doctor (fix https://github.com/flutter/flutter/issues/2173)
- don't show the doctor summary in flutter -h (fix https://github.com/flutter/flutter/issues/2169, and perhaps also fix https://github.com/flutter/flutter/issues/2863)

```
[✓] Flutter (macos)
    • Flutter root at /Users/devoncarew/projects/flutter/flutter
    • Framework revision d7e4f78 (12 minutes ago, channel master)
    • Engine revision b7419de
...
```

### CODE REVIEW

**Comment by devoncarew** [comment]
@Hixie, could you re-test #2863 w/ this? I don't currently have an engine build set up.

**Comment by abarth** [comment]
`macos` probably should be "Mac OS"

File: packages/flutter_tools/lib/src/doctor.dart [hunk 1]
```diff
@@ -179,11 +179,11 @@ class _FlutterValidator extends DoctorValidator {
 
     messages.add(new ValidationMessage('Flutter root at ${version.flutterRoot}'));
     messages.add(new ValidationMessage('Framework revision ${version.frameworkRevisionShort} '
-      '(${version.frameworkAge})'));
+      '(${version.frameworkAge}, channel ${version.channel})'));
     messages.add(new ValidationMessage('Engine revision ${version.engineRevisionShort}'));
 
     return new ValidationResult(ValidationType.installed, messages,
-      statusInfo: '${version.frameworkRevisionShort} - channel ${version.channel}');
+      statusInfo: Platform.operatingSystem);
```
Comment (abarth) [inline packages/flutter_tools/lib/src/doctor.dart]: I wonder if we should make these strings more human readable.

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
(I didn't re-test #2863)

File: packages/flutter_tools/lib/src/doctor.dart (hunk 1 above)
Comment (devoncarew) [inline packages/flutter_tools/lib/src/doctor.dart]: I could map them through a table of known os values -
