### PR TITLE
Stop recommending android sdk root

### LINKED ISSUE #117245: devicelab tests want ANDROID_SDK_ROOT but it is deprecated
If you run the devicelab tests it will complain that ANDROID_SDK_ROOT is not set.  But if you set it, you'll no longer be able to compile the flutter engine because of the following error:

```
* What went wrong:
Could not determine the dependencies of task ':app:lintDebug'.
> Several environment variables and/or system properties contain different paths to the SDK.
  Please correct and use only one way to inject the SDK location.
  
  ANDROID_HOME: /Users/aaclarke/dev/engine/src/third_party/android_tools/sdk
  ANDROID_SDK_ROOT: /Users/aaclarke/Library/Android/sdk
  
  It is recommended to use ANDROID_HOME as other methods are deprecated
```

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/117245

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/android_sdk.dart [hunk 1]
```diff
@@ -10,27 +10,27 @@ import '../convert.dart';
 import '../globals.dart' as globals;
 import 'java.dart';
 
-// ANDROID_HOME is deprecated.
+// ANDROID_SDK_ROOT is deprecated.
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/android_sdk.dart:13]: whoops

**Review by goderbauer — APPROVED** [review]
LGTM 🎉
