### PR TITLE
Fix crashes when current route parsing transactions are discarded

### LINKED ISSUE #100225: _CastError in _RouterState._verifyRouteInformationParserStillCurrent.<fn> at line 666
## Steps to Reproduce

This is an automated anonymous crash report. 
Breadcrumbs:
```
     {
        "timestamp": 1647315980.868,
        "type": "navigation",
        "category": "ui.lifecycle",
        "level": "info",
        "data": {
          "screen": "FlutterActivity",
          "state": "started"
        }
      },
      {
        "timestamp": 1647315980.882,
        "type": "session",
        "category": "app.lifecycle",
        "level": "info",
        "data": {
          "state": "start"
        }
      },
      {
        "timestamp": 1647315980.885,
        "type": "navigation",
        "category": "app.lifecycle",
        "level": "info",
        "data": {
          "state": "foreground"
        }
      },
      {
        "timestamp": 1647315980.892,
        "type": "navigation",
        "category": "ui.lifecycle",
        "level": "info",
        "data": {
          "screen": "FlutterActivity",
          "state": "resumed"
        }
      },
      {
        "timestamp": 1647315980.895,
        "type": "navigation",
        "category": "ui.lifecycle",
        "level": "info",
        "data": {
          "screen": "FlutterActivity",
          "state": "paused"
        }
      },
      {
        "timestamp": 1647315980.912,
        "type": "navigation",
        "category": "ui.lifecycle",
        "level": "info",
        "data": {
          "screen": "FlutterActivity",
          "state": "stopped"
        }
      },
      {
        "timestamp": 1647315980.919,
        "type": "navigation",
        "category": "ui.lifecycle",
        "level": "info",
        "data": {
          "screen": "FlutterActivity",
          "state": "saveInstanceState"
        }
      },
      {
        "timestamp": 1647315981.596,
        "type": "navigation",
        "category": "app.lifecycle",
        "level": "info",
        "data": {
          "state": "background"
        }
      },
      {
        "timestamp": 1647318133.644,
        "type": "session",
        "category": "app.lifecycle",
        "level": "info",
        "data": {
          "state": "end"
        }
      },
      {
        "timestamp": 1647321636.405,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STOPPED"
        }
      },
      {
        "timestamp": 1647321636.606,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_ON",
          "extras": {
            "why": "1"
          }
        }
      },
      {
        "timestamp": 1647321642.396,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STARTED"
        }
      },
      {
        "timestamp": 1647321642.833,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_OFF",
          "extras": {
            "reason": "2",
            "why": "3"
          }
        }
      },
      {
        "timestamp": 1647323101.389,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STOPPED"
        }
      },
      {
        "timestamp": 1647323101.642,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_ON",
          "extras": {
            "why": "2"
          }
        }
      },
      {
        "timestamp": 1647323114.821,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "ACTION_POWER_DISCONNECTED",
          "extras": {
            "seq": "4835"
          }
        }
      },
      {
        "timestamp": 1647323419.549,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STARTED"
        }
      },
      {
        "timestamp": 1647323419.918,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_OFF",
          "extras": {
            "reason": "2",
            "why": "3"
          }
        }
      },
      {
        "timestamp": 1647323701.565,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STOPPED"
        }
      },
      {
        "timestamp": 1647323701.946,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_ON",
          "extras": {
            "why": "2"
          }
        }
      },
      {
        "timestamp": 1647323713.459,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STARTED"
        }
      },
      {
        "timestamp": 1647323713.819,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_OFF",
          "extras": {
            "reason": "2",
            "why": "3"
          }
        }
      },
      {
        "timestamp": 1647324001.498,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STOPPED"
        }
      },
      {
        "timestamp": 1647324001.809,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_ON",
          "extras": {
            "why": "2"
          }
        }
      },
      {
        "timestamp": 1647324015.513,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STARTED"
        }
      },
      {
        "timestamp": 1647324015.894,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_OFF",
          "extras": {
            "reason": "2",
            "why": "3"
          }
        }
      },
      {
        "timestamp": 1647324158.627,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STOPPED"
        }
      },
      {
        "timestamp": 1647324158.868,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_ON",
          "extras": {
            "why": "2"
          }
        }
      },
      {
        "timestamp": 1647324164.803,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STARTED"
        }
      },
      {
        "timestamp": 1647324165.194,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_OFF",
          "extras": {
            "reason": "2",
            "why": "3"
          }
        }
      },
      {
        "timestamp": 1647324601.643,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STOPPED"
        }
      },
      {
        "timestamp": 1647324602.929,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_ON",
          "extras": {
            "why": "2"
          }
        }
      },
      {
        "timestamp": 1647324613.094,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STARTED"
        }
      },
      {
        "timestamp": 1647324613.48,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_OFF",
          "extras": {
            "reason": "2",
            "why": "3"
          }
        }
      },
      {
        "timestamp": 1647324797.686,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "DREAMING_STOPPED"
        }
      },
      {
        "timestamp": 1647324797.885,
        "type": "system",
        "category": "device.event",
        "level": "info",
        "data": {
          "action": "SCREEN_ON",
          "extras": {
            "why": "103"
          }
        }
      },
      {
        "timestamp": 1647324799.081,
        "type": "navigation",
        "category": "ui.lifecycle",
        "level": "info",
        "data": {
          "screen": "FlutterActivity",
          "state": "started"
        }
      },
      {
        "timestamp": 1647324799.091,
        "type": "session",
        "category": "app.lifecycle",
        "level": "info",
        "data": {
          "state": "start"
        }
      },
      {
        "timestamp": 1647324799.091,
        "type": "navigation",
        "category": "app.lifecycle",
        "level": "info",
        "data": {
          "state": "foreground"
        }
      },
      {
        "timestamp": 1647324799.095,
        "type": "navigation",
        "category": "ui.lifecycle",
        "level": "info",
        "data": {
          "screen": "FlutterActivity",
          "state": "resumed"
        }
      }
```

**Expected results:** 
No exception is thrown.

**Actual results:** 
```
_CastError: type 'Future<dynamic>' is not a subtype of type 'Future<Object>' in type cast
  File "router.dart", line 666, in _RouterState._verifyRouteInformationParserStillCurrent.<fn>
  File "zone.dart", line 1436, in _rootRunUnary
```

<details>
<summary>Code sample</summary>
No app code is involved.
Check `_RouterState` in this repo.

</details>

<details>
  <summary>Logs</summary>

N/A
```
```

```
No issues found!
```

App was built on CI, some time ago, so I could not execute shell commands. However, here is the relevant part of the log which is available:

```
Flutter 2.8.1 • channel unknown • unknown source
Framework • revision 77d935af4d (3 months ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

</details>

It looks like there is an issue with code here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/router.dart#L666

```
  static final Future<dynamic> _never = Completer<dynamic>().future; // won't ever complete

  _AsyncPassthrough<T> _verifyRouteInformationParserStillCurrent(Object? transaction, Router<T> originalWidget) {
    return (T data) {
//...
      return _never as Future<T>;
    };
  }
```
`dynamic` is not an `Object`

### PR DESCRIPTION
**Pull request by chunhtai**
There doesn't seem to be a way to create generic future that can be downward cast to any type. This pr refactor the logic around discarding parsing transaction

fixes https://github.com/flutter/flutter/issues/100225

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/router.dart [hunk 1]
```diff
@@ -632,7 +636,10 @@ class _RouterState<T> extends State<Router<T>> with RestorationMixin {
       .then<T>(_verifyRouteInformationParserStillCurrent(_currentRouteInformationParserTransaction, widget))
       .then<void>(delegateRouteSetter())
       .then<void>(_verifyRouterDelegatePushStillCurrent(_currentRouterDelegateTransaction, widget))
-      .then<void>(_rebuild);
+      .then<void>(_rebuild)
+      .onError<_DiscardTransaction>((_DiscardTransaction e, StackTrace trace) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/router.dart:640]: cc @Hixie who wrote the code i copied from. I am not sure whether  this may have performance implication, but this is the only way i can think of to skip the`then` future.

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/router.dart:640]: Could we refactor this into something like 

```dart
widget.routeInformationParser!
      .parseRouteInformation(information).then(_processParsedRouteInfo);
```

with:

```dart
Future<void> _processParsedRouteInfo(T data) async {
   if (route information parser no longer current) {
     return;
   }
   await _processParsedRouteInfo();
   if (route delegate push still current) {
     _rebuild();
   }
}
```

Doing it with exceptions feels a bit strange...

**Comment by chunhtai** [comment]
@goderbauer Thanks for review, this is ready for another look

**Review by goderbauer — APPROVED** [review]
LGTM
