### PR TITLE
Fixing AutomaticKeepAlive Docs

### LINKED ISSUE #48533: ListView documentation error
The `ListView` docs say:

```dart
///    Using [AutomaticKeepAlive] widgets (inserted by default when
///    [addAutomaticKeepAlives] is true). Instead of unconditionally caching the
///    child element subtree when scrolling off-screen like [KeepAlive],
///    [AutomaticKeepAlive] can let whether to cache the subtree be determined
///    by descendant logic in the subtree.
```

`[AutomaticKeepAlive] can let whether` this sounds weird, maybe there's a `know` missing? Like `cant let know  whether`?

### PR DESCRIPTION
**Pull request by feinstein**
## Description

Fixed missing word

## Related Issues

Fixes #48533

## Tests

I added the following tests:

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
  

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by feinstein** [comment]
@Hixie I need an exemption from the tests rule, as this is only a documentation fix, Thanks.

File: packages/flutter/lib/src/widgets/scroll_view.dart [hunk 1]
```diff
@@ -735,7 +735,7 @@ abstract class BoxScrollView extends ScrollView {
 ///  * Using [AutomaticKeepAlive] widgets (inserted by default when
 ///    [addAutomaticKeepAlives] is true). Instead of unconditionally caching the
 ///    child element subtree when scrolling off-screen like [KeepAlive],
-///    [AutomaticKeepAlive] can let whether to cache the subtree be determined
+///    [AutomaticKeepAlive] can let know whether to cache the subtree be determined
```
Comment (dnfield) [inline packages/flutter/lib/src/widgets/scroll_view.dart]: For both of these, I'm not sure this actually makes things better.

AutomaticKeepAlive can let _what_ or _who_ know?

The problem right now is that the sentence is just awkwardly structured. We should just rewrite these two lines to be clearer about responsible parties and what those parties actually do.

**Comment by Hixie** [comment]
testing exemption: sure

but I don't understand the patch, the original grammar seems fine

File: packages/flutter/lib/src/widgets/scroll_view.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/scroll_view.dart]: For example,

```
///  * Using [AutomaticKeepAlive] widgets (inserted by default when
///    [addAutomaticKeepAlives] is true). [AutomaticKeepAlive] allows descendant
///    widgets to control whether the subtree is actually kept alive or not.
///    This behavior is in contrast with [KeepAlive], which will unconditionally keep
///    the subtree alive.
```

**Comment by feinstein** [comment]
@Hixie `can let whether` sounds weird to me, like something is missing, maybe the English is correct and it's a construct I am not used to, but  consulted with some friends to know how it sounds to them (all living in the USA) and they agreed there's something weird. But `can let know whether` makes sense to all of us, at least it doesn't sound as if there's a word missing.

`Can let whether` - Can let what?
`Can let know whether` - Can let know to whom?

I agree with @dnfield and the whole text should be clearer.

**Comment by Hixie** [comment]
It's not `can let whether` it's `can let [whether to xyz] be determined by [abc]`

**Comment by Hixie** [comment]
that said i'm fine with it being made clearer, it's just that the change proposed here isn't clearer, it's less correct. :-)

**Comment by feinstein** [comment]
@Hixie reading it again after your explanation it still sounds a bit weird to me, maybe there's a comma missing, or maybe that language construct is hard for brazilians to catch, or just maybe I need to remove "fluent english" from my resume :P 

I will update it with the new text made by @dnfield thank you everyone for your attention on this.

**Comment by goderbauer** [comment]
Looks like you have some trailing white space as pointed out by the analyzer: https://github.com/flutter/flutter/pull/48575/checks?check_run_id=385182538

Can you remove those? After that, the change LGTM.

**Review by dnfield — APPROVED** [review]
LGTM.  As @goderbauer said just fix the trailing whitespace.

One thing I do is set my editor to remove trailing whitespace on save :)

**Comment by feinstein** [comment]
@dnfield me too, but I edited those files online using github's editor, as it's easier for those simple cases than just do the whole git procedure.
