### PR TITLE
Catch file system exceptions when trying to parse user-provided asset file paths

### LINKED ISSUE #141211: [flutter_tools] UnsupportedError at _Uri._checkWindowsPathReservedCharacters when parsing file entries with invalid characters in assets section in pubspec.yaml
Highly related: https://github.com/flutter/flutter/issues/140092

Repro steps (Windows host only):

* Create a new flutter project.
* In the `assets` section of your pubspec, add a file path that includes : anywhere in the path (such as `https://website.com/file.png`)
* flutter run -d chrome (the crash does not happen when using -d windows).

Stack trace (https://github.com/flutter/flutter/commit/29db9dbd44b1dbf781a84318811db676aadd6fd7):

```

FileSystemException: FileSystemException: Exists failed, path = 'C:\Users\Jozz\Desktop\deleteme\assets_test\http:\\whitehouse.gov' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)

#0      _Directory.existsSync (dart:io/directory_impl.dart:87:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:490:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:489:12)
#5      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:1254:43)
#6      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:974:37)
#7      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:829:9)
#8      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:267:54)
<asynchronous suspension>
#9      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:531:26)
<asynchronous suspension>
#10     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:319:41)
<asynchronous suspension>
#11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```

### PR DESCRIPTION
**Pull request by andrewkolos**
Fixes #141211

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/asset.dart [hunk 1]
```diff
@@ -1285,8 +1285,16 @@ class _AssetDirectoryCache {
   List<String> variantsFor(String assetPath) {
     final String directory = _fileSystem.path.dirname(assetPath);
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/asset.dart:1286]: nit maybe name this directoryName?

File: packages/flutter_tools/lib/src/asset.dart [hunk 2]
```diff
@@ -1285,8 +1285,16 @@ class _AssetDirectoryCache {
...
 
-    if (!_fileSystem.directory(directory).existsSync()) {
-      return const <String>[];
+    try {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/asset.dart:1288]: can we catch this at the file, and not directory level?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/asset.dart:1288]: per andrew, not a blocker.

Comment (andrewkolos) [reply packages/flutter_tools/lib/src/asset.dart:1301]: I learned that that `existsSync` only throws this exception in the scenario where entity in question is a directory (not a file).

File: packages/flutter_tools/lib/src/asset.dart [hunk 3]
```diff
@@ -1296,17 +1296,25 @@ class _AssetDirectoryCache {
...
+      if (!_fileSystem.directory(directoryName).existsSync()) {
+        return const <String>[];
+      }
+    } on FileSystemException catch (e) {
+      throwToolExit(
+        'Unable to check the existence of asset file "$assetPath". '
+        'Ensure that the asset file is declared is a valid local file system path.\n'
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/asset.dart:1308]:
```diff
-'Ensure that the asset file is declared is a valid local file system path.\n'
+'Ensure that the asset file is declared and is a valid local file system path.\n'
```

**Comment by andrewkolos** [comment]
@christopherfujino FYI I'm rewriting the test to be hermetic. Converting to draft.

File: packages/flutter_tools/test/general.shard/asset_bundle_test.dart [hunk 4]
```diff
@@ -177,6 +177,35 @@ flutter:
...
+    }, overrides: <Type, Generator>{
+      FileSystem: () => MemoryFileSystem(style: FileSystemStyle.windows,
+      opHandle: (String context, FileSystemOp operation) {
+        if (operation == FileSystemOp.exists && context == r'C:\http:\\website.com') {
+          throw const FileSystemException(
+            r"FileSystemException: Exists failed, path = 'C:\http:\\website.com' "
+            '(OS Error: The filename, directory name, or volume label syntax is '
+            'incorrect., errno = 123)',
+          );
+        }
```
[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/asset_bundle_test.dart:203]: I would never have expected it to look like this, with backslashes. Do you know why it looks like this? Or should we just chalk this up to URI weirdness (interpreting a web url as a file uri things get escaped weird)?

File: packages/flutter_tools/test/general.shard/asset_bundle_test.dart [hunk 5]
```diff
@@ -177,6 +177,35 @@ flutter:
...
+      },),
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/asset_bundle_test.dart:204]: can you put a newline in between here?

**Comment by christopherfujino** [comment]
> @christopherfujino FYI I'm rewriting the test to be hermetic. Converting to draft.

oops, just saw this, SGTM

File: packages/flutter_tools/test/general.shard/asset_bundle_test.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/asset_bundle_test.dart:203]: It's probably happening here: https://github.com/flutter/flutter/blob/7839b8eb00d89bc199fd5c883018352f2156a42d/packages/flutter_tools/lib/src/asset.dart#L1217-L1219

We are working with URIs (which are, AFAIK, agnostic of separator styles, always using `/`). We are then asking `fileSystem` to turn that URI into something that is a valid path on the local file system.

[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/asset_bundle_test.dart:203]: > which are, AFAIK, agnostic of separator styles, always using /

We are working with URIs (which are, AFAIK, agnostic of separator styles, always using /). We are then asking fileSystem to turn that URI into something that is a valid path on the local file system, which probably turns /s into \s.

**Comment by andrewkolos** [comment]
Ready again. I did some tidying up before I left, making the diff bigger. See the recent commits with `refactor` in the message to help yourself make sense of it.

File: packages/flutter_tools/lib/src/asset.dart [hunk 6]
```diff
@@ -958,7 +958,7 @@ class ManifestAssetBundle implements AssetBundle {
     } on UnsupportedError catch (e) {
       throwToolExit(
         'Unable to search for asset files in directory path "${assetUri.path}". '
-        'Please ensure that this is valid URI that points to a directory '
+        'Please ensure that this is a valid URI that points to a directory '
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/asset.dart:961]: nit avoid referring to URIs. Maybe "Please ensure that this path exists and your current user has permissions." or some such

File: packages/flutter_tools/test/general.shard/asset_bundle_test.dart [hunk 7]
```diff
@@ -361,180 +335,99 @@ flutter:
...
-        );
-
-        await bundle.build(
-          packagesPath: '.packages',
-          flutterProject: FlutterProject.fromDirectoryTest(testFileSystem.currentDirectory),
-          flavor: flavor,
-        );
-        return bundle;
-      }
+  group('AssetBundle.build (hermetic)', () {
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/asset_bundle_test.dart:340]: why hermetic in the group name? are some of these not hermetic?

File: packages/flutter_tools/test/general.shard/asset_bundle_test.dart [hunk 8]
```diff
@@ -361,180 +335,99 @@ flutter:
...
+    testUsingContext('throws ToolExit when directory entry contains invalid characters (Windows only)', () async {
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/asset_bundle_test.dart:341]: What globals are we referencing from the context, and should we explicitly override them?

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/asset_bundle_test.dart:341]: I ask because these types of tests make it easy to write tests that look like we're creating the appropriate fakes, while the test under code silently uses real globals it got from the context.

**Review by christopherfujino — APPROVED** [review]
A few nit questions, but LGTM, this is a good cleanup!

File: packages/flutter_tools/test/general.shard/asset_bundle_test.dart (hunk 7 above)
Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/asset_bundle_test.dart:340]: Yes, see the group above named "AssetBundle.build"

File: packages/flutter_tools/test/general.shard/asset_bundle_test.dart (hunk 8 above)
Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/asset_bundle_test.dart:341]: This was a mistake. I forgot to change this to `testWithoutContext`. Working on it.

File: packages/flutter_tools/test/general.shard/asset_bundle_test.dart (hunk 7 above)
Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/asset_bundle_test.dart:340]: Alternatively, I can rename the other group to `AssetBundle.build (non-hermetic)`

Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/asset_bundle_test.dart:340]: Basically the point of this was I didn't want to reuse the polluted scope of the existing group

File: packages/flutter_tools/lib/src/asset.dart (hunk 6 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/asset.dart]: Addressed.

File: packages/flutter_tools/test/general.shard/asset_bundle_test.dart (hunk 8 above)
Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/asset_bundle_test.dart]: Addressed.

File: packages/flutter_tools/test/general.shard/asset_bundle_test.dart [hunk 9]
```diff
@@ -24,18 +24,16 @@ import 'package:standard_message_codec/standard_message_codec.dart';
...
 import '../src/context.dart';
 
-const String shaderLibDir = '/./shader_lib';
-
 void main() {
-  group('AssetBundle.build', () {
-    late Logger logger;
+  const String shaderLibDir = '/./shader_lib';
+
+  group('AssetBundle.build (non-hermetic)', () {
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/asset_bundle_test.dart:30]: in what ways are these non-hermetic? ideally we would either make them hermetic, or move them to the integration shard if they must use the real environment.

Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/asset_bundle_test.dart:30]: I'm uncomfortable calling anything that uses `testUsingContext` hermetic. If you ignore the lack of a `Logger` override, these tests are _probably_ hermetic, so perhaps the `non-hermetic` label is unfair. If you have better ideas for group names, I'm all ears (perhaps "using context" and "not using context").

The reason the groups are separate is that one uses `setUp` (polluting the scope with `testFileSystem` and `platform`) and `testUsingContext` (both of which are not recommended for use), and the latter group is more idiomatic. 

I do not wish the rewrite all of these tests to be idiomatic now, as this would be a significant undertaking, and I lack the needed bandwidth.

Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/asset_bundle_test.dart]: addressed in [tweak group name](https://github.com/flutter/flutter/pull/142214/commits/f76d7039365d98f9f73bee27be549fe2f579c630)

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/asset_bundle_test.dart]: ahh, I see, thanks for the explanation!
