### PR TITLE
[ Device Lab ] Fix wakefulness check to only match log entries with string values

### LINKED ISSUE #174948: Linux_pixel_7pro tests increasingly flakey
A bunch of Linux_pixel_7pro are failing in post-submit with this error:

```
[2025-09-04 00:35:05.893558] [STDERR] Task failed: Bad state: Too many elements
 [2025-09-04 00:35:05.893772] [STDERR] 
 [2025-09-04 00:35:05.893802] [STDERR] Stack trace:
 [2025-09-04 00:35:05.911669] [STDERR] dart:core                                                  Iterable.single
 [2025-09-04 00:35:05.911731] [STDERR] package:flutter_devicelab/framework/devices.dart 689:73    AndroidDevice._getWakefulness
 [2025-09-04 00:35:05.911739] [STDERR] ===== asynchronous gap ===========================
 [2025-09-04 00:35:05.911748] [STDERR] dart:async                                                 _CustomZone.registerBinaryCallback
 [2025-09-04 00:35:05.911758] [STDERR] package:flutter_devicelab/framework/framework.dart 309:28  _TaskRunner._performTask.<fn>
 [2025-09-04 00:35:05.911769] [STDERR] package:stack_trace                                        Chain.capture
 [2025-09-04 00:35:05.911778] [STDERR] package:flutter_devicelab/framework/framework.dart 307:11  _TaskRunner._performTask
 [2025-09-04 00:35:05.911796] [STDERR] package:flutter_devicelab/framework/framework.dart 200:43  _TaskRunner.run
 [2025-09-04 00:35:05.911806] [STDERR] 
 [2025-09-04 00:35:05.914682] [STDOUT] Checking for reboot
 [platform_interaction_test] Process terminated with exit code 0.
```

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20platform_interaction_test/9260/overview

It's crashing on usage of `single`:
https://github.com/flutter/flutter/blob/6e9286d6ebc17a2301ff31fdc8ec39d3a0d8e774/dev/devicelab/lib/framework/devices.dart#L689

Looks like it's now returning two values for `mWakefulness`:

```
mWakefulness=Awake
...
 mWakefulness=1
```

### PR DESCRIPTION
**Pull request by bkonyi**
Sometimes there can be multiple wakefulness log entries (e.g., 'mWakefulness=Awake' and 'mWakefulness=1'), but we only care about the entry with a string value.

Fixed https://github.com/flutter/flutter/issues/174948

### CODE REVIEW

**Comment by bkonyi** [comment]
This fixes the flaky failures currently making the tree red ([example](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20new_gallery_impeller__transition_perf/6185/overview)).

**Review by jason-simmons — APPROVED** [review]

File: dev/devicelab/lib/framework/devices.dart [hunk 1]
```diff
@@ -685,7 +685,7 @@ class AndroidDevice extends Device {
     final String powerInfo = await shellEval('dumpsys', <String>['power']);
     // A motoG4 phone returns `mWakefulness=Awake`.
     // A Samsung phone returns `getWakefullnessLocked()=Awake`.
-    final RegExp wakefulnessRegexp = RegExp(r'.*(mWakefulness=|getWakefulnessLocked\(\)=).*');
+    final RegExp wakefulnessRegexp = RegExp(r'(?:mWakefulness|getWakefulnessLocked\(\))=[a-zA-Z]+');
     final String wakefulness = grep(wakefulnessRegexp, from: powerInfo).single.split('=')[1].trim();
```
Comment (gaaclarke) [inline dev/devicelab/lib/framework/devices.dart:689]: nit: we should use capture groups instead of doing string manipulation on the result

**Review by gaaclarke — CHANGES_REQUESTED** [review]
Can we get a test for this?

**Comment by bkonyi** [comment]
I'm stepping out for a bit, so let's let this land to unblock the tree and
I can follow up with the suggested changes.

We do have tests verifying the regex matches correctly, so the expression
itself is tested. I'll add a negative test to ensure we don't accidentally
match `mWakefulness=1`.

**Review by reidbaker — APPROVED** [review]
