### PR TITLE
[framework] Fix Text.semanticsIdentifier being absorbed by ancestor nodes

### LINKED ISSUE #180894: semanticsIdentifier of Text widget does not applied Semantic to it when used in Dialog widget with showDialog
### Steps to reproduce

Use below dartpad link where I have added this example to reproduce the issue. 
[Dart pad link](https://dartpad.dev/c4dfd4225ec70dc77fe55183eec947ec)

Run the application and open inspect console and paste 
`document.querySelector('[aria-label="Enable accessibility"]').click();` to enable element selection. 

Encounter if we use below only, Text element won't be identified.
```dart
Text( 'I should have the Semantics', semanticsIdentifier:'From Text Parameter',) 
```

However, if we use below, Text element will be identified.
```dart
Semantics(identifier: 'From Semantics',container: true, child: Text( 'I should have the Semantics', semanticsIdentifier:'From Text Parameter',) )
```

Whaat would be the reason for first part of code where Semantics are not identified using the `Text` paramenter?

### Expected results

It should identify the Text element same as what it can do with `Semantics` widget having container as true.

### Actual results

It's not identifying `Text` element with `semanticsIdentifier` parameter only.   

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const DialogTextSemantics(),
    );
  }
}

class DialogTextSemantics extends StatefulWidget {
  const DialogTextSemantics({super.key});

  @override
  State<DialogTextSemantics> createState() => _DialogTextSemanticsState();
}

class _DialogTextSemanticsState extends State<DialogTextSemantics> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            showDialog(
                context: context,
                builder: (bContext) {
                  return Material(
                    color: Colors.transparent,
                    child: Dialog(
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(4)),
                      child: SizedBox(
                        width: 800,
                        child: Padding(
                          padding: const EdgeInsets.all(16.0),
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Row(
                                children: [
                                  IconButton(
                                      onPressed: () {
                                        Navigator.of(bContext).pop();
                                      },
                                      icon:
                                          const Icon(Icons.arrow_back_rounded)),
                                  Expanded(
                                    // this below Semantics does help to identify the element using element selection
                                    child: Semantics(
                                      identifier: 'From Semantics',
                                      container: true,
                                      child: const Text(
                                        'I should have the Semantics',
                                        // this does not let the element identified using element selection
                                        // semanticsIdentifier:
                                        //     'From Text Parameter',
                                      ),
                                    ),
                                  ),
                                  IconButton(
                                      onPressed: () {
                                        Navigator.of(bContext).pop();
                                      },
                                      icon: const Icon(Icons.close_rounded)),
                                ],
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  );
                });
          },
          child: const Text('Click Here'),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image
Image
Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
purvikrana@Purviks-MacBook-Pro dialog_text_semantics % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.35.7, on macOS 26.1 25B78 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    ! CocoaPods 1.14.3 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.96.4)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for Purvik Rana. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Purvik’s Apple Watch. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
purvikrana@Purviks-MacBook-Pro dialog_text_semantics % 
```

</details>

### PR DESCRIPTION
**Pull request by flutter-zl**
Problem: Text widget's semanticsIdentifier was being absorbed into ancestor semantic nodes (like Dialog) instead of creating its own semantic element.

Root Cause: The Semantics wrapper in Text didn't set container: true, allowing the identifier to be merged upward during semantics tree construction.

Fix: Added container: semanticsIdentifier != null to the Text widget's Semantics wrapper.

Fixes #180894.

Before
https://flutter-demo-11-before.web.app/

After
https://flutter-demo-11-after.web.app/

### CODE REVIEW

File: packages/flutter/lib/src/widgets/text.dart [hunk 1]
```diff
@@ -804,6 +804,9 @@ class Text extends StatelessWidget {
         textDirection: textDirection,
         label: semanticsLabel,
         identifier: semanticsIdentifier,
+        // Fix for issue #180894: When semanticsIdentifier is provided, set container: true
+        // to prevent the identifier from being absorbed into ancestor semantic nodes.
+        container: semanticsIdentifier != null,
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/text.dart]: semanticsIdentifier IIRC is mostly for unittest and uiautomation test, letting it change tree shape seems weird. This seems a bit drastic to fix the root cause, i.e. dialog role ignored semantics identifier.

Comment (mdebbar) [reply packages/flutter/lib/src/widgets/text.dart]: @chunhtai we could look at `semanticsIdentifier` as being a signal from the user wanting to have a reference to this semantics node, so we should not merge it up.

That being said, if we decide to go this route, the fix should be more general, not only for the Text widget.

Comment (flutter-zl) [reply packages/flutter/lib/src/widgets/text.dart]: Make fix more general at SemanticsConfiguration level. Please review.

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 2]
```diff
@@ -6693,6 +6693,9 @@ class SemanticsConfiguration {
     if (_maxValue != null && other._maxValue != null) {
       return false;
     }
+    if (other._identifier.isNotEmpty) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/semantics/semantics.dart]: We don't promise how this is called, for example other may be the parent, child, or sibling. but this code will depends on how the api is called to do the right thing.

I assume the intention is that we are ok if a child merge to a "parent that has identifier", but disallows a "child that has identifer" to merge to parent? the code here will fail if we somehow do child.isCompatableWith(parent).

We may need find a different way around it.

Comment (flutter-zl) [reply packages/flutter/lib/src/semantics/semantics.dart]: Good catch. I've updated the logic. Now when identifier is set, isSemanticBoundary is set to true, which forces a dedicated SemanticsNode before merging is even considered. This avoids the isCompatibleWith directionality issue entirely.

File: packages/flutter/lib/src/rendering/object.dart [hunk 3]
```diff
@@ -4786,7 +4786,7 @@ mixin SemanticsAnnotationsMixin on RenderObject {
   @override
   void describeSemanticsConfiguration(SemanticsConfiguration config) {
     super.describeSemanticsConfiguration(config);
-    config.isSemanticBoundary = container;
+    config.isSemanticBoundary = container || (_properties.identifier != null);
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/object.dart:4789]: can you also update the doc for _SemanticsBase.container and SemanticsProperty.identifier to mention this behavior?

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/object.dart:4789]: also this may be a potential breaking change even if it is not breaking customer test, so should watchout after merge.

**Review by chunhtai — COMMENTED** [review]
LGTM, just some minor comments

File: packages/flutter/lib/src/rendering/object.dart (hunk 3 above)
Comment (flutter-zl) [reply packages/flutter/lib/src/rendering/object.dart:4789]: 1. I updated the docs.
2. Good point. I'll keep an eye on it after landing.

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by chunhtai — APPROVED** [review]
LGTM
