### PR TITLE
Fix update drag error that made NestedScrollView un-scrollable

### LINKED ISSUE #32563: NestedScrollView won't scroll using SliverOverlapAbsorber and few items (and other related bugs)
Hi! I've made a single file demo screen showing how NestedScrollView won't scroll if the amount of scroll available is less of some unknown threshold if SliverOverlapAbsorber is used as well. The widget presented next will calculate some amount of items to reproduce this issue in any screen size.

Also, AppBar doesn't seem to work in floating mode in this same condition.

## Steps to Reproduce

Just render this widget:

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

class TestPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      /*
        Using LayoutBuilder to calculate the amount of
        items to print depending on screen height
      */
      home: LayoutBuilder(
        builder: (context, box)=>Scaffold(
          body: NestedScrollView(
            headerSliverBuilder: (context, innerScrolled)=>[
              SliverOverlapAbsorber(
                handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                child: SliverAppBar(
                  forceElevated: innerScrolled,
                  pinned: true,
                  title: Text("Printing ${(box.maxHeight/20).floor()} items"),
                ),
              ),
            ],
            body: Builder(
              builder: (context)=>CustomScrollView(
                slivers: <Widget>[
                  SliverOverlapInjector(
                    handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                  ),
                  SliverList(
                    delegate: SliverChildListDelegate(
                      [
                        for (var i=0; i<box.maxHeight/20; i++)
                          Text("Some text $i", style: TextStyle(fontSize: 20)),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

}
```
</details>

## `flutter doctor` output

<details>
<summary>flutter doctor -v</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```
</details>

### LINKED ISSUE #45619: Document how NestedScrollView.physics/scrollDirection/reverse affect outer/inner scroll views
I read code ,find this code in scrollable.dart

 ```dart
void _updatePosition() {
    _configuration = ScrollConfiguration.of(context);
    _physics = _configuration.getScrollPhysics(context);
    if (widget.physics != null)
      _physics = widget.physics.applyTo(_physics);
    final ScrollController controller = widget.controller;
    final ScrollPosition oldPosition = position;
    if (oldPosition != null) {
      controller?.detach(oldPosition);
      // It's important that we not dispose the old position until after the
      // viewport has had a chance to unregister its listeners from the old
      // position. So, schedule a microtask to do it.
      scheduleMicrotask(oldPosition.dispose);
    }

    _position = controller?.createScrollPosition(_physics, this, oldPosition)
      ?? ScrollPositionWithSingleContext(physics: _physics, context: this, oldPosition: oldPosition);
    assert(position != null);
    controller?.attach(position);
  }

```

### LINKED ISSUE #46089: NestedScrollView does not allow nested scrolling when content extent is less than 2 x viewport height.
## Steps to Reproduce

A `NestedScrollView` containing a `CustomScrollView` (or perhaps any scrolling view) with content less than twice the `viewportDimension` (screen height) will not permit scrolling.

One possible source for this behavior seems to be `_NestedScrollPosition.updateCanDrag`, which compares the `totalExtent` it receives (which is derived from `maxScrollExtent`) with `viewportDimension` (which has already been subtracted from the `maxScrollExtent` in `RenderViewport.performLayout` around line 1279). Replacing `viewportDimension` with `0.0` in `updateCanDrag` fixes my observed issue, but might have other side effects I'm not aware of.

Tested on 1.10.7 and master (v1.12.17-pre.67). Same behavior for debug/emulator as for release/device.

A simple example to demonstrate (though this can also be observed by using the example from the NestedScrollView documentation, by reducing the number of items from 30 to something extending just beyond the screen):

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: NestedScrollProblem()));

class NestedScrollProblem extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
    body: NestedScrollView(
      headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) => <Widget>[ ],
      body: SingleChildScrollView(
        child: Container(
          margin: EdgeInsets.all(8.0),
          alignment: Alignment.center,
          color: Colors.red,
          constraints: BoxConstraints.tight(MediaQuery.of(context).size + Offset(0.0, 100.0)),
          child: Text("This should be scrollable"),
        ),
      ),
    ),
  );
}
```

**Target Platform:** Android/iOS

## Logs
```
[√] Flutter (Channel master, v1.12.17-pre.67, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.12.17-pre.67 at C:\flutter
    • Framework revision 3ea8c87ce9 (4 hours ago), 2019-12-04 13:27:23 +0100
    • Engine revision 1cdfc99314
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 2a13b1fe26)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\****\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\****\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

### LINKED ISSUE #76760: set ClampingScrollPhysics on CustomScrollView in NestedScrollView,it can only prevent the elasticity of the top, not the elasticity of the bottom of the widget
when i set ClampingScrollPhysics on CustomScrollView in NestedScrollView,it can only prevent the elasticity of the top, not the elasticity of the bottom of the widget

<details>
<summary>code sample</summary>

```dart
Widget build(BuildContext context) {
    final List<String> _tabs = ['Tab 1', 'Tab 2'];
    return Scaffold(
      appBar: LBAppBar(title: '测试嵌套滚动'),
      body: DefaultTabController(
        length: _tabs.length, // This is the number of tabs.
        child: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            // These are the slivers that show up in the "outer" scroll view.
            return <Widget>[
              SliverOverlapAbsorber(
                // This widget takes the overlapping behavior of the SliverAppBar,
                // and redirects it to the SliverOverlapInjector below. If it is
                // missing, then it is possible for the nested "inner" scroll view
                // below to end up under the SliverAppBar even when the inner
                // scroll view thinks it has not been scrolled.
                // This is not necessary if the "headerSliverBuilder" only builds
                // widgets that do not overlap the next sliver.
                handle:
                    NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                sliver: SliverAppBar(
                  title:
                      const Text('Books'), // This is the title in the app bar.
                  pinned: true,
                  expandedHeight: 150.0,
                  // The "forceElevated" property causes the SliverAppBar to show
                  // a shadow. The "innerBoxIsScrolled" parameter is true when the
                  // inner scroll view is scrolled beyond its "zero" point, i.e.
                  // when it appears to be scrolled below the SliverAppBar.
                  // Without this, there are cases where the shadow would appear
                  // or not appear inappropriately, because the SliverAppBar is
                  // not actually aware of the precise position of the inner
                  // scroll views.
                  forceElevated: innerBoxIsScrolled,
                  bottom: TabBar(
                    // These are the widgets to put in each tab in the tab bar.
                    tabs: _tabs.map((String name) => Tab(text: name)).toList(),
                  ),
                ),
              ),
            ];
          },
          body: TabBarView(
            // These are the contents of the tab views, below the tabs.
            children: _tabs.map((String name) {
              return SafeArea(
                top: false,
                bottom: false,
                child: Builder(
                  // This Builder is needed to provide a BuildContext that is
                  // "inside" the NestedScrollView, so that
                  // sliverOverlapAbsorberHandleFor() can find the
                  // NestedScrollView.
                  builder: (BuildContext context) {
                    return CustomScrollView(
                      physics: ClampingScrollPhysics(),
                      // The "controller" and "primary" members should be left
                      // unset, so that the NestedScrollView can control this
                      // inner scroll view.
                      // If the "controller" property is set, then this scroll
                      // view will not be associated with the NestedScrollView.
                      // The PageStorageKey should be unique to this ScrollView;
                      // it allows the list to remember its scroll position when
                      // the tab view is not on the screen.
                      key: PageStorageKey<String>(name),
                      slivers: <Widget>[
                        SliverOverlapInjector(
                          // This is the flip side of the SliverOverlapAbsorber
                          // above.
                          handle:
                              NestedScrollView.sliverOverlapAbsorberHandleFor(
                                  context),
                        ),

                        //列表
                        SliverList(
                          delegate:
                              SliverChildBuilderDelegate((content, index) {
                            return ListTile(
                              title: Text('测试数据$index'),
                            );
                          }, childCount: 15),
                        ),
                      ],
                    );
                  },
                ),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash

[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.6 at /Users/rwt/gitlab/stock_flutter/.flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/rwt/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.1.2
    • Dart plugin version 183.5901

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 84228D28-FD68-497F-9584-7DFBA071AFAC • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
```
</details>

### LINKED ISSUE #79077: NestedScrollView becomes unscrollable with certain headerSliverBuilder configurations
as titled

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  MyStatelessWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final List<String> _tabs = ['Tab 1', 'Tab 2'];
    final paddingTop = MediaQuery.of(context).padding.top;
    return DefaultTabController(
      length: _tabs.length, // This is the number of tabs.
      child: Scaffold(
        body: NestedScrollView(
          floatHeaderSlivers: true,
          headerSliverBuilder: (context, innerBoxIsScrolled) => [

            // SliverAppBar(
            //   pinned: false,
            //   toolbarHeight: 0.0,
            //   collapsedHeight: 0.0,
            //   expandedHeight: null,
            //   primary: false,
            // ),

            //********* or *********

            // SliverOverlapAbsorber(
            //   handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
            //   sliver: SliverAppBar(
            //     pinned: true,
            //     toolbarHeight: 62.0,                    // 63.0 works fine
            //     collapsedHeight: 62.0,                  // 63.0 works fine
            //     expandedHeight: null,
            //     primary: false,
            //   ),
            // ),

            //********* or *********

            // SliverOverlapAbsorber(
            //   handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
            //   sliver: SliverAppBar(
            //     pinned: true,
            //     toolbarHeight: 62.0 - paddingTop,    // 63.0 - paddingTop works fine
            //     collapsedHeight: 62.0 - paddingTop,  // 63.0 - paddingTop works fine
            //     expandedHeight: null,
            //     primary: true,
            //   ),
            // ),

            //********* or *********

            // SliverOverlapAbsorber(
            //   handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
            //   sliver: SliverAppBar(
            //     pinned: true,
            //     toolbarHeight: kToolbarHeight,
            //     collapsedHeight: null,
            //     expandedHeight: 56.0,                // 57.0 works fine
            //     primary: false,
            //   ),
            // ),
          ],
          body: TabBarView(
            // These are the contents of the tab views, below the tabs.
            children: _tabs.map((String name) {
              return SafeArea(
                top: false,
                bottom: false,
                child: Builder(
                  builder: (BuildContext context) {
                    return CustomScrollView(
                      key: PageStorageKey<String>(name),
                      slivers: <Widget>[
                        SliverOverlapInjector(
                          handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                        ),
                        SliverPadding(
                          padding: const EdgeInsets.all(8.0),
                          sliver: SliverFixedExtentList(
                            itemExtent: 48.0,
                            delegate: SliverChildBuilderDelegate(
                              (BuildContext context, int index) {
                                return ListTile(
                                  title: Text('Item $index'),
                                );
                              },
                              childCount: 30,
                            ),
                          ),
                        ),
                      ],
                    );
                  },
                ),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.223, on Microsoft Windows [Version 10.0.19041.867], locale ru-RU)
    • Flutter version 2.1.0-13.0.pre.223 at c:\dev\src\flutter
    • Framework revision 891511d58f (2 days ago), 2021-03-23 14:57:01 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (5 available)
    • Redmi Note 5 (mobile)   • 40c9f14       • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!
```
</details>

https://user-images.githubusercontent.com/39104740/112532826-58e88900-8dba-11eb-8e2a-65990421548e.mp4

### LINKED ISSUE #82391: ScrollableState.setCanDrag should not contradict with scroll physics
Currently, because `ScrollableState.setCanDrag` doesn't check whether it complies with `ScrollPhysics.shouldAcceptUserOffset`, it's possible that user of ScrollableState doesn't check whether it can be set to `true` or `false` and thus ignores scroll physics by mistake - which is what happens to NestedScrollView, which forgets to do exactly this https://github.com/flutter/flutter/issues/45619

https://github.com/flutter/flutter/blob/ff15d04f214ae7cc4ffbacde2faefa1772e112e4/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L1619-L1621

I propose that we force users of the ScrollableState to check the physics before they apply their own conditions with such assert (or something similar)

```dart
assert(
  _physics == null || newCanDrag == _physics!.shouldAcceptUserOffset(position),
  'When scrollable has physics, canDrag should be equal to shouldAcceptUserOffset result',
);
```

cc @Hixie

### LINKED ISSUE #110956: NestedScrollView does not scroll unless a minimum number of children are added to the CustomScrollView
## Steps to Reproduce

1. Create a project using the command below (from the official documentation)
`flutter create --sample=widgets.NestedScrollView.1 mysample`
2. Change the value of the childCount to 7
3. Remove the expandedHeight: 150.0 from the SliverAppBar
4. Set the extent to be 120
5. Build the App on Android or iOS 

**Expected results:** 
The List should be scrolled without any issues as there are a couple of items off the screen.

**Actual results:** 
The List is not scrolled.

<details>
Change the item count to 10 or more (depending on the device screen) => The list is scrolling.

<summary>Code sample</summary>
Use the sample code for NestedScrollView and adjust it as in the "Steps to reproduce"
</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

https://user-images.githubusercontent.com/5802728/188334536-2c8bbc23-5ac3-4703-bf36-01c88ad0543f.mov

https://user-images.githubusercontent.com/5802728/188334541-56b546f4-b12d-43e9-a9fa-d350ae33959c.mov

### LINKED ISSUE #117316: NestedScrollView + ListView not work touchpad scroll
NestedScrollView + ListView not work touchpad scroll

if the application has a height equal to 0.8 of the screen height, then the touchpad scroll does not work
if we reduce the window size to about 0.5 screen height the touchpad scroll works

desktop macOS
 master or stable
Flutter 3.7.0-10.0.pre.46 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 420c6d6cc8 (89 minutes ago) • 2022-12-19 08:44:36 -0500
Engine • revision 58ab5277a7
Tools • Dart 3.0.0 (build 3.0.0-35.0.dev) • DevTools 2.20.0

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: NestedScrollView(
        body: ListView(children: [
          ListView.builder(
              physics: const ScrollPhysics(),
              shrinkWrap: true,
              itemCount: 6,
              itemBuilder: (context, index) {
                return Padding(
                  padding: const EdgeInsets.all(8.0),
                  child:
                      Container(width: 100, height: 100, color: Colors.green),
                );
              }),
          ListView.builder(
              physics: const ScrollPhysics(),
              shrinkWrap: true,
              itemCount: 5,
              itemBuilder: (context, index) {
                return Padding(
                  padding: const EdgeInsets.all(8.0),
                  child:
                      Container(width: 100, height: 100, color: Colors.purple),
                );
              }),
        ]),
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return [];
        },
      ),
    );
  }
}
```

### LINKED ISSUE #127282: Scroll not working on a SliverList.list inside a CustomScrollView, but yes with a SliverList.builder
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have a ``NestedScrollView``with a ``SliverAppBar``, and a ``CustomScrollView`` as a child. Inside the ``CustomScrollView``, if I use a ``SliverList.builder`` everything works fine, but if I use a ``SliverList.list``the scroll doesn't work. This only happens with the normal ``SliverAppBar``. If you use a ``SliverAppBar.medium``or a ``SliverAppBar.large``, both SliverLists works fine.

### Expected results

Scrolling with ``SliverList.list``should scroll as it does ``SliverList.builder``.

### Actual results

``SliverList.builder`` scrolls but ``SliverList.list``doesn't.

### Code sample

In case you wonder why I want to use a ``SliverList.list`` instead of a ``SliverList.builder`` it's because I want to build a settings screen, with a list of different options. The list is built with widgets with different structures, it's not a list with the same widget but with different data, so that's why I want to use a normal SliverList.list instead a SliverList.builder.

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      theme: ThemeData(
        useMaterial3: true
      ),
      home: const MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return <Widget>[
            SliverOverlapAbsorber(
              handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
              sliver: SliverAppBar(
                title: const Text("Title"),
                pinned: true,
                floating: true,
                centerTitle: false,
                forceElevated: innerBoxIsScrolled,
              ),
            ),
          ];
        },
        body: SafeArea(
          top: false,
          bottom: false,
          child: Builder(
            builder: (context) => CustomScrollView(
              slivers: [
                SliverOverlapInjector(
                  handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                ),
                SliverList.list(
                  children: [
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                    ListTile(
                      title: const Text("List tile"),
                      subtitle: const Text("Navigate to second screen"),
                      onTap: () => Navigator.push(context, MaterialPageRoute(
                        builder: (context) => const SecondScreen()
                      )),
                    ),
                  ]
                ),
                // SliverList.builder(
                //   itemCount: 30,
                //   itemBuilder: (context, index) => ListTile(
                //     title: Text("List tile $index"),
                //     subtitle: const Text("Navigate to second screen"),
                //     onTap: () => Navigator.push(context, MaterialPageRoute(
                //       builder: (context) => const SecondScreen()
                //     )),
                //   ) 
                // )
              ],
            ),
          )
        )
      ),
    );
  }
}

class SecondScreen extends StatefulWidget {
  const SecondScreen({Key? key}) : super(key: key);

  @override
  State<SecondScreen> createState() => _SecondScreenState();
}

class _SecondScreenState extends State<SecondScreen> {
  int count = 30;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
        headerSliverBuilder: (context, innerBoxIsScrolled) => [
          SliverOverlapAbsorber(
            handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
            sliver: SliverAppBar.large(
              leading: IconButton(
                onPressed: () => Navigator.pop(context), 
                icon: const Icon(Icons.close)
              ),
              pinned: true,
              floating: true,
              centerTitle: false,
              forceElevated: innerBoxIsScrolled,
              title: const Text("Second screen"),
              actions: [
                IconButton(
                  onPressed: () => setState(() => count++), 
                  icon: const Icon(Icons.add)
                ),
                const SizedBox(width: 10)
              ],
            ),
          )
        ],
        body: SafeArea(
          top: false,
          bottom: false,
          child: Builder(
            builder: (context) => CustomScrollView(
              slivers: [
                SliverOverlapInjector(
                  handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                ),
                SliverList.builder(
                  itemCount: count,
                  itemBuilder: (context, index) => ListTile(
                    title: Text("Item $index"),
                  ),
                )
              ],
            ),
          ) 
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/47545344/a2e1d684-81e2-4508-a2fe-d7335c8ad433

</details>

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale es-ES)
    • Flutter version 3.10.1 on channel stable at /Users/juan/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (4 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/juan/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/juan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • sdk gphone64 arm64 (mobile) • emulator-5556 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

### PR DESCRIPTION
**Pull request by Piinks**
#### (plus some more docs)

Fixes https://github.com/flutter/flutter/issues/76760
Fixes https://github.com/flutter/flutter/issues/82391
Fixes https://github.com/flutter/flutter/issues/45619
Fixes #117316
Fixes #110956
Fixes #127282 
Fixes #32563
Fixes #46089 
Fixes #79077
Part of fixing #62833

This fixes (a bunch of) issues that have been reported differently over the years, but all have the same root cause. Sometimes the NestedScrollView would incorrectly calculate whether or not there is enough content to allow scrolling. This would only apply to drag scrolling (not mouse wheel scrolling for example). This did not relate to how the extent of the NestedScrollView is computed, but just the logic that enabled the actual drag gestures. This fixes that. :)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Piinks** [comment]
Still scanning issues to see if there are other test cases here, it looks like this has been reported a lot of different ways over the years. @nt4f04uNd and @xu-baolin might like to see this, no worries if you are unavailable to check it out, but if you can I'd be interested to see what you think. :)

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 1]
```diff
@@ -1438,9 +1441,36 @@ class _NestedScrollPosition extends ScrollPosition implements ScrollActivityDele
...
+    final double maxScrollExtent = this.maxScrollExtent + overlapExtent;
+    final bool extentAllows =
+      // There is already room to scroll in the outer scroll view.
+      minScrollExtent != maxScrollExtent
+      // The inner extent exceeds the bounds of the viewport, accounting for the
+      // outer extent.
+      || totalInnerExtent > (viewportDimension - maxScrollExtent)
+      // There is no outer extent. The inner extent was computed based on the
+      // full viewport dimension and is accurate for the whole NestedScrollView.
+      || (maxScrollExtent == 0 && totalInnerExtent > 0);
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:1471]: I think I need time to check if this change works for all the problem cases 😄 

Will feedback in the next few days.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 2]
```diff
@@ -855,7 +855,10 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
         position.maxScrollExtent - position.minScrollExtent,
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:855]: In fact, `maxInnerExtent` is not the total extension of the inner scrollable, but the maximum scrolling space inside, right?

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 3]
```diff
@@ -1438,9 +1441,36 @@ class _NestedScrollPosition extends ScrollPosition implements ScrollActivityDele
...
+    // and maxExtent of 56.0 will have a ScrollPosition.maxExtent of 0.0 after
+    // the SliverOverlap is applied. This is correct because the pinned sliver
+    // app bar should not have to consume scrolling before the inner body of the
+    // NestedScrollView scrolls. However, when calculating the drag here, 0
+    // could result in scrolling being disabled unexpectedly if the inner scroll
+    // view by itself were not long enough to allow scrolling on its own.
+    final double maxScrollExtent = this.maxScrollExtent + overlapExtent;
+    final bool extentAllows =
+      // There is already room to scroll in the outer scroll view.
+      minScrollExtent != maxScrollExtent
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:1465]: This should be `this.minScrollExtent != this.maxScrollExtent`.
Thinking of this case, the `overlapExtent > 0`(just pinned the sliver bar) and the inner scrollable has a little extent that can not scrolling, we should not set this can drag, right?

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 4]
```diff
@@ -1438,9 +1441,36 @@ class _NestedScrollPosition extends ScrollPosition implements ScrollActivityDele
...
+      // The inner extent exceeds the bounds of the viewport, accounting for the
+      // outer extent.
+      || totalInnerExtent > (viewportDimension - maxScrollExtent)
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:1468]: If [this]( https://github.com/flutter/flutter/pull/127718/files#r1209928710) is right, we just should change `extentAllows ` to 
```dart
final bool extentAllows = this.minScrollExtent != this.maxScrollExtent || totalInnerExtent > 0
```

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 5]
```diff
@@ -1438,9 +1441,36 @@ class _NestedScrollPosition extends ScrollPosition implements ScrollActivityDele
...
+    // expected since the inner and outer scroll views' extents are manipulated
+    // in this way for them to behave as one, but the extent must be accounted
+    // for when considering the full extent available to drag.
+    // For example, a pinned SliverAppBar in the outer position with a minExtent
+    // and maxExtent of 56.0 will have a ScrollPosition.maxExtent of 0.0 after
+    // the SliverOverlap is applied. This is correct because the pinned sliver
+    // app bar should not have to consume scrolling before the inner body of the
+    // NestedScrollView scrolls. However, when calculating the drag here, 0
+    // could result in scrolling being disabled unexpectedly if the inner scroll
+    // view by itself were not long enough to allow scrolling on its own.
```
Comment (nt4f04uNd) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:1461]: Great comment!
I have to admit that this was pretty tricky for me to wrap my head around this ;-)

I am not very familiar with the internals of NestedScrollView, so I'll leave this to @xu-baolin to review

Comment (Piinks) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1461]: I was actually able to make it even simpler. :)

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 4 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1468]: So I realized this is not accounting for the physics at all! Which reminded me of https://github.com/flutter/flutter/issues/82391... so I changed it to what i think it should really be. Even if the extent is not enough to scroll, I don't want to completely ignore AlwaysScrollableScrollPhysics, which should always scroll even if it is not long enough.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 6]
```diff
@@ -1438,9 +1469,16 @@ class _NestedScrollPosition extends ScrollPosition implements ScrollActivityDele
     coordinator.updateCanDrag();
   }
 
-  void updateCanDrag(double totalExtent) {
-    context.setCanDrag(physics.allowUserScrolling &&
-        (totalExtent > (viewportDimension - maxScrollExtent) || minScrollExtent != maxScrollExtent));
+  void updateCanDrag(bool innerCanDrag,) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:1472]: nit: that trailing comma feels a little lonly.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 7]
```diff
@@ -1438,9 +1469,16 @@ class _NestedScrollPosition extends ScrollPosition implements ScrollActivityDele
...
+    // This is only called for the outer position
+    assert(coordinator._outerPosition == this);
+    context.setCanDrag(
+      // This refers to the physics of the actual outer scroll position, not
+      // the whole NestedScrollView, since it is possible to have different
+      // ScrollPhysics for the inner and outer positions.
+      physics.shouldAcceptUserOffset(this)
+      || innerCanDrag,
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:1480]: nit: just leave this on one line (or indent line 1480 a little further)?

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 8]
```diff
@@ -2948,17 +2952,281 @@ void main() {
...
+                ];
+              }
+              return header != null ? <Widget>[ header ] : <Widget>[];
+            },
+            body: Builder(
+              builder: (BuildContext context) {
+                return CustomScrollView(
+                  slivers: <Widget>[
+                    SliverList.builder(
+                      itemCount: bodyLength == _BodyLength.short ? 10 : 100,
```
Comment (goderbauer) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:2996]: since enums are best used with switch/case, can you use one of those fancy switch expressions here?

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 6 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1472]: Oh whoops. Thanks!

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 7 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1480]: Definitely. I separated them purely for the context of the comment.

File: packages/flutter/test/widgets/nested_scroll_view_test.dart (hunk 8 above)
Comment (Piinks) [reply packages/flutter/test/widgets/nested_scroll_view_test.dart:2996]: Oh yeah! Absolutely!
