### PR TITLE
Ignore spam from SurfaceSyncer

### LINKED ISSUE #123255: Flutter should not print the `E/SurfaceSyncer` messages about `Failed to find sync for id=`
There is a little more context on this in b/268445629, cl/494699962 (sorry, Google only).

From a member of the Android team at Google:

> Thanks for the bug report. This issue is fixed in Android U. Besides the spammy logs, this shouldn't be causing any issues.

A Google-internal Android framework also ignores this message. The message can become very spammy and concerning to users (see e.g. https://stackoverflow.com/questions/73432326/failed-to-find-sync-for-id-0-in-flutter), especially if it is covering up otehr problems.

/cc @reidbaker fyi, @christopherfujino - I'm pretty sure we have things in the android logging logic to ignore other messages already.

### PR DESCRIPTION
**Pull request by dnfield**
Fixes #123255

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/android/android_device.dart [hunk 1]
```diff
@@ -1096,6 +1096,11 @@ class AdbLogReader extends DeviceLogReader {
     RegExp(r'^[F]\/[\S^:]+:\s+'),
   ];
 
+  // E/SurfaceSyncer(22636): Failed to find sync for id=9
+  // Some versions of Android spew this out. It is inactionable to the end user
+  // and causes no problems for the application.
```
Comment (reidbaker) [inline packages/flutter_tools/lib/src/android/android_device.dart:1101]: If you have a link to the documentation you used to figure this out including it here could help future maintainers.

Comment (dnfield) [reply packages/flutter_tools/lib/src/android/android_device.dart:1101]: I linked it in the bug linked in this PR - unfortunately it's not visible to non-googlers, but perhaps I should have included it here too...
