### PR TITLE
[Android] Fix integration test to check if dev dependencies are removed from release builds + address no non-dev dependency plugin edge case

### LINKED ISSUE #161780: 🛑 `flutter config --explicit-package-dependencies-`: Gradle release build fails with only dev-dependencies
In https://github.com/flutter/flutter/pull/160289, I attempt to enable `flutter config --explicit-package-dependencies`.

It's getting there... the next blocker after updating the lock files is this:
```sh
$ cd dev/integration_tests/spell_check
$ flutter config --explicit-package-dependencies
$ flutter build apk

e: file:///Users/matanl/Developer/flutter/dev/integration_tests/spell_check/android/app/src/main/kotlin/com/example/sc_int_test/MainActivity.kt:3:8 Unresolved reference: io
e: file:///Users/matanl/Developer/flutter/dev/integration_tests/spell_check/android/app/src/main/kotlin/com/example/sc_int_test/MainActivity.kt:5:22 Unresolved reference: FlutterActivity

FAILURE: Build failed with an exception.
```

From what I can tell, it's due to this stanza in `flutter.groovy`:

https://github.com/flutter/flutter/blob/90f926edc1357eb1216a09fe7b3716d5e95fe9f9/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L600-L603

With our new logic flow (TM), it's possible for plugins to evaluate to `size() > 0` _and_ no plugins to receive the Flutter embedding dependencies. From talking to @gmackall this may or may not be intentional, we can figure that out debugging and submitting PRs fixing these tests.

What I'd like to see is:

1. `android_release_builds_exclude_dev_dependencies_test` showcases the failure being talked about (and is fixed)
2. The above workflow (`cd dev/integration_tests/spell_check && flutter build apk`) works when the flag is enabled

https://github.com/flutter/flutter/blob/90f926edc1357eb1216a09fe7b3716d5e95fe9f9/dev/devicelab/bin/tasks/android_release_builds_exclude_dev_dependencies_test.dart#L32-L36

### PR DESCRIPTION
**Pull request by camsim99**
Makes the following change to fix the case where dev dependencies are stripped in apps that only contain dev dependencies:
- Changes the Flutter Gradle plugin to add the Flutter embedding as a direct dependency of a Flutter app if it contains no plugins that would include it transitively (this excludes dev dependencies in release builds)

Makes the following changes to correct + improve the integration test that checks if dev dependencies are stripped from release builds:

- Fixes the plugin that was supposed to be as dev dependency to actually be a dev dependency
- Changes the test structure to check the output of `./gradlew app:dependencies` (see [more details on this call](https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html)) instead of the classes included in the APK. Checking the APK was leading us astray because it appears obfuscation occurs for release builds.
- Adds more sections, comments, etc.

Fixes https://github.com/flutter/flutter/issues/161780.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: dev/devicelab/bin/tasks/android_release_builds_exclude_dev_dependencies_test.dart [hunk 1]
```diff
@@ -8,72 +8,100 @@ import 'dart:io';
...
-          section('APK does contain methods from dev dependency in $buildMode mode');
+          final String gradlew = Platform.isWindows ? 'gradlew.bat' : 'gradlew';
+          final String gradlewExecutable = Platform.isWindows ? '.\\$gradlew' : './$gradlew';
+          final RegExp regExpToMatchDevDependencyPlugin = RegExp(
+            r'--- project :dev_dependency_plugin',
+          );
+          final RegExp regExpToMatchDevDependencyPluginWithTransitiveDependencies = RegExp(
+            r'--- project :dev_dependency_plugin\n(\s)*\+--- org.jetbrains.kotlin.*\s\(\*\)\n(\s)*\\---\sio.flutter:flutter_embedding_' +
+                buildMode,
+          );
```
Comment (camsim99) [inline dev/devicelab/bin/tasks/android_release_builds_exclude_dev_dependencies_test.dart:60]: If there's any feedback on the regex I used please let me know! My intention was to make the check for release builds much looser in case the dev dependency is included in some way we don't expect. The other builds should always include the dev dependency plugin that depends on the Flutter embedding and because the default language is Kotlin (I think?), the Kotlin plugin as well.

I can include sample outputs here if helpful for review.

Comment (matanlurey) [reply dev/devicelab/bin/tasks/android_release_builds_exclude_dev_dependencies_test.dart:60]: Seems reasonable for now.

**Comment by camsim99** [comment]
Sorry didn't mean to leave this as a draft :)

**Review by matanlurey — APPROVED** [review]
LGTM! I did not have a chance to try this locally but I trust you did :)

**Comment by camsim99** [comment]
I did test it locally :) but in an effort to catch any outstanding issued I merged this with https://github.com/flutter/flutter/pull/160289 to see what happened. There are [failures](https://github.com/flutter/flutter/pull/162262/checks?check_run_id=36254835237). They seem unrelated, but just going to double check before I cause a regression for modules.

**Comment by matanlurey** [comment]
> I did test it locally :) but in an effort to catch any outstanding issued I merged this with #160289 to see what happened. There are [failures](https://github.com/flutter/flutter/pull/162262/checks?check_run_id=36254835237). They seem unrelated, but just going to double check before I cause a regression for modules.

These look like "good" failures (https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8724551273408643713/+/u/run_test.dart_for_tool_tests_shard_and_subshard_commands/stdout), that is, they would be fixed by https://github.com/flutter/flutter/pull/160289.

**Comment by camsim99** [comment]
Hmm but I merged this PR with that one to get those failures? Can you elaborate on why you think it might have fixed that failure?

**Comment by camsim99** [comment]
Updated https://github.com/flutter/flutter/pull/162262 to check out the state of things before landing
