### PR TITLE
Fix to Linux_pixel_7pro integration_ui_keyboard_resize test flakiness

### LINKED ISSUE #161300: Linux_pixel_7pro integration_ui_keyboard_resize is 2.17% flaky
The post-submit test builder `Linux_pixel_7pro integration_ui_keyboard_resize` had a flaky ratio 2.17% for the past (up to) 100 commits, which is above our 2.00% threshold.

One recent flaky example for a same commit: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20integration_ui_keyboard_resize/4489
Commit: https://github.com/flutter/flutter/commit/62c6859e593ba7c7b075ee850c3690eb44401afa

Flaky builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20integration_ui_keyboard_resize/4489
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20integration_ui_keyboard_resize/4470

Recent test runs:
https://flutter-dashboard.appspot.com/#/build?taskFilter=Linux_pixel_7pro%20integration_ui_keyboard_resize

Please follow https://github.com/flutter/flutter/blob/master/docs/infra/Reducing-Test-Flakiness.md#fixing-flaky-tests to fix the flakiness and enable the test back after validating the fix (internal dashboard to validate: go/flutter_test_flakiness).

### PR DESCRIPTION
**Pull request by harri35**
## `integration_ui_keyboard_resize` flakiness reduction

This PR addresses flakiness in the `integration_ui_keyboard_resize` test (issue #161300) and slightly improves its performance.

**Issue summary:**

The `integration_ui_keyboard_resize` test occasionally fails because the device keyboard does not reliably open at the start of the test.  This PR mitigates one cause of this flakiness, though other potential underlying issues may still exist.  See #161300 for a detailed investigation.

**Changes and rationale:**

1.  **Improved keyboard detection logic (flakiness reduction):**
    *   The core change moves `await driver.tap(defaultTextField);` *inside* the loop that checks for layout changes. This ensures the test repeatedly attempts to open the keyboard *while* waiting for the expected layout shift, significantly improving reliability.
    *   **Local testing results (MacBook Pro M1 + Pixel 8 Pro):**
        *   **Original implementation:** Consistent failures within the first 15 iterations.
        *   **This PR:**  Ran consistently for at least 300 iterations (out of 2000) before any failure, with some runs exceeding 900 iterations.

2.  **`enableTextEntryEmulation` configuration improvement:**
    *   The `keyboard_resize.dart` app is *exclusively* used for testing and requires `enableTextEntryEmulation: false` for proper device keyboard interaction.
    *   This PR sets `enableTextEntryEmulation: false` directly within the app's `enableFlutterDriverExtension` setup.  This simplifies the test setup, avoids cross-thread communication, and prevents the app from appearing broken when run independently (as manual text input wouldn't work otherwise).

3.  **UI enhancements for manual testing:**
    *   Added `SafeArea` and `InputDecoration` to `keyboard_resize.dart`. This ensures the `TextField` is fully visible and usable during manual testing (it was previously obscured by the Android status bar).  This improves the developer experience when debugging the app directly.

4.  **Optimized polling for speed:**
    *   Reduced the polling interval and increased the number of polling iterations (maintaining the overall timeout).  This change resulted in a ~2-second speed improvement per test iteration during local testing.

**Further flakiness improvement discussion and ideas**
See the discussion at https://github.com/flutter/flutter/issues/161300

**Testing and reproduction:**

To reproduce the original flakiness and verify the fix (reproducibility may vary based on setup; see https://github.com/flutter/flutter/issues/161300#issuecomment-2618952501):

1.  **Disable automatic reboots:** Comment out the `await checkForRebootRequired();` line in https://github.com/flutter/flutter/blob/9e273d5e6e2e75336f26951a09aba0f5656a7e77/dev/devicelab/lib/framework/framework.dart#L240-L243
2.  **Disable automatic retries:** Set `static const int retryNumber = 0;` in https://github.com/flutter/flutter/blob/9e273d5e6e2e75336f26951a09aba0f5656a7e77/dev/devicelab/lib/framework/cocoon.dart#L56-L57
3.  **Install `hyperfine`:**  This is a command-line benchmarking tool (e.g., `brew install hyperfine` on macOS).
4.  **Connect a device/emulator:** Connect a physical Android device or start an emulator.
5.  **Run repeated tests:** Use `hyperfine` to run the test multiple times and capture the output:
    ```bash
    hyperfine -r 100 'dart bin/test_runner.dart test -t integration_ui_keyboard_resize > log.txt'
    ```

### CODE REVIEW

**Comment by harri35** [comment]
Converting back to a draft as this change does not fully fix the problem - https://github.com/flutter/flutter/issues/161300#issuecomment-2620976969

**Comment by harri35** [comment]
Updated the PR to use an even simpler solution - moved to tap action inside the loop that is waiting for the keyboard to open. So if the InputManager ignores the first tap we also retry that.

**Comment by harri35** [comment]
@bkonyi Would be awesome if you would have time to take a look / try this. While it fully doesn't fix the whole issue, based on the local evidence, it is a partial fix and would reduce the flakiness.

File: dev/integration_tests/ui/test_driver/keyboard_resize_test.dart [hunk 1]
```diff
@@ -49,8 +48,8 @@ void main() {
       await driver.tap(unfocusButton);
 
       bool heightTextDidExpand = false;
-      for (int i = 0; i < 3; ++i) {
-        await Future<void>.delayed(const Duration(seconds: 1));
+      for (int i = 0; i < 10; ++i) {
+        await Future<void>.delayed(const Duration(milliseconds: 300));
```
Comment (matanlurey) [inline dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:52]: Please pull out a definition, such as:

```dart
/// Longer explanation of why this timing was picked.
const Duration _longPoll300Ms = Duration(...);
```

and use it here and above.

File: dev/integration_tests/ui/test_driver/keyboard_resize_test.dart [hunk 2]
```diff
@@ -29,11 +28,11 @@ void main() {
       // Focus the text field to show the keyboard.
       final SerializableFinder defaultTextField = find.byValueKey(keys.kDefaultTextField);
       await driver.waitFor(defaultTextField);
-      await driver.tap(defaultTextField);
 
       bool heightTextDidShrink = false;
-      for (int i = 0; i < 6; ++i) {
-        await Future<void>.delayed(const Duration(seconds: 1));
+      for (int i = 0; i < 20; ++i) {
+        await driver.tap(defaultTextField);
```
Comment (matanlurey) [inline dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:34]: Needing up to 20 taps for this to work... that seems like a bug we're hiding in this test.

Can you clarify why we need to tap this multiple times?

Is it possible we need something like [`waitForTappable`](https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/waitForTappable.html) instead?

/cc @jonahwilliams

**Review by matanlurey — CHANGES_REQUESTED** [review]

**Review by matanlurey — CHANGES_REQUESTED** [review]
Thanks for jumping on this. The concept of the change I'm satisfied with, but I'm not convinced the implementation is correct or good - it appears to either be hiding bugs, or I misunderstand what is going on.

File: dev/integration_tests/ui/test_driver/keyboard_resize_test.dart (hunk 2 above)
Comment (harri35) [reply dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:34]: Thanks for the feedback!

> Is it possible we need something like waitForTappable instead?

- The `waitForTappable  `is a good idea indeed. I did some local tests with this, but it didn't make any difference. See https://github.com/flutter/flutter/issues/161300#issuecomment-2636055448
- I also tried some additional things - see https://github.com/flutter/flutter/issues/161300#issuecomment-2642378226

> Needing up to 20 taps for this to work... that seems like a bug we're hiding in this test.
> Can you clarify why we need to tap this multiple times?

Can't explain it. I agree, this looks like a bug. 

My first guess would be that it is a bug in FlutterDriver and/or how it interacts with Android's InputManager in the case of `enableTextEntryEmulation: false`. 
Or possibly some issue in how FlutterView and InputManager interact, but in that case I would expect to see bug reports from production also. As opening an app and clicking on a TextField and expecting a keyboard to open is a very common use case. 

As I propose in https://github.com/flutter/flutter/issues/161300#issuecomment-2642378226, I think it would make sense to make a separate bug report for this specific bug description. Otherwise, it is somewhat obfuscated in https://github.com/flutter/flutter/issues/161300 

The goal of making this PR is a temporary workaround to reduce the flakiness until the bug can be found and addressed. It seems it has been an issue for some time: https://github.com/flutter/flutter/pull/141301. 
But if you feel this is premature and the workaround creates more confusion than it helps, then I propose we close this PR and try out some more strategies.

Speaking of that - as I can reproduce this locally quite easily, then if anyone has any suggestions I should try - let me know.

One observation: this also behaves slightly differently depending on the Android version and/or speed of the device. For me, the faster the device / newer the Android version, the more the setup of the test fails (for me locally).

Comment (matanlurey) [reply dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:41]: > My first guess would be that it is a bug in FlutterDriver and/or how it interacts with Android's InputManager in the case of `enableTextEntryEmulation: false`.

In driver mode, you mean. Yeah that is possible, I have not dug into the code here (yet).

> Or possibly some issue in how FlutterView and InputManager interact, but in that case I would expect to see bug reports from production also. As opening an app and clicking on a TextField and expecting a keyboard to open is a very common use case.

Also possible. I am going to add @justinmc to this PR, and see if he has insight (works on text input).

> The goal of making this PR is a temporary workaround to reduce the flakiness until the bug can be found and addressed.

It's just not clear to me this _does_ resolve any flakiness, at least locally I can still fairly easily run into:

```txt
00:07 +0 -1: end-to-end test Ensure keyboard dismissal resizes the view to original size [E]

  Expected: true
    Actual: <false>
```

It is possible the polling changes you made make it a bit less likely to occur, but tapping multiple times doesn't change focus, and only changing focus is supposed to open the keyboard. I ran out of time today to look in more detail, but you could please try adding some logging (even locally) and tell how often a for-loop retry causes the test to pass where it would otherwise fail?

Something like:

```dart
int retries = 0;

// ...

if (double.parse(heightWithKeyboardShown) < double.parse(startHeight)) {
  if (retries > 0) {
    print('>>> $retries retries were used to make this PASS.');
  }
  heightTextDidShrink = true;
  break;
} else {
  retries++;
}
```

... and let me know if you see this hit significantly? I'll try to come back to this tomorrow.

**Comment by matanlurey** [comment]
@justinmc @harri35 is one of our contractors and is working on deflaking some tests, which is awesome.

They are trying to deflake/fix [`dev/integration_tests/ui/lib/keyboard_resize.dart`](https://github.com/flutter/flutter/blob/master/dev/integration_tests/ui/lib/keyboard_resize.dart) (and the test), which appears to _not_ be opening the Android keyboard some % of the time. It appears to _always_ work when I run this app manually:

```sh
cd dev/integration_tests/ui
flutter run lib/keyboard_resize.dart
```

... but fails a reasonable % of the time when run as a test:

```sh
flutter drive lib/keyboard_resize.dart
```

Do you happen to know any oddities, with or without driver, and the keyboard not opening on focus?

I can sync with you later today or tomorrow AM, but could use your _input_ (pun not intended).

File: dev/integration_tests/ui/test_driver/keyboard_resize_test.dart (hunk 2 above)
Comment (harri35) [reply dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:41]: Good idea! 

I added the logging in a [separate branch my fork](https://github.com/harri35/flutter/blob/6a06f330c9da1fe41df03f65ea63bc5c0e630b7d/dev/integration_tests/ui/test_driver/keyboard_resize_test.dart#L48)

I ran 100 iterations, using 2 different Android devices and OS'es to execute the test from. I disabled automatic retries, so the stats is about actually running 100 test iterations (with no failures).

```
hyperfine -r 10 --style=full 'dart bin/test_runner.dart test -t integration_ui_keyboard_resize >> log.txt'
```

Results as follows.

**MacBook Pro M1 + Pixel 8 Pro API 36**
- **15x** "No retries were used to make this PASS."
- **85x** "1 retries were used to make this PASS."
- **0x** "2 retries were used to make this PASS."

**ThinkPad X1 Extreme Gen 4i Windows 11 Pro  + Pixel 8 Pro API 36**
- **94x** "No retries were used to make this PASS."
- **6x** "1 retries were used to make this PASS."
- **0x** "2 retries were used to make this PASS."

**MacBook Pro M1 + Samsung Galaxy Tab S3 API 28**
- **0x** "No retries were used to make this PASS."
- **88x** "1 retries were used to make this PASS."
- **12x** "2 retries were used to make this PASS."


**ThinkPad X1 Extreme Gen 4i Windows 11 Pro  + Samsung Galaxy Tab S3 API 28**
- **0x** "No retries were used to make this PASS."
- **99x** "1 retries were used to make this PASS."
- **1x** "2 were used to make this PASS."


Note that tests were about 15 seconds slower per test on average when executed from the ThinkPad vs the Macbook.

> It is possible the polling changes you made make it a bit less likely to occur, but tapping multiple times doesn't change focus, and only changing focus is supposed to open the keyboard.

Good point! 

Based on this video https://drive.google.com/file/d/1dQmIPs7mCVjxocCvWB9KSfsaSiB7_Tyh/view?usp=sharing of a failure I was able to capture it looks to me the TextFlied gets the focus, just InputManager refuses to open the keyboard (fails on 4th attempt at the end).  As this log line warns:

```
W/InputMethodManager(19804): Ignoring showSoftInput() as view=io.flutter.embedding.android.FlutterView{16610da VFE...... .F....ID 0,0-1008,2244 #1} is not served.
```

This log comes from https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/view/inputmethod/InputMethodManager.java;drc=8fae81cc40d98877629b28a16fcc72b736423bdb;l=2385

Also tried to add a second TextField to the test app (with a separate FocusNode etc) and tap on the second TextField if opening the keyboard doesn't work with the first one - same results. 
It fails with both. At both times, complains about the same instance of a FlutterView.

Comment (harri35) [reply dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:41]: During today's call with John and Ergo we generated some more ideas to try out here to collect more info:
- Try an infinite loop to wait for the keyboard - does it pass then? Or never passes sometimes?
- Add an initial delay at the test - does it affect it? Will it pass better then?
- Any additional verbose info/logs we can activate (from FlutterDriver, etc) to better understand the process/communication between the threads there?

Comment (harri35) [reply dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:41]: Note: I'll edit this post when the test finishes all 2000 iterations. 

I created a version of this test with an infinite loop trying to open the keyboard, it can be found from my fork from the branch [fix/keyboard-resize-test-tap-with-logging-infinite](https://github.com/harri35/flutter/blob/fe80784cddb7dfdad1538cff26161abd34ec5e01/dev/integration_tests/ui/test_driver/keyboard_resize_test.dart#L41).

Results (MacBook Pro M1 + Pixel 8 Pro API 36 at 1506/2000 iterations)
```
  408x "No retries were used to make this PASS."
 1095x "1 retries were used to make this PASS."
    1x "31 retries were used to make this PASS."
    1x "53 retries were used to make this PASS."
    1x "54 retries were used to make this PASS."
```

The 31x, 53x and 54x are 9.3 sec, 15,9 sec and 16.2 sec loops of tapping and waiting (300ms) and checking for layout size. 
Surprising to me. I was of an assumption it would get just stuck forever. 
Maybe it still will in the last ~500 iterations, but something for sure seems to get stuck there (very infrequently) for a long time.

Comment (harri35) [reply dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:41]: 2nd test - tab outside of the loop, 3 sec delay at the start of the test, eg we always wait a little before running anything from the test ([fix/keyboard-resize-test-tap-with-start-wait](https://github.com/harri35/flutter/blob/2e37c02fc652379a36343b9b6b74b2bcbbb187bd/dev/integration_tests/ui/test_driver/keyboard_resize_test.dart#L22))

Results (MacBook Pro M1 + Pixel 8 Pro API 36) - FAILED at 179/2000
```
178x "No retries were used to make this PASS."
```

So, it doesn't seem that the speed of starting the test affects the success in the end. 
But all the successful passes needed 0 retries, so waiting at start it somewhat affects the default flow. Compared to the previous test where most common was "1 retries were used to make this PASS."
Eg something needs some time to start up.

Comment (harri35) [reply dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:41]: @matanlurey @justinmc 
Comparing the logs from the infinite loop test. 
I see the following pattern here - the keyboard can only be opened after the `D/InsetsController(...): hide(ime(), fromIme=false)` appears in the log. 

...
<-Test starts->
`.. end-to-end test Ensure keyboard dismissal resizes the view to original size ..`
<- All attempts to open the keyboard fail in this period ->
`D/InsetsController(...): hide(ime(), fromIme=false)`
<- All attempts to open the keyboard succeed now ->
`I/ImeTracker(...): com.yourcompany.integration_ui:...: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN`
`I/ImeTracker(...): com.yourcompany.integration_ui:...: onRequestShow at ORIGIN_CLIENT reason SHOW_SOFT_INPUT fromUser false`
`D/InsetsController(12023): show(ime(), fromIme=false)`
<- Keyboard opens somewhere here .. ->
`D/InsetsController(12023): Setting requestedVisibleTypes to -1 (was -9)`
`D/InputConnectionAdaptor(12023): The input method toggled cursor monitoring on`
...

Looking a the timing, 
- In the tests with no retries or 1 retry the `D/InsetsController(...): hide(ime(), fromIme=false)` takes ~ 1 second to appear from start of the test
- In the test with 54 retries it takes 21 seconds to appear

Comment (harri35) [reply dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:44]: I re-ran the 2000/2000 test with the same hardware and infinite loop setup. The results are surprisingly similar. 

One new learning - if Google Assistant / Gemini accidentally triggers on the device while testing, then the test is unable to proceed until the user manually dismisses the assistant sheet (this is the 3279 retries). 
The 54x iteration is curious and strange because it matches the first test 1:1.

Results (MacBook Pro M1 + Pixel 8 Pro API 36) - SUCCEEDED at 2000/2000

```
 992x 1 retries were used to make this PASS.
   1x 3279 retries were used to make this PASS.
   1x 54 retries were used to make this PASS.
 174x No retries were used to make this PASS.
```

Sadly, I do not have the Pixel 7 Pro device. But I'll try with an older Pixel (Pixel 3) and with the Pixel 7 Pro emulator. As the 2000 iteration tests take about 10h to run it will take some time.

I have not yet had the time to look into more when the `D/InsetsController(...): hide(ime(), fromIme=false)` exactly triggers in the Android Activity lifecycle and why it affects our test in this way. Any hints here are welcome.

**Review by matanlurey — APPROVED** [review]
LGTM to help deflake with the added TODOs/issues filed for follow-up.

**Comment by harri35** [comment]
@matanlurey I filed an issue for further investigation: https://github.com/flutter/flutter/issues/163606
I probably should have also set the `team-tool` label, but I do not have access to do it :)

File: dev/integration_tests/ui/test_driver/keyboard_resize_test.dart (hunk 2 above)
Comment (harri35) [reply dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:44]: Unable to reproduce longer retry loops on Pixel 3 API 31:

```
1893x 1 retries were used to make this PASS.
 107x No retries were used to make this PASS.
```

Comment (harri35) [reply dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:44]: Tried 2000 iterations with 0 fails on Pixel 7 Pro emulator API 35 - nothing interesting.

```
1610x 1 retries were used to make this PASS.
   1x 2 retries were used to make this PASS.
 389x No retries were used to make this PASS
```

File: dev/integration_tests/ui/test_driver/keyboard_resize_test.dart [hunk 3]
```diff
@@ -29,11 +28,21 @@ void main() {
...
+      // is to use polling and wait for the layout to change.
+      // We pick a short polling interval to speed up the test for most devices.
+      // In local tests, Pixel 8 Pro API 36 usually only one poll iteration is needed,
+      // older device like Galaxy Tab S3 API 28 takes 2-3 iterations.
+      const Duration pollDelay300Ms = Duration(milliseconds: 300);
 
       bool heightTextDidShrink = false;
-      for (int i = 0; i < 6; ++i) {
-        await Future<void>.delayed(const Duration(seconds: 1));
+      // TODO(harri35): Reconsider this polling duration when the root cause is found.
```
Comment (justinmc) [inline dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:40]: Nit: Include a link to https://github.com/flutter/flutter/issues/163606?

**Review by justinmc — APPROVED** [review]
The interim improvement here LGTM :+1: . Sorry I missed this notification.

The way the framework shows the keyboard is via the TextInputConnection and calling the method channel method `TextInput.show`.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/editable_text.dart#L3942

https://github.com/flutter/flutter/blob/a8d1b6238219f585c462b11276574c323b8014f4/packages/flutter/lib/src/services/text_input.dart#L2480

It might be interesting to check if that method channel call is being sent when the field is tapped. But that's for another PR. I'll leave a comment on the new issue.

And by the way, I added `team-tool` to https://github.com/flutter/flutter/issues/163606.

**Comment by harri35** [comment]
@bkonyi Can you please confirm whether we should proceed with merging the workaround?

File: dev/integration_tests/ui/test_driver/keyboard_resize_test.dart (hunk 2 above)
Comment (reidbaker) [reply dev/integration_tests/ui/test_driver/keyboard_resize_test.dart:45]: Thank you for all the work here.
