### PR TITLE
Fix scheduler event loop being stuck due to task with Priority.idle

### LINKED ISSUE #73766: [SchedulerBinding] SchedulerBinding.instance.scheduleTask is jammed when Priority is idle
I found `SchedulerBinding.instance.scheduleTask` can be stucked in a specific scene.

Here is my example code
```
const tag = "ScheduleTest";

class ScheduleTestPage1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(
            child: Container(
              width: 50,
              height: 50,
              child: CircularProgressIndicator(),
            ),
          ),
          FlatButton(
              onPressed: () {
                Navigator.of(context).push(MaterialPageRoute(builder: (context) {
                  return ScheduleTestPage2();
                })).then((value) {
                  SchedulerBinding.instance.scheduleTask(() {
                    print("$tag>>>>>>scheduleTask1");
                  }, Priority.touch);

                  Future.delayed(Duration(seconds: 1), () {
                    SchedulerBinding.instance.scheduleTask(() {
                      print("$tag>>>>>>scheduleTask2");
                    }, Priority.touch);
                  });
                });
              },
              child: Text("click me "))
        ],
      ),
    );
  }
}

class ScheduleTestPage2 extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _ScheduleTest2State();
  }
}

class _ScheduleTest2State extends State<ScheduleTestPage2> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          width: 100,
          height: 50,
          child: FlatButton(
            onPressed: () {
              Navigator.of(context).pop();
            },
            child: Text("Back"),
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    SchedulerBinding.instance.scheduleTask(() {
      print("$tag>>>>>> call ScheduleTestPage2 dispose");
      // do something such as Exception .    throw Exception("Exception Test");
    }, Priority.idle);
  }
}

```

The console just print 1 log.
image

After debug the `SchedulerBinding`, I found the task was not been executed because of these code.
https://github.com/flutter/flutter/blob/80f15dcfb93867f640e39d099abdc6cb5b1f9bad/packages/flutter/lib/src/scheduler/binding.dart#L1173-L1177

The `transientCallbackCount ` will be increased by `Ticker` in `SingleTickerProviderStateMixin.didChangeDependencies`
https://github.com/flutter/flutter/blob/80f15dcfb93867f640e39d099abdc6cb5b1f9bad/packages/flutter/lib/src/scheduler/ticker.dart#L90-L99

I draw a timeline might explain the issue.
image

Because of `_taskQueue.isEmpty` is not true, so the remain task will not have chance to be executed  :(

### PR DESCRIPTION
**Pull request by lauweijie**
`handleEventLoopCallback()` should return `true` rather than `false` when there are tasks in the queue but the highest priority task is not run because of the `schedulingStrategy`. If `false` is returned when the queue still has tasks, the event loop stops, causing existing and new tasks to never be scheduled.

For full context, see https://github.com/flutter/flutter/issues/73766#issuecomment-2202427256.

Fixes #73766 and #82016.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/scheduler/binding.dart [hunk 1]
```diff
@@ -553,7 +553,7 @@ mixin SchedulerBinding on BindingBase {
       }
       return _taskQueue.isNotEmpty;
     }
-    return false;
+    return true;
```
Comment (goderbauer) [inline packages/flutter/lib/src/scheduler/binding.dart:556]: Can you update the doc comment on the method to reflect this change?

**Review by goderbauer — COMMENTED** [review]
Excellent analysis!

File: packages/flutter/lib/src/scheduler/binding.dart [hunk 2]
```diff
@@ -520,11 +520,8 @@ mixin SchedulerBinding on BindingBase {
   /// Returns true if a task was executed and there are other tasks remaining
```
Comment (goderbauer) [inline packages/flutter/lib/src/scheduler/binding.dart:520]: Update this as well to indicate that it also returns true if no task executed, but other tasks are remaining?

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/scheduler/binding.dart [hunk 3]
```diff
@@ -517,14 +517,11 @@ mixin SchedulerBinding on BindingBase {
...
-  /// (even if they are not high-enough priority).
+  /// Returns false if the scheduler is [locked], or if there are no tasks
+  /// remaining.
   ///
-  /// Returns false if no task was executed, which can occur if there are no
-  /// tasks scheduled, if the scheduler is [locked], or if the highest-priority
-  /// task is of too low a priority given the current [schedulingStrategy].
-  ///
-  /// Also returns false if there are no tasks remaining.
+  /// Returns true otherwise, including when no task is executed due to priory
```
Comment (Piinks) [inline packages/flutter/lib/src/scheduler/binding.dart:523]:
```suggestion
  /// Returns true otherwise, including when no task is executed due to priority
```

Comment (Piinks) [reply packages/flutter/lib/src/scheduler/binding.dart:523]: Just a small typo, can fix here

**Review by Piinks — APPROVED** [review]
LGTM, thank you for the fix!

**Comment by jiahaog** [comment]
Thanks for the fix! I overwrote "Google testing" because it seems to have already passed internally but the status isn't reflected here.
