### PR TITLE
Fix rendereditable to check the latest text before setting the selection

### LINKED ISSUE #78918: Clear text crashed in android
b/183372823

## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

final textEditingController = TextEditingController();

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextFormField(
            autofocus: true,
            controller: textEditingController,
            decoration: InputDecoration(
              suffixIcon: IconButton(
                icon: const Icon(Icons.cancel),
                onPressed: () => textEditingController.clear(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

1. run app in android
2. type something and tap clear

## Logs

<details>
<summary>Logs</summary>

```
I/flutter (14849): setSelection on TextSelection(baseOffset: 5, extentOffset: 5, affinity: TextAffinity.upstream, isDirectional: false) on value TextEditingValue(text: ┤├, selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
E/MethodChannel#flutter/textinput(14849): Failed to handle method call
E/MethodChannel#flutter/textinput(14849): java.lang.IndexOutOfBoundsException: invalid selection start: 5
E/MethodChannel#flutter/textinput(14849): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:724)
E/MethodChannel#flutter/textinput(14849): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/MethodChannel#flutter/textinput(14849): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/MethodChannel#flutter/textinput(14849): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput(14849): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/textinput(14849): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/textinput(14849): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput(14849): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter/textinput(14849): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#flutter/textinput(14849): 	at android.app.ActivityThread.main(ActivityThread.java:6334)
E/MethodChannel#flutter/textinput(14849): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput(14849): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/MethodChannel#flutter/textinput(14849): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

```
```

</details>

### LINKED ISSUE #78978: Calling clear() on TextEditingController causes an exception on Android
https://b.corp.google.com/issues/183372823.

Sample code
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

final textEditingController = TextEditingController();

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextFormField(
            autofocus: true,
            controller: textEditingController,
            decoration: InputDecoration(
              suffixIcon: IconButton(
                icon: const Icon(Icons.cancel),
                onPressed: () => textEditingController.clear(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

Stack trace
```
E/MethodChannel#flutter/textinput( 9823): Failed to handle method call
E/MethodChannel#flutter/textinput( 9823): java.lang.IndexOutOfBoundsException: invalid selection start: 4
E/MethodChannel#flutter/textinput( 9823): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:724)
E/MethodChannel#flutter/textinput( 9823): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/MethodChannel#flutter/textinput( 9823): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/MethodChannel#flutter/textinput( 9823): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput( 9823): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/textinput( 9823): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/textinput( 9823): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput( 9823): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter/textinput( 9823): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#flutter/textinput( 9823): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#flutter/textinput( 9823): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput( 9823): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#flutter/textinput( 9823): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 9823): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, invalid selection start: 4, null, java.lang.IndexOutOfBoundsException: invalid selection start: 4
E/flutter ( 9823): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:724)
E/flutter ( 9823): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/flutter ( 9823): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/flutter ( 9823): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 9823): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 9823): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter ( 9823): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 9823): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter ( 9823): 	at android.os.Looper.loop(Looper.java:174)
E/flutter ( 9823): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter ( 9823): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9823): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter ( 9823): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 9823): )
E/flutter ( 9823): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:164:7)
E/flutter ( 9823): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 9823): <asynchronous suspension>
E/flutter ( 9823): 
```

@jason-simmons notes that
"I had started looking at this and saw that it began with https://github.com/flutter/flutter/commit/a46139a2cef8144444a3e13a3970e9a267304b91

RenderEditable._setSelection is calling _setTextEditingValue with a value containing empty text, but with a selection offset based on the old text value before it was cleared."

### PR DESCRIPTION
**Pull request by chunhtai**
When user taps on a textfield,  both the gesture recognizer on top of the editable text and the render editable will handle the tap. This is due to the renderEditable needs to be able to receive tap if any of its textspans have gesture recognizers.

This causes an issue if the gesture recognizer on top of the editable text changes the text in text editing controller. It took one frame for the text to propagate to renderEditable, and renderEditable may uses outdated text stored in its textpainter to handle the pointer events.

This pr adds a sanity check in rendereditable before it wants to set the selection in response of pointer events.

fixes https://github.com/flutter/flutter/issues/78918
fixes https://github.com/flutter/flutter/issues/78978
## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -564,6 +564,21 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+      // The nextSelection is calculated based on _plainText, which can be out
+      // of sync with the textSelectionDelegate.textEditingValue by one frame.
+      // This is due to the render editable and editable text handle pointer
+      // event separately. If the editable text changes the text during the
+      // event handler, the render editable will use the outdated text stored in
+      // the _plainText when handling the pointer event.
+      //
+      // If this happens, we need to make sure the new selection is still valid.
+      final int textLength = textSelectionDelegate.textEditingValue.text.length;
+      nextSelection = nextSelection.copyWith(
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:577]: Does the linter complain about modifying a function parameter?  If not then this is fine.

File: packages/flutter/test/material/text_field_test.dart [hunk 2]
```diff
@@ -393,6 +393,33 @@ void main() {
     expect(renderEditable.cursorColor!.alpha, 0);
   }, variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.iOS,  TargetPlatform.macOS }));
 
+  // Regression test for https://github.com/flutter/flutter/issues/78918.
+  testWidgets('RenderEditable sets correct text editing value', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:397]: I confirmed that this fails on master 👍

File: packages/flutter/lib/src/rendering/editable.dart [hunk 3]
```diff
@@ -564,6 +564,21 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
   }
 
   void _setSelection(TextSelection nextSelection, SelectionChangedCause cause) {
+    if (nextSelection != const TextSelection.collapsed(offset: -1)) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/rendering/editable.dart:567]:
```suggestion
    if (nextSelection.isValid) {
```

**Review by justinmc — APPROVED** [review]
LGTM

This feels hacky at first glance, but I believe it is necessary given the current architecture.  Hopefully we can fix the root causes of this in the future.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:577]: AFAIK parameters are not final (which is weird) and we're doing this in multiple places.

**Review by LongCatIsLooong — APPROVED** [review]

**Comment by justinmc** [comment]
It looks like this caused some legitimate failures, e.g. [here in rendering/editable_test.dart](https://github.com/flutter/flutter/blob/515ef91ba1f6021403e30ecf535a852e3cbd9a2c/packages/flutter/test/rendering/editable_test.dart#L472).

**Comment by justinmc** [comment]
The problem seems to just be that the test needs to be updated to set the text value to its TextSelectionDelegate as well.

**Review by justinmc — APPROVED** [review]
LGTM with the fix for the tests 👍
