### PR TITLE
Linux and Windows right clicking text behavior

### LINKED ISSUE #101587: Right clicking text on Linux and Windows shouldn't change the selection
This is the behavior I see natively on TextEdit on Linux when I right click, tested on my work computer and my personal Ubuntu machine:

out

Windows Notepad is the same.

However, currently Flutter on all platforms seems to change the selection and move the context menu, which is the native Mac behavior:

out

Flutter should match the native Linux and Windows behavior.

## How to reproduce

  1. Run any Flutter app with a text field, such as the example given below.
  2. Enter some text.
  3. Right click on some text in the field other than where the cursor is.

Expected: The selection doesn't change and the menu is dismissed, on Linux and Windows.
Actual: The clicked word is selected and the menu moves to the new location.

<details>

<summary>Example code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(),
          ],
        ),
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by justinmc**
Right clicking a text field should toggle the menu on Windows and Linux, whereas on Mac it selects the word and moves the menu.

| Native Linux | Flutter before this PR |
| --- | --- |
| image | image |

Fixes https://github.com/flutter/flutter/issues/101587

### CODE REVIEW

File: packages/flutter/test/material/text_field_test.dart [hunk 1]
```diff
@@ -10057,9 +10202,9 @@ void main() {
     await tester.pumpAndSettle();
 
     expect(RendererBinding.instance.mouseTracker.debugDeviceActiveCursor(1), SystemMouseCursors.text);
-    expect(find.text('Copy'), findsOneWidget);
+    expect(find.text('Paste'), findsOneWidget);
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/text_field_test.dart:10205]: Why does this change from `Copy` to `Paste`?

**Review by Renzo-Olivares — APPROVED** [review]
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
```

File: packages/flutter/test/material/text_field_test.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart:10205]: Copy isn't shown if the selection is collapsed.  Previously, right clicking would always select the underlying word, so copy would always be shown.  Now it will be collapsed on Windows and Linux, and copy won't be there.  But paste should always be there.

Comment (Renzo-Olivares) [reply packages/flutter/test/material/text_field_test.dart:10205]: Oh I get it. Thanks for the clarification!

**Comment by justinmc** [comment]
The failed Google test seemed to have nothing to do with this PR (it was about the number of parameters in `Icon`...).  I've pushed a merge commit and hopefully it will go green this time.
