### PR TITLE
[flutter_tools] enable `flutter upgrade` to support force pushed branches

### LINKED ISSUE #55576: Flutter upgrade should support upstream branches that have been force pushed
With our current flutter release revamp, we intend to empty merge back to master from every release branch cherry-pick and then have flutter upgrade *always* fast forward. However, this would severely limit the choices of which release to promote to a branch if said branch had a cherry pick late in its life cycle. Consider:

```
I   <- HEAD of master
|
H   <- empty merge beta into master
|\
| G <- beta cherry pick of F 1.0.0-0.1.pre, HEAD of beta branch
| |
F | <- fix for A
| |
E | <- regression
| |
D | <- dev release 1.1.0-0.0.pre, candidate for next beta
| |
C | <- important feature desired for next beta release
|/
B   <- dev & beta release 1.0.0-0.0.pre
|
A   <- regression
```

In this situation, where commit G is a cherry pick onto the beta branch, and H is the subsequent merge to master, the next beta release would have to be (or be branched from) a commit that appears AFTER H in the master branch, or else users on commit G would not be able to fast forward to the next beta version. However, picking a commit after H would mean also picking up the regression in E.

Thus, we should restore support in `flutter upgrade` for non-fast-forward upgrades.

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

In https://github.com/flutter/flutter/pull/53715 I removed support for `flutter upgrade`-ing forward through a force pushed branch assuming that we would not be force pushing in the future, and to allow the `downgrade_upgrade_integration_test` to properly test upgrading.

However, because of #55576, we will have to again force push past hotfixes. The way upgrading from hotfixed branches *previously* worked was:

1. reset backward to the last non-hotfix tag on the branch (e.g. `v1.2.3+hotfix.4 -> v1.2.3`)
1. do a `git pull --ff` fast forward to the tip of the branch (e.g. `v1.2.3 -> 1.3.0`).

However, with the new release scheme, finding the point to reset to is not as simple as stripping out the `+hotfix.x` from the tag (I'm guessing we could use `git merge-base master <channel>`. However this would regress the `downgrade_upgrade_integration_test`, and since we're doing a hard reset, we might as well just hard reset to the upstream HEAD:

1. fetch the upstream version of the branch, `git fetch`
1. retrieve the revision of the upstream HEAD, `git rev-parse --verify @{u}`
1. hard reset to the upstream HEAD, `git reset --hard <revision from last step>`

## Related Issues

Fixes https://github.com/flutter/flutter/issues/55576.

## Tests

I updated mocks to the unit tests and the `downgrade_upgrade_integration_test` still passes.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/upgrade.dart [hunk 1]
```diff
@@ -100,7 +100,12 @@ class UpgradeCommandRunner {
     @required FlutterVersion flutterVersion,
     @required bool testFlow,
   }) async {
-    await verifyUpstreamConfigured();
+    final String upstreamRevision = await fetchRemoteRevision();
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/upgrade.dart:103]: I know we used to have this check, could you remind me of the reason we added? Is there git console spam on no-op upgrades otherwise?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/upgrade.dart:103]: I think before, we never grabbed the revision that we wanted to upgrade to, so the way that we checked if an upgrade wasn't necessary was that we saved the version we were at, did an upgrade, and checked to see if we were on the same commit. if so, the upgrade was an essential no-op, and we didn't have to do the second half.

Since we're grabbing the desired upgrade target revision from the start, just exist early without messing with their repo.

**Review by jmagman — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/commands/upgrade.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/upgrade.dart:103]: That makes sense, thanks Chris!

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by zanderso — COMMENTED** [review]
dbc

File: packages/flutter_tools/lib/src/commands/upgrade.dart [hunk 2]
```diff
@@ -227,33 +238,20 @@ class UpgradeCommandRunner {
...
-
-    // Check if the upgrade did anything.
-    bool alreadyUpToDate = false;
-    try {
-      final FlutterVersion newFlutterVersion = FlutterVersion(const SystemClock(), workingDirectory);
-      alreadyUpToDate = newFlutterVersion.channel == oldFlutterVersion.channel &&
-        newFlutterVersion.frameworkRevision == oldFlutterVersion.frameworkRevision;
-    } on Exception catch (e) {
-      globals.printTrace('Failed to determine FlutterVersion after upgrade fast-forward: $e');
+    if (result.exitCode != 0) {
```
[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/upgrade.dart:252]: Good point, lemme look into it.

[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/upgrade.dart:252]: Created [this PR](https://github.com/flutter/flutter/pull/55759) to address.
