### PR TITLE
Transform PointerEvents to the local coordinate system of the event receiver

### LINKED ISSUE #18408: Transforms break UI hit testing
If you use a Transform widget to perform a 3D transformation, it breaks the UI (you cannot click on a button anymore). Scaling and rotateZ seem to be fine, but rotateX or rotateY seem to break things if you rotate more than a few degrees.

To reproduce, run the file https://gist.github.com/wmleler/cfc18137ce7db77d7e599e179dee4619 (change its name to main.dart, of course)

To rotate things, just touch the screen and pan around, like this (the little moving circle is the position of the user's finger):

screen2

As long as the screen is not rotated very much, you can still tap the FAB and increment the counter. Rotate a little more and the tap target is slightly away from the FAB itself and you can still find it by tapping around. But rotate more than that, and you can't even find the tap target.

### LINKED ISSUE #29916: Scrollables do not obey MediaQuery devicePixelRatio
A client in Google is trying to scale the contents of their screen to other screen factors using a combination of Transform and creating a new MediaQuery. Something along these lines:

```dart
Transform(
  transform: Matrix4.diagonal3Values(transformScale, transformScale, 1.0),
  child: MediaQuery(
    data: parentMediaQuery.copyWith(
      size: virtualSize,
      devicePixelRatio: transformScale * parentMediaQuery.devicePixelRatio),
    child: child),
);
```

This works pretty well for their intended use case (e.g. the touch input coordinates are transformed correctly). However, they noticed that the drag gesture is not scaling properly. They worked around this by modifying the device pixel ratio in the embedder. Discussion with @chinmaygarde and others have indicated this is a heavy weight solution and we should instead look into fixing this in the framework; hence this issue.

### LINKED ISSUE #31958: Scaling a widget also scales its drag gestures
## Steps to reproduce

Run the following app, and scroll the list of integers by dragging up on the box.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Scaling drag destures is bad',
    home: Scaffold(
      body: Center(
        child: SizedBox(
          width: 240,
          height: 240,
          child: FittedBox(
            fit: BoxFit.fill,
            child: DecoratedBox(
              decoration: BoxDecoration(
                border: Border.all(color: Colors.grey),
                borderRadius: BorderRadius.all(Radius.circular(5)),
                color: Colors.white,
              ),
              child: Padding(
                padding: EdgeInsets.all(1),
                child: ClipRRect(
                  borderRadius: BorderRadius.all(Radius.circular(4)),
                  child: SizedBox(
                    width: 38,
                    height: 38,
                    child: Center(
                      child: ListWheelScrollView(
                        itemExtent: 15,
                        children: <Widget>[
                          ...Iterable<int>.generate(100).map<Widget>((int index) {
                            return Text('$index');
                          }),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  ));
}
```

## Expected behavior

You expect the item being scrolled to follow your finger.

## Actual behavior

The item being scrolled scrolls much faster than your finger moves, because the widget is being scaled 6x, and so the scrolling happens 6x as fast (because the drag gesture is also getting scaled 6x).

### PR DESCRIPTION
**Pull request by goderbauer**
Note: This PR is a follow-up to https://github.com/flutter/flutter/pull/31894.

## Description

Before this change, `PointerEvent`s would always be expressed in the global coordinate system of the screen. The change adds `localPosition` and `localDelta` to `PointerEvent`s, which are expressed in the local coordinate system of the event receiver. This means - among other things - that scrolling now sticks to your finger even if the Scrollable has been scaled up or down. Furthermore, a rotated scrollable can now be scrolled by moving the finger in the (rotated) direction of the scrollview.

Furthermore, this change also fixes hit testing for perspective transforms. For example, if a view is rotated along its x axis, buttons now continue to react to touch events.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/29916
Fixes https://github.com/flutter/flutter/issues/18408
Fixes #31958

## Tests

I added the following tests:

* wrapping HitTestResult and its subclasses
* transforming PointerEvents and related helper methods
* PointerRouter transforms events before delivering them to the route
* PointerSignalResolver delivers the transformed event
* Tests for changed GestureRecognizers to ensure they work in transformed subtrees
* Tests for new MatrixUtil functions
* Tests for position transforming methods on BoxHitTestResult and SliverHitTestResult
* Listener receives transformed events for touch/signal/mouse
* Scrolling now works as expected (sticks to the finger) in transformed subtrees (incl. perspective transform).

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change: https://groups.google.com/forum/#!topic/flutter-announce/CnYVAz5dR4U

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by ooyemyintaung007** [comment]
Thank

**Comment by gspencergoog** [comment]
Looks like you need to check for a null `onHover` callback before trying to call it.

Also, I've been working on trying to make a `Iterable<S> findAll<S>(Offset regionOffset)` on the `Layer` that will return all of the found annotations at that offset, instead of just the first one.

Otherwise, we can't nest Listeners (i.e. we can't put a button that handles hover detection inside of another `Listener` that also handles mouse enter/exit).

How will this change with this PR? WIll I need to apply a transform at each child layer? (And maybe I should wait until this lands?)

**Comment by gspencergoog** [comment]
Actually, in looking at your code some more, it looks like my change was orthogonal to yours, so I committed it: https://github.com/flutter/flutter/pull/32350

**Comment by goderbauer** [comment]
@gspencergoog You're right about the null check. Sorry for being confused. Thanks for looking at it!

**Comment by VerTiGoEtrex** [comment]
Eager to see this merged -- wish I had seen this before I started trying to learn how to "unproject" perspective matrices for hit-testing. Thanks for your work -- it works perfectly!


thanks

File: packages/flutter/lib/src/gestures/events.dart [hunk 1]
```diff
@@ -323,11 +362,50 @@ abstract class PointerEvent extends Diagnosticable {
...
+  /// See also:
+  ///
+  ///  * [transformed], which transforms this event into a different coordinate
+  ///    space.
+  final Matrix4 transform;
+
+  /// The original [PointerEvent] before it was transformed by [transform].
+  ///
+  /// If [transform] is null or the identity transformation this may be null.
+  final PointerEvent original;
```
Comment (gspencergoog) [inline packages/flutter/lib/src/gestures/events.dart]: What is this used for? (might want to document).  Also, if the event is transformed multiple times, should it be the version of the event before the first transform, or before the most recent transform?

File: packages/flutter/lib/src/gestures/recognizer.dart [hunk 2]
```diff
@@ -494,3 +499,49 @@ abstract class PrimaryPointerGestureRecognizer extends OneSequenceGestureRecogni
     properties.add(EnumProperty<GestureRecognizerState>('state', state));
   }
 }
+
+/// A container for a [local] and [global] [Offset].
+///
+/// Usually, the [global] [Offset] is in the coordinate space of the screen
+/// after conversion to logical pixels and the [local] offset is the same
+/// [Offset], but transformed to a local coordinate space.
```
Comment (gspencergoog) [inline packages/flutter/lib/src/gestures/recognizer.dart]: Is there any way to know what the local space is, or what it belongs to?

**Review by gspencergoog — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/gestures/hit_test.dart [hunk 3]
```diff
@@ -73,15 +93,82 @@ class HitTestResult {
...
+  ///
+  ///  * [pushTransform], which describes the use case of this function pair in
+  ///    more details.
+  @protected
+  void popTransform() {
+    assert(_transforms.isNotEmpty);
+    _transforms.removeLast();
+  }
+
+  bool _vectorMoreOrLessEquals(Vector4 a, Vector4 b, { double epsilon =  0.000001 }) {
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/hit_test.dart]: please use the constant for epsilon

cc @dnfield did you look for "0.000" cases? might be some more of those

Comment (Hixie) [inline packages/flutter/lib/src/gestures/hit_test.dart]: maybe this should be _debugMoreOrLessEquals and wrapped in an assert

Comment (Hixie) [reply packages/flutter/lib/src/gestures/hit_test.dart]: (since you only call it from an assert)

File: packages/flutter/lib/src/gestures/recognizer.dart [hunk 4]
```diff
@@ -494,3 +499,49 @@ abstract class PrimaryPointerGestureRecognizer extends OneSequenceGestureRecogni
...
+
+  /// The [Offset] in the local coordinate space.
+  final Offset local;
+
+  /// The [Offset] in the global coordinate space after conversion to logical
+  /// pixels.
+  final Offset global;
+
+  /// Adds the `other.global` to [global] and `other.local` to [local].
+  CombinedOffset operator+(CombinedOffset other) {
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/recognizer.dart]: we should implement - as well, if we have +

File: packages/flutter/lib/src/gestures/recognizer.dart [hunk 5]
```diff
@@ -494,3 +499,49 @@ abstract class PrimaryPointerGestureRecognizer extends OneSequenceGestureRecogni
     properties.add(EnumProperty<GestureRecognizerState>('state', state));
   }
 }
+
+/// A container for a [local] and [global] [Offset].
+///
+/// Usually, the [global] [Offset] is in the coordinate space of the screen
+/// after conversion to logical pixels and the [local] offset is the same
+/// [Offset], but transformed to a local coordinate space.
+class CombinedOffset {
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/recognizer.dart]: I'm not a big fan of this name (it's not an Offset subclass)...

Maybe something based on the word Position? I don't have a good idea...

File: packages/flutter/test/gestures/transformed_monodarg_test.dart [hunk 6]
```diff
@@ -0,0 +1,668 @@
+// Copyright 2019 The Chromium Authors. All rights reserved.
```
Comment (Hixie) [inline packages/flutter/test/gestures/transformed_monodarg_test.dart]: typo in file name

**Comment by Hixie** [comment]
LGTM modulo comments (especially we need a better name than CombinedOffset)

File: packages/flutter/lib/src/gestures/hit_test.dart (hunk 3 above)
Comment (dnfield) [reply packages/flutter/lib/src/gestures/hit_test.dart]: Preparing a patch to remove those.  I searched for `e` numbers initially.

File: packages/flutter/lib/src/gestures/recognizer.dart (hunk 5 above)
Comment (dnfield) [reply packages/flutter/lib/src/gestures/recognizer.dart]: Is there some way we can avoid making a public class at all for this?  It's not clear to me that it does anything outside of this use case we need for this class.

File: packages/flutter/lib/src/gestures/hit_test.dart (hunk 3 above)
Comment (dnfield) [reply packages/flutter/lib/src/gestures/hit_test.dart]: There are a few related to text that I'm going to have to leave as is - they pass on macOS but not Windows or Linux when making the epsilon smaller.

File: packages/flutter/test/gestures/events_test.dart [hunk 7]
```diff
@@ -110,4 +112,342 @@ void main() {
...
+    expect(changed, original);
+  });
+
+  test('transformPosition', () {
+    const Offset position = Offset(20, 30);
+    expect(PointerEvent.transformPosition(null, position), position);
+    expect(PointerEvent.transformPosition(Matrix4.identity(), position), position);
+    final Matrix4 transform = Matrix4.translationValues(10, 20, 0);
+    expect(PointerEvent.transformPosition(transform, position), const Offset(20.0 + 10.0, 30.0 + 20.0));
+  });
```
Comment (spkersten) [inline packages/flutter/test/gestures/events_test.dart]: Having this test with a transformation containing an out of plane rotation (rotateX or rotateY) would be useful as that is a less obvious case that has a bug in the Transform widget.

File: packages/flutter/lib/src/gestures/events.dart [hunk 8]
```diff
@@ -356,6 +434,61 @@ abstract class PointerEvent extends Diagnosticable {
   String toStringFull() {
     return toString(minLevel: DiagnosticLevel.fine);
   }
+
+  /// Returns the transformation of `position` into the coordinate system
+  /// described by `transform`.
+  ///
+  /// The z-value of `position` is assumed to be 0.0. If `transform` is null,
```
[the remark this answers is not in the document]
Comment (spkersten) [reply packages/flutter/lib/src/gestures/events.dart]: If this function is used to convert global to local coordinates, it appears to have the some problem with out of plane rotations as the `Transform` widget which I tried to describe here https://github.com/flutter/flutter/issues/18408#issuecomment-493681361.

File: packages/flutter/lib/src/gestures/events.dart [hunk 9]
```diff
@@ -356,6 +434,61 @@ abstract class PointerEvent extends Diagnosticable {
...
+
+  /// Takes a transform matrix meant for painting and returns a matrix that can
+  /// be used to transform [PointerEvent]s for hit testing.
+  ///
+  /// This method removes the "perspective" component from `paintTransform` by
+  /// setting the third column and third row of the matrix to "0, 0, 1, 0".
+  /// The resulting matrix can be used to determine the point in the local
+  /// coordinate system of the transformed component that is exactly under the
+  /// user's finger when the user is touching the screen.
+  static Matrix4 paintTransformToPointerEventTransform(Matrix4 paintTransform) {
```
Comment (spkersten) [inline packages/flutter/lib/src/gestures/events.dart]: I don't understand why this would work without inverting the matrix. Let's say the paint transformation is to scale both x and y by a factor 2: `T = diag(2, 2, 1, 1)`. That means pixels of the widget are visually presented twice as far from the origin than in the local coordinate system. Then when a user taps the screen on one such pixel, that tap position will be twice as far from the origin than in the local coordinate system as well. So to do hit testing in the local coordinate system, the point would have to be transformed by `drag(0.5, 0.5, 1, 1)`. That should generalise to the inverse of `T`.

**Review by spkersten — CHANGES_REQUESTED** [review]
I've made some comments on the transformations, based on what I found for the `Transform` widget's hit testing. Please consider my comments as doubts that could be looked into and not as facts, since I've spend only a limited amount of time with this PR so far.

File: packages/flutter/test/gestures/events_test.dart (hunk 7 above)
Comment (goderbauer) [reply packages/flutter/test/gestures/events_test.dart]: There's the complex "Perspective transform on scrollable" test at the very bottom of the PR that rotates around X and verifies that scrolling still works.

File: packages/flutter/lib/src/gestures/events.dart (hunk 8 above)
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/gestures/events.dart]: @gspencergoog Offsets only have an x and y value - and the z value is always assumed to be zero. The method is just explicitly documenting that.

@spkersten The secret is in the transform matrix that's passed into this. We take the paint transform, set the third row and third column to (0,0,1,0) and then invert it to get a transform matrix that ignores z.

File: packages/flutter/lib/src/gestures/events.dart [hunk 10]
```diff
@@ -356,6 +434,61 @@ abstract class PointerEvent extends Diagnosticable {
...
+    final Vector4 vector = Vector4(0, 0, 1, 0);
+    return paintTransform.clone()
```
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/gestures/events.dart]: Internally, it's just replacing values in an array, which I would assume is quicker than doing two additional function calls...

File: packages/flutter/lib/src/gestures/events.dart (hunk 9 above)
Comment (goderbauer) [reply packages/flutter/lib/src/gestures/events.dart]: I renamed this function to make it clearer what it actually does.

File: packages/flutter/lib/src/gestures/events.dart [hunk 11]
```diff
@@ -487,7 +681,47 @@ class PointerHoverEvent extends PointerEvent {
...
+         original: original,
        );
+
+  @override
+  PointerHoverEvent transformed(Matrix4 transform) {
+    if (transform == this.transform) {
+      return this;
+    }
+    final Offset transformedPosition = PointerEvent.transformPosition(transform, position);
+    return PointerHoverEvent(
```
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/gestures/events.dart]: I do not want to transform the original PointerEvent because a PointerEvent may be delivered to multiple listeners and all listeners needs the event in their local coordinate space.

Not sure how the copyWith constructor would help? I would just call copyWith from here and then the copyWith constructors would contain this ugliness of copying over the values?

File: packages/flutter/lib/src/gestures/events.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/gestures/events.dart]: Clarified and added.

File: packages/flutter/lib/src/gestures/hit_test.dart (hunk 3 above)
Comment (goderbauer) [reply packages/flutter/lib/src/gestures/hit_test.dart]: What epsilon constant are we talking about here? I am having trouble locating it...

File: packages/flutter/test/gestures/events_test.dart (hunk 7 above)
Comment (spkersten) [reply packages/flutter/test/gestures/events_test.dart]: I hope it's okay, but created the test that I proposed to show that it fails: https://github.com/goderbauer/flutter/compare/s2...spkersten:goderbauer-s2-rotation-test?expand=1

Comment (spkersten) [reply packages/flutter/test/gestures/events_test.dart]: I've looked at the "Perspective transform on scrollable" test and it made me really confused. It also fails when I removed the perspective (`setEntry(3,2, 0.001)`) and only keep the rotation. So I add the widget tree in an app to see what happens:
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Foo());
}

class Foo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
      transform: Matrix4.identity()
        ..setEntry(3, 2, 0.001)
        ..rotateX(math.pi / 4)
      ,
      child: Container(
        padding: EdgeInsets.all(16),
        color: Colors.yellow,
        child: Center(
          child: Container(
            width: 200,
            child: ListView.builder(
//            controller: controller,
              cacheExtent: 0.0,
              itemBuilder: (BuildContext context, int index) {
                return Container(
                  height: 100.0,
                  color: index % 2 == 0 ? Colors.blue : Colors.red,
                  child: Text('Tile $index'),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}
```
I've added the `DecoratedBox` to see more clearly what is going on. Here is a screenshot:
Screenshot 2019-05-24 at 19 42 30
So it looks like the children aren't transformed at all!

Comment (goderbauer) [reply packages/flutter/test/gestures/events_test.dart]: > https://github.com/goderbauer/flutter/compare/s2...spkersten:goderbauer-s2-rotation-test?expand=1

Yes, applying `MatrixUtils.transformPoint` in both directions will not work as that method completely drops the z value on the floor as you already found out. If you use that method to transform a point P(x, y, 0) on the xy-plane of a x-rotated render plane you will end up with a point P'(x', y', z') and z' will most likely not be 0. If you now take the x' and y' of that point and run it through `transformPoint` again (which just sets z to 0), you will not end up with x and y again.

In combination with `PointerEvent.removePerspectiveTransform` it works because that method modifies the transform matrix in a way to map point P(x, y, 0) from the xy-plane of the render plane to the point P'(x', y', 0) on the xy-plane of the screen (that's the point on the screen at which P will be drawn). Because z is zero for both points, we can now use `MatrixUtils.transformPoint` to correctly transform between the two.

Hope this makes sense? Looking at the other example you posted now...

File: packages/flutter/lib/src/gestures/events.dart (hunk 11 above)
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/lib/src/gestures/events.dart]: Yeah, OK.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Review by dnfield — APPROVED** [review]

File: packages/flutter/test/gestures/events_test.dart (hunk 7 above)
Comment (goderbauer) [reply packages/flutter/test/gestures/events_test.dart]: About your second comment: That looks like an iOS-specific rendering bug. On Android your example renders fine. Let me do a little investigation and file a separate bug about it.

Comment (goderbauer) [reply packages/flutter/test/gestures/events_test.dart]: Actually, it looks like it was a bug with the old engine version that this PR was synced to. I just pulled in master and everything renders correctly. (And hit testing also works as expected.)

File: packages/flutter/lib/src/gestures/recognizer.dart (hunk 5 above)
Comment (goderbauer) [reply packages/flutter/lib/src/gestures/recognizer.dart]: Done.

File: packages/flutter/lib/src/gestures/hit_test.dart (hunk 3 above)
Comment (goderbauer) [reply packages/flutter/lib/src/gestures/hit_test.dart]: Done.

**Comment by goderbauer** [comment]
I took out the event transformation for mouse-specific events (enter/hover/exit) since supporting those correctly will require some re-structuring of how the MouseTracker works. I filed https://github.com/flutter/flutter/issues/33675 to fix that. Please upvote the issue if transformed mouse events are important for you.

**Comment by mtcliatt** [comment]
I'm still getting global events from `GestureDetector.onScaleUpdate`. I created a minimal example, where I've got a box that renders the initial focal point of the gesture, as well as the current focal point: [example on gist.github](https://gist.github.com/mtcliatt/24fc63d7d4f58f1e928be1da47c90b2f). 

Here's a screenshot of the example that shows the focal points below the box that contains the gesture detector: [link](https://drive.google.com/open?id=1vse_a0u9nISnlPSpLQDPJgDinv6SvNer).

Is this expected?

I'm running: 
Flutter 1.6.8-pre.43 • channel master • https://github.com/flutter/flutter.git
Framework • revision cd1d40a7c9 (7 hours ago) • 2019-06-03 11:08:30 -0700
Engine • revision f9ce01674e
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 224f82c21c)
