### PR TITLE
fix: exclude semantics for disabled dates

### LINKED ISSUE #178713: CupertinoDatePicker reads disabled dates when VoiceOver is on.
### Steps to reproduce

1. Add CupertinoDatePicker to use in any simple UI of your choice.
2. Set minimumDate and maximumDate property for the date picker.
3. Enable voice over from iPhone setting App.
4. Now try to scroll to dates where it is disabled.

### Expected results

Date picker should not scroll to disabled dates because native iOS picker in voice over mode don't allow scrolling to disabled dates or at least voice over should not read disabled dates, as this can mislead users with visual impairments.

### Actual results

Date picker in voiceover mode allowing scroll to disable dates.

### Code sample

```
CupertinoDatePicker(
                  minimumDate: firstDate,
                  maximumDate: lastDate,
                  initialDateTime: dateNow,
                  onDateTimeChanged: (DateTime newDateTime) {
                    changedDate = newDateTime;
                  },
                  mode: CupertinoDatePickerMode.date,
                )
```

### Screenshots or Video

https://github.com/user-attachments/assets/26310fda-2d97-4f38-ae32-b0506da9ffbc

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

_No response_

### Flutter Doctor output

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
```
[✓] Flutter (Channel stable, 3.22.0, on macOS 15.6.1 24G90 darwin-arm64, locale en-US)
    • Flutter version 3.22.0 on channel stable at /Users/sarim/fvm/versions/3.22.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (1 year, 6 months ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 36.1.0)
    • Android SDK at /Users/sarim/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.8+-14196175-b1038.72)

[✓] VS Code (version 1.105.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.120.0

[✓] Connected device (5 available)
    • Sarim’s iPhone (mobile)         • 00008120-000A43363A7BC01E            • ios            • iOS 18.6.2 22G100
    • iPhone 12 Pro (mobile)          • ED65F754-AF51-4C71-B04C-17CAED855C85 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5
      (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.6.1 24G90 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.6.1 24G90 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 142.0.7444.162
    ! Error: Browsing on the local area network for Labeeqa’s Iphone. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by rkishan516**
## Changes
* Exclude semantics for disabled dates directly in CupertinoDatePicker

fixes: #178713

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/picker.dart [hunk 1]
```diff
@@ -568,14 +568,26 @@ class _RenderCupertinoPickerSemantics extends RenderProxyBox {
     if (indexedChildren[_currentIndex] == null) {
       return node.updateWith(config: config);
     }
-    config.value = indexedChildren[_currentIndex]!.label;
+    final String currentLabel = indexedChildren[_currentIndex]!.label;
+    // If the current item has an empty label (e.g., wrapped with ExcludeSemantics),
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/picker.dart:572]: if this is wrapped in `ExcludeSemantics` how does this method get called in the first place?

File: packages/flutter/lib/src/cupertino/picker.dart [hunk 2]
```diff
@@ -568,14 +568,26 @@ class _RenderCupertinoPickerSemantics extends RenderProxyBox {
...
+    // don't set any semantics configuration to avoid assertion errors.
+    // The semantics system requires that if "value" is empty, "increasedValue"
+    // and "decreasedValue" must also be empty, and no increase/decrease actions
+    // should be set.
+    if (currentLabel.isEmpty) {
+      return node.updateWith(config: config);
+    }
+    config.value = currentLabel;
     final SemanticsNode? previousChild = indexedChildren[_currentIndex - 1];
     final SemanticsNode? nextChild = indexedChildren[_currentIndex + 1];
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/picker.dart:582]: same here, for the ExludesSemantics, they shouldn't be in the in indexedChildren I think? is the `ExludesSemantics` wrapped in the wrong level?

File: packages/flutter/lib/src/cupertino/picker.dart (hunk 1 above)
Comment (rkishan516) [reply packages/flutter/lib/src/cupertino/picker.dart:572]: Hey @chunhtai, 

If we look at assembleSemanticsNode in picker.dart:553:

  1. The method iterates over all child semantics nodes via scrollable.visitChildren
  2. It builds indexedChildren map using each node's indexInParent
  3. Nodes wrapped with ExcludeSemantics are still present in this iteration - they just have an empty label

 So the SemanticsNode for a disabled date still exists and gets added to indexedChildren, but its label property is empty.

**Comment by rkishan516** [comment]
> What is the status of this PR? (from triage)

Waiting for another review after https://github.com/flutter/flutter/pull/178981#discussion_r2558437790

File: packages/flutter/lib/src/cupertino/picker.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/cupertino/picker.dart:572]: I see, it is the ListWheelChildBuilderDelegate that wrap all the children with indexedSemantics even for those who ExcludedSemantics which is not ideal, but fixing this will probably need to modify the API which probably not worth it. This is good then

**Review by chunhtai — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/cupertino/picker.dart [hunk 3]
```diff
@@ -568,14 +568,26 @@ class _RenderCupertinoPickerSemantics extends RenderProxyBox {
...
       return node.updateWith(config: config);
     }
-    config.value = indexedChildren[_currentIndex]!.label;
+    final String currentLabel = indexedChildren[_currentIndex]!.label;
+    // If the current item has an empty label (e.g., wrapped with ExcludeSemantics),
+    // don't set any semantics configuration to avoid assertion errors.
+    // The semantics system requires that if "value" is empty, "increasedValue"
+    // and "decreasedValue" must also be empty, and no increase/decrease actions
+    // should be set.
+    if (currentLabel.isEmpty) {
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/picker.dart:577]: can we also add a test for this if-block?

Comment (rkishan516) [reply packages/flutter/lib/src/cupertino/picker.dart:577]: Sure, will add and push.

File: packages/flutter/test/cupertino/picker_test.dart [hunk 4]
```diff
@@ -100,6 +100,75 @@ void main() {
...
+    await tester.pumpWidget(
+      CupertinoApp(
+        home: SizedBox(
+          height: 300.0,
+          width: 300.0,
+          child: CupertinoPicker(
+            scrollController: controller,
+            itemExtent: 50.0,
+            onSelectedItemChanged: (_) {},
+            children: <Widget>[
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/picker_test.dart]: add const

File: packages/flutter/test/cupertino/picker_test.dart [hunk 5]
```diff
@@ -100,6 +100,75 @@ void main() {
...
+              // Item at index 1 is excluded from semantics (simulating a disabled item)
+              const ExcludeSemantics(child: Text('1')),
+              const Text('2'),
+            ],
+          ),
+        ),
+      ),
+    );
+
+    // When the current item (index 1) has an empty label due to ExcludeSemantics,
```
Comment (victorsanni) [inline packages/flutter/test/cupertino/picker_test.dart:132]: uber nit: Would be nice if we had periods at the end of these comments.

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/test/cupertino/picker_test.dart (hunk 5 above)
Comment (rkishan516) [reply packages/flutter/test/cupertino/picker_test.dart:132]: Updated.

File: packages/flutter/test/cupertino/picker_test.dart (hunk 4 above)
Comment (rkishan516) [reply packages/flutter/test/cupertino/picker_test.dart]: Updated.
