### PR TITLE
Fix spell_check_test

### LINKED ISSUE #110611: Linux_android spell_check_test is consistently failing, "The processing instruction target matching "[xX][mM][lL]" is not allowed."
```
[spell_check_test] [STDOUT] stderr: [        ] FAILURE: Build failed with an exception.
[spell_check_test] [STDOUT] stderr: [        ] * What went wrong:
[spell_check_test] [STDOUT] stderr: [        ] Execution failed for task ':app:mergeDebugResources'.
[spell_check_test] [STDOUT] stderr: [        ] > /opt/s/w/ir/x/w/recipe_cleanup/tmpg4n5wqkj/flutter sdk/dev/integration_tests/spell_check/android/app/src/main/res/values/styles.xml:5:6: Error: The processing instruction target matching "[xX][mM][lL]" is not allowed.
[spell_check_test] [STDOUT] stderr: [        ] * Try:
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804378514533463825/+/u/run_spell_check_test/test_stdout

@camsim99 testowner

### PR DESCRIPTION
**Pull request by camsim99**
Fixes https://github.com/flutter/flutter/issues/110611 by moving xml declarations to the top of the file. Also includes a fix for  a merge error I found.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/integration_tests/spell_check/integration_test/integration_test.dart [hunk 1]
```diff
@@ -147,7 +147,7 @@ Future<void> main() async {
 
     await tester.pumpWidget(const MyApp());
 
-    await tester.enterText(find.byType(EditableText), 'Hey wrororld! Hey!');
+    await tester.enterText(find.byType(EditableText), 'Hey cfabiueqqocnakoef! Hey!');
```
Comment (camsim99) [inline dev/integration_tests/spell_check/integration_test/integration_test.dart:150]: @jmagman I found that when running this through the devicelab locally, the "wrororld" was either not detected as misspelled or learned. I don't want to introduce any flakiness, though, so would it be best to remove this test? I notice that the next test below passes consistently, so that's why I changed this to gibberish.

Comment (jmagman) [reply dev/integration_tests/spell_check/integration_test/integration_test.dart:150]: How about leaving this as-is, and if it introduces flakes then reevaluate.

**Review by jmagman — APPROVED** [review]

File: dev/integration_tests/spell_check/integration_test/integration_test.dart (hunk 1 above)
Comment (camsim99) [reply dev/integration_tests/spell_check/integration_test/integration_test.dart:150]: Sounds good!

Comment (camsim99) [reply dev/integration_tests/spell_check/integration_test/integration_test.dart:150]: As somewhat expected, this introduced flakes https://github.com/flutter/flutter/issues/111569#issue-1373260894. Before removing the test, I'm going to investigate this further since the issue seems more related to the rendering side rather than the spell check side, since the other tests checking for spell check results are passing.
