### PR TITLE
Fix documentation of equality functions.

### LINKED ISSUE #78730: Deep equality
Functions `listEquals`, `mapEquals`, and `setEquals` do not inspect _deep_ equality despite the documentation claims it. Somebody noticed this, but instead of improving the implementation, only added a note that _deep_ means not deep at all: "The term "deep" above refers to the first level of equality: if the elements are maps, lists, sets, or other collections/composite objects, then the values of those elements are not compared element by element unless their equality operators ([Object.operator==]) do so." Here: [https://github.com/flutter/flutter/commit/ce1509714c28fec0462fc702c8d9b8d2d4878bf4#](https://github.com/flutter/flutter/commit/ce1509714c28fec0462fc702c8d9b8d2d4878bf4#)

### PR DESCRIPTION
**Pull request by KristofMerey**
The first line of the documentation of equality functions `listEquals`, `mapEquals`, and `setEquals` claimed that they are deep equality functions. A later paragraph explained that they check for deep equality only if the elements, which are collections, implement the equality operator to do so. That is almost never the case.

The first line of the documentation was changed to shallow equality, and a reference was added to the `DeepCollectionEquality` class.

Fixes #78730

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

Only the documentation was modified.

### CODE REVIEW

**Comment by KristofHorvath** [comment]
@darshankawar Hi, you made the triage of my original issue. I realized that the collection package handles the situation perfectly well, so some changes in the documentation solve the issue. Could you review this PR or recommend somebody?

File: packages/flutter/lib/src/foundation/collections.dart [hunk 1]
```diff
@@ -4,16 +4,16 @@
...
 /// Returns true if the sets are both null, or if they are both non-null, have
 /// the same length, and contain the same members. Returns false otherwise.
 /// Order is not compared.
 ///
-/// The term "deep" above refers to the first level of equality: if the elements
-/// are maps, lists, sets, or other collections/composite objects, then the
-/// values of those elements are not compared element by element unless their
-/// equality operators ([Object.==]) do so.
+/// If the elements in the sets are collections (e.g., maps, lists, sets),
+/// then the result may not be as expected since the function uses the
```
Comment (Piinks) [inline packages/flutter/lib/src/foundation/collections.dart:14]: I am not sure this adds clarity to this. What might be expected? 
Also, does the see also for lists and maps not provide additional guidance?

**Comment by Piinks** [comment]
cc @gspencergoog I think you authored this originally as pointed out in the linked issue. Can you take a look at this clarification?

File: packages/flutter/lib/src/foundation/collections.dart [hunk 2]
```diff
@@ -4,16 +4,16 @@
 
 // TODO(ianh): These should be on the Set and List classes themselves.
 
-/// Compares two sets for deep equality.
+/// Compares two sets for shallow equality.
```
Comment (gspencergoog) [inline packages/flutter/lib/src/foundation/collections.dart:7]: Reading this, I would assume "shallow" equality was just `list1 == list2`, and not comparing any of the elements.

Maybe use "element by element equality"?

File: packages/flutter/lib/src/foundation/collections.dart [hunk 3]
```diff
@@ -4,16 +4,16 @@
...
 ///
 /// Returns true if the sets are both null, or if they are both non-null, have
 /// the same length, and contain the same members. Returns false otherwise.
 /// Order is not compared.
 ///
-/// The term "deep" above refers to the first level of equality: if the elements
-/// are maps, lists, sets, or other collections/composite objects, then the
-/// values of those elements are not compared element by element unless their
-/// equality operators ([Object.==]) do so.
+/// If the elements in the sets are collections (e.g., maps, lists, sets),
```
Comment (gspencergoog) [inline packages/flutter/lib/src/foundation/collections.dart:13]: I don't think these changes are needed if you use "element-by-element equality" above, and they seem to make it less clear to me.

Adding a "consider" note for `DeepCollectionEquality` is still a good idea, though.

File: packages/flutter/lib/src/foundation/collections.dart [hunk 4]
```diff
@@ -4,16 +4,16 @@
...
-/// Compares two sets for deep equality.
+/// Compares two sets for shallow equality.
 ///
 /// Returns true if the sets are both null, or if they are both non-null, have
 /// the same length, and contain the same members. Returns false otherwise.
 /// Order is not compared.
 ///
-/// The term "deep" above refers to the first level of equality: if the elements
-/// are maps, lists, sets, or other collections/composite objects, then the
-/// values of those elements are not compared element by element unless their
```
Comment (gspencergoog) [inline packages/flutter/lib/src/foundation/collections.dart:15]: I might use "contents" here instead of "values".

File: packages/flutter/lib/src/foundation/collections.dart [hunk 5]
```diff
@@ -4,16 +4,16 @@
...
 // TODO(ianh): These should be on the Set and List classes themselves.
 
-/// Compares two sets for deep equality.
+/// Compares two sets for shallow equality.
 ///
 /// Returns true if the sets are both null, or if they are both non-null, have
 /// the same length, and contain the same members. Returns false otherwise.
 /// Order is not compared.
 ///
-/// The term "deep" above refers to the first level of equality: if the elements
```
Comment (gspencergoog) [inline packages/flutter/lib/src/foundation/collections.dart:13]: I would replace "deep" here with "element-by-element equality"

File: packages/flutter/lib/src/foundation/collections.dart (hunk 1 above)
Comment (KristofHorvath) [reply packages/flutter/lib/src/foundation/collections.dart:14]: Hi @Piinks, Thank you for your review. The root of my problem was the "deep" word in the first line of the documentation. When I first used this function, I only read the first line and expected a recursive check for equality.

You are right, if the first line is changed to shallow equality, then the expected behavior is different, and so these lines can be confusing.

See also refers to the "twin" functions for lists and maps where the problem is the same.

@gspencergoog also reviewed the changes, so I will make a new commit soon based on your comments.

File: packages/flutter/lib/src/foundation/collections.dart (hunk 2 above)
Comment (KristofHorvath) [reply packages/flutter/lib/src/foundation/collections.dart:7]: Hi @gspencergoog, Thank you for your review. I think the phrase "shallow equality" means exactly what is needed here since it refers to the equality of the objects instead of references (`list1 == list2`). But only in the first level in contrast to deep equality that checks recursively.

Element-by-element equality is not bad; however, it doesn't indicate that the operation is recursive or not (deep or shallow).

What's your opinion about "Compares two sets for shallow (element-by-element) equality."

File: packages/flutter/lib/src/foundation/collections.dart (hunk 3 above)
Comment (KristofHorvath) [reply packages/flutter/lib/src/foundation/collections.dart:13]: @Piinks has also pointed out the problem with this sentence, and I agree with you.

File: packages/flutter/lib/src/foundation/collections.dart (hunk 4 above)
Comment (KristofHorvath) [reply packages/flutter/lib/src/foundation/collections.dart:15]: Good idea!

File: packages/flutter/lib/src/foundation/collections.dart (hunk 5 above)
Comment (KristofHorvath) [reply packages/flutter/lib/src/foundation/collections.dart:13]: I would explain the term shallow with this sentence.

File: packages/flutter/lib/src/foundation/collections.dart (hunk 2 above)
Comment (KristofHorvath) [reply packages/flutter/lib/src/foundation/collections.dart:7]: Or maybe "Compares two sets for shallow equality (element-by-element)."

Comment (gspencergoog) [reply packages/flutter/lib/src/foundation/collections.dart]: Whether it is deep or shallow isn't actually known here, though: if each element's operator== uses its own element-by-element comparison, then it actually is a deep comparison. If it just uses the identity comparison, then it's shallow. That's why I think you should probably avoid both deep and shallow and just describe what it uses (element by element).

Comment (KristofHorvath) [reply packages/flutter/lib/src/foundation/collections.dart]: I understand your point. However, the user who reads this documentation should find out the output if they call these functions for a collection. No one is expected to know the implementation of operator== of the built-in collections. By the way, is it possible that the implementation of operator== will change without rewriting these functions? (There's a TODO comment that says these functions should be on collection classes themselves, so I think a bigger refactoring that could affect the implementation of operator== also would eliminate these functions.)

File: packages/flutter/lib/src/foundation/collections.dart [hunk 6]
```diff
@@ -33,16 +34,17 @@ bool setEquals<T>(Set<T>? a, Set<T>? b) {
   return true;
 }
 
-/// Compares two lists for deep equality.
+/// Compares two lists for shallow equality (element-by-element).
```
Comment (gspencergoog) [inline packages/flutter/lib/src/foundation/collections.dart:37]:
```suggestion
/// Compares two lists for shallow, element by element, equality.
```

File: packages/flutter/lib/src/foundation/collections.dart [hunk 7]
```diff
@@ -4,16 +4,17 @@
 
 // TODO(ianh): These should be on the Set and List classes themselves.
 
-/// Compares two sets for deep equality.
+/// Compares two sets for shallow equality (element-by-element).
```
Comment (gspencergoog) [inline packages/flutter/lib/src/foundation/collections.dart:7]:
```suggestion
/// Compares two sets for shallow, element by element, equality.
```

File: packages/flutter/lib/src/foundation/collections.dart (hunk 2 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/foundation/collections.dart]: If you use the term "shallow", then people will be surprised if they put composite objects into the list and get a deep comparison (because those composites might implement deep comparisons). Which means they actually will be required to know the implementation of `operator==` on the elements put into the list. If you use the term "element by element", then they will not be surprised, because you told them exactly what the behavior is. I think both "shallow" and "deep" here are misleading.

As for whether the implementations of `operator==` can change without `listEquals` changing: Yes they can change without rewriting these functions. The `listEquals` function takes a `List<T>`, and T can be anything, so if the type is a composite object (an object that contains other objects), and that type implements an `operator==` that compares all of its children with the "other" object's children, then you'll get deep equality. The `listEquals` function doesn't know this, and has no way to ask. It's even possible for some parts of the list to be compared deeply and others shallowly.

**Comment by KristofHorvath** [comment]
@gspencergoog For some reason, I couldn't reply to your last review comment about the term shallow.

In some other languages, shallow equality checks the elements by operator== (that usually means reference equality). In contrast, deep equality uses a special equal function on the elements that compare their's values. Since we haven't got these two kinds of equality here, you may be right, and mentioning shallow could be misleading. The term element by element should be enough, and the note below mentions the `DeepCollectionEquality` class, which makes deep equality surely.

You proposed element by element instead of element-by-element. I'm not a native English person, so I accepted it. I think that 'elements are not compared element by element' is the good form. Still, in the phrase 'for element by element equality', the 'element by element' is like an adjective, and I feel that hyphens are missing. But as I said, I'm not competent in this question.

**Comment by gspencergoog** [comment]
> You proposed element by element instead of element-by-element. I'm not a native English person, so I accepted it. I think that 'elements are not compared element by element' is the good form. Still, in the phrase 'for element by element equality', the 'element by element' is like an adjective, and I feel that hyphens are missing. But as I said, I'm not competent in this question.

Actually, I think you're correct here, it probably should be "element-by-element equality", and "elements are not compared element by element".

**Comment by KristofHorvath** [comment]
@gspencergoog I fixed it.

What do you think about the other modifications? (Both 'deep' and 'shallow' terms were removed, only a reference for `DeepCollectionEquality` appears as a note.)

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d
