### PR TITLE
Fix the issue where calling showOnScreen on a sliver after a pinned child in SliverMainAxisGroup does not reveal it.

### LINKED ISSUE #154615: `RenderSliverMainAxisGroup` does not take pinned slivers into consideration when ensureVisible is called on a child
### Steps to reproduce

1. Run the following code.
2. Scroll the screen down so that the `TextField` gets hidden under the `SliverPersistentHeader` (the red box). 
3. Click the button.

### Expected results

The `TextField` is visible on the screen.

### Actual results

The screen scrolls, but the `TextField` is hidden behind the pinned `SliverPersistentHeader`. 

I'm guessing that it has to do with the `childScrollOffset` computation for `RenderSliverMainAxisGroup` (https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/sliver_group.dart#L207-L229). When not overriding the `childScrollOffset` method (defaulting to returning 0), everything works as expected. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  FocusNode textFieldFocus = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverMainAxisGroup(
            slivers: [
              SliverPersistentHeader(
                pinned: true,
                delegate: _SliverTitleDelegate(
                  child: Container(
                    color: Colors.red,
                    height: 60.0,
                  ),
                  height: 60.0,
                ),
              ),
              SliverToBoxAdapter(
                  child: TextField(
                focusNode: textFieldFocus,
              )),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.green,
                  height: 500,
                ),
              ),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.black,
                  height: 500,
                ),
              ),
            ],
          )
        ],
      ),
      floatingActionButton: TextButton(
          onPressed: () {
            textFieldFocus.requestFocus();
          },
          child: const Text('Focus TextField')),
    );
  }
}

class _SliverTitleDelegate extends SliverPersistentHeaderDelegate {
  _SliverTitleDelegate({
    required this.height,
    required this.child,
  });
  final double height;
  final Widget child;

  @override
  double get minExtent => height;
  @override
  double get maxExtent => height;

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return child;
  }

  @override
  bool shouldRebuild(_SliverTitleDelegate oldDelegate) => true;
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/1f3dc12d-a681-40ab-8a52-291e28ccf83c

</details>

### Logs

<details open><summary>Logs</summary>

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-SE)
    • Flutter version 3.24.1 on channel stable at /Users/xxx/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (2 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.119

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by yiiim**
Fixes: #154615

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/rendering/sliver.dart [hunk 1]
```diff
@@ -1675,6 +1675,19 @@ abstract class RenderSliver extends RenderObject {
...
+  /// Returns the scroll offset required to reveal the specified child.
+  ///
+  /// This method is used to calculate the scroll offset needed to bring the given
+  /// [child] into view within this sliver. By default, it returns the value from
+  /// [childScrollOffset], but subclasses can override this method to provide
+  /// custom logic for revealing a child.
+  ///
+  /// Typically used by [RenderViewportBase.getOffsetToReveal] to ensure a particular
+  /// child is visible.
+  double? childScrollOffsetToReveal(covariant RenderObject child) {
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/sliver.dart]: Why add this method instead of handling it in the already overridden `childScrollOffset` in `RenderSliverMainAxisGroup`?

Comment (yiiim) [reply packages/flutter/lib/src/rendering/sliver.dart]: Based on the current `childScrollOffset` documentation, it should return the scroll offset of a child item, not necessarily for making the child visible. However, currently in `RenderSliverMainAxisGroup`, it seems to only be called during `ensureVisible`. I tried directly overriding `childScrollOffset` and all tests in `sliver_main_axis_group_test.dart` still pass. So I think this approach is also feasible. But I think `childScrollOffsetToReveal` is also good - it can clearly indicate that it's for revealing a child item's offset. If we don't do this, we might need to modify the documentation description of `childScrollOffset`. I'll follow your guidance on which approach to use.

Comment (Piinks) [reply packages/flutter/lib/src/rendering/sliver.dart]: It looks like this is the value people would consider correct and want back from childScrollOffset for RenderSliverMainAxisGroup. 
I think it makes sense to update the docs for childScrollOffset to clarify. I think SliverMainAxisGroup was the first, and the only so far, sliver that contains sliver children. We already have childScrollOffset and childMainAxis, adding to this space might be confusing to determine which means what.

Comment (Piinks) [reply packages/flutter/lib/src/rendering/sliver.dart]: The childScrollOffsetToReveal method also made me think that folks would expect to be able to configure the alignment and have a return type of RevealedOffset, which the other similar API does.

**Review by Piinks — APPROVED** [review]
LGTM thank you!
