### PR TITLE
[flutter_tools] use fixed entry for dill uploads

### LINKED ISSUE #63243: Cannot easily hot restart a framework test
When `flutter run`ning a test you should be able to restart the test by doing a hot restart. However, when doing so, I always get this error:

```

Performing hot restart...                                              ⣾E/flutter (25430): [ERROR:flutter/shell/common/engine.cc(205)] Could not prepare to run the isolate.
E/flutter (25430): [ERROR:flutter/shell/common/engine.cc(144)] Engine not prepare and launch isolate.
        
Restarted application in 731ms.
Application finished.
hot restart failed to complete: _flutter.runInView: (-32000) Could not run configuration in engine.
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

For historical reasons, the flutter tool uploads dill files to paths based on the entrypoint URI. This isn't actually necessary, and the tool can use specific files : `main.dart.incremental.dill` for incremental dills, and `main.dart.dill`/`main.dart.swap.dill` for full dills. This allows hot restarting applications with an entrypoint outside of `lib/` and simplifies the devFS code.

Fixes https://github.com/flutter/flutter/issues/63243

### CODE REVIEW

File: packages/flutter_tools/lib/src/resident_runner.dart [hunk 1]
```diff
@@ -782,9 +782,9 @@ abstract class ResidentRunner {
     @required bool swap,
   }) {
     if (!fullRestart) {
-      return '$mainPath.incremental.dill';
+      return 'main.dart.incremental.dill';
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/resident_runner.dart:785]: Does this cause any problems if the entrypoint is not called main.dart?

**Review by zanderso — APPROVED** [review]
lgtm w/ question

File: packages/flutter_tools/lib/src/resident_runner.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/resident_runner.dart:785]: Nope, the file name doesn't really matter - I tested with `test/hello_world_test.dart` and `main_2.dart`. It did historically when reload worked from source files.
