### PR TITLE
Fix: Gap between prefix and suffix icon and input field in input deco…

### LINKED ISSUE #149408: InputDecorator gap between prefixIcon and input field is not compliant
### Steps to reproduce

1. Run the given test

### Expected results

The label and input text left position should be 52 pixels, per M3 spec.

image

### Actual results

The label and input text left position is 48 pixels.

### Code sample

<details open><summary>Code sample</summary>

```dart
  testWidgets('Input text horizontal position when prefixIcon is set', (WidgetTester tester) async {
    const String label = "label";
    const String content = "Flutter";
    final TextEditingController controller = TextEditingController(text: content);
    addTearDown(controller.dispose);

    await tester.pumpWidget(
      MaterialApp(
        home: Material(
          child: Align(
            alignment: Alignment.topLeft,
            child: TextField(
              controller: controller,
              autofocus: true,
              decoration: const InputDecoration(
                filled: true,
                labelText: label,
                prefixIcon: Icon(Icons.search),
              ),
            ),
          ),
        ),
      ),
    );

    expect(find.text(label), findsOne);
    expect(find.text(content), findsOne);

    expect(tester.getSize(find.byType(TextField)), const Size(800.0, 56.0));
    expect(tester.getTopLeft(find.text(label)).dx, 52.0);
    expect(tester.getTopLeft(find.text(content)).dx, 52.0);
  });

```

</details>

### Screenshots or Video

_No response_

### Logs

<details open><summary>Error logs</summary>

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <52>
  Actual: <48.0>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home/bruno/Nevercode/Investigation/investigationapp/test/useM3Migration/input_decorator/input_decorator_basic_test.dart:98:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1025:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/bruno/Nevercode/Investigation/investigationapp/test/useM3Migration/input_decorator/input_decorator_basic_test.dart line 98
The test description was:
  TextField height
════════════════════════════════════════════════════════════════════════════════════════════════════
``` 

</details> 

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.22.0-18.0.pre.572, on Ubuntu 24.04 LTS
```

</details>

### LINKED ISSUE #149409: InputDecorator gap between suffixIcon and input field is not compliant
### Steps to reproduce

1. Run the given test

### Expected results

The input text right position should at 52 pixels from the text field right border, per M3 spec.

image

### Actual results

The input text right position is at 48 pixels from the text field right border.

### Code sample

<details open><summary>Code sample</summary>

```dart

  testWidgets('Input horizontal position when suffixIcon is set', (WidgetTester tester) async {
    const String content = "Flutter";
    final TextEditingController controller = TextEditingController(text: content);
    addTearDown(controller.dispose);

    await tester.pumpWidget(
      MaterialApp(
        home: Material(
          child: Align(
            alignment: Alignment.topLeft,
            child: TextField(
              controller: controller,
              autofocus: true,
              decoration: const InputDecoration(
                filled: true,
                labelText: 'Label text',
                suffixIcon: Icon(Icons.search),
              ),
              //style: const TextStyle(height: 3.0),
            ),
          ),
        ),
      ),
    );

    expect(find.text(content), findsOne);

    expect(tester.getSize(find.byType(TextField)), const Size(800.0, 56.0));
    expect(tester.getTopRight(find.text(content)).dx, 800.0 - 52.0);
  });
```

</details>

### Screenshots or Video

_No response_

### Logs

<details open><summary>Logs</summary>

```console

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <748.0>
  Actual: <752.0>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home/bruno/Nevercode/Investigation/investigationapp/test/useM3Migration/input_decorator/input_decorator_basic_test.dart:96:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1025:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/bruno/Nevercode/Investigation/investigationapp/test/useM3Migration/input_decorator/input_decorator_basic_test.dart line 96
The test description was:
  Input horizontal position when suffixIcon is set
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.22.0-18.0.pre.572, on Ubuntu 24.04 LTS
```

</details>

### PR DESCRIPTION
**Pull request by rkishan516**
Gap between `prefixIcon` and `input` field was not compliant with M3 spec i.e. 16.0 rather it was 12.0
and similar situation was also happening with `suffixIcon` and `input` field.

Now with these changes, its compliant with M3 spec of input decoration.

Fixes #149408 
Fixes #149409 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/material/input_decorator_test.dart [hunk 1]
```diff
@@ -4234,15 +4234,13 @@ void main() {
...
           // 12 is the left padding.
-          // TODO(bleroux): consider changing this padding because from M3 soec this should be 16.
-          expect(getLabelRect(tester).left, 12.0);
-          // TODO(bleroux): consider changing the input text position because, based on M3 spec,
+          expect(getLabelRect(tester).left, 16.0);
+          // Based on M3 spec,
           // the expected horizontal position is 52 (12 padding, 24 icon, 16 gap between icon and input).
           // See https://m3.material.io/components/text-fields/specs#1ad2798c-ab41-4f0c-9a97-295ab9b37f33
           // (Note that the diagrams on the spec for outlined text field are wrong but the table for
           // outlined text fields and the diagrams for filled text field point to these values).
```
Comment (justinmc) [inline packages/flutter/test/material/input_decorator_test.dart:4242]: Can you reflow these comments so that the first line isn't so short?

**Review by justinmc — COMMENTED** [review]
Thanks for attempting to fix this! Can you take a look at the test failures? Changes to InputDecorator's layout can be pretty finicky.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 2]
```diff
@@ -1397,6 +1399,7 @@ class _RenderDecoration extends RenderBox with SlottedContainerRenderObjectMixin
         if (suffixIcon != null) {
           end -= contentPadding.end;
           end += centerLayout(suffixIcon!, end);
+          end += inputToSuffixGap;
```
Comment (bleroux) [inline packages/flutter/lib/src/material/input_decorator.dart:1402]: This change is for the `TextDirection.rtl` case, I would also expect a similar change for the prefix (probably at line 1382)

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 3]
```diff
@@ -1407,6 +1410,7 @@ class _RenderDecoration extends RenderBox with SlottedContainerRenderObjectMixin
         if (prefixIcon != null) {
           start -= contentPadding.start;
           start += centerLayout(prefixIcon!, start);
+          start += prefixToInputGap;
```
Comment (bleroux) [inline packages/flutter/lib/src/material/input_decorator.dart:1413]: This change is for the `TextDirection.ltr` case, I would also expect a similar change for the suffix (probably at line 1438)

File: packages/flutter/test/material/input_decorator_test.dart [hunk 4]
```diff
@@ -4234,15 +4234,12 @@ void main() {
           );
 
           // 12 is the left padding.
```
Comment (bleroux) [inline packages/flutter/test/material/input_decorator_test.dart:4236]:
```suggestion
          // Label left padding is 16.0 (12.0 right padding for a decoration with icons + 4.0 extra padding for the floating label)
```

File: packages/flutter/test/material/input_decorator_test.dart [hunk 5]
```diff
@@ -5358,9 +5355,9 @@ void main() {
           // Left padding is 12 per Material 3 spec.
           expect(tester.getRect(findPrefixIconInnerRichText()).left, 12.0);
           // Check the padding between the prefix icon and the input.
-          // TODO(bleroux): the gap between the icon and the input should be 16 based on M3 specification.
+          // The gap between the icon and the input should be 16 based on M3 specification.
           // See https://github.com/flutter/flutter/issues/149408.
```
Comment (bleroux) [inline packages/flutter/test/material/input_decorator_test.dart:5359]: Remove this reference to the issue, this link was required for the TODO (it no more required now).

File: packages/flutter/test/material/input_decorator_test.dart [hunk 6]
```diff
@@ -5399,9 +5396,9 @@ void main() {
           // Right padding is 12 per Material 3 spec.
           expect(getDecoratorRect(tester).right - tester.getRect(findSuffixIconInnerRichText()).right, 12.0);
           // Check the padding between the suffix icon and the input.
-          // TODO(bleroux): the gap between the icon and the input should be 16 based on M3 specification.
+          // The gap between the icon and the input should be 16 based on M3 specification.
           // See https://github.com/flutter/flutter/issues/149409.
```
Comment (bleroux) [inline packages/flutter/test/material/input_decorator_test.dart:5400]: Remove this reference to the issue, this link was required for the TODO (it no more required now).

**Review by bleroux — COMMENTED** [review]
Thanks for working on this.
I’m ok with the approach (adding prefix/suffix gaps).

As Justin mentioned, be aware that it might be difficult to get this change landed because it will probably break some internal Google tests and maybe some customer tests.
Another difficulty is that `InputDecoration` test coverage is not perfect because the migration of the tests from Material 2 to Material 3 is still in progress (for instance there are missing tests for the RTL text direction).


See my comments on specific lines of the PR but I noticed that the rendering is wrong for RTL.



<details><summary>Here is a code sample that we can use to make this more visual</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(
        child: Material(
          child: Container(
            color: const Color.fromARGB(255, 200, 206, 182),
            padding: const EdgeInsets.all(8.0),
            child: const Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                SizedBox(height: 10),
                IconsMetrics(),
                SizedBox(height: 4),
                InputDecoratorWithIcons(
                  textDirection: TextDirection.ltr,
                ),
                SizedBox(height: 16),
                FloatingLabelMetrics(),
                SizedBox(height: 4),
                InputDecoratorWithIcons(
                  textDirection: TextDirection.ltr,
                  labelText: 'Label text',
                ),
                SizedBox(height: 30),
                IconsMetrics(),
                SizedBox(height: 4),
                InputDecoratorWithIcons(
                  textDirection: TextDirection.rtl,
                ),
                SizedBox(height: 16),
                FloatingLabelMetrics(),
                SizedBox(height: 4),
                InputDecoratorWithIcons(
                  textDirection: TextDirection.rtl,
                  labelText: 'Label text',
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class InputDecoratorWithIcons extends StatelessWidget {
  const InputDecoratorWithIcons({super.key, required this.textDirection, this.labelText});

  final TextDirection textDirection;
  final String? labelText;

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: textDirection,
      child: SizedBox(
        width: 200,
        child: InputDecorator(
          isEmpty: false,
          isFocused: false,
          decoration: InputDecoration(
            labelText: labelText,
            prefixIcon: const Icon(Icons.search),
            suffixIcon: const Icon(Icons.cancel),
            filled: true,
            border: const OutlineInputBorder(),
          ),
          child: Container(
            width: 200, // Too long but will be cut.
            height: 24, // Simulate default font height.
            color: Colors.blueGrey,
            child: Center(
              child: Text(
                textDirection == TextDirection.rtl ? 'RTL' : 'LTR',
                style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class IconsMetrics extends StatelessWidget {
  const IconsMetrics({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 12,
      child: Row(
        children: [
          // Based on https://m3.material.io/components/text-fields/specs#1ad2798c-ab41-4f0c-9a97-295ab9b37f33.
          Container(color: Colors.purple, width: 12),
          Container(color: Colors.white, width: 24),
          Container(color: Colors.purple, width: 16),
          Container(color: Colors.blueGrey, width: 96), // 200 - 52 - 52
          Container(color: Colors.purple, width: 16),
          Container(color: Colors.white, width: 24),
          Container(color: Colors.purple, width: 12),
        ],
      ),
    );
  }
}

class FloatingLabelMetrics extends StatelessWidget {
  const FloatingLabelMetrics({super.key});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 12,
      child: Row(
        children: [
          // Based on https://m3.material.io/components/text-fields/specs#1ad2798c-ab41-4f0c-9a97-295ab9b37f33.
          Container(color: Colors.red, width: 12 + 4), // 16
          Container(color: Colors.white, width: 168),  // 200 - 16 - 16
          Container(color: Colors.red, width: 12 + 4), // 16
        ],
      ),
    );
  }
}

```

</details>

See the following screenshot where I added red arrows to point out to two problems with the rendering in RTL direction
(the colored lines above the decorations are based on the expected padding from the M3 spec):

image

**Comment by rkishan516** [comment]
Sure @bleroux, Let me do the respective changes and notify once done.

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 2 above)
Comment (rkishan516) [reply packages/flutter/lib/src/material/input_decorator.dart:1402]: @bleroux For both cases we are increasing size of box (line 1008 & 1009). So for `TextDirection.rtl` we are adding gap between `suffix` and `input`. On the other side for `TextDirection.ltr` we are adding gap between `prefix` and `input`. So, I don't think we need to add prefix gap (for `TextDirection.rtl`) or suffix gap (for `TextDirection.ltr`). Because that is already handled by size of the box.

Comment (bleroux) [reply packages/flutter/lib/src/material/input_decorator.dart:1402]: The size of the box is correct but the placements in RTL is wrong (too much padding on the left side not enough on the right, see the screenshot I posted).
Testing locally, when adding the logic I pointed, I can get the correct result in RTL but maybe there are other ways to get the correct result.

Comment (rkishan516) [reply packages/flutter/lib/src/material/input_decorator.dart:1403]: Yup, make sense. Sorry, I didn't checked the images. I have pushed respective changes.

**Comment by rkishan516** [comment]
@bleroux I have made changes for `TextDirection.rtl`. Please have a look.

File: packages/flutter/test/material/input_decorator_test.dart [hunk 7]
```diff
@@ -5358,9 +5355,8 @@ void main() {
           // Left padding is 12 per Material 3 spec.
           expect(tester.getRect(findPrefixIconInnerRichText()).left, 12.0);
           // Check the padding between the prefix icon and the input.
-          // TODO(bleroux): the gap between the icon and the input should be 16 based on M3 specification.
-          // See https://github.com/flutter/flutter/issues/149408.
-          expect(getInputRect(tester).left - tester.getRect(findPrefixIconInnerRichText()).right, 12.0);
+          // The gap between the icon and the input should be 16 based on M3 specification.
+          expect(getInputRect(tester).left - tester.getRect(findPrefixIconInnerRichText()).right, 16.0);
         });
```
Comment (bleroux) [inline packages/flutter/test/material/input_decorator_test.dart:5361]: Consider adding a test similar to the one above but for RTL?

File: packages/flutter/test/material/input_decorator_test.dart [hunk 8]
```diff
@@ -5399,9 +5395,8 @@ void main() {
           // Right padding is 12 per Material 3 spec.
           expect(getDecoratorRect(tester).right - tester.getRect(findSuffixIconInnerRichText()).right, 12.0);
           // Check the padding between the suffix icon and the input.
-          // TODO(bleroux): the gap between the icon and the input should be 16 based on M3 specification.
-          // See https://github.com/flutter/flutter/issues/149409.
-          expect(tester.getRect(findSuffixIconInnerRichText()).left - getInputRect(tester).right, 12.0);
+          // The gap between the icon and the input should be 16 based on M3 specification.
+          expect(tester.getRect(findSuffixIconInnerRichText()).left - getInputRect(tester).right, 16.0);
         });
```
Comment (bleroux) [inline packages/flutter/test/material/input_decorator_test.dart:5401]: Similarly, consider adding a test similar to the one above but for RTL?

**Review by bleroux — COMMENTED** [review]
Thanks for the last changes.
There were some missing tests related to RTL, can you add them? (see my review comments).

**Comment by rkishan516** [comment]
Hey @bleroux, I have added both test you mentioned. But as you said, there are many more test related to `TextDirection.rtl`  as pending, I feel I can cover few of them. Do you want me to continue on `this PR` or should I create a new one for those tests ?

**Comment by bleroux** [comment]
> Hey @bleroux, I have added both test you mentioned. But as you said, there are many more test related to `TextDirection.rtl` as pending, I feel I can cover few of them. Do you want me to continue on `this PR` or should I create a new one for those tests ?

@rkishan516 It would be better to add other tests on a new PR because we don't know if this one will be merged (it could be blocked on Google internal testing or being reverted after being merged due to an internal customer having an issue with it).
Adding tests on a separate PR will make it possible to land them without waiting for this PR.

**Comment by rkishan516** [comment]
> @rkishan516 It would be better to add other tests on a new PR because we don't know if this one will be merged (it could be blocked on Google internal testing or being reverted after being merged due to an internal customer having an issue with it). Adding tests on a separate PR will make it possible to land them without waiting for this PR.

Sure, I will create a new PR.

**Comment by bleroux** [comment]
@rkishan516
Can you have a look at the test failures in step 'Linux framework_tests_libraries '?
You can get details on those failures in two different ways:
- Follow the 'Details' link near that CI check, then tap the link 'View more details on flutter-dashboard' and then the link 'stdout[raw]'.
- Running the whole framework test suite locally (go to flutter/packages/flutter directory and run 'flutter test').

**Comment by rkishan516** [comment]
Sure @bleroux, I can fix them.

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 9]
```diff
@@ -2035,14 +2036,14 @@ void main() {
     await tester.pumpAndSettle();
 
     // Check text location in text field.
-    expect(tester.getTopLeft(find.text('Hint')).dx, 48.0);
+    expect(tester.getTopLeft(find.text('Hint')).dx, 52.0);
 
     // By default, the text of item 0 should be aligned with the text of the text field.
     expect(tester.getTopLeft(find.text('Item 0').last).dx, 48.0);
```
Comment (bleroux) [inline packages/flutter/test/material/dropdown_menu_test.dart:2042]: Do you know why this line is not impacted?

Comment (rkishan516) [reply packages/flutter/test/material/dropdown_menu_test.dart:2042]: Oh, weird. I don't know. But let me check.

Comment (rkishan516) [reply packages/flutter/test/material/dropdown_menu_test.dart]: It was happening because I forgot to add padding when leading icon is not there. I have fixed and pushed the change.

Comment (bleroux) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Great 👍

**Review by bleroux — APPROVED** [review]
LGTM! Thanks for keeping up on this PR.
Let me approve the PR and see how it goes with the 'Google testing' CI check.

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 10]
```diff
@@ -581,6 +583,9 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
       }
       setState(() {
         leadingPadding = getWidth(_leadingKey);
+        if (leadingPadding != null) {
+          leadingPadding = leadingPadding! + _kLeadingIconToInputPadding;
+        }
```
Comment (justinmc) [inline packages/flutter/lib/src/material/dropdown_menu.dart:588]: Rather than setting leadingPadding twice can you set it to a local variable first?

**Review by justinmc — APPROVED** [review]
Unfortunately this is failing the Google tests, but I guess that's expected. Pretty much any field with a prefix or suffix in a visual diff test will break with this PR. I'll look through them and see if we can approve the changes.

**Comment by justinmc** [comment]
There are a few tests where the field has broken onto more lines now than before, due to the increased width of the prefix/suffix. I want to double check with the owners that that's ok. Otherwise the failures are expected.

**Review by bleroux — CHANGES_REQUESTED** [review]
While working on InputDecorator intrinsic size, I noticed that this PR needs to update intrinsic width computation.
I filed https://github.com/flutter/flutter/pull/154098 to migrate the intrinsic width test to M3.

@justinmc Thanks in advance for reviewing https://github.com/flutter/flutter/pull/154098
@rkishan516 Once https://github.com/flutter/flutter/pull/154098 will be merged, thanks for updating your PR to satisfy those new tests (you will have to update `computeMinIntrinsicWidth` and `computeMinIntrinsicWidth`).

Fixing this might help with some of the Google testing failures.

**Comment by justinmc** [comment]
Good catch @bleroux! Hopefully that helps with the Google tests.

**Comment by Piinks** [comment]
Hey @rkishan516 thanks for the updates! Can you check the failing tests here?

**Comment by bleroux** [comment]
@rkishan516 https://github.com/flutter/flutter/pull/154098 has been merged, thanks for updating your PR to satisfy those new tests (you will have to update `computeMinIntrinsicWidth` and `computeMinIntrinsicWidth`).

**Comment by rkishan516** [comment]
> @rkishan516 #154098 has been merged, thanks for updating your PR to satisfy those new tests (you will have to update `computeMinIntrinsicWidth` and `computeMinIntrinsicWidth`).

@bleroux What kind of update is required, because I currently see both uses children sizes

**Comment by bleroux** [comment]
> What kind of update is required, because I currently see both uses children sizes

In cas you did not look at the right ones, here are the methods that needs to be updated (`prefixToInputGap` and/or `inputToSuffixGap` should be added when prefix and/or suffix are not null):

https://github.com/flutter/flutter/blob/e167992911f7cfdc95e8a7f77e3a075d61b00561/packages/flutter/lib/src/material/input_decorator.dart#L1171-L1193

**Comment by rkishan516** [comment]
@bleroux I have updated `computeMinIntrinsicWidth` and `computeMinIntrinsicWidth`.

**Review by bleroux — APPROVED** [review]
LGTM! Thanks for this hard work 🙏

**Comment by bleroux** [comment]
@justinmc This PR is ready now. Thank you in advance for checking the Google testing failures.
Especially if the ones you mentioned in https://github.com/flutter/flutter/pull/152069#issuecomment-2307918459 are still there or were fixed with the update of `computeMinIntrinsicWidth` and `computeMinIntrinsicWidth`.

**Comment by justinmc** [comment]
Sorry for the delay here, I'm currently looking at the Google test failures.

**Comment by justinmc** [comment]
I see a few instances where the cursor is sitting in the middle of the first character of the hint, where before this PR it was correctly to the left of the first letter. It's as if the cursor has moved but the hint has not. Any reason why that might happen here?

If I try a simple naive example I don't see the bug (tried on Mac, as pictured the cursor is in the correct place):

Screenshot 2024-09-25 at 3 31 17 PM


<details>

<summary>Example app that doesn't seem to reproduce it</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              decoration: InputDecoration(
                prefixIcon: Icon(Icons.cake),
                hintText: 'hint',
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by justinmc** [comment]
I believe the bug is actually something that needs to be fixed inside of Google's code. I am trying to suggest a fix and contact the team.

**Comment by rkishan516** [comment]
Thanks @justinmc, I will wait for get it fixed from team.

**Comment by justinmc** [comment]
I'm struggling to figure out how to land this, but I just need to track someone down to help me and then we can move forward. I'm writing myself a reminder to check on this next week.

Basically we need to accept visual diff test changes AND make a small change to a customer's code.

**Comment by rayliverified** [comment]
The Material suffix padding specs looks and feels very bad and would not pass design review at most companies.

**Issue**
The suffix right padding is 12dp which cuts off the splash which is 4dp too large. There's no option to customize the size of the splash, nor the right padding.

image

image


So while it technically meets the Material Design specs, the actual result is that the suffix icon is almost unusable because it won't pass design review.

**Comment by rkishan516** [comment]
So, what changes do you suggest @rayliverified ?

**Comment by rayliverified** [comment]
SuffixIconPadding perhaps.

There's already `contentPadding`. Would match the API pattern.

**Comment by rkishan516** [comment]
Sure, I will add suffixIconPadding with default to 4.0

**Comment by rayliverified** [comment]
Amazing, thank you! 

What would the decision be because the clipping is what happens if you follow the material specs exactly (default 0 padding). Adding 4 padding would fix the clipping, but not follow the materials specs.

**Comment by rkishan516** [comment]
I think @bleroux or @justinmc can take a call on that because I think both are not possible together (either we can follow m3 spec or avoid clipping).

**Comment by bleroux** [comment]
@rayliverified @rkishan516
This is an interesting point. It will more actionnable to discuss that on a separate issue.
Getting this PR merged as-is is already far from easy so let's keep this PR discussion focused on the main goal.

**Comment by rkishan516** [comment]
Sure @bleroux, Then I will wait until google test are fixed. Once it's merged, we can create another issue.

**Comment by justinmc** [comment]
@rayliverified Would you be able to create a separate issue with the information in https://github.com/flutter/flutter/pull/152069#issuecomment-2395883216 and tag me?

**Comment by rayliverified** [comment]
Sure, the icon is also bugged where it doesn't respect any size configurations. You can't customize the size of the trailing icon.

**Comment by justinmc** [comment]
@rkishan516 Can you fix the merge conflict here? I'm still working on figuring out how to land this.

**Comment by justinmc** [comment]
Thanks @rkishan516 for all your work here. Hopefully this will roll in smoothly but I'll be keeping an eye on it.

**Comment by rayliverified** [comment]
Amazing work @rkishan516 👏 👏 

Thanks for letting me jump in and distract you. I appreciate your professionalism and humoring me. 

I do have a TODO to open a separate issue with what I raised.

**Comment by justinmc** [comment]
Thank you @rayliverified, no rush!

**Comment by rkishan516** [comment]
No no, Thanks to all of you @justinmc and @bleroux and @rayliverified, Without guidance I couldn't have fetched this far.
