### PR TITLE
Text field border radius bug fix

### LINKED ISSUE #23982: TextField with UnderlineInputBorders animates a border radius even with radius zero
When creating TextField with an InputDecorator, using an UnderlineInputBorder as border for every state and BorderRadius.zero, changing the focused field briefly animates the default 4px border radius in the fields that had their focus state change.

Recording of the issue, notice the top left and right corners
ezgif com-crop

I have reproduced this issue using the iOS simulator, several Android emulators and a OnePlus 3T running 8.0.0

## Steps to Reproduce
Run
[main.dart](https://gist.github.com/krwrang/d2ae7b40d9237be1f9f24c0d94d993c7)

## Logs

```
Analyzing glitch1...                                             
No issues found! (ran in 1.1s)
```

```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en-FI)
    • Flutter version 0.9.4 at /Users/foranamo/Flutter/flutter_v0.5.1
    • Framework revision f37c235c32 (6 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/foranamo/Library/Android/sdk
    • Android NDK at /Users/foranamo/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 27.0.3
    • ANDROID_HOME = /Users/foranamo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.3911.37

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected devices (1 available)
    • iPhone XR • 8446D7A6-E5D6-4437-94FC-6F30C342EBC3 • ios • iOS 12.1 (simulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by justinmc**
Closes https://github.com/flutter/flutter/issues/23982

### CODE REVIEW

File: packages/flutter/test/material/input_decorator_test.dart [hunk 1]
```diff
@@ -1931,6 +1939,50 @@ void main() {
...
+    await tester.pumpAndSettle();
+    expect(getBorderRadius(tester), BorderRadius.zero);
+
+    // Focusing does not change the border either
+    await tester.tap(find.byKey(key));
+    expect(getBorderRadius(tester), BorderRadius.zero);
+    await tester.pump(const Duration(milliseconds: 50));
+    expect(getBorderRadius(tester), BorderRadius.zero);
+    await tester.pump(const Duration(milliseconds: 50));
+    expect(getBorderRadius(tester), BorderRadius.zero);
```
Comment (justinmc) [inline packages/flutter/test/material/input_decorator_test.dart]: This line is where it fails if I remove my fix.  If I change the first pump to 100 and get rid of this one, it doesn't fail at all!  It's a really weird timing thing.  Let me know if there's a better way to test it.

Comment (HansMuller) [reply packages/flutter/test/material/input_decorator_test.dart]: Pump one frame to "get the animation started" and then you can pump frames with arbitrary durations.

File: packages/flutter/test/material/input_decorator_test.dart [hunk 2]
```diff
@@ -1931,6 +1939,50 @@ void main() {
...
+                ),
+              ),
+            ),
+          ),
+        ),
+      ),
+    );
+
+    // TextField has the given border and doesn't ever tween to the default
+    expect(getBorderRadius(tester), BorderRadius.zero);
```
Comment (HansMuller) [inline packages/flutter/test/material/input_decorator_test.dart]: It would be useful to verify that the border is initially zero, however there's no animation here.

**Comment by justinmc** [comment]
@HansMuller Updated.

File: packages/flutter/test/material/input_decorator_test.dart [hunk 3]
```diff
@@ -1931,6 +1939,43 @@ void main() {
     expect(getBorder(tester), disabledBorder);
   });
 
+  testWidgets('OutlineInputBorder radius carries over when lerping', (WidgetTester tester) async {
+    const Key key = Key('textField');
```
Comment (HansMuller) [inline packages/flutter/test/material/input_decorator_test.dart]: At the top of the test body, please include:
```
// This is a regression test for https://github.com/flutter/flutter/issues/23982

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/test/material/input_decorator_test.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/test/material/input_decorator_test.dart]: :+1:
