### PR TITLE
Fixes inputDecoration sibling explicit child not included in semantic…

### LINKED ISSUE #169499: InputDecoration -> suffix Semantics.identifier not showing in Maestro.dev when building with Flutter 3.32.0
### Steps to reproduce

Hello Flutter team,

Yesterday we ran and passed our Maestro.dev tests, then decided to update Flutter from 3.29 to 3.32. 
After that, some tests started failing. It turns out that Maestro.dev couldn't find some elements with specific identifiers.
To add a visible identifier for Maestro, we were using the Semantics widget with 'container:true' - see code sample.

While this Widget created a visible identifier for Maestro.dev to find on Flutter 3.29, it seems to no longer be the case with 3.32.

1. Create the default project with 'flutter create'
2. Replace the main.dart file by the code below.
3. Run the app on Android
4. Launch Maestro.dev
5. Focus the TextInput and select the Container with Semantics

### Expected results

The input decoration with the semantics 'myId' was visible by Maestro.dev in Flutter <= 3.29.

### Actual results

The input decoration with the semantics 'myId' is not seen by Maestro.dev.

Our automated tests cannot find the element to click on, and fail:

Image

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Input TextField ',
      theme: ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple)),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,

        title: Text(widget.title),
      ),
      body: Center(
        child: TextField(
          decoration: InputDecoration(
            suffix: Semantics(
              identifier: 'myId',
              container: true,
              child: Container(width: 50, height: 50, color: Colors.amber),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

Image

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.32.0, on macOS 15.5 24F74 darwin-arm64, locale en-BE) [1,558ms]
    • Flutter version 3.32.0 on channel stable at /Users/cekrozl1/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision be698c48a6 (8 days ago), 2025-05-19 12:59:14 -0700
    • Engine revision 1881800949
    • Dart version 3.8.0
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc4) [3.6s]
    • Android SDK at /Users/cekrozl1/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0-rc4
    • ANDROID_HOME = /Users/cekrozl1/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/cekrozl1/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [2.9s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [16ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [15ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)

[✓] VS Code (version 1.100.2) [13ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (3 available) [7.9s]
    • Pixel 7 (mobile) • 29291FDH200097 • android-arm64  • Android 16 (API 36)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 137.0.7151.41
    ! Error: Browsing on the local area network for OneSpan iPhone 15. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Abby. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [450ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
…s tree

fixes https://github.com/flutter/flutter/issues/169499

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/rendering/object.dart [hunk 1]
```diff
@@ -4739,8 +4739,8 @@ class _SemanticsConfigurationProvider {
   ///
   /// This is typically use to recalculate certain properties when mutating
   /// [effective] since [effective] may contain stale data from previous update.
-  /// Examples are [SemanticsConfiguration.isBlockingUserActions] or
-  /// [SemanticsConfiguration.elevation]. Otherwise, use [effective] instead.
+  /// Examples are [SemanticsConfiguration.isBlockingUserActions] or. Otherwise,
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/object.dart]: Looks like this sentence got chopped up weirdly, should it be "An example is ..." and remove the "or"?

File: packages/flutter/lib/src/rendering/object.dart [hunk 2]
```diff
@@ -5328,16 +5327,35 @@ class _RenderObjectSemantics extends _SemanticsFragment with DiagnosticableTreeM
...
     }
+    for (final _RenderObjectSemantics explicitSiblingChild in siblingMergeGroups
+        .expand<_SemanticsFragment>((List<_SemanticsFragment> group) => group)
+        .whereType<_RenderObjectSemantics>()
+        .expand(
+          (_RenderObjectSemantics siblingChild) =>
+              siblingChild.shouldFormSemanticsNode
+                  ? <_RenderObjectSemantics>[siblingChild]
+                  : siblingChild._children,
+        )) {
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/object.dart:5300]: I asked @chunhtai offline about possible performance impact here, seems to be minimal as the existence of explicitSiblingChildren is rare.

**Review by justinmc — APPROVED** [review]
I took a deep dive into semantics to try to review this PR well, thanks @chunhtai for giving me a crash course. This makes sense that children like prefix/suffix of InputDecorator were dropped before and this includes them, but can you link the PR that caused this regression? Just for my own interest. Otherwise LGTM 👍

**Comment by chunhtai** [comment]
The previous pr was a big refactor that rewrote the entire semantics compilation https://github.com/flutter/flutter/pull/161195

before the refactor the explicit children under the sibling merge group are built and attached to the render object directly, which is still incorrect
here is a diagram explain what happened
image

**Comment by justinmc** [comment]
Thanks for the diagram and link!
