### PR TITLE
SelectableText keep alive only when it has selection

### LINKED ISSUE #91509: NestedScrollView + TabBar + SelectableText: Unexpected behaviour when scrolling
## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Tab bar example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  ScrollController _scrollController = ScrollController();

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length: 2,
        child: Scaffold(
            body: NestedScrollView(
                controller: _scrollController,
                headerSliverBuilder:
                    (BuildContext context, bool innerBoxIsScrolled) {
                  return [
                    SliverToBoxAdapter(
                      child: Container(
                        height: 200,
                        color: Colors.black12,
                      ),
                    ),
                    SliverToBoxAdapter(
                        child: Center(
                      child: SizedBox(
                          child: TabBar(
                        labelColor: Colors.black,
                        isScrollable: true,
                        tabs: [Tab(text: 'Tab1'), Tab(text: 'Tab2')],
                      )),
                    )),
                  ];
                },
                body: TabBarView(
                  children: [
                    ListView.builder(
                        itemCount: 1000,
                        itemBuilder: (context, index) => Container(
                              height: 50,
                              color: index % 2 == 0 ? Colors.red : Colors.white,
                            )),
                    ListView.builder(
                        itemCount: 2,
                        itemBuilder: (context, index) => Container(
                              child: SelectableText('Index=[$index].'),
                            ))
                  ],
                ))));
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }
}


```

**Expected results:**

Slivers should appear only when user is done with scrolling all the way up, however, when using SelectableText, scrolling up at any position (even at the 1000th element) of the TarBarView, the slivers show up.

The behaviour is inconsistent with when using Text instead of SelectableText.

I would expect the scrolling to work well like in this GIF:

Text

which is associated to below code (replacing SelectableText with Text makes it work as expected)

```dart

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Tab bar example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TestPage(),
    );
  }
}

class TestPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  ScrollController _scrollController = ScrollController();

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length: 2,
        child: Scaffold(
            body: NestedScrollView(
                controller: _scrollController,
                headerSliverBuilder:
                    (BuildContext context, bool innerBoxIsScrolled) {
                  return [
                    SliverToBoxAdapter(
                      child: Container(
                        height: 200,
                        color: Colors.black12,
                      ),
                    ),
                    SliverToBoxAdapter(
                        child: Center(
                      child: SizedBox(
                          child: TabBar(
                        labelColor: Colors.black,
                        isScrollable: true,
                        tabs: [Tab(text: 'Tab1'), Tab(text: 'Tab2')],
                      )),
                    )),
                  ];
                },
                body: TabBarView(
                  children: [
                    ListView.builder(
                        itemCount: 1000,
                        itemBuilder: (context, index) => Container(
                              height: 50,
                              color: index % 2 == 0 ? Colors.red : Colors.white,
                            )),
                    ListView.builder(
                        itemCount: 2,
                        itemBuilder: (context, index) => Container(
                              child: Text('Index=[$index].'),
                            ))
                  ],
                ))));
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }
}

```

**Actual results:**

The scrolling doesn't work well (when scrolling up from the middle of the TabBarView, it shows the slivers) as it can be observed in this GIF:

SelectedText

<details>
  <summary>Logs</summary>

```
[  +48 ms] executing: uname -m
[  +22 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +4 ms] executing: [/home/juancarlos/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +23 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[        ] executing: [/home/juancarlos/snap/flutter/common/flutter/] git tag --points-at
3595343e20a61ff16d14e8ecc25f364276bb1b8b
[ +149 ms] Exit code 0 from: git tag --points-at 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[   +4 ms] 2.5.2
[  +26 ms] executing: [/home/juancarlos/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/juancarlos/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +85 ms] executing: [/home/juancarlos/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +48 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +52 ms] executing: /home/juancarlos/Android/Sdk/platform-tools/adb devices -l
[  +23 ms] List of devices attached
           emulator-5554          device product:sdk_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:1
[   +3 ms] /home/juancarlos/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +28 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] Skipping pub get: version match.
[  +27 ms] Found plugin device_info at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.2/
[   +6 ms] Found plugin firebase_core at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.7.0/
[   +2 ms] Found plugin firebase_core_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/
[   +1 ms] Found plugin firebase_dynamic_links at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-2.0.10/
[   +1 ms] Found plugin firebase_messaging at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-10.0.8/
[   +1 ms] Found plugin firebase_messaging_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_web-2.0.6/
[   +2 ms] Found plugin flutter_local_notifications at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-6.1.1/
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.3
/
[   +1 ms] Found plugin flutter_sound at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sound-8.3.9/
[   +1 ms] Found plugin flutter_sound_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sound_web-8.3.9/
[   +3 ms] Found plugin fluttertoast at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/
[   +5 ms] Found plugin image_picker at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+2/
[   +1 ms] Found plugin image_picker_for_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/
[   +5 ms] Found plugin package_info_plus at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus-1.2.1/
[   +1 ms] Found plugin package_info_plus_macos at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus_macos-1.2.0/
[   +1 ms] Found plugin package_info_plus_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus_web-1.0.4/
[   +3 ms] Found plugin path_provider at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.5/
[        ] Found plugin path_provider_linux at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.0/
[   +1 ms] Found plugin path_provider_macos at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.2/
[   +1 ms] Found plugin path_provider_windows at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.3/
[   +1 ms] Found plugin permission_handler at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.2/
[   +4 ms] Found plugin share_plus at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus-2.2.0/
[   +1 ms] Found plugin share_plus_macos at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus_macos-2.0.2/
[   +1 ms] Found plugin share_plus_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus_web-2.0.4/
[   +1 ms] Found plugin shared_preferences at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.8/
[        ] Found plugin shared_preferences_linux at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.2/
[        ] Found plugin shared_preferences_macos at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.2/
[        ] Found plugin shared_preferences_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.2/
[        ] Found plugin shared_preferences_windows at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.2/
[   +4 ms] Found plugin url_launcher at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.12/
[        ] Found plugin url_launcher_linux at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.2/
[        ] Found plugin url_launcher_macos at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.2/
[   +1 ms] Found plugin url_launcher_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.4/
[        ] Found plugin url_launcher_windows at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.2/
[   +1 ms] Found plugin video_player at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-2.2.5/
[   +1 ms] Found plugin video_player_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_web-2.0.4/
[        ] Found plugin video_thumbnail at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_thumbnail-0.3.3/
[        ] Found plugin wakelock at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.6/
[        ] Found plugin wakelock_macos at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_macos-0.4.0/
[   +1 ms] Found plugin wakelock_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_web-0.4.0/
[  +60 ms] Found plugin device_info at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.2/
[   +2 ms] Found plugin firebase_core at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.7.0/
[        ] Found plugin firebase_core_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/
[        ] Found plugin firebase_dynamic_links at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-2.0.10/
[        ] Found plugin firebase_messaging at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-10.0.8/
[        ] Found plugin firebase_messaging_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_web-2.0.6/
[   +1 ms] Found plugin flutter_local_notifications at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-6.1.1/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.3
/
[        ] Found plugin flutter_sound at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sound-8.3.9/
[        ] Found plugin flutter_sound_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sound_web-8.3.9/
[   +1 ms] Found plugin fluttertoast at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-7.1.8/
[   +2 ms] Found plugin image_picker at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+2/
[        ] Found plugin image_picker_for_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/
[   +3 ms] Found plugin package_info_plus at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus-1.2.1/
[        ] Found plugin package_info_plus_macos at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus_macos-1.2.0/
[        ] Found plugin package_info_plus_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/package_info_plus_web-1.0.4/
[   +1 ms] Found plugin path_provider at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.5/
[        ] Found plugin path_provider_linux at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.0/
[        ] Found plugin path_provider_macos at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.2/
[        ] Found plugin path_provider_windows at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.3/
[        ] Found plugin permission_handler at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.2/
[   +2 ms] Found plugin share_plus at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus-2.2.0/
[   +1 ms] Found plugin share_plus_macos at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus_macos-2.0.2/
[        ] Found plugin share_plus_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/share_plus_web-2.0.4/
[   +1 ms] Found plugin shared_preferences at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.8/
[        ] Found plugin shared_preferences_linux at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.2/
[        ] Found plugin shared_preferences_macos at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.2/
[        ] Found plugin shared_preferences_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.2/
[        ] Found plugin shared_preferences_windows at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.2/
[   +3 ms] Found plugin url_launcher at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.12/
[        ] Found plugin url_launcher_linux at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.2/
[        ] Found plugin url_launcher_macos at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.2/
[        ] Found plugin url_launcher_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.4/
[        ] Found plugin url_launcher_windows at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.2/
[        ] Found plugin video_player at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-2.2.5/
[        ] Found plugin video_player_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_web-2.0.4/
[        ] Found plugin video_thumbnail at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/video_thumbnail-0.3.3/
[        ] Found plugin wakelock at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.6/
[        ] Found plugin wakelock_macos at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_macos-0.4.0/
[        ] Found plugin wakelock_web at
/home/juancarlos/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_web-0.4.0/
[  +12 ms] The plugin `video_thumbnail` uses a deprecated version of the Android embedding.
           To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the
Android V2
           embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated
APIs.
           If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
           https://flutter.dev/go/android-plugin-migration.
[   +1 ms] Generating
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginR
egistrant.java
[  +32 ms] ro.hardware = ranchu
[  +13 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[  +19 ms] Initializing file store
[   +7 ms] Skipping target: gen_localizations
[   +2 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[   +1 ms] complete
[   +3 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[   +4 ms] /home/juancarlos/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/juancarlos/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot
--sdk-root /home/juancarlos/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.BZDZUP/flutter_tool.OEUBCL/app.dill --packages
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[   +5 ms] executing: /home/juancarlos/Android/Sdk/build-tools/30.0.2/aapt dump xmltree
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +5 ms] Exit code 0 from: /home/juancarlos/Android/Sdk/build-tools/30.0.2/aapt dump xmltree
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.solon.app" (Raw: "com.solon.app")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x15
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=17)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=18)
                 A: android:name(0x01010003)="android.permission.RECORD_AUDIO" (Raw:
                 "android.permission.RECORD_AUDIO")
               E: uses-permission (line=19)
                 A: android:name(0x01010003)="android.permission.FOREGROUND_SERVICE" (Raw:
                 "android.permission.FOREGROUND_SERVICE")
               E: uses-permission (line=20)
                 A: android:name(0x01010003)="android.permission.WAKE_LOCK" (Raw: "android.permission.WAKE_LOCK")
               E: uses-permission (line=21)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw:
                 "android.permission.ACCESS_NETWORK_STATE")
               E: uses-permission (line=22)
                 A: android:name(0x01010003)="android.permission.RECEIVE_BOOT_COMPLETED" (Raw:
                 "android.permission.RECEIVE_BOOT_COMPLETED")
               E: uses-permission (line=23)
                 A: android:name(0x01010003)="android.permission.VIBRATE" (Raw: "android.permission.VIBRATE")
               E: uses-permission (line=24)
                 A: android:name(0x01010003)="android.permission.USE_FULL_SCREEN_INTENT" (Raw:
                 "android.permission.USE_FULL_SCREEN_INTENT")
               E: uses-permission (line=25)
                 A: android:name(0x01010003)="com.google.android.c2dm.permission.RECEIVE" (Raw:
                 "com.google.android.c2dm.permission.RECEIVE")
               E: uses-permission (line=26)
                 A: android:name(0x01010003)="android.permission.BLUETOOTH" (Raw: "android.permission.BLUETOOTH")
               E: uses-permission (line=27)
                 A: android:name(0x01010003)="android.permission.MODIFY_AUDIO_SETTINGS" (Raw:
                 "android.permission.MODIFY_AUDIO_SETTINGS")
               E: uses-permission (line=28)
                 A: android:name(0x01010003)="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE"
                 (Raw: "com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE")
               E: application (line=30)
                 A: android:label(0x01010001)="Solon" (Raw: "Solon")
                 A: android:icon(0x01010002)=@0x7f0b0000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw:
                 "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=36)
                   A: android:theme(0x01010000)=@0x7f0e00a2
                   A: android:name(0x01010003)="com.solon.app.MainActivity" (Raw: "com.solon.app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x2
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   A: android:usesCleartextTraffic(0x010104ec)=(type 0x12)0xffffffff
                   E: meta-data (line=51)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0e00a3
                   E: meta-data (line=61)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f06007a
                   E: intent-filter (line=65)
                     E: action (line=66)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=68)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                   E: intent-filter (line=70)
                     E: action (line=71)
                       A: android:name(0x01010003)="android.intent.action.VIEW" (Raw: "android.intent.action.VIEW")
                     E: category (line=73)
                       A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw:
                       "android.intent.category.DEFAULT")
                     E: category (line=74)
                       A: android:name(0x01010003)="android.intent.category.BROWSABLE" (Raw:
                       "android.intent.category.BROWSABLE")
                     E: data (line=76)
                       A: android:scheme(0x01010027)="https" (Raw: "https")
                       A: android:host(0x01010028)="www.soloninterests.com" (Raw: "www.soloninterests.com")
                   E: intent-filter (line=80)
                     E: action (line=81)
                       A: android:name(0x01010003)="FLUTTER_NOTIFICATION_CLICK" (Raw: "FLUTTER_NOTIFICATION_CLICK")
                     E: category (line=83)
                       A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw:
                       "android.intent.category.DEFAULT")
                 E: meta-data (line=90)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: service (line=94)
                   A: android:name(0x01010003)="com.google.firebase.components.ComponentDiscoveryService" (Raw:
                   "com.google.firebase.components.ComponentDiscoveryService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                   E: meta-data (line=98)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebasedynamiclinks.
                     FlutterFirebaseAppRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebasedynamiclinks.FlutterFirebaseAppRegistr
                     ar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=101)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebase.messaging.Fl
                     utterFirebaseAppRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebase.messaging.FlutterFirebaseAppRegistrar
                     ")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=104)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebase.core.Flutter
                     FirebaseCoreRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebase.core.FlutterFirebaseCoreRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=107)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.analytics.ktx.Fireba
                     seAnalyticsKtxRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.analytics.ktx.FirebaseAnalyticsKtxRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=110)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.ktx.FirebaseCommonKt
                     xRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.ktx.FirebaseCommonKtxRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=113)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.messaging.FirebaseMe
                     ssagingRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=116)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.datatransport.Transp
                     ortRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.datatransport.TransportRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=119)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.dynamiclinks.interna
                     l.FirebaseDynamicLinkRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.dynamiclinks.internal.FirebaseDynamicLinkRegi
                     strar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=122)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.analytics.connector.
                     internal.AnalyticsConnectorRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnect
                     orRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=125)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.installations.Fireba
                     seInstallationsRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar"
                     )
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                 E: service (line=129)
                   A:
                   android:name(0x01010003)="io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundS
                   ervice" (Raw: "io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService")
                   A: android:permission(0x01010006)="android.permission.BIND_JOB_SERVICE" (Raw:
                   "android.permission.BIND_JOB_SERVICE")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: service (line=133)
                   A: android:name(0x01010003)="io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingService"
                   (Raw: "io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   E: intent-filter (line=136)
                     E: action (line=137)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw:
                       "com.google.firebase.MESSAGING_EVENT")
                 E: receiver (line=141)
                   A:
                   android:name(0x01010003)="io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver"
                   (Raw: "io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver")
                   A: android:permission(0x01010006)="com.google.android.c2dm.permission.SEND" (Raw:
                   "com.google.android.c2dm.permission.SEND")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   E: intent-filter (line=145)
                     E: action (line=146)
                       A: android:name(0x01010003)="com.google.android.c2dm.intent.RECEIVE" (Raw:
                       "com.google.android.c2dm.intent.RECEIVE")
                 E: provider (line=150)
                   A:
                   android:name(0x01010003)="io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingInitProvide
                   r" (Raw: "io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingInitProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.solon.app.flutterfirebasemessaginginitprovider" (Raw:
                   "com.solon.app.flutterfirebasemessaginginitprovider")
                   A: android:initOrder(0x0101001a)=(type 0x10)0x63
                 E: provider (line=155)
                   A: android:name(0x01010003)="io.flutter.plugins.imagepicker.ImagePickerFileProvider" (Raw:
                   "io.flutter.plugins.imagepicker.ImagePickerFileProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.solon.app.flutter.image_provider" (Raw:
                   "com.solon.app.flutter.image_provider")
                   A: android:grantUriPermissions(0x0101001b)=(type 0x12)0xffffffff
                   E: meta-data (line=160)
                     A: android:name(0x01010003)="android.support.FILE_PROVIDER_PATHS" (Raw:
                     "android.support.FILE_PROVIDER_PATHS")
                     A: android:resource(0x01010025)=@0x7f100000
                 E: receiver (line=165)
                   A: android:name(0x01010003)="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver"
                   (Raw: "com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver")
                 E: receiver (line=166)
                   A:
                   android:name(0x01010003)="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver
                   " (Raw: "com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver")
                   E: intent-filter (line=167)
                     E: action (line=168)
                       A: android:name(0x01010003)="android.intent.action.BOOT_COMPLETED" (Raw:
                       "android.intent.action.BOOT_COMPLETED")
                     E: action (line=169)
                       A: android:name(0x01010003)="android.intent.action.MY_PACKAGE_REPLACED" (Raw:
                       "android.intent.action.MY_PACKAGE_REPLACED")
                     E: action (line=170)
                       A: android:name(0x01010003)="android.intent.action.QUICKBOOT_POWERON" (Raw:
                       "android.intent.action.QUICKBOOT_POWERON")
                     E: action (line=171)
                       A: android:name(0x01010003)="com.htc.intent.action.QUICKBOOT_POWERON" (Raw:
                       "com.htc.intent.action.QUICKBOOT_POWERON")
                 E: provider (line=175)
                   A: android:name(0x01010003)="dev.fluttercommunity.plus.share.ShareFileProvider" (Raw:
                   "dev.fluttercommunity.plus.share.ShareFileProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.solon.app.flutter.share_provider" (Raw:
                   "com.solon.app.flutter.share_provider")
                   A: android:grantUriPermissions(0x0101001b)=(type 0x12)0xffffffff
                   E: meta-data (line=180)
                     A: android:name(0x01010003)="android.support.FILE_PROVIDER_PATHS" (Raw:
                     "android.support.FILE_PROVIDER_PATHS")
                     A: android:resource(0x01010025)=@0x7f100001
                 E: activity (line=185)
                   A: android:theme(0x01010000)=@0x01030007
                   A: android:name(0x01010003)="io.flutter.plugins.urllauncher.WebViewActivity" (Raw:
                   "io.flutter.plugins.urllauncher.WebViewActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: receiver (line=190)
                   A: android:name(0x01010003)="com.google.firebase.iid.FirebaseInstanceIdReceiver" (Raw:
                   "com.google.firebase.iid.FirebaseInstanceIdReceiver")
                   A: android:permission(0x01010006)="com.google.android.c2dm.permission.SEND" (Raw:
                   "com.google.android.c2dm.permission.SEND")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   E: intent-filter (line=194)
                     E: action (line=195)
                       A: android:name(0x01010003)="com.google.android.c2dm.intent.RECEIVE" (Raw:
                       "com.google.android.c2dm.intent.RECEIVE")
                 E: service (line=202)
                   A: android:name(0x01010003)="com.google.firebase.messaging.FirebaseMessagingService" (Raw:
                   "com.google.firebase.messaging.FirebaseMessagingService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                   E: intent-filter (line=206)
                     A: android:priority(0x0101001c)=(type 0x10)0xfffffe0c
                     E: action (line=207)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw:
                       "com.google.firebase.MESSAGING_EVENT")
                 E: service (line=210)
                   A:
                   android:name(0x01010003)="com.google.android.datatransport.runtime.backends.TransportBackendDiscove
                   ry" (Raw: "com.google.android.datatransport.runtime.backends.TransportBackendDiscovery")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   E: meta-data (line=213)
                     A: android:name(0x01010003)="backend:com.google.android.datatransport.cct.CctBackendFactory"
                     (Raw: "backend:com.google.android.datatransport.cct.CctBackendFactory")
                     A: android:value(0x01010024)="cct" (Raw: "cct")
                 E: provider (line=218)
                   A: android:name(0x01010003)="com.google.firebase.provider.FirebaseInitProvider" (Raw:
                   "com.google.firebase.provider.FirebaseInitProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.solon.app.firebaseinitprovider" (Raw:
                   "com.solon.app.firebaseinitprovider")
                   A: android:initOrder(0x0101001a)=(type 0x10)0x64
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                 E: receiver (line=225)
                   A: android:name(0x01010003)="androidx.media.session.MediaButtonReceiver" (Raw:
                   "androidx.media.session.MediaButtonReceiver")
                   E: intent-filter (line=226)
                     E: action (line=227)
                       A: android:name(0x01010003)="android.intent.action.MEDIA_BUTTON" (Raw:
                       "android.intent.action.MEDIA_BUTTON")
                     E: action (line=228)
                       A: android:name(0x01010003)="android.media.AUDIO_BECOMING_NOISY" (Raw:
                       "android.media.AUDIO_BECOMING_NOISY")
                 E: service (line=232)
                   A: android:name(0x01010003)="com.dooboolab.TauEngine.FlautoBackgroundAudioService" (Raw:
                   "com.dooboolab.TauEngine.FlautoBackgroundAudioService")
                   E: intent-filter (line=233)
                     E: action (line=234)
                       A: android:name(0x01010003)="android.intent.action.MEDIA_BUTTON" (Raw:
                       "android.intent.action.MEDIA_BUTTON")
                     E: action (line=235)
                       A: android:name(0x01010003)="android.media.AUDIO_BECOMING_NOISY" (Raw:
                       "android.media.AUDIO_BECOMING_NOISY")
                     E: action (line=236)
                       A: android:name(0x01010003)="android.media.browse.FlautoMediaBrowserService" (Raw:
                       "android.media.browse.FlautoMediaBrowserService")
                 E: activity (line=240)
                   A: android:theme(0x01010000)=@0x01030010
                   A: android:name(0x01010003)="com.google.android.gms.common.api.GoogleApiActivity" (Raw:
                   "com.google.android.gms.common.api.GoogleApiActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: receiver (line=245)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementReceiver" (Raw:
                   "com.google.android.gms.measurement.AppMeasurementReceiver")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: service (line=251)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementService" (Raw:
                   "com.google.android.gms.measurement.AppMeasurementService")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: service (line=255)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementJobService" (Raw:
                   "com.google.android.gms.measurement.AppMeasurementJobService")
                   A: android:permission(0x01010006)="android.permission.BIND_JOB_SERVICE" (Raw:
                   "android.permission.BIND_JOB_SERVICE")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: meta-data (line=261)
                   A: android:name(0x01010003)="com.google.android.gms.version" (Raw:
                   "com.google.android.gms.version")
                   A: android:value(0x01010024)=@0x7f080004
                 E: service (line=265)
                   A:
                   android:name(0x01010003)="com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfo
                   SchedulerService" (Raw:
                   "com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService")
                   A: android:permission(0x01010006)="android.permission.BIND_JOB_SERVICE" (Raw:
                   "android.permission.BIND_JOB_SERVICE")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: receiver (line=271)
                   A:
                   android:name(0x01010003)="com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmMa
                   nagerSchedulerBroadcastReceiver" (Raw:
                   "com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastRe
                   ceiver")
                   A: android:exported(0x01010010)=(type 0x12)0x0
[   +9 ms] executing: /home/juancarlos/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[   +5 ms] <- compile package:solon_app/main.dart
[  +18 ms] --------- beginning of main
           10-08 20:36:35.383 E/wifi_forwarder(  525): RemoteConnection failed to initialize: RemoteConnection failed
           to open pipe
[   +9 ms] executing: /home/juancarlos/Android/Sdk/platform-tools/adb version
[   +5 ms] Android Debug Bridge version 1.0.41
           Version 31.0.3-7562133
           Installed as /home/juancarlos/Android/Sdk/platform-tools/adb
[   +1 ms] executing: /home/juancarlos/Android/Sdk/platform-tools/adb start-server
[   +9 ms] Building APK
[  +11 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] Using gradle from /home/juancarlos/AndroidStudioProjects/solon_flutter_app/android/gradlew.
[  +11 ms] executing: /home/juancarlos/android-studio/jre/bin/java -version
[ +110 ms] Exit code 0 from: /home/juancarlos/android-studio/jre/bin/java -version
[        ] openjdk version "11.0.11" 2021-04-20
           OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
           OpenJDK 64-Bit Server VM (build 11.0.11+0-b60-7590822, mixed mode)
[   +1 ms] executing: [/home/juancarlos/AndroidStudioProjects/solon_flutter_app/android/]
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/android/gradlew -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=/home/juancarlos/AndroidStudioProjects/solon_flutter_app/lib/main.dart
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true
-Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +971 ms] > Configure project :app
[        ] WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
[        ] It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to
disable R8.
[+3494 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +49 ms] executing: uname -m
[        ] [  +24 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +4 ms] executing: [/home/juancarlos/snap/flutter/common/flutter/] git -c log.showSignature=false log -n
1 --pretty=format:%H
[        ] [   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[        ] [        ] executing: [/home/juancarlos/snap/flutter/common/flutter/] git tag --points-at
3595343e20a61ff16d14e8ecc25f364276bb1b8b
[        ] [  +11 ms] Exit code 0 from: git tag --points-at 3595343e20a61ff16d14e8ecc25f364276bb1b8b
[        ] [        ] 2.5.2
[        ] [   +6 ms] executing: [/home/juancarlos/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/juancarlos/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +41 ms] executing: [/home/juancarlos/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +35 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +75 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +27 ms] Initializing file store
[        ] [  +13 ms] Done initializing file store
[        ] [  +35 ms] Skipping target: gen_localizations
[        ] [  +12 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +687 ms] kernel_snapshot: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have
updated contents: /home/juancarlos/AndroidStudioProjects/solon_flutter_app/lib/main.dart}
[        ] [  +20 ms] /home/juancarlos/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/juancarlos/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot
--sdk-root /home/juancarlos/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --no-link-platform --packages
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/.dart_tool/package_config.json --output-dill
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/.dart_tool/flutter_build/2bc81fda306c76acf9b57c8bd74dfd80/app
.dill --depfile
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/.dart_tool/flutter_build/2bc81fda306c76acf9b57c8bd74dfd80/ker
nel_snapshot.d package:solon_app/main.dart
[+6593 ms] [+7240 ms] kernel_snapshot: Complete
[ +199 ms] [ +214 ms] invalidated build due to missing files:
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/DOES_NOT_EXIST_RERUN_FOR_WILDCARD300227152
[ +500 ms] [ +473 ms] debug_android_application: Starting due to {InvalidatedReasonKind.inputChanged: The following
inputs have updated contents:
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/.dart_tool/flutter_build/2bc81fda306c76acf9b57c8bd74dfd80/app
.dill, InvalidatedReasonKind.inputMissing: The following inputs were missing:
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/DOES_NOT_EXIST_RERUN_FOR_WILDCARD300227152}
[  +99 ms] [ +195 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for
more information see #56466.
[ +100 ms] [  +34 ms] debug_android_application: Complete
[ +199 ms] [ +247 ms] Persisting file store
[        ] [   +9 ms] Done persisting file store
[        ] [   +4 ms] build succeeded.
[  +99 ms] [   +7 ms] "flutter assemble" took 9,316ms.
[        ] [   +2 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[  +99 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :device_info:preBuild UP-TO-DATE
[        ] > Task :device_info:preDebugBuild UP-TO-DATE
[        ] > Task :device_info:compileDebugAidl NO-SOURCE
[        ] > Task :firebase_core:preBuild UP-TO-DATE
[        ] > Task :firebase_core:preDebugBuild UP-TO-DATE
[        ] > Task :firebase_core:compileDebugAidl NO-SOURCE
[        ] > Task :firebase_dynamic_links:preBuild UP-TO-DATE
[        ] > Task :firebase_dynamic_links:preDebugBuild UP-TO-DATE
[        ] > Task :firebase_dynamic_links:compileDebugAidl NO-SOURCE
[        ] > Task :firebase_messaging:preBuild UP-TO-DATE
[        ] > Task :firebase_messaging:preDebugBuild UP-TO-DATE
[        ] > Task :firebase_messaging:compileDebugAidl NO-SOURCE
[        ] > Task :flutter_local_notifications:preBuild UP-TO-DATE
[        ] > Task :flutter_local_notifications:preDebugBuild UP-TO-DATE
[        ] > Task :flutter_local_notifications:compileDebugAidl NO-SOURCE
[        ] > Task :flutter_plugin_android_lifecycle:preBuild UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:preDebugBuild UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:compileDebugAidl NO-SOURCE
[        ] > Task :flutter_sound:preBuild UP-TO-DATE
[        ] > Task :flutter_sound:preDebugBuild UP-TO-DATE
[        ] > Task :path_provider:preBuild UP-TO-DATE
[        ] > Task :path_provider:preDebugBuild UP-TO-DATE
[        ] > Task :path_provider:compileDebugAidl NO-SOURCE
[        ] > Task :flutter_sound:compileDebugAidl NO-SOURCE
[        ] > Task :fluttertoast:preBuild UP-TO-DATE
[        ] > Task :fluttertoast:preDebugBuild UP-TO-DATE
[        ] > Task :fluttertoast:compileDebugAidl NO-SOURCE
[        ] > Task :image_picker:preBuild UP-TO-DATE
[        ] > Task :image_picker:preDebugBuild UP-TO-DATE
[        ] > Task :image_picker:compileDebugAidl NO-SOURCE
[        ] > Task :package_info_plus:preBuild UP-TO-DATE
[        ] > Task :package_info_plus:preDebugBuild UP-TO-DATE
[        ] > Task :package_info_plus:compileDebugAidl NO-SOURCE
[        ] > Task :permission_handler:preBuild UP-TO-DATE
[        ] > Task :permission_handler:preDebugBuild UP-TO-DATE
[        ] > Task :permission_handler:compileDebugAidl NO-SOURCE
[        ] > Task :share_plus:preBuild UP-TO-DATE
[        ] > Task :share_plus:preDebugBuild UP-TO-DATE
[        ] > Task :share_plus:compileDebugAidl NO-SOURCE
[        ] > Task :shared_preferences:preBuild UP-TO-DATE
[        ] > Task :shared_preferences:preDebugBuild UP-TO-DATE
[        ] > Task :shared_preferences:compileDebugAidl NO-SOURCE
[        ] > Task :url_launcher:preBuild UP-TO-DATE
[        ] > Task :url_launcher:preDebugBuild UP-TO-DATE
[        ] > Task :url_launcher:compileDebugAidl NO-SOURCE
[        ] > Task :video_player:preBuild UP-TO-DATE
[        ] > Task :video_player:preDebugBuild UP-TO-DATE
[        ] > Task :video_player:compileDebugAidl NO-SOURCE
[        ] > Task :video_thumbnail:preBuild UP-TO-DATE
[        ] > Task :video_thumbnail:preDebugBuild UP-TO-DATE
[        ] > Task :video_thumbnail:compileDebugAidl NO-SOURCE
[        ] > Task :wakelock:preBuild UP-TO-DATE
[        ] > Task :wakelock:preDebugBuild UP-TO-DATE
[        ] > Task :wakelock:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :device_info:packageDebugRenderscript NO-SOURCE
[        ] > Task :firebase_core:packageDebugRenderscript NO-SOURCE
[        ] > Task :firebase_dynamic_links:packageDebugRenderscript NO-SOURCE
[        ] > Task :firebase_messaging:packageDebugRenderscript NO-SOURCE
[        ] > Task :flutter_local_notifications:packageDebugRenderscript NO-SOURCE
[        ] > Task :flutter_plugin_android_lifecycle:packageDebugRenderscript NO-SOURCE
[        ] > Task :flutter_sound:packageDebugRenderscript NO-SOURCE
[        ] > Task :fluttertoast:packageDebugRenderscript NO-SOURCE
[        ] > Task :image_picker:packageDebugRenderscript NO-SOURCE
[        ] > Task :package_info_plus:packageDebugRenderscript NO-SOURCE
[        ] > Task :path_provider:packageDebugRenderscript NO-SOURCE
[        ] > Task :permission_handler:packageDebugRenderscript NO-SOURCE
[        ] > Task :share_plus:packageDebugRenderscript NO-SOURCE
[        ] > Task :shared_preferences:packageDebugRenderscript NO-SOURCE
[        ] > Task :url_launcher:packageDebugRenderscript NO-SOURCE
[        ] > Task :video_player:packageDebugRenderscript NO-SOURCE
[        ] > Task :video_thumbnail:packageDebugRenderscript NO-SOURCE
[        ] > Task :wakelock:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :device_info:mergeDebugShaders UP-TO-DATE
[        ] > Task :device_info:compileDebugShaders UP-TO-DATE
[        ] > Task :device_info:generateDebugAssets UP-TO-DATE
[        ] > Task :device_info:packageDebugAssets UP-TO-DATE
[        ] > Task :firebase_core:mergeDebugShaders UP-TO-DATE
[        ] > Task :firebase_core:compileDebugShaders UP-TO-DATE
[        ] > Task :firebase_core:generateDebugAssets UP-TO-DATE
[        ] > Task :firebase_core:packageDebugAssets UP-TO-DATE
[        ] > Task :firebase_dynamic_links:mergeDebugShaders UP-TO-DATE
[        ] > Task :firebase_dynamic_links:compileDebugShaders UP-TO-DATE
[        ] > Task :firebase_dynamic_links:generateDebugAssets UP-TO-DATE
[        ] > Task :firebase_dynamic_links:packageDebugAssets UP-TO-DATE
[        ] > Task :firebase_messaging:mergeDebugShaders UP-TO-DATE
[        ] > Task :firebase_messaging:compileDebugShaders UP-TO-DATE
[        ] > Task :firebase_messaging:generateDebugAssets UP-TO-DATE
[        ] > Task :firebase_messaging:packageDebugAssets UP-TO-DATE
[        ] > Task :flutter_local_notifications:mergeDebugShaders UP-TO-DATE
[        ] > Task :flutter_local_notifications:compileDebugShaders UP-TO-DATE
[        ] > Task :flutter_local_notifications:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_local_notifications:packageDebugAssets UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:mergeDebugShaders UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:compileDebugShaders UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:packageDebugAssets UP-TO-DATE
[        ] > Task :flutter_sound:mergeDebugShaders UP-TO-DATE
[        ] > Task :flutter_sound:compileDebugShaders UP-TO-DATE
[        ] > Task :flutter_sound:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_sound:packageDebugAssets UP-TO-DATE
[        ] > Task :fluttertoast:mergeDebugShaders UP-TO-DATE
[        ] > Task :fluttertoast:compileDebugShaders UP-TO-DATE
[        ] > Task :fluttertoast:generateDebugAssets UP-TO-DATE
[        ] > Task :fluttertoast:packageDebugAssets UP-TO-DATE
[        ] > Task :image_picker:mergeDebugShaders UP-TO-DATE
[        ] > Task :image_picker:compileDebugShaders UP-TO-DATE
[        ] > Task :image_picker:generateDebugAssets UP-TO-DATE
[        ] > Task :image_picker:packageDebugAssets UP-TO-DATE
[        ] > Task :package_info_plus:mergeDebugShaders UP-TO-DATE
[        ] > Task :package_info_plus:compileDebugShaders UP-TO-DATE
[        ] > Task :package_info_plus:generateDebugAssets UP-TO-DATE
[        ] > Task :package_info_plus:packageDebugAssets UP-TO-DATE
[        ] > Task :path_provider:mergeDebugShaders UP-TO-DATE
[        ] > Task :path_provider:compileDebugShaders UP-TO-DATE
[        ] > Task :path_provider:generateDebugAssets UP-TO-DATE
[        ] > Task :path_provider:packageDebugAssets UP-TO-DATE
[        ] > Task :permission_handler:mergeDebugShaders UP-TO-DATE
[        ] > Task :permission_handler:compileDebugShaders UP-TO-DATE
[        ] > Task :permission_handler:generateDebugAssets UP-TO-DATE
[        ] > Task :permission_handler:packageDebugAssets UP-TO-DATE
[        ] > Task :share_plus:mergeDebugShaders UP-TO-DATE
[        ] > Task :share_plus:compileDebugShaders UP-TO-DATE
[        ] > Task :share_plus:generateDebugAssets UP-TO-DATE
[        ] > Task :share_plus:packageDebugAssets UP-TO-DATE
[        ] > Task :shared_preferences:mergeDebugShaders UP-TO-DATE
[        ] > Task :shared_preferences:compileDebugShaders UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugAssets UP-TO-DATE
[        ] > Task :shared_preferences:packageDebugAssets UP-TO-DATE
[        ] > Task :url_launcher:mergeDebugShaders UP-TO-DATE
[        ] > Task :url_launcher:compileDebugShaders UP-TO-DATE
[        ] > Task :url_launcher:generateDebugAssets UP-TO-DATE
[        ] > Task :url_launcher:packageDebugAssets UP-TO-DATE
[        ] > Task :video_player:mergeDebugShaders UP-TO-DATE
[        ] > Task :video_player:compileDebugShaders UP-TO-DATE
[        ] > Task :video_player:generateDebugAssets UP-TO-DATE
[        ] > Task :video_player:packageDebugAssets UP-TO-DATE
[        ] > Task :video_thumbnail:mergeDebugShaders UP-TO-DATE
[        ] > Task :video_thumbnail:compileDebugShaders UP-TO-DATE
[        ] > Task :video_thumbnail:generateDebugAssets UP-TO-DATE
[        ] > Task :video_thumbnail:packageDebugAssets UP-TO-DATE
[        ] > Task :wakelock:mergeDebugShaders UP-TO-DATE
[        ] > Task :wakelock:compileDebugShaders UP-TO-DATE
[        ] > Task :wakelock:generateDebugAssets UP-TO-DATE
[        ] > Task :wakelock:packageDebugAssets UP-TO-DATE
[  +87 ms] > Task :app:mergeDebugAssets
[  +99 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:processDebugGoogleServices UP-TO-DATE
[        ] > Task :device_info:compileDebugRenderscript NO-SOURCE
[        ] > Task :device_info:generateDebugResValues UP-TO-DATE
[        ] > Task :device_info:generateDebugResources UP-TO-DATE
[        ] > Task :device_info:packageDebugResources UP-TO-DATE
[        ] > Task :firebase_core:compileDebugRenderscript NO-SOURCE
[        ] > Task :firebase_core:generateDebugResValues UP-TO-DATE
[        ] > Task :firebase_core:generateDebugResources UP-TO-DATE
[        ] > Task :firebase_core:packageDebugResources UP-TO-DATE
[        ] > Task :firebase_dynamic_links:compileDebugRenderscript NO-SOURCE
[        ] > Task :firebase_dynamic_links:generateDebugResValues UP-TO-DATE
[        ] > Task :firebase_dynamic_links:generateDebugResources UP-TO-DATE
[  +98 ms] > Task :firebase_dynamic_links:packageDebugResources UP-TO-DATE
[        ] > Task :firebase_messaging:compileDebugRenderscript NO-SOURCE
[        ] > Task :firebase_messaging:generateDebugResValues UP-TO-DATE
[        ] > Task :firebase_messaging:generateDebugResources UP-TO-DATE
[        ] > Task :firebase_messaging:packageDebugResources UP-TO-DATE
[        ] > Task :flutter_local_notifications:compileDebugRenderscript NO-SOURCE
[        ] > Task :flutter_local_notifications:generateDebugResValues UP-TO-DATE
[        ] > Task :flutter_local_notifications:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_local_notifications:packageDebugResources UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:compileDebugRenderscript NO-SOURCE
[        ] > Task :flutter_plugin_android_lifecycle:generateDebugResValues UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:packageDebugResources UP-TO-DATE
[        ] > Task :flutter_sound:compileDebugRenderscript NO-SOURCE
[        ] > Task :flutter_sound:generateDebugResValues UP-TO-DATE
[        ] > Task :flutter_sound:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_sound:packageDebugResources UP-TO-DATE
[        ] > Task :fluttertoast:compileDebugRenderscript NO-SOURCE
[        ] > Task :fluttertoast:generateDebugResValues UP-TO-DATE
[        ] > Task :fluttertoast:generateDebugResources UP-TO-DATE
[        ] > Task :fluttertoast:packageDebugResources UP-TO-DATE
[        ] > Task :image_picker:compileDebugRenderscript NO-SOURCE
[        ] > Task :image_picker:generateDebugResValues UP-TO-DATE
[        ] > Task :image_picker:generateDebugResources UP-TO-DATE
[        ] > Task :image_picker:packageDebugResources UP-TO-DATE
[        ] > Task :package_info_plus:compileDebugRenderscript NO-SOURCE
[        ] > Task :package_info_plus:generateDebugResValues UP-TO-DATE
[        ] > Task :package_info_plus:generateDebugResources UP-TO-DATE
[        ] > Task :package_info_plus:packageDebugResources UP-TO-DATE
[        ] > Task :path_provider:compileDebugRenderscript NO-SOURCE
[        ] > Task :path_provider:generateDebugResValues UP-TO-DATE
[        ] > Task :path_provider:generateDebugResources UP-TO-DATE
[        ] > Task :path_provider:packageDebugResources UP-TO-DATE
[        ] > Task :permission_handler:compileDebugRenderscript NO-SOURCE
[        ] > Task :permission_handler:generateDebugResValues UP-TO-DATE
[        ] > Task :permission_handler:generateDebugResources UP-TO-DATE
[        ] > Task :permission_handler:packageDebugResources UP-TO-DATE
[        ] > Task :share_plus:compileDebugRenderscript NO-SOURCE
[        ] > Task :share_plus:generateDebugResValues UP-TO-DATE
[        ] > Task :share_plus:generateDebugResources UP-TO-DATE
[        ] > Task :share_plus:packageDebugResources UP-TO-DATE
[        ] > Task :shared_preferences:compileDebugRenderscript NO-SOURCE
[        ] > Task :shared_preferences:generateDebugResValues UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugResources UP-TO-DATE
[        ] > Task :shared_preferences:packageDebugResources UP-TO-DATE
[        ] > Task :url_launcher:compileDebugRenderscript NO-SOURCE
[        ] > Task :url_launcher:generateDebugResValues UP-TO-DATE
[        ] > Task :url_launcher:generateDebugResources UP-TO-DATE
[        ] > Task :url_launcher:packageDebugResources UP-TO-DATE
[        ] > Task :video_player:compileDebugRenderscript NO-SOURCE
[        ] > Task :video_player:generateDebugResValues UP-TO-DATE
[        ] > Task :video_player:generateDebugResources UP-TO-DATE
[        ] > Task :video_player:packageDebugResources UP-TO-DATE
[        ] > Task :video_thumbnail:compileDebugRenderscript NO-SOURCE
[        ] > Task :video_thumbnail:generateDebugResValues UP-TO-DATE
[        ] > Task :video_thumbnail:generateDebugResources UP-TO-DATE
[        ] > Task :video_thumbnail:packageDebugResources UP-TO-DATE
[        ] > Task :wakelock:compileDebugRenderscript NO-SOURCE
[        ] > Task :wakelock:generateDebugResValues UP-TO-DATE
[        ] > Task :wakelock:generateDebugResources UP-TO-DATE
[        ] > Task :wakelock:packageDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :device_info:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :device_info:processDebugManifest UP-TO-DATE
[        ] > Task :firebase_core:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :firebase_core:processDebugManifest UP-TO-DATE
[        ] > Task :firebase_dynamic_links:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :firebase_dynamic_links:processDebugManifest UP-TO-DATE
[        ] > Task :firebase_messaging:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :firebase_messaging:processDebugManifest UP-TO-DATE
[        ] > Task :flutter_local_notifications:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :flutter_local_notifications:processDebugManifest UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:processDebugManifest UP-TO-DATE
[        ] > Task :flutter_sound:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :flutter_sound:processDebugManifest UP-TO-DATE
[        ] > Task :fluttertoast:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :fluttertoast:processDebugManifest UP-TO-DATE
[        ] > Task :image_picker:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :image_picker:processDebugManifest UP-TO-DATE
[        ] > Task :package_info_plus:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :package_info_plus:processDebugManifest UP-TO-DATE
[        ] > Task :path_provider:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :path_provider:processDebugManifest UP-TO-DATE
[        ] > Task :permission_handler:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :permission_handler:processDebugManifest UP-TO-DATE
[        ] > Task :share_plus:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :share_plus:processDebugManifest UP-TO-DATE
[        ] > Task :shared_preferences:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :shared_preferences:processDebugManifest UP-TO-DATE
[        ] > Task :url_launcher:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :url_launcher:processDebugManifest UP-TO-DATE
[        ] > Task :video_player:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :video_player:processDebugManifest UP-TO-DATE
[        ] > Task :video_thumbnail:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :video_thumbnail:processDebugManifest UP-TO-DATE
[        ] > Task :wakelock:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :wakelock:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :device_info:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :device_info:parseDebugLocalResources UP-TO-DATE
[        ] > Task :device_info:generateDebugRFile UP-TO-DATE
[        ] > Task :firebase_core:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :firebase_core:parseDebugLocalResources UP-TO-DATE
[  +91 ms] > Task :firebase_core:generateDebugRFile UP-TO-DATE
[        ] > Task :firebase_dynamic_links:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :firebase_dynamic_links:parseDebugLocalResources UP-TO-DATE
[        ] > Task :firebase_dynamic_links:generateDebugRFile UP-TO-DATE
[        ] > Task :firebase_messaging:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :firebase_messaging:parseDebugLocalResources UP-TO-DATE
[        ] > Task :firebase_messaging:generateDebugRFile UP-TO-DATE
[        ] > Task :flutter_local_notifications:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :flutter_local_notifications:parseDebugLocalResources UP-TO-DATE
[        ] > Task :flutter_local_notifications:generateDebugRFile UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:parseDebugLocalResources UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:generateDebugRFile UP-TO-DATE
[        ] > Task :flutter_sound:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :flutter_sound:parseDebugLocalResources UP-TO-DATE
[        ] > Task :path_provider:parseDebugLocalResources UP-TO-DATE
[        ] > Task :path_provider:generateDebugRFile UP-TO-DATE
[        ] > Task :flutter_sound:generateDebugRFile UP-TO-DATE
[        ] > Task :fluttertoast:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :fluttertoast:parseDebugLocalResources UP-TO-DATE
[        ] > Task :fluttertoast:generateDebugRFile UP-TO-DATE
[        ] > Task :image_picker:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :image_picker:parseDebugLocalResources UP-TO-DATE
[        ] > Task :image_picker:generateDebugRFile UP-TO-DATE
[        ] > Task :package_info_plus:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :package_info_plus:parseDebugLocalResources UP-TO-DATE
[        ] > Task :package_info_plus:generateDebugRFile UP-TO-DATE
[        ] > Task :path_provider:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :permission_handler:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :permission_handler:parseDebugLocalResources UP-TO-DATE
[        ] > Task :permission_handler:generateDebugRFile UP-TO-DATE
[        ] > Task :share_plus:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :share_plus:parseDebugLocalResources UP-TO-DATE
[        ] > Task :share_plus:generateDebugRFile UP-TO-DATE
[        ] > Task :shared_preferences:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :shared_preferences:parseDebugLocalResources UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugRFile UP-TO-DATE
[        ] > Task :url_launcher:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :url_launcher:parseDebugLocalResources UP-TO-DATE
[        ] > Task :url_launcher:generateDebugRFile UP-TO-DATE
[        ] > Task :video_player:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :video_player:parseDebugLocalResources UP-TO-DATE
[        ] > Task :video_player:generateDebugRFile UP-TO-DATE
[        ] > Task :video_thumbnail:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :video_thumbnail:parseDebugLocalResources UP-TO-DATE
[        ] > Task :video_thumbnail:generateDebugRFile UP-TO-DATE
[        ] > Task :wakelock:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :wakelock:parseDebugLocalResources UP-TO-DATE
[        ] > Task :wakelock:generateDebugRFile UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :device_info:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :device_info:javaPreCompileDebug UP-TO-DATE
[        ] > Task :device_info:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :device_info:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :firebase_core:generateDebugBuildConfig UP-TO-DATE
[  +95 ms] > Task :firebase_core:javaPreCompileDebug UP-TO-DATE
[        ] > Task :firebase_core:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :firebase_core:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :firebase_dynamic_links:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :firebase_dynamic_links:javaPreCompileDebug UP-TO-DATE
[        ] > Task :firebase_dynamic_links:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :firebase_dynamic_links:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :firebase_messaging:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :firebase_messaging:javaPreCompileDebug UP-TO-DATE
[        ] > Task :firebase_messaging:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :firebase_messaging:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :flutter_local_notifications:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :flutter_local_notifications:javaPreCompileDebug UP-TO-DATE
[        ] > Task :flutter_local_notifications:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :flutter_local_notifications:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:javaPreCompileDebug UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :flutter_sound:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :path_provider:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :path_provider:javaPreCompileDebug UP-TO-DATE
[        ] > Task :path_provider:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :path_provider:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :flutter_sound:javaPreCompileDebug UP-TO-DATE
[        ] > Task :flutter_sound:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :flutter_sound:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :fluttertoast:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :fluttertoast:compileDebugKotlin UP-TO-DATE
[        ] > Task :fluttertoast:javaPreCompileDebug UP-TO-DATE
[        ] > Task :fluttertoast:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :fluttertoast:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :image_picker:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :image_picker:javaPreCompileDebug UP-TO-DATE
[        ] > Task :image_picker:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :image_picker:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :package_info_plus:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :package_info_plus:javaPreCompileDebug UP-TO-DATE
[        ] > Task :package_info_plus:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :package_info_plus:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :permission_handler:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :permission_handler:javaPreCompileDebug UP-TO-DATE
[        ] > Task :permission_handler:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :permission_handler:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :share_plus:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :share_plus:javaPreCompileDebug UP-TO-DATE
[        ] > Task :share_plus:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :share_plus:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :shared_preferences:javaPreCompileDebug UP-TO-DATE
[        ] > Task :shared_preferences:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :shared_preferences:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :url_launcher:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :url_launcher:javaPreCompileDebug UP-TO-DATE
[        ] > Task :url_launcher:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :url_launcher:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :video_player:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :video_player:javaPreCompileDebug UP-TO-DATE
[        ] > Task :video_player:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :video_player:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :video_thumbnail:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :video_thumbnail:javaPreCompileDebug UP-TO-DATE
[        ] > Task :video_thumbnail:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :video_thumbnail:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :wakelock:generateDebugBuildConfig UP-TO-DATE
[  +95 ms] > Task :wakelock:compileDebugKotlin UP-TO-DATE
[        ] > Task :wakelock:javaPreCompileDebug UP-TO-DATE
[        ] > Task :wakelock:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :wakelock:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :device_info:processDebugJavaRes NO-SOURCE
[        ] > Task :device_info:bundleLibResDebug UP-TO-DATE
[        ] > Task :firebase_core:processDebugJavaRes NO-SOURCE
[        ] > Task :firebase_core:bundleLibResDebug UP-TO-DATE
[        ] > Task :firebase_dynamic_links:processDebugJavaRes NO-SOURCE
[        ] > Task :firebase_dynamic_links:bundleLibResDebug UP-TO-DATE
[        ] > Task :firebase_messaging:processDebugJavaRes NO-SOURCE
[        ] > Task :firebase_messaging:bundleLibResDebug UP-TO-DATE
[        ] > Task :flutter_local_notifications:processDebugJavaRes NO-SOURCE
[        ] > Task :flutter_local_notifications:bundleLibResDebug UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:processDebugJavaRes NO-SOURCE
[        ] > Task :flutter_plugin_android_lifecycle:bundleLibResDebug UP-TO-DATE
[        ] > Task :flutter_sound:processDebugJavaRes NO-SOURCE
[        ] > Task :flutter_sound:bundleLibResDebug UP-TO-DATE
[        ] > Task :fluttertoast:processDebugJavaRes NO-SOURCE
[        ] > Task :fluttertoast:bundleLibResDebug UP-TO-DATE
[        ] > Task :image_picker:processDebugJavaRes NO-SOURCE
[        ] > Task :image_picker:bundleLibResDebug UP-TO-DATE
[        ] > Task :package_info_plus:processDebugJavaRes NO-SOURCE
[        ] > Task :package_info_plus:bundleLibResDebug UP-TO-DATE
[        ] > Task :path_provider:processDebugJavaRes NO-SOURCE
[        ] > Task :path_provider:bundleLibResDebug UP-TO-DATE
[        ] > Task :permission_handler:processDebugJavaRes NO-SOURCE
[        ] > Task :permission_handler:bundleLibResDebug UP-TO-DATE
[        ] > Task :share_plus:processDebugJavaRes NO-SOURCE
[        ] > Task :share_plus:bundleLibResDebug UP-TO-DATE
[        ] > Task :shared_preferences:processDebugJavaRes NO-SOURCE
[        ] > Task :shared_preferences:bundleLibResDebug UP-TO-DATE
[        ] > Task :url_launcher:processDebugJavaRes NO-SOURCE
[        ] > Task :url_launcher:bundleLibResDebug UP-TO-DATE
[        ] > Task :video_player:processDebugJavaRes NO-SOURCE
[        ] > Task :video_player:bundleLibResDebug UP-TO-DATE
[        ] > Task :video_thumbnail:processDebugJavaRes NO-SOURCE
[        ] > Task :video_thumbnail:bundleLibResDebug UP-TO-DATE
[        ] > Task :wakelock:processDebugJavaRes NO-SOURCE
[        ] > Task :wakelock:bundleLibResDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[  +96 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :firebase_core:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :firebase_dynamic_links:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :firebase_messaging:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :image_picker:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :shared_preferences:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :flutter_local_notifications:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :path_provider:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :flutter_sound:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :wakelock:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :video_thumbnail:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :device_info:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :video_player:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :share_plus:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :package_info_plus:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :fluttertoast:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :url_launcher:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :permission_handler:bundleLibRuntimeDebug UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:mergeLibDexDebug UP-TO-DATE
[        ] > Task :app:mergeProjectDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :device_info:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :device_info:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :device_info:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :device_info:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :firebase_core:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :firebase_core:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :firebase_core:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :firebase_core:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :firebase_dynamic_links:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :firebase_dynamic_links:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :firebase_dynamic_links:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :firebase_dynamic_links:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :firebase_messaging:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :firebase_messaging:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :firebase_messaging:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :firebase_messaging:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :flutter_local_notifications:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :flutter_local_notifications:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :flutter_local_notifications:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :flutter_local_notifications:copyDebugJniLibsProjectOnly UP-TO-DATE
[  +97 ms] > Task :flutter_plugin_android_lifecycle:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :flutter_sound:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :flutter_sound:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :flutter_sound:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :flutter_sound:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :fluttertoast:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :fluttertoast:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :fluttertoast:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :fluttertoast:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :image_picker:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :image_picker:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :image_picker:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :image_picker:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :package_info_plus:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :package_info_plus:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :package_info_plus:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :package_info_plus:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :path_provider:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :path_provider:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :path_provider:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :path_provider:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :permission_handler:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :permission_handler:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :permission_handler:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :permission_handler:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :share_plus:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :share_plus:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :share_plus:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :share_plus:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :shared_preferences:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :shared_preferences:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :shared_preferences:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :shared_preferences:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :url_launcher:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :url_launcher:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :url_launcher:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :url_launcher:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :video_player:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :video_player:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :video_player:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :video_player:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :video_thumbnail:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :video_thumbnail:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :video_thumbnail:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :video_thumbnail:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :wakelock:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :wakelock:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :wakelock:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :wakelock:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] WARNING: Compatible side by side NDK version was not found. Default is 20.0.5594570.
[        ] Compatible side by side NDK version was not found. Default is 20.0.5594570.
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[ +995 ms] > Task :app:packageDebug
[ +200 ms] > Task :app:assembleDebug
[        ] > Task :device_info:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :device_info:extractDebugAnnotations UP-TO-DATE
[        ] > Task :device_info:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :device_info:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :device_info:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :device_info:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :device_info:syncDebugLibJars UP-TO-DATE
[        ] > Task :device_info:bundleDebugAar UP-TO-DATE
[        ] > Task :device_info:compileDebugSources UP-TO-DATE
[        ] > Task :device_info:assembleDebug UP-TO-DATE
[        ] > Task :firebase_core:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :firebase_core:extractDebugAnnotations UP-TO-DATE
[        ] > Task :firebase_core:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :firebase_core:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :firebase_core:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :firebase_core:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :firebase_core:syncDebugLibJars UP-TO-DATE
[        ] > Task :firebase_core:bundleDebugAar UP-TO-DATE
[        ] > Task :firebase_core:compileDebugSources UP-TO-DATE
[        ] > Task :firebase_core:assembleDebug UP-TO-DATE
[        ] > Task :firebase_dynamic_links:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :firebase_dynamic_links:extractDebugAnnotations UP-TO-DATE
[        ] > Task :firebase_dynamic_links:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :firebase_dynamic_links:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :firebase_dynamic_links:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :firebase_dynamic_links:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :firebase_dynamic_links:syncDebugLibJars UP-TO-DATE
[        ] > Task :firebase_dynamic_links:bundleDebugAar UP-TO-DATE
[        ] > Task :firebase_dynamic_links:compileDebugSources UP-TO-DATE
[        ] > Task :firebase_dynamic_links:assembleDebug UP-TO-DATE
[        ] > Task :firebase_messaging:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :firebase_messaging:extractDebugAnnotations UP-TO-DATE
[        ] > Task :firebase_messaging:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :firebase_messaging:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :firebase_messaging:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :firebase_messaging:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :firebase_messaging:syncDebugLibJars UP-TO-DATE
[        ] > Task :firebase_messaging:bundleDebugAar UP-TO-DATE
[        ] > Task :firebase_messaging:compileDebugSources UP-TO-DATE
[        ] > Task :firebase_messaging:assembleDebug UP-TO-DATE
[        ] > Task :flutter_local_notifications:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :flutter_local_notifications:extractDebugAnnotations UP-TO-DATE
[        ] > Task :flutter_local_notifications:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :flutter_local_notifications:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :flutter_local_notifications:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :flutter_local_notifications:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :flutter_local_notifications:syncDebugLibJars UP-TO-DATE
[        ] > Task :flutter_local_notifications:bundleDebugAar UP-TO-DATE
[        ] > Task :flutter_local_notifications:compileDebugSources UP-TO-DATE
[        ] > Task :flutter_local_notifications:assembleDebug UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[  +95 ms] > Task :flutter_plugin_android_lifecycle:extractDebugAnnotations UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:syncDebugLibJars UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:bundleDebugAar UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:compileDebugSources UP-TO-DATE
[        ] > Task :flutter_plugin_android_lifecycle:assembleDebug UP-TO-DATE
[        ] > Task :flutter_sound:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :flutter_sound:extractDebugAnnotations UP-TO-DATE
[        ] > Task :flutter_sound:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :flutter_sound:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :flutter_sound:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :flutter_sound:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :flutter_sound:syncDebugLibJars UP-TO-DATE
[        ] > Task :flutter_sound:bundleDebugAar UP-TO-DATE
[        ] > Task :flutter_sound:compileDebugSources UP-TO-DATE
[        ] > Task :flutter_sound:assembleDebug UP-TO-DATE
[        ] > Task :fluttertoast:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :fluttertoast:extractDebugAnnotations UP-TO-DATE
[        ] > Task :fluttertoast:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :fluttertoast:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :fluttertoast:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :fluttertoast:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :fluttertoast:syncDebugLibJars UP-TO-DATE
[        ] > Task :fluttertoast:bundleDebugAar UP-TO-DATE
[        ] > Task :fluttertoast:compileDebugSources UP-TO-DATE
[        ] > Task :fluttertoast:assembleDebug UP-TO-DATE
[        ] > Task :image_picker:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :image_picker:extractDebugAnnotations UP-TO-DATE
[        ] > Task :image_picker:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :image_picker:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :image_picker:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :image_picker:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :image_picker:syncDebugLibJars UP-TO-DATE
[        ] > Task :image_picker:bundleDebugAar UP-TO-DATE
[        ] > Task :image_picker:mergeDebugResources UP-TO-DATE
[        ] > Task :image_picker:compileDebugSources UP-TO-DATE
[        ] > Task :image_picker:assembleDebug UP-TO-DATE
[        ] > Task :package_info_plus:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :package_info_plus:extractDebugAnnotations UP-TO-DATE
[        ] > Task :package_info_plus:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :package_info_plus:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :package_info_plus:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :package_info_plus:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :package_info_plus:syncDebugLibJars UP-TO-DATE
[        ] > Task :package_info_plus:bundleDebugAar UP-TO-DATE
[        ] > Task :package_info_plus:compileDebugSources UP-TO-DATE
[        ] > Task :package_info_plus:assembleDebug UP-TO-DATE
[        ] > Task :path_provider:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :path_provider:extractDebugAnnotations UP-TO-DATE
[        ] > Task :path_provider:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :path_provider:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :path_provider:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :path_provider:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :path_provider:syncDebugLibJars UP-TO-DATE
[        ] > Task :path_provider:bundleDebugAar UP-TO-DATE
[        ] > Task :path_provider:mergeDebugResources UP-TO-DATE
[        ] > Task :path_provider:compileDebugSources UP-TO-DATE
[        ] > Task :path_provider:assembleDebug UP-TO-DATE
[        ] > Task :permission_handler:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :permission_handler:extractDebugAnnotations UP-TO-DATE
[        ] > Task :permission_handler:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :permission_handler:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :permission_handler:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :permission_handler:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :permission_handler:syncDebugLibJars UP-TO-DATE
[        ] > Task :permission_handler:bundleDebugAar UP-TO-DATE
[        ] > Task :permission_handler:compileDebugSources UP-TO-DATE
[        ] > Task :permission_handler:assembleDebug UP-TO-DATE
[        ] > Task :share_plus:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :share_plus:extractDebugAnnotations UP-TO-DATE
[        ] > Task :share_plus:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :share_plus:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :share_plus:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :share_plus:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :share_plus:syncDebugLibJars UP-TO-DATE
[        ] > Task :share_plus:bundleDebugAar UP-TO-DATE
[        ] > Task :share_plus:compileDebugSources UP-TO-DATE
[        ] > Task :share_plus:assembleDebug UP-TO-DATE
[        ] > Task :shared_preferences:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :shared_preferences:extractDebugAnnotations UP-TO-DATE
[        ] > Task :shared_preferences:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :shared_preferences:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :shared_preferences:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :shared_preferences:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :shared_preferences:syncDebugLibJars UP-TO-DATE
[        ] > Task :shared_preferences:bundleDebugAar UP-TO-DATE
[        ] > Task :shared_preferences:mergeDebugResources UP-TO-DATE
[        ] > Task :shared_preferences:compileDebugSources UP-TO-DATE
[        ] > Task :shared_preferences:assembleDebug UP-TO-DATE
[        ] > Task :url_launcher:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :url_launcher:extractDebugAnnotations UP-TO-DATE
[        ] > Task :url_launcher:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :url_launcher:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :url_launcher:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :url_launcher:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :url_launcher:syncDebugLibJars UP-TO-DATE
[        ] > Task :url_launcher:bundleDebugAar UP-TO-DATE
[        ] > Task :url_launcher:mergeDebugResources UP-TO-DATE
[        ] > Task :url_launcher:compileDebugSources UP-TO-DATE
[        ] > Task :url_launcher:assembleDebug UP-TO-DATE
[        ] > Task :video_player:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :video_player:extractDebugAnnotations UP-TO-DATE
[        ] > Task :video_player:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :video_player:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :video_player:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :video_player:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :video_player:syncDebugLibJars UP-TO-DATE
[        ] > Task :video_player:bundleDebugAar UP-TO-DATE
[        ] > Task :video_player:mergeDebugResources UP-TO-DATE
[        ] > Task :video_player:compileDebugSources UP-TO-DATE
[        ] > Task :video_player:assembleDebug UP-TO-DATE
[        ] > Task :video_thumbnail:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :video_thumbnail:extractDebugAnnotations UP-TO-DATE
[        ] > Task :video_thumbnail:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :video_thumbnail:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :video_thumbnail:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :video_thumbnail:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :video_thumbnail:syncDebugLibJars UP-TO-DATE
[        ] > Task :video_thumbnail:bundleDebugAar UP-TO-DATE
[        ] > Task :video_thumbnail:compileDebugSources UP-TO-DATE
[        ] > Task :video_thumbnail:assembleDebug UP-TO-DATE
[        ] > Task :wakelock:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :wakelock:extractDebugAnnotations UP-TO-DATE
[        ] > Task :wakelock:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :wakelock:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :wakelock:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :wakelock:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :wakelock:syncDebugLibJars UP-TO-DATE
[        ] > Task :wakelock:bundleDebugAar UP-TO-DATE
[        ] > Task :wakelock:compileDebugSources UP-TO-DATE
[        ] > Task :wakelock:assembleDebug UP-TO-DATE
[  +17 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 14s
[        ] 543 actionable tasks: 6 executed, 537 up-to-date
[ +358 ms] Running Gradle task 'assembleDebug'... (completed in 15.0s)
[  +93 ms] calculateSha: LocalDirectory:
'/home/juancarlos/AndroidStudioProjects/solon_flutter_app/build/app/outputs/flutter-apk'/app.apk
[+1392 ms] ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
[   +1 ms] executing: /home/juancarlos/Android/Sdk/build-tools/30.0.2/aapt dump xmltree
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +8 ms] Exit code 0 from: /home/juancarlos/Android/Sdk/build-tools/30.0.2/aapt dump xmltree
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.solon.app" (Raw: "com.solon.app")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x15
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=17)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=18)
                 A: android:name(0x01010003)="android.permission.RECORD_AUDIO" (Raw:
                 "android.permission.RECORD_AUDIO")
               E: uses-permission (line=19)
                 A: android:name(0x01010003)="android.permission.FOREGROUND_SERVICE" (Raw:
                 "android.permission.FOREGROUND_SERVICE")
               E: uses-permission (line=20)
                 A: android:name(0x01010003)="android.permission.WAKE_LOCK" (Raw: "android.permission.WAKE_LOCK")
               E: uses-permission (line=21)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw:
                 "android.permission.ACCESS_NETWORK_STATE")
               E: uses-permission (line=22)
                 A: android:name(0x01010003)="android.permission.RECEIVE_BOOT_COMPLETED" (Raw:
                 "android.permission.RECEIVE_BOOT_COMPLETED")
               E: uses-permission (line=23)
                 A: android:name(0x01010003)="android.permission.VIBRATE" (Raw: "android.permission.VIBRATE")
               E: uses-permission (line=24)
                 A: android:name(0x01010003)="android.permission.USE_FULL_SCREEN_INTENT" (Raw:
                 "android.permission.USE_FULL_SCREEN_INTENT")
               E: uses-permission (line=25)
                 A: android:name(0x01010003)="com.google.android.c2dm.permission.RECEIVE" (Raw:
                 "com.google.android.c2dm.permission.RECEIVE")
               E: uses-permission (line=26)
                 A: android:name(0x01010003)="android.permission.BLUETOOTH" (Raw: "android.permission.BLUETOOTH")
               E: uses-permission (line=27)
                 A: android:name(0x01010003)="android.permission.MODIFY_AUDIO_SETTINGS" (Raw:
                 "android.permission.MODIFY_AUDIO_SETTINGS")
               E: uses-permission (line=28)
                 A: android:name(0x01010003)="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE"
                 (Raw: "com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE")
               E: application (line=30)
                 A: android:label(0x01010001)="Solon" (Raw: "Solon")
                 A: android:icon(0x01010002)=@0x7f0b0000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw:
                 "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=36)
                   A: android:theme(0x01010000)=@0x7f0e00a2
                   A: android:name(0x01010003)="com.solon.app.MainActivity" (Raw: "com.solon.app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x2
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   A: android:usesCleartextTraffic(0x010104ec)=(type 0x12)0xffffffff
                   E: meta-data (line=51)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0e00a3
                   E: meta-data (line=61)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f06007a
                   E: intent-filter (line=65)
                     E: action (line=66)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=68)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                   E: intent-filter (line=70)
                     E: action (line=71)
                       A: android:name(0x01010003)="android.intent.action.VIEW" (Raw: "android.intent.action.VIEW")
                     E: category (line=73)
                       A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw:
                       "android.intent.category.DEFAULT")
                     E: category (line=74)
                       A: android:name(0x01010003)="android.intent.category.BROWSABLE" (Raw:
                       "android.intent.category.BROWSABLE")
                     E: data (line=76)
                       A: android:scheme(0x01010027)="https" (Raw: "https")
                       A: android:host(0x01010028)="www.soloninterests.com" (Raw: "www.soloninterests.com")
                   E: intent-filter (line=80)
                     E: action (line=81)
                       A: android:name(0x01010003)="FLUTTER_NOTIFICATION_CLICK" (Raw: "FLUTTER_NOTIFICATION_CLICK")
                     E: category (line=83)
                       A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw:
                       "android.intent.category.DEFAULT")
                 E: meta-data (line=90)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: service (line=94)
                   A: android:name(0x01010003)="com.google.firebase.components.ComponentDiscoveryService" (Raw:
                   "com.google.firebase.components.ComponentDiscoveryService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                   E: meta-data (line=98)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebasedynamiclinks.
                     FlutterFirebaseAppRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebasedynamiclinks.FlutterFirebaseAppRegistr
                     ar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=101)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebase.messaging.Fl
                     utterFirebaseAppRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebase.messaging.FlutterFirebaseAppRegistrar
                     ")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=104)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebase.core.Flutter
                     FirebaseCoreRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebase.core.FlutterFirebaseCoreRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=107)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.analytics.ktx.Fireba
                     seAnalyticsKtxRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.analytics.ktx.FirebaseAnalyticsKtxRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=110)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.ktx.FirebaseCommonKt
                     xRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.ktx.FirebaseCommonKtxRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=113)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.messaging.FirebaseMe
                     ssagingRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=116)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.datatransport.Transp
                     ortRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.datatransport.TransportRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=119)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.dynamiclinks.interna
                     l.FirebaseDynamicLinkRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.dynamiclinks.internal.FirebaseDynamicLinkRegi
                     strar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=122)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.analytics.connector.
                     internal.AnalyticsConnectorRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnect
                     orRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=125)
                     A:
                     android:name(0x01010003)="com.google.firebase.components:com.google.firebase.installations.Fireba
                     seInstallationsRegistrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar"
                     )
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw:
                     "com.google.firebase.components.ComponentRegistrar")
                 E: service (line=129)
                   A:
                   android:name(0x01010003)="io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundS
                   ervice" (Raw: "io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService")
                   A: android:permission(0x01010006)="android.permission.BIND_JOB_SERVICE" (Raw:
                   "android.permission.BIND_JOB_SERVICE")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: service (line=133)
                   A: android:name(0x01010003)="io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingService"
                   (Raw: "io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   E: intent-filter (line=136)
                     E: action (line=137)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw:
                       "com.google.firebase.MESSAGING_EVENT")
                 E: receiver (line=141)
                   A:
                   android:name(0x01010003)="io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver"
                   (Raw: "io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver")
                   A: android:permission(0x01010006)="com.google.android.c2dm.permission.SEND" (Raw:
                   "com.google.android.c2dm.permission.SEND")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   E: intent-filter (line=145)
                     E: action (line=146)
                       A: android:name(0x01010003)="com.google.android.c2dm.intent.RECEIVE" (Raw:
                       "com.google.android.c2dm.intent.RECEIVE")
                 E: provider (line=150)
                   A:
                   android:name(0x01010003)="io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingInitProvide
                   r" (Raw: "io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingInitProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.solon.app.flutterfirebasemessaginginitprovider" (Raw:
                   "com.solon.app.flutterfirebasemessaginginitprovider")
                   A: android:initOrder(0x0101001a)=(type 0x10)0x63
                 E: provider (line=155)
                   A: android:name(0x01010003)="io.flutter.plugins.imagepicker.ImagePickerFileProvider" (Raw:
                   "io.flutter.plugins.imagepicker.ImagePickerFileProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.solon.app.flutter.image_provider" (Raw:
                   "com.solon.app.flutter.image_provider")
                   A: android:grantUriPermissions(0x0101001b)=(type 0x12)0xffffffff
                   E: meta-data (line=160)
                     A: android:name(0x01010003)="android.support.FILE_PROVIDER_PATHS" (Raw:
                     "android.support.FILE_PROVIDER_PATHS")
                     A: android:resource(0x01010025)=@0x7f100000
                 E: receiver (line=165)
                   A: android:name(0x01010003)="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver"
                   (Raw: "com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver")
                 E: receiver (line=166)
                   A:
                   android:name(0x01010003)="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver
                   " (Raw: "com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver")
                   E: intent-filter (line=167)
                     E: action (line=168)
                       A: android:name(0x01010003)="android.intent.action.BOOT_COMPLETED" (Raw:
                       "android.intent.action.BOOT_COMPLETED")
                     E: action (line=169)
                       A: android:name(0x01010003)="android.intent.action.MY_PACKAGE_REPLACED" (Raw:
                       "android.intent.action.MY_PACKAGE_REPLACED")
                     E: action (line=170)
                       A: android:name(0x01010003)="android.intent.action.QUICKBOOT_POWERON" (Raw:
                       "android.intent.action.QUICKBOOT_POWERON")
                     E: action (line=171)
                       A: android:name(0x01010003)="com.htc.intent.action.QUICKBOOT_POWERON" (Raw:
                       "com.htc.intent.action.QUICKBOOT_POWERON")
                 E: provider (line=175)
                   A: android:name(0x01010003)="dev.fluttercommunity.plus.share.ShareFileProvider" (Raw:
                   "dev.fluttercommunity.plus.share.ShareFileProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.solon.app.flutter.share_provider" (Raw:
                   "com.solon.app.flutter.share_provider")
                   A: android:grantUriPermissions(0x0101001b)=(type 0x12)0xffffffff
                   E: meta-data (line=180)
                     A: android:name(0x01010003)="android.support.FILE_PROVIDER_PATHS" (Raw:
                     "android.support.FILE_PROVIDER_PATHS")
                     A: android:resource(0x01010025)=@0x7f100001
                 E: activity (line=185)
                   A: android:theme(0x01010000)=@0x01030007
                   A: android:name(0x01010003)="io.flutter.plugins.urllauncher.WebViewActivity" (Raw:
                   "io.flutter.plugins.urllauncher.WebViewActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: receiver (line=190)
                   A: android:name(0x01010003)="com.google.firebase.iid.FirebaseInstanceIdReceiver" (Raw:
                   "com.google.firebase.iid.FirebaseInstanceIdReceiver")
                   A: android:permission(0x01010006)="com.google.android.c2dm.permission.SEND" (Raw:
                   "com.google.android.c2dm.permission.SEND")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   E: intent-filter (line=194)
                     E: action (line=195)
                       A: android:name(0x01010003)="com.google.android.c2dm.intent.RECEIVE" (Raw:
                       "com.google.android.c2dm.intent.RECEIVE")
                 E: service (line=202)
                   A: android:name(0x01010003)="com.google.firebase.messaging.FirebaseMessagingService" (Raw:
                   "com.google.firebase.messaging.FirebaseMessagingService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                   E: intent-filter (line=206)
                     A: android:priority(0x0101001c)=(type 0x10)0xfffffe0c
                     E: action (line=207)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw:
                       "com.google.firebase.MESSAGING_EVENT")
                 E: service (line=210)
                   A:
                   android:name(0x01010003)="com.google.android.datatransport.runtime.backends.TransportBackendDiscove
                   ry" (Raw: "com.google.android.datatransport.runtime.backends.TransportBackendDiscovery")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   E: meta-data (line=213)
                     A: android:name(0x01010003)="backend:com.google.android.datatransport.cct.CctBackendFactory"
                     (Raw: "backend:com.google.android.datatransport.cct.CctBackendFactory")
                     A: android:value(0x01010024)="cct" (Raw: "cct")
                 E: provider (line=218)
                   A: android:name(0x01010003)="com.google.firebase.provider.FirebaseInitProvider" (Raw:
                   "com.google.firebase.provider.FirebaseInitProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="com.solon.app.firebaseinitprovider" (Raw:
                   "com.solon.app.firebaseinitprovider")
                   A: android:initOrder(0x0101001a)=(type 0x10)0x64
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                 E: receiver (line=225)
                   A: android:name(0x01010003)="androidx.media.session.MediaButtonReceiver" (Raw:
                   "androidx.media.session.MediaButtonReceiver")
                   E: intent-filter (line=226)
                     E: action (line=227)
                       A: android:name(0x01010003)="android.intent.action.MEDIA_BUTTON" (Raw:
                       "android.intent.action.MEDIA_BUTTON")
                     E: action (line=228)
                       A: android:name(0x01010003)="android.media.AUDIO_BECOMING_NOISY" (Raw:
                       "android.media.AUDIO_BECOMING_NOISY")
                 E: service (line=232)
                   A: android:name(0x01010003)="com.dooboolab.TauEngine.FlautoBackgroundAudioService" (Raw:
                   "com.dooboolab.TauEngine.FlautoBackgroundAudioService")
                   E: intent-filter (line=233)
                     E: action (line=234)
                       A: android:name(0x01010003)="android.intent.action.MEDIA_BUTTON" (Raw:
                       "android.intent.action.MEDIA_BUTTON")
                     E: action (line=235)
                       A: android:name(0x01010003)="android.media.AUDIO_BECOMING_NOISY" (Raw:
                       "android.media.AUDIO_BECOMING_NOISY")
                     E: action (line=236)
                       A: android:name(0x01010003)="android.media.browse.FlautoMediaBrowserService" (Raw:
                       "android.media.browse.FlautoMediaBrowserService")
                 E: activity (line=240)
                   A: android:theme(0x01010000)=@0x01030010
                   A: android:name(0x01010003)="com.google.android.gms.common.api.GoogleApiActivity" (Raw:
                   "com.google.android.gms.common.api.GoogleApiActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: receiver (line=245)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementReceiver" (Raw:
                   "com.google.android.gms.measurement.AppMeasurementReceiver")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: service (line=251)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementService" (Raw:
                   "com.google.android.gms.measurement.AppMeasurementService")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: service (line=255)
                   A: android:name(0x01010003)="com.google.android.gms.measurement.AppMeasurementJobService" (Raw:
                   "com.google.android.gms.measurement.AppMeasurementJobService")
                   A: android:permission(0x01010006)="android.permission.BIND_JOB_SERVICE" (Raw:
                   "android.permission.BIND_JOB_SERVICE")
                   A: android:enabled(0x0101000e)=(type 0x12)0xffffffff
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: meta-data (line=261)
                   A: android:name(0x01010003)="com.google.android.gms.version" (Raw:
                   "com.google.android.gms.version")
                   A: android:value(0x01010024)=@0x7f080004
                 E: service (line=265)
                   A:
                   android:name(0x01010003)="com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfo
                   SchedulerService" (Raw:
                   "com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService")
                   A: android:permission(0x01010006)="android.permission.BIND_JOB_SERVICE" (Raw:
                   "android.permission.BIND_JOB_SERVICE")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: receiver (line=271)
                   A:
                   android:name(0x01010003)="com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmMa
                   nagerSchedulerBroadcastReceiver" (Raw:
                   "com.google.android.datatransport.runtime.scheduling.jobscheduling.AlarmManagerSchedulerBroadcastRe
                   ceiver")
                   A: android:exported(0x01010010)=(type 0x12)0x0
[   +7 ms] Stopping app 'app.apk' on Android SDK built for x86.
[        ] executing: /home/juancarlos/Android/Sdk/platform-tools/adb -s emulator-5554 shell am force-stop
com.solon.app
[  +36 ms] executing: /home/juancarlos/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm list packages
com.solon.app
[  +28 ms] package:com.solon.app
[   +1 ms] executing: /home/juancarlos/Android/Sdk/platform-tools/adb -s emulator-5554 shell cat
/data/local/tmp/sky.com.solon.app.sha1
[  +18 ms] 4f0afa1e52a0a58c05c5cd589f637c2f7e554878
[        ] Installing APK.
[        ] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /home/juancarlos/Android/Sdk/platform-tools/adb -s emulator-5554 install -t -r
/home/juancarlos/AndroidStudioProjects/solon_flutter_app/build/app/outputs/flutter-apk/app.apk
[+1555 ms] Performing Streamed Install
                    Success
[        ] Installing build/app/outputs/flutter-apk/app.apk... (completed in 1,555ms)
[        ] executing: /home/juancarlos/Android/Sdk/platform-tools/adb -s emulator-5554 shell echo -n
0dc3d37ff0e34e22e634620b0d27ea02260a7936 > /data/local/tmp/sky.com.solon.app.sha1
[  +41 ms] executing: /home/juancarlos/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +74 ms] --------- beginning of main
           10-08 20:37:00.220 D/CarrierSvcBindHelper( 1154): No carrier app for: 0
[  +15 ms] executing: /home/juancarlos/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -a
android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true com.solon.app/com.solon.app.MainActivity
[  +60 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.solon.app/.MainActivity (has
extras) }
[        ] Waiting for observatory port to be available...
[+1043 ms] W/FlutterActivityAndFragmentDelegate( 9203): A splash screen was provided to Flutter, but this is
deprecated. See flutter.dev/go/android-splash-migration for migration steps.
[  +52 ms] Observatory URL on device: http://127.0.0.1:34353/JpUa64_u00w=/
[        ] executing: /home/juancarlos/Android/Sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:34353
[   +7 ms] 38951
[        ] Forwarded host port 38951 to device port 34353 for Observatory
[   +4 ms] Caching compiled dill
[  +34 ms] Connecting to service protocol: http://127.0.0.1:38951/JpUa64_u00w=/
[ +223 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:38951/JpUa64_u00w=/.
[ +113 ms] DDS is listening at http://127.0.0.1:44685/e86hFN1iVNY=/.
[  +38 ms] Successfully connected to service protocol: http://127.0.0.1:38951/JpUa64_u00w=/
[  +99 ms] DevFS: Creating new filesystem on the device (null)
[  +28 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.solon.app/code_cache/solon_flutter_appSLMPII/solon_flutter_app/)
[   +1 ms] Updating assets
[ +124 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more
information see #56466.
[   +4 ms] Syncing files to device Android SDK built for x86...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:solon_app/main.dart 7ba4fe66-b238-4a31-8f79-1cb7d403f7e5
[        ] <- 7ba4fe66-b238-4a31-8f79-1cb7d403f7e5
[  +61 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Android SDK built for x86... (completed in 64ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +2 ms] Connected to _flutterView/0xf5243020.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Android SDK built for x86 is available at:
           http://127.0.0.1:44685/e86hFN1iVNY=/
[ +255 ms] DevTools activation throttled until 2021-10-09 08:12:58.468192.
[ +744 ms] The Flutter DevTools debugger and profiler on Android SDK built for x86 is available at:
                    http://127.0.0.1:9101?uri=http://127.0.0.1:44685/e86hFN1iVNY=/


```

```
Analyzing ReproducibleIssueProject...    
No issues found! (ran in 2.9s)

```

```
[✓] Flutter (Channel stable, 2.5.2, on Ubuntu 20.04.3 LTS 5.11.0-37-generic, locale en_US.UTF-8)
    • Flutter version 2.5.2 at /home/juancarlos/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (8 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/juancarlos/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/juancarlos/android-studio
    • Flutter plugin version 61.2.3
    • Dart plugin version 211.7792
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.81

! Doctor found issues in 1 category.

```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
Currently, SelectableText always stays alive, which can create two problems observed in https://github.com/flutter/flutter/issues/91509:

  1. Performance can suffer in long lists of SelectableTexts.
  2. SelectableText can cause a PrimaryScrollController to stay connected unexpectedly.

I've changed SelectableText's wantKeepAlive to match EditableText, so it only stays alive if it's focused:

https://github.com/flutter/flutter/blob/b5e1ebd73348983c9b22863eb2d52ac15194774c/packages/flutter/lib/src/widgets/editable_text.dart#L1567

@chunhtai Do you know of any reason we shouldn't do that?

I've also added some docs to try to warn developers about the second problem a bit.  @Piinks Is there anywhere else I should document that?

Fixes https://github.com/flutter/flutter/issues/91509

### CODE REVIEW

**Comment by chunhtai** [comment]
I can't remember why I wrote it this way, but the change looks reasonable

File: packages/flutter/lib/src/material/selectable_text.dart [hunk 1]
```diff
@@ -123,6 +123,12 @@ class _SelectableTextSelectionGestureDetectorBuilder extends TextSelectionGestur
 /// behavior is useful, for example, to make the text bold while using the
 /// default font family and size.
 ///
+/// When the widget has some selection, it will keep itself from disposing via
+/// [AutomaticKeepAliveClientMixin.wantKeepAlive] in order to avoid losing the
+/// selection. This may have implications for performance and for preventing
+/// parent widgets from disposing, such as [Scrollable]s that may expect to be
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/selectable_text.dart:129]: I think we should not mention Scrollable/PrimaryScrollController because it is more of implementation detail? I think we should just state there is performance implication and state the consequence if there is any

Comment (chunhtai) [reply packages/flutter/lib/src/material/selectable_text.dart:129]: alternatively, if it the consequence is too serious we could make it not keep alive in any case, and it is up to the developer to keep it alive if they want.

Comment (Piinks) [reply packages/flutter/lib/src/material/selectable_text.dart:129]: I agree with @chunhtai's first comment here. First sentence - :100:. Adding a mention of focus might be nice, since that is what having some selection appears to mean from this change. :)
I think leaving it up to the developer would make it harder for the developer to figure out what to do, especially if they try it themselves and then run into this weird crash. It seems like a really subtle thing that should just work.

**Review by chunhtai — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/selectable_text.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/selectable_text.dart]: Thanks, I've simplified the wording a bit.

I'll keep an eye out in case anyone else mentions wanting to be able to control wantKeepAlive on SelectableText and EditableText.  Maybe we could add a parameter or something.  For now I think basing it on focus is the most intuitive thing in most cases.

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

File: packages/flutter/lib/src/material/selectable_text.dart [hunk 2]
```diff
@@ -580,7 +584,7 @@ class _SelectableTextState extends State<SelectableText> with AutomaticKeepAlive
   }
 
   @override
-  bool get wantKeepAlive => true;
```
Comment (nt4f04uNd) [inline packages/flutter/lib/src/material/selectable_text.dart:583]: Should `updateKeepAlive` be called when focus changes?

Comment (chunhtai) [reply packages/flutter/lib/src/material/selectable_text.dart:583]: it is called in the editable_text base class

**Review by chunhtai — CHANGES_REQUESTED** [review]
I noticed the editableText already had the same logic, maybe we should just remove the automatic keep alive in selectable?

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by justinmc** [comment]
FYI reviewers I just pushed a commit to add that paragraph about `wantKeepAlive` to all of the EditableText-related widgets.  Will merge when green.

File: packages/flutter/lib/src/material/selectable_text.dart (hunk 1 above)
Comment (Tokenyet) [reply packages/flutter/lib/src/material/selectable_text.dart]: Sorry to metion here, but I just found out this is causing the bug for PageView as https://github.com/flutter/flutter/issues/93224 said. I think issue should  be reopened and should be noticed, It cost me a whole day to find out that `SelectableText` can mess up with `PageView`... 😞
