### PR TITLE
fix: Preserve state in horizontal stepper

### LINKED ISSUE #73663: AutomaticKeepAliveClientMixin not working for a Step in a Horizontal Stepper
When AutomaticKeepAliveClientMixin  used for a Step ( Step1 in this case) in a Horizontal Stepper, it doesn't keep the state alive for the step and it rebuilds everytime when switching to/from another step.

## Steps to Reproduce
Use the following main.dart(only file):-

`

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Stepper Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Stepper Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _index = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Stepper(
          currentStep: _index,
          steps: [
            Step(
              title: Text("First"),
              content: Step1(),
            ),
            Step(
              title: Text("Second"),
              content: Text("Second Step"),
            ),
          ],
          type: StepperType.horizontal,
          onStepTapped: (index) {
            setState(() {
              _index = index;
            });
          },
        ));
  }
}

class Step1 extends StatefulWidget {
  const Step1({Key key}) : super(key: key);
  @override
  _Step1State createState() => _Step1State();
}

class _Step1State extends State<Step1> with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return TextFormField(
        initialValue: DateTime.now().microsecondsSinceEpoch.toString());
  }
}

`

```

### PR DESCRIPTION
**Pull request by craiglabenz**
For background context, the vertical stepper renders each `Step` at all times, regardless of which one is currently active. This means that `State` objects for previous or future steps are still in the widget tree, holding on to whatever interesting bits they have.

The horizontal stepper, on the other hand, only rendered the active step, causing the framework to dispose previous steps. This led to behavior where Step 1 would initialize its values upon the stepper's first render, and then would _re-initialize_ upon user navigation _back to Step 1_. Also, any activity from the user would be lost.

With this change, the Stepper widget behaves similarly in horizontal and vertical mode; both ways maintaining every step in the Stepper (with inactive steps being offstage), thus allowing for `State` objects to persist.

The added test uses a Stateful widget that initializes to a random color background, thus exposing whether the widget was kept in the tree or disposed during navigation.

Fixes #73663

### CODE REVIEW

File: packages/flutter/lib/src/material/stepper.dart [hunk 1]
```diff
@@ -717,7 +728,7 @@ class _StepperState extends State<Stepper> with TickerProviderStateMixin {
               AnimatedSize(
                 curve: Curves.fastOutSlowIn,
                 duration: kThemeAnimationDuration,
-                child: widget.steps[widget.currentStep].content,
+                child: Column(children: stepPanels, crossAxisAlignment: CrossAxisAlignment.stretch),
```
Comment (craiglabenz) [inline packages/flutter/lib/src/material/stepper.dart:731]: Would like a second eye on this `crossAxisAlignment` value, which I _think_ is what best replicates the old layout; but I am not certain.

Comment (Piinks) [reply packages/flutter/lib/src/material/stepper.dart:731]: I think this looks ok.

File: packages/flutter/lib/src/material/stepper.dart [hunk 2]
```diff
@@ -698,6 +698,17 @@ class _StepperState extends State<Stepper> with TickerProviderStateMixin {
       ],
     ];
 
+    final List<Widget> stepPanels = <Widget>[];
+    for (int i = 0; i < widget.steps.length; i += 1) {
+      stepPanels.add(
+        Visibility(
+          maintainState: true,
+          visible: i == widget.currentStep,
+          child: widget.steps[i].content,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/stepper.dart:707]: Nice! I love it when it's a clean and simple fix. 🙌

File: packages/flutter/test/material/stepper_test.dart [hunk 3]
```diff
@@ -953,4 +954,100 @@ void main() {
 
      expect(material.elevation, 2.0);
    });
+
+  testWidgets('Stepper horizontal preserves state', (WidgetTester tester) async {
+    Widget buildFrame() {
+      return const MaterialApp(
+        home: Scaffold(
+          body: Center(
+            // Must break this out into its own widget purely to be able to call `setState()`
```
Comment (Piinks) [inline packages/flutter/test/material/stepper_test.dart:963]: Would a StatefulBuilder help here? You can capture the StateSetter in the builder.

File: packages/flutter/test/material/stepper_test.dart [hunk 4]
```diff
@@ -953,4 +954,100 @@ void main() {
...
+        Step(
+          title: Text('Step 2'),
+          content: Text('Step 2 Content'),
+        ),
+      ],
+    );
+  }
+}
+
+class RandomColorWidget extends StatefulWidget {
```
Comment (Piinks) [inline packages/flutter/test/material/stepper_test.dart:1029]: Rather than a random color pick, you could just bake in the states, like start step 1 with blue, call the state setter to make it red and then validate it is still red when you come back?

**Review by Piinks — COMMENTED** [review]
This test might help: https://github.com/flutter/flutter/blob/236a114ddb1eb0297bde1360837594d50f236ffe/packages/flutter/test/cupertino/action_sheet_test.dart#L121

This will need to be rebased with master in order to resolve the infra issues

**Review by Piinks — APPROVED** [review]
LGTM with nit!
