### PR TITLE
Check for bad characters in path on Windows build

### LINKED ISSUE #104802: [Windows][Desktop]: MSB4100 error from %(Link.AdditionalDependencies when path contains `'`
## Error Detail

When i tried run the app with Windows Development (flutter run -d windows), it's give an error MSB4100. I'm using Visual Studio 2022.

## Logs

<details>
<summary>Logs</summary>

```
[ +171 ms] executing: [C:\F Folder\SDK\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +502 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] fb57da5f945d02ef4f98dfd9409a72b7cce74268
[   +2 ms] executing: [C:\F Folder\SDK\flutter/] git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[ +161 ms] Exit code 0 from: git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[   +1 ms] 3.0.1
[  +22 ms] executing: [C:\F Folder\SDK\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +130 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\F Folder\SDK\flutter/] git ls-remote --get-url origin
[ +119 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +335 ms] executing: [C:\F Folder\SDK\flutter/] git rev-parse --abbrev-ref HEAD
[ +172 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +295 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +20 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +193 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +25 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +260 ms] Skipping pub get: version match.
[  +97 ms] Found plugin cloud_firestore at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-3.1.14\
[  +25 ms] Found plugin cloud_firestore_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-2.6.14\
[  +21 ms] Found plugin firebase_auth at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-3.3.15\
[  +10 ms] Found plugin firebase_auth_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-3.3.13\
[  +14 ms] Found plugin firebase_core at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.16.0\
[  +11 ms] Found plugin firebase_core_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.6.3\
[   +6 ms] Found plugin flutter_facebook_auth at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_auth-4.3.0\
[  +12 ms] Found plugin flutter_facebook_auth_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_auth_web-3.1.0\
[  +15 ms] Found plugin google_sign_in at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.3.0\
[   +7 ms] Found plugin google_sign_in_android at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_android-5.2.5\
[   +7 ms] Found plugin google_sign_in_ios at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_ios-5.2.5\
[  +10 ms] Found plugin google_sign_in_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.1\
[  +67 ms] Found plugin sign_in_with_apple at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\sign_in_with_apple-3.3.0\
[  +10 ms] Found plugin sign_in_with_apple_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\sign_in_with_apple_web-1.0.1\
[ +173 ms] Found plugin cloud_firestore at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-3.1.14\
[   +8 ms] Found plugin cloud_firestore_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-2.6.14\
[  +16 ms] Found plugin firebase_auth at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-3.3.15\
[   +7 ms] Found plugin firebase_auth_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-3.3.13\
[   +8 ms] Found plugin firebase_core at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.16.0\
[   +7 ms] Found plugin firebase_core_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.6.3\
[   +4 ms] Found plugin flutter_facebook_auth at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_auth-4.3.0\
[   +5 ms] Found plugin flutter_facebook_auth_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_auth_web-3.1.0\
[  +10 ms] Found plugin google_sign_in at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.3.0\
[   +5 ms] Found plugin google_sign_in_android at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_android-5.2.5\
[   +4 ms] Found plugin google_sign_in_ios at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_ios-5.2.5\
[   +8 ms] Found plugin google_sign_in_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.1\
[  +32 ms] Found plugin sign_in_with_apple at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\sign_in_with_apple-3.3.0\
[   +8 ms] Found plugin sign_in_with_apple_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\sign_in_with_apple_web-1.0.1\
[ +162 ms] Generating C:\F Folder\Let's Code\catat_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +303 ms] Initializing file store
[  +44 ms] Skipping target: gen_localizations
[  +21 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: C:\F Folder\Let's Code\catat_app\.dart_tool\package_config_subset}
[  +43 ms] Found plugin cloud_firestore at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-3.1.14\
[   +8 ms] Found plugin cloud_firestore_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-2.6.14\
[  +11 ms] Found plugin firebase_auth at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-3.3.15\
[   +6 ms] Found plugin firebase_auth_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-3.3.13\
[  +10 ms] Found plugin firebase_core at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.16.0\
[   +7 ms] Found plugin firebase_core_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.6.3\
[   +5 ms] Found plugin flutter_facebook_auth at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_auth-4.3.0\
[   +7 ms] Found plugin flutter_facebook_auth_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_auth_web-3.1.0\
[  +10 ms] Found plugin google_sign_in at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.3.0\
[   +5 ms] Found plugin google_sign_in_android at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_android-5.2.5\
[   +9 ms] Found plugin google_sign_in_ios at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_ios-5.2.5\
[   +9 ms] Found plugin google_sign_in_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.1\
[  +35 ms] Found plugin sign_in_with_apple at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\sign_in_with_apple-3.3.0\
[   +5 ms] Found plugin sign_in_with_apple_web at C:\F Folder\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\sign_in_with_apple_web-1.0.1\
[  +38 ms] gen_dart_plugin_registrant: Complete
[   +5 ms] Skipping target: _composite
[   +8 ms] complete
[  +25 ms] Launching lib\main.dart on Windows in debug mode...
[  +16 ms] C:\F Folder\SDK\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\F Folder\SDK\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root C:\F
Folder\SDK\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\fakhr\AppData\Local\Temp\flutter_tools.1c62f446\flutter_tool.6b37a11d\app.dill --packages C:\F Folder\Let's Code\catat_app\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +99 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[ +114 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +2 ms] []
[   +1 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.VCTools
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[ +108 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.VCTools
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +2 ms] []
[   +1 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -prerelease -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[ +120 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -prerelease -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +3 ms] [
             {
               "instanceId": "8db88f79",
               "installDate": "2022-05-24T02:48:06Z",
               "installationName": "VisualStudioPreview/17.3.0-pre.1.1+32519.111",
               "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community",
               "installationVersion": "17.3.32519.111",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": true,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2022",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.17.Preview",
               "channelUri": "https://aka.ms/vs/17/pre/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installedChannelUri": "https://aka.ms/vs/17/pre/channel",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=661273#17.3.0-pre.1.1",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
               "updateDate": "2022-05-26T11:57:51.854984Z",
               "catalog": {
                 "buildBranch": "d17.3",
                 "buildVersion": "17.3.32519.111",
                 "id": "VisualStudioPreview/17.3.0-pre.1.1+32519.111",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudioPreview",
                 "manifestType": "installer",
                 "productDisplayVersion": "17.3.0 Preview 1.1",
                 "productLine": "Dev17",
                 "productLineVersion": "2022",
                 "productMilestone": "Preview",
                 "productMilestoneIsPreRelease": "True",
                 "productName": "Visual Studio",
                 "productPatchVersion": "0",
                 "productPreReleaseMilestoneSuffix": "1.1",
                 "productSemanticVersion": "17.3.0-pre.1.1+32519.111",
                 "requiredEngineVersion": "3.3.1070.38845"
               },
               "properties": {
                 "campaignId": "2030:abf8ccc7-a7a3-4dba-b24f-c426d24219b1",
                 "channelManifestId": "VisualStudio.17.Preview/17.3.0-pre.1.1+32519.111",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[  +17 ms] Building Windows application...
[  +84 ms] <- compile package:catat_app/main.dart
[   +5 ms] executing: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S C:\F Folder\Let's Code\catat_app\windows -B build\windows -G Visual Studio 17  
2022
[ +378 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.25126.
[ +155 ms] -- Configuring done
[+1023 ms] -- Generating done
[  +97 ms] -- Build files have been written to: C:/F Folder/Let's Code/catat_app/build/windows
[  +48 ms] executing: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --build build\windows --config Debug --target INSTALL --verbose
[+1319 ms] Microsoft (R) Build Engine version 17.3.0-preview-22226-03+b6fc583d4 for .NET Framework
[   +1 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[ +287 ms] Build started 5/27/2022 1:10:57 PM.
[ +759 ms] Project "C:\F Folder\Let's Code\catat_app\build\windows\INSTALL.vcxproj" on node 1 (default targets).
[   +1 ms] Project "C:\F Folder\Let's Code\catat_app\build\windows\INSTALL.vcxproj" (1) is building "C:\F Folder\Let's Code\catat_app\build\windows\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
[   +2 ms] InitializeBuildStatus:
[   +3 ms]   Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[ +107 ms] CustomBuild:
[   +2 ms]   All outputs are up-to-date.
[ +186 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
[   +4 ms] Done Building Project "C:\F Folder\Let's Code\catat_app\build\windows\ZERO_CHECK.vcxproj" (default targets).
[ +268 ms] Project "C:\F Folder\Let's Code\catat_app\build\windows\INSTALL.vcxproj" (1) is building "C:\F Folder\Let's Code\catat_app\build\windows\ALL_BUILD.vcxproj" (3) on node 1 (default targets).
[   +1 ms] Project "C:\F Folder\Let's Code\catat_app\build\windows\ALL_BUILD.vcxproj" (3) is building "C:\F Folder\Let's Code\catat_app\build\windows\runner\catat_app.vcxproj" (4) on node 1 (default targets).
[   +1 ms] Project "C:\F Folder\Let's Code\catat_app\build\windows\runner\catat_app.vcxproj" (4) is building "C:\F Folder\Let's Code\catat_app\build\windows\flutter\flutter_assemble.vcxproj" (5) on node 1 (default targets).  
[   +1 ms] InitializeBuildStatus:
[   +1 ms]   Creating "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +20 ms] CustomBuild:
[   +2 ms]   "The build of 'C:\F Folder\Let's Code\catat_app\build\windows\CMakeFiles\726e8447b42dbe94a3395f8b1d1719eb\flutter_assemble.rule' depends on 'C:\F FOLDER\LET'S
CODE\CATAT_APP\WINDOWS\FLUTTER\EPHEMERAL\FLUTTER_WINDOWS.DLL' which is produced by the build of 'C:\F Folder\Let's Code\catat_app\build\windows\CMakeFiles\70cbdc0ffc8dabc759f7033581ae33e6\flutter_windows.dll.rule'. The items 
cannot be built in parallel."
[ +259 ms]   Generating C:/F Folder/Let's Code/catat_app/windows/flutter/ephemeral/flutter_windows.dll, C:/F Folder/Let's Code/catat_app/windows/flutter/ephemeral/flutter_export.h, C:/F Folder/Let's
Code/catat_app/windows/flutter/ephemeral/flutter_windows.h, C:/F Folder/Let's Code/catat_app/windows/flutter/ephemeral/flutter_messenger.h, C:/F Folder/Let's
Code/catat_app/windows/flutter/ephemeral/flutter_plugin_registrar.h, C:/F Folder/Let's Code/catat_app/windows/flutter/ephemeral/flutter_texture_registrar.h, C:/F Folder/Let's
Code/catat_app/windows/flutter/ephemeral/cpp_client_wrapper/core_implementations.cc, C:/F Folder/Let's Code/catat_app/windows/flutter/ephemeral/cpp_client_wrapper/standard_codec.cc, C:/F Folder/Let's
Code/catat_app/windows/flutter/ephemeral/cpp_client_wrapper/plugin_registrar.cc, C:/F Folder/Let's Code/catat_app/windows/flutter/ephemeral/cpp_client_wrapper/flutter_engine.cc, C:/F Folder/Let's
Code/catat_app/windows/flutter/ephemeral/cpp_client_wrapper/flutter_view_controller.cc, _phony_
[+3367 ms]   [ +197 ms] executing: [C:\F Folder\SDK\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +646 ms]   [ +705 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms]   [   +1 ms] fb57da5f945d02ef4f98dfd9409a72b7cce74268
[   +2 ms]   [   +2 ms] executing: [C:\F Folder\SDK\flutter/] git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[ +360 ms]   [ +361 ms] Exit code 0 from: git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[   +1 ms]   [        ] 3.0.1
[  +28 ms]   [  +28 ms] executing: [C:\F Folder\SDK\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +182 ms]   [ +178 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms]   [        ] origin/stable
[   +1 ms]   [   +1 ms] executing: [C:\F Folder\SDK\flutter/] git ls-remote --get-url origin
[ +160 ms]   [ +166 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms]   [        ] https://github.com/flutter/flutter.git
[ +188 ms]   [ +190 ms] executing: [C:\F Folder\SDK\flutter/] git rev-parse --abbrev-ref HEAD
[ +190 ms]   [ +189 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms]   [        ] stable
[ +246 ms]   [ +248 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +26 ms]   [  +29 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +9 ms]   [   +2 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +3 ms]   [   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms]   [   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms]   [   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +376 ms]   [ +394 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +2 ms]   [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms]   [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[  +14 ms]   [  +17 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +3 ms]   [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms]   [   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +2 ms]   [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +146 ms]   [ +170 ms] Initializing file store
[  +46 ms]   [  +45 ms] Done initializing file store
[ +175 ms]   [ +177 ms] Skipping target: gen_localizations
[  +57 ms]   [  +57 ms] Skipping target: gen_dart_plugin_registrant
[+5046 ms]   [+5046 ms] Skipping target: unpack_windows
[+1943 ms]   [+1944 ms] Skipping target: kernel_snapshot
[  +23 ms]   [  +23 ms] invalidated build due to missing files: C:\F Folder\Let's Code\catat_app\DOES_NOT_EXIST_RERUN_FOR_WILDCARD867939793
[ +927 ms]   [ +928 ms] debug_bundle_windows_assets: Starting due to {InvalidatedReasonKind.inputMissing: The following inputs were missing: C:\F Folder\Let's Code\catat_app\DOES_NOT_EXIST_RERUN_FOR_WILDCARD867939793}
[ +588 ms]   [ +588 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[ +309 ms]   [ +309 ms] debug_bundle_windows_assets: Complete
[ +684 ms]   [ +685 ms] Persisting file store
[  +26 ms]   [  +25 ms] Done persisting file store
[  +22 ms]   [  +21 ms] build succeeded.
[  +31 ms]   [  +32 ms] "flutter assemble" took 10,559ms.
[ +281 ms]   [ +281 ms] ensureAnalyticsSent: 264ms
[   +5 ms]   [   +5 ms] Running shutdown hooks
[   +2 ms]   [   +1 ms] Shutdown hooks complete
[   +8 ms]   [   +8 ms] exiting with code 0
[+1230 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild".
[   +3 ms]   Touching "x64\Debug\flutter_assemble\flutter_assemble.tlog\flutter_assemble.lastbuildstate".
[   +1 ms] Done Building Project "C:\F Folder\Let's Code\catat_app\build\windows\flutter\flutter_assemble.vcxproj" (default targets).
[ +133 ms] Project "C:\F Folder\Let's Code\catat_app\build\windows\runner\catat_app.vcxproj" (4) is building "C:\F Folder\Let's Code\catat_app\build\windows\flutter\flutter_wrapper_app.vcxproj" (6) on node 1 (default
targets).
[   +2 ms] InitializeBuildStatus:
[   +2 ms]   Creating "flutter_wrapper_app.dir\Debug\flutter_.8041E1D2.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[   +6 ms] CustomBuild:
[   +1 ms]   All outputs are up-to-date.
[ +151 ms] ClCompile:
[   +1 ms]   All outputs are up-to-date.
[  +70 ms] Lib:
[   +1 ms]   All outputs are up-to-date.
[   +4 ms]   flutter_wrapper_app.vcxproj -> C:\F Folder\Let's Code\catat_app\build\windows\flutter\Debug\flutter_wrapper_app.lib
[  +50 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "flutter_wrapper_app.dir\Debug\flutter_.8041E1D2.tlog\unsuccessfulbuild".
[   +2 ms]   Touching "flutter_wrapper_app.dir\Debug\flutter_.8041E1D2.tlog\flutter_wrapper_app.lastbuildstate".
[   +2 ms] Done Building Project "C:\F Folder\Let's Code\catat_app\build\windows\flutter\flutter_wrapper_app.vcxproj" (default targets).
**[  +31 ms] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(489,26): error MSB4100: Expected
"$([System.String]::new('%(Link.AdditionalDependencies)').Contains('atls.lib'))" to evaluate to a boolean instead of "$([System.String]::new('..\flutter\Debug\flutter_wrapper_app.lib;C:\F Folder\Let's
Code\catat_app\windows\flutter\ephemeral\flutter_windows.dll.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.lib').Contains('atls.lib'))", in condition     
"'$(ATL_KeyFile)' != '' and ('$(ConfigurationType)' == 'Application' or '$(ConfigurationType)' == 'DynamicLibrary') [C:\F Folder\Let's Code\catat_app\build\windows\runner\catat_app.vcxproj]
[  +11 ms] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(489,26): error MSB4100:                          and %(Link.AdditionalDependencies) != '' and
$([System.String]::new('%(Link.AdditionalDependencies)').Contains('atls.lib'))". [C:\F Folder\Let's Code\catat_app\build\windows\runner\catat_app.vcxproj]
[   +4 ms] Done Building Project "C:\F Folder\Let's Code\catat_app\build\windows\runner\catat_app.vcxproj" (default targets) -- FAILED.
[  +76 ms] Project "C:\F Folder\Let's Code\catat_app\build\windows\ALL_BUILD.vcxproj" (3) is building "C:\F Folder\Let's Code\catat_app\build\windows\flutter\flutter_wrapper_plugin.vcxproj" (7) on node 1 (default targets).**
[   +1 ms] InitializeBuildStatus:
[   +1 ms]   Creating "flutter_wrapper_plugin.dir\Debug\flutter_.4C78F1BE.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[   +7 ms] CustomBuild:
[   +2 ms]   All outputs are up-to-date.
[  +40 ms] ClCompile:
[   +1 ms]   All outputs are up-to-date.
[  +15 ms] Lib:
[   +1 ms]   All outputs are up-to-date.
[   +2 ms]   flutter_wrapper_plugin.vcxproj -> C:\F Folder\Let's Code\catat_app\build\windows\flutter\Debug\flutter_wrapper_plugin.lib
[  +20 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "flutter_wrapper_plugin.dir\Debug\flutter_.4C78F1BE.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "flutter_wrapper_plugin.dir\Debug\flutter_.4C78F1BE.tlog\flutter_wrapper_plugin.lastbuildstate".
[   +2 ms] Done Building Project "C:\F Folder\Let's Code\catat_app\build\windows\flutter\flutter_wrapper_plugin.vcxproj" (default targets).
[   +1 ms] Done Building Project "C:\F Folder\Let's Code\catat_app\build\windows\ALL_BUILD.vcxproj" (default targets) -- FAILED.
[   +3 ms] Done Building Project "C:\F Folder\Let's Code\catat_app\build\windows\INSTALL.vcxproj" (default targets) -- FAILED.
[   +5 ms] Build FAILED.
[   +4 ms] "C:\F Folder\Let's Code\catat_app\build\windows\INSTALL.vcxproj" (default target) (1) ->
[   +1 ms] "C:\F Folder\Let's Code\catat_app\build\windows\ALL_BUILD.vcxproj" (default target) (3) ->
[   +1 ms] "C:\F Folder\Let's Code\catat_app\build\windows\runner\catat_app.vcxproj" (default target) (4) ->
[   +1 ms] (PrepareForBuild target) ->
**[   +1 ms]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(489,26): error MSB4100: Expected
"$([System.String]::new('%(Link.AdditionalDependencies)').Contains('atls.lib'))" to evaluate to a boolean instead of "$([System.String]::new('..\flutter\Debug\flutter_wrapper_app.lib;C:\F Folder\Let's
Code\catat_app\windows\flutter\ephemeral\flutter_windows.dll.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.lib').Contains('atls.lib'))", in condition     
"'$(ATL_KeyFile)' != '' and ('$(ConfigurationType)' == 'Application' or '$(ConfigurationType)' == 'DynamicLibrary') [C:\F Folder\Let's Code\catat_app\build\windows\runner\catat_app.vcxproj]
[   +5 ms] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(489,26): error MSB4100:                          and %(Link.AdditionalDependencies) != '' and
$([System.String]::new('%(Link.AdditionalDependencies)').Contains('atls.lib'))". [C:\F Folder\Let's Code\catat_app\build\windows\runner\catat_app.vcxproj]**
[   +3 ms]     0 Warning(s)
[   +1 ms]     1 Error(s)
[   +2 ms] Time Elapsed 00:00:19.74
[  +72 ms] Building Windows application... (completed in 23.2s)
[+3031 ms] Exception: Build process failed.
[   +5 ms] "flutter run" took 28,770ms.
[  +19 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +134 ms] ensureAnalyticsSent: 124ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

</details>

```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.25126.1000], locale en-US)
    • Flutter version 3.0.1 at C:\F Folder\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (7 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Android
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio Canary\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.0 Preview 1.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32519.111
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Canary
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.68.0-insider)
    • VS Code at C:\Users\fakhr\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.41.20220516

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.25126.1000]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

### PR DESCRIPTION
**Pull request by yaakovschectman**
When running a flutter application for windows in a directory that includes certain problematic characters, e.g. apostrophe('), visual studio would fail and give the fairly unhelpful error message:
`error MSB4100: Expected "$([System.String]::new('%(Link.AdditionalDependencies)').Contains('atls.lib'))" to evaluate to a boolean instead of "$([System.String]`
The build function for Windows now performs a check of the directory for a list of issue-raising characters which, if found, displays a more intuitive error message after exiting early:
`Path ... contains invalid characters in "\'#!\$^&*=|,;<>?". Please rename your directory so as to not include any of these characters and retry.`

Fixes flutter/flutter#104802

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

### CODE REVIEW

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 1]
```diff
@@ -2,6 +2,8 @@
 // Use of this source code is governed by a BSD-style license that can be
 // found in the LICENSE file.
 
+import 'dart:ffi';
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:5]: why did you import dart:ffi?

File: packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart [hunk 2]
```diff
@@ -21,22 +21,24 @@ import '../../src/fakes.dart';
...
+    r'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community';
+const String _cmakePath = visualStudioPath +
+    r'\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe';
 const String _defaultGenerator = 'Visual Studio 16 2019';
 
 final Platform windowsPlatform = FakePlatform(
   operatingSystem: 'windows',
   environment: <String, String>{
     'PROGRAMFILES(X86)':  r'C:\Program Files (x86)\',
-    'FLUTTER_ROOT': flutterRoot,
```
Comment (christopherfujino) [inline packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart:33]: Per our [style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#in-defense-of-the-extra-work-that-hand-formatting-entails), we don't use dart format. please revert all of these formatting changes.

File: packages/flutter_tools/lib/src/windows/build_windows.dart (hunk 1 above)
Comment (yaakovschectman) [reply packages/flutter_tools/lib/src/windows/build_windows.dart]: I did not, it appears VS imported it for reasons I am not sure of. Removed

File: packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart (hunk 2 above)
Comment (yaakovschectman) [reply packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart]: Looks like automatically applied formatting by VS Code. Just went through and manually reset all of these indentations. I believe that should not be an issue going forward now that I disabled "format on save" under "user/dart" in VS Code

Comment (christopherfujino) [reply packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart]: Cool! This might be worth noting on the onboarding doc, as almost everyone's first PR is autoformatted :)

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 3]
```diff
@@ -19,12 +19,23 @@ import '../globals.dart' as globals;
...
 Future<void> buildWindows(WindowsProject windowsProject, BuildInfo buildInfo, {
   String? target,
   VisualStudio? visualStudioOverride,
   SizeAnalyzer? sizeAnalyzer,
 }) async {
+  final String projectPath = windowsProject.parent.directory.absolute.path;
+  final bool badPath = badCharacters.runes
+      .any((int i) => projectPath.contains(String.fromCharCode(i)));
+  if (badPath) {
+    throwToolExit(
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:35]:
```
    throwToolExit('Path $projectPath contains invalid characters in "$badCharacters"');
```

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 4]
```diff
@@ -19,12 +19,23 @@ import '../globals.dart' as globals;
 import '../migrations/cmake_custom_command_migration.dart';
 import 'visual_studio.dart';
 
+/// These characters appear to be fine: @%()-+_{}[]`~
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:22]: This is more of an aside, than official documentation, so only use two slashes (regular comment):

```suggestion
// These characters appear to be fine: @%()-+_{}[]`~
```

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 5]
```diff
@@ -19,12 +19,23 @@ import '../globals.dart' as globals;
...
   String? target,
   VisualStudio? visualStudioOverride,
   SizeAnalyzer? sizeAnalyzer,
 }) async {
+  final String projectPath = windowsProject.parent.directory.absolute.path;
+  final bool badPath = badCharacters.runes
+      .any((int i) => projectPath.contains(String.fromCharCode(i)));
+  if (badPath) {
+    throwToolExit(
+        'Path $projectPath contains invalid characters in "$badCharacters"');
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:36]: Is there some documentation and/or more context we can give the user about how to fix? A lot of times users will see a crash and then immediately copy paste it and file a bug asking for help.

File: packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart [hunk 6]
```diff
@@ -933,6 +935,30 @@ if %errorlevel% neq 0 goto :VCEnd</Command>
     FileSystemUtils: () => FileSystemUtils(fileSystem: fileSystem, platform: windowsPlatform),
     Usage: () => usage,
   });
+
+  /// Confirms that running for Windows in a directory with a
```
Comment (christopherfujino) [inline packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart:939]: This can be two slash comments, don't need to dartdoc tests

File: packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart [hunk 7]
```diff
@@ -933,6 +935,30 @@ if %errorlevel% neq 0 goto :VCEnd</Command>
...
+  testUsingContext('Test bad path characters', () async {
+    final FakeVisualStudio fakeVisualStudio = FakeVisualStudio();
+    final BuildWindowsCommand command = BuildWindowsCommand()
+      ..visualStudioOverride = fakeVisualStudio;
+    fileSystem.currentDirectory = fileSystem.directory("test_'path")
+      ..createSync();
+    final String absPath = fileSystem.currentDirectory.absolute.path;
+    setUpMockCoreProjectFiles();
+
+    expect(
```
Comment (christopherfujino) [inline packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart:950]: formatting should be something like:

```dart
    expect(
      createTestCommandRunner(command).run(const <String>['windows', '--no-pub']),
      throwsToolExit(
        message: 'Path $absPath contains invalid characters in "\'#!\$^&*=|,;<>?"',
      ),
    );
```

File: packages/flutter_tools/lib/src/windows/build_windows.dart (hunk 3 above)
Comment (yaakovschectman) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:35]: What is the difference? The newline?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:35]: yes, this formatting does not follow Flutter's style guide https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#formatting

File: packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart [hunk 8]
```diff
@@ -933,6 +935,32 @@ if %errorlevel% neq 0 goto :VCEnd</Command>
     FileSystemUtils: () => FileSystemUtils(fileSystem: fileSystem, platform: windowsPlatform),
     Usage: () => usage,
   });
+
+  // Confirms that running for Windows in a directory with a
+  // bad caracter (' in this case) throws the desired error message
```
Comment (loic-sharma) [inline packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart:940]:
```suggestion
  // bad character (' in this case) throws the desired error message
```

Comment (loic-sharma) [inline packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart:940]: If whoever is responsible (CMake or Visual Studio) ever fixes this bug, we should remove the check & this test. I would consider adding a link to [the issue](https://github.com/flutter/flutter/issues/104802) in this comment for our own future reference.

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 9]
```diff
@@ -19,12 +19,25 @@ import '../globals.dart' as globals;
...
+// These characters appear to be fine: @%()-+_{}[]`~
+const String badCharacters = r"'#!$^&*=|,;<>?";
+
 /// Builds the Windows project using msbuild.
 Future<void> buildWindows(WindowsProject windowsProject, BuildInfo buildInfo, {
   String? target,
   VisualStudio? visualStudioOverride,
   SizeAnalyzer? sizeAnalyzer,
 }) async {
+  final String projectPath = windowsProject.parent.directory.absolute.path;
```
Comment (loic-sharma) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:31]: In the future, it'll be difficult to remember *why* this check exists without looking at the commit history. I would add a quick comment about how CMake generates MSBuild files that does not properly escape the paths. Consider also adding a link to the issue.

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 10]
```diff
@@ -19,12 +19,28 @@ import '../globals.dart' as globals;
 import '../migrations/cmake_custom_command_migration.dart';
 import 'visual_studio.dart';
 
+// These characters appear to be fine: @%()-+_{}[]`~
+const String badCharacters = r"'#!$^&*=|,;<>?";
```
Comment (loic-sharma) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:23]: Style is to prefix constants with `k` and to keep things private if possible:

```suggestion
const String _kBadCharacters = r"'#!$^&*=|,;<>?";
```

See: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#begin-global-constant-names-with-prefix-k

**Review by loic-sharma — APPROVED** [review]
Looks good, nice work!
