### PR TITLE
Apply media bottom padding in BottomNavigationBar

### LINKED ISSUE #12099: iPhone X: Additional bottom padding for BottomNavigationBar
## Steps to Reproduce

On the iPhone X, `BottomNavigationBar` should include additional bottom padding to avoid placing `BottomNavigationBarItem`s under the indicator for accessing the Home screen.

See Apple's [Human Interface Guidelines for iPhone X](https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x).

Dependent on issue #12098

Example:
screen shot 2017-09-12 at 15 21 34

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-AU, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision dd7e313317 (51 minutes ago), 2017-09-14 12:28:21 -0700
    • Engine revision 57a1445a45
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/cbracken/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode9.0.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1
```

### PR DESCRIPTION
**Pull request by cbracken**
Updates scaffold to expose bottom padding to the associated
BottonNavigationBar (if present). BottomNavigationBar is now responsible
for adjusting itself to account for bottom padding.

This change is necessary to support the updated BottomNavigationBar
layout for the iPhone X.

Fixes flutter/flutter#12099 once the associated engine roll lands.

### CODE REVIEW

File: packages/flutter/lib/src/material/scaffold.dart [hunk 1]
```diff
@@ -930,6 +933,7 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
         removeLeftPadding: false,
         removeTopPadding: true,
         removeRightPadding: false,
+        removeBottomPadding: false,
```
Comment (xster) [inline packages/flutter/lib/src/material/scaffold.dart]: bah, github doesn't let me comment on unchanged lines. You'd want to remove the bottom padding from the body now no? Since it's 'consumed'.

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 2]
```diff
@@ -436,6 +436,8 @@ class _BottomNavigationBarState extends State<BottomNavigationBar> with TickerPr
   @override
   Widget build(BuildContext context) {
     assert(debugCheckHasDirectionality(context));
+
+    final double bottomPadding = math.max(MediaQuery.of(context).padding.bottom - _kBottomMargin, 0.0);
```
Comment (cbracken) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart]: FWIW: not entirely thrilled with this. An alternative would be to deal with this in the individual item widgets where we deal with bottom margin. Ideas welcome :)

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (cbracken) [reply packages/flutter/lib/src/material/scaffold.dart]: The body already does remove the bottom padding if necessary (line 861). Bottom padding removal is defaulted to `widget.resizeToAvoidBottomPadding` in `_addIfNonNull()`

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 2 above)
Comment (xster) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart]: I think consolidating here is fine. Though some comment / const renaming might help future readers. Something like we only need to shift up if the partial obstruction may intersect with interactive parts of this widget, liberally generalized by this const (feel free to do all this in a different PR).

Comment (xster) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart]: Maybe the 2 names needs some additional differentiation too. They're both called bottom padding which is a bit confusing when one is a outer container padding and one is an inner layout padding.

File: packages/flutter/test/material/bottom_navigation_bar_test.dart [hunk 3]
```diff
@@ -65,6 +65,35 @@ void main() {
...
+                )
+              ]
+            )
+          )
+        )
+      )
+    );
+
+    const double labelBottomMargin = 8.0; // _kBottomMargin in implementation.
+    const double additionalPadding = 40.0 - labelBottomMargin;
```
Comment (xster) [inline packages/flutter/test/material/bottom_navigation_bar_test.dart]: <not a real comment>Ha, you even called this 'additional' padding here :)</>

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (xster) [reply packages/flutter/lib/src/material/scaffold.dart]: If in the ultimate future, resizeToAvoidBottomPadding is gone, don't we still need to explicitly set removebottompadding to true if bottom tab bar != null?

**Comment by xster** [comment]
LGTM, feel free to respond/address everything in a separate PR if this unblocks you

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (cbracken) [reply packages/flutter/lib/src/material/scaffold.dart]: In the future the padding is the safe area padding so we don't want to remove it, we want the nav bar to adapt itself for the additional padding.

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 2 above)
Comment (cbracken) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart]: Good point. I'll update the names.

Comment (cbracken) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart]: Done.

File: packages/flutter/test/material/bottom_navigation_bar_test.dart (hunk 3 above)
Comment (cbracken) [reply packages/flutter/test/material/bottom_navigation_bar_test.dart]: Stole the name and used it in place of `bottomPadding` internally.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (cbracken) [reply packages/flutter/lib/src/material/scaffold.dart]: Done in #13437

**Comment by cbracken** [comment]
Switching over to viewInsets and making `removeBottomPadding` required done in #13437.
