### PR TITLE
[material/menu_anchor.dart] Create internal menu controller if external controller is changed to null.

### LINKED ISSUE #176374: [material/menu_anchor.dart] Internal menu controller is not created when external menu controller is removed.
### Steps to reproduce

Just came across a bug I introduced. I'll get the fix in ASAP

1. Run example
2. Tap "Toggle Controller"

### Expected results

An internal menu controller should be created and no error should be thrown.

### Actual results

Throws "Null check operator used on a null value" because an internal menu controller is not created.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main(List<String> args) {
  runApp(const App());
}

class App extends StatefulWidget {
  const App({super.key});

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  final MenuController menuController = MenuController();
  bool isControllerAttached = true;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Material(
        child: MenuAnchor(
          controller: isControllerAttached ? menuController : null,
          menuChildren: const <Widget>[
            Text('Item'),
          ],
          builder: (BuildContext context, MenuController controller, Widget? child) {
            return Center(
              child: ElevatedButton(
                onPressed: () {
                  setState(() {
                    isControllerAttached = !isControllerAttached;
                  });
                },
                child: const Text('Toggle Controller'),
              ),
            );
          },
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.35.5, on macOS 15.5 24F74 darwin-arm64, locale en-US) [242ms]
    • Flutter version 3.35.5 on channel stable at /Users/davidhicks/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ac4e799d23 (5 days ago), 2025-09-26 12:05:09 -0700
    • Engine revision d3d45dcf25
    • Dart version 3.9.2
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-lldb-debugging

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [1,754ms]
    • Android SDK at /Users/davidhicks/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 35.0.0
    • ANDROID_HOME = /Users/davidhicks/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [1,129ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [8ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.103.2) [7ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.120.0

[✓] Connected device (3 available) [10.0s]
    • iPhone 16 Pro (mobile) • 202ED8C0-7DDC-4EB3-91F7-A3C2180AE01E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 140.0.7339.214
    ! Error: Browsing on the local area network for David’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [189ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.```

</details>

### PR DESCRIPTION
**Pull request by davidhicks980**
When removing a MenuController from a MenuAnchor, an internal MenuController was not being made. 

image

My bad for introducing the bug! 

Fixes https://github.com/flutter/flutter/issues/176374

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 1]
```diff
@@ -364,7 +364,11 @@ class _MenuAnchorState extends State<MenuAnchor> {
   void didUpdateWidget(MenuAnchor oldWidget) {
     super.didUpdateWidget(oldWidget);
     if (oldWidget.controller != widget.controller) {
-      _internalMenuController = widget.controller != null ? MenuController() : null;
+      if (widget.controller == null) {
+        _internalMenuController = MenuController();
+      } else {
+        _internalMenuController = null;
+      }
```
[the remark this answers is not in the document]
Comment (davidhicks980) [reply packages/flutter/lib/src/material/menu_anchor.dart:371]: I find it easier to read blocks, which may be why I introduced the bug in the first place 😞

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 2]
```diff
@@ -364,7 +364,11 @@ class _MenuAnchorState extends State<MenuAnchor> {
   void didUpdateWidget(MenuAnchor oldWidget) {
     super.didUpdateWidget(oldWidget);
     if (oldWidget.controller != widget.controller) {
-      _internalMenuController = widget.controller != null ? MenuController() : null;
+      if (widget.controller == null) {
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/menu_anchor.dart:367]: While this is ok, I find the following logic slightly easier to understand:

Change `MenuController get _menuController` this way:
```dart
  MenuController get _menuController {
     if (widget.controller != null)
        return widget.controller;
     return _internalMenuController ??= MenuController();
  }
```

Then change `didUpdateWidget` this way:
```dart
  @override
  void didUpdateWidget(MenuAnchor oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.controller != widget.controller) {
      // Use a separate line to rebuild _internalMenuController when necessary
      final MenuController effectiveController = _menuController;
      if (effectiveController != _internalMenuController)
        _internalMenuController = null;
    }
  }
```

What do you think?

**Review by dkwingsmt — APPROVED** [review]
LGTM, thank you!

File: packages/flutter/lib/src/material/menu_anchor.dart (hunk 2 above)
Comment (davidhicks980) [reply packages/flutter/lib/src/material/menu_anchor.dart:367]: I find the update a little harder to follow since it requires jumping between two parts of the code and adds an additional variable (effectiveController). But, that could be because I'm looking at it with fresh eyes.

Not that performance is too concerning in this situation, but wouldn't `_internalMenuController ??= MenuController();` require an additional null check every time `_menuController` is accessed?

Either way, your call! I don't mind as long as I fix the bug I introduced 😅

Comment (davidhicks980) [reply packages/flutter/lib/src/material/menu_anchor.dart:367]: I'll go ahead and merge, but let me know if you want me to update this later!
