### PR TITLE
Prevent exception being thrown on hasScrolledBody

### LINKED ISSUE #28351: NestedScrollCoordinator: The method '>' was called on null
I get his Exception occasionally when opening the app:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19651): The following NoSuchMethodError was thrown building Builder(dirty):
I/flutter (19651): The method '>' was called on null.
I/flutter (19651): Receiver: null
I/flutter (19651): Tried calling: >()
I/flutter (19651):
I/flutter (19651): When the exception was thrown, this was the stack:
I/flutter (19651): #0      _NestedScrollCoordinator.get:hasScrolledBody (package:flutter/src/widgets/nested_scroll_view.dart:493)
I/flutter (19651): #1      _NestedScrollViewState.build.<anonymous closure> (package:flutter/src/widgets/nested_scroll_view.dart:339)
I/flutter (19651): #2      Builder.build (package:flutter/src/widgets/basic.dart:5736)
I/flutter (19651): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774)
I/flutter (19651): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721)
I/flutter (19651): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3547)
I/flutter (19651): #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286)
I/flutter (19651): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676)
I/flutter (19651): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219)
I/flutter (19651): #9      _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
I/flutter (19651): #10     _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
I/flutter (19651): #11     _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751)
I/flutter (19651): #13     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382)
I/flutter (19651): #14     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416)
I/flutter (19651): #15     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171)
I/flutter (19651): (elided one frame from package dart:async)
I/flutter (19651): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
I can't seem to figure out a pattern when it happens, all I have is this Exception that doesn't really tells me much, so I decided to post it here in hope that someone might know what this could cause.

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale de-DE)
    • Flutter version 1.0.0 at /Users/jonas/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jonas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jonas/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[!] IntelliJ IDEA Community Edition (version 2018.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.
```

### LINKED ISSUE #31195: Exception:  'toDouble' was called on null' on IOS
## Steps to Reproduce

1. `flutter run -t lib/main_prod.dart`
2. Exception appears and disappears as soon as the app loads/builds properly
3. This only happens on iOS device.
4. Project available here >> https://github.com/JuliusNM/Frecipe

## Logs
```
[ +201 ms] flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] flutter: The following NoSuchMethodError was thrown building Builder(dirty, dependencies: [MediaQuery]):
[        ] flutter: The method 'toDouble' was called on null.
[        ] flutter: Receiver: null
[        ] flutter: Tried calling: toDouble()
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[  +49 ms] flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
[        ] flutter: #1      double.> (dart:core-patch/double.dart:87:31)
[        ] flutter: #2      _NestedScrollCoordinator.hasScrolledBody (package:flutter/src/widgets/nested_scroll_view.dart:501:27)
[   +7 ms] flutter: #3      _NestedScrollViewState.build.<anonymous closure> (package:flutter/src/widgets/nested_scroll_view.dart:344:47)
[   +1 ms] flutter: #4      Builder.build (package:flutter/src/widgets/basic.dart:6233:41)
[        ] flutter: #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
[        ] flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
[        ] flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #8      StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
[        ] flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #12     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #16     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[   +6 ms] flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #24     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #26     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
[        ] flutter: #27     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
[        ] flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #39     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #45     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
[        ] flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #51     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #55     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #59     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #63     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #67     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #71     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #75     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #81     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
[        ] flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #85     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[   +1 ms] flutter: #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #87     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
[        ] flutter: #88     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
[        ] flutter: #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #92     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #94     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[   +3 ms] flutter: #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #98     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #100    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #104    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #106    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[   +1 ms] flutter: #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[   +5 ms] flutter: #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[   +1 ms] flutter: #110    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[   +1 ms] flutter: #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #114    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
[        ] flutter: #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #118    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[   +1 ms] flutter: #120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[   +2 ms] flutter: #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[   +1 ms] flutter: #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[   +1 ms] flutter: #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[   +1 ms] flutter: #124    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[   +1 ms] flutter: #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[  +52 ms] flutter: #126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #130    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] flutter: #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #134    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
[        ] flutter: #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #136    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] flutter: #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[        ] flutter: #140    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] flutter: #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
[        ] flutter: #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
[        ] flutter: #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
[+1260 ms] flutter: #144    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
[   +4 ms] flutter: #145
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:700:20)
[        ] flutter: #146
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:286:5)
[        ] flutter: #147    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1012:15)
[   +4 ms] flutter: #148    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:952:9)
[        ] flutter: #149    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure>
(package:flutter/src/scheduler/binding.dart:773:7)
[        ] flutter: #158    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
[        ] flutter: #159    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
[   +4 ms] flutter: #160    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
[        ] flutter: (elided 8 frames from package dart:async and package dart:async-patch)
[   +3 ms] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] flutter: Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
[ +471 ms] Scanned through 0 files in 0ms
[   +1 ms] Syncing files to device Julius Mburu’s iPhone...
[   +1 ms] Scanning asset files
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +9 ms] /Users/julius/development/flutter/bin/cache/dart-sdk/bin/dart
/Users/julius/development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/julius/development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build/app.dill --packages
/Users/julius/AndroidStudioProjects/frecipe/.packages --filesystem-scheme org-dartlang-root
[  +10 ms] <- compile package:Frecipe/main_prod.dart
```
```
```

`flutter analyze`
No issues found! (ran in 65.3s)

```
```

`flutter doctor -v`

[✓] Flutter (Channel master, v1.5.2-pre.3, on Mac OS X 10.13.6 17G6030, locale en-KE)
    • Flutter version 1.5.2-pre.3 at /Users/julius/development/flutter
    • Framework revision ca46fc03de (11 hours ago), 2019-04-16 22:27:18 -0400
    • Engine revision 388124f948
    • Dart version 2.3.0 (build 2.3.0-dev.0.0 8e73b3c006)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/julius/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Julius Mburu’s iPhone • 00032057848b762b448d1a0b36cf672226e6ecf9 • ios • iOS 12.1.3

• No issues found!

```
```

### PR DESCRIPTION
**Pull request by kpsroka**
## Description

Fixes #31195, by introducing a null check in `hasScrolledBody` of `_NestedScrollCoordinator`.

The root cause of the issue is that the `position.minScrollExtent` returns null, and the comparison operator trying to cast the value to `toDouble` on it causes exception to be thrown.

This occurs as a result of [`scheduleWarmUpFrame`](https://docs.flutter.io/flutter/scheduler/SchedulerBinding/scheduleWarmUpFrame.html) causing a cascade of `updateChild` calls. Eventually this reaches a `NestedScrollViewState`'s `build` method.

The bug is likely more due to the `scheduleWarmUpFrame` being run with some assumptions that do not hold. The `_minScrollExtent` of `_NestedScrollPosition` that back NestedScrollView is initialized with null, and updated to a double value in [`applyContentDimensions`](https://docs.flutter.io/flutter/widgets/ScrollPosition/applyContentDimensions.html). That, in turn, is executed by cascaded [`layout`](https://docs.flutter.io/flutter/rendering/RenderObject/layout.html) calls, which happens only after the `scheduleWarmUpFrame` finishes.

It is likely that the bug has a better solution, but I'd need some guidance on resolving this in another way.

## Related Issues

Fixes #31195 
Fixes #28351

## Tests

I added the following tests:

I'd love to know how to reproduce this in a test environment (including fake 'warmUp' frame).

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by dnfield** [comment]
Thanks for this!

I'm wondering if this is really the right fix.  There are a lot of places in the framework that assume `minScrollExtent` is not null, and would throw a similar exception if it were.

I suspect the intent of marking `minScrollExtent` as required in `_NestedScrollViewController`'s constructor was to mean it also shouldn't be null, but there's no assert.  What if we were to add an assert, and figure out who is calling it with `null`, and make sure they call it with something sensible (like perhaps `0.0`)?

**Review by dnfield — DISMISSED** [review]
As mentioned in the comment, I suspect we just shouldn't let this be null rather than allowing it to be null in this one special case.

**Comment by kpsroka** [comment]
@dnfield Both `_minScrollExtent` and `_maxScrollExtent` are [being uninitialized in `ScrollPosition`](https://github.com/flutter/flutter/blob/802eca29d212856ba5cf98aae535dfbc982ef32a/packages/flutter/lib/src/widgets/scroll_position.dart#L112-L117). The documentation for these can be found in [ScrollMetrics](https://github.com/flutter/flutter/blob/d927c9331005f81157fa39dff7b5dab415ad330b/packages/flutter/lib/src/widgets/scroll_metrics.dart#L59-L72).

Given that the permitted values can be also -/+ infinity, it might be actually good to change the getters of these fields to return -/+ infinity if they are not being set?* I'll check what effect this will have, but after looking at the code, I believe this will retain the current behaviour of null where nulls are accepted, and otherwise won't change the behaviour. WDYT?

_* or perhaps initialize them with infinities -- I'm not sure what's the code style around these cases_

**Comment by kpsroka** [comment]
I've updated the PR with the changes I suggested above, PTAL.

Looking through the code I've also noticed that [FixedScrollMetrics]( https://github.com/flutter/flutter/blob/d927c9331005f81157fa39dff7b5dab415ad330b/packages/flutter/lib/src/widgets/scroll_metrics.dart#L120) should also probably have an assertion on the min-/maxScrollExtent params. However, this _can_ be breaking for some clients (though the usage with nulls might not necessarily be useful).

**Comment by dnfield** [comment]
They get set in the consturctor for _NestedScrollView no?

**Comment by kpsroka** [comment]
> They get set in the consturctor for _NestedScrollView no?

I'm afraid that I don't know which  _they_ you are referring to.

**Comment by dnfield** [comment]
Sorry, not being clear.  I'll take a look when not on mobile :)

**Comment by dnfield** [comment]
I was mixing up the constructor for `_NestedScrollMetrics` with `_NestedScrollView`.

I suspect the fix here is to default the min and max scroll extents to _something_, but I suspect 0.0 is a safer default than double.infinity (or double.negativeInfinity). It also may be the case that we don't need to default it, we just need to figure out why someone is failing to properly initialize it. Either way, it seems allowing it to ever be null could potentialy cause problems all over the place.  

@goderbauer might know better but he's out right now.  I'll poke at it a little more in the mean time.

**Comment by kpsroka** [comment]
Two nits/thoughts:
 - wrt `FixedScrollMetrics` constructor (and inheriting `_NestedScrollMetrics`): the *extent params are `@required`, but their value is not asserted upon (the analyzer doesn't require the `@required` args to be non-null, right?). That's why adding an assertion might be _breaking_ (though I doubt that it serves a purpose to initialize them with null).
 - In common case of finite scroll content, the `minScrollExtent` will be most likely set to zero upon first `layout`. However, I don't think there's going to be any difference in the way the NestedScrollView works.

**Comment by dnfield** [comment]
Had a quick chat with @Hixie  about this - he's suggesting we shouldn't default it, as that could cause some bad behavior in other places.

Basically, we need to figure out who is initializing or trying to use NestedScrollController before it's actually ready for use.  Then we need to either make sure it's properly initialized at that point, or we need to make sure the lifecycle is making sense and not trying to use something it's not supposed to.

**Comment by kpsroka** [comment]
I've added a test for the bug in `nested_scroll_view_test.dart`. You can find the minimal repro I could achieve at https://gist.github.com/kpsroka/02d1bfd1ce9faedb92f4aa56f3e23b4a

**Comment by kpsroka** [comment]
OK, After investigating the repro I think I know what's happening:
 1. `NestedScrollView` makes use -- through `_NestedScrollCoordinator` -- of two instances of `_NestedScrollController`: inner, and outer. Both of them hold a list of `ScrollPosition`s. These lists are being mutated through `attach` and `detach` methods.
 1. The inner instance is passed in the `_buildSlivers` method to the body of `NestedScrollView` using the `PrimaryScrollController` inherited widget.
 1. If the body of the `NestedScrollView` extends `Scrollable`, upon first build (on `attachRootWidget` it will execute `didChangeDependencies` and `_updatePosition()`, which in turn calls attach() on  the supplied inner controller, with a newly created ScrollPosition. That position's min/maxScrollExtent are initially set to `null`.
 1 . The attached position's min/maxScrollExtent are going to be updated in the next layout() phase. However, it will not happen before the `scheduleWarmUpFrame` executes another `build` method. 
 1. If the widget tree contains `_ModalScope` (e.g. via `MaterialPageRoute`), it is being marked as dirty after the initial build (through `NavigatorState.didUpdateWidget()`).
 1. The next build phase (before the first layout phase) triggers the crash when `NestedScrollView` reaches its build().

Now, the questions is: what shouldn't happen? :)

**Comment by kpsroka** [comment]
Note: I realized that the test that I wrote doesn't follow the same path that production code does -- it might be related to the placeholder being present in tests, or some binding overrides.

**Comment by dnfield** [comment]
Thanks for the detailed explanation!

This part seems strange to me:

>The attached position's min/maxScrollExtent are going to be updated in the next layout() phase. However, it will not happen before the scheduleWarmUpFrame executes another build method.

Are you saying that the build method call here skips a layout?

**Comment by kpsroka** [comment]
> Thanks for the detailed explanation!
> 
> This part seems strange to me:
> 
> > The attached position's min/maxScrollExtent are going to be updated in the next layout() phase. However, it will not happen before the scheduleWarmUpFrame executes another build method.
> 
> Are you saying that the build method call here skips a layout?

I assumed it doesn't, since it looks like on layout, the scroll extents should get updated unconditionally. I'll verify that later today.

**Comment by kpsroka** [comment]
> Thanks for the detailed explanation!
> 
> This part seems strange to me:
> 
> > The attached position's min/maxScrollExtent are going to be updated in the next layout() phase. However, it will not happen before the scheduleWarmUpFrame executes another build method.
> 
> Are you saying that the build method call here skips a layout?

The initial build (caused by `attachRootWidget`) is not triggered via frame callbacks, but rather by [this `mount` call](https://github.com/flutter/flutter/blob/a8116e9ea3dd21eb450c1c00780f1985e1f33967/packages/flutter/lib/src/widgets/binding.dart#L850), which causes a series of update -> inflate -> mount -> build calls. Afterwards the warm up frame proceeds with another build cycle before it gets to the layout phase.

**Comment by kpsroka** [comment]
@dnfield Any idea how to proceed with that?

**Comment by Hixie** [comment]
If there's any part of the framework or test framework that causes us to go through a build cycle before the corresponding layout cycle, that's the bug we should track down and fix. The only times that should happen is when you've explicitly told the test framework to only go as far as build, and that's quite rare.

**Comment by dnfield** [comment]
It seems like the problem here is that `scheduleWarmupFrame` may be getting to a second build before the first layout completes.  Do you think that's the case @kpsroka?

**Comment by kpsroka** [comment]
I believe that what happens is that the initial [mount()](https://github.com/flutter/flutter/blob/a8116e9ea3dd21eb450c1c00780f1985e1f33967/packages/flutter/lib/src/widgets/binding.dart#L850) of the root component causes build that's not followed by layout, but by another build from the warm up frame.

**Comment by dnfield** [comment]
Can you try this with setting `debugPrintBeginFrameBanner` and `debugPrintEndFrameBanner` set to true?  That may help narrow down what's getting called when.

**Comment by kpsroka** [comment]
I'll get back to you next week, my Mac decided to get broken, and I can't repro this on an Android. (This itself is somewhat strange, but I guess more debugging will figure this out)

**Comment by kpsroka** [comment]
I've compiled logs from several runs. Apart from a physical device (Samsung Galaxy J7 running Oreo 8.1), All seem to have similar pattern on execution. See https://gist.github.com/kpsroka/b3bf0607ac81cd2a2434a055f57c2cd1

**Comment by kpsroka** [comment]
Some more digging -- you can notice two extra files in the gist, using `debugPrintBuildScope` to obtain what gets built in either crash and no-crash scenarios. The difference between the two is that when the crash occurs, the `WidgetsApp` is on the dirty elements list after the initial `attachToRoot()` call.

The WidgetsApp then schedules build for `_ModalScope`. Below you can find the call stack that ends up in having `WidgetsApp` on the dirty list.

```
Runner: flutter: scheduleBuildFor() called for WidgetsApp-[GlobalObjectKey _MaterialAppState#b0677](dirty, state: _WidgetsAppState#22c83)
Runner: flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:707:39)
Runner: flutter: #1      BuildOwner.scheduleBuildFor.<anonymous closure> (package:flutter/src/widgets/framework.dart:2157:9)
Runner: flutter: #2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2171:6)
Runner: flutter: #3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3617:11)
Runner: flutter: #4      State.setState (package:flutter/src/widgets/framework.dart:1143:14)
Runner: flutter: #5      _WidgetsAppState.didChangeTextScaleFactor (package:flutter/src/widgets/app.dart:1016:5)
Runner: flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.handleTextScaleFactorChanged (package:flutter/src/widgets/binding.dart:411:16)
Runner: flutter: #10     _invoke (dart:ui/hooks.dart:220:10)
Runner: flutter: #11     _updateTextScaleFactor (dart:ui/hooks.dart:104:3)
Runner: flutter: #12     _updateUserSettingsData (dart:ui/hooks.dart:87:3)
Runner: flutter: (elided 3 frames from package dart:async)
Runner: flutter: ...dirty list is now: [FocusScope(AUTOFOCUS, node: FocusScopeNode#4d68e, dirty, state: _FocusScopeState#4e5ea), _FocusMarker(dirty), WidgetsApp-[GlobalObjectKey _MaterialAppState#b0677](dirty, state: _WidgetsAppState#22c83)]
```

That said, the above doesn't look like an _illegal_ call. The fault lies in `buildScope` being called twice before first layout, the first time through [`attachToRenderTree`](https://github.com/flutter/flutter/blob/63aa5b3647dbd912a02f7545fc0101003cb3adc4/packages/flutter/lib/src/widgets/binding.dart#L849), the second time through [`drawFrame`](https://github.com/flutter/flutter/blob/63aa5b3647dbd912a02f7545fc0101003cb3adc4/packages/flutter/lib/src/widgets/binding.dart#L700) during the warm up frame.

**Comment by kpsroka** [comment]
Note: I tried adding a `performLayout` call after the root widget is initialized (and goes through the first build), but that causes a lot of tests to fail. Maybe the solution is not to build the widget tree during `attachToRenderTree`? I can try that, but I believe it will cause even more failures.

**Comment by kpsroka** [comment]
@dnfield @Hixie Any idea how to proceed with this?

In essence, the initial `attachRootWidget` causes one build to happen, although this is done in a `buildScope` callback, which nullifies marking widgets for build. However, before the warm up frame starts some async hooks get fired, causing widgets to be marked dirty, and the warm up frame begins with building these (before the layout). I guess the timers being run is the effect of wrapping drawFrame* calls in `Timer.run()` -- see below: https://github.com/flutter/flutter/blob/63aa5b3647dbd912a02f7545fc0101003cb3adc4/packages/flutter/lib/src/scheduler/binding.dart#L767

Now, I can force the RendererBinding to run its `drawFrame()` before the warm up frame starts, but it's not very clean - and some tests fail when I try to do this.

**Comment by dnfield** [comment]
I'm not sure I'm fully understanding this, but is it possible that we just need `scheduleWarmupFrame` to fizzle if there's already a frame in progress?

Alternatively, does it help to move that `lockEvents` up higher in the warmup frame body so that we don't get anything else interfering?

**Comment by kpsroka** [comment]
Thanks! I went with moving the event lock higher, and modifying it slightly. I'll still need to verify this works ok on iOS - but that's something for (my) tomorrow.

**Comment by kpsroka** [comment]
Unfortunately, the problem still persists (at least with the iOS simulator).

File: packages/flutter/lib/src/scheduler/binding.dart [hunk 1]
```diff
@@ -781,16 +791,10 @@ mixin SchedulerBinding on BindingBase, ServicesBinding {
...
       if (hadScheduledFrame)
         scheduleFrame();
     });
-
-    // Lock events so touch events etc don't insert themselves until the
-    // scheduled frame has finished.
-    lockEvents(() async {
-      await endOfFrame;
-      Timeline.finishSync();
-    });
```
Comment (Hixie) [inline packages/flutter/lib/src/scheduler/binding.dart]: as far as i can tell, this patch shouldn't change the behaviour at all. endOfFrame is completed pretty much at the same time as handleDrawFrame ends, if I remember correctly.

Comment (kpsroka) [reply packages/flutter/lib/src/scheduler/binding.dart]: Actually, what would change is that we wouldn't unnecessarily schedule a frame, as `endOfFrame` is a [non-trivial getter](https://github.com/flutter/flutter/blob/16ff0b0da462175d5fd61c94d5134a6c131e2133/packages/flutter/lib/src/scheduler/binding.dart#L611-L623), that does schedule a frame. But for the bug it would not have any effect.

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 2]
```diff
@@ -498,7 +498,7 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
 
   bool get hasScrolledBody {
     for (_NestedScrollPosition position in _innerPositions) {
-      if (position.pixels > position.minScrollExtent)
+      if (position.minScrollExtent != null && position.pixels > position.minScrollExtent)
```
Comment (JuliusNM) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart]: This seems to fix my issue. I will proceed to use it as a workaround in the meantime

**Comment by dnfield** [comment]
Ok.  Here's the sequence that seems to cause this:

1. The root widget is attached and fires an initial build.
2. A warm up frame is scheduled.  It starts its work and flushes the microtask queue.
3. The engine finds out the platform brightness and text scale settings, and sends those down to the window (adding to the microtask queue).
4. The microtask flush in the middle of scheduling the warmup frame again marks the tree as dirty.
5. As the warmup frame continues to make progress, the scroll controller is in a bad state.  It thinks it's been sucessfully built and laid out previously, and so it should be safe to access the metrics - however, the layout hasn't happened yet even though we're marked dirty again.

So our two options are:

- Make scroll metrics tolerant of this case. The risk is that we end up hiding lifecycle issues this way.
- Somehow make the warmup frame finish before processing the setState call for the platformbrightness/textscale notification(s).

**Comment by dnfield** [comment]
Discussed this elsewhere, but one possibility for this is to update the RendererBinding to override the `scheduleWarmupFrame`.  It could then wrap the `super.scheduleWarmupFrame` with something to let the renderer binding know that it should defer callbacks coming from the engine to a queue.  Once the `super.scheduleWarmUpFrame()` is done, it could then flush that queue and go back to sending them immediately.

File: packages/flutter/lib/src/widgets/binding.dart [hunk 3]
```diff
@@ -399,30 +399,38 @@ mixin WidgetsBinding on BindingBase, SchedulerBinding, GestureBinding, RendererB
 
   @override
   void handleMetricsChanged() {
-    super.handleMetricsChanged();
-    for (WidgetsBindingObserver observer in _observers)
-      observer.didChangeMetrics();
+    afterWarmUpFrame(() {
```
Comment (dnfield) [inline packages/flutter/lib/src/widgets/binding.dart]: I think this won't be robust enough - we'll eventually add some new `handle` call, or another implementer of the binding would potentially dirty the tree in some unexpected way.  Can we somehow push this up to the RendererBinding?

**Comment by Hixie** [comment]
> The engine finds out the platform brightness and text scale settings, and sends those down to the window (adding to the microtask queue).

That seems like the bug. Why are these ending up on the microtask queue instead of the task queue?

**Comment by dnfield** [comment]
Hm.  It may not actually be the microtask queue at all - the problem is they mark the widgets as needing a build again, but they're getting marked as needing a build while a build is already going on which leads to the confusion.

**Comment by kpsroka** [comment]
> > The engine finds out the platform brightness and text scale settings, and sends those down to the window (adding to the microtask queue).
> 
> That seems like the bug. Why are these ending up on the microtask queue instead of the task queue?

Actually, they are not. I've been a bit mislead by the comment in `scheduleWarmUpFrame`:
```
    // We use timers here to ensure that microtasks flush in between.
```

The engine calls that actually regular Tasks, rather than microtasks. So I tried a different approach now, in which instead of using `Timer.run` to call handle*Frame within `scheduleWarmUpFrame`, I'm using `scheduleMicrotask`.

**Comment by dnfield** [comment]
This seems reasonable to me but I'm afraid I may be lacking in my understanding of what's going on here.  I suspect @jonahwilliams @goderbauer, @yjbanov  or @Hixie would be better suited to review this.  Could one of you take a look?

**Review by dnfield — APPROVED** [review]
This LGTM.  I've talked with a couple people and no one has been able to give me a strong reason not to do this, and it seems to work fine.  We'll keep an eye out for it breaking anything.

**Comment by dnfield** [comment]
Thanks for sticking with this @kpsroka !  It definitely was a tricky one.

**Comment by Hixie** [comment]
The PR as it stands now seems correct, but I'm still confused as to why it didn't work before when calling `Timer.run` twice back-to-back synchronously. I would have expected the result to be identical (modulo microtask counts).

It would be good to have a test that specifically tests the original bug that led to this, though I admit I don't really know how one would write that test.
