### PR TITLE
[benchmarks] Handle multiple begin/end trace events

### LINKED ISSUE #54095: color_filter_and_fade_perf__timeline_summary regression worst_frame_rasterizer_time_millis
Clear jump at this engine roll: https://github.com/flutter/flutter/pull/53890

Screen Shot 2020-04-06 at 7 58 17 AM

### PR DESCRIPTION
**Pull request by iskakaushik**
Parser would earlier alternate after finding the first
begin event, now it looks for pairs.

Fixes: https://github.com/flutter/flutter/issues/54095

### CODE REVIEW

**Comment by jason-simmons** [comment]
In https://github.com/flutter/flutter/issues/54095, the begin/end pairs were mismatched because timeline events in the JSON were not written in timestamp order.

The flutter_driver parser could work around this by sorting the events itself.  But the timeline JSON should not have this problem.

File: packages/flutter_driver/lib/src/driver/timeline_summary.dart [hunk 1]
```diff
@@ -150,15 +150,19 @@ class TimelineSummary {
     Duration extractor(TimelineEvent beginEvent, TimelineEvent endEvent),
   ) {
     final List<Duration> result = <Duration>[];
+    final List<TimelineEvent> events = _extractNamedEvents(name);
```
Comment (liyuqian) [inline packages/flutter_driver/lib/src/driver/timeline_summary.dart:153]: While the code below fixes the case with rogue events that don't come in pairs, it doesn't seem to fix the case where `_extractNamedEvents` didn't return events in time order? Maybe we need to add a `sort` somewhere, and probably assert that events are in order in the `for` loop below.

**Review by liyuqian — COMMENTED** [review]
> not it looks for pairs

typo "not" should be "now"? (If so, please don't forget to correct the commit message while merging so the typo won't be included in the git log.)

File: packages/flutter_driver/lib/src/driver/timeline_summary.dart (hunk 1 above)
Comment (iskakaushik) [reply packages/flutter_driver/lib/src/driver/timeline_summary.dart:153]: I think it should be the responsibility of the timeline exporter to sort the events prior to producing the json meant for consumption by `chrome://tracing`. I reached out to the team, will respond here with what I hear. I think this is a good change independent of that.

> typo "not" should be "now"

Yes, it's now 👍

Comment (liyuqian) [reply packages/flutter_driver/lib/src/driver/timeline_summary.dart:153]: I see. Since it's their responsibility to sort, we only need to do some `assert` check to make sure that they fulfill the responsibility :)

Comment (iskakaushik) [reply packages/flutter_driver/lib/src/driver/timeline_summary.dart:153]: Given that this assert could currently fail. I've filed https://github.com/flutter/flutter/issues/54300 to enable this once the observatory team has enforced this invariant.

**Review by liyuqian — APPROVED** [review]
LGTM!
