### PR TITLE
Ensure FloatingActionButtonLocations are always within safe interactive areas

### LINKED ISSUE #30105: SafeArea should have a `fab` parameter
## Steps to Reproduce

When using a `SafeArea`, there should be an option to place the `FloatingActionButton` inside the device's `SafeArea`, but also extend its body to the bottom of the screen (using `bottom: false` and `fab: true`, for example).

[Images](https://imgur.com/a/9xvSsnl)

Sample code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: "Swapp",
      home: SafeAreaExtended(),
    ),
  );
}

class SafeAreaExtended extends StatelessWidget {
  final List<String> sampleData =
      List.generate(50, (index) => 'Item $index', growable: false);
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
        floatingActionButton: FloatingActionButton.extended(
          onPressed: () => null,
          label: Text('Add'),
          icon: Icon(Icons.add),
        ),
        body: ListView.builder(
          itemCount: sampleData.length,
          itemBuilder: (context, index) => Text(sampleData[index]),
        ),
      ),
    );
  }
}
```

## Logs

```
$ flutter doctor -v
[✓] Flutter (Channel master, v1.4.5-pre.12, on Mac OS X 10.14.4 18E226, locale es-ES)
    • Flutter version 1.4.5-pre.12 at /Applications/flutter
    • Framework revision 557c94ff77 (4 hours ago), 2019-03-28 01:00:29 -0700
    • Engine revision 37947f961a
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cristianzazo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.4 Preview.app/Contents
    • Flutter plugin version 32.0.2
    • Dart plugin version 183.4733
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

```

### LINKED ISSUE #58942: Floating action buttons don't respect SafeArea
b/158392371

When using a Scaffold, floatingActionButton: doesn't seem to respect the bottom SafeArea.

Full repro code:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        appBar: AppBar(title: Text('FloatingActionButton test')),
        body: SafeArea(
          child: Container(color: Colors.yellow),
        ),
        floatingActionButton: RaisedButton(
          onPressed: () {},
          child: Text('Press me'),
        ),
      ),
    );
  }
}
```

Result:
image

The yellow area is the safe area, but it can clearly be seen that the RaisedButton goes into the safe area.

Wrapping the RaisedButton with a SafeArea widget doesn't change its position either.

Similar issue: https://github.com/flutter/flutter/issues/30105

### PR DESCRIPTION
**Pull request by Piinks**
## Description

This PR makes `Scaffold.floatingActionButton`s respect safe areas. This is done by adding `minViewPadding` to `_ScaffoldLayout` and the `ScaffoldPrelayoutGeometry`, so we can check that the button is placed within a valid interactive area.
The FAB usually uses `kFloatingActionButtonMargin`, or aligns with the relevant objects for the given location, like the `BottomNavigationBar`, `BottomSheet`, `AppBar`, or `SnackBar`. With `viewPadding` added into consideration, it will conditionally choose the `viewPadding` if one of the standard options does not result in a safe position.

#### Example:

`FloatingActionButton.endFloat` chooses `(bottom: 34.0, right: 16.0)`   for safe interaction. (34.0 being the bottom viewPadding, and 16.0 the default `kFloatingActionButtonMargin`.
Screen Shot 2020-06-24 at 12 15 09 PM

`FloatingActionButtonLocation.endFloat` chooses default `kFloatingActionButtonMargin` (16.0) for bottom and right as there are no interfering obstructions:
Screen Shot 2020-06-24 at 12 16 09 PM

## Related Issues

Fixes https://github.com/flutter/flutter/issues/58942
Fixes #30105
b/158392371

## Tests

I added the following tests:

Oodles!
There are a lot of tests here since so many Scaffold elements affect the FAB placement, and there are 18 FAB locations. I split them into three main categories, the Float, Top, and End locations.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/floating_action_button_location.dart [hunk 1]
```diff
@@ -419,8 +419,12 @@ mixin FabTopOffsetY on StandardFabLocation {
   /// the transition between the [Scaffold.appBar] and the [Scaffold.body].
   @override
   double getOffsetY(ScaffoldPrelayoutGeometry scaffoldGeometry, double adjustment) {
-    final double fabHalfHeight = scaffoldGeometry.floatingActionButtonSize.height / 2.0;
-    return scaffoldGeometry.contentTop - fabHalfHeight;
+    if (scaffoldGeometry.contentTop > scaffoldGeometry.minViewPadding.top) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/floating_action_button_location.dart:422]: We're ignoring the adjustment parameter here, same as before (@pennzht - why is that?). Maybe update the API doc?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 2]
```diff
@@ -134,6 +135,16 @@ class ScaffoldPrelayoutGeometry {
   /// will be 0.0.
   final EdgeInsets minInsets;
 
+  /// The minimum padding to inset interactive elements to be within a safe,
+  /// un-obscured space.
+  ///
+  /// This value is the result of calling [MediaQuery.viewPadding] in the
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/scaffold.dart:141]: Is the value just based on [MediaQuery.viewPadding] or is it the same as viewPadding?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 3]
```diff
@@ -134,6 +135,16 @@ class ScaffoldPrelayoutGeometry {
...
+  /// [Scaffold]'s [BuildContext], this helps distinguish different types of
+  /// obstructions. For example, by using the viewPadding property, padding
+  /// would defer to the iPhone "safe area" regardless of whether a keyboard is
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/scaffold.dart:144]: We want to make it clear that minViewPadding doesn't change when the soft keyboard goes up and down.

File: packages/flutter/test/material/floating_action_button_location_test.dart [hunk 4]
```diff
@@ -609,8 +609,749 @@ void main() {
...
+      // Default
+      await tester.pumpWidget(_buildTest(
+        location,
+        const MediaQueryData(viewPadding: EdgeInsets.only(bottom: viewPadding)),
+        floatingActionButton,
+        mini: mini,
+      ));
+      expect(
+        tester.getRect(find.byKey(floatingActionButton)),
+        rectMoreOrLessEquals(defaultRect),
```
Comment (HansMuller) [inline packages/flutter/test/material/floating_action_button_location_test.dart:932]: Whey are we using rectMoreOrlessEquals here and elsewhere? It would be OK to just include an explanatory comment.

**Review by HansMuller — APPROVED** [review]
LGTM. The tests are superb!

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

**Comment by flutter-github-sync** [comment]
Google testing passed!

File: packages/flutter/lib/src/material/floating_action_button_location.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/floating_action_button_location.dart:422]: According to the docs, the Y offset is not affected by the adjustment for the mini Top positions. It looks like only the X is adjusted.
https://github.com/flutter/flutter/blob/9322c80825bb582954410408de39c0ef90b395ec/packages/flutter/lib/src/material/floating_action_button_location.dart#L40

File: packages/flutter/lib/src/material/scaffold.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/scaffold.dart:141]: It's also dependent on `_resizeToAvoidBottomInset`, I'll update the docs. :)

File: packages/flutter/lib/src/material/scaffold.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/scaffold.dart:144]: I'll add some more clarification. :)

File: packages/flutter/test/material/floating_action_button_location_test.dart (hunk 4 above)
Comment (Piinks) [reply packages/flutter/test/material/floating_action_button_location_test.dart:932]: Oh I borrowed a little from other FAB tests. I'm not sure we have to use `rectMoreOrLessEquals`. I'll see if I can simplify.

Comment (Piinks) [reply packages/flutter/test/material/floating_action_button_location_test.dart:932]: Ah, just checked. This is required as it accounts for the precisionErrorTolerance. The tests will not pass otherwise.

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

File: packages/flutter/lib/src/material/floating_action_button_location.dart (hunk 1 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/floating_action_button_location.dart:422]: We're providing API doc for this override, so it would be helpful to reiterate the point about ignoring the adjustment parameter here.

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

**Comment by flutter-github-sync** [comment]
Google testing passed!

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

**Comment by flutter-github-sync** [comment]
Google testing passed!

File: packages/flutter/lib/src/material/scaffold.dart [hunk 5]
```diff
@@ -410,6 +422,7 @@ class _ScaffoldLayout extends MultiChildLayoutDelegate {
   final bool extendBody;
   final bool extendBodyBehindAppBar;
   final EdgeInsets minInsets;
+  final EdgeInsets minViewPadding;
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/scaffold.dart:425]: @Piinks Hey, I am currently working on another scaffold issue.
some tests block me. it seems to be relative to this change.
I am wondering why not add `minViewPadding` to `shouldRelayout(oldDelegate)`, it should re-layout if it changes, right?

If the above is right, this test('Floating Action Button bottom padding not consumed by viewInsets') will fail, could you take a look at this?

Additional, the test was added in https://github.com/flutter/flutter/pull/34298 by you too :)

Comment (Piinks) [reply packages/flutter/lib/src/material/scaffold.dart:425]: Hey @xu-baolin! Can you share the issue you are working on? It will help me better understand. It's been a while since I worked on this so I am trying to refresh my memory. 😅

Comment (Piinks) [reply packages/flutter/lib/src/material/scaffold.dart:425]: Looking at `Floating Action Button bottom padding not consumed by viewInsets`, it makes sense to me, but the issue you are working on may provide a reason otherwise.
