### PR TITLE
Switch to assemble API for dart2js

### LINKED ISSUE #40463: Issues in release mode when running Flutter Web
## Steps to Reproduce

running: flutter run -d chrome --release --local-engine=host_debug_unopt --web-port=8080

We saw two issues running in release mode today:
1) The runner doesn't use the given web-port put uses a random port.
2) After making a change, to make it visible, I needed to run flutter clean to remove the cache. Otherwise my change didn't took effect.

Thanks!

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Use flutter tools to build with dart2js directly instead of build through build runner. Updates resident web runner to serve from build/web. Should fix cases where local updates to dart2js or dart SDK does not result in correct rebuild through build_runner. Removes cases where multiple entrypoints are compiled with build runner.

Fixes https://github.com/flutter/flutter/issues/40463

### CODE REVIEW

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 1]
```diff
@@ -283,6 +285,20 @@ class ResidentWebRunner extends ResidentRunner {
         ).send();
       }
     }
+    if (device is ChromeDevice && debuggingOptions.browserLaunch) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Allows page refresh on release/profile builds

File: packages/flutter_tools/lib/src/build_runner/web_fs.dart [hunk 2]
```diff
@@ -161,47 +176,16 @@ class WebFs {
     if (!flutterProject.dartTool.existsSync()) {
       flutterProject.dartTool.createSync(recursive: true);
     }
-    final bool hasWebPlugins = findPlugins(flutterProject)
-        .any((Plugin p) => p.platforms.containsKey(WebPlugin.kConfigKey));
     // Start the build daemon and run an initial build.
     final Completer<bool> inititalBuild = Completer<bool>();
```
Comment (hterkelsen) [inline packages/flutter_tools/lib/src/build_runner/web_fs.dart]: nit: inititalBuild -> initialBuild

**Review by harryterkelsen — APPROVED** [review]

File: packages/flutter_tools/lib/src/build_runner/web_fs.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/web_fs.dart]: Woops, Fixed!

File: packages/flutter_tools/lib/src/build_runner/web_fs.dart [hunk 3]
```diff
@@ -236,29 +220,77 @@ class WebFs {
...
+            initializePlatform: initializePlatform,
+        );
+      client.startBuild();
+      // Only provide relevant build results
+      final Stream<BuildResult> filteredBuildResults = client.buildResults
+        .asyncMap<BuildResult>((BuildResults results) {
+          return results.results
+            .firstWhere((BuildResult result) => result.target == kBuildTargetName);
+        });
+      firstBuild = client.buildResults.listen((BuildResults buildResults) {
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/build_runner/web_fs.dart]: Is there a difference between "first" and "initial" builds?

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart [hunk 4]
```diff
@@ -283,6 +285,20 @@ class ResidentWebRunner extends ResidentRunner {
...
+      try {
+        final Chrome chrome = await ChromeLauncher.connectedInstance;
+        final ChromeTab chromeTab = await chrome.chromeConnection.getTab((ChromeTab chromeTab) {
+          return chromeTab.url.contains(debuggingOptions.hostname);
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: Should we use some sort of nonce in case there are multiple tabs?

File: packages/flutter_tools/lib/src/build_system/file_hash_store.dart [hunk 5]
```diff
@@ -143,24 +137,27 @@ class FileHashStore {
...
-  // APKs before installing them on device.
   Future<List<File>> hashFiles(List<File> files) async {
     final List<File> dirty = <File>[];
-    for (File file in files) {
-      final String absolutePath = file.resolveSymbolicLinksSync();
-      final String previousHash = previousHashes[absolutePath];
-      final List<int> bytes = file.readAsBytesSync();
-      final String currentHash = md5.convert(bytes).toString();
+    await Future.wait(<Future<void>>[
+      for (File file in files) _hashFile(file, dirty, Pool(32))]);
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/build_system/file_hash_store.dart]: How was the limit of 32 chosen?

File: packages/flutter_tools/lib/src/build_system/targets/dart.dart [hunk 6]
```diff
@@ -140,6 +124,28 @@ class CopyFlutterBundle extends Target {
...
+/// A helper function to copy an [assetBundle] into an [environment]'s output directory,
+/// plus an optional [pathSuffix]
+Future<void> copyAssets(AssetBundle assetBundle, Environment environment, [String pathSuffix = '']) async {
+  final Pool pool = Pool(64);
+  await Future.wait<void>(
+    assetBundle.entries.entries.map<Future<void>>((MapEntry<String, DevFSContent> entry) async {
+      final PoolResource resource = await pool.request();
+      try {
+        final File file = fs.file(fs.path.join(environment.outputDir.path, pathSuffix, entry.key));
+        file.parent.createSync(recursive: true);
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/build_system/targets/dart.dart]: For the pool to be effective, wouldn't you want to stick with async I/O only?

File: packages/flutter_tools/lib/src/build_system/targets/web.dart [hunk 7]
```diff
@@ -0,0 +1,202 @@
...
+      if (!fs.path.basename(outputFile.path).contains('main.dart.js')) {
+        continue;
+      }
+      outputFile.copySync(
+        environment.outputDir.childFile(fs.path.basename(outputFile.path)).path
+      );
+    }
+    environment.projectDir
+      .childDirectory('web')
+      .childFile('index.html').copySync(fs.path.join(environment.outputDir.path, 'index.html'));
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/build_system/targets/web.dart]: nit: unless this is dartfmt'ed I'd move `copySync` to the next line too.

File: packages/flutter_tools/test/general.shard/build_system/targets/web_test.dart [hunk 8]
```diff
@@ -0,0 +1,194 @@
...
+    expect(generated, contains('registerPlugins(webPluginRegistry);'));
+
+    // Platform
+    expect(generated, contains('if (true) {'));
+
+    // Main
+    expect(generated, contains('entrypoint.main();'));
+
+    // Import.
+    if (platform.isWindows) {
```
Comment (yjbanov) [inline packages/flutter_tools/test/general.shard/build_system/targets/web_test.dart]: According to the `setUp` above this will always be false. Only `isMacOS` is ever `true`. Or am I missing something?

**Review by yjbanov — APPROVED** [review]

File: packages/flutter_tools/lib/src/build_runner/build_script.dart [hunk 9]
```diff
@@ -245,12 +238,8 @@ class FlutterWebEntrypointBuilder implements Builder {
...
   @override
   Future<void> build(BuildStep buildStep) async {
-    if (release || profile) {
-      await bootstrapDart2Js(buildStep, flutterWebSdk, profile);
-    } else {
-      await bootstrapDdc(buildStep, platform: flutterWebPlatform,
-          skipPlatformCheckPackages: skipPlatformCheckPackages);
-    }
+    await bootstrapDdc(buildStep, platform: flutterWebPlatform,
+        skipPlatformCheckPackages: skipPlatformCheckPackages);
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/build_script.dart]: This doesn't run at all in non-debug builds

File: packages/flutter_tools/lib/src/build_system/targets/dart.dart (hunk 6 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/targets/dart.dart]: No, sync methods create and dispose the fd immediately

File: packages/flutter_tools/test/general.shard/build_system/targets/web_test.dart (hunk 8 above)
Comment (jonahwilliams) [reply packages/flutter_tools/test/general.shard/build_system/targets/web_test.dart]: Fixed

File: packages/flutter_tools/lib/src/build_system/targets/web.dart (hunk 7 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/targets/web.dart]: Fixed

File: packages/flutter_tools/lib/src/build_system/file_hash_store.dart (hunk 5 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/file_hash_store.dart]: Its a nice sounding number. There's no real way to know though

File: packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart (hunk 4 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart]: We don't really support that in the launched browser case

File: packages/flutter_tools/lib/src/build_runner/web_fs.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_runner/web_fs.dart]: Fixed the names so that it is clear they are related

File: packages/flutter_tools/lib/src/build_system/file_hash_store.dart (hunk 5 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/build_system/file_hash_store.dart]: Ah. I'd just leave a comment that this number is arbitrary. Otherwise, it looks purposeful. Someone may be scared to change it later.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/build_system/file_hash_store.dart]: Did you one better and moved it to a constant - also tried making this async
