### PR TITLE
Fix FocusTraversalPolicy makes focus lost

### LINKED ISSUE #33435: Anti-hysteresis code causes loss of focus occasionally.
Reported by @eyun-tv (thank you for the report and the clear reproduction case!):

"I write a demo use DefaultFocusTraversal with ReadingOrderTraversalPolicy
But , I find when you press up or down , sometimes , the focus will lose .
I record a video https://vimeo.com/338635739 for show this bug

My code is there :
https://github.com/eyun-tv/flutter-tv/blob/master/lib/main.dart
https://github.com/eyun-tv/flutter-tv/blob/master/lib/ui/util/video.dart

My flutter version is master and my tv box is android 9"

I took a quick look, and it seems to be related to the anti-hysteresis code that makes sure we follow the same reverse path as we took forward, probably having to do with reaching the end of the history but not doing anything in that case.

### LINKED ISSUE #34153: Focus sometimes lost when focus move in the GridView
I am an AndroidTV developer, so it is excited to see that flutter support Focus shifts in different widget. 

But it seems to the FocusManager have some problems in the GridView. When using the controller or keyboard to move the focus, the focus sometimes got lost.

Here is a gif example：
focus_loss

GIf is running on macOS, Android also has the same problem when using the remote control

## Steps to Reproduce

gif example source code is here : https://github.com/boyan01/flutter_focus_loss

It's easy to reproduce, just press the navigation key to  move the focus up and down.

## Logs
This is the key log when the focus has been lost，It seems that FocusManager's primary focus does not have an ancestor. maybe this is the cause

```log
flutter: ERR: the focus has been loss
flutter: primary focus：FocusNode#9d55a(context: Focus, FOCUSED)
flutter: primary focus ancestor: ：()
flutter: FocusManager#07390
flutter:  │ currentFocus: FocusNode#9d55a
flutter:  │
flutter:  └─rootScope: FocusScopeNode#96475
flutter:    │ debugLabel: "Root Focus Scope"
flutter:    │ focusedChild: FocusScopeNode#78b3f
flutter:    │
flutter:    └─Child 1: FocusScopeNode#78b3f
flutter:      │ context: FocusScope
flutter:      │ debugLabel: "Navigator Scope"
flutter:      │ focusedChild: FocusScopeNode#f41e2
flutter:      │
flutter:      └─Child 1: FocusScopeNode#f41e2
flutter:        │ context: FocusScope
flutter:        │ debugLabel: "_ModalScopeState<dynamic> Focus Scope"
flutter:        │ focusedChild: FocusScopeNode#9625d
flutter:        │
flutter:        └─Child 1: FocusScopeNode#9625d
flutter:          │ context: FocusScope
flutter:          │ focusedChild: FocusNode#107c4
flutter:          │
flutter:          ├─Child 1: FocusNode#107c4
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 2: FocusNode#cab25
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 3: FocusNode#7e80d
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 4: FocusNode#a2324
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 5: FocusNode#16794
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 6: FocusNode#96fcd
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 7: FocusNode#8aa87
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 8: FocusNode#f3cd7
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 9: FocusNode#c40c0
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 10: FocusNode#3d090
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 11: FocusNode#9d015
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 12: FocusNode#0ccba
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 13: FocusNode#17a06
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 14: FocusNode#c7fb3
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 15: FocusNode#bc2be
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 16: FocusNode#81c77
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 17: FocusNode#1bd7d
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 18: FocusNode#ba30a
flutter:          │   context: Focus
flutter:          │
flutter:          ├─Child 19: FocusNode#4b07c
flutter:          │   context: Focus
flutter:          │
flutter:          └─Child 20: FocusNode#77eaa
flutter:              context: Focus
flutter: 

```

### Flutter version
```

  [✓] Flutter (Channel master, v1.7.4-pre.30, on Mac OS X 10.14.5 18F132, locale
    zh-Hans-CN)
    • Flutter version 1.7.4-pre.30 at /Users/ff/flutter
    • Framework revision 1157e67491 (12 hours ago), 2019-06-09 15:05:55 -0400
    • Engine revision e886d7b082
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 7f146e431e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/ff/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.5.3

[!] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 36.0.7
    • Dart plugin version 191.7221
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b02)

[!] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.14.5 18F132

```

### PR DESCRIPTION
**Pull request by boyan01**
## Description

FocusTraversalPolicy keep the previously visited node to avoid hysteresis. But even if the visited focus has been disposed, FocusTraversalPolicy will still use it to requestFocus, which will cause FocusManger to get an abandoned node to get the focus.

## Related Issues

Fixes #34153
Fixes #33435

## Tests

I added the following tests:

* A test to see that focus can be correctly found when visited focus has been disposed. 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by boyan01** [comment]
@darrenaustin  @gspencergoog  Review Request

**Comment by dnfield** [comment]
The release smoke tests failure is expected.

@gspencergoog would really be the best person to review this, but he is OOO right now.  Sorry for the delay, but it would be best if we can wait until he's back to review this.

File: packages/flutter/lib/src/widgets/focus_traversal.dart [hunk 1]
```diff
@@ -311,6 +311,11 @@ mixin DirectionalFocusTraversalPolicyMixin on FocusTraversalPolicy {
   bool _popPolicyDataIfNeeded(TraversalDirection direction, FocusScopeNode nearestScope, FocusNode focusedChild) {
     final _DirectionalPolicyData policyData = _policyData[nearestScope];
     if (policyData != null && policyData.history.isNotEmpty && policyData.history.first.direction != direction) {
+      if (policyData.history.last.node.parent == null) {
```
Comment (dnfield) [inline packages/flutter/lib/src/widgets/focus_traversal.dart]: I think we need to better understand how this could happen.  I'm concerned that this may arise because some node that is supposed to be kept alive is actually not being kept alive, and that's why we're losing it.  Making this change would hide that, if it is in fact the problem.

Comment (boyan01) [reply packages/flutter/lib/src/widgets/focus_traversal.dart]: This situation is widespread in the Sliver component. 
such as GridView(#34153):  when we move the focus down, grid element slides up. The grid elements would be unmount if they out of grid container, which cause history kept an unreachable node.

**Comment by boyan01** [comment]
> @gspencergoog would really be the best person to review this, but he is OOO right now. Sorry for the delay, but it would be best if we can wait until he's back to review this.

thanks for your reply. of course we could wait spencergoog back to review, maybe he has better ideas to fix this issue.

File: packages/flutter/lib/src/widgets/focus_traversal.dart (hunk 1 above)
Comment (boyan01) [reply packages/flutter/lib/src/widgets/focus_traversal.dart]: What I think is that the last element might not be unmounted, in this situation, the last node can still be used to avoid hysteresis.

Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_traversal.dart]: Yes, I guess that makes sense, just because a previous node is already unmounted doesn't mean that the last one is invalid. OK.  I do think you should add the comment I suggested above, though, to explain what's going on.

**Review by gspencergoog — APPROVED** [review]

File: packages/flutter/lib/src/widgets/focus_traversal.dart (hunk 1 above)
Comment (boyan01) [reply packages/flutter/lib/src/widgets/focus_traversal.dart]: Yes, I think I should add a comment to explain why this code was added.

**Comment by Piinks** [comment]
Hi @boyan01, Are you ready for this to be merged? It looks like this is ready to go unless you would like to make more changes.

**Comment by boyan01** [comment]
> Hi @boyan01, Are you ready for this to be merged? It looks like this is ready to go unless you would like to make more changes.

@Piinks Yes, this PR is ready.

**Comment by gspencergoog** [comment]
@boyan01, thanks so much for the fix!
