### PR TITLE
Fix navigation rail with long labels misplaced highlights

### LINKED ISSUE #128005: NavigationRail with big labels show incorrect hover area in Material 3
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

As you can see on the first destination there's a hover highlight that's off-center with the icon, while when the second destination is selected, the selected highlight is properly center-aligned with the icon. This makes a weird effect, specially when I hover my mouse over a selected destination:

image

image

I caught this bug when I updated to Material 3, on Material 2 it was working fine.

### Expected results

Both the selected and hovering highlighted areas should be center aligned.

### Actual results

The hovering highlight is left aligned while the selected highlight is center aligned with the destination icon.

### Code sample

<details><summary>Code sample</summary>

```dart
NavigationRail(
            labelType: NavigationRailLabelType.all,
            onDestinationSelected: (index) {
              setState(() => selectedIndex = index);
            },
            destinations: const [
              NavigationRailDestination(icon: Icon(Icons.description), label: Text('My long label 1')),
              NavigationRailDestination(icon: Icon(Icons.currency_bitcoin), label: Text('My long label 2')),
              NavigationRailDestination(icon: Icon(Icons.view_list), label: Text('My long label 3')),
            ], selectedIndex: selectedIndex,
          )
```
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.19045.2965], locale pt-BR)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```
</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes an issue related to `InkWell` highlights being misplaced for navigation rail destinations with long labels.

- Before:

https://github.com/flutter/flutter/assets/840911/a64bb55f-ed17-43b4-a67c-e1ae057264cf

- After: 

https://github.com/flutter/flutter/assets/840911/1ac9ae45-b752-4b17-9953-6c1baae170ac

## Related Issue

Fixes https://github.com/flutter/flutter/issues/128005

## Tests

Adds 1 test.

### CODE REVIEW

File: packages/flutter/lib/src/material/navigation_rail.dart [hunk 1]
```diff
@@ -806,13 +810,15 @@ class _IndicatorInkWell extends InkResponse {
 
   final bool useMaterial3;
   final Offset indicatorOffset;
+  final bool applyXOffset;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/navigation_rail.dart:813]: A comment that explained what this flag is for would be helpful here.

**Review by HansMuller — APPROVED** [review]
With the addition of one comment, this looks good to go.

**Comment by bleroux** [comment]
@feinstein Because the vertical offset is always used. I considered replacing the indicatorOffset by two variables, indicatorOffsetX and indicatorOffsetY but this was LESS readable.

**Comment by feinstein** [comment]
Ok, makes sense. Thanks for the contribution.
