### PR TITLE
Documentation update to advertize timedDrag

### LINKED ISSUE #96893: `ReorderableListView` weird onReorder behaviour in tests
I'm facing a weird behaviour in my flutter test. I have a list of 6 elements, and I'm trying to test the drag and drop of the 2nd element after the 4th one.
I can't manage to do it and it looks like it can only be dropped after the 3rd element or the 5th one.

The code sample provided is a  test that tries to drag the 2nd element of the list just after the 4th one.

Note the `extra` value which I changed between runs to drag a little bit further down the 2nd element.

## Steps to Reproduce

1. Execute `flutter test` on the code sample (see "Code sample" section below).
The test fails because the element is actually dragged after the 3rd element instead of the 4th one.
<details>
<summary>Logs</summary>

```
00:04 +0: It should allow the item to be dragged when enabled is true                                                                                                                                                     
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: equals [0, 2, 3, 1, 4, 5] ordered
  Actual: [0, 2, 1, 3, 4, 5]
   Which: at location [2] is <1> instead of <3>
```

</details>

<details>
<summary>Golden images</summary>

`0.png` :

`1.png` :

The element is dragged just after the 4th element.

`2.png` :

When the other elements of the list are moving, the 4th element still staying behind the dragged on

</details>

2. Change the value of `extra` to `1` 
```dart

const double extra = 1; // Extra `dy` offset the 2nd element will be dragged.
```

and execute `flutter test` on the code sample (see "Code sample" section below).
The test fails because the element is actually dragged after the 5th element instead of the 4th one.
<details>
<summary>Logs</summary>

```
00:03 +0: It should drag the 2nd element after the 4th one                                                                                                                                                                
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: equals [0, 2, 3, 1, 4, 5] ordered
  Actual: [0, 2, 3, 4, 1, 5]
   Which: at location [3] is <4> instead of <1>
```

</details>

<details>
<summary>Golden images</summary>

`0.png` :

`1.png` :

The element is dragged just after the 4th element (+1 pixel down).

`2.png` :

When the other elements of the list are moving, the 4th and the 5th elements are going before the dragged one

</details>

**Expected results:** 

It should be able to drag the 2nd element after the 4th one in the test.

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
void main() {
  testWidgets('It should drag the 2nd element after the 4th one', (WidgetTester tester) async {
    const int itemCount = 6;
    final List<int> items = List<int>.generate(itemCount, (int index) => index);
    const double height = 50; // Height of the elements in the list.
    const double margin = 2; // Element margin so they are visible in the golden images.

    const double extra = 0; // Extra `dy` offset the 2nd element will be dragged.

    void handleReorder(int fromIndex, int toIndex) {
      if (toIndex > fromIndex) {
        toIndex -= 1;
      }
      items.insert(toIndex, items.removeAt(fromIndex));
    }

    final widget = MaterialApp(
      home: Scaffold(
        body: ReorderableList(
          itemCount: itemCount,
          itemBuilder: (BuildContext context, int index) {
            return Card(
              margin: EdgeInsets.all(margin), // Give a margin so the elements are visible in the golden images.
              key: ValueKey<int>(items[index]),
              child: SizedBox(
                height: height - 2 * margin,
                child: ReorderableDragStartListener(
                  index: index,
                  child: Text('item ${items[index]} ' + ('#' * (index + 1))),
                ),
              ),
            );
          },
          onReorder: handleReorder,
        ),
      ),
    );

    // The list has six elements of height 50.
    await tester.pumpWidget(widget);

    await expectLater(find.byWidget(widget), matchesGoldenFile('0.png')); // Display the initial list.

    // Start gesture on the second item
    final TestGesture drag = await tester.startGesture(tester.getCenter(find.textContaining('item 1')));
    await tester.pump(kPressTimeout);

    // Drag enough to move down the 2nd item after the 4th one.
    await drag.moveTo(
      tester.getCenter(find.byKey(const ValueKey(3))) + const Offset(0.0, height / 2) + const Offset(0.0, extra),
    );
    await tester.pump();
    await expectLater(find.byWidget(widget), matchesGoldenFile('1.png')); // Displays where is the dragged element is before the drop.
    await tester.pumpAndSettle();
    await expectLater(find.byWidget(widget), matchesGoldenFile('2.png')); // Displays how the list is moving before the drop.

    await drag.up();
    await tester.pumpAndSettle();

    expect(items, orderedEquals(<int>[0, 2, 3, 1, 4, 5])); // The 2nd element (index 1) should have been dropped after the 4th element (index 3).
  });
}
```

</details>

<details>
  <summary>Logs</summary>

With `extra = 0`:

```
$ flutter test --verbose test/test.dart
[  +90 ms] executing: sysctl hw.optional.arm64
[  +16 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +7 ms] executing: [/Users/valentin/flutter/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +16 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] executing: [/Users/valentin/flutter/flutter/] git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[  +35 ms] Exit code 0 from: git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] 2.8.1
[  +11 ms] executing: [/Users/valentin/flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/valentin/flutter/flutter/] git ls-remote --get-url origin
[  +15 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +108 ms] executing: [/Users/valentin/flutter/flutter/] git rev-parse --abbrev-ref HEAD
[  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.5.1
[        ] executing: sw_vers -buildVersion
[  +16 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20G80
[  +65 ms] Found 1 files which will be executed as Widget Tests.
[   +9 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +46 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +68 ms] Skipping pub get: version match.
[  +28 ms] Found plugin sqlcipher_flutter_libs at /Users/valentin/.pub-cache/git/sqlite3.dart-51ddd3832a51c771bc9160510b3a8143ce5597d0/sqlcipher_flutter_libs/
[   +9 ms] Found plugin amplitude_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/
[  +30 ms] Found plugin camera at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/camera-0.8.1+7/
[  +16 ms] Found plugin device_info at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.2/
[   +2 ms] Found plugin device_info_plus at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus-3.1.0/
[   +2 ms] Found plugin device_info_plus_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus_macos-2.2.0/
[   +2 ms] Found plugin device_info_plus_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus_web-2.1.0/
[  +18 ms] Found plugin file_picker at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/file_picker-4.2.7/
[   +2 ms] Found plugin firebase_core at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.7.0/
[   +2 ms] Found plugin firebase_core_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/
[   +1 ms] Found plugin firebase_messaging at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-10.0.8/
[   +1 ms] Found plugin firebase_messaging_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_web-2.0.6/
[   +3 ms] Found plugin flutter_inappwebview at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/
[   +1 ms] Found plugin flutter_keyboard_visibility at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-5.1.0/
[   +1 ms] Found plugin flutter_keyboard_visibility_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility_web-2.0.0/
[   +1 ms] Found plugin flutter_local_notifications at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-5.0.0+4/
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.3/
[   +1 ms] Found plugin flutter_secure_storage at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-4.2.1/
[   +6 ms] Found plugin geocoding at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.1/
[   +1 ms] Found plugin geolocator at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator-7.7.0/
[        ] Found plugin geolocator_android at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_android-2.1.0/
[   +1 ms] Found plugin geolocator_apple at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.2.2/
[   +1 ms] Found plugin geolocator_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_web-2.0.6/
[  +12 ms] Found plugin image_cropper at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.4.1/
[   +1 ms] Found plugin image_picker at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/
[   +1 ms] Found plugin image_picker_for_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/
[   +9 ms] Found plugin native_pdf_renderer at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/native_pdf_renderer-3.1.0/
[   +4 ms] Found plugin open_file at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/open_file-3.2.1/
[   +1 ms] Found plugin package_info_plus at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus-1.3.0/
[   +1 ms] Found plugin package_info_plus_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus_macos-1.3.0/
[   +1 ms] Found plugin package_info_plus_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus_web-1.0.4/
[   +4 ms] Found plugin path_provider at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.4/
[   +1 ms] Found plugin path_provider_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.0/
[   +1 ms] Found plugin path_provider_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.2/
[   +1 ms] Found plugin path_provider_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.3/
[   +1 ms] Found plugin permission_handler at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.1.6/
[   +6 ms] Found plugin sentry_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/sentry_flutter-6.1.2/
[        ] Found plugin shared_preferences at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.7/
[        ] Found plugin shared_preferences_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.2/
[   +1 ms] Found plugin shared_preferences_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.2/
[   +1 ms] Found plugin shared_preferences_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.2/
[        ] Found plugin shared_preferences_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.2/
[   +5 ms] Found plugin sqflite at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.0+4/
[   +7 ms] Found plugin uni_links at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/uni_links-0.5.1/
[   +1 ms] Found plugin uni_links_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/uni_links_web-0.1.0/
[   +2 ms] Found plugin url_launcher at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.10/
[        ] Found plugin url_launcher_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.2/
[   +1 ms] Found plugin url_launcher_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.2/
[   +2 ms] Found plugin url_launcher_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.4/
[        ] Found plugin url_launcher_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.2/
[   +5 ms] Found plugin webview_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.13/
[ +120 ms] Found plugin sqlcipher_flutter_libs at /Users/valentin/.pub-cache/git/sqlite3.dart-51ddd3832a51c771bc9160510b3a8143ce5597d0/sqlcipher_flutter_libs/
[   +3 ms] Found plugin amplitude_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/
[  +10 ms] Found plugin camera at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/camera-0.8.1+7/
[   +7 ms] Found plugin device_info at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.2/
[   +1 ms] Found plugin device_info_plus at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus-3.1.0/
[   +1 ms] Found plugin device_info_plus_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus_macos-2.2.0/
[   +1 ms] Found plugin device_info_plus_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus_web-2.1.0/
[   +8 ms] Found plugin file_picker at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/file_picker-4.2.7/
[   +1 ms] Found plugin firebase_core at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.7.0/
[   +1 ms] Found plugin firebase_core_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/
[   +1 ms] Found plugin firebase_messaging at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-10.0.8/
[   +1 ms] Found plugin firebase_messaging_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_web-2.0.6/
[   +4 ms] Found plugin flutter_inappwebview at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/
[        ] Found plugin flutter_keyboard_visibility at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-5.1.0/
[        ] Found plugin flutter_keyboard_visibility_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility_web-2.0.0/
[        ] Found plugin flutter_local_notifications at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-5.0.0+4/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.3/
[   +1 ms] Found plugin flutter_secure_storage at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-4.2.1/
[   +3 ms] Found plugin geocoding at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.1/
[   +1 ms] Found plugin geolocator at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator-7.7.0/
[        ] Found plugin geolocator_android at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_android-2.1.0/
[        ] Found plugin geolocator_apple at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.2.2/
[   +1 ms] Found plugin geolocator_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_web-2.0.6/
[   +5 ms] Found plugin image_cropper at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.4.1/
[        ] Found plugin image_picker at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/
[        ] Found plugin image_picker_for_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/
[   +7 ms] Found plugin native_pdf_renderer at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/native_pdf_renderer-3.1.0/
[   +2 ms] Found plugin open_file at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/open_file-3.2.1/
[        ] Found plugin package_info_plus at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus-1.3.0/
[        ] Found plugin package_info_plus_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus_macos-1.3.0/
[        ] Found plugin package_info_plus_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus_web-1.0.4/
[   +1 ms] Found plugin path_provider at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.4/
[        ] Found plugin path_provider_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.0/
[        ] Found plugin path_provider_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.2/
[        ] Found plugin path_provider_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.3/
[        ] Found plugin permission_handler at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.1.6/
[   +5 ms] Found plugin sentry_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/sentry_flutter-6.1.2/
[   +1 ms] Found plugin shared_preferences at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.7/
[   +1 ms] Found plugin shared_preferences_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.2/
[        ] Found plugin shared_preferences_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.2/
[        ] Found plugin shared_preferences_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.2/
[        ] Found plugin shared_preferences_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.2/
[   +3 ms] Found plugin sqflite at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.0+4/
[   +5 ms] Found plugin uni_links at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/uni_links-0.5.1/
[   +1 ms] Found plugin uni_links_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/uni_links_web-0.1.0/
[   +1 ms] Found plugin url_launcher at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.10/
[        ] Found plugin url_launcher_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.2/
[        ] Found plugin url_launcher_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.2/
[        ] Found plugin url_launcher_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.4/
[        ] Found plugin url_launcher_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.2/
[   +2 ms] Found plugin webview_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.13/
[  +24 ms] Generating /Users/valentin/Projects/MyProject/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +35 ms] executing: sysctl hw.optional.arm64
[   +7 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +585 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 12.5.1
           Build version 12E507
[ +250 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +14 ms] running test package with arguments: [-r, compact, --timeout, 30s, --concurrency=10, --chain-stack-traces, --, /Users/valentin/Projects/MyProject/test/test.dart]
00:00 +0: loading /Users/valentin/Projects/MyProject/test/test.dart                                                                                                                                                      [ +268 ms] test 0: starting test /Users/valentin/Projects/MyProject/test/test.dart
[   +5 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/valentin/Projects/MyProject
[   +2 ms] Compiler will use the following file as its incremental dill file: /var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.gkDuiI/flutter_test_compiler.s8ngEB/output.dill
[        ] Listening to compiler controller...
[  +12 ms] Compiling file:///var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.gkDuiI/flutter_test_listener.rHMg9N/listener.dart
[  +14 ms] Found plugin sqlcipher_flutter_libs at /Users/valentin/.pub-cache/git/sqlite3.dart-51ddd3832a51c771bc9160510b3a8143ce5597d0/sqlcipher_flutter_libs/
[   +3 ms] Found plugin amplitude_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/
[  +11 ms] Found plugin camera at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/camera-0.8.1+7/
[   +7 ms] Found plugin device_info at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.2/
[   +1 ms] Found plugin device_info_plus at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus-3.1.0/
[        ] Found plugin device_info_plus_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus_macos-2.2.0/
[        ] Found plugin device_info_plus_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus_web-2.1.0/
[   +7 ms] Found plugin file_picker at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/file_picker-4.2.7/
[        ] Found plugin firebase_core at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.7.0/
[        ] Found plugin firebase_core_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/
[        ] Found plugin firebase_messaging at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-10.0.8/
[   +1 ms] Found plugin firebase_messaging_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_web-2.0.6/
[   +2 ms] Found plugin flutter_inappwebview at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/
[        ] Found plugin flutter_keyboard_visibility at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-5.1.0/
[        ] Found plugin flutter_keyboard_visibility_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility_web-2.0.0/
[        ] Found plugin flutter_local_notifications at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-5.0.0+4/
[        ] Found plugin flutter_plugin_android_lifecycle at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.3/
[        ] Found plugin flutter_secure_storage at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-4.2.1/
[   +2 ms] Found plugin geocoding at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.1/
[        ] Found plugin geolocator at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator-7.7.0/
[        ] Found plugin geolocator_android at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_android-2.1.0/
[        ] Found plugin geolocator_apple at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.2.2/
[        ] Found plugin geolocator_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_web-2.0.6/
[   +5 ms] Found plugin image_cropper at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.4.1/
[        ] Found plugin image_picker at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/
[        ] Found plugin image_picker_for_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/
[   +4 ms] Found plugin native_pdf_renderer at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/native_pdf_renderer-3.1.0/
[   +1 ms] Found plugin open_file at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/open_file-3.2.1/
[        ] Found plugin package_info_plus at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus-1.3.0/
[        ] Found plugin package_info_plus_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus_macos-1.3.0/
[        ] Found plugin package_info_plus_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus_web-1.0.4/
[   +1 ms] Found plugin path_provider at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.4/
[        ] Found plugin path_provider_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.0/
[        ] Found plugin path_provider_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.2/
[        ] Found plugin path_provider_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.3/
[        ] Found plugin permission_handler at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.1.6/
[   +4 ms] Found plugin sentry_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/sentry_flutter-6.1.2/
[        ] Found plugin shared_preferences at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.7/
[        ] Found plugin shared_preferences_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.2/
[        ] Found plugin shared_preferences_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.2/
[        ] Found plugin shared_preferences_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.2/
[        ] Found plugin shared_preferences_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.2/
[   +2 ms] Found plugin sqflite at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.0+4/
[   +4 ms] Found plugin uni_links at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/uni_links-0.5.1/
[        ] Found plugin uni_links_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/uni_links_web-0.1.0/
[        ] Found plugin url_launcher at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.10/
[        ] Found plugin url_launcher_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.2/
[        ] Found plugin url_launcher_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.2/
[        ] Found plugin url_launcher_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.4/
[        ] Found plugin url_launcher_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.2/
[   +3 ms] Found plugin webview_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.13/
[  +17 ms] /Users/valentin/flutter/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/valentin/flutter/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/valentin/flutter/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --no-print-incremental-dependencies --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.gkDuiI/flutter_test_compiler.s8ngEB/output.dill --packages
/Users/valentin/Projects/MyProject/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --initialize-from-dill
/Users/valentin/Projects/MyProject/build/test_cache/build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
[  +39 ms] <- compile file:///Users/valentin/Projects/MyProject/.dart_tool/flutter_build/generated_main.dart
00:01 +0: loading /Users/valentin/Projects/MyProject/test/test.dart                                                                                                                                                      [+1096 ms] <- accept
[        ] <- reset
[        ] Compiling file:///var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.gkDuiI/flutter_test_listener.rHMg9N/listener.dart took 1254ms
[        ] test 0: starting test device
[   +4 ms] test 0: awaiting connection to test device
[   +1 ms] test 0: Observatory uri is not available
[   +5 ms] test 0: test harness socket server is running at port:57602
[   +6 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[   +2 ms] Using this directory for fonts configuration: /var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.gkDuiI/flutter_test_fonts.h8Cgvk
[   +1 ms] test 0: Starting flutter_tester process with command=[/Users/valentin/flutter/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester, --disable-observatory, --enable-checked-mode, --verify-entry-points,
--enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling, --non-interactive, --use-test-fonts, --packages=/Users/valentin/Projects/MyProject/.dart_tool/package_config.json,
/var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.gkDuiI/flutter_test_listener.rHMg9N/listener.dart.dill], environment={FLUTTER_TEST: true, FONTCONFIG_FILE:
/var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.gkDuiI/flutter_test_fonts.h8Cgvk/fonts.conf, SERVER_PORT: 57602, APP_NAME: my_project, UNIT_TEST_ASSETS:
/Users/valentin/Projects/MyProject/build/unit_test_assets}
[   +9 ms] test 0: Started flutter_tester process at pid 17828
[ +603 ms] test 0: connected to test device, now awaiting test result
[        ] test 0: Waiting for test harness or tests to finish
00:06 +0: It should drag the 2nd element after the 4th one                                                                                                                                                                
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown while running async test code:
Golden "1.png": Pixel test failed, 0.69% diff detected.
Failure feedback can be found at /Users/valentin/Projects/MyProject/test/failures

When the exception was thrown, this was the stack:
#0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:100:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown while running async test code:
Golden "2.png": Pixel test failed, 12.70% diff detected.
Failure feedback can be found at /Users/valentin/Projects/MyProject/test/failures

When the exception was thrown, this was the stack:
#0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:100:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: equals [0, 2, 3, 1, 4, 5] ordered
  Actual: [0, 2, 1, 3, 4, 5]
   Which: at location [2] is <1> instead of <3>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/valentin/Projects/MyProject/test/test.dart:117:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/valentin/Projects/MyProject/test/test.dart line 117
The test description was:
  It should drag the 2nd element after the 4th one
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (3) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════
00:06 +0 -1: It should drag the 2nd element after the 4th one [E]                                                                                                                                                         
  Test failed. See exception logs above.
  The test description was: It should drag the 2nd element after the 4th one
  
[+4607 ms] test 0: Test harness is no longer needed by test process
[        ] test 0: finished
[   +1 ms] test 0: cleaning up...
[        ] test 0: ensuring test device is terminated.
[        ] test 0: Terminating flutter_tester process
[        ] test 0: Shutting down test harness socket server
[        ] test 0: Test process is no longer needed by test harness
[  +41 ms] test 0: flutter_tester process at pid 17828 exited with code=-9
[   +1 ms] test 0: deleting temporary directory
[   +2 ms] test 0: finished
00:06 +0 -1: Some tests failed.                                                                                                                                                                                           
[  +13 ms] Deleting /var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.gkDuiI/flutter_test_compiler.s8ngEB...
[   +3 ms] killing pid 17823
[  +52 ms] Deleting /var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.gkDuiI/flutter_test_fonts.h8Cgvk...
[   +5 ms] test package returned with exit code 1
[  +19 ms] "flutter test" took 8,460ms.
[  +10 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:470:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[  +45 ms] ensureAnalyticsSent: 41ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

With `extra = 1`:

```
$ flutter test --verbose test/test.dart
[  +88 ms] executing: sysctl hw.optional.arm64
[  +15 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +7 ms] executing: [/Users/valentin/flutter/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +16 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] executing: [/Users/valentin/flutter/flutter/] git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[  +29 ms] Exit code 0 from: git tag --points-at 77d935af4db863f6abd0b9c31c7e6df2a13de57b
[        ] 2.8.1
[  +10 ms] executing: [/Users/valentin/flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/valentin/flutter/flutter/] git ls-remote --get-url origin
[  +16 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +106 ms] executing: [/Users/valentin/flutter/flutter/] git rev-parse --abbrev-ref HEAD
[  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +5 ms] executing: sw_vers -productName
[  +14 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +17 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.5.1
[        ] executing: sw_vers -buildVersion
[  +16 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20G80
[  +64 ms] Found 1 files which will be executed as Widget Tests.
[   +9 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +47 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +82 ms] Skipping pub get: version match.
[  +29 ms] Found plugin sqlcipher_flutter_libs at /Users/valentin/.pub-cache/git/sqlite3.dart-51ddd3832a51c771bc9160510b3a8143ce5597d0/sqlcipher_flutter_libs/
[   +9 ms] Found plugin amplitude_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/
[  +31 ms] Found plugin camera at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/camera-0.8.1+7/
[  +17 ms] Found plugin device_info at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.2/
[   +2 ms] Found plugin device_info_plus at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus-3.1.0/
[   +1 ms] Found plugin device_info_plus_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus_macos-2.2.0/
[   +2 ms] Found plugin device_info_plus_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus_web-2.1.0/
[  +15 ms] Found plugin file_picker at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/file_picker-4.2.7/
[   +1 ms] Found plugin firebase_core at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.7.0/
[   +2 ms] Found plugin firebase_core_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/
[   +1 ms] Found plugin firebase_messaging at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-10.0.8/
[   +1 ms] Found plugin firebase_messaging_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_web-2.0.6/
[   +4 ms] Found plugin flutter_inappwebview at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/
[        ] Found plugin flutter_keyboard_visibility at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-5.1.0/
[   +1 ms] Found plugin flutter_keyboard_visibility_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility_web-2.0.0/
[   +1 ms] Found plugin flutter_local_notifications at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-5.0.0+4/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.3/
[   +1 ms] Found plugin flutter_secure_storage at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-4.2.1/
[   +5 ms] Found plugin geocoding at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.1/
[   +1 ms] Found plugin geolocator at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator-7.7.0/
[        ] Found plugin geolocator_android at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_android-2.1.0/
[   +1 ms] Found plugin geolocator_apple at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.2.2/
[   +1 ms] Found plugin geolocator_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_web-2.0.6/
[  +11 ms] Found plugin image_cropper at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.4.1/
[   +1 ms] Found plugin image_picker at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/
[   +1 ms] Found plugin image_picker_for_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/
[  +12 ms] Found plugin native_pdf_renderer at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/native_pdf_renderer-3.1.0/
[   +4 ms] Found plugin open_file at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/open_file-3.2.1/
[   +1 ms] Found plugin package_info_plus at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus-1.3.0/
[   +1 ms] Found plugin package_info_plus_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus_macos-1.3.0/
[   +1 ms] Found plugin package_info_plus_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus_web-1.0.4/
[   +3 ms] Found plugin path_provider at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.4/
[   +1 ms] Found plugin path_provider_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.0/
[   +1 ms] Found plugin path_provider_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.2/
[   +1 ms] Found plugin path_provider_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.3/
[   +1 ms] Found plugin permission_handler at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.1.6/
[   +7 ms] Found plugin sentry_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/sentry_flutter-6.1.2/
[   +1 ms] Found plugin shared_preferences at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.7/
[        ] Found plugin shared_preferences_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.2/
[   +1 ms] Found plugin shared_preferences_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.2/
[   +1 ms] Found plugin shared_preferences_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.2/
[        ] Found plugin shared_preferences_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.2/
[   +5 ms] Found plugin sqflite at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.0+4/
[   +7 ms] Found plugin uni_links at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/uni_links-0.5.1/
[   +1 ms] Found plugin uni_links_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/uni_links_web-0.1.0/
[   +2 ms] Found plugin url_launcher at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.10/
[   +1 ms] Found plugin url_launcher_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.2/
[   +1 ms] Found plugin url_launcher_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.2/
[   +1 ms] Found plugin url_launcher_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.4/
[        ] Found plugin url_launcher_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.2/
[   +4 ms] Found plugin webview_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.13/
[ +104 ms] Found plugin sqlcipher_flutter_libs at /Users/valentin/.pub-cache/git/sqlite3.dart-51ddd3832a51c771bc9160510b3a8143ce5597d0/sqlcipher_flutter_libs/
[   +1 ms] Found plugin amplitude_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/
[   +9 ms] Found plugin camera at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/camera-0.8.1+7/
[   +6 ms] Found plugin device_info at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.2/
[   +1 ms] Found plugin device_info_plus at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus-3.1.0/
[   +1 ms] Found plugin device_info_plus_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus_macos-2.2.0/
[   +1 ms] Found plugin device_info_plus_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus_web-2.1.0/
[   +7 ms] Found plugin file_picker at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/file_picker-4.2.7/
[        ] Found plugin firebase_core at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.7.0/
[        ] Found plugin firebase_core_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/
[        ] Found plugin firebase_messaging at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-10.0.8/
[        ] Found plugin firebase_messaging_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_web-2.0.6/
[   +4 ms] Found plugin flutter_inappwebview at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/
[   +1 ms] Found plugin flutter_keyboard_visibility at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-5.1.0/
[   +1 ms] Found plugin flutter_keyboard_visibility_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility_web-2.0.0/
[   +1 ms] Found plugin flutter_local_notifications at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-5.0.0+4/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.3/
[   +1 ms] Found plugin flutter_secure_storage at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-4.2.1/
[   +2 ms] Found plugin geocoding at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.1/
[        ] Found plugin geolocator at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator-7.7.0/
[        ] Found plugin geolocator_android at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_android-2.1.0/
[        ] Found plugin geolocator_apple at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.2.2/
[        ] Found plugin geolocator_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_web-2.0.6/
[   +6 ms] Found plugin image_cropper at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.4.1/
[        ] Found plugin image_picker at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/
[        ] Found plugin image_picker_for_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/
[   +5 ms] Found plugin native_pdf_renderer at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/native_pdf_renderer-3.1.0/
[   +1 ms] Found plugin open_file at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/open_file-3.2.1/
[   +1 ms] Found plugin package_info_plus at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus-1.3.0/
[        ] Found plugin package_info_plus_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus_macos-1.3.0/
[        ] Found plugin package_info_plus_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus_web-1.0.4/
[   +1 ms] Found plugin path_provider at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.4/
[   +1 ms] Found plugin path_provider_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.0/
[        ] Found plugin path_provider_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.2/
[        ] Found plugin path_provider_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.3/
[   +1 ms] Found plugin permission_handler at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.1.6/
[   +4 ms] Found plugin sentry_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/sentry_flutter-6.1.2/
[        ] Found plugin shared_preferences at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.7/
[        ] Found plugin shared_preferences_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.2/
[        ] Found plugin shared_preferences_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.2/
[        ] Found plugin shared_preferences_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.2/
[        ] Found plugin shared_preferences_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.2/
[   +3 ms] Found plugin sqflite at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.0+4/
[   +6 ms] Found plugin uni_links at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/uni_links-0.5.1/
[        ] Found plugin uni_links_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/uni_links_web-0.1.0/
[   +1 ms] Found plugin url_launcher at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.10/
[        ] Found plugin url_launcher_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.2/
[        ] Found plugin url_launcher_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.2/
[        ] Found plugin url_launcher_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.4/
[        ] Found plugin url_launcher_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.2/
[   +2 ms] Found plugin webview_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.13/
[  +25 ms] Generating /Users/valentin/Projects/MyProject/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +35 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +634 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 12.5.1
           Build version 12E507
[ +289 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +15 ms] running test package with arguments: [-r, compact, --timeout, 30s, --concurrency=10, --chain-stack-traces, --, /Users/valentin/Projects/MyProject/test/test.dart]
00:00 +0: loading /Users/valentin/Projects/MyProject/test/test.dart                                                                                                                                                      [ +304 ms] test 0: starting test /Users/valentin/Projects/MyProject/test/test.dart
[   +5 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/valentin/Projects/MyProject
[   +4 ms] Compiler will use the following file as its incremental dill file: /var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.xjMKrH/flutter_test_compiler.G9vZfr/output.dill
[        ] Listening to compiler controller...
[  +14 ms] Compiling file:///var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.xjMKrH/flutter_test_listener.3tYcKH/listener.dart
[  +14 ms] Found plugin sqlcipher_flutter_libs at /Users/valentin/.pub-cache/git/sqlite3.dart-51ddd3832a51c771bc9160510b3a8143ce5597d0/sqlcipher_flutter_libs/
[   +3 ms] Found plugin amplitude_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/amplitude_flutter-3.8.0/
[  +13 ms] Found plugin camera at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/camera-0.8.1+7/
[   +9 ms] Found plugin device_info at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info-2.0.2/
[   +1 ms] Found plugin device_info_plus at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus-3.1.0/
[   +1 ms] Found plugin device_info_plus_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus_macos-2.2.0/
[   +1 ms] Found plugin device_info_plus_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/device_info_plus_web-2.1.0/
[  +11 ms] Found plugin file_picker at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/file_picker-4.2.7/
[        ] Found plugin firebase_core at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.7.0/
[        ] Found plugin firebase_core_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/
[        ] Found plugin firebase_messaging at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-10.0.8/
[   +1 ms] Found plugin firebase_messaging_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_web-2.0.6/
[   +2 ms] Found plugin flutter_inappwebview at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/
[        ] Found plugin flutter_keyboard_visibility at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-5.1.0/
[   +1 ms] Found plugin flutter_keyboard_visibility_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility_web-2.0.0/
[        ] Found plugin flutter_local_notifications at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-5.0.0+4/
[        ] Found plugin flutter_plugin_android_lifecycle at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.3/
[   +1 ms] Found plugin flutter_secure_storage at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-4.2.1/
[   +3 ms] Found plugin geocoding at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.1/
[   +1 ms] Found plugin geolocator at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator-7.7.0/
[        ] Found plugin geolocator_android at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_android-2.1.0/
[        ] Found plugin geolocator_apple at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.2.2/
[        ] Found plugin geolocator_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/geolocator_web-2.0.6/
[   +5 ms] Found plugin image_cropper at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.4.1/
[        ] Found plugin image_picker at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+1/
[        ] Found plugin image_picker_for_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/
[   +7 ms] Found plugin native_pdf_renderer at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/native_pdf_renderer-3.1.0/
[   +1 ms] Found plugin open_file at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/open_file-3.2.1/
[        ] Found plugin package_info_plus at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus-1.3.0/
[        ] Found plugin package_info_plus_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus_macos-1.3.0/
[        ] Found plugin package_info_plus_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/package_info_plus_web-1.0.4/
[   +1 ms] Found plugin path_provider at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.4/
[        ] Found plugin path_provider_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.0/
[        ] Found plugin path_provider_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.2/
[        ] Found plugin path_provider_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.3/
[        ] Found plugin permission_handler at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.1.6/
[   +3 ms] Found plugin sentry_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/sentry_flutter-6.1.2/
[        ] Found plugin shared_preferences at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.7/
[        ] Found plugin shared_preferences_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.2/
[        ] Found plugin shared_preferences_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.2/
[        ] Found plugin shared_preferences_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.2/
[        ] Found plugin shared_preferences_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.2/
[   +3 ms] Found plugin sqflite at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.0+4/
[   +4 ms] Found plugin uni_links at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/uni_links-0.5.1/
[        ] Found plugin uni_links_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/uni_links_web-0.1.0/
[        ] Found plugin url_launcher at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.10/
[        ] Found plugin url_launcher_linux at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.2/
[        ] Found plugin url_launcher_macos at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.2/
[        ] Found plugin url_launcher_web at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.4/
[        ] Found plugin url_launcher_windows at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.2/
[   +2 ms] Found plugin webview_flutter at /Users/valentin/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.13/
[  +17 ms] /Users/valentin/flutter/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/valentin/flutter/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/valentin/flutter/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --no-print-incremental-dependencies --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.xjMKrH/flutter_test_compiler.G9vZfr/output.dill --packages
/Users/valentin/Projects/MyProject/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --initialize-from-dill
/Users/valentin/Projects/MyProject/build/test_cache/build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
[  +40 ms] <- compile file:///Users/valentin/Projects/MyProject/.dart_tool/flutter_build/generated_main.dart
00:01 +0: loading /Users/valentin/Projects/MyProject/test/test.dart                                                                                                                                                      [+1392 ms] <- accept
[        ] <- reset
[        ] Compiling file:///var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.xjMKrH/flutter_test_listener.3tYcKH/listener.dart took 1566ms
[        ] test 0: starting test device
[   +5 ms] test 0: awaiting connection to test device
[   +2 ms] test 0: Observatory uri is not available
[   +6 ms] test 0: test harness socket server is running at port:57461
[   +7 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[   +2 ms] Using this directory for fonts configuration: /var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.xjMKrH/flutter_test_fonts.fw0PEN
[   +1 ms] test 0: Starting flutter_tester process with command=[/Users/valentin/flutter/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester, --disable-observatory, --enable-checked-mode, --verify-entry-points,
--enable-software-rendering, --skia-deterministic-rendering, --enable-dart-profiling, --non-interactive, --use-test-fonts, --packages=/Users/valentin/Projects/MyProject/.dart_tool/package_config.json,
/var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.xjMKrH/flutter_test_listener.3tYcKH/listener.dart.dill], environment={FLUTTER_TEST: true, FONTCONFIG_FILE:
/var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.xjMKrH/flutter_test_fonts.fw0PEN/fonts.conf, SERVER_PORT: 57461, APP_NAME: my_project, UNIT_TEST_ASSETS:
/Users/valentin/Projects/MyProject/build/unit_test_assets}
[   +9 ms] test 0: Started flutter_tester process at pid 17511
00:02 +0: loading /Users/valentin/Projects/MyProject/test/test.dart                                                                                                                                                      [ +710 ms] test 0: connected to test device, now awaiting test result
[        ] test 0: Waiting for test harness or tests to finish
00:05 +0: It should drag the 2nd element after the 4th one                                                                                                                                                                
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: equals [0, 2, 3, 1, 4, 5] ordered
  Actual: [0, 2, 3, 4, 1, 5]
   Which: at location [3] is <4> instead of <1>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/valentin/Projects/MyProject/test/test.dart:117:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/valentin/Projects/MyProject/test/test.dart line 117
The test description was:
  It should drag the 2nd element after the 4th one
════════════════════════════════════════════════════════════════════════════════════════════════════
00:05 +0 -1: It should drag the 2nd element after the 4th one [E]                                                                                                                                                         
  Test failed. See exception logs above.
  The test description was: It should drag the 2nd element after the 4th one
  
[+3249 ms] test 0: Test harness is no longer needed by test process
[        ] test 0: finished
[   +1 ms] test 0: cleaning up...
[        ] test 0: ensuring test device is terminated.
[        ] test 0: Terminating flutter_tester process
[        ] test 0: Shutting down test harness socket server
[        ] test 0: Test process is no longer needed by test harness
[  +34 ms] test 0: flutter_tester process at pid 17511 exited with code=-9
[        ] test 0: deleting temporary directory
[   +2 ms] test 0: finished
00:05 +0 -1: Some tests failed.                                                                                                                                                                                           
[  +14 ms] Deleting /var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.xjMKrH/flutter_test_compiler.G9vZfr...
[   +3 ms] killing pid 17500
[  +37 ms] Deleting /var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/flutter_tools.xjMKrH/flutter_test_fonts.fw0PEN...
[   +3 ms] test package returned with exit code 1
[  +14 ms] "flutter test" took 7,615ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:470:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[  +53 ms] ensureAnalyticsSent: 48ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
$ flutter analyze
Analyzing MyProject...
No issues found! (ran in 26.6.s)
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.1 20G80 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /Users/valentin/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /usr/local/Caskroom/android-sdk/4333796
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.1 20G80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.71

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This documentation PR adds several 'see also' sections in order to make `WidgetController.timedDrag` more discoverable. 

## Related Issue

Fixes https://github.com/flutter/flutter/issues/96893

## Tests

No Test, documentation update only.

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
@loic-sharma Can you do a secondary review?

**Review by loic-sharma — APPROVED** [review]

File: packages/flutter_test/lib/src/controller.dart [hunk 1]
```diff
@@ -781,6 +781,11 @@ abstract class WidgetController {
   ///
   /// You can use [createGesture] if your gesture doesn't begin with an initial
   /// down gesture.
+  ///
+  /// See also:
+  /// - [WidgetController.drag], a method to simulate a drag.
+  /// - [WidgetController.timedDrag], a method to simulate the drag of a given widget in a given duration. It sends move events at a given frequency and it is useful when there are listeners involved.
+  /// - [WidgetController.fling], a method to simulate a fling.
```
Comment (dkwingsmt) [inline packages/flutter_test/lib/src/controller.dart:788]:
```suggestion
  ///  * [WidgetController.drag], a method to simulate a drag.
  ///  * [WidgetController.timedDrag], a method to simulate the drag of a given widget in a given duration.
  ///    It sends move events at a given frequency and it is useful when there are listeners involved.
  ///  * [WidgetController.fling], a method to simulate a fling.
```

File: packages/flutter_test/lib/src/test_pointer.dart [hunk 2]
```diff
@@ -463,6 +463,11 @@ class TestGesture {
   ///
   /// If the pointer is down, then a move event is dispatched. If the pointer is
   /// up, then a hover event is dispatched.
+  ///
+  /// See also:
+  /// - [WidgetController.drag], a method to simulate a drag.
+  /// - [WidgetController.timedDrag], a method to simulate the drag of a given widget in a given duration. It sends move events at a given frequency and it is useful when there are listeners involved.
+  /// - [WidgetController.fling], a method to simulate a fling.
```
Comment (dkwingsmt) [inline packages/flutter_test/lib/src/test_pointer.dart:470]:
```suggestion
  ///  * [WidgetController.drag], a method to simulate a drag.
  ///  * [WidgetController.timedDrag], a method to simulate the drag of a given widget in a given duration.
  ///    It sends move events at a given frequency and it is useful when there are listeners involved.
  ///  * [WidgetController.fling], a method to simulate a fling.
```

File: packages/flutter_test/lib/src/test_pointer.dart [hunk 3]
```diff
@@ -472,6 +477,11 @@ class TestGesture {
...
```
Comment (dkwingsmt) [inline packages/flutter_test/lib/src/test_pointer.dart:484]:
```suggestion
  ///  * [WidgetController.drag], a method to simulate a drag.
  ///  * [WidgetController.timedDrag], a method to simulate the drag of a given widget in a given duration.
  ///    It sends move events at a given frequency and it is useful when there are listeners involved.
  ///  * [WidgetController.fling], a method to simulate a fling.
```

**Review by dkwingsmt — CHANGES_REQUESTED** [review]
Some bikeshedding on format. Otherwise good!

**Review by dkwingsmt — APPROVED** [review]
LGTM
