### PR TITLE
[web] Use platform detection from Flutter web engine.

### LINKED ISSUE #128943: Theme.of(context).platform running on web returns macOS instead of iOS when accessed from Safari on iPad
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Make an app that prints `Theme.of(context).platform` in the middle of the screen
2. Build it for the web
3. Publish it online
4. Access that web from Safari on iPad

If you want to see the bug by yourself in a quick fashion, for convenience, a website that reproduces the issue has been published here: https://flutterthemeplatform.codemagic.app/

### Expected results

It should print `iOS`

### Actual results

It prints `macOS`

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Theme Platform',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Theme Platform"),
      ),
      body: Center(
        child: Text(
          'Theme.of(context).platform is ${Theme.of(context).platform}',
        ),
      ),
    );
  }
}
```

</details>

Here's the repo of this code: https://github.com/fewlaps/theme-platform-flutter

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Screenshot 2023-06-15 at 13 54 50

</details>

### Logs

<details><summary>Logs</summary>

```console
== Building for Web ==

> flutter build web
Resolving dependencies...
  collection 1.17.1 (1.17.2 available)
  lints 2.0.1 (2.1.1 available)
  matcher 0.12.15 (0.12.16 available)
  material_color_utilities 0.2.0 (0.5.0 available)
  source_span 1.9.1 (1.10.0 available)
  test_api 0.5.1 (0.6.0 available)
Got dependencies!

Compiling lib/main.dart for the Web...                          
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7548 bytes (99.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 1236 bytes (99.6% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Compiling lib/main.dart for the Web...                             15.4s
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
roc@Pitxoli theme-platform-flutter % fvm flutter doctor -v
[!] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E772610a darwin-arm64, locale en-ES)
    • Flutter version 3.10.5 on channel stable at /Users/roc/fvm/versions/3.10.5
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.7/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/roc/fvm/versions/3.10.5. Consider adding /Users/roc/fvm/versions/3.10.5/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (2 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/roc/Development/android
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • iPhone 14 Pro Max (mobile)                     • 0DF12398-20BE-41AA-A069-77F282BF9BF5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPad Pro (12.9-inch) (6th generation) (mobile) • DC32C696-0FD5-48B8-9627-617D11465469 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                                • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

### PR DESCRIPTION
**Pull request by ditman**
> [!IMPORTANT]
> Requires the following engine PR:
> * https://github.com/flutter/engine/pull/52380
> ----

This PR refactors Flutter `foundation`'s library `platform` for the web with the same code we use to detect platforms in the engine.

## Issues

* Fixes: https://github.com/flutter/flutter/issues/128943

## Testing

Demo app deployed here:

* https://dit-browser-detect.web.app

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by ditman** [comment]
Rebased with latest master, marking as ready for review!

**Comment by ditman** [comment]
Rebasing again to give FROB a chance to pick up the engine-related changes as well.

File: packages/flutter/lib/src/foundation/_platform_web.dart [hunk 1]
```diff
@@ -30,35 +29,18 @@ final platform.TargetPlatform? _testPlatform = () {
...
-  }
-  return platform.TargetPlatform.android;
+  return switch (ui_web.browser.operatingSystem) {
+    ui_web.OperatingSystem.android => platform.TargetPlatform.android,
+    ui_web.OperatingSystem.iOs => platform.TargetPlatform.iOS,
+    ui_web.OperatingSystem.linux => platform.TargetPlatform.linux,
+    ui_web.OperatingSystem.macOs => platform.TargetPlatform.macOS,
+    ui_web.OperatingSystem.windows => platform.TargetPlatform.windows,
+    // Default 'unknown' OS values to `android`.
+    _ => platform.TargetPlatform.android,
```
Comment (Hixie) [inline packages/flutter/lib/src/foundation/_platform_web.dart:44]: why do we need a default? shouldn't this always be exhaustive?

**Comment by ditman** [comment]
> is it possible to write a test that just spot checks that it's actually using the engine values and not just coincidentally implementing the same algorithm?

@Hixie hmm... not sure I can inspect directly that the code I'm using is from the engine, but I think I can mock something wacky in the engine, then ensure that the framework returns the same.

Thanks!

File: packages/flutter/lib/src/foundation/_platform_web.dart (hunk 1 above)
Comment (ditman) [reply packages/flutter/lib/src/foundation/_platform_web.dart:44]: @Hixie I added the default so the engine can roll into the framework without breaking if we add a new `OperatingSystem` value.

Comment (ditman) [reply packages/flutter/lib/src/foundation/_platform_web.dart]: Made the switch expression exhaustive.

**Comment by ditman** [comment]
Tweaked the `_testPlatform` variable (so it may be overridden by tests), and made it respect the ui_web override. The test now tests the code of the function that translates between OperatingSystem and Flutter.

File: packages/flutter/lib/src/foundation/_platform_web.dart [hunk 2]
```diff
@@ -19,46 +18,45 @@ platform.TargetPlatform get defaultTargetPlatform {
       _browserPlatform;
 }
 
-final platform.TargetPlatform? _testPlatform = () {
-  platform.TargetPlatform? result;
+// The TargetPlatform used ON WEB TESTS, unless overridden.
+//
+// Respects the `ui_web.browser.debugOperatingSystemOverride` value (when set).
+platform.TargetPlatform? get _testPlatform {
+  platform.TargetPlatform? testPlatform;
```
Comment (ditman) [inline packages/flutter/lib/src/foundation/_platform_web.dart:25]: Note that this used to be a `final` variable computed from an IIFE, but it needs to be a `getter` so it can be overridden as needed from tests. The getter ends up as an empty function when asserts are disabled, so I hope this doesn't cause a huge performance hit.

Comment (mdebbar) [reply packages/flutter/lib/src/foundation/_platform_web.dart]: Maybe `@pragma('dart2js:tryInline')` could help?

**Review by mdebbar — APPROVED** [review]

File: packages/flutter/lib/src/foundation/_platform_web.dart (hunk 2 above)
Comment (ditman) [reply packages/flutter/lib/src/foundation/_platform_web.dart]: Brought this up with the dart2js people, and they confirmed that the annotation is not needed; @biggs0125 said:

> Dart2js should do a pretty good job of inlining that code when assertions are disabled, even without the annotation. We should be able to tell that (1) the code has no side effects and (2) the code always returns null. So it should just inline a null into the callsite.

(I hope it doesn't make `debug` mode too miserable! In that case, I'd walk back the changes that I added just for testing, and find another way)
