### PR TITLE
BottomNavigationBar: fix the calculation of the expanding circle animation

### LINKED ISSUE #6046: Bottom nav: new color animation does not start under tap in landscape
On a Nexus 6P, and Nexus 5, and iPhone 6.

Open Gallery, go landscape, open Bottom navigation. Tap on all four options. Notice how after you tap the first option, the later taps will start a color animation outside of the tap location. This effect is especially noticeable on the far right and left items.

Video of the effect in action: https://youtu.be/vlWN4swz4U8

### PR DESCRIPTION
**Pull request by jason-simmons**
The circle's offset represents the position of a navigation button within the
row of buttons.  Previously, this offset had been applied to the entire width
of the bottom bar, not just the button region.

Fixes https://github.com/flutter/flutter/issues/6046

### CODE REVIEW

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 1]
```diff
@@ -514,10 +515,12 @@ class _Circle {
 
 class _RadialPainter extends CustomPainter {
   _RadialPainter({
-    this.circles
+    this.circles,
+    this.bottomNavMaxWidth,
   });
 
   final List<_Circle> circles;
+  final double bottomNavMaxWidth;
```
Comment (Hixie) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart]: also update shouldRepaint

**Comment by Hixie** [comment]
LGTM

**Comment by sethladd** [comment]
Great! Thanks for taking a look. Did you test this in landscape, too?

**Comment by jason-simmons** [comment]
Yes, this should work for any width
