### PR TITLE
fix GestureDetector.onDoubleTapDown not getting called

### LINKED ISSUE #107770: GestureDetector doesn't call onDoubleTapDown if there's no onDoubleTap callback
I have a `GestureDetector` where I want to respond to a double-tap at a specific location. This requires responding to `onDoubleTapDown`. However, the only way I can get `onDoubleTapDown` to be called, is if I also provide a callback for `onDoubleTap`. 

```dart
GestureDetector(
  onDoubleTapDown: _onDoubleTapDown,
  onDoubleTap: () {}, // onDoubleTapDown only seems to fire if we include a callback here, too
);
```

Flutter version:
```
Flutter 3.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 85684f9300 (2 weeks ago) • 2022-06-30 13:22:47 -0700
Engine • revision 6ba2af10bb
Tools • Dart 2.17.5 • DevTools 2.12.2
```

### PR DESCRIPTION
**Pull request by pedromassango**
Fixes https://github.com/flutter/flutter/issues/107770

## Tests

Adds two tests:
- [x] Assert that `onDoubleTap` gets called without providing `onDoubleTapDown`.
- [x] Assert that `onDoubleTapDown` gets called even if `onDoubleTap` has not been provided.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/gesture_detector.dart [hunk 1]
```diff
@@ -1041,7 +1041,7 @@ class GestureDetector extends StatelessWidget {
       );
     }
 
-    if (onDoubleTap != null) {
+    if (onDoubleTap != null || onDoubleTapDown != null) {
```
Comment (tvolkert) [inline packages/flutter/lib/src/widgets/gesture_detector.dart:1044]: `|| onDoubleTapCancel != null`

**Review by tvolkert — APPROVED** [review]
LGTM modulo one small comment

**Review by dkwingsmt — APPROVED** [review]
LGTM
