### PR TITLE
Gradient transform

### LINKED ISSUE #23648: SweepGradient startAngle doesn't work as expected.
I want to create something like this. 
gear
I use shader created from SweepGradient. Here's my code.
```dart  

    import 'package:flutter/material.dart';
    import 'dart:math';

    class Arc extends CustomPainter {

    double doubleToAngle(double angle) => angle * pi / 180.0;

    void drawArcWithRadius(
        Canvas canvas, Offset center, double radius, double angle, Paint paint) {
        canvas.drawArc(Rect.fromCircle(center: center, radius: radius),
          doubleToAngle(-90.0), doubleToAngle(angle), false, paint);
    }

    @override
    void paint(Canvas canvas, Size size) {
      final Offset center = Offset(size.width / 2.0, size.height / 2.0);
      final double radius = size.width / 3.0;
      double angle = 210.0;
      Paint paint = Paint()
        ..strokeCap = StrokeCap.round
        ..strokeWidth = 40.0
        ..style = PaintingStyle.stroke
        ..color = Colors.red
        ..shader = new SweepGradient(colors: [
          Color(0xFFB4EC51),
          Color(0xFF3023AE),
        ], startAngle: 0.0, endAngle: doubleToAngle(angle))
            .createShader(Rect.fromCircle(center: center, radius: radius));
  
      drawArcWithRadius(canvas, center, radius, angle, paint);
    }

    @override
    bool shouldRepaint(CustomPainter oldDelegate) {
      return true;
    }
    }
```

But it ends up something like this.
hvh6i
It seems like sweepAngle doesn't have any effect.

### PR DESCRIPTION
**Pull request by dnfield**
## Description

Exposes the `transform` parameter for gradients into the framework via a `GradientTransform` class, which is akin to `Alignment` or `EdgeInsets` in that it resolves an actual `Matrix4` by means of a `Rect` (and potentially a `TextDirection`). This enables more easily creating rotated gradient effects without having to rotate the entire canvas.

Fixes https://github.com/flutter/flutter/issues/23648

## Related Issues

https://github.com/flutter/flutter/issues/23648

## Tests

I added the following tests:

Golden tests for transformed gradients.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/painting/gradient.dart [hunk 1]
```diff
@@ -124,7 +125,41 @@ abstract class Gradient {
...
+  ///   // Calculate the point to rotate about.
+  ///   final double sinRadians = math.sin(radians);
+  ///   final double oneMinusCosRadians = 1 - math.cos(radians);
+  ///   final Offset center = rect.center;
+  ///   final double originX = sinRadians * center.dy + oneMinusCosRadians * center.dx;
+  ///   final double originY = -sinRadians * center.dx + oneMinusCosRadians * center.dy;
+  ///
+  ///   final Matrix4 transform = Matrix4.identity()
+  ///     ..translate(originX, originY)
+  ///     ..rotateZ(radians);
```
Comment (dnfield) [inline packages/flutter/lib/src/painting/gradient.dart]: I suspect having amethod like this in the framework might be helpful to people, but I'm not sure where it would go.  MatrixUtils?

@goderbauer wdyt?

**Comment by Hixie** [comment]
Would it make more sense for the matrix to be a property rather than something you pass to createShader? The shader is created pretty low-down, most people don't use that API.

**Comment by dnfield** [comment]
The thing is, you're generally going to need to know the `Rect` that's being used for `createShader` to make sense of what to do with your matrix.  And the people requesting this in the linked bug were already using `createShader` to apply this to a `Paint` object's `shader` property in things like a `CustomPaint` anyway.

It would be nice but I'm not sure how we'd really abstract the rect away properly.

**Comment by dnfield** [comment]
We could maybe give it a callback where you're given a rect and you give back a transform, like:

```dart
typdef MatrixBuilder = Matrix4 Function(Rect rect);
```

And then `createShader` would call that and use the transform created by that to transform the shader.  That would make this more useable in something like a `BoxDecoration`. WDYT?

**Comment by Hixie** [comment]
We could also take a new kind of class that represents a matrix transform. That class would have a method on it that takes a rect to do the actual transform computation. This is analogous to what we do wiht `Alignment` or `EdgeInsets` (both of which need the actual Rect to do their actual work, but don't have it available when you specify them).

**Comment by dnfield** [comment]
I've added a `GradientTransform` and a `GradientRotation` class.

We could trivially implement things like `GradientTranslate` and `GradientSkew` and the like - rotation is probably the hardest of the bunch though and it's the only one being asked for right now.

File: packages/flutter/lib/src/painting/gradient.dart [hunk 2]
```diff
@@ -57,6 +59,63 @@ _ColorsAndStops _interpolateColorsAndStops(
   return _ColorsAndStops(interpolatedColors, interpolatedStops);
 }
 
+/// Base class for transforming gradient shaders without applying the same
+/// transform to the entire canvas.
+///
+/// For example, a [SweepGradient] normally starts its gradation at 3 o'clock
+/// and draws clockwise. To have the sweep appear to start at 6 o'clock, supply
+/// a [GradientRotation] of `0.785398` radians (i.e. `45` degrees).
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/gradient.dart]: trivial nit: I think our style is to not use backticks for literals.

File: packages/flutter/lib/src/painting/gradient.dart [hunk 3]
```diff
@@ -57,6 +59,63 @@ _ColorsAndStops _interpolateColorsAndStops(
...
+@immutable
+abstract class GradientTransform {
+  /// A const constructor that allows subclasses to be const.
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/gradient.dart]: there's a boilerplate paragraph we use for this kind of thing.

File: packages/flutter/lib/src/painting/gradient.dart [hunk 4]
```diff
@@ -57,6 +59,63 @@ _ColorsAndStops _interpolateColorsAndStops(
...
+///
+/// For example, the following would rotate a sweep gradient by a quarter turn
+/// clockwise:
+///
+/// ```dart
+/// SweepGradient(
+///   colors: colors,
+///   transform: GradientRotation(0.785398),
+/// );
+/// ```
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/gradient.dart]: we should use the sample code logic for this

File: packages/flutter/lib/src/painting/gradient.dart [hunk 5]
```diff
@@ -57,6 +59,63 @@ _ColorsAndStops _interpolateColorsAndStops(
...
+@immutable
+class GradientRotation extends GradientTransform {
+  /// Constructs a `GradientRotation` for the specified angle.
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/gradient.dart]: use `[]` for identifiers

File: packages/flutter/lib/src/painting/gradient.dart [hunk 6]
```diff
@@ -57,6 +59,63 @@ _ColorsAndStops _interpolateColorsAndStops(
...
+  ///
+  /// The angle is in radians in the clockwise direction.
+  const GradientRotation(this.radians);
+
+  /// The angle of rotation.
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/gradient.dart]: This needs more detail, e.g. direction of rotation (clockwise, counter-clockwise), the units (though it's pretty obvious from the name).

File: packages/flutter/lib/src/painting/gradient.dart [hunk 7]
```diff
@@ -76,9 +135,17 @@ abstract class Gradient {
   /// If specified, the [stops] argument must have the same number of entries as
   /// [colors] (this is also not verified until the [createShader] method is
   /// called).
+  ///
+  /// The [transform] argument can be applied to transform _only_ the gradient,
+  /// without rotating the canvas itself or other geometry on the canvas. For
+  /// example, a `GradientRotation(0.785398)` will result in a [SweepGradient]
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/gradient.dart]: here and elsewhere, rather than 0.785398 we should say pi/4

**Comment by Hixie** [comment]
This looks great!
LGTM

**Comment by dnfield** [comment]
In case it's not obvious - I've rev'd goldens a few times in this because I've made very minor changes to the tests that are resulting in miniscule pixel differences.
