### PR TITLE
Fix `StretchingOverscrollIndicator` clipping and add `clipBehavior` parameter

### LINKED ISSUE #103491: [Android]: `StretchingOverscrollIndicator` clips `ListView` while scrolling horizontally
## Details

I'm using a custom clip for the visible shadow but when I use `StretchingOverscrollIndicator` it automatically clips my `ListView`. 

**Target Platform:** Android
**Target OS version/browser:** 12

## Logs

<details>
<summary>Logs</summary>

https://user-images.githubusercontent.com/62325868/167863954-7a6c29e7-e925-4a15-b8a5-d0c47ae55e3a.mov

flutter doctor -v

```js
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm (Rosetta), locale en-VN)
    • Flutter version 3.0.0 at /Users/daiduong/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/daiduong/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm (Rosetta)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details>
<summary>The code</summary>
My reproduce code

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const SampleCode());
}

class SampleCode extends StatelessWidget {
  const SampleCode({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: Scaffold(
          appBar: AppBar(title: const Text('Issue')),
          body: Padding(
            padding: const EdgeInsets.symmetric(vertical: 30),
            child: Column(
              children: [
                NumberSeclectBar(
                  title: "ScrollTest",
                  value: 1,
                  onChanged: (_) {},
                ),
                const SizedBox(height: 10),
                NumberSeclectBar(
                  title: "ScrollTest",
                  value: 1,
                  onChanged: (_) {},
                ),
                const SizedBox(height: 10),
                NumberSeclectBar(
                  title: "ScrollTest",
                  value: 1,
                  onChanged: (_) {},
                ),
                const SizedBox(height: 10),
                NumberSeclectBar(
                  title: "ScrollTest",
                  value: 1,
                  onChanged: (_) {},
                ),
                const SizedBox(height: 10),
                NumberSeclectBar(
                  title: "ScrollTest",
                  value: 1,
                  onChanged: (_) {},
                ),
              ],
            ),
          ),
      ),
    );
  }
}

class NumberSeclectBar extends StatelessWidget {
  const NumberSeclectBar({
    Key? key,
    required this.title,
    required this.value,
    required this.onChanged,
    this.required = true,
    this.subtitle,
  }) : super(key: key);

  final String title;
  final String? subtitle;
  final int value;
  final ValueChanged<int> onChanged;
  final bool required;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return SizedBox(
      height: 45,
      child: Row(
        children: [
          SizedBox(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(title),
                if (subtitle != null)
                  Text(
                    subtitle!,
                    style: theme.textTheme.bodySmall,
                  ),
              ],
            ),
            width: 100,
          ),
          const SizedBox(width: 10),
          Expanded(
            child: ClipPath(
              clipper: CustomClip(),
              child: ListView.builder(
                padding: EdgeInsets.zero,
                scrollDirection: Axis.horizontal,
                clipBehavior: Clip.none,
                itemBuilder: (context, index) {
                  return Padding(
                    padding: const EdgeInsets.only(right: 10),
                    child: AspectRatio(
                      aspectRatio: 1,
                      child: InkWell(
                        onTap: () {
                          if (required) {
                            onChanged(index + 1);
                            return;
                          }
                          onChanged(index);
                        },
                        borderRadius: BorderRadius.circular(10),
                        child: AnimatedContainer(
                          duration: const Duration(milliseconds: 300),
                          curve: Curves.ease,
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(10),
                            color:
                                (required ? value == index + 1 : value == index)
                                    ? theme.colorScheme.primary
                                    : theme.colorScheme.surface,
                            boxShadow: [
                              BoxShadow(
                                blurRadius: 12,
                                color: theme.colorScheme.primary.withOpacity(1),
                              ),
                            ],
                          ),
                          child: Center(
                            child: Text(
                              required
                                  ? (index + 1).toString()
                                  : index.toString(),
                              style: theme.textTheme.bodyMedium!.copyWith(
                                color: (required
                                        ? value == index + 1
                                        : value == index)
                                    ? theme.colorScheme.onPrimary
                                    : theme.colorScheme.onSurface,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  );
                },
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class CustomClip extends CustomClipper<Path> {
  @override
  Path getClip(Size size) {
    final path = Path();
    path.addRect(
      Rect.fromCenter(
        center: size.center(Offset.zero),
        width: size.width + 20,
        height: size.height + 30,
      ),
    );
    return path;
  }

  @override
  bool shouldReclip(covariant CustomClipper<Path> oldClipper) => false;
}
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/103491

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scroll_view.dart [hunk 1]
```diff
@@ -407,10 +407,16 @@ abstract class ScrollView extends StatelessWidget {
         return buildViewport(context, offset, axisDirection, slivers);
       },
     );
-    final Widget scrollableResult = primary && scrollController != null
+
+    Widget scrollableResult = primary && scrollController != null
         ? PrimaryScrollController.none(child: scrollable)
         : scrollable;
 
+    scrollableResult = OverscrollClipBehavior(
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_view.dart:415]: This may not be necessary to add to the widget tree for every app, especially since the stretch is an opt-in on one platform. Could we instead pass the ScrollView.clipBehavior to Scrollable?
Then Scrollable can include it in the ScrollableDetails it provides to the indicator. :)

**Review by Piinks — COMMENTED** [review]
Thanks for taking this on!

File: packages/flutter/lib/src/widgets/scroll_view.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/widgets/scroll_view.dart]: Thanks for the feedback! Updated the PR.

File: packages/flutter/lib/src/cupertino/app.dart [hunk 2]
```diff
@@ -471,7 +471,12 @@ class CupertinoScrollBehavior extends ScrollBehavior {
   }
 
   @override
-  Widget buildOverscrollIndicator(BuildContext context, Widget child, ScrollableDetails details) {
+  Widget buildOverscrollIndicator(
```
Comment (Piinks) [inline packages/flutter/lib/src/cupertino/app.dart:474]: Changing these function signatures is a breaking change. Rather than passing the clipBehavior, can you add it to ScrollableDetails? That is already being passed here. We created ScrollableDetails for this exact reason, so if we needed to supply more information to decorators like scrollbar and indicators, we would not have to break the function signature here. :) 

https://github.com/flutter/flutter/blob/4dec56b2c9326b33b156bb053c8a6733778fedf7/packages/flutter/lib/src/widgets/scrollable.dart#L1310

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 3]
```diff
@@ -261,6 +262,11 @@ class Scrollable extends StatefulWidget {
   /// [ScrollBehavior].
   final ScrollBehavior? scrollBehavior;
 
+  /// {@macro flutter.material.Material.clipBehavior}
+  ///
+  /// Defaults to [Clip.hardEdge].
+  final Clip clipBehavior;
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scrollable.dart:268]: In this particular case, we should probably document that it does not apply clipping to the Scrollable, rather that is is passed on to decorators in ScrollableDetails.

**Review by Piinks — COMMENTED** [review]
Thanks for the update! Just a doc tweak and this should be good to go!

File: packages/flutter/lib/src/widgets/scrollable.dart (hunk 3 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/widgets/scrollable.dart:268]: That's a great idea, this is not a regular `clipBehavior` property and I tried to find a similar use case of this property in other widgets yesterday and I couldn't find anything like this so I kept it as it is. Updating this doc.

**Review by Piinks — APPROVED** [review]
LGTM! Thank you!
