### PR TITLE
Fix DropdownButtonFormField focusing when replacing FocusNode

### LINKED ISSUE #166642: DropdownButtonFormField can't be focused/unfocused when replacing FocusNode
### Steps to reproduce

Run the sample try focusing/unfocusing after replacing FocusNode similar to the video sample.

### Expected results

1. DropdownButtonFormField can be focused if it was unfocused and we replaced FocusNode.
2. DropdownButtonFormField can be unfocused if it was focused and we replaced FocusNode.

### Actual results

DropdownButtonFormField can't be focused/unfocused when replacing FocusNode.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: DropdownFocusDemo(),
    );
  }
}

class DropdownFocusDemo extends StatefulWidget {
  const DropdownFocusDemo({super.key});

  @override
  State<DropdownFocusDemo> createState() => _DropdownFocusDemoState();
}

class _DropdownFocusDemoState extends State<DropdownFocusDemo> {
  FocusNode _focusNode = FocusNode();
  String _selectedValue = 'One';

  void _replaceFocusNode() {
    setState(() {
      _focusNode.dispose();
      _focusNode = FocusNode();
      print('FocusNode replaced');
    });
  }

  @override
  void dispose() {
    _focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Dropdown Focus Demo')),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            DropdownButtonFormField<String>(
              focusNode: _focusNode,
              focusColor: Colors.yellow,
              decoration: InputDecoration(
                filled: true,
                contentPadding: EdgeInsets.symmetric(vertical: 100),
              ),
              value: _selectedValue,
              items: const [
                DropdownMenuItem(value: 'One', child: Text('One')),
                DropdownMenuItem(value: 'Two', child: Text('Two')),
              ],
              onChanged: (value) {
                setState(() {
                  _selectedValue = value!;
                });
              },
            ),
            const SizedBox(height: 16),
            ElevatedButton(
              onPressed: () {
                _focusNode.requestFocus();
              },
              child: const Text('Request Focus'),
            ),
            ElevatedButton(
              onPressed: _replaceFocusNode,
              child: const Text('Replace FocusNode'),
            ),
            ElevatedButton(
              onPressed: () {
                FocusManager.instance.primaryFocus?.unfocus();
              },
              child: const Text('Remove FocusNode'),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/user-attachments/assets/6ea63510-81c7-4007-a6a1-148f4d485778)

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.3.2 24D81 darwin-arm64, locale en-EG) [1,169ms]
    • Flutter version 3.29.2 on channel stable at /Users/ahmedelsayed/.puro/envs/stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (3 weeks ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [1,263ms]
    • Android SDK at /Users/ahmedelsayed/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • Java binary at: /Users/ahmedelsayed/Library/Java/JavaVirtualMachines/jbr-21.0.6/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment JBR-21.0.6+9-895.97-nomod (build 21.0.6+9-b895.97)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [825ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [13ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [13ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] VS Code (version 1.98.2) [12ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.108.0

[✓] Connected device (5 available) [5.9s]

[✓] Network resources [774ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by AhmedLSayed9**
fixes #166642

**The newly added tests verify the following behaviors:**

1. DropdownButtonFormField can be focused if it was unfocused and we replaced FocusNode.
2. DropdownButtonFormField can be unfocused if it was focused and we replaced FocusNode.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/dropdown.dart [hunk 1]
```diff
@@ -1301,7 +1301,7 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
   _DropdownRoute<T>? _dropdownRoute;
   Orientation? _lastOrientation;
   FocusNode? _internalNode;
-  FocusNode? get focusNode => widget.focusNode ?? _internalNode;
+  FocusNode get focusNode => widget.focusNode ?? _internalNode!;
```
Comment (Hamza-Nasser) [inline packages/flutter/lib/src/material/dropdown.dart:1304]: If both `widget.focusNode` and `_internalNode` are null, this leads to null check exception

Comment (AhmedLSayed9) [reply packages/flutter/lib/src/material/dropdown.dart:1304]: @Hamza-Nasser
They can't both be null

File: packages/flutter/lib/src/material/dropdown.dart [hunk 2]
```diff
@@ -1357,8 +1357,13 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
...
     super.didUpdateWidget(oldWidget);
-    if (widget.focusNode == null) {
-      _internalNode ??= _createFocusNode();
+    if (widget.focusNode != oldWidget.focusNode) {
+      oldWidget.focusNode?.removeListener(_handleFocusChanged);
+      if (widget.focusNode == null) {
+        _internalNode ??= _createFocusNode();
+      }
+      _hasPrimaryFocus = focusNode.hasPrimaryFocus;
+      focusNode.addListener(_handleFocusChanged);
```
Comment (justinmc) [inline packages/flutter/lib/src/material/dropdown.dart:1366]: I think it might be possible for _internalNode to leak a listener. Consider if oldWidget had no focusNode, so it created an _internalNode in initState. Then here there is a widget.focusNode. We should call _internalNode.removeListener, but it looks like we don't.

Comment (justinmc) [reply packages/flutter/lib/src/material/dropdown.dart:1366]: Could you write a test that covers this case?

File: packages/flutter/lib/src/material/dropdown.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/dropdown.dart:1304]: Yes, as long as focusNode is not accessed before _internalNode is created in initState.

Overall I like the fact that focusNode is non-nullable, I think it simplifies things.

**Review by justinmc — COMMENTED** [review]
Thanks for jumping in to fix this! I think I see a possible leak, see my comment below. Otherwise this looks good.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 2 above)
Comment (AhmedLSayed9) [reply packages/flutter/lib/src/material/dropdown.dart]: Good catch! I've handled that case.

I can't find a way to test it, since:
- `FocusNode` mixes in `ChangeNotifier` but its `hasListeners` getter is marked as @protected
- The `_handleFocusChanged` callback doesn't affect anything anyway when leaked

File: packages/flutter/lib/src/material/dropdown.dart [hunk 3]
```diff
@@ -1357,8 +1357,17 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
   @override
   void didUpdateWidget(DropdownButton<T> oldWidget) {
     super.didUpdateWidget(oldWidget);
-    if (widget.focusNode == null) {
-      _internalNode ??= _createFocusNode();
+    if (widget.focusNode != oldWidget.focusNode) {
+      oldWidget.focusNode?.removeListener(_handleFocusChanged);
+      if (_internalNode != null && widget.focusNode != null) {
+        _internalNode!.removeListener(_handleFocusChanged);
```
Comment (justinmc) [inline packages/flutter/lib/src/material/dropdown.dart:1363]: Also you should set _internalNode to null I think.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/dropdown.dart]: We have some automatic leak detection that might catch this. You can run it like:

```
flutter test --dart-define LEAK_TRACKING=true <path/to/test.dart>
```

So I think if you just write a test that covers this case it's good enough, even if you can't directly verify that a leak didn't happen. Assuming we don't already have a test that covers this, I would do something like:

 * Build a DropdownButtonFormField wrapped in a StatefulBuilder with some boolean to decide whether to pass a focusNode. Start off with no focusNode.
 * Maybe expect that it uses focusColor when focused or something.
 * Call change your boolean and call setState so it rebuilds and now has no focusNode.
 * Expect the focusColor thing again.

**Review by justinmc — COMMENTED** [review]
Two possible changes to make in my two comments, otherwise good. Thanks for the quick response!

File: packages/flutter/lib/src/material/dropdown.dart (hunk 2 above)
Comment (AhmedLSayed9) [reply packages/flutter/lib/src/material/dropdown.dart]: Running the test with `LEAK_TRACKING=true` revealed that a FocusNode is still leaking due to not being properly disposed. I found that we should therefore fully dispose `_internalNode` rather than just removing the listener.

Interestingly, running the test with or without disposing `_internalNode` doesn't trigger a leak warning. The warning only appears when we remove the listener without disposing the focus node.

Given that we're now disposing the internal focus node, we can write a more relevant test to cover that, by calling the dispose method again and verifying that it throws an error.

**Comment by AhmedLSayed9** [comment]
> Can you fix the analyzer failure here?

All good now.

File: packages/flutter/test/material/dropdown_test.dart [hunk 4]
```diff
@@ -2576,6 +2576,90 @@ void main() {
...
+      paints..path(style: PaintingStyle.fill, color: defaultBorderColor),
+    );
+
+    // Replace focusNode and request focus.
+    focusNode.dispose();
+    focusNode = FocusNode(debugLabel: 'DropdownButtonFormField');
+    focusNode.requestFocus();
+
+    await tester.pumpWidget(buildFormField());
+    await tester.pump(); // Wait for requestFocus to take effect.
```
Comment (justinmc) [inline packages/flutter/test/material/dropdown_test.dart:2611]: Thanks for including the comment here.

File: packages/flutter/test/material/dropdown_test.dart [hunk 5]
```diff
@@ -2576,6 +2576,90 @@ void main() {
...
+        Theme.of(tester.element(find.byType(InputDecorator))).colorScheme.surfaceContainerHighest;
+    expect(
+      findInputDecoratorBorderPainter(),
+      paints..path(style: PaintingStyle.fill, color: defaultBorderColor),
+    );
+
+    // Replace focusNode and request focus.
+    focusNode.dispose();
+    focusNode = FocusNode(debugLabel: 'DropdownButtonFormField');
+    focusNode.requestFocus();
```
Comment (justinmc) [inline packages/flutter/test/material/dropdown_test.dart:2608]: I'm confused by this, why do you create a new FocusNode and not use it anywhere? The widget created by buildFormField will not have a reference to this new FocusNode right?

**Review by justinmc — COMMENTED** [review]
Sorry for the delay, one question about the tests.

File: packages/flutter/test/material/dropdown_test.dart (hunk 5 above)
Comment (AhmedLSayed9) [reply packages/flutter/test/material/dropdown_test.dart:2608]: It doesn't create a new FocusNode variable, it replaces the value of the existing focusNode variable which is used by buildFormField. The focusNode declared at the start of the test is a mutable variable.

Comment (AhmedLSayed9) [reply packages/flutter/test/material/dropdown_test.dart:2608]: @justinmc
This is just a reminder, in case you've missed my reply :)

Comment (justinmc) [reply packages/flutter/test/material/dropdown_test.dart:2608]: Sorry, thanks for the reminder here. You're right that it will get picked up when buildFormField is called below, looks good :+1:

**Review by justinmc — APPROVED** [review]
LGTM :+1:. Thanks for following through on this PR! I will look for a secondary reviewer.

**Review by bleroux — APPROVED** [review]
LGTM! Thanks for your contribution :pray:

**Comment by jonahwilliams** [comment]
reason for revert: multiple test failures w/ dropdown buttons - https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_libraries/22946/overview

**Comment by AhmedLSayed9** [comment]
> reason for revert: multiple test failures w/ dropdown buttons - https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_libraries/22946/overview

@jonahwilliams Should I open another PR to address this, or is there something else you’d recommend I do to get this merged?

**Comment by bleroux** [comment]
@AhmedLSayed9
Yes, please file another PR to reland your fix, there was probably a change which landed between the time you finalised your PR and the moment it was merged.
See https://github.com/flutter/flutter/issues/170476 for some context.

With this new PR we will see if all CI checks pass.
