### PR TITLE
Characters Package

### LINKED ISSUE #32240: Add basic handling of grapheme clustering
Flutter is changing the way the cursor moves in text fields when the text contains grapheme clusters (e.g. composed emojis). The relevant tests are in `text_painter_test.dart`.

### LINKED ISSUE #54240: Incorrect character count in TextField for extended grapheme clusters
The character count is wrong when a complex emoji such as 👨‍👩‍👦 is used in a TextField.

```dart
TextField(
  maxLength: 10,
),
```

screenshot

This is due to Flutter counting [runes](https://master-api.flutter.dev/flutter/dart-core/Runes-class.html) instead of graphemes.  Read more about this problem in my solution proposal: https://docs.google.com/a/google.com/document/d/1OOFW0PEZf0orBl445YXJ3nfjyKOqZdmeQ6KU3glUh7s/edit?usp=sharing.

### LINKED ISSUE #55670: When EditText has emoji, the maximum length of editable.dart will be abnormal length and cursor abnormality
/***
*** my class example : maxlength = 15
***/

```
TextField(
                 controller: TextEditingController.fromValue(TextEditingValue(
                                  text: _txtController.text,
                                  selection: TextSelection.fromPosition(
                                      TextPosition(affinity: TextAffinity.downstream, offset:_txtController.text.length)))),
                 decoration: InputDecoration(
                           border: InputBorder.none,
                  ),
                 style: TextStyle(fontSize: 16),
                  inputFormatters: [
                                LengthLimitingTextInputFormatter(15),
                   ]
)
```

descrition: When the input box contains an emoticon, when 16 characters are input, the input box can still display the 16th character, and then the cursor moves to the 15th character position.

my hope：When the input box contains an emoticon, when 16 characters are input, the input box can still display 15 characters, and then the cursor moves to the 15th character position.

find：I find the source -（editable_text.dart） do not  deal with max length state. 
So I want to solve this bug only through the business layer to make logical judgments。

My Solution for suspension
1. add field to get maxLength number;
2. This is what I need for work;(this is my work need)

```
     final int selfMaxLength;
     final Function maxLengthCallBack;
     final TextEditingController myController;

    @override 
    void initState() {
    ……
    myController =  TextEditingController.fromValue(TextEditingValue(
                                  text: _txtController.text,
                                  selection: TextSelection.fromPosition(
                                      TextPosition(affinity: TextAffinity.downstream, offset:_txtController.text.length))));
    if (widget.controller.text.length == widget.selfMaxLength) {
       hasAlreadyMaxLength = true;
       lastMaxContent = widget.controller.text;
    } else {
      hasAlreadyMaxLength = false;
      lastMaxContent = "";
          }
    }
 
    @override
    Widget build(BuildContext context) {
          return Container(
                child: TextField(
                 controller: myController,
                 decoration: InputDecoration(
                           border: InputBorder.none,
                  ),
                 style: TextStyle(fontSize: 16),
                  inputFormatters: [
                                LengthLimitingTextInputFormatter(15),
                   ]，
                   onChanged: (String value) {
                    _actionMaxLengthState(value);
                  }
                 )
          )
    }

    void _resetSelection(String newText) {
     var sRunes = newText.runes;
     String result;
     for (int i = 0; i < sRunes.length; i++) {
         if (String.fromCharCodes(sRunes, 0, sRunes.length - i).length <= widget.selfMaxLength) {
         result = String.fromCharCodes(sRunes, 0, sRunes.length - i);
         break;
      }
    }
    TextSelection temp = myController.value.selection.copyWith(
      baseOffset: result.length,
      extentOffset: result.length,
    );
    TextRange fixRange = widget.controller.value.composing;
    if (widget.controller.value.composing.end > result.length) {
      fixRange = TextRange(start: fixRange.start, end: result.length);
    } 
    
    //composing is used iOS inputMethod
    myController.value = TextEditingValue(text: result, selection: temp, composing: fixRange);
    lastMaxContent = result;
    }

    void _initOldDataSelection(String newText) {
          TextSelection actualSelection = myController.value.selection;
          actualSelection = myController.value.selection.copyWith(
                  baseOffset: lastMaxContent.length,
                  extentOffset: lastMaxContent.length,
           );
    //ios: When TextRange is not -1, the next update will replace all the variable values ​​of start and end directly. When you are sure that the content is unchanged, please change them to -1
    TextRange fixRange = TextRange(start: -1, end: -1);
          myController.value = TextEditingValue(text: lastMaxContent, selection: actualSelection, composing: fixRange);
    }

    void _actionMaxLengthState(String newText) {
    if (newText.length >= widget.selfMaxLength) {
      if (maxLengthCallBack != null) maxLengthCallBack();
      if (hasAlreadyMaxLength) {
        _initOldDataSelection(newText);
      } else {
        hasAlreadyMaxLength = true;
        _resetSelection(newText);
      }
    } else {
      //For the controller's text setting, you must change the value or set the text directly, and the selection is the default value of -1.
      widget.controller.value = TextEditingValue(text: newText, selection: widget.controller.value.selection, composing: widget.controller.value.composing);
      hasAlreadyMaxLength = false;
      lastMaxContent = "";
      }
    }
```

Finally, I hope flutter Team can resovle this question.

### PR DESCRIPTION
**Pull request by justinmc**
## Description

Flutter currently has poor support for grapheme clusters like 👨‍👩‍👦, which it considers to be multiple characters even though it appears to the user as one.  This PR is a proposal for adding support via the [characters package](https://pub.dev/packages/characters).

Screen Shot 2020-03-26 at 2 26 01 PM

The [design doc](https://docs.google.com/document/d/1OOFW0PEZf0orBl445YXJ3nfjyKOqZdmeQ6KU3glUh7s/edit?usp=sharing) has more details.

### Changes

  - [x] Character count.
  - [x] Error state based on character count.
  - [x] Pasting excessive characters places the cursor correctly.

## Related Issues

Engine PR (independent):
https://github.com/flutter/engine/pull/17420

Closes https://github.com/flutter/flutter/issues/32240
Closes https://github.com/flutter/flutter/issues/55670
Closes https://github.com/flutter/flutter/issues/54240

## Tests

  * Character count for maxLength works with/without grapheme clusters and surrogate pairs.
  * Enforced character limit for maxLength works with/without grapheme clusters and surrogate pairs.
  * Error state for maxLength shows at the right length with/without grapheme clusters and surrogate pairs.

## Breaking Change

Currently I don't think this is a breaking change.  There may be broken visual diff tests in the rare case where they include a grapheme cluster.

### CODE REVIEW

**Comment by justinmc** [comment]
TODO: Handle arrow key navigation in the framework using characters: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/editable.dart#L556

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -544,6 +547,55 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
     }
   }
 
+  /// Returns the index of the first character after extent.
+  ///
+  /// Setting includeWhitespace to false will only return the index of non-space
+  /// characters.
+  @visibleForTesting
+  static int nextCharacter(int extent, String string, [bool includeWhitespace = true]) {
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:555]: Is there any performance concern with `nextCharacter` and `previousCharacter`?  They iterate the entire string in order to avoid bugs where the extent is in the middle of an extended grapheme cluster. If we can assume that won't happen, or we are ok with these methods not finding the end/beginning of the grapheme cluster when it does happen, then we can optimize by starting our search from `extent`.

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 2]
```diff
@@ -635,15 +635,13 @@ class TextPainter {
 
   // Get the Rect of the cursor (in logical pixels) based off the near edge
   // of the character upstream from the given string offset.
-  // TODO(garyq): Use actual extended grapheme cluster length instead of
-  // an increasing cluster length amount to achieve deterministic performance.
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/text_painter.dart:639]: It's not possible to improve performance using the characters package as expected.  It can find characters by iterating from the start or end of a string, but at some offset into a string, it doesn't know where the character boundaries are.  Performance is likely to be worse iterating from the start/end of a long string rather than using the existing logarithmic algorithm.

**Comment by justinmc** [comment]
I'm not sure if the failures are due to something special I'm missing because I added a new package, or if it's the typical versioning failure.  I'm going to squash all the commits and see if it goes away.

**Comment by justinmc** [comment]
I could use advice on the test failure if anyone has any ideas. `Stack frames parsed incorrectly` https://github.com/flutter/flutter/pull/53381/checks?check_run_id=755670351

**Comment by justinmc** [comment]
I'm going to split this into 2 PRs, so I'm putting this back into WIP.  The other PR will simply add the characters package to the repo, and I'll update this one once it's merged.

**Comment by justinmc** [comment]
https://github.com/flutter/flutter/pull/59267 was merged and I updated this PR, so we're ready for review again.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 3]
```diff
@@ -557,6 +542,55 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+    });
+    return string.length - remaining.toString().length;
+  }
+
+  /// Returns the index of the first character before extent.
+  ///
+  /// Setting includeWhitespace to false will only return the index of non-space
+  /// characters.
+  @visibleForTesting
+  static int previousCharacter(int extent, String string, [bool includeWhitespace = true]) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/editable.dart:574]: This method and the nextCharacter method should make meaning of their extent parameter and return value really clear, i.e. are they string indices or string.character indices. They should make how they handle edge cases clear as well.

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 4]
```diff
@@ -600,15 +600,15 @@ class TextPainter {
 
   // Complex glyphs can be represented by two or more UTF16 codepoints. This
   // checks if the value represents a UTF16 glyph by itself or is a 'surrogate'.
-  bool _isUtf16Surrogate(int value) {
+  static bool _isUtf16Surrogate(int value) {
     return value & 0xF800 == 0xD800;
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/painting/text_painter.dart:604]: I've opened a separate issue for this and assigned myself.  I'll look into it and merge a small PR separately if it is indeed wrong.  https://github.com/flutter/flutter/issues/59513

File: packages/flutter/lib/src/rendering/editable.dart [hunk 5]
```diff
@@ -557,6 +542,55 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
     }
   }
 
+  /// Returns the index of the first character after extent.
+  ///
+  /// Setting includeWhitespace to false will only return the index of non-space
+  /// characters.
+  @visibleForTesting
+  static int nextCharacter(int extent, String string, [bool includeWhitespace = true]) {
+    if (extent >= string.length) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart]: I've made this more straightforward in b3cdde2210c01abe721ddb4f339e5b2be01b27c3.

  1. I assert that the input must be between 0 and string.length, inclusive.
  1. Asking for the previous character from index 0 returns 0. Asking for the next character after string.length returns string.length.
  1. I clarified that the input and output of this method are all positions in the string (not character indices).
  1. I tested all missing edge cases, including cases that assert.

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/rendering/editable.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart]: I wrote a proof-of-concept and it seemed like something like this would work and would be potentially much faster.  I'll follow up after this is merged.

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (lrhn) [reply packages/flutter/lib/src/painting/text_painter.dart:604]: The test is sufficient. The check uses `& 0xF800` which maps every value in the range 0xD800 .. 0xDFFF to 0xD800.

Not sure if it would be more readable as `value & ~0x7FF == 0xD800` or `value >>11 == 0x1B`.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 6]
```diff
@@ -557,6 +542,55 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+    int count = 0;
+    final Characters remaining = string.characters.skipWhile((String currentString) {
+      if (count <= extent) {
+        count += currentString.length;
+        return true;
+      }
+      if (includeWhitespace) {
+        return false;
+      }
+      return _isWhitespace(currentString.characters.first.toString().codeUnitAt(0));
```
Comment (lrhn) [inline packages/flutter/lib/src/rendering/editable.dart:572]: That line is equivalent to:
```dart 
   return _isWhitespace(currentString.codeUnitAt(0));
```

Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart:572]: Ah thanks, good call!

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/painting/text_painter.dart:604]: Thanks for the clarification. I'll update the documentation on https://github.com/flutter/flutter/pull/53381#discussion_r441495677.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/lib/src/rendering/editable.dart:572]: This will be fixed when I reland this PR in https://github.com/flutter/flutter/pull/59778.
