### PR TITLE
Shortcircuit if Tooltip message and richMessage are empty

### LINKED ISSUE #182495: [flutter 3.41.x] NavigationDestination shows empty tooltip
### Steps to reproduce

Use `NavigationDestination` and pass an empty string for the `tooltip` parameter

### Expected results

[Documentation](https://github.com/flutter/flutter/blob/9fa7f81be038464d2aabef4752d2f50ea60ce561/packages/flutter/lib/src/material/navigation_bar.dart#L414) states:
>If [tooltip] is an empty string, no tooltip will be used.

In every version below Flutter 3.41, no tooltip would show up when hovering a NavigationDestination with an empty string as tooltip.

### Actual results

Since Flutter 3.41, a small "empty" tooltip shows up (see screenshot), which I don't think is intended.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(child: Text('Hello World!')),
        bottomNavigationBar: NavigationBar(
          destinations: [
            NavigationDestination(
              icon: Icon(Icons.bug_report),
              label: 'Bug',
              tooltip: '',
            ),
            NavigationDestination(
              icon: Icon(Icons.bug_report),
              label: 'Bug',
              tooltip: '',
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

<details open><summary>Logs</summary>

(Not relevant)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.41.1, on Microsoft Windows [Version 10.0.26100.7840], locale de-DE) [429ms]
    • Flutter version 3.41.1 on channel stable at C:\Users\...\fvm\versions\3.41.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 582a0e7c55 (5 days ago), 2026-02-12 17:12:32 -0800
    • Engine revision 3452d735bd
    • Dart version 3.11.0
    • DevTools version 2.54.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios,
      cli-animations, enable-native-assets, omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration

[√] Windows Version (Windows 11 or higher, 24H2, 2009) [983ms]

[!] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [403ms]
    • Android SDK at C:\Users\...\AppData\Local\Android\sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    X cmdline-tools component is missing.
      Try installing or updating Android Studio.
      Alternatively, download the tools from https://developer.android.com/studio#command-line-tools-only and make sure to set the
      ANDROID_HOME environment variable.
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.

[√] Chrome - develop for the web [175ms]
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.14.0 Preview 3.0) [174ms]
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.14.36015.10
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.26100.0

[√] Connected device (3 available) [217ms]
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.26100.7840]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 144.0.7559.133
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 145.0.3800.58

[√] Network resources [355ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by victorsanni**
Regressed when migrating to `RawTooltip`. 

The unit tests added in https://github.com/flutter/flutter/pull/87638 to prevent this from happening were faulty, I've updated them to reflect this feature.

Fixes [[flutter 3.41.x] NavigationDestination shows empty tooltip](https://github.com/flutter/flutter/issues/182495)

### CODE REVIEW

**Review by dkwingsmt — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/tooltip.dart [hunk 1]
```diff
@@ -403,6 +403,11 @@ class TooltipState extends State<Tooltip> with SingleTickerProviderStateMixin {
   late bool _visible;
   late TooltipThemeData _tooltipTheme;
 
+  /// The plain text message for this tooltip.
+  ///
+  /// This value will either come from [widget.message] or [widget.richMessage].
+  String get _tooltipMessage => widget.message ?? widget.richMessage!.toPlainText();
```
Comment (navaronbracke) [inline packages/flutter/lib/src/material/tooltip.dart:409]: The original code used the empty string if rich message was null?

**Review by navaronbracke — APPROVED** [review]
LGTM, with nit.

File: packages/flutter/lib/src/material/tooltip.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/material/tooltip.dart:409]: If richMessage is just a widget span, this may be shortcircuited as well. Is this the existing behavior before the change?

Comment (victorsanni) [reply packages/flutter/lib/src/material/tooltip.dart:409]: Yes, this is existing behavior before RawTooltip.
