### PR TITLE
[versions] update all versions

### LINKED ISSUE #59718: Flutter Web Hot Refresh Broken - :59527/dart_sdk.js:133084 Uncaught (in promise) TypeError: Cannot read property 'ensureFontsLoaded' of null
## Steps to Reproduce

`flutter upgrade` on master channel
run the default project
make a change and notice the page will entirely stall and you must manually refresh to see the change

I noticed this started happening after an upgrade 2-3 days ago.

```
:59527/dart_sdk.js:133084 Uncaught (in promise) TypeError: Cannot read property 'ensureFontsLoaded' of null
    at _initializePlatform (:59527/dart_sdk.js:133084)
    at _initializePlatform.next (<anonymous>)
    at :59527/dart_sdk.js:37106
    at _RootZone.runUnary (:59527/dart_sdk.js:36960)
    at _FutureListener.thenAwait.handleValue (:59527/dart_sdk.js:32047)
    at handleValueCallback (:59527/dart_sdk.js:32594)
    at Function._propagateToListeners (:59527/dart_sdk.js:32632)
    at _Future.new.[_completeWithValue] (:59527/dart_sdk.js:32475)
    at async._AsyncCallbackEntry.new.callback (:59527/dart_sdk.js:32497)
    at Object._microtaskLoop (:59527/dart_sdk.js:37221)
    at _startMicrotaskLoop (:59527/dart_sdk.js:37227)
    at :59527/dart_sdk.js:32849
```

```
[√] Flutter (Channel master, 1.20.0-1.0.pre.90, on Microsoft Windows [Version 10.0.17758.4], locale en-US)
    • Flutter version 1.20.0-1.0.pre.90 at C:\src\flutter
    • Framework revision 42e02d60d3 (5 hours ago), 2020-06-17 10:57:40 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\Miche\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\Miche\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.106

```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes https://github.com/flutter/flutter/issues/59718

Update all versions, specifically dwds which has a hot restart fix

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Review by gaaclarke — APPROVED** [review]

File: packages/flutter_tools/lib/src/commands/update_packages.dart [hunk 1]
```diff
@@ -30,6 +30,7 @@ const Map<String, String> _kManuallyPinnedDependencies = <String, String>{
   'vm_service_client': '0.2.6+2', // Final version before being marked deprecated.
   'video_player': '0.10.6', // 0.10.7 fails a gallery smoke test for toString.
   'flutter_template_images': '1.0.1', // Must always exactly match flutter_tools template.
+  'shelf': '0.7.5'
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/update_packages.dart:33]: do you remember why we pinned this?
(i'm trying to add comments to the file explaining all the pins)
