### PR TITLE
Fix: Active step fully colored in vertical mode

### LINKED ISSUE #169661: Stepper line on active step is not fully colored
### Steps to reproduce

Create a simple app with a Stepper component, you will notice that the line of the active step is not fully colored.

### Expected results

The expected result should be a fully colored line for the active step

### Actual results

Actually this is the current result

Image

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Stepper(
            currentStep: 0,
            controlsBuilder: (_, __) => const SizedBox.shrink(),
            connectorThickness: 3,
            steps: ["test1", "test2", "test3"]
                .map(
                  (s) => Step(
                    title: Align(
                      alignment: Alignment.centerLeft,
                      child: Text(
                        s,
                      ),
                    ),
                    content: Align(
                      alignment: Alignment.centerLeft,
                      child: Text(
                        "Content for $s",
                      ),
                    ),
                    isActive: s == "test1",
                  ),
                )
                .toList(),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.0, on macOS 15.5 24F74 darwin-arm64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.100.2)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

### PR DESCRIPTION
**Pull request by rkishan516**
Fix: Active step fully colored in vertical mode
fixes: #169661 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/material/stepper_test.dart [hunk 1]
```diff
@@ -1636,6 +1636,47 @@ void main() {
...
+          widget.child is SizedBox &&
+          (widget.child! as SizedBox).width == 3.0,
+    );
+
+    expect(connectorLines, findsWidgets);
+
+    final List<ColoredBox> lineWidgets = tester.widgetList<ColoredBox>(connectorLines).toList();
+    final List<Color> colors = lineWidgets.map((ColoredBox box) => box.color).toList();
+    // Both top and bottom box should be colored.
+    expect(colors.where((Color c) => c == activeColor).length, equals(2));
```
Comment (dkwingsmt) [inline packages/flutter/test/material/stepper_test.dart:1682]: Can you also check exactly which two members are active?

**Review by dkwingsmt — APPROVED** [review]
LGTM except a nit. Thank you!

File: packages/flutter/test/material/stepper_test.dart (hunk 1 above)
Comment (rkishan516) [reply packages/flutter/test/material/stepper_test.dart:1682]: Thanks for review @dkwingsmt, I have pushed the change.

**Review by QuncCccccc — APPROVED** [review]
NICE fix! LGTM! Thank you for your contribution:)
