### PR TITLE
fix a regex in the ios logs command

### LINKED ISSUE #869: Developer should see streaming log output from Flutter app running on iOS simulator
While developing a Flutter app running on an iOS simulator, the developer should see any logs from Flutter stream out from the simulator onto their desktop console or Flutter IDE plugin.

### PR DESCRIPTION
**Pull request by devoncarew**
- fix a regression with streaming sub-process output (introduced w/ the print / status refactoring). We were introducing extra blank lines every few lines of child process output
- slightly better text for the `start` command
- update a regex in the ios simulator `logs` command

fix #869

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
Presumably this fixes https://github.com/flutter/flutter/issues/869 ?

File: packages/flutter_tools/lib/src/base/process.dart [hunk 1]
```diff
@@ -27,6 +27,7 @@ Future<int> runCommandAndStreamOutput(List<String> cmd, {
       // TODO(ianh): This doesn't handle IO buffering (where the data might be split half-way through a line)
       dataLines = dataLines.where((String s) => filter.hasMatch(s)).toList();
     }
+    dataLines = dataLines.where((String s) => s.isNotEmpty).toList();
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/base/process.dart]: this is still going to be buggy. See the comment higher up. We should be properly buffering the text using a stream and a LineSplitter or something.

File: packages/flutter_tools/lib/src/commands/start.dart [hunk 2]
```diff
@@ -165,3 +165,10 @@ Future<int> startApp(
 
   return startedSomething ? 0 : 2;
 }
+
+String _getRelativePath(String fullPath) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/start.dart]: The path package has something to do this IIRC.

File: packages/flutter_tools/lib/src/ios/device_ios.dart [hunk 3]
```diff
@@ -518,12 +518,21 @@ class IOSSimulator extends Device {
     String logFilePath = path.join(
       homeDirectory, 'Library', 'Logs', 'CoreSimulator', simulatorDeviceID, 'system.log'
     );
+
     if (clear)
       runSync(['rm', logFilePath]);
+
+    // TODO: The log message prefix could be shortened or removed.
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/ios/device_ios.dart]: include username in TODOs

**Comment by Hixie** [comment]
lgtm

File: packages/flutter_tools/lib/src/ios/device_ios.dart (hunk 3 above)
Comment (eseidelGoogle) [inline packages/flutter_tools/lib/src/ios/device_ios.dart]: I learned *why* Google does this the other day.  It's not necessarily your username, but rather the username of the person who has the most context on the issue. :)  The person to ask about the TODO.

Comment (Hixie) [inline packages/flutter_tools/lib/src/ios/device_ios.dart]: Yeah. Though make sure they know they're being mentioned. ;-)

Comment (devoncarew) [inline packages/flutter_tools/lib/src/ios/device_ios.dart]: I don't always remember to write the username - will add it here.

File: packages/flutter_tools/lib/src/commands/start.dart (hunk 2 above)
Comment (devoncarew) [inline packages/flutter_tools/lib/src/commands/start.dart]: Hmm, I wasn't aware. I looked at it - it'll always try and relativize the name. What I want here is a good, short display name. So, relative if it's contained in the cwd, and absolute otherwise. I renamed this to `_getDisplayPath()` to clarify -

File: packages/flutter_tools/lib/src/ios/device_ios.dart (hunk 3 above)
Comment (devoncarew) [inline packages/flutter_tools/lib/src/ios/device_ios.dart]: added

File: packages/flutter_tools/lib/src/base/process.dart (hunk 1 above)
Comment (devoncarew) [inline packages/flutter_tools/lib/src/base/process.dart]: Yup, good point. I changed to using a `LineSplitter`, filters, and listeners. Shorter and fewer bugs :)

**Comment by Hixie** [comment]
new code looks great
