### PR TITLE
Adjust default CupertinoCheckbox size on desktop

### LINKED ISSUE #165140: CupertinoCheckbox padding on MacOS is excessive, is applying iOS standards
### Steps to reproduce

Build and run on MacOS desktop any CupertinoApp with a widget with stacked checkboxes, such as:

```
Column(children: [
  CupertinoCheckbox(value: true, onChanged: (){}),
  CupertinoCheckbox(value: true, onChanged: (){}),
  CupertinoCheckbox(value: true, onChanged: (){}),
])
```

Observe that the three stacked checkboxes have excessive vertical spacing, and no means of reducing it (no parameters dev can pass to constructor will reduce vertical spacing). 

This is caused by:

```
https://github.com/flutter/flutter/tree/main/packages/flutter/lib/src/cupertino/checkbox.dart

Line 433: 
  size: const Size.square(kMinInteractiveDimensionCupertino),

Where constants.dart is:
  const double kMinInteractiveDimensionCupertino = 44.0;
```

That causes minimum size of ```buildToggleable()``` result to be the **minimum tap-target size for iOS**, which is the wrong standard to be applying if ```Platform.isMacOS```.

Note that this default behavior of CupertinoCheckbox is not even internally consistent with behavior of ```CupertinoRadio``` where minimum is set as: 

```
const Size _size = Size(18.0, 18.0);
```

### Expected results

Minimum spacing for checkboxes set consistent with a desktop-OS platform with precision pointing device.

### Actual results

Minimum spacing is set for "stab at it with a fat finger" iOS standards, and cannot be reduced. 

### Suggested Fix

I've forked the checkbox.dart file and find that using the CupertinoRadio's default value of 18 instead produces the best results, letting the developer optionally add additional padding around the Widget if needed: 

```
const minCheckboxSquareSizeMacOS = 18.0;
```

Making the line in checkbox build(): 
```
  size: const Size.square( Platform.isMacOS ? minCheckboxSquareSizeMacOS : kMinInteractiveDimensionCupertino ),
```

### PR DESCRIPTION
**Pull request by victorsanni**
Fixes [CupertinoCheckbox padding on MacOS is excessive, is applying iOS standards](https://github.com/flutter/flutter/issues/165140)

### CODE REVIEW

**Comment by victorsanni** [comment]
Scuba changes are pretty bad. Maybe we can add it as an optional parameter and have it stick to its current default.

**Comment by victorsanni** [comment]
This is tricky because if we expose the tapTargetSize, there is weird behavior if they supply a size <18px:

Screenshot 2025-09-03 at 11 30 10 AM

The solutions I think could work here are:

* Hard break everyone to move to 18px since checkboxes aren't recommended on mobile anyways
* add the 18px checkbox as a new constructor (`CupertinoCheckbox.small`/`CupertinoCheckbox.large` or `CupertinoCheckbox.mobile`/`CupertinoCheckbox.desktop`)
* add the `tapTargetSize` property and assert a minimum size of 18x18 px

Which of these should we proceed with @MitchellGoodwin?

**Comment by MitchellGoodwin** [comment]
My vote is for
> add the tapTargetSize property and assert a minimum size of 18x18 px

Besides visual appearance changes, tap targets are in the realm of accessibility so I'm a little nervous to make breaking changes when it comes to that. Also, rather than 18x18, it might make sense to make the minimum 14x14. 18 is the width of the radio, 14 is the width of the checkbox. I don't know if we need to enforce having a tap target bigger than the checkbox.

Right now the width of the checkbox is set by a static value. I think the min TapTargetSize and the width should point to the same value.

I think we can merge this in and then consider a breaking change after. I think we might want to consider having tapTargetSize default to it's current value on mobile, and to a lower default on all other platforms. That makes the most sense to me, but would be breaking on desktop and web.

**Comment by victorsanni** [comment]
> I think we might want to consider having tapTargetSize default to it's current value on mobile, and to a lower default on all other platforms.

That's an option I didn't consider. And might help with the google tests as well. Plus, it means we don't have to increase the API surface.

**Comment by MitchellGoodwin** [comment]
Another thing to consider is that it's common to adjust the size of the checkbox with Transform.scale, so whatever we do we need to make sure it works as expected with that.

File: packages/flutter/lib/src/cupertino/checkbox.dart [hunk 1]
```diff
@@ -422,6 +425,15 @@ class _CupertinoCheckboxState extends State<CupertinoCheckbox>
                   : SystemMouseCursors.basic);
         });
 
+    final Size effectiveSize = switch (defaultTargetPlatform) {
+      TargetPlatform.iOS ||
+      TargetPlatform.android ||
+      TargetPlatform.fuchsia => const Size.square(kMinInteractiveDimensionCupertino),
+      TargetPlatform.macOS ||
+      TargetPlatform.linux ||
+      TargetPlatform.windows => const Size.square(CupertinoCheckbox.width),
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/cupertino/checkbox.dart]: `CupertinoCheckbox.width` is 14 while the size tested in the original issue is 18, which looks pretty good. Will 14 be too small?

**Review by dkwingsmt — COMMENTED** [review]
I think a better way is to expose a `size` property that applies the platform-dependent default size in this PR. What do you think?

**Comment by victorsanni** [comment]
> I think a better way is to expose a `size` property that applies the platform-dependent default size in this PR. What do you think?

It gets weird because the size here doesn't actually affect the size of the checkbox, just the area that, when tapped, toggles the checkbox.

**Comment by dkwingsmt** [comment]
I see that Material has a `MaterialTapTargetSize` that does a similar job. It's actually an enum, which does exactly what your current `switch` statement does. That being said, I think the enum is a bad choice (it was added in 2018 anyway) but we can call this new property `tapTargetSize` and make it a `Size`.

File: packages/flutter/lib/src/cupertino/checkbox.dart (hunk 1 above)
Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/checkbox.dart]: No, I think the issue has 18px because of the default macOS padding. But it's probably best to leave any additional padding customizations to the user.

**Review by dkwingsmt — APPROVED** [review]
LGTM, thank you

File: packages/flutter/lib/src/cupertino/checkbox.dart [hunk 2]
```diff
@@ -66,6 +66,9 @@ const List<double> _kDisabledDarkGradientOpacities = <double>[0.08, 0.14];
 /// ([CupertinoSwitch] in Flutter) instead, or to find a creative custom
 /// solution.
 ///
+/// The checkbox has a default size of 14-by-14 pixels on desktop devices and
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/cupertino/checkbox.dart]: Nit: I think this should clarify that the size difference is only the tap target area and layout padding. The actual visual checkbox itself is 14-by-14 on all platforms with this change.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM with one nit on the documentation
