### PR TITLE
[Gen-l10n] Infer placeholder types on both templates and localizations

### LINKED ISSUE #163627: Flutter Internationalization Error related to placeholder types
When starting the app in debug mode I'm now getting this error message:

```
Error: The placeholder, count, has its "type" resource attribute set to the "null" type in locale "en", but it is "num" in the template placeholder. For compatibility with template placeholder, change the "type" attribute to "num".
```

Unfortunately I have no idea how I am supposed to address this.

Do I need to go through the arb files and check every single entry if it has the exact same shape across all languages?
Because I don't have any types or anything set anywhere explicitly, I just have a bunch of arbs.

I think this problem started with the 3.29 release.

I have already tried removing `generate: true` from `pubspec.yaml` and adding `synthetic-package: false` to `l10n.yaml`.

### PR DESCRIPTION
**Pull request by benthillerkus**
This fixes https://github.com/flutter/flutter/issues/163627 by trying to the infer the type of a placeholder on both the template messages and their localised versions.

This way, if the placeholder is being referenced in the localisation, but the type is omitted in both the template and the localisation, the check for if the template and the localisation have the same type will not fail anymore.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by bkonyi** [comment]
Thanks for the PR @benthillerkus! My apologies for the delay, I was out for a few weeks. I think this looks good to me, but I need to brush up on my l10n details before I feel confident approving. I'll get back to you today or tomorrow.

File: packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart [hunk 1]
```diff
@@ -245,6 +245,7 @@ class Placeholder {
   final bool? isCustomDateFormat;
   // The following will be initialized after all messages are parsed in the Message constructor.
   String? type;
+
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:248]: Nit: this whitespace can be removed.

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart [hunk 2]
```diff
@@ -1689,6 +1689,33 @@ import 'output-localization-file_en.dart' deferred as output-localization-file_e
           expect(content, contains("String get helloWorld => 'Hello {name}'"));
         },
       );
+
+      testWithoutContext('translations can copy the placeholder definitions for plurals', () {
```
Comment (bkonyi) [inline packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1693]: How does this test behave without your above patch? Do we expect for an exception to be thrown? It might be worth leaving a comment what the failure would look like with a reference to https://github.com/flutter/flutter/issues/163627 to make it clear that this is a regression test.

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart [hunk 3]
```diff
@@ -2155,7 +2182,7 @@ import 'output-localization-file_en.dart' deferred as output-localization-file_e
         "description": "The first day of spring",
         "placeholders": {
           "springStartDate": {
-            "format": "MMMMd"
+            "format": "MMMd"
```
Comment (bkonyi) [inline packages/flutter_tools/test/general.shard/generate_localizations_test.dart:2185]: Is there any particular reason this was changed? If not, we should probably change it back.

**Review by bkonyi — COMMENTED** [review]
Looks good to me overall! Just a few comments to address and then I'll approve.

Thanks for being patient!

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart (hunk 3 above)
Comment (benthillerkus) [reply packages/flutter_tools/test/general.shard/generate_localizations_test.dart]: No, I thought I was fixing a typo, because I thought this was defining the input shape and not how the placeholder will be rendered into the string

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart (hunk 2 above)
Comment (benthillerkus) [reply packages/flutter_tools/test/general.shard/generate_localizations_test.dart]: Like so?

Comment (bkonyi) [reply packages/flutter_tools/test/general.shard/generate_localizations_test.dart]: Perfect! Thanks!

**Review by bkonyi — APPROVED** [review]
LGTM! Thanks for the contribution!

@jyameo, can you rubber stamp this as well? 😄

**Comment by bkonyi** [comment]
@benthillerkus I think you need to run `dart format` on `[packages/flutter_tools/test/general.shard/generate_localizations_test.dart](https://github.com/flutter/flutter/pull/163690/files/c3e909168900643a5869316c11bd0378f3c3ce4a#diff-fbe84336fde1c1d4c9e791531332cdc1dcfbb1dbcf8aef7b9e353812dbccc495)` to get the analyzer check passing.

**Review by jyameo — APPROVED** [review]
LGTM!
