### PR TITLE
[web] Enable material text field tests on web

### LINKED ISSUE #79070: [web] Unskip cupertino & material text field tests
These are the test files:

* https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/text_field_test.dart
* https://github.com/flutter/flutter/blob/master/packages/flutter/test/cupertino/text_field_test.dart

Because these tests were disabled, a [regression](https://github.com/flutter/flutter/issues/79012) was allowed to happen, even though there was a [test](https://github.com/flutter/flutter/blob/f712fecde2e3105b6a2f604c86da86175444195d/packages/flutter/test/material/text_field_test.dart#L8920-L8953) covering it.

### LINKED ISSUE #79415: [web] Few dragging tests are failing in test/material/text_field_test.dart

### PR DESCRIPTION
**Pull request by mdebbar**
Several fixes that allow us to enable material text field tests on web:

1. In test mode, use target platform "android" instead of trying to detect the real platform.
2. Let mobile web display the last obscured character (just like native mobile does).
3. Properly setup (and dispose of) the mock handler.
4. Fix test that relies on default `MaxLengthEnforcement` (web has a different default from android).
5. Re-enable several unnecessarily skipped tests on web.
6. Skip or adjust the expectations of tests that use key events or the toolbar (web doesn't use either of them).
7. Skip tests for things that aren't implemented on web yet or implemented incorrectly (with links to the corresponding issues).

In addition to the above, there are a few fixes in the engine that this PR depends on: https://github.com/flutter/engine/pull/25367

Fixes https://github.com/flutter/flutter/issues/79415
Partially fixes https://github.com/flutter/flutter/issues/79070

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 8 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/79665

File: packages/flutter/lib/src/foundation/_platform_web.dart [hunk 1]
```diff
@@ -3,16 +3,32 @@
...
+  return platform.debugDefaultTargetPlatformOverride ??
+      _testPlatform ??
+      _browserPlatform;
 }
 
+final platform.TargetPlatform? _testPlatform = () {
+  platform.TargetPlatform? result;
+  assert(() {
+    // ignore: undefined_prefixed_name
+    if (ui.debugEmulateFlutterTesterEnvironment as bool) {
```
Comment (yjbanov) [inline packages/flutter/lib/src/foundation/_platform_web.dart:24]: Why is `as` necessary?

Would be good to leave a comment above the `// ignore` explaining what this is and why it's OK to ignore. The mobile/desktop part of the team may not know what this is about.

File: packages/flutter/test/material/text_field_test.dart [hunk 2]
```diff
@@ -1338,14 +1350,16 @@ void main() {
     );
     // Read only text field cannot open keyboard.
     await tester.showKeyboard(find.byType(TextField));
-    expect(tester.testTextInput.hasAnyClients, false);
+    // On web, we always create a client connection to the engine.
+    expect(tester.testTextInput.hasAnyClients, isBrowser ? isTrue : isFalse);
```
Comment (yjbanov) [inline packages/flutter/test/material/text_field_test.dart:1354]: I think we should find a way to avoid this distinction. We do this on the web to get the correct context menu, correct? If so, perhaps we can treat "having a client" separately from "being in edit state". The latter is what this test seems to care about. If this makes sense to you, could you please file an issue and leave a TODO with the link?

File: packages/flutter/test/material/text_field_test.dart [hunk 3]
```diff
@@ -1929,7 +1946,8 @@ void main() {
     await tester.tap(find.text('Paste'));
     await tester.pump();
     expect(controller.text, 'abc d${testValue}ef ghi');
-  });
+    // On web, we don't let Flutter show the toolbar.
+  }, skip: isBrowser);
```
Comment (yjbanov) [inline packages/flutter/test/material/text_field_test.dart:1950]: Consider creating a top-level variable `final bool isContextMenuProvidedByPlatform = isBrowser;` and leave a comment there about the difference between web and non-web. Then you can reuse that variable many times and not duplicate the comment.

File: packages/flutter/test/material/text_field_test.dart [hunk 4]
```diff
@@ -4638,7 +4672,9 @@ void main() {
       await tester.sendKeyDownEvent(LogicalKeyboardKey.arrowLeft);
       expect(controller.selection.extentOffset - controller.selection.baseOffset, -1);
     });
-  });
+
+    // On web, keyboard events in text fields are handled by the browser.
```
Comment (yjbanov) [inline packages/flutter/test/material/text_field_test.dart:4676]: I'd use the same top-level variable trick here too.

File: packages/flutter/test/material/text_field_test.dart [hunk 5]
```diff
@@ -6052,7 +6108,10 @@ void main() {
     );
 
     expect(topLeft.dx, equals(160.0));
-  });
+
+    // RTL support still has issues on the web.
```
Comment (yjbanov) [inline packages/flutter/test/material/text_field_test.dart:6112]: TODO?

File: packages/flutter/test/material/text_field_test.dart [hunk 6]
```diff
@@ -9367,7 +9472,10 @@ void main() {
     inputWidth = editable.size.width;
     expect(inputWidth, wideWidth);
     expect(cursorRight, inputWidth - kCaretGap);
-  });
+
+    // RTL support still has issues on the web.
```
Comment (yjbanov) [inline packages/flutter/test/material/text_field_test.dart:9476]: TODO?

**Review by yjbanov — APPROVED** [review]
lgtm

File: packages/flutter/lib/src/foundation/_platform_web.dart (hunk 1 above)
Comment (mdebbar) [reply packages/flutter/lib/src/foundation/_platform_web.dart:24]: @yjbanov the analyzer thinks `ui.debugEmulateFlutterTesterEnvironment` is `dynamic` so it complains that the condition has to be a boolean.

File: packages/flutter/test/material/text_field_test.dart (hunk 2 above)
Comment (mdebbar) [reply packages/flutter/test/material/text_field_test.dart:1354]: This check is making sure that the framework doesn't open a connection, by mistake, for a read-only text field. It's a valid check for native platforms. But on web, we always need the real input element to perform all the text selection stuff. Few things:

1. Correct context menu (with real copy and select all options).
2. Using the keyboard to manipulate the selection.
3. `cmd/ctrl + c` to copy.

**Comment by skia-gold** [comment]
Gold has detected about 8 untriaged digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/79665

**Comment by skia-gold** [comment]
Gold has detected about 8 untriaged digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/79665

**Comment by skia-gold** [comment]
Gold has detected about 8 untriaged digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/79665
