### PR TITLE
Fix SelectionArea handles overlapping context menu on Android

### LINKED ISSUE #168765: Selection Handles Overlap Context Menu in SelectionArea
### Steps to reproduce

Do the following (see code and video):

 -- Wrap a **`Text`** widget in a **`SelectionArea`** widget
 -- Long press on a word: the word will be selected and the context menu will open
 -- Click on the 3-dot button to see the other context menu options: the selection handle/bubbles will be over the context menu

Some observations:

 -- The problem doesn't happen with the **`SelectableText`** widget, it only happens with **`SelectionArea`**
 -- The problem disappears if the selection handle is moved after the long press (see video)

Related issue: [#59229](https://github.com/flutter/flutter/issues/59229)

### Expected results

(see video)

### Actual results

(see video)

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() { runApp( const MyAppContextMenu() );  }

class MyAppContextMenu extends StatelessWidget {
  const MyAppContextMenu( {super.key} );

  @override
  Widget build(final BuildContext context) {
     return MaterialApp( home:
       Scaffold(
         appBar: AppBar( title: Text( 'Bug: $runtimeType' ), ),
         body:   const ContextMenuExample( )
     ) );
} }

class ContextMenuExample extends StatelessWidget {
  const ContextMenuExample( {super.key} );

  @override
  Widget build(final BuildContext context) {
  return Column( children: [

      const Text( 'SelectionArea\n(problem)', style: TextStyle( fontSize: 20 ), textAlign: TextAlign.center ),
      SelectionArea( child: const Text('Flutter is an open-source UI software development kit created by Google. It can be used to develop cross platform applications from a single codebase for the web,[4] Fuchsia, Android, iOS, Linux, macOS, and Windows.[5] First described in 2015,[6][7] Flutter was released in May 2017. Flutter is used internally by Google in apps such as Google Pay[8][9] and Google Earth[10][11] as well as other software developers including ByteDance[12][13] and Alibaba....'),
          contextMenuBuilder: ( final BuildContext context, final SelectableRegionState selectableRegionState ) {
               return contextMenuBuilderArea( ctx: context, selectableRegionState: selectableRegionState );
          },
      ),

      const Text( '\nSelectableText\n(no problem here)', style: TextStyle( fontSize: 20 ), textAlign: TextAlign.center ),
      SelectableText( 'Flutter is an open-source UI software development kit created by Google. It can be used to develop cross platform applications from a single codebase for the web,[4] Fuchsia, Android, iOS, Linux, macOS, and Windows.[5] First described in 2015,[6][7] Flutter was released in May 2017. Flutter is used internally by Google in apps such as Google Pay[8][9] and Google Earth[10][11] as well as other software developers including ByteDance[12][13] and Alibaba....',
          contextMenuBuilder: ( final BuildContext context, final EditableTextState editableTextState ) {
               return contextMenuBuilderText( ctx: context, editableTextState: editableTextState );
          },
      ),

  ] );
} }

AdaptiveTextSelectionToolbar contextMenuBuilderArea( {
          required final BuildContext ctx,
          required final SelectableRegionState selectableRegionState,
} ){
  final buttonItems = selectableRegionState.contextMenuButtonItems;
  final buttons     = AdaptiveTextSelectionToolbar.getAdaptiveButtons( ctx, buttonItems ).toList( );
  return AdaptiveTextSelectionToolbar(
    anchors: selectableRegionState.contextMenuAnchors,
    children: [
    // ADDING MANY BUTTONS TO MIMIC REAL DEVICES
       ... buttons,
       ... buttons,
       ... buttons,
    ]
  );
}

AdaptiveTextSelectionToolbar contextMenuBuilderText( {
          required final BuildContext ctx,
          required final EditableTextState editableTextState,
} ){
  final buttonItems = editableTextState.contextMenuButtonItems;
  final buttons     = AdaptiveTextSelectionToolbar.getAdaptiveButtons( ctx, buttonItems ).toList( );
  return AdaptiveTextSelectionToolbar(
    anchors: editableTextState.contextMenuAnchors,
    children: [ ... buttons, ... buttons, ... buttons, ]
  );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

https://github.com/user-attachments/assets/8bc9ed67-dfb4-45d4-8604-7c2db9c8e793

</details>

### Logs

<details open><summary>Logs</summary>

```console

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor
[✓] Flutter (Channel stable, 3.29.3, on openSUSE Tumbleweed 6.13.0-1-default, locale en_US.UTF-8)
    • Dart version 3.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
    • Platform android-35, build-tools 35.0.1
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] Connected device (2 available) [120ms]
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 15 (API 35) (emulator)
```

</details>

### PR DESCRIPTION
**Pull request by JhonaCodes**
This PR fixes an Android `SelectionArea` layering issue where selection handles can paint above the expanded context
  menu (overflow actions), causing visual overlap and making menu actions harder to read/tap.

  The change updates the overlay/show ordering so the context menu remains visually above selection handles when both are
  visible.

  **Before**

  https://github.com/user-attachments/assets/e91edd3d-5926-4ad2-94e8-8c67985dc401

  **After**

  https://github.com/user-attachments/assets/bd2b5c3b-bd2f-4022-9f8f-9575a8066fd9

  Fixes https://github.com/flutter/flutter/issues/168765

  No changes were made in the [flutter/tests] repo.

  Test-exempt: small overlay ordering change, manually validated with the issue repro.

  ## Pre-launch Checklist

  - [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
  - [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
  - [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
  - [x] I signed the [CLA].
  - [x] I listed at least one issue that this PR fixes in the description above.
  - [ ] I updated/added relevant documentation (doc comments with `///`).
  - [x] I added new tests to check the change I am making, or this PR is [test-exempt].
  - [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
  - [x] All existing and new tests are passing.

  If you need help, consider asking for advice on the #hackers-new channel on [Discord].

  **Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://
  developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should
  not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code
  accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's
  review for guidance on which automated comments should be addressed.

  
  [Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
  [Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
  [test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
  [Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
  [Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-
  guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
  [CLA]: https://cla.developers.google.com/
  [flutter/tests]: https://github.com/flutter/tests
  [breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-
  breaking-changes
  [Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
  [Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 1]
```diff
@@ -1021,10 +1021,11 @@ class SelectableRegionState extends State<SelectableRegion>
     _finalizeSelection();
     _updateSelectedContentIfNeeded();
     _finalizeSelectableRegionStatus();
-    _showToolbar();
+    
     if (defaultTargetPlatform == TargetPlatform.android) {
       _showHandles();
     }
+    _showToolbar();
```
[the remark this answers is not in the document]
Comment (JhonaCodes) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1028]: Added a regression test in packages/flutter/test/widgets/selectable_region_test.dart: 
`context menu receives taps over selection handle on Android after long press`  to cover the overlay layering behavior.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 2]
```diff
@@ -1021,10 +1021,10 @@ class SelectableRegionState extends State<SelectableRegion>
     _finalizeSelection();
     _updateSelectedContentIfNeeded();
     _finalizeSelectableRegionStatus();
-    _showToolbar();
     if (defaultTargetPlatform == TargetPlatform.android) {
       _showHandles();
     }
+    _showToolbar();
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1028]: Another place where this may be an issue is `selectAll`.

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 3]
```diff
@@ -2949,6 +2949,57 @@ void main() {
       skip: kIsWeb, // [intended] Web uses its native context menu.
     );
 
+    testWidgets(
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart]: This test should live in `selection_area_test.dart`, ideally it could live in `selectable_region_test.dart` but we do not provide mock selection handles for testing yet.

**Review by Renzo-Olivares — COMMENTED** [review]
Hi @JhonaCodes, thank you for the contribution! Overall the change looks good I just left a few small comments.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 2 above)
Comment (JhonaCodes) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1028]: Done! Applied the same fix to `selectAll` by reordering  `_showHandles()`  before `_showToolbar()`.

File: packages/flutter/test/widgets/selectable_region_test.dart (hunk 3 above)
Comment (JhonaCodes) [reply packages/flutter/test/widgets/selectable_region_test.dart]: Done here too! Moved the test to `selection_area_test.dart` and adapted it to use `SelectionArea` instead of `SelectableRegion` directly.

File: packages/flutter/test/material/selection_area_test.dart [hunk 4]
```diff
@@ -637,4 +637,54 @@ void main() {
     );
     expect(tester.getSize(find.byType(SelectionArea)), Size.zero);
   });
+
+  testWidgets(
+    'context menu receives taps over selection handle on Android after long press',
+    (WidgetTester tester) async {
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/selection_area_test.dart]: I had one last thought about this test. Maybe we can move this test to selectable_region_test.dart.

It would need to:

1. Use `TestWidgetsApp` instead of `MaterialApp`.
2. Use `SelectableRegion` instead of `SelectionArea`.
3. Confirm the overlay order of selection handles and context menus inserted by selectable region by verifying against the build order rather than creating a very large context menu. You can look to this test https://github.com/flutter/flutter/blob/c4774005e97c4b5e1da79becc7e92a63b6910ac4/packages/flutter/test/widgets/overlay_test.dart#L215 for an example. You can track the builder order through `contextMenuBuilder` and passing a custom `selectionControls` to `SelectableRegion`.

**Review by Renzo-Olivares — COMMENTED** [review]
@JhonaCodes Thank you for the changes! I had one last thought about the test but other than that it looks good to me.

File: packages/flutter/test/material/selection_area_test.dart (hunk 4 above)
Comment (JhonaCodes) [reply packages/flutter/test/material/selection_area_test.dart]: Thanks for the suggestion, I find this approach more elegant and granular. Verifying the build order rather than simulating the interaction is something I hadn't considered. Applied.

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 5]
```diff
@@ -6840,3 +6881,31 @@ class RenderSelectAll extends RenderProxyBox with Selectable, SelectionRegistran
     this.endHandle = endHandle;
   }
 }
+
+/// A [TextSelectionControls] with [TextSelectionHandleControls] mixin that
+/// tracks when handles are built, used to verify overlay insertion order.
+class _OrderTrackingSelectionControls extends TextSelectionControls
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart]: super nit: This could be made a little more general as a `_TextSelectionControlsSpy` that exposes a `onBuildHandle` callback. Then in the test we can provide a callback that adds a string to our `buildOrder` list inside the test. Then we don't have to pass the list to the `TextSelectionHandleControls` and is more reusable for future tests.

**Review by Renzo-Olivares — COMMENTED** [review]
Had one more comment about the test @JhonaCodes! Thank you for the fast changes!

**Review by Renzo-Olivares — DISMISSED** [review]
LGTM, thank you for the contribution @JhonaCodes!

**Review by loic-sharma — DISMISSED** [review]
Thanks for the wonderful contribution!

**Comment by loic-sharma** [comment]
It looks like the analyzer check failed:

> [2026-04-17 16:59:41.664699] [STDOUT] stdout:    info • Omit the type annotation on a local variable when the type is obvious. Try removing the type annotation • packages/flutter/test/widgets/selectable_region_test.dart:6739:13 • omit_obvious_local_variable_types

**Comment by loic-sharma** [comment]
@JhonaCodes It looks like you'll need to run `dart format packages/flutter/`.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 6]
```diff
@@ -1022,10 +1022,10 @@ class SelectableRegionState extends State<SelectableRegion>
...
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1028]: can this be solve by providing above https://api.flutter.dev/flutter/widgets/OverlayState/insert.html?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1028]: Looking at the code, the anchor must be insert first, so the order still matter, but at least it will throw if someone accidentally revert this change

Comment (JhonaCodes) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1028]: Thanks @chunhtai

Just to make sure I'm applying what you're suggesting:  the actual `overlay.insert` for the toolbar is in `SelectionOverlay.showToolbar()` `(text_selection.dart:~1639)`, not here in `selectable_region.dart`. 

My read of your suggestion is to change `).insert(_toolbar!);`  to  `).insert(_toolbar!, above: _handles?.end);` so that when handles are present the assertion in `_debugVerifyInsertPosition` throws if the handle-before-toolbar order is ever reversed,  and when _handles is null, (valid on some platforms / EditableText paths where handles aren't shown) it falls back to default top insertion. 

Does that match what you had in mind, or did you want it narrower (e.g. only from the Android long-press path)?.

Thanks.

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1028]: > My read of your suggestion is to change ).insert(_toolbar!); to ).insert(_toolbar!, above: _handles?.end); so that when handles are present the assertion in _debugVerifyInsertPosition throws if the handle-before-toolbar order is ever reversed, and when _handles is null, (valid on some platforms / EditableText paths where handles aren't shown) it falls back to default top insertion.

correct

> Does that match what you had in mind, or did you want it narrower (e.g. only from the Android long-press path)?.

should be universally for all cases if possible

**Review by loic-sharma — DISMISSED** [review]
Re-LGTM

**Review by loic-sharma — APPROVED** [review]
Re-LGTM

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by Renzo-Olivares — APPROVED** [review]
Re-LGTM
