### PR TITLE
Warm cache with all transitive dependencies in `flutter update-packages` command

### LINKED ISSUE #96240: update-packages is failing due to conflicts between concurrent pub get processes
We are sometimes seeing failures in `flutter update-packages` when a `pub get` process throws an exception due to invalid filesystem state in the pub cache.

This seems to be happening especially often in Cirrus CI jobs.  Several Dart->engine and Skia->engine rolls recently failed due to this:
(examples: https://github.com/flutter/engine/runs/4730759888 and https://github.com/flutter/engine/runs/4723438043)

`update-packages` starts multiple concurrent instances of `pub get` in order to improve performance (see https://github.com/flutter/flutter/commit/01af8e5987e4ed1f4ea12675975e98bc0ebe87ac).
It looks like this may be unsafe if the `pub get` processes are simultaneously trying to download a package and update the pub cache.

`update-packages` also tries to prewarm the cache and force a download of the necessary packages before running `pub get` on the various Flutter subcomponents.

@gspencergoog What is the prewarm expected to handle?

The prewarm is parsing the `pubspec.yaml` files in the subcomponents and fetching their direct dependencies.  But it appears to be skipping the autogenerated transitive dependencies declared in those `pubspec.yaml` files.

If the transitive dependencies are pinned to a different version than the one fetched by the prewarm, then the `pub get` calls for the subcomponents will still need to download more packages.  That can result in conflicting cache writes that cause errors in `pub get`.

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This change fixes a bug in `flutter update-packages` where it only pre-warms the pub cache with explicit dependencies, and doesn't pin the versions of the transitive dependencies. This meant that sometimes there could be contention when downloading transitive dependencies in parallel, since the warmed dependency might be a different version. Since `pub get` isn't really safe for parallel running when downloading packages, this sometimes causes CI failures.

In this change, all transitive dependencies are added, with pinned versions, to the pre-warm step, and so the remaining `pub get` runs can all run with `--offline`, making sure that there won't be contention when running them in parallel.

Also, I reorganized the `UpdatePackagesCommand` to split the `runCommand` function into several helper functions, to make it easier to follow the steps in the command. I also added a hermetic test for the `update-packages` command that will verify that `pub get` gets called for the things we expect, both normally, and when `--force-upgrade` is specified.

Lastly, I added a `--jobs` argument to the command to allow specification of the number of jobs, so that if (in the future) we have concurrency issues in CI, we can just pass `--jobs=1` to avoid them.

## Related Issues
 - Fixes https://github.com/flutter/flutter/issues/96240

## Tests
 - Added tests for the `update-packages` command, and some for the `PubspecYaml` class.

### CODE REVIEW

**Comment by gspencergoog** [comment]
cc @jason-simmons

File: packages/flutter_tools/lib/src/commands/update_packages.dart [hunk 1]
```diff
@@ -266,17 +359,17 @@ class UpdatePackagesCommand extends FlutterCommand {
...
-          final PubspecDependency previous = dependencies[dependency.name];
+          final PubspecDependency previous = explicitDependencies[dependency.name];
           if (dependency.kind != previous.kind || dependency.lockTarget != previous.lockTarget) {
             throwToolExit(
-              'Inconsistent requirements around ${dependency.name}; '
-              'saw ${dependency.kind} (${dependency.lockTarget}) in "${dependency.sourcePath}" '
-              'and ${previous.kind} (${previous.lockTarget}) in "${previous.sourcePath}".'
+                'Inconsistent requirements around ${dependency.name}; '
+                    'saw ${dependency.kind} (${dependency.lockTarget}) in "${dependency.sourcePath}" '
+                    'and ${previous.kind} (${previous.lockTarget}) in "${previous.sourcePath}".'
```
Comment (dnfield) [inline packages/flutter_tools/lib/src/commands/update_packages.dart:367]: nit: formatting

**Review by dnfield — APPROVED** [review]
LGTM with formatting nit
