### PR TITLE
[flutter_tools] validate android arch and build number

### LINKED ISSUE #45256: Silent gradlew crash when flutterVersion is larger than 32bit integer
After changing some CI config, builds started failing with the following error:

```
Initializing gradle...                                              0.5s
Resolving dependencies...                                               
* Error running Gradle:
ProcessException: Process "/home/code/my_flutter_app/android/gradlew" exited abnormally:

  Command: /home/code/my_flutter_app/android/gradlew app:properties


Please review your Gradle project setup in the android/ folder.
```

Manually running that gradle task (`cd android && ./gradlew app:properties`) started to print some output, but then exited with no error message.

It was only after opening the `android` directory in Android Studio that I finally saw an error message: `ERROR: For input string: "20191119142208"`. This is the `flutter.versionCode=20191119142208` from the `local.properties` file, which is then converted to an int in build.gradle: 
```
defaultConfig {
    versionCode flutterVersionCode.toInteger()
    ...
}
```
Changing the version code to something that fits in a 32-bit integer fixes the issue. Googling only found results relating to #23777 and #34324 so I figured I'd open an issue to help future googlers.

## Steps to Reproduce

1. Open `android/local.properties` 
2. Add `flutter.versionCode=20191119142208`
3. Run `flutter build apk`

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_CA.UTF-8)
    • Flutter version 1.9.1+hotfix.6 at /*****/Flutter/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /*****/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /*****/Android/Sdk
    • ANDROID_SDK_ROOT = /*****/Android/Sdk
    • Java binary at: /*****/AndroidStudio/ch-0/183.5692245/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /*****/AndroidStudio/ch-0/183.5692245
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /*****/IDEA-U/ch-0/192.5728.98
    • Flutter plugin version 39.0.4
    • Dart plugin version 192.7402

[✓] Connected device (1 available)
    • SM T510 • android-arm • Android 9 (API 28)

• No issues found!
```

### LINKED ISSUE #57815: Display warning/error when building android application with build number greater than allowed value
Hello everyone. I have setup a CI which uses the current timestamp since epoch as the build number. It was working just fine, until today. It stopped accepting the build-number. I suppose this is a problem at handling large integer values ? Btw, our app is actually blocked upon compiling (and we cannot go back as we already published several playstore and app-store versions).

## Steps to Reproduce

1. Run `flutter create bug`.
2. flutter build appbundle -t lib/main.dart --build-name=5.44.0 --build-number=1590170586079 --release --tree-shake-icons

**Expected results:** AppBundle or APK compiles

**Actual results:** 
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/nicolas/dev/xxx/android/app/build.gradle' line: 42

* What went wrong:
A problem occurred evaluating project ':app'.
> For input string: "1590170586079"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 663ms
Running Gradle task 'bundleXXX'...
Running Gradle task 'bundleXXX'... Done                  1,4s
Gradle task bundleXXX failed with exit code 1
```

and line 42 is: 
```
versionCode flutterVersionCode.toInteger()
```

<details>
  <summary>Logs</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale it-IT)
    • Flutter version 1.17.1 at /Users/nicolas/dev/flutter_sdk/flutter
    • Framework revision f7a6a7906b (10 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nicolas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/nicolas/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/nicolas/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android
      Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Users/nicolas/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 201.7223.99
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (1 available)
    • ASUS Z00A • XXX • android-x86 • Android 7.1.2 (API 25)

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Validate that the android arch and build number are valid before hitting gradle.

Fixes https://github.com/flutter/flutter/issues/57815
Fixes https://github.com/flutter/flutter/issues/45256

related to https://github.com/flutter/flutter/issues/57824

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/build_validation.dart [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+import '../base/common.dart';
+import '../build_info.dart';
+
+const String kGooglePlayVersioning = 'https://developer.android.com/studio/publish/versioning.html';
+
+/// Validates that the build mode and build number are valid for a given build.
+void validateBuild(AndroidBuildInfo androidBuildInfo) {
+  final BuildInfo buildInfo = androidBuildInfo.buildInfo;
+  if (buildInfo.mode.isPrecompiled && androidBuildInfo.targetArchs.contains(AndroidArch.x86)) {
+    throwToolExit('Cannot build ${androidBuildInfo.buildInfo.mode.name} mode for x86 ABI.');
```
Comment (blasten) [inline packages/flutter_tools/lib/src/android/build_validation.dart:14]: Uber nit: Link to https://flutter.dev/docs/deployment/android#what-are-the-supported-target-architectures

**Review by blasten — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/android/build_validation.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/android/build_validation.dart:14]: Ahh, good idea!

File: packages/flutter_tools/test/general.shard/android/build_validation_test.dart [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+      const AndroidBuildInfo(
+        // Negative number
+        BuildInfo(BuildMode.debug, '', treeShakeIcons: false, buildNumber: '-1'),
+        targetArchs: <AndroidArch>[AndroidArch.x86],
+      ),
+    ), throwsToolExit(message: 'buildNumber: -1 must be a positive integer value.'));
+
+    expect(() => validateBuild(
+      const AndroidBuildInfo(
+        // Nigger than maximum supported play store value
```
Comment (imrhk) [inline packages/flutter_tools/test/general.shard/android/build_validation_test.dart:48]: Please fix the typo.

Comment (jonahwilliams) [reply packages/flutter_tools/test/general.shard/android/build_validation_test.dart:48]: https://github.com/flutter/flutter/pull/61548
