### PR TITLE
Fix previous text input connection interrupts enter/space

### LINKED ISSUE #51478: Flutter OnScreen Keyboard opens on physical key press
I have a device that uses a laserscanner to scan barcodes and outputs the result as simulated keypresses. I've used this with a RawKeyboardListener and it worked fine. Since then I've added a login screen to the app, that is only shown if the user hasn't logged in. If the login screen has been shown and disposed the onscreen keyboard opens when i press the physical scanner button. This should not happen and doesn't happen if the login screen hasn't been shown. My guess is, that there still are some remains of the textfields used in the login screen, after it is disposed. I've tried setting the FocusNodes for the Textfields and then disposing them in the dispose method, but that didn't work

I've asked a question on StackOverflow: [https://stackoverflow.com/questions/60417173/flutter-onscreen-keyboard-opens-on-physical-key-press](url)

## Steps to Reproduce

1. Screen with one or more Textfields
2. focus one or more
3. navigate to new screen
4. press physical button

**Expected results:** button is pressed but only the keyevents are fired

**Actual results:** the onscreen keyboard opens

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.16299.1686], locale de-DE)
    • Flutter version 1.12.13+hotfix.8 at C:\Users\sruettge\Documents\flutter
    • Framework revision 0b8abb4724 (2 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\sruettge\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\sruettge\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • MEMOR 10 • S19H00332 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

</details>

### LINKED ISSUE #70546: RawKeyboardListener triggers soft keyboard on Android
This was spun off from https://github.com/flutter/flutter/issues/67915.

On Android, `RawKeyboardListener` triggers the soft keyboard when it receives input. This only happens after a TextField has received focus once. Until a TextField has received focus, the soft keyboard remains hidden.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Replace `main.dart` with this:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final FocusNode rawKbFocusNode = FocusNode();
  final FocusNode textFocusNode = FocusNode();

  bool renderTextField = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RawKeyboardListener(
              onKey: (event) {
                print(event);
              },
              focusNode: rawKbFocusNode,
              autofocus: true,
              child: renderTextField
                  ? TextField(
                      focusNode: textFocusNode,
                    )
                  : Text('No textfield'),
            ),
            RaisedButton(
              child: Text('Focus RawKeyboardListener'),
              onPressed: () => rawKbFocusNode.requestFocus(),
            ),
            RaisedButton(
              child: Text('Toggle textfield'),
              onPressed: () => setState(() {
                renderTextField = !renderTextField;
              }),
            )
          ],
        ),
      ),
    );
  }
}
```

3. Use a hardware keyboard to enter text. Key events are printed, no soft keyboard is visible.
4. Focus the text field. Move focus back to `RawKeyboardListener`.
5. Use the hardware keyboard again to enter text. Now the soft keyboard will pop up.
6. Dismiss the soft keyboard and enter some more text. Soft keyboard will show again.
7. Even if the TextField is not rendered anymore, the same behavior keeps happening.

**Expected results:** 

I expected the soft keyboard to remain hidden. As long as no`TextField` receives focus, things behave as expected.
Only after a TextField has received focus once, the soft keyboard will keep popping up when the `RawKeyboardListener` receives input.

**Actual results:** 

The soft keyboard shows up.

Here's a gif showing the behavior.
All input is typed via a hardware keyboard.

rawkeyboardlistener

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.230, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.230 at /Users/Pascal/.local/flutter-master
    • Framework revision af5eb3b987 (32 hours ago), 2020-11-13 19:57:15 +0800
    • Engine revision dddb532b5c
    • Dart version 2.12.0 (build 2.12.0-37.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/Pascal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/Pascal/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64  • Mac OS X 10.15.7 19H15 darwin-x64

• No issues found!
```

</details>

### LINKED ISSUE #168099: TextInputConnection interferes with widget selection when using external keyboard
### Steps to reproduce

1. Press tab key until reaching TextField or tap on TextField to establish a text input connection.
2. Press tab key until reaching "Radio Option 3".
3. Press space or enter to select a "Radio Option 3".

### Expected results

Radio Option 3 is selected.

### Actual results

Radio button selection does not change.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

// Main application widget
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final TextEditingController _textController = TextEditingController();
  int? _radioValue = 1;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: ListView(
          children: <Widget>[
            const SizedBox(height: 8),
            TextField(
              controller: _textController,
              decoration: const InputDecoration(
                border: OutlineInputBorder(),
                labelText: 'Enter text',
                hintText: 'Type something here',
                prefixIcon: Icon(Icons.edit),
              ),
            ),
            const SizedBox(height: 20),
            Column(
              children: <Widget>[
                RadioListTile<int>(
                  title: const Text('Radio Option 1'),
                  value: 1,
                  groupValue: _radioValue,
                  onChanged: (int? value) {
                    setState(() {
                      _radioValue = value;
                    });
                  },
                ),
                RadioListTile<int>(
                  title: const Text('Radio Option 2'),
                  value: 2,
                  groupValue: _radioValue,
                  onChanged: (int? value) {
                    setState(() {
                      _radioValue = value;
                    });
                  },
                ),
                 RadioListTile<int>(
                  title: const Text('Radio Option 3'),
                  value: 3,
                  groupValue: _radioValue,
                  onChanged: (int? value) {
                    setState(() {
                      _radioValue = value;
                    });
                  },
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    _textController.dispose();
    super.dispose();
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/9d11a6f3-34c2-4406-be51-8ce0dc92f9c9

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Fixes an issue where a previously closed text input connection may cause interference with hardware keyboard on Samsung devices. 

On the Samsung Galaxy S10 Tab the Samsung IME will request the operating system to show the IME when pressing enter/space on components like a radio option or a checkbox if there was a previously opened text input connection. It seems the Samsung Keyboard is caching some text input related state, and when it detects an enter/space key it acts on this previously cached state even if the text input connection has been closed. This prevents the radio option/checkbox and framework as a whole from responding to the key events. To solve this issue we should reset the input method manager when the IME has been hidden, and when the framework closes the input connection we should also reset the input method manager if the IME is hidden at the time of closing. This effectively resets any state cached by the Samsung keyboard and it no longer acts on stale state.

Fixes https://github.com/flutter/flutter/issues/168099
Fixes https://github.com/flutter/flutter/issues/51478
Fixes https://github.com/flutter/flutter/issues/70546

Related:
https://github.com/flutter/flutter/issues/136745

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: engine/src/flutter/shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java [hunk 1]
```diff
@@ -1230,6 +1230,49 @@ public void setTextInputEditingState_nullInputMethodSubtype() {
     assertEquals(1, testImm.getRestartCount(testView));
   }
 
+  @Test
+  public void clearTextInputClient_restartsImmWhenIMEHidden() {
```
Comment (camsim99) [inline engine/src/flutter/shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java]: I can see how this tests the changes to the `TextInputPlugin` constructor, but does this actually call/test `clearTextInputClient`? Sorry if I'm missing it; from what I can tell, that is only called via method channel?

**Review by camsim99 — COMMENTED** [review]
Overall looks good! I just have one question about the test.

**Review by justinmc — APPROVED** [review]
LGTM 👍 

Restarting the IME when it disappears seems like it would be a good idea. I know we have had lots of bugs related to lingering state in Samsung IMEs and have tried a lot of hacks to restart the IME. It seems to me like you always want it to restart when it disappears though, and I'm encouraged by seeing this close several different issues.

File: engine/src/flutter/shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java [hunk 2]
```diff
@@ -1230,8 +1230,124 @@ public void setTextInputEditingState_nullInputMethodSubtype() {
...
+            // Imm restarts when clearTextInputClient is called while the IME is hidden.
+            textInputPlugin.clearTextInputClient();
+            assertEquals(3, testImm.getRestartCount(testView));
+          });
+    }
+  }
+
   @Test
   public void destroy_clearTextInputMethodHandler() {
+
```
Comment (loic-sharma) [inline engine/src/flutter/shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java]: This new line looks unintentional? (Feel free to skip if this is intentional!)

```suggestion
```

File: engine/src/flutter/shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java (hunk 1 above)
Comment (Renzo-Olivares) [reply engine/src/flutter/shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java]: Good point, I added a new test that calls `clearTextInputClient` explicitly.

File: engine/src/flutter/shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java (hunk 2 above)
Comment (Renzo-Olivares) [reply engine/src/flutter/shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java]: Thanks for catching that!

**Review by camsim99 — APPROVED** [review]
LGTM!
