### PR TITLE
[A11y] Allow percentage strings like "50%" as `SemanticsValue` for `ProgressIndicator`

### LINKED ISSUE #182491: a11y android semanticsValue causes screen to freeze
### Steps to reproduce

1. flutter create --sample=material.CircularProgressIndicator.1
2. madd semanticsValue: "someval" to the CircularProgressIndicator

### Expected results

The progress bar should be correctly visible to talkback. So should the other controls on the screen.

### Actual results

Talkback can't see any control on progress bar screen

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      // Setting this to true will help you instantly see the semantics crash!
      showSemanticsDebugger: true, 
      home: ProgressIndicatorExample(),
    );
  }
}

class ProgressIndicatorExample extends StatefulWidget {
  const ProgressIndicatorExample({super.key});

  @override
  State<ProgressIndicatorExample> createState() => _ProgressIndicatorExampleState();
}

class _ProgressIndicatorExampleState extends State<ProgressIndicatorExample> with SingleTickerProviderStateMixin {
  bool year2023 = false;
  late AnimationController controller;

  @override
  void initState() {
    super.initState();
    // Creates a dummy progress value that loops from 0.0 to 1.0
    controller = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 2),
    )..addListener(() {
        setState(() {});
      })..repeat();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Semantics Crash Repro')),
      body: Center(
        child: Column(
          spacing: 16.0,
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('Determinate CircularProgressIndicator'),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              child: CircularProgressIndicator(
                // ignore: deprecated_member_use
                year2023: year2023,
                // BUG TRIGGER: The "%" symbol here causes the crash when Semantics tries to parse it
                semanticsValue: "${controller.value}%", 
                value: controller.value,
              ),
            ),
            const Text('Indeterminate CircularProgressIndicator'),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              // ignore: deprecated_member_use
              child: CircularProgressIndicator(year2023: year2023),
            ),
            SwitchListTile(
              value: year2023,
              title: year2023
                  ? const Text('Switch to latest M3 style')
                  : const Text('Switch to year2023 M3 style'),
              onChanged: (bool value) {
                setState(() {
                  year2023 = !year2023;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY
╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Progress bar value, minValue, and maxValue must be valid numbers. value:
"0.2517312%", minValue:
"0", maxValue: "100"

When the exception was thrown, this was the stack:
#0      SemanticsNode._addToUpdate.<anonymous closure>
(package:flutter/src/semantics/semantics.dart:4014:9)
#1      SemanticsNode._addToUpdate
(package:flutter/src/semantics/semantics.dart:4017:6)
#2      SemanticsOwner.sendSemanticsUpdate
(package:flutter/src/semantics/semantics.dart:4987:14)
#3      PipelineOwner.flushSemantics
(package:flutter/src/rendering/object.dart:1516:24)
#4      PipelineOwner.flushSemantics
(package:flutter/src/rendering/object.dart:1518:15)
#5      RendererBinding.drawFrame
(package:flutter/src/rendering/binding.dart:636:25)
#6      WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:1477:13)
#7      RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:495:5)
#8      SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1430:15)
#9      SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1345:9)
#10     SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1198:5)
#11     _invoke (dart:ui/hooks.dart:423:13)
#12     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:447:5)
#13     _drawFrame (dart:ui/hooks.dart:395:31)
════════════════════════════════════════════════════════════════════════════════
════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output main branch</summary>

```console
[zywek@dell sample5]$ flutter doctor -v
[✓] Flutter (Channel main, 3.42.0-1.0.pre-151, on Arch Linux 6.18.5-arch1-1,
    locale pl_PL.UTF-8) [452ms]
    • Flutter version 3.42.0-1.0.pre-151 on channel main at
      /home/zywek/git/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 9fa7f81be0 (2 godziny temu), 2026-02-17 05:03:31 -0500
    • Engine revision 9fa7f81be0
    • Dart version 3.12.0 (build 3.12.0-154.0.dev)
    • DevTools version 2.55.0
    • Feature flags: enable-web, enable-linux-desktop, no-enable-macos-desktop,
      no-enable-windows-desktop, enable-android, no-enable-ios,
      no-cli-animations, enable-native-assets, omit-legacy-version-file,
      enable-lldb-debugging, enable-uiscene-migration, enable-riscv64

[✓] Android toolchain - develop for Android devices (Android SDK version 36.1.0)
    [973ms]
    • Android SDK at /opt/android-sdk
    • Emulator version 36.2.12.0 (build_id 14214601) (CL:N/A)
    • Platform android-36.1, build-tools 36.1.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/bin/java
      This JDK was found in the system PATH.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.17+10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web [5ms]
    • CHROME_EXECUTABLE = /opt/brave-bin/brave

[✓] Linux toolchain - develop for Linux desktop [215ms]
    • clang version 21.1.6
    • cmake version 4.2.1
    • ninja version 1.13.2
    • pkg-config version 2.5.1
    • OpenGL core renderer: Mesa Intel(R) Graphics (ARL) (X11)
    • OpenGL core version: 4.6 (Core Profile) Mesa 25.3.3-arch1.2 (X11)
    • OpenGL core shading language version: 4.60 (X11)
    • OpenGL ES renderer: Mesa Intel(R) Graphics (ARL) (X11)
    • OpenGL ES version: OpenGL ES 3.2 Mesa 25.3.3-arch1.2 (X11)
    • OpenGL ES shading language version: OpenGL ES GLSL ES 3.20 (X11)
    • GL_EXT_framebuffer_blit: yes (X11)
    • GL_EXT_texture_format_BGRA8888: yes (X11)

[✓] Connected device (3 available) [179ms]
    • SM G973F (mobile) • RF8M63XB4HA • android-arm64  • Android 15 (API 35)
    • Linux (desktop)   • linux       • linux-x64      • Arch Linux
      6.18.5-arch1-1
    • Chrome (web)      • chrome      • web-javascript • Brave Browser
      143.1.85.120 unknown

[✓] Network resources [218ms]
    • All expected network resources are available.

• No issues found!
[zywek@dell sample5]$ 

```

</details>

<details open><summary>Doctor output stable branch</summary>

```console
[zywek@dell sample5]$ flutter doctor -v
[✓] Flutter (Channel stable, 3.41.1, on Arch Linux 6.18.5-arch1-1, locale
    pl_PL.UTF-8) [17ms]
    • Flutter version 3.41.1 on channel stable at /home/zywek/git/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 582a0e7c55 (4 dni temu), 2026-02-12 17:12:32 -0800
    • Engine revision 3452d735bd
    • Dart version 3.11.0
    • DevTools version 2.54.1
    • Feature flags: enable-web, enable-linux-desktop, no-enable-macos-desktop,
      no-enable-windows-desktop, enable-android, no-enable-ios,
      no-cli-animations, enable-native-assets, omit-legacy-version-file,
      enable-lldb-debugging, enable-uiscene-migration

[✓] Android toolchain - develop for Android devices (Android SDK version 36.1.0)
    [711ms]
    • Android SDK at /opt/android-sdk
    • Emulator version 36.2.12.0 (build_id 14214601) (CL:N/A)
    • Platform android-36.1, build-tools 36.1.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/bin/java
      This JDK was found in the system PATH.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 17.0.17+10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web [4ms]
    • CHROME_EXECUTABLE = /opt/brave-bin/brave

[✓] Linux toolchain - develop for Linux desktop [204ms]
    • clang version 21.1.6
    • cmake version 4.2.1
    • ninja version 1.13.2
    • pkg-config version 2.5.1
    • OpenGL core renderer: Mesa Intel(R) Graphics (ARL) (X11)
    • OpenGL core version: 4.6 (Core Profile) Mesa 25.3.3-arch1.2 (X11)
    • OpenGL core shading language version: 4.60 (X11)
    • OpenGL ES renderer: Mesa Intel(R) Graphics (ARL) (X11)
    • OpenGL ES version: OpenGL ES 3.2 Mesa 25.3.3-arch1.2 (X11)
    • OpenGL ES shading language version: OpenGL ES GLSL ES 3.20 (X11)
    • GL_EXT_framebuffer_blit: yes (X11)
    • GL_EXT_texture_format_BGRA8888: yes (X11)

[✓] Connected device (3 available) [182ms]
    • SM G973F (mobile) • RF8M63XB4HA • android-arm64  • Android 15 (API 35)
    • Linux (desktop)   • linux       • linux-x64      • Arch Linux
      6.18.5-arch1-1
    • Chrome (web)      • chrome      • web-javascript • Brave Browser
      143.1.85.120 unknown

[✓] Network resources [222ms]
    • All expected network resources are available.

• No issues found!
[zywek@dell sample5]$ 

```

</details>

I hope someone will take a peek at this sooner than [this](https://github.com/flutter/flutter/issues/149613)  it is quite important to me as this error appeared in the app ready to be updated on google play

### PR DESCRIPTION
**Pull request by hannah-hyj**
Fix: #182491 

So they can make the progress bar read "50%" instead of "0.5", "50" and provide a better user experience. 

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [AI contribution guidelines] and understand my responsibilities, or I am not using AI tools.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[AI contribution guidelines]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#ai-contribution-guidelines
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 1]
```diff
@@ -223,12 +223,13 @@ sealed class _DebugSemanticsRoleChecks {
...
-    // Validate that value is within min and max range
-    try {
-      final double currentValue = double.parse(data.value);
-      final double minVal = double.parse(data.minValue!);
-      final double maxVal = double.parse(data.maxValue!);
-
+    // Validate that the value is within the min and max range if all values are
+    // valid numbers. If the value is a descriptive string (e.g., "50%"), skip
+    // numeric validation.
+    final double? currentValue = double.tryParse(data.value);
```
Comment (chunhtai) [inline packages/flutter/lib/src/semantics/semantics.dart]: can you double check what would happen in web when the value contains non numerical string?

Comment (hannah-hyj) [reply packages/flutter/lib/src/semantics/semantics.dart]: on web if the value is set to "randomstring" it will announce "0% ,randomstring" , it's not ideal.

Comment (hannah-hyj) [reply packages/flutter/lib/src/semantics/semantics.dart]: I think we can do maybe:
[SemanticsValue] support a double or a percentage string like "50%", and if it's a percentage string we change it to a double for web.

Comment (chunhtai) [reply packages/flutter/lib/src/semantics/semantics.dart]: post processing like this may be confusing. I would rather throw and let customer figure out.

Comment (hannah-hyj) [reply packages/flutter/lib/src/semantics/semantics.dart]: do we only throw for web or throw for all platform?

Comment (hannah-hyj) [reply packages/flutter/lib/src/semantics/semantics.dart]: I was reading slider  when trying to adding a slider role.
For slider,
we set semantics value to XX% for both material and cupertino, https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/slider.dart#L1938 
And doing some post processing in web: https://github.com/flutter/flutter/blob/master/engine/src/flutter/lib/web_ui/lib/src/engine/semantics/incrementable.dart#L95-L100 

I think we can do the same thing for progressbar to support XX%

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/progress_bar.dart [hunk 2]
```diff
@@ -29,7 +29,25 @@ class SemanticsProgressBar extends SemanticRole {
...
+
+      if (doubleValue != null) {
+        setAttribute('aria-valuenow', value);
+      } else if (value.endsWith('%')) {
+        final double? percentage = double.tryParse(value.substring(0, value.length - 1));
+        if (percentage != null) {
+          final double? min = double.tryParse(semanticsObject.minValue ?? '');
+          final double? max = double.tryParse(semanticsObject.maxValue ?? '');
+          if (min != null && max != null) {
+            final double calculatedValue = min + (percentage / 100.0) * (max - min);
```
Comment (chunhtai) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/progress_bar.dart:43]: is this a use case backing this? the developer sets min and max and use % in value? I don't think we do this by default? If the this is set by user, would be better to just throw or ignore them and use which ever value store in the progress indicator, since we will be introducing a failure of value for them.

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/progress_bar.dart [hunk 3]
```diff
@@ -29,7 +29,25 @@ class SemanticsProgressBar extends SemanticRole {
...
+            setAttribute('aria-valuenow', calculatedValue.toString());
+          }
+        }
+        setAttribute('aria-valuetext', value);
```
Comment (chunhtai) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/progress_bar.dart:47]: if we set this, do we still need valuenow?

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/progress_bar.dart (hunk 2 above)
Comment (hannah-hyj) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/progress_bar.dart:43]: for slider, we support setting min and max as double and use % in value. 
for progress bar, we dont support setting min and max as double and use % in value. 

I think we can make progress bar and slider consistent. 

the use case was raised in https://github.com/flutter/flutter/issues/182491

Comment (chunhtai) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/progress_bar.dart:43]: do we have safe guard if the value and semantics value doesn't match? for example the value is 60, but the semantics value is 45%. If not, whats should get priority over the other.

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/progress_bar.dart (hunk 3 above)
Comment (hannah-hyj) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/progress_bar.dart:47]: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-valuetext says valuetext is only need if it's some meaningful info on the top of valuenow. `For example, a battery meter value might be conveyed as aria-valuetext="8% (34 minutes) remaining".`

since it's only for custom text like that we can only set valuenow, not valuetext.  I will remove the  valuetext.

Comment (chunhtai) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/progress_bar.dart:47]: it almost feels like we need another semantics property for this, it feels a bit troublsome for both customer and our code to make sense of custom value string and how they apply to these property. If almost feels like we need a separate semantics property for this.

just thowing out idea, what if we set the hint to valuetext?

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/progress_bar.dart (hunk 2 above)
Comment (hannah-hyj) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/progress_bar.dart:43]: we don't have a safe guard for that. 
but we also don't have a safe guard for number values,  if the value is 60 and but the developer set the  semantic value to 70.  we will announce 70.

**Review by chunhtai — DISMISSED** [review]
LGTM

**Review by chunhtai — APPROVED** [review]
LGTM
