### PR TITLE
Text Selection Overflow (Android)

### LINKED ISSUE #50935: Incorrect Cut/Copy/Paste button positioning above text field
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: .

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(child: TextField(maxLines: 3)),
      ),
    );
  }
}
```
3. Type more than 3 lines of text into the text field. Tap the cursor to bring up "PASTE / SELECT ALL" buttons, then tap "SELECT ALL".

**Expected results:** The "CUT / COPY / PASTE" buttons immediately above the text field.

**Actual results:** 
The "CUT/COPY/PASTE" buttons float above the text field at a height determined by how many lines are in the field. In the extreme case, you can get the buttons floating at the very top of the screen:

image

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/matt/lib/flutter
    • Framework revision 0b8abb4724 (6 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/matt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/matt/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
## Description

The text selection menu overflows in some fairly common cases.  This PR will fix it by handling it the same way that native does.

This PR is only for Android, and we'll need to do a similar approach for iOS.

## Related Issues

https://github.com/flutter/flutter/issues/35826
Closes https://github.com/flutter/flutter/issues/50935

## Tests

In material/text_selection_test.dart, I tested various overflow cases and the position of the menu above and below the anchor. I also noticed an edge case in showing the menu when a large block of text was selected, and I wrote a test for that too.

## Breaking change
This is a breaking change, see the [design doc](https://docs.google.com/document/d/1qSEvbgi3m-OvB_dUKch8LHOk-iyPFeLgCsXbK0bI2DA/edit).

### CODE REVIEW

File: packages/flutter/test/material/text_field_test.dart [hunk 1]
```diff
@@ -560,6 +522,8 @@ void main() {
     await tester.pump(const Duration(milliseconds: 50));
 
     await tester.tapAt(textfieldStart + const Offset(150.0, 9.0));
+    // Selection menu renders one frame offstage, so pump twice.
+    await tester.pump();
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart]: I had to add a second pump all over the place due to the selection menu rendering offstage for the first frame.  A single pumpAndSettle didn't work.  Is there any other way to avoid all of these?

Comment (chunhtai) [reply packages/flutter/test/material/text_field_test.dart]: If it is delayed for a frame, you will have to do this all over

File: packages/flutter/lib/src/material/text_selection.dart [hunk 2]
```diff
@@ -20,64 +23,390 @@ const double _kHandleSize = 22.0;
...
+  final double width;
+
+  @override
+  _TextSelectionToolbarContainerState createState() => _TextSelectionToolbarContainerState();
+}
+
+class _TextSelectionToolbarContainerState extends State<_TextSelectionToolbarContainer> with TickerProviderStateMixin {
+  @override
+  Widget build(BuildContext context) {
+    return Container(
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/text_selection.dart]: I just throwing out idea, can we have a RenderObjectElement that can rebuild again if it is not happy about its rendering object? A new RenderObject that take a callback and call the callback after it has been laid out, the Element can use the callback to rebuild if it is not happy about it maybe by marking it dirty or something.

Here you can use a sizedBox instead of container so that it never overflow and will return the width it need

Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Pinging @goderbauer in case you know whether this is possible.

What I would need is to be able to build one widget tree, lay it out, and at that time be able to scrap the widget tree and build and lay out a new one.  The reason is that the widget tree depends on the size of the children to determine if they go into the overflow menu or not.

I took a look at RenderObjectElement and how its used in LayoutBuilder as an example, and I didn't see how this would be possible, but I could be missing it.  For example, [where it calls the `builder` method](https://github.com/flutter/flutter/blob/4896c85ede72a7c9571fb534d21d8570a73697ba/packages/flutter/lib/src/widgets/layout_builder.dart#L100) (and I imagine I could call one of two builder methods or something like that), the layout phase hasn't happened and I wouldn't know the size of the children.  In [performLayout](https://github.com/flutter/flutter/blob/4896c85ede72a7c9571fb534d21d8570a73697ba/packages/flutter/lib/src/widgets/layout_builder.dart#L240) during the layout phase, it doesn't seem possible to build a different child.

Hopefully someone knows for sure either way.

Comment (goderbauer) [reply packages/flutter/lib/src/material/text_selection.dart]: I don't think we should make it particularly easy to delay things by a frame as this can easily lead to janky UI.

If you would like to do this all in the same frame you probably could with a custom RenderObject similarly to how we do it with lazy (sliver) lists:

I'd imagine a Toolbar widget that takes two builders:
* The first builder takes a BuildContext and an index. It returns a widget that should be shown in the toolbar.
* The second builder also takes a BuildContext and an index. It returns a widget for the overflow menu with all the items remaining starting at index.

The toolbar widget is now backed by a custom RenderObject that in its layout calls the first builder for index 0 and lays out that child. Now you have its dimensions. If there's room for more, it will call the builder for index 1 and lays that out. And so on.

Once it runs out of space, it would call the second builder to obtain and layout the overflow menu.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 3]
```diff
@@ -20,64 +23,390 @@ const double _kHandleSize = 22.0;
 const double _kToolbarScreenPadding = 8.0;
 const double _kToolbarHeight = 44.0;
 // Padding when positioning toolbar below selection.
-const double _kToolbarContentDistanceBelow = 16.0;
+const double _kToolbarContentDistanceBelow = _kHandleSize - 2.0;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/text_selection.dart]: Was 16 is now 20 - that's OK?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 4]
```diff
@@ -20,64 +23,390 @@ const double _kHandleSize = 22.0;
...
+  @override
+  _TextSelectionToolbarState createState() => _TextSelectionToolbarState();
+}
+
+class _TextSelectionToolbarState extends State<_TextSelectionToolbar> {
+  final GlobalKey _containerKey = GlobalKey();
+  final GlobalKey _moreButtonKey = GlobalKey();
+
+  // The width of all of the items that are being rendered in the closed
+  // toolbar, including the more button if visible.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/text_selection.dart]: the "more" button, if visible

File: packages/flutter/lib/src/material/text_selection.dart [hunk 5]
```diff
@@ -20,64 +23,390 @@ const double _kHandleSize = 22.0;
...
+    final int itemsInFirstMenu = _indexWhereOverflows == -1 ? _itemKeys.length : _indexWhereOverflows;
+    if (_itemKeys.isEmpty || itemsInFirstMenu == null) {
+      return false;
+    }
+    return itemsInFirstMenu < _itemKeys.length;
+  }
+
+  @override
+  void initState() {
+    _measureItemsNextFrame();
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/text_selection.dart]: NICE

File: packages/flutter/lib/src/material/text_selection.dart [hunk 6]
```diff
@@ -20,64 +23,390 @@ const double _kHandleSize = 22.0;
...
     final MaterialLocalizations localizations = MaterialLocalizations.of(context);
-    final List<Widget> items = <Widget>[
-      if (handleCut != null) FlatButton(child: Text(localizations.cutButtonLabel), onPressed: handleCut),
-      if (handleCopy != null) FlatButton(child: Text(localizations.copyButtonLabel), onPressed: handleCopy),
-      if (handlePaste != null) FlatButton(child: Text(localizations.pasteButtonLabel), onPressed: handlePaste),
-      if (handleSelectAll != null) FlatButton(child: Text(localizations.selectAllButtonLabel), onPressed: handleSelectAll),
-    ];
+
+    final List<Widget> items = <Widget>[];
+    _itemKeys.removeRange(0, _itemKeys.length);
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/text_selection.dart]: Same as _itemKeys.clear()

File: packages/flutter/lib/src/material/text_selection.dart [hunk 7]
```diff
@@ -20,64 +23,390 @@ const double _kHandleSize = 22.0;
...
+    if (widget.handleCut != null) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/text_selection.dart]: It looks like the code here could be factored into a local function like:
```dart
void _addSelectionMenuItem(VoidCallback handler, String label) {
  if (handler = null)
     return;
  _itemKeys.add(GlobalKey());
  items.add(
    FlatButton(
      key: _itemKeys.last,
      child: Text(label),
      onPressed: () {
        setState(() {
          _overflowOpen = false;
        });
        handler();
      },
    ),
  );
}
```

File: packages/flutter/lib/src/material/text_selection.dart [hunk 8]
```diff
@@ -20,64 +23,390 @@ const double _kHandleSize = 22.0;
...
     if (items.isEmpty) {
       return Container(width: 0.0, height: 0.0);
     }
 
-    return Material(
-      elevation: 1.0,
-      child: Container(
-        height: _kToolbarHeight,
-        child: Row(mainAxisSize: MainAxisSize.min, children: items),
+    // If _itemsInFirstMenu hasn't been calculated yet, render offstage for one
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/text_selection.dart]: On the face of it, it looks like "If _menuContentWidth" hasn't been calculated yet.

**Review by HansMuller — COMMENTED** [review]
Will defer reviewing the rest of this until you've decided about https://github.com/flutter/flutter/pull/49391/files#r375987680

File: packages/flutter/lib/src/material/text_selection.dart [hunk 9]
```diff
@@ -20,64 +23,413 @@ const double _kHandleSize = 22.0;
...
+          isAbove: widget.isAbove,
+          overflowOpen: _overflowOpen,
+          children: <Widget>[
+            // The navButton that shows and hides the overflow menu is the first
+            // child.
+            Material(
+              child: IconButton(
+                // TODO(justinmc): This should be an AnimatedIcon, but
+                // AnimatedIcons doesn't yet support arrow_back to more_vert.
+                // https://github.com/flutter/flutter/issues/51209
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection.dart]: In addition to this, the icon actually animates its position in the native menu.  How can I do that given that this button is positioned by a RenderBox?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 10]
```diff
@@ -20,64 +23,413 @@ const double _kHandleSize = 22.0;
...
+
+      final RenderBox child = renderObjectChild as RenderBox;
+      final FlexParentData childParentData = child.parentData as FlexParentData;
+
+      // If the current child is not displayed, place it offscreen to avoid it
+      // interfering with hit detection.
+      if (_lastIndexThatFits != -1) {
+        if ((!overflowOpen && i > _lastIndexThatFits)
+          || (overflowOpen && i <= _lastIndexThatFits)) {
+          childParentData.offset = Offset(-child.size.width, -child.size.height);
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection.dart]: Is there any other way to make a child that isn't painted not be hit detected?

File: packages/flutter/lib/src/material/text_selection.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: @goderbauer @chunhtai I was finally able to get this working using RenderBox, needs re-review please!

I left a two questions in Github comments below.  Also, I noticed that several tests are now failing because menu buttons that are laid out but not painted are still detected by `findsNothing`.  This is similarly causing problems with hit detection, which I solved by placing these buttons offscreen.  Is there a way to stop the child from appearing in the tree altogether after calling `child.layout`?

File: packages/flutter/lib/src/material/text_selection.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: No longer relevant with the RenderBox approach.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: The code was removed with the RenderBox approach.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 10 above)
Comment (chunhtai) [reply packages/flutter/lib/src/material/text_selection.dart]: I wonder if you can override defaultHitTestChildren to walk through the list starting with  _lastIndexThatFits.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 11]
```diff
@@ -20,64 +23,406 @@ const double _kHandleSize = 22.0;
...
+    _overflowOpen = value;
+    markNeedsLayout();
+  }
+
+  // Lay out all children, regardless of whether or not they will be painted or
+  // placed with an offset. Find which child overflows, if any.
+  void _layoutChildren() {
+    int i = -1;
+    double width = 0.0;
+    visitChildren((RenderObject renderObjectChild) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/text_selection.dart]: do you have to layout all the children? Can you layout the child one by one and stop when the width overflows? Also can we defer the layout of navigation bar until we know it will overflow?

File: packages/flutter/test/material/text_field_test.dart [hunk 12]
```diff
@@ -1935,6 +1897,7 @@ void main() {
     final Offset slightRight = iPos + const Offset(30.0, 0.0);
     await tester.longPressAt(slightRight, pointer: 7);
     await tester.pump();
+    await tester.pump();
```
Comment (chunhtai) [inline packages/flutter/test/material/text_field_test.dart]: Is this still needed?

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 13]
```diff
@@ -622,6 +622,8 @@ void main() {
     const int dIndex = 5;
     final Offset dPos = textOffsetToPosition(tester, dIndex);
     await tester.longPressAt(dPos);
+    // Selection menu renders one frame offstage, so pump twice.
+    await tester.pump();
```
Comment (chunhtai) [inline packages/flutter/test/widgets/selectable_text_test.dart]: same here

**Review by chunhtai — COMMENTED** [review]
Looks like a good approach, I left some comments

File: packages/flutter/lib/src/material/text_selection.dart (hunk 10 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Yeah that would work, I'll implement it.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 11 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: In the case where the overflow menu is open, I have to layout all of the children, because I have to decide where it overflows and then I have to paint the overflowing children.  In the case where it's not open, I can add an optimization to not layout the overflowing children.

File: packages/flutter/test/material/text_field_test.dart (hunk 12 above)
Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart]: No, I thought I removed all of these!  Thanks.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 9 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Actually, it seems my AnimatedSize doesn't work either now that I'm using a RenderBox.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: I've adjusted the positioning to match native where I saw differences.  It breaks a few golden tests.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 8 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: This code was removed with the RenderBox approach.

**Comment by justinmc** [comment]
@chunhtai @goderbauer I've updated for code review again.

One problem I noticed: My AnimatedSize widget no longer seems to work to animate the size of the RenderBox's container (https://github.com/flutter/flutter/pull/49391/commits/76110884016b40f14cb4667c9946b3af657e7713).  Do I need to manually do the animation inside of my custom RenderBox (_TextSelectionToolbarItemsRenderBox)?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 14]
```diff
@@ -20,64 +23,411 @@ const double _kHandleSize = 22.0;
...
+    }
+
+    // If there is no overflow, all children besides the navButton are painted.
+    if (_lastIndexThatFits == -1) {
+      return true;
+    }
+
+    // When there is overflow, paint if the child is in the part of the menu
+    // that is currently open.
+    return (index > _lastIndexThatFits) == overflowOpen;
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/text_selection.dart]: when the overflow is open and index<= _lastIndexThatFits, don't we still want to paint?

Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: No, because when the overflow menu is open, only the overflowing items are shown.  So only the items with index > _lastIndexThatFits.  The opposite items are shown when the overflow menu is closed.

I'll add some more detail in my comments for overflowOpen because this is pretty nuanced.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 9 above)
Comment (chunhtai) [reply packages/flutter/lib/src/material/text_selection.dart]: Do you have a gif for native animation? I am not sure what animation we should achieve here

File: packages/flutter/lib/src/material/text_selection.dart [hunk 15]
```diff
@@ -20,64 +23,417 @@ const double _kHandleSize = 22.0;
...
+  final bool isAbove;
+
+  @override
+  _TextSelectionToolbarState createState() => _TextSelectionToolbarState();
+}
+
+class _TextSelectionToolbarState extends State<_TextSelectionToolbar> with TickerProviderStateMixin {
+  final GlobalKey _key = GlobalKey();
+
+  // Whether or not the overflow menu is open.  When it is closed, the menu
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: nit: extra " " (space) after the "."?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 16]
```diff
@@ -20,64 +23,417 @@ const double _kHandleSize = 22.0;
...
+            ...items,
+          ],
+        ),
+      ),
+    );
+
+    // When the menu shrinks as the overflow is opened, then it occupies the
+    // same size as it did with overflow closed and aligns itself to the right
+    // of its original size.
+    return _maxWidth == null ? child : SizedBox(
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: I don't fully get the _maxWidth business. Isn't that value always (at least) one frame behind?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 17]
```diff
@@ -20,64 +23,417 @@ const double _kHandleSize = 22.0;
...
+  // items that don't overflow are shown. When it is open, only the overflowing
+  // menu items are shown.
+  bool _overflowOpen = false;
+  // The greatest width ever measured for this widget. This is used to position
+  // the overflow menu when it is open, since it is usually not as wide as the
+  // closed menu.
+  double _maxWidth;
+
+  FlatButton _getItem(VoidCallback onPressed, String label) {
+    if (onPressed == null) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: Should this be an assert instead?

(On the call side you're always guarding to never pass in null)

File: packages/flutter/lib/src/material/text_selection.dart [hunk 18]
```diff
@@ -20,64 +23,417 @@ const double _kHandleSize = 22.0;
...
+
+      if (width > constraints.maxWidth && _lastIndexThatFits == -1) {
+        _lastIndexThatFits = i - 1;
+      }
+    });
+
+    // If the last child overflows, but only because of the width of the
+    // overflow button, then just show it and hide the overflow button.
+    final RenderBox navButton = firstChild;
+    if (_lastIndexThatFits != -1 && _lastIndexThatFits == childCount - 2
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: nit: maybe reformat this to show one condition per line?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 19]
```diff
@@ -20,64 +23,417 @@ const double _kHandleSize = 22.0;
...
+    visitChildren((RenderObject renderObjectChild) {
+      i++;
+
+      // The navigation button is placed after iterating all children.
+      if (renderObjectChild == firstChild) {
+        return;
+      }
+
+      // No need to place children that won't be painted.
+      if (!_shouldPaintChild(renderObjectChild, i)) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: nit: I would merge this if with the previous one.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 20]
```diff
@@ -20,64 +23,417 @@ const double _kHandleSize = 22.0;
...
+    // When there is overflow, paint if the child is in the part of the menu
+    // that is currently open. Overflowing children are painted when the
+    // overflow menu is open, and the children that fit are painted when the
+    // overflow menu is closed.
+    return (index > _lastIndexThatFits) == overflowOpen;
+  }
+
+  @override
+  void performLayout() {
+    _lastIndexThatFits = -1;
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection.dart]: Note: What happens if overflowOpen is true but it doesn't actually overflow? Make sure that case is handled.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 21]
```diff
@@ -20,64 +23,417 @@ const double _kHandleSize = 22.0;
...
+        ),
+      ),
+    );
+
+    // When the menu shrinks as the overflow is opened, then it occupies the
+    // same size as it did with overflow closed and aligns itself to the right
+    // of its original size.
+    return _maxWidth == null ? child : SizedBox(
+      width: _maxWidth,
+      child: Align(
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection.dart]: Note: What if the overflow menu is wider than the regular menu? Try it.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 9 above)
Comment (chunhtai) [reply packages/flutter/lib/src/material/text_selection.dart]: @justinmc

File: packages/flutter/lib/src/material/text_selection.dart [hunk 22]
```diff
@@ -20,64 +23,417 @@ const double _kHandleSize = 22.0;
...
 
-    return Material(
-      elevation: 1.0,
-      child: Container(
-        height: _kToolbarHeight,
-        child: Row(mainAxisSize: MainAxisSize.min, children: items),
+    final Container child = Container(
+      key: _key,
+      height: _overflowOpen ? null : _kToolbarHeight,
+      child: Material(
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection.dart]: Note: Consider drawing this inside of _TextSelectionToolbarItems. Then you can do the calculation you're doing with `_maxWidth` inside of _TextSelectionToolbarItems.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 17 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Yes, good call.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 18 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: :+1: Looks a lot better that way.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 9 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Here it is on native Android:

selection_menu_overflow_native_android_2

**Comment by chunhtai** [comment]
in reply to https://github.com/flutter/flutter/pull/49391#discussion_r385874977

I can only think of using animation to achieve this effect. however, this might be tricky, you will have to provide both pure container element and animation element to renderObject. If the rendering layout with overflow, you paints the pure container element. otherwise paints the animation element. There might be way to simply the structure, but i this is what i can think of from a quick peek.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 23]
```diff
@@ -20,64 +23,418 @@ const double _kHandleSize = 22.0;
...
-    return Material(
-      elevation: 1.0,
-      child: Container(
-        height: _kToolbarHeight,
-        child: Row(mainAxisSize: MainAxisSize.min, children: items),
+    final Align child = Align(
+      alignment: Alignment.topRight,
+      heightFactor: 1.0,
+      widthFactor: 1.0,
+      child: AnimatedSize(
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: What are the incoming constraints for AnimatedSize? My guess is that they end up to be tight giving AnimatedSize no choice in what size it can be?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 24]
```diff
@@ -20,64 +23,418 @@ const double _kHandleSize = 22.0;
...
+       assert(isAbove != null),
+       _isAbove = isAbove,
+       _overflowOpen = overflowOpen,
+       super();
+
+  // This is static so that it can be preserved between instances. The
+  // IntrinsicWidth widget is added and removed above this in the tree, causing
+  // it to be recreated, but _intrinsicWidth is needed immediately when the
+  // overflow menu is open.
+  static double _intrinsicWidth;
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: Caching this seems dangerous. Can we not just calculate this on-demand when getIntrinsicsWidth is called (by calling getInstrinsicsWidth on them)?

Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: The problem is that at the time I'm asked for intrinsic width, I don't yet have `constraints`, so I can't know where the menu will overflow.  I can calculate the true intrinsic width of the menu without any constraints, but that doesn't help our IntrinsicWidth widget hack.

Is there any other way I can do it? A hack that comes to mind is to use the width of the screen instead of constraints.maxWidth...

File: packages/flutter/lib/src/material/text_selection.dart (hunk 23 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Unfortunately I couldn't check the constraints directly by using a LayoutBuilder because it wasn't letting me put a LayoutBuilder inside of InstrincWidth...

But I'm pretty sure that the constraints are set to tight by the IntrinsicWidth widget.  If I remove IntrinsicWidth, the animation works.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 21 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Handled in https://github.com/flutter/flutter/pull/49391/commits/42f976714798555c8e95e8708a499b6a1fd229fe by allowing the overflow menu to be its full width and not aligning the right edges.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 22 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Not needed if the approach in https://github.com/flutter/flutter/pull/49391/commits/42f976714798555c8e95e8708a499b6a1fd229fe is ok.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 23 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: This and the comment in this review below should be irrelevant with the new approach in https://github.com/flutter/flutter/pull/49391/commits/42f976714798555c8e95e8708a499b6a1fd229fe.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 25]
```diff
@@ -20,64 +23,528 @@ const double _kHandleSize = 22.0;
...
+  _TextSelectionToolbarState createState() => _TextSelectionToolbarState();
+}
+
+class _TextSelectionToolbarState extends State<_TextSelectionToolbar> with TickerProviderStateMixin {
+  // Whether or not the overflow menu is open. When it is closed, the menu
+  // items that don't overflow are shown. When it is open, only the overflowing
+  // menu items are shown.
+  bool _overflowOpen = false;
+
+  // Whether or not the currently enabled menu items have changed since the
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Currently, the menu items are all hard coded, and they simply are shown if a handler is given and hidden otherwise.  _menuChanged is true when the existence of a handler changes and an item is hidden or shown.  I'll clarify in the docs!

File: packages/flutter/lib/src/material/text_selection.dart [hunk 26]
```diff
@@ -20,64 +23,528 @@ const double _kHandleSize = 22.0;
...
+              },
+              tooltip: _overflowOpen ? 'Back' : 'More',
+            ),
+          ),
+          ...items,
+        ],
       ),
     );
+    // Size animation should only happen when overflowOpen is being toggled and
+    // not when the enabled menu items are changing.
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Say the menu shows "Paste" and "Select All", and the user taps "Select All".  The menu will then change to show "Cut", "Copy", and "Paste" and be a bit wider.  In native Android, the menu resizing doesn't animate in this case, it only animates when the overflow menu is opened or closed.  I'll update this comment too!

File: packages/flutter/lib/src/material/text_selection.dart [hunk 27]
```diff
@@ -20,64 +23,528 @@ const double _kHandleSize = 22.0;
...
+  _TextSelectionToolbarContainerRenderBox createRenderObject(BuildContext context) {
+    return _TextSelectionToolbarContainerRenderBox(overflowOpen: overflowOpen);
+  }
+
+  @override
+  void updateRenderObject(BuildContext context, _TextSelectionToolbarContainerRenderBox renderObject) {
+    renderObject
+      ..overflowOpen = overflowOpen;
+
+    if (menuChanged) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: How can I get access to the renderObject from there?

I also just tried a few different ways of getting rid of menuChanged but I couldn't get it to work in all cases without it.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 28]
```diff
@@ -20,64 +23,528 @@ const double _kHandleSize = 22.0;
...
+    if (value == overflowOpen) {
+      return;
+    }
+    _overflowOpen = value;
+    markNeedsLayout();
+  }
+
+  // If the contents of the menu changed, reset the tracked width.
+  void onMenuChanged() {
+    _closedWidth = null;
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Yeah good call.  I've changed it so that when the menu items change, the overflow menu is closed.  That should avoid any problems like this.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 27 above)
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/material/text_selection.dart]: context.findRenderObject() should find the first descendant which will be this renderobject?

However, this seems weird to me that widget access the renderobject one level down.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 29]
```diff
@@ -20,64 +23,528 @@ const double _kHandleSize = 22.0;
...
+    markNeedsLayout();
+  }
+
+  @override
+  void performLayout() {
+    child.layout(constraints.loosen(), parentUsesSize: true);
+
+    if (!overflowOpen && _closedWidth == null) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: It matters because the size is animated.  In the frame that `overflowOpen` is first toggled to false, the menu is still at the "open" size, and the animation begins.  If I were to immediately set the size to the full open size, then its alignment would jump to the left, and then it would animate.

`_closedWidth` doesn't get reset to null after open/close, because the "closed" size of the menu doesn't change.  It only changes when the menu items change, and at that time `_closedWidth` is reset to null.

[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Adding a comment about this.

[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: I also added a condition to handle the case where the menu is first built with the overflow menu open. In that case it will just render at the size of the open menu.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 30]
```diff
@@ -20,64 +23,528 @@ const double _kHandleSize = 22.0;
...
+  // right edge.
+  double _closedWidth;
+
+  bool _overflowOpen;
+  bool get overflowOpen => _overflowOpen;
+  set overflowOpen(bool value) {
+    if (value == overflowOpen) {
+      return;
+    }
+    _overflowOpen = value;
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: No, see my [comment above](https://github.com/flutter/flutter/pull/49391#discussion_r387200572) about animations.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 20 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Handled by resetting overflowOpen to false when the menu changes.

**Comment by justinmc** [comment]
@goderbauer @chunhtai Ready for re-review, thanks!

I used `applyPaintTransform` to get the tests to work again.  Before, `tester.tap` was not tapping at the right location, and now it is.  However, I still don't fully understand how and when that method should be used, so please let me know if something looks off.  I tried implementing it on the child RenderBox as well (`_TextSelectionToolbarItems`), but the test always received weird values for the location of the buttons in that case.  I tried many different combinations of transforming and not transforming and peeked at the values the hit testers were getting, but couldn't convince myself that I understood the way it's intended to be used.

I'll take a look at updating the goldens soon.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 31]
```diff
@@ -20,64 +23,582 @@ const double _kHandleSize = 22.0;
...
+
+class _TextSelectionToolbarState extends State<_TextSelectionToolbar> with TickerProviderStateMixin {
+  // Whether or not the overflow menu is open. When it is closed, the menu
+  // items that don't overflow are shown. When it is open, only the overflowing
+  // menu items are shown.
+  bool _overflowOpen = false;
+
+  // True iff which menu items are shown has changed since the widget last
+  // updated.
+  bool _menuChanged = false;
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: The `_menuChanged` business is strange because of edge-triggered vs. level-triggered. I wonder if we could do the following:
* remove this member.
* add a Key member variable, initialize it with a UniqueKey
* in didUpdateWidget, when we detect that the menu has changed, assign a new UniqueKey to this variable (and continue to close the menu).
* Use this key as a key for _TextSelectionToolbarContainer.

This way, when the menu changes substantially, we just build a new one from scratch.

Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Done in https://github.com/flutter/flutter/pull/49391/commits/35774643eee558f108e619f5bcdf4304d65b494b, however, I still needed the `_menuChanged` variable within `_TextSelectionToolbarState` in order to include/exclude AnimatedSize.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 32]
```diff
@@ -20,64 +23,582 @@ const double _kHandleSize = 22.0;
...
+  bool get overflowOpen => _overflowOpen;
+  set overflowOpen(bool value) {
+    if (value == overflowOpen) {
+      return;
+    }
+    _overflowOpen = value;
+    markNeedsLayout();
+  }
+
+  // Lay out all children, regardless of whether or not they will be painted or
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Yes, good catch!

File: packages/flutter/lib/src/material/text_selection.dart (hunk 31 above)
Comment (goderbauer) [reply packages/flutter/lib/src/material/text_selection.dart]: Interesting. I would have expected that due to the key change a new RenderAnimatedSize is instantiated and a new RenderAnimatedSize shouldn't be animating anything when it is first added. But that's not the case?

**Comment by justinmc** [comment]
[Design doc](https://docs.google.com/document/d/1qSEvbgi3m-OvB_dUKch8LHOk-iyPFeLgCsXbK0bI2DA/edit)

Breaking change email:

> Hello Flutter,
> 
> If your app doesn't involve selectable or editable text, you can stop reading now.
> 
> I'm modernizing a few things about the text selection menu, and if you use any visual diff tests with the text selection menu open, you may encounter failures.  See the full design doc.
> 
> Summary of Changes
> The text selection menu has a positioning bug when selecting multiline text.  The position will be changed to match native.
> 
> The visual appearance of Android's menu will be updated slightly to match the latest versions of Android.
> 
> In the case that the menu overflows, such as on narrow devices or locales with long menu items, the menu will place overflowing items in an overflow menu in line with the native platform on iOS and Android.
> 
> Migration Guide
> No code changes are needed.  If you have affected visual diff tests, update the tests to recognize the new visuals.
> 
> 
> Thanks!  Please see the design doc for more information and to leave feedback.
> 
> Justin (@justinmc)

File: packages/flutter/lib/src/material/text_selection.dart [hunk 33]
```diff
@@ -20,64 +23,559 @@ const double _kHandleSize = 22.0;
...
+
+  @override
+  void didUpdateWidget(_TextSelectionToolbar oldWidget) {
+    if (((widget.handleCut == null) != (oldWidget.handleCut == null))
+      || ((widget.handleCopy == null) != (oldWidget.handleCopy == null))
+      || ((widget.handlePaste == null) != (oldWidget.handlePaste == null))
+      || ((widget.handleSelectAll == null) != (oldWidget.handleSelectAll == null))) {
+      // Change _TextSelectionToolbarContainer's key when the menu changes in
+      // order to cause it to rebuild. This lets it recalculate its
+      // saved width for the new set of children.
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: ... and also avoids animating any changes in size (or something like that)?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 34]
```diff
@@ -20,64 +23,559 @@ const double _kHandleSize = 22.0;
...
+      _containerKey = UniqueKey();
+      // If the menu items change, make sure the overflow menu is closed. This
+      // prevents an empty overflow menu and an incorrect saved width.
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: "the incorrect saved width" part is now handled by the key above. Maybe remove that here?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 35]
```diff
@@ -20,64 +23,559 @@ const double _kHandleSize = 22.0;
...
+                  // TODO(justinmc): This should be an AnimatedIcon, but
+                  // AnimatedIcons doesn't yet support arrow_back to more_vert.
+                  // https://github.com/flutter/flutter/issues/51209
+                  icon: Icon(_overflowOpen ? Icons.arrow_back : Icons.more_vert),
+                  onPressed: () {
+                    setState(() {
+                      _overflowOpen = !_overflowOpen;
+                    });
+                  },
+                  tooltip: _overflowOpen ? 'Back' : 'More',
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: These strings need to be internationalized.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 36]
```diff
@@ -20,64 +23,559 @@ const double _kHandleSize = 22.0;
...
+    markNeedsLayout();
+  }
+
+  @override
+  void performLayout() {
+    child.layout(constraints.loosen(), parentUsesSize: true);
+
+    // Save the width when the menu is closed. If the menu changes, this width
+    // is invalid, so it's important that this RenderBox be recreated in that
+    // case.
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: Maybe mention that we achieve this by providing a new key to the corresponding widget.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 37]
```diff
@@ -20,64 +23,559 @@ const double _kHandleSize = 22.0;
...
+      ..isAbove = isAbove
+      ..overflowOpen = overflowOpen;
+  }
+
+  @override
+  _TextSelectionToolbarItemsElement createElement() => _TextSelectionToolbarItemsElement(this);
+}
+
+class _ToolbarParentData extends ContainerBoxParentData<RenderBox> {
+  // Whether or not this child is painted.
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: nit: use `///` instead of `//` (this is a doc-quality comment).

File: packages/flutter/lib/src/material/text_selection.dart [hunk 38]
```diff
@@ -20,64 +23,559 @@ const double _kHandleSize = 22.0;
...
+    return (child.renderObject.parentData as _ToolbarParentData).shouldPaint;
+  }
+
+  @override
+  void debugVisitOnstageChildren(ElementVisitor visitor) {
+    children.where(_shouldPaint).forEach(visitor);
+  }
+}
+
+class _TextSelectionToolbarItemsRenderBox extends RenderBox with ContainerRenderObjectMixin<RenderBox, _ToolbarParentData>, RenderBoxContainerDefaultsMixin<RenderBox, _ToolbarParentData> {
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: Maybe I missed it, but do you actually use anything from RenderBoxContainerDefaultsMixin?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 39]
```diff
@@ -20,64 +23,559 @@ const double _kHandleSize = 22.0;
...
+        nextSize = Size(
+          nextSize.width,
+          isAbove ? nextSize.height + navButton.size.height : nextSize.height,
+        );
+      } else {
+        navButtonParentData.offset = Offset(fitWidth, 0.0);
+        nextSize = Size(nextSize.width + navButton.size.width, nextSize.height);
+      }
+    } else {
+      navButtonParentData.shouldPaint = false;
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: Didn't you already do this above in line 435? Maybe change line 435 to just be:

```
if (renderObjectChild == firstChild) {
  // Deal with the navigation button later.
  return;
}

... and then figure out what to do with the nav button right here.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 40]
```diff
@@ -20,64 +23,559 @@ const double _kHandleSize = 22.0;
...
+    double overflowHeight = overflowOpen && !isAbove ? navButton.size.height : 0.0;
+    visitChildren((RenderObject renderObjectChild) {
+      i++;
+
+      final RenderBox child = renderObjectChild as RenderBox;
+      final _ToolbarParentData childParentData = child.parentData as _ToolbarParentData;
+
+      // The navigation button is placed after iterating all children, and there
+      // is no need to place children that won't be painted.
+      if (renderObjectChild == firstChild
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: compare this to navButton instead of firstChild to make the code slightly more readable?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 41]
```diff
@@ -143,42 +636,52 @@ class _MaterialTextSelectionControls extends TextSelectionControls {
...
+            anchor,
+            _kToolbarScreenPadding + paddingTop,
+            fitsAbove,
+          ),
+          child: _TextSelectionToolbar(
+            handleCut: canCut(delegate) ? () => handleCut(delegate) : null,
+            handleCopy: canCopy(delegate) ? () => handleCopy(delegate) : null,
+            handlePaste: canPaste(delegate) ? () => handlePaste(delegate) : null,
+            handleSelectAll: canSelectAll(delegate) ? () => handleSelectAll(delegate) : null,
+            isAbove: fitsAbove,
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/text_selection.dart]: How is fitsAbove updated when the textfield is in a scrollable and I scroll while the toolbar is shown? Is that even possible? What does native do?

**Review by goderbauer — APPROVED** [review]
LGTM after i18n issue is resolved.

**Comment by goderbauer** [comment]
Looks like cirrus is unhappy, though.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 42]
```diff
@@ -20,64 +23,559 @@ const double _kHandleSize = 22.0;
...
+
+  // The key for _TextSelectionToolbarContainer.
+  UniqueKey _containerKey = UniqueKey();
+
+  FlatButton _getItem(VoidCallback onPressed, String label) {
+    assert(onPressed != null);
+    return FlatButton(
+      child: Text(label),
+      onPressed: () {
+        setState(() {
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/text_selection.dart]: Is there a use case that we want to close the overflow when we select a button? If i remember correctly, the callback will remove the overlay entry anyway?

File: packages/flutter/lib/src/material/text_selection.dart (hunk 38 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Nope not anymore it looks like, good catch!

File: packages/flutter/lib/src/material/text_selection.dart (hunk 39 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Will do.  I agree this way is misleading now that I look at it.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 28.
Please triage them at https://flutter-gold.skia.org/search?issue=49391.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 28.
Please triage them at https://flutter-gold.skia.org/search?issue=49391.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 28.
Please triage them at https://flutter-gold.skia.org/search?issue=49391.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 41 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: I noticed a couple of problems while looking into this.  I'm going to create two new issues and defer them until after this PR, if that's alright with you.

  1. ✅ Scrolling a multiline text field properly updates fitsAbove immediately.  The position of the menu changes as well as the orientation of the back button.
  1. ❌ Scrolling the entire TextField as an item in a ListView does not update fitsAbove.
  1. ❌ On native Android, the menu fades out during scrolling and back in afterwards, but Flutter doesn't do this.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 42 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: You're right, the overlay entry appears to be closed in all current cases.  Also maybe in the future when we've got more/custom selection menu buttons, users will want to handle that themselves.  I'll remove this setState.
