### PR TITLE
Reject requests for hot reload if a hot reload is already in progress.

### LINKED ISSUE #14184: Crash if request for hot reload is sent while a reload is already in progress
If you sent a reload request while a reload is in progress, it crashes. I'll see if I can handle this in the IDE for now, though it should probably be handled better in flutter.

(Copied from https://github.com/Dart-Code/Dart-Code/issues/492)

```text
Error 108 received from application: Isolate is reloading
Unhandled exception:
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("type")
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      HotRunner.validateReloadReport (package:flutter_tools/src/run_hot.dart:407)
#3      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:528)
#4      _rootRunUnary (dart:async/zone.dart:1128)
#5      _CustomZone.runUnary (dart:async/zone.dart:1012)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#9      _Future._completeWithValue (dart:async/future_impl.dart:478)
#10     Future.wait.<anonymous closure> (dart:async/future.dart:392)
#11     _rootRunUnary (dart:async/zone.dart:1128)
#12     _CustomZone.runUnary (dart:async/zone.dart:1012)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#16     _Future._complete (dart:async/future_impl.dart:468)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
#19     Isolate.reloadSources (package:flutter_tools/src/vmservice.dart:1047)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:30)
#21     _rootRunUnary (dart:async/zone.dart:1128)
#22     _CustomZone.runUnary (dart:async/zone.dart:1012)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#24     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#25     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#26     _Future._complete (dart:async/future_impl.dart:468)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
#29     VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:748)
#30     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:37)
#31     _rootRunBinary (dart:async/zone.dart:1140)
#32     _CustomZone.runBinary (dart:async/zone.dart:1023)
#33     _FutureListener.handleError (dart:async/future_impl.dart:142)
#34     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:648)
#35     _Future._propagateToListeners (dart:async/future_impl.dart:669)
#36     _Future._completeError (dart:async/future_impl.dart:486)
#37     _Future.timeout.<anonymous closure> (dart:async/future_impl.dart:739)
#38     _rootRunBinary (dart:async/zone.dart:1140)
#39     _CustomZone.runBinary (dart:async/zone.dart:1023)
#40     _FutureListener.handleError (dart:async/future_impl.dart:142)
#41     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:648)
#42     _Future._propagateToListeners (dart:async/future_impl.dart:669)
#43     _Future._completeError (dart:async/future_impl.dart:486)
#44     _SyncCompleter._completeError (dart:async/future_impl.dart:55)
#45     _Completer.completeError (dart:async/future_impl.dart:27)
#46     Future.any.<anonymous closure> (dart:async/future.dart:454)
#47     _rootRunBinary (dart:async/zone.dart:1140)
#48     _CustomZone.runBinary (dart:async/zone.dart:1023)
#49     _FutureListener.handleError (dart:async/future_impl.dart:142)
#50     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:648)
#51     _Future._propagateToListeners (dart:async/future_impl.dart:669)
#52     _Future._completeError (dart:async/future_impl.dart:486)
#53     _SyncCompleter._completeError (dart:async/future_impl.dart:55)
#54     _Completer.completeError (dart:async/future_impl.dart:27)
#55     Client._handleSingleResponse (package:json_rpc_2/src/client.dart:193)
#56     Client._handleResponse (package:json_rpc_2/src/client.dart:181)
#57     _rootRunUnary (dart:async/zone.dart:1128)
#58     _CustomZone.runUnary (dart:async/zone.dart:1012)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#62     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#63     _StreamController._add (dart:async/stream_controller.dart:667)
#64     _StreamController.add (dart:async/stream_controller.dart:613)
#65     Peer.listen.<anonymous closure> (package:json_rpc_2/src/peer.dart:91)
#66     _rootRunUnary (dart:async/zone.dart:1128)
#67     _CustomZone.runUnary (dart:async/zone.dart:1012)
#68     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#69     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#70     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#71     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#72     _MapStream._handleData (dart:async/stream_pipe.dart:232)
#73     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#74     _rootRunUnary (dart:async/zone.dart:1128)
#75     _CustomZone.runUnary (dart:async/zone.dart:1012)
#76     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#77     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#78     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#79     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#80     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98)
#81     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#82     _rootRunUnary (dart:async/zone.dart:1128)
#83     _CustomZone.runUnary (dart:async/zone.dart:1012)
#84     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#85     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#86     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#87     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#88     _StreamController._add (dart:async/stream_controller.dart:667)
#89     _rootRunUnary (dart:async/zone.dart:1128)
#90     _CustomZone.runUnary (dart:async/zone.dart:1012)
#91     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#92     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#93     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#94     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#95     _StreamController._add (dart:async/stream_controller.dart:667)
#96     _StreamController.add (dart:async/stream_controller.dart:613)
#97     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:io/websocket_impl.dart:1116)
#98     _rootRunUnary (dart:async/zone.dart:1128)
#99     _CustomZone.runUnary (dart:async/zone.dart:1012)
#100    _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#101    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#102    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#103    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#104    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#105    _WebSocketProtocolTransformer._messageFrameEnd (dart:io/websocket_impl.dart:337)
#106    _WebSocketProtocolTransformer.add (dart:io/websocket_impl.dart:232)
#107    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#108    _rootRunUnary (dart:async/zone.dart:1128)
#109    _CustomZone.runUnary (dart:async/zone.dart:1012)
#110    _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#111    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#112    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#113    _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#114    _StreamController._add (dart:async/stream_controller.dart:667)
#115    _StreamController.add (dart:async/stream_controller.dart:613)
#116    _Socket._onData (dart:io-patch/socket_patch.dart:1643)
#117    _rootRunUnary (dart:async/zone.dart:1132)
#118    _CustomZone.runUnary (dart:async/zone.dart:1012)
#119    _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)
#120    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#121    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#122    _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#123    _StreamController._add (dart:async/stream_controller.dart:667)
#124    _StreamController.add (dart:async/stream_controller.dart:613)
#125    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
#126    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#127    _microtaskLoop (dart:async/schedule_microtask.dart:41)
#128    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#129    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#130    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
Exited (255)
```

### PR DESCRIPTION
**Pull request by DanTup**
Fixes #14184 

I created a copy of the `command_tests.dart` devicelab test and changed it to talk `--machine` (including extracting the debug port from `app.debugPort` since there's no banner like `flutter run --hot` which is what the other test used). Without the change in `daemon.dart` this test will fail because of a crash. With the code change the test passes (the second reload is rejected).

I'm somewhat nervous about this change because breaking hot reload would be a big deal, so please review carefully. Is the change in `daemon.dart` reliable enough that it can't end up with a hungover future that stops future hot reloads working?

Also; should I be adding run_machine_concurrent_hot_reload to the manifest file? The doc says "The `manifest.yaml` file describes a subset of tests we run in the CI" but I'm not certain what that subset is and whether this test should be part of it.

As always, nitpick away; this is a learning exercise!

cc @devoncarew @yjbanov

### CODE REVIEW

File: dev/devicelab/bin/tasks/run_machine_concurrent_hot_reload.dart [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+          .transform(const LineSplitter())
+          .listen((String line) {
+            print('run:stdout: $line');
+            stdout.add(line);
+            final dynamic json = parseFlutterResponse(line);
+            if (json != null && json['event'] == 'app.debugPort') {
+              vmServicePort = Uri.parse(json['params']['wsUri']).port;
+              print('service protocol connection available at port $vmServicePort');
+            }
+            else if (json != null && json['event'] == 'app.started') {
```
Comment (devoncarew) [inline dev/devicelab/bin/tasks/run_machine_concurrent_hot_reload.dart]: nit: else on the previous line

Since this is a new file, you may run it through dartfmt once in order to level set the formatting (you probably don't want to do that to existing repo files however)

File: dev/devicelab/bin/tasks/run_machine_concurrent_hot_reload.dart [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+    await inDirectory(appDir, () async {
+      final Completer<Null> ready = new Completer<Null>();
+      bool ok;
+      print('run: starting...');
+      final Process run = await startProcess(
+        path.join(flutterDirectory.path, 'bin', 'flutter'),
+        <String>['run', '--machine', '--verbose', '-d', device.deviceId, 'lib/commands.dart'],
+      );
+      final StreamController<String> stdout = new StreamController<String>.broadcast();
+      run.stdout
```
Comment (devoncarew) [inline dev/devicelab/bin/tasks/run_machine_concurrent_hot_reload.dart]: We're doing this twice in this file (and lots of places in other files); perhaps in-line a small `Stream<List<int>>` ==> `Stream<String` function?

```
Stream<String> transformToLines(Stream<List<int>> byteStream) {
  return byteStream.transform(UTF8.decoder).transform(const LineSplitter());
}
```

File: packages/flutter_tools/lib/src/commands/daemon.dart [hunk 3]
```diff
@@ -447,6 +447,7 @@ class AppDomain extends Domain {
   bool isRestartSupported(bool enableHotReload, Device device) =>
       enableHotReload && device.supportsHotMode;
 
+  Future<Null> inProgressHotReload;
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/commands/daemon.dart]: nit: newline after

Perhaps make this private? `_inProgressReload`?

**Comment by DanTup** [comment]
Oh dear, looks like I didn't fix my lints! :( Will sort these first in the morning.

File: packages/flutter_tools/lib/src/commands/daemon.dart [hunk 4]
```diff
@@ -456,9 +457,15 @@ class AppDomain extends Domain {
     if (app == null)
       throw "app '$appId' not found";
 
-    return app._runInZone(this, () {
+    if (!fullRestart && inProgressHotReload != null)
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/commands/daemon.dart]: We probably want to disallow any concurrent reload/restart? So, `if (_inProgressReload != null) ...`

File: packages/flutter_tools/lib/src/commands/daemon.dart [hunk 5]
```diff
@@ -456,9 +457,15 @@ class AppDomain extends Domain {
...
+      throw 'hot restart already in progress';
+
+    final Future<OperationResult> action = app._runInZone(this, () {
       return app.restart(fullRestart: fullRestart, pauseAfterRestart: pauseAfterRestart);
     });
+    if (!fullRestart)
+      inProgressHotReload = action.then((_) => inProgressHotReload = null);
+    return action;
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/commands/daemon.dart]: It may be possible to simplify this all to:

```
_inProgressReload = app._runInZone(this, () {
  return app.restart(fullRestart: fullRestart, pauseAfterRestart: pauseAfterRestart);
});

return _inProgressReload.whenComplete(() {
  _inProgressReload = nu'l;
});
```

In which case we'd want to type `_inProgressReload` as `Future<OperationResult>`. I think the above will have the nice benefit that errors in the reload operation future will be passed back to the caller (and back over the wire).

**Review by devoncarew — COMMENTED** [review]
Very nice!

> Also; should I be adding run_machine_concurrent_hot_reload to the manifest file?

Yes, I think so; that way this test will run as part of the devicelab tests.

**Comment by DanTup** [comment]
@devoncarew 

> Yes, I think so; that way this test will run as part of the devicelab tests.

I've added this in b406480, I'm not sure if these values are set optimally:

```yaml
    stage: devicelab
    required_agent_capabilities: ["mac/android"]
```

I've been building/testing on windows/android though the test I originally copied was set to mac/android. In theory the test should work fine on all platforms, but I don't know if there's a trade-off between running it in all places versus how long the test run will take.

File: dev/devicelab/bin/tasks/run_machine_concurrent_hot_reload.dart (hunk 1 above)
Comment (DanTup) [reply dev/devicelab/bin/tasks/run_machine_concurrent_hot_reload.dart]: Fixed in 55b68ef (note: I'm not sure if linking to changesets in response to comments is useful or spammy, it's just something I did at previous company, lmk if not useful!)

File: dev/devicelab/bin/tasks/run_machine_concurrent_hot_reload.dart (hunk 2 above)
Comment (DanTup) [reply dev/devicelab/bin/tasks/run_machine_concurrent_hot_reload.dart]: In 859a279 I made a function at the top, though not sure if you want more globally?

This is one of those places I wish Dart had extension methods... `stream.transformToLines()` versus `transformToLines(stream)`!

File: packages/flutter_tools/lib/src/commands/daemon.dart (hunk 3 above)
Comment (DanTup) [reply packages/flutter_tools/lib/src/commands/daemon.dart]: Done in ae25a98. C# is private by default, suspect I will keep making this mistake for a while!

File: packages/flutter_tools/lib/src/commands/daemon.dart (hunk 4 above)
Comment (DanTup) [reply packages/flutter_tools/lib/src/commands/daemon.dart]: Changed in b01335d. I wasn't totally sure if we wanted to affect full restarts too, but I guess it could suffer from similar issues so seems safest (as long as we don't ever go leaving this future around when it should've been cleared - I think hot reload has a timeout so hopefully this is all handled nicely).

File: packages/flutter_tools/lib/src/commands/daemon.dart (hunk 5 above)
Comment (DanTup) [reply packages/flutter_tools/lib/src/commands/daemon.dart]: Oops, good catch - I think my original code would've failed to set the in-progress future back to null if the `runInZone` future errorred. 2a58cd8 changes to your code (similar to the earlier change, this removes the checking for only hot reloads, so the future will be set for full restarts too, but I think you intended this).

**Review by devoncarew — APPROVED** [review]
Looks good! Let me know if you can merge; if not, I can do for now.

I'd watch the devicelab build page after this lands to make sure everything looks good.

**Comment by DanTup** [comment]
@devoncarew I can't merge; I don't have any access here (which might not be a bad thing, at least for now! 😁). I'll keep an eye on the devicelab tests once merged 👍

**Comment by DanTup** [comment]
> I'd watch the devicelab build page after this lands to make sure everything looks good.

Looks like everything (eventually) went green, thanks!

**Comment by yjbanov** [comment]
Just realized that I forgot to click the "Send" button 🤦‍♂️  I was going to say that when we add a brand new devicelab test we begin by marking it as `flaky: true` until we're sure it's consistently green. Of course, this is @DanTup's code, so the chances of build breakage was extremely low anyway 😉

**Comment by DanTup** [comment]
> Of course, this is @DanTup's code, so the chances of build breakage was extremely low anyway 😉

Hmm, unsure if misplaced faith or sarcasm! 😛 

But I can see on the [build page](https://flutter-dashboard.appspot.com/build.html) that two runs are red and two are yellow. I'm not entirely sure what's with the yellow ones - is is being run multiple times to determine it's flaky?

I can't currently access the logs (I don't have access to my @google account yet, and my personal Google account gives `Authentication/authorization error: da***@tupp***.com is not authorized to access the dashboard` when clicking the log). Can someone give me details of what was up and advise whether I should mark it flaky?

**Comment by DanTup** [comment]
@mraleph I think everyone above may be on US time so I wonder if you have any opinions on this - my devicelab test `run_machine_concurrent_hot_reload` looks flaky. I can't currently access the logs (I don't have access to my @google account yet); I don't know the impact of this. Should I mark it as flaky in the manifest? Will that stop the build being considered broken?

**Comment by DanTup** [comment]
@devoncarew @yjbanov 

I got some of these logs from @mraleph; I guess something is trying to write to stdout as it's terminating (as a result of `app.stop`); not sure how best to handle though? The code at the end is kinda similar to the command_test one I copied - it sends `q` then awaits the exit code, whereas I send `app.stop` then await it.

So, two questions:

1. Should I mark this flaky in the manifest?
2. How can I make it unflaky?

<details>
<summary>NoSuchMethodError: The getter 'stdout' was called on null.</summary>
<code><pre>
run:stdout: [{"event":"app.stop","params":{"appId":"c7777f51-f0a5-4273-a726-fe57345fa5c6"}}]
run:stdout: [   +2 ms] "flutter run" took 57,615ms.
run:stderr: Unhandled exception:
run:stderr: NoSuchMethodError: The getter 'stdout' was called on null.
run:stderr: Receiver: null
run:stderr: Tried calling: stdout
run:stderr: #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
run:stderr: #1      stdout (package:flutter_tools/src/base/io.dart:176)
run:stderr: #2      StdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:92)
run:stderr: #3      StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:87)
run:stderr: #4      VerboseLogger._emit (package:flutter_tools/src/base/logger.dart:244)
run:stderr: #5      VerboseLogger.printTrace (package:flutter_tools/src/base/logger.dart:207)
run:stderr: #6      _AppRunLogger.printTrace (package:flutter_tools/src/commands/daemon.dart:859)
run:stderr: #7      printTrace (package:flutter_tools/src/globals.dart:50)
run:stderr: #8      ResidentRunner._serviceProtocolDone (package:flutter_tools/src/resident_runner.dart:652)
run:stderr: #9      _rootRunUnary (dart:async/zone.dart:1134)
run:stderr: #10     _CustomZone.runUnary (dart:async/zone.dart:1031)
run:stderr: #11     _FutureListener.handleValue (dart:async/future_impl.dart:129)
run:stderr: #12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
run:stderr: #13     _Future._propagateToListeners (dart:async/future_impl.dart:662)
run:stderr: #14     _Future._complete (dart:async/future_impl.dart:467)
run:stderr: #15     _SyncCompleter.complete (dart:async/future_impl.dart:51)
run:stderr: #16     ChannelManager.listen. (package:json_rpc_2/src/channel_manager.dart:58)
run:stderr: #17     _rootRun (dart:async/zone.dart:1122)
run:stderr: #18     _CustomZone.run (dart:async/zone.dart:1023)
run:stderr: #19     _CustomZone.runGuarded (dart:async/zone.dart:925)
run:stderr: #20     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:383)
run:stderr: #21     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:393)
run:stderr: #22     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277)
run:stderr: #23     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106)
run:stderr: #24     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172)
run:stderr: #25     _rootRun (dart:async/zone.dart:1122)
run:stderr: #26     _CustomZone.run (dart:async/zone.dart:1023)
run:stderr: #27     _CustomZone.runGuarded (dart:async/zone.dart:925)
run:stderr: #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:383)
run:stderr: #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:393)
run:stderr: #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277)
run:stderr: #31     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106)
run:stderr: #32     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172)
run:stderr: #33     _rootRun (dart:async/zone.dart:1122)
run:stderr: #34     _CustomZone.run (dart:async/zone.dart:1023)
run:stderr: #35     _CustomZone.runGuarded (dart:async/zone.dart:925)
run:stderr: #36     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:383)
run:stderr: #37     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:393)
run:stderr: #38     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277)
run:stderr: #39     _StreamController&&_SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:770)
run:stderr: #40     _StreamController._closeUnchecked (dart:async/stream_controller.dart:627)
run:stderr: #41     _StreamController.close (dart:async/stream_controller.dart:620)
run:stderr: #42     _rootRun (dart:async/zone.dart:1122)
run:stderr: #43     _CustomZone.run (dart:async/zone.dart:1023)
run:stderr: #44     _FutureListener.handleWhenComplete (dart:async/future_impl.dart:151)
run:stderr: #45     _Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:603)
run:stderr: #46     _Future._propagateToListeners (dart:async/future_impl.dart:659)
run:stderr: #47     _Future._completeWithValue (dart:async/future_impl.dart:477)
run:stderr: #48     _Future._asyncComplete. (dart:async/future_impl.dart:507)
run:stderr: #49     _rootRun (dart:async/zone.dart:1126)
run:stderr: #50     _CustomZone.run (dart:async/zone.dart:1023)
run:stderr: #51     _CustomZone.bindCallback. (dart:async/zone.dart:949)
run:stderr: #52     _microtaskLoop (dart:async/schedule_microtask.dart:41)
run:stderr: #53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
run:stderr: #54     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:112)
run:stderr: #55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
exitcode: 255
Task failed: Received unexpected exit code 255 from run process.
</pre></code>
</details>

**Comment by devoncarew** [comment]
Looks like it's trying to print `'Service protocol connection closed.'`. This call may be happening after we've torn down some of the app context / logging forwarding machinery. We may need to make this more robust in terms of writes after the app finishes, or choose to send the writes up to the higher-level handlers (would would probably just print to stdout).

But it looks like you're tickling an existing issue - this isn't new with your PR.

**Comment by devoncarew** [comment]
@tvolkert, @jcollins-g, is it expected that `context[Stdio]` can be null, or should that be updated to always return a value?

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/io.dart#L176

**Comment by tvolkert** [comment]
`context[Stdio]` shouldn't be null:

https://github.com/flutter/flutter/blob/0885866265a0d460d6a12075991809d5a3d33f86/packages/flutter_tools/lib/runner.dart#L68

**Comment by DanTup** [comment]
I've raised a specific issue to investigate/fix this flakiness (#14636) since this PR is already merged and it could easily get lost.

File: dev/devicelab/bin/tasks/run_machine_concurrent_hot_reload.dart [hunk 6]
```diff
@@ -0,0 +1,155 @@
...
+      final Process run = await startProcess(
+        path.join(flutterDirectory.path, 'bin', 'flutter'),
+        <String>[
+          'run',
+          '--machine',
+          '--verbose',
+          '-d',
+          device.deviceId,
+          'lib/commands.dart'
+        ],
```
Comment (aam) [inline dev/devicelab/bin/tasks/run_machine_concurrent_hot_reload.dart]: Is this supposed to support preview-dart-2 mode?

**Comment by aam** [comment]
> > Also; should I be adding run_machine_concurrent_hot_reload to the manifest file?

> Yes, I think so; that way this test will run as part of the devicelab tests.

Not sure if this changes are for preview-dart-2, but if they are the tests should run together with other preview-dart-2 hot reload tests.

**Comment by DanTup** [comment]
No, this one is just for a crash when concurrent reload requests are sent (it existed well before preview-dart-2).

I've since been told about reload issues with preview-dart-2 via the daemon though, so suspect there will be additional daemon tests on the way.
