### PR TITLE
Make `CupertinoTextField` at least as tall as its first line of placeholder

### LINKED ISSUE #133241: `CupertinoSearchTextField` height changes if `placeholder` contains Chinese Character.
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

If the `placeholder` contains Chinese, the widget's height will change when user inputs something. 

 An empty `CupertinoSearchTextField` with Chinese placeholder is higher than ones with English placeholder.

 While a `CupertinoSearchTextField` with user input Chinese characters is as same as default ones in height. 

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

/// Flutter code sample for [CupertinoSearchTextField].

void main() => runApp(const SearchTextFieldApp());

class SearchTextFieldApp extends StatelessWidget {
  const SearchTextFieldApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      home: SearchTextFieldExample(),
    );
  }
}

class SearchTextFieldExample extends StatefulWidget {
  const SearchTextFieldExample({super.key});

  @override
  State<SearchTextFieldExample> createState() => _SearchTextFieldExampleState();
}

class _SearchTextFieldExampleState extends State<SearchTextFieldExample> {

  @override
  Widget build(BuildContext context) {
    return const CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('CupertinoSearchTextField Sample'),
      ),
      child: Center(
        child: Padding(
          padding: EdgeInsets.all(16.0),
          child: CupertinoSearchTextField(
            placeholder: '搜索',
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/14086980/26765241-0e11-42b3-ade4-c278c442aa3e

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on Fedora Linux 38 (Workstation Edition)
    6.4.10-200.fc38.x86_64, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] Proxy Configuration
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/133241
and some CupertinoTextField cleanup.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 1]
```diff
@@ -1079,41 +1081,16 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with Restoratio
...
-      hasText: text.text.isNotEmpty,
-    );
-  }
-
-  bool _showClearButton(TextEditingValue text) {
-    return _shouldShowAttachment(
-      attachment: widget.clearButtonMode,
-      hasText: text.text.isNotEmpty,
-    );
+    return switch (attachment) {
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/cupertino/text_field.dart:1088]: TIL you can use switch statements in this way. Awesome!

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 2]
```diff
@@ -1134,6 +1111,31 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with Restoratio
     return _hasDecoration ? TextAlignVertical.center : TextAlignVertical.top;
   }
 
+  void _onClearButtonTapped() {
+    // Special handle onChanged for ClearButton
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/cupertino/text_field.dart:1115]: consider consolidating this comment into one sentence. maybe something like `Handler for ClearButton that calls onChanged when the clear button is tapped`.

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 3]
```diff
@@ -393,7 +393,7 @@ class CupertinoTextField extends StatefulWidget {
     this.onSubmitted,
     this.onTapOutside,
     this.inputFormatters,
-    this.enabled,
+    this.enabled = true,
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/cupertino/text_field.dart:396]: I wonder if we should just make this a private variable inside of `CupertinoTextFieldState` similar to how `TextFieldState` does it. I'm not too opinionated on this either way but it would keep the API consistent between both `TextField`s.

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 4]
```diff
@@ -1145,59 +1147,68 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with Restoratio
...
-          if (_showPrefixWidget(text!)) widget.prefix!,
+          if (prefixWidget != null) prefixWidget,
           // In the middle part, stack the placeholder on top of the main EditableText
           // if needed.
           Expanded(
             child: Stack(
+              // Ideally this should be baseline aligned. However that comes at
+              // the cost of the ability to compute the intrinsic dimensions of
+              // this widget.
+              // See also https://github.com/flutter/flutter/issues/13715
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/cupertino/text_field.dart:1202]: nit: consider adding a period at the end of this line.

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 5]
```diff
@@ -1145,59 +1147,68 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with Restoratio
     return ValueListenableBuilder<TextEditingValue>(
       valueListenable: _effectiveController,
       child: editableText,
-      builder: (BuildContext context, TextEditingValue? text, Widget? child) {
+      builder: (BuildContext context, TextEditingValue text, Widget? child) {
+        final bool hasText = text.text.isNotEmpty;
+        final String? placeholderText = widget.placeholder;
+        final Widget? placeholder = placeholderText == null
+          ? null
+          : Visibility(
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/cupertino/text_field.dart:1155]: Before this change the placeholder would not be built at all if there was text, but now it is built regardless but hidden when there is text. This is so the input field does not shrink when the user starts entering text because now the placeholder is still there just hidden.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/cupertino/text_field.dart:1155]: Just wondering if I am understanding this change correctly.

File: packages/flutter/lib/src/cupertino/text_field.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/text_field.dart:396]: `TextField.enabled?` is a `bool?` because it can default to `InputDecoration.enabled` I think. Here it doesn't have anything to default to other than the const `true` so I don't know if there's a good reason to keep this `bool?`. 

I don't think we need to store `enabled` in CupertinoTextFieldState since the configuration is completely determined by the widget itself (`CupertinoTextField.enabled`), unless I'm missing something?

File: packages/flutter/lib/src/cupertino/text_field.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/text_field.dart:1115]: I basically moved the code and the comment to an instance method. I'll update the comment.

File: packages/flutter/lib/src/cupertino/text_field.dart (hunk 5 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/text_field.dart:1155]: Yeah the placeholder will be kept in the widget tree to make sure the text field's height is always greater than or equal to the height of the first line of the placeholder, even when there's user text.

File: packages/flutter/lib/src/cupertino/text_field.dart (hunk 3 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/cupertino/text_field.dart:396]: I didn't consider the defaults in `InputDecoration`, that makes sense to me then.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Review by MitchellGoodwin — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/cupertino/text_field.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/text_field.dart:1088]: This is new in dart3. It's a switch expression (an expression evaluates to a value so you can directly return a switch expression), a bit different from a switch statement.

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 6]
```diff
@@ -1145,59 +1148,69 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with Restoratio
...
         return Row(children: <Widget>[
           // Insert a prefix at the front if the prefix visibility mode matches
           // the current text state.
-          if (_showPrefixWidget(text!)) widget.prefix!,
+          if (prefixWidget != null) prefixWidget,
           // In the middle part, stack the placeholder on top of the main EditableText
           // if needed.
           Expanded(
             child: Stack(
+              // Ideally this should be baseline aligned. However that comes at
```
Comment (moffatman) [inline packages/flutter/lib/src/cupertino/text_field.dart:1201]: Since this change, the placeholder is vertically centered on multi-line textfield instead of being on the first line, because alignment is set to center instead of default topLeft. Is this intended? Not sure how to read the comment above.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/text_field.dart:1201]: Yeah it should be baseline aligned with the input text instead of center aligned. I'll try to fix that.
