### PR TITLE
Expand DropdownButton width based on isExpanded flag

### LINKED ISSUE #13135: DropdownButton fills it's parent, but children don't expand
I read an existing issue (#4949) where the developer wanted the opposite behavior. He wanted the the underline to shrink; where as I would like the contents of the result to expand and force the dropdown arrow button to the right. 

I was actually able to make it work by changing the underlying code to use a `ConstrainedBox` instead of a `SizedBox`. However, that does not work for all scenarios due to various flex restrictions. 

image

I guess I'm asking if
1. this is possible today and there's something I'm missing; or
2. could an expand option be added to the DropdownButton and it would use something other than a `SizedBox` (`ConstrainedBox` is probably not right) in order to fill the remaining space?

**Update:** I used my brain a bit more and found a simpler solution to expand the `SizedBox`. Simply set it's width to `double.INFINITY` (taking some cues from `SizedBox.expand` constructor). I don't want to override this since it seems like that would be a lot of work, but if expand was passed into DropdownButton as:

```dart
new DropdownButton<String>(items: ..., value: ..., expand: true)
```

then the SizedBox could have a width of null or infinity based on the value of expand...

```dart
new SizedBox(
  height: widget.isDense ? _denseButtonHeight : null,
  width: widget.expand ? double.INFINITY : null,
  ...
)
```

## Steps to Reproduce

image

```dart
new Container(
  child: new Row(
    children: <Widget>[
      new Expanded(
        child: new Container(
          child: new DropdownButton<String>(
              isDense: true,
              value: 'one',
              items: <DropdownMenuItem<String>>[
                new DropdownMenuItem(
                    child: new Container(
                      child: new Row(
                        mainAxisSize: MainAxisSize.max,
                        children: <Widget>[
                          new Text('one')
                        ],
                      ),
                    ),
                    value: 'one'),
                new DropdownMenuItem(child: new Text('two'), value: 'two'),
                new DropdownMenuItem(child: new Text('three'), value: 'three')
              ],
              onChanged: null),
        )
      )
    ],
  ),
)
```

## Logs

no useful `flutter run` logs

Analyzing /Users/jpgilchrist/Development/github/veoci-mobile...
  lint • Name non-constant identifiers using lowerCamelCase at lib/utils/veoci_api.dart:15:16 • non_constant_identifier_names
  hint • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method at lib/components/my_rooms/my_rooms_component.dart:143:8 • must_call_super
  hint • Unused import at lib/components/private_chat/private_chat_component.dart:2:8 • unused_import
  hint • Unused import at lib/config/route_handlers.dart:3:8 • unused_import
4 issues found.
(Ran in 6.5s)

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.13.1 17B48, locale en-US, channel alpha)
    • Flutter at /Users/jpgilchrist/Development/github/flutter
    • Framework revision e8aa40eddd (5 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/jpgilchrist/Library/Android/sdk
    • Platform android-27, build-tools 27.0.1
    • ANDROID_HOME = /Users/jpgilchrist/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone X                  • 44914EA5-A848-49F9-9A6D-E1E196D58E4A • ios         • iOS 11.1 (simulator)

### PR DESCRIPTION
**Pull request by mklim**
Fixes #13135, #16606

### CODE REVIEW

**Comment by mklim** [comment]
Manually updated the CLA to yes since the other patch author consented for their commits to be contributed to this project in [PR #19450](https://github.com/flutter/flutter/pull/19450).

File: packages/flutter/lib/src/material/dropdown.dart [hunk 1]
```diff
@@ -529,6 +530,13 @@ class DropdownButton<T> extends StatefulWidget {
   /// its own decorations, like [InputDecorator].
   final bool isDense;
 
+  /// Set the dropdown's inner contents to horizontally fill its parent.
+  ///
+  /// By default this button's inner width is the minimum size of its contents.
+  /// If isExpanded is true, the inner width is expanded to fill its surrounding
```
Comment (Hixie) [inline packages/flutter/lib/src/material/dropdown.dart]: `If [isExpanded] is...`

File: packages/flutter/test/material/dropdown_test.dart [hunk 2]
```diff
@@ -337,6 +339,25 @@ void main() {
     });
   }
 
+  testWidgets('Arrow icon aligns with the edge of button when expanded', (WidgetTester tester) async {
+    final Key buttonKey = new UniqueKey();
+
+    Widget build() =>
+        buildFrame(buttonKey: buttonKey, value: 'two', isExpanded: true);
```
Comment (Hixie) [inline packages/flutter/test/material/dropdown_test.dart]: might be easier to read if this was all on one line, or if the line breaks were in the arguments rather than after the `=>`.

File: packages/flutter/test/material/dropdown_test.dart [hunk 3]
```diff
@@ -337,6 +339,25 @@ void main() {
...
+
+    await tester.pumpWidget(build());
+    final RenderBox buttonBox = tester.renderObject(find.byKey(buttonKey));
+    assert(buttonBox.attached);
+
+    final RenderBox arrowIcon =
+        tester.renderObject(find.byIcon(Icons.arrow_drop_down));
```
Comment (Hixie) [inline packages/flutter/test/material/dropdown_test.dart]: definitely don't wrap this since it hides that this code is basically identical to line 349

**Comment by Hixie** [comment]
LGTM modulo comments.

Might be interesting to do a golden test for this.

**Review by HansMuller — APPROVED** [review]
LGTM

You added a RepaintBoundary which seems like a reasonable change but isn't part of fixing either of the issues (as far as I can tell).  Adding something to the issue's description about the new RepaintBoundary would be helpful.

**Comment by mklim** [comment]
From what I can tell the repaint boundary is used to crop the goldens to the size of the widget, so that's why I added it in to the test. l'll mention it in the commit message too.
