### PR TITLE
[Impeller] optimize drawImageRect with blend and matrix color filter.

### LINKED ISSUE #165959: Severe performance degradation of `drawImageRect`
### Steps to reproduce

Clone https://github.com/jag2011/flutter_impeller_bunnies or run any app doing a lot of `drawImageRect` calls for Flutter v3.29.2 and compare to Flutter v3.27.4, and compare Skia to Impeller.

### Expected results

We expect similar performance for Impeller and Skia, and no degradation in Impeller compared to v3.27.4.

This issue has been reported by many game creators and Flame users, which is to be expected since it's much more common to do many `drawImageRect` calls in the gamedev domain compared to normal apps.

### Actual results

These results are from runs on a Nothing phone 1 (A063) in profile mode.

| Entity count | Flutter version | Impeller | Result                                                            |
|-------------------|-----------------------|:------------:|----------------------------------------------------------|
| 300                | v3.29.2               | yes          |   |
| 300                | v3.29.2               | no          |   |
| 300                | v3.27.4               | yes          |  |
| 300                | v3.27.4               | no          |  |
| 2000               | v3.29.2               | yes          |   |
| 2000                | v3.29.2               | no          |   |
| 2000               | v3.27.4               | yes          | Crash (`sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory`) |
| 2000               | v3.27.4               | no           |   |

These results are for Android, but you'll see similar a degradation on iOS too if the MRE is run there.

Many thanks to @jag2011 for the MRE and @gnarhard for detailed report of the degradation.

### Code sample

Reproduction code can be found here: https://github.com/jag2011/flutter_impeller_bunnies

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.2, on Ubuntu 24.04.2 LTS 6.8.0-55-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2024.3)
[✓] VS Code (version 1.98.2)
[✓] VS Code (version 1.99.0-insider)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/165959

Flame uses a lot of individual calls to drawImageRect w/ blend color filters to color the sprites. This is much slower with Impeller today, because we convert this into:

```
saveLayer(color filter)
drawImageRect
restore
```

Instead, we can detect this case and convert to a call to drawAtlas. drawAtlas will use the porter-duff shader which removes the saveLayer entirely. We could do this optimization while recording, but for now its fine to do in dispatch.

We do have a snapshot optimization that catches "normal" image usage, but it doesn't apply in the flame case as the source rects are sampling from a larger texture and we don't have a way to pass those through the snapshot system.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
So in theory our snapshot optimization handles this - however we don't handle a src/dst rect that are different sizes. Since this is really only an improvement for blend/matrix color filters, I think it makes more sense to add the optimization in canvas than it does to refactor the snapshot system.

File: engine/src/flutter/impeller/display_list/canvas.cc [hunk 1]
```diff
@@ -730,6 +743,68 @@ void Canvas::DrawImageRect(const std::shared_ptr<Texture>& image,
...
+  // we should swap out the shader for the porter duff blend shader and avoid a
+  // saveLayer. This can only be done for imageRects without a strict source
+  // rect, as the porter duff shader does not support this feature. This
+  // optimization is important for flame.
+  if (src_rect_constraint != SourceRectConstraint::kStrict &&  //
+      paint.color_filter &&                                    //
+      paint.image_filter == nullptr &&                         //
+      !paint.mask_blur_descriptor.has_value() &&               //
+      IsPipelineBlendOrMatrixFilter(paint.color_filter)) {
+    if (paint.color_filter->type() == flutter::DlColorFilterType::kBlend) {
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/display_list/canvas.cc:758]: nit: This method is huge, can you split this out into it's own function.

File: engine/src/flutter/impeller/display_list/canvas.cc [hunk 2]
```diff
@@ -730,6 +743,68 @@ void Canvas::DrawImageRect(const std::shared_ptr<Texture>& image,
   if (!clipped_source) {
     return;
   }
+
+  // Optimization: if the texture has a color filter that is a simple
+  // porter-duff blend or matrix filter, then instead of performing a save layer
+  // we should swap out the shader for the porter duff blend shader and avoid a
+  // saveLayer. This can only be done for imageRects without a strict source
+  // rect, as the porter duff shader does not support this feature. This
+  // optimization is important for flame.
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/display_list/canvas.cc:752]:
```suggestion
  // optimization is important for Flame.
```

File: engine/src/flutter/impeller/entity/contents/atlas_contents.h [hunk 3]
```diff
@@ -64,6 +105,38 @@ class AtlasContents final : public Contents {
   AtlasContents& operator=(const AtlasContents&) = delete;
 };
 
+/////
+
+class ColorFilterAtlasContents final : public Contents {
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/contents/atlas_contents.h:110]: Add brief docstring

File: engine/src/flutter/impeller/entity/contents/atlas_contents.h [hunk 4]
```diff
@@ -64,6 +105,38 @@ class AtlasContents final : public Contents {
...
+  // |Contents|
+  std::optional<Rect> GetCoverage(const Entity& entity) const override;
+
+  // |Contents|
+  bool Render(const ContentContext& renderer,
+              const Entity& entity,
+              RenderPass& pass) const override;
+
+ private:
+  AtlasGeometry* geometry_ = nullptr;
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/contents/atlas_contents.h:131]: Add comment why raw pointer can't result in a dangling pointer.

File: engine/src/flutter/impeller/entity/shaders/filters/color_matrix_color_filter.frag [hunk 5]
```diff
@@ -54,5 +55,5 @@ void main() {
                 float16_t(0), float16_t(1.0));
 
   // premultiply the outputs
-  frag_color = f16vec4(color.rgb * color.a, color.a);
+  frag_color = f16vec4(color.rgb * color.a, color.a) * frag_info.output_alpha;
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/shaders/filters/color_matrix_color_filter.frag:58]:
```suggestion
  frag_color = IPHalfPremultiply(color) * frag_info.output_alpha;
```

**Review by gaaclarke — COMMENTED** [review]
Code looks good to me, the goldens don't look alright though.  Check out impeller_Play_AiksTest_ColorFilterBlend_Metal.

File: engine/src/flutter/impeller/entity/contents/atlas_contents.h (hunk 4 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/atlas_contents.h:134]: Done

File: engine/src/flutter/impeller/entity/contents/atlas_contents.h (hunk 3 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/contents/atlas_contents.h:110]: Done

File: engine/src/flutter/impeller/display_list/canvas.cc (hunk 1 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/display_list/canvas.cc]: Done

**Review by gaaclarke — APPROVED** [review]
lgtm as long as the goldens are good.
