### PR TITLE
Fix v1 embedding support heuristic for plugins

### LINKED ISSUE #43779: Print message when app is using the Android embedding v1 and a plugin using v2
This will require a go link with some actionable information.

### PR DESCRIPTION
**Pull request by blasten**
## Description

Detect if a plugin supports the v1 embedding by checking if the main class imports `io.flutter.plugin.common.PluginRegistry`.  

I ran `./script/build_all_plugins_app.sh apk` and it succeeded.

## Related Issues

#43779

I added the following tests: Unit test.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by xster** [comment]
Nit, I think we're not going to fix #44161 and #44171 specifically right. If they already upgraded their projects, we'd have to fix whatever follow up issues they're facing

**Comment by xster** [comment]
LGTM

**Comment by xster** [comment]
This is super speculative at this point. Theoretically, it's possible to get a false negative if someone imports io.flutter.plugin.common.*, and then calls registerWith(PluginRegistry registry).

**Comment by mklim** [comment]
> This is super speculative at this point. Theoretically, it's possible to get a false negative if someone imports io.flutter.plugin.common.*, and then calls registerWith(PluginRegistry registry).

I don't think this is that speculative given how large the ecosystem is, though unfortunately I can't easily search Github for examples since the punctuation is the important part here. In general I'd prefer we land the rollback first at flutter/flutter#44210 and then work on a more robust fix if possible.

It's going to be hard to meaningfully ensure that this works with text matching. I think `registerWith` casts the widest net but will almost certainly have some false positives.

**Comment by xster** [comment]
spoken offline, we're suggesting adding both io.flutter.plugin.common or registerWith as heuristics. We'll try to add 'error diagnostics' for false positives but it may not make the phase 1 cut to stable.

**Comment by blasten** [comment]
Understood @mklim. PTAL

File: packages/flutter_tools/lib/src/platform_plugins.dart [hunk 1]
```diff
@@ -120,8 +120,8 @@ class AndroidPlugin extends PluginPlatform {
     } else {
       supportedEmbeddings.add('1');
     }
-    if (mainClassContent.contains('registerWith(Registrar registrar)') ||
-        mainClassContent.contains('registerWith(registrar: Registrar)')) {
+    if (mainClassContent.contains('PluginRegistry')
```
Comment (xster) [inline packages/flutter_tools/lib/src/platform_plugins.dart]: ohhhh I like this, nice

**Comment by xster** [comment]
LGTM

**Review by mklim — APPROVED** [review]
I think this solves the problem the original PR had but introduces some potential false positives. My Kotlin knowledge is patchy enough that I'm a little concerned about unknown unknowns causing bugs there, but I don't actually have any concrete issues in mind here.

If it's urgent to land this ASAP I think this is an acceptable least invasive fix, so LGTM.

I don't think this is the best overall approach if we want to actually meaningfully understand the plugin state at this point in time.  If we had more time I'd suggest a couple alternatives instead:

- Asking for plugin authors to update the `pubspec.yaml` with some key and enum, and assuming just v1 support in the absence of it being set. This could also be useful for pub?
- Importing some kind of meaningful Java parser into Dart, or offloading this task to something on the JVM that can actually understand the class and output a result (not sure if it's worth it).

If it's not time so much as effort, as in false positives just really aren't that important, then I would rather rewrite this to just always assume that v1 embedding exists at this point and maybe print a message about v2 being required after the fact if and when compilation fails.

**Comment by blasten** [comment]
@mklim we discussed adding these fields to pubspec.yaml. At the time, the conclusion was to check the files for imports since they are the source of truth.  Unfortunately, I don't think the conversation was captured in a doc.

**Comment by xster** [comment]
Still LGTM
