### PR TITLE
Fix paint offset in reverse for 2D

### LINKED ISSUE #128723: 2D paint offset is off in reverse
While writing tests for ensureVisible in 2D, found a bug in how the 2D viewport calculates the paint offset of the children when reversed. 

Expected:

image

Actual:

Screenshot 2023-06-12 at 2 42 21 PM

```dart
import 'dart:math' as math;
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const SimpleTest());
}

class SimpleTest extends StatelessWidget {
  const SimpleTest({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SimpleTableView(
          mainAxis: Axis.vertical,
          primary: true,
          verticalDetails: const ScrollableDetails.vertical(reverse: true),
          horizontalDetails: const ScrollableDetails.horizontal(),
          delegate: SimpleTableDelegate(builder: (context, vicinity) {
            return Container(
              decoration: BoxDecoration(
                border: Border.all(),
                color: vicinity.xIndex.isEven && vicinity.yIndex.isEven
                    ? Colors.amber[100]
                    : (vicinity.xIndex.isOdd && vicinity.yIndex.isOdd
                        ? Colors.blueAccent[100]
                        : null),
              ),
              height: 200.0,
              width: 200.0,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Checkbox(value: false, onChanged: (value) {}),
                  Text(vicinity.toString()),
                ],
              ),
            );
          }),
        ),
      ),
    );
  }
}

class SimpleTableDelegate extends TwoDimensionalChildBuilderDelegate {
  SimpleTableDelegate({required super.builder});
}

class SimpleTableView extends TwoDimensionalScrollView {
  const SimpleTableView({
    super.key,
    super.primary,
    super.mainAxis = Axis.vertical,
    super.verticalDetails = const ScrollableDetails.vertical(),
    super.horizontalDetails = const ScrollableDetails.horizontal(),
    required super.delegate,
    super.cacheExtent,
    super.diagonalDragBehavior = DiagonalDragBehavior.none,
    super.dragStartBehavior = DragStartBehavior.start,
    super.keyboardDismissBehavior = ScrollViewKeyboardDismissBehavior.manual,
    super.clipBehavior = Clip.hardEdge,
  });

  @override
  Widget buildViewport(BuildContext context, ViewportOffset verticalOffset,
      ViewportOffset horizontalOffset) {
    return SimpleTableViewport(
      horizontalOffset: horizontalOffset,
      horizontalAxisDirection: horizontalDetails.direction,
      verticalOffset: verticalOffset,
      verticalAxisDirection: verticalDetails.direction,
      mainAxis: mainAxis,
      delegate: delegate,
      cacheExtent: cacheExtent,
      clipBehavior: clipBehavior,
    );
  }
}

class SimpleTableViewport extends TwoDimensionalViewport {
  const SimpleTableViewport({
    super.key,
    required super.verticalOffset,
    required super.verticalAxisDirection,
    required super.horizontalOffset,
    required super.horizontalAxisDirection,
    required super.delegate,
    required super.mainAxis,
    super.cacheExtent,
    super.clipBehavior = Clip.hardEdge,
  });

  @override
  SimpleTableDelegate get delegate => super.delegate as SimpleTableDelegate;

  @override
  RenderTwoDimensionalViewport createRenderObject(BuildContext context) {
    return RenderSimpleTableViewport(
      horizontalOffset: horizontalOffset,
      horizontalAxisDirection: horizontalAxisDirection,
      verticalOffset: verticalOffset,
      verticalAxisDirection: verticalAxisDirection,
      mainAxis: mainAxis,
      delegate: delegate,
      childManager: context as TwoDimensionalChildManager,
      cacheExtent: cacheExtent,
      clipBehavior: clipBehavior,
    );
  }

  @override
  void updateRenderObject(
      BuildContext context, RenderSimpleTableViewport renderObject) {
    renderObject
      ..horizontalOffset = horizontalOffset
      ..horizontalAxisDirection = horizontalAxisDirection
      ..verticalOffset = verticalOffset
      ..verticalAxisDirection = verticalAxisDirection
      ..mainAxis = mainAxis
      ..delegate = delegate
      ..cacheExtent = cacheExtent
      ..clipBehavior = clipBehavior;
  }
}

class RenderSimpleTableViewport extends RenderTwoDimensionalViewport {
  RenderSimpleTableViewport({
    required super.horizontalOffset,
    required super.horizontalAxisDirection,
    required super.verticalOffset,
    required super.verticalAxisDirection,
    required super.delegate,
    required super.mainAxis,
    required super.childManager,
    super.cacheExtent,
    super.clipBehavior = Clip.hardEdge,
  });

  @override
  void layoutChildSequence() {
    // Every child is 200x200 square
    final double horizontalPixels = horizontalOffset.pixels;
    final double verticalPixels = verticalOffset.pixels;
    final int leadingColumn = math.max((horizontalPixels / 200).floor(), 0);
    final int trailingColumn = math.min(
      ((horizontalPixels + viewportDimension.width + cacheExtent) / 200).ceil(),
      99,
    );
    final int leadingRow = math.max((verticalPixels / 200).floor(), 0);
    final int trailingRow = math.min(
      ((verticalPixels + viewportDimension.height + cacheExtent) / 200).ceil(),
      99,
    );

    double xLayoutOffset = (leadingColumn * 200) - horizontalOffset.pixels;
    for (int column = leadingColumn; column <= trailingColumn; column++) {
      double yLayoutOffset = (leadingRow * 200) - verticalOffset.pixels;
      for (int row = leadingRow; row <= trailingRow; row++) {
        final ChildVicinity vicinity = ChildVicinity(xIndex: column, yIndex: row);
        final RenderBox child = buildOrObtainChildFor(vicinity)!;
        child.layout(constraints, parentUsesSize: true);
        parentDataOf(child).layoutOffset = Offset(xLayoutOffset, yLayoutOffset);
        yLayoutOffset += 200;
      }
      xLayoutOffset += 200;
    }
    verticalOffset.applyContentDimensions(
      0,
      200 * 100 - viewportDimension.height,
    );
    horizontalOffset.applyContentDimensions(
      0,
      200 * 100 - viewportDimension.width,
    );
  }
}

```

I have a fix on the way...

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/128723

The paint offset was incorrectly being computed when one or both axis was in the reverse direction. Instead of using the paint extent, the child's size should be used.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/two_dimensional_viewport.dart [hunk 1]
```diff
@@ -1243,14 +1242,15 @@ abstract class RenderTwoDimensionalViewport extends RenderBox implements RenderA
   Offset computeAbsolutePaintOffsetFor(
     RenderBox child, {
     required Offset layoutOffset,
-    required Size paintExtent,
   }) {
-    assert(hasSize); // this is only usable once we have a size
+    // This is only usable once we have a sizes
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/two_dimensional_viewport.dart:1246]:
```suggestion
    // This is only usable once we have a size.
```

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/two_dimensional_viewport.dart:1246]: Or

```suggestion
    // This is only usable once we have sizes.
```

**Review by goderbauer — APPROVED** [review]
LGTM
