### PR TITLE
Check if `MultiChildRenderObjectElement` has an associated RO

### LINKED ISSUE #78159: We can write a widget which messes up with MultiChild widgets
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
main.dart:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(title: const Text('Oops')),
        body: Center(
          child: IndexedStack(
            index: 0,
            children: [
              Text('1'),
              const AnotherWidget(),
              Text('2'),
            ],
          ),
        ),
      ),
    );
  }
}

class AnotherWidget extends Widget {
  const AnotherWidget({Key key}) : super(key: key);

  @override
  Element createElement() => _AnotherElement(this);
}

class _AnotherElement extends Element {
  _AnotherElement(AnotherWidget widget) : super(widget);

  @override
  bool get debugDoingBuild => false;

  @override
  void performRebuild() {}
}
```
3. Run the app

**Expected results:** 
1 is displayed

**Actual results:** 
2 is displayed

<details>
  <summary>Logs</summary>

```
[  +69 ms] executing: [D:\Dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +72 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[        ] executing: [D:\Dev\flutter/] git tag --points-at 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[  +79 ms] Exit code 0 from: git tag --points-at 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[        ] 2.0.2
[  +36 ms] executing: [D:\Dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\Dev\flutter/] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +73 ms] executing: [D:\Dev\flutter/] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +90 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +54 ms] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe devices -l
[  +38 ms] List of devices attached
           87950fce               device product:OnePlus8Pro_EEA model:IN2023 device:OnePlus8Pro transport_id:2
[   +5 ms] D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce shell getprop
[  +93 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +76 ms] Skipping pub get: version match.
[ +110 ms] Generating D:\Dev\flutter_devs\bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +62 ms] ro.hardware = qcom
[  +33 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +7 ms] complete
[   +4 ms] Launching lib\main.dart on IN2023 in debug mode...
[   +5 ms] D:\Dev\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev D:\Dev\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root D:\Dev\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata --output-dill D:\sys\tmp\flutter_tools.9642b74a\flutter_tool.68569e6e\app.dill --packages D:\Dev\flutter_devs\bug\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[   +9 ms] executing: D:\DevResources\Android\sdk\build-tools\30.0.3\aapt dump xmltree D:\Dev\flutter_devs\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +12 ms] Exit code 0 from: D:\DevResources\Android\sdk\build-tools\30.0.3\aapt dump xmltree D:\Dev\flutter_devs\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +6 ms] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce shell -x logcat -v time -t 1
[  +12 ms] <- compile package:bug/main.dart
[ +221 ms] --------- beginning of main
           03-14 16:51:07.453 I/OMX-VENC: venc_dev( 1366): stats: avg. fps 0.32, bitrate 3007
[   +9 ms] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe version
[  +23 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as D:\DevResources\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe start-server
[  +21 ms] Building APK
[  +23 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] Using gradle from D:\Dev\flutter_devs\bug\android\gradlew.bat.
[   +1 ms] D:\Dev\flutter_devs\bug\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +10 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +82 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_152-release"
           OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
           OpenJDK 64-Bit Server VM (build 25.152-b02, mixed mode)
[   +1 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +77 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_152-release"
           OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
           OpenJDK 64-Bit Server VM (build 25.152-b02, mixed mode)
[   +3 ms] executing: [D:\Dev\flutter_devs\bug\android/] D:\Dev\flutter_devs\bug\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=D:\Dev\flutter_devs\bug\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3504 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +80 ms] executing: [D:\Dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +73 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[        ] [        ] executing: [D:\Dev\flutter/] git tag --points-at 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[        ] [  +83 ms] Exit code 0 from: git tag --points-at 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[        ] [        ] 2.0.2
[        ] [  +40 ms] executing: [D:\Dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [D:\Dev\flutter/] git ls-remote --get-url origin
[        ] [  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +77 ms] executing: [D:\Dev\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +49 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +67 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +59 ms] Initializing file store
[        ] [  +14 ms] Done initializing file store
[        ] [  +34 ms] Skipping target: gen_localizations
[  +93 ms] [ +488 ms] Skipping target: kernel_snapshot
[ +299 ms] [ +296 ms] Skipping target: debug_android_application
[        ] [   +1 ms] Persisting file store
[        ] [  +17 ms] Done persisting file store
[   +1 ms] [   +4 ms] build succeeded.
[  +14 ms] [  +18 ms] "flutter assemble" took 1ÔÇ»028ms.
[        ] [   +4 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +5 ms] exiting with code 0
[  +78 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata UP-TO-DATE
[  +90 ms] > Task :app:cleanMergeDebugAssets
[   +1 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +336 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[  +91 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[   +1 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[  +10 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[  +90 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[  +61 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[   +1 ms] > Task :app:validateSigningDebug UP-TO-DATE
[  +12 ms] > Task :app:packageDebug UP-TO-DATE
[ +184 ms] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 4s
[        ] 32 actionable tasks: 5 executed, 27 up-to-date
[ +532 ms] Running Gradle task 'assembleDebug'... (completed in 5,6s)
[  +38 ms] calculateSha: LocalDirectory: 'D:\Dev\flutter_devs\bug\build\app\outputs\flutter-apk'/app.apk
[  +20 ms] calculateSha: reading file took 19us
[ +634 ms] calculateSha: computing sha took 633us
[   +4 ms] ÔêÜ Built build\app\outputs\flutter-apk\app-debug.apk.
[  +10 ms] executing: D:\DevResources\Android\sdk\build-tools\30.0.3\aapt dump xmltree D:\Dev\flutter_devs\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +23 ms] Exit code 0 from: D:\DevResources\Android\sdk\build-tools\30.0.3\aapt dump xmltree D:\Dev\flutter_devs\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[        ] Stopping app 'app.apk' on IN2023.
[        ] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce shell am force-stop com.example.bug
[ +114 ms] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce shell pm list packages com.example.bug
[  +98 ms] package:com.example.bug
[   +1 ms] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce shell cat /data/local/tmp/sky.com.example.bug.sha1
[  +51 ms] 1777b12bf444164c8b99a035d934af85e92e5c90
[        ] Latest build already installed.
[        ] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce shell -x logcat -v time -t 1
[ +206 ms] --------- beginning of main
           03-14 16:51:14.454 I/cmd     (15624): oneway function results will be dropped but finished with status OK and parcel size 4
[   +5 ms] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.bug/com.example.bug.MainActivity
[  +89 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.bug/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +270 ms] Observatory URL on device: http://127.0.0.1:39857/-qrNehs5JcA=/
[   +1 ms] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce forward tcp:0 tcp:39857
[  +24 ms] 58621
[        ] Forwarded host port 58621 to device port 39857 for Observatory
[ +348 ms] Caching compiled dill
[  +35 ms] Connecting to service protocol: http://127.0.0.1:58621/-qrNehs5JcA=/
[ +137 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:58621/-qrNehs5JcA=/.
[  +85 ms] DDS is listening at http://127.0.0.1:58627/CaqdUOZeEHU=/.
[  +47 ms] Successfully connected to service protocol: http://127.0.0.1:58621/-qrNehs5JcA=/
[  +35 ms] Activating Dart DevTools...
[+2354 ms] Activating Dart DevTools... (completed in 2ÔÇ»353ms)
[ +702 ms] DevFS: Creating new filesystem on the device (null)
[  +33 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.bug/code_cache/bugTANULV/bug/)
[   +4 ms] Updating assets
[  +66 ms] Syncing files to device IN2023...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:bug/main.dart 9f040c6b-6bb0-47a2-9b94-abdb5725235d
[        ] <- 9f040c6b-6bb0-47a2-9b94-abdb5725235d
[ +151 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device IN2023... (completed in 156ms)
[        ] Synced 0.0MB.
[        ] <- accept
[  +15 ms] Connected to _flutterView/0xb4000074e0f7de00.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on IN2023 is available at: http://127.0.0.1:58627/CaqdUOZeEHU=/
[        ] 
           Flutter DevTools, a Flutter debugger and profiler, on IN2023 is available at: http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A58627%2FCaqdUOZeEHU%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+17262 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.bug/code_cache/bugTANULV/bug/)
[  +31 ms] DevFS: Deleted filesystem on the device (file:///data/user/0/com.example.bug/code_cache/bugTANULV/bug/)
[ +148 ms] Service protocol connection closed.
[        ] Application finished.
[   +5 ms] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce forward --list
[  +22 ms] Exit code 0 from: D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce forward --list
[        ] 87950fce tcp:58621 tcp:39857
[        ] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce forward --remove tcp:58621
[  +24 ms] executing: D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce forward --list
[  +20 ms] Exit code 0 from: D:\DevResources\Android\sdk\platform-tools\adb.exe -s 87950fce forward --list
[        ] "flutter run" took 29ÔÇ»669ms.
[  +96 ms] ensureAnalyticsSent: 93ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

```
```

```
[ÔêÜ] Flutter (Channel stable, 2.0.2, on Microsoft Windows [version 10.0.19041.867], locale fr-FR)
    ÔÇó Flutter version 2.0.2 at D:\Dev\flutter
    ÔÇó Framework revision 8962f6dc68 (3 days ago), 2021-03-11 13:22:20 -0800
    ÔÇó Engine revision 5d8bf811b3
    ÔÇó Dart version 2.12.1

[ÔêÜ] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ÔÇó Android SDK at D:\DevResources\Android\sdk
    ÔÇó Platform android-30, build-tools 30.0.3
    ÔÇó ANDROID_HOME = D:\DevResources\Android\sdk
    ÔÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ÔÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    ÔÇó All Android licenses accepted.

[ÔêÜ] Chrome - develop for the web
    ÔÇó Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[ÔêÜ] Android Studio (version 3.1)
    ÔÇó Android Studio at C:\Program Files\Android\Android Studio
    ÔÇó Flutter plugin version 21.0.1
    ÔÇó Dart plugin version 171.4424
    ÔÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[ÔêÜ] IntelliJ IDEA Community Edition (version 2018.1)
    ÔÇó IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.4
    ÔÇó Flutter plugin version 31.3.1
    ÔÇó Dart plugin version 181.4892.1

[ÔêÜ] VS Code (version 1.54.2)
    ÔÇó VS Code at C:\Users\romai\AppData\Local\Programs\Microsoft VS Code
    ÔÇó Flutter extension version 3.20.0

[ÔêÜ] Connected device (3 available)
    ÔÇó IN2023 (mobile) ÔÇó 87950fce ÔÇó android-arm64  ÔÇó Android 11 (API 30)
    ÔÇó Chrome (web)    ÔÇó chrome   ÔÇó web-javascript ÔÇó Google Chrome 89.0.4389.82
    ÔÇó Edge (web)      ÔÇó edge     ÔÇó web-javascript ÔÇó Microsoft Edge 89.0.774.50

ÔÇó No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes #78159 

If we mount a non-RenderObjectElement to `MultiChildRenderObjectElement` will cause `ContainerRenderObjectMixin` works abnormal. This is because the `MultiChildRenderObjectElement.insertRenderObjectChild` depend on the RO to decide where the new RO to insert. If some of the elements's RO is null, the new RO child will insert at the first position by mistake.

This change tries to add a checker for the situation.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/framework.dart [hunk 1]
```diff
@@ -6194,6 +6212,10 @@ class MultiChildRenderObjectElement extends RenderObjectElement {
     super.update(newWidget);
     assert(widget == newWidget);
     _children = updateChildren(_children, widget.children, forgottenChildren: _forgottenChildren);
+    assert(() {
+      _children.forEach(_debugCheckHasAssociatedRenderObject);
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/framework.dart:6216]: If we check after `updateChildren`, some scenarios where keys are reused will throw more exceptions. See the test cases for details.
If we want to avoid this happens, we need to extend the `updateChildren` parameter and pass the check function to it. However, if we do this, the modification is very invasive. What is your opinion?

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/framework.dart:6216]: @chunhtai

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/framework.dart:6216]: It seems like that we can override the inflateWidge and make the check instead. I will try it.

**Comment by chunhtai** [comment]
The original issue seems to be an indexedStack specific issue, where it assume the first renderobject corresponds to index 0, second to index 1, ... and so on. We had the similar issue in RenderParagraph, where we tag the child renderobject with the index.

I am not confident whether we should force the same thing to other widget. For example, column widget does not really care about this

**Comment by xu-baolin** [comment]
@chunhtai Hey
I think this is a common bug of `MultiChildRenderObjectElement`, for example
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}
final Key key = GlobalKey(debugLabel: 'problematic');
class MyApp extends StatelessWidget {
  const MyApp({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(title: const Text('Oops')),
        body: Center(
          child: Column(
            // index: 0,
            children: [
              // Container(key: const ValueKey<int>(1)),
              // Container(key: const ValueKey<int>(1), child: Container(key: key)),
              // // Container(key: const ValueKey<int>(2),),
              // Container(key: const ValueKey<int>(2), child: Container(key: key)),
              Text('1'),
              Text('11'),
              const AnotherWidget(),
              Text('2'),
              // Container(),
              // Text('1'),
            ],
          ),
        ),
      ),
    );
  }
}

class AnotherWidget extends Widget {
  const AnotherWidget({Key key}) : super(key: key);

  @override
  Element createElement() => _AnotherElement(this);
}

class _AnotherElement extends Element {
  _AnotherElement(AnotherWidget widget) : super(widget);

  @override
  bool get debugDoingBuild => false;

  @override
  void performRebuild() {}
}
```

**Comment by xu-baolin** [comment]
Empty widgets will cause the order of ContainerRenderObjectMixin children to be disordered, resulting in misplaced rendering.

**Review by chunhtai — COMMENTED** [review]
Sounds good, thanks for fixing this

File: packages/flutter/lib/src/widgets/framework.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/framework.dart]: @chunhtai Hi,
If we make checking after `updateChildren` like this commit, it will break some tests because retaken the globalKey will re-parent the RO and trigger the new assert first. Also, need to traverse all the children extra.

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/framework.dart]: And we are not easy to rewrite the `Element.updateChildren `, because it is too complicated.

File: packages/flutter/lib/src/widgets/framework.dart [hunk 2]
```diff
@@ -6176,6 +6176,30 @@ class MultiChildRenderObjectElement extends RenderObjectElement {
     super.forgetChild(child);
   }
 
+  bool _debugCheckHasAssociatedRenderObject(Element newChild) {
+    assert(() {
+      if (newChild.renderObject == null) {
+        throw FlutterError.fromParts(<DiagnosticsNode>[
+          ErrorSummary('The subtree of `MultiChildRenderObjectElement` must have an associated render object.'),
```
[the remark this answers is not in the document]
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/framework.dart]: done

File: packages/flutter/lib/src/widgets/framework.dart [hunk 3]
```diff
@@ -6176,6 +6176,30 @@ class MultiChildRenderObjectElement extends RenderObjectElement {
     super.forgetChild(child);
   }
 
+  bool _debugCheckHasAssociatedRenderObject(Element newChild) {
+    assert(() {
+      if (newChild.renderObject == null) {
+        throw FlutterError.fromParts(<DiagnosticsNode>[
```
[the remark this answers is not in the document]
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/framework.dart]: done

File: packages/flutter/lib/src/widgets/framework.dart [hunk 4]
```diff
@@ -6176,6 +6176,30 @@ class MultiChildRenderObjectElement extends RenderObjectElement {
...
+          newChild.describeElement('The following element does not have an associated render object'),
+        ]);
+      }
+      return true;
+    }());
+    return true;
+  }
+
+  @override
+  Element inflateWidget(Widget newWidget, Object? newSlot) {
```
[the remark this answers is not in the document]
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/framework.dart:6202]: https://github.com/flutter/flutter/pull/78854#discussion_r600960629

File: packages/flutter/test/widgets/framework_test.dart [hunk 5]
```diff
@@ -1849,3 +1907,20 @@ class FakeLeafRenderObject extends RenderBox {
...
+
+class _EmptyElement extends Element {
+  _EmptyElement(_EmptyWidget widget) : super(widget);
+
+  @override
+  bool get debugDoingBuild => false;
+
+  @override
+  void performRebuild() {}
+}
```
Comment (chunhtai) [inline packages/flutter/test/widgets/framework_test.dart:1926]: nit: new line at the end of file

**Review by chunhtai — APPROVED** [review]
LGTM
