### PR TITLE
[Impeller] use device private on non-iOS devices.

### LINKED ISSUE #134399: [Impeller] Could not decompress image on intel macOS
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Display an image from local or network.

### Expected results

Just display.

### Actual results

image

### Code sample

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Center(
          child: Image.network('https://i.imgur.com/CzXTtJV.jpg'),
        ),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

_No response_

### Logs

<details><summary>Logs</summary>

```console

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image frame:
Exception: Could not decompress image.

When the exception was thrown, this was the stack

Image provider: NetworkImage("https://i.imgur.com/CzXTtJV.jpg", scale: 1.0)
Image key: NetworkImage("https://i.imgur.com/CzXTtJV.jpg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.14.0-14.0.pre.210, on macOS 13.5.2
    22G91 darwin-x64, locale zh-Hans-HK)
[!] Android toolchain - develop for Android devices (Android SDK
    version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more
      details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK
      licenses.
      See
      https://flutter.dev/docs/get-started/install/macos#android-setup
      for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
[✓] VS Code (version 1.82.0)
[✓] VS Code (version 1.82.0-insider)
[✓] Connected device (2 available)
[✓] Network resources

```

</details>

### LINKED ISSUE #136365: [Impeller] `.webp` assets are broken on macOS.
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Flutter 3.13.6
2. macOS Sonoma
3. `Image.asset('assets/image.webp')`

### Expected results

Regular Image view with asset displayed

### Actual results

Broken image widget

### Code sample

<details><summary>Code sample</summary>

```dart
Image.asset('assets/image.webp')
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

image

</details>

### Logs

<details><summary>Logs</summary>

```console
[ERROR:flutter/shell/platform/embedder/embedder_external_texture_metal.mm(100)] Could not create external texture: 105553158460032
[ERROR:flutter/shell/platform/embedder/embedder_external_texture_metal.mm(100)] Could not create external texture: 105553158460032
[ERROR:flutter/shell/platform/embedder/embedder_external_texture_metal.mm(100)] Could not create external texture: 105553158460032
[ERROR:flutter/shell/platform/embedder/embedder_external_texture_metal.mm(100)] Could not create external texture: 105553158460032
embedder.cc (2691): 'FlutterEngineMarkExternalTextureFrameAvailable' returned 'kInternalInconsistency'. Could not mark the texture frame as being available.
2023-10-11 16:27:40.668 Konflikt[66554:659692] Unable to mark texture with id 105553158460032 as available.
Lost connection to device.
MediaKitEventLoopHandler::Register: std::thread exit: 140156038447120

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for chäeMil’s iPad Pro. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
Redo of https://github.com/flutter/flutter/pull/164573

Fixes https://github.com/flutter/flutter/issues/136365
Fixes https://github.com/flutter/flutter/issues/134399

We should avoid using "host visible" textures outside of iOS, which besides arm macs, is the only place they are supported. Deletes a test that was completely invalid because it was testing a feature "the gpu sync switch aka iOS background check" that was never used in mutli_frame image codecs.

### CODE REVIEW

File: engine/src/flutter/lib/ui/painting/image_decoder_unittests.cc [hunk 1]
```diff
@@ -1007,88 +1010,6 @@ TEST_F(ImageDecoderFixtureTest,
   PostTaskSync(runners.GetIOTaskRunner(), [&]() { io_manager.reset(); });
 }
 
-TEST_F(ImageDecoderFixtureTest, MultiFrameCodecDidAccessGpuDisabledSyncSwitch) {
```
Comment (jonahwilliams) [inline engine/src/flutter/lib/ui/painting/image_decoder_unittests.cc:1010]: We don't actually use the GPU sync switch in the multiframe codec. Instead iOS uses host visible that is always updated ignoring the switch.

**Review by matanlurey — APPROVED** [review]
LGTM
