### PR TITLE
LayerLink can temporary allow multiple leaders

### LINKED ISSUE #95974: LeaderLayer can't attach to different renderobjects in the same frame
I have a stateful widget which builds multiple renderobjects in its subtree. This widget also owns a layerlink and will choose one renderobject children paint this leaderlayer with the layerlink base on state.

It crashes when it try to move the layer link from one render object to another.

The problem can be demonstrated in this test

```dart
  test('Leader layer can switch to a different render object within one frame', () {
    final LayerLink layerLink = LayerLink();
    // renderObject1 paints the leader layer first.
    final LeaderLayerRenderObject renderObject1 = LeaderLayerRenderObject();
    renderObject1.layerLink = layerLink;
    final PipelineOwner owner = PipelineOwner();
    renderObject1.attach(owner);
    final OffsetLayer rootLayer1 = OffsetLayer();
    rootLayer1.attach(renderObject1);
    renderObject1.scheduleInitialPaint(rootLayer1);
    renderObject1.layout(const BoxConstraints.tightForFinite());

    final LeaderLayerRenderObject renderObject2 = LeaderLayerRenderObject();
    final OffsetLayer rootLayer2 = OffsetLayer();
    rootLayer2.attach(renderObject2);
    renderObject2.attach(owner);
    renderObject2.scheduleInitialPaint(rootLayer2);
    renderObject2.layout(const BoxConstraints.tightForFinite());

    owner.flushPaint();
    // Swap the layer link to renderObject2 in the same frame
    renderObject1.layerLink = null;
    renderObject1.markNeedsPaint();
    renderObject2.layerLink = layerLink;
    renderObject2.markNeedsPaint();
    owner.flushPaint();

    // Swap the layer link to renderObject1 in the same frame , this will cause a crash because renderObject1 
   //is painted first, and the layer link think it still belongs to renderobject2
    renderObject1.layerLink = layerLink;
    renderObject1.markNeedsPaint();
    renderObject2.layerLink = null;
    renderObject2.markNeedsPaint();
    owner.flushPaint();
  });

class LeaderLayerRenderObject extends RenderObject {
  LeaderLayerRenderObject();

  LayerLink? layerLink;

  @override
  bool isRepaintBoundary = true;

  @override
  void debugAssertDoesMeetConstraints() { }

  @override
  Rect get paintBounds {
    return Rect.zero;
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    if (layerLink != null) {
      context.pushLayer(LeaderLayer(link: layerLink!), super.paint, offset);
    }
  }

  @override
  void performLayout() { }

  @override
  void performResize() { }

  @override
  Rect get semanticBounds => const Rect.fromLTWH(0.0, 0.0, 10.0, 20.0);
}
```

## Logs

<details>
<summary>Logs</summary>

```
```

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
'package:flutter/src/rendering/layer.dart': Failed assertion: line 2231 pos 12: 'link._leader ==
null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      LeaderLayer.attach (package:flutter/src/rendering/layer.dart:2231:12)
#3      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:138:13)
#4      Layer.adoptChild (package:flutter/src/rendering/layer.dart:402:11)
#5      ContainerLayer.append (package:flutter/src/rendering/layer.dart:1032:5)
#6      PaintingContext.appendLayer (package:flutter/src/rendering/object.dart:226:21)
#7      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384:5)
#8      LeaderLayerRenderObject.paint (file:///Users/chtai/git/flutter/packages/flutter/test/rendering/object_test.dart:312:15)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449:7)
#10     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#11     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#12     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:995:29)
#13     main.<anonymous closure> (file:///Users/chtai/git/flutter/packages/flutter/test/rendering/object_test.dart:188:11)
#14     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:19)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from class _AssertionError and package:stack_trace)

The following RenderObject was being processed when the exception was fired: LeaderLayerRenderObject#023d6:
  needs compositing
  parentData: MISSING
  constraints: BoxConstraints(unconstrained)
  layer: OffsetLayer#01b8b
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════


```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
fixes https://github.com/flutter/flutter/issues/95974

If a child layer is moved to a new container layer in the same frame. the assert will throw if the new container is painted before the old container is painted. This pr fixes it so that the pipelineowner resets all the dirty container layer before any of them is painted

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/rendering/object.dart [hunk 1]
```diff
@@ -103,6 +108,33 @@ class PaintingContext extends ClipContext {
     );
   }
 
+  /// Reset the container layer for the child.
+  ///
+  /// All layers of dirtied composited Children needs to be reset before any of
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/object.dart:113]:
```suggestion
  /// All layers of dirty composited children need to be reset before any of
```

File: packages/flutter/lib/src/rendering/object.dart [hunk 2]
```diff
@@ -103,6 +108,33 @@ class PaintingContext extends ClipContext {
...
+  /// them is repainted in the same frame. Otherwise, a child layer may be
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/object.dart:114]: is -> are

File: packages/flutter/lib/src/rendering/object.dart [hunk 3]
```diff
@@ -103,6 +108,33 @@ class PaintingContext extends ClipContext {
...
+  ///
+  /// See also:
+  ///
+  ///  * [RenderObject.isRepaintBoundary], which determines if a [RenderObject]
+  ///    has a composited layer.
+  static void resetCompositedChildLayer(RenderObject child, { bool debugAlsoPaintedParent = false }) {
+    assert(child.isRepaintBoundary);
+    if (child._layerHandle.layer == null) {
+      assert(debugAlsoPaintedParent);
+      assert(child._layerHandle.layer == null);
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/object.dart:125]: That's the condition of the if branch, so this will be always true?

File: packages/flutter/lib/src/rendering/object.dart [hunk 4]
```diff
@@ -117,27 +149,14 @@ class PaintingContext extends ClipContext {
...
-      // apply here because this is exactly the place designed to create a
-      // layer for repaint boundaries.
-      final OffsetLayer layer = OffsetLayer();
-      child._layerHandle.layer = childLayer = layer;
-    } else {
-      assert(debugAlsoPaintedParent || childLayer.attached);
-      childLayer.removeAllChildren();
-    }
-    assert(identical(childLayer, child._layerHandle.layer));
+    late OffsetLayer childLayer;
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/object.dart:152]: maybe rename this to debugChildLayer since its only used in asserts now?

File: packages/flutter/lib/src/rendering/object.dart [hunk 5]
```diff
@@ -87,14 +87,19 @@ class PaintingContext extends ClipContext {
   /// Repaint the given render object.
   ///
   /// The render object must be attached to a [PipelineOwner], must have a
-  /// composited layer, and must be in need of painting. The render object's
-  /// layer, if any, is re-used, along with any layers in the subtree that don't
-  /// need to be repainted.
+  /// composited layer, and must be in need of painting.
+  ///
+  /// The composited layer must be reset by calling [resetCompositedChildLayer]
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/object.dart:92]: can we assert that this has been called?

File: packages/flutter/test/rendering/object_test.dart [hunk 6]
```diff
@@ -255,6 +334,39 @@ class TestRenderObject extends RenderObject {
   }
 }
 
+class LeaderLayerRenderObject extends RenderObject {
+  LeaderLayerRenderObject();
+
+  LayerLink? layerLink;
+
+  @override
+  bool isRepaintBoundary = true;
```
Comment (goderbauer) [inline packages/flutter/test/rendering/object_test.dart:343]: Just to double check: There isn't a problem if we are not a repaint boundary?

File: packages/flutter/lib/src/rendering/object.dart [hunk 7]
```diff
@@ -987,8 +1008,20 @@ class PipelineOwner {
...
       final List<RenderObject> dirtyNodes = _nodesNeedingPaint;
       _nodesNeedingPaint = <RenderObject>[];
+      // Need to reset the layer of every repaint boundary; otherwise, a child
+      // layer may be appended to a new parent layer before it is removed from
+      // the old parent layer.
+      dirtyNodes.sort((RenderObject a, RenderObject b) => b.depth - a.depth);
+      for (final RenderObject node in dirtyNodes) {
+        assert(node._layerHandle.layer != null);
+        if (node._needsPaint && node.owner == this) {
+          if (node._layerHandle.layer!.attached) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/object.dart:1018]: could be merged into just one if?

File: packages/flutter/lib/src/rendering/object.dart [hunk 8]
```diff
@@ -987,8 +1008,20 @@ class PipelineOwner {
     try {
       final List<RenderObject> dirtyNodes = _nodesNeedingPaint;
       _nodesNeedingPaint = <RenderObject>[];
+      // Need to reset the layer of every repaint boundary; otherwise, a child
+      // layer may be appended to a new parent layer before it is removed from
+      // the old parent layer.
+      dirtyNodes.sort((RenderObject a, RenderObject b) => b.depth - a.depth);
+      for (final RenderObject node in dirtyNodes) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/object.dart:1015]: Since this is performance critical code: We are not doing any extra work now, right? We are just doing the reset upfront instead of later?

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/object.dart:1015]: yes, but it becomes two for-loops instead of one. Not sure whether there will be any impact on perf. If this is not acceptable, I will then have to do something similar to globalkey duplication that temporary allows child to be attached to two parents and adds a postframecallback to make sure the previous parent give up the child.

This will be more complicated than the global key cases though, since it involves detaching/attaching logic.

File: packages/flutter/test/rendering/object_test.dart (hunk 6 above)
Comment (chunhtai) [reply packages/flutter/test/rendering/object_test.dart:343]: It will still be a problem.

The reason i made it a repaint boundary is for easy testing. If it is not a repaint boundary, the markNeedsPaint will go through the ancestor chain to find the nearest repaint boundary and markNeedsPaint on it. That means I would have to create a parent repaint boundary in the test anyway.

Comment (goderbauer) [reply packages/flutter/test/rendering/object_test.dart:343]: But that case is also fixed by this fix, right?

File: packages/flutter/lib/src/rendering/object.dart (hunk 5 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/object.dart:94]: done

**Comment by skia-gold** [comment]
Gold has detected about 8 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/95977

File: packages/flutter/test/rendering/object_test.dart (hunk 6 above)
Comment (chunhtai) [reply packages/flutter/test/rendering/object_test.dart:343]: Yes, In the layer tree, the non-repaint boundary renderobject does not contributing additional node, so there is no difference between layer added by non-repaint boundary renderobject and layer added by the nearest repaint boundary.

**Comment by chunhtai** [comment]
@goderbauer  PTAL

**Comment by goderbauer** [comment]
Why does this change goldens? Is that expected?

**Comment by chunhtai** [comment]
@goderbauer that is previous commit, which broke a lot of tests, the latest commit does not have golden change

**Comment by chunhtai** [comment]
@goderbauer PTAL

File: packages/flutter/lib/src/rendering/layer.dart [hunk 9]
```diff
@@ -2105,6 +2106,29 @@ class PhysicalModelLayer extends ContainerLayer {
...
 
+  /// Stores the previous leaders that were replaced by the current [_leader]
+  /// in the current frame.
+  ///
+  /// These leaders need to give up their leaderships of this link by the end of
+  /// the current frame.
+  Set<LeaderLayer>? _debugPreviousLeaders;
+  bool _debugLeaderCheckScheduled = false;
+
+  /// schedule the check as post frame callback to make sure the
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/layer.dart:2117]: schedule -> Schedule

File: packages/flutter/lib/src/rendering/layer.dart [hunk 10]
```diff
@@ -2105,6 +2106,29 @@ class PhysicalModelLayer extends ContainerLayer {
 class LayerLink {
   LeaderLayer? _leader;
 
+  /// Stores the previous leaders that were replaced by the current [_leader]
+  /// in the current frame.
+  ///
+  /// These leaders need to give up their leaderships of this link by the end of
+  /// the current frame.
+  Set<LeaderLayer>? _debugPreviousLeaders;
+  bool _debugLeaderCheckScheduled = false;
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/layer.dart:2115]: This is never set to true?

File: packages/flutter/lib/src/rendering/layer.dart [hunk 11]
```diff
@@ -2228,15 +2252,32 @@ class LeaderLayer extends ContainerLayer {
...
-    assert(link._leader == null);
+    assert(link._leader != this);
+    assert((){
+      if (link._leader != null) {
+        link._debugPreviousLeaders ??= <LeaderLayer>{};
+        link._debugPreviousLeaders!.add(link._leader!);
+        link._debugScheduleLeadersCleanUpCheck();
+      }
+      return true;
+    }());
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/layer.dart:2263]: I would move all of this into a `_registerLeader` method on LeaderLink to keep this a little cleaner here. This is all impl. detail of leaderLink.

File: packages/flutter/lib/src/rendering/layer.dart [hunk 12]
```diff
@@ -2228,15 +2252,32 @@ class LeaderLayer extends ContainerLayer {
...
+    if (link._leader == this) {
+      link._leader = null;
+    } else {
+      assert((){
+        if (link._leader != this) {
+          return link._debugPreviousLeaders!.remove(this);
+        }
+        return true;
+      }());
+    }
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/layer.dart:2280]: Same with this.

File: packages/flutter/lib/src/rendering/layer.dart [hunk 13]
```diff
@@ -2197,7 +2247,10 @@ class LeaderLayer extends ContainerLayer {
     if (_link == value) {
       return;
     }
-    _link._leader = null;
+    if (attached) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/layer.dart:2250]: wrote a test `switching layer link of an attached leader layer should not crash` for this change

File: packages/flutter/lib/src/rendering/layer.dart (hunk 10 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/layer.dart:2140]: fixed

**Comment by chunhtai** [comment]
@goderbauer PTAL, I also fixed another corner case.

**Review by goderbauer — APPROVED** [review]
LGTM
