### PR TITLE
Cupertino text clear label

### LINKED ISSUE #123107: CupertinoTextField clear button accessibility
## Steps to Reproduce

1. Place a `CupertinoTextField`with `clearButtonMode: OverlayVisibilityMode.always`.
2. Use VoiceOver on an iOS device or turn on the `showSemanticsDebugger` in the Flutter app.

**Expected results:** 

A semantic label (preferably a customizable one) for the clear button.

**Actual results:** 

No semantic label for the clear button.

### PR DESCRIPTION
**Pull request by MitchellGoodwin**
Fixes #123107

Adds a customizable semantic label so that the clear button on the Cupertino text field will be picked up by screen readers.

https://github.com/flutter/flutter/assets/58190796/de31d9dd-923c-402f-a55b-e5cc77ea68bb

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 1]
```diff
@@ -229,6 +229,7 @@ class CupertinoTextField extends StatefulWidget {
     this.suffix,
     this.suffixMode = OverlayVisibilityMode.always,
     this.clearButtonMode = OverlayVisibilityMode.never,
+    this.clearButtonSemanticLabel = 'Text Field Clear',
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_field.dart:232]: I think the label should be localized?

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/cupertino/text_field.dart:232]: I'll put that in.

File: packages/flutter_localizations/lib/src/l10n/cupertino_mr.arb [hunk 2]
```diff
@@ -23,5 +23,6 @@
   "modalBarrierDismissLabel": "डिसमिस करा",
   "searchTextFieldPlaceholderLabel": "शोधा",
   "noSpellCheckReplacementsLabel": "No Replacements Found",
```
Comment (LongCatIsLooong) [inline packages/flutter_localizations/lib/src/l10n/cupertino_mr.arb:25]: Much of these arb files don't seem to have the correct translation for "clearButtonLabel", "menuDismissLabel" or "noSpellCheckReplacementsLabel"?

**Review by LongCatIsLooong — COMMENTED** [review]
I'm not familiar with semantics or internationalization. @chunhtai @thkim1011 do you mind taking a look?

File: packages/flutter_localizations/lib/src/l10n/cupertino_mr.arb (hunk 2 above)
Comment (thkim1011) [reply packages/flutter_localizations/lib/src/l10n/cupertino_mr.arb:25]: The process is that these arb files holds the english strings as a placeholder until they are translated internally. Then we can incorporate those translations into Flutter. Although, it looks like some arb files are missing some strings. Was this [README](https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/README.md) followed for regenerating the arb files?

Comment (MitchellGoodwin) [reply packages/flutter_localizations/lib/src/l10n/cupertino_mr.arb:25]: I found that README file partway through manually adding the `clearButtonLabel` to some of the arb files and was originally copying the flow from previous PRs adding localization. The only difference I saw was the placement of `clearButtonLabel` was different in the files I manually added. The other two translations are from other work.

Comment (MitchellGoodwin) [reply packages/flutter_localizations/lib/src/l10n/cupertino_mr.arb:25]: Are there arb files missing the translation besides the cupertino_xx_XX.arb files? I assumed the script skipped those for a reason.

Comment (thkim1011) [reply packages/flutter_localizations/lib/src/l10n/cupertino_mr.arb:25]: Ah my bad, I thought `menuDismissLabel` was added in this PR but I think it just changed because of commas at the end of the line. The localization changes LGTM.

**Comment by goderbauer** [comment]
@MitchellGoodwin said last week that he still has plans to finish this.

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 3]
```diff
@@ -508,6 +511,12 @@ class CupertinoTextField extends StatefulWidget {
   /// Defaults to [OverlayVisibilityMode.never].
   final OverlayVisibilityMode clearButtonMode;
 
+  /// The semantic label for the clear button used by screen readers.
+  ///
+  /// This will be used by screen reading software to identify the clear button
+  /// widget. Defaults to "Text Field Clear".
```
Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/text_field.dart:517]: From looking at the intl files: doesn't this just default to "clear"?

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 4]
```diff
@@ -1116,15 +1126,21 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with Restoratio
...
-    return GestureDetector(
-      key: _clearGlobalKey,
-      onTap: widget.enabled ? _onClearButtonTapped : null,
-      child: Padding(
-        padding: const EdgeInsets.symmetric(horizontal: 6.0),
-        child: Icon(
-          CupertinoIcons.clear_thick_circled,
-          size: 18.0,
-          color: CupertinoDynamicColor.resolve(_kClearButtonColor, context),
+    final CupertinoLocalizations localizations = CupertinoLocalizations.of(context);
```
Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/text_field.dart:1129]: I would do:

```dart
final String clearLabel = widget.clearButtonSemanticLabel ?? CupertinoLocalizations.of(context).clearButtonLabel;
```
That way, you only establish a dependency on CupertinoLocalizations if you actually need it.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 5]
```diff
@@ -7887,6 +7887,65 @@ void main() {
...
+            child: const CupertinoTextField(
+              clearButtonMode: OverlayVisibilityMode.always,
+              clearButtonSemanticLabel: 'Delete Text'
+            ),
+          ),
+        ),
+      ),
+    );
+
+    expect(find.bySemanticsLabel('Text Field Clear'), findsNothing);
```
Comment (goderbauer) [inline packages/flutter/test/cupertino/text_field_test.dart:7933]: Should this be

```suggestion
    expect(find.bySemanticsLabel('Clear'), findsNothing);
```

**Review by goderbauer — APPROVED** [review]
LGTM
