### PR TITLE
use FlutterError in MultiChildRenderObjectWidget

### LINKED ISSUE #37056: Passing null in array to Stack child results in unhelpful error.
I passed an array of widgets to a Stack's children property.

One of the widgets in the array was null.

The result is that the following assertion fired:

```
 MultiChildRenderObjectWidget({ Key key, this.children = const <Widget>[] })
    : assert(children != null),
      assert(() {
        final int index = children.indexOf(null);
        if (index >= 0) {
----------------------------------- The following assert fired
          throw AssertionError(
            "The widget's children must not contain any null values, but a null value was found at index $index"
          );
        }
 ```
The assertion is correct however the error printed to the console did not contain the actual assertion text as follows:

```

Syncing files to device Android SDK built for x86...
D/EGL_emulation( 9358): eglMakeCurrent: 0xebdfd2c0: ver 2 0 (tinfo 0xd511d320)
I/flutter ( 9358): [2019-07-27 11:20:35.462] [/pages/userDashboard/SendInviteDashlet.dart:12:9] ::: new SendInviteDashlet ::: Invite
I/flutter ( 9358): [2019-07-27 11:20:35.483] [/widgets/thumbMenu/ThumbMenu.dart:20:9] ::: new ThumbMenu ::: ThumbMenu
I/flutter ( 9358): [2019-07-27 11:20:35.551] [/widgets/thumbMenu/ThumbMenu.dart:41:9] ::: new ThumbMenuState ::: Providers are being added
I/flutter ( 9358): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9358): The following assertion was thrown building ThumbMenuImpl(dirty, dependencies:
I/flutter ( 9358): [_LocalizationsScope-[GlobalKey#c5e5c], _InheritedTheme, MediaQuery], state:
I/flutter ( 9358): ThumbMenuImplState#78f02):
I/flutter ( 9358): Assertion failed
I/flutter ( 9358): 
I/flutter ( 9358): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9358): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9358): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9358):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 9358): 
I/flutter ( 9358): When the exception was thrown, this was the stack:
I/flutter ( 9358): #0      new MultiChildRenderObjectWidget.<anonymous closure> (package:flutter/src/widgets/framework.dart:1691:11)
I/flutter ( 9358): #1      new MultiChildRenderObjectWidget (package:flutter/src/widgets/framework.dart:1696:8)
I/flutter ( 9358): #2      new Stack (package:flutter/src/widgets/basic.dart:3118:8)
I/flutter ( 9358): #3      ThumbMenuImplState.buildTitle (/widgets/thumbMenu/ThumbMenuImp.dart:120:16)
I/flutter ( 9358): #4      ThumbMenuImplState.build (/widgets/thumbMenu/ThumbMenuImp.dart:94:21)
I/flutter ( 9358): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
I/flutter ( 9358): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
I/flutter ( 9358): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #22     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #61     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #71     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #77     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #93     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #102    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #107    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #114    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #118    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #123    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #124    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #125    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #127    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5198:32)
I/flutter ( 9358): #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #132    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #133    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #137    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): unhandled element metadata; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#a2030(), name: "assets/icons/Training.svg", colorFilter: null)
I/flutter ( 9358): #138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #139    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #141    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #142    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #143    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #144    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #148    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #149    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #150    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #151    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #155    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #156    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #157    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #158    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #160    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #161    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #162    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #163    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #164    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #165    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #167    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #168    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #171    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #173    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #175    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #176    ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4279:11)
I/flutter ( 9358): #177    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #178    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5198:32)
I/flutter ( 9358): #179    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #180    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #181    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #182    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #183    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #184    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #185    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #186    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #187    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #189    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #190    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #191    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #192    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #193    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #194    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #195    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #196    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #197    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #198    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #199    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #200    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #201    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #202    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #203    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #205    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #206    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #207    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #208    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #209    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #210    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #212    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #213    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #214    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #215    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #216    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #217    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #218    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #219    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #221    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #222    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #223    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #224    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #225    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #226    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #227    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #228    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #229    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #230    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #231    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #232    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #233    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #234    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #235    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #236    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #237    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #238    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #239    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #240    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #241    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #242    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #243    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #244    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #245    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #246    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #247    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #248    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #249    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #250    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #251    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #252    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #253    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #254    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #255    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #256    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #257    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #258    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #259    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #260    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #261    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #262    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #263    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #264    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #265    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #266    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #267    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #268    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #269    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #270    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #271    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #272    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #273    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #274    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #275    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #276    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #277    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #278    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #279    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #280    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #281    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #282    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #283    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #284    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #285    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #286    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #287    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #288    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #289    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #290    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #291    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #292    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #293    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #294    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #295    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #296    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #297    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #298    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #299    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #300    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #301    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #302    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #303    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #304    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #305    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #306    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #307    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #308    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #309    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #310    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #311    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #312    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #313    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #314    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #315    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #316    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #317    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #318    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #319    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter ( 9358): #320    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #321    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #322    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #323    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #324    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #325    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #326    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #327    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #328    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #329    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #330    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #331    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #332    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #333    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #334    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #335    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #336    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #337    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter ( 9358): #338    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter ( 9358): #339    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter ( 9358): #340    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter ( 9358): #341    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter ( 9358): #342    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4875:32)
I/flutter ( 9358): #343    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
I/flutter ( 9358): #344    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 9358): #345    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
I/flutter ( 9358): #346    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 9358): #347    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 9358): #348    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 9358): #349    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
I/flutter ( 9358): #350    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 9358): #351    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 9358): #352    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter ( 9358): #353    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter ( 9358): #354    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter ( 9358): #358    _invoke (dart:ui/hooks.dart:236:10)
I/flutter ( 9358): #359    _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter ( 9358): (elided 3 frames from package dart:async)
I/flutter ( 9358): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 9358): Another exception was thrown: A RenderFlex overflowed by 99317 pixels on the bottom.

```

The error should include the assertion text.
The assert text should also be improved to include the count of children in the array not just the index of the null child.
The count would have lead me to the error cause much faster.

### LINKED ISSUE #37136: Assertion failed error
I have a problem with flutter and the error log suggest reporting this issue.

> I/flutter (20162): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20162): The following assertion was thrown building Post(dirty, state: _PostState#a2a2a):
I/flutter (20162): Assertion failed
I/flutter (20162):
I/flutter (20162): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20162): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20162): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20162):   https://github.com/flutter/flutter/issues/new?template=BUG.md

Due to the project being larger than one file, I uploaded it on Github([here](https://github.com/ThatsEli/drawErrorExample)). Don't wonder about the name, I used this repo before for an issue with another project :)

## Steps to Reproduce

1. Run the App
2. Login/Authenticate with reddit
3. Scroll down 

## Logs

```
[+3607 ms] I/flutter (20752): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[  +14 ms] I/flutter (20752): The following assertion was thrown building Post(dirty, state: _PostState#34fc0):
[   +2 ms] I/flutter (20752): Assertion failed
[   +2 ms] I/flutter (20752):
[   +2 ms] I/flutter (20752): Either the assertion indicates an error in the framework itself, or we should provide substantially
[   +7 ms] I/flutter (20752): more information in this error message to help you determine and fix the underlying cause.
[   +4 ms] I/flutter (20752): In either case, please report this assertion by filing a bug on GitHub:
[   +2 ms] I/flutter (20752):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[   +7 ms] I/flutter (20752):
[   +1 ms] I/flutter (20752): When the exception was thrown, this was the stack:
[   +2 ms] I/flutter (20752): #0      new MultiChildRenderObjectWidget.<anonymous closure>
(package:flutter/src/widgets/framework.dart:1691:11)
[  +10 ms] I/flutter (20752): #1      new MultiChildRenderObjectWidget (package:flutter/src/widgets/framework.dart:1696:8)
[   +2 ms] I/flutter (20752): #2      new Flex (package:flutter/src/widgets/basic.dart:3707:8)
[   +1 ms] I/flutter (20752): #3      new Column (package:flutter/src/widgets/basic.dart:4234:8)
[   +9 ms] I/flutter (20752): #4      _PostState.build (package:redditclient/widgets/post.dart:36:15)
[   +2 ms] I/flutter (20752): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
[   +1 ms] I/flutter (20752): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
[   +1 ms] I/flutter (20752): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
[   +7 ms] I/flutter (20752): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
[   +2 ms] I/flutter (20752): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
[   +2 ms] I/flutter (20752): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
[   +1 ms] I/flutter (20752): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[   +8 ms] I/flutter (20752): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +2 ms] I/flutter (20752): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
[   +3 ms] I/flutter (20752): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[  +16 ms] I/flutter (20752): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +2 ms] I/flutter (20752): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
[   +3 ms] I/flutter (20752): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[   +2 ms] I/flutter (20752): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +7 ms] I/flutter (20752): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
[   +2 ms] I/flutter (20752): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
[   +2 ms] I/flutter (20752): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
[   +9 ms] I/flutter (20752): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
[   +2 ms] I/flutter (20752): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[   +2 ms] I/flutter (20752): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +2 ms] I/flutter (20752): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
[   +9 ms] I/flutter (20752): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
[   +2 ms] I/flutter (20752): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
[   +1 ms] I/flutter (20752): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
[   +1 ms] I/flutter (20752): #29     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4279:11)
[   +8 ms] I/flutter (20752): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[   +2 ms] I/flutter (20752): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +2 ms] I/flutter (20752): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
[   +2 ms] I/flutter (20752): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
[   +7 ms] I/flutter (20752): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
[   +2 ms] I/flutter (20752): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
[   +2 ms] I/flutter (20752): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
[   +2 ms] I/flutter (20752): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[   +9 ms] I/flutter (20752): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +3 ms] I/flutter (20752): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
[   +2 ms] I/flutter (20752): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
[   +7 ms] I/flutter (20752): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
[   +1 ms] I/flutter (20752): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
[   +2 ms] I/flutter (20752): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[   +2 ms] I/flutter (20752): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +8 ms] I/flutter (20752): #45     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1181:36)
[   +2 ms] I/flutter (20752): #46     SliverMultiBoxAdaptorElement.createChild.<anonymous closure>
(package:flutter/src/widgets/sliver.dart:1166:20)
[   +3 ms] I/flutter (20752): #47     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
[   +8 ms] I/flutter (20752): #48     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1159:11)
[   +2 ms] I/flutter (20752): #49     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
[   +3 ms] I/flutter (20752): #50     RenderObject.invokeLayoutCallback.<anonymous closure>
(package:flutter/src/rendering/object.dart:1715:58)
[   +8 ms] I/flutter (20752): #51     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
[   +2 ms] I/flutter (20752): #52     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1715:13)
[   +2 ms] I/flutter (20752): #53     RenderSliverMultiBoxAdaptor._createOrObtainChild
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
[  +10 ms] I/flutter (20752): #54     RenderSliverMultiBoxAdaptor.insertAndLayoutChild
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
[   +2 ms] I/flutter (20752): #55     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:191:19)
[   +2 ms] I/flutter (20752): #56     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:234:19)
[   +2 ms] I/flutter (20752): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[   +9 ms] I/flutter (20752): #58     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
[   +2 ms] I/flutter (20752): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[   +2 ms] I/flutter (20752): #60     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
[   +9 ms] I/flutter (20752): #61     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
[   +2 ms] I/flutter (20752): #62     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
[   +1 ms] I/flutter (20752): #63     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
[   +2 ms] I/flutter (20752): #64     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
[   +7 ms] I/flutter (20752): #65
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.dra
wFrame (package:flutter/src/rendering/binding.dart:346:19)
[   +3 ms] I/flutter (20752): #66
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&Wid
getsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
[  +14 ms] I/flutter (20752): #67
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._ha
ndlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
[   +3 ms] I/flutter (20752): #68
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1016:15)
[   +2 ms] I/flutter (20752): #69
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:958:9)
[   +9 ms] I/flutter (20752): #70
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:874:5)
[   +3 ms] I/flutter (20752): #74     _invoke (dart:ui/hooks.dart:236:10)
[   +1 ms] I/flutter (20752): #75     _drawFrame (dart:ui/hooks.dart:194:3)
[  +13 ms] I/flutter (20752): (elided 3 frames from package dart:async)
[   +3 ms] I/flutter (20752): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
Analyzing redditclient...
No issues found! (ran in 3.5s)
```

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.885], locale de-DE)
    • Flutter version 1.7.8+hotfix.4 at C:\Users\Elias\Documents\develop\flutter
    • Framework revision 20e59316b8 (9 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\Elias\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • ONEPLUS A5010 • 192.168.179.134:5556 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

Throw `FlutterError` instead of `AssertionError` whose `toString()` doesn't provide any insight of what caused the framework to assert.

Now the error message should read:
> I/flutter ( 4170): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4170): The following assertion was thrown building TestPage(dirty, state: _TestPageState#a4aee):
I/flutter ( 4170): Column's children must not contain any null values, but a null value was found at index 0
I/flutter ( 4170):
I/flutter ( 4170): User-created ancestor of the error-causing widget was:
I/flutter ( 4170):   MaterialApp org-dartlang-app:/main.dart:55:12

## Related Issues

Fixes https://github.com/flutter/flutter/issues/37136
Fixes https://github.com/flutter/flutter/issues/37056
and many others

## Tests

I added the following tests:

- provides useful assertion message when one of the children is null

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/widgets/multichild_test.dart [hunk 1]
```diff
@@ -345,4 +352,17 @@ void main() {
 
     checkTree(tester, <BoxDecoration>[kBoxDecorationB, kBoxDecorationC]);
   });
+
+  // Regression test for https://github.com/flutter/flutter/issues/37136.
```
Comment (Piinks) [inline packages/flutter/test/widgets/multichild_test.dart]: I've noticed this pattern in a number of recent pull requests. Does the style guide specify referencing issue for tests?

**Review by Piinks — APPROVED** [review]
LGTM!

File: packages/flutter/test/widgets/multichild_test.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/multichild_test.dart]: Did a quick search in the wiki, wasn't able to find anything related. But I vaguely remember being told once to add this line in a PR. Search for `regression test` in the codebase yields 150 matches, so I guess it's probably a undocumented convention?

File: packages/flutter/lib/src/widgets/framework.dart [hunk 2]
```diff
@@ -1688,8 +1688,9 @@ abstract class MultiChildRenderObjectWidget extends RenderObjectWidget {
       assert(() {
         final int index = children.indexOf(null);
         if (index >= 0) {
-          throw AssertionError(
-            "The widget's children must not contain any null values, but a null value was found at index $index"
+          throw FlutterError(
+            "$runtimeType's children must not contain any null values, "
+            'but a null value was found at index $index'
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/framework.dart]: NICE

File: packages/flutter/test/widgets/multichild_test.dart [hunk 3]
```diff
@@ -31,6 +31,13 @@ void checkTree(WidgetTester tester, List<BoxDecoration> expectedDecorations) {
   }
 }
 
+class MockMultiChildRenderObjectWidget extends MultiChildRenderObjectWidget {
+  MockMultiChildRenderObjectWidget({Key key, List<Widget> children}) : super(key: key, children: children);
```
Comment (HansMuller) [inline packages/flutter/test/widgets/multichild_test.dart]: `( {Key key, List<Widget> children} )`

**Review by HansMuller — APPROVED** [review]
LGTM
