### PR TITLE
Relax syntax for gen-l10n

### LINKED ISSUE #122404: [gen-l10n] Escaping curly braces without use-escaping
Hello! We have a very big Flutter project and we use a translation management service for all our terms and languages. After upgrading from Flutter 3.3 to 3.7 some of our terms started to fail on parse. Below is the minimum example for that:

```
➜  arb_curly_brace_escape flutter --version
Flutter 3.7.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12cb4eb7a0 (9 days ago) • 2023-03-01 10:29:26 -0800
Engine • revision ada363ee93
Tools • Dart 2.19.3 • DevTools 2.20.1

➜  arb_curly_brace_escape cat lib/l10n/app_en.arb
{
    "test": "You shouldn't use those characters: { } in this field"
}

➜  arb_curly_brace_escape flutter gen-l10n
Because l10n.yaml exists, the options defined there will be used instead.
To use the command line arguments, delete the l10n.yaml file in the Flutter project.


[app_en.arb:test] ICU Syntax Error: Expected "identifier" but found "}".
    You shouldn't use those characters: { } in this field
                                          ^
Found syntax errors.
```
Right now we cannot use curly braces in our terms literally, without being parsed as placeholders.

There is the `use-escaping` param in `l10n.yaml`, but this requires changing almost every term where a `'` character is used and educating (which won't always work so there's additional QA needed) our translators to escape single quotes.

For us, that is a major regression.

---

IMO, if a term uses the `{placeholder}` syntax, but has no `placeholder` in its `@termName.placeholders` defined, it shouldn't be treated and parsed (and thus fail to do so) as a placeholder. But that's just one of the solutions.

### PR DESCRIPTION
**Pull request by thkim1011**
To preserve backward compatibility with the old parser which would ignore syntax errors, this PR introduces a way to treat the special characters `{` and `}` in the following way:
1. If we encounter a `{` which searching for a string token and this `{` is not followed by a valid placeholder, then we treat the `{` as a string and continue lexing for strings.
2. If we encounter a `}` while not within some expression (i.e. placeholders, arguments, plurals, or selects), then we treat the `}` as a string and continue lexing for strings.

This makes it so that
```
"helloWorld": "{ } { placeholder }",
"@@helloWorld": {
  "placeholders": {
    "placeholder" {}
  }
}
```
treats the `{ }` as a string while `{ placeholder } ` is treated as a placeholder.

Fixes https://github.com/flutter/flutter/issues/122404.

### CODE REVIEW

File: packages/flutter_tools/lib/src/localizations/message_parser.dart [hunk 1]
```diff
@@ -267,9 +273,28 @@ class Parser {
...
+            if (matchedBrace == '{' && (identifierMatch == null || !placeholders!.contains(identifierMatch.group(0)))) {
+              tokens.add(Node.string(startIndex, matchedBrace));
+              startIndex = match.end;
+              continue;
+            }
+          }
           tokens.add(Node.brace(startIndex, match.group(0)!));
           isString = false;
           startIndex = match.end;
+          depth++;
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/localizations/message_parser.dart:297]: `depth += 1` is preferred because no one remembers PDP-11s anymore :-).

File: packages/flutter_tools/lib/src/commands/generate_localizations.dart [hunk 2]
```diff
@@ -200,6 +200,11 @@ class GenerateLocalizationsCommand extends FlutterCommand {
       'suppress-warnings',
       help: 'When specified, all warnings will be suppressed.\n'
     );
+    argParser.addFlag(
+      'relax-syntax',
+      help: 'When specified, some instances of "{" and "}" will be treated as strings '
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/commands/generate_localizations.dart:205]: It would be better to explain this more precisely.

**Review by HansMuller — COMMENTED** [review]
This looks good! Some presubmit tests are failing though.

File: packages/flutter_tools/lib/src/commands/generate_localizations.dart [hunk 3]
```diff
@@ -200,6 +200,13 @@ class GenerateLocalizationsCommand extends FlutterCommand {
       'suppress-warnings',
       help: 'When specified, all warnings will be suppressed.\n'
     );
+    argParser.addFlag(
+      'relax-syntax',
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/commands/generate_localizations.dart:204]: NICE

File: packages/flutter_tools/lib/src/localizations/localizations_utils.dart [hunk 4]
```diff
@@ -455,6 +457,11 @@ class LocalizationOptions {
   ///
   /// Whether or not to suppress warnings.
   final bool suppressWarnings;
+
+  /// The `relax-syntax` argument.
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/localizations/localizations_utils.dart:461]: You should incorporate the text from the help message here.

It would also be worth explaining here and in the help message that `relax-syntax` was added for backwards compatibility with an a earlier version of the parser and that we don't advising using it because it can mask errors.

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/localizations/localizations_utils.dart (hunk 4 above)
Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/localizations_utils.dart:461]: Done!

**Comment by devxpy** [comment]
backwards compatibility for non major version changes should be the default behaviour
