### PR TITLE
Fix DropdownMenu does not apply opacity to the selected value when disabled

### LINKED ISSUE #169942: DropdownMenu does not apply opacity to the selected value when disabled
### Steps to reproduce

1. Press the floating action button to change the field's state from enabled to disabled

### Expected results

Labels have a 38% opacity according to the material design guidelines: https://m3.material.io/components/menus/specs#c811d2fa-469a-4e4e-9d9f-0f535c5c9b4c

### Actual results

The opacity of the `Textfield` text has changed, while the `DropdownMenu` label has not

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final TextEditingController textEditingController = TextEditingController(
    text: 'One',
  );
  bool enabled = true;

  void _disable() {
    setState(() {
      enabled = !enabled;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Padding(
          padding: EdgeInsets.all(24),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              DropdownMenu<String>(
                width: double.infinity,
                enabled: enabled,
                initialSelection: 'One',
                dropdownMenuEntries: [
                  DropdownMenuEntry(value: 'One', label: 'One'),
                ],
              ),
              TextField(controller: textEditingController, enabled: enabled),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _disable,
        tooltip: 'Update dropdown',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.1, on macOS 15.5 24F74 darwin-arm64, locale en-UA) [680ms]
    • Flutter version 3.32.1 on channel stable at /Users/user/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b25305a883 (5 days ago), 2025-05-29 10:40:06 -0700
    • Engine revision 1425e5e9ec
    • Dart version 3.8.1
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2.5s]
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [2.6s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [11ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [11ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)

[✓] Connected device (4 available) [6.9s]
    • Yurii’s iPhone (wireless) (mobile) • 00008030-0016551C1450402E            • ios            • iOS 18.4.1 22E252
    • iPhone 16 (mobile)                 • 4EEC28AE-FBC1-4565-A1E4-1A45C36D4213 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-5 (simulator)
    • macOS (desktop)                    • macos                                • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 136.0.7103.114

[✓] Network resources [374ms]
    • All expected network resources are available.

```

</details>

### PR DESCRIPTION
**Pull request by huycozy**
Fix https://github.com/flutter/flutter/issues/169942

### Description

The bug is about the [effectiveTextStyle](https://github.com/flutter/flutter/blob/b086fe7b79b80a9567f61660b1565efba773fdc3/packages/flutter/lib/src/material/dropdown_menu.dart#L979) being applied to the inner [TextField](https://github.com/flutter/flutter/blob/b086fe7b79b80a9567f61660b1565efba773fdc3/packages/flutter/lib/src/material/dropdown_menu.dart#L1049) inside DropdownMenu fails to reflect the disabled style based on the [enabled property](https://github.com/flutter/flutter/blob/b086fe7b79b80a9567f61660b1565efba773fdc3/packages/flutter/lib/src/material/dropdown_menu.dart#L209).
The fix for this is simply to check the `enabled` property and override the TextField's TextStyle.

### Demo of the fix

| before | after |
| --------------- | --------------- |
<video src="https://github.com/user-attachments/assets/0c56577b-301a-4369-bb1c-280643521cab"/> | <video src="https://github.com/user-attachments/assets/7e806fc7-4b90-49e5-b91b-8779454c8e60"/>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 1]
```diff
@@ -976,7 +976,12 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
       useMaterial3: useMaterial3,
     );
 
-    final TextStyle? effectiveTextStyle = widget.textStyle ?? theme.textStyle ?? defaults.textStyle;
+    final TextStyle? baseTextStyle = widget.textStyle ?? theme.textStyle ?? defaults.textStyle;
+    final Color disabledColor = Theme.of(context).colorScheme.onSurface.withOpacity(0.38);
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/dropdown_menu.dart]: With this change, seems we are not able to customize disabled color. I think we can add a `bool enabled` property in `_DropdownMenuDefaultsM3` and provide this value as the default value when `DropdownMenu` is disabled. Does this make sense?

Comment (huycozy) [reply packages/flutter/lib/src/material/dropdown_menu.dart]: If we provide customization ability, I think it's better to do it in `DropdownMenuThemeData` by adding a `disabledColor` property there. IMHO, `enabled` property is to control widget's behavior, not its appearance and it's already existing in DropdownMenu's properties. `_DropdownMenuDefaultsM3` is designed to provide styling defaults, not to handle runtime states. If users want to change the default disabled color, let's do it via the theme. Please check out my last commit and let me know if it's fine.

**Review by QuncCccccc — APPROVED** [review]
Adding it in DropdownMenu theme sounds better. Thank you! LGTM.
