### PR TITLE
Point "flutter build ipa --analyze-size" to archive app output

### LINKED ISSUE #77571: [tool_crash] flutter build ipa fails with FileSystemException
## command

flutter build ipa --analyze-size --build-number=24

## exception

FileSystemException: FileSystemException: Directory listing failed, path = 'build/ios/Release-iphoneos/' (OS Error: No such file or directory, errno = 2)

```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:278:57)
<asynchronous suspension>
#5      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:111:50)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#19     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.2 20D80 darwin-arm, locale en-CH)
    • Flutter version 2.0.1 at /Users/eliabieri/git/flutter/flutter
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/eliabieri/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • B336ECD5-6A6D-4924-922F-5DA468C09897 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 88.0.4324.192
    ! Error: WG is not connected. Xcode will continue when WG is connected. (code -13)

• No issues found!
```

### LINKED ISSUE #78231: _BuildIOSSubCommand.runCommand StateError: Bad state: No element
Reported by @eliabieri in https://github.com/flutter/flutter/issues/77571#issuecomment-797898707

## command

flutter build ipa --analyze-size --build-number=24 --verbose

## exception

StateError: Bad state: No element

```
#0      Iterable.firstWhere (dart:core/iterable.dart:516:5)
#1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:280:10)
<asynchronous suspension>
#2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:111:50)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#16     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.3 20D91 darwin-arm, locale en-CH)
    • Flutter version 2.0.1 at /Users/eliabieri/git/flutter/flutter
    • Framework revision c5a4b4029c (9 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/eliabieri/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B336ECD5-6A6D-4924-922F-5DA468C09897 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.82
    ! Error: WG is not connected. Xcode will continue when WG is connected. (code -13)

• No issues found!
```

### PR DESCRIPTION
**Pull request by jmagman**
1. Fix `flutter build ipa --analyze-size` to analyze `build/ios/archive/*.xcarchive/Products/Applications/*.app` (fixes the crash).
2. Instead of `flutter build ios --analyze-size` analyzing `build/ios/Release-iphoneos/*app`, instead analyze at `build/ios/iphoneos/*app` to avoid knowing anything about the `Release-iphoneos` path.  The command already enforces that analyzing the size requires release mode (added a test confirming that).
3. Create command-level test of `build_ios_test.dart` based on `build_ipa_test.dart`.

Validated both `flutter build ipa --analyze-size` and `flutter build ios --analyze-size` work after respective `flutter clean`s.

Fixes https://github.com/flutter/flutter/issues/77571
Fixes https://github.com/flutter/flutter/issues/78231

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/build_ios.dart [hunk 1]
```diff
@@ -273,16 +284,19 @@ abstract class _BuildIOSSubCommand extends BuildSubCommand {
...
-      final Directory appDirectory = candidateDirectory.listSync()
-        .whereType<Directory>()
-        .firstWhere((Directory directory) {
-        return globals.fs.path.extension(directory.path) == '.app';
-      });
+      final Directory outputAppDirectoryCandidate = _outputAppDirectory(result.output);
+
+      Directory appDirectory;
+      if (outputAppDirectoryCandidate.existsSync()) {
+        appDirectory = outputAppDirectoryCandidate.listSync()
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/build_ios.dart:291]: Fun fact, with null safety enabled this pattern isn't allowed anymore.

**Review by jonahwilliams — APPROVED** [review]
LGTM!
