### PR TITLE
Fix local gold output for flutter/flutter

### LINKED ISSUE #66072: Gold failure locally does not show images
Steps:

in `packages/flutter/test/widgets/image_test.dart`, modify `kBlueSquarePng` to something like `kTransparent`, and run the tests. The gold failures are expected, but I would have thought there would be some output telling me where to find failures.

/cc @Piinks 

Logs:

```
00:04 +45: Rotated images                                                                                                                                                                                                                                                                           
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: one widget whose rasterized image matches golden image "rotated_image_aa.png"
  Actual: _KeyFinder:<exactly one widget with key [#f8bdb] (ignoring offstage widgets):
RepaintBoundary-[#f8bdb](renderObject: RenderRepaintBoundary#e582e)>
   Which: does not match

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/frontend/expect.dart:155:31)
#1      _expect.<anonymous closure> (package:test_api/src/frontend/expect.dart:130:9)
#13     MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart)
<asynchronous suspension>
#14     MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart)
#15     AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:1010:22)
#18     AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:1008:26)
#19     MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:72:20)
#20     _expect (package:test_api/src/frontend/expect.dart:119:26)
#21     expectLater (package:test_api/src/frontend/expect.dart:75:5)
#22     expectLater (package:flutter_test/src/widget_tester.dart:468:10)
#23     main._testRotatedImage (file:///Users/dnfield/src/flutter/flutter/packages/flutter/test/widgets/image_test.dart:1706:11)
#34     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:193:32)
#35     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1199:19)
(elided 35 frames from dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  Rotated images
════════════════════════════════════════════════════════════════════════════════════════════════════
00:04 +45 -1: Rotated images [E]                                                                                                                                                                                                                                                                    
  Test failed. See exception logs above.
  The test description was: Rotated images
  
00:04 +46 -1: Some tests failed.     
```

### PR DESCRIPTION
**Pull request by Piinks**
## Description

This fixes a local output bug for golden file testing that was only affecting the flutter repository.
I thought this may have been introduced by https://github.com/flutter/flutter/pull/64982/files, but it looks like that change may have just exposed it.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/66072

## Tests

Not certain yet how to test this.. I would have thought it would be covered by https://github.com/flutter/flutter/blob/78929661fbdb5fb56bf032c0958a020cb615838f/packages/flutter_goldens/test/flutter_goldens_test.dart#L935

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Piinks** [comment]
@goderbauer I am wondering how to test this. I remember we came up with this while back https://github.com/flutter/flutter/blob/78929661fbdb5fb56bf032c0958a020cb615838f/packages/flutter_goldens/test/flutter_goldens_test.dart#L935 but that did not seem to catch this. WDYT?

**Comment by Piinks** [comment]
FYI @dnfield :) Thanks for spotting this.

File: packages/flutter_goldens/lib/flutter_goldens.dart [hunk 1]
```diff
@@ -670,7 +670,7 @@ class FlutterLocalFileComparator extends FlutterGoldenFileComparator with LocalC
     if (result.passed)
       return true;
 
-    generateFailureOutput(result, golden, basedir);
+    await generateFailureOutput(result, golden, basedir);
```
Comment (dnfield) [inline packages/flutter_goldens/lib/flutter_goldens.dart:673]: You can use TestAsyncUtild.giard for the method being called here and it will throw if you fail to await

Comment (Piinks) [reply packages/flutter_goldens/lib/flutter_goldens.dart:673]: Thanks @dnfield!

**Comment by Piinks** [comment]
Applied your suggestion @dnfield, thanks again! PTAL. :)

File: packages/flutter_test/lib/src/_goldens_io.dart [hunk 2]
```diff
@@ -126,32 +129,31 @@ class LocalComparisonOutput {
...
-        final File output = getFailureFile(
-          key.isEmpty ? entry.key : entry.key + '_' + key,
-          golden,
-          basedir,
-        );
-        output.parent.createSync(recursive: true);
-        final ByteData? pngBytes =
-            await entry.value.toByteData(format: ImageByteFormat.png);
-        output.writeAsBytesSync(pngBytes!.buffer.asUint8List());
+    return TestAsyncUtils.guard<String>(() async {
```
Comment (dnfield) [inline packages/flutter_test/lib/src/_goldens_io.dart:138]: uber nit: this can be combined with the above line as

```dart
  }) => TestAsyncUtils.guard<String>(() async {
```

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by Piinks** [comment]
Ack, it looks like this is blocked by NNDB migration. `test_async_utils.dart` does not use NNDB, but the goldens have already been migrated.

**Comment by dnfield** [comment]
I'd ask in #hackers-nnbd about what to do about that

**Comment by goderbauer** [comment]
PR triage: This one is blocked on flutter_test migrating to NNBD.

**Comment by Piinks** [comment]
This should be unblocked now. :)
