### PR TITLE
Compare SemanticsHandler# at end of test to value at beginning of test

### LINKED ISSUE #18015: "A SemanticsHandle was active at the end of the test" for even the simplest of tests
## Steps to Reproduce

1. Create a new Flutter project with the incrementer app
2. Verify the test passes when run through `flutter test`
2. Then, `flutter run test/widget_test.dart` (e.g. in the iOS Simulator)

Test fails with "The following assertion was thrown running a test: A SemanticsHandle was active at the end of the test."

The test itself doesn't touch Semantics at all, nor does the sample app. That makes it very confusing.

## Logs

```
$ flutter run --verbose test/widget_test.dart
[  +27 ms] [/Users/filiph/dev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [/Users/filiph/dev/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [/Users/filiph/dev/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/filiph/dev/flutter/] git log -n 1 --pretty=format:%H
[  +14 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] f9bb4289e9fd861d70ae78bcc3a042ef1b35cc9d
[        ] [/Users/filiph/dev/flutter/] git log -n 1 --pretty=format:%ar
[   +6 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 weeks ago
[        ] [/Users/filiph/dev/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +25 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.4.4-0-gf9bb4289e
[+1417 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +60 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[ +113 ms] /Users/filiph/Library/Android/sdk/platform-tools/adb devices -l
[  +13 ms] Exit code 0 from: /Users/filiph/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +4 ms] idevice_id -h
[ +260 ms] /usr/bin/xcrun simctl list --json devices
[ +912 ms] Launching test/widget_test.dart on iPhone X in debug mode...
[   +1 ms] /usr/bin/defaults read /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/Info CFBundleIdentifier
[  +61 ms] Exit code 0 from: /usr/bin/defaults read /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/Info CFBundleIdentifier
[        ] $(PRODUCT_BUNDLE_IDENTIFIER)
[        ] [ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner.xcodeproj -target Runner -showBuildSettings
[ +856 ms] Exit code 0 from: /usr/bin/xcodebuild -project /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner.xcodeproj -target Runner -showBuildSettings
[        ] Build settings for action build and target Runner:
               ACTION = build
               AD_HOC_CODE_SIGNING_ALLOWED = NO
               ALTERNATE_GROUP = eng
               ALTERNATE_MODE = u+w,go-w,a+rX
               ALTERNATE_OWNER = filiph
               ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO
               ALWAYS_SEARCH_USER_PATHS = NO
               ALWAYS_USE_SEPARATE_HEADERMAPS = NO
               APPLE_INTERNAL_DEVELOPER_DIR = /AppleInternal/Developer
               APPLE_INTERNAL_DIR = /AppleInternal
               APPLE_INTERNAL_DOCUMENTATION_DIR = /AppleInternal/Documentation
               APPLE_INTERNAL_LIBRARY_DIR = /AppleInternal/Library
               APPLE_INTERNAL_TOOLS = /AppleInternal/Developer/Tools
               APPLICATION_EXTENSION_API_ONLY = NO
               APPLY_RULES_IN_COPY_FILES = NO
               ARCHS = arm64
               ARCHS_STANDARD = armv7 arm64
               ARCHS_STANDARD_32_64_BIT = armv7 arm64
               ARCHS_STANDARD_32_BIT = armv7
               ARCHS_STANDARD_64_BIT = arm64
               ARCHS_STANDARD_INCLUDING_64_BIT = armv7 arm64
               ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
               ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
               AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator
               BITCODE_GENERATION_MODE = marker
               BUILD_ACTIVE_RESOURCES_ONLY = NO
               BUILD_COMPONENTS = headers build
               BUILD_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios
               BUILD_ROOT = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios
               BUILD_STYLE =
               BUILD_VARIANTS = normal
               BUILT_PRODUCTS_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Release-iphoneos
               CACHE_ROOT = /var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/C/com.apple.DeveloperTools/9.4-9F1027a/Xcode
               CCHROOT = /var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/C/com.apple.DeveloperTools/9.4-9F1027a/Xcode
               CHMOD = /bin/chmod
               CHOWN = /usr/sbin/chown
               CLANG_ANALYZER_NONNULL = YES
               CLANG_CXX_LANGUAGE_STANDARD = gnu++0x
               CLANG_CXX_LIBRARY = libc++
               CLANG_ENABLE_MODULES = YES
               CLANG_ENABLE_OBJC_ARC = YES
               CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
               CLANG_WARN_BOOL_CONVERSION = YES
               CLANG_WARN_COMMA = YES
               CLANG_WARN_CONSTANT_CONVERSION = YES
               CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR
               CLANG_WARN_EMPTY_BODY = YES
               CLANG_WARN_ENUM_CONVERSION = YES
               CLANG_WARN_INFINITE_RECURSION = YES
               CLANG_WARN_INT_CONVERSION = YES
               CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
               CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
               CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR
               CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
               CLANG_WARN_STRICT_PROTOTYPES = YES
               CLANG_WARN_SUSPICIOUS_MOVE = YES
               CLANG_WARN_UNREACHABLE_CODE = YES
               CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
               CLASS_FILE_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/JavaClasses
               CLEAN_PRECOMPS = YES
               CLONE_HEADERS = NO
               CODESIGNING_FOLDER_PATH = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Release-iphoneos/Runner.app
               CODE_SIGNING_ALLOWED = YES
               CODE_SIGNING_REQUIRED = YES
               CODE_SIGN_CONTEXT_CLASS = XCiPhoneOSCodeSignContext
               CODE_SIGN_IDENTITY = iPhone Developer
               CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
               COLOR_DIAGNOSTICS = NO
               COMBINE_HIDPI_IMAGES = NO
               COMPILER_INDEX_STORE_ENABLE = Default
               COMPOSITE_SDK_DIRS = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/CompositeSDKs
               COMPRESS_PNG_FILES = YES
               CONFIGURATION = Release
               CONFIGURATION_BUILD_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Release-iphoneos
               CONFIGURATION_TEMP_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos
               CONTENTS_FOLDER_PATH = Runner.app
               COPYING_PRESERVES_HFS_DATA = NO
               COPY_HEADERS_RUN_UNIFDEF = NO
               COPY_PHASE_STRIP = NO
               COPY_RESOURCES_FROM_STATIC_FRAMEWORKS = YES
               CORRESPONDING_SIMULATOR_PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               CORRESPONDING_SIMULATOR_PLATFORM_NAME = iphonesimulator
               CORRESPONDING_SIMULATOR_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk
               CORRESPONDING_SIMULATOR_SDK_NAME = iphonesimulator11.4
               CP = /bin/cp
               CREATE_INFOPLIST_SECTION_IN_BINARY = NO
               CURRENT_ARCH = arm64
               CURRENT_PROJECT_VERSION = 1
               CURRENT_VARIANT = normal
               DEAD_CODE_STRIPPING = YES
               DEBUGGING_SYMBOLS = YES
               DEBUG_INFORMATION_FORMAT = dwarf-with-dsym
               DEFAULT_COMPILER = com.apple.compilers.llvm.clang.1_0
               DEFAULT_KEXT_INSTALL_PATH = /System/Library/Extensions
               DEFINES_MODULE = NO
               DEPLOYMENT_LOCATION = NO
               DEPLOYMENT_POSTPROCESSING = NO
               DEPLOYMENT_TARGET_CLANG_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_CLANG_FLAG_NAME = miphoneos-version-min
               DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX = -miphoneos-version-min=
               DEPLOYMENT_TARGET_SETTING_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_SUGGESTED_VALUES = 8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4
               DERIVED_FILES_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DERIVED_FILE_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DERIVED_SOURCES_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               DEVELOPER_FRAMEWORKS_DIR = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_FRAMEWORKS_DIR_QUOTED = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/Developer/Library
               DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Tools
               DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               DEVELOPMENT_LANGUAGE = English
               DOCUMENTATION_FOLDER_PATH = Runner.app/English.lproj/Documentation
               DO_HEADER_SCANNING_IN_JAM = NO
               DSTROOT = /tmp/Runner.dst
               DT_TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               DWARF_DSYM_FILE_NAME = Runner.app.dSYM
               DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
               DWARF_DSYM_FOLDER_PATH = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Release-iphoneos
               EFFECTIVE_PLATFORM_NAME = -iphoneos
               EMBEDDED_CONTENT_CONTAINS_SWIFT = NO
               EMBEDDED_PROFILE_NAME = embedded.mobileprovision
               EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE = NO
               ENABLE_BITCODE = NO
               ENABLE_DEFAULT_HEADER_SEARCH_PATHS = YES
               ENABLE_HEADER_DEPENDENCIES = YES
               ENABLE_NS_ASSERTIONS = NO
               ENABLE_ON_DEMAND_RESOURCES = YES
               ENABLE_STRICT_OBJC_MSGSEND = YES
               ENABLE_TESTABILITY = NO
               ENTITLEMENTS_ALLOWED = YES
               ENTITLEMENTS_REQUIRED = YES
               EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS = .DS_Store .svn .git .hg CVS
               EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES = *.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj
               EXECUTABLES_FOLDER_PATH = Runner.app/Executables
               EXECUTABLE_FOLDER_PATH = Runner.app
               EXECUTABLE_NAME = Runner
               EXECUTABLE_PATH = Runner.app/Runner
               EXPANDED_CODE_SIGN_IDENTITY =
               EXPANDED_CODE_SIGN_IDENTITY_NAME =
               EXPANDED_PROVISIONING_PROFILE =
               FILE_LIST = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects/LinkFileList
               FIXED_FILES_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/FixedFiles
               FLUTTER_APPLICATION_PATH = /Users/filiph/dev/reactive_exploration/hello_world_start
               FLUTTER_BUILD_DIR = build
               FLUTTER_BUILD_MODE = debug
               FLUTTER_FRAMEWORK_DIR = /Users/filiph/dev/flutter/bin/cache/artifacts/engine/ios
               FLUTTER_ROOT = /Users/filiph/dev/flutter
               FLUTTER_TARGET = lib/main.dart
               FRAMEWORKS_FOLDER_PATH = Runner.app/Frameworks
               FRAMEWORK_FLAG_PREFIX = -framework
               FRAMEWORK_SEARCH_PATHS =  /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter
               FRAMEWORK_VERSION = A
               FULL_PRODUCT_NAME = Runner.app
               GCC3_VERSION = 3.3
               GCC_C_LANGUAGE_STANDARD = gnu99
               GCC_INLINES_ARE_PRIVATE_EXTERN = YES
               GCC_NO_COMMON_BLOCKS = YES
               GCC_PFE_FILE_C_DIALECTS = c objective-c c++ objective-c++
               GCC_SYMBOLS_PRIVATE_EXTERN = YES
               GCC_THUMB_SUPPORT = YES
               GCC_TREAT_WARNINGS_AS_ERRORS = NO
               GCC_VERSION = com.apple.compilers.llvm.clang.1_0
               GCC_VERSION_IDENTIFIER = com_apple_compilers_llvm_clang_1_0
               GCC_WARN_64_TO_32_BIT_CONVERSION = YES
               GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR
               GCC_WARN_UNDECLARED_SELECTOR = YES
               GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE
               GCC_WARN_UNUSED_FUNCTION = YES
               GCC_WARN_UNUSED_VARIABLE = YES
               GENERATE_MASTER_OBJECT_FILE = NO
               GENERATE_PKGINFO_FILE = YES
               GENERATE_PROFILING_CODE = NO
               GENERATE_TEXT_BASED_STUBS = NO
               GID = 5000
               GROUP = eng
               HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT = YES
               HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES = YES
               HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS = YES
               HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
               HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
               HEADERMAP_USES_VFS = NO
               HIDE_BITCODE_SYMBOLS = YES
               HOME = /Users/filiph
               ICONV = /usr/bin/iconv
               INFOPLIST_EXPAND_BUILD_SETTINGS = YES
               INFOPLIST_FILE = Runner/Info.plist
               INFOPLIST_OUTPUT_FORMAT = binary
               INFOPLIST_PATH = Runner.app/Info.plist
               INFOPLIST_PREPROCESS = NO
               INFOSTRINGS_PATH = Runner.app/English.lproj/InfoPlist.strings
               INLINE_PRIVATE_FRAMEWORKS = NO
               INSTALLHDRS_COPY_PHASE = NO
               INSTALLHDRS_SCRIPT_PHASE = NO
               INSTALL_DIR = /tmp/Runner.dst/Applications
               INSTALL_GROUP = eng
               INSTALL_MODE_FLAG = u+w,go-w,a+rX
               INSTALL_OWNER = filiph
               INSTALL_PATH = /Applications
               INSTALL_ROOT = /tmp/Runner.dst
               IPHONEOS_DEPLOYMENT_TARGET = 8.0
               JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8
               JAVA_APP_STUB = /System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               JAVA_ARCHIVE_CLASSES = YES
               JAVA_ARCHIVE_TYPE = JAR
               JAVA_COMPILER = /usr/bin/javac
               JAVA_FOLDER_PATH = Runner.app/Java
               JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
               JAVA_JAR_FLAGS = cv
               JAVA_SOURCE_SUBDIR = .
               JAVA_USE_DEPENDENCIES = YES
               JAVA_ZIP_FLAGS = -urg
               JIKES_DEFAULT_FLAGS = +E +OLDCSO
               KASAN_DEFAULT_CFLAGS = -DKASAN=1 -fsanitize=address -mllvm -asan-globals-live-support -mllvm -asan-force-dynamic-shadow
               KEEP_PRIVATE_EXTERNS = NO
               LD_DEPENDENCY_INFO_FILE = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat
               LD_GENERATE_MAP_FILE = NO
               LD_MAP_FILE_PATH = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/Runner-LinkMap-normal-arm64.txt
               LD_NO_PIE = NO
               LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
               LD_RUNPATH_SEARCH_PATHS =  @executable_path/Frameworks
               LEGACY_DEVELOPER_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               LEX = lex
               LIBRARY_FLAG_NOSPACE = YES
               LIBRARY_FLAG_PREFIX = -l
               LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
               LIBRARY_SEARCH_PATHS =  /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter
               LINKER_DISPLAYS_MANGLED_NAMES = NO
               LINK_FILE_LIST_normal_arm64 =
               LINK_WITH_STANDARD_LIBRARIES = YES
               LOCALIZABLE_CONTENT_DIR =
               LOCALIZED_RESOURCES_FOLDER_PATH = Runner.app/English.lproj
               LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString CFLocalizedString
               LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
               LOCAL_APPS_DIR = /Applications
               LOCAL_DEVELOPER_DIR = /Library/Developer
               LOCAL_LIBRARY_DIR = /Library
               LOCROOT =
               LOCSYMROOT =
               MACH_O_TYPE = mh_execute
               MAC_OS_X_PRODUCT_BUILD_VERSION = 17E202
               MAC_OS_X_VERSION_ACTUAL = 101304
               MAC_OS_X_VERSION_MAJOR = 101300
               MAC_OS_X_VERSION_MINOR = 1304
               METAL_LIBRARY_FILE_BASE = default
               METAL_LIBRARY_OUTPUT_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Release-iphoneos/Runner.app
               MODULE_CACHE_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               MTL_ENABLE_DEBUG_INFO = NO
               NATIVE_ARCH = armv7
               NATIVE_ARCH_32_BIT = i386
               NATIVE_ARCH_64_BIT = x86_64
               NATIVE_ARCH_ACTUAL = x86_64
               NO_COMMON = YES
               OBJECT_FILE_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects
               OBJECT_FILE_DIR_normal = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects-normal
               OBJROOT = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios
               ONLY_ACTIVE_ARCH = NO
               OS = MACOS
               OSAC = /usr/bin/osacompile
               PACKAGE_TYPE = com.apple.package-type.wrapper.application
               PASCAL_STRINGS = YES
               PATH = /Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin
               PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES = /usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms
               PBDEVELOPMENTPLIST_PATH = Runner.app/pbdevelopment.plist
               PFE_FILE_C_DIALECTS = objective-c
               PKGINFO_FILE_PATH = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/PkgInfo
               PKGINFO_PATH = Runner.app/PkgInfo
               PLATFORM_DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Applications
               PLATFORM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin
               PLATFORM_DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
               PLATFORM_DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
               PLATFORM_DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Tools
               PLATFORM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr
               PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               PLATFORM_DISPLAY_NAME = iOS
               PLATFORM_NAME = iphoneos
               PLATFORM_PREFERRED_ARCH = arm64
               PLATFORM_PRODUCT_BUILD_VERSION = 15F79
               PLIST_FILE_OUTPUT_FORMAT = binary
               PLUGINS_FOLDER_PATH = Runner.app/PlugIns
               PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR = YES
               PRECOMP_DESTINATION_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/PrefixHeaders
               PRESERVE_DEAD_CODE_INITS_AND_TERMS = NO
               PREVIEW_DART_2 = true
               PRIVATE_HEADERS_FOLDER_PATH = Runner.app/PrivateHeaders
               PRODUCT_BUNDLE_IDENTIFIER = hello_world.flutter.io.helloWorldStart
               PRODUCT_MODULE_NAME = Runner
               PRODUCT_NAME = Runner
               PRODUCT_SETTINGS_PATH = /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/Info.plist
               PRODUCT_TYPE = com.apple.product-type.application
               PROFILING_CODE = NO
               PROJECT = Runner
               PROJECT_DERIVED_FILE_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/DerivedSources
               PROJECT_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/ios
               PROJECT_FILE_PATH = /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner.xcodeproj
               PROJECT_NAME = Runner
               PROJECT_TEMP_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build
               PROJECT_TEMP_ROOT = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios
               PROVISIONING_PROFILE_REQUIRED = YES
               PUBLIC_HEADERS_FOLDER_PATH = Runner.app/Headers
               RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS = YES
               REMOVE_CVS_FROM_RESOURCES = YES
               REMOVE_GIT_FROM_RESOURCES = YES
               REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES = YES
               REMOVE_HG_FROM_RESOURCES = YES
               REMOVE_SVN_FROM_RESOURCES = YES
               RESOURCE_RULES_REQUIRED = YES
               REZ_COLLECTOR_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/ResourceManagerResources
               REZ_OBJECTS_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build/ResourceManagerResources/Objects
               SCAN_ALL_SOURCE_FILES_FOR_INCLUDES = NO
               SCRIPTS_FOLDER_PATH = Runner.app/Scripts
               SDKROOT = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk
               SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk
               SDK_DIR_iphoneos11_4 = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk
               SDK_NAME = iphoneos11.4
               SDK_NAMES = iphoneos11.4
               SDK_PRODUCT_BUILD_VERSION = 15F79
               SDK_VERSION = 11.4
               SDK_VERSION_ACTUAL = 110400
               SDK_VERSION_MAJOR = 110000
               SDK_VERSION_MINOR = 400
               SED = /usr/bin/sed
               SEPARATE_STRIP = NO
               SEPARATE_SYMBOL_EDIT = NO
               SET_DIR_MODE_OWNER_GROUP = YES
               SET_FILE_MODE_OWNER_GROUP = NO
               SHALLOW_BUNDLE = YES
               SHARED_DERIVED_FILE_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Release-iphoneos/DerivedSources
               SHARED_FRAMEWORKS_FOLDER_PATH = Runner.app/SharedFrameworks
               SHARED_PRECOMPS_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/SharedPrecompiledHeaders
               SHARED_SUPPORT_FOLDER_PATH = Runner.app/SharedSupport
               SKIP_INSTALL = NO
               SOURCE_ROOT = /Users/filiph/dev/reactive_exploration/hello_world_start/ios
               SRCROOT = /Users/filiph/dev/reactive_exploration/hello_world_start/ios
               STRINGS_FILE_OUTPUT_ENCODING = binary
               STRIP_BITCODE_FROM_COPIED_FILES = YES
               STRIP_INSTALLED_PRODUCT = YES
               STRIP_STYLE = all
               STRIP_SWIFT_SYMBOLS = YES
               SUPPORTED_DEVICE_FAMILIES = 1,2
               SUPPORTED_PLATFORMS = iphonesimulator iphoneos
               SUPPORTS_TEXT_BASED_API = NO
               SWIFT_COMPILATION_MODE = wholemodule
               SWIFT_OBJC_BRIDGING_HEADER = Runner/Runner-Bridging-Header.h
               SWIFT_OPTIMIZATION_LEVEL = -O
               SWIFT_PLATFORM_TARGET_PREFIX = ios
               SWIFT_SWIFT3_OBJC_INFERENCE = On
               SWIFT_VERSION = 4.0
               SYMROOT = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios
               SYSTEM_ADMIN_APPS_DIR = /Applications/Utilities
               SYSTEM_APPS_DIR = /Applications
               SYSTEM_CORE_SERVICES_DIR = /System/Library/CoreServices
               SYSTEM_DEMOS_DIR = /Applications/Extras
               SYSTEM_DEVELOPER_APPS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               SYSTEM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               SYSTEM_DEVELOPER_DEMOS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples
               SYSTEM_DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               SYSTEM_DEVELOPER_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library
               SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools
               SYSTEM_DEVELOPER_JAVA_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Java Tools
               SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Performance Tools
               SYSTEM_DEVELOPER_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes
               SYSTEM_DEVELOPER_TOOLS = /Applications/Xcode.app/Contents/Developer/Tools
               SYSTEM_DEVELOPER_TOOLS_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools
               SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools
               SYSTEM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               SYSTEM_DEVELOPER_UTILITIES_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities
               SYSTEM_DOCUMENTATION_DIR = /Library/Documentation
               SYSTEM_KEXT_INSTALL_PATH = /System/Library/Extensions
               SYSTEM_LIBRARY_DIR = /System/Library
               TAPI_VERIFY_MODE = ErrorsOnly
               TARGETED_DEVICE_FAMILY = 1,2
               TARGETNAME = Runner
               TARGET_BUILD_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Release-iphoneos
               TARGET_NAME = Runner
               TARGET_TEMP_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_FILES_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_FILE_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_ROOT = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios
               TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               TREAT_MISSING_BASELINES_AS_TEST_FAILURES = NO
               UID = 74285
               UNLOCALIZED_RESOURCES_FOLDER_PATH = Runner.app
               UNSTRIPPED_PRODUCT = NO
               USER = filiph
               USER_APPS_DIR = /Users/filiph/Applications
               USER_LIBRARY_DIR = /Users/filiph/Library
               USE_DYNAMIC_NO_PIC = YES
               USE_HEADERMAP = YES
               USE_HEADER_SYMLINKS = NO
               VALIDATE_PRODUCT = YES
               VALID_ARCHS = arm64 armv7 armv7s
               VERBOSE_PBXCP = NO
               VERSIONING_SYSTEM = apple-generic
               VERSIONPLIST_PATH = Runner.app/version.plist
               VERSION_INFO_BUILDER = filiph
               VERSION_INFO_FILE = Runner_vers.c
               VERSION_INFO_STRING = "@(#)PROGRAM:Runner  PROJECT:Runner-1"
               WRAPPER_EXTENSION = app
               WRAPPER_NAME = Runner.app
               WRAPPER_SUFFIX = .app
               WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
               XCODE_APP_SUPPORT_DIR = /Applications/Xcode.app/Contents/Developer/Library/Xcode
               XCODE_PRODUCT_BUILD_VERSION = 9F1027a
               XCODE_VERSION_ACTUAL = 0940
               XCODE_VERSION_MAJOR = 0900
               XCODE_VERSION_MINOR = 0940
               XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
               YACC = yacc
               arch = arm64
               variant = normal
[  +15 ms] Building Runner.app for 8C0199F9-DE6D-4A50-86F3-875D58FF15E6.
[   +9 ms] script /dev/null /usr/bin/log stream --style syslog --predicate processImagePath CONTAINS "8C0199F9-DE6D-4A50-86F3-875D58FF15E6"
[  +34 ms] [DEVICE LOG] Filtering the log data using "processImagePath CONTAINS "8C0199F9-DE6D-4A50-86F3-875D58FF15E6""
[   +4 ms] [DEVICE LOG] Timestamp                       (process)[PID]
[ +129 ms] Skipping kernel compilation. Fingerprint match.
[ +230 ms] Building bundle
[        ] Writing asset files to build/flutter_assets
[  +46 ms] Wrote build/flutter_assets
[   +1 ms] /usr/bin/xcrun simctl get_app_container 8C0199F9-DE6D-4A50-86F3-875D58FF15E6 hello_world.flutter.io.helloWorldStart
[        ] /usr/bin/killall Runner
[ +143 ms] python -c import six
[ +152 ms] [ios/] /usr/bin/xcodebuild -list
[ +622 ms] Exit code 0 from: /usr/bin/xcodebuild -list
[        ] Information about project "Runner":
               Targets:
                   Runner

               Build Configurations:
                   Debug
                   Release

               If no build configuration is specified and -scheme is not passed then "Release" is used.

               Schemes:
                   Runner
[   +1 ms] Trying to resolve native pub services.
[   +1 ms] Looking for YAML at 'pubspec.yaml'
[        ] No services specified in the manifest
[        ] Found 0 service definition(s).
[        ] Copying service frameworks to '/Users/filiph/dev/reactive_exploration/hello_world_start/ios/Frameworks'.
[        ] Creating service definitions manifest at 'ios/ServiceDefinitions.json'
[   +5 ms] mkfifo /var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/flutter_build_log_pipeeWkOLu/pipe_to_stdout
[   +5 ms] Exit code 0 from: mkfifo /var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/flutter_build_log_pipeeWkOLu/pipe_to_stdout
[        ] Starting Xcode build...
[   +1 ms] [ios/] /usr/bin/env xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios -sdk iphonesimulator -arch x86_64 SCRIPT_OUTPUT_STREAM_FILE=/var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/flutter_build_log_pipeeWkOLu/pipe_to_stdout
[+1052 ms]  ├─Assembling Flutter resources...
[+1076 ms]  └─Compiling, linking and signing...
[+2963 ms] Build settings from command line:
                       ARCHS = x86_64
                       BUILD_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios
                       SCRIPT_OUTPUT_STREAM_FILE = /var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/flutter_build_log_pipeeWkOLu/pipe_to_stdout
                       SDKROOT = iphonesimulator11.4
                       VERBOSE_SCRIPT_LOGGING = YES

                   === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===

                   Check dependencies
                   The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.

                   PhaseScriptExecution Run\ Script /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export ACTION=build
                       export AD_HOC_CODE_SIGNING_ALLOWED=YES
                       export ALTERNATE_GROUP=eng
                       export ALTERNATE_MODE=u+w,go-w,a+rX
                       export ALTERNATE_OWNER=filiph
                       export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
                       export ALWAYS_SEARCH_USER_PATHS=NO
                       export ALWAYS_USE_SEPARATE_HEADERMAPS=NO
                       export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
                       export APPLE_INTERNAL_DIR=/AppleInternal
                       export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
                       export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
                       export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
                       export APPLICATION_EXTENSION_API_ONLY=NO
                       export APPLY_RULES_IN_COPY_FILES=NO
                       export ARCHS=x86_64
                       export ARCHS_STANDARD="i386 x86_64"
                       export ARCHS_STANDARD_32_64_BIT="i386 x86_64"
                       export ARCHS_STANDARD_32_BIT=i386
                       export ARCHS_STANDARD_64_BIT=x86_64
                       export ARCHS_STANDARD_INCLUDING_64_BIT="i386 x86_64"
                       export ARCHS_UNIVERSAL_IPHONE_OS="i386 x86_64"
                       export ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon
                       export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
                       export BITCODE_GENERATION_MODE=marker
                       export BUILD_ACTIVE_RESOURCES_ONLY=YES
                       export BUILD_COMPONENTS="headers build"
                       export BUILD_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios
                       export BUILD_ROOT=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Products
                       export BUILD_STYLE=
                       export BUILD_VARIANTS=normal
                       export BUILT_PRODUCTS_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator
                       export CACHE_ROOT=/var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/C/com.apple.DeveloperTools/9.4-9F1027a/Xcode
                       export CCHROOT=/var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/C/com.apple.DeveloperTools/9.4-9F1027a/Xcode
                       export CHMOD=/bin/chmod
                       export CHOWN=/usr/sbin/chown
                       export CLANG_ANALYZER_NONNULL=YES
                       export CLANG_CXX_LANGUAGE_STANDARD=gnu++0x
                       export CLANG_CXX_LIBRARY=libc++
                       export CLANG_ENABLE_MODULES=YES
                       export CLANG_ENABLE_OBJC_ARC=YES
                       export CLANG_MODULES_BUILD_SESSION_FILE=/Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation
                       export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING=YES
                       export CLANG_WARN_BOOL_CONVERSION=YES
                       export CLANG_WARN_COMMA=YES
                       export CLANG_WARN_CONSTANT_CONVERSION=YES
                       export CLANG_WARN_DIRECT_OBJC_ISA_USAGE=YES_ERROR
                       export CLANG_WARN_EMPTY_BODY=YES
                       export CLANG_WARN_ENUM_CONVERSION=YES
                       export CLANG_WARN_INFINITE_RECURSION=YES
                       export CLANG_WARN_INT_CONVERSION=YES
                       export CLANG_WARN_NON_LITERAL_NULL_CONVERSION=YES
                       export CLANG_WARN_OBJC_LITERAL_CONVERSION=YES
                       export CLANG_WARN_OBJC_ROOT_CLASS=YES_ERROR
                       export CLANG_WARN_RANGE_LOOP_ANALYSIS=YES
                       export CLANG_WARN_STRICT_PROTOTYPES=YES
                       export CLANG_WARN_SUSPICIOUS_MOVE=YES
                       export CLANG_WARN_UNREACHABLE_CODE=YES
                       export CLANG_WARN__DUPLICATE_METHOD_MATCH=YES
                       export CLASS_FILE_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/JavaClasses
                       export CLEAN_PRECOMPS=YES
                       export CLONE_HEADERS=NO
                       export CODESIGNING_FOLDER_PATH=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app
                       export CODE_SIGNING_ALLOWED=YES
                       export CODE_SIGNING_REQUIRED=YES
                       export CODE_SIGN_CONTEXT_CLASS=XCiPhoneSimulatorCodeSignContext
                       export CODE_SIGN_IDENTITY=-
                       export CODE_SIGN_INJECT_BASE_ENTITLEMENTS=YES
                       export COLOR_DIAGNOSTICS=NO
                       export COMBINE_HIDPI_IMAGES=NO
                       export COMMAND_MODE=legacy
                       export COMPILER_INDEX_STORE_ENABLE=Default
                       export COMPOSITE_SDK_DIRS=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/CompositeSDKs
                       export COMPRESS_PNG_FILES=YES
                       export CONFIGURATION=Debug
                       export CONFIGURATION_BUILD_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator
                       export CONFIGURATION_TEMP_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator
                       export CONTENTS_FOLDER_PATH=Runner.app
                       export COPYING_PRESERVES_HFS_DATA=NO
                       export COPY_HEADERS_RUN_UNIFDEF=NO
                       export COPY_PHASE_STRIP=NO
                       export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS=YES
                       export CORRESPONDING_DEVICE_PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
                       export CORRESPONDING_DEVICE_PLATFORM_NAME=iphoneos
                       export CORRESPONDING_DEVICE_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk
                       export CORRESPONDING_DEVICE_SDK_NAME=iphoneos11.4
                       export CP=/bin/cp
                       export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
                       export CURRENT_ARCH=x86_64
                       export CURRENT_PROJECT_VERSION=1
                       export CURRENT_VARIANT=normal
                       export DEAD_CODE_STRIPPING=YES
                       export DEBUGGING_SYMBOLS=YES
                       export DEBUG_INFORMATION_FORMAT=dwarf
                       export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
                       export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
                       export DEFINES_MODULE=NO
                       export DEPLOYMENT_LOCATION=NO
                       export DEPLOYMENT_POSTPROCESSING=NO
                       export DEPLOYMENT_TARGET_CLANG_ENV_NAME=IPHONEOS_DEPLOYMENT_TARGET
                       export DEPLOYMENT_TARGET_CLANG_FLAG_NAME=mios-simulator-version-min
                       export DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX=-mios-simulator-version-min=
                       export DEPLOYMENT_TARGET_SETTING_NAME=IPHONEOS_DEPLOYMENT_TARGET
                       export DEPLOYMENT_TARGET_SUGGESTED_VALUES="8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4"
                       export DERIVED_FILES_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
                       export DERIVED_FILE_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
                       export DERIVED_SOURCES_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
                       export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
                       export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
                       export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
                       export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
                       export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
                       export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
                       export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
                       export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
                       export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
                       export DEVELOPMENT_LANGUAGE=English
                       export DOCUMENTATION_FOLDER_PATH=Runner.app/English.lproj/Documentation
                       export DO_HEADER_SCANNING_IN_JAM=NO
                       export DSTROOT=/tmp/Runner.dst
                       export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
                       export DWARF_DSYM_FILE_NAME=Runner.app.dSYM
                       export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
                       export DWARF_DSYM_FOLDER_PATH=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator
                       export EFFECTIVE_PLATFORM_NAME=-iphonesimulator
                       export EMBEDDED_CONTENT_CONTAINS_SWIFT=NO
                       export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
                       export ENABLE_BITCODE=NO
                       export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES
                       export ENABLE_HEADER_DEPENDENCIES=YES
                       export ENABLE_ON_DEMAND_RESOURCES=YES
                       export ENABLE_STRICT_OBJC_MSGSEND=YES
                       export ENABLE_TESTABILITY=YES
                       export ENTITLEMENTS_REQUIRED=YES
                       export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
                       export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
                       export EXECUTABLES_FOLDER_PATH=Runner.app/Executables
                       export EXECUTABLE_FOLDER_PATH=Runner.app
                       export EXECUTABLE_NAME=Runner
                       export EXECUTABLE_PATH=Runner.app/Runner
                       export EXPANDED_CODE_SIGN_IDENTITY=-
                       export EXPANDED_CODE_SIGN_IDENTITY_NAME=-
                       export EXPANDED_PROVISIONING_PROFILE=
                       export FILE_LIST=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects/LinkFileList
                       export FIXED_FILES_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/FixedFiles
                       export FLUTTER_APPLICATION_PATH=/Users/filiph/dev/reactive_exploration/hello_world_start
                       export FLUTTER_BUILD_DIR=build
                       export FLUTTER_BUILD_MODE=debug
                       export FLUTTER_FRAMEWORK_DIR=/Users/filiph/dev/flutter/bin/cache/artifacts/engine/ios
                       export FLUTTER_ROOT=/Users/filiph/dev/flutter
                       export FLUTTER_TARGET=lib/main.dart
                       export FRAMEWORKS_FOLDER_PATH=Runner.app/Frameworks
                       export FRAMEWORK_FLAG_PREFIX=-framework
                       export FRAMEWORK_SEARCH_PATHS="/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator  /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter"
                       export FRAMEWORK_VERSION=A
                       export FULL_PRODUCT_NAME=Runner.app
                       export GCC3_VERSION=3.3
                       export GCC_C_LANGUAGE_STANDARD=gnu99
                       export GCC_DYNAMIC_NO_PIC=NO
                       export GCC_INLINES_ARE_PRIVATE_EXTERN=YES
                       export GCC_NO_COMMON_BLOCKS=YES
                       export GCC_OBJC_LEGACY_DISPATCH=YES
                       export GCC_OPTIMIZATION_LEVEL=0
                       export GCC_PFE_FILE_C_DIALECTS="c objective-c c++ objective-c++"
                       export GCC_PREPROCESSOR_DEFINITIONS="DEBUG=1 "
                       export GCC_SYMBOLS_PRIVATE_EXTERN=NO
                       export GCC_TREAT_WARNINGS_AS_ERRORS=NO
                       export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
                       export GCC_VERSION_IDENTIFIER=com_apple_compilers_llvm_clang_1_0
                       export GCC_WARN_64_TO_32_BIT_CONVERSION=YES
                       export GCC_WARN_ABOUT_RETURN_TYPE=YES_ERROR
                       export GCC_WARN_UNDECLARED_SELECTOR=YES
                       export GCC_WARN_UNINITIALIZED_AUTOS=YES_AGGRESSIVE
                       export GCC_WARN_UNUSED_FUNCTION=YES
                       export GCC_WARN_UNUSED_VARIABLE=YES
                       export GENERATE_MASTER_OBJECT_FILE=NO
                       export GENERATE_PKGINFO_FILE=YES
                       export GENERATE_PROFILING_CODE=NO
                       export GENERATE_TEXT_BASED_STUBS=NO
                       export GID=5000
                       export GROUP=eng
                       export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
                       export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
                       export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
                       export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
                       export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
                       export HEADERMAP_USES_VFS=NO
                       export HEADER_SEARCH_PATHS="/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/include "
                       export HIDE_BITCODE_SYMBOLS=YES
                       export HOME=/Users/filiph
                       export ICONV=/usr/bin/iconv
                       export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
                       export INFOPLIST_FILE=Runner/Info.plist
                       export INFOPLIST_OUTPUT_FORMAT=binary
                       export INFOPLIST_PATH=Runner.app/Info.plist
                       export INFOPLIST_PREPROCESS=NO
                       export INFOSTRINGS_PATH=Runner.app/English.lproj/InfoPlist.strings
                       export INLINE_PRIVATE_FRAMEWORKS=NO
                       export INSTALLHDRS_COPY_PHASE=NO
                       export INSTALLHDRS_SCRIPT_PHASE=NO
                       export INSTALL_DIR=/tmp/Runner.dst/Applications
                       export INSTALL_GROUP=eng
                       export INSTALL_MODE_FLAG=u+w,go-w,a+rX
                       export INSTALL_OWNER=filiph
                       export INSTALL_PATH=/Applications
                       export INSTALL_ROOT=/tmp/Runner.dst
                       export IPHONEOS_DEPLOYMENT_TARGET=8.0
                       export JAVAC_DEFAULT_FLAGS="-J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8"
                       export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
                       export JAVA_ARCHIVE_CLASSES=YES
                       export JAVA_ARCHIVE_TYPE=JAR
                       export JAVA_COMPILER=/usr/bin/javac
                       export JAVA_FOLDER_PATH=Runner.app/Java
                       export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
                       export JAVA_JAR_FLAGS=cv
                       export JAVA_SOURCE_SUBDIR=.
                       export JAVA_USE_DEPENDENCIES=YES
                       export JAVA_ZIP_FLAGS=-urg
                       export JIKES_DEFAULT_FLAGS="+E +OLDCSO"
                       export KEEP_PRIVATE_EXTERNS=NO
                       export LD_DEPENDENCY_INFO_FILE=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat
                       export LD_GENERATE_MAP_FILE=NO
                       export LD_MAP_FILE_PATH=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-LinkMap-normal-x86_64.txt
                       export LD_NO_PIE=NO
                       export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
                       export LD_RUNPATH_SEARCH_PATHS=" @executable_path/Frameworks"
                       export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
                       export LEX=lex
                       export LIBRARY_FLAG_NOSPACE=YES
                       export LIBRARY_FLAG_PREFIX=-l
                       export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
                       export LIBRARY_SEARCH_PATHS="/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator  /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter"
                       export LINKER_DISPLAYS_MANGLED_NAMES=NO
                       export LINK_FILE_LIST_normal_x86_64=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.LinkFileList
                       export LINK_WITH_STANDARD_LIBRARIES=YES
                       export LOCALIZABLE_CONTENT_DIR=
                       export LOCALIZED_RESOURCES_FOLDER_PATH=Runner.app/English.lproj
                       export LOCALIZED_STRING_MACRO_NAMES="NSLocalizedString CFLocalizedString"
                       export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
                       export LOCAL_APPS_DIR=/Applications
                       export LOCAL_DEVELOPER_DIR=/Library/Developer
                       export LOCAL_LIBRARY_DIR=/Library
                       export LOCROOT=
                       export LOCSYMROOT=
                       export MACH_O_TYPE=mh_execute
                       export MAC_OS_X_PRODUCT_BUILD_VERSION=17E202
                       export MAC_OS_X_VERSION_ACTUAL=101304
                       export MAC_OS_X_VERSION_MAJOR=101300
                       export MAC_OS_X_VERSION_MINOR=1304
                       export METAL_LIBRARY_FILE_BASE=default
                       export METAL_LIBRARY_OUTPUT_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app
                       export MODULE_CACHE_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
                       export MTL_ENABLE_DEBUG_INFO=YES
                       export NATIVE_ARCH=i386
                       export NATIVE_ARCH_32_BIT=i386
                       export NATIVE_ARCH_64_BIT=x86_64
                       export NATIVE_ARCH_ACTUAL=x86_64
                       export NO_COMMON=YES
                       export OBJC_ABI_VERSION=2
                       export OBJECT_FILE_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects
                       export OBJECT_FILE_DIR_normal=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
                       export OBJROOT=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex
                       export ONLY_ACTIVE_ARCH=YES
                       export OS=MACOS
                       export OSAC=/usr/bin/osacompile
                       export PACKAGE_TYPE=com.apple.package-type.wrapper.application
                       export PASCAL_STRINGS=YES
                       export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Tools:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:/Users/filiph/.pub-cache/bin:/Users/filiph/gsutil:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"
                       export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
                       export PBDEVELOPMENTPLIST_PATH=Runner.app/pbdevelopment.plist
                       export PFE_FILE_C_DIALECTS=objective-c
                       export PKGINFO_FILE_PATH=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PkgInfo
                       export PKGINFO_PATH=Runner.app/PkgInfo
                       export PLATFORM_DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
                       export PLATFORM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
                       export PLATFORM_DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
                       export PLATFORM_DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
                       export PLATFORM_DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
                       export PLATFORM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
                       export PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
                       export PLATFORM_DISPLAY_NAME="iOS Simulator"
                       export PLATFORM_NAME=iphonesimulator
                       export PLATFORM_PREFERRED_ARCH=x86_64
                       export PLIST_FILE_OUTPUT_FORMAT=binary
                       export PLUGINS_FOLDER_PATH=Runner.app/PlugIns
                       export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
                       export PRECOMP_DESTINATION_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PrefixHeaders
                       export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
                       export PREVIEW_DART_2=true
                       export PRIVATE_HEADERS_FOLDER_PATH=Runner.app/PrivateHeaders
                       export PRODUCT_BUNDLE_IDENTIFIER=hello_world.flutter.io.helloWorldStart
                       export PRODUCT_MODULE_NAME=Runner
                       export PRODUCT_NAME=Runner
                       export PRODUCT_SETTINGS_PATH=/Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/Info.plist
                       export PRODUCT_TYPE=com.apple.product-type.application
                       export PROFILING_CODE=NO
                       export PROJECT=Runner
                       export PROJECT_DERIVED_FILE_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/DerivedSources
                       export PROJECT_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export PROJECT_FILE_PATH=/Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner.xcodeproj
                       export PROJECT_NAME=Runner
                       export PROJECT_TEMP_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build
                       export PROJECT_TEMP_ROOT=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex
                       export PUBLIC_HEADERS_FOLDER_PATH=Runner.app/Headers
                       export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS=YES
                       export REMOVE_CVS_FROM_RESOURCES=YES
                       export REMOVE_GIT_FROM_RESOURCES=YES
                       export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
                       export REMOVE_HG_FROM_RESOURCES=YES
                       export REMOVE_SVN_FROM_RESOURCES=YES
                       export REZ_COLLECTOR_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources
                       export REZ_OBJECTS_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources/Objects
                       export REZ_SEARCH_PATHS="/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator "
                       export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
                       export SCRIPTS_FOLDER_PATH=Runner.app/Scripts
                       export SCRIPT_INPUT_FILE_COUNT=0
                       export SCRIPT_OUTPUT_FILE_COUNT=0
                       export SCRIPT_OUTPUT_STREAM_FILE=/var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/flutter_build_log_pipeeWkOLu/pipe_to_stdout
                       export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk
                       export SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk
                       export SDK_DIR_iphonesimulator11_4=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk
                       export SDK_NAME=iphonesimulator11.4
                       export SDK_NAMES=iphonesimulator11.4
                       export SDK_PRODUCT_BUILD_VERSION=15F79
                       export SDK_VERSION=11.4
                       export SDK_VERSION_ACTUAL=110400
                       export SDK_VERSION_MAJOR=110000
                       export SDK_VERSION_MINOR=400
                       export SED=/usr/bin/sed
                       export SEPARATE_STRIP=NO
                       export SEPARATE_SYMBOL_EDIT=NO
                       export SET_DIR_MODE_OWNER_GROUP=YES
                       export SET_FILE_MODE_OWNER_GROUP=NO
                       export SHALLOW_BUNDLE=YES
                       export SHARED_DERIVED_FILE_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/DerivedSources
                       export SHARED_FRAMEWORKS_FOLDER_PATH=Runner.app/SharedFrameworks
                       export SHARED_PRECOMPS_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/PrecompiledHeaders
                       export SHARED_SUPPORT_FOLDER_PATH=Runner.app/SharedSupport
                       export SKIP_INSTALL=NO
                       export SOURCE_ROOT=/Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export SRCROOT=/Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export STRINGS_FILE_OUTPUT_ENCODING=binary
                       export STRIP_BITCODE_FROM_COPIED_FILES=NO
                       export STRIP_INSTALLED_PRODUCT=YES
                       export STRIP_STYLE=all
                       export STRIP_SWIFT_SYMBOLS=YES
                       export SUPPORTED_DEVICE_FAMILIES=1,2
                       export SUPPORTED_PLATFORMS="iphonesimulator iphoneos"
                       export SUPPORTS_TEXT_BASED_API=NO
                       export SWIFT_OBJC_BRIDGING_HEADER=Runner/Runner-Bridging-Header.h
                       export SWIFT_OPTIMIZATION_LEVEL=-Onone
                       export SWIFT_PLATFORM_TARGET_PREFIX=ios
                       export SWIFT_SWIFT3_OBJC_INFERENCE=On
                       export SWIFT_VERSION=4.0
                       export SYMROOT=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Products
                       export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
                       export SYSTEM_APPS_DIR=/Applications
                       export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
                       export SYSTEM_DEMOS_DIR=/Applications/Extras
                       export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
                       export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
                       export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
                       export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
                       export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
                       export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
                       export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
                       export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
                       export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
                       export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
                       export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
                       export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
                       export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
                       export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
                       export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
                       export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
                       export SYSTEM_LIBRARY_DIR=/System/Library
                       export TAPI_VERIFY_MODE=ErrorsOnly
                       export TARGETED_DEVICE_FAMILY=1,2
                       export TARGETNAME=Runner
                       export TARGET_BUILD_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator
                       export TARGET_DEVICE_IDENTIFIER="dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder"
                       export TARGET_NAME=Runner
                       export TARGET_TEMP_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
                       export TEMP_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
                       export TEMP_FILES_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
                       export TEMP_FILE_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
                       export TEMP_ROOT=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex
                       export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
                       export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
                       export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
                       export UID=74285
                       export UNLOCALIZED_RESOURCES_FOLDER_PATH=Runner.app
                       export UNSTRIPPED_PRODUCT=NO
                       export USER=filiph
                       export USER_APPS_DIR=/Users/filiph/Applications
                       export USER_LIBRARY_DIR=/Users/filiph/Library
                       export USE_DYNAMIC_NO_PIC=YES
                       export USE_HEADERMAP=YES
                       export USE_HEADER_SYMLINKS=NO
                       export VALIDATE_PRODUCT=NO
                       export VALID_ARCHS="i386 x86_64"
                       export VERBOSE_PBXCP=NO
                       export VERBOSE_SCRIPT_LOGGING=YES
                       export VERSIONING_SYSTEM=apple-generic
                       export VERSIONPLIST_PATH=Runner.app/version.plist
                       export VERSION_INFO_BUILDER=filiph
                       export VERSION_INFO_FILE=Runner_vers.c
                       export VERSION_INFO_STRING="\"@(#)PROGRAM:Runner  PROJECT:Runner-1\""
                       export WRAPPER_EXTENSION=app
                       export WRAPPER_NAME=Runner.app
                       export WRAPPER_SUFFIX=.app
                       export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
                       export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
                       export XCODE_PRODUCT_BUILD_VERSION=9F1027a
                       export XCODE_VERSION_ACTUAL=0940
                       export XCODE_VERSION_MAJOR=0900
                       export XCODE_VERSION_MINOR=0940
                       export XPCSERVICES_FOLDER_PATH=Runner.app/XPCServices
                       export YACC=yacc
                       export arch=x86_64
                       export variant=normal
                       /bin/sh -c /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh
                   ♦ mkdir -p -- /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter
                   ♦ rm -rf -- /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/Flutter.framework
                   ♦ rm -rf -- /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/App.framework
                   ♦ cp -r -- /Users/filiph/dev/flutter/bin/cache/artifacts/engine/ios/Flutter.framework /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter
                   ♦ find /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/Flutter.framework -type f -exec chmod a-w {} ;
                   ♦ mkdir -p -- /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/App.framework
                   ♦ eval
                   ♦ cp -- /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/AppFrameworkInfo.plist /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/App.framework/Info.plist
                   ♦ /Users/filiph/dev/flutter/bin/flutter --suppress-analytics --verbose build bundle --target=lib/main.dart --snapshot=build/snapshot_blob.bin --depfile=build/snapshot_blob.bin.d --asset-dir=/Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/flutter_assets --preview-dart-2
                   [   +6 ms] [/Users/filiph/dev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
                   [  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
                   [        ] origin/beta
                   [        ] [/Users/filiph/dev/flutter/] git rev-parse --abbrev-ref HEAD
                   [   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
                   [        ] beta
                   [        ] [/Users/filiph/dev/flutter/] git ls-remote --get-url origin
                   [   +6 ms] Exit code 0 from: git ls-remote --get-url origin
                   [        ] https://github.com/flutter/flutter.git
                   [        ] [/Users/filiph/dev/flutter/] git log -n 1 --pretty=format:%H
                   [   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
                   [        ] f9bb4289e9fd861d70ae78bcc3a042ef1b35cc9d
                   [        ] [/Users/filiph/dev/flutter/] git log -n 1 --pretty=format:%ar
                   [   +6 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
                   [        ] 3 weeks ago
                   [        ] [/Users/filiph/dev/flutter/] git describe --match v*.*.* --first-parent --long --tags
                   [  +11 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
                   [        ] v0.4.4-0-gf9bb4289e
                   [ +389 ms] Skipping kernel compilation. Fingerprint match.
                   [ +186 ms] Building bundle
                   [        ] Writing asset files to /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/flutter_assets
                   [  +50 ms] Wrote /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/flutter_assets
                   [  +12 ms] "flutter bundle" took 521ms.
                   Project /Users/filiph/dev/reactive_exploration/hello_world_start built and packaged successfully.

                   CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
                       export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"
                       export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk
                       /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name Runner -Onone -enforce-exclusivity=checked -Xfrontend -enable-swift3-objc-inference -Xfrontend -warn-swift3-objc-inference-minimal -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -target x86_64-apple-ios8.0 -g -module-cache-path /Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -index-store-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Index/DataStore -swift-version 4 -I /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator -F /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator -F /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter -parse-as-library -c -j8 /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/AppDelegate.swift -output-file-map /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.swiftmodule -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-generated-files.hmap -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-own-target-headers.hmap -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-all-target-headers.hmap -Xcc -iquote -Xcc /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-project-headers.hmap -Xcc -I/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/include -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64 -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -Xcc -DDEBUG=1 -emit-objc-header -emit-objc-header-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner-Swift.h -import-objc-header /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/Runner-Bridging-Header.h -pch-output-dir /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/PrecompiledHeaders -Xcc -working-directory/Users/filiph/dev/reactive_exploration/hello_world_start/ios

                   PrecompileSwiftBridgingHeader normal x86_64
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -target x86_64-apple-ios8.0 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -I /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator -F /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator -F /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter -enable-testing -g -module-cache-path /Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 4 -enforce-exclusivity=checked -Onone -enable-swift3-objc-inference -warn-swift3-objc-inference-minimal -serialize-debugging-options -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-generated-files.hmap -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-own-target-headers.hmap -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-all-target-headers.hmap -Xcc -iquote -Xcc /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-project-headers.hmap -Xcc -I/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/include -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64 -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -working-directory/Users/filiph/dev/reactive_exploration/hello_world_start/ios -serialize-diagnostics-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-PRCS6XFCJS4P.dia /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/Runner-Bridging-Header.h -index-store-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Index/DataStore -emit-pch -pch-output-dir /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/PrecompiledHeaders
                   fatal error: file '/Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/Flutter.framework/Headers/FlutterTexture.h' has been modified since the precompiled header '/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_3T2UML2Y97EKX-clang_1XG1GSGAHZSM3.pch' was built
                   note: '/Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/Flutter.framework/Headers/FlutterTexture.h' required by '/Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1XG1GSGAHZSM3/Flutter-3EKIXUP53SHO5.pcm'
                   note: '/Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1XG1GSGAHZSM3/Flutter-3EKIXUP53SHO5.pcm' required by '/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_3T2UML2Y97EKX-clang_1XG1GSGAHZSM3.pch'
                   note: please rebuild precompiled header '/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_3T2UML2Y97EKX-clang_1XG1GSGAHZSM3.pch'
                   note: imported by '/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_3T2UML2Y97EKX-clang_1XG1GSGAHZSM3.pch'

                   CompileSwift normal x86_64 /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/AppDelegate.swift
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/AppDelegate.swift -target x86_64-apple-ios8.0 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -I /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator -F /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator -F /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter -enable-testing -g -module-cache-path /Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 4 -enforce-exclusivity=checked -Onone -enable-swift3-objc-inference -warn-swift3-objc-inference-minimal -serialize-debugging-options -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-generated-files.hmap -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-own-target-headers.hmap -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-all-target-headers.hmap -Xcc -iquote -Xcc /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-project-headers.hmap -Xcc -I/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/include -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64 -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -working-directory/Users/filiph/dev/reactive_exploration/hello_world_start/ios -emit-module-doc-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate~partial.swiftdoc -serialize-diagnostics-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.dia -import-objc-header /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/Runner-Bridging-Header.h -pch-output-dir /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/PrecompiledHeaders -pch-disable-validation -parse-as-library -module-name Runner -emit-module-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate~partial.swiftmodule -emit-dependencies-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.d -emit-reference-dependencies-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.swiftdeps -o /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.o -index-store-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Index/DataStore -index-system-modules

                   MergeSwiftModule normal x86_64 /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.swiftmodule
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -merge-modules -emit-module /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate~partial.swiftmodule -parse-as-library -sil-merge-partial-modules -disable-diagnostic-passes -disable-sil-perf-optzns -target x86_64-apple-ios8.0 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -I /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator -F /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator -F /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter -enable-testing -g -module-cache-path /Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 4 -enforce-exclusivity=checked -Onone -enable-swift3-objc-inference -warn-swift3-objc-inference-minimal -serialize-debugging-options -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-generated-files.hmap -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-own-target-headers.hmap -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-all-target-headers.hmap -Xcc -iquote -Xcc /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-project-headers.hmap -Xcc -I/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/include -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64 -Xcc -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -working-directory/Users/filiph/dev/reactive_exploration/hello_world_start/ios -emit-module-doc-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.swiftdoc -import-objc-header /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/Runner-Bridging-Header.h -module-name Runner -emit-objc-header-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner-Swift.h -o /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.swiftmodule

                   CompileC /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.o Runner/GeneratedPluginRegistrant.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export LANG=en_US.US-ASCII
                       export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"
                       /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Index/DataStore -iquote /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-generated-files.hmap -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-own-target-headers.hmap -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-all-target-headers.hmap -iquote /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-project-headers.hmap -I/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/include -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64 -I/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -F/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator -F/Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter -MMD -MT dependencies -MF /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.d --serialize-diagnostics /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.dia -c /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/GeneratedPluginRegistrant.m -o /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.o
                   While building module 'Flutter' imported from /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/GeneratedPluginRegistrant.h:8:
                   In file included from <module-includes>:1:
                   In file included from /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/Flutter.framework/Headers/Flutter.h:37:
                   In file included from /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
                   /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h:140:58: warning: this block declaration is not a prototype [-Wstrict-prototypes]
                                         completionHandler:(nonnull void (^)())completionHandler;
                                                                            ^
                                                                             void
                   1 warning generated.
                   1 warning generated.

                   Ld /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Runner normal x86_64
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export IPHONEOS_DEPLOYMENT_TARGET=8.0
                       export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"
                       /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -L/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator -L/Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter -F/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator -F/Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter -filelist /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.swiftmodule -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent -framework Flutter -framework App -Xlinker -dependency_info -Xlinker /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat -o /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Runner

                   CpResource Flutter/Generated.xcconfig /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Generated.xcconfig
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"
                       builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/Generated.xcconfig /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app

                   CpResource Flutter/flutter_assets /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/flutter_assets
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"
                       builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/flutter_assets /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app

                   PBXCp Flutter/App.framework /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/App.framework
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"
                       builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -exclude Headers -exclude PrivateHeaders -exclude Modules -exclude *.tbd -resolve-src-symlinks /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/App.framework /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks

                   PBXCp Flutter/Flutter.framework /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"
                       builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -exclude Headers -exclude PrivateHeaders -exclude Modules -exclude *.tbd -resolve-src-symlinks /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/Flutter.framework /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks

                   CodeSign /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/App.framework
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
                       export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"

                   Signing Identity:     "-"

                       /usr/bin/codesign --force --sign - --preserve-metadata=identifier,entitlements,flags --timestamp=none /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/App.framework

                   CodeSign /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
                       export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"

                   Signing Identity:     "-"

                       /usr/bin/codesign --force --sign - --preserve-metadata=identifier,entitlements,flags --timestamp=none /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework

                   PhaseScriptExecution Thin\ Binary /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export ACTION=build
                       export AD_HOC_CODE_SIGNING_ALLOWED=YES
                       export ALTERNATE_GROUP=eng
                       export ALTERNATE_MODE=u+w,go-w,a+rX
                       export ALTERNATE_OWNER=filiph
                       export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
                       export ALWAYS_SEARCH_USER_PATHS=NO
                       export ALWAYS_USE_SEPARATE_HEADERMAPS=NO
                       export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
                       export APPLE_INTERNAL_DIR=/AppleInternal
                       export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
                       export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
                       export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
                       export APPLICATION_EXTENSION_API_ONLY=NO
                       export APPLY_RULES_IN_COPY_FILES=NO
                       export ARCHS=x86_64
                       export ARCHS_STANDARD="i386 x86_64"
                       export ARCHS_STANDARD_32_64_BIT="i386 x86_64"
                       export ARCHS_STANDARD_32_BIT=i386
                       export ARCHS_STANDARD_64_BIT=x86_64
                       export ARCHS_STANDARD_INCLUDING_64_BIT="i386 x86_64"
                       export ARCHS_UNIVERSAL_IPHONE_OS="i386 x86_64"
                       export ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon
                       export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
                       export BITCODE_GENERATION_MODE=marker
                       export BUILD_ACTIVE_RESOURCES_ONLY=YES
                       export BUILD_COMPONENTS="headers build"
                       export BUILD_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios
                       export BUILD_ROOT=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Products
                       export BUILD_STYLE=
                       export BUILD_VARIANTS=normal
                       export BUILT_PRODUCTS_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator
                       export CACHE_ROOT=/var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/C/com.apple.DeveloperTools/9.4-9F1027a/Xcode
                       export CCHROOT=/var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/C/com.apple.DeveloperTools/9.4-9F1027a/Xcode
                       export CHMOD=/bin/chmod
                       export CHOWN=/usr/sbin/chown
                       export CLANG_ANALYZER_NONNULL=YES
                       export CLANG_CXX_LANGUAGE_STANDARD=gnu++0x
                       export CLANG_CXX_LIBRARY=libc++
                       export CLANG_ENABLE_MODULES=YES
                       export CLANG_ENABLE_OBJC_ARC=YES
                       export CLANG_MODULES_BUILD_SESSION_FILE=/Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation
                       export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING=YES
                       export CLANG_WARN_BOOL_CONVERSION=YES
                       export CLANG_WARN_COMMA=YES
                       export CLANG_WARN_CONSTANT_CONVERSION=YES
                       export CLANG_WARN_DIRECT_OBJC_ISA_USAGE=YES_ERROR
                       export CLANG_WARN_EMPTY_BODY=YES
                       export CLANG_WARN_ENUM_CONVERSION=YES
                       export CLANG_WARN_INFINITE_RECURSION=YES
                       export CLANG_WARN_INT_CONVERSION=YES
                       export CLANG_WARN_NON_LITERAL_NULL_CONVERSION=YES
                       export CLANG_WARN_OBJC_LITERAL_CONVERSION=YES
                       export CLANG_WARN_OBJC_ROOT_CLASS=YES_ERROR
                       export CLANG_WARN_RANGE_LOOP_ANALYSIS=YES
                       export CLANG_WARN_STRICT_PROTOTYPES=YES
                       export CLANG_WARN_SUSPICIOUS_MOVE=YES
                       export CLANG_WARN_UNREACHABLE_CODE=YES
                       export CLANG_WARN__DUPLICATE_METHOD_MATCH=YES
                       export CLASS_FILE_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/JavaClasses
                       export CLEAN_PRECOMPS=YES
                       export CLONE_HEADERS=NO
                       export CODESIGNING_FOLDER_PATH=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app
                       export CODE_SIGNING_ALLOWED=YES
                       export CODE_SIGNING_REQUIRED=YES
                       export CODE_SIGN_CONTEXT_CLASS=XCiPhoneSimulatorCodeSignContext
                       export CODE_SIGN_IDENTITY=-
                       export CODE_SIGN_INJECT_BASE_ENTITLEMENTS=YES
                       export COLOR_DIAGNOSTICS=NO
                       export COMBINE_HIDPI_IMAGES=NO
                       export COMMAND_MODE=legacy
                       export COMPILER_INDEX_STORE_ENABLE=Default
                       export COMPOSITE_SDK_DIRS=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/CompositeSDKs
                       export COMPRESS_PNG_FILES=YES
                       export CONFIGURATION=Debug
                       export CONFIGURATION_BUILD_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator
                       export CONFIGURATION_TEMP_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator
                       export CONTENTS_FOLDER_PATH=Runner.app
                       export COPYING_PRESERVES_HFS_DATA=NO
                       export COPY_HEADERS_RUN_UNIFDEF=NO
                       export COPY_PHASE_STRIP=NO
                       export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS=YES
                       export CORRESPONDING_DEVICE_PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
                       export CORRESPONDING_DEVICE_PLATFORM_NAME=iphoneos
                       export CORRESPONDING_DEVICE_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk
                       export CORRESPONDING_DEVICE_SDK_NAME=iphoneos11.4
                       export CP=/bin/cp
                       export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
                       export CURRENT_ARCH=x86_64
                       export CURRENT_PROJECT_VERSION=1
                       export CURRENT_VARIANT=normal
                       export DEAD_CODE_STRIPPING=YES
                       export DEBUGGING_SYMBOLS=YES
                       export DEBUG_INFORMATION_FORMAT=dwarf
                       export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
                       export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
                       export DEFINES_MODULE=NO
                       export DEPLOYMENT_LOCATION=NO
                       export DEPLOYMENT_POSTPROCESSING=NO
                       export DEPLOYMENT_TARGET_CLANG_ENV_NAME=IPHONEOS_DEPLOYMENT_TARGET
                       export DEPLOYMENT_TARGET_CLANG_FLAG_NAME=mios-simulator-version-min
                       export DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX=-mios-simulator-version-min=
                       export DEPLOYMENT_TARGET_SETTING_NAME=IPHONEOS_DEPLOYMENT_TARGET
                       export DEPLOYMENT_TARGET_SUGGESTED_VALUES="8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4"
                       export DERIVED_FILES_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
                       export DERIVED_FILE_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
                       export DERIVED_SOURCES_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
                       export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
                       export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
                       export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
                       export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
                       export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
                       export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
                       export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
                       export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
                       export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
                       export DEVELOPMENT_LANGUAGE=English
                       export DOCUMENTATION_FOLDER_PATH=Runner.app/English.lproj/Documentation
                       export DO_HEADER_SCANNING_IN_JAM=NO
                       export DSTROOT=/tmp/Runner.dst
                       export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
                       export DWARF_DSYM_FILE_NAME=Runner.app.dSYM
                       export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
                       export DWARF_DSYM_FOLDER_PATH=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator
                       export EFFECTIVE_PLATFORM_NAME=-iphonesimulator
                       export EMBEDDED_CONTENT_CONTAINS_SWIFT=NO
                       export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
                       export ENABLE_BITCODE=NO
                       export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES
                       export ENABLE_HEADER_DEPENDENCIES=YES
                       export ENABLE_ON_DEMAND_RESOURCES=YES
                       export ENABLE_STRICT_OBJC_MSGSEND=YES
                       export ENABLE_TESTABILITY=YES
                       export ENTITLEMENTS_REQUIRED=YES
                       export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
                       export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
                       export EXECUTABLES_FOLDER_PATH=Runner.app/Executables
                       export EXECUTABLE_FOLDER_PATH=Runner.app
                       export EXECUTABLE_NAME=Runner
                       export EXECUTABLE_PATH=Runner.app/Runner
                       export EXPANDED_CODE_SIGN_IDENTITY=-
                       export EXPANDED_CODE_SIGN_IDENTITY_NAME=-
                       export EXPANDED_PROVISIONING_PROFILE=
                       export FILE_LIST=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects/LinkFileList
                       export FIXED_FILES_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/FixedFiles
                       export FLUTTER_APPLICATION_PATH=/Users/filiph/dev/reactive_exploration/hello_world_start
                       export FLUTTER_BUILD_DIR=build
                       export FLUTTER_BUILD_MODE=debug
                       export FLUTTER_FRAMEWORK_DIR=/Users/filiph/dev/flutter/bin/cache/artifacts/engine/ios
                       export FLUTTER_ROOT=/Users/filiph/dev/flutter
                       export FLUTTER_TARGET=lib/main.dart
                       export FRAMEWORKS_FOLDER_PATH=Runner.app/Frameworks
                       export FRAMEWORK_FLAG_PREFIX=-framework
                       export FRAMEWORK_SEARCH_PATHS="/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator  /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter"
                       export FRAMEWORK_VERSION=A
                       export FULL_PRODUCT_NAME=Runner.app
                       export GCC3_VERSION=3.3
                       export GCC_C_LANGUAGE_STANDARD=gnu99
                       export GCC_DYNAMIC_NO_PIC=NO
                       export GCC_INLINES_ARE_PRIVATE_EXTERN=YES
                       export GCC_NO_COMMON_BLOCKS=YES
                       export GCC_OBJC_LEGACY_DISPATCH=YES
                       export GCC_OPTIMIZATION_LEVEL=0
                       export GCC_PFE_FILE_C_DIALECTS="c objective-c c++ objective-c++"
                       export GCC_PREPROCESSOR_DEFINITIONS="DEBUG=1 "
                       export GCC_SYMBOLS_PRIVATE_EXTERN=NO
                       export GCC_TREAT_WARNINGS_AS_ERRORS=NO
                       export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
                       export GCC_VERSION_IDENTIFIER=com_apple_compilers_llvm_clang_1_0
                       export GCC_WARN_64_TO_32_BIT_CONVERSION=YES
                       export GCC_WARN_ABOUT_RETURN_TYPE=YES_ERROR
                       export GCC_WARN_UNDECLARED_SELECTOR=YES
                       export GCC_WARN_UNINITIALIZED_AUTOS=YES_AGGRESSIVE
                       export GCC_WARN_UNUSED_FUNCTION=YES
                       export GCC_WARN_UNUSED_VARIABLE=YES
                       export GENERATE_MASTER_OBJECT_FILE=NO
                       export GENERATE_PKGINFO_FILE=YES
                       export GENERATE_PROFILING_CODE=NO
                       export GENERATE_TEXT_BASED_STUBS=NO
                       export GID=5000
                       export GROUP=eng
                       export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
                       export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
                       export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
                       export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
                       export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
                       export HEADERMAP_USES_VFS=NO
                       export HEADER_SEARCH_PATHS="/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/include "
                       export HIDE_BITCODE_SYMBOLS=YES
                       export HOME=/Users/filiph
                       export ICONV=/usr/bin/iconv
                       export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
                       export INFOPLIST_FILE=Runner/Info.plist
                       export INFOPLIST_OUTPUT_FORMAT=binary
                       export INFOPLIST_PATH=Runner.app/Info.plist
                       export INFOPLIST_PREPROCESS=NO
                       export INFOSTRINGS_PATH=Runner.app/English.lproj/InfoPlist.strings
                       export INLINE_PRIVATE_FRAMEWORKS=NO
                       export INSTALLHDRS_COPY_PHASE=NO
                       export INSTALLHDRS_SCRIPT_PHASE=NO
                       export INSTALL_DIR=/tmp/Runner.dst/Applications
                       export INSTALL_GROUP=eng
                       export INSTALL_MODE_FLAG=u+w,go-w,a+rX
                       export INSTALL_OWNER=filiph
                       export INSTALL_PATH=/Applications
                       export INSTALL_ROOT=/tmp/Runner.dst
                       export IPHONEOS_DEPLOYMENT_TARGET=8.0
                       export JAVAC_DEFAULT_FLAGS="-J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8"
                       export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
                       export JAVA_ARCHIVE_CLASSES=YES
                       export JAVA_ARCHIVE_TYPE=JAR
                       export JAVA_COMPILER=/usr/bin/javac
                       export JAVA_FOLDER_PATH=Runner.app/Java
                       export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
                       export JAVA_JAR_FLAGS=cv
                       export JAVA_SOURCE_SUBDIR=.
                       export JAVA_USE_DEPENDENCIES=YES
                       export JAVA_ZIP_FLAGS=-urg
                       export JIKES_DEFAULT_FLAGS="+E +OLDCSO"
                       export KEEP_PRIVATE_EXTERNS=NO
                       export LD_DEPENDENCY_INFO_FILE=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat
                       export LD_GENERATE_MAP_FILE=NO
                       export LD_MAP_FILE_PATH=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-LinkMap-normal-x86_64.txt
                       export LD_NO_PIE=NO
                       export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
                       export LD_RUNPATH_SEARCH_PATHS=" @executable_path/Frameworks"
                       export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
                       export LEX=lex
                       export LIBRARY_FLAG_NOSPACE=YES
                       export LIBRARY_FLAG_PREFIX=-l
                       export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
                       export LIBRARY_SEARCH_PATHS="/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator  /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter"
                       export LINKER_DISPLAYS_MANGLED_NAMES=NO
                       export LINK_FILE_LIST_normal_x86_64=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.LinkFileList
                       export LINK_WITH_STANDARD_LIBRARIES=YES
                       export LOCALIZABLE_CONTENT_DIR=
                       export LOCALIZED_RESOURCES_FOLDER_PATH=Runner.app/English.lproj
                       export LOCALIZED_STRING_MACRO_NAMES="NSLocalizedString CFLocalizedString"
                       export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
                       export LOCAL_APPS_DIR=/Applications
                       export LOCAL_DEVELOPER_DIR=/Library/Developer
                       export LOCAL_LIBRARY_DIR=/Library
                       export LOCROOT=
                       export LOCSYMROOT=
                       export MACH_O_TYPE=mh_execute
                       export MAC_OS_X_PRODUCT_BUILD_VERSION=17E202
                       export MAC_OS_X_VERSION_ACTUAL=101304
                       export MAC_OS_X_VERSION_MAJOR=101300
                       export MAC_OS_X_VERSION_MINOR=1304
                       export METAL_LIBRARY_FILE_BASE=default
                       export METAL_LIBRARY_OUTPUT_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app
                       export MODULE_CACHE_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
                       export MTL_ENABLE_DEBUG_INFO=YES
                       export NATIVE_ARCH=i386
                       export NATIVE_ARCH_32_BIT=i386
                       export NATIVE_ARCH_64_BIT=x86_64
                       export NATIVE_ARCH_ACTUAL=x86_64
                       export NO_COMMON=YES
                       export OBJC_ABI_VERSION=2
                       export OBJECT_FILE_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects
                       export OBJECT_FILE_DIR_normal=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
                       export OBJROOT=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex
                       export ONLY_ACTIVE_ARCH=YES
                       export OS=MACOS
                       export OSAC=/usr/bin/osacompile
                       export PACKAGE_TYPE=com.apple.package-type.wrapper.application
                       export PASCAL_STRINGS=YES
                       export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Tools:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:/Users/filiph/.pub-cache/bin:/Users/filiph/gsutil:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"
                       export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
                       export PBDEVELOPMENTPLIST_PATH=Runner.app/pbdevelopment.plist
                       export PFE_FILE_C_DIALECTS=objective-c
                       export PKGINFO_FILE_PATH=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PkgInfo
                       export PKGINFO_PATH=Runner.app/PkgInfo
                       export PLATFORM_DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
                       export PLATFORM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
                       export PLATFORM_DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
                       export PLATFORM_DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
                       export PLATFORM_DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
                       export PLATFORM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
                       export PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
                       export PLATFORM_DISPLAY_NAME="iOS Simulator"
                       export PLATFORM_NAME=iphonesimulator
                       export PLATFORM_PREFERRED_ARCH=x86_64
                       export PLIST_FILE_OUTPUT_FORMAT=binary
                       export PLUGINS_FOLDER_PATH=Runner.app/PlugIns
                       export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
                       export PRECOMP_DESTINATION_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PrefixHeaders
                       export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
                       export PREVIEW_DART_2=true
                       export PRIVATE_HEADERS_FOLDER_PATH=Runner.app/PrivateHeaders
                       export PRODUCT_BUNDLE_IDENTIFIER=hello_world.flutter.io.helloWorldStart
                       export PRODUCT_MODULE_NAME=Runner
                       export PRODUCT_NAME=Runner
                       export PRODUCT_SETTINGS_PATH=/Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/Info.plist
                       export PRODUCT_TYPE=com.apple.product-type.application
                       export PROFILING_CODE=NO
                       export PROJECT=Runner
                       export PROJECT_DERIVED_FILE_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/DerivedSources
                       export PROJECT_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export PROJECT_FILE_PATH=/Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner.xcodeproj
                       export PROJECT_NAME=Runner
                       export PROJECT_TEMP_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build
                       export PROJECT_TEMP_ROOT=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex
                       export PUBLIC_HEADERS_FOLDER_PATH=Runner.app/Headers
                       export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS=YES
                       export REMOVE_CVS_FROM_RESOURCES=YES
                       export REMOVE_GIT_FROM_RESOURCES=YES
                       export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
                       export REMOVE_HG_FROM_RESOURCES=YES
                       export REMOVE_SVN_FROM_RESOURCES=YES
                       export REZ_COLLECTOR_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources
                       export REZ_OBJECTS_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources/Objects
                       export REZ_SEARCH_PATHS="/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator "
                       export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
                       export SCRIPTS_FOLDER_PATH=Runner.app/Scripts
                       export SCRIPT_INPUT_FILE_COUNT=0
                       export SCRIPT_OUTPUT_FILE_COUNT=0
                       export SCRIPT_OUTPUT_STREAM_FILE=/var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/flutter_build_log_pipeeWkOLu/pipe_to_stdout
                       export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk
                       export SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk
                       export SDK_DIR_iphonesimulator11_4=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk
                       export SDK_NAME=iphonesimulator11.4
                       export SDK_NAMES=iphonesimulator11.4
                       export SDK_PRODUCT_BUILD_VERSION=15F79
                       export SDK_VERSION=11.4
                       export SDK_VERSION_ACTUAL=110400
                       export SDK_VERSION_MAJOR=110000
                       export SDK_VERSION_MINOR=400
                       export SED=/usr/bin/sed
                       export SEPARATE_STRIP=NO
                       export SEPARATE_SYMBOL_EDIT=NO
                       export SET_DIR_MODE_OWNER_GROUP=YES
                       export SET_FILE_MODE_OWNER_GROUP=NO
                       export SHALLOW_BUNDLE=YES
                       export SHARED_DERIVED_FILE_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/DerivedSources
                       export SHARED_FRAMEWORKS_FOLDER_PATH=Runner.app/SharedFrameworks
                       export SHARED_PRECOMPS_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/PrecompiledHeaders
                       export SHARED_SUPPORT_FOLDER_PATH=Runner.app/SharedSupport
                       export SKIP_INSTALL=NO
                       export SOURCE_ROOT=/Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export SRCROOT=/Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export STRINGS_FILE_OUTPUT_ENCODING=binary
                       export STRIP_BITCODE_FROM_COPIED_FILES=NO
                       export STRIP_INSTALLED_PRODUCT=YES
                       export STRIP_STYLE=all
                       export STRIP_SWIFT_SYMBOLS=YES
                       export SUPPORTED_DEVICE_FAMILIES=1,2
                       export SUPPORTED_PLATFORMS="iphonesimulator iphoneos"
                       export SUPPORTS_TEXT_BASED_API=NO
                       export SWIFT_OBJC_BRIDGING_HEADER=Runner/Runner-Bridging-Header.h
                       export SWIFT_OPTIMIZATION_LEVEL=-Onone
                       export SWIFT_PLATFORM_TARGET_PREFIX=ios
                       export SWIFT_SWIFT3_OBJC_INFERENCE=On
                       export SWIFT_VERSION=4.0
                       export SYMROOT=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Products
                       export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
                       export SYSTEM_APPS_DIR=/Applications
                       export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
                       export SYSTEM_DEMOS_DIR=/Applications/Extras
                       export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
                       export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
                       export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
                       export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
                       export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
                       export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
                       export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
                       export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
                       export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
                       export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
                       export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
                       export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
                       export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
                       export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
                       export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
                       export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
                       export SYSTEM_LIBRARY_DIR=/System/Library
                       export TAPI_VERIFY_MODE=ErrorsOnly
                       export TARGETED_DEVICE_FAMILY=1,2
                       export TARGETNAME=Runner
                       export TARGET_BUILD_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator
                       export TARGET_DEVICE_IDENTIFIER="dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder"
                       export TARGET_NAME=Runner
                       export TARGET_TEMP_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
                       export TEMP_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
                       export TEMP_FILES_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
                       export TEMP_FILE_DIR=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
                       export TEMP_ROOT=/Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex
                       export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
                       export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
                       export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
                       export UID=74285
                       export UNLOCALIZED_RESOURCES_FOLDER_PATH=Runner.app
                       export UNSTRIPPED_PRODUCT=NO
                       export USER=filiph
                       export USER_APPS_DIR=/Users/filiph/Applications
                       export USER_LIBRARY_DIR=/Users/filiph/Library
                       export USE_DYNAMIC_NO_PIC=YES
                       export USE_HEADERMAP=YES
                       export USE_HEADER_SYMLINKS=NO
                       export VALIDATE_PRODUCT=NO
                       export VALID_ARCHS="i386 x86_64"
                       export VERBOSE_PBXCP=NO
                       export VERBOSE_SCRIPT_LOGGING=YES
                       export VERSIONING_SYSTEM=apple-generic
                       export VERSIONPLIST_PATH=Runner.app/version.plist
                       export VERSION_INFO_BUILDER=filiph
                       export VERSION_INFO_FILE=Runner_vers.c
                       export VERSION_INFO_STRING="\"@(#)PROGRAM:Runner  PROJECT:Runner-1\""
                       export WRAPPER_EXTENSION=app
                       export WRAPPER_NAME=Runner.app
                       export WRAPPER_SUFFIX=.app
                       export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
                       export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
                       export XCODE_PRODUCT_BUILD_VERSION=9F1027a
                       export XCODE_VERSION_ACTUAL=0940
                       export XCODE_VERSION_MAJOR=0900
                       export XCODE_VERSION_MINOR=0940
                       export XPCSERVICES_FOLDER_PATH=Runner.app/XPCServices
                       export YACC=yacc
                       export arch=x86_64
                       export variant=normal
                       /bin/sh -c /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh

                   CopySwiftLibs /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
                       export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
                       export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"
                       export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk
                       builtin-swiftStdLibTool --copy --verbose --sign - --scan-executable /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Runner --scan-folder /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks --scan-folder /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/PlugIns --scan-folder /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/Flutter.framework --scan-folder /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter/App.framework --platform iphonesimulator --toolchain /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain --destination /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks --strip-bitcode --resource-destination /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app --resource-library libswiftRemoteMirror.dylib
                   Requested Swift ABI version based on scanned binaries: 6
                   libswiftCore.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
                   libswiftCoreAudio.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib
                   libswiftCoreFoundation.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
                   libswiftCoreGraphics.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
                   libswiftCoreImage.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib
                   libswiftCoreMedia.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib
                   libswiftDarwin.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
                   libswiftDispatch.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
                   libswiftFoundation.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
                   libswiftMetal.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib
                   libswiftObjectiveC.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
                   libswiftQuartzCore.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib
                   libswiftUIKit.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib
                   libswiftos.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib
                   libswiftRemoteMirror.dylib is up to date at /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/libswiftRemoteMirror.dylib
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib'
                   Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib'
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib'
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib is unchanged; keeping original
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib'
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib'
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib'
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib'
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib'
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib'
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib'
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib'
                   Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib
                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib'
                   Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib
                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib'Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib

                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib'
                   Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
                   Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib
                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib'
                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib'
                   Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
                   Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib
                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib'
                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib'
                   Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib'
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib'
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib'
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib'
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib'
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib'
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib'
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib'
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib is unchanged; keeping original
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib is unchanged; keeping original
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib'
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib'
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib is unchanged; keeping original
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib is unchanged; keeping original
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib is unchanged; keeping original
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib is unchanged; keeping original
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib'
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib'
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib'
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib is unchanged; keeping original
                   Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib'
                   Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib'
                   Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
                   Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib
                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib'Codesigning /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib

                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib'
                     /usr/bin/codesign '--force' '--sign' '-' '--verbose' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib'
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib'
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib'
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib'
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib'
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib'
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib is unchanged; keeping original
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib is unchanged; keeping original
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib is unchanged; keeping original
                   Probing signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
                     /usr/bin/codesign '-r-' '--display' '/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib'
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib is unchanged; keeping original
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib is unchanged; keeping original
                   Code signature of /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib is unchanged; keeping original

                   Touch /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"
                       /usr/bin/touch -c /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app

                   CodeSign /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app
                       cd /Users/filiph/dev/reactive_exploration/hello_world_start/ios
                       export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
                       export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin"

                   Signing Identity:     "-"

                       /usr/bin/codesign --force --sign - --entitlements /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app.xcent --timestamp=none /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app

                   ** BUILD SUCCEEDED **
[  +21 ms] Xcode build done.
[        ] [ios/] /usr/bin/env xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios -sdk iphonesimulator -arch x86_64 SCRIPT_OUTPUT_STREAM_FILE=/var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/flutter_build_log_pipeeWkOLu/pipe_to_stdout -showBuildSettings
[ +724 ms] Exit code 0 from: /usr/bin/env xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/filiph/dev/reactive_exploration/hello_world_start/build/ios -sdk iphonesimulator -arch x86_64 SCRIPT_OUTPUT_STREAM_FILE=/var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/flutter_build_log_pipeeWkOLu/pipe_to_stdout -showBuildSettings
[        ] Build settings from command line:
               ARCHS = x86_64
               BUILD_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios
               SCRIPT_OUTPUT_STREAM_FILE = /var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/flutter_build_log_pipeeWkOLu/pipe_to_stdout
               SDKROOT = iphonesimulator11.4
               VERBOSE_SCRIPT_LOGGING = YES

           Build settings for action build and target Runner:
               ACTION = build
               AD_HOC_CODE_SIGNING_ALLOWED = YES
               ALTERNATE_GROUP = eng
               ALTERNATE_MODE = u+w,go-w,a+rX
               ALTERNATE_OWNER = filiph
               ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO
               ALWAYS_SEARCH_USER_PATHS = NO
               ALWAYS_USE_SEPARATE_HEADERMAPS = NO
               APPLE_INTERNAL_DEVELOPER_DIR = /AppleInternal/Developer
               APPLE_INTERNAL_DIR = /AppleInternal
               APPLE_INTERNAL_DOCUMENTATION_DIR = /AppleInternal/Documentation
               APPLE_INTERNAL_LIBRARY_DIR = /AppleInternal/Library
               APPLE_INTERNAL_TOOLS = /AppleInternal/Developer/Tools
               APPLICATION_EXTENSION_API_ONLY = NO
               APPLY_RULES_IN_COPY_FILES = NO
               ARCHS = x86_64
               ARCHS_STANDARD = i386 x86_64
               ARCHS_STANDARD_32_64_BIT = i386 x86_64
               ARCHS_STANDARD_32_BIT = i386
               ARCHS_STANDARD_64_BIT = x86_64
               ARCHS_STANDARD_INCLUDING_64_BIT = i386 x86_64
               ARCHS_UNIVERSAL_IPHONE_OS = i386 x86_64
               ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
               AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator
               BITCODE_GENERATION_MODE = marker
               BUILD_ACTIVE_RESOURCES_ONLY = NO
               BUILD_COMPONENTS = headers build
               BUILD_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios
               BUILD_ROOT = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Products
               BUILD_STYLE =
               BUILD_VARIANTS = normal
               BUILT_PRODUCTS_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator
               CACHE_ROOT = /var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/C/com.apple.DeveloperTools/9.4-9F1027a/Xcode
               CCHROOT = /var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/C/com.apple.DeveloperTools/9.4-9F1027a/Xcode
               CHMOD = /bin/chmod
               CHOWN = /usr/sbin/chown
               CLANG_ANALYZER_NONNULL = YES
               CLANG_CXX_LANGUAGE_STANDARD = gnu++0x
               CLANG_CXX_LIBRARY = libc++
               CLANG_ENABLE_MODULES = YES
               CLANG_ENABLE_OBJC_ARC = YES
               CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
               CLANG_WARN_BOOL_CONVERSION = YES
               CLANG_WARN_COMMA = YES
               CLANG_WARN_CONSTANT_CONVERSION = YES
               CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR
               CLANG_WARN_EMPTY_BODY = YES
               CLANG_WARN_ENUM_CONVERSION = YES
               CLANG_WARN_INFINITE_RECURSION = YES
               CLANG_WARN_INT_CONVERSION = YES
               CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
               CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
               CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR
               CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
               CLANG_WARN_STRICT_PROTOTYPES = YES
               CLANG_WARN_SUSPICIOUS_MOVE = YES
               CLANG_WARN_UNREACHABLE_CODE = YES
               CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
               CLASS_FILE_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/JavaClasses
               CLEAN_PRECOMPS = YES
               CLONE_HEADERS = NO
               CODESIGNING_FOLDER_PATH = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app
               CODE_SIGNING_ALLOWED = YES
               CODE_SIGNING_REQUIRED = YES
               CODE_SIGN_CONTEXT_CLASS = XCiPhoneSimulatorCodeSignContext
               CODE_SIGN_IDENTITY = -
               CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
               COLOR_DIAGNOSTICS = NO
               COMBINE_HIDPI_IMAGES = NO
               COMPILER_INDEX_STORE_ENABLE = Default
               COMPOSITE_SDK_DIRS = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/CompositeSDKs
               COMPRESS_PNG_FILES = YES
               CONFIGURATION = Debug
               CONFIGURATION_BUILD_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator
               CONFIGURATION_TEMP_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator
               CONTENTS_FOLDER_PATH = Runner.app
               COPYING_PRESERVES_HFS_DATA = NO
               COPY_HEADERS_RUN_UNIFDEF = NO
               COPY_PHASE_STRIP = NO
               COPY_RESOURCES_FROM_STATIC_FRAMEWORKS = YES
               CORRESPONDING_DEVICE_PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               CORRESPONDING_DEVICE_PLATFORM_NAME = iphoneos
               CORRESPONDING_DEVICE_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk
               CORRESPONDING_DEVICE_SDK_NAME = iphoneos11.4
               CP = /bin/cp
               CREATE_INFOPLIST_SECTION_IN_BINARY = NO
               CURRENT_ARCH = x86_64
               CURRENT_PROJECT_VERSION = 1
               CURRENT_VARIANT = normal
               DEAD_CODE_STRIPPING = YES
               DEBUGGING_SYMBOLS = YES
               DEBUG_INFORMATION_FORMAT = dwarf
               DEFAULT_COMPILER = com.apple.compilers.llvm.clang.1_0
               DEFAULT_KEXT_INSTALL_PATH = /System/Library/Extensions
               DEFINES_MODULE = NO
               DEPLOYMENT_LOCATION = NO
               DEPLOYMENT_POSTPROCESSING = NO
               DEPLOYMENT_TARGET_CLANG_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_CLANG_FLAG_NAME = mios-simulator-version-min
               DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX = -mios-simulator-version-min=
               DEPLOYMENT_TARGET_SETTING_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_SUGGESTED_VALUES = 8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4
               DERIVED_FILES_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               DERIVED_FILE_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               DERIVED_SOURCES_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               DEVELOPER_FRAMEWORKS_DIR = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_FRAMEWORKS_DIR_QUOTED = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/Developer/Library
               DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Tools
               DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               DEVELOPMENT_LANGUAGE = English
               DOCUMENTATION_FOLDER_PATH = Runner.app/English.lproj/Documentation
               DO_HEADER_SCANNING_IN_JAM = NO
               DSTROOT = /tmp/Runner.dst
               DT_TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               DWARF_DSYM_FILE_NAME = Runner.app.dSYM
               DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
               DWARF_DSYM_FOLDER_PATH = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator
               EFFECTIVE_PLATFORM_NAME = -iphonesimulator
               EMBEDDED_CONTENT_CONTAINS_SWIFT = NO
               EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE = NO
               ENABLE_BITCODE = NO
               ENABLE_DEFAULT_HEADER_SEARCH_PATHS = YES
               ENABLE_HEADER_DEPENDENCIES = YES
               ENABLE_ON_DEMAND_RESOURCES = YES
               ENABLE_STRICT_OBJC_MSGSEND = YES
               ENABLE_TESTABILITY = YES
               ENTITLEMENTS_REQUIRED = YES
               EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS = .DS_Store .svn .git .hg CVS
               EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES = *.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj
               EXECUTABLES_FOLDER_PATH = Runner.app/Executables
               EXECUTABLE_FOLDER_PATH = Runner.app
               EXECUTABLE_NAME = Runner
               EXECUTABLE_PATH = Runner.app/Runner
               EXPANDED_CODE_SIGN_IDENTITY =
               EXPANDED_CODE_SIGN_IDENTITY_NAME =
               EXPANDED_PROVISIONING_PROFILE =
               FILE_LIST = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects/LinkFileList
               FIXED_FILES_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/FixedFiles
               FLUTTER_APPLICATION_PATH = /Users/filiph/dev/reactive_exploration/hello_world_start
               FLUTTER_BUILD_DIR = build
               FLUTTER_BUILD_MODE = debug
               FLUTTER_FRAMEWORK_DIR = /Users/filiph/dev/flutter/bin/cache/artifacts/engine/ios
               FLUTTER_ROOT = /Users/filiph/dev/flutter
               FLUTTER_TARGET = lib/main.dart
               FRAMEWORKS_FOLDER_PATH = Runner.app/Frameworks
               FRAMEWORK_FLAG_PREFIX = -framework
               FRAMEWORK_SEARCH_PATHS =  /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter
               FRAMEWORK_VERSION = A
               FULL_PRODUCT_NAME = Runner.app
               GCC3_VERSION = 3.3
               GCC_C_LANGUAGE_STANDARD = gnu99
               GCC_DYNAMIC_NO_PIC = NO
               GCC_INLINES_ARE_PRIVATE_EXTERN = YES
               GCC_NO_COMMON_BLOCKS = YES
               GCC_OBJC_LEGACY_DISPATCH = YES
               GCC_OPTIMIZATION_LEVEL = 0
               GCC_PFE_FILE_C_DIALECTS = c objective-c c++ objective-c++
               GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
               GCC_SYMBOLS_PRIVATE_EXTERN = NO
               GCC_TREAT_WARNINGS_AS_ERRORS = NO
               GCC_VERSION = com.apple.compilers.llvm.clang.1_0
               GCC_VERSION_IDENTIFIER = com_apple_compilers_llvm_clang_1_0
               GCC_WARN_64_TO_32_BIT_CONVERSION = YES
               GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR
               GCC_WARN_UNDECLARED_SELECTOR = YES
               GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE
               GCC_WARN_UNUSED_FUNCTION = YES
               GCC_WARN_UNUSED_VARIABLE = YES
               GENERATE_MASTER_OBJECT_FILE = NO
               GENERATE_PKGINFO_FILE = YES
               GENERATE_PROFILING_CODE = NO
               GENERATE_TEXT_BASED_STUBS = NO
               GID = 5000
               GROUP = eng
               HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT = YES
               HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES = YES
               HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS = YES
               HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
               HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
               HEADERMAP_USES_VFS = NO
               HIDE_BITCODE_SYMBOLS = YES
               HOME = /Users/filiph
               ICONV = /usr/bin/iconv
               INFOPLIST_EXPAND_BUILD_SETTINGS = YES
               INFOPLIST_FILE = Runner/Info.plist
               INFOPLIST_OUTPUT_FORMAT = binary
               INFOPLIST_PATH = Runner.app/Info.plist
               INFOPLIST_PREPROCESS = NO
               INFOSTRINGS_PATH = Runner.app/English.lproj/InfoPlist.strings
               INLINE_PRIVATE_FRAMEWORKS = NO
               INSTALLHDRS_COPY_PHASE = NO
               INSTALLHDRS_SCRIPT_PHASE = NO
               INSTALL_DIR = /tmp/Runner.dst/Applications
               INSTALL_GROUP = eng
               INSTALL_MODE_FLAG = u+w,go-w,a+rX
               INSTALL_OWNER = filiph
               INSTALL_PATH = /Applications
               INSTALL_ROOT = /tmp/Runner.dst
               IPHONEOS_DEPLOYMENT_TARGET = 8.0
               JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8
               JAVA_APP_STUB = /System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               JAVA_ARCHIVE_CLASSES = YES
               JAVA_ARCHIVE_TYPE = JAR
               JAVA_COMPILER = /usr/bin/javac
               JAVA_FOLDER_PATH = Runner.app/Java
               JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
               JAVA_JAR_FLAGS = cv
               JAVA_SOURCE_SUBDIR = .
               JAVA_USE_DEPENDENCIES = YES
               JAVA_ZIP_FLAGS = -urg
               JIKES_DEFAULT_FLAGS = +E +OLDCSO
               KEEP_PRIVATE_EXTERNS = NO
               LD_DEPENDENCY_INFO_FILE = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat
               LD_GENERATE_MAP_FILE = NO
               LD_MAP_FILE_PATH = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-LinkMap-normal-x86_64.txt
               LD_NO_PIE = NO
               LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
               LD_RUNPATH_SEARCH_PATHS =  @executable_path/Frameworks
               LEGACY_DEVELOPER_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               LEX = lex
               LIBRARY_FLAG_NOSPACE = YES
               LIBRARY_FLAG_PREFIX = -l
               LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
               LIBRARY_SEARCH_PATHS =  /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Flutter
               LINKER_DISPLAYS_MANGLED_NAMES = NO
               LINK_FILE_LIST_normal_x86_64 =
               LINK_WITH_STANDARD_LIBRARIES = YES
               LOCALIZABLE_CONTENT_DIR =
               LOCALIZED_RESOURCES_FOLDER_PATH = Runner.app/English.lproj
               LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString CFLocalizedString
               LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
               LOCAL_APPS_DIR = /Applications
               LOCAL_DEVELOPER_DIR = /Library/Developer
               LOCAL_LIBRARY_DIR = /Library
               LOCROOT =
               LOCSYMROOT =
               MACH_O_TYPE = mh_execute
               MAC_OS_X_PRODUCT_BUILD_VERSION = 17E202
               MAC_OS_X_VERSION_ACTUAL = 101304
               MAC_OS_X_VERSION_MAJOR = 101300
               MAC_OS_X_VERSION_MINOR = 1304
               METAL_LIBRARY_FILE_BASE = default
               METAL_LIBRARY_OUTPUT_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/Runner.app
               MODULE_CACHE_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               MTL_ENABLE_DEBUG_INFO = YES
               NATIVE_ARCH = i386
               NATIVE_ARCH_32_BIT = i386
               NATIVE_ARCH_64_BIT = x86_64
               NATIVE_ARCH_ACTUAL = x86_64
               NO_COMMON = YES
               OBJC_ABI_VERSION = 2
               OBJECT_FILE_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects
               OBJECT_FILE_DIR_normal = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
               OBJROOT = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex
               ONLY_ACTIVE_ARCH = YES
               OS = MACOS
               OSAC = /usr/bin/osacompile
               PACKAGE_TYPE = com.apple.package-type.wrapper.application
               PASCAL_STRINGS = YES
               PATH = /Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/google-cloud-sdk/bin:/usr/local/var/pyenv/shims:/Users/filiph/.nvm/versions/node/v6.10.3/bin:/Users/filiph/.rvm/gems/ruby-2.3.1/bin:/Users/filiph/.rvm/gems/ruby-2.3.1@global/bin:/Users/filiph/.rvm/rubies/ruby-2.3.1/bin:/Users/filiph/dev/flutter/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/dart/dart-sdk/bin:~/.pub-cache/bin:/Users/filiph/gsutil:~/.pub-cache/bin:/usr/local/bin/depot_tools:/Users/filiph/.rvm/bin
               PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES = /usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms
               PBDEVELOPMENTPLIST_PATH = Runner.app/pbdevelopment.plist
               PFE_FILE_C_DIALECTS = objective-c
               PKGINFO_FILE_PATH = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PkgInfo
               PKGINFO_PATH = Runner.app/PkgInfo
               PLATFORM_DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
               PLATFORM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
               PLATFORM_DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
               PLATFORM_DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
               PLATFORM_DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
               PLATFORM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
               PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               PLATFORM_DISPLAY_NAME = iOS Simulator
               PLATFORM_NAME = iphonesimulator
               PLATFORM_PREFERRED_ARCH = x86_64
               PLIST_FILE_OUTPUT_FORMAT = binary
               PLUGINS_FOLDER_PATH = Runner.app/PlugIns
               PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR = YES
               PRECOMP_DESTINATION_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PrefixHeaders
               PRESERVE_DEAD_CODE_INITS_AND_TERMS = NO
               PREVIEW_DART_2 = true
               PRIVATE_HEADERS_FOLDER_PATH = Runner.app/PrivateHeaders
               PRODUCT_BUNDLE_IDENTIFIER = hello_world.flutter.io.helloWorldStart
               PRODUCT_MODULE_NAME = Runner
               PRODUCT_NAME = Runner
               PRODUCT_SETTINGS_PATH = /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner/Info.plist
               PRODUCT_TYPE = com.apple.product-type.application
               PROFILING_CODE = NO
               PROJECT = Runner
               PROJECT_DERIVED_FILE_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/DerivedSources
               PROJECT_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/ios
               PROJECT_FILE_PATH = /Users/filiph/dev/reactive_exploration/hello_world_start/ios/Runner.xcodeproj
               PROJECT_NAME = Runner
               PROJECT_TEMP_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build
               PROJECT_TEMP_ROOT = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex
               PUBLIC_HEADERS_FOLDER_PATH = Runner.app/Headers
               RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS = YES
               REMOVE_CVS_FROM_RESOURCES = YES
               REMOVE_GIT_FROM_RESOURCES = YES
               REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES = YES
               REMOVE_HG_FROM_RESOURCES = YES
               REMOVE_SVN_FROM_RESOURCES = YES
               REZ_COLLECTOR_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources
               REZ_OBJECTS_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources/Objects
               SCAN_ALL_SOURCE_FILES_FOR_INCLUDES = NO
               SCRIPTS_FOLDER_PATH = Runner.app/Scripts
               SCRIPT_OUTPUT_STREAM_FILE = /var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/flutter_build_log_pipeeWkOLu/pipe_to_stdout
               SDKROOT = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk
               SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk
               SDK_DIR_iphonesimulator11_4 = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk
               SDK_NAME = iphonesimulator11.4
               SDK_NAMES = iphonesimulator11.4
               SDK_PRODUCT_BUILD_VERSION = 15F79
               SDK_VERSION = 11.4
               SDK_VERSION_ACTUAL = 110400
               SDK_VERSION_MAJOR = 110000
               SDK_VERSION_MINOR = 400
               SED = /usr/bin/sed
               SEPARATE_STRIP = NO
               SEPARATE_SYMBOL_EDIT = NO
               SET_DIR_MODE_OWNER_GROUP = YES
               SET_FILE_MODE_OWNER_GROUP = NO
               SHALLOW_BUNDLE = YES
               SHARED_DERIVED_FILE_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator/DerivedSources
               SHARED_FRAMEWORKS_FOLDER_PATH = Runner.app/SharedFrameworks
               SHARED_PRECOMPS_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/PrecompiledHeaders
               SHARED_SUPPORT_FOLDER_PATH = Runner.app/SharedSupport
               SKIP_INSTALL = NO
               SOURCE_ROOT = /Users/filiph/dev/reactive_exploration/hello_world_start/ios
               SRCROOT = /Users/filiph/dev/reactive_exploration/hello_world_start/ios
               STRINGS_FILE_OUTPUT_ENCODING = binary
               STRIP_BITCODE_FROM_COPIED_FILES = NO
               STRIP_INSTALLED_PRODUCT = YES
               STRIP_STYLE = all
               STRIP_SWIFT_SYMBOLS = YES
               SUPPORTED_DEVICE_FAMILIES = 1,2
               SUPPORTED_PLATFORMS = iphonesimulator iphoneos
               SUPPORTS_TEXT_BASED_API = NO
               SWIFT_OBJC_BRIDGING_HEADER = Runner/Runner-Bridging-Header.h
               SWIFT_OPTIMIZATION_LEVEL = -Onone
               SWIFT_PLATFORM_TARGET_PREFIX = ios
               SWIFT_SWIFT3_OBJC_INFERENCE = On
               SWIFT_VERSION = 4.0
               SYMROOT = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Products
               SYSTEM_ADMIN_APPS_DIR = /Applications/Utilities
               SYSTEM_APPS_DIR = /Applications
               SYSTEM_CORE_SERVICES_DIR = /System/Library/CoreServices
               SYSTEM_DEMOS_DIR = /Applications/Extras
               SYSTEM_DEVELOPER_APPS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               SYSTEM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               SYSTEM_DEVELOPER_DEMOS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples
               SYSTEM_DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               SYSTEM_DEVELOPER_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library
               SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools
               SYSTEM_DEVELOPER_JAVA_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Java Tools
               SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Performance Tools
               SYSTEM_DEVELOPER_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes
               SYSTEM_DEVELOPER_TOOLS = /Applications/Xcode.app/Contents/Developer/Tools
               SYSTEM_DEVELOPER_TOOLS_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools
               SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools
               SYSTEM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               SYSTEM_DEVELOPER_UTILITIES_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities
               SYSTEM_DOCUMENTATION_DIR = /Library/Documentation
               SYSTEM_KEXT_INSTALL_PATH = /System/Library/Extensions
               SYSTEM_LIBRARY_DIR = /System/Library
               TAPI_VERIFY_MODE = ErrorsOnly
               TARGETED_DEVICE_FAMILY = 1,2
               TARGETNAME = Runner
               TARGET_BUILD_DIR = /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/Debug-iphonesimulator
               TARGET_NAME = Runner
               TARGET_TEMP_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               TEMP_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               TEMP_FILES_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               TEMP_FILE_DIR = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               TEMP_ROOT = /Users/filiph/Library/Developer/Xcode/DerivedData/Runner-ehcnmfimlvrrtmgmvugxzkzautwv/Build/Intermediates.noindex
               TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               TREAT_MISSING_BASELINES_AS_TEST_FAILURES = NO
               UID = 74285
               UNLOCALIZED_RESOURCES_FOLDER_PATH = Runner.app
               UNSTRIPPED_PRODUCT = NO
               USER = filiph
               USER_APPS_DIR = /Users/filiph/Applications
               USER_LIBRARY_DIR = /Users/filiph/Library
               USE_DYNAMIC_NO_PIC = YES
               USE_HEADERMAP = YES
               USE_HEADER_SYMLINKS = NO
               VALIDATE_PRODUCT = NO
               VALID_ARCHS = i386 x86_64
               VERBOSE_PBXCP = NO
               VERBOSE_SCRIPT_LOGGING = YES
               VERSIONING_SYSTEM = apple-generic
               VERSIONPLIST_PATH = Runner.app/version.plist
               VERSION_INFO_BUILDER = filiph
               VERSION_INFO_FILE = Runner_vers.c
               VERSION_INFO_STRING = "@(#)PROGRAM:Runner  PROJECT:Runner-1"
               WRAPPER_EXTENSION = app
               WRAPPER_NAME = Runner.app
               WRAPPER_SUFFIX = .app
               WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
               XCODE_APP_SUPPORT_DIR = /Applications/Xcode.app/Contents/Developer/Library/Xcode
               XCODE_PRODUCT_BUILD_VERSION = 9F1027a
               XCODE_VERSION_ACTUAL = 0940
               XCODE_VERSION_MAJOR = 0900
               XCODE_VERSION_MINOR = 0940
               XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
               YACC = yacc
               arch = x86_64
               variant = normal
[ +209 ms] /usr/bin/xcrun simctl install 8C0199F9-DE6D-4A50-86F3-875D58FF15E6 /Users/filiph/dev/reactive_exploration/hello_world_start/build/ios/iphonesimulator/Runner.app
[ +954 ms] /usr/bin/xcrun simctl launch 8C0199F9-DE6D-4A50-86F3-875D58FF15E6 hello_world.flutter.io.helloWorldStart --enable-dart-profiling --enable-checked-mode --observatory-port=8100
[ +166 ms] hello_world.flutter.io.helloWorldStart: 63932
[        ] Waiting for observatory port to be available...
[ +445 ms] [DEVICE LOG] 2018-05-29 22:27:25.903559-0700  localhost Runner[63932]: (Runner) Created Activity ID: 0xc0190, Description: Loading Preferences From System CFPrefsD For Search List
[   +1 ms] [DEVICE LOG] 2018-05-29 22:27:25.904127-0700  localhost Runner[63932]: (Runner) Created Activity ID: 0xc0191, Description: Loading Preferences From System CFPrefsD For Search List
[   +9 ms] [DEVICE LOG] 2018-05-29 22:27:25.915592-0700  localhost Runner[63932]: (Runner) Created Activity ID: 0xc0192, Description: Loading Preferences From System CFPrefsD For Search List
[   +5 ms] [DEVICE LOG] 2018-05-29 22:27:25.921418-0700  localhost Runner[63932]: (libAccessibility.dylib) [com.apple.Accessibility:AccessibilitySupport] Retrieving resting unlock: 0
[ +296 ms] [DEVICE LOG] 2018-05-29 22:27:26.217354-0700  localhost Runner[63932]: (UIKit) You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
[        ] [DEVICE LOG] 2018-05-29 22:27:26.217496-0700  localhost Runner[63932]: (UIKit) You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
[        ] [DEVICE LOG] 2018-05-29 22:27:26.217995-0700  localhost Runner[63932]: (Flutter) flutter: Observatory listening on http://127.0.0.1:8100/
[   +2 ms] Observatory URL on device: http://127.0.0.1:8100/
[   +4 ms] Connecting to service protocol: http://127.0.0.1:8100/
[ +145 ms] Successfully connected to service protocol: http://127.0.0.1:8100/
[   +2 ms] getVM: {}
[  +10 ms] getIsolate: {isolateId: isolates/942361266}
[   +2 ms] _flutter.listViews: {}
[  +95 ms] [DEVICE LOG] 2018-05-29 22:27:26.481422-0700  localhost Runner[63932]: (Flutter) flutter: 00:00 \^[[32m+0\^[[0m: - Counter increments smoke test<…>
[   +5 ms] flutter: 00:00 \^[[32m+0\^[[0m: - Counter increments smoke test<…>
[ +130 ms] DevFS: Creating new filesystem on the device (null)
[        ] _createDevFS: {fsName: hello_world_start}
[  +20 ms] DevFS: Created new filesystem on the device (file:///Users/filiph/Library/Developer/CoreSimulator/Devices/8C0199F9-DE6D-4A50-86F3-875D58FF15E6/data/Containers/Data/Application/268FE187-C441-4D14-96EB-EEDECEF38AC7/tmp/hello_world_startdHAKV9/hello_world_start/)
[   +1 ms] Updating assets
[ +147 ms] Syncing files to device iPhone X...
[   +3 ms] DevFS: Starting sync from LocalDirectory: '/Users/filiph/dev/reactive_exploration/hello_world_start'
[        ] Scanning project files
[   +4 ms] Scanning package files
[ +112 ms] Scanning asset files
[        ] Scanning for deleted files
[  +14 ms] Compiling dart to kernel with 669 updated files
[   +2 ms] /Users/filiph/dev/flutter/bin/cache/dart-sdk/bin/dart /Users/filiph/dev/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/filiph/dev/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build/app.dill --packages /Users/filiph/dev/reactive_exploration/hello_world_start/.packages --filesystem-scheme org-dartlang-root
[ +216 ms] [DEVICE LOG] 2018-05-29 22:27:27.142424-0700  localhost Runner[63932]: (Flutter) flutter: (The following exception is now available via WidgetTester.takeException:)
[        ] flutter: (The following exception is now available via WidgetTester.takeException:)
[   +1 ms] [DEVICE LOG] 2018-05-29 22:27:27.144620-0700  localhost Runner[63932]: (Flutter) flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
[        ] flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
[   +4 ms] [DEVICE LOG] 2018-05-29 22:27:27.149599-0700  localhost Runner[63932]: (Flutter) flutter: The following assertion was thrown running a test:
[        ] [DEVICE LOG] 2018-05-29 22:27:27.149736-0700  localhost Runner[63932]: (Flutter) flutter: A SemanticsHandle was active at the end of the test.
[        ] [DEVICE LOG] 2018-05-29 22:27:27.149872-0700  localhost Runner[63932]: (Flutter) flutter: All SemanticsHandle instances must be disposed by calling dispose() on the SemanticsHandle. If your
[        ] flutter: The following assertion was thrown running a test:
[        ] flutter: A SemanticsHandle was active at the end of the test.
[        ] flutter: All SemanticsHandle instances must be disposed by calling dispose() on the SemanticsHandle. If your
[        ] [DEVICE LOG] 2018-05-29 22:27:27.150012-0700  localhost Runner[63932]: (Flutter) flutter: test uses SemanticsTester, it is sufficient to call dispose() on SemanticsTester. Otherwise, the
[        ] [DEVICE LOG] 2018-05-29 22:27:27.150191-0700  localhost Runner[63932]: (Flutter) flutter: existing handle will leak into another test and alter its behavior.
[        ] flutter: test uses SemanticsTester, it is sufficient to call dispose() on SemanticsTester. Otherwise, the
[        ] flutter: existing handle will leak into another test and alter its behavior.
[        ] [DEVICE LOG] 2018-05-29 22:27:27.150736-0700  localhost Runner[63932]: (Flutter) flutter:
[        ] [DEVICE LOG] 2018-05-29 22:27:27.151124-0700  localhost Runner[63932]: (Flutter) flutter: When the exception was thrown, this was the stack:
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[   +5 ms] [DEVICE LOG] 2018-05-29 22:27:27.157261-0700  localhost Runner[63932]: (Flutter) flutter: #0      WidgetTester._verifySemanticsHandlesWereDisposed (package:flutter_test/src/widget_tester.dart:526:7)
[        ] flutter: #0      WidgetTester._verifySemanticsHandlesWereDisposed (package:flutter_test/src/widget_tester.dart:526:7)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.157464-0700  localhost Runner[63932]: (Flutter) flutter: #1      WidgetTester._endOfTestVerifications (package:flutter_test/src/widget_tester.dart:521:5)
[        ] flutter: #1      WidgetTester._endOfTestVerifications (package:flutter_test/src/widget_tester.dart:521:5)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.157681-0700  localhost Runner[63932]: (Flutter) flutter: #2      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:518:22)
[        ] flutter: #2      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:518:22)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.157880-0700  localhost Runner[63932]: (Flutter) flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.158019-0700  localhost Runner[63932]: (Flutter) flutter: #5      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:494:14)
[        ] flutter: <asynchronous suspension>
[        ] flutter: #5      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:494:14)
[   +1 ms] [DEVICE LOG] 2018-05-29 22:27:27.158145-0700  localhost Runner[63932]: (Flutter) flutter: #6      LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1109:12)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.158310-0700  localhost Runner[63932]: (Flutter) flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.158438-0700  localhost Runner[63932]: (Flutter) flutter: #7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:62:24)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.158648-0700  localhost Runner[63932]: (Flutter) flutter: #8      Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
[        ] flutter: #6      LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1109:12)
[        ] flutter: <asynchronous suspension>
[        ] flutter: #7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:62:24)
[        ] flutter: #8      Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.158797-0700  localhost Runner[63932]: (Flutter) flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.158951-0700  localhost Runner[63932]: (Flutter) flutter: #9      Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.159076-0700  localhost Runner[63932]: (Flutter) flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.159197-0700  localhost Runner[63932]: (Flutter) flutter: #13     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.160042-0700  localhost Runner[63932]: (Flutter) flutter: #14     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.160614-0700  localhost Runner[63932]: (Flutter) flutter: #18     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.161182-0700  localhost Runner[63932]: (Flutter) flutter: <asynchronous suspension>
[        ] flutter: <asynchronous suspension>
[        ] flutter: #9      Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
[        ] flutter: <asynchronous suspension>
[        ] flutter: #13     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
[        ] flutter: #14     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
[        ] flutter: #18     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
[        ] flutter: <asynchronous suspension>
[        ] [DEVICE LOG]
[   +5 ms] [DEVICE LOG] 2018-05-29 22:27:27.161558-0700  localhost Runner[63932]: (Flutter) flutter: #19     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.162280-0700  localhost Runner[63932]: (Flutter) flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.162811-0700  localhost Runner[63932]: (Flutter) flutter: #33     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.163014-0700  localhost Runner[63932]: (Flutter) flutter: #34     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
[        ] flutter: #19     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
[        ] flutter: <asynchronous suspension>
[        ] flutter: #33     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
[        ] flutter: #34     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.163431-0700  localhost Runner[63932]: (Flutter) flutter: #35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.163919-0700  localhost Runner[63932]: (Flutter) flutter: (elided 21 frames from package dart:async and package stack_trace)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.164818-0700  localhost Runner[63932]: (Flutter) flutter:
[        ] [DEVICE LOG] 2018-05-29 22:27:27.165113-0700  localhost Runner[63932]: (Flutter) flutter: The test description was:
[        ] [DEVICE LOG] 2018-05-29 22:27:27.165232-0700  localhost Runner[63932]: (Flutter) flutter: Counter increments smoke test
[        ] [DEVICE LOG] 2018-05-29 22:27:27.165571-0700  localhost Runner[63932]: (Flutter) flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] [DEVICE LOG] 2018-05-29 22:27:27.165778-0700  localhost Runner[63932]: (Flutter) flutter: (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.166559-0700  localhost Runner[63932]: (Flutter) flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
[        ] [DEVICE LOG] 2018-05-29 22:27:27.166919-0700  localhost Runner[63932]: (Flutter) flutter: The following assertion was thrown running a test:
[        ] [DEVICE LOG] 2018-05-29 22:27:27.167390-0700  localhost Runner[63932]: (Flutter) flutter: A SemanticsHandle was active at the end of the test.
[        ] [DEVICE LOG] 2018-05-29 22:27:27.167637-0700  localhost Runner[63932]: (Flutter) flutter: All SemanticsHandle instances must be disposed by calling dispose() on the SemanticsHandle. If your
[        ] [DEVICE LOG] 2018-05-29 22:27:27.167862-0700  localhost Runner[63932]: (Flutter) flutter: test uses SemanticsTester, it is sufficient to call dispose() on SemanticsTester. Otherwise, the
[        ] [DEVICE LOG] 2018-05-29 22:27:27.168039-0700  localhost Runner[63932]: (Flutter) flutter: existing handle will leak into another test and alter its behavior.
[        ] [DEVICE LOG] 2018-05-29 22:27:27.168637-0700  localhost Runner[63932]: (Flutter) flutter:
[        ] [DEVICE LOG] 2018-05-29 22:27:27.168757-0700  localhost Runner[63932]: (Flutter) flutter: When the exception was thrown, this was the stack:
[        ] flutter: #35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
[        ] flutter: (elided 21 frames from package dart:async and package stack_trace)
[        ] flutter:
[        ] flutter: The test description was:
[        ] flutter: Counter increments smoke test
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] flutter: (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
[        ] flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
[        ] flutter: The following assertion was thrown running a test:
[        ] flutter: A SemanticsHandle was active at the end of the test.
[        ] flutter: All SemanticsHandle instances must be disposed by calling dispose() on the SemanticsHandle. If your
[        ] flutter: test uses SemanticsTester, it is sufficient to call dispose() on SemanticsTester. Otherwise, the
[        ] flutter: existing handle will leak into another test and alter its behavior.
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] [DEVICE LOG] 2018-05-29 22:27:27.170440-0700  localhost Runner[63932]: (Flutter) flutter: #0      WidgetTester._verifySemanticsHandlesWereDisposed (package:flutter_test/src/widget_tester.dart:526:7)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.170991-0700  localhost Runner[63932]: (Flutter) flutter: #1      WidgetTester._endOfTestVerifications (package:flutter_test/src/widget_tester.dart:521:5)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.171376-0700  localhost Runner[63932]: (Flutter) flutter: #2      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:518:22)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.171666-0700  localhost Runner[63932]: (Flutter) flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.172383-0700  localhost Runner[63932]: (Flutter) flutter: #5      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:494:14)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.172576-0700  localhost Runner[63932]: (Flutter) flutter: #6      LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1109:12)
[        ] flutter: #0      WidgetTester._verifySemanticsHandlesWereDisposed (package:flutter_test/src/widget_tester.dart:526:7)
[        ] flutter: #1      WidgetTester._endOfTestVerifications (package:flutter_test/src/widget_tester.dart:521:5)
[        ] flutter: #2      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:518:22)
[        ] flutter: <asynchronous suspension>
[        ] flutter: #5      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:494:14)
[        ] flutter: #6      LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1109:12)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.172811-0700  localhost Runner[63932]: (Flutter) flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.173069-0700  localhost Runner[63932]: (Flutter) flutter: #7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:62:24)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.173311-0700  localhost Runner[63932]: (Flutter) flutter: #8      Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.173586-0700  localhost Runner[63932]: (Flutter) flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.173885-0700  localhost Runner[63932]: (Flutter) flutter: #9      Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
[        ] flutter: <asynchronous suspension>
[        ] flutter: #7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:62:24)
[        ] flutter: #8      Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:161:27)
[        ] flutter: <asynchronous suspension>
[        ] flutter: #9      Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:249:15)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.174278-0700  localhost Runner[63932]: (Flutter) flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.174509-0700  localhost Runner[63932]: (Flutter) flutter: #13     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.174717-0700  localhost Runner[63932]: (Flutter) flutter: #14     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.174986-0700  localhost Runner[63932]: (Flutter) flutter: #18     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
[        ] flutter: <asynchronous suspension>
[        ] flutter: #13     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:246:5)
[        ] flutter: #14     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:159:33)
[        ] flutter: #18     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:158:13)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.175314-0700  localhost Runner[63932]: (Flutter) flutter: <asynchronous suspension>
[        ] flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.175597-0700  localhost Runner[63932]: (Flutter) flutter: #19     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
[        ] flutter: #19     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
[   +2 ms] [DEVICE LOG] 2018-05-29 22:27:27.175917-0700  localhost Runner[63932]: (Flutter) flutter: <asynchronous suspension>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.176281-0700  localhost Runner[63932]: (Flutter) flutter: #33     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
[        ] flutter: <asynchronous suspension>
[        ] flutter: #33     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.176783-0700  localhost Runner[63932]: (Flutter) flutter: #34     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
[  +10 ms] [DEVICE LOG] 2018-05-29 22:27:27.177188-0700  localhost Runner[63932]: (Flutter) flutter: #35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
[        ] flutter: #34     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
[        ] flutter: #35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.178388-0700  localhost Runner[63932]: (Flutter) flutter: (elided 21 frames from package dart:async and package stack_trace)
[        ] [DEVICE LOG] 2018-05-29 22:27:27.178885-0700  localhost Runner[63932]: (Flutter) flutter:
[        ] [DEVICE LOG] 2018-05-29 22:27:27.179625-0700  localhost Runner[63932]: (Flutter) flutter: The test description was:
[        ] [DEVICE LOG] 2018-05-29 22:27:27.180150-0700  localhost Runner[63932]: (Flutter) flutter: Counter increments smoke test
[        ] [DEVICE LOG] 2018-05-29 22:27:27.180428-0700  localhost Runner[63932]: (Flutter) flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] [DEVICE LOG] 2018-05-29 22:27:27.185011-0700  localhost Runner[63932]: (Flutter) flutter: 00:00 \^[[32m+0\^[[0m\^[[31m -1\^[[0m: - Counter increments smoke test \^[[1m\^[[31<…>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.186003-0700  localhost Runner[63932]: (Flutter) flutter:   Test failed. See exception logs above.
[        ] [DEVICE LOG]   The test description was: Counter increments smoke test
[        ] [DEVICE LOG] 2018-05-29 22:27:27.186709-0700  localhost Runner[63932]: (Flutter) flutter:
[        ] flutter: (elided 21 frames from package dart:async and package stack_trace)
[        ] flutter:
[        ] flutter: The test description was:
[        ] flutter: Counter increments smoke test
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] flutter: 00:00 \^[[32m+0\^[[0m\^[[31m -1\^[[0m: - Counter increments smoke test \^[[1m\^[[31<…>
[        ] flutter:   Test failed. See exception logs above.
[        ]   The test description was: Counter increments smoke test
[        ] flutter:
[        ] [DEVICE LOG] 2018-05-29 22:27:27.192445-0700  localhost Runner[63932]: (Flutter) flutter: 00:00 \^[[32m+0\^[[0m\^[[31m -1\^[[0m: - smoke <…>
[        ] flutter: 00:00 \^[[32m+0\^[[0m\^[[31m -1\^[[0m: - smoke <…>
[  +11 ms] [DEVICE LOG] 2018-05-29 22:27:27.204288-0700  localhost Runner[63932]: (Flutter) flutter: 00:00 \^[[32m+0\^[[0m\^[[33m ~1\^[[0m\^[[31m -1\^[[0m: \^[[31mSome tes<…>
[        ] flutter: 00:00 \^[[32m+0\^[[0m\^[[33m ~1\^[[0m\^[[31m -1\^[[0m: \^[[31mSome tes<…>
[        ] [DEVICE LOG] 2018-05-29 22:27:27.204575-0700  localhost Runner[63932]: (Flutter) flutter:
[        ] flutter:
[        ] [DEVICE LOG] 2018-05-29 22:27:27.205658-0700  localhost Runner[63932]: (Flutter) [VERBOSE-2:dart_error.cc(16)] Unhandled exception:
[        ] [DEVICE LOG] Dummy exception to set exit code.
[        ] [DEVICE LOG] #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114:29)
[        ] [DEVICE LOG] #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ] [DEVICE LOG] #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[   +1 ms] [VERBOSE-2:dart_error.cc(16)] Unhandled exception:
[        ] Dummy exception to set exit code.
[        ] #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114:29)
[        ] #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ] #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[+1199 ms] Updating files
[ +558 ms] DevFS: Sync finished
[        ] Synced 0.8MB.
[   +4 ms] _flutter.listViews: {}
[   +1 ms] Connected to _flutterView/0x7fcabae01f78.
[        ] 🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
[        ] An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8100/
[        ] For a more detailed help message, press "h". To quit, press "q".

```


```
$ flutter analyze test/
Analyzing 2 directories...
No issues found! (ran in 1.6s)
```

<!-- Finally, paste the output of running `flutter doctor -v` here. -->

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.4 17E202, locale en-US)
    • Flutter version 0.4.4 at /Users/filiph/dev/flutter
    • Framework revision f9bb4289e9 (3 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/filiph/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.9.2

[✓] Connected devices (1 available)
    • iPhone X • 8C0199F9-DE6D-4A50-86F3-875D58FF15E6 • ios • iOS 11.4 (simulator)

! Doctor found issues in 2 categories.
```

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/18015

/cc @yjbanov

### CODE REVIEW

File: packages/flutter_test/lib/src/widget_tester.dart [hunk 1]
```diff
@@ -532,6 +535,13 @@ class WidgetTester extends WidgetController implements HitTestDispatcher, Ticker
         'existing handle will leak into another test and alter its behavior.'
       );
     }
+    _semanticsHandles = null;
+  }
+
+  int _semanticsHandles;
```
Comment (yjbanov) [inline packages/flutter_test/lib/src/widget_tester.dart]: I'd use a more specific name. As is it implies the current number of semantic handles, while you want to convey something like "last recorded", or "before test started".

**Review by yjbanov — APPROVED** [review]
