### PR TITLE
Instrument pending timers in tests

### LINKED ISSUE #4237: Test framework should hook timer creation so that when it complains about leaking timers, it can give a stack trace for where the timer was registered

### PR DESCRIPTION
**Pull request by jamesderlin**
## Description

Flutter widget tests assert if a test completes with timers still
pending.  However, it can be hard to diagnose where a pending timer
came from.  For example, a widget might consume a third-party library
that internally uses a timer.

I added a FakeAsync.pendingTimersDebugInfo getter to quiver
(https://github.com/google/quiver-dart/pull/500).  Make flutter_test
use it.

Additionally modify Flutter's debugPrintStack to take an optional
StackTrace argument instead of always printing StackTrace.current.

## Related Issues

Fixes #4237.

## Tests

Since this adjusts error reporting for specific types of test failures, I did not add any tests.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [X] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 1]
```diff
@@ -737,19 +737,20 @@ class FlutterError extends Error with DiagnosticableTreeMixin implements Asserti
...
-/// Dump the current stack to the console using [debugPrint] and
+/// Dump the stack to the console using [debugPrint] and
 /// [FlutterError.defaultStackFilter].
 ///
-/// The current stack is obtained using [StackTrace.current].
+/// If `stackTrace` is null, dumps the current stack using [StackTrace.current].
 ///
 /// The `maxFrames` argument can be given to limit the stack to the given number
-/// of lines. By default, all non-filtered stack lines are shown.
+/// of non-filtered lines. By default, all non-filtered stack lines are shown.
```
Comment (dnfield) [inline packages/flutter/lib/src/foundation/assertions.dart]: nit: I'm not sure it helps to add `non-filtered` in here - I think I'd probably rather remove it from the other part of the sentence, since we don't really have any options for filtering on this method anyway.

File: packages/flutter_test/lib/src/binding.dart [hunk 2]
```diff
@@ -1044,14 +1044,32 @@ class AutomatedTestWidgetsFlutterBinding extends TestWidgetsFlutterBinding {
...
     super._verifyInvariants();
-    assert(
-      _currentFakeAsync.periodicTimerCount == 0,
-      'A periodic Timer is still running even after the widget tree was disposed.'
-    );
-    assert(
-      _currentFakeAsync.nonPeriodicTimerCount == 0,
-      'A Timer is still pending even after the widget tree was disposed.'
-    );
+    try {
```
Comment (dnfield) [inline packages/flutter_test/lib/src/binding.dart]: I think the idiom more commonly used here would be something like:

```dart
assert(() {
  if (_currentFakeAsync.periodTimerCount != 0) {
    // Print error/message(s)
    return false;
  }
  // ...
  return true;
}());
```

**Review by dnfield — COMMENTED** [review]
Couple minor things.

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 1 above)
Comment (jamesderlin) [reply packages/flutter/lib/src/foundation/assertions.dart]: Without it, I think it's unclear how filtering and `maxFrames` interact with each other.  Is filtering done first, and then `maxFrames` frames are printed?  Or is the `StackTrace` truncated first and then filtered?

File: packages/flutter_test/lib/src/binding.dart (hunk 2 above)
Comment (jamesderlin) [reply packages/flutter_test/lib/src/binding.dart]: I was trying to preserve the existing `AssertionError`s and their messages.

I suppose now that the debugging information should report whether the pending timers are periodic or non-periodic (albeit in a less friendly form), that distinction is less important.

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 1 above)
Comment (jamesderlin) [reply packages/flutter/lib/src/foundation/assertions.dart]: I reworded the comment hopefully to both our liking.

File: packages/flutter_test/lib/src/binding.dart [hunk 3]
```diff
@@ -1044,14 +1044,29 @@ class AutomatedTestWidgetsFlutterBinding extends TestWidgetsFlutterBinding {
...
+        // No need to include the newline.
+        final String firstLine = timerInfo.substring(0, firstLineEnd);
+        final String stackTrace = timerInfo.substring(firstLineEnd + 1);
+
+        debugPrint(firstLine);
+        debugPrintStack(stackTrace: StackTrace.fromString(stackTrace));
+        debugPrint('');
+      }
+      return false;
+    }(),'A Timer is still pending even after the widget tree was disposed.');
```
Comment (Hixie) [inline packages/flutter_test/lib/src/binding.dart]: trivialiest of nits: space missing after comma

**Comment by Hixie** [comment]
This is great.

Can we add a test for this? In the past I've found this kind of code ends up being very brittle and because it only gets hit when things fail it takes a long time for anyone to notice it broke.

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 4]
```diff
@@ -737,19 +737,21 @@ class FlutterError extends Error with DiagnosticableTreeMixin implements Asserti
   }
 }
 
-/// Dump the current stack to the console using [debugPrint] and
+/// Dump the stack to the console using [debugPrint] and
 /// [FlutterError.defaultStackFilter].
 ///
-/// The current stack is obtained using [StackTrace.current].
+/// If `stackTrace` is null, dumps the current stack using [StackTrace.current].
```
Comment (dnfield) [inline packages/flutter/lib/src/foundation/assertions.dart]: One last nit: this isn't quite a sentence now.  Maybe 
````
If the `stackTrace` parameter is null, the [StackTrace.current] is used to obtain the stack.
````

File: packages/flutter_test/lib/src/binding.dart (hunk 3 above)
Comment (jamesderlin) [reply packages/flutter_test/lib/src/binding.dart]: Oops.  Fixed.

> Can we add a test for this? In the past I've found this kind of code ends up being very brittle and because it only gets hit when things fail it takes a long time for anyone to notice it broke.

Okay, I'll see if I can make a relevant test.

File: packages/flutter/lib/src/foundation/assertions.dart (hunk 4 above)
Comment (jamesderlin) [reply packages/flutter/lib/src/foundation/assertions.dart]: Well, it's a sentence, but maybe it's not in the preferred style and doesn't read as well. =)

I'll change it to your suggestion.

File: packages/flutter_test/lib/src/binding.dart (hunk 3 above)
Comment (jamesderlin) [reply packages/flutter_test/lib/src/binding.dart]: I remember now why I didn't add a test: I don't know how.  I want to test that a test fails, but `test`/`testWidgets` doesn't allow nesting.  I assume that my test will need to essentially run `flutter test` on a failing test and interpret the ouptut.

Do you know of examples of tests of tests that I can use for reference?

**Comment by dnfield** [comment]
You can write a test that fails because it leaks a timer and check the output (and that the error code is -1).  E.g. https://github.com/flutter/flutter/blob/master/dev/bots/test.dart#L87

**Comment by goderbauer** [comment]
(PR triage): @dnfield says this is waiting for https://github.com/flutter/flutter/pull/37981.

**Comment by jamesderlin** [comment]
@dnfield Thanks!  I've added a test.

File: dev/automated_tests/test_smoke_test/pending_timer_fail_test.dart [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+
+import 'package:flutter_test/flutter_test.dart';
+
+void main() {
+  failingPendingTimerTest();
+}
+
+void failingPendingTimerTest() {
+  testWidgets('flutter_test pending timer - negative', (WidgetTester tester) async {
+    Timer(const Duration(seconds: 1), () {});
```
Comment (dnfield) [inline dev/automated_tests/test_smoke_test/pending_timer_fail_test.dart]: I'm not sure if this makes a difference but can we make the duration longer, like a few minutes?  Just in case this runs on a slow CI machine and actually takes a second to make it all the way through this code (it seems pretty unlikely, but far less likely if the timer is for a few minutes or hours or something).

**Review by dnfield — APPROVED** [review]
LGTM with nit about the timer duration.

Also, please make sure to squash this when you land it instead of as a merge commit - our CI gets really bogged down by those.

File: dev/automated_tests/test_smoke_test/pending_timer_fail_test.dart (hunk 5 above)
Comment (jamesderlin) [reply dev/automated_tests/test_smoke_test/pending_timer_fail_test.dart]: I'll change it to 10 minutes.

(BTW, I *meant* to squash #37981 but picked the wrong choice by accident.  Sorry about that.)
