### PR TITLE
[flutter] prevent errant text field clicks from losing focus

### LINKED ISSUE #86154: [desktop/web] TextField loses focus when pressing prefix or suffix button
## Steps to Reproduce (desktop & web)

1. Run `flutter create bug`.
2. Update **main.dart**:
    ```dart
    import 'package:flutter/material.dart';

    void main() => runApp(const MaterialApp(home: EditPage()));

    class EditPage extends StatefulWidget {
      const EditPage({Key? key}) : super(key: key);

      @override
      State<EditPage> createState() => _EditPageState();
    }

    class _EditPageState extends State<EditPage> {
      final _controller = TextEditingController(text: 'TextField');

      @override
      void dispose() {
        _controller.dispose();
        super.dispose();
      }

      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(title: const Text('TextField')),
          body: Center(
            child: Padding(
              padding: const EdgeInsets.all(24.0),
              child: TextField(
                autofocus: true,
                controller: _controller,
                decoration: InputDecoration(
                  suffix: IconButton(
                    onPressed: _controller.clear,
                    icon: const Icon(Icons.clear),
                  ),
                ),
              ),
            ),
          ),
        );
      }
    }
    ```

3. Run the app and press the clear button.

**Expected results:** `TextField` retains focus (stable channel)

**Actual results:** `TextField` loses focus (master channel)

| stable (2.2.3) | master (2.4.0-1.0.pre.143) |
|---|---|
| stable | master |

```
Flutter 2.4.0-1.0.pre.143 • channel master • https://github.com/flutter/flutter.git
Framework • revision 311920b326 (37 minutes ago) • 2021-07-09 02:06:03 -0400
Engine • revision dc06724099
Tools • Dart 2.14.0 (build 2.14.0-291.0.dev)
```

Related to #82575.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Without making dramatic adjustments to the focus system, attempts to support the text field / editable text nesting while still preventing clicks from text field decoration from removing focus from the editable text.

Fixes https://github.com/flutter/flutter/issues/86154

### CODE REVIEW

**Comment by jonahwilliams** [comment]
@gspencergoog @chunhtai this is an attempt to fix one of the side effects from the focus removal change; since the "focused" part of the text field is just the tiny editable text portion it is too easy to lose focus by clicking on the decorative parts. This introduces another context that can be attached to a focus node to detect this.

File: packages/flutter/lib/src/widgets/routes.dart [hunk 1]
```diff
@@ -2024,13 +2021,7 @@ class _RenderFocusTrap extends RenderProxyBoxWithHitTestBehavior {
   set focusScopeNode(FocusScopeNode value) {
     if (focusScopeNode == value)
       return;
-    focusScopeNode.removeListener(_currentFocusListener);
     _focusScopeNode = value;
-    focusScopeNode.addListener(_currentFocusListener);
-  }
-
-  void _currentFocusListener() {
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/widgets/routes.dart:2032]: For some reason this wasn't giving up to date results when using tab navigation

**Comment by jonahwilliams** [comment]
ahh, need to port over my old tests

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -1600,7 +1605,7 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     super.initState();
     _clipboardStatus?.addListener(_onChangedClipboardStatus);
     widget.controller.addListener(_didChangeTextEditingValue);
-    _focusAttachment = widget.focusNode.attach(context);
+    _focusAttachment = widget.focusNode.attach(context, contextBounds: widget.parentContext);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/editable_text.dart:1608]: It looks like the hittest uses prioritize context bounds to determine hittest rect, I wonder can it directly attach to the widget.parentContext if it is not null?

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/editable_text.dart:1608]: Thinking about this more, we might have some issues if editable text migrates to use a regular focus node since we won't have the attachment available.

Attaching to the parent context might work, but thinking about it more I'm not sure if we need to worry about reparenting. Surely you'd never re-parent the text field decoration apart from an editable text right?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/editable_text.dart:1608]: third party libraries does crazy thing around editable text, I wouldn't be surprised if the editabletext gets reparented. but I think we should be able to reparent the attachment in didUpdateWidget?

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Currently focus will be lost (at least according to my test cases)

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 3]
```diff
@@ -571,6 +571,11 @@ class FocusNode with DiagnosticableTreeMixin, ChangeNotifier {
   BuildContext? get context => _context;
   BuildContext? _context;
 
+  /// An optional parent context that determines whether or not a primary pointer
+  /// gesture that missed the actual [context] should remove focus from the node.
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: expanded the comments here a bit

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/editable_text.dart]: yes, focusAttachment.detach will call unfocus on the focusnode. I think this is probably fine because this will be an edgy case where people keep swapping out the parent focus. We can fix it later if that actually cause issue.

File: packages/flutter/lib/src/widgets/routes.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/routes.dart:2032]: I am not so certain about why we need to remove this code. If this is indeed a bug fixes, we should have a test for this.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -1346,6 +1347,14 @@ class EditableText extends StatefulWidget {
   /// than 1.
   final ScrollBehavior? scrollBehavior;
 
+  /// Optionally, the parent build context if this editable text was built as part of
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/editable_text.dart:1350]:
```suggestion
  /// The optional parent build context if this editable text was built as part of
```

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 5]
```diff
@@ -1346,6 +1347,14 @@ class EditableText extends StatefulWidget {
...
+  /// a larger text field.
+  ///
+  /// If this is provided then focus will be attached to the parent context instead of
+  /// the editable text. If the [parentContext] is later modified while the editable text
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/editable_text.dart:1354]: Maybe also explain what's the different consequences to attach to this context vs parent context, and why developer may want to do that

**Comment by chunhtai** [comment]
The overall approach looks good to me, just some nits

**Comment by jonahwilliams** [comment]
Good point, i need to investigate a bit more. i might be working around a focus bug, so finding the root cause first is probably ideal.

**Comment by jonahwilliams** [comment]
moved the listener change to https://github.com/flutter/flutter/pull/86141

**Comment by jonahwilliams** [comment]
I wasn't able to make the parent context work - it changed how actions/shortcuts were looked up in some non-obvious ways. I've gone back to tagging render objects with the focus node.

**Comment by jonahwilliams** [comment]
This is ready for review

File: packages/flutter/lib/src/widgets/routes.dart [hunk 6]
```diff
@@ -2010,6 +2010,40 @@ class _FocusTrap extends SingleChildRenderObjectWidget {
...
 }
 
+/// Declares a widget subtree which is part of the provided [focusNode]'s focus area
+/// without attaching focus to that region.
+///
+/// This is used by text field widgets which decorate a smaller editable text area.
+/// This area is conceptually part of the editable text, but not attached to the
+/// focus context. The [FocusTrapArea] is used to inform the framework of this
+/// relationship, so that primary pointer contact inside of this region but above
+/// the editable text focus will not trigger loss of focus.
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/routes.dart:2020]: You might add a reference/description here for the focus trap and when it comes into play, etc. If I pretend that I just happened upon the API docs page for this widget, it feels like if I wasn't writing my own text widget I wouldn't quite know when to use it, or what it affects.

Since `_FocusTrap` isn't a public class, there's probably not much mention of it in other docs.

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart:2020]: I could make it public, no need to keep it private really

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart:2020]: that would require me to document it a bit more, but no harm there

Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/routes.dart:2020]: The other option would be to make `FocusTrapArea` private, if you don't think anyone will need it outside of the text field (but it seems like they might).

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart:2020]: probably the cupertino text field needs it as well, as would other like the macos ui package - depending on whether or not they are editable text widget based

**Comment by jonahwilliams** [comment]
I've updated the documentation and made focus trap/ focus area stuff public. ptAL @gspencergoog

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by jpnurmi** [comment]
Is the linked issue wrong? This fixes https://github.com/flutter/flutter/issues/85732 (decoration) but not https://github.com/flutter/flutter/issues/86154 (prefix/suffix buttons).

**Review by chunhtai — APPROVED** [review]
LGTM
