### PR TITLE
fix SliverReorderableLists item wrong offset

### LINKED ISSUE #135819: ReorderableListView.builder in Horizontal moves last item into view when dragging
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the code below
2. Resize the window to the image provided (make sure to Resize it properly)
3. Make sure only 3 of the 4 widgest are visible, like the image provided
4. Drag the first "Test" widget
5. Notice when you start to drag, even though the 4th widget isn't on the screen, it moves into view over thte 3rd widget text.  So you see "Something" over "Good"

### Expected results

1. When dragging, things farther in the view shouldn't glitch over into view

### Actual results

1. Widgets move from outside the viewport into view

### Code sample

<details><summary>Code sample</summary>

```dart

import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      scrollBehavior: const MaterialScrollBehavior().copyWith(
        // Mouse dragging enabled for this demo
        dragDevices: PointerDeviceKind.values.toSet(),
      ),
      debugShowCheckedModeBanner: false,
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    List<String> items = ['Test', 'Bad', 'Good', 'Something'];
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: ReorderableListView.builder(
        proxyDecorator: (child, index, animation) {
          return Container(
            decoration: BoxDecoration(
              color: Colors.black26,
              borderRadius: BorderRadius.circular(10.0),
              border: Border.all(
                color: Colors.white10,
                width: 2.0,
              ),
            ),
            child: SizedBox(
              width: 500,
              child: child,
            ),
          );
        },
        buildDefaultDragHandles: false,
        scrollDirection: Axis.horizontal,
        itemCount: 4,
        onReorder: (oldIndex, newIndex) {},
        itemBuilder: (context, i) => ReorderableDragStartListener(
          key: ValueKey(i),
          index: i,
          child: GestureDetector(
            onSecondaryTap: null,
            child: SizedBox(
              width: 500,
              child: TextButton(
                onPressed: null,
                child: Row(
                  children: [
                    Text(
                      items[i],
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>

flutter_glitch

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.7.3)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.82.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by yiiim**
This PR fixes the issue of items being created at the wrong position during dragging.

Fixes #135819 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 1]
```diff
@@ -730,6 +730,9 @@ class SliverReorderableListState extends State<SliverReorderableList> with Ticke
   }
 
   void _registerItem(_ReorderableItemState item) {
+    if (_dragInfo != null && _items[item.index] == null) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/reorderable_list.dart:733]: what if _items[item.index] contains other item? e.g a rebuild that replace an existing item with a new item at a index

Comment (yiiim) [reply packages/flutter/lib/src/widgets/reorderable_list.dart]: You are right, update to `_items[item.index] != item`

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
adding @Piinks as secondary reviewer

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
