### PR TITLE
Bind `GL_FRAMEBUFFER` with `glReadPixels` for gles2 compatibility

### LINKED ISSUE #164459: Upon upgrading version 3.29, image.toByteData doesn't return correct image bytes.
### Steps to reproduce

1. Open flutter app with flutter version 3.29 an android emulator (tried on android 11)
2. Add code that fetches ui.Image bytes in any encoding. `image.toByteData`
3. Only reproduceable on emulators.
(Does it possibly have anything to do with the decision to [disable Vulkan on emulators starting v3.29](https://github.com/flutter/flutter/issues/160442#issuecomment-2627839218)?) 

### Expected results

1- Correct image data
2- Console free of opengl errors

### Actual results

1- Image data is incorrect.
2- Console shoes opengl errors.

### Code sample

<details open><summary>Code sample</summary>

```dart
    ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
E/emuglGLESv2_enc( 6025): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glBindFramebuffer:2710 GL error 0x500
E/emuglGLESv2_enc( 6025): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glFramebufferTexture2D:2723 GL error 0x500
E/emuglGLESv2_enc( 6025): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glBindFramebuffer:2710 GL error 0x500
```
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.29.0, on Microsoft Windows [Version 10.0.22631.4890], locale en-US)
[√] Windows Version (11 Enterprise 64-bit, 23H2, 2009)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.12.5)
[√] Android Studio (version 2024.2)
[√] VS Code (version 1.97.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/164459

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles_unittests.cc [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+  EXPECT_TRUE(command.Encode(*reactor));
+
+  source_texture.reset();
+  dest_buffer.reset();
+
+  ASSERT_TRUE(reactor->React());
+}
+
+}  // namespace testing
+}  // namespace impeller
```
Comment (chinmaygarde) [inline engine/src/flutter/impeller/renderer/backend/gles/blit_command_gles_unittests.cc]: Nit: Newline at EOF

**Review by chinmaygarde — APPROVED** [review]
