### PR TITLE
[flutter_tools] cache result of BotDetector in persistent tool state

### LINKED ISSUE #52065: Azure bot detector is slowing down flutter tool startup by at least a second
`flutter run` takes a very long time. It wasn't always like this, but I just upgraded to the latest `master` (sorry I don't know the previous revision I was using), and how it is super-slow. Like 2 minutes slow. I'm sure it was on the order of 10 seconds before.

Even `flutter help` is very slow:

```
$ time flutter help
Manage your Flutter app development.
...
real	0m5.503s
user	0m0.616s
sys	0m0.195s
```

## Steps to Reproduce

1. Run `time flutter help`.
2. It shouldn't take over 5 seconds!

I 50% suspect it is the shitty ESET Antivirus I have on this Mac. Unfortunately I don't have access to disable it.

<details>
  <summary>Logs</summary>

Unfortunately `flutter help --verbose` does not show anything, and the huge pause for `flutter run` seems to be before the first output of the logs, i.e. the line that says +28 ms here actually appears about a minute after I run the command:

```
$ flutter run --verbose
[  +28 ms] executing: [/Users/me/local/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
```

```
[✓] Flutter (Channel master, v1.15.12-pre.8, on Mac OS X 10.14.4 18E226, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (not installed)
[!] IntelliJ IDEA Community Edition (version 2019.3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

The Azure bot detection can take up to a second to determine if a client is/isn't a bot. To prevent this from slowing down all flutter commands, we can cache the results in the persistent tool state - since we don't expect the same client id to ever become a bot or stop being a bot

Fixes https://github.com/flutter/flutter/issues/52065

### CODE REVIEW

File: packages/flutter_tools/lib/runner.dart [hunk 1]
```diff
@@ -48,6 +46,8 @@ Future<int> run(
   commands.forEach(runner.addCommand);
 
   return runInContext<int>(() async {
+    reportCrashes ??= !await globals.isRunningOnBot;
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/runner.dart]: Moved this into context so we can pull overrides correctly

File: packages/flutter_tools/lib/src/base/bot_detector.dart [hunk 2]
```diff
@@ -5,17 +5,20 @@
...
 class BotDetector {
   BotDetector({
     @required HttpClientFactory httpClientFactory,
     @required Platform platform,
+    @required PersistentToolState persistentToolState,
   }) :
     _platform = platform,
     _azureDetector = AzureDetector(
       httpClientFactory: httpClientFactory,
+      persistentToolState: persistentToolState,
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/bot_detector.dart]: Should this cache `BotDetector.isRunningOnBot` instead of just the `AzureBotDetector` result? That would guard against someone adding another expensive step.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/bot_detector.dart]: If someone does add another bot detector though, we might be incorrectly caching a value for these bots ... through I'm not sure if it matters. I expect that the same bot would not be using flutter over and over...

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/bot_detector.dart]: Updated to cache at bot detector level

File: packages/flutter_tools/lib/src/persistent_tool_state.dart [hunk 3]
```diff
@@ -78,6 +81,7 @@ class _DefaultPersistentToolState implements PersistentToolState {
     Channel.beta: 'last-active-beta-version',
     Channel.stable: 'last-active-stable-version'
   };
+  static const String _kAzureBot = 'azure-bot';
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/persistent_tool_state.dart]: maybe 'is-bot' since this is no longer azure specific.

**Review by zanderso — APPROVED** [review]
thanks!

File: packages/flutter_tools/lib/src/persistent_tool_state.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/persistent_tool_state.dart]: Done

**Review by christopherfujino — APPROVED** [review]
lgtm

**Review by jmagman — APPROVED** [review]
LGTM
