### PR TITLE
[Material] Implement TooltipTheme and Tooltip.textStyle, fix Tooltip debugLabel, update Tooltip defaults

### LINKED ISSUE #35513: Global configuration for Tooltip
## Use case

I need to customize Tooltip text color and background color across my app. 
Current solution: https://stackoverflow.com/questions/55426001/tooltip-message-text-and-background-color 

## Proposal
Please add another parameter that takes tooltip configuration on ThemeData or maybe MaterialApp. 

Thank you.

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

1. Implements a TooltipTheme widget that allows all existing properties to be themeable. 
Screen Shot 2019-07-19 at 1 25 50 PM
Screen Shot 2019-07-19 at 1 25 40 PM

2. Introduces the `textStyle` property, granting more fine-grained control to developers to update the tooltip's text message.
Screen Shot 2019-07-19 at 1 31 22 PM
Screen Shot 2019-07-19 at 1 31 06 PM

3. Fix `debugLabel` to use the correct color when reporting the message's textStyle

4. Breaking change: Updating default tooltip `decoration` to the following: 

- Brightness.light
```
BoxDecoration(
  color: Colors.grey[700].withOpacity(0.9),
  borderRadius: const BorderRadius.all(Radius.circular(4)),
);
```
- Brightness.dark
```
BoxDecoration(
  color: Colors.white.withOpacity(0.9), // new
  borderRadius: const BorderRadius.all(Radius.circular(4)),
);
```
5. Breaking change: Updating default `textStyle` to the following: 

- Brightness.light
```
theme.textTheme.body1.copyWith(
  color: Colors.white, // new
  debugLabel: theme.textTheme.body1.debugLabel.replaceAll('white', 'black'), // fixes debugLabel
);
```
- Brightness.dark
```
theme.textTheme.body1.copyWith(
  color: Colors.black, // new
  debugLabel: theme.textTheme.body1.debugLabel.replaceAll('white', 'black'), // fixes debugLabel
);
```

Tooltip Before Breaking change:
Screen Shot 2019-07-19 at 3 21 15 PM
Screen Shot 2019-07-19 at 3 21 26 PM

Tooltip After Breaking change: 
Screen Shot 2019-07-19 at 3 19 39 PM
Screen Shot 2019-07-19 at 3 20 08 PM

## Related Issues

Fixes https://github.com/flutter/flutter/issues/35513
Related to https://github.com/flutter/flutter/issues/33654
Related to https://github.com/flutter/flutter/pull/25844

## Tests

I added the following tests:

- Several tests verifying passing down of TooltipTheme properties (color, location, height, decoration, semantics, show and wait durations to reveal and hide tooltip)
- Tests for textStyle implementation
- Test to verify debugLabel for light and dark theme

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 1]
```diff
@@ -0,0 +1,227 @@
...
+
+  /// The amount of space by which to inset the child.
+  ///
+  /// Defaults to 16.0 logical pixels in each direction.
+  final EdgeInsetsGeometry padding;
+
+  /// The vertical gap between the widget and the displayed tooltip.
+  final double verticalOffset;
+
+  /// Whether the tooltip defaults to being displayed below the widget.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip_theme.dart]: defaults to being displayed below the widget => is displayed below its widget by default

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 2]
```diff
@@ -0,0 +1,227 @@
...
+  /// Defaults to true. If there is insufficient space to display the tooltip in
+  /// the preferred direction, the tooltip will be displayed in the opposite
+  /// direction.
+  final bool preferBelow;
+
+  /// Whether the tooltip's [message] should be excluded from the semantics
+  /// tree.
+  final bool excludeFromSemantics;
+
+  /// Specifies the tooltip's shape and background color.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip_theme.dart]: Specifies the tooltip's => The tooltip's

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 3]
```diff
@@ -0,0 +1,227 @@
...
+  /// [ThemeData.textTheme.body1] will be merged with
+  /// [ThemeData.typography.white]. Otherwise, if [ThemeData.brightness] is set
+  /// to [Brightness.light], [ThemeData.primaryTextTheme.body1] will be merged
+  /// with [ThemeData.typography.white].
+  final TextStyle textStyle;
+
+  /// The amount of time that a pointer must hover over the widget before it
+  /// will show a tooltip.
+  ///
+  /// Defaults to 0 milliseconds (tooltips show immediately upon hover).
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip_theme.dart]: show => are shown

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 4]
```diff
@@ -0,0 +1,227 @@
...
+  ///
+  /// If null, the message's [TextStyle] will be determined based on
+  /// [ThemeData]. If [ThemeData.brightness] is set to [Brightness.dark],
+  /// [ThemeData.textTheme.body1] will be merged with
+  /// [ThemeData.typography.white]. Otherwise, if [ThemeData.brightness] is set
+  /// to [Brightness.light], [ThemeData.primaryTextTheme.body1] will be merged
+  /// with [ThemeData.typography.white].
+  final TextStyle textStyle;
+
+  /// The amount of time that a pointer must hover over the widget before it
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip_theme.dart]: The amount of time that a pointer must hover over the widget before it will show a tooltip => The length of time that a pointer must hover over a tooltip's widget before the tooltip will be shown.

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 5]
```diff
@@ -0,0 +1,227 @@
...
+      showDuration: showDuration ?? this.showDuration,
+    );
+  }
+
+  /// Linearly interpolate between two tooltip themes.
+  static TooltipThemeData lerp(TooltipThemeData a, TooltipThemeData b, double t) {
+    assert(t != null);
+    assert(a?.preferBelow == b?.preferBelow);
+    assert(a?.excludeFromSemantics == b?.excludeFromSemantics);
+    if (a == null && b == null)
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip_theme.dart]: It seems like this statement should be first.

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 6]
```diff
@@ -0,0 +1,227 @@
...
+      preferBelow: preferBelow ?? this.preferBelow,
+      excludeFromSemantics: excludeFromSemantics ?? this.excludeFromSemantics,
+      decoration: decoration ?? this.decoration,
+      textStyle: textStyle ?? this.textStyle,
+      waitDuration: waitDuration ?? this.waitDuration,
+      showDuration: showDuration ?? this.showDuration,
+    );
+  }
+
+  /// Linearly interpolate between two tooltip themes.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip_theme.dart]: If we're going to prohibit changing preferBelow and excludeFromSemantics, we should document that. It might be better to use this kind of "interpolation" instead:
```
      preferBelow: t < 0.5 ? a.preferBelow: b.preferBelow
```

Ideally this stuff wouldn't change but it doesn't seem worth creating a corner case for the odd case where it does.

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 7]
```diff
@@ -0,0 +1,227 @@
...
+         preferBelow: preferBelow,
+         excludeFromSemantics: excludeFromSemantics,
+         decoration: decoration,
+         textStyle: textStyle,
+         waitDuration: waitDuration,
+         showDuration: showDuration,
+       ),
+       super(key: key, child: child);
+
+  /// Specifies the properties for descendant [Tooltip] widgets.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip_theme.dart]: Specifies the => The

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 8]
```diff
@@ -0,0 +1,227 @@
...
+  final TooltipThemeData data;
+
+  /// The closest instance of this class that encloses the given context.
+  ///
+  /// Typical usage is as follows:
+  ///
+  /// ```dart
+  /// TooltipTheme theme = TooltipTheme.of(context);
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip_theme.dart]:
```
TooltipThemeData theme = ...
```

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 9]
```diff
@@ -0,0 +1,227 @@
...
+         textStyle: textStyle,
+         waitDuration: waitDuration,
+         showDuration: showDuration,
+       ),
+       super(key: key, child: child);
+
+  /// Specifies the properties for descendant [Tooltip] widgets.
+  final TooltipThemeData data;
+
+  /// The closest instance of this class that encloses the given context.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip_theme.dart]: This is the conventional boilerplate for an inherited widget; it's not correct for this theme. This `of` method returns the closest TooltipTheme ancestor's [data] value, and if there is no TooltipTheme ancestor, then it returns the current [Theme]'s tooltipTheme. Apps can assume that the returned value is not null.

**Review by HansMuller — COMMENTED** [review]
This all looks good although I'd like to see if we can avoid the Theme brightness dependency. Most of feedback is trivial wordsmithing.

Please add:

DebugFillProperties tests like https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/bottom_sheet_theme_test.dart#L22 and
https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/bottom_sheet_theme_test.dart#L34

A copyWith/hashCode/== test like this: https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/bottom_sheet_theme_test.dart#L10

A test that verifies the theme's default values (even though they're all null; so we don't regress) like this:
https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/button_theme_test.dart#L9

File: packages/flutter/lib/src/material/tooltip.dart [hunk 10]
```diff
@@ -398,33 +417,39 @@ class _TooltipOverlay extends StatelessWidget {
...
-      brightness: Brightness.dark,
-      textTheme: theme.brightness == Brightness.dark ? theme.textTheme : theme.primaryTextTheme,
-      platform: theme.platform,
+    final TooltipThemeData tooltipTheme = TooltipTheme.of(context);
+
+    final TextStyle defaultTextStyle = theme.brightness == Brightness.dark
+      ? theme.typography.white.merge(theme.textTheme).body1
+      : theme.typography.white.merge(theme.primaryTextTheme).body1;
+
+    final BoxDecoration defaultDecoration = BoxDecoration(
```
[the remark this answers is not in the document]
Comment (shihaohong) [reply packages/flutter/lib/src/material/tooltip.dart]: How can this be achieved for the color `Colors.grey[700].withOpacity(0.9)`? I could use `Color(0xFF616161)`, but calling `.withOpacity()` makes it a non-const value.

File: packages/flutter/lib/src/material/tooltip_theme.dart (hunk 6 above)
Comment (shihaohong) [reply packages/flutter/lib/src/material/tooltip_theme.dart]: I'll use that interpolation style instead. It seems to be better than just blocking them outright.

File: packages/flutter/lib/src/material/tooltip.dart (hunk 10 above)
[the remark this answers is not in the document]
Comment (shihaohong) [reply packages/flutter/lib/src/material/tooltip.dart]: Actually, after our discussion, if we decide to do a breaking change, the defaults would change as follows: 
```
    final BoxDecoration defaultDecoration = BoxDecoration(
      color: theme.colorScheme.surface,
      borderRadius: const BorderRadius.all(Radius.circular(4)),
    );
```

File: packages/flutter/lib/src/material/tooltip.dart [hunk 11]
```diff
@@ -106,6 +96,16 @@ class Tooltip extends StatefulWidget {
   /// [ThemeData.brightness] is dark, and [ThemeData.primaryTextTheme] if not.
   final Decoration decoration;
 
+  /// The style to use for the message of the tooltip.
+  ///
+  /// If null, the message's [TextStyle] will be determined based on
```
[the remark this answers is not in the document]
Comment (shihaohong) [reply packages/flutter/lib/src/material/tooltip.dart]: Should we do the following instead: 
```
    final TextStyle defaultTextStyle = theme.textTheme.body1.copyWith(
      color: theme.colorScheme.onSurface,
    );
```

As discussed offline, it'd be a breaking change, but it'd be closer aligned to the material spec and removes the dependency on Brightness.

[the remark this answers is not in the document]
Comment (shihaohong) [reply packages/flutter/lib/src/material/tooltip.dart]: Theming is specified by the material spec here: https://material.io/design/components/tooltips.html#theming

**Comment by shihaohong** [comment]
I've implemented most of the code review suggestions and added the default tests for TooltipThemeData. I'm still currently waiting on what the default values for the border radii, background color, text color and opacity values should be.

**Comment by shihaohong** [comment]
I've received feedback on what the default tooltip `decoration` and `textStyle` should be, and this PR is now ready for review.

File: packages/flutter/lib/src/material/tooltip.dart (hunk 11 above)
[the remark this answers is not in the document]
Comment (shihaohong) [reply packages/flutter/lib/src/material/tooltip.dart]: I've updated the textTheme to correspond with what is expected by Material

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 12]
```diff
@@ -0,0 +1,227 @@
...
+import 'package:flutter/widgets.dart';
+
+import 'theme.dart';
+
+/// Defines the properties of [Tooltip] widgets.
+///
+/// Used by [TooltipTheme] to control the properties of tooltips in a widget
+/// subtree.
+///
+/// To obtain the current [TooltipTheme], use [TooltipTheme.of].
```
[the remark this answers is not in the document]
Comment (shihaohong) [reply packages/flutter/lib/src/material/tooltip_theme.dart]: I updated it to the following:
```
/// To obtain this configuration, use [TooltipTheme.of] to access the closest
/// ancestor [TooltipTheme] of the current [BuildContext].
```

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 13]
```diff
@@ -0,0 +1,227 @@
...
+
+  /// Whether the tooltip defaults to being displayed below the widget.
+  ///
+  /// Defaults to true. If there is insufficient space to display the tooltip in
+  /// the preferred direction, the tooltip will be displayed in the opposite
+  /// direction.
+  final bool preferBelow;
+
+  /// Whether the tooltip's [message] should be excluded from the semantics
+  /// tree.
```
[the remark this answers is not in the document]
Comment (shihaohong) [reply packages/flutter/lib/src/material/tooltip_theme.dart]: Added an explanation to the API doc

File: packages/flutter/lib/src/material/tooltip.dart [hunk 14]
```diff
@@ -92,6 +93,10 @@ class Tooltip extends StatefulWidget {
 
   /// Whether the tooltip's [message] should be excluded from the semantics
   /// tree.
+  ///
+  /// Defaults to false. A tooltip will add a [Semantics.label] that is set to
+  /// [Tooltip.message]. Set this property to true if a custom
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip.dart]: I think you mean ... true if the app is going to provide its own custom semantics label?

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 15]
```diff
@@ -0,0 +1,251 @@
...
+  ///
+  /// If there is insufficient space to display the tooltip in the preferred
+  /// direction, the tooltip will be displayed in the opposite direction.
+  final bool preferBelow;
+
+  /// Whether the tooltip's [message] should be excluded from the semantics
+  /// tree.
+  ///
+  /// By default, [Tooltip]s will add a [Semantics.label] that is set to
+  /// [Tooltip.message]. Set this property to true if a custom
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip_theme.dart]: same comment as earlier

File: packages/flutter/lib/src/material/tooltip_theme.dart [hunk 16]
```diff
@@ -0,0 +1,251 @@
...
+         textStyle: textStyle,
+         waitDuration: waitDuration,
+         showDuration: showDuration,
+       ),
+       super(key: key, child: child);
+
+  /// The properties for descendant [Tooltip] widgets.
+  final TooltipThemeData data;
+
+  /// The closest instance of this class' [data] value that encloses the given
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip_theme.dart]: class' => class's

Maybe this could be a little clearer.
```
Returns the [data] from the closest [TooltipTheme] ancestor.
```

File: packages/flutter/lib/src/material/tooltip.dart [hunk 17]
```diff
@@ -32,55 +34,54 @@ import 'theme_data.dart';
...
 ///
 ///  * <https://material.io/design/components/tooltips.html>
+///  * [TooltipTheme] or [ThemeData.tooltipTheme]
 class Tooltip extends StatefulWidget {
   /// Creates a tooltip.
   ///
-  /// By default, tooltips prefer to appear below the [child] widget when the
-  /// user long presses on the widget.
+  /// By default, tooltips should adhere to the
+  /// [Material specifications](https://material.io/design/components/tooltips.html#spec).
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/tooltip.dart]: specifications => specification

**Review by HansMuller — APPROVED** [review]
LGTM!

File: packages/flutter/lib/src/material/tooltip.dart (hunk 14 above)
Comment (shihaohong) [reply packages/flutter/lib/src/material/tooltip.dart]: Yes! I'll update that
