### PR TITLE
ShaderMask on web for CupertinoContextMenu

### LINKED ISSUE #52967: CupertinoContextMenu doesn't fully work on the web
CupertinoContextMenu uses the ShaderMask widget, which currently [isn't supported](https://github.com/flutter/flutter/issues/44152) on web.  So, when a CupertinoContextMenu is used on the web, an obscure error is thrown.  The [docs](https://master-api.flutter.dev/flutter/cupertino/CupertinoContextMenu-class.html) for CupertinoContextMenu has a broken dartpad example because of this problem.

*Update*: CupertinoContextMenu is usable on web now, but it is missing the small darkening/lightening effect on the target before the menu opens.  Fixing that depends on https://github.com/flutter/flutter/issues/44152.

### PR DESCRIPTION
**Pull request by justinmc**
I'm [told](https://github.com/flutter/flutter/issues/52967#issuecomment-785506069) that web now supports ShaderMask, so we can remove this workaround that was put into CupertinoContextMenu to simplify it so it didn't need ShaderMask on web.

Also unskips ShaderMask tests on web.

Closes https://github.com/flutter/flutter/issues/52967

### CODE REVIEW

**Review by LongCatIsLooong — APPROVED** [review]

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 1]
```diff
@@ -104,10 +103,7 @@ void main() {
       Rect decoyChildRect = tester.getRect(_findDecoyChild(child));
       expect(childRect, equals(decoyChildRect));
 
-      // TODO(justinmc): When ShaderMask is supported on web, remove this
-      // conditional and just check for ShaderMask.
-      // https://github.com/flutter/flutter/issues/52967.
-      expect(find.byType(ShaderMask), kIsWeb ? findsNothing : findsOneWidget);
+      expect(find.byType(ShaderMask), findsOneWidget);
```
Comment (LongCatIsLooong) [inline packages/flutter/test/cupertino/context_menu_test.dart:106]: The test is getting skipped when `isBrowser` is true. Is the skipping still needed?

**Comment by skia-gold** [comment]
Gold has detected about 2 untriaged digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/77864

**Review by ferhatb — COMMENTED** [review]
LGTM. Thank you for unskipping tests too.
