### PR TITLE
[ios][engine] Fix autofill context cleanup and view lifecycle management

### LINKED ISSUE #145681: `AutofillContextAction.cancel` in `AutofillGroup#onDisposeAction` does not work as expected on iPhone.
### Steps to reproduce

1. (developer) Prepare AutofillGroup
   * Make username and password fields child elements.
   * Set `onDisposeAction: AutofillContextAction.cancel` for AutofillGroup
2. (user) enter username and password in the AutofillGroup child element
3. return to previous screen or go to next screen

### Expected results

A sheet for saving username and password is not displayed.

### Actual results

A sheet for saving username and password is displayed.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter autofill issue',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
        ),
      ),
      home: const FirstPage(),
    );
  }
}

class FirstPage extends StatelessWidget {
  const FirstPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('First Page'),
      ),
      body: Center(
        child: FilledButton(
          onPressed: () {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) => const SecondPage(),
              ),
            );
          },
          child: const Text('Go to Second Page'),
        ),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Page'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: AutofillGroup(
          onDisposeAction: AutofillContextAction.cancel,
          child: Column(
            children: [
              const TextField(
                decoration: InputDecoration(
                  labelText: 'Username',
                ),
                autofillHints: [
                  AutofillHints.username,
                ],
              ),
              const SizedBox(
                height: 16,
              ),
              const TextField(
                decoration: InputDecoration(
                  labelText: 'Password',
                ),
                autofillHints: [
                  AutofillHints.password,
                ],
              ),
              const SizedBox(
                height: 16,
              ),
              FilledButton(
                onPressed: () {
                  TextInput.finishAutofillContext(
                    shouldSave: true,
                  );
                },
                child: const Text('Submit'),
              ),
              const SizedBox(
                height: 16,
              ),
              FilledButton(
                onPressed: () {
                  Navigator.of(context).push(
                    MaterialPageRoute(
                      builder: (context) => const ThirdPage(),
                    ),
                  );
                },
                child: const Text('Go to Third Page'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class ThirdPage extends StatelessWidget {
  const ThirdPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Third Page'),
      ),
      body: Center(
        child: FilledButton(
          onPressed: () {
            Navigator.of(context).pop();
          },
          child: const Text('Go back to Second Page'),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/17231507/095d59d9-e32c-47dc-8de0-0241761734fa

</details>

### Logs

<details open><summary>Logs</summary>

```console
Launching lib/main.dart on iPhone Xs in debug mode...
Running Xcode build...
Xcode build done.                                            5.3s
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
Debug service listening on ws://127.0.0.1:53891/st0zbwSK1OA=/ws
Syncing files to device iPhone Xs...
Application finished.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4 23E214 darwin-arm64, locale
    ja-JP)
    • Flutter version 3.19.4 on channel stable at /Users/koji/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (5 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/koji/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/koji/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/koji/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2023.3.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 78.4.2
    • Dart plugin version 233.15026.12

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • iPhone Xs (mobile) • 0E4C5F44-27EB-4EA3-9FCB-C6605D110BF5 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64
      • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 123.0.6312.59

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by koji-1009**
fix https://github.com/flutter/flutter/issues/145681

I created a PR based on the survey described in [comment](https://github.com/flutter/flutter/issues/145681#issuecomment-3151444768). The existing processing is not deleted, but the method to be executed is moved. If `_autofillContext` is not empty, the timing of removing `activeView` and `_inputHider` is delayed.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by koji-1009** [comment]
Hi @LongCatIsLooong, I've removed `removeFromSuperview` from `hideTextInput`. What do you think of this fix?

**Comment by jmagman** [comment]
Need to make sure this doesn't regress https://github.com/flutter/flutter/issues/71885.
cc @chunhtai who worked on this flutter/engine#23776

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm [hunk 1]
```diff
@@ -2518,6 +2520,8 @@ - (void)handleKeyboardWillShow:(NSNotification*)notification {
 }
 
 - (void)dealloc {
+  [_autofillContext removeAllObjects];
```
Comment (LongCatIsLooong) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm]: Thanks for catching these! nit: should this just call reset then?

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm [hunk 2]
```diff
@@ -2797,22 +2803,6 @@ - (void)startLiveTextInput {
...
-  // the newly attached active view while performing accessibility update.
-  // This results in accessibility focus stuck at the FlutterTextInputView.
-  if (!_enableFlutterTextInputViewAccessibilityTimer) {
-    _enableFlutterTextInputViewAccessibilityTimer =
-        [NSTimer scheduledTimerWithTimeInterval:kUITextInputAccessibilityEnablingDelaySeconds
-                                         target:[FlutterTimerProxy proxyWithTarget:self]
-                                       selector:@selector(enableActiveViewAccessibility)
-                                       userInfo:nil
-                                        repeats:NO];
-  }
```
Comment (LongCatIsLooong) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2836]: I'm hoping we can just remove these (at least the timer).

Per @chunhtai (if I recall correctly) this is for cases like navigating to a new route with an "autofocus: true" text field. But I think when that happens, the accessibility bridge would have already received the new semantics tree, especially with the [current implementation](https://github.com/flutter/flutter/blob/f604188a4540436978880ae7848a97a0acc2d13a/packages/flutter/lib/src/widgets/editable_text.dart#L3248-L3256) where `autofocus` is scheduled in a post frame callback and semantics updates are sent synchronously to the accessibility bridge on iOS.

Comment (LongCatIsLooong) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2836]: @chunhtai do you think this can be removed?

Comment (LongCatIsLooong) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2836]: Also, if we're worried about the timing with the semantics tree update, shouldn't accessibility bridge be the one that calls `enableActiveViewAccessbility` when it's ready, instead of the text input plugin tries to coordinate with the accessibility bridge?

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm (hunk 1 above)
Comment (koji-1009) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm]: I changed it to call `reset`. Thanks for the advice. [5af6987](https://github.com/flutter/flutter/pull/173598/commits/5af698716c7a263b3caa091b34bc9a329ac89c5e)

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm (hunk 2 above)
Comment (chunhtai) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2836]: The current implementation was five years ago https://github.com/flutter/flutter/commit/bf551a31fe7ef45c854a219686b6837400bfd94c.

Where this changed was introduced 4 years ago https://github.com/flutter/flutter/commit/d2dacb33bc353b4c89e41a570efecb4c6d31a3a7

I am not sure if this is still needed either though.

> if we're worried about the timing with the semantics tree update, shouldn't accessibility bridge be the one that calls enableActiveViewAccessbility.

This is only an issue due to iOS internal implementation that it reuses UItextinput for text editing and a11y tree. From the framework perspective, there is nothing wrong that autofocus the textfield and then sends a11y tree update. The keyboard focus and a11y focus are separated concepts in the first place.

Comment (chunhtai) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2836]: Is removing this delay necessary for autofill to work?

Comment (LongCatIsLooong) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2836]: > Is removing this delay necessary for autofill to work?

I would think not (it's more of a drive-by comment). 

> From the framework perspective, there is nothing wrong that autofocus the textfield and then sends a11y tree update. The keyboard focus and a11y focus are separated concepts in the first place.

Yeah the framework doesn't have to know about the details of what UIKit / the text input plugin does, but the iOS accessibility bridge is specialized for the iOS implementation, and to me it seems to be the perfect place to determining when to switch between an a11y node and the "real" input field (instead of using a timer in TextInputPlugin). But again I digress.


IIRC the PR moves the switch code from `show/hide` to `setInputClient/clearInputClient`, so the timing is a bit different and the app may call `show/hide` themselves to dismiss / reveal the virtual keyboard. Do you happen to know if that will break anything, or are there things we should test to make sure there's no regression.

Comment (chunhtai) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2836]: > the iOS accessibility bridge is specialized for the iOS implementation, and to me it seems to be the perfect place to determining when to switch between an a11y node and the "real" input field (instead of using a timer in TextInputPlugin). But again I digress.

Oh I misread the original question, yeah moving this to ios a11ybridge is fine. It just feels a bit weird that a11y needs to listen to textinputplugin activation and then set the attribute on textinputplugin, but I get it makes a bit more sense to structure the code this way

> PR moves the switch code from show/hide to setInputClient/clearInputClient, so the timing is a bit different and the app may call show/hide themselves to dismiss / reveal the virtual keyboard. Do you happen to know if that will break anything, or are there things we should test to make sure there's no regression.

I think this is probably fine. to do a manual test just create a push a new route with autofocus textfield in voice over and see if you will see weird focus behavior

Comment (LongCatIsLooong) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2836]: Sounds good I'll give that a try.

Comment (LongCatIsLooong) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2836]: (trying the implementation out now).

Comment (LongCatIsLooong) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:2836]: I tried out the patch and the behavior seems to be exactly the same in my test app:
```dart
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: TextButton(
          onPressed: () {
            Navigator.of(context).push(MaterialPageRoute(builder: (context) {
              return Scaffold(
                //appBar: AppBar(title: const Text('My Page')),
                body: Column(
                  children: [
                    TextButton(
                      child: const Text('POP'),
                      onPressed: () {
                        Navigator.pop(context);
                      },
                    ),
                    TextField(
                      autofocus: true,
                    )
                  ],
                ),
              );
            }));
          },
          child: Text('123')),
    ));
  }
}
```

The only weirdness I observed: when I press the "123" button and wait for the route transition to finish, the accessibility focus indicator (the rectangle with black borders) would sometimes show over an empty area with no interactive UI elements and announce "one hundred and twenty three". I'm seeing that with and without this patch so I guess that's not related.

**Review by LongCatIsLooong — APPROVED** [review]

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by LongCatIsLooong** [comment]
the google testing failures don't seem related. Syncing to the tip of the tree and retrying.

**Comment by koji-1009** [comment]
Thank you!
