### PR TITLE
[web] Popping a nameless route should preserve the correct route name

### LINKED ISSUE #173356: The showDialog bug prevents Flutter from being applied to production-level web applications.
### Steps to reproduce

1. Jump from the home page to the detail page
2. Open the dialog on the detail page.
3. Click the back button that comes with the Edge Mobile browser.

### Expected results

The dialog will close, and the page will remain on the detail page, with the URL being "/detail"

### Actual results

The dialog will close, and the page will remain on the detail page, But the URL is /

### Code sample

part1

```dart
routes:  {
  '/': (context) => const HomePage(),
  '/detail': (context) => const DetailPage(),
},
```

part2

```dart
onTap: () {
  showDialog(
    context: context,
    builder:
        (ctx) => AlertDialog(
      title: const Text('Invalid Input'),
      content: const Text('Please enter all the fields'),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(ctx),
          child: const Text('Okay'),
        ),
      ],
    ),
  );
```
Do not click the "OK" button. Instead, click the back button built into the Edge browser (since you cannot prevent users from doing so). Clicking the "OK" button is normal. Only by clicking the back button provided by the browser can this bug be reproduced.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.32.8, on Microsoft Windows [版本 10.0.19045.6093], locale zh-CN)
[√] Windows Version (10 专业版 64 位, 22H2, 2009)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.1)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.2)
[√] IntelliJ IDEA Ultimate Edition (version 2025.1)
[√] Connected device (4 available)
[√] Network resources

### PR DESCRIPTION
**Pull request by mdebbar**
Fixes https://github.com/flutter/flutter/issues/173356

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/navigation/history.dart [hunk 1]
```diff
@@ -258,19 +257,30 @@ class SingleEntryBrowserHistory extends BrowserHistory {
     _setupStrategy(strategy);
 
     final String path = currentPath;
-    if (!_isFlutterEntry(domWindow.history.state)) {
+    _currentRouteName = path;
```
Comment (chunhtai) [inline engine/src/flutter/lib/web_ui/lib/src/engine/navigation/history.dart]:
```dart
_currentRouteName = currentPath
```

File: engine/src/flutter/lib/web_ui/lib/src/engine/navigation/history.dart [hunk 2]
```diff
@@ -303,11 +313,11 @@ class SingleEntryBrowserHistory extends BrowserHistory {
   @override
   void setRouteName(String? routeName, {Object? state, bool replace = false}) {
     if (urlStrategy != null) {
-      _setupFlutterEntry(urlStrategy!, replace: true, path: routeName);
+      _currentRouteName = routeName ?? currentPath;
```
Comment (chunhtai) [inline engine/src/flutter/lib/web_ui/lib/src/engine/navigation/history.dart:315]: i think `routeName` will never be null given since `routeUpdated` method has been deprecated for ages.

File: engine/src/flutter/lib/web_ui/test/engine/history_test.dart [hunk 3]
```diff
@@ -293,7 +295,7 @@ void testMain() {
       expect(spy.messages[0].methodName, 'pushRoute');
       expect(spy.messages[0].methodArguments, '/page3');
       spy.messages.clear();
-      // 2. The framework sends a `routePushed` platform message.
+      // 2. The framework sends a `routeUpdated` platform message.
```
Comment (chunhtai) [inline engine/src/flutter/lib/web_ui/test/engine/history_test.dart:298]: not something need to be address in this pr, routeUpdated is not used by framework for a long time now

File: engine/src/flutter/lib/web_ui/test/engine/history_test.dart [hunk 4]
```diff
@@ -341,6 +343,35 @@ void testMain() {
...
     });
+
+    test('popping a nameless route does not change url', () async {
+      final TestUrlStrategy strategy = TestUrlStrategy.fromEntry(
+        const TestHistoryEntry(null, null, '/home'),
+      );
+      await implicitView.debugInitializeHistory(strategy, useSingle: true);
+
+      // Go to a named route.
+      await routeUpdated('/named-route');
```
Comment (chunhtai) [inline engine/src/flutter/lib/web_ui/test/engine/history_test.dart:354]: let's use routeInformationUpdated for accuracy

**Review by chunhtai — COMMENTED** [review]
LGTM, just some minor comment

**Review by chunhtai — APPROVED** [review]

File: engine/src/flutter/lib/web_ui/lib/src/engine/navigation/history.dart (hunk 2 above)
Comment (mdebbar) [reply engine/src/flutter/lib/web_ui/lib/src/engine/navigation/history.dart:315]: Do you think it's safe to remove the entire `routeUpdated` handler:
https://github.com/flutter/flutter/blob/1eb2f68da5a7d38e0c3bdef887d888a6594a6a9d/engine/src/flutter/lib/web_ui/lib/src/engine/window.dart#L628-L632

Comment (chunhtai) [reply engine/src/flutter/lib/web_ui/lib/src/engine/navigation/history.dart:315]: yes, I think so, it has not been used since we have introduced Router. I forgot to clean it up

Comment (mdebbar) [reply engine/src/flutter/lib/web_ui/lib/src/engine/navigation/history.dart:315]: Ok, I'll do this cleanup in a follow up PR.
