### PR TITLE
macOS unzip then rsync to delete stale artifacts

### LINKED ISSUE #85062: iOS engine artifacts Flutter.xcframework contains old architecture triples directories
As of https://github.com/flutter/flutter/pull/85052 the Flutter engine iOS artifacts contain iOS ARM simulator binaries, and the `Flutter.xcframework` should only contain a `ios-arm64_x86_64-simulator` directory.  It also was built on Xcode 12, so the `ios-armv7_arm64` directory has been renamed `ios-arm64_armv7`.  However, because the artifact downloads do not remove old directories from the bundle, the old and new architecture triple directories exist next to each other.

### Steps to reproduce
```
$ git checkout stable
$ flutter precache
$ git checkout a2fa6d4 # master as of https://github.com/flutter/flutter/pull/85052
$ flutter precache
$ ls bin/cache/artifacts/engine/ios/Flutter.xcframework
```
### Expected
```
ios-arm64_armv7
ios-arm64_x86_64-simulator
```

### Actual
```
ios-arm64_armv7
ios-arm64_x86_64-simulator
ios-armv7_arm64
ios-x86_64-simulator
```

### PR DESCRIPTION
**Pull request by jmagman**
On macOS only, when unzipping, first unzip to a temp directory, then `rsync` with the `--delete` flag so stale files that aren't in the target directory are deleted, and files continue to only be updated as needed.  This adds an extra I/O copy step to unzipping, but will make sure deleted archive files are actually deleted.  This applies for downloading cached artifacts as well as unzipping prebuilt macOS and iOS app bundles.

Confirmed that the stale xcframework architecture triple directories are removed on this PR (more details in https://github.com/flutter/flutter/issues/85062)

Fixes https://github.com/flutter/flutter/issues/85062

There was a previous attempt to do this at https://github.com/flutter/flutter/pull/74818 but that only seems to delete `flutter/bin/cache/artifacts/engine/ios/artifacts` (which doesn't exist), not `flutter/bin/cache/artifacts/engine/ios/*`

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/os.dart [hunk 1]
```diff
@@ -427,6 +427,44 @@ class _MacOSUtils extends _PosixUtils {
...
+            <String>['rsync', '-av', '--delete', unzippedFile.path, targetDirectory.path],
+            throwOnError: true,
+            verboseExceptions: true,
+          );
+        }
+      } finally {
+        tempDirectory.deleteSync(recursive: true);
+      }
+    } else {
+      // Fall back to unzipping directly.
```
Comment (gw280) [inline packages/flutter_tools/lib/src/base/os.dart:460]: We should probably have a warning log here

**Review by Lofterheit — APPROVED** [review]

**Review by jonahwilliams — APPROVED** [review]
LGTM

We already require rsync and unzip on macOS

File: packages/flutter_tools/lib/src/base/os.dart (hunk 1 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/base/os.dart]: Done.
