### PR TITLE
Do not throw when trying to discover a fuchsia device and the sshConfig is invalid

### LINKED ISSUE #52849: `flutter run` and `flutter devices` fails with error about FUCHSIA_SSH_CONFIG
On macOS:

```
 dnfield@dnfield-macbookpro $ flutter run
Building flutter tool...
Cannot interact with device. No ssh config.
Try setting FUCHSIA_SSH_CONFIG or FUCHSIA_BUILD_DIR.
```

This started recently.  I'm not sure why.  If I modify `fuchsia_sdk.dart` to always return false from `isFuchsiaSupportedPlatform` it goes away.

/cc @gw280 @iskakaushik @jonahwilliams @zanderso

### PR DESCRIPTION
**Pull request by dnfield**
## Description

If there is a Fuchsia device discoverable on your network (via dev_finder), but you don't have any ssh config set up (e.g. because you're not actually developing for Fuchsia on this machine), the tool currently throws if you try to `flutter run` or `flutter devices`.

This makes it so we print an error and return the same default as in other error conditions in these code paths.

## Related Issues

Fixes #52849 

## Tests

I added the following tests:

Test that we don't throw if the ssh config is not present.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter_tools/lib/src/fuchsia/fuchsia_sdk.dart [hunk 1]
```diff
@@ -156,4 +156,10 @@ class FuchsiaArtifacts {
 
   /// The pm tool.
   final File pm;
+
+  /// Returns true if the [sshConfig] file is not null and exists.
+  bool validateSshConfig() {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/fuchsia/fuchsia_sdk.dart]: A getter like the following would probably be more idiomatic:
```dart
bool get hasSshConfig => sshConfig != null && sshConfig.existsSync();
```
(or `hasValidSshConfig`)

File: packages/flutter_tools/lib/src/fuchsia/fuchsia_device.dart [hunk 2]
```diff
@@ -480,16 +487,22 @@ class FuchsiaDevice extends Device {
 
   @override
   Future<String> get sdkNameAndVersion async {
+    const String defaultName = 'Fuchsia';
+    if (!globals.fuchsiaArtifacts.validateSshConfig()) {
+      globals.printError('Could not determine Fuchsia sdk name or version '
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/fuchsia/fuchsia_device.dart]: These could be `printTrace`. If someone is really trying to run on Fuchsia, they'll get a better error message later.

File: packages/flutter_tools/lib/src/fuchsia/fuchsia_device.dart [hunk 3]
```diff
@@ -423,11 +423,18 @@ class FuchsiaDevice extends Device {
   TargetPlatform _targetPlatform;
 
   Future<TargetPlatform> _queryTargetPlatform() async {
+    const TargetPlatform defaultTargetPlatform = TargetPlatform.fuchsia_arm64;
+    if (!globals.fuchsiaArtifacts.validateSshConfig()) {
+      globals.printError('Could not determine Fuchsia target platform because '
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/fuchsia/fuchsia_device.dart]: `printTrace` instead of `printError`.

File: packages/flutter_tools/lib/src/fuchsia/fuchsia_sdk.dart (hunk 1 above)
Comment (dnfield) [reply packages/flutter_tools/lib/src/fuchsia/fuchsia_sdk.dart]: Done.  At one point this was a method that was also checking that pm and dev_finder were executable, which seemed heavy for a getter, but also turned out to be less helpful than I thought.

File: packages/flutter_tools/lib/src/fuchsia/fuchsia_device.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter_tools/lib/src/fuchsia/fuchsia_device.dart]: Done and done.

**Review by zanderso — APPROVED** [review]

File: packages/flutter_tools/lib/src/fuchsia/fuchsia_device.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter_tools/lib/src/fuchsia/fuchsia_device.dart]: Errrr - I changed the wrong one, I'll fix that.
