### PR TITLE
Fixed regex to show missing assets file error

### LINKED ISSUE #97065: [Windows] Build failed without clalify error if asset file not exist
## Steps to Reproduce

1. create new project ```flutter create myapp```
2. add to pubspec not exit asset file: 
```
flutter:
  assets:
    - assets/somefile.txt
```
4. check warning in your IDE
3. run app

**actual result:**
build failed with error:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: пользовательская сборка для "..\myapp\build\windows\CMakeFiles\2dc32e292af62a6e4b8b352773afe775\flutter_windows.dll.rule;..\myapp\build\windows\CMakeFiles\469176a6d3b8459cb97902e5168c5d4b\flutter_assemble.rule" завершила работу с кодом 1. [..\myapp\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
```

**expected result:**
the error clarify the asset is missing

<details>
  <summary>flutter doctor</summary>

[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale ru-RU)
    • Flutter version 2.8.1 at [some_path]
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0
</details>

### PR DESCRIPTION
**Pull request by thisisjaymehta**
Added Regex to match error message from verbos build as suggested by @stuartmorgan [here](https://github.com/flutter/flutter/pull/98137#discussion_r810559589).
Modified Windows Build Test

Fixes #97065 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by thisisjaymehta** [comment]
Bug:
image


After fix:
image

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 1]
```diff
@@ -190,7 +190,18 @@ Future<void> _runBuild(
 
   // MSBuild sends all output to stdout, including build errors. This surfaces
   // known error patterns.
-  final RegExp errorMatcher = RegExp(r':\s*(?:warning|(?:fatal )?error).*?:');
+  final List<String> errorMessages = <String>[
+    r':\s*(?:warning|(?:fatal )?error).*?:',
+    r'Error detected in pubspec.yaml:',
```
Comment (loic-sharma) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:195]: Period should be escaped to not match any character:

```suggestion
    r'Error detected in pubspec\.yaml:',
```

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 2]
```diff
@@ -190,7 +190,18 @@ Future<void> _runBuild(
...
+  ];
+  // Known secondary error lines for pubspec.yaml errors:
+  final List<String> pubspecErrorDetails = <String>[
+    r'No file or variants found for asset:',
+  ];
+  final RegExp errorMatcher = RegExp(<String>[
+    ...errorMessages,
+    ...pubspecErrorDetails,
+  ].join('|'));
```
Comment (loic-sharma) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:204]: Does this work? I would expect that each regex would be wrapped in `(`. Something like:

```regex
:(\s*(?:warning|(?:fatal )?error).*?:)|(Error detected in pubspec.yaml:)|(No file or variants found for asset:)
```

File: packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart [hunk 3]
```diff
@@ -256,6 +258,8 @@ C:\foo\windows\runner\main.cpp(18): warning C4706: assignment within conditional
 main.obj : error LNK2019: unresolved external symbol "void __cdecl Bar(void)" (?Bar@@YAXXZ) referenced in function wWinMain [C:\foo\build\windows\runner\test.vcxproj]
 C:\foo\build\windows\runner\Debug\test.exe : fatal error LNK1120: 1 unresolved externals [C:\foo\build\windows\runner\test.vcxproj]
 C:\foo\windows\runner\main.cpp(17,1): error C2065: 'Baz': undeclared identifier [C:\foo\build\windows\runner\test.vcxproj]
+Error detected in pubspec.yaml:
+No file or variants found for asset: images/a_dot_burr.jpeg.
```
Comment (loic-sharma) [inline packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart:262]: Please create separate tests for expected error we match

File: packages/flutter_tools/lib/src/windows/build_windows.dart (hunk 2 above)
Comment (thisisjaymehta) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:204]: Since OR in first regex is already inside parantesis and other two regex's dont use OR, it works.
Demo: https://dartpad.dev/db72fced323edcf59414a373f42d49ce

**Comment by thisisjaymehta** [comment]
1. Fixed regex by escaping `pubspec\.yaml`
2. Added new test for pubspec related error

File: packages/flutter_tools/lib/src/windows/build_windows.dart (hunk 2 above)
Comment (loic-sharma) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:204]: Ah interesting!

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 4]
```diff
@@ -190,7 +190,18 @@ Future<void> _runBuild(
...
+    r'Error detected in pubspec\.yaml:',
+  ];
+  // Known secondary error lines for pubspec.yaml errors:
+  final List<String> pubspecErrorDetails = <String>[
+    r'No file or variants found for asset:',
+  ];
+  final RegExp errorMatcher = RegExp(<String>[
+    ...errorMessages,
+    ...pubspecErrorDetails,
+  ].join('|'));
```
Comment (loic-sharma) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:204]: Let's keep this simple, the string joining makes readability a tiny bit harder:

```suggestion
  final RegExp errorMatcher = RegExp(
    r'(:\s*(?:warning|(?:fatal )?error).*?:)|'
    r'Error detected in pubspec\.yaml:|'
    r'No file or variants found for asset:'
  );
```

Comment (loic-sharma) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:204]: Hm. What do you think of something like this?

```dart
  final RegExp errorMatcher = RegExp(
	<String>[
      // Known error messages
      r'(:\s*(?:warning|(?:fatal )?error).*?:)',
      r'Error detected in pubspec\.yaml:',
    
      // Known secondary error lines for pubspec.yaml
      r'|No file or variants found for asset:',
    ].join('|'),
  );
```

Comment (stuartmorgan) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:204]: That seems fine to me (other than the extra inline `|` which I assume is a typo).

Comment (loic-sharma) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:204]: Yup that was a typo, I updated the code snippet

Comment (thisisjaymehta) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:204]: I will test the new suggetion locally and commit. Thanks.

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 5]
```diff
@@ -190,7 +190,16 @@ Future<void> _runBuild(
 
   // MSBuild sends all output to stdout, including build errors. This surfaces
   // known error patterns.
-  final RegExp errorMatcher = RegExp(r':\s*(?:warning|(?:fatal )?error).*?:');
+  final RegExp errorMatcher = RegExp(
+	<String>[
```
Comment (loic-sharma) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:194]: Please use spaces:

```suggestion
    <String>[
```

**Review by loic-sharma — APPROVED** [review]
Looks good, nice work!

File: packages/flutter_tools/lib/src/windows/build_windows.dart (hunk 5 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:194]: as an aside, we should add a test for this in analyze.dart.

File: packages/flutter_tools/lib/src/windows/build_windows.dart [hunk 6]
```diff
@@ -190,7 +190,16 @@ Future<void> _runBuild(
...
+      // Known error messages
+      r'(:\s*(?:warning|(?:fatal )?error).*?:)',
+      r'Error detected in pubspec\.yaml:',
+
+      // Known secondary error lines for pubspec.yaml
+      r'No file or variants found for asset:',
+    ].join('|'),
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/windows/build_windows.dart:201]: Please create multiple regular expressions rather than joining together one super regex for readability and debugability.

**Review by christopherfujino — CHANGES_REQUESTED** [review]

File: packages/flutter_tools/lib/src/windows/build_windows.dart (hunk 6 above)
Comment (thisisjaymehta) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:201]: Currently `stdoutErrorMatcher` expects a `RegExp`. Hence the super regex.

```dart
result = await globals.processUtils.stream(
      <String>[
        cmakePath,
        '--build',
        buildDir.path,
        '--config',
        sentenceCase(buildModeName),
        if (install)
          ...<String>['--target', 'INSTALL'],
        if (globals.logger.isVerbose)
          '--verbose',
      ],
      environment: <String, String>{
        if (globals.logger.isVerbose)
          'VERBOSE_SCRIPT_LOGGING': 'true',
      },
      trace: true,
      stdoutErrorMatcher: errorMatcher, // <--- HERE
    );
```

Do you approve reformating `RegExp? stdoutErrorMatcher` to `List<RegExp>? stdoutErrorMatcher` in stram function?

```dart
@override
  Future<int> stream(
    List<String> cmd, {
    String? workingDirectory,
    bool allowReentrantFlutter = false,
    String prefix = '',
    bool trace = false,
    RegExp? filter,
    RegExp? stdoutErrorMatcher,  // <--- HERE
    StringConverter? mapFunction,
    Map<String, String>? environment,
  }) async {
```

That would allow for something like this:

```

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:201]: ahh, I see. This is fine (as is).

File: packages/flutter_tools/lib/src/windows/build_windows.dart (hunk 5 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/windows/build_windows.dart:194]: please still fix this

Comment (thisisjaymehta) [reply packages/flutter_tools/lib/src/windows/build_windows.dart]: Fixed

**Review by christopherfujino — APPROVED** [review]
LGTM
