### PR TITLE
Ensure that animated pairs of Tabs TextStyles have matching inherited values

### LINKED ISSUE #28784: TabBarTheme.labelStyle breaks the app
If you add any label style to TabBarTheme you get overflow error.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.2.2, on Mac OS X 10.14.3 18D109, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)

• No issues found!
```

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sandbox',
      theme: ThemeData(
        tabBarTheme: TabBarTheme(
          labelColor: Colors.blue,
          labelStyle: TextStyle( color: Colors.blue ), /// comment this out to make it work
        ),
      ),
      home: Scaffold(
        body: SafeArea(
          child: _Home(),
        ),
      ),
    );
  }
}

class _Home extends StatefulWidget {
  @override
  __HomeState createState() => __HomeState();
}

class __HomeState extends State<_Home> with SingleTickerProviderStateMixin {
  TabController _controller;

  @override
  void initState() {
    _controller = TabController(vsync: this, length: 3);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        TabBar(
          controller: _controller,
          tabs: <Widget>[
            Text("One"),
            Text("Two"),
            Text("Three"),
          ],
        ),
        Expanded(
          child: TabBarView(
            controller: _controller,
            children: <Widget>[
              Center(
                child: Text("One"),
              ),
              Center(
                child: Text("Two"),
              ),
              Center(
                child: Text("Three"),
              ),
            ],
          ),
        )
      ],
    );
  }
}

```

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building _TabStyle(animation: kAlwaysDismissedAnimation, dirty,
flutter: dependencies: [_LocalizationsScope-[GlobalKey#12053], _InheritedTheme], state:
flutter: _AnimatedState#837d9):
flutter: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 742 pos 12: 'a == null || b
flutter: == null || a.inherit == b.inherit': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      TextStyle.lerp 
flutter: #3      _TabStyle.build 
flutter: #4      _AnimatedState.build 
flutter: #5      StatefulElement.build 
flutter: #6      ComponentElement.performRebuild 
flutter: #7      Element.rebuild 
flutter: #8      ComponentElement._firstBuild 
flutter: #9      StatefulElement._firstBuild 
flutter: #10     ComponentElement.mount 
flutter: #11     Element.inflateWidget 
flutter: #12     Element.updateChild 
flutter: #13     SingleChildRenderObjectElement.mount 
flutter: #14     Element.inflateWidget 
flutter: #15     Element.updateChild 
flutter: #16     ComponentElement.performRebuild 
flutter: #17     Element.rebuild 
flutter: #18     ComponentElement._firstBuild 
flutter: #19     StatefulElement._firstBuild 
flutter: #20     ComponentElement.mount 
flutter: #21     Element.inflateWidget 
flutter: #22     MultiChildRenderObjectElement.mount 
flutter: #23     Element.inflateWidget 
flutter: #24     Element.updateChild 
flutter: #25     ComponentElement.performRebuild 
flutter: #26     Element.rebuild 
flutter: #27     ComponentElement._firstBuild 
flutter: #28     StatefulElement._firstBuild 
flutter: #29     ComponentElement.mount 
flutter: #30     Element.inflateWidget 
flutter: #31     Element.updateChild 
flutter: #32     ComponentElement.performRebuild 
flutter: #33     Element.rebuild 
flutter: #34     ComponentElement._firstBuild 
flutter: #35     ComponentElement.mount 
flutter: #36     Element.inflateWidget 
flutter: #37     Element.updateChild 
flutter: #38     SingleChildRenderObjectElement.mount 
flutter: #39     Element.inflateWidget 
flutter: #40     Element.updateChild 
flutter: #41     ComponentElement.performRebuild 
flutter: #42     Element.rebuild 
flutter: #43     ComponentElement._firstBuild 
flutter: #44     ComponentElement.mount 
flutter: #45     Element.inflateWidget 
flutter: #46     Element.updateChild 
flutter: #47     ComponentElement.performRebuild 
flutter: #48     Element.rebuild 
flutter: #49     ComponentElement._firstBuild 
flutter: #50     ComponentElement.mount 
flutter: #51     Element.inflateWidget 
flutter: #52     Element.updateChild 
flutter: #53     ComponentElement.performRebuild 
flutter: #54     Element.rebuild 
flutter: #55     ComponentElement._firstBuild 
flutter: #56     ComponentElement.mount 
flutter: #57     ParentDataElement.mount 
flutter: #58     Element.inflateWidget 
flutter: #59     MultiChildRenderObjectElement.mount 
flutter: #60     Element.inflateWidget 
flutter: #61     Element.updateChild 
flutter: #62     ComponentElement.performRebuild 
flutter: #63     Element.rebuild 
flutter: #64     ComponentElement._firstBuild 
flutter: #65     StatefulElement._firstBuild 
flutter: #66     ComponentElement.mount 
flutter: #67     Element.inflateWidget 
flutter: #68     Element.updateChild 
flutter: #69     ComponentElement.performRebuild 
flutter: #70     Element.rebuild 
flutter: #71     ComponentElement._firstBuild 
flutter: #72     ComponentElement.mount 
flutter: #73     Element.inflateWidget 
flutter: #74     Element.updateChild 
flutter: #75     ComponentElement.performRebuild 
flutter: #76     Element.rebuild 
flutter: #77     ComponentElement._firstBuild 
flutter: #78     StatefulElement._firstBuild 
flutter: #79     ComponentElement.mount 
flutter: #80     Element.inflateWidget 
flutter: #81     Element.updateChild 
flutter: #82     SingleChildRenderObjectElement.mount 
flutter: #83     Element.inflateWidget 
flutter: #84     Element.updateChild 
flutter: #85     ComponentElement.performRebuild 
flutter: #86     Element.rebuild 
flutter: #87     ComponentElement._firstBuild 
flutter: #88     ComponentElement.mount 
flutter: #89     Element.inflateWidget 
flutter: #90     Element.updateChild 
flutter: #91     SingleChildRenderObjectElement.mount 
flutter: #92     Element.inflateWidget 
flutter: #93     Element.updateChild 
flutter: #94     ComponentElement.performRebuild 
flutter: #95     Element.rebuild 
flutter: #96     ComponentElement._firstBuild 
flutter: #97     StatefulElement._firstBuild 
flutter: #98     ComponentElement.mount 
flutter: #99     Element.inflateWidget 
flutter: #100    Element.updateChild 
flutter: #101    ComponentElement.performRebuild 
flutter: #102    Element.rebuild 
flutter: #103    ComponentElement._firstBuild 
flutter: #104    StatefulElement._firstBuild 
flutter: #105    ComponentElement.mount 
flutter: #106    Element.inflateWidget 
flutter: #107    Element.updateChild 
flutter: #108    ComponentElement.performRebuild 
flutter: #109    Element.rebuild 
flutter: #110    ComponentElement._firstBuild 
flutter: #111    ComponentElement.mount 
flutter: #112    Element.inflateWidget 
flutter: #113    Element.updateChild 
flutter: #114    ComponentElement.performRebuild 
flutter: #115    Element.rebuild 
flutter: #116    ComponentElement._firstBuild 
flutter: #117    ComponentElement.mount 
flutter: #118    Element.inflateWidget 
flutter: #119    Element.updateChild 
flutter: #120    ComponentElement.performRebuild 
flutter: #121    Element.rebuild 
flutter: #122    ComponentElement._firstBuild 
flutter: #123    StatefulElement._firstBuild 
flutter: #124    ComponentElement.mount 
flutter: #125    Element.inflateWidget 
flutter: #126    Element.updateChild 
flutter: #127    SingleChildRenderObjectElement.mount 
flutter: #128    Element.inflateWidget 
flutter: #129    Element.updateChild 
flutter: #130    ComponentElement.performRebuild 
flutter: #131    Element.rebuild 
flutter: #132    ComponentElement._firstBuild 
flutter: #133    ComponentElement.mount 
flutter: #134    Element.inflateWidget 
flutter: #135    Element.updateChild 
flutter: #136    SingleChildRenderObjectElement.mount 
flutter: #137    Element.inflateWidget 
flutter: #138    Element.updateChild 
flutter: #139    SingleChildRenderObjectElement.mount 
flutter: #140    Element.inflateWidget 
flutter: #141    MultiChildRenderObjectElement.mount 
flutter: #142    Element.inflateWidget 
flutter: #143    Element.updateChild 
flutter: #144    ComponentElement.performRebuild 
flutter: #145    Element.rebuild 
flutter: #146    ComponentElement._firstBuild 
flutter: #147    StatefulElement._firstBuild 
flutter: #148    ComponentElement.mount 
flutter: #149    Element.inflateWidget 
flutter: #150    Element.updateChild 
flutter: #151    SingleChildRenderObjectElement.mount 
flutter: #152    Element.inflateWidget 
flutter: #153    Element.updateChild 
flutter: #154    ComponentElement.performRebuild 
flutter: #155    Element.rebuild 
flutter: #156    ComponentElement._firstBuild 
flutter: #157    StatefulElement._firstBuild 
flutter: #158    ComponentElement.mount 
flutter: #159    Element.inflateWidget 
flutter: #160    Element.updateChild 
flutter: #161    SingleChildRenderObjectElement.mount 
flutter: #162    Element.inflateWidget 
flutter: #163    Element.updateChild 
flutter: #164    ComponentElement.performRebuild 
flutter: #165    Element.rebuild 
flutter: #166    ComponentElement._firstBuild 
flutter: #167    StatefulElement._firstBuild 
flutter: #168    ComponentElement.mount 
flutter: #169    Element.inflateWidget 
flutter: #170    Element.updateChild 
flutter: #171    SingleChildRenderObjectElement.mount 
flutter: #172    Element.inflateWidget 
flutter: #173    Element.updateChild 
flutter: #174    ComponentElement.performRebuild 
flutter: #175    Element.rebuild 
flutter: #176    ComponentElement._firstBuild 
flutter: #177    StatefulElement._firstBuild 
flutter: #178    ComponentElement.mount 
flutter: #179    Element.inflateWidget 
flutter: #180    Element.updateChild 
flutter: #181    ComponentElement.performRebuild 
flutter: #182    Element.rebuild 
flutter: #183    ComponentElement._firstBuild 
flutter: #184    ComponentElement.mount 
flutter: #185    Element.inflateWidget 
flutter: #186    Element.updateChild 
flutter: #187    ComponentElement.performRebuild 
flutter: #188    Element.rebuild 
flutter: #189    ComponentElement._firstBuild 
flutter: #190    StatefulElement._firstBuild 
flutter: #191    ComponentElement.mount 
flutter: #192    Element.inflateWidget 
flutter: #193    Element.updateChild 
flutter: #194    SingleChildRenderObjectElement.mount 
flutter: #195    Element.inflateWidget 
flutter: #196    Element.updateChild 
flutter: #197    ComponentElement.performRebuild 
flutter: #198    Element.rebuild 
flutter: #199    ComponentElement._firstBuild 
flutter: #200    ComponentElement.mount 
flutter: #201    Element.inflateWidget 
flutter: #202    Element.updateChild 
flutter: #203    SingleChildRenderObjectElement.mount 
flutter: #204    Element.inflateWidget 
flutter: #205    Element.updateChild 
flutter: #206    ComponentElement.performRebuild 
flutter: #207    Element.rebuild 
flutter: #208    ComponentElement._firstBuild 
flutter: #209    StatefulElement._firstBuild 
flutter: #210    ComponentElement.mount 
flutter: #211    Element.inflateWidget 
flutter: #212    Element.updateChild 
flutter: #213    ComponentElement.performRebuild 
flutter: #214    Element.rebuild 
flutter: #215    ComponentElement._firstBuild 
flutter: #216    ComponentElement.mount 
flutter: #217    Element.inflateWidget 
flutter: #218    Element.updateChild 
flutter: #219    SingleChildRenderObjectElement.mount 
flutter: #220    Element.inflateWidget 
flutter: #221    Element.updateChild 
flutter: #222    ComponentElement.performRebuild 
flutter: #223    Element.rebuild 
flutter: #224    ComponentElement._firstBuild 
flutter: #225    ComponentElement.mount 
flutter: #226    Element.inflateWidget 
flutter: #227    Element.updateChild 
flutter: #228    ComponentElement.performRebuild 
flutter: #229    Element.rebuild 
flutter: #230    ComponentElement._firstBuild 
flutter: #231    StatefulElement._firstBuild 
flutter: #232    ComponentElement.mount 
flutter: #233    Element.inflateWidget 
flutter: #234    Element.updateChild 
flutter: #235    ComponentElement.performRebuild 
flutter: #236    Element.rebuild 
flutter: #237    ComponentElement._firstBuild 
flutter: #238    StatefulElement._firstBuild 
flutter: #239    ComponentElement.mount 
flutter: #240    Element.inflateWidget 
flutter: #241    MultiChildRenderObjectElement.mount 
flutter: #242    Element.inflateWidget 
flutter: #243    Element.updateChild 
flutter: #244    _TheatreElement.mount 
flutter: #245    Element.inflateWidget 
flutter: #246    Element.updateChild 
flutter: #247    ComponentElement.performRebuild 
flutter: #248    Element.rebuild 
flutter: #249    ComponentElement._firstBuild 
flutter: #250    StatefulElement._firstBuild 
flutter: #251    ComponentElement.mount 
flutter: #252    Element.inflateWidget 
flutter: #253    Element.updateChild 
flutter: #254    ComponentElement.performRebuild 
flutter: #255    Element.rebuild 
flutter: #256    ComponentElement._firstBuild 
flutter: #257    ComponentElement.mount 
flutter: #258    Element.inflateWidget 
flutter: #259    Element.updateChild 
flutter: #260    SingleChildRenderObjectElement.mount 
flutter: #261    Element.inflateWidget 
flutter: #262    Element.updateChild 
flutter: #263    ComponentElement.performRebuild 
flutter: #264    Element.rebuild 
flutter: #265    ComponentElement._firstBuild 
flutter: #266    StatefulElement._firstBuild 
flutter: #267    ComponentElement.mount 
flutter: #268    Element.inflateWidget 
flutter: #269    Element.updateChild 
flutter: #270    SingleChildRenderObjectElement.mount 
flutter: #271    Element.inflateWidget 
flutter: #272    Element.updateChild 
flutter: #273    SingleChildRenderObjectElement.mount 
flutter: #274    Element.inflateWidget 
flutter: #275    Element.updateChild 
flutter: #276    ComponentElement.performRebuild 
flutter: #277    Element.rebuild 
flutter: #278    ComponentElement._firstBuild 
flutter: #279    StatefulElement._firstBuild 
flutter: #280    ComponentElement.mount 
flutter: #281    Element.inflateWidget 
flutter: #282    Element.updateChild 
flutter: #283    ComponentElement.performRebuild 
flutter: #284    Element.rebuild 
flutter: #285    ComponentElement._firstBuild 
flutter: #286    ComponentElement.mount 
flutter: #287    Element.inflateWidget 
flutter: #288    Element.updateChild 
flutter: #289    ComponentElement.performRebuild 
flutter: #290    Element.rebuild 
flutter: #291    ComponentElement._firstBuild 
flutter: #292    ComponentElement.mount 
flutter: #293    Element.inflateWidget 
flutter: #294    Element.updateChild 
flutter: #295    ComponentElement.performRebuild 
flutter: #296    Element.rebuild 
flutter: #297    ComponentElement._firstBuild 
flutter: #298    ComponentElement.mount 
flutter: #299    Element.inflateWidget 
flutter: #300    Element.updateChild 
flutter: #301    ComponentElement.performRebuild 
flutter: #302    Element.rebuild 
flutter: #303    ComponentElement._firstBuild 
flutter: #304    ComponentElement.mount 
flutter: #305    Element.inflateWidget 
flutter: #306    Element.updateChild 
flutter: #307    ComponentElement.performRebuild 
flutter: #308    Element.rebuild 
flutter: #309    ComponentElement._firstBuild 
flutter: #310    StatefulElement._firstBuild 
flutter: #311    ComponentElement.mount 
flutter: #312    Element.inflateWidget 
flutter: #313    Element.updateChild 
flutter: #314    ComponentElement.performRebuild 
flutter: #315    Element.rebuild 
flutter: #316    ComponentElement._firstBuild 
flutter: #317    ComponentElement.mount 
flutter: #318    Element.inflateWidget 
flutter: #319    Element.updateChild 
flutter: #320    ComponentElement.performRebuild 
flutter: #321    Element.rebuild 
flutter: #322    ComponentElement._firstBuild 
flutter: #323    ComponentElement.mount 
flutter: #324    Element.inflateWidget 
flutter: #325    Element.updateChild 
flutter: #326    SingleChildRenderObjectElement.mount 
flutter: #327    Element.inflateWidget 
flutter: #328    Element.updateChild 
flutter: #329    ComponentElement.performRebuild 
flutter: #330    Element.rebuild 
flutter: #331    ComponentElement._firstBuild 
flutter: #332    ComponentElement.mount 
flutter: #333    Element.inflateWidget 
flutter: #334    Element.updateChild 
flutter: #335    ComponentElement.performRebuild 
flutter: #336    Element.rebuild 
flutter: #337    ComponentElement._firstBuild 
flutter: #338    ComponentElement.mount 
flutter: #339    Element.inflateWidget 
flutter: #340    Element.updateChild 
flutter: #341    ComponentElement.performRebuild 
flutter: #342    Element.rebuild 
flutter: #343    ComponentElement._firstBuild 
flutter: #344    ComponentElement.mount 
flutter: #345    Element.inflateWidget 
flutter: #346    Element.updateChild 
flutter: #347    ComponentElement.performRebuild 
flutter: #348    Element.rebuild 
flutter: #349    ComponentElement._firstBuild 
flutter: #350    ComponentElement.mount 
flutter: #351    Element.inflateWidget 
flutter: #352    Element.updateChild 
flutter: #353    ComponentElement.performRebuild 
flutter: #354    Element.rebuild 
flutter: #355    ComponentElement._firstBuild 
flutter: #356    ComponentElement.mount 
flutter: #357    Element.inflateWidget 
flutter: #358    Element.updateChild 
flutter: #359    SingleChildRenderObjectElement.mount 
flutter: #360    Element.inflateWidget 
flutter: #361    Element.updateChild 
flutter: #362    ComponentElement.performRebuild 
flutter: #363    Element.rebuild 
flutter: #364    ComponentElement._firstBuild 
flutter: #365    StatefulElement._firstBuild 
flutter: #366    ComponentElement.mount 
flutter: #367    Element.inflateWidget 
flutter: #368    Element.updateChild 
flutter: #369    ComponentElement.performRebuild 
flutter: #370    Element.rebuild 
flutter: #371    ComponentElement._firstBuild 
flutter: #372    ComponentElement.mount 
flutter: #373    Element.inflateWidget 
flutter: #374    Element.updateChild 
flutter: #375    ComponentElement.performRebuild 
flutter: #376    Element.rebuild 
flutter: #377    ComponentElement._firstBuild 
flutter: #378    StatefulElement._firstBuild 
flutter: #379    ComponentElement.mount 
flutter: #380    Element.inflateWidget 
flutter: #381    Element.updateChild 
flutter: #382    ComponentElement.performRebuild 
flutter: #383    Element.rebuild 
flutter: #384    ComponentElement._firstBuild 
flutter: #385    ComponentElement.mount 
flutter: #386    Element.inflateWidget 
flutter: #387    Element.updateChild 
flutter: #388    ComponentElement.performRebuild 
flutter: #389    Element.rebuild 
flutter: #390    ComponentElement._firstBuild 
flutter: #391    StatefulElement._firstBuild 
flutter: #392    ComponentElement.mount 
flutter: #393    Element.inflateWidget 
flutter: #394    Element.updateChild 
flutter: #395    ComponentElement.performRebuild 
flutter: #396    Element.rebuild 
flutter: #397    ComponentElement._firstBuild 
flutter: #398    ComponentElement.mount 
flutter: #399    Element.inflateWidget 
flutter: #400    Element.updateChild 
flutter: #401    RenderObjectToWidgetElement._rebuild 
flutter: #402    RenderObjectToWidgetElement.mount 
flutter: #403    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> 
flutter: #404    BuildOwner.buildScope 
flutter: #405    RenderObjectToWidgetAdapter.attachToRenderTree 
flutter: #406    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget 
flutter: #407    runApp 
flutter: #408    main 
flutter: #409    _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:189:25)
flutter: #414    _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
flutter: #415    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
flutter: #416    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided 6 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/material/tabs.dart': Failed assertion: line 347 pos 12: '_currentTabOffsets != null': is not true.
flutter: Another exception was thrown: A RenderFlex overflowed by 99284 pixels on the bottom.
```

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes https://github.com/flutter/flutter/issues/28784

The following kind of expression will assert because the inherit values for the two text styles do not match.  That's because the text styles provided by `DefaultTextStyle` and `Theme` have `inherit: false` and TextStyles created with `new TextStyle()` have `inherit: true`.

```
TextStyle.lerp(Theme.of(context).textTheme.display2, TextStyle(color: Colors.blue), 0.5));
```

Added an inherit parameter to TextStyle.copyWith and used it in the tabs code to ensure that the to-be-lerped text styles have the same inherit value.

### CODE REVIEW

File: packages/flutter/test/material/theme_test.dart [hunk 1]
```diff
@@ -731,7 +731,7 @@ class _TextStyleProxy implements TextStyle {
   }
 
   @override
-  TextStyle copyWith({ Color color, Color backgroundColor, String fontFamily, List<String> fontFamilyFallback, double fontSize, FontWeight fontWeight, FontStyle fontStyle, double letterSpacing, double wordSpacing, TextBaseline textBaseline, double height, Locale locale, ui.Paint foreground, ui.Paint background, List<Shadow> shadows, TextDecoration decoration, Color decorationColor, TextDecorationStyle decorationStyle, String debugLabel }) {
+  TextStyle copyWith({ bool inherit, Color color, Color backgroundColor, String fontFamily, List<String> fontFamilyFallback, double fontSize, FontWeight fontWeight, FontStyle fontStyle, double letterSpacing, double wordSpacing, TextBaseline textBaseline, double height, Locale locale, ui.Paint foreground, ui.Paint background, List<Shadow> shadows, TextDecoration decoration, Color decorationColor, TextDecorationStyle decorationStyle, String debugLabel }) {
```
Comment (goderbauer) [inline packages/flutter/test/material/theme_test.dart]: nit: this line looks like it could really use some line breaks...

**Review by goderbauer — APPROVED** [review]
LGTM
