### PR TITLE
Use first Dart VM Service found with mDNS if there are duplicates

### LINKED ISSUE #119535: Exact duplicate Dart VM Services when running flutter attach
Occasionally, there will be multiple results with the same application id and port when running `flutter attach`.

## Steps to Reproduce

1. Run flutter app wirelessly through Xcode
2. Run `flutter attach` in terminal
3. If you don't get the error, stop the attach and stop in Xcode and try steps 1-2 again

```
There are multiple Dart VM Services available.
Rerun this command with one of the following passed in as the app-id and device-vmservice-port:

  flutter attach --app-id "com.example.app_name" --device-vmservice-port xxxxxx
  flutter attach --app-id "com.example.app_name" --device-vmservice-port xxxxxx
```

### PR DESCRIPTION
**Pull request by vashworth**
Fixes https://github.com/flutter/flutter/issues/119535.

Also, fixes issue where device IP would not be included in mDNS results if auth code was not found, although hypothetically this should never occur.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/mdns_discovery.dart [hunk 1]
```diff
@@ -202,6 +202,7 @@ class MDnsVmServiceDiscovery {
       final List<MDnsVmServiceDiscoveryResult> results =
           <MDnsVmServiceDiscoveryResult>[];
       final Set<String> uniqueDomainNames = <String>{};
+      final Set<String> uniqueResultsByDomainName = <String>{};
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/mdns_discovery.dart:205]: The "by" name sounds like it should be a dictionary with a key of domain name mapped to values of unique results.  Can you name it something that describes more how it is different from `uniqueDomainNames`?

File: packages/flutter_tools/lib/src/mdns_discovery.dart [hunk 2]
```diff
@@ -338,6 +320,27 @@ class MDnsVmServiceDiscovery {
...
 
+  String _getAuthCode(String txtRecord) {
+    const String authCodePrefix = 'authCode=';
+    String? raw;
+    for (final String record in txtRecord.split('\n')) {
+      if (record.startsWith(authCodePrefix)) {
+        raw = record;
+        break;
+      }
+    }
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/mdns_discovery.dart:331]: I know you just moved this part, but can you make this use `LineSplitter` instead? `import 'convert.dart'` (not `dart:convert`). You can also use `where` (I wish `whereFirst` worked well with nullable values, but it doesn't...), up to you.
```suggestion
    final Iterable<String> matchingRecords =
        LineSplitter.split(txt.first.text).where((String record) => record.startsWith(authCodePrefix));
    for (final String record in matchingRecords) {
      raw = record;
      break;
    }
```

File: packages/flutter_tools/lib/src/mdns_discovery.dart [hunk 3]
```diff
@@ -322,17 +332,12 @@ class MDnsVmServiceDiscovery {
...
-    for (final String record in txtRecord.split('\n')) {
-      if (record.startsWith(authCodePrefix)) {
-        raw = record;
-        break;
-      }
-    }
-    if (raw == null) {
+    final Iterable<String> matchingRecords =
+        LineSplitter.split(txtRecord).where((String record) => record.startsWith(authCodePrefix));
+    if (matchingRecords.isEmpty) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/mdns_discovery.dart:337]: That's better than what I suggested 😄

**Review by jmagman — APPROVED** [review]
