### PR TITLE
Reset TextFormField to initial value after state change

### LINKED ISSUE #180056: `FormState.reset()` doesn't reset `TextFormField` if its parent rebuilds
### Steps to reproduce

1. Wrap your UI inside a Form widget and assign it a GlobalKey<FormState>.
2. Add a TextFormField inside the Form, and attach a TextEditingController initialized with an empty value.
3. Update the value of the TextFormField by modifying the controller’s text and calling setState()
4. Call _formKey.currentState!.reset() to reset the form fields to their initial state.

### Expected results

That TextFormField should revert to the initial empty value.

### Actual results

TextFormField stays at the value before setState is called.

### Code sample

<details open><summary>Minimal repro...</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: FormDemoScreen()));
}

class FormDemoScreen extends StatefulWidget {
  const FormDemoScreen({super.key});

  @override
  State<FormDemoScreen> createState() => _FormDemoState();
}

class _FormDemoState extends State<FormDemoScreen> {
  final _formKey = GlobalKey<FormState>();
  final _textFieldController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Form(
        key: _formKey,
        child: Column(
          children: [
            TextFormField(
              controller: _textFieldController,
              decoration: const InputDecoration(labelText: "Type something here - it won't reset!"),
              onChanged: (String value) {
                // However, commenting this out will make the reset work:
                setState(() {});
              },
            ),
        
            FormField<bool>(
              initialValue: false,
              builder: (FormFieldState<bool> state) {
                return CheckboxListTile(
                  title: const Text('This does reset though!'),
                  value: state.value ?? false,
                  onChanged: state.didChange,
                );
              },
            ),

            ElevatedButton(
              onPressed: () => _formKey.currentState?.reset(),
              child: const Text('Reset Form'),
            ),
          ],
        ),
      ),
    );
  }
}
```

<details><summary>Detailed sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Form Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
      home: const FormDemoScreen(),
    );
  }
}

class FormDemoScreen extends StatefulWidget {
  const FormDemoScreen({super.key});

  @override
  State<FormDemoScreen> createState() => _FormDemoState();
}

class _FormDemoState extends State<FormDemoScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _emailController = TextEditingController();

  final ValueKey<String> _key = const ValueKey("value");

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Form Demo')),
      body: Form(
        key: _formKey,
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            children: [
              Text('Hello: ${_nameController.text}'),
              // Text fields (already FormField widgets)
              TextFormField(
                controller: _emailController,
                decoration: const InputDecoration(labelText: 'Email'),
                validator: (value) =>
                    value?.isEmpty ?? true ? 'Required' : null,
              ),
              TextFormField(
                key: _key,
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Name'),
                onChanged: (String value) {
                  setState(() {});
                },
                validator: (value) =>
                    value?.isEmpty ?? true ? 'Required' : null,
              ),

              // Radio buttons wrapped in FormField
              FormField<String>(
                initialValue: null,
                builder: (FormFieldState<String> state) {
                  return Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text('Gender:'),
                      RadioListTile<String>(
                        title: const Text('Male'),
                        value: 'male',
                        groupValue: state.value,
                        onChanged: state.didChange,
                      ),
                      RadioListTile<String>(
                        title: const Text('Female'),
                        value: 'female',
                        groupValue: state.value,
                        onChanged: state.didChange,
                      ),
                      RadioListTile<String>(
                        title: const Text('Other'),
                        value: 'other',
                        groupValue: state.value,
                        onChanged: state.didChange,
                      ),
                    ],
                  );
                },
              ),

              // Checkboxes wrapped in FormField
              FormField<bool>(
                initialValue: false,
                builder: (FormFieldState<bool> state) {
                  return CheckboxListTile(
                    title: const Text('Subscribe to Newsletter'),
                    value: state.value ?? false,
                    onChanged: state.didChange,
                  );
                },
              ),

              FormField<bool>(
                initialValue: false,
                builder: (FormFieldState<bool> state) {
                  return CheckboxListTile(
                    title: const Text('Agree to Terms & Conditions'),
                    value: state.value ?? false,
                    onChanged: state.didChange,
                  );
                },
              ),

              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: () {
                  _formKey.currentState?.reset();
                },
                child: const Text('Reset Form'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.8, on macOS 15.5 24F74 darwin-arm64, locale en-IN) [752ms]
    • Flutter version 3.32.8 on channel stable at /Users/sahil.t/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision edada7c56e (5 months ago), 2025-07-25 14:08:03 +0000
    • Engine revision ef0cd00091
    • Dart version 3.8.1
    • DevTools version 2.45.1

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [3.9s]
    • Android SDK at /Users/sahil.t/Library/Android/sdk
    • Platform android-36, build-tools 35.0.0
    • Java binary at: /Users/sahil.t/Library/Java/JavaVirtualMachines/jbr-17.0.14/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment JBR-17.0.14+1-1367.22-nomod (build 17.0.14+1-b1367.22)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 16.4) [2.1s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    ! CocoaPods 1.15.2 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.1) [8ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)

[✓] VS Code (version 1.106.3) [7ms]
    • VS Code at /Applications/Visual Studio Code 3.app/Contents
    • Flutter extension version 3.124.0

[✓] Connected device (4 available) [10.6s]
    • ios            • iOS 18.5 22F76
    • iPhone 16 Plus (mobile)      • com.apple.CoreSimulator.SimRuntime.iOS-18-5 (simulator)
    • macOS (desktop)                • macos                                • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)                   • chrome                               • web-javascript • Google Chrome 143.0.7499.110

[✓] Network resources [495ms]
    • All expected network resources are available.

```

</details>

### PR DESCRIPTION
**Pull request by Mairramer**
Fixes flutter/flutter#180056
Fixes flutter/flutter#104975

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/text_form_field_test.dart [hunk 1]
```diff
@@ -1889,4 +1890,40 @@ void main() {
     controller.selection = const TextSelection.collapsed(offset: 0);
     tester.pump();
   });
+
+  testWidgets('TextFormField resets to initial value after setState', (WidgetTester tester) async {
```
Comment (loic-sharma) [inline packages/flutter/test/material/text_form_field_test.dart:1895]: For these kinds of tests, we add a link to the issue. This makes it easier to understand why we added the test.

```suggestion
  // Regression test for https://github.com/flutter/flutter/pull/181199.
  testWidgets('TextFormField resets to initial value after setState', (WidgetTester tester) async {
```

Comment (loic-sharma) [reply packages/flutter/test/material/text_form_field_test.dart:1895]: Great test BTW 👍

File: packages/flutter/lib/src/material/text_form_field.dart [hunk 2]
```diff
@@ -345,6 +345,7 @@ class _TextFormFieldState extends FormFieldState<String> {
   TextEditingController get _effectiveController => _textFormField.controller ?? _controller!.value;
 
   TextFormField get _textFormField => super.widget as TextFormField;
+  late final String? _initialValue;
```
Comment (loic-sharma) [inline packages/flutter/lib/src/material/text_form_field.dart]: Super nit: could you move this directly after `_controller` so that fields are grouped together, before properties.

**Review by loic-sharma — APPROVED** [review]
Thanks for the wonderful fix!

**Review by justinmc — APPROVED** [review]
Surprisingly straightforward! I like this solution for the reasons that @loic-sharma shared in https://github.com/flutter/flutter/issues/180056#issuecomment-3757475426. This seems like something that is the responsibility of TextFormField, so it makes sense to store the initial value there.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM
