### PR TITLE
✨ `flutter config --list`

### LINKED ISSUE #81831: [flutter_tools] Running `flutter config` should only show configured settings
## Use case
Currently running `flutter config` also prints the usage information, which constitutes all the flags the user could pass to turn a specific feature on, thus resulting in extra noise for someone who would only want to view the currently configured settings:
```
$ flutter config
Configure Flutter settings.

To remove a setting, configure it to an empty string.

The Flutter tool anonymously reports feature usage statistics and basic crash reports to help improve
Flutter tools over time. See Google's privacy policy: https://www.google.com/intl/en/policies/privacy/

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
...
```
The (new) user would have to scan this message all the way down to view the settings, or worse, might completely miss them.

## Proposal
Since the usage information can be also viewed by passing `-h`/`--help` just like other flutter sub-commands, `flutter config` could be _configured_ to only show the current user settings, with a suggestion to run `flutter config -h` to view all settings.
```
$ flutter config
Configured Flutter settings.
Run "flutter config -h" to see all available settings.

  enable-linux-desktop: true
  enable-web: true
  enable-ios: false

Analytics reporting is currently disabled.
```

### PR DESCRIPTION
**Pull request by AlexV525**
Resolves #81831.

The PR improves the `config` command in below ways:
- Does not print the settings in usages or other options.
- Adds the `--list` flag to print the full settings list.
- Separates usages for settings and analytics.
- Prints the restart tip when clearing features.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/commands/config.dart [hunk 1]
```diff
@@ -15,6 +15,7 @@ import '../runner/flutter_command_runner.dart';
 
 class ConfigCommand extends FlutterCommand {
   ConfigCommand({ bool verboseHelp = false }) {
+    argParser.addFlag('list', help: 'List all settings and their current values.');
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/commands/config.dart:18]: Consider adding `negatable: false`, since `--no-list` doesn't make sense as an option.

**Review by andrewkolos — CHANGES_REQUESTED** [review]
Requested one small change. Otherwise LGTM

File: packages/flutter_tools/lib/src/commands/config.dart (hunk 1 above)
Comment (AlexV525) [reply packages/flutter_tools/lib/src/commands/config.dart]: Done.

**Comment by AlexV525** [comment]
Google tests are still failing because of merge commits. I thought it was maximum retries limit but it seems not. @christopherfujino @andrewkolos Could you help with resolving it?

**Comment by christopherfujino** [comment]
Hmm, it says "manual started" now (but no link to results). I will give it some more time and if by the end of the day there are no test results, I will override the status. Please don't merge upstream in again unless there is a merge conflict (as it will re-trigger testing).

Also @andrewkolos please give this another review.

**Comment by AlexV525** [comment]
Now it's `Please rebase your PR to tip of tree. Your PR is out of date`.

**Review by andrewkolos — APPROVED** [review]
LGTM
