### PR TITLE
Report RpcException error thrown by _reloadSource vmservice rpc.

### LINKED ISSUE #16384: hot-reload an app that doesn't have main() crashes flutter tools
To repro with flutter_gallery: rename main() to main1() in `lib/main.dart`, then run the app. Observe errors on initial start:
```
[  +14 ms] E/flutter (23458): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
[        ] E/flutter (23458): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Dart_GetClosure expects argument 'library' to be non-null.
...
[  +40 ms] Connected to _flutterView/0xe77f1d60.
[   +1 ms] 🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
[   +1 ms] An Observatory debugger and profiler on Pixel 2 is available at: http://127.0.0.1:42623/
[        ] For a more detailed help message, press "h". To quit, press "q".
```

Press 'r' to hot reload(renaming main1 to main doesn't make a difference), observe the exception as flutter tools exits.
```
[   +1 ms] _flutter.setAssetBundlePath: {viewId: _flutterView/0xe77f1d60, assetDirectory: /data/user/0/io.flutter.demo.gallery/cache/flutter_galleryMGXEEO/flutter_gallery/build/flutter_assets}
[  +15 ms] _reloadSources: {pause: false, rootLibUri: /data/user/0/io.flutter.demo.gallery/cache/flutter_galleryMGXEEO/flutter_gallery/lib/main.dart.dill, packagesUri: /data/user/0/io.flutter.demo.gallery/cache/flutter_galleryMGXEEO/flutter_gallery/.packages, isolateId: isolates/358384796}
[  +18 ms] Error 105 received from application: Isolate must be runnable
[        ] {request: {method: _reloadSources, params: {pause: false, rootLibUri: /data/user/0/io.flutter.demo.gallery/cache/flutter_galleryMGXEEO/flutter_gallery/lib/main.dart.dill, packagesUri: /data/user/0/io.flutter.demo.gallery/cache/flutter_galleryMGXEEO/flutter_gallery/.packages, isolateId: isolates/358384796}}, details: Isolate must be runnable before this request is made.}
Unhandled exception:
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("type")
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      HotRunner.validateReloadReport (package:flutter_tools/src/run_hot.dart:415)
#2      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:542)
#3      _rootRunUnary (dart:async/zone.dart:1134)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#7      Future._propagateToListeners (dart:async/future_impl.dart:662)
#8      Future._completeWithValue (dart:async/future_impl.dart:477)
#9      Future.wait.<anonymous closure> (dart:async/future.dart:392)
#10     _rootRunUnary (dart:async/zone.dart:1134)
#11     _CustomZone.runUnary (dart:async/zone.dart:1031)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#14     Future._propagateToListeners (dart:async/future_impl.dart:662)
#15     Future._complete (dart:async/future_impl.dart:467)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#17     _completeOnAsyncReturn (dart:async-patch/dart:async/async_patch.dart:292)
#18     Isolate.reloadSources (package:flutter_tools/src/vmservice.dart:1059)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:77)
#20     _rootRunUnary (dart:async/zone.dart:1134)
#21     _CustomZone.runUnary (dart:async/zone.dart:1031)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#24     Future._propagateToListeners (dart:async/future_impl.dart:662)
#25     Future._complete (dart:async/future_impl.dart:467)
#26     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#27     _completeOnAsyncReturn (dart:async-patch/dart:async/async_patch.dart:292)
#28     VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:758)
#29     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:84)
#30     _rootRunBinary (dart:async/zone.dart:1146)
#31     _CustomZone.runBinary (dart:async/zone.dart:1039)
#32     _FutureListener.handleError (dart:async/future_impl.dart:141)
#33     Future._propagateToListeners.handleError (dart:async/future_impl.dart:645)
#34     Future._propagateToListeners (dart:async/future_impl.dart:666)
#35     Future._completeError (dart:async/future_impl.dart:485)
#36     Future.timeout.<anonymous closure> (dart:async/future_impl.dart:736)
#37     _rootRunBinary (dart:async/zone.dart:1146)
#38     _CustomZone.runBinary (dart:async/zone.dart:1039)
#39     _FutureListener.handleError (dart:async/future_impl.dart:141)
#40     Future._propagateToListeners.handleError (dart:async/future_impl.dart:645)
#41     Future._propagateToListeners (dart:async/future_impl.dart:666)
#42     Future._completeError (dart:async/future_impl.dart:485)
#43     _SyncCompleter._completeError (dart:async/future_impl.dart:55)
#44     _Completer.completeError (dart:async/future_impl.dart:27)
#45     Future.any.<anonymous closure> (dart:async/future.dart:454)
#46     _rootRunBinary (dart:async/zone.dart:1146)
#47     _CustomZone.runBinary (dart:async/zone.dart:1039)
#48     _FutureListener.handleError (dart:async/future_impl.dart:141)
#49     Future._propagateToListeners.handleError (dart:async/future_impl.dart:645)
#50     Future._propagateToListeners (dart:async/future_impl.dart:666)
#51     Future._completeError (dart:async/future_impl.dart:485)
#52     _SyncCompleter._completeError (dart:async/future_impl.dart:55)
#53     _Completer.completeError (dart:async/future_impl.dart:27)
#54     Client._handleSingleResponse (package:json_rpc_2/src/client.dart:191)
#55     Client._handleResponse (package:json_rpc_2/src/client.dart:179)
#56     _rootRunUnary (dart:async/zone.dart:1134)
#57     _CustomZone.runUnary (dart:async/zone.dart:1031)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#62     _StreamController._add (dart:async/stream_controller.dart:639)
#63     _StreamController.add (dart:async/stream_controller.dart:585)
#64     Peer.listen.<anonymous closure> (package:json_rpc_2/src/peer.dart:91)
#65     _rootRunUnary (dart:async/zone.dart:1134)
#66     _CustomZone.runUnary (dart:async/zone.dart:1031)
#67     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#68     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#69     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#70     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#71     _MapStream._handleData (dart:async/stream_pipe.dart:232)
#72     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#73     _rootRunUnary (dart:async/zone.dart:1134)
#74     _CustomZone.runUnary (dart:async/zone.dart:1031)
#75     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#76     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#77     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#78     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)
#79     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98)
#80     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)
#81     _rootRunUnary (dart:async/zone.dart:1134)
#82     _CustomZone.runUnary (dart:async/zone.dart:1031)
#83     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#84     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#85     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#86     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#87     _StreamController._add (dart:async/stream_controller.dart:639)
#88     _rootRunUnary (dart:async/zone.dart:1134)
#89     _CustomZone.runUnary (dart:async/zone.dart:1031)
#90     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#91     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#92     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#93     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#94     _StreamController._add (dart:async/stream_controller.dart:639)
#95     _StreamController.add (dart:async/stream_controller.dart:585)
#96     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1128)
#97     _rootRunUnary (dart:async/zone.dart:1134)
#98     _CustomZone.runUnary (dart:async/zone.dart:1031)
#99     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#100    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#101    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#102    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#103    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#104    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334)
#105    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229)
#106    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#107    _rootRunUnary (dart:async/zone.dart:1134)
#108    _CustomZone.runUnary (dart:async/zone.dart:1031)
#109    _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#110    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#111    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#112    _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#113    _StreamController._add (dart:async/stream_controller.dart:639)
#114    _StreamController.add (dart:async/stream_controller.dart:585)
#115    _Socket._onData (dart:io-patch/socket_patch.dart:1674)
#116    _rootRunUnary (dart:async/zone.dart:1138)
#117    _CustomZone.runUnary (dart:async/zone.dart:1031)
#118    _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#119    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#120    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#121    _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#122    _StreamController._add (dart:async/stream_controller.dart:639)
#123    _StreamController.add (dart:async/stream_controller.dart:585)
#124    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#125    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:799)
#126    _microtaskLoop (dart:async/schedule_microtask.dart:41)
#127    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#128    _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#129    _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

### PR DESCRIPTION
**Pull request by aam**
Fixes https://github.com/flutter/flutter/issues/16384

### CODE REVIEW

**Comment by a-siva** [comment]
Is this still a change we need?

**Comment by aam** [comment]
> Is this still a change we need?
Yes, I think the use case is still valid - in absence of hot reload report flutter tools crashes.

File: packages/flutter_tools/lib/src/run_hot.dart [hunk 1]
```diff
@@ -537,6 +537,13 @@ class HotRunner extends ResidentRunner {
           // TODO(aam): Investigate why we are validating only first reload report,
           // which seems to be current behavior
           final Map<String, dynamic> firstReport = list.first;
+          if (firstReport == null) {
+            // This could happen if the isolate is not actually running,
+            // failed to start for some reason. For example, if main method
+            // is not found in the app.
+            retrieveFirstReloadReport.completeError('Dart VM failed to provide reload report');
```
Comment (a-siva) [inline packages/flutter_tools/lib/src/run_hot.dart]: maybe the message should state
'Reload failed, please restart the application'

**Review by a-siva — APPROVED** [review]

File: packages/flutter_tools/lib/src/run_hot.dart (hunk 1 above)
Comment (aam) [reply packages/flutter_tools/lib/src/run_hot.dart]: This message comes up in context where it is clear that hot reload failed, it's purpose seem to provide more details as to why it failed:
```
Initializing hot reload...
Error 105 received from application: Isolate must be runnable
Try again after fixing the above error(s).
Hot reload failed: Dart VM failed to provide reload report
```

Comment (a-siva) [reply packages/flutter_tools/lib/src/run_hot.dart]: In that case would it make sense to use the actual error
'main' not found
in this case.

The message 'Dart VM failed to provide reload report' sounds like an internal error to me.

Comment (aam) [reply packages/flutter_tools/lib/src/run_hot.dart]: I think it is kind of internal error, it's just we are handling it more gracefully. In the console output you can actually see that we complained that `main` was not found first:
```
Initializing gradle...
Built build/app/outputs/apk/debug/app-debug.apk (30.3MB).
Installing build/app/outputs/apk/app.apk...
I/FlutterActivityDelegate(18782): onResume setting current activity to this
E/flutter (18782): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
E/flutter (18782): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Dart_GetClosure expects argument 'library' to be non-null.
Syncing files to device Android SDK built for x86...

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8104/
For a more detailed help message, press "h". To quit, press "q".
r

Initializing hot reload...
Error 105 received from application: Isolate must be runnable
Try again after fixing the above error(s).
Hot reload failed: Dart VM failed to provide reload report
```

Comment (a-siva) [reply packages/flutter_tools/lib/src/run_hot.dart]: The app did not start in the first place because it got the error 'The binary program does not contain 'main'', why did we not quit the execution instead of displaying the 'hot reload' prompt.
What does it mean to 'hot reload' an app that did not start at all ?

Comment (aam) [reply packages/flutter_tools/lib/src/run_hot.dart]: This PR addresses just a crashing part of current user experience. The app still doesn't run, but flutter tools doesn't crash anymore, just produces an error.

Comment (aam) [reply packages/flutter_tools/lib/src/run_hot.dart]: Ideally in this particular case we stop flutter tools from progressing forward after request to run flutter app failed, but it will take some more effort because currently there is no api for engine to report errors during launch. Also, there is engine refactor that should land first before the api is adjusted further.

Comment (a-siva) [reply packages/flutter_tools/lib/src/run_hot.dart]: Ok, maybe a TODO here about stopping flutter tools in this case.
Can we also change the message to 'launch of app failed' or something like that.

Comment (aam) [reply packages/flutter_tools/lib/src/run_hot.dart]: Added TODO.

The message is already says "Hot reload failed:". This adds some more context as to the reason why it failed, so the end result looks like this: "Hot reload failed: Dart VM failed to provide reload report".

Comment (aam) [reply packages/flutter_tools/lib/src/run_hot.dart]: Turns out there is better way to handle this as `null` overrides properly formed error message in Flutter vmservice.

**Review by rmacnak-google — APPROVED** [review]

**Review by a-siva — APPROVED** [review]
