### PR TITLE
Fix selectWordsInRange when last word is located before the first word

### LINKED ISSUE #32339: Long-press-drag in text fields only expands correctly in one direction, and the originally selected word should stay highlighted during the expansion
#### Android
1. Create a `TextField`
2. Enter "abc def ghi"
3. Long press on "e" to highlight "def"
4. Move the touch point to "h", "def gh" is selected as expected
5. Move the touch point to "a", the space between "abc" and "def" is selected.

#### iOS
Double tap drag has not yet been implemented (tracked in #23973), but `RenderEditable.selectPositionAt` seems to work only in one direction.

#### Expected: 
5. On both iOS and Android, move the touch point to "a", "abc def" should be selected. Also the initially selected word "def" in step 3 should always stay selected after step 3, regardless of the touch point position .

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This change fixes an issue where on a long-press the selection would only expand correctly in one direction. 

This was due to always using the `firstWord.base.offset` as the new selection base offset and `lastWord.extent.offset` as the new extent offset. 

This is an issue because say we have `abc def ghi`, and we long press `def` and drag to `ghi`. Here the first word is `def` and the last word is `ghi`. With the previous logic the new base would be at position 4 (the firstWord.base.offset) and the new extent would be at position 11 (the lastWord.extent.offset). If we want to drag backwards and move our drag to `abc`, the first word will be `def` and the last word will be `abc`. The new base will be at position 4 (firstWord.base.offset), and the new extent will be at position 3 (lastWord.extent.offset). This means the whitespace between the `abc` and `def` will be selected, when the expected selection is `abc def`.

When the last word comes before the first word we want the base to start at the end of the first word, and extend to the beginning of the last word.

Before | After
---|---
Screen Recording 2022-10-10 at 11 53 56 AM|Screen Recording 2022-10-10 at 11 53 03 AM

Fixes #32339

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -2078,12 +2078,27 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
...
+    } else {
+      newSelectionBase = isFirstWordBeforeLast ? firstWord.base.offset : firstWord.extent.offset;
+      newSelectionExtent = isFirstWordBeforeLast ? lastWord.extent.offset : lastWord.base.offset;
+    }
+
     _setSelection(
       TextSelection(
-        baseOffset: firstWord.base.offset,
-        extentOffset: lastWord.extent.offset,
+        baseOffset: newSelectionBase,
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/rendering/editable.dart:2100]: We should probably deprecate this method in the future, but could you add to the documentation that this method selects words that intersect the positions, and the words don't have to be strictly inside of the range?

File: packages/flutter/lib/src/rendering/editable.dart [hunk 2]
```diff
@@ -2078,12 +2078,27 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
     _computeTextMetricsIfNeeded();
     final TextPosition firstPosition = _textPainter.getPositionForOffset(globalToLocal(from - _paintOffset));
     final TextSelection firstWord = _getWordAtOffset(firstPosition);
-    final TextSelection lastWord = to == null ?
-      firstWord : _getWordAtOffset(_textPainter.getPositionForOffset(globalToLocal(to - _paintOffset)));
+    final TextPosition lastPosition = to == null ? firstPosition : _textPainter.getPositionForOffset(globalToLocal(to - _paintOffset));
+    final TextSelection lastWord = lastPosition == firstPosition ? firstWord : _getWordAtOffset(lastPosition);
+
+    final bool isFirstWordBeforeLast = firstPosition.offset < lastPosition.offset;
+    final bool firstWordIsLast = firstWord == lastWord;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/rendering/editable.dart:2085]: nit: probably don't need this?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:2085]: also consider renaming first -> from, last -> to, to match the names of the args.

**Review by LongCatIsLooong — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/rendering/editable.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/editable.dart:2085]: Do you mean the conditionals can just be in line?

```dart
if (fromWord == toWord) {
    
} else if (fromPosition .offset < toPosition.offset) {

}
```

File: packages/flutter/lib/src/rendering/editable.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/editable.dart:2100]: Yeah I agree, I will look into doing this for my text selection gestures project. And yes I’ll add the documentation.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:2085]: I meant `firstWord.start > lastWord.end ? (firstWord.end, lastWord.start) : (firstWord.start, lastWord.end)`. Didn't notice you were comparing `firstPosition` and `lastPosition`.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/editable.dart:2085]: Still a little confused.

For `also consider renaming first -> from, last -> to, to match the names of the args.` Did you mean change `firstPosition` -> `fromPosition`, `lastPosition` -> `toPosition` or change `firstWord` -> `fromWord`, `lastWord` -> `toWord`?

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/editable.dart:2085]: Also what line where you referring to for `nit: probably don't need this?`.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:2085]: I meant a `s/first/from/` etc. first/last are a bit ambiguous since it's unclear what order it's referring to.

 > Also what line where you referring to for nit: probably don't need this?

Special casing `firstWordIsLast` can be avoided I think. But it's not a big deal.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/editable.dart:2085]: I think it could as well but some tests were failing because without it the case always default to false if `from == to` which means the `firstWord.extent.offset` will be the base and `lastWord.base.offset` will be the extent. I think i'll leave it for now to keep those tests happy.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart]: Are you comparing `fromPositoin.offset` and `toPosition.offset`? firstWord.start > lastWord.end ? (firstWord.end, lastWord.start) : (firstWord.start, lastWord.end) should work?

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/editable.dart]: Ahh you're right that worked and cleans up the code a bit. Thanks!

File: packages/flutter/lib/src/rendering/editable.dart [hunk 3]
```diff
@@ -2066,7 +2066,8 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
     selectWordsInRange(from: _lastTapDownPosition!, cause: cause);
   }
 
-  /// Selects the set words of a paragraph in a given range of global positions.
+  /// Selects the set words of a paragraph that intersect a given range of global positions.
+  /// The set of words selected are not strictly bounded by the range of global positions.
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:2070]: The first paragraph should be once sentence per the styleguide.  Maybe just add an empty line of `///` between these two.

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 4]
```diff
@@ -3384,10 +3384,84 @@ void main() {
...
+            child: Center(
+              child: SelectableText('Atwater Peel Sherbrooke Bonaventure'),
+            ),
+          ),
+        ),
+      );
 
       final TestGesture gesture =
-      await tester.startGesture(selectableTextStart + const Offset(50.0, 5.0));
+          await tester.startGesture(textOffsetToPosition(tester, 18));
```
Comment (justinmc) [inline packages/flutter/test/widgets/selectable_text_test.dart:3464]: 👍

**Review by justinmc — APPROVED** [review]
LGTM 👍 with one docs nit.

**Review by LongCatIsLooong — APPROVED** [review]
