### PR TITLE
[flutter_conductor] ensure release branch point is always tagged

### LINKED ISSUE #92809: beta releases should always ensure the branch point between the release and master is tagged
I think something seems to have gone wrong with beta (channel) branch, I did this just now as I was seeing same thing with my local fvm managed install and with clean install from git, `beta` is for some reason labeled as `2.7` while master is `2.6` ?

cc @christopherfujino 

```
git clone https://github.com/flutter/flutter.git -b beta
Cloning into 'flutter'...
...

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.7.0-3.1.pre, on Ubuntu 21.04 5.11.0-38-generic, locale en_AU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code
[✓] Connected device (2 available)

• No issues found!
~/temp/flutter $ flutter channel master
Switching to flutter channel 'master'...
git: Already on 'master'
git: Your branch is up to date with 'origin/master'.
Successfully switched to flutter channel 'master'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
beta  ~/temp/flutter $ flutter upgrade
Flutter is already up to date on channel master
Flutter 2.6.0-12.0.pre.535 • channel master • https://github.com/flutter/flutter.git
Framework • revision 04156b6636 (2 days ago) • 2021-10-29 18:29:31 -0700
Engine • revision 3a0a63c2d2
Tools • Dart 2.15.0 (build 2.15.0-262.0.dev)
```

and just to be sure back again to beta:
```
flutter channel beta
Switching to flutter channel 'beta'...
git: Switched to a new branch 'beta'
git: Branch 'beta' set up to track remote branch 'beta' from 'origin'.
Successfully switched to flutter channel 'beta'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
beta  ~/temp/flutter $ flutter upgrade
Downloading Dart SDK from Flutter engine a75e3b80f9c1ffb30bbe736c5a42e4a815a79197...
 ...
Building flutter tool...
Flutter is already up to date on channel beta
Flutter 2.7.0-3.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision fc7015e35a (4 days ago) • 2021-10-27 15:18:41 -0700
Engine • revision a75e3b80f9
Tools • Dart 2.15.0 (build 2.15.0-178.1.beta)
```

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/92809

### CODE REVIEW

File: dev/conductor/core/lib/src/globals.dart [hunk 1]
```diff
@@ -8,6 +8,8 @@ import 'proto/conductor_state.pb.dart' as pb;
 
 const String gsutilBinary = 'gsutil.py';
 
+const String kFrameworkDefaultBranch = 'master';
```
Comment (godofredoc) [inline dev/conductor/core/lib/src/globals.dart:11]: How will this be handled when engine moves to main?

Comment (christopherfujino) [reply dev/conductor/core/lib/src/globals.dart:11]: This only relevant on the framework, as we only apply tags to the framework.

**Review by godofredoc — APPROVED** [review]
