### PR TITLE
Fix `Action.overridable` example

### LINKED ISSUE #97397: The Action.overridable dartpad example fails to run
The DartPad example on this page in the docs gives the error "Error compiling to JavaScript". https://master-api.flutter.dev/flutter/widgets/Action/Action.overridable.html

CC @LongCatIsLooong

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/97397

Changed to a different example since text input shortcuts don't work on web.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/actions.dart [hunk 1]
```diff
@@ -145,12 +145,16 @@ abstract class Action<T extends Intent> with Diagnosticable {
...
-  /// This sample implements a custom text input field that handles the
-  /// [DeleteCharacterIntent] intent, as well as a US telephone number input
-  /// widget that consists of multiple text fields for area code, prefix and line
-  /// number. When the backspace key is pressed, the phone number input widget
-  /// sends the focus to the preceding text field when the currently focused
-  /// field becomes empty.
+  /// This sample shows how to implement a rudimentary `CopyableText` widget
+  /// that responds to Ctrl-C by copying its own content to the clipboard.
+  ///
+  /// if `CopyableText` is to be provided in a package, developers use the
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/actions.dart:151]:
```suggestion
  /// if `CopyableText` is to be provided in a package, developers using the
```

File: packages/flutter/lib/src/widgets/actions.dart [hunk 2]
```diff
@@ -145,12 +145,16 @@ abstract class Action<T extends Intent> with Diagnosticable {
...
+  /// widget may want to change how copying is handled. As the author of the
+  /// package, you can enable that by making the corresponding [Action]
+  /// overridable. In the second part of the code sample, three `CopyableText`
+  /// widgets are used to build a verification code widget which overrides the
+  /// "copy" action to copying the combined numbers from all 3 `CopyableText`
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/actions.dart:156]:
```suggestion
  /// "copy" action by copying the combined numbers from all three `CopyableText`
```

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d
