### PR TITLE
[web] Use defensive null check in text editing placeElement

### LINKED ISSUE #178619: Null check operator used on a null value
### Steps to reproduce

It is unclear where (in our code) this is comming from, I think it's usually only on the web version of our app.

The error is being logged by the Uncaught Error handler.  it's been happening since 3.35 I belive.

```
Null check operator used on a null value↵
TypeError: Cannot read properties of null (reading 'focus')↵
    at GloballyPositionedTextEditingStrategy.placeElement$0 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:226791:26)↵
    at GloballyPositionedTextEditingStrategy.updateElementPlacement$1 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:226979:17)↵
    at TextInputSetEditableSizeAndTransform.run$1 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:227503:34)↵
    at TextEditingChannel.handleTextInput$2 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:227617:15)↵
    at EnginePlatformDispatcher._sendPlatformMessage$3 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:219777:47)↵
    at _DefaultBinaryMessenger.send$2 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:595508:51)↵
    at https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:596756:54↵
    at _wrapJsFunctionForAsync_closure.$protected (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:12123:15)↵
    at _wrapJsFunctionForAsync_closure.call$2 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:237656:12)↵
    at Object._asyncStartSync (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:12087:20)

```
### Expected results

Code should not be using the ! operator with out checking...

### Actual results

These null check errors are randomly showing up in our application logs.

### Code sample

Since I don't know where this is even coming from I can't provide a stripped down example.
But hopefully given the relatively readable stack track you can tell where the unchecked .focus! is.
I have not seen any strange behaviour in our app nor do I even know how to make this error happen within our app.  I just see the error in our logs. 

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Null check operator used on a null value↵
TypeError: Cannot read properties of null (reading 'focus')↵
    at GloballyPositionedTextEditingStrategy.placeElement$0 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:226791:26)↵
    at GloballyPositionedTextEditingStrategy.updateElementPlacement$1 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:226979:17)↵
    at TextInputSetEditableSizeAndTransform.run$1 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:227503:34)↵
    at TextEditingChannel.handleTextInput$2 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:227617:15)↵
    at EnginePlatformDispatcher._sendPlatformMessage$3 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:219777:47)↵
    at _DefaultBinaryMessenger.send$2 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:595508:51)↵
    at https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:596756:54↵
    at _wrapJsFunctionForAsync_closure.$protected (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:12123:15)↵
    at _wrapJsFunctionForAsync_closure.call$2 (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:237656:12)↵
    at Object._asyncStartSync (https://aio.lochbox.app/vL8CUKhWmHM9gmT64gRAdQ.js.gz:12087:20)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.38.1, on Fedora Linux 42 (Adams) 6.16.12-200.fc42.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.1.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by flutter-zl**
Fixes #178619

Uses defensive null check (?.) instead of null assertion (!) when calling focusWithoutScroll() on focusedFormElement in GloballyPositionedTextEditingStrategy.placeElement().

This prevents a crash that can occur due to a race condition where hasAutofillGroup returns true but focusedFormElement is null by the time it's accessed.

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart [hunk 1]
```diff
@@ -1176,7 +1176,7 @@ class GloballyPositionedTextEditingStrategy extends DefaultTextEditingStrategy {
       // only after placing it to the correct position. Hence autofill menu
       // does not appear on top-left of the page.
       // Refocus on the elements after applying the geometry.
-      focusedFormElement!.focusWithoutScroll();
+      focusedFormElement?.focusWithoutScroll();
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart:1183]: I'm concerned this may be putting a band-aid on the real issue. When `hasAutofillGroup` is true, the expectation is that `focusedFormElement` is always a real value.

@gemini-code-assist any idea why `focusedFormElement` would be null here some times?

Comment (flutter-zl) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart:1183]: I have added a comment explaining the re-entrancy issue.
1. placeElement() checks hasAutofillGroup → true
2. placeForm() does DOM operations (insertBefore, etc.)
3. DOM ops trigger synchronous event handlers that process a pending TextInput.updateConfig
4. applyConfiguration() replaces inputConfiguration with a config where autofillGroup = null
5. Back in placeElement(), focusedFormElement is now null → crash

**Review by mdebbar — APPROVED** [review]
LGTM!
