### PR TITLE
fix DropdownMenu overflow

### LINKED ISSUE #147173: `DropdownMenu` overflow with large helper text
### Steps to reproduce

Use DropdownMenu with large helper text.
The size and helper text which causes helper text to crop is tricky and need magic number

### Expected results

input region ("hint text") should be able to tapped to select. 
helper text should not be cropped.

### Actual results

input region cannot be able to tapped to select. 
text is cropped

### Code sample

<details open><summary>Code sample</summary>

```dart
import "package:flutter/material.dart";
  
void main() => runApp(const MyMenuApp());


class MyMenuApp extends StatelessWidget {
  const MyMenuApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: SizedBox(
          width: 327,
          height: 658,
          child: Center(
            child: Container(
              color: Colors.purple,
              child: DropdownMenu<int>(
                hintText: 'Hint text',
                helperText: 'This is a long helper text that need 3 lines',
                inputDecorationTheme: InputDecorationTheme(
                    helperMaxLines: 3, helperStyle: TextStyle(fontSize: 30)),
                dropdownMenuEntries: <DropdownMenuEntry<int>>[
                  DropdownMenuEntry<int>(
                    value: 0,
                    label: 'MenuEntry Item 1',
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
Screenshot 2024-04-23 at 2 23 52 AM

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.22.0-14.0.pre.67, on macOS 14.4 23E214 darwin-arm64, locale en-AU)
    • Flutter version 3.22.0-14.0.pre.67 on channel master at /Users/mainj/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1a905d508d (30 hours ago), 2024-04-21 06:44:23 -0400
    • Engine revision 75ca2195c9
    • Dart version 3.5.0 (build 3.5.0-83.0.dev)
    • DevTools version 2.35.0-dev.8
....
```

</details>

### PR DESCRIPTION
**Pull request by PurplePolyhedron**
fix `DropdownMenu` overflow issue in  https://github.com/flutter/flutter/issues/147076 and https://github.com/flutter/flutter/issues/147173
However I believe the the menu placement issue in https://github.com/flutter/flutter/issues/147076 is a separate issue. It is not fixed here.

fixes https://github.com/flutter/flutter/issues/147173

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 1]
```diff
@@ -2129,6 +2129,59 @@ void main() {
...
+            ],
+          ),
+        ),
+      ),
+    ));
+
+  await tester.pump();
+  await tester.tapAt(tester.getCenter(find.text('Hint text')));
+  await tester.pumpAndSettle();
+  expect(find.byType(MenuItemButton), findsNWidgets(2));
```
Comment (bleroux) [inline packages/flutter/test/material/dropdown_menu_test.dart:2183]:
```suggestion
    // One is layout for the _DropdownMenuBody, the other one is the real button item in the menu.
    expect(find.widgetWithText(MenuItemButton, label), findsNWidgets(2));
```
Consider reusing a comment seen in another test from this file which clarifies why we are looking for two occurrences. Also consider relying on `find.widgetWithText` for a more precise finder (doing so the menu item label is repeated so introducing a const for the label would be great).

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 2]
```diff
@@ -2129,6 +2129,59 @@ void main() {
...
+
+    await tester.pump();
+    final RenderBox box = tester.firstRenderObject(find.byType(TextField));
+    expect(box.size.width, 300.0);
+  });
+
+  // This is a regression test for https://github.com/flutter/flutter/issues/147173.
+  testWidgets('Text field with large helper text can be selected', (WidgetTester tester) async {
+    await tester.pumpWidget(
+     const MaterialApp(
```
Comment (bleroux) [inline packages/flutter/test/material/dropdown_menu_test.dart:2159]:
```suggestion
    await tester.pumpWidget(const MaterialApp(
```
Similarly to the other tests in this file.

**Review by bleroux — COMMENTED** [review]
Thanks for this PR!
Just some minor comments to address.

File: packages/flutter/test/material/dropdown_menu_test.dart (hunk 2 above)
Comment (PurplePolyhedron) [reply packages/flutter/test/material/dropdown_menu_test.dart]: Thanks for the suggestion. I've fixed the above issues.

**Review by QuncCccccc — APPROVED** [review]
LGTM! Thanks a lot for the fix!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
