### PR TITLE
Horizontally expand text selection toolbar buttons in overflow menu

### LINKED ISSUE #144089: Items in the overflow of the TextSelectionToolbar should take the width of the largest item
### Steps to reproduce

1. create a Material style ```TextSelectionToolbar``` with ```contextMenuBuilder``` of a ```TextField```, ```TextFormField``` or similar
2. make the context menu items overflow to show the overflow button
2.1. if you are in DartPad and the menu does not overflow, you can drag the vertical divider between the code and the display to make the display smaller.
2.2. similarly, you can add more ContextMenuButtonItems to the Toolbar to make it wider
4. open the overflow menu

### Expected results

All items in the overflow menu should have the width of the largest item

### Actual results

All items have their own minimal width resulting in a non-clickable area beside them

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();

    if (kIsWeb) {
      BrowserContextMenu.disableContextMenu();
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextFormField(
            initialValue: "Example Text",
            contextMenuBuilder: (context, editableTextState) {
              final anchors = editableTextState.contextMenuAnchors;
              final buttonItems = [
                ContextMenuButtonItem(label: "More items", onPressed: () {}),
                ContextMenuButtonItem(label: "To make the menu", onPressed: () {}),
                ContextMenuButtonItem(label: "Overflow", onPressed: () {}),
                ...editableTextState.contextMenuButtonItems,
                ContextMenuButtonItem(label: "Long example menu item", onPressed: () {}),
                ContextMenuButtonItem(label: "Short", onPressed: () {}),
              ];

              // Follwing is the code that AdaptiveTextSelectionToolbar uses when the platform is android.
              // I copied it to force the material style toolbar

              final List<Widget> buttons = <Widget>[];
              for (int i = 0; i < buttonItems.length; i++) {
                final ContextMenuButtonItem buttonItem = buttonItems[i];
                buttons.add(TextSelectionToolbarTextButton(
                  padding: TextSelectionToolbarTextButton.getPadding(
                      i, buttonItems.length),
                  onPressed: buttonItem.onPressed,
                  child: Text(AdaptiveTextSelectionToolbar.getButtonLabel(
                      context, buttonItem)),
                ));
              }

              return TextSelectionToolbar(
                anchorAbove: anchors.primaryAnchor,
                anchorBelow: anchors.secondaryAnchor == null
                    ? anchors.primaryAnchor
                    : anchors.secondaryAnchor!,
                children: buttons,
              );
            },
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

grafik
The buttons  with shorter text do not take the full width, resulting in a non-clickable area on their right hand side

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>
none

The example code was executed in DartPad with Dart 3.3.0 and Flutter 3.19.0 on the Stable channel

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR expands the items displayed in the overflow menu of a `TextSelectionToolbar` making buttons clickable in the blank area.

| Before | After |
|--------|--------|
| Each item has its own width | All items expand horizontally |
|  Capture d’écran 2024-02-29 à 14 43 57 | Capture d’écran 2024-02-29 à 14 40 47 | 

## Related Issue

Fixes https://github.com/flutter/flutter/issues/144089.

## Tests

Adds 1 tests.

### CODE REVIEW

File: packages/flutter/lib/src/material/text_selection_toolbar.dart [hunk 1]
```diff
@@ -539,10 +540,8 @@ class _RenderTextSelectionToolbarItemsLayout extends RenderBox with ContainerRen
       } else {
         childParentData.offset = Offset(0.0, overflowHeight);
         overflowHeight += child.size.height;
-        nextSize = Size(
-          math.max(child.size.width, nextSize.width),
-          overflowHeight,
-        );
+        overflowWidth = math.max(child.size.width, nextSize.width);
+        nextSize = Size(overflowWidth, overflowHeight);
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection_toolbar.dart:544]: Is the introduction of overflowWidth just an attempt to make this easier to read, or am I misreading this? I think you can declare it here rather than up above, right?

File: packages/flutter/lib/src/material/text_selection_toolbar.dart [hunk 2]
```diff
@@ -569,6 +568,38 @@ class _RenderTextSelectionToolbarItemsLayout extends RenderBox with ContainerRen
     size = nextSize;
   }
 
+  // Horizontally expand the children when the menu overflow so they can react to
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection_toolbar.dart:571]: "overflow" => "overflows"

File: packages/flutter/lib/src/material/text_selection_toolbar.dart [hunk 3]
```diff
@@ -569,6 +568,38 @@ class _RenderTextSelectionToolbarItemsLayout extends RenderBox with ContainerRen
...
+  // pointer events into their whole area.
+  void _resizeChildrenWhenOverflow() {
+    if (overflowOpen) {
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_selection_toolbar.dart:574]: Nit: Maybe it's more clear as:

```dart
if (!overflowOpen) {
  return;
}
```

**Review by justinmc — APPROVED** [review]
LGTM with nits :+1: 

Thanks for fixing this! Much better this way.

File: packages/flutter/lib/src/material/text_selection_toolbar.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/text_selection_toolbar.dart:544]: Oh good catch: I first introduced it because I need it at the end of this method and after moving the logic to a separate method I kept it for readability. I will move the declaration as suggested, thanks.

Comment (bleroux) [reply packages/flutter/lib/src/material/text_selection_toolbar.dart]: Just push an update and finally I removed this variable as it does not improve readability.
