### PR TITLE
Fix `ReorderableList` proxy animation for partial drag-back

### LINKED ISSUE #88331: Visual bug on the last two items of a ReorderableListView
## Steps to Reproduce

File below includes the main dart file example:
[main.zip](https://github.com/flutter/flutter/files/6997000/main.zip)

1. Create any ReorderableListView with or without .builder(), and with any settings you want (this appears to be repeatable with any parameters or settings)
2. add 2 or more items to the list
3. go to the end of the list, hold and drag the second last item in the list
4. pull the item over the last item in the list, and then bring the item you're holding back to its original position, second last
5. Make sure you're not dragging and dropping the second last item into the last position, you're just hovering the second last item over the last item and then back again

**Expected results:** 
I expected the item I'm dragging to go back into place where I originally held and dragged it from after I dropped it back in its original position

**Actual results:** 
When you drop the item back where you originally dragged it from, the item decides to try and drop in the last position, and then snaps back to its original position

This is actually repeatable without running any code on your machine at all, you can do the same steps above with the example within the Flutter docs:
https://api.flutter.dev/flutter/material/ReorderableListView-class.html

<details>
  <summary>Logs</summary>

flutter run --verbose
```
[  +40 ms] executing: uname -m
[  +19 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +3 ms] executing: [/home/inno/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] 0f465e5b2a3ed2431321b490a614c3d15089854c
[        ] executing: [/home/inno/snap/flutter/common/flutter/] git tag
--points-at 0f465e5b2a3ed2431321b490a614c3d15089854c
[   +7 ms] Exit code 0 from: git tag --points-at
0f465e5b2a3ed2431321b490a614c3d15089854c
[        ] 2.5.0-5.0.pre
[   +6 ms] executing: [/home/inno/snap/flutter/common/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/inno/snap/flutter/common/flutter/] git ls-remote
--get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +50 ms] executing: [/home/inno/snap/flutter/common/flutter/] git rev-parse
--abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +33 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +38 ms] executing: /home/inno/Android/Sdk/platform-tools/adb devices -l
[  +22 ms] List of devices attached
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +41 ms] Multiple devices found:
[  +75 ms] Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.2 LTS
5.11.0-25-generic
[   +1 ms] Chrome (web)    • chrome • web-javascript • Google Chrome
92.0.4515.131
[   +1 ms] [1]: Linux (linux)
[        ] [2]: Chrome (chrome)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 

```

flutter analyze
```
Analyzing bug...                                                        
No issues found! (ran in 0.8s)

```

flutter doctor -v

```
[✓] Flutter (Channel dev, 2.5.0-5.0.pre, on Ubuntu 20.04.2 LTS
    5.11.0-25-generic, locale en_AU.UTF-8)
    • Flutter version 2.5.0-5.0.pre at /home/inno/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0f465e5b2a (12 days ago), 2021-08-04 18:59:50 -0400
    • Engine revision a0d89b1a54
    • Dart version 2.14.0 (build 2.14.0-377.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/inno/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio
    • Android Studio at /home/inno/Local_Code/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ android-studio-dir = /home/inno/Local_Code/android-studio
    ✗ Android Studio not found at /home/inno/Local_Code/android-studio
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.2 LTS
      5.11.0-25-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

```

</details>

### LINKED ISSUE #90856: ReorderableListView Weird Behaviour on reordering the second last child
## Steps to Reproduce

1. Run this Code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> items = List.generate(5, (index) => 'Tile $index');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: ReorderableListView.builder(
            buildDefaultDragHandles: false,
            itemBuilder: (context, index) {
              return ListTile(
                trailing: ReorderableDragStartListener(
                  index: index,
                  child: const Icon(Icons.drag_indicator),
                ),
                key: Key('$index'),
                title: Text(items[index]),
              );
            },
            itemCount: items.length,
            onReorder: (int oldIndex, int newIndex) {
              setState(() {
                if (oldIndex < newIndex) {
                  newIndex -= 1;
                }
                final item = items.removeAt(oldIndex);
                items.insert(newIndex, item);
              });
            }));
  }
}
```

**Expected results:** 
It should behave like all the children.

**Actual results:** 

https://user-images.githubusercontent.com/77046231/135039306-1868b4b8-41dc-4f93-990c-51ddedfe9309.mp4

The Issue is not platform-specific.

<details>

```
Analyzing reorderablelistview_bug...                                    
No issues found! (ran in 1.5s)
```

```
[✓] Flutter (Channel stable, 2.5.0, on Ubuntu 21.04 5.11.0-16-generic, locale en_IN)
    • Flutter version 2.5.0 at /home/mayank/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mayank/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 21.04 5.11.0-16-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>

### LINKED ISSUE #150843: ReorderableList - incorrect newIndex when dragging an item down and returning it to its original position
### Steps to reproduce

dragging an item down and without releasing return it to its original position

### Expected results

The item should return to its original position without a jump. with smooth animation 
see video below 

### Actual results

Since when returning to the original position the newIndex is not equal to the start index, it equals startIndex + 1, which leads to a jump in the animation.

### Code sample

code sample from https://api.flutter.dev/flutter/material/ReorderableListView-class.html
<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [ReorderableListView].

void main() => runApp(const ReorderableApp());

class ReorderableApp extends StatelessWidget {
  const ReorderableApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('ReorderableListView Sample')),
        body: const ReorderableExample(),
      ),
    );
  }
}

class ReorderableExample extends StatefulWidget {
  const ReorderableExample({super.key});

  @override
  State<ReorderableExample> createState() => _ReorderableListViewExampleState();
}

class _ReorderableListViewExampleState extends State<ReorderableExample> {
  final List<int> _items = List<int>.generate(50, (int index) => index);

  @override
  Widget build(BuildContext context) {
    final ColorScheme colorScheme = Theme.of(context).colorScheme;
    final Color oddItemColor = colorScheme.primary.withOpacity(0.05);
    final Color evenItemColor = colorScheme.primary.withOpacity(0.15);

    return ReorderableListView(
      padding: const EdgeInsets.symmetric(horizontal: 40),
      children: <Widget>[
        for (int index = 0; index < _items.length; index += 1)
          ListTile(
            key: Key('$index'),
            tileColor: _items[index].isOdd ? oddItemColor : evenItemColor,
            title: Text('Item ${_items[index]}'),
          ),
      ],
      onReorder: (int oldIndex, int newIndex) {
        setState(() {
          if (oldIndex < newIndex) {
            newIndex -= 1;
          }
          final int item = _items.removeAt(oldIndex);
          _items.insert(newIndex, item);
        });
      },
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
Actual result

https://github.com/flutter/flutter/assets/23139753/aa24a740-5552-4e8d-9fbe-ef596ee28987

 
Expected

https://github.com/flutter/flutter/assets/23139753/c768b4e7-6efc-4d6b-b55f-e7c3e5dc1b25

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale ru-UZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.90.0)
[✓] Connected device (5 available)
[✓] Network resources
```

</details>

### PR DESCRIPTION
**Pull request by lukemmtt**
_**Note:** Alongside this PR, I've also prepared [another PR](https://github.com/flutter/flutter/pull/172882) with an alternative solution involving a more substantial refactor that addresses the root cause, rather than adding more conditional logic._

## Description

This PR fixes the proxy animation bug where dragging a `ReorderableList` item downward and then back to its original position causes it to animate to the wrong location (one position too low).

## The Problem

When dragging a `ReorderableList` item downward and then back to its original position, the proxy widget briefly animates to the wrong location (one position too low) before snapping to the correct spot.

**Reproduction**: Drag any item down past at least one other item, then drag it back to where it started.

<p align="center">
  demo2
</p>

## Root Cause

This bug is specific to dragging an item down and then bringing it back up to nearly (but not 100% of the way ) to its original position:

1. When the item approaches its original position **from below**, `_insertIndex` becomes `item.index + 1`
    - This happens because Flutter's `ReorderableList` calculates `_insertIndex` with the dragged item still present in the list (see #24786)
2. The proxy _should_ animate to the item's original position at `item.index`
    - _But the proxy actually animates one position too low._
    - This happens because `_dragEnd` incorrectly calculates 
    `_finalDropPosition = _itemOffsetAt(_insertIndex! - 1) +
  _extentOffset(...)`
    - The `_extentOffset(...)` addition, designed for items dropping _between other items_, shifts the position down by one item's height
    - The correct calculation for "returning home from below" should be just `_itemOffsetAt(_insertIndex! - 1)`

Note that this only occurs when returning from below (`_insertIndex > item.index`). Dragging upward (in a vertical list for example) or doesn't trigger this bug.

## Existing Implementation

The existing `_dragEnd` method in `reorderable_list.dart`:

```dart
void _dragEnd(_DragInfo item) {
  setState(() {
    if (_insertIndex == item.index) {
      _finalDropPosition = _itemOffsetAt(_insertIndex!);
    } else if (_reverse) {
      if (_insertIndex! >= _items.length) {
        _finalDropPosition =
            _itemOffsetAt(_items.length - 1) - _extentOffset(item.itemExtent, _scrollDirection);
      } else {
        _finalDropPosition =
            _itemOffsetAt(_insertIndex!) +
            _extentOffset(_itemExtentAt(_insertIndex!), _scrollDirection);
      }
    } else {
      if (_insertIndex! == 0) {
        _finalDropPosition = _itemOffsetAt(0) - 
          _extentOffset(item.itemExtent, _scrollDirection);
      } else {
        _finalDropPosition = _itemOffsetAt(_insertIndex! - 1) +
          _extentOffset(_itemExtentAt(_insertIndex! - 1), _scrollDirection);
      }
    }
  });
}
```

When returning from below, the code falls through to the final else block, which incorrectly adds `_extentOffset`.

## Fix

Detect when `_insertIndex - item.index == 1` (indicating a return to original position from below) and animate to the correct position.

```dart
if (_insertIndex! - item.index == 1) {
  // Drop at the original position when item returns from below
  _finalDropPosition = _itemOffsetAt(_insertIndex! - 1);
}
```

This fix was proposed by @frankpape in https://github.com/flutter/flutter/issues/90856#issuecomment-2599368939; I've merely validated and researched the background of why the fix works, and supported it with tests. 

**_Demo of the fixed implementation:_**
<p align="center">
  fixed
</p>

Fixes #88331
Fixes #90856
Fixes #150843

## A note about a previous PR: 

While investigating this issue, I found a PR addressing what seemed to be [the same exact issue](https://github.com/flutter/flutter/issues/150843): PR #151026; it turns out that that PR solved a _portion_ of the edge case: the case where an item is dragged down and back and slightly **overshoots** its original position when being dragged back & dropped—but that PR did not account for the presence of this bug when the dragged item slightly **undershoots** its original position on the return drag. This new PR effectively addresses the 'undershooting' case.

With this, I've added a new pair of regression tests that are identical to the [previous PR's tests](https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/reorderable_list_test.dart#L734), except for the fact that they simulate an undershoot on the return trip (90% of the way back instead of 110% like the original tests). This definitively captures the issue, failing in the master branch and passing in this PR's branch.

Here is the specific case resolved by the [**old** PR](https://github.com/flutter/flutter/pull/151026):
<table>
  <tr>
    <td align="center">
      Before<br>
      <sub>Before</sub>
    </td>
    <td align="center">
      After<br>
      <sub>After</sub>
    </td>
  </tr>
</table>

Here is the additional case resolved by **this** PR:
<table>
  <tr>
    <td align="center">
      Before<br>
      <sub>Before</sub>
    </td>
    <td align="center">
      After<br>
      <sub>After</sub>
    </td>
  </tr>
</table>

Two final observations worth noting:
- The fix proposed in this PR seems to **supersede** the previous PR's solution; it addresses both cases (overshooting and undershooting) even in my tests with the [original PR's changes ](https://github.com/flutter/flutter/pull/151026/files#diff-23a4bb073009d89f09084bdf5f85232de135b8f11be625e6312bb85900a90e67) reverted. Probably best to keep the old PR's code anyway to be conservative, but noteworthy.
- I also found it notable that neither this PR nor the older PR fix any issue with "reversed lists", which, in my tests, are simply not subject to this edge case as we've defined it. The regression tests added for the reverse case are thus purely precautionary.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hey @lukemmtt! Welcome. Thank you for contributing. Rather than an integration test, this should be easier to test with a simple unit test in `packages/flutter/test/widgets/reorderable_list_test.dart` 
Can you update to test this there? I think most of CI is failing since the changes here are not quite right for setting up a new integration test, but reverting and adding a unit test should resolve those. :)

**Comment by lukemmtt** [comment]
> Hey @lukemmtt! Welcome. Thank you for contributing. Rather than an integration test, this should be easier to test with a simple unit test in `packages/flutter/test/widgets/reorderable_list_test.dart` Can you update to test this there? I think most of CI is failing since the changes here are not quite right for setting up a new integration test, but reverting and adding a unit test should resolve those. :)

Thanks @Piinks for looking into this and for your reply!

I certainly agree that an integration test is a last resort, and I'm not surprised I set it up wrong (sorry 🥲!) but I'm afraid I was unable to create a comparable unit test despite hours of trying. The thing is, no matter what I tried, I could not manage to create a unit test that properly captured the direction of movement of the proxy as it was animating to its final position upon being released (which is the basis for the integration test). Every time I tried to 'observe' the animation during a unit test (even one frame later), I was finding that the proxy had already 'settled' into its final position, as if it wasn't animating at all. I asked AI models about it, and they just said that maybe the animation frames were being 'collapsed' in the unit test, which would make any "observing the movement of the proxy over time" an impossible task.

I'd love to be proven wrong, but I'm afraid I'm out of ideas. Open to any suggestions!

**Comment by Piinks** [comment]
Thanks for the update. Can you share some of the unit test code you tried to reproduce with? Its hard to say without it what might have been going on.

**Comment by lukemmtt** [comment]
@Piinks I scrapped it, but I trust that if you're asking, it must be possible, so I'll be glad to investigate the existing tests and and keep trying to figure it out. I appreciate the feedback!

**Comment by lukemmtt** [comment]
Hey @Piinks, some updates:

In looking through the [existing widget tests](https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/reorderable_list_test.dart) for `ReorderableList`, I was surprised to find one that sounded extremely similar to the condition I'm trying to test, called ["properly animates the drop at starting position"](https://github.com/flutter/flutter/blob/fdc1b5cd29f7223213548e501c03398568997a55/packages/flutter/test/widgets/reorderable_list_test.dart#L734), added in PR #151026, which was a fix for #150843, which, in its filing video, is shown to look like this:



...which looks strikingly similar to the issue in my own PR here. Perhaps that issue was subtly different in some way, or perhaps it simply regressed, but it certainly seems to persist in my own tests in the master branch, despite that PR being merged in December 2024 and [rolled into Flutter 3.27.0 the same month](https://docs.flutter.dev/release/release-notes/release-notes-3.27.0)).
- Moreover, that PR's [widget test](https://github.com/flutter/flutter/blob/fdc1b5cd29f7223213548e501c03398568997a55/packages/flutter/test/widgets/reorderable_list_test.dart#L734) seems to be adequate for reproducing this issue at a glance, so I'm curious as to why it's not failing today. This makes me wonder of the suitability of using a widget test or unit test to reliably protect against the regression of this issue.

All that is to say: I understand that we would like to avoid an integration test if at all possible, but I remain unsure of how to make that happen effectively. I remain eager to learn how I can do better here.

Thanks for your time and for any additional feedback!

**Comment by lukemmtt** [comment]
@Piinks I'm pleased to report that I figured out why this issue has persisted to this day, despite seemingly having been addressed last year in PR #151026; that PR solved a _portion_ of the issue. All is explained in detail in the revised PR description.

I appreciate you pointing me in the right direction with the widget/unit tests!

As for the remaining CI failure: are the failing Windows framework tests related to my code?

Thanks!

**Comment by lukemmtt** [comment]
@Piinks Looks like all CI checks are passing now 🙏🏻 I look forward to your thoughts, thank you!

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 1]
```diff
@@ -798,6 +800,76 @@ void main() {
...
+      final TestGesture drag = await tester.startGesture(tester.getCenter(find.text('item 2')));
+      await tester.pump(kPressTimeout);
+      await drag.moveBy(const Offset(0, 100));
+      await tester.pumpAndSettle();
+      await drag.moveBy(const Offset(0, -90));
+      await tester.pump();
+      expect(tester.getTopLeft(find.text('item 2')), const Offset(0, 310));
+      expect(tester.getTopLeft(find.text('item 1')), const Offset(0, 300));
+
+      // Now leave the drag, it should go to index 1.
```
[the remark this answers is not in the document]
Comment (Piinks) [reply packages/flutter/test/widgets/reorderable_list_test.dart:863]: I think G was off here.

[the remark this answers is not in the document]
Comment (Piinks) [reply packages/flutter/test/widgets/reorderable_list_test.dart:863]: To clarify - I think G is off here because it is confusing item 1 for index 1. :)

**Review by Piinks — APPROVED** [review]
LGTM, thank you!

**Comment by Piinks** [comment]
> Note: Alongside this PR, I've also prepared https://github.com/flutter/flutter/pull/172882 with an alternative solution involving a more substantial refactor that addresses the root cause, rather than adding more conditional logic.

LOL! I too was like, I feel like we keep adding conditional cases and was drafting a simpler flow over here. 😀 
Let's land this, and then maybe we can compare notes to refactor?

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 2]
```diff
@@ -798,6 +800,76 @@ void main() {
...
+      await tester.pump();
+
+      // It should animate back to the original position
+      await tester.pump(const Duration(milliseconds: 200));
+      expect(tester.getTopLeft(find.text('item 0')).dy, lessThan(10));
+    },
+  );
+
+  testWidgets(
+    'SliverReorderableList - properly animates the drop at starting position with reverse:true (undershoot)',
```
Comment (victorsanni) [inline packages/flutter/test/widgets/reorderable_list_test.dart:839]: This test passes on `master`, is this intended?

Comment (lukemmtt) [reply packages/flutter/test/widgets/reorderable_list_test.dart:839]: 😯 no that is not intended—I will double check this, thanks @victorsanni

Comment (lukemmtt) [reply packages/flutter/test/widgets/reorderable_list_test.dart:839]: @victorsanni: I tested this again and it seems to be working properly for me; this is my first time doing this so it's fully possible that I'm doing something wrong, but I don't know what that could be.

Specifically, after merging the latest master (`7920077a5d`, 2025-08-06 17:54:17) into my branch, I tested with both states by running this:

```bash
./bin/flutter test packages/flutter/test/widgets/reorderable_list_test.dart --name "undershoot"
```
 With the fix: All tests passed; Without the fix (reverted): Some tests failed

Is it possible that you accidentally ran the similar looking tests that don't have "undershoot" in their name? Those do pass on master. This PR adds two new "undershoot" tests that specifically test dragging an item down then back up 90%—these fail without the fix.

Let me know what you think, thanks for your review 🙏🏻

Comment (victorsanni) [reply packages/flutter/test/widgets/reorderable_list_test.dart:839]: Reconfirmed, the test passes even without the changes in the PR. To reproduce this, copy this test into a new branch and run it, it passes without the changes in the PR while the other one fails.

Without the fix, both tests should fail.

Comment (lukemmtt) [reply packages/flutter/test/widgets/reorderable_list_test.dart:839]: AH—I apologize deeply Victor—I misread your message before: I failed to realize you were referring to just **one** of the two tests—specifically the `reverse: true` case.

Your observation is correct, the reverse test passes in both `master` and in my branch. This is intentional.

I mentioned this in the PR description, although I admit this could have been emphasized more prominently. It's in the final section of the PR description that discusses an [earlier PR by another contributor](https://github.com/flutter/flutter/pull/151026) that only solved the issue partially:

> I also found it notable that neither this PR nor the older PR fix any issue with "reversed lists", which, in my tests, are simply not subject to this edge case as we've defined it. The regression tests added for the reverse case are thus purely precautionary.

Quite notably, in @Piinks' review of that original PR, I noticed that she requested that the reverse case be covered in the test as well [(comment)](https://github.com/flutter/flutter/pull/151026/files#r1735058079)—a pattern which I've followed for consistency, even though neither that original fix nor my new fix (nor their accompanying tests) actually fix/verify any behavior with respect to the `reverse: true` case.

Again, I apologize for not reading your comment more closely. I value your time and appreciate your review.

**Review by victorsanni — APPROVED** [review]
LGTM - thanks for the fix!
