### PR TITLE
Changing `TextPainter.getOffsetForCaret` implementation to remove the logarithmic search

### LINKED ISSUE #123424: Caret misplaced in bidi text
I don't have a repro recipe for this handy, but it's a bug I believe is there based on reading the code, and I'm filing the issue so I have something to link to in a comment.

The bug is the same as #122477, but limited to the case where there is some LTR text and also some RTL text near the cursor. Specifically:
* The algorithm we have for [TextPainter.getOffsetForCaret], in [TextPainter._getMetricsFromDownstream] and [TextPainter._getMetricsFromUpstream], takes exponentially longer and longer ranges of code units and asks SkParagraph for the text boxes contained in those ranges.

* Those boxes are returned in left-to-right order, not logical text order. (Thanks to @tgucio for [spotting this possibility](https://github.com/flutter/flutter/pull/122480#discussion_r1147301944).)

  Even the left-to-right order is only from empirical observation; we haven't pinned down an API guarantee of that, and haven't experimented carefully with what happens if e.g. the text on the right is higher than the text on the left.

* We then try to work out from that list of boxes which one is adjacent to the given offset — which one comes logically first (for _getMetricsFromDownstream) or last (for _getMetricsFromUpstream).

* If the boxes are all LTR, or all RTL, one can do that. (Provided our assumption that they're given in left-to-right order holds.)

  But if they're of different directions, I think there is not a way to do that reliably even in principle. For example if there's an LTR box to the left of an RTL box, either one could be the one that came first in the text.

Before #122480, our implementation effectively assumed RTL text. After #122480, it will work correctly for pure LTR text as well as for pure RTL text. But it will still not work for bidirectional text.

---

Like with #122477, in order to trigger this issue, one necessary ingredient is a grapheme cluster that's at least 3 code units long (specifically, it has to not be 1, 2, 4, 8, or another power of two code units long.) One way to do that is with a complex emoji, as in the #122477 recipe.

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
The behavior largely remains the same, except:

1. The EOT cursor `(textLength, downstream)` for text ending in the opposite writing direction as the paragraph is now placed at the visual end of the last line. 
  For example, in a LTR paragraph, the EOT cursor for `aA` (lowercase for LTR and uppercase for RTL) is placed to the right of the line: `aA|` (it was `a|A` before). 
  This matches the behavior of most applications that do logical order arrow key navigation instead of visual order navigation. 
  And it makes the navigation order consistent for `aA\naA`:
```
  |aA    =>  aA|  => aA|  => aA  => aA   => aA 
   aA        aA      aA     |aA     aA|     aA|     
   (1)       (2)     (3)    (4)    (5)      (6)
```
This is indeed still pretty confusing as (2) and (3), as well as (5) and (6) are hard to distinguish (when the I beam has a large width they are actually visually distinguishable -- they use the same anchor but one gets painted to the left and the other to the right. I noticed that emacs does the same). 
But logical order navigation will always be confusing in bidi text, in one way or another.

Interestingly there are 3 different behaviors I've observed in chrome:
- the chrome download dialog (which I think uses GTK text widgets but not sure which version) gives me 2 cursors when navigating bidi text, and 
- its HTML fields only show one, and presumably they place the I beam at the **trailing edge** of the character (which makes more sense for backspacing I guess). 
- On the other hand, its (new) omnibar seems to use visual order arrow navigation

Side note: we may need to update the "tap to place the caret here" logic to handle the case where the tap lands outside of the text and the text ends in the opposite writing direction. 

2. Removed the logarithmic search. The same could be done using the characters package but when glyphInfo tells you about the baseline location in the future we probably don't need the `getBoxesForRange` call. This should fix https://github.com/flutter/flutter/issues/123424.

## Internal Tests

This is going to change the image output of some internal golden tests. I'm planning to merge https://github.com/flutter/flutter/pull/143281 before this to avoid updating the same golden files twice for invalid selections.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jason-simmons — APPROVED** [review]

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 1]
```diff
@@ -203,8 +203,14 @@ class WordBoundary extends TextBoundary {
...
   static bool _isNewline(int codePoint) {
+    // Carriage Return is not treated as a hard line break.
     return switch (codePoint) {
-      0x000A || 0x0085 || 0x000B || 0x000C || 0x2028 || 0x2029 => true,
+      0x000A ||       // Line Feed
+      0x0085 ||       // New Line
+      0x000B ||       // Form Feed
+      0x000C ||       // Vertical Feed
+      0x2028 ||       // Line Separator
+      0x2029 => true, // Paragraph Separator
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/text_painter.dart:213]: Much better, thanks!

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 2]
```diff
@@ -315,6 +324,57 @@ class _TextLayout {
...
+  /// levels have opposite parities (which implies opposite writing directions),
+  /// this makes sure the caret is placed at the same "end" of the line as if the
+  /// line ended with a line feed.
+  late final _LineCaretMetrics _endOfTextCaretMetrics = _computeEndOfTextCaretAnchorOffset();
+  _LineCaretMetrics _computeEndOfTextCaretAnchorOffset() {
+    final int lastLineIndex = _paragraph.numberOfLines - 1;
+    assert(lastLineIndex >= 0);
+    final ui.LineMetrics lineMetrics = _paragraph.getLineMetricsAt(lastLineIndex)!;
+    // SkParagraph currently treats " " and "\t" as white spaces. Trailing white
+    // spaces don't contribute to the line width thus require special handling
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/text_painter.dart:346]: Should this say "and thus"?

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 3]
```diff
@@ -315,6 +324,57 @@ class _TextLayout {
...
+      0x9 ||        // horizontal tab
+      0x20 => true, // space
+      _ => false,
+    };
+
+    final double baseline = lineMetrics.baseline;
+    final double dx;
+    late final ui.GlyphInfo? lastGlyph = _paragraph.getGlyphInfoAt(rawString.length - 1);
+    // TODO(LongCatIsLooong): handle the case where maxLine is set to non-null
+    // and the last line ends with trailing whitespaces.
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/text_painter.dart:361]: Did you mean to handle this in this PR?

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 4]
```diff
@@ -419,39 +479,29 @@ class _TextPainterLayoutCacheWithOffset {
...
-final class _LineCaretMetrics implements _CaretMetrics {
-  const _LineCaretMetrics({required this.offset, required this.writingDirection, required this.fullHeight});
-  /// The offset of the top left corner of the caret from the top left
-  /// corner of the paragraph.
+/// The _CaretMetrics for carets located in a non-empty paragraph. Such carets
+/// are anchored to the trailing edge or the leading edge of a glyph, or a
+/// ligature component.
+final class _LineCaretMetrics {
+  const _LineCaretMetrics({required this.offset, required this.writingDirection});
+  /// The offset from the top left corner of the paragraph to the the caret's
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/text_painter.dart:491]: Duplicate "the".

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 5]
```diff
@@ -1432,38 +1363,136 @@ class TextPainter {
...
 
-  // Checks if the [position] and [caretPrototype] have changed from the cached
-  // version and recomputes the metrics required to position the caret.
-  _CaretMetrics _computeCaretMetrics(TextPosition position) {
+  // This function returns the caret's offset and height for the given
+  // `position` in the text, or null if the paragraph is empty.
+  //
+  // For a TextPosition, typically when its TextAffinity is downstream, the
+  // corresponding I-beam caret is anchored to the leading edge of the
+  // `offset`-th character in the text. When the TextAffinity is upstream, the
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/text_painter.dart:1383]: Maybe: "`offset`-th character" => "character at `offset`"

So for offset 1 and affinity downstream, it's anchored to the leading edge of the 2nd character (the character at index 1), right? If so, I think the above change is more clear. When I first read this paragraph, I think I incorrectly interpreted it to mean the 1st character.

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 6]
```diff
@@ -1432,38 +1363,136 @@ class TextPainter {
...
+  //
+  // 2. (textLength, downstream), the end-of-text caret when the text is not
+  //    empty: it's placed next to the trailing edge of the last line of the
+  //    text, in case the text and its last bidi run have different writing
+  //    directions. See the `_computeEndOfTextCaretAnchorOffset` method for more
+  //    details.
+  //
+  // 3. (0, upstream), which isn't a valid position, but it's not a conventional
+  //    "invalid" caret location either (the offset isn't negative). For
+  //    historical reasons, this is treated as (0, downstream).
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/text_painter.dart:1398]: Maybe at some point we should make TextPosition throw an error if you try to create that or something.

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 7]
```diff
@@ -1432,38 +1363,136 @@ class TextPainter {
...
+  //
+  // 4. (x, upstream) where x - 1 points to a line break character. The caret
+  //    should be displayed at the beginning of the newline instead of at the
+  //    end of the previous line. Converts the location to (x, downstream). The
+  //    choice we makes in 5. allows us to still check (x - 1) in case x points
+  //    to a multi-code-unit character.
+  //
+  // 5. (x, downstream || upstream), where x points to a multi-code-unit
+  //    character. There's no perfect caret placement in this case. Here we chose
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/text_painter.dart:1407]: Meaning x could be just before the start of the character or it could be inside of it?

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 8]
```diff
@@ -1432,38 +1363,136 @@ class TextPainter {
...
+
     final _TextPainterLayoutCacheWithOffset cachedLayout = _layoutCache!;
-    if (position == cachedLayout._previousCaretPosition) {
-      return _caretMetrics;
+    // If nothing is laid out, top start is the only reasonable place to place
+    // the cursor.
+    // The HTML renderer reports numberOfLines == 1 when the text is empty:
+    // https://github.com/flutter/flutter/issues/143331
+    if (cachedLayout.paragraph.numberOfLines < 1 || plainText.isEmpty) {
+      // TODO(LongCatIsLooong): assert when an invalid position is given.
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/text_painter.dart:1427]: Calling out another TODO, also repeated below.

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 9]
```diff
@@ -1432,38 +1363,136 @@ class TextPainter {
...
+    final List<TextBox> boxes = cachedLayout.paragraph
+      .getBoxesForRange(graphemeRange.start, graphemeRange.end, boxHeightStyle: ui.BoxHeightStyle.strut);
+    if (boxes.isNotEmpty) {
+      final TextBox box = boxes.single;
+      metrics =_LineCaretMetrics(
+        offset: Offset(anchorToLeadingEdge ? box.start : box.end, box.top),
+        writingDirection: box.direction,
+      );
+    } else {
+      // fallback to glyphInfo. This should only happen when using the HTML renderer.
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/text_painter.dart:1481]: Super nit: Capital "F".

Comment (justinmc) [reply packages/flutter/lib/src/painting/text_painter.dart:1481]: Even more of a nit: should it be "Fall back" with a space?

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 10]
```diff
@@ -6941,7 +6941,7 @@ void main() {
       // the arrow should not point exactly to the caret because the caret is
       // too close to the right.
       controller.dispose();
-      controller = TextEditingController(text: List<String>.filled(200, 'a').join());
+      controller = TextEditingController(text: 'a' * 200);
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:6944]: Did Dart not always have the multiplying a String thing?

File: packages/flutter/test/material/text_field_test.dart [hunk 11]
```diff
@@ -15287,15 +15289,17 @@ void main() {
...
+    // because the paragraph's writing direction is RTL.
+    await tester.enterText(find.byType(TextField), text);
     await tester.pump();
     editable = findRenderEditable(tester);
     cursorRight = editable.getLocalRectForCaret(
       TextPosition(offset: controller.value.text.length),
     ).topRight.dx;
     inputWidth = editable.size.width;
-    expect(cursorRight, inputWidth - kCaretGap);
+    expect(cursorRight, inputWidth - kCaretGap - text.length * 10 - 2.0);
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:15302]: What's the 2.0?

File: packages/flutter/test/widgets/editable_text_utils.dart [hunk 12]
```diff
@@ -39,6 +39,7 @@ List<TextSelectionPoint> globalize(Iterable<TextSelectionPoint> points, RenderBo
 }
 
 Offset textOffsetToPosition(WidgetTester tester, int offset, {int index = 0}) {
+  assert(0 <= offset);
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_utils.dart:42]: Nit: Yoda ordering.

File: examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart [hunk 13]
```diff
@@ -96,16 +97,15 @@ void main() {
   }, variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.iOS, TargetPlatform.android }));
 
 
-  for (final TextDirection textDirection in TextDirection.values) {
```
Comment (justinmc) [inline examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart:99]: Why not run this for both TextDirections any more?

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 14]
```diff
@@ -1432,38 +1363,136 @@ class TextPainter {
...
-    // Cache the input parameters to prevent repeat work later.
-    cachedLayout._previousCaretPosition = position;
-    return _caretMetrics = metrics ?? const _EmptyLineCaretMetrics(lineVerticalOffset: 0);
+
+    final int caretPositionCacheKey = anchorToLeadingEdge ? offset : -offset - 1;
+    if (caretPositionCacheKey == cachedLayout._previousCaretPositionKey) {
+      return _caretMetrics;
+    }
+
+    final ui.GlyphInfo? glyphInfo = cachedLayout.paragraph.getGlyphInfoAt(offset);
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/text_painter.dart:1443]: Can you explain the secret to removing the logarithmic search? Are you able to get the bounds of the glyph using this getGlyphInfoAt method instead? What does it do internally if so?

**Review by justinmc — APPROVED** [review]
LGTM with nits :+1:

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 5 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/painting/text_painter.dart:1383]: That's right.

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 7 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/painting/text_painter.dart:1407]: `x ∈ [grapheme_start, grapheme_end)` where `grapheme_end > grapheme_start + 1`

File: packages/flutter/test/widgets/editable_text_utils.dart (hunk 12 above)
Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/editable_text_utils.dart:42]: removed the assert.

File: examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart (hunk 13 above)
Comment (LongCatIsLooong) [reply examples/api/test/widgets/text_magnifier/text_magnifier.0_test.dart:99]: The LTR variation is exactly the same test as the one above.

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 14 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/painting/text_painter.dart:1443]: `getBoxForSelection` doesn't include a multi-code-unit character if the input selection doesn't include the full range of it. Alternatively the same can be done using the characters package.

File: packages/flutter/test/material/text_field_test.dart (hunk 11 above)
Comment (LongCatIsLooong) [reply packages/flutter/test/material/text_field_test.dart:15265]: caret width

**Comment by LongCatIsLooong** [comment]
Internal golden changes: 608683435/OCL:608683435:BASE:608686983:1708458883435:81866925 the new images look right to me.

**Comment by LongCatIsLooong** [comment]
Reason for revert: https://github.com/flutter/flutter/issues/143797
