### PR TITLE
Fix DropdownButton crash when hint and selectedItemBuilder are simultaneously defined

### LINKED ISSUE #42340: DropdownButton exception when selectedItemBuilder and hint are simultaneously defined
For DropdownButtons, specifying both a 'selectedItemBuilder' and 'hint' at the same time causes an exception:

Error message: 
```
I/flutter (13720): The following assertion was thrown building DropdownButton<String>(dirty, dependencies:
I/flutter (13720): [_LocalizationsScope-[GlobalKey#3706d], _InheritedTheme], state:
I/flutter (13720): _DropdownButtonState<String>#95f65):
I/flutter (13720): type 'DefaultTextStyle' is not a subtype of type 'Container' of 'value'
I/flutter (13720):
I/flutter (13720): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13720): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13720): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13720):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (13720):
I/flutter (13720): User-created ancestor of the error-causing widget was:
I/flutter (13720):   Padding
I/flutter (13720):   
lib/main.dart:31
I/flutter (13720):
I/flutter (13720): When the exception was thrown, this was the stack:
I/flutter (13720): #0      List.add (dart:core-patch/growable_array.dart)
I/flutter (13720): #1      _DropdownButtonState.build 
package:flutter/…/material/dropdown.dart:962
I/flutter (13720): #2      StatefulElement.build 
package:flutter/…/widgets/framework.dart:4064
I/flutter (13720): #3      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3958
I/flutter (13720): #4      Element.rebuild 
package:flutter/…/widgets/framework.dart:3755
I/flutter (13720): #5      ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:3941
I/flutter (13720): #6      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4111
I/flutter (13720): #7      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3936
I/flutter (13720): #8      Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3109
I/flutter (13720): #9      Element.updateChild 
package:flutter/…/widgets/framework.dart:2903
I/flutter (13720): #10     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5165
I/flutter (13720): #11     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3109
I/flutter (13720): #12     Element.updateChild 
package:flutter/…/widgets/framework.dart:2903
I/flutter (13720): #13     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5165
```

Test code: 
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Test')),
        body: MyStatefulWidget(),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  final List<String> items = <String>['Item 1', 'Item 2', 'Item 3'];
  String selectedItem = 'Item 1';

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 12.0),
        child: DropdownButton<String>(
          hint: Text('Here is a hint'),
          value: selectedItem,
          onChanged: (String string) => setState(() => selectedItem = string),
          selectedItemBuilder: (BuildContext context) {
            return items.map((String item) {
              return Text(item);
            }).toList();
          },
          items: items.map((String item) {
            return DropdownMenuItem<String>(
              child: Text(item),
              value: item,
            );
          }).toList(),
        ),
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

Currently, DropdownButton causes a crash when both `hint` and `selectedItemBuilder` are simultaneously defined because an internal List.map call was returning a List\<Container\> instead of List\<Widget\>. This fix forces selectedItemBuilder to return List\<Widget\>

## Related Issues

Fixes https://github.com/flutter/flutter/issues/42340

## Tests

I added the following tests:

- A test to initially show the hint text, and then tapping an item from the menu correctly displaying its corresponding selected item in selectedItemBuilder

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/material/dropdown_test.dart [hunk 1]
```diff
@@ -1359,6 +1359,50 @@ void main() {
     expect(find.text('Two as an Arabic numeral: 2'), findsOneWidget);
   });
 
+  testWidgets('DropdownButton hint displays properly when selectedItemBuilder is defined', (WidgetTester tester) async {
+    // Test for https://github.com/flutter/flutter/issues/42340
```
Comment (HansMuller) [inline packages/flutter/test/material/dropdown_test.dart]: Regression test for ...

File: packages/flutter/lib/src/material/dropdown.dart [hunk 2]
```diff
@@ -942,7 +942,7 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
     if (_enabled) {
       items = widget.selectedItemBuilder == null
         ? List<Widget>.from(widget.items)
-        : widget.selectedItemBuilder(context).map((Widget item) {
+        : widget.selectedItemBuilder(context).map<Widget>((Widget item) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/dropdown.dart]: It would be helpful to make the same change in the sample code.

**Review by HansMuller — APPROVED** [review]
LGTM
