### PR TITLE
WebKit should respect TextCapitalization.words

### LINKED ISSUE #151118: `TextCapitalization.words` doesn't work on `Web` using iOS devices
### Steps to reproduce

1. Create a new flutter app
2. Copy the sample code in `lib/main.dart`
3. Build for web platform and host somewhere
4. Open it on safari, chrome, etc. on an iOS device
5. Start typing with spaces in between
6. See first letter of words after the first word are not capitalized.

### Expected results

Each word's first letter should be capital just like in native iOS application.

### Actual results

Only the first letter of the first word in each sentence is capitalized.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: const Text('iOS Text Capitalization Issue'),
        ),
        body: Padding(
          padding: const EdgeInsets.all(20),
          child: Center(
            child: TextFormField(
              decoration: const InputDecoration(
                labelText: 'Name',
                hintText: 'Enter Your Name',
                border: UnderlineInputBorder(),
                counterText: '',
              ),
              maxLength: 50,
              keyboardType: TextInputType.text,
              textCapitalization: TextCapitalization.words,
              textInputAction: TextInputAction.done,
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

| iOS | Android |
|--------|--------|
| <video src='https://github.com/flutter/flutter/assets/74326345/3ee525d2-0f99-4031-b914-ef8a49b191c5' /> | <video src='https://github.com/flutter/flutter/assets/74326345/c263bfe2-c577-4568-9405-22fc006c1038' /> | 

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-IN)
    • Flutter version 3.22.2 on channel stable at /Users/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] VS Code (version 1.91.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by NabilaWorks**
Fixes https://github.com/flutter/flutter/issues/151118

https://github.com/user-attachments/assets/88a9baf9-8f2c-48fb-ad9c-1618fbce0795

Flutter web apps on iOS were forced to use `sentences` instead of `words` when `TextCapitalization.words` was specified, in order to work around this particular bug : https://bugs.webkit.org/show_bug.cgi?id=148504

That bug was fixed more than 4 years ago so it should be safe to use `words` now.

With this change, legacy devices that are still on specific versions on iOS 13 or lower might experience the old WebKit bug when `TextCapitalization.words` is used, however the Flutter developer who expects such users can work around that bug by detecting the user agent and using `TextCapitalization.sentences` conditionally, in order to get the existing behavior prior to this change.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by justinmc — APPROVED** [review]
LGTM from the text input point of view 👍 

CC @mdebbar for secondary review please! Your comment is removed here.

**Comment by justinmc** [comment]
I'm asking about the failure on Discord: https://discord.com/channels/608014603317936148/608021351567065092/1329946390385922228

**Comment by justinmc** [comment]
@NabilaWorks The analyzer failure seems totally unrelated... If merge commits aren't working, try a rebase maybe?

File: engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart [hunk 1]
```diff
@@ -1545,6 +1545,39 @@ Future<void> testMain() async {
...
+
+      const MethodCall show = MethodCall('TextInput.show');
+      sendFrameworkMessage(codec.encodeMethodCall(show));
+      spy.messages.clear();
+
+      // Test for mobile Safari.
+      if (ui_web.browser.browserEngine == ui_web.BrowserEngine.webkit &&
+          ui_web.browser.operatingSystem == ui_web.OperatingSystem.iOs) {
+        expect(textEditing!.strategy.domElement!.getAttribute('autocapitalize'), 'words');
+      }
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart:1575]: Since this is supposed to work in all browsers now, let's test all browsers:
```suggestion
      expect(textEditing!.strategy.domElement!.getAttribute('autocapitalize'), 'words');
```

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_capitalization.dart
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_capitalization.dart:1]: Line 5: `import 'package:ui/ui_web/src/ui_web.dart' as ui_web;` needs to be removed.

**Review by mdebbar — APPROVED** [review]
Thanks for the contribution! I only have a couple of comments; other than that, the PR looks good to me 👍

**Comment by hellohuanlin** [comment]
> With this change, legacy devices that are still on specific versions on iOS 13 or lower might experience the old WebKit bug when TextCapitalization.words is used, however the Flutter developer who expects such users can work around that bug by detecting the user agent and using TextCapitalization.sentences conditionally, in order to get the existing behavior prior to this change.

I'd recommend doing a version check for iOS 13.

File: engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_capitalization.dart [hunk 2]
```diff
@@ -62,14 +62,7 @@ class TextCapitalizationConfig {
     String autocapitalize = '';
     switch (textCapitalization) {
       case TextCapitalization.words:
-        // TODO(mdebbar): There is a bug for `words` level capitalization in IOS now.
-        // For now go back to default. Remove the check after bug is resolved.
-        // https://bugs.webkit.org/show_bug.cgi?id=148504
-        if (ui_web.browser.browserEngine == ui_web.BrowserEngine.webkit) {
```
Comment (justinmc) [inline engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_capitalization.dart:68]: I think removing this has made an import obsolete, which is being caught by the analyzer.

Comment (justinmc) [reply engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_capitalization.dart:68]: @NabilaWorks Are you still available to get this PR passing?

File: engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart (hunk 1 above)
Comment (mdebbar) [reply engine/src/flutter/lib/web_ui/test/engine/text_editing_test.dart:1575]: Oh my bad. The `autocapitalize` attribute is only applied for mobile browsers:
https://github.com/flutter/flutter/blob/e6c333b555b5be4d339ed27d24a364c2719993d4/engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart#L1662
https://github.com/flutter/flutter/blob/e6c333b555b5be4d339ed27d24a364c2719993d4/engine/src/flutter/lib/web_ui/lib/src/engine/text_editing/text_editing.dart#L1792

**Review by mdebbar — APPROVED** [review]
LGTM

**Review by justinmc — APPROVED** [review]
Thanks for getting this passing, I'll add the autosubmit label.
