### PR TITLE
[flutter_tools] fix lateinitialization error in devicelab-runner

### LINKED ISSUE #94956: package:flutter_devicelab "LateInitializationError: Local 'simulatorDeviceId' has not been initialized"
I hit this flake for the try build `Mac module_test_ios`

PR/failing check: https://github.com/flutter/flutter/pull/94950/checks?check_run_id=4475140908
LUCI build: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20module_test_ios/11324/overview
STDERR: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8828296312716791249/+/u/run_module_test_ios/test_stderr

```
[module_test_ios] [STDERR] Task failed: LateInitializationError: Local 'simulatorDeviceId' has not been initialized.
[module_test_ios] [STDERR] 
[module_test_ios] [STDERR] Stack trace:
[module_test_ios] [STDERR] dart:_internal                                             LateError._throwLocalNotInitialized
[module_test_ios] [STDERR] bin/tasks/module_test_ios.dart 478:35                      main.<fn>
[module_test_ios] [STDERR] ===== asynchronous gap ===========================
[module_test_ios] [STDERR] dart:async                                                 _asyncErrorWrapperHelper
[module_test_ios] [STDERR] package:flutter_devicelab/framework/framework.dart         _TaskRunner._performTask.<fn>
[module_test_ios] [STDERR] package:stack_trace                                        Chain.capture
[module_test_ios] [STDERR] package:flutter_devicelab/framework/framework.dart 262:11  _TaskRunner._performTask
[module_test_ios] [STDERR] package:flutter_devicelab/framework/framework.dart 155:43  _TaskRunner.run
```

Here is the line that is failing: https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/module_test_ios.dart#L478

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/94956

A variable was marked `late` although it was accessed in a `finally` block that could have run before the variable was initialized. Thus, mark the variable nullable, and update the function that handles the value to receive a nullable parameter (the code already handles `null`).

### CODE REVIEW

File: dev/devicelab/lib/framework/ios.dart [hunk 1]
```diff
@@ -116,14 +116,14 @@ Future<void> testWithNewIOSSimulator(
 }
 
 /// Shuts down and deletes simulator with deviceId.
-Future<void> removeIOSimulator(String deviceId) async {
+Future<void> removeIOSimulator(String? deviceId) async {
```
Comment (christopherfujino) [inline dev/devicelab/lib/framework/ios.dart:119]: as this function handles `null`, I believe the root problem was that when this file was migrated, this parameter type should have been made nullable.

Comment (keyonghan) [reply dev/devicelab/lib/framework/ios.dart:119]: I am wondering why the post submit run has never hit this flake: https://ci.chromium.org/p/flutter/builders/prod/Mac%20module_test_ios?limit=100?

Comment (christopherfujino) [reply dev/devicelab/lib/framework/ios.dart:119]: maybe post-submit has never failed early enough?

**Review by keyonghan — APPROVED** [review]
LGTM.
