### PR TITLE
Retry getting tabs in chrome launcher on ConnectionException

### LINKED ISSUE #94886: Intermittent failure to connect to chrome tabs on test bots
Part of issues causing web_tool_tests bot failures. See parent issue: https://github.com/flutter/flutter/issues/93256

From build https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/4272/overview

```
01:36 +3 -1: test/web.shard/vm_service_web_test.dart: Clients of flutter run on web with DDS enabled can validate flutter version in parallel [E]                                                      
  Exception: Received app.stop event while waiting for app.started event
  
  [+1795 ms] FormatException: Unexpected character (at character 1)
         <html>
         ^

         #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
         #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272:9)
         #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937:22)
         #3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
         #4      JsonDecoder.convert (dart:convert/json.dart:612:36)
         #5      JsonCodec.decode (dart:convert/json.dart:216:41)
         #6      jsonDecode (dart:convert/json.dart:155:10)
         #7      ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:44:10)
         <asynchronous suspension>
         #8      ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:57:25)
         <asynchronous suspension>
         #9      ChromiumLauncher._connect (package:flutter_tools/src/web/chrome.dart:401:9)
         <asynchronous suspension>
         #10     ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:134:17)
         <asynchronous suspension>
         #11     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:307:9)
         <asynchronous suspension>
         #12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
         <asynchronous suspension>

  Unable to connect to Chrome debug port: 40881
```

### PR DESCRIPTION
**Pull request by annagrin**
Add more information and potentially resolve `web_tool_tests` flakes caused by failure to get a tab list from Chrome on launch.

- run `flutter update-packages --force-upgrade` to bring new `package:webkit_inspection_protocol.dart` and more.
- update ChromeLauncher to pass a `retryFor` duration so we try getting tabs for a couple of seconds.
- make `ChromeLauncher.connect` API available for testing.
- add tests for `ChromeLauncher.connect`.

Closes: https://github.com/flutter/flutter/issues/94886

## Pre-launch Checklist

- [v] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [v] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [v] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [v] I signed the [CLA].
- [v] I listed at least one issue that this PR fixes in the description above.
- [v] I updated/added relevant documentation (doc comments with `///`).
- [v] I added new tests to check the change I am making, or this PR is [test-exempt].
- [v] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 1]
```diff
@@ -411,6 +413,36 @@ class ChromiumLauncher {
     return chrome;
   }
 
+  /// Gets the first [chrome] tab.
+  ///
+  /// Note: Retry getting tabs from Chrome for a few seconds and retry finding
+  /// the tab a few times. This prevents flakes caused by Chrome not returning
+  /// correct output if the call was too close to the start.
+  Future<ChromeTab?> _getFirstTab(Chromium chrome) async {
+    const Duration retryFor = Duration(seconds: 2);
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/web/chrome.dart:422]: This is intended to retry for up to 10s (2s * 5 tries)?

FYI, the `getTabs(retryFor)` call automatically retries around 4 times, and for as long as the given duration. This method - which may be intended? - is then layered more retry efforts on top of that.

https://github.com/google/webkit_inspection_protocol.dart/pull/88/files#diff-1c32e5460556de493e3a74667b36726abd37a69815a1e579cd18a5a1eac9b54fR47

Comment (annagrin) [reply packages/flutter_tools/lib/src/web/chrome.dart:422]: The layers of retries are intentional - normally we would retry until we get the first tab (the first attempts might return empty tab list).

In theory, we should always succeed, and previously the tool crashed at the first failure so it is hard to tell how many times the current failure can happen in a row. 

I might have added too many retries, but I would like to collect more information if the failures happen again - if we cannot connect to chrome for that long then something is else is going wrong and needs investigation. I would also change it to less retries at that moment to make sure we do not delay the tests too much.

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 2]
```diff
@@ -411,6 +413,36 @@ class ChromiumLauncher {
...
+        }
+        if (i == attempts) {
+          return null;
+        }
+      } on ConnectionException catch (_) {
+        if (i == attempts) {
+          rethrow;
+        }
+      }
+      await Future<dynamic>.delayed(const Duration(milliseconds: 25));
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/web/chrome.dart:441]:
```suggestion
      await Future<void>.delayed(const Duration(milliseconds: 25));
```

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/web/chrome.dart:441]: we try to avoid `dynamic` in the tool (in cases where you actually use hte value, `Object?` is preferred over `dynamic`)

**Review by christopherfujino — APPROVED** [review]
LGTM with 1 nit

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 1 above)
Comment (devoncarew) [reply packages/flutter_tools/lib/src/web/chrome.dart:422]: Gotcha! Sounds like this is indeed what's intended.

**Comment by christopherfujino** [comment]
@annagrin marked "Google testing" green because the CL says pre-submits passed, I'm guessing this is a FRoB bug. This is good to go!

**Comment by annagrin** [comment]
@christopherfujino 

> marked "Google testing" green because the CL says pre-submits passed, I'm guessing this is a FRoB bug. This is good to go!

Thanks, they were failing of a reason at first - package:webkit_inspection_protocol needed to be updated - so I fixed it and rerun the tests (that's why they were showing as passing) but the CI did not detect it for some reason.
