### PR TITLE
[flutter_tools] Let CMake handle escaping

### LINKED ISSUE #67270: Flutter Desktop Linux: Running with spaces in the current directory path doesn't escape properly.
### Steps to reproduce
~~~
flutter create myapp
flutter run -d linux
~~~
### Flutter Doctor Output
~~~
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.23.0-7.0.pre, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.3)
[✓] Connected device (3 available)

• No issues found!
~~~

### Flutter run -v -d linux
~~~
[ +130 ms] executing: [/home/syed/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] db6e2d8aa5bb9a0bd3e75fc7470268b5a56fd0b0
[        ] executing: [/home/syed/snap/flutter/common/flutter/] git tag --points-at HEAD
[  +14 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.23.0-7.0.pre
[  +19 ms] executing: [/home/syed/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/syed/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +67 ms] executing: [/home/syed/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +79 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +106 ms] executing: /home/syed/Android/Sdk/platform-tools/adb devices -l
[  +21 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +106 ms] executing: /home/syed/Android/Sdk/platform-tools/adb devices -l
[  +40 ms] Running "flutter pub get" in linux_terminal...
[   +9 ms] Using /home/syed/snap/flutter/common/flutter/.pub-cache for the pub cache.
[   +1 ms] executing: [/home/syed/Development/Flutter Demo Apps/Linux Apps/linux_terminal/]
/home/syed/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[  +92 ms] List of devices attached
[   +6 ms] List of devices attached
[  +47 ms] FINE: Pub 2.11.0-161.0.dev
[ +137 ms] MSG : Resolving dependencies...
[  +72 ms] SLVR: fact: linux_terminal is 1.0.0+1
[  +12 ms] SLVR: derived: linux_terminal
[  +39 ms] SLVR: fact: linux_terminal depends on flutter any from sdk
[   +2 ms] SLVR: fact: linux_terminal depends on cupertino_icons ^1.0.0
[   +1 ms] SLVR: fact: linux_terminal depends on flutter_test any from sdk
[   +3 ms] SLVR:   selecting linux_terminal
[        ] SLVR:   derived: flutter_test any from sdk
[   +4 ms] SLVR:   derived: cupertino_icons ^1.0.0
[        ] SLVR:   derived: flutter any from sdk
[  +31 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on flutter any from sdk
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on test_api 0.2.19-nullsafety.2
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on path 1.8.0-nullsafety.1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on fake_async 1.2.0-nullsafety.1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on clock 1.1.0-nullsafety.1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stack_trace 1.10.0-nullsafety.1
[   +3 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on vector_math 2.1.0-nullsafety.3
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on async 2.5.0-nullsafety.1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on boolean_selector 2.1.0-nullsafety.1
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on characters 1.1.0-nullsafety.3
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on charcode 1.2.0-nullsafety.1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on collection 1.15.0-nullsafety.3
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on matcher 0.12.10-nullsafety.1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on meta 1.3.0-nullsafety.3
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on source_span 1.8.0-nullsafety.2
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stream_channel 2.1.0-nullsafety.1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on string_scanner 1.1.0-nullsafety.1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on term_glyph 1.2.0-nullsafety.1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on typed_data 1.3.0-nullsafety.3
[        ] SLVR:     selecting flutter_test 0.0.0 from sdk
[        ] SLVR:     derived: typed_data 1.3.0-nullsafety.3
[        ] SLVR:     derived: term_glyph 1.2.0-nullsafety.1
[        ] SLVR:     derived: string_scanner 1.1.0-nullsafety.1
[        ] SLVR:     derived: stream_channel 2.1.0-nullsafety.1
[        ] SLVR:     derived: source_span 1.8.0-nullsafety.2
[        ] SLVR:     derived: meta 1.3.0-nullsafety.3
[   +1 ms] SLVR:     derived: matcher 0.12.10-nullsafety.1
[        ] SLVR:     derived: collection 1.15.0-nullsafety.3
[        ] SLVR:     derived: charcode 1.2.0-nullsafety.1
[        ] SLVR:     derived: characters 1.1.0-nullsafety.3
[        ] SLVR:     derived: boolean_selector 2.1.0-nullsafety.1
[        ] SLVR:     derived: async 2.5.0-nullsafety.1
[        ] SLVR:     derived: vector_math 2.1.0-nullsafety.3
[   +1 ms] SLVR:     derived: stack_trace 1.10.0-nullsafety.1
[   +2 ms] SLVR:     derived: clock 1.1.0-nullsafety.1
[        ] SLVR:     derived: fake_async 1.2.0-nullsafety.1
[        ] SLVR:     derived: path 1.8.0-nullsafety.1
[        ] SLVR:     derived: test_api 0.2.19-nullsafety.2
[  +13 ms] SLVR:       selecting cupertino_icons 1.0.0
[  +15 ms] SLVR:       fact: flutter 0.0.0 from sdk depends on characters 1.1.0-nullsafety.3
[   +1 ms] SLVR:       fact: flutter 0.0.0 from sdk depends on collection 1.15.0-nullsafety.3
[        ] SLVR:       fact: flutter 0.0.0 from sdk depends on meta 1.3.0-nullsafety.3
[        ] SLVR:       fact: flutter 0.0.0 from sdk depends on typed_data 1.3.0-nullsafety.3
[        ] SLVR:       fact: flutter 0.0.0 from sdk depends on vector_math 2.1.0-nullsafety.3
[   +2 ms] SLVR:       fact: flutter 0.0.0 from sdk depends on sky_engine any from sdk
[        ] SLVR:         selecting flutter 0.0.0 from sdk
[        ] SLVR:         derived: sky_engine any from sdk
[   +9 ms] SLVR:         fact: typed_data 1.3.0-nullsafety.3 depends on collection >=1.15.0-nullsafety <1.15.0
[   +2 ms] SLVR:           selecting typed_data 1.3.0-nullsafety.3
[   +8 ms] SLVR:             selecting term_glyph 1.2.0-nullsafety.1
[  +13 ms] SLVR:             fact: string_scanner 1.1.0-nullsafety.1 depends on charcode >=1.2.0-nullsafety <1.2.0
[        ] SLVR:             fact: string_scanner 1.1.0-nullsafety.1 depends on source_span >=1.8.0-nullsafety <1.8.0
[   +1 ms] SLVR:               selecting string_scanner 1.1.0-nullsafety.1
[   +5 ms] SLVR:               fact: stream_channel 2.1.0-nullsafety.1 depends on async >=2.5.0-nullsafety <2.5.0
[        ] SLVR:                 selecting stream_channel 2.1.0-nullsafety.1
[  +11 ms] SLVR:                 fact: source_span 1.8.0-nullsafety.2 depends on charcode >=1.2.0-nullsafety <1.2.0
[        ] SLVR:                 fact: source_span 1.8.0-nullsafety.2 depends on collection >=1.15.0-nullsafety <1.15.0
[        ] SLVR:                 fact: source_span 1.8.0-nullsafety.2 depends on path >=1.8.0-nullsafety <1.8.0
[        ] SLVR:                 fact: source_span 1.8.0-nullsafety.2 depends on term_glyph >=1.2.0-nullsafety <1.2.0
[   +1 ms] SLVR:                   selecting source_span 1.8.0-nullsafety.2
[        ] SLVR:                     selecting meta 1.3.0-nullsafety.3
[   +5 ms] SLVR:                     fact: matcher 0.12.10-nullsafety.1 depends on stack_trace >=1.10.0-nullsafety <1.10.0
[   +1 ms] SLVR:                       selecting matcher 0.12.10-nullsafety.1
[   +4 ms] SLVR:                         selecting collection 1.15.0-nullsafety.3
[   +9 ms] SLVR:                           selecting charcode 1.2.0-nullsafety.1
[   +8 ms] SLVR:                             selecting characters 1.1.0-nullsafety.3
[   +5 ms] SLVR:                             fact: boolean_selector 2.1.0-nullsafety.1 depends on source_span
>=1.8.0-nullsafety <1.8.0
[   +7 ms] SLVR:                             fact: boolean_selector 2.1.0-nullsafety.1 depends on string_scanner
>=1.1.0-nullsafety <1.1.0
[   +1 ms] SLVR:                               selecting boolean_selector 2.1.0-nullsafety.1
[   +2 ms] SLVR:                               fact: async 2.5.0-nullsafety.1 depends on collection >=1.15.0-nullsafety
<1.15.0
[        ] SLVR:                                 selecting async 2.5.0-nullsafety.1
[   +6 ms] SLVR:                                   selecting vector_math 2.1.0-nullsafety.3
[   +5 ms] SLVR:                                   fact: stack_trace 1.10.0-nullsafety.1 depends on path >=1.8.0-nullsafety
<1.8.0
[        ] SLVR:                                     selecting stack_trace 1.10.0-nullsafety.1
[   +4 ms] SLVR:                                       selecting clock 1.1.0-nullsafety.1
[   +6 ms] SLVR:                                       fact: fake_async 1.2.0-nullsafety.1 depends on clock
>=1.1.0-nullsafety <1.1.0
[        ] SLVR:                                       fact: fake_async 1.2.0-nullsafety.1 depends on collection
>=1.15.0-nullsafety <1.15.0
[   +1 ms] SLVR:                                         selecting fake_async 1.2.0-nullsafety.1
[   +2 ms] SLVR:                                           selecting path 1.8.0-nullsafety.1
[   +7 ms] SLVR:                                           fact: test_api 0.2.19-nullsafety.2 depends on async
>=2.5.0-nullsafety <2.5.0
[        ] SLVR:                                           fact: test_api 0.2.19-nullsafety.2 depends on boolean_selector
>=2.1.0-nullsafety <2.1.0
[   +3 ms] SLVR:                                           fact: test_api 0.2.19-nullsafety.2 depends on collection
>=1.15.0-nullsafety <1.15.0
[   +1 ms] SLVR:                                           fact: test_api 0.2.19-nullsafety.2 depends on meta
>=1.3.0-nullsafety <1.3.0
[        ] SLVR:                                           fact: test_api 0.2.19-nullsafety.2 depends on path
>=1.8.0-nullsafety <1.8.0
[        ] SLVR:                                           fact: test_api 0.2.19-nullsafety.2 depends on source_span
>=1.8.0-nullsafety <1.8.0
[   +1 ms] SLVR:                                           fact: test_api 0.2.19-nullsafety.2 depends on stack_trace
>=1.10.0-nullsafety <1.10.0
[   +2 ms] SLVR:                                           fact: test_api 0.2.19-nullsafety.2 depends on stream_channel
>=2.1.0-nullsafety <2.1.0
[   +1 ms] SLVR:                                           fact: test_api 0.2.19-nullsafety.2 depends on string_scanner
>=1.1.0-nullsafety <1.1.0
[   +2 ms] SLVR:                                           fact: test_api 0.2.19-nullsafety.2 depends on term_glyph
>=1.2.0-nullsafety <1.2.0
[   +1 ms] SLVR:                                           fact: test_api 0.2.19-nullsafety.2 depends on matcher
>=0.12.10-nullsafety <0.12.10
[   +1 ms] SLVR:                                             selecting test_api 0.2.19-nullsafety.2
[        ] SLVR:                                               selecting sky_engine 0.0.99 from sdk
[   +2 ms] SLVR: Version solving took 0:00:00.326126 seconds.
[        ]     | Tried 1 solutions.
[        ] FINE: Resolving dependencies finished (0.395s).
[   +8 ms] MSG : Overriding the upper bound Dart SDK constraint to <=2.11.0-161.0.dev for the following packages:
[        ]     | 
[        ]     | async, boolean_selector, characters, charcode, clock, collection, fake_async, matcher, meta, path,
source_span, stack_trace, stream_channel, string_scanner, term_glyph, test_api, typed_data, vector_math
[   +6 ms]     | 
[        ]     | To disable this you can set the PUB_ALLOW_PRERELEASE_SDK system environment variable to `false`, or you
can silence this message by setting it to `quiet`.
[ +113 ms] IO  : Writing 3691 characters to text file ./pubspec.lock.
[        ] FINE: Contents:
[        ]     | # Generated by pub
[        ]     | # See https://dart.dev/tools/pub/glossary#lockfile
[        ]     | packages:
[        ]     |   async:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: async
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.5.0-nullsafety.1"
[   +3 ms]     |   boolean_selector:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: boolean_selector
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.1.0-nullsafety.1"
[        ]     |   characters:
[   +5 ms]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: characters
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.1.0-nullsafety.3"
[        ]     |   charcode:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: charcode
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.2.0-nullsafety.1"
[   +3 ms]     |   clock:
[        ]     |     dependency: transitive
[        ]     |     description:
[   +1 ms]     |       name: clock
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.1.0-nullsafety.1"
[        ]     |   collection:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: collection
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.15.0-nullsafety.3"
[        ]     |   cupertino_icons:
[        ]     |     dependency: "direct main"
[        ]     |     description:
[        ]     |       name: cupertino_icons
[   +3 ms]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.0.0"
[        ]     |   fake_async:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: fake_async
[        ]     |       url: "https://pub.dartlang.org"
[   +4 ms]     |     source: hosted
[   +3 ms]     |     version: "1.2.0-nullsafety.1"
[        ]     |   flutter:
[        ]     |     dependency: "direct main"
[   +3 ms]     |     description: flutter
[   +2 ms]     |     source: sdk
[        ]     |     version: "0.0.0"
[        ]     |   flutter_test:
[        ]     |     dependency: "direct dev"
[        ]     |     description: flutter
[        ]     |     source: sdk
[   +4 ms]     |     version: "0.0.0"
[        ]     |   matcher:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: matcher
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "0.12.10-nullsafety.1"
[   +4 ms]     |   meta:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: meta
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.3.0-nullsafety.3"
[        ]     |   path:
[        ]     |     dependency: transitive
[        ]     |     description:
[   +3 ms]     |       name: path
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[   +2 ms]     |     version: "1.8.0-nullsafety.1"
[        ]     |   sky_engine:
[        ]     |     dependency: transitive
[        ]     |     description: flutter
[        ]     |     source: sdk
[        ]     |     version: "0.0.99"
[        ]     |   source_span:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: source_span
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.8.0-nullsafety.2"
[        ]     |   stack_trace:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: stack_trace
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.10.0-nullsafety.1"
[        ]     |   stream_channel:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: stream_channel
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[   +1 ms]     |     version: "2.1.0-nullsafety.1"
[        ]     |   string_scanner:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: string_scanner
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[   +1 ms]     |     version: "1.1.0-nullsafety.1"
[        ]     |   term_glyph:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: term_glyph
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[   +4 ms]     |     version: "1.2.0-nullsafety.1"
[        ]     |   test_api:
[        ]     |     dependency: transitive
[        ]     |     description:
[   +3 ms]     |       name: test_api
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "0.2.19-nullsafety.2"
[        ]     |   typed_data:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: typed_data
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.3.0-nullsafety.3"
[        ]     |   vector_math:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: vector_math
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.1.0-nullsafety.3"
[        ]     | sdks:
[        ]     |   dart: ">=2.10.0-110 <=2.11.0-161.0.dev"
[   +2 ms] IO  : Writing 2710 characters to text file ./.packages.
[        ] FINE: Contents:
[        ]     | # Generated by pub on 2020-10-04 20:30:09.811757.
[        ]     |
async:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/async-2.5.0-nullsafety.1/lib/
[   +1 ms]     |
boolean_selector:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/boolean_selector-2.1.0-nu
llsafety.1/lib/
[   +1 ms]     |
characters:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/characters-1.1.0-nullsafety.3/l
ib/
[        ]     |
charcode:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/charcode-1.2.0-nullsafety.1/lib/
[        ]     |
clock:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/clock-1.1.0-nullsafety.1/lib/
[        ]     |
collection:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.15.0-nullsafety.3/
lib/
[        ]     |
cupertino_icons:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cupertino_icons-1.0.0/lib/
[        ]     |
fake_async:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fake_async-1.2.0-nullsafety.1/l
ib/
[   +1 ms]     | flutter:file:///home/syed/snap/flutter/common/flutter/packages/flutter/lib/
[        ]     | flutter_test:file:///home/syed/snap/flutter/common/flutter/packages/flutter_test/lib/
[        ]     |
matcher:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.10-nullsafety.1/lib/
[        ]     |
meta:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0-nullsafety.3/lib/
[        ]     |
path:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety.1/lib/
[        ]     | sky_engine:file:///home/syed/snap/flutter/common/flutter/bin/cache/pkg/sky_engine/lib/
[        ]     |
source_span:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/source_span-1.8.0-nullsafety.2
/lib/
[   +1 ms]     |
stack_trace:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.10.0-nullsafety.
1/lib/
[        ]     |
stream_channel:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.1.0-nullsa
fety.1/lib/
[        ]     |
string_scanner:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.1.0-nullsa
fety.1/lib/
[        ]     |
term_glyph:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.2.0-nullsafety.1/l
ib/
[        ]     |
test_api:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.19-nullsafety.2/lib/
[        ]     |
typed_data:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/typed_data-1.3.0-nullsafety.3/l
ib/
[        ]     |
vector_math:file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.1.0-nullsafety.3
/lib/
[        ]     | linux_terminal:lib/
[        ] IO  : Writing 5231 characters to text file ./.dart_tool/package_config.json.
[        ] FINE: Contents:
[        ]     | {
[        ]     |   "configVersion": 2,
[        ]     |   "packages": [
[        ]     |     {
[        ]     |       "name": "async",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/async-2.5.0-nullsafety.1",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "boolean_selector",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/boolean_selector-2.1.0-nullsafety.1",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "characters",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/characters-1.1.0-nullsafety.3",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "charcode",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/charcode-1.2.0-nullsafety.1",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "clock",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/clock-1.1.0-nullsafety.1",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "collection",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.15.0-nullsafety.3",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "cupertino_icons",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cupertino_icons-1.0.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.0"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "fake_async",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fake_async-1.2.0-nullsafety.1",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "flutter",
[        ]     |       "rootUri": "file:///home/syed/snap/flutter/common/flutter/packages/flutter",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "flutter_test",
[        ]     |       "rootUri": "file:///home/syed/snap/flutter/common/flutter/packages/flutter_test",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.2"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "matcher",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.10-nullsafety.1",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "meta",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0-nullsafety.3",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "path",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety.1",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "sky_engine",
[        ]     |       "rootUri": "file:///home/syed/snap/flutter/common/flutter/bin/cache/pkg/sky_engine",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "1.11"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "source_span",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/source_span-1.8.0-nullsafety.2",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "stack_trace",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.10.0-nullsafety.1",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "stream_channel",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.1.0-nullsafety.1",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "string_scanner",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.1.0-nullsafety.1",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "term_glyph",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.2.0-nullsafety.1",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "test_api",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.19-nullsafety.2",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "typed_data",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/typed_data-1.3.0-nullsafety.3",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "vector_math",
[        ]     |       "rootUri":
"file:///home/syed/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.1.0-nullsafety.3",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.10"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "linux_terminal",
[        ]     |       "rootUri": "../",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.7"
[        ]     |     }
[        ]     |   ],
[        ]     |   "generated": "2020-10-04T15:30:09.858645Z",
[        ]     |   "generator": "pub",
[        ]     |   "generatorVersion": "2.11.0-161.0.dev"
[        ]     | }
[   +2 ms] MSG : Got dependencies!
[  +74 ms] Running "flutter pub get" in linux_terminal... (completed in 1.1s)
[ +335 ms] Generating /home/syed/Development/Flutter Demo Apps/Linux
Apps/linux_terminal/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +139 ms] Starting incremental build...
[   +4 ms] Initializing file store
[  +22 ms] Skipping target: gen_localizations
[  +13 ms] complete
[   +7 ms] Launching lib/main.dart on Linux in debug mode...
[  +14 ms] /home/syed/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/syed/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/syed/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental
--target=flutter --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true
--output-dill /tmp/flutter_tools.XELCWR/flutter_tool.VALNRC/app.dill --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-c
losure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build/cache.dill.track.dill
[  +20 ms] Building Linux application...
[  +22 ms] <- compile package:linux_terminal/main.dart
[   +5 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux
[ +319 ms] -- The CXX compiler identification is Clang 6.0.0
[   +6 ms] -- Check for working CXX compiler: /snap/flutter/29/usr/bin/clang++
[ +178 ms] -- Check for working CXX compiler: /snap/flutter/29/usr/bin/clang++ -- works
[   +3 ms] -- Detecting CXX compiler ABI info
[ +199 ms] -- Detecting CXX compiler ABI info - done
[   +8 ms] -- Detecting CXX compile features
[ +799 ms] -- Detecting CXX compile features - done
[   +9 ms] -- Found PkgConfig: /snap/flutter/29/usr/bin/pkg-config (found version "0.29.1") 
[   +2 ms] -- Checking for module 'gtk+-3.0'
[  +31 ms] --   Found gtk+-3.0, version 3.22.30
[ +127 ms] -- Checking for module 'glib-2.0'
[  +34 ms] --   Found glib-2.0, version 2.56.4
[  +95 ms] -- Checking for module 'gio-2.0'
[  +33 ms] --   Found gio-2.0, version 2.56.4
[ +104 ms] -- Checking for module 'blkid'
[  +27 ms] --   Found blkid, version 2.31.1
[ +111 ms] -- Configuring done
[  +15 ms] -- Generating done
[   +4 ms] -- Build files have been written to: /home/syed/Development/Flutter Demo Apps/Linux
Apps/linux_terminal/build/linux/debug
[   +8 ms] executing: ninja -C build/linux/debug install
[  +17 ms] ninja: Entering directory `build/linux/debug'
[ +674 ms] [1/6] Generating /home/syed/Development/Flutter Demo Apps/Linux
Apps/linux_terminal/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/syed/Development/Flutter Demo Apps/Linux
Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /home/syed/Development/Flutter
Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/syed/Development/Flutter
Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/syed/Development/Flutter Demo Apps/Linux
Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/syed/Development/Flutter
Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /home/syed/Development/Flutter
Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/syed/Development/Flutter Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/syed/Development/Flutter Demo Apps/Linux
Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /home/syed/Development/Flutter
Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/syed/Development/Flutter Demo Apps/Linux
Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/syed/Development/Flutter Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/syed/Development/Flutter Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/syed/Development/Flutter Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/syed/Development/Flutter Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/flutter_linux.h,
_phony_
[   +5 ms] FAILED: /home/syed/Development/Flutter Demo Apps/Linux
Apps/linux_terminal/linux/flutter/ephemeral/libflutter_linux_gtk.so /home/syed/Development/Flutter Demo Apps/Linux
Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h /home/syed/Development/Flutter
Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h /home/syed/Development/Flutter
Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_engine.h /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h /home/syed/Development/Flutter
Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h
/home/syed/Development/Flutter Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h
/home/syed/Development/Flutter Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_method_call.h
/home/syed/Development/Flutter Demo Apps/Linux
Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_method_response.h /home/syed/Development/Flutter
Demo Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h
/home/syed/Development/Flutter Demo Apps/Linux
Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h
/home/syed/Development/Flutter Demo Apps/Linux
Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_value.h /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/fl_view.h /home/syed/Development/Flutter Demo
Apps/Linux Apps/linux_terminal/linux/flutter/ephemeral/flutter_linux/flutter_linux.h flutter/_phony_
[   +7 ms] cd "/home/syed/Development/Flutter Demo Apps/Linux Apps/linux_terminal/build/linux/debug/flutter" &&
/snap/flutter/29/usr/bin/cmake -E env FLUTTER_ROOT="/home/syed/snap/flutter/common/flutter"
PROJECT_DIR="/home/syed/Development/Flutter\ Demo\ Apps/Linux\ Apps/linux_terminal" DART_OBFUSCATION="false"
TRACK_WIDGET_CREATION="true" TREE_SHAKE_ICONS="false" PACKAGE_CONFIG=".packages"
FLUTTER_TARGET="/home/syed/Development/Flutter\ Demo\ Apps/Linux\ Apps/linux_terminal/lib/main.dart"
/home/syed/snap/flutter/common/flutter/packages/flutter_tools/bin/tool_backend.sh linux-x64 Debug
[  +10 ms] Unhandled exception:
[        ] FileSystemException: Setting current working directory failed, path = '/home/syed/Development/Flutter\ Demo\
Apps/Linux\ Apps/linux_terminal' (OS Error: No such file or directory, errno = 2)
[        ] #0      _Directory.current= (dart:io/directory_impl.dart:72:7)
[        ] #1      Directory.current= (dart:io/directory.dart:189:18)
[        ] #2      main (file:///home/syed/snap/flutter/common/flutter/packages/flutter_tools/bin/tool_backend.dart:31:13)
[        ] #3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
[        ] #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
[        ] ninja: build stopped: subcommand failed.
[   +8 ms] Building Linux application... (completed in 2.9s)
[+9968 ms] Exception: Build process failed
[   +4 ms] "flutter run" took 14,792ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:612:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:985:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +255 ms] ensureAnalyticsSent: 252ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +8 ms] Shutdown hooks complete
[        ] exiting with code 1
~~~

### PR DESCRIPTION
**Pull request by jpnurmi**
## Description

Using `VERBATIM` for [`add_custom_command()`](https://cmake.org/cmake/help/latest/command/add_custom_command.html) handles escaping of paths with spaces etc. correctly as long as the manual escaping in `flutter/ephemeral/generated_config.cmake` is removed. A migrator has been added to ensure that existing projects are updated accordingly.

## Related Issues

Fixes: #67270

## Tests

Minor updates:
- test/commands.shard/hermetic/build_linux_test.dart
- test/commands.shard/hermetic/build_windows_test.dart 

Added:
- test/general.shard/migrations/cmake_project_migration_test.dart

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Are there other characters that need to be un-escaped besides spaces?

**Comment by jpnurmi** [comment]
I had a quick look. I think the full list is here: :exploding_head: 

https://github.com/Kitware/CMake/blob/master/Source/cmOutputConverter.cxx#L229-L277

**Comment by jonahwilliams** [comment]
Thats not that bad!

**Comment by jpnurmi** [comment]
Should any other of those variables be unescaped? Maybe BUNDLE_SKSL_PATH?

**Comment by jonahwilliams** [comment]
Yeah, in theory anything that is a path string could require unescaping. 

Because this will require more logic, I would actually create the unescape function in a new file in lib/src (with no dependencies). Then it can still have a unit test

**Comment by stuartmorgan** [comment]
Does adding `VERBATIM` [here](https://github.com/flutter/flutter/blob/145df3995379f5c1d3a613b249080a3b0c32a938/packages/flutter_tools/templates/app/linux.tmpl/flutter/CMakeLists.txt#L80) instead fix these? These are already quoted, so shouldn't need escaping; ideally we would just turn that behavior off.

**Comment by jpnurmi** [comment]
With `VERBATIM`:

```
$ flutter build linux -v
[   +1 ms] cd "/home/jpnurmi/Temp/foo bar/foo_bar/build/linux/release/flutter" && /usr/bin/cmake -E env FLUTTER_ROOT=\"/home/jpnurmi/Flutter\" "PROJECT_DIR=\"/home/jpnurmi/Temp/foo bar/foo_bar\""
DART_OBFUSCATION=\"false\" TRACK_WIDGET_CREATION=\"true\" TREE_SHAKE_ICONS=\"true\" "PACKAGE_CONFIG=\"/home/jpnurmi/Temp/foo bar/foo_bar/.dart_tool/package_config.json\"" FLUTTER_TARGET=\"lib/main.dart\"
/home/jpnurmi/Flutter/packages/flutter_tools/bin/tool_backend.sh linux-x64 Release
[        ] /home/jpnurmi/Flutter/packages/flutter_tools/bin/tool_backend.sh: line 9: /home/jpnurmi/Temp/foo bar/foo_bar/build/linux/release/flutter/"/home/jpnurmi/Flutter"/bin/cache/dart-sdk/bin/dart: No such file or directory
```

For reference, without `VERBATIM`:

```
[   +1 ms] cd "/home/jpnurmi/Temp/foo bar/foo_bar/build/linux/release/flutter" && /usr/bin/cmake -E env FLUTTER_ROOT="/home/jpnurmi/Flutter" PROJECT_DIR="/home/jpnurmi/Temp/foo\ bar/foo_bar"
DART_OBFUSCATION="false" TRACK_WIDGET_CREATION="true" TREE_SHAKE_ICONS="true" PACKAGE_CONFIG="/home/jpnurmi/Temp/foo\ bar/foo_bar/.dart_tool/package_config.json" FLUTTER_TARGET="lib/main.dart"
/home/jpnurmi/Flutter/packages/flutter_tools/bin/tool_backend.sh linux-x64 Release
```

**Comment by jpnurmi** [comment]
Using `VERBATIM` does the right thing as long as the manual escaping in `flutter/ephemeral/generated_config.cmake` is removed.

**Comment by stuartmorgan** [comment]
Great, that sounds like the right solution then given that the docs recommend `VERBATIM` (I just didn't see that when putting that generation code together).

File: packages/flutter_tools/lib/src/cmake.dart [hunk 1]
```diff
@@ -40,12 +40,12 @@ file(TO_CMAKE_PATH "$escapedProjectDir" PROJECT_DIR)
 
 # Environment variables to pass to tool_backend.sh
 list(APPEND FLUTTER_TOOL_ENVIRONMENT
-  "FLUTTER_ROOT=\\"$escapedFlutterRoot\\""
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/cmake.dart:43]: Will changing these paths break existing projects that don't already have VERBATIM in their templates?

Also, you need to update the test expectation for this

Comment (jpnurmi) [reply packages/flutter_tools/lib/src/cmake.dart:43]: > Will changing these paths break existing projects that don't already have VERBATIM in their templates?

I thought about the same first, but I saw that both `buildLinux()` and `buildWindows()` are unconditionally re-writing `generated_config.cmake`.

> Also, you need to update the test expectation for this

Thanks, done

Comment (stuartmorgan) [reply packages/flutter_tools/lib/src/cmake.dart:43]: > Will changing these paths break existing projects that don't already have VERBATIM in their templates?

Ugh, good point. We'll need to either write a migrator, or make this logic conditional on the presence of `VERBATIM`.

> but I saw that both `buildLinux()` and `buildWindows()` are unconditionally re-writing `generated_config.cmake`.

Right, but the problem is that `CMakeLists.txt` is only created at `flutter create`-time, and that's where the VERBATIM needs to be added.

Comment (jpnurmi) [reply packages/flutter_tools/lib/src/cmake.dart:43]: Right. What kind of migrator did you have in mind? I wonder if it's really worth the trouble. Perhaps going back to the earlier solution (unescaping `'\ '`) would be good enough? It fixes the most common case in a simple and backward-compatible way.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/cmake.dart:43]: The tool already has a migrator API used for iOS but not yet for linux.

See https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/migrations/ios_migrator.dart and https://github.com/flutter/flutter/blob/f865ac7e259d320d7e565f887f894f293a463782/packages/flutter_tools/lib/src/ios/migrations/xcode_build_system_migration.dart#L13

**Comment by jpnurmi** [comment]
WIP: missing Windows & tests

**Comment by jpnurmi** [comment]
Alright, this is ready for another round of reviews.

Where do you prefer the have shared CMake migrators and tests for Linux & Windows?

**Comment by jpnurmi** [comment]
Rebased. https://github.com/flutter/flutter/pull/71757 applied similar migrator changes to make it available on all platforms.

**Comment by jmagman** [comment]
> Rebased. #71757 applied similar migrator changes to make it available on all platforms.

Thanks for noticing this, I meant to comment here.  The migration part LGTM.

@jonahwilliams is OOO.  @stuartmorgan does the actual `VERBATIM` part of this PR look good?  Can I merge it?

File: packages/flutter_tools/test/commands.shard/hermetic/build_linux_test.dart [hunk 2]
```diff
@@ -362,17 +362,17 @@ clang: error: linker command failed with exit code 1 (use -v to see invocation)
...
+      r'  "DART_OBFUSCATION=true"',
+      r'  "EXTRA_FRONT_END_OPTIONS=--enable-experiment%3Dnon-nullable"',
+      r'  "EXTRA_GEN_SNAPSHOT_OPTIONS=--enable-experiment%3Dnon-nullable"',
+      r'  "SPLIT_DEBUG_INFO=foo/"',
+      r'  "TRACK_WIDGET_CREATION=true"',
+      r'  "TREE_SHAKE_ICONS=true"',
+      '  "FLUTTER_ROOT=$_kTestFlutterRoot"',
+      '  "PROJECT_DIR=${fileSystem.currentDirectory.path}"',
+      r'  "FLUTTER_TARGET=lib/other.dart"',
+      r'  "BUNDLE_SKSL_PATH=foo/bar.sksl.json"',
```
Comment (stuartmorgan) [inline packages/flutter_tools/test/commands.shard/hermetic/build_linux_test.dart:375]: Nit: you should be able to drop all the `r` prefixes here; they were to simplify the quote escaping.

**Review by stuartmorgan-g — APPROVED** [review]
Sorry, I too was OOO. The actual CMake changes here LGTM; someone else should review the migrator code, then it's good to land.

**Review by jmagman — APPROVED** [review]
