### PR TITLE
Correctly synthesise event buttons

### LINKED ISSUE #30532: Incorrect `buttons` value for mouse events
https://github.com/flutter/flutter/pull/30457 introduces a bug where all mouse buttons will have `0x01` incorrectly set, even when only other buttons are pressed. (See https://github.com/flutter/flutter/pull/30457/files#r272393824)

I'm fixing it ASAP.

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

#30457 introduces a bug where all mouse buttons will have 0x01 incorrectly set, specifically when buttons other than left are pressed. (See https://github.com/flutter/flutter/pull/30457/files#r272393824)

This PR correctly synthesises buttons based on device.

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/30532

## Tests

I added the following tests:
- Should synthesise kPrimaryButton for touch
- Should synthesise kPrimaryButton for stylus
- Should not synthesise kPrimaryButton for mouse

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/gestures/converter.dart [hunk 1]
```diff
@@ -40,6 +40,22 @@ class _PointerState {
...
+// https://github.com/flutter/flutter/issues/30454
+int _synthesiseDownButtons(int buttons, PointerDeviceKind kind) {
+  switch (kind) {
+  case PointerDeviceKind.touch:
+  case PointerDeviceKind.stylus:
+  case PointerDeviceKind.invertedStylus:
+    return buttons | kPrimaryButton;
+  default:
+    return buttons;
+  }
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/converter.dart]: indent the body of the switch by 2

**Comment by Hixie** [comment]
LGTM
