### PR TITLE
Fix CupertinoAlertDialog TextStyle

### LINKED ISSUE #55059: CupertinoAlertDialog does not look native
## Steps to Reproduce

`main.dart`
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: <Widget>[
            RaisedButton(
              onPressed: _showNativeDialog,
              child: Text('Native'),
            ),
            RaisedButton(
              onPressed: _showFlutterDialog,
              child: Text('Flutter'),
            ),
          ],
        ),
      ),
    );
  }

  void _showNativeDialog() {
    ImagePicker.pickImage(source: ImageSource.camera);
  }

  void _showFlutterDialog() {
    showCupertinoDialog(
      context: context,
      builder: (BuildContext context) {
        return CupertinoAlertDialog(
          title: Text('“flutterapp” Would Like to Access the Camera'),
          content: Text('Allow camera access for taking photos'),
          actions: <Widget>[
            CupertinoDialogAction(
              onPressed: _back,
              child: Text('Don′t Allow'),
            ),
            CupertinoDialogAction(
              isDefaultAction: true,
              onPressed: _back,
              child: Text('OK'),
            ),
          ],
        );
      },
    );
  }

  void _back() {
    Navigator.of(context).pop();
  }
}
```

**Expected results:** 
CupertinoAlertDialog should look native.

**Actual results:** 
Letters are spaced too far apart. Title and content are too close.
| Native | Flutter |
| --- | --- |
| IMG_0083 | IMG_0084 |

<details>
  <summary>Logs</summary>

`flutter doctor -v`

```
[✓] Flutter (Channel master, v1.18.0-6.0.pre.66, on Mac OS X 10.15.4 19E287, locale en-PL)
    • Flutter version 1.18.0-6.0.pre.66 at /Users/tomasz/development/flutter
    • Framework revision bec63a54bf (3 hours ago), 2020-04-17 08:54:48 -0700
    • Engine revision f4d6ce13dc
    • Dart version 2.8.0 (build 2.8.0-dev.20.7 5900a0ac49)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tomasz/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/tomasz/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/tomasz/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • Tomasz’s iPhone • 00008030-000D19860C12603E • ios            • iOS 13.4.1
    • Chrome          • chrome                    • web-javascript • Google Chrome 80.0.3987.163
    • Web Server      • web-server                • web-javascript • Flutter Tools

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by JuYeong0413**
## Description

Fix `CupertinoAlertDialog` `TextStyle` to look more native. (Edited `fontSize`, `height`, `letterSpacing`.)
<details>
<summary>Reproducible code sample</summary>

  ```dart
  import 'dart:io';
  import 'package:flutter/cupertino.dart';
  import 'package:flutter/material.dart';
  import 'package:image_picker/image_picker.dart';

  void main() => runApp(MyApp());

  class MyApp extends StatelessWidget {
    @override
    Widget build(BuildContext context) {
      return MaterialApp(
        home: MyHomePage(),
      );
    }
  }

  class MyHomePage extends StatefulWidget {
    @override
    _MyHomePageState createState() => _MyHomePageState();
  }

  class _MyHomePageState extends State<MyHomePage> {
    File _image;
    final picker = ImagePicker();

    Future _showNativeDialog() async {
      final pickedFile = await picker.getImage(source: ImageSource.camera);
    }
  
    @override
    Widget build(BuildContext context) {
      return Scaffold(
        body: SafeArea(
          child: Column(
            children: <Widget>[
              RaisedButton(
                onPressed: _showNativeDialog,
                child: Text('Native'),
              ),
              RaisedButton(
                onPressed: _showFlutterDialog,
                child: Text('Flutter'),
              ),
            ],
          ),
        ),
      );
    }

    void _showFlutterDialog() {
      showCupertinoDialog(
        context: context,
        builder: (BuildContext context) {
          return CupertinoAlertDialog(
            title: Text('“sampleapp” Would Like to Access the Camera'),
            content: Text('Allow camera access for taking photos'),
            actions: <Widget>[
              CupertinoDialogAction(
                onPressed: _back,
                child: Text('Don′t Allow'),
              ),
              CupertinoDialogAction(
                isDefaultAction: true,
                onPressed: _back,
                child: Text('OK'),
              ),
            ],
          );
        },
      );
    }

    void _back() {
      Navigator.of(context).pop();
    }
  }
  ```
</details>

| Before | Native Dialog | After |
|---|---|---|
|  |  |  |

### Golden test image
| dialog_test.cupertino.default.png |
|---|
|  |

I used [XD to Flutter plugin](https://github.com/AdobeXD/xd-to-flutter-plugin) to derive values of cupertino dialog from [Adobe XD template for iOS 13](https://developer.apple.com/design/resources/). Then I compared visually to make the dialog look more similar to native one.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/55059

## Tests

None

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by JuYeong0413** [comment]
One test in `dialog_test.dart` is failing - Message is scrollable, has correct padding with large text sizes.
https://github.com/flutter/flutter/blob/780f5f99044ce7fcbcd868e2cf6878da02022db5/packages/flutter/test/cupertino/dialog_test.dart#L323
Only this line is getting failure.
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: Size:<Size(270.0, 162.0)>
  Actual: _DebugSize:<Size(270.0, 132.0)>
```
Seems like this failure is due to change of the dialog title font size. This pull request only changes the style of dialog, but since the test is failing, should this be a breaking change?

**Comment by LongCatIsLooong** [comment]
@JuYeong0413 thanks for the PR! According to the [updated breaking change policy](https://github.com/flutter/flutter/wiki/Tree-hygiene#1-determine-if-your-change-is-a-breaking-change), the PR is not a breaking change if it only breaks existing tests. 

You might still need to add tests for these changes. It seems we don't have golden tests for cupertino dialogs so adding one would be great. Instructions for adding golden tests can be found here: https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

**Comment by skia-gold** [comment]
Gold has detected about 2 untriaged digest(s) on patchset 6.
View them at https://flutter-gold.skia.org/cl/github/64468

**Comment by JuYeong0413** [comment]
Thank you @LongCatIsLooong! I've revised the failing part and added golden test. The image is in the description. :)
Could you please take a look?

File: packages/flutter/lib/src/cupertino/dialog.dart [hunk 1]
```diff
@@ -21,19 +21,20 @@ import 'scrollbar.dart';
 const TextStyle _kCupertinoDialogTitleStyle = TextStyle(
   fontFamily: '.SF UI Display',
   inherit: false,
-  fontSize: 18.0,
+  fontSize: 17.0,
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/dialog.dart:24]: The font size change here (and the one below) looks good to me. It matches what I saw in Xcode too. I'm not sure how the rest of them (height and letterSpacing) are derived. Could you document where these values came from (similar to https://github.com/flutter/flutter/issues/21302)? This will help other maintainers when they revise these values.

**Review by LongCatIsLooong — COMMENTED** [review]
Thank you for the pull request, and for providing a visual comparison! Then end result looks a lot better :+1: . But it's a bit difficult to review since I can't figure out for myself how these values are derived (except for font size). Would you mind documenting that in code comments?

**Comment by JuYeong0413** [comment]
I've added how I derived the values in the description yesterday-it's under the golden test image. Seems like it's easy to miss, so I'll move it to the top. 🙂 
> I used [XD to Flutter plugin](https://github.com/AdobeXD/xd-to-flutter-plugin) to derive values of cupertino dialog from [Adobe XD template for iOS 13](https://developer.apple.com/design/resources/). Then I compared visually to make the dialog look more similar to native one.

File: packages/flutter/lib/src/cupertino/dialog.dart (hunk 1 above)
Comment (JuYeong0413) [reply packages/flutter/lib/src/cupertino/dialog.dart:29]: Sure! I've added code comments.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/cupertino/dialog.dart:29]: You are saying the values are from the said plugin, but you had to make some adjustments?

**Review by LongCatIsLooong — APPROVED** [review]
LGTM. Thank you for contributing!

File: packages/flutter/lib/src/cupertino/dialog.dart (hunk 1 above)
Comment (JuYeong0413) [reply packages/flutter/lib/src/cupertino/dialog.dart:29]: Yup, that's right. Some rounding off and visual comparison is needed.
What I got from the plugin:
* Title
```dart
fontSize: 17,
letterSpacing: -0.544, // Rounded up to -0.5
height: 1.2941176470588236, // Rounded up to 1.3
```
* Content
```dart
fontSize: 13,
letterSpacing: -0.10400000000000001,
height: 1.2307692307692308,
```
The title `TextStyle` is okay, but content `TextStyle` needed adjustments.
When rounded `letterSpacing` and `height` of content to -0.1 and 1.2, the result looks like below.
| Before | Native Dialog | Before adjustments | After adjustments |
|---|---|---|---|
|  |  |  | |

**Comment by JuYeong0413** [comment]
Is there anything I should do about the failing framework tests? Seems like it's related to new golden test I've added.

**Comment by LongCatIsLooong** [comment]
Rerunning the tests.

**Comment by JuYeong0413** [comment]
Linux test passed, macos still failing. 🤔 
The log says:
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: one widget whose rasterized image matches golden image
"dialog_test.cupertino.default.png"
  Actual: _WidgetTypeFinder:<exactly one widget with type "CupertinoAlertDialog" (ignoring offstage
widgets): CupertinoAlertDialog(dependencies: [_LocalizationsScope-[GlobalKey#299ca], MediaQuery])>
   Which: does not match

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/frontend/expect.dart:155:31)
#1      _expect.<anonymous closure> (package:test_api/src/frontend/expect.dart:130:9)
#13     MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart)
<asynchronous suspension>
#14     MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart)
#15     AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:1003:22)
#18     AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:1001:26)
#19     MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:72:20)
#20     _expect (package:test_api/src/frontend/expect.dart:119:26)
#21     expectLater (package:test_api/src/frontend/expect.dart:75:5)
#22     expectLater (package:flutter_test/src/widget_tester.dart:468:10)
#23     main.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter/test/cupertino/dialog_test.dart:1175:11)
#34     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:193:32)
#35     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1189:17)
#36     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1177:35)
(elided 38 frames from dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  Default cupertino dialog golden
════════════════════════════════════════════════════════════════════════════════════════════════════

01:58 +1988 ~12 -1: /private/tmp/flutter sdk/packages/flutter/test/cupertino/dialog_test.dart: Default cupertino dialog golden [E]                                                                     
  Test failed. See exception logs above.
  The test description was: Default cupertino dialog golden
```

**Comment by LongCatIsLooong** [comment]
Could you try pulling from the latest `upstream/master` and see if that helps?

**Comment by skia-gold** [comment]
Gold has detected about 1 untriaged digest(s) on patchset 11.
View them at https://flutter-gold.skia.org/cl/github/64468

**Comment by JuYeong0413** [comment]
Great, now it's passing. The outdated branch was the problem. Thank you!

**Comment by LongCatIsLooong** [comment]
FYI the google testing failure does not seem related. I'll retry the test to see if it was a flake.
