### PR TITLE
[flutter_tools] fix performance of tree-shake-icons

### LINKED ISSUE #53240: icon_tree_shaker.dart causes dead code diagnostic
The location https://github.com/flutter/flutter/blob/0c5ffdc9efc4e04ed637645014465b656afc14a5/packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart#L191
gives rise to a `dead_code_on_catch_subtype` diagnostic:

```
   info • Dead code: This on-catch block won’t be executed because 'OSError' is a subtype of 'Exception' and hence will have been caught already • packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart:191:7 • dead_code_on_catch_subtype
```

The second `catch` clause is unreachable and should be deleted.

### LINKED ISSUE #55370: --shrink --tree-shake-icons causes huge system load, causing CI Runners to fail
My setup:

- My CI Gitlab CI, using a Mac Mini as Runner to run the flutter builds
- I want to build release artifacts with `--tree-shake-icons` and `--shrink`

Starting a build with` --tree-shake-icons --shrink` causes a huge load on my system.
If run it on my local workstation, I get load averages like this (from `uptime`): (load averages: `397.06 239.44 116.03` ! ).

On the build machine, I cannot get load averages easily as that my ssh session freezes when the build is running.

The system gets unresponsive during the build because of that.

On the CI, this causes my builds to fail because the CI server thinks that the Runners crashed (My guess is that there is some ping mechanism that fails because of the huge load that the flutter builds cause).

I think it would be nice if there were a build option like `--low-resource-mode`, that would take longer to finish the build, but cause lower strain on the system during the build (e.g. by spawning fewer threads or using a lower priority), making sure the system stays responsive during the build.

```
./flutterw doctor -v
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0 at /Users/kami/diagnosia/neocortex-mobile/.flutter
    • Framework revision d3ed9ec945 (2 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kami/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/kami/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes the performance issue with tree-shake-icons and filters to ttf mime type. Does not change default or error behavior.

Fixes https://github.com/flutter/flutter/issues/53240 
Fixes https://github.com/flutter/flutter/issues/55370

### CODE REVIEW

**Comment by jonahwilliams** [comment]
@dnfield could we possibly loosen some of the error cases to make this non-breaking? Specifically, we could allow (with a warning) the case where the kernel still contains references to icons that don't exist as assets

File: packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart [hunk 1]
```diff
@@ -119,12 +127,14 @@ class IconTreeShaker {
     );
 
     if (fonts.length != iconData.length) {
-      throwToolExit('Expected to find fonts for ${iconData.keys}, but found '
-                    '${fonts.keys}. This usually means you are refering to '
-                    'font families in an IconData class but not including them '
-                    'in the assets section of your pubspec.yaml, are missing '
-                    'the package that would include them, or are missing '
-                    '"uses-material-design: true".');
+      _logger.printError(
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart:130]: I'm not sure if this breaks any invariants. It might also need to be a trace event

**Comment by dnfield** [comment]
If a kernel has references to a font that isn't present, that's a bug. The fact that we're failing earlier should not be considered a breaking change IMO - if you try to use an icon from a non-existant font, you'll get undefined behavior at runtime. You'll end up with either an arbitrary character from a fallback font, or (more likely), a replacement character or some garbage in your application.

**Comment by jonahwilliams** [comment]
For now we'll need to disable for web then.

On the other side, I disagree that it is a bug. There are plenty of code patterns that would lead to icons being retained but not actually used. For example, a pattern like the following will not tree shake:

```
Widget build(BuildContext context) {
  switch (data) {
    case 'material':
       return WidgetWithMaterialIcon();
     case 'cupertino':
       return WidgetWithCupertinoIcon();
  }
}
```

If data comes from an API endpoint, the compiler will never be able to remove the cupertino path. Despite that, the author may know with certainty that their endpoint will always return `material`. In fact, this code could be present in a third party dependency of that authors code in such a way that is not obvious. 

Is tree-shake-icons a way to reduce bundle size, or an icon usage linter? Its going to be very difficult to roll out both of these at once. If you really want the later behavior I would strongly consider staging that as a warning first and doing a gradual breaking change.

**Comment by jonahwilliams** [comment]
And I'm also concerned that we'd be really depending on the specific implementation of tree shaking, despite the fact that the Dart team has provided no formal guidance or guarantees on how it applies: https://github.com/dart-lang/sdk/issues/33920

**Comment by dnfield** [comment]
Someone who wants to use that pattern cannot tree shake thier icons. They would have to opt out.  Perhaps we could make this just print a warning and opt them out, and the warning could be suppressed if they explicitly opted out.

As far as implementation details go, I'm not sure what else to do there. The only concern would be if they changed the way apt/tfa const evaluation worked.  That seems pretty safe to me.

**Comment by dnfield** [comment]
I think we should just let them know that their icon fonts cannot be shaken given the state of their code. We could create a wiki or doc page explaining that for Icons to be shakeable, they have to be const, and that any reachable code has to include the referenced font.

**Comment by jonahwilliams** [comment]
FYI @zanderso

**Comment by jonahwilliams** [comment]
Updated to not adjust the error behavior for now

**Review by zanderso — APPROVED** [review]
lgtm

So, tree shaking fonts is still off by default, and when it is turned on by default, it will still be off for Web, correct? Is there an issue tracking what the story is for web?

**Comment by jonahwilliams** [comment]
Yes, its still off by default. Whether or not we can turn it on for web depends on the outcome of a discussion involving @dnfield when he gets back
