### PR TITLE
SliverAppBar Default Elevation Patch

### LINKED ISSUE #73525: SliverAppBar does not respect Theme's AppBar elevation
## Steps to Reproduce

1. Create a page which uses a SliverAppBar.
2. Make the SliverAppBar elevated by:
  a. Setting "forceElevated" to true.
  b. Or setting "pinned" to true and providing enough content in the CustomScrollView to allow scrolling.
3. Wrap the page in a Theme which specifies an AppBar elevation different from the default. (ie 24.0)

**Expected results:** 
When no elevation is explicitly given to the SliverAppBar, it should follow the AppBarTheme.

**Actual results:** 
When SliverAppBar is elevated, it does not respect the value provided by the AppBarTheme. It will always use 4.0.

<details><summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Theme(
        data: Theme.of(context).copyWith(
          appBarTheme: AppBarTheme(
            elevation: 24.0, // The SliverAppBar should use this if no elevation is specified
          ),
        ),
        child: CustomScrollView(
          slivers: <Widget>[
            SliverAppBar(
              title: Text(widget.title),
              forceElevated: true,
              //elevation: 24.0,
              // Uncommenting this line demonstrates the difference
              // in appearance if the Theme were properly used.
            ),
            SliverList(
              delegate: SliverChildListDelegate([
                Text(
                  'You have pushed the button this many times:',
                ),
                Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headline4,
                ),
              ]),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```
</details>

<details>
  <summary>Logs</summary>

flutter analyze
```
Analyzing sliverappbar...
No issues found! (ran in 18.4s)
```

flutter doctor -v
```
[√] Flutter (Channel master, 1.26.0-2.0.pre.240, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.26.0-2.0.pre.240 at d:\Developer\flutter
    • Framework revision 4ffc8f9da9 (2 hours ago), 2021-01-07 15:36:21 -0800
    • Engine revision 2e5833b7c5
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\Developer\Android\SDK
    • Platform android-30, build-tools 30.0.1
    • ANDROID_SDK_ROOT = D:\Developer\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.685]
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by NWalker1208**
This PR is super simple. The SliverAppBar, when it creates the embedded AppBar widget, would before pass a fixed elevation of 4.0 if no other elevation was provided to it. This means that the AppBarTheme would be ignored if it specified it's own default elevation. This PR simply removes the operator that caused the SliverAppBar to default to 4.0. It now will instead pass an elevation of null to the AppBar, which causes the AppBar to use the elevation provided by the theme.

*List which issues are fixed by this PR. You must list at least one issue.*

Fixes #73525

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

Added the "SliverAppBar uses elevation of AppBarTheme" test to app_bar_test.dart.

I made a slight modification to the "SliverAppBar rebuilds when forceElevated changes" test in app_bar_test.dart. Instead of expecting a specific elevation of 4.0 on the embedded AppBar widget, it expects null, which means the AppBar is using the AppBarTheme elevation if an AppBarTheme is defined. Otherwise, it uses the default elevation defined by AppBar. I also added a line to check that providing a specific elevation is properly reflected in the AppBar widget.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by MrBirb** [comment]
cc @perclasson who wrote that test

**Comment by NWalker1208** [comment]
Here is the commit where the old test was introduced: https://github.com/flutter/flutter/commit/8cf15ee2aa25f91908478de99ffc7b8fe522b6b7
From what I can tell, the purpose of the test was to make sure that changing forceElevated caused the elevation of the AppBar to change. It doesn't look like it was intended to enforce an elevation of 4.0 as the default, even though that was a side effect of that test.

File: packages/flutter/test/material/app_bar_test.dart [hunk 1]
```diff
@@ -926,6 +927,9 @@ void main() {
     expect(getAppBarWidget(appBarFinder).elevation, 0.0);
 
     await tester.pumpWidget(buildSliverAppBar(true));
+    expect(getAppBarWidget(appBarFinder).elevation, null);
+
+    await tester.pumpWidget(buildSliverAppBar(true, 4.0));
     expect(getAppBarWidget(appBarFinder).elevation, 4.0);
   });
```
Comment (perclasson) [inline packages/flutter/test/material/app_bar_test.dart:934]: @NWalker1208 I think it's better if you add a new test, maybe called 'SliverAppBar uses elevation from AppBarTheme' where you set the custom elevation etc. Then you actually test that the Material (`getMaterialWidget`) has an elevation, rather then the appBarWidget. You can keep the changes to this test.

Add a comment that it is a regression test for your issue. Otherwise it LGTM, I would ping someone from the Flutter team to review it.

**Review by perclasson — COMMENTED** [review]
LGTM also ask someone from the Flutter team to review

File: packages/flutter/test/material/app_bar_test.dart (hunk 1 above)
Comment (NWalker1208) [reply packages/flutter/test/material/app_bar_test.dart:934]: Thanks for the suggestion, I've added the test

**Comment by NWalker1208** [comment]
@HansMuller Just checking in, have you been able to take a look at this PR yet?

File: packages/flutter/test/material/app_bar_test.dart [hunk 2]
```diff
@@ -926,9 +927,43 @@ void main() {
     expect(getAppBarWidget(appBarFinder).elevation, 0.0);
 
     await tester.pumpWidget(buildSliverAppBar(true));
+    expect(getAppBarWidget(appBarFinder).elevation, null);
```
Comment (shihaohong) [inline packages/flutter/test/material/app_bar_test.dart:930]: We'll need to add a little more to this test:

The main problem is that we haven't verified that SliverAppBar sets the default value of `elevation` to `4.0` when elevation and AppBarTheme.elevation are null: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/app_bar.dart#L370.

Meaning, we also need the test to prove that the following priority order is preserved:
SliverAppBar.elevation > AppBarTheme.elevation > default value of 4. Currently, it just shows that `SliverAppBar.elevation`'s value is null, which doesn't tell us what elevation is actually painted by default.

So, we need to add more to the test to prove that the correct elevation is still painted by the AppBar onto `Material`, since it doesn't verify that the default. Here is how [an AppBarTheme test does it](https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/app_bar_theme_test.dart#L27).

**Review by shihaohong — COMMENTED** [review]
Need some test modifications to make sure that the default elevation value is preserved. Otherwise, the change looks good!

**Comment by shihaohong** [comment]
Also, you'll likely need to rebase this branch with `master`. Some problems cropped up with CI over the last few weeks and I have a feeling that without rebasing the checks will fail after adding new commits to the PR.

File: packages/flutter/test/material/app_bar_test.dart (hunk 2 above)
Comment (NWalker1208) [reply packages/flutter/test/material/app_bar_test.dart]: Okay. I've modified the tests to check for an default elevation of 4.0 on the Material widget. Ideally, I would have referenced the constant inside _AppBarState, but because it's private, I had to hardcode the value of 4.0. This is also what the AppBarTheme test does that you linked to. I still have it check if the AppBar itself has an elevation of null, since that means that SliverAppBar allowed it to decide it's own elevation.

**Comment by NWalker1208** [comment]
@shihaohong I've made the changes you requested. Does everything else look good to you?

File: packages/flutter/test/material/app_bar_test.dart [hunk 3]
```diff
@@ -903,30 +903,92 @@ void main() {
...
+    // SliverAppBar should use the specified elevation.
+    await tester.pumpWidget(buildSliverAppBar(true, 8.0));
+    expect(getMaterial().elevation, 8.0);
+  });
+
+  testWidgets('SliverAppBar uses elevation of AppBarTheme', (WidgetTester tester) async {
+    // Regression test for https://github.com/flutter/flutter/issues/73525.
+    const double themeElevation = 12.0;
+
+    Widget buildSliverAppBar(bool forceElevated, double elevation) {
```
Comment (Piinks) [inline packages/flutter/test/material/app_bar_test.dart:968]: The common methods here could be broken out and shared to reduce boilerplate. You can `group` common tests to share methods like this. Example: https://github.com/flutter/flutter/blob/a2a77285dceaed7fcc284f8c0abfdb511f1c545e/packages/flutter/test/material/floating_action_button_location_test.dart#L611

**Review by Piinks — COMMENTED** [review]
This is a great fix! Nice! If we could reduce the code duplication in the tests this is good to go. :)

**Review by Piinks — APPROVED** [review]
LGTM! Thanks for the contribution!
