### PR TITLE
[Api Docs] Improves contentPadding documentation in InputDecoration

### LINKED ISSUE #50991: InputDecoration's contentPadding defaults are unspecified in the API docs
## Steps to Reproduce

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Flexible(
              child: TextFormField(
                decoration: InputDecoration(
                  contentPadding: EdgeInsets.only(left: 1),
                  border: OutlineInputBorder(),
                ),
              ),
            ),
            Flexible(
              child: TextFormField(
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
```

**Expected results:** 

Two `TextFormFields` of equal height with whatever `contentPadding` I specify.

**Actual results:** 

textFormField

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel master, v1.15.4-pre.90, on Mac OS X 10.15.3 19D76, locale
    en-US)
    • Flutter version 1.15.4-pre.90 at
      /Users/albertlardizabal/dev/flutter/test/flutter
    • Framework revision 89ff794ac8 (55 minutes ago), 2020-02-18 11:31:04 -0800
    • Engine revision d60f298d9e
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 edd64e6d5c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/albertlardizabal/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
```

</details>

### PR DESCRIPTION
**Pull request by AyushBherwani1998**
## Description

Improves the `contentPadding` documentation in `InputDecoration` by adding documentation for default values of `contentPadding` .

## Related Issues
Fixes: #50991

## Tests

I added the following tests:
Since only documentation is updated, no test cases are added.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -2729,8 +2729,12 @@ class InputDecoration {
...
   ///
   /// By default the `contentPadding` reflects [isDense] and the type of the
-  /// [border]. If [isCollapsed] is true then `contentPadding` is
-  /// [EdgeInsets.zero].
+  /// [border]. If the [border] is [OutlineInputBorder] then `contentPadding` is
+  /// `EdgeInsets.LTRB(12, 24, 12, 16)`. If the [border] is [UnderlineInputBorder]
+  /// or [InputBorder.none] then `contentPadding` is `EdgeInsets.LTRB(0, 12, 0, 12)`.
+  /// If the [border] is [UnderlineInputBorder] or [InputBorder.none] and if
+  /// [filled] is true then `contentPadding` is `EdgeInsets.LTRB(12, 12, 12, 12)`.
+  /// If [isCollapsed] is true then `contentPadding` is [EdgeInsets.zero].
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/input_decorator.dart]: I think that the existing wording could use some work as well. The documentation assumes that by default, padding is applied where `isDense` is true. I think we should just lay it out as the code says so that people aren't confused by the behavior here.

```
When `contentPadding` is not specified, its default value depend on the type 
of [border] used, the value of [isDense], and the value of [isCollapsed].

When [isCollapsed] is true, the content padding defaults to [EdgeInsets.zero]. 

When [border.isOutline] is false and [filled] is true, then content padding will 
be set to `EdgeInsets.fromLTRB(12, 8, 12, 8)` when [isDense] is true and 
`EdgeInsets.fromLTRB(12, 12, 12, 12)` when [isDense] is false. When 
[border.isOutline] is false and [filled] is false, then content padding will 
be the same as above, but without the left and right padding.

When [border.isOutline] is true, then content padding will be set 
to `EdgeInsets.fromLTRB(12, 20, 12, 12)` when [isDense] is true
and `EdgeInsets.fromLTRB(12, 24, 12, 16)` when [isDense] is false.
```

Let me know what you think, but definitely give your suggestions and only make modifications as you see fit :)

Comment (AyushBherwani1998) [reply packages/flutter/lib/src/material/input_decorator.dart]: I think you are right, the first statement is ambiguous. We can list out all the possible default values of `contentPaddding`

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 2]
```diff
@@ -2729,12 +2729,20 @@ class InputDecoration {
...
-  /// [border]. If the [border] is [OutlineInputBorder] then `contentPadding` is
-  /// `EdgeInsets.LTRB(12, 24, 12, 16)`. If the [border] is [UnderlineInputBorder]
-  /// or [InputBorder.none] then `contentPadding` is `EdgeInsets.LTRB(0, 12, 0, 12)`.
-  /// If the [border] is [UnderlineInputBorder] or [InputBorder.none] and if
-  /// [filled] is true then `contentPadding` is `EdgeInsets.LTRB(12, 12, 12, 12)`.
+  /// [border].
+  ///
   /// If [isCollapsed] is true then `contentPadding` is [EdgeInsets.zero].
+  ///
+  /// If [InputBorder.isOutline] is false and [filled] is true then
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/input_decorator.dart]: We might want to still link this into [border] somehow so people know the parameter to set. Maybe:
```suggestion
  /// If [border]'s [InputBorder.isOutline] property is false and [filled] is true then
```

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 3]
```diff
@@ -2729,12 +2729,20 @@ class InputDecoration {
...
+  /// `contentPadding` is `EdgeInsets.fromLTRB(12, 8, 12, 8)` when [isDense]
+  /// is true and `EdgeInsets.fromLTRB(12, 12, 12, 12)` when [isDense] is false`.
+  /// If [InputBorder.isOutline] is false and [filled] is false then
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/input_decorator.dart]: ditto

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 4]
```diff
@@ -2729,12 +2729,20 @@ class InputDecoration {
...
+  /// `contentPadding` is `EdgeInsets.fromLTRB(0, 8, 0, 8)` when [isDense] is
+  /// true and `EdgeInsets.fromLTRB(0, 12, 0, 12)` when [isDense] is false`.
+  ///
+  /// If [InputBorder.isOutline] is true then `contentPadding` is
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/input_decorator.dart]: ditto

**Review by shihaohong — APPROVED** [review]

**Comment by AyushBherwani1998** [comment]
Thank you @shihaohong for helping out :)

**Comment by shihaohong** [comment]
No problem! Thank you for being timely with responding to feedback!
