### PR TITLE
[web] Gracefully handle empty ui.Vertices

### LINKED ISSUE #160355: Creating an empty `Vertices` object causes an exception on web (canvaskit)
## Description

If you attempt to create a Vertices object which doesn't have any vertices in it, the following exception is thrown, which didn't use to be the case.  This is currently blocking the Flutter roll, see cl/705912913 for details.

```
DartError: TypeError: null: type 'Null' is not a subtype of type 'JavaScriptObject'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 307:3  throw_
errors.dart:307
dart-sdk/lib/_internal/js_dev_runtime/private/profile.dart 117:39            _failedAsCheck
profile.dart:117
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1554:3                         _generalAsCheckImplementation
rti.dart:1554
dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 110:3                callMethod$
js_util_patch.dart:110
lib/_engine/engine/canvaskit/canvaskit_api.dart 95:8                         CanvasKitExtension.MakeVertices
canvaskit_api.dart:95
lib/_engine/engine/canvaskit/vertices.dart 82:45                             __
vertices.dart:82
lib/_engine/engine/canvaskit/vertices.dart 66:23                             raw
vertices.dart:66
lib/_engine/engine/canvaskit/renderer.dart 124:18                            createVerticesRaw
renderer.dart:124
lib/ui/canvas.dart 45:28                                                     raw
canvas.dart:45
packages/manual_tests/simple_test.dart 7:41                                  main
simple_test.dart:7
web_entrypoint.dart 24:31                                                    <fn>
web_entrypoint.dart:24
lib/ui_web/ui_web/initialization.dart 41:15                                  <fn>
initialization.dart:41
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 622:19          <fn>
async_patch.dart:622
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 647:23          <fn>
async_patch.dart:647
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 593:31          <fn>
async_patch.dart:593
dart-sdk/lib/async/zone.dart 1849:54                                         runUnary
zone.dart:1849
dart-sdk/lib/async/future_impl.dart 208:18                                   handleValue
future_impl.dart:208
dart-sdk/lib/async/future_impl.dart 932:44                                   handleValueCallback
future_impl.dart:932
dart-sdk/lib/async/future_impl.dart 961:13                                   _propagateToListeners
future_impl.dart:961
dart-sdk/lib/async/future_impl.dart 712:5                                    [_completeWithValue]
future_impl.dart:712
dart-sdk/lib/async/future_impl.dart 792:7                                    callback
future_impl.dart:792
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
schedule_microtask.dart:40
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
schedule_microtask.dart:49
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 186:7           <fn>
async_patch.dart:186
```

Here's a simple reproduction case:

```dart
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  final ui.Vertices verts = ui.Vertices.raw(
    VertexMode.triangles,
    Float32List(0),
    indices: Uint16List(0),
    textureCoordinates: Float32List(0),
  );
  print('$verts');

  runApp(const SizedBox.shrink());
}
```

### PR DESCRIPTION
**Pull request by harryterkelsen**
It is valid to create a `ui.Vertices` object with empty positions. This fixes Flutter Web so we don't crash when we see an empty `ui.Vertices` object.

Fixes https://github.com/flutter/flutter/issues/160355

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/html/render_vertices.dart [hunk 1]
```diff
@@ -50,6 +50,8 @@ class SurfaceVertices implements ui.Vertices {
     return list;
   }
 
+  bool get isEmpty => positions.isEmpty;
```
Comment (yjbanov) [inline engine/src/flutter/lib/web_ui/lib/src/engine/html/render_vertices.dart:53]: nit: There could be several empty things: positions, colors, indices. Just `isEmpty` doesn't seem specific enough?

**Review by yjbanov — APPROVED** [review]

File: engine/src/flutter/lib/web_ui/lib/src/engine/html/render_vertices.dart (hunk 1 above)
Comment (harryterkelsen) [reply engine/src/flutter/lib/web_ui/lib/src/engine/html/render_vertices.dart]: Renamed to `hasNoPoints` for clarity
