### PR TITLE
Fix NavigationBar indicator overlay color

### LINKED ISSUE #163871: NavigationBar lacks visual feedback when focused using keyboard on any platform, or when touched on mobile devices
### Steps to reproduce

1. Create an app that uses `NavigationBar`
2. Touch, hover, or focus on the different destinations

### Expected results

All destinations, including the selected destination, should give visual feedback when touched, focused, or hovered.

### Actual results

Unselected destinations have appropriate visual feedback, but the selected destination doesn't.

### Code sample

<details open><summary>Code sample</summary>

Note: this is directly copied from https://api.flutter.dev/flutter/material/NavigationBar-class.html

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [NavigationBar].

void main() => runApp(const NavigationBarApp());

class NavigationBarApp extends StatelessWidget {
  const NavigationBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: NavigationExample());
  }
}

class NavigationExample extends StatefulWidget {
  const NavigationExample({super.key});

  @override
  State<NavigationExample> createState() => _NavigationExampleState();
}

class _NavigationExampleState extends State<NavigationExample> {
  int currentPageIndex = 0;
  NavigationDestinationLabelBehavior labelBehavior = NavigationDestinationLabelBehavior.alwaysShow;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: NavigationBar(
        labelBehavior: labelBehavior,
        selectedIndex: currentPageIndex,
        onDestinationSelected: (int index) {
          setState(() {
            currentPageIndex = index;
          });
        },
        destinations: const <Widget>[
          NavigationDestination(icon: Icon(Icons.explore), label: 'Explore'),
          NavigationDestination(icon: Icon(Icons.commute), label: 'Commute'),
          NavigationDestination(
            selectedIcon: Icon(Icons.bookmark),
            icon: Icon(Icons.bookmark_border),
            label: 'Saved',
          ),
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('Label behavior: ${labelBehavior.name}'),
            const SizedBox(height: 10),
            OverflowBar(
              spacing: 10.0,
              overflowAlignment: OverflowBarAlignment.center,
              overflowSpacing: 10.0,
              children: <Widget>[
                ElevatedButton(
                  onPressed: () {
                    setState(() {
                      labelBehavior = NavigationDestinationLabelBehavior.alwaysShow;
                    });
                  },
                  child: const Text('alwaysShow'),
                ),
                ElevatedButton(
                  onPressed: () {
                    setState(() {
                      labelBehavior = NavigationDestinationLabelBehavior.onlyShowSelected;
                    });
                  },
                  child: const Text('onlyShowSelected'),
                ),
                ElevatedButton(
                  onPressed: () {
                    setState(() {
                      labelBehavior = NavigationDestinationLabelBehavior.alwaysHide;
                    });
                  },
                  child: const Text('alwaysHide'),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Compare hovering the unselected tab: 

Image

versus the selected tab:

Image

Note that the tooltip isn't sufficient because that won't show up for focus or touch feedback use cases.

</details>

### Logs

<details open><summary>Logs</summary>

N/A

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

N/A, Google-internal client

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes NavigationBar lacking visual feedback on the active destination indicator.

### Before:

The navigation indicator does not change color when hovered or focused:

https://github.com/user-attachments/assets/a1e67dee-4a38-4711-ba90-bdcd9bed3226

### After:

The navigation indicator color changes (slightly darker):

https://github.com/user-attachments/assets/1b1cc335-2cf4-4c41-9c53-696537707c72

## Related Issue

Fixes [NavigationBar lacks visual feedback when focused or hovered](https://github.com/flutter/flutter/issues/163871) 

## Tests

- Updates several helper functions which are used by several tests.
- Updates several test: adding an Ink widget changes the coordinates used in several tests because these coordinates are now relative to the Ink offset.
- Will impact fours golden tests which were capturing the bad behavior (indicator color not changing when hovered or focused).

### CODE REVIEW

**Review by TahaTesser — APPROVED** [review]
LGTM! (To trigger Google testing)

File: packages/flutter/lib/src/material/navigation_bar.dart [hunk 1]
```diff
@@ -853,7 +854,7 @@ class NavigationIndicator extends StatelessWidget {
             builder: (BuildContext context, Animation<double> fadeAnimation) {
               return FadeTransition(
                 opacity: fadeAnimation,
-                child: Container(
+                child: Ink(
```
Comment (justinmc) [inline packages/flutter/lib/src/material/navigation_bar.dart:857]: Simple fix 👍

**Review by justinmc — APPROVED** [review]
LGTM 👍 . The Google failures were all expected.

**Comment by bggRGjQaUbCoE** [comment]
There is a bug, selected nav will not change if switch nav by code instead of clicking.

**Comment by bleroux** [comment]
> There is a bug caused by this change, selected nav will not change if switch nav by code instead of clicking.

@bggRGjQaUbCoE Can you file an issue to illustrate this problem?

**Comment by bggRGjQaUbCoE** [comment]
> > There is a bug caused by this change, selected nav will not change if switch nav by code instead of clicking.
> 
> @bggRGjQaUbCoE Can you file an issue to illustrate this problem?

@bleroux Thanks for your response, here i created an issue, https://github.com/flutter/flutter/issues/169249
