### PR TITLE
TextField magnifier stuck on long press cancel

### LINKED ISSUE #167879: TextField magnifier gets stuck on screen when long press is cancelled
### Steps to reproduce

1. Long press TextField to open magnifier
2. While still long pressing, put the app to background with another finger (-> cancel long press)
3. Open the app again

### Expected results

Magnifier should close, similarly to when the long press ends (without cancelling)

### Actual results

Magnifier is stuck on the screen, even if you scroll away from the textfield

### Code sample

<details>

<summary>Example code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Magnifier bug',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Magnifier bug'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView(
        children: [
          const Text(
            "Long press to trigger the magnifier and while holding down, put the app into background. When coming back to app, the magnifier should be stuck on screen.",
          ),
           TextField(
            decoration: InputDecoration(hintText: "write something"),
          ),
          ...List.generate(
            20,
            (i) => GestureDetector(
                onTap: (){
              FocusScope.of(context).unfocus();
            },
              child: Container(
                height: 50,
                width: double.infinity,
                color: i % 2 == 0 ? Colors.red : Colors.blue,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/user-attachments/assets/8dfe50cb-6dc2-47c1-a342-cc49c5403ff9)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by O-Hannonen**
## Fixes #167879

This PR fixes bug where magnifier and floating cursor get stuck on screen when long press is cancelled (eg. by closing the app).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by VB10 — COMMENTED** [review]
lgtm 🎉

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 1]
```diff
@@ -2663,22 +2663,23 @@ class TextSelectionGestureDetectorBuilder {
...
-      final RawFloatingCursorPoint cursorPoint = RawFloatingCursorPoint(
-        state: FloatingCursorDragState.End,
-      );
-      editableText.updateFloatingCursor(cursorPoint);
-    }
+  }
+
+  /// Handler for [TextSelectionGestureDetector.onSingleLongTapCancel].
+  ///
+  /// By default, it hides magnifier and floating cursor if necesasary.
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/text_selection.dart:2674]:
```suggestion
  /// By default, it hides the magnifier and the floating cursor if necessary.
```

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 2]
```diff
@@ -3304,6 +3323,9 @@ class TextSelectionGestureDetector extends StatefulWidget {
   /// Called after [onSingleLongTapStart] when the pointer is lifted.
   final GestureLongPressEndCallback? onSingleLongTapEnd;
 
+  /// Called after [onSingleLongTapStart] when the pointer is cancelled.
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/text_selection.dart:3326]:
```suggestion
  /// Called after [onSingleLongTapStart] when the pointer is canceled.
```

**Comment by loic-sharma** [comment]
FYI there's a test failure: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8716520139161227697/+/u/run_test.dart_for_framework_tests_shard_and_subshard_widgets/stdout

It looks like if the text field is unmounted after a long press down, `onLongPressCancel` is called. I suspect we'll want to update `_hideMagnifierIfSupportedByPlatform` to no-op if the text field is unmounted. 

<details>
<summary>Test failure logs...</summary>

```
06:03 +5819 ~113: /b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/text_selection_test.dart: test TextSelectionGestureDetectorBuilder forcePress disabled
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      TextSelectionGestureDetectorBuilder.editableText (package:flutter/src/widgets/text_selection.dart:2176:78)
#1      TextSelectionGestureDetectorBuilder._hideMagnifierIfSupportedByPlatform (package:flutter/src/widgets/text_selection.dart:2068:9)
#2      TextSelectionGestureDetectorBuilder._longTapCleanup (package:flutter/src/widgets/text_selection.dart:2753:5)
#3      TextSelectionGestureDetectorBuilder.onSingleLongTapCancel (package:flutter/src/widgets/text_selection.dart:2682:5)
#4      _TextSelectionGestureDetectorState._handleLongPressCancel (package:flutter/src/widgets/text_selection.dart:3471:35)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:345:24)
#6      LongPressGestureRecognizer._checkLongPressCancel (package:flutter/src/gestures/long_press.dart:721:13)
#7      LongPressGestureRecognizer.resolve (package:flutter/src/gestures/long_press.dart:867:9)
#8      OneSequenceGestureRecognizer.dispose (package:flutter/src/gestures/recognizer.dart:470:5)
#9      PrimaryPointerGestureRecognizer.dispose (package:flutter/src/gestures/recognizer.dart:765:11)
#10     RawGestureDetectorState.dispose (package:flutter/src/widgets/gesture_detector.dart:1529:18)
#11     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5922:11)
...
#349    ListIterable.forEach (dart:_internal/iterable.dart:49:13)
#350    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2084:25)
#351    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2965:15)
#352    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3288:7)
#353    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1537:19)
#354    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495:5)
#355    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1438:15)
#356    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1351:9)
#357    AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:1441:5)
#358    _runWidget (package:flutter/src/widgets/binding.dart:1547:7)
#359    runApp (package:flutter/src/widgets/binding.dart:1480:3)
#360    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1071:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

Handler: "onLongPressCancel"
Recognizer:
  LongPressGestureRecognizer#02ba0
════════════════════════════════════════════════════════════════════════════════════════════════════
...
06:03 +5819 ~113 -1: /b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/text_selection_test.dart: test TextSelectionGestureDetectorBuilder forcePress disabled [E]
  Test failed. See exception logs above.
  The test description was: test TextSelectionGestureDetectorBuilder forcePress disabled
```

</details>

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 3]
```diff
@@ -2748,6 +2749,22 @@ class TextSelectionGestureDetectorBuilder {
     }
   }
 
+  void _longTapCleanup(){
```
[the remark this answers is not in the document]
Comment (O-Hannonen) [reply packages/flutter/lib/src/widgets/text_selection.dart:2752]: Makes sense!

**Comment by dkwingsmt** [comment]
Gentle nudge @loic-sharma

**Comment by Renzo-Olivares** [comment]
Looks like there is an analyzer issue, you can fix that by running `dart format` on `text_selection.dart`.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM thanks for the fix!

**Comment by justinmc** [comment]
@O-Hannonen Can you take a look at the analyzer failure?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 4]
```diff
@@ -2748,6 +2759,22 @@ class TextSelectionGestureDetectorBuilder {
     }
   }
 
+  void _onSingleLongTapEndOrCancel(){
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/text_selection.dart:2762]:
```suggestion
  void _onSingleLongTapEndOrCancel() {
```

**Review by loic-sharma — APPROVED** [review]
Looks good to me, thanks for the wonderful contribution!

**Comment by Renzo-Olivares** [comment]
Rebasing to get Google testing running again.

**Comment by Renzo-Olivares** [comment]
Rebasing one more time to fix merge queue issue.
