### PR TITLE
[flutter] when primary mouse pointers don't contact a focused node, reset the focus

### LINKED ISSUE #32433: [Web]: Click outside of text field should unfocus
When trying the gallery example app in flutter_web I noticed that clicking away from a focused text field does not cause it to lose focus. 

It is standard behaviour on the web that when a text field is focused and the mouse is clicked on a blank space on the page the field is unfocused.

Steps to reproduce on Chrome browser with a mouse and keyboard (e.g. on a desktop):
1) Click on text field - Field is now in focus with cursor visible
2) Click outside of text field on a blank space (not another text field) - Text field is still in focus

### LINKED ISSUE #82515: Not possible to de-focus a text field without clicking another focusable widget
Consider a page with a focusable text field, such as the gallery. After focusing the text field, I would expect that one the web or desktop I could click outside the text field area to remove focus. However this is not possible today, I need to click another focusable widget such as a text field or leave the page.

Aside from platform adaoption, this makes it difficult or impossible to use the Shortcuts widget to on a page with text fields. The Shortcuts may not be able to gain focus again after the text field has been focused.

Since the text fields cannot receive tap events that don't hit them (in order to dispose of focus), the solution requires a new widget be introduced that can intercept focus from the text fields.

Solution: The ~~parent~~ focus trap. A widget introduced at either the app level or route level. On tap events, it always requests focus. This will only be granted if the tap does not hit a more specific focus node. Draft:

```dart
class FocusTrap extends StatefulWidget {
  /// Create a new [FocusTrap] widget.
  const FocusTrap({
    required this.child,
    this.focusNode,
    Key? key
  }) : super(key: key);

  final Widget child;
  final FocusNode? focusNode;

  @override
  State<FocusTrap> createState() => _FocusTrapState();
}

class _FocusTrapState extends State<FocusTrap> {
  final Map<Type, GestureRecognizerFactory> _gestures = <Type, GestureRecognizerFactory>{};
  late FocusNode _focusNode;

  FocusNode get focusNode => widget.focusNode ?? _focusNode;

  void _stealFocus(TapDownDetails details) {
    if (details.kind != PointerDeviceKind.mouse)
      return;
    focusNode.requestFocus();
  }

  @override
  void initState() {
    super.initState();
    _focusNode = FocusNode();
    _gestures[TapGestureRecognizer] = GestureRecognizerFactoryWithHandlers<TapGestureRecognizer>(
        () => TapGestureRecognizer(debugOwner: this),
        (TapGestureRecognizer instance) {
          instance
            .onTapDown = _stealFocus;
        },
      );
  }

  @override
  Widget build(BuildContext context) {
    return Focus(
      autofocus: true,
      child: RawGestureDetector(
        child: widget.child,
        gestures: _gestures,
      ),
      focusNode: focusNode,
    );
  }
}

```

And currently introduced in the same place I was putting SelectionArea (since this is needed to make Ctrl+C and other shortcuts work reliably) 

```diff
@@ -10,6 +10,7 @@ import 'package:flutter/scheduler.dart';
 import 'package:flutter/semantics.dart';

 import 'actions.dart';
+import 'base_focus.dart';
 import 'basic.dart';
 import 'focus_manager.dart';
 import 'focus_scope.dart';
@@ -841,11 +842,11 @@ class _ModalScopeState<T> extends State<_ModalScope<T>> {
                             key: widget.route._subtreeKey, // immutable
                             child: Builder(
                               builder: (BuildContext context) {
-                                return widget.route.buildPage(
+                                return FocusTrap(child: widget.route.buildPage(
                                   context,
                                   widget.route.animation!,
                                   widget.route.secondaryAnimation!,
-                                );
+                                ));
                               },
                             ),
                           ),
 ```

new behavior:

https://user-images.githubusercontent.com/8975114/118219120-ad5ccc00-b42d-11eb-9d72-9b5cf9ffee73.mp4

blocks: https://github.com/flutter/flutter/issues/81839

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/82515
Fixes https://github.com/flutter/flutter/issues/32433

Introduces a widget that checks if a pointer down event has hit the currently focused nodes' render object. This leads to odd behavior with text field decorations due to the focus being only owned by the inner editable text widget.

The modal route's focus scoped node is used to "reset" the focus when pointer did not contact either.

This is limited to mouse pointers on desktop and mobile web.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This currently only applies for keyboard events, I'd need to do more research into how touch events should behave

**Comment by skia-gold** [comment]
Gold has detected about 2 untriaged digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/82575

**Comment by jonahwilliams** [comment]
adding another widget here seems to be changing the layout slightly, which is unfortunate...

File: packages/flutter/lib/src/widgets/routes.dart [hunk 1]
```diff
@@ -841,11 +843,11 @@ class _ModalScopeState<T> extends State<_ModalScope<T>> {
                             key: widget.route._subtreeKey, // immutable
                             child: Builder(
                               builder: (BuildContext context) {
-                                return widget.route.buildPage(
+                                return _FocusTrap(child: widget.route.buildPage(
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/routes.dart:846]: any reason we scope at route level?

File: packages/flutter/lib/src/widgets/routes.dart [hunk 2]
```diff
@@ -1980,3 +1982,61 @@ typedef RoutePageBuilder = Widget Function(BuildContext context, Animation<doubl
...
+}
+
+class _FocusTrapState extends State<_FocusTrap> {
+  final Map<Type, GestureRecognizerFactory> _gestures = <Type, GestureRecognizerFactory>{};
+  late FocusNode _focusNode;
+
+  FocusNode get focusNode => widget.focusNode ?? _focusNode;
+
+  void _stealFocus(TapDownDetails details) {
+    if (details.kind != PointerDeviceKind.mouse)
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/routes.dart:2013]: do you know what is the native behavior for mobile if you have an external mouse?

File: packages/flutter/lib/src/widgets/routes.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart:846]: i scoped it at the route level so that I can have this and the shortcuts widget used by the SelectionArea widget use the same focus node.

File: packages/flutter/lib/src/widgets/routes.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart:2013]: i don't have access to the hardware to test this. we could definitely just disable the behavior on iOS/android until we could test it

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart]: (disabled for non-desktop platforms for now)

**Comment by MarcusWichelmann** [comment]
Just an outsiders thought:

This looks great and all, but should it really be necessary to add a `FocusTrap` widget to the widget tree just to get a behaviour which one might expect to be there by default? Of course, this is a good first step, but maybe this functionallity should also be included into other widgets like e.g. `MaterialApp` so programmers get the behaviour they know from the web without having to google for it and add the `FocusTrap` widget oneself?

**Comment by jonahwilliams** [comment]
I agree, I'm not sure that this is the right solution exactly but i'm not sure how else you would do it. Widgets can't unfocus themselves if they aren't hit 🤔

**Comment by Wissperwind** [comment]
In HTML Web every element can be focused. Even if it is not editable, correct?
Cant we make every widget fucusable? This would change the focus away from a text field if you click for example on the backend scaffold or the scroll bar.

I am not a flutter developer. So this is only an idea from outside but I wanted to post it.

For me it is rather important to get some working solution in the next two weeks that to get a really good solution.

**Comment by jonahwilliams** [comment]
An html element isn't equivalent to a flutter widget. A widget not have any UI, only configuring other widgets themselves. Even making every widget with uI focusable would make pure focus traversal painful.

**Comment by jonahwilliams** [comment]
Based on some discussion with @gspencergoog , I've updated this to use the unfocus functionality of the modal route's FocusScopeNode. Of course, using the gesture recognizer the way that I am is breaking the world, so I'll need to find a way to make this change not compete with any other recognizers somehow...

**Comment by skia-gold** [comment]
Gold has detected about 3 untriaged digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/82575

File: packages/flutter/lib/src/gestures/tap.dart [hunk 3]
```diff
@@ -136,8 +136,8 @@ typedef GestureTapCancelCallback = void Function();
 ///    any buttons.
 abstract class BaseTapGestureRecognizer extends PrimaryPointerGestureRecognizer {
   /// Creates a tap gesture recognizer.
-  BaseTapGestureRecognizer({ Object? debugOwner })
-    : super(deadline: kPressTimeout , debugOwner: debugOwner);
+  BaseTapGestureRecognizer({ Object? debugOwner, Set<PointerDeviceKind>? supportedDevices })
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/gestures/tap.dart:139]: Will revert, unrelated

File: packages/flutter/lib/src/material/text_field.dart [hunk 4]
```diff
@@ -1302,30 +1302,33 @@ class _TextFieldState extends State<TextField> with RestorationMixin implements
...
-            return Semantics(
-              maxValueLength: semanticsMaxValueLength,
-              currentValueLength: _currentLength,
-              onTap: widget.readOnly ? null : () {
-                if (!_effectiveController.selection.isValid)
-                  _effectiveController.selection = TextSelection.collapsed(offset: _effectiveController.text.length);
-                _requestKeyboard();
-              },
-              onDidGainAccessibilityFocus: handleDidGainAccessibilityFocus,
+    return FocusArea(
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/material/text_field.dart:1305]: Because we want clicks on the decorations of at text field to retain focus

**Comment by jonahwilliams** [comment]
PTAL at the current approach

**Comment by jonahwilliams** [comment]
This should probably be widened to include all touch gestures on the web, but maybe we should study that a bit more and handle the easier desktop case first?

File: packages/flutter/lib/src/widgets/focus_scope.dart [hunk 5]
```diff
@@ -1043,3 +1044,35 @@ class ExcludeFocus extends StatelessWidget {
...
+    return RenderFocusArea(focusNode);
+  }
+
+  @override
+  void updateRenderObject(BuildContext context, covariant RenderFocusArea renderObject) {
+    renderObject.focusNode = focusNode;
+  }
+}
+
+/// The focus area render object is used as a sentinel in routes.dart.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/focus_scope.dart:1071]: Maybe explain in more detail? and it feel weird to me that we point to a source code file in API doc.

File: packages/flutter/lib/src/widgets/focus_scope.dart [hunk 6]
```diff
@@ -1043,3 +1044,35 @@ class ExcludeFocus extends StatelessWidget {
     );
   }
 }
+
+/// A focus area is used to expand a focus node as part of the render object layer
+/// outside of its descendant render objects.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/focus_scope.dart:1049]: We should also explain what is the use case, i.e. why would developers want to use this widget

File: packages/flutter/lib/src/widgets/focus_scope.dart [hunk 7]
```diff
@@ -1043,3 +1044,35 @@ class ExcludeFocus extends StatelessWidget {
...
+///
+/// This is used by the [TextField] widgets to associate the focus node with the input
+/// decorations.
+class FocusArea extends SingleChildRenderObjectWidget {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/focus_scope.dart:1053]: This widget can really only work with the FocusTrap, It feel weird that one is private and another is public. I feel we should either make both public or both private. Curious what others think? @gspencergoog

File: packages/flutter/lib/src/widgets/routes.dart [hunk 8]
```diff
@@ -1980,3 +1986,125 @@ typedef RoutePageBuilder = Widget Function(BuildContext context, Animation<doubl
...
 /// See [ModalRoute.buildTransitions] for complete definition of the parameters.
 typedef RouteTransitionsBuilder = Widget Function(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child);
+
+/// When a primary pointer makes contact with the screen, this widget determines if that pointer
+/// contacted an existing focused widget. If not, this asks the [FocusScopeNode] to reset the
+/// focus state. This allows [TextField]s and other focusable widgets to give up their focus
+/// state, without creating a gesture detector that competes with others on screen.
+///
+/// See also:
+///   * [RenderFocusArea], which allows a focus node to own a larger render object
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/routes.dart:1996]: nit: add a new line after see also

File: packages/flutter/lib/src/material/text_field.dart [hunk 9]
```diff
@@ -1302,30 +1302,33 @@ class _TextFieldState extends State<TextField> with RestorationMixin implements
...
+      focusNode: focusNode,
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/text_field.dart:1306]: This is a little odd. It's usually not OK to give the same focus node to two widgets: it messes with where the focus node ends up in the focus tree, and can cause some really weird focus issues, since the where it ends up depends on who builds last.

In this case, since you're just listening to the focus node, it's probably OK, but we should probably not call this attribute `focusNode`, so that we differentiate it from all the other widgets that take a focus node in order to use it to implement focus.  Maybe `watchedFocusNode`, `monitoredFocusNode`? (don't love either of those, really)

I do worry about lifecycle issues: if this widget is listening to the focus node, I think it will assert if it tries to remove listener on that node if the node has already been disposed by the widget that owns it.

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/text_field.dart:1306]: yes, this one is a head scratcher. The problem I have is that at the render object layer, the focus not only belongs to a tiny part of the text field. But if you look at what is on screen, the focus is clearly attributable to a much wider area that encompasses the decoration / borders / et cetera.



> It's usually not OK to give the same focus node to two widgets

i'm not really giving the focus in this case, more like using it as a key/token. I can definitely rename to something else, but overall I'd love for there to be a cleaner solution here

File: packages/flutter/lib/src/widgets/routes.dart [hunk 10]
```diff
@@ -1980,3 +1986,125 @@ typedef RoutePageBuilder = Widget Function(BuildContext context, Animation<doubl
...
+        hitCurrentFocus = true;
+        break;
+      }
+      if (target is RenderFocusArea && target.focusNode == currentFocus) {
+        hitCurrentFocus = true;
+        break;
+      }
+    }
+    if (!hitCurrentFocus)
+      focusScopeNode.unfocus(disposition: UnfocusDisposition.scope);
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart:2108]: If I push a new route and hit tab, what is the expected focus behavior?

Clicking out of a focus area to deselect should return to this same state, no?

File: packages/flutter/lib/src/material/text_field.dart (hunk 9 above)
Comment (chunhtai) [reply packages/flutter/lib/src/material/text_field.dart:1306]: I am also curious, if user click the decoration, will that bring the focus to the editable text? if so, how does it know it hits the editable text?

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/text_field.dart:1306]: This is already the behavior today.

What this change does is makes sure that we do not remove focus if the user clicks the decoration. Doing so would cause it to immediately be re-acquired by the text field's gesture detection.

Comment (chunhtai) [reply packages/flutter/lib/src/material/text_field.dart:1306]: I wonder if we can make focusnode attach to the TextFieldState instead of EditableTextState?

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/text_field.dart:1306]: I think the editable text state uses the focus too though, which goes back to @gspencergoog 's point about not re-using a focus object (though we kind of already are?)

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/text_field.dart:1306]: we could conditionally attach the focus to either state based on how the widget was created. Seems iffy TBH

Comment (chunhtai) [reply packages/flutter/lib/src/material/text_field.dart:1306]: You can attach in TextFieldState and pass into the EditableText, and the EditableText just listen to the focusnode. I think as long as the EditableTextState dispose before TextFieldState dispose, there should be any issue. @gspencergoog may know more. This way, the focusNode.currentContext.findRenderObject will return the renderobject of the TextDecoration.

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/text_field.dart:1306]: let me play around with this a bit, I'm not sure if EditableText needs the focus attachment if the text field already has it

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/text_field.dart:1306]: flutter gallery seems to work OK, I don't dare run the tests...

**Comment by jonahwilliams** [comment]
By conditionally attach the focus to the text field instead of the editable text, I can drop the entire FocusArea concept.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 11]
```diff
@@ -1582,7 +1582,8 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     super.initState();
     _clipboardStatus?.addListener(_onChangedClipboardStatus);
     widget.controller.addListener(_didChangeTextEditingValue);
-    _focusAttachment = widget.focusNode.attach(context);
+    if (!widget.focusNode.hasAttachment)
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/editable_text.dart:1585]: I think it will be cleaner if we document the focusnode need to be attached before passing into the EditableText, but I think that will be a pretty bad breaking change. so I think this looks fine as is.

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 12]
```diff
@@ -754,6 +754,9 @@ class FocusNode with DiagnosticableTreeMixin, ChangeNotifier {
     return Rect.fromLTRB(topLeft.dx, topLeft.dy, bottomRight.dx, bottomRight.dy);
   }
 
+  /// Whether this focus node is already attached to the widget tree.
+  bool get hasAttachment => _context != null;
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/focus_manager.dart:758]:
```suggestion
  bool get attached => _attachment != null;
```

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/focus_manager.dart:758]: _context may be non-null even if the attachment has been detached. It is probably a bug we should fix.

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/focus_manager.dart:758]: Ahh, OK 😅

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 11 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/editable_text.dart:1585]: Is EditableText widely used by itself? If so i don't see another way unfortunately. if there is no wrapper widget the editable text would need to attach.

**Comment by chunhtai** [comment]
This seems to turn into a big refactor. cc @LongCatIsLooong who may have a better idea how to handle this

**Comment by gspencergoog** [comment]
Something we should do eventually is convert the editable text to use a Focus widget instead of doing special things with a focus node and its own focus attachment. It's the only thing that uses `FocusAttachment` other than `Focus`, and it would be better if we could just say that all focus operations should use a `Focus` widget, in order to centralize the code for that. It will also require some reworking of things, since it'll have to discover the focus node from the `Focus` widget (via `Focus.of(context)`) and pass it down to the render object, but I think it would be a good idea. That might also help with this problem, to pull some of the focus stuff out of editable text.

**Comment by jonahwilliams** [comment]
How would moving the EditableText to use a FocusNode help the issue of the Focus needing to include the parent decoration?

**Comment by jonahwilliams** [comment]
the other approach would be to remove the text field specific work arounds for this change, let it be broken, and then prioritize a fix later.

**Comment by jonahwilliams** [comment]
I updated this to remove the text field specific hacks. currently investigating how to correctly "reset" focus so that tab still works

File: packages/flutter/lib/src/widgets/routes.dart (hunk 10 above)
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart]: seems like calling unfocus on the node itself has this behavior, I can tab and start focusing again

**Comment by jonahwilliams** [comment]
Tab focus works now

**Comment by jonahwilliams** [comment]
PTAL

File: packages/flutter/lib/src/widgets/routes.dart [hunk 13]
```diff
@@ -1980,3 +1986,117 @@ typedef RoutePageBuilder = Widget Function(BuildContext context, Animation<doubl
...
+        result.add(entry);
+      }
+    }
+    return hitTarget;
+  }
+
+  @override
+  bool hitTestSelf(Offset position) => false;
+
+  @override
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/routes.dart:2053]: is this method used?

File: packages/flutter/lib/src/widgets/routes.dart [hunk 14]
```diff
@@ -1980,3 +1986,117 @@ typedef RoutePageBuilder = Widget Function(BuildContext context, Animation<doubl
...
+        final BoxHitTestEntry entry = BoxHitTestEntry(this, position);
+        cachedResults[entry] = result;
+        result.add(entry);
+      }
+    }
+    return hitTarget;
+  }
+
+  @override
+  bool hitTestSelf(Offset position) => false;
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/routes.dart:2051]: it is already default to false

File: packages/flutter/lib/src/widgets/routes.dart [hunk 15]
```diff
@@ -811,42 +814,45 @@ class _ModalScopeState<T> extends State<_ModalScope<T>> {
...
-                              AnimatedBuilder(
-                                animation: widget.route.navigator?.userGestureInProgressNotifier ?? ValueNotifier<bool>(false),
-                                builder: (BuildContext context, Widget? child) {
-                                  final bool ignoreEvents = _shouldIgnoreFocusRequest;
-                                  focusScopeNode.canRequestFocus = !ignoreEvents;
-                                  return IgnorePointer(
-                                    ignoring: ignoreEvents,
-                                    child: child,
+                      child: _FocusTrap(
+                      focusScopeNode: focusScopeNode,
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/routes.dart:818]: nit: indent

File: packages/flutter/lib/src/widgets/routes.dart (hunk 13 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart]: nope removed

File: packages/flutter/lib/src/widgets/routes.dart (hunk 14 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart]: removed

File: packages/flutter/lib/src/widgets/routes.dart (hunk 15 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart]: fixed

File: packages/flutter/lib/src/widgets/routes.dart [hunk 16]
```diff
@@ -811,42 +814,45 @@ class _ModalScopeState<T> extends State<_ModalScope<T>> {
...
-                              AnimatedBuilder(
-                                animation: widget.route.navigator?.userGestureInProgressNotifier ?? ValueNotifier<bool>(false),
-                                builder: (BuildContext context, Widget? child) {
-                                  final bool ignoreEvents = _shouldIgnoreFocusRequest;
-                                  focusScopeNode.canRequestFocus = !ignoreEvents;
-                                  return IgnorePointer(
-                                    ignoring: ignoreEvents,
-                                    child: child,
+                      child: _FocusTrap(
+                        focusScopeNode: focusScopeNode,
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/routes.dart:818]: The same focusnode get passed into two widgets. not sure if this is a concern cc @gspencergoog 

If it is, we can avoid this by merging the FocusScope and _focusTrap into one widget.

**Review by chunhtai — APPROVED** [review]
LGTM except for the share focusScopeNode in two widgets.

File: packages/flutter/lib/src/widgets/routes.dart (hunk 16 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/routes.dart:818]: Usually sharing a `FocusNode` (or `FocusScopeNode`) between two widgets is a concern because they'll fight over the attachment.  If the focus node is _only_ used to call `requestFocus()`, or something else that doesn't require attachment, in one of the widgets, then it's technically OK.

Basically, the rule is: Don't pass the same focus node to two widgets that will attach it to the focus tree. Only one widget can "own" it.

You might also have lifetime issues when it comes to disposing them. Again, only one may dispose of the focus node, and so the widget that it is passed to that doesn't own it needs to have a shorter lifetime than the one that does own it.

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart:818]: I think what I'm doing here is safe, no stack traces or bugs so far. What would you like me to change about the current structure?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/routes.dart:818]: I don't have a good suggestion neither, if @gspencergoog is ok with the current structure, I am fine with it as well

File: packages/flutter/lib/src/widgets/routes.dart [hunk 17]
```diff
@@ -1980,3 +1986,109 @@ typedef RoutePageBuilder = Widget Function(BuildContext context, Animation<doubl
...
+  }
+
+  @override
+  void handleEvent(PointerEvent event, HitTestEntry entry) {
+    assert(debugHandleEvent(event, entry));
+    if (event is! PointerDownEvent
+      || event.buttons != kPrimaryButton
+      || event.kind != PointerDeviceKind.mouse
+      || _shouldIgnoreEvents
+      || currentFocus == null)
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/routes.dart:2072]: nit: Can you put braces on this conditional block? Having a really long multi-line conditional just reads weird without the braces.

File: packages/flutter/lib/src/widgets/routes.dart (hunk 16 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/routes.dart:818]: I think I'm OK with the current structure: the widget using the node is a private class, so we have control over its lifetime, and it doesn't appear to be doing anything that would attach the node to the focus tree.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

File: packages/flutter/lib/src/widgets/routes.dart (hunk 17 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart:2072]: will do

**Comment by jonahwilliams** [comment]
FYI @renyou , not sure what is up with the google testing on this PR

**Comment by renyou** [comment]
It seems some google internal tests may be very slow and I am going to increase the timeout threshold. Hopefully it can resolve this.

**Comment by renyou** [comment]
@jonahwilliams  Did you trigger a full test on this PR?

**Comment by jonahwilliams** [comment]
yes, since it is a potentially a substantial change I wanted to be sure we ran as many tests as possible...

**Comment by renyou** [comment]
Yes! The tests are actually all done, just took longer to analyze all the test results. I manually set the results. Everything looks good!

**Comment by jonahwilliams** [comment]
🎊

**Comment by HansMuller** [comment]
@jonahwilliams - does this PR address https://github.com/flutter/flutter/pull/74354?

**Comment by jpnurmi** [comment]
- On Linux, native GNOME/GTK apps don't reset focus when clicking outside text fields.
- The focused render object inside TextField doesn't cover the entire TextField? Please check https://github.com/flutter/flutter/issues/85732
- Is it not possible to have buttons that don't reset focus? https://github.com/flutter/flutter/pull/76072#issuecomment-872032090

**Comment by Hixie** [comment]
If we want this behaviour, why not just put a Focus widget around the route?

...but I'm not convinced we want this behaviour. It's not what happens on Windows and macOS as far as I can tell.

**Comment by Hixie** [comment]
I think this is just something we want on Web, and on Web the behaviour is just that the root of the tree is itself focusable, no need to check whether a tap would have focused a node and all that.
