### PR TITLE
Snackbar Refactor

### LINKED ISSUE #374: Calling showSnackBar() twice in a row will fail
If I'm reading the code right, if you call showSnackBar() while an existing snack bar is up, we'll just replace the previous one with the new one, rather than doing a transition or something. Then later we'll set the placeholder to null even while one of the snack bars is still up.

### LINKED ISSUE #432: Redesign snackbar API to not use routes
I think snack bars should be a feature of a Scaffold. They probably shouldn't use routes at all.

According to the specs -- https://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-specs -- they should not time out while another route (e.g. a dialog) is over them, they should reset their timeout when their parent route resumes being the current route, they should be displayed consecutively in time, etc.

### PR DESCRIPTION
**Pull request by Hixie**
"showSnackBar()" is now a feature of a Scaffold. To get to a Scaffold
you either use a global key (`scaffoldKey.currentState.showSnackBar(...)`),
or you use `Scaffold.of(context)`.

Snack bars no longer have a route. They are entirely managed by the
Scaffold. Fixes #432.

Snack bars now queue up when you have several of them. Fixes #374.

Snack bars now auto-size themselves around their contents. This is step
one towards implementing multiline snack bars.

Snack bars now self-dismiss after some per-snackbar configurable period.

The self-dismissing pauses while a dialog is up above the snackbar (or
anything that uses ModalRoute). To enable this, there's now a
`ModalRoute.of(context)` API that returns the current ModalRoute, and
you will be rebuilt if you asked for this and the route's "current"
status changes. To implement this, the Navigator now rebuilds
unconditionally any time it pushes or pops a route.

Snack bars now use the curves that Android uses for snack bars.

Snack bar contents now fade in.

### CODE REVIEW

File: packages/flutter/lib/src/material/scaffold.dart [hunk 1]
```diff
@@ -77,46 +79,102 @@ class _ScaffoldLayout extends MultiChildLayoutDelegate {
...
-      // TODO(jackson): On tablet/desktop, minWidth = 288, maxWidth = 568
-      constrainedSnackBar = new ConstrainedBox(
-        constraints: const BoxConstraints(maxHeight: kSnackBarHeight),
-        child: snackBar
-      );
+    final Widget paddedToolBar = config.toolBar?.withPadding(new EdgeDims.only(top: ui.window.padding.top));
+    final Widget materialBody = config.body != null ? new Material(child: config.body) : null;
+
+    if (_snackBars.length > 0) {
+print('build! ${_snackBars.length} ${ModalRoute.of(context).isCurrent}');
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/scaffold.dart]: Is this supposed to be here?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 2]
```diff
@@ -77,46 +79,102 @@ class _ScaffoldLayout extends MultiChildLayoutDelegate {
...
-  final Widget bottomSheet;
+
+  static ScaffoldState of(BuildContext context) => context.ancestorStateOfType(ScaffoldState);
+
+  ScaffoldState createState() => new ScaffoldState();
+}
+
+class ScaffoldState extends State<Scaffold> {
+
+  List<SnackBar> _snackBars = <SnackBar>[];
```
Comment (abarth) [inline packages/flutter/lib/src/material/scaffold.dart]: This should be a Queue rather than a list given your mutation pattern.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (abarth) [inline packages/flutter/lib/src/material/scaffold.dart]: print!!!

File: packages/flutter/lib/src/material/scaffold.dart [hunk 3]
```diff
@@ -77,46 +79,102 @@ class _ScaffoldLayout extends MultiChildLayoutDelegate {
...
+  }
+
+  void _hideSnackBar() {
+    _snackBarPerformance.reverse();
+    _snackBarTimer = null;
+  }
+
+  void dispose() {
+    _snackBarPerformance?.stop();
+    _snackBarTimer?.cancel();
```
Comment (abarth) [inline packages/flutter/lib/src/material/scaffold.dart]: I'd null these out here for paranoia

File: packages/flutter/lib/src/material/scaffold.dart [hunk 4]
```diff
@@ -77,46 +79,102 @@ class _ScaffoldLayout extends MultiChildLayoutDelegate {
...
-        child: snackBar
-      );
+    final Widget paddedToolBar = config.toolBar?.withPadding(new EdgeDims.only(top: ui.window.padding.top));
+    final Widget materialBody = config.body != null ? new Material(child: config.body) : null;
+
+    if (_snackBars.length > 0) {
+print('build! ${_snackBars.length} ${ModalRoute.of(context).isCurrent}');
+      if (_snackBarPerformance.isDismissed)
+        _snackBarPerformance.forward();
+      if (ModalRoute.of(context).isCurrent) {
```
Comment (abarth) [inline packages/flutter/lib/src/material/scaffold.dart]: Should we handle the error of not finding the modal route?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 5]
```diff
@@ -77,46 +79,102 @@ class _ScaffoldLayout extends MultiChildLayoutDelegate {
...
+        if (_snackBarPerformance.isCompleted && _snackBarTimer == null)
+          _snackBarTimer = new Timer(_snackBars[0].duration, _hideSnackBar);
+      } else {
+        if (_snackBarTimer != null) {
+          _snackBarTimer.cancel();
+          _snackBarTimer = null;
+        }
```
Comment (abarth) [inline packages/flutter/lib/src/material/scaffold.dart]: Elvis operator?

```
_snackBarTimer?.cancel();
_snackBarTimer = null;
```

File: packages/flutter/lib/src/material/snack_bar.dart [hunk 6]
```diff
@@ -91,33 +100,24 @@ class _SnackBar extends StatelessComponent {
...
-  );
-
-  // TODO(hansmuller): https://github.com/flutter/flutter/issues/374
-  assert(placeholderKey.currentState.child == null);
+  static Performance createPerformance(PerformanceStatusListener statusListener) {
+    assert(statusListener != null);
+    return new Performance(
+      duration: kSnackBarTransitionDuration,
+      debugLabel: 'SnackBar'
+    )..addStatusListener(statusListener);
```
Comment (abarth) [inline packages/flutter/lib/src/material/snack_bar.dart]: Why does this add the status listener for you?  Seems cleaner to just return the performance and have the caller add the status listener.

**Comment by abarth** [comment]
LGTM

File: packages/unit/test/widget/snack_bar_test.dart [hunk 7]
```diff
@@ -7,60 +7,140 @@ import 'package:test/test.dart';
...
-      tester.pump(new Duration(seconds: 1));
-      expect(showSnackBarThenCalled, isTrue);
+      tester.pump(new Duration(milliseconds: 750)); // 2.25s 
+      expect(tester.findText(helloSnackBar), isNotNull);
+      tester.pump(new Duration(milliseconds: 750)); // 3.00s // timer triggers to dismiss snackbar, reverse animation is scheduled
+      tester.pump(); // begin animation
+      expect(tester.findText(helloSnackBar), isNotNull); // frame 0 of dismiss animation
+      tester.pump(new Duration(milliseconds: 750)); // 3.75s // last frame of animation, snackbar removed from build
       expect(tester.findText(helloSnackBar), isNull);
-      expect(placeholderKey.currentState.child, isNull);
```
Comment (HansMuller) [inline packages/unit/test/widget/snack_bar_test.dart]: We don't care about clearing the placeholder anymore?

Comment (Hixie) [inline packages/unit/test/widget/snack_bar_test.dart]: there is no placeholder anymore.
