### PR TITLE
Show a warning when a module uses a v1 only plugin

### LINKED ISSUE #44245: Show a warning when a Flutter module depends on a plugin that only has Android v1 plugins
Since v1 plugins are written with the assumption that it will be used in full-Flutter scenarios and may have unexpected behavior in add-to-app cases.

### LINKED ISSUE #44423: GeneratedPluginsRegistrant version matching for modules isn't strictly correct
plugins.dart's _getAndroidEmbeddingVersion() isn't strictly right for module types. The embedding version is determined by the AndroidManifest of the app but modules' embedding version should just be hardcoded to V2. The modules happens to have a lightweight wrapper app as an example whose AndroidManifest says v2 but it's more of a coincidence. 

cc @blasten 

We should probably fix it at the same time as https://github.com/flutter/flutter/issues/44245

### PR DESCRIPTION
**Pull request by xster**
## Description

Since v1 plugins can make incorrect assumptions when used in add-to-app, show a warning when they're being imported. 

## Related Issues

Fixes https://github.com/flutter/flutter/issues/44245
Fixes https://github.com/flutter/flutter/issues/44423

## Tests

I added the following tests:

added tests in plugin_test

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter_tools/lib/src/plugins.dart [hunk 1]
```diff
@@ -402,6 +403,16 @@ Future<void> _writeAndroidPluginRegistrant(FlutterProject project, List<Plugin>
       for (Map<String, dynamic> plugin in androidPlugins) {
         if (plugin['supportsEmbeddingV1'] && !plugin['supportsEmbeddingV2']) {
           templateContext['needsShim'] = true;
+          if (isModule) {
+            printStatus(
+              'The plugin `${plugin['name']}` is built using an older version '
```
Comment (xster) [inline packages/flutter_tools/lib/src/plugins.dart]: @zoeyfan to double check on the wording here.

File: packages/flutter_tools/lib/src/plugins.dart [hunk 2]
```diff
@@ -394,6 +394,7 @@ Future<void> _writeAndroidPluginRegistrant(FlutterProject project, List<Plugin>
   );
   String templateContent;
   final AndroidEmbeddingVersion appEmbeddingVersion = _getAndroidEmbeddingVersion(project);
+  final bool isModule = project.isModule;
```
Comment (blasten) [inline packages/flutter_tools/lib/src/plugins.dart]: Trivial nit: maybe move this closer to where is used.

File: packages/flutter_tools/lib/src/project.dart [hunk 3]
```diff
@@ -645,6 +645,11 @@ class AndroidProject {
   }
 
   AndroidEmbeddingVersion getEmbeddingVersion() {
+    if (isModule) {
+      // A module type's Android project is used in add-to-app scenarios and
+      // only supports the V2 embedding.
+      return AndroidEmbeddingVersion.v2;
```
Comment (blasten) [inline packages/flutter_tools/lib/src/project.dart]: what about a project that was created with v1 and ran make-host-app-editable?

**Review by blasten — APPROVED** [review]
LGTM /w nit

File: packages/flutter_tools/lib/src/plugins.dart (hunk 2 above)
Comment (xster) [reply packages/flutter_tools/lib/src/plugins.dart]: Sure, isModule happens to just be a pre-populated map key check, so it could be done in the loop

File: packages/flutter_tools/lib/src/project.dart (hunk 3 above)
Comment (xster) [reply packages/flutter_tools/lib/src/project.dart]: Discussed on chat. If users generally consumed v1 in add-to-app, it would break in the next stable. Those plugins will need to be registered manually since our tools can't predict whether a v1 or v2 style consumption will be made in the host Android project. 

Document in https://github.com/flutter/flutter/issues/36491
