### PR TITLE
Selecting an implementation widget with the on-device inspector opens the code location for the nearest project widget

### LINKED ISSUE #9252: Error:  Flutter Inspector navigates to framework source instead of user code in Flutter 3.22.3
**Description**

In Flutter 3.32.3, the Flutter Inspector no longer navigates to the widget usage in my codebase when selecting a widget from the widget tree. Instead, it opens the widget definition from the Flutter SDK itself.

For example, when I select a **CupertinoButton** in the Flutter Inspector, instead of opening the line where I used **CupertinoButton** in my own Dart file (e.g. **home_screen.dart**), it jumps directly to the Flutter SDK source (**cupertino.dart**).

This behavior breaks the expected functionality where the Inspector should navigate to the actual widget usage in user code (i.e. call site), not its definition.

----------------------------------

**Steps to Reproduce:**

1. Create a Flutter app.

2. Use a standard widget like **CupertinoButton** or **ElevatedButton** in your widget tree:

```
CupertinoButton(
  child: Text('Click'),
  onPressed: () {},
)
```
3. Run in debug mode with Flutter 3.32.3

4. Open Flutter Inspector and select the button widget in the widget tree.

5. Inspector opens the Flutter SDK source instead of your own Dart file.

----------------------------------

**Expected Behavior:**

Flutter Inspector should open the file and line where the widget is used in my application code, not inside the Flutter SDK.

----------------------------------

**Actual Behavior:**

Inspector opens **cupertino.dart**, **material.dart,** or another SDK file where the widget is defined, ignoring the actual location of usage in my project.

### PR DESCRIPTION
**Pull request by elliette**
Fixes https://github.com/flutter/devtools/issues/9252

Previously, if a user selected a widget that was not created in their project files using the on-device inspector, we would open the code location for that widget. Now, we open the code location of the nearest ancestor widget in their project files. (e.g., a user selects `RichText` in the framework, we open the `Text` widget in their project)

Users can still open the code location for a Flutter framework or third-party package widget by explicitly selecting it in the DevTools widget tree. See more details/rationale on issue comment https://github.com/flutter/devtools/issues/9252#issuecomment-3368491936

_Note: This resolves one of the top user complaints in the 2025 DevTools user survey._

project_file_fix

### CODE REVIEW

File: packages/flutter/test/widgets/widget_inspector_test.dart [hunk 1]
```diff
@@ -939,31 +939,20 @@ class _TestWidgetInspectorService extends TestWidgetInspectorService {
     });
 
     testWidgets(
-      'WidgetInspector Exit Selection Mode button',
+      'On-device selection test',
```
Comment (elliette) [inline packages/flutter/test/widgets/widget_inspector_test.dart:942]: This test was not actually testing anything to do with the exit selection mode button. Renamed the test for clarity, and added an exit selection mode button test below.

**Comment by elliette** [comment]
Please review test changes with **Hide whitespaces** due to moving test cases into a group.

Screenshot 2025-10-04 at 12 37 28 PM

**Review by srawlins — APPROVED** [review]
LGTM!
