### PR TITLE
[RawKeyboard, Web, macOS] Upper keys should generate lower logical keys

### LINKED ISSUE #94610: Cmd+Shift+key shortcuts don't work on macOS
## Steps to Reproduce

1. Do `flutter create shortcuts_test`
2. Replace main.dart with the code below:
3. `flutter run`
4. Press Cmd+Z a few times, then Cmd+Shift+Z.

**Expected results:** Counter is incremented on pressing Cmd+Shift+Z

**Actual results:** Cmd+Shift+Z shortcut handler isn't called

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _undo() {
    setState(() { _counter--; });
  }

  void _redo() {
    setState(() { _counter++; });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Shortcuts(
        shortcuts: <LogicalKeySet, Intent>{
          LogicalKeySet(LogicalKeyboardKey.meta, LogicalKeyboardKey.keyZ): const UndoIntent(),
          LogicalKeySet(LogicalKeyboardKey.meta, LogicalKeyboardKey.shift, LogicalKeyboardKey.keyZ): const RedoIntent(),
        },
        child: Actions(
          actions: <Type, Action<Intent>>{
            UndoIntent: CallbackAction(onInvoke: (_) => _undo()),
            RedoIntent: CallbackAction(onInvoke: (_) => _redo()),
          },
          child: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                const TextField(),
                const Text('Undo/redo counter:'),
                Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headline4,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class UndoIntent extends Intent {
  const UndoIntent();
}

class RedoIntent extends Intent {
  const RedoIntent();
}
```

</details>

<details>
  <summary>Logs</summary>

```
% flutter doctor -v
[✓] Flutter (Channel master, 2.6.0-12.0.pre.896, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.896 at /Library/Frameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9412edf1ca (19 hours ago), 2021-12-02 16:29:05 -0500
    • Engine revision 1a76ac24c5
    • Dart version 2.16.0 (build 2.16.0-56.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jsmith/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
% 
```

</details>

### PR DESCRIPTION
**Pull request by dkwingsmt**
This PR fixes RawKeyboard on Web and macOS so that letter keys with shift keys (such as `Shift-A`) will still yield `RawKeyEvent`s with the correct logical key (`keyA`). This was a regression introduced by https://github.com/flutter/flutter/pull/80756.

Fixes https://github.com/flutter/flutter/issues/94610 and https://github.com/flutter/flutter/issues/90167.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/services/raw_keyboard_common.dart [hunk 1]
```diff
@@ -0,0 +1,31 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+
+/// Converts upper letters to lower letters in ASCII and extended ASCII, and
+/// returns as-is otherwise.
+///
+/// Independent of locale.
+int toLower(int n) {
```
Comment (gspencergoog) [inline packages/flutter/lib/src/services/raw_keyboard_common.dart:10]: Does `String.toLowerCase()` not do extended ASCII? Otherwise, it would be preferable to use the Dart standard method.

They standard method appears to be pretty exhaustive:
https://github.com/dart-lang/sdk/blob/b06b60702b9e85585c3979c69ca91df85204173f/sdk/lib/_internal/vm/lib/string_patch.dart#L1214

**Review by gspencergoog — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/services/raw_keyboard_macos.dart [hunk 2]
```diff
@@ -10,6 +10,16 @@ import 'keyboard_key.dart';
 import 'keyboard_maps.dart';
 import 'raw_keyboard.dart';
 
+/// Convert a UTF32 rune to its lower case.
+int runeToLowerCase(int rune) {
+  // Assume only BMP runes have lower and upper cases. For other characters,
```
Comment (gspencergoog) [inline packages/flutter/lib/src/services/raw_keyboard_macos.dart:15]: Maybe write out BMP as Basic Multilingual Plane.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d
