### PR TITLE
Fix broken text field with set hint and min and max lines(#153183)

### LINKED ISSUE #52008: Unexpected behaviour of TextField hintMaxLines property
I am using the `hintMaxLines` property of the TextField which unexpectedly increases the TextField height even if the hint is not shown (See images below)

**TextField when Hint is displayed:**
Screenshot 2020-03-05 at 12 08 59

**TextField when Hint is not shown:**
Screenshot 2020-03-05 at 12 09 02

**Expected TextField when Hint is not shown:**
Screenshot 2020-03-05 at 12 09 20

In the last image i forced the `hintMaxLines = 1` if a text value was inserted by the user. 

**Code:**

```
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomeScreen(title: 'Flutter Demo Home Page'),
    );
  }
}

class HomeScreen extends StatefulWidget {
  HomeScreen({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  TextEditingController controller = TextEditingController();

  bool isEmpty = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Container(
          padding: EdgeInsets.all(16),
          child: TextField(
            keyboardType: TextInputType.multiline,
            maxLines: null,
            controller: controller,
            onChanged: (value) {
              setState(() {
                // Toggle this for expected behavior
                // isEmpty = value.isEmpty;
              });
            },
            decoration: InputDecoration(
                labelText: 'Title',
                hintMaxLines: isEmpty ? 15 : 1,
                hintText:
                  Iterable.generate(400, (index) => 'a').join(),
                    errorText: 'This is an error'),
          ),
        ));
  }
}

```

**Flutter Doctor:**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

### LINKED ISSUE #153183: Broken text field with set hint and min and max lines
### Steps to reproduce
1. use new stable Flutter (3.24.0) - I believe this is a new issue
1. Just place`TextField` with long hint, minLines = 1, maxLines=4 (example values)
2. type in a short text

### Expected results

I except the field to have as many lines as the short text needs, not the hint (when it's not visible)

### Actual results

when we have long hint and it needs more lines, even though we typed some short text and the hint is not visible, the text fields still have as many lines as the hint needs

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool useHint = true;

  void toggleHint() {
    setState(() {
      useHint = !useHint;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: 200,
              decoration: BoxDecoration(
                  border: Border.all(color: Colors.blue, width: 4.0)),
              child: TextField(
                minLines: 1, // this here causes problem
                maxLines: 4, // this here causes problem
                decoration: InputDecoration(
                    hintText: useHint // with hint there is a problem
                        ? "veeeery loooooooooooooooooong hiiiintttttttttt"
                        : null),
              ),
            ),
            Switch(value: useHint, onChanged: (_) => toggleHint())
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/dd3d5ab5-82f5-44f9-a75d-3bffd6f9d206

</details>

### Logs

<details open><summary>Logs</summary>

[https://pastebin.com/EuCj4Cvk](https://pastebin.com/EuCj4Cvk)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
shark@sharkbook hint_issue % fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.24.0, on macOS 14.4.1 23E224 darwin-arm64, locale pl-PL)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.17.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/shark/fvm/versions/stable. Consider adding /Users/shark/fvm/versions/stable/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
[✓] VS Code (version 1.92.1)
[✓] Connected device (4 available)
[✓] Network resources```

</details>

### PR DESCRIPTION
**Pull request by zeqinjie**
Fix https://github.com/flutter/flutter/issues/153183
Fix https://github.com/flutter/flutter/issues/52008

Pre-launch Checklist
- [x] I read the [Contributor Guide](https://github.com/flutter/flutter/wiki/Tree-hygiene#overview) and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene](https://github.com/flutter/flutter/wiki/Tree-hygiene) wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo), including [Features we expect every widget to implement](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement).
- [x] I signed the [CLA](https://cla.developers.google.com/).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with ///).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord](https://github.com/flutter/flutter/wiki/Chat).

### CODE REVIEW

File: packages/flutter/lib/src/material/text_form_field.dart [hunk 1]
```diff
@@ -292,6 +294,9 @@ class TextFormField extends FormField<String> {
   /// {@macro flutter.widgets.editableText.groupId}
   final Object groupId;
 
+  /// Whether the hint view do not be created when there is input text.
```
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/text_form_field.dart:297]: `hintText` is on InputDecoration so that class seems to be a better place to add this api?

**Review by LongCatIsLooong — COMMENTED** [review]
Looks like the feature is achievable without any flutter code changes. You can set the hintText to null when the text field becomes non-empty. Also having long hint text usually isn't great UX since it goes away as soon as you start typing.

**Comment by zeqinjie** [comment]
> Looks like the feature is achievable without any flutter code changes. You can set the hintText to null when the text field becomes non-empty. Also having long hint text usually isn't great UX since it goes away as soon as you start typing.

@LongCatIsLooong Thank you for your review, yes, but we need additional logic to update textField, so I added a variable to control it for the convenience of users.

File: packages/flutter/lib/src/material/text_form_field.dart (hunk 1 above)
[the remark this answers is not in the document]
Comment (zeqinjie) [reply packages/flutter/lib/src/material/text_form_field.dart]: @LongCatIsLooong Thank you for your review，i have updated~

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 2]
```diff
@@ -3557,6 +3560,11 @@ class InputDecoration {
   /// a default height based on text size.
   final BoxConstraints? constraints;
 
+  /// Whether the hint text should be adapt its height when the user enters text.
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/input_decorator.dart:3563]: Maybe: 

Whether the input field's height should always be greater than or equal to the height of the hint text, even if the hint text is not visible.

This is useful when [hintText] is ...... 

Defaults to false, which allows the input field to ignore the height of the [hintText] during layout when it is not displayed.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/input_decorator.dart:3563]: also consider updating the field name accordingly

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 3]
```diff
@@ -2163,7 +2163,8 @@ class _InputDecoratorState extends State<InputDecorator> with TickerProviderStat
 
     final TextStyle hintStyle = _getInlineHintStyle(themeData, defaults);
     final String? hintText = decoration.hintText;
-    final Widget? hint = hintText == null ? null : AnimatedOpacity(
+    final bool adjustHeightForHintOnInput = !isEmpty && decoration.adjustHeightForHintOnInput;
+    final Widget? hint = (adjustHeightForHintOnInput || hintText == null) ? null : AnimatedOpacity(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/input_decorator.dart:2167]: This change will break the fadeout animation. If the flag is set, then the hintText disappears immediately.

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 2 above)
Comment (zeqinjie) [reply packages/flutter/lib/src/material/input_decorator.dart]: Thank you for your review, I got it

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 3 above)
Comment (zeqinjie) [reply packages/flutter/lib/src/material/input_decorator.dart]: @LongCatIsLooong Thank you for your review, I got it

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/input_decorator.dart]: I think with the new implementation it will still disappear immediately without the fade out animation.

Comment (zeqinjie) [reply packages/flutter/lib/src/material/input_decorator.dart]: @LongCatIsLooong Thank you for your review, I have updated~
Simulator Screen Recording - iPhone 15 Pro Max - 2024-09-01 at 14 01 52

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 4]
```diff
@@ -2163,20 +2163,32 @@ class _InputDecoratorState extends State<InputDecorator> with TickerProviderStat
...
         style: hintStyle,
         textDirection: decoration.hintTextDirection,
         overflow: hintStyle.overflow ?? (decoration.hintMaxLines == null ? null : TextOverflow.ellipsis),
         textAlign: textAlign,
         maxLines: decoration.hintMaxLines,
-      ),
-    );
-
+      );
+      hint = hintIgnoreHeightOnInput ? AnimatedSwitcher(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/input_decorator.dart:2180]: I tried this out and unfortunately this doesn't work very well:
- There is no fade-out animation for the hint text.
- The size of the input decorator becomes too big when there's text.

Comment (zeqinjie) [reply packages/flutter/lib/src/material/input_decorator.dart:2178]: @LongCatIsLooong thx,  i update curve, and it is my test code.
```
 /// after
  buildTextField() {
    return Container(
      width: 200,
      decoration: BoxDecoration(
        border: Border.all(
          color: Colors.blue,
        ),
      ),
      child: TextField(
        controller: controller,
        minLines: 1,
        maxLines: 2,
        decoration: InputDecoration(
          hintText: 'To be, or not to be, that is question' * 10,
          hintIgnoreHeightOnInput: true,
          hintFadeDuration: const Duration(seconds: 1),
        ),
      ),
    );
  }
 /// beford
  buildTextField2() {
    return Container(
      width: 200,
      decoration: BoxDecoration(
        border: Border.all(
          color: Colors.green,
        ),
      ),
      child: TextField(
        controller: controller2,
        minLines: 1,
        maxLines: 2,
        decoration: InputDecoration(
          hintText: 'To be, or not to be, that is question' * 10,
          hintFadeDuration: const Duration(seconds: 1),
        ),
      ),
    );
  }
```

https://github.com/user-attachments/assets/08072d28-b29d-4ce4-aae6-06f0bb739dc9

Comment (zeqinjie) [reply packages/flutter/lib/src/material/input_decorator.dart:2178]: > I tried this out and unfortunately this doesn't work very well:
> 
> * There is no fade-out animation for the hint text.
> * The size of the input decorator becomes too big when there's input text, when hint text size is supposed to be (0, 0)

@LongCatIsLooong It seems that the hintFadeDuration time needs to be set, otherwise the fadeout effect will not be visible.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/input_decorator.dart:2178]: Still it doesn't seem to fix the sizing. When there's no hint text the text field becomes even taller with this change.

Comment (zeqinjie) [reply packages/flutter/lib/src/material/input_decorator.dart:2178]: @LongCatIsLooong Sorry, I don't quite understand what you mean. Can you explain the problem in detail or provide the code I tested?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/input_decorator.dart:2178]: Ah sorry I wasn't clear. This is my test app:
```dart
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(
        child: TextField(
          decoration: InputDecoration(
            hintText: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' * 5,
            hintMaxLines: 3,
            hintFadeDuration: Duration(seconds: 5),
          ),
        )
      ),
    ),
  ));
```
with this patch applied, the text field becomes much taller when I enter text into the text field, than it would be without the patch. Without the patch the text field would be roughly as tall as the characters. You can see that in widget inspectors or if you dump the render tree in the console.

Comment (zeqinjie) [reply packages/flutter/lib/src/material/input_decorator.dart:2178]: @LongCatIsLooong Thank you very much for the test code you provided, I fixed it.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 5]
```diff
@@ -2904,6 +2923,15 @@ class InputDecoration {
   /// If [InputDecorationTheme.hintFadeDuration] is null defaults to 20ms.
   final Duration? hintFadeDuration;
 
+  /// Whether the input field's height should always be greater than or equal to
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/input_decorator.dart:2926]: With the docs the field name should probably be negated (e.g. `maintainHintHeight`).

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 6]
```diff
@@ -2904,6 +2923,15 @@ class InputDecoration {
...
+  /// the height of the [hintText], even if the [hintText] is not visible.
+  ///
+  /// This is useful, If true, while inputting it will ignore the height of the [hintText]
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/input_decorator.dart:2929]: If you change the flag name to `mantainHintHeight`: Maybe: `The [InputDecorator] widget ignores [hintText] during layout when it's not visible, if this flag is set to false.`

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 7]
```diff
@@ -2163,20 +2163,37 @@ class _InputDecoratorState extends State<InputDecorator> with TickerProviderStat
...
+        transitionBuilder: (Widget child, Animation<double> animation) {
+          return FadeTransition(
+            opacity: CurvedAnimation(
+              parent: animation,
+              curve: _kTransitionCurve,
+            ),
+            child: child,
+          );
+        },
+        child: showHint ? hintTextWidget : const SizedBox.shrink(),
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/input_decorator.dart:2189]: Does it work if we only change the leaf here based on the flag? i.e.:
```dart
child: !hintIgnoreHeightOnInput || showHint ? hintTextWidget : const SizedBox.shrink(),
 ```
So we can get rid of the `AnimatedOpacity` branch?

Comment (zeqinjie) [reply packages/flutter/lib/src/material/input_decorator.dart:2189]: @LongCatIsLooong I’m sorry, but I tried it, but it seems that it can’t hide the hint, and there’s no animation effect.

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 6 above)
Comment (zeqinjie) [reply packages/flutter/lib/src/material/input_decorator.dart]: @LongCatIsLooong  Thx for your review, so mantainHintHeight default to true?  i update it ~

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/input_decorator.dart]: Yeah. Also could you keep the first sentence?

Comment (zeqinjie) [reply packages/flutter/lib/src/material/input_decorator.dart]: @LongCatIsLooong ok , I update

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/input_decorator.dart]: Sorry I meant this:

```dart
  /// Whether the input field's height should always be greater than or equal to
  /// the height of the [hintText], even if the [hintText] is not visible.
  ///
  /// The [InputDecorator] widget ignores [hintText] during layout when
  /// it's not visible, if this flag is set to false.
  ///
  /// Defaults to true.
```

**Review by LongCatIsLooong — APPROVED** [review]
LGTM. Thanks for bearing with me!

**Comment by zeqinjie** [comment]
> LGTM. Thanks for bearing with me!

@LongCatIsLooong Thx, so can we autosubmit?

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 8]
```diff
@@ -2904,6 +2923,15 @@ class InputDecoration {
...
   final Duration? hintFadeDuration;
 
+  /// Whether the input field's height should always be greater than or equal to
+  /// the height of the [hintText], even if the [hintText] is not visible.
+  ///
+  /// The [InputDecorator] widget ignores [hintText] during layout when
+  /// it's not visible, if this flag is set to false.
+  ///
+  /// Defaults to true.
+  final bool maintainHintHeight;
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/input_decorator.dart:2933]: Why do we need this new property? I think PR is a bug fix, not a new feature, so we should just make the behavior the same as `maintainHintHeight = false` without allowing `maintainHintHeight = true`.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/input_decorator.dart:2933]: This is a new (opt-in) feature. Changing the current behavior will probably be breaking (although from a UX perspective the hint text should typically be as brief as possible so it shouldn't be multiline in most cases).

Comment (dkwingsmt) [reply packages/flutter/lib/src/material/input_decorator.dart:2933]: But as stated in https://github.com/flutter/flutter/issues/153183 this was (probably) broken recently, which in my opinion should be considered a regression, and should be fixed without the concern of breaking projects that rely on it.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/input_decorator.dart:2933]: I don't think that's true, there's [an older issue](https://github.com/flutter/flutter/issues/52008) from 2020. I think the behavior just became more noticeable after a different bug is fixed (https://github.com/flutter/flutter/pull/148423). The input decorator widget has always been taking the hint height into account afaik.

Comment (dkwingsmt) [reply packages/flutter/lib/src/material/input_decorator.dart:2933]: Ok that makes sense. Thanks for pointing out.

File: packages/flutter/test/material/input_decorator_test.dart [hunk 9]
```diff
@@ -4505,6 +4505,21 @@ void main() {
       final Text hintTextWidget = tester.widget(hintTextFinder);
       expect(hintTextWidget.style!.overflow, decoration.hintStyle!.overflow);
     });
+
+    testWidgets('hint should be ignore its height when input text', (WidgetTester tester) async {
```
Comment (dkwingsmt) [inline packages/flutter/test/material/input_decorator_test.dart:4509]:
```suggestion
    testWidgets('Ignore hint height on non-empty text', (WidgetTester tester) async {
```

File: packages/flutter/test/material/input_decorator_test.dart [hunk 10]
```diff
@@ -4505,6 +4505,21 @@ void main() {
...
+        hintText: hintText,
+        maintainHintHeight: false,
+      );
+
+      await tester.pumpWidget(
+        buildInputDecorator(
+          decoration: decoration,
+        ),
+      );
+      expect(find.text(hintText), findsNothing);
```
Comment (dkwingsmt) [inline packages/flutter/test/material/input_decorator_test.dart:4521]: Rather than finding no hint text, I think it's better to test the widget height. Something like
```
    expect(tester.getSize(find.byType(InputDecorator)).height, lessThan(100));
```

File: packages/flutter/test/material/input_decorator_test.dart [hunk 11]
```diff
@@ -4505,6 +4505,21 @@ void main() {
...
+    });
```
Comment (dkwingsmt) [inline packages/flutter/test/material/input_decorator_test.dart:4522]: Also, add another test without specifying `maintainHintHeight` to test the default behavior.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 12]
```diff
@@ -2163,20 +2163,37 @@ class _InputDecoratorState extends State<InputDecorator> with TickerProviderStat
...
-      ),
-    );
-
+      );
+      hint = maintainHintHeight ? AnimatedOpacity(
+        opacity: showHint ? 1.0 : 0.0,
+        duration: decoration.hintFadeDuration ?? _kHintFadeTransitionDuration,
+        curve: _kTransitionCurve,
+        child: hintTextWidget,
+      ) : AnimatedSwitcher(
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/input_decorator.dart:2183]: The animation logic seems complicated. I don't know what the expectation is here, but we probably want to test any non-trivial behavior. (Consider `AnimationSheetBuilder`)

File: packages/flutter/test/material/input_decorator_test.dart (hunk 9 above)
Comment (zeqinjie) [reply packages/flutter/test/material/input_decorator_test.dart]: @dkwingsmt thank you, i update my test

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 12 above)
Comment (zeqinjie) [reply packages/flutter/lib/src/material/input_decorator.dart:2183]: @dkwingsmt Sorry, I don't know much about the AnimationSheetBuilder component, so I refer to `testWidgets('InputDecoration.collapsed accepts hintFadeDuration')`

File: packages/flutter/test/material/input_decorator_test.dart [hunk 13]
```diff
@@ -4505,6 +4505,120 @@ void main() {
       final Text hintTextWidget = tester.widget(hintTextFinder);
       expect(hintTextWidget.style!.overflow, decoration.hintStyle!.overflow);
     });
+
+    testWidgets('Not Maintain hint height on non-empty text', (WidgetTester tester) async {
```
Comment (dkwingsmt) [inline packages/flutter/test/material/input_decorator_test.dart:4509]:
```suggestion
    testWidgets('Widget height collapses from hint height when maintainHintHeight is false', (WidgetTester tester) async {
```

File: packages/flutter/test/material/input_decorator_test.dart [hunk 14]
```diff
@@ -4505,6 +4505,120 @@ void main() {
...
+
+      await tester.pumpWidget(
+        buildInputDecorator(
+          decoration: decoration,
+        ),
+      );
+      expect(tester.getSize(find.byType(InputDecorator)).height, 48.0);
+    });
+
+    testWidgets('Maintain hint height on non-empty text', (WidgetTester tester) async {
```
Comment (dkwingsmt) [inline packages/flutter/test/material/input_decorator_test.dart:4525]:
```suggestion
    testWidgets('Widget height stays at hint height by default', (WidgetTester tester) async {
```

File: packages/flutter/test/material/input_decorator_test.dart [hunk 15]
```diff
@@ -4505,6 +4505,120 @@ void main() {
...
+        buildInputDecorator(
+          decoration: decoration,
+        ),
+      );
+      final double hintHeight = tester.getSize(find.text(hintText)).height;
+      final double inputHeight = tester.getSize(find.byType(InputDecorator)).height;
+      expect(inputHeight, hintHeight + 16.0);
+    });
+
+    testWidgets('Not Maintain hint height from non-empty to empty text accepts hintFadeDuration', (WidgetTester tester) async {
```
Comment (dkwingsmt) [inline packages/flutter/test/material/input_decorator_test.dart:4542]:
```suggestion
    testWidgets('hintFadeDuration applies to hint fade-in when maintainHintHeight is false', (WidgetTester tester) async {
```

File: packages/flutter/test/material/input_decorator_test.dart [hunk 16]
```diff
@@ -4505,6 +4505,120 @@ void main() {
...
+      expect(hintOpacity50ms, inExclusiveRange(0.0, 1.0));
+      await tester.pump(const Duration(milliseconds: 50));
+      final double hintOpacity100ms = getHintOpacity(tester);
+      expect(hintOpacity100ms, inExclusiveRange(hintOpacity50ms, 1.0));
+      await tester.pump(const Duration(milliseconds: 20));
+      final double hintOpacity120ms = getHintOpacity(tester);
+      expect(hintOpacity120ms, 1.0);
+    });
+
+    testWidgets('Not Maintain hint height from empty to non-empty text accepts hintFadeDuration', (WidgetTester tester) async {
```
Comment (dkwingsmt) [inline packages/flutter/test/material/input_decorator_test.dart:4581]:
```suggestion
    testWidgets('hintFadeDuration applies to hint fade-out when maintainHintHeight is false', (WidgetTester tester) async {
```

**Review by dkwingsmt — APPROVED** [review]
LGTM with test name suggestions

**Comment by dkwingsmt** [comment]
The tests for fade-in and fade-out are interestingly built. Great job, and thanks for your contribution!

**Comment by zeqinjie** [comment]
> The tests for fade-in and fade-out are interestingly built. Great job, and thanks for your contribution!

@dkwingsmt thank you for your review, i had updated test name
