### PR TITLE
Fixes FocusHighlightMode on Android when typing in software keyboard

### LINKED ISSUE #180746: [Android] Software keyboard backspace makes focus highlightMode invalid
### Steps to reproduce

1. flutter create --platforms android highlightMode
2. Copy paste the code sample below
3. Start android simulator phone
4. flutter run
5. Touch the textfield to open the software keyboard and enter some text
7. Delete a letter with backspace
8. Observe the FocusHighlightMode become traditional

### Expected results

The focus highlightMode should stay `FocusHighlightMode.touch`

### Actual results

The focus highlightMode becomes `FocusHighlightMode.traditional` when pressing the backspace

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'Flutter Demo', home: const MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final mode = FocusManager.instance.highlightMode;

    return Scaffold(
      body: Column(
        spacing: 32,
        mainAxisAlignment: .center,
        children: [
          Text(mode.toString()),
          TextField(onChanged: (_) => setState(() {})),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
✓] Flutter (Channel stable, 3.38.5, on macOS 26.2 25C56 darwin-arm64, locale fr-FR) [587ms]
    • Flutter version 3.38.5 on channel stable at /Users/romanojw10/.puro/envs/stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f6ff1529fd (4 weeks ago), 2025-12-11 11:50:07 -0500
    • Engine revision 1527ae0ec5
    • Dart version 3.10.4
    • DevTools version 2.51.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations,
      enable-native-assets, omit-legacy-version-file, enable-lldb-debugging

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2,1s]
    • Android SDK at /Users/romanojw10/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 35.0.0
    • ANDROID_HOME = /Users/romanojw10/Library/Android/sdk
    • Java binary at: /Users/romanojw10/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.7+-13880790-b1038.58)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 26.2) [693ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17C52
    ✗ CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome) [14ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Connected device (2 available) [7,0s]
    • sdk gphone64 arm64 (mobile)                • emulator-5554             • android-arm64 • Android 16 (API 36) (emulator)
    • macOS (desktop)                            • macos                     • darwin-arm64  • macOS 26.2 25C56 darwin-arm64

[✓] Network resources [325ms]
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by romaingyh**
When typing in a textfield on android mobile, the backspace key produces a KeyEvent message that switches the FocusHighlightMode from touch to traditional.

This PR ignores key messages when raw data include the FLAG_SOFT_KEYBOARD or when the device id is VIRTUAL_KEYBOARD

Fixes #180746 

I know it uses deprecated APIs `RawKeyEvent` and `RawKeyEventData` but I couldn't find any other solutions and the initial system is also based on deprecated `KeyMessage`.

Side note: 
I think the var `_lastInteractionRequiresTraditionalHighlights` name is a bit misleading. When it's true the mode is switched to touch and when it's false to traditional. Shouldn't it be the opposite?
 
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 1]
```diff
@@ -2187,9 +2187,27 @@ class _HighlightModeManager {
...
+    return (data.flags & _kAndroidSoftKeyboardFlag) != 0 ||
+        data.deviceId == _kAndroidVirtualKeyboardDeviceId;
+  }
+
   bool handleKeyMessage(KeyMessage message) {
+    final bool isFromVirtualKeyboard = _isKeyMessageFromAndroidIME(message);
+
     // ignore: use_if_null_to_convert_nulls_to_bools
-    if (_lastInteractionRequiresTraditionalHighlights != false) {
+    if (!isFromVirtualKeyboard && _lastInteractionRequiresTraditionalHighlights != false) {
```
Comment (loic-sharma) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: We'll eventually want to migrate this logic from the legacy raw key events to the new hardware key events. When we do this, this logic should no longer be necessary. Let's leave ourselves some breadcrumbs so that it's easier to understand what work needs to be done here when we migrate this logic to hardware key events.

Consider something like:

```dart
bool handleKeyMessage(KeyMessage message) {
  // Update highlightMode first, since things responding to the keys might
  // look at the highlight mode, and it should be accurate.
  // ignore: use_if_null_to_convert_nulls_to_bools
  if (_lastInteractionRequiresTraditionalHighlights != false) {
    // Android sends raw key events for "Backspace" key events from virtual
    // keyboards. These shouldn't switch the highlight mode to traditional.
    // See: https://github.com/flutter/flutter/issues/180746
    // TODO(team-text-input): Remove this virtual keyboard check when we
    // migrate to HardwareKeyboard:
    // https://github.com/flutter/flutter/issues/136419
    final bool isFromVirtualKeyboard = _isKeyMessageFromAndroidIME(message);
    if (!isFromVirtualKeyboard) {
      _lastInteractionRequiresTraditionalHighlights = false;
      updateMode();
    }
  }

  ...
```

File: packages/flutter/test/widgets/focus_manager_test.dart [hunk 2]
```diff
@@ -1491,6 +1491,39 @@ void main() {
       expect(FocusManager.instance.highlightMode, equals(FocusHighlightMode.traditional));
     }, variant: TargetPlatformVariant.all());
 
+    testWidgets(
```
Comment (loic-sharma) [inline packages/flutter/test/widgets/focus_manager_test.dart:1495]:
```suggestion
    // Regression test for https://github.com/flutter/flutter/pull/180753
    testWidgets(
```

**Review by loic-sharma — COMMENTED** [review]
This looks good to me, but I left some minor comments to leave ourselves breadcrumbs to make it easier for us to migrate this logic to `HardwareKeyboard` in the future.

File: packages/flutter/test/widgets/focus_manager_test.dart [hunk 3]
```diff
@@ -1491,6 +1491,39 @@ void main() {
...
+      (WidgetTester tester) async {
+        await setupWidget(tester);
+
+        FocusManager.instance.highlightStrategy = FocusHighlightStrategy.automatic;
+        await tester.tap(find.byType(Container), warnIfMissed: false);
+        await tester.pump();
+
+        expect(FocusManager.instance.highlightMode, equals(FocusHighlightMode.touch));
+
+        // simulates a soft keyboard key event
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/focus_manager_test.dart]: super nit:  capitalization and period `Simulates a soft keyboard key event.`

**Review by Renzo-Olivares — APPROVED** [review]
LGTM with some small nits and modulo @loic-sharma comments.

**Review by loic-sharma — APPROVED** [review]
I'm heading out on vacation for two weeks, so I'll approve this now even though there are still test failures.

**Comment by justinmc** [comment]
@romaingyh FYI there are still a few failures here.
