### PR TITLE
[web] Use pointer-events: auto for non-interactive leaf semantics nodes

### LINKED ISSUE #182493: OverlayPortal overlay content allows click-through to underlying widgets when ensureSemantics() is enabled
When SemanticsBinding.instance.ensureSemantics() is active (which is the default behavior when a screen reader is active or on many Web configurations), hit-testing on content rendered via OverlayPortal behaves incorrectly. Pointer events seem to "pierce" or pass through the overlay content and trigger widgets situated physically behind the overlay.

This issue does not occur if ensureSemantics() is not called (i.e., when the semantics tree is not actively built).

### Steps to reproduce

- Run the code sample on a platform where semantics can be enabled (e.g., Chrome/Web, or macOS/Windows with ensureSemantics() call).
- Click the text "Press to show/hide tooltip" to open the yellow overlay.
- Observe that the yellow overlay ("Tooltip") appears covering part of the screen.
- Click strictly on the yellow overlay area (ensure you are clicking the overlay, not the text behind it).

### Expected results

The click should land on the yellow overlay (consuming the event or doing nothing). It should not trigger the TextButton underneath.

### Actual results

The click passes through the yellow overlay and triggers the TextButton's onPressed callback (toggling the overlay again or executing the button's action).

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

/// Flutter code sample for [OverlayPortal].
void main() => runApp(const OverlayPortalExampleApp());

class OverlayPortalExampleApp extends StatelessWidget {
  const OverlayPortalExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('OverlayPortal Example')),
        body: const Center(child: ClickableTooltipWidget()),
      ),
    );
  }
}

class ClickableTooltipWidget extends StatefulWidget {
  const ClickableTooltipWidget({super.key});

  @override
  State<StatefulWidget> createState() => ClickableTooltipWidgetState();
}

class ClickableTooltipWidgetState extends State<ClickableTooltipWidget> {
  final OverlayPortalController _tooltipController = OverlayPortalController();
  
  @override
  void initState() {
     // Triggering semantics causes the hit-test issue
     SemanticsBinding.instance.ensureSemantics();
     super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        TextButton(
          onPressed: _tooltipController.toggle,
          child: DefaultTextStyle(
            style: DefaultTextStyle.of(context).style.copyWith(fontSize: 50),
            child: OverlayPortal(
              controller: _tooltipController,
              overlayChildBuilder: (BuildContext context) {
                return Positioned(
                  left: 100,
                  top: 60,
                  // This box appears over the UI, but clicks pass through it 
                  // to the button behind it when semantics are enabled.
                  child: ColoredBox(
                    color: Colors.amberAccent,
                    child: const SizedBox(
                      width: 200, 
                      height: 100, 
                      child: Center(child: Text('Tooltip (Click me)')),
                    ),
                  ),
                );
              },
              child: const Text('Press to show/hide tooltip'),
            ),
          ),
        ),
      ],
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

| With `ensureSemantics` (Bug) | Without `ensureSemantics` (Correct) |
| --- | --- |
| <video src="https://github.com/user-attachments/assets/f9d3f6a7-69f3-4385-a79c-9e2928b7081d"> | <video src="https://github.com/user-attachments/assets/864cee4d-1475-4c6b-b461-361efd3b1a45"> |

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.35.4, on macOS 26.1 25B78 darwin-arm64, locale en-US) [710ms]
    • Flutter version 3.35.4 on channel stable at /Users/djanko/fvm/versions/3.35.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d693b4b9db (5 months ago), 2025-09-16 14:27:41 +0000
    • Engine revision c298091351
    • Dart version 3.9.2
    • DevTools version 2.48.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android,
      enable-ios, cli-animations, enable-lldb-debugging

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [3.0s]
    • Android SDK at /Users/djanko/Library/Android/sdk
    • Emulator version 36.1.9.0 (build_id 13823996) (CL:N/A)
    • Platform android-36, build-tools 35.0.0
    • ANDROID_HOME = /Users/djanko/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.8+-14196175-b1038.72)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.1.1) [1,734ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17B100
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2025.2) [6ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.8+-14196175-b1038.72)

[✓] VS Code (version 1.108.2) [5ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.128.0

[✓] Connected device (2 available) [7.6s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 26.1 25B78 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 144.0.7559.134

[✓] Network resources [315ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by flutter-zl**
Fixes https://github.com/flutter/flutter/issues/182493

**Problem**

When semantics are enabled, `OverlayPortal` overlay content cannot receive pointer events. Clicks pass through the overlay to the widget underneath because every non-interactive semantics DOM node was assigned `pointer-events: none`, bypassing the browser's z-index stacking order.

**Fix**

Non-interactive leaf semantics nodes now use `pointer-events: auto` instead of `none`. This delegates hit testing to the browser's native z-index stacking, so higher-z-index overlays naturally intercept events. Containers keep `none` (children handle their own events), and explicit `transparent` nodes (e.g. platform views) also keep `none`.

**Demo**

Before change 
https://flutter-demo-13-before.web.app

After change
https://flutter-demo-13-afte.web.app

Steps: click "Press to show/hide tooltip" → click the yellow tooltip box. 
Before: toggles the button behind it. A
fter: click lands on the overlay.

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart [hunk 1]
```diff
@@ -2006,10 +2008,21 @@ class SemanticsObject {
...
+    //            browser's z-index hit testing so that higher-z-index overlays
+    //            (e.g. OverlayPortal content) correctly intercept events.
     if (semanticRole!.acceptsPointerEvents) {
       element.style.pointerEvents = 'all';
-    } else {
+    } else if (hitTestBehavior == ui.SemanticsHitTestBehavior.transparent || hasChildren) {
       element.style.pointerEvents = 'none';
+    } else {
+      element.style.pointerEvents = 'auto';
     }
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart:2026]: Mixing conditions like this doesn't seem ideal. Can we fully rely on `hitTestBehavior`?

```suggestion
    switch (hitTestBehavior) {
      case ui.SemanticsHitTestBehavior.opaque:
        element.style.pointerEvents = 'all';
      case ui.SemanticsHitTestBehavior.transparent:
        // The framework should automatically set containers to `transparent`.
        element.style.pointerEvents = 'none';
      case ui.SemanticsHitTestBehavior.defer:
        element.style.pointerEvents = 'auto';
    }
```

Comment (chunhtai) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart:2026]: This is ideal, but this may be a bit hard to implement though.

Comment (flutter-zl) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart:2026]: The switch approach is cleaner, but it requires the framework to explicitly set transparent on all container nodes.
Today, only 3 places set hitTestBehavior to a non-defer value: platform_view.dart (transparent) and dialog.dart/bottom_sheet.dart (opaque). All other container nodes stay at the default defer. So a pure switch would assign pointer-events: auto to containers too, breaking the assumption that children handle their own events.

**Review by chunhtai — APPROVED** [review]
LGTM, but should wait for @mdebbar 's approval

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart (hunk 1 above)
Comment (chunhtai) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart:2026]: since this is a web corner case, I think will be better to handle internally in web engine.

Comment (mdebbar) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart:2026]: Got it, thanks for clarifying.

Is it fair to say that `opaque` and `transparent` values from the framework should be 100% respected, and the engine should only make a decision within the `defer` case?

i.e. something like this with clear separation:

```dart
switch (hitTestBehavior) {
  case ui.SemanticsHitTestBehavior.opaque:
    // Repect the framework's request for `opaque`.
    element.style.pointerEvents = 'all';
    return;
  case ui.SemanticsHitTestBehavior.transparent:
    // Repect the framework's request for `transparent`.
    element.style.pointerEvents = 'none';
    return;
  case ui.SemanticsHitTestBehavior.defer:
    // The engine should do a best effort to decide below.
    break;
}

if (semanticRole!.acceptsPointerEvents) {
  element.style.pointerEvents = 'all';
} else if (hasChildren) {
  element.style.pointerEvents = 'none';
} else {
  element.style.pointerEvents = 'auto';
}
```

Comment (mdebbar) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart:2026]: Another thing is, in the past, when `acceptsPointerEvents` returns false, there was an expectation that `pointer-events` would be set to `none`, but now it's being set to `auto` in some cases. This could break things like platform views:
https://github.com/flutter/flutter/blob/eb0b756f6e05e1d0e71ae2dc2cd84d4cc4fea75f/engine/src/flutter/lib/web_ui/lib/src/engine/semantics/platform_view.dart#L32-L37

Comment (mdebbar) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart:2026]: Oh never mind, platform views are configured as `transparent` at the framework level:

https://github.com/flutter/flutter/blob/eb0b756f6e05e1d0e71ae2dc2cd84d4cc4fea75f/packages/flutter/lib/src/rendering/platform_view.dart#L282

**Review by mdebbar — APPROVED** [review]
My comments are merely suggestions, but shouldn't block this PR!
