### PR TITLE
Fix bug parsing Gradle version.

### LINKED ISSUE #8298: unable to locate gradle (gradle-3.2 clearly installed)
## Logs
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Exception from flutter run: Exception: Unable to locate gradle. Please install Android Studio.
package:flutter_tools/src/base/common.dart 29                          throwToolExit
package:flutter_tools/src/android/gradle.dart 97                       ensureGradle
package:flutter_tools/src/android/gradle.dart 122                      buildGradleProject
package:flutter_tools/src/commands/build_apk.dart 598                  buildAndroidWithGradle
package:flutter_tools/src/commands/build_apk.dart 609                  buildApk
package:flutter_tools/src/android/android_device.dart 281              AndroidDevice.startApp
package:flutter_tools/src/run_hot.dart 167                             HotRunner._run
package:flutter_tools/src/run_hot.dart 79                              HotRunner.run.<fn>
package:stack_trace/src/chain.dart 93                                  Chain.capture.<fn>
dart:async/zone.dart 1150                                              _rootRun
dart:async/zone.dart 1026                                              _CustomZone.run
dart:async/zone.dart 1503                                              runZoned
package:stack_trace/src/chain.dart 91                                  Chain.capture
package:flutter_tools/src/run_hot.dart 78                              HotRunner.run
package:flutter_tools/src/commands/daemon.dart 406                     AppDomain.startApp.<fn>
package:flutter_tools/src/base/context.dart 76                         AppContext._run
package:flutter_tools/src/base/context.dart 66                         AppContext.runInZone.<fn>
dart:async/zone.dart 1150                                              _rootRun
dart:async/zone.dart 1026                                              _CustomZone.run
dart:async/zone.dart 1503                                              runZoned
package:flutter_tools/src/base/context.dart 65                         AppContext.runInZone
package:flutter_tools/src/commands/daemon.dart 732                     AppInstance._runInZone
package:flutter_tools/src/commands/daemon.dart 404                     AppDomain.startApp
package:flutter_tools/src/commands/run.dart 216                        RunCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148              FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/commands/run.dart 199                        RunCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119              FlutterCommand.run
package:args/command_runner.dart 194                                   CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 221       FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                                   CommandRunner.run.<fn>
dart:async/future.dart 208                                             Future.Future.sync
package:args/command_runner.dart 109                                   CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 150       FlutterCommandRunner.run
package:flutter_tools/executable.dart 128                              main.<fn>.<fn>
package:stack_trace/src/chain.dart 93                                  Chain.capture.<fn>
dart:async/zone.dart 1150                                              _rootRun
dart:async/zone.dart 1026                                              _CustomZone.run
dart:async/zone.dart 1503                                              runZoned
package:stack_trace/src/chain.dart 91                                  Chain.capture
package:flutter_tools/executable.dart 127                              main.<fn>
package:flutter_tools/src/base/context.dart 76                         AppContext._run
package:flutter_tools/src/base/context.dart 66                         AppContext.runInZone.<fn>
dart:async/zone.dart 1150                                              _rootRun
dart:async/zone.dart 1026                                              _CustomZone.run
dart:async/zone.dart 1503                                              runZoned
package:flutter_tools/src/base/context.dart 65                         AppContext.runInZone
package:flutter_tools/executable.dart 98                               main
/home/darrell/flutter/packages/flutter_tools/bin/flutter_tools.dart 8  main
dart:isolate-patch/isolate_patch.dart 259                              _startIsolate.<fn>
dart:isolate-patch/isolate_patch.dart 148                              _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/future_impl.dart 22                                         _Completer.completeError
package:flutter_tools/src/android/gradle.dart 104                      ensureGradle
===== asynchronous gap ===========================
dart:async/zone.dart 1061                                              _CustomZone.registerCallback
dart:async/zone.dart 949                                               _CustomZone.bindCallback
dart:async/schedule_microtask.dart 148                                 scheduleMicrotask
dart:async/future.dart 182                                             Future.Future.microtask
package:flutter_tools/src/android/gradle.dart                          ensureGradle
package:flutter_tools/src/android/gradle.dart 122                      buildGradleProject
===== asynchronous gap ===========================
dart:async/zone.dart 1061                                              _CustomZone.registerCallback
dart:async/zone.dart 949                                               _CustomZone.bindCallback
dart:async/schedule_microtask.dart 148                                 scheduleMicrotask
dart:async/future.dart 182                                             Future.Future.microtask
package:flutter_tools/src/android/gradle.dart                          buildGradleProject
package:flutter_tools/src/commands/build_apk.dart 598                  buildAndroidWithGradle
===== asynchronous gap ===========================
dart:async/zone.dart 1061                                              _CustomZone.registerCallback
dart:async/zone.dart 949                                               _CustomZone.bindCallback
dart:async/schedule_microtask.dart 148                                 scheduleMicrotask
dart:async/future.dart 182                                             Future.Future.microtask
package:flutter_tools/src/commands/build_apk.dart                      buildAndroidWithGradle
package:flutter_tools/src/commands/build_apk.dart 609                  buildApk
===== asynchronous gap ===========================
dart:async/zone.dart 1061                                              _CustomZone.registerCallback
dart:async/zone.dart 949                                               _CustomZone.bindCallback
dart:async/schedule_microtask.dart 148                                 scheduleMicrotask
dart:async/future.dart 182                                             Future.Future.microtask
package:flutter_tools/src/commands/build_apk.dart                      buildApk
package:flutter_tools/src/android/android_device.dart 281              AndroidDevice.startApp
===== asynchronous gap ===========================
dart:async/zone.dart 1073                                              _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 27                                   _asyncThenWrapperHelper
package:flutter_tools/src/android/android_device.dart                  AndroidDevice.startApp
package:flutter_tools/src/run_hot.dart 167                             HotRunner._run
===== asynchronous gap ===========================
dart:async/zone.dart 1073                                              _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 27                                   _asyncThenWrapperHelper
package:flutter_tools/src/run_hot.dart                                 HotRunner._run
package:flutter_tools/src/run_hot.dart 79                              HotRunner.run.<fn>
package:stack_trace/src/chain.dart 93                                  Chain.capture.<fn>
dart:async/zone.dart 1150                                              _rootRun
dart:async/zone.dart 1026                                              _CustomZone.run
dart:async/zone.dart 1503                                              runZoned
package:stack_trace/src/chain.dart 91                                  Chain.capture
package:flutter_tools/src/run_hot.dart 78                              HotRunner.run
package:flutter_tools/src/commands/daemon.dart 406                     AppDomain.startApp.<fn>
```

## Flutter Doctor
```
/home/darrell/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/darrell/flutter
    • Framework revision 1e1f7703cc (2 hours ago), 2017-02-21 12:22:26
    • Engine revision ab09530927
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /home/darrell/Android/Sdk
    • Platform android-25, build-tools 25.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

[-] Android Studio (version 2.3)
    • Android Studio at /home/darrell/android-studio
    ✗ Gradle not found.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.10

[-] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.3019.10
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1 (API 25) (emulator)
Process finished with exit code 0
```

------------------------------------------
Using IDEA 2016.3 since the plugin isn't available for the 2017 version yet.

Up until yesterday flutter_gallery worked but hello_services failed to find gradle.

I've flutter upgraded most days and gallery worked at least last week.

ls -al android-studio/gradle
total 16
drwxrwxr-x. 4 darrell darrell 4096 Dec 15 21:10 .
drwxrwxr-x. 8 darrell darrell 4096 Feb 21 05:00 ..
drwxrwxr-x. 6 darrell darrell 4096 Dec 15 21:10 gradle-3.2
drwxrwxr-x. 8 darrell darrell 4096 Nov 28 17:52 m2repository
[darrell@localhost ~]$ ls -al /home/darrell/android-studio/gradle

### PR DESCRIPTION
**Pull request by jakobr-google**
Version from pub_semver requires versions of the format X.Y.Z. Gradle
doesn't follow semantic versioning, though, so version parsing would
fail on versions like '3.2'. Fixed by writing a custom Version class.

Also removed a check for apksigner when building Gradle-based projects.

Fixes #8298

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/version.dart [hunk 1]
```diff
@@ -0,0 +1,86 @@
+// Copyright 2017 The Chromium Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+class Version implements Comparable<Version> {
+  static final RegExp versionPattern =
+      new RegExp(r'^(\d+)(\.(\d+)(\.(\d+))?)?');
```
Comment (mravn-google) [inline packages/flutter_tools/lib/src/base/version.dart]: Perhaps add a $ at the end to match the ^ at the beginning?

File: packages/flutter_tools/lib/src/base/version.dart [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+      return new Version._(major, minor, patch, text);
+    } on FormatException {
+      throw new FormatException('Could not parse "$text".');
+    }
+  }
+
+  static Version get unknown => new Version(0, 0, 0, text: 'unknown');
+
+  @override
+  bool operator ==(dynamic other) {
```
Comment (mravn-google) [inline packages/flutter_tools/lib/src/base/version.dart]: The `==` operator ignores `_text`. Is that on purpose?

According to your tests it is. Perhaps just mention that in a comment?

File: packages/flutter_tools/lib/src/base/version.dart [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+  /// The original string representation of the version number.
+  ///
+  /// This preserves textual artifacts like leading zeros that may be left out
+  /// of the parsed version.
+  final String _text;
+
+  /// Creates a new [Version] object.
+  factory Version(int major, int minor, int patch, {String text}) {
+    if (text == null) {
+      text = major ?? '0';
```
Comment (mravn-google) [inline packages/flutter_tools/lib/src/base/version.dart]: You probably want to convert `major` into a String.

File: packages/flutter_tools/test/utils_test.dart [hunk 4]
```diff
@@ -79,4 +80,36 @@ baz=qux
       }
     });
   });
+
+  group('Version', () {
+    test('can parse and compare', () {
```
Comment (mravn-google) [inline packages/flutter_tools/test/utils_test.dart]: `new Version(null, null, null).toString()` might lead to trouble?

If you get more tests, you may want to split your single `test` into atoms.

**Review by mravn-google — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/base/version.dart (hunk 1 above)
Comment (jakobr-google) [inline packages/flutter_tools/lib/src/base/version.dart]: I left it off on purpose, so it'd still match something like '1.2.3-foo', in case we ever came across that.

File: packages/flutter_tools/lib/src/base/version.dart (hunk 3 above)
Comment (jakobr-google) [inline packages/flutter_tools/lib/src/base/version.dart]: I most certainly do!

File: packages/flutter_tools/lib/src/base/version.dart (hunk 2 above)
Comment (jakobr-google) [inline packages/flutter_tools/lib/src/base/version.dart]: Done.

File: packages/flutter_tools/test/utils_test.dart (hunk 4 above)
Comment (jakobr-google) [inline packages/flutter_tools/test/utils_test.dart]: No trouble anymore.

**Review by jakobr-google — COMMENTED** [review]
Thanks for the review!
