### PR TITLE
Remove use of announce in time_picker and remove double Feedback.forTap calls

### LINKED ISSUE #166448: Android TalkBack announces previous radio button's unchecked state when tapping a new radio button wrapped in Feedback.wrapForTap
**Platform:** Android (with TalkBack enabled)

**Context:**

This issue was observed while refactoring the Material Time Picker's AM/PM selector (`packages/flutter/lib/src/material/time_picker.dart`). The goal of the refactoring is to move away from using `SemanticService.announce` and instead rely on a more idiomatic semantic widget tree that self-describes the state changes. Custom radio buttons using `Feedback.wrapForTap` were implemented for the AM/PM selection.
https://github.com/flutter/flutter/issues/165510

**Problem Description:**

When using a group of custom radio buttons where each button is wrapped in `Feedback.wrapForTap`, tapping on a button (other than the first one selected) causes the TalkBack screen reader on Android to announce the state change of the *previously selected* button (checked/not checked) *after* announcing the state change of the *currently tapped* button (becoming checked/unchecked).

**Steps to Reproduce:**

1.  Enable the TalkBack screen reader on an Android device.
2.  Run the minimal reproduction code provided below.
3.  Go to "Item 1" radio button. TalkBack announces its selection correctly (e.g., "not checked, Item 1, Radio").
4.  Tap the "Item 1" radio button. TalkBack announces its selection correctly (e.g., "checked").
5.  Go to "Item 2" radio button. TalkBack announces its selection correctly (e.g., "not checked, Item 2, Radio").
6.  Tap the "Item 2" radio button. TalkBack **does not** announcesits selection correctly (e.g., "checked, not checked").

**Expected Results:**

When tapping "Item 2", TalkBack should *only* announce the state of the tapped element (e.g, "checked")

The state change of the previously selected element ("Item 1") should not be announced as part of the interaction with "Item 2".

**Actual Results:**

When tapping "Item 2" after "Item 1" was selected, TalkBack announces the state change of *both* elements:
> "checked, not checked"

**Video:**

[Link to video demonstrating the issue](https://github.com/user-attachments/assets/7fa899a0-4950-40a9-a4d2-4ba42ca38143)

**Minimal Reproduction Code:**

```
import 'package:flutter/material.dart';

void main() {
  runApp(App(child: Radio()));
}

class App extends StatelessWidget {
  final Widget child;

  const App({
    super.key,
    required this.child,
  });

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Radio Sample')),
        body: Center(child: child),
      ),
    );
  }
}

class Radio extends StatefulWidget {
  const Radio({super.key});

  @override
  State<Radio> createState() => _RadioState();
}

class _RadioState extends State<Radio> {
  var selected = 0;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Semantics(
          checked: selected == 1,
          button: true,
          inMutuallyExclusiveGroup: true,
          child: InkWell(
            onTap: Feedback.wrapForTap(() {
              setState(() {
                selected = 1;
              });
            }, context),
            child: Text("${selected == 1 ? "X " : ""}Item 1"),
          ),
        ),
        Semantics(
          checked: selected == 2,
          button: true,
          inMutuallyExclusiveGroup: true,
          child: InkWell(
            onTap: Feedback.wrapForTap(() {
              setState(() {
                selected = 2;
              });
            }, context),
            child: Text("${selected == 2 ? "X " : ""}Item 2"),
          ),
        ),
        Semantics(
          checked: selected == 3,
          button: true,
          inMutuallyExclusiveGroup: true,
          child: InkWell(
            onTap: Feedback.wrapForTap(() {
              setState(() {
                selected = 3;
              });
            }, context),
            child: Text("${selected == 3 ? "X " : ""}Item 3"),
          ),
        ),
      ],
    );
  }
}
```

### PR DESCRIPTION
**Pull request by ash2moon**
This pull request replaces the use of the deprecated announce calls with idiomatic Semantic widgets and also removes the extra `Feedback.forTap` call. The `InkWell` widget already wraps the onTap with the `Feedback.forTap`. I also made sure sure that existing functionality is not impacted.

Resolves https://github.com/flutter/flutter/issues/166448
Partially addresses https://github.com/flutter/flutter/issues/165510

Physical Testing:
Android ✅
iOS ✅
Web ✅

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/time_picker.dart [hunk 1]
```diff
@@ -250,9 +250,13 @@ class _TimePickerHeader extends StatelessWidget {
...
-    switch (_TimePickerModel.orientationOf(context)) {
-      case Orientation.portrait:
-        return Column(
+    return Semantics(
+      label: MaterialLocalizations.of(context).formatTimeOfDay(
+        _TimePickerModel.selectedTimeOf(context),
+        alwaysUse24HourFormat: MediaQuery.alwaysUse24HourFormatOf(context),
+      ),
+      child: switch (_TimePickerModel.orientationOf(context)) {
+        Orientation.portrait => Column(
```
[the remark this answers is not in the document]
Comment (reidbaker) [reply packages/flutter/lib/src/material/time_picker.dart:259]: Ignore this request.

**Comment by QuncCccccc** [comment]
I can take a look! But I probably will ask @chunhtai for a second review, as he is the accessibility expert! Please let me know when it's ready😊

File: packages/flutter/lib/src/material/time_picker.dart [hunk 2]
```diff
@@ -250,9 +250,14 @@ class _TimePickerHeader extends StatelessWidget {
     ).timeOfDayFormat(alwaysUse24HourFormat: _TimePickerModel.use24HourFormatOf(context));
 
     final _HourDialType hourDialType = _TimePickerModel.hourDialTypeOf(context);
-    switch (_TimePickerModel.orientationOf(context)) {
-      case Orientation.portrait:
-        return Column(
+    return Semantics(
+      key: const ValueKey<String>('time-picker-header-semantics'),
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart:254]: we should avoid adding key for testing purposes like this.

If the purpose is to ensure the semantics label is correct in test, you can use find.bySemanticsLabel('your expected label') and findsOneWidget

File: packages/flutter/lib/src/material/time_picker.dart [hunk 3]
```diff
@@ -250,9 +250,14 @@ class _TimePickerHeader extends StatelessWidget {
...
+      label: MaterialLocalizations.of(context).formatTimeOfDay(
+        _TimePickerModel.selectedTimeOf(context),
+        alwaysUse24HourFormat: MediaQuery.alwaysUse24HourFormatOf(context),
+      ),
+      child: switch (_TimePickerModel.orientationOf(context)) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart:259]: Consider store the switch result into a child first for readability

File: packages/flutter/lib/src/material/time_picker.dart [hunk 4]
```diff
@@ -250,9 +250,14 @@ class _TimePickerHeader extends StatelessWidget {
     ).timeOfDayFormat(alwaysUse24HourFormat: _TimePickerModel.use24HourFormatOf(context));
 
     final _HourDialType hourDialType = _TimePickerModel.hourDialTypeOf(context);
-    switch (_TimePickerModel.orientationOf(context)) {
-      case Orientation.portrait:
-        return Column(
+    return Semantics(
+      key: const ValueKey<String>('time-picker-header-semantics'),
+      label: MaterialLocalizations.of(context).formatTimeOfDay(
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart:255]: Can you explain a bit why we need a label here, is the previous behavior broken?

File: packages/flutter/lib/src/material/time_picker.dart [hunk 5]
```diff
@@ -1328,18 +1299,9 @@ class _DialState extends State<_Dial> with SingleTickerProviderStateMixin {
     _center = box.size.center(Offset.zero);
     _dialSize = box.size;
     _updateThetaForPan(roundMinutes: true);
-    final TimeOfDay newTime = _notifyOnChangedIfNeeded(roundMinutes: true);
+    _notifyOnChangedIfNeeded(roundMinutes: true);
     if (widget.hourMinuteMode == _HourMinuteMode.hour) {
-      switch (widget.hourDialType) {
-        case _HourDialType.twentyFourHour:
-        case _HourDialType.twentyFourHourDoubleRing:
-          _announceToAccessibility(context, localizations.formatDecimal(newTime.hour));
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/time_picker.dart:1336]: Since we remove all the announcement, how do we convey the information to user ? I assume there will be a liveregion somewhere?

Same for other announcements.

File: packages/flutter/lib/src/material/time_picker.dart (hunk 4 above)
Comment (ash2moon) [reply packages/flutter/lib/src/material/time_picker.dart:255]: This is because previously we were using `_announceInitialTimeOnce` to announce this time, but now with a label, it is announced when it is in focus.

File: packages/flutter/lib/src/material/time_picker.dart (hunk 5 above)
Comment (ash2moon) [reply packages/flutter/lib/src/material/time_picker.dart:1336]: A lot of these announcements were manually invoked because of the problem with `Feedback.wrapForTap` resulting in double announcements. Since the root cause was due to `InkWell` already doing a `Feedback.wrapForTap`, we did not need the extra wrapper within the `on*` callbacks. I think because of this, the original author used `announce` to prevent Talkback from speaking the double announcement and rewriting its responses.

Comment (reidbaker) [reply packages/flutter/lib/src/material/time_picker.dart:1336]: If in the course of your investigation you found prs or comments that helped you come to this conclusion please add them as a comment here. If not then please do not spend time tracking it down.

File: packages/flutter/lib/src/material/time_picker.dart [hunk 6]
```diff
@@ -250,81 +250,89 @@ class _TimePickerHeader extends StatelessWidget {
...
-              ),
-              child: Text(
-                helpText,
-                style:
-                    _TimePickerModel.themeOf(context).helpTextStyle ??
-                    _TimePickerModel.defaultThemeOf(context).helpTextStyle,
+    final RenderObjectWidget orientationSpecificHeader = switch (_TimePickerModel.orientationOf(
+      context,
+    )) {
+      Orientation.portrait => Column(
```
Comment (reidbaker) [inline packages/flutter/lib/src/material/time_picker.dart:256]: It is out of scope for this pr but I really dont like how we are using the device orientation enum value all over this code for what I think is a proxy for OrientationBuilder.

**Review by reidbaker — APPROVED** [review]

**Review by reidbaker — APPROVED** [review]
Please hold merge until approval from someone on the framework team.

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by ash2moon** [comment]
> @ash2moon Is this PR ready for submission?

It's ready now, just wanted to verify Google testing.
