### PR TITLE
Start logger in startProgress to avoid assertion failure

### LINKED ISSUE #20812: Failed assertion in flutter run --machine
If you run `flutter run --machine` with assertions enabled, you get a crash. I'm testing on macOS using the `examples/hello_world` project. Happens with iOS simulator and flutter-tester at least:

```
dantup-macbookpro:hello_world dantup$ FLUTTER_TOOL_ARGS=--enable-asserts flutter run --machine 
[{"event":"daemon.connected","params":{"version":"0.4.1","pid":40801}}]
[{"event":"app.start","params":{"appId":"72f4edf8-abbb-4e78-83b4-00caa2892206","deviceId":"735F9F08-FF94-4E03-BB0E-FE8FD114610F","directory":"/Users/dantup/Dev/Google/flutter/examples/hello_world","supportsRestart":true}}]
Launching lib/main.dart on iPhone X in debug mode...
[{"event":"app.progress","params":{"appId":"72f4edf8-abbb-4e78-83b4-00caa2892206","id":"0","progressId":null,"message":"Starting Xcode build..."}}]
Unhandled exception:
'package:flutter_tools/src/base/logger.dart': Failed assertion: line 330 pos 12: '_isStarted': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      Status.cancel (package:flutter_tools/src/base/logger.dart:330:12)
#3      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:335:30)
<asynchronous suspension>
#4      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:347:29)
<asynchronous suspension>
#5      IOSSimulator._buildAndInstallApplicationBundle (package:flutter_tools/src/ios/simulators.dart:367:48)
<asynchronous suspension>
#6      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:353:14)
<asynchronous suspension>
#7      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:283:15)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:292:54)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#15     Future._complete (dart:async/future_impl.dart:476:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
dantup-macbookpro:hello_world dantup$ 
```

### PR DESCRIPTION
**Pull request by DanTup**
There are lots of places that create a `Status()` and all but two of them call `..start()` immediately. This is one of the places that doesn't which causes an assertion failure when running with `--enable-asserts` and the other is in the same file (I suspect it's also incorrect, but haven't managed to trigger it yet so I don't want to blindly change it).

Fixes #20812.

### CODE REVIEW

**Comment by Hixie** [comment]
If literally all but one call site call `start()`, and we're not even 100% sure about the last call site, maybe we should just change the API.

**Comment by Hixie** [comment]
test?

**Comment by DanTup** [comment]
> If literally all but one call site call `start()`, and we're not even 100% sure about the last call site, maybe we should just change the API.

I did think that too, but I wasn't sure if it was designed this way for a reason (or if my search didn't find all uses. Possibly making it a named constructor (`new Status.start(...)`) might make it clearer?

If you think we should, I don't mind doing (though it may be best in another PR so we can land this - I 
tried turned asserts on in my bash profile as you'd suggested elsewhere, but this crash is blocking, it totally breaks running apps from an editor).

> test?

This code is somewhat indirectly tested by the integration tests that run `flutter run` (in that they all fail if you have asserts enabled without this fix). I'm not sure how we could specifically test that `start()` was called though; it's implementation looks like this:

```dart
  void start() {
    assert(!_isStarted);
    _isStarted = true;
  }
```

The `_isStarted` variable is private and only used in asserts. Running without asserts effectively means the `start()` does nothing at all, so testing that consuming code is calling it is tricky.

I think I already asked this, but I couldn't find what your response was - can't we run the CIs with asserts enabled? That would've caught this (it would've failed in the PR build). Is the performance hit too high?

**Comment by Hixie** [comment]
Everything is designed its way for a reason, but that shouldn't stop us from making things better. :-)
(Definitely in a separate PR.)
Don't treat anything as holy. If anything is important, it will have been tested.

If it's caught by running with asserts enabled, then yes, let's turn on asserts while running the `flutter_tools` tests from `test.dart`. (That's easy, just set FLUTTER_ARGS in the environment when shelling out to `pub run test` for flutter_tools.) We can't turn on asserts in general because it destroys analyzer performance.

**Comment by DanTup** [comment]
I've pushed a change that enables asserts for these tools tests only (but based on your analyzer comment I'm not sure if this may negatively affect things like tests over `flutter analyze`?).

I made it check that the variable wasn't already set and including this so we don't stamp on any other `FLUTTER_TOOL_ARGS` that might be set (and checked this was working by running like `$ SHARD=tool_tests FLUTTER_TOOL_ARGS=--enable-asserts dart dev/bots/test.dart`.

File: dev/bots/test.dart [hunk 1]
```diff
@@ -294,7 +294,10 @@ Future<Null> _runSmokeTests() async {
 Future<Null> _runToolTests() async {
   await _runSmokeTests();
 
-  await _pubRunTest(path.join(flutterRoot, 'packages', 'flutter_tools'));
+  await _pubRunTest(
+    path.join(flutterRoot, 'packages', 'flutter_tools'),
+    enableAsserts: true,
```
Comment (Hixie) [inline dev/bots/test.dart]: maybe call this enableFlutterToolAsserts to clarify that it doesn't affect whether pub run itself, or the tests themselves, have asserts enabled.

**Comment by Hixie** [comment]
LGTM

**Comment by DanTup** [comment]
First CI failure was a Cirrus issue, second one was a flake on the attach test (which I've since fixed in another PR). Rebased on master (no conflicts), so hopefully will be green soon and I'll land.
