### PR TITLE
Set DEFINES_MODULE for FlutterPluginRegistrant to generate modulemap

### LINKED ISSUE #40289: Support adding Objective-C plugins as static libraries to existing Swift app with CocoaPods
## Steps to Reproduce

1. Create a Flutter module with Objective-C platform code like `url_launcher`
2. Add the module to an existing Swift app.  Make sure `use_frameworks!` is not in the existing app Podfile to create the plugins as static libraries.
3. Build

Build failure:
error: no such module 'FlutterPluginRegistrant'

## Logs

```
Showing Recent Messages
CompileSwift normal x86_64 /Users/m/Projects/flutter-swift-test-31104/SampleiOSFlutter/SampleiOSFlutter/AppDelegate.swift (in target 'SampleiOSFlutter' from project 'SampleiOSFlutter')
    cd /Users/m/Projects/flutter-swift-test-31104/SampleiOSFlutter
    /Users/m/Applications/Xcode-beta6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Users/m/Projects/flutter-swift-test-31104/SampleiOSFlutter/SampleiOSFlutter/ViewController.swift -primary-file /Users/m/Projects/flutter-swift-test-31104/SampleiOSFlutter/SampleiOSFlutter/AppDelegate.swift -emit-module-path /Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/Objects-normal/x86_64/AppDelegate\~partial.swiftmodule -emit-module-doc-path /Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/Objects-normal/x86_64/AppDelegate\~partial.swiftdoc -serialize-diagnostics-path /Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/Objects-normal/x86_64/AppDelegate.dia -emit-dependencies-path /Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/Objects-normal/x86_64/AppDelegate.d -emit-reference-dependencies-path /Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/Objects-normal/x86_64/AppDelegate.swiftdeps -target x86_64-apple-ios12.2-simulator -enable-objc-interop -sdk /Users/m/Applications/Xcode-beta6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk -I /Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Products/Debug-iphonesimulator -F /Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Products/Debug-iphonesimulator -F /Users/m/Projects/flutter-swift-test-31104/FlutterModule/.ios/Flutter -F /Users/m/Projects/flutter-swift-test-31104/FlutterModule/.ios/Flutter/engine -enable-testing -g -module-cache-path /Users/m/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D DEBUG -serialize-debugging-options -Xcc -working-directory -Xcc /Users/m/Projects/flutter-swift-test-31104/SampleiOSFlutter -enable-anonymous-context-mangled-names -Xcc -I/Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/SampleiOSFlutter-generated-files.hmap -Xcc -I/Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/SampleiOSFlutter-own-target-headers.hmap -Xcc -I/Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/SampleiOSFlutter-all-target-headers.hmap -Xcc -iquote -Xcc /Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/SampleiOSFlutter-project-headers.hmap -Xcc -I/Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/m/Projects/flutter-swift-test-31104/SampleiOSFlutter/Pods/Headers/Public -Xcc -I/Users/m/Projects/flutter-swift-test-31104/SampleiOSFlutter/Pods/Headers/Public/FlutterPluginRegistrant -Xcc -I/Users/m/Projects/flutter-swift-test-31104/SampleiOSFlutter/Pods/Headers/Public/url_launcher -Xcc -I/Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/DerivedSources-normal/x86_64 -Xcc -I/Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/DerivedSources/x86_64 -Xcc -I/Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -module-name SampleiOSFlutter -o /Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Build/Intermediates.noindex/SampleiOSFlutter.build/Debug-iphonesimulator/SampleiOSFlutter.build/Objects-normal/x86_64/AppDelegate.o -index-store-path /Users/m/Library/Developer/Xcode/DerivedData/SampleiOSFlutter-dynfdplugzidvkdmfalgbckdklna/Index/DataStore -index-system-modules

/Users/m/Projects/flutter-swift-test/AppDelegate.swift:11:8: error: no such module 'FlutterPluginRegistrant'
import FlutterPluginRegistrant
       ^
```

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Let CocoaPods generate a module map for FlutterPluginRegistrant so it can be imported by existing Swift apps that don't `use_frameworks!` as a static library.

Bonus: existing Objective-C apps can use `@import FlutterPluginRegistrant` syntax and any existing imports or includes will become module imports and leverage the module cache.

See http://blog.cocoapods.org/CocoaPods-1.5.0/.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/40289.
Gives a workaround to https://github.com/flutter/flutter/issues/31104 with Swift apps importing static libraries (don't use `use_frameworks!` in the Podfile).

## Tests

I added a Swift app to the module_test_ios.  They fail before without the DEFINES_MODULE change:
```
[module_test_ios] [STDOUT] stdout: import FlutterPluginRegistrant
[module_test_ios] [STDOUT] stdout:        ^
[module_test_ios] [STDOUT] stdout: 
[module_test_ios] [STDOUT] stderr: ** BUILD FAILED **
```
And pass with the DEFINES_MODULE change.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter_tools/lib/src/plugins.dart [hunk 1]
```diff
@@ -383,6 +383,7 @@ Depends on all your plugins, and provides a function to register them.
   s.source_files =  "Classes", "Classes/**/*.{h,m}"
   s.source           = { :path => '.' }
   s.public_header_files = './Classes/**/*.h'
+  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/plugins.dart]: This is the actual change, everything else is tests.
