### PR TITLE
fix the widget span layout when text scale factor != 1

### LINKED ISSUE #59316: Nested RichText objects apply textScaleFactor multiple times
## Background
When a `RichText` element embeds other `RichText` elements, the scaling and wrapping doesn't work properly when the user's default font size is increased using the device's accessibility settings. Specifically:

* For each level of nesting, it appears as though the `textScaleFactor` value is compounded resulting in extremely large text sizings for deep nesting
* The wrapping boundaries do not appear to be constrained to the screen's width.

Note the same symptoms can be seen using `Text.rich()`, but I've chosen to use `RichText` in the code example below so that I can be super-explicit in demonstrating the exact settings in play.

The example below is a little contrived, but I've tried to extract it to the most bare-bones example I could. For what it is worth, the original problem was encountered when parsing HTML that might look like:

```
<underline><italic><bold>xxxxx</bold></italic></underline>
```

From here, one reasonable technique would be to create a text span containing a bold `xxxxx`, and then wrap that in another span that applies the italics, and then wrap that in another span that applies the underline.

Anyway, the sample program below shows three groups that show slightly different perspectives on the problem:

* The first group contains an element (`scaled3`) that wraps an element (`scaled2`) that wraps another element (`scaled1`). We then dump each of those elements on-screen to see what they look like. All three of these are using the "normal" scaling factor. Essentially, this is the same as using `Rich.text()`.  As you can see, they all scale up much more than the baseline and the wrapping is not correct.
* The second group also contains three nested elements (`notScaled[1-3]`), however, this time, I hard-code the scaling factor to `1.0`. As you can see, they all remain the same size (which is what I'd expect) ... to me, this is a very strong indicator that a `textScaleFactor > 1.0` is what is compounding the size.
* The last group is a single example where it has a 3-deep nested element where all the inner elements contain a `textScaleFactor` of `1.0`, and then it is wrapped in one more that has the "normal" scale factor. As you can see, this time the scaling is only applied once (which is good), but even in this case, the wrapping calculations are incorrect.

## Steps to Reproduce
Run the following program:
```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(home: new MyHomePage());
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final inputText = 'The quick brown fox jumped over the lazy dog. The quick brown fox jumped over the lazy dog.';
    final initialSpan = TextSpan(text: inputText, style: TextStyle(color: Colors.black));

    final scaled1 = _wrap(context, initialSpan, true);
    final scaled2 = _wrap(context, WidgetSpan(child: scaled1), true);
    final scaled3 = _wrap(context, WidgetSpan(child: scaled2), true);

    final notScaled1 = _wrap(context, initialSpan, false);
    final notScaled2 = _wrap(context, WidgetSpan(child: notScaled1), false);
    final notScaled3 = _wrap(context, WidgetSpan(child: notScaled2), false);

    final outerScaling = _wrap(context, WidgetSpan(child: notScaled3), true);

    return new Scaffold(
      appBar: AppBar(title: Text('')),
      body: Column(
        children: [
          // a simple baseline for comparison. scales OK + wraps OK
          Text(inputText),
          // one level deep (standard scaling). scales OK + wraps OK
          scaled1,
          // two levels deep (standard scaling). too big + doesn't wrap properly
          scaled2,
          // three levels deep (standard scaling). way too big + doesn't wrap properly
          scaled3,

          // spacer
          SizedBox(height: 20),

          // one level deep (no scaling). doesn't scale (expected) + wraps OK
          notScaled1,
          // two levels deep (no scaling). doesn't scale (expected) + wraps OK
          notScaled2,
          // three levels deep (no scaling). doesn't scale (expected) + wraps OK
          notScaled3,

          // spacer
          SizedBox(height: 20),

          // no scaling on the inner text(s), but standard scaling on the outer. scales OK + doesn't wrap properly
          outerScaling,
        ],
      ),
    );
  }

  Widget _wrap(BuildContext context, InlineSpan span, bool useNormalStyle) {
    if (useNormalStyle) {
      return RichText(text: span, textScaleFactor: MediaQuery.of(context).textScaleFactor);
    } else {
      return RichText(text: span, textScaleFactor: 1.0);
    }
  }
}
```

**Expected results:**
All rows of text should scale at exactly the same rate.

**Actual results:**
See screenshots:

| Default text scaling | Increased accessibility size |
|---|---|
| ![Simulator Screen Shot - iPhone 11 - 2020-06-12 at 17 23 23](https://user-images.githubusercontent.com/1574429/84480544-109f2500-acd8-11ea-92dd-300d9e181ef3.png) | ![Simulator Screen Shot - iPhone 11 - 2020-06-12 at 17 23 30](https://user-images.githubusercontent.com/1574429/84480559-14cb4280-acd8-11ea-9312-f093397f274f.png) |
 
<details>
  <summary>Logs</summary>

<!--
      Run your application with `flutter run --verbose` and attach all the
      log output below between the lines with the backticks. If there is an
      exception, please see if the error message includes enough information
      to explain how to solve the issue.
-->

```
[ +117 ms] executing: [/Users/edwardsc/dev/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +36 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d9653445f4d1257b5f5adb4b271d1316469e8cf1
[        ] executing: [/Users/edwardsc/dev/flutter/] git tag --contains HEAD
[ +175 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.0-0.0.pre
[  +10 ms] executing: [/Users/edwardsc/dev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/Users/edwardsc/dev/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +54 ms] executing: [/Users/edwardsc/dev/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[   +6 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +14 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G103
[  +40 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +11 ms] executing: /Users/edwardsc/Library/Android/sdk/platform-tools/adb devices -l
[   +6 ms] executing: /usr/bin/xcode-select --print-path
[  +10 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +103 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.2.1
           Build version 11B500
[   +2 ms] executing: xcrun --find xcdevice
[   +8 ms] Exit code 0 from: xcrun --find xcdevice
[        ] /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice
[        ] executing: xcrun xcdevice list --timeout 2
[   +5 ms] /usr/bin/xcrun simctl list --json devices
[        ] executing: /usr/bin/xcrun simctl list --json devices
[  +40 ms] List of devices attached
           R58M45EWRCK            device usb:338690048X product:a20dv model:SM_A205YN device:a20 transport_id:1
[  +73 ms] {
             "devices" : {
               "com.apple.CoreSimulator.SimRuntime.iOS-12-4" : [
                 {
                   "state" : "Shutdown",
                   "isAvailable" : true,
                   "name" : "iPhone 5s",
                   "udid" : "647A64A2-E427-4301-AA51-E413B53A1224"
                 }
               ],
               "com.apple.CoreSimulator.SimRuntime.iOS-11-4" : [

               ],
               "com.apple.CoreSimulator.SimRuntime.tvOS-13-2" : [

               ],
               "com.apple.CoreSimulator.SimRuntime.iOS-13-2" : [
                 {
                   "state" : "Booted",
                   "isAvailable" : true,
                   "name" : "iPhone 11",
                   "udid" : "537708A7-5E27-4804-B6C9-D233D029B49A"
                 }
               ],
               "com.apple.CoreSimulator.SimRuntime.watchOS-6-1" : [
                 {
                   "state" : "Shutdown",
                   "isAvailable" : true,
                   "name" : "Apple Watch Series 4 - 40mm",
                   "udid" : "E79AAB5E-A5B7-4D96-8FB1-882CCBB99B41"
                 },
                 {
                   "state" : "Shutdown",
                   "isAvailable" : true,
                   "name" : "Apple Watch Series 4 - 44mm",
                   "udid" : "7018FC6D-CDD7-42B7-9DC9-C19C6D2FE988"
                 }
               ]
             }
           }
[+2414 ms] [
             {
               "simulator" : true,
               "operatingSystemVersion" : "6.1 (17S83)",
               "available" : true,
               "platform" : "com.apple.platform.watchsimulator",
               "modelCode" : "Watch4,4",
               "identifier" : "7018FC6D-CDD7-42B7-9DC9-C19C6D2FE988",
               "architecture" : "i386",
               "modelName" : "Apple Watch Series 4 - 44mm",
               "name" : "Apple Watch Series 4 - 44mm"
             },
             {
               "simulator" : true,
               "operatingSystemVersion" : "12.4 (16G73)",
               "available" : true,
               "platform" : "com.apple.platform.iphonesimulator",
               "modelCode" : "iPhone6,1",
               "identifier" : "647A64A2-E427-4301-AA51-E413B53A1224",
               "architecture" : "x86_64",
               "modelName" : "iPhone 5s",
               "name" : "iPhone 5s"
             },
             {
               "simulator" : true,
               "operatingSystemVersion" : "13.2.2 (17B102)",
               "available" : true,
               "platform" : "com.apple.platform.iphonesimulator",
               "modelCode" : "iPhone12,1",
               "identifier" : "537708A7-5E27-4804-B6C9-D233D029B49A",
               "architecture" : "x86_64",
               "modelName" : "iPhone 11",
               "name" : "iPhone 11"
             },
             {
               "simulator" : true,
               "operatingSystemVersion" : "6.1 (17S83)",
               "available" : true,
               "platform" : "com.apple.platform.watchsimulator",
               "modelCode" : "Watch4,3",
               "identifier" : "E79AAB5E-A5B7-4D96-8FB1-882CCBB99B41",
               "architecture" : "i386",
               "modelName" : "Apple Watch Series 4 - 40mm",
               "name" : "Apple Watch Series 4 - 40mm"
             }
           ]
[   +4 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +192 ms] Generating /Users/edwardsc/Desktop/text_1/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +82 ms] Starting incremental build...
[   +2 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +4 ms] Launching lib/main.dart on iPhone 11 in debug mode...
[   +5 ms] /Users/edwardsc/dev/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/edwardsc/dev/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/edwardsc/dev/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill /var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/T/flutter_tools.ZLfbtl/flutter_tool.8YWmxV/app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[   +6 ms] executing: /usr/bin/plutil -convert json -o - /Users/edwardsc/Desktop/text_1/ios/Runner/Info.plist
[   +8 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/edwardsc/Desktop/text_1/ios/Runner/Info.plist
[        ] {"CFBundleName":"text_1","CFBundleIdentifier":"$(PRODUCT_BUNDLE_IDENTIFIER)","CFBundleInfoDictionaryVersion":"6.0","UIMainStoryboardFile":"Main","CFBundleVersion":"$(FLUTTER_BUILD_NUMBER)","UILaunchStoryboardName":"LaunchScreen","CFBundleExecutable":"$(EXECUTABLE_NAME)","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrientations":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"UIViewControllerBasedStatusBarAppearance":false,"CFBundleSignature":"????","CFBundlePackageType":"APPL","CFBundleDevelopmentRegion":"$(DEVELOPMENT_LANGUAGE)","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"CFBundleShortVersionString":"$(FLUTTER_BUILD_NAME)"}
[   +4 ms] executing: [/Users/edwardsc/Desktop/text_1/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /Users/edwardsc/Desktop/text_1/ios/Runner.xcodeproj -scheme Runner -showBuildSettings
[        ] executing: [/Users/edwardsc/Desktop/text_1/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /Users/edwardsc/Desktop/text_1/ios/Runner.xcodeproj -scheme Runner -showBuildSettings
[  +13 ms] <- compile package:text_1/main.dart
[+1308 ms] Build settings for action build and target Runner:
               ACTION = build
               AD_HOC_CODE_SIGNING_ALLOWED = NO
               ALTERNATE_GROUP = staff
               ALTERNATE_MODE = u+w,go-w,a+rX
               ALTERNATE_OWNER = edwardsc
               ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO
               ALWAYS_SEARCH_USER_PATHS = NO
               ALWAYS_USE_SEPARATE_HEADERMAPS = NO
               APPLE_INTERNAL_DEVELOPER_DIR = /AppleInternal/Developer
               APPLE_INTERNAL_DIR = /AppleInternal
               APPLE_INTERNAL_DOCUMENTATION_DIR = /AppleInternal/Documentation
               APPLE_INTERNAL_LIBRARY_DIR = /AppleInternal/Library
               APPLE_INTERNAL_TOOLS = /AppleInternal/Developer/Tools
               APPLICATION_EXTENSION_API_ONLY = NO
               APPLY_RULES_IN_COPY_FILES = NO
               APPLY_RULES_IN_COPY_HEADERS = NO
               ARCHS = armv7 arm64
               ARCHS_STANDARD = armv7 arm64
               ARCHS_STANDARD_32_64_BIT = armv7 arm64
               ARCHS_STANDARD_32_BIT = armv7
               ARCHS_STANDARD_64_BIT = arm64
               ARCHS_STANDARD_INCLUDING_64_BIT = armv7 arm64
               ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
               ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
               AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator
               BITCODE_GENERATION_MODE = marker
               BUILD_ACTIVE_RESOURCES_ONLY = NO
               BUILD_COMPONENTS = headers build
               BUILD_DIR = /Users/edwardsc/Desktop/text_1/build/ios
               BUILD_LIBRARY_FOR_DISTRIBUTION = NO
               BUILD_ROOT = /Users/edwardsc/Desktop/text_1/build/ios
               BUILD_STYLE = 
               BUILD_VARIANTS = normal
               BUILT_PRODUCTS_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Release-iphoneos
               CACHE_ROOT = /var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/C/com.apple.DeveloperTools/11.2.1-11B500/Xcode
               CCHROOT = /var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/C/com.apple.DeveloperTools/11.2.1-11B500/Xcode
               CHMOD = /bin/chmod
               CHOWN = /usr/sbin/chown
               CLANG_ANALYZER_NONNULL = YES
               CLANG_CXX_LANGUAGE_STANDARD = gnu++0x
               CLANG_CXX_LIBRARY = libc++
               CLANG_ENABLE_MODULES = YES
               CLANG_ENABLE_OBJC_ARC = YES
               CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
               CLANG_WARN_BOOL_CONVERSION = YES
               CLANG_WARN_COMMA = YES
               CLANG_WARN_CONSTANT_CONVERSION = YES
               CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES
               CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR
               CLANG_WARN_EMPTY_BODY = YES
               CLANG_WARN_ENUM_CONVERSION = YES
               CLANG_WARN_INFINITE_RECURSION = YES
               CLANG_WARN_INT_CONVERSION = YES
               CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
               CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES
               CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
               CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR
               CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
               CLANG_WARN_STRICT_PROTOTYPES = YES
               CLANG_WARN_SUSPICIOUS_MOVE = YES
               CLANG_WARN_UNREACHABLE_CODE = YES
               CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
               CLASS_FILE_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/JavaClasses
               CLEAN_PRECOMPS = YES
               CLONE_HEADERS = NO
               CODESIGNING_FOLDER_PATH = /Users/edwardsc/Desktop/text_1/build/ios/Release-iphoneos/Runner.app
               CODE_SIGNING_ALLOWED = YES
               CODE_SIGNING_REQUIRED = YES
               CODE_SIGN_CONTEXT_CLASS = XCiPhoneOSCodeSignContext
               CODE_SIGN_IDENTITY = iPhone Developer
               CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
               COLOR_DIAGNOSTICS = NO
               COMBINE_HIDPI_IMAGES = NO
               COMPILER_INDEX_STORE_ENABLE = Default
               COMPOSITE_SDK_DIRS = /Users/edwardsc/Desktop/text_1/build/ios/CompositeSDKs
               COMPRESS_PNG_FILES = YES
               CONFIGURATION = Release
               CONFIGURATION_BUILD_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Release-iphoneos
               CONFIGURATION_TEMP_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos
               CONTENTS_FOLDER_PATH = Runner.app
               COPYING_PRESERVES_HFS_DATA = NO
               COPY_HEADERS_RUN_UNIFDEF = NO
               COPY_PHASE_STRIP = NO
               COPY_RESOURCES_FROM_STATIC_FRAMEWORKS = YES
               CORRESPONDING_SIMULATOR_PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               CORRESPONDING_SIMULATOR_PLATFORM_NAME = iphonesimulator
               CORRESPONDING_SIMULATOR_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               CORRESPONDING_SIMULATOR_SDK_NAME = iphonesimulator13.2
               CP = /bin/cp
               CREATE_INFOPLIST_SECTION_IN_BINARY = NO
               CURRENT_ARCH = arm64
               CURRENT_PROJECT_VERSION = 1
               CURRENT_VARIANT = normal
               DART_OBFUSCATION = false
               DEAD_CODE_STRIPPING = YES
               DEBUGGING_SYMBOLS = YES
               DEBUG_INFORMATION_FORMAT = dwarf-with-dsym
               DEFAULT_COMPILER = com.apple.compilers.llvm.clang.1_0
               DEFAULT_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
               DEFAULT_KEXT_INSTALL_PATH = /System/Library/Extensions
               DEFINES_MODULE = NO
               DEPLOYMENT_LOCATION = NO
               DEPLOYMENT_POSTPROCESSING = NO
               DEPLOYMENT_TARGET_CLANG_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_CLANG_FLAG_NAME = miphoneos-version-min
               DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX = -miphoneos-version-min=
               DEPLOYMENT_TARGET_LD_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_LD_FLAG_NAME = ios_version_min
               DEPLOYMENT_TARGET_SETTING_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_SUGGESTED_VALUES = 8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4 13.0 13.1 13.2
               DERIVED_FILES_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DERIVED_FILE_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DERIVED_SOURCES_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/DerivedSources
               DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               DEVELOPER_FRAMEWORKS_DIR = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_FRAMEWORKS_DIR_QUOTED = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/Developer/Library
               DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Tools
               DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               DEVELOPMENT_LANGUAGE = en
               DOCUMENTATION_FOLDER_PATH = Runner.app/en.lproj/Documentation
               DONT_GENERATE_INFOPLIST_FILE = NO
               DO_HEADER_SCANNING_IN_JAM = NO
               DSTROOT = /tmp/Runner.dst
               DT_TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               DWARF_DSYM_FILE_NAME = Runner.app.dSYM
               DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
               DWARF_DSYM_FOLDER_PATH = /Users/edwardsc/Desktop/text_1/build/ios/Release-iphoneos
               EFFECTIVE_PLATFORM_NAME = -iphoneos
               EMBEDDED_CONTENT_CONTAINS_SWIFT = NO
               EMBEDDED_PROFILE_NAME = embedded.mobileprovision
               EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE = NO
               ENABLE_BITCODE = NO
               ENABLE_DEFAULT_HEADER_SEARCH_PATHS = YES
               ENABLE_HARDENED_RUNTIME = NO
               ENABLE_HEADER_DEPENDENCIES = YES
               ENABLE_NS_ASSERTIONS = NO
               ENABLE_ON_DEMAND_RESOURCES = YES
               ENABLE_STRICT_OBJC_MSGSEND = YES
               ENABLE_TESTABILITY = NO
               ENTITLEMENTS_ALLOWED = YES
               ENTITLEMENTS_DESTINATION = Signature
               ENTITLEMENTS_REQUIRED = YES
               EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS = .DS_Store .svn .git .hg CVS
               EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES = *.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj
               EXECUTABLES_FOLDER_PATH = Runner.app/Executables
               EXECUTABLE_FOLDER_PATH = Runner.app
               EXECUTABLE_NAME = Runner
               EXECUTABLE_PATH = Runner.app/Runner
               EXPANDED_CODE_SIGN_IDENTITY = 
               EXPANDED_CODE_SIGN_IDENTITY_NAME = 
               EXPANDED_PROVISIONING_PROFILE = 
               FILE_LIST = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects/LinkFileList
               FIXED_FILES_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/FixedFiles
               FLUTTER_APPLICATION_PATH = /Users/edwardsc/Desktop/text_1
               FLUTTER_BUILD_DIR = build
               FLUTTER_BUILD_NAME = 1.0.0
               FLUTTER_BUILD_NUMBER = 1
               FLUTTER_FRAMEWORK_DIR = /Users/edwardsc/dev/flutter/bin/cache/artifacts/engine/ios
               FLUTTER_ROOT = /Users/edwardsc/dev/flutter
               FLUTTER_TARGET = /Users/edwardsc/Desktop/text_1/lib/main.dart
               FRAMEWORKS_FOLDER_PATH = Runner.app/Frameworks
               FRAMEWORK_FLAG_PREFIX = -framework
               FRAMEWORK_SEARCH_PATHS =  /Users/edwardsc/Desktop/text_1/ios/Flutter
               FRAMEWORK_VERSION = A
               FULL_PRODUCT_NAME = Runner.app
               GCC3_VERSION = 3.3
               GCC_C_LANGUAGE_STANDARD = gnu99
               GCC_INLINES_ARE_PRIVATE_EXTERN = YES
               GCC_NO_COMMON_BLOCKS = YES
               GCC_PFE_FILE_C_DIALECTS = c objective-c c++ objective-c++
               GCC_SYMBOLS_PRIVATE_EXTERN = YES
               GCC_THUMB_SUPPORT = YES
               GCC_TREAT_WARNINGS_AS_ERRORS = NO
               GCC_VERSION = com.apple.compilers.llvm.clang.1_0
               GCC_VERSION_IDENTIFIER = com_apple_compilers_llvm_clang_1_0
               GCC_WARN_64_TO_32_BIT_CONVERSION = YES
               GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR
               GCC_WARN_UNDECLARED_SELECTOR = YES
               GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE
               GCC_WARN_UNUSED_FUNCTION = YES
               GCC_WARN_UNUSED_VARIABLE = YES
               GENERATE_MASTER_OBJECT_FILE = NO
               GENERATE_PKGINFO_FILE = YES
               GENERATE_PROFILING_CODE = NO
               GENERATE_TEXT_BASED_STUBS = NO
               GID = 20
               GROUP = staff
               HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT = YES
               HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES = YES
               HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS = YES
               HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
               HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
               HEADERMAP_USES_VFS = NO
               HIDE_BITCODE_SYMBOLS = YES
               HOME = /Users/edwardsc
               ICONV = /usr/bin/iconv
               INFOPLIST_EXPAND_BUILD_SETTINGS = YES
               INFOPLIST_FILE = Runner/Info.plist
               INFOPLIST_OUTPUT_FORMAT = binary
               INFOPLIST_PATH = Runner.app/Info.plist
               INFOPLIST_PREPROCESS = NO
               INFOSTRINGS_PATH = Runner.app/en.lproj/InfoPlist.strings
               INLINE_PRIVATE_FRAMEWORKS = NO
               INSTALLHDRS_COPY_PHASE = NO
               INSTALLHDRS_SCRIPT_PHASE = NO
               INSTALL_DIR = /tmp/Runner.dst/Applications
               INSTALL_GROUP = staff
               INSTALL_MODE_FLAG = u+w,go-w,a+rX
               INSTALL_OWNER = edwardsc
               INSTALL_PATH = /Applications
               INSTALL_ROOT = /tmp/Runner.dst
               IPHONEOS_DEPLOYMENT_TARGET = 8.0
               JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8
               JAVA_APP_STUB = /System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               JAVA_ARCHIVE_CLASSES = YES
               JAVA_ARCHIVE_TYPE = JAR
               JAVA_COMPILER = /usr/bin/javac
               JAVA_FOLDER_PATH = Runner.app/Java
               JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
               JAVA_JAR_FLAGS = cv
               JAVA_SOURCE_SUBDIR = .
               JAVA_USE_DEPENDENCIES = YES
               JAVA_ZIP_FLAGS = -urg
               JIKES_DEFAULT_FLAGS = +E +OLDCSO
               KASAN_DEFAULT_CFLAGS = -DKASAN=1 -fsanitize=address -mllvm -asan-globals-live-support -mllvm -asan-force-dynamic-shadow
               KEEP_PRIVATE_EXTERNS = NO
               LD_DEPENDENCY_INFO_FILE = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat
               LD_GENERATE_MAP_FILE = NO
               LD_MAP_FILE_PATH = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/Runner-LinkMap-normal-arm64.txt
               LD_NO_PIE = NO
               LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
               LD_RUNPATH_SEARCH_PATHS =  @executable_path/Frameworks
               LEGACY_DEVELOPER_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               LEX = lex
               LIBRARY_DEXT_INSTALL_PATH = /Library/DriverExtensions
               LIBRARY_FLAG_NOSPACE = YES
               LIBRARY_FLAG_PREFIX = -l
               LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
               LIBRARY_SEARCH_PATHS =  /Users/edwardsc/Desktop/text_1/ios/Flutter
               LINKER_DISPLAYS_MANGLED_NAMES = NO
               LINK_FILE_LIST_normal_arm64 = 
               LINK_FILE_LIST_normal_armv7 = 
               LINK_WITH_STANDARD_LIBRARIES = YES
               LLVM_TARGET_TRIPLE_OS_VERSION = ios8.0
               LLVM_TARGET_TRIPLE_VENDOR = apple
               LOCALIZABLE_CONTENT_DIR = 
               LOCALIZED_RESOURCES_FOLDER_PATH = Runner.app/en.lproj
               LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString CFCopyLocalizedString
               LOCALIZED_STRING_SWIFTUI_SUPPORT = YES
               LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
               LOCAL_APPS_DIR = /Applications
               LOCAL_DEVELOPER_DIR = /Library/Developer
               LOCAL_LIBRARY_DIR = /Library
               LOCROOT = 
               LOCSYMROOT = 
               MACH_O_TYPE = mh_execute
               MAC_OS_X_PRODUCT_BUILD_VERSION = 18G103
               MAC_OS_X_VERSION_ACTUAL = 101406
               MAC_OS_X_VERSION_MAJOR = 101400
               MAC_OS_X_VERSION_MINOR = 1406
               METAL_LIBRARY_FILE_BASE = default
               METAL_LIBRARY_OUTPUT_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Release-iphoneos/Runner.app
               MODULES_FOLDER_PATH = Runner.app/Modules
               MODULE_CACHE_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               MTL_ENABLE_DEBUG_INFO = NO
               NATIVE_ARCH = armv7
               NATIVE_ARCH_32_BIT = i386
               NATIVE_ARCH_64_BIT = x86_64
               NATIVE_ARCH_ACTUAL = x86_64
               NO_COMMON = YES
               OBJECT_FILE_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects
               OBJECT_FILE_DIR_normal = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/Objects-normal
               OBJROOT = /Users/edwardsc/Desktop/text_1/build/ios
               ONLY_ACTIVE_ARCH = NO
               OS = MACOS
               OSAC = /usr/bin/osacompile
               OTHER_LDFLAGS =  -framework Flutter
               PACKAGE_TYPE = com.apple.package-type.wrapper.application
               PASCAL_STRINGS = YES
               PATH = /Applications/Xcode.app/Contents/Developer/usr/bin:/Users/edwardsc/.rbenv/shims:/Users/edwardsc/.gem/ruby/2.6.0/bin:/Users/edwardsc/Library/Android/sdk/platform-tools:/Users/edwardsc/Library/Android/sdk/tools:/Users/edwardsc/.pub-cache/bin:/Users/edwardsc/dev/flutter/bin/cache/dart-sdk/bin:/Users/edwardsc/dev/flutter/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/mysql-client/bin:/Users/edwardsc/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/edwardsc/.rbenv/shims:/Users/edwardsc/.gem/ruby/2.6.0/bin:/Users/edwardsc/Library/Android/sdk/platform-tools:/Users/edwardsc/Library/Android/sdk/tools:/Users/edwardsc/.pub-cache/bin:/Users/edwardsc/dev/flutter/bin/cache/dart-sdk/bin:/Users/edwardsc/dev/flutter/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/mysql-client/bin:/Users/edwardsc/bin:/Users/edwardsc/.ec2/bin:/Users/edwardsc/.ec2/bin
               PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES = /usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms
               PBDEVELOPMENTPLIST_PATH = Runner.app/pbdevelopment.plist
               PFE_FILE_C_DIALECTS = objective-c
               PKGINFO_FILE_PATH = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/PkgInfo
               PKGINFO_PATH = Runner.app/PkgInfo
               PLATFORM_DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Applications
               PLATFORM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin
               PLATFORM_DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
               PLATFORM_DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
               PLATFORM_DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Tools
               PLATFORM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr
               PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               PLATFORM_DISPLAY_NAME = iOS
               PLATFORM_NAME = iphoneos
               PLATFORM_PREFERRED_ARCH = arm64
               PLATFORM_PRODUCT_BUILD_VERSION = 17B102
               PLIST_FILE_OUTPUT_FORMAT = binary
               PLUGINS_FOLDER_PATH = Runner.app/PlugIns
               PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR = YES
               PRECOMP_DESTINATION_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/PrefixHeaders
               PRESERVE_DEAD_CODE_INITS_AND_TERMS = NO
               PRIVATE_HEADERS_FOLDER_PATH = Runner.app/PrivateHeaders
               PRODUCT_BUNDLE_IDENTIFIER = com.example.text1
               PRODUCT_BUNDLE_PACKAGE_TYPE = APPL
               PRODUCT_MODULE_NAME = Runner
               PRODUCT_NAME = Runner
               PRODUCT_SETTINGS_PATH = /Users/edwardsc/Desktop/text_1/ios/Runner/Info.plist
               PRODUCT_TYPE = com.apple.product-type.application
               PROFILING_CODE = NO
               PROJECT = Runner
               PROJECT_DERIVED_FILE_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/DerivedSources
               PROJECT_DIR = /Users/edwardsc/Desktop/text_1/ios
               PROJECT_FILE_PATH = /Users/edwardsc/Desktop/text_1/ios/Runner.xcodeproj
               PROJECT_NAME = Runner
               PROJECT_TEMP_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build
               PROJECT_TEMP_ROOT = /Users/edwardsc/Desktop/text_1/build/ios
               PROVISIONING_PROFILE_REQUIRED = YES
               PUBLIC_HEADERS_FOLDER_PATH = Runner.app/Headers
               RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS = YES
               REMOVE_CVS_FROM_RESOURCES = YES
               REMOVE_GIT_FROM_RESOURCES = YES
               REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES = YES
               REMOVE_HG_FROM_RESOURCES = YES
               REMOVE_SVN_FROM_RESOURCES = YES
               RESOURCE_RULES_REQUIRED = YES
               REZ_COLLECTOR_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/ResourceManagerResources
               REZ_OBJECTS_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build/ResourceManagerResources/Objects
               SCAN_ALL_SOURCE_FILES_FOR_INCLUDES = NO
               SCRIPTS_FOLDER_PATH = Runner.app/Scripts
               SDKROOT = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
               SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
               SDK_DIR_iphoneos13_2 = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
               SDK_NAME = iphoneos13.2
               SDK_NAMES = iphoneos13.2
               SDK_PRODUCT_BUILD_VERSION = 17B102
               SDK_VERSION = 13.2
               SDK_VERSION_ACTUAL = 130200
               SDK_VERSION_MAJOR = 130000
               SDK_VERSION_MINOR = 200
               SED = /usr/bin/sed
               SEPARATE_STRIP = NO
               SEPARATE_SYMBOL_EDIT = NO
               SET_DIR_MODE_OWNER_GROUP = YES
               SET_FILE_MODE_OWNER_GROUP = NO
               SHALLOW_BUNDLE = YES
               SHARED_DERIVED_FILE_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Release-iphoneos/DerivedSources
               SHARED_FRAMEWORKS_FOLDER_PATH = Runner.app/SharedFrameworks
               SHARED_PRECOMPS_DIR = /Users/edwardsc/Desktop/text_1/build/ios/SharedPrecompiledHeaders
               SHARED_SUPPORT_FOLDER_PATH = Runner.app/SharedSupport
               SKIP_INSTALL = NO
               SOURCE_ROOT = /Users/edwardsc/Desktop/text_1/ios
               SRCROOT = /Users/edwardsc/Desktop/text_1/ios
               STRINGS_FILE_OUTPUT_ENCODING = binary
               STRIP_BITCODE_FROM_COPIED_FILES = YES
               STRIP_INSTALLED_PRODUCT = YES
               STRIP_STYLE = all
               STRIP_SWIFT_SYMBOLS = YES
               SUPPORTED_DEVICE_FAMILIES = 1,2
               SUPPORTED_PLATFORMS = iphoneos
               SUPPORTS_MACCATALYST = NO
               SUPPORTS_TEXT_BASED_API = NO
               SWIFT_COMPILATION_MODE = wholemodule
               SWIFT_OBJC_BRIDGING_HEADER = Runner/Runner-Bridging-Header.h
               SWIFT_OPTIMIZATION_LEVEL = -O
               SWIFT_PLATFORM_TARGET_PREFIX = ios
               SWIFT_VERSION = 5.0
               SYMROOT = /Users/edwardsc/Desktop/text_1/build/ios
               SYSTEM_ADMIN_APPS_DIR = /Applications/Utilities
               SYSTEM_APPS_DIR = /Applications
               SYSTEM_CORE_SERVICES_DIR = /System/Library/CoreServices
               SYSTEM_DEMOS_DIR = /Applications/Extras
               SYSTEM_DEVELOPER_APPS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               SYSTEM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               SYSTEM_DEVELOPER_DEMOS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples
               SYSTEM_DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               SYSTEM_DEVELOPER_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library
               SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools
               SYSTEM_DEVELOPER_JAVA_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Java Tools
               SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Performance Tools
               SYSTEM_DEVELOPER_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes
               SYSTEM_DEVELOPER_TOOLS = /Applications/Xcode.app/Contents/Developer/Tools
               SYSTEM_DEVELOPER_TOOLS_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools
               SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools
               SYSTEM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               SYSTEM_DEVELOPER_UTILITIES_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities
               SYSTEM_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
               SYSTEM_DOCUMENTATION_DIR = /Library/Documentation
               SYSTEM_KEXT_INSTALL_PATH = /System/Library/Extensions
               SYSTEM_LIBRARY_DIR = /System/Library
               TAPI_VERIFY_MODE = ErrorsOnly
               TARGETED_DEVICE_FAMILY = 1,2
               TARGETNAME = Runner
               TARGET_BUILD_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Release-iphoneos
               TARGET_NAME = Runner
               TARGET_TEMP_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_FILES_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_FILE_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Runner.build/Release-iphoneos/Runner.build
               TEMP_ROOT = /Users/edwardsc/Desktop/text_1/build/ios
               TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               TRACK_WIDGET_CREATION = true
               TREAT_MISSING_BASELINES_AS_TEST_FAILURES = NO
               TREE_SHAKE_ICONS = false
               UID = 501
               UNLOCALIZED_RESOURCES_FOLDER_PATH = Runner.app
               UNSTRIPPED_PRODUCT = NO
               USER = edwardsc
               USER_APPS_DIR = /Users/edwardsc/Applications
               USER_LIBRARY_DIR = /Users/edwardsc/Library
               USE_DYNAMIC_NO_PIC = YES
               USE_HEADERMAP = YES
               USE_HEADER_SYMLINKS = NO
               USE_LLVM_TARGET_TRIPLES = YES
               USE_LLVM_TARGET_TRIPLES_FOR_CLANG = YES
               USE_LLVM_TARGET_TRIPLES_FOR_LD = YES
               USE_LLVM_TARGET_TRIPLES_FOR_TAPI = YES
               VALIDATE_PRODUCT = YES
               VALIDATE_WORKSPACE = NO
               VALID_ARCHS = arm64 arm64e armv7 armv7s
               VERBOSE_PBXCP = NO
               VERSIONING_SYSTEM = apple-generic
               VERSIONPLIST_PATH = Runner.app/version.plist
               VERSION_INFO_BUILDER = edwardsc
               VERSION_INFO_FILE = Runner_vers.c
               VERSION_INFO_STRING = "@(#)PROGRAM:Runner  PROJECT:Runner-1"
               WRAPPER_EXTENSION = app
               WRAPPER_NAME = Runner.app
               WRAPPER_SUFFIX = .app
               WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
               XCODE_APP_SUPPORT_DIR = /Applications/Xcode.app/Contents/Developer/Library/Xcode
               XCODE_PRODUCT_BUILD_VERSION = 11B500
               XCODE_VERSION_ACTUAL = 1121
               XCODE_VERSION_MAJOR = 1100
               XCODE_VERSION_MINOR = 1120
               XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
               YACC = yacc
               arch = arm64
               variant = normal
[  +18 ms] Building Runner.app for 537708A7-5E27-4804-B6C9-D233D029B49A.
[  +14 ms] Xcode workspace settings not found, skipping build system migration
[   +5 ms] executing: xattr -r -d com.apple.FinderInfo /Users/edwardsc/Desktop/text_1/ios
[   +3 ms] executing: /usr/bin/xcrun simctl spawn 537708A7-5E27-4804-B6C9-D233D029B49A log stream --style json --predicate eventType = logEvent AND processImagePath ENDSWITH "Runner" AND (senderImagePath ENDSWITH "/Flutter" OR senderImagePath ENDSWITH "/libswiftCore.dylib" OR processImageUUID == senderImageUUID) AND NOT(eventMessage CONTAINS ": could not find icon for representation -> com.apple.") AND NOT(eventMessage BEGINSWITH "assertion failed: ") AND NOT(eventMessage CONTAINS " libxpc.dylib ")
[ +163 ms] executing: [/Users/edwardsc/Desktop/text_1/ios/] /usr/bin/xcodebuild -list
[+1038 ms] Information about project "Runner":
               Targets:
                   Runner

               Build Configurations:
                   Debug
                   Release
                   Profile

               If no build configuration is specified and -scheme is not passed then "Release" is used.

               Schemes:
                   Runner
[  +45 ms] executing: /usr/bin/plutil -convert json -o - /Users/edwardsc/Desktop/text_1/ios/Runner/Info.plist
[   +8 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/edwardsc/Desktop/text_1/ios/Runner/Info.plist
[        ] {"CFBundleName":"text_1","CFBundleIdentifier":"$(PRODUCT_BUNDLE_IDENTIFIER)","CFBundleInfoDictionaryVersion":"6.0","UIMainStoryboardFile":"Main","CFBundleVersion":"$(FLUTTER_BUILD_NUMBER)","UILaunchStoryboardName":"LaunchScreen","CFBundleExecutable":"$(EXECUTABLE_NAME)","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrientations":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"UIViewControllerBasedStatusBarAppearance":false,"CFBundleSignature":"????","CFBundlePackageType":"APPL","CFBundleDevelopmentRegion":"$(DEVELOPMENT_LANGUAGE)","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"CFBundleShortVersionString":"$(FLUTTER_BUILD_NAME)"}
[   +4 ms] executing: mkfifo /var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/T/flutter_tools.ZLfbtl/flutter_build_log_pipe.sUprNk/pipe_to_stdout
[   +5 ms] Exit code 0 from: mkfifo /var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/T/flutter_tools.ZLfbtl/flutter_build_log_pipe.sUprNk/pipe_to_stdout
[   +3 ms] Running Xcode build...
[   +1 ms] executing: [/Users/edwardsc/Desktop/text_1/ios/] /usr/bin/env xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/edwardsc/Desktop/text_1/build/ios -sdk iphonesimulator -arch x86_64 SCRIPT_OUTPUT_STREAM_FILE=/var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/T/flutter_tools.ZLfbtl/flutter_build_log_pipe.sUprNk/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO
[+2966 ms] Running Xcode build... (completed in 2,957ms, longer than expected)
[   +1 ms]  └─Compiling, linking and signing...
[+4584 ms] Build settings from command line:
               ARCHS = x86_64
               BUILD_DIR = /Users/edwardsc/Desktop/text_1/build/ios
               COMPILER_INDEX_STORE_ENABLE = NO
               FLUTTER_SUPPRESS_ANALYTICS = true
               SCRIPT_OUTPUT_STREAM_FILE = /var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/T/flutter_tools.ZLfbtl/flutter_build_log_pipe.sUprNk/pipe_to_stdout
               SDKROOT = iphonesimulator13.2
               VERBOSE_SCRIPT_LOGGING = YES

           note: Using new build system
           note: Planning build
           note: Constructing build description
           ProcessProductPackaging "" /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios


           Entitlements:

           {
               "application-identifier" = "7333GKPQG5.com.example.text1";
               "keychain-access-groups" =     (
                   "7333GKPQG5.com.example.text1"
               );
           }


               builtin-productPackagingUtility -entitlements -format xml -o /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent

           ProcessProductPackaging "" /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app.xcent (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios


           Entitlements:

           {
               "com.apple.security.get-task-allow" = 1;
           }


               builtin-productPackagingUtility -entitlements -format xml -o /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app.xcent

           PhaseScriptExecution Run\ Script /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios
               export ACTION=build
               export AD_HOC_CODE_SIGNING_ALLOWED=YES
               export ALTERNATE_GROUP=staff
               export ALTERNATE_MODE=u+w,go-w,a+rX
               export ALTERNATE_OWNER=edwardsc
               export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
               export ALWAYS_SEARCH_USER_PATHS=NO
               export ALWAYS_USE_SEPARATE_HEADERMAPS=NO
               export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
               export APPLE_INTERNAL_DIR=/AppleInternal
               export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
               export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
               export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
               export APPLICATION_EXTENSION_API_ONLY=NO
               export APPLY_RULES_IN_COPY_FILES=NO
               export APPLY_RULES_IN_COPY_HEADERS=NO
               export ARCHS=x86_64
               export ARCHS_STANDARD="i386 x86_64"
               export ARCHS_STANDARD_32_64_BIT="i386 x86_64"
               export ARCHS_STANDARD_32_BIT=i386
               export ARCHS_STANDARD_64_BIT=x86_64
               export ARCHS_STANDARD_INCLUDING_64_BIT="i386 x86_64"
               export ARCHS_UNIVERSAL_IPHONE_OS="i386 x86_64"
               export ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon
               export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
               export AppIdentifierPrefix=7333GKPQG5.
               export BITCODE_GENERATION_MODE=marker
               export BUILD_ACTIVE_RESOURCES_ONLY=YES
               export BUILD_COMPONENTS="headers build"
               export BUILD_DIR=/Users/edwardsc/Desktop/text_1/build/ios
               export BUILD_LIBRARY_FOR_DISTRIBUTION=NO
               export BUILD_ROOT=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Products
               export BUILD_STYLE=
               export BUILD_VARIANTS=normal
               export BUILT_PRODUCTS_DIR=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator
               export CACHE_ROOT=/var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/C/com.apple.DeveloperTools/11.2.1-11B500/Xcode
               export CCHROOT=/var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/C/com.apple.DeveloperTools/11.2.1-11B500/Xcode
               export CHMOD=/bin/chmod
               export CHOWN=/usr/sbin/chown
               export CLANG_ANALYZER_NONNULL=YES
               export CLANG_CXX_LANGUAGE_STANDARD=gnu++0x
               export CLANG_CXX_LIBRARY=libc++
               export CLANG_ENABLE_MODULES=YES
               export CLANG_ENABLE_OBJC_ARC=YES
               export CLANG_MODULES_BUILD_SESSION_FILE=/Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation
               export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING=YES
               export CLANG_WARN_BOOL_CONVERSION=YES
               export CLANG_WARN_COMMA=YES
               export CLANG_WARN_CONSTANT_CONVERSION=YES
               export CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS=YES
               export CLANG_WARN_DIRECT_OBJC_ISA_USAGE=YES_ERROR
               export CLANG_WARN_EMPTY_BODY=YES
               export CLANG_WARN_ENUM_CONVERSION=YES
               export CLANG_WARN_INFINITE_RECURSION=YES
               export CLANG_WARN_INT_CONVERSION=YES
               export CLANG_WARN_NON_LITERAL_NULL_CONVERSION=YES
               export CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF=YES
               export CLANG_WARN_OBJC_LITERAL_CONVERSION=YES
               export CLANG_WARN_OBJC_ROOT_CLASS=YES_ERROR
               export CLANG_WARN_RANGE_LOOP_ANALYSIS=YES
               export CLANG_WARN_STRICT_PROTOTYPES=YES
               export CLANG_WARN_SUSPICIOUS_MOVE=YES
               export CLANG_WARN_UNREACHABLE_CODE=YES
               export CLANG_WARN__DUPLICATE_METHOD_MATCH=YES
               export CLASS_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/JavaClasses
               export CLEAN_PRECOMPS=YES
               export CLONE_HEADERS=NO
               export CODESIGNING_FOLDER_PATH=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app
               export CODE_SIGNING_ALLOWED=YES
               export CODE_SIGNING_REQUIRED=YES
               export CODE_SIGN_CONTEXT_CLASS=XCiPhoneSimulatorCodeSignContext
               export CODE_SIGN_IDENTITY=-
               export CODE_SIGN_INJECT_BASE_ENTITLEMENTS=YES
               export COLOR_DIAGNOSTICS=NO
               export COMBINE_HIDPI_IMAGES=NO
               export COMPILER_INDEX_STORE_ENABLE=NO
               export COMPOSITE_SDK_DIRS=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/CompositeSDKs
               export COMPRESS_PNG_FILES=YES
               export CONFIGURATION=Debug
               export CONFIGURATION_BUILD_DIR=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator
               export CONFIGURATION_TEMP_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator
               export CONTENTS_FOLDER_PATH=Runner.app
               export COPYING_PRESERVES_HFS_DATA=NO
               export COPY_HEADERS_RUN_UNIFDEF=NO
               export COPY_PHASE_STRIP=NO
               export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS=YES
               export CORRESPONDING_DEVICE_PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               export CORRESPONDING_DEVICE_PLATFORM_NAME=iphoneos
               export CORRESPONDING_DEVICE_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
               export CORRESPONDING_DEVICE_SDK_NAME=iphoneos13.2
               export CP=/bin/cp
               export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
               export CURRENT_ARCH=undefined_arch
               export CURRENT_PROJECT_VERSION=1
               export CURRENT_VARIANT=normal
               export DART_OBFUSCATION=false
               export DEAD_CODE_STRIPPING=YES
               export DEBUGGING_SYMBOLS=YES
               export DEBUG_INFORMATION_FORMAT=dwarf
               export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
               export DEFAULT_DEXT_INSTALL_PATH=/System/Library/DriverExtensions
               export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
               export DEFINES_MODULE=NO
               export DEPLOYMENT_LOCATION=NO
               export DEPLOYMENT_POSTPROCESSING=NO
               export DEPLOYMENT_TARGET_CLANG_ENV_NAME=IPHONEOS_DEPLOYMENT_TARGET
               export DEPLOYMENT_TARGET_CLANG_FLAG_NAME=mios-simulator-version-min
               export DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX=-mios-simulator-version-min=
               export DEPLOYMENT_TARGET_LD_ENV_NAME=IPHONEOS_DEPLOYMENT_TARGET
               export DEPLOYMENT_TARGET_LD_FLAG_NAME=ios_simulator_version_min
               export DEPLOYMENT_TARGET_SETTING_NAME=IPHONEOS_DEPLOYMENT_TARGET
               export DEPLOYMENT_TARGET_SUGGESTED_VALUES="8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4 13.0 13.1 13.2"
               export DERIVED_FILES_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               export DERIVED_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               export DERIVED_SOURCES_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
               export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
               export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
               export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
               export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
               export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
               export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
               export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
               export DEVELOPMENT_LANGUAGE=en
               export DOCUMENTATION_FOLDER_PATH=Runner.app/en.lproj/Documentation
               export DONT_GENERATE_INFOPLIST_FILE=NO
               export DO_HEADER_SCANNING_IN_JAM=NO
               export DSTROOT=/tmp/Runner.dst
               export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               export DWARF_DSYM_FILE_NAME=Runner.app.dSYM
               export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
               export DWARF_DSYM_FOLDER_PATH=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator
               export EFFECTIVE_PLATFORM_NAME=-iphonesimulator
               export EMBEDDED_CONTENT_CONTAINS_SWIFT=NO
               export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
               export ENABLE_BITCODE=NO
               export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES
               export ENABLE_HARDENED_RUNTIME=NO
               export ENABLE_HEADER_DEPENDENCIES=YES
               export ENABLE_ON_DEMAND_RESOURCES=YES
               export ENABLE_PREVIEWS=NO
               export ENABLE_STRICT_OBJC_MSGSEND=YES
               export ENABLE_TESTABILITY=YES
               export ENTITLEMENTS_DESTINATION=__entitlements
               export ENTITLEMENTS_REQUIRED=YES
               export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
               export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
               export EXECUTABLES_FOLDER_PATH=Runner.app/Executables
               export EXECUTABLE_FOLDER_PATH=Runner.app
               export EXECUTABLE_NAME=Runner
               export EXECUTABLE_PATH=Runner.app/Runner
               export EXPANDED_CODE_SIGN_IDENTITY=-
               export EXPANDED_CODE_SIGN_IDENTITY_NAME=-
               export FILE_LIST=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects/LinkFileList
               export FIXED_FILES_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/FixedFiles
               export FLUTTER_APPLICATION_PATH=/Users/edwardsc/Desktop/text_1
               export FLUTTER_BUILD_DIR=build
               export FLUTTER_BUILD_NAME=1.0.0
               export FLUTTER_BUILD_NUMBER=1
               export FLUTTER_FRAMEWORK_DIR=/Users/edwardsc/dev/flutter/bin/cache/artifacts/engine/ios
               export FLUTTER_ROOT=/Users/edwardsc/dev/flutter
               export FLUTTER_SUPPRESS_ANALYTICS=true
               export FLUTTER_TARGET=/Users/edwardsc/Desktop/text_1/lib/main.dart
               export FRAMEWORKS_FOLDER_PATH=Runner.app/Frameworks
               export FRAMEWORK_FLAG_PREFIX=-framework
               export FRAMEWORK_SEARCH_PATHS="/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator  /Users/edwardsc/Desktop/text_1/ios/Flutter"
               export FRAMEWORK_VERSION=A
               export FULL_PRODUCT_NAME=Runner.app
               export GCC3_VERSION=3.3
               export GCC_C_LANGUAGE_STANDARD=gnu99
               export GCC_DYNAMIC_NO_PIC=NO
               export GCC_INLINES_ARE_PRIVATE_EXTERN=YES
               export GCC_NO_COMMON_BLOCKS=YES
               export GCC_OBJC_LEGACY_DISPATCH=YES
               export GCC_OPTIMIZATION_LEVEL=0
               export GCC_PFE_FILE_C_DIALECTS="c objective-c c++ objective-c++"
               export GCC_PREPROCESSOR_DEFINITIONS="DEBUG=1 "
               export GCC_SYMBOLS_PRIVATE_EXTERN=NO
               export GCC_TREAT_WARNINGS_AS_ERRORS=NO
               export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
               export GCC_VERSION_IDENTIFIER=com_apple_compilers_llvm_clang_1_0
               export GCC_WARN_64_TO_32_BIT_CONVERSION=YES
               export GCC_WARN_ABOUT_RETURN_TYPE=YES_ERROR
               export GCC_WARN_UNDECLARED_SELECTOR=YES
               export GCC_WARN_UNINITIALIZED_AUTOS=YES_AGGRESSIVE
               export GCC_WARN_UNUSED_FUNCTION=YES
               export GCC_WARN_UNUSED_VARIABLE=YES
               export GENERATE_MASTER_OBJECT_FILE=NO
               export GENERATE_PKGINFO_FILE=YES
               export GENERATE_PROFILING_CODE=NO
               export GENERATE_TEXT_BASED_STUBS=NO
               export GID=20
               export GROUP=staff
               export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
               export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
               export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
               export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
               export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
               export HEADERMAP_USES_VFS=NO
               export HEADER_SEARCH_PATHS="/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/include "
               export HIDE_BITCODE_SYMBOLS=YES
               export HOME=/Users/edwardsc
               export ICONV=/usr/bin/iconv
               export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
               export INFOPLIST_FILE=Runner/Info.plist
               export INFOPLIST_OUTPUT_FORMAT=binary
               export INFOPLIST_PATH=Runner.app/Info.plist
               export INFOPLIST_PREPROCESS=NO
               export INFOSTRINGS_PATH=Runner.app/en.lproj/InfoPlist.strings
               export INLINE_PRIVATE_FRAMEWORKS=NO
               export INSTALLHDRS_COPY_PHASE=NO
               export INSTALLHDRS_SCRIPT_PHASE=NO
               export INSTALL_DIR=/tmp/Runner.dst/Applications
               export INSTALL_GROUP=staff
               export INSTALL_MODE_FLAG=u+w,go-w,a+rX
               export INSTALL_OWNER=edwardsc
               export INSTALL_PATH=/Applications
               export INSTALL_ROOT=/tmp/Runner.dst
               export IPHONEOS_DEPLOYMENT_TARGET=8.0
               export JAVAC_DEFAULT_FLAGS="-J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8"
               export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               export JAVA_ARCHIVE_CLASSES=YES
               export JAVA_ARCHIVE_TYPE=JAR
               export JAVA_COMPILER=/usr/bin/javac
               export JAVA_FOLDER_PATH=Runner.app/Java
               export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
               export JAVA_JAR_FLAGS=cv
               export JAVA_SOURCE_SUBDIR=.
               export JAVA_USE_DEPENDENCIES=YES
               export JAVA_ZIP_FLAGS=-urg
               export JIKES_DEFAULT_FLAGS="+E +OLDCSO"
               export KEEP_PRIVATE_EXTERNS=NO
               export LD_DEPENDENCY_INFO_FILE=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/undefined_arch/Runner_dependency_info.dat
               export LD_ENTITLEMENTS_SECTION=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent
               export LD_GENERATE_MAP_FILE=NO
               export LD_MAP_FILE_PATH=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-LinkMap-normal-undefined_arch.txt
               export LD_NO_PIE=NO
               export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
               export LD_RUNPATH_SEARCH_PATHS=" @executable_path/Frameworks"
               export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               export LEX=lex
               export LIBRARY_DEXT_INSTALL_PATH=/Library/DriverExtensions
               export LIBRARY_FLAG_NOSPACE=YES
               export LIBRARY_FLAG_PREFIX=-l
               export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
               export LIBRARY_SEARCH_PATHS="/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator  /Users/edwardsc/Desktop/text_1/ios/Flutter"
               export LINKER_DISPLAYS_MANGLED_NAMES=NO
               export LINK_FILE_LIST_normal_x86_64=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.LinkFileList
               export LINK_WITH_STANDARD_LIBRARIES=YES
               export LLVM_TARGET_TRIPLE_OS_VERSION=ios8.0
               export LLVM_TARGET_TRIPLE_SUFFIX=-simulator
               export LLVM_TARGET_TRIPLE_VENDOR=apple
               export LOCALIZED_RESOURCES_FOLDER_PATH=Runner.app/en.lproj
               export LOCALIZED_STRING_MACRO_NAMES="NSLocalizedString CFCopyLocalizedString"
               export LOCALIZED_STRING_SWIFTUI_SUPPORT=YES
               export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
               export LOCAL_APPS_DIR=/Applications
               export LOCAL_DEVELOPER_DIR=/Library/Developer
               export LOCAL_LIBRARY_DIR=/Library
               export LOCROOT=/Users/edwardsc/Desktop/text_1/ios
               export LOCSYMROOT=/Users/edwardsc/Desktop/text_1/ios
               export MACH_O_TYPE=mh_execute
               export MAC_OS_X_PRODUCT_BUILD_VERSION=18G103
               export MAC_OS_X_VERSION_ACTUAL=101406
               export MAC_OS_X_VERSION_MAJOR=101400
               export MAC_OS_X_VERSION_MINOR=1406
               export METAL_LIBRARY_FILE_BASE=default
               export METAL_LIBRARY_OUTPUT_DIR=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app
               export MODULES_FOLDER_PATH=Runner.app/Modules
               export MODULE_CACHE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               export MTL_ENABLE_DEBUG_INFO=YES
               export NATIVE_ARCH=i386
               export NATIVE_ARCH_32_BIT=i386
               export NATIVE_ARCH_64_BIT=x86_64
               export NATIVE_ARCH_ACTUAL=x86_64
               export NO_COMMON=YES
               export OBJC_ABI_VERSION=2
               export OBJECT_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects
               export OBJECT_FILE_DIR_normal=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
               export OBJROOT=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex
               export ONLY_ACTIVE_ARCH=YES
               export OS=MACOS
               export OSAC=/usr/bin/osacompile
               export OTHER_LDFLAGS=" -framework Flutter"
               export PACKAGE_TYPE=com.apple.package-type.wrapper.application
               export PASCAL_STRINGS=YES
               export PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Users/edwardsc/.rbenv/shims:/Users/edwardsc/.gem/ruby/2.6.0/bin:/Users/edwardsc/Library/Android/sdk/platform-tools:/Users/edwardsc/Library/Android/sdk/tools:/Users/edwardsc/.pub-cache/bin:/Users/edwardsc/dev/flutter/bin/cache/dart-sdk/bin:/Users/edwardsc/dev/flutter/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/mysql-client/bin:/Users/edwardsc/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/edwardsc/.ec2/bin
               export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
               export PBDEVELOPMENTPLIST_PATH=Runner.app/pbdevelopment.plist
               export PER_ARCH_OBJECT_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/undefined_arch
               export PER_VARIANT_OBJECT_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
               export PKGINFO_FILE_PATH=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PkgInfo
               export PKGINFO_PATH=Runner.app/PkgInfo
               export PLATFORM_DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
               export PLATFORM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
               export PLATFORM_DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library
               export PLATFORM_DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
               export PLATFORM_DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
               export PLATFORM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
               export PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               export PLATFORM_DISPLAY_NAME="iOS Simulator"
               export PLATFORM_NAME=iphonesimulator
               export PLATFORM_PREFERRED_ARCH=x86_64
               export PLATFORM_PRODUCT_BUILD_VERSION=17B102
               export PLIST_FILE_OUTPUT_FORMAT=binary
               export PLUGINS_FOLDER_PATH=Runner.app/PlugIns
               export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
               export PRECOMP_DESTINATION_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PrefixHeaders
               export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
               export PRIVATE_HEADERS_FOLDER_PATH=Runner.app/PrivateHeaders
               export PRODUCT_BUNDLE_IDENTIFIER=com.example.text1
               export PRODUCT_BUNDLE_PACKAGE_TYPE=APPL
               export PRODUCT_MODULE_NAME=Runner
               export PRODUCT_NAME=Runner
               export PRODUCT_SETTINGS_PATH=/Users/edwardsc/Desktop/text_1/ios/Runner/Info.plist
               export PRODUCT_TYPE=com.apple.product-type.application
               export PROFILING_CODE=NO
               export PROJECT=Runner
               export PROJECT_DERIVED_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/DerivedSources
               export PROJECT_DIR=/Users/edwardsc/Desktop/text_1/ios
               export PROJECT_FILE_PATH=/Users/edwardsc/Desktop/text_1/ios/Runner.xcodeproj
               export PROJECT_NAME=Runner
               export PROJECT_TEMP_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build
               export PROJECT_TEMP_ROOT=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex
               export PUBLIC_HEADERS_FOLDER_PATH=Runner.app/Headers
               export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS=YES
               export REMOVE_CVS_FROM_RESOURCES=YES
               export REMOVE_GIT_FROM_RESOURCES=YES
               export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
               export REMOVE_HG_FROM_RESOURCES=YES
               export REMOVE_SVN_FROM_RESOURCES=YES
               export REZ_COLLECTOR_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources
               export REZ_OBJECTS_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources/Objects
               export REZ_SEARCH_PATHS="/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator "
               export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
               export SCRIPTS_FOLDER_PATH=Runner.app/Scripts
               export SCRIPT_INPUT_FILE_COUNT=0
               export SCRIPT_INPUT_FILE_LIST_COUNT=0
               export SCRIPT_OUTPUT_FILE_COUNT=0
               export SCRIPT_OUTPUT_FILE_LIST_COUNT=0
               export SCRIPT_OUTPUT_STREAM_FILE=/var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/T/flutter_tools.ZLfbtl/flutter_build_log_pipe.sUprNk/pipe_to_stdout
               export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               export SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               export SDK_DIR_iphonesimulator13_2=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               export SDK_NAME=iphonesimulator13.2
               export SDK_NAMES=iphonesimulator13.2
               export SDK_PRODUCT_BUILD_VERSION=17B102
               export SDK_VERSION=13.2
               export SDK_VERSION_ACTUAL=130200
               export SDK_VERSION_MAJOR=130000
               export SDK_VERSION_MINOR=200
               export SED=/usr/bin/sed
               export SEPARATE_STRIP=NO
               export SEPARATE_SYMBOL_EDIT=NO
               export SET_DIR_MODE_OWNER_GROUP=YES
               export SET_FILE_MODE_OWNER_GROUP=NO
               export SHALLOW_BUNDLE=YES
               export SHARED_DERIVED_FILE_DIR=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/DerivedSources
               export SHARED_FRAMEWORKS_FOLDER_PATH=Runner.app/SharedFrameworks
               export SHARED_PRECOMPS_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/PrecompiledHeaders
               export SHARED_SUPPORT_FOLDER_PATH=Runner.app/SharedSupport
               export SKIP_INSTALL=NO
               export SOURCE_ROOT=/Users/edwardsc/Desktop/text_1/ios
               export SRCROOT=/Users/edwardsc/Desktop/text_1/ios
               export STRINGS_FILE_OUTPUT_ENCODING=binary
               export STRIP_BITCODE_FROM_COPIED_FILES=NO
               export STRIP_INSTALLED_PRODUCT=YES
               export STRIP_STYLE=all
               export STRIP_SWIFT_SYMBOLS=YES
               export SUPPORTED_DEVICE_FAMILIES=1,2
               export SUPPORTED_PLATFORMS="iphoneos iphonesimulator"
               export SUPPORTS_TEXT_BASED_API=NO
               export SWIFT_OBJC_BRIDGING_HEADER=Runner/Runner-Bridging-Header.h
               export SWIFT_OPTIMIZATION_LEVEL=-Onone
               export SWIFT_PLATFORM_TARGET_PREFIX=ios
               export SWIFT_RESPONSE_FILE_PATH_normal_x86_64=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.SwiftFileList
               export SWIFT_VERSION=5.0
               export SYMROOT=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Products
               export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
               export SYSTEM_APPS_DIR=/Applications
               export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
               export SYSTEM_DEMOS_DIR=/Applications/Extras
               export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
               export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
               export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
               export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
               export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
               export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
               export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
               export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
               export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
               export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
               export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
               export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
               export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
               export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
               export SYSTEM_DEXT_INSTALL_PATH=/System/Library/DriverExtensions
               export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
               export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
               export SYSTEM_LIBRARY_DIR=/System/Library
               export TAPI_VERIFY_MODE=ErrorsOnly
               export TARGETED_DEVICE_FAMILY=1,2
               export TARGETNAME=Runner
               export TARGET_BUILD_DIR=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator
               export TARGET_DEVICE_IDENTIFIER=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder
               export TARGET_NAME=Runner
               export TARGET_TEMP_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_FILES_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_ROOT=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex
               export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
               export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               export TRACK_WIDGET_CREATION=true
               export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
               export TREE_SHAKE_ICONS=false
               export TeamIdentifierPrefix=7333GKPQG5.
               export UID=501
               export UNLOCALIZED_RESOURCES_FOLDER_PATH=Runner.app
               export UNSTRIPPED_PRODUCT=NO
               export USER=edwardsc
               export USER_APPS_DIR=/Users/edwardsc/Applications
               export USER_LIBRARY_DIR=/Users/edwardsc/Library
               export USE_DYNAMIC_NO_PIC=YES
               export USE_HEADERMAP=YES
               export USE_HEADER_SYMLINKS=NO
               export USE_LLVM_TARGET_TRIPLES=YES
               export USE_LLVM_TARGET_TRIPLES_FOR_CLANG=YES
               export USE_LLVM_TARGET_TRIPLES_FOR_LD=YES
               export USE_LLVM_TARGET_TRIPLES_FOR_TAPI=YES
               export VALIDATE_DEVELOPMENT_ASSET_PATHS=YES_ERROR
               export VALIDATE_PRODUCT=NO
               export VALIDATE_WORKSPACE=NO
               export VALID_ARCHS="i386 x86_64"
               export VERBOSE_PBXCP=NO
               export VERBOSE_SCRIPT_LOGGING=YES
               export VERSIONING_SYSTEM=apple-generic
               export VERSIONPLIST_PATH=Runner.app/version.plist
               export VERSION_INFO_BUILDER=edwardsc
               export VERSION_INFO_FILE=Runner_vers.c
               export VERSION_INFO_STRING=""@(#)PROGRAM:Runner  PROJECT:Runner-1""
               export WRAPPER_EXTENSION=app
               export WRAPPER_NAME=Runner.app
               export WRAPPER_SUFFIX=.app
               export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
               export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
               export XCODE_PRODUCT_BUILD_VERSION=11B500
               export XCODE_VERSION_ACTUAL=1120
               export XCODE_VERSION_MAJOR=1100
               export XCODE_VERSION_MINOR=1120
               export XPCSERVICES_FOLDER_PATH=Runner.app/XPCServices
               export YACC=yacc
               export arch=undefined_arch
               export variant=normal
               /bin/sh -c /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh
           ♦ rm -rf -- /Users/edwardsc/Desktop/text_1/ios/Flutter/Flutter.framework
           ♦ cp -- /Users/edwardsc/dev/flutter/bin/cache/artifacts/engine/ios/Flutter.podspec /Users/edwardsc/Desktop/text_1/ios/Flutter
           ♦ cp -r -- /Users/edwardsc/dev/flutter/bin/cache/artifacts/engine/ios/Flutter.framework /Users/edwardsc/Desktop/text_1/ios/Flutter
           ♦ /Users/edwardsc/dev/flutter/bin/flutter --verbose assemble --output=/Users/edwardsc/Desktop/text_1/ios/Flutter/ -dTargetPlatform=ios -dTargetFile=/Users/edwardsc/Desktop/text_1/lib/main.dart -dBuildMode=debug -dIosArchs=x86_64 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions= debug_ios_bundle_flutter_assets
           [ +122 ms] executing: [/Users/edwardsc/dev/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
           [  +33 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
           [        ] d9653445f4d1257b5f5adb4b271d1316469e8cf1
           [        ] executing: [/Users/edwardsc/dev/flutter/] git tag --contains HEAD
           [ +178 ms] Exit code 0 from: git tag --contains HEAD
           [        ] 1.20.0-0.0.pre
           [   +8 ms] executing: [/Users/edwardsc/dev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
           [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
           [        ] origin/dev
           [        ] executing: [/Users/edwardsc/dev/flutter/] git ls-remote --get-url origin
           [   +5 ms] Exit code 0 from: git ls-remote --get-url origin
           [        ] https://github.com/flutter/flutter.git
           [  +47 ms] executing: [/Users/edwardsc/dev/flutter/] git rev-parse --abbrev-ref HEAD
           [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
           [        ] dev
           [  +35 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
           [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
           [   +4 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
           [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
           [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
           [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
           [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
           [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
           [  +80 ms] Initializing file store
           [   +8 ms] Done initializing file store
           [  +38 ms] Skipping target: gen_localizations
           [ +514 ms] Skipping target: kernel_snapshot
           [   +4 ms] Skipping target: debug_universal_framework
           [ +304 ms] Skipping target: debug_ios_bundle_flutter_assets
           [        ] Persisting file store
           [   +7 ms] Done persisting file store
           [   +5 ms] build succeeded.
           [   +8 ms] "flutter assemble" took 991ms.
           [   +3 ms] ensureAnalyticsSent: 0ms
           [   +1 ms] Running shutdown hooks
           [        ] Shutdown hooks complete
           [   +3 ms] exiting with code 0
           Project /Users/edwardsc/Desktop/text_1 built and packaged successfully.

           CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios
               export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
               export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name Runner -Onone -enable-batch-mode -enforce-exclusivity=checked @/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.SwiftFileList -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -target x86_64-apple-ios8.0-simulator -g -module-cache-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -swift-version 5 -I /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator -F /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator -F /Users/edwardsc/Desktop/text_1/ios/Flutter -parse-as-library -c -j12 -output-file-map /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.swiftmodule -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-generated-files.hmap -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-own-target-headers.hmap -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-all-target-headers.hmap -Xcc -iquote -Xcc /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-project-headers.hmap -Xcc -I/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/include -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources-normal/x86_64 -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64 -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -Xcc -DDEBUG=1 -emit-objc-header -emit-objc-header-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner-Swift.h -import-objc-header /Users/edwardsc/Desktop/text_1/ios/Runner/Runner-Bridging-Header.h -pch-output-dir /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/PrecompiledHeaders -working-directory /Users/edwardsc/Desktop/text_1/ios

           PrecompileSwiftBridgingHeader normal x86_64 (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios
               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -target x86_64-apple-ios8.0-simulator -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -I /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator -F /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator -F /Users/edwardsc/Desktop/text_1/ios/Flutter -enable-testing -g -module-cache-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -serialize-debugging-options -Xcc -working-directory -Xcc /Users/edwardsc/Desktop/text_1/ios -enable-anonymous-context-mangled-names -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-generated-files.hmap -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-own-target-headers.hmap -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-all-target-headers.hmap -Xcc -iquote -Xcc /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-project-headers.hmap -Xcc -I/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/include -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources-normal/x86_64 -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64 -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -Xcc -DDEBUG=1 -serialize-diagnostics-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-3LJJQZ0Q5KJPK.dia /Users/edwardsc/Desktop/text_1/ios/Runner/Runner-Bridging-Header.h -emit-pch -pch-output-dir /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/PrecompiledHeaders
           fatal error: file '/Users/edwardsc/Desktop/text_1/ios/Flutter/Flutter.framework/Headers/FlutterTexture.h' has been modified since the precompiled header '/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_1L5HZJQLLLLFU-clang_3IQ3BQ8EHGN7.pch' was built
           note: '/Users/edwardsc/Desktop/text_1/ios/Flutter/Flutter.framework/Headers/FlutterTexture.h' required by '/Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3IQ3BQ8EHGN7/Flutter-178GJW67KBIKB.pcm'
           note: '/Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3IQ3BQ8EHGN7/Flutter-178GJW67KBIKB.pcm' required by '/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_1L5HZJQLLLLFU-clang_3IQ3BQ8EHGN7.pch'
           note: please rebuild precompiled header '/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_1L5HZJQLLLLFU-clang_3IQ3BQ8EHGN7.pch'
           note: imported by '/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_1L5HZJQLLLLFU-clang_3IQ3BQ8EHGN7.pch'

           CompileSwift normal x86_64 /Users/edwardsc/Desktop/text_1/ios/Runner/AppDelegate.swift (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios
               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/edwardsc/Desktop/text_1/ios/Runner/AppDelegate.swift -emit-module-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate\~partial.swiftmodule -emit-module-doc-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate\~partial.swiftdoc -serialize-diagnostics-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.dia -emit-dependencies-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.d -emit-reference-dependencies-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.swiftdeps -target x86_64-apple-ios8.0-simulator -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -I /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator -F /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator -F /Users/edwardsc/Desktop/text_1/ios/Flutter -enable-testing -g -module-cache-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -serialize-debugging-options -Xcc -working-directory -Xcc /Users/edwardsc/Desktop/text_1/ios -enable-anonymous-context-mangled-names -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-generated-files.hmap -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-own-target-headers.hmap -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-all-target-headers.hmap -Xcc -iquote -Xcc /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-project-headers.hmap -Xcc -I/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/include -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources-normal/x86_64 -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64 -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -Xcc -DDEBUG=1 -import-objc-header /Users/edwardsc/Desktop/text_1/ios/Runner/Runner-Bridging-Header.h -pch-output-dir /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/PrecompiledHeaders -pch-disable-validation -parse-as-library -module-name Runner -o /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.o

           MergeSwiftModule normal x86_64 (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios
               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -merge-modules -emit-module /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate\~partial.swiftmodule -parse-as-library -sil-merge-partial-modules -disable-diagnostic-passes -disable-sil-perf-optzns -target x86_64-apple-ios8.0-simulator -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -I /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator -F /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator -F /Users/edwardsc/Desktop/text_1/ios/Flutter -enable-testing -g -module-cache-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -serialize-debugging-options -Xcc -working-directory -Xcc /Users/edwardsc/Desktop/text_1/ios -enable-anonymous-context-mangled-names -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-generated-files.hmap -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-own-target-headers.hmap -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-all-target-headers.hmap -Xcc -iquote -Xcc /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-project-headers.hmap -Xcc -I/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/include -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources-normal/x86_64 -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64 -Xcc -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -Xcc -DDEBUG=1 -emit-module-doc-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.swiftdoc -emit-objc-header-path /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner-Swift.h -import-objc-header /Users/edwardsc/Desktop/text_1/ios/Runner/Runner-Bridging-Header.h -module-name Runner -o /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.swiftmodule

           CompileC /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.o /Users/edwardsc/Desktop/text_1/ios/Runner/GeneratedPluginRegistrant.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios
               export LANG=en_US.US-ASCII
               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios8.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-generated-files.hmap -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-own-target-headers.hmap -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-all-target-headers.hmap -iquote /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-project-headers.hmap -I/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/include -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources-normal/x86_64 -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64 -I/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -F/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator -F/Users/edwardsc/Desktop/text_1/ios/Flutter -MMD -MT dependencies -MF /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.d --serialize-diagnostics /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.dia -c /Users/edwardsc/Desktop/text_1/ios/Runner/GeneratedPluginRegistrant.m -o /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.o

           Ld /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Runner normal x86_64 (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios
               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios8.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -L/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator -L/Users/edwardsc/Desktop/text_1/ios/Flutter -F/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator -F/Users/edwardsc/Desktop/text_1/ios/Flutter -filelist /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.swiftmodule -framework Flutter -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent -Xlinker -dependency_info -Xlinker /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat -o /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Runner

           PhaseScriptExecution Thin\ Binary /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios
               export ACTION=build
               export AD_HOC_CODE_SIGNING_ALLOWED=YES
               export ALTERNATE_GROUP=staff
               export ALTERNATE_MODE=u+w,go-w,a+rX
               export ALTERNATE_OWNER=edwardsc
               export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
               export ALWAYS_SEARCH_USER_PATHS=NO
               export ALWAYS_USE_SEPARATE_HEADERMAPS=NO
               export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
               export APPLE_INTERNAL_DIR=/AppleInternal
               export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
               export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
               export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
               export APPLICATION_EXTENSION_API_ONLY=NO
               export APPLY_RULES_IN_COPY_FILES=NO
               export APPLY_RULES_IN_COPY_HEADERS=NO
               export ARCHS=x86_64
               export ARCHS_STANDARD="i386 x86_64"
               export ARCHS_STANDARD_32_64_BIT="i386 x86_64"
               export ARCHS_STANDARD_32_BIT=i386
               export ARCHS_STANDARD_64_BIT=x86_64
               export ARCHS_STANDARD_INCLUDING_64_BIT="i386 x86_64"
               export ARCHS_UNIVERSAL_IPHONE_OS="i386 x86_64"
               export ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon
               export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
               export AppIdentifierPrefix=7333GKPQG5.
               export BITCODE_GENERATION_MODE=marker
               export BUILD_ACTIVE_RESOURCES_ONLY=YES
               export BUILD_COMPONENTS="headers build"
               export BUILD_DIR=/Users/edwardsc/Desktop/text_1/build/ios
               export BUILD_LIBRARY_FOR_DISTRIBUTION=NO
               export BUILD_ROOT=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Products
               export BUILD_STYLE=
               export BUILD_VARIANTS=normal
               export BUILT_PRODUCTS_DIR=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator
               export CACHE_ROOT=/var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/C/com.apple.DeveloperTools/11.2.1-11B500/Xcode
               export CCHROOT=/var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/C/com.apple.DeveloperTools/11.2.1-11B500/Xcode
               export CHMOD=/bin/chmod
               export CHOWN=/usr/sbin/chown
               export CLANG_ANALYZER_NONNULL=YES
               export CLANG_CXX_LANGUAGE_STANDARD=gnu++0x
               export CLANG_CXX_LIBRARY=libc++
               export CLANG_ENABLE_MODULES=YES
               export CLANG_ENABLE_OBJC_ARC=YES
               export CLANG_MODULES_BUILD_SESSION_FILE=/Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation
               export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING=YES
               export CLANG_WARN_BOOL_CONVERSION=YES
               export CLANG_WARN_COMMA=YES
               export CLANG_WARN_CONSTANT_CONVERSION=YES
               export CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS=YES
               export CLANG_WARN_DIRECT_OBJC_ISA_USAGE=YES_ERROR
               export CLANG_WARN_EMPTY_BODY=YES
               export CLANG_WARN_ENUM_CONVERSION=YES
               export CLANG_WARN_INFINITE_RECURSION=YES
               export CLANG_WARN_INT_CONVERSION=YES
               export CLANG_WARN_NON_LITERAL_NULL_CONVERSION=YES
               export CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF=YES
               export CLANG_WARN_OBJC_LITERAL_CONVERSION=YES
               export CLANG_WARN_OBJC_ROOT_CLASS=YES_ERROR
               export CLANG_WARN_RANGE_LOOP_ANALYSIS=YES
               export CLANG_WARN_STRICT_PROTOTYPES=YES
               export CLANG_WARN_SUSPICIOUS_MOVE=YES
               export CLANG_WARN_UNREACHABLE_CODE=YES
               export CLANG_WARN__DUPLICATE_METHOD_MATCH=YES
               export CLASS_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/JavaClasses
               export CLEAN_PRECOMPS=YES
               export CLONE_HEADERS=NO
               export CODESIGNING_FOLDER_PATH=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app
               export CODE_SIGNING_ALLOWED=YES
               export CODE_SIGNING_REQUIRED=YES
               export CODE_SIGN_CONTEXT_CLASS=XCiPhoneSimulatorCodeSignContext
               export CODE_SIGN_IDENTITY=-
               export CODE_SIGN_INJECT_BASE_ENTITLEMENTS=YES
               export COLOR_DIAGNOSTICS=NO
               export COMBINE_HIDPI_IMAGES=NO
               export COMPILER_INDEX_STORE_ENABLE=NO
               export COMPOSITE_SDK_DIRS=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/CompositeSDKs
               export COMPRESS_PNG_FILES=YES
               export CONFIGURATION=Debug
               export CONFIGURATION_BUILD_DIR=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator
               export CONFIGURATION_TEMP_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator
               export CONTENTS_FOLDER_PATH=Runner.app
               export COPYING_PRESERVES_HFS_DATA=NO
               export COPY_HEADERS_RUN_UNIFDEF=NO
               export COPY_PHASE_STRIP=NO
               export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS=YES
               export CORRESPONDING_DEVICE_PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               export CORRESPONDING_DEVICE_PLATFORM_NAME=iphoneos
               export CORRESPONDING_DEVICE_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
               export CORRESPONDING_DEVICE_SDK_NAME=iphoneos13.2
               export CP=/bin/cp
               export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
               export CURRENT_ARCH=undefined_arch
               export CURRENT_PROJECT_VERSION=1
               export CURRENT_VARIANT=normal
               export DART_OBFUSCATION=false
               export DEAD_CODE_STRIPPING=YES
               export DEBUGGING_SYMBOLS=YES
               export DEBUG_INFORMATION_FORMAT=dwarf
               export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
               export DEFAULT_DEXT_INSTALL_PATH=/System/Library/DriverExtensions
               export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
               export DEFINES_MODULE=NO
               export DEPLOYMENT_LOCATION=NO
               export DEPLOYMENT_POSTPROCESSING=NO
               export DEPLOYMENT_TARGET_CLANG_ENV_NAME=IPHONEOS_DEPLOYMENT_TARGET
               export DEPLOYMENT_TARGET_CLANG_FLAG_NAME=mios-simulator-version-min
               export DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX=-mios-simulator-version-min=
               export DEPLOYMENT_TARGET_LD_ENV_NAME=IPHONEOS_DEPLOYMENT_TARGET
               export DEPLOYMENT_TARGET_LD_FLAG_NAME=ios_simulator_version_min
               export DEPLOYMENT_TARGET_SETTING_NAME=IPHONEOS_DEPLOYMENT_TARGET
               export DEPLOYMENT_TARGET_SUGGESTED_VALUES="8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4 13.0 13.1 13.2"
               export DERIVED_FILES_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               export DERIVED_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               export DERIVED_SOURCES_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
               export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
               export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
               export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
               export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
               export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
               export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
               export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
               export DEVELOPMENT_LANGUAGE=en
               export DOCUMENTATION_FOLDER_PATH=Runner.app/en.lproj/Documentation
               export DONT_GENERATE_INFOPLIST_FILE=NO
               export DO_HEADER_SCANNING_IN_JAM=NO
               export DSTROOT=/tmp/Runner.dst
               export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               export DWARF_DSYM_FILE_NAME=Runner.app.dSYM
               export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
               export DWARF_DSYM_FOLDER_PATH=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator
               export EFFECTIVE_PLATFORM_NAME=-iphonesimulator
               export EMBEDDED_CONTENT_CONTAINS_SWIFT=NO
               export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
               export ENABLE_BITCODE=NO
               export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES
               export ENABLE_HARDENED_RUNTIME=NO
               export ENABLE_HEADER_DEPENDENCIES=YES
               export ENABLE_ON_DEMAND_RESOURCES=YES
               export ENABLE_PREVIEWS=NO
               export ENABLE_STRICT_OBJC_MSGSEND=YES
               export ENABLE_TESTABILITY=YES
               export ENTITLEMENTS_DESTINATION=__entitlements
               export ENTITLEMENTS_REQUIRED=YES
               export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
               export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
               export EXECUTABLES_FOLDER_PATH=Runner.app/Executables
               export EXECUTABLE_FOLDER_PATH=Runner.app
               export EXECUTABLE_NAME=Runner
               export EXECUTABLE_PATH=Runner.app/Runner
               export EXPANDED_CODE_SIGN_IDENTITY=-
               export EXPANDED_CODE_SIGN_IDENTITY_NAME=-
               export FILE_LIST=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects/LinkFileList
               export FIXED_FILES_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/FixedFiles
               export FLUTTER_APPLICATION_PATH=/Users/edwardsc/Desktop/text_1
               export FLUTTER_BUILD_DIR=build
               export FLUTTER_BUILD_NAME=1.0.0
               export FLUTTER_BUILD_NUMBER=1
               export FLUTTER_FRAMEWORK_DIR=/Users/edwardsc/dev/flutter/bin/cache/artifacts/engine/ios
               export FLUTTER_ROOT=/Users/edwardsc/dev/flutter
               export FLUTTER_SUPPRESS_ANALYTICS=true
               export FLUTTER_TARGET=/Users/edwardsc/Desktop/text_1/lib/main.dart
               export FRAMEWORKS_FOLDER_PATH=Runner.app/Frameworks
               export FRAMEWORK_FLAG_PREFIX=-framework
               export FRAMEWORK_SEARCH_PATHS="/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator  /Users/edwardsc/Desktop/text_1/ios/Flutter"
               export FRAMEWORK_VERSION=A
               export FULL_PRODUCT_NAME=Runner.app
               export GCC3_VERSION=3.3
               export GCC_C_LANGUAGE_STANDARD=gnu99
               export GCC_DYNAMIC_NO_PIC=NO
               export GCC_INLINES_ARE_PRIVATE_EXTERN=YES
               export GCC_NO_COMMON_BLOCKS=YES
               export GCC_OBJC_LEGACY_DISPATCH=YES
               export GCC_OPTIMIZATION_LEVEL=0
               export GCC_PFE_FILE_C_DIALECTS="c objective-c c++ objective-c++"
               export GCC_PREPROCESSOR_DEFINITIONS="DEBUG=1 "
               export GCC_SYMBOLS_PRIVATE_EXTERN=NO
               export GCC_TREAT_WARNINGS_AS_ERRORS=NO
               export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
               export GCC_VERSION_IDENTIFIER=com_apple_compilers_llvm_clang_1_0
               export GCC_WARN_64_TO_32_BIT_CONVERSION=YES
               export GCC_WARN_ABOUT_RETURN_TYPE=YES_ERROR
               export GCC_WARN_UNDECLARED_SELECTOR=YES
               export GCC_WARN_UNINITIALIZED_AUTOS=YES_AGGRESSIVE
               export GCC_WARN_UNUSED_FUNCTION=YES
               export GCC_WARN_UNUSED_VARIABLE=YES
               export GENERATE_MASTER_OBJECT_FILE=NO
               export GENERATE_PKGINFO_FILE=YES
               export GENERATE_PROFILING_CODE=NO
               export GENERATE_TEXT_BASED_STUBS=NO
               export GID=20
               export GROUP=staff
               export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
               export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
               export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
               export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
               export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
               export HEADERMAP_USES_VFS=NO
               export HEADER_SEARCH_PATHS="/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/include "
               export HIDE_BITCODE_SYMBOLS=YES
               export HOME=/Users/edwardsc
               export ICONV=/usr/bin/iconv
               export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
               export INFOPLIST_FILE=Runner/Info.plist
               export INFOPLIST_OUTPUT_FORMAT=binary
               export INFOPLIST_PATH=Runner.app/Info.plist
               export INFOPLIST_PREPROCESS=NO
               export INFOSTRINGS_PATH=Runner.app/en.lproj/InfoPlist.strings
               export INLINE_PRIVATE_FRAMEWORKS=NO
               export INSTALLHDRS_COPY_PHASE=NO
               export INSTALLHDRS_SCRIPT_PHASE=NO
               export INSTALL_DIR=/tmp/Runner.dst/Applications
               export INSTALL_GROUP=staff
               export INSTALL_MODE_FLAG=u+w,go-w,a+rX
               export INSTALL_OWNER=edwardsc
               export INSTALL_PATH=/Applications
               export INSTALL_ROOT=/tmp/Runner.dst
               export IPHONEOS_DEPLOYMENT_TARGET=8.0
               export JAVAC_DEFAULT_FLAGS="-J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8"
               export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               export JAVA_ARCHIVE_CLASSES=YES
               export JAVA_ARCHIVE_TYPE=JAR
               export JAVA_COMPILER=/usr/bin/javac
               export JAVA_FOLDER_PATH=Runner.app/Java
               export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
               export JAVA_JAR_FLAGS=cv
               export JAVA_SOURCE_SUBDIR=.
               export JAVA_USE_DEPENDENCIES=YES
               export JAVA_ZIP_FLAGS=-urg
               export JIKES_DEFAULT_FLAGS="+E +OLDCSO"
               export KEEP_PRIVATE_EXTERNS=NO
               export LD_DEPENDENCY_INFO_FILE=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/undefined_arch/Runner_dependency_info.dat
               export LD_ENTITLEMENTS_SECTION=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent
               export LD_GENERATE_MAP_FILE=NO
               export LD_MAP_FILE_PATH=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-LinkMap-normal-undefined_arch.txt
               export LD_NO_PIE=NO
               export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
               export LD_RUNPATH_SEARCH_PATHS=" @executable_path/Frameworks"
               export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               export LEX=lex
               export LIBRARY_DEXT_INSTALL_PATH=/Library/DriverExtensions
               export LIBRARY_FLAG_NOSPACE=YES
               export LIBRARY_FLAG_PREFIX=-l
               export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
               export LIBRARY_SEARCH_PATHS="/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator  /Users/edwardsc/Desktop/text_1/ios/Flutter"
               export LINKER_DISPLAYS_MANGLED_NAMES=NO
               export LINK_FILE_LIST_normal_x86_64=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.LinkFileList
               export LINK_WITH_STANDARD_LIBRARIES=YES
               export LLVM_TARGET_TRIPLE_OS_VERSION=ios8.0
               export LLVM_TARGET_TRIPLE_SUFFIX=-simulator
               export LLVM_TARGET_TRIPLE_VENDOR=apple
               export LOCALIZED_RESOURCES_FOLDER_PATH=Runner.app/en.lproj
               export LOCALIZED_STRING_MACRO_NAMES="NSLocalizedString CFCopyLocalizedString"
               export LOCALIZED_STRING_SWIFTUI_SUPPORT=YES
               export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
               export LOCAL_APPS_DIR=/Applications
               export LOCAL_DEVELOPER_DIR=/Library/Developer
               export LOCAL_LIBRARY_DIR=/Library
               export LOCROOT=/Users/edwardsc/Desktop/text_1/ios
               export LOCSYMROOT=/Users/edwardsc/Desktop/text_1/ios
               export MACH_O_TYPE=mh_execute
               export MAC_OS_X_PRODUCT_BUILD_VERSION=18G103
               export MAC_OS_X_VERSION_ACTUAL=101406
               export MAC_OS_X_VERSION_MAJOR=101400
               export MAC_OS_X_VERSION_MINOR=1406
               export METAL_LIBRARY_FILE_BASE=default
               export METAL_LIBRARY_OUTPUT_DIR=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app
               export MODULES_FOLDER_PATH=Runner.app/Modules
               export MODULE_CACHE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               export MTL_ENABLE_DEBUG_INFO=YES
               export NATIVE_ARCH=i386
               export NATIVE_ARCH_32_BIT=i386
               export NATIVE_ARCH_64_BIT=x86_64
               export NATIVE_ARCH_ACTUAL=x86_64
               export NO_COMMON=YES
               export OBJC_ABI_VERSION=2
               export OBJECT_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects
               export OBJECT_FILE_DIR_normal=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
               export OBJROOT=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex
               export ONLY_ACTIVE_ARCH=YES
               export OS=MACOS
               export OSAC=/usr/bin/osacompile
               export OTHER_LDFLAGS=" -framework Flutter"
               export PACKAGE_TYPE=com.apple.package-type.wrapper.application
               export PASCAL_STRINGS=YES
               export PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Users/edwardsc/.rbenv/shims:/Users/edwardsc/.gem/ruby/2.6.0/bin:/Users/edwardsc/Library/Android/sdk/platform-tools:/Users/edwardsc/Library/Android/sdk/tools:/Users/edwardsc/.pub-cache/bin:/Users/edwardsc/dev/flutter/bin/cache/dart-sdk/bin:/Users/edwardsc/dev/flutter/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/mysql-client/bin:/Users/edwardsc/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/edwardsc/.ec2/bin
               export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
               export PBDEVELOPMENTPLIST_PATH=Runner.app/pbdevelopment.plist
               export PER_ARCH_OBJECT_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/undefined_arch
               export PER_VARIANT_OBJECT_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
               export PKGINFO_FILE_PATH=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PkgInfo
               export PKGINFO_PATH=Runner.app/PkgInfo
               export PLATFORM_DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
               export PLATFORM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
               export PLATFORM_DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library
               export PLATFORM_DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
               export PLATFORM_DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
               export PLATFORM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
               export PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               export PLATFORM_DISPLAY_NAME="iOS Simulator"
               export PLATFORM_NAME=iphonesimulator
               export PLATFORM_PREFERRED_ARCH=x86_64
               export PLATFORM_PRODUCT_BUILD_VERSION=17B102
               export PLIST_FILE_OUTPUT_FORMAT=binary
               export PLUGINS_FOLDER_PATH=Runner.app/PlugIns
               export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
               export PRECOMP_DESTINATION_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PrefixHeaders
               export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
               export PRIVATE_HEADERS_FOLDER_PATH=Runner.app/PrivateHeaders
               export PRODUCT_BUNDLE_IDENTIFIER=com.example.text1
               export PRODUCT_BUNDLE_PACKAGE_TYPE=APPL
               export PRODUCT_MODULE_NAME=Runner
               export PRODUCT_NAME=Runner
               export PRODUCT_SETTINGS_PATH=/Users/edwardsc/Desktop/text_1/ios/Runner/Info.plist
               export PRODUCT_TYPE=com.apple.product-type.application
               export PROFILING_CODE=NO
               export PROJECT=Runner
               export PROJECT_DERIVED_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/DerivedSources
               export PROJECT_DIR=/Users/edwardsc/Desktop/text_1/ios
               export PROJECT_FILE_PATH=/Users/edwardsc/Desktop/text_1/ios/Runner.xcodeproj
               export PROJECT_NAME=Runner
               export PROJECT_TEMP_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build
               export PROJECT_TEMP_ROOT=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex
               export PUBLIC_HEADERS_FOLDER_PATH=Runner.app/Headers
               export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS=YES
               export REMOVE_CVS_FROM_RESOURCES=YES
               export REMOVE_GIT_FROM_RESOURCES=YES
               export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
               export REMOVE_HG_FROM_RESOURCES=YES
               export REMOVE_SVN_FROM_RESOURCES=YES
               export REZ_COLLECTOR_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources
               export REZ_OBJECTS_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources/Objects
               export REZ_SEARCH_PATHS="/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator "
               export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
               export SCRIPTS_FOLDER_PATH=Runner.app/Scripts
               export SCRIPT_INPUT_FILE_COUNT=0
               export SCRIPT_INPUT_FILE_LIST_COUNT=0
               export SCRIPT_OUTPUT_FILE_COUNT=0
               export SCRIPT_OUTPUT_FILE_LIST_COUNT=0
               export SCRIPT_OUTPUT_STREAM_FILE=/var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/T/flutter_tools.ZLfbtl/flutter_build_log_pipe.sUprNk/pipe_to_stdout
               export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               export SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               export SDK_DIR_iphonesimulator13_2=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               export SDK_NAME=iphonesimulator13.2
               export SDK_NAMES=iphonesimulator13.2
               export SDK_PRODUCT_BUILD_VERSION=17B102
               export SDK_VERSION=13.2
               export SDK_VERSION_ACTUAL=130200
               export SDK_VERSION_MAJOR=130000
               export SDK_VERSION_MINOR=200
               export SED=/usr/bin/sed
               export SEPARATE_STRIP=NO
               export SEPARATE_SYMBOL_EDIT=NO
               export SET_DIR_MODE_OWNER_GROUP=YES
               export SET_FILE_MODE_OWNER_GROUP=NO
               export SHALLOW_BUNDLE=YES
               export SHARED_DERIVED_FILE_DIR=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/DerivedSources
               export SHARED_FRAMEWORKS_FOLDER_PATH=Runner.app/SharedFrameworks
               export SHARED_PRECOMPS_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/PrecompiledHeaders
               export SHARED_SUPPORT_FOLDER_PATH=Runner.app/SharedSupport
               export SKIP_INSTALL=NO
               export SOURCE_ROOT=/Users/edwardsc/Desktop/text_1/ios
               export SRCROOT=/Users/edwardsc/Desktop/text_1/ios
               export STRINGS_FILE_OUTPUT_ENCODING=binary
               export STRIP_BITCODE_FROM_COPIED_FILES=NO
               export STRIP_INSTALLED_PRODUCT=YES
               export STRIP_STYLE=all
               export STRIP_SWIFT_SYMBOLS=YES
               export SUPPORTED_DEVICE_FAMILIES=1,2
               export SUPPORTED_PLATFORMS="iphoneos iphonesimulator"
               export SUPPORTS_TEXT_BASED_API=NO
               export SWIFT_OBJC_BRIDGING_HEADER=Runner/Runner-Bridging-Header.h
               export SWIFT_OPTIMIZATION_LEVEL=-Onone
               export SWIFT_PLATFORM_TARGET_PREFIX=ios
               export SWIFT_RESPONSE_FILE_PATH_normal_x86_64=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.SwiftFileList
               export SWIFT_VERSION=5.0
               export SYMROOT=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Products
               export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
               export SYSTEM_APPS_DIR=/Applications
               export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
               export SYSTEM_DEMOS_DIR=/Applications/Extras
               export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
               export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
               export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
               export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
               export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
               export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
               export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
               export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
               export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
               export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
               export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
               export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
               export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
               export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
               export SYSTEM_DEXT_INSTALL_PATH=/System/Library/DriverExtensions
               export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
               export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
               export SYSTEM_LIBRARY_DIR=/System/Library
               export TAPI_VERIFY_MODE=ErrorsOnly
               export TARGETED_DEVICE_FAMILY=1,2
               export TARGETNAME=Runner
               export TARGET_BUILD_DIR=/Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator
               export TARGET_DEVICE_IDENTIFIER=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder
               export TARGET_NAME=Runner
               export TARGET_TEMP_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_FILES_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_FILE_DIR=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_ROOT=/Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex
               export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
               export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               export TRACK_WIDGET_CREATION=true
               export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
               export TREE_SHAKE_ICONS=false
               export TeamIdentifierPrefix=7333GKPQG5.
               export UID=501
               export UNLOCALIZED_RESOURCES_FOLDER_PATH=Runner.app
               export UNSTRIPPED_PRODUCT=NO
               export USER=edwardsc
               export USER_APPS_DIR=/Users/edwardsc/Applications
               export USER_LIBRARY_DIR=/Users/edwardsc/Library
               export USE_DYNAMIC_NO_PIC=YES
               export USE_HEADERMAP=YES
               export USE_HEADER_SYMLINKS=NO
               export USE_LLVM_TARGET_TRIPLES=YES
               export USE_LLVM_TARGET_TRIPLES_FOR_CLANG=YES
               export USE_LLVM_TARGET_TRIPLES_FOR_LD=YES
               export USE_LLVM_TARGET_TRIPLES_FOR_TAPI=YES
               export VALIDATE_DEVELOPMENT_ASSET_PATHS=YES_ERROR
               export VALIDATE_PRODUCT=NO
               export VALIDATE_WORKSPACE=NO
               export VALID_ARCHS="i386 x86_64"
               export VERBOSE_PBXCP=NO
               export VERBOSE_SCRIPT_LOGGING=YES
               export VERSIONING_SYSTEM=apple-generic
               export VERSIONPLIST_PATH=Runner.app/version.plist
               export VERSION_INFO_BUILDER=edwardsc
               export VERSION_INFO_FILE=Runner_vers.c
               export VERSION_INFO_STRING=""@(#)PROGRAM:Runner  PROJECT:Runner-1""
               export WRAPPER_EXTENSION=app
               export WRAPPER_NAME=Runner.app
               export WRAPPER_SUFFIX=.app
               export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
               export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
               export XCODE_PRODUCT_BUILD_VERSION=11B500
               export XCODE_VERSION_ACTUAL=1120
               export XCODE_VERSION_MAJOR=1100
               export XCODE_VERSION_MINOR=1120
               export XPCSERVICES_FOLDER_PATH=Runner.app/XPCServices
               export YACC=yacc
               export arch=undefined_arch
               export variant=normal
               /bin/sh -c /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh
           ♦ mkdir -p -- /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
           ♦ rsync -av --delete /Users/edwardsc/Desktop/text_1/ios/Flutter/App.framework /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
           building file list ... done
           deleting App.framework/_CodeSignature/CodeResources
           deleting App.framework/_CodeSignature/
           App.framework/
           App.framework/App

           sent 49735 bytes  received 48 bytes  99566.00 bytes/sec
           total size is 33353329  speedup is 669.97
           ♦ rsync -av --delete --filter - .DS_Store/ --filter - Headers/ --filter - Modules/ /Users/edwardsc/Desktop/text_1/ios/Flutter/Flutter.framework /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/
           building file list ... done
           Flutter.framework/
           Flutter.framework/Flutter
           Flutter.framework/Info.plist
           Flutter.framework/icudtl.dat
           Flutter.framework/_CodeSignature/
           Flutter.framework/_CodeSignature/CodeResources

           sent 98411791 bytes  received 120 bytes  65607940.67 bytes/sec
           total size is 98399379  speedup is 1.00
           ♦ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip /Users/edwardsc/Desktop/text_1/ios/Flutter/Flutter.framework/Flutter -r -o /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework/Flutter
           ♦ codesign --force --verbose --sign - -- /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/App.framework/App
           /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/App.framework/App: signed bundle with Mach-O universal (x86_64 arm64) [io.flutter.flutter.app]
           ♦ codesign --force --verbose --sign - -- /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework/Flutter
           /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework/Flutter: replacing existing signature
           /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework/Flutter: signed bundle with Mach-O universal (armv7 x86_64 arm64) [io.flutter.flutter]

           ProcessInfoPlistFile /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Info.plist /Users/edwardsc/Desktop/text_1/ios/Runner/Info.plist (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios
               builtin-infoPlistUtility /Users/edwardsc/Desktop/text_1/ios/Runner/Info.plist -producttype com.apple.product-type.application -genpkginfo /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/PkgInfo -expandbuildsettings -format binary -platform iphonesimulator -additionalcontentfile /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Base.lproj/LaunchScreen-SBPartialInfo.plist -additionalcontentfile /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Base.lproj/Main-SBPartialInfo.plist -additionalcontentfile /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/assetcatalog_generated_info.plist -o /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Info.plist

           CopySwiftLibs /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios
               export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
               export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
               export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               builtin-swiftStdLibTool --copy --verbose --sign - --scan-executable /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Runner --scan-folder /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks --scan-folder /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/PlugIns --platform iphonesimulator --toolchain /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain --destination /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks --strip-bitcode --strip-bitcode-tool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip --emit-dependency-info /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/SwiftStdLibToolInputDependencies.dep
           libswiftDispatch.dylib is up to date at /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
           libswiftDarwin.dylib is up to date at /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
           libswiftCoreGraphics.dylib is up to date at /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
           libswiftObjectiveC.dylib is up to date at /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
           libswiftCore.dylib is up to date at /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
           libswiftCoreFoundation.dylib is up to date at /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
           libswiftFoundation.dylib is up to date at /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
           Codesigning /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
           /usr/bin/codesign --force --sign - --verbose /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
           Code signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib is unchanged; keeping original
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
           Codesigning /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
           Codesigning /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
           Codesigning /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
           /usr/bin/codesign --force --sign - --verbose /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
           /usr/bin/codesign --force --sign - --verbose /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
           /usr/bin/codesign --force --sign - --verbose /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
           Codesigning /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
           Codesigning /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
           /usr/bin/codesign --force --sign - --verbose /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
           /usr/bin/codesign --force --sign - --verbose /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
           Codesigning /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
           /usr/bin/codesign --force --sign - --verbose /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
           Code signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib is unchanged; keeping original
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
           Code signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib is unchanged; keeping original
           Code signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib is unchanged; keeping original
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
           Probing signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
           /usr/bin/codesign -r- --display /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
           Code signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib is unchanged; keeping original
           Code signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib is unchanged; keeping original
           Code signature of /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib is unchanged; keeping original

           CodeSign /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app (in target 'Runner' from project 'Runner')
               cd /Users/edwardsc/Desktop/text_1/ios
               export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate

           Signing Identity:     "-"

               /usr/bin/codesign --force --sign - --entitlements /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app.xcent --timestamp=none /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app

           ** BUILD SUCCEEDED **
[  +14 ms]  └─Compiling, linking and signing... (completed in 4.6s)
[        ] Xcode build done.                                            7.6s
[   +2 ms] executing: [/Users/edwardsc/Desktop/text_1/ios/] /usr/bin/env xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/edwardsc/Desktop/text_1/build/ios -sdk iphonesimulator -arch x86_64 SCRIPT_OUTPUT_STREAM_FILE=/var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/T/flutter_tools.ZLfbtl/flutter_build_log_pipe.sUprNk/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
[        ] executing: [/Users/edwardsc/Desktop/text_1/ios/] /usr/bin/env xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/edwardsc/Desktop/text_1/build/ios -sdk iphonesimulator -arch x86_64 SCRIPT_OUTPUT_STREAM_FILE=/var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/T/flutter_tools.ZLfbtl/flutter_build_log_pipe.sUprNk/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
[+1182 ms] Build settings from command line:
               ARCHS = x86_64
               BUILD_DIR = /Users/edwardsc/Desktop/text_1/build/ios
               COMPILER_INDEX_STORE_ENABLE = NO
               FLUTTER_SUPPRESS_ANALYTICS = true
               SCRIPT_OUTPUT_STREAM_FILE = /var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/T/flutter_tools.ZLfbtl/flutter_build_log_pipe.sUprNk/pipe_to_stdout
               SDKROOT = iphonesimulator13.2
               VERBOSE_SCRIPT_LOGGING = YES

           Build settings for action build and target Runner:
               ACTION = build
               AD_HOC_CODE_SIGNING_ALLOWED = YES
               ALTERNATE_GROUP = staff
               ALTERNATE_MODE = u+w,go-w,a+rX
               ALTERNATE_OWNER = edwardsc
               ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO
               ALWAYS_SEARCH_USER_PATHS = NO
               ALWAYS_USE_SEPARATE_HEADERMAPS = NO
               APPLE_INTERNAL_DEVELOPER_DIR = /AppleInternal/Developer
               APPLE_INTERNAL_DIR = /AppleInternal
               APPLE_INTERNAL_DOCUMENTATION_DIR = /AppleInternal/Documentation
               APPLE_INTERNAL_LIBRARY_DIR = /AppleInternal/Library
               APPLE_INTERNAL_TOOLS = /AppleInternal/Developer/Tools
               APPLICATION_EXTENSION_API_ONLY = NO
               APPLY_RULES_IN_COPY_FILES = NO
               APPLY_RULES_IN_COPY_HEADERS = NO
               ARCHS = x86_64
               ARCHS_STANDARD = i386 x86_64
               ARCHS_STANDARD_32_64_BIT = i386 x86_64
               ARCHS_STANDARD_32_BIT = i386
               ARCHS_STANDARD_64_BIT = x86_64
               ARCHS_STANDARD_INCLUDING_64_BIT = i386 x86_64
               ARCHS_UNIVERSAL_IPHONE_OS = i386 x86_64
               ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
               AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator
               BITCODE_GENERATION_MODE = marker
               BUILD_ACTIVE_RESOURCES_ONLY = NO
               BUILD_COMPONENTS = headers build
               BUILD_DIR = /Users/edwardsc/Desktop/text_1/build/ios
               BUILD_LIBRARY_FOR_DISTRIBUTION = NO
               BUILD_ROOT = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Products
               BUILD_STYLE = 
               BUILD_VARIANTS = normal
               BUILT_PRODUCTS_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator
               CACHE_ROOT = /var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/C/com.apple.DeveloperTools/11.2.1-11B500/Xcode
               CCHROOT = /var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/C/com.apple.DeveloperTools/11.2.1-11B500/Xcode
               CHMOD = /bin/chmod
               CHOWN = /usr/sbin/chown
               CLANG_ANALYZER_NONNULL = YES
               CLANG_CXX_LANGUAGE_STANDARD = gnu++0x
               CLANG_CXX_LIBRARY = libc++
               CLANG_ENABLE_MODULES = YES
               CLANG_ENABLE_OBJC_ARC = YES
               CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
               CLANG_WARN_BOOL_CONVERSION = YES
               CLANG_WARN_COMMA = YES
               CLANG_WARN_CONSTANT_CONVERSION = YES
               CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES
               CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR
               CLANG_WARN_EMPTY_BODY = YES
               CLANG_WARN_ENUM_CONVERSION = YES
               CLANG_WARN_INFINITE_RECURSION = YES
               CLANG_WARN_INT_CONVERSION = YES
               CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
               CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES
               CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
               CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR
               CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
               CLANG_WARN_STRICT_PROTOTYPES = YES
               CLANG_WARN_SUSPICIOUS_MOVE = YES
               CLANG_WARN_UNREACHABLE_CODE = YES
               CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
               CLASS_FILE_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/JavaClasses
               CLEAN_PRECOMPS = YES
               CLONE_HEADERS = NO
               CODESIGNING_FOLDER_PATH = /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app
               CODE_SIGNING_ALLOWED = YES
               CODE_SIGNING_REQUIRED = YES
               CODE_SIGN_CONTEXT_CLASS = XCiPhoneSimulatorCodeSignContext
               CODE_SIGN_IDENTITY = -
               CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
               COLOR_DIAGNOSTICS = NO
               COMBINE_HIDPI_IMAGES = NO
               COMPILER_INDEX_STORE_ENABLE = NO
               COMPOSITE_SDK_DIRS = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/CompositeSDKs
               COMPRESS_PNG_FILES = YES
               CONFIGURATION = Debug
               CONFIGURATION_BUILD_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator
               CONFIGURATION_TEMP_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator
               CONTENTS_FOLDER_PATH = Runner.app
               COPYING_PRESERVES_HFS_DATA = NO
               COPY_HEADERS_RUN_UNIFDEF = NO
               COPY_PHASE_STRIP = NO
               COPY_RESOURCES_FROM_STATIC_FRAMEWORKS = YES
               CORRESPONDING_DEVICE_PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               CORRESPONDING_DEVICE_PLATFORM_NAME = iphoneos
               CORRESPONDING_DEVICE_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
               CORRESPONDING_DEVICE_SDK_NAME = iphoneos13.2
               CP = /bin/cp
               CREATE_INFOPLIST_SECTION_IN_BINARY = NO
               CURRENT_ARCH = x86_64
               CURRENT_PROJECT_VERSION = 1
               CURRENT_VARIANT = normal
               DART_OBFUSCATION = false
               DEAD_CODE_STRIPPING = YES
               DEBUGGING_SYMBOLS = YES
               DEBUG_INFORMATION_FORMAT = dwarf
               DEFAULT_COMPILER = com.apple.compilers.llvm.clang.1_0
               DEFAULT_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
               DEFAULT_KEXT_INSTALL_PATH = /System/Library/Extensions
               DEFINES_MODULE = NO
               DEPLOYMENT_LOCATION = NO
               DEPLOYMENT_POSTPROCESSING = NO
               DEPLOYMENT_TARGET_CLANG_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_CLANG_FLAG_NAME = mios-simulator-version-min
               DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX = -mios-simulator-version-min=
               DEPLOYMENT_TARGET_LD_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_LD_FLAG_NAME = ios_simulator_version_min
               DEPLOYMENT_TARGET_SETTING_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_SUGGESTED_VALUES = 8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4 13.0 13.1 13.2
               DERIVED_FILES_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               DERIVED_FILE_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               DERIVED_SOURCES_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               DEVELOPER_FRAMEWORKS_DIR = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_FRAMEWORKS_DIR_QUOTED = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/Developer/Library
               DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Tools
               DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               DEVELOPMENT_LANGUAGE = en
               DOCUMENTATION_FOLDER_PATH = Runner.app/en.lproj/Documentation
               DONT_GENERATE_INFOPLIST_FILE = NO
               DO_HEADER_SCANNING_IN_JAM = NO
               DSTROOT = /tmp/Runner.dst
               DT_TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               DWARF_DSYM_FILE_NAME = Runner.app.dSYM
               DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
               DWARF_DSYM_FOLDER_PATH = /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator
               EFFECTIVE_PLATFORM_NAME = -iphonesimulator
               EMBEDDED_CONTENT_CONTAINS_SWIFT = NO
               EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE = NO
               ENABLE_BITCODE = NO
               ENABLE_DEFAULT_HEADER_SEARCH_PATHS = YES
               ENABLE_HARDENED_RUNTIME = NO
               ENABLE_HEADER_DEPENDENCIES = YES
               ENABLE_ON_DEMAND_RESOURCES = YES
               ENABLE_STRICT_OBJC_MSGSEND = YES
               ENABLE_TESTABILITY = YES
               ENTITLEMENTS_DESTINATION = __entitlements
               ENTITLEMENTS_REQUIRED = YES
               EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS = .DS_Store .svn .git .hg CVS
               EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES = *.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj
               EXECUTABLES_FOLDER_PATH = Runner.app/Executables
               EXECUTABLE_FOLDER_PATH = Runner.app
               EXECUTABLE_NAME = Runner
               EXECUTABLE_PATH = Runner.app/Runner
               EXPANDED_CODE_SIGN_IDENTITY = 
               EXPANDED_CODE_SIGN_IDENTITY_NAME = 
               EXPANDED_PROVISIONING_PROFILE = 
               FILE_LIST = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects/LinkFileList
               FIXED_FILES_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/FixedFiles
               FLUTTER_APPLICATION_PATH = /Users/edwardsc/Desktop/text_1
               FLUTTER_BUILD_DIR = build
               FLUTTER_BUILD_NAME = 1.0.0
               FLUTTER_BUILD_NUMBER = 1
               FLUTTER_FRAMEWORK_DIR = /Users/edwardsc/dev/flutter/bin/cache/artifacts/engine/ios
               FLUTTER_ROOT = /Users/edwardsc/dev/flutter
               FLUTTER_SUPPRESS_ANALYTICS = true
               FLUTTER_TARGET = /Users/edwardsc/Desktop/text_1/lib/main.dart
               FRAMEWORKS_FOLDER_PATH = Runner.app/Frameworks
               FRAMEWORK_FLAG_PREFIX = -framework
               FRAMEWORK_SEARCH_PATHS =  /Users/edwardsc/Desktop/text_1/ios/Flutter
               FRAMEWORK_VERSION = A
               FULL_PRODUCT_NAME = Runner.app
               GCC3_VERSION = 3.3
               GCC_C_LANGUAGE_STANDARD = gnu99
               GCC_DYNAMIC_NO_PIC = NO
               GCC_INLINES_ARE_PRIVATE_EXTERN = YES
               GCC_NO_COMMON_BLOCKS = YES
               GCC_OBJC_LEGACY_DISPATCH = YES
               GCC_OPTIMIZATION_LEVEL = 0
               GCC_PFE_FILE_C_DIALECTS = c objective-c c++ objective-c++
               GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1 
               GCC_SYMBOLS_PRIVATE_EXTERN = NO
               GCC_TREAT_WARNINGS_AS_ERRORS = NO
               GCC_VERSION = com.apple.compilers.llvm.clang.1_0
               GCC_VERSION_IDENTIFIER = com_apple_compilers_llvm_clang_1_0
               GCC_WARN_64_TO_32_BIT_CONVERSION = YES
               GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR
               GCC_WARN_UNDECLARED_SELECTOR = YES
               GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE
               GCC_WARN_UNUSED_FUNCTION = YES
               GCC_WARN_UNUSED_VARIABLE = YES
               GENERATE_MASTER_OBJECT_FILE = NO
               GENERATE_PKGINFO_FILE = YES
               GENERATE_PROFILING_CODE = NO
               GENERATE_TEXT_BASED_STUBS = NO
               GID = 20
               GROUP = staff
               HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT = YES
               HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES = YES
               HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS = YES
               HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
               HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
               HEADERMAP_USES_VFS = NO
               HIDE_BITCODE_SYMBOLS = YES
               HOME = /Users/edwardsc
               ICONV = /usr/bin/iconv
               INFOPLIST_EXPAND_BUILD_SETTINGS = YES
               INFOPLIST_FILE = Runner/Info.plist
               INFOPLIST_OUTPUT_FORMAT = binary
               INFOPLIST_PATH = Runner.app/Info.plist
               INFOPLIST_PREPROCESS = NO
               INFOSTRINGS_PATH = Runner.app/en.lproj/InfoPlist.strings
               INLINE_PRIVATE_FRAMEWORKS = NO
               INSTALLHDRS_COPY_PHASE = NO
               INSTALLHDRS_SCRIPT_PHASE = NO
               INSTALL_DIR = /tmp/Runner.dst/Applications
               INSTALL_GROUP = staff
               INSTALL_MODE_FLAG = u+w,go-w,a+rX
               INSTALL_OWNER = edwardsc
               INSTALL_PATH = /Applications
               INSTALL_ROOT = /tmp/Runner.dst
               IPHONEOS_DEPLOYMENT_TARGET = 8.0
               JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8
               JAVA_APP_STUB = /System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               JAVA_ARCHIVE_CLASSES = YES
               JAVA_ARCHIVE_TYPE = JAR
               JAVA_COMPILER = /usr/bin/javac
               JAVA_FOLDER_PATH = Runner.app/Java
               JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
               JAVA_JAR_FLAGS = cv
               JAVA_SOURCE_SUBDIR = .
               JAVA_USE_DEPENDENCIES = YES
               JAVA_ZIP_FLAGS = -urg
               JIKES_DEFAULT_FLAGS = +E +OLDCSO
               KEEP_PRIVATE_EXTERNS = NO
               LD_DEPENDENCY_INFO_FILE = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat
               LD_GENERATE_MAP_FILE = NO
               LD_MAP_FILE_PATH = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-LinkMap-normal-x86_64.txt
               LD_NO_PIE = NO
               LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
               LD_RUNPATH_SEARCH_PATHS =  @executable_path/Frameworks
               LEGACY_DEVELOPER_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               LEX = lex
               LIBRARY_DEXT_INSTALL_PATH = /Library/DriverExtensions
               LIBRARY_FLAG_NOSPACE = YES
               LIBRARY_FLAG_PREFIX = -l
               LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
               LIBRARY_SEARCH_PATHS =  /Users/edwardsc/Desktop/text_1/ios/Flutter
               LINKER_DISPLAYS_MANGLED_NAMES = NO
               LINK_FILE_LIST_normal_x86_64 = 
               LINK_WITH_STANDARD_LIBRARIES = YES
               LLVM_TARGET_TRIPLE_OS_VERSION = ios8.0
               LLVM_TARGET_TRIPLE_SUFFIX = -simulator
               LLVM_TARGET_TRIPLE_VENDOR = apple
               LOCALIZABLE_CONTENT_DIR = 
               LOCALIZED_RESOURCES_FOLDER_PATH = Runner.app/en.lproj
               LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString CFCopyLocalizedString
               LOCALIZED_STRING_SWIFTUI_SUPPORT = YES
               LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
               LOCAL_APPS_DIR = /Applications
               LOCAL_DEVELOPER_DIR = /Library/Developer
               LOCAL_LIBRARY_DIR = /Library
               LOCROOT = 
               LOCSYMROOT = 
               MACH_O_TYPE = mh_execute
               MAC_OS_X_PRODUCT_BUILD_VERSION = 18G103
               MAC_OS_X_VERSION_ACTUAL = 101406
               MAC_OS_X_VERSION_MAJOR = 101400
               MAC_OS_X_VERSION_MINOR = 1406
               METAL_LIBRARY_FILE_BASE = default
               METAL_LIBRARY_OUTPUT_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/Runner.app
               MODULES_FOLDER_PATH = Runner.app/Modules
               MODULE_CACHE_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               MTL_ENABLE_DEBUG_INFO = YES
               NATIVE_ARCH = i386
               NATIVE_ARCH_32_BIT = i386
               NATIVE_ARCH_64_BIT = x86_64
               NATIVE_ARCH_ACTUAL = x86_64
               NO_COMMON = YES
               OBJC_ABI_VERSION = 2
               OBJECT_FILE_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects
               OBJECT_FILE_DIR_normal = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
               OBJROOT = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex
               ONLY_ACTIVE_ARCH = YES
               OS = MACOS
               OSAC = /usr/bin/osacompile
               OTHER_LDFLAGS =  -framework Flutter
               PACKAGE_TYPE = com.apple.package-type.wrapper.application
               PASCAL_STRINGS = YES
               PATH = /Applications/Xcode.app/Contents/Developer/usr/bin:/Users/edwardsc/.rbenv/shims:/Users/edwardsc/.gem/ruby/2.6.0/bin:/Users/edwardsc/Library/Android/sdk/platform-tools:/Users/edwardsc/Library/Android/sdk/tools:/Users/edwardsc/.pub-cache/bin:/Users/edwardsc/dev/flutter/bin/cache/dart-sdk/bin:/Users/edwardsc/dev/flutter/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/mysql-client/bin:/Users/edwardsc/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/edwardsc/.rbenv/shims:/Users/edwardsc/.gem/ruby/2.6.0/bin:/Users/edwardsc/Library/Android/sdk/platform-tools:/Users/edwardsc/Library/Android/sdk/tools:/Users/edwardsc/.pub-cache/bin:/Users/edwardsc/dev/flutter/bin/cache/dart-sdk/bin:/Users/edwardsc/dev/flutter/bin:/opt/local/bin:/opt/local/sbin:/usr/local/opt/mysql-client/bin:/Users/edwardsc/bin:/Users/edwardsc/.ec2/bin:/Users/edwardsc/.ec2/bin
               PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES = /usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms
               PBDEVELOPMENTPLIST_PATH = Runner.app/pbdevelopment.plist
               PFE_FILE_C_DIALECTS = objective-c
               PKGINFO_FILE_PATH = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PkgInfo
               PKGINFO_PATH = Runner.app/PkgInfo
               PLATFORM_DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
               PLATFORM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
               PLATFORM_DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
               PLATFORM_DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
               PLATFORM_DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
               PLATFORM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
               PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               PLATFORM_DISPLAY_NAME = iOS Simulator
               PLATFORM_NAME = iphonesimulator
               PLATFORM_PREFERRED_ARCH = x86_64
               PLATFORM_PRODUCT_BUILD_VERSION = 17B102
               PLIST_FILE_OUTPUT_FORMAT = binary
               PLUGINS_FOLDER_PATH = Runner.app/PlugIns
               PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR = YES
               PRECOMP_DESTINATION_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PrefixHeaders
               PRESERVE_DEAD_CODE_INITS_AND_TERMS = NO
               PRIVATE_HEADERS_FOLDER_PATH = Runner.app/PrivateHeaders
               PRODUCT_BUNDLE_IDENTIFIER = com.example.text1
               PRODUCT_BUNDLE_PACKAGE_TYPE = APPL
               PRODUCT_MODULE_NAME = Runner
               PRODUCT_NAME = Runner
               PRODUCT_SETTINGS_PATH = /Users/edwardsc/Desktop/text_1/ios/Runner/Info.plist
               PRODUCT_TYPE = com.apple.product-type.application
               PROFILING_CODE = NO
               PROJECT = Runner
               PROJECT_DERIVED_FILE_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/DerivedSources
               PROJECT_DIR = /Users/edwardsc/Desktop/text_1/ios
               PROJECT_FILE_PATH = /Users/edwardsc/Desktop/text_1/ios/Runner.xcodeproj
               PROJECT_NAME = Runner
               PROJECT_TEMP_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build
               PROJECT_TEMP_ROOT = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex
               PUBLIC_HEADERS_FOLDER_PATH = Runner.app/Headers
               RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS = YES
               REMOVE_CVS_FROM_RESOURCES = YES
               REMOVE_GIT_FROM_RESOURCES = YES
               REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES = YES
               REMOVE_HG_FROM_RESOURCES = YES
               REMOVE_SVN_FROM_RESOURCES = YES
               REZ_COLLECTOR_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources
               REZ_OBJECTS_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources/Objects
               SCAN_ALL_SOURCE_FILES_FOR_INCLUDES = NO
               SCRIPTS_FOLDER_PATH = Runner.app/Scripts
               SCRIPT_OUTPUT_STREAM_FILE = /var/folders/wf/9_v52sxn3754f4mzf658nwfh0000gn/T/flutter_tools.ZLfbtl/flutter_build_log_pipe.sUprNk/pipe_to_stdout
               SDKROOT = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               SDK_DIR_iphonesimulator13_2 = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
               SDK_NAME = iphonesimulator13.2
               SDK_NAMES = iphonesimulator13.2
               SDK_PRODUCT_BUILD_VERSION = 17B102
               SDK_VERSION = 13.2
               SDK_VERSION_ACTUAL = 130200
               SDK_VERSION_MAJOR = 130000
               SDK_VERSION_MINOR = 200
               SED = /usr/bin/sed
               SEPARATE_STRIP = NO
               SEPARATE_SYMBOL_EDIT = NO
               SET_DIR_MODE_OWNER_GROUP = YES
               SET_FILE_MODE_OWNER_GROUP = NO
               SHALLOW_BUNDLE = YES
               SHARED_DERIVED_FILE_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator/DerivedSources
               SHARED_FRAMEWORKS_FOLDER_PATH = Runner.app/SharedFrameworks
               SHARED_PRECOMPS_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/PrecompiledHeaders
               SHARED_SUPPORT_FOLDER_PATH = Runner.app/SharedSupport
               SKIP_INSTALL = NO
               SOURCE_ROOT = /Users/edwardsc/Desktop/text_1/ios
               SRCROOT = /Users/edwardsc/Desktop/text_1/ios
               STRINGS_FILE_OUTPUT_ENCODING = binary
               STRIP_BITCODE_FROM_COPIED_FILES = NO
               STRIP_INSTALLED_PRODUCT = YES
               STRIP_STYLE = all
               STRIP_SWIFT_SYMBOLS = YES
               SUPPORTED_DEVICE_FAMILIES = 1,2
               SUPPORTED_PLATFORMS = iphonesimulator iphoneos
               SUPPORTS_TEXT_BASED_API = NO
               SWIFT_OBJC_BRIDGING_HEADER = Runner/Runner-Bridging-Header.h
               SWIFT_OPTIMIZATION_LEVEL = -Onone
               SWIFT_PLATFORM_TARGET_PREFIX = ios
               SWIFT_VERSION = 5.0
               SYMROOT = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Products
               SYSTEM_ADMIN_APPS_DIR = /Applications/Utilities
               SYSTEM_APPS_DIR = /Applications
               SYSTEM_CORE_SERVICES_DIR = /System/Library/CoreServices
               SYSTEM_DEMOS_DIR = /Applications/Extras
               SYSTEM_DEVELOPER_APPS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               SYSTEM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               SYSTEM_DEVELOPER_DEMOS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples
               SYSTEM_DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               SYSTEM_DEVELOPER_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library
               SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools
               SYSTEM_DEVELOPER_JAVA_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Java Tools
               SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Performance Tools
               SYSTEM_DEVELOPER_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes
               SYSTEM_DEVELOPER_TOOLS = /Applications/Xcode.app/Contents/Developer/Tools
               SYSTEM_DEVELOPER_TOOLS_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools
               SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools
               SYSTEM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               SYSTEM_DEVELOPER_UTILITIES_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities
               SYSTEM_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
               SYSTEM_DOCUMENTATION_DIR = /Library/Documentation
               SYSTEM_KEXT_INSTALL_PATH = /System/Library/Extensions
               SYSTEM_LIBRARY_DIR = /System/Library
               TAPI_VERIFY_MODE = ErrorsOnly
               TARGETED_DEVICE_FAMILY = 1,2
               TARGETNAME = Runner
               TARGET_BUILD_DIR = /Users/edwardsc/Desktop/text_1/build/ios/Debug-iphonesimulator
               TARGET_NAME = Runner
               TARGET_TEMP_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               TEMP_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               TEMP_FILES_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               TEMP_FILE_DIR = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               TEMP_ROOT = /Users/edwardsc/Library/Developer/Xcode/DerivedData/Runner-ecwzrapsdpqxfnaflrkyclzgxfuf/Build/Intermediates.noindex
               TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               TRACK_WIDGET_CREATION = true
               TREAT_MISSING_BASELINES_AS_TEST_FAILURES = NO
               TREE_SHAKE_ICONS = false
               UID = 501
               UNLOCALIZED_RESOURCES_FOLDER_PATH = Runner.app
               UNSTRIPPED_PRODUCT = NO
               USER = edwardsc
               USER_APPS_DIR = /Users/edwardsc/Applications
               USER_LIBRARY_DIR = /Users/edwardsc/Library
               USE_DYNAMIC_NO_PIC = YES
               USE_HEADERMAP = YES
               USE_HEADER_SYMLINKS = NO
               USE_LLVM_TARGET_TRIPLES = YES
               USE_LLVM_TARGET_TRIPLES_FOR_CLANG = YES
               USE_LLVM_TARGET_TRIPLES_FOR_LD = YES
               USE_LLVM_TARGET_TRIPLES_FOR_TAPI = YES
               VALIDATE_PRODUCT = NO
               VALIDATE_WORKSPACE = NO
               VALID_ARCHS = i386 x86_64
               VERBOSE_PBXCP = NO
               VERBOSE_SCRIPT_LOGGING = YES
               VERSIONING_SYSTEM = apple-generic
               VERSIONPLIST_PATH = Runner.app/version.plist
               VERSION_INFO_BUILDER = edwardsc
               VERSION_INFO_FILE = Runner_vers.c
               VERSION_INFO_STRING = "@(#)PROGRAM:Runner  PROJECT:Runner-1"
               WRAPPER_EXTENSION = app
               WRAPPER_NAME = Runner.app
               WRAPPER_SUFFIX = .app
               WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
               XCODE_APP_SUPPORT_DIR = /Applications/Xcode.app/Contents/Developer/Library/Xcode
               XCODE_PRODUCT_BUILD_VERSION = 11B500
               XCODE_VERSION_ACTUAL = 1121
               XCODE_VERSION_MAJOR = 1100
               XCODE_VERSION_MINOR = 1120
               XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
               YACC = yacc
               arch = x86_64
               variant = normal
[ +306 ms] executing: /usr/bin/xcrun simctl install 537708A7-5E27-4804-B6C9-D233D029B49A /Users/edwardsc/Desktop/text_1/build/ios/iphonesimulator/Runner.app
[ +507 ms] executing: /usr/bin/plutil -convert json -o - /Users/edwardsc/Desktop/text_1/build/ios/iphonesimulator/Runner.app/Info.plist
[  +10 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/edwardsc/Desktop/text_1/build/ios/iphonesimulator/Runner.app/Info.plist
[        ] {"CFBundleName":"text_1","DTSDKName":"iphonesimulator13.2","DTXcode":"1120","CFBundleIcons~ipad":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60","AppIcon76x76","AppIcon83.5x83.5"],"CFBundleIconName":"AppIcon"}},"UILaunchStoryboardName":"LaunchScreen","DTSDKBuild":"17B102","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","BuildMachineOSBuild":"18G103","DTPlatformName":"iphonesimulator","CFBundlePackageType":"APPL","CFBundleShortVersionString":"1.0.0","CFBundleSupportedPlatforms":["iPhoneSimulator"],"UIMainStoryboardFile":"Main","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"Runner","DTCompiler":"com.apple.compilers.llvm.clang.1_0","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"MinimumOSVersion":"8.0","CFBundleIdentifier":"com.example.text1","UIDeviceFamily":[1,2],"CFBundleSignature":"????","DTPlatformVersion":"13.2","CFBundleIcons":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60"],"CFBundleIconName":"AppIcon"}},"DTXcodeBuild":"11B500","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrientations":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"UIViewControllerBasedStatusBarAppearance":false,"DTPlatformBuild":"17B102"}
[   +1 ms] executing: /usr/bin/xcrun simctl launch 537708A7-5E27-4804-B6C9-D233D029B49A com.example.text1 --enable-dart-profiling --enable-checked-mode --verify-entry-points --observatory-port=0
[ +162 ms] com.example.text1: 30340
[        ] Waiting for observatory port to be available...
[+1003 ms] Observatory URL on device: http://127.0.0.1:51939/YbjeRv5xMnM=/
[   +5 ms] Caching compiled dill
[  +29 ms] Connecting to service protocol: http://127.0.0.1:51939/YbjeRv5xMnM=/
[ +113 ms] Successfully connected to service protocol: http://127.0.0.1:51939/YbjeRv5xMnM=/
[        ] Waiting for iPhone 11 to report its views...
[   +3 ms] Waiting for iPhone 11 to report its views... (completed in 3ms)
[   +9 ms] DevFS: Creating new filesystem on the device (null)
[  +24 ms] DevFS: Created new filesystem on the device (file:///Users/edwardsc/Library/Developer/CoreSimulator/Devices/537708A7-5E27-4804-B6C9-D233D029B49A/data/Containers/Data/Application/B1A6959F-B6F1-409F-A4C4-E5887720CA7C/tmp/text_194zjhG/text_1/)
[   +4 ms] Updating assets
[  +81 ms] Syncing files to device iPhone 11...
[   +2 ms] Scanning asset files
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:text_1/main.dart a6ac8c52-98ec-448c-83b0-720a830fbb48
[        ] <- a6ac8c52-98ec-448c-83b0-720a830fbb48
[  +43 ms] Updating files
[  +67 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 11... (completed in 117ms)
[        ] Synced 0.9MB.
[   +1 ms] <- accept
[   +1 ms] Connected to _flutterView/0x7f831202b420.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone 11 is available at: http://127.0.0.1:51939/YbjeRv5xMnM=/
[+3629 ms] Application finished.
```

<!--
     Run `flutter analyze` and attach any output of that command below.
     If there are any analysis errors, try resolving them before filing this issue.
-->

```
~/Desktop/text_1> flutter analyze
Analyzing text_1...                                                     
No issues found! (ran in 7.3s)
```

<!-- Finally, paste the output of running `flutter doctor -v` here. -->

```
~/Desktop/text_1> flutter doctor -v
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.14.6 18G103, locale en-AU)
    • Flutter version 1.20.0-0.0.pre at /Users/edwardsc/dev/flutter
    • Framework revision d9653445f4 (2 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/edwardsc/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /Users/edwardsc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • SM A205YN • R58M45EWRCK                          • android-arm64 • Android 9 (API 28)
    • iPhone 11 • 537708A7-5E27-4804-B6C9-D233D029B49A • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
## Description

The widget span is laid out with original size but enlarged after paint. This cause the content to flow out of the box.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/59316

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behaviour with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 1]
```diff
@@ -530,9 +530,10 @@ class RenderParagraph extends RenderBox
       // Only constrain the width to the maximum width of the paragraph.
       // Leave height unconstrained, which will overflow if expanded past.
       child.layout(
-        BoxConstraints(
-          maxWidth: constraints.maxWidth,
-        ),
+        // The content will be enlarged by textScaleFactor during painting phase.
+        // We reduce contraint by textScaleFactor so that the content will fit
+        // into the box once it is enlarged.
+        BoxConstraints(maxWidth: constraints.maxWidth) / textScaleFactor,
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/paragraph.dart:536]: @GaryQian I wonder why do we need _textPainter.inlinePlaceholderScales? aren't they always the same as textScaleFactor?

**Review by justinmc — COMMENTED** [review]
I checked out this branch and ran the code in the issue and it didn't seem to fix the problem for me.  I still saw different sizes when I increased the font size in the phone settings.  Let me know if I messed something up and you don't see the same thing.

Screen Shot 2020-06-17 at 2 33 23 PM

**Comment by chunhtai** [comment]
> I checked out this branch and ran the code in the issue and it didn't seem to fix the problem for me. I still saw different sizes when I increased the font size in the phone settings. Let me know if I messed something up and you don't see the same thing.
> 
> Screen Shot 2020-06-17 at 2 33 23 PM

I think the size scaling is correct (wrapping a RichText inside a RichText will make scaling^2), and the main issue this pr tries to solve is Text wrapping for the inner RichText.
See the text was cut of before the change
image

**Review by justinmc — APPROVED** [review]
Ah I see, thanks for the clarification. I do see the overflowing without this PR and it goes away on your branch. LGTM 👍

File: packages/flutter/lib/src/rendering/paragraph.dart (hunk 1 above)
Comment (GaryQian) [reply packages/flutter/lib/src/rendering/paragraph.dart:536]: I believe that in actual use cases, it is indeed true, but it is also possible (at lower levels) to independently set them. This may or may not be necessary at this level, I can look into it to see if it is safe to remove.

**Review by GaryQian — APPROVED** [review]
LGTM, Thanks!

File: packages/flutter/lib/src/rendering/paragraph.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/paragraph.dart:536]: The scales are added into the list through WidgetSpan.build() which gets its value from the textScaleFactor. I couldn't find a possible way to have a different textscalefactor.

**Comment by thenexus00** [comment]
Wanted to confirm on a real world app that with what effectively is the flutter_html where the html_parser sees the scale factor implemented that. it does not wrap:
https://www.dropbox.com/s/kr72vlx4ij9tiqn/image007.png?dl=0

When will we see the layout flow fix in the master branch?

**Comment by chunhtai** [comment]
This may take a while, we are seeing a large number of test failure in our internal tests. we are in the middle of sorting this out.

**Comment by thenexus00** [comment]
> This may take a while, we are seeing a large number of test failure in our internal tests. we are in the middle of sorting this out.

How is it going on the the tests on this one? If there is a build in master happy to do any tests and report back if you need.
