### PR TITLE
Fix assertion failure when reordering two dimensional children

### LINKED ISSUE #141101: RenderTwoDimensionalViewport.buildOrObtainChildFor throws assertion failure for a valid vicinity
### Steps to reproduce

1. Run the example
2. Press on FAB
3. Press again on FAB

### Expected results

You should see the initial widgets on screen since pressing on FAB for second time returns to the initial state.

### Actual results

Nothing renders on screen and you'll get an exception log in console due to assertion failure in `RenderTwoDimensionalViewport.parentDataOf`

### Code sample

<details open><summary>Code sample</summary>

https://dartpad.dev/?id=2c4cc823007d1dc0a9727be611e62f2c

</details>

### Logs

<details open><summary>Logs</summary>

```console
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/widgets/two_dimensional_viewport.dart': Failed assertion: line 783 pos 12: '_children.containsValue(child)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    TwoDimensionalGridViewport TwoDimensionalGridViewport:file:///main.dart:127:12

When the exception was thrown, this was the stack:
#2      RenderTwoDimensionalViewport.parentDataOf (package:flutter/src/widgets/two_dimensional_viewport.dart:783:12)
#3      RenderTwoDimensionalViewport._moveChild (package:flutter/src/widgets/two_dimensional_viewport.dart:1630:62)
#4      _TwoDimensionalViewportElement.moveRenderObjectChild (package:flutter/src/widgets/two_dimensional_viewport.dart:265:18)
#5      RenderObjectElement.updateSlot (package:flutter/src/widgets/framework.dart:6542:35)
#6      Element.updateSlotForChild.visit (package:flutter/src/widgets/framework.dart:4153:15)
#7      Element.updateSlotForChild.visit (package:flutter/src/widgets/framework.dart:4156:9)
#8      Element.updateSlotForChild.visit (package:flutter/src/widgets/framework.dart:4156:9)
#9      Element.updateSlotForChild.visit (package:flutter/src/widgets/framework.dart:4156:9)
#10     Element.updateSlotForChild (package:flutter/src/widgets/framework.dart:4159:5)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3799:11)
#12     _TwoDimensionalViewportElement._buildChild.<anonymous closure> (package:flutter/src/widgets/two_dimensional_viewport.dart:313:33)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835:19)
#14     _TwoDimensionalViewportElement._buildChild (package:flutter/src/widgets/two_dimensional_viewport.dart:307:12)
#15     RenderTwoDimensionalViewport.buildOrObtainChildFor.<anonymous closure> (package:flutter/src/widgets/two_dimensional_viewport.dart:1427:23)
#16     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657:59)
#17     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071:15)
#18     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657:14)
#19     RenderTwoDimensionalViewport.buildOrObtainChildFor (package:flutter/src/widgets/two_dimensional_viewport.dart:1426:7)
#20     RenderTwoDimensionalGridViewport.layoutChildSequence (package:example/main.dart:227:34)
#21     RenderTwoDimensionalViewport.performLayout (package:flutter/src/widgets/two_dimensional_viewport.dart:1252:5)
#22     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
#23     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
#24     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
#25     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
#26     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#27     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#28     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#29     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#30     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#31     _invoke (dart:ui/hooks.dart:312:13)
#32     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#33     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)

The following RenderObject was being processed when the exception was fired: RenderTwoDimensionalGridViewport#9d954 NEEDS-LAYOUT
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=984.0, 0.0<=h<=691.0)
    layer: OffsetLayer#dc1bd
        engine layer: OffsetEngineLayer#3c122
        handles: 2
        offset: Offset(0.0, 56.0)
    size: Size(984.0, 691.0)
    (xIndex: 1, yIndex: 1): RenderRepaintBoundary#71f4f NEEDS-PAINT
        needs compositing
        parentData: vicinity=(xIndex: 1, yIndex: 1); layoutOffset=Offset(200.0, 200.0); paintOffset=Offset(0.0, 0.0); visible - paintExtent=Size(200.0, 200.0);
        constraints: BoxConstraints(0.0<=w<=984.0, 0.0<=h<=691.0)
        layer: OffsetLayer#8295b
            engine layer: OffsetEngineLayer#415f8
            handles: 2
            offset: Offset(0.0, 0.0)
        size: Size(200.0, 200.0)
        metrics: 66.7% useful (1 bad vs 2 good)
        diagnosis: insufficient data to draw conclusion (less than five repaints)
        child: RenderConstrainedBox#f153a relayoutBoundary=up1 NEEDS-PAINT
            parentData: <none> (can use size)
            constraints: BoxConstraints(0.0<=w<=984.0, 0.0<=h<=691.0)
            size: Size(200.0, 200.0)
            additionalConstraints: BoxConstraints(w=200.0, h=200.0)
            child: _RenderColoredBox#e6003 NEEDS-PAINT
                parentData: <none> (can use size)
                constraints: BoxConstraints(w=200.0, h=200.0)
                size: Size(200.0, 200.0)
                behavior: opaque
                child: RenderPositionedBox#d4659
                    parentData: <none> (can use size)
                    constraints: BoxConstraints(w=200.0, h=200.0)
                    size: Size(200.0, 200.0)
                    alignment: Alignment.center
                    textDirection: ltr
                    widthFactor: expand
                    heightFactor: expand
RenderObject: RenderTwoDimensionalGridViewport#9d954 NEEDS-LAYOUT
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=984.0, 0.0<=h<=691.0)
    layer: OffsetLayer#dc1bd
        engine layer: OffsetEngineLayer#3c122
        handles: 2
        offset: Offset(0.0, 56.0)
    size: Size(984.0, 691.0)
    (xIndex: 1, yIndex: 1): RenderRepaintBoundary#71f4f NEEDS-PAINT
        needs compositing
        parentData: vicinity=(xIndex: 1, yIndex: 1); layoutOffset=Offset(200.0, 200.0); paintOffset=Offset(0.0, 0.0); visible - paintExtent=Size(200.0, 200.0);
        constraints: BoxConstraints(0.0<=w<=984.0, 0.0<=h<=691.0)
        layer: OffsetLayer#8295b
            engine layer: OffsetEngineLayer#415f8
            handles: 2
            offset: Offset(0.0, 0.0)
        size: Size(200.0, 200.0)
        metrics: 66.7% useful (1 bad vs 2 good)
        diagnosis: insufficient data to draw conclusion (less than five repaints)
        child: RenderConstrainedBox#f153a relayoutBoundary=up1 NEEDS-PAINT
            parentData: <none> (can use size)
            constraints: BoxConstraints(0.0<=w<=984.0, 0.0<=h<=691.0)
            size: Size(200.0, 200.0)
            additionalConstraints: BoxConstraints(w=200.0, h=200.0)
            child: _RenderColoredBox#e6003 NEEDS-PAINT
                parentData: <none> (can use size)
                constraints: BoxConstraints(w=200.0, h=200.0)
                size: Size(200.0, 200.0)
                behavior: opaque
                child: RenderPositionedBox#d4659
                    parentData: <none> (can use size)
                    constraints: BoxConstraints(w=200.0, h=200.0)
                    size: Size(200.0, 200.0)
                    alignment: Alignment.center
                    textDirection: ltr
                    widthFactor: expand
                    heightFactor: expand
════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.1, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-US)
    • Flutter version 3.16.1 on channel stable at /flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (6 weeks ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3
```

</details>

### PR DESCRIPTION
**Pull request by Amir-P**
It fixes assertion failure due to unstable state of children list during reordering in `RenderTwoDimensionalViewport.parentDataOf`. This changes the assertion to check debug orphan list and `keepAlive` bucket in addition to children list to determine whether child belongs to this render object or not.

- Fixes #141101 

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/widgets/two_dimensional_utils.dart [hunk 1]
```diff
@@ -195,7 +195,7 @@ class RenderSimpleBuilderTableViewport extends RenderTwoDimensionalViewport {
 
   @override
   TestExtendedParentData parentDataOf(RenderBox child) {
-    return child.parentData! as TestExtendedParentData;
+    return super.parentDataOf(child) as TestExtendedParentData;
```
Comment (Piinks) [inline packages/flutter/test/widgets/two_dimensional_utils.dart:198]: This makes me wonder if we should add `@mustCallSuper` to the method in the base class

File: packages/flutter/lib/src/widgets/two_dimensional_viewport.dart [hunk 2]
```diff
@@ -780,7 +780,9 @@ abstract class RenderTwoDimensionalViewport extends RenderBox implements RenderA
   /// [TwoDimensionalViewportParentData], or a subclass thereof.
   @protected
   TwoDimensionalViewportParentData parentDataOf(RenderBox child) {
-    assert(_children.containsValue(child));
+    assert(_children.containsValue(child) ||
+        _keepAliveBucket.containsValue(child) ||
+        _debugOrphans!.contains(child));
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/two_dimensional_viewport.dart:785]: Yeah, I think this is definitely right, since during layout we may need to access parent data on any of the children currently being moved around. 👍

File: packages/flutter/test/widgets/two_dimensional_utils.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/test/widgets/two_dimensional_utils.dart:198]: Can you add that in this PR?

File: packages/flutter/test/widgets/two_dimensional_viewport_test.dart [hunk 3]
```diff
@@ -2711,6 +2711,54 @@ void main() {
         );
       });
     });
+
+    testWidgets('correctly reorders children and wont throw assertion failure',
```
Comment (Piinks) [inline packages/flutter/test/widgets/two_dimensional_viewport_test.dart:2715]: This test currently passes without your change, so it does not verify the fix. I would recommend using the code you shared in the issue that demonstrated the crash.

**Review by Piinks — COMMENTED** [review]
Thank you for contributing @Amir-P!

File: packages/flutter/test/widgets/two_dimensional_viewport_test.dart (hunk 3 above)
Comment (Amir-P) [reply packages/flutter/test/widgets/two_dimensional_viewport_test.dart:2715]: I just ran it again and I can assure you that it's failing if you revert the changes in `two_dimensional_viewport.dart`. Maybe you're also reverting the changes in `two_dimensional_utils.dart` too?

**Comment by Amir-P** [comment]
@Piinks Could you please take a look again? Also do you think we should include https://github.com/flutter/flutter/issues/130754 as issues this PR fixes?

**Comment by Piinks** [comment]
I don't think this will fix https://github.com/flutter/flutter/issues/130754

This fixes a reordering issue, but I don't think it preserves the state of children when they are reordered. A good way to check this is to place a Checkbox as a child of the viewport, check it, and then reorder it. The checkbox will move, but it won't be checked anymore. Since the test here is a SizedBox, there is no state for it that we're validating in the test. :)

File: packages/flutter/test/widgets/two_dimensional_viewport_test.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter/test/widgets/two_dimensional_viewport_test.dart:2715]: Oh I bet you are right! I missed updating the call to the super class. Thanks for verifying!

**Comment by Piinks** [comment]
This might fix https://github.com/flutter/flutter/issues/138977 though :)

**Review by Piinks — APPROVED** [review]
This LGTM, the flutter/packages change will need to land first. 💯

**Comment by Amir-P** [comment]
> I don't think this will fix #130754
> 
> This fixes a reordering issue, but I don't think it preserves the state of children when they are reordered. A good way to check this is to place a Checkbox as a child of the viewport, check it, and then reorder it. The checkbox will move, but it won't be checked anymore. Since the test here is a SizedBox, there is no state for it that we're validating in the test. :)

I haven't checked how the reordering is handled in 1D scrolling but using a key on built widgets for 2D viewport, it's working correctly. Am I missing something? @Piinks 

Sample:
```dart
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      scrollBehavior: const MaterialScrollBehavior().copyWith(
        // Mouse dragging enabled for this demo
        dragDevices: PointerDeviceKind.values.toSet(),
      ),
      debugShowCheckedModeBanner: false,
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

final vicinityToKey1 = <ChildVicinity, String>{
  ChildVicinity(xIndex: 1, yIndex: 1): '1',
  ChildVicinity(xIndex: 1, yIndex: 2): '2',
};

final vicinityToKey2 = <ChildVicinity, String>{
  ChildVicinity(xIndex: 0, yIndex: 0): '1',
  ChildVicinity(xIndex: 1, yIndex: 1): '2',
};

class _MyHomePageState extends State<MyHomePage> {
  late Map<ChildVicinity, String> vicinityToKey = vicinityToKey1;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      floatingActionButton: FloatingActionButton(
        onPressed: () => setState(() {
          if (vicinityToKey == vicinityToKey1) {
            vicinityToKey = vicinityToKey2;
          } else {
            vicinityToKey = vicinityToKey1;
          }
        }),
      ),
      body: TwoDimensionalGridView(
        diagonalDragBehavior: DiagonalDragBehavior.free,
        delegate: TwoDimensionalChildBuilderDelegate(
            maxXIndex: 30,
            maxYIndex: 30,
            addAutomaticKeepAlives: false,
            addRepaintBoundaries: false,
            builder: (BuildContext context, ChildVicinity vicinity) {
              final key = vicinityToKey[vicinity];
              if (key != null) {
                return _Item(key: ValueKey(key), title: key);
              }
              return null;
            }),
      ),
    );
  }
}

class _Item extends StatefulWidget {
  final String title;

  const _Item({super.key, required this.title});

  @override
  State<_Item> createState() => __ItemState();
}

class __ItemState extends State<_Item> {
  Color color = Colors.amber[50]!;

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () => setState(() {
        if (color == Colors.amber[50]!) {
          color = Colors.purple[50]!;
        } else {
          color = Colors.amber[50]!;
        }
      }),
      child: Container(
        color: color,
        height: 200,
        width: 200,
        child: Center(child: Text(widget.title)),
      ),
    );
  }
}

class TwoDimensionalGridView extends TwoDimensionalScrollView {
  const TwoDimensionalGridView({
    super.key,
    super.primary,
    super.mainAxis = Axis.vertical,
    super.verticalDetails = const ScrollableDetails.vertical(),
    super.horizontalDetails = const ScrollableDetails.horizontal(),
    required TwoDimensionalChildBuilderDelegate delegate,
    super.cacheExtent,
    super.diagonalDragBehavior = DiagonalDragBehavior.none,
    super.dragStartBehavior = DragStartBehavior.start,
    super.keyboardDismissBehavior = ScrollViewKeyboardDismissBehavior.manual,
    super.clipBehavior = Clip.hardEdge,
  }) : super(delegate: delegate);

  @override
  Widget buildViewport(
    BuildContext context,
    ViewportOffset verticalOffset,
    ViewportOffset horizontalOffset,
  ) {
    return TwoDimensionalGridViewport(
      horizontalOffset: horizontalOffset,
      horizontalAxisDirection: horizontalDetails.direction,
      verticalOffset: verticalOffset,
      verticalAxisDirection: verticalDetails.direction,
      mainAxis: mainAxis,
      delegate: delegate as TwoDimensionalChildBuilderDelegate,
      cacheExtent: cacheExtent,
      clipBehavior: clipBehavior,
    );
  }
}

class TwoDimensionalGridViewport extends TwoDimensionalViewport {
  const TwoDimensionalGridViewport({
    super.key,
    required super.verticalOffset,
    required super.verticalAxisDirection,
    required super.horizontalOffset,
    required super.horizontalAxisDirection,
    required TwoDimensionalChildBuilderDelegate super.delegate,
    required super.mainAxis,
    super.cacheExtent,
    super.clipBehavior = Clip.hardEdge,
  });

  @override
  RenderTwoDimensionalViewport createRenderObject(BuildContext context) {
    return RenderTwoDimensionalGridViewport(
      horizontalOffset: horizontalOffset,
      horizontalAxisDirection: horizontalAxisDirection,
      verticalOffset: verticalOffset,
      verticalAxisDirection: verticalAxisDirection,
      mainAxis: mainAxis,
      delegate: delegate as TwoDimensionalChildBuilderDelegate,
      childManager: context as TwoDimensionalChildManager,
      cacheExtent: cacheExtent,
      clipBehavior: clipBehavior,
    );
  }

  @override
  void updateRenderObject(
    BuildContext context,
    RenderTwoDimensionalGridViewport renderObject,
  ) {
    renderObject
      ..horizontalOffset = horizontalOffset
      ..horizontalAxisDirection = horizontalAxisDirection
      ..verticalOffset = verticalOffset
      ..verticalAxisDirection = verticalAxisDirection
      ..mainAxis = mainAxis
      ..delegate = delegate
      ..cacheExtent = cacheExtent
      ..clipBehavior = clipBehavior;
  }
}

class RenderTwoDimensionalGridViewport extends RenderTwoDimensionalViewport {
  RenderTwoDimensionalGridViewport({
    required super.horizontalOffset,
    required super.horizontalAxisDirection,
    required super.verticalOffset,
    required super.verticalAxisDirection,
    required TwoDimensionalChildBuilderDelegate delegate,
    required super.mainAxis,
    required super.childManager,
    super.cacheExtent = 10,
    super.clipBehavior = Clip.hardEdge,
  }) : super(delegate: delegate);

  @override
  TwoDimensionalViewportParentData parentDataOf(RenderBox child) {
    return child.parentData! as TwoDimensionalViewportParentData;
  }

  @override
  void layoutChildSequence() {
    final double horizontalPixels = horizontalOffset.pixels;
    final double verticalPixels = verticalOffset.pixels;
    final double viewportWidth = viewportDimension.width + cacheExtent;
    final double viewportHeight = viewportDimension.height + cacheExtent;
    final TwoDimensionalChildBuilderDelegate builderDelegate =
        delegate as TwoDimensionalChildBuilderDelegate;

    final int maxRowIndex = builderDelegate.maxYIndex!;
    final int maxColumnIndex = builderDelegate.maxXIndex!;

    final int leadingColumn = math.max((horizontalPixels / 200).floor(), 0);
    final int leadingRow = math.max((verticalPixels / 200).floor(), 0);
    final int trailingColumn = math.min(
      ((horizontalPixels + viewportWidth) / 200).ceil(),
      maxColumnIndex,
    );
    final int trailingRow = math.min(
      ((verticalPixels + viewportHeight) / 200).ceil(),
      maxRowIndex,
    );

    double xLayoutOffset = (leadingColumn * 200) - horizontalOffset.pixels;
    for (int column = leadingColumn; column <= trailingColumn; column++) {
      double yLayoutOffset = (leadingRow * 200) - verticalOffset.pixels;
      for (int row = leadingRow; row <= trailingRow; row++) {
        final ChildVicinity vicinity =
            ChildVicinity(xIndex: column, yIndex: row);
        final RenderBox? child = buildOrObtainChildFor(vicinity);

        if (child != null) {
          child.layout(constraints.loosen());

          // Subclasses only need to set the normalized layout offset. The super
          // class adjusts for reversed axes.
          parentDataOf(child).layoutOffset =
              Offset(xLayoutOffset, yLayoutOffset);
        }

        yLayoutOffset += 200;
      }
      xLayoutOffset += 200;
    }

    // Set the min and max scroll extents for each axis.
    final double verticalExtent = 200 * (maxRowIndex + 1);
    verticalOffset.applyContentDimensions(
      0.0,
      clampDouble(
          verticalExtent - viewportDimension.height, 0.0, double.infinity),
    );
    final double horizontalExtent = 200 * (maxColumnIndex + 1);
    horizontalOffset.applyContentDimensions(
      0.0,
      clampDouble(
          horizontalExtent - viewportDimension.width, 0.0, double.infinity),
    );
    // Super class handles garbage collection too!
  }
}
```

**Comment by Piinks** [comment]
Oh interesting! Let me look at the code you provided. I really appreciate all of the work you have been putting into this!

Are you interested in seeing if this fixes https://github.com/flutter/flutter/issues/138977 as well? If so, would you add a test? 

In 1D, the findIndexByKey in SliverChildDelegate, SliverChildBuilderDelegate, and SliverChildListDelegate handles stateful reordering. If we do not need to add more API surface though, it would be great! thanks again, and I will report back once I check out your sample code above!

**Comment by Amir-P** [comment]
Hi @Piinks, were you able to test the snippet? Can we add the #130754 too and get this merged?

**Review by Piinks — COMMENTED** [review]
I did check it out! Thank you! I agree, I think we can close https://github.com/flutter/flutter/issues/130754 with this change. However, we will need to add a test that validates that scenario. Some sample code would probably be a good idea to include in the docs as well. 

Would you like to add a test/sample code? Or we can leave https://github.com/flutter/flutter/issues/130754 open for now and add those in another PR. Let me know how you would like to move forward.

Also - a rebase with head should clear that flutter_plugins check. :)

**Comment by Amir-P** [comment]
> I did check it out! Thank you! I agree, I think we can close #130754 with this change. However, we will need to add a test that validates that scenario. Some sample code would probably be a good idea to include in the docs as well.
> 
> Would you like to add a test/sample code? Or we can leave #130754 open for now and add those in another PR. Let me know how you would like to move forward.

In that case, let's leave it for another PR. But what kind of test do you want for #130754? Isn't the test added in this PR enough?

> Also - a rebase with head should clear that flutter_plugins check. :)

Done. @Piinks

**Comment by Piinks** [comment]
> Isn't the test added in this PR enough?

The test here does not validate a stateful widget being reordered in the viewport and having its state maintained before and after reordering. The children in test are SizedBoxes.
But if we are covering that in a separate change, let's do that then! :)

**Review by Piinks — APPROVED** [review]
This change LGTM for resolving #141101! Thank you!

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal
