### PR TITLE
Fix that `flutter test` does not understand `concurrency`

### LINKED ISSUE #125940: `flutter test` does not understand `concurrency`
Possible fix: Mimic https://github.com/flutter/flutter/pull/115160

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

`flutter test`

### Expected results

Tests should be executed one-by-one, since we specify concurrency=1 in dart_test.yaml

### Actual results

They are executed parallelly.

<details>

```
flutter test
00:02 +0: /Users/tom/RefCode/bug/test/c_test.dart: hello this is test                                                                         
c_test is running (i=0)
00:02 +0: /Users/tom/RefCode/bug/test/b_test.dart: hello this is test                                                                         
b_test is running (i=0)
00:02 +0: /Users/tom/RefCode/bug/test/a_test.dart: hello this is test                                                                         
a_test is running (i=0)
00:03 +0: /Users/tom/RefCode/bug/test/c_test.dart: hello this is test                                                                         
c_test is running (i=1)
00:03 +0: /Users/tom/RefCode/bug/test/b_test.dart: hello this is test                                                                         
b_test is running (i=1)
00:03 +0: /Users/tom/RefCode/bug/test/a_test.dart: hello this is test                                                                         
a_test is running (i=1)
00:03 +0: /Users/tom/RefCode/bug/test/c_test.dart: hello this is test                                                                         
c_test is running (i=2)
00:03 +0: /Users/tom/RefCode/bug/test/b_test.dart: hello this is test                                                                         
b_test is running (i=2)
00:03 +0: /Users/tom/RefCode/bug/test/a_test.dart: hello this is test                                                                         
a_test is running (i=2)
00:04 +0: /Users/tom/RefCode/bug/test/c_test.dart: hello this is test                                                                         
c_test is running (i=3)
00:04 +0: /Users/tom/RefCode/bug/test/b_test.dart: hello this is test                                                                         
b_test is running (i=3)
00:04 +0: /Users/tom/RefCode/bug/test/a_test.dart: hello this is test                                                                         
a_test is running (i=3)
00:04 +0: /Users/tom/RefCode/bug/test/c_test.dart: hello this is test                                                                         
c_test is running (i=4)
00:04 +0: /Users/tom/RefCode/bug/test/b_test.dart: hello this is test                                                                         
b_test is running (i=4)
00:04 +0: /Users/tom/RefCode/bug/test/a_test.dart: hello this is test                                                                         
a_test is running (i=4)
00:05 +0: /Users/tom/RefCode/bug/test/c_test.dart: hello this is test                                                                         
c_test is running (i=5)
00:05 +0: /Users/tom/RefCode/bug/test/b_test.dart: hello this is test                                                                         
b_test is running (i=5)
00:05 +0: /Users/tom/RefCode/bug/test/a_test.dart: hello this is test                                                                         
a_test is running (i=5)
00:05 +0: /Users/tom/RefCode/bug/test/c_test.dart: hello this is test                                                                         
c_test is running (i=6)
00:05 +0: /Users/tom/RefCode/bug/test/b_test.dart: hello this is test                                                                         
b_test is running (i=6)
00:05 +0: /Users/tom/RefCode/bug/test/a_test.dart: hello this is test                                                                         
a_test is running (i=6)
00:06 +0: /Users/tom/RefCode/bug/test/c_test.dart: hello this is test                                                                         
c_test is running (i=7)
00:06 +0: /Users/tom/RefCode/bug/test/b_test.dart: hello this is test                                                                         
b_test is running (i=7)
00:06 +0: /Users/tom/RefCode/bug/test/a_test.dart: hello this is test                                                                         
a_test is running (i=7)
00:06 +0: /Users/tom/RefCode/bug/test/c_test.dart: hello this is test                                                                         
c_test is running (i=8)
00:06 +0: /Users/tom/RefCode/bug/test/b_test.dart: hello this is test                                                                         
b_test is running (i=8)
00:06 +0: /Users/tom/RefCode/bug/test/a_test.dart: hello this is test                                                                         
a_test is running (i=8)
00:07 +0: /Users/tom/RefCode/bug/test/c_test.dart: hello this is test                                                                         
c_test is running (i=9)
00:07 +0: /Users/tom/RefCode/bug/test/b_test.dart: hello this is test                                                                         
b_test is running (i=9)
00:07 +0: /Users/tom/RefCode/bug/test/a_test.dart: hello this is test                                                                         
a_test is running (i=9)
00:07 +3: All tests passed!
```

</details>

### Code sample

<details><summary>Code sample</summary>

dart_test.yaml

```
concurrency: 1
```

test/a_test.dart

```dart
import 'dart:io';
import 'package:flutter_test/flutter_test.dart';
void main() {
  test('hello this is test', () {
    for (var i = 0; i < 10; ++i) {
      print('a_test is running (i=$i)');
      sleep(const Duration(milliseconds: 500));
    }
  });
}
```

test/b_test.dart

same, just change the name in "print", i.e.

```
import 'dart:io';
import 'package:flutter_test/flutter_test.dart';
void main() {
  test('hello this is test', () {
    for (var i = 0; i < 10; ++i) {
      print('b_test is running (i=$i)');
      sleep(const Duration(milliseconds: 500));
    }
  });
}
```

test/c_test.dart

similar to b_test.dart

```
import 'dart:io';
import 'package:flutter_test/flutter_test.dart';
void main() {
  test('hello this is test', () {
    for (var i = 0; i < 10; ++i) {
      print('c_test is running (i=$i)');
      sleep(const Duration(milliseconds: 500));
    }
  });
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by fzyzcjy**
Close https://github.com/flutter/flutter/issues/125940

I will add tests if this PR looks roughly OK :)

The fix mainly mimics https://github.com/flutter/flutter/pull/115160 - just remove the default argument.

p.s. I ran into this bug when wanting to set concurrency in my dart_test.yaml for one set of my tests which I need to be executed without parallalization.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
Awesome, this approach looks good to me. If you add tests, we will review it next week.

**Comment by fzyzcjy** [comment]
Sure! I will add tests (in batch with my other PRs) as soon as possible when having time

**Comment by fzyzcjy** [comment]
Tests added (mimicking #115160)

**Comment by christopherfujino** [comment]
@eliasyishak can you review this one?

**Comment by eliasyishak** [comment]
> @eliasyishak can you review this one?

Yep I'll take a look!

File: packages/flutter_tools/lib/src/commands/test.dart [hunk 1]
```diff
@@ -146,7 +144,6 @@ class TestCommand extends FlutterCommand with DeviceBasedDevelopmentArtifacts {
       )
       ..addOption('concurrency',
         abbr: 'j',
-        defaultsTo: math.max<int>(1, globals.platform.numberOfProcessors - 2).toString(),
```
Comment (eliasyishak) [inline packages/flutter_tools/lib/src/commands/test.dart:149]: Although we are not setting the default value for concurrency in Flutter, we are eventually calling `dart test` which does have a default set for concurrency. As you can see here https://pub.dev/packages/test#test-concurrency, the default is going to be half of the host's CPU cores. ie. for me I have 10, so flutter would have defaulted to 8 while dart defaulted to 5.

So instead of removing the default help text, we should pass the default from dart.

This will prevent people from thinking that they are running on one thread when in reality it is likely running on a few.

Comment (eliasyishak) [reply packages/flutter_tools/lib/src/commands/test.dart:149]: Actually, I'm not 100% sure what I said above is correct, @christopherfujino, do you know if we are passing the args from the flutter command to `dart test` and using the dart defaults for test? Or do we have our own implementation that doesn't use the defaults?

Comment (fzyzcjy) [reply packages/flutter_tools/lib/src/commands/test.dart:149]: Hmm, then how can we read data from dart_test.yaml? If we are passing a value like `dart test --concurrency sth`, dart test will ignore it, and thus the bug still occurs

Comment (eliasyishak) [reply packages/flutter_tools/lib/src/commands/test.dart:149]: Perfect, thanks for the pointer @christopherfujino, this is the snippet from the last link above

```dart
  /// How many tests to run concurrently.
  int get concurrency =>
      pauseAfterLoad ? 1 : (_concurrency ?? defaultConcurrency);
```

And the ultimate fall back value is going to be stored in `defaultConcurrency` which is calculated in this file https://github.com/dart-lang/test/blob/master/pkgs/test_core/lib/src/runner/configuration/values.dart#L10-L14

```dart
/// The default number of test suites to run at once.
///
/// This defaults to half the available processors, since presumably some of
/// them will be used for the OS and other processes.
final defaultConcurrency = math.max(1, Platform.numberOfProcessors ~/ 2);
```

So @fzyzcjy, instead of removing the `defaultsTo` parameter, we should probably reference that value using flutter's globals to get the number of processors. Without this, developers may assume they are running on one worker when that may not be the case

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/test.dart:149]: > So @fzyzcjy, instead of removing the defaultsTo parameter, we should probably reference that value using flutter's globals to get the number of processors. Without this, developers may assume they are running on one worker when that may not be the case

Not sure what you mean. What does "reference that value using flutter's globals" mean? Are we talking about the help text or `defaultsTo` value?

Comment (eliasyishak) [reply packages/flutter_tools/lib/src/commands/test.dart:149]: I was referring to the defaultsTo value that gets printed along with the help text when you run `flutter test --help`. I'm suggesting that we keep the changes made in this PR but for the defaultsTo value, we should refer to the default value that dart uses, which is half of the number of processors on the developer's machine

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/test.dart:149]: I only skimmed this change, maybe I'm misunderstanding, but I thought the fix here was to remove `defaultsTo` and let package:test figure it out on its own, so that it will respect `dart_test.yaml`.

Comment (eliasyishak) [reply packages/flutter_tools/lib/src/commands/test.dart:149]: Yes, that is correct, and @fzyzcjy PR fixes that issue.

My only concern is that flutter users may not know that under the hood `package:test` also has a default value for concurrency that will be applied if the flutter developer does not supply a value for concurrency.

For example, if the user runs `flutter test` in their app without specifying concurrent workers, they may be thinking that it will only run on one worker, when in reality `package:test` is doing something else.

This may not be an issue but I thought giving that information in the help text would be helpful

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/test.dart:149]: But if we provide a `defaultsTo` value, then how would package:test ever look up dart_test.yaml? It will see that it's always being passed an explicit argument.

Comment (eliasyishak) [reply packages/flutter_tools/lib/src/commands/test.dart:149]: Ah this is my mistake, I forgot that `defaultsTo` will actually pass a value. Sorry for the confusion!

This should be okay then because we will end up with the same bug. I was really just trying to document that there will likely be more than one worker running for `flutter test`

**Review by eliasyishak — APPROVED** [review]
LGTM, thank you for contribution! 😄

**Review by christopherfujino — APPROVED** [review]
LGTM
