### PR TITLE
resolved the issue of indeterminate CircularProgressIndicator.adaptive on Darwin 

### LINKED ISSUE #140574: CircularProgressIndicator.adaptive is always indeterminate on Darwin
## Steps to reproduce

Run the following app on macOS or iOS:

```dart
class IssueApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Center(
        child: CircularProgressIndicator.adaptive(
          value: 0.5,
        ),
      ),
    );
  }
}
```

## Expected behavior

You expect to see  a partially revealed Cupertino activity indicator.

## Actual behavior

You see an indeterminate (continually animated) Cupertino activity indicator

## Analysis

The adaptive progress indicator is coded to always use the default `CupertinoActivityIndicator` constructor, which is always indeterminate:

https://github.com/flutter/flutter/blob/02d1d64e7f5fdb239ad865705a93c381159d49c1/packages/flutter/lib/src/material/progress_indicator.dart#L708

### PR DESCRIPTION
**Pull request by nikkivirtuoso**
Fixes #140574

Passes the value from `CircularProgressIndicator` to the Cupertino version so that functionality is not lost on Apple devices.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by nikkivirtuoso** [comment]
please review my code

File: packages/flutter/lib/src/material/progress_indicator.dart [hunk 1]
```diff
@@ -705,7 +705,14 @@ class _CircularProgressIndicatorState extends State<CircularProgressIndicator> w
...
     final Color? tickColor = widget.backgroundColor;
-    return CupertinoActivityIndicator(key: widget.key, color: tickColor);
+    final double? val = widget.value;
+
+    if (val == null) {
+      return CupertinoActivityIndicator(key: widget.key, color: tickColor);
+    }
+
+    return CupertinoActivityIndicator.partiallyRevealed(
+        key: widget.key, color: tickColor, progress: val);
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/material/progress_indicator.dart:715]: Formatting nit: move each property to a new line since this line is already long:
```
return CupertinoActivityIndicator.partiallyRevealed(
     key: widget.key,
     color: tickColor,
     progress: val
);
```

**Review by MitchellGoodwin — COMMENTED** [review]
Code looks good to me, with a small nit. This will need a test however. Probably one that gives a `CircularProgressIndicator.adaptive` a value, then checks to see if a `CupertinoActivityIndicator` is rendered with the expected value.

**Comment by nikkivirtuoso** [comment]
@MitchellGoodwin, sir please check now i have made the necessary changes and all test cases have passed

File: packages/flutter/lib/src/material/progress_indicator.dart [hunk 2]
```diff
@@ -705,7 +705,20 @@ class _CircularProgressIndicatorState extends State<CircularProgressIndicator> w
...
+
+    if (val == null) {
+      return CupertinoActivityIndicator(
+        key: widget.key,
+        color: tickColor
+      );
+    }
+
+    return CupertinoActivityIndicator.partiallyRevealed(
+        key: widget.key,
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/material/progress_indicator.dart:718]: Nit: this has an extra indent that should be removed.

**Comment by MitchellGoodwin** [comment]
Per our policy on test coverage, this change still needs a test added to it. Could you please add one? It just needs to check if `CircularProgressIndicator.adaptive` with a value renders a CupertinoActivityIndicator with that same value.

**Comment by nikkivirtuoso** [comment]
yes i will add the test guide me

**Comment by nikkivirtuoso** [comment]
i have tried a code for testing here it is:
`import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('CircularProgressIndicator.adaptive test', (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: const Centre(
          child: CircularProgressIndicator.adaptive(
            value: 0.5, 
          ),
        ),
      ),
    );

    expect(find.byType(CupertinoActivityIndicator), findsOneWidget);

 
    expect(
      find.byType(CupertinoActivityIndicator).evaluate().first.widget.value,
      0.5,
    );
  });
}`

**Comment by MitchellGoodwin** [comment]
The test should be added in `/packages/flutter/test/material/progress_indicator_test.dart`. You can find a basic adaptive test on line 1065. What's important is the `variant` argument near the end. That will make the test only run on Apple platforms so the adaptive version goes to the Cupertino progress indicator. I believe the rest of your code will work.

**Comment by nikkivirtuoso** [comment]
@MitchellGoodwin, sir i have updated the test case as at first it was unable to extract the value hence i have taken the return type so that it don't get lost and all test cases have been passed, please review my code

**Comment by nikkivirtuoso** [comment]
Sir, please have a look

File: packages/flutter/lib/src/material/progress_indicator.dart [hunk 3]
```diff
@@ -705,7 +705,18 @@ class _CircularProgressIndicatorState extends State<CircularProgressIndicator> w
...
+    if (val == null) {
+      return CupertinoActivityIndicator(
+        key: widget.key,
+        color: tickColor
+      );
+    }
+    return CupertinoActivityIndicator.partiallyRevealed(
+        key: widget.key,
+      color: tickColor,
+      progress: val
```
Comment (MitchellGoodwin) [inline packages/flutter/lib/src/material/progress_indicator.dart:718]:
```suggestion
      key: widget.key,
      color: tickColor,
      progress: val
```

File: packages/flutter/test/material/progress_indicator_test.dart [hunk 4]
```diff
@@ -1070,13 +1070,20 @@ void main() {
...
           ),
         ),
       );
 
       expect(find.byType(CupertinoActivityIndicator), findsOneWidget);
+      expect(
+        tester.widget<CircularProgressIndicator>(
+          find.byType(CircularProgressIndicator)).value,
+          0.5,
+        );
```
Comment (MitchellGoodwin) [inline packages/flutter/test/material/progress_indicator_test.dart:1086]: This test should be left alone. Instead, it would be better to add a new one. So you can copy the existing test as it was and put it below, then change it to look for the adaptive value logic. This makes it so that if either test fails in the future it will be easier to see what logic is broken.

Also, it would be better to try and get the value of `progress` of `CupertinoActivityIndicator` to check that the adaptive logic is working.

Comment (nikkivirtuoso) [reply packages/flutter/test/material/progress_indicator_test.dart:1086]: Sir i got the first part, but i am confused with the last part, you are saying that it should test on the value provided by the user not the default value that i have set to 0.5, am I right ?

Comment (MitchellGoodwin) [reply packages/flutter/test/material/progress_indicator_test.dart:1086]: You should test that if `CircularProgressIndicator.adaptive` is given a `value` of something, in this case 0.5, then a `CupertinoActivityIndicator` is rendered with a `progress` of 0.5.

**Comment by nikkivirtuoso** [comment]
sir please have a look on my code i dont know what have i done wrong

**Comment by MitchellGoodwin** [comment]
I don't think it's an issue with this PR. It looks like it's a problem with versioning introduced from another commit. https://github.com/flutter/flutter/issues/141032
Other PRs appear to be failing for the same reason. So it would probably be best to wait for the tree to be green, then rebase or merge the changes from master.

**Comment by nikkivirtuoso** [comment]
@MitchellGoodwin , sir can your review the changes and tell me whether there is still need to change in code or not

**Comment by nikkivirtuoso** [comment]
sir app test cases have been passed please have a look

**Comment by nikkivirtuoso** [comment]
@MitchellGoodwin Sir please review my code

**Comment by nikkivirtuoso** [comment]
@MitchellGoodwin sir please review my code

File: packages/flutter/test/material/progress_indicator_test.dart [hunk 5]
```diff
@@ -1077,13 +1077,39 @@ void main() {
...
+      final double actualProgress =tester.widget<CupertinoActivityIndicator>(
+        find.byType(CupertinoActivityIndicator)).progress;
+      expect(actualProgress, 0.5);
+      },
+      variant: const TargetPlatformVariant(<TargetPlatform> {
       TargetPlatform.iOS,
       TargetPlatform.macOS,
     }),
   );
-
```
Comment (MitchellGoodwin) [inline packages/flutter/test/material/progress_indicator_test.dart:1086]: Leave a line in between tests

File: packages/flutter/test/material/progress_indicator_test.dart [hunk 6]
```diff
@@ -1077,13 +1077,39 @@ void main() {
...
+          ),
+        ),
+      );
+
+      expect(find.byType(CupertinoActivityIndicator), findsOneWidget);
+      final double actualProgress =tester.widget<CupertinoActivityIndicator>(
+        find.byType(CupertinoActivityIndicator)).progress;
+      expect(actualProgress, 0.5);
+      },
+      variant: const TargetPlatformVariant(<TargetPlatform> {
```
Comment (MitchellGoodwin) [inline packages/flutter/test/material/progress_indicator_test.dart:1108]:
```suggestion
      expect(actualProgress, 0.5);
   },
   variant: const TargetPlatformVariant(<TargetPlatform> {
```
Formatting nit, tab these two lines to the left

**Review by MitchellGoodwin — COMMENTED** [review]
Code looks good to me. Thank you for righting the test. I just have some formatting nits.

**Comment by MitchellGoodwin** [comment]
I updated the PR description with a link to the original issue, and put the checklist. I checked off what I could see was done. Check the top three if you've read those resources. If not, I would encourage you to look over them. This PR does not need documentation, so that can be left blank.

**Comment by nikkivirtuoso** [comment]
Yes sir, I have checked the top three resources, and i have read them, now i have understood the significance of trailing spaces, Thankyou Sir.

**Comment by nikkivirtuoso** [comment]
Sir, any suggestions for me its my first PR which is going to merge and i haven't entered the software industry yet i am trying to get a job

**Comment by nikkivirtuoso** [comment]
Sir, please review my code

**Comment by MitchellGoodwin** [comment]
I have two outstanding nits. Address those and this will be done, I think.

File: packages/flutter/test/material/progress_indicator_test.dart (hunk 5 above)
Comment (nikkivirtuoso) [reply packages/flutter/test/material/progress_indicator_test.dart:1086]: sir if i leave a line here then this leads to fail in linux analyze test

Comment (MitchellGoodwin) [reply packages/flutter/test/material/progress_indicator_test.dart:1086]: Trailing space normally means that there's an extra space within the line. So if I am able to do this:
Screenshot 2024-01-08 at 11 14 41 AM
and have my cursor be anywhere other than than the far left edge of an empty line, it will throw a linting error, which I'm not sure if that will show on Github. See if there's some white space on line 1113 and delete it, while leaving the empty line there.

Comment (nikkivirtuoso) [reply packages/flutter/test/material/progress_indicator_test.dart:1086]: @MitchellGoodwin sir, the linux analyze test case has been passed but now another test case i.e.Mac build_tests_2_4 has failed, when i go into the details there were some absence of example directory can you help me please ?

Comment (nikkivirtuoso) [reply packages/flutter/test/material/progress_indicator_test.dart:1086]: @MitchellGoodwin sir, suddenly the number of failed test cases has increased, is there any fault in this PR ?

Comment (MitchellGoodwin) [reply packages/flutter/test/material/progress_indicator_test.dart:1086]: I do not believe so. Looks like other PRs are failing similar tests.

Comment (nikkivirtuoso) [reply packages/flutter/test/material/progress_indicator_test.dart:1086]: Okay Sir

**Comment by jmagman** [comment]
> sir please review my code

@nikkivirtuoso thank you so much for your contribution!  But please refrain from pinging your PR, @MitchellGoodwin is in the process of reviewing it and has many things to do, in addition to reviewing this.  Our [contribution guide](https://github.com/flutter/flutter/wiki/Tree-hygiene#getting-a-code-review) says:
> If nobody has reviewed your code after a week, then reach out on our [Chat](https://github.com/flutter/flutter/wiki/Chat) channels. The #hackers-new channel is a good place to ask for help if you're a new contributor.

So if it's been more than a week, please reach out!  Thanks again!

**Review by MitchellGoodwin — APPROVED** [review]
LGTM. Thank you for responding to all my feedback. The next step is to get a second approval. I'll ask around to see if I can get someone to take a look.

File: packages/flutter/lib/src/material/progress_indicator.dart [hunk 7]
```diff
@@ -705,7 +705,18 @@ class _CircularProgressIndicatorState extends State<CircularProgressIndicator> w
 
   Widget _buildCupertinoIndicator(BuildContext context) {
     final Color? tickColor = widget.backgroundColor;
-    return CupertinoActivityIndicator(key: widget.key, color: tickColor);
+    final double? val = widget.value;
```
Comment (justinmc) [inline packages/flutter/lib/src/material/progress_indicator.dart:708]: `val` should be `value` per the styleguide: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-abbreviations

Or just use the full `widget.value` directly.

File: packages/flutter/test/material/progress_indicator_test.dart [hunk 8]
```diff
@@ -1084,6 +1084,33 @@ void main() {
...
+  testWidgets(
+    'Adaptive CircularProgressIndicator displays CupertinoActivityIndicator in iOS',
+    (WidgetTester tester) async {
+      await tester.pumpWidget(
+        MaterialApp(
+          theme: ThemeData(),
+          home: const Scaffold(
+            body: Material(
+              child: CircularProgressIndicator.adaptive(
+                value:0.5,
```
Comment (justinmc) [inline packages/flutter/test/material/progress_indicator_test.dart:1096]: Space after the colon here.

File: packages/flutter/test/material/progress_indicator_test.dart [hunk 9]
```diff
@@ -1084,6 +1084,33 @@ void main() {
     }),
   );
 
+  testWidgets(
+    'Adaptive CircularProgressIndicator displays CupertinoActivityIndicator in iOS',
```
Comment (QuncCccccc) [inline packages/flutter/test/material/progress_indicator_test.dart:1088]: nit: 
```suggestion
    'Adaptive CircularProgressIndicator displays CupertinoActivityIndicator in iOS/macOS',
```

**Review by QuncCccccc — APPROVED** [review]
LGTM with some nits. Thanks a lot for the contribution:)!

File: packages/flutter/test/material/progress_indicator_test.dart [hunk 10]
```diff
@@ -1084,6 +1084,33 @@ void main() {
...
+                value:0.5,
+              ),
+            ),
+          ),
+        ),
+      );
+
+      expect(find.byType(CupertinoActivityIndicator), findsOneWidget);
+      final double actualProgress =tester.widget<CupertinoActivityIndicator>(
+        find.byType(CupertinoActivityIndicator)).progress;
```
Comment (justinmc) [inline packages/flutter/test/material/progress_indicator_test.dart:1105]:
```dart
      final double actualProgress = tester.widget<CupertinoActivityIndicator>(
        find.byType(CupertinoActivityIndicator),
      ).progress;
```

**Review by justinmc — APPROVED** [review]
Thanks for fixing this bug!  LGTM with some small style changes below.

**Comment by nikkivirtuoso** [comment]
> > sir please review my code
> 
> @nikkivirtuoso thank you so much for your contribution! But please refrain from pinging your PR, @MitchellGoodwin is in the process of reviewing it and has many things to do, in addition to reviewing this. Our [contribution guide](https://github.com/flutter/flutter/wiki/Tree-hygiene#getting-a-code-review) says:
> 
> > If nobody has reviewed your code after a week, then reach out on our [Chat](https://github.com/flutter/flutter/wiki/Chat) channels. The #hackers-new channel is a good place to ask for help if you're a new contributor.
> 
> So if it's been more than a week, please reach out! Thanks again!

Thank you for the guidance! I appreciate your consideration and will refrain from further pings. I'll patiently wait for the review and, if needed, will follow up after a week. Thanks for your time and support!
