### PR TITLE
fix a DragTarget type cast bug

### LINKED ISSUE #72483: DragTarget<dynamic> does not accept int/String, Draggable fails
## Steps to Reproduce

1. Run `flutter create bug`.
2. Run `cd bug`.
2. Update the file `lib/main.dart` as follows:
    ```dart
    import 'dart:math';
    import 'package:flutter/material.dart';

    void main() {
      runApp(DraggableIssue());
    }

    class DraggableIssue extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        int intFail = 5;
        dynamic dynamicSuccess = 5;
        return MaterialApp(
          home: Column(
            children: [
              DragTarget<int>(
                onWillAccept: (int data) => true,
                builder: (context, candidateData, rejectedData) {
                  return Text('y ' +
                      candidateData.length.toString() +
                      ' n ' +
                      rejectedData.length.toString());
                },
              ),
              DragTarget<dynamic>(
                onWillAccept: (dynamic data) => true,
                builder: (context, candidateData, rejectedData) {
                  return Text('y ' +
                      candidateData.length.toString() +
                      ' n ' +
                      rejectedData.length.toString());
                },
              ),
              Draggable<dynamic>(
                feedback: Text('dragging'),
                data: dynamicSuccess,
                child: Text('dynamic'),
              ),
              Draggable<int>(
                feedback: Text('dragging'),
                data: intFail,
                child: Text('int'),
              ),
            ],
          ),
        );
      }
    }
    ```
2. Run `flutter run -d linux` (platform shouldn't matter here).
3. Drag the text "dynamic" over the numbers.
4. Drag the text "int" over the numbers.

**Expected results:** The two draggables should be accepted by both drag targets.

**Actual results:** The "dynamic" draggable gets rejected by the DragTarget&lt;int&gt; widget and, more importantly, the "int" draggable is completely ignored by the DragTarget&lt;dynamic&gt; widget. Same happens for String instead of int.

<details>
  <summary>Logs</summary>

```
[  +94 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +45 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 63062a64432cce03315d6b5196fda7912866eb37
[   +4 ms] executing: [/opt/flutter/] git tag --points-at 63062a64432cce03315d6b5196fda7912866eb37
[  +16 ms] Exit code 0 from: git tag --points-at 63062a64432cce03315d6b5196fda7912866eb37
[        ] 1.26.0-1.0.pre
[  +50 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +59 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +75 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +90 ms] executing: /opt/android-sdk/platform-tools/adb devices -l
[  +58 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +107 ms] Skipping pub get: version match.
[ +125 ms] Found plugin integration_test at /opt/flutter/packages/integration_test/
[ +147 ms] Found plugin integration_test at /opt/flutter/packages/integration_test/
[   +6 ms] Generating /tmp/a/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +128 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[   +4 ms] complete
[   +6 ms] Launching lib/main.dart on Linux in debug mode...
[   +6 ms] /opt/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /opt/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.JGZPLW/flutter_tool.ZAGLLL/app.dill --packages /tmp/a/bug/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +15 ms] Building Linux application...
[  +25 ms] <- compile package:bug/main.dart
[   +3 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /tmp/a/bug/linux
[  +46 ms] -- Configuring done
[   +6 ms] -- Generating done
[  +11 ms] -- Build files have been written to: /tmp/a/bug/build/linux/debug
[   +5 ms] executing: ninja -C build/linux/debug install
[  +18 ms] ninja: Entering directory `build/linux/debug'
[+5899 ms] [1/5] Generating /tmp/a/bug/linux/flutter/ephemeral/libflutter_linux_gtk.so, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_value.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/fl_view.h, /tmp/a/bug/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +11 ms] [ +133 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +71 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 63062a64432cce03315d6b5196fda7912866eb37
[        ] [   +1 ms] executing: [/opt/flutter/] git tag --points-at 63062a64432cce03315d6b5196fda7912866eb37
[   +1 ms] [  +29 ms] Exit code 0 from: git tag --points-at 63062a64432cce03315d6b5196fda7912866eb37
[        ] [        ] 1.26.0-1.0.pre
[        ] [  +70 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/dev
[   +1 ms] [        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[        ] [   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [ +107 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] dev
[   +1 ms] [  +89 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +91 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [ +138 ms] Initializing file store
[        ] [  +11 ms] Done initializing file store
[        ] [  +49 ms] Skipping target: gen_localizations
[   +1 ms] [+3028 ms] Skipping target: unpack_linux
[        ] [ +563 ms] Skipping target: kernel_snapshot
[        ] [ +407 ms] Skipping target: debug_bundle_linux_assets
[        ] [   +1 ms] Persisting file store
[        ] [  +12 ms] Done persisting file store
[   +1 ms] [   +6 ms] build succeeded.
[        ] [  +13 ms] "flutter assemble" took 4,351ms.
[        ] [  +32 ms] ensureAnalyticsSent: 26ms
[        ] [   +2 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +2 ms] exiting with code 0
[+1375 ms] [2/5] Building CXX object CMakeFiles/bug.dir/flutter/generated_plugin_registrant.cc.o
[ +352 ms] [3/5] Building CXX object CMakeFiles/bug.dir/my_application.cc.o
[ +266 ms] [4/5] Linking CXX executable intermediates_do_not_run/bug
[        ] [4/5] Install the project...
[  +11 ms] -- Install configuration: "Debug"
[  +33 ms] -- Installing: /tmp/a/bug/build/linux/debug/bundle/bug
[        ] -- Set runtime path of "/tmp/a/bug/build/linux/debug/bundle/bug" to "$ORIGIN/lib"
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/icudtl.dat
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/lib/libflutter_linux_gtk.so
[ +107 ms] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/flutter_assets
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/flutter_assets/NOTICES
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /tmp/a/bug/build/linux/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +51 ms] Building Linux application... (completed in 8.2s)
[ +327 ms] Observatory URL on device: http://127.0.0.1:46685/fjuDjpNeFg8=/
[+3403 ms] Caching compiled dill
[  +29 ms] Connecting to service protocol: http://127.0.0.1:46685/fjuDjpNeFg8=/
[   +3 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:46685/fjuDjpNeFg8=/.
[ +316 ms] DDS is listening at http://127.0.0.1:43533/yMokt44rJWE=/.
[  +93 ms] Successfully connected to service protocol: http://127.0.0.1:46685/fjuDjpNeFg8=/
[  +19 ms] DevFS: Creating new filesystem on the device (null)
[  +27 ms] DevFS: Created new filesystem on the device (file:///tmp/bugVFIKMW/bug/)
[   +4 ms] Updating assets
[ +170 ms] Syncing files to device Linux...
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:bug/main.dart 206a2164-d44d-4488-baae-9e0b7f56ff9a
[        ] <- 206a2164-d44d-4488-baae-9e0b7f56ff9a
[ +153 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Linux... (completed in 160ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +8 ms] Connected to _flutterView/0x55dea090dd20.
[   +1 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:43533/yMokt44rJWE=/
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+5262 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +6 ms] DevFS: Deleting filesystem on the device (file:///tmp/bugVFIKMW/bug/)
[ +253 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +2 ms] "flutter run" took 19,108ms.
[  +11 ms] ensureAnalyticsSent: 8ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 0
```

```
Analyzing bug...

   info • Unused import: 'dart:math' • lib/main.dart:1:8 • unused_import
   info • Unused import: 'package:bug/main.dart' • test/widget_test.dart:11:8 • unused_import
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function

3 issues found. (ran in 9.0s)
```

```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-1.0.pre at /opt/flutter
    • Framework revision 63062a6443 (3 days ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /opt/android-sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /home/adabru/work/armin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.0.0
    • cmake version 3.19.1
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 3.6)
    • Android Studio at /home/adabru/work/armin/android-studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

This patch fixes the following cases:
1, `DragTarget<Object>` should accept `Draggable<int>` data
2, `DragTarget<int>` should accept `Draggable<Object>` data when the data runtime type is `int`

## Related Issues

Fixes #72483

## Tests

I added the following tests:

See files.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 1]
```diff
@@ -644,18 +644,19 @@ class DragTarget<T extends Object> extends StatefulWidget {
...
-  final List<_DragAvatar<T>> _candidateAvatars = <_DragAvatar<T>>[];
+  final List<_DragAvatar<Object>> _candidateAvatars = <_DragAvatar<Object>>[];
   final List<_DragAvatar<Object>> _rejectedAvatars = <_DragAvatar<Object>>[];
 
   bool didEnter(_DragAvatar<Object> avatar) {
     assert(!_candidateAvatars.contains(avatar));
     assert(!_rejectedAvatars.contains(avatar));
-    if (avatar is _DragAvatar<T> && (widget.onWillAccept == null || widget.onWillAccept!(avatar.data))) {
+    if ((avatar.data == null || avatar.data is T)
+        && (widget.onWillAccept == null || widget.onWillAccept!(avatar.data as T?))) {
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/drag_target.dart:659]: This fixes:
DragTarget<int>` should accept `Draggable<Object>` data(runtime is `int`)

Before this change,  `avatar` runtime is `_DragAvatar<Object>` which is not a subtype of `_DragAvatar<int>`, cause not be accepted

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 2]
```diff
@@ -821,21 +822,21 @@ class _DragAvatar<T extends Object> extends Drag {
...
-  Iterable<_DragTargetState<T>> _getDragTargets(Iterable<HitTestEntry> path) sync* {
+  Iterable<_DragTargetState<Object>> _getDragTargets(Iterable<HitTestEntry> path) sync* {
     // Look for the RenderBoxes that corresponds to the hit target (the hit target
     // widgets build RenderMetaData boxes for us for this purpose).
     for (final HitTestEntry entry in path) {
       final HitTestTarget target = entry.target;
       if (target is RenderMetaData) {
         final dynamic metaData = target.metaData;
-        if (metaData is _DragTargetState<T>)
+        if (metaData is _DragTargetState)
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/drag_target.dart:839]: This fixes:
`DragTarget<Object>` should accept `Draggable<int>` data

Before this change,  `metaData ` runtime is `_DragTargetState<Object>` which is not a subtype of `_DragTargetState<int>`, cause not be accepted

**Comment by xu-baolin** [comment]
@shihaohong Hi
Could you help me figure out what causes the web_test to fail?
It seems to relate the dart to js that I am not good at.

**Comment by xu-baolin** [comment]
For web:
The `int(1)` will treat as `double`, so `if ((avatar.data == null || avatar.data is T)` cause `_DragTargetState<Double>` accept `Draggable<int>`

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 3]
```diff
@@ -644,18 +645,30 @@ class DragTarget<T extends Object> extends StatefulWidget {
...
+        return data is T?;
+      }
+    }
+  }
+
   bool didEnter(_DragAvatar<Object> avatar) {
     assert(!_candidateAvatars.contains(avatar));
     assert(!_rejectedAvatars.contains(avatar));
-    if (avatar is _DragAvatar<T> && (widget.onWillAccept == null || widget.onWillAccept!(avatar.data))) {
+    if (widget.onWillAccept == null || widget.onWillAccept!(avatar.data as T?)) {
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/drag_target.dart:671]: `_getDragTargets` already checked the data type.

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 4]
```diff
@@ -644,18 +645,30 @@ class DragTarget<T extends Object> extends StatefulWidget {
...
 class _DragTargetState<T extends Object> extends State<DragTarget<T>> {
-  final List<_DragAvatar<T>> _candidateAvatars = <_DragAvatar<T>>[];
+  final List<_DragAvatar<Object>> _candidateAvatars = <_DragAvatar<Object>>[];
   final List<_DragAvatar<Object>> _rejectedAvatars = <_DragAvatar<Object>>[];
 
+  bool _checkDataType(Object? data, Type type) {
+    if (!kIsWeb) {
+      return data is T?;
+    } else {
+      if ((type == int && T == double) || (type == double && T == int)) {
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/drag_target.dart:660]: We must use the `type` that passed in, can not use `data.runtimeType` because `int` and `double` are `int` runtime type on WEB.

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 5]
```diff
@@ -644,18 +645,30 @@ class DragTarget<T extends Object> extends StatefulWidget {
...
+List<T?> _mapAvatarsToData<T extends Object>(List<_DragAvatar<Object>> avatars) {
+  return avatars.map<T?>((_DragAvatar<Object> avatar) => avatar.data as T?).toList();
 }
 
 class _DragTargetState<T extends Object> extends State<DragTarget<T>> {
-  final List<_DragAvatar<T>> _candidateAvatars = <_DragAvatar<T>>[];
+  final List<_DragAvatar<Object>> _candidateAvatars = <_DragAvatar<Object>>[];
   final List<_DragAvatar<Object>> _rejectedAvatars = <_DragAvatar<Object>>[];
 
+  bool checkDataType(Object? data, Type type) {
```
Comment (shihaohong) [inline packages/flutter/lib/src/widgets/drag_target.dart:656]: Add documentation here on what `checkDataType` accomplishes. I would note that:
1. On non-web platforms, checks if `data` Object is equal to `type`.
2. On web, it does the same, but requires a check for ints and doubles because `runtimeType` on the web since numbers are treated as doubles on web.

Comment (shihaohong) [reply packages/flutter/lib/src/widgets/drag_target.dart:656]: I would also describe why this logic is necessary, since it might not be obvious without the context of the issue that made this PR necessary.

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 6]
```diff
@@ -644,18 +645,30 @@ class DragTarget<T extends Object> extends StatefulWidget {
...
+    if (!kIsWeb) {
+      return data is T?;
+    } else {
+      if ((type == int && T == double) || (type == double && T == int)) {
+        return false;
+      } else {
+        return data is T?;
+      }
+    }
```
Comment (shihaohong) [inline packages/flutter/lib/src/widgets/drag_target.dart:665]: Maybe:
```suggestion
    if (kIsWeb && (type == int && T == double) || (type == double && T == int)) {
      return false;
    }

    return data is T?;
```

This makes it a little more clear that the edge case lies in web as a target platform and particularly with identifying `int`s and `double`s.

File: packages/flutter/test/widgets/draggable_test.dart [hunk 7]
```diff
@@ -2533,6 +2533,121 @@ void main() {
...
+    await gesture.moveTo(secondLocation);
+    await tester.pump();
+
+    await gesture.up();
+    await tester.pump();
+
+    expect(accepted, equals(<int>[1]));
+  });
+
+  testWidgets('Drag and drop - DragTarget<int> should not accept Draggable<Object> data when runtime type null', (WidgetTester tester) async {
```
Comment (shihaohong) [inline packages/flutter/test/widgets/draggable_test.dart:2609]: Why is this particular test necessary? Or, what does it check for/prevent from happening?

File: packages/flutter/lib/src/widgets/drag_target.dart (hunk 5 above)
Comment (shihaohong) [reply packages/flutter/lib/src/widgets/drag_target.dart:656]: Might be a more appropriate name for the method:
```suggestion
  bool isExpectedDataType(Object? data, Type type) {
```

**Comment by shihaohong** [comment]
Thanks for looking into the web edge case, sorry I couldn't get back to you before you figured it out!

File: packages/flutter/test/widgets/draggable_test.dart (hunk 7 above)
Comment (xu-baolin) [reply packages/flutter/test/widgets/draggable_test.dart:2609]: This can catch the mistake of writing `return data is T?` as `return data is T`.

**Comment by xu-baolin** [comment]
That is fine. ：）
Wish you guys have a wonderful holiday.

**Review by shihaohong — APPROVED** [review]
LGTM. Thanks for adding the well-worded comment for `isExpectedDataType`! 

Thanks for the holiday wish :) Hope you have a wonderful holiday yourself!
