### PR TITLE
Fix crash from alt-tab'ing just after startup

### LINKED ISSUE #76325: 'package:flutter/src/rendering/mouse_tracking.dart': Failed assertion: line 311 pos 12: '!_debugDuringDeviceUpdate': is not true.
## Steps to Reproduce
I have been asked by flutter to file an issue:
_Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md_

This randomly occurred once during startup of my application on macOS.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracking.dart': Failed assertion: line 423 pos 18: 'event is! PointerRemovedEvent': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      BaseMouseTracker.updateWithEvent.<anonymous closure>.<anonymous closure> (package:flutter/src/rendering/mouse_tracking.dart:423:18)
#3      BaseMouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracking.dart:316:9)
#4      BaseMouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracking.dart:418:7)
#5      BaseMouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracking.dart:300:9)
#6      BaseMouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracking.dart:417:5)
#7      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:275:22)
#8      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316:7)
#9      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
#10     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
#11     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
#12     _rootRunUnary (dart:async/zone.dart:1370:13)
#13     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#15     _invoke1 (dart:ui/hooks.dart:186:10)
#16     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)


======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/mouse_tracking.dart': Failed assertion: line 311 pos 12: '!_debugDuringDeviceUpdate': is not true.

When the exception was thrown, this was the stack: 
#2      BaseMouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracking.dart:311:12)
#3      BaseMouseTracker.updateAllDevices (package:flutter/src/rendering/mouse_tracking.dart:460:5)
#4      RendererBinding._scheduleMouseTrackerUpdate.<anonymous closure> (package:flutter/src/rendering/binding.dart:336:22)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
```

```
flutter doctor -v
[✓] Flutter (Channel dev, 1.27.0-1.0.pre, on macOS 11.2.1 20D74 darwin-arm, locale en-DE)
    • Flutter version 1.27.0-1.0.pre at /Users/tilo/development/flutter
    • Framework revision 68c96f100e (10 days ago), 2021-02-08 16:14:15 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tilo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/tilo/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu15.29+15-CA (build 15.0.2+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 08081FDD4002T6 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 11.2.1 20D74 darwin-arm
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.
```

</details>

### LINKED ISSUE #80867: [macOS] Assertion failed "'event is! PointerRemovedEvent': is not true"
## Steps to Reproduce

1. Run `flutter create bug`.
2. For it to be easier to reproduce, make a long to hot-restart app. It is possible with the template, however.
3. Run and fullscreen the app and the editor/console, and put them in neighboring windows.
3. Hot restart, and before it finishes, ctrl-arrow to the app, then back.

**Expected results:** Everything working fine.

**Actual results:** Exception: `[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 314 pos 18: 'event is! PointerRemovedEvent': is not true.`

<details>
  <summary>Logs</summary>

Flutter analyze:

```
Analyzing pre...                                                        
No issues found! (ran in 1.7s)
```

```
[✓] Flutter (Channel master, 2.2.0-11.0.pre.184, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.2.0-11.0.pre.184 at /Users/.../dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9699b3bf11 (16 hours ago), 2021-04-20 18:59:03 -0400
    • Engine revision 610fd039ae
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/.../Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ✗ Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H524 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 2 categories.

```

</details>

### LINKED ISSUE #90838: [Linux] Pressing Alt-Tab without moving the mouse after startup breaks mouse movement afterwards
Reproduction code: 
```dart
import 'package:flutter/material.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(),
      ),
    );
  }
}
```

Reproduction step: 
1. `flutter run -d linux`
2. Alt-Tab to the app, if needed, without moving the mouse at all
3. Alt-Tab to other apps

Expected result: The app is still usable.

Actual result: The app keeps informing assertion for the mouse system and does not respond to mouse interactions. The first of the errors is:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 317 pos 18: 'event is! PointerRemovedEvent': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      MouseTracker.updateWithEvent.<anonymous closure>.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:317:18)
#3      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:206:9)
#4      MouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:312:7)
#5      MouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracker.dart:190:9)
#6      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:311:5)
#7      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:270:20)
#8      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#9      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#10     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#11     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#12     _rootRunUnary (dart:async/zone.dart:1444:13)
#13     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#15     _invoke1 (dart:ui/hooks.dart:185:10)
#16     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
```

Version:
```
 flutter doctor -v                                     ✔  10102  16:00:08
[✓] Flutter (Channel master, 2.6.0-12.0.pre.64, on Debian GNU/Linux rodete 5.10.46-4rodete4-amd64, locale
    en_US.UTF-8)
    • Flutter version 2.6.0-12.0.pre.64 at /usr/local/google/home/tongmu/dev/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 975da38dd3 (4 days ago), 2021-09-23 14:13:04 -0400
    • Engine revision a3911f24a5
    • Dart version 2.15.0 (build 2.15.0-140.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /usr/local/google/home/tongmu/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 3.5)
    • Android Studio at /usr/local/google/home/tongmu/src/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux rodete 5.10.46-4rodete4-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 94.0.4606.61

! Doctor found issues in 1 category.
```

### LINKED ISSUE #98262: Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 201 pos 12: '!_debugDuringDeviceUpdate': is not true.
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

### LINKED ISSUE #99761: [Linux] Failed assertion: line 322 pos 18: 'event is! PointerRemovedEvent': is not true.
Hi,
I am consistantly getting an error with the two flutter apps I've tried to run under Linux (Debian, to be precise).

Here is the output of `flutter run`:

```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                   
Syncing files to device Linux...                                   164ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:37749/nFrqOJh0LEQ=/
The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:37749/nFrqOJh0LEQ=/
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 322 pos 18: 'event is! PointerRemovedEvent': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      MouseTracker.updateWithEvent.<anonymous closure>.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:322:18)
#3      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:211:9)
#4      MouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:317:7)
#5      MouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracker.dart:195:9)
#6      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:316:5)
#7      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:318:20)
#8      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#9      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#10     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#11     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#12     _rootRunUnary (dart:async/zone.dart:1442:13)
#13     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#15     _invoke1 (dart:ui/hooks.dart:170:10)
#16     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)


Application finished.
```

And here is `flutter doctor -v`:

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.820, on Ubuntu 21.10 5.13.0-21-generic, locale en_GB.UTF-8)
    • Flutter version 2.11.0-0.0.pre.820 at /home/chris/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 33ab8ebad7 (3 hours ago), 2022-03-08 07:10:23 -0500
    • Engine revision 5c760759fe
    • Dart version 2.17.0 (build 2.17.0-182.0.dev)
    • DevTools version 2.11.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 13.0.0-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.65.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.27.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 21.10 5.13.0-21-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

This was also happening when I was on the beta channel.

### LINKED ISSUE #100659: [Linux Desktop]Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 317 pos 18: 'event is! PointerRemovedEvent': is not true.
**Expected results:** 

I wrote a simple desktop app to exhibit flutter assertion failures in mouse_tracker.dart.  These failures occur at startup of the app - not always, but on a high percentage of runs.

**Actual results:** 
Sometimes starts with assertion failures, sometimes not. 

The example uses the Google `window_size` plugin to constrain the app window size, then runs a trivial app consisting of a Listener widget wrapping a Container.  I suspect that the problem is with the `window_size` plugin, since I haven't seen the issue when I comment out the lines of code using it

<details>
<summary>code sample.</summary>

```dart
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';

import 'package:window_size/window_size.dart';

Future<void> main() async {

  WidgetsFlutterBinding.ensureInitialized();

  if (Platform.isLinux) {
    setWindowMaxSize(const Size(640, 480));
    setWindowMinSize(const Size(640, 480));
  }

  runApp(Listener(onPointerDown: _pointerEventListener,
      child: Container()));
}

void _pointerEventListener(PointerEvent event) {

  print('Pointer down at: ${event.position}');
}
```

</details>

<details>
  <summary>Logs</summary>

```
Launching test/mouse_tracker_bug_test.dart on Linux in debug mode...
Building Linux application...
Debug service listening on ws://127.0.0.1:45687/jLrRROscyPg=/ws
Syncing files to device Linux...
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 317 pos 18: 'event is! PointerRemovedEvent': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      MouseTracker.updateWithEvent.<anonymous closure>.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:317:18)
#3      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:206:9)
#4      MouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:312:7)
#5      MouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracker.dart:190:9)
#6      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:311:5)
#7      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:314:20)
#8      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#9      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#10     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#11     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#12     _rootRunUnary (dart:async/zone.dart:1442:13)
#13     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#15     _invoke1 (dart:ui/hooks.dart:170:10)
#16     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)


======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 201 pos 12: '!_debugDuringDeviceUpdate': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:201:12)
#3      MouseTracker.updateAllDevices (package:flutter/src/rendering/mouse_tracker.dart:353:5)
#4      RendererBinding._scheduleMouseTrackerUpdate.<anonymous closure> (package:flutter/src/rendering/binding.dart:380:22)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1089:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#11     _invoke (dart:ui/hooks.dart:151:10)
#12     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#13     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
Lost connection to device.

```

```
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.4.0-104-generic, locale
    en_US.UTF-8)
    • Flutter version 2.10.3 at /home/rhr/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/rhr/Android/Sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.14+9-Ubuntu-0ubuntu2.20.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 9.0.1-12
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /home/rhr/Tools/idea-IC-212.4416.7
    • Flutter plugin version 63.3.3
    • Dart plugin version 212.5632

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.4.0-104-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.74

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by jeremyschlatter**
There is a common failure on desktop platforms that I and other developers have experienced. If you do the following sequence of actions, your app will start logging endless "assertion failed" messages and stop responding to mouse events:

    - start the app with 'flutter run'
    - position your mouse above where the app window will load
    - when the app loads, alt-tab away from it, then alt-tab back

This is a sequence I have done unintentionally many times, and -- judging by these issue reports -- so have others:

  - Fixes #76325
  - Fixes #80867
  - Fixes #90838
  - Fixes #98262
  - Fixes #99761
  - Fixes #100659
  - https://github.com/flutter/flutter/issues/70375#issuecomment-829325236
  - Possibly #70375 ?
  - Possibly #93233 ?
  - Possibly #96364 ?

It looks like the problem is that when you do that series of actions, the first mouse event that the app sees is a Removed event. The author(s) of mouse_tracker.dart assumed that such a thing could not happen, and even (helpfully) put in an assertion to that effect.

I don't have a deep understanding of the mouse tracker, but it appears that a reasonable response to receiving an initial Removed event is to simply ignore the event and wait for the next one. Doing this fixes the
crash, and the mouse continues to work afterward.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by dkwingsmt — APPROVED** [review]
LGTM. Thanks for the investigation!

File: packages/flutter/test/rendering/mouse_tracker_test.dart [hunk 1]
```diff
@@ -133,6 +133,15 @@ void main() {
     listenerLogs.clear();
   });
 
+  test('should not crash if the first event is a Removed event', () {
```
Comment (dkwingsmt) [inline packages/flutter/test/rendering/mouse_tracker_test.dart:136]:
```suggestion
  // Regression test for https://github.com/flutter/flutter/issues/90838
  test('should not crash if the first event is a Removed event', () {
```

**Review by dkwingsmt — APPROVED** [review]

**Comment by dkwingsmt** [comment]
I'm requesting a second review.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by darrenaustin** [comment]
This appears to have broken the build:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20analyze/7051/overview

```
▌18:29:36▐ RUNNING: cd .; bin/flutter analyze --flutter-repo
Analyzing 3 items...                                            

   info • Avoid method calls or property accesses on a "dynamic" target • packages/flutter/test/rendering/mouse_tracker_test.dart:139:5 • avoid_dynamic_calls
  error • The function '_setUpWithOneAnnotation' isn't defined • packages/flutter/test/rendering/mouse_tracker_test.dart:139:5 • undefined_function
```

Not sure how this wasn't caught by the pre-commit checks. Unless there is a quick fix for this, I will revert this shortly to get the tree green again.

**Comment by jason-simmons** [comment]
I looked into at why this assertion was happening in Linux desktop apps (see https://github.com/flutter/flutter/issues/100659)

There is a race between Linux embedder startup and framework startup which can cause the first pointer add event to be sent by the `FlView` before the framework has set up the pointer event handler.  The framework then sees the remove event and triggers an assert about a remove with no matching add.

One option would be fixing this by buffering the pointer events in the engine.  But it's probably simpler to relax the requirements for the embedder's event stream and just ignore the mismatched event as is done in this PR.

**Comment by dkwingsmt** [comment]
I was suspecting the same. Keyboard events used to face the same problem and we switched to the messenger, which supports message buffering https://github.com/flutter/engine/pull/29795.

However this is not enough. The message buffering only supports one message, and at least for keyboard it's not hard to build a scenario that overflows (see https://github.com/flutter/flutter/issues/89748). We can resize the buffer, but to how much? Any size is an arbitrary size.

So I think the ultimate goal is for the framework to initiate a "startup request" and the engine replies with an initial state.

**Comment by dkwingsmt** [comment]
I have described this issue at https://github.com/flutter/flutter/issues/103094.
