### PR TITLE
Show error message in release mode when box is not laid out without losing performance

### LINKED ISSUE #126303: Show error message in release mode when box is not laid out without losing performance
Please see description in https://github.com/flutter/flutter/pull/126302 :)

_Copied from https://github.com/flutter/flutter/pull/126302_

When I encounter bugs in production environment saying null pointer error on `return _size!`, I wish I could know more information! However, currently the information is revealed by `assert(hasSize, 'RenderBox was not laid out: $this');`, thus *only* in debug mode can I know what is `this` (and/or more information that can be added), while in release mode I can only see a stack trace saying it is `RenderBox.size` that throws - nothing more :/

Therefore, it is intuitive to add this extra information in release mode. However, will it affect performance? We all know this is in critical path and should be quite careful. Thus I did some experiments: https://godbolt.org/z/zPPPf5969 From my naive understanding of assembly, the two versions of code (`size!` vs `size ?? throw`) has the same assembly, except that they throw different types of errors. In other words, when there is no error, both code should be equivalent; when there is an error, surely the new code will be slower since it calls `this.toString()`, but the error handling process is rare and already heavy, so this is not a problem.

image

### PR DESCRIPTION
**Pull request by fzyzcjy**
Close https://github.com/flutter/flutter/issues/126303

When I encounter bugs in production environment saying null pointer error on `return _size!`, I wish I could know more information! However, currently the information is revealed by `assert(hasSize, 'RenderBox was not laid out: $this');`, thus *only* in debug mode can I know what is `this` (and/or more information that can be added), while in release mode I can only see a stack trace saying it is `RenderBox.size` that throws - nothing more :/

Therefore, it is intuitive to add this extra information in release mode. However, will it affect performance? We all know this is in critical path and should be quite careful. Thus I did some experiments: https://godbolt.org/z/zPPPf5969 From my naive understanding of assembly, the two versions of code (`size!` vs `size ?? throw`) has the same assembly, except that they throw different types of errors. In other words, when there is no error, both code should be equivalent; when there is an error, surely the new code will be slower since it calls `this.toString()`, but the error handling process is rare and already heavy, so this is not a problem.

image

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/rendering/box.dart [hunk 1]
```diff
@@ -1985,7 +1985,7 @@ abstract class RenderBox extends RenderObject {
       }
       return true;
     }());
-    return _size!;
+    return _size ?? (throw AssertionError('RenderBox was not laid out: $this'));
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/box.dart:1988]: we should use StateError in release builds, not AssertionError, and we should definitely not call `RenderBox.toString`, because merely referencing that has significant performance implications.

**Comment by Hixie** [comment]
test-exempt: changes the type of a release mode exception

File: packages/flutter/lib/src/rendering/box.dart (hunk 1 above)
Comment (fzyzcjy) [reply packages/flutter/lib/src/rendering/box.dart]: 1. StateError fixed
2. we should definitely not call RenderBox.toString: May I know a bit more details - do you mean code size or runtime overhead? For code size, I guess toString is not tree-stripped since there can be `dynamic.toString` but I will make an experiment; for runtime overhead, IMHO the whole error processing logic is quite complex and slow, thus no need to worry

Comment (fzyzcjy) [reply packages/flutter/lib/src/rendering/box.dart]: Hmm I realize in release mode, `toString()` calls `toStringShort` and then it outputs almost nothing (just describeIdentity)...

**Comment by fzyzcjy** [comment]
(Possibly related: https://github.com/dart-lang/sdk/issues/52317)

**Comment by goderbauer** [comment]
@fzyzcjy I seem to remember that this was opened in the context of Crashlytics garbling up some stack traces. Without that issue, is this PR still relevant and useful?

File: packages/flutter/lib/src/rendering/box.dart [hunk 2]
```diff
@@ -1985,7 +1985,7 @@ abstract class RenderBox extends RenderObject {
       }
       return true;
     }());
-    return _size!;
+    return _size ?? (throw StateError('RenderBox was not laid out: $runtimeType#${shortHash(this)}'));
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/box.dart:1988]: We avoid calling `toString` on `runtimeType` (as is done here implicitly) in release mode, see [objectRuntimeType](https://master-api.flutter.dev/flutter/foundation/objectRuntimeType.html)

**Comment by fzyzcjy** [comment]
> @fzyzcjy I seem to remember that this was opened in the context of Crashlytics garbling up some stack traces. Without that issue, is this PR still relevant and useful?

Yes and no. Yes I opened a series of issues because of Sentry yields wrong stacks. However, for this single one, I guess this can still be useful even not under that scenario, because the `RenderBox.size` may be accessed by functions in class RenderBox, thus it is hard to debug if we just see a stack trace full of RenderBox.layout and RenderBox.size - we do not know which RenderBox causes the problem (say, RenderStack? RenderColoredBox? etc).

File: packages/flutter/lib/src/rendering/box.dart (hunk 2 above)
Comment (fzyzcjy) [reply packages/flutter/lib/src/rendering/box.dart:1988]: I did it deliberately ;) This is because `objectRuntimeType` will yield `<optimized out>` at runtime, while the main idea of the PR is to know *which* exact class causes the bug. 

Given the godbolt decompile results above, it seems that, as long as we do not touch this branch (i.e. throw error), we have zero overhead. When we throw error, we already have a ton of overhead and trouble so this runtimeType.toString does not seem to be a big problem.

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by Piinks — APPROVED** [review]
LGTM
