### PR TITLE
[O] Fix a race condition in vmservice_test.dart

### LINKED ISSUE #19273: flutter_tester hangs on linux workstation
On my Linux workstation, running flutter tester just hangs and doesn't find a flutter view to run on.

Repro:

1. `flutter create mytest`
1. `cd mytest`
1. `flutter run -d flutter-tester --verbose`
1. fails with a stack trace and `Error connecting to the service protocol: Exception: No Flutter view is available`

The same thing works fine on my mac, and flutter tester tests seem to run fine on the bots.

I have tried:
1. killing all flutter_tester processes (there were 10 running! I think it's not dying properly either).
1. rebooting my machine
1. nuking my cache directory and git pulling from master again.
1. running flutter_tester manually directly.  It runs and just sits there not reporting any errors.

I'm using master branch HEAD at 36e16e754433a1357e7f49af8c1221d70b67bc79.

Here's the entire output:
```
(home/gspencer:master) -- test_reload > flutter run -d flutter-tester --verbose
[  +42 ms] [/usr/local/google/home/gspencer/code/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +40 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: no upstream configured for branch 'master'
[        ] [/usr/local/google/home/gspencer/code/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] [/usr/local/google/home/gspencer/code/flutter/] git log -n 1 --pretty=format:%H
[   +7 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 36e16e754433a1357e7f49af8c1221d70b67bc79
[        ] [/usr/local/google/home/gspencer/code/flutter/] git log -n 1 --pretty=format:%ar
[   +6 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 68 minutes ago
[   +1 ms] [/usr/local/google/home/gspencer/code/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +25 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.6-97-g36e16e754
[ +102 ms] /usr/local/google/home/gspencer/Android/Sdk/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /usr/local/google/home/gspencer/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           84B7N15A07007628       device usb:2-2.3 product:angler model:Nexus_6P device:angler transport_id:1
[ +210 ms] Found plugin shared_preferences at /usr/local/google/home/gspencer/code/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.2/
[ +792 ms] Launching lib/main.dart on Flutter test device in debug mode...
[ +389 ms] DependencyChecker: nothing is modified after 2018-07-11 10:44:23.408.
[ +208 ms] Skipping kernel compilation. Fingerprint match.
[ +285 ms] Building bundle
[        ] Writing asset files to build/flutter_assets
[  +66 ms] Wrote build/flutter_assets
[        ] /usr/local/google/home/gspencer/code/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester --run-forever --non-interactive --enable-dart-profiling --packages=.packages --flutter-assets-dir=build/flutter_assets build/app.dill
[ +243 ms] Observatory URL on device: http://127.0.0.1:34079/
[   +6 ms] Connecting to service protocol: http://127.0.0.1:34079/
[ +195 ms] Successfully connected to service protocol: http://127.0.0.1:34079/
[   +3 ms] getVM: {}
[  +11 ms] Waiting for Flutter view
[ +187 ms] Do not know weight for: TeXGyreSchola (BoldItalic) 
[ +813 ms] Waiting for Flutter view
[+1004 ms] Waiting for Flutter view
[+1000 ms] Waiting for Flutter view
[+1000 ms] Waiting for Flutter view
[+1002 ms] No Flutter views available on Flutter test device
[   +6 ms] Error connecting to the service protocol: Exception: No Flutter view is available
[  +21 ms] "flutter run" took 7,512ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:406)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:77)
#4      _rootRunUnary (dart:async/zone.dart:1134)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638)
#8      Future._propagateToListeners (dart:async/future_impl.dart:667)
#9      Future._complete (dart:async/future_impl.dart:472)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/dart:async/async_patch.dart:28)
#12     _completeOnAsyncReturn (dart:async-patch/dart:async/async_patch.dart:292)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart:211)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:77)
#15     _rootRunUnary (dart:async/zone.dart:1134)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638)
#19     Future._propagateToListeners (dart:async/future_impl.dart:667)
#20     Future._complete (dart:async/future_impl.dart:472)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:33)
#23     _rootRun (dart:async/zone.dart:1126)
#24     _CustomZone.run (dart:async/zone.dart:1023)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#28     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/19273

### CODE REVIEW

**Comment by Hixie** [comment]
cc @zanderso

File: packages/flutter_tools/lib/src/vmservice.dart [hunk 1]
```diff
@@ -394,8 +387,8 @@ void _upgradeMap(Map<String, dynamic> map, ServiceObjectOwner owner) {
 }
 
 void _upgradeList(List<dynamic> list, ServiceObjectOwner owner) {
-  for (int i = 0; i < list.length; i++) {
-    final dynamic v = list[i];
+  for (int i = 0; i < list.length; i += 1) {
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/vmservice.dart]: Curious: is there a reason why `i++` is less desirable?

File: packages/flutter_tools/lib/src/vmservice.dart [hunk 2]
```diff
@@ -105,7 +105,7 @@ const Duration kShortRequestTimeout = Duration(seconds: 5);
 // TODO(flutter/flutter#23031): Test this.
 /// A connection to the Dart VM Service.
 class VMService {
-  VMService._(
+  VMService(
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/vmservice.dart]: `@visibleForTesting`?

File: packages/flutter_tools/lib/src/vmservice.dart [hunk 3]
```diff
@@ -394,8 +387,8 @@ void _upgradeMap(Map<String, dynamic> map, ServiceObjectOwner owner) {
 }
 
 void _upgradeList(List<dynamic> list, ServiceObjectOwner owner) {
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/vmservice.dart]: Should/can this be `List<Object>` too, since you change `dynamic` to `Object` below?

File: packages/flutter_tools/lib/src/vmservice.dart [hunk 4]
```diff
@@ -661,7 +650,7 @@ class VM extends ServiceObjectOwner {
   VM get vm => this;
 
   @override
-  Future<Map<String, dynamic>> _fetchDirect() async {
+  Future<Map<String, dynamic>> _fetchDirect() {
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/vmservice.dart]: `=> invokeRpcRaw('getVM');`

File: packages/flutter_tools/lib/src/resident_runner.dart [hunk 5]
```diff
@@ -79,15 +79,13 @@ class FlutterDevice {
...
-      return Future<void>.value(null);
+      return;
     final List<Future<void>> futures = <Future<void>>[];
     for (VMService service in vmServices)
-      futures.add(service.vm.refreshViews());
-    final Completer<void> completer = Completer<void>();
-    Future.wait(futures).whenComplete(() => completer.complete(null)); // ignore: unawaited_futures
-    return completer.future;
+      futures.add(service.vm.refreshViews(waitForViews: true));
+    await Future.wait(futures);
```
Comment (aam) [inline packages/flutter_tools/lib/src/resident_runner.dart]: I think my intent was not to `await `here, so refreshViews could continue without blocking. Was there a reason you put `await` back?

File: packages/flutter_tools/lib/src/vmservice.dart [hunk 6]
```diff
@@ -949,19 +943,31 @@ class VM extends ServiceObjectOwner {
...
+      final List<Future<void>> futures = <Future<void>>[];
+      for (Isolate isolate in isolates.toList()) {
+        futures.add(vmService.vm.invokeRpc<ServiceObject>(
+          '_flutter.listViews',
           timeout: kLongRequestTimeout,
-          params: <String, dynamic> {'isolateId': isolate.id}));
+          params: <String, dynamic> {'isolateId': isolate.id},
+        ));
+      }
+      await Future.wait(futures);
```
Comment (aam) [inline packages/flutter_tools/lib/src/vmservice.dart]: Similarly, can we avoid awaiting in this method and instead let caller await if it decided it needed to?

Comment (tvolkert) [reply packages/flutter_tools/lib/src/vmservice.dart]: The return value of this method will be a future that will complete when all the futures have completed.  It's still up to the caller to await the future returned by this method or not.

File: packages/flutter_tools/lib/src/resident_runner.dart (hunk 5 above)
Comment (tvolkert) [reply packages/flutter_tools/lib/src/resident_runner.dart]: The caller of `refreshViews()` can choose to not await the returned future.  The use of async/await here is semantically equivalent to what you were trying to do with the `Completer`.

File: packages/flutter_tools/lib/src/vmservice.dart [hunk 7]
```diff
@@ -949,19 +943,31 @@ class VM extends ServiceObjectOwner {
...
-    final List<Future<ServiceObject>> futures = <Future<ServiceObject>>[];
-    for (Isolate isolate in isolates.toList()) {
-      futures.add(vmService.vm.invokeRpc<ServiceObject>('_flutter.listViews',
+      return;
+    int failCount = 0;
+    while (true) {
+      _viewCache.clear();
+      final List<Future<void>> futures = <Future<void>>[];
+      for (Isolate isolate in isolates.toList()) {
+        futures.add(vmService.vm.invokeRpc<ServiceObject>(
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/vmservice.dart]: Add a comment explaining that upon completion of this RPM, `_viewCache` will be updated.

File: packages/flutter_tools/lib/src/vmservice.dart [hunk 8]
```diff
@@ -949,19 +943,31 @@ class VM extends ServiceObjectOwner {
...
+          '_flutter.listViews',
           timeout: kLongRequestTimeout,
-          params: <String, dynamic> {'isolateId': isolate.id}));
+          params: <String, dynamic> {'isolateId': isolate.id},
+        ));
+      }
+      await Future.wait(futures);
+      if (_viewCache.values.isNotEmpty || !waitForViews)
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/vmservice.dart]: Can `listViews` ever legitimately turn up no `FlutterView` instances?  If so, we'll retry here until we eventually fail, even though there was no failure...

Comment (tvolkert) [reply packages/flutter_tools/lib/src/vmservice.dart]: Though I guess that's what `waitForViews` is for (why why it defaults to `false`)?

File: packages/flutter_tools/test/vmservice_test.dart [hunk 9]
```diff
@@ -2,18 +2,230 @@
...
+  final MockStdio mockStdio = MockStdio();
   group('VMService', () {
     testUsingContext('fails connection eagerly in the connect() method', () async {
       expect(
         VMService.connect(Uri.parse('http://host.invalid:9999/')),
         throwsToolExit(),
       );
     });
+
+    testUsingContext('refreshViews', () async {
```
Comment (tvolkert) [inline packages/flutter_tools/test/vmservice_test.dart]: No need for `async`

**Review by tvolkert — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/resident_runner.dart (hunk 5 above)
Comment (aam) [reply packages/flutter_tools/lib/src/resident_runner.dart]: Ok, got it.

**Review by aam — APPROVED** [review]

File: packages/flutter_tools/lib/src/vmservice.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter_tools/lib/src/vmservice.dart]: in this case, not really. In the general case, `++` suffix can be less efficient (since it has to store the value, then increment it, then use it), so `++` prefix is preferred. But that's ugly. So I pre-emptively turn `++` into the equivalent `+= 1` to make people more comfortable with `+= 1` so that the issue of `++` prefix can go away. :-)

File: packages/flutter_tools/lib/src/vmservice.dart (hunk 2 above)
Comment (Hixie) [reply packages/flutter_tools/lib/src/vmservice.dart]: Does it matter in this case?

File: packages/flutter_tools/lib/src/vmservice.dart (hunk 3 above)
Comment (Hixie) [reply packages/flutter_tools/lib/src/vmservice.dart]: I think the JSON logic creates `List<dynamic>`s, not `List<Object>`s.

File: packages/flutter_tools/lib/src/vmservice.dart (hunk 4 above)
Comment (Hixie) [reply packages/flutter_tools/lib/src/vmservice.dart]: done

File: packages/flutter_tools/lib/src/resident_runner.dart (hunk 5 above)
Comment (Hixie) [reply packages/flutter_tools/lib/src/resident_runner.dart]: yeah these are identical semantically. I happened to have already made this change on my branch; I didn't put the await back so much as have to resolve the merge. :-)

File: packages/flutter_tools/lib/src/vmservice.dart (hunk 6 above)
Comment (Hixie) [reply packages/flutter_tools/lib/src/vmservice.dart]: `await future; ...rest of method...` is exactly equivalent to `return future.then(...rest of method...)`.

File: packages/flutter_tools/lib/src/vmservice.dart (hunk 7 above)
Comment (Hixie) [reply packages/flutter_tools/lib/src/vmservice.dart]: done

File: packages/flutter_tools/lib/src/vmservice.dart (hunk 8 above)
Comment (Hixie) [reply packages/flutter_tools/lib/src/vmservice.dart]: I don't know the answer to your first question, but if so, I don't know how we would distinguish that case from the normal case where we don't want to return until we have a view.

The argument defaults to false so as to not change the default behaviour in the regular case; only in the specific case where I believe we definitely need a view did I set it to true.

File: packages/flutter_tools/test/vmservice_test.dart (hunk 9 above)
Comment (Hixie) [reply packages/flutter_tools/test/vmservice_test.dart]: fixed

**Comment by Hixie** [comment]
thanks for the reviews, will land on green

**Comment by Hixie** [comment]
Reverting this since it broke a test. cc @aam we might want to work together on this... both of our patches in the same area had the same problem.

**Comment by Hixie** [comment]
Specifically, named_isolates_test failed.

File: packages/flutter_tools/lib/src/resident_runner.dart [hunk 10]
```diff
@@ -483,8 +485,10 @@ abstract class ResidentRunner {
   }
 
   Future<void> refreshViews() async {
+    final List<Future<void>> futures = <Future<void>>[];
     for (FlutterDevice device in flutterDevices)
-      await device.refreshViews();
+      futures.add(device.refreshViews());
+    await Future.wait(futures);
```
Comment (aam) [inline packages/flutter_tools/lib/src/resident_runner.dart]: This is the change that breaks named_isolates_test.
From what I can tell flutter engine is getting stuck processing two concurrent listViews requests https://github.com/flutter/engine/blob/master/runtime/service_protocol.cc#L237.

cc @jason-simmons @chinmaygarde

Comment (aam) [reply packages/flutter_tools/lib/src/resident_runner.dart]: To reproduce the failure pick up this new implementation of refreshViews() method and run named_isolates_test locally from `$FH/flutter/dev/devicelab`: `$FH/flutter/bin/cache/dart-sdk/bin/dart bin/run.dart -t named_isolates_test`

Comment (aam) [reply packages/flutter_tools/lib/src/resident_runner.dart]: I am fixing refreshViews so it is app-wide, rather than isolate-specific message, that should fix deadlock in the engine((in https://github.com/flutter/flutter/commit/89665ac4527fd8e9cadc1df28c86c9b0c8659a58). @chinmaygarde is making engine more robust to these kind of scenarios.

Comment (Hixie) [reply packages/flutter_tools/lib/src/resident_runner.dart]: awesome.
