### PR TITLE
RawKeyboard synthesizes key pressing state for modifier

### LINKED ISSUE #93278: [Linux, Keyboard] Pressing AltRight-ShiftLeft repeatedly crashes the app
App: Any app with a text field.

Reproduction:
1. Run with `flutter run -d linux`
2. Press ShiftLeft-AltRight repeatedly
3. The terminal first starts to show errors related to `synchronize_pressed_states_loop_body`, then eventually crashes.

```
** (test_app:2003431): CRITICAL **: 12:45:00.738: void synchronize_pressed_states_loop_body(gpointer, gpointer, gpointer): assertion 'pressed_logical_key_before_event == 0 || pressed_logical_key_before_event == logical_key' failed

** (test_app:2003431): CRITICAL **: 12:45:00.773: void synchronize_pressed_states_loop_body(gpointer, gpointer, gpointer): assertion 'pressed_logical_key_before_event == 0 || pressed_logical_key_before_event == logical_key' failed

** (test_app:2003431): CRITICAL **: 12:45:00.773: void synchronize_pressed_states_loop_body(gpointer, gpointer, gpointer): assertion 'pressed_logical_key_before_event == 0 || pressed_logical_key_before_event == logical_key' failed

** (test_app:2003431): CRITICAL **: 12:45:00.793: void synchronize_pressed_states_loop_body(gpointer, gpointer, gpointer): assertion 'pressed_logical_key_before_event == 0 || pressed_logical_key_before_event == logical_key' failed

** (test_app:2003431): WARNING **: 12:45:00.947: Unable to retrieve framework response: Message is not valid JSON

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key
event being sent doesn't properly set its modifier flags. This was the event:
RawKeyDownEvent#b50a1(logicalKey: LogicalKeyboardKey#00105(keyId: "0x200000105", keyLabel: "Alt
Right", debugName: "Alt Right"), physicalKey: PhysicalKeyboardKey#700e6(usbHidUsage: "0x000700e6",
debugName: "Alt Right")) and its data: RawKeyEventDataLinux#2cf6e(toolkit: GTK, unicodeScalarValues:
0, scanCode: 108, keyCode: 65027, modifiers: 33562624, isDown: true)
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 668 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:668:7)
#3      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:818:33)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#5      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:389:35)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:386:46)
#8      _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
#12     _invoke2 (dart:ui/hooks.dart:188:10)
#13     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#14     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#15     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#16     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
#17     _dispatchPlatformMessage (dart:ui/hooks.dart:83:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

** (test_app:2003431): WARNING **: 12:45:01.125: Unable to retrieve framework response: Message is not valid JSON

Another exception was thrown: Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#dcac4(logicalKey:
LogicalKeyboardKey#00105(keyId: "0x200000105", keyLabel: "Alt Right", debugName: "Alt Right"), physicalKey: PhysicalKeyboardKey#700e6(usbHidUsage: "0x000700e6", debugName: "Alt Right")) and its data: RawKeyEventDataLinux#2cf6e(toolkit: GTK,
unicodeScalarValues: 0, scanCode: 108, keyCode: 65027, modifiers: 33562624, isDown: true)
```

Environment: (Linux over Chrome remote desktop from macOS)
<details><pre>
[✓] Flutter (Channel master, 2.6.0-12.0.pre.641, on Debian GNU/Linux rodete 5.10.46-5rodete1-amd64, locale en_US.UTF-8)
    • Flutter version 2.6.0-12.0.pre.641 at /usr/local/google/home/tongmu/dev/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision f4f23ecb59 (21 minutes ago), 2021-11-08 12:27:14 -0800
    • Engine revision 469d6f1a09
    • Dart version 2.15.0 (build 2.15.0-285.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /usr/local/google/home/tongmu/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.1.0-4+build1
    • cmake version 3.21.3
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 3.5)
    • Android Studio at /usr/local/google/home/tongmu/src/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux rodete 5.10.46-5rodete1-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

! Doctor found issues in 1 category
</pre></details>

### PR DESCRIPTION
**Pull request by dkwingsmt**
This PR changes `RawKeyboard` so that, if the current key is being pressed but does not exist in the modifier bit mask, add this key to `keysPressed`. This change effectively disables the assertion check immediately after `_synchronizeModifiers` (but it is still kept there.)

This change fixes a case on Linux where a very peculiar sequence of key presses result in an AltRight key down event being sent without the Alt modifier bit, breaking our assumption where the key being pressed must exist in the modifier bit. The approach of this PR adapts the `keysPressed` state to the event. 

An alternative solution is to pretend this event didn't happen, adapting the event to the `keysPressed` state. I didn't choose this solution because it breaks `RawKeyboard`'s design of one-to-one mapping from the native events to the Flutter events. After all, the modifier bits are used to assist synthesization, not to change event output overall.

~~It's a sad choice to disable this check that helped us for so long.~~ Update: I've limited the check bypassing to Linux AltRight key.

This PR fixes one of the two symptoms of https://github.com/flutter/flutter/issues/93278.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/services/raw_keyboard_test.dart [hunk 1]
```diff
@@ -348,6 +350,55 @@ void main() {
...
+      await simulate(true,  0x6c/*AltRight*/,  0xfe03/*AltRight*/,  0x2002000/*Reserve14*/);
+      expect(
+        RawKeyboard.instance.keysPressed,
+        equals(
+          <LogicalKeyboardKey>{
+            LogicalKeyboardKey.altRight,
+          },
+        ),
+      );
+    }, skip: isBrowser); // [intended] This is a GLFW-specific test.
```
Comment (gspencergoog) [inline packages/flutter/test/services/raw_keyboard_test.dart:400]: Isn't it Gtk specific, not GLFW?

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

I think it's probably the right choice to disable it here, but would we be able to limit this change to just Linux? At least then we would be able to keep the check on other platforms.

**Comment by dkwingsmt** [comment]
Update: I've limited the check bypassing to Linux AltRight key.
