### PR TITLE
When a list is scrolling, children can't be tapped

### LINKED ISSUE #5023: Stopping flings should not count as a touch
(A video would make this easy to understand, but it's not easy for me to capture one at this second.)

To repro:
1.  Open Flutter Gallery on iOS
2. Fling scroll on the home page.
3.  Stop the fling with your finger (notice how it starts a splash effect on the item below your finger).
4.  Lift your finger after stopping.  Notice that it counted your "stop scroll" as an action and activated the list item below your finger and took you to whatever demo you happened to be over.

Compare this behavior with how flings of other scrolling lists work on iOS (such as Settings), notice that Flutter's behavior is incorrect.

It's possible our behavior here is wrong on Android too, but I haven't confirmed yet.

Thanks to @goderbauer for bringing this to my attention.

### PR DESCRIPTION
**Pull request by Hixie**
Fixes #5023 better than #5222 did.

The key difference is that since the controller's state is now used in the build function, we have to setState() in the _stop() function and in the status handler.

Also added more tests.

### CODE REVIEW

File: examples/flutter_gallery/test/smoke_test.dart [hunk 1]
```diff
@@ -64,16 +67,18 @@ Future<Null> smokeDemo(WidgetTester tester, String routeName) async {
 }
 
 void main() {
-  TestWidgetsFlutterBinding binding =
-      TestWidgetsFlutterBinding.ensureInitialized();
-  if (binding is LiveTestWidgetsFlutterBinding) binding.allowAllFrames = true;
+  // TestWidgetsFlutterBinding binding = TestWidgetsFlutterBinding.ensureInitialized();
+  // if (binding is LiveTestWidgetsFlutterBinding)
+  //   binding.allowAllFrames = true;
```
Comment (abarth) [inline examples/flutter_gallery/test/smoke_test.dart]: Commented out code?

**Comment by abarth** [comment]
LGTM
