### PR TITLE
limit open files on macOS when copying assets

### LINKED ISSUE #34045: Web tools failed first time, worked second.
```
eseidel@eseidel-macbookpro3 /src/flutter/examples/flutter_gallery %FLUTTER_WEB=true flutter run -d web                                                                                         [/src/flutter/examples/flutter_gallery]
Downloading Web SDK...                                              3.5s
Downloading package sky_engine...                                   0.5s
Downloading common tools...                                         6.7s
Downloading common tools...                                         7.5s
Downloading darwin-x64 tools...                                    24.6s
Running "flutter pub get" in flutter_gallery...                    29.6s
Compiling lib/main.dart for the Web...                             34.3s

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 70069559c728fde5)
 
Crash report written to /src/flutter/examples/flutter_gallery/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
eseidel@eseidel-macbookpro3 /src/flutter/examples/flutter_gallery %less /src/flutter/examples/flutter_gallery/flutter_01.log                                                                   [/src/flutter/examples/flutter_gallery]
eseidel@eseidel-macbookpro3 /src/flutter/examples/flutter_gallery %FLUTTER_WEB=true flutter run -d web                                                                                         [/src/flutter/examples/flutter_gallery]
Compiling lib/main.dart for the Web...                              1.6s

🔥  To hot restart (and rebuild state), press "R".
For a more detailed help message, press "h". To quit, press "q".
```
[flutter_01.log](https://github.com/flutter/flutter/files/3266670/flutter_01.log)

@jonahwilliams

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

The async File APIs batch their work to be shipped off to a background thread, but in doing so they retain the file descriptors. The fix is to only run on ~30 or so files at a time for macOS so as to not exhaust the open files.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/34045

### CODE REVIEW

File: packages/flutter_tools/lib/src/bundle.dart [hunk 1]
```diff
@@ -226,10 +228,18 @@ Future<void> writeBundle(
     bundleDir.deleteSync(recursive: true);
   bundleDir.createSync(recursive: true);
 
+  // On systems with a limited number of file descriptors, limit number of
+  // open files.
+  final Pool pool = Pool(platform.isMacOS ? 30 : 1000);
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/bundle.dart]: How about something like 64 everywhere. We'll hit the same problem again on some other platform with a small limit, and I'd be surprised if there was any performance impact on any platform.

**Review by zanderso — APPROVED** [review]
