### PR TITLE
Spacebar and enter in EditableText work with Inkwells

### LINKED ISSUE #98322: BUG Newline not working with TextFormField/TextField on Android device with Chinese keyboard when TextFormField is a child of ListTile
## Steps to Reproduce

1. Run the app on any Android device (Using google Chinese keyboard). Enter the textfield and try to enter a text with line breaks by using the enter key on your software keyboard.

**Expected results:**
A text with line breaks

**Actual results:**
A text without line breaks and triggers a press on ListTile.

bug

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ListTile(
              title: TextFormField(
                keyboardType: TextInputType.multiline,
                textInputAction: TextInputAction.newline,
                maxLines: 4,
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                ),
              ),
              subtitle: TextFormField(
                keyboardType: TextInputType.multiline,
                textInputAction: TextInputAction.newline,
                maxLines: 4,
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
C:\Users\wyliu\StudioProjects\text_field_newline>flutter run --verbose
[  +68 ms] executing: [C:\Users\wyliu\Documents\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +232 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c
[        ] executing: [C:\Users\wyliu\Documents\flutter/] git tag --points-at 5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c
[  +42 ms] Exit code 0 from: git tag --points-at 5f105a6ca7a5ac7b8bc9b241f4c2d86f4188cf5c
[        ] 2.10.0
[   +7 ms] executing: [C:\Users\wyliu\Documents\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\wyliu\Documents\flutter/] git ls-remote --get-url origin
[  +28 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +102 ms] executing: [C:\Users\wyliu\Documents\flutter/] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +69 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +56 ms] executing: C:\Users\wyliu\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +51 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:2
[   +7 ms] C:\Users\wyliu\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +41 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +123 ms] Skipping pub get: version match.
[  +66 ms] Generating C:\Users\wyliu\StudioProjects\text_field_newline\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +51 ms] ro.hardware = ranchu
[  +13 ms] Using hardware rendering with device AOSP on IA Emulator. If you notice graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
[  +30 ms] Initializing file store
[  +14 ms] Skipping target: gen_localizations
[   +7 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
C:\Users\wyliu\StudioProjects\text_field_newline\.dart_tool\package_config_subset}
[  +31 ms] gen_dart_plugin_registrant: Complete
[   +2 ms] Skipping target: _composite
[   +2 ms] complete
[   +7 ms] Launching lib\main.dart on AOSP on IA Emulator in debug mode...
[   +5 ms] C:\Users\wyliu\Documents\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\wyliu\Documents\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\wyliu\Documents\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\wyliu\AppData\Local\Temp\flutter_tools.64d4216\flutter_tool.ddeae8e4\app.dill --packages
C:\Users\wyliu\StudioProjects\text_field_newline\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +11 ms] executing: C:\Users\wyliu\AppData\Local\Android\sdk\build-tools\33.0.0-rc1\aapt dump xmltree
C:\Users\wyliu\StudioProjects\text_field_newline\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +65 ms] Exit code 0 from: C:\Users\wyliu\AppData\Local\Android\sdk\build-tools\33.0.0-rc1\aapt dump xmltree
C:\Users\wyliu\StudioProjects\text_field_newline\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.ppodds.text_field_newline" (Raw: "com.ppodds.text_field_newline")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="text_field_newline" (Raw: "text_field_newline")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.ppodds.text_field_newline.MainActivity" (Raw: "com.ppodds.text_field_newline.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=37)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=41)
                     E: action (line=42)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=44)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=51)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=55)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=58)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +6 ms] executing: C:\Users\wyliu\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +14 ms] <- compile package:text_field_newline/main.dart
[  +73 ms] --------- beginning of main
           02-12 08:44:43.495 D/AlarmManagerService( 1936): Kernel timezone updated to 0 minutes west of GMT
[  +10 ms] executing: C:\Users\wyliu\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +17 ms] Android Debug Bridge version 1.0.41
           Version 32.0.0-8006631
           Installed as C:\Users\wyliu\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\wyliu\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +28 ms] Building APK
[  +18 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] Using gradle from C:\Users\wyliu\StudioProjects\text_field_newline\android\gradlew.bat.
[  +16 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +139 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.11" 2021-04-20
           OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
           OpenJDK 64-Bit Server VM (build 11.0.11+9-b60-7590822, mixed mode)
[   +1 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +155 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.11" 2021-04-20
           OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
           OpenJDK 64-Bit Server VM (build 11.0.11+9-b60-7590822, mixed mode)
[   +2 ms] executing: [C:\Users\wyliu\StudioProjects\text_field_newline\android/] C:\Users\wyliu\StudioProjects\text_field_newline\android\gradlew.bat
-Pverbose=true -Ptarget-platform=android-x86 -Ptarget=C:\Users\wyliu\StudioProjects\text_field_newline\lib\main.dart -Pbase-application-name=android.app.Application
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1587 ms] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
[   +2 ms] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
[        ] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
[ +103 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[  +85 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugAssets
[ +298 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[  +89 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[ +103 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:packageDebug UP-TO-DATE
[  +91 ms] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 2s
[        ] 32 actionable tasks: 4 executed, 28 up-to-date
[ +545 ms] Running Gradle task 'assembleDebug'... (completed in 3.2s)
[  +54 ms] calculateSha: LocalDirectory: 'C:\Users\wyliu\StudioProjects\text_field_newline\build\app\outputs\flutter-apk'/app.apk
[ +555 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +3 ms] executing: C:\Users\wyliu\AppData\Local\Android\sdk\build-tools\33.0.0-rc1\aapt dump xmltree
C:\Users\wyliu\StudioProjects\text_field_newline\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +14 ms] Exit code 0 from: C:\Users\wyliu\AppData\Local\Android\sdk\build-tools\33.0.0-rc1\aapt dump xmltree
C:\Users\wyliu\StudioProjects\text_field_newline\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.ppodds.text_field_newline" (Raw: "com.ppodds.text_field_newline")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="text_field_newline" (Raw: "text_field_newline")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.ppodds.text_field_newline.MainActivity" (Raw: "com.ppodds.text_field_newline.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=37)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=41)
                     E: action (line=42)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=44)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=51)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=55)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=58)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +2 ms] Stopping app 'app.apk' on AOSP on IA Emulator.
[        ] executing: C:\Users\wyliu\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am force-stop com.ppodds.text_field_newline
[  +46 ms] executing: C:\Users\wyliu\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell pm list packages com.ppodds.text_field_newline
[ +372 ms] package:com.ppodds.text_field_newline
[   +2 ms] executing: C:\Users\wyliu\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell cat
/data/local/tmp/sky.com.ppodds.text_field_newline.sha1
[ +167 ms] 56e1c011dca6d629c1764045448dda868b88c3bc
[   +1 ms] Latest build already installed.
[        ] executing: C:\Users\wyliu\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +27 ms] --------- beginning of main
           02-12 08:44:48.163 I/GnssLocationProvider( 1936): WakeLock released by handleMessage(REPORT_SV_STATUS, 0,
           com.android.server.location.GnssLocationProvider$SvStatusInfo@50f5b20)
[   +6 ms] executing: C:\Users\wyliu\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000
--ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.ppodds.text_field_newline/com.ppodds.text_field_newline.MainActivity
[  +79 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.ppodds.text_field_newline/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+2410 ms] Observatory URL on device: http://127.0.0.1:34708/7Qu6ufkTZX0=/
[   +1 ms] executing: C:\Users\wyliu\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:0 tcp:34708
[  +21 ms] 53492
[        ] Forwarded host port 53492 to device port 34708 for Observatory
[   +5 ms] Caching compiled dill
[  +31 ms] Connecting to service protocol: http://127.0.0.1:53492/7Qu6ufkTZX0=/
[ +533 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:53492/7Qu6ufkTZX0=/.
[ +791 ms] DDS is listening at http://127.0.0.1:53495/vqIjj0WLIJs=/.
[  +51 ms] Successfully connected to service protocol: http://127.0.0.1:53492/7Qu6ufkTZX0=/
[  +51 ms] DevFS: Creating new filesystem on the device (null)
[  +41 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.ppodds.text_field_newline/code_cache/text_field_newlineXEAHKZ/text_field_newline/)
[   +2 ms] Updating assets
[  +79 ms] Syncing files to device AOSP on IA Emulator...
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] Processing bundle.
[   +1 ms] <- recompile package:text_field_newline/main.dart 0a28a445-011c-4374-a2ae-a4689230d2d2
[        ] <- 0a28a445-011c-4374-a2ae-a4689230d2d2
[   +2 ms] Bundle processing done.
[ +306 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device AOSP on IA Emulator... (completed in 315ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +5 ms] Connected to _flutterView/0xec045f10.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 
[   +1 ms] R Hot restart.
[   +1 ms] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ]  Running with sound null safety 
[   +1 ms] An Observatory debugger and profiler on AOSP on IA Emulator is available at: http://127.0.0.1:53495/vqIjj0WLIJs=/
[+1204 ms] The Flutter DevTools debugger and profiler on AOSP on IA Emulator is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:53495/vqIjj0WLIJs=/
[  +42 ms] D/eglCodecCommon( 2533): setVertexArrayObject: set vao to 0 (0) 1 0
[   +6 ms] D/skia    ( 2533): Shader compilation error
[   +1 ms] D/skia    ( 2533): ------------------------
[        ] D/skia    ( 2533): Errors:
[   +2 ms] D/skia    ( 2533): link failed but did not provide an info log
[   +7 ms] D/skia    ( 2533): Shader compilation error
[   +2 ms] D/skia    ( 2533): ------------------------
[   +1 ms] D/skia    ( 2533): Errors:
[        ] D/skia    ( 2533): link failed but did not provide an info log
[   +1 ms] D/skia    ( 2533): Shader compilation error
[        ] D/skia    ( 2533): ------------------------
[        ] D/skia    ( 2533): Errors:
[   +1 ms] D/skia    ( 2533): link failed but did not provide an info log
[   +2 ms] D/skia    ( 2533): Shader compilation error
[   +1 ms] D/skia    ( 2533): ------------------------
[        ] D/skia    ( 2533): Errors:
[        ] D/skia    ( 2533): link failed but did not provide an info log
[   +4 ms] D/skia    ( 2533): Shader compilation error
[        ] D/skia    ( 2533): ------------------------
[        ] D/skia    ( 2533): Errors:
[   +1 ms] D/skia    ( 2533): link failed but did not provide an info log
[  +75 ms] D/EGL_emulation( 2533): eglMakeCurrent: 0xec385a80: ver 3 0 (tinfo 0xec383cb0)
[  +29 ms] D/eglCodecCommon( 2533): setVertexArrayObject: set vao to 0 (0) 1 2
[+3590 ms] D/skia    ( 2533): Shader compilation error
[   +2 ms] D/skia    ( 2533): ------------------------
[        ] D/skia    ( 2533): Errors:
[        ] D/skia    ( 2533): link failed but did not provide an info log
[+16835 ms] D/skia    ( 2533): Shader compilation error
[   +1 ms] D/skia    ( 2533): ------------------------
[        ] D/skia    ( 2533): Errors:
[        ] D/skia    ( 2533): link failed but did not provide an info log
[  +26 ms] D/skia    ( 2533): Shader compilation error
[        ] D/skia    ( 2533): ------------------------
[        ] D/skia    ( 2533): Errors:
[        ] D/skia    ( 2533): link failed but did not provide an info log
[+7807 ms] D/skia    ( 2533): Shader compilation error
[   +1 ms] D/skia    ( 2533): ------------------------
[        ] D/skia    ( 2533): Errors:
[        ] D/skia    ( 2533): link failed but did not provide an info log
[  +33 ms] D/skia    ( 2533): Shader compilation error
[        ] D/skia    ( 2533): ------------------------
[        ] D/skia    ( 2533): Errors:
[        ] D/skia    ( 2533): link failed but did not provide an info log
[+15480 ms] D/EGL_emulation( 2533): eglMakeCurrent: 0xec385a80: ver 3 0 (tinfo 0xec383cb0)
[  +95 ms] E/eglCodecCommon( 2533): goldfish_dma_create_region: could not obtain fd to device! fd 0 errno=11
[+2047 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +3 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.ppodds.text_field_newline/code_cache/text_field_newlineXEAHKZ/text_field_newline/)
[ +261 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[  +13 ms] "flutter run" took 57,373ms.
[  +29 ms] ensureAnalyticsSent: 26ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +2 ms] exiting with code 0
```

```
C:\Users\wyliu\StudioProjects\text_field_newline>flutter analyze
Analyzing text_field_newline...
No issues found! (ran in 1.8s)
```

```
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19044.1526], locale zh-TW)
    • Flutter version 2.10.0 at C:\Users\wyliu\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (10 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at C:\Users\wyliu\AppData\Local\Android\sdk
    • Platform android-32, build-tools 33.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31410.357
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these
      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at D:\Programs\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.64.0)
    • VS Code at C:\Users\wyliu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1526]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 98.0.1108.43

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
Previously, an EditableText with an Inkwell above it couldn't input space or enter.  The Inkwell would receive the key instead of the EditableText.  This PR tells EditableText to consume ActivateIntents, because keypresses while entering text into an EditableText shouldn't activate anything.

Fixes https://github.com/flutter/flutter/issues/98322

### CODE REVIEW

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -3146,6 +3146,10 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
   }
 
   late final Map<Type, Action<Intent>> _actions = <Type, Action<Intent>>{
+    // Keypresses in EditableText shouldn't activate anything in the tree above.
+    ActivateIntent: DoNothingAction(consumesKey: false),
+    ButtonActivateIntent: DoNothingAction(consumesKey: false),
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:3151]: Originally I tried a much more complicated solution.  I tried to make an Action that disabled itself when an EditableText was focused.

I think this solution is much more elegant.  Here the EditableText is saying that you can't activate anything while typing into it.  I think this makes sense on its own in the context of EditableText.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:3151]: Ideally `EditableText` shouldn't be the one that has to deal with this. The key event should just be consumed by one of the text editing shortcuts and should never reach the inkwell. Would that be possible with the current Shortcuts mechanism?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:3151]: Unfortunately no if I understand you correctly.  On the engine side, the key is first sent to the framework where Shortcuts has the chance to consume it.  If it doesn't, then the engine sends it to the IME.

There may or may not be a better way to organize that...  As it is, I think it makes sense to me that it's EditableText's responsibility to say that it wants these keys to go to the IME and not to be consumed by shortcuts.  Maybe it would be better if I used Shortcuts and consumed the keys directly instead of the Intents?

```dart
      // Inside EditableTextState's build method
      child: Shortcuts(
        shortcuts: <ShortcutActivator, Intent>{
          SingleActivator(LogicalKeyboardKey.space): DoNothingAndStopPropagationIntent(),
          SingleActivator(LogicalKeyboardKey.enter): DoNothingAndStopPropagationIntent(),
        },
```

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:3151]: Don't we have `DoNothingAndStopPropagationTextIntent` which can only be handled by text fields? If we map space & enter to that intent in the default text editing shortcuts, when the current focus is a text field then the key event will be sent back to the engine/IME I think?

**Comment by justinmc** [comment]
I think my comment got swallowed when I pushed a commit but your idea in [your comment](https://github.com/flutter/flutter/pull/98469#discussion_r809332493) worked great, I've updated the PR.  I didn't realize that was possible but it's a lot cleaner 👍

**Review by LongCatIsLooong — APPROVED** [review]
