### PR TITLE
Fix null issue with dynamically updating from zero tabs for TabBar

### LINKED ISSUE #40014: Intermittent TabBar crash in _IndicatorPainter._tabOffsetsEqual
## Description

The _IndicatorPainter._tabOffsetsEqual() method in [material/tabs.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/tabs.dart#L421) compares cached lists of the x-offsets of its tabbar's tabs:

```dart
  static bool _tabOffsetsEqual(List<double> a, List<double> b) {
    if (a?.length != b?.length)
      return false;
    for (int i = 0; i < a.length; i += 1) {
      if (a[i] != b[i])
        return false;
    }
    return true;
  }
```

Here `a` and `b` are the values of _IndicatorPainter_currentTabOffsets. The offsets are computed each time the tabbar is laid out.

If either a or b are null the code will crash. However this function is called by `shouldRepaint()` and it's assumed that layout will have completed before shouldRepaint() calls _tabOffsetsEqual().

The crash has occurred intermittently in the field but we have not been able to reproduce it.

FTR: This scenario used to be [guarded against](https://github.com/flutter/flutter/pull/13164/files#diff-6d433f126d05f45352a40b9bb916ac70L317), but the assert was removed.

## Related Issues
Original crash report: https://github.com/flutter/flutter/issues/35997
PR for null checks: https://github.com/flutter/flutter/pull/40009

### LINKED ISSUE #68586: Use TabBar in Dialog to report an error, LateInitializationError: _currentTabOffsets@1725014024
## Steps to Reproduce

1. 在一个Dialog上使用TabBar.
2. 调用```showGeneralDialog```；
3. 页面提示```Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.```异常；

**Expected results:** 
页面正常显示；

**Actual results:** 
页面提示```Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.```异常；

<details>
  <summary>Logs</summary>

```
[+1540 ms] flutter: Another exception was thrown: LateInitializationError: _currentTabOffsets@595014024
[   +2 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +3 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: LateInitializationError: _currentTabOffsets@595014024
[   +7 ms] flutter: Another exception was thrown: buildScope missed some dirty elements.
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Mac OS X 10.15.7 19H2 x86_64, locale zh-Hans-CN)
    • Flutter version 1.23.0-18.0.pre at /Users/changlei/Downloads/flutter
    • Framework revision 37ebe3d82a (7 days ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/changlei/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/changlei/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • iPad Pro (11-inch) (2nd generation) (mobile) • 84E523B2-614D-4645-9B55-546BF61B0A30 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                              • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web)                             • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

### LINKED ISSUE #68962: Adding tabs when starting from zero tabs causes LateInitializationError
After post this question in [Stackoverflow](https://stackoverflow.com/questions/64516441/flutter-error-occurred-when-add-tab-to-the-page?noredirect=1#comment114080502_64516441), it's seems that the issue I am facing might be a bug.

I have the following code that should display page with button to add tab in the page:

Edit (@shihaohong): I updated the sample to contain a minimal reproducible app. You will also need to turn on null-safety in your Flutter app on the `master` branch to see this error. You can do so by using `flutter run --enable-experiment=non-nullable`.

```flutter
import 'package:flutter/material.dart';
void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with TickerProviderStateMixin {
  List<String> tabTitles = [];
  List<Widget> tabContents = [];
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: tabContents.length, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  void _onTabAdd(int index) {
    setState(() {
      tabTitles.add("Tab ${tabTitles.length}");
      tabContents.add(
        Container(
          color: Colors.red,
          height: 200,
          width: 200,
        ),
      );
      _tabController = TabController(length: tabContents.length, vsync: this);
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('DataTable of Gene Lists'),
          centerTitle: true,
          actions: [
            FlatButton(
              child: Text('+'),
              onPressed: () => _onTabAdd(_tabController.index),
            ),
          ],
          bottom: PreferredSize(
            preferredSize: Size.fromHeight(40.0),
            child: Expanded(
              child: TabBar(
                controller: _tabController,
                tabs: tabTitles
                  .map((title) => Tab(text: title))
                  .toList(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

When I click this button the content seems to load successfully, but the problem is that the title is not shown, and the following error is displayed as you can see in the picture:
Philadelphia's Magic Gardens. This place was so cool!

It's important to tell that it happened after I updated to the last version of Flutter (before it worked with no problem).
I don't know what was the previous version, but the current version is:
```
Flutter 1.24.0-4.0.pre.51 • channel master • https://github.com/flutter/flutter.git
Framework • revision 720dff6a94 (9 hours ago) • 2020-10-24 03:57:03 -0400
Engine • revision 432974a52b
Tools • Dart 2.11.0 (build 2.11.0-251.0.dev)
```

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

When a TabBar is created with zero tabs, it is never laid out or painted. This is because it uses `Flex`, which will not perform layout or paint when it has an empty list of children. However, with the recent intro of null safety, this causes issues with dynamically updating tabs, because `_IndicatorPainter._currentTabOffset` and `_IndicatorPainter._currentTextDirection` expects a non-null value, but they are only ever set if layout is called on `TabBar.tabs`.

This PR reintroduced allowing null `_currentTabOffset` and `_currentTextDirection` values, as well as documenting the meaning of a null `_IndicatorPainter._currentTabOffset` and `_IndicatorPainter._currentTextDirection` value.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/68962
Fixes https://github.com/flutter/flutter/issues/68586
Closes https://github.com/flutter/flutter/issues/40014

## Tests

I added the following tests:

A test checking to make sure dynamically moving from zero to one and one to zero tabs does not throw an error.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -426,13 +430,14 @@ class _IndicatorPainter extends CustomPainter {
     _painter!.paint(canvas, _currentRect!.topLeft, configuration);
   }
 
-  static bool _tabOffsetsEqual(List<double> a, List<double> b) {
-    // TODO(shihaohong): The following null check should be replaced when a fix
-    // for https://github.com/flutter/flutter/issues/40014 is available.
-    if (a == null || b == null || a.length != b.length)
+  static bool _tabOffsetsEqual(List<double>? a, List<double>? b) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/tabs.dart:433]: you can use listEquals from foundation.dart

**Review by chunhtai — APPROVED** [review]
LGTM
