### PR TITLE
[flutter_tools] handle case where file is deleted by other program or running on read only volume

### LINKED ISSUE #57950: [tool_crash] FileSystemException: Deletion failed, path = '/Volumes/SD256/Github/flutter_module/build/ios/iphoneos/Runner.app' (OS Error: No such file or directory, errno = 2)
## Command
```
flutter build ios --release
```

## Steps to Reproduce
1. Create a new Flutter module, according to https://flutter.dev/docs/development/add-to-app/ios/project-setup
2. Build iOS version (debug mode by default), integrated it into existing app, added call to Flutter module, run the app in a simulator, everything worked OK
3. Run Fastlane build (this is what we are using for CI/CD), got error that Flutter needs to run in release mode or have FLUTTER_BUILD_MODE = release.
4. Try rebuilding Flutter module using 'flutter build ios -- release'. Every second run it fails with the error "FileSystemException, path ... OS Error: No such file or directory"
5. Also, even after successful running release build manually, fastlane still fails

## Logs
FileSystemException: FileSystemException: Deletion failed, path = '/Volumes/SD256/Github/flutter_module/build/ios/iphoneos/Runner.app' (OS Error: No such file or directory, errno = 2)
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:208:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:460:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:385:41)
<asynchronous suspension>
#4      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:83:43)
#5      _rootRunUnary (dart:async/zone.dart:1192:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#13     ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
```
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.1 19B88, locale en-CA)
    • Flutter version 1.17.1 at ~/flutter
    • Framework revision f7a6a7906b (13 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at ~/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: ~/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at ~/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone 6s • A906D945-1904-4A95-8EBB-EC8E080ADA77 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.***.flutter_module
**iOS bundle identifier**: com.***.flutterModule
**Creation channel**: stable
**Creation framework version**: f7a6a7906be96d2288f5d63a5a54c515a6e987fe

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

I've seen some odd bugs in crash reporting where the tool fails to delete a file that it just checked does exist. It could be that a different program was deleting the file and the timing was just right. Be defensive to this and test on an OSError of 2 if it still exists. If it does, then it is probably pointing at a read-only volume

Fixes https://github.com/flutter/flutter/issues/57950

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/file_system.dart [hunk 1]
```diff
@@ -17,6 +17,40 @@ import 'signals.dart';
 // the tool is killed by a signal.
 export 'package:file/file.dart';
 
+extension FileUtils on File {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/base/file_system.dart:20]: Not in love with the extension method, but I don't want to re-type everything as ErrorHandling file.

Maybe just a static helper method?

Comment (zanderso) [inline packages/flutter_tools/lib/src/base/file_system.dart:20]: Does this extension apply to every class that extends or implements `File`, or does it apply *only* to exactly `File`? Either way, it is probably worth a comment here.

File: packages/flutter_tools/test/general.shard/base/file_system_test.dart [hunk 2]
```diff
@@ -57,6 +58,44 @@ void main() {
     });
   });
 
+  testWithoutContext('deleteIfExists does not delete if file does not exist', () {
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/base/file_system_test.dart:61]: If the extension method applies to any implementation of `File`, then we need test coverage of how it applies to them.

File: packages/flutter_tools/lib/src/base/file_system.dart [hunk 3]
```diff
@@ -17,6 +17,40 @@ import 'signals.dart';
...
+  /// This method should be prefered to checking if it exists and
+  /// then deleting, because it handles the edge case where the file is
+  /// deleted by a different program between the two calls.
+  bool deleteIfExists({bool recursive = false}) {
+    if (!existsSync()) {
+      return false;
+    }
+    try {
+      deleteSync(recursive: recursive);
+    } on FileSystemException catch (err) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/file_system.dart:33]: If `File` is an `ErrorHandlingFile`, then you could get either a `ToolExit` or an `Exception` here depending on whether you're under a `noExitOnFailure`.

File: packages/flutter_tools/lib/src/base/file_system.dart [hunk 4]
```diff
@@ -17,6 +17,40 @@ import 'signals.dart';
...
+      // Certain error codes indicate the file could not be found. It could have
+      // been deleted by a different program while the tool was running.
+      // if it still exists, the file likely exists on a read-only volume.
+      // This error code is the same across linux, windows, and macOS.
+      const int kSystemCannotFindFile = 2;
+      if (err?.osError?.errorCode != kSystemCannotFindFile) {
+        rethrow;
+      }
+      if (existsSync()) {
+        throwToolExit(
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/file_system.dart:43]: This would subvert a `noExitOnFailure`.

**Review by zanderso — COMMENTED** [review]
Extension methods are a bit scary. Not saying it's the not the right thing here, but it looks like we need to be careful with them.

File: packages/flutter_tools/lib/src/base/file_system.dart (hunk 4 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/file_system.dart:43]: Thats true - this should probably become a static method on error handling file system - then that can be taken into account.

File: packages/flutter_tools/lib/src/base/file_system.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/file_system.dart:33]: The goal with this catch is to only intercept error code 2, which we don't catch with error handling io because it normally seems to indicate a tool error.

Any other exception types should pass through as is, though I will add support for the existing error ignoring logic

File: packages/flutter_tools/lib/src/base/file_system.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/file_system.dart]: Update to static method on ErrorHandlingFileSystem

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/file_system.dart]: Moved to ErrorHandlingFileSystem

File: packages/flutter_tools/lib/src/base/file_system.dart (hunk 4 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/file_system.dart]: Updated to support noExitOnFailure

**Comment by jonahwilliams** [comment]
Friendly ping @zanderso

File: packages/flutter_tools/lib/src/base/error_handling_io.dart [hunk 5]
```diff
@@ -63,6 +63,38 @@ class ErrorHandlingFileSystem extends ForwardingFileSystem {
     }
   }
 
+  /// Delete the file and return true if it exists, take no action and return
+  /// false if it does not.
+  ///
+  /// This method should be prefered to checking if it exists and
+  /// then deleting, because it handles the edge case where the file is
+  /// deleted by a different program between the two calls.
+  static bool deleteFileIfExists(File file, {bool recursive = false}) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/error_handling_io.dart:72]: How about:
```dart
static bool deleteIfExists(FileSystemEntity entity, ...) { ... }
```

Then it can handle directories and links as well.

File: packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart [hunk 6]
```diff
@@ -241,9 +242,7 @@ flutter_project:lib/
         toolExit: true,
       );
     } finally {
-      if (optionsFile.existsSync()) {
```
Comment (zanderso) [inline packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart:244]: How about replacing https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/src/common.dart#L34 and using that not just for directories but also for files?

**Review by zanderso — COMMENTED** [review]
Sorry for the delay.

File: packages/flutter_tools/lib/src/base/error_handling_io.dart [hunk 7]
```diff
@@ -63,6 +63,38 @@ class ErrorHandlingFileSystem extends ForwardingFileSystem {
...
+      return false;
+    }
+    try {
+      file.deleteSync(recursive: recursive);
+    } on FileSystemException catch (err) {
+      // Certain error codes indicate the file could not be found. It could have
+      // been deleted by a different program while the tool was running.
+      // if it still exists, the file likely exists on a read-only volume.
+      // This error code is the same across linux, windows, and macOS.
+      const int kSystemCannotFindFile = 2;
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:83]: For files it is the same, windows 2 is ERROR_FILE_NOT_FOUND, and 2 on linux/macOS  2 is ENOENT is No such file or directory. I can check if deleting a directory that does not exist uses the same error code on windows

File: packages/flutter_tools/lib/src/base/error_handling_io.dart (hunk 5 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:72]: Will check if these have the same error code on windows

File: packages/flutter_tools/lib/src/base/error_handling_io.dart (hunk 7 above)
[the remark this answers is not in the document]
Comment (zanderso) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:83]: kk. This would be good to have as a comment in the code here.

File: packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart (hunk 6 above)
Comment (jonahwilliams) [reply packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart:244]: That probably needs to be fixed too, but it is more for file lock issues on windows than read-only problems

File: packages/flutter_tools/lib/src/base/error_handling_io.dart (hunk 5 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart]: same error code for directories

File: packages/flutter_tools/lib/src/base/error_handling_io.dart (hunk 7 above)
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:85]: Made the comment more specific

File: packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart (hunk 6 above)
Comment (zanderso) [reply packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart:244]: So, the difference would be a different error code? The same code structure could handle the situation apart from that, though, right? Maybe not for this PR, but it would be nice to have a single way for the tool to try to delete something.

Comment (jonahwilliams) [reply packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart:244]: I think we would prefer if the tests shut down cleanly, and this was added as more of a stopgap

Comment (zanderso) [reply packages/flutter_tools/test/commands.shard/permeable/analyze_once_test.dart:244]: Ah, yeah. Good point.

**Review by zanderso — APPROVED** [review]
lgtm
