### PR TITLE
Make popup menu position configurable

### LINKED ISSUE #82067: PopupMenuButton: Menu is positioned directly over the button
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:
```dart
...

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: [
          // This menu button widget updates a _selection field (of type WhyFarther, not shown here).
          PopupMenuButton(
            itemBuilder: (BuildContext context) => <PopupMenuEntry>[
              const PopupMenuItem(
                child: Text('Working a lot harder'),
              ),
              const PopupMenuItem(
                child: Text('Being a lot smarter'),
              ),
              const PopupMenuItem(
                child: Text('Being a self-starter'),
              ),
              const PopupMenuItem(
                child: Text('Placed in charge of trading charter'),
              ),
            ],
          ),
        ],
      ),
...
```
3. `flutter run` and click the PopupMenuButton. 

**Expected results:** 
The menu should appear below the button as per the Material Design documentation:
https://material.io/components/menus/flutter#types
MD Menu

**Actual results:** 
The menu appears directly over the button.
	

<details>
  <summary>Logs</summary>

```
                        export PLATFORM_PRODUCT_BUILD_VERSION\=18E182
                        export PLIST_FILE_OUTPUT_FORMAT\=binary
                        export PLUGINS_FOLDER_PATH\=Runner.app/PlugIns
                        export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR\=YES
                        export
                        PRECOMP_DESTINATION_DIR\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noind
                        ex/Runner.build/Debug-iphonesimulator/Runner.build/PrefixHeaders
                        export PRESERVE_DEAD_CODE_INITS_AND_TERMS\=NO
                        export PRIVATE_HEADERS_FOLDER_PATH\=Runner.app/PrivateHeaders
                        export PRODUCT_BUNDLE_IDENTIFIER\=com.example.bug
                        export PRODUCT_BUNDLE_PACKAGE_TYPE\=APPL
                        export PRODUCT_MODULE_NAME\=Runner
                        export PRODUCT_NAME\=Runner
                        export PRODUCT_SETTINGS_PATH\=/Users/cpboyd/Documents/GitHub/bug/ios/Runner/Info.plist
                        export PRODUCT_TYPE\=com.apple.product-type.application
                        export PROFILING_CODE\=NO
                        export PROJECT\=Runner
                        export
                        PROJECT_DERIVED_FILE_DIR\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noin
                        dex/Runner.build/DerivedSources
                        export PROJECT_DIR\=/Users/cpboyd/Documents/GitHub/bug/ios
                        export PROJECT_FILE_PATH\=/Users/cpboyd/Documents/GitHub/bug/ios/Runner.xcodeproj
                        export PROJECT_NAME\=Runner
                        export
                        PROJECT_TEMP_DIR\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runn
                        er.build
                        export
                        PROJECT_TEMP_ROOT\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex
                        export PUBLIC_HEADERS_FOLDER_PATH\=Runner.app/Headers
                        export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS\=YES
                        export REMOVE_CVS_FROM_RESOURCES\=YES
                        export REMOVE_GIT_FROM_RESOURCES\=YES
                        export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES\=YES
                        export REMOVE_HG_FROM_RESOURCES\=YES
                        export REMOVE_SVN_FROM_RESOURCES\=YES
                        export
                        REZ_COLLECTOR_DIR\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Run
                        ner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources
                        export
                        REZ_OBJECTS_DIR\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runne
                        r.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources/Objects
                        export REZ_SEARCH_PATHS\=/Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator\ 
                        export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES\=NO
                        export SCRIPTS_FOLDER_PATH\=Runner.app/Scripts
                        export SCRIPT_INPUT_FILE_COUNT\=0
                        export SCRIPT_INPUT_FILE_LIST_COUNT\=0
                        export SCRIPT_OUTPUT_FILE_COUNT\=0
                        export SCRIPT_OUTPUT_FILE_LIST_COUNT\=0
                        export
                        SCRIPT_OUTPUT_STREAM_FILE\=/var/folders/v0/m8t66vt90z711gkgclc6q34h0000gn/T/flutter_tools.bZT087/flutter_build_log_pipe.dcRmvf/pipe_to_s
                        tdout
                        export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk
                        export SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk
                        export
                        SDK_DIR_iphonesimulator\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.
                        5.sdk
                        export
                        SDK_DIR_iphonesimulator14_5\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulato
                        r14.5.sdk
                        export SDK_NAME\=iphonesimulator14.5
                        export SDK_NAMES\=iphonesimulator14.5
                        export SDK_PRODUCT_BUILD_VERSION\=18E182
                        export SDK_VERSION\=14.5
                        export SDK_VERSION_ACTUAL\=140500
                        export SDK_VERSION_MAJOR\=140000
                        export SDK_VERSION_MINOR\=140500
                        export SED\=/usr/bin/sed
                        export SEPARATE_STRIP\=NO
                        export SEPARATE_SYMBOL_EDIT\=NO
                        export SET_DIR_MODE_OWNER_GROUP\=YES
                        export SET_FILE_MODE_OWNER_GROUP\=NO
                        export SHALLOW_BUNDLE\=YES
                        export SHARED_DERIVED_FILE_DIR\=/Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/DerivedSources
                        export SHARED_FRAMEWORKS_FOLDER_PATH\=Runner.app/SharedFrameworks
                        export
                        SHARED_PRECOMPS_DIR\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/P
                        recompiledHeaders
                        export SHARED_SUPPORT_FOLDER_PATH\=Runner.app/SharedSupport
                        export SKIP_INSTALL\=NO
                        export SOURCE_ROOT\=/Users/cpboyd/Documents/GitHub/bug/ios
                        export SRCROOT\=/Users/cpboyd/Documents/GitHub/bug/ios
                        export STRINGS_FILE_INFOPLIST_RENAME\=YES
                        export STRINGS_FILE_OUTPUT_ENCODING\=binary
                        export STRIP_BITCODE_FROM_COPIED_FILES\=NO
                        export STRIP_INSTALLED_PRODUCT\=YES
                        export STRIP_STYLE\=all
                        export STRIP_SWIFT_SYMBOLS\=YES
                        export SUPPORTED_DEVICE_FAMILIES\=1,2
                        export SUPPORTED_PLATFORMS\=iphoneos\ iphonesimulator
                        export SUPPORTS_TEXT_BASED_API\=NO
                        export SWIFT_OBJC_BRIDGING_HEADER\=Runner/Runner-Bridging-Header.h
                        export SWIFT_OPTIMIZATION_LEVEL\=-Onone
                        export SWIFT_PLATFORM_TARGET_PREFIX\=ios
                        export
                        SWIFT_RESPONSE_FILE_PATH_normal_x86_64\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Inte
                        rmediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.SwiftFileList
                        export SWIFT_VERSION\=5.0
                        export SYMROOT\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Products
                        export SYSTEM_ADMIN_APPS_DIR\=/Applications/Utilities
                        export SYSTEM_APPS_DIR\=/Applications
                        export SYSTEM_CORE_SERVICES_DIR\=/System/Library/CoreServices
                        export SYSTEM_DEMOS_DIR\=/Applications/Extras
                        export SYSTEM_DEVELOPER_APPS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications
                        export SYSTEM_DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/usr/bin
                        export SYSTEM_DEVELOPER_DEMOS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built\ Examples
                        export SYSTEM_DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
                        export SYSTEM_DEVELOPER_DOC_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library
                        export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Graphics\ Tools
                        export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Java\ Tools
                        export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Performance\ Tools
                        export SYSTEM_DEVELOPER_RELEASENOTES_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/releasenotes
                        export SYSTEM_DEVELOPER_TOOLS\=/Applications/Xcode.app/Contents/Developer/Tools
                        export SYSTEM_DEVELOPER_TOOLS_DOC_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/documentation/DeveloperTools
                        export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\
                        Library/releasenotes/DeveloperTools
                        export SYSTEM_DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
                        export SYSTEM_DEVELOPER_UTILITIES_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
                        export SYSTEM_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
                        export SYSTEM_DOCUMENTATION_DIR\=/Library/Documentation
                        export SYSTEM_KEXT_INSTALL_PATH\=/System/Library/Extensions
                        export SYSTEM_LIBRARY_DIR\=/System/Library
                        export TAPI_VERIFY_MODE\=ErrorsOnly
                        export TARGETED_DEVICE_FAMILY\=1,2
                        export TARGETNAME\=Runner
                        export TARGET_BUILD_DIR\=/Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator
                        export TARGET_DEVICE_IDENTIFIER\=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder
                        export TARGET_DEVICE_PLATFORM_NAME\=iphonesimulator
                        export TARGET_NAME\=Runner
                        export
                        TARGET_TEMP_DIR\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runne
                        r.build/Debug-iphonesimulator/Runner.build
                        export
                        TEMP_DIR\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build
                        /Debug-iphonesimulator/Runner.build
                        export
                        TEMP_FILES_DIR\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner
                        .build/Debug-iphonesimulator/Runner.build
                        export
                        TEMP_FILE_DIR\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.
                        build/Debug-iphonesimulator/Runner.build
                        export TEMP_ROOT\=/Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex
                        export TEST_FRAMEWORK_SEARCH_PATHS\=\
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks\
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/Developer/Library/F
                        rameworks
                        export TEST_LIBRARY_SEARCH_PATHS\=\ /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib
                        export TOOLCHAINS\=com.apple.dt.toolchain.XcodeDefault
                        export TOOLCHAIN_DIR\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
                        export TRACK_WIDGET_CREATION\=true
                        export TREAT_MISSING_BASELINES_AS_TEST_FAILURES\=NO
                        export TREE_SHAKE_ICONS\=false
                        export TeamIdentifierPrefix\=PRMYS7FUAY.
                        export UID\=501
                        export UNLOCALIZED_RESOURCES_FOLDER_PATH\=Runner.app
                        export UNSTRIPPED_PRODUCT\=NO
                        export USER\=cpboyd
                        export USER_APPS_DIR\=/Users/cpboyd/Applications
                        export USER_LIBRARY_DIR\=/Users/cpboyd/Library
                        export USE_DYNAMIC_NO_PIC\=YES
                        export USE_HEADERMAP\=YES
                        export USE_HEADER_SYMLINKS\=NO
                        export USE_LLVM_TARGET_TRIPLES\=YES
                        export USE_LLVM_TARGET_TRIPLES_FOR_CLANG\=YES
                        export USE_LLVM_TARGET_TRIPLES_FOR_LD\=YES
                        export USE_LLVM_TARGET_TRIPLES_FOR_TAPI\=YES
                        export VALIDATE_DEVELOPMENT_ASSET_PATHS\=YES_ERROR
                        export VALIDATE_PRODUCT\=NO
                        export VALIDATE_WORKSPACE\=YES_ERROR
                        export VALID_ARCHS\=arm64\ arm64e\ i386\ x86_64
                        export VERBOSE_PBXCP\=NO
                        export VERBOSE_SCRIPT_LOGGING\=YES
                        export VERSIONING_SYSTEM\=apple-generic
                        export VERSIONPLIST_PATH\=Runner.app/version.plist
                        export VERSION_INFO_BUILDER\=cpboyd
                        export VERSION_INFO_FILE\=Runner_vers.c
                        export VERSION_INFO_STRING\=\"@\(\#\)PROGRAM:Runner\ \ PROJECT:Runner-1\"
                        export WRAPPER_EXTENSION\=app
                        export WRAPPER_NAME\=Runner.app
                        export WRAPPER_SUFFIX\=.app
                        export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES\=NO
                        export XCODE_APP_SUPPORT_DIR\=/Applications/Xcode.app/Contents/Developer/Library/Xcode
                        export XCODE_PRODUCT_BUILD_VERSION\=12E262
                        export XCODE_VERSION_ACTUAL\=1250
                        export XCODE_VERSION_MAJOR\=1200
                        export XCODE_VERSION_MINOR\=1250
                        export XPCSERVICES_FOLDER_PATH\=Runner.app/XPCServices
                        export YACC\=yacc
                        export arch\=undefined_arch
                        export variant\=normal
                        /bin/sh -c
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh
                    ♦ mkdir -p -- /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
                    ♦ rsync -av --delete --filter - .DS_Store /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/App.framework
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
                    building file list ... done
                    App.framework/
                    App.framework/App
                    App.framework/_CodeSignature/CodeResources
                    App.framework/flutter_assets/AssetManifest.json
                    App.framework/flutter_assets/FontManifest.json
                    App.framework/flutter_assets/NOTICES
                    App.framework/flutter_assets/kernel_blob.bin

                    sent 35752421 bytes  received 158 bytes  71505158.00 bytes/sec
                    total size is 41530280  speedup is 1.16
                    ♦ rsync -av --delete --filter - .DS_Store /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Flutter.framework
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/
                    building file list ... done

                    sent 631 bytes  received 20 bytes  1302.00 bytes/sec
                    total size is 38637883  speedup is 59351.59
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Info.plist: Could not extract value, error: No value at that
                    key path or invalid key path: NSBonjourServices
                    ♦ plutil -insert NSBonjourServices -json ["_dartobservatory._tcp"]
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Info.plist
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Info.plist: Could not extract value, error: No value at that
                    key path or invalid key path: NSLocalNetworkUsageDescription
                    ♦ plutil -insert NSLocalNetworkUsageDescription -string Allow Flutter tools on your computer to connect and debug your application. This
                    prompt will not appear on release builds. /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Info.plist

                    CopySwiftLibs /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app (in target 'Runner' from project 'Runner')
                        cd /Users/cpboyd/Documents/GitHub/bug/ios
                        export CODESIGN_ALLOCATE\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
                        export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
                        export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk
                        builtin-swiftStdLibTool --copy --verbose --sign - --scan-executable
                        /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Runner --scan-folder
                        /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks --scan-folder
                        /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/PlugIns --platform iphonesimulator --toolchain
                        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain --destination
                        /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks --strip-bitcode --strip-bitcode-tool
                        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip --emit-dependency-info
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/SwiftStdLibToolInputDependencies.dep
                    libswiftObjectiveC.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
                    libswiftCoreMedia.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib
                    libswiftUIKit.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib
                    libswiftCoreGraphics.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
                    libswiftos.dylib is up to date at /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib
                    libswiftMetal.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib
                    libswiftCoreImage.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib
                    libswiftQuartzCore.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib
                    libswiftFoundation.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
                    libswiftCore.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
                    libswiftCoreAudio.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib
                    libswiftDarwin.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
                    libswiftDispatch.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
                    libswiftCoreFoundation.dylib is up to date at
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftObjectiveC.dylib is
                    unchanged; keeping original
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib
                    /usr/bin/codesign -r- --display /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib
                    /usr/bin/codesign -r- --display /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
                    /usr/bin/codesign -r- --display /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib
                    /usr/bin/codesign -r- --display /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreImage.dylib is
                    unchanged; keeping original
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib
                    /usr/bin/codesign -r- --display /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftos.dylib is unchanged;
                    keeping original
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib
                    Codesigning /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
                    /usr/bin/codesign --force --sign - --verbose
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDispatch.dylib is
                    unchanged; keeping original
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreAudio.dylib is
                    unchanged; keeping original
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib
                    /usr/bin/codesign -r- --display /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreMedia.dylib is
                    unchanged; keeping original
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib
                    /usr/bin/codesign -r- --display /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftUIKit.dylib is unchanged;
                    keeping original
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftMetal.dylib is unchanged;
                    keeping original
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftDarwin.dylib is
                    unchanged; keeping original
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftQuartzCore.dylib is
                    unchanged; keeping original
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreGraphics.dylib is
                    unchanged; keeping original
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCoreFoundation.dylib is
                    unchanged; keeping original
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
                    /usr/bin/codesign -r- --display
                    /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftFoundation.dylib is
                    unchanged; keeping original
                    Probing signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
                    /usr/bin/codesign -r- --display /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib
                    Code signature of /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/libswiftCore.dylib is unchanged;
                    keeping original

                    CodeSign /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app (in target 'Runner' from project 'Runner')
                        cd /Users/cpboyd/Documents/GitHub/bug/ios
                        export CODESIGN_ALLOCATE\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate

                        Signing Identity:     "-"

                        /usr/bin/codesign --force --sign - --entitlements
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/Runner.app.xcent --timestamp\=none
                        /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app

                    ** BUILD SUCCEEDED **
[ +192 ms]  └─Compiling, linking and signing... (completed in 3.4s)
[   +1 ms] Xcode build done.                                           17.4s
[   +1 ms] executing: [/Users/cpboyd/Documents/GitHub/bug/ios/] xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace
-scheme Runner BUILD_DIR=/Users/cpboyd/Documents/GitHub/bug/build/ios -sdk iphonesimulator
SCRIPT_OUTPUT_STREAM_FILE=/var/folders/v0/m8t66vt90z711gkgclc6q34h0000gn/T/flutter_tools.bZT087/flutter_build_log_pipe.dcRmvf/pipe_to_stdout
FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
[        ] executing: [/Users/cpboyd/Documents/GitHub/bug/ios/] xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace
-scheme Runner BUILD_DIR=/Users/cpboyd/Documents/GitHub/bug/build/ios -sdk iphonesimulator
SCRIPT_OUTPUT_STREAM_FILE=/var/folders/v0/m8t66vt90z711gkgclc6q34h0000gn/T/flutter_tools.bZT087/flutter_build_log_pipe.dcRmvf/pipe_to_stdout
FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
[+1793 ms] Command line invocation:
                        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace
                        Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/cpboyd/Documents/GitHub/bug/build/ios -sdk iphonesimulator
                        SCRIPT_OUTPUT_STREAM_FILE=/var/folders/v0/m8t66vt90z711gkgclc6q34h0000gn/T/flutter_tools.bZT087/flutter_build_log_pipe.dcRmvf/pipe_to_st
                        dout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings

                    User defaults from command line:
                        IDEPackageSupportUseBuiltinSCM = YES

                    Build settings from command line:
                        BUILD_DIR = /Users/cpboyd/Documents/GitHub/bug/build/ios
                        COMPILER_INDEX_STORE_ENABLE = NO
                        FLUTTER_SUPPRESS_ANALYTICS = true
                        SCRIPT_OUTPUT_STREAM_FILE =
                        /var/folders/v0/m8t66vt90z711gkgclc6q34h0000gn/T/flutter_tools.bZT087/flutter_build_log_pipe.dcRmvf/pipe_to_stdout
                        SDKROOT = iphonesimulator14.5
                        VERBOSE_SCRIPT_LOGGING = YES

                    Build settings for action build and target Runner:
                        ACTION = build
                        AD_HOC_CODE_SIGNING_ALLOWED = YES
                        ALTERNATE_GROUP = staff
                        ALTERNATE_MODE = u+w,go-w,a+rX
                        ALTERNATE_OWNER = cpboyd
                        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO
                        ALWAYS_SEARCH_USER_PATHS = NO
                        ALWAYS_USE_SEPARATE_HEADERMAPS = NO
                        APPLE_INTERNAL_DEVELOPER_DIR = /AppleInternal/Developer
                        APPLE_INTERNAL_DIR = /AppleInternal
                        APPLE_INTERNAL_DOCUMENTATION_DIR = /AppleInternal/Documentation
                        APPLE_INTERNAL_LIBRARY_DIR = /AppleInternal/Library
                        APPLE_INTERNAL_TOOLS = /AppleInternal/Developer/Tools
                        APPLICATION_EXTENSION_API_ONLY = NO
                        APPLY_RULES_IN_COPY_FILES = NO
                        APPLY_RULES_IN_COPY_HEADERS = NO
                        ARCHS = x86_64
                        ARCHS_STANDARD = arm64 x86_64 i386
                        ARCHS_STANDARD_32_64_BIT = arm64 i386 x86_64
                        ARCHS_STANDARD_32_BIT = i386
                        ARCHS_STANDARD_64_BIT = arm64 x86_64
                        ARCHS_STANDARD_INCLUDING_64_BIT = arm64 x86_64 i386
                        ARCHS_UNIVERSAL_IPHONE_OS = arm64 i386 x86_64
                        ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
                        AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator
                        BITCODE_GENERATION_MODE = marker
                        BUILD_ACTIVE_RESOURCES_ONLY = NO
                        BUILD_COMPONENTS = headers build
                        BUILD_DIR = /Users/cpboyd/Documents/GitHub/bug/build/ios
                        BUILD_LIBRARY_FOR_DISTRIBUTION = NO
                        BUILD_ROOT = /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Products
                        BUILD_STYLE = 
                        BUILD_VARIANTS = normal
                        BUILT_PRODUCTS_DIR = /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator
                        BUNDLE_CONTENTS_FOLDER_PATH_deep = Contents/
                        BUNDLE_EXECUTABLE_FOLDER_NAME_deep = MacOS
                        BUNDLE_FORMAT = shallow
                        BUNDLE_FRAMEWORKS_FOLDER_PATH = Frameworks
                        BUNDLE_PLUGINS_FOLDER_PATH = PlugIns
                        BUNDLE_PRIVATE_HEADERS_FOLDER_PATH = PrivateHeaders
                        BUNDLE_PUBLIC_HEADERS_FOLDER_PATH = Headers
                        CACHE_ROOT = /var/folders/v0/m8t66vt90z711gkgclc6q34h0000gn/C/com.apple.DeveloperTools/12.5-12E262/Xcode
                        CCHROOT = /var/folders/v0/m8t66vt90z711gkgclc6q34h0000gn/C/com.apple.DeveloperTools/12.5-12E262/Xcode
                        CHMOD = /bin/chmod
                        CHOWN = /usr/sbin/chown
                        CLANG_ANALYZER_NONNULL = YES
                        CLANG_CXX_LANGUAGE_STANDARD = gnu++0x
                        CLANG_CXX_LIBRARY = libc++
                        CLANG_ENABLE_MODULES = YES
                        CLANG_ENABLE_OBJC_ARC = YES
                        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
                        CLANG_WARN_BOOL_CONVERSION = YES
                        CLANG_WARN_COMMA = YES
                        CLANG_WARN_CONSTANT_CONVERSION = YES
                        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES
                        CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR
                        CLANG_WARN_EMPTY_BODY = YES
                        CLANG_WARN_ENUM_CONVERSION = YES
                        CLANG_WARN_INFINITE_RECURSION = YES
                        CLANG_WARN_INT_CONVERSION = YES
                        CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
                        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES
                        CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
                        CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR
                        CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
                        CLANG_WARN_STRICT_PROTOTYPES = YES
                        CLANG_WARN_SUSPICIOUS_MOVE = YES
                        CLANG_WARN_UNREACHABLE_CODE = YES
                        CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
                        CLASS_FILE_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/JavaClasses
                        CLEAN_PRECOMPS = YES
                        CLONE_HEADERS = NO
                        COCOAPODS_PARALLEL_CODE_SIGN = true
                        CODESIGNING_FOLDER_PATH = /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app
                        CODE_SIGNING_ALLOWED = YES
                        CODE_SIGNING_REQUIRED = YES
                        CODE_SIGN_CONTEXT_CLASS = XCiPhoneSimulatorCodeSignContext
                        CODE_SIGN_IDENTITY = -
                        CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
                        COLOR_DIAGNOSTICS = NO
                        COMBINE_HIDPI_IMAGES = NO
                        COMPILER_INDEX_STORE_ENABLE = NO
                        COMPOSITE_SDK_DIRS =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/CompositeSDKs
                        COMPRESS_PNG_FILES = YES
                        CONFIGURATION = Debug
                        CONFIGURATION_BUILD_DIR = /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator
                        CONFIGURATION_TEMP_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator
                        CONTENTS_FOLDER_PATH = Runner.app
                        COPYING_PRESERVES_HFS_DATA = NO
                        COPY_HEADERS_RUN_UNIFDEF = NO
                        COPY_PHASE_STRIP = NO
                        COPY_RESOURCES_FROM_STATIC_FRAMEWORKS = YES
                        CORRESPONDING_DEVICE_PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
                        CORRESPONDING_DEVICE_PLATFORM_NAME = iphoneos
                        CORRESPONDING_DEVICE_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk
                        CORRESPONDING_DEVICE_SDK_NAME = iphoneos14.5
                        CP = /bin/cp
                        CREATE_INFOPLIST_SECTION_IN_BINARY = NO
                        CURRENT_ARCH = x86_64
                        CURRENT_PROJECT_VERSION = 1
                        CURRENT_VARIANT = normal
                        DART_DEFINES = RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==
                        DART_OBFUSCATION = false
                        DEAD_CODE_STRIPPING = YES
                        DEBUGGING_SYMBOLS = YES
                        DEBUG_INFORMATION_FORMAT = dwarf
                        DEFAULT_COMPILER = com.apple.compilers.llvm.clang.1_0
                        DEFAULT_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
                        DEFAULT_KEXT_INSTALL_PATH = /System/Library/Extensions
                        DEFINES_MODULE = NO
                        DEPLOYMENT_LOCATION = NO
                        DEPLOYMENT_POSTPROCESSING = NO
                        DEPLOYMENT_TARGET_CLANG_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
                        DEPLOYMENT_TARGET_CLANG_FLAG_NAME = mios-simulator-version-min
                        DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX = -mios-simulator-version-min=
                        DEPLOYMENT_TARGET_LD_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
                        DEPLOYMENT_TARGET_LD_FLAG_NAME = ios_simulator_version_min
                        DEPLOYMENT_TARGET_SETTING_NAME = IPHONEOS_DEPLOYMENT_TARGET
                        DEPLOYMENT_TARGET_SUGGESTED_VALUES = 9.0 9.2 10.0 10.2 11.0 11.2 11.4 12.1 12.3 13.0 13.2 13.4 13.6 14.1 14.3 14.5
                        DERIVED_FILES_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/DerivedSources
                        DERIVED_FILE_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/DerivedSources
                        DERIVED_SOURCES_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/DerivedSources
                        DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
                        DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
                        DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
                        DEVELOPER_FRAMEWORKS_DIR = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
                        DEVELOPER_FRAMEWORKS_DIR_QUOTED = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
                        DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/Developer/Library
                        DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
                        DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Tools
                        DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
                        DEVELOPMENT_LANGUAGE = en
                        DOCUMENTATION_FOLDER_PATH = Runner.app/en.lproj/Documentation
                        DONT_GENERATE_INFOPLIST_FILE = NO
                        DO_HEADER_SCANNING_IN_JAM = NO
                        DSTROOT = /tmp/Runner.dst
                        DT_TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
                        DWARF_DSYM_FILE_NAME = Runner.app.dSYM
                        DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
                        DWARF_DSYM_FOLDER_PATH = /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator
                        EFFECTIVE_PLATFORM_NAME = -iphonesimulator
                        EMBEDDED_CONTENT_CONTAINS_SWIFT = NO
                        EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE = NO
                        ENABLE_BITCODE = NO
                        ENABLE_DEFAULT_HEADER_SEARCH_PATHS = YES
                        ENABLE_HARDENED_RUNTIME = NO
                        ENABLE_HEADER_DEPENDENCIES = YES
                        ENABLE_ON_DEMAND_RESOURCES = YES
                        ENABLE_STRICT_OBJC_MSGSEND = YES
                        ENABLE_TESTABILITY = YES
                        ENABLE_TESTING_SEARCH_PATHS = NO
                        ENTITLEMENTS_DESTINATION = __entitlements
                        ENTITLEMENTS_REQUIRED = YES
                        EXCLUDED_ARCHS = arm64 i386
                        EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS = .DS_Store .svn .git .hg CVS
                        EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES = *.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg
                        *.pbproj *.pbxproj
                        EXECUTABLES_FOLDER_PATH = Runner.app/Executables
                        EXECUTABLE_FOLDER_PATH = Runner.app
                        EXECUTABLE_NAME = Runner
                        EXECUTABLE_PATH = Runner.app/Runner
                        EXPANDED_CODE_SIGN_IDENTITY = 
                        EXPANDED_CODE_SIGN_IDENTITY_NAME = 
                        EXPANDED_PROVISIONING_PROFILE = 
                        FILE_LIST =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/Objects/LinkFileList
                        FIXED_FILES_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/FixedFiles
                        FLUTTER_APPLICATION_PATH = /Users/cpboyd/Documents/GitHub/bug
                        FLUTTER_BUILD_DIR = build
                        FLUTTER_BUILD_NAME = 1.0.0
                        FLUTTER_BUILD_NUMBER = 1
                        FLUTTER_ROOT = /Users/cpboyd/dev/flutter
                        FLUTTER_SUPPRESS_ANALYTICS = true
                        FLUTTER_TARGET = /Users/cpboyd/Documents/GitHub/bug/lib/main.dart
                        FRAMEWORKS_FOLDER_PATH = Runner.app/Frameworks
                        FRAMEWORK_FLAG_PREFIX = -framework
                        FRAMEWORK_VERSION = A
                        FULL_PRODUCT_NAME = Runner.app
                        GCC3_VERSION = 3.3
                        GCC_C_LANGUAGE_STANDARD = gnu99
                        GCC_DYNAMIC_NO_PIC = NO
                        GCC_INLINES_ARE_PRIVATE_EXTERN = YES
                        GCC_NO_COMMON_BLOCKS = YES
                        GCC_OBJC_LEGACY_DISPATCH = YES
                        GCC_OPTIMIZATION_LEVEL = 0
                        GCC_PFE_FILE_C_DIALECTS = c objective-c c++ objective-c++
                        GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1 
                        GCC_SYMBOLS_PRIVATE_EXTERN = NO
                        GCC_TREAT_WARNINGS_AS_ERRORS = NO
                        GCC_VERSION = com.apple.compilers.llvm.clang.1_0
                        GCC_VERSION_IDENTIFIER = com_apple_compilers_llvm_clang_1_0
                        GCC_WARN_64_TO_32_BIT_CONVERSION = YES
                        GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR
                        GCC_WARN_UNDECLARED_SELECTOR = YES
                        GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE
                        GCC_WARN_UNUSED_FUNCTION = YES
                        GCC_WARN_UNUSED_VARIABLE = YES
                        GENERATED_MODULEMAP_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/GeneratedModuleMaps-ip
                        honesimulator
                        GENERATE_MASTER_OBJECT_FILE = NO
                        GENERATE_PKGINFO_FILE = YES
                        GENERATE_PROFILING_CODE = NO
                        GENERATE_TEXT_BASED_STUBS = NO
                        GID = 20
                        GROUP = staff
                        HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT = YES
                        HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES = YES
                        HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS = YES
                        HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
                        HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
                        HEADERMAP_USES_VFS = NO
                        HIDE_BITCODE_SYMBOLS = YES
                        HOME = /Users/cpboyd
                        ICONV = /usr/bin/iconv
                        INFOPLIST_EXPAND_BUILD_SETTINGS = YES
                        INFOPLIST_FILE = Runner/Info.plist
                        INFOPLIST_OUTPUT_FORMAT = binary
                        INFOPLIST_PATH = Runner.app/Info.plist
                        INFOPLIST_PREPROCESS = NO
                        INFOSTRINGS_PATH = Runner.app/en.lproj/InfoPlist.strings
                        INLINE_PRIVATE_FRAMEWORKS = NO
                        INSTALLHDRS_COPY_PHASE = NO
                        INSTALLHDRS_SCRIPT_PHASE = NO
                        INSTALL_DIR = /tmp/Runner.dst/Applications
                        INSTALL_GROUP = staff
                        INSTALL_MODE_FLAG = u+w,go-w,a+rX
                        INSTALL_OWNER = cpboyd
                        INSTALL_PATH = /Applications
                        INSTALL_ROOT = /tmp/Runner.dst
                        IPHONEOS_DEPLOYMENT_TARGET = 9.0
                        JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8
                        JAVA_APP_STUB = /System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
                        JAVA_ARCHIVE_CLASSES = YES
                        JAVA_ARCHIVE_TYPE = JAR
                        JAVA_COMPILER = /usr/bin/javac
                        JAVA_FOLDER_PATH = Runner.app/Java
                        JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
                        JAVA_JAR_FLAGS = cv
                        JAVA_SOURCE_SUBDIR = .
                        JAVA_USE_DEPENDENCIES = YES
                        JAVA_ZIP_FLAGS = -urg
                        JIKES_DEFAULT_FLAGS = +E +OLDCSO
                        KEEP_PRIVATE_EXTERNS = NO
                        LD_DEPENDENCY_INFO_FILE =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat
                        LD_GENERATE_MAP_FILE = NO
                        LD_MAP_FILE_PATH =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/Runner-LinkMap-normal-x86_64.txt
                        LD_NO_PIE = NO
                        LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
                        LD_RUNPATH_SEARCH_PATHS =  @executable_path/Frameworks
                        LEGACY_DEVELOPER_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
                        LEX = lex
                        LIBRARY_DEXT_INSTALL_PATH = /Library/DriverExtensions
                        LIBRARY_FLAG_NOSPACE = YES
                        LIBRARY_FLAG_PREFIX = -l
                        LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
                        LINKER_DISPLAYS_MANGLED_NAMES = NO
                        LINK_FILE_LIST_normal_x86_64 = 
                        LINK_WITH_STANDARD_LIBRARIES = YES
                        LLVM_TARGET_TRIPLE_OS_VERSION = ios9.0
                        LLVM_TARGET_TRIPLE_SUFFIX = -simulator
                        LLVM_TARGET_TRIPLE_VENDOR = apple
                        LOCALIZABLE_CONTENT_DIR = 
                        LOCALIZATION_EXPORT_SUPPORTED = YES
                        LOCALIZED_RESOURCES_FOLDER_PATH = Runner.app/en.lproj
                        LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString CFCopyLocalizedString
                        LOCALIZED_STRING_SWIFTUI_SUPPORT = YES
                        LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
                        LOCAL_APPS_DIR = /Applications
                        LOCAL_DEVELOPER_DIR = /Library/Developer
                        LOCAL_LIBRARY_DIR = /Library
                        LOCROOT = 
                        LOCSYMROOT = 
                        MACH_O_TYPE = mh_execute
                        MAC_OS_X_PRODUCT_BUILD_VERSION = 20E241
                        MAC_OS_X_VERSION_ACTUAL = 110301
                        MAC_OS_X_VERSION_MAJOR = 110000
                        MAC_OS_X_VERSION_MINOR = 110300
                        METAL_LIBRARY_FILE_BASE = default
                        METAL_LIBRARY_OUTPUT_DIR = /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app
                        MODULES_FOLDER_PATH = Runner.app/Modules
                        MODULE_CACHE_DIR = /Users/cpboyd/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
                        MTL_ENABLE_DEBUG_INFO = YES
                        NATIVE_ARCH = x86_64
                        NATIVE_ARCH_32_BIT = i386
                        NATIVE_ARCH_64_BIT = x86_64
                        NATIVE_ARCH_ACTUAL = x86_64
                        NO_COMMON = YES
                        OBJC_ABI_VERSION = 2
                        OBJECT_FILE_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/Objects
                        OBJECT_FILE_DIR_normal =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/Objects-normal
                        OBJROOT = /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex
                        ONLY_ACTIVE_ARCH = YES
                        OS = MACOS
                        OSAC = /usr/bin/osacompile
                        PACKAGE_CONFIG = /Users/cpboyd/Documents/GitHub/bug/.dart_tool/package_config.json
                        PACKAGE_TYPE = com.apple.package-type.wrapper.application
                        PASCAL_STRINGS = YES
                        PATH =
                        /Applications/Xcode.app/Contents/Developer/usr/bin:/Users/cpboyd/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sb
                        in:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/cp
                        boyd/.pyenv/shims:/usr/local/sbin:/Users/cpboyd/dev/flutter/bin:/Users/cpboyd/dev/flutter/bin
                        PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES = /usr/include /usr/local/include /System/Library/Frameworks
                        /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs
                        /Applications/Xcode.app/Contents/Developer/Platforms
                        PBDEVELOPMENTPLIST_PATH = Runner.app/pbdevelopment.plist
                        PFE_FILE_C_DIALECTS = objective-c
                        PKGINFO_FILE_PATH =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/PkgInfo
                        PKGINFO_PATH = Runner.app/PkgInfo
                        PLATFORM_DEVELOPER_APPLICATIONS_DIR =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
                        PLATFORM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
                        PLATFORM_DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
                        PLATFORM_DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
                        PLATFORM_DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
                        PLATFORM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
                        PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
                        PLATFORM_DISPLAY_NAME = iOS Simulator
                        PLATFORM_NAME = iphonesimulator
                        PLATFORM_PREFERRED_ARCH = x86_64
                        PLATFORM_PRODUCT_BUILD_VERSION = 18E182
                        PLIST_FILE_OUTPUT_FORMAT = binary
                        PLUGINS_FOLDER_PATH = Runner.app/PlugIns
                        PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR = YES
                        PRECOMP_DESTINATION_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/PrefixHeaders
                        PRESERVE_DEAD_CODE_INITS_AND_TERMS = NO
                        PRIVATE_HEADERS_FOLDER_PATH = Runner.app/PrivateHeaders
                        PRODUCT_BUNDLE_IDENTIFIER = com.example.bug
                        PRODUCT_BUNDLE_PACKAGE_TYPE = APPL
                        PRODUCT_MODULE_NAME = Runner
                        PRODUCT_NAME = Runner
                        PRODUCT_SETTINGS_PATH = /Users/cpboyd/Documents/GitHub/bug/ios/Runner/Info.plist
                        PRODUCT_TYPE = com.apple.product-type.application
                        PROFILING_CODE = NO
                        PROJECT = Runner
                        PROJECT_DERIVED_FILE_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/DerivedSo
                        urces
                        PROJECT_DIR = /Users/cpboyd/Documents/GitHub/bug/ios
                        PROJECT_FILE_PATH = /Users/cpboyd/Documents/GitHub/bug/ios/Runner.xcodeproj
                        PROJECT_NAME = Runner
                        PROJECT_TEMP_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build
                        PROJECT_TEMP_ROOT = /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex
                        PUBLIC_HEADERS_FOLDER_PATH = Runner.app/Headers
                        RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS = YES
                        REMOVE_CVS_FROM_RESOURCES = YES
                        REMOVE_GIT_FROM_RESOURCES = YES
                        REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES = YES
                        REMOVE_HG_FROM_RESOURCES = YES
                        REMOVE_SVN_FROM_RESOURCES = YES
                        REZ_COLLECTOR_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/ResourceManagerResources
                        REZ_OBJECTS_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build/ResourceManagerResources/Objects
                        SCAN_ALL_SOURCE_FILES_FOR_INCLUDES = NO
                        SCRIPTS_FOLDER_PATH = Runner.app/Scripts
                        SCRIPT_OUTPUT_STREAM_FILE =
                        /var/folders/v0/m8t66vt90z711gkgclc6q34h0000gn/T/flutter_tools.bZT087/flutter_build_log_pipe.dcRmvf/pipe_to_stdout
                        SDKROOT = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk
                        SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk
                        SDK_DIR_iphonesimulator14_5 =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk
                        SDK_NAME = iphonesimulator14.5
                        SDK_NAMES = iphonesimulator14.5
                        SDK_PRODUCT_BUILD_VERSION = 18E182
                        SDK_VERSION = 14.5
                        SDK_VERSION_ACTUAL = 140500
                        SDK_VERSION_MAJOR = 140000
                        SDK_VERSION_MINOR = 140500
                        SED = /usr/bin/sed
                        SEPARATE_STRIP = NO
                        SEPARATE_SYMBOL_EDIT = NO
                        SET_DIR_MODE_OWNER_GROUP = YES
                        SET_FILE_MODE_OWNER_GROUP = NO
                        SHALLOW_BUNDLE = YES
                        SHARED_DERIVED_FILE_DIR = /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/DerivedSources
                        SHARED_FRAMEWORKS_FOLDER_PATH = Runner.app/SharedFrameworks
                        SHARED_PRECOMPS_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/PrecompiledHeaders
                        SHARED_SUPPORT_FOLDER_PATH = Runner.app/SharedSupport
                        SKIP_INSTALL = NO
                        SOURCE_ROOT = /Users/cpboyd/Documents/GitHub/bug/ios
                        SRCROOT = /Users/cpboyd/Documents/GitHub/bug/ios
                        STRINGS_FILE_INFOPLIST_RENAME = YES
                        STRINGS_FILE_OUTPUT_ENCODING = binary
                        STRIP_BITCODE_FROM_COPIED_FILES = NO
                        STRIP_INSTALLED_PRODUCT = YES
                        STRIP_STYLE = all
                        STRIP_SWIFT_SYMBOLS = YES
                        SUPPORTED_DEVICE_FAMILIES = 1,2
                        SUPPORTED_PLATFORMS = iphonesimulator iphoneos
                        SUPPORTS_TEXT_BASED_API = NO
                        SWIFT_OBJC_BRIDGING_HEADER = Runner/Runner-Bridging-Header.h
                        SWIFT_OPTIMIZATION_LEVEL = -Onone
                        SWIFT_PLATFORM_TARGET_PREFIX = ios
                        SWIFT_VERSION = 5.0
                        SYMROOT = /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Products
                        SYSTEM_ADMIN_APPS_DIR = /Applications/Utilities
                        SYSTEM_APPS_DIR = /Applications
                        SYSTEM_CORE_SERVICES_DIR = /System/Library/CoreServices
                        SYSTEM_DEMOS_DIR = /Applications/Extras
                        SYSTEM_DEVELOPER_APPS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
                        SYSTEM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
                        SYSTEM_DEVELOPER_DEMOS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples
                        SYSTEM_DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
                        SYSTEM_DEVELOPER_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library
                        SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools
                        SYSTEM_DEVELOPER_JAVA_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Java Tools
                        SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Performance Tools
                        SYSTEM_DEVELOPER_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes
                        SYSTEM_DEVELOPER_TOOLS = /Applications/Xcode.app/Contents/Developer/Tools
                        SYSTEM_DEVELOPER_TOOLS_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools
                        SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools
                        SYSTEM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
                        SYSTEM_DEVELOPER_UTILITIES_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities
                        SYSTEM_DEXT_INSTALL_PATH = /System/Library/DriverExtensions
                        SYSTEM_DOCUMENTATION_DIR = /Library/Documentation
                        SYSTEM_KEXT_INSTALL_PATH = /System/Library/Extensions
                        SYSTEM_LIBRARY_DIR = /System/Library
                        TAPI_VERIFY_MODE = ErrorsOnly
                        TARGETED_DEVICE_FAMILY = 1,2
                        TARGETNAME = Runner
                        TARGET_BUILD_DIR = /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator
                        TARGET_NAME = Runner
                        TARGET_TEMP_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build
                        TEMP_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build
                        TEMP_FILES_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build
                        TEMP_FILE_DIR =
                        /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex/Runner.build/Debug-iph
                        onesimulator/Runner.build
                        TEMP_ROOT = /Users/cpboyd/Library/Developer/Xcode/DerivedData/Runner-bdqtgjwvbrebrsgmazjfbqbgnxqb/Build/Intermediates.noindex
                        TEST_FRAMEWORK_SEARCH_PATHS =
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks
                        /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/Developer/Library/F
                        rameworks
                        TEST_LIBRARY_SEARCH_PATHS =  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib
                        TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
                        TRACK_WIDGET_CREATION = true
                        TREAT_MISSING_BASELINES_AS_TEST_FAILURES = NO
                        TREE_SHAKE_ICONS = false
                        UID = 501
                        UNLOCALIZED_RESOURCES_FOLDER_PATH = Runner.app
                        UNSTRIPPED_PRODUCT = NO
                        USER = cpboyd
                        USER_APPS_DIR = /Users/cpboyd/Applications
                        USER_LIBRARY_DIR = /Users/cpboyd/Library
                        USE_DYNAMIC_NO_PIC = YES
                        USE_HEADERMAP = YES
                        USE_HEADER_SYMLINKS = NO
                        USE_LLVM_TARGET_TRIPLES = YES
                        USE_LLVM_TARGET_TRIPLES_FOR_CLANG = YES
                        USE_LLVM_TARGET_TRIPLES_FOR_LD = YES
                        USE_LLVM_TARGET_TRIPLES_FOR_TAPI = YES
                        VALIDATE_PRODUCT = NO
                        VALIDATE_WORKSPACE = NO
                        VALID_ARCHS = arm64 arm64e i386 x86_64
                        VERBOSE_PBXCP = NO
                        VERBOSE_SCRIPT_LOGGING = YES
                        VERSIONING_SYSTEM = apple-generic
                        VERSIONPLIST_PATH = Runner.app/version.plist
                        VERSION_INFO_BUILDER = cpboyd
                        VERSION_INFO_FILE = Runner_vers.c
                        VERSION_INFO_STRING = "@(#)PROGRAM:Runner  PROJECT:Runner-1"
                        WRAPPER_EXTENSION = app
                        WRAPPER_NAME = Runner.app
                        WRAPPER_SUFFIX = .app
                        WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
                        XCODE_APP_SUPPORT_DIR = /Applications/Xcode.app/Contents/Developer/Library/Xcode
                        XCODE_PRODUCT_BUILD_VERSION = 12E262
                        XCODE_VERSION_ACTUAL = 1250
                        XCODE_VERSION_MAJOR = 1200
                        XCODE_VERSION_MINOR = 1250
                        XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
                        YACC = yacc
                        arch = x86_64
                        variant = normal
[  +10 ms] executing: rsync -av --delete /Users/cpboyd/Documents/GitHub/bug/build/ios/Debug-iphonesimulator/Runner.app
/Users/cpboyd/Documents/GitHub/bug/build/ios/iphonesimulator
[ +221 ms] building file list ... done
                    Runner.app/
                    Runner.app/Info.plist
                    Runner.app/PkgInfo
                    Runner.app/Runner
                    Runner.app/Frameworks/
                    Runner.app/Frameworks/App.framework/
                    Runner.app/Frameworks/App.framework/App
                    Runner.app/Frameworks/App.framework/_CodeSignature/CodeResources
                    Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.json
                    Runner.app/Frameworks/App.framework/flutter_assets/FontManifest.json
                    Runner.app/Frameworks/App.framework/flutter_assets/NOTICES
                    Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
                    Runner.app/_CodeSignature/CodeResources

                    sent 35865391 bytes  received 258 bytes  71731298.00 bytes/sec
                    total size is 102233541  speedup is 2.85
[   +3 ms] executing: xcrun simctl install B68DDD0B-98C1-483B-875C-F025235CC303 /Users/cpboyd/Documents/GitHub/bug/build/ios/iphonesimulator/Runner.app
[ +598 ms] executing: /usr/bin/plutil -convert json -o - /Users/cpboyd/Documents/GitHub/bug/build/ios/iphonesimulator/Runner.app/Info.plist
[  +15 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/cpboyd/Documents/GitHub/bug/build/ios/iphonesimulator/Runner.app/Info.plist
[        ]
{"CFBundleName":"bug","DTXcode":"1250","DTSDKName":"iphonesimulator14.5","UILaunchStoryboardName":"LaunchScreen","CFBundleIcons~ipad":{"CFBundlePrimaryIcon":{"C
FBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60","AppIcon76x76","AppIcon83.5x83.5"],"CFBundleIconName":"AppIcon"}},"DTSDKBuild":"1
8E182","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","BuildMachineOSBuild":"20E241","DTPlatformName":"iphonesimulator","CFBundlePackageType":"APPL","UI
MainStoryboardFile":"Main","CFBundleSupportedPlatforms":["iPhoneSimulator"],"CFBundleShortVersionString":"1.0.0","CFBundleInfoDictionaryVersion":"6.0","CFBundle
Executable":"Runner","DTCompiler":"com.apple.compilers.llvm.clang.1_0","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOri
entationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"MinimumOSVersion":"9.0","CFBundleIdentifier":"com.exa
mple.bug","UIDeviceFamily":[1,2],"DTPlatformVersion":"14.5","CFBundleSignature":"????","CFBundleIcons":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x2
0","AppIcon29x29","AppIcon40x40","AppIcon60x60"],"CFBundleIconName":"AppIcon"}},"DTXcodeBuild":"12E262","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrientati
ons":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"UIViewControllerBasedStatusBarAppearance":
false,"NSBonjourServices":["_dartobservatory._tcp"],"DTPlatformBuild":"18E182","NSLocalNetworkUsageDescription":"Allow Flutter tools on your computer to connect
and debug your application. This prompt will not appear on release builds."}
[   +4 ms] executing: xcrun simctl launch B68DDD0B-98C1-483B-875C-F025235CC303 com.example.bug --enable-dart-profiling --enable-checked-mode
--verify-entry-points --observatory-port=0
[ +424 ms] com.example.bug: 76895
[        ] Waiting for observatory port to be available...
[ +335 ms] Observatory URL on device: http://127.0.0.1:51918/QkALp_wXErc=/
[   +6 ms] Caching compiled dill
[  +38 ms] Connecting to service protocol: http://127.0.0.1:51918/QkALp_wXErc=/
[ +163 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:51918/QkALp_wXErc=/.
[  +79 ms] DDS is listening at http://127.0.0.1:51921/rsmtmItmwq0=/.
[  +80 ms] Successfully connected to service protocol: http://127.0.0.1:51918/QkALp_wXErc=/
[  +20 ms] DevFS: Creating new filesystem on the device (null)
[  +31 ms] DevFS: Created new filesystem on the device
(file:///Users/cpboyd/Library/Developer/CoreSimulator/Devices/B68DDD0B-98C1-483B-875C-F025235CC303/data/Containers/Data/Application/84BCD17D-EFD0-4102-9387-9DF8
DEF9D418/tmp/bugiLgtRR/bug/)
[   +2 ms] Updating assets
[  +84 ms] Syncing files to device iPhone SE (2nd generation)...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +3 ms] <- recompile package:bug/main.dart 9c6e340a-b36a-4499-b8fa-7d3e2512d47c
[        ] <- 9c6e340a-b36a-4499-b8fa-7d3e2512d47c
[  +87 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device iPhone SE (2nd generation)... (completed in 94ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[  +37 ms] Connected to _flutterView/0x7ff8cc014820.
[   +5 ms] Flutter run key commands.
[   +4 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[   +2 ms] An Observatory debugger and profiler on iPhone SE (2nd generation) is available at: http://127.0.0.1:51921/rsmtmItmwq0=/
[ +606 ms] The Flutter DevTools debugger and profiler on iPhone SE (2nd generation) is available at:
                    http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A51921%2FrsmtmItmwq0%3D%2F
```

```
% flutter analyze
Analyzing bug...                                                        
No issues found! (ran in 1.8s)
```

```
% flutter doctor -v
[✓] Flutter (Channel beta, 2.2.0-10.2.pre, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
    • Flutter version 2.2.0-10.2.pre at /Users/cpboyd/dev/flutter
    • Framework revision b5017bf8de (9 days ago), 2021-04-28 17:09:53 -0700
    • Engine revision 91ed51e05c
    • Dart version 2.13.0 (build 2.13.0-211.13.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cpboyd/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/cpboyd/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 4.2 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • B68DDD0B-98C1-483B-875C-F025235CC303 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/82067

### Description

Currently, PopupMenuButton provides a default position for the popup menu. According to the issue and material guidelines, it should be able to position below the button, you can achieve this by providing an offset parameter however, this is roughly calculated.

According to guidelines, a popup menu should be positioned below and if there is no room, it can be positioned over the button.  Flutter automatically does this calculation.

However, the default offset is still `Offset.zero` so a roughly calculated offset parameter must be provided to achieve the same design as material guidelines.

Here I decided to add an enum that provides control over the position of the popup menu which calculates the height of the button itself minus vertical padding and position the menu correctly without setting rough offset every time.

This way popup menu can be positioned over or under the button without rough offset and offset can be provided if enum positions are insufficient.

### Code sample

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

enum Fruits { mango, apple, banana, straberry }

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key, this.dark = true}) : super(key: key);

  final bool dark;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: dark ? ThemeData.dark() : ThemeData.light(),
      home: const PopupMenuButtonSample(),
    );
  }
}

class PopupMenuButtonSample extends StatelessWidget {
  const PopupMenuButtonSample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(' PopupMenuButton Sample'),
        actions: <Widget>[
          PopupMenuButton<Fruits>(
            position: MenuPosition.under,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
            onSelected: (Fruits result) {
              print('selected fruit: ${result.name}');
            },
            onCanceled: () {
              print('onCanceled');
            },
            color: Colors.red[700],
            itemBuilder: (BuildContext context) => <PopupMenuEntry<Fruits>>[
              const PopupMenuItem<Fruits>(
                value: Fruits.mango,
                child: Text('Mango'),
              ),
              const PopupMenuItem<Fruits>(
                value: Fruits.apple,
                child: Text('Apple'),
              ),
              const PopupMenuItem<Fruits>(
                value: Fruits.banana,
                child: Text('Banana'),
              ),
              const PopupMenuItem<Fruits>(
                value: Fruits.straberry,
                child: Text('Strawberry'),
              ),
            ],
          )
        ],
      ),
      body: Center(
        child: Stack(
          children: [
            Positioned(
              bottom: 25,
              right: 10,
              child: PopupMenuButton<Fruits>(
                position: MenuPosition.under,
                icon: const Icon(Icons.apple),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
                onSelected: (Fruits result) {
                  print('selected fruit: ${result.name}');
                },
                onCanceled: () {
                  print('onCanceled');
                },
                color: Colors.red[700],
                itemBuilder: (BuildContext context) => <PopupMenuEntry<Fruits>>[
                  const PopupMenuItem<Fruits>(
                    value: Fruits.mango,
                    child: Text('Mango'),
                  ),
                  const PopupMenuItem<Fruits>(
                    value: Fruits.apple,
                    child: Text('Apple'),
                  ),
                  const PopupMenuItem<Fruits>(
                    value: Fruits.banana,
                    child: Text('Banana'),
                  ),
                  const PopupMenuItem<Fruits>(
                    value: Fruits.straberry,
                    child: Text('Strawberry'),
                  ),
                ],
              ),
            ),
            Positioned.fill(
              child: Center(
                child: PopupMenuButton<Fruits>(
                  position: MenuPosition.under,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                  onSelected: (Fruits result) {
                    print('selected fruit: ${result.name}');
                  },
                  onCanceled: () {
                    print('onCanceled');
                  },
                  color: Colors.red[700],
                  itemBuilder: (BuildContext context) =>
                      <PopupMenuEntry<Fruits>>[
                    const PopupMenuItem<Fruits>(
                      value: Fruits.mango,
                      child: Text('Mango'),
                    ),
                    const PopupMenuItem<Fruits>(
                      value: Fruits.apple,
                      child: Text('Apple'),
                    ),
                    const PopupMenuItem<Fruits>(
                      value: Fruits.banana,
                      child: Text('Banana'),
                    ),
                    const PopupMenuItem<Fruits>(
                      value: Fruits.straberry,
                      child: Text('Strawberry'),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
``` 
	
</details>

### Preview

https://user-images.githubusercontent.com/48603081/155325514-fc12b86e-5e11-4d06-8bd6-9638bcf50ad4.mov

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 1]
```diff
@@ -1033,11 +1045,11 @@ class PopupMenuButton<T> extends StatefulWidget {
...
   final Widget? icon;
 
-  /// The offset applied to the Popup Menu Button.
+  /// The offset applied to the popup menu.
   ///
-  /// When not set, the Popup Menu Button will be positioned directly next to
+  /// When not set, the popup menu will be positioned directly over
   /// the button that was used to create it.
-  final Offset offset;
+  final Offset? offset;
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/popup_menu.dart:1052]: Instead of making this nullable, why not make it be relative to the position described by `position`?  Then, position can also be non-nullable, and if it defaults to `MenuPosition.over`, will not be a breaking change, since an offset of zero (the default), and the default position will be identical to the previous behavior.

**Review by gspencergoog — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/material/popup_menu.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/popup_menu.dart]: Thanks so much for the review. I did revert offset being nullable, however, I think the new position parameter should be nullable so that the user doesn't try to change offset to a random value when the position still has a fixed menu offset defined.

They can either just use the widget as it is, override position, or set an offset. Without conflicting fixed positions and a custom offset. If the default position says over but offset is Offset(-100,-100), it would be conflicting information.
Let me know if you think this makes sense.

Comment (gspencergoog) [reply packages/flutter/lib/src/material/popup_menu.dart]: Sorry, I'm not sure I understand...

Why can't you add the offset to the default position? If the `position` is `over`, and the `offset` is zero, you have a location for the menu (the current default location before this PR).  If you then change the `offset`, it starts at that location, and modifies it by the `offset`.  If the position is `under`, and the `offset` is zero, then that also defines a location for the menu right below the button, and changing the `offset` will just modify the position relative to that point.

It doesn't sound conflicting to me, but maybe I've totally missed your point... Unless you just mean that "over" implies that it is visually on top of the button, but a large offset will mean that it is no longer visually over it? I think that's OK: they said they wanted it a long way away from the "over" location: it should be expected.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/popup_menu.dart]: Thanks so much for the explanation.

My idea was offset should override both positions enum but after reading our comment. I realized you wanted offset to apply on top of predefined offset and if the position is `under`, `offset` will just modify the position relative to that point.


I added conditions that handle this logic and expanded the test to cover offset changes.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/popup_menu.dart]: cc: @gspencergoog

**Review by gspencergoog — CHANGES_REQUESTED** [review]
Sorry! I wrote this feedback a few days ago, and just forgot to submit.

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 2]
```diff
@@ -1120,10 +1134,20 @@ class PopupMenuButtonState<T> extends State<PopupMenuButton<T>> {
     final PopupMenuThemeData popupMenuTheme = PopupMenuTheme.of(context);
     final RenderBox button = context.findRenderObject()! as RenderBox;
     final RenderBox overlay = Navigator.of(context).overlay!.context.findRenderObject()! as RenderBox;
+    final Offset offset;
```
[the remark this answers is not in the document]
Comment (TahaTesser) [reply packages/flutter/lib/src/material/popup_menu.dart:1137]: That's awesome, I couldn't think it could be that simplified using a switch, thanks!  I will avoid if statements

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 3]
```diff
@@ -38,6 +38,14 @@ const double _kMenuVerticalPadding = 8.0;
 const double _kMenuWidthStep = 56.0;
 const double _kMenuScreenPadding = 8.0;
 
+/// Used to configure how the [PopupMenuButton] positions its popup menu.
+enum MenuPosition {
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/popup_menu.dart:42]: I know it's longer, but can we rename this to `PopupMenuPosition`?  I'm working on a `MenuBar` widget, and while I'm not using an enum (at least not yet), people might be confused as to which widget this works with if they didn't read the docs.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Just the one rename.

File: packages/flutter/lib/src/material/popup_menu.dart (hunk 3 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/popup_menu.dart:42]: That makes sense, renaming it later would be a breaking change, better safe now :)
