### PR TITLE
Work around the glibc bug that causes rare Chrome crashes

### LINKED ISSUE #67454: Web test timing out from after two hours
This test is flaking 1.85%

The web tests seem to be retrying tests with timeouts of 12 mins each making the builder to use resources for hours:

```
144:02 +4 ~4 -71: loading /b/s/w/ir/k/flutter/packages/flutter/test/widgets/icon_data_test.dart [E]                                                                                                    
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1182:47                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1190:13                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 397:19         _Timer._runTimers
  dart:isolate-patch/isolate_patch.dart 168:12      _RawReceivePortImpl._handleMessage
  

144:04 +4 ~4 -72: loading /b/s/w/ir/k/flutter/packages/flutter/test/material/text_selection_test.dart [E]                                                                                              
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1182:47                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1190:13                      _rootRun
  dart:async/zone.dart 1093:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 397:19         _Timer._runTimers
  dart:isolate-patch/isolate_patch.dart 168:12      _RawReceivePortImpl._handleMessage
```

Here is an example from 09/23/2020:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20SDK%20Drone/9244?

One more recent example 10/06/2020:

https://ci.chromium.org/p/flutter/builders/try/Linux%20SDK%20Drone/61704?

### PR DESCRIPTION
**Pull request by yjbanov**
## Description

Due to https://sourceware.org/bugzilla/show_bug.cgi?id=19329 once every few thousands times Chrome fails to launch, crashing with exit code 127.

This PR works around that issue by checking for an error message specific to that bug and relaunching Chrome. With this change a test run that launched Chrome 18000 times was 100% green, when previously that many attempts would be 100% red.

Other changes:

- When in verbose mode print the version of Chromium.
- Change `try_builders.json` to always run tests whenever anything under `packages/` changes.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/67454

### CODE REVIEW

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 1]
```diff
@@ -241,6 +227,66 @@ class ChromiumLauncher {
     ), skipCheck);
   }
 
+  Future<Process> _spawnChromiumProcess(List<String> args) async {
+    // Keep attempting to launch the browser until one of:
+    // - We successfully launched it, in which case we just return from the loop.
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/web/chrome.dart:232]: go/no-we

File: dev/try_builders.json [hunk 2]
```diff
@@ -165,7 +165,7 @@
          "repo":"flutter",
          "task_name":"linux_web_tests",
          "enabled":true,
-         "run_if":["dev/", "packages/flutter/", "packages/flutter_goldens_client/", "packages/flutter_goldens/", "packages/flutter_test/", "packages/flutter_tools/lib/src/test/", "packages/flutter_web_plugins/", "bin/"]
+         "run_if":["dev/", "packages/", "bin/"]
```
Comment (christopherfujino) [inline dev/try_builders.json:168]: is this right?

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 3]
```diff
@@ -241,6 +227,66 @@ class ChromiumLauncher {
...
+      // When this happens Chrome spits out something like the following then exits with code 127:
+      //
+      //     Inconsistency detected by ld.so: ../elf/dl-tls.c: 493: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
+      bool hitGlibcBug = false;
+      await process.stderr
+        .transform(utf8.decoder)
+        .transform(const LineSplitter())
+        .map((String line) {
+          _logger.printTrace('[CHROME]:$line');
+          if (line.contains('Inconsistency detected by ld.so')) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/web/chrome.dart:262]: Consider hoisting this into a constant, along with the documentation you added above.

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 4]
```diff
@@ -241,6 +227,66 @@ class ChromiumLauncher {
...
+          return line;
+        })
+        .firstWhere((String line) => line.startsWith('DevTools listening'), orElse: () {
+          if (hitGlibcBug) {
+            _logger.printStatus(
+              'Encountered glibc bug https://sourceware.org/bugzilla/show_bug.cgi?id=19329. '
+              'Will try launching browser again.',
+            );
+            return null;
+          } else {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/web/chrome.dart:274]: `else` isn't necessary due to return above

File: dev/try_builders.json (hunk 2 above)
Comment (yjbanov) [reply dev/try_builders.json:168]: Depends on the definition of "right" :)

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 5]
```diff
@@ -241,6 +227,66 @@ class ChromiumLauncher {
...
+          }
+        });
+
+      if (!hitGlibcBug) {
+        return process;
+      } else if (!exited) {
+        // A precaution that avoids accumulating browser processes, in case the
+        // glibc bug doesn't cause the browser to quit and we keep looping and
+        // launching more processes.
+        process.kill();
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/web/chrome.dart:285]: Check if this is successful. What happens if the tool fails to kill it?

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 6]
```diff
@@ -241,6 +227,66 @@ class ChromiumLauncher {
...
+            );
+            return null;
+          } else {
+            throw ToolExit('Failed to spawn: ${args.join(' ')}');
+          }
+        });
+
+      if (!hitGlibcBug) {
+        return process;
+      } else if (!exited) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/web/chrome.dart:281]: `if (!exited) {` on the next line instead of else if

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 7]
```diff
@@ -241,6 +227,66 @@ class ChromiumLauncher {
...
+        })
+        .firstWhere((String line) => line.startsWith('DevTools listening'), orElse: () {
+          if (hitGlibcBug) {
+            _logger.printStatus(
+              'Encountered glibc bug https://sourceware.org/bugzilla/show_bug.cgi?id=19329. '
+              'Will try launching browser again.',
+            );
+            return null;
+          } else {
+            throw ToolExit('Failed to spawn: ${args.join(' ')}');
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/web/chrome.dart:275]: `throwToolExit`.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/chrome.dart:275]: Generally I would stick with a more actionable message here, the args themselves is more like debugging info.

File: dev/try_builders.json (hunk 2 above)
Comment (christopherfujino) [reply dev/try_builders.json:168]: ahh, I read this as `"dev/packages/bin"`, lol, disregard

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 5 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart:285]: How does the tool normally do this check? I can't find an example. I'm not sure what to do if it fails to kill it. I added it only as a precaution. I think it's OK if we fail. That would probably indicate that the system is in a completely busted and unrecoverable state.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 1 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart]: Done.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 3 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart]: Done.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 4 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart]: Done.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 6 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart]: Done.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 7 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart]: Done.

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 8]
```diff
@@ -241,6 +239,67 @@ class ChromiumLauncher {
...
 
+  Future<Process> _spawnChromiumProcess(List<String> args) async {
+    // Keep attempting to launch the browser until one of:
+    // - Chrome launched successfully, in which case we just return from the loop.
+    // - The tool detected an unretriable Chrome error, in which case we throw ToolExit.
+    while (true) {
+      final Process process = await _processManager.start(args);
+
+      bool exited = false;
+      unawaited(process.exitCode.then((int exitCode) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/web/chrome.dart:250]: since you don't use the exitCode, use `whenComplete(() { ... })`

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 9]
```diff
@@ -241,6 +239,67 @@ class ChromiumLauncher {
...
+        .firstWhere((String line) => line.startsWith('DevTools listening'), orElse: () {
+          if (hitGlibcBug) {
+            _logger.printStatus(
+              'Encountered glibc bug https://sourceware.org/bugzilla/show_bug.cgi?id=19329. '
+              'Will try launching browser again.',
+            );
+            return null;
+          }
+          _logger.printTrace('Failed to launch browser. Command used to launch it: ${args.join(' ')}');
+          throw ToolExit(
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/web/chrome.dart:283]: `throwToolExit`

**Review by jonahwilliams — APPROVED** [review]
LGTM with nit

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 5 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/chrome.dart:298]: I don't have any advice :)

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 9 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart:283]: Can't use `throwToolExit` because the function must end with a `return` or `throw`.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 8 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart:250]: Done.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 5 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/web/chrome.dart:298]: Instead of using the `exited` flag, it's a little more idiomatic to put a timeout out `process.exitCode`, and then do `process.kill()` if it doesn't finish in time. Following sending the kill, if stdout might be useful for debugging, you'll want to explicitly drain that stream.

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 10]
```diff
@@ -241,6 +239,67 @@ class ChromiumLauncher {
...
+        .transform(utf8.decoder)
+        .transform(const LineSplitter())
+        .listen((String line) {
+          _logger.printTrace('[CHROME]: $line');
+        });
+
+      // Wait until the DevTools are listening before trying to connect. This is
+      // only required for flutter_test --platform=chrome and not flutter run.
+      bool hitGlibcBug = false;
+      await process.stderr
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/chrome.dart:264]: This can throw dart:io exceptions if the process fails in certain ways/at certain times. Ditto for `process.stdout` which is another reason to do `.listen().asFuture()` and await the `Future` in a `try {} catch {}` for it.

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 11]
```diff
@@ -241,6 +239,67 @@ class ChromiumLauncher {
...
+        .map((String line) {
+          _logger.printTrace('[CHROME]:$line');
+          if (line.contains(_kGlibcError)) {
+            hitGlibcBug = true;
+          }
+          return line;
+        })
+        .firstWhere((String line) => line.startsWith('DevTools listening'), orElse: () {
+          if (hitGlibcBug) {
+            _logger.printStatus(
```
[the remark this answers is not in the document]
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart:276]: Done.

**Comment by yjbanov** [comment]
@zanderso 

> Instead of using the exited flag, it's a little more idiomatic to put a timeout out process.exitCode, and then do process.kill() if it doesn't finish in time. Following sending the kill, if stdout might be useful for debugging, you'll want to explicitly drain that stream.

Done.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 10 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart:264]: This sounds like a good future enhancement. I'd prefer to wait until it actually happens, so we can recreate the exact situation in a test. I ran this code 18000 times and it worked fine.

**Comment by yjbanov** [comment]
Landing on stuck "Google testing". Google is using ddr instead of flutter tools for this anyway.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 9 above)
Comment (dnfield) [reply packages/flutter_tools/lib/src/web/chrome.dart:278]: Would it help if we made `throwToolExit` return `Never`?

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 12]
```diff
@@ -241,6 +239,63 @@ class ChromiumLauncher {
...
+
+      if (!hitGlibcBug) {
+        return process;
+      }
+
+      // A precaution that avoids accumulating browser processes, in case the
+      // glibc bug doesn't cause the browser to quit and we keep looping and
+      // launching more processes.
+      unawaited(process.exitCode.timeout(const Duration(seconds: 1), onTimeout: () {
+        process.kill();
```
Comment (dnfield) [inline packages/flutter_tools/lib/src/web/chrome.dart:293]: drive by comment: if this code ever has to run on windows, it might fail to kill the process _and_ fail to block execution, leading to accumulation of processes.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 9 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/web/chrome.dart:278]: We cannot do that until we migrate to null safety

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 12 above)
Comment (yjbanov) [reply packages/flutter_tools/lib/src/web/chrome.dart:293]: What's a good way to do this on Windows?

**Comment by yjbanov** [comment]
To follow-up. This fix seems to have been effective:

Screen Shot 2020-10-14 at 9 55 35 AM

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 12 above)
Comment (dnfield) [reply packages/flutter_tools/lib/src/web/chrome.dart:293]: There isn't one unfortunately. As far as I can tell, Dart does not offer a way to reliably kill processes on windows - if you want to be really paranoid about it you can try to sleep/poll for when the process actually dies, but if the process is really stuck (like, you have to reboot the machine stuck), that might never end.

Windows doesn't quite have a "kill -9" idea.
