### PR TITLE
Fix double.infinity serialization

### LINKED ISSUE #39937: CupertinoTextField with placeholder fails to serialize diagnostics for dev tools
Repro steps:
1. Return a `CupertinoTextField` from your build method. Ensure `placeholder` is set.
2. Open dev tools
3. Attempt to view details about the text field
4. An exception is encountered, and details do not display

Did a little bit of investigation. Looks like `CupertinoTextField` is creating a `SizedBox` with `double.infinity` width ([`cupertino/text_field.dart:748`](https://github.com/flutter/flutter/blob/a24bfed0e7b65f4a927af2ddc8ff7440a2051e24/packages/flutter/lib/src/cupertino/text_field.dart#L748)). When the service layer attempts to serialize this value to send it to the devtools, it's found to be infinite, cannot serialize ([`dart:core/json.dart:658`](https://github.com/dart-lang/sdk/blob/770436d47781a3aa6c9113fdd6684e3d613bd133/sdk/lib/convert/json.dart#L656)), and throws an exception.

Introduced in #33739 
cc @HaijunWei, @LongCatIsLooong

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

Convert infinite numbers to strings before serializing them.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/39937

## Tests

I added the following tests:

double.infinity serialization test

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/foundation/diagnostics.dart [hunk 1]
```diff
@@ -2669,7 +2669,9 @@ class DiagnosticsProperty<T> extends DiagnosticsNode {
     json['defaultLevel'] = describeEnum(_defaultLevel);
     if (value is Diagnosticable || value is DiagnosticsNode)
       json['isDiagnosticableValue'] = true;
-    if (value is num || value is String || value is bool || value == null)
+    if (v is num)
+      json['value'] = v.isFinite ? v :  v.toString();
```
Comment (jacob314) [inline packages/flutter/lib/src/foundation/diagnostics.dart]: Add a comment explaining this is due to json restrictions.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/foundation/diagnostics.dart]: done

**Comment by jacob314** [comment]
lgtm
