### PR TITLE
Fix memory leaks in WidgetInspector and WidgetInspectorService. [prod-leak-fix]

### LINKED ISSUE #135824: Memory Leak: WidgetInspectorServiceExtensions.screenshot does not dispose created ui.Image.
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

`WidgetInspectorServiceExtensions.screenshot` does not dispose created `ui.Image` instance.

Test to reveal the leak:

```dart
import 'dart:convert';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:leak_tracker_flutter_testing/leak_tracker_flutter_testing.dart';

import 'widget_inspector_test_utils.dart';

void main() {
  _TestWidgetInspectorService.runTests();
}

class _TestWidgetInspectorService extends TestWidgetInspectorService {
  // These tests need access to protected members of WidgetInspectorService.
  static void runTests() {
    final TestWidgetInspectorService service = TestWidgetInspectorService();
    WidgetInspectorService.instance = service;

    testWidgetsWithLeakTracking('Leak', (WidgetTester tester) async {
      await tester.pumpWidget(
        const Center(
          child: RepaintBoundary(
            child: ColoredBox(
              color: Colors.red,
              child: Padding(
                padding: EdgeInsets.all(100.0),
                child: SizedBox(
                  height: 100.0,
                  width: 100.0,
                ),
              ),
            ),
          ),
        ),
      );

      final Element repaintBoundary =
          find.byType(RepaintBoundary).evaluate().single;

      // Verify we get the same image if we go through the service extension
      // instead of invoking the screenshot method directly.
      final Future<Object?> base64ScreenshotFuture = service.testExtension(
        WidgetInspectorServiceExtensions.screenshot.name,
        <String, String>{
          'id': service.toId(repaintBoundary, 'group')!,
          'width': '300.0',
          'height': '300.0',
        },
      );

      final TestWidgetsFlutterBinding binding =
          TestWidgetsFlutterBinding.ensureInitialized();
      final ui.Image screenshot = (await binding.runAsync<ui.Image>(() async {
        final String base64Screenshot =
            (await base64ScreenshotFuture)! as String;
        final ui.Codec codec =
            await ui.instantiateImageCodec(base64.decode(base64Screenshot));
        final ui.FrameInfo frame = await codec.getNextFrame();
        return frame.image;
      }))!;
      addTearDown(screenshot.dispose);
    }, leakTrackingTestConfig: LeakTrackingTestConfig.debugNotDisposed());
  }
}
```

<details><summary>Test output</summary>

```console
Expected: leak free
  Actual: <Instance of 'Leaks'>
   Which: contains leaks:
          # The text is generated by leak_tracker.
          # For leak troubleshooting tips open:
          # https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md
          notDisposed:
            total: 1
            objects:
              Image:
                test: leak
                identityHashCode: 13383695
                context:
                  start: >
#6_______flutterEventToLeakTracker_
test_widgets.dart:24
#7______MemoryAllocations.dispatchObjectEvent_
memory_allocations.dart:241
#8______MemoryAllocations._imageOnCreate_
memory_allocations.dart:315
#9______new_Image.__(dart:ui/painting.dart:1717:15)
#10______NativeScene.toImage.<anonymous_closure>.<anonymous_closure>_(dart:ui/compositing.dart:71:26)
                    #11_____FfiTrampoline___toImage$Method$FfiNative$Ptr_(dart:ffi)
#12______NativeScene._toImage_(dart:ui/compositing.dart:78:20)
#13______NativeScene.toImage.<anonymous_closure>_(dart:ui/compositing.dart:67:54)
#14______futurize_(dart:ui/painting.dart:6946:35)
#15______NativeScene.toImage_(dart:ui/compositing.dart:67:12)
#16_____OffsetLayer.toImage_
layer.dart:1554
#17______ScreenshotPaintingContext.toImage_
widget_inspector.dart:615
#18_____WidgetInspectorService.screenshot_
widget_inspector.dart:2096
#19_____WidgetInspectorService.initServiceExtensions.<anonymous_closure>_
widget_inspector.dart:1287
#20_____TestWidgetInspectorService.testExtension_
widget_inspector_test_utils.dart:100
#21______TestWidgetInspectorService.runTests.<anonymous_closure>_
widget_inspector_1_test.dart:43
                    <asynchronous_suspension>
#22_____testWidgetsWithLeakTracking.wrappedCallBack_
test_widgets.dart:127
                    <asynchronous_suspension>
#23_____testWidgets.<anonymous_closure>.<anonymous_closure>_
widget_tester.dart:168
                    <asynchronous_suspension>
#24_____TestWidgetsFlutterBinding._runTestBody_
binding.dart:1013
                    <asynchronous_suspension>
#25_____StackZoneSpecification._registerCallback.<anonymous_closure>_
stack_zone_specification.dart:114
                    <asynchronous_suspension>
          
          


package:matcher                                                  expect
expect
widget_tester.dart:458
_tearDownTestingWithLeakTracking
test_widgets.dart:82
===== asynchronous gap ===========================
dart:async                                                       _CustomZone.registerBinaryCallback
configureLeakTrackingTearDown.<fn>
test_widgets.dart:59

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-14.0.pre.580, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.14.0-14.0.pre.580 on channel master at /Users/ksokolovskyi/dev/flutter_master
    • Upstream repository git@github.com:ksokolovskyi/flutter.git
    • FLUTTER_GIT_URL = git@github.com:ksokolovskyi/flutter.git
    • Framework revision ba1d6147ba (28 hours ago), 2023-09-30 04:52:24 -0400
    • Engine revision f726438d4d
    • Dart version 3.2.0 (build 3.2.0-218.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #135826: Memory Leak: _InspectorOverlayLayer does not dispose created ui.Picture.
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

`_InspectorOverlayLayer ` does not dispose created `ui.Picture` instance.

Test to reveal the leak:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:leak_tracker_flutter_testing/leak_tracker_flutter_testing.dart';

import 'widget_inspector_test_utils.dart';

void main() {
  _TestWidgetInspectorService.runTests();
}

class _TestWidgetInspectorService extends TestWidgetInspectorService {
  // These tests need access to protected members of WidgetInspectorService.
  static void runTests() {
    final TestWidgetInspectorService service = TestWidgetInspectorService();
    WidgetInspectorService.instance = service;

    testWidgetsWithLeakTracking('_InspectorOverlayLayer leak',
        (WidgetTester tester) async {
      final GlobalKey selectButtonKey = GlobalKey();
      final GlobalKey inspectorKey = GlobalKey();

      await tester.pumpWidget(
        Directionality(
          textDirection: TextDirection.ltr,
          child: WidgetInspector(
            key: inspectorKey,
            selectButtonBuilder:
                (BuildContext context, VoidCallback onPressed) {
              return Material(
                child: ElevatedButton(
                  onPressed: onPressed,
                  key: selectButtonKey,
                  child: null,
                ),
              );
            },
            child: Material(
              child: Center(
                child: ElevatedButton(
                  onPressed: () {},
                  child: const Text('TOP'),
                ),
              ),
            ),
          ),
        ),
      );

      expect(WidgetInspectorService.instance.selection.current, isNull);

      await tester.tap(find.text('TOP'), warnIfMissed: false);
      await tester.pump();

      expect(WidgetInspectorService.instance.selection.current, isNotNull);
    }, leakTrackingTestConfig: LeakTrackingTestConfig.debugNotDisposed());
  }
}
```

<details><summary>Test output</summary>

```console
Expected: leak free
  Actual: <Instance of 'Leaks'>
   Which: contains leaks:
          # The text is generated by leak_tracker.
          # For leak troubleshooting tips open:
          # https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md
          notDisposed:
            total: 1
            objects:
              _NativePicture:
                test: _InspectorOverlayLayer leak
                identityHashCode: 393545165
                context:
                  start: >
#6_______flutterEventToLeakTracker_
test_widgets.dart:24
#7______MemoryAllocations.dispatchObjectEvent_
memory_allocations.dart:241
#8______MemoryAllocations._pictureOnCreate_
memory_allocations.dart:323
#9_______NativePictureRecorder.endRecording_(dart:ui/painting.dart:6435:23)
#10______InspectorOverlayLayer._buildPicture_
widget_inspector.dart:3256
#11______InspectorOverlayLayer.addToScene_
widget_inspector.dart:3203
#12_____Layer._addToSceneWithRetainedRendering_
layer.dart:712
#13_____ContainerLayer.addChildrenToScene_
layer.dart:1378
#14_____TransformLayer.addToScene_
layer.dart:1995
#15_____ContainerLayer.buildScene_
layer.dart:1130
#16_____RenderView.compositeFrame_
view.dart:252
#17_____AutomatedTestWidgetsFlutterBinding.drawFrame_
binding.dart:1419
#18_____RendererBinding._handlePersistentFrameCallback_
binding.dart:457
#19_____SchedulerBinding._invokeFrameCallback_
binding.dart:1325
#20_____SchedulerBinding.handleDrawFrame_
binding.dart:1255
#21_____AutomatedTestWidgetsFlutterBinding.pump.<anonymous_closure>_
binding.dart:1264
#22______rootRun_(dart:async/zone.dart:1399:13)
#23______CustomZone.run_(dart:async/zone.dart:1301:19)
#24_____TestAsyncUtils.guard_
test_async_utils.dart:71
#25_____AutomatedTestWidgetsFlutterBinding.pump_
binding.dart:1251
#26_____WidgetTester.pump.<anonymous_closure>_
widget_tester.dart:637
#27______rootRun_(dart:async/zone.dart:1399:13)
#28______CustomZone.run_(dart:async/zone.dart:1301:19)
#29_____TestAsyncUtils.guard_
test_async_utils.dart:71
#30_____WidgetTester.pump_
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-14.0.pre.580, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.14.0-14.0.pre.580 on channel master at /Users/ksokolovskyi/dev/flutter_master
    • Upstream repository git@github.com:ksokolovskyi/flutter.git
    • FLUTTER_GIT_URL = git@github.com:ksokolovskyi/flutter.git
    • Framework revision ba1d6147ba (28 hours ago), 2023-09-30 04:52:24 -0400
    • Engine revision f726438d4d
    • Dart version 3.2.0 (build 3.2.0-218.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #135827: Memory Leak: _ScreenshotPaintingContext.toImage does not dispose created _ScreenshotContainerLayer.
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

`_ScreenshotPaintingContext.toImage ` does not dispose created `_ScreenshotContainerLayer` instance.

Test to reveal the leak:

```dart
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:leak_tracker_flutter_testing/leak_tracker_flutter_testing.dart';

import 'widget_inspector_test_utils.dart';

void main() {
  _TestWidgetInspectorService.runTests();
}

class _TestWidgetInspectorService extends TestWidgetInspectorService {
  // These tests need access to protected members of WidgetInspectorService.
  static void runTests() {
    final TestWidgetInspectorService service = TestWidgetInspectorService();
    WidgetInspectorService.instance = service;

    testWidgetsWithLeakTracking('_ScreenshotPaintingContext.toImage leak',
        (WidgetTester tester) async {
      final TestWidgetInspectorService service = TestWidgetInspectorService();

      WidgetInspectorService.instance = service;

      await tester.pumpWidget(
        const Center(
          child: RepaintBoundary(
            child: ColoredBox(
              color: Colors.red,
              child: Padding(
                padding: EdgeInsets.all(100.0),
                child: SizedBox(
                  height: 100.0,
                  width: 100.0,
                ),
              ),
            ),
          ),
        ),
      );

      final Element repaintBoundary =
          find.byType(RepaintBoundary).evaluate().single;

      final ui.Image? screenshot1 = await service.screenshot(
        repaintBoundary,
        width: 300.0,
        height: 300.0,
      );
      addTearDown(() => screenshot1?.dispose());
    }, leakTrackingTestConfig: LeakTrackingTestConfig.debugNotDisposed());
  }
}
```

<details><summary>Test output</summary>

```console
Expected: leak free
  Actual: <Instance of 'Leaks'>
   Which: contains leaks:
          # The text is generated by leak_tracker.
          # For leak troubleshooting tips open:
          # https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md
          notDisposed:
            total: 2
            objects:
              _ScreenshotContainerLayer:
                test: _ScreenshotPaintingContext.toImage leak
                identityHashCode: 557158822
                context:
                  start: >
#6_______flutterEventToLeakTracker_
test_widgets.dart:24
#7______MemoryAllocations.dispatchObjectEvent_
memory_allocations.dart:241
#8______MemoryAllocations.dispatchObjectCreated_
memory_allocations.dart:275
#9______new_Layer_
layer.dart:143
#10_____new_ContainerLayer_(package:flutter/src/rendering/layer.dart)
layer.dart:1
#11_____new_OffsetLayer_(package:flutter/src/rendering/layer.dart)
layer.dart:1
#12_____new__ScreenshotContainerLayer_(package:flutter/src/widgets/widget_inspector.dart)
widget_inspector.dart:1
#13_____new__ScreenshotData_
widget_inspector.dart:339
#14______ScreenshotPaintingContext.toImage_
widget_inspector.dart:563
#15_____WidgetInspectorService.screenshot_
widget_inspector.dart:2096
#16______TestWidgetInspectorService.runTests.<anonymous_closure>_
widget_inspector_1_test.dart:45
                    <asynchronous_suspension>
#17_____testWidgetsWithLeakTracking.wrappedCallBack_
test_widgets.dart:127
                    <asynchronous_suspension>
#18_____testWidgets.<anonymous_closure>.<anonymous_closure>_
widget_tester.dart:168
                    <asynchronous_suspension>
#19_____TestWidgetsFlutterBinding._runTestBody_
binding.dart:1013
                    <asynchronous_suspension>
#20_____StackZoneSpecification._registerCallback.<anonymous_closure>_
stack_zone_specification.dart:114
                    <asynchronous_suspension>
              _ProxyLayer:
                test: _ScreenshotPaintingContext.toImage leak
                identityHashCode: 232357060
                context:
                  start: >
#6_______flutterEventToLeakTracker_
test_widgets.dart:24
#7______MemoryAllocations.dispatchObjectEvent_
memory_allocations.dart:241
#8______MemoryAllocations.dispatchObjectCreated_
memory_allocations.dart:275
#9______new_Layer_
layer.dart:143
#10_____new__ProxyLayer_(package:flutter/src/widgets/widget_inspector.dart)
widget_inspector.dart:1
#11______ScreenshotPaintingContext.toImage_
widget_inspector.dart:574
#12_____WidgetInspectorService.screenshot_
widget_inspector.dart:2096
#13______TestWidgetInspectorService.runTests.<anonymous_closure>_
widget_inspector_1_test.dart:45
                    <asynchronous_suspension>
#14_____testWidgetsWithLeakTracking.wrappedCallBack_
test_widgets.dart:127
                    <asynchronous_suspension>
#15_____testWidgets.<anonymous_closure>.<anonymous_closure>_
widget_tester.dart:168
                    <asynchronous_suspension>
#16_____TestWidgetsFlutterBinding._runTestBody_
binding.dart:1013
                    <asynchronous_suspension>
#17_____StackZoneSpecification._registerCallback.<anonymous_closure>_
stack_zone_specification.dart:114
                    <asynchronous_suspension>
          
          


package:matcher                                                  expect
expect
widget_tester.dart:458
_tearDownTestingWithLeakTracking
test_widgets.dart:82
===== asynchronous gap ===========================
dart:async                                                       _CustomZone.registerBinaryCallback
configureLeakTrackingTearDown.<fn>
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-14.0.pre.580, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.14.0-14.0.pre.580 on channel master at /Users/ksokolovskyi/dev/flutter_master
    • Upstream repository git@github.com:ksokolovskyi/flutter.git
    • FLUTTER_GIT_URL = git@github.com:ksokolovskyi/flutter.git
    • Framework revision ba1d6147ba (28 hours ago), 2023-09-30 04:52:24 -0400
    • Engine revision f726438d4d
    • Dart version 3.2.0 (build 3.2.0-218.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by ksokolovskyi**
This PR fixes several memory leaks in the `widget_inspector.dart`.

### Description
- Fixes https://github.com/flutter/flutter/issues/135824;
- Fixes https://github.com/flutter/flutter/issues/135826;
- Fixes https://github.com/flutter/flutter/issues/135827.

### Tests
- Updates `widget_inspector_test.dart` to use `testWidgetsWithLeakTracking`.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by ksokolovskyi** [comment]
cc @polina-c

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 1]
```diff
@@ -372,6 +372,11 @@ class _ScreenshotData {
   set screenshotOffset(Offset offset) {
     containerLayer.offset = offset;
   }
+
+  /// Releases allocated resources.
```
Comment (polina-c) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:376]: Can you add @mustCallSuper?

Comment (ksokolovskyi) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:376]: Thanks for the review. I added @mustCallSuper in the latest commit.

**Review by polina-c — APPROVED** [review]
