### PR TITLE
Refresh indicator overscroll

### LINKED ISSUE #5320: Bounce overscroll does not occur when using RefreshIndicator
## Steps to Reproduce

Run the flutter gallery on the iOS simulator and attempt to scroll past the bottom of the list in the "Over-scroll" demo. Notice that you do not get any overscroll indication when in "Refresh Indicator" mode.

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision 5e2f04173a (16 minutes ago), engine revision 67a42cd19d

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
```

### PR DESCRIPTION
**Pull request by HansMuller**
The refresh indicator widget now only clamps overscrolling at the scrollable-edge where the refresh indicator appears.
- Added ScrollableEdge enum for identifying one or both limits of a [Scrollable] in terms of the scrollable's scrollDirection.
- Added support for specifying which scrollable edge an OverscrollIndicator appears on.
- Added similar support to ClampOverscrolls.
- On Android, the material app now only adds an overscroll indicator to scrollable edges that aren't already clamped.

Fixes #5320

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 1]
```diff
@@ -19,6 +19,24 @@ import 'page_storage.dart';
 import 'scroll_behavior.dart';
 import 'scroll_configuration.dart';
 
+/// Identifies one or both limits of a [Scrollable] in terms of its scrollDirection.
```
Comment (dragostis) [inline packages/flutter/lib/src/widgets/scrollable.dart]: This should probably explain what *limits* means.

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 2]
```diff
@@ -19,6 +19,24 @@ import 'page_storage.dart';
...
+enum ScrollableEdge {
```
Comment (dragostis) [inline packages/flutter/lib/src/widgets/scrollable.dart]: Would `IndicatorEdge` be a better name?

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 3]
```diff
@@ -19,6 +19,24 @@ import 'page_storage.dart';
...
+  /// The top and bottom of the scrollable if its scrollDirection is vertical
+  /// or the left and right if its scrollDirection is horizontal.
+  both,
+
+  /// Only the top of the scrollable if its scrollDirection is vertical,
+  /// or only the left if its scrollDirection is horizontal.
+  leading,
```
Comment (dragostis) [inline packages/flutter/lib/src/widgets/scrollable.dart]: Wouldn't it be better to give up on a bit of explicitness in order to have more consistent naming and name these `start` and `end` like in other cases?

File: packages/flutter/lib/src/material/overscroll_indicator.dart [hunk 4]
```diff
@@ -97,16 +97,21 @@ class OverscrollIndicator extends StatefulWidget {
...
     assert(child != null);
+    assert(edge != null);
   }
 
   /// Identifies the [Scrollable] descendant of child that the overscroll
   /// indicator will track. Can be null if there's only one [Scrollable]
   /// descendant.
   final Key scrollableKey;
 
+  /// Where the scroll indicator should appear.
```
Comment (dragostis) [inline packages/flutter/lib/src/material/overscroll_indicator.dart]: scroll -> overscroll

File: packages/flutter/lib/src/widgets/scrollable.dart (hunk 3 above)
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/scrollable.dart]: We do use start/end in the same sense for ViewportAnchor.  However edges are usually characterized as leading and trailing. I could change the enum to ScrollableLimit with values start, end, both, none?

Comment (dragostis) [inline packages/flutter/lib/src/widgets/scrollable.dart]: That seems to me like a better name. @Hixie ?

Comment (Hixie) [inline packages/flutter/lib/src/widgets/scrollable.dart]: I don't have a strong opinion here. Generally, in LTR text, start is the left hand side, end is the right hand side, before is above, and after is below. I think it might be confusing to use start/end here because you might be in an RTL context with a reversed vertical scroller in which case "start" would mean the bottom edge and that wouldn't make any sense. So I can see value in leading/trailing.

File: packages/flutter/lib/src/widgets/clamp_overscrolls.dart [hunk 5]
```diff
@@ -13,39 +13,103 @@ import 'scrollable.dart';
...
+  /// based on the given [edge] and the inherited ClampOverscrolls widget for
+  /// the given [context]. For example if edge is ScrollableEdge.leading
+  /// and a ClampOverscrolls ancestor exists that specified ScrollableEdge.trailing,
+  /// then this widget would clamp both scrollable edges.
+  ///
+  /// The [context], [edge] and [child] arguments must not be null.
+  factory ClampOverscrolls.inherit({
+    Key key,
+    @required BuildContext context,
+    @required ScrollableEdge edge: ScrollableEdge.none,
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/clamp_overscrolls.dart]: default values don't make sense with @required

**Comment by Hixie** [comment]
LGTM.

Heads-up: this code is likely to get replaced with my planned scrollable refactor.
