### PR TITLE
[web][upstream] Fix debugPrintStack for web platform

### LINKED ISSUE #37488: [web][upstream] Upstream debugPrintStack fix for web
On the web platform stacktrace.current includes the current methods itself, therefore the top of the stack needs to be removed.

### PR DESCRIPTION
**Pull request by ferhatb**
## Description

Updates debugPrintStack to skip Stacktrace.current that is added to top of stack on web platform.

## Related Issues

Fixes: https://github.com/flutter/flutter/issues/37488
https://github.com/flutter/flutter/issues/37635

## Tests

Updated assertions_test.dart to un-skip previously skipped tests.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter/lib/src/foundation/assertions.dart [hunk 1]
```diff
@@ -747,9 +747,16 @@ class FlutterError extends Error with DiagnosticableTreeMixin implements Asserti
 ///
 /// The `label` argument, if present, will be printed before the stack.
 void debugPrintStack({ String label, int maxFrames }) {
+  const bool isBrowser = identical(0, 0.0);
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/foundation/assertions.dart]: Use the const from foundation

Comment (ferhatb) [reply packages/flutter/lib/src/foundation/assertions.dart]: Updated. thx!

**Review by jonahwilliams — APPROVED** [review]
LGTM
