### PR TITLE
[DropdownButton]: Fix `alignment` parameter doesn't work for `hint` when `isExpanded: true`

### LINKED ISSUE #102751: [DropdownButton]: `alignment` parameter doesn't work for `hint` when `isExpanded: true`
https://master-api.flutter.dev/flutter/material/DropdownButton/alignment.html

> Defines how the hint or the selected item is positioned within the button.
> This property must not be null. It defaults to [AlignmentDirectional.centerStart](https://master-api.flutter.dev/flutter/painting/AlignmentDirectional/centerStart-constant.html).

### Description
`DropdownButton.alignment` should align hint when `isExpanded` is `false` or `true`.

<details> 
<summary>minimal code sample</summary> 

```dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Flutter code sample for DropdownButton.selectedItemBuilder

import 'package:flutter/material.dart';

Map<String, String> cities = <String, String>{
  'New York': 'NYC',
  'Los Angeles': 'LA',
  'San Francisco': 'SF',
  'Chicago': 'CH',
  'Miami': 'MI',
};

void main() => runApp(const DropdownButtonApp());

class DropdownButtonApp extends StatelessWidget {
  const DropdownButtonApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('DropdownButton Sample')),
        body: const Center(child: DropdownButtonExample()),
      ),
    );
  }
}

class DropdownButtonExample extends StatefulWidget {
  const DropdownButtonExample({Key? key}) : super(key: key);

  @override
  State<DropdownButtonExample> createState() => _DropdownButtonExampleState();
}

class _DropdownButtonExampleState extends State<DropdownButtonExample> {
  String? selectedItem;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          DropdownButton<String>(
            value: selectedItem,
            alignment: Alignment.centerRight,
            hint: const Text('Hint'),
            onChanged: (String? string) {
              // This is called when the user selects an item.
              setState(() => selectedItem = string);
            },
            items: cities.keys.map<DropdownMenuItem<String>>((String item) {
              return DropdownMenuItem<String>(
                value: item,
                child: Text(item),
              );
            }).toList(),
          ),
          const SizedBox(height: 20),
          DropdownButton<String>(
            value: selectedItem,
            isExpanded: true,
            alignment: Alignment.centerRight,
            hint: const Text('Hint'),
            onChanged: (String? string) {
              // This is called when the user selects an item.
              setState(() => selectedItem = string);
            },
            items: cities.keys.map<DropdownMenuItem<String>>((String item) {
              return DropdownMenuItem<String>(
                value: item,
                child: Text(item),
              );
            }).toList(),
          ),
        ],
      ),
    );
  }
}

``` 
	
</details>

### Actual Results
Screenshot 2022-04-28 at 14 16 19

### Expected Results

Screenshot 2022-04-28 at 14 16 30

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/102751

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/dropdown_test.dart [hunk 1]
```diff
@@ -3681,4 +3685,58 @@ void main() {
...
+
+    await tester.pumpWidget(buildFrame(
+      buttonKey: buttonKey,
+      mediaSize: const Size(800, 600),
+      isExpanded: true,
+      alignment: AlignmentDirectional.centerEnd,
+      hint: const Text(hintText)),
+    );
+    expect(tester.getTopLeft(find.text(hintText)).dx, 712.0);
+  });
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_test.dart:3741]: LGTM. Just double check, do we need tests to cover AlightmentDirectional.topStart, AlightmentDirectional.topEnd, AlightmentDirectional.bottomStart, AlightmentDirectional.buttomEnd and etc.?

Comment (TahaTesser) [reply packages/flutter/test/material/dropdown_test.dart:3841]: Hey, thanks for looking into this. It makes sense it is certainly possible to align at corners when setting `itemHeight` 
I've updated the test and added comments to make it easier to follow the large test.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d
