### PR TITLE
Keyboard service doesn't commit the last edit when it's dismissed

### LINKED ISSUE #115: Keyboard service doesn't commit the last edit when it's dismissed
<a href="https://github.com/Hixie"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 23, 2015 at 00:41 GMT_
_Originally opened as https://github.com/flutter/engine/issues/227_

----

Steps to reproduce:
1. Focus a text field.
2. Type "aaa".
3. Focus another text field.
4. Focus the text field from step 1.
5. Type "bbb".

The result should be "aaa bbb". However, the "aaa" is discarded by typing "bbb".

### PR DESCRIPTION
**Pull request by abarth**
We were getting the proper values, but we thought we were still composing, so
the text was still underlined.

Fixes #115

### CODE REVIEW

**Comment by abarth** [comment]
@jason-simmons @Hixie

File: packages/flutter/lib/src/material/input.dart [hunk 1]
```diff
@@ -109,6 +109,7 @@ class _InputState extends State<Input> {
                                    _editableString.selection.end);
     } else if (!focused && _keyboardHandle.attached) {
       _keyboardHandle.release();
+      _editableString.composing = TextRange.empty;
```
Comment (eseidelGoogle) [inline packages/flutter/lib/src/material/input.dart]: So this is the real fix, and the rest is just cleanup to use a single static?

Comment (abarth) [inline packages/flutter/lib/src/material/input.dart]: Yeah, I wanted to write this line of code correctly, which required refactoring how to get an empty text range.
