### PR TITLE
[web] do not send SemanticsAction.focus inside frame

### LINKED ISSUE #162472: Web engine must not send SemanticsAction during Frame
SemanticsActions (like pointer and key events) should only be dispatched between frames. The engine should not synchronously dispatch events while the framework is sending a semantics update to the engine.

In the strack trace below, `invokeOnSemanticsAction` must not be synchronously invoked from inside `sendSemanticsUpdate`.
 
```
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 307:3     throw_
package:flutter/src/widgets/binding.dart 1093:9                                 <fn>
package:flutter/src/widgets/binding.dart 1115:14                                [_handleBuildScheduled]
package:flutter/src/widgets/framework.dart 2942:7                               scheduleBuildFor
package:flutter/src/widgets/framework.dart 5306:5                               markNeedsBuild
package:flutter/src/widgets/framework.dart 1227:5                               setState
package:flutter/src/material/ink_well.dart 1098:5                               handleFocusHighlightModeChange
package:flutter/src/widgets/focus_manager.dart 2152:11                          notifyListeners
package:flutter/src/widgets/focus_manager.dart 2333:7                           updateMode
package:flutter/src/widgets/focus_manager.dart 2300:7                           handleSemanticsAction
package:flutter/src/semantics/binding.dart 149:9                                [_handleSemanticsActionEvent]
lib/_engine/engine/platform_dispatcher.dart 1362:5                              invoke1
lib/_engine/engine/platform_dispatcher.dart 1245:5                              invokeOnSemanticsAction
lib/_engine/engine/semantics/text_field.dart 273:34                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27  _callDartFunctionFast1
lib/_engine/engine/dom.dart 668:8                                               DomElementExtension.focusWithoutScroll
lib/_engine/engine/text_editing/text_editing.dart 1584:22                       moveFocusToActiveDomElement
lib/_engine/engine/text_editing/text_editing.dart 1551:5                        enable
lib/_engine/engine/semantics/text_field.dart 81:11                              activate
lib/_engine/engine/semantics/text_field.dart 310:47                             update
lib/_engine/engine/semantics/semantics.dart 1783:28                             [_updateRole]
lib/_engine/engine/semantics/semantics.dart 1512:5                              updateSelf
lib/_engine/engine/semantics/semantics.dart 2592:13                             updateSemantics
lib/_engine/engine/window.dart 110:5                                            updateSemantics
package:flutter/src/rendering/view.dart 386:5                                   updateSemantics
package:flutter/src/rendering/binding.dart 255:48                               <fn>
package:flutter/src/semantics/semantics.dart 3848:22                            sendSemanticsUpdate
package:flutter/src/rendering/object.dart 1381:7                                flushSemantics
package:flutter/src/rendering/object.dart 1383:14                               flushSemantics
package:flutter/src/rendering/binding.dart 623:7                                drawFrame
package:flutter/src/widgets/binding.dart 1231:13                                drawFrame
package:flutter/src/rendering/binding.dart 482:5                                [_handlePersistentFrameCallback]
package:flutter/src/scheduler/binding.dart 1442:7                               [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1355:9                               handleDrawFrame
package:flutter/src/scheduler/binding.dart 1208:5                               [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1347:5                              invoke
lib/_engine/engine/platform_dispatcher.dart 301:5                               invokeOnDrawFrame
lib/_engine/engine/initialization.dart 190:36                                   <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 224:27  _callDartFunctionFast1
```

See also https://github.com/flutter/flutter/blob/a3fced5da1e6734a6087d246094865997cd4b083/engine/src/flutter/lib/web_ui/lib/src/engine/semantics/text_field.dart#L277C43-L277C66

This is blocking https://github.com/flutter/flutter/pull/162417.

### PR DESCRIPTION
**Pull request by yjbanov**
When a `SemanticsAction` fires while rendering a frame, delay it by a zero-length timer.

## Explanation

A concrete situation where this happens is when a semantics update causes DOM focus shift. DOM focus events are delivered synchronously when induced programmatically. We _want_ to notify the framework about the shift. Since it wasn't the framework that decided where the focus moved, the framework may end up out-of-sync with the engine about which widget is currently focused. However, if the framework is still in the middle of rendering a frame, the notification may induce an illegal `setState`. We have to wait until the framework is done before delivering the notification.

## How

* Introduce `FrameService` and consolidate all frame scheduling logic into it (this also makes it way more testable).
* Update all code that needs to schedule frames to use `FrameService`.
* Introduce `isRenderingFrame` boolean that can be used to tell if a frame is being rendered.
* Change `invokeOnSemanticsAction` to use `isRenderingFrame` to decide if the action can be delivered immediately, or delayed by a zero-length timer.

Fixes https://github.com/flutter/flutter/issues/162472

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/frame_reference.dart [hunk 1]
```diff
@@ -2,10 +2,8 @@
 // Use of this source code is governed by a BSD-style license that can be
 // found in the LICENSE file.
 
-/// A monotonically increasing frame number being rendered.
-///
-/// Used for debugging only.
-int debugFrameNumber = 1;
+// TODO(yjbanov): this file should be deleted as part of https://github.com/flutter/flutter/issues/145954
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/frame_reference.dart:5]: Nice catch! I think it's better if we moved the file so that it gets deleted with the html code: https://github.com/flutter/flutter/pull/162608

File: engine/src/flutter/lib/web_ui/lib/src/engine/frame_service.dart [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+  static FrameService get instance => _instance ??= FrameService();
+  static FrameService? _instance;
+
+  /// Overrides the value returned by [instance].
+  ///
+  /// If [mock] is null, resets the value of [instance] back to real
+  /// implementation.
+  ///
+  /// This is intended for tests only.
+  static void debugOverrideFrameService(FrameService? mock) {
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/frame_service.dart:33]:
```suggestion
  @visibleForTesting
  static void debugOverrideFrameService(FrameService? mock) {
```

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart [hunk 3]
```diff
@@ -2595,14 +2595,43 @@ class EngineSemanticsOwner {
...
+  /// the framework. As far as the framework is concerned, the semantics tree is
+  /// being updated as part of rendering a frame, as the last phase that follows
+  /// rendering the [Scene] into a [FlutterView]. The framework does not
+  /// anticipate to receive any events that lead to widget state changes that
+  /// alter the current frame's contents. That must be done in the next frame.
+  ///
+  /// DOM event handlers whose notifications to the framework result in state
+  /// changes may want to delay their notifications, e.g. by scheduling them in
+  /// a timer.
+  bool get isUpdatingSemanticsTree => _isUpdatingSemanticsTree;
```
Comment (mdebbar) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/semantics.dart:2613]: I'm guessing this is leftover from a previous iteration? It's not being used anywhere.

**Review by mdebbar — APPROVED** [review]
