### PR TITLE
[flutter_tools] Catch rpc error in render frame with raster stats

### LINKED ISSUE #143010: [flutter_tools] RPCError: _flutter.renderFrameWithRasterStats: (-32000) Raster status not supported on Impeller backend
Top crasher on `beta/3.19.0-0.4.pre`
With command `flutter run`

```
RPCError: _flutter.renderFrameWithRasterStats: (-32000) Raster status not supported on Impeller backend.
at new _OutstandingRequest(vm_service.dart:265)
at VmService._call.<anonymous closure>(vm_service.dart:1771)
at VmService._call(vm_service.dart:1783)
at VmService.callServiceExtension(vm_service.dart:1733)
at VmService.callMethod(vm_service.dart:1716)
at FlutterVmService.callMethodWrapper(vmservice.dart:501)
at FlutterVmService.renderFrameWithRasterStats(vmservice.dart:601)
at ResidentHandlers.debugFrameJankMetrics(resident_runner.dart:726)
at <asynchronous gap>(async)
at TerminalHandler.processTerminalInput(resident_runner.dart:1830)
at <asynchronous gap>(async)
```

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/143010. This is intended to be cherrypicked into the 3.19 and 3.20 releases.

Long-term, we should deprecate this feature: https://github.com/flutter/flutter/issues/144191

### CODE REVIEW

File: packages/flutter_tools/lib/src/resident_runner.dart [hunk 1]
```diff
@@ -714,23 +714,30 @@ abstract class ResidentHandlers {
...
+              'json',
+            );
+            tempFile.writeAsStringSync(jsonEncode(rasterData), flush: true);
+            logger.printStatus('Wrote jank metrics to ${tempFile.absolute.path}');
+          } else {
+            logger.printWarning('Unable to get jank metrics.');
+          }
+        }
+      } on vm_service.RPCError catch (err) {
+        if (err.code != RPCErrorCodes.kServerError || !err.message.contains('Raster status not supported on Impeller backend')) {
```
Comment (eliasyishak) [inline packages/flutter_tools/lib/src/resident_runner.dart:737]: Will this always be the case for Impeller?

**Review by eliasyishak — APPROVED** [review]
LGTM, we should add a TODO where i commented if Impeller supports `ResidentHandlers.debugFrameJankMetrics()` in the future

File: packages/flutter_tools/lib/src/resident_runner.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/resident_runner.dart:737]: Yes, the whole feature will be deleted, in which case it will stlil not support Impeller :) https://github.com/flutter/flutter/issues/144191
