### PR TITLE
Fix text field clipping when erasing rapidly.

### LINKED ISSUE #22288: Text edit displays outside of box when erasing quickly.
When rapidly erasing lines from a scrolling text box, the text that should be hidden due to it being outside of the box incorrectly appears.

To reproduce:

1. Open Flutter gallery
2. Select "Material"
3. Select "Text Fields"
4. Type many lines of short text in the "Life story" section (at least 6, the more the better)
5. Rapidly erase the lines. The first few hidden lines will appear as the text scrolls up.

### PR DESCRIPTION
**Pull request by sjindel-google**
`RenderEditable.paint` assumes that if the length of the text fits within the
visible region, then the text will be rendered at the start of the region and be
completely visible. This is not always true, since the text may still be
rendered at an offset if an animation is ongoing when the text begins to fit.

This fixes #22288 and #14121

### CODE REVIEW

**Review by GaryQian — APPROVED** [review]
Thanks for fixing! Do you think you could add a test to make sure we don't regress? Otherwise, LGTM.

**Comment by sjindel-google** [comment]
> Thanks for fixing! Do you think you could add a test to make sure we don't regress? Otherwise, LGTM.

Done, although I've refactored the implementation a little to make it easier to test. Please take another look since this is my first Flutter PR.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -921,7 +921,11 @@ class RenderEditable extends RenderBox {
     return null;
   }
 
-  bool _hasVisualOverflow = false;
+  double _maxScrollExtent = 0;
+
+    // We need to check the paint offset here because during animation, the start of
+    // the text may position outside the visible region even when the text fits.
+  bool get hasVisualOverflow => _maxScrollExtent > 0 || _paintOffset != Offset.zero;
```
[the remark this answers is not in the document]
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Done. The reason I made it public was to access the getter from the test. I've changed the test to use a mock painting canvas instead.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 2]
```diff
@@ -921,7 +921,11 @@ class RenderEditable extends RenderBox {
     return null;
   }
 
-  bool _hasVisualOverflow = false;
+  double _maxScrollExtent = 0;
+
+    // We need to check the paint offset here because during animation, the start of
+    // the text may position outside the visible region even when the text fits.
```
Comment (GaryQian) [inline packages/flutter/lib/src/rendering/editable.dart]: nit: align comments.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 3]
```diff
@@ -104,8 +104,7 @@ class _TextSelectionToolbarLayout extends SingleChildLayoutDelegate {
   }
 }
 
-/// Draws a single text selection handle. The [type] determines where the handle
-/// points (e.g. the [left] handle points up and to the right).
+/// Draws a single text selection handle which points up and to the left.
```
Comment (GaryQian) [inline packages/flutter/lib/src/material/text_selection.dart]: The old comment seemed to explain this better? Has the behavior here changed?

**Comment by GaryQian** [comment]
A few nits, otherwise LGTM!

File: packages/flutter/lib/src/material/text_selection.dart (hunk 3 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/material/text_selection.dart]: The behavior hasn't actually changed, but the old comment refers to [type] and [left] which aren't actually used in this class. This class always draws the caret up and to the right. It then gets rotated later in `buildHandle`, at `material/text_selection.dart:173`.

Comment (GaryQian) [reply packages/flutter/lib/src/material/text_selection.dart]: Ahh ok, I see!

File: packages/flutter/lib/src/rendering/editable.dart (hunk 2 above)
Comment (sjindel-google) [reply packages/flutter/lib/src/rendering/editable.dart]: Done.
