### PR TITLE
Fix missing await

### LINKED ISSUE #9612: Can't deploy on Android or IOS with IDE
Despite flutter doctor reporting I have both devices connected.

I did a flutter upgrade in the morning which I think could have caused it, since last night it was working fine.

I've restarted my mac and IDE also

screenshot 2017-04-26 13 24 35

[✓] Flutter (on Mac OS X 10.12.5 16F67a, channel master)
    • Flutter at /Users/FaisalAbid/Development/workspace/Verve/Elixer/flutter
    • Framework revision 21f57a85e8 (17 hours ago), 2017-04-25 17:40:28 -0700
    • Engine revision a5b64899c9
    • Tools Dart version 1.23.0-dev.11.11

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/FaisalAbid/Library/Android/sdk/
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/FaisalAbid/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.0

[✓] Connected devices
    • Pixel XL • HT6A60208436                         • android-arm • Android 7.1.2 (API 25)
    • iPhone 6 • 420A0FA6-F4C4-442E-A398-A912FC17917E • ios         • iOS 10.3 (simulator)

### PR DESCRIPTION
**Pull request by tvolkert**
Fixes #9612

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
This is why folks dream that an unawaited_futures lint could work. :D  @Hixie

**Review by devoncarew — APPROVED** [review]

File: packages/flutter_tools/lib/src/commands/daemon.dart [hunk 1]
```diff
@@ -655,7 +655,7 @@ Future<Map<String, dynamic>> _deviceToMap(Device device) async {
     'id': device.id,
     'name': device.name,
     'platform': getNameForTargetPlatform(await device.targetPlatform),
-    'emulator': device.isLocalEmulator
+    'emulator': await device.isLocalEmulator,
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/daemon.dart]: why are we using a map here instead of a structured class? it would have caught this problem.

Comment (tvolkert) [inline packages/flutter_tools/lib/src/commands/daemon.dart]: @Hixie so that it's natively encodable into JSON, which is apparently how we communicate info to our IntelliJ plugin

Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/daemon.dart]: mmmm k :-)
