### PR TITLE
fix(a11y): check for remaining relevant text direction properties

### LINKED ISSUE #165051: A11y: textDirection not set correctly when using attributedXY parameters
### Steps to reproduce

We faced an issue that the assert at https://github.com/flutter/flutter/blob/3.29.1/packages/flutter/lib/src/semantics/semantics.dart#L497-L500 was triggering although our widget was placed under a `MaterialApp` and therefore had a text direction set.

Turns out that `_getTextDirection()` just was not checking for `attributedValue`, etc.

### Expected results

`textDirection` is correctly set.

### Actual results

`textDirection` is not set and the assert is being triggered.

### Code sample

```dart
testWidgets('semantics with attributed value should not fail',
    (tester) async {
  await tester.pumpWidget(
    MaterialApp(
      home: Semantics(
        attributedValue: AttributedString('test value'),
        child: const Placeholder(),
      ),
    ),
  );
});
```

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.26100.3194], locale de-DE)
    • Flutter version 3.24.5 on channel stable at C:\Users\goddc\fvm\versions\3.24.5@stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (4 months ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\goddc\dev\android-sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: C:\Program Files\Microsoft\jdk-17.0.13.11-hotspot\bin\java
    • Java version OpenJDK Runtime Environment Microsoft-10376486 (build 17.0.13+11-LTS)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.13.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.13.35825.156
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[√] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.98.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.106.0

[√] Connected device (3 available)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version
      10.0.26100.3194]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 134.0.6998.37
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 133.0.3065.69        

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by Goddchen**
We faced an issue that the assert at https://github.com/flutter/flutter/blob/3.29.1/packages/flutter/lib/src/semantics/semantics.dart#L497-L500 was triggering although our widget was placed under a `MaterialApp` and therefore had a text direction set.

Turns out that `_getTextDirection()` just was not checking for `attributedValue`, etc.

Related issue: https://github.com/flutter/flutter/issues/165051
fixes https://github.com/flutter/flutter/issues/165051
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by lColinDl** [comment]
Here's a standalone test to reproduce the bug and verify that it's fixed:
```
testWidgets('semantics with attributed value should not fail',
    (tester) async {
  await tester.pumpWidget(
    MaterialApp(
      home: Semantics(
        attributedValue: AttributedString('test value'),
        child: const Placeholder(),
      ),
    ),
  );
});
```

**Review by justinmc — COMMENTED** [review]
@Goddchen Sorry for the late review here. Thanks for fixing this.

Can you add a test? @lColinDl has a good suggestion in https://github.com/flutter/flutter/pull/165028#issuecomment-2720317919. I would just add  this to the bottom I think: `expect(tester.takeException(), isNull);`.

**Comment by Goddchen** [comment]
@justinmc done ✅ 
Not sure what is up with that failing `Linux build_tests_2_5` job. It fails while downloading Gradle 🤷‍♂️ Do you have any idea?

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

I've rerun that failing test, looks like an infrastructure failure. I'll try to find a secondary reviewer.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 1]
```diff
@@ -7568,7 +7568,13 @@ class Semantics extends SingleChildRenderObjectWidget {
...
         properties.label != null ||
+        properties.attributedDecreasedValue != null ||
+        properties.attributedIncreasedValue != null ||
+        properties.attributedValue != null ||
+        properties.decreasedValue != null ||
+        properties.increasedValue != null ||
         properties.value != null ||
+        properties.attributedHint != null ||
         properties.hint != null ||
         properties.tooltip != null;
```
Comment (gnprice) [inline packages/flutter/lib/src/widgets/basic.dart:7579]: I'm thinking about how to help make this more easily kept in sync in the future. I think a useful tactic would be to list these attributes in the same order they're declared on SemanticsProperties:

image

That'd help make it easy to compare this code to that list by eye and check if anything's missing. Conveniently it's also an order that has a nice internal consistency to it: all in pairs `foo` then `attributedFoo` (except the one outlier `tooltip`).

**Review by gnprice — APPROVED** [review]
LGTM, but one small suggestion.

File: packages/flutter/lib/src/widgets/basic.dart (hunk 1 above)
Comment (Goddchen) [reply packages/flutter/lib/src/widgets/basic.dart]: @gnprice done in f9ef22a68bdde5dba0c83ca08ee1d5411c0b1470

**Comment by Goddchen** [comment]
Absolutely no clue why these 2 jobs failed, any ideas @gnprice @justinmc ?

**Comment by gnprice** [comment]
One failure is:
> tree-status — Tree is currently broken. Please do not merge this PR unless it contains a fix for the tree.

So that means there's a problem unrelated to this PR. There's a few more words on "tree status" here:
https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#introduction

That one will automatically go green when the tree gets fixed, so there's nothing you need to do.

---

The other is Google testing. More about that here:
https://github.com/flutter/flutter/blob/master/docs/infra/Understanding-Google-Testing.md

You'll need a Google employee to investigate that one — so that means @justinmc :-)

**Comment by Goddchen** [comment]
thanks for the clarification. The tree status job is green again. @justinmc can you check on the "Google testing" job? Or can I do anything there?

**Comment by justinmc** [comment]
Looks like the Google test failure was a timeout? Hopefully just that. I've rerun it.
