### PR TITLE
Check if reg can run before calling it on Windows

### LINKED ISSUE #79896: registry lookup for microsoft edge can fail, fallback to assuming unsupported version?
```
ProcessException: Failed to find "reg" in the search path.
  Command: reg 
  
  
  | at LocalProcessManager.run | (local_process_manager.dart:89)
-- | -- | --
  | at ErrorHandlingProcessManager.run.<anonymous closure> | (error_handling_io.dart:642)
  | at _run | (error_handling_io.dart:544)
  | at ErrorHandlingProcessManager.run | (error_handling_io.dart:641)
  | at MicrosoftEdgeDevice._getSdkNameAndVersion | (web_device.dart:273)
  | at MicrosoftEdgeDevice.sdkNameAndVersion | (web_device.dart:270)
  | at MicrosoftEdgeDevice._meetsVersionConstraint | (web_device.dart:261)
  | at WebDevices.pollingGetDevices | (web_device.dart:355)
  | at PollingDeviceDiscovery._initTimer.<anonymous closure> | (device.dart:370)
  | at PollingDeviceDiscovery._initTimer.<anonymous closure> | (device.dart:368)
  | at _rootRun | (zone.dart:1346)
  | at _CustomZone.run | (zone.dart:1258)
  | at _CustomZone.runGuarded | (zone.dart:1162)
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:1202)
  | at _rootRun | (zone.dart:1354)
  | at _CustomZone.run | (zone.dart:1258)
  | at _CustomZone.bindCallback.<anonymous closure> | (zone.dart:1186)
  | at Timer._createTimer.<anonymous closure> | (timer_patch.dart:18)
  | at _Timer._runTimers | (timer_impl.dart:395)
  | at _Timer._handleMessage | (timer_impl.dart:426)
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:184)


  ```

### PR DESCRIPTION
**Pull request by jmagman**
Check if `reg` is on search path before checking registry values.

Fixes https://github.com/flutter/flutter/issues/79896

### CODE REVIEW

File: packages/flutter_tools/lib/src/web/web_device.dart [hunk 1]
```diff
@@ -210,13 +210,15 @@ class GoogleChromeDevice extends ChromiumDevice {
...
-          version = 'Google Chrome ' + parts[parts.length - 2];
+      if (_processManager.canRun('reg')) {
+        final ProcessResult result = await _processManager.run(<String>[
+          r'reg', 'query', r'HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon', '/v', 'version',
+        ]);
+        if (result.exitCode == 0) {
+          final List<String> parts = (result.stdout as String).split(RegExp(r'\s+'));
+          if (parts.length > 2) {
+            version = 'Google Chrome ' + parts[parts.length - 2];
+          }
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/web/web_device.dart:221]: Whitespace only.

File: packages/flutter_tools/lib/src/web/web_device.dart [hunk 2]
```diff
@@ -270,13 +271,15 @@ class MicrosoftEdgeDevice extends ChromiumDevice {
...
-        return 'Microsoft Edge ' + parts[parts.length - 2];
+    if (_processManager.canRun('reg')) {
+      final ProcessResult result = await _processManager.run(<String>[
+        r'reg', 'query', r'HKEY_CURRENT_USER\Software\Microsoft\Edge\BLBeacon', '/v', 'version',
+      ]);
+      if (result.exitCode == 0) {
+        final List<String> parts = (result.stdout as String).split(RegExp(r'\s+'));
+        if (parts.length > 2) {
+          return 'Microsoft Edge ' + parts[parts.length - 2];
+        }
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/web/web_device.dart:282]: Whitespace only.

File: packages/flutter_tools/test/general.shard/web/devices_test.dart [hunk 3]
```diff
@@ -255,6 +255,42 @@ void main() {
...
+      logger: BufferLogger.test(),
+    );
+    final MicrosoftEdgeDevice edgeDevice = MicrosoftEdgeDevice(
+      chromiumLauncher: chromeLauncher,
+      fileSystem: MemoryFileSystem.test(),
+      logger: BufferLogger.test(),
+      processManager: processManager,
+    );
+
+    expect(edgeDevice.isSupported(), true);
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/web/devices_test.dart:279]: so we will still detect edge, it's just `sdkNameAndVersion` will be empty? is this what we should be doing if we can't verify it's chromium-based?

Comment (jmagman) [reply packages/flutter_tools/test/general.shard/web/devices_test.dart:279]: It looks like the empty string is used to make sure it fails the version constraint check later (although you'd think `sdkNameAndVersion` would be `'unknown` like the `GoogleChromeDevice` one):
https://github.com/flutter/flutter/blob/152af5aba7eddf8f25c9369313986e8da8973484/packages/flutter_tools/lib/src/web/web_device.dart#L282-L284

I see https://github.com/flutter/flutter/pull/56173#discussion_r419719180 as well.  \cc @jonahwilliams

**Review by jonahwilliams — APPROVED** [review]
I have no memory of this place....

Code looks good though, LGTM

File: packages/flutter_tools/test/general.shard/web/devices_test.dart (hunk 3 above)
Comment (jmagman) [reply packages/flutter_tools/test/general.shard/web/devices_test.dart:279]: It seems like it will fall through to a version check failure, are you fine with this change as-is, @christopherfujino?  I can also dig in more and try to figure out another way to verify it's chromium based (though I don't have a Windows dev environment). I would hope `reg` being missing from the search path is pretty rare.

**Review by christopherfujino — APPROVED** [review]
lgtm
