### PR TITLE
[flutter_tools/dap] Inform DAP client whether restart is supported

### LINKED ISSUE #4281: Handle debugger restart request (with a cold restart) for Flutter profile/release mode
See https://github.com/Dart-Code/Dart-Code/issues/4276#issuecomment-1325338777.

-----

We can't hide the "restart" button (which we usually use for _Hot_ Restart) because VS Code doesn't allow it (restart should always be possible, even if it's not a Hot Restart, because it should just be the same as stopping the session and starting it again). We also can't currently tell VS Code to handle the restart because we only know about profile/release flags in launchRequest (not during startup when capabilities are exchanged).

So there are a few options:

1. Do nothing. This means the restart button on the debug toolbar will not work, and instead prints an error to the console in profile/release mode:
    > Failed to Hot Restart: DebugAdapterException: Exception: Restart is not supported in profile mode
2. Handle restartRequest in the DAP and terminate the `flutter run` process, clean up all state, and then restart it (this is probably the best solution, but also complex)
3. Pass an additional flag for profile/release mode to the `flutter debug_adapter` process so it's known before `launchRequest`, and use that to set the `supportsRestartRequest` capability.

1 is ofc easiest, but I think we should probably do 2.

(on a related note, we should ensure Hot Restart commands are disabled/hidden from the palette etc., since we're just implementing a standard restart here, and having Hot Restart commands show up may be confusing where it's not supporting and we will do a cold restart).

### PR DESCRIPTION
**Pull request by DanTup**
Before this change, the Flutter adapter always sent "supportsRestartRequest: true" to the DAP client. This told the DAP client if the user clicks the "Restart" button on the debug toolbar that we (the DAP server) will handle the restart (allowing us to Hot Restart instead of a slower termination and restart of the entire debug session).

However, Profile/Release mode do not support Hot Restart, so this would result in an error "Hot Restart failed".

This change no longer sets `supportsRestartRequest: true` at startup, but instead waits for the `app.start` event, and sends the value of its `supportsRestart` field (an existing field that was already available in the `app.start` event).

This results in Hot Restart being available for debug builds, but the DAP client/IDE performing a full debug session restart for other modes.

Fixes https://github.com/Dart-Code/Dart-Code/issues/4281.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/debug_adapters/flutter_adapter.dart [hunk 1]
```diff
@@ -399,6 +392,12 @@ class FlutterDebugAdapter extends FlutterBaseDebugAdapter {
     if (_appId == null) {
       throw DebugAdapterException('Unexpected null `appId` in app.start event');
     }
+
+    // Notify the client whether it can call 'restartRequest' when the user
+    // clicks restart, instead of terminating and re-starting its own debug
+    //session (which is much slower, but required for profile/release mode).
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/debug_adapters/flutter_adapter.dart:398]:
```suggestion
    // session (which is much slower, but required for profile/release mode).
```

**Review by christopherfujino — APPROVED** [review]
nit about comment, but otherwise LGTM

**Comment by DanTup** [comment]
Fixed, thanks!
