### PR TITLE
Skip [tool] crash reporting on `--local-engine`

### LINKED ISSUE #70238: Disable tool crash logging when running with a locally built engine
These crashes tend not to be informative and are generally not possible to reproduce/fix without access to the locally built engine.

/cc @jonahwilliams

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/70238.

### CODE REVIEW

**Review by jason-simmons — APPROVED** [review]

File: packages/flutter_tools/lib/runner.dart [hunk 1]
```diff
@@ -152,6 +156,7 @@ Future<int> _handleToolError(
   bool reportCrashes,
   String Function() getFlutterVersion,
   ShutdownHooks shutdownHooks, {
+  required bool usingLocalEngine,
```
Comment (gaaclarke) [inline packages/flutter_tools/lib/runner.dart:159]: Instead of introducing a new instance variable, can't we just set `reportCrashes` appropriately when we have a local engine?  (ie solve this problem one level higher?)

**Review by gaaclarke — APPROVED** [review]

**Review by justinmc — APPROVED** [review]
LGTM :+1:

File: packages/flutter_tools/lib/runner.dart (hunk 1 above)
Comment (gaaclarke) [reply packages/flutter_tools/lib/runner.dart:159]: @matanlurey friendly ping on this question.  I don't think it was worth holding back the approval, but I'm still interested in a response
