### PR TITLE
Don't fail docs-linux on release branches

### LINKED ISSUE #64068: docs-linux failing on release branches
https://github.com/flutter/flutter/runs/999350932

ex failure:  Docs deployment cannot be run on the flutter-1.21-candidate.9 branch.

cc @tvolkert @christopherfujino

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

Don't fail if we reach the `deploy_docs()` function and the branch isn't either master or stable. This returns the behavior prior to https://github.com/christopherfujino/flutter/commit/8e0eee9008157df879353d92b394c788d5a7b361.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/64068

### CODE REVIEW

File: dev/bots/docs.sh [hunk 1]
```diff
@@ -9,7 +9,7 @@ function deploy {
   local total_tries="$1"
   local remaining_tries=$(($total_tries - 1))
   shift
-  while [[ "$remaining_tries" > 0 ]]; do
+  while [[ "$remaining_tries" -gt 0 ]]; do
```
Comment (christopherfujino) [inline dev/bots/docs.sh:12]: this was a shellcheck error, not sure if this did what it was supposed to.

**Review by tvolkert — APPROVED** [review]

File: dev/bots/docs.sh (hunk 1 above)
Comment (gspencergoog) [reply dev/bots/docs.sh:12]: `-gt` is correct.
