### PR TITLE
Cupertino sheet MediaQuery values

### LINKED ISSUE #167943: CupertinoSheet page content taking wrong MediaQuery values
### Steps to reproduce

Use widgets that use MediaQuery properties to constrain their size/position, like Appbar and SafeArea in the pageBuilder of the showCupertinoSheet function.

### Expected results

- Widgets wrapped in safe area should be visible and not go under the screen
- Appbar should be aligned to the top since there's no top padding for the sheet content.

### Actual results

- Widgets wrapped in SafeArea go under the visible area of the screen
- Appbar is aligned wrongly since MediaQuery padding has a non-zero value.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Builder(
        builder: (context) {
          return Scaffold(
            appBar: AppBar(
              backgroundColor: Theme.of(context).colorScheme.inversePrimary,
              title: Text('Show cupertino sheet demo'),
            ),
            body: Center(
              child: ElevatedButton(
                onPressed: () {
                  showCupertinoSheet(
                    context: context,
                    pageBuilder: (context) {
                      Widget child = SafeArea(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Container(
                              height: 80,
                              width: double.infinity,
                              color: Colors.pink,
                            ),
                            Container(
                              height: 80,
                              width: double.infinity,
                              color: Colors.green,
                            ),
                          ],
                        ),
                      );

                      // return CupertinoPageScaffold(
                      //   navigationBar: CupertinoNavigationBar(previousPageTitle: 'Hello'),
                      //   child: child,
                      // );
                      return Scaffold(
                        appBar: AppBar(title: Text('Hello')),
                        body: child,
                      );
                    },
                  );
                },
                child: Text('Open cupertino bottom sheet'),
              ),
            ),
          );
        },
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Scaffold and CupertinoPageScaffold screenshots from the above code sample</summary>

Image

Image

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4 24E248 darwin-arm64, locale en-NG) [2.6s]
    • Flutter version 3.29.3 on channel stable at /Users/sebastine/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (2 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [6.8s]
    • Android SDK at /Users/sebastine/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Users/sebastine/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 16.3) [1,577ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    ! CocoaPods 1.15.2 out of date (1.16.2 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✓] Chrome - develop for the web [337ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [337ms]
    • Android Studio at /Users/sebastine/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] Android Studio (version 2024.2) [334ms]
    • Android Studio at /Users/sebastine/Library/Caches/JetBrains/Toolbox/backup/AndroidStudio-242.23726.103.2422.13016713-4739872658208990322/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] IntelliJ IDEA Ultimate Edition (version 2025.1) [334ms]
    • IntelliJ at /Users/sebastine/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 85.2.4
    • Dart plugin version 251.25267.1

[✓] VS Code (version 1.99.2) [16ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.108.0

[✓] Connected device (4 available) [6.9s]
    • iPhone 15 Pro (mobile)          • 324C2CAF-F3BD-4D88-997B-BCECB503FB34 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.4 24E248 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.4 24E248 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 135.0.7049.115
    ! Error: Browsing on the local area network for Sebastine’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [1,200ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by CoderNamedHendrick**
There's an issue with the Cupertino sheet route in the current stable version of Flutter. However, it was partly fixed in master. This PR addresses passing the appropriate bottom padding values to the page content, which ensures widgets placed in Safe Areas are laid out correctly.

Before
image

After
image

Fixes [#167943](https://github.com/flutter/flutter/issues/167943)

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/cupertino/sheet_test.dart [hunk 1]
```diff
@@ -1339,4 +1339,99 @@ void main() {
...
+          },
+        ),
+      );
+
+      expect(find.text('Page 1'), findsOneWidget);
+
+      await tester.tap(find.text('Push Page 2'));
+      await tester.pumpAndSettle();
+
+      expect(find.byType(Container), findsExactly(2));
```
Comment (MitchellGoodwin) [inline packages/flutter/test/cupertino/sheet_test.dart:1412]: Nit: prefer not to have this check. It doesn't seem needed and if another widget in this test adds a Container for some reason and breaks this, that could be annoying.

File: packages/flutter/test/cupertino/sheet_test.dart [hunk 2]
```diff
@@ -1339,4 +1339,99 @@ void main() {
...
+    'content placed in safe area of showCupertinoSheet is rendered within the safe area bounds',
+    (WidgetTester tester) async {
+      final GlobalKey scaffoldKey = GlobalKey();
+
+      Widget sheetScaffoldContent(BuildContext context) {
+        return SafeArea(
+          child: Column(
+            mainAxisAlignment: MainAxisAlignment.spaceBetween,
+            children: <Widget>[
+              Container(
```
Comment (MitchellGoodwin) [inline packages/flutter/test/cupertino/sheet_test.dart:1353]: Turbo nit: If we made these widgets `SizedBox`s instead of Containers we could make more of this constant. The colors aren't necessary for the test.

**Review by MitchellGoodwin — COMMENTED** [review]
Thanks for submitting a PR to make this improvement. I left some comments.

File: packages/flutter/test/cupertino/sheet_test.dart (hunk 1 above)
Comment (CoderNamedHendrick) [reply packages/flutter/test/cupertino/sheet_test.dart:1412]: Will remove this, thanks🚀

File: packages/flutter/test/cupertino/sheet_test.dart (hunk 2 above)
Comment (CoderNamedHendrick) [reply packages/flutter/test/cupertino/sheet_test.dart:1353]: You're right

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for the fix. In order to get this merged, it will need a second approval. I'll ask around.

**Review by Piinks — APPROVED** [review]
LGTM! Welcome @CoderNamedHendrick! Thanks for contributing.
