### PR TITLE
Fix TextField selects all content after the application is resumed

### LINKED ISSUE #156078: [TextField] When switching to another browser tab or window and then going back, all text on TextField is selected automatically
### Steps to reproduce

Could work with any text field as far as I know. Here is a dart pad : https://dartpad.dev/?id=c1df1f23d5be833eb2f45004a2c37d63&channel=main

1. ensure the field is focused (by clicking on it)
2. switch tab or window
3. go back to the demo tab

The whole text field content is now selected. 

### Expected results

The cursor stays at the same position as before, or at least not all the text is selected

### Actual results

all the text is selected, leading to accidental text deletion

### Code sample

<details open><summary>Code sample</summary>

```dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: TextField(
          autofocus: true,
          controller: TextEditingController(
            text: 'Some text I do not people to accidentally delete',
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/89409723-0dff-47c7-b71e-ead985a97ea9

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on Fedora Linux 40 (Workstation Edition)
    6.10.11-200.fc40.x86_64, locale fr_FR.UTF-8)
    • Flutter version 3.22.2 on channel stable at
      /home/thareau/Logiciels/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (il y a 4 mois), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/thareau/Logiciels/AndroidSdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (Red_Hat-17.0.12.0.7-2) (build
      17.0.12+7)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang),
      or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake),
      or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install
      ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    • pkg-config version 2.1.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install
      libgtk-3-dev)

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2)
    • IntelliJ at
      /home/thareau/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin version 81.1.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Fedora Linux 40 (Workstation
      Edition) 6.10.11-200.fc40.x86_64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR makes `EditableText` aware of the lifecycle 'resumed' state to let the current selection unchanged when the application is resumed (on web and desktop, 'resumed' means the Flutter app window regained focus).

Before this PR, on web and desktop, the whole content of a `TextField` was selected whenever a `TextField` gained focus. This is the correct behavior when tabbing between fields but it is not when a field regains focus after the application is resumed 

## Related Issue

Fixes [When switching to another browser tab or window and then going back, all text on TextField is selected automatically](https://github.com/flutter/flutter/issues/156078).

## Tests

Adds 1 test.

### CODE REVIEW

**Review by justinmc — COMMENTED** [review]
I feel like this approach LGTM... It does seem like it should be possible to know the cause of a focus change, but without that functionality, this seems to be the best way to do it. @gspencergoog is this a reliable way to do this or is there a better way?

If Greg is onboard then this just needs a test and a comment somewhere explaining what this is for, maybe on the declaration of justResumed.

I checked out the code locally and confirmed that it works in all the situations it should:

| Scenario | Works? |
| --- | --- |
| Changing to another window and returning on desktop (Linux) | :heavy_check_mark: |
| Changing tabs on Chrome | :heavy_check_mark: |
| Changing to another window and returning to Chrome | :heavy_check_mark: |

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

This seems good to me.  Transitioning to `resumed` can occur on app startup too (`resumed` is just the "running while focused" state of an app), but I think that not selecting the whole text in that case is probably the right behavior anyhow.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 1]
```diff
@@ -17017,6 +17017,45 @@ void main() {
...
+
+      expect(focusNode1.hasFocus, true);
+      expect(controller1.selection, collapsedAtEnd('Flutter!').selection);
+
+      await setAppLifeCycleState(AppLifecycleState.inactive);
+      await setAppLifeCycleState(AppLifecycleState.resumed);
+
+      expect(focusNode1.hasFocus, true);
+      expect(controller1.selection, collapsedAtEnd('Flutter!').selection);
+    }, variant: TargetPlatformVariant.all());
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:17058]: Nit: Is `TargetPlatformVariant.all()` necessary? I think the behavior will be the same for all platform variants.

**Review by justinmc — APPROVED** [review]
LGTM :+1:

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/test/widgets/editable_text_test.dart:17058]: Good point, I think it is important to keep it, otherwise this test will not fail if the fix is removed (the 'select all' behavior is only desktop and web so the logic I added to fix this issue is not used on Android).

**Comment by jacobsimionato** [comment]
Reason for revert: Google3 roll failing - see b/375019489

**Comment by jacobsimionato** [comment]
I'm sorry for the revert here! So what happened is some Google integration tests failed at this line:
https://github.com/flutter/flutter/blob/48149781f258360dde672f03b1447b28e1211837/packages/flutter/lib/src/widgets/app_lifecycle_listener.dart#L253

```
'package:flutter/src/widgets/app_lifecycle_listener.dart': Failed assertion: line 253 pos 16: 'previousState == null || previousState == AppLifecycleState.hidden': Invalid state transition from AppLifecycleState.resumed to AppLifecycleState.paused
```

The test logic is doing something like:
```
// Enter some text in text fields, click some buttons

tester.binding.handleAppLifecycleStateChanged(AppLifecycleState.paused);
```

I imagine the test logic needs updating, but I'm not sure exactly what to do yet, hence the revert. Should I try to fix this by simulating a change to the 'hidden' state before 'paused' ?
```
tester.binding.handleAppLifecycleStateChanged(AppLifecycleState.hidden);
```

**Comment by gspencergoog** [comment]
@jacobsimionato See [this diagram for the allowed state transitions](https://docs.google.com/document/d/1FL5Fgk7EzMNOpJL0GZJt-lfWtGt2igHuC2ZznItS2l8/edit?resourcekey=0-IZNfpSVPkMbigQLLXoJcfw&tab=t.0#bookmark=id.h96bgmvzhhpu) (or [this one](https://docs.google.com/document/d/1FL5Fgk7EzMNOpJL0GZJt-lfWtGt2igHuC2ZznItS2l8/edit?resourcekey=0-IZNfpSVPkMbigQLLXoJcfw&tab=t.0#bookmark=id.revfj0mdtaf9))

I think the test is doing an invalid state transition, and one that the engine wouldn't send.  The engine implementations are coded to synthesize any intermediate state transitions if the platform jumps from one to another so that the state machine is followed, and an application can count on getting all the states in the expected order.

So, yes, you should probably add that transition, but if the test is expected to start in a particular state, then you should generate any intermediate states too, so if, for instance, the test starts at `resumed`, it should generate these states to get to paused:

```dart
tester.binding.handleAppLifecycleStateChanged(AppLifecycleState.inactive);
tester.binding.handleAppLifecycleStateChanged(AppLifecycleState.hidden);
tester.binding.handleAppLifecycleStateChanged(AppLifecycleState.paused);
```

**Comment by jacobsimionato** [comment]
I've now updated the internal tests to do the valid state transitions as you suggested.

@bleroux could you reland the PR? Sorry to make you do it twice!

**Comment by bleroux** [comment]
> Could you reland the PR? Sorry to make you do it twice!

Hey @jacobsimionato :wave: !
No problem at all, especially because I just woke up (France time) and see that you already sorted everything out :smile::pray:.

Here is the reland: https://github.com/flutter/flutter/pull/157399.
Can you approve it? That way I will be able to merge it as soon as the CI checks are ok.
