### PR TITLE
Use the engine's TextOverflow API to implement ellipsizing

### LINKED ISSUE #4478: Text overflow with ellipsis also has fade
## Steps to Reproduce

A **text** widget with _overflow_ set to _TextOverflow.ellipsis_ should not have a fade. 
screen shot 2016-06-07 at 4 56 50 pm

## Flutter Doctor
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/dayang/Flutter
    • Framework revision 21fa2753d8 (13 days ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/dayang/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3, Build version 7D175

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.3

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/4478

### CODE REVIEW

**Comment by jason-simmons** [comment]
@abarth

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 1]
```diff
@@ -225,10 +223,7 @@ class RenderParagraph extends RenderBox {
     final Canvas canvas = context.canvas;
     if (_hasVisualOverflow) {
       final Rect bounds = offset & size;
-      if (_overflowPainter != null)
-        canvas.saveLayer(bounds, new Paint());
-      else
-        canvas.save();
+      canvas.save();
```
Comment (abarth) [inline packages/flutter/lib/src/rendering/paragraph.dart]: I think we still need to do a saveLayer here if we need to generate the fade effect because the fade effect needs to blend the text against the background.

Comment (abarth) [inline packages/flutter/lib/src/rendering/paragraph.dart]: Probably _overflowShader is the thing to change the check to.

**Comment by abarth** [comment]
LGTM

File: packages/flutter/lib/src/rendering/paragraph.dart (hunk 1 above)
Comment (jason-simmons) [inline packages/flutter/lib/src/rendering/paragraph.dart]: done

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 2]
```diff
@@ -33,14 +33,16 @@ class TextPainter {
   TextPainter({
     TextSpan text,
     TextAlign textAlign,
-    double textScaleFactor: 1.0
-  }) : _text = text, _textAlign = textAlign, _textScaleFactor = textScaleFactor {
+    double textScaleFactor: 1.0,
+    ui.TextOverflow textOverflow,
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_painter.dart]: please re-export this so that consumers don't have to get it from dart:ui

Comment (jason-simmons) [inline packages/flutter/lib/src/painting/text_painter.dart]: That would conflict with the TextOverflow enum in the framework package

**Comment by Hixie** [comment]
in general i'd like to now see ui.OverflowEffect anywhere in the framework code.

**Comment by jason-simmons** [comment]
TextOverflow is provided by the framework and includes overflow effects that are rendered on the framework side (i.e. fade).

ui.TextOverflow only covers overflow policies that are implemented within the engine

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 2 above)
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_painter.dart]: ok well we definitely shouldn't have both if they're both going to be exposed in the framework API.

**Comment by Hixie** [comment]
Is ui.TextOverflow only used at the lowest levels, like ui.TextStyle? It looks like you have some classes in the framework that take ui.TextOverflow.

**Comment by Hixie** [comment]
I think the best way to resolve this really is to have the engine take a string instead of this enum. That would remove any API conflict.

**Comment by Hixie** [comment]
(the framework would then just pass in the ellipsis character as the string value when _its_ enum is set to the ellipsis value.)

**Comment by jason-simmons** [comment]
ui.TextOverflow is used by low-level text painting APIs that talk to the engine API (TextPainter and TextStyle/ParagraphStyle)

TextOverflow is used by widgets and render objects (RichText and RenderParagraph)

**Comment by Hixie** [comment]
TextPainter is not a low-level API. It's the API you use when you paint on a canvas from user code. It shouldn't use any non-reexported dart:ui types in its API.

**Comment by jason-simmons** [comment]
Updated for the new engine API.

PTAL

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 3]
```diff
@@ -33,8 +33,9 @@ class TextPainter {
   TextPainter({
     TextSpan text,
     TextAlign textAlign,
-    double textScaleFactor: 1.0
-  }) : _text = text, _textAlign = textAlign, _textScaleFactor = textScaleFactor {
+    double textScaleFactor: 1.0,
+    String ellipsis
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_painter.dart]: nit: these days, when you have a list like this, stick a trailing comma in there so future changes don't need to edit the previous line

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 4]
```diff
@@ -80,6 +81,18 @@ class TextPainter {
     _needsLayout = true;
   }
 
+  /// The string used to ellipsize overflowing text.
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_painter.dart]: Add more documentation, for example:
* Is providing a string sufficient to cause ellipsising?
* Is there a difference between null and the empty string? (If not, consider disallowing one just to remove that axis of freedom.)
* What are the performance implications of this feature?
* What are edge cases you might run into, and how are they handled? e.g. if the ellipsising string is wider than the container, if it contains unbalanced bidi characters, combining characters, or explicit line breaks, that kind of thing.
* How is the ellipsising done? (clipping truncation vs character truncation vs ligature truncation etc)

Weave all these answers into a coherent narrative. :-)

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 5]
```diff
@@ -162,7 +175,11 @@ class TextPainter {
     if (_paragraph == null) {
       ui.ParagraphBuilder builder = new ui.ParagraphBuilder();
       _text.build(builder, textScaleFactor: textScaleFactor);
-      ui.ParagraphStyle paragraphStyle = _text.style?.getParagraphStyle(textAlign: textAlign, textScaleFactor: textScaleFactor);
+      ui.ParagraphStyle paragraphStyle = _text.style?.getParagraphStyle(
+          textAlign: textAlign,
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_painter.dart]: we usually do a two-character indent here. we'll probably change at some point to match typical dart style but for now let's keep the code consistent.

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 6]
```diff
@@ -162,7 +175,11 @@ class TextPainter {
...
+          textScaleFactor: textScaleFactor,
+          ellipsis: _ellipsis
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_painter.dart]: nit: trailing comma

File: packages/flutter/lib/src/painting/text_style.dart [hunk 7]
```diff
@@ -229,14 +229,19 @@ class TextStyle {
...
+   }) {
     return new ui.ParagraphStyle(
       textAlign: textAlign,
       fontWeight: fontWeight,
       fontStyle: fontStyle,
       fontFamily: fontFamily,
       fontSize: fontSize == null ? null : fontSize * textScaleFactor,
-      lineHeight: height
+      lineHeight: height,
+      ellipsis: ellipsis
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_style.dart]: ditto

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 8]
```diff
@@ -34,7 +36,12 @@ class RenderParagraph extends RenderBox {
     double textScaleFactor: 1.0
   }) : _softWrap = softWrap,
        _overflow = overflow,
-       _textPainter = new TextPainter(text: text, textAlign: textAlign, textScaleFactor: textScaleFactor) {
+       _textPainter = new TextPainter(
+           text: text,
+           textAlign: textAlign,
+           textScaleFactor: textScaleFactor,
+           ellipsis: overflow == TextOverflow.ellipsis ? _kEllipsis : null
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/paragraph.dart]: ditto

**Comment by Hixie** [comment]
LGTM

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 4 above)
Comment (jason-simmons) [inline packages/flutter/lib/src/painting/text_painter.dart]: Clarified the docs and added an assert for empty ellipsis strings

(I don't know the internals of the text rendering engine well enough to precisely describe its behavior)
