### PR TITLE
fixes deeplinking in uiscenedelegate migrated projects

### LINKED ISSUE #170350: Deeplinks on iOS fail silently after UISceneDelegate migration
### Steps to reproduce

1. Checkout Flutter SDK to https://github.com/flutter/flutter/commit/40f1695bef096b60a935e2be8882c718d16a6040 (Parent commit of UISceneDelegate PR).
2. `flutter run` this sample app on iOS Simulator: https://github.com/rajveermalviya/sample_ios_deeplinks
3. In a separate terminal, run this command to trigger a deeplink:
```
xcrun simctl openurl booted 'sampleiosdeeplinks:///details'
```
5. Notice that the "Details Screen" (`/details`) is opened on the iOS Simulator.
6. Now checkout Flutter SDK to https://github.com/flutter/flutter/commit/3d8fa621c1394a5bc22525676a41bd3a2a4b0ce5 (UISceneDelegate PR).
7. Repeat Step 2 and 3 again.
8. Notice that the "Details Screen" does _not_ open and there are no errors logged in the console.

### Expected results

The deeplink should work and the "Details Screen" to open in the sample when triggered.

### Actual results

The deeplink is ignored and there aren't any errors are reported.

### Code sample

<details open><summary>Code sample</summary>

https://github.com/rajveermalviya/sample_ios_deeplinks

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[!] Flutter (Channel [user-branch], 3.33.0-1.0.pre.293, on macOS 15.5 24F74 darwin-arm64, locale en-IN) [973ms]
    ! Flutter version 3.33.0-1.0.pre.293 on channel [user-branch] at /Users/rajveer/sdk/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 3d8fa621c1 (11 days ago), 2025-05-30 13:57:40 -0700
    • Engine revision 3d8fa621c1
    • Dart version 3.9.0 (build 3.9.0-172.0.dev)
    • DevTools version 2.46.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [1,739ms]
    • Android SDK at /Users/rajveer/Library/Android/sdk
    • Emulator version 35.5.10.0 (build_id 13402964) (CL:N/A)
    • Platform android-36, build-tools 35.0.0
    • ANDROID_HOME = /Users/rajveer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [881ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [13ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [13ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)

[✓] VS Code (version 1.100.3) [10ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.112.0

[✓] Connected device (3 available) [5.8s]
    • iPhone 16 Pro (mobile) • 20B032C1-32A7-4FE6-BC13-7DE6FEC575AC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 137.0.7151.69

[✓] Network resources [1,306ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/170350

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by hellohuanlin — COMMENTED** [review]
Wanna double check if we still want this in given that migration has been paused?

**Comment by gaaclarke** [comment]
> Wanna double check if we still want this in given that migration has been paused?

Yes, we still want it for people that have already auto migrated, for those that already have attempted to migrated before this all started and for those that choose to manually migrate.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m [hunk 1]
```diff
@@ -29,4 +30,54 @@ - (void)scene:(UIScene*)scene
...
+  id appDelegate = FlutterSharedApplication.application.delegate;
+  if ([appDelegate respondsToSelector:@selector(lifeCycleDelegate)]) {
+    FlutterPluginAppLifeCycleDelegate* lifeCycleDelegate = [appDelegate lifeCycleDelegate];
+    [lifeCycleDelegate application:FlutterSharedApplication.application
+        performActionForShortcutItem:shortcutItem
+                   completionHandler:completionHandler];
+  }
+}
+
+static NSDictionary<UIApplicationOpenURLOptionsKey, id>* ConvertOptions(
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:45]: nit: `FLTConvertSceneOpenURLOptions`

**Review by hellohuanlin — APPROVED** [review]
CC @vashworth

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m (hunk 1 above)
Comment (gaaclarke) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:45]: FYI that is a static function which means it only has file scope, the symbol isn't exported so there is no risk that it will collide with other functions.  Those sorts of naming conventions are important for functions that have external linkage.

Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:45]: > the symbol isn't exported so there is no risk that it will collide with other functions

Say you have 

```
static void foo() {
  // print foo
}
```

Then one of the included header has: 
```
void foo() {
  // print bar
}
```
This won't compile right? (haven't tried)

Comment (gaaclarke) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:45]: That's not a problem, you can just change the name at that point safely because the symbol doesn't exist beyond the translation unit.

Comment (gaaclarke) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:45]: Also, something named `foo` in a header would be an exported symbol which should follow a safe naming scheme.
