### PR TITLE
[flutter tools] Move _informUserOfCrash into crash_reporting.dart

### LINKED ISSUE #53766: Allow configuration of the flutter crash reporting logic
Internal: b/137028157

Currently this writes out a file to the local filesystem and produces github metadata. This logic should be configurable so that the google3 client can direct developers that get crashes to buganizer and ensure that the crash report is written somewhere accessible.

fyi @jmagman  @jamesderlin

### PR DESCRIPTION
**Pull request by jamesderlin**
## Description

I intend to override `_informUserOfCrash` in google3.  Move it to a new `CrashReporter` class and make it public in preparation for this.

I think it's a bit confusing that there is a `CrashReporter` class and a `CrashReportSender` class, but I haven't thought of a better name, and there's been pushback on merging them.

* To limit the scope of what can be overridden, slightly refactor it to move some of its work (generating the doctor text and local crash file) into the caller.  To facilitate this, add a `CrashDetails` class to replace arguments that get repeatedly passed around.

* Move instructions about reporting bugs on GitHub to an overridable `UserMessage`.

## Related Issues

* Fixes #53766.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jamesderlin** [comment]
For easier reviewing, I broke this pull request into several discrete commits.  It will be easier to see what changed in the moved code from the individual commits.

File: packages/flutter_tools/lib/src/base/user_messages.dart [hunk 1]
```diff
@@ -10,6 +10,11 @@ UserMessages get userMessages => context.get<UserMessages>();
 
 /// Class containing message strings that can be produced by Flutter tools.
 class UserMessages {
+  // Common messages.
+  String get flutterToolBugInstructions =>
+      'Please file a bug at https://github.com/flutter/flutter/issues.';
+
+
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/base/user_messages.dart:17]: Extra line.

File: packages/flutter_tools/lib/src/base/user_messages.dart [hunk 2]
```diff
@@ -10,6 +10,11 @@ UserMessages get userMessages => context.get<UserMessages>();
 
 /// Class containing message strings that can be produced by Flutter tools.
 class UserMessages {
+  // Common messages.
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/base/user_messages.dart:13]: Does "common messages" mean anything as a comment?

File: packages/flutter_tools/lib/src/base/user_messages.dart [hunk 3]
```diff
@@ -10,6 +10,11 @@ UserMessages get userMessages => context.get<UserMessages>();
...
+  String get flutterToolBugInstructions =>
+      'Please file a bug at https://github.com/flutter/flutter/issues.';
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/base/user_messages.dart:15]: I like I like the "Please let us know at" text better, I say "file" all the time but I don't think everyone uses that verb.

File: packages/flutter_tools/lib/src/context_runner.dart [hunk 4]
```diff
@@ -127,6 +131,12 @@ Future<T> runInContext<T>(
       FuchsiaDeviceTools: () => FuchsiaDeviceTools(),
       FuchsiaSdk: () => FuchsiaSdk(),
       FuchsiaWorkflow: () => FuchsiaWorkflow(),
+      GitHubTemplateCreator: () => GitHubTemplateCreator(
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/context_runner.dart:134]: Does this need to be in the context?  We're trying to move as much out of the context and globals as possible for testability, and g3 doesn't need to override it.

Can we inject fileSystem, flutterProjectFactory, and client into CrashReporter and let the Flutter version create a `GitHubTemplateCreator`, and the g3 version just ignore any params it doesn't need?

Then there's no need for a nullable `GitHubTemplateCreator` injected into `CrashReporter`

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart [hunk 5]
```diff
@@ -26,15 +26,61 @@ const String _kStackTraceFileField = 'DartError';
...
+    @required this.command,
+    @required this.error,
+    @required this.stackTrace,
+    @required this.doctorText,
+  });
+
+  String command;
+  dynamic error;
+  StackTrace stackTrace;
+  String doctorText;
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/reporting/crash_reporting.dart:40]: Can you make these final and private?

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart [hunk 6]
```diff
@@ -26,15 +26,61 @@ const String _kStackTraceFileField = 'DartError';
...
+  Future<void> informUser(CrashDetails details, File crashFile) async {
+    logger.printError('A crash report has been written to ${crashFile.path}.');
+    logger.printStatus('This crash may already be reported. Check GitHub for similar crashes.', emphasis: true);
+
+    final String similarIssuesURL = GitHubTemplateCreator.toolCrashSimilarIssuesURL('${details.error}');
+    logger.printStatus('$similarIssuesURL\n', wrap: false);
+    logger.printStatus('To report your crash to the Flutter team, first read the guide to filing a bug.', emphasis: true);
+    logger.printStatus('https://flutter.dev/docs/resources/bug-reports\n', wrap: false);
+
+    if (gitHubTemplateCreator != null) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/reporting/crash_reporting.dart:63]: Then this null check doesn't need to be here if this class creates the GitHubTemplateCreator.

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart [hunk 7]
```diff
@@ -26,15 +26,61 @@ const String _kStackTraceFileField = 'DartError';
...
+  });
+
+  String command;
+  dynamic error;
+  StackTrace stackTrace;
+  String doctorText;
+}
+
+/// Reports information about the crash to the user.
+class CrashReporter {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/reporting/crash_reporting.dart:44]: I think this needs tests.

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart [hunk 8]
```diff
@@ -26,15 +26,61 @@ const String _kStackTraceFileField = 'DartError';
...
+  CrashReporter({
+    @required this.logger,
+    this.gitHubTemplateCreator,
+  });
+
+  final GitHubTemplateCreator gitHubTemplateCreator;
+  final Logger logger;
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/reporting/crash_reporting.dart:51]: Can you make these private?

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart [hunk 9]
```diff
@@ -26,15 +26,61 @@ const String _kStackTraceFileField = 'DartError';
...
+
+  /// Prints instructions for filing a bug about the crash.
+  Future<void> informUser(CrashDetails details, File crashFile) async {
+    logger.printError('A crash report has been written to ${crashFile.path}.');
+    logger.printStatus('This crash may already be reported. Check GitHub for similar crashes.', emphasis: true);
+
+    final String similarIssuesURL = GitHubTemplateCreator.toolCrashSimilarIssuesURL('${details.error}');
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/reporting/crash_reporting.dart:58]: details.error.toString()

File: packages/flutter_tools/lib/src/base/user_messages.dart (hunk 1 above)
Comment (jamesderlin) [reply packages/flutter_tools/lib/src/base/user_messages.dart:17]: Oops.  Fixed.

File: packages/flutter_tools/lib/src/base/user_messages.dart (hunk 2 above)
Comment (jamesderlin) [reply packages/flutter_tools/lib/src/base/user_messages.dart:13]: All of the other messages in this file are preceded by "Messages used in X", so I was trying to clarify this is a message used in multiple components.

File: packages/flutter_tools/lib/src/base/user_messages.dart (hunk 3 above)
Comment (jamesderlin) [reply packages/flutter_tools/lib/src/base/user_messages.dart:15]: How about "Please report"?

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart (hunk 5 above)
Comment (jamesderlin) [reply packages/flutter_tools/lib/src/reporting/crash_reporting.dart:40]: I can make them final.  Private doesn't make sense; the point is for these fields to be extracted by whatever the `CrashDetails` object is passed to.

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart (hunk 6 above)
Comment (jamesderlin) [reply packages/flutter_tools/lib/src/reporting/crash_reporting.dart:63]: `gitHubTemplateCreator` is supplied as an construction argument, and it could be null. (The google3 subclass will not provide one. Granted, it also will override `informUser`, but in principle overridng `informUser` isn't required.)

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart (hunk 8 above)
Comment (jamesderlin) [reply packages/flutter_tools/lib/src/reporting/crash_reporting.dart:51]: I did not make them private since they might be needed by the derived class.  I either could make them `@protected` or make them private with the derived class duplicating the fields.

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart (hunk 9 above)
Comment (jamesderlin) [reply packages/flutter_tools/lib/src/reporting/crash_reporting.dart:58]: Is there a preference for using `.toString()`?  I generally prefer string interpolation since it guarantees a string even for null inputs.

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart (hunk 6 above)
Comment (jamesderlin) [reply packages/flutter_tools/lib/src/reporting/crash_reporting.dart:63]: Oops, I missed the other comment about creating the `GitHubTemplateCreator`.  Okay.

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart (hunk 7 above)
Comment (jamesderlin) [reply packages/flutter_tools/lib/src/reporting/crash_reporting.dart:44]: I've added a simple test that verifies that `CrashReporter.informUser` prints some key strings.  Did you have anything beyond that in mind?

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart [hunk 10]
```diff
@@ -26,15 +26,70 @@ const String _kStackTraceFileField = 'DartError';
...
+/// Reports information about the crash to the user.
+class CrashReporter {
+  CrashReporter({
+    @required this.fileSystem,
+    @required this.logger,
+    @required this.flutterProjectFactory,
+    @required this.client,
+  });
+
+  final FileSystem fileSystem;
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/reporting/crash_reporting.dart:52]: If there isn't some reason in this PR that these need to be public, then following suit with this pattern in the rest of the tool, they should be private.

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart (hunk 9 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/reporting/crash_reporting.dart:62]: IIRC from my VM team days, interpolation will be a bit slower. This code is not performance critical, so the overriding concern here would be following a consistent style. Also, I think it is not possible to throw `null`, so `error` won't  ever be `null`. We'll be able to enforce that to this point with non-nullability in the future.

**Review by zanderso — COMMENTED** [review]
dbc

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart (hunk 10 above)
Comment (jamesderlin) [reply packages/flutter_tools/lib/src/reporting/crash_reporting.dart:52]: Okay, I'll make them private.

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart (hunk 9 above)
Comment (jamesderlin) [reply packages/flutter_tools/lib/src/reporting/crash_reporting.dart:62]: Okay, I'll fix it `.toString()`.

File: packages/flutter_tools/lib/src/reporting/crash_reporting.dart (hunk 7 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/reporting/crash_reporting.dart:44]: Good enough, thanks!

**Review by jmagman — APPROVED** [review]
LGTM, thanks for doing this!

**Comment by jmagman** [comment]
[Pushed a commit](https://github.com/flutter/flutter/pull/55614/commits/778079c563444e65b96bd0ae0282bbe842dd82b3) to @jamesderlin's fork that verifies `CrashDetails` in runner_test, and swaps out `MockGitHubTemplateCreator` for `MockCrashReporter` in the test context.
