### PR TITLE
Changes the offset computation to first item for RenderSliverMainAxisGroup

### LINKED ISSUE #154615: `RenderSliverMainAxisGroup` does not take pinned slivers into consideration when ensureVisible is called on a child
### Steps to reproduce

1. Run the following code.
2. Scroll the screen down so that the `TextField` gets hidden under the `SliverPersistentHeader` (the red box). 
3. Click the button.

### Expected results

The `TextField` is visible on the screen.

### Actual results

The screen scrolls, but the `TextField` is hidden behind the pinned `SliverPersistentHeader`. 

I'm guessing that it has to do with the `childScrollOffset` computation for `RenderSliverMainAxisGroup` (https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/sliver_group.dart#L207-L229). When not overriding the `childScrollOffset` method (defaulting to returning 0), everything works as expected. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  FocusNode textFieldFocus = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverMainAxisGroup(
            slivers: [
              SliverPersistentHeader(
                pinned: true,
                delegate: _SliverTitleDelegate(
                  child: Container(
                    color: Colors.red,
                    height: 60.0,
                  ),
                  height: 60.0,
                ),
              ),
              SliverToBoxAdapter(
                  child: TextField(
                focusNode: textFieldFocus,
              )),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.green,
                  height: 500,
                ),
              ),
              SliverToBoxAdapter(
                child: Container(
                  color: Colors.black,
                  height: 500,
                ),
              ),
            ],
          )
        ],
      ),
      floatingActionButton: TextButton(
          onPressed: () {
            textFieldFocus.requestFocus();
          },
          child: const Text('Focus TextField')),
    );
  }
}

class _SliverTitleDelegate extends SliverPersistentHeaderDelegate {
  _SliverTitleDelegate({
    required this.height,
    required this.child,
  });
  final double height;
  final Widget child;

  @override
  double get minExtent => height;
  @override
  double get maxExtent => height;

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return child;
  }

  @override
  bool shouldRebuild(_SliverTitleDelegate oldDelegate) => true;
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/1f3dc12d-a681-40ab-8a52-291e28ccf83c

</details>

### Logs

<details open><summary>Logs</summary>

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-SE)
    • Flutter version 3.24.1 on channel stable at /Users/xxx/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (2 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.119

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by Mairramer**
Fixes https://github.com/flutter/flutter/issues/154615
When scrolling back to the top, the position of the first visible item should have its scrollExtent subtracted. Otherwise, the accumulated position may be retained, which may result in the first visible item being hidden in some cases.
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
@Mairramer can you share why the values of the existing tests changed?

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart [hunk 1]
```diff
@@ -795,7 +795,79 @@ void main() {
...
+              height: 500,
+            ),
+          ),
+          SliverToBoxAdapter(
+            child: Container(
+              color: Colors.black,
+              height: 500,
+            ),
+          ),
+          SliverToBoxAdapter(
```
Comment (victorsanni) [inline packages/flutter/test/widgets/sliver_main_axis_group_test.dart:842]: Do we need this many containers/textfields? Is it possible to make the smallest use case for this test?

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 2]
```diff
@@ -213,7 +214,16 @@ class RenderSliverMainAxisGroup extends RenderSliver with ContainerRenderObjectM
...
         RenderSliver? current = childBefore(child as RenderSliver);
         while (current != null) {
-          childScrollOffset += current.geometry!.scrollExtent;
+          final double scrollExtent = current.geometry!.scrollExtent;
+          childScrollOffset += scrollExtent;
+
+          // If the current item is the first visible item, we subtract its scrollExtent
+          // to correct the offset, since we accumulated the scrollExtent of this item in the loop.
+          // We are not assuming that this is the first item in the list, but rather the first visible one.
+          if (childBefore(current) == null && (childAfter(child) != null) ) {
```
Comment (victorsanni) [inline packages/flutter/lib/src/rendering/sliver_group.dart:223]:
```suggestion
          if (childBefore(current) == null && childAfter(child) != null) {
```

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 3]
```diff
@@ -213,7 +214,16 @@ class RenderSliverMainAxisGroup extends RenderSliver with ContainerRenderObjectM
...
+            childScrollOffset -= scrollExtent;
```
Comment (victorsanni) [inline packages/flutter/lib/src/rendering/sliver_group.dart:224]: Nit: Do we have to add the `scrollExtent` then remove it afterwards? Can't we just add it only if the condition above doesn't hold?

**Review by victorsanni — COMMENTED** [review]
LGTM with nits and pending further review.

**Comment by Mairramer** [comment]
@Piinks The changes in test values are due to a fix in the scrolling and display logic within the `SliverMainAxisGroup`. The updated logic ensures that content is displayed correctly while scrolling, preventing items from being improperly hidden.
These changes ensure that content is visible and positioned correctly as intended.

Reason for changes:
- Logic Correction: Adjusts how the `SliverPersistentHeader` and other items are positioned and scrolled.
- Impact on Tests: Expected values were updated to align with the correct behavior after the fix. `Offset` values and item positioning now reflect the new display logic.

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 4]
```diff
@@ -213,7 +214,13 @@ class RenderSliverMainAxisGroup extends RenderSliver with ContainerRenderObjectM
         double childScrollOffset = 0.0;
         RenderSliver? current = childBefore(child as RenderSliver);
         while (current != null) {
-          childScrollOffset += current.geometry!.scrollExtent;
+          // If the current item is the first visible item, we subtract its scrollExtent
+          // to correct the offset, since we accumulated the scrollExtent of this item in the loop.
+          // We are not assuming that this is the first item in the list, but rather the first visible one.
+          if (childBefore(current) != null || childAfter(child) == null) {
+          final double scrollExtent = current.geometry!.scrollExtent;
+            childScrollOffset += scrollExtent;
```
Comment (victorsanni) [inline packages/flutter/lib/src/rendering/sliver_group.dart:222]:
```suggestion
            final double scrollExtent = current.geometry!.scrollExtent;
              childScrollOffset += scrollExtent;
```

**Review by victorsanni — APPROVED** [review]

**Comment by victorsanni** [comment]
> @Piinks The changes in test values are due to a fix in the scrolling and display logic within the `SliverMainAxisGroup`. The updated logic ensures that content is displayed correctly while scrolling, preventing items from being improperly hidden. These changes ensure that content is visible and positioned correctly as intended.

I think what @Piinks is asking for is, specifically, what was the previous test doing (e.g moving some widget, then scrolling a certain way, and expecting some header to be visible, etc) and how is this PR going to change that behavior?

(also for some reason this reads to me like an llm-generated response).

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart [hunk 5]
```diff
@@ -795,7 +795,58 @@ void main() {
     );
     Scrollable.ensureVisible(key.currentContext!);
     await tester.pumpAndSettle();
-    expect(tester.getTopLeft(find.byKey(key)), Offset.zero);
+    // Regression test for https://github.com/flutter/flutter/issues/154615
+    expect(tester.getTopLeft(find.byKey(key)), const Offset(0, 300));
+  });
+
+  testWidgets('SliverMainAxisGroup scrolls to the correct position when focusing on a text field within a header', (WidgetTester tester) async {
```
Comment (victorsanni) [inline packages/flutter/test/widgets/sliver_main_axis_group_test.dart:802]: This test passes on `master`.

**Review by victorsanni — CHANGES_REQUESTED** [review]

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart (hunk 5 above)
Comment (Mairramer) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart:802]: fixed

Comment (Piinks) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart:802]: What was incorrect about the test previously that was fixed?

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 6]
```diff
@@ -17546,7 +17546,8 @@ void main() {
     await tester.pumpWidget(widget);
     await tester.showKeyboard(find.byType(EditableText));
     await tester.pumpAndSettle();
-    expect(scrollController.offset, 75.0);
+    // Regression test for https://github.com/flutter/flutter/issues/154615
+    expect(scrollController.offset, 0.0);
```
Comment (Piinks) [inline packages/flutter/test/widgets/editable_text_test.dart:17550]: Testing this out in an app, I don't think this is correct to change.
This test is verifying that when the keyboard is presented, with focus on the text field, it is then scrolled into view. An offset of zero means it did not scroll at all.

Comment (Piinks) [reply packages/flutter/test/widgets/editable_text_test.dart:17550]: See https://github.com/flutter/flutter/pull/141671 for more context

Comment (Mairramer) [reply packages/flutter/test/widgets/editable_text_test.dart:17550]: Ah I see, I'll probably have to improve my code. It really works for specific cases.I will work better on this issue.

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 7]
```diff
@@ -213,7 +214,11 @@ class RenderSliverMainAxisGroup extends RenderSliver with ContainerRenderObjectM
         double childScrollOffset = 0.0;
         RenderSliver? current = childBefore(child as RenderSliver);
         while (current != null) {
-          childScrollOffset += current.geometry!.scrollExtent;
+          // If the sliver is not clipped, then we add the scroll extent of the
+          // sliver to the childScrollOffset.
+          if (current.geometry?.hasVisualOverflow == false) {
```
Comment (victorsanni) [inline packages/flutter/lib/src/rendering/sliver_group.dart:219]: is this change also applicable for `GrowthDirection.reverse`?

Comment (Mairramer) [reply packages/flutter/lib/src/rendering/sliver_group.dart]: Yes yes

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 8]
```diff
@@ -213,15 +214,19 @@ class RenderSliverMainAxisGroup extends RenderSliver with ContainerRenderObjectM
...
           current = childBefore(current);
         }
         return childScrollOffset;
       case GrowthDirection.reverse:
         double childScrollOffset = 0.0;
         RenderSliver? current = childAfter(child as RenderSliver);
         while (current != null) {
-          childScrollOffset -= current.geometry!.scrollExtent;
+          if (!current.geometry!.hasVisualOverflow || firstChild == child ) {
+            childScrollOffset += current.geometry!.scrollExtent;
```
Comment (victorsanni) [inline packages/flutter/lib/src/rendering/sliver_group.dart:228]: Shouldn't it be subtracted here instead?

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart [hunk 9]
```diff
@@ -797,6 +797,64 @@ void main() {
     await tester.pumpAndSettle();
     expect(tester.getTopLeft(find.byKey(key)), Offset.zero);
   });
+
+  testWidgets('SliverMainAxisGroup scrolls to the correct position when focusing on a text field within a header', (WidgetTester tester) async {
```
Comment (victorsanni) [inline packages/flutter/test/widgets/sliver_main_axis_group_test.dart:801]: Can we add a test for GrowthDirection.reverse?

Comment (Mairramer) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart:801]: For some reason it never goes into reverse. I tried to look at other examples, but there are no similar ones. And it's also a bit confusing on how it works.

Comment (victorsanni) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart:801]: Can you try to reproduce the bug with GrowthDirection.reverse?

Comment (Mairramer) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart:801]: I tried but I couldn't. I must probably be missing something or it never really goes into reverse.

Comment (victorsanni) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart:801]: If it can't be reproduced in `GrowthDirection.reverse`, then we should probably not try to solve a problem that doesn't exist yet. In the meantime I'll try reproducing it.

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 10]
```diff
@@ -213,15 +214,31 @@ class RenderSliverMainAxisGroup extends RenderSliver with ContainerRenderObjectM
...
+          }
           current = childBefore(current);
         }
         return childScrollOffset;
       case GrowthDirection.reverse:
         double childScrollOffset = 0.0;
         RenderSliver? current = childAfter(child as RenderSliver);
         while (current != null) {
-          childScrollOffset -= current.geometry!.scrollExtent;
+          // If the current sliver is not the last child, subtract twice the scrollExtent to the scrollOffset
```
Comment (victorsanni) [inline packages/flutter/lib/src/rendering/sliver_group.dart:233]: @Mairramer to continue from the thread below, my current thought process is to revert this block and land the PR (to avoid over-engineering). Then, if it ever happens that someone runs into an issue here, their particular use case would give more clarity on how (or even if) it should be fixed.

**Review by victorsanni — APPROVED** [review]

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 11]
```diff
@@ -213,7 +214,15 @@ class RenderSliverMainAxisGroup extends RenderSliver with ContainerRenderObjectM
         double childScrollOffset = 0.0;
         RenderSliver? current = childBefore(child as RenderSliver);
         while (current != null) {
-          childScrollOffset += current.geometry!.scrollExtent;
+          // If the current sliver is not the first child, add twice the scrollExtent to the scrollOffset
+          // to account for both the current and the previous slivers.
+          // If the current sliver is the first child, add its scrollExtent once to the scrollOffset
+          // to account for only the current sliver.
+          if (childBefore(current) != null) {
+            childScrollOffset += 2 * current.geometry!.scrollExtent;
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/sliver_group.dart:222]: 2 feels like a magic number here. Shouldn't it depends on the preceding child's size?

File: packages/flutter/test/widgets/sliver_main_axis_group_test.dart (hunk 5 above)
Comment (Piinks) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart:801]: @Mairramer this was resolved without an answer.

Comment (Mairramer) [reply packages/flutter/test/widgets/sliver_main_axis_group_test.dart:801]: @Piinks Ah, sorry, I forgot to mention. I was checking a parameter of the `ScrollController` that would work even without any changes I made.

**Comment by Piinks** [comment]
Rebasing to fix CI

File: packages/flutter/lib/src/rendering/sliver_group.dart (hunk 11 above)
Comment (Mairramer) [reply packages/flutter/lib/src/rendering/sliver_group.dart]: Yes, you're right. I adjusted the code to have the expected behavior and avoid 2 as the magic number, in addition to preventing it from scrolling further than expected.

**Review by Piinks — APPROVED** [review]
LGTM
