### PR TITLE
Label unnecessarily ellided

### LINKED ISSUE #56008: InputDecoration labelText is unnecessarily ellipsized from long prefixText
## Steps to Reproduce
See https://dartpad.dev/cfc5ac6bcce92be669c147981f5a97ec for a demonstration, but the main part is:

```dart
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SizedBox(
          width: 300,
          height: 200,
          child: TextField(
            controller: _controller,
            decoration: const InputDecoration(
              prefixText: 'The five boxing wizards jump quickly:',
              labelText: 'My Label',
            ),
          ),
        ),
      ),
    );
  }
```

**Actual results:**
Even though `prefixText` and `labelText` never share the same space, it appears that `labelText` is truncated with an ellipsis if `prefixText` is sufficiently long, regardless of whether the `TextField` has focus.

**Expected results:** 
`labelText` truncation is independent of `prefixText`.

Internal bug is b/155349947.

### PR DESCRIPTION
**Pull request by justinmc**
## Description

The label in input decoration was making room for prefix and suffix when calculating its width. However, when label is displayed in the input, prefix and suffix are not, so label was being ellided when it didn't need to be.  This removes them from the width calculation and allows label to take up all the available space.

## Related Issues

Closes https://github.com/flutter/flutter/issues/56008

## Tests

I added the following tests:

Test that the label's width stays the same despite adding a prefix and suffix.

## Breaking Change

None.

### CODE REVIEW

File: packages/flutter/test/material/input_decorator_test.dart [hunk 1]
```diff
@@ -4161,4 +4161,64 @@ void main() {
 
     expect(tester.getTopLeft(find.text(hintText)).dy, topPosition);
   });
+
+  testWidgets('InputDecorator label width isn\'t affected by prefix or suffix', (WidgetTester tester) async {
```
Comment (LongCatIsLooong) [inline packages/flutter/test/material/input_decorator_test.dart:4165]: nit: use double quotes so you don't have to escape the `'` (I thought it was a lint rule?)

**Review by LongCatIsLooong — APPROVED** [review]
LGTM :+1:

**Review by guidezpl — APPROVED** [review]
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
```
