### PR TITLE
Pass fit property to RenderIndexedStack

### LINKED ISSUE #109247: IndexedStack ignores `sizing` param
Setting `IndexedStack.sizing` to `StackFit.expand` does not cause children to expand to fill the space. The `sizing` constructor argument is passed to super as `Stack.fit`, but IndexedStack uses a different RenderObject that doesn't use the value.

A working workaround is to wrap children with `Positioned.fill`.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** The child should be expanded to fit the size of the IndexedStack.
expected

**Actual results:** The child renders at its intrinsic size.
observed

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) => Scaffold(
        body: IndexedStack(
          index: 0,
          // StackFit.expand does not give desired result:
          sizing: StackFit.expand,
          children: const [
            ContentWidget(),
            // wrapping with Positioned.fill gives desired result:
            // Positioned.fill(child: ContentWidget()),
          ],
        ),
      );
}

class ContentWidget extends StatelessWidget {
  const ContentWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Container(
        color: Colors.deepPurpleAccent,
        child: const Text('Some Content'),
      );
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

[I] ➜ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.5 at /opt/homebrew/Caskroom/flutter/2.2.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/austin/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/austin/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/austin/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-16.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu16.30+19-CA (build 16.0.1+9)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.58.2)
    • VS Code at /Users/austin/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • Austin’s iPad (mobile) • 00008020-000D0C4E2105002E • ios          • iOS 15.5 19F77
    • macOS (desktop)        • macos                     • darwin-arm64 • macOS 12.4 21F79 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```

</details>

### PR DESCRIPTION
**Pull request by maheshj01**
Pass fit property from IndexedStack to RenderIndexedStack so as to fit Children within a Stack

Fixes: https://github.com/flutter/flutter/issues/109247

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by xu-baolin** [comment]
Could you add `clipBehavior` to IndexedStack too?

**Comment by maheshmnj** [comment]
@xu-baolin  sure

**Comment by maheshmnj** [comment]
Would this require any tests?

**Comment by xu-baolin** [comment]
yes this needs tests.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 1]
```diff
@@ -3917,6 +3918,7 @@ class IndexedStack extends Stack {
     assert(_debugCheckHasDirectionality(context));
     return RenderIndexedStack(
       index: index,
+      fit:fit,
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/basic.dart:3921]: RO should add `clipBehavior` too

Comment (maheshmnj) [reply packages/flutter/lib/src/widgets/basic.dart:3921]: added

File: packages/flutter/test/widgets/stack_test.dart [hunk 2]
```diff
@@ -799,4 +799,22 @@ void main() {
...
+
+    /// Update clipBehavior to Clip.antiAlias
+
+    await tester.pumpWidget(IndexedStack(
+      textDirection: TextDirection.ltr,
+      clipBehavior: Clip.antiAlias,
+    ));
+    final RenderIndexedStack renderIndexedObject =
+      tester.allRenderObjects.whereType<RenderIndexedStack>().first;
+    expect(renderIndexedObject.clipBehavior, equals(Clip.antiAlias));
```
Comment (maheshmnj) [inline packages/flutter/test/widgets/stack_test.dart:818]: @xu-baolin The test is failing when updating clipBehavior. Are my changes correct?

File: packages/flutter/lib/src/widgets/basic.dart [hunk 3]
```diff
@@ -3927,6 +3930,7 @@ class IndexedStack extends Stack {
     assert(_debugCheckHasDirectionality(context));
     renderObject
       ..index = index
+      ..fit = fit
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/basic.dart:3933]: `updateRenderObject` also needs to update the clipBehavior on the RenderObject.

File: packages/flutter/test/widgets/stack_test.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/test/widgets/stack_test.dart:818]: Likely because `updateRenderObject` isn't updating the clip behavior (see my other comment above).

File: packages/flutter/test/widgets/stack_test.dart [hunk 4]
```diff
@@ -799,4 +799,22 @@ void main() {
       "'alignment', or an explicit 'textDirection', to the Stack.",
     );
   });
+
+  testWidgets('Can update clipBehavior of IndexedStack',
+      (WidgetTester tester) async {
+    await tester.pumpWidget(IndexedStack(textDirection: TextDirection.ltr));
+    final RenderIndexedStack renderObject =
+        tester.allRenderObjects.whereType<RenderIndexedStack>().first;
```
Comment (goderbauer) [inline packages/flutter/test/widgets/stack_test.dart:807]: Probably a little more idiomatic: 

```suggestion
        tester.renderObject<RenderIndexedStack>(find.type(IndexedStack));
```

File: packages/flutter/test/widgets/stack_test.dart [hunk 5]
```diff
@@ -799,4 +799,22 @@ void main() {
...
+    expect(renderObject.clipBehavior, equals(Clip.hardEdge));
+
+    /// Update clipBehavior to Clip.antiAlias
+
+    await tester.pumpWidget(IndexedStack(
+      textDirection: TextDirection.ltr,
+      clipBehavior: Clip.antiAlias,
+    ));
+    final RenderIndexedStack renderIndexedObject =
+      tester.allRenderObjects.whereType<RenderIndexedStack>().first;
```
Comment (goderbauer) [inline packages/flutter/test/widgets/stack_test.dart:817]: same

File: packages/flutter/test/widgets/stack_test.dart [hunk 6]
```diff
@@ -799,4 +799,22 @@ void main() {
...
+    expect(renderIndexedObject.clipBehavior, equals(Clip.antiAlias));
+  });
 }
```
Comment (goderbauer) [inline packages/flutter/test/widgets/stack_test.dart:820]: Can you also add a test for the `fit` property?

File: packages/flutter/test/widgets/stack_test.dart [hunk 7]
```diff
@@ -799,4 +799,22 @@ void main() {
...
   });
+
+  testWidgets('Can update clipBehavior of IndexedStack',
+      (WidgetTester tester) async {
+    await tester.pumpWidget(IndexedStack(textDirection: TextDirection.ltr));
+    final RenderIndexedStack renderObject =
+        tester.allRenderObjects.whereType<RenderIndexedStack>().first;
+    expect(renderObject.clipBehavior, equals(Clip.hardEdge));
+
+    /// Update clipBehavior to Clip.antiAlias
```
Comment (goderbauer) [inline packages/flutter/test/widgets/stack_test.dart:810]: `///` -> `//`

File: packages/flutter/test/widgets/stack_test.dart (hunk 2 above)
Comment (maheshmnj) [reply packages/flutter/test/widgets/stack_test.dart:818]: Yes thanks that worked.

File: packages/flutter/test/widgets/stack_test.dart (hunk 7 above)
Comment (maheshmnj) [reply packages/flutter/test/widgets/stack_test.dart:810]: fixed

File: packages/flutter/test/widgets/stack_test.dart (hunk 6 above)
Comment (maheshmnj) [reply packages/flutter/test/widgets/stack_test.dart:820]: Added, Please review.

File: packages/flutter/lib/src/widgets/basic.dart (hunk 3 above)
Comment (maheshmnj) [reply packages/flutter/lib/src/widgets/basic.dart:3933]: Thanks!  Fixed.

File: packages/flutter/test/widgets/stack_test.dart (hunk 4 above)
Comment (maheshmnj) [reply packages/flutter/test/widgets/stack_test.dart]: Done

**Review by xu-baolin — APPROVED** [review]
LGTM
