### PR TITLE
fix a draggableScrollableSheet's LocalHistoryEntry leaking

### LINKED ISSUE #110123: Persistent bottomSheet with DraggableScrollableSheet not clearing route LocalHistoryEntry when back button pressed
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Go to Page 2
3. Drag the Bottom Sheet `DraggableScrollableSheet` up and down multiple times, then keep it at max height and press android navigation back button, after which you will still see back icon on the App bar even though the bottom sheet is closed and we navigated back to Home page, which means the route LocalHistoryEntry is not cleared, furthermore pressing back button on Home screen will not close the App, rather you will have to press it multiple times to clear all route LocalHistoryEntries
4. But if you hot restart the App and go to Page 2 drag the sheet up and then completely down and press android navigation back button then everything will work fine

**Expected results:**
By definition persistent bottom sheets on `Scaffold.bottomSheet` should not create a `LocalHistoryEntry` as the sheet is considered part of the main UI as per material guidelines, however even if it is creating a LocalHistoryEntry it should clear it from history when navigated back. This is from `Scaffold.bottomSheet` documentation: `Unlike the persistent bottom sheet displayed by showBottomSheet this bottom sheet is not a LocalHistoryEntry and cannot be dismissed with the scaffold appbar's back button`

**Actual results:**
Persistent bottom sheets is creating a LocalHistoryEntry when `DraggableScrollableSheet` is used and probably not clearing it from history when navigated back

<details>
<summary>Code sample</summary>

```dart
void main() => runApp(const PersistentBottomSheetIssue());

class PersistentBottomSheetIssue extends StatelessWidget {
  const PersistentBottomSheetIssue({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final theme = ThemeData.light();
    return MaterialApp(
      home: const BottomNavigator(),
      theme: theme.copyWith(
        bottomSheetTheme: theme.bottomSheetTheme.copyWith(
          backgroundColor: Colors.grey,
          shape: const RoundedRectangleBorder(
            borderRadius: BorderRadiusDirectional.only(
              topStart: Radius.circular(15.0),
              topEnd: Radius.circular(15.0),
            ),
          ),
        ),
      ),
    );
  }
}

class BottomNavigator extends StatefulWidget {
  const BottomNavigator({super.key});

  @override
  State<BottomNavigator> createState() => _BottomNavigatorState();
}

class _BottomNavigatorState extends State<BottomNavigator> {
  late List<Widget> _pages;
  final int _homePageIndex = 0;
  var _selectedPageIndex = 0;

  bool get isHomepage => _selectedPageIndex == _homePageIndex;

  void _selectPage(int index) {
    setState(() => _selectedPageIndex = index);
  }

  @override
  void initState() {
    super.initState();
    _selectedPageIndex = _homePageIndex;
    _pages = <Widget>[const HomePage(), const Page2()];
  }

  @override
  Widget build(BuildContext context) {
    final bottomNavigator = BottomAppBar(
      shape: const CircularNotchedRectangle(),
      clipBehavior: Clip.antiAlias,
      color: Colors.transparent,
      child: BottomNavigationBar(
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
          BottomNavigationBarItem(icon: Icon(Icons.ac_unit), label: 'Page 2'),
        ],
        onTap: _selectPage,
        currentIndex: _selectedPageIndex,
        type: BottomNavigationBarType.fixed,
      ),
    );

    return Scaffold(
      body: WillPopScope(
        onWillPop: () {
          if (!isHomepage) {
            _selectPage(_homePageIndex);
            return Future.value(false);
          }
          return Future.value(true);
        },
        child: _pages[_selectedPageIndex],
      ),
      appBar: AppBar(title: Text(isHomepage ? 'Home' : 'Page2')),
      backgroundColor: isHomepage ? Colors.greenAccent : Colors.lightBlue,
      bottomNavigationBar: bottomNavigator,
      bottomSheet: isHomepage
          ? null
          : SizedBox(
              width: double.infinity,
              child: DraggableScrollableSheet(
                initialChildSize: 0.1,
                minChildSize: 0.1,
                maxChildSize: 0.5,
                expand: false,
                snap: true,
                builder: (_, sc) => SingleChildScrollView(
                  controller: sc,
                  child: const Center(
                    child: Padding(
                      padding: EdgeInsets.all(8.0),
                      child: Text(
                          'Scroll me up and down multiple times, then keep '
                          'me at max size and press back button, you will see back '
                          'icon on the App bar even though the bottom sheet is '
                          'closed and we navigated to Home page, means the route '
                          'LocalHistoryEntry is not gone'),
                    ),
                  ),
                ),
              ),
            ),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('Home'));
  }
}

class Page2 extends StatelessWidget {
  const Page2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('Page2'));
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1889], locale en-US)
    • Flutter version 3.0.5 at \Apps\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at \Apps\Android\Sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • ANDROID_HOME = \Apps\Android\Sdk
    • Java binary at: \Apps\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Apps\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at \Apps\JetBrains\IntelliJ IDEA 2021.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
```

</details>

https://user-images.githubusercontent.com/1186833/186279760-648608d9-da0a-4b1b-8304-2314c792c00d.mp4

### PR DESCRIPTION
**Pull request by xu-baolin**
If the persistent bottom sheet is a draggableScrollableSheet and the user expand it, there will be a back button for a11y.
There are two situations that the local history entry may be leaked,
1, When user shrink the sheet we can not remove the entry due to the double calculations precision.
2, We do not remove the route entry when unmount the draggableScrollableSheet widget.

Fixes https://github.com/flutter/flutter/issues/110123

### CODE REVIEW

File: packages/flutter/lib/src/material/scaffold.dart [hunk 1]
```diff
@@ -2177,29 +2177,27 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
...
       // The new _currentBottomSheet is not a local history entry so a "back" button
       // will not be added to the Scaffold's appbar and the bottom sheet will not
       // support drag or swipe to dismiss.
       final AnimationController animationController = BottomSheet.createAnimationController(this)..value = 1.0;
-      LocalHistoryEntry? persistentSheetHistoryEntry;
       bool persistentBottomSheetExtentChanged(DraggableScrollableNotification notification) {
-        if (notification.extent > notification.initialExtent) {
-          if (persistentSheetHistoryEntry == null) {
-            persistentSheetHistoryEntry = LocalHistoryEntry(onRemove: () {
-              if (notification.extent > notification.initialExtent) {
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/scaffold.dart:2192]: This condition is always true, right?

Comment (Piinks) [reply packages/flutter/lib/src/material/scaffold.dart:2192]: It would seem so.. I am out today and will take a closer look a little later. FYI @thkim1011, who is joining us in scrolling land. Tae has been studying the draggable scrollable sheet. :)

Comment (xu-baolin) [reply packages/flutter/lib/src/material/scaffold.dart:2192]: @thkim1011 Hi, nice to meet you : )

Comment (absar) [reply packages/flutter/lib/src/material/scaffold.dart:2192]: Isn't it true that, by definition persistent bottom sheets on `Scaffold.bottomSheet` should not create a `LocalHistoryEntry` as the sheet is considered part of the main UI as per material guidelines, from `Scaffold.bottomSheet` documentation: `Unlike the persistent bottom sheet displayed by showBottomSheet this bottom sheet is not a LocalHistoryEntry and cannot be dismissed with the scaffold appbar's back button`. If so why is it even creating a `LocalHistoryEntry`

**Comment by absar** [comment]
Isn't it true that, by definition persistent bottom sheets on `Scaffold.bottomSheet` should not create a `LocalHistoryEntry` as the sheet is considered part of the main UI as per material guidelines, from `Scaffold.bottomSheet` documentation: `Unlike the persistent bottom sheet displayed by showBottomSheet this bottom sheet is not a LocalHistoryEntry and cannot be dismissed with the scaffold appbar's back button`. If so why is it even creating a `LocalHistoryEntry`

**Comment by xu-baolin** [comment]
> Isn't it true that, by definition persistent bottom sheets on `Scaffold.bottomSheet` should not create a `LocalHistoryEntry` as the sheet is considered part of the main UI as per material guidelines, from `Scaffold.bottomSheet` documentation: `Unlike the persistent bottom sheet displayed by showBottomSheet this bottom sheet is not a LocalHistoryEntry and cannot be dismissed with the scaffold appbar's back button`. If so why is it even creating a `LocalHistoryEntry`

This is a special case where if the persistent sheet has a draggable widget we should give it a back button for a11y.
Maybe we can update the docs for more information.

**Comment by absar** [comment]
Ok understood. Can the reviewers prioritize it, the issue is giving a bad UX for the end users

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/scaffold.dart:2192]: This statement in the scope of  `onRemove` callback and it should be never changed until it actually called, right?

Comment (xu-baolin) [reply packages/flutter/lib/src/material/scaffold.dart:2192]: Line #2189 already ensures that this condition is true.

Comment (Piinks) [reply packages/flutter/lib/src/material/scaffold.dart:2192]: Oh silly me, I missed that.

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
