### PR TITLE
showDialog assertion for non-null builder or child property

### LINKED ISSUE #71834: ShowDialog: Misleading exception on null value of child and builder
On not providing ```child``` and ```builder``` argument in ```ShowDialog()``` throws Exception
```Null check operator used on a null value```

</img>

<details>
<summary>Code Sample</summary>

```Dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: ExampleDialogMaxWidth(),
    );
  }
}

class ExampleDialogMaxWidth extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
            child: Text("Dialog"),
            onPressed: () {
              showDialog(
                context: context,
              );
            }),
      ),
    );
  }
}

```

</details>

<details>
<summary>Logs</summary>

```Dart

════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown building Builder(dirty):
Null check operator used on a null value

The relevant error-causing widget was
MaterialApp
lib\main.dart:10
When the exception was thrown, this was the stack
#0      showDialog.<anonymous closure>
package:flutter/…/material/dialog.dart:985
#1      _DialogRoute.buildPage
package:flutter/…/widgets/routes.dart:1762
#2      _ModalScopeState.build.<anonymous closure>.<anonymous closure>
package:flutter/…/widgets/routes.dart:840
#3      Builder.build
package:flutter/…/widgets/basic.dart:7552
#4      StatelessElement.build
package:flutter/…/widgets/framework.dart:4758
...

```

</details>

### PR DESCRIPTION
**Pull request by Amitpatil215**
## Description

If child and builder are null then

**Expected Exception** (in this PR)
```
The following assertion was thrown while handling a gesture:
'package:flutter/src/material/dialog.dart': 
Failed assertion: line 975 pos 10: 'child != null || builder != null': is not true.
```

<details>
<summary>Logs</summary>

```Dart

════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/material/dialog.dart': Failed assertion: line 975 pos 10: 'child != null || builder != null': is not true.

When the exception was thrown, this was the stack
#2      showDialog
package:flutter/…/material/dialog.dart:975
#3      ExampleDialogMaxWidth.build.<anonymous closure>
package:issue_44570_dialog_max_width/main.dart:27
#4      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:990```
```
</details>

**Existing Exception**

```Dart
The following _CastError was thrown building Builder(dirty):
Null check operator used on a null value
```

### Special Mention
On providing ```child``` and ```builder``` simultaneously may pass assertion but we only considering ```child``` as both are not-null.  
Refer
https://github.com/flutter/flutter/blob/1aafb3a8b9b0c36241c5f5b34ee914770f015818/packages/flutter/lib/src/material/dialog.dart#L993

## Related Issues

fixes #71834

## Tests

I added the following tests:

None

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/dialog.dart [hunk 1]
```diff
@@ -972,7 +972,7 @@ Future<T?> showDialog<T>({
   )
   Widget? child,
 }) {
-  assert(child == null || builder == null);
+  assert(child != null || builder != null);
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/dialog.dart:975]: I don't think this change achieves what you're looking for. The original assert simply doesn't allow for both to be null at the same time, which is valid use case: We don't want users to define both, even though the code technically allows for it. 

I think what you meant to do was introduce another assert:
```suggestion
  assert(child == null || builder == null);
  assert(child != null || builder != null);
```

We can need add a test to ensure that the assert is triggered to make sure there are no regressions

Comment (shihaohong) [reply packages/flutter/lib/src/material/dialog.dart:975]: I helped write the tests for you since it can be quite convoluted to write assertion tests:
```dart
  testWidgets('showDialog child and builder cannot be simultaneously defined', (WidgetTester tester) async {
    late BuildContext currentBuildContext;
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Center(
            child: Builder(
              builder: (BuildContext context) {
                currentBuildContext = context;
                return Container();
              }
            ),
          ),
        ),
      ),
    );

    expect(() async {
      showDialog<void>(
        context: currentBuildContext,
        child: const Text('Child'),
        builder: (BuildContext context) {
          return const Text('Builder');
        },
      );
    }, throwsAssertionError);
  });

  testWidgets('showDialog child or builder must be defined', (WidgetTester tester) async {
    late BuildContext currentBuildContext;
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Center(
            child: Builder(
              builder: (BuildContext context) {
                currentBuildContext = context;
                return Container();
              }
            ),
          ),
        ),
      ),
    );

    expect(
      () => showDialog<void>(context: currentBuildContext),
      throwsAssertionError,
    );
  });
```

**Comment by Amitpatil215** [comment]
Resolved suggestions. Thank you for helping me out :)

File: packages/flutter/test/material/dialog_test.dart [hunk 2]
```diff
@@ -217,6 +217,57 @@ void main() {
     expect(materialWidget.shape, customBorder);
   });
 
+   testWidgets('showDialog child and builder cannot be simultaneously defined', (WidgetTester tester) async {
```
Comment (shihaohong) [inline packages/flutter/test/material/dialog_test.dart:220]: nit: indentation is off
```suggestion
  testWidgets('showDialog child and builder cannot be simultaneously defined', (WidgetTester tester) async {
```

**Review by shihaohong — APPROVED** [review]
LGTM, with a nit
