### PR TITLE
Context Menus

### LINKED ISSUE #22210: Missing API for TextSelectionToolbar styling
There is no way to override `TextSelectionToolbar` styles.
Example below doesn't have any effect on TextSelectionToolbar styling

```dart
Theme(
    data: Theme.of(context).copyWith(
        splashColor: Colors.black, // should update splash color of FlatButton used in Toolbar
        canvasColor: Colors.red, // should update background color
    ),
    child: TextField(...),
);
```

Background color of TextSelectionToolbar is also not obvious to override (it comes from underlying `Material` which takes `canvasColor` as a background). This chain of "dependencies" is not really obvious, so maybe it worth extending `ThemeData` with `textSelectionToolbarTheme` prop?

Flutter doctor output:

```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-BY)
    • Flutter version 0.8.2 at /Users/r1zzu/flutter
    • Framework revision 5ab9e70727 (2 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/r1zzu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/r1zzu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2017.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

### LINKED ISSUE #49996: Enable Copy-toolbar for all widgets
# Use case

On iOS it is a common pattern to be able to long-press content in various form and bring up the same Edit Menu as you get in text fields for copying & other actions.

IMG_40CAC5CF2B14-1

# Proposal

I'm proposing the extraction of the current `CupertinoTextSelectionToolbar` and `_TextSelectionToolbar` into a `showEditMenu` function, working just like `showMenu` for popup menus.

### LINKED ISSUE #73574: Proposal: Simple custom text selection toolbars
It should be easier to create and modify custom text selection toolbars.

## Use case
Users often want to just do something simple like add an extra button to the existing text selection toolbar.  That should look something like this:

```dart
TextField(
  textSelectionToolbar: TextSelectionToolbar(
    children: <Widget>[
      ...TextSelectionToolbar.defaultChildren,
      TextSelectionToolbarTextButton(
        onPressed: () { /* Do special stuff */ },
        child: const Text('My special button'),
      ),
    ],
  ),
)
```

Screen Shot 2021-01-08 at 10 17 01 AM

## Context
Recently, https://github.com/flutter/flutter/pull/69428 made it possible to customize the Material text selection toolbar and buttons, and https://github.com/flutter/flutter/pull/73578 does the same for Cupertino.  However, the current TextSelectionControls interface still requires a bunch of extra work in order to be able to use a custom toolbar.  Rather than the simple example above, it looks more like this:

```dart
TextField(
  textSelectionControls: MyTextSelectionControls(),
)

...

class MyTextSelectionControls extends TextSelectionControls {
  @override
  Widget buildToolbar(
    // Lots of confusing parameters that I don't care about when I just want to add a button:
    BuildContext context,
    Rect globalEditableRegion,
    double textLineHeight,
    Offset selectionMidpoint,
    List<TextSelectionPoint> endpoints,
    TextSelectionDelegate delegate,
    ClipboardStatusNotifier clipboardStatus,
  ) {
    /*
      ... Lots of confusing math that's duplicating what we do internally to calculate the anchors...
   */

    return TextSelectionToolbar(
      anchorAbove: anchorAbove,
      anchorBelow: anchorBelow,
      children: <Widget>[
        ...aRecreationOfTheDefaultButtons,
        TextSelectionToolbarTextButton(
          onPressed: () { /* Do special stuff */ },
          child: const Text('My special button'),
        ),
      ],
    );
  }
}
```

## Proposal

I propose that we make a breaking change to the existing TextSelectionControls and its Material and Cupertino counterparts.  The new interface should allow something similar to the simplicity of the first example above.  It should be built around TextSelectionToolbar and should not hardcode a preference for the existing default buttons.

I plan to update this with a full design doc if I'm able to get around to it.

*Update*: [Design doc](https://docs.google.com/document/d/1F1itGgbSS3Cbq70hScSCNriDoux1sMGF9LHZsMdvU74/edit?usp=sharing&resourcekey=0-RkHGwhe-tcoTGlaQyclPtQ)

### LINKED ISSUE #79796: Add the ability to disable ContextMenu in TextFields
In the case where we have implemented a consistent ContextMenu theme across the entire app, we would like to disable the built-in context menu and use our own instead. Currently the TextField widget swallows the RightClick event, so there is no way for us to override it.  See this comment for more specifics: https://github.com/flutter/flutter/issues/74255#issuecomment-790810610

@justinmc

### LINKED ISSUE #90563: ☂️  Text editing for desktop - stable
This issue tracks the work required to consider text editing on desktop to be stable.

 * [x] https://github.com/flutter/flutter/issues/90562
 * [x] https://github.com/flutter/flutter/issues/24222
 * [x] https://github.com/flutter/flutter/issues/59141
 * [ ] https://github.com/flutter/flutter/issues/74255
 * [x] https://github.com/flutter/flutter/pull/93170
 * [x] https://github.com/flutter/flutter/issues/98272
 * [x] https://github.com/flutter/flutter/issues/90993

### LINKED ISSUE #98272: Desktop's right click menu doesn't work outside of text fields
On our desktop platforms Mac, Linux, and Windows, right clicking anywhere in a native app usually brings up the context menu with some relevant options (Select All, etc.).  In Flutter desktop apps, that menu can only be shown inside of an EditableText.  Even if a developer wanted to add custom support for that menu to be shown somewhere, it would be very hacky due to tight coupling with EditableText.  Soon, selection will be supported outside of EditableText (https://github.com/flutter/flutter/pull/95226), and this will be even more needed.

We should provide a simple public API for showing/hiding this menu and modifying its appearance, and we should refactor EditableText to consume that API.

### To reproduce

 1. Run an app with some text field that doesn't take up the entire screen (example below).
 2. Right click on the text field and notice that the menu is shown.
 3. Click anywhere to dismiss the menu.
 4. Right click anywhere outside of the text field.
 5. No context menu is shown, and there is no way for the developer to show it if they wanted to.

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter Demo'),
        ),
        body: const Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

</details>

Related:
https://github.com/flutter/flutter/issues/74255
https://github.com/flutter/flutter/issues/90563

### LINKED ISSUE #111213: Remove TextSelectionDelegate from SelectableRegionState
SelectableRegionState currently [mixes in](https://github.com/flutter/flutter/blob/652ff7a5e6684fb3fe94f89cfd23a8445f5943e5/packages/flutter/lib/src/widgets/selectable_region.dart#L241) TextSelectionDelegate in order to receive text selection toolbar functionality, however, this functionality is being remove from TextSelectionDelegate in https://github.com/flutter/flutter/pull/107193.  After the deprecations in that PR are removed, it should be possible to remove TextSelectionDelegate from SelectableRegionState altogether.

### Why remove TextSelectionDelegate?

TextSelectionDelegate provides functionality that is related to editing text and which SelectableRegion doesn't use ([example](https://github.com/flutter/flutter/blob/652ff7a5e6684fb3fe94f89cfd23a8445f5943e5/packages/flutter/lib/src/widgets/selectable_region.dart#L869)).  Text selection should be separate from text editing.

CC @chunhtai

### PR DESCRIPTION
**Pull request by justinmc**
[Design doc](https://docs.google.com/document/d/1F1itGgbSS3Cbq70hScSCNriDoux1sMGF9LHZsMdvU74/edit?resourcekey=0-RkHGwhe-tcoTGlaQyclPtQ)

This PR makes it easy to work with context menus, the menu that shows up on right click, longpress, or when working with text selection.

Screenshot from 2022-07-26 16-45-11

### tl;dr

  * Widgets that have context menus, like TextField, now have a `contextMenuBuilder` parameter that allows any widget to be built as the context menu.
  * The context menu can be controlled, and even displayed in new places, using the new global ContextMenuController.
  * Several new widgets have been added to make it easy to compose context menus, like AdaptiveTextSelectionToolbar.
  * The old way to build context menus in TextSelectionControls has been deprecated.

More details below.

### Deprecations

The old way of building a toolbar still works exactly as before, but it's deprecated.  That's toolbarOptions and the toolbar-related parts of TextSelectionControls.

  * toolbarOptions (in EditableText et. al.)
  * TextSelectionControls.buildToolbar
  * TextSelectionControls.canCopy (and other toolbar operations)
  * TextSelectionDelegate.canCopy (and other toolbar operations)
  * TextSelectionControls.handleCopy etc.

All of these have been replace by contextMenuBuilder and a suite of widgets that allow customizing the default text selection toolbar.  Direct equivalents of canCopy etc. are now at TextSelectionToolbarButtonItemsBuilder.canCopy etc.

#### New stuff immediately deprecated

  * TextSelectionHandleControls
    - Since I have deprecated the parts of TextSelectionControls related to the toolbar, I needed a way to distinguish old TextSelectionControls that still desire to customize the toolbar.  To do that, I created a new mixin TextSelectionHandleControls on TextSelectionControls for new usages that don't care about the toolbar.  I immediately deprecated TextSelectionHandleControls.  When the deprecation is removed, we can remove that class and all TextSelectionControls will only relate to handles and not toolbars.
  * buttonItemsForToolbarOptions
    - For the same reason as the previous point, this method was created and immediately deprecated.  It translates between the old toolbarOptions system and the new buttonItems.

### User-side changes

  * Mac no longer shows a "Select all" button.  I think we missed this before and native Mac shouldn't show one.  I don't ever see one natively, except in the browser.
  * The text selection menu is now clamped to within the field.

### API changes
  * The desktop text selection toolbar and buttons classes that were previously private have been made public.
    - DesktopTextSelectionToolbar, CupertinoDesktopTextSelectionToolbar, CupertinoDesktopTextSelectionToolbarButton, CupertinoDesktopTextSelectionToolbarButton
    - This is so that we can give users a way to build the default toolbar for the platform, via AdaptiveTextSelectionToolbar and CupertinoAdaptiveTextSelectionToolbar.
  * EditableTextState.clipboardStatus was made public.
    - This was done to allow EditableTextContextMenuButtonItemsBuilder to build the context menu buttons based on the same clipboard status that the EditableText has.

### Open questions

  * ContextMenuButtonItem
    - I'm not using @gspencergoog's [MenuItem](https://master-api.flutter.dev/flutter/widgets/MenuItem-class.html) class as it doesn't seem relevant here.  Am I wrong or is there anything else to do to make this easier to mesh with cascading menus?
    - Also, @Renzo-Olivares had the idea to include a `child` parameter to pass a Widget to the button instead of just a text label hardcoded to a Text.  A good use case would be for an icon button.
  * ContextMenuController.isShown only knows if *any* menu is shown, not a specific one.
    - Because ContextMenuController is global, show/hide can be called at any time from anywhere.  If I call `show`, I have no guarantee that my menu is visible or not in the future.  Will that be important?  I could add an "onHidden" callback or something.

### Related

This PR was reopened from https://github.com/flutter/flutter/pull/104647 due to incorrectly failing customer tests, losing ~91 commits of history.

Fixes https://github.com/flutter/flutter/issues/98272
Fixes https://github.com/flutter/flutter/issues/73574
Fixes https://github.com/flutter/flutter/issues/90563
Fixes https://github.com/flutter/flutter/issues/79796
Fixes https://github.com/flutter/flutter/issues/22210
Fixes https://github.com/flutter/flutter/issues/49996
Partial fix for https://github.com/flutter/flutter/issues/74255
After deprecations are removed, will fix: https://github.com/flutter/flutter/issues/111213

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/default_text_selection_toolbar.dart [hunk 1]
```diff
@@ -0,0 +1,208 @@
...
+  /// The platform to base the toolbar on.
+  ///
+  /// If null, then [defaultTargetPlatform] will be used.
+  TargetPlatform get targetPlatform => _targetPlatform ?? defaultTargetPlatform;
+
+  final TargetPlatform? _targetPlatform;
+
+  /// The children of the toolbar.
+  ///
+  /// If provided, buttonDatas cannot also be provided.
```
Comment (pedromassango) [inline packages/flutter/lib/src/cupertino/default_text_selection_toolbar.dart:79]:
```suggestion
  /// If provided, [buttonDatas] cannot also be provided.
```

Comment (justinmc) [reply packages/flutter/lib/src/cupertino/default_text_selection_toolbar.dart]: Thanks!

**Comment by pedromassango** [comment]
@justinmc is there any chance to make it disappear when the application lose focus?

**Comment by justinmc** [comment]
@pedromassango It seems like it's not possible right now to detect when the app loses focus on desktop (without a plugin).  Here's a PR that is trying to add that functionality for Windows: https://github.com/flutter/engine/pull/29288.  I think we can do it once that is merged.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 2]
```diff
@@ -1676,3 +1750,93 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
...
+/// By default the [targetPlatform] will be [defaultTargetPlatform].
+///
+/// See also:
+///
+/// * [TextSelectionToolbarButtonsBuilder], which builds the button Widgets
+///   given [ContextMenuButtonItem]s.
+/// * [DefaultTextSelectionToolbar], which builds the toolbar itself.
+/// * [EditableTextContextMenuButtonItemBuilder], which performs a similar role
+///   but for [EditableText]'s context menu.
+class _SelectableRegionContextMenuButtonItemsBuilder extends StatelessWidget {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1766]: @chunhtai, I'd prefer to make this public so that users can build the same buttons that show by default for SelectableRegion, but the delegate here is a private class _SelectableRegionState. I wonder what you think of this approach, if you think we could make _SelectableRegionState public or if there is another way.

This is the same pattern that I use to allow users to customize EditableText's default buttons. That class is EditableTextContextMenuButtonDatasBuilder, and it is passed EditableTextState, which is public.

File: packages/flutter/lib/src/widgets/context_menu_button_item.dart [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+
+/// The type and callback for a context menu button.
+///
+/// See also:
+///
+///  * [DefaultTextSelectionToolbar], which can take a list of
+///    ContextMenuButtonItems and create a platform-specific context menu with
+///    the indicated buttons.
+@immutable
+class ContextMenuButtonItem {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/context_menu_button_item.dart:33]: @gspencergoog I mentioned this in my PR description, but this is how I'm defining the data that can be used to generate buttons in my menu.  Otherwise everything else is just widgets.  It seems to me that something like [MenuItem](https://master-api.flutter.dev/flutter/widgets/MenuItem-class.html) wouldn't work here, but let me know if you have any ideas here or elsewhere for how to make this work better with your cascading menu work.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 4]
```diff
@@ -337,7 +388,51 @@ class TextSelectionOverlay {
   /// {@macro flutter.widgets.SelectionOverlay.showToolbar}
   void showToolbar() {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:389]: @camsim99 Does it look like you'll be able to tie your spell check menu in here somewhere?  I guess if users are customizing their context menu via contextMenuBuilder then they will expect to be able to update the spellcheck menu too.

Hopefully it should also be easy to build the actual UI for your menu using the toolbar widgets in this PR.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 2 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1766]: Yeah I think we can make it public if there is a reasonable use case.
I remember I originally made it public so you can see a lot of public method has doc string, but decide to close it until there is a use case for it.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1766]: Ok good to hear, I'll plan to make that change to this PR.

File: packages/flutter/lib/src/material/desktop_text_selection_toolbar.dart [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+        _kToolbarScreenPadding,
+        paddingAbove,
+        _kToolbarScreenPadding,
+        _kToolbarScreenPadding,
+      ),
+      child: CustomSingleChildLayout(
+        delegate: DesktopTextSelectionToolbarLayoutDelegate(
+          anchor: anchor - localAdjustment,
+        ),
+        child: _defaultToolbarBuilder(context, Column(
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/material/desktop_text_selection_toolbar.dart:81]: Nit: trailing comma, and formatting: `context`, and `Column` on their own lines.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 6]
```diff
@@ -3553,12 +3654,14 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
     );
+
+    return child;
   }
 
   /// Builds [TextSpan] from current editing value.
   ///
   /// By default makes text in composing range appear as underlined.
-  /// Descendants can override this method to customize appearance of text.
+  /// Descendants can override this method to customize appearance of text
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/editable_text.dart:3664]: Nit: Comment should end with a `.`

**Review by Renzo-Olivares — COMMENTED** [review]
Just a few nits from my first look-over.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:3664]: Not sure how I ended up removing that :grin:

File: examples/api/lib/material/context_menu/anywhere.dart [hunk 7]
```diff
@@ -0,0 +1,154 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
```
Comment (gspencergoog) [inline examples/api/lib/material/context_menu/anywhere.dart:1]: This file should be named to match the snake_case version of the symbol that it is attached to in the `context_menu.dart` file, along with an index of which example on that symbol this is. This makes it easy to add more than one example to a symbol and keep track of them.

```
examples/api/lib/material/context_menu/context_menu_controller.0.dart
```
Same for all the examples (which are really great to see!).

File: examples/api/lib/material/context_menu/anywhere.dart [hunk 8]
```diff
@@ -0,0 +1,154 @@
...
+        ),
+        body: _ContextMenuRegion(
+          contextMenuBuilder: (BuildContext context, Offset primaryAnchor, [Offset? secondaryAnchor]) {
+            // The custom context menu will look like the default context menu
+            // on the current platform, but it will have only a single 'Print'
+            // button.
+            return DefaultTextSelectionToolbar(
+              primaryAnchor: primaryAnchor,
+              secondaryAnchor: secondaryAnchor,
+              buttonItems: <ContextMenuButtonItem>[
```
Comment (gspencergoog) [inline examples/api/lib/material/context_menu/anywhere.dart:41]: can `buttonItems` be called `children`, to keep in line with what most container widgets in Flutter use? And is it necessary to use a specific type of item, or could you use any `Widget` instead?

File: examples/api/lib/material/context_menu/with_specific_selection.dart [hunk 9]
```diff
@@ -0,0 +1,82 @@
...
+            ],
+          ),
+        ),
+      ),
+    );
+  }
+}
+
+bool _isValidEmail(String text) {
+  return RegExp(r'^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$')
```
Comment (gspencergoog) [inline examples/api/lib/material/context_menu/with_specific_selection.dart:80]: I'd split this up into multiple lines, and use named regions (e.g. `(?<foo>.*)` for a region named 'foo') to help explain the regexp a bit.

**Review by gspencergoog — COMMENTED** [review]
Just some starting comments, I didn't get very far yet...

File: examples/api/lib/material/context_menu/anywhere.dart (hunk 8 above)
Comment (justinmc) [reply examples/api/lib/material/context_menu/anywhere.dart:41]: I allow either/or, Widgets or ContextMenuButtonItems, mainly for convenience.  @Renzo-Olivares was also confused by why I did this.  I just added a new [appendix](https://docs.google.com/document/d/1F1itGgbSS3Cbq70hScSCNriDoux1sMGF9LHZsMdvU74/edit?resourcekey=0-RkHGwhe-tcoTGlaQyclPtQ#heading=h.lbwwfocsw4n5) to my design doc to better explain this, along with some examples.  Let me know if this pattern still doesn't make sense or if I can improve it.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 10]
```diff
@@ -1676,3 +1741,113 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
...
+  BuildContext,
+  SelectableRegionState,
+  Offset,
+  [Offset?]
+);
+
+/// Calls [builder] with the [ContextMenuButtonItem]s representing the
+/// buttons in this platform's default text selection menu.
+///
+/// By default the [targetPlatform] will be [defaultTargetPlatform].
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1763]: Since there's a build context available, shouldn't this use `Theme.of(context).platform`?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 11]
```diff
@@ -337,7 +388,51 @@ class TextSelectionOverlay {
...
+
+    if (contextMenuBuilder == null) {
+      return;
+    }
+
+    // If right clicking on desktop, use the right click position as the only
+    // anchor.
+    final RenderBox renderBox = context.findRenderObject()! as RenderBox;
+    if (renderObject.lastSecondaryTapDownPosition != null) {
+      switch (defaultTargetPlatform) {
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/text_selection.dart:405]: Since you have a context here, this should be `Theme.of(context).platform)`.

File: packages/flutter/lib/src/cupertino/default_text_selection_toolbar.dart [hunk 12]
```diff
@@ -0,0 +1,205 @@
...
+import 'package:flutter/widgets.dart';
+
+import 'desktop_text_selection_toolbar.dart';
+import 'text_selection_toolbar.dart';
+import 'text_selection_toolbar_buttons_builder.dart';
+
+/// The default Cupertino context menu for text selection for the current
+/// platform.
+///
+/// Builds the mobile Cupertino context menu for all mobile platforms, not just
```
Comment (gspencergoog) [inline packages/flutter/lib/src/cupertino/default_text_selection_toolbar.dart:15]: Then maybe it needs a different name that doesn't include `Cupertino`?

File: packages/flutter/lib/src/cupertino/default_text_selection_toolbar.dart [hunk 13]
```diff
@@ -0,0 +1,205 @@
...
+/// parameters. If neither is given, then the default buttons will be used.
+///
+/// See also:
+///
+/// * [EditableTextContextMenuButtonItemsBuilder], which generates the default
+///   [ContextMenuButtonItem]s for the current platform for a context menu
+///   displaying inside of an [EditableText].
+/// * [TextSelectionToolbarButtonsBuilder], which builds the native-looking
+///   button Widgets for the current platform given [ContextMenuButtonItem]s.
+/// * [DefaultTextSelectionToolbar], which does the same thing as this widget
```
Comment (gspencergoog) [inline packages/flutter/lib/src/cupertino/default_text_selection_toolbar.dart:30]: This seems to contradict what it says above.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 14]
```diff
@@ -1676,3 +1741,113 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
...
+///
+/// See also:
+///
+/// * [TextSelectionToolbarButtonsBuilder], which builds the button Widgets
+///   given [ContextMenuButtonItem]s.
+/// * [DefaultTextSelectionToolbar], which builds the toolbar itself.
+/// * [EditableTextContextMenuButtonItemBuilder], which performs a similar role
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/selectable_region.dart]: I don't think `EditableTextContextMenuButtonItemBuilder` is a thing.

```suggestion
/// * [EditableTextContextMenuButtonItemsBuilder], which performs a similar role
```

File: examples/api/lib/material/context_menu/anywhere.dart (hunk 7 above)
Comment (justinmc) [reply examples/api/lib/material/context_menu/anywhere.dart]: Thanks for the explanation, I thought I might have been doing that wrong.

Are the tests supposed to be like context_menu.0_test.dart or context_menu.0.test.dart?  I see both patterns multiple times in the examples test directory.

File: examples/api/lib/material/context_menu/with_specific_selection.dart (hunk 9 above)
Comment (justinmc) [reply examples/api/lib/material/context_menu/with_specific_selection.dart]: Good call.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar_buttons_builder.dart [hunk 15]
```diff
@@ -0,0 +1,113 @@
...
+
+import 'package:flutter/foundation.dart';
+import 'package:flutter/widgets.dart';
+
+import 'debug.dart';
+import 'desktop_text_selection_toolbar_button.dart';
+import 'localizations.dart';
+import 'text_selection_toolbar_button.dart';
+
+/// A Function that builds a context menu given a List of its children Widgets.
```
Comment (gspencergoog) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar_buttons_builder.dart:13]:
```suggestion
/// A Function that builds a context menu given a List of `children` Widgets.
```

File: packages/flutter/lib/src/cupertino/text_selection_toolbar_buttons_builder.dart [hunk 16]
```diff
@@ -0,0 +1,113 @@
...
+typedef ContextMenuFromChildrenBuilder = Widget Function(
+  BuildContext context,
+  List<Widget> children,
+);
+
+/// Calls [builder] with a List of Widgets generated by turning [buttonItems]
+/// into the default Cupertino buttons for the platform.
+///
+/// Does not build Material buttons. On non-Apple platforms, Cupertino-style
+/// buttons will still be used, because the Cupertino library does not access
```
Comment (gspencergoog) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar_buttons_builder.dart:28]: I'm not really sure what this means. Does that mean that on non-Apple platforms, if I'm not using Material, I get Cupertino?

File: packages/flutter/lib/src/cupertino/text_selection_toolbar_buttons_builder.dart [hunk 17]
```diff
@@ -0,0 +1,113 @@
...
+    required this.buttonItems,
+    required this.builder,
+  });
+
+  /// The information used to create each button Widget.
+  final List<ContextMenuButtonItem> buttonItems;
+
+  /// Called with a List of Widgets created from the given [buttonItems].
+  ///
+  /// Typically builds a text selection toolbar with the given Widgets as
```
Comment (gspencergoog) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar_buttons_builder.dart:56]:
```suggestion
  /// Typically builds a text selection toolbar with the Widgets it is given as
```
(the widgets aren't given here, they're given when the builder is called)

File: packages/flutter/lib/src/cupertino/text_selection_toolbar_buttons_builder.dart [hunk 18]
```diff
@@ -0,0 +1,113 @@
...
+  /// children.
+  final ContextMenuFromChildrenBuilder builder;
+
+  /// Returns the default button label String for the button of the given
+  /// [ContextMenuButtonType].
```
Comment (gspencergoog) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar_buttons_builder.dart:61]: The `ContextMenuButtonType` isn't given as an attribute, it's inside the `buttonItem`.

**Review by gspencergoog — COMMENTED** [review]
Another round of comments.

I think the most significant thing here is to try and make `DefaultTextSelectionToolbar` and its ilk use only `Widget` children instead of having multiple modes of configuration. That will make it easier to use my menu API, and I think make things less confusing overall.

File: examples/api/lib/material/context_menu/anywhere.dart (hunk 7 above)
Comment (gspencergoog) [reply examples/api/lib/material/context_menu/anywhere.dart]: `context_menu.0_test.dart`, since otherwise they're not considered tests by some tools (most notably, I think `@visibleForTesting` doesn't work then).

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 19]
```diff
@@ -783,6 +750,50 @@ class CupertinoTextField extends StatefulWidget {
...
+      case TargetPlatform.fuchsia:
+        return TargetPlatform.iOS;
+      case TargetPlatform.linux:
+      case TargetPlatform.windows:
+      case TargetPlatform.macOS:
+        return TargetPlatform.macOS;
+    }
+  }
+
+  static Widget _defaultBuildContextMenu(BuildContext context, EditableTextState editableTextState, Offset primaryAnchor, [Offset? secondaryAnchor]) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/text_field.dart:784]: It feels like this is duplicating code between TextFields?

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 20]
```diff
@@ -783,6 +750,50 @@ class CupertinoTextField extends StatefulWidget {
...
+
+  /// The platform that the current `defaultTargetPlatform` will be treated as.
+  ///
+  /// The Cupertino library has no access to Material, so it cannot build things
+  /// like the Material text selection toolbars on the platforms that use them.
+  /// Instead it will treat those non-Cupertino platforms as if they are the
+  /// platform returned here.
+  ///
+  /// For example, using a CupertionTextField on an Android device will show the
+  /// iOS text selection toolbar.
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/text_field.dart:770]: Should this be a correct behavior? I would imagine people will still expect to see Android text selection toolbar.

File: packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart [hunk 21]
```diff
@@ -0,0 +1,296 @@
...
+      case TargetPlatform.linux:
+      case TargetPlatform.windows:
+        return editableTextState.textEditingValue.text.isNotEmpty
+           && !(editableTextState.textEditingValue.selection.start == 0
+               && editableTextState.textEditingValue.selection.end == editableTextState.textEditingValue.text.length);
+    }
+  }
+
+  /// Returns the [ContextMenuButtonItem]s for the given [ToolbarOptions].
+  @Deprecated(
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart:102]: Is this deprecated by accident?

File: examples/api/lib/material/context_menu/context_menu_controller.0.dart [hunk 22]
```diff
@@ -0,0 +1,154 @@
...
+    ContextMenuController.show(
+      context: context,
+      contextMenuBuilder: (BuildContext context) {
+        return widget.contextMenuBuilder(context, position);
+      },
+    );
+  }
+
+  void _hide() {
+    ContextMenuController.hide();
```
Comment (LongCatIsLooong) [inline examples/api/lib/material/context_menu/context_menu_controller.0.dart:134]: I find it easy to make mistakes in apps where more than one thing can present a context menu: there doesn't seem to be a way to know whose menu is currently being presented and when you call `hide` (especially in `dispose`), chances are you're hiding the context menu that another widget just presented.

File: examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart [hunk 23]
```diff
@@ -0,0 +1,70 @@
...
+        appBar: AppBar(
+          title: const Text('Custom button appearance'),
+        ),
+        body: Center(
+          child: Column(
+            children: <Widget>[
+              const SizedBox(height: 20.0),
+              TextField(
+                controller: _controller,
+                contextMenuBuilder: (BuildContext context, EditableTextState editableTextState, Offset primaryAnchor, [Offset? secondaryAnchor]) {
```
Comment (LongCatIsLooong) [inline examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart:33]: It could be tempting for people to try to directly/indirectly use `editableTextState.context` and trigger asserts.

File: packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart [hunk 24]
```diff
@@ -0,0 +1,296 @@
...
+    'Use `contextMenuBuilder` instead of `toolbarOptions`. '
+    'This feature was deprecated after v2.12.0-4.1.pre.',
+  )
+  static List<ContextMenuButtonItem>? buttonItemsForToolbarOptions(EditableTextState editableTextState, [TargetPlatform? targetPlatform]) {
+    final ToolbarOptions toolbarOptions = editableTextState.widget.toolbarOptions;
+    if (toolbarOptions == const ToolbarOptions()) {
```
Comment (tgucio) [inline packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart:108]: In nullable toolbarOptions isn't desired, then in `ToolbarOptions` class, you could define a static const ToolbarOptions.empty for this e.g.:
```
  static const empty = ToolbarOptions();
```
Then do:
```
if (toolbarOptions == ToolbarOptions.empty)
```

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 25]
```diff
@@ -1481,6 +1630,9 @@ class TextSelectionGestureDetectorBuilder {
     // trigger the selection overlay.
     // For backwards-compatibility, we treat a null kind the same as touch.
     final PointerDeviceKind? kind = details.kind;
+    // TODO(justinmc): Should a desktop platform show its selection toolbar when
+    // receiving a tap event?  Say a Windows device with a touchscreen.
```
Comment (tgucio) [inline packages/flutter/lib/src/widgets/text_selection.dart:1634]: Great question there - and I think it definitely should. Just added comments in #106586 and opened another PR to enable selection handles.

File: packages/flutter/lib/src/widgets/context_menu_controller.dart [hunk 26]
```diff
@@ -0,0 +1,114 @@
...
+/// ** See code in examples/api/lib/material/context_menu/anywhere.dart **
+/// {@end-tool}
+class ContextMenuController {
+  ContextMenuController._();
+
+  // The OverlayEntry is static because only one context menu can be displayed
+  // at one time.
+  static OverlayEntry? _menuOverlayEntry;
+
+  /// True iff the menu is currently being displayed.
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart]: Yeah you're right, I've been using `iff` all over our docs and someone else made the same argument in another review recently.  I'm trying to stop 😁 .  Will change it here and anywhere else in this PR.

File: packages/flutter/lib/src/widgets/context_menu_controller.dart [hunk 27]
```diff
@@ -0,0 +1,114 @@
...
+/// {@tool dartpad}
+/// This example shows how to use a GestureDetector to show a context menu
+//  anywhere in a widget subtree that receives a right click or long press.
+///
+/// ** See code in examples/api/lib/material/context_menu/anywhere.dart **
+/// {@end-tool}
+class ContextMenuController {
+  ContextMenuController._();
+
+  // The OverlayEntry is static because only one context menu can be displayed
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart:62]: Good question. I hadn't thought about it, but it should work out correctly as-is.  There can be only one context menu in any window of a Flutter app, which is correct.

**Comment by justinmc** [comment]
@gspencergoog I wanted to address your comment above about making ContextMenuButtonItem a widget, now that I've done some refactoring and exploratory code.  I'm coming to the conclusion that it's not feasible, but I'd be interested if you had different thoughts here.

The purpose of ContextMenuButtonItem is to provide an intermediate representation of the buttons before building their widgets, allowing:

  1. Button widgets to be built with knowledge of their siblings.  Some buttons look different depending on if they're the first button of many, or the only button, or a middle button, etc.
  2. Users to modify the buttons before they are turned into widgets.  Users may want use a different widget than the default but with the same label/callback, insert a custom button after the Paste button, etc.

Currently in my refactored PR, this looks something like this:

```dart
EditableTextContextMenuButtonItemsBuilder(
  editableTextState: editableTextState,
  builder: (BuildContext context, List<ContextMenuButtonItem> buttonItems) {
    // Here, buttonItems represents the default buttons for the current platform.
    // A user could modify those buttons in any way here before allowing them to
    // be built as full widgets below.
    return AdaptiveTextSelectionToolbar.buttonItems(
      primaryAnchor: primaryAnchor,
      secondaryAnchor: secondaryAnchor,
      buttonItems: buttonItems,
    );
  },
)
```

If I made them Widgets, it might look like this:

```dart
EditableTextContextMenuButtonItemsBuilder(
  editableTextState: editableTextState,
  builder: (BuildContext context, List<Widget> children) {
    // This looks nice, but the widget children are totally opaque.
    // If I wanted to just remove the Paste button, I couldn't figure
    // out which member of children to remove.
    return AdaptiveTextSelectionToolbar(
      primaryAnchor: primaryAnchor,
      secondaryAnchor: secondaryAnchor,
      children: children,
    );
  },
)
```

I could work around that problem by passing the children widgets as a specific type in order to allow their fields to be accessed, though that might start to defeat the purpose of just using widgets, and I still run into the problem from point 1 above:

```dart
EditableTextContextMenuButtonItemsBuilder(
  editableTextState: editableTextState,
  builder: (BuildContext context, List<AdaptiveTextSelectionToolbarButton> buttons) {
    // This would allow me to take a look at, say, buttons.first.label and modify the list
    // based on that.  However, remember from point number 1 above that the buttons
    // need to know their place in the list.  So I can't just remove the Paste button from
    // the list, I'd also have to rebuild every other button widget as well!
    return AdaptiveTextSelectionToolbar(
      primaryAnchor: primaryAnchor,
      secondaryAnchor: secondaryAnchor,
      children: buttons,
    );
  },
)
```

## Conclusion

It seems impractical to fully make ContextMenuButtonItem into a widget here unless I'm missing another approach.  However, in my refactoring I have moved lots of buttonItem logic into named constructors and generally hidden them away unless users need them.  By default, widgets like AdaptiveTextSelectionToolbar work on a list of `children` widgets.

File: packages/flutter/lib/src/material/default_text_selection_toolbar.dart [hunk 28]
```diff
@@ -0,0 +1,198 @@
...
+
+  /// {@macro flutter.cupertino.DefaultCupertinoTextSelectionToolbar.primaryAnchor}
+  final Offset primaryAnchor;
+
+  /// {@macro flutter.cupertino.DefaultCupertinoTextSelectionToolbar.secondaryAnchor}
+  final Offset? secondaryAnchor;
+
+  /// The information needed to create each child button of the menu.
+  ///
+  /// If provided, [children] cannot also be provided.
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/default_text_selection_toolbar.dart]: I left a long comment below about making ContextMenuButtonItem a widget, which I believe is not feasible. https://github.com/flutter/flutter/pull/107193#issuecomment-1221245442

However, I've separated all of these overlapping ways of providing the buttons by putting them into separate named constructors with tight requirements.  By default, this widget now takes a list of Widget children.  Only if a user wants ContextMenuButtonItems then they can use the `.buttonItems` constructor.

File: packages/flutter/lib/src/material/default_text_selection_toolbar.dart [hunk 29]
```diff
@@ -0,0 +1,198 @@
...
+         'No need for both buttonItems and children, use one or the other, or neither.',
+       ),
+       assert(
+         !(buttonItems == null && children == null && editableTextState == null),
+         'If not providing buttonItems or children, provide editableTextState to generate them.',
+       );
+
+  /// If provided, used to generate the buttons.
+  ///
+  /// Otherwise, manually pass in [buttonItems] or [children].
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/default_text_selection_toolbar.dart]: Mentioned above, this is now separate named constructors.  To me it seems cleaner than a bunch of totally separate widgets but let me know what you think.  I definitely like it a lot more than my original approach here.

File: packages/flutter/lib/src/cupertino/desktop_text_selection_toolbar.dart [hunk 30]
```diff
@@ -0,0 +1,115 @@
...
+// Minimal padding from all edges of the selection toolbar to all edges of the
+// screen.
+const double _kToolbarScreenPadding = 8.0;
+
+// These values were measured from a screenshot of TextEdit on MacOS 10.15.7 on
+// a Macbook Pro.
+const double _kToolbarWidth = 222.0;
+const Radius _kToolbarBorderRadius = Radius.circular(4.0);
+
+// These values were measured from a screenshot of TextEdit on MacOS 10.16 on a
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/desktop_text_selection_toolbar.dart:18]: This PR just made this class public and moved it to its own file.  The comments were probably originally added in separate PRs over time, so I was running different versions of macOS at each time.  So they should be accurate!

I'll update the capitalization here and everywhere else I see it.

File: packages/flutter/lib/src/material/desktop_text_selection_toolbar.dart [hunk 31]
```diff
@@ -0,0 +1,91 @@
...
+class DesktopTextSelectionToolbar extends StatelessWidget {
+  /// Creates an instance of _DesktopTextSelectionToolbar.
+  const DesktopTextSelectionToolbar({
+    super.key,
+    required this.anchor,
+    required this.children,
+  }) : assert(children.length > 0);
+
+  /// {@template flutter.material.DesktopTextSelectionToolbar.anchor}
+  /// The point at which the toolbar will attempt to position itself as closely
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/desktop_text_selection_toolbar.dart:36]: 👍  I feel like the auto suggestions in Google Docs always tell me things like this too...

File: packages/flutter/lib/src/material/desktop_text_selection_toolbar.dart [hunk 32]
```diff
@@ -0,0 +1,91 @@
...
+const double _kToolbarScreenPadding = 8.0;
+const double _kToolbarWidth = 222.0;
+
+/// A Material-style desktop text selection toolbar.
+///
+/// Typically displays buttons for text manipulation, e.g. copying and pasting
+/// text.
+///
+/// Tries to position itself as closely as possible to [anchor] while remaining
+/// fully on-screen.
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/desktop_text_selection_toolbar.dart:19]: Good point!

File: packages/flutter/lib/src/material/scaffold.dart [hunk 33]
```diff
@@ -7,6 +7,7 @@ import 'dart:collection';
 import 'dart:math' as math;
 import 'dart:ui' show lerpDouble;
 
+import 'package:flutter/cupertino.dart';
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/scaffold.dart:10]: Good catch 😁 . I'm going to undo that line I deleted below too.

File: packages/flutter/lib/src/material/selection_area.dart [hunk 34]
```diff
@@ -45,11 +47,40 @@ class SelectionArea extends StatefulWidget {
   /// If it is null, the platform specific selection control is used.
   final TextSelectionControls? selectionControls;
 
+  /// {@macro flutter.widgets.EditableText.contextMenuBuilder}
+  ///
+  /// If not provided, will build a default menu based on the platform.
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/selection_area.dart:70]: Good call, I have probably made this mistake before, I should be more specific about this.

File: packages/flutter/lib/src/material/text_field.dart [hunk 35]
```diff
@@ -365,31 +371,7 @@ class TextField extends StatefulWidget {
        assert(clipBehavior != null),
        assert(enableIMEPersonalizedLearning != null),
        keyboardType = keyboardType ?? (maxLines == 1 ? TextInputType.text : TextInputType.multiline),
-       enableInteractiveSelection = enableInteractiveSelection ?? (!readOnly || !obscureText),
-       toolbarOptions = toolbarOptions ??
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/text_field.dart:376]: I've moved this logic here: https://github.com/flutter/flutter/pull/107193/files#diff-b4ecc433d218176fa9f2815f6b88ce0eb901452d07aa353e6cf44e8e6f4aa5d8R106

ToolbarOptions should continue to work as it did before.  I removed this default here so that I can distinguish between a user that didn't pass anything here and someone that is explicitly using toolbarOptions.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 10 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1890]: This is the widgets library so I can't use Theme, right?

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 11 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart:467]: Same comment above about the widgets library accessing Theme.

File: packages/flutter/lib/src/cupertino/default_text_selection_toolbar.dart (hunk 12 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/default_text_selection_toolbar.dart]: I've been putting al macOS stuff into the Cupertino library and calling it Cupertino, but maybe that's not accurate.  Should we come up with another name that encompasses both iOS and macOS?

File: packages/flutter/lib/src/cupertino/default_text_selection_toolbar.dart (hunk 13 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/default_text_selection_toolbar.dart]: I reworded it, thanks.

File: packages/flutter/lib/src/cupertino/text_selection_toolbar_buttons_builder.dart (hunk 16 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection_toolbar_buttons_builder.dart:28]: That's right.  I'll clarify.

File: examples/api/lib/material/context_menu/context_menu_controller.0.dart [hunk 36]
```diff
@@ -0,0 +1,154 @@
...
+        ),
+      ),
+    );
+  }
+}
+
+/// Shows and hides the context menu based on user gestures.
+///
+/// By default, shows the menu on right clicks and long presses.
+class _ContextMenuRegion extends StatefulWidget {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply examples/api/lib/material/context_menu/context_menu_controller.0.dart:70]: I originally had it as a public widget but decided to put it here as an example instead since it's so trivial.  Maybe I'll consider making it public if anyone asks for it in the future, or what do you think?

File: packages/flutter/lib/src/cupertino/text_field.dart (hunk 19 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_field.dart]: This will be much simpler once the deprecations go away, I think it's the toolbarOptions stuff that seems so verbose here.

File: packages/flutter/lib/src/cupertino/text_field.dart (hunk 20 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_field.dart:774]: I agree, but it's my understanding that we have to do this when we're totally within the Cupertino library and don't have access to Material.  This is the pattern that I've followed for other stuff like this in the past.

It is possible for users to pass in an adaptive context menu to their own CupertinoTextField if they are using Material too, though.

File: packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart (hunk 21 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart:102]: No, see the section in my PR description called "New stuff immediately deprecated".  This was created to keep both the old and new stuff working while they both coexist.  Once the deprecations are removed this should go away too.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 37]
```diff
@@ -1505,6 +1520,36 @@ class EditableText extends StatefulWidget {
   /// {@macro flutter.services.TextInputConfiguration.enableIMEPersonalizedLearning}
   final bool enableIMEPersonalizedLearning;
 
+  /// {@template flutter.widgets.EditableText.contextMenuBuilder}
+  /// Builds the text selection toolbar when requested by the user.
+  ///
+  /// {@tool dartpad}
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:1587]: I tried it and the blue boxes showed up! 👍

File: examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart (hunk 23 above)
Comment (justinmc) [reply examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart:33]: True... Is there anything I can do about it?  It would be way overkill to try to create a mixin that doesn't include the BuildContext or something.

File: packages/flutter/lib/src/widgets/context_menu_controller.dart [hunk 38]
```diff
@@ -0,0 +1,114 @@
...
+
+import 'basic.dart';
+import 'context_menu_button_item.dart';
+import 'editable_text.dart';
+import 'framework.dart';
+import 'inherited_theme.dart';
+import 'navigator.dart';
+import 'overlay.dart';
+
+/// Builds a context menu at [primaryAnchor] if possible, otherwise at
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart:13]: I never realized that was a rule, thank you!

File: packages/flutter/lib/src/widgets/context_menu_controller.dart [hunk 39]
```diff
@@ -0,0 +1,114 @@
...
+/// A function that builds a widget to use as the text selection toolbar for
+/// [EditableText].
+///
+/// See also:
+///
+///  * [ContextMenuBuilder], which is the generic type for any context menu
+///    builder, not just for the editable text selection toolbar.
+///  * [SelectableRegionToolbarBuilder], which is the builder for
+///    [SelectableRegion].
+typedef EditableTextToolbarBuilder = Widget Function(
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart:42]: I'll give them all names, good catch.

File: packages/flutter/lib/src/widgets/context_menu_controller.dart [hunk 40]
```diff
@@ -0,0 +1,114 @@
...
+  BuildContext,
+  EditableTextState,
+  Offset,
+  [Offset?]
+);
+
+/// Builds and manages a context menu at a given location.
+///
+/// There can only ever be one context menu shown at a given time.
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart:51]: In the entire app, will clarify 👍

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 41]
```diff
@@ -1931,6 +1994,16 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     );
 
     if (cause == SelectionChangedCause.toolbar) {
+      switch (defaultTargetPlatform) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:2063]: I can't remember why I didn't make this separate in the first place...  If anyone else feels strongly I'll remove it and open a new PR.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 42]
```diff
@@ -2629,6 +2705,18 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
       selectionDelegate: this,
       dragStartBehavior: widget.dragStartBehavior,
       onSelectionHandleTapped: widget.onSelectionHandleTapped,
+      contextMenuBuilder: widget.contextMenuBuilder == null ? null : (
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:2811]: I agree, thanks.

File: packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart (hunk 24 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart:108]: I like that, thanks.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 25 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart:1916]: Thanks, I'm looking forward to straightening that out in Flutter.  I keep running into it.

File: examples/api/lib/material/context_menu/context_menu_controller.0.dart (hunk 22 above)
Comment (justinmc) [reply examples/api/lib/material/context_menu/context_menu_controller.0.dart:134]: I think I'm going to take a closer look at ContextMenuController.  The whole idea of having this be global scares me, I was hoping someone would tell me it's totally forbidden in Flutter or something.  It's also true that `isShown` doesn't necessarily tell you that *your* menu is shown.  Maybe I can solve all of these problems by allowing this to be instantiated and refactoring a bit somehow.

File: packages/flutter/lib/src/material/adaptive_text_selection_toolbar.dart [hunk 43]
```diff
@@ -0,0 +1,312 @@
...
+  ///
+  /// {@macro flutter.material.AdaptiveTextSelectionToolbar.constructor.selectableRegion}
+  ///
+  /// {@macro flutter.material.AdaptiveTextSelectionToolbar.constructor.buttonItems}
+  ///
+  /// See also:
+  ///
+  ///  * [EditableTextContextMenuButtonItemsBuilder], which builds the default
+  ///    [ContextMenuButtonItem]s for [EditableText] on the platform.
+  const AdaptiveTextSelectionToolbar.editableText({
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/adaptive_text_selection_toolbar.dart:81]: Why grouping them in AdaptiveTextSelectionToolbar. I looked at the build, they are their own ContextMenuButtonItemsBuilder anyway

**Comment by masus04** [comment]
Does this PR also allow `ContextMenu`s to be used on web platforms?
It appears the current implementation of `TextField.toolbarOptions` is simply ignored on the web.

**Comment by justinmc** [comment]
@masus04 This does not add full support for context menus on the web, but it gets us closer.  We need a way to prevent the browser from showing its context menu using Dart, which is covered by https://github.com/flutter/flutter/issues/78671.  Once that issue is resolved, I think it would be pretty straightforward to get this to work on web.

File: packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart [hunk 44]
```diff
@@ -0,0 +1,296 @@
...
+    return widget.editableTextState.pasteText(SelectionChangedCause.toolbar);
+  }
+
+  void _handleSelectAll() {
+    return widget.editableTextState.selectAll(SelectionChangedCause.toolbar);
+  }
+
+  @override
+  Widget build(BuildContext context) {
+    return _ClipboardStatusBuilder(
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart:176]: It can also change even if the system clipboard changes outside of the scope of EditableText or even Flutter, like copying some text in another app.

[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart:176]: No I meant _ClipboardStatusBuilder seems to be only useful to handle where the instance of widget.editableTextState.clipboardStatus are different from build to build. but it would only be different if the instance of editableTextState are different. so logic can be handled in _EditableTextContextMenuButtonItemsBuilderState.didUpdateWidget

I imagine you can just listen to widget.editableTextState.clipboardStatus directly in _EditableTextContextMenuButtonItemsBuilderState and update the listener in didUpdateWidget if the `widget.editableTextState != old.editableTextState`

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 45]
```diff
@@ -1776,3 +1868,113 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
...
+
+  final TargetPlatform? _targetPlatform;
+
+  /// The platform to base the button items on.
+  TargetPlatform get targetPlatform => _targetPlatform ?? defaultTargetPlatform;
+
+  /// Returns true if the given [SelectableRegionState]
+  /// supports copy.
+  static bool canCopy(SelectableRegionState state) {
+    final String? selectedText = state._selectionDelegate.getSelectedContent()?.plainText;
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart:1945]: Good call, thanks!

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 46]
```diff
@@ -814,9 +890,17 @@ class _SelectableRegionState extends State<SelectableRegion> with TextSelectionD
 
   // [TextSelectionDelegate] overrides.
 
+  @Deprecated(
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart:911]: Are you asking if we should remove the deprecation and keep cutEnabled, or if we should remove cutEnabled right now?

I've deprecated all of these methods on TextSelectionDelegate in favor of handling the context menus in separate widgets.  Now the logic for when these buttons are enabled is in SelectableRegionContextMenuButtonItemsBuilder.  For EditableText it's in EditableTextContextMenuButtonItemsBuilder.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 47]
```diff
@@ -852,6 +936,10 @@ class _SelectableRegionState extends State<SelectableRegion> with TextSelectionD
   @override
   void bringIntoView(TextPosition position) {/* SelectableRegion must be in view at this point. */}
 
+  @Deprecated(
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart:958]: Looks like we're getting there actually...  I've created an issue to track this (https://github.com/flutter/flutter/issues/111213) and I'm going to link it in your TODO.

File: packages/flutter/lib/src/material/adaptive_text_selection_toolbar.dart (hunk 43 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/adaptive_text_selection_toolbar.dart]: The idea was just user friendliness, but now I'm thinking you might be right and they should just be separate widgets.  I've split them out, let me know what you think.

**Comment by justinmc** [comment]
I've refactored ContextMenuController so that it is no longer a singleton.

Previously, all methods were static and everything operated globally on a single context menu.  This was nice to enforce that there is only one context menu, but it meant that you couldn't know if a specific context menu was shown at any time.

Now, you show it by creating an instance, and you can use that instance to see `isShown` or to `remove` that specific instance without affecting others.  I also added `onRemove` to be notified if an instance is removed by someone else.  There is still only one static OverlayEntry under the hood, so it still prevents showing multiple context menus at the same time.

Example:

```dart
myContextMenuController = ContextMenuController(
  context: context,
  onRemove: () {
    myContextMenuController = null;
  },
  contextMenuBuilder: (BuildContext context) {
    return MyContextMenu();
  },
);
```

File: packages/flutter/lib/src/widgets/context_menu_controller.dart [hunk 48]
```diff
@@ -0,0 +1,115 @@
...
+  ///
+  /// You need to call this function if the output of [contextMenuBuilder] has
+  /// changed.
+  ///
+  /// If the context menu is not currently shown, does nothing.
+  ///
+  /// See also:
+  ///
+  ///  * [OverlayEntry.markNeedsBuild]
+  static void markNeedsBuild() {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart]: I've now refactored ContextMenuController to not be a singleton, so it's possible to know if a specific context menu is shown or not.  See https://github.com/flutter/flutter/pull/107193#issuecomment-1241333434

File: packages/flutter/lib/src/widgets/context_menu_controller.dart (hunk 27 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart:85]: I've refactored ContextMenuController to not be a singleton, and now you can just do `controller.isShown`.  See https://github.com/flutter/flutter/pull/107193#issuecomment-1241333434

File: examples/api/lib/material/context_menu/context_menu_controller.0.dart (hunk 22 above)
Comment (justinmc) [reply examples/api/lib/material/context_menu/context_menu_controller.0.dart]: I've refactored ContextMenuController to not be a singleton, see https://github.com/flutter/flutter/pull/107193#issuecomment-1241333434

File: packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart (hunk 44 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart:176]: Ah I see.  Looks like it's probably cleaner that way, I'll change it 👍

**Comment by justinmc** [comment]
Ready for re-review from everyone, thanks!  Notice the switch away from a singleton ContextMenuController ([explanation above](https://github.com/flutter/flutter/pull/107193#issuecomment-1241333434)).

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 47 above)
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:959]: Is it a lot of work to migrate? Since this class is previously private and this pr makes it public, should we do it as part of this pr?

[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart]: I was worried it was going to be, but I tried it and I think it worked out super nicely: https://github.com/flutter/flutter/pull/107193/commits/4cee48b3d86508e0c7cc0c2c74061d4cd13d0eee

So the TextSelectionDelegate parameter of SelectionOverlay is now deprecated, which is great, and TextSelectionDelegate is removed from SelectableRegion.  Thanks for calling this out.

[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart:972]: Actually I spoke too soon.  In order to keep the old way of doing things working, I need to keep TextSelectionDelegate there during the deprecation period.  I reverted that commit but kept the deprecations.  After we remove the deprecations, it will be really easy to remove TextSelectionDelegate for good.

File: examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart (hunk 23 above)
Comment (justinmc) [reply examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart:33]: Thanks for this comment, I spent a bunch of time refactoring to decouple from EditableText.  I definitely want this context menu system to be easily usable by people that are building custom editors etc. and not using EditableText.

  * I moved from builder widgets to functions where possible.
    - getEditableButtonItems, etc. instead of a StatelessWidget with a builder.
  * getEditableButtonItems just takes the required parameters directly, not EditableTextState.
  * getEditableTextButtonItems exists as a convenience and it calls out to getEditableButtonItems.
  * canCut etc. are back to being the responsibility of EditableText.
  * This all applies to SelectableRegion as well (getSelectableButtonItems doesn't depend on SelectableRegionState).

I didn't use TextSelectionDelegate because it seemed to be bigger than what I needed.  I think it will be easier for people not using EditableText/SelectableRegion to just pass in the parameters directly.

File: packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart [hunk 49]
```diff
@@ -0,0 +1,248 @@
...
+  /// toolbar.
+  final EditableTextState editableTextState;
+
+  final TargetPlatform? _targetPlatform;
+
+  /// The platform to base the button items on.
+  TargetPlatform get targetPlatform => _targetPlatform ?? defaultTargetPlatform;
+
+  /// Returns true if the given [EditableTextState] supports cut.
+  static bool canCut(EditableTextState editableTextState) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text_context_menu_button_items_builder.dart]: Moved to EditableTextState, thanks.

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart [hunk 50]
```diff
@@ -0,0 +1,375 @@
...
+  }) : buttonItems = null,
+       _targetPlatform = targetPlatform;
+
+  /// Create an instance of [CupertinoAdaptiveTextSelectionToolbar] whose
+  /// children will be built from the given [buttonItems].
+  ///
+  /// See also:
+  ///
+  /// {@template flutter.cupertino.CupertinoAdaptiveTextSelectionToolbar.new}
+  /// * [CupertinoAdaptiveTextSelectionToolbar.new], which takes the children
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:77]: Is `.new` referring to the default constructor?

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart [hunk 51]
```diff
@@ -0,0 +1,375 @@
...
+    final List<Widget> resultChildren = children != null
+        ? children!
+        : getAdaptiveButtons(context, buttonItems!).toList();
+
+    return _AdaptiveTextSelectionToolbarFromChildren(
+      primaryAnchor: primaryAnchor,
+      secondaryAnchor: secondaryAnchor,
+      targetPlatform: targetPlatform,
+      children: resultChildren,
+      /*
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:312]: Just pointing this out, in case you forgot these comments.

File: packages/flutter/lib/src/cupertino/text_field.dart (hunk 20 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/cupertino/text_field.dart:775]: I agree, that the user would expect to see the Android toolbar on an Android device regardless of the TextField used, maybe there could be an example on how to pass a Material text selection toolbar to a CupertinoTextField for these cases?

**Comment by Renzo-Olivares** [comment]
Is there a way to add dividers in between toolbar items? I tried something around these lines, but was wondering if there is another way.

```dart
        child: TextField(
          contextMenuBuilder: (BuildContext context, EditableTextState state, Offset primaryAnchor, [Offset? secondaryAnchor]) {
            return AdaptiveTextSelectionToolbar(
              primaryAnchor: primaryAnchor,
              secondaryAnchor: secondaryAnchor,
              children: getEditableTextButtonItems(state)
                  .map((ContextMenuButtonItem buttonItem) {
                return Column(
                  children: [
                    TextSelectionToolbarTextButton(
                      onPressed: buttonItem.onPressed,
                      padding: const EdgeInsets.all(10.0),
                      child: SizedBox(
                        width: 200.0,
                        child: Text(
                          AdaptiveTextSelectionToolbar.getButtonLabel(context, buttonItem),
                        ),
                      ),
                    ),
                    Divider(color: Colors.black,)
                  ],
                );
              }).toList() as List<Widget>,
            );
          },
        ),
```

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart [hunk 52]
```diff
@@ -0,0 +1,375 @@
...
+          );
+        });
+    }
+  }
+
+  @override
+  Widget build(BuildContext context) {
+    // If there aren't any buttons to build, build an empty toolbar.
+    if ((children != null && children!.isEmpty)
+      || (buttonItems != null && buttonItems!.isEmpty)) {
```
Comment (tgucio) [inline packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:299]: Nit: turn this into `if ((children?.isEmpty ?? false) || (buttonItems?.isEmpty ?? false))` (I think there was a lint for that).

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart [hunk 53]
```diff
@@ -0,0 +1,375 @@
...
+      return const SizedBox(width: 0.0, height: 0.0);
```
Comment (tgucio) [inline packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:300]: SizedBox.shrink() here and in other 5 `SizedBox(width: 0.0, height: 0.0)` occurrences.

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart [hunk 54]
```diff
@@ -0,0 +1,375 @@
...
+  ///   the default Cupertino children for a [SelectableRegion].
+  /// {@endtemplate}
+  const CupertinoAdaptiveTextSelectionToolbar({
+    super.key,
+    required this.children,
+    required this.primaryAnchor,
+    this.secondaryAnchor,
+    final TargetPlatform? targetPlatform,
+  }) : buttonItems = null,
+       _targetPlatform = targetPlatform;
```
Comment (tgucio) [inline packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:69]: Out of curiosity, is there a reason to provide `targetPlatform` as an explicit parameter instead of using `Theme.of(context).targetPlatform`? Even if there's no `Theme` in the context (e.g. non-Material app?), it should default to `ThemeData.fallback`.

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart [hunk 55]
```diff
@@ -0,0 +1,375 @@
...
+  /// {@macro flutter.cupertino.CupertinoAdaptiveTextSelectionToolbar.new}
+  /// {@macro flutter.cupertino.CupertinoAdaptiveTextSelectionToolbar.buttonItems}
+  /// {@macro flutter.cupertino.CupertinoAdaptiveTextSelectionToolbar.editableText}
+  /// {@macro flutter.cupertino.CupertinoAdaptiveTextSelectionToolbar.selectable}
+  /// {@macro flutter.cupertino.CupertinoAdaptiveTextSelectionToolbar.selectableRegion}
+  CupertinoAdaptiveTextSelectionToolbar.editable({
+    super.key,
+    required bool readOnly,
+    required ClipboardStatus clipboardStatus,
+    required bool copyEnabled,
```
Comment (tgucio) [inline packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:109]: Would it make sense to use nullable callbacks as indicator whether each functionality is enabled and remove the four `Enabled*` parameters?
```
    required VoidCallback? onCopy,
    required VoidCallback? onCut,
    required VoidCallback? onPaste,
    required VoidCallback? onSelectAll,
```
Then either check for `onCut != null` or maybe define getters like:
```
  bool get _isCutEnabled => onCut != null
```

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart (hunk 50 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:77]: Yes, I didn't know that and had to look it up when I wrote these docs, but it's actually built in to dartdoc: https://dart.dev/guides/language/effective-dart/documentation#do-use-square-brackets-in-doc-comments-to-refer-to-in-scope-identifiers

File: examples/api/lib/material/context_menu/context_menu_controller.0.dart [hunk 56]
```diff
@@ -0,0 +1,155 @@
...
+      ),
+    );
+  }
+
+  @override
+  Widget build(BuildContext context) {
+    return MaterialApp(
+      home: Scaffold(
+        appBar: AppBar(
+          title: const Text('Context menu in SelectionArea'),
```
[the remark this answers is not in the document]
Comment (justinmc) [reply examples/api/lib/material/context_menu/context_menu_controller.0.dart:31]: Good catch, I think I copied this from the SelectionArea example.

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart (hunk 51 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:312]: Yes I did, thank you!

**Comment by justinmc** [comment]
@Renzo-Olivares About dividers, are you talking about the iOS dividers [here](https://github.com/flutter/flutter/pull/107193/files#diff-b35010ea66b8fe0d3e4792bb7eed205ecb04d5d44d5f36747d771c0a1a01ee34R294) or some other ones?  There might be problems with not adding a divider after the last button if I do it in-line like in your code.  Anyway I think any code related to dividers was added before this PR and I just moved it, though I'm happy to clean that up if possible here or in a new PR afterwards.

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart (hunk 52 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:299]: Thanks!  Yeah there should be a lint for that at least...

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart (hunk 54 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:69]: Yes the reason is to keep Cupertino free of stuff from the Material library.  You're right though, if I just remove this parameter everywhere the result is the same as using defaultTargetPlatform.  I'll do that.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 57]
```diff
@@ -516,7 +555,7 @@ class _SelectableRegionState extends State<SelectableRegion> with TextSelectionD
   late Offset _selectionStartHandleDragPosition;
   late Offset _selectionEndHandleDragPosition;
 
-  late List<TextSelectionPoint> points;
+  late List<TextSelectionPoint> _points;
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:558]: This is probably a mistake I made previously, This can be function variable instead.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 46 above)
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:939]: Ah ok.this is to support people who still pass in the materialTextSelectionControls?

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 47 above)
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:996]: gotcha

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 58]
```diff
@@ -332,10 +370,18 @@ class TextSelectionOverlay {
...
+  /// This context must have an [Overlay] as an ancestor because this object
+  /// will display the text selection handles in that [Overlay].
+  /// {@endtemplate}
+  final BuildContext context;
+
   /// Controls the fade-in and fade-out animations for the toolbar and handles.
   @Deprecated(
     'Use `SelectionOverlay.fadeDuration` instead. '
-    'This feature was deprecated after v2.12.0-4.1.pre.'
+    'This feature was deprecated after v3.3.0-0.5.pre.'
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/text_selection.dart:384]: I remember this was deprecated a while back, why the version change?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 59]
```diff
@@ -837,7 +970,7 @@ class SelectionOverlay {
   /// [MagnifierController.shown].
   /// {@endtemplate}
   void showMagnifier(MagnifierOverlayInfoBearer initialInfoBearer) {
-    if (_toolbar != null) {
+    if (_toolbar != null || (_contextMenuController?.isShown ?? false)) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/text_selection.dart:973]: may be easier to be a getter

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart (hunk 55 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:105]: Yeah I like that better, thanks 👍

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 57 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart:558]: Oh right, I'll do that.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 58 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart:384]: Whoops, this must have been my overzealous find and replace when I changed the deprecated version number in the deprecations that I made in this PR.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 46 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart:938]: Yeah exactly, that's why I didn't just remove all of this right now. Once these deprecations expire we can remove a ton of this stuff.

File: packages/flutter/lib/src/widgets/context_menu_button_item.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/context_menu_button_item.dart:38]: Leaving a link to my answer to this question in order to make this easier to follow: https://github.com/flutter/flutter/pull/107193#issuecomment-1221245442

File: examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart (hunk 23 above)
Comment (justinmc) [reply examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart]: @chunhtai I think you're right and that's better.  I've updated the PR to pass button items instead of states.

Originally I didn't do this because I didn't want to generate the button items if users didn't want to use them, but I think the work required is very minimal, and users likely do want to use them anyway.

This also means that SelectableRegionState can remain private.  I'll keep an eye out in case people want to access some of that state when they generate their context menus but I think the selection will be enough.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 60]
```diff
@@ -405,7 +450,60 @@ class TextSelectionOverlay {
...
+      return;
+    }
+
+    if (contextMenuBuilder == null) {
+      return;
+    }
+
+    // If right clicking on desktop, use the right click position as the only
+    // anchor.
+    final RenderBox renderBox = context.findRenderObject()! as RenderBox;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:465]: Since this is a public method, assert the context is not disposed?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 61]
```diff
@@ -728,7 +831,33 @@ class TextSelectionOverlay {
...
 
-  void _handleAnyDragEnd(DragEndDetails details) => _selectionOverlay.hideMagnifier(shouldShowToolbar: !_selection.isCollapsed);
+  void _handleAnyDragEnd(DragEndDetails details) {
+    if (selectionControls is! TextSelectionHandleControls) {
+      _selectionOverlay.hideMagnifier(
+        shouldShowToolbar: !_selection.isCollapsed,
+      );
+      return;
+    }
+    final RenderBox renderBox = context.findRenderObject()! as RenderBox;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:841]: The context may have already been unmounted since this is on a different OverlayEntry.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 62]
```diff
@@ -867,11 +1000,20 @@ class SelectionOverlay {
...
   /// {@template flutter.widgets.SelectionOverlay.hideMagnifier}
   /// Hide the current magnifier, optionally immediately showing
-  /// the toolbar.
+  /// the toolbar provided by `contextMenuBuilder`.
   ///
   /// This does nothing if there is no magnifier.
   /// {@endtemplate}
-  void hideMagnifier({required bool shouldShowToolbar}) {
+  void hideMagnifier({
+    WidgetBuilder? contextMenuBuilder,
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:1008]: nit: It seems a bit strange to hard-tie these 2 things together. If the developer wants to show the context menu immediately after hiding the magnifier, they should call `showToolbar`?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 63]
```diff
@@ -1091,6 +1243,50 @@ class SelectionOverlay {
...
+  // Set when there is a visible context menu, null otherwise.
+  ContextMenuController? _contextMenuController;
+
+  // When the context menu is removed, clean up the dead instance of
+  // ContextMenuController.
+  void _onRemoveContextMenu() {
+    _contextMenuController = null;
+  }
+
+  bool get _contextMenuControllerIsShown => (_contextMenuController?.isShown) ?? false;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:1255]: nit: the parentheses are probably not needed?

File: packages/flutter/lib/src/widgets/context_menu_controller.dart (hunk 27 above)
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart:73]: Can we give each menu a focus node instead of having a global registry? Then each menu will be notified when it's no longer in the path of the primary focus and can optionally dismiss itself. Not sure if how this applies to SeletableRegion, but SelectableRegion needs a focus node to do shortcuts anyways?

[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart:73]: @LongCatIsLooong Do you mean to get rid of the global removeAny method?  Let me know if this is what you mean: https://github.com/justinmc/flutter/commit/a483fbb9fdf9d7b23668fe52c802af019a4bd4ef

I didn't need to touch SelectableRegion because it uses `.remove` directly.  Maybe it's a bit strange using a FocusNode to remove the menu in my context_menu_controller.0 example.  Not sure if this is exactly what you mean though.

File: examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart [hunk 64]
```diff
@@ -0,0 +1,65 @@
...
+        appBar: AppBar(
+          title: const Text('Custom button appearance'),
+        ),
+        body: Center(
+          child: Column(
+            children: <Widget>[
+              const SizedBox(height: 20.0),
+              TextField(
+                controller: _controller,
+                contextMenuBuilder: (BuildContext context, List<ContextMenuButtonItem> buttonItems, Offset primaryAnchor, [Offset? secondaryAnchor]) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart:33]: I think this goes back to [this discussion above](https://github.com/flutter/flutter/pull/107193#discussion_r933784798).  Do we want to pass simple parameters that are used to build the default menu (list of button items and the anchors), or something comprehensive that gives users more control?

I was leaning towards the "simple" solution of late, but I was assuming that users could look up the EditableTextState if they wanted to.  That's not true anymore though, is it?  Maybe I should just pass BuildContext and EditableTextState, then provide easy ways to get the buttonItems and anchors if needed.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 62 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart:1008]: Good call, I should have caught this in the loupe code review.  I'll change it.

File: examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart (hunk 64 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart:33]: I went down a rabbit hole trying to refactor this to pass only EditableTextState ([wip commit](https://github.com/flutter/flutter/commit/b6808d2fa07bb3bd52fc9772d264899915bc74a4)), but I think we should keep the parameters as-is for now, if I can convince you to agree with me.  The two anchors are the simplest representation of the menu position, they existed as part of the toolbar API before this PR, and they also work really well for precise positioning based on right click.  I'd like to make this more customizable for users, but this isn't going to be both clean and comprehensive without a lot of refactoring because we don't have good ways to get/expose metrics about this kind of stuff right now.

I propose we release the simple parameters as-is, and then we see how users react and what they are trying to build with this (maybe they want to hang the menu off the start/end of the selection, maybe they want to point to specific word within the selection, etc.).  Once we know what users want and we know that it's worthwhile to make this more customizable, then we can make that possible in a clean way in a separate PR.

File: packages/flutter/lib/src/widgets/adaptive_text_selection_toolbar.dart [hunk 65]
```diff
@@ -0,0 +1,101 @@
...
+/// See also:
+///
+/// * [getEditableButtonItems], which performs a similar role but for content
+///   that is both selectable and editable.
+/// * [AdaptiveTextSelectionToolbar], which builds the toolbar itself, and can
+///   take a list of [ContextMenuButtonItem]s with
+///   [AdaptiveTextSelectionToolbar.buttonItems].
+/// * [AdaptiveTextSelectionToolbar.getAdaptiveButtons], which builds the button
+///   Widgets for the current platform given [ContextMenuButtonItem]s.
+List<ContextMenuButtonItem> getSelectableButtonItems({
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/adaptive_text_selection_toolbar.dart]: Good call.  I moved this to SelectableRegion and the editable one to EditableText.

**Comment by justinmc** [comment]
I've refactored so that builders take EditableTextState or SelectableTextState instead of buttonItems and anchors.  This stems from a [discussion](https://github.com/flutter/flutter/pull/107193#discussion_r980529444) above with @LongCatIsLooong and partially conflicts with some [discussion](https://github.com/flutter/flutter/pull/107193#discussion_r978026488) above with @chunhtai. Here are some details summarizing the change.

### What
Here's an example of adding a "Print" button to a TextField's context menu.

Before:

```dart
TextField(
  contextMenuBuilder: (BuildContext context, List<ContextMenuButtonItems> buttonItems, Offset primaryAnchor, [Offset? secondaryAnchor]) {
    return AdaptiveTextSelectionToolbar(
      buttonItems: <ContextMenuButtonItem>[
        ...buttonItems,
        ContextMenuButtonItem(
          label: 'Print',
          onPressed: print(),
        ),
      ],
      primaryAnchor: primaryAnchor,
      secondaryAnchor: secondaryAnchor,
    );
  },
)
```

After:

```dart
TextField(
  contextMenuBuilder: (BuildContext context, EditableTextState editableTextState) {
    return AdaptiveTextSelectionToolbar(
      buttonItems: <ContextMenuButtonItem>[
        ...editableTextState.contextMenuButtonItems,
        ContextMenuButtonItem(
          label: 'Print',
          onPressed: print(),
        ),
      ],
      anchors: AdaptiveTextSelectionToolbar.getAnchorsEditable(editableTextState),
    );
  },
)
```

### Why
This approach decouples us from the primary/secondary anchor approach, which is specific to our built-in context menus and not to context menus generally.  I think it better follows Flutter's principal of just accepting generic widgets everywhere.

In the future, we can update contextMenuBuilder to take a generic TextLayoutMetrics object, further decoupling us from EditableTextState and SelectableRegionState.

### Changes

### Context menu builders
Previously these passed buttonItems and anchor Offsets.  Now they pass EditableTextState or SelectableRegionState when used for those widgets specifically, and otherwise they're just a generic WidgetBuilder.

### AdaptiveTextSelectionToolbar constructors
This and CupertinoTextSelectionToolbar now have `.editableText` and `.selectableRegion` constructors again.  They handle the logic of building a menu specifically for these widgets, since contextMenuBuilder is now generic.

The logic of calculating the anchors has also been moved from widgets/text_selection.dart to AdaptiveTextSelectionToolbar, since the logic is specific to that widget.

The logic for generating buttonItems is still on EditableTextState and SelectableRegionState and has been made public via `contextMenuButtonItems` getters, which AdaptiveTextSelectionToolbar accesses.  EditableTextState and SelectableRegionState still know about context menus and decide what their default buttons are.

### Anchors
Where we previously took two offsets, `Offset primaryAnchor, [Offset? secondaryAnchor]`, I have now encapsulated this in a class, TextSelectionToolbarAnchors.  This is mainly done because Dart doesn't have tuples yet and it's the easiest way to allow passing both anchors and no duplicating overlapping calculations for each anchor in two separate calls.

### SelectableRegionState
This class had to be made public again.  I [discussed](https://github.com/flutter/flutter/pull/107193#discussion_r978026488) this above earlier in this PR's life but later made it private again, and now we're back to public.  It makes sense public, similar to EditableTextState, while we don't have TextLayoutMetrics and we're not passing specific buttonItems and anchors to the contextMenuBuilder.

Also, `selectionEndpoints` has been exposed publicly on this class in order to allow AdaptiveTextSelectionToolbar to calculate the anchors for it.

### Reviewing
All changes for this feature are tagged `(pass editable text state)`.  You can view all changes at once with: `git diff cf9e31b0dc9f4e2c7224d55b8bd17e3bd026a96e^ 2a2438c6fe1af8a1213be4d8f0bbc211e4f7be3c`.

File: examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart (hunk 64 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart]: I've moved back to passing EditableTextState, details in this comment: https://github.com/flutter/flutter/pull/107193#issuecomment-1268749813

File: examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart (hunk 23 above)
Comment (justinmc) [reply examples/api/lib/material/context_menu/editable_text_toolbar_builder.0.dart]: I've moved back to passing EditableTextState, details in this comment: https://github.com/flutter/flutter/pull/107193#issuecomment-1268749813

File: examples/api/lib/material/context_menu/editable_text_toolbar_builder.1.dart [hunk 66]
```diff
@@ -0,0 +1,83 @@
...
+        ),
+        body: Center(
+          child: Column(
+            children: <Widget>[
+              Container(height: 20.0),
+              TextField(
+                controller: _controller,
+                contextMenuBuilder: (BuildContext context, EditableTextState editableTextState) {
+                  final List<ContextMenuButtonItem> buttonItems =
+                      editableTextState.contextMenuButtonItems;
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply examples/api/lib/material/context_menu/editable_text_toolbar_builder.1.dart:47]: Also I think either `contextMenuButtonItems`
and `getAnchors` should both be in the EditableState, or both are coming from a static method of `AdaptiveTextSelectionToolbar`. It feels weird that one of them is a getter in editable, while the other one retrieved through AdaptiveTextSelectionToolbar. It will be good that all of information to customize the context menu is in a central place. 

In the future, the API to retrieve those information can also be a mixin so that any widget state use that mixin can have the context menu.

File: examples/api/lib/material/context_menu/editable_text_toolbar_builder.1.dart [hunk 67]
```diff
@@ -0,0 +1,83 @@
...
+                    buttonItems.insert(0, ContextMenuButtonItem(
+                      label: 'Send email',
+                      onPressed: () {
+                        ContextMenuController.removeAny();
+                        _showDialog(context);
+                      },
+                    ));
+                  }
+                  return AdaptiveTextSelectionToolbar.buttonItems(
+                    anchors: AdaptiveTextSelectionToolbar.getAnchorsEditable(editableTextState),
```
Comment (chunhtai) [inline examples/api/lib/material/context_menu/editable_text_toolbar_builder.1.dart:62]: I wish we can get rid of the anchor and use layer link instead. There will always be one frame delay using the offset to position the toolbar.

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart [hunk 68]
```diff
@@ -0,0 +1,393 @@
...
+  ///   directly as a list of widgets.
+  /// {@endtemplate}
+  /// {@macro flutter.cupertino.CupertinoAdaptiveTextSelectionToolbar.editable}
+  /// {@macro flutter.cupertino.CupertinoAdaptiveTextSelectionToolbar.editableText}
+  /// {@macro flutter.cupertino.CupertinoAdaptiveTextSelectionToolbar.selectable}
+  const CupertinoAdaptiveTextSelectionToolbar.buttonItems({
+    super.key,
+    required this.buttonItems,
+    required this.anchors,
+  }) : children = null;
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:77]: Can this just be 
`children = getAdaptiveButtons(buttonItems)`

I noticed you need a context to call the function, but you don't need to if CupertinoTextSelectionToolbarButton.text builds the text in build method instead of the constructor. This will also benefit the inherited rebuild the the text widget only instead of the entire toolbar

Comment (chunhtai) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:77]: unless of course you want the const constructor

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart [hunk 69]
```diff
@@ -0,0 +1,393 @@
...
+  ///   equivalent of this class and builds only the Material buttons.
+  static Iterable<Widget> getAdaptiveButtons(BuildContext context, List<ContextMenuButtonItem> buttonItems) {
+    switch (defaultTargetPlatform) {
+      case TargetPlatform.android:
+      case TargetPlatform.fuchsia:
+      case TargetPlatform.iOS:
+        return buttonItems.map((ContextMenuButtonItem buttonItem) {
+          return CupertinoTextSelectionToolbarButton.text(
+            onPressed: buttonItem.onPressed,
+            text: getButtonLabel(context, buttonItem),
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:253]: probably not too big of an issue, but a dependency check up in this level will cause the rebuild of the entire toolbar  while you can do the look up in the CupertinoTextSelectionToolbarButton

**Review by chunhtai — COMMENTED** [review]
Overall looks good, left some comments on the APIs

**Review by LongCatIsLooong — COMMENTED** [review]
Regarding ButtonItem vs widget:

> Button widgets to be built with knowledge of their siblings. Some buttons look different depending on if they're the first button of many, or the only button, or a middle button, etc.

is there an example? Does the Toobar widget decide what they look like if a button's appearance has to do with the location in the toolbar? 

> Users to modify the buttons before they are turned into widgets. Users may want use a different widget than the default but with the same label/callback, insert a custom button after the Paste button, etc.

ContextMenuItemWidget can still expose its `type` field so if you pass in a List of ContextMenuItemWidget, the callee can still find out if there's a widget for paste , and its index?

**Comment by justinmc** [comment]
@LongCatIsLooong About ButtonItem vs. widget: [Here](https://github.com/flutter/flutter/pull/107193/files#diff-a9680c8f968ad15d426a2929cc646ca042795ec16464e9fbae8213fc59ec1f61R246) is where AdaptiveTextSelectionToolbar decides the padding of its children based on the index and total number of children.  [Here](https://github.com/flutter/flutter/blob/8875040c9871a5538bf204f0a73874e04412da98/packages/flutter/lib/src/material/text_selection.dart#L261) is where this used to happen before this PR.

[Here's a commit](https://github.com/flutter/flutter/commit/5f65c540a67665ef1a0f79a79272a2bc688d390e) where I quickly got it working by turning ContextMenuButtonItem into ContextMenuItem, a StatelessWidget.  Besides taking `label` and `onPressed`, it now takes a nullable `child`.  If child is null, then it will build a SizedBox.shrink (really the point of this is to tell the AdaptiveTextSelectionToolbar to override it with the right button for the platform).  If child is not null then it's used as-is.

This definitely isn't fully fleshed out, but I wonder what your vision here is.  I think fundamentally I do need a way to specify the label/callback without specifying what the button looks like.  It's possible to do this using a single widget as in the commit linked above, but it feels forced as it is there.

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart [hunk 70]
```diff
@@ -0,0 +1,393 @@
...
+  /// The children of the toolbar, typically buttons.
+  final List<Widget>? children;
+
+  /// The [ContextMenuButtonItem]s that will be turned into the correct button
+  /// widgets for the current platform.
+  final List<ContextMenuButtonItem>? buttonItems;
+
+  /// Gets the line height at the start of the selection for the given
+  /// [EditableTextState].
+  static double _getStartGlyphHeight(EditableTextState editableTextState) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart]: Good call, I've taken both suggestions in https://github.com/flutter/flutter/pull/107193/commits/31466a40a3f59c67057ce5e1d00ed82dfe92e0ec.

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart [hunk 71]
```diff
@@ -0,0 +1,393 @@
...
+    final RenderEditable renderEditable = editableTextState.renderEditable;
+    final InlineSpan span = renderEditable.text!;
+    final String prevText = span.toPlainText();
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart]: How do I get the InlineSpan from EditableTextState, by calling `buildTextSpan`?

This is code is just moved from here: https://github.com/flutter/flutter/blob/f059dd40ea2d89a7b3489d36a742d7656545183f/packages/flutter/lib/src/widgets/text_selection.dart#L513.

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart [hunk 72]
```diff
@@ -0,0 +1,369 @@
...
+  }
+
+  /// {@template flutter.cupertino.CupertinoAdaptiveTextSelectionToolbar.getAnchorsEditable}
+  /// Returns the location anchors for the text selection toolbar for the given
+  /// [EditableTextState].
+  /// {@endtemplate}
+  static TextSelectionToolbarAnchors getAnchorsEditable(EditableTextState editableTextState) {
+    if (editableTextState.renderEditable.lastSecondaryTapDownPosition != null) {
+      return TextSelectionToolbarAnchors(
+        primaryAnchor: editableTextState.renderEditable.lastSecondaryTapDownPosition!,
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:264]: I'm definitely on board with that.  I'm hoping @Renzo-Olivares's work will make that possible.

File: packages/flutter/lib/src/cupertino/desktop_text_selection_toolbar_button.dart [hunk 73]
```diff
@@ -0,0 +1,102 @@
...
+
+  @override
+  Widget build(BuildContext context) {
+    return SizedBox(
+      width: double.infinity,
+      child: MouseRegion(
+        onEnter: _onEnter,
+        onExit: _onExit,
+        child: CupertinoButton(
+          alignment: Alignment.centerLeft,
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/desktop_text_selection_toolbar_button.dart:90]: I think so, this is what it looks like:

Screenshot from 2022-10-17 11-09-45

This code was moved as-is from here:

https://github.com/flutter/flutter/blob/f059dd40ea2d89a7b3489d36a742d7656545183f/packages/flutter/lib/src/cupertino/desktop_text_selection.dart#L375

File: packages/flutter/lib/src/material/desktop_text_selection_toolbar.dart [hunk 74]
```diff
@@ -0,0 +1,93 @@
...
+// a Macbook Pro.
+const double _kToolbarScreenPadding = 8.0;
+const double _kToolbarWidth = 222.0;
+
+/// A Material-style desktop text selection toolbar.
+///
+/// Typically displays buttons for text manipulation, e.g. copying and pasting
+/// text.
+///
+/// Tries to position itself as closely as possible to [anchor] while remaining
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/desktop_text_selection_toolbar.dart:20]: In this case it's the distance between the point and the top left corner, I'll clarify.  Good catch.

File: packages/flutter/lib/src/widgets/context_menu_controller.dart (hunk 27 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart:46]: In my examples I'm using removeAny to close the menu that's managed by the TextField, see: https://github.com/flutter/flutter/pull/107193/files#diff-c37e45d149cf86a6565f1eb32f738d5faaf4170b8bd4f1f6421651f0af2f1bfaR56

Without that I might need to pass the instance of ContextMenuController via the contextMenuBuilder parameters.  Do you think that's a better option?

I think that the owner of a context menu should expect that their menu can be closed at any time.  If the users interacts with any other part of the app then the menu will be closed.  The owner can listen to `onRemove` if they want.

Maybe I should make it more clear in the docs that the menu can be closed from anywhere?

File: examples/api/lib/material/context_menu/editable_text_toolbar_builder.1.dart (hunk 66 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply examples/api/lib/material/context_menu/editable_text_toolbar_builder.1.dart:47]: About your first comment: Good idea, I'll keep an eye out for how users are using this after it's merged.  Your idea would make it easier to append buttons, which is probably the most common use case.  For fancier things like inserting buttons in other places, removing buttons, modifying buttons, they can still use the approach in this example.

About your second comment: I took your advice and moved the anchors to EditableTextState and SelectableRegionState, see commit https://github.com/flutter/flutter/pull/107193/commits/327d47bc8900271c00d4766bdb526ce9947af8f9.

File: examples/api/lib/material/context_menu/editable_text_toolbar_builder.1.dart (hunk 67 above)
Comment (justinmc) [reply examples/api/lib/material/context_menu/editable_text_toolbar_builder.1.dart:62]: There is a LayerLink used to position the toolbar relative to scrolling, but the anchor is used to position it relative to that. [Code](https://github.com/flutter/flutter/pull/107193/files#diff-6f186b82dcb3d864ea23246744ea7a67bcb64d369e0da5495cd0bd0e038f9bd9R1517).

The position of the anchor depends on the laid out text.  I don't know if we can get around a one frame delay due to that, but I admit I haven't played around with the idea.

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart (hunk 68 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:77]: Here you go: https://github.com/flutter/flutter/pull/107193/commits/f8571e42dc06ab088d5734ec4190ea3df681c288

Let me know what you think.  I ended up having to use an `// ignore:` comment.  Let me know if you can think of a better way to do this.

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart (hunk 69 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart]: Covered in https://github.com/flutter/flutter/pull/107193#discussion_r997571373

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart (hunk 68 above)
Comment (chunhtai) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:77]: I think you can fix the warnning by using
```
required Widget this.child,
```

Comment (justinmc) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:75]: Ah that worked, thanks!

File: packages/flutter/test/material/text_selection_test.dart [hunk 75]
```diff
@@ -489,6 +489,7 @@ void main() {
               child: Material(
                 child: TextField(
                   controller: controller,
+                  maxLines: null,
```
Comment (chunhtai) [inline packages/flutter/test/material/text_selection_test.dart:492]: ?

**Review by chunhtai — COMMENTED** [review]
The rest LGTM

File: packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart [hunk 76]
```diff
@@ -0,0 +1,225 @@
...
+  /// will still be used, because the Cupertino library does not access the
+  /// Material library. To get the native-looking buttons on every platform, use
+  /// use [AdaptiveTextSelectionToolbar.getAdaptiveButtons] in the Material
+  /// library.
+  ///
+  /// See also:
+  ///
+  /// * [AdaptiveTextSelectionToolbar.getAdaptiveButtons], which is the Material
+  ///   equivalent of this class and builds only the Material buttons.
+  static Iterable<Widget> getAdaptiveButtons(BuildContext context, List<ContextMenuButtonItem> buttonItems) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/adaptive_text_selection_toolbar.dart:177]: I made it public for the case where a user wants to create buttons that look like the default ones for the current platform but with custom labels and callbacks.  I just added another example to demonstrate this use case and better document how this method can be used: https://github.com/flutter/flutter/pull/107193/commits/45844cce7cc93c748618d1a4657a5fbfbcdaf25c

We should keep an eye on how users are actually using these new APIs and what kinds of menus they're building, though.  I imagine this method will be useful but I could be wrong.

File: packages/flutter/lib/src/cupertino/desktop_text_selection_toolbar.dart [hunk 77]
```diff
@@ -0,0 +1,115 @@
...
+///    macOS.
+///  * [DesktopTextSelectionToolbar], which is similar but builds a
+///    Material-style desktop toolbar.
+class CupertinoDesktopTextSelectionToolbar extends StatelessWidget {
+  /// Creates a const instance of CupertinoTextSelectionToolbar.
+  const CupertinoDesktopTextSelectionToolbar({
+    super.key,
+    required this.anchor,
+    required this.children,
+  }) : assert(children.length > 0);
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/desktop_text_selection_toolbar.dart:51]: Apparently `isNotEmpty` is not a constant value!  The compiler yelled at me when I tried to change it.  I guess I'll just keep it like this rather than remove the `const`.

File: packages/flutter/lib/src/cupertino/desktop_text_selection_toolbar.dart [hunk 78]
```diff
@@ -0,0 +1,115 @@
...
+        border: Border.all(
+          color: _kToolbarBorderColor.resolveFrom(context),
+        ),
+        borderRadius: const BorderRadius.all(_kToolbarBorderRadius),
+      ),
+      child: Padding(
+        padding: const EdgeInsets.symmetric(
+          // This value was measured from a screenshot of TextEdit on macOS
+          // 10.15.7 on a Macbook Pro.
+          vertical: 3.0,
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/desktop_text_selection_toolbar.dart:79]: Good idea, in fact I already have some constants above with the same comment so I can just put this with those.

File: packages/flutter/lib/src/material/desktop_text_selection_toolbar.dart [hunk 79]
```diff
@@ -0,0 +1,93 @@
...
+///    platform.
+///  * [TextSelectionToolbar], which is similar, but builds an Android-style
+///    toolbar.
+class DesktopTextSelectionToolbar extends StatelessWidget {
+  /// Creates a const instance of DesktopTextSelectionToolbar.
+  const DesktopTextSelectionToolbar({
+    super.key,
+    required this.anchor,
+    required this.children,
+  }) : assert(children.length > 0);
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/material/desktop_text_selection_toolbar.dart:35]: See https://github.com/flutter/flutter/pull/107193#discussion_r1002042010

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 80]
```diff
@@ -5988,6 +6086,7 @@ void main() {
                 key: key1,
                 focusNode: focusNode1,
               ),
+              const SizedBox(height: 100.0),
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/test/cupertino/text_field_test.dart:6089]: This test started failing because the context menu from one field would block the other field.  One of these taps aimed at a field ended up hitting a button on the context menu instead.  This spacer puts them far enough apart that it won't happen anymore.

In this PR I corrected some logic on when the menu will show and which menu will show, so this problem didn't happen before.

File: packages/flutter/test/material/text_selection_test.dart (hunk 75 above)
Comment (justinmc) [reply packages/flutter/test/material/text_selection_test.dart:492]: I can't remember why I did that, I must have been debugging something.  I'll remove it, it passes without it still.

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 80 above)
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/test/cupertino/text_field_test.dart:6089]: maybe add a comment here?

File: packages/flutter/lib/src/widgets/context_menu_controller.dart [hunk 81]
```diff
@@ -0,0 +1,132 @@
...
+  ///
+  /// Since there can only be one shown context menu at a time, calling this
+  /// constructor will also remove any other context menu that is visible.
+  ContextMenuController({
+    this.onRemove,
+    required BuildContext context,
+    required WidgetBuilder contextMenuBuilder,
+    Widget? debugRequiredFor,
+  }) {
+    _show(
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart:32]: You make some good points.  The interesting thing about ContextMenuController is that it can only ever be showing one instance of a context menu at a time, so I made the API try to reinforce that idea.  But I could refactor things like TextField to take a ContextMenuController instance instead of contextMenuBuilder.  What do you think @LongCatIsLooong?

It would feel better to call `contextMenuController.remove()` instead of `ContextMenuController.removeAny()` in places like [this example](https://github.com/flutter/flutter/pull/107193/files#diff-c37e45d149cf86a6565f1eb32f738d5faaf4170b8bd4f1f6421651f0af2f1bfaR56) at least.  I'll play around with this and see what it looks like.

[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart:32]: I think it make sense to have removeAny.

I think there are two ways:
1. constructor shows the context menu, and dispose close the context menu.
2. constructor does not show context menu, add an additional `show` API

If we go with (1) we should rename remove/removeAny to dispose/disposeAll. This is kinda weird though because calling this disposeAll will dispose other controller where the caller does not own, it creates a weird ownership model. It is probably better to go with singleton model if we go down this route

If we want to makes the controller a pass in parameter TextField, we can only go with (2).

**Review by chunhtai — APPROVED** [review]
LGTM, except for the contextmenucontroller. I am fine with either approach

File: packages/flutter/lib/src/widgets/context_menu_controller.dart (hunk 81 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/context_menu_controller.dart]: I went with 2 after trying out both.

I also tried passing in the controller to TextField, but I decided against it for now.  The catch here is that in most practical cases that I tried, the contextMenuBuilder needed to be updated for each subsequent call to `show`.  So it wasn't possible to pass the contextMenuBuilder into the constructor and then just call `show` on that instance every time, say, the user right clicks.  Instead, each time the user right clicks, I need to pass in a new contextMenuBuilder to `show`.  That negates the benefit of single long-lived controller instance that the user passes in along with their contextMenuBuilder.

I plan to revisit this when OverlayPortal is released, though I'm not sure how drastically it will change this kind of thing.

**Comment by BernardinD** [comment]
Hi, thx for introducing this feature. It's been very helpful.

I'm wondering if the "undo" will become available for android. I had assumed all the default menu options for the platform always show up for each text field type but "undo" isn't showing up for TextFormField so I'm in need of some guidance.

**Comment by justinmc** [comment]
@BernardinD I'm glad this has been useful for you!

I think this is the relevant issue: https://github.com/flutter/flutter/issues/107578

Would you be able to leave a comment over there with details about when the "undo" button should show up?  Looking at that issue, it seems that I missed it when I investigated which buttons are missing for Android.  Currently, only Cut, Copy, Paste, and Select all are built-in, but now that this PR has been merged, it should be much easier to add the missing buttons.
