### PR TITLE
prevent _computeColumnWidths from getting stuck due to double precision

### LINKED ISSUE #27083: Table is stuck in an infinite loop sometimes
## Steps to Reproduce

1. Create a Table with two rows and 6 columns, all containing a Text widget.
2. When it is supposed to be displayed as child of a `DefaultTabController->Scaffold->TabBarView` it might get stuck in an infinite loop.
3. I'll describe where and how it is stuck below

It gets stuck in `RenderTable._computeColumnWidths` method, specifically in this while loop:

```dart
int availableColumns = columns;
      while (deficit > 0.0 && totalFlex > 0.0) {
        double newTotalFlex = 0.0;
        for (int x = 0; x < columns; x += 1) {
          if (flexes[x] != null) {
            final double newWidth = widths[x] - deficit * flexes[x] / totalFlex;
            assert(newWidth.isFinite);
            if (newWidth <= minWidths[x]) {
              // shrank to minimum
              deficit -= widths[x] - minWidths[x];
              widths[x] = minWidths[x];
              flexes[x] = null;
              availableColumns -= 1;
            } else {
              deficit -= widths[x] - newWidth;
              widths[x] = newWidth;
              newTotalFlex += flexes[x];
            }
            assert(widths[x] >= 0.0);
          }
        }
        totalFlex = newTotalFlex;
      }
```

The problem is that deficit is a really small value `2.842170943040401e-14` and it won't get to or below `0`.
Other values are:
```
widths: [65.9047619047619, 65.9047619047619, 65.90476190476191, 65.90476190476191, 65.90476190476191, 65.90476190476191]
minWidths: [0, 0, 0, 0, 0, 0]
flexes: [1, 1, 1, 1, 1, 1]
totalFlex: 6
```
Basically `newWidth <= minWidths[x]` is always false and deficit doesn't decrease because `widths[x] - newWidth` is always `0`.

This problem happens only on some screens and it is consistent when it starts (i.e. works on emulator and not on device - Nexus 6, or the other way round).

## Logs

No useful logs (when it gets stuck nothing is reported).

No issues found! (ran in 3.4s)

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.253], locale sl-SI)  
    • Flutter version 1.0.0 at D:\SDK\flutter                                                      
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800                       
    • Engine revision 7375a0f414                                                                   
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)                                          
                                                                                                   
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)                           
    • Android SDK at C:\Users\miha\AppData\Local\Android\sdk                                       
    • Android NDK location not configured (optional; useful for native profiling support)          
    • Platform android-28, build-tools 28.0.3                                                      
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java                         
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)                  
    • All Android licenses accepted.                                                               
                                                                                                   
[√] Android Studio (version 3.3)                                                                   
    • Android Studio at C:\Program Files\Android\Android Studio                                    
    X Flutter plugin not installed; this adds Flutter specific functionality.                      
    X Dart plugin not installed; this adds Dart specific functionality.                            
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)                  
                                                                                                   
[√] VS Code (version 1.30.2)                                                                       
    • VS Code at C:\Users\miha\AppData\Local\Programs\Microsoft VS Code                            
    • Flutter extension version 2.21.1                                                             
                                                                                                   
[√] Connected device (2 available)                                                                 
    • Nexus 6                   • ZX1G4256JM    • android-arm • Android 7.1.1 (API 25)             
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)  
                                                                                                   
• No issues found!                                                                                 
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
Certain table arrangements can cause _computeColumnWidths to end up with a very small deficit value like 1e-14. Because we check for > 0, this can get stuck in an infinite loop.

Instead changed 0 to a small value.

Added regression test.

Fixes https://github.com/flutter/flutter/issues/27083

### CODE REVIEW

File: packages/flutter/test/widgets/table_test.dart [hunk 1]
```diff
@@ -297,6 +297,31 @@ void main() {
     expect(boxG1, isNot(equals(boxG2)));
   });
 
+  // Regression test for https://github.com/flutter/flutter/issues/27083
```
Comment (goderbauer) [inline packages/flutter/test/widgets/table_test.dart]: I believe we usually put this comment inside the testWidgets?

File: packages/flutter/test/widgets/table_test.dart [hunk 2]
```diff
@@ -297,6 +297,31 @@ void main() {
...
+            TableRow(
+              children: <Widget>[
+                cell, cell, cell, cell, cell, cell,
+              ],
+            ),
+          ],
+        ),
+      ),
+    );
+    expect(true, true);
```
Comment (goderbauer) [inline packages/flutter/test/widgets/table_test.dart]: This looks very odd. Is that necessary? If so, probably deserves a comment.

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/widgets/table_test.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter/test/widgets/table_test.dart]: Not really necessary, I can leave it out. The test will run forever without the fix applied so I felt it was necessary to put something in there...

Comment (goderbauer) [reply packages/flutter/test/widgets/table_test.dart]: Maybe just a comment that the failing condition is never terminates?

Comment (jonahwilliams) [reply packages/flutter/test/widgets/table_test.dart]: Done
