### PR TITLE
Precise browser resizing with integration_test and driver

### LINKED ISSUE #136109: Flutter drive --browser-dimension not working
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am trying to run flutter web test on Chrome, with the following command:

```
flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/main_test.dart > C:\Automation_test\Report_log\log.txt \
  --browser-dimension="1920,1080" \
  -d chrome
```

### Expected results

The browser is resized to 1920 x 1080 when start.

### Actual results

The browser is NOT resized to 1920 x 1080 when start.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by munrocket**
Fixes #136109 P2
Related #148028 P1

Roadmap:
- [x] find why not working (described in #136109)
- [x] create new API with backward compatibility (`--browser-dimension=393×852@3`)
- [x] fix edge cases
- [x] internal testing
- [x] add documentation (flutter drive -h)

This PR:
- Fixes Chrome bug from dart side
- Adds pixelRatio mobile emulation in web
- Adds new notation: 393,852 -> 393×852[@1]
- Leaves previous behavior as it was, so 393,852 will give wrong size until Chrome will fix it. But you can use 393×852@1.

### CODE REVIEW

**Comment by munrocket** [comment]
This PR is ready for review.

**Comment by jmagman** [comment]
The analysis error is 
```
 Found 1 Dart file which was formatted incorrectly.
 To fix, run `dart format packages/flutter_tools/lib/src/drive/web_driver_service.dart` or:
 git apply <<DONE
 diff --git a/packages/flutter_tools/lib/src/drive/web_driver_service.dart b/packages/flutter_tools/lib/src/drive/web_driver_service.dart
 index 02cbe7a84e..0000000000 100644
 --- a/packages/flutter_tools/lib/src/drive/web_driver_service.dart
 +++ b/packages/flutter_tools/lib/src/drive/web_driver_service.dart
 @@ -178,7 +178,8 @@ class WebDriverService extends DriverService {
                'height': height,
                'pixelRatio': double.parse(browserDimension[2]),
              },
 -            'userAgent': 'Mozilla/5.0 (Linux; Android 15) AppleWebKit/537.36 '
 +            'userAgent':
 +                'Mozilla/5.0 (Linux; Android 15) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/131.0.6778.200 Mobile Safari/537.36',
            };
          }
 @@ -382,3 +383,4 @@ Map<String, dynamic> getDesiredCapabilities(
      },
    },
  };
 DONE
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8727677075114199649/+/u/run_test.dart_for_analyze_shard_and_subshard_None/stdout

**Comment by munrocket** [comment]
@jmagman thanks for answer, I have little progress.

- [x] fixed format
- [x] linux android [stderr: Screenshot not supported for Linux.](https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android_emu_34%20android%20views/7335/overview) miraculously fixed after rebase
- [ ] mac native_ui [The Swift Package Manager feature is off.](https://ci.chromium.org/ui/p/flutter/builders/try/Mac_x64%20native_ui_tests_macos) maybe will be fixed in same way.

It’s not obvious how to find proper build, because there are no link from github and searching by PR/hash is off, only by test name.

**Comment by munrocket** [comment]
It was not easy, but CI passed. Ready for review.

**Comment by jmagman** [comment]
> It was not easy, but CI passed. Ready for review.

Thank you for figuring it all out!  We're a bit slower to review around the end of the year due to holidays, the web or tool team will take a look during their regularly scheduled triage.
cc @yjbanov

File: packages/flutter_tools/lib/src/drive/web_driver_service.dart [hunk 1]
```diff
@@ -156,6 +156,38 @@ class WebDriverService extends DriverService {
...
+        if (len == 3) {
+          mobileEmulation = <String, dynamic>{
+            'deviceMetrics': <String, dynamic>{
+              'width': width,
+              'height': height,
+              'pixelRatio': double.parse(browserDimension[2]),
+            },
+            'userAgent':
+                'Mozilla/5.0 (Linux; Android 15) AppleWebKit/537.36 (KHTML, '
+                'like Gecko) Chrome/131.0.6778.200 Mobile Safari/537.36',
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/drive/web_driver_service.dart:183]: Why do we need to pass the `userAgent`? Also, is it safe to hard-code the browser version like this?

File: packages/flutter_tools/lib/src/commands/drive.dart [hunk 2]
```diff
@@ -135,11 +135,11 @@ class DriveCommand extends RunCommandBase {
       )
       ..addOption(
         'browser-dimension',
-        defaultsTo: '1600,1024',
+        defaultsTo: '1600x1024',
         help:
             'The dimension of the browser when running a Flutter Web test. '
             'This will affect screenshot and all offset-related actions.',
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/commands/drive.dart:141]: Let's also update the docs and describe the accepted value format.

File: packages/flutter_tools/lib/src/drive/web_driver_service.dart (hunk 1 above)
Comment (EatonWu) [reply packages/flutter_tools/lib/src/drive/web_driver_service.dart:183]: I believe this is necessary, in the developer tools of chrome, you can set the user agent, this will probably emulate some of that: 
image

The device user agent is often used to test platform specific functionality.

**Comment by munrocket** [comment]
Sorry, didn't notice updates here.

**Comment by munrocket** [comment]
We also can force mobileEmulation in any situation, because it magically works.
But in this case we probably need to update some goldens.

**Comment by bkonyi** [comment]
@yjbanov do you have any more comments / concerns?

**Comment by bkonyi** [comment]
Friendly ping @yjbanov

**Comment by jBorkowska** [comment]
Any ETA on this? Just wondering because I really would like to use it in my project :)

**Comment by alexobviously** [comment]
+1 this bug is blocking something significant for me too :)

**Comment by mdebbar** [comment]
Looks good to me, thanks for the contribution!

I hit "Update branch" to bring the PR up to date. Let's see if CI is happy or not.

**Review by mdebbar — APPROVED** [review]

**Comment by mdebbar** [comment]
I think we need a 2nd review to land this PR. @bkonyi do you wanna take a look?

**Review by bkonyi — APPROVED** [review]
Sorry for the delay on this. LGTM.
