### PR TITLE
Fixing memory leak in EditableTextState

### LINKED ISSUE #130469: EditableTextState does not dispose TextSelectionOverlay.
PR that marks leak: https://github.com/flutter/flutter/pull/130470
Creation call stack: https://raw.githubusercontent.com/polina-c/spikes/master/notes/failures/2023-July-12/text_selection_theme_111.txt

To repro, remove leakTrackingTestConfig in flutter/test/material/text_selection_theme_test.dart, and observe the tests failing.

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Fixes #130469

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/material/text_selection_theme_test.dart [hunk 1]
```diff
@@ -168,17 +168,19 @@ void main() {
     final RenderBox handle = tester.firstRenderObject<RenderBox>(find.byType(CustomPaint));
     expect(handle, paints..path(color: defaultSelectionHandleColor));
   },
+  // leakTrackingTestConfig: LeakTrackingTestConfig.retainingPath(),
```
Comment (polina-c) [inline packages/flutter/test/material/text_selection_theme_test.dart:171]: This can be removed completely.

File: packages/flutter/lib/src/material/text_field.dart [hunk 2]
```diff
@@ -1101,6 +1101,7 @@ class _TextFieldState extends State<TextField> with RestorationMixin implements
     _effectiveFocusNode.removeListener(_handleFocusChanged);
     _focusNode?.dispose();
     _controller?.dispose();
+    _controller = null;
```
Comment (polina-c) [inline packages/flutter/lib/src/material/text_field.dart:1104]: Nulling out in dispose, as a fix for leak, smells.
Here is why: https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md#1-static-or-global-object-causes-notgced-leaks

May be some field on retaining path should be converted to WeakReference?

See other fix for notGCed, that converts a field, not owned by parent, to WeakReference: https://github.com/flutter/flutter/pull/130842

**Review by polina-c — APPROVED** [review]
