### PR TITLE
Prevent dropdown menu's scroll offset from going negative

### LINKED ISSUE #15346: DropdownButton with long list scroll to end of list
## Steps to Reproduce
```
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new DropdownButton<int>(
        items: new List<DropdownMenuItem<int>>.generate(
          50,
          (int index) => new DropdownMenuItem<int>(
                value: index,
                child: new Text(index.toString()),
              ),
        ),
        onChanged: (int value) {},
      ),
    );
  }
```
## Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [version 10.0.16299.248], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
[√] VS Code (version 1.20.1)
[√] Connected devices (1 available)

• No issues found!
```

output

### PR DESCRIPTION
**Pull request by mklim**
Before the offset was adjusted by `- (buttonTop - menuTop)`, which meant
that with no item selected the offset would actually be a negative
number. In long lists that would result in the the dropdown scrolling to
the very last item in the list. Changed to be the `selectedItemOffset`
directly instead, since the extra margin seemed unnecessary.

Fixes flutter/flutter#15346

### CODE REVIEW

**Comment by mklim** [comment]
@HansMuller I dug through the history a bit but didn't see the reasoning behind `- (buttonTop - menuTop)`. From what I can tell it always computes a negative value, but maybe there's a case where that offset is needed that I'm not seeing? So far it looks like all the tests are passing with it removed still.

**Comment by HansMuller** [comment]
@mklim - the overall idea is to have the menu appear with the selected item lined up with (itself) the dropdown menu button's value. Forgetting scrolling for the moment: if the menu contains 4 items [A, B, C, D] the selected item is C, the dropdown looks like "Hello: C v", and when the menu pops up it looks like:

```
      A
      B 
Hello C
      D
```

As you can see, the top of the menu is negative relative to the top of the dropdown button. 

Things get more complicated when it's also necessary to scroll the selected item into view of course.

**Comment by mklim** [comment]
Thanks, makes sense. I'll add a test for that and rework this to make sure it still handles that case.

**Comment by mklim** [comment]
Updated.

File: packages/flutter/lib/src/material/dropdown.dart [hunk 1]
```diff
@@ -346,9 +346,9 @@ class _DropdownRoute<T> extends PopupRoute<_DropdownRouteResult<T>> {
     }
 
     if (scrollController == null) {
-      double scrollOffset = 0.0;
-      if (preferredMenuHeight > maxMenuHeight)
-        scrollOffset = selectedItemOffset - (buttonTop - menuTop);
+      final double scrollOffset = (preferredMenuHeight > maxMenuHeight) ?
+        (selectedItemOffset - (buttonTop - menuTop)).clamp(0.0, double.maxFinite)
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/dropdown.dart]: This is OK, but it seems like an odd way to say: 
`math.max(0.0, selectedItemOffset - (buttonTop - menuTop))`

File: packages/flutter/test/material/dropdown_test.dart [hunk 2]
```diff
@@ -422,6 +422,67 @@ void main() {
     checkSelectedItemTextGeometry(tester, 'two');
   });
 
+  testWidgets('Dropdown menu scrolls to first item in long lists', (WidgetTester tester) async {
+    final Key buttonKey = UniqueKey();
+    Widget build() => buildFrame(
```
Comment (HansMuller) [inline packages/flutter/test/material/dropdown_test.dart]: We typically only use `=>` for one-liners that return a value.

Why not just put the buildFrame() call in-line?

File: packages/flutter/test/material/dropdown_test.dart [hunk 3]
```diff
@@ -422,6 +422,67 @@ void main() {
...
+      buttonKey: buttonKey,
+      value: null, // nothing selected
+      items: List<String>.generate(/*length=*/ 100, (int index) => index.toString())
+    );
+
+    // Open the dropdown menu
+    await tester.pumpWidget(build());
+    final RenderBox buttonBox = tester.renderObject(find.byKey(buttonKey));
```
Comment (HansMuller) [inline packages/flutter/test/material/dropdown_test.dart]: `tester.renderObject<RenderBox>(...)`

File: packages/flutter/test/material/dropdown_test.dart [hunk 4]
```diff
@@ -422,6 +422,67 @@ void main() {
...
+    assert(buttonBox.attached);
+    await tester.tap(find.byKey(buttonKey));
+    await tester.pump();
+    await tester.pump(const Duration(seconds: 10)); // finish the menu animation
```
Comment (HansMuller) [inline packages/flutter/test/material/dropdown_test.dart]: `await tester.pumpAndSettle()`

File: packages/flutter/test/material/dropdown_test.dart [hunk 5]
```diff
@@ -422,6 +422,67 @@ void main() {
...
+    // Find the first item in the scrollable dropdown list
+    final Finder menuItemFinder = find.byType(Scrollable);
+    final RenderBox menuItemContainer = tester.renderObject<RenderBox>(menuItemFinder);
+    assert(menuItemContainer.attached);
+    final RenderBox firstItem = tester.renderObject<RenderBox>(
+      find.descendant(of: menuItemFinder, matching: find.byKey(const ValueKey<String>('0'))));
+    assert(firstItem.attached);
+
+    // List should be scrolled so that the first item is at the top
+    const Offset selectedItemOffset = Offset(0.0, -8.0);
```
Comment (HansMuller) [inline packages/flutter/test/material/dropdown_test.dart]: The comment should explain what the -8.0 is for.

File: packages/flutter/test/material/dropdown_test.dart [hunk 6]
```diff
@@ -422,6 +422,67 @@ void main() {
...
+    expect(
```
Comment (HansMuller) [inline packages/flutter/test/material/dropdown_test.dart]: NICE.

File: packages/flutter/test/material/dropdown_test.dart [hunk 7]
```diff
@@ -422,6 +422,67 @@ void main() {
...
+  testWidgets('Dropdown menu aligns selected item with button in long lists', (WidgetTester tester) async {
+    final Key buttonKey = UniqueKey();
+    Widget build() => buildFrame(
+      buttonKey: buttonKey,
+      value: '50',
+      items: List<String>.generate(/*length=*/ 100, (int index) => index.toString())
+    );
+
+    // Open the dropdown menu
+    await tester.pumpWidget(build());
```
Comment (HansMuller) [inline packages/flutter/test/material/dropdown_test.dart]: As before. Typically we don't add a level of indirection like this.

File: packages/flutter/test/material/dropdown_test.dart [hunk 8]
```diff
@@ -422,6 +422,67 @@ void main() {
...
+    final RenderBox buttonBox = tester.renderObject(find.byKey(buttonKey));
+    assert(buttonBox.attached);
+    await tester.tap(find.byKey(buttonKey));
+    await tester.pump();
+    await tester.pump(const Duration(seconds: 1)); // finish the menu animation
+
+    // Find the selected item in the scrollable dropdown list
+    final RenderBox selectedItem = tester.renderObject<RenderBox>(
+      find.descendant(of: find.byType(Scrollable), matching: find.byKey(const ValueKey<String>('50'))));
+    assert(selectedItem.attached);
```
Comment (HansMuller) [inline packages/flutter/test/material/dropdown_test.dart]: Why are we asserting `attached` here and elsewhere? I don't believe WidgetTester.renderObject will succeed for an unattached renderer.

... I see, these assertions appear through this file, but not anywhere else (in fact I appear to responsible for a few of them).

File: packages/flutter/test/material/dropdown_test.dart [hunk 9]
```diff
@@ -422,6 +422,67 @@ void main() {
...
+      items: List<String>.generate(/*length=*/ 100, (int index) => index.toString())
+    );
+
+    // Open the dropdown menu
+    await tester.pumpWidget(build());
+    final RenderBox buttonBox = tester.renderObject(find.byKey(buttonKey));
+    assert(buttonBox.attached);
+    await tester.tap(find.byKey(buttonKey));
+    await tester.pump();
+    await tester.pump(const Duration(seconds: 1)); // finish the menu animation
```
Comment (HansMuller) [inline packages/flutter/test/material/dropdown_test.dart]: `await tester.pumpAndSettle()`

**Review by HansMuller — COMMENTED** [review]
This all looks good. I'd just like to get to the bottom of the attached assertions. Maybe we're trying to determine if tester.renderObject is turning up scrollable child that's no longer visible? Seems like that should be checked with expect, not assert(). And not by checking the attached property, but by checking that it's within the scrollable's viewport.

File: packages/flutter/test/material/dropdown_test.dart (hunk 6 above)
Comment (mklim) [reply packages/flutter/test/material/dropdown_test.dart]: :)

**Comment by mklim** [comment]
Thanks for the review! This patch looks much cleaner now.

> I'd just like to get to the bottom of the attached assertions.

They definitely weren't necessary for the test cases I added, I was just following the pattern I saw in other cases in this file. I assumed that it was common or best practice to assert that elements exist before acting on them since I saw it in other test cases. For my cases the last `expect()`s are checking everything that I need to actually verify. Not sure why the other test cases had them originally though, that is probably worth following up on.

**Review by HansMuller — APPROVED** [review]
LGTM

Eventually we should get to the bottom of the attached assertions in the rest of dropdown_test.dart. This PR looks good without them :-).

**Comment by gspencergoog** [comment]
@fkorotkov, why is there still one GitHub check status that says it hasn't completed, when Cirrus says it has?  It looks like GitHub is listing `tests-windows` status three times in this PR.

**Comment by fkorotkov** [comment]
@gspencergoog there are two of them for the same task! One passed and one reported as still queued Looking into it.

**Comment by mklim** [comment]
@fkorotkov Thanks! I just recently tried restarting the task, if that makes a difference. The new run from that is https://cirrus-ci.com/task/5629948521873408.

File: packages/flutter/lib/src/material/dropdown.dart [hunk 10]
```diff
@@ -346,9 +346,8 @@ class _DropdownRoute<T> extends PopupRoute<_DropdownRouteResult<T>> {
     }
 
     if (scrollController == null) {
-      double scrollOffset = 0.0;
-      if (preferredMenuHeight > maxMenuHeight)
-        scrollOffset = selectedItemOffset - (buttonTop - menuTop);
+      final double scrollOffset = (preferredMenuHeight > maxMenuHeight) ?
+        math.max(0.0, selectedItemOffset - (buttonTop - menuTop)) : 0.0;
```
Comment (Hixie) [inline packages/flutter/lib/src/material/dropdown.dart]: what i find weird about this approach is that it's asymmetrical. Why do we clamp at zero but not at some equivalent large offset?

**Comment by jslavitz** [comment]
Hey! I've got a fix here: https://github.com/flutter/flutter/pull/22594 that I think makes sense.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 10 above)
Comment (mklim) [reply packages/flutter/lib/src/material/dropdown.dart]: I never saw a situation where `selectedItemOffset - (buttonTop - menuTop)` produced values that were incorrectly large, so I didn't see a need for it.

In my testing it looked like this did correctly calculate an offset for all items after the first one. It perfectly aligned them with the dropdown button itself if there was room to scroll to them. But it was consistently setting a negative value for when either nothing or the first item in a list was selected. In short lists that doesn't matter since there's no room to scroll, but as soon as there was a scrollbar then it was wrapping around to the bottom of the list to match the negative `scrollOffset`.

@jslavitz's fix in flutter/flutter#22594 looks more robust to me. If the problem is with the variables in this calculation, updating that makes more sense than clamping off known incorrect bounds.
