### PR TITLE
Ensure all errors thrown by image providers can be caught by developers.

### LINKED ISSUE #20910: App Crashes when `Image.network` fails to resolve URL
Hello there, I'm loading an image from a URL using the following code:

```
Widget _bannerImage(String url, double height) {
    return Container(
        constraints: BoxConstraints.tightFor(height: height),
        child: Image.network(url, fit: BoxFit.fitWidth));
  }
```

Using the URL:  `http://everydaydreamholiday.com/wp-content/uploads/2013/01/Arashiyama-bamboo-grove-path_kyoto_japan.jpg`

Now, this used to work, but all of a sudden, when I tried compiling my code from a poor / no internet connection, I get an exception for some reason. See below.

## Logs

```
C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06>flutter run --verbose
[  +52 ms] [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [C:\src\flutter\] git ls-remote --get-url origin
[  +59 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [C:\src\flutter\] git log -n 1 --pretty=format:%H
[  +41 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c7ea3ca377e909469c68f2ab878a5bc53d3cf66b
[        ] [C:\src\flutter\] git log -n 1 --pretty=format:%ar
[  +46 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 months ago
[   +2 ms] [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +58 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +7 ms] v0.5.1-0-gc7ea3ca37
[ +243 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb devices -l
[  +33 ms] Exit code 0 from: C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb devices -l
[   +7 ms] List of devices attached
           192.168.65.101:5555    device product:vbox86p model:Google_Pixel_2___8_0___API_26___1080x1920 device:vbox86p transport_id:1
[ +243 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb -s 192.168.65.101:5555 shell getprop
[  +85 ms] ro.hardware = vbox86
[   +2 ms] ro.build.characteristics = nosdcard
[ +991 ms] Launching lib/main.dart on Google Pixel 2, 8 0, API 26, 1080x1920 in debug mode...
[  +11 ms] Initializing gradle...
[   +1 ms] Using gradle from C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\android\gradlew.bat.
[  +85 ms] C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\android\gradlew.bat -v
[ +624 ms]
                   ------------------------------------------------------------
                   Gradle 4.1
                   ------------------------------------------------------------

                   Build time:   2017-08-07 14:38:48 UTC
                   Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

                   Groovy:       2.4.11
                   Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
                   JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b02)
                   OS:           Windows 10 10.0 amd64
[   +9 ms] Resolving dependencies...
[   +1 ms] [android\] C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\android\gradlew.bat app:properties
[+1926 ms] :app:properties

                   ------------------------------------------------------------
                   Project :app
                   ------------------------------------------------------------

                   allprojects: [project ':app']
                   android: com.android.build.gradle.AppExtension_Decorated@7a9c6f89
                   androidDependencies: task ':app:androidDependencies'
                   ant: org.gradle.api.internal.project.DefaultAntBuilder@1b6ddb3
                   antBuilderFactory: org.gradle.api.internal.project.DefaultAntBuilderFactory@20ca2b0
                   archivesBaseName: app
                   artifacts: org.gradle.api.internal.artifacts.dsl.DefaultArtifactHandler_Decorated@50e3b171
                   asDynamicObject: DynamicObject for project ':app'
                   assemble: task ':app:assemble'
                   assembleAndroidTest: task ':app:assembleAndroidTest'
                   assembleDebug: task ':app:assembleDebug'
                   assembleDebugAndroidTest: task ':app:assembleDebugAndroidTest'
                   assembleDebugUnitTest: task ':app:assembleDebugUnitTest'
                   assembleProfile: task ':app:assembleProfile'
                   assembleProfileUnitTest: task ':app:assembleProfileUnitTest'
                   assembleRelease: task ':app:assembleRelease'
                   assembleReleaseUnitTest: task ':app:assembleReleaseUnitTest'
                   baseClassLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@499a6cc3
                   buildDependents: task ':app:buildDependents'
                   buildDir: C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\build\app
                   buildFile: C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\android\app\build.gradle
                   buildNeeded: task ':app:buildNeeded'
                   buildOutputs: BaseVariantOutput container
                   buildScriptSource: org.gradle.groovy.scripts.UriScriptSource@7ef67b06
                   buildscript: org.gradle.api.internal.initialization.DefaultScriptHandler@19084f4a
                   bundleAppClassesDebug: task ':app:bundleAppClassesDebug'
                   bundleAppClassesDebugAndroidTest: task ':app:bundleAppClassesDebugAndroidTest'
                   bundleAppClassesDebugUnitTest: task ':app:bundleAppClassesDebugUnitTest'
                   bundleAppClassesProfile: task ':app:bundleAppClassesProfile'
                   bundleAppClassesProfileUnitTest: task ':app:bundleAppClassesProfileUnitTest'
                   bundleAppClassesRelease: task ':app:bundleAppClassesRelease'
                   bundleAppClassesReleaseUnitTest: task ':app:bundleAppClassesReleaseUnitTest'
                   check: task ':app:check'
                   checkDebugManifest: task ':app:checkDebugManifest'
                   checkProfileManifest: task ':app:checkProfileManifest'
                   checkReleaseManifest: task ':app:checkReleaseManifest'
                   childProjects: {}
                   class: class org.gradle.api.internal.project.DefaultProject_Decorated
                   classLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@54ad0d23
                   cleanBuildCache: task ':app:cleanBuildCache'
                   compileDebugAidl: task ':app:compileDebugAidl'
                   compileDebugAndroidTestAidl: task ':app:compileDebugAndroidTestAidl'
                   compileDebugAndroidTestJavaWithJavac: task ':app:compileDebugAndroidTestJavaWithJavac'
                   compileDebugAndroidTestNdk: task ':app:compileDebugAndroidTestNdk'
                   compileDebugAndroidTestRenderscript: task ':app:compileDebugAndroidTestRenderscript'
                   compileDebugAndroidTestShaders: task ':app:compileDebugAndroidTestShaders'
                   compileDebugAndroidTestSources: task ':app:compileDebugAndroidTestSources'
                   compileDebugJavaWithJavac: task ':app:compileDebugJavaWithJavac'
                   compileDebugNdk: task ':app:compileDebugNdk'
                   compileDebugRenderscript: task ':app:compileDebugRenderscript'
                   compileDebugShaders: task ':app:compileDebugShaders'
                   compileDebugSources: task ':app:compileDebugSources'
                   compileDebugUnitTestJavaWithJavac: task ':app:compileDebugUnitTestJavaWithJavac'
                   compileDebugUnitTestSources: task ':app:compileDebugUnitTestSources'
                   compileLint: task ':app:compileLint'
                   compileProfileAidl: task ':app:compileProfileAidl'
                   compileProfileJavaWithJavac: task ':app:compileProfileJavaWithJavac'
                   compileProfileNdk: task ':app:compileProfileNdk'
                   compileProfileRenderscript: task ':app:compileProfileRenderscript'
                   compileProfileShaders: task ':app:compileProfileShaders'
                   compileProfileSources: task ':app:compileProfileSources'
                   compileProfileUnitTestJavaWithJavac: task ':app:compileProfileUnitTestJavaWithJavac'
                   compileProfileUnitTestSources: task ':app:compileProfileUnitTestSources'
                   compileReleaseAidl: task ':app:compileReleaseAidl'
                   compileReleaseJavaWithJavac: task ':app:compileReleaseJavaWithJavac'
                   compileReleaseNdk: task ':app:compileReleaseNdk'
                   compileReleaseRenderscript: task ':app:compileReleaseRenderscript'
                   compileReleaseShaders: task ':app:compileReleaseShaders'
                   compileReleaseSources: task ':app:compileReleaseSources'
                   compileReleaseUnitTestJavaWithJavac: task ':app:compileReleaseUnitTestJavaWithJavac'
                   compileReleaseUnitTestSources: task ':app:compileReleaseUnitTestSources'
                   components: SoftwareComponentInternal set
                   configurationActions: org.gradle.configuration.project.DefaultProjectConfigurationActionContainer@4ecb8f01
                   configurationTargetIdentifier: org.gradle.configuration.ConfigurationTargetIdentifier$1@328f395
                   configurations: configuration container
                   connectedAndroidTest: task ':app:connectedAndroidTest'
                   connectedCheck: task ':app:connectedCheck'
                   connectedDebugAndroidTest: task ':app:connectedDebugAndroidTest'
                   consumeConfigAttr: task ':app:consumeConfigAttr'
                   convention: org.gradle.api.internal.plugins.DefaultConvention@58819ea5
                   copyFlutterAssetsDebug: task ':app:copyFlutterAssetsDebug'
                   copyFlutterAssetsProfile: task ':app:copyFlutterAssetsProfile'
                   copyFlutterAssetsRelease: task ':app:copyFlutterAssetsRelease'
                   createDebugCompatibleScreenManifests: task ':app:createDebugCompatibleScreenManifests'
                   createProfileCompatibleScreenManifests: task ':app:createProfileCompatibleScreenManifests'
                   createReleaseCompatibleScreenManifests: task ':app:createReleaseCompatibleScreenManifests'
                   defaultArtifacts: org.gradle.api.internal.plugins.DefaultArtifactPublicationSet_Decorated@64795483
                   defaultTasks: []
                   deferredProjectConfiguration: org.gradle.api.internal.project.DeferredProjectConfiguration@76587c8a
                   dependencies: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@32a89d8f
                   depth: 1
                   description: null
                   deviceAndroidTest: task ':app:deviceAndroidTest'
                   deviceCheck: task ':app:deviceCheck'
                   displayName: project ':app'
                   distsDir: C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\build\app\distributions
                   distsDirName: distributions
                   docsDir: C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\build\app\docs
                   docsDirName: docs
                   ext: org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension@660859c9
                   extensions: org.gradle.api.internal.plugins.DefaultConvention@58819ea5
                   extractProguardFiles: task ':app:extractProguardFiles'
                   fileOperations: org.gradle.api.internal.file.DefaultFileOperations@48fbd4c7
                   fileResolver: org.gradle.api.internal.file.BaseDirFileResolver@7df25d7e
                   flutter: FlutterExtension_Decorated@bc0f3aa
                   flutterBuildDebug: task ':app:flutterBuildDebug'
                   flutterBuildProfile: task ':app:flutterBuildProfile'
                   flutterBuildRelease: task ':app:flutterBuildRelease'
                   flutterBuildX86Jar: task ':app:flutterBuildX86Jar'
                   generateDebugAndroidTestAssets: task ':app:generateDebugAndroidTestAssets'
                   generateDebugAndroidTestBuildConfig: task ':app:generateDebugAndroidTestBuildConfig'
                   generateDebugAndroidTestResValues: task ':app:generateDebugAndroidTestResValues'
                   generateDebugAndroidTestResources: task ':app:generateDebugAndroidTestResources'
                   generateDebugAndroidTestSources: task ':app:generateDebugAndroidTestSources'
                   generateDebugAssets: task ':app:generateDebugAssets'
                   generateDebugBuildConfig: task ':app:generateDebugBuildConfig'
                   generateDebugResValues: task ':app:generateDebugResValues'
                   generateDebugResources: task ':app:generateDebugResources'
                   generateDebugSources: task ':app:generateDebugSources'
                   generateProfileAssets: task ':app:generateProfileAssets'
                   generateProfileBuildConfig: task ':app:generateProfileBuildConfig'
                   generateProfileResValues: task ':app:generateProfileResValues'
                   generateProfileResources: task ':app:generateProfileResources'
                   generateProfileSources: task ':app:generateProfileSources'
                   generateReleaseAssets: task ':app:generateReleaseAssets'
                   generateReleaseBuildConfig: task ':app:generateReleaseBuildConfig'
                   generateReleaseResValues: task ':app:generateReleaseResValues'
                   generateReleaseResources: task ':app:generateReleaseResources'
                   generateReleaseSources: task ':app:generateReleaseSources'
                   gradle: build 'android'
                   group: android
                   identityPath: :app
                   inheritedScope: org.gradle.api.internal.ExtensibleDynamicObject$InheritedDynamicObject@2fa2250a
                   installDebug: task ':app:installDebug'
                   installDebugAndroidTest: task ':app:installDebugAndroidTest'
                   installProfile: task ':app:installProfile'
                   installRelease: task ':app:installRelease'
                   javaPreCompileDebug: task ':app:javaPreCompileDebug'
                   javaPreCompileDebugAndroidTest: task ':app:javaPreCompileDebugAndroidTest'
                   javaPreCompileDebugUnitTest: task ':app:javaPreCompileDebugUnitTest'
                   javaPreCompileProfile: task ':app:javaPreCompileProfile'
                   javaPreCompileProfileUnitTest: task ':app:javaPreCompileProfileUnitTest'
                   javaPreCompileRelease: task ':app:javaPreCompileRelease'
                   javaPreCompileReleaseUnitTest: task ':app:javaPreCompileReleaseUnitTest'
                   layout: org.gradle.api.internal.file.DefaultProjectLayout@39e981d5
                   libsDir: C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\build\app\libs
                   libsDirName: libs
                   lint: task ':app:lint'
                   lintDebug: task ':app:lintDebug'
                   lintProfile: task ':app:lintProfile'
                   lintRelease: task ':app:lintRelease'
                   lintVitalRelease: task ':app:lintVitalRelease'
                   logger: org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger@d3f5151
                   logging: org.gradle.internal.logging.services.DefaultLoggingManager@561f223b
                   mergeDebugAndroidTestAssets: task ':app:mergeDebugAndroidTestAssets'
                   mergeDebugAndroidTestJniLibFolders: task ':app:mergeDebugAndroidTestJniLibFolders'
                   mergeDebugAndroidTestResources: task ':app:mergeDebugAndroidTestResources'
                   mergeDebugAndroidTestShaders: task ':app:mergeDebugAndroidTestShaders'
                   mergeDebugAssets: task ':app:mergeDebugAssets'
                   mergeDebugJniLibFolders: task ':app:mergeDebugJniLibFolders'
                   mergeDebugResources: task ':app:mergeDebugResources'
                   mergeDebugShaders: task ':app:mergeDebugShaders'
                   mergeProfileAssets: task ':app:mergeProfileAssets'
                   mergeProfileJniLibFolders: task ':app:mergeProfileJniLibFolders'
                   mergeProfileResources: task ':app:mergeProfileResources'
                   mergeProfileShaders: task ':app:mergeProfileShaders'
                   mergeReleaseAssets: task ':app:mergeReleaseAssets'
                   mergeReleaseJniLibFolders: task ':app:mergeReleaseJniLibFolders'
                   mergeReleaseResources: task ':app:mergeReleaseResources'
                   mergeReleaseShaders: task ':app:mergeReleaseShaders'
                   mockableAndroidJar: task ':app:mockableAndroidJar'
                   modelRegistry: org.gradle.model.internal.registry.DefaultModelRegistry@5a4ed6f1
                   modelSchemaStore: org.gradle.model.internal.manage.schema.extract.DefaultModelSchemaStore@4c2fde24
                   module: org.gradle.api.internal.artifacts.ProjectBackedModule@160fb53d
                   name: app
                   normalization: org.gradle.normalization.internal.DefaultInputNormalizationHandler_Decorated@647a22c7
                   objects: org.gradle.api.internal.model.DefaultObjectFactory@5b11e030
                   org.gradle.jvmargs: -Xmx1536M
                   packageDebug: task ':app:packageDebug'
                   packageDebugAndroidTest: task ':app:packageDebugAndroidTest'
                   packageProfile: task ':app:packageProfile'
                   packageRelease: task ':app:packageRelease'
                   parent: root project 'android'
                   parentIdentifier: root project 'android'
                   path: :app
                   platformAttrExtractor: task ':app:platformAttrExtractor'
                   pluginManager: org.gradle.api.internal.plugins.DefaultPluginManager_Decorated@1168f0b4
                   plugins: [org.gradle.api.plugins.HelpTasksPlugin@7df1f3b4, com.android.build.gradle.api.AndroidBasePlugin@7530d31a, org.gradle.language.base.plugins.LifecycleBasePlugin@75728a86, org.gradle.api.plugins.BasePlugin@ab28433, org.gradle.api.plugins.ReportingBasePlugin@7946249c, org.gradle.platform.base.plugins.ComponentBasePlugin@63cff10f, org.gradle.language.base.plugins.LanguageBasePlugin@2be54b2e, org.gradle.platform.base.plugins.BinaryBasePlugin@56fe6291, org.gradle.api.plugins.JavaBasePlugin@281668f8, com.android.build.gradle.internal.coverage.JacocoPlugin@7742e049, com.android.build.gradle.AppPlugin@4cd462ae, FlutterPlugin@7b393c87]
                   preBuild: task ':app:preBuild'
                   preDebugAndroidTestBuild: task ':app:preDebugAndroidTestBuild'
                   preDebugBuild: task ':app:preDebugBuild'
                   preDebugUnitTestBuild: task ':app:preDebugUnitTestBuild'
                   preProfileBuild: task ':app:preProfileBuild'
                   preProfileUnitTestBuild: task ':app:preProfileUnitTestBuild'
                   preReleaseBuild: task ':app:preReleaseBuild'
                   preReleaseUnitTestBuild: task ':app:preReleaseUnitTestBuild'
                   prepareLintJar: task ':app:prepareLintJar'
                   processDebugAndroidTestJavaRes: task ':app:processDebugAndroidTestJavaRes'
                   processDebugAndroidTestManifest: task ':app:processDebugAndroidTestManifest'
                   processDebugAndroidTestResources: task ':app:processDebugAndroidTestResources'
                   processDebugJavaRes: task ':app:processDebugJavaRes'
                   processDebugManifest: task ':app:processDebugManifest'
                   processDebugResources: task ':app:processDebugResources'
                   processDebugUnitTestJavaRes: task ':app:processDebugUnitTestJavaRes'
                   processOperations: org.gradle.api.internal.file.DefaultFileOperations@48fbd4c7
                   processProfileJavaRes: task ':app:processProfileJavaRes'
                   processProfileManifest: task ':app:processProfileManifest'
                   processProfileResources: task ':app:processProfileResources'
                   processProfileUnitTestJavaRes: task ':app:processProfileUnitTestJavaRes'
                   processReleaseJavaRes: task ':app:processReleaseJavaRes'
                   processReleaseManifest: task ':app:processReleaseManifest'
                   processReleaseResources: task ':app:processReleaseResources'
                   processReleaseUnitTestJavaRes: task ':app:processReleaseUnitTestJavaRes'
                   project: project ':app'
                   projectConfigurator: org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator@3ec90658
                   projectDir: C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\android\app
                   projectEvaluationBroadcaster: ProjectEvaluationListener broadcast
                   projectEvaluator: org.gradle.configuration.project.LifecycleProjectEvaluator@121cb62e
                   projectPath: :app
                   projectRegistry: org.gradle.api.internal.project.DefaultProjectRegistry@2745d2b0
                   properties: {...}
                   providers: org.gradle.api.internal.provider.DefaultProviderFactory@2007ece3
                   reporting: org.gradle.api.reporting.ReportingExtension_Decorated@71fe7bbc
                   reportsDir: C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\build\app\reports
                   repositories: repository container
                   resolveConfigAttr: task ':app:resolveConfigAttr'
                   resources: org.gradle.api.internal.resources.DefaultResourceHandler@7f3581d
                   rootDir: C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\android
                   rootProject: root project 'android'
                   scriptHandlerFactory: org.gradle.api.internal.initialization.DefaultScriptHandlerFactory@7029330b
                   scriptPluginFactory: org.gradle.configuration.ScriptPluginFactorySelector@7970bfec
                   serviceRegistryFactory: org.gradle.internal.service.scopes.ProjectScopeServices$4@7b5118e5
                   services: ProjectScopeServices
                   signingReport: task ':app:signingReport'
                   sourceCompatibility: 1.8
                   sourceSets: SourceSet container
                   splitsDiscoveryTaskDebug: task ':app:splitsDiscoveryTaskDebug'
                   splitsDiscoveryTaskDebugAndroidTest: task ':app:splitsDiscoveryTaskDebugAndroidTest'
                   splitsDiscoveryTaskProfile: task ':app:splitsDiscoveryTaskProfile'
                   splitsDiscoveryTaskRelease: task ':app:splitsDiscoveryTaskRelease'
                   standardOutputCapture: org.gradle.internal.logging.services.DefaultLoggingManager@561f223b
                   state: project state 'EXECUTED'
                   status: integration
                   subprojects: []
                   targetCompatibility: 1.8
                   tasks: task set
                   test: task ':app:test'
                   testDebugUnitTest: task ':app:testDebugUnitTest'
                   testProfileUnitTest: task ':app:testProfileUnitTest'
                   testReleaseUnitTest: task ':app:testReleaseUnitTest'
                   testReportDir: C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\build\app\reports\tests
                   testReportDirName: tests
                   testResultsDir: C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\build\app\test-results
                   testResultsDirName: test-results
                   transformClassesWithDexBuilderForDebug: task ':app:transformClassesWithDexBuilderForDebug'
                   transformClassesWithDexBuilderForDebugAndroidTest: task ':app:transformClassesWithDexBuilderForDebugAndroidTest'
                   transformClassesWithDexBuilderForProfile: task ':app:transformClassesWithDexBuilderForProfile'
                   transformClassesWithPreDexForRelease: task ':app:transformClassesWithPreDexForRelease'
                   transformDexArchiveWithDexMergerForDebug: task ':app:transformDexArchiveWithDexMergerForDebug'
                   transformDexArchiveWithDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithDexMergerForDebugAndroidTest'
                   transformDexArchiveWithDexMergerForProfile: task ':app:transformDexArchiveWithDexMergerForProfile'
                   transformDexArchiveWithExternalLibsDexMergerForDebug: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'
                   transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'
                   transformDexArchiveWithExternalLibsDexMergerForProfile: task ':app:transformDexArchiveWithExternalLibsDexMergerForProfile'
                   transformDexWithDexForRelease: task ':app:transformDexWithDexForRelease'
                   transformNativeLibsWithMergeJniLibsForDebug: task ':app:transformNativeLibsWithMergeJniLibsForDebug'
                   transformNativeLibsWithMergeJniLibsForDebugAndroidTest: task ':app:transformNativeLibsWithMergeJniLibsForDebugAndroidTest'
                   transformNativeLibsWithMergeJniLibsForProfile: task ':app:transformNativeLibsWithMergeJniLibsForProfile'
                   transformNativeLibsWithMergeJniLibsForRelease: task ':app:transformNativeLibsWithMergeJniLibsForRelease'
                   transformResourcesWithMergeJavaResForDebug: task ':app:transformResourcesWithMergeJavaResForDebug'
                   transformResourcesWithMergeJavaResForDebugAndroidTest: task ':app:transformResourcesWithMergeJavaResForDebugAndroidTest'
                   transformResourcesWithMergeJavaResForDebugUnitTest: task ':app:transformResourcesWithMergeJavaResForDebugUnitTest'
                   transformResourcesWithMergeJavaResForProfile: task ':app:transformResourcesWithMergeJavaResForProfile'
                   transformResourcesWithMergeJavaResForProfileUnitTest: task ':app:transformResourcesWithMergeJavaResForProfileUnitTest'
                   transformResourcesWithMergeJavaResForRelease: task ':app:transformResourcesWithMergeJavaResForRelease'
                   transformResourcesWithMergeJavaResForReleaseUnitTest: task ':app:transformResourcesWithMergeJavaResForReleaseUnitTest'
                   uninstallAll: task ':app:uninstallAll'
                   uninstallDebug: task ':app:uninstallDebug'
                   uninstallDebugAndroidTest: task ':app:uninstallDebugAndroidTest'
                   uninstallProfile: task ':app:uninstallProfile'
                   uninstallRelease: task ':app:uninstallRelease'
                   validateSigningDebug: task ':app:validateSigningDebug'
                   validateSigningDebugAndroidTest: task ':app:validateSigningDebugAndroidTest'
                   validateSigningProfile: task ':app:validateSigningProfile'
                   validateSigningRelease: task ':app:validateSigningRelease'
                   version: unspecified
                   writeDebugApplicationId: task ':app:writeDebugApplicationId'
                   writeProfileApplicationId: task ':app:writeProfileApplicationId'
                   writeReleaseApplicationId: task ':app:writeReleaseApplicationId'

                   BUILD SUCCESSFUL in 1s
                   1 actionable task: 1 executed
[  +37 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\build-tools\28.0.1\aapt dump badging build\app\outputs\apk\app.apk
[  +24 ms] Exit code 0 from: C:\Users\seenickcode\AppData\Local\Android\Sdk\build-tools\28.0.1\aapt dump badging build\app\outputs\apk\app.apk
[   +8 ms] package: name='com.example.lesson05' versionCode='1' versionName='1.0'
           sdkVersion:'16'
           targetSdkVersion:'27'
           uses-permission: name='android.permission.INTERNET'
           application-label:'lesson05'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='lesson05' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.example.lesson05.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales: '--_--'
           densities: '160' '240' '320' '480' '640'
           native-code: 'armeabi-v7a' 'x86' 'x86_64'
[  +30 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb -s 192.168.65.101:5555 logcat -v time -t 1
[ +118 ms] Exit code 0 from: C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb -s 192.168.65.101:5555 logcat -v time -t 1
[   +3 ms] --------- beginning of main
           08-22 12:51:00.189 I/logcat  ( 2199): type=1400 audit(0.0:1616): avc: denied { connectto } for path="/dev/socket/logdr" scontext=u:r:logpersist:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1
[  +13 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb -s 192.168.65.101:5555 logcat -v time
[ +396 ms] DependencyChecker: nothing is modified after 2018-08-22 08:41:00.000.
[   +7 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb version
[  +29 ms] Android Debug Bridge version 1.0.40
           Version 4797878
           Installed as C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb.EXE
[   +5 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb start-server
[  +27 ms] Building APK
[  +10 ms] Running 'gradlew assembleDebug'...
[   +3 ms] [android\] C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\android\gradlew.bat -Ptarget=C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\lib/main.dart -Ppreview-dart-2=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1801 ms] :app:preBuild UP-TO-DATE
[   +7 ms] :app:preDebugBuild UP-TO-DATE
[  +10 ms] :app:compileDebugAidl UP-TO-DATE
[   +1 ms] :app:compileDebugRenderscript UP-TO-DATE
[   +9 ms] :app:flutterBuildX86Jar UP-TO-DATE
[   +3 ms] :app:checkDebugManifest UP-TO-DATE
[   +5 ms] :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] :app:prepareLintJar UP-TO-DATE
[  +10 ms] :app:cleanMergeDebugAssets
[ +169 ms] :app:flutterBuildDebug UP-TO-DATE
[   +3 ms] :app:mergeDebugShaders UP-TO-DATE
[   +6 ms] :app:compileDebugShaders UP-TO-DATE
[   +2 ms] :app:generateDebugAssets UP-TO-DATE
[   +8 ms] :app:mergeDebugAssets
[ +316 ms] :app:copyFlutterAssetsDebug
[   +8 ms] :app:generateDebugResValues UP-TO-DATE
[   +1 ms] :app:generateDebugResources UP-TO-DATE
[   +3 ms] :app:mergeDebugResources UP-TO-DATE
[   +8 ms] :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +6 ms] :app:processDebugManifest UP-TO-DATE
[   +1 ms] :app:splitsDiscoveryTaskDebug UP-TO-DATE
[   +1 ms] :app:processDebugResources UP-TO-DATE
[   +2 ms] :app:generateDebugSources UP-TO-DATE
[   +8 ms] :app:javaPreCompileDebug UP-TO-DATE
[  +10 ms] :app:compileDebugJavaWithJavac UP-TO-DATE
[   +2 ms] :app:compileDebugNdk NO-SOURCE
[   +6 ms] :app:compileDebugSources UP-TO-DATE
[   +1 ms] :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[   +6 ms] :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
[   +3 ms] :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
[   +2 ms] :app:mergeDebugJniLibFolders UP-TO-DATE
[   +8 ms] :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
[   +2 ms] :app:processDebugJavaRes NO-SOURCE
[   +8 ms] :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
[   +2 ms] :app:validateSigningDebug
[  +19 ms] :app:packageDebug UP-TO-DATE
[   +8 ms] :app:assembleDebug UP-TO-DATE
[   +1 ms] BUILD SUCCESSFUL in 2s
[        ] 29 actionable tasks: 4 executed, 25 up-to-date
[ +510 ms] calculateSha: C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\build\app\outputs\apk/app.apk
[ +418 ms] Built build\app\outputs\apk\debug\app-debug.apk.
[   +3 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\build-tools\28.0.1\aapt dump badging build\app\outputs\apk\app.apk
[  +30 ms] Exit code 0 from: C:\Users\seenickcode\AppData\Local\Android\Sdk\build-tools\28.0.1\aapt dump badging build\app\outputs\apk\app.apk
[   +2 ms] package: name='com.example.lesson05' versionCode='1' versionName='1.0'
           sdkVersion:'16'
           targetSdkVersion:'27'
           uses-permission: name='android.permission.INTERNET'
           application-label:'lesson05'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='lesson05' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.example.lesson05.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales: '--_--'
           densities: '160' '240' '320' '480' '640'
           native-code: 'armeabi-v7a' 'x86' 'x86_64'
[   +6 ms] Stopping app 'app.apk' on Google Pixel 2, 8 0, API 26, 1080x1920.
[   +2 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb -s 192.168.65.101:5555 shell am force-stop com.example.lesson05
[ +178 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb -s 192.168.65.101:5555 shell pm list packages com.example.lesson05
[ +603 ms] package:com.example.lesson05
[   +5 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb -s 192.168.65.101:5555 shell cat /data/local/tmp/sky.com.example.lesson05.sha1
[  +70 ms] 83cb98fa05d0a8998124b3ec572023e6e41e2bdb
[  +14 ms] Latest build already installed.
[   +2 ms] Google Pixel 2, 8 0, API 26, 1080x1920 startApp
[  +13 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb -s 192.168.65.101:5555 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true com.example.lesson05/com.example.lesson05.MainActivity
[ +143 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.lesson05/.MainActivity (has extras) }
[  +12 ms] Waiting for observatory port to be available...
[ +602 ms] I/FlutterActivityDelegate( 2227): onResume setting current activity to this
[  +87 ms] Observatory URL on device: http://127.0.0.1:37459/
[  +12 ms] C:\Users\seenickcode\AppData\Local\Android\Sdk\platform-tools\adb -s 192.168.65.101:5555 forward tcp:8105 tcp:37459
[  +36 ms] Forwarded host port 8105 to device port 37459 for Observatory
[  +18 ms] Connecting to service protocol: http://127.0.0.1:8105/
[ +362 ms] Successfully connected to service protocol: http://127.0.0.1:8105/
[   +7 ms] getVM: {}
[  +35 ms] getIsolate: {isolateId: isolates/604683667}
[   +5 ms] _flutter.listViews: {isolateId: isolates/604683667}
[  +73 ms] DevFS: Creating new filesystem on the device (null)
[   +2 ms] _createDevFS: {fsName: lesson06}
[  +55 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.lesson05/cache/lesson06MDDBHM/lesson06/)
[   +5 ms] Updating assets
[ +295 ms] Syncing files to device Google Pixel 2, 8 0, API 26, 1080x1920...
[  +13 ms] DevFS: Starting sync from LocalDirectory: 'C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06'
[   +1 ms] Scanning project files
[   +7 ms] Scanning package files
[ +107 ms] Scanning asset files
[   +3 ms] Scanning for deleted files
[  +45 ms] Compiling dart to kernel with 421 updated files
[   +6 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build\app.dill --packages C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06\.packages --filesystem-scheme org-dartlang-root
[  +83 ms] D/        ( 2227): HostConnection::get() New Host Connection established 0xe76d7a80, tid 2245
[  +15 ms] W/        ( 2227): Unrecognized GLES max version string in extensions:
[  +20 ms] I/flutter ( 2227): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
[  +14 ms] I/flutter ( 2227): The following SocketException was thrown resolving an image codec:
[   +1 ms] I/flutter ( 2227): Failed host lookup: 'everydaydreamholiday.com' (OS Error: No address associated with hostname, errno
[        ] I/flutter ( 2227): = 7)
[  +36 ms] I/flutter ( 2227):
[   +2 ms] I/flutter ( 2227): When the exception was thrown, this was the stack:
[  +41 ms] I/flutter ( 2227): #0      NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:440:39)
[   +3 ms] I/flutter ( 2227): <asynchronous suspension>
[   +6 ms] I/flutter ( 2227): #1      NetworkImage.load (package:flutter/src/painting/image_provider.dart:425:14)
[   +1 ms] I/flutter ( 2227): #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:86)
[   +2 ms] I/flutter ( 2227): #3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82:22)
[   +6 ms] I/flutter ( 2227): #4      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:63)
[   +3 ms] I/flutter ( 2227): #5      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
[   +1 ms] I/flutter ( 2227): #6      ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:263:30)
[  +10 ms] I/flutter ( 2227): #7      _ImageState._resolveImage (package:flutter/src/widgets/image.dart:526:20)
[   +6 ms] I/flutter ( 2227): #8      _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:501:5)
[   +1 ms] I/flutter ( 2227): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3767:12)
[        ] I/flutter ( 2227): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +3 ms] I/flutter ( 2227): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[        ] I/flutter ( 2227): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[   +3 ms] I/flutter ( 2227): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +5 ms] I/flutter ( 2227): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +1 ms] I/flutter ( 2227): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +3 ms] I/flutter ( 2227): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +6 ms] I/flutter ( 2227): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +3 ms] I/flutter ( 2227): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #21     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4759:32)
[   +6 ms] I/flutter ( 2227): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +8 ms] I/flutter ( 2227): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter ( 2227): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +2 ms] I/flutter ( 2227): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +6 ms] I/flutter ( 2227): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +3 ms] I/flutter ( 2227): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +3 ms] I/flutter ( 2227): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +6 ms] I/flutter ( 2227): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[        ] I/flutter ( 2227): #34     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3955:11)
[   +4 ms] I/flutter ( 2227): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +4 ms] I/flutter ( 2227): #36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4759:32)
[   +1 ms] I/flutter ( 2227): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +3 ms] I/flutter ( 2227): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +6 ms] I/flutter ( 2227): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +3 ms] I/flutter ( 2227): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +1 ms] I/flutter ( 2227): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +6 ms] I/flutter ( 2227): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +3 ms] I/flutter ( 2227): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter ( 2227): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +2 ms] I/flutter ( 2227): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +6 ms] I/flutter ( 2227): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +1 ms] I/flutter ( 2227): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +3 ms] I/flutter ( 2227): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +4 ms] I/flutter ( 2227): #55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +6 ms] I/flutter ( 2227): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +1 ms] I/flutter ( 2227): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[        ] I/flutter ( 2227): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +2 ms] I/flutter ( 2227): #59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[   +6 ms] I/flutter ( 2227): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +2 ms] I/flutter ( 2227): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +7 ms] I/flutter ( 2227): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +2 ms] I/flutter ( 2227): #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +6 ms] I/flutter ( 2227): #65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +3 ms] I/flutter ( 2227): #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +7 ms] I/flutter ( 2227): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +3 ms] I/flutter ( 2227): #68     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[   +1 ms] I/flutter ( 2227): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +6 ms] I/flutter ( 2227): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +3 ms] I/flutter ( 2227): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +6 ms] I/flutter ( 2227): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +3 ms] I/flutter ( 2227): #74     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +1 ms] I/flutter ( 2227): #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +6 ms] I/flutter ( 2227): #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +9 ms] I/flutter ( 2227): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +5 ms] I/flutter ( 2227): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[  +11 ms] I/flutter ( 2227): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +9 ms] I/flutter ( 2227): #81     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +5 ms] I/flutter ( 2227): #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +1 ms] I/flutter ( 2227): #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +3 ms] I/flutter ( 2227): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +2 ms] I/flutter ( 2227): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +6 ms] I/flutter ( 2227): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +3 ms] I/flutter ( 2227): #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +6 ms] I/flutter ( 2227): #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +1 ms] I/flutter ( 2227): #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +9 ms] I/flutter ( 2227): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +3 ms] I/flutter ( 2227): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +8 ms] I/flutter ( 2227): #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +7 ms] I/flutter ( 2227): #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +1 ms] I/flutter ( 2227): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +3 ms] I/flutter ( 2227): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +1 ms] I/flutter ( 2227): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +6 ms] I/flutter ( 2227): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +8 ms] I/flutter ( 2227): #99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[        ] I/flutter ( 2227): #100    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +1 ms] I/flutter ( 2227): #101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +1 ms] I/flutter ( 2227): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +2 ms] I/flutter ( 2227): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +3 ms] I/flutter ( 2227): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +4 ms] I/flutter ( 2227): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[        ] I/flutter ( 2227): #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[        ] I/flutter ( 2227): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[        ] I/flutter ( 2227): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +1 ms] I/flutter ( 2227): #110    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[        ] I/flutter ( 2227): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +8 ms] I/flutter ( 2227): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[        ] I/flutter ( 2227): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter ( 2227): #114    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter ( 2227): #115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[        ] I/flutter ( 2227): #116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +7 ms] I/flutter ( 2227): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[        ] I/flutter ( 2227): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[        ] I/flutter ( 2227): #119    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[        ] I/flutter ( 2227): #120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[        ] I/flutter ( 2227): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +9 ms] I/flutter ( 2227): #122    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[   +1 ms] I/flutter ( 2227): #123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[        ] I/flutter ( 2227): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +1 ms] I/flutter ( 2227): #125    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[        ] I/flutter ( 2227): #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +1 ms] I/flutter ( 2227): #128    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[   +1 ms] I/flutter ( 2227): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +4 ms] I/flutter ( 2227): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter ( 2227): #133    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +1 ms] I/flutter ( 2227): #134    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +4 ms] I/flutter ( 2227): #135    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +6 ms] I/flutter ( 2227): #136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +3 ms] I/flutter ( 2227): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +5 ms] I/flutter ( 2227): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter ( 2227): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter ( 2227): #140    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[ +520 ms] I/flutter ( 2227): #141    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +2 ms] I/flutter ( 2227): #142    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +6 ms] I/flutter ( 2227): #143    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +5 ms] I/flutter ( 2227): #144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[  +10 ms] I/flutter ( 2227): #145    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter ( 2227): #146    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +6 ms] I/flutter ( 2227): #147    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[        ] I/flutter ( 2227): #148    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +3 ms] I/flutter ( 2227): #149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +6 ms] I/flutter ( 2227): #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +1 ms] I/flutter ( 2227): #151    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[  +11 ms] I/flutter ( 2227): #152    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +5 ms] I/flutter ( 2227): #153    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +7 ms] I/flutter ( 2227): #154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +3 ms] I/flutter ( 2227): #155    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #156    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[  +10 ms] I/flutter ( 2227): #157    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +5 ms] I/flutter ( 2227): #158    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +7 ms] I/flutter ( 2227): #159    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #160    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[   +1 ms] I/flutter ( 2227): #161    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +2 ms] I/flutter ( 2227): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[  +11 ms] I/flutter ( 2227): #163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #164    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[  +14 ms] I/flutter ( 2227): #165    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +1 ms] I/flutter ( 2227): #166    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +8 ms] I/flutter ( 2227): #167    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[  +10 ms] I/flutter ( 2227): #168    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #169    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +4 ms] I/flutter ( 2227): #171    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #172    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[  +11 ms] I/flutter ( 2227): #173    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +5 ms] I/flutter ( 2227): #174    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +2 ms] I/flutter ( 2227): #175    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +3 ms] I/flutter ( 2227): #176    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[   +7 ms] I/flutter ( 2227): #177    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[  +12 ms] I/flutter ( 2227): #178    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +1 ms] I/flutter ( 2227): #179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #180    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter ( 2227): #181    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[        ] I/flutter ( 2227): #182    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[        ] I/flutter ( 2227): #183    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #184    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[  +12 ms] I/flutter ( 2227): #186    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #187    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +9 ms] I/flutter ( 2227): #188    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +5 ms] I/flutter ( 2227): #189    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +1 ms] I/flutter ( 2227): #190    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +3 ms] I/flutter ( 2227): #191    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +1 ms] I/flutter ( 2227): #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +6 ms] I/flutter ( 2227): #193    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +5 ms] I/flutter ( 2227): #194    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +2 ms] I/flutter ( 2227): #195    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +6 ms] I/flutter ( 2227): #196    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +8 ms] I/flutter ( 2227): #197    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #198    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4759:32)
[   +1 ms] I/flutter ( 2227): #199    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[  +10 ms] I/flutter ( 2227): #200    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +4 ms] I/flutter ( 2227): #201    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
[   +1 ms] I/flutter ( 2227): #202    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +6 ms] I/flutter ( 2227): #203    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +9 ms] I/flutter ( 2227): #204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #205    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +3 ms] I/flutter ( 2227): #206    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +7 ms] I/flutter ( 2227): #207    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[        ] I/flutter ( 2227): #208    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +3 ms] I/flutter ( 2227): #209    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #210    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +8 ms] I/flutter ( 2227): #212    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #213    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[        ] I/flutter ( 2227): #214    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +3 ms] I/flutter ( 2227): #215    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +6 ms] I/flutter ( 2227): #216    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +2 ms] I/flutter ( 2227): #217    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[   +6 ms] I/flutter ( 2227): #218    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #219    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[        ] I/flutter ( 2227): #220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +3 ms] I/flutter ( 2227): #221    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #222    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +6 ms] I/flutter ( 2227): #223    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +3 ms] I/flutter ( 2227): #224    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +1 ms] I/flutter ( 2227): #225    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +6 ms] I/flutter ( 2227): #226    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +9 ms] I/flutter ( 2227): #227    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[   +3 ms] I/flutter ( 2227): #228    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #229    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #230    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[   +9 ms] I/flutter ( 2227): #231    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #232    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +3 ms] I/flutter ( 2227): #233    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #234    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +6 ms] I/flutter ( 2227): #235    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +3 ms] I/flutter ( 2227): #236    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +5 ms] I/flutter ( 2227): #237    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +1 ms] I/flutter ( 2227): #238    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #239    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +3 ms] I/flutter ( 2227): #240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +7 ms] I/flutter ( 2227): #241    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +3 ms] I/flutter ( 2227): #242    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +1 ms] I/flutter ( 2227): #243    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +6 ms] I/flutter ( 2227): #244    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #245    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +9 ms] I/flutter ( 2227): #246    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[   +1 ms] I/flutter ( 2227): #247    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +3 ms] I/flutter ( 2227): #248    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +1 ms] I/flutter ( 2227): #249    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +6 ms] I/flutter ( 2227): #250    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +3 ms] I/flutter ( 2227): #251    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +1 ms] I/flutter ( 2227): #252    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +6 ms] I/flutter ( 2227): #253    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +3 ms] I/flutter ( 2227): #254    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +7 ms] I/flutter ( 2227): #255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +2 ms] I/flutter ( 2227): #256    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #257    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +6 ms] I/flutter ( 2227): #258    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +3 ms] I/flutter ( 2227): #259    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +6 ms] I/flutter ( 2227): #260    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +1 ms] I/flutter ( 2227): #261    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter ( 2227): #262    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +3 ms] I/flutter ( 2227): #263    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +5 ms] I/flutter ( 2227): #264    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[        ] I/flutter ( 2227): #265    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +8 ms] I/flutter ( 2227): #266    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +2 ms] I/flutter ( 2227): #267    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +2 ms] I/flutter ( 2227): #268    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #269    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +9 ms] I/flutter ( 2227): #270    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +1 ms] I/flutter ( 2227): #271    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +6 ms] I/flutter ( 2227): #272    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[        ] I/flutter ( 2227): #273    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +3 ms] I/flutter ( 2227): #274    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +6 ms] I/flutter ( 2227): #275    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[        ] I/flutter ( 2227): #276    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[        ] I/flutter ( 2227): #277    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +2 ms] I/flutter ( 2227): #278    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #279    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
[        ] I/flutter ( 2227): #280    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +2 ms] I/flutter ( 2227): #281    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #282    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter ( 2227): #283    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter ( 2227): #284    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +2 ms] I/flutter ( 2227): #285    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +5 ms] I/flutter ( 2227): #286    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[        ] I/flutter ( 2227): #287    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[ +379 ms] I/flutter ( 2227): #288    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +3 ms] I/flutter ( 2227): #289    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +6 ms] I/flutter ( 2227): #290    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter ( 2227): #291    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +3 ms] I/flutter ( 2227): #292    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[  +11 ms] I/flutter ( 2227): #293    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +7 ms] I/flutter ( 2227): #294    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +3 ms] I/flutter ( 2227): #295    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #296    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +6 ms] I/flutter ( 2227): #297    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +9 ms] I/flutter ( 2227): #298    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[   +1 ms] I/flutter ( 2227): #299    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +3 ms] I/flutter ( 2227): #300    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +1 ms] I/flutter ( 2227): #301    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #302    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +8 ms] I/flutter ( 2227): #303    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #304    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +1 ms] I/flutter ( 2227): #305    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +3 ms] I/flutter ( 2227): #306    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +6 ms] I/flutter ( 2227): #307    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +1 ms] I/flutter ( 2227): #308    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +7 ms] I/flutter ( 2227): #309    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter ( 2227): #310    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[        ] I/flutter ( 2227): #311    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[        ] I/flutter ( 2227): #312    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +2 ms] I/flutter ( 2227): #313    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[   +6 ms] I/flutter ( 2227): #314    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter ( 2227): #315    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter ( 2227): #316    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +8 ms] I/flutter ( 2227): #317    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[        ] I/flutter ( 2227): #318    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[        ] I/flutter ( 2227): #319    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[        ] I/flutter ( 2227): #320    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter ( 2227): #321    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter ( 2227): #322    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +1 ms] I/flutter ( 2227): #323    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[        ] I/flutter ( 2227): #324    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[   +1 ms] I/flutter ( 2227): #325    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[   +8 ms] I/flutter ( 2227): #326    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[        ] I/flutter ( 2227): #327    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter ( 2227): #328    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter ( 2227): #329    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[   +8 ms] I/flutter ( 2227): #330    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[        ] I/flutter ( 2227): #331    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[        ] I/flutter ( 2227): #332    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[        ] I/flutter ( 2227): #333    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter ( 2227): #334    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter ( 2227): #335    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
[        ] I/flutter ( 2227): #336    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
[        ] I/flutter ( 2227): #337    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
[        ] I/flutter ( 2227): #338    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
[        ] I/flutter ( 2227): #339    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
[        ] I/flutter ( 2227): #340    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
[        ] I/flutter ( 2227): #341    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
[        ] I/flutter ( 2227): #342    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
[        ] I/flutter ( 2227): #343    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
[   +8 ms] I/flutter ( 2227): #344    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
[        ] I/flutter ( 2227): #345    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
[        ] I/flutter ( 2227): #346    runApp (package:flutter/src/widgets/binding.dart:704:7)
[        ] I/flutter ( 2227): #347    main (file:///C:/Users/seenickcode/code/fluttercrashcourse-lessons/recipe01-product-detail-pages/lesson06/lib/main.dart:8:10)
[   +8 ms] I/flutter ( 2227): #348    _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
[   +1 ms] I/flutter ( 2227): #349    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
[        ] I/flutter ( 2227):
[        ] I/flutter ( 2227): Image provider:
[        ] I/flutter ( 2227): NetworkImage("http://everydaydreamholiday.com/wp-content/uploads/2013/01/Arashiyama-bamboo-grove-path_kyoto_japan.jpg",
[        ] I/flutter ( 2227): scale: 1.0)
[        ] I/flutter ( 2227): Image key:
[        ] I/flutter ( 2227): NetworkImage("http://everydaydreamholiday.com/wp-content/uploads/2013/01/Arashiyama-bamboo-grove-path_kyoto_japan.jpg",
[   +1 ms] I/flutter ( 2227): scale: 1.0)
[        ] I/flutter ( 2227): ════════════════════════════════════════════════════════════════════════════════════════════════════
[+3324 ms] Updating files
[+1126 ms] DevFS: Sync finished
[   +8 ms] Synced 0.8MB.
[   +2 ms] _flutter.listViews: {isolateId: isolates/604683667}
[  +18 ms] Connected to _flutterView/0xf0a34dcc.
[   +3 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +3 ms] An Observatory debugger and profiler on Google Pixel 2, 8 0, API 26, 1080x1920 is available at: http://127.0.0.1:8105/
[   +8 ms] For a more detailed help message, press "h". To quit, press "q".
```

Flutter analyze:

```
C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06>flutter analyze
Analyzing lesson06...

   info - Unused import: 'package:lesson05/main.dart' - test\widget_test.dart:10:8
  error - The constructor returns type 'dynamic' that isn't of expected type 'Widget' - test\widget_test.dart:15:29
  error - Undefined class 'MyApp' - test\widget_test.dart:15:33

3 issues found. (ran in 2.3s)```
```

Flutter doctor:

```

C:\Users\seenickcode\code\fluttercrashcourse-lessons\recipe01-product-detail-pages\lesson06>flutter doctor -v
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
    • Flutter version 0.5.1 at C:\src\flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\seenickcode\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = C:\Users\seenickcode\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Google Pixel 2, 8 0, API 26, 1080x1920 • 192.168.65.101:5555 • android-x86 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

### LINKED ISSUE #25227: ImageProvider.resolve can throw synchronously
`instantiateImageCodec` from `dart:ui` returns a `Future` that doesn't conform to the `Future` contract as it's implemented using a `Completer<T>.sync`.

As a result of this, `ImageProvider.resolve` can end up throwing synchronously instead of invoking the `ImageErrorListener` of the `ImageStreamCompleter`. I suspect this happens because `_loadAsync` is an `async` function, which attempts to `await` on a `Future` from `instantiateImageCodec`.

From the `Completer<T>.sync` docs:

> For that reason, a synchronous completion must only occur at the very end (in "tail position") of another synchronous event [...]

`_loadAsync` is not a "synchronous event", so completing the "weird" future from `instantiateImageCodec` breaks the `async-await` contract, and instead propages the exception synchronously into the `_loadAsync` caller which is the `resolve`

This happens in cases when e.g. `Network.image` caches malformed binary data, in which case synchronous instantiation of the `Codec` ends up failing the `resolve` caller with an exception.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Add an `onError` parameter to the ImageCache.putIfAbsent method. In the event that an error is thrown when resolving an image, catch if this parameter is provided. Use the onError parameter to ensure that all errors thrown are forwarded to the ImageStream error channel instead of directly into the void.

Fixes https://github.com/flutter/flutter/issues/25227
Fixes https://github.com/flutter/flutter/issues/20910

### CODE REVIEW

File: packages/flutter/lib/src/painting/image_provider.dart [hunk 1]
```diff
@@ -262,27 +262,31 @@ abstract class ImageProvider<T> {
     assert(configuration != null);
     final ImageStream stream = ImageStream();
     T obtainedKey;
+    Future<void> handleError(dynamic exception, StackTrace stack) async {
+      await null; // wait an event turn in case a listener has been added to the image stream.
+      final _ErrorImageCompleter imageCompleter = _ErrorImageCompleter();
+      stream.setCompleter(imageCompleter);
+      imageCompleter.reportError( // ignore: invalid_use_of_protected_member
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/image_provider.dart]: The ignore seems fishy. Should the private subclass _ErrorImageCompleter just expose some form of reportError as public? Or could all these things be passed into the constructor and it internally calls reportError or something like that?

File: packages/flutter/lib/src/painting/image_provider.dart [hunk 2]
```diff
@@ -773,3 +777,8 @@ class ExactAssetImage extends AssetBundleImageProvider {
   @override
   String toString() => '$runtimeType(name: "$keyName", scale: $scale, bundle: $bundle)';
 }
+
+// A completer used when resolving an image completes
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/image_provider.dart]: The doc comment seems incomplete.

File: packages/flutter/lib/src/painting/image_provider.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/painting/image_provider.dart]: Yes, I could just add a new method to the _ErrorImageCompleter - will do that instead

**Review by goderbauer — APPROVED** [review]
LGTM
