### PR TITLE
Multiline Selection Menu Position Bug

### LINKED ISSUE #36749: Copy and Paste controls position in textfield widget display  is abnormal
It is always displayed at the top

Screenshot_1563874231

It is not displayed when I selected text at the bottom. So I have no way to copy and paste.

Screenshot_1563874414

It works fine in version 1.5.4, this problem occurred after I upgraded the version.

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.7.8+hotfix.3 at /home/xia/develop/flutter/flutter
    • Framework revision b712a172f9 (2 周前), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/xia/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at:
      /home/xia/develop/tool/android-studio-ide-181.5014246-linux/android-studio
      /jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at
      /home/xia/develop/tool/android-studio-ide-181.5014246-linux/android-studio
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /home/xia/develop/tool/ideaIU-2019.1.1/idea-IU-191.6707.61
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.36.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by justinmc**
## Description

The selection menu is showing up in the wrong place for multiline inputs in Material.

## Related Issues

Closes https://github.com/flutter/flutter/issues/36749

## Tests

Wrote a multiline input test that checks the position of the selection menu.

### CODE REVIEW

**Comment by justinmc** [comment]
@LongCatIsLooong Requesting a review from you because of your recent cleanup of the Cupertino text selection postioning code (https://github.com/flutter/flutter/pull/34095).  Cupertino's behavior seems perfect after your PR, but apparently Material's was still buggy.  I tried to copy your approach a bit for Material, let me know what you think or if I missed anything though.

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 1]
```diff
@@ -305,11 +305,12 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
     // The toolbar should appear below the TextField when there is not enough
     // space above the TextField to show it, assuming there's always enough space
     // at the bottom in this case.
-    final bool isArrowPointingDown =
-      mediaQuery.padding.top
+    final double toolbarHeightNeeded = mediaQuery.padding.top
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_selection.dart]: :+1:

File: packages/flutter/lib/src/material/text_selection.dart [hunk 2]
```diff
@@ -158,11 +160,14 @@ class _MaterialTextSelectionControls extends TextSelectionControls {
...
         ? startTextSelectionPoint.point.dx
         : (startTextSelectionPoint.point.dx + endTextSelectionPoint.point.dx) / 2.0;
-    final double availableHeight
-        = globalEditableRegion.top - MediaQuery.of(context).padding.top - _kToolbarScreenPadding;
-    final double y = (availableHeight < _kToolbarHeight)
-        ? startTextSelectionPoint.point.dy + globalEditableRegion.height + _kToolbarHeight + _kToolbarScreenPadding
-        : startTextSelectionPoint.point.dy - globalEditableRegion.height;
+    final double toolbarHeightNeeded = MediaQuery.of(context).padding.top
+      + _kToolbarScreenPadding
+      + _kToolbarHeight;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/text_selection.dart]: Is there supposed to be a non-zero content padding (between the paragraph and the bottom of the toolbar)?

File: packages/flutter/lib/src/material/text_selection.dart [hunk 3]
```diff
@@ -158,11 +160,14 @@ class _MaterialTextSelectionControls extends TextSelectionControls {
...
+    final double availableHeight = globalEditableRegion.top + endpoints.first.point.dy - textLineHeight;
+    final bool fitsAbove = toolbarHeightNeeded <= availableHeight;
+    final double y = fitsAbove
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/text_selection.dart]: The comment here
https://github.com/flutter/flutter/blob/9be3399fb59347a8e2bfdfd9cd17814456c089f3/packages/flutter/lib/src/material/text_selection.dart#L81-L83
Makes it really confusing. I guess instead of anchor it should say bottom left? And the fact that we use bottom left instead of top left sounds strange to me too.

File: packages/flutter/lib/src/material/text_selection.dart [hunk 4]
```diff
@@ -158,11 +160,14 @@ class _MaterialTextSelectionControls extends TextSelectionControls {
...
+        ? startTextSelectionPoint.point.dy - textLineHeight
+        : startTextSelectionPoint.point.dy + _kToolbarHeight + _kToolbarContentDistanceBelow;
     final Offset preciseMidpoint = Offset(x, y);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/material/text_selection.dart]: Not really related to the issue, but I think `x` is already calculated in `TextSelectionOverlay._buildToolbar`. Instead of doing it here again maybe just use `position.dx`?

File: packages/flutter/lib/src/material/text_selection.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: It doesn't seem so looking at the code, but looking at native apps it seems like there should be.  I'll add in a `_kToolbarContentDistance` like in iOS.  It may break golden/scuba tests.

Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: After:

Screen Shot 2019-07-30 at 8 32 30 AM
Screen Shot 2019-07-30 at 8 32 56 AM

File: packages/flutter/lib/src/material/text_selection.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: I think the value passed in for position is where the center of the toolbar is drawn? If I pass in `0.0` for y, it draws the toolbar so that it's vertical midpoint is on the top of the textfield.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Yeah seems to be calculating the same exact value to me.  I'll change it.

File: packages/flutter/lib/src/material/text_selection.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/text_selection.dart]: in `_TextSelectionToolbarLayout.getPositionForChild` I think `_TextSelectionToolbarLayout.position` is used as the coordinate of the bottom left vertex of the toolbar, in global coordinate system.

Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Hmm I don't fully understand what that value is meant to be.  Do you think I should update the comment to something specific?  This is what I see when I set `position` to 0,0:

Screen Shot 2019-07-30 at 4 17 16 PM

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/text_selection.dart]: Ah sorry I was just ranting because it threw me off, It's not really related to this PR.

Comment (justinmc) [reply packages/flutter/lib/src/material/text_selection.dart]: Ok got it.  Yeah it's definitely confusing.

**Comment by justinmc** [comment]
Waiting on a goldens file update in https://github.com/flutter/goldens/pull/41

File: packages/flutter/test/material/text_field_test.dart [hunk 5]
```diff
@@ -1493,36 +1506,77 @@ void main() {
...
+      await skipPastScrollingAnimation(tester);
+
+      // Show the selection menu on the first line and verify the selection
+      // toolbar position is below the first line.
+      await _showSelectionMenuAt(tester, controller, testValue.indexOf('c'));
+      expect(find.text('SELECT ALL'), findsOneWidget);
+      final Offset firstLineToolbarTopLeft = tester.getTopLeft(find.text('SELECT ALL'));
+      final Offset firstLineTopLeft = textOffsetToPosition(tester, testValue.indexOf('a'));
+      expect(firstLineTopLeft.dy, lessThan(firstLineToolbarTopLeft.dy));
+      expect(firstLineToolbarTopLeft.dy, greaterThan(firstLineTopLeft.dy));
```
Comment (LongCatIsLooong) [inline packages/flutter/test/material/text_field_test.dart]: Is this line saying the same thing as the line above?

File: packages/flutter/test/material/text_field_test.dart [hunk 6]
```diff
@@ -1443,6 +1443,33 @@ void main() {
     expect(controller.text, 'abc d${testValue}ef ghi');
   });
 
+  // Show the selection menu at the given index into the text by tapping to
+  // place the cursor and then tapping on the handle.
+  Future<void> _showSelectionMenuAt(WidgetTester tester, TextEditingController controller, int index) async {
+    await tester.tapAt(tester.getCenter(find.byType(EditableText)));
+    await tester.pump();
+    await tester.pump(const Duration(milliseconds: 200)); // skip past the frame where the opacity is zero
+    await tester.pumpAndSettle();
```
Comment (LongCatIsLooong) [inline packages/flutter/test/material/text_field_test.dart]: Why do we need to pump a third time here?

**Review by LongCatIsLooong — APPROVED** [review]
LGTM!

File: packages/flutter/test/material/text_field_test.dart [hunk 7]
```diff
@@ -499,7 +499,7 @@ void main() {
       find.byType(Overlay),
       matchesGoldenFile(
         'text_field_opacity_test.0.png',
-        version: 2,
+        version: 3,
```
Comment (Piinks) [inline packages/flutter/test/material/text_field_test.dart]: 👍

**Review by Piinks — APPROVED** [review]
LGTM!

File: packages/flutter/test/material/text_field_test.dart (hunk 5 above)
Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart]: Yes, good catch!

File: packages/flutter/test/material/text_field_test.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart]: I tried it and it seems to be unnecessary, so I'll remove it.
