### PR TITLE
Do not replace text with semantics labels in selectable text widgets

### LINKED ISSUE #77779: Providing a semantic label in TextSpans inside a SelectableText.rich causes an exception on double-tap
<details>
<summary>The stack-trace</summary>

```bash
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following RangeError was thrown while handling a gesture:
RangeError (index): Invalid value: Valid value range is empty: 4

When the exception was thrown, this was the stack: 
#0      String.codeUnitAt (dart:core-patch/string_patch.dart:971:55)
#1      RenderEditable._selectWordAtOffset (package:flutter/src/rendering/editable.dart:1993:46)
#2      RenderEditable.selectWordsInRange (package:flutter/src/rendering/editable.dart:1940:37)
#3      RenderEditable.selectWord (package:flutter/src/rendering/editable.dart:1923:5)
#4      _SelectableTextSelectionGestureDetectorBuilder.onSingleLongTapStart (package:flutter/src/material/selectable_text.dart:106:22)
...
Handler: "onLongPressStart"
Recognizer: LongPressGestureRecognizer#f68d1
  debugOwner: _TextSelectionGestureDetectorState#09973
  state: possible
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

<details>
<summary>Code to reproduce the crash</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Hello'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            SelectableText.rich(
              // Setting the `semanticsLabel` to an empty-string will cause a crash if user long-press on the TextSpan
              TextSpan(
                text: 'testing', semanticsLabel: ''
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel dev, 1.26.0-17.2.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[!] Xcode - develop for iOS and macOS
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.53.2)
[✓] Connected device (4 available)
    ! Error: iPhone 8 (Google) is busy: Copying cache files from device. Xcode will continue when iPhone 8 (Google) is finished. (code -10)

! Doctor found issues in 1 category.
meiwin-imacpro:flutter_app_ecrash meiwin$ flutter doctor -v
[✓] Flutter (Channel dev, 1.26.0-17.2.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-SG)
    • Flutter version 1.26.0-17.2.pre at /Users/meiwin/development/flutter
    • Framework revision 79b49b9e10 (5 weeks ago), 2021-02-03 15:33:39 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/meiwin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
```
</details>

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/77779

### CODE REVIEW

File: packages/flutter/test/widgets/selectable_text_test.dart [hunk 1]
```diff
@@ -2815,6 +2815,37 @@ void main() {
...
+      await tester.pump();
+
+      final EditableText editableTextWidget = tester.widget(find.byType(EditableText).first);
+      final TextEditingController controller = editableTextWidget.controller;
+
+      expect(
+        controller.selection,
+        const TextSelection(baseOffset: 13, extentOffset: 23),
+      );
+  }, variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.iOS,  TargetPlatform.macOS }));
```
Comment (chunhtai) [inline packages/flutter/test/widgets/selectable_text_test.dart:2847]: why only test for macOS and iOS?

**Review by chunhtai — APPROVED** [review]
LGTM, one comment on test.

File: packages/flutter/test/widgets/selectable_text_test.dart (hunk 1 above)
Comment (jason-simmons) [reply packages/flutter/test/widgets/selectable_text_test.dart:2847]: This was done to be consistent with the other double tap tests in this file that were specifying macOS/iOS
