### PR TITLE
Include transform in static Gradient lerp methods

### LINKED ISSUE #149534: Gradient subclasses' static lerp methods drop the GradientTransform of both `a` and `b`
### Steps to reproduce

1. Construct a LinearGradient `a` with some arbitrary GradientTransform.
2. Construct a LinearGradient `b` with some other arbitrary GradientTransform or none.
3. Construct a third LinearGradient using the static LinearGradient.lerp() method, using any value for `t`.
4. Observe that the gradient created by the lerp method never has a GradientTransform of any kind. It neither has the transform of `a` when `t == 0.0` nor has the transform of `b` when `t == 1.0`.

### Expected results

While it's not too surprising to have no true unmatrix or decomposition that can accurately interpolate all `Matrix4`s, it at least stands to reason that the lerped result should at minimum have either of `a`'s or `b`'s transforms.

TileMode is handled by returning a.tileMode if t < 0.5 and b.tileMode otherwise. This should also be the case for transforms, in lieu of true interpolation.

### Actual results

The interpolated gradient has lost the original transform's of either (or both) `a` and `b`. This is also the case with RadialGradients and SweepGradients.

It can be plainly seen, in the [LinearGradient.lerp static method](https://github.com/flutter/flutter/blob/124aacbaef3ff0476f3a02c2ab05271e152224db/packages/flutter/lib/src/painting/gradient.dart#L504) for example, that the returned gradient object simply gets no `transform` argument:

```
return LinearGradient(
  begin: AlignmentGeometry.lerp(a.begin, b.begin, t)!,
  end: AlignmentGeometry.lerp(a.end, b.end, t)!,
  colors: interpolated.colors,
  stops: interpolated.stops,
  tileMode: t < 0.5 ? a.tileMode : b.tileMode, // TODO(ianh): interpolate tile mode
);
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

const colors = [Colors.red, Colors.blue, Colors.yellow],
    a = LinearGradient(colors: colors, transform: GradientRotation(1.57)),
    b = LinearGradient(colors: colors, transform: GradientRotation(2.36)),
    t = 0.0,
    kTickSec = 5;

/// The `lerp` gradient should be more-or-less identical to `a` when
/// `t == 0.0`; look like `b` when `t == 1.0`; and should at least have
/// the GradientTransform of either when `t` is any other value, such as
/// for TileMode:
///     transform: t < 0.5 ? a.transform : b.transform
final lerp = LinearGradient.lerp(a, b, t)!;

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({super.key});
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var index = 0;
  late Timer timer;

  void incrementGradient() =>
      mounted ? setState(() => index = (index == 2) ? 0 : index + 1) : null;

  @override
  void initState() {
    super.initState();
    timer = Timer.periodic(
        const Duration(seconds: kTickSec), (timer) => incrementGradient());
  }

  @override
  void dispose() {
    timer.cancel();
    super.dispose();
  }

  Gradient get gradient => switch (index) { 0 => a, 1 => b, _ => lerp };

  @override
  Widget build(BuildContext context) {
    final gradient = this.gradient;
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: DecoratedBox(
            decoration: BoxDecoration(gradient: gradient),
            child: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [
                  Center(
                      child: Text(
                          '$index\n${switch (index) {
                            0 => 'LinearGradient a',
                            1 => 'LinearGradient b',
                            _ =>
                              'LinearGradient.lerp(a, b, ${t.toStringAsFixed(1)})'
                          }}',
                          style: const TextStyle(fontSize: 40),
                          textAlign: TextAlign.center)),
                  Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 25),
                      child: Center(
                          child: Text(
                        '$gradient',
                        style: const TextStyle(fontSize: 20),
                      ))),
                  Center(
                      child: Text(
                    '${gradient.transform}',
                    style: const TextStyle(fontSize: 26),
                  )),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/65806473/de14e201-b1a7-44ba-95ff-e62587c7f6ac

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19045.4412], locale en-US)
    • Flutter version 3.22.1 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (10 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\src\android
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = C:\src\android
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34511.84
    • Windows 10 SDK version 10.0.20348.0

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] VS Code, 64-bit edition (version 1.89.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.89.20240501

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4412]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 124.0.6367.119
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.105

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by Zabadam**
*Fixes #149534 Gradient subclasses' static lerp methods drop the GradientTransform of both `a` and `b`*

LinearGradient.lerp(), RadialGradient.lerp() and SweepGradient.lerp() no longer drop the GradientTransform of `a` and/or `b`.

The primitive interpolation is performed the same way TileMode is handled:  `transform: t < 0.5 ? a.transform : b.transform`.

## Media

<details>
<summary>Video demonstration</summary>

### Before
https://github.com/flutter/flutter/assets/65806473/de14e201-b1a7-44ba-95ff-e62587c7f6ac

### After
https://github.com/flutter/flutter/assets/65806473/d48f40e2-1b0f-4ac8-a45c-b3c423e3fd64

</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
  - Changed no documentation.
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
  - Non-breaking change.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter/lib/src/painting/gradient.dart [hunk 1]
```diff
@@ -507,6 +507,7 @@ class LinearGradient extends Gradient {
       colors: interpolated.colors,
       stops: interpolated.stops,
       tileMode: t < 0.5 ? a.tileMode : b.tileMode, // TODO(ianh): interpolate tile mode
+      transform: t < 0.5 ? a.transform : b.transform,
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/gradient.dart:510]: not a big deal, but if you feel like it, you could remove the TODO on the line above (or alternatively, add one on the new line, with a link to https://github.com/flutter/flutter/issues/443)

(same for all three gradients)

**Review by Hixie — APPROVED** [review]
LGTM

File: packages/flutter/test/painting/gradient_test.dart [hunk 2]
```diff
@@ -191,6 +191,32 @@ void main() {
...
+      ],
+      stops: <double>[0, 1],
+    );
+
+    final LinearGradient? actual0 = LinearGradient.lerp(testGradient1, testGradient2, 0.0);
+    final LinearGradient? actual1 = LinearGradient.lerp(testGradient1, testGradient2, 1.0);
+    final LinearGradient? actual2 = LinearGradient.lerp(testGradient1, testGradient2, 0.5);
+    expect(testGradient1, equals(actual0));
+    expect(testGradient2, equals(actual1));
+    expect(testGradient2, equals(actual2));
```
Comment (nate-thegrate) [inline packages/flutter/test/painting/gradient_test.dart:217]:
```suggestion
    expect(actual0, equals(testGradient1));
    expect(actual1, equals(testGradient2));
    expect(actual2, equals(testGradient2));
```

Tiny nit: "actual" should be passed as the first argument for [`expect()`](https://github.com/flutter/flutter/blob/7b6d667701e38c1d9d700e2bcc29bc7a06598c59/packages/flutter_test/lib/src/widget_tester.dart#L458-L475) (here and below). Not a big deal though, since in this case the test works fine either way.

**Review by nate-thegrate — APPROVED** [review]
LGTM! 👍

Thanks for noticing the bug and implementing a fix!

**Comment by nate-thegrate** [comment]
We can probably merge this now, and then make the aforementioned tweaks the next time we update these functions.
