### PR TITLE
Handle `ProcessException`s due to `git` missing on the host

### LINKED ISSUE #133585: [flutter_tools] ProcessException trying to call git
On stable/3.13.1

```
ProcessPackageException: ProcessException: Failed to find "git" in the search path.  Command: git
at LocalProcessManager.runSync(local_process_manager.dart:118)
at ErrorHandlingProcessManager.runSync.<anonymous closure>(error_handling_io.dart:714)
at _runSync(error_handling_io.dart:590)
at ErrorHandlingProcessManager.runSync(error_handling_io.dart:713)
at _runSync(version.dart:835)
at _gitCommitDate(version.dart:434)
at FlutterVersion.checkFlutterVersionFreshness(version.dart:279)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:311)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:285)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:115)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:90)
at <asynchronous gap>(async)
```

### PR DESCRIPTION
**Pull request by andrewkolos**
Fixes https://github.com/flutter/flutter/issues/133585.

This PR elects to add a new catch within `_handleToolError` that checks any uncaught error. This new catch will exit the tool without crashing provided the following conditions are met:

1. the error is a `ProcessException`,
2. the error message contains `git` somewhere in the message (we don't match on the entire string in case it changes or is locale-dependent), and
3. `git` does not appear to be runnable on the host system (`ProcessManager.canRun` returns `false` for git).

This is preferable to checking for runnability of `git` before we run it for 1) its simplicity and 2) lack of performance penalty for users that already have git installed (almost every single one).

This PR also does some light refactoring to runner_test.dart to make room for tests that aren't related to crash reporting.

## Pre-launch Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 1]
```diff
@@ -578,7 +578,7 @@ Future<ChromeTab?> getChromeTabGuarded(
   void Function(Object error, StackTrace stackTrace)? onIoError,
 }) async {
   try {
-    return asyncGuard(
+    return await asyncGuard(
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/web/chrome.dart:581]: This change is admittedly orthogonal to the rest of this PR, but—IIRC—there are weird corner cases around errors, zones, and when futures are actually `await`ed. However, I'm not sure that it's worth the time to do a deep dive and look for a bug+test here. I'm happy just adding the `await` in this PR.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/web/chrome.dart:581]: Maybe we should make it a separate PR should we decide to cherrypick this? And maybe we should?

File: packages/flutter_tools/lib/runner.dart [hunk 2]
```diff
@@ -164,6 +164,10 @@ Future<int> _handleToolError(
   String Function() getFlutterVersion,
   ShutdownHooks shutdownHooks,
 ) async {
+
+  bool isDueToGitMissing(ProcessException error) => error.message.contains('git') &&
+      !globals.processManager.canRun('git');
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/runner.dart:169]: what if .canRun() throws?

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 1 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/web/chrome.dart:581]: The use of `asyncGuard` hasn't yet been cherrypicked to stable (drafted in https://github.com/flutter/flutter/pull/154380, where I've already added this `await`), so we have the ability to get this change on stable without needing a separate CP (which would be more noise on the hotfix release notes). I just want this change to also exist in master so it's not implicitly reverted with the next major release.

Comment (andrewkolos) [reply packages/flutter_tools/lib/src/web/chrome.dart:581]: One way or the other, I would like this `await` to be hotfixed. IIRC when I was playing around with this yesterday, I got a repro where this `await` was required to fix it; but, in my experimentation, I lost the repro.

Comment (andrewkolos) [reply packages/flutter_tools/lib/src/web/chrome.dart:581]: OOOOH you are saying should we cherrypick *this* PR.

Comment (andrewkolos) [reply packages/flutter_tools/lib/src/web/chrome.dart:581]: > Maybe we should make it a separate PR should we decide to cherrypick this? And maybe we should?

Focusing on the main point of this PR, yeah I suppose cherrypicking it is not a bad idea. The tool exit message would be a lot helpful than a crash (judging by the amount of threads online from people running into this issue).

Okay. I will revert the chrome aspect of this change and consider it separately, but I'm shuddering at the thought of finding a way to get it under test.

File: packages/flutter_tools/lib/runner.dart (hunk 2 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/runner.dart:169]: Great question.

I think wrapping this call in `try` is a good idea.

File: packages/flutter_tools/lib/src/web/chrome.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/web/chrome.dart]: > drafted in https://github.com/flutter/flutter/pull/154380, where I've already added this await

Ahh, cool, SGTM

> OOOOH you are saying maybe we should cherrypick this PR.

No, I meant specifically the await, but since that's already in your draft, this is good as is.

File: packages/flutter_tools/lib/runner.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/runner.dart:169]: been bitten by this one before, unfortunately

Comment (andrewkolos) [reply packages/flutter_tools/lib/runner.dart]: addressed in [wrap .canRun for git with try-catch](https://github.com/flutter/flutter/pull/154445/commits/5319638b6b51af56cc59d51622516f9df6b549cb)

File: packages/flutter_tools/test/general.shard/runner/runner_test.dart [hunk 3]
```diff
@@ -20,6 +20,7 @@ import 'package:flutter_tools/src/globals.dart' as globals;
 import 'package:flutter_tools/src/reporting/crash_reporting.dart';
 import 'package:flutter_tools/src/reporting/reporting.dart';
 import 'package:flutter_tools/src/runner/flutter_command.dart';
+import 'package:test_api/fake.dart';
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/runner/runner_test.dart:23]: we shouldn't be importing from test_api (except in the few places we *need* to).

```suggestion
import 'package:test/fake.dart';
```

File: packages/flutter_tools/test/general.shard/runner/runner_test.dart [hunk 4]
```diff
@@ -327,6 +326,102 @@ void main() {
...
+      expect(
+          (globals.logger as BufferLogger).errorText,
+          'Failed to find "git" in the search path.\n'
+          '\n'
+          'An error was encountered when trying to run git.\n'
+          "Please ensure git is installed and available in your system's search path. "
+          'See https://docs.flutter.dev/get-started/install for instructions on installing git for your platform.\n');
+      },
+      overrides: <Type, Generator>{
+        Analytics: () => fakeAnalytics,
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/runner/runner_test.dart:381]: can't you just leave this blank, and use the default override `NoOpAnalytics`?

File: packages/flutter_tools/test/general.shard/runner/runner_test.dart [hunk 5]
```diff
@@ -327,6 +326,102 @@ void main() {
...
+      Cache.disableLocking();
+    });
+
+    tearDown(() {
+      io.restoreExitFunction();
+      Cache.enableLocking();
+    });
+
+    testUsingContext("catches ProcessException calling git because it's not available", () async {
+      io.setExitFunctionForTests((int exitCode) {});
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/runner/runner_test.dart:352]: should we call this from `setUp()`?

File: packages/flutter_tools/test/general.shard/runner/runner_test.dart (hunk 4 above)
Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/runner/runner_test.dart:381]: oh i see, nvm, you're asserting on it.

File: packages/flutter_tools/test/general.shard/runner/runner_test.dart (hunk 5 above)
Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/runner/runner_test.dart:352]: and in the other tests

File: packages/flutter_tools/test/general.shard/runner/runner_test.dart (hunk 4 above)
Comment (andrewkolos) [reply packages/flutter_tools/test/general.shard/runner/runner_test.dart:381]: I was asserting on it, but I'm not sure it's necessary.

**Review by christopherfujino — APPROVED** [review]
nit about moving the mocking out of `setExitFunctionForTests` to setUp, but LGTM
