### PR TITLE
Fix `SliverAppBar.medium` & `SliverAppBar.large` title overlap with leading/actions widgets, leading width, and title spacing

### LINKED ISSUE #116188: SliverAppBar.large/medium title overlaps with actions when scrolled
## Steps to Reproduce

1. Execute `flutter run` on the code sample
image
2. Scroll down so the `SliverAppBar.large` collapses
image
3. Make the flutter window smaller so the title _would_ be cut off/overflow with the action icon buttons
image
4. Observe that the AppBar title overlaps the action Icon buttons

**Expected results:**
I expect that the appbar title gets cut off by the actions, and the appropriate `overflow` is applied

**Actual results:**
The appbar title is rendered at the same spot as the actions, leading to unreadable text.

This issue occurs on the `SliverAppBar.medium` variant too.

The code sample below is based on the [sample from the docs](https://api.flutter.dev/flutter/material/SliverAppBar/SliverAppBar.large.html) with minimal changes to illustrate the issue. The issue can also be reproduced within this documentation sample with the edits as below.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const AppBarLargeApp());
}

class AppBarLargeApp extends StatelessWidget {
  const AppBarLargeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
          useMaterial3: true, colorSchemeSeed: const Color(0xff6750A4)),
      home: Material(
        child: CustomScrollView(
          slivers: <Widget>[
            SliverAppBar.large(
              leading:
                  IconButton(icon: const Icon(Icons.menu), onPressed: () {}),
              title: const Text('Large App Bar With Long Title', maxLines: 1),
              actions: <Widget>[
                IconButton(icon: const Icon(Icons.looks_one), onPressed: () {}),
                IconButton(icon: const Icon(Icons.looks_two), onPressed: () {}),
                IconButton(icon: const Icon(Icons.looks_3), onPressed: () {}),
                IconButton(icon: const Icon(Icons.looks_4), onPressed: () {}),
              ],
            ),
            // Just some content big enough to have something to scroll.
            SliverToBoxAdapter(
              child: Card(
                child: SizedBox(
                  height: 1200,
                  child: Padding(
                    padding: const EdgeInsets.fromLTRB(8, 100, 8, 100),
                    child: Text(
                      'Here be scrolling content...',
                      style: Theme.of(context).textTheme.headlineSmall,
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

The issue occurs on the latest stable version (and, to my knowledge, any version since the introduction of the `SliverAppBar.large` constructor with M3).

<details>
<summary>Output of flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22000.1219], locale nl-NL)
    • Flutter version 3.3.9 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (7 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at C:\Users\fvollebregt\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\fvollebregt\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • Pixel 6 (mobile)  • 18071FDF6002GB • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.22000.1219]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 107.0.5304.121
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 104.0.1293.63

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

### LINKED ISSUE #120516: SliverAppBar.medium & SliverAppBar.large do not have correct title spacing in collapsed state
## Steps to reproduce

1. Execute `flutter run` on the code sample.
2. Scroll the `CustomScrollView` beyond certain threshold, so that `SliverAppBar` collapses.

**Expected results:**

A `16dp` space between title & leading icon.

**Actual results:**

No space between title & leading icon.

## Code sample

<details>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.from(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF6750A4),
          brightness: Brightness.light,
        ),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: CustomScrollView(
          slivers: [
            SliverAppBar.medium(
              leading: IconButton(
                onPressed: () {},
                icon: const Icon(Icons.arrow_back),
              ),
              title: const Text('Settings'),
            ),
            SliverList(
              delegate: SliverChildListDelegate(
                [
                  for (int i = 0; i <= 100; i++) ...[
                    ListTile(
                      title: Text('#$i'),
                    ),
                    const Divider(height: 1.0, thickness: 1.0),
                  ],
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22621.1105], locale en-GB)
    • Flutter version 3.7.1 on channel stable at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (10 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Hitesh\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.20348.0

[✓] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.69.2)
    • VS Code at C:\Users\Hitesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • Redmi Note 10S (mobile) • 192.168.201.176:5555 • android-arm64  • Android 13 (API 33)
    • Windows (desktop)       • windows              • windows-x64    • Microsoft Windows [Version 10.0.22621.1105]
    • Chrome (web)            • chrome               • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)              • edge                 • web-javascript • Microsoft Edge 110.0.1587.41

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

## Resources

https://m3.material.io/components/top-app-bar/specs

## Additional images

**Material Design:**

**Flutter:**

See space between navigation button & title.

The required 16dp gap between the navigation button & title of the `SliverAppBar` may be seen in various Android applications e.g. settings of default "Clock" application on Android 12+. However, same does not reflect in Flutter.

### LINKED ISSUE #120603: `SliverAppBar.medium` & `SliverAppBar.large` have fixed padding when leading widget isn't provided
Both `SliverAppBar.medium` & `SliverAppBar.large`  have fixed padding in the collapsed state even when the `leading` widget isn't provided and this is also not removed when overriding the `leadingWidth` parameter.

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      home: const SliverAppBarExample(),
    );
  }
}

class SliverAppBarExample extends StatefulWidget {
  const SliverAppBarExample({super.key});

  @override
  State<SliverAppBarExample> createState() => _SliverAppBarExampleState();
}

class _SliverAppBarExampleState extends State<SliverAppBarExample> {
  bool hideLeading = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          SliverAppBar(
            leading: hideLeading
                ? IconButton(
                    icon: const Icon(Icons.menu),
                    onPressed: () {},
                  )
                : null,
            // leadingWidth: 0,
            title: const Text('Sliver App Bar'),
            centerTitle: false,
            pinned: true,
            actions: <Widget>[
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
            ],
          ),
          SliverAppBar.medium(
            leading: hideLeading
                ? IconButton(
                    icon: const Icon(Icons.menu),
                    onPressed: () {},
                  )
                : null,
            // leadingWidth: 0,
            title: const Text('Medium App Bar'),
            centerTitle: false,
            actions: <Widget>[
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
            ],
          ),
          SliverAppBar.large(
            leading: hideLeading
                ? IconButton(
                    icon: const Icon(Icons.menu),
                    onPressed: () {},
                  )
                : null,
            automaticallyImplyLeading: false,
            // leadingWidth: 0,
            title: const Text('Large App Bar'),
            centerTitle: false,
            actions: <Widget>[
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
            ],
          ),
          const SliverFillRemaining(
            child: Center(
              child: Text(
                'Scroll down to collapse the app bar',
              ),
            ),
          )
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {
          setState(() {
            hideLeading = !hideLeading;
          });
        },
        label: const Text('Toggle leading'),
      ),
    );
  }
}

``` 
	
</details

### Expected results
| With a `leading` widget |  Without a `leading` widget |
| --------------- |  --------------- | 
| 	|  	|

### Actual results
| Without a `leading` widget |  Inspector |
| --------------- |   --------------- | 
| 	|  |

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/116188
fixes https://github.com/flutter/flutter/issues/120516
fixes https://github.com/flutter/flutter/issues/120603

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      home: const SliverAppBarExample(),
    );
  }
}

class SliverAppBarExample extends StatefulWidget {
  const SliverAppBarExample({super.key});

  @override
  State<SliverAppBarExample> createState() => _SliverAppBarExampleState();
}

class _SliverAppBarExampleState extends State<SliverAppBarExample> {
  bool showLeading = true;
  bool centerTitle = false;
  bool removeTitleSpacing = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          SliverAppBar.medium(
            leading: showLeading
                ? IconButton(
                    icon: const Icon(Icons.menu),
                    onPressed: () {},
                  )
                : null,
            // leadingWidth: 0,
            title: const Text('Medium App Bar with a long title', maxLines: 1),
            titleSpacing: removeTitleSpacing ? 0 : null,

            centerTitle: centerTitle,
            actions: <Widget>[
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
            ],
          ),
          SliverAppBar.large(
            leading: showLeading
                ? IconButton(
                    icon: const Icon(Icons.menu),
                    onPressed: () {},
                  )
                : null,
            automaticallyImplyLeading: false,
            // leadingWidth: 0,
            title: const Text('Large App Bar with a long title', maxLines: 1),
            titleSpacing: removeTitleSpacing ? 0 : null,
            centerTitle: centerTitle,
            actions: <Widget>[
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
              IconButton(icon: const Icon(Icons.favorite), onPressed: () {}),
            ],
          ),
          const SliverFillRemaining(
            child: Center(
              child: Text(
                'Scroll down to collapse the app bar',
              ),
            ),
          )
        ],
      ),
      bottomSheet: Padding(
        padding: const EdgeInsets.all(8.0),
        child: OverflowBar(
          alignment: MainAxisAlignment.spaceEvenly,
          spacing: 10,
          overflowSpacing: 10,
          children: <Widget>[
            FilledButton(
              onPressed: () {
                setState(() {
                  removeTitleSpacing = !removeTitleSpacing;
                });
              },
              child: Text('titleSpacing: ${removeTitleSpacing ? 0 : 16}'),
            ),
            FilledButton(
              onPressed: () {
                setState(() {
                  centerTitle = !centerTitle;
                });
              },
              child: Text('Center title: $centerTitle'),
            ),
            FilledButton(
              onPressed: () {
                setState(() {
                  showLeading = !showLeading;
                });
              },
              child: const Text('Toggle leading'),
            ),
          ],
        ),
      ),
    );
  }
}

``` 
	
</details>

### Description

- The title widget inside `_ScrollUnderFlexibleSpace` cannot be aware of the `actions` spacing, how many `actions` widgets there are, and what size. This information is hard to get without a global key and having to measure the `actions` row size. 
However, we can use a lower-level widget like `NavigationToolbar` which does align the title so it doesn't overlap with `actions` widgets.  As a result, added `NavigationToolbar` and provided the `title` and `actions` widgets to this.
This addresses  https://github.com/flutter/flutter/issues/116188

### Before
title_overlap_before

### After
title_overlap_after

- https://github.com/flutter/flutter/issues/120516 pointed out that there is no spacing between the `leading` widget and the `title`. Thanks to adding `NavigationToolbar`, we can get `titleSpacing` support. However, this requires updating the default collapsed title padding so we don't get unnecessary padding. 
This also makes it possible to update `titleSpacing` from the `SliverAppBar.medium` & `SliverAppBar.large` parameters or from the `AppBarTheme`, which is not possible without this PR.
This addresses https://github.com/flutter/flutter/issues/120516.

### Before
title_spacing_before

### After
title_spacing_after

- While fixing other `SliverAppBar.medium` & `SliverAppBar.large` issues, I noticed when the `leading` widget isn't provided, we still get the default padding in the collapsed state. I added a condition that updates the leading padding when the `leading` widget is removed.
This addresses https://github.com/flutter/flutter/issues/120603.

 ### Before
leading_width_before

### After
leading_width_after

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Piinks — APPROVED** [review]
Flutter_LGTM but let me check internal tests first to ensure we don't break anything again. 🙃

**Comment by Piinks** [comment]
Update: the google testing shard os having issues, but the initial sampling of tests passed. Doing a global run manually to ensure this is good to go.

**Comment by Piinks** [comment]
Tests are all green! This can merge now.

**Comment by MominRaza** [comment]
Still overlapping with leading icon if leading icon is not provided, when automaticallyImplyLeading added back icon

File: packages/flutter/lib/src/material/app_bar.dart [hunk 1]
```diff
@@ -1543,13 +1543,16 @@ class SliverAppBar extends StatefulWidget {
       key: key,
       leading: leading,
       automaticallyImplyLeading: automaticallyImplyLeading,
-      actions: actions,
```
Comment (alifgiant) [inline packages/flutter/lib/src/material/app_bar.dart:1546]: how to implement `actions` if we provide `flexibleSpace` by using `FlexibleSpaceBar`?
