### PR TITLE
Changes the regular cursor to a floating cursor when a long press occurs.

### LINKED ISSUE #89228: Double cursor using iOS floating cursor (keyboard cursor move with spacebar)
I created this Issue for the [last bug](https://github.com/flutter/flutter/issues/17030#issuecomment-803130790) described in #17030, which we also just encountered, because the #17030 got closed. 

## Steps to Reproduce

OS: iOs and iPadOS

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

Enter so much text into the TextField, that the TextField starts scrolling. Then try to scroll with two fingers, on the spacebar, horizontally through the text.

**Expected results:** The curser moves with the fingers and scrolls horizontal through the TextField.

**Actual results:** A second curser appears, which moves separately to the original curser, and the TextField doesn't scroll horizontally.

<details>
  <summary>Logs</summary>

```

[+18718 ms] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ] 	Probably at least one of the constraints in the following list is one you don't want. 
[        ] 	Try this: 
[        ] 		(1) look at each constraint and try to figure out which you don't expect; 
[        ] 		(2) find the code that added the unwanted constraint or constraints and fix it. 
[        ] 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x2820c7700 h=--& v=--& _UIButtonBarButton:0x10888cf40.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x2820f8aa0 _UIUCBKBSelectionBackground:0x10888d860.bottom == _UIButtonBarButton:0x10888cf40.bottom - 6   (active)>",
[        ]     "<NSLayoutConstraint:0x2820f88c0 V:|-(6)-[_UIUCBKBSelectionBackground:0x10888d860]   (active, names: '|':_UIButtonBarButton:0x10888cf40 )>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x2820f8aa0 _UIUCBKBSelectionBackground:0x10888d860.bottom == _UIButtonBarButton:0x10888cf40.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ] 	Probably at least one of the constraints in the following list is one you don't want. 
[        ] 	Try this: 
[        ] 		(1) look at each constraint and try to figure out which you don't expect; 
[        ] 		(2) find the code that added the unwanted constraint or constraints and fix it. 
[        ] 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x2820fb610 h=--& v=--& _UIButtonBarButton:0x10888b3c0.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x2820f82d0 V:|-(6)-[_UIUCBKBSelectionBackground:0x10888bc60]   (active, names: '|':_UIButtonBarButton:0x10888b3c0 )>",
[        ]     "<NSLayoutConstraint:0x2820fbe30 _UIUCBKBSelectionBackground:0x10888bc60.bottom == _UIButtonBarButton:0x10888b3c0.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x2820fbe30 _UIUCBKBSelectionBackground:0x10888bc60.bottom == _UIButtonBarButton:0x10888b3c0.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ] 	Probably at least one of the constraints in the following list is one you don't want. 
[        ] 	Try this: 
[        ] 		(1) look at each constraint and try to figure out which you don't expect; 
[        ] 		(2) find the code that added the unwanted constraint or constraints and fix it. 
[        ] 	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x2820f8a50 h=--& v=--& _UIButtonBarButton:0x10888bde0.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x2820f8dc0 V:|-(6)-[_UIUCBKBSelectionBackground:0x10888c5e0]   (active, names: '|':_UIButtonBarButton:0x10888bde0 )>",
[        ]     "<NSLayoutConstraint:0x2820f8d70 _UIUCBKBSelectionBackground:0x10888c5e0.bottom == _UIButtonBarButton:0x10888bde0.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x2820f8d70 _UIUCBKBSelectionBackground:0x10888c5e0.bottom == _UIButtonBarButton:0x10888bde0.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.


```
```

Analyzing bug...                                                        
No issues found! (ran in 3.5s)

```
```

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-DE)
    • Flutter version 2.2.3 at /Users/curvel/dev/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/curvel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Curvel’s iPad (mobile) • 00008027-001E08420C22002E            • ios            • iOS 14.6
    • iPhone 12 (mobile)     • AB9878B8-38E4-4250-B538-BAA98837CFA5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!

```

### LINKED ISSUE #132825: virtual keyboard of the input box flashes when pressed and swiped
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

virtual keyboard of the input box flashes when pressed and swiped

### Expected results

ios native 16.6

https://github.com/flutter/flutter/assets/21240282/2daade89-22d2-45bd-8207-551ffe55d3d5

### Actual results

https://github.com/flutter/flutter/assets/21240282/87072c69-189b-42a5-8189-4787b29559c9

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [版本 10.0.22621.2134], locale zh-CN)
    • Flutter version 3.13.0 on channel stable at C:\Apps\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (2 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\95646\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Apps\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Apps\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Apps\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [版本 10.0.22621.2134]
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 115.0.1901.203
```

</details>

### PR DESCRIPTION
**Pull request by yiiim**
This PR changes the regular cursor to a floating cursor when a long press occurs.

This is a new feature. Fixes  #89228 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -30,6 +30,10 @@ const EdgeInsets _kFloatingCursorSizeIncrease = EdgeInsets.symmetric(horizontal:
 // The corner radius of the floating cursor in pixels.
 const Radius _kFloatingCursorRadius = Radius.circular(1.0);
 
+// Represents the shortest distance required when both the floating cursor
+// and regular cursor are present.
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/rendering/editable.dart:34]: nit: maybe add a bit more context about the behavior? Something like in UITextField when floating cursor is activated the regular cursor won't be visible unless it's too far away from the regular one?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -3132,16 +3132,23 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
         _pointOffsetOrigin = point.offset;
+        final TextPosition currentTextPosition = TextPosition(
+          offset: widget.controller.selection.baseOffset,
+          affinity: widget.controller.selection.affinity,
+        );
 
-        final TextPosition currentTextPosition = TextPosition(offset: renderEditable.selection!.baseOffset, affinity: renderEditable.selection!.affinity);
-        _startCaretRect = renderEditable.getLocalRectForCaret(currentTextPosition);
+        if (point.localPosition != null) {
+          _startCaretCenter = point.localPosition;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3141]: nit: use `??` over `if` statements?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 3]
```diff
@@ -3622,3 +3622,37 @@ mixin TextSelectionHandleControls on TextSelectionControls {
   @override
   void handleSelectAll(TextSelectionDelegate delegate) {}
 }
+
+/// [FloatingCursorSingleLongPressDetectorBuilder] is a mixin that adds handling for single long press on top of [TextSelectionGestureDetectorBuilder].
+/// This mixin is primarily used to handle floating cursor behavior during text selection.
+mixin FloatingCursorSingleLongPressDetectorBuilder on TextSelectionGestureDetectorBuilder{
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:3628]: can this be incorporated into the base class instead of a separate mixin?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -3132,16 +3132,23 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
         // We want to send in points that are centered around a (0,0) origin, so
         // we cache the position.
         _pointOffsetOrigin = point.offset;
+        final TextPosition currentTextPosition = TextPosition(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:3135]: Ideally we should avoid using the selection value from the controller. The value from the controller is potentially one frame ahead of the currently rendered selection range.

**Review by LongCatIsLooong — COMMENTED** [review]
This looks like a new feature to me. Could you add a bit more detail wrt how this fixes the flickering in https://github.com/flutter/flutter/issues/132825 ?

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 3 above)
Comment (yiiim) [reply packages/flutter/lib/src/widgets/text_selection.dart:3628]: Yes, I found that it doesn't affect `SelectableText`, so we can incorporate into the base class.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 4 above)
Comment (yiiim) [reply packages/flutter/lib/src/widgets/editable_text.dart:3135]: Then we have to update the floating cursor after the frame

**Comment by yiiim** [comment]
> This looks like a new feature to me. Could you add a bit more detail wrt how this fixes the flickering in #132825 ?

Sorry, I seem to have had some misunderstandings. This cannot be fixed #132825. I will change the description.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 5]
```diff
@@ -2436,6 +2436,16 @@ class TextSelectionGestureDetectorBuilder {
 
       _dragStartViewportOffset = renderEditable.offset.pixels;
       _dragStartScrollOffset = _scrollPosition;
+
+      // Show the floating cursor
+      SchedulerBinding.instance.addPostFrameCallback((Duration duration) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:2441]: Why does the code need to be scheduled to run as a post-frame callback?

**Comment by LongCatIsLooong** [comment]
I'd like to verify some floating cursor interactions in a UIKit app tomorrow and get back to this PR. Sorry for the delay!

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 5 above)
Comment (yiiim) [reply packages/flutter/lib/src/widgets/text_selection.dart:2441]: [editable_text.dart#L3135C7-L3135C7](https://github.com/yiiim/flutter/blob/9f18c5db821600f37cbeb90d26e371046e790dd8/packages/flutter/lib/src/widgets/editable_text.dart#L3135C7-L3135C7) Need to get the correct selection after the frame.

**Comment by yiiim** [comment]
I also found that the cursor will be reset to the blinking state shortly after long pressing. This may also be incorrect behavior. I will look for this issue later and fix it as another PR.

**Comment by yiiim** [comment]
Any feedback?

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 5 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_selection.dart:2441]: Shouldn't this go to line 2417? The floating cursor is iOS only right? And it only happens when you long press and drag the blinking cursor?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_selection.dart:2441]: (Same for the update/end events)

**Review by LongCatIsLooong — COMMENTED** [review]
Sorry for the delay.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 5 above)
Comment (yiiim) [reply packages/flutter/lib/src/widgets/text_selection.dart]: A long press displays a floating cursor that does not require dragging. A long press may be further away from the regular cursor. For example, long press at the end of the text far away from the text

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_selection.dart]: Ah I see thanks for pointing this out. I tried this in a UITextView, my observations so far:

1. When the text selection is collapsed, long press drag initiates floating cursor and when it ends the selection remains collapsed.
2. When there is pre-selected text, long press drag does the same, but only when the initial long press starts outside of the selected text. And when it ends the selection becomes collapsed. 
3. When there is pre-selected text, and the initial long press starts inside of the selected text, the behavior has been somewhat inconsistent for me. Most of the time it enters "text drag and drop" mode, but sometimes one of the selection handlers enters the floating cursor mode and I was able to adjust the text selection in that mode.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 6]
```diff
@@ -2415,6 +2415,17 @@ class TextSelectionGestureDetectorBuilder {
...
+          // Show the floating cursor
+          SchedulerBinding.instance.addPostFrameCallback((Duration duration) {
+            final RawFloatingCursorPoint cursorPoint = RawFloatingCursorPoint(
+              state: FloatingCursorDragState.Start,
+              localPosition: renderEditable.globalToLocal(details.globalPosition),
+              offset: Offset.zero,
+            );
+            editableText.updateFloatingCursor(cursorPoint);
+          }, debugLabel: 'TextSelectionGestureDetectorBuilderDelegate.updateFloatingCursor');
+          continue macOSCase;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:2427]: It will probably be easier if we update the logic in `RenderEditable.updateFloatingCursor` to update the selection immediately on `FloatingCursorDragState.Start` (as all types of floating cursors seem to relocate the caret to where the floating cursor is on start?), so we don't have to do this?

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 5 above)
Comment (yiiim) [reply packages/flutter/lib/src/widgets/text_selection.dart]: I guess I should only need to show the floating cursor when the text is collapsed. Do we have any plans regarding "text drag and drop" mode? I'd like to contribute to this.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 6 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_selection.dart:2429]: Good point. Then does it make sense to add the new text selection to the `RawFloatingCursorPoint` class? 
```dart
class RawFloatingCursorPoint {
  // (local offset, new caret location)
  //  Only non-null when starting a floating cursor via long press.
  final (Offset, TextPositon)? startLocation;
}
```

Then in editable_text.dart we can use that information in the `FloatingCursorDragState.Start` clause if non-null. It's error-prone to use `addPostframeCallback` in general since you don't know what is going to happen in that frame (the render object can be disposed, for example).

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 5 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_selection.dart]: One existing issue I found: https://github.com/flutter/flutter/issues/128388. @Renzo-Olivares have you looked into this?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 7]
```diff
@@ -2449,6 +2436,22 @@ class TextSelectionGestureDetectorBuilder {
 
       _dragStartViewportOffset = renderEditable.offset.pixels;
       _dragStartScrollOffset = _scrollPosition;
+
+      if (editableText.textEditingValue.selection.isCollapsed && defaultTargetPlatform == TargetPlatform.iOS) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:2440]: nit: I think it probably makes more sense to keep this in the `switch` statement? If the render editable isn't focused, instead of selecting the word, we want to select the position and start the floating cursor right?

**Review by LongCatIsLooong — COMMENTED** [review]
Could you add a few tests to verify the new feature works?

File: packages/flutter/lib/src/services/text_input.dart [hunk 8]
```diff
@@ -744,12 +744,17 @@ class RawFloatingCursorPoint {
...
+    this.startLocation,
     required this.state,
   }) : assert(state != FloatingCursorDragState.Update || offset != null);
 
   /// The raw position of the floating cursor as determined by the iOS sdk.
   final Offset? offset;
 
+  /// (local offset, new caret location)
+  ///  Only non-null when starting a floating cursor via long press.
+  final (Offset, TextPosition)? startLocation;
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/services/text_input.dart:756]: Can this just be an `Offset` and we can get the current value from within `updateFloatingCursor`?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 9]
```diff
@@ -2436,6 +2449,7 @@ class TextSelectionGestureDetectorBuilder {
 
       _dragStartViewportOffset = renderEditable.offset.pixels;
       _dragStartScrollOffset = _scrollPosition;
+
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/text_selection.dart:2452]: nit: is this empty line needed?

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 10]
```diff
@@ -2474,6 +2487,12 @@ class TextSelectionGestureDetectorBuilder {
               from: details.globalPosition,
               cause: SelectionChangedCause.longPress,
             );
+            // Update the floating cursor
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/text_selection.dart:2490]: nit: add a period at the end of this comment.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 11]
```diff
@@ -2507,6 +2526,13 @@ class TextSelectionGestureDetectorBuilder {
     _longPressStartedWithoutFocus = false;
     _dragStartViewportOffset = 0.0;
     _dragStartScrollOffset = 0.0;
+    if (defaultTargetPlatform == TargetPlatform.iOS && delegate.selectionEnabled && editableText.textEditingValue.selection.isCollapsed) {
+      // Update the floating cursor
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/text_selection.dart:2530]: nit: add a period at the end of this comment.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 12]
```diff
@@ -10118,4 +10118,45 @@ void main() {
...
+              child: CupertinoTextField(
+                autofocus: true,
+                controller: controller,
+              ),
+            )
+          ),
+        ),
+      ),
+    );
+    // wait focus
```
Comment (Renzo-Olivares) [inline packages/flutter/test/cupertino/text_field_test.dart:10142]: nit: `Wait for autofocus.`

File: packages/flutter/test/material/text_field_test.dart [hunk 13]
```diff
@@ -17063,6 +17063,48 @@ void main() {
...
+              child: TextField(
+                autofocus: true,
+                controller: controller,
+              ),
+            )
+          ),
+        ),
+      ),
+    );
+    // wait focus
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/text_field_test.dart:17087]: nit: consider changing to `Wait for autofocus.`

File: packages/flutter/test/widgets/editable_text_cursor_test.dart [hunk 14]
```diff
@@ -984,14 +977,32 @@ void main() {
...
         rrect: RRect.fromRectAndRadius(
-          const Rect.fromLTRB(191.3333282470703, -0.916666666666668, 193.3333282470703, 17.083333015441895),
+          const Rect.fromLTRB(193.83334350585938, -0.916666666666668, 196.83334350585938, 19.083333969116211),
+          const Radius.circular(1.0),
+        ),
+        color: const Color(0xbf2196f3),
+      ),
+    );
+
+    // Move the cursor away from characters, this will show the regular cursor
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/editable_text_cursor_test.dart:987]: nit: Add a period at the end of this comment.

File: packages/flutter/lib/src/services/text_input.dart (hunk 8 above)
Comment (yiiim) [reply packages/flutter/lib/src/services/text_input.dart:756]: I had a discussion with LongCatIsLooong, and because `renderEditable.selection` updates one frame late, we can't use `renderEditable.selection` for calculation.

**Comment by yiiim** [comment]
All nits have been fixed.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 15]
```diff
@@ -2352,19 +2359,39 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
...
+  Offset calculateBoundedFloatingCursorOffset(Offset rawCursorOffset, {bool? shouldResetOrigin}) {
+    Offset deltaPosition = Offset.zero;
+    final EdgeInsets boundingRect = _calculateFloatingCursorBounds();
+
+    if (shouldResetOrigin != null) {
+      _shouldResetOrigin = shouldResetOrigin;
+    }
+
+    if (!_shouldResetOrigin) {
+      return _calculateAdjustedCursorOffset(rawCursorOffset, boundingRect);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/rendering/editable.dart:2393]: If you adjust the cursor offset to be within `boundingRect`, does a multiline text field still scroll down if you drag the cursor to the bottom of the text field?

File: packages/flutter/lib/src/rendering/editable.dart [hunk 16]
```diff
@@ -2352,19 +2359,39 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
...
+  Offset _calculateAdjustedCursorOffset(Offset offset, EdgeInsets boundingRect) {
+    final double adjustedX = math.min(math.max(offset.dx, boundingRect.left), boundingRect.right);
+    final double adjustedY = math.min(math.max(offset.dy, boundingRect.top), boundingRect.bottom);
+    return Offset(adjustedX, adjustedY);
+  }
+
+  /// Returns the position within the text field closest to the raw cursor offset.
+  Offset calculateBoundedFloatingCursorOffset(Offset rawCursorOffset, {bool? shouldResetOrigin}) {
+    Offset deltaPosition = Offset.zero;
+    final EdgeInsets boundingRect = _calculateFloatingCursorBounds();
```
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:2386]: also nit: bounding rects are typically Rects.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 17]
```diff
@@ -2352,19 +2359,39 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
...
+
+    if (shouldResetOrigin != null) {
+      _shouldResetOrigin = shouldResetOrigin;
```
[the remark this answers is not in the document]
Comment (yiiim) [reply packages/flutter/lib/src/rendering/editable.dart:2385]: We can't use `??=` here. When `shouldResetOrigin` is not `null`, the variable that needs to be assigned is `_shouldResetOrigin`, they are not the same.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 15 above)
Comment (yiiim) [reply packages/flutter/lib/src/rendering/editable.dart]: I see that they are working properly.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 16 above)
[the remark this answers is not in the document]
Comment (yiiim) [reply packages/flutter/lib/src/rendering/editable.dart]: Fixed.

[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart]: nit: use Rect instead of EdgeInsets.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 18]
```diff
@@ -2352,19 +2359,39 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
...
-    Offset deltaPosition = Offset.zero;
+  EdgeInsets _calculateFloatingCursorBounds() {
     final double topBound = -floatingCursorAddedMargin.top;
     final double bottomBound = _textPainter.height - preferredLineHeight + floatingCursorAddedMargin.bottom;
     final double leftBound = -floatingCursorAddedMargin.left;
     final double rightBound = _textPainter.width + floatingCursorAddedMargin.right;
+    return EdgeInsets.fromLTRB(leftBound, topBound, rightBound, bottomBound);
+  }
+
+  Offset _calculateAdjustedCursorOffset(Offset offset, EdgeInsets boundingRect) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/rendering/editable.dart]: nit: make this static?

File: packages/flutter/lib/src/services/text_input.dart (hunk 8 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/services/text_input.dart:756]: Since this is public API documentation, could you update it to make it more formal / descriptive?

**Review by LongCatIsLooong — APPROVED** [review]
LGTM modulo nits. Thank you for contributing! The floating cursor seems to work pretty well when I tried out this patch.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 19]
```diff
@@ -2453,6 +2453,19 @@ class TextSelectionGestureDetectorBuilder {
               from: details.globalPosition,
               cause: SelectionChangedCause.longPress,
             );
+            // Show the floating cursor
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/text_selection.dart:2456]: nit: period at the end of sentence.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM w/ small nit.

**Comment by yiiim** [comment]
The nits have been fixed, I believe it's ready for merge.
