### PR TITLE
fix a TextFormField bug

### LINKED ISSUE #119628: Scrollable parent does not scroll to TextFormField (on focus)when TextSelection is set
## Steps to Reproduce

1. Wrap a TextFormField into a scrollable widget like SingleChildScrollView.
2. Into onTap callback select the whole text of the text controller.
3. Run the example scroll down and tap the textfield.

**Expected results:** 
The TextFormField should be scroll up above the keyboard. Video shows the behavior when text selection is not set.

https://user-images.githubusercontent.com/22661573/215796187-e20f6bf4-8060-42df-821a-9f24b53777e0.mov

**Actual results:** 
The TextFormField is hidden behind.

https://user-images.githubusercontent.com/22661573/215795951-47b42499-bb35-4eec-915e-3306e2082c5d.mov

<details>
<summary>Code sample</summary>

```dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const TestSelectControllerWidget(),
    );
  }
}

class TestSelectControllerWidget extends StatefulWidget {
  const TestSelectControllerWidget({super.key});

  @override
  State<StatefulWidget> createState() => _TestSelectControllerState();
}

class _TestSelectControllerState extends State<TestSelectControllerWidget> {
  final TextEditingController _controller = TextEditingController();

  @override
  void initState() {
    super.initState();

    _controller.text = 'Select all!';
  }

  @override
  void dispose() {
    _controller.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Select test'),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            SizedBox(
              height: MediaQuery.of(context).size.height,
              child: const Text('Moved field to bottom'),
            ),
            TextFormField(
              controller: _controller,
              onTap: () {
                //when removed the scroll behavior is correct!
                _controller.selection = TextSelection(
                    baseOffset: 0, extentOffset: _controller.text.length);
              },
            )
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
No issues found! (ran in 1.8s)
```

```
[!] Flutter (Channel stable, 3.7.0, on macOS 12.5.1 21G83 darwin-x64, locale de-DE)
    • Flutter version 3.7.0 on channel stable at xxx
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.12.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at xxx/flutter_sdk/flutter. Consider adding xxx/flutter_sdk/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (8 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at xxx/android_sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/xxx/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/xxx/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9301383/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio
    • Android Studio at /Users/xxx/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Users/xxx/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/202.7319.50/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://mrketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM X200 (mobile) • R9YT307A0QK • android-arm64  • Android 13 (API 33)
    • mcOS (desktop)  • macos       • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 5 categories.
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes https://github.com/flutter/flutter/issues/119628

This is a regression by #102992 and I believe it was an unintentional change by accident.

@justinmc Hi, could you take a look at this :)

### CODE REVIEW

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 1]
```diff
@@ -132,6 +132,52 @@ void main() {
     expect(tester.testTextInput.setClientArgs!['inputAction'], equals(serializedActionName));
   }
 
+  testWidgets('Text with selection can be show on the screen when the keyboard shown', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:135]: "show" => "shown"

**Review by justinmc — APPROVED** [review]
LGTM 👍 

I think you're right that it was just a mistake of mine in https://github.com/flutter/flutter/pull/102992.  I tried the edge scrolling that that PR fixed, and it still works with this change.
