### PR TITLE
Do not add run spacing if there are no run metrics

### LINKED ISSUE #16285: Wrap widget's height not matching children when only in one run
## Steps to Reproduce
```dart
new Container(
  color: Colors.red,
  child: new Wrap(
    spacing: 16.0,
    runSpacing: 16.0,
    runAlignment: WrapAlignment.center,
    children: chips,
  ),
),
```
When the children match on a single run, there is space between the bottom edge of the children and the container (see screenshots). When there are on two or more runs, that space disappears. When removing ``runSpacing``, the space disappears as well, but that is not an option because it is needed or it wouldn't look good when two or more runs are needed.

## Screenshots
**Two Runs:** Everything is fine
Two Runs

**One Run:** Small space below chips
One Run

**One Run: Expectation** (how it is now when ``runSpacing`` is removed)
One Run: Expectation

## Flutter Doctor
```
[√] Flutter (Channel master, v0.2.10-pre.25, on Microsoft Windows [Version 10.0.16299.309], locale de-DE)    • Flutter version 0.2.10-pre.25 at D:\Program Files\flutter
    • Framework revision 24bfbeb246 (2 hours ago), 2018-04-05 10:24:05 -0700
    • Engine revision 23c0b7bbf7
    • Dart version 2.0.0-dev.45.0.flutter-52afcba357

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Program Files\Android\Android SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\Program Files\Android\Android SDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Community Edition (version 2017.1)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
After the initial run we always add run spacing.  Detect this by checking if there are run metrics, and avoid adding the spacing.

Fixes https://github.com/flutter/flutter/issues/16285

### CODE REVIEW

File: packages/flutter/test/widgets/wrap_test.dart [hunk 1]
```diff
@@ -853,17 +853,47 @@ void main() {
...
+          ),
+        ],
+      )
+    );
 
-    expect(tester.renderObject<RenderBox>(find.byType(Wrap)).size, equals(const Size(800.0, 600.0)));
+    expect(tester.renderObject<RenderBox>(find.byType(Wrap)).size, equals(const Size(800.0, 10.0)));
     verify(tester, <Offset>[const Offset(0.0, 0.0)]);
+
+
```
Comment (Hixie) [inline packages/flutter/test/widgets/wrap_test.dart]: extraneous blank line

**Comment by Hixie** [comment]
LGTM

Nice catch!
