### PR TITLE
Fix edge scrolling on platforms that select word by word on long press move

### LINKED ISSUE #26394: Long press drag on Android selects word and expands selection by words

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This change moves the long press logic from the material layer (TextField) back into the widgets layer (TextSelection). This includes changing the long press behavior to match the platform behavior on CupertinoTextField and TextField. Previously in some cases CupertinoTextField and TextField attempted to match the behavior of the theme rather than the platform, this resulted in CupertinoTextField for Android having iOS text gestures.

This change fixes edge scrolling on long press by using the same technique used during drag to select text. We offset the new selection baseOffset by the editable and scrollable offsets. We also bring the selection into view for all platforms now on a long press or drag.

Before | After
---|---
192354969-dd6cc2d4-4612-461b-a997-9b1eaa46ea0a|Screen Recording 2022-10-10 at 12 03 34 PM

Fixes #26394

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 1]
```diff
@@ -1561,7 +1561,7 @@ void main() {
     expect(text.style!.fontWeight, FontWeight.w400);
   }, skip: isContextMenuProvidedByPlatform); // [intended] only applies to platforms where we supply the context menu.
 
-  testWidgets('text field toolbar options correctly changes options', (WidgetTester tester) async {
+  testWidgets('text field toolbar options correctly changes options on Apple Platforms', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:1564]: FYI I'm deprecating toolbarOptions in my context menu PR.  I worry that these tests might get deleted when toolbarOptions is removed a year from now.  Maybe change the title to indicate that they're testing longpress behavior too?  If you think they should not be deleted.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 2]
```diff
@@ -2365,7 +2461,40 @@ void main() {
...
+      await tester.longPressAt(textFieldStart + const Offset(50.0, 5.0));
+      await tester.pumpAndSettle();
+
+      // Select word, 'Atwater, on long press.
+      expect(
+        controller.selection,
+        const TextSelection(baseOffset: 0, extentOffset: 7, affinity: TextAffinity.upstream),
+      );
+
+      // non-Collapsed toolbar shows 3 buttons.
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:2490]: Nit: Capitalize the first letter.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 3]
```diff
@@ -6105,7 +6386,66 @@ void main() {
...
+      // Expect the position the magnifier gets to have moved.
+      expect(firstLongPressGesturePosition, isNot(magnifierInfo.value.globalGesturePosition));
+
+      // End the long press to hide the magnifier.
+      await gesture.up();
+      await tester.pumpAndSettle();
+      expect(find.byKey(fakeMagnifier.key!), findsNothing);
+    }, variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.android }));
+
+    testWidgets('Can long press to show, unshow, and update magnifier on Apple platforms', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:6448]: Super nit: Should this just say "on iOS"?

File: packages/flutter/test/material/text_field_test.dart [hunk 4]
```diff
@@ -2360,7 +2360,7 @@ void main() {
         break;
     }
   },
-    variant: TargetPlatformVariant.all(),
+    variant: TargetPlatformVariant.all(excluding: <TargetPlatform>{ TargetPlatform.iOS, TargetPlatform.macOS }),
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:2363]: Nit: Change the title to say "on Apple platforms"?

**Review by justinmc — APPROVED** [review]
LGTM with nits 👍 

Thanks for cleaning this up, I'm happy to get this logic out of widgets like TextField and into more separate and reusable places.

Don't forget you have a merge conflict.

File: packages/flutter/test/material/text_field_test.dart (hunk 4 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/material/text_field_test.dart:2363]: You're right. This also reminds me that I should add a test for Apple/non-Apple platforms.

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/cupertino/text_field_test.dart:1564]: I think we can delete these tests with the deprecation. There are other tests that more implicitly test long press. This test also doesn't test for long press on apple platforms since they do not select a word on long press, only move the cursor.
