### PR TITLE
Fix plugin template app's tests

### LINKED ISSUE #39077: flutter create --template plugin has failing tests
Steps to reproduce:

flutter create --template myplugin
cd myplugin
flutter test

Fails with:

```
00:06 +0 -1: getPlatformVersion [E]                                                                                                                                                          
  ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
  If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
  If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
  package:flutter/src/services/binary_messenger.dart 73:7    defaultBinaryMessenger.<fn>
  package:flutter/src/services/binary_messenger.dart 86:4    defaultBinaryMessenger
  package:flutter/src/services/platform_channel.dart 140:62  MethodChannel.binaryMessenger
  package:flutter/src/services/platform_channel.dart 393:5   MethodChannel.setMockMethodCallHandler
  my_plugin_test.dart 9:13                                   main.<fn>
  
  ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
  If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
  If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
  package:flutter/src/services/binary_messenger.dart 73:7    defaultBinaryMessenger.<fn>
  package:flutter/src/services/binary_messenger.dart 86:4    defaultBinaryMessenger
  package:flutter/src/services/platform_channel.dart 140:62  MethodChannel.binaryMessenger
  package:flutter/src/services/platform_channel.dart 393:5   MethodChannel.setMockMethodCallHandler
  my_plugin_test.dart 15:13                                  main.<fn>
  
00:06 +0 -1: Some tests failed.  
```

We should fix this, and also we should add a test to the Flutter CI to prevent this type of failure from occurring in the future.

### PR DESCRIPTION
**Pull request by collinjackson**
## Description

Plugin template app needs to be updated with this breaking change:

https://groups.google.com/forum/#!msg/flutter-announce/sHAL2fBtJ1Y/mGjrKH3dEwAJ

> https://github.com/flutter/flutter/pull/37489 proposed to move the default BinaryMessenger instance to ServicesBinding, and deprecate the former. This is going to be a breaking change, if users reference to the defaultBinaryMessenger directly. Instead, users will use ServicesBinding.instance.defaultBinaryMessenger to access the default BinaryMessenger that's used for sending platform messages.
> 
> Why this change?
> By this change, we are capable of registering a different default BinaryMessenger under testing environment, by creating a ServicesBinding subclass for testing. With that, we can track # of pending platform messages for synchronization purposes. See more details in https://github.com/flutter/flutter/issues/37409.
> 
> Path to migrate
> You'll use ServicesBinding.instance.defaultBinaryMessenger to access the default BinaryMessenger. In your tests, make sure the ServicesBinding is properly initialized before accessing any message channels.
> 
> If you have any concerns or otherwise feel that this change should not be made, please comment on the above PR or on the associated issue: https://github.com/flutter/flutter/issues/37409 -- or just reply to this email.

## Related Issues

Fixes #39077 

## Tests

I included the following tests:

- dev/devicelab/lib/tasks/plugin_test.dart

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by tvolkert — APPROVED** [review]
LGTM

File: dev/devicelab/lib/tasks/plugin_tests.dart [hunk 1]
```diff
@@ -55,30 +63,86 @@ class PluginTest {
...
+          'plugintestapp'
+        ],
+      );
+    });
+    return _FlutterApp(directory, 'plugintestapp');
+  }
 
-  Future<void> addPlugin(String plugin) async {
+  Future<void> addPlugin(String plugin, {String pluginPath}) async {
     final File pubspec = File(path.join(rootPath, 'pubspec.yaml'));
```
Comment (adazh) [inline dev/devicelab/lib/tasks/plugin_tests.dart]: Does `addPlugin` have to be a method on the _FlutterPlugin class? It looks to me the two classes `_FlutterProject` and `_FlutterPlugin` are quite similar except the binary/project name? Wondering whether you'll have to define two classes.

**Review by adazh — APPROVED** [review]

File: dev/devicelab/lib/tasks/plugin_tests.dart (hunk 1 above)
Comment (collinjackson) [reply dev/devicelab/lib/tasks/plugin_tests.dart]: `_FlutterPlugin` extends `_FlutterProject`.

I've moved `addPlugin` from `_FlutterApp` into `_FlutterProject` and `test` from `_FlutterPlugin` into `_FlutterProject` since they make sense for both plugins and apps. 

I haven't written any test that have plugins depending on plugins, but I added a line that ensures that the template app's unit tests pass.

File: dev/devicelab/lib/tasks/plugin_tests.dart [hunk 2]
```diff
@@ -103,4 +105,53 @@ class FlutterProject {
     }
     rmTree(parent);
   }
+
+}
+
+class _FlutterPlugin extends _FlutterProject {
+  _FlutterPlugin(Directory parent, String name) : super(parent, name);
```
Comment (adazh) [inline dev/devicelab/lib/tasks/plugin_tests.dart]: Is it possible to have everything in the `_FlutterProject` class?
It appears you can define a create method with `template`, `project_name/binary_name` arguments, and simply create:
- plugin by calling `create('plugin', 'plugintest', ...)`;
- app by calling `create('app', 'plugintestapp')`.

File: dev/devicelab/lib/tasks/plugin_tests.dart [hunk 3]
```diff
@@ -103,4 +105,53 @@ class FlutterProject {
...
+          'io.flutter.devicelab',
+          ...options,
+          'plugintestapp'
+        ],
+      );
+    });
+    return _FlutterApp(directory, 'plugintestapp');
+  }
+
+  Future<void> build(String target) async {
```
Comment (adazh) [inline dev/devicelab/lib/tasks/plugin_tests.dart]: Curious whether `build` is app specific? Can we build a plugin project too?

Comment (collinjackson) [reply dev/devicelab/lib/tasks/plugin_tests.dart]: This only works for apps. For plugins, you have to build the example app.

File: dev/devicelab/lib/tasks/plugin_tests.dart (hunk 2 above)
Comment (collinjackson) [reply dev/devicelab/lib/tasks/plugin_tests.dart]: I could go either way on this. Since it's not a public API and is confined to this file it's easy to change later. I've consolidated everything into one class since you seem to prefer that.

**Review by adazh — APPROVED** [review]
