### PR TITLE
Fix CarouselView demo page is not functional using mouse scroll

### LINKED ISSUE #165265: CarouselView demo page not functional using mouse scroll
This may be a docs/sample bug.  I'm aware of #154618, but my main concern is that the **web demo** for https://api.flutter.dev/flutter/material/CarouselView-class.html does not work **on the web**.

When I saw the sample didn't work, I searched the page for any mention of "web" and didn't find any, so I  was about to log a bug but found #154618 in a search. 

I think the sample should include the workaround provided in the comments for #154618, i.e. the `scrollBehavior: MyCustomScrollBehavior()` code, so that the sample works and devs don't have to hunt for a comment in a bug to make CarouselView work on the web (and probably other systems that are mouse-based).  Ideally the text could mention `MaterialScrollBehavior` and explain that this is necessary for mouse-based systems.

Even better, it would be nice if CarouselView just worked on all platforms without that `scrollBehavior: MyCustomScrollBehavior()` patch to MaterialApp, but I recognize there may be good reasons why it doesn't.

### PR DESCRIPTION
**Pull request by huycozy**
### Description
This PR seeks to refine the CarouselView API doc sample for Web and Desktop platforms. On these platforms, mouse dragging gestures do not provide natural behavior similar to other desktop applications. This PR will improve the documentation by suggesting appropriate approaches to users (either using Shift + mouse wheel to scroll the view horizontally or referring to the instructions for overriding the default ScrollBehavior if they still want to implement dragging on these platforms).

### Related issue
Fix https://github.com/flutter/flutter/issues/165265

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/carousel.dart [hunk 1]
```diff
@@ -107,6 +107,15 @@ import 'theme.dart';
...
 /// and [CarouselView.weighted] can build.
 ///
+/// On desktop and web running on desktop platforms, dragging to scroll with a mouse is disabled by default
+/// to align with the natural behavior found in other desktop applications.
+///
+/// Nevertheless, it remains feasible to scroll horizontally using a mouse by pressing Shift key while scrolling with the mouse wheel.
+///
+/// This behavior is dictated by the [ScrollBehavior], and can be changed by adding
+/// [PointerDeviceKind.mouse] to [ScrollBehavior.dragDevices].
+/// For more info on this, please refer to https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag
```
Comment (Piinks) [inline packages/flutter/lib/src/material/carousel.dart:117]:
```suggestion
/// On desktop and web running on desktop platforms, dragging to scroll with a mouse is disabled by default
/// to align with natural behavior.
///
/// To further align expected behavior like this, mouse input can scroll horizontally by pressing  the shift key while scrolling with the mouse wheel.
///
/// This key-driven behavior is dictated by the [ScrollBehavior.pointerAxisModifers], 
/// while [ScrollBehavior.dragDevices] manages what devices can drag a scrollable.
```

We don't need to refer to old breaking changes docs. They are not relevant to new users. :)

Comment (huycozy) [reply packages/flutter/lib/src/material/carousel.dart:117]: Thanks for reviewing this, Kate! The change looks much more seamless and intuitive.

**Review by QuncCccccc — APPROVED** [review]
LGTM. Thank you for adding the doc:)
