### PR TITLE
fix `DropdownMenu` crashes when provided menuStyle with small maximumSize

### LINKED ISSUE #162356: `DropdownMenu` crashes when provided `menuStyle` with small `maximumSize`
### Steps to reproduce

set `maximumSize` property of `menuStyle` to be smaller than the `DropdownMenu`

### Expected results

`maximumSize` property of `menuStyle` should be able to set the width of menu item smaller than the `DropdownMenu`

### Actual results

`DropdownMenu` would overwrite the `minimumSize` property of `menuStyle` to the width of the `Textfield`, The widget would throw when trying to set the width to be smaller than `Textfield`.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const DropApp());
}

class DropApp extends StatelessWidget {
  const DropApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(32.0),
          child: DropdownMenu<String>(
            width: 200.0,
            dropdownMenuEntries: [
              DropdownMenuEntry(
                  value: "1", label: "one this is a long long long text"),
              DropdownMenuEntry(
                  value: "2", label: "two this is a long long long text"),
            ],
            menuStyle: MenuStyle(
              maximumSize: WidgetStatePropertyAll(Size(150.0, 100.0)),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building _MenuPanel(dirty, dependencies:
[InheritedCupertinoTheme, _InheritedTheme, _LocalizationsScope-[GlobalKey#f400a]], state:
_MenuPanelState#b76a8):
BoxConstraints has non-normalized width constraints.
The offending constraints were:
  BoxConstraints(200.0<=w<=150.0, 0.0<=h<=100.0; NOT NORMALIZED)


```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-AU)
    • Flutter version 3.27.3 on channel stable at /Users/mainj/php/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c519ee916e (7 days ago), 2025-01-21 10:32:23 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2
```

</details>

### PR DESCRIPTION
**Pull request by PurplePolyhedron**
fix #162356
Previously `DropdownMenu` overwrites `minimumSize` in `menuStyle` to be the width of the `TextField`
Now it set the `minimumSize` to be the min between the width of the `TextField` and the width of `maximumSize`, so that the menu can be smaller than the `TextField`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 1]
```diff
@@ -3952,6 +3952,51 @@ void main() {
     textField = tester.widget(find.byType(TextField));
     expect(textField.textInputAction, TextInputAction.next);
   });
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:3954]: nit: should have a empty line between tests:)

**Review by QuncCccccc — APPROVED** [review]
Nice fix:)! LGTM!

**Review by hannah-hyj — APPROVED** [review]
LGTM!

**Comment by dkwingsmt** [comment]
@PurplePolyhedron Is this PR ready to go? If yes I can start the merging process. :) Thanks for your contribution!
