### PR TITLE
Fix example code just showing endless spinner when deployed from Windows

### LINKED ISSUE #14820: Animated Images "Example Code" just hangs on spinner in Gallery example app
Using current master (b6d8615aed8062e6e9d3dff7d340edf2982c4847) if I launch the Gallery app and go to "Animated Media" and then click on the "Example Code" icon on the top right, I just get a spinner - it never seems to finish loading (it doesn't break into the debugger or output anything to the console).

(This is not specific to `--preview-dart-2`, happens without it too)

### PR DESCRIPTION
**Pull request by DanTup**
Fixes #14820. The issue is that the code is split be `\n` and then put into a map. On Windows the key has a trailing `\r` which means the lookups don't find any code.

I made two changes:

1. If the code is not found, display a message rather than leaving it as null (which keeps the spinner visible)
2. Trim the code label before putting into the map

Happy to tweak this if you don't think they're the best fixes.

### CODE REVIEW

**Comment by xster** [comment]
Seems sensible. LGTM. Can you add a test to example_code_parser_test.dart to make sure we don't accidentally break it again in the future?

**Comment by DanTup** [comment]
Sure, will do!

**Comment by DanTup** [comment]
@xster Pushed two changes:

1. `.trimRight()` on the code as it's parsed (I didn't `.trim ()` because I don't want to destroy indenting, but I wanted to remove the \r so it's consistent - otherwise the test for Windows would need to expect \r's in there too)
2. Added a test which fails without my change (expects code, gets null) and passes with it (on Windows). I presume the CI runs these tests so we can confirm it didn't affect other platforms?

**Comment by xster** [comment]
Thanks for the test! LGTM. 

Ya, travis runs the test on all platforms.

File: examples/flutter_gallery/lib/gallery/example_code_parser.dart [hunk 1]
```diff
@@ -46,7 +46,7 @@ Future<Null> _parseExampleCode(AssetBundle bundle) async {
         codeTag = null;
       } else {
         // Add to the current block
-        codeBlock.add(line);
+        codeBlock.add(line.trimRight());
```
Comment (xster) [inline examples/flutter_gallery/lib/gallery/example_code_parser.dart]: I'd just add one comment on why trimRight here

**Review by xster — APPROVED** [review]

**Comment by DanTup** [comment]
@xster done! lmk if you're happy for me to merge this (or feel free to do it). Thanks!

**Comment by xster** [comment]
Thanks. You go ahead. Though it seems like the CI bot flaked. I restarted it. Please make sure it passed before merging.

**Comment by DanTup** [comment]
Builds all look green to me now :)
