### PR TITLE
Fix BottomNavigationBarItem tooltip defaults to label

### LINKED ISSUE #107036: Tooltip issues. (e.g. BottomNavigationBarItem no tooltip by default)
Flutter has some issues with tooltip for Windows Application. Tooltips are shown immediately on hover. That's annoying. On mobile you have to long press. Because you can't hover. We need some options or default behaviors.

- The tooltip needs delay. Define an option with milliseconds or boolean between 0ms and 300ms (or some other good value).

- Tooltips should not show the same state as the element where it comes from. For example: The [BottomNavigationBarItem](https://api.flutter.dev/flutter/widgets/BottomNavigationBarItem-class.html) should not show a tooltip. The default behavior should be changed. It currently just shows the label. That's really bad UX. By default the tooltip's should be not shown. The FAB already works in this way. You have to specify the tooltip property to show it. Current workaround to suppress tooltips: Set tooltip to empty string. 
demo

- Option to show tooltip only on long press as described in docs. Same behavior for Windows apps.

> The text to display in the tooltip for this widget, when the user <ins>long presses</ins> the item. 

It's a bad UX if everywhere floating tooltips. Especially if the tooltip is useless (same content).  

Tested with Flutter 3.0.4 (stable) on Windows.

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR updates `BottomNavigationBar` to not show a tooltip when `BottomNavigationBarItem.tooltip` is null (instead of displaying the label text). 

## Related Issue

Fixes https://github.com/flutter/flutter/issues/107036

## Tests

Updates 1 test.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/bottom_navigation_bar_item.dart [hunk 1]
```diff
@@ -81,12 +81,11 @@ class BottomNavigationBarItem {
   ///    the icons themselves.
   final Color? backgroundColor;
 
-  /// The text to display in the tooltip for this [BottomNavigationBarItem], when
-  /// the user long presses the item.
+  /// The text to display in the tooltip for this [BottomNavigationBarItem].
   ///
   /// The [Tooltip] will only appear on an item in a Material design [BottomNavigationBar], and
-  /// when the string is not empty.
+  /// when the string is neither empty nor null.
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/bottom_navigation_bar_item.dart:87]: I'd say something like this instead:
```dart
  /// A [Tooltip] will only appear on this item if `tooltip` is set to a non-empty string..
```

File: packages/flutter/lib/src/widgets/bottom_navigation_bar_item.dart [hunk 2]
```diff
@@ -81,12 +81,11 @@ class BottomNavigationBarItem {
   ///    the icons themselves.
   final Color? backgroundColor;
 
-  /// The text to display in the tooltip for this [BottomNavigationBarItem], when
-  /// the user long presses the item.
+  /// The text to display in the tooltip for this [BottomNavigationBarItem].
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/bottom_navigation_bar_item.dart:84]:
```suggestion
  /// The text to display in the [Tooltip] for this [BottomNavigationBarItem].
```

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Just some documentation nits.
