### PR TITLE
Reland "Update `FocusManager` platform check to include iOS"

### LINKED ISSUE #148475: Autofill Hints not populating in text fields on iOS with Flutter 3.22.0
### Steps to reproduce

1. Update Flutter to version 3.22.0.
2. Ensure .well-known/apple-app-site-association is correctly configured on the server.
3. Implement autofill hints in your Flutter app.
4. Test the autofill functionality on an iOS device.
5. Try to autofill with some saved credentials

### Expected results

Input fields should be automatically populated with relevant data when using autofill on iOS, similar to how it works on Android.

### Actual results

Autofill suggestions appear on iOS, but selecting a suggestion does not populate the input fields.

### Code sample

```dart
 AutofillGroup(
      child: Scaffold(
        body: GoldRippleGradientBackground(
          child: CustomScrollView(slivers: <Widget>[
            SliverFillRemaining(
              hasScrollBody: false,
              child: SafeArea(
                child: Padding(
                  padding:
                      const EdgeInsets.all(Dimensions.defaultScreenPadding),
                  child: Form(
                    key: formKey,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        const Spacer(),
                          TextFormField(
                            key: const Key('email_sign_in'),
                            autofillHints: const <String>[
                              AutofillHints.email,
                              AutofillHints.username
                            ],
                            decoration: InputDecoration(
                              labelText: context.strings.authEmailLabel,
                            )),
                          TextFormField(
                              key: const Key('password_sign_in'),
                              autofillHints: const <String>[
                                AutofillHints.password,
                              ],
                              decoration: InputDecoration(
                                labelText: context.strings.authPasswordLabel,
                          )),                      
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ]),
        ),
      ),
    );
```

### Screenshots or Video

https://github.com/flutter/flutter/assets/57009558/382d0e3a-840f-43a0-a758-24e63ae086dc

### Logs

_No response_

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1)
    • Flutter version 3.22.0 on channel stable at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (7 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK  path
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = path
    • Java binary at: path
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Network resources
    • All expected network resources are available.

### PR DESCRIPTION
**Pull request by nate-thegrate**
The [original PR](https://github.com/flutter/flutter/pull/148612) ended up having incompatible changes with #148067.

### CODE REVIEW

**Comment by Renzo-Olivares** [comment]
I think `FocusManager.listenToApplicationLifecycleChangesIfSupported` should also be updated to reflect this new platform check.

**Comment by nate-thegrate** [comment]
@Renzo-Olivares I hadn't noticed that the `listenToApplicationLifecycleChangesIfSupported` method was added, thank you!

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 1]
```diff
@@ -1532,12 +1532,21 @@ class FocusManager with DiagnosticableTreeMixin, ChangeNotifier {
     if (kFlutterMemoryAllocationsEnabled) {
       ChangeNotifier.maybeDispatchObjectCreation(this);
     }
-    if (kIsWeb || defaultTargetPlatform != TargetPlatform.android) {
+    final bool mobileDevice = switch (defaultTargetPlatform) {
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/focus_manager.dart:1535]: Consider moving this to a private getter so it can be reused in all places in this file.

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 2]
```diff
@@ -1554,6 +1549,14 @@ class FocusManager with DiagnosticableTreeMixin, ChangeNotifier {
     rootScope._manager = this;
   }
 
+  // Used in the constructor and in [listenToApplicationLifecycleChangesIfSupported]
+  // to check if the app is running on a native mobile platform.
+  static final bool _mobileDevice = switch (defaultTargetPlatform) {
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/focus_manager.dart:1554]: I think we should probably add `kIsWeb` to this check, so if we ever do remove it, we only have to remove it from one place. Also consider moving the comments regarding Android/iOS support above this variable.

File: packages/flutter/test/widgets/focus_manager_test.dart [hunk 3]
```diff
@@ -354,9 +354,13 @@ void main() {
...
-    testWidgets('FocusManager ignores app lifecycle changes on Android.', (WidgetTester tester) async {
-      final bool shouldRespond = kIsWeb || defaultTargetPlatform != TargetPlatform.android;
-      if (shouldRespond) {
+    testWidgets('FocusManager ignores app lifecycle changes on Android and iOS.', (WidgetTester tester) async {
+      final bool mobileDevice = switch (defaultTargetPlatform) {
+        TargetPlatform.android || TargetPlatform.iOS => false,
+        TargetPlatform.fuchsia || TargetPlatform.linux => true,
+        TargetPlatform.windows || TargetPlatform.macOS => true,
+      };
+      if (kIsWeb || mobileDevice) {
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/focus_manager_test.dart:363]: What do you think about removing this check, and instead specifying `Android` and `iOS` as the test variants, and skipping the web test? I think as the test stands now it is only running on `Android`.

File: packages/flutter/test/widgets/focus_manager_test.dart [hunk 4]
```diff
@@ -387,8 +391,12 @@ void main() {
     });
 
     testWidgets('FocusManager responds to app lifecycle changes.', (WidgetTester tester) async {
-      final bool shouldRespond = kIsWeb || defaultTargetPlatform != TargetPlatform.android;
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/focus_manager_test.dart:390]: Similar question with the above test, can we just rely on the test variants here?

File: packages/flutter/test/widgets/focus_manager_test.dart (hunk 3 above)
Comment (nate-thegrate) [reply packages/flutter/test/widgets/focus_manager_test.dart]: Can't believe I didn't notice that you can specify a test variant! Thanks for the suggestion.

File: packages/flutter/test/widgets/focus_manager_test.dart [hunk 5]
```diff
@@ -354,9 +354,8 @@ void main() {
       logs.clear();
     }, variant: KeySimulatorTransitModeVariant.all());
 
-    testWidgets('FocusManager ignores app lifecycle changes on Android.', (WidgetTester tester) async {
-      final bool shouldRespond = kIsWeb || defaultTargetPlatform != TargetPlatform.android;
-      if (shouldRespond) {
+    testWidgets('FocusManager ignores app lifecycle changes on Android and iOS.', (WidgetTester tester) async {
+      if (kIsWeb) {
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/focus_manager_test.dart:358]: nit: consider using `skip: kIsWeb`.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM w/ small nit. Thank you for the quick changes and contribution!

File: packages/flutter/test/widgets/focus_manager_test.dart [hunk 6]
```diff
@@ -354,44 +354,39 @@ void main() {
...
+        expect(focusNode.hasPrimaryFocus, isTrue);
 
-      await setAppLifecycleState(AppLifecycleState.resumed);
-      expect(focusNode.hasPrimaryFocus, isTrue);
-    });
+        await setAppLifecycleState(AppLifecycleState.resumed);
+        expect(focusNode.hasPrimaryFocus, isTrue);
+      },
+      skip: kIsWeb, // [intended]
+      variant: TargetPlatformVariant.only(TargetPlatform.iOS, TargetPlatform.android),
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/focus_manager_test.dart:386]: I think this should be

`variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.android, TargetPlatform.iOS })`.

**Comment by techouse** [comment]
When will this land in stable? It has been baking in master for over a month now.

**Comment by nate-thegrate** [comment]
Hi @techouse, I appreciate your concern! Unfortunately, a comment like this one contravenes our [issue hygiene guidelines](https://github.com/flutter/flutter/blob/1c9c375e4e33e638aa6be3a25e466f494cc1987e/docs/contributing/issue_hygiene/README.md#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs).

But to answer your question: it will land in stable once someone makes a cherry-pick pull request, and that PR is approved. I was planning to manually create a PR within the next day or two!
