### PR TITLE
[flutter_tools] don't elapse real time during fallback test

### LINKED ISSUE #54332: fallback_discovery_tests are taking 10+ seconds to run
Failure cases like `Selects mdns discovery if VM service connecton fails due to Sentinel` are really running the backoff time.

https://github.com/flutter/flutter/blob/77ea848c462eb0eafa9a01d76a678317d7470890/packages/flutter_tools/lib/src/ios/fallback_discovery.dart#L187

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

don't elapse real time during the test, by injecting a "Delay" function. This was simpler than using FakeAsync since we don't need to control any other timers.

Fixes https://github.com/flutter/flutter/issues/54332

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart [hunk 1]
```diff
@@ -42,14 +52,16 @@ class FallbackDiscovery {
     @required Logger logger,
     @required ProtocolDiscovery protocolDiscovery,
     @required Usage flutterUsage,
-    Future<VmService> Function(String wsUri, {Log log}) vmServiceConnectUri =
+    VmServiceConnector vmServiceConnectUri =
       vm_service_io.vmServiceConnectUri,
+    Delay delay = _defaultDelay,
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/fallback_discovery.dart:57]: Make this name more descriptive, delay of what?

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart [hunk 2]
```diff
@@ -184,7 +197,7 @@ class FallbackDiscovery {
       // tool waits for a connection to be reasonable. If the vmservice cannot
       // be connected to in this way, the mDNS discovery must be reached
       // sooner rather than later.
-      await Future<void>.delayed(const Duration(seconds: kDelaySeconds));
+      await _delay(const Duration(seconds: kDelaySeconds));
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/fallback_discovery.dart:200]: I don't love this pattern, it seems very one-off, but I don't really have a better suggestions.
@zanderso what do you think of this pattern?

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart [hunk 3]
```diff
@@ -13,6 +13,16 @@ import '../mdns_discovery.dart';
 import '../protocol_discovery.dart';
 import '../reporting/reporting.dart';
 
+typedef Delay = Future<void> Function(Duration);
+
+typedef VmServiceConnector = Future<VmService> Function(String, {Log log});
+
+// constructors cannot be torn off, otherwise it would be better to use
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/ios/fallback_discovery.dart:20]: Dart 1 had generalized tear-offs briefly: https://github.com/dart-lang/sdk/issues/27518 =(

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart (hunk 2 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/ios/fallback_discovery.dart:200]: There's precedent for using `FakeAsync` to drive time from tests. We should be giving that a try first before resorting to something like this. If `FakeAsync` is still too heavyweight for the test for some reason, another alternative would be to create a custom `Zone` with `createTimer` callback in its `ZoneSpecification` to wrap the operation, but that could also be error prone if the `Zone` doesn't capture the right set of stuff.

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/ios/fallback_discovery.dart:20]: 😿

File: packages/flutter_tools/lib/src/ios/fallback_discovery.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/ios/fallback_discovery.dart]: This seems pretty straightforward compared to creating a Zone (or dealing with zones at all).

The issue with fakeAsync is that the test still needs to manually elapse time. As written, the ProtocolDiscovery doesn't expose a hook so that a test could know when it is blocking and needs the FakeAsync to elapse again

**Comment by zanderso** [comment]
Alternately, could `FallbackDiscovery.discover()` take an optional named `Duration` argument that defaults to `const Duration(seconds: kDelaySeconds)`, which the tests could pass as 0?

**Comment by jonahwilliams** [comment]
RIGHT 🤦‍♂️ 

That is much simpler

**Review by zanderso — APPROVED** [review]

**Review by jmagman — APPROVED** [review]
LGTM!
