### PR TITLE
Fix bug with back gesture with a persistent bottom sheet showing.

### LINKED ISSUE #6451: Back Gesture away from persistent bottom sheet = dead Gallery
1.  Open Gallery > Persistent Bottom Sheet
2.  Click the button to open the sheet.
3.  With the sheet still showing, back-gesture back to the main page.
4.  Click on anything else, your routes are now in a bad state, app will go black or other badness.

See video.
https://youtu.be/kI-dzP66omQ

### PR DESCRIPTION
**Pull request by mpcomplete**
Fixes https://github.com/flutter/flutter/issues/6451

### CODE REVIEW

**Comment by abarth** [comment]
Test?

**Comment by mpcomplete** [comment]
Test added.

File: packages/flutter/lib/src/material/page.dart [hunk 1]
```diff
@@ -141,8 +141,11 @@ class _CupertinoBackGestureController extends NavigationGestureController {
     }
 
     // Don't end the gesture until the transition completes.
+    AnimationStatus status = controller.status;
```
Comment (abarth) [inline packages/flutter/lib/src/material/page.dart]: final

File: packages/flutter/lib/src/material/scaffold.dart [hunk 2]
```diff
@@ -771,12 +771,16 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
   }
 
   void _handleDragEnd(DragEndDetails details) {
-    _backGestureController?.dragEnd(details.velocity.pixelsPerSecond.dx / context.size.width);
+    bool willPop = _backGestureController?.dragEnd(details.velocity.pixelsPerSecond.dx / context.size.width);
```
Comment (abarth) [inline packages/flutter/lib/src/material/scaffold.dart]: final

File: packages/flutter/lib/src/material/scaffold.dart [hunk 3]
```diff
@@ -771,12 +771,16 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
...
+    if (willPop == true)
```
Comment (abarth) [inline packages/flutter/lib/src/material/scaffold.dart]: Rather than explicitly testing against `true` here, I'd put a `??` on line 774 to always store a non-null value in `willPop`.  It just makes it less likely someone will refactor this code in the future and remove the null handling.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 4]
```diff
@@ -771,12 +771,16 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
...
+      _currentBottomSheet?.close();
     _backGestureController = null;
   }
 
   void _handleDragCancel() {
-    _backGestureController?.dragEnd(0.0);
+    bool willPop = _backGestureController?.dragEnd(0.0);
+    if (willPop == true)
```
Comment (abarth) [inline packages/flutter/lib/src/material/scaffold.dart]: ditto

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 5]
```diff
@@ -217,8 +217,10 @@ abstract class NavigationGestureController {
   void dragUpdate(double fractionalDelta);
 
   /// The drag gesture has ended with a horizontal motion of
-  /// [fractionalVelocity] as a fraction of screen width per second.
-  void dragEnd(double fractionalVelocity);
+  /// [fractionalVelocity] as a fraction of screen width per second. Returns
```
Comment (abarth) [inline packages/flutter/lib/src/widgets/navigator.dart]: I'd put the sentence that starts with "Returns" on a new line after a blank (comment) line.  That will make the docs look slightly prettier on the web site:

```dart
/// [fractionalVelocity] as a fraction of screen width per second.
///
/// Returns...
```

File: packages/flutter/test/widget/page_transitions_test.dart [hunk 6]
```diff
@@ -13,6 +13,38 @@ class TestOverlayRoute extends OverlayRoute<Null> {
   Widget _build(BuildContext context) => new Text('Overlay');
 }
 
+class PersistentBottomSheetTest extends StatefulWidget {
+  PersistentBottomSheetTest({Key key}) : super(key: key);
```
Comment (abarth) [inline packages/flutter/test/widget/page_transitions_test.dart]: Space after the `{` and before the `}`

**Review by abarth — APPROVED** [review]
LGTM
