### PR TITLE
fix PopupMenuButton unmounted exception when updating position

### LINKED ISSUE #163477: PopupMenuRoute crashes sometimes on drawFrame
### Steps to reproduce

1. Add PopUpMenuButton and show it
2. While the menu is being displayed, trigger drawFrame (such that PopupMenuRoute gets rebuilt)
3. _positionBuilder inside PopupMenuRoute crashes due to the stale context

This crash only happens with this commit https://github.com/flutter/flutter/commit/efa7d52303e3e565027b2927e6b2597d9502766f. Seems like positionBuilder now calculates position dynamically, but it holds to the invalidated context sometimes.

Crash trace
```
_TypeError: Null check operator used on a null value

at Navigator.of	(navigator.dart:2894)

at PopupMenuButtonState._positionBuilder	(popup_menu.dart:1522)

at _PopupMenuRoute.buildPage.<anonymous closure>	(popup_menu.dart:972)

at _LayoutBuilderElement._rebuildWithConstraints.updateChildCallback	(layout_builder.dart:201)
at BuildOwner.buildScope	(framework.dart:3056)
at _LayoutBuilderElement._rebuildWithConstraints	(layout_builder.dart:240)
at _LayoutBuilderElement._rebuildWithConstraints	(layout_builder.dart:196)
at RenderObject.invokeLayoutCallback.<anonymous closure>	(object.dart:2827)
at PipelineOwner._enableMutationsToDirtySubtrees	(object.dart:1161)
at RenderObject.invokeLayoutCallback	(object.dart:2826)
at RenderConstrainedLayoutBuilder.rebuildIfNecessary	(layout_builder.dart:293)
at _RenderLayoutBuilder.performLayout	(layout_builder.dart:390)
at RenderObject.layout	(object.dart:2715)
at RenderProxyBoxMixin.performLayout	(proxy_box.dart:115)
at RenderObject.layout	(object.dart:2715)
at RenderProxyBoxMixin.performLayout	(proxy_box.dart:115)
at RenderObject.layout	(object.dart:2715)
at RenderProxyBoxMixin.performLayout	(proxy_box.dart:115)
at RenderObject.layout	(object.dart:2715)
at RenderProxyBoxMixin.performLayout	(proxy_box.dart:115)
at RenderObject.layout	(object.dart:2715)
at RenderProxyBoxMixin.performLayout	(proxy_box.dart:115)
at RenderOffstage.performLayout	(proxy_box.dart:3750)
at RenderObject.layout	(object.dart:2715)
at RenderProxyBoxMixin.performLayout	(proxy_box.dart:115)
at RenderObject.layout	(object.dart:2715)
at _RenderTheaterMixin.layoutChild	(overlay.dart:1076)
at _RenderTheater.performLayout	(overlay.dart:1422)
at RenderObject._layoutWithoutResize	(object.dart:2548)
at PipelineOwner.flushLayout	(object.dart:1112)
at PipelineOwner.flushLayout	(object.dart:1125)
at RendererBinding.drawFrame	(binding.dart:616)
at WidgetsBinding.drawFrame	(binding.dart:1231)
at RendererBinding._handlePersistentFrameCallback	(binding.dart:482)
at RendererBinding._handlePersistentFrameCallback	(binding.dart:481)
at SchedulerBinding._invokeFrameCallback	(binding.dart:1442)
at SchedulerBinding.handleDrawFrame	(binding.dart:1355)
at SchedulerBinding._handleDrawFrame	(binding.dart:1208)
at SchedulerBinding._handleDrawFrame	(binding.dart:1190)
at _invoke	(hooks.dart:316)
at PlatformDispatcher._drawFrame	(platform_dispatcher.dart:428)
at _drawFrame	(hooks.dart:288)
at _drawFrame	(hooks.dart:286)
```

### Expected results

Popup menu stays displayed

### Actual results

App Crashes

### Code sample

<>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
✓] Flutter (Channel google3, on Debian GNU/Linux rodete 6.10.11-1rodete2-amd64, locale en_US.UTF-8) [93ms]
    • Framework revision 5944d992ac (11 days ago), 2025-02-06T00:00:00.000
    • Engine revision 5944d992ac
    • Dart version 548dcc7a54

[✓] Android toolchain - develop for Android devices (Android SDK version Stable) [93ms]
    • Android SDK at google3
    • Platform Stable, build-tools Stable
    • Java binary at: /opt/android-studio-with-blaze-stable/jbr/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[!] Flutter IDE Support (No supported IDEs installed) [0ms]
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (1 available) [22ms]
    • Linux (desktop) • linux • linux-x64 • Debian GNU/Linux rodete 6.10.11-1rodete2-amd64

```

</details>

### PR DESCRIPTION
**Pull request by sstasi95**
This PR fixes an exception thrown when trying to update an unmounted PopupMenuButton's position, which can happen when a layout change is triggered during PopupMenuButton's pop animation (see issue's attached video).
A workaround is to set `popUpAnimationStyle: AnimationStyle.noAnimation`.
This PR fixes it by returning the last known position if the button is unmounted.

Exception thrown:` FlutterError (This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.)`

Code that causes the exception: `final PopupMenuThemeData popupMenuTheme = PopupMenuTheme.of(context);`

Fixes #163477 

Tested both on stable (3.29.2) and master (a0b1b325341)

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/popup_menu_test.dart [hunk 1]
```diff
@@ -2863,6 +2863,48 @@ void main() {
...
+        ),
+      ),
+    );
+
+    await tester.showKeyboard(find.byType(TextField));
+
+    await tester.tap(find.byKey(buttonKey));
+    await tester.pumpAndSettle();
+
+    // TODO(sstasi95): here we should trigger a layout change to test the fix
```
Comment (navaronbracke) [inline packages/flutter/test/material/popup_menu_test.dart:2901]: You can try pumping an unrelated widget with the `tester` (I.e. a SizedBox), after the button is tapped, to trigger the unmounting of the popup menu.

File: packages/flutter/test/material/popup_menu_test.dart [hunk 2]
```diff
@@ -2863,6 +2863,48 @@ void main() {
...
+    await tester.tap(find.text('ACTION'));
+    await tester.pumpAndSettle();
+
+    expect(find.text('ACTION'), findsNothing);
```
Comment (navaronbracke) [inline packages/flutter/test/material/popup_menu_test.dart:2905]: We should also check that no error is thrown.

```suggestion
    expect(find.text('ACTION'), findsNothing);
    expect(tester.takeException(), isNull);
```

File: packages/flutter/test/material/popup_menu_test.dart (hunk 1 above)
Comment (sstasi95) [reply packages/flutter/test/material/popup_menu_test.dart:2901]: I've tried but it's not enough, we should also update the layout after the popup menu is unmounted but when is still visible (during the pop animation), as you can see in [this screen recording](https://github.com/flutter/flutter/issues/163477#issuecomment-2772303456). This way the `_positionBuilder` method will be called on an unmounted popup menu.

**Comment by Piinks** [comment]
Hey @sstasi95 it looks like this never entered our review queue since this is a draft. Would you like to move forward with this change?

**Comment by sstasi95** [comment]
Hi @Piinks, sure. I left it as a draft because I wasn't able to write a test for it, I'll mark it ready for review now

**Comment by dkwingsmt** [comment]
Sorry for the late review and for drafting the PR! I've managed to rewrite your test in the following way, which breaks before your fix and passes after your fix.
```dart
  // Regression test for https://github.com/flutter/flutter/issues/163477
  testWidgets("PopupMenu's overlay can be rebuilt even when the button is unmounted", (
    WidgetTester tester,
  ) async {
    final GlobalKey buttonKey = GlobalKey();

    late StateSetter setState;
    bool showButton = true;

    Widget widget({required Size viewSize}) {
      return Center(
        child: SizedBox(
          width: viewSize.width,
          height: viewSize.height,
          child: MaterialApp(
            home: Material(
              child: StatefulBuilder(builder: (BuildContext context, StateSetter innerSetState) {
                setState = innerSetState;
                return showButton
                        ? PopupMenuButton<int>(
                          key: buttonKey,
                          popUpAnimationStyle: const AnimationStyle(
                            reverseDuration: Duration(milliseconds: 400),
                          ),
                          itemBuilder: (BuildContext context) {
                            return <PopupMenuEntry<int>>[
                              PopupMenuItem<int>(
                                value: 1,
                                child: const Text('ACTION'),
                                onTap: () {},
                              ),
                            ];
                          },
                        )
                        : Container();
                }),
              ),
            ),
          ),
      );
    }

    // Pump a button
    await tester.pumpWidget(widget(viewSize: const Size(500, 500)));

    // Tap the button to show the menu
    await tester.tap(find.byKey(buttonKey));
    await tester.pumpAndSettle();
    expect(find.text('ACTION'), findsOne);
    expect(find.byKey(buttonKey), findsOne);

    // Hide the button. The menu still shows since it's placed on a separate route.
    setState(() {
      showButton = false;
    });
    await tester.pump();
    expect(find.text('ACTION'), findsOne);
    expect(find.byKey(buttonKey), findsNothing);

    // Resize the view, causing the menu to rebuild. Before the fix, this
    // rebuild would lead to a crash, because it relies on context of the button,
    // which has been unmounted.
    await tester.pumpWidget(widget(viewSize: const Size(300, 300)));

    expect(tester.takeException(), isNull);
  });
```

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 3]
```diff
@@ -1520,7 +1520,13 @@ class PopupMenuButton<T> extends StatefulWidget {
 /// of your button state.
 class PopupMenuButtonState<T> extends State<PopupMenuButton<T>> {
   bool _isMenuExpanded = false;
+  RelativeRect? _lastPosition;
+
   RelativeRect _positionBuilder(BuildContext _, BoxConstraints constraints) {
+    if (!mounted) {
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/popup_menu.dart:1574]: Probably add the following comment:
```dart
    // When the route is displayed, the `_positionBuilder` closure is stored.
    // Even after the button has been unmounted and the context becomes invalid,
    // the route might keep displaying, and `_positionBuilder` must continue to
    // work in that case.
```

**Review by dkwingsmt — COMMENTED** [review]
Everything else looks good to me! Thank you for the investigation.

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 4]
```diff
@@ -1568,7 +1568,17 @@ class PopupMenuButton<T> extends StatefulWidget {
...
+      // When the route is displayed, the `_positionBuilder` closure is stored.
+      // Even after the button has been unmounted and the context becomes invalid,
+      // the route might keep displaying, and `_positionBuilder` must continue to
+      // work in that case.
+      return _lastPosition ?? RelativeRect.fromSize(Rect.zero, constraints.biggest);
+    }
+
     final PopupMenuThemeData popupMenuTheme = PopupMenuTheme.of(context);
     final RenderBox button = context.findRenderObject()! as RenderBox;
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/popup_menu.dart:1583]: Since this is already implemented this way, so not blocking the merge. but if the goal is to pin the popup to this button with a delta offset, we should use compositedtrasnformfollower and target/leaderlayer. Things will just be simpler with no mounted/unmounted problem

**Review by chunhtai — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/popup_menu.dart (hunk 4 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/material/popup_menu.dart:1583]: @chunhtai Are you talking about https://github.com/flutter/flutter/pull/169814 ?

Comment (chunhtai) [reply packages/flutter/lib/src/material/popup_menu.dart:1583]: yes, that is right. although looking at the comment it mentioned some bug about using compsitedfollower, which is new to me.

**Review by dkwingsmt — APPROVED** [review]
