### PR TITLE
Regression tests should verify that debug are not set

### LINKED ISSUE #7082: Regression tests should conclude by ensuring that debug flags aren't set
Add something to the test framework that verifies that the debug flags  aren't enabled at the end of each test (per https://github.com/flutter/flutter/pull/7067#issuecomment-263660876).

Avoid a doing something like this again: https://github.com/flutter/flutter/pull/7059#discussion_r90071349

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes #7082

### CODE REVIEW

**Comment by HansMuller** [comment]
@Hixie

File: packages/flutter_test/lib/src/binding.dart [hunk 1]
```diff
@@ -395,6 +395,18 @@ abstract class TestWidgetsFlutterBinding extends BindingBase
     assert(debugAssertNoTransientCallbacks(
       'An animation is still running even after the widget tree was disposed.'
     ));
+    assert(() {
```
Comment (Hixie) [inline packages/flutter_test/lib/src/binding.dart]: we've moved to throwing a FlutterError rather than having a string in the assert

File: packages/flutter/lib/src/rendering/debug.dart [hunk 2]
```diff
@@ -89,3 +104,32 @@ List<String> debugDescribeTransform(Matrix4 transform) {
   matrix.removeLast();
   return matrix;
 }
+
+/// Returns true if none of the rendering debug variables have been changed.
+///
+/// This function is used by the test framework to ensure that debug variables
+/// haven't been inadvertently changed.
+bool debugAllRenderVarsUnset() {
+  return !(
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/debug.dart]: ideally these debug*Unset functions would have their bodies entirely in an assert() (maybe except for a result variable declared before and returned after). That way the debug variables aren't ever accessed outside asserts, which will be easier for the compiler to prove.

File: packages/flutter/lib/src/rendering/debug.dart [hunk 3]
```diff
@@ -7,40 +7,55 @@ import 'package:flutter/rendering.dart';
 
 export 'package:flutter/foundation.dart' show debugPrint;
 
+// WARNING: Any changes to this file should be reflected in the
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/debug.dart]: s/WARNING:// - this is a minor thing, we don't want to devalue the word "WARNING" :-)

**Comment by Hixie** [comment]
Did you check if this would have caught the earlier issue?

**Comment by HansMuller** [comment]
I did and it does.

File: packages/flutter_test/lib/src/binding.dart [hunk 4]
```diff
@@ -395,6 +395,15 @@ abstract class TestWidgetsFlutterBinding extends BindingBase
     assert(debugAssertNoTransientCallbacks(
       'An animation is still running even after the widget tree was disposed.'
     ));
+    assert(debugAllRenderVarsUnset(
```
Comment (Hixie) [inline packages/flutter_test/lib/src/binding.dart]: looks like the convention is debugAssertFoo... rather than just debugFoo, but I'll leave that up to you.

LGTM.

Comment (HansMuller) [inline packages/flutter_test/lib/src/binding.dart]: You are correct, I will bend to convention :-)
