### PR TITLE
Fix DropdownMenuFormField does not clear text field content on reset …

### LINKED ISSUE #174578: DropdownMenuFormField does not reset when calling FormState.reset
### Steps to reproduce

The new DropdownMenuFormField does not reset its value like other FormField widgets when FormState.reset is invoked.

### Expected results

The DropdownMenuFormField should reset its value, just like a TextFormField does.

### Actual results

The DropdownMenuFormField retains its value after FormState.reset is called.

### Code sample

You can check out this dartpad:

https://dartpad.dev/?id=ca0e76d6b65ece8922aad012bd135793

### Logs

_No response_

### Flutter Doctor output

[√] Flutter (Channel stable, 3.35.1, on Microsoft Windows [Versi¢n 10.0.26100.4946], locale es-MX)
[√] Windows Version (Windows 11 or higher, 24H2, 2009)
[√] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.14.11)
[√] Android Studio (version 2025.1.2)
[√] VS Code (version 1.103.2)
[√] Connected device (4 available)
[√] Network resources

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes `DropdownMenuFormField` not clearing the text field value when the form is reset and DropdownMenuFormField.initialSelection is null.

## Related Issue

Fixes [DropdownMenuFormField does not reset when calling FormState.reset](https://github.com/flutter/flutter/issues/174578) 

## Tests

Adds 2 tests.

### CODE REVIEW

File: packages/flutter/lib/src/material/dropdown_menu_form_field.dart [hunk 1]
```diff
@@ -139,8 +139,14 @@ class DropdownMenuFormField<T> extends FormField<T> {
 class _DropdownMenuFormFieldState<T> extends FormFieldState<T> {
   DropdownMenuFormField<T> get _dropdownMenuFormField => widget as DropdownMenuFormField<T>;
 
+  // The controller used to restore the selected item.
   RestorableTextEditingController? _restorableController;
 
+  // The controller used to reset the content of the DropdownMenu inner TextField.
```
Comment (justinmc) [inline packages/flutter/lib/src/material/dropdown_menu_form_field.dart:145]: Thanks for labeling these.

File: packages/flutter/test/material/dropdown_menu_form_field_test.dart [hunk 2]
```diff
@@ -967,6 +968,83 @@ void main() {
...
+      // After reset the text field content is cleared.
+      fieldKey.currentState!.reset();
+      await tester.pump();
+
+      expect(fieldKey.currentState!.value, null);
+      final TextField textField = tester.widget(find.byType(TextField));
+      expect(
+        textField.controller?.value,
+        const TextEditingValue(selection: TextSelection.collapsed(offset: 0)),
+      );
```
Comment (justinmc) [inline packages/flutter/test/material/dropdown_menu_form_field_test.dart:1006]: Nit: Do you think it would add value to `expect` that the value is not empty before the call to `reset`?

Comment (justinmc) [reply packages/flutter/test/material/dropdown_menu_form_field_test.dart:1006]: Same comment for the next test.

**Review by justinmc — APPROVED** [review]
LGTM with a nit. Thank you Bruno!
