### PR TITLE
Try a mildly prettier FlutterError and make it less drastic in release mode

### LINKED ISSUE #40452: Disable "Red Screen of Death" in Release mode
## Use case

When a widget crashes (because it got bad data passed to its parameters for example), we make the area that widget previously occupied turn red, with the error message. This happens in debug _AND_ release mode. 

People can currently override this behavior by setting a custom onError handler or creating a custom ErrorWidget builder (see examples discussed [here](https://github.com/flutter/flutter/issues/24950) and [here](https://github.com/flutter/flutter/issues/10695) ), but this unfortunately means that it's potentially less obvious what's going on while debugging and this default behavior scares off potential users (not everyone knows they can implement the aforementioned options, and it was cited in the team's recent Japanese trip report as a reason why users there are hesitant about Flutter). 

I have heard this request from multiple independent sources myself as well.

[Related issue](https://github.com/flutter/flutter/issues/29233) around overflow rendering in release mode.

## Proposal

Only have this behavior with the red screen in _debug_ mode. 

Ideal behavior if a widget has crashed in release mode would be to keep rendering what it shows the moment before crash (like when you're debugging and it freezes when an exception occurs). I seem to recall readin in another bug that may be not possible, in which case, a more "external-user-friendly" option might be to just show a blank widget with whatever the app's default background color is. Logging to a console should still take place, with options to connect to things like Crashlytics, but we shouldn't expose these problems to the end users of the apps.

### PR DESCRIPTION
**Pull request by Hixie**
Also, more documentation and tests.

Fixes https://github.com/flutter/flutter/issues/40452 (maybe).

### CODE REVIEW

**Comment by Hixie** [comment]
cc @goderbauer

**Review by darielopper — APPROVED** [review]

File: packages/flutter/lib/src/widgets/framework.dart [hunk 1]
```diff
@@ -3810,13 +3810,62 @@ typedef ErrorWidgetBuilder = Widget Function(FlutterErrorDetails details);
...
+/// ```dart
+/// import 'package:flutter/material.dart';
+///
+/// void main() {
+///   ErrorWidget.builder = (FlutterErrorDetails details) {
+///     bool inDebug = false;
+///     assert(() { inDebug = true; return true; }());
+///     // In debug mode, use the normal error widget which shows
+///     // the error message:
+///     if (inDebug)
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/framework.dart]: Just use `if (!kReleaseMode)`?

https://master-api.flutter.dev/flutter/foundation/kReleaseMode-constant.html

File: packages/flutter/lib/src/rendering/error.dart [hunk 2]
```diff
@@ -82,39 +77,87 @@ class RenderErrorBox extends RenderBox {
...
+
   /// The color to use when painting the background of [RenderErrorBox] objects.
-  static Color backgroundColor = const Color(0xF0900000);
+  ///
+  /// Defaults to red in debug mode, a light gray otherwise.
+  static Color backgroundColor = _initBackgroundColor();
+
+  static Color _initBackgroundColor() {
+    Color result = const Color(0xF0C0C0C0);
+    assert(() {
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/error.dart]: To make the intend of these asserts clearer: Maybe use kReleaseMode or kProfileMode instead?

File: packages/flutter/lib/src/widgets/framework.dart [hunk 3]
```diff
@@ -3810,13 +3810,62 @@ typedef ErrorWidgetBuilder = Widget Function(FlutterErrorDetails details);
...
+///         'Error!',
+///         style: TextStyle(color: Colors.yellow),
+///         textDirection: TextDirection.ltr,
+///       ),
+///     );
+///   };
+///   // Here we would normally runApp() the root widget, but to demonstrate
+///   // the error handling we artificially fail:
+///   return runApp(Builder(
+///     builder: (BuildContext context) { throw 'oh no, an error'; },
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/framework.dart]: nit: I would format it as follows to make it visually clearer that this throws:
```suggestion
///     builder: (BuildContext context) { 
///        throw 'oh no, an error'; 
///     },
```

File: packages/flutter/lib/src/widgets/framework.dart [hunk 4]
```diff
@@ -3835,17 +3884,26 @@ class ErrorWidget extends LeafRenderObjectWidget {
...
   ///    invoked, and which can also be configured to control how errors are
   ///    reported.
-  static ErrorWidgetBuilder builder = (FlutterErrorDetails details) => ErrorWidget(details.exception);
+  static ErrorWidgetBuilder builder = _defaultErrorWidgetBuilder;
 
-  /// The message to display.
-  final String message;
-  final FlutterError _flutterError;
+  static Widget _defaultErrorWidgetBuilder(FlutterErrorDetails details) {
+    String message = '[sic]'; // could also consider "‽"
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/framework.dart]: Why not just `[error]` to make it clear that this is not supposed to be here, but something went wrong. Or something a little more more friendly like "Oh snap, something went wrong here" (borrowing from Chrome).

If I see [sic] in an app I've no idea what that's supposed to be....

**Review by goderbauer — COMMENTED** [review]
Looks fine. I do think that even in release mode it should be clearer that it's an (unexpected) error state.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/framework.dart]: That would make profile and release mode different, no?

File: packages/flutter/lib/src/widgets/framework.dart (hunk 4 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/framework.dart]: Yeah, I wasn't sure what to put here.

I don't want to put "error" or something like that because the whole point is to make this friendly.

I don't want to put ":-(" or an emoji or "Oh snap" or similar, because that would leak our personality into Flutter apps, and the whole point is to not do that.

Maybe it should just not show any text at all?

File: packages/flutter/lib/src/rendering/error.dart (hunk 2 above)
Comment (Hixie) [reply packages/flutter/lib/src/rendering/error.dart]: I'd really rather we got rid of those constants entirely...

Comment (goderbauer) [reply packages/flutter/lib/src/rendering/error.dart]: To me, the constants make the intent clearer and the code more readable then the assert wrapping.

File: packages/flutter/lib/src/widgets/framework.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/framework.dart]: `if (!kReleaseMode && !kProfileMode)` :)

File: packages/flutter/lib/src/widgets/framework.dart (hunk 4 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/framework.dart]: If that's the goal I wouldn't put any text at all (that would also get around the problem that any string we put here really needs to be localized).

However, I also find that odd from a usability perspective. As a user I'd much rather know that something is broken over seeing a state that looks kinda OK but may not work as expected. The latter is far more frustrating. It makes me think that we may just want to crash...

File: packages/flutter/lib/src/widgets/framework.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/framework.dart]: What if we add a third non-debug mode?

File: packages/flutter/lib/src/rendering/error.dart (hunk 2 above)
Comment (Hixie) [reply packages/flutter/lib/src/rendering/error.dart]: if statements look dynamic. I want something that looks like an `#ifdef` (but structural).

File: packages/flutter/lib/src/widgets/framework.dart (hunk 4 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/framework.dart]: Crashing isn't really reasonable when the ErrorWidget only appears for a tiny 10x10 part of the screen for one frame of a long animation, though...

File: packages/flutter/lib/src/widgets/framework.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/framework.dart]: (bear in mind this is developer code, so we can't go and change it)

File: packages/flutter/lib/src/widgets/framework.dart (hunk 4 above)
Comment (Hixie) [reply packages/flutter/lib/src/widgets/framework.dart]: removed "[sic]"

**Comment by Hixie** [comment]
PTAL

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/framework.dart [hunk 5]
```diff
@@ -3810,13 +3810,71 @@ typedef ErrorWidgetBuilder = Widget Function(FlutterErrorDetails details);
...
+///
+/// void main() {
+///   ErrorWidget.builder = (FlutterErrorDetails details) {
+///     bool inDebug = false;
+///     assert(() { inDebug = true; return true; }());
+///     // In debug mode, use the normal error widget which shows
+///     // the error message:
+///     if (inDebug)
+///       return ErrorWidget(details.exception);
+///     // In release builds, show a yellow-on-blue message instead:
```
Comment (Levi-Lesches) [inline packages/flutter/lib/src/widgets/framework.dart]: Can there be a way to configure the styling of this widget?

**Comment by Hixie** [comment]
It's been configurable for a looooong time. There's even an example of how to do it in the docs added in this PR.

**Comment by Levi-Lesches** [comment]
Right I understood that part, I just got thrown off by the difference between `ErrorWidget` and `RenderErrorBox`, I see now.
