### PR TITLE
M3 - Fix Chip icon and label colors

### LINKED ISSUE #136632: Chips don't use the correct `selected` & `unselected` `ColorScheme` colors for the icons in Material 3
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

While working on other chip issues and testing the changes I noticed the chips aren't using the correct `selected` & `unselected` `ColorScheme` colors for the icons in Material 3.

According to tokens and the web [specs](https://m3.material.io/components/chips/specs), the chips should be using the `onSurfaceVariant` for the `unselected` state and `onSecondaryContainer` for `selected` state (for the chips that don't use primary color for the selected state)
https://github.com/flutter/flutter/blob/0b035e026a5244215a0dffa4870783d209b78405/dev/tools/gen_defaults/data/chip_filter.json#L64-L87

To reproduce run the code sample below which overrides these colors using a custom `ColorScheme`.

### Expected results

Screenshot 2023-10-16 at 13 08 59

### Actual results

Screenshot 2023-10-16 at 13 06 54

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.green).copyWith(
          onSurfaceVariant: const Color(0xffff0000),
          onSecondaryContainer: const Color(0xff0000ff),
        ),
      ),
      home: const Example(),
    );
  }
}

class Example extends StatefulWidget {
  const Example({super.key});

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                const Text('Selected'),
                FilterChip(
                    avatar: const Icon(Icons.favorite_rounded),
                    label: const Text('FilterChip'),
                    selected: true,
                    showCheckmark: false,
                    onSelected: (bool value) {}),
                InputChip(
                  avatar: const Icon(Icons.favorite_rounded),
                  label: const Text('InputChip'),
                  selected: true,
                  showCheckmark: false,
                  onPressed: () {},
                ),
                ChoiceChip(
                  avatar: const Icon(Icons.favorite_rounded),
                  label: const Text('ChoiceChip'),
                  selected: true,
                  showCheckmark: false,
                  onSelected: (bool value) {},
                ),
              ],
            ),
            Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                const Text('Enabled'),
                FilterChip(
                  avatar: const Icon(Icons.favorite_rounded),
                  label: const Text('FilterChip'),
                  onSelected: (bool value) {},
                ),
                InputChip(
                  avatar: const Icon(Icons.favorite_rounded),
                  label: const Text('InputChip'),
                  onPressed: () {},
                ),
                ChoiceChip(
                  avatar: const Icon(Icons.favorite_rounded),
                  label: const Text('ChoiceChip'),
                  selected: false,
                  onSelected: (bool value) {},
                ),
              ],
            ),
            const Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                Text('Disabled'),
                FilterChip(
                  avatar: Icon(Icons.favorite_rounded),
                  label: Text('FilterChip'),
                  onSelected: null,
                ),
                InputChip(
                  avatar: Icon(Icons.favorite_rounded),
                  label: Text('InputChip'),
                  isEnabled: false,
                  onPressed: null,
                ),
                ChoiceChip(
                  avatar: Icon(Icons.favorite_rounded),
                  label: Text('ChoiceChip'),
                  selected: false,
                  onSelected: null,
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.16.0-11.0.pre.69, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.16.0-11.0.pre.69 on channel master at /Users/tahatesser/Code/flutter
    • Upstream repository git@github.com:TahaTesser/flutter.git
    • FLUTTER_GIT_URL = git@github.com:TahaTesser/flutter.git
    • Framework revision b66ab70c09 (4 hours ago), 2023-10-16 02:37:09 -0400
    • Engine revision 539ad5b232
    • Dart version 3.3.0 (build 3.3.0-27.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by davidmartos96**
The following PR adjusts the usage of the Material 3 tokens for the Filter, Input and Choice chips. In particular, to fix how the label and icon colors are displayed depending on the unselected/selected state.

Fixes https://github.com/flutter/flutter/issues/136632

For this PR I had to change a few of the tests in the repo, which were expecting incorrect colors. How is that particular situation handled?

@TahaTesser Just pinging to let you know that the image you provided in the expected results section doesn't seem to be using exactly the tokens from the material specification. In the spec, the leading icon color is "primary" for InputChip (selected) and for unselected ChoiceChip and FilterChip.

## Example with contrasting colors from the linked issue:
**Primary:**                           Dark green
**SecondaryContainer**:       Light green
**OnSecondaryContainer:**  Blue
**OnSurfaceVariant:**            Red

## Before:

Screenshot from 2023-12-23 15-16-20

## After:

Screenshot from 2023-12-23 15-16-01

## Before:
Screenshot from 2023-12-23 16-51-56

## After:
Screenshot from 2023-12-23 16-52-06

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/tools/gen_defaults/lib/filter_chip_template.dart [hunk 1]
```diff
@@ -43,7 +43,20 @@ class _${blockName}DefaultsM3 extends ChipThemeData {
...
+  Color get _labelColor {
+    if (!isEnabled) {
+      // Without color opacity token. _RenderChip handles 'disable' opacity internally
+      return ${color("$tokenGroup.disabled.label-text.color")};
+    }
+
+    return isSelected
+      ? ${componentColor("$tokenGroup.selected.label-text")}
+      : ${componentColor("$tokenGroup.unselected.label-text")};
+  }
```
Comment (TahaTesser) [inline dev/tools/gen_defaults/lib/filter_chip_template.dart:59]:
```suggestion
  TextStyle? get labelStyle => ${textStyle("$tokenGroup.label-text")}?.copyWith(
    color: isEnabled
      ? isSelected
        ? ${color("$tokenGroup.selected.label-text.color")}
        : ${color("$tokenGroup.unselected.label-text.color")}
      : ${color("$tokenGroup.disabled.label-text.color")},
  );
```

File: dev/tools/gen_defaults/lib/filter_chip_template.dart [hunk 2]
```diff
@@ -77,10 +90,30 @@ class _${blockName}DefaultsM3 extends ChipThemeData {
   Color? get surfaceTintColor => ${colorOrTransparent("$tokenGroup.container.surface-tint-layer.color")};
 
   @override
-  Color? get checkmarkColor => ${color("$tokenGroup.with-leading-icon.selected.leading-icon.color")};
+  Color? get checkmarkColor => _leadingIconColor;
```
Comment (TahaTesser) [inline dev/tools/gen_defaults/lib/filter_chip_template.dart:93]:
```suggestion
  Color? get checkmarkColor => isEnabled
    ? isSelected
      ? ${color("$tokenGroup.with-leading-icon.selected.leading-icon.color")}
      : ${color("$tokenGroup.with-leading-icon.unselected.leading-icon.color")}
    : ${color("$tokenGroup.with-leading-icon.disabled.leading-icon.color")};
```

File: dev/tools/gen_defaults/lib/filter_chip_template.dart [hunk 3]
```diff
@@ -77,10 +90,30 @@ class _${blockName}DefaultsM3 extends ChipThemeData {
...
+
+  Color get _trailingIconColor {
+    if (!isEnabled) {
+      return ${color("$tokenGroup.with-trailing-icon.disabled.trailing-icon.color")};
+    }
+
+    return isSelected
+      ? ${color("$tokenGroup.with-trailing-icon.selected.trailing-icon.color")}
+      : ${color("$tokenGroup.with-trailing-icon.unselected.trailing-icon.color")};
+  }
```
Comment (TahaTesser) [inline dev/tools/gen_defaults/lib/filter_chip_template.dart:116]:
```suggestion
  Color? get deleteIconColor => isEnabled
    ? isSelected
      ? ${color("$tokenGroup.with-trailing-icon.selected.trailing-icon.color")}
      : ${color("$tokenGroup.with-trailing-icon.unselected.trailing-icon.color")}
    : ${color("$tokenGroup.with-trailing-icon.disabled.trailing-icon.color")};
```

File: dev/tools/gen_defaults/lib/filter_chip_template.dart [hunk 4]
```diff
@@ -91,9 +124,7 @@ class _${blockName}DefaultsM3 extends ChipThemeData {
 
   @override
   IconThemeData? get iconTheme => IconThemeData(
-    color: isEnabled
-      ? ${color("$tokenGroup.with-icon.icon.color")}
-      : ${color("$tokenGroup.with-leading-icon.disabled.leading-icon.color")},
+    color: _leadingIconColor,
```
Comment (TahaTesser) [inline dev/tools/gen_defaults/lib/filter_chip_template.dart:127]:
```suggestion
    color: isEnabled
      ? isSelected
        ? ${color("$tokenGroup.with-leading-icon.selected.leading-icon.color")}
        : ${color("$tokenGroup.with-leading-icon.unselected.leading-icon.color")}
      : ${color("$tokenGroup.with-leading-icon.disabled.leading-icon.color")},
     
```

File: dev/tools/gen_defaults/lib/input_chip_template.dart [hunk 5]
```diff
@@ -30,7 +30,20 @@ class _${blockName}DefaultsM3 extends ChipThemeData {
   late final TextTheme _textTheme = Theme.of(context).textTheme;
 
   @override
-  TextStyle? get labelStyle => ${textStyle("$tokenGroup.label-text")};
+  TextStyle? get labelStyle => ${textStyle("$tokenGroup.label-text")}?.copyWith(
```
Comment (TahaTesser) [inline dev/tools/gen_defaults/lib/input_chip_template.dart:33]: Please follow the same style I've suggested for `FilterChip` template for this class and run generate command to update widget classes

File: packages/flutter/test/material/filter_chip_test.dart [hunk 6]
```diff
@@ -938,4 +948,67 @@ void main() {
...
     expectLater(find.byType(RawChip), matchesGoldenFile('filter_chip.disabled.delete_button.png'));
   });
+
+  testWidgets('Material3 - FilterChip icon colors', (WidgetTester tester) async {
+    const IconData avatarIcon = Icons.house;
+    final ThemeData theme = ThemeData();
+
+    Widget buildFlatChip({
+      required bool selected,
+    }) {
```
Comment (TahaTesser) [inline packages/flutter/test/material/filter_chip_test.dart:958]:
```suggestion
    Widget buildFlatChip({ required bool selected }) {
```

File: packages/flutter/test/material/filter_chip_test.dart [hunk 7]
```diff
@@ -938,4 +948,67 @@ void main() {
...
+              onDeleted: () { },
+            ),
+          ),
+        ),
+      );
+    }
+
+    Widget buildElevatedChip({
+      required bool selected,
+    }) {
```
Comment (TahaTesser) [inline packages/flutter/test/material/filter_chip_test.dart:977]: Why not put both flat and elevated chips in a column?  This will simplify the test

**Review by TahaTesser — CHANGES_REQUESTED** [review]
Thanks for contributing.

File: packages/flutter/test/material/filter_chip_test.dart (hunk 7 above)
Comment (davidmartos96) [reply packages/flutter/test/material/filter_chip_test.dart:977]: Then it would be harder to obtain the correct "clear" icon in the tree.
Currently the following is being used for the expect. Internally it does a `firstWidget` finder, which would be problematic if there are 2 of them.

`getIconDataForIcon(tester, Icons.clear).color`

Comment (TahaTesser) [reply packages/flutter/test/material/filter_chip_test.dart:977]: `getIconDataForIcon` is only used by this one widget.  You can move it tin the test and retrieve first and last icon or use different icons

File: dev/tools/gen_defaults/lib/filter_chip_template.dart (hunk 4 above)
Comment (davidmartos96) [reply dev/tools/gen_defaults/lib/filter_chip_template.dart:127]: I guess the nested ternary is more compact, we can change that, but I would keep the named getter, as it gives more meaning and it is reusable. For instance the input_chip_template reuses `_leadingIconColor` for the custom `iconTheme` icon color. What do you think?

Comment (TahaTesser) [reply dev/tools/gen_defaults/lib/filter_chip_template.dart:112]: Named getters are not used in the templates. The format I suggested is consistency and readability. Templates are not about reusability as the tokens can be changed in the future. Please follow the suggestions.

File: dev/tools/gen_defaults/lib/input_chip_template.dart [hunk 8]
```diff
@@ -54,10 +60,22 @@ class _${blockName}DefaultsM3 extends ChipThemeData {
   Color? get surfaceTintColor => ${colorOrTransparent("$tokenGroup.container.surface-tint-layer.color")};
 
   @override
-  Color? get checkmarkColor => ${color("$tokenGroup.with-icon.selected.icon.color")};
+  Color? get checkmarkColor => _leadingIconColor;
```
Comment (TahaTesser) [inline dev/tools/gen_defaults/lib/input_chip_template.dart:63]: https://github.com/flutter/flutter/pull/140573/files#r1439730160

**Review by TahaTesser — CHANGES_REQUESTED** [review]

File: dev/tools/gen_defaults/lib/filter_chip_template.dart (hunk 4 above)
Comment (davidmartos96) [reply dev/tools/gen_defaults/lib/filter_chip_template.dart]: Ok, I removed the private getters. Thanks for the review!

File: packages/flutter/test/material/filter_chip_test.dart [hunk 9]
```diff
@@ -938,4 +938,66 @@ void main() {
...
+    expect(getIconDataForIcon(elevatedChip: true, tester, avatarIcon).color, theme.colorScheme.primary);
+    expect(getIconDataForIcon(elevatedChip: true, tester, Icons.clear).color, theme.colorScheme.onSurfaceVariant);
+
+    // Selected state
+    await tester.pumpWidget(buildChips(selected: true));
+    expect(getIconDataForIcon(elevatedChip: false, tester, avatarIcon).color, theme.colorScheme.onSecondaryContainer);
+    expect(getIconDataForIcon(elevatedChip: false, tester, Icons.clear).color, theme.colorScheme.onSecondaryContainer);
+    expect(getIconDataForIcon(elevatedChip: true, tester, avatarIcon).color, theme.colorScheme.onSecondaryContainer);
+    expect(getIconDataForIcon(elevatedChip: true, tester, Icons.clear).color, theme.colorScheme.onSecondaryContainer);
+  });
```
Comment (TahaTesser) [inline packages/flutter/test/material/filter_chip_test.dart:1002]:
```suggestion
  testWidgets('Material3 - Default FilterChip icon colors', (WidgetTester tester) async {
    const IconData flatAvatar = Icons.favorite;
    const IconData flatDeleteIcon = Icons.delete;
    const IconData elevatedAvatar = Icons.house;
    const IconData elevatedDeleteIcon = Icons.clear_all;
    final ThemeData theme = ThemeData();

    Widget buildChips({
      required bool selected,
    }) {
      return MaterialApp(
        theme: theme,
        home: Material(
          child: Column(
            children: <Widget>[
              FilterChip(
                avatar: const Icon(flatAvatar),
                deleteIcon: const Icon(flatDeleteIcon),
                onSelected: (bool valueChanged) { },
                label: const Text('FilterChip'),
                selected: selected,
                onDeleted: () { },
              ),
              FilterChip.elevated(
                avatar: const Icon(elevatedAvatar),
                deleteIcon: const Icon(elevatedDeleteIcon),
                onSelected: (bool valueChanged) { },
                label: const Text('Elevated FilterChip'),
                selected: selected,
                onDeleted: () { },
              ),
            ],
          ),
        ),
      );
    }

    Color getIconColor(WidgetTester tester, IconData icon) {
      return tester.firstWidget<IconTheme>(
        find.ancestor(
          of: find.byIcon(icon),
          matching: find.byType(IconTheme),
        ),
      ).data.color!;
    }

    // Test unselected state.
    await tester.pumpWidget(buildChips(selected: false));
    // Check the flat chip icon colors.
    expect(getIconColor(tester, flatAvatar), theme.colorScheme.primary);
    expect(
      getIconColor(tester, flatDeleteIcon),
      theme.colorScheme.onSurfaceVariant,
    );
    // Check the elevated chip icon colors.
    expect(getIconColor(tester, elevatedAvatar), theme.colorScheme.primary);
    expect(
      getIconColor(tester, elevatedDeleteIcon),
      theme.colorScheme.onSurfaceVariant,
    );

    // Test selected state.
    await tester.pumpWidget(buildChips(selected: true));
    // Check the flat chip icon colors.
    expect(
      getIconColor(tester, flatAvatar),
      theme.colorScheme.onSecondaryContainer,
    );
    expect(
      getIconColor(tester, flatDeleteIcon),
      theme.colorScheme.onSecondaryContainer,
    );
    // Check the elevated chip icon colors.
    expect(
      getIconColor(tester, elevatedAvatar),
      theme.colorScheme.onSecondaryContainer,
    );
    expect(
      getIconColor(tester, elevatedDeleteIcon),
      theme.colorScheme.onSecondaryContainer,
    );
  });
```

**Review by TahaTesser — CHANGES_REQUESTED** [review]
Thanks for updating the PR!

File: packages/flutter/test/material/input_chip_test.dart [hunk 10]
```diff
@@ -408,7 +408,7 @@ void main() {
     // Test default icon theme.
     await tester.pumpWidget(buildChip());
 
-    expect(getIconData(tester).color, ThemeData().iconTheme.color);
+    expect(getIconData(tester).color, ThemeData().colorScheme.onSurfaceVariant);
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:411]: Please add `theme` variable in this test and pass it to the `MaterialApp`. This ensures we're testing the expected `ThemeData` object.

```dart
    final ThemeData theme = ThemeData();

    Widget buildChip({ IconThemeData? iconTheme }) {
      return MaterialApp(
        theme: theme,
```

```suggestion
    expect(getIconData(tester).color, theme.colorScheme.onSurfaceVariant);
```

**Review by TahaTesser — CHANGES_REQUESTED** [review]

**Review by TahaTesser — CHANGES_REQUESTED** [review]
Further minor improvement

**Comment by TahaTesser** [comment]
I'll take a final look and review this once https://github.com/flutter/flutter/pull/140964 and https://github.com/flutter/flutter/pull/141022 are merged after the tree is fixed. We can resolve any merged conflicts that may come from this.

**Comment by davidmartos96** [comment]
@TahaTesser Good call. I didn't know there was a refactor of the chip tests pending for M2-M3. Nice!

**Comment by davidmartos96** [comment]
@TahaTesser I've updated with your merged PRs. There weren't merge conflicts, but one of the duplicated M2 tests had to be changed for M3 with the token changes in this PR.
In particular the disabled color of the checkmark in the input chips. It's hardly a noticeable change though.

72ff6cc

```dart
InputChip(
  showCheckmark: true,
  selected: true,
  label: Text('Selected InputChip'),
  isEnabled: false,
  onPressed: null,
  onDeleted: () {},
),
```

M3 - Flutter stable:

image


M3 - This PR:

image

File: packages/flutter/test/material/input_chip_test.dart [hunk 11]
```diff
@@ -321,14 +321,14 @@ void main() {
...
-  testWidgets('Material3 - Input chip check mark color is determined by platform brightness when dark', (WidgetTester tester) async {
+  testWidgets('Material3 - Input chip disabled check mark color is determined by platform brightness when dark', (WidgetTester tester) async {
     await pumpCheckmarkChip(
       tester,
       chip: selectedInputChip(),
       brightness: Brightness.dark,
     );
-
-    expectCheckmarkColor(find.byType(InputChip), Colors.white.withAlpha(0xde));
+    // Without color opacity. _RenderChip handles the 'disabled' state opacity internally
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:330]:
```suggestion
```
We shouldn't document private class.

Expected results already matches the spec.

File: packages/flutter/test/material/input_chip_test.dart [hunk 12]
```diff
@@ -321,14 +321,14 @@ void main() {
...
+    expectCheckmarkColor(find.byType(InputChip), ThemeData.dark().colorScheme.onSurface);
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:331]:
```suggestion
    expectCheckmarkColor(find.byType(InputChip), theme.colorScheme.onSurface);
```

Since we're checking theme's color scheme for M3. This also needs a ThemeData variable like M3 tests.
`final ThemeData theme = ThemeData(brightness: Brightness.dark);` then pass `theme`  variable.

**Comment by TahaTesser** [comment]
>  but one of the duplicated M2 tests had to be changed for M3 because of the token changes in this PR.

Its not a duplicate test, it's the same test for M2 and M3. Eventually M2 test will be removed.

I see you updated M3 test's expected value, it makes sense the default value is also updated. Looks fine.

**Review by TahaTesser — CHANGES_REQUESTED** [review]

File: packages/flutter/test/material/input_chip_test.dart (hunk 11 above)
Comment (davidmartos96) [reply packages/flutter/test/material/input_chip_test.dart:330]: Ok. I placed the note, because the M2 color has an opacity, whereas M3 doesn't, although the spec in M3 specifies an opacity.

File: packages/flutter/test/material/input_chip_test.dart (hunk 12 above)
Comment (davidmartos96) [reply packages/flutter/test/material/input_chip_test.dart]: Done in 0cbf9b5b9593c71902b6f58689a789004d386703
I followed the same pattern as in your other PR https://github.com/flutter/flutter/pull/140964/files

**Comment by davidmartos96** [comment]
I pushed an empty commit to force the re-run of a failed ICU workflow due to "resource exhaustion", but it appears it is still unavailable.
Regarding the golden changes approvals, I'm assuming those are better left when the PR is approved, right? Otherwise the "goldens bot" will be complaining about diffs for every new commit.

File: packages/flutter/test/material/filter_chip_test.dart [hunk 13]
```diff
@@ -720,11 +718,11 @@ void main() {
   });
 
   testWidgets('Material2 - Filter chip check mark color is determined by platform brightness when dark', (WidgetTester tester) async {
+    final ThemeData theme = ThemeData.dark(useMaterial3: false);
```
Comment (TahaTesser) [inline packages/flutter/test/material/filter_chip_test.dart:721]:
```suggestion
```

This test isn't checking theme value. No variable is needed.

File: packages/flutter/test/material/filter_chip_test.dart [hunk 14]
```diff
@@ -720,11 +718,11 @@ void main() {
...
     await pumpCheckmarkChip(
       tester,
       chip: selectedFilterChip(),
-      brightness: Brightness.dark,
-      useMaterial3: false,
+      theme: theme,
```
Comment (TahaTesser) [inline packages/flutter/test/material/filter_chip_test.dart:725]:
```suggestion
      brightness: Brightness.dark,
      useMaterial3: false,
```

File: packages/flutter/test/material/filter_chip_test.dart [hunk 15]
```diff
@@ -738,8 +736,7 @@ void main() {
     await pumpCheckmarkChip(
       tester,
       chip: selectedFilterChip(),
-      brightness: theme.brightness,
-      useMaterial3: theme.useMaterial3,
+      theme: theme,
```
Comment (TahaTesser) [inline packages/flutter/test/material/filter_chip_test.dart:739]:
```suggestion
      brightness: theme.brightness,
      useMaterial3: theme.useMaterial3,
```

File: packages/flutter/test/material/filter_chip_test.dart [hunk 16]
```diff
@@ -696,10 +693,11 @@ void main() {
   });
 
   testWidgets('Material2 - Filter chip check mark color is determined by platform brightness when light', (WidgetTester tester) async {
+    final ThemeData theme = ThemeData(useMaterial3: false);
```
Comment (TahaTesser) [inline packages/flutter/test/material/filter_chip_test.dart:696]:
```suggestion
```

File: packages/flutter/test/material/filter_chip_test.dart [hunk 17]
```diff
@@ -696,10 +693,11 @@ void main() {
...
     await pumpCheckmarkChip(
       tester,
       chip: selectedFilterChip(),
-      useMaterial3: false,
+      theme: theme,
```
Comment (TahaTesser) [inline packages/flutter/test/material/filter_chip_test.dart:700]:
```suggestion
      useMaterial3: false,
```

File: packages/flutter/test/material/filter_chip_test.dart [hunk 18]
```diff
@@ -710,7 +708,7 @@ void main() {
     await pumpCheckmarkChip(
       tester,
       chip: selectedFilterChip(),
-      useMaterial3: theme.useMaterial3,
+      theme: theme,
```
Comment (TahaTesser) [inline packages/flutter/test/material/filter_chip_test.dart:711]:
```suggestion
      useMaterial3: theme.useMaterial3,
```

File: packages/flutter/test/material/filter_chip_test.dart [hunk 19]
```diff
@@ -840,7 +840,7 @@ void main() {
     // Test default icon theme.
     await tester.pumpWidget(buildChip());
 
-    expect(getIconData(tester).color, ThemeData().iconTheme.color);
+    expect(getIconData(tester).color, theme.colorScheme.primary);
```
Comment (TahaTesser) [inline packages/flutter/test/material/filter_chip_test.dart:843]: This actually checks the theme value so the theme variable is good here.

File: packages/flutter/test/material/input_chip_test.dart [hunk 20]
```diff
@@ -15,11 +15,10 @@ Widget wrapForChip({
   required Widget child,
   TextDirection textDirection = TextDirection.ltr,
   double textScaleFactor = 1.0,
-  Brightness brightness = Brightness.light,
-  bool? useMaterial3,
+  ThemeData? theme,
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:18]:
```suggestion
  Brightness brightness = Brightness.light,
  bool? useMaterial3,
```

File: packages/flutter/test/material/input_chip_test.dart [hunk 21]
```diff
@@ -15,11 +15,10 @@ Widget wrapForChip({
...
 }) {
   return MaterialApp(
-    theme: ThemeData(brightness: brightness, useMaterial3: useMaterial3),
+    theme: theme,
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:21]:
```suggestion
    theme: ThemeData(brightness: brightness, useMaterial3: useMaterial3),
```

File: packages/flutter/test/material/input_chip_test.dart [hunk 22]
```diff
@@ -48,13 +47,11 @@ Future<void> pumpCheckmarkChip(
   WidgetTester tester, {
   required Widget chip,
   Color? themeColor,
-  Brightness brightness = Brightness.light,
-  bool? useMaterial3,
+  ThemeData? theme,
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:50]:
```suggestion
  Brightness brightness = Brightness.light,
  bool? useMaterial3,
```

File: packages/flutter/test/material/input_chip_test.dart [hunk 23]
```diff
@@ -48,13 +47,11 @@ Future<void> pumpCheckmarkChip(
...
 }) async {
   await tester.pumpWidget(
     wrapForChip(
-      useMaterial3: useMaterial3,
-      brightness: brightness,
+      theme: theme,
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:54]:
```suggestion
      useMaterial3: useMaterial3,
      brightness: brightness,
```

File: packages/flutter/test/material/input_chip_test.dart [hunk 24]
```diff
@@ -294,41 +291,42 @@ void main() {
     focusNode2.dispose();
   });
 
-  testWidgets('Material2 - Input chip check mark color is determined by platform brightness when light', (WidgetTester tester) async {
+  testWidgets('Material2 - Input chip disabled check mark color is determined by platform brightness when light', (WidgetTester tester) async {
+    final ThemeData theme = ThemeData(useMaterial3: false);
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:295]:
```suggestion
```

File: packages/flutter/test/material/input_chip_test.dart [hunk 25]
```diff
@@ -294,41 +291,42 @@ void main() {
...
     await pumpCheckmarkChip(
       tester,
       chip: selectedInputChip(),
-      useMaterial3: false,
+      theme: theme,
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:299]:
```suggestion
      useMaterial3: false,
```

File: packages/flutter/test/material/input_chip_test.dart [hunk 26]
```diff
@@ -294,41 +291,42 @@ void main() {
...
 
     expectCheckmarkColor(find.byType(InputChip), Colors.black.withAlpha(0xde));
   });
 
-  testWidgets('Material3 - Input chip check mark color is determined by platform brightness when light', (WidgetTester tester) async {
-    await pumpCheckmarkChip(tester, chip: selectedInputChip());
-
-    expectCheckmarkColor(find.byType(InputChip), Colors.black.withAlpha(0xde));
+  testWidgets('Material3 - Input chip disabled check mark color is determined by platform brightness when light', (WidgetTester tester) async {
+    final ThemeData theme = ThemeData(useMaterial3: true);
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:306]:
```suggestion
    final ThemeData theme = ThemeData();
```

File: packages/flutter/test/material/input_chip_test.dart [hunk 27]
```diff
@@ -294,41 +291,42 @@ void main() {
...
+    await pumpCheckmarkChip(tester, chip: selectedInputChip(), theme: theme);
+    expectCheckmarkColor(find.byType(InputChip), theme.colorScheme.onSurface);
   });
 
-  testWidgets('Material2 - Input chip check mark color is determined by platform brightness when dark', (WidgetTester tester) async {
+  testWidgets('Material2 - Input chip disabled check mark color is determined by platform brightness when dark', (WidgetTester tester) async {
+    final ThemeData theme = ThemeData.dark(useMaterial3: false);
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:312]:
```suggestion
```

File: packages/flutter/test/material/input_chip_test.dart [hunk 28]
```diff
@@ -294,41 +291,42 @@ void main() {
...
     await pumpCheckmarkChip(
       tester,
       chip: selectedInputChip(),
-      brightness: Brightness.dark,
-      useMaterial3: false,
+      theme: theme,
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:316]:
```suggestion
      brightness: Brightness.dark,
      useMaterial3: false,
```

File: packages/flutter/test/material/input_chip_test.dart [hunk 29]
```diff
@@ -294,41 +291,42 @@ void main() {
...
   });
 
-  testWidgets('Material3 - Input chip check mark color is determined by platform brightness when dark', (WidgetTester tester) async {
+  testWidgets('Material3 - Input chip disabled check mark color is determined by platform brightness when dark', (WidgetTester tester) async {
+    final ThemeData theme = ThemeData.dark(useMaterial3: true);
     await pumpCheckmarkChip(
       tester,
       chip: selectedInputChip(),
-      brightness: Brightness.dark,
+      theme: theme,
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:327]:
```suggestion
      brightness: Brightness.dark,
```

File: packages/flutter/test/material/input_chip_test.dart [hunk 30]
```diff
@@ -294,41 +291,42 @@ void main() {
...
-      useMaterial3: false,
+      theme: theme,
     );
 
     expectCheckmarkColor(find.byType(InputChip), Colors.white.withAlpha(0xde));
   });
 
-  testWidgets('Material3 - Input chip check mark color is determined by platform brightness when dark', (WidgetTester tester) async {
+  testWidgets('Material3 - Input chip disabled check mark color is determined by platform brightness when dark', (WidgetTester tester) async {
+    final ThemeData theme = ThemeData.dark(useMaterial3: true);
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:323]:
```suggestion
    final ThemeData theme = ThemeData.dark();
```

This checks the theme value but it is one off so we can keep the variable without passing; M3 is true by default.

File: packages/flutter/test/material/input_chip_test.dart [hunk 31]
```diff
@@ -294,41 +291,42 @@ void main() {
...
     await pumpCheckmarkChip(
       tester,
       chip: selectedInputChip(),
-      brightness: Brightness.dark,
+      theme: theme,
     );
-
-    expectCheckmarkColor(find.byType(InputChip), Colors.white.withAlpha(0xde));
+    expectCheckmarkColor(find.byType(InputChip), theme.colorScheme.onSurface);
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:329]:
```suggestion

    expectCheckmarkColor(find.byType(InputChip), theme.colorScheme.onSurface);
```

File: packages/flutter/test/material/input_chip_test.dart [hunk 32]
```diff
@@ -370,32 +368,37 @@ void main() {
...
+    final ChipThemeData material3ChipDefaults = theme.chipTheme;
     await pumpCheckmarkChip(
       tester,
       chip: selectedInputChip(enabled: true),
-      useMaterial3: true,
+      theme: theme,
     );
 
     final RenderBox materialBox = getMaterialBox(tester);
     expect(materialBox, paints..rrect(color: material3ChipDefaults.backgroundColor));
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:380]: This doesn't look right. `material3ChipDefaults.backgroundColor` is a `null` value. 

`ThemeData(useMaterial3: true).chipTheme` is might be incorrect here.

File: packages/flutter/test/material/input_chip_test.dart [hunk 33]
```diff
@@ -370,32 +368,37 @@ void main() {
...
+    final ChipThemeData material3ChipDefaults = theme.chipTheme;
     await pumpCheckmarkChip(
       tester,
       chip: selectedInputChip(),
-      useMaterial3: true,
+      theme: theme,
     );
 
     final RenderBox materialBox = getMaterialBox(tester);
     expect(materialBox, paints..path(color: material3ChipDefaults.disabledColor));
```
Comment (TahaTesser) [inline packages/flutter/test/material/input_chip_test.dart:393]:
```suggestion
    expect(materialBox, paints..path(color: material3ChipDefaults.disabledColor));
```

same here

**Review by TahaTesser — CHANGES_REQUESTED** [review]

File: packages/flutter/test/material/filter_chip_test.dart (hunk 15 above)
Comment (davidmartos96) [reply packages/flutter/test/material/filter_chip_test.dart:739]: @TahaTesser  Part of the changes in this PR change the utility methods in the test following your recommendation on a previous review, where the 2 parameters are collpased into a single ThemeData. There was a recent PR from you which took this same aproach.
Should we revert and keep the 2 parameters or use the single ThemeData param?

image

File: packages/flutter/test/material/filter_chip_test.dart (hunk 19 above)
Comment (davidmartos96) [reply packages/flutter/test/material/filter_chip_test.dart:843]: Do you mean in comparison with the other comment? To use or not the `final theme = ThemeData()` variable?

File: packages/flutter/test/material/filter_chip_test.dart (hunk 15 above)
Comment (TahaTesser) [reply packages/flutter/test/material/filter_chip_test.dart:739]: If you can link the PR. 

I merged two chips PRs recently and we decided to keep `brightness` and `useMaterial3`, this is from that one of those PRs. Please restore the changes.

Comment (TahaTesser) [reply packages/flutter/test/material/filter_chip_test.dart:739]: I just found the PR, my bad. This is fine.

https://github.com/flutter/flutter/pull/140964/files#diff-771d4e403370d0f93ff8abb7aeb2468ab94a86d69f3ccda521b89948bdbf7d14R80

Comment (TahaTesser) [reply packages/flutter/test/material/filter_chip_test.dart:739]: I misunderstood and thought we did the opposite.

File: packages/flutter/test/material/filter_chip_test.dart (hunk 19 above)
Comment (TahaTesser) [reply packages/flutter/test/material/filter_chip_test.dart:843]: If the test checks `theme.{value}`, keep the variable.

File: packages/flutter/test/material/filter_chip_test.dart (hunk 15 above)
Comment (davidmartos96) [reply packages/flutter/test/material/filter_chip_test.dart:739]: Yes, that's the one I was referring to. Great then

File: packages/flutter/test/material/input_chip_test.dart (hunk 32 above)
Comment (davidmartos96) [reply packages/flutter/test/material/input_chip_test.dart]: Nice catch! 
I investigated a bit and it looks like it could be a faulty implementation of the test, as `paint.rrect(color: null)` passes, and `theme.chipTheme` has all values as null by default. So that expect never had proper non null values to check.
I've updated the test to check for the correct values in the theme colorScheme, but I had to also update how the default input chip in the test is built. The `enabled` param was not being used properly. Regardless the value of `enabled` the chip always had the MaterialState.disabled because it didn't have any of the callbacks (onPressed, onSelected, onDeleted).

I've checked if `filter_chip_test` had the same issue, but it doesn't look like it. The utility chip builder used there doesn't have `enabled` as a parameter.

Changes in 1ab12f1

File: packages/flutter/test/material/input_chip_test.dart (hunk 33 above)
Comment (davidmartos96) [reply packages/flutter/test/material/input_chip_test.dart]: Fixed in https://github.com/flutter/flutter/commit/1ab12f11b973923bbc0cb050f09bf639da3856f6

**Review by TahaTesser — APPROVED** [review]
LGTM!

**Review by QuncCccccc — APPROVED** [review]
LGTM. Thanks for the contribution! That's so nice to have more tokens being applied:)

**Comment by QuncCccccc** [comment]
I just approved all the golden diffs. Maybe we can rebase master next to solve the conflicts and we are ready to go!

**Comment by davidmartos96** [comment]
@QuncCccccc Thank you! I've fixed the merge conflict. It was just a new test that was added at the end of the filter_chip.test file.

**Comment by davidmartos96** [comment]
@QuncCccccc Oops. Another conflict appeared recently. It should be good now.

**Comment by TahaTesser** [comment]
@davidmartos96 
Can you please rebase again?

**Comment by davidmartos96** [comment]
@TahaTesser Is merge allowed? I've already fixed the merge conflicts in a previous commit. If I rebase it would recreate those conflicts for multiple commits with minor changes from the review.

Or is it to unstuck the 'Google testing' check?

**Comment by davidmartos96** [comment]
@TahaTesser Hello! It has been rebased.
Is it good to merge now?

**Comment by TahaTesser** [comment]
Three is currently down, I'll wait for the tree to go green then merge.

**Comment by QuncCccccc** [comment]
FRoB is not reporting TAP failures now because of b/319513492. Let me do a local test for G3 before we merge this in master.
