### PR TITLE
Keyboard Animation Fix

### LINKED ISSUE #168768: Content above keyboard jumps when keyboard is nearly opened (Only with edge-to-edge)
## Steps to reproduce

1. Create a Flutter project with a newer version i.e. 3.29. ❗It should have edge-to-edge activated by default (the bug only happens with e2e)❗
2. Add a TextFormField.
3. Run in a newer device. I reproduced it both in my Pixel 9 Pro emulator and my physical device Pixel 8 Pro (the latter was a release build).

## Animation jump triggered by any of 2 different actions
- Open the TextFormField by pressing on it. The content above the keyboard will make a small jump when finishing the animation.
- Once the keyboard is opened, slide from an edge so the 'back' bubble appears but don't release the finger from the screen (see example video). The keyboard will jump down. Cancel the 'back' action (swipe to the edge again). The keyboard will jump up.

❗❗ This **does not** happen when edge-to-edge is not active. It only happens with edge-to-edge.

## Expected results

The animation of the content above the keyboard should be smooth while opening and not jump.

This bug was already created some years ago and supposedly fixed, but it's happening (again?). 

Old issues:
- https://github.com/flutter/flutter/issues/89914 
- https://github.com/flutter/flutter/issues/131152
- https://github.com/flutter/flutter/issues/116836 (this one is even opened for years but has 0 activity by the dev team? I hope that I track some attention by posting a complete Issue with more data and a more detailed video demo).

The supposed fix, which by a comment in the 2nd issue it was supposed to be released after 3.11 but it's still hapenning):
- https://github.com/flutter/engine/pull/39391

❗❗👉👉 Guys, opening a keyboard is a pretty main action of an app. I'm really worried about the opened issue not having been attended for years, in a feature that is now activated by default in flutter (edge-to-edge). Not sure why this is not a main concern.

## Actual results

The content above the keyboard jumps when it's nearly opened.

## Code sample

Reproducible public repository: https://github.com/javiermrz/edge_to_edge_keyboard_bug_reproducible

## Screenshots or Video

<summary>Video demonstration</summary>

https://github.com/user-attachments/assets/5b107883-80cf-4ee1-a8eb-09d8db1788e8

## Logs

<details open><summary>Logs</summary>

```console
Performing hot restart...
Syncing files to device sdk gphone64 arm64...
Restarted application in 781ms.
I/ug_reproducible( 5999): AssetManager2(0xb4000076cbd63598) locale list changing from [] to [en-US]
E/libEGL  ( 5999): called unimplemented OpenGL ES API
D/InsetsController( 5999): Setting requestedVisibleTypes to -9 (was -1)
E/libEGL  ( 5999): called unimplemented OpenGL ES API
I/ImeTracker( 5999): com.example.bottom_input_bug_reproducible:79af6f08: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT_REQUEST_HIDE_WITH_CONTROL fromUser true
W/WindowOnBackDispatcher( 5999): sendCancelIfRunning: isInProgress=false callback=android.view.ImeBackAnimationController@9c68457
D/InsetsController( 5999): hide(ime(), fromIme=false)
I/ImeTracker( 5999): com.example.bottom_input_bug_reproducible:79af6f08: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
I/ImeTracker( 5999): system_server:fbe0c45a: onCancelled at PHASE_CLIENT_ON_CONTROLS_CHANGED
E/libEGL  ( 5999): called unimplemented OpenGL ES API
I/ImeTracker( 5999): com.example.bottom_input_bug_reproducible:ad84d20c: onRequestShow at ORIGIN_CLIENT reason SHOW_SOFT_INPUT fromUser false
D/InsetsController( 5999): show(ime(), fromIme=false)
D/InsetsController( 5999): Setting requestedVisibleTypes to -1 (was -9)
D/InputConnectionAdaptor( 5999): The input method toggled cursor monitoring on
I/ImeTracker( 5999): com.example.bottom_input_bug_reproducible:ad84d20c: onShown
```

</details>

The `onShown` message is the last one displayed after the keyboard finished opening.

## Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-arm64, locale en-ES)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 16.3)
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2025.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2025.1)
[✓] Connected device (5 available)
[✓] Network resources

```

</details>

### PR DESCRIPTION
**Pull request by mboetger**
Fixing Keyboard Animation Issue
Before:

https://github.com/user-attachments/assets/2b863ca1-20e3-47e2-94f1-5cb2083c1e28

After: 

https://github.com/user-attachments/assets/914efc84-13aa-4bde-8c44-d1761f1fe79a

Fixes: #168768

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by reidbaker** [comment]
It wasnt obvious to me where tests for this class lived. I think it is engine/src/flutter/shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java

File: engine/src/flutter/shell/platform/android/io/flutter/plugin/editing/ImeSyncDeferringInsetsCallback.java [hunk 1]
```diff
@@ -146,13 +146,15 @@ public WindowInsets onProgress(
...
-      // To fix this, we subtract the navigationBars bottom inset if the system UI flags for laying
-      // out behind the navigation bar aren't present.
+      // If not Edge-to-Edge, the IME insets include the height of the navigation bar. If the app
+      // isn't laid out behind the navigation bar, this causes the IME insets to be too large during
+      // the animation.  To fix this, we subtract the navigationBars bottom inset if the system UI
+      // flags for laying out behind the navigation bar aren't present.
       int excludedInsets = 0;
       int systemUiFlags = view.getWindowSystemUiVisibility();
-      if ((systemUiFlags & View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION) == 0
+      if (!((systemUiFlags & View.SYSTEM_UI_FLAG_LAYOUT_STABLE) != 0
```
Comment (gmackall) [inline engine/src/flutter/shell/platform/android/io/flutter/plugin/editing/ImeSyncDeferringInsetsCallback.java]: nit: This conditional is getting too long for me to understand it, written inline. Are there any logical pieces you can break out of here into intermediate booleans with helpful names?

**Review by gmackall — COMMENTED** [review]
When trying to change any piece of this logic in the past I've experienced it breaking random individual modes of https://api.flutter.dev/flutter/services/SystemUiMode.html

Have you tested those modes as well? If not, can you try opting out of edge-to-edge as described here https://docs.flutter.dev/release/breaking-changes/default-systemuimode-edge-to-edge?_gl=1*q1wl35*_ga*MTM2MzE0NDc2My4xNzU4NzUzNDI0*_ga_04YGWK0175*czE3NTk1MTc5MTkkbzUkZzAkdDE3NTk1MTgwNDAkajYwJGwwJGgw#migration-guide, and ensure that those modes aren't regressed? Sorry to add a bunch more validation work but this has historically been extremely brittle.

**Review by gmackall — APPROVED** [review]
Change LGTM though if those comments are addressed.

**Comment by mboetger** [comment]
> When trying to change any piece of this logic in the past I've experienced it breaking random individual modes of https://api.flutter.dev/flutter/services/SystemUiMode.html
> 
> Have you tested those modes as well? If not, can you try opting out of edge-to-edge as described here https://docs.flutter.dev/release/breaking-changes/default-systemuimode-edge-to-edge?_gl=1*q1wl35*_ga*MTM2MzE0NDc2My4xNzU4NzUzNDI0*_ga_04YGWK0175*czE3NTk1MTc5MTkkbzUkZzAkdDE3NTk1MTgwNDAkajYwJGwwJGgw#migration-guide, and ensure that those modes aren't regressed? Sorry to add a bunch more validation work but this has historically been extremely brittle.

Yeah, I need to go back and test the code sample provided in https://github.com/flutter/flutter/issues/109623 pre-15 and post-15.  Will do before submitting.

**Comment by mboetger** [comment]
@gmackall For API 36, Using the [repro app](https://github.com/mboetger/flutter_tests/tree/keyboard-original-109623) for #109623:

Before 

https://github.com/user-attachments/assets/37e88c18-e72e-4ac0-a2c9-9211dd4dfcfc

After

https://github.com/user-attachments/assets/23699209-73b5-4c3d-976c-60e48c12aaba

**Comment by gmackall** [comment]
> @gmackall For API 36, Using the [repro app](https://github.com/mboetger/flutter_tests/tree/keyboard-original-109623) for #109623:
> 
> Before
> 
> After
> 

Nice, that lgtm

**Review by reidbaker — APPROVED** [review]

**Comment by mboetger** [comment]
> https://api.flutter.dev/flutter/services/SystemUiMode.html



> > @gmackall For API 36, Using the [repro app](https://github.com/mboetger/flutter_tests/tree/keyboard-original-109623) for #109623:
> > Before
> > After
> 
> Nice, that lgtm

Unfortunately, it looks to me like it breaks pre-15.  It's harder for me to check, because I just have an emulator, but it definitely is creating too much space.  
[Screen_recording_20251006_110629.webm](https://github.com/user-attachments/assets/6c65d638-6680-4981-981f-ea6a0dfb88a0)

That being said, it may just make sense to fork on the SDK level
```
if (Build.VERSION.SDK_INT < API_LEVELS.API_35) {
```

Reading [this](https://developer.android.com/about/versions/15/behavior-changes-15) makes me think this is the correct call.

WDYT?  @reidbaker @gmackall 

Testing

**Comment by reidbaker** [comment]
That link takes me to https://developer.android.com/about/versions/15/behavior-changes-15 is there a subtitle that more specificly makes you think branching on 35+ behavior is the right thing to do?

**Comment by reidbaker** [comment]
> That link takes me to https://developer.android.com/about/versions/15/behavior-changes-15 is there a subtitle that more specificly makes you think branching on 35+ behavior is the right thing to do?

Maybe https://developer.android.com/about/versions/15/behavior-changes-15#stable-configuration

**Comment by mboetger** [comment]
With the API fork, everything seems to be working correctly:

Android 12:
[Screen_recording_20251006_135549.webm](https://github.com/user-attachments/assets/afb366cf-ddc4-4991-b4c5-339a22e20c7c)

Android 16: 
https://github.com/user-attachments/assets/07fc7c84-e573-4cc7-bba6-e874dfa93270

> > That link takes me to https://developer.android.com/about/versions/15/behavior-changes-15 is there a subtitle that more specificly makes you think branching on 35+ behavior is the right thing to do?
> 
> Maybe https://developer.android.com/about/versions/15/behavior-changes-15#stable-configuration

Honestly, I cannot find anything definitive about the IME insets including the height of the navigation bar.  It certainly seems like this is not the case post 15.

File: engine/src/flutter/shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java [hunk 2]
```diff
@@ -2707,6 +2707,101 @@ public void ime_windowInsetsSync_notLaidOutBehindNavigation_excludesNavigationBa
     }
   }
 
+  @Test
+  @TargetApi(API_LEVELS.API_35)
+  @Config(sdk = API_LEVELS.API_35)
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/test/io/flutter/plugin/editing/TextInputPluginTest.java]: please change this to minSdk =

**Review by reidbaker — APPROVED** [review]

**Comment by kale-xie** [comment]
Hello, I’d like to ask whether updating Flutter to the latest version would resolve the issue of the keyboard causing the input field to jitter. I found that after updating to Flutter 3.35.7, the problem still persists.

**Comment by tksoh** [comment]
It's in beta channel now. I tested it and seemed to work okay. Hope to see in next stable release.

**Comment by mdurmaz** [comment]
Is there any progress on this issue? Which version should I upgrade to solve this problem?
