### PR TITLE
[Impeller] Fix overdraw in DrawRect geometry

### LINKED ISSUE #174579: Paint not render coreectly
### Steps to reproduce

Flutter 3.35.2 • channel stable

```dart
Text(
          'Test',
          style:
          TextStyle(
            fontSize: 24,
            background: Paint()
              ..strokeWidth = 44
              ..color = const Color(0x1a0078ff)
              ..style = PaintingStyle.stroke
              ..strokeJoin = StrokeJoin.round,
          ),
        )
```

```
flutter run
```

### Expected results

Image

### Actual results

Image

### Code sample

<details open><summary>Code sample</summary>

```dart
Text(
          'Test',
          style:
          TextStyle(
            fontSize: 24,
            background: Paint()
              ..strokeWidth = 44
              ..color = const Color(0x1a0078ff)
              ..style = PaintingStyle.stroke
              ..strokeJoin = StrokeJoin.round,
          ),
        )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Screenshot 2025-08-27 at 8 34 41 PM

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
➜  ~ flutter doctor                   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.35.2, on macOS 15.6.1 24G90 darwin-arm64, locale
    en-SA)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2025.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2025.2)
[✓] VS Code (version 1.103.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
➜  ~ 
```

</details>

### PR DESCRIPTION
**Pull request by flar**
Fixes https://github.com/flutter/flutter/issues/174579

Vertex lists for stroked rects were fixed by being more careful about the creation of the vertices so that they have no inherent overdraw. These operations continue to use the fastest kNormal vertex mode but no longer create rendering artifacts due to multiple triangles covering the same area.

### CODE REVIEW

File: engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc [hunk 1]
```diff
@@ -35,6 +35,86 @@ TEST_P(AiksTest, CanRenderColoredRect) {
...
+  builder.DrawRect(DlRect::MakeXYWH(100.0f, 400.0f, 100.0f, 100.0f), paint);
+
+  paint.setStrokeJoin(DlStrokeJoin::kRound);
+  builder.DrawRect(DlRect::MakeXYWH(350.0f, 400.0f, 100.0f, 100.0f), paint);
+
+  paint.setStrokeJoin(DlStrokeJoin::kMiter);
+  builder.DrawRect(DlRect::MakeXYWH(600.0f, 400.0f, 100.0f, 100.0f), paint);
+
+  ASSERT_TRUE(OpenPlaygroundHere(builder.Build()));
+}
```
[the remark this answers is not in the document]
Comment (flar) [reply engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc]: Done

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc [hunk 2]
```diff
@@ -128,10 +129,40 @@ GeometryResult StrokeRectGeometry::GetPositionBuffer(
                   .index_type = IndexType::kNone,
               },
           .transform = entity.GetShaderTransform(pass),
+          .mode = GeometryResult::Mode::kPreventOverdraw,
       };
     }
 
     case Join::kBevel: {
+      if (half_stroke_width * 2.0f >= rect.GetSize().MinDimension()) {
```
[the remark this answers is not in the document]
Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: Done

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc [hunk 3]
```diff
@@ -144,32 +175,59 @@ GeometryResult StrokeRectGeometry::GetPositionBuffer(
...
                   .vertex_count = 17u,
                   .index_type = IndexType::kNone,
               },
           .transform = entity.GetShaderTransform(pass),
+          .mode = GeometryResult::Mode::kNormal,
       };
     }
 
     case Join::kMiter: {
+      if (half_stroke_width * 2.0f >= rect.GetSize().MinDimension()) {
```
[the remark this answers is not in the document]
Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: Done

**Comment by flar** [comment]
All tests passed and the goldens for the new tests look correct (no overdraw anomalies that I could see). This PR is ready for review now.

**Comment by flar** [comment]
ping @gaaclarke @chinmaygarde

File: engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc [hunk 4]
```diff
@@ -35,6 +35,76 @@ TEST_P(AiksTest, CanRenderColoredRect) {
   ASSERT_TRUE(OpenPlaygroundHere(builder.Build()));
 }
 
+namespace {
+using DrawRectProc =
+    std::function<void(DisplayListBuilder&, const DlRect&, const DlPaint&)>;
+
+[[maybe_unused]]
```
Comment (chinmaygarde) [inline engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc]: How maybe_unused?

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc [hunk 5]
```diff
@@ -207,35 +339,17 @@ std::optional<Rect> StrokeRectGeometry::GetCoverage(
   return rect_.TransformBounds(transform);
 }
 
+GeometryResult::Mode StrokeRectGeometry::GetResultMode() const {
+  // Most(all?) of our geometry is produced in full with an explicit mode
+  // specified in the returned GeometryResult, but just in case we missed
+  // a case, the safest mode to return here is kPreventOverdraw.
+  return GeometryResult::Mode::kPreventOverdraw;
```
Comment (chinmaygarde) [inline engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: I may be missing something obvious. But this should no longer be necessary now right?

File: engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc (hunk 4 above)
Comment (flar) [reply engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc]: Oh, crap, that was in there for testing. Thanks for finding that.

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc [hunk 6]
```diff
@@ -80,46 +83,117 @@ GeometryResult StrokeRectGeometry::GetPositionBuffer(
...
 
       return GeometryResult{
           .type = PrimitiveType::kTriangleStrip,
           .vertex_buffer =
               {
                   .vertex_buffer = data_host_buffer.Emplace(
                       vertex_count * sizeof(Point), alignof(Point),
-                      [hsw = half_stroke_width, &rect, vertex_count,
-                       &trigs](uint8_t* buffer) {
+                      [hsw = half_stroke_width, &rect, vertex_count, &trigs,
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/geometry/rect_geometry.cc:100]: No abbreviations ("hsw")

https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc (hunk 5 above)
Comment (chinmaygarde) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: My reading of "PreventOverdraw" is "there may be overlapping triangles produced by this geometry but I want you to render them as though there aren't". The fix for the linked issue is either to just specify this result mode, **or** not produce any overlapping trianges. Not both I'd think.

Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: In case anyone adds a new case somewhere that isn't explicitly tagged, I wanted to make sure that we returned the safest option.

This "you can specify it if you want, the default is the one that is least safe but fastest, or you can return it from a method and some of our code might fill it in for you" spectrum of how this Mode is handled can be confusing and I don't think we are doing anyone any maintenance favors by having all of the defaults be "do it the fastest you can and don't worry about the consequences"...?

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc [hunk 7]
```diff
@@ -144,32 +248,59 @@ GeometryResult StrokeRectGeometry::GetPositionBuffer(
...
+                {
+                    .vertex_buffer = data_host_buffer.Emplace(
+                        4 * sizeof(Point), alignof(Point),
+                        [hsw = half_stroke_width, &rect](uint8_t* buffer) {
+                          Scalar left = rect.GetLeft();
+                          Scalar top = rect.GetTop();
+                          Scalar right = rect.GetRight();
+                          Scalar bottom = rect.GetBottom();
+                          auto vertices = reinterpret_cast<Point*>(buffer);
+                          // Zig-zag pattern: UL, UR, LL, LR
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: Upper-left, upper-right, lower-left, lower-right?

**Review by gaaclarke — APPROVED** [review]
lgtm

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc (hunk 5 above)
Comment (chinmaygarde) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: Put another way, I bet the test passes if you only specify this and literally nothing else. So, why not just specify this for simplicity. As I understand, this specification forces a slower path to account for overlaps.

Or am I just mistaken?

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc (hunk 6 above)
Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc:100]: Not going to change this. The following code would become unreadable and unmaintainable.

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc (hunk 7 above)
Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: Yes.

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc (hunk 5 above)
Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: It also runs 50% slower.

Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: kPreventOverdraw isn't magic. It costs - a lot.

Comment (chinmaygarde) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: Yeah, so why specify that as the default on the off chance we missed some edge case.

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc (hunk 6 above)
Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc:100]: `However, a name should not distract the reader by repeating information that's present in the immediate context. Generally, this means that descriptiveness should be proportional to the name's scope of visibility.`

hsw has a short scope of visibility and is defined in the calls of each of these lambdas. It also keeps the coordinate equations well-aligned and balanced.

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc (hunk 5 above)
Comment (chinmaygarde) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: Oh poop, I missed the spot where you explicitly set the mode to be normal for the known fast cases.

I take it that its by far the most common case? If so, all good 😊

**Review by chinmaygarde — APPROVED** [review]
Sorry about the confusion regarding overlap content mode in the default case.

I can totally empathize with the argument that we should fall back to a known safe but slow technique in case we missed something. OTOH, if we missed something, I'd rather folks report it to us as a bug instead of a mysterious performance issue that we'd have a harder time tracking down. Right now, I don't think there are cases we know we will miss. So I don't want to introduce a potential performance cliff.

Perhaps @gaaclarke has a different take but the current state of the patch without the fallback lgtm.

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc (hunk 5 above)
Comment (flar) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: It's not just the most common case, it never falls through. I removed it for now, but I don't like the entire design of this API that assumes things that have consequences that aren't immediately obvious and we construct an entire operation.

File: engine/src/flutter/impeller/entity/geometry/rect_geometry.cc (hunk 7 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/entity/geometry/rect_geometry.cc]: Please, update the comment to avoid these abbreviations.

**Comment by gaaclarke** [comment]
> Perhaps @gaaclarke has a different take but the current state of the patch without the fallback lgtm.

I'm not as familiar as you guys are with the ramifications of using different `GeometryResult::Mode` values.  LGTM.

**Comment by chinmaygarde** [comment]
The gist of it is that strokes that overlap but also have a translucent stroke color will look weird where they overlap. I'll need to lookup the technique used to render them right but the a solid stroke is rendered offscreen and composited with the alpha component onscreen. Hence the slowness.

**Comment by chinmaygarde** [comment]
Looks like the golden diffs are for the test cases you added 🎉
