### PR TITLE
fix a BackButtonListener bug

### LINKED ISSUE #80323: BackButtonListener not working
in the reproducible sample i attached below, when you go to search delegate, you should be able to press back button two times, however, it doesn't work, because `onBackButtonPressed` is never called

what i found remarkable - when i tested it myself as a code snippet from issue https://github.com/flutter/flutter/issues/74437#issuecomment-765576033, it was working for me, so i tried to comment out `didUpdateWidget` from the implementation and BOOM - it starts working

https://github.com/flutter/flutter/blob/7cec142f8c738f6a7b1844db1de47da0f3888c62/packages/flutter/lib/src/widgets/router.dart#L1050-L1057

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  return runApp(App());
}

class App extends StatelessWidget {
  static GlobalKey<NavigatorState> navigatorKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Flutter Demo',
      theme: ThemeData(primaryColor: Colors.white),
      routeInformationParser: AppRouteInformationParser(),
      routerDelegate: AppRouter.instance,
      debugShowCheckedModeBanner: false,
    );
  }
}

class HomeScreen extends StatefulWidget {
  HomeScreen({Key key}) : super(key: key);

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> with RouteAware {
  final List<int> list = List.generate(1000, (index) => index);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          child: const Text('Go'),
          onPressed: () {
            showSearch(context: context, delegate: ImplementedSearchDelegate());
          },
        ),
      ),
    );
  }
}

class ImplementedSearchDelegate extends SearchDelegate {
  @override
  List<Widget> buildActions(BuildContext context) {
    return [];
  }
  
  @override
  Widget buildLeading(BuildContext context) {
    return Container();
  }
  
  @override
  Widget buildResults(BuildContext context) {
    return Container();
  }

  bool canPop = false; 
  @override
  Widget buildSuggestions(BuildContext context) {
    return BackButtonListener(
      onBackButtonPressed: () async {
        if (!canPop) {
          canPop = true;
          return true;
        }
        return false;
      },
      child: Center()
    );
  }
}

class AppRoutes {
  const AppRoutes._(this.location);
  final String location;

  static const home = AppRoutes._('/');
}

class AppRouteInformationParser extends RouteInformationParser<AppRoutes> {
  @override
  Future<AppRoutes> parseRouteInformation(RouteInformation routeInformation) async {
    return AppRoutes._(routeInformation.location);
  }

  @override
  RouteInformation restoreRouteInformation(AppRoutes configuration) {
    return RouteInformation(location: configuration.location);
  }
}

class AppRouter extends RouterDelegate<AppRoutes>
  with ChangeNotifier,
       PopNavigatorRouterDelegateMixin {

  AppRouter._();
  static final AppRouter instance = AppRouter._();

  AppRoutes _currentConfiguration = AppRoutes.home;

  @override
  AppRoutes get currentConfiguration => _currentConfiguration;

  @override
  Future<void> setNewRoutePath(AppRoutes configuration) async {
    _currentConfiguration = configuration;
    notifyListeners();
  }
         
  @override
  GlobalKey<NavigatorState> get navigatorKey => App.navigatorKey;

  @override
  Widget build(BuildContext context) {
    return Navigator(
      key: navigatorKey,
      pages: <Page<void>>[
        MaterialPage(
          key: ValueKey('home'),
          child: HomeScreen(),
        ),
      ],
      onPopPage: (route, result) {
        final bool success = route.didPop(result);
        if (success) {
          _currentConfiguration = AppRoutes.home;
        }
        return success;
      },
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.574, on Microsoft Windows [Version 10.0.19041.867], locale ru-RU)
    • Flutter version 2.1.0-13.0.pre.574 at c:\dev\src\flutter
    • Framework revision 02efffc134 (33 hours ago), 2021-04-10 03:49:01 -0400
    • Engine revision 8863afff16
    • Dart version 2.13.0 (build 2.13.0-222.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```
</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes #80323

### CODE REVIEW

File: packages/flutter/lib/src/widgets/router.dart [hunk 1]
```diff
@@ -1052,6 +1052,7 @@ class _BackButtonListenerState extends State<BackButtonListener> {
     if (oldWidget.onBackButtonPressed != widget.onBackButtonPressed) {
       dispatcher?.removeCallback(oldWidget.onBackButtonPressed);
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/router.dart:1053]: `ChildBackButtonDispatcher.removeCallback` will remove itself from parent.
```dart
  @override
  void removeCallback(ValueGetter<Future<bool>> callback) {
    super.removeCallback(callback);
    if (!hasCallbacks)
      parent.forget(this);
  }
```

File: packages/flutter/test/widgets/router_test.dart [hunk 2]
```diff
@@ -1032,6 +1032,64 @@ testWidgets('ChildBackButtonDispatcher take priority recursively', (WidgetTester
     await tester.pump();
     expect(find.text('popped inner1'), findsOneWidget);
   });
+
+  testWidgets('`didUpdateWidget` test', (WidgetTester tester) async {
```
Comment (xu-baolin) [inline packages/flutter/test/widgets/router_test.dart:1036]: The existing  [test ](https://github.com/douglasiacovelli/flutter/blob/bd4043077de1a7f437778d45076ddf00d941f25b/packages/flutter/test/widgets/router_test.dart#L777) case will trigger `didUpdateWidget` and `didChangeDependencies`(`_RouterScope` InheritedWidget change) at the same time, so no bug will be triggered.

File: packages/flutter/lib/src/widgets/router.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/router.dart:1053]: Ah nice catch!

**Review by chunhtai — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/router.dart (hunk 1 above)
Comment (nt4f04uNd) [reply packages/flutter/lib/src/widgets/router.dart:1053]: maybe add `updateCallback` instead?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/router.dart:1053]: update callback need to remove the old callback, this will not work. The other way to avoid the take priority is to swap the order
```dart
dispatcher?.addCallback(widget.onBackButtonPressed);
dispatcher?.removeCallback(oldWidget.onBackButtonPressed);
```

**Comment by xu-baolin** [comment]
Google test looks unhappy T_T

**Comment by chunhtai** [comment]
@xu-baolin can you try rebasing off the latest master and see if that fixes the google test?
