### PR TITLE
Fix scrollUntilVisible in WidgetTester

### LINKED ISSUE #143921: [flutter_test]scrollUntilVisible has different results if ListTile's onTap is null or not
### Steps to reproduce

1. Paste sample code to tests/xxx_test.dart in Flutter project
2. Execute test by flutter test --plain-name 'scrollUntilVisible'

### Expected results

The test passes, whether or not the ListTile's onTap attribute is null.

### Actual results

The test will fail if ListTile's onTap attribute is not null.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

// flutter test --plain-name 'scrollUntilVisible'
void main() {
  group("scrollUntilVisible", () {
    Future<void> pumpListViewAndScrollToEndContent(
        WidgetTester tester, bool hasOnTap) async {
      int itemCount = 30;
      final controller = ScrollController();
      await tester.pumpWidget(MaterialApp(
          home: Scaffold(
        body: ListView.builder(
          controller: controller,
          itemBuilder: (context, index) {
            if (index <= itemCount) {
              return ListTile(
                onTap: hasOnTap
                    ? () {
                        //debugPrint("tapped");
                      }
                    : null,
                title: Text("$index"),
              );
            }
            return null;
          },
        ),
      )));

      // controller.addListener(() {
      //   debugPrint(
      //       "${controller.position.pixels}, ${controller.position.maxScrollExtent}");
      // });

      await tester.scrollUntilVisible(
        find.text("${itemCount - 1}"),
        20,
        maxScrolls: 2000,
        duration: const Duration(milliseconds: 50),
        scrollable: find.byType(Scrollable),
      );
    }

    testWidgets("This results success", (tester) async {
      // ListTile has "onTap" as null
      await pumpListViewAndScrollToEndContent(tester, false);
    });

    testWidgets("This results failed", (tester) async {
      // ListTile has "onTap" as not null
      await pumpListViewAndScrollToEndContent(tester, true);
    });
  });
}

```

</details>

### Screenshots or Video

_No response_

### Logs

<details open><summary>Logs</summary>

```console
% flutter test --plain-name 'scrollUntilVisible'
00:06 +1: /xxx/xxx.dart: scrollUntilVisible This results failed                                                      
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:674:25)
#1      WidgetController.element (package:flutter_test/src/controller.dart:448:30)
#2      WidgetController.dragUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1709:38)
<asynchronous suspension>
#3      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:117:7)
<asynchronous suspension>
#4      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1675:7)
<asynchronous suspension>
#5      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:117:7)
<asynchronous suspension>
#6      main.<anonymous closure>.pumpListViewAndScrollToEndContent (/xxx/xxx_test.dart:36:7)
<asynchronous suspension>
#7      main.<anonymous closure>.<anonymous closure> (/xxx/xxx_test.dart:52:7)
<asynchronous suspension>
#8      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
<asynchronous suspension>
#9      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

</details>

### Flutter Doctor output

<details open><summary>I have not installed the Android environment, but it is not related to the test.</summary>

```console
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.1.1 23B81 darwin-arm64, locale ja-JP)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.86.0)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by hgraceb**
Fixes #143921.

The single `moveBy` event may be consumed when `onTap` is present.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_test/lib/src/controller.dart [hunk 1]
```diff
@@ -2221,12 +2222,17 @@ abstract class WidgetController {
     int maxIteration = 50,
     Duration duration = const Duration(milliseconds: 50),
   }) {
+    assert(moveStep != Offset.zero);
+    assert(maxIteration > 0);
```
Comment (victorsanni) [inline packages/flutter_test/lib/src/controller.dart:2226]: (from offline review with @Piinks) these asserts (plus the delta assert) look valid. Are they related to this change specifically or just good to have generally? And can we add tests for them in either case?

Comment (hgraceb) [reply packages/flutter_test/lib/src/controller.dart:2226]: Should I revert the asserts and the corresponding tests first, and then submit a new PR later?

**Review by victorsanni — APPROVED** [review]
LGTM! Thanks for the PR.

**Review by Piinks — APPROVED** [review]
LGTM thank you!

File: packages/flutter_test/lib/src/controller.dart [hunk 2]
```diff
@@ -2222,11 +2222,14 @@ abstract class WidgetController {
     Duration duration = const Duration(milliseconds: 50),
   }) {
     return TestAsyncUtils.guard<void>(() async {
+      TestGesture? gesture;
       while (maxIteration > 0 && finder.evaluate().isEmpty) {
-        await drag(view, moveStep);
+        gesture ??= await startGesture(getCenter(view, warnIfMissed: true));
+        await gesture.moveBy(moveStep);
```
Comment (victorsanni) [inline packages/flutter_test/lib/src/controller.dart:2228]: There are quite a lot of google testing failures. I wonder if there are things in the `drag` method that this refactor doesn't replace?

Comment (Piinks) [reply packages/flutter_test/lib/src/controller.dart:2228]: I'm guessing the tests this affects in Google were written to expect the behavior written in the bug. This might be difficult to change since it breaks existing test logic.

**Comment by goderbauer** [comment]
Maybe we need to introduce this as a new method or guard it behind a parameter to not break all the existing code?

**Comment by goderbauer** [comment]
(triage): @hgraceb Are you interested in updating this to make it opt-in (e.g. as a new method or via a parameter).

**Comment by hgraceb** [comment]
@goderbauer Sorry, I haven't had time to follow up on this issue recently because I've been job hunting. I might try to make some updates this week or next week.

**Comment by hgraceb** [comment]
@victorsanni @goderbauer Hi, I tried to keep all the original code logic and only reuse the gesture, but the Google tests are still failing. I might need some more specific error examples to make further changes. Can someone help provide a portion of the failing test code?

**Comment by victorsanni** [comment]
> Hi, I tried to keep all the original code logic and only reuse the gesture, but the Google tests are still failing. I might need some more specific error examples to make further changes. Can someone help provide a portion of the failing test code?

Most of the test failures are image diffs reflecting the previous behavior, as @Piinks [mentioned](https://github.com/flutter/flutter/pull/159582#discussion_r1876433084). Can we make the behavior opt in as @goderbauer [described](https://github.com/flutter/flutter/pull/159582#issuecomment-2549863642)?

File: packages/flutter_test/test/controller_test.dart [hunk 3]
```diff
@@ -612,6 +612,47 @@ void main() {
...
+    await tester.pumpAndSettle();
+    expect(target, findsNothing);
+    await tester.scrollUntilVisible(target, 20, scrollable: scrollable, continuous: true);
+    expect(target, findsOneWidget);
+
+    // Scroll with onTap.
+    await tester.pumpWidget(buildFrame(true));
+    await tester.pumpAndSettle();
+    expect(target, findsNothing);
+    await tester.scrollUntilVisible(target, 20, scrollable: scrollable, continuous: true);
```
Comment (victorsanni) [inline packages/flutter_test/test/controller_test.dart:652]: Should this test also check for the correct behavior when `continuous = false`?

**Review by victorsanni — APPROVED** [review]

File: packages/flutter_test/test/controller_test.dart (hunk 3 above)
Comment (hgraceb) [reply packages/flutter_test/test/controller_test.dart:652]: @victorsanni I don't think there is a 'correct' behavior in this case when `continuous = false`. The fact that all tests without the continuous parameter have passed is the correct behavior. If your suggestion is that I should add another test to ensure that the function works the same way when `continuous = false`, then I will add that test.

By the way, do you know how I should handle the persistent errors with [Linux analyze](https://github.com/flutter/flutter/pull/159582/checks?check_run_id=36245402250)? The logs only contain some garbled text, and I can't execute the same commands locally.
