### PR TITLE
Fix analytics regression

### LINKED ISSUE #46165: Target platform name not set for "run" command analytics screen
In https://github.com/flutter/flutter/pull/45267, the query for connected devices was moved after sending the analytics screen. This results in the analytics screen not including the target name of the connected device.

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

In https://github.com/flutter/flutter/pull/45267, the tool stopped sending target device information on run command analytics events. This happened because the setting of `List<Device> devices` was moved from the run `validateCommand()` method to the `runCommand()` method. However, the order of events in the `verifyThenRunCommand()` method is to:

1. call `validateCommand()`
2. update the cache
3. send usage event
4. call `runCommand()`

This PR fixes the regression by moving the setting of `devices` back to `validateCommand()`, but changing the order of events in `verifyThenRunCommand()` to:

1. update the cache
2. call `validateCommand()`
3. send the usage event
4. call `runCommand()`

## Related Issues

Fixes https://github.com/flutter/flutter/issues/46165.

## Tests

I fixed the "updates before checking devices" test, and added a new test verifying that we send the command event with the proper device data.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/run.dart [hunk 1]
```diff
@@ -284,6 +284,10 @@ class RunCommand extends RunCommandBase {
     if (!runningWithPrebuiltApplication) {
       await super.validateCommand();
     }
+    devices = await findAllTargetDevices();
+    if (devices == null) {
+      throwToolExit(null);
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/commands/run.dart]: Should this give a message like "Failed to find a target device" ?

**Review by zanderso — APPROVED** [review]
lgtm w/ question

File: packages/flutter_tools/lib/src/commands/run.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/run.dart]: In `findAllTargetDevices()`, before returning `null`, the appropriate `userMessages` will be printed to stdout; in this case:

```sh
~/git/flutter/examples/hello_world$ flutter run
Building flutter tool...
No supported devices connected.
```

So we're covered. I'll add a test verifying this (we have one for attach, but not for run) though.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/run.dart]: Added a test, PTAL

**Review by zanderso — APPROVED** [review]
still lgtm
