### PR TITLE
Desktop edge scrolling

### LINKED ISSUE #32344: Implement edge scrolling for text selection in Text/TextField
In the gif I attempted to extend the text selection beyond the word "wondering" (the first visible word) but wasn't able to. The text field should scroll upwards to allow me to further expand the selected area.

edgescrolling

### LINKED ISSUE #59141: Can't select text with mouse once it's longer than the text field
## Steps to Reproduce

Sometimes, I cannot select and highlight the text in TextField with mouse.
* I used the latest Flutter SDK and GTK embedding.

1. Enter to some characters in the TextField.
2. Select text with mouse left click and moving.

bug_report2

<details>
  <summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-6.0.pre.42, on Linux, locale ja_JP.UTF-8)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.45.1)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

</details>

Thank you.

### PR DESCRIPTION
**Pull request by justinmc**
When selection moves on desktop, the field will now scroll to view the scroll extent, like it already does on mobile.

edge_mac_2

TODO:
 - [x] Make sure horizontal edge scrolling works.
 - [x] Make sure this works on Windows.
 - [x] Tests.

Fixes https://github.com/flutter/flutter/issues/32344
Fixes https://github.com/flutter/flutter/issues/59141

### CODE REVIEW

**Comment by justinmc** [comment]
@mdebbar Is this old TODO of yours actually fixed?

https://github.com/flutter/flutter/blob/2a00eacfacfed1f04d52346bd78ed02e37e39a19/packages/flutter/lib/src/widgets/text_selection.dart#L1530-L1531

I ran into a strange problem where vertical mouse dragging wasn't being detected properly in a test.  I'm wondering if there's anything unimplemented there that could be causing it, or if that TODO should be removed.

**Comment by mdebbar** [comment]
@justinmc if you look at that code, it's only using a `HorizontalDragGestureRecognizer` which doesn't detect vertical dragging. At that time, vertical dragging was used for scrolling (even on web, because there was no scroll bars yet). But now I think that's not the case anymore. Maybe we should use `PanGestureRecognizer`?

**Comment by justinmc** [comment]
Sounds good, thanks for the info.  I'll make a quick attempt at using PanGestureRecognizer and see if that fixes the strange missing vertical drag component that I saw in the test.  If it seems complicated, I'll save it for another PR.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 1]
```diff
@@ -1409,14 +1409,24 @@ class _TextSelectionGestureDetectorState extends State<TextSelectionGestureDetec
   DragStartDetails? _lastDragStartDetails;
   DragUpdateDetails? _lastDragUpdateDetails;
   Timer? _dragUpdateThrottleTimer;
+  bool _isMouseDragging = false;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:1412]: HorizontalDragGestureRecognizer allows you to specify the type of pointer to accept, but now that we've switched to PanGestureRecognizer, which doesn't support that, we have to manually make sure we only listen to mouse drags.

**Comment by justinmc** [comment]
@mdebbar Switching to PanGestureRecognizer worked without too much tweaking, and it fixed my test!  I've replaced it here in this PR and removed your TODO.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 1 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_selection.dart:1412]: Would it be possible to add that to the existing `PanGestureRecognizer` or have a private subclass of `PanGestureRecognizer`?

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 2]
```diff
@@ -967,15 +967,30 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with Restoratio
...
     if (willShowSelectionHandles != _showSelectionHandles) {
       setState(() {
         _showSelectionHandles = willShowSelectionHandles;
       });
     }
+
+    switch (defaultTargetPlatform) {
+      case TargetPlatform.iOS:
+      case TargetPlatform.macOS:
+        if (cause == SelectionChangedCause.longPress
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/text_field.dart:980]: Just curious what does a long-press do on iOS and macOS? Is it the force press floating cursor that makes them different?

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart]: Great idea, looks like it's actually only a 2 line change to add it to PanGesureRecognizer because the super class already supports it.

File: packages/flutter/lib/src/gestures/monodrag.dart [hunk 3]
```diff
@@ -614,7 +614,13 @@ class HorizontalDragGestureRecognizer extends DragGestureRecognizer {
 ///    some time has passed.
 class PanGestureRecognizer extends DragGestureRecognizer {
   /// Create a gesture recognizer for tracking movement on a plane.
-  PanGestureRecognizer({ Object? debugOwner }) : super(debugOwner: debugOwner);
+  PanGestureRecognizer({
+    Object? debugOwner,
+    PointerDeviceKind? kind,
+  }) : super(
+         debugOwner: debugOwner,
+         kind: kind,
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/gestures/monodrag.dart:622]: `kind` is deprecated I think?

File: packages/flutter/lib/src/cupertino/text_field.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_field.dart:980]: Yup this handles the thing where you force press and then drag the cursor.

File: packages/flutter/lib/src/gestures/monodrag.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/gestures/monodrag.dart:622]: Ah I missed that, thanks.  I'll do the same thing but with `supportedDevices` as the deprecation message suggests.

**Review by LongCatIsLooong — APPROVED** [review]
LGTM. This should also close https://github.com/flutter/flutter/issues/28676 (the TODO issue) right?

**Comment by justinmc** [comment]
@LongCatIsLooong That one is already closed, but I guess the TODO was missed.

**Comment by justinmc** [comment]
Adding the cherry pick tag after discussing with @mariamhas, if we're still doing cherry picks for 2.8.  Shouldn't be a high risk of regressions.

**Comment by devoncarew** [comment]
@justinmc and @HansMuller - when was this regression introduced? What's the impact if we don't take it for this hotfix? We should carefully weigh taking it now (the week right before the release) w/ delaying until a batch of fixes after the release.

**Comment by justinmc** [comment]
I'm ok with skipping this.  The behavior without it is fairly bad, but it's actually not a regression.  Also there were previously a few goldens issues with this.  Probably best to let it be released normally if @mariamhas is alright with that.
