### PR TITLE
[gen-l10n] Fix untranslated messages

### LINKED ISSUE #67138: Flutter gen-l10n untranslated messages warning false positive
## Steps to Reproduce

1. `flutter create .`
2. create `app_en.arb` in `lib/l10n`, for example:
```json
{
    "helloWorld": "Hello World",
    "@helloWorld": {
        "description": "Generic text"
    }
}
```
3. set `flutter: generate: true` in `pubspec.yaml`, create an empty `l10n.yaml` in project root
4. run `flutter run` or `flutter gen-l10n`
**Expected results:** Everything is translated, no message
**Actual results:** Right after starting the build the first message in console is:
```
To see a detailed report, use the --untranslated-messages-file 
option in the tool to generate a JSON format file containing 
all messages that need to be translated.
```

- `--untranslated-messages-file` flag doesn't generate any file
- `--gen-inputs-and-outputs-list` file doesn't contain the untranslated-messages-file

Appeared in 1.22.0 release

<details>
  <summary>Logs</summary>

```
%USERPROFILE%\DEV\files\flutter\gen_l10n_bug>flutter gen-l10n --untranslated-messages-file file.json -v
[ +184 ms] executing: [%USERPROFILE%\DEV\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +154 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] d408d302e22179d598f467e11da5dd968dbdc9ec
[   +2 ms] executing: [%USERPROFILE%\DEV\tools\flutter/] git tag --points-at HEAD
[ +145 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.0
           1.22.0-12.3.pre
[  +22 ms] executing: [%USERPROFILE%\DEV\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +125 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [%USERPROFILE%\DEV\tools\flutter/] git ls-remote --get-url origin
[  +91 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +159 ms] executing: [%USERPROFILE%\DEV\tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +175 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +51 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +29 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +25 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +50 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +40 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[  +55 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +34 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +29 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +47 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +26 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +370 ms] "flutter gen-l10n" took 914ms.
[ +269 ms] ensureAnalyticsSent: 258ms
[   +3 ms] Running shutdown hooks
[  +16 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

%USERPROFILE%\DEV\files\flutter\gen_l10n_bug>flutter gen-l10n -v                                        
[ +202 ms] executing: [%USERPROFILE%\DEV\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +134 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] d408d302e22179d598f467e11da5dd968dbdc9ec
[   +2 ms] executing: [%USERPROFILE%\DEV\tools\flutter/] git tag --points-at HEAD
[ +135 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.0
           1.22.0-12.3.pre
[  +47 ms] executing: [%USERPROFILE%\DEV\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +140 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [%USERPROFILE%\DEV\tools\flutter/] git ls-remote --get-url origin
[  +82 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +201 ms] executing: [%USERPROFILE%\DEV\tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +90 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +159 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +32 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +57 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +49 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +44 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +77 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +45 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +338 ms] To see a detailed report, use the --untranslated-messages-file 
                    option in the tool to generate a JSON format file containing 
                    all messages that need to be translated.
[  +64 ms] "flutter gen-l10n" took 785ms.
[ +300 ms] ensureAnalyticsSent: 263ms
[   +3 ms] Running shutdown hooks
[  +18 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

```

```
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.20221.1000], locale en-150)
    • Flutter version 1.22.0 at C:\Users\sominemo\DEV\tools\flutter
    • Framework revision d408d302e2 (3 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\sominemo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.49.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • Pixel 4 (mobile) • 9A231FFAZ006J5 • android-arm64 • Android 11 (API 30)

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

Fixes the following issues:
- `--untranslated-messages-file` flag doesn't generate any file when all messages have already been translated. This PR now generates an empty JSON file when this is the case.
- `--gen-inputs-and-outputs-list` file doesn't contain the untranslated-messages-file. It now will.
- Only print message with missing translations status when unimplemented messages is empty
- The deprecated path has been pointing to the wrong command (`flutter generate-localizations` instead of `flutter gen-l10n`). Since this has been broken for some time without any complaints, maybe it's a good time to remove it altogether.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/67138

## Tests

I added the following tests:

- A test to ensure that inputs and outputs list contains the untranslated messages file when specified
- Tests to ensure that the untranslated messages file status correctly generated

### CODE REVIEW

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 1]
```diff
@@ -514,6 +514,10 @@ class LocalizationsGenerator {
   /// classes.
   String _generatedLocalizationsFile;
 
+  /// A generated file that will contain the list of messages for each locale
+  /// that has does not have a translation yet.
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/localizations/gen_l10n.dart:518]: that do not have a

**Review by HansMuller — APPROVED** [review]
LGTM
