### PR TITLE
[RenderEditable] fix crash & remove `TextPainter.layout` short-circuiting

### LINKED ISSUE #84896: `RenderEditable` crash: `_textPainter.paragraph` is null.
No repro unfortunately. Internal links: b/191227237, 

Stacktraces:
```	
at TextPainter._getRectFromDownstream	(text_painter.dart:732)
at TextPainter._computeCaretMetrics	(text_painter.dart:832)
at TextPainter.getOffsetForCaret	(text_painter.dart:792)
at RenderEditable._updateSelectionExtentsVisibility	(editable.dart:417)
at RenderEditable._paintContents	(editable.dart:2311)
at RenderEditable.paint	(editable.dart:2374)
at RenderObject._paintWithContext	(object.dart:2315)
at PaintingContext.paintChild	(object.dart:189)
at RenderProxyBoxMixin.paint	(proxy_box.dart:144)
```

```
Thread 0 main thread_CastError: Null check operator used on a null value
at TextPainter._getRectFromDownstream	(text_painter.dart:750)
at TextPainter._computeCaretMetrics	(text_painter.dart:850)
at TextPainter.getOffsetForCaret	(text_painter.dart:810)
at _FloatingCursorPainter.paintRegularCursor	(editable.dart:4007)
at _FloatingCursorPainter.paint	(editable.dart:4079)
at _CompositeRenderEditablePainter.paint	(editable.dart:4131)
at _RenderEditableCustomPaint.paint	(editable.dart:3781)
at RenderObject._paintWithContext	(object.dart:2326)
at PaintingContext._repaintCompositedChild	(object.dart:139)
at PipelineOwner.flushPaint	(object.dart:100)
```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Maybe fixes https://github.com/flutter/flutter/issues/84896:

The crash likely happened on an invisible & keepalive `TextField` that lives in a multi-box adapter. `TextField` does not have relayout boundaries but may contain multiple repaint boundaries, in which case:
-  `markNeedsLayout` only calls `markParentNeedsLayout`. So the parent `RenderObject` is responsible for calling `layout` on this `RenderObject`,  instead of the pipeline owner. when the `RenderObject` is in a keepalive bucket, the parent may choose to not do so because the `RenderObject` is going to be invisible,
-  but `markNeedsPaint` actually adds the repaint boundary to the pipeline owner's dirty nodes list. 

When this happens we're painting using outdated layout information. In the case of `RenderEditable` it may crash because we may have called `_textPainter.markNeedsLayout`, and accessing text metrics will crash without first calling `_textPainter.layout` (which is supposed to be called by the `RenderObject`'s `RenderObject.performLayout`).

This fix is a hack. A "keepalive" `RenderObject` should probably not be allowed to paint if it's not laid out.

### Other fixes

```dart
    if (_textLayoutLastMaxWidth == maxWidth && _textLayoutLastMinWidth == minWidth)
      return;
```
may skip text painter layout when it's actually needed, as `maxWidth` and `minWidth` are not the only input of the layout algorithm.
plus `TextPainter.layout` is already doing something similar: 
https://github.com/flutter/flutter/blob/a1a360bf1385d82ef99319fed06352a2d0189b21/packages/flutter/lib/src/painting/text_painter.dart#L582-L583

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -301,6 +301,8 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
     _foregroundRenderObject = null;
     _backgroundRenderObject?.dispose();
     _backgroundRenderObject = null;
+    _cachedBuiltInForegroundPainters?.dispose();
+    _cachedBuiltInPainters?.dispose();
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:305]: Good catch!

File: packages/flutter/lib/src/rendering/editable.dart [hunk 2]
```diff
@@ -3707,6 +3705,25 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
     _textLayoutLastMaxWidth = maxWidth;
   }
 
+  // Computes the text metrics if `_textPainter`'s layout information was marked
+  // as dirty.
+  //
+  // This method must be called in [RenderEditable]'s public methods that
+  // expose `_textPainter`'s metrics. For instance, `systemFontsDidChange` sets
+  // _textPainter._paragraph to null, accessing _textPainter's metrics
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:3713]: "null, accessing" => "null, so accessing"

File: packages/flutter/lib/src/rendering/editable.dart [hunk 3]
```diff
@@ -3707,6 +3705,25 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
...
+  // immediately after `systemFontsDidChange` without first calling this method
+  // may crash.
+  //
+  // This method is also called in various paint methods (`RenderEditable.paint`
+  // as well as its foreground/background painters' `paint`). It's needed
+  // because invisible render objects kept in the tree by `KeepAlive` may not
+  // get a chance to do layout but can still paint.
+  // See https://github.com/flutter/flutter/issues/84896.
+  void _computeTextMetricsIfNeeded() {
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:3722]: Why is it called "IfNeeded"?  I expected some kind of conditional in this method.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 4]
```diff
@@ -4071,6 +4088,7 @@ class _RenderEditableCustomPaint extends RenderBox {
     assert(parent != null);
     final RenderEditablePainter? painter = this.painter;
     if (painter != null && parent != null) {
+      parent._computeTextMetricsIfNeeded();
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:4091]: Any potential performance impact from this and/or the removal of the conditional in _layoutText?

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 5]
```diff
@@ -1142,6 +1142,75 @@ void main() {
...
+                  cursorColor: cursorColor,
+                  showCursor: true,
+                ),
+              ],
+            ),
+          ),
+        ),
+      );
+
+      EditableText.debugDeterministicCursor = false;
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:1211]: Would this be a good place to use `expect(tester.takeException(), isNull);`?  Or maybe it's not necessary and the test would fail anyway, I'm not sure...

**Review by justinmc — APPROVED** [review]
LGTM

Some questions I wanted to think about in my comments but otherwise should be fine.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:3722]: The condition lives in `TextPainter.layout`: https://github.com/flutter/flutter/blob/a1a360bf1385d82ef99319fed06352a2d0189b21/packages/flutter/lib/src/painting/text_painter.dart#L582-L583. I added a few more lines to the code comments.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 4 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:4096]: - removal the conditional:

I think `TextPainter.layout` is already doing a good enough job caching the layout results. Most of the time when ` _textLayoutLastMaxWidth == maxWidth && _textLayoutLastMinWidth == minWidth` evaluates to true in `_layoutText` , ` !_needsLayout && minWidth == _lastMinWidth && maxWidth == _lastMaxWidth` in `TextPainter.layout` would return true anyways (so it's just a few additional instructions).
in cases where the former evaluates to true but the latter evaluates to false, the cache is either already invalidated ( `_needsLayout` is true, so accessing the text layout will crash), or the cache was computed using a different set of constraints and should be invalidated.

- adding `_computeTextMetricsIfNeeded` here: 

Yeah I think the multibox adapter should prevent this render object from painting since it didn't layout. But since its constraints are not changed (unless `computeDryLayout` or one of the compute intrinsics methods were called after the last `performLayout` call), the cache is likely going to hit if it's not invalidated.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:4096]: There's an edge case where `_textLayoutLastMaxWidth == maxWidth && _textLayoutLastMinWidth == minWidth` is not sufficient. See the test added in `editable_test.dart`.
