### PR TITLE
Filter Android logs by the pid of the remote process

### LINKED ISSUE #6849: Services: not displaying errors/exceptions from Java side in flutter logs
If there's a runtime exception in the Java code of a running Flutter app, we don't see an actionable log entry in the flutter logs output.

Here's what we see in the Flutter console output:

```
Built android/app/build/outputs/apk/app-debug.apk (7.5MB).
Running lib/main.dart on Moto G 4...
E/flutter (14047): [ERROR:../../flutter/assets/unzipper_provider.cc(16)] Unable to open zip file: /data/user/0/com.example.flutter/app_sky_shell/app.flx
F/flutter (14047): [FATAL:jni_android.cc(249)] Check failed: false. Please include Java exception stack in crash report
```

See "unable to open zip file" , which is a bit weird because the actual error on the Java side was actually about not getting a file path correct. :)

Since we knew enough of adb, we did display the log. But, for the less experienced developer, we'll want to show log entries from the Java code from a Flutter app (especially, the Java code the user wrote).

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/6849

### CODE REVIEW

File: packages/flutter_tools/lib/src/device.dart [hunk 1]
```diff
@@ -378,6 +378,8 @@ abstract class DeviceLogReader {
 
   @override
   String toString() => name;
+
+  set pid(int value) { }
```
Comment (cbracken) [inline packages/flutter_tools/lib/src/device.dart]: Any reason not to make this read-write & clear up the subclass?

Comment (jason-simmons) [inline packages/flutter_tools/lib/src/device.dart]: This was done in case subclasses needed to add side effects when the pid is set, but it looks like that's unnecessary.  Moved this to a field in the superclass.

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm
