### PR TITLE
Fix flaky complex_layout_scroll_perf__memory test

### LINKED ISSUE #150096: Linux_mokey complex_layout_scroll_perf__memory is 2.44% flaky
The post-submit test builder `Linux_mokey complex_layout_scroll_perf__memory` had a flaky ratio 2.44% for the past (up to) 100 commits, which is above our 2.00% threshold.

One recent flaky example for a same commit: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_mokey%20complex_layout_scroll_perf__memory/35
Commit: https://github.com/flutter/flutter/commit/14df7be3f9471a97f34e4601fb7710850373ac3b

Flaky builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_mokey%20complex_layout_scroll_perf__memory/35

Recent test runs:
https://flutter-dashboard.appspot.com/#/build?taskFilter=Linux_mokey%20complex_layout_scroll_perf__memory

Please follow https://github.com/flutter/flutter/blob/master/docs/infra/Reducing-Test-Flakiness.md#fixing-flaky-tests to fix the flakiness and enable the test back after validating the fix (internal dashboard to validate: go/flutter_test_flakiness).

### PR DESCRIPTION
**Pull request by jtmcdole**
Initial tap is missing sometimes; either its never delivered or it is delivered before gesture controller is hooked up.

1: Update the two perf tests to output when TAPPED is received
2: Update the MemoryTest to keep tapping while waiting for TAPPED

Tested on devicelab:
* setting iterations=1
* removing the timeout before READY
* running tests in a while loop

Before this change, you could get the test to hang often. After this change you'll see "tapping device... [x]" where x is the counter.

Fixes #150096

### CODE REVIEW

File: dev/devicelab/lib/tasks/perf_tests.dart [hunk 1]
```diff
@@ -2071,9 +2071,34 @@ class MemoryTest {
     await launchApp();
     await recordStart();
 
+    // Keep "tapping" the device till it responds with the string we expect,
+    // or throw an error instead of tying up the infrastructure for 30 minutes.
+    prepareForNextMessage('TAPPED');
+    bool tapped = false;
+    int i = 0;
```
Comment (gaaclarke) [inline dev/devicelab/lib/tasks/perf_tests.dart:2078]:
```suggestion
    int tapCount = 0;
```

**Review by gaaclarke — APPROVED** [review]
lgtm modulo single character variable name.

Instead of repeatedly tapping, it seems like you could do the same thing you did to receive the tap event to know when the thing is ready to be tapped.  Seems like there should be a latch for that in Flutter?  Maybe sending the message when the `State` is initialized would be enough?

There is a risk of accidentally tapping twice before registering the tap because of some sort of latency in receiving the TAPPED print statement.  Hopefully 250ms makes that unlikely though and is definitely better than what we had.

**Comment by jtmcdole** [comment]
> Instead of repeatedly tapping, it seems like you could do the same thing you did to receive the tap event to know when the thing is ready to be tapped. Seems like there should be a latch for that in Flutter? Maybe sending the message when the `State` is initialized would be enough?

I think that would be a moving target. If there was a magical "we're ready for input" then I'd wait on it; but a side effect of state loaded might be undocumented.

> There is a risk of accidentally tapping twice before registering the tap because of some sort of latency in receiving the TAPPED print statement. Hopefully 250ms makes that unlikely though and is definitely better than what we had.

I could increase the caffeine to 100ms tapping if that makes things better.  We could also delay after the READY for ~milliseconds.

**Comment by jtmcdole** [comment]
The other tests  don't send the "TAPPED" signal, so of course they timeout.

**Comment by jtmcdole** [comment]
Reason for revert: other memperf tests don't wait for or send a TAPPED; so they fail.
