### PR TITLE
[tool] ⚡️ Install the corresponding APK in `flutter run`

### LINKED ISSUE #111585: [tool] `flutter run` runs only `app.apk`
## Steps to Reproduce

1. Configure flavors for the Android app, such as "inside".
2. `flutter run --flavor=inside`
3. The `Installing xxx.apk` has a different path from `Built xxx.apk`.

`android/app/build.gradle`:
```groovy
//......
android {
    //......
    flavorDimensions "app"
    productFlavors {
        inside {}
        play {}
    }
}
//......
```

image

(`LocalFile` is my additional print.)

```
[!] Flutter (Channel master, 3.4.0-19.0.pre.254, on Microsoft Windows [版本 10.0.22000.856], locale zh-CN)
    • Flutter version 3.4.0-19.0.pre.254 on channel master at X:\SDK\flutter-master
    ! Upstream repository https://github.com/AlexV525/flutter is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/AlexV525/flutter to dismiss this error.
    • Framework revision 6b1f84fe10 (66 minutes ago), 2022-09-14 09:46:00 -0700
    • Engine revision 179d528f6a
    • Dart version 2.19.0 (build 2.19.0-197.0.dev)
    • DevTools version 2.17.0
```

### PR DESCRIPTION
**Pull request by AlexV525**
Fix #111585. The PR makes the tool installs exactly the generated APK file, which corrects the console's output too. Also, SHA1 will be generated for all generated APKs in the batch.

## Filename comparison (DEBUG Mode)

| Install APK file| Before | After |
|-------|-------------|-----------|
| No flavor | app.apk | app-debug.apk |
| Flavor configured | app.apk | app-flavor-debug.apk |

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/application_package.dart [hunk 1]
```diff
@@ -103,11 +103,21 @@ class AndroidApk extends ApplicationPackage implements PrebuiltApplicationPackag
     required ProcessUtils processUtils,
     required Logger logger,
     required FileSystem fileSystem,
+    BuildInfo? buildInfo,
   }) async {
-    File apkFile;
+    final File apkFile;
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/android/application_package.dart:108]: Rather than concatenating to the string, I think this is a little easier to read if the branches yield the complete string, like:

```dart
final File apkFile;
final String filename;
if (buildInfo == null) {
  fileName = 'app.apk';
} else if (buildInfo.flavor == null) {
  fileName = 'app-${buildInfo.mode.name}.apk';
} else {
  fileName = 'app-${buildInfo.lowerCasedFlavor}-${buildInfo.mode.name}.apk';
}
```

Comment (AlexV525) [reply packages/flutter_tools/lib/src/android/application_package.dart:108]: That looks the same as implemented IMO. Could we leave another one for opinion? 😄

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/android/application_package.dart:108]: This is easier to read, as it doesn't have nested branches, and it each final string is on a single line.

**Review by christopherfujino — COMMENTED** [review]
This looks like the correct fix to make, I'll defer final approval to @GaryQian though.

File: packages/flutter_tools/lib/src/android/application_package.dart (hunk 1 above)
Comment (GaryQian) [reply packages/flutter_tools/lib/src/android/application_package.dart:108]: I prefer the better readability in Chris's suggestion, as it is both more searchable and easier for people to comprehend in the future when revisiting this code.

Comment (AlexV525) [reply packages/flutter_tools/lib/src/android/application_package.dart:108]: Thanks for these explanations, applying.

**Comment by AlexV525** [comment]
I'm not sure if any external tools are using `app.apk` in their usages, that's the only thing I'm concerning.

**Comment by GaryQian** [comment]
It's likely that there are tools depending on the `app.apk` copy. It may be reasonable for backwards compatibility to continue copying the first apk and deprecate the usage of the copy. We can add a TODO and phase it out later.

**Comment by AlexV525** [comment]
https://github.com/flutter/flutter/pull/112768/checks?check_run_id=8940587074 The failure doesn't seem to be related.

**Review by GaryQian — APPROVED** [review]
LGTM, Thanks!

**Comment by AlexV525** [comment]
> It may be reasonable for backwards compatibility to continue copying the first apk and deprecate the usage of the copy.

It's unclear how to deprecate a usage like this. The tool itself is not using the file at present, and other tools won't access the file through `flutter_tools`, so we can't raise a deprecate message for it.

**Comment by godofredoc** [comment]
This PR has been reverted because is blocking the tree. \cc @christopherfujino @AlexV525

**Comment by AlexV525** [comment]
@christopherfujino @gspencergoog Could you help me with dumping the tests log? I can't access to the tree's dashboard due to my network issues currently, or maybe a tracking issue. Thanks!

**Comment by christopherfujino** [comment]
> @christopherfujino @gspencergoog Could you help me with dumping the tests log? I can't access to the tree's dashboard due to my network issues currently, or maybe a tracking issue. Thanks!

I will open a tracking issue and link from here
