### PR TITLE
Fix applyBoxFit's handling of fitWidth and fitHeight.

### LINKED ISSUE #117183: BoxDecoration doesn't respect repeatX/repeatY when fitWidth/fitHeight is used.
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Look at the screen

**Expected results:**

Since the [source image](https://docs.flutter.dev/assets/images/shared/brand/flutter/logo/flutter-lockup.png) has a wider aspect ratio than the `BoxDecoration`, and `fitWidth` is used in combination with `repeatY`, I would expect the image to be repeated vertically, like this:

image

**Actual results:**

Instead the image is drawn only once:

image

(Note that if `BoxFit.fitWidth` is changed to `BoxFit.contain`, then I get the expected behaviour in this example.  But `BoxFit.contain` only fits the width if the source image has a wider aspect ratio than the `BoxDecoration`; I want to fit the width regardless of the aspect ratios).

A similar problem exists between `fitHeight` and `repeatX` (though to see it you'll have to modify the aspect ratios in my example program).

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    FittedBox(
      child: Container(
        width: 100,
        height: 200,
        decoration: const BoxDecoration(
          color: Colors.white,
          image: DecorationImage(
            image: NetworkImage(
                'https://docs.flutter.dev/assets/images/shared/brand/flutter/logo/flutter-lockup.png'),
            fit: BoxFit.fitWidth,
            repeat: ImageRepeat.repeatY,
          ),
        ),
      ),
    ),
  );
}
```

</details>

### PR DESCRIPTION
**Pull request by stereotype441**
Previously, in `fitWidth` mode, if the input size had a wider aspect ratio than the output size, `applyBoxFit` would make the source rect taller than the input size in order to match the aspect ratio of the destination rect.  Similarly, in `fitHeight` mode, if the input size had a taller aspect ratio than the output size, `applyBoxFit` would make the source rect wider than the input size in to match the aspect ratio of the destination rect.  This is in contrast to all the other modes, which never output a source rect that's larger than the input size.

Most of the time this worked as intended (since attempting to blit pixels that are outside the source image has no effect), however it meant that if a user attempted to create a `BoxDecoration` that used both `fitWidth` and `repeatY` (e.g. in an attempt to tile a background image), the image would not actually appear to repeat, since the logic in `paintImage` for determining the proper tiling stride is based on the destination image size, meaning that the entire destination rect would be covered in a single tile.

This change modifies `applyBoxFit` so that in `fitWidth` mode, if the input size has a wider aspect ratio than the output size, it uses formulas that are equivalent to `contain`, whereas if the input size has a taller aspect ratio than the output size, it uses formulas that are equivalent to `cover`.  And vice versa for `fitHeight` mode.  This produces source and destination rects that match the behaviour specified in https://api.flutter.dev/flutter/painting/BoxFit.html.

Fixes #117183.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/painting/decoration_test.dart [hunk 1]
```diff
@@ -669,6 +669,86 @@ void main() {
     }
   });
 
+  test('paintImage with repeatX and fitHeight', () async {
+    final TestCanvas canvas = TestCanvas();
+
+    // paint a square image into an output rect that is twice as wide as it is
```
Comment (goderbauer) [inline packages/flutter/test/painting/decoration_test.dart:675]: nit: Sentences should start with a capital letter: paint -> Paint

File: packages/flutter/test/painting/decoration_test.dart [hunk 2]
```diff
@@ -669,6 +669,86 @@ void main() {
...
+      expect(call.positionalArguments[3], isA<Paint>());
+    }
+
+    expect(tileRects, <Rect>{const Rect.fromLTWH(30.0, 30.0, 200.0, 200.0), const Rect.fromLTWH(230.0, 30.0, 200.0, 200.0)});
+  });
+
+  test('paintImage with repeatY and fitWidth', () async {
+    final TestCanvas canvas = TestCanvas();
+
+    // paint a square image into an output rect that is twice as tall as it is
```
Comment (goderbauer) [inline packages/flutter/test/painting/decoration_test.dart:715]: same

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/painting/decoration_test.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/test/painting/decoration_test.dart:675]:
```suggestion
    // Paint a square image into an output rect that is twice as wide as it is
```

File: packages/flutter/test/painting/decoration_test.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/test/painting/decoration_test.dart:715]:
```suggestion
    // Paint a square image into an output rect that is twice as tall as it is
```
