### PR TITLE
Scroll CupertinoContextMenu if items overflow

### LINKED ISSUE #55025: Add CupertinoContextMenu scroll feature
## Use case

```dart
class CustomContextMenu extends StatelessWidget {
  final Widget child;
  final dynamic param;
  const CustomContextMenu({this.child, this.tour, this.param})
      : assert(child != null, tour != null);

  @override
  Widget build(BuildContext context) {
    Features _features =
        Features(context: context, param: param,);

    return CupertinoContextMenu(
      child: child,
      actions: <Widget>[
        CupertinoContextMenuAction(
          child: const Text('Option 1'),
          onPressed: () async => await _features.doThings1(),
        ),
        CupertinoContextMenuAction(
          child: const Text('Option 2'),
          onPressed: () async => await _features.doThings2(),
        ),
        CupertinoContextMenuAction(
          child: const Text('Option 3'),
          onPressed: () async => await _features.doThings3(),
        ),
        CupertinoContextMenuAction(
          child: const Text('Option 4'),
          onPressed: () async => await _features.doThings4(),
        )
      ],
    );
  }
}
```

image
## Proposal

At the moment there is no way to make `CupertinoContextMenu ()` scrollable and it is a big problem for me. I need to implement a lot of actions and, mostly on small screen device, I receive the overflow exception. Can scroll behaviour be implemented for this widget?

### LINKED ISSUE #154040: Allow for customization of mainAxisMargin in CupertinoScrollbar
### Use case

Needed for https://github.com/flutter/flutter/issues/55025 to correctly draw the scrollbar used in scrollable context menus.

This is what CupertinoScrollbar would look like:

https://github.com/user-attachments/assets/b3e31682-d2a9-4454-a3fd-edb85d0888b2

This is the native margin:

https://github.com/user-attachments/assets/4147116c-307d-4eb0-9587-e8045881aa73

### Proposal

Add property `mainAxisMargin` to `CupertinoScrollbar`.

### PR DESCRIPTION
**Pull request by victorsanni**
Fixes [Add CupertinoContextMenu scroll feature](https://github.com/flutter/flutter/issues/55025)
Fixes [Allow for customization of mainAxisMargin in CupertinoScrollbar](https://github.com/flutter/flutter/issues/154040)

### Native Context menu

https://github.com/user-attachments/assets/4ebed3e3-ab4f-4e94-8b47-e9c957f245ef

### Flutter iOS Context menu

https://github.com/user-attachments/assets/ad8426b4-ff18-40e1-9a4f-c61d7620b069

### Flutter macOS Context menu

https://github.com/user-attachments/assets/7374a8b2-ee8d-447b-9cd4-a7f2e7674fc2

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by victorsanni** [comment]
Blocked on https://github.com/flutter/flutter/issues/154040 to correctly set the margins of the scrollbar.

File: packages/flutter/lib/src/cupertino/context_menu.dart [hunk 1]
```diff
@@ -58,6 +59,11 @@ const Color _borderColor = CupertinoDynamicColor.withBrightness(
   darkColor: Color(0xFF57585A),
 );
 
+const Color _kBackgroundColor = CupertinoDynamicColor.withBrightness(
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/context_menu.dart:62]: This is also defined in CupertinoContextMenuAction: https://github.com/flutter/flutter/blob/418fa9d62610b6990f18c0a7cf6c194364fad4b8/packages/flutter/lib/src/cupertino/context_menu_action.dart#L50

How can we remove the duplicate/use one for both?

File: packages/flutter/lib/src/cupertino/context_menu.dart [hunk 2]
```diff
@@ -1382,8 +1388,13 @@ class _ContextMenuSheet extends StatelessWidget {
   final List<Widget> actions;
   final _ContextMenuLocation _contextMenuLocation;
   final Orientation _orientation;
+  // Link the scrollbar to the scrollview by providing them the same scroll
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/context_menu.dart:1391]:
```suggestion
  // Link the scrollbar to the scrollview by providing both the same scroll
```

File: packages/flutter/lib/src/cupertino/context_menu.dart [hunk 3]
```diff
@@ -1382,8 +1388,13 @@ class _ContextMenuSheet extends StatelessWidget {
...
+  // controller.
+  final ScrollController _controller = ScrollController();
```
Comment (navaronbracke) [inline packages/flutter/lib/src/cupertino/context_menu.dart:1393]: This scroll controller is not disposed?

Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/context_menu.dart:1393]: Thanks for the heads up.

Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/context_menu.dart:1393]: Wait actually @navaronbracke this class is a stateless widget, would we still need to dispose the controller, and if so, how?

File: packages/flutter/lib/src/cupertino/context_menu.dart (hunk 1 above)
Comment (MitchellGoodwin) [reply packages/flutter/lib/src/cupertino/context_menu.dart:62]: We should probably expose these in one, then use them in the other? As in CupertinoContextMenuAction can use `CupertinoContextMenu.kBackgroundColor`. The `actions` property is asking for any kind of widget, so providing these constants so somebody could make their own, slightly different CupertinoContextMenuAction that still uses some constants from us makes sense.

If it makes sense to either move these to the constants file or use an existing constant we can, but if the styling is specific to these widgets I think it's fine to leave them in these files. It improves specific discoverability in the API docs that way.

**Comment by victorsanni** [comment]
> Blocked on #154040 to correctly set the margins of the scrollbar.

Talking with @Piinks offline, it seems like the native margin is different in this case because of the border radius of the context menu. So it makes sense to expose `mainAxisMargin` in this PR so it can be customized for this use case.

File: packages/flutter/lib/src/cupertino/context_menu.dart (hunk 3 above)
Comment (navaronbracke) [reply packages/flutter/lib/src/cupertino/context_menu.dart:1393]: Hmm, in that case @polina-c what is the guidance here? Since the main reason why I asked if this could be done is for leak tracking purposes (otherwise we'll end up with tests that fail with leak tracking enabled?) Do we convert it to a stateful widget?

Comment (polina-c) [reply packages/flutter/lib/src/cupertino/context_menu.dart:1393]: Thanks!
Yes, if a controller is created by a widget, it should be stateful widget.

**Review by Piinks — COMMENTED** [review]
Oh my it looks as though I did not hit `submit` on my earlier comments. 😓  Sorry about that.

**Review by Piinks — APPROVED** [review]
Turns out they've all been addressed, so this LGTM! 🎊

**Review by MitchellGoodwin — APPROVED** [review]
LGTM!
