### PR TITLE
Fix a ModalbottomSheet bug

### LINKED ISSUE #99627: Back button in app bar doesn't go away, after multiple bottom sheet instances were opened without closing the previous one.
Same issue was reported in #36345

## Steps to Reproduce

1. Execute `flutter run` on the code sample, or run in dart pad. 
2. Tap `Show bottom sheet` button several times 
3. Close current bottom sheet via swipping it down, or pressing back button on app bar/phone. 

**Expected results:** 
Bottom sheet is closed. Back button on the app bar dissapears.

**Actual results:** 
Bottom sheet is closed. The back button on the appbar is still there, until you press it as many times as you opened bottom sheets.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter Demo'),
        ),
        body: const MyHomePage(),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void bottomSheet() {
    Scaffold.of(context).showBottomSheet((BuildContext context) {
      return const FractionallySizedBox(
        heightFactor: .2,
        child: Center(child: Text('This is a bottom sheet')),
      );
    }, backgroundColor: Colors.amber);
  }

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      child: const Text('Show bottom sheet'),
      onPressed: bottomSheet,
    );
  }
}

```
Dartpad: https://dartpad.dev/9fcec8e531d68534b1f71513fe876fba
</details>

<details>
  <summary>Logs</summary>

```
[  +53 ms] executing: [C:\Flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +220 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 7e9793dee1b85a243edd0e06cb1658e98b077561
[        ] executing: [C:\Flutter/] git tag --points-at 7e9793dee1b85a243edd0e06cb1658e98b077561
[  +23 ms] Exit code 0 from: git tag --points-at 7e9793dee1b85a243edd0e06cb1658e98b077561
[        ] 2.10.3
[   +5 ms] executing: [C:\Flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Flutter/] git ls-remote --get-url origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +77 ms] executing: [C:\Flutter/] git rev-parse --abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +53 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +47 ms] executing: C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +43 ms] List of devices attached
           7438aafc7ce6           device product:tiare_ru model:Redmi_Go device:tiare transport_id:2
[   +6 ms] C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7438aafc7ce6 shell getprop
[ +192 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +100 ms] Skipping pub get: version match.
[  +52 ms] Generating C:\Code\bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +59 ms] ro.hardware = qcom
[  +26 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +6 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: C:\Code\bug\.dart_tool\package_config_subset}
[  +20 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +1 ms] complete
[   +5 ms] Launching lib\main.dart on Redmi Go in debug mode...
[   +4 ms] C:\Flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\andyr\AppData\Local\Temp\flutter_tools.76e2a96f\flutter_tool.b1ae1b46\app.dill --packages C:\Code\bug\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[   +6 ms] executing: C:\Users\andyr\AppData\Local\Android\sdk\build-tools\32.1.0-rc1\aapt dump xmltree C:\Code\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +10 ms] Exit code 0 from: C:\Users\andyr\AppData\Local\Android\sdk\build-tools\32.1.0-rc1\aapt dump xmltree C:\Code\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=37)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=41)
                     E: action (line=42)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=44)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=51)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=55)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=58)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +4 ms] executing: C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7438aafc7ce6 shell -x logcat -v time -t 1
[  +14 ms] <- compile package:bug/main.dart
[ +249 ms] --------- beginning of main
           03-06 17:20:12.807 I/Finsky  ( 2705): [2] qpq.onStartJob(3): SCH: job service start with id 9870.
[   +8 ms] executing: C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +15 ms] Android Debug Bridge version 1.0.41
           Version 33.0.0-8141338
           Installed as C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +1 ms] executing: C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +16 ms] Building APK
[  +13 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] Using gradle from C:\Code\bug\android\gradlew.bat.
[  +10 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +90 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.11" 2021-04-20
           OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
           OpenJDK 64-Bit Server VM (build 11.0.11+9-b60-7590822, mixed mode)
[   +1 ms] executing: [C:\Code\bug\android/] C:\Code\bug\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm -Ptarget=C:\Code\bug\lib\main.dart -Pbase-application-name=android.app.Application -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1265 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[  +84 ms] > Task :app:mergeDebugAssets
[ +302 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[  +88 ms] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[ +107 ms] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:packageDebug UP-TO-DATE
[ +130 ms] > Task :app:assembleDebug
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 1s
[        ] 32 actionable tasks: 4 executed, 28 up-to-date
[ +526 ms] Running Gradle task 'assembleDebug'... (completed in 2 612ms)
[  +66 ms] calculateSha: LocalDirectory: 'C:\Code\bug\build\app\outputs\flutter-apk'/app.apk
[ +667 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +2 ms] executing: C:\Users\andyr\AppData\Local\Android\sdk\build-tools\32.1.0-rc1\aapt dump xmltree C:\Code\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +20 ms] Exit code 0 from: C:\Users\andyr\AppData\Local\Android\sdk\build-tools\32.1.0-rc1\aapt dump xmltree C:\Code\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=37)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=41)
                     E: action (line=42)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=44)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=51)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=55)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=58)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +1 ms] Stopping app 'app.apk' on Redmi Go.
[        ] executing: C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7438aafc7ce6 shell am force-stop com.example.bug
[ +140 ms] executing: C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7438aafc7ce6 shell pm list packages com.example.bug
[+1433 ms] Installing APK.
[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk...
[        ] executing: C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7438aafc7ce6 install -t -r C:\Code\bug\build\app\outputs\flutter-apk\app.apk
[+19510 ms] Performing Streamed Install
            Success
[        ] Installing build\app\outputs\flutter-apk\app.apk... (completed in 19,5s)
[   +1 ms] executing: C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7438aafc7ce6 shell echo -n f17c3ee9797af8741b34b76380c05513ad3ee95f > /data/local/tmp/sky.com.example.bug.sha1
[ +100 ms] executing: C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7438aafc7ce6 shell -x logcat -v time -t 1
[ +204 ms] --------- beginning of main
           03-06 17:20:37.641 D/CompatibilityInfo( 2218): applicationScale - 1.0
[   +5 ms] executing: C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7438aafc7ce6 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.bug/com.example.bug.MainActivity
[ +222 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.bug/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+6131 ms] Observatory URL on device: http://127.0.0.1:44266/9eGg2noktgM=/
[        ] executing: C:\Users\andyr\AppData\Local\Android\sdk\platform-tools\adb.exe -s 7438aafc7ce6 forward tcp:0 tcp:44266
[  +17 ms] 55499
[        ] Forwarded host port 55499 to device port 44266 for Observatory
[   +4 ms] Caching compiled dill
[  +24 ms] Connecting to service protocol: http://127.0.0.1:55499/9eGg2noktgM=/
[ +950 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:55499/9eGg2noktgM=/.
[+1164 ms] DDS is listening at http://127.0.0.1:55502/y2DtQ3Lqu3o=/.
[  +39 ms] Successfully connected to service protocol: http://127.0.0.1:55499/9eGg2noktgM=/
[ +365 ms] DevFS: Creating new filesystem on the device (null)
[  +15 ms] I/zygote  ( 3345): Do partial code cache collection, code=18KB, data=29KB
[  +18 ms] I/zygote  ( 3345): After code cache collection, code=18KB, data=29KB
[        ] I/zygote  ( 3345): Increasing code cache capacity to 128KB
[ +204 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.bug/code_cache/bugVLGZIR/bug/)
[   +1 ms] Updating assets
[  +68 ms] Syncing files to device Redmi Go...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:bug/main.dart 36342c1b-d4c8-454f-b871-7d92e4ca2c6a
[        ] <- 36342c1b-d4c8-454f-b871-7d92e4ca2c6a
[   +1 ms] Bundle processing done.
[  +68 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Redmi Go... (completed in 73ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +5 ms] Connected to _flutterView/0xb3107610.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload.
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ]  Running with sound null safety
[        ] An Observatory debugger and profiler on Redmi Go is available at: http://127.0.0.1:55502/y2DtQ3Lqu3o=/
[+6892 ms] The Flutter DevTools debugger and profiler on Redmi Go is available at: http://127.0.0.1:9104?uri=http://127.0.0.1:55502/y2DtQ3Lqu3o=/
[+5692 ms] I/zygote  ( 3345): Do partial code cache collection, code=62KB, data=45KB
[        ] I/zygote  ( 3345): After code cache collection, code=62KB, data=45KB
[        ] I/zygote  ( 3345): Increasing code cache capacity to 256KB
[+15486 ms] W/Adreno-ES20( 3345): <core_glFinish:34>: glFinish skipped: 0
[  +35 ms] W/Adreno-ES20( 3345): <core_glFinish:34>: glFinish skipped: 0
[   +2 ms] W/Adreno-ES20( 3345): <core_glFinish:34>: glFinish skipped: 0
[   +2 ms] W/Adreno-ES20( 3345): <core_glFinish:34>: glFinish skipped: 0
[ +107 ms] I/chatty  ( 3345): uid=10254(com.example.bug) RenderThread identical 1 line
[        ] W/Adreno-ES20( 3345): <core_glFinish:34>: glFinish skipped: 0
[+1070 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.bug/code_cache/bugVLGZIR/bug/)
[ +254 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[  +22 ms] "flutter run" took 64 614ms.
[ +178 ms] ensureAnalyticsSent: 176ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

```
Analyzing bug...
No issues found! (ran in 4.1s)
```

```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19042.1526], locale ru-RU)
    • Flutter version 2.10.3 at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\andyr\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (4 available)
    • Redmi Go (mobile) • 7438aafc7ce6 • android-arm    • Android 8.1.0 (API 27)
    • Windows (desktop) • windows      • windows-x64    • Microsoft Windows [Version 10.0.19042.1526]
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge         • web-javascript • Microsoft Edge 98.0.1108.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

https://user-images.githubusercontent.com/88431411/156923439-265449cd-57a9-41af-90c7-2e1fff276a50.mp4

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes https://github.com/flutter/flutter/issues/99627

Forget to remove the old route entry when popup a new sheet.

### CODE REVIEW

File: packages/flutter/lib/src/material/scaffold.dart [hunk 1]
```diff
@@ -2394,20 +2402,19 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
...
-        }
       },
       onDismissed: () {
         if (_dismissedBottomSheets.contains(bottomSheet)) {
           setState(() {
             _dismissedBottomSheets.remove(bottomSheet);
           });
         }
+        setState(() {
+          _currentBottomSheet = null;
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/scaffold.dart:2413]: We should remove the widget from the tree when dismissing the sheet by gesture, otherwise will be a small leaking.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 2]
```diff
@@ -2394,20 +2401,23 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
...
         }
+        if (_currentBottomSheet == null) {
+          return;
+        }
+        setState(() {
+          _currentBottomSheet = null;
+        });
       },
       onDispose: () {
+        _removeEntryIfNeeded();
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/scaffold.dart:2420]: `ShowBottomSheet` multiple times will only call `onDispose`, so this is a good time to remove the entry.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 3]
```diff
@@ -2385,6 +2384,14 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
           }
         });
 
+    void _removeEntryIfNeeded() {
+      if (!isPersistent && !removedEntry) {
+        assert(entry != null);
+        removedEntry = true;
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/scaffold.dart:2390]: Move this flag(`removedEntry`) forward so as not to trigger `LocalHistoryEntry.onRemove`, otherwise `_StandardBottomSheet.onClosing` will be triggered twice when using the gesture remove the sheet, which is strange behavior.

**Comment by xu-baolin** [comment]
I just filed a new issue https://github.com/flutter/flutter/issues/100047, which has nothing to do with this change, and the trunk branch can be reproduced.

**Review by Piinks — APPROVED** [review]
Nice! Thank you for fixing!
