### PR TITLE
Fix flaky peer connection

### LINKED ISSUE #36091: mac8 stuck in flutter driver tests every time
We setup mac8 to be our new Mac mini (2018) with iPhone XS. It's intended to do performance benchmarks for issues like https://github.com/flutter/flutter/issues/31086. However, all our `tiles_scroll_perf_iphonexs__timeline_summary` driver test runs have been timed out: https://flutter-dashboard.appspot.com/build.html

During local tests, such timing out not only happens with iPhone XS, but also with iPhone 6 and other driver tests like flutter_gallery transition, as long as it's running on our new mac8, a Mac mini (2018). The same device and driver test won't trigger the time out on my Mac Book Pro.

@rmacnak-google and I tracked the issue down to the web socket connection.

### PR DESCRIPTION
**Pull request by liyuqian**
Fixes https://github.com/flutter/flutter/issues/36091

Previously, a sendRequest will be sent even if the peer is closed during
a driver test. That will cause a time out without any error information.
Such issue is unreproducible on my Mac Book Pro, but 100% reproducible
on our new Mac mini (2018).

Additional to this fix, we should also patch the jason_rpc_2 so the peer
will throw exception if sendRequest is attempted while the connection is
closed.

**Test**:
tiles_scroll_perf_iphonexs__timeline_summary failed without this patch.
It will pass after this patch.

I'm not sure how to add a unit test for this. Please let me know if you have
some ideas.

This patch will generate the following warning log on the new Mac Mini
```
flutter: Observatory listening on http://127.0.0.1:50192/cZPDF4sW7MM=/  
Installing and launching...                                        10.2s
00:00 +0: scrolling performance test (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:1069/cZPDF4sW7MM=/
[trace] FlutterDriver: Isolate found with number: 3684677742843303
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:00 +0: scrolling performance test complex_layout_scroll_perf
[warning] FlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
[warning] FlutterDriver: Peer connection is closed! Trying to restore the connection...
00:10 +1: scrolling performance test tiles_scroll_perf
[warning] FlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
[warning] FlutterDriver: Peer connection is closed! Trying to restore the connection...
00:20 +2: scrolling performance test (tearDownAll)
00:20 +2: All tests passed!
Stopping application instance.
```

### CODE REVIEW

File: packages/flutter_driver/lib/src/driver/driver.dart [hunk 1]
```diff
@@ -392,7 +394,21 @@ class FlutterDriver {
...
+  rpc.Peer _peer;
+
+  String _dartVmReconnectUrl;
+
+  Future<void> _restorePeerConnectionIfNeeded() async {
+    if (!_peer.isClosed || _dartVmReconnectUrl == null) {
+      return;
+    }
+
+    _log.warning('Peer connection is closed! Try to restore the connection...');
```
Comment (dnfield) [inline packages/flutter_driver/lib/src/driver/driver.dart]: Is this meant to be `Trying to restore the connection...`?

**Comment by dnfield** [comment]
This seems to make sense- can we get a test for it?

**Comment by jonahwilliams** [comment]
Do we understand why we're losing a vmservice connection? Is this also potentially affecting hot reload as well?

cc @zanderso

File: packages/flutter_driver/lib/src/driver/driver.dart (hunk 1 above)
Comment (liyuqian) [reply packages/flutter_driver/lib/src/driver/driver.dart]: Done.

**Comment by liyuqian** [comment]
@dnfield : I'd love to add a test. I just don't know how to trigger or emulate an unexpected web socket closing. Any suggestion on that, @rmacnak-google ?

@jonahwilliams : so far, no. Someone must have silently closed the connection without emitting any error messages. @rmacnak-google gave me a patch https://gist.github.com/rmacnak-google/11463f7f8ca076265a0463dd10cc7549 which unfortunately still doesn't generate any error messages.

**Comment by rmacnak-google** [comment]
Maybe the rpc.Peer should be completing outstanding requests with an exception when the underlying socket closes?

**Comment by liyuqian** [comment]
Yes, @rmacnak-google . Can such exception be added to https://github.com/dart-lang/json_rpc_2/blob/master/lib/src/peer.dart#L78 ?

**Comment by liyuqian** [comment]
Ping... It would be nice if we can fix the iPhone XS soon so the mac8 will no longer be red.

**Review by dnfield — APPROVED** [review]
LGTM - but we should figure out why the connection is getting reset

File: packages/flutter_driver/lib/src/driver/driver.dart [hunk 2]
```diff
@@ -392,7 +394,27 @@ class FlutterDriver {
...
+      return;
+    }
+
+    _log.warning(
+        'Peer connection is closed! Trying to restore the connection...'
+    );
+
+    final String webSocketUrl = _getWebSocketUrl(_dartVmReconnectUrl);
+    final WebSocket ws = await WebSocket.connect(webSocketUrl);
+    ws.done.then((dynamic _) => _checkCloseCode(ws));
```
Comment (zanderso) [inline packages/flutter_driver/lib/src/driver/driver.dart]: use `whenComplete` here instead of `then`

File: packages/flutter_driver/lib/src/driver/driver.dart [hunk 3]
```diff
@@ -1096,16 +1117,36 @@ Future<VMServiceClientConnection> _waitAndConnect(String url) async {
...
   while (true) {
     WebSocket ws1;
     WebSocket ws2;
     try {
-      ws1 = await WebSocket.connect(uri.toString());
-      ws2 = await WebSocket.connect(uri.toString());
+      ws1 = await WebSocket.connect(webSocketUrl);
+      ws2 = await WebSocket.connect(webSocketUrl);
+
+      ws1.done.then((dynamic _) => _checkCloseCode(ws1));
```
Comment (zanderso) [inline packages/flutter_driver/lib/src/driver/driver.dart]: ditto

**Comment by liyuqian** [comment]
Filed https://github.com/flutter/flutter/issues/36268 to track the web socket issue.

**Comment by liyuqian** [comment]
@zanderso : oops, the Github didn't load your comment until I merged the PR. I opened another PR to address your comment: https://github.com/flutter/flutter/pull/36270

**Comment by zanderso** [comment]
Also a heads up that this was landed on red.

**Comment by liyuqian** [comment]
Seems to be flaky tests. They all turned green for this commit.
