### PR TITLE
Fallback to protocol discovery if mdns returns null

### LINKED ISSUE #45468: mdns attach is broken on latest master
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color attach --machine --device-id=1b6eae756ec0f26f3134b3d0c03f7932a8be1a61 lib/main.dart

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      VMService._connect (package:flutter_tools/src/vmservice.dart:325:80)
#2      VMService.connect (package:flutter_tools/src/vmservice.dart:315:21)
#3      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:175:35)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#9      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:20)
#10     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:252:5)
#11     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:476:11)
#12     _rootRunUnary (dart:async/zone.dart:1138:13)
#13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#17     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#18     _StreamController._add (dart:async/stream_controller.dart:642:7)
#19     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:174:18)
#20     _rootRunUnary (dart:async/zone.dart:1134:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#28     MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart)
<asynchronous suspension>
#29     AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:238:47)
<asynchronous suspension>
#30     AttachCommand.runCommand.<anonymous closure> (package:flutter_tools/src/commands/attach.dart:177:19)
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1465:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#37     AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:176:19)
<asynchronous suspension>
#38     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#39     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#40     _rootRunUnary (dart:async/zone.dart:1134:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#42     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#44     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#45     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#46     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#47     _rootRun (dart:async/zone.dart:1126:13)
#48     _CustomZone.run (dart:async/zone.dart:1023:19)
#49     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#50     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#51     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#52     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#53     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.12.11-pre.8, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.12.11-pre.8 at /Users/apple/Library/flutter
    • Framework revision f40dbf8ca0 (10 hours ago), 2019-11-23 01:02:54 -0500
    • Engine revision d1cac77d5a
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 40.2.3
    • Dart plugin version 192.7359

[✓] Connected device (2 available)
    • “apple”的 iPhone • 1b6eae756ec0f26f3134b3d0c03f7932a8be1a61 • ios • iOS 12.4.2
    • iPhone 8        • D2483163-94BA-4A1C-9EB8-26964C81824C     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by blasten**
## Description

Addresses the comment on https://github.com/flutter/flutter/pull/44637#pullrequestreview-321634273

Fixes https://github.com/flutter/flutter/issues/45468

## Tests

I added the following tests: Unit test

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Fixes https://github.com/flutter/flutter/issues/45468 ?

File: packages/flutter_tools/lib/src/commands/attach.dart [hunk 1]
```diff
@@ -233,15 +233,16 @@ class AttachCommand extends FlutterCommand {
...
-            )
-          ).asBroadcastStream();
+        final Uri uriFromMdns =
+          await MDnsObservatoryDiscovery.instance.getObservatoryUri(
+            appId,
+            device,
+            usesIpv6: usesIpv6,
+            deviceVmservicePort: deviceVmservicePort,
+          );
+        observatoryUri = uriFromMdns == null
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/attach.dart]: Instead of settings this to null with a ternary, set it conditionally:

```
if (uriFromMdns != null) {
  observatoryUri = Stream<Uri>.value(uriFromMdns).asBroadcastStream();
}
```

**Comment by jonahwilliams** [comment]
The failure if from my rolled back change, if you sync it should work

File: packages/flutter_tools/lib/src/commands/attach.dart (hunk 1 above)
Comment (blasten) [reply packages/flutter_tools/lib/src/commands/attach.dart]: I think being explicit about this value being null at this point is perhaps more readable than assuming it’s already null at this point. Wdyt?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/attach.dart]: SGTM

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by zanderso — APPROVED** [review]
lgtm.
