### PR TITLE
Fix FlexibleSpaceBar Opacity when AppBar.toolbarHeight > ktoolbarHeight

### LINKED ISSUE #80451: FlexibleSpaceBar incompatible when AppBar.toolbarHeight is larger than ktoolbarHeight
The `AppBar` supports `flexibleSpace` - even though it doe not actually collapse unless animated or otherwise manually.
However, the `Opacity` calculation for the `FlexibleSpaceBar.background` dow not account for the AppBar using a different `toolbarHeight`. 
For example, this computes an opacity of 0 for the background, resulting in nothing being painted:

```dart
MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            toolbarHeight: 300,
            flexibleSpace: const FlexibleSpaceBar(
              title: Text('Title'),
              // Invisible and how! :)
              background:  Text('Background'),
              collapseMode: CollapseMode.pin,
            ),
          ),
          body: CustomScrollView(
            primary: true,
            slivers: <Widget>[
              SliverToBoxAdapter(
                child: Container(
                  height: 1200.0,
                  color: Colors.orange[400],
                ),
              ),
            ],
          ),
        ),
      ),
```

### PR DESCRIPTION
**Pull request by Piinks**
This fixes a miscalculation in the opacity of the background of the FlexibleSpaceBar widget when used in an AppBar that has a height greater than ktoolbarHeight.

Fixes https://github.com/flutter/flutter/issues/80451

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/flexible_space_bar.dart [hunk 1]
```diff
@@ -305,7 +305,11 @@ class _FlexibleSpaceBarState extends State<FlexibleSpaceBar> {
           final double fadeStart = math.max(0.0, 1.0 - kToolbarHeight / deltaExtent);
           const double fadeEnd = 1.0;
           assert(fadeStart <= fadeEnd);
-          final double opacity = 1.0 - Interval(fadeStart, fadeEnd).transform(t);
+          // If the min and max extent are the same, the app bar cannot collapse
+          // and the content should be visible, so opacity = 1
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/flexible_space_bar.dart:309]:
```suggestion
          // and the content should be visible, so opacity = 1.
```

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d
