### PR TITLE
fix: add parameter to maintainState of SearchDelegate

### LINKED ISSUE #43582: keep state inside SearchDelegate
I have  FutureBuilder>>ListView widgets  Inside **@override buildResults(BuildContext context)** method. I navigate to a new screen on list view item tap. but when i pop from the new screen the future is called again. Also i have pagination in the main list view, so when the user tap on item 100 for ex. after popping from the new screen, the main listview it will  rebuild from the beginning

```
class DataSearch extends SearchDelegate<String>{
  
  @override
  List<Widget> buildActions(BuildContext context) {
    return [
      IconButton(
          icon: Icon(Icons.clear),
          onPressed: () {
            query = '';
          })
    ];
  }

  @override
  ThemeData appBarTheme(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    return theme.copyWith(
        inputDecorationTheme: InputDecorationTheme(
            hintStyle: TextStyle(color: theme.primaryTextTheme.title.color)),
        primaryColor: theme.primaryColor,
        primaryIconTheme: theme.primaryIconTheme,
        primaryColorBrightness: theme.primaryColorBrightness,
        primaryTextTheme: theme.primaryTextTheme,
        textTheme: theme.textTheme.copyWith(
            title: theme.textTheme.title
                .copyWith(color: theme.primaryTextTheme.title.color)));
  }

  @override
  Widget buildLeading(BuildContext context) {
    return IconButton(
        icon: AnimatedIcon(
            icon: AnimatedIcons.menu_arrow, progress: transitionAnimation),
        onPressed: () {
          close(context, null);
        });
  }

  @override
  Widget buildResults(BuildContext context) {
     SearchProvider searchProvider =
        Provider.of<SearchProvider>(context, listen: false);

    return query.isEmpty == true ? Container() : FutureBuilder(
        future:  searchProvider.fetchData(query),
        builder: (context, snapshot) {
          switch (snapshot.connectionState) {
            case ConnectionState.waiting:
              return Center(
                  child: SpinKitHourGlass(
                color: Colors.greenAccent,
              ));
              break;
            default:
              if (snapshot.hasError) {
                return Center(child: Text("Error: ${snapshot.error}"));
              } else {
                return Consumer<SearchProvider>(
                  builder: (context, provider, child) => ImageList(
                    models: snapshot.data,
                    isSearch: true,
                  ),
                );
              }
          }
        });
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    return Container();
  }
}
```

### PR DESCRIPTION
**Pull request by gazal-k**
Add parameter to `showSearch`, which is passed to `_SearchPageRoute` to maintain the state of the SearchDelegate.

- fix #43582

_Just contributed this change to start the conversation on how the #43582 can be addressed. Have not added tests yet._

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/search.dart [hunk 1]
```diff
@@ -68,11 +68,13 @@ Future<T?> showSearch<T>({
   required SearchDelegate<T> delegate,
   String? query = '',
   bool useRootNavigator = false,
+  bool maintainState = false,
 }) {
   delegate.query = query ?? delegate.query;
   delegate._currentBody = _SearchBody.suggestions;
   return Navigator.of(context, rootNavigator: useRootNavigator).push(_SearchPageRoute<T>(
     delegate: delegate,
+    maintainStateOverride: maintainState,
```
Comment (navaronbracke) [inline packages/flutter/lib/src/material/search.dart:77]: Instead of calling the new property `maintainStateOverride`, why not have the property annotated with an override annotation?

dart```
class _SearchPageRoute<T> extends PageRoute<T> {

// ...

@override
final bool maintainState;

// ...
```

Comment (gazal-k) [reply packages/flutter/lib/src/material/search.dart]: Thank you for that tip.

I'm not very familiar with dart tests 😞, figuring out how to write a test for this.

**Comment by dkwingsmt** [comment]
@goderbauer Can you take a brief look and see if this is something we want to add?

File: packages/flutter/test/material/search_test.dart [hunk 2]
```diff
@@ -1175,6 +1175,54 @@ void main() {
...
+                        await showSearch(context: context, delegate: delegate);
+                      },
+                      child: const Text('showSearch')),
+                  TextButton(
+                      onPressed: () async {
+                        await showSearch(context: context, delegate: delegate, maintainState: true);
+                      },
+                      child: const Text('showSearchWithMaintainState')),
+                ],
+              )),
```
Comment (goderbauer) [inline packages/flutter/test/material/search_test.dart:1201]: format nit:

```suggestion
      home: Builder(builder: (BuildContext context) => Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          TextButton(
            onPressed: () async {
              await showSearch(
                context: context,
                delegate: delegate,
              );
            },
            child: const Text('showSearch'),
          ),
          TextButton(
            onPressed: () async {
              await showSearch(
                context: context,
                delegate: delegate,
                maintainState: true,
              );
            },
            child: const Text('showSearchWithMaintainState'),
          ),
        ],
      ),
```

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/search.dart [hunk 3]
```diff
@@ -48,6 +48,9 @@ import 'theme.dart';
 /// route created by this method is pushed to the nearest navigator to the
 /// given `context`. It can not be `null`.
 ///
+/// The `maintainState` argument is used to determine if the route should remain
+/// in memory when it is inactive. By default, `maintainState` is `false`.
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/search.dart:52]: Shall we refer to the original doc for more information? 
```suggestion
/// The `maintainState` argument is used to determine if the route should remain
/// in memory when it is inactive (see [ModalRoute.maintainState] for more details].
/// By default, `maintainState` is `false`.
```

Also, do you think it's possible to provide examples on how this might be useful?

**Review by dkwingsmt — APPROVED** [review]
LGTM after addressing the feedbacks
