### PR TITLE
Fixes an issue where onTapOutside was incorrectly triggered across routes in TapRegion

### LINKED ISSUE #153093: TapRegion will fire callback on other navigation's stack
Issue's explanation is that. 
if we have TapRegion on our PageA and then we push to other PageB then we continue getting callback on TapRegion's onTapOutside when we make any contact with device's screen on PageB.

### Steps to reproduce

1. just run the following code
2. open the terminal
3. see the print from the onTapOutside of TapRegion of both Pages in the terminal

### Expected results

EditPageElement not leak

we have to not see the print from one of the TapRegion callbacks because they are in different Pages. 
when we open first page we click outside the red container we see the print from the onTapOutside of TapRegion. And ther we click onto FloatingActionButton to navigate to other page. There we have another TapRegion which works the same. And here we see the terminal that we are getting callback twice. One from the first page since that has to be disposed. 

### Actual results

EditPageElement leaked

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text('Home'),
      ),
      body: Center(
        child: TapRegion(
          onTapOutside: (event) {
            print('From The First Page: $event');
          },
          child: Container(
            width: 100,
            height: 100,
            color: Colors.red,
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.push(context, MaterialPageRoute(builder: (context) => const EditPage()));
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}

class EditPage extends StatelessWidget {
  const EditPage({super.key});

  @override
  StatelessElement createElement() => EditPageElement(this);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('EditPage')),
      body: Center(
        child: TapRegion(
          onTapOutside: (event) {
            print('From The Second Page: $event');
          },
          child: Container(
            width: 100,
            height: 100,
            color: Colors.red,
          ),
        ),
      ),
    );
  }
}

class EditPageElement extends StatelessElement {
  EditPageElement(super.widget);
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
From The First Page: _TransformedPointerDownEvent#92e5a(position: Offset(351.2, 276.2))
From The Second Page: _TransformedPointerDownEvent#83e76(position: Offset(136.1, 173.5))
From The First Page: _TransformedPointerDownEvent#fd16b(position: Offset(134.3, 188.6))
From The Second Page: _TransformedPointerDownEvent#fd16b(position: Offset(134.3, 188.6))
From The First Page: _TransformedPointerDownEvent#5df0f(position: Offset(16.1, 22.0))
From The Second Page: _TransformedPointerDownEvent#5df0f(position: Offset(16.1, 22.0))
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
➜  ~ flutter doctor                   

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 13.2.1 22D68 darwin-x64, locale
    en-TJ)
[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0-rc2)
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.0)
[!] Connected device
    ! No devices available
[✓] Network resources```

</details>

### PR DESCRIPTION
**Pull request by Mairramer**
Fixes https://github.com/flutter/flutter/issues/153093

This PR fixes the issue of onTapOutside being triggered on other routes incorrectly.
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/app.dart [hunk 1]
```diff
@@ -1703,7 +1703,11 @@ class _WidgetsAppState extends State<WidgetsApp> with WidgetsBindingObserver {
               return widget.onGenerateInitialRoutes!(initialRouteName);
             },
           onUnknownRoute: _onUnknownRoute,
-          observers: widget.navigatorObservers!,
+          observers: <NavigatorObserver>[
+            TapRegionNavigatorObserver(),
+            if (widget.navigatorObservers != null)
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/app.dart:1708]:
```suggestion
...?widget.navigatorObservers,
```

File: packages/flutter/lib/src/widgets/tap_region.dart [hunk 2]
```diff
@@ -139,6 +147,74 @@ class TapRegionSurface extends SingleChildRenderObjectWidget {
...
+///
+/// This observer is used by the [TapRegionSurface] to clear the registered tap
+/// regions when a new route is pushed, and to re-register the tap regions when
+/// a route is popped.
+class TapRegionNavigatorObserver extends NavigatorObserver {
+  /// Creates a [TapRegionNavigatorObserver].
+  TapRegionNavigatorObserver();
+
+  @override
+  void didPush(Route<dynamic> route, Route<dynamic>? previousRoute) {
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/tap_region.dart:161]: Prefer using `Object?` instead of `dynamic`

File: packages/flutter/lib/src/widgets/tap_region.dart [hunk 3]
```diff
@@ -139,6 +147,74 @@ class TapRegionSurface extends SingleChildRenderObjectWidget {
...
+        registry.registerTapRegion(region);
+      }
+    }
+  }
+
+  List<RenderTapRegion> _findTapRegionsInElementTree(BuildContext context) {
+    final List<RenderTapRegion> regions = <RenderTapRegion>[];
+
+    void visitor(Element element) {
+      if (element.renderObject.runtimeType == RenderTapRegion) {
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/tap_region.dart:207]: Don't use `==` to check for types. Also, since this is a member field of the element, you can use an if-case to grab the variable and bind it directly to a local var for the check.

```suggestion
      if (element.renderObject case final RenderTapRegion region) {
         regions.add(region);
      }
```

File: packages/flutter/test/widgets/tap_region_test.dart [hunk 4]
```diff
@@ -1053,4 +1053,101 @@ void main() {
...
+    expect(count2, 0);
+
+    await tester.tap(find.byType(FloatingActionButton));
+    await tester.pumpAndSettle();
+
+    // Tap outside the second TapRegion to trigger onTapOutside
+    await tapOutside(tester, find.byKey(tapRegion2Key), times: 10);
+    expect(count1, 2); // When the Fab is pressed, the first TapRegion is still active.
+    expect(count2, 10);
+
```
Comment (navaronbracke) [inline packages/flutter/test/widgets/tap_region_test.dart:1130]: There are some extra blank lines here.

File: packages/flutter/test/widgets/tap_region_test.dart [hunk 5]
```diff
@@ -1053,4 +1053,101 @@ void main() {
...
+    await tester.pumpAndSettle();
+
+    // Tap outside the first TapRegion to trigger onTapOutside
+    await tapOutside(tester, find.byKey(tapRegion1Key));
+    expect(count1, 3);
+    expect(count2, 10);
+  });
+}
+
+Future<void> tapOutside(WidgetTester tester, Finder regionFinder, {int times = 1}) async {
```
Comment (navaronbracke) [inline packages/flutter/test/widgets/tap_region_test.dart:1144]: Why do we need to tap N times here? Isn't just tapping once or twice enough?

Comment (Mairramer) [reply packages/flutter/test/widgets/tap_region_test.dart]: I can remove it. It was originally added for an initial test, but I kept it without much consideration.

File: packages/flutter/lib/src/widgets/tap_region.dart [hunk 6]
```diff
@@ -139,6 +147,74 @@ class TapRegionSurface extends SingleChildRenderObjectWidget {
...
+      if (registry != null) {
+        SchedulerBinding.instance.addPostFrameCallback((_) {
+          _registerTapRegions(previousRoute, registry);
+        });
+      }
+    }
+  }
+
+  TapRegionRegistry? _getRegistry(Route<Object?> route) {
+    final NavigatorState? navigator = route.navigator;
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/tap_region.dart:181]: Maybe to stay consistent we also use 

```
    final BuildContext? context = route.navigator?.context;
    if (context == null) {
      return;
    }
```

like in _registerTapRegions ?

**Review by nate-thegrate — COMMENTED** [review]
I'm super impressed with this contribution—it doesn't seem like many people have knowledge & experience with `NavigatorObserver` and other route/navigation-related APIs.

Case-in-point: when Dart was migrated to sound null safety, nearly every nullable `.of(context)` method was changed to `.maybeOf(context)`, but it looks like [`ModalRoute.of(context)`](https://main-api.flutter.dev/flutter/widgets/ModalRoute/of.html) never got updated.

My main concern with this PR is that perhaps a developer would want their `onTapOutside()` to always trigger, or trigger when a non-fullscreen route is pushed, or not trigger at all if it isn't part of the topmost route; having the **TapRegionNavigatorObserver** baked into the WidgetsApp `build()` method wouldn't provide that flexibility.

<br><br>

I really appreciate the time you took to read that ["zero rebuilds" design doc](https://flutter.dev/go/zero-rebuilds) 😄

I'll be putting up a PR soon that will allow `RenderObjectWidget`s to respond to dependency updates. This would make it possible to have something like:

```dart
class TapRegion extends SingleChildRenderObjectWidget {
  // ...

  @override
  void updateRenderObject(BuildContext context, RenderTapRegion renderObject) {
    final ModalRoute<Object?>? route = ModalRoute.of(context);
    if (route != null) {
      renderObject.onTapOutside = route.isCurrent ? onTapOutside : null;
    }
  }
}
```

And then we might be able to add a flag or enum to `TapRegion` so the developer can choose whether it's disabled when the enclosing route is no longer the current one.

Interested to hear your thoughts on this!

**Comment by Mairramer** [comment]
> My main concern with this PR is that perhaps a developer would want their `onTapOutside()` to always trigger, or trigger when a non-fullscreen route is pushed, or not trigger at all if it isn't part of the topmost route; having the **TapRegionNavigatorObserver** baked into the WidgetsApp `build()` method wouldn't provide that flexibility.
> 
I've thought about this before and concluded that while it's a good solution for our current needs, it's not the best. I'm getting more into Flutter and so I sometimes consider more conventional approaches.

> I'll be putting up a PR soon that will allow `RenderObjectWidget`s to respond to dependency updates.
> 
I've been looking forward to this for quite some time now.
> 
> And then we might be able to add a flag or enum to `TapRegion` so the developer can choose whether it's disabled when the enclosing route is no longer the current one.
> 
Once this change is implemented, we can proceed in this manner. I have tried something similar in the past, but since there were no dependency updates to the RenderObjectWidget as you mentioned, the code ended up being less flexible. I think we can wait to approach this in a more efficient way.

I would like to emphasize once again that I am still deepening my understanding of how Flutter works and as a result I am not yet able to foresee all the future implications, but I am excited to learn more.

**Comment by jaybe78** [comment]
thanks @Mairramer. Will that be release anytime soon ?

**Comment by Mairramer** [comment]
> thanks @Mairramer. Will that be release anytime soon ?

This depends on the team approving this change.

**Comment by jaybe78** [comment]
> > thanks @Mairramer. Will that be release anytime soon ?
> 
> This depends on the team approving this change.

@Mairramer 
I tried to use your changes  in my project which uses GoRouter with shell routes but could not make it work so far.
The problem is that GoRouter does not fire the push() pop() function in the observers.
We could say it's a Go Router issue though I wonder whether your solution would work across all scenarios and different implementations.

**Comment by Mairramer** [comment]
> > > thanks @Mairramer. Will that be release anytime soon ?
> > 
> > 
> > This depends on the team approving this change.
> 
> @Mairramer I tried to use your changes in my project which uses GoRouter with shell routes but could not make it work so far. [The problem is that GoRouter does not fire the push() pop() function in the observers. ](https://github.com/flutter/flutter/issues/112196) We could say it's a Go Router issue though I wonder whether your solution would work across all scenarios and different implementations.

Is it possible to use `GoRouter(observers: [TapRegionNavigatorObserver()] ` ?

**Comment by Mairramer** [comment]
> > > > > thanks @Mairramer. Will that be release anytime soon ?
> > > > 
> > > > 
> > > > This depends on the team approving this change.
> > > 
> > > 
> > > @Mairramer I tried to use your changes in my project which uses GoRouter with shell routes but could not make it work so far. [The problem is that GoRouter does not fire the push() pop() function in the observers. ](https://github.com/flutter/flutter/issues/112196) We could say it's a Go Router issue though I wonder whether your solution would work across all scenarios and different implementations.
> > 
> > 
> > Is it possible to use `GoRouter(observers: [TapRegionNavigatorObserver()] ` ? I can review it later.
> 
> no it does not work (at least for me). The pop() is not getting trigger in ShellRoutes.
> 
> I put your code in `redirect` which is more or less the same because it's triggered when there's a change of url, but that did not work either.

I'll review this later, but I believe it will be resolved when we do it directly through the RenderObjectWidget.

**Comment by jaybe78** [comment]
> > > > > > thanks @Mairramer. Will that be release anytime soon ?
> > > > > 
> > > > > 
> > > > > This depends on the team approving this change.
> > > > 
> > > > 
> > > > @Mairramer I tried to use your changes in my project which uses GoRouter with shell routes but could not make it work so far. [The problem is that GoRouter does not fire the push() pop() function in the observers. ](https://github.com/flutter/flutter/issues/112196) We could say it's a Go Router issue though I wonder whether your solution would work across all scenarios and different implementations.
> > > 
> > > 
> > > Is it possible to use `GoRouter(observers: [TapRegionNavigatorObserver()] ` ? I can review it later.
> > 
> > 
> > no it does not work (at least for me). The pop() is not getting trigger in ShellRoutes.
> > I put your code in `redirect` which is more or less the same because it's triggered when there's a change of url, but that did not work either.
> 
> I'll review this later, but I believe it will be resolved when we do it directly through the RenderObjectWidget.


The other thing that I see is that when I switch StatefulShellBranch  using `GoRouter.go()`, getting the list of TapRegion for the current page also returns TapRegion that were rendered on the previous page.
I'm not sure but I think it has to do with the fact that there's no rebuilt of the screen when using StatefulShellBranch.
I hope this PR will solve that as well.

**Comment by jaybe78** [comment]
ok for those of you struggling with this I found a workaround which should be ok (at least for me) until we get a fix released.

After digging a bit more, it seems that the `TapRegionSurface` located in the app root is not keeping up to date correctly the registry, so what I did is that I created a CustomTapRegionSurface with more or less the same implementation and used multiple `CustomTapRegionSurface` in key places where my app gets re-rendered, so that when an update occurs like during a GoRouter.go(), the CustomTapRegionSurface gets re-rendered as well and therefore correctly adds/removes the TapRegion from the registry, so that it's always up to date with the current route.

Bearing in mind, I have a common layout with shared header and only the body changing, I just had to add CustomTapRegionSurface in 2 places (header and body) and that works for now 🤞.

Probably not the best but since it's a blocker for me, it's the only viable solution I could come up with for now.

Cheers

File: packages/flutter/lib/src/widgets/app.dart [hunk 7]
```diff
@@ -1703,7 +1703,10 @@ class _WidgetsAppState extends State<WidgetsApp> with WidgetsBindingObserver {
               return widget.onGenerateInitialRoutes!(initialRouteName);
             },
           onUnknownRoute: _onUnknownRoute,
-          observers: widget.navigatorObservers!,
+          observers: <NavigatorObserver>[
+            TapRegionNavigatorObserver(),
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/app.dart:1707]: this is not good, if may broke for nested navigator. I think we may need to a way to mute TapRegion underneath the active route without using navigator observer. I can think of two ways.
1. TapRegion awares of ModalRoute.isActive and register/unregister itself
2. A new widget to hide TapRegionRegistry in the subtree, and then ModalRoute or Overlay use that to hide TapRegionRegistry for not opaque

**Comment by nate-thegrate** [comment]
After an enormous overhaul of the `RenderObject` class, we were finally able to get the issue resolved:

- https://github.com/flutter/flutter/issues/155852

<br>

@Mairramer feel free to go ahead with pulling `TapRegion` data from the `BuildContext`!

File: packages/flutter/test/widgets/tap_region_test.dart [hunk 8]
```diff
@@ -1053,4 +1053,97 @@ void main() {
...
+    Widget buildPage(Widget body, {FloatingActionButton? fab}) {
+      return Scaffold(
+        appBar: AppBar(
+          backgroundColor: Colors.blue,
+          title: const Text('Test Page'),
+        ),
+        body: Center(child: body),
+        floatingActionButton: fab,
+      );
+    }
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/tap_region_test.dart:1097]: We might want to switch up the `fab` parameter here, based on the [**Avoid abbreviations**](https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-abbreviations) rule.

Perhaps this test will still work as intended without the `AppBar`, and if so, the page might be simple enough that it doesn't really need a helper method.

File: packages/flutter/test/widgets/tap_region_test.dart [hunk 9]
```diff
@@ -1053,4 +1053,97 @@ void main() {
...
+
+    await tester.pumpWidget(
+      MaterialApp(
+        home: buildPage(
+          tapRegion1,
+          fab: FloatingActionButton(
+            onPressed: () {
+              Navigator.push(
+                tester.element(find.byType(FloatingActionButton)),
+                MaterialPageRoute<Widget>(builder: (BuildContext context) => buildPage(tapRegion2)),
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/tap_region_test.dart:1107]: nit: void out the type argument

```suggestion
                MaterialPageRoute<void>(builder: (BuildContext context) => buildPage(tapRegion2)),
```

<br>

Depending on whether you decide to keep the `buildPage` method, it could be:

```suggestion
                MaterialPageRoute<void>(
                  builder: (BuildContext context) => Scaffold(
                    body: Center(child: tapRegion2),
                  ),
                ),
```

Comment (nate-thegrate) [reply packages/flutter/test/widgets/tap_region_test.dart:1107]: If you're interested in what the route's type argument is used for: it's to allow a "pop with result".
For example, you could show a dialog with yes/no buttons, and one of them could do `Navigator.pop(context, true)` and the other could do `Navigator.pop(context, false)`.

Then you'd use it like so:

```dart
final bool? result = await showDialog<bool>(
  context: context,
  builder: (context) => const YesNoDialog(),
);
```

File: packages/flutter/test/widgets/tap_region_test.dart [hunk 10]
```diff
@@ -1053,4 +1053,97 @@ void main() {
...
+    const ValueKey<String> tapRegion1Key = ValueKey<String>('TapRegion');
+    const ValueKey<String> tapRegion2Key = ValueKey<String>('TapRegion2');
+
+    int count1 = 0;
+    int count2 = 0;
+
+    final TapRegion tapRegion1 = TapRegion(
+      key: tapRegion1Key,
+      onTapOutside: (PointerEvent event) {
+        count1++;
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/tap_region_test.dart:1067]: Another tiny nit based on the [style guide](https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#prefer--over-):

```suggestion
        count1 += 1;
```

(same applies to tapRegion2)

File: packages/flutter/test/widgets/tap_region_test.dart [hunk 11]
```diff
@@ -1053,4 +1053,97 @@ void main() {
...
+      },
+      child: Container(
+        width: 100,
+        height: 100,
+        color: Colors.red,
+      ),
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/tap_region_test.dart:1073]: I probably shouldn't be suggesting this since it's not a big deal whatsoever, but I'm in the habit of avoiding Container objects since they have suboptimal performance.

```suggestion
      behavior: HitTestBehavior.opaque,
      child: SizedBox.square(dimension: 100),
```

File: packages/flutter/test/widgets/tap_region_test.dart [hunk 12]
```diff
@@ -1053,4 +1053,97 @@ void main() {
     await click(find.text('Outside Surface'));
     expect(tappedInside, isEmpty);
   });
+
+  testWidgets('TapRegion should register and unregister correctly on push and pop', (WidgetTester tester) async {
```
Comment (nate-thegrate) [inline packages/flutter/test/widgets/tap_region_test.dart:1057]:
```suggestion
  // Regression test for https://github.com/flutter/flutter/issues/153093.
  testWidgets('TapRegion should register and unregister correctly on push and pop', (WidgetTester tester) async {
```

**Review by nate-thegrate — COMMENTED** [review]
Thanks so much for this update! I love the solution's simplicity, and it looks like we have good test coverage for it too.

With regards to the test, I have a bunch of tiny suggestions, so take a look when you have a chance :)

File: packages/flutter/lib/src/widgets/tap_region.dart [hunk 13]
```diff
@@ -403,6 +404,8 @@ class TapRegion extends SingleChildRenderObjectWidget {
 
   @override
   RenderObject createRenderObject(BuildContext context) {
+    ModalRoute.of(context);
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/tap_region.dart:407]: why didn't we disable on tap outside in the create method?

[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/tap_region.dart:407]: also somewhere in the doc should mention this now will be aware of the route

**Review by chunhtai — COMMENTED** [review]
just some comments

File: packages/flutter/lib/src/widgets/tap_region.dart (hunk 13 above)
[the remark this answers is not in the document]
Comment (nate-thegrate) [reply packages/flutter/lib/src/widgets/tap_region.dart:411]: > why didn't we disable on tap outside in the create method?

I believe the assumption is that new widgets are always inflated in the active/current route.
(But now that you mention it, maybe there are edge cases we should take into account.)

[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/tap_region.dart:411]: You may have cases where you have multiple initial routes. or multiple route add/push.

while they will not be laid out, but it will still be built

[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/tap_region.dart:411]: Also I meant the API doc of TapRegion class should be updated to mention the new behavior

[the remark this answers is not in the document]
Comment (Mairramer) [reply packages/flutter/lib/src/widgets/tap_region.dart:411]: > You may have cases where you have multiple initial routes. or multiple route add/push.
> 
> while they will not be laid out, but it will still be built
Hmm, I see.

**Review by nate-thegrate — APPROVED** [review]
LGTM, pending a couple of comment tweaks 👍

Thanks for making this fix, and being responsive to feedback!

File: packages/flutter/lib/src/widgets/tap_region.dart [hunk 14]
```diff
@@ -329,6 +330,9 @@ class _DummyTapRecognizer extends GestureArenaMember {
 /// regions in the group will act as one.
 ///
 /// If there is no [TapRegionSurface] ancestor, [TapRegion] will do nothing.
+///
+/// [TapRegion] calls [ModalRoute.of] to establish a dependency on the current route,
+/// so that [onTapOutside] isn't called after the user navigates to a different page.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/tap_region.dart:335]:
```suggestion
/// [TapRegion] is aware of the [Route]s in the [Navigator], so that [onTapOutside]
/// isn't called after the user navigates to a different page.
```

**Review by chunhtai — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/tap_region.dart [hunk 15]
```diff
@@ -403,12 +407,14 @@ class TapRegion extends SingleChildRenderObjectWidget {
...
   RenderObject createRenderObject(BuildContext context) {
+    final ModalRoute<Object?>? route = ModalRoute.of(context);
+
     return RenderTapRegion(
       registry: TapRegionRegistry.maybeOf(context),
       enabled: enabled,
       consumeOutsideTaps: consumeOutsideTaps,
       behavior: behavior,
-      onTapOutside: onTapOutside,
+      onTapOutside: (route?.isCurrent ?? true) ? onTapOutside : null,
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/tap_region.dart:417]: Can we use https://api.flutter.dev/flutter/widgets/ModalRoute/isCurrentOf.html here? That uses an aspect of the modal route, which would be better for rebuilds.

File: packages/flutter/lib/src/widgets/tap_region.dart [hunk 16]
```diff
@@ -417,12 +423,14 @@ class TapRegion extends SingleChildRenderObjectWidget {
 
   @override
   void updateRenderObject(BuildContext context, covariant RenderTapRegion renderObject) {
+    final ModalRoute<Object?>? route = ModalRoute.of(context);
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/tap_region.dart:426]: Same here

File: packages/flutter/lib/src/widgets/tap_region.dart (hunk 15 above)
Comment (Mairramer) [reply packages/flutter/lib/src/widgets/tap_region.dart]: Yes it works, thanks.

Comment (nate-thegrate) [reply packages/flutter/lib/src/widgets/tap_region.dart]: Didn't realize ModalRoute was an inherited model, good to know!

**Comment by vfiruz97** [comment]
thanks, pretty elegant contribution! When will we see this in stable version?

**Comment by nate-thegrate** [comment]
> thanks, pretty elegant contribution! When will we see this in stable version?

Stable releases happen on a quarterly basis, so most likely in a month from now!
