### PR TITLE
Switched the font atlas to discrete math for hash keys

### LINKED ISSUE #164606: [Impeller]Impeller errors appear when app opens:`Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.`
### Steps to reproduce

1. Install and run [Wonderous](https://github.com/gskinnerTeam/flutter-wonderous-app) app on Android and iOS, my devices are: `Pixel 7, Android 15` and `iPhone 16 Pro Max (iOS 18.3.1)`.
2. Home page/screen will appear (since the second time open app), and observe Impeller errors appear from the run output log. If you swipe pages, more same errors may appear.

Observing this issue on Flutter master channel `3.30.0-1.0.pre.448`while I don't see it on stable 3.29.0.

### Expected results

No error appear

### Actual results

Multiple same errors are printed out as shared in Logs section.

### Code sample

<details open><summary>Code sample</summary>

https://github.com/gskinnerTeam/flutter-wonderous-app

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/0c3ccff9-cb39-49b9-98f8-a8c19f7c6a79

</details>

### Logs

<details open><summary>Logs</summary>

```console
Connecting to VM Service at ws://127.0.0.1:58613/UshQ4FN6TyY=/ws
Connected to the VM Service.
flutter: bootstrap start...
flutter: Navigate to: /
flutter: Saving...
flutter: setting discoveredCount for home widget 2
flutter: Navigate to: /home
11
[ERROR:flutter/impeller/entity/contents/text_contents.cc(161)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.
2
flutter: Saving...
19
[ERROR:flutter/impeller/entity/contents/text_contents.cc(161)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.
2
flutter: Saving...
24
[ERROR:flutter/impeller/entity/contents/text_contents.cc(161)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel master, 3.30.0-1.0.pre.448, on macOS 15.3.1 24D70 darwin-x64, locale en-VN) [4.1s]
    • Flutter version 3.30.0-1.0.pre.448 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 24418d0d80 (2 hours ago), 2025-03-04 00:04:22 -0500
    • Engine revision 24418d0d80
    • Dart version 3.8.0 (build 3.8.0-133.0.dev)
    • DevTools version 2.43.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [4.5s]
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [1,828ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [27ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [25ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] VS Code (version 1.97.2) [23ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.106.0

[✓] Connected device (4 available) [7.2s]
    • Pixel 7 (mobile)                      • 2B171FDH20084L            • android-arm64  • Android 15 (API 35)
    • iPhone 16 pro max (wireless) (mobile) • 00008140-00194CC23A68801C • ios            • iOS 18.3.1 22D72
    • macOS (desktop)                       • macos                     • darwin-x64     • macOS 15.3.1 24D70 darwin-x64
    • Chrome (web)                          • chrome                    • web-javascript • Google Chrome 133.0.6943.142

[✓] Network resources [477ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by gaaclarke**
issue: https://github.com/flutter/flutter/issues/164606

This is a refactor of how we store font atlas data.  Previously we were using floating point values with custom hash functions as keys.  This was very hard to debug.  This change instead makes all keys used in the font atlas discrete.

The hope was that this might fix https://github.com/flutter/flutter/issues/164606, or at least make it easier to debug.  It didn't fix the issue.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by gaaclarke** [comment]
In theory this can give us higher fidelity too.  I don't take advantage of it here.  But we could start doing `(x*y)/z` instead of `x*(y/z)`.

File: engine/src/flutter/impeller/typographer/backends/skia/typographer_context_skia.cc [hunk 1]
```diff
@@ -453,23 +459,24 @@ TypographerContextSkia::CollectNewGlyphs(
...
+                      static_cast<Scalar>(scaled_font.scale));
       sk_font.setSubpixel(true);
 
       for (const auto& glyph_position : run.GetGlyphPositions()) {
-        Point subpixel = TextFrame::ComputeSubpixelPosition(
-            glyph_position, scaled_font.font.GetAxisAlignment(),
-            frame->GetTransform() *
-                Matrix::MakeTranslation(frame->GetOffset()));
+        auto foo =
+            frame->GetTransform() * Matrix::MakeTranslation(frame->GetOffset());
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/typographer/backends/skia/typographer_context_skia.cc:468]: ooops, I left this debugging code in.  It's going to have to be fixed when I merge with the workaround we are about to land though.

File: engine/src/flutter/impeller/geometry/rational.cc [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+    return AbsToUnsigned(num_) * that.den_ < AbsToUnsigned(that.num_) * den_;
+  }
+}
+
+uint64_t Rational::GetHash() const {
+  if (num_ == 0) {
+    return 0;
+  }
+  uint64_t gcd = std::gcd(num_, den_);
+  return ((num_ / gcd) << 32) | (den_ / gcd);
```
Comment (jonahwilliams) [inline engine/src/flutter/impeller/geometry/rational.cc:47]: So the goal here is to compute a hash that is == when the values are equal, basically making sure that 1/5 and 2/10 have the same hash?

File: engine/src/flutter/impeller/typographer/font_glyph_pair.h [hunk 3]
```diff
@@ -54,16 +55,35 @@ struct ScaledFont {
   };
 };
 
+enum SubpixelPosition : uint8_t {
+  kSubpixel00 = 0x0,
```
Comment (jonahwilliams) [inline engine/src/flutter/impeller/typographer/font_glyph_pair.h:59]: Lets document this a bit more: which ones are the X positions and which ones are Y positions?

File: engine/src/flutter/impeller/typographer/backends/skia/typographer_context_skia.cc [hunk 4]
```diff
@@ -205,6 +205,10 @@ static ISize ComputeNextAtlasSize(
   return {};
 }
 
+static Point SubpixelPositionToPoint(SubpixelPosition pos) {
```
Comment (jonahwilliams) [inline engine/src/flutter/impeller/typographer/backends/skia/typographer_context_skia.cc:208]: hmm yess... yes

**Review by jonahwilliams — COMMENTED** [review]
Like this approach, mostly just nits!

File: engine/src/flutter/impeller/geometry/rational.cc (hunk 2 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/geometry/rational.cc:47]: Exactly, we had a few other options:
1) Simplify the fractions in the constructor so that if you ask for Rational(2, 10) you get Rational(1, 5), but I tried to optimize the math for fractions with the same denominator.
1) Make the denominator part of the type, so `Rational(1,5)` becomes `Rational<5>(1)`. That way we could have made sure everything has the same denominator.  It only occurred to me later, it is a bit awkward though.

File: engine/src/flutter/impeller/typographer/font_glyph_pair.h (hunk 3 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/typographer/font_glyph_pair.h:63]: done

File: engine/src/flutter/impeller/geometry/rational.cc (hunk 2 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/geometry/rational.cc:47]: I'm slightly concerned about the performance of computing the gcd (nlogn ?) for the hash, given that we end up hashing each glyph each frame. the subpixel hash already shows up quite hot in the flame graphs. this can be verified on an app with a moderate amount of text, like the old flutter gallery.

I'd lean towards an approach where we computed the float and then hashed that.

Comment (gaaclarke) [reply engine/src/flutter/impeller/geometry/rational.cc:47]: I had the same concern, but gcd isn't actually that expensive.  Our denominator will typically be 200, so the worst case scenario is Rational(199,200).  The euclidean method loops 3 times in order to figure that out which is like 12 operations.

I don't think we want to compute the float since you'll be throwing away precision.  We have the opportunity to have a perfect hash function without gcd in it in the 2 approaches I listed above.

Comment (gaaclarke) [reply engine/src/flutter/impeller/geometry/rational.cc:47]: Let's land it like this and look at the numbers afterwards.  I say if we notice any change we should switch to approach 2 since it is the fastest.

**Review by jonahwilliams — APPROVED** [review]
LGTM
