### PR TITLE
Finish removing `null-safety` mode, checks, and reporting.

### LINKED ISSUE #162846: Remove `*nullSafety*`(Mode) from `flutter_tools`
I suspect in the last 16 months if folks are still seeing this at HEAD we would ... know something is horribly broken:
https://github.com/flutter/flutter/blob/1e035cc693f067ed5033f180e0b6169d2c8a3e58/packages/flutter_tools/lib/src/commands/build.dart#L119-L133

There are still artifacts from https://github.com/flutter/flutter/issues/118810, basically.

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/162846.

At HEAD, including before this PR, it was impossible to use, or pass-in, an unsound null-safety mode, but we still had code checking for it, and reported analytics (I think? Some of these are `package:usage` specific which is defunct).

This PR eradicates the otherwise unused code.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by bkonyi — APPROVED** [review]

File: packages/flutter_tools/lib/src/test/web_test_compiler.dart [hunk 1]
```diff
@@ -118,24 +118,10 @@ class WebTestCompiler {
...
-    switch (buildInfo.nullSafetyMode) {
-      case NullSafetyMode.unsound || NullSafetyMode.autodetect:
-        // TODO(matanlurey): Should be unreachable, remove as part of https://github.com/flutter/flutter/issues/162846.
-        throw UnsupportedError('Unsound null safety mode is not supported');
-      case NullSafetyMode.sound:
-        languageVersion = currentLanguageVersion(_fileSystem, Cache.flutterRoot!);
-        platformDillName = 'ddc_outline.dill';
-    }
-
+    final LanguageVersion languageVersion = LanguageVersion(2, 8);
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/test/web_test_compiler.dart]: The errors on CI are caused by this, 2.8 is the last non-null safe version. I _think_ if you just leave the language version string out, it will just work, but specifying an old version won't

Comment (matanlurey) [reply packages/flutter_tools/lib/src/test/web_test_compiler.dart]: Right, it was my mistake, the original code was:

```dart
final LanguageVersion languageVersion = currentLanguageVersion(_fileSystem, Cache.flutterRoot!);
```

Is that better (or worse) than your suggestion of omission?
