### PR TITLE
[flutter_tools] retry chrome launch up to 3 times

### LINKED ISSUE #83899: Retry chrome launch on debug connection failure
web_tool_tests flake on setting up the debug connection with chrome:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/2305/overview

Not sure if this is the right fix, but when hitting the exception here:

https://github.com/flutter/flutter/blob/59cdad49143c967cef2d46ae510a24c00d2b6f71/packages/flutter_tools/lib/src/web/chrome.dart#L392

instead of throwing a tool exit, we might try killing chrome and trying again some number of times. There's already a retry loop for spawning chrome, so maybe it just needs to be a bit wider to encompass the connection check as well?

/cc @jonahwilliams @grouma @annagrin

### PR DESCRIPTION
**Pull request by jonahwilliams**
Instead of only retrying chrome launch on the glibc bug, just retry up to 3 times to see if it can pass

Fixes https://github.com/flutter/flutter/issues/83899

### CODE REVIEW

File: packages/flutter_tools/lib/src/web/chrome.dart [hunk 1]
```diff
@@ -282,17 +285,22 @@ class ChromiumLauncher {
             // Return value unused.
             return '';
           }
-          _logger.printTrace('Failed to launch browser. Command used to launch it: ${args.join(' ')}');
-          throw ToolExit(
-            'Failed to launch browser. Make sure you are using an up-to-date '
-            'Chrome or Edge. Otherwise, consider using -d web-server instead '
-            'and filing an issue at https://github.com/flutter/flutter/issues.',
-          );
+          if (retry >= 3) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/web/chrome.dart:288]: Pull 3 up out of the loop to a named constant. `kMaxRetries`

**Review by zanderso — COMMENTED** [review]
Does this help with any particular issue that we have filed?

**Comment by jonahwilliams** [comment]
the issue is around here somewhere...

**Review by zanderso — APPROVED** [review]
