### PR TITLE
[Material] Fix BottomNavTheme.showSelectedLabels bug

### LINKED ISSUE #66738: showSelectedLabels of BottomNavigationBarThemeData is not applied
I could be wrong, but the issue is likely caused by `showSelectedLabels` having a default value set in the BottomNavigationBar's constructor, which makes the part after the ?? operator on this line unreachable (at least in debug mode, since it doesn't allow null) :
https://github.com/flutter/flutter/blob/ec40df9576d6020dd56820b9b5aff8f828706e49/packages/flutter/lib/src/material/bottom_navigation_bar.dart#L901 
As a fix the default value could be moved from the constructor to the `build` method (as it is done for `showUnselectedLabels` on the next line of the mentioned file).

## Steps to Reproduce

Create a new project, update the contents of `main.dart` as follows, and run it
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        bottomNavigationBarTheme: BottomNavigationBarThemeData(
          type: BottomNavigationBarType.fixed,
          showSelectedLabels: false,
          showUnselectedLabels: true,
        ),
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _page = 0;

  void _updatePage(int page) {
    setState(() => _page = page);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: Text('$_page')),
      bottomNavigationBar: _buildBottomNavBar(),
    );
  }

  Widget _buildBottomNavBar() {
    return BottomNavigationBar(
      onTap: _updatePage,
      currentIndex: _page,
      items: [
        BottomNavigationBarItem(
          icon: const Icon(Icons.looks_one),
          label: 'Label 1',
        ),
        BottomNavigationBarItem(
          icon: const Icon(Icons.looks_two),
          label: 'Label 2',
        ),
        BottomNavigationBarItem(
          icon: const Icon(Icons.looks_3),
          label: 'Label 3',
        ),
      ],
    );
  }
}
```

**Expected results:**
Selected item's text is not visible.

**Actual results:**
Selected item's text is visible.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.380, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.380 at E:\Android\flutter
    • Framework revision ec40df9576 (11 hours ago), 2020-09-25 21:27:22 -0700
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at E:\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_SDK_ROOT = E:\Android\sdk
    • Java binary at: E:\Android\Android-Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at E:\Android\Android-Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.1)
    • VS Code at C:\Users\El\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Redmi Note 5 (mobile)              • 4fcb747c      • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86   • Android 7.0 (API 24) (emulator)

• No issues found!
```

</details>

### LINKED ISSUE #67185: [doc] BottomNavigationBarItem : Update title with label to reflect correct message.
I noticed that the API documentation for [BottomNavigationBarItem](https://api.flutter.dev/flutter/widgets/BottomNavigationBarItem/BottomNavigationBarItem.html) is out of date.

It mentions:
> The argument `icon` should not be null and the argument `title` should not be null when used in a Material Design's BottomNavigationBar.

However, since `title` is now deprecated, shouldn't this message be revised to say `label` instead?

### PR DESCRIPTION
**Pull request by johnsonmh**
## Description

This PR fixes a bug with the `BottomNavigationBarThemeData.showSelectedLabels` param. Because `BottomNavigationBar.showSelectedLables` was being set to `true`, in the constructor, that meant it was not null by default, as the rest of the implementation expected.

Also cleaned up some of the NNBD logic. 

## Related Issues

Fixes https://github.com/flutter/flutter/issues/66738
Fixes https://github.com/flutter/flutter/issues/67185

## Tests

I added the following tests:

* Test that `BottomNavTheme.showSelectedLabels: false`  and `BottomNavTheme.showUnselectedLabels: false` works when no widget params provided.
* Test that `BottomNavTheme.showSelectedLabels: false`  and `BottomNavTheme.showUnselectedLabels: true` works when no widget params provided.
* Test that `BottomNavTheme.showSelectedLabels: true`  and `BottomNavTheme.showUnselectedLabels: false` works when no widget params provided.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by clocksmith — APPROVED** [review]

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 1]
```diff
@@ -898,7 +896,7 @@ class _BottomNavigationBarState extends State<BottomNavigationBar> with TickerPr
         colorTween: colorTween,
         flex: _evaluateFlex(_animations[i]),
         selected: i == widget.currentIndex,
-        showSelectedLabels: widget.showSelectedLabels ?? bottomTheme.showSelectedLabels,
+        showSelectedLabels: widget.showSelectedLabels ?? bottomTheme.showSelectedLabels ?? true,
         showUnselectedLabels: widget.showUnselectedLabels ?? bottomTheme.showUnselectedLabels ?? _defaultShowUnselected,
```
Comment (rami-a) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart:900]: Should `_defaultShowUnselected` just be replaced with the value itself to match the line above?

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 2]
```diff
@@ -476,17 +474,17 @@ class _BottomNavigationTile extends StatelessWidget {
...
               animation: animation,
               item: item,
-              selectedLabelStyle: selectedLabelStyle ?? bottomTheme.selectedLabelStyle,
-              unselectedLabelStyle: unselectedLabelStyle ?? bottomTheme.unselectedLabelStyle,
-              showSelectedLabels: showSelectedLabels ?? bottomTheme.showUnselectedLabels,
-              showUnselectedLabels: showUnselectedLabels ?? bottomTheme.showUnselectedLabels,
+              selectedLabelStyle: selectedLabelStyle,
+              unselectedLabelStyle: unselectedLabelStyle,
+              showSelectedLabels: showSelectedLabels,
+              showUnselectedLabels: showUnselectedLabels,
```
Comment (rami-a) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart:487]: whats the reason for this change?

**Review by rami-a — APPROVED** [review]

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 2 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart:481]: The null coalescing here is redundant, because the values passed to `_BottomNavigationTile` have already done the null theme checks. This will also make the NNBD migration more clear.

https://github.com/flutter/flutter/pull/67078

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 1 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart:894]: No, because _defaultShowUnselected is a getter that depends on the `BottomNavigationBar.type`

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 3]
```diff
@@ -164,9 +164,8 @@ class BottomNavigationBar extends StatefulWidget {
   /// former is preferred, [fixedColor] only exists for the sake of
   /// backwards compatibility.
   ///
-  /// The [showSelectedLabels] argument must be non-null.
-  ///
-  /// The [showUnselectedLabels] argument defaults to `true` if [type] is
+  /// The [showSelectedLabels] argument defaults to `true`. The
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart:167]: This isn't strictly true (it defaults to null) and it doesn't cover what's actually happening: `widget.showSelectedLabels ?? bottomTheme.showSelectedLabels ?? true`.

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 4]
```diff
@@ -164,9 +164,8 @@ class BottomNavigationBar extends StatefulWidget {
...
+  /// [showUnselectedLabels] argument defaults to `true` if [type] is
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart:168]: Similar comment to the previous one.

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 5]
```diff
@@ -383,16 +381,10 @@ class _BottomNavigationTile extends StatelessWidget {
...
-
     final double selectedFontSize = selectedLabelStyle.fontSize!;
 
-    final double selectedIconSize = selectedIconTheme?.size
-      ?? bottomTheme.selectedIconTheme?.size
-      ?? iconSize;
-    final double unselectedIconSize = unselectedIconTheme?.size
-      ?? bottomTheme.unselectedIconTheme?.size
-      ?? iconSize;
+    final double selectedIconSize = selectedIconTheme?.size ?? iconSize;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart:386]: Why are we now ignoring `bottomTheme.selectedIconTheme?.size`? Here and on the next line.

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 3 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart:167]: Updated comment

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 4 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart:168]: Updated comment

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 5 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart:386]: We discussed this offline, but to summarize, the whole `BottomNavigationBarThemeData.selectedIconTheme` is ignored if `BottomNavigationBar.selectedIconTheme` is present. I updated the documentation on `BottomNavigationBarThemeData` to make that more clear.

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 6]
```diff
@@ -164,10 +164,14 @@ class BottomNavigationBar extends StatefulWidget {
   /// former is preferred, [fixedColor] only exists for the sake of
   /// backwards compatibility.
   ///
-  /// The [showSelectedLabels] argument must be non-null.
+  /// If [showSelectedLabels] is `null`, [BottomNavigationBarThemeData.showSelectedLabels]
+  /// is used. If [BottomNavigationBarThemeData.showSelectedLabels]  is null,
+  /// then [showSelectedLabels] defaults to `true`.argument defaults to `true`.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart:169]: typo here - remove trailing `argument defaults to `true`.

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 7]
```diff
@@ -164,10 +164,14 @@ class BottomNavigationBar extends StatefulWidget {
...
   ///
-  /// The [showUnselectedLabels] argument defaults to `true` if [type] is
-  /// [BottomNavigationBarType.fixed] and `false` if [type] is
+  /// If [showUnselectedLabels] is `null`, [BottomNavigationBarThemeData.showUnselectedLabels]
+  /// is used. If [BottomNavigationBarThemeData.showSelectedLabels]  is null,
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart:172]: extra space before "is null"

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by pedromassangocode** [comment]
Updating PR to close the related issues automatically.

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 6 above)
Comment (johnsonmh) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart:169]: Thanks for spotting this
