### PR TITLE
fix hidden TextSpan with recognizer does not auto scroll

### LINKED ISSUE #100395: [iOS][A11y] hidden TextSpan with recognizer does not auto scroll.
b/219908129

## Steps to Reproduce

<details>
<summary>code  </summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

class Home extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    final description =
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
        'Make each shot Make each shotMake each shotMake each shotMake each shotMake each shotMake each shot'
    ;

    return Scaffold(
      appBar: AppBar(
        title: Text('test'),
      ),
      body: ListView(
        children: [
          const SizedBox(height: 100.0),
          Text.rich(
              TextSpan(
                  children: [
                    TextSpan(text: description),
                    TextSpan(text: 'Learn More', recognizer: TapGestureRecognizer()..onTap = () => null),
                  ]
              )
          ),
        ],
      ),
    );
  }
}

void main() {
  runApp(MaterialApp(home: Home()));
}
```

</details>
1. turn on voice over
2. try to focus the `learn more` by swiping right.

the screen does not auto scroll the focused span

### PR DESCRIPTION
**Pull request by chunhtai**
Makes RenderParagraph and RenderEditable to mark text span semantics node hidden if they are off screen. Also implement show on screen logic for the hidden semantics node. As part of the implementation, I move UniqueKey class from widget layer to foundation so that it can be used by both RenderParagraph and RenderEditable

fixes https://github.com/flutter/flutter/issues/100395

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/100494

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/100494

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/100494

**Comment by chunhtai** [comment]
cc @Kate the golden triage log is empty. may need some guidance.

**Comment by Piinks** [comment]
Nope, this is fine. Please disregard the skia bot messages here. Thanks!

File: packages/flutter/lib/src/foundation/key.dart [hunk 1]
```diff
@@ -47,6 +49,23 @@ abstract class LocalKey extends Key {
   const LocalKey() : super.empty();
 }
 
+/// A key that is only equal to itself.
+///
+/// This cannot be created with a const constructor because that implies that
+/// all instantiated keys would be the same instance and therefore not be unique.
+class UniqueKey extends LocalKey {
```
Comment (justinmc) [inline packages/flutter/lib/src/foundation/key.dart:56]: Moving this here makes sense to me, isn't foundation where the other Key classes are?  Though maybe someone with more context on this stuff than me should confirm.  @goderbauer?

File: packages/flutter/lib/src/rendering/editable.dart [hunk 2]
```diff
@@ -1406,20 +1406,38 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
...
         newChildren.add(newChild);
       }
     }
     _cachedChildNodes = newChildCache;
     node.updateWith(config: config, childrenInInversePaintOrder: newChildren);
   }
 
+  VoidCallback? _createShowOnScreenFor(Key key) {
+    return () {
+      final SemanticsNode node = _cachedChildNodes![key]!;
```
Comment (justinmc) [inline packages/flutter/lib/src/rendering/editable.dart:1436]: So newChildCache became a LinkedHashMap instead of a Queue so that you can do this lookup here?

File: packages/flutter/test/widgets/text_test.dart [hunk 3]
```diff
@@ -412,6 +412,76 @@ void main() {
...
+    // Test show on screen.
+    expect(controller.offset, 0.0);
+    tester.binding.pipelineOwner.semanticsOwner!.performAction(4, SemanticsAction.showOnScreen);
+    await tester.pumpAndSettle();
+    expect(controller.offset != 0.0, isTrue);
+
+    semantics.dispose();
+  });
+
+
```
Comment (justinmc) [inline packages/flutter/test/widgets/text_test.dart:484]: Too many newlines here.

**Review by justinmc — APPROVED** [review]
LGTM 👍 

Just double check that moving UniqueKey is ok.  I guess there is a small chance of a breaking change?

This helps fix the problem that you were talking about recently for global selection of offscreen items in a list, right?  Seems like a good way to do it, we probably should have done this originally anyway 👍 .

**Comment by chunhtai** [comment]
> This helps fix the problem that you were talking about recently for global selection of offscreen items in a list, right? Seems like a good way to do it, we probably should have done this originally anyway 👍 .

The global selection is a different issue. This is to fix a problem where iOS voiceover does not auto scroll when the textspan is off screen

**Comment by chunhtai** [comment]
> Just double check that moving UniqueKey is ok. I guess there is a small chance of a breaking change?

I export the UniqueKey in the widgets.dart. So It should not be a breaking change.

File: packages/flutter/lib/src/foundation/key.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/foundation/key.dart:56]: Moving this here seems fine.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 2 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/editable.dart:1436]: yes, unfortunately the showonscreen can't be change after the node is created.
