### PR TITLE
Revert "Disable selection of the Android ARM64 target platform based on the attached device"

### LINKED ISSUE #14646: Flutter crashes with run in release mode, can't find libflutter.so
## Steps to Reproduce
```
rm -rf build
flutter upgrade
flutter run --release
```

Crash:

```
02-12 11:11:54.773 14016 14016 D AndroidRuntime: Shutting down VM
02-12 11:11:54.774 14016 14016 E AndroidRuntime: FATAL EXCEPTION: main
02-12 11:11:54.774 14016 14016 E AndroidRuntime: Process: <redacted>, PID: 14016
02-12 11:11:54.774 14016 14016 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/<redacted>--Dq_zYwqOAAC0D2dY6KCNA==/base.apk"],nativeLibraryDirectories=[/data/app/<redacted>--Dq_zYwqOAAC0D2dY6KCNA==/lib/arm64, /data/app/<redacted>--Dq_zYwqOAAC0D2dY6KCNA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1657)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:157)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:142)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:20)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
02-12 11:11:54.774 14016 14016 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
02-12 11:11:54.777   398   634 W ActivityManager:   Force finishing activity <redacted>/.MainActivity
02-12 11:11:54.779   398   413 I ActivityManager: Showing crash dialog for package <redacted> u0

```

### PR DESCRIPTION
**Pull request by jason-simmons**
This reverts commit cdb581807cc11030b63d00c04bb2d55fcb3d7ef4.

Dart has been updated in the engine, and this workaround should no longer be necessary.

Fixes https://github.com/flutter/flutter/issues/14646

### CODE REVIEW

**Review by tvolkert — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/android/android_device.dart [hunk 1]
```diff
@@ -366,11 +366,15 @@ class AndroidDevice extends Device {
       return new LaunchResult.failed();
     }
 
+    BuildInfo buildInfo = debuggingOptions.buildInfo;
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/android/android_device.dart]: `debuggingOptions` can legally be `null` here.
