### PR TITLE
[flutter_tools] handle terminals that do not support single char mode in Terminal.promptForCharInput

### LINKED ISSUE #65267: "Please choose one (To quit, press "q/Q")" does not work in Emacs terminal buffer
```
$ flutter run
Building flutter tool...
Downloading android-arm-profile/linux-x64 tools...                  0.5s
Downloading android-arm-release/linux-x64 tools...                  0.3s
Downloading android-arm64-profile/linux-x64 tools...                0.4s
Downloading android-arm64-release/linux-x64 tools...                0.5s
Downloading android-x64-profile/linux-x64 tools...                  0.3s
Downloading android-x64-release/linux-x64 tools...                  0.4s
Downloading Web SDK...                                              1.2s
Multiple devices found:
Pixel 3 XL (mobile)      • 8AJY0LZ2N  • android-arm64  • Android 11 (API 30)
Lenovo TB 8504F (mobile) • HGAFGRP2   • android-arm64  • Android 7.1.1 (API 25)
Web Server (web)         • web-server • web-javascript • Flutter Tools
Chrome (web)             • chrome     • web-javascript • Google Chrome 81.0.4044.113
[0]: Pixel 3 XL (8AJY0LZ2N)
[1]: Lenovo TB 8504F (HGAFGRP2)
[2]: Web Server (web-server)
[3]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 0
0

Please choose one (To quit, press "q/Q"): 0
0
 
Please choose one (To quit, press "q/Q"): 0                                                                                                        
0
 
Please choose one (To quit, press "q/Q"): 0
0
 
Please choose one (To quit, press "q/Q"): q
q
 
Please choose one (To quit, press "q/Q"): q
q
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Some terminals stdin do not support single char mode (like an emacs terminal buffer apparently). If this is the case, then the presented choice values would always have an appended newline `\n` which would prevent us from finding the value in the listed index (or using it as a signal for the default choice). To fix, treat '' as the default choice and always trim the choice value.

While this has seemingly always been broken, it wasn't noticeable until the multi-device selection prompt was added a few months ago.

Fixes https://github.com/flutter/flutter/issues/65267

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/terminal.dart [hunk 1]
```diff
@@ -288,11 +288,11 @@ class AnsiTerminal implements Terminal {
         // prompt ends with ': '
         logger.printStatus(': ', emphasis: true, newline: false);
       }
-      choice = await keystrokes.first;
+      choice = (await keystrokes.first).trim();
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/terminal.dart:291]: Does this mean that we can't use e.g. spacebar as an input?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/terminal.dart:291]: yes - though this matches the restrictions that the resident runner has. This could be changed to strip off a trailing newline line if length > 1 instead? I'm not sure that would buy us that much

Comment (zanderso) [reply packages/flutter_tools/lib/src/base/terminal.dart:291]: Maybe worth adding this as a comment, though I'm not sure this would be the best spot?

The spacebar is pretty big on keyboards, so it might be convenient to use for something someday.

**Review by zanderso — APPROVED** [review]
lgtm
