### PR TITLE
Fix scroll jump when NestedScrollPosition is inertia-cancelled.

### LINKED ISSUE #116486: NestedScrollView accidentally scroll back to top when keep scrolling down
## Steps to Reproduce

1. run [example 1](https://github.com/flutter/flutter/blob/e617d003fbc4d20fdf4b7b381621a54429ce68da/examples/api/lib/widgets/nested_scroll_view/nested_scroll_view.1.dart) of NestedScrollView
2. keep scrolling down before scroll ended, then you can see the strange behavior in video

Works normal on web and mobile(iOS), strange in macOS. It seems flutter calculates offset from top again when previous scroll is still scrolling.

**Actual results:** 

https://user-images.githubusercontent.com/56487872/205503527-64948c78-4039-40c6-a0dc-08079c1c8efb.mov

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 3.6.0-0.1.pre, on macOS 12.6 21G115 darwin-x64, locale en-CN)
    • Flutter version 3.6.0-0.1.pre on channel beta at /Users/narumi/Library/flutter-beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 75927305ff (3 weeks ago), 2022-11-17 05:52:50 +0530
    • Engine revision b754eabc98
    • Dart version 2.19.0 (build 2.19.0-374.1.beta)
    • DevTools version 2.19.0
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

...flutter doctor stuck at check android licenses, so no following logs
```

</details>

### PR DESCRIPTION
**Pull request by moffatman**
`ScrollPosition.pointerScroll(delta)` is modified to support a delta of zero to stop inertia instead of issuing a jump to the current pixel value. The pixel value on the outer nested scroll position doesn't contain the information about the inner scroll position.

Fixes #116486

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 1]
```diff
@@ -780,7 +780,12 @@ class ScrollableState extends State<Scrollable> with TickerProviderStateMixin, R
         GestureBinding.instance.pointerSignalResolver.register(event, _handlePointerScroll);
       }
     } else if (event is PointerScrollInertiaCancelEvent) {
-      position.jumpTo(position.pixels);
+      if (position is ScrollActivityDelegate) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scrollable.dart:783]: Mainly just curious, in what case would this not be a ScrollActivityDelegate?

**Review by Piinks — COMMENTED** [review]
Thank you so much for jumping right on this. We might want to cherry pick it into the latest release candidate, @goderbauer WDYT?

File: packages/flutter/lib/src/widgets/scrollable.dart (hunk 1 above)
Comment (moffatman) [reply packages/flutter/lib/src/widgets/scrollable.dart:783]: Nowhere in flutter framework, but I guess they aren't guaranteed to be combined together. I don't know what the impact would be to make `ScrollPosition` implement `ScrollActivityDelegate`. Is there any way of seeing what that would break with whatever googler information you have available to you?

Comment (Piinks) [reply packages/flutter/lib/src/widgets/scrollable.dart:783]: Yeah, let me check and see if there are any cases where someone has implemented ScrollPosition and not included ScrollActivityDelegate..

Comment (Piinks) [reply packages/flutter/lib/src/widgets/scrollable.dart:783]: Actually, I started digging a bit, and I have a couple of ideas...

First, ScrollPosition has the beginActivity method, so you could actually just call for that here:

```dart
position.beginActivity(IdleScrollActivity(...));
```

Although in that case, it is required to provide a delegate, but...

ScrollActivity (and its ScrollActivityDelegate) manage dragging and flinging, so could it stand to reason that a scroll position that ends up here must be of a ScrollActivityDelegate?

If so, you could assert that...

```dart
assert(position is ScrollActivityDelegate);
position.beginActivity(IdleScrollActivity(position as ScrollActivityDelegate));
```

However, we don't have anything like this in Scrollable as an existing pattern. What we normally do is call on methods like pointerScroll that ScrollPositionWithSingleContext and _NestedScrollPosition implement in their own unique ways.
Ideally I think we would have this handled the same way. A method on ScrollPosition (like maybe `cancelActivity`?) would allow the same convention.
There are a fair number of customers that implement ScrollPosition so it would be breaking to add to ScrollPosition. Many of the implementing cases I can see though are just test mocks. I've fired off a global test run on adding something to ScrollPosition so I'll repot back on how breaking it is.

If `assert(position is ScrollActivityDelegate);` is logically fair, that might be the way to go if adding to ScrollPosition is incredibly breaking. What are your thoughts?

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 2]
```diff
@@ -780,7 +780,12 @@ class ScrollableState extends State<Scrollable> with TickerProviderStateMixin, R
         GestureBinding.instance.pointerSignalResolver.register(event, _handlePointerScroll);
       }
     } else if (event is PointerScrollInertiaCancelEvent) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scrollable.dart:782]: OH! Or (sorry last thought) - Can this somehow be handled in the `pointerScroll` method instead?

Comment (Piinks) [reply packages/flutter/lib/src/widgets/scrollable.dart:782]: The more I think about this, the more I feel it is the right way to go. Can `PointerScrollInertiaCancelEvent` be a subclass of `PointerScrollEvent`?

Comment (moffatman) [reply packages/flutter/lib/src/widgets/scrollable.dart:782]: It seems like pointerScroll always goes idle after use. So it should work, even if not by design I guess.

Comment (moffatman) [reply packages/flutter/lib/src/widgets/scrollable.dart:782]: Oh never mind it is actually specified to go idle. So i'll try that instead

>   /// Any active animation is canceled. If the user is currently scrolling, that
>  /// action is canceled.

Comment (moffatman) [reply packages/flutter/lib/src/widgets/scrollable.dart:782]: I don't know if it is smart to remove this assertion, anyone who has their own implementation might have it as well, and get a breakage/assertion failure when inertia cancel is used. 

https://github.com/flutter/flutter/blob/e57b7f4ea8ab8b348810d0a76f7bcf4aeabbe6d2/packages/flutter/lib/src/widgets/scroll_position_with_single_context.dart#L210-L215

Comment (Piinks) [reply packages/flutter/lib/src/widgets/scrollable.dart:782]: That's ok. I think in the case of 0 we can just go idle and return.. ostensibly any change we make in the framework can end up breaking someone's custom widgets. I think it is worth investigating. We have methods in place to identify if it would be a big breaking change.

**Comment by goderbauer** [comment]
> Thank you so much for jumping right on this. We might want to cherry pick it into the latest release candidate, @goderbauer WDYT?

I am on board with that. Can you create an issue for it and kick that off?

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 3]
```diff
@@ -903,8 +903,6 @@ class _NestedScrollCoordinator implements ScrollActivityDelegate, ScrollHoldCont
     // If an update is made to pointer scrolling here, consider if the same
     // (or similar) change should be made in
     // ScrollPositionWithSingleContext.pointerScroll.
-    assert(delta != 0.0);
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:906]: In the case of 0, can we go idle and just return? Just in case allowing delta to be 0 in these `pointerScroll` implementations would introduce other regressions.

**Comment by Piinks** [comment]
> Can you create an issue for it and kick that off?

Will do once it lands! Thanks!

**Review by Piinks — APPROVED** [review]
LGTM! Thank you again!
