### PR TITLE
Fix floating SnackBar throws when FAB is on the top

### LINKED ISSUE #128150: Floating SnackBar incompatible with certain FloatingActionButtonLocations
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create an app with a Scaffold and a FloatingActionButton
2. Set FloatingActionButtonLocation so that the button is at the top of the screen, such as FloatingActionButtonLocation.startTop.
3. Call a SnackBar with behavior of SnackBarBehavior.floating.

### Expected results

Display a SnackBar on a visible portion of the screen. Either at the bottom of the screen, or below the FloatingActionButton. 

### Actual results

SnackBar tries to float above the FloatingActionButton, causing it to display off-screen (or above the SafeArea, and partially off-screen). 

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyHomePage(title: 'Snackbar Position Issue'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  void _showSnackBar(BuildContext context) {
    SnackBar mySnackBar = const SnackBar(
      content: Text('Snack Time'),
      behavior: SnackBarBehavior.floating,
      width: 300,
    );
    ScaffoldMessenger.of(context).showSnackBar(mySnackBar);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Press the Ice Cream to call SnackBar'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          _showSnackBar(context);
        },
        tooltip: 'Call SnackBar',
        child: const Icon(Icons.icecream),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.startTop,
    );
  }
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots of SnackBar visible halfway off-screen</summary>

Screenshot from 2023-06-02 18-43-32

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.3, on Pop!_OS 22.04 LTS 5.18.10-76051810-generic, locale en_US.UTF-8)
    • Flutter version 3.10.3 on channel stable at /home/user/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (23 hours ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/user/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/user/Downloads/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.78.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Pixel 3a XL (mobile) • 94PAX0EFHR • android-arm64  • Android 12 (API 32)
    • Linux (desktop)      • linux      • linux-x64      • Pop!_OS 22.04 LTS 5.18.10-76051810-generic
    • Chrome (web)         • chrome     • web-javascript • Google Chrome 109.0.5414.74

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR updates how a floating snack bar is positionned when a `Scaffold` defines a FAB with `Scaffold.floatingActionButtonLocation` sets to one of the top locations.

**Before this PR:**
- When a FAB location is set to the top of the `Scaffold`, a floating `SnackBar` can't be displayed and an assert throws in debug mode.

**After this PR:**
- When a FAB location is set to the top of the `Scaffold`, a floating `SnackBar` will be displayed at the bottom of the screen, above a `NavigationBar` for instance (the top FAB is ignored when computing the floating snack bar position).

image

## Motivation

This is a edge case related to a discrepancy between the Material spec and the Flutter `Scaffold` customizability:
- Material spec states that a floating `SnackBar` should be displayed above a FAB. But, in Material spec, FABs are expected to be on the bottom.
- Since https://github.com/flutter/flutter/issues/51465, Flutter `Scaffold` makes it valid to show a FAB on the top of the `Scaffold`.

## Related Issue

fixes https://github.com/flutter/flutter/issues/128150

## Tests

Adds 1 test.

### CODE REVIEW

File: packages/flutter/lib/src/material/scaffold.dart [hunk 1]
```diff
@@ -1136,7 +1136,13 @@ class _ScaffoldLayout extends MultiChildLayoutDelegate {
       }
 
       final double snackBarYOffsetBase;
-      if (floatingActionButtonRect.size != Size.zero && isSnackBarFloating) {
+      final bool showAboveFab = currentFloatingActionButtonLocation != FloatingActionButtonLocation.startTop
```
Comment (Piinks) [inline packages/flutter/lib/src/material/scaffold.dart:1139]: This should use a switch statement. Dart 3 makes it really quite nice!

For example:

```dart
final BorderRadius childrenGroupBorderRadius = switch (type) {
        CupertinoListSectionType.insetGrouped => _kDefaultInsetGroupedBorderRadius,
        CupertinoListSectionType.base => BorderRadius.zero,
      };
```

Comment (bleroux) [reply packages/flutter/lib/src/material/scaffold.dart]: Nice! I switched to Dart 3 switch :smile:

File: packages/flutter/lib/src/material/scaffold.dart [hunk 2]
```diff
@@ -1136,7 +1136,16 @@ class _ScaffoldLayout extends MultiChildLayoutDelegate {
...
 
       final double snackBarYOffsetBase;
-      if (floatingActionButtonRect.size != Size.zero && isSnackBarFloating) {
+      final bool showAboveFab = switch (currentFloatingActionButtonLocation) {
+        FloatingActionButtonLocation.startTop => false,
+        FloatingActionButtonLocation.centerTop => false,
+        FloatingActionButtonLocation.endTop => false,
+        FloatingActionButtonLocation.miniStartTop => false,
+        FloatingActionButtonLocation.miniCenterTop => false,
+        FloatingActionButtonLocation.miniEndTop => false,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/scaffold.dart:1145]: These can use `||` so `=> false` does not need to be repeated.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 3]
```diff
@@ -1136,7 +1136,16 @@ class _ScaffoldLayout extends MultiChildLayoutDelegate {
...
+        _ => true,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/scaffold.dart:1146]: Instead of a default case, can you enumerate the other values? That way if we ever add another case, we won't introduce a bug where it isn't accounted for. This is actually why we prefer to use switch statements with enums :)

https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-using-if-chains-or--or--with-enum-values

Comment (bleroux) [reply packages/flutter/lib/src/material/scaffold.dart]: > This is actually why we prefer to use switch statements with enums :)
I'm not used to rely on switch, thanks for your explanations :+1: . 

In this particular case, it turned out that `FloatingActionButtonLocation` is not an enum (values are constants defined in an abstract class and they are initialized by instantiating various subclasses). I think we can't avoid adding a default case because this is not a real enum?
I pushed a commit where I enumerated all values (there are a lot ot them). It seems that this an edge case where maybe we can avoid listing all values for readability?

Comment (Piinks) [reply packages/flutter/lib/src/material/scaffold.dart]: Oh wow I did not realize it was an enum! TIL something new! In that case (and sorry for not realizing it sooner) I would recommend throwing an error for the default case. That way, if we add a new location, there will be an error that let's us know we need to account for it here. :)

File: packages/flutter/lib/src/material/scaffold.dart [hunk 4]
```diff
@@ -1136,7 +1136,29 @@ class _ScaffoldLayout extends MultiChildLayoutDelegate {
...
+        || FloatingActionButtonLocation.endContained
+        || FloatingActionButtonLocation.endDocked
+        || FloatingActionButtonLocation.endFloat
+        || FloatingActionButtonLocation.miniStartDocked
+        || FloatingActionButtonLocation.miniStartFloat
+        || FloatingActionButtonLocation.miniCenterDocked
+        || FloatingActionButtonLocation.miniCenterFloat
+        || FloatingActionButtonLocation.miniEndDocked
+        || FloatingActionButtonLocation.miniEndFloat => true,
+        FloatingActionButtonLocation() => true
```
Comment (Piinks) [inline packages/flutter/lib/src/material/scaffold.dart:1159]: So this instead could be that default case that presents an error. :)
I know it is very verbose, but it will keep future bugs away.

**Review by Piinks — APPROVED** [review]
LGTM!
