### PR TITLE
Paginated Data Table : Fixed Row number at footer in last page 

### LINKED ISSUE #116569: PaginatedDataTable shows "wrong" number of total records in footer on last page
The PaginatedDataTable displays empty rows on the last page, if their remaining number does not fit the height. That's ok for me, but the footer displays e.g.  "10 -20 of 15". In my opinion this is confusing, so I suggest the following change in paginated_data_table.dart (line 443):
```
footerWidgets.addAll(<Widget>[
      Container(width: 32.0),
      Text(
        localizations.pageRowsInfoTitle(
          _firstRowIndex + 1,
          _firstRowIndex + widget.rowsPerPage,
          _rowCount,
          _rowCountApproximate,
        ),
      ),
```

-->

```
footerWidgets.addAll(<Widget>[
      Container(width: 32.0),
      Text(
        localizations.pageRowsInfoTitle(
          _firstRowIndex + 1,
          math.min(_firstRowIndex + widget.rowsPerPage, _rowCount),
          _rowCount,
          _rowCountApproximate,
        ),
      ),
```

### PR DESCRIPTION
**Pull request by aakash-pamnani**
Fixed the row count in the footer.

Before
image

After
image

*Issues Resolved*
Fixes #116569

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/paginated_data_table_test.dart [hunk 1]
```diff
@@ -170,6 +170,138 @@ void main() {
     log.clear();
   });
 
+  testWidgets('PaginatedDataTable fotter page number', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/material/paginated_data_table_test.dart:173]:
```suggestion
  testWidgets('PaginatedDataTable footer page number', (WidgetTester tester) async {
```

File: packages/flutter/lib/src/material/paginated_data_table.dart [hunk 2]
```diff
@@ -456,7 +477,7 @@ class PaginatedDataTableState extends State<PaginatedDataTable> {
       Text(
         localizations.pageRowsInfoTitle(
           _firstRowIndex + 1,
-          _firstRowIndex + widget.rowsPerPage,
+          (_firstRowIndex + widget.rowsPerPage) > _rowCount ? _rowCount : (_firstRowIndex + widget.rowsPerPage),
```
Comment (Piinks) [inline packages/flutter/lib/src/material/paginated_data_table.dart:480]: Can you split this out into a separate pull request? Trying to fix multiple things with this widget is great! However, it would be a shame if one part of this PR was reverted because the other part created an unforeseen issue. :)

File: packages/flutter/lib/src/material/paginated_data_table.dart [hunk 3]
```diff
@@ -94,6 +95,11 @@ class PaginatedDataTable extends StatefulWidget {
     this.checkboxHorizontalMargin,
     this.controller,
     this.primary,
+    this.dataRowColor,
+    this.dividerThickness,
+    this.dataTextStyle,
+    this.headingRowColor,
+    this.headingTextStyle,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/paginated_data_table.dart:102]: Can you add tests that verify these new properties are all properly set when used?

**Review by Piinks — COMMENTED** [review]
Hi @aakash-pamnani! Welcome, and thanks for contributing. It looks like this PR is addressing two separate issues. Can you split them up into separate PRs? Thank you!

File: packages/flutter/lib/src/material/paginated_data_table.dart (hunk 2 above)
Comment (aakash-pamnani) [reply packages/flutter/lib/src/material/paginated_data_table.dart:480]: Sure I will create a new PR for the new parameters, I didn't thought about this. Thanks

File: packages/flutter/lib/src/material/paginated_data_table.dart (hunk 3 above)
Comment (aakash-pamnani) [reply packages/flutter/lib/src/material/paginated_data_table.dart:102]: I will try this.

**Comment by aakash-pamnani** [comment]
Hi @Piinks I have removed one fix from this PR, will create a new PR one the test's are ready.

**Review by Piinks — COMMENTED** [review]
Thank you for the update! I think just a small tweak below - using a min function is probably a bit more reader friendly. :)

File: packages/flutter/lib/src/material/paginated_data_table.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/paginated_data_table.dart:459]: Could this be a min function?

```suggestion
          math.min(_firstRowIndex + widget.rowsPerPage, _rowCount),
```

**Comment by aakash-pamnani** [comment]
Done

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Comment by gibahjoe** [comment]
I do not think this pr fixes https://github.com/flutter/flutter/issues/80421 as advertised because https://github.com/flutter/flutter/issues/80421 talks about phantom rows which is still visible in your _After_ photo.

**Comment by aakash-pamnani** [comment]
> I do not think this pr fixes #80421 as advertised because #80421 talks about phantom rows which is still visible in your _After_ photo.

Someone in #80421 commented that "The toolbar is then halfway down the page instead of at the bottom of the page." And that does not meet the material design standards.
And it actually resolves #116569 but it is closed with comments "duplicate of #80421 "

**Review by justinmc — APPROVED** [review]
LGTM 👍 

There was a test failure but it seems to be an infrastructure problem, so I've rerun it.

File: packages/flutter/test/material/paginated_data_table_test.dart [hunk 4]
```diff
@@ -170,6 +170,138 @@ void main() {
...
+
+    expect(find.text('5–8 of 500'), findsOneWidget);
+    expect(tester.widget<IconButton>(lastPageButton).onPressed, isNotNull);
+
+    await tester.tap(lastPageButton);
+    await tester.pump();
+
+    expect(find.text('497–500 of 500'), findsOneWidget);
+
+
```
[the remark this answers is not in the document]
Comment (aakash-pamnani) [reply packages/flutter/test/material/paginated_data_table_test.dart]: Hi @justinmc, removed the newline.
