### PR TITLE
Fix SelectionArea scrolling conflicts

### LINKED ISSUE #150897: SelectionArea intermittently interferes with listview scrolling (and possibly other scrolls)
### Steps to reproduce

SelectionArea wrapped around text within a listview is causing some of the scroll gestures to not get picked up (no response to swiping finger on the screen).

This behavior is intermittent.  But I'm best able to reproduce it when I scroll down (swipe up) fairly quickly and then 'catch' or stop the scroll by single tapping on the screen, then immediately after it stops then try to scroll up (swipe down) and nothing will happen. You will have to try swiping down a second or even third/fourth time for it to finally move the list.

I just noticed the behavior ~one week ago and took me some time to track down the cause of the issue.   Because it took time to find, Im not sure what change made it happen, but I can guess that it appears to affect master `3.23.0-13.0.pre.x`.  This behavior is not seen on the current stable channel of `3.22.2` or earlier versions of 3.23 from my recollection

UPDATE, trying to find the actual bad commit by randomly installing commits:
Commit `84fe3b6e537220caf03784a2f574cd009038b0d8` is OK (5/23/24)
Commit `d89ae485208c5c6a9e20fe1de994a7d22c9b4a00` is OK (5/30/24)
Commit `c63339866d4f7477777e7377bf044f14b743f71c` is OK (6/20/24)
Commit `9056c0b192bda5ff055a80d2caaa8c0d6d10dbac` is OK (6/20/24)
Commit `20459dda0d6d22d0502b9e04347401027016e573` is BAD (6/20/24)
Commit `4a84fb0fea9dedbedf47f225d1a5581f5e2a8ea2` is BAD (6/20/24)
Commit `d2b42d8c13f2dba6ba12c84a0e66fadf7eb94c16` is BAD (6/24/24)

UPDATE: Therefor I believe https://github.com/flutter/flutter/pull/149295 has caused this problem

Ive attached a simple widget to demonstrate the behavior.  I have alot of text and some images in there so that its a longer widget so you can play around and bring the effect out.  For comparison purposes, simply remove all the `SelectionArea` wrappers and you will see it is quite smooth and professional.  

This equally affects Android and iOS

I find this change to be fairly nasty as it makes otherwise bug-free apps feel sluggish and buggy.

### Expected results

Smooth scrolling fully responsive to user swipes

### Actual results

Many swipes up and down in a listviw are not registered and no movement occurs with swipes

### Code sample

<details open><summary>Code sample</summary>

Code in which the error can be seen
```dart
class TestView extends StatefulWidget {
  const TestView({super.key});

  @override
  State<TestView> createState() => _TestViewState();
}

class _TestViewState extends State<TestView> {
  @override
  Widget build(BuildContext context) {
    return
      Material(
        child: ListView(
            children: [
              Text('List item 1'),
              SizedBox(height: 30,),
              SelectionArea(child: Text('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet eget sit amet tellus cras adipiscing enim eu. In iaculis nunc sed augue lacus. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique senectus. Fringilla urna porttitor rhoncus dolor purus non. Nulla facilisi cras fermentum odio. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. Amet dictum sit amet justo donec enim diam vulputate ut. Fermentum iaculis eu non diam phasellus vestibulum lorem sed.\n\nMagna eget est lorem ipsum dolor. A diam maecenas sed enim. Vehicula ipsum a arcu cursus. Nisi quis eleifend quam adipiscing vitae proin sagittis. Ullamcorper velit sed ullamcorper morbi. Viverra suspendisse potenti nullam ac tortor. Augue lacus viverra vitae congue eu consequat. Et odio pellentesque diam volutpat commodo sed egestas. Viverra justo nec ultrices dui sapien. Ac placerat vestibulum lectus mauris ultrices eros in. At in tellus integer feugiat scelerisque. Neque gravida in fermentum et sollicitudin ac orci. Lectus mauris ultrices eros in. Turpis egestas maecenas pharetra convallis posuere morbi. Facilisis magna etiam tempor orci eu.')),
              SizedBox(height: 10,),
              Image.network('https://picsum.photos/1400/800'),
              Text('List item 10'),
              SizedBox(height: 30,),
              SelectionArea(child: Text('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet eget sit amet tellus cras adipiscing enim eu. In iaculis nunc sed augue lacus. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique senectus. Fringilla urna porttitor rhoncus dolor purus non. Nulla facilisi cras fermentum odio. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. Amet dictum sit amet justo donec enim diam vulputate ut. Fermentum iaculis eu non diam phasellus vestibulum lorem sed.\n\nMagna eget est lorem ipsum dolor. A diam maecenas sed enim. Vehicula ipsum a arcu cursus. Nisi quis eleifend quam adipiscing vitae proin sagittis. Ullamcorper velit sed ullamcorper morbi. Viverra suspendisse potenti nullam ac tortor. Augue lacus viverra vitae congue eu consequat. Et odio pellentesque diam volutpat commodo sed egestas. Viverra justo nec ultrices dui sapien. Ac placerat vestibulum lectus mauris ultrices eros in. At in tellus integer feugiat scelerisque. Neque gravida in fermentum et sollicitudin ac orci. Lectus mauris ultrices eros in. Turpis egestas maecenas pharetra convallis posuere morbi. Facilisis magna etiam tempor orci eu.')),
              SizedBox(height: 10,),

              Text('List item 20'),
              SizedBox(height: 30,),
              SelectionArea(child: Text('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet eget sit amet tellus cras adipiscing enim eu. In iaculis nunc sed augue lacus. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique senectus. Fringilla urna porttitor rhoncus dolor purus non. Nulla facilisi cras fermentum odio. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. Amet dictum sit amet justo donec enim diam vulputate ut. Fermentum iaculis eu non diam phasellus vestibulum lorem sed.\n\nMagna eget est lorem ipsum dolor. A diam maecenas sed enim. Vehicula ipsum a arcu cursus. Nisi quis eleifend quam adipiscing vitae proin sagittis. Ullamcorper velit sed ullamcorper morbi. Viverra suspendisse potenti nullam ac tortor. Augue lacus viverra vitae congue eu consequat. Et odio pellentesque diam volutpat commodo sed egestas. Viverra justo nec ultrices dui sapien. Ac placerat vestibulum lectus mauris ultrices eros in. At in tellus integer feugiat scelerisque. Neque gravida in fermentum et sollicitudin ac orci. Lectus mauris ultrices eros in. Turpis egestas maecenas pharetra convallis posuere morbi. Facilisis magna etiam tempor orci eu.')),
              SizedBox(height: 10,),
              Image.network('https://picsum.photos/1400/800'),
              Text('List item 40'),
              SizedBox(height: 30,),
              SelectionArea(child: Text('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet eget sit amet tellus cras adipiscing enim eu. In iaculis nunc sed augue lacus. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique senectus. Fringilla urna porttitor rhoncus dolor purus non. Nulla facilisi cras fermentum odio. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. Amet dictum sit amet justo donec enim diam vulputate ut. Fermentum iaculis eu non diam phasellus vestibulum lorem sed.\n\nMagna eget est lorem ipsum dolor. A diam maecenas sed enim. Vehicula ipsum a arcu cursus. Nisi quis eleifend quam adipiscing vitae proin sagittis. Ullamcorper velit sed ullamcorper morbi. Viverra suspendisse potenti nullam ac tortor. Augue lacus viverra vitae congue eu consequat. Et odio pellentesque diam volutpat commodo sed egestas. Viverra justo nec ultrices dui sapien. Ac placerat vestibulum lectus mauris ultrices eros in. At in tellus integer feugiat scelerisque. Neque gravida in fermentum et sollicitudin ac orci. Lectus mauris ultrices eros in. Turpis egestas maecenas pharetra convallis posuere morbi. Facilisis magna etiam tempor orci eu.')),
              SizedBox(height: 10,),
            ],
            ),
      );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>

Screenshots / Video demonstration</summary>

## Broken on version 3.23.  
Problem can be seen at :02, :05, :10, :13

https://github.com/flutter/flutter/assets/87546778/5514274d-1c87-4053-b7d3-ae5d770678fa

## Working smoothly on version 3.22.

https://github.com/flutter/flutter/assets/87546778/29552e12-e0aa-49f8-bb87-9757664b8881

  
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.23.0-13.0.pre.357 • channel master • https://github.com/flutter/flutter.git
Framework • revision 805d79607e (24 minutes ago) • 2024-06-27 05:53:58 +0200
Engine • revision a9194f0f01
Tools • Dart 3.5.0 (build 3.5.0-304.0.dev) • DevTools 2.36.0

```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Fixes #150897

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by Renzo-Olivares** [comment]
Friendly bump for review.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 1]
```diff
@@ -535,30 +535,60 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
   }
 
   void _initMouseGestureRecognizer() {
-    switch (defaultTargetPlatform) {
-      case TargetPlatform.android:
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:539]: nice clean up. I wonder why we have the switch case before

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 2]
```diff
@@ -535,30 +535,60 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
...
+          ..dragStartBehavior = DragStartBehavior.down;
+      },
+    );
   }
 
   void _initTouchGestureRecognizer() {
+    // A [TapAndHorizontalDragGestureRecognizer] is used on non-precise pointer devices
+    // like PointerDeviceKind.touch so [SelectableRegion] gestures do not conflict with
+    // ancestor Scrollable gestures in common scenarios like a vertically scrolling list view.
+    _gestureRecognizers[TapAndHorizontalDragGestureRecognizer] = GestureRecognizerFactoryWithHandlers<TapAndHorizontalDragGestureRecognizer>(
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:560]: does the touch gesture support drag selection without tapping the selection gesture?

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:560]: Do you mean a single tap followed by a drag? Touch devices do not support this only mouse. There is an existing check that looks for this https://github.com/flutter/flutter/blob/b9e4416ad358892a24fb4f50a56ce1b0b3a54260/packages/flutter/lib/src/widgets/selectable_region.dart#L632-L636 and https://github.com/flutter/flutter/blob/b9e4416ad358892a24fb4f50a56ce1b0b3a54260/packages/flutter/lib/src/widgets/selectable_region.dart#L644-L648 .

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:539]: Yeah I think I just forgot to remove it.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 2 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:560]: will using this gesture recognizer causes weirdness when user tap and vertical select? Base on reading the doc it looks like it would only accept horizontal drag first before winning the arena.

If the issue is with the slop, could we fix the vertical conflict by increase or decrease the tapandPanGestureRecognizer as well?

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:560]: It shouldn't cause weirdness with tap and vertical select, for example in the case of a double tap + vertical drag on Android or iOS, the `TapAndHorizontalDragGestureRecognizer` will declare victory on a consecutive tap https://github.com/flutter/flutter/blob/22a5c6cb0a906c219e360ab72da0935aa7a18b93/packages/flutter/lib/src/gestures/tap_and_drag.dart#L1322-L1327, so when the drag happens the recognizer has already won and will accept the drag in any direction.

I think the more we increase the slop the less responsive the selection gesture will feel. I don't think this is ideal since selection gestures will not always be used in a Scrollable. I explored this method with `TextField`s when fixing a similar issue and found it to be fragile.

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:560]: sounds good to me then.

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by mark8044** [comment]
Itching to get this onto my app for testing, how does it get past the Google testing?
