### PR TITLE
[Material] Relanding fix to ensure time picker input mode lays out correctly in RTL

### LINKED ISSUE #63427: Wrong hour/minute order in timePicker in RTL mode
Hour and Minute order are wrong in RTL mode. It is just reversed from left -> right to right -> left.
Hour view is same in both RTL and LTR meaning hour comes on the left and minute comes on the right.  
To reproduce the problem set ``locale`` in ``MaterialApp`` to an rtl locale (like ``Locale('fa')``); and call ``showTimePicker(context:context, initialTime: TimeOfDay.now());``
screenshot-2020-08-11_01 50 05 949

### PR DESCRIPTION
**Pull request by rami-a**
## Description

This is re-landing https://github.com/flutter/flutter/pull/63599 and it ensures that the hours and minutes are laid out correctly for RTL for the time picker input mode.

In the previous PR, the ":" separator became vertically offset from the hours and minutes because of the addition of a nested `Row` widget that didn't specify the crossAxisAlignment appropriately. So it was reverted in https://github.com/flutter/flutter/pull/64094. This PR adds a fix for that.

## Related Issues

Fixes #63427

## Tests

I added the following tests:

- a test to check the position of elements in various locales including an RTL one
- a regression test to check the position of the separator compared to the hour/minute text fields

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/material/time_picker_test.dart [hunk 1]
```diff
@@ -806,6 +806,14 @@ void _testsInput() {
     await finishPicker(tester);
     expect(result, equals(const TimeOfDay(hour: 8, minute: 15)));
   });
+
+  // Fixes regression that was reverted in https://github.com/flutter/flutter/pull/64094#pullrequestreview-469836378.
+  testWidgets('Ensure hour/minute fields are top-aligned with the separator', (WidgetTester tester) async {
+    await startPicker(tester, (TimeOfDay time) { }, entryMode: TimePickerEntryMode.input);
+    final double hourFieldTop = tester.getTopLeft(find.byWidgetPredicate((Widget w) => '${w.runtimeType}' == '_HourTextField')).dy;
+    final double separatorTop = tester.getTopLeft(find.byWidgetPredicate((Widget w) => '${w.runtimeType}' == '_StringFragment')).dy;
```
Comment (HansMuller) [inline packages/flutter/test/material/time_picker_test.dart:814]: Should we be checking the _MinuteTextField as well?

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/test/material/time_picker_test.dart (hunk 1 above)
Comment (rami-a) [reply packages/flutter/test/material/time_picker_test.dart:814]: Good point, yeah we might as well

**Review by johnsonmh — APPROVED** [review]
LGTM

**Review by perclasson — COMMENTED** [review]
LGTM

**Review by perclasson — APPROVED** [review]
