### PR TITLE
explicitly catch ArgumentError in `exitsHappy()`, and add tests

### LINKED ISSUE #52702: Crash in 'flutter create' (?)
@christopherfujino This is on `dev/1.15.21` with a command `create --ios-language swift --android-language kotlin .`. Maybe there is a bad interaction when the artifacts are incomplete in `FlutterCommand.verifyAndRunCommand()` ?

```
ArgumentError: Invalid argument(s): Cannot find executable for E:\[...]\bin\cache\artifacts\libimobiledevice\idevicescreenshot
  | at _getExecutable | (local_process_manager.dart:127 )
  | at LocalProcessManager.runSync | (local_process_manager.dart:94 )
  | at _DefaultProcessUtils.exitsHappySync | (process.dart:541 )
  | at IMobileDevice.isInstalled | (mac.dart:39 )
  | at IOSWorkflow.canListDevices | (ios_workflow.dart:20 )
  | at IOSDevices.canListAnything | (devices.dart:38 )
  | at DeviceManager.canListAnything.<anonymous closure> | (device.dart:150 )
  | at Iterable.any | (iterable.dart:388 )
  | at DeviceManager.canListAnything | (device.dart:150 )
  | at _DefaultDoctorValidatorsProvider.validators | (doctor.dart:99 )
  | at Doctor.validators | (doctor.dart:158 )
  | at Doctor.startValidatorTasks | (doctor.dart:164 )
  | at Doctor.diagnose | (doctor.dart:270 )
  | at CreateCommand.runCommand | (create.dart:493 )
  | at _rootRunUnary | (zone.dart:1134 )
  | at _CustomZone.runUnary | (zone.dart:1031 )
  | at _FutureListener.handleValue | (future_impl.dart:140 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:682 )
  | at Future._propagateToListeners | (future_impl.dart:711 )
  | at Future._completeWithValue | (future_impl.dart:526 )
  | at _AsyncAwaitCompleter.complete | (async_patch.dart:34 )
  | at _completeOnAsyncReturn | (async_patch.dart:293 )
  | at CreateCommand._generateApp | (create.dart )
  | at _rootRunUnary | (zone.dart:1134 )
  | at _CustomZone.runUnary | (zone.dart:1031 )
  | at _FutureListener.handleValue | (future_impl.dart:140 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:682 )
  | at Future._propagateToListeners | (future_impl.dart:711 )
  | at Future._completeWithValue | (future_impl.dart:526 )
  | at _AsyncAwaitCompleter.complete | (async_patch.dart:34 )
  | at _completeOnAsyncReturn | (async_patch.dart:293 )
  | at FlutterProject.ensureReadyForPlatformSpecificTooling | (project.dart )
  | at _rootRunUnary | (zone.dart:1134 )
  | at _CustomZone.runUnary | (zone.dart:1031 )
  | at _FutureListener.handleValue | (future_impl.dart:140 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:682 )
  | at Future._propagateToListeners | (future_impl.dart:711 )
  | at Future._completeWithValue | (future_impl.dart:526 )
  | at _AsyncAwaitCompleter.complete | (async_patch.dart:34 )
  | at _completeOnAsyncReturn | (async_patch.dart:293 )
  | at injectPlugins | (plugins.dart )
  | at _rootRunUnary | (zone.dart:1134 )
  | at _CustomZone.runUnary | (zone.dart:1031 )
  | at _FutureListener.handleValue | (future_impl.dart:140 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:682 )
  | at Future._propagateToListeners | (future_impl.dart:711 )
  | at Future._completeWithValue | (future_impl.dart:526 )
  | at Future._asyncComplete.<anonymous closure> | (future_impl.dart:556 )
  | at _rootRun | (zone.dart:1126 )
  | at _CustomZone.run | (zone.dart:1023 )
  | at _CustomZone.runGuarded | (zone.dart:925 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:965 )
  | at _microtaskLoop | (schedule_microtask.dart:43 )
  | at _startMicrotaskLoop | (schedule_microtask.dart:52 )
  | at _runPendingImmediateCallback | (isolate_patch.dart:118 )
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:169 )
```

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

After https://github.com/flutter/flutter/pull/52021, `exitsHappy()` and `exitsHappySync()` only catch `Exception`s but not `ArgumentError`s, such as when the command being invoked doesn't exist. This PR explicitly catches `ArgumentError`.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/52702

## Tests

I added tests for both `exitsHappy()` and `exitsHappySync()` that it catches both `Exception`s and `ArgumentError`s.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
thanks!

File: packages/flutter_tools/lib/src/base/process.dart [hunk 1]
```diff
@@ -542,6 +542,9 @@ class _DefaultProcessUtils implements ProcessUtils {
     } on Exception catch (error) {
       _logger.printTrace('$cli failed with $error');
       return false;
+    } on ArgumentError catch (error) {
```
Comment (dnfield) [inline packages/flutter_tools/lib/src/base/process.dart]: Why are we even calling it in this case?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/process.dart]: Sometimes we call `exitsHappy` to verify if the binary exists, e.g. https://github.com/flutter/flutter/blob/071d4eb2c8cb20f2f28c0740046ecfae69e5c7ae/packages/flutter_tools/lib/src/ios/mac.dart#L38

Comment (dnfield) [reply packages/flutter_tools/lib/src/base/process.dart]: Ahhh ok, I see now, and we're catching `ArgumentError` from `_processManager`.  Is this more reliable than just calling https://api.flutter.dev/flutter/package-process_process/ProcessManager/canRun.html?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/process.dart]: Not more reliable, but I think also not less reliable(?) The goal with `processUtils` was to have a small, concise API surface.

Comment (dnfield) [reply packages/flutter_tools/lib/src/base/process.dart]: Yes, I mean we could call that in here first and return false if it's false, rather than trying to catch an argument exception.  That way if some other code starts throwing that we don't end up swallowing the unrelated exception.

Comment (dnfield) [reply packages/flutter_tools/lib/src/base/process.dart]: i.e. on line 541 of this file (or maybe line 539), `if (!_processManager.canRun(cli.first), environment: environment)) { return false; }` - probably also with either asserts or guards against `cli` being null or empty.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/process.dart]: Oh, I see what you mean

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/process.dart]: That would be changing what this function does slightly, however, by discarding the arguments.

Comment (zanderso) [reply packages/flutter_tools/lib/src/base/process.dart]: `DeviceManager.canListAnything` should probably check `discoverer.supportsPlatform` before querying `discoverer.canListAnything`.  The similar code in `EmulatorManager` in emulator.dart probably needs a similar fix. (Sorry for not suggesting this earlier, but the fix in this PR was needed as well.)

Comment (dnfield) [reply packages/flutter_tools/lib/src/base/process.dart]: RE discarding arguments - after checking `canRun`, you can still use the existing logic, but avoid trying to catch an argument error.  

My concern with catching argument error is that it can be thrown for a number of reasons, including errors in the upstream code (e.g. someone accidentally makes the string null, or passes in an empty array).
