### PR TITLE
Transition Curve Fix

### LINKED ISSUE #20405: Mid transition route push/pop curve is wrong in CupertinoPageRoute
The page route has asymmetrical curves. Pushing a route then popping the route halfway into the animation causes the sliding edge to jump. We need to reverse the exact same curve instead of using the reverse curve.

### PR DESCRIPTION
**Pull request by jslavitz**
Better replicates the pushing and popping animation of routes on iOS. Also fixes #20405.

### CODE REVIEW

**Comment by xster** [comment]
Can you check the CI tests?

File: packages/flutter/lib/src/cupertino/route.dart [hunk 1]
```diff
@@ -4,14 +4,18 @@
...
 
 import 'package:flutter/foundation.dart';
 import 'package:flutter/gestures.dart';
 import 'package:flutter/rendering.dart';
 import 'package:flutter/widgets.dart';
+import 'package:flutter/animation.dart' show Curves;
 
 const double _kBackGestureWidth = 20.0;
 const double _kMinFlingVelocity = 1.0; // Screen widths per second.
+const int _kMaxPageForwardAnimationTime = 800; // Milliseconds.
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/route.dart]: Document where these values came from. (just saying they're eyeballed is fine too)

File: packages/flutter/lib/src/cupertino/route.dart [hunk 2]
```diff
@@ -152,7 +156,7 @@ class CupertinoPageRoute<T> extends PageRoute<T> {
   final bool maintainState;
 
   @override
-  Duration get transitionDuration => const Duration(milliseconds: 350);
+  Duration get transitionDuration => const Duration(milliseconds: 400);
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/route.dart]: ditto

File: packages/flutter/lib/src/cupertino/route.dart [hunk 3]
```diff
@@ -348,18 +352,18 @@ class CupertinoPageTransition extends StatelessWidget {
        _primaryPositionAnimation = (linearTransition ? primaryRouteAnimation :
          CurvedAnimation(
            parent: primaryRouteAnimation,
-           curve: Curves.easeOut,
-           reverseCurve: Curves.easeIn,
+           curve: Curves.linearToEaseOut,
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/route.dart]: ditto

Comment (jslavitz) [reply packages/flutter/lib/src/cupertino/route.dart]: To be honest, without a rigorous check comparing frames between native iOS and our Cupertino implementation, it's hard to say for sure which curve is the most accurate. Looking at a recording of native iOS frames, it seemed to me that a linear to ease curve was the most accurate. However, we are planning on making a framework to do native vs flutter testing in the future. 

Also, if you are testing this code, make sure you test in release mode as the animations feel quite different than they do in debug mode.

Comment (marcoms) [reply packages/flutter/lib/src/cupertino/route.dart]: With a bit too much time on my hands :smile: , I [plotted the frames](https://plot.ly/~marcoms/1) of a screen recording I made on my iPhone. The raw data is the following (measured with a ruler and lerp'd):

```
0
0.121212
0.208588
0.339393
0.442424
0.533333
0.618181
0.690909
0.751515
0.842424
0.878787
0.903030
0.921212
0.939393
0.951515
0.963636
0.969696
0.975757
0.981818
0.987878
0.990909
0.992424
0.993939
0.996969
1
```

Actually you're right that it is more of a linear curve followed by an ease out (and 400ms is about right too). The only difference is the native curve is fairly steeper.

Here it is modeled on cubic-bezier.com: http://cubic-bezier.com/#.35,.91,.33,.97

Hopefully plugging that into `Cubic()` will get us feeling more native. My only concern is whether Apple internally uses a parameterized curve that changes depending on the UI element :/

Comment (marcoms) [reply packages/flutter/lib/src/cupertino/route.dart]: With a bit too much time on my hands :smile: , I [plotted the frames](https://plot.ly/~marcoms/1) of a screen recording I made on my iPhone. The raw data is the following (measured with a ruler and lerp'd):

```
0
0.121212
0.208588
0.339393
0.442424
0.533333
0.618181
0.690909
0.751515
0.842424
0.878787
0.903030
0.921212
0.939393
0.951515
0.963636
0.969696
0.975757
0.981818
0.987878
0.990909
0.992424
0.993939
0.996969
1
```

Actually you're right that it is more of a linear curve followed by an ease out (and 400ms is about right too). The only difference is the native curve is fairly steeper.

Here it is modeled on cubic-bezier.com: http://cubic-bezier.com/#.35,.91,.33,.97

Hopefully plugging that into `Cubic()` will get us feeling more native. My only concern is whether Apple internally uses a parameterized curve that changes depending on the UI element :/

Comment (jslavitz) [reply packages/flutter/lib/src/cupertino/route.dart]: Wow! That's awesome! Thanks for doing that! I'll add that function and see how it feels!

And by eyeball estimation, it looked like all their transition curves are the same across all their apps, tho it's hard to say absolutely for sure without checking. What I did notice tho is that the curve they use for animating a page back or forward if you release mid drag is different than the animation they use for when you tap a button to show a page.

Again, thanks for verifying this ! 😊

File: packages/flutter/lib/src/animation/animation_controller.dart [hunk 4]
```diff
@@ -487,6 +487,23 @@ class AnimationController extends Animation<double>
     return _animateToInternal(target, duration: duration, curve: curve);
   }
 
+  /// Drives the animation from its current value to target.
```
Comment (xster) [inline packages/flutter/lib/src/animation/animation_controller.dart]: Reading this file in order. So far I'm a bit skeptical about adding new APIs at this low level since it seems like it's the same as [reverse] and the curve can come from the Animation being driven.

File: packages/flutter/lib/src/animation/curves.dart [hunk 5]
```diff
@@ -512,6 +511,15 @@ class Curves {
...
   static const Curve decelerate = _DecelerateCurve._();
 
+  /// A curve that is very steep and linear at the beginning, but quickly flattens out
+  /// and very slowly eases in.
+  ///
+  /// By default is the curve used to animate pages on iOS back to their original
+  /// position if a swipe gesture is ended midway through a swipe.
+  ///
+  /// {http://cubic-bezier.com/#.22,.99,.08,1}
+  static const Cubic fastLinearToSlowEaseIn = Cubic(0.18, 1.0, 0.04, 1.0);
```
Comment (xster) [inline packages/flutter/lib/src/animation/curves.dart]: there's a lot of subjective adjectives here. What each person can mentally visualize this to be can be very different.

File: packages/flutter/lib/src/animation/curves.dart [hunk 6]
```diff
@@ -522,6 +530,11 @@ class Curves {
   /// {@animation 464 192 https://flutter.github.io/assets-for-api-docs/assets/animation/curve_ease_in.mp4}
   static const Cubic easeIn = Cubic(0.42, 0.0, 1.0, 1.0);
 
+  /// A cubic animation curve that starts starts slowly and ends linearly.
+  ///
+  /// The symmetric animation to [linearToEaseOut].
```
Comment (xster) [inline packages/flutter/lib/src/animation/curves.dart]: These ones seem better described. Remember to add an animation movie here and in the class doc. @dnfield has this fresh in his mind so he might be able to help.

File: packages/flutter/lib/src/cupertino/route.dart [hunk 7]
```diff
@@ -4,15 +4,25 @@
...
 import 'package:flutter/rendering.dart';
 import 'package:flutter/widgets.dart';
+import 'package:flutter/animation.dart' show Curves;
 
 const double _kBackGestureWidth = 20.0;
 const double _kMinFlingVelocity = 1.0; // Screen widths per second.
 
+// An eyeballed value for the maximum time it takes for a page to animate forward
+// if the user releases a page mid swipe.
+const int _kMaxPageForwardAnimationTime = 800; // Milliseconds.
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/route.dart]: The name should somehow reflect the special nature of it (only on dropped swipes)

File: packages/flutter/lib/src/cupertino/route.dart [hunk 8]
```diff
@@ -346,20 +357,22 @@ class CupertinoPageTransition extends StatelessWidget {
     @required bool linearTransition,
   }) : assert(linearTransition != null),
        _primaryPositionAnimation = (linearTransition ? primaryRouteAnimation :
+       // The curves below have been rigorously derived from plots of native
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/route.dart]: As they get more and more certain, be more specific (i.e. stop frames filmed then measured on screen)

File: packages/flutter/lib/src/cupertino/route.dart [hunk 9]
```diff
@@ -346,20 +357,22 @@ class CupertinoPageTransition extends StatelessWidget {
...
+       // iOS animation frames.
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/route.dart]: alignment

File: packages/flutter/lib/src/cupertino/route.dart [hunk 10]
```diff
@@ -593,13 +606,32 @@ class _CupertinoBackGestureController<T> {
...
+
+    // If the user releases the page before mid screen with sufficient velocity,
+    // or after mid screen, we should animate the page out. Otherwise, the page
+    // should be animated back in.
+    if (velocity.abs() >= _kMinFlingVelocity)
+      animateForward = velocity > 0 ? false : true;
+    else
+      animateForward = controller.value > 0.5 ? true : false;
+
+    if (animateForward) {
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/route.dart]: Are we sure the curve is the same in either direction? Either way this PR is fine. I'm just wondering.

File: packages/flutter/lib/src/cupertino/route.dart [hunk 11]
```diff
@@ -593,13 +606,32 @@ class _CupertinoBackGestureController<T> {
...
+      // The closer the panel is to dismissing, the shorter the animation is.
+      // We want to cap the animation time, but we want to use a linear curve
+      // to determine it.
+      final int milliseconds = min(lerpDouble(_kMaxPageForwardAnimationTime, 0, controller.value).floor(),
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/route.dart]: we should call it something more descriptive than milliseconds

File: packages/flutter/lib/src/cupertino/route.dart [hunk 12]
```diff
@@ -593,13 +606,32 @@ class _CupertinoBackGestureController<T> {
...
+                                   _kMaxPageBackAnimationTime);
+      controller.animateTo(1.01, duration: Duration(milliseconds: milliseconds), curve: animationCurve);
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/route.dart]: oh I see. Why 1.01? This definitely needs some code comments

File: packages/flutter/test/cupertino/page_test.dart [hunk 13]
```diff
@@ -222,7 +228,7 @@ void main() {
     tester.state<NavigatorState>(find.byType(Navigator)).pushNamed('/next');
 
     await tester.pump();
-    await tester.pump(const Duration(milliseconds: 400));
+    await tester.pumpAndSettle();
```
Comment (xster) [inline packages/flutter/test/cupertino/page_test.dart]: I'd still keep a concrete number here. That the animation doesn't go on for 2s is still part of the 'test'.

File: packages/flutter/lib/src/animation/animation_controller.dart (hunk 4 above)
Comment (jslavitz) [reply packages/flutter/lib/src/animation/animation_controller.dart]: So, I mean, the core of the issue is that it is necessary that the animation direction is ```reverse```, and there's no way to do that using a custom animation with the functions that we currently have and the way the whole animation system is set up for the route, at least as far as I could tell. Tho maybe I'm missing something?

File: packages/flutter/lib/src/animation/curves.dart (hunk 5 above)
Comment (jslavitz) [reply packages/flutter/lib/src/animation/curves.dart]: I'm not sure how to make this easier to understand? I'm also linked the bezier curve so people can see exactly what it looks like by clicking on the link?

**Comment by marcoms** [comment]
One thing I forgot about from my old PR was that we still have to fix the curve for scrolling to the top of the screen by tapping on the status bar, as it's linear at the moment. I suppose you could use `linearToEaseOut` for that as well. This will fix #18586

One potential complication is that I think on iOS the duration changes depending on how much there is to scroll.

Relevant code is at `lib/src/material/scaffold.dart:1386`

**Comment by jslavitz** [comment]
@marcoms We can always add more curves if we need to. Good to know the scroll time is consistent!

**Comment by xster** [comment]
Let's do the status bar scroll in a separate PR. Thanks for looking at the timing @marcoms. Keep them coming :D

File: packages/flutter/lib/src/animation/animation_controller.dart (hunk 4 above)
Comment (xster) [reply packages/flutter/lib/src/animation/animation_controller.dart]: Talked offline. This is ok since we're already driving animation controllers non-linearly via calls to .fling etc.

File: packages/flutter/lib/src/cupertino/route.dart (hunk 10 above)
Comment (jslavitz) [reply packages/flutter/lib/src/cupertino/route.dart]: I'm like almost 100% sure. I just inverted the bezier points, it should be the reflected curve, but I did not verify my math checking the graphs or anything...

File: packages/flutter/lib/src/cupertino/route.dart (hunk 12 above)
Comment (jslavitz) [reply packages/flutter/lib/src/cupertino/route.dart]: So if you look at this: https://github.com/flutter/flutter/blob/649f49d4bfeed3f9bbcdaaf301da85fd91671f3c/packages/flutter/lib/src/animation/animation_controller.dart#L584, you can see that for fling they added or subtracted .01 from the value. So I thought it would make sense to do that for the replacement animation? But maybe that value is just so that the simulation finishes? You think it would be ok to remove the .01? I don't think the graphic difference is noticeable.

File: packages/flutter/lib/src/animation/curves.dart (hunk 5 above)
Comment (xster) [reply packages/flutter/lib/src/animation/curves.dart]: Not sure how publicly re-usable this is if we can't describe it in an objective way. I'd just leave this privately defined in route.dart.

File: packages/flutter/lib/src/cupertino/route.dart (hunk 12 above)
Comment (xster) [reply packages/flutter/lib/src/cupertino/route.dart]: They should have added a test :D. If we can't figure out why it was added, we should remove it.

File: packages/flutter/test/cupertino/nav_bar_transition_test.dart [hunk 14]
```diff
@@ -1171,17 +1169,11 @@ void main() {
     await gesture.up();
 
     await tester.pump();
-
     // Transition continues.
     expect(
       tester.getTopLeft(flying(tester, find.text('Page 2'))),
       const Offset(655.2055835723877, 13.5),
     );
-    await tester.pump(const Duration(milliseconds: 50));
```
Comment (xster) [inline packages/flutter/test/cupertino/nav_bar_transition_test.dart]: Is this intended?

File: packages/flutter/test/cupertino/page_test.dart [hunk 15]
```diff
@@ -285,15 +291,15 @@ void main() {
     );
 
     await tester.pump();
-    await tester.pump(const Duration(milliseconds: 400));
+    await tester.pumpAndSettle();
```
Comment (xster) [inline packages/flutter/test/cupertino/page_test.dart]: In general, we should check that all animations complete in some reasonable amount of time.

File: packages/flutter/test/cupertino/nav_bar_transition_test.dart [hunk 16]
```diff
@@ -1229,7 +1221,7 @@ void main() {
     await tester.pump(const Duration(milliseconds: 50));
     expect(
       tester.getTopLeft(flying(tester, find.text('Page 2'))),
-      const Offset(351.00985169410706, 13.5),
+      const Offset(350.0, 13.5),
     );
```
Comment (xster) [inline packages/flutter/test/cupertino/nav_bar_transition_test.dart]: There may be one already but make sure that there's a test that checks the animation when a back gesture is flung and dropped.

**Comment by xster** [comment]
LGTM

File: packages/flutter/lib/src/animation/curves.dart (hunk 5 above)
Comment (jslavitz) [reply packages/flutter/lib/src/animation/curves.dart]: I can totally do this, but I guess I'm unclear on how you're measuring a description's objectivity?

File: packages/flutter/test/cupertino/nav_bar_transition_test.dart (hunk 14 above)
Comment (jslavitz) [reply packages/flutter/test/cupertino/nav_bar_transition_test.dart]: Nope, thanks for catching that!

**Comment by marcoms** [comment]
Would it be possible to submit a PR for just `Curves.linearToEaseOut` in the meantime, so I could use it for other animation work like the status bar scroll?

**Comment by Hixie** [comment]
@jslavitz @xster Please also add the curves documentation to the Curves class, not just the properties. That makes them easier to compare. Thanks.

**Comment by Hixie** [comment]
(Incidentally, the assets for the new curves seem to be broken.)
