### PR TITLE
Use toPictureSync for faster zoom page transition

### LINKED ISSUE #100972: Improve the memory footprint of the zoom page transition
On https://github.com/flutter/flutter/commit/543a7e858828e721258b8fb9ded62d7a2ff05808, several flutter_gallery benchmarks are showing a 10-20MB regression in memory footprint.

https://flutter-flutter-perf.skia.org/e/?begin=1648252513&end=1648446610&keys=X845c9ddf84d6ac62deff51c6cee6ad22&num_commits=50&request_type=1&xbaroffset=28090

Weirdly, SkiaPerf flags the following commit, but it's pretty clear from the chart where the regression happened.

@dnfield @AlexV525

### LINKED ISSUE #104680: Determine a fix for the zoom page transition performance
The zoom page transition is the default page transition for Android, and used heavily by google customers and customer: money. Unfortunately, the raster performance of this transitions leaves a lot to be desired. Currently, the transition uses a FadeTransition and ScaleTransition. The changing scale factor essentially disables raster caching of child pictures, and apparently causes increases in native memory compared to the baseline transition: https://github.com/flutter/flutter/issues/100972

To solve this, we originally investigated switching from a ScaleTransition using a transform layer, to a ScaleTransition using an ImageFilterLayer with a ImageFilter.matrix. In theory, this should be faster than a transform layer for this case, since the pages aren't animated at all while the transition occurs and this allows a single raster cache entry to be used for the entire page (which can also absorb the opacity from the FadeTransition). While switching did improve memory consumption, it regressed worst frame raster performance by about 1.5x on our gallery benchmark (https://flutter-flutter-perf.skia.org/e/?begin=1650989645&end=1651012744&keys=X809a5f88fb68c1b259242471f65ee081&num_commits=50&request_type=1&xbaroffset=28565) . This is likely due to either the performance of Skia's ImageFilter, or perhaps specific to shader compilation for the first use of this filter.

Interestingly enough though, we accidentally rolled a version of flutter into google3 that used a ImageFilterLayer  🙃 and it significantly improved the performance of a number of customer money benchmarks. A "worst raster frame" benchmark improved from 104.7 ms to 41.75 ms.  A follow-up roll reverted the change and the benchmark regressed again. b/232993351

Its quite difficult to identify performance improvements that are as good as the above change, so I attempted a fix in the engine/raster cache to special case a scale transform matrix filter: https://github.com/flutter/engine/pull/33562 , but that stalled out since it conflicted with another refactor PR.
 
@xster @zanderso can you help determine how we should prioritize this?

### PR DESCRIPTION
**Pull request by jonahwilliams**
Rather than using transform layers, snap off a texture of the current/next route using toGpuImage, and then draw the scale/opacity operations using these images while the animation is ongoing.

Edit: Updated because I realized I was accidentally drawing one of the layers twice + dpr

### Pixel 6

<html>
<body>

  | toGpuImage | ToT |   | Delta
-- | -- | -- | -- | --
average_frame_rasterizer_time_millis | 2.704333333 | 6.932666667 |   | 4.228333333
90th_percentile_frame_rasterizer_time_millis | 3.108333333 | 13.91833333 |   | 10.81
99th_percentile_frame_rasterizer_time_millis | 13.19466667 | 21.64666667 |   | 8.452
worst_frame_rasterizer_time_millis | 16.031 | 24.299 |   | 8.268

</body>
</html>

### Wembly

<html>
<body>

  | toGpuImage | ToT |   | Delta
-- | -- | -- | -- | --
average_frame_rasterizer_time_millis | 6.576966868 | 10.93125447 |   | 4.354287606
90th_percentile_frame_rasterizer_time_millis | 8.874 | 15.01333333 |   | 6.139333333
99th_percentile_frame_rasterizer_time_millis | 10.67266667 | 20.96766667 |   | 10.295
worst_frame_rasterizer_time_millis | 33.301 | 39.167 |   | 5.866

</body>
</html>

Fixes https://github.com/flutter/flutter/issues/104680
Fixes https://github.com/flutter/flutter/issues/100972

### CODE REVIEW

**Comment by jonahwilliams** [comment]
FYI @dnfield , this is awesome

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 1]
```diff
@@ -250,18 +253,137 @@ class _ZoomPageTransition extends StatelessWidget {
   }
 }
 
-class _ZoomEnterTransition extends StatelessWidget {
+abstract class _RadicallyAwesomeRenderObject extends RenderProxyBox {
```
Comment (dnfield) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:256]: https://c.tenor.com/sjL3PoQE7OQAAAAM/thats-rad-sarcastic.gif

**Comment by jonahwilliams** [comment]
Ahh shit, web

**Comment by jonahwilliams** [comment]
Updated numbers with pixel 6 benchmark, the improvement is even more dramatic, partially due to a new benchmark I wrote which isolates the page transition better

**Comment by jonahwilliams** [comment]
The fidelity of this is a little off, but promising results so far. Hopefully fixing the fidelity doesn't tank the performance...

File: dev/integration_tests/flutter_gallery/test_driver/page_transition_perf_test.dart [hunk 2]
```diff
@@ -0,0 +1,39 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'package:flutter_driver/flutter_driver.dart';
+import 'package:test/test.dart' hide TypeMatcher, isInstanceOf;
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply dev/integration_tests/flutter_gallery/test_driver/page_transition_perf_test.dart:6]: Don't remember, its just a copy paste from the other test

[the remark this answers is not in the document]
Comment (dnfield) [reply dev/integration_tests/flutter_gallery/test_driver/page_transition_perf_test.dart:6]: I believe it causes type definition clashes because flutter_test defined this before it was availalbe in package:test or something.

**Comment by jonahwilliams** [comment]
I also investigated total frame count after @dnfield raised some concerns about potentially hidden costs of toGpuImage. I found that with toGpuImage, the attached benchmark pumps about 208 frames. With the old version, we get about 65 frames - on a pixel 6.

**Comment by jonahwilliams** [comment]
Flutter DevTools - Google Chrome 6_27_2022 1_34_24 PM

I'm observing some odd GC behavior, it seems to trigger consistently when calling toGpuImage

**Comment by jonahwilliams** [comment]
Filled https://github.com/flutter/flutter/issues/106698

File: packages/flutter/lib/src/widgets/animated_raster.dart [hunk 3]
```diff
@@ -0,0 +1,215 @@
...
+      case AnimationStatus.completed:
+        super.paint(context, offset);
+        return;
+      case AnimationStatus.forward:
+      case AnimationStatus.reverse:
+        break;
+    }
+    final bool updateImage = delegate.willPaint(animation);
+    if (_childImage == null && updateImage) {
+      _childImage = PaintingContext.paintAndDetachToGpuImage(
```
Comment (fzyzcjy) [inline packages/flutter/lib/src/widgets/animated_raster.dart:198]: Will we have trouble if the children is changing during animation? For example, there may be a loading indicator that is animating during this zoom page transition. Or there may be a splash effect happening because user has just tapped a button.

In those cases, the content (i.e. childImage) actually should be updated, but we are caching it and never update it except when animation status changes.

Therefore, users may see the loading indicator or splash "freezed" during this zoom IMHO.

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/animated_raster.dart:198]: That is a price I am willing to pay

Comment (fzyzcjy) [reply packages/flutter/lib/src/widgets/animated_raster.dart:198]: I agree. But maybe we should have some flags allowing users to customize it? Or maybe some documentation saying this is expected behavior - or people may file a bug about it

Comment (dnfield) [reply packages/flutter/lib/src/widgets/animated_raster.dart:198]: @goderbauer did we ever change route transitions to turn the ticker mode off, or was that just in customer: money's app?

Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/animated_raster.dart:198]: I suspect that would not have improved raster performance at all for zoom page, given that the scale transform would invalidate all raster caches

Comment (dnfield) [reply packages/flutter/lib/src/widgets/animated_raster.dart:198]: It was for the opacity one. Animation was busting the raster caching there

File: packages/flutter/lib/src/rendering/layer.dart [hunk 4]
```diff
@@ -1425,6 +1425,47 @@ class OffsetLayer extends ContainerLayer {
...
+    assert(pixelRatio != null);
+    final ui.SceneBuilder builder = ui.SceneBuilder();
+    final Matrix4 transform = Matrix4.translationValues(
+      (-bounds.left  - offset.dx) * pixelRatio,
+      (-bounds.top - offset.dy) * pixelRatio,
+      0.0,
+    );
+    transform.scale(pixelRatio, pixelRatio);
+    builder.pushTransform(transform.storage);
+    final ui.Scene scene = buildScene(builder);
```
Comment (dnfield) [inline packages/flutter/lib/src/rendering/layer.dart:1456]: nit: consider factoring to a common private method shared with toImage

File: packages/flutter/lib/src/rendering/layer.dart [hunk 5]
```diff
@@ -1425,6 +1425,47 @@ class OffsetLayer extends ContainerLayer {
       scene.dispose();
     }
   }
+
+  /// Capture an image of the current state of this layer and its children.
+  ///
+  /// The returned [ui.Image] has uncompressed raw RGBA bytes, will be offset
```
Comment (dnfield) [inline packages/flutter/lib/src/rendering/layer.dart:1431]: Some of this documentation si shared with `toImage` and we should probably have a template for it.

These docs should mention something about the difference between this method and `toImage`.

File: packages/flutter/lib/src/rendering/object.dart [hunk 6]
```diff
@@ -82,6 +82,22 @@ class PaintingContext extends ClipContext {
   /// The [estimatedBounds] rectangle is in the [canvas] coordinate system.
   final Rect estimatedBounds;
 
+  /// Paint [child] with this painting context, then convert to a raster and detach all
+  /// children from this layer.
+  static ui.Image paintAndDetachToGpuImage(OffsetLayer layer, {
```
Comment (dnfield) [inline packages/flutter/lib/src/rendering/object.dart:87]: Why is this needed?

If you have an offset layer, why not just call `layer.toGpuImage`? If it's not the offset layer that is already composited for this subtree, why are we asking you for it at all?

Comment (dnfield) [reply packages/flutter/lib/src/rendering/object.dart:87]: Alternative question: should this really just be call to `PaintingContext.repaintCompositedChild`, which knows how track whether this layer has already been composited or not?

**Review by dnfield — COMMENTED** [review]
I like this.

I think we need to figure out what to do about people who try to play animations during transitions. We may need an escape hatch for them - some parameter that can be passed to the route to say "do this the slow way so that an animation can try to play every frame."

That said, it's probably almost never a good idea to do that. We should at least document the behavior though.

File: packages/flutter/lib/src/rendering/object.dart (hunk 6 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/rendering/object.dart:87]: Its possible I could make this work by calling super.paint with a locally constructed PaintingContext as well, but this seems useful because there are a few gotchas.  Its important that the detach is added as well, otherwise you may draw things twice.  

Calling `PaintingContext.repaintCompositedChild` would be a re-entrant call to the same render object. If we wanted to use that we'd need to have the animated raster RO create two layers.

**Comment by jonahwilliams** [comment]
> I think we need to figure out what to do about people who try to play animations during transitions. We may need an escape hatch for them - some parameter that can be passed to the route to say "do this the slow way so that an animation can try to play every frame."

> That said, it's probably almost never a good idea to do that. We should at least document the behavior though.

Do we want to add an API that we wouldn't want people to use? I agree with documentation. Probably on the theme builder itself to start

File: packages/flutter/lib/src/rendering/layer.dart (hunk 4 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/rendering/layer.dart]: done

File: packages/flutter/lib/src/rendering/layer.dart (hunk 5 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/rendering/layer.dart:1435]: Added some more details. I don't think it would be right to describe this as containing uncompressed raw RGBA bytes since this is a GPU resident texture, right?

File: packages/flutter/lib/src/widgets/animated_raster.dart [hunk 7]
```diff
@@ -0,0 +1,215 @@
...
+/// While the status of [animation] is [AnimationStatus.completed] or
+/// [AnimationStatus.dismissed], children are painted normally. When the status
+/// is [AnimationStatus.forward] or [AnimationStatus.reverse], this render object
+/// will create a GPU resident texture the first time that [AnimatedRasterDelegate.willPaint] returns true
+/// and provide it to [AnimatedRasterDelegate.paint].
+///
+/// See also:
+///  * [ZoomPageTransitionsBuilder], which uses this render object to implement the fade and
+///    stretch effect efficiently.
+class RenderAnimatedRaster extends RenderProxyBox {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/animated_raster.dart:90]: Can/should this render object be private?

File: packages/flutter/lib/src/rendering/layer.dart (hunk 5 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/layer.dart:1435]: Yeah it may be BGRA depending on the platform. It's less important what the byte format is here.

File: packages/flutter/lib/src/widgets/animated_raster.dart [hunk 8]
```diff
@@ -0,0 +1,215 @@
...
+  /// Create a new [RenderAnimatedRaster].
+  RenderAnimatedRaster(this._animation, this._delegate, this._devicePixelRatio) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/animated_raster.dart:92]: nit: by convention these should be named arguments (if this remains public)

File: packages/flutter/lib/src/widgets/animated_raster.dart [hunk 9]
```diff
@@ -0,0 +1,215 @@
...
+    animation.addListener(markNeedsPaint);
+    animation.addStatusListener(_updateStatus);
+    _updateStatus(animation.status);
+  }
+
+  AnimationStatus _status = AnimationStatus.completed;
+
+  void _updateStatus(AnimationStatus newStatus, [bool painting = false]) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/animated_raster.dart:100]: nit: use named parameter for "painting" to make callsites easier to read.

File: packages/flutter/lib/src/widgets/animated_raster.dart [hunk 10]
```diff
@@ -0,0 +1,215 @@
...
+    animation.removeStatusListener(_updateStatus);
+    _childImage?.dispose();
+    _childImage = null;
+    super.dispose();
+  }
+
+  @override
+  void attach(covariant PipelineOwner owner) {
+    animation.addListener(markNeedsPaint);
+    animation.addStatusListener(_updateStatus);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/animated_raster.dart:164]: Arn't these listeners now added twice? Once in the constructor and again on attach?

File: packages/flutter/lib/src/widgets/animated_raster.dart [hunk 11]
```diff
@@ -0,0 +1,215 @@
...
+    switch (_status) {
+      case AnimationStatus.dismissed:
+      case AnimationStatus.completed:
+        super.paint(context, offset);
+        return;
+      case AnimationStatus.forward:
+      case AnimationStatus.reverse:
+        break;
+    }
+    final bool updateImage = delegate.willPaint(animation);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/animated_raster.dart:196]: uber-nit: `updateImage` is a little misleading since it controls whether paint is called?

File: packages/flutter/lib/src/widgets/animated_raster.dart (hunk 3 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/animated_raster.dart:198]: > did we ever change route transitions to turn the ticker mode off, or was that just in customer: money's app?

We did not change TIckerModes with regards to transitions anywhere. We changed that changes in TickerMode don't cause unnecessary rebuilds in - mostly hidden - routes.

**Comment by jonahwilliams** [comment]
I suppose if its not the default then its probably fine, and we need to keep the old one around for html anyway

File: packages/flutter/lib/src/widgets/animated_raster.dart (hunk 3 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/animated_raster.dart:198]: > That is a price I am willing to pay

I am going back and forth on this. On the one hand, this is also how iOS handles transitions, I believe. On the other hand, this was a cool feature of flutter that we could do animations while transitioning...

At the very least, we need to document this behavior somewhere. I also wonder if we need a flag to opt out of this behavior?

One example where you absolutely want animations to run during transitions are Hero animations. It's the whole point of a Hero that they fly around while you transition between routes. How does this change affect Heros? (Maybe they are unaffected, because the Hero is placed in a separate Overlay?)

Also, there are transitions where when you trigger them manually (e.g. by swiping back) things actually animate on the screen (e.g. a back-arrow animates back to a Hamburger Menu button). Are any of these use cases impacted?

**Review by goderbauer — COMMENTED** [review]
not a full review, only looked at `animated_raster.dart` so far, still want to look at the other files.

File: packages/flutter/lib/src/rendering/object.dart [hunk 12]
```diff
@@ -82,6 +82,22 @@ class PaintingContext extends ClipContext {
   /// The [estimatedBounds] rectangle is in the [canvas] coordinate system.
   final Rect estimatedBounds;
 
+  /// Paint [child] with this painting context, then convert to a raster and detach all
+  /// children from this layer.
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/object.dart:86]: This documentation could be a little more extensive. One thing to mention would be that the caller is responsible for actually drawing the returned image. Otherwise my understanding is that it will no show up, which may not what people expect from a method that's called "paint".

File: packages/flutter/lib/src/rendering/layer.dart [hunk 13]
```diff
@@ -1402,17 +1416,7 @@ class OffsetLayer extends ContainerLayer {
   ///  * [RenderRepaintBoundary.toImage] for a similar API at the render object level.
   ///  * [dart:ui.Scene.toImage] for more information about the image returned.
   Future<ui.Image> toImage(Rect bounds, { double pixelRatio = 1.0 }) async {
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/layer.dart:1418]: Link from this doc to `toGpuImage` and briefly point out how they are different?

File: packages/flutter/lib/src/rendering/layer.dart [hunk 14]
```diff
@@ -1425,6 +1429,40 @@ class OffsetLayer extends ContainerLayer {
       scene.dispose();
     }
   }
+
+  /// Capture an image of the current state of this layer and its children.
+  ///
+  /// The returned [ui.Image] will be offset by the top-left corner of [bounds],
+  /// and have dimensions equal to the size of [bounds] multiplied by [pixelRatio].
+  ///
+  /// Unlike [toImage], this creates a GPU-resident texture which has a backend
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/layer.dart:1438]: This paragraph sort-of leaves me as a developer wondering when I should use this over the other. Can we add some guidance?

**Comment by jonahwilliams** [comment]
> I am going back and forth on this. On the one hand, this is also how iOS handles transitions, I believe. On the other hand, this was a cool feature of flutter that we could do animations while transitioning...

Today I can't run a zoom page transition at 90hz on a Pixel 6. Maybe supporting animation was okay for the relatively cheap slide in transitions, but visible jank even on top of the line phones is _terrible_

I agree we shouldn't break heroes or other transitions, but as long as they don't use the ZoomPageTransition they should be unaffected.

> Also, there are transitions where when you trigger them manually (e.g. by swiping back) things actually animate on the screen (e.g. a back-arrow animates back to a Hamburger Menu button). Are any of these use cases impacted?

Do you have an example of this? I think I've seen those before. It may not work

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 15]
```diff
@@ -368,6 +491,42 @@ class _ZoomExitTransition extends StatelessWidget {
...
+      : 1.0;
+    return fade != 0.0;
+  }
+
+  @override
+  void paint(PaintingContext context, ui.Image image, double pixelRatio, Animation<double> animation) {
+    final double fade = reverse
+      ? _ZoomExitTransition._fadeOutTransition.evaluate(animation)
+      : 1.0;
+    final double scale = (reverse
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:518]: Can scale end up being larger than 1.0? Will this make the scaled image more pixelated?

**Comment by jonahwilliams** [comment]
One possible compromise is that we could apply the raster only to the next route and not the current route. That would allow animations on the current page to continue working.

**Comment by goderbauer** [comment]
> I agree we shouldn't break heroes or other transitions, but as long as they don't use the ZoomPageTransition they should be unaffected.

Isn't this transition the default? People would be likely to use it with heroes then. We should check that they continue to work, is what I am saying :)

> Do you have an example of this? I think I've seen those before. It may not work

I don't have one immediately at hand...

**Comment by jonahwilliams** [comment]
Heroes still work:

https://user-images.githubusercontent.com/8975114/176255545-951c450c-7c4d-4c2f-9388-6e9174431efd.mp4


https://user-images.githubusercontent.com/8975114/176255553-864c46c0-aba5-4d2b-a180-6955e029c136.mp4

**Comment by goderbauer** [comment]
> Heroes still work:

It's hard to tell because the animation is happening so fast (can you post one with animations slowed down?): But it looks like that in the demo_new the word "Banner" actually appears multiple times on screen (one flying around and one sitting at the start (or end?) location)....

**Comment by dnfield** [comment]
Is `Banner` supposed to be red between transitions? 
image

**Comment by jonahwilliams** [comment]
Its red on bot ToT and with the new version so that is unrelated.

**Comment by jonahwilliams** [comment]
Old slowed down:

https://user-images.githubusercontent.com/8975114/176262212-a62c0830-5787-4895-bd2a-b090c73591d9.mp4

New slowed down:


https://user-images.githubusercontent.com/8975114/176262481-31d9cd88-41c9-4f86-b762-1889a3bcd50c.mp4


You're right, it looks like this rendering is incorrect on the outgoing route

**Comment by jonahwilliams** [comment]
New slowed down. 

https://user-images.githubusercontent.com/8975114/176262945-e9b54a5d-f00e-49fa-95e7-ade0921e2d35.mp4

**Comment by jonahwilliams** [comment]
Old slowed down:

https://user-images.githubusercontent.com/8975114/176263716-788671f1-71ec-4389-927c-1a8b70dd6e1d.mp4

**Comment by dnfield** [comment]
It's turning red because it's getting put in a subtree with no default text style

**Comment by jonahwilliams** [comment]
> It's turning red because it's getting put in a subtree with no default text style

Dan, this isn't really relevant at all to the discussion

**Comment by jonahwilliams** [comment]
I'm going to grab lunch, why don't we talk about this in a GVC later today?

**Comment by dnfield** [comment]
> > It's turning red because it's getting put in a subtree with no default text style
> 
> Dan, this isn't really relevant at all to the discussion

Haha it's not for this pr but it was bothering me.  Sure let's chat. It'd be good to figure out a way to make the hero closer

**Comment by jonahwilliams** [comment]
I think we can get away with making frame 1 of the outgoing route skip the raster and only start that on frame 2. On frame 1 both opacity and scale should be at 1.0 which means all of the existing raster cache entries still exist

**Comment by goderbauer** [comment]
> 
I'm going to grab lunch, why don't we talk about this in a GVC later today?

Feel free to put something on my calendar.

**Comment by jonahwilliams** [comment]
I've updated this so that we only rasterize if `scale != 0` or `opacity != 0 || 1`. This allows the hero animation to begin correctly

Results aren't any worse:

```
  "average_frame_rasterizer_time_millis": 2.5510900473933633,
  "90th_percentile_frame_rasterizer_time_millis": 2.963,
  "99th_percentile_frame_rasterizer_time_millis": 9.966,
  "worst_frame_rasterizer_time_millis": 12.701,
   "frame_rasterizer_count": 211,
  ```

**Comment by jonahwilliams** [comment]
numbers aren't much worse if I skip rasterization on frame 1

```
  "average_frame_rasterizer_time_millis": 2.649248780487806,
  "90th_percentile_frame_rasterizer_time_millis": 2.944,
  "99th_percentile_frame_rasterizer_time_millis": 12.926,
  "worst_frame_rasterizer_time_millis": 13.699,
  "missed_frame_rasterizer_budget_count": 0,
  "frame_count": 204,
  "frame_rasterizer_count": 205,
  ```

File: packages/flutter/lib/src/widgets/animated_raster.dart [hunk 16]
```diff
@@ -0,0 +1,226 @@
...
+import 'package:flutter/animation.dart';
+import 'package:flutter/rendering.dart';
+
+import 'framework.dart';
+import 'media_query.dart';
+
+/// A delegate that controls what is painted during an animation in the [AnimatedRaster]
+/// widget.
+@immutable
+abstract class AnimatedRasterDelegate {
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/widgets/animated_raster.dart:16]: This API probably needs another pass. paint and paintRaster should be more similar.

**Comment by jonahwilliams** [comment]
hero is fixed:

https://user-images.githubusercontent.com/8975114/176282727-09a6737d-a91f-49d7-9bf1-65925df1ed36.mp4

File: packages/flutter/lib/src/widgets/animated_raster.dart (hunk 7 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/animated_raster.dart:94]: _maybe_ 

I like the idea of a general purpose widget that we can point folks towards that makes toGpuImage easier to use. Whether or not this API is general purpose enough remains to be seen of course

**Comment by jonahwilliams** [comment]
From offline discussion:

* The rasterization behavior can be the default, but we need an opt out. `shouldRasterize` on `TransitionRoute` default to true, let the transition builder read that value. This should be well documented.
* Make the widget/RO private for now since we're not sure about the API
* Remove the painting context API and just ignore the warning for stopRecordingIfNeeded

File: packages/flutter/lib/src/widgets/animated_raster.dart (hunk 10 above)
Comment (fzyzcjy) [reply packages/flutter/lib/src/widgets/animated_raster.dart:163]: Btw when programming Flutter, do we really have to spot such kind of bugs manually by eyes? Or can we develop some lints or verifiers for it... I am willing to contribute

**Comment by nt4f04uNd** [comment]
It's sad that you will not see splash new effects from the source route with this. It would be cool if this could be optimized in some other way.

Also, how will it look like if you hold your finger a bit, so the splash expands, and then release it - would the splash be frozen for the time of the transition? I guess that's a bit weird.

**Comment by jonahwilliams** [comment]
If you have other ideas for how to improve performance you should certainly puruse those as well. We'll allow an opt out if the old behavior is important, though I suspect most folks won't actually notice.

**Comment by ds84182** [comment]
I think @flar 's idea for a RasterTransformLayer would still work well here, giving the performance benefits for route transitions while keeping the route animations live during the transition. 

Since this impacts fidelity (because native Android animates during transitions) should this be opt-in until a solution that preserves the behavior is found?

**Comment by dnfield** [comment]
@ds84182 it would help if you could share a case where the fidelity impact is noticeable.

**Comment by jonahwilliams** [comment]
The rasterized transform layer will not help in this case, because changing the scale via the zoom would invalidate the raster cache. And if it didn't use the raster cache, it would mostly be the same performance as today minus an extra save layer from the image filter

**Comment by flar** [comment]
> The rasterized transform layer will not help in this case, because changing the scale via the zoom would invalidate the raster cache. And if it didn't use the raster cache, it would mostly be the same performance as today minus an extra save layer from the image filter

I don't think you understand the purpose of a "rasterized transform layer". Its 100% benefit is to prevent invalidation of its cached children due to transform changes. It literally was defined to solve the problem that you are saying can't be solved here. Am I missing something?

See https://github.com/flutter/engine/pull/31443

It solves the problem at the engine level without little change to the framework and it solves it in a very targeted manner. It was closed because at the time I thought that fixing the tree stability issues would interoperate with ImageFilter.Matrix well enough to make it obsolete, but it looks like ImageFilter.Matrix doesn't provide the fast path we originally thought it does. That PR was designed to solve exactly the problem you are trying to solve here in as direct a manner as possible.

**Comment by flar** [comment]
> No, you're right - its not that changing the scale invaldiates it - its that the child animation, intentional or accidental invalidates it.

How does a child animation disrupt a raster transform layer solution, but does not invalidate the toGPUImage image?

**Comment by jonahwilliams** [comment]
Because I'm not invaliding the image regardless of child animation state

**Comment by dnfield** [comment]
The raster transform layer proposal is a bit harder to use for developers, and still requires a bunch of fiddliness about the raster cache rather than letting the framework use it's knowledge of the animation to make and dispose the raster.

This patch will discard animations drawn in the same layer. Trying to draw those during the transition generally doesn't work anyway (but I would welcome counterexamples)

**Comment by dnfield** [comment]
Put another way: the linked patch adds more complexity to dart:ui. We should avoid that if possible. This makes it possible.

**Comment by jonahwilliams** [comment]
@ds84182 this isn't a fidelity - performance trade off, this is just a fidelity - fidelity trade off. Today you can either run at a device appropriate framerate (90hz/60hz) during the transition, or you can run animations but at a significantly reduced frame rate. Obviously we'd prefer to run at the full frame rate, with as rich of transitions as possible but that is not possible today.

@flar If you suspect that we could still get good frame rates by using this rasterized transform layer or (ideally) by fixing image filter, then I think you should prioritize working on it and compare that benchmark with the numbers I have above. 

I had a previous PR that had a more targeted heursitc fix for this, but in retrospect I think that is actually a bad idea. What happens when the next android version has a page transition that does a spin and fade mixed with a color blending effect? How long would the framework team need to wait for the engine team to adjust their heustics? toGpuImage gives the framework the ability to take performance into their own hands, which is important given that our priorities don't always line up.

**Comment by flar** [comment]
OK, here is some background on what makes this solution work better than what we have been achieving with the existing engine design:

- Engine layers are single purpose. If you want to do multiple operations, you have to break it up into multiple "engine layers" each of which work independently. Scale and Fade? That requires a TransformLayer and an OpacityLayer and they each operate on "children" - to try to combine their operations requires work by the engine to notice when those operations can be combined. So, while each engine layer can easily cache-optimize its own operations, the ability for a sequence of layers to cache-optimize their combined operations is missing in so many configurations and gets expensive to recognize when the authoring code (the widgets) already knew how the operations combined before they were forced to express the ops as individual nested layers.
- It appears that the framework code here can decide to "cache and freeze" the children so that if the children continue to animate, it can ignore the subsequent changes in the children. Existing cache stability mechanism all rely on the children actually not changing, but this code will enforce that condition (presumably because widgets undergoing a transition effect don't need to be animating themselves?)
- Overall toGpuImage as an isolated mechanism should have similar performance to the caching in the engine layers, but the resulting image can be dealt with more flexibly at the widget/RenderObject level than it can at the "each op is its own layer" engine level.

Am I seeing this accurately?

**Comment by dnfield** [comment]
Yes, I think that sounds right.

**Comment by jonahwilliams** [comment]
> it appears that the framework code here can decide to "cache and freeze" the children so that if the children continue to animate, it can ignore the subsequent changes in the children. Existing cache stability mechanism all rely on the children actually not changing, but this code will enforce that condition (presumably because widgets undergoing a transition effect don't need to be animating themselves?)

I would say more generally, the engine caching is conservative because it doesn't know the intention of the developer - and providing more hints is difficult since the engine caching decision happens very "far" from where the developer may have authored the code. The framework, or a particular widget, may decide to more agressively cache, and configuring that caching is something that is easier to discover by a developer. This caching may even amount to disabling an animation, which could be desirable if the performance is significant enough or if that animation or repainting is incindental

File: packages/flutter/lib/src/rendering/layer.dart (hunk 14 above)
Comment (dnfield) [reply packages/flutter/lib/src/rendering/layer.dart:1438]: I think it would still be good to have some more details in here about when to use this and when to prefer toImage.

For example:

```
Prefer using this method when the image will immediately and exclusively be drawn via [Canvas.drawImage] and related [Canvas] APIs, and manipulation or transformation of the image will only come via [Canvas] and [Paint] API usage for drawing to the screen.

Prefer using [toImage] when the program needs direct access to the image bytes, for example to save them to disk or send them over a network connection, or will otherwise require direct access to a [ByteData] representation of the image.
```

**Comment by flar** [comment]
> > it appears that the framework code here can decide to "cache and freeze" the children so that if the children continue to animate, it can ignore the subsequent changes in the children. Existing cache stability mechanism all rely on the children actually not changing, but this code will enforce that condition (presumably because widgets undergoing a transition effect don't need to be animating themselves?)
> 
> I would say more generally, the engine caching is conservative because it doesn't know the intention of the developer - and providing more hints is difficult since the engine caching decision happens very "far" from where the developer may have authored the code. The framework, or a particular widget, may decide to more agressively cache, and configuring that caching is something that is easier to discover by a developer. This caching may even amount to disabling an animation, which could be desirable if the performance is significant enough or if that animation or repainting is incindental

Another way to look at this PR is that you are answering the question of "what if I just wanted to express what I want to do with my children as a call to drawImage?" For this PR to work, it necessarily involves creating the GpuImage in order to express what you want - which means you have to involve caching in order to express a complex operation through the existing SceneBuilder API. What if we could break those 2 concepts up and so you could still express your transition as "drawScene(scene, geometric destination description (x,y or rects, nine-slice, etc), Paint, <transform info>)" and then it could be used as a common way to present modifications of a set of children. That could be combined with either automatic or explicit caching to be able to do the entire zoom page transition in one operation. Even without caching, it would be a much more efficient operation. toGpuImage or the existing engine cache would become implementation details, but the API being presented would be this more flexible one that is independent of those details and would work well with them.

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 17]
```diff
@@ -0,0 +1,223 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+part of page_transitions_theme;
```
Comment (dnfield) [inline packages/flutter/lib/src/material/animated_raster.dart:5]: here and elsewhere:

let's file a TODO to remove these once we figure out a good way to make this public. 

Alternatively, this looks like something reasonable to have as public API to me, but I'd get @goderbauer's opinion on that.

**Comment by dnfield** [comment]
@flar - what happens when the next transition we have to optimize for involves a rotation? Or a custom fragment shader? 

I'm also interested in hearing about the advantages we'd gain by adding API to the SceneBuilder that we otherwise would lose.

**Comment by flar** [comment]
> @flar - what happens when the next transition we have to optimize for involves a rotation? Or a custom fragment shader?
> 
> I'm also interested in hearing about the advantages we'd gain by adding API to the SceneBuilder that we otherwise would lose.

Are you talking about my comment about a potential drawScene(...)? FragmentShader is installed in a Paint so it would already be dealing with that. The transform is part of the operation just as if it would be with drawImage().

What I'm saying is that if you can express your operation as a call to drawImage - as this PR already implicitly requires - then it could be expressed as drawScene(...) which has all of the same bells and whistles as drawImage, but operates on a scene fragment.

We're not adding API to the SceneBuilder, we're removing API and replacing it with a more flexible operation.

pushOpacity should have never existed, it should have been drawScene(children, Paint..setAlpha).
pushImageFilter should have never existed, it should have been drawScene(children, Paint..setIF()).
pushColorFilter should have never existed, it should have been drawScene(children, Paint..setCF()).
pushTransform could be replaced by some variant of drawScene(children) with a transform.

At that point, pushOpacity nested with pushImageFilter becomes an obsolete concept replaced by drawScene(children, Paint..setThis..setThat).

And if the new transition involves perspective transforms, then it should already be expressable by the new mechanism because it can do anything you could have done with manual caching and a call to drawImage().

**Comment by flar** [comment]
Also, I'm suggesting that a simpler near-term change would be that pushOpacity, pushImageFilter and pushColorFilter could very easily and non-disruptively be replaced by a single pushPaint. Those methods on SceneBuilder could still exist as special cases of pushPaint, but if we had had pushPaint all along, many of the "peephole optimization" complications that were part of the reason for this PR would have never been an issue.

And doing so combines 3 engine layers into 1, without any changes to framework code other than providing the framework with an opportunity to combine its layers if it so wishes.

To completely express most conceivable transition concepts, pushPaint isn't enough - we'd have to add a transform optimization into that. It isn't as "mostly delete code with a few lines added" trivial as adding pushPaint, but it is not that much work.

The longer term idea, though, is that pushSingleConceptFoo() is not a good API for us to have ever provided developers.

**Comment by fzyzcjy** [comment]
> Overall, toGpuImage as an isolated mechanism should have similar performance to the caching in the engine layers in terms of getting pieces of scenes into images. But the resulting image can be dealt with more flexibly at the widget/RenderObject level than it can at the "each op is its own layer" engine level.

That would be very useful for many cases, because when the flutter app is getting larger and more complicated, it is often the case that we have to control all the underlying details in some performance-critical components.

**Comment by flar** [comment]
Where is the time spent in toGPUImage accounted? The call itself just returns a placeholder and puts a task on the rasterizer queue. The rasterization time reported in frame metrics is only the time to render the frame's layer tree itself. The other tasks are not timed or reported AFAICT.

So, unless I'm missing something, the results above are basically ignoring the rasterization time of the GPU image...? Perhaps that is only on the first frame of the animation, but it still should be accounted for somewhere to get accurate data.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/pull/106621#issuecomment-1167748551

There is a specific event for toGpuImage, but the important bit is overall frame count goes way up.

File: packages/flutter/lib/src/material/animated_raster.dart (hunk 17 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/animated_raster.dart:5]: I think from the last discussion we had, we're going to keep it private until we find more than one use case for it

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/animated_raster.dart:5]: @goderbauer to confirm...

**Comment by flar** [comment]
> #106621 (comment)

That's good, but we should be accounting for these in the benchmark metrics so we can track regressions. The toGpuImage events will be in the timeline, but the code that reads timelines needs  to be taught what to do with it. This time will not be accounted for in the FrameTiming structures that the E2E benchmarks use.

We also track cache counts and memory used trace flows that show their lifetimes through creation, usage, and eviction.

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 18]
```diff
@@ -0,0 +1,202 @@
...
+// a reasonable public API.
+part of page_transitions_theme;
+
+// Foundational widgets for the rasterized zoom page transition.
+
+/// A delegate that controls what is painted during an animation in the [_AnimatedRaster]
+/// widget.
+@immutable
+abstract class _AnimatedRasterDelegate {
+  /// const constructor so that subclasses can be const.
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/animated_raster.dart:15]: nit: sentences in docs should be grammatically correct and start with a capital letter.

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 19]
```diff
@@ -0,0 +1,202 @@
...
+  const _AnimatedRasterDelegate();
+
+  /// Whether [paint] will paint anything on the current frame.
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/animated_raster.dart:18]: This seems inaccurate. you can totally return false from here if you want to paint directly e.g. because an animation you care about is running...

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 20]
```diff
@@ -0,0 +1,202 @@
...
+  /// Paint the children of this render object.
+  ///
+  /// The provided [image] contains a GPU resident texture of the children of
+  /// this render object.
+  ///
+  /// The [pixelRatio] is the ratio of pixels in [image] to logical pixels.
+  @protected
+  void paintRaster(PaintingContext context, ui.Image image, double pixelRatio, Animation<double> animation);
+
+  /// Paint the children of this render object.
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/animated_raster.dart:36]: It strikes me as a little odd that this paint is only used when `useRaster` is false, but isn't used to paint the children for the initial rasterization if `useRaster` is true...

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 21]
```diff
@@ -0,0 +1,202 @@
...
+  @protected
+  void paint(PaintingContext context, Animation<double> animation, Rect area, PaintingContextCallback callback);
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/animated_raster.dart:38]: The parameters to this method should be documented, especially callback.

Comment (goderbauer) [inline packages/flutter/lib/src/material/animated_raster.dart:38]: nit: organize same parameters in the same order for paint and paintRaster to show parallelism?

File: packages/flutter/lib/src/material/animated_raster.dart (hunk 17 above)
Comment (goderbauer) [reply packages/flutter/lib/src/material/animated_raster.dart:7]: (some of my doc comments below assume that we will make this eventually public)

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 22]
```diff
@@ -0,0 +1,202 @@
...
+// found in the LICENSE file.
+
+// TODO(jonahwilliams): this is temporarily a private library until we determine
+// a reasonable public API.
+part of page_transitions_theme;
+
+// Foundational widgets for the rasterized zoom page transition.
+
+/// A delegate that controls what is painted during an animation in the [_AnimatedRaster]
+/// widget.
```
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/material/animated_raster.dart:12]: Might also be worth documenting how the pre-rastered image is painted since that - surprisingly - is not going through paint?

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 23]
```diff
@@ -0,0 +1,202 @@
...
+  /// The [pixelRatio] is the ratio of pixels in [image] to logical pixels.
+  @protected
+  void paintRaster(PaintingContext context, ui.Image image, double pixelRatio, Animation<double> animation);
+
+  /// Paint the children of this render object.
+  @protected
+  void paint(PaintingContext context, Animation<double> animation, Rect area, PaintingContextCallback callback);
+}
+
+/// A widget that replaces [child] with a rasterized version while an animation is active.
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/animated_raster.dart:41]: > [...] while an animation is active.

Technically, it's up to the delegate to decide when to require rasterization, no? And it could be the other way around: only when the animation is not active, if one wanted...

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 24]
```diff
@@ -0,0 +1,202 @@
...
+      ..animation = animation
+      ..delegate = delegate
+      ..devicePixelRatio = MediaQuery.maybeOf(context)?.devicePixelRatio ?? 1.0;
+  }
+}
+
+/// A render object that converts its children to a [ui.Image].
+///
+/// This render object will create a GPU resident texture the first time that
+/// [_AnimatedRasterDelegate.willPaint] returns true and and provide it to
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/animated_raster.dart:83]: willPaint -> useRaster?

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 25]
```diff
@@ -0,0 +1,202 @@
...
+/// [_AnimatedRasterDelegate.paintRaster]. This will be reused until `willPaint`
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/animated_raster.dart:84]: same

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 26]
```diff
@@ -0,0 +1,202 @@
...
+  /// The animation used to drive this render object.
+  Animation<double> get animation => _animation;
+  Animation<double> _animation;
+  set animation(Animation<double> value) {
+    if (value == animation) {
+      return;
+    }
+    animation.removeListener(markNeedsPaint);
+    _animation = value;
+    animation.addListener(markNeedsPaint);
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/animated_raster.dart:130]: Only do this if we are attached? Otherwise you'll do it again when you get attached.

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 27]
```diff
@@ -0,0 +1,202 @@
...
+    animation.removeListener(markNeedsPaint);
+    super.detach();
+  }
+
+  // Paint [child] with this painting context, then convert to a raster and detach all
+  // children from this layer.
+  ui.Image _paintAndDetachToGpuImage() {
+    final OffsetLayer offsetLayer = layer! as OffsetLayer;
+    final PaintingContext context = PaintingContext(offsetLayer, Offset.zero & size);
+    context.paintChild(child!, Offset.zero);
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/animated_raster.dart:159]: See earlier comments: Why is this not going through the delegate's paint?

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 28]
```diff
@@ -0,0 +1,202 @@
...
+    // ignore: invalid_use_of_protected_member
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/animated_raster.dart:160]: Ugh...

File: packages/flutter/lib/src/widgets/routes.dart [hunk 29]
```diff
@@ -126,6 +126,21 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
...
+  /// When this value is true, certain route transitions (Such as the Android
+  /// zoom page transition) will rasterize the entering and exiting routes.
+  /// These textures are then animated in place of the underlying widgets to
+  /// improve performance of the transition.
+  ///
+  /// Generally this means that animations that occur on the entering/exiting
+  /// route while the route animation plays may appear frozen - unless they
+  /// are a hero animation or something that is drawn in a separate overlay.
+  /// {@endtemplate}
+  bool get preferRasterization => true;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/routes.dart:142]: Wondering: should we name this more explicitly `preferRasterizationDuringTransition` - or is this getting too ridiculous?

File: packages/flutter/lib/src/material/animated_raster.dart (hunk 17 above)
Comment (goderbauer) [reply packages/flutter/lib/src/material/animated_raster.dart:7]: Uff, you also want to use the part of trick for testing. That has caused us trouble before... maybe we should just properly design the API for this and make it public....

File: packages/flutter/lib/src/material/animated_raster.dart (hunk 28 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/animated_raster.dart:162]: Yeah, this is why I added the PaintingContext API

File: packages/flutter/lib/src/widgets/routes.dart (hunk 29 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart:142]: I think that's a bit too much

File: packages/flutter/lib/src/material/animated_raster.dart (hunk 20 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/animated_raster.dart:36]: I could see us breaking this into multiple simpler ROs which might alieviate the problem - which is that this RO + delegate need to do too much - that being said, one issue is that for this API to be flexible enough we should have access to the resulting image somehow. I'm not sure how to do that with composition.

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/animated_raster.dart:36]: maybe _all_ the delegate does is handle drawing the image, the notifier is separate, and then the parent which controls the notifier chooses whether to draw with any effects? That might let us combine the two animations. I'll investigate that a bit

**Comment by flar** [comment]
Some more thoughts on the Gpu Images. Is there a mechanism to invalidate them and/or recreate them when the GPU is taken away from us? I'm not sure if that is still a thing, but I know back when we were creating Gpu images in Java (decades ago) we had to create a concept called VolatileImage that could tell you "I'm sorry, but my contents are missing and I have no way of getting them back, you'll have to abandon this object and recreate it" because most platforms could just dump your GPU assets outside of your control.

I looked at the native RasterCache and it looks like it has a Clear method that gets called from CompositorContext::OnGrContextCreated/Destroyed which appears to be a way to invalidate our native cache when these events occur.

So...

- Does asynchronous loss of GPU assets still happen on any platforms we support (or are likely to support in the future)?
- Does this GpuImage mechanism have a way to recover from that (which would either require remembering the scene/DL from which they were created and repopulating automatically, or notifying the framework so that it could recreate the image). I did a brief look through this PR and didn't see any code that looked like it was dealing with this issue.

**Comment by dnfield** [comment]
@flar I think some of these questions might be better suited in some dedicated issues. When implementing https://github.com/flutter/engine/pull/33736 I did run a number of test cases manually to try to simulate the things you're suggesting. It's quite possible I missed something or that there are bugs in the implementation. 

In general, the GPU image will throw when you try to draw it to the canvas if there was a problem. I tried some test cases manually that should have exercised loss of GPU context, but it's quite possible that I didn't exercise it correctly.

In any case, for the cases in this patch, when the GrContext is restored you'd be generating a new image anyway - this only really happens today when the app goes to background and comes back.

File: packages/flutter/lib/src/material/animated_raster.dart (hunk 20 above)
Comment (dnfield) [reply packages/flutter/lib/src/material/animated_raster.dart:36]: Maybe instead of having a delegate, we have an abstract class as public that does the `ideal` case above, and a private concrete implementation that does the `reality` case?

File: packages/flutter/lib/src/material/animated_raster.dart [hunk 30]
```diff
@@ -0,0 +1,202 @@
...
+    try {
+      delegate.paintRaster(
+        context,
+        _childImage!,
+        devicePixelRatio,
+        animation,
+      );
+    } on ui.PictureRasterizationException {
+      // We're running on an emulator without a GPU context.
+      // For now render nothing.
```
[the remark this answers is not in the document]
Comment (fzyzcjy) [reply packages/flutter/lib/src/material/animated_raster.dart:201]: > So far this only happens on android emulators with --use-software-rendering. 

Seems also happens when using `flutter test` for widget tests, i.e. without a simulator/real-device?

[the remark this answers is not in the document]
Comment (dnfield) [reply packages/flutter/lib/src/material/animated_raster.dart:201]: Flutter test won't throw here, but it currently will return a checkerboard image.

We could add API that tells you whether this API is available or not to avoid this -my assumption with the current design is that developers would be in a place here to just draw their original picture or scene instead, but maybe that's not a good assumption.

File: packages/flutter/lib/src/rendering/layer.dart [hunk 31]
```diff
@@ -1402,17 +1416,7 @@ class OffsetLayer extends ContainerLayer {
...
-    final ui.SceneBuilder builder = ui.SceneBuilder();
-    final Matrix4 transform = Matrix4.translationValues(
-      (-bounds.left  - offset.dx) * pixelRatio,
-      (-bounds.top - offset.dy) * pixelRatio,
-      0.0,
-    );
-    transform.scale(pixelRatio, pixelRatio);
-    builder.pushTransform(transform.storage);
-    final ui.Scene scene = buildScene(builder);
+    final ui.Scene scene = _createSceneForImage(bounds, pixelRatio: pixelRatio);
```
Comment (flar) [inline packages/flutter/lib/src/rendering/layer.dart:1419]: The bounds calculation below is bad math, you don't want the ceil of the size, you want the size of the roundOut()

File: packages/flutter/lib/src/rendering/layer.dart [hunk 32]
```diff
@@ -1425,6 +1429,40 @@ class OffsetLayer extends ContainerLayer {
...
+  /// size of the output image. It is independent of the
+  /// [dart:ui.FlutterView.devicePixelRatio] for the device, so specifying 1.0
+  /// (the default) will give you a 1:1 mapping between logical pixels and the
+  /// output pixels in the image.
+  ///
+  /// See also:
+  ///
+  ///  * [RenderRepaintBoundary.toImage] for a similar API at the render object level.
+  ///  * [dart:ui.Scene.toGpuImage] for more information about the image returned.
+  ui.Image toGpuImage(Rect bounds, { double pixelRatio = 1.0 }) {
```
Comment (flar) [inline packages/flutter/lib/src/rendering/layer.dart:1452]: Why not provide a full transform so that this sub-scene can be rasterized with all inherited transforms. The existing scene should already contain the pixelRatio in a transform inserted early on in the scene building process.

Pixel ratio is the primary concern here for what scale to render it with, but if some sort of scene magnification is in effect you will lose that information by only adjusting for the pixel ratio.

File: packages/flutter/lib/src/rendering/layer.dart [hunk 33]
```diff
@@ -1385,6 +1385,20 @@ class OffsetLayer extends ContainerLayer {
...
+  ui.Scene _createSceneForImage(Rect bounds, { double pixelRatio = 1.0 }) {
+    assert(bounds != null);
+    assert(pixelRatio != null);
+    final ui.SceneBuilder builder = ui.SceneBuilder();
+    final Matrix4 transform = Matrix4.translationValues(
+      (-bounds.left  - offset.dx) * pixelRatio,
+      (-bounds.top - offset.dy) * pixelRatio,
+      0.0,
+    );
+    transform.scale(pixelRatio, pixelRatio);
```
Comment (flar) [inline packages/flutter/lib/src/rendering/layer.dart:1397]: It is a poorly named method in Matrix4, but I think it would be more straightforward to just say:

```
  final Matrix4 transform = Matrix4.diagonal3Values(pixelRatio, pixelRatio, 1);
  transform.translate(-(bounds.left + offset.dx), -(bounds.top + offset.dy));
```

File: packages/flutter/lib/src/rendering/layer.dart (hunk 31 above)
Comment (flar) [reply packages/flutter/lib/src/rendering/layer.dart:1419]: Actually, given that the scene was created by translating back by the origin of the bounds, it might work if there was no offset.

Unfortunately, there is an offset, so the scene isn't necessarily rendered at the origin of the bounds.

So, what is really needed is (bounds+offset).roundOut.size. If offset is zero then this will end up being equivalent to the calculation below, but if it is not zero, then this will fix a potential "clipping off the last pixel" bug.

Comment (flar) [reply packages/flutter/lib/src/rendering/layer.dart:1419]: Hmmm, thinking through this more - if the first thing that buildScene does is to translate by offset, then those would cancel out and size.ceil is fine. I don't see that as happening in buildScene, though. Am I missing something there?

File: packages/flutter/lib/src/rendering/layer.dart (hunk 33 above)
Comment (fzyzcjy) [reply packages/flutter/lib/src/rendering/layer.dart:1397]: I wonder whether the two are equivalent? The original code is "first translate then scale" while the suggested code is "first scale then translate"

File: packages/flutter/lib/src/rendering/layer.dart (hunk 31 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/rendering/layer.dart:1419]: I need to do some research on the intention of this API and what the engine is actually doing with it.  It seems like it would be reasonable for a developer to specify a fractional offset if they intended to sample from only part of the picture. Which makes ceil not make sense either really. We'd only need to round up to an integral value for the texture/width height.

Comment (jonahwilliams) [reply packages/flutter/lib/src/rendering/layer.dart:1419]: oh wait, its the bounds width / height - isn't that correct then:

developer specifies a Rect.fromLTWH(0.5, 0.5, 1.5, 1.5) -> we create a texture size of (1, 1). developer specifies a Rect.fromLTWH(0.5, 0.5, 1, 1) -> we need to round up to create a texture of (1, 1)?

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 34]
```diff
@@ -0,0 +1,165 @@
...
+import 'dart:ui' as ui;
+
+import 'package:flutter/rendering.dart';
+
+import 'basic.dart';
+import 'framework.dart';
+import 'media_query.dart';
+
+/// A widget that replaces its child with a rasterized version of said child.
+class RasterWidget extends SingleChildRenderObjectWidget {
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/widgets/raster_widget.dart:14]: @goderbauer @dnfield here is my next attempt at a reusable widget for this, which does only one thing. some notes:

1. Currently catches PictureRasterizationException. We just need some way of detecting tester + software backend so that I can fall back to better behavior.
2. I'm using a bool for raster vs non-raster, but I don't have a good way of saying "keep using the raster but re-create the raster"

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 35]
```diff
@@ -0,0 +1,165 @@
...
+    _devicePixelRatio = value;
+    markNeedsPaint();
+  }
+
+  /// The delegate used to draw the `ui.Image` representing the rasterized child widget.
+  RasterWidgetDelegate get delegate => _delegate;
+  RasterWidgetDelegate _delegate;
+  set delegate(RasterWidgetDelegate value) {
+    if (!value.shouldRepaint(delegate)) {
+      return;
```
Comment (dnfield) [inline packages/flutter/lib/src/widgets/raster_widget.dart:107]: Shouldn't this still update the `_delegate`?

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 36]
```diff
@@ -0,0 +1,165 @@
...
+  bool get isRepaintBoundary => child != null;
+
+
+  @override
+  void paint(PaintingContext context, Offset offset) {
+    _childRaster ??= _paintAndDetachToGpuImage();
+    try {
+      delegate.paint(context, offset & size, _childRaster!, devicePixelRatio);
+    } on ui.PictureRasterizationException {
+      // TODO(jonahwilliams): handle software backend.
```
[the remark this answers is not in the document]
Comment (dnfield) [reply packages/flutter/lib/src/widgets/raster_widget.dart]: We talked offline - I'm going to see if I can refactor the upstream API to better support this case.

**Comment by jonahwilliams** [comment]
Currently waiting on updates for toImageSync. Will need to refactor the existing PR a bit more - the straegy I am using of dynamically adding/removing the raster widget is leading to extra rebuilds.

**Comment by jonahwilliams** [comment]
Need to do a few more cleanups and add some tests and this will be ready for another pass

File: packages/flutter/lib/src/rendering/layer.dart (hunk 32 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/rendering/layer.dart]: Depending on how this is constructed, you could always provide an arbitrary transform by embedding said transform in your scene. If A widget/RO that uses this API is not aware of a parent transform, or aware of changes in parent transform, then there may be pixelation issues, but that is the same caveat that the existing async API has

File: dev/bots/test.dart [hunk 37]
```diff
@@ -134,6 +137,9 @@ const Map<String, List<String>> kWebTestFileKnownFailures = <String, List<String
     'test/cupertino/scaffold_test.dart',
     'test/rendering/platform_view_test.dart',
     'test/cupertino/context_menu_action_test.dart',
+
+    // This test uses the part of trick
+    'test/widgets/animated_raster_test.dart',
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply dev/bots/test.dart]: Fixed

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 38]
```diff
@@ -296,46 +461,59 @@ class _ZoomEnterTransition extends StatelessWidget {
...
 
+  @override
+  State<_ZoomExitTransition> createState() => _ZoomExitTransitionState();
+}
+
+class _ZoomExitTransitionState extends State<_ZoomExitTransition> with _ZoomTransitionBase {
+  late _ZoomExitTransitionDelegate delegate;
+
+  @override
+  bool get allowRasterization => !kIsWeb && widget.preferRasterization;
```
Comment (dnfield) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:515]: This is overly aggressive right?

I think you or yegor filed an issue somewhere for this, can we link it here with a TODO?

Comment (jonahwilliams) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:517]: Done

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 39]
```diff
@@ -0,0 +1,258 @@
...
+  @override
+  void updateRenderObject(BuildContext context, covariant RenderRasterWidget renderObject) {
+    renderObject
+      ..delegate = delegate
+      ..rasterize = rasterize
+      ..devicePixelRatio = MediaQuery.maybeOf(context)?.devicePixelRatio ?? 1.0;
+  }
+}
+
+/// A delegate used to draw the image representing the rasterized child.
```
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/raster_widget.dart:90]: Also document why this is a ChangeNotifier? What happens if it notifies its listeners? Or When should implementations notify their listeners?

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 40]
```diff
@@ -0,0 +1,258 @@
...
+    }
+  }
+
+  ui.Image? _childRaster;
+  bool _currentlyRepaintBoundary = false;
+
+  @override
+  void attach(covariant PipelineOwner owner) {
+    delegate.addListener(markNeedsPaint);
+    rasterize.addListener(_onRasterValueChanged);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/raster_widget.dart:200]: These get added twice if deelgate and rasterizer are set while the RO is detached.

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 41]
```diff
@@ -0,0 +1,258 @@
...
+    _currentlyRepaintBoundary = rasterize.value;
+    if (_currentlyRepaintBoundary != wasRepaintBoundary) {
+      markNeedsCompositingBitsUpdate();
+    }
+    markNeedsPaint();
+  }
+
+  // Paint [child] with this painting context, then convert to a raster and detach all
+  // children from this layer.
+  ui.Image _paintAndDetachToGpuImage() {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/raster_widget.dart:233]: nitty nit: remove the GPU from this method now that the inderlying API also doesn't have it in its name anymore?

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 42]
```diff
@@ -0,0 +1,258 @@
...
+    final OffsetLayer offsetLayer = layer! as OffsetLayer;
+    final PaintingContext context = PaintingContext(offsetLayer, Offset.zero & size);
+    super.paint(context, Offset.zero);
+    // ignore: invalid_use_of_protected_member
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/raster_widget.dart:237]: Ideally, we avoid this ignore altogether. At the very least it needs a comment explaining why this is here and whether this is temporary.

File: packages/flutter/lib/src/widgets/routes.dart [hunk 43]
```diff
@@ -126,6 +126,21 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
   /// {@endtemplate}
   bool get opaque;
 
+  /// {@template flutter.widgets.TransitionRoute.preferRasterization}
+  /// Whether the route transition will prefer to animate a rasterized
+  /// snapshot of the entering/exiting routes.
+  ///
+  /// When this value is true, certain route transitions (Such as the Android
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/routes.dart:133]: capitalization: Such -> such

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 44]
```diff
@@ -351,23 +529,105 @@ class _ZoomExitTransition extends StatelessWidget {
...
+  final Animation<double> fade;
+
+  @override
+  void paint(PaintingContext context, Rect area, ui.Image image, double pixelRatio) {
+    _drawImageScaledAndCentered(context, image, scale.value, fade.value, pixelRatio);
+  }
+
+  @override
+  bool shouldRepaint(covariant _ZoomExitTransitionDelegate oldDelegate) {
+    return oldDelegate.reverse != reverse || oldDelegate.fade != fade || oldDelegate.scale != scale;
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:622]: Technically, you'd only have to repaint if `oldDelegate.fade.value != fade.value` (and same for scale), right?

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 45]
```diff
@@ -0,0 +1,258 @@
...
+  @override
+  void notifyListeners() { }
+
+  @override
+  void removeListener(ui.VoidCallback listener) { }
+}
+
+/// A widget that replaces its child with a rasterized version of the child.
+///
+/// When the value of [rasterize] is true, this widget will convert the child scene into
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart:47]: You can hack around it by changing the key, but that obviously isn't ideal.

To match the existing API, we could accept some sort of notifier that will invalidate the raster whenever it fires?

**Comment by jonahwilliams** [comment]
I have not addressed all feedback, but I did update to a controller API which I think makes more sense

File: packages/flutter/lib/src/widgets/raster_widget.dart (hunk 45 above)
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart]: Added controller API

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 46]
```diff
@@ -0,0 +1,258 @@
...
+  });
+
+  /// A delegate that allows customization of how the image is painted.
+  ///
+  /// If not provided, defaults to a delegate which paints the child as is.
+  final RasterWidgetDelegate delegate;
+
+  /// Whether a rasterized version of this render objects child is drawn in
+  /// place of the child.
+  final ValueNotifier<bool> rasterize;
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart]: Outdated by way of controller API change

File: packages/flutter/lib/src/widgets/raster_widget.dart (hunk 41 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart]: Done

File: packages/flutter/lib/src/widgets/raster_widget.dart (hunk 42 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart:240]: Added comment, LMK what you think

File: packages/flutter/lib/src/widgets/routes.dart (hunk 43 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/routes.dart]: Done

File: packages/flutter/lib/src/material/page_transitions_theme.dart (hunk 44 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:590]: Done

File: packages/flutter/lib/src/widgets/raster_widget.dart (hunk 40 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart]: I always miss this one

File: packages/flutter/lib/src/widgets/raster_widget.dart (hunk 35 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart]: Done

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 47]
```diff
@@ -250,18 +260,67 @@ class _ZoomPageTransition extends StatelessWidget {
...
+  final bool preferRasterization;
   final bool reverse;
 
+  @override
+  State<_ZoomEnterTransition> createState() => _ZoomEnterTransitionState();
+}
+
+mixin _ZoomTransitionBase {
+  // Don't rasterize if:
+  // 1. rasterization is disabled by the platform.
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/page_transitions_theme.dart]: Done

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 48]
```diff
@@ -250,18 +260,67 @@ class _ZoomPageTransition extends StatelessWidget {
...
   final Animation<double> animation;
   final Widget? child;
+  final bool preferRasterization;
   final bool reverse;
 
+  @override
+  State<_ZoomEnterTransition> createState() => _ZoomEnterTransitionState();
+}
+
+mixin _ZoomTransitionBase {
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/page_transitions_theme.dart]: Yeah this mixin isn't really that great, but its also private. Not sure exactly what I'd want to do here.

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 49]
```diff
@@ -0,0 +1,258 @@
...
+
+/// A widget that replaces its child with a rasterized version of the child.
+///
+/// When the value of [rasterize] is true, this widget will convert the child scene into
+/// an image. This image will be drawn in place of the children until [rasterize] is false.
+///
+/// How this image is drawn can be customized by providing a new subclass of [RasterWidgetDelegate]
+/// to the [delegate] argument.
+///
+/// This widget is not supported on the HTML backend of flutter for the web.
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart]: Done

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 50]
```diff
@@ -0,0 +1,258 @@
...
+    required super.child
+  });
+
+  /// A delegate that allows customization of how the image is painted.
+  ///
+  /// If not provided, defaults to a delegate which paints the child as is.
+  final RasterWidgetDelegate delegate;
+
+  /// Whether a rasterized version of this render objects child is drawn in
+  /// place of the child.
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart]: Think this should be more clear with the controller API?

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 51]
```diff
@@ -0,0 +1,258 @@
...
+  void removeListener(ui.VoidCallback listener) { }
+}
+
+/// A widget that replaces its child with a rasterized version of the child.
+///
+/// When the value of [rasterize] is true, this widget will convert the child scene into
+/// an image. This image will be drawn in place of the children until [rasterize] is false.
+///
+/// How this image is drawn can be customized by providing a new subclass of [RasterWidgetDelegate]
+/// to the [delegate] argument.
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart]: Done

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 52]
```diff
@@ -0,0 +1,258 @@
...
+  ///
+  /// The image is rasterized at the physical pixel resolution and should be scaled down by
+  /// [pixelRatio] to account for device independent pixels.
+  ///
+  /// There is no offset given in this paint method, as the parent is an [OffsetLayer] all
+  /// offsets are `Offset.zero`.
+  ///
+  /// Example:
+  ///
+  /// ```dart
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart:112]: Done

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 53]
```diff
@@ -0,0 +1,258 @@
...
+abstract class RasterWidgetDelegate extends ChangeNotifier {
+  /// Called whenever the [image] that represents a [RasterWidget]s child should be painted.
+  ///
+  /// The image is rasterized at the physical pixel resolution and should be scaled down by
+  /// [pixelRatio] to account for device independent pixels.
+  ///
+  /// There is no offset given in this paint method, as the parent is an [OffsetLayer] all
+  /// offsets are `Offset.zero`.
+  ///
+  /// Example:
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart]: Done

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 54]
```diff
@@ -0,0 +1,258 @@
...
+  ///   final Rect dst = Rect.fromLTWH(0, 0, area.width, area.height);
+  ///   final Paint paint = Paint()
+  ///     ..filterQuality = FilterQuality.low;
+  ///   context.canvas.drawImageRect(image, src, dst, paint);
+  /// }
+  ///
+  /// ```
+  void paint(PaintingContext context, Rect area, ui.Image image, double pixelRatio);
+
+  /// Called whenever a new instance of the custom painter delegate class is
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart:124]: Fixed, it was just a copy paste error

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 55]
```diff
@@ -0,0 +1,258 @@
...
+  /// away.
+  ///
+  /// It's possible that the [paint] method will get called even if
+  /// [shouldRepaint] returns false (e.g. if an ancestor or descendant needed to
+  /// be repainted). It's also possible that the [paint] method will get called
+  /// without [shouldRepaint] being called at all (e.g. if the box changes
+  /// size).
+  ///
+  /// The `oldDelegate` argument will never be null.
+  bool shouldRepaint(covariant RasterWidgetDelegate oldDelegate);
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart:148]: Done

**Comment by jonahwilliams** [comment]
Took a pass attempting to address documentation issues

**Review by dnfield — DISMISSED** [review]
Lgtm if lgt goderbauer

**Comment by jonahwilliams** [comment]
Latest numbers:

New:
```
"average_frame_build_time_millis": 1.2650128755364807,
  "90th_percentile_frame_build_time_millis": 1.058,
  "99th_percentile_frame_build_time_millis": 20.284,
  "worst_frame_build_time_millis": 37.832,
  "missed_frame_build_budget_count": 3,
  "average_frame_rasterizer_time_millis": 2.697935622317597,
  "90th_percentile_frame_rasterizer_time_millis": 3.095,
  "99th_percentile_frame_rasterizer_time_millis": 14.474,
  "worst_frame_rasterizer_time_millis": 15.469,
  "missed_frame_rasterizer_budget_count": 0,
  "frame_count": 233,
  "frame_rasterizer_count": 233,
  "new_gen_gc_count": 36,
  "old_gen_gc_count": 2,
  ```
  
  Old:
  
  ```
 "average_frame_build_time_millis": 1.1861463414634146,
  "90th_percentile_frame_build_time_millis": 1.13,
  "99th_percentile_frame_build_time_millis": 6.712,
  "worst_frame_build_time_millis": 34.433,
  "missed_frame_build_budget_count": 1,
  "average_frame_rasterizer_time_millis": 6.972506024096388,
  "90th_percentile_frame_rasterizer_time_millis": 14.395,
  "99th_percentile_frame_rasterizer_time_millis": 22.621,
  "worst_frame_rasterizer_time_millis": 22.64,
  "missed_frame_rasterizer_budget_count": 6,
  "frame_count": 82,
  "frame_rasterizer_count": 83,
  "new_gen_gc_count": 2,
  "old_gen_gc_count": 0,
  ```
  
  Device is a Pixel 6.

**Comment by jonahwilliams** [comment]
Converting to a draft while I hack out the last platform view specific bits

**Comment by jonahwilliams** [comment]
PTAL @dnfield @goderbauer 

I've added a fallback system that detects the first time a PlatformView or TextureView is encountered and errors out. We then provide a special delegate in the route transitions that make this not error out and instead fall back to pushing layers.

By default we don't handle these errors so users are discouraged from including platform views as children of these - though there is the option to disable this check if they don't care.

A future change will remove the restriction on texture view.

**Comment by jonahwilliams** [comment]
The future change: https://github.com/flutter/engine/pull/34624

**Comment by jonahwilliams** [comment]
open question, should I just use the single fallback and make the web use the fallback delegate?

**Comment by dnfield** [comment]
> open question, should I just use the single fallback and make the web use the fallback delegate?

As opposed to what?

**Comment by dnfield** [comment]
Having fewer code paths in general is probably good though.

**Comment by jonahwilliams** [comment]
as opposed to detecting web before starting the transition and switching to the "old" zoom page transition, I could let it hit the fallback path provided to the raster widget

**Comment by jonahwilliams** [comment]
Actually that doesn't quite work unless we give a RasterWidget a way to force hit its fallback path, since we want to allow users to opt out of it via prefer-rasterization. I'm okay keeping this very special cased, since we're only doing it once for this route transition

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 56]
```diff
@@ -250,18 +266,31 @@ class _ZoomPageTransition extends StatelessWidget {
...
   final bool reverse;
 
+  @override
+  State<_ZoomEnterTransition> createState() => _ZoomEnterTransitionState();
+}
+
+class _ZoomEnterTransitionState extends State<_ZoomEnterTransition> with _ZoomTransitionBase {
+  // TODO(jonahwilliams): https://github.com/flutter/flutter/issues/106689
+  @override
+  bool get allowRasterization => !kIsWeb && widget.preferRasterization;
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:290]: This Widget does some unnecessary work in initState and didUpdateWidget when this evaluates to false - and probably also wastes some memory with unused objects...

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 57]
```diff
@@ -282,60 +311,122 @@ class _ZoomEnterTransition extends StatelessWidget {
...
+        child: widget.child,
+      );
+    }
     return AnimatedBuilder(
-      animation: animation,
+      animation: widget.animation,
       builder: (BuildContext context, Widget? child) {
+        double scrimOpacity = 0;
+        // The transition's scrim opacity only increases on the forward transition.
+        // In the reverse transition, the opacity should always be 0.0.
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:380]: Can you assert here that the 0.0 is true?

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 58]
```diff
@@ -282,60 +311,122 @@ class _ZoomEnterTransition extends StatelessWidget {
...
+  @override
+  State<_ZoomExitTransition> createState() => _ZoomExitTransitionState();
+}
+
+class _ZoomExitTransitionState extends State<_ZoomExitTransition> with _ZoomTransitionBase {
+  late _ZoomExitTransitionDelegate delegate;
+
+  // TODO(jonahwilliams): https://github.com/flutter/flutter/issues/106689
+  @override
+  bool get allowRasterization => !kIsWeb && widget.preferRasterization;
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:428]: same as above.

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 59]
```diff
@@ -629,3 +772,194 @@ class PageTransitionsTheme with Diagnosticable {
...
+        break;
+      case AnimationStatus.forward:
+      case AnimationStatus.reverse:
+        controller.rasterize = allowRasterization;
+        break;
+    }
+  }
+}
+
+
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:842]: nit: remove one blank line.

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 60]
```diff
@@ -629,3 +772,194 @@ class PageTransitionsTheme with Diagnosticable {
...
+  final Animation<double> fade;
+
+  final Matrix4 _transform = Matrix4.zero();
+  OpacityLayer? _oldOpacity;
+  TransformLayer? _oldTransform;
+
+  void _drawScrim(PaintingContext context, Offset offset, Size size) {
+    double scrimOpacity = 0.0;
+    // The transition's scrim opacity only increases on the forward transition.
+    // In the reverse transition, the opacity should always be 0.0.
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:867]: can this be asserted in case it ever changes?

File: packages/flutter/lib/src/rendering/layer.dart [hunk 61]
```diff
@@ -168,6 +168,15 @@ abstract class Layer extends AbstractNode with DiagnosticableTreeMixin {
 
   bool _debugMutationsLocked = false;
 
+  /// Whether or not this layer, or any child layers, can be rasterized with
+  /// [Scene.toImage] or [Scene.toImageSync].
+  ///
+  /// If `false`, calling the above methods may yield an image which is
+  /// incomplete.
+  bool supportsRasterization() {
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/layer.dart:176]: This sounds like it should be a getter.

File: packages/flutter/lib/src/rendering/layer.dart [hunk 62]
```diff
@@ -168,6 +168,15 @@ abstract class Layer extends AbstractNode with DiagnosticableTreeMixin {
 
   bool _debugMutationsLocked = false;
 
+  /// Whether or not this layer, or any child layers, can be rasterized with
+  /// [Scene.toImage] or [Scene.toImageSync].
+  ///
+  /// If `false`, calling the above methods may yield an image which is
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/layer.dart:174]: Document: Is what this returns allowed to change during the lifetime of the Layer or must it stay static? If it can change, do you need to notify anybody if it does?

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 63]
```diff
@@ -0,0 +1,401 @@
...
+///
+/// By default, the child is drawn as is. The default [delegate] simply scales
+/// down the image by the current device pixel ratio and paints it into the
+/// canvas. How this image is drawn can be customized by providing a new
+/// subclass of [RasterWidgetDelegate] to the [delegate] argument.
+///
+/// Caveats:
+///
+/// The contents of platform views cannot be captured by a raster
+/// widget. If a platform view is encountered, then nothing will be rendered unless
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/raster_widget.dart:82]: This is at odds with the documentation at ignorePlatformViews, which says an error is thrown. I think throwing an error is preferred over silently drawing nothing.

File: packages/flutter/lib/src/widgets/raster_widget.dart (hunk 39 above)
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/raster_widget.dart:138]: These comments still need addressing.

File: packages/flutter/lib/src/widgets/raster_widget.dart (hunk 54 above)
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/raster_widget.dart:168]: The doc here still talks about a custom painter delegate.

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 64]
```diff
@@ -0,0 +1,401 @@
...
+/// Consumers of [RasterWidget] should almost never use this delegate. For the most part,
+/// the raster widget only functions as a performance improvement. If a platform view is
+/// present, the performance improving qualities aren't possible and using this API is
+/// pointless.
+///
+/// Instead, this interface is useful if a generic/reusable widget is being created which
+/// may include a platform view and it needs to handle this transparently. For example, the
+/// framework uses this for the zoom page transition so that navigating to a page shows the same
+/// animation whether or not there is a platform view.
+abstract class RasterWidgetFallbackDelegate {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/raster_widget.dart:61]: nitnit: move this closer to the regular delegate?

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 65]
```diff
@@ -0,0 +1,401 @@
...
+  ui.Image? _paintAndDetachToImage(PaintingContext originalContext) {
+    final OffsetLayer offsetLayer = OffsetLayer();
+    final PaintingContext context = PaintingContext(offsetLayer, Offset.zero & size);
+    super.paint(context, Offset.zero);
+    // This ignore is here because this method is protected by the `PaintingContext`. Adding a new
+    // method that performs the work of `_paintAndDetachToImage` would avoid the need for this, but
+    // that would conflict with our goals of minimizing painting context.
+    // ignore: invalid_use_of_protected_member
+    context.stopRecordingIfNeeded();
+    if (!ignorePlatformViews && !offsetLayer.supportsRasterization()) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/raster_widget.dart:329]: THere's an implicit walk of the layer tree here. This doesn't change the perf characteristics in an undesired way?

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 66]
```diff
@@ -0,0 +1,401 @@
...
+  /// The controller that determines when to display the children as an image.
+  final RasterWidgetController controller;
+
+  /// A fallback delegate which is used if the child layers contains a platform view.
+  final RasterWidgetFallbackDelegate? fallback;
+
+  /// Whether the raster widget will ignore platform views in child layers.
+  ///
+  /// Defaults to `false`, which causes an error to be thrown if a platform view
+  /// is encountered.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/raster_widget.dart:113]: ... unless a fallback has been specified.

It is rather complicate to wrap one's head around how `ignorePlatformViews` and `fallback` interact. Do we really need this as separate settings? Could we do with just the optional `fallback` and if you don't provide one, we just error to simplify things? Why dod we need the option to ignore platform views?

**Review by goderbauer — COMMENTED** [review]
It worries me a little that this introduces three separate paths for rendering the same thing. That's a lot of complexity. Any change we can reduce this a little to maybe just two: The fully optimized case and one fallback case in case that's not possible?

File: packages/flutter/lib/src/widgets/raster_widget.dart (hunk 65 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart:329]: Because we only walk the layer tree once per raster widget (and because we need to walk it anyway to render it) - it is fairly cheap.

File: packages/flutter/lib/src/widgets/raster_widget.dart (hunk 66 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart:116]: I added some more context to the documentation here. The idea is, suppose that you are using this widget and the child has a platform view. But the platform view isn't really important, and you don't care if its included in the scene. Without this flag, there is no way to force rasterization of the scene. You can provide a fallback but that doesn't allow you to opt into rasterization

File: packages/flutter/lib/src/widgets/raster_widget.dart (hunk 64 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/widgets/raster_widget.dart]: Done

File: packages/flutter/lib/src/material/page_transitions_theme.dart (hunk 59 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/page_transitions_theme.dart]: Done

File: packages/flutter/lib/src/material/page_transitions_theme.dart (hunk 56 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:290]: These are now always used that we use the raster widget fallback

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 67]
```diff
@@ -190,6 +195,13 @@ class _ZoomPageTransition extends StatelessWidget {
   ///    property when the [_ZoomPageTransition] is used as a page transition.
   final Animation<double> secondaryAnimation;
 
+  /// Whether the [RasterWidget] based-rasterized strategy for the zoom page transition
+  /// will be used.
+  ///
+  /// Notably, this improves performance by disabling animations on both the outgoing and
+  /// incoming route.
```
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/page_transitions_theme.dart]: Added more context here

**Comment by jonahwilliams** [comment]
I removed one of the fallback paths and spent some time working on the documentation

File: packages/flutter/lib/src/rendering/layer.dart (hunk 61 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/rendering/layer.dart:179]: It does a tree walk and doesn't cache, so making it a method follows flutter guidelines

File: packages/flutter/lib/src/rendering/layer.dart (hunk 62 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/rendering/layer.dart:174]: Added comment that this value is assumed to not change

File: packages/flutter/lib/src/rendering/layer.dart (hunk 13 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/rendering/layer.dart:1450]: Done. There are some more incidental differences, but we're working on unifying those now.

File: packages/flutter/lib/src/material/page_transitions_theme.dart (hunk 60 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:832]: I added an assert to singular place this is used

File: packages/flutter/lib/src/material/page_transitions_theme.dart (hunk 57 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/page_transitions_theme.dart]: Done

File: packages/flutter/lib/src/material/page_transitions_theme.dart (hunk 58 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/page_transitions_theme.dart:401]: Done I think?

File: packages/flutter/lib/src/material/page_transitions_theme.dart [hunk 68]
```diff
@@ -629,3 +738,193 @@ class PageTransitionsTheme with Diagnosticable {
...
+  // 1. Rasterization is disabled by the platform.
+  // 2. The animation is paused/stopped.
+  // 3. The values of the scale/fade transition do not
+  //    benefit from rasterization.
+  final RasterWidgetController controller = RasterWidgetController();
+
+  late Animation<double> fadeTransition;
+  late Animation<double> scaleTransition;
+
+  bool get allowRasterization;
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/page_transitions_theme.dart:782]: nit: the mixin doesn't care about this setting anymore. Maybe remove it here and just make the overrides private in the subclasses?

File: packages/flutter/lib/src/rendering/layer.dart (hunk 61 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/layer.dart:179]: Right, I wrote this before I saw the other implementation that does the walk...

File: packages/flutter/lib/src/rendering/layer.dart (hunk 62 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/layer.dart:174]: Now that I read over this again I think that statement is actually not true, right? Layers get reused and if at one point one of your children is a platform view, this will return false, if then that platform view goes away, this will be true. So, it does change...

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 69]
```diff
@@ -0,0 +1,457 @@
...
+import 'package:flutter/rendering.dart';
+
+import 'basic.dart';
+import 'framework.dart';
+import 'media_query.dart';
+
+/// A controller for the [RasterWidget] that controls when the child image is displayed
+/// and when to regenerated the child image.
+///
+/// When the value of [rasterize] is true, The [RasterWidget] will convert the child scene into
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/raster_widget.dart:16]: The -> the

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 70]
```diff
@@ -0,0 +1,457 @@
...
+
+  /// Whether the raster widget should use the provided [RasterWidgetFallbackDelegate]
+  /// to render.
+  ///
+  /// Defaults to `false`. Generally, this should only be used if it is known
+  /// that the current platform does not support the raster widget.
+  ///
+  /// Setting this to `true` on a raster widget that does not have a fallback
+  /// delegate will cause an exception to be thrown.
+  bool get fallback => _fallback;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/raster_widget.dart:58]: should we roll `fallback` and `rasterize` into a tri-state enum?

File: packages/flutter/lib/src/widgets/raster_widget.dart (hunk 66 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/raster_widget.dart:116]: Can you add exactly that explanation to the doc?

File: packages/flutter/lib/src/widgets/raster_widget.dart [hunk 71]
```diff
@@ -0,0 +1,457 @@
...
+  final RasterWidgetController controller;
+
+  /// A fallback delegate which is used if the child layers contains a platform view.
+  final RasterWidgetFallbackDelegate? fallback;
+
+  /// Whether the raster widget will ignore platform views in child layers.
+  ///
+  /// Defaults to `false`, which causes an error to be thrown if a platform view
+  /// is encountered.
+  final bool ignorePlatformViews;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/raster_widget.dart:117]: (per in-person conversation this flag is going away so I will not complain about it further in this review)

**Review by goderbauer — APPROVED** [review]
LGTM w/ the boolean reconciliation that we just discussed in person.

File: packages/flutter/lib/src/rendering/layer.dart (hunk 62 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/rendering/layer.dart:174]: Oh ... right. The value may change. I think I was thinking about individual layers, but then it actually doesn't really matter. You only generate a snapshot for a specific instance of a layer tree.
