### PR TITLE
Suggest predicate-based formatter in [FilteringTextInputFormatter] docs for whole string matching

### LINKED ISSUE #78100: [TextInputFormatter] FilteringTextInputFormatter might have some handling mistakes
Not sure whether is by design for regexp's match result or a bug.

# Case 1:

## Pattern

`FilteringTextInputFormatter.allow(RegExp(r'^(0|[1-9]{0,4})(\.\d{0,2})?$'))`

## Steps to Reproduce

1. Input `1111.11`.
2. Input another number.

**Expected results:** Keep the original input.

**Actual results:** All inputs are gone.

# Case 2:

## Pattern

`FilteringTextInputFormatter.allow(RegExp(r'^(0|[1-9]{0,4})(\.\d{0,2})?'))` (without the end matching pattern `$`)

## Steps to Reproduce

1. Input `1111.11`.
2. Move the selection offset to `.1` and the last `1`.
3. Input another number.
4. Move the selection offset after `.1` again.
5. Input another number.

**Actual results:** There can be 6 decimal at most.

**Expected results:** Only 2 decimal allowed.

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
- Fixes #78100

Explains when not to use a `FilteringTextInputFormatter`.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/services/text_formatter.dart [hunk 1]
```diff
@@ -212,18 +212,30 @@ class _TextEditingValueAccumulator {
...
 /// Instances of filtered characters found in the new [TextEditingValue]s
-/// will be replaced with the [replacementString] which defaults to the empty
+/// will be replaced by the [replacementString] which defaults to the empty
 /// string.
 ///
-/// Since this formatter only removes characters from the text, it attempts to
-/// preserve the existing [TextEditingValue.selection] to values it would now
-/// fall at with the removed characters.
+/// A [FilteringTextInputFormatter] also tries to preserve the existing
+/// [TextEditingValue.selection] and [TextEditingValue.composing], and adjusts
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_formatter.dart:224]: nit: maybe add a "region" after "[TextEditingValue.composing]" to make this read better?

File: packages/flutter/lib/src/services/text_formatter.dart [hunk 2]
```diff
@@ -212,18 +212,30 @@ class _TextEditingValueAccumulator {
...
+/// them accordingly if text within either of these ranges is replaced.
+///
+/// This formatter is typically used to match potentially recurring [Pattern]s
+/// in the new [TextEditingValue], and it never completely rejects the new
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_formatter.dart:228]: maybe break this sentence up a little. It's super long with the two "and"s.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by LongCatIsLooong** [comment]
@goderbauer rephrased some of the new docs could you take a look again?

File: packages/flutter/lib/src/services/text_formatter.dart [hunk 3]
```diff
@@ -212,19 +212,31 @@ class _TextEditingValueAccumulator {
...
+/// A [FilteringTextInputFormatter] also tries to preserve the existing
+/// [TextEditingValue.selection] and the [TextEditingValue.composing] region,
+/// adjusting them accordingly if text within either of these ranges is replaced.
+///
+/// This formatter is typically used to match potentially recurring [Pattern]s
+/// in the new [TextEditingValue]. It never completely rejects the new
+/// [TextEditingValue] and falls back to the current [TextEditingValue] when the
+/// given [filterPattern] fails to match. Consider using a different
+/// [TextInputFormatter] such as:
+/// `TextInputFormatter.withFunction((oldValue, newValue) => regExp.hasMatch(newValue.text) ? newValue : oldValue)`.
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/text_formatter.dart:232]: could you wrap this in a ```dart section to get nicer code formatting in docs?

**Review by goderbauer — APPROVED** [review]
Still LGTM

File: packages/flutter/lib/src/services/text_formatter.dart [hunk 4]
```diff
@@ -212,19 +212,33 @@ class _TextEditingValueAccumulator {
...
-/// will be replaced with the [replacementString] which defaults to the empty
+/// will be replaced by the [replacementString] which defaults to the empty
 /// string.
 ///
-/// Since this formatter only removes characters from the text, it attempts to
-/// preserve the existing [TextEditingValue.selection] to values it would now
-/// fall at with the removed characters.
+/// A [FilteringTextInputFormatter] also tries to preserve the existing
+/// [TextEditingValue.selection] and the [TextEditingValue.composing] region,
+/// adjusting them accordingly if text within either of these ranges is replaced.
```
Comment (justinmc) [inline packages/flutter/lib/src/services/text_formatter.dart:225]: Nit: Is it also possible that that text before these ranges is replaced and they need to be updated?  Not sure but just being pedantic.

File: packages/flutter/lib/src/services/text_formatter.dart [hunk 5]
```diff
@@ -212,19 +212,33 @@ class _TextEditingValueAccumulator {
...
+/// [TextEditingValue] and falls back to the current [TextEditingValue] when the
+/// given [filterPattern] fails to match. Consider using a different
+/// [TextInputFormatter] such as:
+/// ```dart
+/// TextInputFormatter.withFunction((oldValue, newValue) => regExp.hasMatch(newValue.text) ? newValue : oldValue)
+/// ```
+/// for accepting/rejecting new input based on a predicate on the full string.
+/// As an example, [FilteringTextInputFormatter] typically shouldn't be used
+/// with [RegExp]s that contain positional matchers (`^` or `$`) since these
+/// patterns are usually meant for matching the whole string.
```
Comment (justinmc) [inline packages/flutter/lib/src/services/text_formatter.dart:238]: This is much more clear to me and I feel like I know what to do in both situations thanks to the examples :+1:

**Review by justinmc — APPROVED** [review]
LGTM :+1:
