### PR TITLE
[flutter_tools] Suggest actions to fix failing `FlutterValidator`

### LINKED ISSUE #106334: Suggest actions to resolve failing FlutterValidator
`flutter doctor` can now find issues with the git configuration of the user's install (#103259), but does not provide suggestions to fix.

The following suggestions can be added:
- If upstream repository is a non-standard remote, we show a message to set `FLUTTER_GIT_URL` to the non-standard remote.
- If upstream repository is unknown, we display a message to reinstall Flutter.
- If channel is unknown, we display a message to switch to a release channel using `flutter channel`(to fix detached HEAD), and if that doesn't work, reinstall Flutter.
- If frameworkVersion is unknown, we display a message that the tool was unable to resolve version possibly due to local changes, and if is okay to lose changes, reinstall Flutter.

### PR DESCRIPTION
**Pull request by royarg02**
Add suggestions to doctor, to fix failing `FlutterValidator` due to broken git configuration of local install.

Fixes #106334.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/user_messages.dart [hunk 1]
```diff
@@ -18,11 +18,21 @@ class UserMessages {
...
-      'Framework revision $revision ($age), $date';
+    'Framework revision $revision ($age), $date';
   String flutterUpstreamRepositoryUrl(String url) => 'Upstream repository $url';
+  String get flutterUpstreamRepositoryUnknown =>
+    'Unknown upstream repository.\n'
+    'Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.';
   String flutterUpstreamRepositoryUrlEnvMismatch(String url) => 'Upstream repository $url is not the same as FLUTTER_GIT_URL';
-  String flutterUpstreamRepositoryUrlNonStandard(String url) => 'Upstream repository $url is not a standard remote';
+  String flutterUpstreamRepositoryUrlNonStandard(String url) =>
+    'Upstream repository $url is not a standard remote. Set "FLUTTER_GIT_URL" to $url.';
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/base/user_messages.dart:35]:
```suggestion
    'Upstream repository $url is not a standard remote. If this is intentional, set "FLUTTER_GIT_URL" to $url to dismiss this error.';
```

File: packages/flutter_tools/lib/src/base/user_messages.dart [hunk 2]
```diff
@@ -18,11 +18,22 @@ class UserMessages {
       'Channel ${channel ?? 'unknown'}, ${version ?? 'Unknown'}, on $os, locale $locale';
   String flutterVersion(String version, String channel, String flutterRoot) =>
       'Flutter version $version on channel $channel at $flutterRoot';
+  String get flutterUnknownChannel =>
+    'Currently on an unknown channel. Run `flutter channel` to switch to an official channel.\n'
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/base/user_messages.dart:22]: I feel like these messages are implying that the user's SDK installation is broken, which may not be the case. And from experience, we've found that not-green validations in the Flutter doctor can cause people a lot of anxiety. What about updating all of these to make it clear that if their current state is intentional, they are fine to continue?

Comment (RoyARG02) [reply packages/flutter_tools/lib/src/base/user_messages.dart:22]: That is fine, but I prefer to avoid users confused by seeing the error messages from upgrade and have to be pointed out the "potential" causes, by other users comparing the doctor output.

Comment (RoyARG02) [reply packages/flutter_tools/lib/src/base/user_messages.dart:22]: How about "It is fine to continue if this is intentional, however it is recommended to use "git" directly as the tool won't be able to perform upgrades_(and inform about new versions, wherever applicable)_ at this state".

Comment (RoyARG02) [reply packages/flutter_tools/lib/src/base/user_messages.dart:22]: Added a message when FlutterValidator fails stating the above.

File: packages/flutter_tools/lib/src/base/user_messages.dart [hunk 3]
```diff
@@ -36,6 +47,9 @@ class UserMessages {
       'On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6\n'
       'On Fedora: dnf install libstdc++.i686\n'
       'On Arch: pacman -S lib32-gcc-libs';
+  String get flutterValidatorErrorIntentional =>
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/base/user_messages.dart:50]: How about:

```
'If this was intentional, you can disregard this warning; however, it is '
'recommended to use "git" directly to perform update checks and upgrades.';
```

**Review by christopherfujino — APPROVED** [review]
nit on the message, otherwise LGTM

File: packages/flutter_tools/lib/src/base/user_messages.dart (hunk 3 above)
Comment (RoyARG02) [reply packages/flutter_tools/lib/src/base/user_messages.dart:50]: Updated the message as per your suggestion. Would still like to have your thoughts on the pluralized version though.

**Comment by RoyARG02** [comment]
Also, I went ahead and added a test so that the tool doesn't show the message on pass.

File: packages/flutter_tools/lib/src/base/user_messages.dart (hunk 3 above)
Comment (RoyARG02) [reply packages/flutter_tools/lib/src/base/user_messages.dart:50]: Would you prefer to have the pluralized version then?

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/user_messages.dart:50]: Ahh ok, after re-reading it, I think this is fine, as is the pluralization.

**Comment by christopherfujino** [comment]
> Also, I went ahead and added a test so that the tool doesn't show the message on pass.

Nice! this still LGTM.

**Review by Jasguerrero — APPROVED** [review]
LGTM

**Comment by RoyARG02** [comment]
@christopherfujino @Jasguerrero could anyone of you add the required labels to merge this PR?
