### PR TITLE
	Make tear-offs cacheable for RenderSemanticsGestureHandler

### LINKED ISSUE #11552: Caching callbacks in RenderSemanticsGestureHandler doesn't work as expected
`RenderSemanticsGestureHandler` contains multiple setters in the following style:

```dart
  set onTap(GestureTapCallback value) {
    if (_onTap == value)
      return;
    _onTap = value;
    // Do work because value as changed.
  }
```

In real words: if the setter is set to the same value it already has no extra work should happen. However, in the precise environment the setters are called this check doesn't work as expected.

The setters are called from `_GestureSemantics` and the callbacks are set to a member function of that class. While `RenderSemanticsGestureHandler` is a long-lived object, `_GestureSemantics` is a short-lived widget. In fact, in every frame, a new `_GestureSemantics` is build and the callbacks of `RenderSemanticsGestureHandler` are updated to the new `_GestureSemantics`'s member functions. The member function from the old `_GestureSemantics` object and the one from the new `_GestureSemantics` object are not considered equal by Dart, the `_onTap == value` check in the setter returns `false` and we do extra work in the setter for nothing as the actual onTap handler might not have changed.

Failing test case to illustrate the problem:
```dart
  testWidgets('cache unchanged callbacks', (WidgetTester tester) async {
    final GestureTapCallback inputCallback = () {};

    await tester.pumpWidget(
        new Center(
            child: new GestureDetector(
              onTap: inputCallback,
              child: new Container(),
            )
        )
    );

    final RenderSemanticsGestureHandler renderObj1 = tester.renderObject(find.byType(GestureDetector));
    final GestureTapCallback actualCallback1 = renderObj1.onTap;

    await tester.pumpWidget(
        new Center(
            child: new GestureDetector(
              onTap: inputCallback,
              child: new Container(),
            )
        )
    );

    final RenderSemanticsGestureHandler renderObj2 = tester.renderObject(find.byType(GestureDetector));
    final GestureTapCallback actualCallback2 = renderObj2.onTap;

    expect(renderObj1, same(renderObj2));
    expect(actualCallback1, same(actualCallback2));  // This call fails.
  });
```

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/11552.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/gesture_detector.dart [hunk 1]
```diff
@@ -718,20 +681,58 @@ class _GestureSemantics extends SingleChildRenderObjectWidget {
...
+    Widget child,
+    this.owner
+  }) : super(key: key, child: child);
+
+  final RawGestureDetectorState owner;
+
+  @override
   RenderSemanticsGestureHandler createRenderObject(BuildContext context) {
     final RenderSemanticsGestureHandler result = new RenderSemanticsGestureHandler();
     updateRenderObject(context, result);
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/gesture_detector.dart]: Can you have this call _updateHandlers directly? Having it bounce through updateRenderObject is weird.

Comment (goderbauer) [inline packages/flutter/lib/src/widgets/gesture_detector.dart]: True. Changed.

**Comment by Hixie** [comment]
LGTM
