### PR TITLE
[flutter_tools] fix documentation on default built ios

### LINKED ISSUE #56717: Instructions discrepancy
According to https://flutter.dev/docs/deployment/ios `flutter build ios` defaults to --release version. However, my zshell says otherwise:

```
Usage: flutter build ios [arguments]
    --debug                                       Build a debug version of your app (default mode).
    --profile                                     Build a version of your app specialized for performance profiling.
    --release                                     Build a release version of your app.
```

So, how is it in the end? What does it defaults to?

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes https://github.com/flutter/flutter/issues/56717

The default for build for `flutter build ios` should be release to match the other `build` commands. This is correctly handled in the command, but the documentation is incorrect. Update the documentation and the default to reflect the more common case of building for a physical device.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/build_ios.dart [hunk 1]
```diff
@@ -22,7 +22,7 @@ class BuildIOSCommand extends BuildSubCommand {
   BuildIOSCommand({ @required bool verboseHelp }) {
     addTreeShakeIconsFlag();
     addSplitDebugInfoOption();
-    addBuildModeFlags(defaultToRelease: false);
+    addBuildModeFlags(defaultToRelease: true);
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/build_ios.dart:25]: This is a big behavior change, who knows what build scripts out there are leaving off `--debug`.  Can we leave the default behavior and just fix up the text?

**Comment by jmagman** [comment]
Fixes https://github.com/flutter/flutter/issues/52698.

File: packages/flutter_tools/lib/src/commands/build_ios.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/build_ios.dart:25]: This doesn't change the default, see https://github.com/flutter/flutter/pull/56720/files#diff-c616f0a92b2c8f4d7b8d95d2367e0ff6R61

Unless a user passed simulator, we're defaulting to release anyway.

Comment (jmagman) [reply packages/flutter_tools/lib/src/commands/build_ios.dart:25]: Doesn't it have the side effect of setting _defaultBuildMode?
https://github.com/flutter/flutter/blob/0a4f6cdef0c39c73cab310342784813dfe6b5ec8/packages/flutter_tools/lib/src/runner/flutter_command.dart#L381

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/build_ios.dart:25]: But that is overriden again on L61

Comment (jmagman) [reply packages/flutter_tools/lib/src/commands/build_ios.dart:25]: So it is.

**Review by jmagman — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/commands/build_ios.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/build_ios.dart:25]: Its a confusing API
