### PR TITLE
Fix for PR #174374 - Fix - TalkBack does not announce list information

### LINKED ISSUE #168651: [Google3 Bug]: Android Talkback does not read "1 of 4" or similar indexes of items for any of the children of the `ListView` even with the use of `IndexedSemantics`
### Help us understand the severity of this issue

- [ ] causing severe production issues e.g. malfunctions or data loss
- [ ] blocking next binary release
- [x] blocking a client feature launch within a quarter
- [ ] nice-to-have but does not block a launch within the next quarter

### Steps to reproduce

1. Run the flutter application on android device
2. Start android Talkback
3. Swipe horizontally to allow Android talkback read through the Text widgets on the screen.

### Expected results

With the use of IndexedSemantics, Android Talkback should have read:
"1 of 4, Title 1"
"2 of 4, Title 2",
"3 of 4, Title 3",
"4 of 4, Title 4"

### Actual results

The following is read out by Talkback:
"Title 1"
"Title 2"
"Title 3"
"Title 4"

### Code sample

<details open><summary>Code sample</summary>
In the `bug_repro` project (created via `flutter create ~/Desktop/bug_repro`),
Replace the `build` method of `_MyHomePageState` with the following code:

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: ListView(
          addSemanticIndexes: false,
          semanticChildCount: 4,
          physics: NeverScrollableScrollPhysics(),
          children: [
            IndexedSemantics(index: 0, child: Text('title 1')),
            IndexedSemantics(index: 1, child: Text('title 2')),
            IndexedSemantics(index: 2, child: Text('title 3')),
            IndexedSemantics(index: 3, child: Text('title 4')),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      )
    );
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/0d3d1b93-8514-4db2-8f7e-7dc0b8f77516

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-arm64, locale en) [2.2s]
    • Flutter version 3.29.3 on channel stable at /Users/bhagrawal/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (4 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2.3s]
    • Android SDK at /Users/bhagrawal/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio with Blaze.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 16.0) [1,204ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    ✗ CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation

[✓] Chrome - develop for the web [8ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13368085-b895.109)

[✓] VS Code (version 1.100.0) [6ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (4 available) [6.4s]
    • Pixel 6a (mobile)               • 29121JEGR04412        • android-arm64  • Android 15 (API 35)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.4.1 24E263
      darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.4.1 24E263
      darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 136.0.7103.93
    ! Error: Browsing on the local area network for GBA iPhone12 202404. Ensure the device is unlocked and
      attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Bhuvnesh’s Apple Watch. Ensure the device is unlocked and
      discoverable via Bluetooth. (code -27)

[✓] Network resources [478ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

b/418696524

### PR DESCRIPTION
**Pull request by jwlilly**
Fix for PR #174374. It was reverted due to failing tests for creating CollectionInfo and CollectionItemInfo using constructors added in API 30. I used the `obtain` method for creating both CollectionInfo and CollectionItemInfo if the API version is lower than 33. The `obtain` method was deprecated in API 33. 

> 
> Updating AccessibilityBridge.java and AccessibilityBridgeTest.java to include AccessibilityNodeInfo.CollectionItemInfo to get TalkBack to announce item indexes for ListViews.
> 
>     Updated the logic for adding CollectionInfo to add when the scrollChildren count is greater than 1. This is an attempt to exclude something like a SingleChildScrollView from getting CollectionInfo added. The only semantics info we can rely on from Android is the hasImplicitScrolling and the number of scrollChildren.
>     Added logic for adding the CollectionItemInfo to ListView children. It first checks to see if the parent node qualifies for CollectionInfo and then adds the CollectionItemInfo to the child view. The index values come from the childrenInTraversalOrder. We aren't currently passing the indexedSemantics into the SemanticsNode. Once those values are available, this can be made more robust.
> 
> The following video includes the new changes with a ListView
>
> https://github.com/user-attachments/assets/b9bf1b80-9f29-40e2-8f33-a08919554b7e
> 
> 
> This video includes the logic with a SingleChildScrollView (no list announcements as expected)
> 
> https://github.com/user-attachments/assets/8fe4dd24-cc5a-4a6b-b4b0-0f371fea20df

Fixes #168651 - This is a minimal fix. A full fix would be to pass the indexedSemantics to the SemanticsNode in Android and build the list with those values but that is a larger effort. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java:1]: In this file can you add a test that is configured for each of the following api levels below 30, 30-33, 34+ that verifies the behavior you expect based on the branching you describe in the pr description. 

Thank you for your original submission and the follow up pr.

**Review by reidbaker — CHANGES_REQUESTED** [review]

File: engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
Comment (jwlilly) [reply engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java:1]: Sure, but I'm not quite sure I would be checking for in each test. The outcome is the same with the CollectionInfo and CollectionItemInfo being created. The only difference is the method that is used to create the objects. Before API 33, the .`obtain` method is used, but that is deprecated in API 33 and they direct you to use a regular constructor

Comment (reidbaker) [reply engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java:1]: My expectation (hope?) is that the assert in the test would be the same for the same test data but the setup would be different. I think the core value is ensuring that if we regressed the code to the state in https://github.com/flutter/flutter/pull/174374 that there is some test that fails clearly.

Comment (jwlilly) [reply engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java:1]: Ok, so are you thinking something like this? 

``` java

@Config(sdk = API_LEVELS.API_33)
  @TargetApi(API_LEVELS.API_33)
  @Test
public void itAddsCollectionInfoAPI33() {
// same test that I currently have but should route to the new constructor 
}

@Config(sdk = API_LEVELS.API_32)
  @TargetApi(API_LEVELS.API_32)
  @Test
public void itAddsCollectionInfoAPI32() {
// same test that I currently have but should route to the .obtain method
}

```

I'm not sure if the test procedures will deliberately swap to different API version to test this, but if it does, I definitely see how this would be beneficial.

File: engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java [hunk 1]
```diff
@@ -907,60 +914,132 @@ public AccessibilityNodeInfo createAccessibilityNodeInfo(int virtualViewId) {
...
+                  ));
+        } else {
+          result.setCollectionItemInfo(
+              new AccessibilityNodeInfo.CollectionItemInfo(
+                  0, // row index
+                  1, // row span
+                  nodeIndex, // column index
+                  1, // column span
+                  semanticsNode.hasFlag(Flag.IS_HEADER) // is heading
+                  ));
```
[the remark this answers is not in the document]
Comment (reidbaker) [reply engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java:1039]: This comment is an improvement in readability.

File: engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java [hunk 2]
```diff
@@ -2217,6 +2218,66 @@ public void itAddsClickActionToSliderNodeInfo() {
...
+    testSemanticsUpdate.sendUpdateToBridge(accessibilityBridge);
+    nodeInfo = accessibilityBridge.createAccessibilityNodeInfo(0);
+    AccessibilityNodeInfo.CollectionInfo collectionInfo = nodeInfo.getCollectionInfo();
+    assertNotNull(collectionInfo);
+
+    boolean rowCount = collectionInfo.getRowCount() == testSemanticsNode.scrollChildren;
+    boolean colCount = collectionInfo.getColumnCount() == 1; // 1 column for a list
+    boolean isHierarchical =
+        !collectionInfo.isHierarchical(); // this should currently always be false
+    assertTrue(rowCount && colCount && isHierarchical);
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java]:
```suggestion
    assertTrue(collectionInfo.getRowCount() == testSemanticsNode.scrollChildren);
    assertTrue(collectionInfo.getColumnCount() == 1); // 1 column for a list
    assertFalse(collectionInfo.isHierarchical());
```

File: engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java [hunk 3]
```diff
@@ -2217,6 +2218,66 @@ public void itAddsClickActionToSliderNodeInfo() {
...
+    // add children to parentTestSemanticsNode
+    TestSemanticsNode childNode1 = new TestSemanticsNode();
+    childNode1.id = 1;
+    childNode1.label = "Test 1";
+    TestSemanticsNode childNode2 = new TestSemanticsNode();
+    childNode2.id = 2;
+    childNode2.label = "Test 2";
+    parentTestSemanticsNode.addChild(childNode1);
+    parentTestSemanticsNode.addChild(childNode2);
+    TestSemanticsUpdate testSemanticsUpdate = parentTestSemanticsNode.toUpdate();
```
[the remark this answers is not in the document]
Comment (reidbaker) [reply engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java:2281]: Agree with this recommendation.

**Review by reidbaker — APPROVED** [review]
Couple of test best practices and we can get this landed. Thank you for your pull request.

File: engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java
Comment (jwlilly) [reply engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java:1]: @reidbaker I went ahead and implemented this. Let me know if that's not what you were thinking

File: engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (jwlilly) [reply engine/src/flutter/shell/platform/android/test/io/flutter/view/AccessibilityBridgeTest.java:2281]: Added in most recent commit. I changed the assertFalse to `assertFalse(nodeInfo.isHeading()` since CollectionItemInfo.isHeading() was deprecated in API 28

File: engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (jwlilly) [reply engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java:1039]: I used `API_LEVELS.API_33` instead of `Build.VERSION_CODES.TIRAMISU`. We are using `API_LEVELS.API_33` in other places so I thought that might more sense

[the remark this answers is not in the document]
Comment (reidbaker) [reply engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java:1039]: That was the correct thing to sorry I was focused on reducing the duplication and cared less about the raw api number. Using API_LEVELS.API_33 is an improvement thank you.

**Review by reidbaker — APPROVED** [review]

**Review by camsim99 — APPROVED** [review]
LGTM! Thanks for getting this re-landed :)
