### PR TITLE
Fix ScrollbarPainter thumbExtent calculation and add padding 

### LINKED ISSUE #13253: Let scrollbars avoid obstructing slivers and media query paddings
Internal: b/144318472

Consider a CustomScrollView with a SliverAppBar and a SliverList and the user wants a scrollbar showing the position inside the SliverList's contents only. 

Let the SliverAppBar report SliverGeometry describing its obstructing and max obstructing extends. Let that get aggregated by the scrollable and bubbled up with a scroll notification so the scrollbar can start below the obstructing area.

### LINKED ISSUE #31430: Incorrect implementation of ScrollMetrics.extentInside getter
## Steps to Reproduce

See following test:

```
import 'package:flutter/widgets.dart';
import 'package:test/test.dart';

void main() {
  test('Expect correct extent metrics when max scroll extent is less than viewport dimension', () {

    // Given
    ScrollMetrics metrics = FixedScrollMetrics(
      axisDirection: AxisDirection.down,
      // User scrolled 1 pixel
      pixels: 1,
      // Viewport is 100
      viewportDimension: 100,
      minScrollExtent: 0,
      // User can scroll max 10 pixels
      maxScrollExtent: 10,
    );

    // Extent before is 1, which is correct
    expect(metrics.extentBefore, 1);

    // Extent inside fails here.
    // According to documentation
    // extentInside should be viewport height
    // as extentBefore and extentAfter are non-zero
    // But it is 10, not 100
    expect(metrics.extentInside, 100);

    // Extent after is 9, which is correct
    expect(metrics.extentAfter, 9);
  });
}
```
On UI it will cause scroll thumb to be always half height of the viewport in cases when there is no too much to scroll.
In those cases scroll thumb should be close to viewport height.

```
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

- Fixed `extentInside` calculation in `ScrollMetrics`
- Added asserts to `extentInside` getter, as well as `ScrollPosition.applyContentDimensions` to enforce `minScrollExtent <= maxScrollExtent`
- Added padding to `ScrollbarPainter`, updated implementation. Took care of some edge cases.
- Changed some scroll bar constants on Cupertino side.

## Related Issues

Fixes #31430, partially fixes #13253 and #25802

## Tests

I added the following tests:

- Scrollbar is not smaller than minLength with large scroll views, if minLength is small 
- When scrolling normally, the size of the scrollbar stays the same, and it scrolls evenly
- mainAxisMargin is respected
- crossAxisMargin & text direction are respected
- Padding works for all scroll directions
- Should scroll towards the right direction
- Handles MediaQuery well

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

## Appendix: Screenshots from iPhone XR running iOS 12.1

1. Both horizontal and vertical scrollbars are visible and overscrolling
Simulator Screen Shot - iPhone XR - 2019-04-30 at 15 00 14

2. Only the horizontal scrollbars is visible and overscrolling
Simulator Screen Shot - iPhone XR - 2019-04-30 at 15 12 06

3. Only the vertical scrollbars is visible and overscrolling
Simulator Screen Shot - iPhone XR - 2019-04-30 at 17 53 40

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 1]
```diff
@@ -450,6 +450,9 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
     if (!nearEqual(_minScrollExtent, minScrollExtent, Tolerance.defaultTolerance.distance) ||
         !nearEqual(_maxScrollExtent, maxScrollExtent, Tolerance.defaultTolerance.distance) ||
         _didChangeViewportDimensionOrReceiveCorrection) {
+      assert(minScrollExtent != null);
+      assert(maxScrollExtent != null);
+      assert(minScrollExtent <= maxScrollExtent);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/scroll_position.dart]: I assume this makes it a breaking change?

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 2]
```diff
@@ -86,13 +92,30 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
...
+  /// Defaults to [EdgeInsets.zero]. Must not be null and offsets from all four
+  /// directions must be greater than or equal to zero.
+  final EdgeInsets padding;
+
+  /// The preferred smallest size the scrollbar can shrink to when the total
+  /// scrollable extent is large and the current visible viewport is small, and the
+  /// viewport is not overscrolled.
+  ///
+  /// Mustn't be null and the value is typically greater than or equal to
+  /// [minOverscrollLength].
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: In current implementation when `minOverscrollLength > minLength`, the minimum normal scrolling length is in fact `minOverscrollLength`: 
```
    double thumbExtent = math.min(effectiveViewport, minOverscrollLength);
    if (before > 0 && after > 0) {
      thumbExtent = math.max(	      thumbExtent = math.max(
        minLength,
        thumbExtent,	        thumbExtent,
        viewport * fractionVisible - 2 * mainAxisMargin,	
      );	      );
      // Thumb extent is no smaller than minLength if scrolling normally.	    
}
```
Should we enforce `minOverscrollLength <= minLength`?

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 3]
```diff
@@ -116,89 +139,109 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
...
+        thumbSize = Size(thickness, thumbExtent);
+        x = textDirection == TextDirection.rtl
+        ? crossAxisMargin + padding.left
+        : size.width - thickness - crossAxisMargin - padding.right;
+        y = thumbOffset;
+        break;
+      case AxisDirection.left:
+        thumbSize = Size(thumbExtent, thickness);
+        x = thumbOffset;
+        y = size.height - thickness - crossAxisMargin - padding.bottom;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: Not sure if we want to honor `crossAxisMargin` in a horizontal scrollbar.

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/scrollbar.dart]: Also the value is *preferred* because it's only a hint, i.e. if it's set to a unreasonably large value, or when `mainAxisMargin` gets too large we won't be able to stick to these min values

**Comment by xster** [comment]
Can you rebase to head to solve the merge conflict?

File: packages/flutter/lib/src/widgets/scroll_position.dart (hunk 1 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/scroll_position.dart]: I think it's ok. Our existing API documentation is already stricter than what these asserts enforce.

File: packages/flutter/lib/src/widgets/scroll_metrics.dart [hunk 4]
```diff
@@ -98,12 +100,23 @@ abstract class ScrollMetrics {
...
+  /// See also:
+  ///
+  /// * [ViewportOffset.applyContentDimensions]
   double get extentInside {
+    assert(maxScrollExtent != null);
+    assert(minScrollExtent != null);
+    assert(minScrollExtent <= maxScrollExtent);
     return math.min(pixels, maxScrollExtent) -
            math.max(pixels, minScrollExtent) +
-           math.min(viewportDimension, maxScrollExtent - minScrollExtent);
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scroll_metrics.dart]: What was this for again? I think we're flipping the previous definition now.

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 5]
```diff
@@ -54,7 +55,12 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
        assert(fadeoutOpacityAnimation != null),
        assert(mainAxisMargin != null),
        assert(crossAxisMargin != null),
-       assert(minLength != null) {
+       assert(minLength != null),
+       assert(padding != null),
+       assert(padding.top >= 0),
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: Instead of doing this, add a EdgeInsets.debugAssertIsValid instance method and call that instead.

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 6]
```diff
@@ -86,13 +92,30 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
...
 
-  /// The smallest size the scrollbar can shrink to when the total scrollable
-  /// extent is large and the current visible viewport is small, and the
-  /// viewport is not overscrolled. Mustn't be null.
+  /// The amount of space by which to inset the scrollbar's start and end, as
+  /// well as its side to the nearest edge, in pixels.
+  ///
+  /// This is typically set to the current [MediaQueryData.padding] to avoid
+  /// partial obstructions such as display notches. If you want additonal
+  /// margins around the scrollbar, see [mainAxisMargin] or [crossAxisMargin].
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: Oh this isn't API breaking :)

We should be very explicit about `padding` being redundant with `mainAxisMargin` and this lets you control the exact padding on each side and *margin are just doubles.

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 2 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/scrollbar.dart]: Ya, I think it's ok to generally add more enforcements to make sure that the relationships between minLength, minOverscrollLength are respected and describe edge cases.

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 7]
```diff
@@ -86,13 +92,30 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
...
+  /// scrollable extent is large and the current visible viewport is small, and the
+  /// viewport is not overscrolled.
+  ///
+  /// Mustn't be null and the value is typically greater than or equal to
+  /// [minOverscrollLength].
   final double minLength;
 
-  /// The smallest size the scrollbar can shrink to when viewport is
-  /// overscrolled. Mustn't be null.
+  /// The preferred smallest size the scrollbar can shrink to when viewport is
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: In case we say 'preferred' describe when do things fall out of the preferred behavior.

File: packages/flutter/lib/src/widgets/scrollbar.dart (hunk 3 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/scrollbar.dart]: sure, why not

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 8]
```diff
@@ -116,89 +139,109 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
...
+        thumbSize = Size(thickness, thumbExtent);
+        x = textDirection == TextDirection.rtl
+          ? crossAxisMargin + padding.left
+          : size.width - thickness - crossAxisMargin - padding.right;
+        y = thumbOffset;
+        break;
+      case AxisDirection.up:
+        thumbSize = Size(thickness, thumbExtent);
+        x = textDirection == TextDirection.rtl
+        ? crossAxisMargin + padding.left
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: fix indents

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 9]
```diff
@@ -116,89 +139,109 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
...
     double inside,
+    double afterInset,
     double after,
     double viewport,
     Canvas canvas,
     Size size,
-    void painter(Canvas canvas, Size size, double thumbOffset, double thumbExtent),
+    AxisDirection direction,
   ) {
+    final double totalInset = beforeInset + afterInset;
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: I think we already have too many terminologies that really mean the same thing between padding, margin and inset. Try to keep it tighter.

File: packages/flutter/test/cupertino/scrollbar_paint_test.dart [hunk 10]
```diff
@@ -7,15 +7,28 @@ import 'package:flutter_test/flutter_test.dart';
 
 import '../rendering/mock_canvas.dart';
 
+const Color _kScrollbarColor = Color(0x99777777);
+
+Widget _buildSingleChildScrollViewWithCupertinoScrollbar({
```
Comment (xster) [inline packages/flutter/test/cupertino/scrollbar_paint_test.dart]:
```dart
Widget _buildSingleChildScrollViewWithCupertinoScrollbar({
  TextDirection textDirection = TextDirection.ltr,
  EdgeInsets padding = EdgeInsets.zero,
  Widget child,
}) {
```

File: packages/flutter/test/widgets/scrollbar_test.dart [hunk 11]
```diff
@@ -0,0 +1,435 @@
...
+    mainAxisMargin: mainAxisMargin,
+    crossAxisMargin: crossAxisMargin,
+    radius: radius,
+    minLength: minLength,
+    minOverscrollLength: minOverscrollLength,
+    fadeoutOpacityAnimation: kAlwaysCompleteAnimation,
+  )..update(scrollMetrics, scrollMetrics.axisDirection);
+}
+
+class _DrawRectOnceCanvas implements Canvas {
```
Comment (xster) [inline packages/flutter/test/widgets/scrollbar_test.dart]: For what it's worth, you ended up reimplementing mockito https://github.com/dart-lang/mockito :) which we use elsewhere in tests (if you search for the word mockito). 

You don't have to change since it's more or less the same length of code for your specific scenario but typically it's easier to use than to spin your own mocks.

File: packages/flutter/test/widgets/scrollbar_test.dart [hunk 12]
```diff
@@ -0,0 +1,435 @@
...
+  void reset() {
+    rect = null;
+  }
+}
+
+void main() {
+  final _DrawRectOnceCanvas testCanvas = _DrawRectOnceCanvas();
+  ScrollbarPainter painter;
+
+  tearDown(testCanvas.reset);
```
Comment (xster) [inline packages/flutter/test/widgets/scrollbar_test.dart]: Instead of doing this, implement setUp and instantiate a new instance of _DrawRectOnceCanvas in there instead. Starting clean is cleaner than cleaning up.

File: packages/flutter/test/widgets/scrollbar_test.dart [hunk 13]
```diff
@@ -0,0 +1,435 @@
...
+      const double minLen = 0;
+
+      painter = _buildPainter(
+        minLength: minLen,
+        minOverscrollLength: minLen,
+        scrollMetrics: defaultMetrics
+      );
+
+      final List<ScrollMetrics> metricsList =
+      <ScrollMetrics> [startingMetrics.copyWith(pixels: 0.01)]
```
Comment (xster) [inline packages/flutter/test/widgets/scrollbar_test.dart]: Fix indents

File: packages/flutter/test/widgets/scrollbar_test.dart [hunk 14]
```diff
@@ -0,0 +1,435 @@
...
+        testCanvas.reset();
+        painter.update(
+          startingMetrics.copyWith(pixels: double.infinity),
+          startingMetrics.axisDirection
+        );
+
+        painter.paint(testCanvas, size);
+        expect(size.height - testCanvas.rect.bottom, margin);
+
+        testCanvas.reset();
```
Comment (xster) [inline packages/flutter/test/widgets/scrollbar_test.dart]: You wouldn't have to do this with mockito because each interaction you verify is taken off the queue. You can also use our mock_canvas

File: packages/flutter/test/cupertino/scrollbar_test.dart [hunk 15]
```diff
@@ -42,25 +45,4 @@ void main() {
       color: const Color(0x15777777),
     ));
   });
-
```
Comment (xster) [inline packages/flutter/test/cupertino/scrollbar_test.dart]: Grouping all the tests is ok, we should still specifically test a CupertinoScrollbar and make sure it works with other cupertino widgets, such as putting a scaffold with a nav bar and a scrollbar under it.

**Review by xster — COMMENTED** [review]
This is great! Awesome
LGTM

File: packages/flutter/lib/src/widgets/scroll_metrics.dart (hunk 4 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/scroll_metrics.dart]: This is to fix #31430. According to the documentation of [ViewportOffset.applyContentDimensions](https://docs.flutter.io/flutter/rendering/ViewportOffset/applyContentDimensions.html):

> The maximum scroll extent has the viewport dimension subtracted from it. For instance, if there is 100.0 pixels of scrollable content, and the viewport is 80.0 pixels high, then the minimum scroll extent will typically be 0.0 and the maximum scroll extent will typically be 20.0, because there's only 20.0 pixels of actual scroll slack.

So `maxScrollExtent - minScrollExtent` is not the size of the content, `maxScrollExtent - minScrollExtent + viewportDimension` is.

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 16]
```diff
@@ -73,26 +83,57 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
...
-  /// The smallest size the scrollbar can shrink to when viewport is
-  /// overscrolled. Mustn't be null.
+  /// The preferred smallest size the scrollbar can shrink to when viewport is
+  /// overscrolled.
+  ///
+  /// When overscrolling, if the size of the scrollbar track in the view port
+  /// is smaller than [minOverscrollLength], the size of the scrollbar may become
+  /// smaller than [minOverscrollLength] in order to fit in the scrollable area.
+  ///
+  /// The value is less than or equal to [minLength] and greater than or equal to 0.
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: Ah ok, disregard the comment above about defaulting the minOverscrollLength.

File: packages/flutter/test/cupertino/scrollbar_paint_test.dart [hunk 17]
```diff
@@ -7,35 +7,92 @@ import 'package:flutter_test/flutter_test.dart';
...
+    await gesture.moveBy(Offset.zero.translate(-_kGestureOffset.dx, -_kGestureOffset.dy));
+    await tester.pump();
+    await tester.pump(const Duration(milliseconds: 500));
+
+    expect(find.byType(CupertinoScrollbar), paints..rrect(
+        color: _kScrollbarColor,
+        rrect: RRect.fromRectAndRadius(
+          const Rect.fromLTWH(
+            800.0 - 3 - 2.5, // Screen width - margin - thickness.
+            44 + 20 + 3.0, // nav bar height + top margin
```
Comment (xster) [inline packages/flutter/test/cupertino/scrollbar_paint_test.dart]: Thanks for the comments

File: packages/flutter/test/material/scrollbar_test.dart [hunk 18]
```diff
@@ -19,34 +19,49 @@ class TestCanvas implements Canvas {
   }
```
Comment (xster) [inline packages/flutter/test/material/scrollbar_test.dart]: Add a general test for the Material Scrollbar as well, to make sure the Scrollbar catches the MediaQuery padding correctly, not just the custom painter.

File: packages/flutter/test/widgets/scrollbar_test.dart [hunk 19]
```diff
@@ -0,0 +1,425 @@
...
+
+class _DrawRectOnceCanvas extends Mock implements Canvas { }
+
+void main() {
+  final _DrawRectOnceCanvas testCanvas = _DrawRectOnceCanvas();
+  ScrollbarPainter painter;
+  Rect captureRect() => verify(testCanvas.drawRect(captureAny, any)).captured.single;
+
+  tearDown(() => painter = null);
+
```
Comment (xster) [inline packages/flutter/test/widgets/scrollbar_test.dart]: nit:

**Review by xster — COMMENTED** [review]
LGTM

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 20]
```diff
@@ -73,26 +83,57 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
...
+  /// Defaults to [EdgeInsets.zero]. Must not be null and offsets from all four
+  /// directions must be greater than or equal to zero.
+  final EdgeInsets padding;
+
+  /// The preferred smallest size the scrollbar can shrink to when the total
+  /// scrollable extent is large and the current visible viewport is small, and the
+  /// viewport is not overscrolled.
+  ///
+  /// When the size of the scrollbar track in the view port is smaller than
+  /// [minLength], the size of the scrollbar may shrink to a smaller size than
```
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/scrollbar.dart]: yeah I'll just refer to it as "scrollbar paint area" as you previously suggested

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 21]
```diff
@@ -73,26 +83,57 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
...
   final Radius radius;
 
-  /// The smallest size the scrollbar can shrink to when the total scrollable
-  /// extent is large and the current visible viewport is small, and the
-  /// viewport is not overscrolled. Mustn't be null.
+  /// The amount of space by which to inset the scrollbar's start and end, as
+  /// well as its side to the nearest edge, in pixels.
+  ///
+  /// This is typically set to the current [MediaQueryData.padding] to avoid
+  /// partial obstructions such as display notches. Contents that overlap
```
[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/scrollbar.dart]: Hmm I guess I was trying to explain how `padding` is different from `mainAxisMargin`. Contents that are covered by the `padding` area is considered not visible when calculating the content's visible percentage while `mainAxisMargin` doesn't affect the visible percentage. Does "[padding] reduces the visible content size to total content size ratio during the scrollbar size calculation, thus reduces the size of the scrollbar. If you only want additional margins around the scrollbar, see [mainAxisMargin], which does not affect the said ratio." sound better, or should I take the second sentence off since it's not too helpful?

[the remark this answers is not in the document]
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/scrollbar.dart]: Removed the second sentence.

**Comment by LongCatIsLooong** [comment]
@xster @HansMuller removed some randomly made-up terms in docs. Could you take a look?

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 22]
```diff
@@ -12,7 +12,10 @@ import 'scroll_metrics.dart';
 
 const double _kMinThumbExtent = 18.0;
 
-/// A [CustomPainter] for painting scrollbars.
+/// A [CustomPainter] for painting scrollbars. The size of the scrollbar along
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: Let the dartdoc's first sentence be a one line summary paragraph.

File: packages/flutter/test/cupertino/scrollbar_paint_test.dart [hunk 23]
```diff
@@ -7,35 +7,93 @@ import 'package:flutter_test/flutter_test.dart';
...
+
+    final TestGesture gesture = await tester.startGesture(tester.getCenter(find.byType(ListView)));
+    await gesture.moveBy(_kGestureOffset);
+    // Move back to original position.
+    await gesture.moveBy(Offset.zero.translate(-_kGestureOffset.dx, -_kGestureOffset.dy));
+    await tester.pump();
+    await tester.pump(const Duration(milliseconds: 500));
+
+    expect(find.byType(CupertinoScrollbar), paints..rrect(
+        color: _kScrollbarColor,
```
Comment (xster) [inline packages/flutter/test/cupertino/scrollbar_paint_test.dart]: 2 indents

File: packages/flutter/test/material/scrollbar_paint_test.dart [hunk 24]
```diff
@@ -7,32 +7,74 @@ import 'package:flutter/material.dart';
 
 import '../rendering/mock_canvas.dart';
 
+Widget _buildSingleChildScrollViewWithScrollbar({
+    TextDirection textDirection = TextDirection.ltr,
```
Comment (xster) [inline packages/flutter/test/material/scrollbar_paint_test.dart]: 2 indents

**Review by xster — COMMENTED** [review]
LGTM

File: packages/flutter/lib/src/widgets/scroll_metrics.dart [hunk 25]
```diff
@@ -60,14 +60,16 @@ abstract class ScrollMetrics {
   ///
   /// The actual [pixels] value might be [outOfRange].
   ///
-  /// This value can be negative infinity, if the scroll is unbounded.
+  /// This value must not be null and must be less than or equal to [maxScrollExtent].
+  /// It can be negative infinity, if the scroll is unbounded.
   double get minScrollExtent;
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/scroll_metrics.dart]: FixedScrollMetrics should assert that these constraints are true.

File: packages/flutter/lib/src/widgets/scroll_metrics.dart [hunk 26]
```diff
@@ -60,14 +60,16 @@ abstract class ScrollMetrics {
...
 
   /// The maximum in-range value for [pixels].
   ///
   /// The actual [pixels] value might be [outOfRange].
   ///
-  /// This value can be infinity, if the scroll is unbounded.
+  /// This value must not be null and must be greater than or equal to
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/scroll_metrics.dart]: FixedScrollMetrics should assert that these constraints are true.

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 27]
```diff
@@ -73,26 +84,56 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
   /// Mustn't be null.
   final Animation<double> fadeoutOpacityAnimation;
 
-  /// Distance from the scrollbar's start and end to the edge of the viewport in
-  /// pixels. Mustn't be null.
+  /// Distance from the scrollbar's start and end to the edge of the viewport
+  /// in pixels. It affects the amount of available paint area.
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: pixels => logical pixels

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 28]
```diff
@@ -73,26 +84,56 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
...
   final double minLength;
 
-  /// The smallest size the scrollbar can shrink to when viewport is
-  /// overscrolled. Mustn't be null.
+  /// The preferred smallest size the scrollbar can shrink to when viewport is
+  /// overscrolled.
+  ///
+  /// When overscrolling, the size of the scrollbar may shrink to a smaller size
+  /// than [minOverscrollLength] to fit in the available paint area. E.g., when
+  /// [minOverscrollLength] is `double.infinite`, it will not be respected if
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: double.infinite => double.infinity

File: packages/flutter/lib/src/widgets/scrollbar.dart [hunk 29]
```diff
@@ -116,64 +157,67 @@ class ScrollbarPainter extends ChangeNotifier implements CustomPainter {
...
-      // Thumb extent reflects fraction of content visible, as long as this
-      // isn't less than the absolute minimum size.
-      final double fractionVisible = inside / (before + inside + after);
-      thumbExtent = math.max(
-        thumbExtent,
-        viewport * fractionVisible - 2 * mainAxisMargin,
-      );
+    // Thumb extent reflects fraction of content visible, as long as this
+    // isn't less than the absolute minimum size.
+    // contentExtent >= viewportDimension, so (contentExtent - mainAxisPadding) > 0
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/scrollbar.dart]: NICE

File: packages/flutter/test/widgets/slivers_evil_test.dart [hunk 30]
```diff
@@ -73,94 +73,99 @@ class TestViewportScrollPosition extends ScrollPositionWithSingleContext {
...
+                    ],
+                  );
+                },
+              ),
+            ),
           ),
-        ),
-      ),
-    ));
+        )
```
Comment (HansMuller) [inline packages/flutter/test/widgets/slivers_evil_test.dart]: restore trailing commas

File: packages/flutter/test/widgets/slivers_evil_test.dart [hunk 31]
```diff
@@ -73,94 +73,99 @@ class TestViewportScrollPosition extends ScrollPositionWithSingleContext {
...
-      child: ScrollConfiguration(
-        behavior: TestBehavior(),
-        child: Scrollbar(
-          child: Scrollable(
-            axisDirection: AxisDirection.down,
-            physics: const TestScrollPhysics(),
-            viewportBuilder: (BuildContext context, ViewportOffset offset) {
-              return Viewport(
+    await tester.pumpWidget(
+      MediaQuery(
```
Comment (HansMuller) [inline packages/flutter/test/widgets/slivers_evil_test.dart]: I'm hoping that the only change to this test is just adding the MediaQuery

**Review by HansMuller — COMMENTED** [review]
This looks good, although I'm not claiming to have combed through all of the new tests. Just some minor feedback.

File: packages/flutter/test/widgets/slivers_evil_test.dart (hunk 31 above)
Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/slivers_evil_test.dart]: I think that's the case. Should I make the `MediaQuery` dependency optional?

Comment (HansMuller) [reply packages/flutter/test/widgets/slivers_evil_test.dart]: It's fine as is; just difficult to read github diffs sometimes.

**Review by HansMuller — APPROVED** [review]
LGTM
