### PR TITLE
Fixed improper assertion of maxCrossAxisExtent

### LINKED ISSUE #75093: Improper assertion in maxCrossAxisExtent in SliverGridDelegateWithMaxCrossAxisExtent
The assertion in ```SliverGridDelegateWithMaxCrossAxisExtent``` checks for ```maxCrossAxisExtent >= 0```  instead of ```maxCrossAxisExtent > 0```

### PR DESCRIPTION
**Pull request by chinmoy12c**
The assertion in SliverGridDelegateWithMaxCrossAxisExtent checks for maxCrossAxisExtent >= 0 instead of maxCrossAxisExtent > 0

Fixes #75093 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
@chinmoy12c Can you please add a test for this to make sure that we never break this again? Thanks!

**Comment by chinmoy12c** [comment]
> @chinmoy12c Can you please add a test for this to make sure that we never break this again? Thanks!

Hey @goderbauer actually I'm facing some issues while writing the test, 
I'm using this test ,

```
await tester.pumpWidget(
      Directionality(
        textDirection: TextDirection.ltr,
        child: GridView.extent(
          maxCrossAxisExtent: 0,
        ),
      ),
    );

expect(tester.takeException(), isAssertionError);
```

The problem is that the pumpWidget still throws even after using tester.takeException(), it does not seem to consume the assertion failure. :confused: 

This is the complete debug output - 

<details open>
<summary> debug output </summary>

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 450 pos 15:
'maxCrossAxisExtent != null && maxCrossAxisExtent > 0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      new SliverGridDelegateWithMaxCrossAxisExtent (package:flutter/src/rendering/sliver_grid.dart:450:15)
#3      new GridView.extent (package:flutter/src/widgets/scroll_view.dart:1959:23)
#4      main.<anonymous closure> (file:///home/Chinmoy/MasterFiles/openSource/flutter/packages/flutter/test/widgets/grid_view_test.dart:791:25)
#5      main.<anonymous closure> (file:///home/Chinmoy/MasterFiles/openSource/flutter/packages/flutter/test/widgets/grid_view_test.dart:787:111)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from class _AssertionError and package:stack_trace)

The test description was:
  SliverGridDelegateWithMaxCrossAxisExtent throws assertion error when maxCrossAxisExtent is 0
```

</details>

**Comment by chinmoy12c** [comment]
@goderbauer PR is ready for review :smile:

File: packages/flutter/lib/src/rendering/sliver_grid.dart [hunk 1]
```diff
@@ -447,7 +447,7 @@ class SliverGridDelegateWithMaxCrossAxisExtent extends SliverGridDelegate {
     this.crossAxisSpacing = 0.0,
     this.childAspectRatio = 1.0,
     this.mainAxisExtent,
-  }) : assert(maxCrossAxisExtent != null && maxCrossAxisExtent >= 0),
+  }) : assert(maxCrossAxisExtent != null && maxCrossAxisExtent > 0),
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/sliver_grid.dart:450]: We also need to update the docs above to match this.

**Review by goderbauer — COMMENTED** [review]
/cc @Piinks, you recently changed `_debugAssertIsValid` to disallow zero. Do you remember why? Should we do the same here?

File: packages/flutter/lib/src/rendering/sliver_grid.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/lib/src/rendering/sliver_grid.dart:450]: Hrm, looks like I did this in https://github.com/flutter/flutter/pull/60726 which was resolving a bunch of trivial bugs. Looks like https://github.com/flutter/flutter/issues/13861 was the motivation... but looking now 7 months later I am not sure it makes sense. Or at least I cannot remember. Let me check a few things to see if I can jog my memory. 😕

Comment (Piinks) [reply packages/flutter/lib/src/rendering/sliver_grid.dart:450]: Ah, that change was to assert the `crossAxisExtent` of the SliverConstraints provided to `performLayout`. This is a contradiction on `maxCrossAxisExtent`.
I did a bit of archaeology, and it looks like the constructor assert was added in https://github.com/flutter/flutter/pull/9945 which asserts it is >= 0
At that point the assert that `maxCrossAxisExtent > 0` was already in `_debugAssertIsValid`, originating all the way back in #7780
So I think this is a bug that has been around for quite a while! Nice find @chinmoy12c!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Comment by chinmoy12c** [comment]
Hey @Piinks, can you please merge this PR :smile: .
