### PR TITLE
Release cache lock for commands after required artifacts are downloaded

### LINKED ISSUE #20850: flutter --help should not depend on the lock file
## Steps to Reproduce

In `terminal 1`, start a long-running process, like "flutter build ios" etc.
Meanwhile, in `terminal 2`, try to get help for another / next flutter command you want to learn about:

```
$ flutter --help
Waiting for another flutter command to release the startup lock...
```

Same goes for `flutter --version` & `flutter doctor`.

This is even a global setting, so switching out of the project directory will not fix it.

I understand the need for preventing cross-process access to the same resources, but the help system, version number and basic diagnostics shouldn't be affected by this.

## flutter doctor

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.26.1)
[✓] Connected devices (2 available)

• No issues found!
```

### LINKED ISSUE #42225: Flutter command line cannot be used with multiple instances.
When i tried to run two flutter projects at a time the lock has been set to command line and only one project started running.then it displays message as "Waiting for another flutter command to release the startup lock..." .When the one project takes a long time to build app the next project can't out from waiting state. 

simple you can get this result using:
1)open two cmd
2)run on both flutter doctor
3)one get in this state
```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18990.1],
    locale en-US)
    • Flutter version 1.9.1+hotfix.4 at D:\software\flutter
    • Framework revision cc949a8e8b (11 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Pratik\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\Pratik\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • Redmi 4 • 4d78c0c57cf4 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!
```

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Release the cache lock for commands after required artifacts are downloaded.
Keep the lock for `precache`.

## Related Issues
Fixes https://github.com/flutter/flutter/issues/20850
Fixes https://github.com/flutter/flutter/issues/42225

## Tests

Updated existing cache tests.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/build_ios.dart [hunk 1]
```diff
@@ -58,6 +59,8 @@ class BuildIOSCommand extends BuildSubCommand {
 
   @override
   Future<FlutterCommandResult> runCommand() async {
+    Cache.releaseLockEarly();
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/build_ios.dart:62]: The cache is only for downloading artifacts (I think). Could we release the cache automatically after checking for cache updates? that way it wouldn't need to be done adhoc in each subcommand, and would be able to skip the cache for commands that don't download anything (like --version)

Comment (jmagman) [reply packages/flutter_tools/lib/src/commands/build_ios.dart:62]: That makes sense.  The one-off I see is test command explicitly running [`await globals.cache.updateAll(await requiredArtifacts);`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/test.dart#L159) which is causing it to check for updates twice.

(Introduced at https://github.com/flutter/flutter/pull/30254/files#diff-57bf7f0d5a70ab392ae3047369120c83R102).

Comment (jmagman) [reply packages/flutter_tools/lib/src/commands/build_ios.dart:62]: Also `precache` probably needs it re-locked.

File: packages/flutter_tools/lib/src/cache.dart [hunk 2]
```diff
@@ -222,8 +221,11 @@ class Cache {
     }
   }
 
-  /// Releases the lock. This is not necessary unless the process is long-lived.
-  static void releaseLockEarly() {
+  /// Releases the lock.
+  ///
+  /// This happens automatically on startup (see [FlutterCommand.verifyThenRunCommand])
+  /// after the command's required artifacts are updated.
+  static void releaseLock() {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/cache.dart:228]: Remove "early" semantics.

File: packages/flutter_tools/lib/src/commands/precache.dart [hunk 3]
```diff
@@ -111,6 +111,11 @@ class PrecacheCommand extends FlutterCommand {
 
   @override
   Future<FlutterCommandResult> runCommand() async {
+    // Re-lock the cache.
+    if (globals.platform.environment['FLUTTER_ALREADY_LOCKED'] != 'true') {
+      await Cache.lock();
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/precache.dart:116]: Pre-cache still needs the cache lock.  I tested this manually and confirmed two concurrent `precache` commands wait for each other.

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 4]
```diff
@@ -810,6 +810,7 @@ abstract class FlutterCommand extends Command<void> {
       await project.ensureReadyForPlatformSpecificTooling(checkProjects: true);
     }
 
+    Cache.releaseLock();
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart:813]: This is the magic line, correct?

File: packages/flutter_tools/lib/src/commands/test.dart [hunk 5]
```diff
@@ -156,7 +156,6 @@ class TestCommand extends FlutterCommand {
 
   @override
   Future<FlutterCommandResult> runCommand() async {
-    await globals.cache.updateAll(await requiredArtifacts);
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/test.dart:159]: Unless I'm totally missing something, this did a second required artifacts update check.  When I stepped through it it called `updateAll` with the same artifacts twice.

File: packages/flutter_tools/lib/src/runner/flutter_command.dart (hunk 4 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart:813]: Yup that's the good stuff.

Comment (jmagman) [reply packages/flutter_tools/lib/src/runner/flutter_command.dart:813]: I'll add a comment.

File: packages/flutter_tools/lib/src/commands/test.dart (hunk 5 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/test.dart:159]: odd...

I'm sure that is my fault

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 6]
```diff
@@ -806,8 +806,12 @@ abstract class FlutterCommand extends Command<void> {
 
     if (shouldRunPub) {
       await pub.get(context: PubContext.getVerifyContext(name));
+      // All done updating dependencies. Release the cache lock.
+      Cache.releaseLock();
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart:810]: Moved `releaseLock` so it can run before `ensureReadyForPlatformSpecificTooling`.

File: packages/flutter_tools/lib/src/commands/precache.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/commands/precache.dart:116]: Could you add a command test for the re-lock? somehow..

**Review by jonahwilliams — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/commands/precache.dart (hunk 3 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/commands/precache.dart:116]: Added two new tests.  Kind of lame but I needed:
```
  @visibleForTesting
  static bool isLocked() {
    return _lock != null;
  }
```
