### PR TITLE
Do not crash when toggling Semantics on, off, on

### LINKED ISSUE #13957: Toggling semantics debugger leads to crash
Steps to reproduce:
1. Launch Stocks
2. Open drawer
3. Tap Settings
4. Tap "Show semantics overlay" three times (on, off, on)

```
I/flutter (20775): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (20775): The following assertion was thrown during a scheduler callback:
I/flutter (20775): 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 797 pos 12:
I/flutter (20775): 'owner._nodes.containsKey(id)': is not true.
I/flutter (20775): 
I/flutter (20775): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20775): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20775): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20775):   https://github.com/flutter/flutter/issues/new
I/flutter (20775): 
I/flutter (20775): When the exception was thrown, this was the stack:
I/flutter (20775): #2      SemanticsNode.detach (package:flutter/src/semantics/semantics.dart:797:12)
I/flutter (20775): #3      AbstractNode.dropChild (package:flutter/src/foundation/node.dart:143:13)
I/flutter (20775): #4      SemanticsNode._replaceChildren (package:flutter/src/semantics/semantics.dart:706:27)
I/flutter (20775): #5      SemanticsNode.updateWith (package:flutter/src/semantics/semantics.dart:935:5)
I/flutter (20775): #6      RenderSemanticsGestureHandler.assembleSemanticsNode (package:flutter/src/rendering/proxy_box.dart:2748:10)
I/flutter (20775): #7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3190:13)
I/flutter (20775): #8      _SyncIterator.moveNext (dart:core-patch/dart:core/core_patch.dart:149)
I/flutter (20775): #9      List.addAll (dart:core-patch/dart:core/growable_array.dart:188)
I/flutter (20775): #10     _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3094:16)
I/flutter (20775): #11     _SyncIterator.moveNext (dart:core-patch/dart:core/core_patch.dart:149)
I/flutter (20775): #12     Iterable.single (dart:core/iterable.dart:512)
I/flutter (20775): #13     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2275:96)
I/flutter (20775): #14     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:872:16)
I/flutter (20775): #15     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:274:19)
I/flutter (20775): #16     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:613:22)
I/flutter (20775): #17     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (20775): #18     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:921:15)
I/flutter (20775): #19     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:861:9)
I/flutter (20775): #20     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:773:5)
I/flutter (20775): #21     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:120)
I/flutter (20775): #22     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:109)
I/flutter (20775): (elided 2 frames from class _AssertionError)
I/flutter (20775): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

cc @goderbauer

### PR DESCRIPTION
**Pull request by goderbauer**
Cause of the crash are custom `assembleSemanticsNode` implementations that create nodes without properly disposing them when semantics are turned off. Next time semantics are turned on, those out-of-date nodes are incorrectly assumed to be up-to-date and the app crashes...

Fixes https://github.com/flutter/flutter/issues/13957.

/cc @yjbanov @Hixie

### CODE REVIEW

File: packages/flutter/lib/src/rendering/object.dart [hunk 1]
```diff
@@ -2399,7 +2403,9 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
   /// `children` to it.
   ///
   /// Subclasses can override this method to add additional [SemanticsNode]s
-  /// to the tree.
+  /// to the tree. If new [SemanticsNode]s are instantiated in this method
+  /// you'll also have to override [clearSemantics] and dispose those nodes
```
Comment (yjbanov) [inline packages/flutter/lib/src/rendering/object.dart]: nit: dispose of

File: packages/flutter/test/widgets/scrollable_semantics_test.dart [hunk 2]
```diff
@@ -37,10 +37,12 @@ void main() {
 
     await flingDown(tester);
     expect(semantics, includesNodeWith(actions: <SemanticsAction>[SemanticsAction.scrollUp, SemanticsAction.scrollDown]));
+
+    semantics.dispose();
```
Comment (yjbanov) [inline packages/flutter/test/widgets/scrollable_semantics_test.dart]: What do you think of adding an `assert` in the constructor of `SemanticsTester` making sure that the semantics is off, and throwing something along the lines of "Semantics is already turn on. It is possible that a previous unit test failed to call `semantics.dispose` before it finished".

Also, maybe these should be moved into `setUp` so they are called regardless of whether the test succeeds or fails?

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
lgtm

File: packages/flutter/lib/src/rendering/object.dart [hunk 3]
```diff
@@ -2220,6 +2220,10 @@ abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin im
   /// Removes all semantics from this render object and its descendants.
   ///
   /// Should only be called on objects whose [parent] is not a [RenderObject].
+  ///
+  /// Override this method if you instantiate new [SemanticsNode]s in an
+  /// overridden [assembleSemanticsNode] method to dispose those nodes.
```
Comment (Hixie) [inline packages/flutter/lib/src/rendering/object.dart]: nit: comma before "to", otherwise you're saying that it should be overridden (but not saying why), if the person is disposing the nodes in their assembleSemanticsNode. :-)

File: packages/flutter/lib/src/rendering/object.dart (hunk 1 above)
Comment (Hixie) [inline packages/flutter/lib/src/rendering/object.dart]: `you'll .. there` -> `they must be disposed in [clearSemantics]`. We prefer the passive voice, because the reader may not be the person who wrote the code.

**Comment by Hixie** [comment]
Can we make the place where we used to crash catch this case and say something about maybe something needs to be disposed, or something?

File: packages/flutter/test/widgets/scrollable_semantics_test.dart (hunk 2 above)
Comment (goderbauer) [reply packages/flutter/test/widgets/scrollable_semantics_test.dart]: I wish we could turn on semantics in setUp and turn it off again in tearDown. The former doesn't work though because we need an instance of WidgetTester to do that. Nevertheless, I refactored the code a little to do at least the dispose in tearDown. 

Adding the assert should probably be done in a separate PR as it affects many tests. Also not sure if we really want it. In theory you want to be able to test that everything works even if you have multiple semantics listeners (not that we currently do that anywhere).

File: packages/flutter/lib/src/rendering/object.dart (hunk 3 above)
Comment (goderbauer) [reply packages/flutter/lib/src/rendering/object.dart]: Thanks for including a grammatical explanation!

File: packages/flutter/test/widgets/scrollable_semantics_test.dart (hunk 2 above)
Comment (yjbanov) [reply packages/flutter/test/widgets/scrollable_semantics_test.dart]: I see. nvm then.
