### PR TITLE
Change iOS device discovery from polling to long-running observation

### LINKED ISSUE #56826: xcdevice is generating a `dyld_shared_cache_arm64` recovered file every ~30 seconds while IDE open
## Steps to Reproduce

1. Open Android Studio or VSCode，Make sure the flutter process is running.
2. Wait for the hard drive to become full.
3. Restart your computer.
4. Open the trash.

## Logs

```
null
```

## Screenshot

image

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/abel/develop/flutter
    • Framework revision e6b34c2b5c (8 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/abel/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/abel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

### PR DESCRIPTION
**Pull request by jmagman**
## Description

For daemon iOS device polling, change periodic `xcdevice list` calls to a long-running `xcdevice observe` call.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/56826

## Tests
- xcdevice.observedDeviceEvents tests
- start polling devices test
- ItemListNotifier tests

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 1]
```diff
@@ -287,7 +304,100 @@ class XCDevice {
...
+  }
+
+  // Attach: d83d5bc53967baa0ee18626ba87b6254b2ab5418
+  // Detach: d83d5bc53967baa0ee18626ba87b6254b2ab5418
+  final RegExp _observationIdentifierPattern = RegExp(r'^(\w*): (\w*)$');
+
+  Future<void> _startObservingTetheredIOSDevices() async {
+    try {
+      // Run in interactive mode (via script) to convince
+      // xcdevice it has a terminal attached and pipe stdout.
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/macos/xcode.dart:339]: Learned this trick from https://github.com/flutter/flutter/pull/12079/files#diff-5a9a07600dceb28cbe887a5a64a24b0aR502-R504.

File: packages/flutter_tools/lib/src/device.dart [hunk 2]
```diff
@@ -289,14 +290,17 @@ abstract class PollingDeviceDiscovery extends DeviceDiscovery {
...
+
+  @protected
+  ItemListNotifier<Device> deviceNotifier;
+
   Timer _timer;
 
   Future<List<Device>> pollingGetDevices({ Duration timeout });
 
-  void startPolling() {
+  Future<void> startPolling() async {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/device.dart:301]: g3 PollingDeviceDiscovery subclasses don't override `startPolling` or `stopPolling`.

File: packages/flutter_tools/lib/src/device.dart [hunk 3]
```diff
@@ -289,14 +290,17 @@ abstract class PollingDeviceDiscovery extends DeviceDiscovery {
   static const Duration _pollingTimeout = Duration(seconds: 30);
 
   final String name;
-  ItemListNotifier<Device> _items;
+
+  @protected
+  ItemListNotifier<Device> deviceNotifier;
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/device.dart:295]: Renamed `_items` -> `deviceNotifier`

File: packages/flutter_tools/lib/src/device.dart [hunk 4]
```diff
@@ -289,14 +290,18 @@ abstract class PollingDeviceDiscovery extends DeviceDiscovery {
   static const Duration _pollingTimeout = Duration(seconds: 30);
 
   final String name;
-  ItemListNotifier<Device> _items;
+
+  @protected
+  @visibleForTesting
+  ItemListNotifier<Device> deviceNotifier;
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/device.dart:296]: Renamed `_items` -> `deviceNotifier`

File: packages/flutter_tools/lib/src/base/utils.dart [hunk 5]
```diff
@@ -104,6 +104,13 @@ class ItemListNotifier<T> {
     removedItems.forEach(_removedController.add);
   }
 
+  void removeItem(T item) {
+    if (_items.contains(item)) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/base/utils.dart:108]: nit, you can simplify this a bit since `List.remove` returns whether it successfully removed the item:

```
if (_items.remove(item)) {
  _removedController.add(item);
}
```

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 6]
```diff
@@ -35,21 +36,84 @@ class IOSDevices extends PollingDeviceDiscovery {
...
+
+    _observedDeviceEventsSubscription ??= _xcdevice.observedDeviceEvents().listen(
+      _onDeviceEvent,
+      onError: (dynamic error, StackTrace stack) {
+        _logger.printTrace('Process exception running xcdevice observe:\n$error');
+      }, onDone: () {
+      // If the xcdevice process is killed, restart it.
+      _logger.printTrace('xcdevice observe stopped, restarting');
+      startPolling();
+    },
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/devices.dart:85]:
```suggestion
      },
```

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/ios/devices.dart:85]: ... or something like that

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 7]
```diff
@@ -35,21 +36,84 @@ class IOSDevices extends PollingDeviceDiscovery {
...
+    deviceNotifier.updateWithNewList(await pollingGetDevices());
+
+    _observedDeviceEventsSubscription ??= _xcdevice.observedDeviceEvents().listen(
+      _onDeviceEvent,
+      onError: (dynamic error, StackTrace stack) {
+        _logger.printTrace('Process exception running xcdevice observe:\n$error');
+      }, onDone: () {
+      // If the xcdevice process is killed, restart it.
+      _logger.printTrace('xcdevice observe stopped, restarting');
+      startPolling();
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/devices.dart:84]: So I'm understanding this correctly: since we're relying on a single long running process now, it needs to restart in case it goes down unexpectedly, otherwise IDEs wouldn't be able to discover new iOS devices without restarting - right?

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/devices.dart:84]: That's it.

File: packages/flutter_tools/lib/src/ios/devices.dart (hunk 6 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/devices.dart:85]: Android Studio's auto indent is confused by this one.  Will fix.

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 8]
```diff
@@ -74,15 +74,20 @@ class IOSDevices extends PollingDeviceDiscovery {
...
         _logger.printTrace('Process exception running xcdevice observe:\n$error');
       }, onDone: () {
-      // If the xcdevice process is killed, restart it.
-      _logger.printTrace('xcdevice observe stopped, restarting');
-      startPolling();
-    },
+        _logger.printTrace('xcdevice observe stopped, restarting');
+
+        // If the xcdevice process is killed, give it a few seconds and restart it.
+        Timer(const Duration(seconds: 1), () {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/devices.dart:87]: What if the device discovery exits immediately on start up (something is broken). Will this keep scheduling work in a loop? Likewise if this is killed as part of tear down.

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/devices.dart:87]: `PollingDeviceDiscovery` polling currently schedules a timer every 4 seconds to call device-specific discovery code, so that's the existing behavior.  It depends what we want the behavior to be.  If I `killall` xcdevice (exits 137), I would expect it to get rescheduled and the IDE not to need to be restarted.  However if it just fails in some other way, rerunning it probably won't help?  @zanderso What do you think?

Restarting after `stopPolling` is bad though...

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/ios/devices.dart:87]: Its a bit of a tricky situation. How common is it for this process to go down during an IDE session? It might be less risky to log a message and move on

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/devices.dart:87]: I never saw it organically go down in my testing, but I also never saw my hard drive fill up with `xcdevice` caches described in #56826.

Good opportunity for metrics?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/ios/devices.dart:87]: yeah, if we're not sure lets measure

Comment (zanderso) [reply packages/flutter_tools/lib/src/ios/devices.dart:87]: It looks like `close()` on the `StreamController` for this `Stream` isn't called, so how does the 'onDone' callback get invoked?

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 9]
```diff
@@ -287,7 +306,84 @@ class XCDevice {
...
+
+  // Attach: d83d5bc53967baa0ee18626ba87b6254b2ab5418
+  // Detach: d83d5bc53967baa0ee18626ba87b6254b2ab5418
+  final RegExp _observationIdentifierPattern = RegExp(r'^(\w*): (\w*)$');
+
+  Future<void> _startObservingTetheredIOSDevices() async {
+    try {
+      // Run in interactive mode (via script) to convince
+      // xcdevice it has a terminal attached in order to redirect stdout.
+      _deviceObservationProcess = await _processUtils.start(
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/macos/xcode.dart:329]: Can you check/assert somehow that you're not blowing away your handle to an active process?

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 10]
```diff
@@ -287,7 +312,95 @@ class XCDevice {
...
+        <String>[
+          'script',
+          '-t',
+          '0',
+          '/dev/null',
+          'xcrun',
+          'xcdevice',
+          'observe',
+          '--both',
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/macos/xcode.dart:348]: I also changed this to `--both` to reflect what I just did in https://github.com/flutter/flutter/pull/58257/files#diff-8d108d6a887a4f5b74f7c7d77003e795R97.  Wireless devices aren't being sufaced yet, so if one attaches it will kick off an unnecessary fetch.  Should be rare.

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 9 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcode.dart:339]: Done.

File: packages/flutter_tools/lib/src/ios/devices.dart (hunk 8 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/devices.dart]: It is now.  See comment at https://github.com/flutter/flutter/pull/58137#discussion_r432732711.

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 11]
```diff
@@ -287,7 +312,95 @@ class XCDevice {
...
+        ],
+      );
+
+      _deviceObservationProcess.stdout
+        .transform<String>(utf8.decoder)
+        .transform<String>(const LineSplitter())
+        .listen((String line) async {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/macos/xcode.dart:355]: nit: doesn't need to be async

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 12]
```diff
@@ -287,7 +312,95 @@ class XCDevice {
...
+          }
+        }
+      });
+      _deviceObservationProcess.stderr
+        .transform<String>(utf8.decoder)
+        .transform<String>(const LineSplitter())
+        .listen((String line) {
+        _logger.printTrace('xcdevice observe error: $line');
+      });
+      unawaited(_deviceObservationProcess.exitCode.whenComplete(() async {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/macos/xcode.dart:384]: consider changing to `then` to add the exit code to a trace output.

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 13]
```diff
@@ -287,7 +312,95 @@ class XCDevice {
...
+    return _deviceIdentifierByEvent.stream;
+  }
+
+  // Attach: d83d5bc53967baa0ee18626ba87b6254b2ab5418
+  // Detach: d83d5bc53967baa0ee18626ba87b6254b2ab5418
+  final RegExp _observationIdentifierPattern = RegExp(r'^(\w*): (\w*)$');
+
+  Future<void> _startObservingTetheredIOSDevices() async {
+    try {
+      if (_deviceObservationProcess != null) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/macos/xcode.dart:333]: should this be `== null` ? This gets called from the `listen` from `_setupDeviceIdentifierByEventStream`, but the whenDone nulls out the process: https://github.com/flutter/flutter/pull/58137/files#diff-ebc648b2067d73f2af30539f5d3a59faR389

File: packages/flutter_tools/lib/src/macos/xcode.dart [hunk 14]
```diff
@@ -287,7 +312,95 @@ class XCDevice {
...
+        if (_deviceIdentifierByEvent.hasListener) {
+          // Tell listeners the process died.
+          await _deviceIdentifierByEvent.close();
+        }
+        _deviceObservationProcess = null;
+
+        // Reopen it so new listeners can resume polling.
+        _setupDeviceIdentifierByEventStream();
+      }));
+    } on ProcessException catch (exception) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/macos/xcode.dart:394]: these should grab the stackTrace too and pass it to addError

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 13 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcode.dart:333]: It should always be null since as you saw the `whenDone` should handle nulling it out.
https://github.com/flutter/flutter/pull/58137#discussion_r432661646
> Can you check/assert somehow that you're not blowing away your handle to an active process?

I think the concern is there would be a logic error where `_startObservingTetheredIOSDevices` could be called twice without the process exiting.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/macos/xcode.dart:333]: Oops, I forgot how != worked briefly...

File: packages/flutter_tools/lib/src/macos/xcode.dart (hunk 12 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/macos/xcode.dart:384]: Will also cancel the stdout and stdrerr subscriptions in there.

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 15]
```diff
@@ -35,21 +36,83 @@ class IOSDevices extends PollingDeviceDiscovery {
...
+
+    // Start by populating all currently attached devices.
+    deviceNotifier.updateWithNewList(await pollingGetDevices());
+
+    // cancel any outstanding subscriptions.
+    await _observedDeviceEventsSubscription?.cancel();
+    _observedDeviceEventsSubscription = _xcdevice.observedDeviceEvents().listen(
+      _onDeviceEvent,
+      onError: (dynamic error, StackTrace stack) {
+        _logger.printTrace('Process exception running xcdevice observe:\n$error');
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/ios/devices.dart:82]: I believe the stack traces that @jonahwilliams is asking for below will end up here, so consider printing them a long with `error`.

**Review by zanderso — APPROVED** [review]
lgtm after addressing @jonahwilliams comments.

**Review by jonahwilliams — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/device.dart [hunk 16]
```diff
@@ -327,23 +332,23 @@ abstract class PollingDeviceDiscovery extends DeviceDiscovery {
...
   }
 
   Stream<Device> get onRemoved {
-    _items ??= ItemListNotifier<Device>();
-    return _items.onRemoved;
+    deviceNotifier ??= ItemListNotifier<Device>();
+    return deviceNotifier.onRemoved;
   }
 
   void dispose() => stopPolling();
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/device.dart:354]: Shouldn't this be async now?

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 17]
```diff
@@ -35,21 +36,83 @@ class IOSDevices extends PollingDeviceDiscovery {
...
+    Logger logger,
   }) : _platform = platform ?? globals.platform,
        _xcdevice = xcdevice ?? globals.xcdevice,
        _iosWorkflow = iosWorkflow ?? globals.iosWorkflow,
+       _logger = logger ?? globals.logger,
        super('iOS devices');
 
+  @override
+  void dispose() {
+    _observedDeviceEventsSubscription?.cancel();
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/ios/devices.dart:48]: Should this not call `super.dispose()`?

Comment (tvolkert) [reply packages/flutter_tools/lib/src/ios/devices.dart:48]: Also, if the super signature was async, this would just be `await stopPolling()`
