### PR TITLE
Fix `iconTheme` in `AppBar` doesn't apply custom `Colors.white` in the dark mode for M3

### LINKED ISSUE #130485: [Material3] AppBar does not respect `foregroundColor` or `iconTheme` for leading and actions in some cases
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new empty `MaterialApp` with `Scaffold` and `AppBar`.
2. Set `foregroundColor` to `Colors.black87` in light theme, or `Colors.white` in dark theme. (Those are the `kDefaultIconLightColor` and `kDefaultIconDarkColor`).
3. Set `ThemeData` with `useMaterial3: true`.
4. Add some leading or actions to AppBar. For example: `leading: IconButton(icon: const Icon(Icons.menu), onPressed: () {}),`

### Expected results

When we set `foregroundColor` or `iconTheme` in AppBar to `Colors.black87` in Light mode, or ` Colors.white` in Dark mode, this color should be used for leading and action buttons.

### Actual results

 `foregroundColor` or `iconTheme` set in AppBar is ignored, and the default ColorScheme `onSurfaceVariant` color is used instead.

### Code sample

<details><summary>Code sample</summary>
This is code for a simple app to test the issue:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: const ColorScheme.dark().copyWith(onSurfaceVariant: Colors.red),
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          foregroundColor: Colors.white, // This color is ignored and icons are red!
          iconTheme: const IconThemeData(color: Colors.white), // This color is also ignored and icons are red!
          leading: IconButton(icon: const Icon(Icons.menu), onPressed: () {}),
          actions: <Widget>[
            IconButton(icon: const Icon(Icons.add), onPressed: () {}),
          ],
        ),
      ),
    );
  }
}
```

## Test
This is slightly edited code from `app_bar_test.dart`. This test will fail with `Colors.black87`, but is successful with any other color.

```dart
testWidgets('The foregroundColor property of the AppBar overrides any IconButtonTheme present in the theme - M3', (WidgetTester tester) async {
  final ThemeData themeData = ThemeData(useMaterial3: true);

  await tester.pumpWidget(
    MaterialApp(
      theme: themeData,
      home: Scaffold(
        appBar: AppBar(
          foregroundColor: Colors.black87,
          leading: IconButton(icon: const Icon(Icons.menu), onPressed: () {}),
          actions: <Widget>[
            IconButton(icon: const Icon(Icons.add), onPressed: () {}),
          ],
        ),
      ),
    ),
  );

  Color? leadingIconButtonColor() => iconStyle(tester, Icons.menu)?.color;
  Color? actionIconButtonColor() => iconStyle(tester, Icons.add)?.color;

  expect(leadingIconButtonColor(), Colors.black87);
  expect(actionIconButtonColor(), Colors.black87);
});
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Unsuccessful test:
image

Successful test:
image

Wrong color set in sample app:
image

</details>

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.13.0-3.0.pre.21, on Linux Mint 21.1 5.19.0-46-generic, locale cs_CZ.UTF-8)
    • Flutter version 3.13.0-3.0.pre.21 on channel master at /home/helu/Software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 47ba59c762 (8 hours ago), 2023-07-12 20:46:57 -0400
    • Engine revision 1b1ccdd1f5
    • Dart version 3.1.0 (build 3.1.0-302.0.dev)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/helu/Software/android-sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /home/helu/Software/android-sdk/
    • Java binary at: /home/helu/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/helu/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /home/helu/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • android-studio-dir = /home/helu/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Linux Mint 21.1 5.19.0-46-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 114.0.5735.198
    ! Device R3CT30WFRLD is not authorized.
      You might need to check your device for an authorization dialog.

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [[Material3] AppBar does not respect `foregroundColor` or `iconTheme` for leading and actions in some cases](https://github.com/flutter/flutter/issues/130485)

### Description

- Fix `Colors.white` not applied in dark mode
- Add regression tests
- make `iconStyle` private for consistency

### Before
Screenshot 2023-07-14 at 18 40 58

### After
Screenshot 2023-07-14 at 18 41 04

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/app_bar_test.dart [hunk 1]
```diff
@@ -3416,12 +3416,37 @@ void main() {
...
+      Color? leadingIconButtonColor() => _iconStyle(tester, Icons.menu)?.color;
+      Color? actionIconButtonColor() => _iconStyle(tester, Icons.add)?.color;
 
       expect(leadingIconButtonColor(), Colors.purple);
       expect(actionIconButtonColor(), Colors.purple);
     });
+
+    // This is a regression test for https://github.com/flutter/flutter/issues/130485.
+    testWidgets('Material3 - AppBar.iconTheme correctly applies custom white color in dark mode', (WidgetTester tester) async {
+      final ThemeData themeData = ThemeData(useMaterial3: true, brightness: Brightness.dark);
```
Comment (QuncCccccc) [inline packages/flutter/test/material/app_bar_test.dart:3428]: Would it be better if we just use the ThemeData config mentioned in the issue description? Just feel it would be more straightforward:)
```dart
theme: ThemeData(
  colorScheme: const ColorScheme.dark().copyWith(onSurfaceVariant: Colors.red),
  useMaterial3: true,
)
```

File: packages/flutter/test/material/app_bar_test.dart [hunk 2]
```diff
@@ -3416,12 +3416,37 @@ void main() {
...
+          ),
+        ),
+      );
+
+      Color? leadingIconButtonColor() => _iconStyle(tester, Icons.menu)?.color;
+      Color? actionIconButtonColor() => _iconStyle(tester, Icons.add)?.color;
+
+      expect(leadingIconButtonColor(), Colors.white);
+      expect(actionIconButtonColor(), Colors.white);
+    });
```
Comment (QuncCccccc) [inline packages/flutter/test/material/app_bar_test.dart:3449]: Can we also add 3 more unit tests?

1. One similar test for `foregroundColor: Colors.white`.
2. Two tests in the light brightness
```dart
colorScheme: const ColorScheme.light().copyWith(onSurfaceVariant: Colors.red),
```
, the `iconTheme: IconTheme(color: Colors.black87)` and `foregroundColor: Colors.black87` should also be respected. Just want to make sure in light brightness, when we provide the same color(black87) as the `IconTheme.fallback().color` to `IconTheme`, the color can be respected instead of using `onSurfaceVairiant`

**Review by QuncCccccc — COMMENTED** [review]
Looks good to me! Thanks for adding this fix quickly. Just left two comments for tests below.

File: packages/flutter/test/material/app_bar_test.dart [hunk 3]
```diff
@@ -3416,12 +3416,124 @@ void main() {
...
+
+    // This is a regression test for https://github.com/flutter/flutter/issues/130485.
+    testWidgets('Material3 - AppBar.iconTheme is correctly applied in dark mode', (WidgetTester tester) async {
```
Comment (QuncCccccc) [inline packages/flutter/test/material/app_bar_test.dart:3483]:
```suggestion
    testWidgets('Material3 - AppBar.iconTheme is correctly applied in light mode', (WidgetTester tester) async {
```

Comment (TahaTesser) [reply packages/flutter/test/material/app_bar_test.dart:3483]: Ooops.. good catch

**Review by QuncCccccc — APPROVED** [review]
LGTM:) Thanks!
