### PR TITLE
Show cursor after swipe only if TextField has focus

### LINKED ISSUE #173106: Multiple cursors visible on a list of TextField on iOS
### Steps to reproduce

1. Run provided code sample on an iPhone
2. Select a field in the list
3. Select another field with a very quick gesture (it requires a specific slide gesture that is hard to explain but it's relatively easy to trigger by playing a bit with it).
4. See video for demonstration

### Expected results

It should be impossible to have several cursors visible at the same time

### Actual results

Several cursors are visible at the same time.

I'm able to reproduce this on the latest master and latest beta channel. Only on iOS devices. I could not reproduce on Android.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('Text fields')),
        body: SingleChildScrollView(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: Column(
            children: [
              for (var i = 0; i < 20; i++)
                TextFormField(
                  key: ValueKey(i),
                  decoration: InputDecoration(hintText: 'Field $i'),
                ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/user-attachments/assets/7e43d0fd-f036-4922-84fe-22c5f04e5118)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel main, 3.33.0-1.0.pre-1227, on macOS 14.5 23F79 darwin-arm64, locale en-BE)
```

</details>

### PR DESCRIPTION
**Pull request by Memet18**
This PR fixes the issue where the cursor appears on a `TextField` after a small swipe gesture, even if the field does not have focus.  

The problem was caused by missing focus validation when showing the cursor.  
Now the cursor is only shown if the `TextField` has focus, which aligns with expected behavior.  

Fixes #173106

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 1]
```diff
@@ -2930,7 +2930,8 @@ class TextSelectionGestureDetectorBuilder {
     if (_isEditableTextMounted &&
         defaultTargetPlatform == TargetPlatform.iOS &&
         delegate.selectionEnabled &&
-        editableText.textEditingValue.selection.isCollapsed) {
+        editableText.textEditingValue.selection.isCollapsed &&
+        editableText.renderEditable.hasFocus) {
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/text_selection.dart]: Awesome catching this bug! I wonder if it might be better to fix this at the `EditableText` level in the `updateFloatingCursor` method. 

If `updateFloatingCursor` is passed a `RawFloatingCursorPoint` with a `state: FloatingCursorDragState.End`, then only resume the cursor blink only line `3656` if the editable text currently has focus.

https://github.com/flutter/flutter/blob/973320c0270b521e4622d453bbd1ca4db405223a/packages/flutter/lib/src/widgets/editable_text.dart#L3654-L3665

This way we prevent the cursor blink on the unfocused text field, and still reset the floating cursor.

Comment (Memet18) [reply packages/flutter/lib/src/widgets/text_selection.dart]: @Renzo-Olivares Thanks for the suggestion! 🙌 You’re right, the focus check should only wrap the _startCursorBlink() call. I’ve updated the PR accordingly.

File: packages/flutter/test/material/text_field_test.dart [hunk 2]
```diff
@@ -17679,6 +17679,62 @@ void main() {
...
+            ),
+          ),
+        );
+
+        final Offset fieldCenter = tester.getCenter(find.byType(EditableText));
+        final TestGesture gesture = await tester.startGesture(fieldCenter);
+        await gesture.moveBy(const Offset(30, 0));
+        await tester.pumpAndSettle();
+
+        // The floating cursor should NOT be shown.
```
Comment (Renzo-Olivares) [inline packages/flutter/test/material/text_field_test.dart]: Let's change `floating` to `blinking` here since it is the blinking cursor that was appearing.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 3]
```diff
@@ -9975,6 +9975,48 @@ void main() {
...
+            ),
+          ),
+        );
+
+        final Offset fieldCenter = tester.getCenter(find.byType(EditableText));
+        final TestGesture gesture = await tester.startGesture(fieldCenter);
+        await gesture.moveBy(const Offset(30, 0));
+        await tester.pumpAndSettle();
+
+        // The floating cursor should NOT be shown.
```
Comment (Renzo-Olivares) [inline packages/flutter/test/cupertino/text_field_test.dart]: Same as https://github.com/flutter/flutter/pull/175044/files#r2331404583

**Review by Renzo-Olivares — APPROVED** [review]
LGTM w/ small comments, thank you for the fix!

File: packages/flutter/test/material/text_field_test.dart (hunk 2 above)
Comment (Memet18) [reply packages/flutter/test/material/text_field_test.dart]: Thanks! Fixed.

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 3 above)
Comment (Memet18) [reply packages/flutter/test/cupertino/text_field_test.dart]: Thanks! Fixed.

**Comment by vasilich6107** [comment]
Hi @Renzo-Olivares 
Could you clarify who could help with merging and releasing as hotfix

**Comment by Renzo-Olivares** [comment]
@vasilich6107 This PR will need a secondary review/approval before being merged.

**Review by loic-sharma — APPROVED** [review]
Thank you for the excellent contribution!

**Comment by loic-sharma** [comment]
I'll get the ball rolling for a cherry pick to stable and beta.

**Comment by loic-sharma** [comment]
Cherry pick pull requests:

* Beta: https://github.com/flutter/flutter/pull/175391
* Stable: https://github.com/flutter/flutter/pull/175393
