### PR TITLE
Fix VoiceOver does not announce state of ButtonSegment

### LINKED ISSUE #146987: [a11y] VoiceOver does not announce state of ButtonSegment
### Steps to reproduce

Create a widget that shows a `SegmentedButton`, without any explicit use of `Semantics`.  The example below is for a light/dark mode toggle.

```dart
class _ThemeSelector extends StatelessWidget {
  const _ThemeSelector();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Get the current theme mode...
    final themeMode = ...;

    return SegmentedButton(
      showSelectedIcon: false,
      segments: [
        ButtonSegment(
          icon: const Icon(Icons.light_mode),
          label: Text('Light mode'),
          value: ThemeMode.light,
        ),
        ButtonSegment(
          icon: const Icon(Icons.dark_mode),
          label: Text('Dark mode'.hardcoded),
          value: ThemeMode.dark,
        ),
      ],
      selected: {themeMode},
      onSelectionChanged: (selected) {
        // Set the current theme mode...
      },
    );
  }
}
```

### Expected results

I would expect that the button segment announces that it is selected, or perhaps toggled on, without needing to wrap `ButtonSegment.label` in an explicit `Semantics` widget.

For example, given the example, it should announce "selected, light mode, button".

It is also probable that the role of a button segment is a toggle, rather than a button.

### Actual results

In the example above, VoiceOver announces the button segment's label followed by "button" but without indicating when the button segment is selected, for example, "light mode, button".

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Segmented Button Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _themeMode = ThemeMode.light;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: SegmentedButton(
          showSelectedIcon: false,
          segments: const [
            ButtonSegment(
              icon: Icon(Icons.light_mode),
              label: Text('Light mode'),
              value: ThemeMode.light,
            ),
            ButtonSegment(
              icon: Icon(Icons.dark_mode),
              label: Text('Dark mode'),
              value: ThemeMode.dark,
            ),
          ],
          selected: {_themeMode},
          onSelectionChanged: (selected) {
            setState(() {
              _themeMode = selected.first;
            });
          },
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter
doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.6)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by huycozy**
- Fix https://github.com/flutter/flutter/issues/146987
- As explained at https://github.com/flutter/flutter/issues/146987#issuecomment-3294737075: this PR proposes _replacing_ `checked` with `selected` here:
 
https://github.com/flutter/flutter/blob/f4de70c6470386db28d23ac5e2e48c681ca23c7a/packages/flutter/lib/src/material/segmented_button.dart#L634
 
Then VoiceOver can indicate when the button segment is selected. It's _replacing_ action but not _adding_ because _adding_ (keep both `checked` and `selected`) will cause the button to be read with both checked and selected states with Android TalkBack reader that may cause confusion to users (watch demo videos). I also did test with iOS segmented control (storyboard) and Android Jetpack Compose to compare: on these native platforms, it announces `selected` state  (watch demo videos).

<details>
<summary>Demo Flutter app - after the fix</summary>

| Flutter Android | Flutter iOS |
| --------------- | --------------- |
<video src="https://github.com/user-attachments/assets/458c9b78-8275-45db-83cb-b2581505d240"/> | <video src="https://github.com/user-attachments/assets/1c69694d-67f8-4f8c-a453-2cf7696e43b5"/>

</details>

<details>
<summary>Demo native platforms</summary>

| Android Jetpack Compose | iOS segmented control (storyboard) |
| --------------- | --------------- |
<video src="https://github.com/user-attachments/assets/5b682c7e-4c50-49be-a613-58673154aa88"/> | <video src="https://github.com/user-attachments/assets/9faba9ea-d373-4756-953a-cde510871247"/>

</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/segmented_button_test.dart [hunk 1]
```diff
@@ -612,6 +612,62 @@ void main() {
...
+
+    // Verify that there is one selected segment and one unselected segment.
+    expect(selectedNodes.length, equals(1));
+    expect(unselectedNodes.length, equals(1));
+
+    // Ensure that the 'checked' flags are NOT used to prevent duplication issue
+    // on Android.
+    // On Android, TalkBack reader announces both 'checked' and 'selected' states.
+    // This verifies `checked` state is not read with Android TalkBack.
+    //
```
Comment (victorsanni) [inline packages/flutter/test/material/segmented_button_test.dart]:
```suggestion
```

**Review by victorsanni — APPROVED** [review]

**Comment by victorsanni** [comment]
Google testing failures are legitimate. The tests print semantics that match the checked/unchecked states which this PR changes to the selected state.

File: packages/flutter/lib/src/material/segmented_button.dart [hunk 2]
```diff
@@ -631,7 +631,7 @@ class SegmentedButtonState<T> extends State<SegmentedButton<T>> {
 
       return MergeSemantics(
         child: Semantics(
-          checked: segmentSelected,
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/segmented_button.dart:634]: checked has special meaning in android https://github.com/flutter/flutter/blob/238db3574bbacae308950375f65ecffb7d15a734/engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L1020

may be does this in platform adaptive way? i.e checking defaultTargetPlatform

Comment (huycozy) [reply packages/flutter/lib/src/material/segmented_button.dart:634]: @chunhtai Thanks for pointing that out. I also see it is working with `selected` here on Android:

https://github.com/flutter/flutter/blob/238db3574bbacae308950375f65ecffb7d15a734/engine/src/flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L1031

Indeed, as shared above with Android Jetpack Compose demo, `selected` state is announced instead of `checked`. Is that a thing we should fix in this PR, or do you want to solve it in another PR(belongs with a separate issue to discuss first)? (I'm willing to do that for better tracking, just let me know)

Also, semantically, I think `selected` is more appropriate for a segmented button; whilst `checked` sounds more appropriate for a Radio or Checkbox, right?

Comment (chunhtai) [reply packages/flutter/lib/src/material/segmented_button.dart:634]: yeah, that makes sense. This sgtm

**Review by chunhtai — APPROVED** [review]
LGTM
