### PR TITLE
Make ClampingScrollSimulation ballistic and more like Android

### LINKED ISSUE #113424: `ClampingScrollSimulation` has large nonzero velocity when near the end, and velocity even increases slightly there
## The problem

When using ClampingScrollSimulation, there are two problems:

* It has large nonzero velocity when near the end (see figure below). We all know, for list view scrolling to feel comfortable, it should decrease its velocity and get to near-zero value when near end, instead of a large nonzero value.
* velocity even increases slightly there (again see figure below). We know velocity should at least decrease due to friction.

## Reproduction code for "velocity increases when near end"

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('ClampingScrollSimulation should have decreasing speed', () {
    final ClampingScrollSimulation simulation =
        ClampingScrollSimulation(position: 0, velocity: 1000);

    final List<double> tValues = List<double>.generate(60, (int i) => i / 60);
    final List<double> xValues = tValues.map(simulation.x).toList();
    final List<double> xDeltas = <double>[
      for (int i = 0; i < xValues.length - 1; ++i) xValues[i + 1] - xValues[i]
    ];

    // If curious, uncomment this to see the real values
    // debugPrint('$tValues\n$xValues\n$xDeltas');

    for (int i = 0; i < xDeltas.length - 1; ++i) {
      expect(xDeltas[i], greaterThan(xDeltas[i + 1]));
    }
  });
}
```

## Figures

Code:

<details>

```python
import matplotlib
import numpy as np

matplotlib.use("MacOSX")

import matplotlib.pyplot as plt

import math
from dataclasses import dataclass

_kDecelerationRate = math.log(0.78) / math.log(0.9)
_initialVelocityPenetration = 3.065


def _decelerationForFriction(friction: float):
    return friction * 61774.04968


def _flingDistancePenetration(t):
    return (1.2 * t * t * t) - (3.27 * t * t) + (_initialVelocityPenetration * t)


def _flingVelocityPenetration(t):
    return (3.6 * t * t) - (6.54 * t) + _initialVelocityPenetration


def clampDouble(x, min, max):
    if x < min:
        return min
    if x > max:
        return max
    return x


def _sign(x):
    if x > 0:
        return 1.0
    if x < 0:
        return -1.0
    return x


def _array_map(x, f):
    return np.fromiter((f(xi) for xi in x), x.dtype)


@dataclass
class ClampingScrollSimulation:
    position: float
    velocity: float
    friction: float = 0.015

    def __post_init__(self):
        self._duration = self._flingDuration(self.velocity)
        self._distance = abs(self.velocity * self._duration / _initialVelocityPenetration)

    def _flingDuration(self, velocity: float):
        scaledFriction = self.friction * _decelerationForFriction(0.84)
        deceleration = math.log(0.35 * abs(velocity) / scaledFriction)
        return math.exp(deceleration / (_kDecelerationRate - 1.0))

    def x(self, time):
        t = clampDouble(time / self._duration, 0.0, 1.0)
        return self.position + self._distance * _flingDistancePenetration(t) * _sign(self.velocity)

    def dx(self, time):
        t = clampDouble(time / self._duration, 0.0, 1.0)
        return self._distance * _flingVelocityPenetration(t) * _sign(self.velocity) / self._duration


# %%

plt.clf()
plt.tight_layout()
ax1 = plt.gca()
ax2 = ax1.twinx()

dt = 1 / 60
t = np.arange(0, 1, dt)

simulation_a = ClampingScrollSimulation(position=0, velocity=1000)
x_a = _array_map(t, simulation_a.x)
v_a = _array_map(t, simulation_a.dx)
diffx_a = (x_a[1:] - x_a[:-1]) / dt

ax1.plot(t, x_a, label='x_a')
ax2.plot(t, v_a, label='v_a')
ax2.plot(t[:-1], diffx_a, label='diffx_a')

if False:
    b_start_time = 0.3
    simulation_b = ClampingScrollSimulation(
        position=simulation_a.x(b_start_time),
        velocity=simulation_a.dx(b_start_time),
    )
    x_b = _array_map(t, simulation_b.x)
    v_b = _array_map(t, simulation_b.dx)
    diffx_b = (x_b[1:] - x_b[:-1]) / dt

    ax1.plot(t + b_start_time, x_b, label='x_b')
    ax2.plot(t + b_start_time, v_b, label='v_b')
    ax2.plot(t[:-1] + b_start_time, diffx_b, label='diffx_b')

ax1.legend(loc="upper left")
ax2.legend(loc="upper right")

plt.xlim([0, 1])

plt.show()

```

</details>

Image:

image

zoom in:

image

zoom in again:

image

### LINKED ISSUE #119875: ClampingScrollSimulation decays sooner and goes less far than native Android scrolling
On Android, when the user attempts to scroll quickly using a "fling" gesture, the scroll doesn't go as far or as fast as it would have in a native Android scrolling view. In a long list this can make scrolling feel sluggish, or not easy, or not responsive.

One reason for this behavior is that Flutter's `ClampingScrollSimulation`, which is meant to match Android's scroll physics (and is used by default on Android and other non-Apple platforms), in fact uses a curve that decays faster than the Android curve, and goes less far in total. When the simulation is complete, the distance traveled is about 7.2% less than the Android scroll physics would travel.

(This isn't the only factor contributing to the overall slowness of the scroll; I'll file other issues separately.)

Related issue:
* #103762

## Steps to Reproduce

1. Run the [`platform_tests/scroll_overlay`](https://github.com/flutter/platform_tests/tree/1d797b8699546f1178e3cf58de9c6cc64f825281/scroll_overlay) app on an Android device.
2. Scroll with a fling gesture: swipe rapidly upward and release. Wait a couple of seconds for the scroll to come to a stop.
   * (To isolate this single issue: swipe just once, and swipe as precisely straight upward as possible. Swiping diagonally triggers a second issue I'll file separately (→#120345), and re-flinging while the scroll is still going triggers additional logic with its own complexity.)
3. Observe how far the scroll went, as shown by the numbered items in the Android- and Flutter-driven scrolling lists.

**Expected results:** 

The Flutter list should scroll the same distance as the Android list, so that corresponding list items are aligned with each other.

**Actual results:** 

The Flutter list goes substantially less far than the Android list.

Specifically, when I try this on the current version of `scroll_overlay` (at flutter/platform_tests@1d797b8699546f1178e3cf58de9c6cc64f825281 ), I see "Android 94" next to "Flutter 81".

That version has item heights that vary through the list and don't quite agree between Android and Flutter, making the numbers a bit hard to interpret.  In a revised `scroll_overlay` with fixed heights (which I'll send a platform_tests PR for), I see "Android 202" next to "Flutter 189".

<details>
  <summary>Logs</summary>

```
[   +6 ms] executing: uname -m
[   +3 ms] Exit code 0 from: uname -m
[        ] x86_64
[        ] executing: [/home/greg/n/flutter/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 33e896b47581fe2737f641a181f86839df72719f
[        ] executing: [/home/greg/n/flutter/flutter/] git tag --points-at 33e896b47581fe2737f641a181f86839df72719f
[  +13 ms] Exit code 0 from: git tag --points-at 33e896b47581fe2737f641a181f86839df72719f
[        ] executing: [/home/greg/n/flutter/flutter/] git describe --match *.*.* --long --tags 33e896b47581fe2737f641a181f86839df72719f
[  +14 ms] Exit code 0 from: git describe --match *.*.* --long --tags 33e896b47581fe2737f641a181f86839df72719f
[        ] 3.7.0-12.0.pre-4-g33e896b47
[   +6 ms] executing: [/home/greg/n/flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/main
[        ] executing: [/home/greg/n/flutter/flutter/] git ls-remote --get-url origin
[   +1 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +9 ms] executing: [/home/greg/n/flutter/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] main
[  +23 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +31 ms] executing: /home/greg/Android/Sdk/platform-tools/adb devices -l
[   +7 ms] List of devices attached
           08171FDD40025F         device usb:1-5 product:redfin model:Pixel_5 device:redfin transport_id:7
[   +3 ms] /home/greg/Android/Sdk/platform-tools/adb -s 08171FDD40025F shell getprop
[  +33 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +88 ms] Skipping pub get: version match.
[  +28 ms] Generating /home/greg/n/flutter/platform_tests/scroll_overlay/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +32 ms] ro.hardware = redfin
[        ] ro.build.characteristics = nosdcard
[  +20 ms] Initializing file store
[   +5 ms] Skipping target: gen_localizations
[   +3 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/greg/n/flutter/platform_tests/scroll_overlay/.dart_tool/package_config_subset}
[  +10 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +1 ms] complete
[   +4 ms] Launching lib/main.dart on Pixel 5 in debug mode...
[   +2 ms] /home/greg/n/flutter/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/greg/n/flutter/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot
--sdk-root /home/greg/n/flutter/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.CIELAI/flutter_tool.WAQCVS/app.dill --packages
/home/greg/n/flutter/platform_tests/scroll_overlay/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --verbosity=error --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[   +4 ms] executing: /home/greg/Android/Sdk/build-tools/33.0.1/aapt dump xmltree /home/greg/n/flutter/platform_tests/scroll_overlay/build/app/outputs/flutter-apk/app-debug.apk
AndroidManifest.xml
[   +3 ms] Exit code 0 from: /home/greg/Android/Sdk/build-tools/33.0.1/aapt dump xmltree /home/greg/n/flutter/platform_tests/scroll_overlay/build/app/outputs/flutter-apk/app-debug.apk
AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0" (Raw: "1.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x21
               A: android:compileSdkVersionCodename(0x01010573)="13" (Raw: "13")
               A: package="io.flutter.scroll_overlay" (Raw: "io.flutter.scroll_overlay")
               A: platformBuildVersionCode=(type 0x10)0x21
               A: platformBuildVersionName=(type 0x10)0xd
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="scroll_overlay" (Raw: "scroll_overlay")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="io.flutter.scroll_overlay.ScrollOverlayActivity" (Raw: "io.flutter.scroll_overlay.ScrollOverlayActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=36)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=40)
                     E: action (line=41)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=43)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=50)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=54)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=57)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +3 ms] executing: /home/greg/Android/Sdk/platform-tools/adb -s 08171FDD40025F shell -x logcat -v time -t 1
[   +8 ms] <- compile package:scroll_overlay/main.dart
[  +62 ms] --------- beginning of main
           02-02 16:16:20.106 D/CHRE    ( 1280): @ 411930.827: [ActivityPlatform] type 6, confidence 41
[   +6 ms] executing: /home/greg/Android/Sdk/platform-tools/adb version
[   +3 ms] Android Debug Bridge version 1.0.41
           Version 33.0.3-8952118
           Installed as /home/greg/Android/Sdk/platform-tools/adb
[   +1 ms] executing: /home/greg/Android/Sdk/platform-tools/adb start-server
[   +4 ms] Building APK
[   +6 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] Using gradle from /home/greg/n/flutter/platform_tests/scroll_overlay/android/gradlew.
[  +14 ms] executing: /home/greg/lib/android-studio-2020.3.1.24/jre/bin/java -version
[  +83 ms] Exit code 0 from: /home/greg/lib/android-studio-2020.3.1.24/jre/bin/java -version
[        ] openjdk version "11.0.15" 2022-04-19
           OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
           OpenJDK 64-Bit Server VM (build 11.0.15+0-b2043.56-8887301, mixed mode)
[   +1 ms] executing: /opt/android-studio/jre/bin/java -version
[  +67 ms] Exit code 0 from: /opt/android-studio/jre/bin/java -version
[        ] openjdk version "11.0.15" 2022-04-19
           OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
           OpenJDK 64-Bit Server VM (build 11.0.15+0-b2043.56-8887301, mixed mode)
[   +1 ms] executing: [/home/greg/n/flutter/platform_tests/scroll_overlay/android/] /home/greg/n/flutter/platform_tests/scroll_overlay/android/gradlew --full-stacktrace --info
-Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=/home/greg/n/flutter/platform_tests/scroll_overlay/lib/main.dart -Pbase-application-name=android.app.Application
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +320 ms] Initialized native services in: /home/greg/.gradle/native
[ +204 ms] The client will now receive all logging from the daemon (pid: 8283). The daemon log file: /home/greg/.gradle/daemon/5.6.2/daemon-8283.out.log
[        ] Starting 15th build in daemon [uptime: 24 mins 23.946 secs, performance: 100%]
[        ] Using 12 worker leases.
[        ] Starting Build
[        ] Settings evaluated using settings file '/home/greg/n/flutter/platform_tests/scroll_overlay/android/settings.gradle'.
[        ] Projects loaded. Root project using build file '/home/greg/n/flutter/platform_tests/scroll_overlay/android/build.gradle'.
[        ] Included projects: [root project 'android', project ':app']
[ +100 ms] > Configure project :app
[        ] Evaluating project ':app' using build file '/home/greg/n/flutter/platform_tests/scroll_overlay/android/app/build.gradle'.
[        ] Creating configuration androidTestUtil
[        ] Creating configuration compile
[        ] Creating configuration apk
[        ] Creating configuration provided
[        ] Creating configuration api
[        ] Creating configuration implementation
[        ] Creating configuration runtimeOnly
[        ] Creating configuration compileOnly
[        ] Creating configuration wearApp
[        ] Creating configuration annotationProcessor
[        ] Creating configuration androidTestCompile
[        ] Creating configuration androidTestApk
[        ] Creating configuration androidTestProvided
[        ] Creating configuration androidTestApi
[        ] Creating configuration androidTestImplementation
[        ] Creating configuration androidTestRuntimeOnly
[        ] Creating configuration androidTestCompileOnly
[        ] Creating configuration androidTestWearApp
[        ] Creating configuration androidTestAnnotationProcessor
[        ] Creating configuration testCompile
[        ] Creating configuration testApk
[        ] Creating configuration testProvided
[        ] Creating configuration testApi
[        ] Creating configuration testImplementation
[        ] Creating configuration testRuntimeOnly
[        ] Creating configuration testCompileOnly
[        ] Creating configuration testWearApp
[        ] Creating configuration testAnnotationProcessor
[        ] Creating configuration debugCompile
[        ] Creating configuration debugApk
[        ] Creating configuration debugProvided
[        ] Creating configuration debugApi
[        ] Creating configuration debugImplementation
[        ] Creating configuration debugRuntimeOnly
[        ] Creating configuration debugCompileOnly
[        ] Creating configuration debugWearApp
[        ] Creating configuration debugAnnotationProcessor
[        ] Creating configuration androidTestDebugCompile
[        ] Creating configuration androidTestDebugApk
[        ] Creating configuration androidTestDebugProvided
[        ] Creating configuration androidTestDebugApi
[        ] Creating configuration androidTestDebugImplementation
[        ] Creating configuration androidTestDebugRuntimeOnly
[        ] Creating configuration androidTestDebugCompileOnly
[        ] Creating configuration androidTestDebugWearApp
[        ] Creating configuration androidTestDebugAnnotationProcessor
[        ] Creating configuration testDebugCompile
[        ] Creating configuration testDebugApk
[        ] Creating configuration testDebugProvided
[        ] Creating configuration testDebugApi
[        ] Creating configuration testDebugImplementation
[        ] Creating configuration testDebugRuntimeOnly
[        ] Creating configuration testDebugCompileOnly
[        ] Creating configuration testDebugWearApp
[        ] Creating configuration testDebugAnnotationProcessor
[        ] Creating configuration releaseCompile
[        ] Creating configuration releaseApk
[        ] Creating configuration releaseProvided
[        ] Creating configuration releaseApi
[        ] Creating configuration releaseImplementation
[        ] Creating configuration releaseRuntimeOnly
[        ] Creating configuration releaseCompileOnly
[        ] Creating configuration releaseWearApp
[        ] Creating configuration releaseAnnotationProcessor
[        ] Creating configuration testReleaseCompile
[        ] Creating configuration testReleaseApk
[        ] Creating configuration testReleaseProvided
[        ] Creating configuration testReleaseApi
[        ] Creating configuration testReleaseImplementation
[        ] Creating configuration testReleaseRuntimeOnly
[        ] Creating configuration testReleaseCompileOnly
[        ] Creating configuration testReleaseWearApp
[        ] Creating configuration testReleaseAnnotationProcessor
[        ] Creating configuration profileCompile
[        ] Creating configuration profileApk
[        ] Creating configuration profileProvided
[        ] Creating configuration profileApi
[        ] Creating configuration profileImplementation
[        ] Creating configuration profileRuntimeOnly
[        ] Creating configuration profileCompileOnly
[        ] Creating configuration profileWearApp
[        ] Creating configuration profileAnnotationProcessor
[        ] Creating configuration testProfileCompile
[        ] Creating configuration testProfileApk
[        ] Creating configuration testProfileProvided
[        ] Creating configuration testProfileApi
[        ] Creating configuration testProfileImplementation
[        ] Creating configuration testProfileRuntimeOnly
[        ] Creating configuration testProfileCompileOnly
[        ] Creating configuration testProfileWearApp
[        ] Creating configuration testProfileAnnotationProcessor
[        ] > Configure project :
[        ] Evaluating root project 'android' using build file '/home/greg/n/flutter/platform_tests/scroll_overlay/android/build.gradle'.
[        ] All projects evaluated.
[        ] Analytics other plugin to proto: Unknown plugin type org.gradle.kotlin.dsl.provider.plugins.KotlinScriptRootPlugin expected enum
ORG_GRADLE_KOTLIN_DSL_PROVIDER_PLUGINS_KOTLINSCRIPTROOTPLUGIN
[        ] Analytics other plugin to proto: Unknown plugin type org.gradle.kotlin.dsl.provider.plugins.KotlinScriptBasePlugin expected enum
ORG_GRADLE_KOTLIN_DSL_PROVIDER_PLUGINS_KOTLINSCRIPTBASEPLUGIN
[        ] Analytics other plugin to proto: Unknown plugin type Flutter_gradle$FlutterPluginKts expected enum FLUTTER_GRADLE$FLUTTERPLUGINKTS
[        ] Analytics other plugin to proto: Unknown plugin type FlutterPlugin expected enum FLUTTERPLUGIN
[        ] Selected primary task 'assembleDebug' from project :
[        ] Tasks to be executed: [task ':app:compileFlutterBuildDebug', task ':app:packLibsflutterBuildDebug', task ':app:preBuild', task ':app:preDebugBuild', task
':app:compileDebugAidl', task ':app:compileDebugRenderscript', task ':app:checkDebugManifest', task ':app:generateDebugBuildConfig', task ':app:cleanMergeDebugAssets', task
':app:mergeDebugShaders', task ':app:compileDebugShaders', task ':app:generateDebugAssets', task ':app:mergeDebugAssets', task ':app:copyFlutterAssetsDebug', task
':app:mainApkListPersistenceDebug', task ':app:generateDebugResValues', task ':app:generateDebugResources', task ':app:mergeDebugResources', task
':app:createDebugCompatibleScreenManifests', task ':app:processDebugManifest', task ':app:processDebugResources', task ':app:compileDebugKotlin', task ':app:javaPreCompileDebug', task
':app:compileDebugJavaWithJavac', task ':app:compileDebugSources', task ':app:processDebugJavaRes', task ':app:mergeDebugJavaResource', task ':app:checkDebugDuplicateClasses', task
':app:desugarDebugFileDependencies', task ':app:mergeExtDexDebug', task ':app:transformClassesWithDexBuilderForDebug', task ':app:mergeDexDebug', task ':app:validateSigningDebug', task
':app:signingConfigWriterDebug', task ':app:mergeDebugJniLibFolders', task ':app:mergeDebugNativeLibs', task ':app:stripDebugDebugSymbols', task ':app:packageDebug', task
':app:assembleDebug']
[   +2 ms] JetifyTransform (Thread[Execution worker for ':',5,main]) started.
[        ] JetifyTransform (Thread[Execution worker for ':' Thread 2,5,main]) started.
[        ] JetifyTransform (Thread[Execution worker for ':' Thread 3,5,main]) started.
[        ] JetifyTransform (Thread[Execution worker for ':' Thread 4,5,main]) started.
[        ] JetifyTransform (Thread[Execution worker for ':' Thread 5,5,main]) started.
[        ] JetifyTransform (Thread[Execution worker for ':' Thread 6,5,main]) started.
[        ] JetifyTransform (Thread[Execution worker for ':' Thread 7,5,main]) started.
[        ] JetifyTransform (Thread[Execution worker for ':' Thread 8,5,main]) started.
[   +1 ms] JetifyTransform (Thread[Execution worker for ':' Thread 10,5,main]) started.
[        ] JetifyTransform (Thread[Execution worker for ':' Thread 11,5,main]) started.
[        ] JetifyTransform (Thread[Daemon worker Thread 7,5,main]) started.
[        ] > Transform artifact kotlin-stdlib-common.jar (org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31) with JetifyTransform
[        ] Transforming artifact kotlin-stdlib-common.jar (org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31) with JetifyTransform
[        ] Caching disabled for JetifyTransform:
/home/greg/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.31/43331609c7de811fed085e0dfd150874b157c32/kotlin-stdlib-common-1.5.31.jar because:
[        ]   Build cache is disabled
[        ] Skipping JetifyTransform:
/home/greg/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.31/43331609c7de811fed085e0dfd150874b157c32/kotlin-stdlib-common-1.5.31.jar as it is up-to-date.
[        ] > Transform artifact kotlin-stdlib-jdk7.jar (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30) with JetifyTransform
[        ] Transforming artifact kotlin-stdlib-jdk7.jar (org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30) with JetifyTransform
[   +3 ms] Caching disabled for JetifyTransform:
/home/greg/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.5.30/525f5a7fa6d7790a571c07dd24214ed2dda352fe/kotlin-stdlib-jdk7-1.5.30.jar because:
[        ]   Build cache is disabled
[        ] Skipping JetifyTransform:
/home/greg/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.5.30/525f5a7fa6d7790a571c07dd24214ed2dda352fe/kotlin-stdlib-jdk7-1.5.30.jar as it is up-to-date.

[… copious build logs elided to meet GitHub's length limit …]

[        ] > Transform artifact tracing.aar (androidx.tracing:tracing:1.0.0) with AarTransform
[        ] Transforming artifact tracing.aar (androidx.tracing:tracing:1.0.0) with AarTransform
[        ] Caching disabled for AarTransform: /home/greg/.gradle/caches/transforms-2/files-2.1/d606eb34fbe4f818c2c6052896a24d12/tracing-1.0.0 because:
[        ]   Build cache is disabled
[        ] Skipping AarTransform: /home/greg/.gradle/caches/transforms-2/files-2.1/d606eb34fbe4f818c2c6052896a24d12/tracing-1.0.0 as it is up-to-date.
[        ] AarTransform (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.003 secs.
[        ] :app:mergeDebugNativeLibs (Thread[Execution worker for ':' Thread 2,5,main]) started.
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] Task :app:mergeDebugNativeLibs in app Starting
[        ] Transforming file /home/greg/n/flutter/platform_tests/scroll_overlay/build/app/intermediates/flutter/debug/libs.jar with JetifyTransform
[        ] Transforming file /home/greg/n/flutter/platform_tests/scroll_overlay/build/app/intermediates/flutter/debug/libs.jar with IdentityTransform
[        ] Caching disabled for task ':app:mergeDebugNativeLibs' because:
[        ]   Build cache is disabled
[        ] Skipping task ':app:mergeDebugNativeLibs' as it is up-to-date.
[        ] Task :app:mergeDebugNativeLibs in app Finished
[        ] :app:mergeDebugNativeLibs (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.001 secs.
[        ] :app:stripDebugDebugSymbols (Thread[Execution worker for ':' Thread 2,5,main]) started.
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Task :app:stripDebugDebugSymbols in app Starting
[        ] android.ndkVersion from module build.gradle is not set
[        ] ndk.dir in local.properties is not set
[        ] ANDROID_NDK_HOME environment variable is not set
[        ] sdkFolder is /home/greg/Android/Sdk
[        ] Considering /home/greg/Android/Sdk/ndk-bundle in SDK ndk-bundle folder
[        ] Considering /home/greg/Android/Sdk/ndk/21.4.7075529 in SDK ndk folder
[        ] Rejected /home/greg/Android/Sdk/ndk-bundle in SDK ndk-bundle folder because that location has no source.properties
[        ] No user requested version, choosing /home/greg/Android/Sdk/ndk/21.4.7075529 which is version 21.4.7075529
[        ] Caching disabled for task ':app:stripDebugDebugSymbols' because:
[        ]   Build cache is disabled
[        ] Skipping task ':app:stripDebugDebugSymbols' as it is up-to-date.
[        ] Task :app:stripDebugDebugSymbols in app Finished
[        ] :app:stripDebugDebugSymbols (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.002 secs.
[        ] :app:packageDebug (Thread[Execution worker for ':' Thread 2,5,main]) started.
[        ] > Task :app:packageDebug UP-TO-DATE
[        ] Task :app:packageDebug in app Starting
[        ] Caching disabled for task ':app:packageDebug' because:
[        ]   Build cache is disabled
[        ] Skipping task ':app:packageDebug' as it is up-to-date.
[        ] Task :app:packageDebug in app Finished
[        ] :app:packageDebug (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.002 secs.
[        ] :app:assembleDebug (Thread[Execution worker for ':' Thread 2,5,main]) started.
[        ] > Task :app:assembleDebug
[        ] Task :app:assembleDebug in app Starting
[        ] Caching disabled for task ':app:assembleDebug' because:
[        ]   Build cache is disabled
[        ] Task ':app:assembleDebug' is not up-to-date because:
[        ]   Task has not declared any outputs despite executing actions.
[        ] Task :app:assembleDebug in app Finished
[        ] :app:assembleDebug (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.098 secs.
[        ] BUILD SUCCESSFUL in 873ms
[        ] 31 actionable tasks: 4 executed, 27 up-to-date
[ +338 ms] Running Gradle task 'assembleDebug'... (completed in 1,438ms)
[   +2 ms] Calculate SHA1: LocalDirectory: '/home/greg/n/flutter/platform_tests/scroll_overlay/build/app/outputs/flutter-apk'/app-debug.apk
[ +579 ms] ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
[   +1 ms] executing: /home/greg/Android/Sdk/build-tools/33.0.1/aapt dump xmltree /home/greg/n/flutter/platform_tests/scroll_overlay/build/app/outputs/flutter-apk/app-debug.apk
AndroidManifest.xml
[   +3 ms] Exit code 0 from: /home/greg/Android/Sdk/build-tools/33.0.1/aapt dump xmltree /home/greg/n/flutter/platform_tests/scroll_overlay/build/app/outputs/flutter-apk/app-debug.apk
AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0" (Raw: "1.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x21
               A: android:compileSdkVersionCodename(0x01010573)="13" (Raw: "13")
               A: package="io.flutter.scroll_overlay" (Raw: "io.flutter.scroll_overlay")
               A: platformBuildVersionCode=(type 0x10)0x21
               A: platformBuildVersionName=(type 0x10)0xd
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="scroll_overlay" (Raw: "scroll_overlay")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="io.flutter.scroll_overlay.ScrollOverlayActivity" (Raw: "io.flutter.scroll_overlay.ScrollOverlayActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=36)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=40)
                     E: action (line=41)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=43)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=50)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=54)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=57)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[        ] Stopping app 'app-debug.apk' on Pixel 5.
[        ] executing: /home/greg/Android/Sdk/platform-tools/adb -s 08171FDD40025F shell am force-stop io.flutter.scroll_overlay
[  +79 ms] executing: /home/greg/Android/Sdk/platform-tools/adb -s 08171FDD40025F shell pm list packages io.flutter.scroll_overlay
[  +74 ms] package:io.flutter.scroll_overlay
[   +1 ms] executing: /home/greg/Android/Sdk/platform-tools/adb -s 08171FDD40025F shell cat /data/local/tmp/sky.io.flutter.scroll_overlay.sha1
[  +21 ms] 18a556dff430ae97d52ae3a1f0ce4362c002fc3f
[        ] Latest build already installed.
[        ] executing: /home/greg/Android/Sdk/platform-tools/adb -s 08171FDD40025F shell -x logcat -v time -t 1
[ +133 ms] --------- beginning of main
                    02-02 16:16:25.194 D/InsetsController( 4868): show(ime(), fromIme=true)
[   +6 ms] executing: /home/greg/Android/Sdk/platform-tools/adb -s 08171FDD40025F shell am start -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x20000000 --ez
enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true io.flutter.scroll_overlay/io.flutter.scroll_overlay.ScrollOverlayActivity
[  +65 ms] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x20000000 cmp=io.flutter.scroll_overlay/.ScrollOverlayActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +381 ms] Observatory URL on device: http://127.0.0.1:43231/BeKDRJHAPZs=/
[        ] executing: /home/greg/Android/Sdk/platform-tools/adb -s 08171FDD40025F forward tcp:0 tcp:43231
[   +4 ms] 38865
[        ] Forwarded host port 38865 to device port 43231 for Observatory
[   +4 ms] Caching compiled dill
[  +37 ms] Connecting to service protocol: http://127.0.0.1:38865/BeKDRJHAPZs=/
[ +212 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:38865/BeKDRJHAPZs=/.
[ +229 ms] DDS is listening at http://127.0.0.1:45645/mUYg-ZDncHM=/.
[  +93 ms] Successfully connected to service protocol: http://127.0.0.1:38865/BeKDRJHAPZs=/
[  +65 ms] DevFS: Creating new filesystem on the device (null)
[  +25 ms] DevFS: Created new filesystem on the device (file:///data/user/0/io.flutter.scroll_overlay/code_cache/scroll_overlayYHASOW/scroll_overlay/)
[   +1 ms] Updating assets
[  +61 ms] Syncing files to device Pixel 5...
[   +1 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:scroll_overlay/main.dart 5c5b1ae6-5cb1-49a2-b251-46283a17da67
[        ] <- 5c5b1ae6-5cb1-49a2-b251-46283a17da67
[   +1 ms] Bundle processing done.
[  +53 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Pixel 5... (completed in 57ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +5 ms] Connected to _flutterView/0x74f404e040.
[   +1 ms] Flutter run key commands.
[        ] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on Pixel 5 is available at: http://127.0.0.1:45645/mUYg-ZDncHM=/
[ +493 ms] The Flutter DevTools debugger and profiler on Pixel 5 is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:45645/mUYg-ZDncHM=/
[+5070 ms] Application finished.
```

```
Analyzing scroll_overlay...                                             
No issues found! (ran in 5.4s)
```

```
[✓] Flutter (Channel main, 3.7.0-13.0.pre.4, on Debian GNU/Linux 10 (buster) 4.19.0-23-amd64, locale en_US.UTF-8)
    • Flutter version 3.7.0-13.0.pre.4 on channel main at /home/greg/n/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 33e896b475 (6 weeks ago), 2022-12-25 23:14:13 -0800
    • Engine revision 339791f190
    • Dart version 3.0.0 (build 3.0.0-35.0.dev)
    • DevTools version 2.20.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/greg/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/greg/lib/android-studio-2020.3.1.24/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.13.4
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] Android Studio (version 2022.1)
    • Android Studio at /home/greg/lib/android-studio-2020.3.1.24
    • Flutter plugin version 71.2.4
    • Dart plugin version 221.6096
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.74.3)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 08171FDD40025F • android-arm64  • Android 13 (API 33)
    • Linux (desktop)  • linux          • linux-x64      • Debian GNU/Linux 10 (buster) 4.19.0-23-amd64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### LINKED ISSUE #120338: Scroll protocol assumes ballistic scroll physics, and ClampingScrollPhysics isn't ballistic
Scrolling in a Flutter list on Android and other platforms often feels much slower and less responsive than it should be. This issue is a major reason why: it can make a fling go about 15% less far than it should. This issue has also gotten in the way of previous attempts to fix some other reasons why.

## Background

The framework's approach to scrolling assumes that each ScrollPhysics implementation is restartable, or ballistic. (*) The simulation is frequently restarted, and the ScrollPhysics is responsible for not letting that cause problems.

This is a lot like how the framework may frequently rebuild widgets, and if that affects behavior then that's a bug in the widget.

In the case of scrolling, this assumption is very natural because it will automatically be satisfied by any scroll physics so long as it obeys a reasonable ("ballistic") physical metaphor:
* The thing that's scrolling is a physical object in motion.
* Its velocity changes due to physical forces on it, according to Newton's second law.
* Those forces depend only on (a) its current velocity and (b) where it is in its environment.

This metaphor works great for a wide variety of springs, frictional forces, clamping barriers, and other forms of scrolling physics one could dream up. Modulo small bugs (#109675, and ~another which I'll file shortly~ #120340 which affects macOS scrolling), it works great for all of the framework's scroll physics…

((*) This assumption doesn't seem to be clearly documented; I'll file a separate issue for that (→#120341), and see about writing a docs PR for it. Fundamentally it stems from the fact that `ScrollPhysics.createBallisticAnimation` takes only (a) a velocity and (b) a `ScrollMetrics`, where the latter encodes the current position plus some facts like `ScrollMetrics.maxScrollExtent` that describe the physical environment.)

## Problem

… all, that is, except one. The trouble is that one scroll physics, ClampingScrollPhysics, breaks this assumption.

(That's the scroll physics we use by default on Android and all other non-Apple platforms.)

If you restart it — specifically if you restart it in the middle of a fling, where it uses ClampingScrollSimulation — then it slows down more.

The effect is that scrolling is often much slower and less responsive-feeling than it should be. In the repro below, a fling goes about 20% less far than it does for a native Android list. Part of that is due to #119875, but most of it (a 15% reduction) is due to this issue.

#### Related issues

* Symptom caused by this issue and several others: #16371
* Different issue causing overlapping symptoms: #119875
* Thread about the fact that we do frequently restart the simulations: #11599
  (Frequently restarting isn't a bug in itself, unless it's so often as to become a performance issue. The bug is that we do restart, even sometimes, and that the physics doesn't handle this.)
* One visible quirk of ClampingScrollPhysics and ClampingScrollSimulation is that near the end, it speeds up slightly and then abruptly stops: #113424
  This quirk would be impossible in a restartable/ballistic scroll simulation: it has to slow down at every speed, or it would never stop.

## Steps to Reproduce

1. Run the [`platform_tests/scroll_overlay`](https://github.com/flutter/platform_tests/tree/1d797b8699546f1178e3cf58de9c6cc64f825281/scroll_overlay) app on an Android device.
2. Scroll with a fling gesture: swipe rapidly upward and release. Wait a couple of seconds for the scroll to come to a stop.
   * Swipe just once, and swipe as precisely straight upward as possible, just like with #119875.
3. Observe how far the scroll went, as shown by the numbered item "Flutter n" in the Flutter-driven scrolling list.

4. Edit `lib/main.dart` to delete the line `itemCount: 1000,`. Reload, and scroll back to the top.
5. Repeat steps 2 and 3.

**Expected results:** 

The list should go the same distance, reaching the same numbered item, regardless of whether the list is infinite or merely practically infinite. (With 1000 items, we never get close to the end of the list.)

**Actual results:** 

The list goes much less far with `itemCount: 1000` present than it does without it.

Specifically, when I try this on the current version of `scroll_overlay` (at flutter/platform_tests@1d797b8699546f1178e3cf58de9c6cc64f825281), I see "Flutter 81" at the top of the screen when the fling is complete. With `itemCount: 1000,` removed, I see "Flutter 90".

(Ideally the list should also go the same distance that the Android list does: I see "Android 94" at the top of the screen. With `itemCount` removed, the remaining discrepancy is #119875.)

This means the total distance travelled with `itemCount` present is about 15% less than without it, and about 20% less than the Android list. (Just dividing (90-81)/90 would give too low an estimate, because the later items are bigger: item N is 40+N logical pixels tall. The 15% and 20% are my calculations using those actual heights.)

**How the repro works:**

This repro uses the fact that passing a non-null `itemCount` to the `ListView` constructor causes frequent restarts of the scroll's ballistic simulation, #11599, and an `itemCount` of null suppresses them. That isolates the effect of this issue from #119875 and others.

<details><summary>Details of why `itemCount` affects the repro</summary>

When `itemCount` is non-null, the underlying SliverList will estimate a max scroll offset based on the children it's laid out, so this estimate constantly changes and each `ScrollPosition.applyContentDimensions` call causes an `applyNewDimensions` call, which leads to `goBallistic` and restarting the simulation. With a null `itemCount`, the estimate is always infinite (from `SliverMultiBoxAdaptorElement.estimateMaxScrollOffset`), so it never changes and `applyNewDimensions` isn't called.

</details>

<details>
  <summary>Logs</summary>

```
$ flutter analyze
Analyzing scroll_overlay...                                             
No issues found! (ran in 0.8s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel main, 3.8.0-8.0.pre.13, on Debian GNU/Linux 10 (buster) 4.19.0-23-amd64, locale en_US.UTF-8)
    • Flutter version 3.8.0-8.0.pre.13 on channel main at /home/greg/n/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2303f42250 (3 hours ago), 2023-02-08 14:24:12 -0500
    • Engine revision cc4ca6a06a
    • Dart version 3.0.0 (build 3.0.0-215.0.dev)
    • DevTools version 2.21.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/greg/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/greg/lib/android-studio-2020.3.1.24/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.13.4
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] Android Studio (version 2022.1)
    • Android Studio at /home/greg/lib/android-studio-2020.3.1.24
    • Flutter plugin version 71.2.4
    • Dart plugin version 221.6096
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 08171FDD40025F • android-arm64  • Android 13 (API 33)
    • Linux (desktop)  • linux          • linux-x64      • Debian GNU/Linux 10 (buster) 4.19.0-23-amd64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

## Android's scroll physics isn't ballistic either

When PR #77497 was merged in order to switch ClampingScrollSimulation to use the native Android physics (which would fix #113424 and #119875 and thereby some of the causes of #16371), it had to be reverted because of a variation on this issue. That was:
* #83632
  and its duplicate #84197

The root cause of those is that it turns out that the native Android scroll physics is also not restartable/ballistic, but in the opposite direction. Restarting the current ClampingScrollSimulation makes it slow down more, but restarting the Android scroll physics makes it keep going more, i.e. makes it slow down less.

Specifically, the Android physics starts at a deceleration of zero, and gradually decelerates more later. (See the curve at https://github.com/flutter/flutter/issues/119875#issuecomment-1414580430 , the blue Android curve in the lower-left graph showing velocity, and note that the velocity at the beginning is flat.) So if you restart it, then it returns to not decelerating — which, when it happens again and again, produces the extremely long gliding behavior seen in #83632.

(That issue title says the scroll "regains velocity", but I think that is an illusion. My eyes see that same illusion too; but when I repro the issue and log the velocity, it always gets slower, not faster. It's just that it gets slower very slowly.)

### PR DESCRIPTION
**Pull request by gnprice**
Fixes #120338.
Fixes #119875.
Fixes #113424.

Fixes most of #16371, as the combined symptom of those three. (There's still #120345, and possibly other contributing factors, remaining.)

This replaces the implementation of ClampingScrollSimulation with a new version that better matches the Android scroll physics it's intended to match.

The new implementation is a version of the Android curve which has been adjusted so that it behaves in a physically reasonable way, in order to satisfy an invariant which the Flutter scroll protocol relies on.

Because the old ClampingScrollSimulation didn't satisfy that invariant either, it suffered from a bug (#120338) where restarting the simulation with new metrics would have the side effect of adding friction, making a fling go about 15% less far. So this fixes #120338.

The new implementation also goes the same total distance as the Android scroll physics, whereas the existing version would go about 7% less far (stacking with the 15% reduction when the other issue was triggered.)  That fixes #119875.

Finally, the new implementation comes to a smooth stop, like Android does, whereas the existing version would speed slightly up before abruptly stopping.  That fixes #113424.

The new implementation's curve is the unique curve that both goes the same total distance as Android's for every possible starting velocity, and meets the Flutter scroll protocol's ballistic invariant.  So in that sense this is the canonical way of fixing up the Android behavior to something physically reasonable, or something that works correctly in Flutter.

Cc: @Piinks @grouma @goderbauer @nt4f04uNd @MxSoul who've previously been interested in this problem.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gnprice** [comment]
Here are before/after screen recordings showing the effect of this PR.  The recipe is very similar to the repro recipes for #119875 and #120338:
1. Use the [`platform_tests/scroll_overlay`](https://github.com/flutter/platform_tests/tree/1d797b8699546f1178e3cf58de9c6cc64f825281/scroll_overlay) app, on an Android device.
   * For these recordings, I use a version based on my platform_tests PR https://github.com/flutter/platform_tests/pull/13 , which fixes a small bug to make it easier to compare the Flutter and Android lists precisely.
   * On top of that PR, I use my further changes described at https://github.com/flutter/platform_tests/pull/13#issuecomment-1421313831 which improve the measurement overlay.

2. Scroll with a fling gesture, swiping rapidly straight upward.  In these recordings, after the first fling completes, I do a series of four rapid flings to test the momentum behavior too.

3. Observe how far the scroll goes, as shown by the numbered items.  In these recordings, you can also see the measured velocity at each frame displayed graphically on the right.

---

The first pair of recordings are with `itemCount: 1000` still included in the ListView constructor call.  This causes the framework to restart the simulation frequently, nearly every frame, so that it relies on the scroll physics being ballistic.

The "before" version therefore shows the effects of #120338 as well as #119875, so it suffers much too much drag; but the restarts mask the effect of #113424.

The "after" version matches Android much more closely, and ends at almost exactly the same place.

| Before, with restarts | After, with restarts |
| --- | --- |
| <video src="https://user-images.githubusercontent.com/28173/218006150-9978479c-ff58-4566-bfc7-ddc828300589.mp4"> | <video src="https://user-images.githubusercontent.com/28173/218007369-a819931c-dcc8-4673-a59c-c7fabd8e231c.mp4"> |






The second pair of recordings are with `itemCount: 1000` removed, which suppresses those restarts as described in the repro for #120338.

The "before" version therefore shows the effect of #113424, speeding up at the end.  And it still displays #119875, suffering too much drag but not as much as when #120338 is also present.

The "after" version again matches Android much more closely; the behavior is the same as in the version with restarts, to within the precision of my finger.  There's no speeding up at the end.

| Before, no restarts | After, no restarts |
| --- | --- |
| <video src="https://user-images.githubusercontent.com/28173/218006707-5d9aff4e-8bb8-4001-ab6e-8df0a5429227.mp4"> | <video src="https://user-images.githubusercontent.com/28173/218006717-97fdf432-a3e6-4db3-a8c3-b509dde7063a.mp4"> |

**Comment by gnprice** [comment]
This PR does not use Android's exact scrolling curve, as the previous PRs #77497 and #107735 did.  As described in #120338, the Android curve unfortunately does not satisfy the Flutter scroll protocol's invariant of physical reasonableness.

Using the Android curve without changes to the scroll protocol causes a loss of friction, #83632 — the effect is in the opposite direction from the existing curve's #119875, and is worse.

Revising the protocol to remove that invariant would be possible, but complicated, and probably requires a breaking change:
https://github.com/flutter/flutter/issues/120338#issuecomment-1423636999

This PR fixes the major user-visible issues with the current implementation and makes it much more similar to Android's.  When I try it out, either in `scroll_overlay` or in a more typical app, the scrolling now feels natural and responsive. (As long as you swipe vertically, pending #120345.)  The remaining discrepancy is in subtle details where Android's behavior loses any grounding in physical metaphor.

So I think it would be reasonable to declare that remaining discrepancy a polish issue in Android, not in Flutter, and stick with this PR's "like Android, but fixed" physics indefinitely.

Alternatively, even if we do intend to pursue changing the scroll protocol in order to use the Android curve, I think it would make sense to merge this implementation first, for two reasons:
* This fixes the existing physics's major user-visible issues in a much lower-risk way that can be shipped sooner.
* Because this makes the physics closer to Android's and the code no more complex, it doesn't put any new obstacles in the way of the other approach.

File: packages/flutter/test/widgets/scroll_simulation_test.dart [hunk 1]
```diff
@@ -23,4 +25,98 @@ void main() {
     checkInitialConditions(75.0, 614.2093);
     checkInitialConditions(5469.0, 182.114534);
   });
+
+  test('ClampingScrollSimulation only decelerates, never speeds up', () {
```
Comment (grouma) [inline packages/flutter/test/widgets/scroll_simulation_test.dart:29]: Can we add a test that the velocity eventually goes to zero?

**Comment by grouma** [comment]
What a wonderful set of write ups. I'm truly impressed and thank you!

I don't own any of this infrastructure so I can't provide a proper review but I did leave a suggestion for another test.

File: packages/flutter/test/widgets/scroll_simulation_test.dart (hunk 1 above)
Comment (gnprice) [reply packages/flutter/test/widgets/scroll_simulation_test.dart:29]: Sure, will do.

I think that follows as a consequence of being ballistic/restartable: if the simulation still has significant velocity in the last moments before the end (i.e., if the limit as time goes to the ending time isn't zero), then restarting it at that point would mean it goes on for longer than the few moments that were otherwise remaining.

But it would still be sensible to have a test for it directly.

**Comment by Piinks** [comment]
Thank you so much for all of this work! I have this and the other PR in scroll_overlay on my review queue, just wanted to acknowledge since it may take me a moment to review all of this.
As you know, we have tried to fix this a couple of times, and every time experienced regressions, so I'd also like to run this through all of the internal tests we have access to as well.
I really appreciate everything you have done here. Should have some feedback by the end of today.

File: packages/flutter/test/widgets/scroll_simulation_test.dart (hunk 1 above)
Comment (gnprice) [reply packages/flutter/test/widgets/scroll_simulation_test.dart:29]: Added.

**Review by Piinks — COMMENTED** [review]
I think this looks great, but will need to wait for Monday to test it extensively. Following up on the scroll_overlay PR now. :+1:

**Comment by whiskeyPeak** [comment]
Are these curves specific to flutter apps running on Android? I find that the scrolling curve on Linux also jumps a little towards the end.

**Comment by gnprice** [comment]
> Are these curves specific to flutter apps running on Android? I find that the scrolling curve on Linux also jumps a little towards the end.

This scroll physics is the one Flutter uses by default on all platforms other than iOS and macOS. So you're seeing #113424, which is one of the issues this PR fixes.

**Comment by Piinks** [comment]
I've fired off some additional internal testing, will report back.

**Comment by Piinks** [comment]
So I've tested this manually against some of the regressions we saw in the past from trying to resolve this issue, so far all is well. :+1:

**Comment by gnprice** [comment]
Great! Thanks for all the testing. Hoping those internal tests all come back green.

**Comment by Piinks** [comment]
Still following up on tests, there is an infra issue with triggering and returning the results here

**Comment by Piinks** [comment]
So there are some test failures, but they look to be expected. For example, if a customer has a screenshot test that scrolled before taking the picture, it would look different now. I will need a day or two to check all of the tests and communicate with customers.

**Comment by gnprice** [comment]
Makes sense. Thanks for your help!

**Comment by Piinks** [comment]
Update: Still working with customers to ensure all of the changes we can see are expected for this PR. Almost there. 👍

**Comment by Piinks** [comment]
Only 1 customer approval remains. Thanks for your patience.

**Comment by Piinks** [comment]
Customers are set. 👍

File: packages/flutter/lib/src/widgets/scroll_simulation.dart [hunk 2]
```diff
@@ -123,98 +123,129 @@ class BouncingScrollSimulation extends Simulation {
...
 
   /// The amount of friction the particle experiences as it travels.
   ///
-  /// The more friction the particle experiences, the sooner it stops.
+  /// The more friction the particle experiences, the sooner it stops and the
+  /// less far it travels.
+  ///
+  /// The default value causes the particle to travel the same total distance
+  /// as in the Android scroll physics.
+  // See mFlingFriction.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_simulation.dart:183]: This should take the form of a `See also` and a breadcrumb `[]` like in other docs.

File: packages/flutter/lib/src/widgets/scroll_simulation.dart [hunk 3]
```diff
@@ -123,98 +123,129 @@ class BouncingScrollSimulation extends Simulation {
...
 //
-// The "See..." comments below refer to Scroller methods and values. Some
-// simplifications have been made.
+// In the Android implementation, times are in milliseconds, positions are in
+// physical pixels, but velocity is in physical pixels per whole second.
+//
+// The "See..." comments below refer to SplineOverScroller methods and values.
 class ClampingScrollSimulation extends Simulation {
-  /// Creates a scroll physics simulation that matches Android scrolling.
+  /// Creates a scroll physics simulation that aligns with Android scrolling.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_simulation.dart:157]: Aligns. Nice. :)

**Review by Piinks — APPROVED** [review]
This LGTM, let me seek out a second reviewer

File: packages/flutter/lib/src/widgets/scroll_simulation.dart (hunk 2 above)
Comment (gnprice) [reply packages/flutter/lib/src/widgets/scroll_simulation.dart:183]: Cool. Yeah, this is a reference to the corresponding Android source (like some other private comments in this class), so I think it's useful only for someone actually reading the implementation.

**Review by jonahwilliams — APPROVED** [review]
LGTM
