### PR TITLE
Mention visualDensity impact on ButtonStyle.padding documentation

### LINKED ISSUE #137411: Incorrect vertical padding for `ElevatedButton` from `ButtonStyle`
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

(tested on macos, stable and master)

Create a new flutter project and paste the following into `main.dart`:

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark(),
      home: const Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      onPressed: () {},
      style: const ButtonStyle(
        backgroundColor: MaterialStatePropertyAll(Colors.blue),
        padding: MaterialStatePropertyAll(
          EdgeInsets.all(30), // <================= 30 horizontal and vertical
        ),
      ),
      child: Container(
        color: Colors.black,
        width: 10,
        height: 10,
      ),
    );
  }
}
```

</p>
</details> 

### Expected results

The given padding should be used for horizontal and vertical padding.

### Actual results

The horizontal padding is honoured, but the vertical padding is too small:

On stable:

- Top padding 22 ❌
  - Screenshot 2023-10-27 at 14 40 14
  
- Right padding 30 ✅
  - Screenshot 2023-10-27 at 14 40 24

On master:
- Top padding 23 ❌
  - Screenshot 2023-10-27 at 14 51 40
- Right padding 30 ✅
  - Screenshot 2023-10-27 at 14 51 51

### Code sample

See above

### Screenshots or Video

See above

### Logs

None

### Flutter Doctor output

<details><summary>Doctor output (stable)</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.4 22F66 darwin-arm64, locale en-DE)
    • Flutter version 3.13.9 on channel stable at /Users/gian/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gian/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

<details><summary>Doctor output (master)</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel master, 3.16.0-18.0.pre.63, on macOS 13.4 22F66 darwin-arm64, locale en-DE)
    • Flutter version 3.16.0-18.0.pre.63 on channel master at /Users/gian/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eba149fcc3 (4 hours ago), 2023-10-27 12:04:07 +0300
    • Engine revision bedc49efc8
    • Dart version 3.3.0 (build 3.3.0-56.0.dev)
    • DevTools version 2.28.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gian/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR adds some information about how the Material buttons padding is impacted by visual density.

## Related Issue

Fixes https://github.com/flutter/flutter/issues/137411

## Tests

Documentation only.

### CODE REVIEW

File: packages/flutter/lib/src/material/button_style.dart [hunk 1]
```diff
@@ -210,6 +210,25 @@ class ButtonStyle with Diagnosticable {
   final MaterialStateProperty<double?>? elevation;
 
   /// The padding between the button's boundary and its child.
+  ///
+  /// The vertical padding is adjusted based on [visualDensity].
```
[the remark this answers is not in the document]
Comment (bleroux) [reply packages/flutter/lib/src/material/button_style.dart:214]: The padding is first resolved (the one specified if set, otherwhise the default one) then changed based on visual density.
Here is where this logic is located:
https://github.com/flutter/flutter/blob/4c46030927626782555918be39985ff95de83438/packages/flutter/lib/src/material/button_style_button.dart#L396-L400

[the remark this answers is not in the document]
Comment (HansMuller) [reply packages/flutter/lib/src/material/button_style.dart:214]: Thanks for clarifying that. Since this is somewhat unusual, it might be good to emphasize it a little. For example: 
```
The vertical aspect of the default or user-specified padding is adjusted automatically based on visualDensity.
```

File: packages/flutter/lib/src/material/button_style.dart [hunk 2]
```diff
@@ -210,6 +210,25 @@ class ButtonStyle with Diagnosticable {
...
+  ///
+  /// When the visual density is [VisualDensity.compact], the top and bottom paddings
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/button_style.dart:216]:
```suggestion
  /// When the visual density is [VisualDensity.compact], the top and bottom insets
```

File: packages/flutter/lib/src/material/button_style.dart [hunk 3]
```diff
@@ -210,6 +210,25 @@ class ButtonStyle with Diagnosticable {
...
+  /// are reduced by 8.0 pixels or set to 0 pixels if the result of the reduced padding
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/button_style.dart:217]:
```suggestion
  /// are reduced by 8 pixels or set to 0 pixels if the result of the reduced padding
```

File: packages/flutter/lib/src/material/button_style.dart [hunk 4]
```diff
@@ -210,6 +210,25 @@ class ButtonStyle with Diagnosticable {
...
+  /// is negative. E.g. The visual density defaults to [VisualDensity.compact] on desktop
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/button_style.dart:218]:
```suggestion
  /// is negative. For example: the visual density defaults to [VisualDensity.compact] on desktop
```

File: packages/flutter/lib/src/material/button_style.dart [hunk 5]
```diff
@@ -210,6 +210,25 @@ class ButtonStyle with Diagnosticable {
...
+  /// and web, if the provided padding is 16 pixels on the top and bottom, it will be
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/button_style.dart:219]:
```suggestion
  /// and web, so if the provided padding is 16 pixels on the top and bottom, it will be
```

File: packages/flutter/lib/src/material/button_style.dart [hunk 6]
```diff
@@ -210,6 +210,25 @@ class ButtonStyle with Diagnosticable {
...
+  /// reduced to 8 pixels on the top and bottom, if the provided padding is 4 pixels,
+  /// it will result to no padding on the top and bottom.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/button_style.dart:221]:
```suggestion
  /// the result will be no padding on the top and bottom.
```

File: packages/flutter/lib/src/material/button_style.dart [hunk 7]
```diff
@@ -210,6 +210,25 @@ class ButtonStyle with Diagnosticable {
...
+  ///
+  /// When the visual density is [VisualDensity.comfortable], the top and bottom paddings
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/button_style.dart:223]:
```suggestion
  /// When the visual density is [VisualDensity.comfortable], the top and bottom insets
```

File: packages/flutter/lib/src/material/button_style.dart [hunk 8]
```diff
@@ -210,6 +210,25 @@ class ButtonStyle with Diagnosticable {
...
+  /// are reduced by 4.0 pixels or set to 0 pixels if the result of the reduced padding
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/button_style.dart:224]:
```suggestion
  /// are reduced by 4 pixels or set to 0 pixels if the result of the reduced padding
```

File: packages/flutter/lib/src/material/button_style.dart [hunk 9]
```diff
@@ -210,6 +210,25 @@ class ButtonStyle with Diagnosticable {
...
+  /// is negative.
+  ///
+  /// When the visual density is [VisualDensity.standard] the top and bottom paddings
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/button_style.dart:227]:
```suggestion
  /// When the visual density is [VisualDensity.standard] the top and bottom insets
```

File: packages/flutter/lib/src/material/button_style.dart [hunk 10]
```diff
@@ -210,6 +210,25 @@ class ButtonStyle with Diagnosticable {
...
+  /// are not changed. E.g. The visual density defaults to [VisualDensity.standard]
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/button_style.dart:228]:
```suggestion
  /// are not changed. The visual density defaults to [VisualDensity.standard]
```

File: packages/flutter/lib/src/material/button_style.dart [hunk 11]
```diff
@@ -210,6 +210,25 @@ class ButtonStyle with Diagnosticable {
...
+  /// on mobile,
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/button_style.dart:229]:
```suggestion
  /// on mobile.
```

File: packages/flutter/lib/src/material/button_style.dart [hunk 12]
```diff
@@ -210,6 +210,25 @@ class ButtonStyle with Diagnosticable {
...
 
   /// The padding between the button's boundary and its child.
+  ///
+  /// The vertical padding is adjusted based on [visualDensity].
+  ///
+  /// When the visual density is [VisualDensity.compact], the top and bottom paddings
+  /// are reduced by 8.0 pixels or set to 0 pixels if the result of the reduced padding
+  /// is negative. E.g. The visual density defaults to [VisualDensity.compact] on desktop
+  /// and web, if the provided padding is 16 pixels on the top and bottom, it will be
+  /// reduced to 8 pixels on the top and bottom, if the provided padding is 4 pixels,
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/button_style.dart:220]:
```suggestion
  /// reduced to 8 pixels on the top and bottom. If the provided padding is 4 pixels,
```

**Review by HansMuller — APPROVED** [review]
This looks like a nice improvement. Just some minor wordsmithing.

File: packages/flutter/lib/src/material/button_style.dart (hunk 1 above)
[the remark this answers is not in the document]
Comment (bleroux) [reply packages/flutter/lib/src/material/button_style.dart:214]: Thanks a lot for this great rewording and for all the other suggestions (today I learned a new english word: **wordsmithing** :tada:)
