### PR TITLE
Change modal barrier to dismissing on tap up

### LINKED ISSUE #41178: Dialog is dismissed on screen touch
Flutter dialog are closed immediately on screen touch. Android native behavior is different. User can touch screen and swipe away to abort dialog dismissal. Problem becomes very visible when using flutter dialogs with android 10 gestural navigation

| Native Android | Flutter |
| ------ | ------- |
| dialog_dismiss_native | dialog_dismiss_flutter |

## Steps to Reproduce

1. Open dialog
2. Press & hold screen, make swipe gesture
3. Drag back to abort back navigation
4. Observe: Dialog should not be dismissed

```dart
RaisedButton(
  child: Text("openDialog"),
  onPressed: () async => await showDialog(
    context: context,
    builder: (context) => SimpleDialog(
      children: <Widget>[Text("Some dialog")],
    ),
)),
```

## Logs

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/audrius/Documents/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/audrius/Documents/android-sdk-canary
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/audrius/Documents/android-sdk-canary
    • Java binary at:
      /home/audrius/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5791312/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.
```

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

Currently Flutter's `ModalBarrier` is dismissed on _tap down_ (when the finger starts contacting the screen), which was [discovered](https://github.com/flutter/flutter/issues/41178) to deviate from the OEM behavior:
- on iOS the modal has always been dismissed by _tap up_ (when the finger stops contacting the screen)
- on Android it had been tap down until 9 and was changed to tap up since 10. This has caused a severe conflict with the new gesture navigation in Android 10 (#41178).

According to Flutter's philosophy of [_Widget libraries follow the latest OEM behavior_](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#widget-libraries-follow-the-latest-oem-behavior), we're changing `ModalBarrier` so they're always dismissed on tap up.

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/41178

## Tests

I changed the following tests:
- `ModalBarrier` should be dismissed by tap up

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (Please read [Handling breaking changes]). https://groups.google.com/forum/#!topic/flutter-announce/fYCVT5fE71E

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/widgets/modal_barrier_test.dart [hunk 1]
```diff
@@ -114,7 +114,7 @@ void main() {
       reason: 'The route should have been dismissed by tapping the barrier.');
   });
 
-  testWidgets('ModalBarrier pops the Navigator when dismissed by primary tap down', (WidgetTester tester) async {
+  testWidgets('ModalBarrier pops the Navigator when dismissed by non-primary tap', (WidgetTester tester) async {
```
Comment (goderbauer) [inline packages/flutter/test/widgets/modal_barrier_test.dart]: There should probably be a test that verifies the dismiss happens on the up. It looks like this test would also pass when the dismiss happened on the down?

Comment (dkwingsmt) [reply packages/flutter/test/widgets/modal_barrier_test.dart]: I've changed the tests so that they verify that dismiss happens during the pointer up event

**Review by goderbauer — APPROVED** [review]
LGTM
