### PR TITLE
exclude files from build/ when looking for asset variants

### LINKED ISSUE #3508: crash while building an flx
## command

flutter build flx --target ... --output-file ... --snapshot ... --depfile ... --no-include-roboto-fonts --manifest assets.yaml

## exception

FileSystemException: Cannot open file, path = .../build/flx/icon.png' (OS Error: No such file or directory, errno = 2)

```
dart:io                                                           _File.readAsBytesSync
package:flutter_tools/src/zip.dart 89                             _ZipToolBuilder.createZip
package:flutter_tools/src/flx.dart 383                            assemble.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/flx.dart 401                            assemble.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/flx.dart                                assemble
package:flutter_tools/src/flx.dart 308                            build.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 60                    runCommandAndStreamOutput.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/flx.dart                                build
package:flutter_tools/src/commands/build_flx.dart 48              BuildFlxCommand.runInProject.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/build_flx.dart                 BuildFlxCommand.runInProject
package:flutter_tools/src/runner/flutter_command.dart 156         FlutterCommand._run.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 108                          Cache.updateAll.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand._run
package:flutter_tools/src/runner/flutter_command.dart 94          FlutterCommand.run
package:args/command_runner.dart 176                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 129                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 239  FlutterCommandRunner.runCommand
package:args/command_runner.dart 103                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 103                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 187  FlutterCommandRunner.run
package:flutter_tools/executable.dart 85                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 79                          main.<async>

### PR DESCRIPTION
**Pull request by devoncarew**
- exclude files from build/ when looking for asset variants, fix https://github.com/flutter/flutter/issues/3508

@jason-simmons

### CODE REVIEW

File: packages/flutter_tools/lib/src/flx.dart [hunk 1]
```diff
@@ -115,7 +115,13 @@ Map<_Asset, List<_Asset>> _parseAssets(
 
       List<FileSystemEntity> files = assetDir.listSync(recursive: true);
 
+      final String buildDirPath = path.absolute(path.join(assetBase, 'build'));
```
Comment (jason-simmons) [inline packages/flutter_tools/lib/src/flx.dart]: This should be the workingDirPath that is given to the ZipBuilder

Comment (devoncarew) [inline packages/flutter_tools/lib/src/flx.dart]: That defaults to `build/flx`. We do want to exclude that dir - to avoid recursion - but I think we want to exclude the contents of the full `build/` dir as well. What about passing a param into `_parseAssets()` - a directory to exclude?

Comment (jason-simmons) [inline packages/flutter_tools/lib/src/flx.dart]: That's fine - I just want to ensure that the FLX working directory will be excluded if its path was overridden by a command line flag

Alternatively, maybe we should require that assets be located within a dedicated directory?  Or require that variants follow a specific file layout or be declared explicitly in the manifest?

Doing a search through the entire directory tree for files matching a given name seems like it carries the risk of misidentifying variants.

Comment (devoncarew) [inline packages/flutter_tools/lib/src/flx.dart]: > I just want to ensure that the FLX working directory will be excluded if its path was overridden by a command line flag

Ah, ok.

> Alternatively, maybe we should require that assets be located within a dedicated directory? Or require that variants follow a specific file layout or be declared explicitly in the manifest?
> Doing a search through the entire directory tree for files matching a given name seems like it carries the risk of misidentifying variants.

Totally agree. I'll change this PR to exclude both the `build/` dir, and the directory that we're zipping up (which, they'll frequently be overlap there).

Also cc'ing @krisgiesing fr ideas re: adopting some conventions around where assets and their variants can live.

Comment (krisgiesing) [inline packages/flutter_tools/lib/src/flx.dart]: The directory search for variants should be rooted at the directory where the main asset is located. Can you give an example where you believe this search would be too permissive? Forcing the variants to follow a too-specific convention now risks brittleness when we start adding variants along more dimensions than just device pixel ratio.

I'm fine adding a convention for where all assets live, and preventing other artifacts from living there too. Most systems have that. But I don't know if that would address your concern.

I'd prefer not to have to include all asset variants by name; that removes a considerable part of the convenience.

**Comment by devoncarew** [comment]
ptal, updated to exclude the `build/` directory, and the directory where we are assembling the flx zip file, when searching for asset variants.

File: packages/flutter_tools/lib/src/flx.dart (hunk 1 above)
Comment (devoncarew) [inline packages/flutter_tools/lib/src/flx.dart]: > I'm fine adding a convention for where all assets live, and preventing other artifacts from living there too. Most systems have that.

Perhaps we just discourage them from living in `.`?

**Comment by jason-simmons** [comment]
LGTM

File: packages/flutter_tools/lib/src/flx.dart (hunk 1 above)
Comment (krisgiesing) [inline packages/flutter_tools/lib/src/flx.dart]: I see the referenced issue now. Yeah, I think we should disallow assets at the project root; even with build/ excluded, the extra tree searching is inefficient.
