### PR TITLE
Fix SemanticsFinder for multi-view

### LINKED ISSUE #143405: SemanticsController.simulatedAccessibilityTraversal broken in multiple views
Found in
- Issue https://github.com/flutter/flutter/issues/143173
- PR https://github.com/flutter/flutter/pull/143386

In SemanticsController.simulatedAccessibilityTraversal, the `start` and `end` parameters are deprecated. They are replaced by `startNode` and `endNode`, but writing a test for this in the context of multiple views fails. 

I wrote such a test in `packages/flutter_test/test/multi_view_controller_test.dart`

```dart
testWidgets('simulatedAccessibilityTraversal - startNode and endNode in same view', (WidgetTester tester) async {
    tester.binding.ensureSemantics();
    await pumpViews(tester: tester);
    expect(
      tester.semantics.simulatedAccessibilityTraversal(
        startNode: find.semantics.byValue('View2Child1'),
        endNode: find.semantics.byValue('View2Child3'),
      ).map((SemanticsNode node) => node.label),
      <String>[
        'View2Child1',
        'View2Child2',
        'View2Child3',
      ],
    );
  });
```

but it failed with 

```The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:674:25)
#1      SemanticsController.simulatedAccessibilityTraversal (package:flutter_test/src/controller.dart:207:57)
```

This is coming from here when we are trying to look up the SemanticsOwner:

https://github.com/flutter/flutter/blob/efd1d1f536ece87fc8c3437879f7f95f12e0d184/packages/flutter_test/lib/src/controller.dart#L202

The new API works in the single view world, so I am going to move forward with that PR to resolve other issues unrelated to this one. 

cc @goderbauer

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/143405.

It was counter-intuitive that a SemanticsFinder without specifying a FlutterView would only search the nodes in the default view. This change makes it so that when no view is specified the semantics trees of all known FlutterViews are searched.

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Might have to revert https://github.com/flutter/flutter/pull/143386 which would block this, investigating now.

**Comment by Piinks** [comment]
It was reverted, but I have a quick fix to turn it around. :)

File: packages/flutter_test/lib/src/finders.dart [hunk 1]
```diff
@@ -1065,16 +1056,44 @@ abstract class Finder extends FinderBase<Element> with _LegacyFinderMixin {
...
 abstract class SemanticsFinder extends FinderBase<SemanticsNode> {
-  /// Creates a new [SemanticsFinder] that will search starting at the given
-  /// `root`.
-  SemanticsFinder(this.root);
+  /// Creates a new [SemanticsFinder] that will search within the given [view] or
+  /// within all views if [view] is null.
+  SemanticsFinder(this.view);
 
-  /// The root of the semantics tree that this finder will search.
-  final SemanticsNode root;
```
Comment (Piinks) [inline packages/flutter_test/lib/src/finders.dart:1073]: So very fortunate this does not appear to break anyone!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
