### PR TITLE
Let SnackBar inherit themeData from its ancestor

### LINKED ISSUE #69894: SnackBar with own widget as content uses incorrect theme
## Steps to Reproduce

1. Run `flutter create snackbar_issue`.
2. Paste this code in main.dart

```
import 'package:flutter/material.dart';
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SnackBar test',
      theme: ThemeData(
        textTheme: TextTheme(
          bodyText1: TextStyle(fontSize: 25.0,fontFamily: 'GTAmerica', color: Colors.amber),
        ),
        //
        snackBarTheme: SnackBarThemeData(
          // This also does not seem to apply
          contentTextStyle: TextStyle(fontSize: 35.0, fontFamily: 'GTAmerica', color: Colors.amber),
        ),
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'SnackBar test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(child: SnackBarTest()),
    );
  }
}

class SnackBarTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final TextStyle textStyle = Theme.of(context).textTheme.bodyText1;
    return ElevatedButton(
        child: Text('Show SnackBar'),
        onPressed: () {
          Scaffold.of(context).showSnackBar(SnackBar(
            backgroundColor: Colors.lightBlue,
            behavior: SnackBarBehavior.floating,
            // Sending my own widget to the SnackBar fails to use the theme, the default TextStyle is used.
            content: MySnackBar('Hello I am a SnackBar'),
            // Using a Text widget here works fine, it uses the correct theme for bodyText1. 
            // content: Text(
            //     'Hello Im a SnackBar with font size ${textStyle.fontSize} and font family ${textStyle.fontFamily} ', 
            //     style: textStyle),
          ));
        });
  }
}

class MySnackBar extends StatelessWidget {
  final String text;
  const MySnackBar(this.text);

  @override
  Widget build(BuildContext context) {
    // Here I expect that the bodyText1 from my theme is used but that is not the case, instead some default value is used
    TextStyle textStyle = Theme.of(context).textTheme.bodyText1;
    return Text('$text with font size ${textStyle.fontSize}, font family ${textStyle.fontFamily} and color ${textStyle.color}', style: textStyle);
  }
}

```
3. If I pass a `Text` widget to the SnackBar the font and font style is shown correctly from the theme. But if I pass my own widget it applies the default theme.

**Expected results:** When I pass `content: MySnackBar('Hello I am a SnackBar')` to the `SnackBar()` I expect it to use the TextStyle from my theme that I apply to it (`Theme.of(context).textTheme.bodyText1`).

**Actual results:** When I'm using my own widget it uses the default TextStyle (FontSize: 14, fontFamily: Roboto, color: white). It seems like it uses another context while showing the SnackBar. 

<details>
  <summary>Logs</summary>

```
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.50.1)
 
[✓] Connected device (2 available)            

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

This change let `SnackBar` inherit `ThemeData` from its ancestor so that its descendants can use those data.

## Related Issues

Fixes #69894 

## Tests

I added the following tests:

See files.

### CODE REVIEW

File: packages/flutter/lib/src/material/snack_bar.dart [hunk 1]
```diff
@@ -460,7 +460,7 @@ class _SnackBarState extends State<SnackBar> {
     final Color themeBackgroundColor = isThemeDark
       ? colorScheme.onSurface
       : Color.alphaBlend(colorScheme.onSurface.withOpacity(0.80), colorScheme.surface);
-    final ThemeData inverseTheme = ThemeData(
+    final ThemeData inverseTheme = theme.copyWith(
       brightness: brightness,
       backgroundColor: themeBackgroundColor,
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/snack_bar.dart:465]: Can we have the Snackbar use the colorScheme's background color instead of ThemeData.backgroundColor?

File: packages/flutter/lib/src/material/snack_bar.dart [hunk 2]
```diff
@@ -480,10 +480,9 @@ class _SnackBarState extends State<SnackBar> {
         onError: colorScheme.error,
         brightness: brightness,
       ),
-      snackBarTheme: snackBarTheme,
     );
 
-    final TextStyle? contentTextStyle = snackBarTheme.contentTextStyle ?? inverseTheme.textTheme.subtitle1;
+    final TextStyle? contentTextStyle = snackBarTheme.contentTextStyle ?? ThemeData(brightness: brightness,).textTheme.subtitle1;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/snack_bar.dart:485]: Why isn't this `theme.textTheme.subtitle1`?  If this version produces a text style with a different color (I can't see that, but I probably haven't looked closely enough), then why not compute the foreground color and use `theme.textTheme.subtitle1.copyWith(color: foregroundColor)`?

File: packages/flutter/lib/src/material/snack_bar.dart [hunk 3]
```diff
@@ -460,7 +460,7 @@ class _SnackBarState extends State<SnackBar> {
     final Color themeBackgroundColor = isThemeDark
       ? colorScheme.onSurface
       : Color.alphaBlend(colorScheme.onSurface.withOpacity(0.80), colorScheme.surface);
-    final ThemeData inverseTheme = ThemeData(
+    final ThemeData inverseTheme = theme.copyWith(
       brightness: brightness,
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/snack_bar.dart:464]: This value came from `theme.brightness`. We're trying to move away from ThemeData dependencies, aside from colorScheme and textTheme; can we use `colorScheme.brightness` instead?

**Review by HansMuller — COMMENTED** [review]
This seems like a good update although maybe it can be taken a bit further.

File: packages/flutter/lib/src/material/snack_bar.dart (hunk 2 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/snack_bar.dart:483]: This version produces a test style with different color and size by default.
Additionally, If the developer provides a custom `subtitle1`, it will change `SnackBar` behavior

File: packages/flutter/lib/src/material/snack_bar.dart (hunk 3 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/snack_bar.dart]: done

File: packages/flutter/lib/src/material/snack_bar.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/snack_bar.dart]: done

File: packages/flutter/lib/src/material/snack_bar.dart (hunk 2 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/snack_bar.dart:483]: Understood that the color would be different, that's why I suggested computing the foreground color etc.  Why would the size be different?  As far as I can tell, `theme.textTheme` is just the top-level theme's text theme. If the developer has overridden that, then we should honor the override. 

Note also: SnackbarTheme has a contentTextStyle. For the sake of consistency, Snackbar should too.

Comment (xu-baolin) [reply packages/flutter/lib/src/material/snack_bar.dart:483]: `ThemeData(brightness: brightness,).textTheme.subtitle1` is:
`TextStyle(debugLabel: whiteMountainView subtitle1, inherit: true, color: Color(0xffffffff), family: Roboto, decoration: TextDecoration.none)`

`theme.textTheme.subtitle1` is (comes from `MaterialApp`):
`TextStyle(debugLabel: (englishLike subhead 2014).merge(blackMountainView subtitle1), inherit: false, color: Color(0xdd000000), family: Roboto, size: 16.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none)`

And if we change this style to `theme.textTheme.subtitle1`, will cause 18 test cases failed:
image

Comment (xu-baolin) [reply packages/flutter/lib/src/material/snack_bar.dart:483]: Any thoughts about this, Keep as is or breaking it?

Comment (shihaohong) [reply packages/flutter/lib/src/material/snack_bar.dart:483]: I tried to dive into why the values differ and couldn't quite figure it out, although the value from `theme.textTheme.subtitle` [looks more correct](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/typography.dart#L507). The only correct thing about `ThemeData(brightness: brightness,).textTheme.subtitle1` is the color value.

Let's keep it as-is here. I think this particular change can be its own separate PR where we address the breaking changes (and migration guide), since those breaking changes will likely result in Google testing failures and the test failures in your above screenshot.

File: packages/flutter/lib/src/material/snack_bar.dart [hunk 4]
```diff
@@ -480,10 +478,9 @@ class _SnackBarState extends State<SnackBar> {
         onError: colorScheme.error,
         brightness: brightness,
       ),
-      snackBarTheme: snackBarTheme,
     );
 
-    final TextStyle? contentTextStyle = snackBarTheme.contentTextStyle ?? inverseTheme.textTheme.subtitle1;
+    final TextStyle? contentTextStyle = snackBarTheme.contentTextStyle ?? ThemeData(brightness: brightness,).textTheme.subtitle1;
```
Comment (shihaohong) [inline packages/flutter/lib/src/material/snack_bar.dart:483]: nit: trailing comma
```suggestion
    final TextStyle? contentTextStyle = snackBarTheme.contentTextStyle ?? ThemeData(brightness: brightness).textTheme.subtitle1;
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 5]
```diff
@@ -669,6 +669,149 @@ void main() {
...
+
+    await tester.tap(find.text('X'));
+    await tester.pump(); // start animation
+    await tester.pump(const Duration(milliseconds: 750));
+
+    final ThemeData comparedTheme = themeBeforeSnackBar!.copyWith(
+      colorScheme: themeAfterSnackBar!.colorScheme,
+    ); // Fields replaced by SnackBar.
+
+    expect(comparedTheme == themeAfterSnackBar, true);
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart:812]:
```suggestion
    expect(comparedTheme, themeAfterSnackBar);
```

File: packages/flutter/test/material/snack_bar_test.dart [hunk 6]
```diff
@@ -669,6 +669,149 @@ void main() {
...
+
+    const PageTransitionsTheme pageTransitionTheme = PageTransitionsTheme(
+      builders: <TargetPlatform, PageTransitionsBuilder>{
+        TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
+        TargetPlatform.macOS: CupertinoPageTransitionsBuilder(),
+      },
+    );
+
+    final ThemeData theme = ThemeData.raw(
+      visualDensity: const VisualDensity(),
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart:694]: If you merge with upstream master, you'll notice that you need three more new theme properties:
```dart
      // ...
      radioTheme: const RadioThemeData(),
      switchTheme: const SwitchThemeData(),
      checkboxTheme: const CheckboxThemeData(),
```

File: packages/flutter/lib/src/material/snack_bar.dart (hunk 2 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/snack_bar.dart]: OK, sounds good!

File: packages/flutter/test/material/snack_bar_test.dart [hunk 7]
```diff
@@ -669,6 +669,152 @@ void main() {
...
+                        action: SnackBarAction(
+                          label: 'ACTION',
+                          onPressed: () { },
+                        ),
+                      ),
+                    );
+                  },
+                  child: const Text('X'),
+                );
+              }
```
Comment (shihaohong) [inline packages/flutter/test/material/snack_bar_test.dart:801]: nit: 2 less spaces for this block
```suggestion
              builder: (BuildContext context) {
                themeBeforeSnackBar = Theme.of(context);
                return GestureDetector(
                  onTap: () {
                    Scaffold.of(context).showSnackBar(
                      SnackBar(
                        content: Builder(
                          builder: (BuildContext context) {
                            themeAfterSnackBar = Theme.of(context);
                            return const Text('I am a snack bar.');
                          },
                        ),
                        duration: const Duration(seconds: 2),
                        action: SnackBarAction(
                          label: 'ACTION',
                          onPressed: () { },
                        ),
                      ),
                    );
                  },
                  child: const Text('X'),
                );
              },
```

**Review by shihaohong — APPROVED** [review]
LGTM, thanks for the fix! :)

**Comment by shihaohong** [comment]
I just checked the `Google testing` failures and they seem acceptable -- Some text font/padding has been affected, but this is the result of the SnackBar now inheriting ThemeData from its ancestor correctly.

**Comment by shihaohong** [comment]
Fixed the internal failures. This PR should now be good to go :) Thanks again! 

Also glad we decided to split up considering [contextTextStyle](https://github.com/flutter/flutter/pull/70080#discussion_r526382463) to a separate PR, since it'd likely cause a lot of changes that may not be easy to tackle.
