### PR TITLE
[Android] Remap each pair of `(pointerId, toolType)` to its own unique id

### LINKED ISSUE #160144: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 224 pos 12: '(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)': is not true. when emulation touches on a mobile device with a mouse
### Steps to reproduce

Just Tap on the Mobile Screen with the help of TouchPad of your laptop

### Expected results

It should not come and not shown in the terminal

### Actual results

Getting the Issue ->

<details open><summary>Logs</summary>

```console

======== Exception caught by gestures library ======================================================
The following assertion was thrown while handling a pointer data packet:
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 224 pos 12: '(event is PointerAddedEvent) == (lastEvent is PointerRemovedEvent)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      MouseTracker._shouldMarkStateDirty (package:flutter/src/rendering/mouse_tracker.dart:224:12)
#3      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:318:10)
#4      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:20)
#5      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:427:7)
#6      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:390:5)
#7      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:337:7)
#8      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:306:9)
#9      _invoke1 (dart:ui/hooks.dart:328:13)
#10     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:450:7)
#11     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Screenshot 2024-12-12 at 1 07 14 PM

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64 (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Hardik's iPhone. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for AKSHAY DAHIYA’s iPhone. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Himanshu’s iPhone. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by gmackall**
Fixes https://github.com/flutter/flutter/issues/160144, by replacing the ID passed by original Android `MotionEvent` with a newly constructed one that is unique per tool type, per offline discussion with @dkwingsmt. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/AndroidTouchProcessorTest.java [hunk 1]
```diff
@@ -537,23 +538,34 @@ public void timeStamp() {
   }
 
   @Test
-  public void device() {
+  public void samePointerIdWithDifferentToolTypes_mapsToUniqueDevice() {
```
Comment (gmackall) [inline engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/AndroidTouchProcessorTest.java:541]: The old test was no longer valid, as the device id in the packet is no longer expected to be equal to the one that was set on the MotionEvent. So I renamed and repurposed this test to instead verify that when we have two motion events with
1. the same MotionEvent - level pointer id
2. different tools

the device ids in the two packets are different

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java [hunk 2]
```diff
@@ -270,6 +280,17 @@ private void addPointerForIndex(
...
 
+  // Some screen mirroring tools will occasionally report the same ID as having different associated
+  // tool types across different events, which breaks Flutter's internal handling of pointer events.
+  // Instead give each (pointerId, toolType) pair a unique ID. Technically this could break when
+  // handling a pointer of id 2^29, but that seems unlikely. Flutter's internal handling uses a
+  // long, so it can be fixed if needed.
+  // See https://github.com/flutter/flutter/issues/160144.
+  private int uniquePointerIdByType(MotionEvent event, int pointerIndex) {
+    return (event.getPointerId(pointerIndex) << TOOL_TYPE_BITS)
+        | (event.getToolType(pointerIndex) & TOOL_TYPE_MASK);
```
Comment (gmackall) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java:293]: Maybe this should instead use flutter's `PointerDeviceKind`? Not sure

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java [hunk 3]
```diff
@@ -270,6 +280,17 @@ private void addPointerForIndex(
         event, pointerIndex, pointerChange, pointerData, transformMatrix, packet, null);
   }
 
+  // Some screen mirroring tools will occasionally report the same ID as having different associated
+  // tool types across different events, which breaks Flutter's internal handling of pointer events.
+  // Instead give each (pointerId, toolType) pair a unique ID. Technically this could break when
+  // handling a pointer of id 2^29, but that seems unlikely. Flutter's internal handling uses a
+  // long, so it can be fixed if needed.
+  // See https://github.com/flutter/flutter/issues/160144.
+  private int uniquePointerIdByType(MotionEvent event, int pointerIndex) {
```
Comment (dkwingsmt) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java:290]: Shall we assert `event.getToolType(pointerIndex) & ~TOOL_TYPE_MASK  == 0` to ensure the tool type bits?

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java (hunk 2 above)
Comment (dkwingsmt) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java:293]: Yeah I think either is ok. But at least you should keep this implementation in sync with the doc of `TOOL_TYPE_BITS`. The doc said 6 types, while `MotionEvent.getToolType` only has 4 types (which should probably still use 4 bits for safety).

**Review by dkwingsmt — APPROVED** [review]
LGTM. Thank you for working on this!

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java [hunk 4]
```diff
@@ -53,6 +53,7 @@ public class AndroidTouchProcessor {
   }
 
   // Must match the PointerDeviceKind enum in pointer.dart.
+  // Also consider changing TOOL_TYPE_BITS when changing the length of this enum.
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java]:
```suggestion
  // When changing the length of this enum check if TOOL_TYPE_BITS needs to increase its value. Next increase is at length 8. 
```

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java [hunk 5]
```diff
@@ -270,6 +280,17 @@ private void addPointerForIndex(
         event, pointerIndex, pointerChange, pointerData, transformMatrix, packet, null);
   }
 
+  // Some screen mirroring tools will occasionally report the same ID as having different associated
+  // tool types across different events, which breaks Flutter's internal handling of pointer events.
+  // Instead give each (pointerId, toolType) pair a unique ID. Technically this could break when
+  // handling a pointer of id 2^29, but that seems unlikely. Flutter's internal handling uses a
+  // long, so it can be fixed if needed.
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java]:
```suggestion
  // long, so we can convert this method to return a long if needed.
```

**Review by reidbaker — DISMISSED** [review]
johnmccutchan added logic so that when we sent a device motion event back to android we returned the event that flutter got and not a synthetic event. I would expect that this unique pointer logic to be used in code that sends android events back to android. This change appears to only affect ingestion. 

That makes me think that somewhere else in the embedder we are relying on the device id to be the same and this will cause a silent failure. 
https://github.com/flutter/flutter/pull/171240/files#r2170067881

**Comment by gmackall** [comment]
> johnmccutchan added logic so that when we sent a device motion event back to android we returned the event that flutter got and not a synthetic event. I would expect that this unique pointer logic to be used in code that sends android events back to android. This change appears to only affect ingestion.
> 
> That makes me think that somewhere else in the embedder we are relying on the device id to be the same and this will cause a silent failure. https://github.com/flutter/flutter/pull/171240/files#r2170067881

I had this thought, but I also tested platform view input with multiple different input types and found that it worked without issue. I can go verify why this is if you prefer, but it does work

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java (hunk 2 above)
Comment (gmackall) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java:293]: I think there are 6 types, no? 

From https://developer.android.com/reference/android/view/MotionEvent#getToolType(int)

> The tool type of the pointer. Value is [TOOL_TYPE_UNKNOWN](https://developer.android.com/reference/android/view/MotionEvent#TOOL_TYPE_UNKNOWN), [TOOL_TYPE_FINGER](https://developer.android.com/reference/android/view/MotionEvent#TOOL_TYPE_FINGER), [TOOL_TYPE_STYLUS](https://developer.android.com/reference/android/view/MotionEvent#TOOL_TYPE_STYLUS), [TOOL_TYPE_MOUSE](https://developer.android.com/reference/android/view/MotionEvent#TOOL_TYPE_MOUSE), [TOOL_TYPE_ERASER](https://developer.android.com/reference/android/view/MotionEvent#TOOL_TYPE_ERASER), or android.view.MotionEvent.TOOL_TYPE_PALM

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java (hunk 3 above)
Comment (gmackall) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java:290]: added

**Comment by gmackall** [comment]
> > johnmccutchan added logic so that when we sent a device motion event back to android we returned the event that flutter got and not a synthetic event. I would expect that this unique pointer logic to be used in code that sends android events back to android. This change appears to only affect ingestion.
> > That makes me think that somewhere else in the embedder we are relying on the device id to be the same and this will cause a silent failure. https://github.com/flutter/flutter/pull/171240/files#r2170067881
> 
> I had this thought, but I also tested platform view input with multiple different input types and found that it worked without issue. I can go verify why this is if you prefer, but it does work

I've also verified that the input verification status remains unchanged.

**Comment by reidbaker** [comment]
> > > johnmccutchan added logic so that when we sent a device motion event back to android we returned the event that flutter got and not a synthetic event. I would expect that this unique pointer logic to be used in code that sends android events back to android. This change appears to only affect ingestion.
> > > That makes me think that somewhere else in the embedder we are relying on the device id to be the same and this will cause a silent failure. https://github.com/flutter/flutter/pull/171240/files#r2170067881
> > 
> > 
> > I had this thought, but I also tested platform view input with multiple different input types and found that it worked without issue. I can go verify why this is if you prefer, but it does work
> 
> I've also verified that the input verification status remains unchanged.

ok if manual testing looks good then this work for me.

**Review by reidbaker — APPROVED** [review]
