### PR TITLE
[a11y] Make sure RenderFractionalTranslation updates its semantics after the translation field is set

### LINKED ISSUE #20449: Semantic boxes are incorrect inside FractionalTranslation
`showCupertinoModalPopup()` uses a `FractionalTranslation` to slide a popup from offscreen into place. The semantic boxes for the popup are drawn while the popup is offscreen, and not updated once the popup is in its final position. Semantic boxes need to be updated once the animation is complete.

To reproduce, build a `CupertinoActionSheet` and show with `showCupertinoModalPopup()` in accessibility mode. Semantic boxes will not be in place when the action sheet is onscreen.

### PR DESCRIPTION
**Pull request by clocksmith**
## Description

This PR ensures that RenderFractionalTranslation calls markNeedsSemanticsUpdate after its translation is set/changed, so that semantics are properly updated (for instance if a FractionalTranslation is animating).

## Related Issues

closes https://github.com/flutter/flutter/issues/20449

## Tests

I added the following tests:

* added test in proxy_box_test.dart to make sure that markNeedsSemanticsUpdate is called when changing the translation value.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/rendering/proxy_box_test.dart [hunk 1]
```diff
@@ -510,3 +522,18 @@ class _TestPathClipper extends CustomClipper<Path> {
...
+  }) : super(translation: translation, child: child);
+
+  int markNeedsSemanticsUpdateCallCount = 0;
+
+  @override
+  void markNeedsSemanticsUpdate() {
+    markNeedsSemanticsUpdateCallCount++;
+    super.markNeedsSemanticsUpdate();
+  }
+}
```
Comment (rami-a) [inline packages/flutter/test/rendering/proxy_box_test.dart]: Missing new line at EOF

File: packages/flutter/test/rendering/proxy_box_test.dart [hunk 2]
```diff
@@ -510,3 +522,18 @@ class _TestPathClipper extends CustomClipper<Path> {
   @override
   bool shouldReclip(_TestPathClipper oldClipper) => false;
 }
+
+class _TestMarkNeedsSemanticsUpdateCountingRenderFractionalTranslation extends RenderFractionalTranslation {
```
Comment (rami-a) [inline packages/flutter/test/rendering/proxy_box_test.dart]: Maybe rename to `_TestSemanticsUpdateRenderFractionalTranslation` for brevity?

**Review by rami-a — APPROVED** [review]

File: packages/flutter/test/rendering/proxy_box_test.dart (hunk 2 above)
Comment (clocksmith) [reply packages/flutter/test/rendering/proxy_box_test.dart]: Done

File: packages/flutter/test/rendering/proxy_box_test.dart (hunk 1 above)
Comment (clocksmith) [reply packages/flutter/test/rendering/proxy_box_test.dart]: Done

File: packages/flutter/test/rendering/proxy_box_test.dart [hunk 3]
```diff
@@ -454,6 +454,18 @@ void main() {
     // transform -> clip
     _testFittedBoxWithClipRectLayer();
   });
+
+  test('RenderFractionalTranslation updates its semantics after its translation value is set', () {
```
Comment (goderbauer) [inline packages/flutter/test/rendering/proxy_box_test.dart]: Might be worthwhile to also add an actual semantics test to the FractionalTranslation widget that verifies that the generated semantics actually changed as expected when the translation is changed.

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/rendering/proxy_box_test.dart (hunk 3 above)
Comment (clocksmith) [reply packages/flutter/test/rendering/proxy_box_test.dart]: I am having trouble writing such a test. I have:

```
    testWidgets('semantics bounds are updated', (WidgetTester tester) async {
      final GlobalKey fractionalTranslationKey = GlobalKey();
      final GlobalKey sizedBoxKey = GlobalKey();
      Offset offset = const Offset(0.4, 0.4);

      await tester.pumpWidget(
        StatefulBuilder(
          builder: (BuildContext context, StateSetter setState) {
            return Center(
              child: FractionalTranslation(
                key: fractionalTranslationKey,
                translation: offset,
                transformHitTests: true,
                child: Listener(
                  onPointerDown: (PointerDownEvent event) {
                    setState(() {
                      offset = const Offset(0.8, 0.8);
                    });
                  },
                  child: SizedBox(
                    key: sizedBoxKey,
                    width: 100.0,
                    height: 100.0,
                    child: Container(
                      color: const Color(0xFF0000FF)
                    ),
                  ),
                ),
              ),
            );
          },
        )
      );
      expect(tester.getSemantics(find.byKey(fractionalTranslationKey)), matchesSemantics(
        size: const Size(40, 40),
      ));
```

which fails with:

```
The following TestFailure object was thrown running a test:
  Expected: has semantics with actions: [] with flags: [] with rect: Rect.fromLTRB(0.0, 0.0, 0.0,
0.0)
  Actual: SemanticsNode:<SemanticsNode#0(Rect.fromLTRB(0.0, 0.0, 2400.0, 1800.0))>
   Which: rect was: Rect.fromLTRB(0.0, 0.0, 2400.0, 1800.0)
```

No matter what the translation is set to, the bounds are always (0.0, 0.0, 2400.0, 1800.0) for both the FractionalTranslation and the SizedBox inside

Comment (goderbauer) [reply packages/flutter/test/rendering/proxy_box_test.dart]: After the pump can you call `debugDumpSemanticsTree` and post the output? That would make it easier to debug this.

My guess is that the the semantics of the FractionalTranslation get pulled up all the way into the root node and that's why you're seeing this. If you throw in a `Semantics(explicitChildNodes: true, child: ...)` around the FractionalTranslation or the Center widget it may work. Looking at the semantics tree dump would tell us for sure.

Comment (clocksmith) [reply packages/flutter/test/rendering/proxy_box_test.dart]: output of `debugDumpSemanticsTree` is the same with or without the `Semantics(explicitChildNodes: true)` wrapper:

```
SemanticsNode#0
   Rect.fromLTRB(0.0, 0.0, 2400.0, 1800.0)
```

Comment (goderbauer) [reply packages/flutter/test/rendering/proxy_box_test.dart]: That's the only node that gets created? 

Oh, it's probably because no child of FractionalTranslation has any real semantics to contribute. Try giving the container a `Text('foo')` child.

Comment (clocksmith) [reply packages/flutter/test/rendering/proxy_box_test.dart]:
```
SemanticsNode#0
 │ Rect.fromLTRB(0.0, 0.0, 2400.0, 1800.0)
 │
 └─SemanticsNode#1
     Rect.fromLTRB(0.0, 0.0, 100.0, 100.0) with transform
     [3.0,0.0,0.0,1170.0; 0.0,3.0,0.0,870.0; 0.0,0.0,1.0,0.0;
     0.0,0.0,0.0,1.0]
     label: "foo"
     textDirection: ltr
```

File: packages/flutter/test/widgets/basic_test.dart [hunk 4]
```diff
@@ -145,6 +145,71 @@ void main() {
...
+                  ),
+                ),
+              ),
+            );
+          },
+        )
+      );
+
+      await tester.pump();
+      debugDumpSemanticsTree(DebugSemanticsDumpOrder.traversalOrder);
```
Comment (goderbauer) [inline packages/flutter/test/widgets/basic_test.dart]: remove this dump?

File: packages/flutter/test/widgets/basic_test.dart [hunk 5]
```diff
@@ -145,6 +145,71 @@ void main() {
...
+            return Directionality(
+              textDirection: TextDirection.ltr,
+              child: Center(
+                child: Semantics(
+                  explicitChildNodes: true,
+                  child: FractionalTranslation(
+                    key: fractionalTranslationKey,
+                    translation: offset,
+                    transformHitTests: true,
+                    child: Listener(
```
Comment (goderbauer) [inline packages/flutter/test/widgets/basic_test.dart]: Use a regular GestureDetector.onTap here instead of the low-level Listener?

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/test/widgets/basic_test.dart (hunk 5 above)
Comment (clocksmith) [reply packages/flutter/test/widgets/basic_test.dart]: Done

File: packages/flutter/test/widgets/basic_test.dart (hunk 4 above)
Comment (clocksmith) [reply packages/flutter/test/widgets/basic_test.dart]: Done

**Comment by dnfield** [comment]
9322d77 somehow pulled in a bunch of things I think this PR didn't mean to.  I think we should revert this whole thing and then reland the actual change that was desired here.
