### PR TITLE
Makes badge to auto size with content

### LINKED ISSUE #146777: [A11y][Android] Badge bubble does not scale with text font size
b/317118086
### Steps to reproduce

1. Run https://github.com/flutter/flutter/tree/master/dev/a11y_assessments
2. In the list press badge
3. go to setting -> accessibility -> font size, and increase font size
4. The text in the bubble increase in size, but not the bubble it self
image

### Actual results

The bubble should also increase in size

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
Makes badge sizes it self according to child.

Previously, the bubble fixed its height to 16pixel. It clip the content if it is taller than 16 pixel. This causes an issue where user can increase font size in the android setting and mess up the ui

Now, the bubble can have various height from 16 pixel to the height of the child, it also extend the width to be the same as height if the child's width < height.

There is minor changes to floating location  in the test. I can't really fix them unless I change some of the public API like `Badge(offset)` or `BadgeThemeData.largeSize`. They are used differently in the new logic since now the badge can be larger than the Badge.child. I figure they are kind of minor so i think it should be ok

Before the fix
image

After the fix
image

fixes https://github.com/flutter/flutter/issues/146777

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter/lib/src/material/badge.dart [hunk 1]
```diff
@@ -275,7 +323,104 @@ class _RenderBadge extends RenderAligningShiftedBox {
     final double badgeSize = child!.size.height;
     final Alignment resolvedAlignment = alignment.resolve(textDirection);
     final BoxParentData childParentData = child!.parentData! as BoxParentData;
-    childParentData.offset = offset + resolvedAlignment.alongOffset(Offset(size.width - badgeSize, size.height - badgeSize));
+    Offset badgeLocation = offset + resolvedAlignment.alongOffset(Offset(size.width - widthOffset, size.height));
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/badge.dart:326]: Just a question here, the logic here and the change on `defaultOffset` seem cause some breaking changes on vertical location. Do you think if it would make sense to keep the logic here so that only the size of the badge is fixed and location won't change?

File: packages/flutter/lib/src/material/badge.dart [hunk 2]
```diff
@@ -190,7 +204,10 @@ class Badge extends StatelessWidget {
     final AlignmentGeometry effectiveAlignment = alignment ?? badgeTheme.alignment ?? defaults.alignment!;
     final TextDirection textDirection = Directionality.of(context);
     final Offset defaultOffset = textDirection == TextDirection.ltr ? const Offset(4, -4) : const Offset(-4, -4);
-    final Offset effectiveOffset = offset ?? badgeTheme.offset ?? defaultOffset;
+    // Adds a offset const Offset(0, 8) to avoiding breaking customers after
+    // the offset calculation changes.
+    // See https://github.com/flutter/flutter/pull/146853.
+    final Offset effectiveOffset = (offset ?? badgeTheme.offset ?? defaultOffset) + const Offset(0, 8);
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/badge.dart:210]: @QuncCccccc This is the best way I can think of to cause least breaking for people who uses Badge(offset).

The customer that have a big jump in icon
https://fusion2.corp.google.com/presubmit/625484245/OCL:625484245:BASE:625495583:1713311589857:35f5826b/targets/invocations/a540f325-e68b-49cd-bce2-dc65254fb25d/targets/%2F%2Fanalytics%2Fmobile%2Fgiant%2Fui%2Fscreens:screens_tests_test_intelligent_home_screen_scuba_test.host/tests
is because they have a child which is too big in size so it uses offset to align the badge.

Adding this constant will make sure the offset they passed adjust the badge the same way.

**Review by QuncCccccc — APPROVED** [review]
LGTM:)
