### PR TITLE
Fix screenshot testing for flutter web integration_test

### LINKED ISSUE #117077: package:integration_test screenshot testing is broken for flutter web
In this example test here, https://github.com/flutter/flutter/blob/master/packages/integration_test/example/test_driver/extended_integration_test.dart, we should include a real example of image comparison (particularly for flutter web). I am trying to implement this method for DevTools flutter web integration tests and there appear to be some rough edges with the integration test package.

For example, even when this method returns true the following exception is thrown:
```
 result {"result":"true","failureDetails":[],"data":{"screenshots":[{"bytes":[]}]}}
 Unhandled exception:
 type 'Null' is not a subtype of type 'String' in type cast
 #0      integrationDriver (package:integration_test/integration_test_driver_extended.dart:103:60)
 <asynchronous suspension>
 #1      main (file:///Users/kenzieschmoll/develop/devtools/packages/devtools_app/test_driver/integration_test.dart:9:3)
 <asynchronous suspension>
```

@yjbanov

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Fixes https://github.com/flutter/flutter/issues/117077.

A complete example of screenshot testing still needs to be provided. This is better to be done once the screenshot testing workflow for integration tests is better thought out for web. Issue tracked at https://github.com/flutter/flutter/issues/86120.

### CODE REVIEW

**Comment by kenzieschmoll** [comment]
@yjbanov @Piinks This is ready for review. Please let me know what needs to be changed, and Kate, Yegor mentioned you might be able to help me move this PR over to using Skia Gold instead of the manual .png storage I have done here. Eager to get the changes to package:integration_test landed so we can use them in DevTools 👍  Thanks!

**Comment by Piinks** [comment]
> Yegor mentioned you might be able to help me move this PR over to using Skia Gold

Yeah, we can't check image files into this repo. Unfortunately, I can't set up integration tests to send images to Gold right now. 

Someone did wire them up for tests in exmaples/api though, you may be able to use #99298 as a guide. :)

**Comment by kenzieschmoll** [comment]
@Piinks do you know of any usages of flutter_goldens in integration tests?

**Comment by kenzieschmoll** [comment]
I followed the pattern in https://github.com/flutter/flutter/pull/99298 and added this to the test:
```dart
    await expectLater(
      find.byType(MaterialApp),
      matchesGoldenFile('platform_name.png'),
    );
```

When running the test:
`flutter drive --driver=test_driver/extended_integration_test.dart --target=integration_test/extended_test.dart -d chrome`

this is what was output:
`Golden comparison requested for "platform_name.png"; skipping...`

File: packages/integration_test/example/test_driver/extended_integration_test.dart [hunk 1]
```diff
@@ -2,15 +2,60 @@
...
   await integrationDriver(
     driver: driver,
-    onScreenshot: (String screenshotName, List<int> screenshotBytes) async {
-      // Return false if the screenshot is invalid.
+    onScreenshot: (
+      String screenshotName,
+      List<int> screenshotBytes, [
+      Map<String, Object?>? args,
+    ]) async {
+      // Here is an example of what updating a golden image might look like.
```
Comment (kenzieschmoll) [inline packages/integration_test/example/test_driver/extended_integration_test.dart:21]: @yjbanov @Piinks would it be acceptable to land this PR with the provided example in comments so that .png's are never added to this example? This still give some guidance or inspiration into how someone could hook up golden image testing if they weren't able to use Skia Gold.

Comment (kenzieschmoll) [reply packages/integration_test/example/test_driver/extended_integration_test.dart:21]: Optionally, I can also remove this example and just leave the changes in this PR that are outside the `example/` directory. We will do something like this for DevTools, since it looks like Skia Gold has not been hooked up yet for web integration tests (https://github.com/flutter/flutter/issues/86120). I'd like to unblock screenshot testing in integration tests for DevTools (even without skia gold support), so let me know what you think. Thanks.

**Comment by Piinks** [comment]
> I followed the pattern in #99298 and added this to the test:
> 
> ```dart
>     await expectLater(
>       find.byType(MaterialApp),
>       matchesGoldenFile('platform_name.png'),
>     );
> ```
> 
> When running the test: `flutter drive --driver=test_driver/extended_integration_test.dart --target=integration_test/extended_test.dart -d chrome`
> 
> this is what was output: `Golden comparison requested for "platform_name.png"; skipping...`

Did you push those changes? It won't work locally, it needs to be authenticated in CI.

**Comment by kenzieschmoll** [comment]
> Did you push those changes? It won't work locally, it needs to be authenticated in CI.

Ah okay. Pushed them up now, so we'll see if it worked 👍

**Comment by yjbanov** [comment]
I'm not sure if `flutter_goldens` will work on the web. `flutter test` sets up a local server that knows how to take screenshots and compare them. I'm not aware of `flutter drive` or `package:integration_test` attempting to do that. `package:integration_test` wants us to perform the comparison in the `onScreenshot` callback, which is not part of the test code. We may need to look for something we can use in the callback. My first intuition was to use `SkiaClient` directly.

Alternatively, we can keep it simple for now and instead of integrating with Skia Gold, use [package:image](https://pub.dev/packages/image) to decode the PNG and spot check a few pixels.

**Comment by kenzieschmoll** [comment]
> Alternatively, we can keep it simple for now and instead of integrating with Skia Gold, use [package:image](https://pub.dev/packages/image) to decode the PNG and spot check a few pixels.

Isn't the problem that we can't check PNGs into the codebase? how would we be able to use package:image to compare images without checking goldens in?

**Comment by yjbanov** [comment]
> Isn't the problem that we can't check PNGs into the codebase? how would we be able to use package:image to compare images without checking goldens in?

Sorry, by "PNG" I meant the screenshot that the test takes and passes to the `onScreenshot` callback as `screenshotBytes`. The callback could parse the screenshot image and check a few known pixels in it.

**Comment by kenzieschmoll** [comment]
> The callback could parse the screenshot image and check a few known pixels in it.

How would we get the "known" pixels? This sounds a bit hand wavy. Would we expect the average flutter developer to know how to parse out image "hot spots" from byte code and store those as constants to compare the new `screenshotBytes` to? Whatever is here in this example is likely the resource that users will look at to figure out how to add screenshot testing through package:integration_test to their app.

Could we possibly separate this PR into two tasks:
1. land the changes to `packages/integration_test/lib` (which un-breaks screenshot testing for flutter web and makes the `onScreenshot` handler more flexible)
2. Add an up to date example to the `onScreenshot` callback in `examples/` on how to actually do the image comparison? It may make more sense to do this once a formal support for `flutter_goldens` on the web or some other recommended way is decided upon. For projects that are not Flutter, keeping .pngs in a repo and comparing the bytes may be a fine solution. Please see my question here: https://github.com/flutter/flutter/pull/117114#discussion_r1051000311. 

I would like to shift this PR to address task 1 and leave task 2 for a later day when this user journey is better addressed.

**Comment by kenzieschmoll** [comment]
https://github.com/flutter/flutter/pull/117496 contains the same changes to `dev/test.dart` that this PR does - the changes to add the formerly failing tests to Linux_web_long_running_tests on the CI. https://github.com/flutter/flutter/pull/117496 demonstrates that these tests are failing at master, but passing in this PR after the changes contained here.

File: packages/integration_test/lib/common.dart [hunk 2]
```diff
@@ -7,17 +7,23 @@ import 'dart:convert';
 
 /// A callback to use with [integrationDriver].
 ///
-/// The callback receives the name of screenshot passed to `binding.takeScreenshot(<name>)` and
-/// a PNG byte buffer.
+/// The callback receives the name of screenshot passed to `binding.takeScreenshot(<name>)`,
+/// a PNG byte buffer representing the screenshot, and an optional Map of arguments.
```
Comment (yjbanov) [inline packages/integration_test/lib/common.dart:11]: nit: consider using backticks for ``` `Map` ```, or just say "map" (with a small "m").

File: packages/integration_test/lib/common.dart [hunk 3]
```diff
@@ -7,17 +7,23 @@ import 'dart:convert';
...
 ///
 /// The callback returns `true` if the test passes or `false` otherwise.
 ///
 /// You can use this callback to store the bytes locally in a file or upload them to a service
 /// that compares the image against a gold or baseline version.
 ///
+/// The optional Map of arguments can be passed from the
```
Comment (yjbanov) [inline packages/integration_test/lib/common.dart:18]: ditto: ``` `Map` ```

File: packages/integration_test/lib/common.dart [hunk 4]
```diff
@@ -7,17 +7,23 @@ import 'dart:convert';
...
+/// `binding.takeScreenshot(<name>, <args>)` callsite in the integration test,
+/// and then the arguments can be used in the `onScreenshot` handler that is defined by
+/// the Flutter driver. This Map should contain primitive types that are able to
+/// be serialized from the browser to the Flutter driver.
```
Comment (yjbanov) [inline packages/integration_test/lib/common.dart:22]: Still not clear what values are supported. I believe we're using JSON (it's run through `Response.toJson`), so I think it's safe to say that `args` only supports values that can be serialized to JSON.

**Review by yjbanov — APPROVED** [review]
lgtm
