### PR TITLE
Default --no-tree-shake-icons to false for 'flutter build bundle'

### LINKED ISSUE #81954: "flutter build bundle --release" fails with `IconTreeShakerException`
## Steps to Reproduce

Note that this fails for flutter build bundle --profile  too. Attempting to build bundles in release or profile modes also fail on a mac.

1. flutter create flutter_counter
2. cd flutter_counter
3. flutter build bundle --verbose --release

## Logs

<details>
<summary>Logs</summary>

20:25 $ flutter create flutter_counter
Creating project flutter_counter...
  flutter_counter/.idea/modules.xml (created)
  flutter_counter/.idea/runConfigurations/main_dart.xml (created)
  flutter_counter/.idea/workspace.xml (created)
  flutter_counter/.idea/libraries/Dart_SDK.xml (created)
  flutter_counter/.idea/libraries/KotlinJavaRuntime.xml (created)
  flutter_counter/linux/main.cc (created)
  flutter_counter/linux/my_application.cc (created)
  flutter_counter/linux/CMakeLists.txt (created)
  flutter_counter/linux/.gitignore (created)
  flutter_counter/linux/my_application.h (created)
  flutter_counter/linux/flutter/CMakeLists.txt (created)
  flutter_counter/flutter_counter.iml (created)
  flutter_counter/lib/main.dart (created)
  flutter_counter/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  flutter_counter/ios/Runner.xcodeproj/project.pbxproj (created)
  flutter_counter/ios/Runner/AppDelegate.swift (created)
  flutter_counter/ios/Runner/Runner-Bridging-Header.h (created)
  flutter_counter/pubspec.yaml (created)
  flutter_counter/android/gradle/wrapper/gradle-wrapper.properties (created)
  flutter_counter/android/.gitignore (created)
  flutter_counter/android/gradle.properties (created)
  flutter_counter/android/settings.gradle (created)
  flutter_counter/android/app/src/profile/AndroidManifest.xml (created)
  flutter_counter/android/app/src/debug/AndroidManifest.xml (created)
  flutter_counter/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  flutter_counter/android/app/src/main/res/values/styles.xml (created)
  flutter_counter/android/app/src/main/res/drawable/launch_background.xml (created)
  flutter_counter/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  flutter_counter/android/app/src/main/res/values-night/styles.xml (created)
  flutter_counter/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  flutter_counter/android/app/src/main/res/drawable-v21/launch_background.xml (created)
  flutter_counter/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  flutter_counter/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  flutter_counter/android/app/src/main/AndroidManifest.xml (created)
  flutter_counter/android/build.gradle (created)
  flutter_counter/android/flutter_counter_android.iml (created)
  flutter_counter/android/app/src/main/kotlin/com/example/flutter_counter/MainActivity.kt (created)
  flutter_counter/android/app/build.gradle (created)
  flutter_counter/README.md (created)
  flutter_counter/.metadata (created)
  flutter_counter/test/widget_test.dart (created)
  flutter_counter/.gitignore (created)
  flutter_counter/web/icons/Icon-192.png (created)
  flutter_counter/web/icons/Icon-512.png (created)
  flutter_counter/web/manifest.json (created)
  flutter_counter/web/index.html (created)
  flutter_counter/web/favicon.png (created)
  flutter_counter/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  flutter_counter/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  flutter_counter/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  flutter_counter/ios/.gitignore (created)
  flutter_counter/ios/Flutter/AppFrameworkInfo.plist (created)
  flutter_counter/ios/Flutter/Release.xcconfig (created)
  flutter_counter/ios/Flutter/Debug.xcconfig (created)
  flutter_counter/ios/Runner/Info.plist (created)
  flutter_counter/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  flutter_counter/ios/Runner/Base.lproj/Main.storyboard (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  flutter_counter/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  flutter_counter/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  flutter_counter/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  flutter_counter/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  flutter_counter/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  flutter_counter/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
Running "flutter pub get" in flutter_counter...                  1,501ms
Wrote 84 files.

All done!
In order to run your application, type:

  $ cd flutter_counter
  $ flutter run

To enable null safety, type:

  $ cd flutter_counter
  $ dart migrate --apply-changes

Your application code is in flutter_counter/lib/main.dart.

✔ ~/src 
20:25 $ cd flutter_counter
✔ ~/src/flutter_counter 
20:26 $ flutter build bundle --verbose --release
[  +62 ms] executing: [/home/kkiyohara/src/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] executing: [/home/kkiyohara/src/flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[  +11 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[  +32 ms] executing: [/home/kkiyohara/src/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/kkiyohara/src/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +33 ms] executing: [/home/kkiyohara/src/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +44 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +36 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +51 ms] Skipping pub get: version match.
[ +100 ms] Generating /home/kkiyohara/src/flutter_counter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +60 ms] 💪 Building with sound null safety 💪
[   +7 ms] Initializing file store
[   +6 ms] release_flutter_bundle: Starting due to {}
[  +97 ms] Persisting file store
[   +1 ms] Done persisting file store
[   +3 ms] Target release_flutter_bundle failed: IconTreeShakerException: Expected to find kernel file at
/home/kkiyohara/src/flutter_counter/.dart_tool/flutter_build/303cf5f7e09bb2a84a7f5b70bcf010f9/app.dill,
           but no file found.
           
           To disable icon tree shaking, pass --no-tree-shake-icons to the requested flutter build command
[  +10 ms] "flutter bundle" took 391ms.
[   +2 ms] Failed to build bundle.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildWithAssemble (package:flutter_tools/src/bundle.dart:175:5)
           <asynchronous suspension>
           #2      BundleBuilder.build (package:flutter_tools/src/bundle.dart:102:5)
           <asynchronous suspension>
           #3      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:102:5)
           <asynchronous suspension>
           #4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #14     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #16     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #17     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #18     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +255 ms] ensureAnalyticsSent: 253ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
✘-1 ~/src/flutter_counter 
20:26 $ flutter build bundle --verbose --release --no-tree-shake-icons
[  +54 ms] executing: [/home/kkiyohara/src/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +24 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] executing: [/home/kkiyohara/src/flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[  +11 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[  +28 ms] executing: [/home/kkiyohara/src/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/kkiyohara/src/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +28 ms] executing: [/home/kkiyohara/src/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +39 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +31 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +44 ms] Skipping pub get: version match.
[  +88 ms] Generating /home/kkiyohara/src/flutter_counter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +43 ms] 💪 Building with sound null safety 💪
[   +6 ms] Initializing file store
[   +6 ms] release_flutter_bundle: Starting due to {}
[  +71 ms] release_flutter_bundle: Complete
[  +35 ms] Persisting file store
[   +1 ms] Done persisting file store
[   +8 ms] "flutter bundle" took 354ms.
[ +255 ms] ensureAnalyticsSent: 252ms
[   +4 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
✔ ~/src/flutter_counter 
20:28 $ ls build/
flutter_assets/      snapshot_blob.bin.d  
✔ ~/src/flutter_counter 
20:28 $ ls build/flutter_assets/
AssetManifest.json  FontManifest.json   fonts/              .last_build_id      NOTICES             packages/         
✔ ~/src/flutter_counter 
20:28 $
✘-INT ~/src/flutter_counter 

### Note that debug builds succeed.

20:30 $ flutter build bundle --verbose --debug
[  +55 ms] executing: [/home/kkiyohara/src/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +24 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] executing: [/home/kkiyohara/src/flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[  +11 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[  +28 ms] executing: [/home/kkiyohara/src/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/kkiyohara/src/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +29 ms] executing: [/home/kkiyohara/src/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +40 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +36 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +37 ms] Skipping pub get: version match.
[  +90 ms] Generating /home/kkiyohara/src/flutter_counter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +45 ms] 💪 Building with sound null safety 💪
[   +6 ms] Initializing file store
[   +9 ms] Skipping target: gen_localizations
[   +4 ms] kernel_snapshot: Starting due to {}
[   +7 ms] /home/kkiyohara/src/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/kkiyohara/src/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/kkiyohara/src/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --no-link-platform --packages /home/kkiyohara/src/flutter_counter/.dart_tool/package_config.json --output-dill
/home/kkiyohara/src/flutter_counter/.dart_tool/flutter_build/69ed6f97b36248922b461cd3c8a35496/app.dill --depfile
/home/kkiyohara/src/flutter_counter/.dart_tool/flutter_build/69ed6f97b36248922b461cd3c8a35496/kernel_snapshot.d package:flutter_counter/main.dart
[+5994 ms] kernel_snapshot: Complete
[ +334 ms] copy_flutter_bundle: Starting due to {}
[  +79 ms] copy_flutter_bundle: Complete
[ +429 ms] Persisting file store
[   +3 ms] Done persisting file store
[  +10 ms] "flutter bundle" took 7,106ms.
[  +73 ms] ensureAnalyticsSent: 70ms
[   +4 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0
✔ ~/src/flutter_counter 
20:31 $ ls  build/flutter_assets/
AssetManifest.json  FontManifest.json  fonts  isolate_snapshot_data  kernel_blob.bin  NOTICES  packages  vm_snapshot_data
✔ ~/src/flutter_counter 

20:25 $ flutter doctor --verbose
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.6 at /home/kkiyohara/src/flutter
    • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/kkiyohara/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /home/kkiyohara/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.7142.45
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.

</details>

### PR DESCRIPTION
**Pull request by jmagman**
`flutter build bundle` should never have supported `--no-tree-shake-icons` since it doesn't generate a dill, just the assets, and so there's nothing for the icon tree shaker to run on.

"Disable" `flutter build bundle --tree-shake-icons` by hiding the flag and defaulting to false, and tool exiting if `--tree-shake-icons` is explicitly passed.  Do not remove the flag in order to support any `--no-tree-shake-icons` workarounds being used in the wild.

Fixes https://github.com/flutter/flutter/issues/81954

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/build_bundle.dart [hunk 1]
```diff
@@ -81,6 +87,14 @@ class BuildBundleCommand extends BuildSubCommand {
     };
   }
 
+  @override
+  Future<void> validateCommand() async {
+    if (argResults['tree-shake-icons'] as bool) {
+      throwToolExit('The "--tree-shake-icons" flag is deprecated and will be removed in a future version of Flutter.');
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/commands/build_bundle.dart:93]:
```suggestion
      throwToolExit('The "--tree-shake-icons" flag is deprecated for "build bundle" and will be removed in a future version of Flutter.');
```

Just so people don't think we're removing it elsewhere

**Review by jonahwilliams — APPROVED** [review]
LGTM with nit
