### PR TITLE
Fix DropdownButton crash when viewport size is too small for the entirety of the menu's height

### LINKED ISSUE #76614: Crash in dropdownmenupainter
Reported internally as b/180079090. 

The stack trace is:
```
at _Double.clamp (double.dart:209 )
at _DropdownMenuPainter.paint (dropdown.dart:68 )
at RenderCustomPaint._paintWithPainter (custom_paint.dart:536 )
at RenderCustomPaint.paint (custom_paint.dart:577 )
at RenderObject._paintWithContext (object.dart:2314 )
at PaintingContext.paintChild (object.dart:189 )
at RenderAnimatedOpacityMixin.paint (proxy_box.dart:1020 )
at RenderObject._paintWithContext (object.dart:2314 )
at PaintingContext.paintChild (object.dart:189 )
at RenderShiftedBox.paint (shifted_box.dart:72 )
at RenderObject._paintWithContext (object.dart:2314 )
at PaintingContext.paintChild (object.dart:189 )
at _RenderLayoutBuilder.paint (layout_builder.dart:384 )
at RenderObject._paintWithContext (object.dart:2314 )
at PaintingContext.paintChild (object.dart:189 )
at RenderProxyBoxMixin.paint (proxy_box.dart:144 )
at RenderObject._paintWithContext (object.dart:2314 )
at PaintingContext._repaintCompositedChild (object.dart:140 )
at  ( )
at RendererBinding.drawFrame (binding.dart:456 )
at WidgetsBinding.drawFrame (binding.dart:900 )
at RendererBinding._handlePersistentFrameCallback (binding.dart:320 )
at SchedulerBinding._invokeFrameCallback (binding.dart:1119 )
at SchedulerBinding.handleDrawFrame (binding.dart:1057 )
at SchedulerBinding._handleDrawFrame (binding.dart:973 )
at _rootRun (zone.dart:1186 )
at _CustomZone.run (zone.dart:1090 )
at _CustomZone.runGuarded (zone.dart:994 )
at _invoke (hooks.dart:157 )
at PlatformDispatcher._drawFrame (platform_dispatcher.dart:253 )
at _drawFrame (hooks.dart:120 )
```

Presumably, the bug is in this line:

https://github.com/flutter/flutter/blob/0a4618943c0360615c02443cecd95656eb2c7892/packages/flutter/lib/src/material/dropdown.dart#L68

When `size.height - _kMenuItemHeight` becomes negative, the `clamp` call throws. We need to guard against `size.height` being smaller than `_kMenuItemHeight`.

### PR DESCRIPTION
**Pull request by xu-baolin**
If a DropDown widget is used when the screen is very small, the drop-down widget will crash because the second argument to `selectedItemOffset.clamp(0.0, size.height - _kMenuItemHeight)` in _DropdownMenuPainter.paint is negative.

Fixes #76614

### CODE REVIEW

File: packages/flutter/test/material/dropdown_test.dart [hunk 1]
```diff
@@ -2949,4 +2949,57 @@ void main() {
...
     expect(find.byType(Scrollbar), paints..rect());
   });
+
+  // Regression test for https://github.com/flutter/flutter/issues/76614
+  testWidgets('Do not crash if used in very short screen', (WidgetTester tester) async {
+    const String value = 'foo';
+    final UniqueKey itemKey = UniqueKey();
+    await tester.pumpWidget(
+      Center(
+        child: SizedBox(
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_test.dart:2959]: I wonder if we should do something similar to https://stackoverflow.com/questions/53706569/how-to-test-flutter-widgets-on-different-screen-sizes, where we adjust the physical screen size and the device pixel ratio. Perhaps that would emulate a real-world scenario better?

File: packages/flutter/test/material/dropdown_test.dart [hunk 2]
```diff
@@ -2949,4 +2949,57 @@ void main() {
...
+        matching: find.byType(CustomPaint),
+      ).at(2),
+      paints
+        ..save()
+        ..rrect()
+        ..rrect()
+        ..rrect()
+        // The height of menu is 47.0.
+        ..rrect(rrect: const RRect.fromLTRBXY(0.0, 0.0, 112.0, 47.0, 2.0, 2.0), color: Colors.grey[50], hasMaskFilter: false)
+    );
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_test.dart:3003]: Does this just show that the menu is painted with a certain height?

File: packages/flutter/test/material/dropdown_test.dart [hunk 3]
```diff
@@ -2949,4 +2949,57 @@ void main() {
...
+
+    await tester.tap(find.text(value));
+    await tester.pumpAndSettle();
+
+    final List<RenderBox> itemBoxes = tester.renderObjectList<RenderBox>(find.byKey(itemKey)).toList();
+    expect(itemBoxes[0].localToGlobal(Offset.zero).dx, 0.0);
+    expect(itemBoxes[0].localToGlobal(Offset.zero).dy, 228.5);
+
+    expect(itemBoxes[1].localToGlobal(Offset.zero).dx, 16.0);
+    expect(itemBoxes[1].localToGlobal(Offset.zero).dy, 228.5);
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_test.dart:2989]: What does this section of the test verify?

File: packages/flutter/test/material/dropdown_test.dart [hunk 4]
```diff
@@ -2949,4 +2949,57 @@ void main() {
...
   });
+
+  // Regression test for https://github.com/flutter/flutter/issues/76614
+  testWidgets('Do not crash if used in very short screen', (WidgetTester tester) async {
+    const String value = 'foo';
+    final UniqueKey itemKey = UniqueKey();
+    await tester.pumpWidget(
+      Center(
+        child: SizedBox(
+          height: 48.0 * 3 - 1.0, // The height of menu is 47.0.
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_test.dart:2960]: We may want to specify why we use 3x - 1.0 (I know from working on a previous PR that we need two items padding since the menu requires empty space surrounding the menu, but people reading just this test by itself wouldn't)

**Review by shihaohong — COMMENTED** [review]
The fix itself looks good, just have some questions about the test

File: packages/flutter/test/material/dropdown_test.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/test/material/dropdown_test.dart:2959]: Nice!
I did not know this API before!

File: packages/flutter/test/material/dropdown_test.dart (hunk 3 above)
Comment (xu-baolin) [reply packages/flutter/test/material/dropdown_test.dart:2989]: Actually nothing special, in case someone changes the position by mistake at this screen size ：）

File: packages/flutter/test/material/dropdown_test.dart (hunk 2 above)
Comment (xu-baolin) [reply packages/flutter/test/material/dropdown_test.dart:3003]: Correct! And without crash like before.

File: packages/flutter/test/material/dropdown_test.dart [hunk 5]
```diff
@@ -3008,4 +3008,61 @@ void main() {
...
   });
+
+  // Regression test for https://github.com/flutter/flutter/issues/76614
+  testWidgets('Do not crash if used in very short screen', (WidgetTester tester) async {
+    // The default item height is 48.0 pixels and needs two items padding since
+    // the menu requires empty space surrounding the menu. Finally, the constraint height
+    // is 47.0 pixels for the menu rendering.
+    tester.binding.window.physicalSizeTestValue = const Size(800.0, 48.0 * 3 - 1.0);
+    tester.binding.window.devicePixelRatioTestValue = 1;
+    addTearDown(tester.binding.window.clearPhysicalSizeTestValue);
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_test.dart:3019]: Nice, I never knew this API existed as well :)

**Review by shihaohong — APPROVED** [review]
LGTM
