### PR TITLE
Restore velocity tracker sample window duration

### LINKED ISSUE #7477: Regression: Flings on iOS have too-high velocity
When I quick slide interface, why always bounce back?

### PR DESCRIPTION
**Pull request by HansMuller**
Pull request https://github.com/flutter/flutter/pull/7363 reduced the kHorizontalMilliseconds constant in velocity_tracker.dart from 100ms to 40ms. On Android, with yours truly as the swipe duration standard, that yielded about 5 sample events and reasonable velocity estimates. On iOS however the result was only 2 or 3 samples. This led to poor (albeit high confidence) velocity estimates.

Fixes #7477

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
My understanding is iOS only gives you one event per frame, you can grab the others though, as we've considered doing in https://github.com/flutter/flutter/issues/5361.

We should probably add a comment next to the 100ms to note such.

**Comment by HansMuller** [comment]
@eseidelGoogle  I've added a comment with a link to your note about coalescedTouchesForTouch (https://developer.apple.com/reference/uikit/uievent/1613808-coalescedtouchesfortouch).

**Comment by abarth** [comment]
LGTM

File: packages/flutter/lib/src/gestures/velocity_tracker.dart [hunk 1]
```diff
@@ -43,7 +43,14 @@ class _LeastSquaresVelocityTrackerStrategy extends _VelocityTrackerStrategy {
   int _index = 0;
 
   static const int kHistorySize = 20;
-  static const int kHorizonMilliseconds = 40;
+
+  // On iOS we're not necccessarily seeing all of the motion events. See:
+  // https://github.com/flutter/flutter/issues/4737#issuecomment-241076994
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/velocity_tracker.dart]: This comment may belong somewhere higher with a TODO, rather than next to this seemingly unrelated constant.

File: packages/flutter/lib/src/gestures/velocity_tracker.dart [hunk 2]
```diff
@@ -73,7 +81,9 @@ class _LeastSquaresVelocityTrackerStrategy extends _VelocityTrackerStrategy {
         break;
 
       double age = (newestMovement.eventTime - movement.eventTime).inMilliseconds.toDouble();
-      if (age > kHorizonMilliseconds)
+      double delta = (movement.eventTime - previousMovement.eventTime).inMilliseconds.toDouble();
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/velocity_tracker.dart]: won't this always result in a negative number?

**Comment by Hixie** [comment]
This needs a test. In particular, the test should verify that if there's a 40ms gap between pointer events, the previous events are ignored. For example, have a series of ten events 10ms apart that are moving fast, and then a 40ms gap, and then one more event that is in the place that it would have been if there had been a continuance of that velocity in that 40ms, and check that the velocity is then zero.
