### PR TITLE
fix initial routes do not run secondary animation when pops

### LINKED ISSUE #46000: Navigator: initial route and secondary animation
When multiple routes are added to the navigator via the `initialRoute` property, it seems like the secondary animation of those routes is not playing correctly when a route is popped off the navigator.

/cc @chunhtai

### PR DESCRIPTION
**Pull request by chunhtai**
## Description

Whenever a new route pushed on top of another route, it will chains the secondary animation of bottom route with the primary animation of top route. However, there is a bug in the method that chain them together. In the method, we try to do train hopping if the two animations does not have the same values. It is possible that the two animations are animating with different directions and the hopping will never happen, and that introduce this bug.

here are the steps, assume initial route is routeA/routeB
1, routeA pushed with pri-animation=1.0, sec-animation=0.0
2, routeB pushed with pri-animation=1.0, and it try to do train hopping on sec-animation of routeA which never happen. The sec-animation of routeA stay at 0.0
3, when routeB pop, the routeA didpopnext will try to do the train hopping again with sec-animation of routeA = 0.0 and pri-animation of routeB =1.0 in reverse order. This is wrong because the sec-animation of routeA should be 1.0 at this moment and animate with pri-animation of routeB.

## Related Issues

Closes https://github.com/flutter/flutter/issues/46000
## Tests

I added the following tests:
"secondary animation is triggered when pop initial route"

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/widgets/routes_test.dart [hunk 1]
```diff
@@ -780,13 +780,46 @@ void main() {
       // Pop page three while replacement push is ongoing.
       navigator.currentState.pop();
       await tester.pump();
-      expect(secondaryAnimationPageOne.parent, isA<TrainHoppingAnimation>());
-      final TrainHoppingAnimation trainHopper2 = secondaryAnimationPageOne.parent as TrainHoppingAnimation;
-      expect(trainHopper2.currentTrain, animationPageTwo.parent);
-      expect(trainHopper.currentTrain, isNull); // Has been disposed.
+      // It should jump to the other train because train hopping will never
+      // happen
+      expect(secondaryAnimationPageOne.parent, isA<CurvedAnimation>());
```
Comment (chunhtai) [inline packages/flutter/test/widgets/routes_test.dart]: @goderbauer you wrote this test. However, something is unclear what the expected behavior should be.
The last pop trigger a train hopping where pri-animation of top most route = 0.16 reverse and sec-animation of the route below =0.67 forward. They will never meet and sec-animation just hang there until everything is disposed. This is what it looks like in real world
ezgif com-video-to-gif

Comment (chunhtai) [reply packages/flutter/test/widgets/routes_test.dart]: This is what it looks like after this pr
ezgif com-video-to-gif (1)

File: packages/flutter/lib/src/widgets/routes.dart [hunk 2]
```diff
@@ -234,13 +234,27 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
     super.didChangeNext(nextRoute);
   }
 
+  bool _shouldJumpTrain(Animation<double> firstTrain, Animation<double> secondTrain) {
+    // We should jump to the other train if two trains will never cross in the
```
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/routes.dart]: The code below also doesn't seem to check that the trains will not cross in the future.

File: packages/flutter/test/widgets/routes_test.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/test/widgets/routes_test.dart]: These animations both look broken.

File: packages/flutter/lib/src/widgets/routes.dart [hunk 3]
```diff
@@ -234,13 +234,27 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
...
+    if (firstTrain.value == secondTrain.value)
+      return true;
+    else if (firstTrain.value < secondTrain.value)
+      return firstTrain.status != AnimationStatus.forward &&
+             secondTrain.status != AnimationStatus.reverse;
+    else
+      return firstTrain.status != AnimationStatus.reverse &&
+             secondTrain.status != AnimationStatus.forward;
+  }
+
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/routes.dart]: nit: remove extra blank line

File: packages/flutter/lib/src/widgets/routes.dart [hunk 4]
```diff
@@ -234,13 +234,27 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
...
+
   void _updateSecondaryAnimation(Route<dynamic> nextRoute) {
     if (nextRoute is TransitionRoute<dynamic> && canTransitionTo(nextRoute) && nextRoute.canTransitionFrom(this)) {
       final Animation<double> current = _secondaryAnimation.parent;
       if (current != null) {
         final Animation<double> currentTrain = current is TrainHoppingAnimation ? current.currentTrain : current;
         final Animation<double> nextTrain = nextRoute._animation;
-        if (currentTrain.value == nextTrain.value) {
+        if (_shouldJumpTrain(currentTrain, nextTrain)) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/routes.dart]: I wonder if we just need to change this condition to jump directly when the values are the same and to also just jump directly when the nextTrain animation is completed (meaning the next route appeared on top of this route without animation).

File: packages/flutter/lib/src/widgets/routes.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/routes.dart]: The check is to detect whether they will cross with the current animations.

File: packages/flutter/lib/src/widgets/routes.dart (hunk 4 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/routes.dart]: This will only fix the initial route issue. what about the test below?

File: packages/flutter/lib/src/widgets/routes.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/routes.dart]: The test below only looks at the current value and the direction of the animation. How's that enough to determine if they will cross? AFIK, the animation values doesn't have to run monotonically from 0.0 to 1.0. It could bounce up and down in between?

File: packages/flutter/lib/src/widgets/routes.dart (hunk 4 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/routes.dart]: Oh, right. So somehow we need to guarantee that we will jump even when the trains haven't crossed at the end of the animation.

**Comment by chunhtai** [comment]
@goderbauer This is blocking the work of navigator page api. When you re-arrange the routes and try to update the secondary animation it is really easy to hit this case where the train hopping never finishes because the animation of next route is already completed

File: packages/flutter/lib/src/widgets/routes.dart [hunk 5]
```diff
@@ -247,42 +247,99 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
...
   }
 
+  // A callback method that disposes existing train hopping animation and
+  // removes its listener.
+  //
+  // This field is non-null if there is a train hopping in progress.
+  VoidCallback _trainHoppingListenerRemover;
+
   void _updateSecondaryAnimation(Route<dynamic> nextRoute) {
+    // There is an existing train hopping in progress. Unfortunately, we cannot
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/routes.dart]: How do you know at this point that there's an existing train hopping in progress?

File: packages/flutter/lib/src/widgets/routes.dart [hunk 6]
```diff
@@ -247,42 +247,99 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
...
           _setSecondaryAnimation(nextTrain, nextRoute.completed);
         } else {
+          // Two trains animate at different values. We have to do train hopping.
+          // There are three possibilities of train hopping:
+          //  1. We hop on the nextTrain when two trains meet in the middle using
+          //     TrainHoppingAnimation.
+          //  2. There is no chance to hop on nextTrain because two trains never
+          //     cross each other. We have to directly set the animation to
+          //     nextTrain once the nextTrain stops animating.
+          //  3. A new update secondary animation is called before train hopping
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/routes.dart]: use `_updateSecondaryAnimation` to make it clear that you mean this method?

File: packages/flutter/lib/src/widgets/routes.dart [hunk 7]
```diff
@@ -247,42 +247,99 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
...
+          //     finishes. We leave a listener remover for the next call to
+          //     properly clean up the existing train hopping
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/routes.dart]: nit: end with `.`

File: packages/flutter/lib/src/widgets/routes.dart [hunk 8]
```diff
@@ -247,42 +247,99 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
...
-          current.dispose();
-        }
       } else {
         _setSecondaryAnimation(nextRoute._animation, nextRoute.completed);
       }
     } else {
       _setSecondaryAnimation(kAlwaysDismissedAnimation);
     }
+    // Finally, we dispose any previous train hopping animation because it
+    // should be successfully updated at this point.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/routes.dart]: it should be -> it has been

File: packages/flutter/test/widgets/routes_test.dart [hunk 9]
```diff
@@ -789,6 +789,43 @@ void main() {
...
+                else
+                  primaryAnimationOfRouteTwo = animation;
+                return const Text('Page');
+              },
+            );
+          },
+          initialRoute: '/a',
+        )
+      );
+      // secondary animation of bottom route should be chained with the primary
```
Comment (goderbauer) [inline packages/flutter/test/widgets/routes_test.dart]: nit: start with a capital letter ("Secondary").

File: packages/flutter/lib/src/widgets/routes.dart [hunk 10]
```diff
@@ -247,42 +247,99 @@ abstract class TransitionRoute<T> extends OverlayRoute<T> {
...
+    if (previousTrainHoppingListenerRemover != null) {
+      previousTrainHoppingListenerRemover();
+      if (previousTrainHoppingListenerRemover == _trainHoppingListenerRemover)
+        _trainHoppingListenerRemover = null;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/routes.dart]: Could we just set _trainHoppingListenerRemover to null at the very beginning of this method after we copied it into  previousTrainHoppingListenerRemover?

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/routes.dart (hunk 5 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/routes.dart]: whoever calls this method will need to make sure to set this private field to null as to indicate there is no more train hopping in progress. I think the comment in line 253 is not clear enough, will update

**Comment by ldelafuente** [comment]
Hi @chunhtai, do you have a planned date to release this in the stable branch?
I tried patching routes.dart on the latest stable release but secondary animations still don't run for initial routes

**Comment by ldelafuente** [comment]
Hi @chunhtai, do you have a planned date to release this in the stable branch?
I tried patching routes.dart on the latest stable release with the insertions you made on this PR, but secondary animations still don't run for initial routes. Do these changes have dependencies on other files maybe?
I notices that the base file to that is in master is dated

**Comment by ldelafuente** [comment]
Hi @chunhtai , do you have a planned date to release this in the stable branch?
I tried patching routes.dart on the latest stable release with the insertions you made on this PR, but secondary animations still don't run for initial routes. Do these changes have dependencies on other files maybe?

I'm using nested navigators and the initial route doesn't pop even if I explicitly set initialRoute to false

**Comment by chunhtai** [comment]
@ldelafuente This patch does not depend on other file, can you provide a runnable example that reproduce the problem you are having? I don't know when the next stable release will be yet
