### PR TITLE
Fix/ios share context menu

### LINKED ISSUE #173491: [iOS] iOS system context menu is missing the "Share" button
### Steps to reproduce

1. Open a Flutter iOS app with a text field that contains text
2. Select text to show the iOS system context menu

### Expected results

A `TextField`'s context menu has the "Share" button when text is selected.

Tapping the "Share" button should show the iOS's share bottom sheet:

### Actual results

A `TextField`'s context menu does not have the "Share" button when text is selected.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      home: TextFieldPage(),
    ),
  );
}

class TextFieldPage extends StatelessWidget {
  const TextFieldPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Padding(
          padding: EdgeInsets.all(64.0),
          child: TextField(),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

_No response_

### Logs

N/A

### Flutter Doctor output

N/A

### PR DESCRIPTION
**Pull request by muradhossin**
This PR fixes https://github.com/flutter/flutter/issues/173491 by adding the missing 'Share' option to the default iOS SystemContextMenu when shareEnabled is true.

Changes:

Added IOSSystemContextMenuItemShare to getDefaultItems in system_context_menu.dart.
Added a widget test to ensure Share is present in the default items for non-empty selections on iOS.
Rationale:
This aligns Flutter's default iOS text selection context menu with native iOS behavior, ensuring users see the expected 'Share' option when selecting text.

Demo:
Video showing Share option in iOS context menu: https://github.com/user-attachments/assets/e04cd1f9-7d92-4147-a09b-719f03d9c625

### CODE REVIEW

File: packages/flutter/lib/src/widgets/system_context_menu.dart [hunk 1]
```diff
@@ -164,6 +164,7 @@ class SystemContextMenu extends StatefulWidget {
       if (editableTextState.lookUpEnabled) const IOSSystemContextMenuItemLookUp(),
       if (editableTextState.searchWebEnabled) const IOSSystemContextMenuItemSearchWeb(),
       if (editableTextState.liveTextInputEnabled) const IOSSystemContextMenuItemLiveText(),
+      if (editableTextState.shareEnabled) const IOSSystemContextMenuItemShare(),
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/system_context_menu.dart]: I would agree with that but no big deal if you have a reason for this ordering, @muradhossin .

File: packages/flutter/test/widgets/system_context_menu_test.dart [hunk 2]
```diff
@@ -1337,4 +1337,74 @@ void main() {
     skip: kIsWeb, // [intended]
     variant: TargetPlatformVariant.only(TargetPlatform.iOS),
   );
+
+  testWidgets(
+    'Default iOS SystemContextMenu includes Share for non-empty selection',
+        (WidgetTester tester) async {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/test/widgets/system_context_menu_test.dart]: Not sure if this is right or not, I'll defer to the CI checks. If they're green it's ok.

File: packages/flutter/test/widgets/system_context_menu_test.dart [hunk 3]
```diff
@@ -1337,4 +1337,74 @@ void main() {
...
+      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger.setMockMethodCallHandler(
+        SystemChannels.platform,
+            (MethodCall methodCall) async {
+          if (methodCall.method == 'ContextMenu.showSystemContextMenu') {
+            final Map<String, dynamic> arguments = methodCall.arguments as Map<String, dynamic>;
+            final List<dynamic> untypedItems = arguments['items'] as List<dynamic>;
+            final List<IOSSystemContextMenuItemData> lastItems = untypedItems.map((dynamic value) {
+              final Map<String, dynamic> itemJson = value as Map<String, dynamic>;
+              return systemContextMenuItemDataFromJson(itemJson);
+            }).toList();
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/test/widgets/system_context_menu_test.dart]: This seems legit.

**Review by justinmc — COMMENTED** [review]
Thanks for fixing this. Did we just forget to add the share button here? It makes me really wish we could use a `switch` or something to ensure that we don't miss any other new subclasses.

Take a look at the analyzer failure, you're missing a type in your test.

File: packages/flutter/lib/src/widgets/system_context_menu.dart [hunk 4]
```diff
@@ -156,15 +157,36 @@ class SystemContextMenu extends StatefulWidget {
...
-      if (editableTextState.selectAllEnabled) const IOSSystemContextMenuItemSelectAll(),
-      if (editableTextState.lookUpEnabled) const IOSSystemContextMenuItemLookUp(),
-      if (editableTextState.searchWebEnabled) const IOSSystemContextMenuItemSearchWeb(),
-      if (editableTextState.liveTextInputEnabled) const IOSSystemContextMenuItemLiveText(),
-    ];
+    final List<IOSSystemContextMenuItem> items = <IOSSystemContextMenuItem>[];
+
+    // Use the generic Flutter-rendered context menu model as the single source of truth.
+    for (final ContextMenuButtonItem button in editableTextState.contextMenuButtonItems) {
+      switch (button.type) {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/system_context_menu.dart:164]: This is great, now we know all button types are handled and always will be!

File: packages/flutter/test/widgets/system_context_menu_test.dart [hunk 5]
```diff
@@ -1337,4 +1337,80 @@ void main() {
...
+      await tester.pump();
+
+      // Assert that the platform message included a Share item.
+      expect(itemsReceived, isNotEmpty);
+      expect(
+        itemsReceived.last.any(
+          (IOSSystemContextMenuItemData e) => e is IOSSystemContextMenuItemDataShare,
+        ),
+        isTrue,
+      );
```
Comment (justinmc) [inline packages/flutter/test/widgets/system_context_menu_test.dart]: Nit: I wonder if there is a matcher that you could use here like `contains`? See https://main-api.flutter.dev/flutter/package-matcher_matcher/.

File: pubspec.lock
Comment (justinmc) [inline pubspec.lock:1]: Can you revert the changes in this file?

**Review by justinmc — COMMENTED** [review]
Looks good besides the accidental changes in pubspec.lock.

**Review by justinmc — APPROVED** [review]
LGTM 👍, thanks for following through on this PR!

File: packages/flutter/lib/src/widgets/system_context_menu.dart [hunk 6]
```diff
@@ -156,15 +157,36 @@ class SystemContextMenu extends StatefulWidget {
...
+        case ContextMenuButtonType.copy:
+          items.add(const IOSSystemContextMenuItemCopy());
```
Comment (jmagman) [inline packages/flutter/lib/src/widgets/system_context_menu.dart:166]: Does `editableTextState.copyEnabled` etc not need to be checked any more?

Comment (muradhossin) [reply packages/flutter/lib/src/widgets/system_context_menu.dart:166]: contextMenuButtonItems already applies those enable-checks for us.

So by iterating editableTextState.contextMenuButtonItems, we’re consuming the filtered set — only enabled actions are present.

That’s why we no longer need separate editableTextState.copyEnabled etc checks here — the switch is now operating on the already-screened model, which is the single source of truth for both Flutter-rendered and native menus.

**Comment by muradhossin** [comment]
@justinmc May I know if there’s any update on the merge?

**Review by dkwingsmt — APPROVED** [review]
LGTM. Thank you!

**Comment by justinmc** [comment]
@muradhossin Can you fix the analyzer failure here?

**Comment by LouiseHsu** [comment]
> > @muradhossin Can you fix the analyzer failure here?
> 
> @justinmc Could you please guide me on why many of the checks are failing?

can you try removing your changes to pubspec.lock and then merge master?
