### PR TITLE
Correct MaterialButton disabledColor

### LINKED ISSUE #30012: MaterialButton disabledColor is not working.
The disabledColor is not working in MaterialButton.

```dart
@override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    final ButtonThemeData buttonTheme = ButtonTheme.of(context);

    return RawMaterialButton(
      onPressed: onPressed,
      onHighlightChanged: onHighlightChanged,
      fillColor: color,
      textStyle: theme.textTheme.button.copyWith(color: buttonTheme.getTextColor(this)),
      highlightColor: highlightColor ?? theme.highlightColor,
      splashColor: splashColor ?? theme.splashColor,
      elevation: buttonTheme.getElevation(this),
      highlightElevation: buttonTheme.getHighlightElevation(this),
      padding: buttonTheme.getPadding(this),
      constraints: buttonTheme.getConstraints(this).copyWith(
        minWidth: minWidth,
        minHeight: height,
      ),
      shape: buttonTheme.shape,
      clipBehavior: clipBehavior ?? Clip.none,
      animationDuration: buttonTheme.getAnimationDuration(this),
      child: child,
      materialTapTargetSize: materialTapTargetSize ?? theme.materialTapTargetSize,
    );
  }
```

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes https://github.com/flutter/flutter/issues/30012

MaterialButton now initializes its RawMaterialButton's fillColor using the ButtonTheme.getFillColor(), just like the other button classes.

Also added some tedious tests that check the default configurations of MaterialButton, FlatButton, RaisedButton, and OutlineButton.

### CODE REVIEW

File: packages/flutter/lib/src/material/button_theme.dart [hunk 1]
```diff
@@ -491,7 +491,7 @@ class ButtonThemeData extends Diagnosticable {
     if (fillColor != null)
       return fillColor;
 
-    if (button is FlatButton || button is OutlineButton)
+    if (button is FlatButton || button is OutlineButton || button.runtimeType == MaterialButton)
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/button_theme.dart]: Why "is" on the others, and runtimeType on the MaterialButton? Seems like they should all be one or the other, no?

**Comment by HansMuller** [comment]
OutlineButton and FlatButton are among the MaterialButton subclasses.  So this expression matches the two subclasses (only) and the base class (only).

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

File: packages/flutter/lib/src/material/button_theme.dart (hunk 1 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/material/button_theme.dart]: OK, maybe a comment explaining that would be good?
