### PR TITLE
Fix the second TextFormField to trigger onTapOutside

### LINKED ISSUE #127597: After inputting text into a textFormField tapping into a second TextFormField does not trigger onTapOutside
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Using flutter web I have a listview with each item in the listview contains a textFormField.  I use the onTapOutside to save the text that has been inputed to a repo.  This works fine if the user taps the back button or most other places on the screen.  However, if they tap into another textFormField then the onTapOutside does not trigger and the text is not stored.  This is on web so using 'done' on the keyboard is not an option like it is on mobile.

### Expected results

Tapping into another textformfield should trigger the onTapOutside callback (and save the text to the repo)

### Actual results

Tapping into another textformfield does not trigger the onTapOutside callback (and text is not stored)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';


class TestTextController extends StatefulWidget {
  const TestTextController({Key? key}) : super(key: key);

  @override
  State<TestTextController> createState() => _TestTextControllerState();
}

class _TestTextControllerState extends State<TestTextController> {
  TextEditingController tx1 = TextEditingController();
  TextEditingController tx2 = TextEditingController();



  @override
  Widget build(BuildContext context) {
    return  Scaffold(
      appBar: AppBar(title: Text('Test'),),
      body: SizedBox(
       width: 200,
        child: Column(
          children: [
            TextFormField(
              controller: tx1,
              decoration: InputDecoration(
                  focusColor: Colors.grey,
                  focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.all(Radius.circular(5.0)),
                      borderSide: BorderSide(color: Colors.blue)),
                  isCollapsed: false,
              ),
              // initialValue: "",
              onChanged: (text)=>print(text),
              onTapOutside: (event)=>print('tapped outside'),
              maxLines: null,
            ),
            TextFormField(
              controller: tx2,
              decoration: InputDecoration(
                  focusColor: Colors.grey,
                  focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.all(Radius.circular(5.0)),
                      borderSide: BorderSide(color: Colors.blue)),
                  isCollapsed: false,
              ),
              // initialValue: "",
              onChanged: (text)=>print(text),
              onTapOutside: (event)=>print('tapped outside'),
              maxLines: null,
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.11.0-6.0.pre.18, on macOS 12.6.4 21G526 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

### PR DESCRIPTION
**Pull request by wyqlxf**
This PR attempts to fix https://github.com/flutter/flutter/issues/127597

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/tap_region.dart [hunk 1]
```diff
@@ -635,5 +635,6 @@ class TextFieldTapRegion extends TapRegion {
     super.onTapInside,
     super.consumeOutsideTaps,
     super.debugLabel,
-  }) : super(groupId: EditableText);
+    super.groupId = EditableText,
+  }) : super();
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/tap_region.dart:639]: Since we now pass everything with `super` parameters, isn't the `super();` redundant here?

Comment (wyqlxf) [reply packages/flutter/lib/src/widgets/tap_region.dart]: Yes, your suggestion is very good, and the unnecessary code has been removed.

**Comment by Piinks** [comment]
Hey @wyqlxf is this implementing the suggestion in https://github.com/flutter/flutter/pull/148112#issuecomment-2105356458?

**Comment by wyqlxf** [comment]
> Hey @wyqlxf is this implementing the suggestion in [#148112 (comment)](https://github.com/flutter/flutter/pull/148112#issuecomment-2105356458)?

Yes, this is in response to the suggestion (comment) in execution #148112, Provide a separate click area groupId object for each text field, Thank you very much to @gspencergoog  for the suggestion.

File: packages/flutter/lib/src/widgets/tap_region.dart (hunk 1 above)
Comment (wyqlxf) [reply packages/flutter/lib/src/widgets/tap_region.dart]: @navaronbracke Are there any other problem?

File: packages/flutter/lib/src/material/text_form_field.dart [hunk 2]
```diff
@@ -279,6 +281,13 @@ class TextFormField extends FormField<String> {
   /// initialize its [TextEditingController.text] with [initialValue].
   final TextEditingController? controller;
 
+  /// {@template flutter.widgets.editableText.groupId}
```
Comment (navaronbracke) [inline packages/flutter/lib/src/material/text_form_field.dart:284]: Same here for the documentation macro

File: packages/flutter/lib/src/material/text_field.dart [hunk 3]
```diff
@@ -369,6 +370,13 @@ class TextField extends StatefulWidget {
   /// {@end-tool}
   final TextMagnifierConfiguration? magnifierConfiguration;
 
+  /// {@template flutter.widgets.editableText.groupId}
```
Comment (navaronbracke) [inline packages/flutter/lib/src/material/text_field.dart:373]: Could you use a documentation macro so that the docs are not duplicated?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -1470,6 +1471,13 @@ class EditableText extends StatefulWidget {
   /// {@macro flutter.widgets.SelectionOverlay.onSelectionHandleTapped}
   final VoidCallback? onSelectionHandleTapped;
 
+  /// {@template flutter.widgets.editableText.groupId}
+  /// Assign a separate click area to each text field, groupId object.
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/editable_text.dart:1475]:
```suggestion
/// The group identifier for the [TextFieldTapRegion] of this text field.
///
/// Text fields with the same group identifier share the same tap region.
/// 
/// Defaults to the type of [EditableText].
```

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 5]
```diff
@@ -1470,6 +1471,13 @@ class EditableText extends StatefulWidget {
...
+  ///
+  /// If this property is null, [EditableText] will be used.
+  /// {@endtemplate}
+  final Object? groupId;
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/editable_text.dart:1479]: I wonder, if the default is `EditableText` anyway, can we make this non-nullable and use `EditableText` in the constructors of `EditableText`, `TextField`, `TextFormField`, as default value ?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 6]
```diff
@@ -841,6 +841,7 @@ class EditableText extends StatefulWidget {
     this.onAppPrivateCommand,
     this.onSelectionChanged,
     this.onSelectionHandleTapped,
+    this.groupId,
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/editable_text.dart:844]: Should we also add this to the `CupertinoTextField` and related widgets in the Cupertino library?

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 7]
```diff
@@ -193,6 +193,80 @@ void main() {
     skip: kIsWeb, // [intended]
   );
 
+  // Regression test for https://github.com/flutter/flutter/issues/127597
+  testWidgets(
+    'TapRegionSurface detects outside right click',
```
Comment (navaronbracke) [inline packages/flutter/test/widgets/editable_text_test.dart:198]: The test doesn't have anything to do with right click? It is for clicks outside of the TextFieldTapRegion, not specifically _right_ clicks.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 8]
```diff
@@ -193,6 +193,80 @@ void main() {
...
+      final GlobalKey keyC = GlobalKey();
+      await tester.pumpWidget(
+        MaterialApp(
+          home: Align(
+            alignment: Alignment.topLeft,
+            child: Column(
+              children: <Widget>[
+                const Text('Outside'),
+                Material(
+                  child: TextFormField(
```
Comment (navaronbracke) [inline packages/flutter/test/widgets/editable_text_test.dart:212]: This test should be for `EditableText` specifically. You can add a different test in the Material library that passes the  `groupId` to a `TextField` and one for a `TextFormField`. In those tests you then use a finder to grab the EditableText and check the group id.

File: packages/flutter/lib/src/material/text_field.dart (hunk 3 above)
Comment (wyqlxf) [reply packages/flutter/lib/src/material/text_field.dart]: Of course, thank you for your suggestion

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 6 above)
Comment (wyqlxf) [reply packages/flutter/lib/src/widgets/editable_text.dart:844]: Yes, thank you for your reminder

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 4 above)
Comment (wyqlxf) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Your suggestion has been received

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 7 above)
Comment (wyqlxf) [reply packages/flutter/test/widgets/editable_text_test.dart]: Yes, I will revise the description

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 8 above)
Comment (wyqlxf) [reply packages/flutter/test/widgets/editable_text_test.dart]: I will modify the unit test

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 9]
```diff
@@ -193,6 +193,80 @@ void main() {
...
+                    key: keyA,
+                    groupId: 'Group A',
+                    onTapOutside: (PointerDownEvent event) {
+                      tappedOutside = 'Outside Callback A';
```
[the remark this answers is not in the document]
Comment (wyqlxf) [reply packages/flutter/test/widgets/editable_text_test.dart]: I will modify the unit test

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 5 above)
Comment (wyqlxf) [reply packages/flutter/lib/src/widgets/editable_text.dart:1480]: The constructor of TextFormField can accept default values, but making the groupId of EditableText mandatory will require callers to pass parameters, potentially necessitating modifications to other unit tests.

Comment (wyqlxf) [reply packages/flutter/lib/src/widgets/editable_text.dart]: I think I should understand what you mean

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 10]
```diff
@@ -1470,6 +1471,14 @@ class EditableText extends StatefulWidget {
   /// {@macro flutter.widgets.SelectionOverlay.onSelectionHandleTapped}
   final VoidCallback? onSelectionHandleTapped;
 
+  /// {@template flutter.widgets.editableText.groupId}
+  /// The group identifier for the [TextFieldTapRegion] of this text field.
+  ///
+  /// Text fields with the same group identifier share the same tap region.
+  /// Defaults to the type of [EditableText].
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/editable_text.dart:1478]: You'll want to add a "See also:" here that points to `TextFieldTapRegion`, and probably add the same `groupId` optional argument there, although you could also explain here that they could also use a raw `TapRegion` with the `groupId` at that point, since they are entirely equivalent. Adding `groupId` to `TextFieldTapRegion` feels a little weird because it basically turns it into `TapRegion`, but without as many options. This is probably OK, given it is meant for a specific use case, but technically odd.

File: packages/flutter/lib/src/widgets/tap_region.dart [hunk 11]
```diff
@@ -635,5 +635,6 @@ class TextFieldTapRegion extends TapRegion {
     super.onTapInside,
     super.consumeOutsideTaps,
     super.debugLabel,
-  }) : super(groupId: EditableText);
+    super.groupId = EditableText,
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/tap_region.dart:638]: Adding `groupId` to `TextFieldTapRegion` feels a little weird because it basically turns it into `TapRegion`, but without as many options. This is probably OK, given it is meant for a specific use case, but technically odd.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Thanks for fixing this!

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 10 above)
Comment (wyqlxf) [reply packages/flutter/lib/src/widgets/editable_text.dart:1478]: Your suggestion has been received

File: packages/flutter/lib/src/widgets/tap_region.dart (hunk 11 above)
Comment (wyqlxf) [reply packages/flutter/lib/src/widgets/tap_region.dart:638]: Yes, thank you for your reminder

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 12]
```diff
@@ -1470,6 +1471,18 @@ class EditableText extends StatefulWidget {
...
+  ///
+  /// See also:
+  ///
+  ///  * [TextFieldTapRegion], for the provision of a separate tap region.
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/editable_text.dart:1482]:
```suggestion
  ///  * [TextFieldTapRegion], to give a [groupId] to a widget that is to be included in a
  ///     [TextField]'s tap region that has [groupId] set.
```

Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:1482]: One nit on @gspencergoog's suggestion above: Maybe avoid saying `[TextField]` since this macro is reused in other classes. Probably say `[EditableText]`?

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 13]
```diff
@@ -909,6 +909,81 @@ void main() {
...
+        await tester.enterText(finder, 'Hello');
+        await tester.pump();
+      }
+
+      expect(outsideClickA, false);
+
+      await click(find.byKey(keyA));
+      await tester.showKeyboard(find.byKey(keyA));
+      await tester.idle();
+      expect(outsideClickA, false);
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:974]: Nit: I would `expect` all 3 `outsideClickX` variables at each step.

File: packages/flutter/test/material/text_form_field_test.dart [hunk 14]
```diff
@@ -824,6 +824,82 @@ void main() {
...
+      expect(outsideClickA, true);
+
+      await click(find.byKey(keyC));
+      expect(outsideClickB, true);
+
+      await tester.tap(find.text('Outside'));
+      expect(outsideClickC, true);
+    },
+  );
+
```
Comment (justinmc) [inline packages/flutter/test/material/text_form_field_test.dart:902]: Nit: Should you add a similar test to TextField too?

**Review by justinmc — APPROVED** [review]
LGTM with nits :+1: 

And I have one more nit about the test organization for you. It feels backwards to me. I would think that the tests in editable_text_test that just expect that groupId is set would be on TextField, TextFormField, and CupertinoTextField, expecting that they have passed the groupId down to their EditableTexts. Similarly, I would do the test that you currently have on CupertinoTextField and TextFormField in editable_text_test instead, so that the functionality is tested once there.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 12 above)
Comment (wyqlxf) [reply packages/flutter/lib/src/widgets/editable_text.dart:1482]: thank you for your suggestions

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 13 above)
Comment (wyqlxf) [reply packages/flutter/test/cupertino/text_field_test.dart:974]: Thank you, this way the testing will be comprehensive.

File: packages/flutter/test/material/text_form_field_test.dart (hunk 14 above)
Comment (wyqlxf) [reply packages/flutter/test/material/text_form_field_test.dart:902]: Initially, I thought having it inside the TextFormField was enough, maybe we should add similar tests to the TextField as well. Thank you for your suggestion.
