### PR TITLE
Dynamically add integration_tests and screenshots to native iOS test results

### LINKED ISSUE #95648: Native iOS tests should generate a test per dart test with separate failure statuses and error messages instead of one "testIntegrationTest"
## Use case

When I submit an Android APK to TestLab that includes multiple test cases, the result screen in TestLab will show the different test cases with their title and status, as expected:

img

When I submit an iOS application to TestLab, the results only show one test case named `testIntegrationTest`, which basically drives the functionality of running Flutter iOS application tests in TestLab useless, given you cannot identify which test case has failed:

img

## Proposal

iOS test results should behave the same as Android test results, meaning that the test cases should be split.

Here's a Stack Overflow question from another user that exemplifies the issue: https://stackoverflow.com/questions/68738425/flutter-integration-test-in-testlab-for-ios-use-cases-are-not-divided-in-ios

### PR DESCRIPTION
**Pull request by jmagman**
A subset of https://github.com/flutter/flutter/pull/88013 which does not get rid of the macro or make it easier to use from Swift, but does dynamically add the dart tests as individual native iOS XCTestCase tests via swizzling.

https://github.com/flutter/flutter/pull/88013 was reverted because the XCTest methods were in the plugin and therefore being embedded in the app, which caused "Non-public API usage" submission failures (even though `XCTest` was weak-linked) https://github.com/flutter/flutter/issues/71873#issuecomment-907421653.  Instead, pull test parsing/swizzling logic out of the plugin and into the macro so it's only called from the test target.  Also don't edit the `podspec` to weak-link `XCTest`.

Screen Shot 2021-12-22 at 6 30 34 PM

Fixes https://github.com/flutter/flutter/issues/95648

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/integration_test/ios/Classes/FLTIntegrationTestRunner.h [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+@import Foundation;
+
+@class UIImage;
+
+NS_ASSUME_NONNULL_BEGIN
+
+typedef void (^FLTIntegrationTestResults)(SEL nativeTestSelector, BOOL success, NSString *_Nullable failureMessage);
```
Comment (jmagman) [inline packages/integration_test/ios/Classes/FLTIntegrationTestRunner.h:11]: This is almost the same as https://github.com/flutter/flutter/pull/88013 except it's passing back a test selector `testVerifyTest` instead of the test name `verify test`. This allows us to do more of the test name casing logic in the plugin instead of the macro.

File: packages/integration_test/ios/Classes/FLTIntegrationTestRunner.m [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+  while (!integrationTestPlugin.testResults) {
+    [NSRunLoop.currentRunLoop runUntilDate:[NSDate dateWithTimeIntervalSinceNow:1.0]];
+  }
+
+  [integrationTestPlugin.testResults enumerateKeysAndObjectsUsingBlock:^(NSString *test, NSString *result, BOOL *stop) {
+    // Create an appropriate XCTest method name based on the dart test name.
+    // Example: dart test "verify widget" becomes "testVerifyWidget"
+    NSString *upperCamelTestName = [test.localizedCapitalizedString stringByReplacingOccurrencesOfString:@" " withString:@""];
+    NSString *testSelectorName = [NSString stringWithFormat:@"test%@", upperCamelTestName];
+    SEL testSelector = NSSelectorFromString(testSelectorName);
```
Comment (jmagman) [inline packages/integration_test/ios/Classes/FLTIntegrationTestRunner.m:46]: The selector logic is here instead of in the macro.  Other than that, this works the same as https://github.com/flutter/flutter/pull/88013.

File: packages/integration_test/ios/Classes/IntegrationTestIosTest.h [hunk 3]
```diff
@@ -21,26 +19,48 @@ NS_ASSUME_NONNULL_BEGIN
 
 @end
 
+// For every Flutter dart test, dynamically generate an Objective-C method mirroring the test results
+// so it is reported as a native XCTest run result.
+// If the Flutter dart tests have captured screenshots, add them to the XCTest bundle.
 #define INTEGRATION_TEST_IOS_RUNNER(__test_class)                                           \
-  @interface __test_class : XCTestCase<FLTIntegrationTestScreenshotDelegate>                \
+  @interface __test_class : XCTestCase                                                      \
```
Comment (jmagman) [inline packages/integration_test/ios/Classes/IntegrationTestIosTest.h:26]: Unfortunately since this is subclassing `XCTestCase` this code can't really live in the plugin or it will cause a "Non-public API usage" submission failure.  Keep the macro and do the test invocation logic swapping there.

File: packages/integration_test/ios/Classes/IntegrationTestIosTest.h [hunk 4]
```diff
@@ -21,26 +19,48 @@ NS_ASSUME_NONNULL_BEGIN
...
-    BOOL testPass = [integrationTestIosTest testIntegrationTest:&testResult];               \
-    XCTAssertTrue(testPass, @"%@", testResult);                                             \
-  }                                                                                         \
-                                                                                            \
-  - (void)didTakeScreenshot:(UIImage *)screenshot attachmentName:(NSString *)name {         \
-    XCTAttachment *attachment = [XCTAttachment attachmentWithImage:screenshot];             \
-    attachment.lifetime = XCTAttachmentLifetimeKeepAlways;                                  \
-    if (name != nil) {                                                                      \
-      attachment.name = name;                                                               \
+  + (NSArray<NSInvocation *> *)testInvocations {                                            \
```
Comment (jmagman) [inline packages/integration_test/ios/Classes/IntegrationTestIosTest.h:31]: This logic is the same as in https://github.com/flutter/flutter/pull/88013 (except the test selector instead of name part).

File: packages/integration_test/ios/Classes/IntegrationTestPlugin.h [hunk 5]
```diff
@@ -23,15 +16,18 @@ NS_ASSUME_NONNULL_BEGIN
  */
 @property(nonatomic, readonly, nullable) NSDictionary<NSString *, NSString *> *testResults;
 
+/**
+ * Mapping of screenshot images by suggested names, captured by the dart tests.
+ */
+@property (copy, readonly) NSDictionary<NSString *, UIImage *> *capturedScreenshotsByName;
```
Comment (jmagman) [inline packages/integration_test/ios/Classes/IntegrationTestPlugin.h:22]: This file is the same as in #88013.

File: packages/integration_test/ios/Classes/IntegrationTestPlugin.m [hunk 6]
```diff
@@ -2,10 +2,10 @@
 // Use of this source code is governed by a BSD-style license that can be
 // found in the LICENSE file.
 
-@import UIKit;
-
 #import "IntegrationTestPlugin.h"
 
+@import UIKit;
```
Comment (jmagman) [inline packages/integration_test/ios/Classes/IntegrationTestPlugin.m:7]: This file is the same as in #88013.

File: packages/integration_test/ios/Classes/FLTIntegrationTestRunner.h [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+
+@interface FLTIntegrationTestRunner : NSObject
+
+/**
+ * Any screenshots captured by the plugin.
+ */
+@property (copy, readonly) NSDictionary<NSString *, UIImage *> *capturedScreenshotsByName;
+
+/*!
```
Comment (stuartmorgan) [inline packages/integration_test/ios/Classes/FLTIntegrationTestRunner.h:20]: Typo: s/!/*/

File: packages/integration_test/ios/Classes/FLTIntegrationTestRunner.h [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+ Start dart tests and wait for results.
```
Comment (stuartmorgan) [inline packages/integration_test/ios/Classes/FLTIntegrationTestRunner.h:21]: Nit: Starts

(per style guide)

File: packages/integration_test/ios/Classes/FLTIntegrationTestRunner.m [hunk 9]
```diff
@@ -0,0 +1,60 @@
...
+
+  // Spin the runloop.
+  while (!integrationTestPlugin.testResults) {
+    [NSRunLoop.currentRunLoop runUntilDate:[NSDate dateWithTimeIntervalSinceNow:1.0]];
+  }
+
+  [integrationTestPlugin.testResults enumerateKeysAndObjectsUsingBlock:^(NSString *test, NSString *result, BOOL *stop) {
+    // Create an appropriate XCTest method name based on the dart test name.
+    // Example: dart test "verify widget" becomes "testVerifyWidget"
+    NSString *upperCamelTestName = [test.localizedCapitalizedString stringByReplacingOccurrencesOfString:@" " withString:@""];
```
Comment (stuartmorgan) [inline packages/integration_test/ios/Classes/FLTIntegrationTestRunner.m:44]: I missed this last time, but it seems like we need a lot more normalization here, since AFAIK a Dart test name can be an arbitrary string. E.g., If the test name is `"validate multi-point unicode: 😁 "` we're going to have a bad time.

Comment (stuartmorgan) [reply packages/integration_test/ios/Classes/FLTIntegrationTestRunner.m:44]: This is probably going to be complicated enough that we should pull it out into a helper that has its own set of unit tests.

**Review by stuartmorgan-g — CHANGES_REQUESTED** [review]

File: packages/integration_test/ios/Classes/FLTIntegrationTestRunner.m (hunk 9 above)
Comment (stuartmorgan) [reply packages/integration_test/ios/Classes/FLTIntegrationTestRunner.m]: Alternately you could sanitize unicode to a byte description (e.g., 🌈 -> "U1F308") to avoid collisions, but it's a pretty unlikely edge case.

**Review by stuartmorgan-g — APPROVED** [review]
LGTM!

File: packages/integration_test/ios/Classes/FLTIntegrationTestRunner.m (hunk 9 above)
Comment (jmagman) [reply packages/integration_test/ios/Classes/FLTIntegrationTestRunner.m]: Let's see if anyone ever files an issue about it...
