### PR TITLE
Shake widget inspector from non-debug builds

### LINKED ISSUE #80156: WidgetInspector code is retained in release mode
To reproduce:

```
cd examples/hello_world
flutter build apk --target-platform android-arm64 --release --analyze-size
flutter pub global run devtools --appSizeBase apk-code-size-analysis_01.json
```

You can find 7.4kb of code related to the WidgetInspector.

I assumed this was due to the static initialization of `WidgetInspectorService.instance`, but just making that lazy isn't enough to shake the code out.

/cc @jacob314

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/80156

Will add a test before marking ready for review.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/binding.dart [hunk 1]
```diff
@@ -290,7 +290,10 @@ mixin WidgetsBinding on BindingBase, ServicesBinding, SchedulerBinding, GestureB
     window.onLocaleChanged = handleLocaleChanged;
     window.onAccessibilityFeaturesChanged = handleAccessibilityFeaturesChanged;
     SystemChannels.navigation.setMethodCallHandler(_handleNavigationInvocation);
-    FlutterErrorDetails.propertiesTransformers.add(transformDebugCreator);
+    assert(() {
+      FlutterErrorDetails.propertiesTransformers.add(transformDebugCreator);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/binding.dart:294]: Maybe we should rename `transformDebugCreator` to `debugTransformDebugCreator` to make it clear that it should only be used in debug builds. Additionally, the implementation of the method could be wrapped in an assert as well so that even if you accidentally call this method in non-debug code, it doesn't actually do anything or retain code...

Comment (dnfield) [reply packages/flutter/lib/src/widgets/binding.dart]: Done.

I've added the test harness, which unfortunately required reving pub packages.

I can split this into a smaller PR if need be.

File: dev/bots/test.dart [hunk 2]
```diff
@@ -637,6 +637,19 @@ Future<void> _runFrameworkTests() async {
...
+      path.join(flutterRoot, 'dev', 'forbidden_from_release_tests', 'bin', 'main.dart'),
+      '--forbidden-type', 'WidgetInspectorService',
+    ];
+    await runCommand(
+      dart,
+      args,
+      workingDirectory: flutterRoot,
+    );
+  }
+
```
Comment (goderbauer) [inline dev/bots/test.dart:651]: nit: just one blank line?

File: dev/forbidden_from_release_tests/bin/main.dart [hunk 3]
```diff
@@ -0,0 +1,268 @@
+import 'dart:io';
```
Comment (goderbauer) [inline dev/forbidden_from_release_tests/bin/main.dart:5]: nit: lisence header

File: dev/forbidden_from_release_tests/README.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+# Forbidden from release tests
+
+This program compiles the Dart portions of some Flutter applications to the
+AOT format used for release builds, and verifies that debugging related types
+are not retained.
```
Comment (goderbauer) [inline dev/forbidden_from_release_tests/README.md:5]: Maybe document how to add forbidden types

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 5]
```diff
@@ -2892,7 +2892,12 @@ bool _isDebugCreator(DiagnosticsNode node) => node is DiagnosticsDebugCreator;
 ///
 /// This function will be registered to [FlutterErrorDetails.propertiesTransformers]
 /// in [WidgetsBinding.initInstances].
-Iterable<DiagnosticsNode> transformDebugCreator(Iterable<DiagnosticsNode> properties) sync* {
+///
+/// This is meant to be called only in debug mode. In other modes, it yeilds an empty list.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2896]: typo: yeilds

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 6]
```diff
@@ -2892,7 +2892,12 @@ bool _isDebugCreator(DiagnosticsNode node) => node is DiagnosticsDebugCreator;
...
+Iterable<DiagnosticsNode> debugTransformDebugCreator(Iterable<DiagnosticsNode> properties) sync* {
+  if (kDebugMode) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2898]: shouldn't this be "if not debug mode"?

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 7]
```diff
@@ -2892,7 +2892,12 @@ bool _isDebugCreator(DiagnosticsNode node) => node is DiagnosticsDebugCreator;
...
+    break;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/widget_inspector.dart]: break?

File: dev/forbidden_from_release_tests/bin/main.dart [hunk 8]
```diff
@@ -0,0 +1,268 @@
...
+  for (final String forbiddenType in options.forbiddenTypes) {
+    if (json.contains(forbiddenType)) {
+      foundForbiddenTypes.add(forbiddenType);
+    }
+  }
+  if (foundForbiddenTypes.isNotEmpty) {
+    print('The output contained the following forbidden types:');
+    print(foundForbiddenTypes);
+    exit(-1);
+  }
```
Comment (goderbauer) [inline dev/forbidden_from_release_tests/bin/main.dart:50]: Should it print something if everything was clean?

File: dev/forbidden_from_release_tests/bin/main.dart (hunk 3 above)
Comment (goderbauer) [inline dev/forbidden_from_release_tests/bin/main.dart:5]: Could you add a test that verifies that this actually warns if a forbidden type is found?

File: dev/forbidden_from_release_tests/README.md [hunk 9]
```diff
@@ -0,0 +1,5 @@
+# Forbidden from release tests
+
+This program compiles the Dart portions of some Flutter applications to the
```
Comment (goderbauer) [inline dev/forbidden_from_release_tests/README.md:3]: What flutter app is actually used?

File: dev/forbidden_from_release_tests/bin/main.dart [hunk 10]
```diff
@@ -0,0 +1,268 @@
...
+
+  tempDirectory.deleteSync(recursive: true);
+}
+
+Future<void> pubGet(File flutter, Directory target) async {
+  final List<String> command = <String>[flutter.path, 'pub', 'get'];
+  print('Running command: ${command.join(' ')} in ${target.path}');
+  final ProcessResult pubGetResult = await processManager.run(
```
Comment (goderbauer) [inline dev/forbidden_from_release_tests/bin/main.dart:58]: Should we maybe stream the outputs to the console? (if this command hangs we will never see anything in the logs where it was hanging I think).

Comment (goderbauer) [reply dev/forbidden_from_release_tests/bin/main.dart:58]: (same for the other run commands)

File: dev/forbidden_from_release_tests/bin/main.dart [hunk 11]
```diff
@@ -0,0 +1,268 @@
...
+      'fe-snapshot',
+      help: 'The path to the frontend server snapshot.',
+      valueHelp: path.join(
+          r'$FLUTTER_ROOT', 'bin', 'cache', 'artifacts', 'engine', _getPlatformName(), 'frontend_server.dart.snapshot'),
+      defaultsTo: path.join(fs.currentDirectory.path, 'bin', 'cache', 'artifacts', 'engine', _getPlatformName(),
+          'frontend_server.dart.snapshot'),
+    );
+    argParser.addOption(
+      'target',
+      abbr: 't',
```
Comment (goderbauer) [inline dev/forbidden_from_release_tests/bin/main.dart:182]: help text?

**Review by goderbauer — COMMENTED** [review]
Nice!

File: dev/bots/test.dart (hunk 2 above)
Comment (dnfield) [reply dev/bots/test.dart:651]: Fixed.

File: dev/forbidden_from_release_tests/bin/main.dart (hunk 3 above)
Comment (dnfield) [reply dev/forbidden_from_release_tests/bin/main.dart:5]: added

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 5 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2896]: fixed

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 6 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/widget_inspector.dart:2898]: Fixed

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 7 above)
Comment (dnfield) [reply packages/flutter/lib/src/widgets/widget_inspector.dart]: Fixed

File: dev/forbidden_from_release_tests/bin/main.dart (hunk 8 above)
Comment (dnfield) [reply dev/forbidden_from_release_tests/bin/main.dart:50]: Added a line.

File: dev/forbidden_from_release_tests/README.md (hunk 9 above)
Comment (dnfield) [reply dev/forbidden_from_release_tests/README.md:3]: By default it's using `examples/hello_world`. That's documented in the usage help from main.dart.

File: dev/forbidden_from_release_tests/bin/main.dart (hunk 11 above)
Comment (dnfield) [reply dev/forbidden_from_release_tests/bin/main.dart:182]: added

File: dev/forbidden_from_release_tests/bin/main.dart (hunk 10 above)
Comment (dnfield) [reply dev/forbidden_from_release_tests/bin/main.dart:58]: I'll change these.

File: dev/forbidden_from_release_tests/README.md (hunk 9 above)
Comment (goderbauer) [reply dev/forbidden_from_release_tests/README.md:3]: Maybe add that information here as well? "some Flutter app" is so vague..

File: dev/forbidden_from_release_tests/bin/main.dart [hunk 12]
```diff
@@ -0,0 +1,272 @@
...
+Future<File> compileKernel({
+  required Directory tempDirectory,
+  required File dart,
+  required File target,
+  required File feSnapshot,
+  required Directory sdkProduct,
+  required File packageConfig,
+  required String packageName,
+}) async {
+  final File dill = tempDirectory.childFile('forbidden_release_imports.dill');
```
Comment (jonahwilliams) [inline dev/forbidden_from_release_tests/bin/main.dart:79]: This is going to be awkward to keep in sync with changes in the tool. Perhaps we could make build bundle support outputting release kernel? Otherwise we need something automated to keep this in sync.

I'm worried about us updating the flags and then forgetting to update this as well, leading to mistaken test results.

Comment (dnfield) [reply dev/forbidden_from_release_tests/bin/main.dart:79]: I'm less concerned about building the kernel as being about to get a deterministic path for the snapshot summary file.

File: dev/forbidden_from_release_tests/bin/main.dart [hunk 13]
```diff
@@ -0,0 +1,272 @@
...
+      defaultsTo: path.join(fs.currentDirectory.path, 'examples', 'hello_world', '.dart_tool', 'package_config.json'),
+    );
+
+    argParser.addOption(
+      'package-name',
+      valueHelp: 'package:hello_world/main.dart',
+      defaultsTo: 'package:hello_world/main.dart',
+    );
+
+    argParser.addMultiOption(
```
Comment (jonahwilliams) [inline dev/forbidden_from_release_tests/bin/main.dart:206]: This is going to have some limitations, in case we add some classes private or otherwise that have similar names. This could include a library URI to disambiguate further

File: dev/forbidden_from_release_tests/pubspec.yaml [hunk 14]
```diff
@@ -0,0 +1,16 @@
+name: forbidden_from_release_tests
+publish_to: 'none'
+
+environment:
+  sdk: '>=2.12.0 <3.0.0'
+
+dependencies:
+  args: 2.0.0
+  file: 6.1.0
```
Comment (jonahwilliams) [inline dev/forbidden_from_release_tests/pubspec.yaml:9]: If you're not writing unit tests for your tests, I don't think using file or process buys you anything. Its almost exactly the same API as Process.run/dart:io File.

File: dev/forbidden_from_release_tests/bin/main.dart (hunk 3 above)
Comment (dnfield) [reply dev/forbidden_from_release_tests/bin/main.dart:5]: Added one to test.dart

File: dev/forbidden_from_release_tests/bin/main.dart (hunk 12 above)
Comment (jonahwilliams) [reply dev/forbidden_from_release_tests/bin/main.dart:74]: To be perfectly clear, I'm not promising to remember this test or consider updates to the flags we pass to the frontend_server to be breaking in anyway. If you're OK remembering to keep this up to date on your own, then by all means :)

File: dev/forbidden_from_release_tests/pubspec.yaml (hunk 14 above)
Comment (dnfield) [reply dev/forbidden_from_release_tests/pubspec.yaml:9]: I figure it makes it easier in the future and no one will have to rerun update-packages. I think these packages also have some additional checks/guards that I'd miss using dart:io directly too right?

File: dev/forbidden_from_release_tests/bin/main.dart (hunk 13 above)
Comment (dnfield) [reply dev/forbidden_from_release_tests/bin/main.dart:110]: I've redone this so that it requires a package URI

File: dev/forbidden_from_release_tests/bin/main.dart (hunk 12 above)
Comment (dnfield) [reply dev/forbidden_from_release_tests/bin/main.dart]: This has been refactored to just use `flutter build apk`.

**Comment by dnfield** [comment]
I've substantially re-written this after landing an option in the tool to allow changing the snapshot json output location.

Main changes:

- Use `flutter build apk` instead of interacting with `dart`/`gen_snapshot` etc.
- Use package:vm_snapshot_analysis to do program info lookups rather than simple string matching, which would easily get false positives.

File: dev/forbidden_from_release_tests/README.md (hunk 9 above)
Comment (dnfield) [reply dev/forbidden_from_release_tests/README.md:3]: Made some updates here - hopefully it's clearer now.

File: dev/forbidden_from_release_tests/pubspec.yaml (hunk 14 above)
Comment (jonahwilliams) [reply dev/forbidden_from_release_tests/pubspec.yaml:9]: not really :)

File: dev/forbidden_from_release_tests/bin/main.dart [hunk 15]
```diff
@@ -0,0 +1,157 @@
...
+    final int doubleColons = forbiddenType.indexOf('::');
+    if (slash == -1 || doubleColons < 2) {
+      print('Invalid forbidden type "$forbiddenType". The format must be <package_uri>::<type_name>, e.g. package:flutter/src/widgets/framework.dart::Widget');
+      fail = true;
+      continue;
+    }
+
+    final List<String> lookupPath = <String>[
+      forbiddenType.substring(0, slash),
+      forbiddenType.substring(0, doubleColons),
```
Comment (goderbauer) [inline dev/forbidden_from_release_tests/bin/main.dart:65]: Is this expected that they both start at 0? Should the second one start after the slash?

**Review by goderbauer — COMMENTED** [review]
The new check seems to be failing on CI and from the logs it's not clear why. Do we need to log more?

File: dev/forbidden_from_release_tests/bin/main.dart (hunk 15 above)
Comment (dnfield) [reply dev/forbidden_from_release_tests/bin/main.dart:65]: Yes, expected - we want `package:flutter/src/whatever/whatever.dart`, not `src/whatever/whatever.dart` when we do the typelookup.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
I think I'm going to do one more refactor of this so we just point it at the snapshot file rather than invoking Flutter. Something's going weird with a second run of `flutter build apk`, and it's wasteful to do that twice anyway.
