### PR TITLE
Fix scrolling of multiple SliverLists and SliverGrids

### LINKED ISSUE #11548: CustomScrollView bug when SliverGrid and SliverList are children
## Steps to Reproduce

Running the Sample Code from [widgets/CustomScrollView](https://docs.flutter.io/flutter/widgets/CustomScrollView-class.html) produces a bug while scrolling. See [Video](https://youtu.be/C-7Dt3ZkaN0) and [Github Repo](https://github.com/JohannesKaufmann/sliverbug/blob/master/lib/main.dart#L41-L82).

(The issue only seems to happen if a `SliverGrid` and a `SliverFixedExtentList`/`SliverList` are mixed together in a `CustomScrollView`?) It was recorded on the iPhone Simulator but the same happens on an actual Android Device.

```dart
/* Sample Code from widgets/CustomScrollView */
new CustomScrollView(
  slivers: <Widget>[
    const SliverAppBar(
      pinned: true,
      expandedHeight: 250.0,
      flexibleSpace: const FlexibleSpaceBar(
        title: const Text('Demo'),
      ),
    ),
    new SliverGrid(
      gridDelegate: new SliverGridDelegateWithMaxCrossAxisExtent(
        maxCrossAxisExtent: 200.0,
        mainAxisSpacing: 10.0,
        crossAxisSpacing: 10.0,
        childAspectRatio: 4.0,
      ),
      delegate: new SliverChildBuilderDelegate(
        (BuildContext context, int index) {
          return new Container(
            alignment: FractionalOffset.center,
            color: Colors.teal[100 * (index % 9)],
            child: new Text('grid item $index'),
          );
        },
        childCount: 20,
      ),
    ),
    new SliverFixedExtentList(
      itemExtent: 50.0,
      delegate: new SliverChildBuilderDelegate(
        (BuildContext context, int index) {
          return new Container(
            alignment: FractionalOffset.center,
            color: Colors.lightBlue[100 * (index % 9)],
            child: new Text('list item $index'),
          );
        },
      ),
    ),
  ],
)
```

```dart
/* similar code in my own app */
List slivers = <Widget>[
  new SliverAppBar(
    pinned: true,
    primary: true,
    expandedHeight: topSize['height'],
    flexibleSpace: new FlexibleSpaceBar(
      background: topContent(context, widget.id),
    ),
    actions: <Widget>[
      new IconButton(
        icon: new Icon(Icons.share),
        onPressed: () {

        },
        tooltip: 'Share',
      )
    ],
  ),
  new SliverList(
    delegate: new SliverChildListDelegate(
      topChildren.where(notNull).toList(),
    )
  ),
  new Images( // is a SliverGrid
    images: screenshots,
    id: widget.id,
    onClickImage: openImage
  ),
  new SliverList(
    delegate: new SliverChildListDelegate(
    bottomChildren.where(notNull).toList(),
  )
 ), 
];

return new CustomScrollView(
  slivers: slivers
)
```

### `flutter logs`

Since there is not crash happening there are no indications in the logs.

```
DTServiceHub: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
diagnosticd: dispatch_io_write error: 32 (Broken pipe)
diagnosticd: reflect channel created for fd 6
DTServiceHub: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
DTServiceHub: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
DTServiceHub: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
```

### `flutter analyze`
only one issues regarding not using the value `_counter`

## `flutter doctor`

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-DE, channel alpha)
    • Flutter at /Users/johannes/Documents/dev/github/flutter-sdk
    • Framework revision bbcfb8d51a (7 days ago), 2017-08-01 14:50:29 -0700
    • Engine revision f2af347363
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/johannes/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/johannes/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[-] IntelliJ IDEA Community Edition (version 2016.3.2)
    ✗ Flutter plugin version 12.1 - the recommended minimum version is 14.0.0
    • Dart plugin version 163.13137
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] Connected devices
    • iPhone SE • A5527156-9756-425D-B9F0-CB741DB4FB42 • ios • iOS 10.3 (simulator)
```

-----

Because there is a lack of documentation regarding slivers I wanted to ask another question:

If I understand correctly this

```
CustomScrollView
  - SliverAppBar
  - SliverList
      - Item
      - Item
  - SliverGrid
  - SliverList
```
is now preferred over
```
$controller

ListView (with controller)
  - Item
  - Item
  - GridView (with controller & shrinkWrap: true)
  - Item
```

Is this correct?

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/11548

Has a backward incompatible change:

> The `SliverGridLayout.estimateMaxScrollOffset` method has been replaced by the `SliverGridLayout.computeMaxScrollOffset` method. This new method must report an accurate value, not just an estimate. This was necessary to fix a bug where a finite `SliverGrid` could not handle being scrolled off the top of the screen (because we had no way to determine how much content it had).
>
> For similar reasons, the `RenderSliverBoxChildManager` interface has a new getter, `childCount`, which must return a non-null value if `createChild` can return null. In practice, it is unusual to implement this interface, so this should have no effect. It is more common to implement the widgets-layer equivalent, `SliverChildDelegate`. This interface already had an `estimatedChildCount` getter. The getter continues to exist, though its semantics have been adjusted a little to require that the returned value be accurate if the `build` method on the delegate ever returns null.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @abarth, who might still be the most qualified person to review this...

File: packages/flutter/lib/src/rendering/sliver_grid.dart [hunk 1]
```diff
@@ -539,10 +540,14 @@ class RenderSliverGrid extends RenderSliverMultiBoxAdaptor {
...
-      if (!addInitialChild(index: firstIndex,
-          layoutOffset: firstChildGridGeometry.scrollOffset)) {
-        // There are no children.
-        geometry = SliverGeometry.zero;
+      if (!addInitialChild(index: firstIndex, layoutOffset: firstChildGridGeometry.scrollOffset)) {
+        // There are either no children, or we are past the end of all our children.
+        final double max = layout.computeMaxScrollOffset(childManager.childCount);
+        geometry = new SliverGeometry(
+          scrollExtent: max,
+          paintExtent: 0.0,
```
Comment (abarth) [inline packages/flutter/lib/src/rendering/sliver_grid.dart]: 0.0 is the default value.  Maybe remove?

**Comment by abarth** [comment]
LGTM

File: packages/flutter/lib/src/rendering/sliver_grid.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/rendering/sliver_grid.dart]: done

**Comment by Hixie** [comment]
Thanks for the review, will land on green.
