### PR TITLE
Colored box optimization (#176028)

### LINKED ISSUE #176028: ColoredBox create unwanted strip when placed close together due to the framework assuming isAntiAlias ​​= true
### Steps to reproduce

I encountered this issue when placing multiple widgets together with the same background. It creates an unwanted visible strip in the background.

Image

I tried the same code in other frameworks, such as SwiftUI, and it rendered as expected.

| Flutter | SwiftUI | 
| :---: | :---: | 
| Image | Image | 
| Image | Image | 

### Expected results

No unwanted strip when render multiple widgets with the same background color close together.

Image

### Actual results

I dug into the implementation of ColoredBox and noticed that the paint function always assumes that Paint() is anti-aliased by default. This is generally good, but as we can see when drawing a rectangle, there’s no need to enable anti-aliasing to ensure smoothness. In fact, it introduces a visual bug like the one I described above.

```dart

class _RenderColoredBox extends RenderProxyBoxWithHitTestBehavior {
   ...

  @override
  void paint(PaintingContext context, Offset offset) {
    // It's tempting to want to optimize out this `drawRect()` call if the
    // color is transparent (alpha==0), but doing so would be incorrect. See
    // https://github.com/flutter/flutter/pull/72526#issuecomment-749185938 for
    // a good description of why.
    if (size > Size.zero) {
      context.canvas.drawRect(offset & size, Paint()..color = color);
    }
    if (child != null) {
      context.paintChild(child!, offset);
    }
  }
}
```

The fix for this problem is simple:

```dart
@override
  void paint(PaintingContext context, Offset offset) {
    // It's tempting to want to optimize out this `drawRect()` call if the
    // color is transparent (alpha==0), but doing so would be incorrect. See
    // https://github.com/flutter/flutter/pull/72526#issuecomment-749185938 for
    // a good description of why.
    if (size > Size.zero) {
      context.canvas.drawRect(
        offset & size,
        Paint()
          ..color = color
          ..isAntiAlias = false,
      );
    }
    if (child != null) {
      context.paintChild(child!, offset);
    }
  }
```

### Code sample

Dartpad link: https://dartpad.dev/?id=72d0881637a25d884d7b922cab8bb0ff

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.37.0-1.0.pre-232, on macOS 26.0 25A354 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 26.0.1)
[✓] Chrome - develop for the web
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for fhihung.iphone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Bui’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Duong phone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for zennn.phone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPad của Chi bé. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone 12 Chi. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by definev**
This PR fixed visual bug when placing multiple `ColoredBox`s together. (Fixes #176028)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by victorsanni — COMMENTED** [review]
Hi @definev, thanks for the PR. Could you add a test to make sure this change does not get regressed?

**Comment by definev** [comment]
Hi @victorsanni, I created the test. Feel free to let me know if you’d like me to write more tests for it. This is my first time contributing to Flutter, thank you so much ☺️

**Review by victorsanni — COMMENTED** [review]
This [golden test](https://github.com/flutter/packages/blob/c7a25fa3463b6e9033a1c6db7acff42e1a3a8799/packages/rfw/test/argument_decoders_test.dart#L495) in the rfw package is failing with the changes in this PR.

**Comment by definev** [comment]
I think that’s the expected behavior since it changes the way ColoredBox is rendered. The next step I should take is to either regenerate all the golden tests or declare this as a breaking change that may affect existing golden tests? cc: @victorsanni 
Screenshot 2025-09-30 at 01 56 11

**Comment by definev** [comment]
@victorsanni @dkwingsmt Are there any new updates for me to do?

**Review by victorsanni — APPROVED** [review]
LGTM awaiting review from someone more knowledgeable about the subject such as @dkwingsmt.

For the failing customer test, the process is to disable it in a separate PR which will land before this one, then re-enable it after this PR lands while approving the new goldens. I can open a PR to do that.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 1]
```diff
@@ -8430,14 +8430,17 @@ class _RenderColoredBox extends RenderProxyBoxWithHitTestBehavior {
...
   @override
   void paint(PaintingContext context, Offset offset) {
     // It's tempting to want to optimize out this `drawRect()` call if the
     // color is transparent (alpha==0), but doing so would be incorrect. See
     // https://github.com/flutter/flutter/pull/72526#issuecomment-749185938 for
     // a good description of why.
     if (size > Size.zero) {
-      context.canvas.drawRect(offset & size, Paint()..color = color);
+      _paint.color = color;
+      context.canvas.drawRect(offset & size, _paint);
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/basic.dart]: Can you instantiate the Paint here instead of reusing it each time? I avoid try to avoid this pattern after seeing https://github.com/flutter/flutter/issues/171194, even though that should be fixed by now.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 2]
```diff
@@ -8429,7 +8429,12 @@ class _RenderColoredBox extends RenderProxyBoxWithHitTestBehavior {
     // https://github.com/flutter/flutter/pull/72526#issuecomment-749185938 for
     // a good description of why.
     if (size > Size.zero) {
-      context.canvas.drawRect(offset & size, Paint()..color = color);
+      context.canvas.drawRect(
+        offset & size,
+        Paint()
+          ..color = color
+          ..isAntiAlias = false,
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/widgets/basic.dart]: I really wonder if there is a performance benefit here in real life or not. After seeing https://github.com/flutter/flutter/issues/171194 it always makes me nervous. Fine as-is though.

**Review by justinmc — APPROVED** [review]
LGTM 👍 . I would guess that we were notting getting much benefit from setting isAntiAlias to true in this case, but I'm interested to see if the Google tests have any failures. We should watch out for any failures that appear to have benefitted from antialiasing.

And +1 to @dkwingsmt reviewing this as well.

File: packages/flutter/lib/src/widgets/basic.dart (hunk 1 above)
Comment (definev) [reply packages/flutter/lib/src/widgets/basic.dart]: Sure, that my initial approach to. Seeing Gemini suggest reuse paint object so i change to fit it comment :-) Let reverse that

Comment (definev) [reply packages/flutter/lib/src/widgets/basic.dart]: Updated

**Comment by dkwingsmt** [comment]
Thanks for the nomination, although I wouldn't call myself an expert at all. :)

I played with this change locally and observed that there are visual changes to all `ColoredBox`es, as expected. The edges are no longer as clear.
image


Even if we think this change is too small to notice or even healthy for having a clearer border, it's bound to break millions of golden tests. The impact is far too great. I don't think we can justify this breakage.

It might be better to expose the `isAntiAlias` as a parameter and keep the current behavior default. I'm not sure how viable it is, since the parameter might need to be propagated to some other widgets, such as `Container`. But it's definitely better than breakage like this.

**Comment by justinmc** [comment]
Good find @dkwingsmt, I was worried something like that might happen. +1 to your recommendation of exploring exposing isAntiAlias.

**Comment by definev** [comment]
I think the effect should apply to all ColoredBox widgets since they depend on each other. For example, placing one anti-aliased ColoredBox between two non-anti-aliased ones still causes the visual bug to appear.

We could introduce a new static variable in ColoredBox, called defaultIsAntiAlias, which would be set to true by default. However, users could set it to false if they prefer crisp borders.

If we still want to expose it, let add a 'bool? isAntiAlias' and set it to defaultIsAntiAlias if null.

**Comment by dkwingsmt** [comment]
> I think the effect should apply to all ColoredBox widgets since they depend on each other. For example, placing one anti-aliased ColoredBox between two non-anti-aliased ones still causes the visual bug to appear.

Turning off anti-alias has many down sides, such as artifacts during rotation or zooming animation. Notice the borders in the following examples:

image

https://github.com/user-attachments/assets/4af30f8c-2e50-42c3-aa3a-52d54c78c918

It should be up to the developers to decide if they really want to use, or need, the non-antialias version. In general, the antialias version should be more widely applicable.

**Comment by definev** [comment]
Agree! I’ve updated the code based on your comment, exposing isAntiAlias in ColoredBox.
One small detail I observed in the SwiftUI framework is that they also use antiAlias, but they don’t have the same visual bug we encountered. Apparently, Flutter on mobile doesn’t have that issue either, so I think it’s related to the engine layer. The current solution is to expose isAntiAlias in ColoredBox.

Note: The stripe is still visible in SwiftUI, but it’s much thinner than in Flutter and only appears when rotating the child.

https://github.com/user-attachments/assets/5b4eaace-6808-45a6-9b54-4f750955c9f8 

https://github.com/user-attachments/assets/bd2b34e1-ea59-4254-bf48-f73edb49bb11

| SwiftUI | Flutter |
|---|---|
| Screenshot 2025-10-09 at 18 32 33 | Screenshot 2025-10-09 at 18 38 24 |

File: packages/flutter/lib/src/widgets/basic.dart [hunk 3]
```diff
@@ -8392,31 +8392,38 @@ class _StatefulBuilderState extends State<StatefulBuilder> {
 /// child on top of that color.
 class ColoredBox extends SingleChildRenderObjectWidget {
   /// Creates a widget that paints its area with the specified [Color].
-  const ColoredBox({required this.color, super.child, super.key});
+  const ColoredBox({required this.color, this.isAntiAlias = true, super.child, super.key});
 
   /// The color to paint the background area with.
   final Color color;
 
+  /// Whether to apply anti-aliasing to the color. Defaults to true.
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/basic.dart]: I think the developers probably would like more explanation on this property. Here's my proposal (suggestions welcome!):

```suggestion
  /// Whether to apply anti-aliasing when painting the box.
  ///
  /// Defaults to `true`.
  ///
  /// When `true`, the painted box will have smooth edges. This is crucial for
  /// animations and transformations (such as rotation or scaling) where the
  /// widget's edges may not align perfectly with the physical pixel grid.
  /// Anti-aliasing allows for sub-pixel rendering, which prevents a 'jagged'
  /// appearance during motion and ensures visually smooth transitions.
  ///
  /// Set this to `false` for specific use cases where multiple `ColoredBox`
  /// widgets are positioned adjacent to each other to form a larger, seamless
  /// area of solid color. With anti-aliasing enabled (`true`), faint seams or
  /// gaps might appear between the boxes due to the semi-transparent pixels at
  /// their edges. Disabling anti-aliasing ensures that the boxes align perfectly
  /// without such visual artifacts.
  ///
  /// See also:
  ///
  ///  * [Paint.isAntiAlias], the underlying property that this controls.
```

File: packages/flutter/lib/src/widgets/container.dart [hunk 4]
```diff
@@ -326,6 +327,9 @@ class Container extends StatelessWidget {
   /// null.
   final Color? color;
 
+  /// Whether to apply anti-aliasing to the color. Defaults to true.
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/container.dart]: After we've decided on `ColoredBox.isAntiAlias`'s doc, can you clone it to here with the `@template` and `@macro` tags?

File: packages/flutter/lib/src/widgets/basic.dart [hunk 5]
```diff
@@ -8392,31 +8392,38 @@ class _StatefulBuilderState extends State<StatefulBuilder> {
...
+    (renderObject as _RenderColoredBox)
+      ..color = color
+      ..isAntiAlias = isAntiAlias;
   }
 
   @override
   void debugFillProperties(DiagnosticPropertiesBuilder properties) {
     super.debugFillProperties(properties);
     properties.add(DiagnosticsProperty<Color>('color', color));
+    properties.add(DiagnosticsProperty<bool?>('isAntiAlias', isAntiAlias));
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/basic.dart]: Maybe `defaultValue: true`?

File: packages/flutter/test/widgets/basic_test.dart [hunk 6]
```diff
@@ -1220,6 +1220,24 @@ void main() {
...
+    });
+
+    testWidgets('ColoredBox - passing isAntiAlias = false', (WidgetTester tester) async {
+      await tester.pumpWidget(const ColoredBox(color: colorToPaint, isAntiAlias: false));
+      expect(find.byType(ColoredBox), findsOneWidget);
+      final RenderObject renderColoredBox = tester.renderObject(find.byType(ColoredBox));
+
+      renderColoredBox.paint(mockContext, Offset.zero);
+      expect(mockCanvas.paints.single.isAntiAlias, isFalse);
+    });
```
Comment (dkwingsmt) [inline packages/flutter/test/widgets/basic_test.dart:1240]: Can you create a golden test to display the difference from antialising? Something just like our screenshots during the discussion. I'm not sure if the antialiasing shows well on golden though and we'll have to see.

File: packages/flutter/lib/src/widgets/basic.dart (hunk 3 above)
Comment (definev) [reply packages/flutter/lib/src/widgets/basic.dart]: I like the detailed explanation for each use case 👍

**Comment by definev** [comment]
@dkwingsmt i added the test but i don't know how to make it generate new golden test image and the CI is failing i don't know why. I follow the Writing-a-golden-file-test-for-package-flutter.md but seem i don't need to edit ci.yaml file

**Comment by dkwingsmt** [comment]
The `ci.yaml` validation failure is simply due to the PR base being too old. I've updated it with the latest master. The golden file will be generated once all checks are green. Let's see how it goes. Thank you.

File: packages/flutter/lib/src/widgets/container.dart [hunk 7]
```diff
@@ -326,6 +327,11 @@ class Container extends StatelessWidget {
   /// null.
   final Color? color;
 
+  /// The [ColoredBox.isAntiAlias] property.
+  ///
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/container.dart]: The macro already has the first paragraph.
```suggestion
```

File: packages/flutter/lib/src/widgets/basic.dart (hunk 5 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/basic.dart]: This isn't fixed?

Comment (definev) [reply packages/flutter/lib/src/widgets/basic.dart]: I already fixed it

File: packages/flutter/lib/src/widgets/container.dart (hunk 7 above)
Comment (definev) [reply packages/flutter/lib/src/widgets/container.dart]: Done ✅

File: packages/flutter/lib/src/widgets/basic.dart (hunk 5 above)
Comment (definev) [reply packages/flutter/lib/src/widgets/basic.dart]: I set default to true on constructor

**Comment by justinmc** [comment]
@definev Looks like there are still analyzer failures FYI.

**Comment by definev** [comment]
I will check on that

**Comment by definev** [comment]
I’ve fixed the format, but I haven’t found a way to resolve the Mac framework_tests_impeller and tree-status issues yet.
One more question - I saw the [flutter/goldens](https://github.com/flutter/goldens) repository. Do I need to upload the golden test images before merging the PR into master?

**Comment by victorsanni** [comment]
> I’ve fixed the format, but I haven’t found a way to resolve the Mac framework_tests_impeller and tree-status issues yet.

Those are infra issues unrelated to this PR.

> One more question - I saw the [flutter/goldens](https://github.com/flutter/goldens) repository. Do I need to upload the golden test images before merging the PR into master?

No, adding a golden test using `matchesGoldenFile` is sufficient. A contributor with commit access will then go ahead to triage the golden images in the flutter gold tool.

File: packages/flutter/lib/src/widgets/basic.dart [hunk 8]
```diff
@@ -8392,31 +8392,59 @@ class _StatefulBuilderState extends State<StatefulBuilder> {
...
+    (renderObject as _RenderColoredBox)
+      ..color = color
+      ..isAntiAlias = isAntiAlias;
   }
 
   @override
   void debugFillProperties(DiagnosticPropertiesBuilder properties) {
     super.debugFillProperties(properties);
     properties.add(DiagnosticsProperty<Color>('color', color));
+    properties.add(DiagnosticsProperty<bool>('isAntiAlias', isAntiAlias));
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/widgets/basic.dart]: `defaultValue: true`?

**Comment by dkwingsmt** [comment]
The golden tests don't seem to demonstrate the non-antialias grids well. I think it's because the dimensions aren't fractional, which would be more noticeable when the dimensions are decided by text.

image

**Comment by definev** [comment]
Got it, I'll create a more concrete example with similar colored squares placed close together to demonstrate the original problem

**Comment by dkwingsmt** [comment]
Yeah. Instead of fixed widths maybe try wrapping them with text.

**Comment by definev** [comment]
I intentionally set `scale: 1.04` to demonstrate the anti-aliasing process. It doesn't show the golden image as expected if I set it to 1 on my mac.
image

File: packages/flutter/test/widgets/basic_test.dart [hunk 9]
```diff
@@ -1220,6 +1220,210 @@ void main() {
...
+
+    testWidgets('ColoredBox golden test - anti-aliasing and rotation variations', (
+      WidgetTester tester,
+    ) async {
```
Comment (dkwingsmt) [inline packages/flutter/test/widgets/basic_test.dart:1248]: nit: Document how to interpret the golden results. My proposal:
```dart
  // This test verifies how `ColoredBox.isAntiAlias` affects rendering.
  // The first row uses `isAntiAlias: true`, showing gaps between the white backgrounds.
  // The second row uses `isAntiAlias: false`, demonstrating no gaps between the white backgrounds.
  // The third row contains three tilted boxes with `isAntiAlias` set to true, false, and false, respectively.
```

**Comment by dkwingsmt** [comment]
The 1.04x scale is brilliant! The golden file looks great as well. I only have two comments left.

**Review by justinmc — APPROVED** [review]
LGTM as long as @dkwingsmt's comments are addressed. Thanks for pivoting on this PR!

File: packages/flutter/lib/src/widgets/basic.dart (hunk 8 above)
Comment (definev) [reply packages/flutter/lib/src/widgets/basic.dart]: This is already true i set `isAntiAlias: true` in the constructor `const ColoredBox({required this.color, this.isAntiAlias = true, super.child, super.key});`

File: packages/flutter/test/widgets/basic_test.dart (hunk 9 above)
Comment (definev) [reply packages/flutter/test/widgets/basic_test.dart:1248]: Done ✅

File: packages/flutter/lib/src/widgets/basic.dart (hunk 8 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/widgets/basic.dart]: Nope, this `defaultValue: true` is used to tell `DiagnosticsProperty` not to display this property when the value is the default value. For example, the reason why `framework_test.dart` needs changing in this PR is because this property. Although this change is relatively subjective, I think it's a good move because it avoids breaking existing logging test and also avoids printing relatively nuance info.

**Comment by definev** [comment]
Thanks @dkwingsmt, @justinmc, and @victorsanni for supporting me in resolving issues and guiding me through my very first PRs in the Flutter project :-) Because of the time zone difference, I couldn’t reply to you guys right away, but you were patient and helped me finish it!

File: packages/flutter/lib/src/widgets/basic.dart (hunk 8 above)
Comment (definev) [reply packages/flutter/lib/src/widgets/basic.dart]: Ah got it, i thought you was mention the `bool?` i mistakenly put in very first commit

Comment (definev) [reply packages/flutter/lib/src/widgets/basic.dart]: Done ✅ Thanks for the clear explanation!

File: packages/flutter/lib/src/widgets/container.dart [hunk 10]
```diff
@@ -257,6 +257,7 @@ class Container extends StatelessWidget {
     this.alignment,
     this.padding,
     this.color,
+    this.isAntiAlias = true,
```
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/container.dart:260]: Should `Container` test for this property as well?

Comment (definev) [reply packages/flutter/lib/src/widgets/container.dart:260]: Could be, but I think we don’t need to test it since under the hood Container still uses `ColoredBox`, so their behavior should be the same. Maybe we should add `isAntiAlias` to existing `Decoration`(`BoxDecoration`, `ShapeDecoration`, etc) to ensure consistent behavior when users want to configure the color? After that, we can add a test for it.

Comment (victorsanni) [reply packages/flutter/lib/src/widgets/container.dart:260]: > I think we don’t need to test it since under the hood Container still uses ColoredBox

I don't think that's enough of a reason not to test it. Imagine a future where someone removes the property from `Container`. Without a test such a change won't raise any alarms.

Comment (definev) [reply packages/flutter/lib/src/widgets/container.dart:260]: I think it’s reasonable. Currently, we don’t expose isAntiAlias on `Decoration` yet, so if we test it in `Container`, it should only use `ColoredBox`, meaning the behavior will be the same.
On the other hand, Container is usually used with a `decoration` setup that includes things like `color`, `borderRadius`, etc. So if we want to write a test for `Container`, we should first implement `isAntiAlias` in the `BoxDecoration` and `ShapeDecoration` classes, and then write tests for them.

Comment (definev) [reply packages/flutter/lib/src/widgets/container.dart:260]: If you think it’s too big for this PR, I can create a new one to implement isAntiAlias on Decoration for consistent behavior 👍

Comment (victorsanni) [reply packages/flutter/lib/src/widgets/container.dart:260]: > If you think it’s too big for this PR, I can create a new one to implement isAntiAlias on Decoration for consistent behavior 👍

That would be great. What about for `Container` in a separate PR also?

Comment (definev) [reply packages/flutter/lib/src/widgets/container.dart:260]: Sure, I'd love to do that 💙 I’ll write tests for `Container` to verify `isAntiAlias` in both cases: when using `Decoration`, and when using the `isAntiAlias` + `color` properties in that PR too ✅

**Review by dkwingsmt — APPROVED** [review]
