### PR TITLE
Fix `ExpansionTile` Expanded/Collapsed announcement is interrupted by VoiceOver

### LINKED ISSUE #132264: `ExpansionTile` accessibility information doesn't read Expanded/Collapsed (iOS)
Internal: b/269139224

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Click on the ExpansionTile component with text "xxx" with accessibility mode enabled. Then, it will read like "xxx, Expanded  double tap to collapse" or "xxx, Collapsed  double tap to expand".
2. Double click on the ExpansionTile component, then immediately it will only read "xxx", but the expected words are "xxx Expanded" or "xxx Collapsed"
3. Note if you single click on the ExpansionTile component it will still read out the output described in step 1 as expected. The only issue is just at step 2, when user finishes the double clicking.

It seems that this issue has been fixed by https://github.com/flutter/flutter/issues/74963, but reverted by https://github.com/flutter/flutter/pull/121699 with a new solution introduced. In the final video shown by https://github.com/flutter/flutter/pull/121699, this issue exists. Furthermore, the error seems to be that "Expanded" and "Collapsed" hints are interrupted when being announced. Related issue --> https://github.com/flutter/flutter/issues/122101. One solution might be delaying the announcement.

### Expected results

When double clicked, the ExpansionTile component should read out "xxx Expanded" or "xxx Collapsed".

### Actual results

When double clicked, the ExpansionTile component only reads out "xxx".

### Code sample

<details><summary>Code sample</summary>

```dart
ExpansionTile(
tilePadding: EdgeInsets.zero,
title: Text("xxx"),
expandedAlignment: Alignment.topLeft,
childrenPadding: const EdgeInsetsDirectional.only(
start: 48,
top: 12,
end: 0,
bottom: 12,
),
children: [],
)
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [`ExpansionTile` accessibility information doesn't read Expanded/Collapsed (iOS)](https://github.com/flutter/flutter/issues/132264)

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: const Text('ExpansionTile'),
        ),
        body: const ExpansionTile(
          title: Text("Title"),
          children: <Widget>[
            Placeholder(),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {},
          child: const Icon(Icons.add),
        ),
      ),
    );
  }
}
```

</details>

### Before

https://github.com/flutter/flutter/assets/48603081/542d8392-52dc-4319-92ba-215a7164db49

### After

https://github.com/flutter/flutter/assets/48603081/c9225144-4c12-4e92-bc41-4ff82b370ad7

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by TahaTesser** [comment]
cc: @math1man

**Comment by TahaTesser** [comment]
We agreed to fix this issue by delaying semantic announcement in https://github.com/flutter/flutter/issues/132264#issuecomment-1956801006. While https://github.com/flutter/flutter/issues/122101 is open.

File: packages/flutter/lib/src/material/expansion_tile.dart [hunk 1]
```diff
@@ -596,7 +597,7 @@ class _ExpansionTileState extends State<ExpansionTile> with SingleTickerProvider
     super.dispose();
   }
 
-  void _toggleExpansion() {
+  Future<void> _toggleExpansion() async {
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/expansion_tile.dart:600]: Any reason to make this async? AFAICT, the futures don't need to be awaited in this method since the Semantics announcement is fire-and-forget.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/expansion_tile.dart]: Ohh... great catch! Since it's a future i always assumed it has to be waited.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by TahaTesser** [comment]
@QuncCccccc 
Can you please also check why this is failing Google Testing? Thanks!

**Comment by QuncCccccc** [comment]
> @QuncCccccc Can you please also check why this is failing Google Testing? Thanks!

For this one, it failed several familylink tests and the exception message shows test failed on this assert: https://github.com/flutter/flutter/blob/f4ee956d3eea7524e37082e5d86f665d0a0bac2e/packages/flutter_test/lib/src/binding.dart#L1527

Same exception message as the PR 143443

**Comment by TahaTesser** [comment]
> > @QuncCccccc Can you please also check why this is failing Google Testing? Thanks!
> 
> For this one, it failed several familylink tests and the exception message shows test failed on this assert:
> 
> https://github.com/flutter/flutter/blob/f4ee956d3eea7524e37082e5d86f665d0a0bac2e/packages/flutter_test/lib/src/binding.dart#L1527
> 
> Same exception message as the PR 143443

`Future.delayed` seems to have cause this issue so I've replaced it with `Timer` and tests are green. 

Can you please review the changes and approve if it looks good.

**Review by QuncCccccc — APPROVED** [review]
LGTM:)
