### PR TITLE
Fix app bar title overflow with centerTitle:true

### LINKED ISSUE #5212: appbar title is overflowing appbar buttons
## Steps to Reproduce

Update buttons_demo.dart to use
```
return new TabbedComponentDemoScaffold(
      title: 'Buttons:WWWWWWWWWWWWWWWWWWW',
      demos: demos
    );
```
then run against an iPhone 5S on the iOS simulator.

screen shot 2016-08-03 at 6 07 00 pm

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision a1fa7c94e3 (71 minutes ago), engine revision 1f03d60a27

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.27
```

### PR DESCRIPTION
**Pull request by HansMuller**
Simplified AppBar title layout. The title only gets the horizontal space between the app bar's leading widget and the (trailing) action widgets.

Also: AppBar.copyWith() wasn't copying the centerTitle property.

Fixes: #5212

### CODE REVIEW

**Comment by sethladd** [comment]
Thanks!

**Comment by dragostis** [comment]
LGTM.

**Comment by abarth** [comment]
Does this mean that title won't be centered in the full app bar if there are a different number (or differrently sized) icons on the left and right?

File: packages/flutter/lib/src/material/app_bar.dart [hunk 1]
```diff
@@ -308,16 +309,18 @@ class AppBar extends StatelessWidget {
...
     toolBarRow.add(new Flexible(
-      child: new Align(
-        // TODO(abarth): In RTL this should be aligned to the right.
-        alignment: FractionalOffset.centerLeft,
-        child: new Padding(
-          padding: new EdgeInsets.only(left: 8.0),
-          child: effectiveCenterTitle ? null : centerWidget
+      child: new Padding(
+        padding: new EdgeInsets.symmetric(horizontal: 8.0),
+        child: new Align(
```
Comment (abarth) [inline packages/flutter/lib/src/material/app_bar.dart]: I think we need a custom layout to get the title centering correct.

I think the correct algorithm is to place the left and right widgets, see how much space is left, and ask the title to layout with that much space.  Once you know the size of the title widget, we need to position it as close to center as possible without overlapping the left and right widgets.

**Comment by HansMuller** [comment]
I agree. Will write a custom multi-child layout.

File: packages/flutter/lib/src/material/app_bar.dart [hunk 2]
```diff
@@ -24,6 +24,65 @@ abstract class AppBarBottomWidget extends Widget {
...
+class _ToolBarLayout extends MultiChildLayoutDelegate {
+  _ToolBarLayout({ this.centerTitle });
+
+  // If false the title should be left or right justified within the space bewteen
+  // the leading and actions widgets, depending on the locale's writing direction.
+  // If true the title is centered within the toolbar (not within the horizontal
+  // space bewteen the leading and actions widgets).
+  final bool centerTitle;
+
+  static const kLeadingWidth = 24.0;
```
Comment (dragostis) [inline packages/flutter/lib/src/material/app_bar.dart]: You'll need types here.

File: packages/flutter/lib/src/material/app_bar.dart [hunk 3]
```diff
@@ -24,6 +24,65 @@ abstract class AppBarBottomWidget extends Widget {
...
+  static const kTitleLeft = 64.0; // The AppBar pads left and right an additional 8.0.
```
Comment (dragostis) [inline packages/flutter/lib/src/material/app_bar.dart]: And here.

File: packages/flutter/lib/src/material/app_bar.dart [hunk 4]
```diff
@@ -24,6 +24,65 @@ abstract class AppBarBottomWidget extends Widget {
...
+
+    if (hasChild(_ToolBarSlot.title)) {
+      final double maxWidth = size.width - kTitleLeft - actionsWidth;
+      final BoxConstraints constraints = new BoxConstraints.loose(size).copyWith(maxWidth: maxWidth);
+      final Size titleSize = layoutChild(_ToolBarSlot.title, constraints);
+      final double titleY = (size.height - titleSize.height) / 2.0;
+      double titleX = kTitleLeft;
+
+      // If the centered title will not fit between the leading and actions
+      // widgets, then justify it with the wider one.
```
Comment (Hixie) [inline packages/flutter/lib/src/material/app_bar.dart]: I don't understand what "then justify it with the wider one" means.

Comment (HansMuller) [inline packages/flutter/lib/src/material/app_bar.dart]: The title is constrained to be no wider than the available space between the leading and actions widgets. If it doesn't fit when centered then it will overlap the wider of the leading and actions widgets. It can't overlap both because [see the first sentence].

So when the centered title doesn't fit, either its left edge is set to the leading widget's right edge, or its right edge is set to the actions widgets' left edge.  That's what I mean by "justified". In this case the code justifies the overlapping title edge.

Comment (Hixie) [inline packages/flutter/lib/src/material/app_bar.dart]: Ah, I see. "justify" means [something else](https://en.wikipedia.org/wiki/Typographic_alignment#Justified). I would recommend saying something like "align it against" or "place it abutting" instead of "justify it with".

**Comment by Hixie** [comment]
LGTM modulo comment issue
