### PR TITLE
fix: selected date decorator renders outside PageView in `DatePickerDialog` dialog

### LINKED ISSUE #171717: Selected date decorator renders outside PageView in `DatePickerDialog` dialog
### Steps to reproduce

1. Open the `showDatePicker` dialog.
2. Select a date.
3. Swipe to another month.

### Expected results

The selected date decorator should stay within the `PageView` and move along with its content during transitions.

### Actual results

The selected date decorator is painted outside the `PageView` during transitions.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      scrollBehavior: MyCustomScrollBehavior(),
      home: Scaffold(
        body: Center(
          child: Builder(
            builder: (context) {
              return FilledButton(
                onPressed: () {
                  showDatePicker(
                    context: context,
                    firstDate: DateTime(2024),
                    lastDate: DateTime(2026),
                  );
                },
                child: Text('showDatePicker'),
              );
            },
          ),
        ),
      ),
    );
  }
}

// Enable scrolling with mouse dragging
class MyCustomScrollBehavior extends MaterialScrollBehavior {
  @override
  Set<PointerDeviceKind> get dragDevices => {
    ...super.dragDevices,
    PointerDeviceKind.mouse,
  };
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.5, on macOS 15.5 24F74 darwin-arm64, locale en-IN)
    [2.0s]
    • Flutter version 3.32.5 on channel stable at /Users/albin/fvm/versions/3.32.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fcf2c11572 (13 days ago), 2025-06-24 11:44:07 -0700
    • Engine revision dd93de6fb1
    • Dart version 3.8.1
    • DevTools version 2.45.1

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [5.8s]
    • Android SDK at /Users/albin/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • Java binary at: /Users/albin/.sdkman/candidates/java/17.0.15.fx-zulu/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment Zulu17.58+21-CA (build 17.0.15+6-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [4.0s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [14ms]
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2024.3) [13ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.101.2) [11ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.115.20250701

[✓] Connected device (2 available) [6.4s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 138.1.80.115

[✓] Network resources [1,175ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by albinpk**
Wraps `PageView` with a transparent `Material` to ensure the selected date decorator is painted in the correct context, avoiding visual glitches during transitions.

Fixes #171717 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by huycozy — COMMENTED** [review]
Thanks for submitting a fix, @albinpk!
The solution looks good to me. However, it appears that test(s) is/are missing. Could you please add one/some? Perhaps you could check the visibility of the Ink's decoration?

**Comment by albinpk** [comment]
Thanks for the review! @huycozy 

I need some help writing a test for this. How to confirm if a decoration is painted on the expected `Material` widget during a test?
What I could do is check the render object sizes of the `PageView` and the nearest `Material` to see if they match. Let me know if that sounds reasonable or if there's a better approach.

**Comment by huycozy** [comment]
> I need some help writing a test for this. How to confirm if a decoration is painted on the expected Material widget during a test?
What I could do is check the render object sizes of the PageView and the nearest Material to see if they match. Let me know if that sounds reasonable or if there's a better approach.

@albinpk I would suggest using Devtools and finding the difference between `before` and `after` the fix. (It could be `visibility of the Ink's decoration` as suggested above, perhaps from some of its property values?)

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 1]
```diff
@@ -888,13 +889,18 @@ class _MonthPickerState extends State<_MonthPicker> {
...
                 date: _dayGridFocus.hasFocus ? _focusedDay : null,
-                child: PageView.builder(
-                  key: _pageViewKey,
-                  controller: _pageController,
-                  itemBuilder: _buildItems,
-                  itemCount:
-                      widget.calendarDelegate.monthDelta(widget.firstDate, widget.lastDate) + 1,
-                  onPageChanged: _handleMonthPageChanged,
+                // Wrap with Material to paint the selected date decorator
+                // here instead of on the Dialog during transitions.
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/calendar_date_picker.dart]: I suggest a bit more detailed explanation:
```suggestion
                // Wrap the PageView with `Material`, so when its child paints on materials
                // the content won't go out of boundary during page transition.
```

**Review by dkwingsmt — COMMENTED** [review]
The change looks good to me.

If unit tests are really a blocker, you can also go the easy way of using golden tests.

**Comment by gnprice** [comment]
Thanks for fixing this! For writing a test, I saw your question in Discord, and have a couple of suggestions:
https://discord.com/channels/608014603317936148/692831010445983785/1397446388681277450

**Review by dkwingsmt — APPROVED** [review]
LGTM

File: packages/flutter/test/material/calendar_date_picker_test.dart [hunk 2]
```diff
@@ -1435,6 +1435,29 @@ void main() {
...
+    testWidgets('Ink feature paints on inner Material', (WidgetTester tester) async {
+      await tester.pumpWidget(
+        calendarDatePicker(
+          firstDate: DateTime(2025, DateTime.june),
+          initialDate: DateTime(2025, DateTime.july, 20),
+          lastDate: DateTime(2025, DateTime.august, 31),
+        ),
+      );
+
+      // Material outside the PageView
```
Comment (huycozy) [inline packages/flutter/test/material/calendar_date_picker_test.dart]:
```suggestion
      // Material outside the PageView.
```

File: packages/flutter/test/material/calendar_date_picker_test.dart [hunk 3]
```diff
@@ -1435,6 +1435,29 @@ void main() {
...
+      final MaterialInkController outerMaterial = Material.of(
+        tester.element(find.byType(FocusableActionDetector)),
+      );
+      // Material directly wrapping the PageView
```
Comment (huycozy) [inline packages/flutter/test/material/calendar_date_picker_test.dart]:
```suggestion
      // Material directly wrapping the PageView.
```

File: packages/flutter/test/material/calendar_date_picker_test.dart [hunk 4]
```diff
@@ -1435,6 +1435,29 @@ void main() {
...
+      final MaterialInkController innerMaterial = Material.of(
+        tester.element(find.byType(PageView)),
+      );
+
+      // Only the inner Material should have ink features
```
Comment (huycozy) [inline packages/flutter/test/material/calendar_date_picker_test.dart]:
```suggestion
      // Only the inner Material should have ink features.
```

**Review by huycozy — APPROVED** [review]
@albinpk Thanks for adding a test! LGTM!

Nit: Comments are missing final period/punctuation mark/dot :)

**Comment by albinpk** [comment]
@huycozy I have updated the PR

**Comment by huycozy** [comment]
Looks like golden test was failed. I tried reproducing it locally with `test --update-goldens` but couldn't see any failures. 
@dkwingsmt Can you please take a look at this to push the PR forward?

**Review by dkwingsmt — APPROVED** [review]
LGTM (restamp)

**Comment by dkwingsmt** [comment]
I think the golden failure has nothing to do with the PR. I've updated the PR and let's see how it goes. I'll monitor its submission.

**Comment by dkwingsmt** [comment]
Ok after another look I think the golden file changes are related to this PR, possibly antialias misalignments due to being drawn on a new surface. It's largely negligible anyway. I'll approve it.
