### PR TITLE
Few overscroll glow fixes.

### LINKED ISSUE #4127: Android overscrolls timeout?
I'm not sure if this is expected behavior or not, but if you hold a view overscrolled the overscroll indicator will eventually timeout?  (From https://github.com/flutter/flutter/issues/4126):

flutter_02

### LINKED ISSUE #4169: Glow effect comes back when releasing finger
Find a scrollable on Android.
Scroll such that it glows.
Stop moving without removing your finger.
The glow times out and goes away.
Release your finger.
Bug: The glow briefly comes back.

### PR DESCRIPTION
**Pull request by aghassemi**
Fixes #4169 and also now overscroll indicator is dismissed the moment
user scrolls in the opposite direction (#4603) but the bounce overscroll
that happens behind the scene and is clamped in the indicator is still
problematic and needs to be fixed. However these fixes are orthogonal to that.

Also closes #4127 as I verified the timeout feature (reduced the duration
to 500ms to be closer to Android behaviour)

### CODE REVIEW

File: packages/flutter/lib/src/material/overscroll_indicator.dart [hunk 1]
```diff
@@ -132,7 +132,9 @@ class _OverscrollIndicatorState extends State<OverscrollIndicator> {
   void _hide() {
     _hideTimer?.cancel();
     _hideTimer = null;
-    _extentAnimation.reverse();
+    if (!_extentAnimation.isAnimating) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/overscroll_indicator.dart]: What we're guarding against here is if the indicator is already animating away when _hide is called? I think that his would be a good place for a comment.

File: packages/flutter/lib/src/material/overscroll_indicator.dart [hunk 2]
```diff
@@ -166,6 +171,25 @@ class _OverscrollIndicatorState extends State<OverscrollIndicator> {
     _hide();
   }
 
+  void _refreshHideTimer() {
+    _hideTimer?.cancel();
+    _hideTimer = new Timer(_kIndicatorTimeoutDuration, _hide);
+  }
+
+  bool _isOverscrolling(double scrollOffset) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/overscroll_indicator.dart]: This is just a nit: since you're testing a single value it seems like the method should be called _isOverscroll().

File: packages/flutter/lib/src/material/overscroll_indicator.dart [hunk 3]
```diff
@@ -166,6 +171,25 @@ class _OverscrollIndicatorState extends State<OverscrollIndicator> {
...
+    return (scrollOffset < _minScrollOffset || scrollOffset > _maxScrollOffset) &&
+      ((scrollOffset - _scrollOffset).abs() > kPixelScrollTolerance.distance);
+  }
+
+  bool _isScrollingInOpposite(double scrollOffset) {
+    double delta = _scrollOffset - scrollOffset;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/overscroll_indicator.dart]: Flutter style is to use final here.

File: packages/flutter/lib/src/material/overscroll_indicator.dart [hunk 4]
```diff
@@ -166,6 +171,25 @@ class _OverscrollIndicatorState extends State<OverscrollIndicator> {
...
+    if (scrollOffset < _minScrollOffset) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/overscroll_indicator.dart]: Or  `return scrollOffset < _minScrollOffset ? delta < 0 : delta > 0`

File: packages/flutter/lib/src/material/overscroll_indicator.dart [hunk 5]
```diff
@@ -166,6 +171,25 @@ class _OverscrollIndicatorState extends State<OverscrollIndicator> {
...
+    _hideTimer?.cancel();
+    _hideTimer = new Timer(_kIndicatorTimeoutDuration, _hide);
+  }
+
+  bool _isOverscrolling(double scrollOffset) {
+    return (scrollOffset < _minScrollOffset || scrollOffset > _maxScrollOffset) &&
+      ((scrollOffset - _scrollOffset).abs() > kPixelScrollTolerance.distance);
+  }
+
+  bool _isScrollingInOpposite(double scrollOffset) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/overscroll_indicator.dart]: OK, since I crabbed about the last method: I would have called this _isReverseScroll().

**Comment by HansMuller** [comment]
Thanks for doing this! I only had superficial comments, LGTM.

**Comment by abarth** [comment]
LGTM2

File: packages/flutter/lib/src/material/overscroll_indicator.dart (hunk 4 above)
Comment (aghassemi) [inline packages/flutter/lib/src/material/overscroll_indicator.dart]: Done

File: packages/flutter/lib/src/material/overscroll_indicator.dart (hunk 3 above)
Comment (aghassemi) [inline packages/flutter/lib/src/material/overscroll_indicator.dart]: Done

File: packages/flutter/lib/src/material/overscroll_indicator.dart (hunk 2 above)
Comment (aghassemi) [inline packages/flutter/lib/src/material/overscroll_indicator.dart]: Done.

File: packages/flutter/lib/src/material/overscroll_indicator.dart (hunk 1 above)
Comment (aghassemi) [inline packages/flutter/lib/src/material/overscroll_indicator.dart]: Done.

**Comment by aghassemi** [comment]
Thanks for the review.
