### PR TITLE
Fix DataCell overflows when cell height is large by adding dataRowMinHeight, dataRowMaxHeight props.

### LINKED ISSUE #70510: DataCell overflows with column with multiple text widgets, row height doesn't adjust based on content height
The heights of widgets in a DataTable DataCell can vary:
```
 DataCell(Text('Professor\nProfessor\nProfessor\nProfessor\nProfessor\nProfessor\n'))
```
image

But if you add the data as a Column, the cell overflows. Seems like a bug.
```
 DataRow(
          cells: <DataCell>[
            DataCell(Text('Janine')),
            DataCell(Text('43')),
            DataCell(Column(mainAxisSize: MainAxisSize.min, children: [
              Text("Professor"),
              Text("Professor"),
              Text("Professor"),
              Text("Professor"),
            ])),
            // DataCell(Text('Professor\nProfessor\nProfessor\nProfessor\nProfessor\nProfessor\n')),
          ],
        ),
```
image

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: MyStatelessWidget(),
      ),
    );
  }
}

/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends StatelessWidget {
  MyStatelessWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return DataTable(
      columns: const <DataColumn>[
        DataColumn(
          label: Text(
            'Name',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
        ),
        DataColumn(
          label: Text(
            'Age',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
        ),
        DataColumn(
          label: Text(
            'Role',
            style: TextStyle(fontStyle: FontStyle.italic),
          ),
        ),
      ],
      rows: <DataRow>[
        DataRow(
          cells: <DataCell>[
            DataCell(Text('Sarah')),
            DataCell(Text('19')),
            DataCell(Text('Student')),
          ],
        ),
        DataRow(
          cells: <DataCell>[
            DataCell(Text('Janine')),
            DataCell(Text('43')),
            DataCell(Column(mainAxisSize: MainAxisSize.min, children: [
              Text("Professor"),
              Text("Professor"),
              Text("Professor"),
              Text("Professor"),
            ])),
            // DataCell(Text('Professor\nProfessor\nProfessor\nProfessor\nProfessor\nProfessor\n')),
          ],
        ),
        DataRow(
          cells: <DataCell>[
            DataCell(Text('William')),
            DataCell(Text('27')),
            DataCell(Text('Associate Professor')),
          ],
        ),
      ],
    );
  }
}
```

Happens in the Android emulator.

```
/home/sir/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel unknown, 1.22.0-12.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-12.2.pre at /home/sir/development/flutter
    • Framework revision 2bafdc8226 (7 weeks ago), 2020-09-25 12:48:22 -0700
    • Engine revision f763b5b9b9
    • Dart version 2.10.0 (build 2.10.0-110.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sir/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/sir/soft/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/sir/soft/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.193

• No issues found!
Process finished with exit code 0
```

### PR DESCRIPTION
**Pull request by inouiw**
Fixes `DataTable` and `PaginatedDataTable` overflow in cells when the cell content height is larger than `dataRowHeight`.

The idea is to add support for a content-based data row height in addition to the default fixed data row height.

This fix depreciates the `dataRowHeight` property and instead adds the `dataRowMinHeight` and `dataRowMaxHeight` properties.

There is no breaking change to existing code. If `dataRowHeight` is not set in existing code, then the data row height will be a fixed value equal to `kMinInteractiveDimension`, as before. Similarly, if `dataRowHeight` is set in existing code, then the data row height will be fixed with the provided value, as before. So, users that have `dataRowHeight` explicitly set can switch to `dataRowMinHeight` and `dataRowMaxHeight` when convenient. 

The problem and possible solutions are discussed in the design document at https://flutter.dev/go/allow-datatable-row-height-to-expand. This pull request implements solution 5.

*Screenshot 1 "Before": It is not possible to avoid the overflow error if the content height is large.*
flutter-fix-before

*Screenshot 2 "After": Setting explicit values for `dataRowMinHeight` and `dataRowMaxHeight` makes the cell height content based.*
flutter-fix-after

Example Code
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(),
        home: DataTable(
          dataRowMinHeight: 0, // new property
          dataRowMaxHeight: double.infinity, // new property
          border: TableBorder.all(),
          columns: const <DataColumn>[
            DataColumn(
              label: Text('Testcase', style: TextStyle(fontWeight: FontWeight.bold)),
            ),
            DataColumn(
              label: Text('Testdata', style: TextStyle(fontWeight: FontWeight.bold)),
            ),
          ],
          rows: <DataRow>[
            const DataRow(
              cells: <DataCell>[
                DataCell(Text('Text widget with three lines.')),
                DataCell(Text('Line one.\nLine two.\nLine three.')),
              ],
            ),
            const DataRow(
              cells: <DataCell>[
                DataCell(Text('Text widget with four lines.\n--> Line four should be visible without overflow.')),
                DataCell(Text('Line one.\nLine two.\nLine three.\nLine four.')),
              ],
            ),
            DataRow(
              cells: <DataCell>[
                const DataCell(
                    Text('Column widget containing a Text widget with four lines.\n--> Line four should be visible without overflow.')),
                DataCell(Column(children: const [
                  Text('Line one.\nLine two.\nLine three.\nLine four.'),
                ])),
              ],
            ),
          ],
        ));
  }
}

```

Which issues are fixed by this PR?
- Fixes https://github.com/flutter/flutter/issues/70510

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/data_table.dart [hunk 1]
```diff
@@ -393,7 +393,13 @@ class DataTable extends StatelessWidget {
     this.onSelectAll,
     this.decoration,
     this.dataRowColor,
+    @Deprecated(
+      'This property is no longer used, please use dataRowMinHeight and dataRowMaxHeight instead. '
+      'This feature was deprecated after v3.5.0-10.0.pre.',
+    )
```
Comment (Piinks) [inline packages/flutter/lib/src/material/data_table.dart:399]: This is still being used and is backwards compatible during the deprecation period, can you update all of the notices to reflect that?

```suggestion
    @Deprecated(
      'Migrate to use dataRowMinHeight and dataRowMaxHeight instead. '
      'This feature was deprecated after v3.5.0-10.0.pre.',
    )
```

File: packages/flutter/lib/src/material/data_table.dart [hunk 2]
```diff
@@ -1069,6 +1106,7 @@ class DataTable extends StatelessWidget {
         clipBehavior: clipBehavior,
         child: Table(
           columnWidths: tableColumns.asMap(),
+          defaultVerticalAlignment: TableCellVerticalAlignment.middle,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/data_table.dart:1109]: What does this change do?

File: packages/flutter/lib/src/material/data_table_theme.dart [hunk 3]
```diff
@@ -92,6 +108,8 @@ class DataTableThemeData with Diagnosticable {
     Decoration? decoration,
     MaterialStateProperty<Color?>? dataRowColor,
     double? dataRowHeight,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/data_table_theme.dart:110]: This should be deprecated here as well

File: packages/flutter/lib/src/material/paginated_data_table.dart [hunk 4]
```diff
@@ -94,8 +100,8 @@ class PaginatedDataTable extends StatefulWidget {
        assert(columns.isNotEmpty),
        assert(sortColumnIndex == null || (sortColumnIndex >= 0 && sortColumnIndex < columns.length)),
        assert(sortAscending != null),
-       assert(dataRowHeight != null),
-       assert(headingRowHeight != null),
```
Comment (Piinks) [inline packages/flutter/lib/src/material/paginated_data_table.dart:98]: The assertion for headingRowHeight should stay

File: packages/flutter/lib/src/material/paginated_data_table.dart [hunk 5]
```diff
@@ -158,7 +164,23 @@ class PaginatedDataTable extends StatefulWidget {
...
-  final double dataRowHeight;
+  @Deprecated(
+    'This property is no longer used, please use dataRowMinHeight and dataRowMaxHeight instead. '
+    'This feature was deprecated after v3.5.0-10.0.pre.',
+  )
+  final double? dataRowHeight;
+
+  /// The minimum height of each row (excluding the row that contains column headings).
+  ///
+  /// This value is optional and defaults to kMinInteractiveDimension if not
```
Comment (Piinks) [inline packages/flutter/lib/src/material/paginated_data_table.dart:175]: This should have breadcrumbs here and below

```suggestion
  /// This value is optional and defaults to [kMinInteractiveDimension] if not
```

File: packages/flutter/test/material/data_table_test.dart [hunk 6]
```diff
@@ -627,14 +627,16 @@ void main() {
     Widget buildCustomTable({
       int? sortColumnIndex,
       bool sortAscending = true,
-      double dataRowHeight = 48.0,
```
Comment (Piinks) [inline packages/flutter/test/material/data_table_test.dart:630]: Can we maintain the original tests? While it is deprecated, we should still ensure that the original property works while it is deprecated.

File: packages/flutter/lib/src/material/data_table.dart (hunk 2 above)
Comment (inouiw) [reply packages/flutter/lib/src/material/data_table.dart:1109]: Without the vertical alignment middle, if there is a table with 2 columns and the first column has one row of text and the second column has 10 rows of text then the text in the first column would appear at the top. See https://github.com/flutter/flutter/issues/70510#issuecomment-871105093

Note that the checkbox is in the middle but not the text in the first and second column of the screenshot in the link.

A user suggested https://github.com/flutter/flutter/issues/70510#issuecomment-950496193 to use `defaultVerticalAlignment: TableCellVerticalAlignment.middle` so that the content is always in the middle.

File: packages/flutter/test/material/data_table_test.dart (hunk 6 above)
Comment (inouiw) [reply packages/flutter/test/material/data_table_test.dart:630]: Yes, there is a separate test for dataRowHeight. see line 780 in the changed data_table_test.dart file.

File: packages/flutter/test/material/data_table_theme_test.dart [hunk 7]
```diff
@@ -60,6 +64,8 @@ void main() {
         (Set<MaterialState> states) => const Color(0xfffffff1),
       ),
       dataRowHeight: 51.0,
+      dataRowMinHeight: 41.0,
+      dataRowMaxHeight: 42.0,
```
Comment (Piinks) [inline packages/flutter/test/material/data_table_theme_test.dart:68]:
```suggestion
      dataRowHeight: 51.0,
      dataRowMinHeight: 41.0,
      dataRowMaxHeight: 42.0,
```

These seem to conflict with each other. How can the height be 41<=x<=42, but also x=51? There should be an assert that let's the user know this is not allowed.

File: packages/flutter/lib/src/material/data_table.dart [hunk 8]
```diff
@@ -393,7 +393,13 @@ class DataTable extends StatelessWidget {
     this.onSelectAll,
     this.decoration,
     this.dataRowColor,
+    @Deprecated(
+      'Migrate to use dataRowMinHeight and dataRowMaxHeight instead. '
+      'This feature was deprecated after v3.5.0-10.0.pre.',
+    )
     this.dataRowHeight,
+    this.dataRowMinHeight,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/data_table.dart:401]: Below there should be some asserts that ensure both options (the old and new) aren't used together.

File: packages/flutter/lib/src/material/data_table_theme.dart [hunk 9]
```diff
@@ -40,7 +40,13 @@ class DataTableThemeData with Diagnosticable {
   const DataTableThemeData({
     this.decoration,
     this.dataRowColor,
+    @Deprecated(
+      'Migrate to use dataRowMinHeight and dataRowMaxHeight instead. '
+      'This feature was deprecated after v3.5.0-10.0.pre.',
+    )
     this.dataRowHeight,
+    this.dataRowMinHeight,
```
Comment (Piinks) [inline packages/flutter/lib/src/material/data_table_theme.dart:48]: There should be similar asserts here too.

File: packages/flutter/lib/src/material/paginated_data_table.dart [hunk 10]
```diff
@@ -158,7 +168,23 @@ class PaginatedDataTable extends StatefulWidget {
   ///
   /// This value is optional and defaults to kMinInteractiveDimension if not
   /// specified.
-  final double dataRowHeight;
+  @Deprecated(
+    'Migrate to use dataRowMinHeight and dataRowMaxHeight instead. '
+    'This feature was deprecated after v3.5.0-10.0.pre.',
+  )
+  double? get dataRowHeight => dataRowMinHeight == dataRowMaxHeight ? dataRowMinHeight : null;
```
Comment (Piinks) [inline packages/flutter/lib/src/material/paginated_data_table.dart:175]: Why is this changed to a getter, while in DataTable and DataTableTheme, there is no change?

Comment (inouiw) [reply packages/flutter/lib/src/material/paginated_data_table.dart:175]: When adding the assertions for `PaginatedDataTable` it seemed clear to me that a separate field for `dataRowHeight` was not needed. For `DataTable` it was not so clear because `dataRowHeight` was used in the `_buildDataCell` method. However, thanks to your comment, I tried to make it consistent and it worked.
Please check the added commit.

File: packages/flutter/lib/src/material/data_table_theme.dart [hunk 11]
```diff
@@ -49,7 +55,11 @@ class DataTableThemeData with Diagnosticable {
     this.columnSpacing,
     this.dividerThickness,
     this.checkboxHorizontalMargin,
-  });
+  }) : assert(dataRowMinHeight == null || dataRowMaxHeight == null || dataRowMaxHeight >= dataRowMinHeight),
+       assert(dataRowHeight == null || (dataRowMinHeight == null && dataRowMaxHeight == null),
```
Comment (Piinks) [inline packages/flutter/lib/src/material/data_table_theme.dart:59]: This assertion is causing the Google tests to fail. I need to investigate a bit.

File: packages/flutter/lib/src/material/data_table_theme.dart [hunk 12]
```diff
@@ -127,6 +155,8 @@ class DataTableThemeData with Diagnosticable {
       decoration: Decoration.lerp(a.decoration, b.decoration, t),
       dataRowColor: MaterialStateProperty.lerp<Color?>(a.dataRowColor, b.dataRowColor, t, Color.lerp),
       dataRowHeight: lerpDouble(a.dataRowHeight, b.dataRowHeight, t),
+      dataRowMinHeight: lerpDouble(a.dataRowMinHeight, b.dataRowMinHeight, t),
+      dataRowMaxHeight: lerpDouble(a.dataRowMaxHeight, b.dataRowMaxHeight, t),
```
Comment (Piinks) [inline packages/flutter/lib/src/material/data_table_theme.dart:159]: I think this is where the issue is. This is creating a value for all three, while the assertion only allows one or two to be set.

File: packages/flutter/lib/src/material/data_table_theme.dart [hunk 13]
```diff
@@ -49,7 +55,11 @@ class DataTableThemeData with Diagnosticable {
     this.columnSpacing,
     this.dividerThickness,
     this.checkboxHorizontalMargin,
-  });
+  }) : assert(dataRowMinHeight == null || dataRowMaxHeight == null || dataRowMaxHeight >= dataRowMinHeight),
+       assert(dataRowHeight == null || (dataRowMinHeight == null && dataRowMaxHeight == null),
+         'dataRowHeight must not be set if dataRowMinHeight or dataRowMaxHeight are set.'),
```
Comment (Piinks) [inline packages/flutter/lib/src/material/data_table_theme.dart:60]: Can you add to this assertion message what the values of all 3 are?

File: AUTHORS [hunk 14]
```diff
@@ -100,4 +100,5 @@ Jingyi Chen <jingyichen@link.cuhk.edu.cn>
 Junhua Lin <1075209054@qq.com>
 Tomasz Gucio <tgucio@gmail.com>
 Jason C.H <ctrysbita@outlook.com>
-Hubert Jóźwiak <hjozwiakdx@gmail.com>
\ No newline at end of file
+Hubert Jóźwiak <hjozwiakdx@gmail.com>
+David Neuy <quantjump@gmail.com>
```
Comment (Piinks) [inline AUTHORS:104]: Nit: There should be a newline here at the end of the file

**Review by Piinks — COMMENTED** [review]
Thanks for the update! Let me check the internal tests

File: AUTHORS (hunk 14 above)
Comment (inouiw) [reply AUTHORS]: @Piinks Added thee new line.
All checks pass now :smiley:

**Comment by Piinks** [comment]
I just saw! There must have been a flaky test in the Google testing shard. Let me look this over once more and see if we can get it landed! 🎉

File: packages/flutter/lib/src/material/data_table_theme.dart [hunk 15]
```diff
@@ -49,7 +55,11 @@ class DataTableThemeData with Diagnosticable {
     this.columnSpacing,
     this.dividerThickness,
     this.checkboxHorizontalMargin,
-  });
+  }) : assert(dataRowMinHeight == null || dataRowMaxHeight == null || dataRowMaxHeight >= dataRowMinHeight),
+       assert(dataRowHeight == null || (dataRowMinHeight == null && dataRowMaxHeight == null),
+         'dataRowHeight $dataRowHeight must not be set if dataRowMinHeight $dataRowMinHeight or dataRowMaxHeight $dataRowMaxHeight are set.'),
```
Comment (Piinks) [inline packages/flutter/lib/src/material/data_table_theme.dart:60]:
```suggestion
         'dataRowHeight ($dataRowHeight) must not be set if dataRowMinHeight ($dataRowMinHeight) or dataRowMaxHeight ($dataRowMaxHeight( are set.'),
```

File: packages/flutter/lib/src/material/paginated_data_table.dart [hunk 16]
```diff
@@ -94,8 +100,12 @@ class PaginatedDataTable extends StatefulWidget {
        assert(columns.isNotEmpty),
        assert(sortColumnIndex == null || (sortColumnIndex >= 0 && sortColumnIndex < columns.length)),
        assert(sortAscending != null),
-       assert(dataRowHeight != null),
        assert(headingRowHeight != null),
+       assert(dataRowMinHeight == null || dataRowMaxHeight == null || dataRowMaxHeight >= dataRowMinHeight),
+       assert(dataRowHeight == null || (dataRowMinHeight == null && dataRowMaxHeight == null),
+         'dataRowHeight $dataRowHeight must not be set if dataRowMinHeight $dataRowMinHeight or dataRowMaxHeight $dataRowMaxHeight are set.'),
```
Comment (Piinks) [inline packages/flutter/lib/src/material/paginated_data_table.dart:106]:
```suggestion
         'dataRowHeight ($dataRowHeight) must not be set if dataRowMinHeight ($dataRowMinHeight) or dataRowMaxHeight ($dataRowMaxHeight) are set.'),
```

File: packages/flutter/lib/src/material/data_table.dart [hunk 17]
```diff
@@ -416,6 +422,11 @@ class DataTable extends StatelessWidget {
        assert(!rows.any((DataRow row) => row.cells.length != columns.length)),
        assert(dividerThickness == null || dividerThickness >= 0),
        assert(clipBehavior != null),
+       assert(dataRowMinHeight == null || dataRowMaxHeight == null || dataRowMaxHeight >= dataRowMinHeight),
+       assert(dataRowHeight == null || (dataRowMinHeight == null && dataRowMaxHeight == null),
+         'dataRowHeight $dataRowHeight must not be set if dataRowMinHeight $dataRowMinHeight or dataRowMaxHeight $dataRowMaxHeight are set.'),
```
Comment (Piinks) [inline packages/flutter/lib/src/material/data_table.dart:427]:
```suggestion
         'dataRowHeight ($dataRowHeight) must not be set if dataRowMinHeight ($dataRowMinHeight) or dataRowMaxHeight ($dataRowMaxHeight) are set.'),
```

**Review by Piinks — APPROVED** [review]
This LGTM - thank you for sticking with this!
Flutter_LGTM

I need to find a second approval, I will seek one out!

**Review by Hixie — APPROVED** [review]
LGTM

**Review by Piinks — COMMENTED** [review]
Thanks for your patience @inouiw! I think I resolved the merge conflicts here. Once it is green we can finally merge this! Thanks for contributing!

File: packages/flutter/test/material/data_table_test.dart [hunk 18]
```diff
@@ -726,14 +728,105 @@ void main() {
...
+          ),
+        ],
+        rows: <DataRow>[
+          DataRow(cells: <DataCell>[
+            const DataCell(Text('Data')),
+            DataCell(Column(children: const <Widget>[
+                  Text(multilineText),
+                ])),
+          ]),
+        ],
```
Comment (Piinks) [inline packages/flutter/test/material/data_table_test.dart:766]:
```suggestion
        rows: const <DataRow>[
          DataRow(cells: <DataCell>[
            DataCell(Text('Data')),
            DataCell(Column(children: <Widget>[
                  Text(multilineText),
                ])),
          ]),
        ],
```
