### PR TITLE
Fix RouteAware.didPushNext documentation inaccuracy

### LINKED ISSUE #24594: RouteAware.didPushNext documentation is incorrect
"Called when a new route has been pushed, and the current route is no longer visible."

It's called before the route transition is finished; therefore, the current route is still visible, just obscured. This is an important distinction in some scenarios like one I ran into today where I wanted to do something as soon as the route containing the current widget was no longer visible whatsoever.

### PR DESCRIPTION
**Pull request by ishaquehassan**
The documentation for `RouteAware.didPushNext` incorrectly states that the method is called when "the current route is no longer visible". However, tracing through the source code in `routes.dart` shows that `didPushNext` is called synchronously during the push operation in `RouteObserver.didPush()`, before the transition animation completes. At this point, the current route may still be partially visible as it animates out.

This PR corrects the documentation to accurately describe when `didPushNext` is called and provides guidance for developers who need to perform actions after the route is fully obscured.

This PR implements the analysis from [my earlier comment](https://github.com/flutter/flutter/issues/24594#issuecomment-3980532756) on this issue.

Fixes #24594

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/routes.dart [hunk 1]
```diff
@@ -2525,8 +2525,13 @@ abstract mixin class RouteAware {
...
 
-  /// Called when a new route has been pushed, and the current route is no
-  /// longer visible.
+  /// Called when a new route has been pushed.
+  ///
+  /// Note that this is called during the push operation, before the transition
+  /// animation completes. At this point the current route may still be
+  /// partially visible as it animates out. To perform actions after the route
+  /// is fully obscured, consider using [ModalRoute.animation] to listen for
+  /// animation completion.
```
[the remark this answers is not in the document]
Comment (ishaquehassan) [reply packages/flutter/lib/src/widgets/routes.dart]: Thanks for the suggestion\! I've added a code snippet demonstrating how to use `ModalRoute.animation` with a status listener, as recommended. This should make it clearer for developers how to perform actions after the transition animation fully completes.

File: packages/flutter/lib/src/widgets/routes.dart [hunk 2]
```diff
@@ -2525,8 +2525,21 @@ abstract mixin class RouteAware {
   /// Called when the current route has been popped off.
   void didPop() {}
 
-  /// Called when a new route has been pushed, and the current route is no
-  /// longer visible.
+  /// Called when a new route has been pushed.
```
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/routes.dart]: This will mean didPush and didPushNext have the same API docs preview in RouteAware's documentation, can we somehow differentiate them in the opening line?

File: packages/flutter/lib/src/widgets/routes.dart [hunk 3]
```diff
@@ -2525,8 +2525,21 @@ abstract mixin class RouteAware {
...
+  ///
+  /// This method is called synchronously during the push operation, before the
+  /// transition animation completes. The current route may still be partially
+  /// visible as it animates out. To perform actions after the route is fully
+  /// obscured, consider using [ModalRoute.animation] to listen for animation
+  /// completion, for example:
```
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/routes.dart]: After the route is fully obscured, wouldn't ModalRoute.animation be completed? Should we listen for the secondaryAnimation instead? Asking for clarification.

**Review by victorsanni — COMMENTED** [review]
This PR will need a test exemption, can you request for one on discord?

File: packages/flutter/lib/src/widgets/routes.dart [hunk 4]
```diff
@@ -2525,8 +2525,21 @@ abstract mixin class RouteAware {
...
+  ///
+  /// ```dart
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/routes.dart:2538]: This should use one of the `{@tool...` templates so it is analyzed.

File: packages/flutter/lib/src/widgets/routes.dart (hunk 2 above)
Comment (ishaquehassan) [reply packages/flutter/lib/src/widgets/routes.dart]: Good catch\! Updated the opening line to "Called when a new route has been pushed on top of this route, temporarily obscuring it." which better captures the semantics and distinguishes it from `didPush`.

File: packages/flutter/lib/src/widgets/routes.dart (hunk 3 above)
Comment (ishaquehassan) [reply packages/flutter/lib/src/widgets/routes.dart]: You are right\! ModalRoute.animation is the route's own entrance animation, which is already completed by the time didPushNext fires. The correct one is secondaryAnimation, which is driven by the incoming route and goes from 0 to 1 as the new route transitions in. Updated the snippet to use secondaryAnimation instead.

File: packages/flutter/lib/src/widgets/routes.dart (hunk 4 above)
Comment (ishaquehassan) [reply packages/flutter/lib/src/widgets/routes.dart:2538]: Good point! Wrapped the snippet in `{@tool snippet}` / `{@end-tool}` as required by the Flutter style guide so it gets analyzed by the tooling. Thanks for flagging!

**Review by victorsanni — APPROVED** [review]

**Review by Piinks — APPROVED** [review]
LGTM

**Comment by Piinks** [comment]
I am not sure that updated the base commit, merging in master is not the same as rebasing. But we'll see what the bot thinks. :)
