### PR TITLE
Provide parameter to Icon and IconThemeData for they to consider the context's text scaler

### LINKED ISSUE #115466: Icon widget does not scale with `textScaleFactor`
## Description

The `Icon` widget does not scale with the context's `textScaleFactor`.  I don't know why this happen, considering that, internally, `Icon` is also a text.

Because of this, we had to make a custom icon widget in our project, like:

```dart
class TextScaleAwareIcon extends StatelessWidget {
  // Basically the same API as Icon except for `shouldScaleAccordingToTextScale` [...]

  @override
  Widget build(BuildContext context) {
    final resolvedSize = size ?? IconTheme.of(context).size ?? kDefaultIconSize;
    final iconSize = shouldScaleAccordingToTextScale //
        ? resolvedSize * MediaQuery.of(context).textScaleFactor
        : resolvedSize;

    return Icon(
      icon,
      size: iconSize,
      color: color,
      semanticLabel: semanticLabel,
      textDirection: textDirection,
      shadows: shadows,
    );
  }
}
```

Alternatively, we would have to always multiply the text scale in our icons usage.

```dart
Icon(
  Icons.something,
  size: IconTheme.of(context).size! * MediaQuery.of(context).textScaleFactor,
),
```

We use this widget in about 90% or more of the times we need an icon, because most of the time is what people expect. Example, in a button we expect that the icon of the button scales with the text scale factor.

## Steps to Reproduce

1. Run the following code:

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              TextRow(),
              const SizedBox(height: 16.0),
              MediaQuery(
                data: const MediaQueryData(textScaleFactor: 2.0),
                child: TextRow(),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class TextRow extends StatelessWidget {
  static const fontSize = 14.0;

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Text(
          'Hello, World!',
          style: Theme.of(context)
              .textTheme
              .headline4
              ?.copyWith(fontSize: fontSize),
        ),
        const SizedBox(width: 16.0),
        const Icon(
          Icons.format_color_text,
          size: fontSize,
        ),
      ],
    );
  }
}
```

**Expected results:**

The icon should be scaled just like the text.

**Actual results:**

The icon is not scaled.

image

## Possible solutions

I see some possible solutions to this issue:

1. Change the default behavior, which is breaking and probably won't happen;
1. Provide a new widget like `TextScaleAwareIcon` that would be tha same but considering the text scale;
1. Provide a parameter in the `Icon` widget to make it consider the text scale;
1. Provide a property in the icon theme to make it consider the text scale.

Personally, I think I would go with the theme option, as it would allow us to, for example, change this behavior for an entire tree by wrapping it in a new `IconTheme` that has it enabled.

### PR DESCRIPTION
**Pull request by mateusfccp**
Provide a parameter `applyTextScaling` to both `Icon` and `IconDataTheme`. When `true`, the context's `TextScaler` will apply it's `scale` method to the icon size.

Fixes #115466

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by HansMuller** [comment]
CC @LongCatIsLooong - please take a look at this - TextScaler dependency.

**Review by MitchellGoodwin — APPROVED** [review]
Tentative LGTM, depending on textScaler dependency.

Thank you for putting this together. Apologies that it's slipped through the cracks for so long.

File: packages/flutter/lib/src/cupertino/icon_theme_data.dart [hunk 1]
```diff
@@ -19,6 +19,7 @@ class CupertinoIconThemeData extends IconThemeData with Diagnosticable {
     super.color,
     super.opacity,
     super.shadows,
+    super.considerTextScale,
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/cupertino/icon_theme_data.dart:22]: nit:  `applyTextScaling`?

File: packages/flutter/lib/src/widgets/icon.dart [hunk 2]
```diff
@@ -231,14 +233,30 @@ class Icon extends StatelessWidget {
   /// specified, either directly using this property or using [Directionality].
   final TextDirection? textDirection;
 
+  /// Whether the size is affected by the context's text scaler.
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/icon.dart:236]: maybe: Whether to scale the size of this widget using the ambient `MediaQuery`'s `TextScaler`. ?

File: packages/flutter/lib/src/widgets/icon.dart [hunk 3]
```diff
@@ -231,14 +233,30 @@ class Icon extends StatelessWidget {
...
+  ///
+  /// If true, the icon size is going to be scaled by the [TextScaler] of the
+  /// context's [MediaQuery].
+  ///
+  /// Defaults to the nearest [IconTheme]'s
+  /// [IconThemeData.considerTextScale].
+  final bool? considerTextScale;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/icon.dart:243]: Should this just be `bool`?

File: packages/flutter/lib/src/widgets/icon.dart [hunk 4]
```diff
@@ -231,14 +233,30 @@ class Icon extends StatelessWidget {
...
   Widget build(BuildContext context) {
     assert(this.textDirection != null || debugCheckHasDirectionality(context));
     final TextDirection textDirection = this.textDirection ?? Directionality.of(context);
 
     final IconThemeData iconTheme = IconTheme.of(context);
 
-    final double? iconSize = size ?? iconTheme.size;
+    final bool? considerTextScale = this.considerTextScale ?? iconTheme.considerTextScale;
+
+    final double? tentativeIconSize = size ?? iconTheme.size;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/icon.dart:254]: This should default to 14 when null.

File: packages/flutter/lib/src/widgets/icon.dart [hunk 5]
```diff
@@ -231,14 +233,30 @@ class Icon extends StatelessWidget {
   /// specified, either directly using this property or using [Directionality].
   final TextDirection? textDirection;
 
+  /// Whether the size is affected by the context's text scaler.
+  ///
+  /// If true, the icon size is going to be scaled by the [TextScaler] of the
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/icon.dart:238]: nit: consider adding a sentence or two to describe common use cases / when this parameter can be helpful.

File: packages/flutter/lib/src/widgets/icon.dart (hunk 3 above)
Comment (mateusfccp) [reply packages/flutter/lib/src/widgets/icon.dart:243]: If the passed value is `null`, the value will be obtained through the `context`, while if it's not null the passed value will be used.

File: packages/flutter/lib/src/widgets/icon.dart (hunk 4 above)
Comment (mateusfccp) [reply packages/flutter/lib/src/widgets/icon.dart:254]: Out of curiosity, why?

I can't see anything in the current code that makes it default to `14.0`, so this is essentially a new behavior, isn't it?

File: packages/flutter/lib/src/cupertino/icon_theme_data.dart (hunk 1 above)
Comment (mateusfccp) [reply packages/flutter/lib/src/cupertino/icon_theme_data.dart]: Done

File: packages/flutter/lib/src/widgets/icon.dart (hunk 2 above)
Comment (mateusfccp) [reply packages/flutter/lib/src/widgets/icon.dart]: Done

File: packages/flutter/lib/src/widgets/icon.dart (hunk 5 above)
Comment (mateusfccp) [reply packages/flutter/lib/src/widgets/icon.dart]: Done

File: packages/flutter/lib/src/widgets/icon.dart (hunk 4 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/icon.dart:255]: It's the default font size the text layout libraries use when the font size isn't specified (it currently happens in flutter/engine so you probably won't find that logic in flutter/flutter).

File: packages/flutter/lib/src/widgets/icon.dart [hunk 6]
```diff
@@ -231,14 +233,31 @@ class Icon extends StatelessWidget {
...
     final TextDirection textDirection = this.textDirection ?? Directionality.of(context);
 
     final IconThemeData iconTheme = IconTheme.of(context);
 
-    final double? iconSize = size ?? iconTheme.size;
+    final bool? applyTextScaling = this.applyTextScaling ?? iconTheme.applyTextScaling;
+
+    final double? tentativeIconSize = size ?? iconTheme.size;
+
+    final double? iconSize = switch ((tentativeIconSize, applyTextScaling)) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/icon.dart:257]: If `applyingTextScaling  == null`  then it's treated as if it was set to false. Then why are we allowing setting the value to null in the theme? It doesn't have a different meaning than setting the value to false in the theme right?

Comment (mateusfccp) [reply packages/flutter/lib/src/widgets/icon.dart:257]: Yes. I am actually following the pattern established for other properties of the theme. Take, for instance, `size`. It is also nullable, and the default value (`24.0`) is set in the `fallback()` constructor. Then, in the `Icon` widget, we simply take it as nullable and pass down to the text style.

It happens with all other properties of the theme, so I feel it's reasonable to follow it.

File: packages/flutter/lib/src/widgets/icon.dart (hunk 4 above)
Comment (mateusfccp) [reply packages/flutter/lib/src/widgets/icon.dart:255]: If the engine handles it whey should we specify it now?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/icon.dart:255]: because we are using the font size to scale the icon right? It doesn't make sense to skip scaling because there's no explicitly specified font size.

File: packages/flutter/lib/src/widgets/icon.dart (hunk 6 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/icon.dart:257]: Ah ok makes sense to me. But in that case I think you'll have to change the implementation of a few more methods (`==`, `merge` for example).

Comment (mateusfccp) [reply packages/flutter/lib/src/widgets/icon.dart:257]: `==` already considers `applyTextScaling`.

`merge` was unintentionally left out, so I am going to work on it.

Finally, there's `lerp`, but I am not sure how I should handle it. Should I scale the size within the `lerp` method? Like, for instance, lerping from `(size: 10.0)` to `(size: 10.0, applyTextScaling: true)` with a scale factor of 2.0 will yield a size of 15.0 when `t` is `0.5` or something like this... WDYT?

File: packages/flutter/lib/src/widgets/icon.dart (hunk 4 above)
Comment (mateusfccp) [reply packages/flutter/lib/src/widgets/icon.dart:255]: Hmm, I get what you are saying now... In this case, do we have any way to knowing this value instead of hardcoding it?

I mean, if the engine ever changes its "internal value" from `14.0` to anything else, it's not hard to forget to update it here, so we could potentially and silently introduce a regression here...

File: packages/flutter/lib/src/widgets/icon.dart (hunk 6 above)
Comment (mateusfccp) [reply packages/flutter/lib/src/widgets/icon.dart:257]: I implemented both `merge` and `lerp`. For `lerp`, I looked at how it's done in other themes' `lerp` methods, and all of them simply do `t < 0.5 ? a?.property : b?.property`, so I went with this.

I am a little confused with `isConcrete`, though. I couldn't understand why `shadows` are not considered int it. It's used in two places, and one of them is in `IconTheme.of`:

```dart
  static IconThemeData of(BuildContext context) {
    final IconThemeData iconThemeData = _getInheritedIconThemeData(context).resolve(context);
    return iconThemeData.isConcrete
      ? iconThemeData
      : iconThemeData.copyWith(
        size: iconThemeData.size ?? const IconThemeData.fallback().size,
        fill: iconThemeData.fill ?? const IconThemeData.fallback().fill,
        weight: iconThemeData.weight ?? const IconThemeData.fallback().weight,
        grade: iconThemeData.grade ?? const IconThemeData.fallback().grade,
        opticalSize: iconThemeData.opticalSize ?? const IconThemeData.fallback().opticalSize,
        color: iconThemeData.color ?? const IconThemeData.fallback().color,
        opacity: iconThemeData.opacity ?? const IconThemeData.fallback().opacity,
        shadows: iconThemeData.shadows ?? const IconThemeData.fallback().shadows,
        applyTextScaling: iconThemeData.applyTextScaling ?? const IconThemeData.fallback().applyTextScaling,
      );
  }
```

As `shadows` are not included in `isConcrete`, if all properties are non-null but shadows are null, the fallback shadows won't be passed. I think this is not the intended behavior. (BTW, I implemented the shadow property in `IconTheme`, and not passing it to `isConcrete` was probably because I overlooked it. However, it was later changed to include other properties and purposely left out, as shown by the documentation)

Why is `shadows` not included? What defines what should be included in it or not? And, ultimately, should I include `applyScalingFactor` in it?

File: packages/flutter/lib/src/widgets/icon.dart (hunk 4 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/icon.dart:255]: Yeah good point. There's a private constant defined in `text_painter.dart` and another one in `widget_span.dart`. You could make the text_painter one public and remove the other.

File: packages/flutter/lib/src/widgets/icon.dart (hunk 6 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/icon.dart:257]: Shadow == null means it's off (although it feels a bit strange). So the fallback value of `applyScalingFactor` shouldn't be null (being null typically means it should fall back to the default value).

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/icon.dart:257]: So yes I think should be taken into account by the `isConcrete` implementation.

File: packages/flutter/lib/src/widgets/icon.dart (hunk 4 above)
Comment (mateusfccp) [reply packages/flutter/lib/src/widgets/icon.dart]: Done.

File: packages/flutter/lib/src/widgets/icon.dart (hunk 6 above)
Comment (mateusfccp) [reply packages/flutter/lib/src/widgets/icon.dart]: Done.

**Comment by LongCatIsLooong** [comment]
LGTM, thank you for contributing! The Google testing failure does not look related. I'll sync the branch to retest.

**Review by LongCatIsLooong — APPROVED** [review]
