### PR TITLE
Remove suspicious constant from input decorator layout

### LINKED ISSUE #124852: Textfield vertical alignment center off with outline input border
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

If you have a textfield with an outlineInputBorder and use textAlignVertical.center the textfield baseline is actually off by a few pixels. Sometimes it is just one, but with higher paddings it it can sometimes be a few.

e.g.
isDense: True, Border: OutlineInputBorder, contentPadding: (0, 10, 0, 10); textAlignVertical: center

### Expected results

A centered text

### Actual results

A centered text that is one pixel higher than really centered.

### Code sample

Actual
<details><summary>Code example</summary>

```dartz
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
            child: TextField(
          decoration: InputDecoration(
            border: OutlineInputBorder(),
            contentPadding: EdgeInsets.fromLTRB(0, 10, 0, 10),
            isDense: true,
          ),
          textAlignVertical: TextAlignVertical.center,
        )),
      ),
    );
  }
}
``` 
´
</details> 

Expected

<details><summary>Code example</summary>

```dartz
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
            child: TextField(
          decoration: InputDecoration(
            border: InputBorder.none,
            contentPadding: EdgeInsets.fromLTRB(0, 10, 0, 10),
            isDense: true,
          ),
          textAlignVertical: TextAlignVertical.center,
        )),
      ),
    );
  }
}
``` 
´
</details> 

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Expected
grafik

Actual
grafik

</details>

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
PS D:\Entwicklung\Flutter\flutter_jvx> flutter doctor -v
[√] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.19044.2846], locale de-AT)
    • Flutter version 3.7.10 on channel stable at C:\tools\Flutter\Flutter_aktuell
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (10 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\theiss\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\tools\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\tools\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2846]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.148
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

As you can see, without an `OutlineInputBorder`, the text baseline is correctly centered. Having one suddenly shifts the text upwards by a small amount. Even with `TextAlignVertical.center`.

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Maybe fixes https://github.com/flutter/flutter/issues/124852. @justinmc do you remember what the constant 2 is for when computing the outline baseline?

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/input_decorator_test.dart [hunk 1]
```diff
@@ -2313,17 +2313,17 @@ void runAllTests({ required bool useMaterial3 }) {
...
     //   16 - bottom padding
     // When a border is present, the input text and prefix/suffix are centered
-    // within the input. Here, that will be content of height 106, including 2
-    // extra pixels of space, centered within an input of height 145. That gives
-    // 19 pixels of space on each side of the content, so the prefix is
-    // positioned at 19, and the text is at 19+100-15=104.
+    // within the input. Here, that will be content of height 106, centered
+    // within an input of height 145. That gives 20 pixels of space on each side
+    // of the content, so the prefix is positioned at 19, and the text is at
+    // 20+100-15=104.
```
Comment (justinmc) [inline packages/flutter/test/material/input_decorator_test.dart:2319]: Should be 105.

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

Sadly I don't remember, sorry about that. I really should have explained it in the PR where it was added (https://github.com/flutter/flutter/pull/34859). I say remove it.

It is mysterious that the input_decorator_test comment that you edited mentions 2 pixels, but that comment wasn't added by my PR. Maybe it was just someone trying to match the behavior seen from _layout after my change.
