### PR TITLE
[flutter_tools] Upgrade only from flutter update-packages

### LINKED ISSUE #102781: [flutter_tools] flutter update-packages downgrades package:coverage
See: https://github.com/flutter/flutter/pull/102780/files

package:coverage is being downgraded from 1.2.0 -> 1.0.3.

This is also leading to compilation failures on the PR:
```
packages/flutter_tools/lib/src/test/coverage_collector.dart:26:15: Error: Type 'coverage.HitMap' not found.
  Map<String, coverage.HitMap> _globalHitmap;
              ^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/102781

Previously, `flutter update-packages --force-upgrade` command would:

1. Crawl the flutter/flutter repo, collecting the set of all pub packages depended on
2. Create a synthetic pub package, populated with all the packages from step 1
3. For manually pinned packages, the pinned version would be used; else, each package version would be set to `any`
4. Run `pub get` on the synthetic package, allowing pub to version solve and determine the "best" version solution
5. Backfill the exact versions resolved by pub get on the synthetic packages to the actual pubspec.yaml files in the repo.

The problem with this algorithm is that the "best version solution" algorithm from step 4 that `pub get` uses is a heuristic that can sometimes result in certain packages getting downgraded relative to the previous run (see https://github.com/flutter/flutter/issues/102781#issuecomment-1115850357 for more details).

This PR solves the problem by substituting `>= $prevVersion` for `any` in step 3. This will preclude `pub` from consideration a solution that would downgrade a package.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/update_packages.dart [hunk 1]
```diff
@@ -1321,8 +1321,19 @@ class PubspecDependency extends PubspecLine {
 
   /// This generates the entry for this dependency for the pubspec.yaml for the
   /// fake package that we'll use to get the version numbers figured out.
-  void describeForFakePubspec(StringBuffer dependencies, StringBuffer overrides, { bool useAnyVersion = true}) {
-    final String versionToUse = useAnyVersion || version.isEmpty ? 'any' : version;
+  void describeForFakePubspec(StringBuffer dependencies, StringBuffer overrides, { bool doUpgrade = true }) {
+    final String versionToUse;
+    // This should only happen when manually adding new dependencies; otherwise
+    // versions should always be pinned exactly
+    if (version.isEmpty || version == 'any') {
```
Comment (Jasguerrero) [inline packages/flutter_tools/lib/src/commands/update_packages.dart:1328]: The || is extra it falls under the last else

File: packages/flutter_tools/lib/src/commands/update_packages.dart [hunk 2]
```diff
@@ -1379,13 +1391,14 @@ File _pubspecFor(Directory directory) {
 
 /// Generates the source of a fake pubspec.yaml file given a list of
 /// dependencies.
-String _generateFakePubspec(
+@visibleForTesting
+String generateFakePubspec(
```
Comment (Jasguerrero) [inline packages/flutter_tools/lib/src/commands/update_packages.dart:1395]: I have a general question about private methods. Is it ok to make them public as long as you add the visibleForTesting? Quoting Dan in this [answer](https://stackoverflow.com/questions/21657315/how-to-test-a-private-function-in-dart) "if it's something worth testing, it's something that's worth being public". Regardless of the answer this is a nit/curiosity

**Review by Jasguerrero — APPROVED** [review]
LGTM with the nit

File: packages/flutter_tools/lib/src/commands/update_packages.dart (hunk 1 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/commands/update_packages.dart:1328]: I think if `doUpgrade` is true, and `version = 'any'`, then without the `||`, we could end up with `versionToUse = '>= any'"`. Not sure if `pub` would like that.

File: packages/flutter_tools/lib/src/commands/update_packages.dart [hunk 3]
```diff
@@ -1321,8 +1321,19 @@ class PubspecDependency extends PubspecLine {
 
   /// This generates the entry for this dependency for the pubspec.yaml for the
   /// fake package that we'll use to get the version numbers figured out.
-  void describeForFakePubspec(StringBuffer dependencies, StringBuffer overrides, { bool useAnyVersion = true}) {
-    final String versionToUse = useAnyVersion || version.isEmpty ? 'any' : version;
+  void describeForFakePubspec(StringBuffer dependencies, StringBuffer overrides, { bool doUpgrade = true }) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/commands/update_packages.dart:1324]: Please add some comments describing the behavior with and without `doUpgrade`.

File: packages/flutter_tools/test/commands.shard/hermetic/update_packages_test.dart [hunk 4]
```diff
@@ -173,6 +174,28 @@ void main() {
       ),
     });
   });
+
+  group('generateFakePubspec', () {
+    testUsingContext('constrains package versions to >= previous version if doUpgrade: true', () {
```
Comment (zanderso) [inline packages/flutter_tools/test/commands.shard/hermetic/update_packages_test.dart:179]: Is there already a test that covers the `doUpgrade = false` case?

File: packages/flutter_tools/lib/src/commands/update_packages.dart (hunk 1 above)
Comment (Jasguerrero) [reply packages/flutter_tools/lib/src/commands/update_packages.dart:1328]: Right, then the || is fine

File: packages/flutter_tools/lib/src/commands/update_packages.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/update_packages.dart:1395]: I think it's a nice goal to strive for to only test public methods. However, this command would be incredibly difficult to end to end test. Also, this synthetic package gets created and deleted during the running of the command, so it would not really be practical to test after the command completed (the behavior we're interested in is also dependent on a heuristic algorithm inside the pub binary).

As for making this function public, I couldn't think of a reason we would ever need to call this function (other than in tests) in another library, and if we later do, we can always mark remove the annotation. The main drawback to using `@visibleForTesting` is that it is effectively public to any downstream users who don't gate their code on the analyzer, but we don't have to worry about that with the tool.

File: packages/flutter_tools/lib/src/commands/update_packages.dart (hunk 3 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/update_packages.dart:1324]: Good idea, this file is like black magic...

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/update_packages.dart:1328]: Done

File: packages/flutter_tools/test/commands.shard/hermetic/update_packages_test.dart (hunk 4 above)
Comment (christopherfujino) [reply packages/flutter_tools/test/commands.shard/hermetic/update_packages_test.dart:180]: Added another test case for doUpgrade = false

**Review by zanderso — APPROVED** [review]
