### PR TITLE
[ Tool ] Throw `ToolExit` when asset entries use absolute paths

### LINKED ISSUE #173405: [tool_crash] ArgumentError: Invalid argument(s): Uri c:/hiyad_app/fonts/times must have scheme 'file:'.
## Command
```sh
flutter --quiet assemble --no-version-check --depfile C:\flutter_projects\new_hiyad_app\build\app\intermediates\flutter\debug/flutter_build.d --output C:\flutter_projects\new_hiyad_app\build\app\intermediates\flutter\debug -dTargetFile=C:\flutter_projects\new_hiyad_app\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=RkxVVFRFUl9WRVJTSU9OPTMuMzIuOA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049ZWRhZGE3YzU2ZQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049ZWYwY2QwMDA5MQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My44LjE= -dFlavor= -dAndroidArchs=android-arm64 -dMinSdkVersion=21 debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Uri c:/hiyad_app/fonts/times must have scheme 'file:'.
```console
#0      WindowsStyle.pathFromUri (package:path/src/style/windows.dart:86:7)
#1      Context.fromUri (package:path/src/context.dart:1040:40)
#2      ManifestAssetBundle._resolveAsset (package:flutter_tools/src/asset.dart:1182:47)
#3      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:965:34)
#4      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:297:54)
<asynchronous suspension>
#5      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:51:26)
<asynchronous suspension>
#6      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:73:34)
<asynchronous suspension>
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:873:9)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:629:16)
<asynchronous suspension>
#9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:346:32)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1563:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:494:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
```
```console
[✓] Flutter (Channel stable, 3.32.8, on Microsoft Windows [Version 10.0.26100.4770], locale en-AE) [1,430ms]
    • Flutter version 3.32.8 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision edada7c56e (13 days ago), 2025-07-25 14:08:03 +0000
    • Engine revision ef0cd00091
    • Dart version 3.8.1
    • DevTools version 2.45.1

[✓] Windows Version (11 Home 64-bit, 24H2, 2009) [2.7s]

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [5.0s]
    • Android SDK at C:\Users\mesal\AppData\Local\Android\sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)
    • All Android licenses accepted.

[✓] Chrome - develop for the web [638ms]
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps [634ms]
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2025.1.2) [40ms]
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13391695-b895.109)

[✓] VS Code (version 1.102.3) [35ms]
    • VS Code at C:\Users\mesal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.116.0

[✓] Connected device (4 available) [564ms]
    • SM A065F (mobile) • R83XC093WNR • android-arm64  • Android 14 (API 34)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.26100.4770]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 139.0.7258.67
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 138.0.3351.121

[✓] Network resources [1,196ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: edada7c56edf4a183c1735310e123c7f923584f1

### PR DESCRIPTION
**Pull request by bkonyi**
Our documentation states that "the value of an asset is a relative path from the pubspec.yaml file", but this was never actually verified by the tool. On systems with POSIX semantics, this would simply result in invalid asset paths being built, but on Windows this could cause an exception to be thrown as the built URI would not be a valid `file://` URI.

This change adds checks to ensure that asset paths are relative and that they are valid file paths.

Fixes https://github.com/flutter/flutter/issues/173405

### CODE REVIEW

File: packages/flutter_tools/lib/src/asset.dart [hunk 1]
```diff
@@ -1182,6 +1175,27 @@ class ManifestAssetBundle implements AssetBundle {
     throwToolExit(errorMessage.toString());
   }
 
+  void ensureAssetPathIsValid({required String assetsBaseDir, required Uri assetUri}) {
```
Comment (matanlurey) [inline packages/flutter_tools/lib/src/asset.dart]: If this is only used in this class, let's make it private.

File: packages/flutter_tools/lib/src/asset.dart [hunk 2]
```diff
@@ -1182,6 +1175,27 @@ class ManifestAssetBundle implements AssetBundle {
...
+        'directory path. Please update this entry in the pubspec.yaml to point to a valid file '
+        'path.',
+      );
+    }
+    if (Uri.directory(
+          assetsBaseDir,
+          windows: _platform.isWindows,
+        ).resolveUri(assetUri).toFilePath(windows: _platform.isWindows) ==
+        assetUri.toFilePath(windows: _platform.isWindows)) {
+      throwToolExit(
```
Comment (matanlurey) [inline packages/flutter_tools/lib/src/asset.dart:1191]: I'm supportive of this change, but I do wonder if it ends up being a breaking change in practice and we could consider relaxing this (making it a warning) for a single release before making it a hard error.

On the other hand if it's very corner-casey, and we don't expect it was used much (or much intentionally), no problem doing this IMO.

**Review by matanlurey — COMMENTED** [review]
Overall LGTM. One question, one nit

File: packages/flutter_tools/lib/src/asset.dart (hunk 2 above)
Comment (bkonyi) [reply packages/flutter_tools/lib/src/asset.dart:1191]: I don't think this ever actually worked, it was just surfaced as a different error.

We basically take the base directory (the directory that contains the pubspec.yaml) and then do a path join with the asset path from the pubspec. Absolute asset paths on Windows would have never worked due to the presence of a drive letter in the path, and would result in an asset not found error on POSIX file systems. There may be a couple of edge cases where this did happen to work, but I'd consider that a bug.

The exception message gives actionable feedback on how to fix this issue, and the fix is "relative"-ly simple, so I think it's worth just landing this as-is.

**Review by matanlurey — APPROVED** [review]
LGTM!
