### PR TITLE
Text field height fix

### LINKED ISSUE #46160: TextField decoration InputDecoration.collapsed has extra padding in new flutter versions.
Currently running on the latest beta branch while waiting on some of the fixes to enter stable. Beta v1.10.7 has the working format/padding our app has always had for our TextField InputDecoration.collapsed. 

In the newer beta versions it has extra padding. I've tried adjusting the padding and was able to remove some of it by adjusting the container. I also tried an InputBorder with contentPadding as well, but ultimately I cannot make my original TextField in the new version.

image

In the latest beta version it looks like this:

image

Code for the TextField below..

```
Container(
                  constraints: BoxConstraints(minHeight: 32.0, maxHeight: 108.0),
                  margin: EdgeInsets.symmetric(vertical: 6.0),
                  padding: EdgeInsets.symmetric(vertical: 6.0, horizontal: 4.0),
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.grey[300]),
                    borderRadius: BorderRadius.circular(12.0),
                    shape: BoxShape.rectangle,
                  ),
                  child: TextField(
                    textCapitalization: TextCapitalization.sentences,
                    style: TextStyle(color: Colors.black, fontSize: 16.0),
                    controller: textEditingController,
                    decoration: InputDecoration.collapsed(
                      hintText: 'Type your message...',
                      hintStyle: TextStyle(color: Colors.grey),
                    ),
                    maxLines: null,
                  ),
                ),
```

### PR DESCRIPTION
**Pull request by justinmc**
## Description

A regression was introduced in https://github.com/flutter/flutter/pull/42449 where inputs with `InputDecoration.collapsed` were forced to have a height of at least `kMinInteractiveDimension`.  There was also a lot of confusion around `collapsed`, `isDense`, and `contentPadding`, as explained well in [this issue comment](https://github.com/flutter/flutter/issues/46160#issuecomment-596245331).  This PR fixes the regression ~~and deals with the confusion by respecting `contentPadding` whenever it is passed in, regardless of whether `isDense` or `collapsed` were used.~~ I've simplified the solution to simply allow small heights when `isCollapsed` is true due to breakages with the original solution.

## Related Issues

Closes https://github.com/flutter/flutter/issues/46160

## Tests

 * I updated a few expectations of minimum height for a collapsed field.
 * I added a test to show that contentPadding is not respected when isDense and isCollapsed are not set.

### CODE REVIEW

**Comment by justinmc** [comment]
@HansMuller This makes an attempt at improving our problems with collapsed and isDense (while fixing a [regression](https://github.com/flutter/flutter/issues/46160)).  The idea is to reduce confusion by always respecting contentPadding when it's given and not depending on isDense.  I left a [comment on the issue](https://github.com/flutter/flutter/issues/46160#issuecomment-620899412) that summarizes the background of this problem.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -1075,20 +1104,20 @@ class _RenderDecoration extends RenderBox {
       + contentPadding.bottom
       + densityOffset.dy,
     );
-    final double minContainerHeight = decoration.isDense || expands
-      ? 0.0
-      : kMinInteractiveDimension + densityOffset.dy;
+    final double minContainerHeight = decoration.isDense
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/input_decorator.dart:1107]: This expression and the following one might be a little easier to read if allowed the lines to get a little wider.  Doing it this way makes the similarity of these statements easier to see.
```dart
final double minContainerHeight =  expands || decoration.isDense || decoration.contentPadding != null
  ? 0.0
  : kMinInteractiveDimension + densityOffset.dy;
```

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 2]
```diff
@@ -1075,20 +1104,20 @@ class _RenderDecoration extends RenderBox {
...
+    final double interactiveAdjustment = minContainerHeight > contentHeight
+       && decoration.contentPadding == null
+            ? (minContainerHeight - contentHeight) / 2.0
+            : 0.0;
     final double maxContainerHeight = boxConstraints.maxHeight - bottomHeight + densityOffset.dy;
     final double containerHeight = expands
       ? maxContainerHeight
       : math.min(math.max(contentHeight, minContainerHeight), maxContainerHeight);
 
-    // Ensure the text is vertically centered in cases where the content is
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/input_decorator.dart:1086]: Do we really want to lose this comment?

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 3]
```diff
@@ -2312,38 +2341,16 @@ class _InputDecoratorState extends State<InputDecorator> with TickerProviderStat
...
-          : const EdgeInsets.fromLTRB(0.0, 12.0, 0.0, 12.0));
-      }
-    } else {
-      floatingLabelHeight = 0.0;
-      contentPadding = decorationContentPadding ?? (decorationIsDense
-        ? const EdgeInsets.fromLTRB(12.0, 20.0, 12.0, 12.0)
-        : const EdgeInsets.fromLTRB(12.0, 24.0, 12.0, 16.0));
-    }
+    final double floatingLabelHeight = !decoration.isCollapsed && !border.isOutline
+        // 4.0: the vertical gap between the inline elements and the floating label.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/input_decorator.dart:2345]: two space indent

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by justinmc** [comment]
@HansMuller Ready for re-review.  I did a much simplified solution by just considering isCollapsed remove the minimum height, as we discussed. It fixes the regression.

I'm checking the internal tests now.

**Comment by justinmc** [comment]
Seems like this doesn't cause any failures on internal tests.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 4]
```diff
@@ -3320,6 +3320,7 @@ class InputDecoration {
     int errorMaxLines,
     bool hasFloatingPlaceholder,
     FloatingLabelBehavior floatingLabelBehavior,
+    bool isCollapsed,
```
Comment (aaronvargas) [inline packages/flutter/lib/src/material/input_decorator.dart:3323]: The doc comment is no longer accurate.

Comment (justinmc) [reply packages/flutter/lib/src/material/input_decorator.dart:3321]: Thanks for catching that!  It makes me worry about people relying on the old behavior, though I think technically it's not a breaking change.  I wonder why isCollapsed was not passed through in the first place.

File: packages/flutter/test/material/input_decorator_test.dart [hunk 5]
```diff
@@ -2630,6 +2629,31 @@ void main() {
     expect(getBorderWeight(tester), 1.0);
   });
 
+  testWidgets('contentPadding smaller than kMinInteractiveDimension', (WidgetTester tester) async {
+    const double verticalPadding = 1.0;
```
Comment (HansMuller) [inline packages/flutter/test/material/input_decorator_test.dart:2633]: Please insert
// Regression test for https://github.com/flutter/flutter/pull/42449

File: packages/flutter/test/material/input_decorator_test.dart [hunk 6]
```diff
@@ -2630,6 +2629,31 @@ void main() {
...
+    // Overall height should be 18dps, but the min is kMinInteractiveDimension
+    // when isDense and isCollapsed are false.
+    //   16 - input text (ahem font size 16dps)
+    //    2 - total vertical padding
+
+    expect(tester.getSize(find.byType(InputDecorator)), const Size(800.0, kMinInteractiveDimension));
+    expect(tester.getSize(find.text('text')).height, 16.0);
+    expect(tester.getTopLeft(find.text('text')).dy, 16.0);
+    expect(getOpacity(tester, 'hint'), 0.0);
+    expect(getBorderWeight(tester), 1.0);
```
Comment (HansMuller) [inline packages/flutter/test/material/input_decorator_test.dart:2654]: For the sake of clarity, it would be nice to include a second part to this test that verifies that the height _is_ 18 when collapsed is true. And a third part, same thing for isDense.

**Review by HansMuller — APPROVED** [review]
LGTM
