### PR TITLE
fix a DraggableScrollableSheet bug

### LINKED ISSUE #89214: DraggableScrollableSheet throws exception when navigating back before animation completes
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the main.dart as follows: ... 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'DSS Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('DSS Test'),
      ),
      body: Center(
        child: ElevatedButton(
          child: Text('Navigate to DSS test page'),
          onPressed: () {
            Navigator.of(context).push(MaterialPageRoute(
              builder: (context) => DssTestPage(),
            ));
          },
        ),
      ),
    );
  }
}

class DssTestPage extends StatelessWidget {
  const DssTestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('DSS Test'),
      ),
      body: DraggableScrollableSheet(
        initialChildSize: 0.2,
        minChildSize: 0.2,
        maxChildSize: 1.0,
        builder: (context, scrollController) => SingleChildScrollView(
          controller: scrollController,
          child: Container(
            height: 1000,
            color: Colors.blue,
          ),
        ),
      ),
    );
  }
}
``` 
	
</details>

3. Click on the button, then move the DraggableScrollableSheet and before it's done moving click on the back button in the app bar.

**Expected results:** 
The application should navigate back to the page with the button in the center.

**Actual results:** 
After navigating back to the previous page the application fails an assertion and throws a "Null check operator used on a null value" error.

The error is caused by `context.notificationContext` being null in `draggable_scrollable_sheet.dart` line 488.

<details>
  <summary>Logs</summary>

```
[+1099 ms] 
                    ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
                    The following assertion was thrown while finalizing the widget tree:
                    ScrollableState#a1fa7(tickers: tracking 1 ticker, position:
                    _DraggableScrollableSheetScrollPosition#0fb9f(offset: 0.0, range: -1.0..157.7, viewport: 843.3,
                    ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, null,
                    ScrollDirection.idle), effective physics: ClampingScrollPhysics -> RangeMaintainingScrollPhysics)
                    was disposed with an active Ticker.
                    ScrollableState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was
                    called on the mixin, that Ticker was still active. All Tickers must be disposed before calling
                    super.dispose().
                    Tickers used by AnimationControllers should be disposed by calling dispose() on the
                    AnimationController itself. Otherwise, the ticker will leak.
                    The offending ticker was:
                      _WidgetTicker(created by ScrollableState#a1fa7(tickers: tracking 0 tickers, position:
                      _DraggableScrollableSheetScrollPosition#0fb9f(offset: 0.0, range: -1.0..731.1, viewport: 269.9,
                      ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics,
                      DragScrollActivity#d128d(ScrollDragController#0bbb2), ScrollDirection.idle), effective physics:
                      ClampingScrollPhysics -> RangeMaintainingScrollPhysics))
                      The stack trace when the _WidgetTicker was actually created was:
                      #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
                      #1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
                      #2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:271:81)
                      #3      TickerProviderStateMixin.createTicker
                      (package:flutter/src/widgets/ticker_provider.dart:202:34)
                      #4      new AnimationController.unbounded
                      (package:flutter/src/animation/animation_controller.dart:280:21)
                      #5      _DraggableScrollableSheetScrollPosition.goBallistic
                      (package:flutter/src/widgets/draggable_scrollable_sheet.dart:480:73)
                      #6      ScrollDragController.end (package:flutter/src/widgets/scroll_activity.dart:412:14)
                      #7      ScrollableState._handleDragEnd (package:flutter/src/widgets/scrollable.dart:652:12)
                      #8      DragGestureRecognizer._checkEnd.<anonymous closure>
                      (package:flutter/src/gestures/monodrag.dart:473:47)
                      #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
                      #10     DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:473:5)
                      #11     DragGestureRecognizer.didStopTrackingLastPointer
                      (package:flutter/src/gestures/monodrag.dart:380:9)
                      #12     OneSequenceGestureRecognizer.stopTrackingPointer
                      (package:flutter/src/gestures/recognizer.dart:341:9)
                      #13     DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:389:5)
                      #14     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:312:7)
                      #15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
                      #16     PointerRouter._dispatchEventToRoutes.<anonymous closure>
                      (package:flutter/src/gestures/pointer_router.dart:138:9)
                      #17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
                      #18     PointerRouter._dispatchEventToRoutes
                      (package:flutter/src/gestures/pointer_router.dart:136:18)
                      #19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
                      #20     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
                      #21     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
                      #22     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
                      #23     GestureBinding._handlePointerEventImmediately
                      (package:flutter/src/gestures/binding.dart:374:7)
                      #24     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
                      #25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
                      #26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
                      #30     _invoke1 (dart:ui/hooks.dart:182:10)
                      #31     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
                      #32     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
                      (elided 3 frames from dart:async)

                    When the exception was thrown, this was the stack:
                    #0      TickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:219:13)
                    #1      TickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:237:6)
                    #2      RestorationMixin.dispose (package:flutter/src/widgets/restoration.dart:1080:11)
                    #3      ScrollableState.dispose (package:flutter/src/widgets/scrollable.dart:512:11)
                    #4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4800:11)
                    #5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1847:13)
                    #6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #16     _LayoutBuilderElement.visitChildren (package:flutter/src/widgets/layout_builder.dart:71:14)
                    #17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #31     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6185:16)
                    #32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #43     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #49     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #63     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #65     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #66     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #67     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #68     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #69     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #71     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #72     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #73     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #74     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #75     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #76     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #79     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #80     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #81     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #82     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #83     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #84     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #85     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #86     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #87     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #88     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #89     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #90     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #91     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #92     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #93     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #94     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #95     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #96     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #97     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #98     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #99     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #100    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #101    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #102    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #103    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #104    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #105    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #106    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #107    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #108    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #109    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #110    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #111    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #113    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #114    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #115    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #116    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #117    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #118    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #119    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #120    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #121    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #122    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #123    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #124    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #125    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #126    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #127    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #128    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #129    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #130    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #131    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #132    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #133    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #134    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #135    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #136    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #137    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #138    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #139    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #140    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #141    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #142    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                    #143    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #144    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #145    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #146    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #147    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #148    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #149    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #150    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                    #151    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                    #152    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                    #153    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
                    #154    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1856:25)
                    #155    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2840:27)
                    #156    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2473:15)
                    #157    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2839:7)
                    #158    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:877:19)
                    #159    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
                    #160    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
                    #161    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
                    #162    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
                    #166    _invoke (dart:ui/hooks.dart:163:10)
                    #167    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
                    #168    _drawFrame (dart:ui/hooks.dart:126:31)
                    (elided 3 frames from dart:async)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +96 ms] 
           Another exception was thrown: Null check operator used on a null value
```

```
Analyzing dss_bug...
No issues found! (ran in 3.6s)
```

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)
    • Flutter version 2.2.3 at C:\Users\adne\flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\adne\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\adne\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • GM1913 (mobile) • f356c12a • android-arm64  • Android 10 (API 29)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)      • edge     • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes #89214

We should release the animation controller before the scrollable widget dispose.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 1]
```diff
@@ -466,6 +466,15 @@ class _DraggableScrollableSheetScrollPosition
     }
   }
 
+  @override
+  void dispose() {
+    if (_ballisticCancelCallback != null) {
+      // Stop the animation before dispose.
+      _ballisticCancelCallback!.call();
+    }
```
Comment (nt4f04uNd) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:474]:
```suggestion
    // Stop the animation before dispose.
    _ballisticCancelCallback?.call();
```

**Review by goderbauer — APPROVED** [review]
LGTM
