### PR TITLE
Fix cursor on hover expand/collapse icon (#155207)

### LINKED ISSUE #155207: ExpansionPanel mouse cursor changes when hovering the expand/collapse icon when ExpansionPanel.canTapOnHeader is true
### Steps to reproduce

Set ExpansionPanel.canTapOnHeader = true, then hover over the ExpansionPanel header on web, the mouse cursor will change from the "hand" to the usual mouse arrow shape while hovering over the expand/collapse icon.

I did a fix for another issue in [147098](https://github.com/flutter/flutter/pull/147098), that would have fixed this, but @TahaTesser removed the `IgnorePointer` and fixed that issue in another way, however that has resulted in this bug. Disabling the Expand/collapse IconButton when canTapOnHeader is true, and trying to put a band-aid on it like changing the disabled color was never going to be a good solution due to all the undesirable side effects that entails, and it has been the cause of multiple user experience bugs. IgnorePointer will need to be used in the end anyway. 

What do we think IgnorePointer was made for? Here is the example in the docs:

The following sample has an [IgnorePointer](https://api.flutter.dev/flutter/widgets/IgnorePointer-class.html) widget wrapping the Column which contains a button. When [ignoring](https://api.flutter.dev/flutter/widgets/IgnorePointer/ignoring.html) is set to true anything inside the Column can not be tapped. When [ignoring](https://api.flutter.dev/flutter/widgets/IgnorePointer/ignoring.html) is set to false anything inside the Column can be tapped.

### Expected results

The mouse cursor is always the hand on the whole ExpansionPanel header. 

### Actual results

The mouse cursor changes from the "hand" to the usual mouse arrow shape while hovering over the expand/collapse icon.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [ExpansionPanelList].

void main() => runApp(const ExpansionPanelListExampleApp());

class ExpansionPanelListExampleApp extends StatelessWidget {
  const ExpansionPanelListExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('ExpansionPanelList Sample')),
        body: const ExpansionPanelListExample(),
      ),
    );
  }
}

// stores ExpansionPanel state information
class Item {
  Item({
    required this.expandedValue,
    required this.headerValue,
    required this.value,
    required this.canTapOnHeader,
  });

  String expandedValue;
  String headerValue;
  int value;
  bool canTapOnHeader;
}

List<Item> generateItems(int numberOfItems) {
  return List<Item>.generate(numberOfItems, (int index) {
    bool canTapOnHeader = index > 3;
    return Item(
      headerValue: 'Panel $index canTapOnHeader=${canTapOnHeader.toString()}',
      expandedValue: 'This is item number $index',
      value: index,
      canTapOnHeader: canTapOnHeader,
    );
  });
}

class ExpansionPanelListExample extends StatefulWidget {
  const ExpansionPanelListExample({super.key});

  @override
  State<ExpansionPanelListExample> createState() =>
      _ExpansionPanelListExampleState();
}

class _ExpansionPanelListExampleState extends State<ExpansionPanelListExample> {
  final List<Item> _data = generateItems(8);

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Container(
        child: _buildPanel(),
      ),
    );
  }

  Widget _buildPanel() {
    return ExpansionPanelList.radio(
      children: _data.map<ExpansionPanelRadio>((Item item) {
        return ExpansionPanelRadio(
          headerBuilder: (BuildContext context, bool isExpanded) {
            return ListTile(
              title: Text(item.headerValue),
            );
          },
          body: ListTile(
              title: Text(item.expandedValue),
          ),
          value: item.value,
          canTapOnHeader: item.canTapOnHeader,
        );
      }).toList(),
      expandIconColor: Colors.red,
    );
  }
}
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.2.1)
[✓] VS Code (version 1.93.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by benji-farquhar**
Fixes [#155207](https://github.com/flutter/flutter/issues/155207).

When ExpansionPanel.canTapOnHeader is true, the cursor doesn't change to a pointer when hovering over the expand/collapse icon, because hover events are blocked.

This PR adds IgnorePointer wrapping to resolve the hover cursor behavior while maintaining the correct tap handling.

### CODE REVIEW

File: packages/flutter/lib/src/material/expansion_panel.dart [hunk 1]
```diff
@@ -391,7 +391,9 @@ class _ExpansionPanelListState extends State<ExpansionPanelList> {
 
       Widget expandIconPadded = Padding(
         padding: const EdgeInsetsDirectional.only(end: 8.0),
-        child: ExpandIcon(
+        child: IgnorePointer(
+          ignoring: child.canTapOnHeader,
+          child: ExpandIcon(
           color: widget.expandIconColor,
           disabledColor: child.canTapOnHeader ? widget.expandIconColor : null,
           isExpanded: _isChildExpanded(index),
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/material/expansion_panel.dart:399]: Lines 397-405 should be indented, now that the `ExpandIcon` is wrapped with the `IgnorePointer` widget.

**Review by nate-thegrate — COMMENTED** [review]
> Set ExpansionPanel.canTapOnHeader = true, then hover over the ExpansionPanel header on web, the mouse cursor will change from the "hand" to the usual mouse arrow shape while hovering over the expand/collapse icon.

It would be great if we had a test for this! That way, it won't be possible to factor out the `IgnorePointer` widget in the future without breaking the test.

Since adding an `IgnorePointer` is a semantic change to the widget tree, this PR will need tests in order to be approved. (Feel free to take a look at the [Tree Hygiene](https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests) wiki page to see which types of changes do/don't qualify for test exemptions.)

<br><br>

> Fix undesirable side effects of your refactor away from my solution during your code review of my PR

Flutter has a very strict [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md); disrespecting someone else's work is not tolerated.

I often struggle to find ways to get my point across while maintaining respect & dignity, especially when I feel that the other person is in the wrong. But at the same time, I'm also amazed by everything the Flutter team has been able to do so far. Overall, I think it's important to recognize & appreciate the valuable contributions that others make, rather than drawing attention to mistakes & shortcomings.

<br><br>

Let me know if you have any questions or additional thoughts!

**Comment by BenjiFarquhar** [comment]
@nate-thegrate Can't get master to compile. It doesn't recognise `Color.a`

**Comment by nate-thegrate** [comment]
Yeah, that was a recent change to the `dart:ui` library.

Should be resolved by following the instructions here: https://github.com/flutter/flutter/blob/main/docs/contributing/Setting-up-the-Framework-development-environment.md

**Comment by Piinks** [comment]
Hey @BenjiFarquhar do you plan to continue working on this change?

**Comment by BenjiFarquhar** [comment]
> Hey @BenjiFarquhar do you plan to continue working on this change?

Hey @Piinks, I'd appreciate if someone can add a test for this. I may be able to do it soon if there are no takers.

**Comment by nate-thegrate** [comment]
Yeah, if you'd be able to add the test at some point that'd be great!

I believe generally, test changes are up to the PR author. If you're not able to get around to it, we can close this pull request and keep https://github.com/flutter/flutter/issues/155207 open, and we'll see if anyone decides to pick it up!

**Review by nate-thegrate — APPROVED** [review]
LGTM, thanks for following up with the test!

(feel free to take a look at a few optional suggestions below.)

**Comment by nate-thegrate** [comment]
Oh dang—looks like this change has caused some ExpansionPanel tests to fail…

sadly we cannot merge this until all checks succeed 😞

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 2]
```diff
@@ -2048,16 +2046,19 @@ void main() {
 
     await tester.pumpWidget(buildWidget());
 
-    await tester.tap(find.text('Panel'));
-    await tester.pumpAndSettle();
+    final Finder expansionPanelListFinder = find.byType(ExpansionPanelList);
+    final Finder ignorePointerFinder = find.descendant(
+      of: expansionPanelListFinder,
+      matching: find.byType(IgnorePointer),
+    );
```
[the remark this answers is not in the document]
Comment (nate-thegrate) [reply packages/flutter/test/material/expansion_panel_test.dart:2053]: (Just going to resolve these, since making checks pass is quite a bit more important)

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 3]
```diff
@@ -2024,14 +2024,12 @@ void main() {
     expect(inkWell.highlightColor, expectedHighlightColor);
   });
 
-  testWidgets('ExpandIcon.disabledColor uses expandIconColor color when canTapOnHeader is true', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/material/expansion_panel_test.dart:2027]: Is there a reason why this test for the disabled color is being removed?

Comment (BenjiFarquhar) [reply packages/flutter/test/material/expansion_panel_test.dart:2027]: @Piinks That test was for the original fix for this issue that broke the mouse pointer. I removed that fix, and fixed it a different way, so the old test is redundant.

File: packages/flutter/lib/src/material/expansion_panel.dart [hunk 4]
```diff
@@ -400,7 +400,9 @@ class _ExpansionPanelListState extends State<ExpansionPanelList> {
             padding: _kExpandIconPadding,
             splashColor: child.splashColor,
             highlightColor: child.highlightColor,
-            onPressed: (bool isExpanded) => _handlePressed(isExpanded, index),
+            onPressed: !child.canTapOnHeader
```
Comment (BenjiFarquhar) [inline packages/flutter/lib/src/material/expansion_panel.dart:403]: @nate-thegrate How come we are back to using disabled color and disabling the button?

Comment (nate-thegrate) [reply packages/flutter/lib/src/material/expansion_panel.dart:403]: The change unfortunately was causing a few different tests to fail: https://github.com/flutter/flutter/runs/32046612820

I wanted to see if reverting would fix it 😄

Comment (BenjiFarquhar) [reply packages/flutter/lib/src/material/expansion_panel.dart:403]: @nate-thegrate I will looking into a fix for the test that addresses the semantic issue but keeps the original fix. This change is kinda going back to what was causing the issue, just not really showing the issue because of the behaviour of IgnorePointer.

Comment (nate-thegrate) [reply packages/flutter/lib/src/material/expansion_panel.dart:403]: Fair point.

I can revert the recent changes, and from there you could figure out how to fix the failing checks.
Would you like me to do that?

**Comment by BenjiFarquhar** [comment]
@nate-thegrate Should be all good now. I think the test was saying the expansion panel header is in an enabled state, and the semantics represent this with the `isEnabled` flag. Adding `isEnabled: true` to the expansion panel header semantics test made it happy. Let me know if you have any changes or are not sure about my test fix.

File: packages/flutter/test/material/expansion_panel_test.dart [hunk 5]
```diff
@@ -2048,16 +2046,19 @@ void main() {
...
+    final Finder expansionPanelListFinder = find.byType(ExpansionPanelList);
+    final Finder ignorePointerFinder = find.descendant(
+      of: expansionPanelListFinder,
+      matching: find.byType(IgnorePointer),
+    );
 
-    ExpandIcon expandIcon = tester.widget(find.byType(ExpandIcon));
-    expect(expandIcon.disabledColor, isNull);
+    final IgnorePointer ignorePointerFalse = tester.widget(ignorePointerFinder.first);
+    expect(ignorePointerFalse.ignoring, isFalse);
```
[the remark this answers is not in the document]
Comment (nate-thegrate) [reply packages/flutter/test/material/expansion_panel_test.dart:2058]: Never mind about this one—the type argument would be necessary here, so at that point it's not a whole lot of improved readability.

**Review by nate-thegrate — APPROVED** [review]
This looks fantastic, thank you @BenjiFarquhar!

I'll unresolve [1 thread](https://github.com/flutter/flutter/pull/155209#discussion_r1816001503) with an optional suggestion but otherwise I got nothing 🙂

File: packages/flutter/test/material/expansion_panel_test.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (BenjiFarquhar) [reply packages/flutter/test/material/expansion_panel_test.dart]: No problem, have now pushed your suggestion.

**Comment by victorsanni** [comment]
My understanding is the approach in https://github.com/flutter/flutter/pull/147098 was taken to avoid Google testing failures? But it has undesired side effects and this PR is reverting it?

**Comment by BenjiFarquhar** [comment]
@victorsanni yeah, original issue was it disabled the IconButton when `canTapOnHeader` is true to give button tap control over to the whole ExpansionPanel header, and the fix from https://github.com/flutter/flutter/pull/147098 was to address the disabled color showing, by changing the disabled color to the normal color. but it broke the mouse pointer  when hovering on the expansion panel header, specifically on the IconButton it became the triangle shape, and on the rest of the header it was the hand to express a tappable area. Disabled button changes the mouse pointer to express that it is not tappable. So I have fixed it here in a different way that fixes all of those things.

**Comment by victorsanni** [comment]
@BenjiFarquhar so basically this PR allows the icon to look enabled (i.e darker) instead of disabled (i.e lighter) when canTapOnHeader is set to true?

**Comment by BenjiFarquhar** [comment]
@victorsanni  Yes. When `canTapOnHeader` is true, the `IconButton` now behaves merely as an Icon, signalling to the user that the header can expand/collapse, and doesn't interfere with hovering effects on the expansion panel header.

**Comment by victorsanni** [comment]
LGTM pending review from @TahaTesser.

**Review by victorsanni — APPROVED** [review]

**Review by TahaTesser — APPROVED** [review]
LGTM
