### PR TITLE
[flutter_tools] catch error 32 in cache

### LINKED ISSUE #75812: Flutter tool crashes due to sharing violation when downloading cached artifacts on windows
A bug in the cherry picked fix for the stale cached artifacts is causing the tool to crash on windows due to err 32 sharing violation. this is the number one crash on beta.

### PR DESCRIPTION
**Pull request by jonahwilliams**
I don't have a good idea for how to test this without mocking everything out. I can't revert the change that introduced this bug, since that was required to fix a different P1.

Fixes https://github.com/flutter/flutter/issues/75812

FYI @zanderso

### CODE REVIEW

File: packages/flutter_tools/lib/src/cache.dart [hunk 1]
```diff
@@ -1796,7 +1796,18 @@ class ArtifactUpdater {
       final Directory destination = location.childDirectory(
         tempFile.fileSystem.path.basenameWithoutExtension(tempFile.path)
       );
-      ErrorHandlingFileSystem.deleteIfExists(destination, recursive: true);
+      try {
+        ErrorHandlingFileSystem.deleteIfExists(destination, recursive: true);
+      } on FileSystemException catch (error) {
+        if (_platform.isWindows && error.osError.errorCode == 32) {
+          throwToolExit(
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/cache.dart:1803]: In some cases the tool can continue if deletion fails, and in some cases it can't continue without user interaction. This seems to be one of the cases where it can't continue, and I could see this logic being useful at other call sites of `deleteIfExists`. Would it make sense to have `deleteIfExists` take an additional argument to indicate which sort of call site it is? That would also have the advantage of at least being able to write some unit test for this change, even if coverage of this exact location is difficult.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/cache.dart]: Done

File: packages/flutter_tools/lib/src/base/error_handling_io.dart [hunk 2]
```diff
@@ -73,30 +73,48 @@ class ErrorHandlingFileSystem extends ForwardingFileSystem {
   /// This method should be preferred to checking if it exists and
   /// then deleting, because it handles the edge case where the file or directory
   /// is deleted by a different program between the two calls.
-  static bool deleteIfExists(FileSystemEntity file, {bool recursive = false}) {
+  static bool deleteIfExists(FileSystemEntity file, {bool recursive = false, bool handleSharingViolation = false}) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/error_handling_io.dart:76]: How about something like this? I'm not sure if the `_noExitOnFailure` case should be skipped when `continueOnError` is true, though. I'm not quite sure how that's supposed to work.

```dart
static bool deleteIfExists(
  FileSystemEntity file, {
  bool recursive = false,
  bool continueOnError = true,
  String errorMessage = "some default",
}) {
  if (!file.existsSync()) {
    return false;
  }
  try {
    file.deleteSync(recursive: true);
  } on FileSystemException catch (err) {
    if (_noExitOnFailure) {
      rethrow;
    }

    final int errorCode = err?.osError?.errorCode;
    const int kSystemCannotFindFile = 2;

    // Detect the case where success is reported as failure.
    if (errorCode == kSystemCannotFindFile) {
      ...
    }

    // For everything else, respect `continueOnError`
    if (continueOnError) {
      printError(...errorMessage...)
    } else {
      throwToolExit(...errorMessage...)
    }
  }

  return true;
}
```

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:76]: I'm not really sure how continueOnError/message fits into the existing use cases - I think this method is getting a bit too big and I think a larger change isn't really cherry pickable.

File: packages/flutter_tools/lib/src/base/error_handling_io.dart [hunk 3]
```diff
@@ -73,30 +73,48 @@ class ErrorHandlingFileSystem extends ForwardingFileSystem {
...
+      // Sharing violation indicates that another program has this file
+      // open. This is only an error on windows.
+      const int kSharingViolation = 32;
+
+      if (_noExitOnFailure) {
         rethrow;
       }
-      if (file.existsSync()) {
+
+      if (handleSharingViolation && errorCode == kSharingViolation) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/error_handling_io.dart:99]: Check that the platform is Windows. 32 is something else on e.g. Linux.

File: packages/flutter_tools/lib/src/base/error_handling_io.dart (hunk 2 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:76]: You're right about the size for the cherry-pick.

`continueOnError` doesn't really try to fit in with existing use cases. The idea is to only crash the tool if we really, really care that a file isn't getting deleted, which would be new, instead of handling all these failures on a case-by-case basis.

**Review by zanderso — APPROVED** [review]
lgtm w/ Windows check.

File: packages/flutter_tools/lib/src/base/error_handling_io.dart (hunk 3 above)
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/error_handling_io.dart:99]: Maybe `failOnSharingViolation` instead of `handleSharingViolation`?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:99]: Since this is a static method, i don't have the platform. In this case, I only set handleSharingViolation to true when platform is windows. I could change the API so that platform is always passed in and do the logic here instead of the cache. WDUT?

Comment (zanderso) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:99]: I'm sorry for the churn, but I'm beginning to wonder if my original suggestion to move the logic here was the right thing to do. I do think we need to rethink this method along the lines of https://github.com/flutter/flutter/pull/75719#discussion_r573250670, but if the aim is to cherry-pick a fix for the prominent crasher, then handling this error at the problematic call site might actually give us something more maintainable.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:99]: Yeah, SGTM

File: packages/flutter_tools/lib/src/cache.dart [hunk 4]
```diff
@@ -1796,7 +1796,20 @@ class ArtifactUpdater {
...
         tempFile.fileSystem.path.basenameWithoutExtension(tempFile.path)
       );
-      ErrorHandlingFileSystem.deleteIfExists(destination, recursive: true);
+      try {
+        ErrorHandlingFileSystem.deleteIfExists(
+          destination,
+          recursive: true,
+        );
+      } on FileSystemException catch (error) {
+        if (_platform.isWindows && error.osError.errorCode == 32) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/cache.dart:1805]: nit: Having a named constant for the `32` would be good, like you had in another patch set.
```
const int kSharingViolation = 32;
```

**Review by zanderso — APPROVED** [review]
lgtm

File: packages/flutter_tools/lib/src/cache.dart (hunk 4 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/cache.dart]: done
