### PR TITLE
Avoid thinning frameworks in iOS extensions

### LINKED ISSUE #60351: Must run flutter clean before building when iOS app has watch extension, Failed to extract arm64 for .../PlugIns/WatchApp.appex/Frameworks
## Problem
Must run `flutter clean` between every build (run/debug) when app includes a WKExtension.
Seems like flutter uses the same "active architecture" for Apple Watch as it does for iPhone.
That in turn causes flutter to try extract the wrong architecture when building app for debug/run on device.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Add a watch extension (https://flutter.dev/docs/development/platform-integration/apple-watch
3. Add a pod for your watch extension target (I use `pod 'EFQRCode/watchOS', '~> 5.1.6'`, but any pod will do)
4. Run your app on an iPhone or iOS simulator.
5. Stop debug/run session after app has installed and launched on device/simulator.
6. Again, run your app on an iPhone or iOS simulator.

**Expected results:** 
App launches.

**Actual results:** 
Build error.

<details>
  <summary>Logs</summary>

```
Flutter.framework/_CodeSignature/CodeResources
               sent 98388907 bytes  received 120 bytes  65592684.67 bytes/sec
               total size is 98376483  speedup is 1.00
               PATH/TO/BUILD/Runner.app/Frameworks/App.framework/App: signed bundle with Mach-O universal (x86_64 arm64) [io.flutter.flutter.app]
               PATH/TO/BUILD/Runner.app/Frameworks/Flutter.framework/Flutter: replacing existing signature
               PATH/TO/BUILD/Runner.app/Frameworks/Flutter.framework/Flutter: signed bundle with Mach-O universal (armv7 x86_64 arm64) [io.flutter.flutter]
               fatal error: lipo: -extract arm64 specified but fat file: PATH/TO/BUILD/Runner.app/Watch/APP_NAME.app/PlugIns/WatchApp_staging Extension.appex/Frameworks/EFQRCode.framework/EFQRCode does not contain that architecture
               Failed to extract arm64 for PATH/TO/BUILD/Runner.app/Watch/APP_NAME.app/PlugIns/WatchApp_staging Extension.appex/Frameworks/EFQRCode.framework/EFQRCode. Running lipo -info:
               Architectures in the fat file: PATH/TO/BUILD/Runner.app/Watch/APP_NAME.app/PlugIns/WatchApp_staging Extension.appex/Frameworks/EFQRCode.framework/EFQRCode are: armv7k arm64_32
               Command PhaseScriptExecution failed with a nonzero exit code
               note: Using new build system
               note: Building targets in parallel
               note: Planning build
               note: Constructing build description
```

```
```

```
```

```
[✓] Flutter (Channel beta, 1.19.0-4.2.pre, on Mac OS X 10.15.5 19F101, locale en-NO)
    • Flutter version 1.19.0-4.2.pre at /Users/ME/Documents/Development/FLUTTER_SDK/flutter
    • Framework revision 9b9b543d92 (4 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/ME/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
```

</details>

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Watch extensions are embedded in iOS apps.  Avoid lipo'ing those frameworks to iOS architectures.  Stick to the app frameworks.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/60351

## Tests

Updated `ios_app_with_extensions_test` to include a watch framework.  Check the build succeeds, and that the watch extension frameworks have the expected watch architectures.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart [hunk 1]
```diff
@@ -33,22 +35,53 @@ Future<void> main() async {
...
+        appBundle,
+        'Watch',
+        'watch.app',
+        'PlugIns',
+        'watch Extension.appex',
+        'Frameworks',
+        'EFQRCode.framework',
+        'EFQRCode',
+      );
+      _checkWatchExtensionFrameworkArchs(watchExtensionFrameworkPath);
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart:78]: This is the new check that these plugin frameworks haven't been `lipo`d to the iOS ARCHS.

File: dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart [hunk 2]
```diff
@@ -160,34 +191,6 @@ Future<void> main() async {
         workingDirectory: flutterDirectory.path,
       );
 
-      await inDirectory(projectDir, () async {
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart:163]: This wasn't actually building for the simulator (it's missing `--simulator`) even with the `-d` flag. `flutter build ios` with a watch companion doesn't actually work.  Anyway the next thing this does is run on the simulator, which does work.

File: dev/integration_tests/ios_app_with_extensions/ios/Podfile [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+
+  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
+end
+
+target 'watch Extension' do
+  platform :watchos
+  use_frameworks!
+  use_modular_headers!
+
+  pod 'EFQRCode/watchOS', '5.1.6'
```
Comment (jmagman) [inline dev/integration_tests/ios_app_with_extensions/ios/Podfile:42]: This adds a framework to the watch extension.  Previous this failed because `xcode_backend` `lipo`d all `.framework`s, even the ones in the watch extension with a different expected architecture.

File: dev/integration_tests/ios_app_with_extensions/ios/Runner.xcodeproj/project.pbxproj [hunk 4]
```diff
@@ -811,7 +946,7 @@
 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
 				CLANG_ENABLE_MODULES = YES;
 				CURRENT_PROJECT_VERSION = "$(FLUTTER_BUILD_NUMBER)";
-				ENABLE_BITCODE = YES;
+				ENABLE_BITCODE = NO;
```
Comment (jmagman) [inline dev/integration_tests/ios_app_with_extensions/ios/Runner.xcodeproj/project.pbxproj:949]: Bitcode should be off for Runner.

File: dev/integration_tests/ios_app_with_extensions/pubspec.yaml [hunk 5]
```diff
@@ -19,9 +19,13 @@ dependencies:
   flutter:
     sdk: flutter
 
+  device_info: 0.4.2+7
```
Comment (jmagman) [inline dev/integration_tests/ios_app_with_extensions/pubspec.yaml:22]: Adding (any) plugin is what kicks the tool into running `pod install`, which we need to embed the watch framework.

File: packages/flutter_tools/bin/xcode_backend.sh [hunk 6]
```diff
@@ -257,11 +257,10 @@ ThinFramework() {
 }
 
 ThinAppFrameworks() {
-  local app_path="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"
-  local frameworks_dir="${app_path}/Frameworks"
+  local xcode_frameworks_dir="${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"
```
Comment (jmagman) [inline packages/flutter_tools/bin/xcode_backend.sh:260]: This is the actual fix.
Instead of `find`ing and thinning all `*.framework`s in `Runner.app`, it now only does so in the `Runner.app/Frameworks` directory.

File: dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart [hunk 7]
```diff
@@ -33,22 +35,53 @@ Future<void> main() async {
...
+      // Check the watch extension framework is in place with the expected watch archs.
+      final String watchExtensionFrameworkPath = path.join(
+        appBundle,
+        'Watch',
+        'watch.app',
+        'PlugIns',
+        'watch Extension.appex',
+        'Frameworks',
+        'EFQRCode.framework',
+        'EFQRCode',
```
Comment (xster) [inline dev/devicelab/bin/tasks/ios_app_with_extensions_test.dart:76]: Add a comment for what this is? It came from a pod?

File: dev/integration_tests/ios_app_with_extensions/ios/Podfile (hunk 3 above)
Comment (xster) [inline dev/integration_tests/ios_app_with_extensions/ios/Podfile:42]: never mind, the answer's here. Still good to comment in the other file.

**Review by xster — COMMENTED** [review]
LGTM

File: dev/integration_tests/ios_app_with_extensions/ios/Runner.xcodeproj/project.pbxproj (hunk 4 above)
Comment (Henrik-glt) [reply dev/integration_tests/ios_app_with_extensions/ios/Runner.xcodeproj/project.pbxproj:949]: Why should bitcode be off? Bitcode is a requirement when you have a watch extension.

Comment (jmagman) [reply dev/integration_tests/ios_app_with_extensions/ios/Runner.xcodeproj/project.pbxproj:949]: Because this is an integration test that will never be submitted to the App Store and I didn't want to track down [issues related to the pods building before the correct bitcode-embedded version of Flutter gets copied around](https://github.com/flutter/flutter/issues/39356#issuecomment-618138976).  I'll set it back to `YES` and see if this particular integration test triggers that case.

**Comment by jmagman** [comment]
> LGTM

@xster would you mind approving it?

**Review by xster — APPROVED** [review]

**Comment by xster** [comment]
GitHub needs an approve button on the main tab instead of the files tab.

**Comment by zanderso** [comment]
It looks like this might have broken `ios_app_with_extensions_test` in the device lab.

**Comment by jmagman** [comment]
Error:
```
 could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig' in search paths (in target 'Runner' from project 'Runner')error: /var/folders/gr/7pczn0h51nz2qb3t_0xyfhqc0000gn/T/ios_app_with_extensions_testUdVJD4/app_with_extensions/ios/Flutter/Release.xcconfig
```
