### PR TITLE
Fix text selection in `SearchAnchor/SearchBar`

### LINKED ISSUE #128332: Fix text selection in search bar
#91605

### Use case

1. To get focus on the text, you need to hold your finger near the vertical text input indicator, and then move your finger to either side. After that, a slider and a magnifier will appear.

<details>
<summary>example to reproduce the problem</summary>

https://github.com/flutter/flutter/assets/102767277/203fc5c5-0187-4b98-9b7a-ac6f72c48d05

</details>

2. In order to be able to select text using the sliders, you must first perform the action described in the first paragraph, and then click on the slider that appears and select "Select all". After that, a magnifying glass and text selection sliders will appear.

<details>
<summary>example to reproduce the problem</summary>

https://github.com/flutter/flutter/assets/102767277/bcf07a55-0161-4799-a43e-a8b24cc8b8d9

</details>

### Proposal

Fix the problems described in the first and second paragraphs that cause difficulties when editing text in a TextField in the search view.

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This changes fixes text selection gestures on the search field when using `SearchAnchor`.

Before this change text selection gestures did not work due to an `IgnorePointer` in the widget tree.

This change:
* Removes the `IgnorePointer` so the underlying `TextField` can receive pointer events.
* Introduces `TextField.onTapAlwaysCalled` and `TextSelectionGestureDetector.onUserTapAlwaysCalled`, so a user provided on tap callback can be called on consecutive taps. This is so that the user provided on tap callback for `SearchAnchor/SearchBar` that was previously only handled by `InkWell` will still work if a tap occurs in the `TextField`s hit box. The `TextField`s default behavior is maintained outside of the context of `SearchAnchor/SearchBar`.

Fixes https://github.com/flutter/flutter/issues/128332 and #134965

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/text_field.dart [hunk 1]
```diff
@@ -69,6 +69,13 @@ class _TextFieldSelectionGestureDetectorBuilder extends TextSelectionGestureDete
   void onSingleTapUp(TapDragUpDetails details) {
     super.onSingleTapUp(details);
     _state._requestKeyboard();
+  }
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/text_field.dart:72]: Seems `_state.widget.onTap?.call();` is removed from `onSingleTapUp`. Just wonder if this is intended?

**Review by QuncCccccc — APPROVED** [review]
This looks good to me! Just left some questions:)

File: packages/flutter/lib/src/material/text_field.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/material/text_field.dart:72]: This is intended, it has been moved to `onUserTap`. This is a non-breaking change because `onUserTap` will still be called with `onSingleTapUp` in `TextSelectionGestureDetector` as it was before this change. Extenders of `TextSelectionGestureDetectorBuilder` will be okay because `TextSelectionGestureDetector` retains its previous behavior as the default.

**Review by QuncCccccc — APPROVED** [review]
LGTM! Thanks so much for this fix and all the unit tests😲!
