### PR TITLE
Change Focus.unfocus to take a disposition for where the focus should go.

### LINKED ISSUE #48903: Keyboard focus is lost when popping multiple screens with Navigator.popuntil
@goderbauer
@gspencergoog
@lorenzOliveto

Steps to reproduce:
- Attach a keyboard to an Android device
- push multiple Widget in the navigator stack
- going back to the root with Navigator.popUntil

The keyboard focus is lost and it doesn’t respond anymore. You can find an example in this repository, https://github.com/lorenzOliveto/flutter_keyboard_navigation_issues (pop_until_example.dart).

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

When `Focus.unfocus` is called, the caller usually just thinks about wanting to remove focus from the node, but really, `unfocus` is a request to automatically pass the focus to another (hopefully useful) node.

This PR removes the `focusPrevious` flag from `unfocus`, and replaces it with a `disposition` enum that indicates where the focus should go from here.

The other value of the `UnfocusDisposition` enum is `UnfocusDisposition.scope`.

`UnfocusDisposition.previouslyFocusedChild ` is closest to what `focusPrevious` used to do: focus the nearest enclosing scope and use its `focusedChild` field to walk down the tree, finding the leaf `focusedChild`. This PR modifies it slightly so that it walks up to the nearest _focusable_ enclosing scope before trying to focus the children. This change addresses #48903

A new mode: `UnfocusDisposition.scope` will focus the nearest focusable enclosing scope of this node without trying to use the `FocusScopeNode.focusedChild` value to descend to the leaf focused child. This is useful as a default for both text field finalization and for what happens when `canRequestFocus` is set to false. It allows the scope to stay focused so that `nextFocus`/`previousFocus` still work as expected, but removes the focus from primary focus.

In addition to those changes, `unfocus` called on a `FocuScope` that wasn't the primary focus used to unfocus the primary focus instead. I removed that behavior, since it was buggy: if the primary focus was inside of a child scope, and you called unfocus on the parent scope, then the child scope could have focused another of its children instead, leaving the scope that you called `unfocus` on with `hasFocus` returning true still. If you want to remove the focus from the primary focus instead of the scope, that's easy enough to do: just call `primaryFocus.unfocus()`.

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/48903

## Tests

- Added tests to check unfocus behavior, and to make sure that #48903 is fixed.

## Breaking Change

- [X] No, this is *not* a breaking change, as the `focusPrevious` argument doesn't appear in any customer tests.

### CODE REVIEW

**Comment by gspencergoog** [comment]
cc @chunhtai, this may supersede your change https://github.com/flutter/flutter/pull/50522

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 1]
```diff
@@ -82,15 +82,14 @@ class FocusAttachment {
...
-        _node.unfocus(focusPrevious: true);
+        _node.unfocus(disposition: UnfocusDisposition.pop);
       }
       // This node is no longer in the tree, so shouldn't send notifications anymore.
       _node._manager?._markDetached(_node);
       _node._parent?._removeChild(_node);
       _node._attachment = null;
       assert(!_node.hasPrimaryFocus);
       assert(_node._manager?._markedForFocus != _node);
-      assert(_node._manager?._markedForUnfocus != _node);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: Why does this assert no longer apply?

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 2]
```diff
@@ -129,6 +128,39 @@ class FocusAttachment {
   }
 }
 
+/// Describe when should happen after [FocusNode.unfocus] is called.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: when -> what?
describe -> describes?

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 3]
```diff
@@ -129,6 +128,39 @@ class FocusAttachment {
...
+///
+/// See also:
+///
+///  * [FocusNode.unfocus], which takes this as its `disposition` parameter.
+enum UnfocusDisposition {
+  /// Focus the [FocusManager.rootScope]. This is often the least useful thing
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: nit: first paragraph should be a single sentence summary.

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 4]
```diff
@@ -129,6 +128,39 @@ class FocusAttachment {
...
+  /// to do with focus, since the root scope is effectively above any node that
+  /// appears in the widget tree, there is no context for it, and thus no
+  /// FocusTraversalPolicy that can be used to determine a next focus. This
+  /// means that if you hit TAB, you go nowhere.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: This seems really odd. If you hit TAB and there are notes that can receive focus, shouldn't the focus always go _somewhere_? Why's the root node special like this and outside of all traversal policies?

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 5]
```diff
@@ -129,6 +128,39 @@ class FocusAttachment {
...
+/// Describe when should happen after [FocusNode.unfocus] is called.
+///
+/// See also:
+///
+///  * [FocusNode.unfocus], which takes this as its `disposition` parameter.
+enum UnfocusDisposition {
+  /// Focus the [FocusManager.rootScope]. This is often the least useful thing
+  /// to do with focus, since the root scope is effectively above any node that
+  /// appears in the widget tree, there is no context for it, and thus no
+  /// FocusTraversalPolicy that can be used to determine a next focus. This
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: FocusTraversalPolicy in [] to link it?

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 6]
```diff
@@ -129,6 +128,39 @@ class FocusAttachment {
...
+  /// means that if you hit TAB, you go nowhere.
+  ///
+  /// But, if you need a place to park to focus which will always be valid, this
+  /// is the option to use. It is most frequently used when an explicit settgin
+  /// of the focus will follow.
+  root,
+
+  /// Focus the nearest focusable enclosing scope of this node without trying to
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: the docs for "scope" and "pop" are very technical... I wish they'd provide a more intuitive understanding of what happens to the focus...

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: In other words: Based on the docs here I don't really know which one I should be passing to `unfocus`.

**Comment by goderbauer** [comment]
Cirrus seems unhappy.

**Comment by gspencergoog** [comment]
@goderbauer, OK Cirrus should be happy again.  PTAL.

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 7]
```diff
@@ -646,43 +678,157 @@ class FocusNode with DiagnosticableTreeMixin, ChangeNotifier {
...
     if (!hasFocus && (_manager == null || _manager._markedForFocus != this)) {
       return;
     }
-    if (!hasPrimaryFocus) {
-      // If we are in the focus chain, but not the primary focus, then unfocus
-      // the primary instead.
-      _manager?.primaryFocus?.unfocus(focusPrevious: focusPrevious);
+    FocusScopeNode scope = enclosingScope;
+    if (scope == null) {
+      // Attempting to unfocus the root scope isn't allowed.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: should we assert instead?

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 8]
```diff
@@ -646,43 +678,157 @@ class FocusNode with DiagnosticableTreeMixin, ChangeNotifier {
...
-    if (scope != null) {
-      scope._focusedChildren.remove(this);
-      if (focusPrevious) {
-        scope._doRequestFocus();
-      }
+    switch (disposition) {
+      case UnfocusDisposition.scope:
+        // Focus the nearest scope without focusing its "focused child" or
+        // modifying the first focus for itself or any descendant scopes, except
+        // for removing the currently focused node from its _focusedChildren,
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: line 810 clears all the focus nodes. It is contradicting with the comment

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 9]
```diff
@@ -1066,12 +1213,29 @@ class FocusScopeNode extends FocusNode {
...
       assert(node.ancestors.contains(this), 'Autofocus was requested for a node that is not a descendant of the scope from which it was requested.');
-      node._doRequestFocus();
+      node._doRequestFocus(findFirstFocus: true);
     }
   }
 
   @override
-  void _doRequestFocus() {
+  void _doRequestFocus({@required bool findFirstFocus}) {
+    // It is possible tha a previously focused child is no longer focusable.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: typo?

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 10]
```diff
@@ -914,6 +914,7 @@ void main() {
 
     tester.testTextInput.log.clear();
     tester.testTextInput.closeConnection();
+    await tester.pump();
```
Comment (chunhtai) [inline packages/flutter/test/widgets/editable_text_test.dart]: why additional pump?

File: packages/flutter/lib/src/widgets/focus_manager.dart (hunk 7 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: No, I think it's fine to do nothing when attempting to unfocus the root node.  The fact that the scope is null indicates that this is either a node that isn't part of the tree yet, or that it's the root node, and in either case just doing nothing is the right thing to do. I reworded the comment a bit.

File: packages/flutter/lib/src/widgets/focus_manager.dart (hunk 8 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: Thanks, I removed the comment, because it no longer does that.

File: packages/flutter/lib/src/widgets/focus_manager.dart (hunk 9 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: Yep.  Thanks.

File: packages/flutter/test/widgets/editable_text_test.dart (hunk 10 above)
Comment (gspencergoog) [reply packages/flutter/test/widgets/editable_text_test.dart]: A pump is needed to allow the focus change (unfocus) to be resolved.

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 11]
```diff
@@ -1066,12 +1213,29 @@ class FocusScopeNode extends FocusNode {
...
+    while (focusedChild != null && !focusedChild.canRequestFocus)
+      _focusedChildren.removeLast();
+
+    assert(findFirstFocus != null);
```
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: Done.

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 12]
```diff
@@ -646,43 +675,157 @@ class FocusNode with DiagnosticableTreeMixin, ChangeNotifier {
     return globalOffset & object.semanticBounds.size;
   }
 
-  /// Removes focus from a node that has the primary focus, and cancels any
-  /// outstanding requests to focus it.
+  /// Moves the primary focus to another node when this one is done with it.
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/focus_manager.dart]: This line is explaining the side affect of unfocus, we should put it below line 682.

File: packages/flutter/lib/src/widgets/focus_manager.dart [hunk 13]
```diff
@@ -646,43 +675,157 @@ class FocusNode with DiagnosticableTreeMixin, ChangeNotifier {
...
+        if (scope.canRequestFocus) {
+          // Clearing the focused children here prevents re-focusing the node
+          // that we just unfocused if we immediately hit "next" after
+          // unfocusing, and also prevents choosing to refocus the next-to-last
+          // focused child if unfocus is called more than once.
+          scope._focusedChildren.clear();
+        }
+
+        while (!scope.canRequestFocus) {
+          scope = scope.enclosingScope ?? _manager?.rootScope;
```
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: I am on the fence about clearing anything though: it might make more sense to just focus the scope, and not touch the `_focusedChildren` here. It would mean that as soon as you hit "next", you get back to the thing you just unfocused, but I'm not sure that's wrong.

[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: thanks for explaining. I think there might not be a correct answer, it is down to different use cases. I am ok with keep what we have now and maybe tweak it later if needed

File: packages/flutter/test/widgets/focus_manager_test.dart [hunk 14]
```diff
@@ -510,27 +510,250 @@ void main() {
...
+      await tester.pump();
+      expect(scope1.focusedChild, equals(child1));
+      expect(scope2.focusedChild, equals(child3));
       expect(scope1.hasFocus, isFalse);
+      expect(scope2.hasFocus, isFalse);
+      expect(child1.hasPrimaryFocus, isFalse);
+      expect(child3.hasPrimaryFocus, isFalse);
+      expect(FocusManager.instance.rootScope.hasPrimaryFocus, isTrue);
+    });
+    testWidgets('Unfocus with disposition scope works properly when some nodes are unfocusable', (WidgetTester tester) async {
```
Comment (chunhtai) [inline packages/flutter/test/widgets/focus_manager_test.dart]: can you include a similar test for UnfocusDisposition.previouslyFocusedChild

File: packages/flutter/lib/src/widgets/focus_manager.dart (hunk 13 above)
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/lib/src/widgets/focus_manager.dart]: Yes, part of why I made this into an enum is so we can add other modes later without breaking things. And we can tweak it if it turns out to just be wrong.

File: packages/flutter/test/widgets/focus_manager_test.dart (hunk 14 above)
Comment (gspencergoog) [reply packages/flutter/test/widgets/focus_manager_test.dart]: Oh, yes, I actually thought I already did that.

**Review by chunhtai — APPROVED** [review]
LGTM
