### PR TITLE
flutter#182361 Fix delegate copy on plugins init

### LINKED ISSUE #182361: [iOS] Crash NSGenericException in FlutterPluginAppLifeCycleDelegate (mutation while enumeration)
### Steps to reproduce

The crash occurs in `FlutterPluginAppLifeCycleDelegate` when the `_delegates` collection is modified (a delegate is added or removed) while it is being enumerated during a lifecycle event.

This typically happens if a plugin registers or unregisters a delegate inside a callback like `application:didFinishLaunchingWithOptions:`.

Steps to reproduce logic:
1. A Flutter app starts on iOS.
2. `FlutterPluginAppLifeCycleDelegate` begins iterating over `_delegates` to forward a lifecycle event.
3. Inside the loop, one of the delegates (or a side effect) calls `addDelegate:` or `removeDelegate:`.
4. The `_delegates` NSHashTable is mutated.
5. The loop continues and crashes with `NSGenericException` because the collection was mutated during enumeration.

this crash has been introduced with 3.38.x and this PR : https://github.com/flutter/flutter/pull/176580/changes
On line 178,

  `for (NSObject<FlutterApplicationLifeCycleDelegate>* delegate in _delegates) {` should be replaced by `  for (NSObject<FlutterApplicationLifeCycleDelegate>* delegate in [_delegates allObjects]) {`

like the original code.

I'm opening a PR with Tests accordingly and this should be fixed in a 3.38.X (we're facing more than 200k crashes everyday)

### Expected results

The app should handle delegate registration/deregistration gracefully during lifecycle events without crashing.

### Actual results

The app crashes with the following exception:
```
Fatal Exception: NSGenericException
Collection <NSHashTable: ...> was mutated while being enumerated.
Stack trace:
          Fatal Exception: NSGenericException
0  CoreFoundation                 0xc5964 __exceptionPreprocess
1  libobjc.A.dylib                0x31814 objc_exception_throw
2  CoreFoundation                 0x14e5dc +[__NSFastEnumerationEnumerator allocWithZone:]
3  Flutter                        0x3d66c -[FlutterPluginAppLifeCycleDelegate application:didFinishLaunchingWithOptions:isFallbackForScene:] + 178 (FlutterPluginAppLifeCycleDelegate.mm:178)
4  Flutter                        0x3d214 -[FlutterPluginAppLifeCycleDelegate application:didFinishLaunchingWithOptions:] + 151 (FlutterPluginAppLifeCycleDelegate.mm:151)
5  Flutter                        0x13090 -[FlutterAppDelegate application:didFinishLaunchingWithOptions:] + 54 (FlutterAppDelegate.mm:54)
6  Runner                         0xcae4 AppDelegate.application(_:didFinishLaunchingWithOptions:) + 79 (AppDelegate.swift:79)
7  Runner                         0xd2f0 @objc AppDelegate.application(_:didFinishLaunchingWithOptions:) (<compiler-generated>)
8  UIKitCore                      0x1420384 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]
9  UIKitCore                      0x1421928 -[UIApplication _callInitializationDelegatesWithActions:forScene:payload:fromOriginatingProcess:]
10 UIKitCore                      0x142594c -[UIApplication _runWithMainScene:transitionContext:completion:]
11 UIKitCore                      0xa2dce8 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:]
12 UIKitCore                      0xd8eb0 _UIScenePerformActionsWithLifecycleActionMask
13 UIKitCore                      0xa2e564 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke
14 UIKitCore                      0xa2e0d8 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
15 UIKitCore                      0xa2e37c -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
16 UIKitCore                      0xa2de08 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
17 UIKitCore                      0xa39288 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
18 UIKitCore                      0xeabec4 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:]
19 UIKitCore                      0xd9cc8 _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion
20 UIKitCore                      0xa38f84 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
21 UIKitCore                      0x8781e4 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.218
22 UIKitCore                      0x877278 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
23 UIKitCore                      0x877e50 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
24 UIKitCore                      0x1424918 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:]
25 UIKitCore                      0xed4cb4 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:]
26 FrontBoardServices             0x1e3ec __95-[FBSScene _callOutQueue_didCreateWithTransitionContext:alternativeCreationCallout:completion:]_block_invoke
27 FrontBoardServices             0x1e8a4 -[FBSScene _callOutQueue_maybeCoalesceClientSettingsUpdates:]
28 FrontBoardServices             0x1e204 -[FBSScene _callOutQueue_didCreateWithTransitionContext:alternativeCreationCallout:completion:]
29 FrontBoardServices             0x8cbcc __93-[FBSWorkspaceScenesClient _callOutQueue_sendDidCreateForScene:transitionContext:completion:]_block_invoke.349
30 FrontBoardServices             0x2bf64 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
31 FrontBoardServices             0x48e04 -[FBSWorkspaceScenesClient _callOutQueue_sendDidCreateForScene:transitionContext:completion:]
32 FrontBoardServices             0x4a768 __92-[FBSWorkspaceScenesClient createSceneWithIdentity:parameters:transitionContext:completion:]_block_invoke_2
33 FrontBoardServices             0x2bf64 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
34 libdispatch.dylib              0x1b7fc _dispatch_client_callout
35 libdispatch.dylib              0x6bb4 _dispatch_block_invoke_direct
36 BoardServices                  0x91d4 __BSSERVICEMAINRUNLOOPQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
37 BoardServices                  0x9054 BSServiceMainRunLoopSourceHandler
38 CoreFoundation                 0x68f10 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
39 CoreFoundation                 0x68e84 __CFRunLoopDoSource0
40 CoreFoundation                 0x46acc __CFRunLoopDoSources0
41 CoreFoundation                 0x1d6d8 __CFRunLoopRun
42 CoreFoundation                 0x1ca6c _CFRunLoopRunSpecificWithOptions
43 GraphicsServices               0x1498 GSEventRunModal
44 UIKitCore                      0x9ddf8 -[UIApplication _run]
45 UIKitCore                      0x46e54 UIApplicationMain
46 UIKitCore                      0x172938 -[UIScrollView contentInset]
47 Runner                         0xdcf0 main (AppDelegate.swift)
48 ???                            0x193592e28 (Manquant)
```
        
...

### Code sample

This is an issue within the iOS Engine embedding (`FlutterPluginAppLifeCycleDelegate`). It cannot be reproduced with pure Dart code.

To reproduce the crash, a native plugin must add or remove a delegate while the `FlutterPluginAppLifeCycleDelegate` is iterating over its delegates (e.g., during `didFinishLaunchingWithOptions`).

Here is the Objective-C unit test logic that reproduces the `NSGenericException`:

```
// 1. Define a delegate that mutates the list during execution
@interface MutatingDelegate : NSObject <FlutterApplicationLifeCycleDelegate>
@property(nonatomic, weak) FlutterPluginAppLifeCycleDelegate* container;
@end

@implementation MutatingDelegate
- (BOOL)application:(UIApplication*)application
    didFinishLaunchingWithOptions:(NSDictionary*)launchOptions {
    // THIS CAUSES THE CRASH: Modifying the collection while it is being iterated
    [self.container addDelegate:[[NSObject alloc] init]]; 
    return YES;
}
@end

// 2. The Test Case
- (void)testCrashReproduction {
    FlutterPluginAppLifeCycleDelegate* delegate = [[FlutterPluginAppLifeCycleDelegate alloc] init];
    MutatingDelegate* mutatingDelegate = [[MutatingDelegate alloc] init];
    mutatingDelegate.container = delegate;
    
    [delegate addDelegate:mutatingDelegate];
    
    // This line throws "Fatal Exception: NSGenericException"
    // "Collection <NSHashTable> was mutated while being enumerated."
    [delegate application:[UIApplication sharedApplication]
        didFinishLaunchingWithOptions:nil];
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
          Fatal Exception: NSGenericException
0  CoreFoundation                 0xc5964 __exceptionPreprocess
1  libobjc.A.dylib                0x31814 objc_exception_throw
2  CoreFoundation                 0x14e5dc +[__NSFastEnumerationEnumerator allocWithZone:]
3  Flutter                        0x3d66c -[FlutterPluginAppLifeCycleDelegate application:didFinishLaunchingWithOptions:isFallbackForScene:] + 178 (FlutterPluginAppLifeCycleDelegate.mm:178)
4  Flutter                        0x3d214 -[FlutterPluginAppLifeCycleDelegate application:didFinishLaunchingWithOptions:] + 151 (FlutterPluginAppLifeCycleDelegate.mm:151)
5  Flutter                        0x13090 -[FlutterAppDelegate application:didFinishLaunchingWithOptions:] + 54 (FlutterAppDelegate.mm:54)
6  Runner                         0xcae4 AppDelegate.application(_:didFinishLaunchingWithOptions:) + 79 (AppDelegate.swift:79)
7  Runner                         0xd2f0 @objc AppDelegate.application(_:didFinishLaunchingWithOptions:) (<compiler-generated>)
8  UIKitCore                      0x1420384 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]
9  UIKitCore                      0x1421928 -[UIApplication _callInitializationDelegatesWithActions:forScene:payload:fromOriginatingProcess:]
10 UIKitCore                      0x142594c -[UIApplication _runWithMainScene:transitionContext:completion:]
11 UIKitCore                      0xa2dce8 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:]
12 UIKitCore                      0xd8eb0 _UIScenePerformActionsWithLifecycleActionMask
13 UIKitCore                      0xa2e564 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke
14 UIKitCore                      0xa2e0d8 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
15 UIKitCore                      0xa2e37c -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
16 UIKitCore                      0xa2de08 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
17 UIKitCore                      0xa39288 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
18 UIKitCore                      0xeabec4 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:]
19 UIKitCore                      0xd9cc8 _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion
20 UIKitCore                      0xa38f84 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
21 UIKitCore                      0x8781e4 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.218
22 UIKitCore                      0x877278 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
23 UIKitCore                      0x877e50 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
24 UIKitCore                      0x1424918 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:]
25 UIKitCore                      0xed4cb4 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:]
26 FrontBoardServices             0x1e3ec __95-[FBSScene _callOutQueue_didCreateWithTransitionContext:alternativeCreationCallout:completion:]_block_invoke
27 FrontBoardServices             0x1e8a4 -[FBSScene _callOutQueue_maybeCoalesceClientSettingsUpdates:]
28 FrontBoardServices             0x1e204 -[FBSScene _callOutQueue_didCreateWithTransitionContext:alternativeCreationCallout:completion:]
29 FrontBoardServices             0x8cbcc __93-[FBSWorkspaceScenesClient _callOutQueue_sendDidCreateForScene:transitionContext:completion:]_block_invoke.349
30 FrontBoardServices             0x2bf64 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
31 FrontBoardServices             0x48e04 -[FBSWorkspaceScenesClient _callOutQueue_sendDidCreateForScene:transitionContext:completion:]
32 FrontBoardServices             0x4a768 __92-[FBSWorkspaceScenesClient createSceneWithIdentity:parameters:transitionContext:completion:]_block_invoke_2
33 FrontBoardServices             0x2bf64 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
34 libdispatch.dylib              0x1b7fc _dispatch_client_callout
35 libdispatch.dylib              0x6bb4 _dispatch_block_invoke_direct
36 BoardServices                  0x91d4 __BSSERVICEMAINRUNLOOPQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
37 BoardServices                  0x9054 BSServiceMainRunLoopSourceHandler
38 CoreFoundation                 0x68f10 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
39 CoreFoundation                 0x68e84 __CFRunLoopDoSource0
40 CoreFoundation                 0x46acc __CFRunLoopDoSources0
41 CoreFoundation                 0x1d6d8 __CFRunLoopRun
42 CoreFoundation                 0x1ca6c _CFRunLoopRunSpecificWithOptions
43 GraphicsServices               0x1498 GSEventRunModal
44 UIKitCore                      0x9ddf8 -[UIApplication _run]
45 UIKitCore                      0x46e54 UIApplicationMain
46 UIKitCore                      0x172938 -[UIScrollView contentInset]
47 Runner                         0xdcf0 main (AppDelegate.swift)
48 ???                            0x193592e28 (Manquant)
        
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Waiting for another flutter command to release the startup lock...
[✓] Flutter (Channel stable, 3.38.7, on macOS 26.2 25C56 darwin-arm64, locale fr-FR) [1 159ms]
    • Flutter version 3.38.7 on channel stable at /Users/maxime_pontoire/fvm/versions/3.38.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3b62efc2a3 (4 weeks ago), 2026-01-13 13:47:42 -0800
    • Engine revision 78fc3012e4
    • Dart version 3.10.7
    • DevTools version 2.51.1
    • Pub download mirror https://artifact.socrate.vsct.fr/artifactory/api/pub/all-pub
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop,
      enable-android, enable-ios, cli-animations, enable-native-assets, omit-legacy-version-file,
      enable-lldb-debugging

[✗] Android toolchain - develop for Android devices [1 105ms]
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 26.2) [2,3s]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17C52
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [13ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (4 available) [6,5s]
    • eMxPi’s iPhone (wireless) (mobile) • 00008130-00063DDA2E04001C            • ios            • iOS
      26.3 23D127
    • iPhone + Watch (mobile)            • A2B07733-85AB-4812-BFD2-1822DB74E7CF • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-26-2 (simulator)
    • macOS (desktop)                    • macos                                • darwin-arm64   •
      macOS 26.2 25C56 darwin-arm64
    • Chrome (web)                       • chrome                               • web-javascript •
      Google Chrome 145.0.7632.46

[✓] Network resources [326ms]
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by eMxPi**
Fix #182361
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm [hunk 1]
```diff
@@ -175,7 +175,7 @@ - (BOOL)sceneWillConnectFallback:(UISceneConnectionOptions*)connectionOptions {
 - (BOOL)application:(UIApplication*)application
     didFinishLaunchingWithOptions:(NSDictionary*)launchOptions
                isFallbackForScene:(BOOL)isFallback {
-  for (NSObject<FlutterApplicationLifeCycleDelegate>* delegate in _delegates) {
+  for (NSObject<FlutterApplicationLifeCycleDelegate>* delegate in [_delegates allObjects]) {
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm:180]: worth adding a comment as this isn't immediately obvious that `_delegates` gets mutated in the loop.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm [hunk 2]
```diff
@@ -81,6 +81,25 @@ - (BOOL)application:(UIApplication*)application
 }
 @end
 
+@interface MutatingDelegate : NSObject <FlutterApplicationLifeCycleDelegate>
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm]: Is this referring to the `AppDelegate` in your actual crash? May wanna call it `MutatingAppDelegate` since there are so many "delegate" names here.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm [hunk 3]
```diff
@@ -81,6 +81,25 @@ - (BOOL)application:(UIApplication*)application
...
+
+@implementation MutatingDelegate
+- (BOOL)application:(UIApplication*)application
+    didFinishLaunchingWithOptions:(NSDictionary*)launchOptions {
+  if (self.shouldAdd) {
+    // Case 1: Add a new delegate during the loop over _delegates
+    [self.container addDelegate:[[FakePlugin alloc] init]];
+  } else {
+    // Case 2: Remove itself during the loop over _delegates
+    [self.container removeDelegate:self];
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm]: IIUC the new convention is to put this kind of logic in `didInitializeImplicitFlutterEngine`? @vashworth

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm (hunk 1 above)
Comment (eMxPi) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm:180]: that's the way Obj-c is working with pointer: inside _delegates, some Plugin can register/unregister and in that way the reference made to a changing value is making the Iteration Crash.

I can add the comment if needed.

Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm:180]: I understand the crash; my point is that the mutation happens downstream and isn't visible here. The fact that this regression occurred proves it's a non-obvious side effect, so a comment would help prevent someone from 'fixing' this back into a crash later.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm (hunk 2 above)
Comment (vashworth) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm]: Typically a `FlutterApplicationLifeCycleDelegate` is a `FlutterPlugin`, but the `FlutterPluginAppLifeCycleDelegate` variable (named `container` in this setup), is usually in the `FlutterAppDelegate`. So yeah it's a little confusing if this is trying to represent a plugin or an app delegate

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm (hunk 3 above)
Comment (vashworth) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm]: Correct, but it's not guaranteed that people have migrated yet.

**Comment by vashworth** [comment]
@eMxPi This PR is trying to merge into the `flutter-3.38-candidate.0` branch. Please change it to target the `master` branch. Once it lands in master, then we will cherry-pick to beta and stable

**Review by reidbaker — DISMISSED** [review]
The changes in the content aware hash (and others) are unrelated to the pr described changes.

**Comment by eMxPi** [comment]
> The changes in the content aware hash (and others) are unrelated to the pr described changes.


> yes need to rebase it on master, target 3.38.x

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm (hunk 2 above)
Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm]: Thanks for clarification. This class is a `FlutterApplicationLifeCycleDelegate` (typically a plugin) and it contains a  `FlutterPluginAppLifeCycleDelegate` (typically the "container" inside app delegate). So I don't  think this test accurately represents the actual crash reported.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm (hunk 3 above)
[the remark this answers is not in the document]
Comment (eMxPi) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm]: Did the fix

**Comment by hellohuanlin** [comment]
> hi @vashworth I think I fixed the tests and all the comments, tell me if I'm missing anything!

You didn't address either of my 2 comments.

**Review by hellohuanlin — DISMISSED** [review]

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm (hunk 1 above)
Comment (eMxPi) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm:180]: You're absolutely right. It's a classic case of a non-obvious fix for a mutation-during-enumeration crash. I'll add a comment to clarify that allObjects creates a snapshot to safely allow plugins to register or unregister themselves during the lifecycle dispatch.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm (hunk 2 above)
Comment (eMxPi) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm]: I've just pushed a new commit with comments/update on the naming to clarify the test. I hope it helps

**Review by vashworth — APPROVED** [review]

**Review by LouiseHsu — APPROVED** [review]

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm [hunk 4]
```diff
@@ -81,6 +100,30 @@ - (BOOL)application:(UIApplication*)application
 }
 @end
 
+/**
+ * A mock plugin that simulates behavior causing a mutation crash.
+ * This represents a "downstream" mutation where a plugin adds or removes
+ * delegates during a lifecycle notification loop.
+ */
+@interface MutatingPlugin : NSObject <FlutterApplicationLifeCycleDelegate>
+@property(nonatomic, weak) FlutterPluginAppLifeCycleDelegate* lifecycleDelegate;
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm:109]: Oh Interesting use case, where a plugin (`MutatingPlugin`) holds a reference to the `lifecycleDelegate` and registers other plugin (`FakePlugin` in your example) (rather than `FakePlugin` registering itself directly). 

I am curious what is your actual use case in your app, if you don't mind? @eMxPi

Comment (eMxPi) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm:109]: We're using several pubs, but the plugins we're registering "'manually" in the AppDelegate are Batch (batch_flutter) and background_locator_2

Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm:109]: Very interesting use case. thanks for the reference.

Comment (eMxPi) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm:109]: > Very interesting use case. thanks for the reference.

@hellohuanlin no problem. Tell me if you need any more details.

In the meantime, do you think we can apply this to the 3.38.X, we've made a lot of tests with 3.41.3 and are facing several issues linked to accessibility. I'll come back to you with more details

Comment (stuartmorgan-g) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm:109]: We only hotfix previous stable releases in truly extraordinary circumstances; this would not meet that bar. If you need a fix for 3.38, you would either need to maintain your own fork of the engine, or find a plugin-level workaround (such as doing any additional registration asynchronously).

Comment (eMxPi) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm:109]: @stuartmorgan-g yes I know, but since the 3.41 has several accessibility issues (i'm waiting for the full report of our tester to give you details about it) I think fixing the regression introduced by the 3.38 would be appreciated by the community.
As you can see in the fix i've produced, it's not in the way plugins are registered but I the modification of the code in 3.38 (no longer using a copy but a direct reference to a changing object). So restoring the right way the engine is (and should) work would be appreciated

Comment (stuartmorgan-g) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegateTest.mm:109]: > I think fixing the regression introduced by the 3.38 would be appreciated by the community.

There will always be some people who want specific fixes in arbitrary old versions of Flutter; that doesn't change our policy. If this had been reported earlier, it could have been fixed in 3.38.x via our normal process. Since it wasn't, that's no longer an option.

> As you can see in the fix i've produced, it's not in the way plugins are registered but I the modification of the code in 3.38 (no longer using a copy but a direct reference to a changing object).

I understand both the bug and the fix. What I described is not a fix, it's a client-level workaround.
