### PR TITLE
Update dropdown menu semantics to fix its a11y issues

### LINKED ISSUE #133742: DropdownMenu VoiceOver/Talkback uses the wrong semantic label
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When voice over reads semantics from `DropdownMenu` it reads the last option instead of the selected one.

I am able to reproduce this behavior with the sample code provide by the `DropdownMenu` class documentation.

1. Run the sample app on iOS simulator
2. Open Accessibility Inspector app and select simulator
3. Target the `DropdownMenu` to see how it will be vocalized

### Expected results

Voice Over should use the selected option from `DropdownMenu`.

### Actual results

Voice Over use the last option from `DropdownMenu`'s items.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const DropdownMenuExample());

class DropdownMenuExample extends StatefulWidget {
  const DropdownMenuExample({super.key});

  @override
  State<DropdownMenuExample> createState() => _DropdownMenuExampleState();
}

class _DropdownMenuExampleState extends State<DropdownMenuExample> {
  final TextEditingController colorController = TextEditingController();
  final TextEditingController iconController = TextEditingController();
  ColorLabel? selectedColor;
  IconLabel? selectedIcon;

  @override
  Widget build(BuildContext context) {
    final List<DropdownMenuEntry<ColorLabel>> colorEntries = <DropdownMenuEntry<ColorLabel>>[];
    for (final ColorLabel color in ColorLabel.values) {
      colorEntries.add(DropdownMenuEntry<ColorLabel>(value: color, label: color.label, enabled: color.label != 'Grey'));
    }

    final List<DropdownMenuEntry<IconLabel>> iconEntries = <DropdownMenuEntry<IconLabel>>[];
    for (final IconLabel icon in IconLabel.values) {
      iconEntries.add(DropdownMenuEntry<IconLabel>(value: icon, label: icon.label));
    }

    return MaterialApp(
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.green),
      home: Scaffold(
        body: SafeArea(
            child: Center(
          child: Column(
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.all(20),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    DropdownMenu<ColorLabel>(
                        width: 350,
                        initialSelection: ColorLabel.green,
                        controller: colorController,
                        label: const Text('Color'),
                        dropdownMenuEntries: colorEntries,
                        onSelected: (ColorLabel? color) {
                          setState(() {
                            selectedColor = color;
                          });
                        },
                        inputDecorationTheme: Theme.of(context).inputDecorationTheme.copyWith(
                              outlineBorder: BorderSide(color: selectedColor?.color ?? Colors.blue),
                              enabledBorder: OutlineInputBorder(
                                borderSide: BorderSide(color: selectedColor?.color ?? Colors.blue),
                                borderRadius: BorderRadius.circular(12),
                              ),
                              focusedBorder: OutlineInputBorder(
                                borderSide: BorderSide(color: selectedColor?.color ?? Colors.blue),
                                borderRadius: BorderRadius.circular(12),
                              ),
                              labelStyle: TextStyle(color: selectedColor?.color ?? Colors.blue),
                            ),
                        menuStyle: MenuStyle(
                          alignment: const Alignment(-1, 1.2),
                          shape: MaterialStatePropertyAll(
                            RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                              side: BorderSide(color: selectedColor?.color ?? Colors.blue),
                            ),
                          ),
                        )
                        // shape: MaterialStatePropertyAll(OutlinedBorder(side: BorderSide(color: Colors.red)))),
                        ),
                    const SizedBox(height: 20),
                    DropdownMenu<IconLabel>(
                      controller: iconController,
                      enableFilter: true,
                      leadingIcon: const Icon(Icons.search),
                      label: const Text('Icon'),
                      dropdownMenuEntries: iconEntries,
                      inputDecorationTheme: const InputDecorationTheme(filled: true),
                      onSelected: (IconLabel? icon) {
                        setState(() {
                          selectedIcon = icon;
                        });
                      },
                    )
                  ],
                ),
              ),
              if (selectedColor != null && selectedIcon != null)
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Text('You selected a ${selectedColor?.label} ${selectedIcon?.label}'),
                    Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 5),
                        child: Icon(
                          selectedIcon?.icon,
                          color: selectedColor?.color,
                        ))
                  ],
                )
              else
                const Text('Please select a color and an icon.')
            ],
          ),
        )),
      ),
    );
  }
}

enum ColorLabel {
  blue('Blue', Colors.blue),
  pink('Pink', Colors.pink),
  green('Green', Colors.green),
  yellow('Yellow', Colors.yellow),
  grey('Grey', Colors.grey);

  const ColorLabel(this.label, this.color);
  final String label;
  final Color color;
}

enum IconLabel {
  smile('Smile', Icons.sentiment_satisfied_outlined),
  cloud(
    'Cloud',
    Icons.cloud_outlined,
  ),
  brush('Brush', Icons.brush_outlined),
  heart('Heart', Icons.favorite);

  const IconLabel(this.label, this.icon);
  final String label;
  final IconData icon;
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

|----|----|
|   Capture d’écran 2023-08-31 à 09 24 51    |  Simulator Screenshot - iPhone 14 Pro - 2023-08-31 at 09 25 46   |
|----|----|
|    Capture d’écran 2023-08-31 à 09 25 07   |   Simulator Screenshot - iPhone 14 Pro - 2023-08-31 at 09 25 55   |
|----|----|

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale fr-FR)
    • Flutter version 3.10.6 on channel stable at /Users/larry_geromegnace/fvm/versions/3.10.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (7 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/larry_geromegnace/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/larry_geromegnace/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/larry_geromegnace/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • C9D62981-23D9-48FF-ABD3-E484835560F5 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #143848: [web:a11y] Enabling Semantics layer breaks DropdownMenu functionality in 3.19.0
### Steps to reproduce

run SemanticsBinding.instance.ensureSemantics();
Implement basic DropdownMenu widget
Click on the dropdown arrow icon

### Expected results

Dropdown opens

### Actual results

Last DropdownMenuEntry is selected

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SemanticsBinding.instance.ensureSemantics();

  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: DropdownMenu<int>(
            dropdownMenuEntries: [
              DropdownMenuEntry(value: 0, label: "zero"),
              DropdownMenuEntry(value: 1, label: "one"),
              DropdownMenuEntry(value: 2, label: "two"),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by hannah-hyj**
fixes https://github.com/flutter/flutter/issues/133742 

fixes https://github.com/flutter/flutter/issues/143848 

because the _initialMenu is invisible, we should not add semantics nodes to it

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 1]
```diff
@@ -2460,6 +2460,48 @@ void main() {
...
+
+  testWidgets('Semantics does not include initial menu buttons', (WidgetTester tester) async {
+    final ThemeData themeData = ThemeData();
+    final TextEditingController controller = TextEditingController();
+    addTearDown(controller.dispose);
+
+    await tester.pumpWidget(
+      StatefulBuilder(
+        builder: (BuildContext context, StateSetter setState) => MaterialApp(
+          theme: themeData,
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:2472]:
```suggestion
```

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 2]
```diff
@@ -2460,6 +2460,48 @@ void main() {
     expect(node.value, 'Item 3');
   });
 
+
+  testWidgets('Semantics does not include initial menu buttons', (WidgetTester tester) async {
+    final ThemeData themeData = ThemeData();
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:2465]:
```suggestion
```

File: packages/flutter/test/material/dropdown_menu_test.dart [hunk 3]
```diff
@@ -2460,6 +2460,48 @@ void main() {
...
+    final TextEditingController controller = TextEditingController();
+    addTearDown(controller.dispose);
+
+    await tester.pumpWidget(
+      StatefulBuilder(
```
Comment (QuncCccccc) [inline packages/flutter/test/material/dropdown_menu_test.dart:2470]: nit: probably we don't need StatefulBuilder as well. Just wanted to simplify this test:)

**Review by QuncCccccc — APPROVED** [review]
Thanks a lot for the fix! LGTM

**Comment by gspencergoog** [comment]
@hannah-hyj Just a heads-up that this may be causing an accessibility issue with some dropdowns: see b/378048044
