### PR TITLE
[flutter_tool] Fix crash in update-packages

### LINKED ISSUE #71876: `flutter update-packages --force-upgrade` fails if `_flutter_web_tool` is present
May have been broken by the addition of `integration_test`.

Logs:

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter update-packages --force-upgrade

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'dependencies' was called on null.
Receiver: null
Tried calling: dependencies

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      createTemporaryFlutterSdk (package:flutter_tools/src/commands/update_packages.dart:1457:60)
#2      UpdatePackagesCommand.runCommand (package:flutter_tools/src/commands/update_packages.dart:322:33)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
<asynchronous suspension>
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#16     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:88:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel unknown, 1.25.0-5.0.pre.100, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.25.0-5.0.pre.100 at /Users/dnfield/src/flutter/flutter
    • Framework revision 625471e1d6 (16 minutes ago), 2020-12-07 13:41:51 -0800
    • Engine revision 69dacc4138
    • Dart version 2.12.0 (build 2.12.0-121.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/dnfield/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/dnfield/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```

### PR DESCRIPTION
**Pull request by zanderso**
## Description

Ignore stray packages in `createTemporaryFlutterSdk`.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/71876

## Tests

I added the following tests:

Added a stray package to the existing test.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/update_packages.dart [hunk 1]
```diff
@@ -1445,6 +1445,9 @@ Directory createTemporaryFlutterSdk(FileSystem fileSystem, Directory realFlutter
       .childFile('pubspec.yaml')
       ..createSync(recursive: true);
     final PubspecYaml pubspecYaml = pubspecsByName[flutterPackage];
+    if (pubspecYaml == null) {
+      continue;
+    }
```
Comment (dnfield) [inline packages/flutter_tools/lib/src/commands/update_packages.dart:1450]: This is an improvement. 

Should we print some kind of warning here that the developer has an unexpected folder in `packages`, and it's being ignored?

**Review by dnfield — APPROVED** [review]
LGTM

File: packages/flutter_tools/lib/src/commands/update_packages.dart (hunk 1 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/commands/update_packages.dart]: Good call. Done.
