### PR TITLE
Fix TextField helper top padding on M3

### LINKED ISSUE #144984: TextField helper text top padding should be 4.0 on Material3
### Steps to reproduce

1. Run the code sample
2. Observe that the gap between the text field container and the helper text is too large (it is 8.0 instead of 4.0).

### Expected results

From the M3 specification:
image

See https://m3.material.io/components/text-fields/specs#0c5c8d6d-2169-4d42-960c-51f6ee42eb57

### Actual results

image

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(
        child: Scaffold(
          body: Padding(
            padding: const EdgeInsets.all(16.0),
            child: TextField(
              controller: TextEditingController(text: ''),
              decoration: InputDecoration(
                labelText: 'label',
                helperText: 'helper',
                filled: true,
                helperStyle: TextStyle(backgroundColor: Colors.amber[700]),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

No error

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.19.0-3.0.pre.1083, on Ubuntu 23.10 6.5.0-25-generic, locale fr_FR.UTF-8)
    • Flutter version 3.19.0-3.0.pre.1083 on channel master at /home/bruno/Nevercode/flutter
    • Upstream repository git@github.com:NevercodeHQ/flutter.git
    • FLUTTER_GIT_URL = git@github.com:NevercodeHQ/flutter.git
    • Framework revision 1ca88730a0 (il y a 9 heures), 2024-03-11 18:31:25 -0700
    • Engine revision 6745955bb4
    • Dart version 3.4.0 (build 3.4.0-220.0.dev)
    • DevTools version 2.33.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /media/oldhome/Android/Sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /media/oldhome/Android/Sdk
    • Java binary at: /media/oldhome/Produits/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /media/oldhome/Produits/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.87.1)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.10 6.5.0-25-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.111

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

`InputDecorator` adds a 8.0 gap beetween the container and the helper text.
From the Material 3 specification, this gap should be 4.0.
See https://m3.material.io/components/text-fields/specs#0c5c8d6d-2169-4d42-960c-51f6ee42eb57.

This PR sets the correct values for M3 without changing the value for M2.

| Before | After | M3 Spec |
|--------|--------|--------|
| image | image| image |

If this change is accepted, a future step will be to make this value configurable, probably by `InputDecorationTheme`.

## Related Issue

Fixes https://github.com/flutter/flutter/issues/144984

## Tests

Updates a value used by several existing tests.

### CODE REVIEW

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -726,7 +726,9 @@ class _RenderDecoration extends RenderBox with SlottedContainerRenderObjectMixin
        _expands = expands,
        _material3 = material3;
 
-  static const double subtextGap = 8.0;
+  // TODO(bleroux): consider defining this value as a Material token and making it
+  // configurable by InputDecorationTheme.
```
Comment (justinmc) [inline packages/flutter/lib/src/material/input_decorator.dart:730]: This is probably a good idea. I've seen issues where people wanted to be able to control the various fine spacing in InputDecorator.

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

I would have thought this might break more tests (internal or Google/customer), but it looks like it's good. I guess fewer people are using M3.

**Comment by bleroux** [comment]
> I would have thought this might break more tests (internal or Google/customer), but it looks like it's good. I guess fewer people are using M3.

Let's see if someone ask for a revert in the coming days :crossed_fingers:

**Comment by justinmc** [comment]
@bleroux This did break many image diff tests, but they all looked like expected changes, except for one: a text field had become too small for the accessibility guidelines (48px for Android, 44px for iOS). Is there a guard against that in InputDecorator that could be fixed?

**Comment by bleroux** [comment]
@justinmc 
I would says that it is weird that reducing the gap below the container by 4.0 (as done by this PR) changes wether the TextField meet the accessibility guideline or not (the interactive zone is the same so it was probably wrong before too).

In either case, this should be fixed, if you have a screenshot or access to this TextField configuration, it would be interesting to know its configuration (maybe isDense is set to true?).

I have not yet migrated tests related to `isDense` (one difficulty is that it is no more a thing in M3, so we will have to decide how it impacts rendering). I can focus on such test before relanding this change.

**Comment by bleroux** [comment]
@justinmc
I checked the `InputDecorator` implementation.
It is intended that the min size is lower than `kMinInteractiveDimension` in some cases:

https://github.com/flutter/flutter/blob/985576dbfdff5e9321941d9f66cb33baed337346/packages/flutter/lib/src/material/input_decorator.dart#L1102-L1104

**Comment by justinmc** [comment]
@bleroux Looking into this more, it seems like it's not the minimum size that it's breaking, it's the [MinimumTextContrastGuideline](https://main-api.flutter.dev/flutter/flutter_test/MinimumTextContrastGuideline-class.html)! Very strange. A field with red error text underneath is now breaking this guideline.

The only hunch I have is this line:

https://github.com/flutter/flutter/blob/20105db16c9955d1792276f709d11e12c3e4ffbc/packages/flutter_test/lib/src/accessibility.dart#L405

It inflates the bounds by 4 pixels. Maybe that's now enough to overlap with the bottom of the field, so it's "seeing" some additional color that it wasn't before?

The only difference that I see before and after your change is that paintBoundsWithOffset is shifted up by 4 pixels (which is exactly the difference that I'd expect from this PR).

**Comment by bleroux** [comment]
@justinmc Very interesting findings.
I have not yet figured out how to reproduce this failure. I would be interested in having more information (error message, screenshot, etc).

**Comment by justinmc** [comment]
It's throwing here: https://github.com/flutter/flutter/blob/b346eb3443e7be86b9ad5767df5c465a908b8f07/packages/flutter_test/lib/src/accessibility.dart#L465

I'll try to get some help on the accessibility test, and otherwise I'll try to write a test that reproduces it and post back.

**Comment by justinmc** [comment]
Sorry for the silence here. I haven't been able to track down any help on the accessibility guideline stuff. I did try to create a test that reproduces the failure, but I wasn't able to get it to fail on this branch. Something similar to the below with a few tweaks must do it...

<details>

<summary>My attempt at a repro test</summary>

```dart
  testWidgets('text contrast bug', (WidgetTester tester) async {
    TextFormField getFormField({
      required String labelText,
    }) {
      return TextFormField(
        keyboardType: TextInputType.number,
        validator: (String? value) {
          return 'Please enter $labelText';
        },
        decoration: InputDecoration(
          labelText: labelText,
          helperText: 'helper',
          filled: true,
          helperStyle: TextStyle(backgroundColor: Colors.amber[700]),
          errorStyle: const TextStyle(
            fontSize: 16.0,
          ),
        ),
      );
    }
    final SemanticsHandle handle = tester.ensureSemantics();
    await tester.pumpWidget(MaterialApp(
      home: Scaffold(
        body: Center(
          child: Form(
            child: Column(
              children: [
                getFormField(
                  labelText: 'Deeeeeeee ID',
                ),
                const SizedBox(
                  height: 16,
                ),
                getFormField(
                  labelText: 'Buuuuuuuu ID',
                ),
                const SizedBox(
                  height: 16,
                ),
                const SizedBox(
                  height: 24,
                ),
                Container(
                  width: double.infinity,
                  padding: const EdgeInsetsDirectional.symmetric(horizontal: 8.0),
                  child: FilledButton(
                    onPressed: () {
                    },
                    // TODO(justinmc): Not sure what style to use.
                    child: const Text('Immmmmmmmmm'),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    ));
    await expectLater(tester, meetsGuideline(const MinimumTextContrastGuideline()));
    handle.dispose();
  });
```

</details>

**Comment by bleroux** [comment]
@justinmc Thanks for providing this example. :pray: 
I see that the background color is set for helperStyle, I will try various combination, but I'm not sure it is related because in https://github.com/flutter/flutter/pull/145087#issuecomment-2000811471 you mentionned that it was related to the error message (I will tweak errorStyle too).

In the meantime, while playing with this test, I can make it fails by using obviously wrong colors (in this case it fails even without using this branch). Looking at the error message I see that it gives a clue to which text is involved and which colors, it might help us to repro if we can see the error message from the failing customer test.

Here is an example of the error message for a test that fails on the text contrast guideline :

```
   Which: SemanticsNode#5(Rect.fromLTRB(12.0, 64.0, 86.4, 80.0), label: "helper", textDirection:
ltr):
          Expected contrast ratio of at least 4.5 but found 1.94 for a font size of 12.0.
          The computed colors was:
          light - Color(0xfffef7ff), dark - Color(0xffffa000)
          See also: https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

          SemanticsNode#7(Rect.fromLTRB(12.0, 64.0, 86.4, 80.0), label: "helper", textDirection:
```

**Comment by justinmc** [comment]
Updated my previous comment with improvements to the test code, but it still doesn't fail.

I thought it might be checking the contrast during the time that the text color is animating to the error state, but that didn't seem to be it with a quick attempt. I'll keep investigating.

**Comment by bleroux** [comment]
@justinmc 
https://github.com/flutter/flutter/issues/146507 might be related to the failure.
As you rightly pointed:
"the accessibility test inflates the bounds by 4 pixels. Maybe that's now enough to overlap with the bottom of the field, so it's "seeing" some additional color that it wasn't before?"
So yes, for a filled text field, a 1 pixel red line will be inside the area and wasn't before my PR.
I will file a PR for https://github.com/flutter/flutter/issues/146507 tomorrow, it might break internal tests if they rely on golden. But it we can land it, I will be eager to see if it helps here.
