### PR TITLE
[flutter_tools] add a mechanism to turn off immediate tool exit

### LINKED ISSUE #4674: gracefully handle when ~/.flutter is not writable
We should handle situations where we're not able to write to `~/.flutter`. The solution might look something like:
- disabling analytics for that run
- not displaying the large, multi-line analytics warning
- possibly showing a one line warning about being unable to write to the settings file

### LINKED ISSUE #66786: Need a mechanism to disable global exit due to permissions on operations that can be allowed to fail
For example, if we failing to write to flutter settings due to permission, the tool should not crash. Possibly need to add some sort of bypass method on the error handling io class

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Instead of always exiting the tool, provide a mechanism to turn off this behavior for non-critical functionality like configuration and analytics settings.

Fixes https://github.com/flutter/flutter/issues/66786
Fixes https://github.com/flutter/flutter/issues/4674

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/error_handling_io.dart [hunk 1]
```diff
@@ -20,6 +20,23 @@ import 'platform.dart';
...
 
+/// Allow any file system operations executed within the closure to fail with any
+/// operating system error, rethrowing an [Exception] instead of a [ToolExit].
+///
+/// This should not be used with async file system operation.
+///
+/// This can be used to bypass the [ErrorHandlingFileSystem] permission exit
+/// checks for situations where failure is acceptable, such as the flutter
+/// persistent settings cache.
+void withAllowedFailure(void Function() operation) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/error_handling_io.dart:31]: I think this should be a static of `ErrorHandlingFileSystem`. `withAllowedFailure` is a bit too generic by itself. Also, how about `noExitOnFailure` or `exceptionOnFailure` since it's not so much that failures are allowed as it is that they're just presented in a different way.

Comment (zanderso) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:31]: Also, this should account for nesting the calls, and have a test that that is handled correctly.

File: packages/flutter_tools/lib/src/base/error_handling_io.dart [hunk 2]
```diff
@@ -542,26 +561,32 @@ void _handlePosixException(Exception e, String message, int errorCode) {
...
         'Please ensure that the SDK and/or project is installed in a location '
-        'that has read/write permissions for the current user.'
-      );
+        'that has read/write permissions for the current user.';
       break;
     default:
       // Caller must rethrow the exception.
       break;
   }
+  if (errorMessage == null) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/error_handling_io.dart:583]: Consider wrapping the logic from here to the `throwToolExit` in a helper method.

File: packages/flutter_tools/test/general.shard/base/error_handling_io_test.dart [hunk 3]
```diff
@@ -114,6 +115,20 @@ void main() {
       when(mockFileSystem.path).thenReturn(MockPathContext());
     });
 
+    testWithoutContext('bypasses error handling when withAllowedFailure is used', () {
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/base/error_handling_io_test.dart:118]: The behavior of config is changing a bit, too, so it would be good to have a test of that as well.

File: packages/flutter_tools/lib/src/base/error_handling_io.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart:31]: Ahh good point about the nesting, I didn't think of that :)

**Comment by jonahwilliams** [comment]
Ahh TIL that we did not wrap readAsStringSync in error_handling_io. @zanderso was this an intentional choice, or just another method that needs to be added?

I can think of a few cases where we could handle the exception if reading fails ... but that could probably be fixed with this method too

File: packages/flutter_tools/test/general.shard/base/error_handling_io_test.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/test/general.shard/base/error_handling_io_test.dart:130]: Done

File: packages/flutter_tools/lib/src/base/error_handling_io.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/base/error_handling_io.dart]: Done

**Comment by zanderso** [comment]
> Ahh TIL that we did not wrap readAsStringSync in error_handling_io. @zanderso was this an intentional choice, or just another method that needs to be added?

It wasn't intentionally omIt hadn't come up yet.

> I can think of a few cases where we could handle the exception if reading fails ... but that could probably be fixed with this method too

sg.

**Review by zanderso — APPROVED** [review]
