### PR TITLE
fix cupertino page route dismisses hero transition when swipe to the …

### LINKED ISSUE #57581: CupertinoNavigationBar dissapears when sliding back
## Steps to Reproduce

Please see this video to understand steps: https://github.com/braindamagedman/flutter_issues_sample/blob/master/record.mp4
I added options to track my touches on video.

1. Download sample app: https://github.com/braindamagedman/flutter_issues_sample
2. Run it on your device
3. Press btn to open Page2
4. Start sliding back to Page1
5. From the middle of the screen, slide your finger back so that the edge of Page2 touches the edge of the screen
6. After that, **without lifting your finger** slide back completely to Page1

**Expected results:** CupertinoNavigationBar present and shows Page1 text

**Actual results:** CupertinoNavigationBar dissapears

## Flutter doctor:
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2018.3)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```

### PR DESCRIPTION
**Pull request by chunhtai**
…edge

## Description

When doing cupertino back swipe, the page animation will be dismissed/completed when the gesture reach either end of the screen. This will cause the hero controller to remove the overlay entry of the flighting hero. If the user keep holding the finger and swipe, the hero animation will not respond because it is no longer in the overlay

## Related Issues

Fixes https://github.com/flutter/flutter/issues/57581

## Tests

I added the following tests:

See files

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/route.dart [hunk 1]
```diff
@@ -633,7 +636,8 @@ class _CupertinoBackGestureController<T> {
   /// The drag gesture has changed by [fractionalDelta]. The total range of the
   /// drag should be 0.0 to 1.0.
   void dragUpdate(double delta) {
-    controller.value -= delta;
+    final double newValue = controller.value - delta;
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/route.dart:639]: I don't like this solution. Ideally the animation should be smart enough to not send animation status update when there is an ongoing gesture. However, I can't think of a good way to do it because the animation is provided from TransitionRoute and we also need to send animation status update when the gesture is lifted.

File: packages/flutter/lib/src/cupertino/route.dart [hunk 2]
```diff
@@ -633,7 +636,8 @@ class _CupertinoBackGestureController<T> {
   /// The drag gesture has changed by [fractionalDelta]. The total range of the
   /// drag should be 0.0 to 1.0.
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/route.dart:637]: Is this comment about 0.0-1.0 still accurate with the changes?

File: packages/flutter/lib/src/cupertino/route.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/route.dart:639]: So the clamp prevents the animation from finishing by keeping its value between 0.0 and 1.0?  I can't think of a better approach off the top of my head...

**Review by justinmc — APPROVED** [review]
LGTM, just some nits.

File: packages/flutter/test/material/page_test.dart [hunk 3]
```diff
@@ -532,7 +532,9 @@ void main() {
     // Bring it exactly back such that there's nothing to animate when releasing.
     await gesture.moveBy(const Offset(-300, 0));
     await gesture.up();
+    // There will be a tiny animation upon release.
     await tester.pump();
+    await tester.pump(const Duration(milliseconds: 50));
```
Comment (xster) [inline packages/flutter/test/material/page_test.dart:537]: So this causes the side effect that there will always be a ballistic scroll at the end of a drag no matter where we dropped it off?

File: packages/flutter/test/cupertino/route_test.dart [hunk 4]
```diff
@@ -1133,6 +1133,76 @@ void main() {
     expect(nestedObserver.popupCount, 0);
   });
 
+  testWidgets('showCupertinoModalPopup uses root navigator by default', (WidgetTester tester) async {
```
Comment (xster) [inline packages/flutter/test/cupertino/route_test.dart:1136]: Is this description right?

**Review by xster — COMMENTED** [review]
What's triggering the removal of the hero overlay? Is the HorizontalDragGestureRecognizer calling onEnd somehow?

File: packages/flutter/test/cupertino/route_test.dart (hunk 4 above)
Comment (chunhtai) [reply packages/flutter/test/cupertino/route_test.dart:1136]: no its not, thanks for catching it

**Comment by chunhtai** [comment]
> What's triggering the removal of the hero overlay? Is the HorizontalDragGestureRecognizer calling onEnd somehow?

It trigger removal when the animation status become dismissed or completed. The animation of the route is AnimationController, that it will update its status to dismissed if its value reach 0 or completed if reach 1.0

https://github.com/flutter/flutter/blob/5663e02645a6e69fedfe8553cbe7940cbb592be9/packages/flutter/lib/src/animation/animation_controller.dart#L398

File: packages/flutter/test/cupertino/page_test.dart [hunk 5]
```diff
@@ -457,7 +457,9 @@ void main() {
     // Bring it exactly back such that there's nothing to animate when releasing.
     await gesture.moveBy(const Offset(-300, 0));
     await gesture.up();
+    // There will be a tiny animation upon release.
     await tester.pump();
+    await tester.pump(const Duration(milliseconds: 50));
```
[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/test/cupertino/page_test.dart:462]: I want to make sure the ballistic scroll is small enough that can be neglect by human eyes.

File: packages/flutter/test/material/page_test.dart (hunk 3 above)
Comment (chunhtai) [reply packages/flutter/test/material/page_test.dart:537]: yes, I try to update the test to make sure it just requires a small pump to finish the ballistic scroll that can be neglected by human eyes

**Comment by xster** [comment]
ah ya, that's unfortunate. Looks like native iOS allows for the page to be fully swiped to the edge then back too. 

Changing the whole animation controller behavior is probably too big of a change. What about making use of navigator didStartUserGesture and somehow not hooking the animation status listener until the gesture stopped?

File: packages/flutter/test/cupertino/page_test.dart (hunk 5 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/test/cupertino/page_test.dart:462]: Ah I see, sounds good.

**Comment by chunhtai** [comment]
> ah ya, that's unfortunate. Looks like native iOS allows for the page to be fully swiped to the edge then back too.
> 
> Changing the whole animation controller behavior is probably too big of a change. What about making use of navigator didStartUserGesture and somehow not hooking the animation status listener until the gesture stopped?

thank you. I think i found a better solution and avoid the breaking change. @justinmc @xster  ready for review

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 6]
```diff
@@ -533,6 +533,14 @@ class _HeroFlight {
   }
 
   void _handleAnimationUpdate(AnimationStatus status) {
+    // The animation will not finish until the user lift their finger, so we
+    // should ignore the status update if the gesture is in progress.
+    //
+    // This also relies on the animation to update its status at the end of the
+    // gesture. See the _CupertinoBackGestureController.dragEnd for how
+    // cupertino page route achieves that.
+    if (manifest.fromRoute?.navigator?.userGestureInProgress == true)
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/heroes.dart:542]: One thing that troubles me in this approach is that we push the responsibility, that gesture should trigger animation update when it ends, to the route transition class. I am worrying the third party library developer might trip on this

Comment (xster) [reply packages/flutter/lib/src/widgets/heroes.dart:542]: I think we already crossed that bridge. Since Navigator and Hero are both from the widgets package and heroes.dart is already making use of the user gesture state.

Comment (xster) [reply packages/flutter/lib/src/widgets/heroes.dart:542]: Does this still work if the user dragged it to the end and dropped it exactly there?

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/heroes.dart:542]: yes we have tests to ensure that https://github.com/flutter/flutter/blob/fed18fc4331e6b109ff96be87cd209730b514246/packages/flutter/test/material/page_test.dart#L541
https://github.com/flutter/flutter/blob/fed18fc4331e6b109ff96be87cd209730b514246/packages/flutter/test/material/page_test.dart#L506

**Comment by chunhtai** [comment]
@justinmc the pr has changed a lot since your last review, can you take another look?

File: packages/flutter/test/cupertino/route_test.dart [hunk 7]
```diff
@@ -1133,6 +1133,76 @@ void main() {
...
+    box = tester.renderObject(find.byKey(container)) as RenderBox;
+    final double finalPosition = box.localToGlobal(Offset.zero).dx;
+
+    final TestGesture gesture = await tester.startGesture(const Offset(5, 300));
+    await gesture.moveBy(const Offset(200, 0));
+    await tester.pump();
+    box = tester.renderObject(find.byKey(container)) as RenderBox;
+    final double firstPosition = box.localToGlobal(Offset.zero).dx;
+    // Checks the hero is in-transit.
+    expect(finalPosition > firstPosition, isTrue);
```
Comment (justinmc) [inline packages/flutter/test/cupertino/route_test.dart:1184]: Nit: Same thing, but maybe the error message is more informative if you do this:

```suggestion
    expect(finalPosition, greaterThan(firstPosition));
```

**Review by justinmc — APPROVED** [review]
LGTM, just two nits.
