### PR TITLE
Route.didMount should throw a useful error message

### LINKED ISSUE #4655: Crash in test using Route
## Steps to Reproduce

Run a test with the following code:
```
class SomePageRoute<T> extends PageRoute<T> {
  SomePageRoute(
      {Completer<T> completer, RouteSettings settings: const RouteSettings()})
      : super(completer: completer, settings: settings);

  @override
  Duration get transitionDuration => const Duration(milliseconds: 1);

  @override
  Color get barrierColor => null;

  @override
  Widget buildPage(BuildContext context, _, __) {
    return new Text('hello');
  }
}

void main() {
  testWidgets('builds', (WidgetTester tester) async {
    final widget = new MaterialApp(onGenerateRoute: (RouteSettings settings) {
      return new SomePageRoute();
    });
    await tester.pumpWidget(widget);
}
```

Most likely due to https://github.com/flutter/flutter/pull/4636.

/cc @abarth 

## Flutter Doctor

```
$ flutter doctor
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/pylaligand/Work/turquoise/sync_flutter_for_sysui/src/third_party/flutter
    • Framework revision e502e9c8f8 (6 hours ago), engine revision c69d907b49

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.26
```

## Logs and Crash Reports

```
════════════════
The following NoSuchMethodError was thrown building Title(color: Color(0xff2196f3)):
The null object does not have a getter 'context'.

NoSuchMethodError: method not found: 'context'
Receiver: null
Arguments: []

When the exception was thrown, this was the stack:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ModalRoute.didPush (package:flutter/src/widgets/routes.dart:528:55)
#3      NavigatorState._push.<anonymous closure> (package:flutter/src/widgets/navigator.dart:392:13)
#4      State.setState (package:flutter/src/widgets/framework.dart:433:24)
#5      NavigatorState._push (package:flutter/src/widgets/navigator.dart:387:5)
#6      NavigatorState.initState (package:flutter/src/widgets/navigator.dart:325:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:1659:14)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:1004:12)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582:16)
#12     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484:5)
#13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556:5)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551:5)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:1004:12)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582:16)
#18     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484:5)
#19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556:5)
#20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551:5)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:1004:12)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582:16)
#24     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484:5)
#25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556:5)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551:5)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:1004:12)
#29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:2232:14)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:1004:12)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582:16)
#33     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484:5)
#34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556:5)
#35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551:5)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:1004:12)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582:16)
#39     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484:5)
#40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556:5)
#41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551:5)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:1004:12)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582:16)
#45     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484:5)
#46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556:5)
#47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:1673:22)
#48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551:5)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127:14)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:1004:12)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582:16)
#52     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484:5)
#53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556:5)
#54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551:5)
#55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127:14)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:1004:12)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582:16)
#58     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484:5)
#59     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556:5)
#60     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:1673:22)
#61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551:5)
#62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127:14)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:1004:12)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582:16)
#65     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484:5)
#66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556:5)
#67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551:5)
#68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127:14)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:1004:12)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582:16)
#71     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484:5)
#72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556:5)
#73     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:1673:22)
#74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551:5)
#75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127:14)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:1004:12)
#77     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:359:14)
#78     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:307:17)
#79     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:794:15)
#80     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:301:11)
#81     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding._runApp (package:flutter/src/widgets/binding.dart:230:7)
#82     runApp (package:flutter/src/widgets/binding.dart:245:45)
#83     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:166:7)
#86     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:38)
#87     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:165:27)
#88     main.<anonymous closure>.<<anonymous closure>_async_body> (/some/path/to/src/common/test/delegating_page_route_test.dart:15:18)
#98     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:493:16)
#99     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:348:5)
#100    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:479:24)
#106    AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:477:16)
#107    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:52:50)
#108    Declarer.test.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:test/src/backend/declarer.dart:88:19)
#120    Declarer._runSetUps.<_runSetUps_async_body> (package:test/src/backend/declarer.dart:167:3)
(elided 63 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package
stack_trace)
```

### PR DESCRIPTION
**Pull request by abarth**
The error code path wasn't actually getting the point where it would throw the
useful error message. Also, fix error recovery when runApp fails.

Fixes #4655

### CODE REVIEW

File: packages/flutter_test/lib/src/widget_tester.dart [hunk 1]
```diff
@@ -162,9 +162,9 @@ class WidgetTester extends WidgetController implements HitTestDispatcher {
     Duration duration,
     EnginePhase phase = EnginePhase.sendSemanticsTree
   ]) {
-    return TestAsyncUtils.guard(() {
+    return TestAsyncUtils.guard(() async {
```
Comment (Hixie) [inline packages/flutter_test/lib/src/widget_tester.dart]: do you still need this change? Looking at the code more it seems like it's intentionally not async.

**Comment by Hixie** [comment]
LGTM except for the flutter_test change which I'd rather do in a separate patch if we do it.

File: packages/flutter_test/lib/src/widget_tester.dart (hunk 1 above)
Comment (abarth) [inline packages/flutter_test/lib/src/widget_tester.dart]: No, I don't need this.
