### PR TITLE
Making DropdownButtonFormField to re-render if parent widget changes

### LINKED ISSUE #56716: Unable to set initial value to DropdownButtonFieldForm [1.17.0]
## Steps to Reproduce

1. Assign a default value in `value` for `DropdownButtonFormField`.

**Expected results:** The dropdown should show the value

**Actual results:** dropdown is showing blank value

## Note:
- I am facing this after upgrading to `1.17.0`. My previous version was `1.12.13`.
- On `1.17.0`, `DropdownButton` works fine but `DropdownButtonFormField` doesn't

## Flutter Doctor:

```
[✓] Flutter (Channel stable, v1.17.0, on Linux, locale en_IN)
    • Flutter version 1.17.0 at /home/arnold/flutter
    • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/arnold/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/arnold/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at /home/arnold/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.43.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

```

</details>

### LINKED ISSUE #56898: DropdownButtonFormField is not re-rendered after value is changed programmatically
I just created a simple app in order to see what am I doing wrong

The code:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  List<int> myList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0];
  int currentNumber = 1;
  int anotherNumber = 9;

  void _incrementCounter() {
    setState(() {
      _counter++;
      anotherNumber = _counter;
      currentNumber = _counter;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            DropdownButtonFormField<int>(
              value: currentNumber,
              items: myList.map((int value) {
                return DropdownMenuItem<int>(
                  value: value,
                  child: Container(
                    width: 200,
                    child: Text(
                      value.toString(),
                    ),
                  ),
                );
              }).toList(),
              onChanged: (int newValue) {
                setState(() {
                  anotherNumber = newValue;
                  currentNumber = newValue;
                });
              },
            ),
            DropdownButtonFormField<int>(
              value: anotherNumber,
              items: myList.map((int value) {
                return DropdownMenuItem<int>(
                  value: value,
                  child: Container(
                    width: 200,
                    child: Text(
                      value.toString(),
                    ),
                  ),
                );
              }).toList(),
              onChanged: (int newValue) {
                setState(() {
                  anotherNumber = newValue;
                });
              },
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

The flutter doctor -v:

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-RS)
    • Flutter version 1.17.0 at /Users/lazarjovicic/flutter
    • Framework revision e6b34c2b5c (9 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lazarjovicic/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • SM G970F • RF8M728WTMP • android-arm64 • Android 10 (API 29)

• No issues found!

```

The demonstration with code above:
https://streamable.com/fwwd46
EDIT: 
The Expectation:
Update the first dropdown filed -> the second dropdown field will be updated automatically

The Result: 
Update the first dropdown field -> the second dropdown field remains unchanged.

Please let me know if you need additional information or any further explanation regarding the problem.

Thanks

### PR DESCRIPTION
**Pull request by pedromassango**
## Description

I'm just making DropdownButtonFormField to show new value by overriding the `didUpdateWidget()` function and replacing the current value with the new widget instance's value.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/56898
Fixes https://github.com/flutter/flutter/issues/56716

## Tests

I added the following tests:
- A test to ensure that the rendered DropdownButtonFormField contains updated text from the passed in `value`.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 1]
```diff
@@ -715,4 +715,52 @@ void main() {
     expect(value, equals('two'));
     expect(dropdownButtonTapCounter, 2); // Should not change.
   });
+
+  testWidgets('DropdownButtonFormField should re-render if value param changes', (WidgetTester tester) async {
+    String currentValue = 'two';
+    final GlobalKey<FormFieldState<String>> key = GlobalKey<FormFieldState<String>>();
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:721]: This key does not seem necessary. I think it could just be removed.

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 2]
```diff
@@ -715,4 +715,52 @@ void main() {
...
+        builder: (BuildContext context, StateSetter setState) {
+          return MaterialApp(
+            home: Material(
+              child: DropdownButtonFormField<String>(
+                key: key,
+                value: currentValue,
+                hint: const Text('Select Value'),
+                decoration: const InputDecoration(
+                    prefixIcon: Icon(Icons.fastfood)
+                ),
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:734]: These params (`hint` and `decoration`) do not seem necessary. It would be better to remove them to make the test clearer.

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 3]
```diff
@@ -715,4 +715,52 @@ void main() {
...
+                    onTap: () {
+                      setState(() {
+                        currentValue = value;
+                      });
+                    },
+                  );
+                }).toList(),
+                onChanged: (String _) {
+                  // Ignored
+                },
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:748]: I think `onChanged` does not need to be defined for the `DropdownButtonFormField` to be enabled. If that's the case, we can remove this parameter as well.

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 4]
```diff
@@ -715,4 +715,52 @@ void main() {
...
+              ),
+            ),
+          );
+        },
+      ),
+    );
+
+    expect(currentValue, equals('two'));
+
+    await tester.tap(find.byType(dropdownButtonType).last);
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:758]: There should only be one instance of DropdownButton in this test:
```suggestion
    await tester.tap(find.byType(dropdownButtonType));
```

Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:758]: Add a comment to explain what the steps of the test accomplish. For example:
```suggestion
    // Taps the dropdown button to open the menu item.
    await tester.tap(find.byType(dropdownButtonType).last);
```

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 5]
```diff
@@ -715,4 +715,52 @@ void main() {
...
+    await tester.pumpAndSettle();
+
+    await tester.tap(find.text('one').last);
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:761]: Add a comment to explain what the steps of the test accomplish. For example:
```suggestion
    // Tap the first dropdown menu item.
    await tester.tap(find.text('one').last);
```

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 6]
```diff
@@ -715,4 +715,52 @@ void main() {
...
+                  // Ignored
+                },
+              ),
+            ),
+          );
+        },
+      ),
+    );
+
+    expect(currentValue, equals('two'));
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:756]: The problem with this expect statement is that is does not check the rendered value. This only checks to see if the state value has updated (This test would pass even without the change that was introduced in `dropdown.dart`). You will need to check the value of the text in the `DropdownButtonFormField` as well.

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 7]
```diff
@@ -715,4 +715,52 @@ void main() {
...
+
+    await tester.tap(find.byType(dropdownButtonType).last);
+    await tester.pumpAndSettle();
+
+    await tester.tap(find.text('one').last);
+    await tester.pumpAndSettle();
+
+    expect(currentValue, equals('one'));
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:764]: Same comment as above:
The problem with this expect statement is that is does not check the rendered value. This only checks to see if the state value has updated. You will need to check the value of the text in the `DropdownButtonFormField` as well.

File: packages/flutter/test/material/dropdown_form_field_test.dart (hunk 1 above)
Comment (pedromassango) [reply packages/flutter/test/material/dropdown_form_field_test.dart:721]: Right

File: packages/flutter/test/material/dropdown_form_field_test.dart (hunk 7 above)
Comment (pedromassango) [reply packages/flutter/test/material/dropdown_form_field_test.dart:765]: Right

File: packages/flutter/test/material/dropdown_form_field_test.dart (hunk 6 above)
Comment (pedromassango) [reply packages/flutter/test/material/dropdown_form_field_test.dart:752]: Fixed

File: packages/flutter/test/material/dropdown_form_field_test.dart (hunk 3 above)
Comment (pedromassango) [reply packages/flutter/test/material/dropdown_form_field_test.dart:744]: Sorry I didn't get this

Comment (pedromassango) [reply packages/flutter/test/material/dropdown_form_field_test.dart:744]: Ahhh. Sorry I was confused. I get your point. The problem is that this param is required that is why I didn't removed it.

Do you think that I should (// ignore:) the warning?

Comment (pedromassango) [reply packages/flutter/test/material/dropdown_form_field_test.dart]: I passed the default value created at the start of the file!

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 8]
```diff
@@ -715,4 +715,50 @@ void main() {
...
+  testWidgets('DropdownButtonFormField should re-render if value param changes', (WidgetTester tester) async {
+    String currentValue = 'two';
+
+    await tester.pumpWidget(
+      StatefulBuilder(
+        builder: (BuildContext context, StateSetter setState) {
+          return MaterialApp(
+            home: Material(
+              child: DropdownButtonFormField<String>(
+                key: key,
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:728]: Remove this key, since it isn't necessary.

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 9]
```diff
@@ -715,4 +715,50 @@ void main() {
...
+                value: currentValue,
+                hint: const Text('Select Value'),
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:730]: Remove the hint, since it isn't necessary.

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 10]
```diff
@@ -715,4 +715,50 @@ void main() {
...
+                    value: value,
+                    child: Text(value),
+                    onTap: () {
+                      setState(() {
+                        currentValue = value;
+                      });
+                    },
+                  );
+                }).toList(),
+                onChanged: onChanged,
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:742]: Avoid dangling parameters, as they're easy to miss. We also tend to put child/children params at the end of the parameter list. In this case, the `items` parameter is synonymous to child/children:
```suggestion
                onChanged: onChanged,
                items: menuItems.map((String value) {
                  return DropdownMenuItem<String>(
                    value: value,
                    child: Text(value),
                    onTap: () {
                      setState(() {
                        currentValue = value;
                      });
                    },
                  );
                }).toList(),
```

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 11]
```diff
@@ -715,4 +715,50 @@ void main() {
...
+              ),
+            ),
+          );
+        },
+      ),
+    );
+
+    expect(currentValue, equals('two'));
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:750]: Add a comment to explain why we do this, since future readers of the code might need some more context on why these assertions are important:
```
// Make sure the rendered text value matches the initial state value.
```

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 12]
```diff
@@ -715,4 +715,50 @@ void main() {
...
+
+    // Tap the DropdownButtonFormField widget
+    await tester.tap(find.byType(dropdownButtonType));
+    await tester.pumpAndSettle();
+
+    // Tap the first dropdown menu item.
+    await tester.tap(find.text('one').last);
+    await tester.pumpAndSettle();
+
+    expect(currentValue, equals('one'));
```
Comment (shihaohong) [inline packages/flutter/test/material/dropdown_form_field_test.dart:761]: Add a comment to explain why we do this:
```
// Make sure the rendered text value matches the updated state value.
```

File: packages/flutter/test/material/dropdown_form_field_test.dart (hunk 3 above)
Comment (shihaohong) [reply packages/flutter/test/material/dropdown_form_field_test.dart]: That works! I had assumed that `onChanged` did not need to be defined for the button to be enabled, so this was my mistake as well

**Review by shihaohong — APPROVED** [review]
LGTM!

**Comment by shihaohong** [comment]
@pedromassango The PR seems to be failing `analyze-linux`. Could you fix the analyzer issues in the PR?

**Comment by pedromassango** [comment]
> @pedromassango The PR seems to be failing `analyze-linux`. Could you fix the analyzer issues in the PR?

Of course

**Comment by pedromassango** [comment]
@shihaohong looks like there is something wrong with Flutter build task!

**Comment by shihaohong** [comment]
@pedromassango That's okay. `flutter-build` indicates whether or not the latest build of Flutter is passing all tests or not. It failing means that one of the recent PRs might have broken tests, or that the infrastructure is not functioning as expected or is down.

Since I applied the `waiting for tree to go green` label, this PR will be merged as soon as the tree is green.

**Comment by shihaohong** [comment]
Thanks again for your contribution!

**Comment by pedromassango** [comment]
> @pedromassango That's okay. `flutter-build` indicates whether or not the latest build of Flutter is passing all tests or not. It failing means that one of the recent PRs might have broken tests, or that the infrastructure is not functioning as expected or is down.
> 
> Since I applied the `waiting for tree to go green` label, this PR will be merged as soon as the tree is green.

Thank you for the clarification

**Comment by jlubeck** [comment]
@shihaohong  What would be the proper way to follow this PR landing on Beta???

**Comment by shihaohong** [comment]
@jlubeck Here is the general guideline for beta releases: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#beta, but basically, there should be a beta release roughly once a month.

**Comment by jlubeck** [comment]
@shihaohong ok, so there is no notification or something that would tell me when this got merged into Beta?

**Comment by shihaohong** [comment]
@jlubeck I think the [flutter-announce google group](https://groups.google.com/forum/#!forum/flutter-announce) is your best bet. New releases and breaking change announcements are made through that channel.

**Comment by jlubeck** [comment]
Thank you @shihaohong 
Great work by the way

**Comment by jlubeck** [comment]
Hey @shihaohong sorry to bug you one last time. I guess this is more of a general github usage question? I just saw that a new Flutter 1.18.0-11.1.pre release got pushed to the beta channel. My question was mainly how can I check that this PR is included in that release?

**Comment by shihaohong** [comment]
@jlubeck You can see the commit list on GitHub: https://github.com/flutter/flutter/commits/beta

I don't think this made it into the latest beta release.
