### PR TITLE
[Impeller] Skip clip entity replay that cannot impact current clip.

### LINKED ISSUE #161262: [Impeller] : Issue with Flutter 3.27 optimization for BackdropFilter
### Steps to reproduce

This is very similar to #144211.

I can reproduce this by adding a [Rive](https://rive.app/) asset (animated vector graphics) and then adding a BackdropFilter on top of that asset. The Rive asset does not have to be animated and the issue occurs only when the Rive asset contains two clipping masks. I'm not sure how the [Rive runtime](https://github.com/rive-app/rive-flutter) is built but everything worked fine in Flutter 3.22.2 but it no longer works with Flutter 3.27.1 on iOS - and it's only affecting impeller rendering. If I run with "--no-enable-impeller" the rendering works as expected.

I'm not sure if this affects Android yet, I'm having some troubles getting the impeller to work with Android emulators. This issue does not affect Android or web because these platforms does not use Impeller. I have not tried to enable Impeller on Android.

This bug can be tested in this repo: https://github.com/mikeesouth/rive_mask_backdrop_bug

### Expected results

I expect that the BackdropFilter optimizations in Flutter 3.27 still works on all scenarios that worked in Flutter 3.24 and 3.22.

This is very similar to #144211. that I reported for Flutter 3.19. The backdrop filter optimizations in Flutter 3.19 prevented the backdrop filter to render over the Rive asset with two clipping masks. This was fixed in a later version and it worked correctly in Flutter 3.22 and 3.24 but now the problem is back in Flutter 3.27 - but this time it's inverted (?). The backdrop filter is now ONLY rendered over the Rive asset with two clipping masks and nowhere else. In Flutter 3.19 it was everywhere except the asset with two clipping masks.

### Actual results

Impeller BackdropFilter in Flutter 3.27 only affects Rive assets with two clipping masks if such an asset exists in the scene. This makes all the other widgets look like they are rendered "on top" of the BackdropFilter.

### Code sample

<details open><summary>Code sample</summary>

https://github.com/mikeesouth/rive_mask_backdrop_bug

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Correct results in Flutter 3.22.2:
Correct in Flutter 3_22_2

Incorrect results in Flutter 3.27.1:
Incorrect in Flutter 3_27_1

</details>

### Logs

<details open><summary>Logs</summary>

N/A

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.1 24B83 darwin-arm64, locale en-US)
    • Flutter version 3.27.1 on channel stable at /Users/mickesoderman/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (3 weeks ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mickesoderman/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.96.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available)
    • iPad (10th generation) (mobile) • 2D0C4D99-BF27-44FA-BC07-263E7B8E97D1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.1 24B83 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.1 24B83 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Microsoft Edge 131.0.2903.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/161262

Sometimes we end up with clip replay entities that have clip depth values substantially below the current depth. I suspect this is due to either mismatched save/restore or a bug in our code. Update: this isn't a bug/bug but its definitely a bug. We can have multiple clips per save, but the restore will remove at most one from the record/replay.

If a clip has a depth value that is less than the current clip depth, it cannot by definition impact anything that draws after it.

### CODE REVIEW

File: engine/src/flutter/impeller/entity/entity_pass_clip_stack.cc [hunk 1]
```diff
@@ -83,6 +83,8 @@ EntityPassClipStack::ClipStateResult EntityPassClipStack::RecordRestore(
   if (subpass_state.clip_coverage.back().coverage.has_value()) {
     FML_DCHECK(next_replay_index_ <=
                subpass_state.rendered_clip_entities.size());
+    // This code is slightly wrong and should be popping more than one clip
+    // entry.
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/entity/entity_pass_clip_stack.cc:87]: File an issue and add a TODO with the link.

File: engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc [hunk 2]
```diff
@@ -1591,5 +1591,30 @@ TEST_P(AiksTest, NoDimplesInRRectPath) {
   ASSERT_TRUE(OpenPlaygroundHere(callback));
 }
 
+TEST_P(AiksTest, BackdropFilterOverUnclosedClip) {
+  DisplayListBuilder builder;
+
+  builder.DrawPaint(DlPaint().setColor(DlColor::kWhite()));
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc:1597]: nit: I think this would be easier to follow if you added some curly braces around the save/restores.

**Review by gaaclarke — COMMENTED** [review]
LGTM, just needs an issue filed for the part of the work we aren't completing here.

File: engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc (hunk 2 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/display_list/aiks_dl_basic_unittests.cc:1597]: Done

File: engine/src/flutter/impeller/entity/entity_pass_clip_stack.cc (hunk 1 above)
Comment (jonahwilliams) [reply engine/src/flutter/impeller/entity/entity_pass_clip_stack.cc:88]: Done

**Review by gaaclarke — APPROVED** [review]
lgtm!
