### PR TITLE
Heroes and nested Navigators

### LINKED ISSUE #28042: Crash on Navigator.push when current route has nested Navigator containing pages with Heros
Minimal example:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Root());
}

class Root extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Navigator(
        onGenerateRoute: (settings) => MaterialPageRoute(builder: (context) => Page1()),
      );
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: GestureDetector(
          onTap: () => Navigator.of(context).push(MaterialPageRoute(builder: (context) => Page2())),
          child: Hero(
            tag: "superman",
            child: Container(width: 40, height: 40, color: Colors.red),
          ),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Hero(
            tag: "superman",
            child: GestureDetector(
                onTap: () => Navigator.of(context, rootNavigator: true)
                    .push(MaterialPageRoute(fullscreenDialog: true, builder: (context) => Modal())),
                child: Container(width: 60, height: 60, color: Colors.red))),
      ),
    );
  }
}

class Modal extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(backgroundColor: Colors.purple);
}
```

Tapping the red square twice results in:

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: There are multiple heroes that share the same tag within a subtree.
flutter: Within each subtree for which heroes are to be animated (typically a PageRoute subtree), each Hero
flutter: must have a unique non-null tag.
flutter: In this case, multiple heroes had the following tag: superman
flutter: Here is the subtree for one of the offending heroes:
flutter: # Hero(tag: superman, state: _HeroState#0b567)
flutter: # └KeyedSubtree-[GlobalKey#5c93c]
flutter: #  └Container(bg: BoxDecoration(color: MaterialColor(primary value: Color(0xfff44336))), constraints: BoxConstraints(w=40.0, h=40.0))
flutter: #   └ConstrainedBox(BoxConstraints(w=40.0, h=40.0), renderObject: RenderConstrainedBox#48feb relayoutBoundary=up4)
flutter: #    └DecoratedBox(bg: BoxDecoration(color: MaterialColor(primary value: Color(0xfff44336))), dependencies: [_LocalizationsScope-[GlobalKey#91878], Directionality, MediaQuery], renderObject: RenderDecoratedBox#7672f)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Hero._allHeroesFor.visitor.<anonymous closure> (package:flutter/src/widgets/heroes.dart:210:15)
flutter: #1      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:220:12)
```

In our case `Root` is a widget having several tabs, each with their own Navigator, while the root Navigator is used to (among other things) show modals route on (which should cover the tabbar).

This seems to be the cause of #25362 and #25218, but the issue is more generic.

```
[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.14.3 18D109, locale en-NL)
    • Flutter version 1.2.2-pre.21 at /Users/spkersten/Development/flutter
    • Framework revision 035e0765cc (3 hours ago), 2019-02-16 01:48:28 -0500
    • Engine revision f37b09a11b
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)
```

### PR DESCRIPTION
**Pull request by goderbauer**
## Description

Before this change nested Navigators were causing trouble for Heroes: If the inner Navigator had two PageRoutes on its stack with a Hero tagged "superman" in each of them (because that Hero was supposed to animate between the two PageRoutes) and you were pushing a PageRoute on the outer navigator it would fail because the from route (the one with the nested Navigator) had two Heroes with the same tag. That's legal in the context of the inner Navigator, but was causing trouble for the outer Navigator (it would assert).

This PR changes which Heroes are considered for animation **for nested Navigators only**: If the source or destination route for a potential Hero transition contain nested Navigators, only the Heroes in the top-most Route (which has to be a PageRoute) of that nested Navigator are considered for animation. 

This is preserving the (existing) behavior of animating a Hero from a PageRoute in the outer Navigator to a PageRoute in the inner navigator (I'll add a test for this).

It's an alternative to the approach suggested in https://github.com/flutter/flutter/pull/28420.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/28042

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by goderbauer** [comment]
@spkersten What do you think about this approach? Can you check that this change works for your use cases?

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 1]
```diff
@@ -110,6 +111,14 @@ Rect _globalBoundingBoxFor(BuildContext context) {
 /// B to A, route A's hero's widget is, by default, placed over where route B's
 /// hero's widget was, and then the animation goes the other way.
 ///
+/// ## Nested Navigators
```
Comment (xster) [inline packages/flutter/lib/src/widgets/heroes.dart]: The previous header only makes sense if there was only one header. We should refactor the doc a bit and split it up if there's more than one.

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 2]
```diff
@@ -194,36 +203,55 @@ class Hero extends StatefulWidget {
   final bool transitionOnUserGestures;
 
   // Returns a map of all of the heroes in context, indexed by hero tag.
-  static Map<Object, _HeroState> _allHeroesFor(BuildContext context, bool isUserGestureTransition) {
+  static Map<Object, _HeroState> _allHeroesFor(
+      BuildContext context,
+      bool isUserGestureTransition,
+      NavigatorState triggeringNavigator,
```
Comment (xster) [inline packages/flutter/lib/src/widgets/heroes.dart]: This needs private docs. Also triggering seems a bit tight. Maybe transitioning?

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 3]
```diff
@@ -194,36 +203,55 @@ class Hero extends StatefulWidget {
...
-            if (result.containsKey(tag)) {
-              throw FlutterError(
-                'There are multiple heroes that share the same tag within a subtree.\n'
-                'Within each subtree for which heroes are to be animated (typically a PageRoute subtree), '
-                'each Hero must have a unique non-null tag.\n'
-                'In this case, multiple heroes had the following tag: $tag\n'
-                'Here is the subtree for one of the offending heroes:\n'
-                '${element.toStringDeep(prefixLineOne: "# ")}'
-              );
+          if (Navigator.of(hero) == triggeringNavigator) {
```
Comment (xster) [inline packages/flutter/lib/src/widgets/heroes.dart]: worth going through the mental exercise of whether nullOk could ever be needed. But seems ok.

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 4]
```diff
@@ -194,36 +203,55 @@ class Hero extends StatefulWidget {
...
+            addHero(hero, tag);
+          } else {
+            // Nested navigators: only consider heros in the topmost route of
```
Comment (xster) [inline packages/flutter/lib/src/widgets/heroes.dart]: Document more how this is derived. e.g. the nearest navigator to the hero is not the navigator of the route currently transitioning.

**Review by xster — COMMENTED** [review]
Approach LG

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 3 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/heroes.dart]: This is triggered by a NavigatorObserver on Routes inside the observed Navigator. We only look for Heroes inside those routes, so there has to be a Navigator for them by definition.

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/heroes.dart]: What's your suggestion? I thought of "Nested Navigators" as just a sub-topic of what's there to Discuss on this Widget (I realize now it should have `###` instead of just `##`).

Comment (xster) [reply packages/flutter/lib/src/widgets/heroes.dart]: ### is fine

**Comment by spkersten** [comment]
@goderbauer From reading the code and description this looks like it will fit our use case. I haven't had time to actually test it though.

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 5]
```diff
@@ -193,37 +202,61 @@ class Hero extends StatefulWidget {
...
-                'Here is the subtree for one of the offending heroes:\n'
-                '${element.toStringDeep(prefixLineOne: "# ")}'
-              );
+          if (Navigator.of(hero) == navigator) {
+            addHero(hero, tag);
+          } else {
+            // The nearest navigator to the Hero is not the Navigator that is
+            // currently transitioning from one route to another. This means,
+            // the Hero is inside a nested Navigator and should only be
+            // considered for animation, if it is part of the top-most route in
```
Comment (xster) [inline packages/flutter/lib/src/widgets/heroes.dart]: There's some comma issues in this sentence.

**Review by xster — COMMENTED** [review]
LGTM

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 6]
```diff
@@ -110,6 +111,14 @@ Rect _globalBoundingBoxFor(BuildContext context) {
 /// B to A, route A's hero's widget is, by default, placed over where route B's
 /// hero's widget was, and then the animation goes the other way.
 ///
+/// ### Nested Navigators
+///
+/// If either or both routes contain nested [Navigator]s, only [Hero]s
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/heroes.dart]: If there aren't any nested navigators we still only consider heroes from the topmost route?

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 7]
```diff
@@ -193,37 +202,61 @@ class Hero extends StatefulWidget {
...
 
-  // Returns a map of all of the heroes in context, indexed by hero tag.
-  static Map<Object, _HeroState> _allHeroesFor(BuildContext context, bool isUserGestureTransition) {
+  // Returns a map of all of the heroes in `context` indexed by hero tag that
+  // should be considered for animation when `navigator` transitions from one
+  // PageRoute to another.
+  static Map<Object, _HeroState> _allHeroesFor(
+      BuildContext context,
+      bool isUserGestureTransition,
+      NavigatorState navigator,
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/heroes.dart]: We should probably assert navigator != null, just for good measure

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 8]
```diff
@@ -193,37 +202,61 @@ class Hero extends StatefulWidget {
...
     assert(context != null);
     assert(isUserGestureTransition != null);
     final Map<Object, _HeroState> result = <Object, _HeroState>{};
+
+    void addHero(StatefulElement hero, Object tag) {
+      assert(() {
+        if (result.containsKey(tag)) {
+          throw FlutterError(
+            'There are multiple heroes that share the same tag within a subtree.\n'
+            'Within each subtree for which heroes are to be animated (typically a PageRoute subtree), '
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/heroes.dart]: We only look for Heroes in PageRoutes, not just typically (see _maybeStartHeroTransition)

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 9]
```diff
@@ -193,37 +202,61 @@ class Hero extends StatefulWidget {
...
-                'Within each subtree for which heroes are to be animated (typically a PageRoute subtree), '
-                'each Hero must have a unique non-null tag.\n'
-                'In this case, multiple heroes had the following tag: $tag\n'
-                'Here is the subtree for one of the offending heroes:\n'
-                '${element.toStringDeep(prefixLineOne: "# ")}'
-              );
+          if (Navigator.of(hero) == navigator) {
+            addHero(hero, tag);
+          } else {
+            // The nearest navigator to the Hero is not the Navigator that is
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/heroes.dart]: Thanks for this explanation!

File: packages/flutter/test/widgets/heroes_test.dart [hunk 10]
```diff
@@ -1383,7 +1383,7 @@ void main() {
 
     await tester.pump();
 
-    // Both Heros exist and seated in their normal parents.
+    // Both Heroes exist and seated in their normal parents.
```
Comment (HansMuller) [inline packages/flutter/test/widgets/heroes_test.dart]: ... and are seated in their normal parents.

I'm not sure we use "seated" anywhere else. I think we mean that the heroes haven't been reparented to the overlay yet, i.e. their flights haven't started.

File: packages/flutter/test/widgets/heroes_test.dart [hunk 11]
```diff
@@ -1450,4 +1450,164 @@ void main() {
...
     expect(find.text('two'), findsOneWidget);
   });
+
+  testWidgets('Can push/pop on outer Navigator if nested Navigator contains Heroes', (WidgetTester tester) async {
+    // Regression test for https://github.com/flutter/flutter/issues/28042.
+
+    const String heroTag = 'You are my hero!';
+    final GlobalKey<NavigatorState> rootNavigator = GlobalKey();
+    final GlobalKey<NavigatorState> nestedNavigator = GlobalKey();
+    final GlobalKey nestedRouteHeroBottom = GlobalKey();
```
Comment (HansMuller) [inline packages/flutter/test/widgets/heroes_test.dart]: Can this key and the next one just be UniqueKey() values or do they really need to be global keys?

**Review by HansMuller — APPROVED** [review]
LGTM, just some random questions about the comments/details

File: packages/flutter/test/widgets/heroes_test.dart (hunk 11 above)
Comment (goderbauer) [reply packages/flutter/test/widgets/heroes_test.dart]: Changed to UniqueKey here and below.

File: packages/flutter/lib/src/widgets/heroes.dart (hunk 6 above)
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/heroes.dart]: The important bit is that in the nested navigator case, its the topmost route **of the nested navigator** (and not the topmost route of the navigator controlling the hero transition)

Comment (goderbauer) [reply packages/flutter/lib/src/widgets/heroes.dart]: I rephrased this a bit and emphasized *nested navigators*.
