### PR TITLE
Reland [#166645] Fix DropdownButtonFormField focusing when replacing FocusNode 

### LINKED ISSUE #166642: DropdownButtonFormField can't be focused/unfocused when replacing FocusNode
### Steps to reproduce

Run the sample try focusing/unfocusing after replacing FocusNode similar to the video sample.

### Expected results

1. DropdownButtonFormField can be focused if it was unfocused and we replaced FocusNode.
2. DropdownButtonFormField can be unfocused if it was focused and we replaced FocusNode.

### Actual results

DropdownButtonFormField can't be focused/unfocused when replacing FocusNode.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: DropdownFocusDemo(),
    );
  }
}

class DropdownFocusDemo extends StatefulWidget {
  const DropdownFocusDemo({super.key});

  @override
  State<DropdownFocusDemo> createState() => _DropdownFocusDemoState();
}

class _DropdownFocusDemoState extends State<DropdownFocusDemo> {
  FocusNode _focusNode = FocusNode();
  String _selectedValue = 'One';

  void _replaceFocusNode() {
    setState(() {
      _focusNode.dispose();
      _focusNode = FocusNode();
      print('FocusNode replaced');
    });
  }

  @override
  void dispose() {
    _focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Dropdown Focus Demo')),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            DropdownButtonFormField<String>(
              focusNode: _focusNode,
              focusColor: Colors.yellow,
              decoration: InputDecoration(
                filled: true,
                contentPadding: EdgeInsets.symmetric(vertical: 100),
              ),
              value: _selectedValue,
              items: const [
                DropdownMenuItem(value: 'One', child: Text('One')),
                DropdownMenuItem(value: 'Two', child: Text('Two')),
              ],
              onChanged: (value) {
                setState(() {
                  _selectedValue = value!;
                });
              },
            ),
            const SizedBox(height: 16),
            ElevatedButton(
              onPressed: () {
                _focusNode.requestFocus();
              },
              child: const Text('Request Focus'),
            ),
            ElevatedButton(
              onPressed: _replaceFocusNode,
              child: const Text('Replace FocusNode'),
            ),
            ElevatedButton(
              onPressed: () {
                FocusManager.instance.primaryFocus?.unfocus();
              },
              child: const Text('Remove FocusNode'),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[[Upload media here]](https://github.com/user-attachments/assets/6ea63510-81c7-4007-a6a1-148f4d485778)

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.3.2 24D81 darwin-arm64, locale en-EG) [1,169ms]
    • Flutter version 3.29.2 on channel stable at /Users/ahmedelsayed/.puro/envs/stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (3 weeks ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [1,263ms]
    • Android SDK at /Users/ahmedelsayed/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • Java binary at: /Users/ahmedelsayed/Library/Java/JavaVirtualMachines/jbr-21.0.6/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment JBR-21.0.6+9-895.97-nomod (build 21.0.6+9-b895.97)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [825ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [13ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [13ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] VS Code (version 1.98.2) [12ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.108.0

[✓] Connected device (5 available) [5.9s]

[✓] Network resources [774ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by AhmedLSayed9**
This is a reland of #166645

fixes #166642

**The newly added tests verify the following behaviors:**

1. DropdownButtonFormField can be focused if it was unfocused and we replaced FocusNode.
2. DropdownButtonFormField can be unfocused if it was focused and we replaced FocusNode.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/material/dropdown.dart [hunk 1]
```diff
@@ -1318,7 +1318,7 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
   _DropdownRoute<T>? _dropdownRoute;
   Orientation? _lastOrientation;
   FocusNode? _internalNode;
-  FocusNode? get focusNode => widget.focusNode ?? _internalNode;
+  FocusNode get focusNode => widget.focusNode ?? _internalNode!;
```
Comment (justinmc) [inline packages/flutter/lib/src/material/dropdown.dart:1321]: The failure seems to just be a null check error in a dropdown test. This changing of the nullability is suspicious.

**Review by justinmc — COMMENTED** [review]
Thanks for following up after this was reverted. Looks like CI is indeed catching a failure here that will need to be fixed before we can reland.

File: packages/flutter/test/material/dropdown_test.dart [hunk 2]
```diff
@@ -2625,6 +2625,90 @@ void main() {
...
+
+    Widget buildFormField() => buildFrame(
+      isFormField: true,
+      buttonKey: buttonKey,
+      onChanged: onChanged,
+      focusNode: focusNode,
+    );
+
+    await tester.pumpWidget(buildFormField());
+    final FocusNode internalNode = tester.widget<Focus>(find.byType(Focus).last).focusNode!;
```
Comment (justinmc) [inline packages/flutter/test/material/dropdown_test.dart]: Actually the failure seems to be coming from here.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 1 above)
Comment (AhmedLSayed9) [reply packages/flutter/lib/src/material/dropdown.dart:1321]: We've agreed both can't be null. See https://github.com/flutter/flutter/pull/166645#discussion_r2049743072

File: packages/flutter/test/material/dropdown_test.dart (hunk 2 above)
Comment (AhmedLSayed9) [reply packages/flutter/test/material/dropdown_test.dart]: That’s true. I’m not sure what changed that caused it to fail.
Anyway, I’ve updated it to use `find.byKey` to access the DropdownButton’s focusNode.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/dropdown.dart:1321]: :+1: This was a red herring. Linking to the real culprit: https://github.com/flutter/flutter/pull/170761#discussion_r2155570901

File: packages/flutter/test/material/dropdown_test.dart [hunk 3]
```diff
@@ -2625,6 +2625,91 @@ void main() {
...
+    Widget buildFormField() => buildFrame(
+      isFormField: true,
+      buttonKey: buttonKey,
+      onChanged: onChanged,
+      focusNode: focusNode,
+    );
+
+    await tester.pumpWidget(buildFormField());
+    final FocusNode internalNode =
+        tester.widget<Focus>(find.byKey(const Key('dropdown-focus'))).focusNode!;
```
Comment (justinmc) [inline packages/flutter/test/material/dropdown_test.dart]: My gut says we should avoid this pattern so we don't end up having key collisions with keys in people's app codebases. Though searching through the codebase it looks like we do use this pattern in a few places, e.g. [in PopupMenu](https://github.com/flutter/flutter/blob/be8cdeb84fcf5e378b68fde3e67455c53c12b203/packages/flutter/lib/src/material/popup_menu.dart#L438).

But I think something like this is a better approach:

```dart
find.descendant(
  of: find.byType(DropdownButton),
  matching: find.byType(Focus),
);
```

**Review by justinmc — COMMENTED** [review]
What do you think about looking up via descendant instead of key? Otherwise looks good.

File: packages/flutter/test/material/dropdown_test.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/test/material/dropdown_test.dart]: Maybe we shouldn't do this in the framework at all? https://github.com/flutter/flutter/pull/170952

Comment (AhmedLSayed9) [reply packages/flutter/test/material/dropdown_test.dart]: Yes, I totally agree since using descendant is safe and reliable enough.

Comment (AhmedLSayed9) [reply packages/flutter/test/material/dropdown_test.dart]: Well, there are two things to note here:
1- We should specify the type as `DropdownButton<String>`.
2- We have to use `.first` because there are multiple `Focus` widgets under `DropdownButton`.

I'll push the update anyway, and if using `.first` turns out to be unreliable, we can revert it.

**Review by justinmc — APPROVED** [review]
LGTM :+1: . Thanks for changing the key thing. I agree the `.first` is not ideal but I think it's better than the key. I'll follow up on my https://github.com/flutter/flutter/pull/170952 PR.

**Review by bleroux — APPROVED** [review]
LGTM! Thanks for this reland 🙏
