### PR TITLE
Assert golden files use the right extension

### LINKED ISSUE #98943: Framework's matchesGoldenFile should assert that file name has right structure
https://github.com/flutter/flutter/pull/98772 broke the tree because the file name provided to matchesGoldenFile was missing `.png`. We should assert that file names have the right structure - maybe even that they are unique at least for the given file?

incorrect:
```dart
matchesGoldenFile('slider_start_text_scale_1_width_0'),
```

correct:
```dart
matchesGoldenFile('slider_start_text_scale_1_width_0.png'),
```

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/98943
This ensures golden files in the framework always have the file extension included.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_goldens/test/flutter_goldens_test.dart [hunk 1]
```diff
@@ -481,6 +481,23 @@ void main() {
         );
       });
 
+      test('asserts .png format', () async {
```
Comment (goderbauer) [inline packages/flutter_goldens/test/flutter_goldens_test.dart:484]: Maybe rewrite these with the `throwsA` type matcher using `having` similarly to how it is done in: https://github.com/flutter/flutter/blob/ab89ce285f76a3fd3a9328ec863f5623cc5ac8bc/packages/flutter/test/gestures/monodrag_test.dart#L60. Unlike that example, you may have to use `await expectLater` since the call is async here.

In general, I find that style less error prone (because the `fail` call is easy to forget) and a little clearer in its intention.

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter_goldens/test/flutter_goldens_test.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter_goldens/test/flutter_goldens_test.dart:484]: Ah! Thank you! I was patting myself on the back fro remembering the `fail`, while simultaneously trying to remember the better way to do it. 😜 
Will update.

File: packages/flutter_goldens/test/flutter_goldens_test.dart [hunk 2]
```diff
@@ -579,6 +599,26 @@ void main() {
...
+        expectLater(
```
Comment (goderbauer) [inline packages/flutter_goldens/test/flutter_goldens_test.dart:603]: I believe you have to await these, no?
