### PR TITLE
Keep Flutter.framework binaries writable so they can be code signed

### LINKED ISSUE #39507: Cannot codesign Flutter.framework, replacing existing signature, Permission denied
## Steps to Reproduce

```
cd dev/
SHARD=add2app_test dart bots/test.dart
```

## Logs
https://cirrus-ci.com/task/6430807339565056?command=test_all#L54
```
total size is 94542653  speedup is 1.00
Stripped /Users/m/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Build/Products/Debug-iphonesimulator/ios_add2app.app/Frameworks/Flutter.framework/Flutter of architectures: armv7 arm64
Code Signing /Users/m/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Build/Products/Debug-iphonesimulator/ios_add2app.app/Frameworks/Flutter.framework with Identity -
/usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements '/Users/m/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Build/Products/Debug-iphonesimulator/ios_add2app.app/Frameworks/Flutter.framework'
/Users/m/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Build/Products/Debug-iphonesimulator/ios_add2app.app/Frameworks/Flutter.framework: replacing existing signature
/Users/m/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Build/Products/Debug-iphonesimulator/ios_add2app.app/Frameworks/Flutter.framework: Permission denied
Command PhaseScriptExecution failed with a nonzero exit code


Test session results, code coverage, and logs:
	/Users/m/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Logs/Test/Test-ios_add2appTests-2019.08.29_11-37-54--0700.xcresult

Testing failed:
	Command PhaseScriptExecution failed with a nonzero exit code
	Testing cancelled because the build failed.

** TEST FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/magder/Library/Developer/Xcode/DerivedData/ios_add2app-btprswwixqqclofvuogmdxvymovu/Build/Intermediates.noindex/ios_add2app.build/Debug-iphonesimulator/ios_add2app.build/Script-7FADF19EC61F97E525982780.sh
(1 failure)
```

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Flutter.framework files were made read-only to "Provide a strong hint to developers that editing Flutter framework headers isn't supported" (https://github.com/flutter/flutter/commit/cb2b89c389e06c2cceb1a3361d520eaccb4cec8c)  However this is making the Flutter binary readonly, which is being copied into the final embedded Frameworks directories, then can't be codesigned.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/39507. 

## Tests

Turn back on add2app shard.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by jmagman** [comment]
This is a bit speculative.  See https://github.com/flutter/flutter/issues/39507#issuecomment-526407580.
1. The original logic was introduced in 2017, so what changed?
2. I wasn't able to reproduce this in a non-module, so what's the difference?
3. This seems flaky.  Even though according to a git bisect this was exposed 20 days ago with https://github.com/flutter/flutter/commit/78cca6250a7104cc1dd89edf1982878530e55ee6, there are many Cirrus runs of add2app that succeeded.  So why is this flaky?

**Comment by jmagman** [comment]
First add2app-macos test passed.  Will keep rebasing to see if it's still flaky.

**Comment by jmagman** [comment]
> First add2app-macos test passed. Will keep rebasing to see if it's still flaky.

Passed a second time.

**Comment by jmagman** [comment]
> > First add2app-macos test passed. Will keep rebasing to see if it's still flaky.
> 
> Passed a second time.

add2app-macos test failed, but got way past signing permissions to a flaky unit test?  So not from this change (though still concerning).
https://cirrus-ci.com/task/4538022030213120

**Comment by jmagman** [comment]
> > > First add2app-macos test passed. Will keep rebasing to see if it's still flaky.
> > 
> > 
> > Passed a second time.
> 
> add2app-macos test failed, but got way past signing permissions to a flaky unit test? So not from this change (though still concerning).
> https://cirrus-ci.com/task/4538022030213120
> 
> > 
> >         Cirrus CI
> >       
> >     [Remove](#)
> >   
> >   
> >       [Instruction test_all failed in 02:52](https://cirrus-ci.com/task/4538022030213120)
> >   
> > 
> >   
> >     
> >       
> >         ✅ 01:41 clone
> > ✅ 00:01 print_date
> > ✅ 00:03 install_cocoapods
> > ✅ 01:06 git_fetch
> > ✅ 05:45 setup
> > ✅ 00:02 setup_xcpretty
> > ❌ 02:52 test_all
> > 

```
> > [[EarlGrey selectElementWithMatcher:grey_buttonTitle(@"Full Screen (Cold)")]
> > performAction:grey_tap()];
> > ```
> > 
> > testFullScreenCanPop, failed: caught "EarlGreyInternalTestInterruptException", "Immediately halt execution of testcase"
> > /tmp/flutter sdk/dev/integration_tests/ios_add2app/ios_add2appTests/IntegrationTests.m:41
> > ```
> > 
> > 
> > [[EarlGrey selectElementWithMatcher:grey_buttonTitle(@"Full Screen (Cold)")]
> > performAction:grey_tap()];
> > ```
> > 
> > testHybridView, Exception: NoMatchingElementException
> > /tmp/flutter sdk/dev/integration_tests/ios_add2app/ios_add2appTests/IntegrationTests.m:114
> > ```
> > 
> > 
> > [[EarlGrey selectElementWithMatcher:grey_buttonTitle(@"Hybrid View (Warm)")]
> > performAction:grey_tap()];
> > ```
> > 
> > testHybridView, failed: caught "EarlGreyInternalTestInterruptException", "Immediately halt execution of testcase"
> > /tmp/flutter sdk/dev/integration_tests/ios_add2app/ios_add2appTests/IntegrationTests.m:114
> > ```
> > 
> > 
> > [[EarlGrey selectElementWithMatcher:grey_buttonTitle(@"Hybrid View (Warm)")]
> > performAction:grey_tap()];
> > ```
> > 
> > 
> >    Executed 4 tests, with 6 failures (6 unexpected) in 22.883 (22.919) seconds
> > 2019-08-30 14:50:15.653 xcodebuild[16360:33968] [MT] IDETestOperationsObserverDebug: 103.533 elapsed -- Testing started completed.
> > 2019-08-30 14:50:15.654 xcodebuild[16360:33968] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
> > 2019-08-30 14:50:15.654 xcodebuild[16360:33968] [MT] IDETestOperationsObserverDebug: 103.533 sec, +103.532 sec -- end
> > 
> > Failing tests:
> >   ios_add2appTests:
> >   	-[FlutterTests testDualFlutterView]
> >   	-[FlutterTests testDualFlutterView]
> >   	-[FlutterTests testFullScreenCanPop]
> >   	-[FlutterTests testFullScreenCanPop]
> >   	-[FlutterTests testHybridView]
> >   	-[FlutterTests testHybridView]
> > 
> > Test session results and logs:
> >   /Users/anka/Library/Developer/Xcode/DerivedData/ios_add2app-csiwhdwugybmwjeggtidemdjpolj/Logs/Test/Test-ios_add2appTests-2019.08.30_14-47-54--0700.xcresult
> > 
> > ** TEST FAILED **
> > 
> > ▌14:50:22▐ ELAPSED TIME: 3min 53.429s for ../../../build_and_test.sh  in dev/integration_tests/ios_add2app
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> > ERROR: Last command exited with 65 (expected: zero).
> > Command: ../../../build_and_test.sh 
> > Relative working directory: dev/integration_tests/ios_add2app
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> > ```
> > 
> > 
> >       
> >       
> >        Show more
> >        Show less

Test Suite ios_add2appTests.xctest started
FlutterTests
    ✗ testDualFlutterView, Exception: NoMatchingElementException
    ✗ testDualFlutterView, failed: caught "EarlGreyInternalTestInterruptException", "Immediately halt execution of testcase"
    ✗ testFullScreenCanPop, Exception: NoMatchingElementException
    ✗ testFullScreenCanPop, failed: caught "EarlGreyInternalTestInterruptException", "Immediately halt execution of testcase"
    ✗ testHybridView, Exception: NoMatchingElementException
    ✗ testHybridView, failed: caught "EarlGreyInternalTestInterruptException", "Immediately halt execution of testcase"
ViewControllerRelease
    ✓ testReleaseFlutterViewController (2.455 seconds)
FlutterTests
  testDualFlutterView, Exception: NoMatchingElementException
  /tmp/flutter sdk/dev/integration_tests/ios_add2app/ios_add2appTests/IntegrationTests.m:96
  ```
  // Verify that there are two Flutter views with the expected marquee text.
  [[[EarlGrey
      selectElementWithMatcher:grey_accessibilityLabel(@"This is Marquee")]
  ```
  testDualFlutterView, failed: caught "EarlGreyInternalTestInterruptException", "Immediately halt execution of testcase"
  /tmp/flutter sdk/dev/integration_tests/ios_add2app/ios_add2appTests/IntegrationTests.m:96
  ```
  // Verify that there are two Flutter views with the expected marquee text.
  [[[EarlGrey
      selectElementWithMatcher:grey_accessibilityLabel(@"This is Marquee")]
  ```
  testFullScreenCanPop, Exception: NoMatchingElementException
  /tmp/flutter sdk/dev/integration_tests/ios_add2app/ios_add2appTests/IntegrationTests.m:41
  ```
  [[EarlGrey selectElementWithMatcher:grey_buttonTitle(@"Full Screen (Cold)")]
      performAction:grey_tap()];
  ```
  testFullScreenCanPop, failed: caught "EarlGreyInternalTestInterruptException", "Immediately halt execution of testcase"
  /tmp/flutter sdk/dev/integration_tests/ios_add2app/ios_add2appTests/IntegrationTests.m:41
  ```
  [[EarlGrey selectElementWithMatcher:grey_buttonTitle(@"Full Screen (Cold)")]
      performAction:grey_tap()];
  ```
  testHybridView, Exception: NoMatchingElementException
  /tmp/flutter sdk/dev/integration_tests/ios_add2app/ios_add2appTests/IntegrationTests.m:114
  ```
  [[EarlGrey selectElementWithMatcher:grey_buttonTitle(@"Hybrid View (Warm)")]
      performAction:grey_tap()];
  ```
  testHybridView, failed: caught "EarlGreyInternalTestInterruptException", "Immediately halt execution of testcase"
  /tmp/flutter sdk/dev/integration_tests/ios_add2app/ios_add2appTests/IntegrationTests.m:114
  ```
  [[EarlGrey selectElementWithMatcher:grey_buttonTitle(@"Hybrid View (Warm)")]
      performAction:grey_tap()];
  ```
	 Executed 4 tests, with 6 failures (6 unexpected) in 22.883 (22.919) seconds
```

**Comment by jmagman** [comment]
> > First add2app-macos test passed. Will keep rebasing to see if it's still flaky.
> 
> Passed a second time.

Passed (the step in question) a fourth time.  Removing WIP.

@cbracken Does any of this make sense to you? https://github.com/flutter/flutter/pull/39539#issuecomment-526421383

File: packages/flutter_tools/bin/xcode_backend.sh [hunk 1]
```diff
@@ -142,11 +142,11 @@ BuildApp() {
     mkdir "${derived_dir}/engine"
     RunCommand cp -r -- "${flutter_podspec}" "${derived_dir}/engine"
     RunCommand cp -r -- "${flutter_framework}" "${derived_dir}/engine"
-    RunCommand find "${derived_dir}/engine/Flutter.framework" -type f -exec chmod a-w "{}" \;
```
Comment (cbracken) [inline packages/flutter_tools/bin/xcode_backend.sh]: Maybe add a comment noting this is marking all non-binary files as read-only so that we can code-sign the binaries.

Comment (cbracken) [reply packages/flutter_tools/bin/xcode_backend.sh]: I also wonder if there's any way to get the same list using only options to `find` rather than feeding it through `grep -Il` then into `xargs`. 

Looking at the manpage, I don't see anything promising though.

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

File: packages/flutter_tools/bin/xcode_backend.sh (hunk 1 above)
Comment (jmagman) [reply packages/flutter_tools/bin/xcode_backend.sh]: That was my first thought but I couldn't find any such flag.

**Comment by jmagman** [comment]
Even though I can't prove this will fix the flaky add-to-app test, I'm going to merge it since I still think it's a good change.  If we continue to see the flakes we can try to gather more info about the environments where this is reproducing.

**Comment by Hixie** [comment]
This broke devicelab, because now we can't delete the flutter repo anymore.
