### PR TITLE
Avoid null check operator failure in RenderFlex._hasOverflow

### LINKED ISSUE #71972: Null check operator error in RenderFlex. _hasOverflow
### Steps to reproduce

Write the following into `test/bug_report.dart`, then test via `flutter test test/bug_report.dart`:

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('bug report', (WidgetTester tester) async {
    await tester.pumpWidget(Row(children: []));
  });
}
```

### Expected behavior

You expect the test to fail because [`Row` requires a text direction](https://github.com/flutter/flutter/blob/bf1091b80db83a2d41d14252b71a3eab06dc7b75/packages/flutter/lib/src/rendering/flex.dart#L464).  But you expect the failure to look something like:

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Horizontal RenderFlex with MainAxisAlignment.start has a null textDirection, so the alignment cannot
be resolved.
'package:flutter/src/rendering/flex.dart':
Failed assertion: line 464 pos 18: 'textDirection != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  Row file:///Users/tvolkert/project/sci/apps/payouts/test/pivot/table_pane.test.dart:7:29

When the exception was thrown, this was the stack:
#2      RenderFlex._debugHasNecessaryDirections (package:flutter/src/rendering/flex.dart:464:18)
#3      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:919:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
...
```

### Actual behavior

In addition to the expected error, you get an ancillary null safety error:

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was:
  Row file:///Users/tvolkert/project/sci/apps/payouts/test/pivot/table_pane.test.dart:7:29

When the exception was thrown, this was the stack:
#0      RenderFlex._hasOverflow (package:flutter/src/rendering/flex.dart:489:37)
#1      RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:10)
#2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
#3      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#4      RenderView.paint (package:flutter/src/rendering/view.dart:214:15)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
#6      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
#7      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#8      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
#9      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1117:27)
#10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:320:5)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1119:15)
#12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1057:9)
#13     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:977:9)
#16     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#17     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:964:27)
#18     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:522:22)
#21     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#22     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:519:27)
#23     main.<anonymous closure> (file:///Users/tvolkert/project/sci/apps/payouts/test/pivot/table_pane.test.dart:7:18)
#24     main.<anonymous closure> (file:///Users/tvolkert/project/sci/apps/payouts/test/pivot/table_pane.test.dart:6:22)
#25     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

The following RenderObject was being processed when the exception was fired: RenderFlex#12e7b:
  creator: Row ← [root]
  parentData: <none>
  constraints: BoxConstraints(w=800.0, h=600.0)
  size: MISSING
  direction: horizontal
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

### Version info

```
[✓] Flutter (Channel master, 1.25.0-5.0.pre.123, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-US)
    • Flutter version 1.25.0-5.0.pre.123 at /Users/tvolkert/project/flutter/flutter
    • Framework revision c8f07aad56 (2 hours ago), 2020-12-08 17:58:28 -0800
    • Engine revision de341faa4d
    • Dart version 2.12.0 (build 2.12.0-125.0.dev)
```

### PR DESCRIPTION
**Pull request by tvolkert**
## Description

This gracefully handles a null `_overflow` value in `RenderFlex._hasOverflow`

## Related Issues

Fixes https://github.com/flutter/flutter/issues/71972

## Tests

I added the following tests:

* A test for the case outlined in the issue.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: packages/flutter/lib/src/rendering/flex.dart [hunk 1]
```diff
@@ -486,7 +486,7 @@ class RenderFlex extends RenderBox with ContainerRenderObjectMixin<RenderBox, Fl
   double? _overflow;
   // Check whether any meaningful overflow is present. Values below an epsilon
   // are treated as not overflowing.
-  bool get _hasOverflow => _overflow! > precisionErrorTolerance;
+  bool get _hasOverflow => _overflow != null && _overflow! > precisionErrorTolerance;
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/flex.dart:489]: If we treat `_overflow == null` as "no overflow", why not just assign `_overflow` an initial value of false and make it non-nullable?

Comment (tvolkert) [reply packages/flutter/lib/src/rendering/flex.dart]: Good point - done.
