### PR TITLE
Fix `NavigationBar` ripple

### LINKED ISSUE #113870: [Material3] Add an option in `NavigationBar` items to disable ripple effects.
## Use case

I need to use `NavigationBar` in my app without ripples, but somehow I didn't find any documentation to disable the ripple.

Just like Google Playstore's bottom nav bar.

## Proposal

As the title suggest.

### LINKED ISSUE #114618: M3 Navigation widgets use wrong ripple
Navigation widgets (NavigationBar and NavigationRail) seem to use a not-spec ripple effect that also is wrongly clipped.

## Steps to Reproduce

1. Create a NavigationBar or NavigationRail 
2. .Hover an item

**Expected results:**
I expected to see an M3 spec ripple on the pill.

This is the [spec](https://m3.material.io/components/navigation-bar/specs#8f59e48a-a2b9-4584-b50d-d24e9e982d04l): 
image

**Actual results:** 
image
As you can see on the third item the ripple is not only behind the "pill" but is behind the entire item, as I said is clipped wrong and it doesn't even go behind the system navigation with the rest of the NavigationBar.

<details>
<summary>To be mentioned</summary>

The exact same problem is present with NavigationRail.
image<h6>The dot represents a device camera </h6>

Some apps adapted this design for the ripple, that extends behind the system navigation:
image
And it would be an amazing thing if this could be implemented in some way.

</details>

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        bottomNavigationBar: NavigationBar(
          labelBehavior: NavigationDestinationLabelBehavior.onlyShowSelected,
          selectedIndex: 0,
          destinations: const [
            NavigationDestination(
              icon: Icon(Icons.home),
              label: 'Page 1',
            ),
            NavigationDestination(
              icon: Icon(Icons.abc),
              label: 'Page 2',
            ),
          ],
          onDestinationSelected: (_) {},
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel beta, 3.4.0-34.1.pre, on Ubuntu 22.10 5.19.0-23-generic, locale en_GB.UTF-8)
    • Flutter version 3.4.0-34.1.pre on channel beta at /home/rares/.apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 71520442d4 (4 weeks ago), 2022-10-05 16:38:28 -0500
    • Engine revision db0cbb2145
    • Dart version 2.19.0 (build 2.19.0-255.2.beta)
    • DevTools version 2.18.0

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/rares/.apps/android-sdk/
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/rares/.apps/jetbrains-toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.2-1
    • cmake version 3.24.2
    • ninja version 1.11.0
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/rares/.apps/jetbrains-toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.10 5.19.0-23-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/114618
fixes #113870

### Description

This PR fixes the large ripple issue and matches NavigationBar states [specs](https://m3.material.io/components/navigation-bar/specs#8f59e48a-a2b9-4584-b50d-d24e9e982d04).

image

Here is a comparison between native and Flutter.  

 While fixing this issue, I noticed indicator animation curves don't match native so I looked into Android [implementation](https://github.com/material-components/material-components-android/blob/d5b41c185ff41243f961784aa5a8382a387aa25a/lib/java/com/google/android/material/navigation/NavigationBarItemView.java#L371) and found the current animation curve in Flutter is incorrect, this is fixed too.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/navigation_bar.dart [hunk 1]
```diff
@@ -17,6 +17,9 @@ import 'text_theme.dart';
 import 'theme.dart';
 import 'tooltip.dart';
 
+const double _kIndicatorHeight = 64;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/navigation_bar.dart:20]: This doesn't look right. What if the app specifies a big NavigationDestination icon?

Comment (TahaTesser) [reply packages/flutter/lib/src/material/navigation_bar.dart:20]: Thanks for your comment. I actually already considered this. 

`NavigationDestination` doesn't allow overriding this width and height indicator and the splash should match the indicator size, not the icon.  

This is how it looks on Android if I provide a bigger item icon size. 
Here you can see splash size remains the same as the indicator shape size, doesn't resize when providing bigger icon size.
Screenshot 2022-11-17 at 11 07 50

This is how it looks in Flutter if we provide a bigger NavigationDestination icon.
```dart
          NavigationDestination(
            icon: Icon(Icons.explore, size: 40),
            label: 'Explore',
          ),
```
ezgif com-gif-maker (1)






### Code reference


https://github.com/flutter/flutter/blob/83d205e9873fd803e032dc65f4b50fa08568c7f2/packages/flutter/lib/src/material/navigation_bar.dart#L332-L336

Here you can see `NavigationDestination` doesn't pass width or height to `NavigationIndicator`.
Screenshot 2022-11-17 at 11 18 28

Comment (HansMuller) [reply packages/flutter/lib/src/material/navigation_bar.dart:20]: Thanks for the nicely illustrated explanation.

File: packages/flutter/lib/src/material/navigation_bar.dart [hunk 2]
```diff
@@ -615,7 +646,7 @@ class NavigationIndicator extends StatelessWidget {
         final double scale = animation.isDismissed
             ? 0.0
             : Tween<double>(begin: .4, end: 1.0).transform(
-            CurveTween(curve: Curves.easeInOutCubicEmphasized).transform(animation.value));
+            CurveTween(curve: Curves.fastOutSlowIn).transform(animation.value));
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/navigation_bar.dart:649]: Why change these curves? I believe that the advice about Motion and Material 3 is that we should always use Curves.easeInOutCubicEmphasized curve.

File: packages/flutter/test/material/navigation_bar_test.dart [hunk 3]
```diff
@@ -553,6 +555,113 @@ void main() {
...
+
+    // Test scale animation with `Curves.fastOutSlowIn`.
+    selectedIndex = 1;
+    await tester.pumpWidget(buildNavigationBar());
+    await tester.pump(const Duration(milliseconds: 100));
+    transformWidget = tester.widget(transformFinder);
+    expect(
+      transformWidget.transform,
+      Matrix4.diagonal3Values(
+        0.4809186697006226,
```
Comment (HansMuller) [inline packages/flutter/test/material/navigation_bar_test.dart:637]: This constant, and the similar ones below, seem like a magnet for confusing FP stability issues. Maybe test one or three elements of of the transform matrix with closeTo.

File: packages/flutter/test/material/navigation_bar_test.dart [hunk 4]
```diff
@@ -553,6 +555,113 @@ void main() {
...
+        },
+      ),
+    );
+
+    await tester.pumpWidget(widget);
+
+    await tester.tap(find.byIcon(Icons.access_alarm));
+    await tester.pump(const Duration(milliseconds: 200));
+
+    final RenderObject inkFeatures = tester.allRenderObjects.firstWhere((RenderObject object) => object.runtimeType.toString() == '_RenderInkFeatures');
```
Comment (HansMuller) [inline packages/flutter/test/material/navigation_bar_test.dart:582]: Should we be checking that a rounded rectangle of the right size is being drawn?

File: packages/flutter/lib/src/material/navigation_bar.dart (hunk 2 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/navigation_bar.dart:649]: After I added the indicator shape ripple and tested the animation progress side by side with Android It felt off to me so I looked into Android implementation to see if it animation curve is the same as in Flutter. After watching it, this looked close to Android. 

See this [source](https://github.com/material-components/material-components-android/blob/d5b41c185ff41243f961784aa5a8382a387aa25a/lib/java/com/google/android/material/navigation/NavigationBarItemView.java#L371)

Screenshot 2022-11-17 at 20 23 44





If this is a deal breaker, I can revert this change and we can consider it in a future PR.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/navigation_bar.dart:649]: Will revert this for now :)

File: packages/flutter/test/material/navigation_bar_test.dart (hunk 3 above)
Comment (TahaTesser) [reply packages/flutter/test/material/navigation_bar_test.dart]: Great point, updated this.

File: packages/flutter/test/material/navigation_bar_test.dart (hunk 4 above)
Comment (TahaTesser) [reply packages/flutter/test/material/navigation_bar_test.dart:586]: There is no rounded rectangle draw since `customBorder` simply adds clipping to `Box.circle` splash shape

So I've updated the test to check `paints..clipPath` with the indicator size. 
Wether it contains an indicator-sized clip-path or not.

**Review by HansMuller — APPROVED** [review]
LGTM
