### PR TITLE
[flutter_tools] Add support for versioned Android cmdline tools

### LINKED ISSUE #76527: Search for versioned cmdline tools instead of always using latest in AndroidSDK
## Steps to Reproduce

1. Run `flutter doctor --android-licenses` with Java 11 and (new) Android SDK command-line tools (new `sdkmanager`, etc.)

## Issue
Instead of using the command-line tools 3.0 installed on the machine, `flutter` sticks to the obsolete tools which are Java-8 only.

## Logs

<details>
<summary>Logs</summary>

```
$ sdkmanager --list_installed      
  ...                     
  cmdline-tools;3.0                                  | 3.0     | Android SDK Command-line Tools          | cmdline-tools/3.0/                                 
  ...
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /home/saschpe/Applications/flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/saschpe/.android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/saschpe/.android/sdk
    • Java binary at: /usr/lib/jvm/java/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 2 categories.
```
```
flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

</details>

### PR DESCRIPTION
**Pull request by GurjinderPartola**
Added a fallback to the highest cmdline-tools version if latest isn't present, and only then fallback to the deprecated SDK tools.

Closes #76527

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/android_sdk.dart [hunk 1]
```diff
@@ -261,23 +261,56 @@ class AndroidSdk {
...
-      return cmdlineToolsBinary.path;
+    if (cmdlineToolsLatestBinary.existsSync()) {
+      return cmdlineToolsLatestBinary.path;
+    }
+
+    // Next look for the highest version of the command-line tools
+    final Directory cmdlineToolsDir = directory.childDirectory('cmdline-tools');
+    if (cmdlineToolsDir.existsSync()) {
+      final List<Version> cmdlineTools = cmdlineToolsDir
+        .listSync()
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/android_sdk.dart:279]: Does this need to filter out files and only include Directories?

Comment (GurjinderPartola) [reply packages/flutter_tools/lib/src/android/android_sdk.dart:279]: Based on the [docs](https://developer.android.com/studio/command-line) I think it should only contain sub-directories.
All files will be discarded later anyways, although we could filter them out early just in case.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Currently working on a google patch so this can roll in

**Comment by jonahwilliams** [comment]
Created the google fix, waiting on testing to rerun

**Comment by jonahwilliams** [comment]
The remaining google3 failure is a flake, will land as soon as the tree is open
