### PR TITLE
ScrollController.jumpTo zero should not trigger the refresh indicator

### LINKED ISSUE #75063: Dragging Scrollbar triggers RefreshIndicator to refresh
Flutter 1.26 adds support for dragging scrollbars.
When a Scrollbar is used with a RefreshIndicator, dragging the Scrollbar triggers the RefreshIndicator to refresh.

I expected that the RefreshIndicator should not be triggered by dragging the Scrollbar, unless ```RefreshIndicator.triggerMode``` is set to ```RefreshIndicatorTriggerMode.anywhere```.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the main.dart file as follows:
```dart
import 'dart:io';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Scrollbar issue'),
      ),
      body: RefreshIndicator(
        onRefresh: () async {
          print('refresh triggered');
          sleep(Duration(milliseconds: 500));
        },
        child: Scrollbar(
          isAlwaysShown: true,
          child: ListView.builder(
            physics: AlwaysScrollableScrollPhysics(),
            itemCount: 10000,
            itemExtent: 50,
            itemBuilder: (context, index) {
              return Container(
                child: Center(child: Text('${index}')),
              );
            },
          ),
        ),
      ),
    );
  }
}
```
3. Drag the scrollbar to bottom and then up rapidly

**Expected results:**
The RefreshIndicator should not be triggered.

**Actual results:**
The RefreshIndicator is triggered and it outputs the "refresh triggered" message.

Screen_Recording_20210130-221633_1_1

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel dev, 1.26.0-17.1.pre, on macOS 11.1 20C69 darwin-arm, locale en-KR)
    • Flutter version 1.26.0-17.1.pre at /Users/idearibosome/flutter
    • Framework revision c40e5294dd (21 hours ago), 2021-01-29 08:44:18 -0800
    • Engine revision 5d3477eab4
    • Dart version 2.12.0 (build 2.12.0-259.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/idearibosome/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • SM G973N (mobile) • R39M10FNK2D • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
### Repro Steps
Call `ScrollController.jumpTo` from 500pixels to 0pixes will trigger the refresh indicator.
See the unit test for details.

### How does it happens

When calling `ScrollController.jumpTo` will trigger three events as follow,

I/flutter (29906): _handleScrollNotification [ScrollStartNotification(depth: 0 (local), FixedScrollMetrics(0.0..[664.3]..499335.7))]
I/flutter (29906): _handleScrollNotification [ScrollUpdateNotification(depth: 0 (local), FixedScrollMetrics(0.0..[664.3]..499335.7), scrollDelta: -500.0)]
I/flutter (29906): _handleScrollNotification [ScrollEndNotification(depth: 0 (local), FixedScrollMetrics(0.0..[664.3]..499335.7))]

The first `ScrollStartNotification` start the indicator at `_shouldStart`
The 2ond and 3rd event show the indicator

```
RefreshIndicator is a widget that supports the Material "swipe to refresh" idiom.
```
According to my understanding, only drag/swipe/pull can trigger the indicator, right?
If someone has a different opinion, please bring it up and we will discuss the solution again.
CC/ @Piinks @chunhtai 

### Solve Solution
We can use `ScrollStartNotification.dragDetails` to distinguish whether the scroll started by a drag.

Fixes #75063

### CODE REVIEW

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 1]
```diff
@@ -262,7 +262,8 @@ class RefreshIndicatorState extends State<RefreshIndicator> with TickerProviderS
   }
 
   bool _shouldStart(ScrollNotification notification) {
-    return (notification is ScrollStartNotification || (notification is ScrollUpdateNotification && notification.dragDetails != null && widget.triggerMode == RefreshIndicatorTriggerMode.anywhere))
+    return ((notification is ScrollStartNotification && notification.dragDetails != null)
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:265]: This is getting more and more mysterious, can you add some comments explain what does it mean when `notification.dragDetails != null` or define boolean getter with a more descriptive name.

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 2]
```diff
@@ -261,6 +261,9 @@ class RefreshIndicatorState extends State<RefreshIndicator> with TickerProviderS
     super.dispose();
   }
 
+  // [dragDetails] is non-null means that the scroll notifications are emitted because of a drag.
+  // The indicator can only be triggered by dragging, and cannot be triggered
+  // by other non-dragging behaviors such as [ScrollController.jumpTo].
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:266]: Can you add more detail on what does it mean when
```
(notification is ScrollStartNotification && notification.dragDetails != null)
```
is true

and 

```
notification is ScrollUpdateNotification && notification.dragDetails != null
```
is true.

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 3]
```diff
@@ -261,6 +261,9 @@ class RefreshIndicatorState extends State<RefreshIndicator> with TickerProviderS
     super.dispose();
   }
 
+  // [dragDetails] is non-null means that the scroll notifications are emitted because of a drag.
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:264]:
```suggestion
  //The [dragDetails] is non-null If the scroll notifications are triggered by dragging.
```

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 4]
```diff
@@ -261,7 +261,7 @@ class RefreshIndicatorState extends State<RefreshIndicator> with TickerProviderS
     super.dispose();
   }
 
-  // [dragDetails] is non-null means that the scroll notifications are emitted because of a drag.
+  //The [dragDetails] is non-null If the scroll notifications are triggered by dragging.
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:264]: ah lower case `if`, sorry i had an typo

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 5]
```diff
@@ -261,8 +261,14 @@ class RefreshIndicatorState extends State<RefreshIndicator> with TickerProviderS
     super.dispose();
   }
 
+  // The [dragDetails] is non-null if the scroll notifications are triggered by dragging.
+  // The indicator can only be triggered by dragging, and cannot be triggered
+  // by other non-dragging behaviors such as [ScrollController.jumpTo].
+  // See also [RefreshIndicator.triggerMode].
   bool _shouldStart(ScrollNotification notification) {
-    return (notification is ScrollStartNotification || (notification is ScrollUpdateNotification && notification.dragDetails != null && widget.triggerMode == RefreshIndicatorTriggerMode.anywhere))
+    return ((notification is ScrollStartNotification && notification.dragDetails != null) // Start dragging at zero scroll position.
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:269]: This comment is a bit confusing, I think what I am looking for is why we need to check notification.dragDetails != null, This seems to be quite convoluted.

I assume something the explanation will be something like this.

```
If the notification.dragDetails is null, this scroll is not triggered by user dragging. It may be a result of ScrollController.jumpTo. In this case we don't want to trigger the refresh indicator.
```

Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:269]: now i looked at this again lets break up this function a bit to be more

```dart
bool _shouldStart(ScrollNotification notification) {
    // If the notification.dragDetails is null, this scroll is not triggered by user dragging. It may be a result of ScrollController.jumpTo or a ballistic scroll. In this case we don't want to trigger the refresh indicator.
    if (notification.dragDetails == null)
      return false;
    return (notification is ScrollStartNotification || (notification is ScrollUpdateNotification && 
   widget.triggerMode == RefreshIndicatorTriggerMode.anywhere))
      && notification.metrics.extentBefore == 0.0
      && _mode == null
      && _start(notification.metrics.axisDirection);
  }
```

**Review by chunhtai — APPROVED** [review]
Sorry, this has taken a bit long, but this is my last nits, otherwise this looks good to me

File: packages/flutter/lib/src/material/refresh_indicator.dart (hunk 5 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/refresh_indicator.dart:269]: It seems that the logic is much clearer. 👍

**Comment by xu-baolin** [comment]
@Piinks Hey, do you have any thoughts here, I saw you had a self-requested review of this.

**Comment by xu-baolin** [comment]
oops, ScrollNotification does not have dragDetails property. I will fix it.

File: packages/flutter/lib/src/material/refresh_indicator.dart (hunk 5 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/refresh_indicator.dart]: Considering the performance, I had to change it to what it was before, but modify the comment as you suggested.
```dart
  bool _shouldStart(ScrollNotification notification) {
    // If the notification.dragDetails is null, this scroll is not triggered by
    // user dragging. It may be a result of ScrollController.jumpTo or a ballistic scroll.
    // In this case we don't want to trigger the refresh indicator.
    return ((notification is ScrollStartNotification && notification.dragDetails != null)
            || (notification is ScrollUpdateNotification && notification.dragDetails != null && widget.triggerMode == RefreshIndicatorTriggerMode.anywhere))
      && notification.metrics.extentBefore == 0.0
      && _mode == null
      && _start(notification.metrics.axisDirection);
  }
```
Any suggestions?

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 6]
```diff
@@ -262,7 +262,11 @@ class RefreshIndicatorState extends State<RefreshIndicator> with TickerProviderS
   }
 
   bool _shouldStart(ScrollNotification notification) {
-    return (notification is ScrollStartNotification || (notification is ScrollUpdateNotification && notification.dragDetails != null && widget.triggerMode == RefreshIndicatorTriggerMode.anywhere))
+    // If the notification.dragDetails is null, this scroll is not triggered by
+    // user dragging. It may be a result of ScrollController.jumpTo or a ballistic scroll.
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:266]:
```suggestion
    // user dragging. It may be a result of ScrollController.jumpTo or ballistic scroll.
```

File: packages/flutter/lib/src/material/refresh_indicator.dart [hunk 7]
```diff
@@ -262,7 +262,11 @@ class RefreshIndicatorState extends State<RefreshIndicator> with TickerProviderS
...
+    // In this case we don't want to trigger the refresh indicator.
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/refresh_indicator.dart:267]:
```suggestion
    // In this case, we don't want to trigger the refresh indicator.
```

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by Piinks — APPROVED** [review]
> @Piinks Hey, do you have any thoughts here, I saw you had a self-requested review of this.

Hey @xu-baolin thanks for another great contribution! 
I self-requested to make sure I did not miss this, but @chunhtai beat me to it. 😜 
This LGTM!

**Comment by idearibosome** [comment]
Thank you all for your great efforts!
