### PR TITLE
Remove duplicated key in _IconButtonM3

### LINKED ISSUE #105554: _IconButtonM3 reusing key
the new _IconButtonM3 is reusing the parent widget key. (line 500 of icon_button.dart)

```dart
      return _IconButtonM3(
        key: key,
        // ...
      );
```

which can make some tests fail, "expected 1 widget with key x but found 2" .

As explained in a similar issue where flutter duplicates keys, here: https://github.com/flutter/flutter/issues/103266 , I'm under the impression that flutter should not reuse keys. I could be wrong though as this seems to be something recurring. It's definitely unexpected though. 

This was caught by our test suite updating to latest master.

### PR DESCRIPTION
**Pull request by cedvdb**
This PR removes the key on _IconButtonM3 as it currently duplicates the parent key. As stated in that issue I'm under the impression that keys should not be reused, since this is not the first time I see this in the flutter repo maybe they are ? In any case, I just removed the duplication in the child widget.

Fixes #105554 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [n/a] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/icon_button_test.dart [hunk 1]
```diff
@@ -28,64 +28,80 @@ void main() {
     mockOnPressedFunction = MockOnPressedFunction();
   });
 
-  testWidgets('test default icon buttons are sized up to 48', (WidgetTester tester) async {
-    final bool material3 = theme.useMaterial3;
```
Comment (cedvdb) [inline packages/flutter/test/material/icon_button_test.dart:32]: I just added this test, but the git recognize every test below as modified.

**Review by darrenaustin — APPROVED** [review]
Thanks for the contribution. This looks reasonable to me. I don't think we are using the key on the internal _IconButtonM3, so I don't think this will cause in issues.

LGTM

**Review by QuncCccccc — APPROVED** [review]
LGTM. Thanks a lot for the fix!
