### PR TITLE
Fix selection handles showing when using a mouse

### LINKED ISSUE #168252: [Android] It's possible to show the touch selection handles when using a mouse
On native Android apps, when using a mouse, the selection handles don't show. However on Flutter, it's possible to get them to show up.

## Steps to reproduce:

  1. Get an Android device and connect a mouse to it.
  1. Run an app with a text field, such as the one below.
  1. Enter some text.
  1. Right click.
  1. Press "Select all"

## Expected results

All the text is highlighted and no selection handles are shown.

## Actual results

All the text is highlighted but selection handles appear.

Image

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            TextField(),
          ],
        ),
      ),
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Fixes #168252

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 1]
```diff
@@ -2727,6 +2740,10 @@ class TextSelectionGestureDetectorBuilder {
     // See https://github.com/flutter/flutter/issues/115130.
     renderEditable.handleSecondaryTapDown(TapDownDetails(globalPosition: details.globalPosition));
     _shouldShowSelectionToolbar = true;
+    _shouldShowSelectionHandles =
+        details.kind == null ||
+        details.kind == PointerDeviceKind.touch ||
+        details.kind == PointerDeviceKind.stylus;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:2746]: I double checked this on native Android and indeed the selection handles show when using a stylus. Good call.

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 2]
```diff
@@ -2164,12 +2164,23 @@ class TextSelectionGestureDetectorBuilder {
...
   bool get shouldShowSelectionToolbar => _shouldShowSelectionToolbar;
   bool _shouldShowSelectionToolbar = true;
 
+  /// Whether to show the selection handles.
+  ///
+  /// It is based on the signal source when [onTapDown], [onSecondaryTapDown],
+  /// [onDragSelectionStart], is called. This getter will return true if the
+  /// current [onTapDown], [onSecondaryTapDown], or [onDragSelectionStart] event
+  /// is triggered by a touch or a stylus.
+  bool get shouldShowSelectionHandles => _shouldShowSelectionHandles;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/text_selection.dart:2181]: I agree it's worth it to expose this :+1: .

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 3]
```diff
@@ -8642,6 +8642,118 @@ void main() {
...
+      TargetPlatform.fuchsia,
+      TargetPlatform.linux,
+      TargetPlatform.windows,
+    }),
+    // [intended] only applies to platforms where we supply the context menu.
+    skip: isContextMenuProvidedByPlatform,
+  );
+
+  testWidgets(
+    'Selection handles should not show when using a mouse on Apple platforms using Flutter context menu',
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:8707]: Is this test separate from the previous test because iOS uses the system context menu?

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 4]
```diff
@@ -8642,6 +8642,118 @@ void main() {
...
+
+      // Click at the end of blah1.
+      await tester.tapAt(firstBlah, kind: PointerDeviceKind.mouse);
+      await tester.pumpAndSettle();
+
+      // Right click the same position to reveal the context menu.
+      await tester.tapAt(firstBlah, kind: PointerDeviceKind.mouse, buttons: kSecondaryMouseButton);
+      await tester.pumpAndSettle();
+
+      switch (defaultTargetPlatform) {
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:8730]: Do you need this switch if `variant` says it's always iOS?

**Review by justinmc — APPROVED** [review]
LGTM :+1:. Thanks for fixing my issue so quick!

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 3 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/cupertino/text_field_test.dart:8707]: No its mostly separate because of cupertino vs material toolbar. I don't think we can test this specific scenario using the system rendered context menu on iOS since from my understanding they wouldn't show up in a widget test because `SystemContextMenu` only builds a `SizedBox.shrink()`. I did try to verify it myself on device and found the behavior is a bit buggy, I opened an issue here with more details and a possible solution (using custom buttons) https://github.com/flutter/flutter/issues/168857 .

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 4 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/cupertino/text_field_test.dart:8730]: good point!
