### PR TITLE
fix MenuItemButton if child is null 

### LINKED ISSUE #147479: MenuItemButton error if child is null
### Steps to reproduce

MenuItemButton(
      onPressed: () {},
      leadingIcon: Icon(Icons.any),
      child: null,
    );

Null check operator used on a null value

### Expected results

The child is nullable. If it is null, the MenuItemButton should be the same as IconButton.

### Actual results

Null check operator used on a null value

### Code sample

<details open><summary>Code sample</summary>

```dart
MenuItemButton(
      onPressed: () {},
      leadingIcon: Icon(Icons.any),
      child: null,
    );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
[✓] Android Studio (version 2022.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by zeqinjie**
Fix https://github.com/flutter/flutter/issues/147479

Pre-launch Checklist
- [x] I read the [Contributor Guide](https://github.com/flutter/flutter/wiki/Tree-hygiene#overview) and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene](https://github.com/flutter/flutter/wiki/Tree-hygiene) wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo), including [Features we expect every widget to implement](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement).
- [x] I signed the [CLA](https://cla.developers.google.com/).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with ///).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord](https://github.com/flutter/flutter/wiki/Chat).

### CODE REVIEW

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 1]
```diff
@@ -1141,7 +1141,7 @@ class _MenuItemButtonState extends State<MenuItemButton> {
         trailingIcon: widget.trailingIcon,
         hasSubmenu: false,
         overflowAxis: _anchor?._orientation ?? widget.overflowAxis,
-        child: widget.child!,
+        child: widget.child ?? const SizedBox(),
```
Comment (mahmoudsaleh1997) [inline packages/flutter/lib/src/material/menu_anchor.dart:1144]: Using **const SizedBox.shrink();** Would be better. 
See https://api.flutter.dev/flutter/widgets/Visibility-class.html

Comment (zeqinjie) [reply packages/flutter/lib/src/material/menu_anchor.dart]: @mahmoudsaleh1997 Agreed, thank you

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 2]
```diff
@@ -1141,7 +1141,7 @@ class _MenuItemButtonState extends State<MenuItemButton> {
         trailingIcon: widget.trailingIcon,
         hasSubmenu: false,
         overflowAxis: _anchor?._orientation ?? widget.overflowAxis,
-        child: widget.child!,
+        child: widget.child ?? const SizedBox.shrink(),
```
Comment (nate-thegrate) [inline packages/flutter/lib/src/material/menu_anchor.dart:1144]: Rather than just a one-line change here, would you be able to update [`_MenuItemLabel`](https://github.com/zeqinjie/flutter/blob/d895475c10af2201f938ac7a663e0425f2c18bba/packages/flutter/lib/src/material/menu_anchor.dart#L2972-L2985) so it has a nullable `child` property? Currently it's still documented as being required:

```dart
const _MenuItemLabel({
  required this.hasSubmenu,
  this.showDecoration = true,
  this.leadingIcon,
  this.trailingIcon,
  this.shortcut,
  this.semanticsLabel,
  this.overflowAxis = Axis.vertical,
  required this.child,
});

/// The required label child widget.
final Widget child;
```

File: packages/flutter/test/material/menu_anchor_test.dart [hunk 3]
```diff
@@ -2532,6 +2532,24 @@ void main() {
           ..rect(color: overlayColor.withOpacity(0.1)),
       );
     });
+
+    testWidgets('MenuItemButton is null check operator when it child is null', (WidgetTester tester) async {
```
Comment (nate-thegrate) [inline packages/flutter/test/material/menu_anchor_test.dart:2536]:
```suggestion
    testWidgets('MenuItemButton can build when its child is null', (WidgetTester tester) async {
```

The rest of this test looks fantastic!

**Review by nate-thegrate — COMMENTED** [review]
Thanks a bunch for the contribution! Looking forward to getting this bug fixed.

File: packages/flutter/lib/src/material/menu_anchor.dart (hunk 2 above)
Comment (zeqinjie) [reply packages/flutter/lib/src/material/menu_anchor.dart]: @nate-thegrate Thank you for your review，i have updated~

File: packages/flutter/test/material/menu_anchor_test.dart (hunk 3 above)
Comment (zeqinjie) [reply packages/flutter/test/material/menu_anchor_test.dart]: @nate-thegrate Thank you for your review，i got it~

**Review by nate-thegrate — APPROVED** [review]
LGTM 👍

Fantastic work here, thank you!

File: packages/flutter/test/material/menu_anchor_test.dart [hunk 4]
```diff
@@ -2532,6 +2532,22 @@ void main() {
...
+            body: SizedBox(
+              width: 200,
+              child: MenuItemButton(),
+            ),
+          ),
+        ),
+      );
+
+      // exception `Null check operator used on a null value` would be thrown.
+      expect(tester.takeException(), isNull);
```
Comment (gspencergoog) [inline packages/flutter/test/material/menu_anchor_test.dart:2549]: Maybe check the type of exception that is thrown?

```suggestion
      expect(tester.takeException(), isA(TypeError));
```

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

File: packages/flutter/test/material/menu_anchor_test.dart (hunk 4 above)
Comment (nate-thegrate) [reply packages/flutter/test/material/menu_anchor_test.dart:2549]: My understanding is that this test expects an empty `MenuItemButton()` constructor to build without errors.

<br>

Kinda similar to one of the date picker tests:

https://github.com/flutter/flutter/blob/5ecd4ea83d66e0aa8ffef205f4c2732f9a5818e7/packages/flutter/test/cupertino/date_picker_test.dart#L127-L137

Comment (gspencergoog) [reply packages/flutter/test/material/menu_anchor_test.dart:2549]: Oh, duh.  Sorry, misread that. Ignore my comment.
