### PR TITLE
Be more helpful when l10n generation fails

### LINKED ISSUE #82714: gen_l10n error message are often unhelpful
I had an extra comma in an `arb` file and when running `flutter run` the error message I got was just

```
Generating synthetic localizations package has failed.
```

I wish this message would be more helpful. My `arb` file was small so the error was easy to spot, but the error could be painful to spot in larger files.

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/82714.

### CODE REVIEW

File: packages/flutter_tools/lib/src/dart/generate_synthetic_packages.dart [hunk 1]
```diff
@@ -62,7 +63,14 @@ Future<void> generateLocalizationsSyntheticPackage({
...
   );
 
-  if (result == null || result.hasException) {
-    throwToolExit('Generating synthetic localizations package has failed.');
+  if (result == null) {
+    throwToolExit('Generating synthetic localizations package failed: result is null.');
+  }
+  if (result.hasException) {
+    throwToolExit(
+      'Generating synthetic localizations package failed with ${result.exceptions.length} ${pluralize('error', result.exceptions.length)}:'
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/dart/generate_synthetic_packages.dart:71]: I forgot about pluralize, I think I'm doing that myself in a few places...

**Review by jonahwilliams — APPROVED** [review]
LGTM
