### PR TITLE
Fix RadioButton is not vocalized as unselected by VoiceOver

### LINKED ISSUE #170422: RadioButton is not vocalized as unselected by VoiceOver.
### Steps to reproduce

Using iOS 18.5
 
1. Navigate to an unselected RadioButton 

### Expected results

1. Navigate to an unselected RadioButton
2. VoiceOver vocalizes the RadioButton state

Since Android (Talkback) does it, I would expect iOS to behave the same way — but maybe I'm wrong.

### Actual results

1. Navigate to an unselected RadioButton
2. VoiceOver does not announce the RadioButton state

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Text('Select an option:'),
              const SizedBox(height: 20),
              const MyRadioButtons(),
            ],
          ),
        ),
      ),
    );
  }
}

class MyRadioButtons extends StatefulWidget {
  const MyRadioButtons({super.key});

  @override
  State<MyRadioButtons> createState() => _MyRadioButtonsState();
}

class _MyRadioButtonsState extends State<MyRadioButtons> {
  String? _selectedValue;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        RadioListTile<String>(
          title: const Text('Option 1'),
          value: 'option1',
          groupValue: _selectedValue,
          onChanged: (String? value) {
            setState(() {
              _selectedValue = value;
            });
          },
        ),
        RadioListTile<String>(
          title: const Text('Option 2'),
          value: 'option2',
          groupValue: _selectedValue,
          onChanged: (String? value) {
            setState(() {
              _selectedValue = value;
            });
          },
        ),
        Text('Selected: ${_selectedValue ?? "None"}'),
      ],
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.5 24F74 darwin-arm64, locale fr-FR) [12,2s]
    • Flutter version 3.29.2 on channel stable at /Users/34080J/fvm/versions/3.29.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (3 months ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [4,7s]
    • Android SDK at /Users/34080J/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • ANDROID_HOME = /Users/34080J/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/openlogic-openjdk-17.jdk/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment OpenLogic-OpenJDK (build 17.0.14+7-adhoc.admin.jdk17u)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [1 876ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [27ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [27ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12932927-b750.29)

[✓] IntelliJ IDEA Ultimate Edition (version 2025.1) [26ms]
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.98.2) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.108.0

[✓] Connected device (5 available) [6,1s]
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 15 (API 35) (emulator)
    • iPhone d’Alexandre (mobile)     • 00008140-001539621E51801C • ios            • iOS 18.5 22F76
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 137.0.7151.69

[✓] Network resources [243ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by huycozy**
### Issue
- Fix https://github.com/flutter/flutter/issues/170422

### Description

This PR proposes a fix by adding a hint to Semantics here:

https://github.com/flutter/flutter/blob/b220f5a2abf53c28623514b223b20a46c69a8ca6/packages/flutter/lib/src/widgets/raw_radio.dart#L217-L222

The hint is only available on iOS &macOS platforms with a localized string for `unselected` state to prevent regression on Android, which works as expected currently and this seems to be the only solution as investigated below ⬇️

<details open>
<summary>Demo the fix</summary>

https://github.com/user-attachments/assets/56c1c6c9-5178-45be-a633-47145a0543d6

</details>

#### Why can't we make it simpler with Semantics flags only?

- I looked at [UIAccessibilityTraits](https://developer.apple.com/documentation/uikit/uiaccessibilitytraits), it seems the [selected](https://developer.apple.com/documentation/uikit/uiaccessibilitytraits/selected) property does announce `selected` state, but it does not mention or give hints for `unselected` state. 
- [L824-L828](https://github.com/flutter/flutter/blob/e8bef98051944f0faee9913f76d22f2d0cc91712/engine/src/flutter/shell/platform/darwin/ios/framework/Source/SemanticsObject.mm#L824-L828) in Flutter source code does mention radio button: Looks like I can try marking both toggle and check, but it's impossible, due to an assertion: [A semantics node cannot be toggled and checked at the same time](https://github.com/flutter/flutter/blob/35375e43fbae661f41dd8a6bda7454f8d55a4d54/packages/flutter/lib/src/rendering/object.dart#L4807-L4809)

➡️ Not sure which flags can trigger `unselected` state implicitly.

#### How do iOS native apps work?

I did test with two approaches:

1. iOS Reminders app: 
VoiceOver vocalizes as follows:
Unchecked radio: "...Incomplete..."
checked radio:"...Completed..."

<details>
<summary>Demo video</summary>

https://github.com/user-attachments/assets/6bed5d14-ded8-47c2-9c09-7afc266898cc

</details>

2. Build Radio with SwiftUI

Looks like [there is no built-in widget for Radio provided by Apple](https://www.reddit.com/r/SwiftUI/comments/1gsh7zo/does_swiftui_have_a_builtin_radiobutton_in_2024/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button). [Is it really a native iOS component?](https://www.reddit.com/r/SwiftUI/comments/1gsh7zo/comment/lxea1uf/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

Most of results I have found suggest building radio from a button with changing image source(selected/unselected, respectively), as I do in this SwiftUI code here: https://gist.github.com/huycozy/93b12c030651c4fde6fe8fceda1ba1ee. We can control what the reader vocalizes by setting traits and value for it manually. This being said, setting accessibility hint or value from Flutter side makes sense in this case. Please let me know if I am missing something.

<details>
<summary>Demo video</summary>

https://github.com/user-attachments/assets/118c89c5-46a3-497f-8b2a-6f7c5ae8edf3

</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/radio_test.dart [hunk 1]
```diff
@@ -2723,4 +2723,101 @@ void main() {
...
+            isEnabled: true,
+            hasTapAction: true,
+            isFocusable: true,
+            isInMutuallyExclusiveGroup: true,
+            hasSelectedState: true,
+            hint: localizations.radioButtonUnselectedLabel, // Unselected radio gets non-empty hint.
+          ),
+        );
+      },
+      variant: TargetPlatformVariant.only(TargetPlatform.iOS),
```
Comment (chunhtai) [inline packages/flutter/test/material/radio_test.dart]: you can write the test in a way that works for all platform for example

```dart
if (defaultTargetedPlatform == ...) {
   expect(hint, "hint");
} else {
   expect(hint, isNull);
}
```

**Review by chunhtai — COMMENTED** [review]
LGTM except one minor comment, @QuncCccccc do you know if we need to do anything to trigger translation once this pr landed?

**Comment by QuncCccccc** [comment]
> do you know if we need to do anything to trigger translation once this pr landed?

Once it's rolling into g3, the translation team will translate the new text. And when the translation is finished, we will need to back-integrate the translation to Flutter. So for now, there's nothing we need to do.

**Comment by chunhtai** [comment]
> > do you know if we need to do anything to trigger translation once this pr landed?
> 
> Once it's rolling into g3, the translation team will translate the new text. And when the translation is finished, we will need to back-integrate the translation to Flutter. So for now, there's nothing we need to do.

Do we get a notification somehow? because I saw some of the old strings are not translated yet

**Comment by QuncCccccc** [comment]
> Do we get a notification somehow? because I saw some of the old strings are not translated yet

We don't get notification I think. Which old strings do you see? We can use go/flutter-l10n to check the status. Seems most of the languages have the 100% translation.

**Comment by chunhtai** [comment]
noResultsFound and searchResultsFound was added recently, but hasn't been translated yet

File: packages/flutter/test/material/radio_test.dart (hunk 1 above)
Comment (huycozy) [reply packages/flutter/test/material/radio_test.dart]: Thanks for the suggestion. I simplified all additional tests to be simpler by removing unnecessary semantic checks/tests and using `defaultTargetedPlatform` to categorize platforms.

**Review by chunhtai — APPROVED** [review]
LGTM
