### PR TITLE
Redo#2: Add buttons to gestures

### LINKED ISSUE #31884: Desktop embedding mouse clicks do not register
Broken by https://github.com/flutter/flutter/pull/31819.

cc @dkwingsmt, lets sit down tomorrow and get the desktop targets setup locally so we can figure out if this is something that needs to change in the embedder, the framework, or both

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

This PR is a reland of #31819.

Changes:
- None yet.

### Explanation
The previous attempt #31819 broke desktop embedders (see more discussion at https://github.com/flutter/flutter/issues/31884). It's likely because the embedder API does not send buttons at all, which is a requirement by gesture recognizers after this PR.

## Related Issues

- Previous attempt: #31819
- Fixes: #31884

## Tests

I added the following tests:

- None

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by dkwingsmt** [comment]
+cc @stuartmorgan @jonahwilliams 
(It's a placeholder PR; no changes have been added yet)

**Comment by stuartmorgan** [comment]
I would suggest doing a separate PR that adds button data to the pointer data created in embedder.cc, landing that, and then re-landing your CL. Sending the button data shouldn't depend on your PR, so that lets you do a simple, easy-to-review PR for that aspect, rather than it being part of an already-large PR.

**Comment by dkwingsmt** [comment]
@jonahwilliams I've tested this PR on desktop and confirmed that the button responds to LMB click, and no longer to RMB click. The environment is as follow:
- gLinux
- Engine: 6e3c0431410ce3ae1e1ee7cf8c139fefd34a6cde
- Embedder: google/flutter-desktop-embedding#355 , linux example

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by wreppun** [comment]
@dkwingsmt , I created a ticket with some detail at #36118 , but I traced the broken scroll on the chromebook touchpad back to this PR.

File: packages/flutter/lib/src/gestures/tap.dart [hunk 1]
```diff
@@ -267,5 +392,6 @@ class TapGestureRecognizer extends PrimaryPointerGestureRecognizer {
     properties.add(FlagProperty('wonArenaForPrimaryPointer', value: _wonArenaForPrimaryPointer, ifTrue: 'won arena'));
     properties.add(DiagnosticsProperty<Offset>('finalPosition', _finalPosition, defaultValue: null));
     properties.add(FlagProperty('sentTapDown', value: _sentTapDown, ifTrue: 'sent tap down'));
+    // TODO(tongmu): Add property _initialButtons and update related tests
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/tap.dart]: is there any reason we couldn't do this as part of this PR when it landed?

Comment (dkwingsmt) [reply packages/flutter/lib/src/gestures/tap.dart]: It was because that this PR was already big and at its 2nd redo, so I didn’t want to introduce unnecessary changes that  affected a lot of files at that time. I’ll fix this.
