### PR TITLE
Fix abi key for local golden file testing

### LINKED ISSUE #148022: Local golden file testing is not using abi key
Due to https://g-issues.skia.org/issues/339508268

We are disabling the key to workaround this temporarily. The correct images are pulled without it, so testing works.
The abi key was added in https://github.com/flutter/flutter/pull/143621

Once the issue is resolved, we should re-enable it.
Disabling in https://github.com/flutter/flutter/pull/148023

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/148022

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter_goldens/lib/skia_client.dart [hunk 1]
```diff
@@ -582,19 +582,22 @@ class SkiaGoldClient {
   /// the image keys.
   String getTraceID(String testName) {
     final String? webRenderer = _webRendererValue;
+    // Keys must be sorted alphabetically, after grouping by letter case.
```
Comment (goderbauer) [inline packages/flutter_goldens/lib/skia_client.dart:585]: Is this also relevant for `_getKeysJSON`?

**Review by goderbauer — APPROVED** [review]
LGTM

Thank you for digging into this!

File: packages/flutter_goldens/lib/skia_client.dart [hunk 2]
```diff
@@ -582,19 +582,22 @@ class SkiaGoldClient {
...
-      'name' : testName,
-      'source_type' : 'flutter',
+
+      // Lower case keys
       if (_isImpeller)
         'impeller': 'swiftshader',
+      'name' : testName,
+      'source_type' : 'flutter',
     };
     final String jsonTrace = json.encode(keys);
```
Comment (goderbauer) [inline packages/flutter_goldens/lib/skia_client.dart:602]: Could we add an assert here (or a test elsewhere) that enforces the sorting rules and breaks if this is messed up in the future?

File: packages/flutter_goldens/lib/skia_client.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter_goldens/lib/skia_client.dart:585]: It is not, since those keys are sorted by Gold when they are ingested. It matters here because we are using the keys to generate an md5 sum to look up the image, and being out of order means we get the wrong result.

File: packages/flutter_goldens/lib/skia_client.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter_goldens/lib/skia_client.dart:602]: I can, it would be pretty complicated though (and probably not today) to account for all the cases where we do or don't include a given key. We don't add keys very often, I was kind of hoping the comment would suffice. WDYT?

Comment (kjlubick) [reply packages/flutter_goldens/lib/skia_client.dart:602]: It does seem a touch fragile. Would it be worth adding some code that somehow alphabetizes the map keys first? If so, then I would imagine it would be easier to add a few tests for that logic: input(map) output(md5 hash).

Comment (goderbauer) [reply packages/flutter_goldens/lib/skia_client.dart:602]: Isn't this just:

```dart
  assert(() {
    List sorted = keys.keys.toList()..sort();
    return listEquals(sorted, keys.keys.toList());
  }());
```

Although, maybe doing this on every golden check is kinda slowing things down? I'd be okay with leaving this out as well.

Comment (As90909w) [reply packages/flutter_goldens/lib/skia_client.dart:602]: The key part is removablee

Comment (As90909w) [reply packages/flutter_goldens/lib/skia_client.dart:602]: > Isn't this just:
> 
> ```dart
>   assert(() {
>     List sorted = keys.keys.toList()..sort();
>     return listEquals(sorted, keys.keys.toList());
>   }());
> ```
> 
> Although, maybe doing this on every golden check is kinda slowing things down? I'd be okay with leaving this out as well.

So assert is like......pulling

Comment (goderbauer) [reply packages/flutter_goldens/lib/skia_client.dart:602]: Another option would be to just throw these key-values into a self-ordering data structor, e.g. https://main-api.flutter.dev/flutter/dart-collection/SplayTreeMap-class.html

Comment (Piinks) [reply packages/flutter_goldens/lib/skia_client.dart:602]: Oh! Will dart sort by case before alphabetical order? I didn't think it would.. let me check

File: packages/flutter_goldens/lib/skia_client.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter_goldens/lib/skia_client.dart:585]: "alphabetically, after grouping by letter case" is just "sort by Unicode scalar value" which is just the default string sort in Dart, so one way to do this would be to create the map first, then get the keys, sort them, and add the key/value pairs to a new map in the sorted order. That would avoid future bugs when someone adds a new key manually and gets the order wrong. It would cost a few CPU cycles and some memory though.

Comment (Hixie) [reply packages/flutter_goldens/lib/skia_client.dart:585]: ah, just saw the comment below. Yeah, the order here is just the default order for Dart sorting.

```dart
void main() {
  Map<String, int> test = {'a': 3, 'B': 2, 'A': 1, 'b': 4};
  print(test);
  print(test.keys.toList()..sort());
  Map<String, int> sorted = {};
  for (String key in test.keys.toList()..sort()) {
    sorted[key] = test[key]!;
  }
  print(sorted);
}
```

->

```
{a: 3, B: 2, A: 1, b: 4}
[A, B, a, b]
{A: 1, B: 2, a: 3, b: 4}
```

Comment (Piinks) [reply packages/flutter_goldens/lib/skia_client.dart:585]: This week I learned Dart does that by default! Awesome! Yeah I'll update this to sort keys so we don't have to worry about it recurring. :)

**Review by goderbauer — APPROVED** [review]
LGTM
