### PR TITLE
Reland "SliverEnsureSemantics (#165589)"

### LINKED ISSUE #160217: Screen readers cannot list or move focus to elements outside of the current viewport
### Steps to reproduce

<p>NVDA, JAWS, and VoiceOver Screen readers cannot list or move focus to elements outside of the current viewport. Any elements that have scrolled out of view or haven't yet been scrolled into view will NOT be reachable via screen reader basic keyboard commands for reading and navigating web content.</p>
<p>Examples:</p>
<div class="table-wrap">

Function | JAWS Shortcut | NVDA Shortcut | VoiceOver Shortcut
-- | -- | -- | --
Next Heading | H, 1-6 for heading level | H, 1-6 for heading level | Control Option Command H
List Headings | Insert F6 | Insert F7 to open Elements list, Select the "Headings" radio button | Control Option U, Press left/right arrow keys until the "Heading" menu is displayed
Next Link | U for unvisited link, V for visited link | K for link, U for unvisited, link V for visited link | Control Option Command L for link, Control Option Command V for visited link
List Links | Insert F7 | Insert F7 to open Elements list, Select the "Links" radio button | Control Option U, Press left/right arrow keys until the "Links" menu is displayed
Next Button | B | B | N/A
List Buttons | Control Insert B | Insert F7 to open Elements list, Select the "Buttons" radio button | Control Option U, Press left/right arrow keys until the "Form Controls" menu is displayed
Next Form Control | F | F | Control Option Command J
Next Table | T | T | Control Option Command T
Next Landmark | R | D | N/A
Next List | L | L | Control Option Command X

</div>

### Expected results

- The "Next" keyboard shortcuts should move the screen reader focus to the next element of that type which exists on the page, not just the elements displayed in the current viewport
- The lists should contain all elements of that type which exist on the page, not just the elements displayed in the current viewport

### Actual results

- The "Next" keyboard shortcuts only move the screen reader focus to the next element of that type which is displayed in the current viewport
- The lists only contain elements of that type which are displayed in the current viewport

### Code sample

N/A

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

`Flutter (Channel beta, 3.27.0-0.1.pre, on macOS 14.5 23F79 darwin-arm64, locale en-US)`

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This reverts commit 2fc716d, and updates the cross-axis size of the `_scrollOverflowElement` to be 1px (non-zero), so it is taken into account by the scrollable elements scrollHeight.

Fixes #160217

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart [hunk 1]
```diff
@@ -183,64 +178,47 @@ class SemanticScrollable extends SemanticRole {
...
+    assert(scrollExtentMin != null);
+    final double scrollExtentTotal =
+        scrollExtentMax! -
+        scrollExtentMin! +
+        (semanticsObject.isVerticalScrollContainer ? rect.height : rect.width);
+    // Place the _scrollOverflowElement at the beginning of the content
+    // and size it based on the total scroll extent so the browser
+    // knows how much scrollable content there is. The cross axis size
+    // should be non-zero so it is taken into account in the scrollable
+    // elements scrollHeight.
```
Comment (yjbanov) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:200]: nit: I'd place this comment immediately above the line that sets 1px. Otherwise, it's hard to make the connection between "non-zero cross axis" and `width = '1px'`/`height = '1px'`.

**Review by yjbanov — APPROVED** [review]
