### PR TITLE
Only run xcodebuild -showBuildSettings once

### LINKED ISSUE #80826: Backout the timeout/retry of showBuildSettings in the xcode build
The tool currently times out and retries the call to `showBuildSettings` in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/mac.dart#L360

We should not retry, and instead show a message when the command has been running long than say 30 seconds or so. The tool should also catch any errors thrown and tool exit instead of crashing.

Its possible this is caused by earlier xcode commands sometimes holding onto resources longer than their process, so it might be worth exploring how to run fewer of these commands or how to ensure they will work correctly when invoked.

### PR DESCRIPTION
**Pull request by jmagman**
Redux of https://github.com/flutter/flutter/pull/72175

## Description

`flutter build ios` was calling `xcodebuild -showBuildSettings` multiple times, which can take several seconds to run.  It was running once with the right flavor/scheme, but always for a real device (not simulator) and for the default configuration (usually `Release`).  That meant it needed to be called a second time with the actual right configuration and SDK (if the simulator was targeted).

This change caches the build settings already fetched for a given scheme, configuration, and SDK type (real device or simulator) as wrapped by the new `XcodeProjectBuildContext` class.  The first time `-showBuildSettings` is called, actually  pass in the right configuration and SDK, and then use the cached build settings on subsequent fetches.

## Related Issues

https://github.com/flutter/flutter/issues/9199
https://github.com/flutter/flutter/issues/70576#issuecomment-736196704
Fixes https://github.com/flutter/flutter/issues/80826 (the other -`showBuildSettings` timeout/retry is tracked at https://github.com/flutter/flutter/issues/42265 and is not removed with this PR)

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 1]
```diff
@@ -176,9 +176,15 @@ Future<XcodeBuildResult> buildXcodeProject({
   }
 
   Map<String, String> autoSigningConfigs;
+
+  final Map<String, String> buildSettings = await app.project.buildSettingsForBuildInfo(
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/ios/mac.dart:180]: can this be defined after line 185, so we don't need to await this if we never hit the if block?

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/mac.dart:180]: Before, `buildSettings` was set in the `showBuildSettingsCommand` code I deleted.  Now it's calculated earlier but still used on line 380.

**Review by christopherfujino — APPROVED** [review]
LGTM
