### PR TITLE
Fix Scaffold bottomSheet null exceptions

### LINKED ISSUE #117004: Null error on Scaffold's bottomSheet
There have been reports of the following error at the following line:

`_CastError: Null check operator used on a null value`

https://github.com/flutter/flutter/blob/15af81782e19ebe7273872f8b07ac71df4e749f2/packages/flutter/lib/src/material/scaffold.dart#L2233

I'm unable to reproduce this in a "natural" way.  I can only reproduce it by forcing the StatefulBuilder in the bottomSheet to rebuild after `widget.bottomSheet` is null while it's animating out.

### References
Google bug b/220078969

### PR DESCRIPTION
**Pull request by justinmc**
Prevents the possibility of null exceptions on `widget.bottomSheet!`.

I was unable to reproduce this "in the wild", but the test does reproduce it by directly calling `setState` on the StatefulBuilder while the bottom sheet is animating out.  Note the use of `ignore: invalid_use_of_protected_member`.

@Piinks Do you have any other ideas about how to reproduce/test this?  I think if I could get that DraggableScrollableActuator to rebuild while its animating out then it would cause the error too.  I tried many different variations of building a DraggableScrollableSheet in my `bottomSheet` and trying to scroll/resize it during the close animation, but couldn't get it to rebuild.

If there is not a better way to test it, are we ok with the `ignore` to be able to call setState?

Closes https://github.com/flutter/flutter/issues/117004

### CODE REVIEW

File: packages/flutter/lib/src/material/scaffold.dart [hunk 1]
```diff
@@ -2223,14 +2223,15 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
...
+      final Widget bottomSheet = widget.bottomSheet!;
       _currentBottomSheet = _buildBottomSheet<void>(
         (BuildContext context) {
           return NotificationListener<DraggableScrollableNotification>(
             onNotification: persistentBottomSheetExtentChanged,
             child: DraggableScrollableActuator(
               child: StatefulBuilder(
                 key: _currentBottomSheetKey,
-                builder: (BuildContext context, StateSetter setState) => widget.bottomSheet!,
+                builder: (BuildContext context, StateSetter setState) => bottomSheet,
```
Comment (justinmc) [inline packages/flutter/lib/src/material/scaffold.dart:2234]: Another option would be to build SizedBox.shrink() here when bottomSheet is null.  However, since this seems to happen when the bottomSheet is animating out, we probably do want to use the old bottomSheet during that time and not suddenly make it disappear.

**Review by Piinks — COMMENTED** [review]
It looks like there are some test failures here. 
To be honest, I am not very familiar here. @xu-baolin may have an idea as to what could cause this issue. The first thing I thought is maybe the customer is removing the sheet from the Scaffold when it is dismissed? Or disposing of it before the animation completes?

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/lib/src/material/scaffold.dart:2234]: Do we know it is happening when animating out?

**Comment by xu-baolin** [comment]
> It looks like there are some test failures here. 
> 
> To be honest, I am not very familiar here. @xu-baolin may have an idea as to what could cause this issue. The first thing I thought is maybe the customer is removing the sheet from the Scaffold when it is dismissed? Or disposing of it before the animation completes?

I just got a positive test. Let's take a look when I defeat the virus.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/scaffold.dart]: In the wild, no, we seem to know nothing about when it's happening.  In my test I was able to cause it to happen while animating out, though.

I have switched over to using SizedBox.shrink despite my previous comment.  The reason is that it needs to get the latest widget.bottomSheet when the widget is rebuilt with a new parameter, otherwise it will still display the old one.

**Comment by justinmc** [comment]
@xu-baolin Get well soon!  Definitely rest up and don't worry about this until you're healthy 💪

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/scaffold.dart]: @justinmc Hi, I think I have reproduced this in the wild, press the '+' button will trigger the exception.
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MyHomePage(title: 'Flutter Demo Home Page');
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return MaterialApp(
      theme: _counter % 2 == 0 ? ThemeData.dark() : ThemeData.light(),
      home: Scaffold(
        appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text(widget.title),
        ),
        bottomSheet: _counter % 2 == 0
            ? Container(
                width: double.infinity,
                height: 100,
                color: Colors.blue,
                child: const Text('BottomSheet'),
              )
            : null,
        body: Center(
          // Center is a layout widget. It takes a single child and positions it
          // in the middle of the parent.
          child: Column(
            // Column is also a layout widget. It takes a list of children and
            // arranges them vertically. By default, it sizes itself to fit its
            // children horizontally, and tries to be as tall as its parent.
            //
            // Invoke "debug painting" (press "p" in the console, choose the
            // "Toggle Debug Paint" action from the Flutter Inspector in Android
            // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
            // to see the wireframe for each widget.
            //
            // Column has various properties to control how it sizes itself and
            // how it positions its children. Here we use mainAxisAlignment to
            // center the children vertically; the main axis here is the vertical
            // axis because Columns are vertical (the cross axis would be
            // horizontal).
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text(
                'You have pushed the button this many times:',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headlineMedium,
              ),
            ],
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: _incrementCounter,
          tooltip: 'Increment',
          child: const Icon(Icons.add),
        ), // This trailing comma makes auto-formatting nicer for build methods.
      ),
    );
  }
}

```

Comment (justinmc) [reply packages/flutter/lib/src/material/scaffold.dart]: @xu-baolin Glad you're back!  I think you nailed it here :+1:.  I was able to write a test that reproduced the bug based on this example.  Thank you!

See https://github.com/flutter/flutter/pull/117008/commits/35a6f8d70fb77096db4b67cce0d25253f8f6b513

Comment (Piinks) [reply packages/flutter/lib/src/material/scaffold.dart]: Amazing @xu-baolin! Thank you! I hope you are feeling better! 🤗

File: packages/flutter/lib/src/material/scaffold.dart [hunk 2]
```diff
@@ -2230,7 +2230,9 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin, Resto
             child: DraggableScrollableActuator(
               child: StatefulBuilder(
                 key: _currentBottomSheetKey,
-                builder: (BuildContext context, StateSetter setState) => widget.bottomSheet!,
+                builder: (BuildContext context, StateSetter setState) {
```
Comment (Piinks) [inline packages/flutter/lib/src/material/scaffold.dart:2233]: Just curious, if the bottom sheet has been abruptly removed and is null at this point, should we also do anything to make the bottom sheet state closed? Should _currentBottomSheet be null? Or should the animation controller value be set to closed? 

I am not sure what the expected behavior is based on no customer test, so I am fine with landing this as is and touching base with the customer to see if this resolves their issues before making more changes. WDYT?

File: packages/flutter/lib/src/material/scaffold.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/scaffold.dart]: Almost recovered, thank you, guys!

File: packages/flutter/lib/src/material/scaffold.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/scaffold.dart:2233]: Ok I think you're right about that.  I've gone back to the previous solution.

The GlobalKey error is reproducible even on master right now because of the exit animation.  But we should probably wait for feedback before we make further changes as you say.

<details>

<summary>Code to repro GlobalKey error</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MyHomePage(title: 'Flutter Demo Home Page');
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  final GlobalKey bottomSheetKey = GlobalKey();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    final Widget bottomSheet = Container(
      key: bottomSheetKey,
      width: double.infinity,
      height: 100,
      color: Colors.blue,
      child: const Text('BottomSheet'),
    );

    return MaterialApp(
      theme: _counter % 2 == 0 ? ThemeData.dark() : ThemeData.light(),
      home: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        bottomSheet: _counter % 2 == 0 ? bottomSheet : null,
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text(
                'You have pushed the button this many times:',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headlineMedium,
              ),
              if (_counter % 2 != 0) 
                bottomSheet,
            ],
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: _incrementCounter,
          tooltip: 'Increment',
          child: const Icon(Icons.add),
        ),
      ),
    );
  }
}
```

</details>

**Review by xu-baolin — APPROVED** [review]
LGTM

**Review by Piinks — APPROVED** [review]
LGTM
