### PR TITLE
Newly constructed tweens should have same begin and end

### LINKED ISSUE #84258: CircleAvatar widget throws Exception if the foregroundImage property changed
**Exception has occurred.
"Error: Expected a value of type 'Decoration', but got one of type 'Null'**

I believe the bug is somewhere in  `AnimatedContainer class` and `AnimationController class`

## Steps to Reproduce
1. Run `flutter create bug`.
2. Update the `main.dart` as follows: 
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(body: BugWidget()),
    ),
  );
}

class BugWidget extends StatefulWidget {
  @override
  _BugWidgetState createState() => _BugWidgetState();
}

class _BugWidgetState extends State<BugWidget> {
  final photoURL = "https://gravatar.com/avatar/11ef7c4b9749807b121e74cd353be3eb";
  var radius = 20.0;
  var toggleForegroundImage = false;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        CircleAvatar(
          radius: radius,
          foregroundImage:
              toggleForegroundImage ? NetworkImage(photoURL) : null,
        ),
        TextButton(
          onPressed: () {
            setState(() {
              radius = radius == 20 ? 40 : 20;
            });
          },
          child: Text('toggle Radius'),
        ),
        TextButton(
          onPressed: () {
            setState(() {
              toggleForegroundImage = !toggleForegroundImage;
            });
          },
          child: Text('toggle ForegroundImage'),
        ),
      ],
    );
  }
}
```
3. Run the app and click 2 buttons
- Click button `toggle Radius`
- Then click button `toggle ForegroundImage`

**Expected results:** 
it should show the `foregroundImage` which is my avatar image

**Actual results:** 
```
Exception has occurred.
"Error: Expected a value of type 'Decoration', but got one of type 'Null'
```
<details>
```
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (13 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```

### PR DESCRIPTION
**Pull request by werainkhatri**
FIxes a bug where when a tween is constructed (was null before), after the implicit animated widget has animated at least once, the newly constructed tween has `end = null`. The widget is not animated, as the tween has just been constructed  ([`shouldAnimate = targetValue != (tween.end ?? tween.begin)`](https://github.com/flutter/flutter/blob/c701126481dcbe62eb06b558f5b1951ae8e8e89c/packages/flutter/lib/src/widgets/implicit_animations.dart#L414)) and hence not updated. But the `animation.value` is 1.0 (as it has been animated once before). So, when this tween is evaluated against `animation.value`, it throws an error.

The fix is to set the `tween.end` of every newly constructed tween to `tween.begin`.

fixes #84258

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by werainkhatri** [comment]
Failing checks will be fixed once #94601 is merged.

File: packages/flutter/lib/src/widgets/implicit_animations.dart [hunk 1]
```diff
@@ -430,6 +430,8 @@ abstract class ImplicitlyAnimatedWidgetState<T extends ImplicitlyAnimatedWidget>
         tween ??= constructor(targetValue);
         if (_shouldAnimateTween(tween, targetValue))
           shouldStartAnimation = true;
+        else
+          tween.end ??= tween.begin;
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/implicit_animations.dart:434]: I don't think this is correct. For some tweens (e.g. ColorTween) null has a special meaning. And as documented in https://master-api.flutter.dev/flutter/animation/Tween-class.html under "Nullability" that's totally ok.

Comment (werainkhatri) [reply packages/flutter/lib/src/widgets/implicit_animations.dart:434]: I understand that.

1. I haven't removed the ability for the value to be `null`. I'm just making sure that when the tween should not animate, begin and end should be the same, as there is no animation. This adds to a state of being unanimated.
2. In the current implementation of `ImplicitlyAnimatedWidget`, it is not possible to animate from non-null color to null anyway, as when the color (aka `targetValue`) becomes null, the tween is set to null, ignoring it. As a matter of fact, this is something that needs to be fixed too.
3. Lastly, `ImplicitlyAnimatedWidget` should be agnostic of what should happen when `targetValue` becomes null. Current extensions of `ImplicitlyAnimatedWidget` are trying to expect different things from it. Example: `AnimatedContainer` has a nullable `alignment` argument which is supposed to be ignored when it is null, which makes its tween null. Whereas `AnimatedColor` (fictional widget working over `ColorTween`) has a special meaning when its `color` is null, meaning its tween should remain non-null and have `end` set to null.

Possible solution:
1. The `tween`s' nullability should be handled by `ImplicitlyAnimatedWidget`'s extension instead of itself.
2. The check for whether a tween should animate or not, should depend only on its current `end`, even it it's null.
    ```dart
    bool _shouldAnimateTween(Tween<dynamic> tween, dynamic targetValue) {
        return targetValue != tween.end;
      }
    ```
3. From the perspective of `ImplicitlyAnimatedWidget`, `targetValue` being null should be considered as one of the valid tween states instead of using it to null the tween.

**Comment by goderbauer** [comment]
@werainkhatri This is still blocked on https://github.com/flutter/flutter/pull/94601 getting fixed first?

**Comment by werainkhatri** [comment]
@goderbauer no, this is separate now. i have listed my findings in the conversation above. do lemme know what you think.

**Comment by goderbauer** [comment]
OK. Can you rebase this to the latest master and make sure that all checks pass? Thanks!

**Comment by werainkhatri** [comment]
The failing checks aren't flakes, they are inconsistency with my logic of how `ImplicitAnimation` should be used v/s how it is currently used. Will provide a better analysis with design doc asap. Sorry for the delay. Thanks!

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by werainkhatri** [comment]
Looks like this was blocked due to #94601

@goderbauer do you mind taking a look at the `Google Testing` check?

**Comment by werainkhatri** [comment]
Fails again :(

**Comment by goderbauer** [comment]
I triggered it again. Hopefully it will pass. There were some technical problems with the check last week.

**Comment by werainkhatri** [comment]
Still failing...
