### PR TITLE
Replace IndexedStack visibility children with _VisibilityScope + ExcludeFocus

### LINKED ISSUE #127553: `IndexedStack` no longer supports `Positioned`
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

-

### Expected results

-

### Actual results

-

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('IndexedStack + Positioned', (tester) async {
    await tester.pumpWidget(MaterialApp(
      home: Scaffold(
        body: IndexedStack(
          children: [
            Positioned(
              child: Container(),
            )
          ],
        ),
      ),
    ));
  });
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by victorsanni**
`IndexedStack` wraps every child with `Visibility.maintain`, which has this widget tree:

`Visibility →  _VisibilityScope → _Visibility → IgnorePointer → ExcludeFocus → child`

`_Visibility` and `IgnorePointer` are `RenderObjectWidget`s, so they insert `RenderObject`s between `RenderIndexedStack` and the child, breaking the `ParentDataWidget` chain — so if a `Positioned` is a direct child of `IndexedStack`, its `StackParentData` never reaches the `RenderIndexedStack` and the widget crashes.

This PR wraps the child instead with only `_VisibilityScope` and `ExcludeFocus`, which do not insert `RenderObject`s. This works because the `_Visibility`/`IgnorePointer` wrappers were redundant anyway as `RenderIndexedStack` already skips painting, hit-testing, and semantics for non-selected children.

However, `_VisibilityScope` is private to `visibility.dart`, and so we either have to:

1. Expose it as a new public API,
2. Mark it as `@internal` and don't export it from `widgets.dart`, or
3. Move `IndexedStack`'s implementation to `visibility.dart`

I chose the 2nd option since it preserves existing behavior without impairing API findability.

**EDIT**: @Renzo-Olivares pointed out that the style guide warns against semi-private APIs:

> Flutter packages should not have "private" APIs other than those that are prefixed with underscores.
>
> When developing new features in Flutter packages, one should follow the philosophy: Only expose the APIs that are necessities to the features.
> 
> Since the private classes in dart language are file-bound, this may often result in large file sizes. In Flutter, this is considered to be more preferable than creating multiple smaller files but exposing intermediate classes that are not needed to use the features.

so option 3 seems like the best solution. API findability might be impaired, but there are ways to mitigate this (.e.g rename `visibility.dart` to `indexed_stack.dart` since `IndexedStack` is a downstream consumer of `visibility.dart`)

Fixes [IndexedStack no longer supports Positioned](https://github.com/flutter/flutter/issues/127553)

### CODE REVIEW

File: packages/flutter/lib/src/widgets/basic.dart [hunk 1]
```diff
@@ -4883,14 +4884,23 @@ class IndexedStack extends StatelessWidget {
 
   @override
   Widget build(BuildContext context) {
+    // Each child is wrapped with [VisibilityScope] (so [Visibility.of] reports
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/basic.dart]: Could we move this above build() and use `///` ? Then the doc links for the symbols will work?

**Review by navaronbracke — DISMISSED** [review]
LGTM with nit about the doc comment

File: packages/flutter/lib/src/widgets/visibility.dart [hunk 2]
```diff
@@ -10,6 +10,7 @@
 library;
 
 import 'package:flutter/rendering.dart';
+import 'package:meta/meta.dart' show internal;
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/visibility.dart]: Linux analyze is flagging this bad import.

```suggestion
import 'package:flutter/foundation.dart' show internal;
```

File: packages/flutter/lib/src/widgets/basic.dart (hunk 1 above)
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/basic.dart]: I don't know that we want to make this a public API, seems like an implementation detail. Maybe I can remove the `[]`s so it is less confusing.

Comment (navaronbracke) [reply packages/flutter/lib/src/widgets/basic.dart]: Yeah, having the [] here is probably what makes it odd. What if you replace these by backticks?

**Review by navaronbracke — DISMISSED** [review]

File: packages/flutter/lib/src/widgets/visibility.dart [hunk 3]
```diff
@@ -312,13 +313,19 @@ class Visibility extends StatelessWidget {
 }
 
 /// Inherited widget that allows descendants to find their visibility status.
-class _VisibilityScope extends InheritedWidget {
-  const _VisibilityScope({required this.isVisible, required super.child});
-
+///
+/// Used internally by [Visibility] and [IndexedStack] to propagate visibility
+/// information to descendants.
+@internal
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/visibility.dart]: I don't think we've ever used this annotation before outside of feature flags (multiwindow), right? We should be sure we want to set this precedent.

I see you considered some alternatives, did you think about duplicating the code in both places and keeping them both private? Looks like it's only 11 lines of code.

**Review by justinmc — COMMENTED** [review]
This is an old bug, thanks for tackling it. Reading through the description, it felt to me like a code smell that we have this kind of problem at all. It seems like a footgun.

But I was unable to think of a better way of doing things. Maybe it's the nature of IndexedStack itself that makes this tricky. I guess it's IndexedStack's responsibility to make sure that it's not breaking the use of Positioned in its children, and your solution fixes it at the IndexedStack level, so I think your solution is good.

File: packages/flutter/lib/src/widgets/visibility.dart (hunk 3 above)
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/visibility.dart]: I'm confident in setting the precedent, I think there are cases where we want to expose an API within the library but not outside. Sort of a middle ground between public and private.

I'm skeptical about duplicating the code, while it is a small class it feels hacky to duplicate because any changes in one implementation will need to be done in the other, and so it can be easy to go out of sync. 

I know we're doing a similar duplication in tests, but in that context I actually prefer it because tests are sandboxed, trivial-ish, and the less coupled they are the better.

Comment (navaronbracke) [reply packages/flutter/lib/src/widgets/visibility.dart]: Once we decided on the rule of if it is allowed to use it, we could put this in the Style Guide? (a section for internal API's?)

File: packages/flutter/lib/src/widgets/visibility.dart [hunk 4]
```diff
@@ -312,13 +313,19 @@ class Visibility extends StatelessWidget {
...
+class VisibilityScope extends InheritedWidget {
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/visibility.dart]: I recommend also marking this class `final` so no one outside this library can extend it. If we do change this API later that would make it easier/safer.

File: packages/flutter/lib/widgets.dart [hunk 5]
```diff
@@ -181,7 +181,7 @@ export 'src/widgets/unique_widget.dart';
 export 'src/widgets/value_listenable_builder.dart';
 export 'src/widgets/view.dart';
 export 'src/widgets/viewport.dart';
-export 'src/widgets/visibility.dart';
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/widgets.dart:184]: Does hiding `VisibilityScope` here possibly contradict the style guide https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#structure wrt exporting public APIs?

File: packages/flutter/lib/src/widgets/visibility.dart (hunk 4 above)
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/visibility.dart]: I'd be curious if there are similar APIs like this that we have exposed in the framework, i.e. a simple inherited widget that provides a bool to certain components.

File: packages/flutter/lib/widgets.dart (hunk 5 above)
Comment (victorsanni) [reply packages/flutter/lib/widgets.dart:184]: Hmm... It looks like it for sure.


> When developing new features in Flutter packages, one should follow the philosophy:
> 
> Only expose the APIs that are necessities to the features.
> 
> Since the private classes in dart language are file-bound, this may often result in large file sizes. In Flutter, this is considered to be more preferable than creating multiple smaller files but exposing intermediate classes that are not needed to use the features.


So should we change the solution to option 3 in the PR description (move IndexedStack impl. to `visibility.dart`?)

File: packages/flutter/lib/src/widgets/visibility.dart (hunk 3 above)
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/visibility.dart]: Actually @justinmc you are right here. The style guide explicitly warns about semi-private APIs:

> When developing new features in Flutter packages, one should follow the philosophy:
> 
> Only expose the APIs that are necessities to the features.
> 
> Since the private classes in dart language are file-bound, this may often result in large file sizes. In Flutter, this is considered to be more preferable than creating multiple smaller files but exposing intermediate classes that are not needed to use the features.

So the solution here might be to move IndexedStack into `visibility.dart`. What do you think?

File: packages/flutter/lib/widgets.dart (hunk 5 above)
Comment (navaronbracke) [reply packages/flutter/lib/widgets.dart:184]: Do we have a "visibility_scope.dart" file? I agree that we should follow the written rule in the style guide, but then discoverability might take a hit (as discussed before)

File: packages/flutter/test/widgets/indexed_stack_test.dart [hunk 6]
```diff
@@ -0,0 +1,422 @@
...
+      ),
+    );
+
+    await tester.tap(find.text('hiddenChild', skipOffstage: false), warnIfMissed: false);
+    await tester.pump();
+
+    expect(tapped, false);
+  });
+
+  testWidgets('IndexedStack supports Positioned children', (WidgetTester tester) async {
```
Comment (victorsanni) [inline packages/flutter/test/widgets/indexed_stack_test.dart:264]: This is the only test added in this PR, the others were just moved over from `stack_test.dart`.

File: packages/flutter/lib/src/widgets/indexed_stack.dart [hunk 7]
```diff
@@ -12,11 +12,197 @@ library;
...
+
+  /// The child widgets of the stack.
+  ///
+  /// Only the child at index [index] will be shown.
+  ///
+  /// See [Stack.children] for more information.
+  final List<Widget> children;
+
+  @override
+  Widget build(BuildContext context) {
```
Comment (victorsanni) [inline packages/flutter/lib/src/widgets/indexed_stack.dart:91]: The `build` method is changing, but the rest is just copied over from `basic.dart`.

File: packages/flutter/test/widgets/indexed_stack_test.dart [hunk 8]
```diff
@@ -0,0 +1,422 @@
...
+    expect(positionedBox.size, const Size(30.0, 40.0));
+
+    // The Positioned render object must be a direct child of the
+    // RenderIndexedStack; no render object should sit between them.
+    expect(positionedBox.parent, isA<RenderIndexedStack>());
+
+    // Non-Positioned siblings still report correct visibility.
+    final Element siblingElement = tester.element(find.byKey(siblingKey, skipOffstage: false));
+    expect(Visibility.of(siblingElement), isFalse);
+  });
```
Comment (navaronbracke) [inline packages/flutter/test/widgets/indexed_stack_test.dart]: Missing a blank line here

File: packages/flutter/test/widgets/indexed_stack_test.dart [hunk 9]
```diff
@@ -0,0 +1,422 @@
...
+  testWidgets('Can update clipBehavior of IndexedStack', (WidgetTester tester) async {
```
Comment (navaronbracke) [inline packages/flutter/test/widgets/indexed_stack_test.dart:307]: Blank line here?

**Review by navaronbracke — APPROVED** [review]

File: packages/flutter/lib/src/widgets/visibility.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/visibility.dart]: It's a little weird having Visibility and SliverVisibility inside of indexed_stack.dart, but I guess it's no weirder than the 8000+ line basic.dart itself and all of the different stuff in there. Also, I think it's wise to keep _VisibilityScope private (as you have done) because it seems too specific to be a public widget. So I'm on board for lack of a better idea.

**Review by justinmc — APPROVED** [review]
LGTM 👍

**Review by Renzo-Olivares — APPROVED** [review]
LGTM
