### PR TITLE
Log XCResult before other build issues

### LINKED ISSUE #100723: Xcode build failures are not printed when codesigning is off
https://github.com/flutter/flutter/pull/94747 parsed the xcresult bundle and printed the errors from Xcode when the build fails.  However, that output is not printed when there are other issues detected.

For example, this [test has a build failure](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8818937356027197105/+/u/run_module_test_ios/test_stdout
), but it's not printing the Xcode error because it's falling through here:
https://github.com/flutter/flutter/blob/b53ed9ba4a54ce009571647d258f1395989175aa/packages/flutter_tools/lib/src/ios/mac.dart#L611-L614

Instead, the xcresult errors should be moved to the top of `diagnoseXcodeBuildFailure` so it's always printed.

### PR DESCRIPTION
**Pull request by cyanglaz**
Always log XCResult first so it won't get lost if there are other issues.

Also updated the order issues are detected.
Some sample error messages after the change are:
1. no provisioning profile:
```
Error (Xcode): "Runner" requires a provisioning profile. Select a provisioning profile in the Signing & Capabilities editor.


════════════════════════════════════════════════════════════════════════════════
No Provisioning Profile was found for your project's Bundle Identifier or your 
device. You can create a new Provisioning Profile for your project in Xcode for 
your team by:
  1- Open the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team. 
     You may need to:
         - Log in with your Apple ID in Xcode first
         - Ensure you have a valid unique Bundle ID
         - Register your device with your Apple Developer Account
         - Let Xcode automatically provision a profile for your app
  4- Build or run your project again

It's also possible that a previously installed app with the same Bundle 
Identifier was signed with a different certificate.

For more information, please visit:
  https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices

Or run on an iOS simulator without code signing
════════════════════════════════════════════════════════════════════════════════
```

2. no development team

```
Error (Xcode): Signing for "Runner" requires a development team. Select a development team in the Signing & Capabilities editor.


════════════════════════════════════════════════════════════════════════════════
Building a deployable iOS app requires a selected Development Team with a 
Provisioning Profile. Please ensure that a Development Team is selected by:
  1- Open the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- Make sure a 'Development Team' is selected under Signing & Capabilities > Team. 
     You may need to:
         - Log in with your Apple ID in Xcode first
         - Ensure you have a valid unique Bundle ID
         - Register your device with your Apple Developer Account
         - Let Xcode automatically provision a profile for your app
  4- Build or run your project again

For more information, please visit:
  https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices

Or run on an iOS simulator without code signing
════════════════════════════════════════════════════════════════════════════════

It appears that your application still contains the default signing identifier.
Try replacing 'com.example' with your signing id in Xcode:
  open ios/Runner.xcworkspace
Encountered error while building for device.
```

Fixes https://github.com/flutter/flutter/issues/100723

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 1]
```diff
@@ -572,6 +572,19 @@ Future<void> diagnoseXcodeBuildFailure(XcodeBuildResult result, Usage flutterUsa
...
   }
 
+  // Handle xcresult errors.
+  final XCResult? xcResult = result.xcResult;
+  if (xcResult == null) {
+    return;
+  }
+  if (xcResult.parseSuccess) {
+    for (final XCResultIssue issue in xcResult.issues) {
+      _handleXCResultIssue(issue: issue, logger: logger);
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/mac.dart:582]: What happens when there's `provisioning profile` in the error?  Looks like `_handleXCResultIssue` and the `noProvisioningProfileInstruction` check below both output?

Comment (cyanglaz) [reply packages/flutter_tools/lib/src/ios/mac.dart:582]: What do you mean? The `_handleXCResultIssue` has a special case to handles general provisioning profile issues and have some special logs for it. It doesn't print the `noProvisioningProfileInstruction`. The later check `(result.stdout?.contains("Xcode couldn't find a provisioning profile matching")` would print an instruction for user if they don't have a provisioning profile in the project.

Did you mean we can add the special "no provisioning profile" case check in `_handleXCResultIssue`?

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/mac.dart:582]: Before your change, if there was a provisioning profile issue it would print this and return:
https://github.com/flutter/flutter/blob/c01cbd23cce18fac149ce8206516cde00e9d40b7/packages/flutter_tools/lib/src/ios/mac.dart#L590-L597
Now, it prints 
https://github.com/flutter/flutter/blob/c01cbd23cce18fac149ce8206516cde00e9d40b7/packages/flutter_tools/lib/src/ios/mac.dart#L748-L756
and then the above.  Unless I'm missing something.

What does that text together look like?  Probably needs to be adjusted, or the one only printed if the `xcresult` wasn't created?

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 2]
```diff
@@ -742,15 +707,48 @@ void _handleXCResultIssue({required XCResultIssue issue, required Logger logger}
...
-    logger.printError('  open ios/Runner.xcworkspace');
-    logger.printError('');
-    logger.printError("Also try selecting 'Product > Build' to fix the problem:");
+  // Add more error messages for flutter users for some special errors.
+  if (issue.message != null ) {
+    final String message = issue.message!;
+    if (message.toLowerCase().contains('requires a provisioning profile.')) {
+      logger.printError(noProvisioningProfileInstruction, emphasis: true);
+    } else if(message.toLowerCase().contains('provisioning profile')) {
+      logger.printError(noDevelopmentTeamInstruction, emphasis: true);
```
Comment (cyanglaz) [inline packages/flutter_tools/lib/src/ios/mac.dart:716]: The `noDevelopmentTeamInstruction` is documented as a fallback message for signing issues. I do think it is a more proper user message + instructions. Let me know if you think otherwise. @jmagman

**Review by cyanglaz — COMMENTED** [review]
@jmagman Updated per our offline discussion. PTAL.
I will update the PR description to reflect all the changes when the general idea of the PR is agreed.

**Comment by jmagman** [comment]
Looks like there are some test failures
```
00:36 +1153 -1: test/general.shard/ios/mac_test.dart: Diagnose Xcode build failure No development team shows message [E]                                                                               
  Expected: contains 'Building a deployable iOS app requires a selected Development Team with a \n'
              'Provisioning Profile.'
    Actual: ''
  
  package:test_api                            expect
  test/general.shard/ios/mac_test.dart 317:7  main.<fn>.<fn>
```

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 3]
```diff
@@ -742,15 +707,48 @@ void _handleXCResultIssue({required XCResultIssue issue, required Logger logger}
...
-  if (issue.message != null && issue.message!.toLowerCase().contains('provisioning profile')) {
-    logger.printError('');
-    logger.printError('It appears that there was a problem signing your application prior to installation on the device.');
-    logger.printError('');
-    logger.printError('Verify that the Bundle Identifier in your project is your signing id in Xcode');
-    logger.printError('  open ios/Runner.xcworkspace');
-    logger.printError('');
-    logger.printError("Also try selecting 'Product > Build' to fix the problem:");
+  // Add more error messages for flutter users for some special errors.
+  if (issue.message != null ) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/mac.dart:711]:
```suggestion
  if (issue.message != null) {
```

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 4]
```diff
@@ -742,15 +707,48 @@ void _handleXCResultIssue({required XCResultIssue issue, required Logger logger}
...
+    final String message = issue.message!;
+    if (message.toLowerCase().contains('requires a provisioning profile.')) {
+      logger.printError(noProvisioningProfileInstruction, emphasis: true);
+    } else if(message.toLowerCase().contains('provisioning profile')) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/mac.dart:715]:
```suggestion
    } else if (message.toLowerCase().contains('provisioning profile')) {
```

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 5]
```diff
@@ -742,15 +707,48 @@ void _handleXCResultIssue({required XCResultIssue issue, required Logger logger}
...
+    }
+    return issueDetected;
+  } else {
+    globals.printTrace('XCResult parsing error: ${xcResult.parsingErrorMessage}');
+    return false;
+  }
+}
+
+// Detects and handles errors without using xcresult.
+void  _handleIssuesWithoutUsingXCResult(XcodeBuildExecution xcodeBuildExecution, Logger logger, XcodeBuildResult result) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/mac.dart:737]:
```suggestion
void _handleIssuesWithoutUsingXCResult(XcodeBuildExecution xcodeBuildExecution, Logger logger, XcodeBuildResult result) {
```

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 6]
```diff
@@ -742,15 +707,48 @@ void _handleXCResultIssue({required XCResultIssue issue, required Logger logger}
...
+      // May need updating if Xcode changes its outputs.
+      && (result.stdout?.contains('requires a provisioning profile. Select a provisioning profile in the Signing & Capabilities editor') ?? false)) {
+    logger.printError(noProvisioningProfileInstruction, emphasis: true);
+    return;
+  }
+  // Make sure the user has specified one of:
+  // * DEVELOPMENT_TEAM (automatic signing)
+  // * PROVISIONING_PROFILE (manual signing)
+  if (xcodeBuildExecution.environmentType == EnvironmentType.physical &&
+      !<String>['DEVELOPMENT_TEAM', 'PROVISIONING_PROFILE'].any(
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/mac.dart:748]: This seems like a better situation to use `noDevelopmentTeamInstruction` instead of `message.toLowerCase().contains('provisioning profile')` since it actually checks if you have `DEVELOPMENT_TEAM` or `PROVISIONING_PROFILE` set.  Can we pipe the `xcodeBuildExecution` into the xcresult handler to do similar checking?

Comment (cyanglaz) [reply packages/flutter_tools/lib/src/ios/mac.dart:749]: This is technically not part of handing xcresult. XCResult does detect this error by showing a message: ```
Showing Recent Messages
Signing for "Runner" requires a development team. Select a development team in the Signing & Capabilities editor.

```

How about move this part where we directly check the flags all the way above xcresult handling? 

So the flow becomes:
1. Check `DEVELOPMENT_TEAM` and `PROVISIONING_PROFILE` flags.
2. Handle xcresults
3. Handle other issues with stdout.

**Comment by jmagman** [comment]
```
00:23 +142 -1: test/commands.shard/hermetic/build_ipa_test.dart: Extra error message for provision profile issue in xcresulb bundle. [E]                                                               
  Expected: contains 'It appears that there was a problem signing your application prior to installation on the device.'
    Actual: 'Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.\n'
              'Semantic Issue (Xcode): Some Provisioning profile issue.\n'
              '\n'
              '════════════════════════════════════════════════════════════════════════════════\n'
              'Building a deployable iOS app requires a selected Development Team with a \n'
              'Provisioning Profile. Please ensure that a Development Team is selected by:\n'
              '  1- Open the Flutter project\'s Xcode target with\n'
              '       open ios/Runner.xcworkspace\n'
              '  2- Select the \'Runner\' project in the navigator then the \'Runner\' target\n'
              '     in the project settings\n'
              '  3- Make sure a \'Development Team\' is selected under Signing & Capabilities > Team. \n'
              '     You may need to:\n'
              '         - Log in with your Apple ID in Xcode first\n'
              '         - Ensure you have a valid unique Bundle ID\n'
              '         - Register your device with your Apple Developer Account\n'
              '         - Let Xcode automatically provision a profile for your app\n'
              '  4- Build or run your project again\n'
              '\n'
              'For more information, please visit:\n'
              '  [https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices\n](https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices%5cn)'
              '\n'
              'Or run on an iOS simulator without code signing\n'
              '════════════════════════════════════════════════════════════════════════════════\n'
              ''
```

File: packages/flutter_tools/lib/src/ios/mac.dart (hunk 6 above)
Comment (cyanglaz) [reply packages/flutter_tools/lib/src/ios/mac.dart:749]: > I'm not following this, why would this one example be a special case where it's handled before the message is parsed?

So the "Check DEVELOPMENT_TEAM and PROVISIONING_PROFILE flag" can be done regardless if xcresult's parsing is successful or not. If this check is part of xcresult handling, it will not be run when xcresult is failed to parse. Or we do the same thing in xcresult handling as well as the fallback error handling when xcresult is failed to parse?

Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/mac.dart:749]: I'm not sure how you want to organize it 🙂  We should only print out the same error once, and include useful recovery suggestions where possible.  There's currently fallback to string parsing if the result bundle fails to build, but maybe that never happens (or we should add `Usage` data about it to see).

**Comment by jmagman** [comment]
>  2. no development team
> It appears that your application still contains the default signing identifier.
Try replacing 'com.example' with your signing id in Xcode:
  open ios/Runner.xcworkspace
Encountered error while building for device.

> It appears that your application still contains the default signing identifier.
Try replacing 'com.example' with your signing id in Xcode:
  open ios/Runner.xcworkspace
Encountered error while building for device.

This is twice in the description.  Is that a typo or did it actually print twice?

**Comment by cyanglaz** [comment]
> > 2. no development team
> >    It appears that your application still contains the default signing identifier.
> >    Try replacing 'com.example' with your signing id in Xcode:
> >    open ios/Runner.xcworkspace
> >    Encountered error while building for device.
> 
> > It appears that your application still contains the default signing identifier.
> > Try replacing 'com.example' with your signing id in Xcode:
> > open ios/Runner.xcworkspace
> > Encountered error while building for device.
> 
> This is twice in the description. Is that a typo or did it actually print twice?

It was a typo

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 7]
```diff
@@ -744,16 +708,89 @@ void _handleXCResultIssue({required XCResultIssue issue, required Logger logger}
...
   }
 
-  // Add more custom output for flutter users.
-  if (issue.message != null && issue.message!.toLowerCase().contains('provisioning profile')) {
+  if (issue.message == null) {
+    return _XCResultIssueHandlingResult(requiresProvisioningProfile: false, hasProvisioningProfileIssue: false);
+  }
+
+  // Add more error messages for flutter users for some special errors.
+  final String message = issue.message!;
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/mac.dart:716]: If you make the local before the null check you won't need the `!`
```suggestion
  // Add more error messages for flutter users for some special errors.
  final String? message = issue.message;
  
  if (issue.message == null) {
    return _XCResultIssueHandlingResult(requiresProvisioningProfile: false, hasProvisioningProfileIssue: false);
  }
```

**Review by jmagman — APPROVED** [review]
LGTM w/ minor nit
