### PR TITLE
[flutter_tools] retry sever socket setup (and port selection if port is unspecified)

### LINKED ISSUE #69348: Web flake in expression evaluation tests
```
14:44 +66 ~7 -1: test/integration.shard/expression_evaluation_web_test.dart: flutter test expression evaluation - can evaluate complex expressions in a test [E]                                       
  Exception: Received app.stop event while waiting for app.started event
  
  Failed to bind web development server:
  SocketException: Failed to create server socket (OS Error: The shared flag to bind() needs to be `true` if binding multiple times on the same (address, port) combination.), address = ::1, port = 44705
  
  #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
  #1      WebAssetServer.start (package:flutter_tools/src/isolated/devfs_web.dart:277:7)
  <asynchronous suspension>
  #2      WebDevFS.create (package:flutter_tools/src/isolated/devfs_web.dart:800:43)
  #3      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:516:44)
  #4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
  #5      _rootRun (dart:async/zone.dart:1190:13)
  #6      _CustomZone.run (dart:async/zone.dart:1093:19)
  #7      _runZoned (dart:async/zone.dart:1630:10)
  #8      runZonedGuarded (dart:async/zone.dart:1618:12)
  #9      runZoned (dart:async/zone.dart:1547:12)
  #10     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
  #11     _ResidentWebRunner.run (package:flutter_tools/src/isolated/resident_web_runner.dart:496:20)
  <asynchronous suspension>
  #12     AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:516:23)
  #13     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:586:26)
  #14     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:1078:18)
  #15     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:584:15)
  #16     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:510:12)
  #17     _rootRunUnary (dart:async/zone.dart:1198:47)
  #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
  #19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
  #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
  #21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
  #22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
  #23     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
  #24     _rootRun (dart:async/zone.dart:1190:13)
  #25     _CustomZone.run (dart:async/zone.dart:1093:19)
  #26     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
  #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
  #28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
  #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
  
  
  
  dart:async                                                         _Completer.completeError
  test/integration.shard/test_driver.dart 379:18                     FlutterTestDriver._waitFor.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart                            FlutterTestDriver._waitFor.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                         _StreamImpl.listen
  test/integration.shard/test_driver.dart 358:35                     FlutterTestDriver._waitFor
  test/integration.shard/test_driver.dart 553:54                     FlutterRunTestDriver._setupProcess.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart                            FlutterRunTestDriver._setupProcess.<fn>
  test/integration.shard/test_driver.dart 572:6                      FlutterRunTestDriver._setupProcess
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart 455:11                     FlutterRunTestDriver.run
  test/integration.shard/expression_evaluation_web_test.dart 140:22  batch2.startPaused
  test/integration.shard/expression_evaluation_web_test.dart 164:22  batch2.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  test/integration.shard/expression_evaluation_web_test.dart         batch2.<fn>
  dart:async                                                         runZoned
  test/src/common.dart 220:14                                        testWithoutContext.<fn>
  test/src/common.dart 190:18                                        test.<fn>
  
  Exception: Exception: Received app.stop event while waiting for app.debugPort event
  
  Failed to bind web development server:
  SocketException: Failed to create server socket (OS Error: The shared flag to bind() needs to be `true` if binding multiple times on the same (address, port) combination.), address = ::1, port = 44705
  
  #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
  #1      WebAssetServer.start (package:flutter_tools/src/isolated/devfs_web.dart:277:7)
  <asynchronous suspension>
  #2      WebDevFS.create (package:flutter_tools/src/isolated/devfs_web.dart:800:43)
  #3      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:516:44)
  #4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
  #5      _rootRun (dart:async/zone.dart:1190:13)
  #6      _CustomZone.run (dart:async/zone.dart:1093:19)
  #7      _runZoned (dart:async/zone.dart:1630:10)
  #8      runZonedGuarded (dart:async/zone.dart:1618:12)
  #9      runZoned (dart:async/zone.dart:1547:12)
  #10     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
  #11     _ResidentWebRunner.run (package:flutter_tools/src/isolated/resident_web_runner.dart:496:20)
  <asynchronous suspension>
  #12     AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:516:23)
  #13     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:586:26)
  #14     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:1078:18)
  #15     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:584:15)
  #16     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:510:12)
  #17     _rootRunUnary (dart:async/zone.dart:1198:47)
  #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
  #19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
  #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
  #21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
  #22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
  #23     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
  #24     _rootRun (dart:async/zone.dart:1190:13)
  #25     _CustomZone.run (dart:async/zone.dart:1093:19)
  #26     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
  #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
  #28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
  #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
  
  
  
  dart:async                                                         _Completer.completeError
  test/integration.shard/test_driver.dart 379:18                     FlutterTestDriver._waitFor.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart                            FlutterTestDriver._waitFor.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                         _StreamImpl.listen
  test/integration.shard/test_driver.dart 358:35                     FlutterTestDriver._waitFor
  test/integration.shard/test_driver.dart 556:56                     FlutterRunTestDriver._setupProcess.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart                            FlutterRunTestDriver._setupProcess.<fn>
  test/integration.shard/test_driver.dart 572:6                      FlutterRunTestDriver._setupProcess
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart 455:11                     FlutterRunTestDriver.run
  test/integration.shard/expression_evaluation_web_test.dart 140:22  batch2.startPaused
  test/integration.shard/expression_evaluation_web_test.dart 164:22  batch2.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                         _asyncThenWrapperHelper
  test/integration.shard/expression_evaluation_web_test.dart         batch2.<fn>
  dart:async                                                         runZoned
  test/src/common.dart 220:14                                        testWithoutContext.<fn>
  test/src/common.dart 190:18                                        test.<fn>
  

14:44 +66 ~7 -1: loading test/integration.shard/command_output_test.dart                                                                                                                               
14:45 +66 ~7 -1: loading test/integration.shard/command_output_test.dart                                                                                                                               
14:46 +66 ~7 -1: loading test/integration.shard/command_output_test.dart                                                                                                                               
14:47 +66 ~7 -1: loading test/integration.shard/command_output_test.dart    
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes https://github.com/flutter/flutter/issues/69348

If the web development server fails to bind, then retry up to 5 times. If a port was not provided, select a new free port each time.

### CODE REVIEW

File: packages/flutter_tools/lib/src/isolated/devfs_web.dart [hunk 1]
```diff
@@ -171,113 +173,123 @@ class WebAssetServer implements AssetReader {
...
-        address = (await InternetAddress.lookup(hostname)).first;
+    InternetAddress address;
+    if (hostname == 'any') {
+      address = InternetAddress.anyIPv4;
+    } else {
+      address = (await InternetAddress.lookup(hostname)).first;
+    }
+    HttpServer httpServer;
+    dynamic lastError;
+    for (int i = 0; i < 5; i += 1) {
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/isolated/devfs_web.dart:184]: If there's a way to tell that the SocketException is permament I'd do `while (true)`

File: packages/flutter_tools/lib/src/isolated/devfs_web.dart [hunk 2]
```diff
@@ -171,113 +173,123 @@ class WebAssetServer implements AssetReader {
...
+      try {
+        httpServer = await HttpServer.bind(address, port ?? await globals.os.findFreePort());
+        break;
+      } on SocketException catch (error) {
+        lastError = error;
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/isolated/devfs_web.dart:189]: Maybe insert `await Future.delayed(Duration(milliseconds: 100))` or something? In case this is happening while something else is struggling to shut down?

**Review by yjbanov — APPROVED** [review]
lgtm

File: packages/flutter_tools/lib/src/isolated/devfs_web.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/isolated/devfs_web.dart:184]: WDYM by permanent?

File: packages/flutter_tools/lib/src/isolated/devfs_web.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/isolated/devfs_web.dart:189]: Done

File: packages/flutter_tools/lib/src/isolated/devfs_web.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/isolated/devfs_web.dart:184]: I think generally no, if another program is holding this port we likely can't tell when it will terminate
