### PR TITLE
Apply the paint offset to the bounds rectangle for shader masks

### LINKED ISSUE #10424: ShaderMask is broken by the shifting done by Align
This works:
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    new Align(
      alignment: FractionalOffset.topLeft,
      child: new SizedBox(
        width: 400.0,
        height: 400.0,
        child: new FittedBox(
          child: new ShaderMask(
            shaderCallback: (Rect bounds) {
              return new RadialGradient(
                center: FractionalOffset.topLeft,
                radius: 1.0,
                colors: <Color>[Colors.yellow, Colors.deepOrange.shade900],
                tileMode: TileMode.repeated,
              ).createShader(bounds);
            },
            blendMode: BlendMode.modulate,
            child: const Text('I’m burning the memories'),
          ),
        ),
      ),
    ),
  );
}
```

If you change `alignment: FractionalOffset.topLeft` to `alignment: FractionalOffset.center` then it stops working.

cc @jason-simmons @abarth

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/10424

### CODE REVIEW

**Comment by jason-simmons** [comment]
@abarth @Hixie

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 1]
```diff
@@ -830,7 +830,7 @@ class RenderShaderMask extends RenderProxyBox {
   void paint(PaintingContext context, Offset offset) {
     if (child != null) {
       assert(needsCompositing);
-      final Rect rect = Offset.zero & size;
+      final Rect rect = offset & size;
```
Comment (abarth) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: I'm not sure this is completely correct.  We pass the offset to pushShaderMask as well, which is redundant with the rect that we pass now.  I'd look at how the other functions (e.g., clip) handle this case.  I thought we always passed the rects before applying the offset.

I guess the tricky issue here is the shader callback?

Comment (jason-simmons) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: The offset is passed to pushShaderMask so it can be passed onward to the painter() callback.

pushClipRect() internally applies the offset to the clipRect and uses the result to construct the ClipRectLayer.

We could do something similar here - call _shaderCallback(offset & size) in RenderShaderMask.paint to build the shader.  Then, in pushShaderMask, use maskRect.shift(offset) as the maskRect when constructing the ShaderMaskLayer.

Would that be more consistent?

Comment (abarth) [inline packages/flutter/lib/src/rendering/proxy_box.dart]: Yes, I think so.

**Comment by abarth** [comment]
Also missing a test.

**Comment by jason-simmons** [comment]
Done - PTAL

**Comment by abarth** [comment]
LGTM
