### PR TITLE
Enhance input decorator padding logic for character counter in text f…

### LINKED ISSUE #175591: TextField helper text and character count overlap when using OutlineInputBorder
### Steps to reproduce

Internal b/445896477, client `huggsy`

Create a `TextInput` widget that specifies a decoration with a long `helperText`, an `OutlineInputBorder`, and a `maxLength`.

### Expected results

The helper text should not overlap the character count.

### Actual results

The helper text overlaps the character count.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: ListView(
          children: [
            const Text('Hello, World!'),
            Builder(
              builder: (context) => TextField(
                decoration: InputDecoration(
                  labelText: 'Label text',
                  helperText:
                      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do '
                      'eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut '
                      'enim ad minim veniam, quis nostrud exercitation ullamco laboris '
                      'nisi ut aliquip ex ea commodo consequat.',
                  border: OutlineInputBorder(
                    borderSide: BorderSide(
                      color: Theme.of(context).colorScheme.outline,
                      width: 1,
                    ),
                    // Setting gapPadding to 0 fixes the bug, but is not desirable.
                    // Increasing the gapPadding exacerbates the bug.
                    // gapPadding: 0,
                    borderRadius: BorderRadius.all(Radius.circular(4)),
                  ),
                ),
                maxLength: 200,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Image

</details>

### Logs

Logs: N/A

### Flutter Doctor output

Doctor output: N/A

### PR DESCRIPTION
**Pull request by RootHex200**
Updated the padding calculations in the _RenderDecoration class to conditionally apply padding based on the presence of a character counter. This change ensures that the layout accommodates the counter correctly, improving the overall appearance and usability of text input fields.

Fix: #175591

before:
image
after:
image

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

-  [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
-  [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
-  [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
-  [x] I signed the [CLA].
-  [x] I listed at least one issue that this PR fixes in the description above.
-  [x] I updated/added relevant documentation (doc comments with `///`).
-  [x] I added new tests to check the change I am making, or this PR is [test-exempt].
-  [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
-  [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -1265,7 +1268,9 @@ class _RenderDecoration extends RenderBox
     final double counterHeight = _minHeight(counter, width);
     final double counterWidth = _minWidth(counter, counterHeight);
 
-    final double helperErrorAvailableWidth = math.max(width - counterWidth, 0.0);
+    // Only add padding when counter is present (maxLength is used)
+    final double counterPadding = counter != null ? 8.0 : 0.0;
```
[the remark this answers is not in the document]
Comment (bleroux) [reply packages/flutter/lib/src/material/input_decorator.dart]: Gemini is right there, a constant should be added at the top of the file with proper documentation.
Based on the M3 spec, the value should be 16.0, see https://m3.material.io/components/text-fields/specs#0c5c8d6d-2169-4d42-960c-51f6ee42eb57

**Review by bleroux — COMMENTED** [review]
@RootHex200 Thanks for working on this :pray: 

See my comment about creating a constant.
This PR will require a test.
The CI step 'Linux analyze' is failing due to code format. Using the dart auto formater should fix this issue.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 2]
```diff
@@ -922,8 +922,11 @@ class _RenderDecoration extends RenderBox
       null => (Size.zero, 0.0),
     };
 
+    // Only add padding when counter is present (maxLength is used)
+    final double counterPadding = counter != null ? 17 : 0.0;
```
[the remark this answers is not in the document]
Comment (victorsanni) [reply packages/flutter/lib/src/material/input_decorator.dart]: Bumping on https://github.com/flutter/flutter/pull/175706/files#r2366936696 for this as well.

**Review by victorsanni — COMMENTED** [review]
Hi @RootHex200, thanks for the PR. This PR will require a test in `flutter/test/material/input_decorator_test.dart` to land. Consider the other tests in the same file as a source of inspiration.

**Comment by RootHex200** [comment]
@victorsanni @bleroux   thanks for feedback . i am looking it

**Comment by RootHex200** [comment]
@victorsanni  @bleroux i have done , can you check

File: packages/flutter/test/material/input_decorator_test.dart [hunk 3]
```diff
@@ -15486,4 +15486,117 @@ void main() {
       expect(find.text(helperTextValue), findsOneWidget);
     },
   );
+
+  testWidgets('helper text and character counter do not overlap', (WidgetTester tester) async {
```
Comment (bleroux) [inline packages/flutter/test/material/input_decorator_test.dart:15666]:
```suggestion
  // Regression test for https://github.com/flutter/flutter/issues/175591.
  testWidgets('helper text and character counter do not overlap', (WidgetTester tester) async {
```

We usually add such regression comment for Material fixes. It makes easier to track tests history (it helps when the Git history is crippled after some big changes such as applying a new version of the auto format).

File: packages/flutter/test/material/input_decorator_test.dart [hunk 4]
```diff
@@ -15486,4 +15486,117 @@ void main() {
...
+              ),
+            ),
+          ),
+        ),
+      ),
+    );
+
+    await tester.pumpAndSettle();
+
+    // Find the helper text and counter widgets
```
Comment (bleroux) [inline packages/flutter/test/material/input_decorator_test.dart]:
```suggestion
    // Find the helper text and counter widgets.
```

Very minor, but it is better for consistency. Same for the other comments in this test.

File: packages/flutter/test/material/input_decorator_test.dart [hunk 5]
```diff
@@ -15486,4 +15486,117 @@ void main() {
...
+    final double counterLeft = counterPosition.dx;
+
+    // Verify that helper text and counter do not overlap
+    // The gap should be positive (no overlap) and reasonable
+    final double actualGap = counterLeft - helperTextRight;
+    expect(actualGap, greaterThan(0.0)); // No overlap
+    expect(actualGap, greaterThanOrEqualTo(8.0)); // Reasonable spacing
+  });
+
+  testWidgets('helper text and character counter spacing with different text lengths', (
```
Comment (bleroux) [inline packages/flutter/test/material/input_decorator_test.dart]: I would propose to remove this second test as the first one seems to be just what is needed to verify the fix.

File: packages/flutter/test/material/input_decorator_test.dart [hunk 6]
```diff
@@ -15486,4 +15486,117 @@ void main() {
...
+
+    // Calculate the right edge of helper text and left edge of counter
+    final double helperTextRight = helperTextPosition.dx + helperTextSize.width;
+    final double counterLeft = counterPosition.dx;
+
+    // Verify that helper text and counter do not overlap
+    // The gap should be positive (no overlap) and reasonable
+    final double actualGap = counterLeft - helperTextRight;
+    expect(actualGap, greaterThan(0.0)); // No overlap
+    expect(actualGap, greaterThanOrEqualTo(8.0)); // Reasonable spacing
```
Comment (bleroux) [inline packages/flutter/test/material/input_decorator_test.dart]: Any reason not to verify the spacing is exactly 16.0?

**Review by bleroux — COMMENTED** [review]
@RootHex200 Great update!

See my comments for test improvements.

One suggestion, once the review started it is better not to force push as it makes things more difficult to track for reviewers (before filing the PR, it is perfectly fine as the history of commits which led to the PR is usually more confusing than helpful).
I mention this because I remember seeing other changes in input_decorator.dart in your first iteration. I wanted to check if they were removed on purpose but I don't remember what lines were impacted).

**Comment by RootHex200** [comment]
> @RootHex200 Great update!
> 
> See my comments for test improvements.
> 
> One suggestion, once the review started it is better not to force push as it makes things more difficult to track for reviewers (before filing the PR, it is perfectly fine as the history of commits which led to the PR is usually more confusing than helpful). I mention this because I remember seeing other changes in input_decorator.dart in your first iteration. I wanted to check if they were removed on purpose but I don't remember what lines were impacted).

updated

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 7]
```diff
@@ -922,8 +926,10 @@ class _RenderDecoration extends RenderBox
       null => (Size.zero, 0.0),
     };
 
+    // Only add padding when counter is present (maxLength is used)
+    final double counterPadding = counter != null ? _kSubtextCounterPadding : 0.0;
     final BoxConstraints helperErrorConstraints = constraints.deflate(
-      EdgeInsets.only(left: counterSize.width),
+      EdgeInsets.only(left: counterSize.width + decoration.inputGap + counterPadding),
```
Comment (bleroux) [inline packages/flutter/lib/src/material/input_decorator.dart]:
```suggestion
      EdgeInsets.only(left: counterSize.width + decoration.inputGap * 2 + counterPadding),
```

I investigated why we did not get the expected 16.0 spacing between the helper/error and the counter in your test.
 I found that the inputGap should be applied twice: it is a gap which is added on both sides of the border. So the overall available width is reduced by inputGap * 2.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 8]
```diff
@@ -1265,7 +1271,12 @@ class _RenderDecoration extends RenderBox
     final double counterHeight = _minHeight(counter, width);
     final double counterWidth = _minWidth(counter, counterHeight);
 
-    final double helperErrorAvailableWidth = math.max(width - counterWidth, 0.0);
+    // Only add padding when counter is present (maxLength is used)
+    final double counterPadding = counter != null ? _kSubtextCounterPadding : 0.0;
+    final double helperErrorAvailableWidth = math.max(
+      width - counterWidth - decoration.inputGap - counterPadding,
```
Comment (bleroux) [inline packages/flutter/lib/src/material/input_decorator.dart]:
```suggestion
      width - counterWidth - decoration.inputGap * 2 - counterPadding,
```

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 9]
```diff
@@ -1265,7 +1271,12 @@ class _RenderDecoration extends RenderBox
     final double counterHeight = _minHeight(counter, width);
     final double counterWidth = _minWidth(counter, counterHeight);
 
-    final double helperErrorAvailableWidth = math.max(width - counterWidth, 0.0);
+    // Only add padding when counter is present (maxLength is used)
```
Comment (bleroux) [inline packages/flutter/lib/src/material/input_decorator.dart]:
```suggestion
    // Only add padding when counter is present (maxLength is used).
```

File: packages/flutter/test/material/input_decorator_test.dart [hunk 10]
```diff
@@ -15486,4 +15486,56 @@ void main() {
...
+
+    // Calculate the right edge of helper text and left edge of counter.
+    final double helperTextRight = helperTextPosition.dx + helperTextSize.width;
+    final double counterLeft = counterPosition.dx;
+
+    // Verify that helper text and counter do not overlap.
+    // The gap should be positive (no overlap) and exactly 16.0 pixels.
+    final double actualGap = counterLeft - helperTextRight;
+    expect(actualGap, greaterThan(0.0)); // No overlap
+    expect(actualGap, greaterThan(11.0)); // Exact spacing as per Material 3 specification
```
Comment (bleroux) [inline packages/flutter/test/material/input_decorator_test.dart]:
```suggestion
    expect(actualGap, 16.0); // Exact spacing as per Material 3 specification.
```

Now we get the correct padding :tada:

**Review by bleroux — COMMENTED** [review]
Format is ok now, great!

See my comments about a change which will get the exact 16.0 result from the spec.
Let me know if it makes sense.

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 7 above)
Comment (RootHex200) [reply packages/flutter/lib/src/material/input_decorator.dart]: i already investigation this.. 


### Before My Implementation:
### Without maxLength HelperText padding :
Using the following code:
dart

final BoxConstraints helperErrorConstraints = constraints.deflate(
  EdgeInsets.only(left: counterSize.width),
);
- Left padding: 16.0 pixels
- Right padding: 8.0 pixels

### With maxLength HelperText padding :
Using the same code:
dart

final BoxConstraints helperErrorConstraints = constraints.deflate(
  EdgeInsets.only(left: counterSize.width),
);
- Gap between helper text end and counter start: -8.0 pixels (negative gap indicates overlap)

## My Implementation Fix

### Updated Code (Without `maxLength`)
dart

final BoxConstraints helperErrorConstraints = constraints.deflate(
  EdgeInsets.only(left: counterSize.width + decoration.inputGap + counterPadding),
);
Results:
- Left padding: 16.0 pixels
- Right padding: 12.0 pixels
- Gap between helper text end and counter start: 12.0 pixels

### Final Fix to Achieve Consistent 16.0 Pixel Padding
To ensure consistent padding of 16.0 pixels on both sides and a proper gap, an additional 4.0 pixels were added:
dart

final BoxConstraints helperErrorConstraints = constraints.deflate(
  EdgeInsets.only(left: counterSize.width + decoration.inputGap + 4 + counterPadding),
);
Results:
- Left padding: 16.0 pixels
- Right padding: 16.0 pixels
- Gap between helper text end and counter start: 16.0 pixels

**Comment by RootHex200** [comment]
> Format is ok now, great!
> 
> See my comments about a change which will get the exact 16.0 result from the spec. Let me know if it makes sense.

Yeah, that makes sense. Thanks for your time and help. This was my first PR, and I really appreciate the guidance—it motivates me. I had already looked into this yesterday, and now I’ve updated the PR.

**Review by bleroux — APPROVED** [review]
LGTM! Thanks for this useful fix :pray: 

Next steps after my approval are:
- the Google testing Ci check will run, let see if it fails (this can happen if some internal Google tests relied on the previous behavior).
- get a second review, apply requested changes and get approval. cc @victorsanni, if you get a chance to do that second review.
- once everything will be green Victor or I will add the autosubmit label and your PR will land some time later. :rocket:

**Review by victorsanni — APPROVED** [review]

**Comment by victorsanni** [comment]
There are a ton of google testing failures. But most of the failures have text fields without a character count. So it visually just looks like extra padding for no reason.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 11]
```diff
@@ -922,8 +926,10 @@ class _RenderDecoration extends RenderBox
       null => (Size.zero, 0.0),
     };
 
+    // Only add padding when counter is present (maxLength is used).
+    final double counterPadding = counter != null ? _kSubtextCounterPadding : 0.0;
```
Comment (victorsanni) [inline packages/flutter/lib/src/material/input_decorator.dart:930]: Does `counter` being non-null necessarily mean that a character count is visually present?

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 12]
```diff
@@ -1265,7 +1271,12 @@ class _RenderDecoration extends RenderBox
     final double counterHeight = _minHeight(counter, width);
     final double counterWidth = _minWidth(counter, counterHeight);
 
-    final double helperErrorAvailableWidth = math.max(width - counterWidth, 0.0);
+    // Only add padding when counter is present (maxLength is used).
+    final double counterPadding = counter != null ? _kSubtextCounterPadding : 0.0;
```
Comment (victorsanni) [inline packages/flutter/lib/src/material/input_decorator.dart:1275]: Same here.

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 11 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/input_decorator.dart:930]: > Does counter being non-null necessarily mean that a character count is visually present?
I think so. 

Notice that we also add 'decoration.inputGap * 2' in this PR unconditionally that might be the issue. I will check tomorrow (it is the evening here).
Just weird that this is only caught in Google testing. We probably miss some test coverage for this case.

Comment (RootHex200) [reply packages/flutter/lib/src/material/input_decorator.dart:930]: yeah .if counter is present then counter can't be null.

Comment (bleroux) [reply packages/flutter/lib/src/material/input_decorator.dart:930]: @victorsanni Does all the failures have a long helper/error text?

It seems that before this PR, the helper/error width was wrong (only visible with long helper/error) as the helper/error padding on the right is only 8.0 pixels, should be 16.0 based on M3 spec.

Screenshot with a long container for InputDecoration.helper:

image

As you can see the left padding is not compliant compared to https://m3.material.io/components/text-fields/specs#0c5c8d6d-2169-4d42-960c-51f6ee42eb57

I will file a separate issue tomorrow and provide guidance to @RootHex200 to get this PR merged. What I have in mind is to land this PR without the 'decoration.inputGap * 2' adjustement, it will mean that:
- helper/error and counter won't overlap (which was the original reported issue).
- the gap between the error/helper and the counter will not be 16.0 for the moment (We will document this).

Doing so this PR will probably break no Google tests or a small number of them (if some capture the current wrong behavior).

Once this PR will be merged, I will try to land a PR to make those paddings compliant, then you and Justin would decide if the Google failures can be fixed.

Comment (victorsanni) [reply packages/flutter/lib/src/material/input_decorator.dart:930]: Yes, they all had long helper/error text. Thanks for finding this.

Comment (bleroux) [reply packages/flutter/lib/src/material/input_decorator.dart:930]: I filed https://github.com/flutter/flutter/issues/175993 which describes the padding issue.

@RootHex200 Sorry for the inconvenience. My suggestion is to proceed as I described in my previous comment, it means updating the PR in the following ways:
- remove the `decoration.inputGap * 2` adjustement.
- update the test to restore your previous use of greaterThanOrEqualTo(8). Above the line with that expect clause add a comment explaining that the expected value should be 16 but it's not because of https://github.com/flutter/flutter/issues/175993

Comment (RootHex200) [reply packages/flutter/lib/src/material/input_decorator.dart:930]: > I filed #175993 which describes the padding issue.
> 
> @RootHex200 Sorry for the inconvenience. My suggestion is to proceed as I described in my previous comment, it means updating the PR in the following ways:
> 
> * remove the `decoration.inputGap * 2` adjustement.
> * update the test to restore your previous use of greaterThanOrEqualTo(8). Above the line with that expect clause add a comment explaining that the expected value should be 16 but it's not because of [InputDecoration helper/error end padding is not compliant with M3 spec #175993](https://github.com/flutter/flutter/issues/175993)

updated now

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 13]
```diff
@@ -922,8 +926,10 @@ class _RenderDecoration extends RenderBox
       null => (Size.zero, 0.0),
     };
 
+    // Only add padding when counter is present (maxLength is used).
+    final double counterPadding = counter != null ? _kSubtextCounterPadding : 0.0;
     final BoxConstraints helperErrorConstraints = constraints.deflate(
-      EdgeInsets.only(left: counterSize.width),
+      EdgeInsets.only(left: counterSize.width + decoration.inputGap + counterPadding),
```
Comment (bleroux) [inline packages/flutter/lib/src/material/input_decorator.dart]:
```suggestion
      EdgeInsets.only(left: counterSize.width + counterPadding),
```
Sorry, my comment was unclear, I meant removing the full usage of `decoration.inputGap` not just the `* 2`. 

Doing so the helper/error width won't be changed unless there is a counter so we drastically reduce the chance of breaking existing Google tests.

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 14]
```diff
@@ -1265,7 +1271,12 @@ class _RenderDecoration extends RenderBox
     final double counterHeight = _minHeight(counter, width);
     final double counterWidth = _minWidth(counter, counterHeight);
 
-    final double helperErrorAvailableWidth = math.max(width - counterWidth, 0.0);
+    // Only add padding when counter is present (maxLength is used).
+    final double counterPadding = counter != null ? _kSubtextCounterPadding : 0.0;
+    final double helperErrorAvailableWidth = math.max(
+      width - counterWidth - decoration.inputGap - counterPadding,
```
Comment (bleroux) [inline packages/flutter/lib/src/material/input_decorator.dart]:
```suggestion
      width - counterWidth -  counterPadding,
```
Same here

File: packages/flutter/test/material/input_decorator_test.dart [hunk 15]
```diff
@@ -15662,4 +15662,58 @@ void main() {
...
+    // Calculate the right edge of helper text and left edge of counter.
+    final double helperTextRight = helperTextPosition.dx + helperTextSize.width;
+    final double counterLeft = counterPosition.dx;
+
+    // Verify that helper text and counter do not overlap.
+    // The gap should be positive (no overlap) and at least 8.0 pixels.
+    final double actualGap = counterLeft - helperTextRight;
+    expect(actualGap, greaterThan(0.0)); // No overlap
+    // The expected value should be 16.0 but it's not because of InputDecoration
+    // helper/error end padding is not compliant with M3 spec https://github.com/flutter/flutter/issues/175993.
```
Comment (bleroux) [inline packages/flutter/test/material/input_decorator_test.dart]:
```suggestion
    // The expected value should be 16.0 but it's not because
    // helper/error end padding is not compliant with M3 spec,
    // see https://github.com/flutter/flutter/issues/175993.
```

**Review by bleroux — COMMENTED** [review]
Thanks for the update! Just one last change and it should be fine.
See my comments.

**Comment by RootHex200** [comment]
> Thanks for the update! Just one last change and it should be fine. See my comments.

done

**Review by bleroux — APPROVED** [review]
LGTM!
Let see now if Google testing step run again (sometimes it does not and Victor might have to trigger it) and if there are failures :crossed_fingers: .

**Comment by bleroux** [comment]
@victorsanni Are there many Google testing failures now?

**Comment by victorsanni** [comment]
> Are there many Google testing failures now?

Less Google testing failures. I looked through them and I think they are expected because the padding between the error/helper text and the count was super small before this PR and more standard with this PR. But I am not a Material expert. I will reach out to @QuncCccccc to verify the images look good. But this LGTM.

**Review by victorsanni — APPROVED** [review]

**Review by QuncCccccc — APPROVED** [review]
LGTM. Thanks for the fix:)

I'm asking for approvals for cl/811419565. Once it's approved, we are good to go!

**Comment by RootHex200** [comment]
> LGTM. Thanks for the fix:)
> 
> I'm asking for approvals for cl/811419565. Once it's approved, we are good to go!

@QuncCccccc what about the approval

Thanks  ,

**Comment by QuncCccccc** [comment]
cl/811419565 has been approved. Merging this PR.
