### PR TITLE
Fix selection toolbar not showing on drag end

### LINKED ISSUE #119314: [SelectionArea] Selecting text and then resizing the selection dismisses the contextMenu
## Steps to Reproduce

1. Execute `flutter run` on the code sample (problem found on at least Android and iOS) 
2. Select any amount of text and finish the selection.
3. Resize the selection using the handles.

**Expected results:** 

The tooltip should reappear allowing for copying and other options.

**Actual results:** 

The tooltip does not reappear after resizing the text selection.
See attached video.

[selection_area_bug.webm](https://user-images.githubusercontent.com/10720298/215013411-18c92c9b-91c6-4280-918e-c77f83e3f03f.webm)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: const SelectionArea(
        child: Text('Text with content'),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
    • Flutter version 3.7.0 on channel stable at C:\Users\{user}\dev\bin\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (3 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\{user}\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.74.3)
    • VS Code at C:\Users\{user}\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1105]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 108.0.1462.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by jankuss**
Fixes #119314

The regression was caused initially by this commit: f014c1e6dcfdfbebaf379757273c4033a5092fbc

### Before

Before, ending the drag didn't show the toolbar, making it impossible to copy the text after adjusting the selection handles.

https://user-images.githubusercontent.com/1659532/220207752-dae81cf2-5ccb-4f13-b3c4-45c0e900f494.mov

### After

Now ending the drag will show the toolbar again:

https://user-images.githubusercontent.com/1659532/220207635-92275b58-7e14-4b57-83da-b12f7e9ed9af.mov

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 1]
```diff
@@ -533,6 +533,7 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
    } else {
      _selectionOverlay!.hideMagnifier();
      _selectionOverlay!.showToolbar(
+       context: context,
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/selectable_region.dart:536]: Good catch, context should be provided when contextMenuBuilder is provided.  Thanks!

File: packages/flutter/test/material/selection_area_test.dart [hunk 2]
```diff
@@ -133,4 +133,56 @@ void main() {
...
+    // This is the position of the selection handle displayed at the end
+    final Offset handlePos = paragraph2.localToGlobal(boxes[0].toRect().bottomRight);
+    await gesture.down(handlePos);
+    await gesture.moveTo(textOffsetToPosition(paragraph2, 11) + Offset(0, paragraph2.size.height / 2));
+    await tester.pump(const Duration(milliseconds: 500));
+    await tester.pump(const Duration(milliseconds: 500));
+
+    await gesture.up();
+    await tester.pump(const Duration(milliseconds: 500));
+    await tester.pump(const Duration(milliseconds: 500));
```
Comment (justinmc) [inline packages/flutter/test/material/selection_area_test.dart:180]: Can you replace these `pump`s with `pumpAndSettle` or, if possible, a `pump` with no Duration?  Ideally we shouldn't have any arbitrary timing things like this unless it's totally necessary.

**Review by justinmc — COMMENTED** [review]
Thank you for fixing this!  We totally missed this when implementing the magnifier.

Just a minor comment about the use of `pump` in your tests, and you also need to sync with the master branch.  Otherwise this should be good to go.

File: packages/flutter/test/material/selection_area_test.dart (hunk 2 above)
Comment (jankuss) [reply packages/flutter/test/material/selection_area_test.dart]: I was able to remove most of the `pump`s with duration, except for one location. I believe this one is necessary though, because it is also used in other tests.

For example, here:
https://github.com/flutter/flutter/blob/686266e4184a107b5e52ddc871cb5400d8caf9df/packages/flutter/test/material/selection_area_test.dart#L61

File: packages/flutter/test/material/selection_area_test.dart [hunk 3]
```diff
@@ -133,4 +133,53 @@ void main() {
...
+    await gesture.up();
+    final List<TextBox> boxes = paragraph2.getBoxesForSelection(paragraph2.selections[0]);
+    expect(boxes.length, 1);
+    // There is a selection now.
+    // We check the presence of the copy button to make sure the selection toolbar
+    // is showing.
+    expect(find.text('Copy'), findsOneWidget);
+
+    // This is the position of the selection handle displayed at the end
```
Comment (justinmc) [inline packages/flutter/test/material/selection_area_test.dart:170]: Period at the end of this sentence.

**Review by justinmc — APPROVED** [review]
LGTM 👍 

I re-ran two tests that looked like infrastructure flakes.

File: packages/flutter/test/material/selection_area_test.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/test/material/selection_area_test.dart]: Sounds good, it's fine like this then 👍

**Comment by justinmc** [comment]
The test failure is something unrelated that I've seen on another PR as well.  Can you push a merge commit?

File: packages/flutter/test/material/selection_area_test.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/material/selection_area_test.dart]: I think this particular use of `pump` is so the down event is held and detected as a long press.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Comment by mzdm** [comment]
Would be good cherry pick candidate IMO

**Comment by justinmc** [comment]
A new stable release will be cut soon with this fix in it, so I think that will work out and we won't need to cherry pick.

**Comment by justinmc** [comment]
Looks like this was tagged in [3.9.0-18.0.pre](https://github.com/flutter/flutter/releases/tag/3.9.0-18.0.pre).
