### PR TITLE
Theme.of provides all TextStyle properties

### LINKED ISSUE #12548: Tooltip text underlined twice with yellow color
## Steps to Reproduce
This seems to affect every Tooltip, but can most easily be seen by creating a new flutter project, running it, and long-pressing the floating action button:

```
flutter create test_tooltip
cd test_tooltip
flutter run
```

The tooltip shown after long-pressing the fab shown looks like this: 
icon
As far as I can tell, this has been introduced in the latest alpha update, but also occures on master.

## Flutter Doctor

```
[✓] Flutter (on Linux, locale de_DE.UTF-8, channel alpha)
    • Flutter at /home/simon/bin/flutter
    • Framework revision 4424892c79 (vor 4 Tagen), 2017-10-10 16:45:11 -0700
    • Engine revision 2a84f18c79
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /home/simon/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • GT I9300 • 32305bd8f5c48001 • android-arm • Android 7.1.2 (API 25)
```

### LINKED ISSUE #12550: Typography text styles aren't fully specified, yielding unexpected behavior
## Use case:

1. Create a shared constant app-wide theme, like so:

```
final appTheme = new ThemeData(
  // Define whatever styles you want, but leave the
  // text themes unspecified (and thus default).
  // In so doing, they'll get the default typography
  // values (e.g. blackMountainView), which as of
  // #12249, specify inherit:true
);
```

2. Create a `Text` widget somewhere in your app, with styles like so:

```
  new Text(
    'sample text',
    style: appTheme.primaryTextTheme.button,
  ),
```

3. The styling of the text widget will be `appTheme.primaryTextTheme.button`, _merged_ with whatever `DefaultTextStyle` happens to live immediately above the widget in the tree.  This is unexpected, since the user doesn't expect the default `primaryTextTheme.button` style to leave some properties ambiguously defined.

## Potential solutions:

1. Do nothing, and call this working as intended.  If the user doesn't want to inherit properties this way, they can do the following:

```
  new DefaultTextStyle(
    style: appTheme.primaryTextTheme.button,
    child: new Text(
      'sample text',
    ),
  ),
```

2. Add the ability to clone a `TextStyle` but change the `inherit` property, yielding user code like this:

```
  new Text(
    'sample text',
    style: appTheme.primaryTextTheme.button.copyWith(new TextStyle(inherit: false)),
  ),
```

3. ???

### PR DESCRIPTION
**Pull request by yjbanov**
Fixes https://github.com/flutter/flutter/issues/12548
Fixes https://github.com/flutter/flutter/issues/12550
See also https://github.com/flutter/flutter/pull/12537

This adds `decoration` property to `TextStyle`s vended by `Theme.of`.

### CODE REVIEW

File: packages/flutter/test/material/theme_test.dart [hunk 1]
```diff
@@ -367,6 +367,53 @@ void main() {
...
+        expect(style.fontWeight, isNotNull);
+        expect(style.fontStyle, null);
+        expect(style.letterSpacing, null);
+        expect(style.wordSpacing, null);
+        expect(style.textBaseline, isNotNull);
+        expect(style.height, null);
+        expect(style.decoration, TextDecoration.none);
+        expect(style.decorationColor, null);
+        expect(style.decorationStyle, null);
+      }
```
Comment (tvolkert) [inline packages/flutter/test/material/theme_test.dart]: It's too bad there's no way to force this test to be updated if any properties are added to `TextStyle`...

**Comment by tvolkert** [comment]
LGTM, but I'd wait for @Hixie to confirm that this is the right way to go before merging.

**Comment by Hixie** [comment]
I would prefer the output of Theme.of to be a ThemeData whose text styles are all inherit:false. That way, if we add anything else to TextStyle, we don't have to keep updating ThemeData.

**Comment by yjbanov** [comment]
> I would prefer the output of Theme.of to be a ThemeData whose text styles are all inherit:false.

Done (see 6885e8a). I wonder, however, if people would want to get `ThemeData` from `Theme.of`, alter it a bit, then feed it back to a `Theme` widget. We currently expect that `ThemeData` supplied to `Theme` is inherit:true so we can localize it.

Test case:

```dart
var original = Theme.of(context);
return new Theme(
  // This will fail during localization.
  theme: original.copyWith(
    accentTextTheme: someOtherTextTheme,
  ),
  child: someWidget,
);
```

One way to solve this is to not localize text styles that are inherit:false. Then in the example above we will localize `someOtherTextTheme` (if it's inherit:true), but not others.

**Comment by Hixie** [comment]
Discussion:
- TextStyle.merge should return other if other.inherit is false (rather than asserting)
- TextStyle should sprout a debugLabel (and have merge, lerp et al update it accordingly)
- update docs everywhere to be the right way round for inherit wrt Typography, ThemeData, etc.

**Comment by yjbanov** [comment]
https://github.com/flutter/flutter/pull/12552/commits/039a61f361ea688c968195cab3ff136368a8dcba and https://github.com/flutter/flutter/pull/12552/commits/dd85edfa4ae4db706cf32e757fb383414b3676cf change the `other.inherit` logic, update docs and add a `debugLabel` field to `TextStyle`.

**Comment by yjbanov** [comment]
PTAL

File: packages/flutter/lib/src/material/theme_data.dart [hunk 2]
```diff
@@ -137,9 +137,9 @@ class ThemeData {
     accentIconTheme ??= accentIsDark ? const IconThemeData(color: Colors.white) : const IconThemeData(color: Colors.black);
     platform ??= defaultTargetPlatform;
     final Typography typography = new Typography(platform: platform);
-    textTheme ??= isDark ? typography.white : typography.black;
-    primaryTextTheme ??= primaryIsDark ? typography.white : typography.black;
-    accentTextTheme ??= accentIsDark ? typography.white : typography.black;
+    textTheme ??= (isDark ? typography.white : typography.black).apply(decoration: TextDecoration.none);
+    primaryTextTheme ??= (primaryIsDark ? typography.white : typography.black).apply(decoration: TextDecoration.none);
+    accentTextTheme ??= (accentIsDark ? typography.white : typography.black).apply(decoration: TextDecoration.none);
```
Comment (Hixie) [inline packages/flutter/lib/src/material/theme_data.dart]: how would you feel about either removing these additions (relying on the way we inherit from a base that doesn't have an underline) or hard-coding them into the constants? It seems weird to have these done in the middle-ground manner.

File: packages/flutter/lib/src/painting/text_style.dart [hunk 3]
```diff
@@ -230,10 +232,13 @@ class TextStyle extends Diagnosticable {
     this.decoration,
     this.decorationColor,
     this.decorationStyle,
+    String debugLabel,
     String fontFamily,
     String package,
   }) : fontFamily = package == null ? fontFamily : 'packages/$package/$fontFamily',
-       assert(inherit != null);
+       debugLabel = debugLabel == null ? _kDefaultDebugLabel : debugLabel,
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_style.dart]: `debugLabel = debugLabel ?? _kDefaultDebugLabel`

Or, if it doesn't interfere with other logic, just make it a default and assert non-null.

File: packages/flutter/lib/src/painting/text_style.dart [hunk 4]
```diff
@@ -230,10 +232,13 @@ class TextStyle extends Diagnosticable {
...
+       assert(inherit != null),
+       assert(debugLabel == null || debugLabel.length <= 100);
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_style.dart]: I'd avoid the maximum length. It's likely that we'll accidentally exceed it at some point when creating a lerp of a lerp of a lerp or some crazy thing.

File: packages/flutter/lib/src/painting/text_style.dart [hunk 5]
```diff
@@ -302,6 +307,12 @@ class TextStyle extends Diagnosticable {
   /// The style in which to paint the text decorations (e.g., dashed).
   final TextDecorationStyle decorationStyle;
 
+  /// A human-readable description of this text style.
+  ///
+  /// This property is not considered when comparing text styles using `==` or
+  /// [compareTo], and it does not affect [hashCode].
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_style.dart]: say something about it only being managed in debug builds.

File: packages/flutter/lib/src/painting/text_style.dart [hunk 6]
```diff
@@ -332,11 +350,26 @@ class TextStyle extends Diagnosticable {
...
       decorationColor: decorationColor ?? this.decorationColor,
       decorationStyle: decorationStyle ?? this.decorationStyle,
+      debugLabel: newDebugLabel,
     );
   }
 
-  /// Creates a copy of this text style but with the numeric fields multiplied
-  /// by the given factors and then incremented by the given deltas.
+  static String _capDebugLabelLength(String label) {
+    const int maxLabelLength = 100;
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_style.dart]: i'd probably remove this entire function but if you do keep it:

- use the same constant everywhere (here and in the assert above)
- remove excessive braces

File: packages/flutter/lib/src/painting/text_style.dart [hunk 7]
```diff
@@ -390,19 +432,39 @@ class TextStyle extends Diagnosticable {
...
+      decorationStyle: decorationStyle ?? this.decorationStyle,
+      debugLabel: modifiedDebugLabel,
     );
   }
 
-  /// Returns a new text style that matches this text style but with some values
-  /// replaced by the non-null parameters of the given text style. If the given
-  /// text style is null, simply returns this text style.
+  /// Returns a new text style that is a combination of this style and the given
+  /// [other] style, following the following rules.
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_style.dart]: remove "following the following rules" because the first sentence needs to be able to stand alone.

File: packages/flutter/lib/src/painting/text_style.dart [hunk 8]
```diff
@@ -390,19 +432,39 @@ class TextStyle extends Diagnosticable {
...
+  ///
+  /// If the given [other] text style has its [TextStyle.inherit] set to true,
+  /// its null properties are replaced with the non-null properties of this text
+  /// style. It is said that the [other] style inherits properties of this
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_style.dart]: I'd probably strike "It is said that", it's one of those phrases that when you really get down to it doesn't add anything meaningful to the docs (like my personal nemesis, "Note that...").

File: packages/flutter/lib/src/painting/text_style.dart [hunk 9]
```diff
@@ -390,19 +432,39 @@ class TextStyle extends Diagnosticable {
...
+  /// style. Another way to think of it is that the "missing" properties of the
+  /// [other] style are filled by the properties of this style.
+  ///
+  /// If the given [other] text style has its [TextStyle.inherit] set to false,
+  /// simply returns the given [other] style unchanged. It is said that the
+  /// [other] style does not inherit properties of this style.
+  ///
+  /// If the given text style is null, simply returns this text style.
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_style.dart]: similarly with "simply". It just leads to people muttering "doesn't seem so simple to _me_" to themselves.

Comment (Hixie) [reply packages/flutter/lib/src/painting/text_style.dart]: not that i ever mutter to myself when reading documentation. no sir.

File: packages/flutter/lib/src/painting/text_style.dart [hunk 10]
```diff
@@ -564,6 +635,8 @@ class TextStyle extends Diagnosticable {
   @override
   void debugFillProperties(DiagnosticPropertiesBuilder properties, { String prefix: '' }) {
     super.debugFillProperties(properties);
+    if (debugLabel != _kDefaultDebugLabel)
+      properties.add(new StringProperty('${prefix}debugLabel', debugLabel, defaultValue: null));
```
Comment (Hixie) [inline packages/flutter/lib/src/painting/text_style.dart]: probably `showName: false`? Or maybe this is a MessageProperty? Check to see what @jacob314 did with the other debugLabels.

File: packages/flutter/test/material/theme_test.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/test/material/theme_test.dart]: There is one way. Have a class in this file that "implements" TextStyle. The analyzer will flag this file whenever we add a member.

File: packages/flutter/test/painting/text_style_test.dart [hunk 11]
```diff
@@ -142,4 +142,42 @@ void main() {
...
+    expect(TextStyle.lerp(foo, bar, 0.5).debugLabel, 'lerp(foo, bar)');
+    expect(TextStyle.lerp(foo.merge(bar), baz, 0.5).copyWith().debugLabel, 'copy of lerp(bar < foo, baz)');
+
+    expect(() => new TextStyle(debugLabel: 'a' * 300), throwsA(const isInstanceOf<AssertionError>()));
+
+    TextStyle cappedMerge = foo;
+    TextStyle cappedCopy = foo;
+    TextStyle cappedApply = foo;
+    TextStyle cappedLerp = foo;
+    for (int i = 0; i < 50; i++) {
```
Comment (Hixie) [inline packages/flutter/test/painting/text_style_test.dart]: `i += 1` (my preference) or `++i`

File: packages/flutter/test/painting/text_style_test.dart [hunk 12]
```diff
@@ -142,4 +142,42 @@ void main() {
...
+    expect(foo.debugLabel, 'foo');
+    expect(foo.toString(), 'TextStyle(debugLabel: "foo", inherit: true, size: 1.0)');
+    expect(foo.merge(bar).debugLabel, 'bar < foo');
+    expect(foo.merge(bar).merge(baz).debugLabel, 'baz < bar < foo');
+    expect(foo.copyWith().debugLabel, 'copy of foo');
+    expect(foo.apply().debugLabel, 'modified foo');
+    expect(TextStyle.lerp(foo, bar, 0.5).debugLabel, 'lerp(foo, bar)');
+    expect(TextStyle.lerp(foo.merge(bar), baz, 0.5).copyWith().debugLabel, 'copy of lerp(bar < foo, baz)');
+
+    expect(() => new TextStyle(debugLabel: 'a' * 300), throwsA(const isInstanceOf<AssertionError>()));
```
Comment (Hixie) [inline packages/flutter/test/painting/text_style_test.dart]: you can import flutter_test and use throwsAssertionError

File: packages/flutter/lib/src/painting/text_style.dart (hunk 3 above)
Comment (Hixie) [reply packages/flutter/lib/src/painting/text_style.dart]: Alternatively, default to null, which will be more efficient in release builds and in comparisons against the default value, and only bringing _kDefaultDebugLabel when you need to merge strings (using `debugLabel ?? _kDefaultDebugLabel`)

File: packages/flutter/lib/src/painting/text_style.dart (hunk 4 above)
Comment (Hixie) [reply packages/flutter/lib/src/painting/text_style.dart]: (...but need to see the whole length because it's meaningful in some way to what we're debugging, or something)

Comment (Hixie) [reply packages/flutter/lib/src/painting/text_style.dart]: I guess maybe you added this because in regular operation we generate 1000-long messages? I defer to your judgement on this. If we do generate ridiculous chains in normal operation, let me know, though. That seems surprising.

**Comment by Hixie** [comment]
LGTM

File: packages/flutter/lib/src/painting/text_style.dart (hunk 10 above)
Comment (jacob314) [reply packages/flutter/lib/src/painting/text_style.dart]: showName: false sounds reasonable. I don't see any other debugLabel properties added as diagnosticProperty. Generally, if you thing debugLabel does conceptually represent a property name, StringProperty is what you want. If debugLabel is just a debugging message you want to show than MessageProperty is what you want.

Comment (yjbanov) [reply packages/flutter/lib/src/painting/text_style.dart]: Thanks! Switched to `MessageProperty`.

File: packages/flutter/test/material/theme_test.dart (hunk 1 above)
Comment (yjbanov) [reply packages/flutter/test/material/theme_test.dart]: Wow, this trick is so devious that I implemented it.

File: packages/flutter/test/painting/text_style_test.dart (hunk 12 above)
Comment (yjbanov) [reply packages/flutter/test/painting/text_style_test.dart]: This is gone now.

File: packages/flutter/test/painting/text_style_test.dart (hunk 11 above)
Comment (yjbanov) [reply packages/flutter/test/painting/text_style_test.dart]: This is gone now.
