### PR TITLE
Slider value indicator gets disposed if it is activated

### LINKED ISSUE #55787: Slider Leaves Value Indicator In Overlay
## Steps to Reproduce

Whenever I show a [`Slider`](https://api.flutter.dev/flutter/material/Slider-class.html) in a [`ModalRoute`](https://api.flutter.dev/flutter/widgets/ModalRoute-class.html) and the user dismisses that modal while the slider is showing its value indicator, the value indicator is "left behind", i.e. the indicator overlay stays on the screen, indefinitely.  
This is very **ugly** and *confusing*.

**Expected results:** slider should completely disappear when the modal is closed.

**Actual results:** the value indicator stays visible indefinitely at the top of the screen.

### Note

The **label** indicator needs to be visible while the modal is being closed, i.e. to reproduce: have a slider with a `label` and change its value by tapping, then immediately close the modal..

This happens with both **v1** *and* **v2** sliders.

```
Flutter v1.18.0-9.0
// master versions since the v2 slider was introduced
```

### LINKED ISSUE #56628: sdkmanager.bat and gradlew.bat are deleted by antivirus on windows
I am trying to install flutter without using Android Studio. I am following [this article](https://medium.com/@quicky316/install-flutter-sdk-on-windows-without-android-studio-102fdf567ce4) for reference.  

1. I installed the flutter SDK from official site. 
2. Then I installed OpenJDK which was facing some issues. So using some advice from a facebook group, I installed from [this site](https://adoptopenjdk.net/).
3. I installed the android SDK from official site. That also faced issues. So using some stackoverflow answer, I downloaded a previous version of SDK .  
4. Everything worked fine till now. I set all the environment variables. I set the path. I run sdkmanager --list. It worked correctly
5. Then I ran ```sdkmanager “system-images;android-27;default;x86_64”``` . It gave me error that "repositories.cfg" not found. I resolved this error by creating this file in desired location
6. Then another error came that "unable to find package system-image" . I found no answer on Internet addressing it. I was trying to resolve this and opened the sdkmanager.bat file and it disappeared from my folder. Now I am again extracting the tools folder but everytime I run sdkmanager, the file disappears. What to do?

### PR DESCRIPTION
**Pull request by JoseAlba**
## Description

Slider value indicator gets disposed even if the value indicator is active. Currently if the Slider gets removed while it is activated than the value indicator remains on the Overlay.

## Related Issues

Closes https://github.com/flutter/flutter/issues/55787

## Tests

I added the following tests:

`flutter/packages/flutter/test/material/slider_test.dart`

test using context 'Slider removes value indicator from overlay if Slider gets disposed without value indicator animation completing.'

`flutter/packages/flutter/test/material/range_slider_test.dart`

test using context 'Range Slider removes value indicator from overlay if Slider gets disposed without value indicator animation completing.'

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by JoseAlba** [comment]
Testing https://dartpad.dev/359b76a8e06676e838ebb9f255e1f64a

File: packages/flutter/lib/src/material/range_slider.dart [hunk 1]
```diff
@@ -472,6 +472,12 @@ class _RangeSliderState extends State<RangeSlider> with TickerProviderStateMixin
     enableController.dispose();
     startPositionController.dispose();
     endPositionController.dispose();
+    if (overlayEntry != null) {
+      overlayEntry.remove();
+      overlayEntry = null;
+    }
+//    print((overlayEntry == null) ? 'overlay entry is null' : 'overlay entry is not null');
```
Comment (rami-a) [inline packages/flutter/lib/src/material/range_slider.dart:479]: Remove print

File: packages/flutter/lib/src/material/slider.dart [hunk 2]
```diff
@@ -507,6 +507,10 @@ class _SliderState extends State<Slider> with TickerProviderStateMixin {
 
   @override
   void dispose() {
+    if (overlayEntry != null) {
```
Comment (rami-a) [inline packages/flutter/lib/src/material/slider.dart:510]: In range slider, you do this logic at the end of the dispose method, I'm not sure if the order is important but either way it should be consistent between both.

File: packages/flutter/test/material/range_slider_test.dart [hunk 3]
```diff
@@ -1338,6 +1338,98 @@ void main() {
...
 
+  testWidgets('Range Slider removes value indicator from overlay if Slider gets disposed without value indicator animation completing.', (WidgetTester tester) async {
+    final ThemeData theme = _buildTheme();
+    final SliderThemeData sliderTheme = theme.sliderTheme;
+    RangeValues values = const RangeValues(0.5, 0.75);
+
+    Widget buildApp({
+      Color activeColor,
+      Color inactiveColor,
+      int divisions,
```
Comment (rami-a) [inline packages/flutter/test/material/range_slider_test.dart:1349]: Looks like divisions isn't used, and is hardcoded to 3 below, was that intentional?

File: packages/flutter/test/material/slider_test.dart [hunk 4]
```diff
@@ -1949,6 +1949,94 @@ void main() {
...
 
+  testWidgets('Slider removes value indicator from overlay if Slider gets disposed without value indicator animation completing.', (WidgetTester tester) async {
+    final Key sliderKey = UniqueKey();
+    double value = 0.0;
+
+
+    Widget buildApp({
+      Color activeColor,
+      Color inactiveColor,
+      int divisions,
```
Comment (rami-a) [inline packages/flutter/test/material/slider_test.dart:1960]: Looks like divisions isn't used, and is hardcoded to 10 below, was that intentional?

File: packages/flutter/test/material/slider_test.dart [hunk 5]
```diff
@@ -1949,6 +1949,94 @@ void main() {
...
+    final TestGesture gesture = await tester.startGesture(topRight);
+    // Wait for value indicator animation to finish.
+    await tester.pumpAndSettle();
+
+    expect(find.byType(Slider), isNotNull);
+    expect(
+      valueIndicatorBox,
+      paints
+        ..rrect(color: const Color(0xff2196f3)) // active track
+        ..rrect(color: const Color(0x3d2196f3)), // inactive
```
Comment (rami-a) [inline packages/flutter/test/material/slider_test.dart:2019]:
```suggestion
        ..rrect(color: const Color(0xff2196f3)) // Active track.
        ..rrect(color: const Color(0x3d2196f3)), // Inactive track.
```

File: packages/flutter/test/material/slider_test.dart [hunk 6]
```diff
@@ -1949,6 +1949,94 @@ void main() {
...
+    await tester.pumpAndSettle();
+
+    expect(find.byType(Slider), findsNothing);
+    expect(
+      valueIndicatorBox,
+      isNot(
+          paints
+            ..rrect(color: const Color(0xff2196f3)) // active track
+            ..rrect(color: const Color(0x3d2196f3))
+      ), //inactive
```
Comment (rami-a) [inline packages/flutter/test/material/slider_test.dart:2032]:
```suggestion
            ..rrect(color: const Color(0xff2196f3)) // Active track.
            ..rrect(color: const Color(0x3d2196f3)) // Inactive track.
      ),
```

**Review by rami-a — APPROVED** [review]

File: packages/flutter/lib/src/material/range_slider.dart (hunk 1 above)
Comment (JoseAlba) [reply packages/flutter/lib/src/material/range_slider.dart:479]: Done

File: packages/flutter/lib/src/material/slider.dart (hunk 2 above)
Comment (JoseAlba) [reply packages/flutter/lib/src/material/slider.dart:510]: Done

File: packages/flutter/test/material/range_slider_test.dart (hunk 3 above)
Comment (JoseAlba) [reply packages/flutter/test/material/range_slider_test.dart:1349]: Done

File: packages/flutter/test/material/slider_test.dart (hunk 4 above)
Comment (JoseAlba) [reply packages/flutter/test/material/slider_test.dart:1960]: It wasn't intentional a lot of the method use buildApp in the slider and range slider test. To keep it consistent I also used the similar format. I used the divisions variable but it doesn't change anything

File: packages/flutter/test/material/slider_test.dart (hunk 5 above)
Comment (JoseAlba) [reply packages/flutter/test/material/slider_test.dart:2019]: Done

File: packages/flutter/test/material/slider_test.dart (hunk 6 above)
Comment (JoseAlba) [reply packages/flutter/test/material/slider_test.dart:2032]: Done

File: packages/flutter/lib/src/material/slider_theme.dart [hunk 7]
```diff
@@ -2791,6 +2791,12 @@ class _RectangularSliderValueIndicatorPathPainter {
     double scale,
   }) {
     assert(!sizeWithOverflow.isEmpty);
+    /// If parentBox is null this means that the Slider was removed without
+    /// disposing value indicator.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/slider_theme.dart:2795]: We're not checking to see if parentBox is null here.  More importantly, I assume we're failing to do some work in _RenderSlider.detach: when the Slider is detached, we should be removing the value indicator's overlay entry. In other words, we shouldn't end up here if the slider is detached.

Comment (JoseAlba) [reply packages/flutter/lib/src/material/slider_theme.dart]: I tried removing the value indicator from the slider detach method but that wouldn't work because it would still appear as attached by the time it got to this part of the code. 

It was similar to the lag issue we were having with the overlay and so was the solution. Instead of checking if the parentbox is attached I am checking from the paint methods with an overlay. 

This is easier to understand through the commit changes.

https://github.com/flutter/flutter/pull/57535/commits/6b4636afcdc7f8851786e3dabd9d8e141dc9c885

File: packages/flutter/test/material/range_slider_test.dart [hunk 8]
```diff
@@ -1338,6 +1338,98 @@ void main() {
...
+              });
+            }),
+          ),
+        ),
+      );
+    }
+
+    await tester.pumpWidget(buildApp(divisions: 3));
+
+    final RenderBox valueIndicatorBox = tester.firstRenderObject(find.byType(Overlay));
```
Comment (HansMuller) [inline packages/flutter/test/material/range_slider_test.dart:1399]: If this really needs to be `firstRenderObject` please add a comment explaining why. It seems like `renderObject` would be sufficient.

Here and below.

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/test/material/range_slider_test.dart (hunk 8 above)
Comment (JoseAlba) [reply packages/flutter/test/material/range_slider_test.dart:1399]: The value indicator is added to the overlay when it is clicked or dragged because both of these gestures are occurring then it adds same value indicator twice into the overlay.
