### PR TITLE
DraggableScrollableSheet & NestedScrollView  should respect NeverScrollableScrollPhysics

### LINKED ISSUE #113753: NestedScrollView physics not working
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Just scroll the view

**Expected results:** 
Scroll should not work in this example

**Actual results:** 
User can scroll. We lost the ability to have custom physics like Clamping or Bouncing.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: Home()));
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: NestedScrollView(
        physics: const NeverScrollableScrollPhysics(),
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) => <Widget>[
          SliverOverlapAbsorber(
            handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
            sliver: const SliverAppBar(
              pinned: true,
              elevation: 0,
              backgroundColor: Colors.blue,
              toolbarHeight: kToolbarHeight,
              expandedHeight: 200,
              flexibleSpace: FlexibleSpaceBar(
                title: Text("Physics not working"),
              ),
            ),
          ),
        ],
        body: Builder(
          builder: (BuildContext context) => CustomScrollView(
            physics: const NeverScrollableScrollPhysics(),
            slivers: <Widget>[
              SliverOverlapInjector(
                handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
              ),
              SliverList(
                delegate: SliverChildBuilderDelegate(
                  (context, index) => Card(
                    child: ListTile(
                      leading: const Icon(Icons.search),
                      title: Text(index.toString()),
                    ),
                  ),
                  childCount: 200,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale fr-FR)
    • Flutter version 3.3.4 on channel stable at /Users/earminjon/fvm/versions/3.3.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/earminjon/Library/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/earminjon/Library/Android/Sdk
    • Java binary at: /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/earminjon/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 70.2.5
    • Dart plugin version 222.4345.14

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/earminjon/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

### LINKED ISSUE #121021: NeverScrollableScrollPhysics doesn't work for Scrollable inside DraggableScrollableSheet in 3.7.3
### **For Android:** 
1. Execute `flutter run` on the code sample 
2.  Try to scroll the list.
3. On 3.3.10 it will not scroll, on 3.7.3 it will scroll.

**Expected results:** 
Expected it to not be movable by scrolling gestures as in previous version of Flutter.

**Actual results:** 
It actually scrolls, which may broke UI/UX in certain cases (when the app expects the sheet to be scrolled via controller).

### **For Web** 
Seems like on web it works correctly.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Stack(
          children: [
            DraggableScrollableSheet(
              maxChildSize: 1,
              builder: (context, scrollController) => SingleChildScrollView(
                physics: const NeverScrollableScrollPhysics(),
                controller: scrollController,
                child: Column(
                  children: List.generate(
                    200,
                        (index) => Text(index.toString()),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.4 21F79 darwin-x64, locale en-IL)
    • Flutter version 3.7.3 on channel stable at /Users/andrey/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (9 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/andrey/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/andrey/Library/Java/JavaVirtualMachines/corretto-11.0.17/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-11.0.17.8.1 (build 11.0.17+8-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes https://github.com/flutter/flutter/issues/121021
Fixes https://github.com/flutter/flutter/issues/113753

#121021 was introduce by https://github.com/flutter/flutter/pull/109081

Adding a `ScrollPhysics.allowUserScrolling` to indicate whether the physics allowed the user scrolling.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scroll_physics.dart [hunk 1]
```diff
@@ -969,4 +972,7 @@ class NeverScrollableScrollPhysics extends ScrollPhysics {
 
   @override
   bool get allowImplicitScrolling => false;
+
+  @override
+  bool get allowUserScrolling => false;
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_physics.dart:977]: Doesn't `shouldAcceptUserOffset` above provide the same thing?

Comment (Piinks) [reply packages/flutter/lib/src/widgets/scroll_physics.dart:977]: Hm, the default implementation of shouldAcceptUserOffset might not work as this is intended. However, I think if adding this allowUserScrolling is the right way to resolve this, it should work with shouldAcceptUserOffset, or at least document what the difference between them is. Should shouldAcceptUserOffset also consider allowUserScrolling?

**Review by Piinks — COMMENTED** [review]
I don't know that this is the right approach, I actually wonder if the original fix for https://github.com/flutter/flutter/issues/98314 was not the right solution. Applying AlwaysScrollableScrollPhysics may have other side effects like we are seeing here with NeverScrollableScrollPhysics.
I am not sure what the right change is, but I'd like to see if we can revisit the original issue and check to see if there is a better solution there first. What do you think @xu-baolin?

File: packages/flutter/lib/src/widgets/scroll_physics.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/scroll_physics.dart]: @Piinks Nice point! Let us review the original issue again : )
1, The framework warp a gesture recognizer only if `physics.shouldAcceptUserOffset(this)` returns true.
https://github.com/flutter/flutter/blob/f266cccdeadb9a5fe7ceed0c4d98a68cf6f27879/packages/flutter/lib/src/widgets/scrollable.dart#L645-L649
So, If the DSS's extent becomes large enough, the scrollable will become unscrollable and the gesture will be removed (The extent's size is actually the scrollable viewport). Then the DSS is stuck and cannot be pulled back. This is the #31739 root cause.

2, Here is `_DraggableScrollableSheetScrollPosition.applyUserOffset` 's implement
https://github.com/flutter/flutter/blob/f266cccdeadb9a5fe7ceed0c4d98a68cf6f27879/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L877-L882

It set the extent's size by the user scrolling. So, if we want fix the original issue we must let the scrollable always scrollable, right?

Regardless of whether #31832 or #109081, they essentially make the scrollable to be always scrollable, but #31832 is a bit hack and introduces issue #98314. 

Unfortunately, #109081 introduces issue #121021 because it ignores the ‘NeverScrollableScrollPhysics’ case. This is why I make this change to introduce a method to distinguish the `NeverScrollableScrollPhysics` and others.

In addition, I tried other solutions at the same time, such as caching the old physics, and then applying it to the user scrolling, but I gave up for it is a bit complicated.

Glad to here your thoughts : )

Comment (Piinks) [reply packages/flutter/lib/src/widgets/scroll_physics.dart]: Ah thank you for this! I really appreciate the context. I came across https://github.com/flutter/flutter/issues/113753 which is a similar-ish case of the explicit physics being overridden by a widget applying other physics.  

This makes me think, what do you think about some way for users to specify that physics should not be meddled with? And then maybe in `applyTo` we check that? I dunno, just brainstorming..
However, this is slightly different from #113753 in that in the nested scroll view, we see  userSuppliedPhysics.applyTo(extraImplementationPhysics), while here we see extraImplementationPhysics.applyTo(userSuppliedPhysics).. so this idea may not actually work...

Since it appears there is a pattern where the user may not want us to to change the scroll physics (I am sure there are other places where we do this, overriding the value explicitly set by the user), what are you thoughts on approaching this in a way that lets users preserve their preferred scroll physics? (not exclusive to just NeverScrollable and `allowUserScrolling`)

File: packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart [hunk 2]
```diff
@@ -781,7 +781,7 @@ class _DraggableScrollableSheetScrollController extends ScrollController {
     ScrollPosition? oldPosition,
   ) {
     return _DraggableScrollableSheetScrollPosition(
-      physics: const AlwaysScrollableScrollPhysics().applyTo(physics),
+      physics: physics.applyTo(const AlwaysScrollableScrollPhysics()),
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart:784]: `userSuppliedPhysics.applyTo(extraImplementationPhysics)` can fix DDS's issue simply : )

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart [hunk 3]
```diff
@@ -1439,7 +1439,8 @@ class _NestedScrollPosition extends ScrollPosition implements ScrollActivityDele
   }
 
   void updateCanDrag(double totalExtent) {
-    context.setCanDrag(totalExtent > (viewportDimension - maxScrollExtent) || minScrollExtent != maxScrollExtent);
+    context.setCanDrag(physics.allowUserScrolling &&
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/nested_scroll_view.dart:1442]: Fixes #113753

Here seems to be more suitable use `physics.allowUserScrolling`

File: packages/flutter/lib/src/widgets/scroll_physics.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/scroll_physics.dart]: `Ah thank you for this! I really appreciate the context. I came across https://github.com/flutter/flutter/issues/113753 which is a similar-ish case of the explicit physics being overridden by a widget applying other physics.`

It seems like physics overridden is not the root cause of that issue but this patch may help to fix that : )

`This makes me think, what do you think about some way for users to specify that physics should not be meddled with?`

Good idea but I'm concerned that doing this would be a breaking change?

File: packages/flutter/lib/src/widgets/nested_scroll_view.dart (hunk 3 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/nested_scroll_view.dart:1442]: Ah yes, thank you!

File: packages/flutter/lib/src/widgets/scroll_physics.dart [hunk 4]
```diff
@@ -197,7 +197,8 @@ class ScrollPhysics {
   }
 
   /// Whether the scrollable should let the user adjust the scroll offset, for
-  /// example by dragging.
+  /// example by dragging. If [allowUserScrolling] is false, the scrollable
+  /// will never allow the user scrolling.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_physics.dart:201]:
```suggestion
  /// will never allow the user input to change the scroll position.
```

File: packages/flutter/lib/src/widgets/scroll_physics.dart [hunk 5]
```diff
@@ -487,6 +492,9 @@ class ScrollPhysics {
   /// scroll position to fulfill such a request.
   bool get allowImplicitScrolling => true;
 
+  /// Whether a viewport is allowed the user scrolling.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scroll_physics.dart:495]:
```suggestion
  /// Whether a viewport is allowed to change the scroll position as the result of user input.
```

**Review by Piinks — APPROVED** [review]
Thanks for your patience on this one. I really appreciate you taking a look at that other issue and including a full fix! LGTM!

**Comment by aqrc** [comment]
Thank you very much for fixing that! Could you please estimate when this fix is going to be officially released?

**Comment by iampato** [comment]
I have flutter version 3.22.3 and this doesn't work for me
@Piinks  what this ever released? if so what version has it

**Comment by iampato** [comment]
Something that works:
```dart
NestedScrollView(
   scrollBehavior: const MaterialScrollBehavior().copyWith(
        physics: const NeverScrollableScrollPhysics(),
        dragDevices: {}, // no drag devices
   )
...
```
