### PR TITLE
Retry Xcode builds if they fail due to concurrent builds running

### LINKED ISSUE #40576: Concurrent builds of same Flutter project for two iOS devices fail
With #40171, it's possible to run two instances of `flutter run` from the same directory at the same time to run on two devices. However if you try this with two iOS Simulators, one of the builds fails with:

> /Developer/Xcode/DerivedData/Runner-cqvvjujagpbkjpcfmgxfzeqtjdep/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.

Handling the error better would be nice, but actually supporting this would be even nicer (even if just waiting for one build to complete then doing the other). It'd be nice to run on an iOS and iPad simulator concurrently while working on different layouts for screen sizes to ensure tweaking one doesn't break the other.

FYI @jonahwilliams

### PR DESCRIPTION
**Pull request by DanTup**
Fixes #40576.

## Description

Running `flutter run` concurrently in the same folder currently fails for an iOS device if there's another one in-progress due them both using the same derived data directory and Xcode outputting:

> /Developer/Xcode/DerivedData/Runner-cqvvjujagpbkjpcfmgxfzeqtjdep/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.

This change detects this type of error and will retry it a few times (increasing the delay between retries) rather than just failing.

Screenshot 2019-11-26 at 12 13 53 pm

## Related Issues

- https://github.com/flutter/flutter/issues/40576

## Tests

I added the following tests:

- TODO

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by DanTup** [comment]
@jonahwilliams added a test for this, but the only place I could see that was testing this code was the device test that tries to build and launch the app. I've added it in there, but because there was so much setup code to make it work, I built it into the existing `nonPreBuilt` test function. Not sure this is the best way though, so happy to change this if you'd prefer it done differently.

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 1]
```diff
@@ -572,6 +570,49 @@ Future<XcodeBuildResult> buildXcodeProject({
   }
 }
 
+Future<RunResult> _runBuildWithRetries(List<String> buildCommands, BuildableIOSApp app) async {
+  int buildRetryDelaySeconds = 1;
+  int remainingTries = 5;
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/ios/mac.dart]: I would give it 2 or 3 more tries, to cover the case where it needs to wait the entire duration of an existing xcode build.

**Comment by jonahwilliams** [comment]
FYI @jmagman

**Comment by jmagman** [comment]
> FYI @jmagman

This approach makes sense to me!

**Review by jonahwilliams — APPROVED** [review]
LGTM with nit
