### PR TITLE
Removed "if" on resolving text color at "SnackBarAction"

### LINKED ISSUE #120047: Material 3 snackBar action label textColor not working
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Click "Show SnackBar"

**Expected results:** 
Color of snackBarAction label is red
**Actual results:** 
Color of snackBarAction label is violet

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final snackBar = SnackBar(
      content: const Text('test',
          style: TextStyle(
            color: Colors.red,
          )),
      duration: const Duration(seconds: 10),
      action: SnackBarAction(
        label: 'action',
        onPressed: () {},
        textColor: Colors.red,
      ),
    );
    return Scaffold(
      body: Center(
        child: TextButton(
            onPressed: () =>
                ScaffoldMessenger.of(context).showSnackBar(snackBar),
            child: const Text('Show SnackBar')),
      ),
    );
  }
}

```

</details>

```
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.0.1 22A400 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.75.0)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by MarchMore**
Removed multiple "if" for "resolveForegroundColor" method at "SnackBarAction". At least one of the multiple "if" ("defaults.actionTextColor is MaterialStateColor") led to not applying a custom set color (e.g. MaterialColor "Colors.red") for the action text when using Material 3.

The second "if" ("snackBarTheme.actionTextColor is MaterialStateColor") also makes no sense then as the set color of the Theme would lead to the same blocking behaviour of manual color assignment.

The last remaining "if" ("widget.textColor is MaterialStateColor") will be unnecessary if the other "if" will be removed, as it will be resolved in the code right afterwards.

The three "if" also seems to block the usage of the custom text color or the color at all if the widget is in the "MaterialState.disabled" state.

This PR resolves following issue:
* Fixes https://github.com/flutter/flutter/issues/120047

### CODE REVIEW

**Comment by esouthren** [comment]
Hi folks - thanks to @bashor4life for discovering the issue and @MarchMore for taking it on. 

There's certainly a bug here in the current implementation; the issue in the example is being caused, as you discovered, by the following chain of events:
- User sets an `action.textColor` value (e.g: `Colors.red`)
- `resolveForegroundColor()` checks if `widget.textColor` is a `MaterialStateColor`; it isn't, so we continue
- `resolveForegroundColor()` checks if `snackBarTheme.actionTextColor` is a `MaterialStateColor`; in Material 3 defaults it is, so the function returns here and resolves the color as Material 3 defaults - purple, in this case.

Your solution fixes the issue for `action.textColor` as a `Color` value, but prevents folks from setting it to a `MaterialStateColor` value. You can test this by setting `action.textColor` to the `MyColor()` example in [the bug](https://github.com/flutter/flutter/issues/120047#issuecomment-1418888668).

I think a full solution will involve some more conditions in `resolveForegroundColor()`; perhaps checking if *any* value has been set for `textColor`, resolving it as either a `Color` or `MaterialStateColor`, then doing the same for `snackBarTheme.actionTextColor` and `defaults.actionTextColor`.

If you'd like to continue working on this, I'm more than happy to comment/review. I can also take on the bug if you would prefer to pass it on. Thanks again!

**Comment by MarchMore** [comment]
Hi @esouthren, thanks for your information - I've updated my PR!

Now the three color properties are checked in the correct order.
If one of them is set, it will be taken (if it is a MaterialStateColor). If it is not a MaterialStateColor, the standard resolution is done (and so the property with the higher priority is taken anyways).

This fixes the issue that the "default color" wins if the other 2 properties are not from type "MaterialStateColor".
The changes also enables the advatages of potential "MaterialStateColor" colors if set.

File: packages/flutter/lib/src/material/snack_bar.dart [hunk 1]
```diff
@@ -140,15 +140,20 @@ class _SnackBarActionState extends State<SnackBarAction> {
...
     MaterialStateColor resolveForegroundColor() {
-      if (widget.textColor is MaterialStateColor) {
-        return widget.textColor! as MaterialStateColor;
-      }
-      if (snackBarTheme.actionTextColor is MaterialStateColor) {
-        return snackBarTheme.actionTextColor! as MaterialStateColor;
-      }
-      if (defaults.actionTextColor is MaterialStateColor) {
-        return defaults.actionTextColor! as MaterialStateColor;
+      if (widget.textColor != null) {
```
Comment (esouthren) [inline packages/flutter/lib/src/material/snack_bar.dart:143]: Great stuff; I think this is the logic we want. 

Can we add a unit test for this, in `snack_bar_test.dart`?

File: packages/flutter/lib/src/material/snack_bar.dart [hunk 2]
```diff
@@ -242,10 +247,10 @@ class SnackBar extends StatefulWidget {
     this.dismissDirection = DismissDirection.down,
     this.clipBehavior = Clip.hardEdge,
   }) : assert(elevation == null || elevation >= 0.0),
-       assert(
-         width == null || margin == null,
-         'Width and margin can not be used together',
-       );
+        assert(
```
Comment (esouthren) [inline packages/flutter/lib/src/material/snack_bar.dart:250]: You'll need to revert the autoformatting changes, here and below. 

See the 'Tip' info at https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment#set-up-your-environment - the code in the framework needs to have it turned off.

**Review by esouthren — CHANGES_REQUESTED** [review]
Thanks for the updates!

File: packages/flutter/lib/src/material/snack_bar.dart (hunk 1 above)
Comment (MarchMore) [reply packages/flutter/lib/src/material/snack_bar.dart:143]: I've added two tests. Sadly I'm not sure how to implement the case with `null` - Therefore I need the default color.
But I hope this sufficient and helpful enough.

File: packages/flutter/lib/src/material/snack_bar.dart (hunk 2 above)
Comment (MarchMore) [reply packages/flutter/lib/src/material/snack_bar.dart]: Resolved

File: packages/flutter/test/material/snack_bar_test.dart [hunk 3]
```diff
@@ -856,6 +856,110 @@ void main() {
     }
   });
 
+  testWidgets('Snackbar labels can be colored (M3 / MaterialColor)',
```
Comment (esouthren) [inline packages/flutter/test/material/snack_bar_test.dart:859]: Can we rename this to 'Snackbar labels can be coloured as Color (Material 3)' 

Same for the other test, with MaterialStateColor.

File: packages/flutter/lib/src/material/snack_bar.dart (hunk 1 above)
Comment (esouthren) [reply packages/flutter/lib/src/material/snack_bar.dart:143]: This is fine - I think the `null` case is covered sufficiently by other tests.

**Review by esouthren — APPROVED** [review]
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
  ```
                        
Great work, thank you for your assistance.

**Comment by s4nk37** [comment]
The issue is still there in  Flutter (Channel stable, 3.7.7). It is by default taking value of inversePrimary from colorScheme, and not getting overridden by either actionTextColor in Theme or textColor in the SnackBarAction widget itself.

**Comment by s4nk37** [comment]
> The issue is still there in Flutter (Channel stable, 3.7.7). It is by default taking value of inversePrimary from colorScheme, and not getting overridden by either actionTextColor in Theme or textColor in the SnackBarAction widget itself.

**Comment by s4nk37** [comment]
Giving value of color like this in both theme and widget worked.

textColor: MaterialStateColor.resolveWith((states) => Colors.red),
