### PR TITLE
Add command key bindings to macOS text editing and fix selection.

### LINKED ISSUE #36316: Support multi-line text editing on desktop platforms
We need to implement full support for multi-line text editing, including:
 - [ ] cut/copy/paste/clear shortcuts and actions
 - [ ] selection via mouse
 - [ ] selection via keyboard (shift-up-arrow, etc.)
 - [ ] navigation via mouse and keyboard (jump to beginning/end, move with arrow keys, set insertion point with mouse)
 - [ ] optionally, commit text with enter key (and add newline with shift-enter).

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This adds support for the command key for text selection/editing on macOS. I had ported the text editing code (in https://github.com/flutter/flutter/pull/42879), but forgot to add support for the command key itself.  This also adds a test that tests the text editing on multiple platforms instead of just testing Android.

There appears to still be a bug (filed https://github.com/flutter/flutter/issues/44135) where we're losing key events sometimes on macOS, leaving some keys "stuck" on, but this PR at least allows the right key combinations to be used.

## Related Issues

Addresses https://github.com/flutter/flutter/issues/30709
Fixes https://github.com/flutter/flutter/issues/36316

## Tests

- Added tests for multiple platforms to make sure that editing works there.

## Breaking Change

- [X] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -402,8 +402,14 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
     LogicalKeyboardKey.control,
   };
 
+  static final Set<LogicalKeyboardKey> _macOsModifierKeys = <LogicalKeyboardKey>{
+    LogicalKeyboardKey.shift,
+    LogicalKeyboardKey.meta,
```
Comment (franciscojma86) [inline packages/flutter/lib/src/rendering/editable.dart]: Should Alt be here as well? Alt+arrow skips word by word

Comment (franciscojma86) [inline packages/flutter/lib/src/rendering/editable.dart]: Should Alt be here too? Alt + arrow skips word by word

File: packages/flutter/lib/src/rendering/editable.dart [hunk 2]
```diff
@@ -440,44 +451,100 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
-      // If control is pressed, we will decide which way to look for a word
-      // based on which arrow is pressed.
-      if (leftArrow && newSelection.extentOffset > 2) {
-        final TextSelection textSelection = _selectWordAtOffset(TextPosition(offset: newSelection.extentOffset - 2));
-        newSelection = newSelection.copyWith(extentOffset: textSelection.baseOffset + 1);
-      } else if (rightArrow && newSelection.extentOffset < text.toPlainText().length - 2) {
-        final TextSelection textSelection = _selectWordAtOffset(TextPosition(offset: newSelection.extentOffset + 1));
-        newSelection = newSelection.copyWith(extentOffset: textSelection.extentOffset - 1);
+    // Returns true if [c] represents a whitespace code unit.
+    bool isWhitespace(int c) => (c <= 0x000D && c >= 0x0009) || c == 0x0020;
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/rendering/editable.dart]: I think we already have some white space checking code somewhere in flutter, it would be good to keep that in sync: https://github.com/flutter/flutter/blob/9307a83f7cdfadfaf017635b01b81b5d5e0ae46e/packages/flutter/lib/src/rendering/editable.dart#L1130

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 3]
```diff
@@ -3017,316 +3071,516 @@ void main() {
...
+      platform: platform,
     );
 
-    expect(cause, equals(SelectionChangedCause.keyboard));
-    expect(selection, equals(const TextSelection(
-      baseOffset: 0,
-      extentOffset: 3,
-      affinity: TextAffinity.upstream,
-    )));
+    expect(cause, equals(SelectionChangedCause.keyboard), reason: 'on $platform');
```
Comment (jonahwilliams) [inline packages/flutter/test/widgets/editable_text_test.dart]: nit: equals doesn't really add anything here, unless you were going to nest matchers

Comment (gspencergoog) [reply packages/flutter/test/widgets/editable_text_test.dart]: Oh, I know that, I just put it in because it reads better.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 4]
```diff
@@ -440,44 +451,100 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
-    if (rightArrow && newSelection.extentOffset < text.toPlainText().length) {
-      newSelection = newSelection.copyWith(extentOffset: newSelection.extentOffset + 1);
-      if (shift) {
-        _cursorResetLocation += 1;
+
+    int nextNonWhitespace(int extent) {
+      final String plain = text.toPlainText();
+      int result = math.min(extent + 1, plain.length);
+      while (result < plain.length && isWhitespace(plain.codeUnitAt(result))) {
+        result++;
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/rendering/editable.dart]: nit: use += 1, https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#prefer-over

File: packages/flutter/lib/src/rendering/editable.dart [hunk 5]
```diff
@@ -440,44 +451,100 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
-        newSelection = newSelection.copyWith(extentOffset: textSelection.extentOffset - 1);
+    // Returns true if [c] represents a whitespace code unit.
+    bool isWhitespace(int c) => (c <= 0x000D && c >= 0x0009) || c == 0x0020;
+
+    // Find the previous non-whitespace character
+    int previousNonWhitespace(int extent) {
+      int result = math.max(extent - 1, 0);
+      final String plain = text.toPlainText();
+      while (result > 0 && isWhitespace(plain.codeUnitAt(result))) {
+        result--;
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/rendering/editable.dart]: nit: use `-= 1`

https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#prefer-over

File: packages/flutter/lib/src/rendering/editable.dart [hunk 6]
```diff
@@ -440,44 +451,100 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
     }
-    // Set the new offset to be +/- 1 depending on which arrow is pressed
-    // If shift is down, we also want to update the previous cursor location
-    if (rightArrow && newSelection.extentOffset < text.toPlainText().length) {
-      newSelection = newSelection.copyWith(extentOffset: newSelection.extentOffset + 1);
-      if (shift) {
-        _cursorResetLocation += 1;
+
+    int nextNonWhitespace(int extent) {
+      final String plain = text.toPlainText();
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/rendering/editable.dart]: Seems like this code would result in use computing plain text every time a key is pressed, which it should be cache-able as long as the TextPainter doesn't update. I'm not sure how large the performance impact would be, but it might be an easy win

File: packages/flutter/lib/src/rendering/editable.dart [hunk 7]
```diff
@@ -440,44 +451,100 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin {
...
+        newSelection = newSelection.copyWith(extentOffset: textSelection.extentOffset);
+      }
+    } else {
+      if (rightArrow && newSelection.extentOffset < text.toPlainText().length) {
+        newSelection = newSelection.copyWith(extentOffset: newSelection.extentOffset + 1);
+        if (shift) {
+          _cursorResetLocation += 1;
+        }
+      }
+      if (leftArrow && newSelection.extentOffset > 0) {
```
Comment (jonahwilliams) [inline packages/flutter/lib/src/rendering/editable.dart]: are leftArrow and rightArrow mutually exclusive?

File: packages/flutter/lib/src/rendering/editable.dart (hunk 2 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/rendering/editable.dart]: Good idea.  Done.  Oddly, I did search for one, but I didn't find that one in the same file!

**Review by jonahwilliams — COMMENTED** [review]
I took a quick pass through this one. Generally looks good, but I'm a bit concerned about performance on larger buffers

**Review by jonahwilliams — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/rendering/editable.dart (hunk 6 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/rendering/editable.dart]: I added `_plainText` that lazily evaluates and caches the plain text version of the text.  It didn't add too much complexity (actually seems easier to read to me), and can only result in a win performance-wise. The only danger is that the `TextPainter` updates its `text` member somehow without telling the `RenderEditable`, but I don't think that's possible, since the `RenderEditable` owns the painter and doesn't expose it.
