### PR TITLE
Make Tooltip recover gracefully when context is destroyed.

### LINKED ISSUE #1518: Tooltip error in flame chart
To reproduce, select node and move mouse off of selected node before tooltip shows
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'findRenderObject' was called on null.
Receiver: null
Tried calling: findRenderObject()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _TooltipState._createNewEntry (package:flutter/src/material/tooltip.dart:283:35)
#2      _TooltipState.ensureTooltipVisible (package:flutter/src/material/tooltip.dart:277:5)
#3      _rootRun (dart:async/zone.dart:1122:38)
#4      _CustomZone.run (dart:async/zone.dart:1023:19)
#5      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#7      _rootRun (dart:async/zone.dart:1126:13)
#8      _CustomZone.run (dart:async/zone.dart:1023:19)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

### LINKED ISSUE #54096: Tooltip does not recover gracefully when context is destroyed
The original issue filed was against Dart DevTools https://github.com/flutter/devtools/issues/1518, but I think this should be fixed in the Flutter framework.

Adding `if (context == null) return false;` before calling `_createNewEntry()` [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/tooltip.dart#L277) fixed the issue and ensured we did not try to create an entry for a destroyed context. But this may not be the best place to add the fix, so passing along to the Flutter team.

Screen Shot 2020-04-06 at 7 59 19 AM

The issue is that the Tooltip widget is destroyed before we create the entry and forward the controller, but there is no fail safe check to prevent `findRenderObject()` from being called on a null `context`.

### PR DESCRIPTION
**Pull request by kenzieschmoll**
fixes https://github.com/flutter/flutter/issues/54096
fixes https://github.com/flutter/devtools/issues/1518

The issue is that the Tooltip widget is destroyed before we create the entry and forward the controller, but there is no fail safe check to prevent `findRenderObject()` from being called on a null context. This ensures we do not call `_createNewEntry()` and try to create an entry for a destroyed context.

### CODE REVIEW

**Comment by goderbauer** [comment]
I am wondering: How/Why do you call `ensureTooltipVisible` on a Tooltip that's not in the tree in the first place?

Also: This will need a test.

**Comment by kenzieschmoll** [comment]
The case where I see this is when the widget is rebuilt before the tooltip appears. For example, an item that changes color on selection. Mouse over the widget -> tooltip starts waiting to appear -> select the widget before tooltip appears -> widget is rebuilt to change color -> tooltip error is thrown because context is null.

Do you have suggestions on how to test this? It seems like it would require destroying the context mid-test.

**Comment by goderbauer** [comment]
> Do you have suggestions on how to test this?

I would write a test that goes through the scenario you provided:

> Mouse over the widget -> tooltip starts waiting to appear -> select the widget before tooltip appears -> widget is rebuilt to change color -> tooltip error is thrown because context is null.

**Comment by goderbauer** [comment]
I am still not fully sure I understand why you're seeing the crash, though. When the State gets disposed (which causes context to go to null), we cancel the `_showTimer`, so `ensureVisible` shouldn't be called in that case. Is for some reason this timer not getting properly cancelled?

File: packages/flutter/lib/src/material/tooltip.dart [hunk 1]
```diff
@@ -274,6 +275,9 @@ class _TooltipState extends State<Tooltip> with SingleTickerProviderStateMixin {
       _controller.forward();
       return false; // Already visible.
     }
+    if (context == null) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/tooltip.dart:278]: you can use `if (mounted)` instead, but as I said in my other comment, I don't fully understand yet why this would be necessary here.

**Comment by devoncarew** [comment]
We do see this issue frequently in DevTools (more or less every time somebody mouses over an item with a tooltip). While minor, it's likely our most frequently encountered exception. I added `customer: ddt` to the associated issue.

File: packages/flutter/lib/src/material/tooltip.dart (hunk 1 above)
Comment (jacob314) [reply packages/flutter/lib/src/material/tooltip.dart:278]: actually the problem may be we are missing a 
`_showTimer.cancel()` elsewhere int his code when the unmount event occurs.

File: packages/flutter/lib/src/material/tooltip.dart [hunk 2]
```diff
@@ -265,7 +265,8 @@ class _TooltipState extends State<Tooltip> with SingleTickerProviderStateMixin {
 
   /// Shows the tooltip if it is not already visible.
   ///
-  /// Returns `false` when the tooltip was already visible.
+  /// Returns `false` when the tooltip was already visible or if the context has
```
Comment (jacob314) [inline packages/flutter/lib/src/material/tooltip.dart:268]: revert this comment change.

File: packages/flutter/lib/src/material/tooltip.dart [hunk 3]
```diff
@@ -336,6 +337,7 @@ class _TooltipState extends State<Tooltip> with SingleTickerProviderStateMixin {
     if (_entry != null) {
       _hideTooltip(immediately: true);
     }
+    _showTimer?.cancel();
```
Comment (jacob314) [inline packages/flutter/lib/src/material/tooltip.dart:340]: should we also cancel the hideTimer or is that also covered by _hideTooltip?

**Review by jacob314 — APPROVED** [review]
lgtm
