### PR TITLE
[flutter_tools] Fix _CastError in HotRunner._resetDirtyAssets

### LINKED ISSUE #108653: [flutter_tools] _CastError in HotRunner._resetDirtyAssets
on `beta/3.3.0-0.0.pre`

with command `flutter run --no-sound-null-safety`

```
_CastError: Null check operator used on a null value
at HotRunner._resetDirtyAssets(run_hot.dart:497)
at HotRunner._restartFromSources(run_hot.dart:565)
at <asynchronous gap>(async)
at HotRunner._fullRestartHelper(run_hot.dart:754)
at <asynchronous gap>(async)
at HotRunner.restart(run_hot.dart:694)
at <asynchronous gap>(async)
at TerminalHandler._commonTerminalInputHandler(resident_runner.dart:1699)
at <asynchronous gap>(async)
at TerminalHandler.processTerminalInput(resident_runner.dart:1739)
at <asynchronous gap>(async)
```

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/108653

### CODE REVIEW

File: packages/flutter_tools/lib/src/run_hot.dart [hunk 1]
```diff
@@ -498,8 +498,8 @@ class HotRunner extends ResidentRunner {
 
   void _resetDirtyAssets() {
     for (final FlutterDevice? device in flutterDevices) {
-      device!.devFS!.assetPathsToEvict.clear();
-      device.devFS!.shaderPathsToEvict.clear();
+      device!.devFS?.assetPathsToEvict.clear();
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/run_hot.dart:501]: Changing the `!` to a `?` here was the fix. I'm not sure why the devFS is null here.

**Comment by christopherfujino** [comment]
@jmagman sorry, this is a meaty PR, enabling null-safety on the test file I needed to make a lot of changes just to get it to compile (and then many more to get the tests to pass).

File: packages/flutter_tools/lib/src/run_hot.dart (hunk 1 above)
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/run_hot.dart:501]: devFS can be null if we hit this code path either before the device has been set up or after its been torn down. The latter seems more likely - perhaps if the user triggers a reload that stalls and then they exit? We hit this issue before and I was never able to repro, in that case something like the following would be more obvious for future readers.

```
final DevFS? devfs = device.devFS;
if (devfs == null) {
 // note about why this happens
  continue;
}
```

**Review by jonahwilliams — APPROVED** [review]
LGTM!

File: packages/flutter_tools/lib/src/run_hot.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/run_hot.dart:501]: SGTM, however I have no idea why it happens. Should I just link to the issue?

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/run_hot.dart:501]: Yeah, that is a reasonable approach. We need this null check to prevent a crash, but we don't know why exactly see issue# or somesuch

File: packages/flutter_tools/lib/src/base/dds.dart [hunk 2]
```diff
@@ -12,8 +12,9 @@ import 'context.dart';
 import 'io.dart' as io;
 import 'logger.dart';
 
+// TODO(fujino): This should be direct injected, rather than mutable global state.
 @visibleForTesting
-Future<dds.DartDevelopmentService> Function(
+Future<dds.DartDevelopmentService?> Function(
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/base/dds.dart:17]: Seems like a bug if this is ever null? In the tests you already have a `DartDevelopmentService` instantiated, can you just return that, or make a fake one?

File: packages/flutter_tools/lib/src/commands/daemon.dart [hunk 3]
```diff
@@ -736,7 +736,7 @@ class AppDomain extends Domain {
     if (app == null) {
       throw DaemonException("app '$appId' not found");
     }
-    final FlutterDevice device = app.runner!.flutterDevices.first!;
+    final FlutterDevice device = app.runner!.flutterDevices.first;
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/daemon.dart:739]: I can't comment on the right lines, but can you swap the `dynamic`s in this file for `Object` or `Object?`s?

File: packages/flutter_tools/lib/src/resident_runner.dart [hunk 4]
```diff
@@ -926,11 +926,11 @@ abstract class ResidentHandlers {
     final List<FlutterView> views = await flutterDevices
       .first!
       .vmService!.getFlutterViews();
-    final Map<String, Object> data = await (flutterDevices.first!.vmService!.getSkSLs(
+    final Map<String, Object?>? data = await flutterDevices.first!.vmService!.getSkSLs(
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/resident_runner.dart:929]: `await flutterDevices.first!.vmService!` is called on 2 lines in a row, make a local.

File: packages/flutter_tools/lib/src/run_hot.dart [hunk 5]
```diff
@@ -455,11 +455,11 @@ class HotRunner extends ResidentRunner {
...
     final Stopwatch findInvalidationTimer = _stopwatchFactory.createStopwatch('updateDevFS')..start();
     final InvalidationResult invalidationResult = await projectFileInvalidator.findInvalidated(
-      lastCompiled: flutterDevices[0]!.devFS!.lastCompiled,
-      urisToMonitor: flutterDevices[0]!.devFS!.sources,
+      lastCompiled: flutterDevices[0].devFS!.lastCompiled,
+      urisToMonitor: flutterDevices[0].devFS!.sources,
       packagesPath: packagesFilePath,
       asyncScanning: hotRunnerConfig!.asyncScanning,
-      packageConfig: flutterDevices[0]!.devFS!.lastPackageConfig
+      packageConfig: flutterDevices[0].devFS!.lastPackageConfig
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/run_hot.dart:462]:
```dart
    final DevFS devFS = flutterDevices[0].devFS!;
    final InvalidationResult invalidationResult = await projectFileInvalidator.findInvalidated(
      lastCompiled: devFS.lastCompiled,
      urisToMonitor: devFS.sources,
      packagesPath: packagesFilePath,
      asyncScanning: hotRunnerConfig!.asyncScanning,
      packageConfig: devFS.lastPackageConfig
```

File: packages/flutter_tools/lib/src/run_hot.dart [hunk 6]
```diff
@@ -474,7 +474,7 @@ class HotRunner extends ResidentRunner {
     }
     final UpdateFSReport results = UpdateFSReport(
       success: true,
-      scannedSourcesCount: flutterDevices[0]!.devFS!.sources.length,
+      scannedSourcesCount: flutterDevices[0].devFS!.sources.length,
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/run_hot.dart:477]:
```suggestion
      scannedSourcesCount: devFS.sources.length,
```

File: packages/flutter_tools/lib/src/run_hot.dart [hunk 7]
```diff
@@ -498,8 +498,14 @@ class HotRunner extends ResidentRunner {
 
   void _resetDirtyAssets() {
     for (final FlutterDevice? device in flutterDevices) {
-      device!.devFS!.assetPathsToEvict.clear();
-      device.devFS!.shaderPathsToEvict.clear();
+      final DevFS? devFS = device!.devFS;
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/run_hot.dart:501]: `flutterDevices` is `List<FlutterDevice>`, not `FlutterDevice?`
```dart
    for (final FlutterDevice device in flutterDevices) {
      final DevFS? devFS = device.devFS;
```

File: packages/flutter_tools/lib/src/isolated/resident_web_runner.dart [hunk 8]
```diff
@@ -81,7 +81,7 @@ const String kExitMessage = 'Failed to establish connection with the application
 
 class ResidentWebRunner extends ResidentRunner {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/isolated/resident_web_runner.dart:82]: You can get of a lot of `!` in this file if `_fileSystem` and `_logger` were correctly marked not nullable.
```dart
  final FileSystem _fileSystem;
  final Logger _logger;
```

File: packages/flutter_tools/lib/src/isolated/resident_web_runner.dart [hunk 9]
```diff
@@ -439,8 +439,8 @@ class ResidentWebRunner extends ResidentRunner {
       // Special handling for entrypoints that are not under lib, such as test scripts.
       if (importedEntrypoint == null) {
         final String parent = _fileSystem!.file(mainUri).parent.path;
-        flutterDevices.first!.generator!.addFileSystemRoot(parent);
-        flutterDevices.first!.generator!.addFileSystemRoot(_fileSystem!.directory('test').absolute.path);
+        flutterDevices.first.generator!.addFileSystemRoot(parent);
+        flutterDevices.first.generator!.addFileSystemRoot(_fileSystem!.directory('test').absolute.path);
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/isolated/resident_web_runner.dart:443]:
```suggestion
        flutterDevices.first.generator!
          ..addFileSystemRoot(parent)
          ..addFileSystemRoot(_fileSystem!.directory('test').absolute.path);
```

File: packages/flutter_tools/lib/src/isolated/resident_web_runner.dart (hunk 8 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/isolated/resident_web_runner.dart:82]: and in `resident_runner`
https://github.com/flutter/flutter/blob/5805f4544534ccb3200e50625f1dd79cd9881b1f/packages/flutter_tools/lib/src/resident_runner.dart#L1087-L1090

File: packages/flutter_tools/lib/src/base/dds.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/dds.dart:17]: You're right; it's not easy to fix the tests however:

1. `DartDevelopmentService` here is a thin wrapper that lazily loads its own `dds.DartDevelopmentService` into a nullable field `_ddsInstance` by calling `ddsLauncherCallback`.
2. If in the tests, I have `ddsLauncherCallback` return a `FakeDartDevelopmentService extends Fake implements dds.DartDevelopmentService`, it his an `UnimplementedError` on this line `_ddsInstance?.done.whenComplete( ... )` https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/dds.dart#L63

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/dds.dart:17]: ok, implemented it and the tests pass now

File: packages/flutter_tools/lib/src/resident_runner.dart (hunk 4 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/resident_runner.dart:929]: :+1:

File: packages/flutter_tools/lib/src/commands/daemon.dart (hunk 3 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/commands/daemon.dart:739]: done.

File: packages/flutter_tools/lib/src/run_hot.dart (hunk 5 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/run_hot.dart:462]: done

File: packages/flutter_tools/lib/src/run_hot.dart (hunk 6 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/run_hot.dart:477]: done

File: packages/flutter_tools/lib/src/run_hot.dart (hunk 7 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/run_hot.dart:501]: done

File: packages/flutter_tools/lib/src/isolated/resident_web_runner.dart (hunk 8 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/isolated/resident_web_runner.dart:82]: done
