### PR TITLE
[flutter_tools] Do not use the logcat -T flag on Android versions before Lollipop

### LINKED ISSUE #47112: Crashing on Android Kitkat (4.4)
Freshly created app crashes on Android Kitkat - both debug and release, and on stable, dev and master channel. Results in:

**Unforunately, testapp has stopped**

```bash
C:\src\Apps\testapp>flutter run --enable-software-rendering --release -d 110103aa8898b200
Running "flutter pub get" in testapp...                             0.9s
Launching lib\main.dart on SM J110F in release mode...
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.3+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.0+1\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.9\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.0\android\src\main\java\io\flutter\plugins\firebase\storage\FirebaseStoragePlugin.java:60: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
        binding.getApplicationContext(), binding.getFlutterEngine().getDartExecutor());
                                                ^
1 warning
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+13\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.5.1\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      99.2s
√ Built build\app\outputs\apk\release\app-release.apk (14.3MB).
Installing build\app\outputs\apk\app.apk...                        15.4s

To quit, press "q".
```

Flutter doctor:
```bash
C:\src\Apps\testapp>flutter doctor -v
[√] Flutter (Channel dev, v1.13.2, on Microsoft Windows [Version 10.0.17763.914], locale en-US)
    • Flutter version 1.13.2 at C:\src\flutter
    • Framework revision 4944622b5d (4 days ago), 2019-12-12 18:43:58 +0000
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Rudeboy\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Rudeboy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (3 available)
    • SM J110F • 110103aa8898b200 • android-arm • Android 4.4.4 (API 19)
    • SM G955F • emulator-5554    • android-x86 • Android 7.1.2 (API 25)
    • SM G955F • localhost:5555   • android-x86 • Android 7.1.2 (API 25)

• No issues found!
```

### LINKED ISSUE #47609: flutter version >1.9.1 not working on Android 4.4 and lower
Flutter doesn't run on Android 4.4 or lower when using Flutter version greater than 1.9.1 - on stable, dev, beta or master.

## Steps to Reproduce

1. `flutter channel stable`, `flutter channel upgrade'
2. `flutter create testapp` (100% freshly created app)
3. Run app on emulator or physical device (Android 4.4 or lower) - "Unfortunately, testapp has stopped working"
4. `flutter channel v1.9.1`
5. App runs correctly.

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/47609
Fixes https://github.com/flutter/flutter/issues/47112

### CODE REVIEW

**Review by blasten — APPROVED** [review]
LGTM! Thanks for fixing this issue.

File: packages/flutter_tools/lib/src/android/android_device.dart [hunk 1]
```diff
@@ -1014,17 +1014,24 @@ class _AdbLogReader extends DeviceLogReader {
...
+    // logcat -T is not supported on Android releases before Lollipop.
+    const int kLollipopVersionCode = 21;
+    final int apiVersion = int.tryParse(await device._apiVersion);
+    if (apiVersion != null && apiVersion >= kLollipopVersionCode) {
+      args.addAll(<String>[
+        '-T',
+        lastTimestamp ?? '', // Empty `-T` means the timestamp of the logcat command invocation.
+      ]);
+    }
+    await processUtils.start(device.adbCommandForDevice(args)).then<void>((Process process) {
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/android/android_device.dart]: With `await`, the `.then` is a bit redundant. You can say
```dart
final Process process = await processUtils.start(...);
_process = process;
...
```

Comment (jason-simmons) [reply packages/flutter_tools/lib/src/android/android_device.dart]: done
