### PR TITLE
[iOS] specify minimum os version for native asset frameworks

### LINKED ISSUE #148501: [iOS] native asset framework is missing MinimumOSVersion
This fails to pass asset validation in AppStore connect:

```
2024-05-16 17:42:33.183 *** Error: ERROR: [ContentDelivery.Uploader] Asset validation failed (90530) Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'Superlist.app/Frameworks/native_regex_pcre2.framework' is ''. (ID: 5f8e77a3-e89b-471e-90cc-ee144bda0f87)
2024-05-16 17:42:33.184 *** Error: ERROR: [ContentDelivery.Uploader] Asset validation failed (90360) Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle 
```

### PR DESCRIPTION
**Pull request by knopp**
Fixes https://github.com/flutter/flutter/issues/148501

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by knopp** [comment]
@dcharkes is the plist file tested anywhere? Also the approach here is a bit ugly, the issue is that the plist key is different for macOS and iOS, and also as far as I can tell it is not mandatory.

File: packages/flutter_tools/lib/src/isolated/native_assets/ios/native_assets.dart [hunk 1]
```diff
@@ -230,7 +230,7 @@ Future<void> _copyNativeAssetsIOS(
       }
       await lipoDylibs(dylibFile, sources);
       await setInstallNameDylib(dylibFile);
-      await createInfoPlist(targetUri.pathSegments.last, frameworkDir);
+      await createInfoPlist(targetUri.pathSegments.last, frameworkDir, minimumIOSVersion: '12.0');
```
Comment (dcharkes) [inline packages/flutter_tools/lib/src/isolated/native_assets/ios/native_assets.dart:233]: I believe this value should come from somewhere.

(Also this value should be passed into the `BuildConfig` so that the build hook can fail if it cannot produce a dylib with the right iOS version (https://github.com/dart-lang/native/issues/1133). This can be done in a separate PR though.)

**Comment by dcharkes** [comment]
Do we have the minimum iOS version that the app we're building is targeting somewhere? See the code that does the same for minimum android version: https://github.com/flutter/flutter/issues/148044#issuecomment-2102326283

**Comment by dcharkes** [comment]
> @dcharkes is the plist file tested anywhere?

No. You could add it here:

https://github.com/flutter/flutter/blob/6b383615c655fe4e58643992a46df31b1f91da52/packages/flutter_tools/test/integration.shard/isolated/native_assets_test.dart#L314-L348

**Comment by knopp** [comment]
> Do we have the minimum iOS version that the app we're building is targeting somewhere? See the code that does the same for minimum android version: [#148044 (comment)](https://github.com/flutter/flutter/issues/148044#issuecomment-2102326283)

I think this is right now hardcoded to 12.0 for `App.framework` inside `AppFrameworkInfo.plist`. There is also `IPHONEOS_DEPLOYMENT_TARGET` set by xcode during build that contains project deployment target. But I think the plugin should be able to specify own deployment target, that seems like the cleanest way.

**Comment by jmagman** [comment]
> What is the interplay between XCode and a Flutter app on the minimal iOS version?

The target version is the minimum support by latest Xcode.  https://flutter.dev/go/match-xcode-deployment-range

> This document proposes that Flutter’s supported deployment platform versions be updated when Xcode is released annually to match its deployment versions.  Versions lower than the Xcode range will become unsupported.

Right now it's set in the tool in a bunch of places, see https://github.com/flutter/flutter/pull/140823 for the last time we had to bump it (note the changes in `dev` and `example` weren't manually updated, those are automatically migrated example/test apps).

@vashworth filed https://github.com/flutter/flutter/issues/145104 to make this settable in fewer places.

**Comment by dcharkes** [comment]
Thanks @jmagman!

Then I'm fine landing as is once we added a test. And maybe leave a comment on https://github.com/flutter/flutter/issues/145104 so that it doesn't get forgotten.

**Comment by knopp** [comment]
@dcharkes, I added test and a TODO to wire things once hook can specify deployment target. There is another issue - the bundle identifier must not contain underscores, we should replace them by - probably. Should that be part of this PR or should I make separate PR for it?

**Comment by knopp** [comment]
Escaping the bundle identifier seems like a tiny change, I added it to this PR.

**Review by dcharkes — APPROVED** [review]
Thanks so much for triaging and supplying a PR @knopp! ❤️   LGTM! 🚀

**Comment by tnarik** [comment]
I've been trying to build and release via TestFlight an app using Thermion (which requires iOS 13.0).
The library suggests an override of the MinimumOSVersion via a scripts (as in https://thermion.dev/ios ), but I was checking and apparently this could be supported within Flutter, right?

This  commit adds the capability to provide the version from the script and the only thing missing (if I understood the conversation) is ensuring a value passed via configuration is used here. I think that part was pending on https://github.com/dart-lang/native/issues/1133 ? correct, @knopp ?

It seems closed now. Is there something I could do to help?

**Comment by dcharkes** [comment]
> Then this version is passed into the build hook and is available as in https://pub.dev/documentation/code_assets/latest/code_assets/IOSCodeConfig/targetVersion.html.

This is not true. (I would like it to be true, but we don't read the cocoapods specs to fish out the number.) It's a hardcoded number right now. Bumping it from 12 to 13 to align with the Flutter supported lowest version:

* https://github.com/flutter/flutter/pull/179079

@tnarik, since Flutter only supports 13 and up, it should probably be fine as long as the Flutter SDK lower bound on your package is the that moved the lowest supported version up to 13.
