### PR TITLE
Text selection located wrong position when selecting multiple lines over max lines

### LINKED ISSUE #96453: Text selection toolbar offset bound to global position of the text
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Long click the text field and _Select all_ from toolbar 
3. Scroll the text up and down 

**Expected results:** 

The toolbar is bound to the viewport of the text field and the offset does not grow further. See...

https://github.com/flutter/flutter/blob/2b21c3e163346e2e75bb45d3e3372eb5cc29d54d/packages/flutter/lib/src/widgets/text_selection.dart#L575

**Actual results:** 
toolbar

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              TextField(
                maxLines: 2,
                controller: TextEditingController(
                  text: "L1\nL2\nL3\nL4\nL5\nL6\nL7\nL8",
                ),
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale de-DE)
    • Flutter version 2.8.1 at /Users/dev/Library/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (vor 4 Wochen), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/dev/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by takassh**
Fixes https://github.com/flutter/flutter/issues/96453

This PR fixes bugs that text selection located wrong position when selecting multiple lines over max lines.

related closed pr https://github.com/flutter/flutter/pull/96471

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

Screen Shot 2022-04-28 at 3 35 07 PM

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by takassh** [comment]
hi
test is failed because of `When renders below a block of text, menu appears below bottom endpoint`.
I want to confirm whether it is expected behavior.

|master|pr|
|---|---|
|Screenshot_1651150321|Screenshot_1651150712|

**Comment by takassh** [comment]
cc @chunhtai

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 1]
```diff
@@ -96,17 +96,23 @@ class _CupertinoTextSelectionControlsToolbarState extends State<_CupertinoTextSe
       mediaQuery.size.width - mediaQuery.padding.right - _kArrowScreenPadding,
     );
 
+    final double topAmountInEditableRegion = widget.endpoints.first.point.dy - widget.textLineHeight;
+    final double anchorTop = (topAmountInEditableRegion > 0 ? topAmountInEditableRegion : 0) + widget.globalEditableRegion.top;
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/text_selection.dart:100]: you can use math.max

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 2]
```diff
@@ -96,17 +96,23 @@ class _CupertinoTextSelectionControlsToolbarState extends State<_CupertinoTextSe
...
+
+    final double bottomAmountInEditableRegion = widget.endpoints.last.point.dy;
+    final double anchorBottom = (bottomAmountInEditableRegion < widget.globalEditableRegion.size.height ? bottomAmountInEditableRegion : widget.globalEditableRegion.size.height) + widget.globalEditableRegion.top;
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/text_selection.dart:103]: use math.min

File: packages/flutter/test/material/text_selection_test.dart [hunk 3]
```diff
@@ -547,6 +547,79 @@ void main() {
...
+        expect(find.text('Select all'), findsNothing);
+        expect(find.byType(IconButton), findsNothing);
+
+        final Offset cutOffset = tester.getTopLeft(find.text('Cut'));
+        final Offset textFieldOffset =
+            tester.getTopLeft(find.byType(TextField));
+        expect(cutOffset.dy + 25, equals(textFieldOffset.dy));
+      },
+      skip:
+          isBrowser, // [intended] We do not use Flutter-rendered context menu on the Web.
```
Comment (chunhtai) [inline packages/flutter/test/material/text_selection_test.dart:619]: avoid `we` in comment.

File: packages/flutter/test/material/text_selection_test.dart [hunk 4]
```diff
@@ -547,6 +547,79 @@ void main() {
...
+      variant: const TargetPlatformVariant(
+          <TargetPlatform>{TargetPlatform.android, TargetPlatform.iOS}),
```
Comment (chunhtai) [inline packages/flutter/test/material/text_selection_test.dart:621]: just keep it one line

Comment (chunhtai) [reply packages/flutter/test/material/text_selection_test.dart:621]: and you need spaces in after `{` and before `}`

**Review by chunhtai — COMMENTED** [review]
logic looks good, left some comments

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 1 above)
Comment (takassh) [reply packages/flutter/lib/src/cupertino/text_selection.dart]: fixed

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 2 above)
Comment (takassh) [reply packages/flutter/lib/src/cupertino/text_selection.dart]: fixed

File: packages/flutter/test/material/text_selection_test.dart (hunk 3 above)
Comment (takassh) [reply packages/flutter/test/material/text_selection_test.dart]: fixed

File: packages/flutter/test/material/text_selection_test.dart (hunk 4 above)
Comment (takassh) [reply packages/flutter/test/material/text_selection_test.dart]: fixed

**Comment by takassh** [comment]
thanks for quick review.
I fixed them and added a new test for `cupertino`.
@chunhtai

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by takassh** [comment]
@justinmc 
Hi, what should I do next?

File: packages/flutter/lib/src/cupertino/text_selection_toolbar.dart [hunk 5]
```diff
@@ -129,6 +129,7 @@ class CupertinoTextSelectionToolbar extends StatelessWidget {
         delegate: TextSelectionToolbarLayoutDelegate(
           anchorAbove: anchorAbove - localAdjustment - contentPaddingAdjustment,
           anchorBelow: anchorBelow - localAdjustment + contentPaddingAdjustment,
+          fitsAbove: fitsAbove,
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/text_selection_toolbar.dart:132]: Previously I wasn't passing this because TextSelectionToolbarLayoutDelegate could calculate it itself (see the [docs](https://master-api.flutter.dev/flutter/widgets/TextSelectionToolbarLayoutDelegate/fitsAbove.html)), but I suppose we can pass it in here to avoid calculating it twice.

**Review by justinmc — COMMENTED** [review]
Thanks for fixing this!  FYI It looks like there is a legitimate test failure in text_selection_test.dart.

Also, about your screenshots in https://github.com/flutter/flutter/pull/102747#issuecomment-1112173270.  I'm not convinced that the new menu location is correct.  Shouldn't it be below?  On native Android I see the selection color expand for the full width of the input, which Flutter might also be getting wrong unrelated to this PR, and the toolbar goes below.

**Comment by takassh** [comment]
@justinmc 
ok, then I put `anchorBelow` back.

I can pass all tests on local, but it doesn't pass on github actions. can you take a look?

**Comment by takassh** [comment]
hi @justinmc

I'm not sure why `Linux web_long_running_tests_1_5` failed.
please tell me what to do?
(sorry for bothering you)

File: packages/flutter/test/cupertino/text_selection_test.dart [hunk 6]
```diff
@@ -533,6 +533,64 @@ void main() {
       skip: isBrowser, // [intended] We do not use Flutter-rendered context menu on the Web.
       variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.iOS }),
     );
+
+    testWidgets(
+      'When select multiple lines over max lines',
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_selection_test.dart:538]: Nit: "select" => "selecting" Here and in the other test.

File: packages/flutter/test/cupertino/text_selection_test.dart [hunk 7]
```diff
@@ -533,6 +533,64 @@ void main() {
...
+        await tester.pumpAndSettle();
+
+        // Only Cut, Copy, and Paste are shown.
+        expect(find.text('Cut'), findsOneWidget);
+        expect(find.text('Copy'), findsOneWidget);
+        expect(find.text('Paste'), findsOneWidget);
+        expect(find.text('Select All'), findsNothing);
+        expect(find.text('◀'), findsNothing);
+        expect(find.text('▶'), findsNothing);
+
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_selection_test.dart:585]: Nit: Maybe add a comment like this?  "The menu appears at the top of the visible selection."

Comment (justinmc) [reply packages/flutter/test/cupertino/text_selection_test.dart:585]: And same for the other test below.

File: packages/flutter/test/cupertino/text_selection_test.dart [hunk 8]
```diff
@@ -533,6 +533,64 @@ void main() {
...
+        final Offset cutOffset = tester.getTopLeft(find.text('Cut'));
+        final Offset textFieldOffset =
+            tester.getTopLeft(find.byType(CupertinoTextField));
+        expect(cutOffset.dy + 36, equals(textFieldOffset.dy));
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_selection_test.dart:589]: Nit: Is there any way to explain where this 36 number comes from?

File: packages/flutter/test/material/text_selection_test.dart [hunk 9]
```diff
@@ -547,6 +547,77 @@ void main() {
...
+        expect(find.text('Cut'), findsOneWidget);
+        expect(find.text('Copy'), findsOneWidget);
+        expect(find.text('Paste'), findsOneWidget);
+        expect(find.text('Select all'), findsNothing);
+        expect(find.byType(IconButton), findsNothing);
+
+        final Offset cutOffset = tester.getTopLeft(find.text('Cut'));
+        final Offset textFieldOffset =
+            tester.getTopLeft(find.byType(TextField));
+        expect(cutOffset.dy + 25, equals(textFieldOffset.dy));
```
Comment (justinmc) [inline packages/flutter/test/material/text_selection_test.dart:616]: Same question about explaining this 25 value.

**Review by justinmc — APPROVED** [review]
LGTM 👍 

Thanks for fixing this.  I tried running your branch with the sample in the issue and it worked correctly for me.  Glad to see you got the tests passing.

**Comment by takassh** [comment]
@justinmc 
thanks for review
added comments

**Comment by justinmc** [comment]
This is good to go.  I'm writing myself a note to merge this on Monday.

**Comment by takassh** [comment]
@justinmc 
thank you!

btw, you mentioned it before
> the selection color expand for the full width of the input, which Flutter might also be getting wrong unrelated to this PR

https://github.com/flutter/flutter/pull/102747#pullrequestreview-976059940

this issue has already been reported? I wanna contribute it next if I can.

**Comment by justinmc** [comment]
@takassh No I have not seen an issue for the width of the selection highlight.  That's great if you want to work on it!  Could you create one and mention me?
