### PR TITLE
Fix DomCSSStyleSheetExtension to work with dart2wasm.

### LINKED ISSUE #122150: [web/wasm] Type 'double' is not a subtype of type 'int' in type cast - DomCSSStyleSheetExtension|insertRule
```
Type 'double' is not a subtype of type 'int' in type cast
    at callMethod (http://localhost:8080/main.dart.wasm:wasm-function[1759]:0x144732)
    at DomCSSStyleSheetExtension|insertRule (http://localhost:8080/main.dart.wasm:wasm-function[11435]:0x282eb5)
    at PlatformSelectableRegionContextMenu._registerWebSelectionCallback closure at file:///Users/kevmoo/github/flutter/packages/flutter/lib/src/widgets/_platform_selectable_region_context_menu_web.dart:104:36 (http://localhost:8080/main.dart.wasm:wasm-function[11420]:0x282cc1)
    at closure wrapper at file:///Users/kevmoo/github/flutter/packages/flutter/lib/src/widgets/_platform_selectable_region_context_menu_web.dart:104:36 (http://localhost:8080/main.dart.wasm:wasm-function[11424]:0x282dca)
    at PlatformViewManager.renderContent closure at file:///Users/kevmoo/github/flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/platform_views/content_manager.dart:112:42 (http://localhost:8080/main.dart.wasm:wasm-function[7372]:0x22493c)
    at closure wrapper at file:///Users/kevmoo/github/flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/platform_views/content_manager.dart:112:42 (http://localhost:8080/main.dart.wasm:wasm-function[7377]:0x224a5e)
    at __WasmDefaultMap&_HashFieldBase&MapMixin&_HashBase&_OperatorEqualsAndHashCode&_LinkedHashMapMixin.putIfAbsent (http://localhost:8080/main.dart.wasm:wasm-function[3241]:0x17767b)
    at PlatformViewManager.renderContent (http://localhost:8080/main.dart.wasm:wasm-function[7371]:0x22483b)
```

this code: https://github.com/kevmoo/flutter_web_number_fun at https://github.com/kevmoo/flutter_web_number_fun/commit/8109765992a212ee7c8dee974b5bd4b325f84d06

Flutter at https://github.com/flutter/flutter/commit/80be2bfc9f8cc39d197f616b8ce809217908a5f8

Chrome at Version 113.0.5637.2 (Official Build) canary (arm64)

these flags

image

### PR DESCRIPTION
**Pull request by eyebrowsoffire**
This fixes https://github.com/flutter/flutter/issues/122150

### CODE REVIEW

File: packages/flutter/lib/src/services/dom.dart [hunk 1]
```diff
@@ -336,8 +336,11 @@ class DomCSSStyleSheet extends DomStyleSheet {}
 /// [DomCSSStyleSheet]'s required extension.
 extension DomCSSStyleSheetExtension on DomCSSStyleSheet {
   /// Inserts a rule into this style sheet.
-  int insertRule(String rule, [int? index]) => js_util
-      .callMethod(this, 'insertRule', <Object>[rule, if (index != null) index]);
+  int insertRule(String rule, [int? index]) =>
+    js_util.callMethod(this, 'insertRule', <Object>[
```
Comment (joshualitt) [inline packages/flutter/lib/src/services/dom.dart:340]: add `<double>`? Also feel free to ignore because this is going away.

**Review by joshualitt — APPROVED** [review]
