### PR TITLE
Deprecate Scaffold resizeToAvoidBottomPadding, now resizeToAvoidBottomInset

### LINKED ISSUE #12084: Double stacked material scaffolds shouldn't double resizeToAvoidBottomPadding
From https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/flutter-dev/pLub7dov2ag

With 2 layers of Scaffolds, it's possible for the resizeToAvoidBottomPadding to produce 2 paddings with the height of the on-screen keyboard. 

We should somehow avoid more than 1 padding to avoid the keyboard.

### LINKED ISSUE #15424: viewInsets and padding on Window and MediaQueryData should define how they interact
Right now we don't see to say anywhere whether they overlap or add.

If they overlap, we should probably fix removePadding to also reduce the viewInsets by the same amount.

cc @cbracken

### LINKED ISSUE #23106: Show warning when nesting Scaffolds
Using nested Scaffolds can cause unexpected behaviors that rush new issues into this repository,
to prevent further issue reports related, I suggest an assertion in the Scaffold Class just for Debug Mode:

```
assert(() {
  assert(context.ancestorWidgetOfExactType(Scaffold) == null);
});
```

These are some of the issues:

- https://github.com/flutter/flutter/issues/23051
- https://github.com/flutter/flutter/issues/20289
- https://github.com/flutter/flutter/issues/12084
- https://github.com/flutter/flutter/issues/20295

### LINKED ISSUE #25758: SafeArea with keyboard
Hello!  (For iPhone x, xr and the like)
The bottom: true / false parameter for the safe area does not respond to changes when the keyboard is on, the bottom parameter is always false. In this connection, if the scaffold parameter has resizeToAvoidBottomPadding: false, and the keyboard appears, the entire widgets is shifted to down MediaQuery.of (context) .padding.bottom
```dart
return Scaffold(
      resizeToAvoidBottomPadding: false,
      body: SafeArea(
          child: Center(
        child: Container(
          width: 200,
          child: TextFormField(
            decoration: InputDecoration(
              hintText: 'text',
            ),
          ),
        ),
      )),
    );
```

```
[✓] Flutter (Channel dev, v1.1.4, on Mac OS X 10.14.2 18C54, locale ru-RU)
    • Flutter version 1.1.4 at /Users/alexfix/Flutter/flutter
    • Framework revision 7a88fbc5fd (5 days ago), 2018-12-20 11:38:07 -0800
    • Engine revision dbdb5e6f8c
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alexfix/Library/Android/sdk
    • Android NDK at /Users/alexfix/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • iPhone XR • 0AB397AD-D503-4882-8849-B6F3229D2B23 • ios • iOS 12.1 (simulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes https://github.com/flutter/flutter/issues/23106 per the [simplified test case](https://gist.github.com/HansMuller/c1fe54fdb4c3ab0db1f3b43d9fa85418) from https://github.com/flutter/flutter/issues/20295. 
Fixes https://github.com/flutter/flutter/issues/25758
Fixes https://github.com/flutter/flutter/issues/12084
Fixes https://github.com/flutter/flutter/issues/15424

**Scaffold Layout**

Originally the `resizeToAvoidBottomPadding` flag referred to `MediaQueryData.padding`. As of https://github.com/flutter/flutter/pull/13437 it refers to `MediaQueryData.viewInsets`. This has caused confusion among developers (me included). Added a Scaffold property called `resizeToAvoidBottomInset` and deprecated resizeToAvoidBottomPadding. Hopefully this will make things a little clearer to readers. There's a similar property on CupertinoPageScaffold so perhaps we're incrementally more consistent as well.

Updated the MediaQuery docs to clarify viewInsets and padding.  Updated the Scaffold docs to further clarify resizeToAvoidBottomInset and its relationship to MediaQuery. Updated the MediaQuery docs similarly.

**Nested Layout**

Nested scaffolds are inset within the parent's scaffold's insets by viewInset.bottom, to avoid the keyboard). Previously, when the keyboard appeared, the bottom of the inner scaffold was adjusted upwards by 2x the keyboard's height (2x the MediaQuery's viewInsets.bottom value). This is because the body's MediaQuery (added by the Scaffold) did not clear the viewInsets.bottom property, even when it had resized body by as much.

Scaffold now clears the body's MediaQuery viewInsets.bottom value if the body was resized.

Updated the Scaffold docs to discourage developers from using nested scaffolds.

### CODE REVIEW

**Comment by xster** [comment]
Is there a bug number. 

Not sure if I understood completely but isn't the bug already 'incurred' higher than the scaffold layout? i.e. the outer scaffold should just remove the media query padding and inset and then put the inner scaffold into the zero media query no? 

Otherwise, wouldn't other non-scaffold things inside the scaffold still be wrong?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 1]
```diff
@@ -1711,10 +1715,23 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
       _buildDrawer(children, textDirection);
     }
 
+    /*
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/scaffold.dart]: Should this commented out code be deleted?

**Comment by goderbauer** [comment]
Should we document this nested behavior in the doc comment of Scaffold?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 2]
```diff
@@ -1711,10 +1715,23 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
...
     // The minimum insets for contents of the Scaffold to keep visible.
     final EdgeInsets minInsets = mediaQuery.padding.copyWith(
       bottom: widget.resizeToAvoidBottomPadding ? mediaQuery.viewInsets.bottom : 0.0,
     );
+    */
+
+    // If this is a nested scaffold: assume that the outer scaffold has
```
[the remark this answers is not in the document]
Comment (HansMuller) [reply packages/flutter/lib/src/material/scaffold.dart]: The current scaffold is the inner one.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 3]
```diff
@@ -694,6 +697,53 @@ class _FloatingActionButtonTransitionState extends State<_FloatingActionButtonTr
 /// ```
 /// {@end-tool}
 ///
+/// ## Scaffold layout, the keyboard, and display "notches"
+///
+/// The scaffold will expand to fill the available space. That usually
+/// means that it will occupy its entire window or device screen. When
+/// the device's keyboard appears the Scaffold's ancestor [MediaQuery]
```
Comment (xster) [inline packages/flutter/lib/src/material/scaffold.dart]: `the device's keyboard appears, the Scaffold's ancestor [MediaQuery]`

File: packages/flutter/lib/src/material/scaffold.dart [hunk 4]
```diff
@@ -694,6 +697,53 @@ class _FloatingActionButtonTransitionState extends State<_FloatingActionButtonTr
...
+/// widget's [MediaQueryData.viewInsets] changes and the Scaffold will
+/// be rebuilt. By default the scaffold's [body] is resized to make
+/// room for the keyboard. To prevent the resize set
```
Comment (xster) [inline packages/flutter/lib/src/material/scaffold.dart]: I would think
`room for the keyboard. To prevent the resize, set`
but my english is crappy so you decide

File: packages/flutter/lib/src/material/scaffold.dart [hunk 5]
```diff
@@ -694,6 +697,53 @@ class _FloatingActionButtonTransitionState extends State<_FloatingActionButtonTr
...
+/// [resizeToAvoidBottomInset] to false. In either case the focused
+/// widget will be scrolled into view if it's within a scrollable
+/// container.
+///
+/// The [MediaQueryData.padding] value defines areas that might
+/// not be completely visible, like the display "notch" on the iPhone
+/// X. The scaffold's [body] is not inset by this padding value
+/// although an [appBar] or [bottomNavigationBar] will typically
+/// cause the body to avoid the vertical padding. The [SafeArea]
```
Comment (xster) [inline packages/flutter/lib/src/material/scaffold.dart]: I wouldn't over-emphasize 'vertical'. If you do call it out, add equal importance to horizontal paddings etc.

Comment (HansMuller) [reply packages/flutter/lib/src/material/scaffold.dart]: In this case the comment is referring to the fact that when the appbar is visible, the body typically ends up below the bottom padding (assuming that the appbar has its default height). Similarly the bottom navbar typically causes the body to move out of the way of the bottom padding. Those are vertical adjustments.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 6]
```diff
@@ -743,9 +794,11 @@ class Scaffold extends StatefulWidget {
 
   /// The primary content of the scaffold.
   ///
-  /// Displayed below the app bar and behind the [floatingActionButton] and
-  /// [drawer]. To avoid the body being resized to avoid the window padding
-  /// (e.g., from the onscreen keyboard), see [resizeToAvoidBottomPadding].
+  /// Displayed below the [appBar], above the bottom of the ambient
```
Comment (xster) [inline packages/flutter/lib/src/material/scaffold.dart]: Is the [appBar] above the bottom of the MediaQueryData.viewInsets or is the [body] above the bottom of the MediaQueryData.viewInset?

File: packages/flutter/lib/src/material/scaffold.dart (hunk 4 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/scaffold.dart]: I'm not sure about the "right" comma usage here. If you think the comma makes it easier to understand, I'm happy to add one.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 6 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/scaffold.dart]: It's the latter

File: packages/flutter/lib/src/material/scaffold.dart (hunk 5 above)
Comment (xster) [reply packages/flutter/lib/src/material/scaffold.dart]: If you rotate the phone, the body just gets the insets horizontally (which is an equally important concept users should be aware of)

File: packages/flutter/lib/src/material/scaffold.dart [hunk 7]
```diff
@@ -850,15 +903,25 @@ class Scaffold extends StatefulWidget {
...
 
-  /// Whether the [body] (and other floating widgets) should size themselves to
-  /// avoid the window's bottom padding.
+  /// This flag is deprecated, please use resizeToAvoidBottomInset
+  /// instead.
+  ///
+  /// Originally the name referred [MediaQueryData.padding]. Now it refers
+  /// [MediaQueryData.viewInsets], so using [resizeToAvoidBottomInset]
+  /// should be clearer to readers.
+  @deprecated
```
Comment (xster) [inline packages/flutter/lib/src/material/scaffold.dart]: Looking at the rest of the codebase, `@Deprecated('reason')` is the Dart annotation and `@deprecated` is the dartdoc annotation.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 5 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/scaffold.dart]: Good point, the notches are horizontal in that case!

File: packages/flutter/lib/src/material/scaffold.dart [hunk 8]
```diff
@@ -1606,16 +1678,14 @@ class ScaffoldState extends State<Scaffold> with TickerProviderStateMixin {
...
         children,
         _snackBars.first._widget,
         _ScaffoldSlot.snackBar,
         removeLeftPadding: false,
         removeTopPadding: true,
         removeRightPadding: false,
-        removeBottomPadding: removeBottomPadding,
+        removeBottomPadding: widget.bottomNavigationBar != null || widget.persistentFooterButtons != null,
       );
     }
```
Comment (xster) [inline packages/flutter/lib/src/material/scaffold.dart]: Not super sure about the material specs. Should the FAB move too?

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 9]
```diff
@@ -30,6 +30,22 @@ enum Orientation {
 /// If no [MediaQuery] is in scope then the [MediaQuery.of] method will throw an
 /// exception, unless the `nullOk` argument is set to true, in which case it
 /// returns null.
+///
+/// MediaQueryData includes two [EdgeInsets] values:
+/// [padding] and [viewInsets]. These
+/// values reflect the configuration of the device and are used by
+/// many top level widgets, like [SafeArea] and the cupertino and
```
Comment (xster) [inline packages/flutter/lib/src/widgets/media_query.dart]: Capitalize Cupertino and Material

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 10]
```diff
@@ -30,6 +30,22 @@ enum Orientation {
...
+/// material scaffold widgets. The padding value defines areas that
+/// might not be completely visible, like the display "notch" on the
+/// iPhone X. The viewInsets value defines areas that aren't visible at
+/// all, typically because they're obscured by the device's keyboard.
+/// The viewInsets and padding values are independent, they're both
+/// measured from the edges of the MediaQuery widget's bounds. The
+/// bounds of the top level MediaQuery created by [WidgetsApp] are the
+/// same as the window that contains the app. The scaffolds typically
```
Comment (xster) [inline packages/flutter/lib/src/widgets/media_query.dart]: Instead of making the scaffolds special, we should actually say all widgets that consumes/handles the paddings or insets should remove it in its descendant MediaQuery

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 11]
```diff
@@ -30,6 +30,22 @@ enum Orientation {
...
+///
+/// MediaQueryData includes two [EdgeInsets] values:
+/// [padding] and [viewInsets]. These
+/// values reflect the configuration of the device and are used by
+/// many top level widgets, like [SafeArea] and the cupertino and
+/// material scaffold widgets. The padding value defines areas that
+/// might not be completely visible, like the display "notch" on the
+/// iPhone X. The viewInsets value defines areas that aren't visible at
+/// all, typically because they're obscured by the device's keyboard.
+/// The viewInsets and padding values are independent, they're both
```
Comment (xster) [inline packages/flutter/lib/src/widgets/media_query.dart]: While you're here... :D

Would you like to add another section describing their interplay? I have to go look it up and/or test it every time.

i.e. when the Android/iOS home bar (padding) and the keyboard (inset) are on top of each other, does the inset include the padding, is the padding just zero, does the inset only count the area on top of the padding etc etc. I can never remember since we didn't write it down.

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 12]
```diff
@@ -67,7 +83,7 @@ class MediaQueryData {
       boldText = window.accessibilityFeatures.boldText,
       alwaysUse24HourFormat = window.alwaysUse24HourFormat;
 
-  /// The size of the media in logical pixel (e.g, the size of the screen).
+  /// The size of the media in logical pixels (e.g, the size of the screen).
```
Comment (xster) [inline packages/flutter/lib/src/widgets/media_query.dart]: `The size of the media in logical pixels or points (e.g, the size of the screen).`

To make it friendlier for mobile developers' lexicon

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 13]
```diff
@@ -91,17 +107,21 @@ class MediaQueryData {
...
   final double textScaleFactor;
 
-  /// The number of physical pixels on each side of the display rectangle into
-  /// which the application can render, but over which the operating system
-  /// will likely place system UI, such as the keyboard, that fully obscures
-  /// any content.
+  /// The parts of the display that are completely obscured by system UI,
+  /// typically by the device's keyboard.
+  ///
+  /// When a mobile device's keyboard is visible `viewInsets.bottom`
```
Comment (xster) [inline packages/flutter/lib/src/widgets/media_query.dart]: Bah, sorry I might be totally wrong on this. But `When a mobile device's keyboard is visible, viewInsets.bottom` seems more natural. Anyway, it's aesthetics. Feel free to ignore.

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 14]
```diff
@@ -91,17 +107,21 @@ class MediaQueryData {
...
+  /// corresponds to the top of the keyboard.
+  ///
+  /// This value is independent of the [padding]: both values are
+  /// measured from the edges of the [MediaQuery] widget's bounds. The
+  /// bounds of the top level MediaQuery created by [WidgetsApp] are the
+  /// same as the window that contains the app.
```
Comment (xster) [inline packages/flutter/lib/src/widgets/media_query.dart]: It might not be clear what 'window' is technically. If you bring it up, it might be worth qualifying specifically.

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 15]
```diff
@@ -91,17 +107,21 @@ class MediaQueryData {
...
   final EdgeInsets viewInsets;
 
-  /// The number of physical pixels on each side of the display rectangle into
-  /// which the application can render, but which may be partially obscured by
-  /// system UI (such as the system notification area), or or physical
-  /// intrusions in the display (e.g. overscan regions on television screens or
-  /// phone sensor housings).
+  /// The parts of the display that are partially obscured by system UI,
+  /// typically by the hardware display "notches" or the system
+  /// notification area.
```
Comment (xster) [inline packages/flutter/lib/src/widgets/media_query.dart]: Ummm, I'm not sure if this is true. If there's a banner notification that pops-up on Android, we don't rebuild the app with a new MediaQueryData.padding do we?

**Comment by xster** [comment]
The implementation LGTM. Just some doc comments since it's such a central and tricky part of the framework.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 11 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/media_query.dart]: Might be worth saying too: if you make a custom widget and it consumes a padding/inset, you're responsible to make sure your child doesn't see it anymore. Otherwise, your child might decide to be funky.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 12 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/media_query.dart]: I don't think that will make it friendlier since it's not clear how "points" which typically would be a font dimension, map to logical pixels.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 13 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/media_query.dart]: Because of all of the comma comments I just read a grammer site's overview of the rules for inserting commas. For as long as I could stand it anyway. As far as I can tell commas like this, which would match the natural pauses in speech, don't belong in written text.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 14 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/media_query.dart]: OK: pointed out parenthetically that it's typically the screen.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 10 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/media_query.dart]: Done.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 9 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/media_query.dart]: Done

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 14 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/media_query.dart]: Bit of a nit but might not be true for add to app.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 8 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/scaffold.dart]: The FAB does still move when the keyboard appears.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 13 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/media_query.dart]: nit: `Because of all of the comma comments, I just read a grammer site's overview of the rules`

I kid I kid. Like I said, you have a better grasp at this than I would.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 12 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/media_query.dart]: https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/Displays/Displays.html
https://developer.android.com/guide/topics/resources/more-resources#Dimension

'points' and 'dp' are just terms of art on iOS/Android.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 11 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/media_query.dart]: Oops, the second comment is in the wrong place.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 10 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/media_query.dart]: > Might be worth saying too: if you make a custom widget and it consumes a padding/inset, you're responsible to make sure your child doesn't see it anymore. Otherwise, your child might decide to be funky.

This comment was meant to be here.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 7 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/scaffold.dart]: Good point, updated.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 11 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/media_query.dart]: The MediaQueryData class doc covers this. I separated the point into its own paragraph to make it more obvious:
```
/// The viewInsets and padding values are independent, they're both
/// measured from the edges of the MediaQuery widget's bounds. The
/// bounds of the top level MediaQuery created by [WidgetsApp] are the
/// same as the window that contains the app.
```

**Comment by xster** [comment]
I have trouble keeping up with the changes. Though general LGTM. Feel free to submit when the comments are addressed.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 16]
```diff
@@ -694,6 +697,53 @@ class _FloatingActionButtonTransitionState extends State<_FloatingActionButtonTr
...
+/// ## Troubleshooting
+///
+/// ### Nested Scaffolds
+///
+/// The Scaffold was designed to be the single top level container for
+/// a [MaterialApp] and it's typically not necessary to nest
+/// scaffolds. For example in a tabbed UI, where the
+/// [bottomNavigationBar] is a [TabBar] and the body is a
+/// [TabBarView], you might be tempted to make each tab bar view a
+/// scaffold with a differently titled AppBar. Better to add a
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/scaffold.dart]: uber-nit: The phrase that starts with `Better to...` doesn't seem to be a sentence?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 17]
```diff
@@ -694,6 +697,53 @@ class _FloatingActionButtonTransitionState extends State<_FloatingActionButtonTr
...
+/// listener to the [TabController] that updates the AppBar:
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/scaffold.dart]: Should this clearify that instead of having a separate app bar in each tab there will only be one global app bar for all tabs in this case?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 18]
```diff
@@ -694,6 +697,53 @@ class _FloatingActionButtonTransitionState extends State<_FloatingActionButtonTr
...
+///
+/// ```dart
+/// tabController = TabController(vsync this, length tabCount)..addListener(() {
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/scaffold.dart]: Given the confusion around nested Scaffolds, I am wondering if we should expand this example more so it shows that there is only one AppBar and one Scaffold instantiated.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 19]
```diff
@@ -694,6 +697,53 @@ class _FloatingActionButtonTransitionState extends State<_FloatingActionButtonTr
...
+///
+/// The Scaffold was designed to be the single top level container for
+/// a [MaterialApp] and it's typically not necessary to nest
+/// scaffolds. For example in a tabbed UI, where the
+/// [bottomNavigationBar] is a [TabBar] and the body is a
+/// [TabBarView], you might be tempted to make each tab bar view a
+/// scaffold with a differently titled AppBar. Better to add a
+/// listener to the [TabController] that updates the AppBar:
+///
+/// ```dart
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/scaffold.dart]: Should this code snippet be wrapped by the [snippet tool](https://github.com/flutter/flutter/blob/65d3ddd5d12c5e78a1e3fca843043f99247efb55/dev/snippets/README.md) or at least be under a `## Sample Code` heading so the analyzer catches errors in this snippet?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 20]
```diff
@@ -731,7 +781,8 @@ class Scaffold extends StatefulWidget {
     this.bottomNavigationBar,
     this.bottomSheet,
     this.backgroundColor,
-    this.resizeToAvoidBottomPadding = true,
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/scaffold.dart]: What happened to the default value?

File: packages/flutter/lib/src/material/scaffold.dart [hunk 21]
```diff
@@ -850,15 +903,25 @@ class Scaffold extends StatefulWidget {
   ///  * [showModalBottomSheet], which displays a modal bottom sheet.
   final Widget bottomSheet;
 
-  /// Whether the [body] (and other floating widgets) should size themselves to
-  /// avoid the window's bottom padding.
+  /// This flag is deprecated, please use resizeToAvoidBottomInset
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/scaffold.dart]: `[resizeToAvoidBottomInset]` with square brackets to directly link to it?

File: packages/flutter/lib/src/material/scaffold.dart (hunk 20 above)
Comment (goderbauer) [reply packages/flutter/lib/src/material/scaffold.dart]: Never mind, I see it is now applied in _resizeToAvoidBottomInset.

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 22]
```diff
@@ -30,6 +30,25 @@ enum Orientation {
 /// If no [MediaQuery] is in scope then the [MediaQuery.of] method will throw an
 /// exception, unless the `nullOk` argument is set to true, in which case it
 /// returns null.
+///
+/// MediaQueryData includes two [EdgeInsets] values:
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/media_query.dart]: +1 for adding this explanation.

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 23]
```diff
@@ -91,17 +110,20 @@ class MediaQueryData {
...
+  /// The parts of the display that are completely obscured by system UI,
+  /// typically by the device's keyboard.
+  ///
+  /// When a mobile device's keyboard is visible `viewInsets.bottom`
+  /// corresponds to the top of the keyboard.
+  ///
+  /// This value is independent of the [padding]: both values are
+  /// measured from the edges of the [MediaQuery] widget's bounds. The
+  /// bounds of the top level MediaQuery created by [WidgetsApp] are the
+  /// same as the window (often the mobile device screen) that contains the app.
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/media_query.dart]: Maybe add a "see also" section that links to the explanation given on the top level of MediaQueryData that illustrates the difference between the two?

File: packages/flutter/lib/src/widgets/media_query.dart [hunk 24]
```diff
@@ -91,17 +110,20 @@ class MediaQueryData {
...
-  /// The number of physical pixels on each side of the display rectangle into
-  /// which the application can render, but which may be partially obscured by
-  /// system UI (such as the system notification area), or or physical
-  /// intrusions in the display (e.g. overscan regions on television screens or
-  /// phone sensor housings).
+  /// The parts of the display that are partially obscured by system UI,
+  /// typically by the hardware display "notches" or the system status bar.
   ///
   /// If you consumed this padding (e.g. by building a widget that envelops or
   /// accounts for this padding in its layout in such a way that children are
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/media_query.dart]: Should the doc for padding somehow also mention its independence from viewInsets and how the two relate (even if it's only in a "see also" bullet)?

**Review by goderbauer — COMMENTED** [review]
Implementation LGTM. Just come comments about dart doc comments...

File: packages/flutter/lib/src/material/scaffold.dart (hunk 19 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/scaffold.dart]: I've put it under a sample code heading. I don't want to emphasize it as much the basic scaffold usage example so it's not a snippet.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 18 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/scaffold.dart]: Given the number of potentially worthy scaffold examples we could include here, I'd really prefer to not make a big (bigger) example out of this.

File: packages/flutter/lib/src/material/scaffold.dart (hunk 21 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/scaffold.dart]: Yes, done.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 23 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/media_query.dart]: Good idea, done.

File: packages/flutter/lib/src/widgets/media_query.dart (hunk 24 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/media_query.dart]: I added a see also bullet per the previous comment.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 25]
```diff
@@ -727,10 +734,15 @@ class _FloatingActionButtonTransitionState extends State<_FloatingActionButtonTr
...
+/// listener to the [TabController] that updates the AppBar.
+///
+/// ## Sample Code
+///
+/// Add a listener to the app's tab controller so that the [AppBar] title of the
+/// app's one and only scaffold is reset each time a new tab is selected.
 ///
 /// ```dart
-/// tabController = TabController(vsync this, length tabCount)..addListener(() {
+/// tabController = TabController(vsync tickerProvider, length tabCount)..addListener(() {
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/scaffold.dart]: Is this one missing `:` after `vsync` and `length`?

Comment (HansMuller) [reply packages/flutter/lib/src/material/scaffold.dart]: Yes and oops. Thanks for pointing that out so quickly.
