### PR TITLE
Fix SliverMainAxisGroup layout in reverse

### LINKED ISSUE #145068: `SliverMainAxisGroup` does not work as expected when placed in a reverse scroll view
### Steps to reproduce

1. Run the example, see a green box rendered at the top
2. Change `home: MainAxisGroupPage(),` to `home: RegularPage(),`
3. Hot reload
4. See the green box rendered (correctly), at the bottom.

### Expected results

I expect both of these examples to be equivalent i.e. that using a `SliverMainAxisGroup` or placing all slivers directly in the `CustomScrollView` would produce the same result. But this doesn't seem to be true.

### Actual results

Slivers are rendered on the wrong side of the viewport, when using `SliverMainAxisGroup` in a reverse scroll view.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MainAxisGroupPage(),
    );
  }
}

class MainAxisGroupPage extends StatelessWidget {
  const MainAxisGroupPage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: CustomScrollView(reverse: true, slivers: [
        SliverMainAxisGroup(slivers: [
          SliverToBoxAdapter(
            child: SizedBox(
              height: 100,
              child: ColoredBox(color: Colors.green),
            ),
          ),
          SliverFillRemaining(
            hasScrollBody: false,
            child: ColoredBox(color: Colors.black54),
          ),
        ]),
      ]),
    );
  }
}

class RegularPage extends StatelessWidget {
  const RegularPage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: CustomScrollView(reverse: true, slivers: [
        SliverToBoxAdapter(
          child: SizedBox(
            height: 100,
            child: ColoredBox(color: Colors.green),
          ),
        ),
        SliverFillRemaining(
          hasScrollBody: false,
          child: ColoredBox(color: Colors.black54),
        ),
      ]),
    );
  }
}
```
</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-arm64, locale en-SI)
    • Flutter version 3.19.3 on channel stable at /Users/.../Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (5 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/.../Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.88.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.112

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/145068

The original tests for SliverMainAxisGroup did not actually check where the child was painted (#126596).

Followed the same pattern in RenderSliverMultiBoxAdaptor:

https://github.com/flutter/flutter/blob/11c034f0371eb28576d41a0c218ccae6b38e7702/packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart#L666

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 1]
```diff
@@ -274,8 +274,8 @@ class RenderSliverMainAxisGroup extends RenderSliver with ContainerRenderObjectM
       assert(() {
         if (child != null && maxPaintExtent.isInfinite) {
           throw FlutterError(
-            'Unreachable sliver found, you may have a sliver behind '
-            'a sliver with infinite extent. '
+            'Unreachable sliver found, you may have a sliver following '
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/sliver_group.dart:277]: `following` - NICE

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 2]
```diff
@@ -327,12 +327,50 @@ class RenderSliverMainAxisGroup extends RenderSliver with ContainerRenderObjectM
...
+      if (addExtent) {
+        childOffset += mainAxisUnit * child.geometry!.paintExtent;
+      }
+
       if (child.geometry!.visible) {
-        final SliverPhysicalParentData childParentData = child.parentData! as SliverPhysicalParentData;
-        context.paintChild(child, offset + childParentData.paintOffset);
+        context.paintChild(child, childOffset);
       }
       child = childBefore(child);
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/sliver_group.dart:375]: I don't completely understand this. Are we cycling backwards through every sliver group child, even though at some point they will no longer be `child.geometry!.visible`? It seems like a short-circuit would be useful although maybe no short-circuit is possible?

File: packages/flutter/lib/src/rendering/sliver_group.dart [hunk 3]
```diff
@@ -327,12 +327,50 @@ class RenderSliverMainAxisGroup extends RenderSliver with ContainerRenderObjectM
...
+        originOffset = offset;
+        addExtent = false;
+      case AxisDirection.left:
+        mainAxisUnit = const Offset(-1.0, 0.0);
+        crossAxisUnit = const Offset(0.0, 1.0);
+        originOffset = offset + Offset(geometry!.paintExtent, 0.0);
+        addExtent = true;
+    }
 
+    RenderSliver? child = lastChild;
```
Comment (jellynoone) [inline packages/flutter/lib/src/rendering/sliver_group.dart:360]: @Piinks Thank you for working on this!

Note, I'm not well versed with slivers so I might be wrong here, but wouldn't this paint children in reverse order?
Wouldn't a layout like this be rendered incorrectly then? i.e. the blue box would be rendered beneath the brown box due to a paint transform being applied.
```dart
SliverMainAxisGroup(slivers: [
  const SliverToBoxAdapter(
    child: ColoredBox(
      color: Colors.brown,
      child: SizedBox(height: 100),
    ),
  ),
  SliverToBoxAdapter(
    child: Transform.translate(
      offset: const Offset(0, -50),
      child: const ColoredBox(
        color: Colors.blue,
        child: SizedBox(height: 100),
      ),
    ),
  ),
]);
```

However, it seems slivers in general are painted in reverse.

I tested the following code on stable and I'd assume all to render the same but they don't.
`PageThroughList` renders as expected, while `MainAxisGroupPage` and `PageThroughSlivers` render the blue box below the brown one.
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MainAxisGroupPage(),
    );
  }
}

class MainAxisGroupPage extends StatelessWidget {
  const MainAxisGroupPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(slivers: [
        SliverMainAxisGroup(slivers: [
          const SliverToBoxAdapter(
            child: ColoredBox(
              color: Colors.brown,
              child: SizedBox(height: 100),
            ),
          ),
          SliverToBoxAdapter(
            child: Transform.translate(
              offset: const Offset(0, -50),
              child: const ColoredBox(
                color: Colors.blue,
                child: SizedBox(height: 100),
              ),
            ),
          ),
        ]),
      ]),
    );
  }
}

class PageThroughSlivers extends StatelessWidget {
  const PageThroughSlivers({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(slivers: [
        const SliverToBoxAdapter(
          child: ColoredBox(
            color: Colors.brown,
            child: SizedBox(height: 100),
          ),
        ),
        SliverToBoxAdapter(
          child: Transform.translate(
            offset: const Offset(0, -50),
            child: const ColoredBox(
              color: Colors.blue,
              child: SizedBox(height: 100),
            ),
          ),
        ),
      ]),
    );
  }
}

class PageThroughList extends StatelessWidget {
  const PageThroughList({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(slivers: [
        SliverList.list(children: [
          const ColoredBox(
            color: Colors.brown,
            child: SizedBox(height: 100),
          ),
          Transform.translate(
            offset: const Offset(0, -50),
            child: const ColoredBox(
              color: Colors.blue,
              child: SizedBox(height: 100),
            ),
          ),
        ]),
      ]),
    );
  }
}
```
Should I file another issue or is this working as expected?

File: packages/flutter/lib/src/rendering/sliver_group.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter/lib/src/rendering/sliver_group.dart:375]: We paint them in reverse because the group supports overlapping widgets like pinned app bars. Paint order stacks, so if we painted from first to last, a pinned app bar would be covered by the slivers it is meant to overlap. We only paints slivers that are visible to be efficient.

Comment (HansMuller) [reply packages/flutter/lib/src/rendering/sliver_group.dart:375]: I think what you're saying is that a short-circuit exit from the loop isn't possible because the visibility of one child doesn't imply anything about previous children?

Comment (Piinks) [reply packages/flutter/lib/src/rendering/sliver_group.dart:375]: Correct. :)

**Review by HansMuller — APPROVED** [review]
LGTM
