### PR TITLE
InteractiveViewer should call onInteractionUpdate even when gesture is disabled

### LINKED ISSUE #77455: InteractiveViewer onInteractionUpdate does not get called when panEnabled is false.
## Steps to Reproduce

1. Add InteractiveViewer widget
2. Use the `onInteractionUpdate` property
3. Set the `panEnabled` property to `false`
4. Trigger the GestureDetector by using a `pan` gesture
5. See that `onInteractionUpdate` does not get called

**Expected results:** 

Make `onInteractionUpdate` get called, even when `panEnabled` is false.

**Actual results:** 

The `onInteractionUpdate` property does not get called, although this case is described in the `onInteractionUpdate` docs:
https://github.com/flutter/flutter/blob/c5a4b4029c0798f37c4a39b479d7cb75daa7b05c/packages/flutter/lib/src/widgets/interactive_viewer.dart#L259-L260

<details>
  <summary>Details/Findings</summary>

 In the `InteractiveViewer` source, I found this line:
https://github.com/flutter/flutter/blob/c5a4b4029c0798f37c4a39b479d7cb75daa7b05c/packages/flutter/lib/src/widgets/interactive_viewer.dart#L798-L800

The `_gestureIsSupported` looks like this:
https://github.com/flutter/flutter/blob/c5a4b4029c0798f37c4a39b479d7cb75daa7b05c/packages/flutter/lib/src/widgets/interactive_viewer.dart#L729-L742

So if the GestureType is `pan` it returns the value of the `panEnabled` property, which is `false` in this case.

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale
    de-AT)
    • Flutter version 2.0.1 at /Users/patrick/Applications/flutter
    • Framework revision c5a4b4029c (2 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/patrick/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone von Patrick (mobile) • 74fd9232bceb37fcaffe76b271f3568b95d9bbf5 •
      ios            • iOS 14.4
    • Chrome (web)                • chrome                                   •
      web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
InteractiveViewer provides onInteractionStart/Update/End events so that users can get information about gestures happening on the child without running into problems with overlapping GestureDetectors.  This information should be provided even when the gesture is disabled, and it is documented as such.  However, onInteractionUpdate wasn't being called.  This PR fixes it.

Closes https://github.com/flutter/flutter/issues/77455

### CODE REVIEW

File: packages/flutter/lib/src/widgets/interactive_viewer.dart [hunk 1]
```diff
@@ -781,6 +781,12 @@ class _InteractiveViewerState extends State<InteractiveViewer> with TickerProvid
   // Handle an update to an ongoing gesture. All of pan, scale, and rotate are
   // handled with GestureDetector's scale gesture.
   void _onScaleUpdate(ScaleUpdateDetails details) {
+    widget.onInteractionUpdate?.call(ScaleUpdateDetails(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/interactive_viewer.dart:784]: Is there a reason a new `ScaleUpdateDetails` has to be constructed instead of just passing `details` to the callback?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/interactive_viewer.dart:784]: The [documentation](https://master-api.flutter.dev/flutter/widgets/InteractiveViewer/onInteractionUpdate.html) states:

> At the time this is called, the TransformationController will have already been updated to reflect the change caused by the interaction. 

Is the statement still true?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/interactive_viewer.dart:784]: About ScaleUpdateDetails: The reason was that I didn't want to pass things that weren't being applied, like independent vertical and horizontal scales.  However, given that I call this even when all interaction is disabled, I think you're right and I should just pass everything.

About the docs: You're right, thanks for catching that.  I think I should actually keep the behavior as it is documented.  I'll move my calls to onInteractionUpdate.

**Review by LongCatIsLooong — APPROVED** [review]
