### PR TITLE
Fixed Cupertino Switch Demo

### LINKED ISSUE #27527: Flutter Gallery Sample Cupertino Enabled switch is shown as disabled.
Bug Line : https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/cupertino/cupertino_switch_demo.dart#L65

### PR DESCRIPTION
**Pull request by Kartik1607**
Fix : https://github.com/flutter/flutter/issues/27527

### CODE REVIEW

File: examples/flutter_gallery/lib/demo/cupertino/cupertino_switch_demo.dart [hunk 1]
```diff
@@ -62,7 +62,7 @@ class _CupertinoSwitchDemoState extends State<CupertinoSwitchDemo> {
                         onChanged: null,
                       ),
                       Text(
-                        'Disabled'
+                        'Enabled'
```
Comment (xster) [inline examples/flutter_gallery/lib/demo/cupertino/cupertino_switch_demo.dart]: Understood, if you'd like to help us clean this up, let's name the first one 'Enabled - On', this one 'Disabled - On' and the next one 'Disabled - Off'.

**Comment by xster** [comment]
Thanks LGTM
