### PR TITLE
Text selection menu show/hide cases

### LINKED ISSUE #33293: TextField property  autofocus: true ，Don't show ‘cut paste’ view
## Steps to Reproduce

1. input string is null
2. autofocus: true
3. long click not show ‘paste cut’ view

## Code
```
TextField(
                    autofocus: true,
                    onSubmitted: _invitationCommit,
                    enabled: true,
                    controller: _textController,
                    maxLength: 8,
                    maxLines: 1,
                    style: TextStyle(
                      fontSize: flexible(context, 18.0),
                      height: 1.0,
                      color: Colors.black,
                      fontWeight: FontWeight.bold,
                    ),
                    decoration: InputDecoration.collapsed(
                      hintText: '',
                      filled: true,
                      fillColor: Colors.white,
                      border: InputBorder.none,
                    ).copyWith(counterText: ''),
                    keyboardType: TextInputType.numberWithOptions(),
                  ),
```
## flutter --version

```
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (3 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

### LINKED ISSUE #34215: Can't trigger paste toolbar when empty text for TextField
## Steps to Reproduce

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Column(
            children: <Widget>[
              Text('input 1'),
              TextField(
                autofocus: true,
              ),
              Text('input 2'),
              TextField()
            ],
          ),
        ),
      ),
    );
  }
}

```

#### empty text case
1. run example and make sure you have a copied text
2. long tap on textfield, the paste toolbar doesn't show up. (this is a bug)
3. double tap on textfield, the paste toolbar doesn't show up. (this is a bug)
4. type a word, and do step 2 and 3, you can get it in both steps.

#### switch textfield case

1. run example and make sure you have a copied text
2. assume current focus is on first field.
3. long tap on text field 1, the paste toolbar doesn't show up. (this is a bug)
4. tap on text field to focus on it, long tap on it and the paste toolbar show up.
5. you can't hide the toolbar anymore except close keyboard/type words/change focus. (this is a bug)

already tried on 1.7.0, 1.7.3 and today's master branch. no lucky. : (

## Logs

```
$ flutter analyze
Analyzing flutter...
No issues found! (ran in 13.1s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel master, v1.7.2-pre.108, on Mac OS X 10.14.5 18F132, locale en-TW)
    • Flutter version 1.7.2-pre.108 at /Users/jerry/Documents/project/flutter
    • Framework revision e9ca112e44 (5 hours ago), 2019-06-10 19:17:55 -0700
    • Engine revision 4c0daaca27
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 7f146e431e)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jerry/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7830

[✓] Connected device (2 available)
    • iPhone Xs • B14E00B6-35BA-4FBE-8CCB-340589DEAC94 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

### LINKED ISSUE #35837: text selection toolbar options is not shown on long press CupertinoTextField Widget !!
with `enableInteractiveSelection: true,`  cut/copy/paste menu must be showed as mentioned in documentation in :
https://api.flutter.dev/flutter/cupertino/CupertinoTextField/enableInteractiveSelection.html
but i can only find the two default options as showed in picture 
https://ibb.co/j55PhdY

it can only shown in double tap not long press!!!

## Logs

```
`CupertinoTextField(
                                  clearButtonMode: OverlayVisibilityMode.always,
                                  enableInteractiveSelection: true,
                                  expands: true,
                                  controller: _noteController,
                                  style: TextStyle(
                                      color: StyleCustom.txtPrimary,
                                      fontSize: 16.0),
                                  maxLines: null,
                                  minLines: null,
                                  placeholder: 'write your note here',
                                  decoration: BoxDecoration(),
                                  onChanged: (String value) {
                                    debugPrint(value);
                                  },
                                ),`
```

```
`[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at C:\src\flutter
    • Framework revision b712a172f9 (4 hours ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\midos\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Java\jdk1.8.0_211\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.3
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7479.14

[√] VS Code, 64-bit edition (version 1.36.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • COR L29 • XTX7N18A31001552 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.`
```

### PR DESCRIPTION
**Pull request by justinmc**
## Description

There are various situations, described in the linked issues, where the text selection menu is not shown/hidden when it should be.  This PR aims to get all cases right.

## Related Issues

Closes https://github.com/flutter/flutter/issues/34215
Closes https://github.com/flutter/flutter/issues/33293
Probably should close https://github.com/flutter/flutter/issues/35837 too

### CODE REVIEW

File: packages/flutter/lib/src/material/text_field.dart [hunk 1]
```diff
@@ -775,6 +775,7 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
     }
     _requestKeyboard();
     _confirmCurrentSplash();
+    _editableTextKey.currentState.hideToolbar();
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_field.dart]: Fix 1/2: This fixes the problem where the selection menu could get stuck open.  I had to add a check to `hideToolbar` to make sure that we're not hiding a toolbar that's already hidden, but it seems like that probably should have been there anyway.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -1442,7 +1442,7 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
       _showCaretOnScreen();
       if (!_value.selection.isValid) {
         // Place cursor at the end if the selection is invalid when we receive focus.
-        widget.controller.selection = TextSelection.collapsed(offset: _value.text.length);
+        _handleSelectionChanged(TextSelection.collapsed(offset: _value.text.length), renderEditable, SelectionChangedCause.tap);
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Fix 2/2: This fixes the case where an autofocused field couldn't ever display its selection menu.  The reason was that the menu was never created.

However, this had an implication in our tests.  I had to wrap a bunch of pumped test widgets in `MaterialApp`, because otherwise I was getting an error that there was no parent `Overlay` widget when it tried to create the selection menu.  See the changes below.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Also, I just remembered that I used `SelectionChangedCause.tap` and it felt a bit hacky.  This isn't isn't caused by a tap.  Really, it's called when the widget is rebuilt and is automatically focused.  Should I add a new value to the `SelectionChangedCause` enum?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -1495,6 +1495,9 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
 
   @override
   void hideToolbar() {
+    if (_selectionOverlay == null || !_selectionOverlay.toolbarIsVisible) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/editable_text.dart]: I am not sure if it is necessary, we might also want to check _selectionOverlay.handlesarevisible

File: packages/flutter/test/material/text_field_test.dart [hunk 4]
```diff
@@ -92,19 +92,21 @@ Widget overlayWithEntry(OverlayEntry entry) {
...
-      MaterialLocalizationsDelegate(),
-    ],
-    child: Directionality(
-      textDirection: TextDirection.ltr,
-      child: MediaQuery(
-        data: const MediaQueryData(size: Size(800.0, 600.0)),
-        child: Center(
-          child: Material(
-            child: child,
+  return MaterialApp(
```
Comment (chunhtai) [inline packages/flutter/test/material/text_field_test.dart]: I think it is good to wrap textfield in overlay, but I am curious why we need to do it here and all the other test.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/editable_text.dart]: I feel a bit hacky too, but I can't think of a good cause either. I wonder if it make sense to leave it null?

File: packages/flutter/lib/src/material/text_field.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/material/text_field.dart]: It might be safer to turn it off at the start of the function? although I don't think we turn on toolbar in selectPosition

Comment (justinmc) [reply packages/flutter/lib/src/material/text_field.dart]: I think I like putting it at the top more, I'll make that change.  It seems to work fine.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Good idea.  I thought it couldn't be null for some reason, but it seems to work fine.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart]: I just tried playing around with it and using `handlesAreVisible` and I think it has to stay as-is.  The use case is tapping to close the selection menu in an empty text field.  In that case no handles are shown, only the toolbar, but we still want to close the toolbar on tap.  However I also don't want to call `selectionOverlay.hide` when there is no selection overlay, like tapping on an empty field without the menu up.

File: packages/flutter/test/material/text_field_test.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart]: These tests started failing after I started calling `_handleSelectionChanged`.  The reason is that now the selection menu is being created, and it asserts that an Overlay exists above it.  Without the MaterialApp there was no Overlay, and the assertion would trigger.

**Comment by chunhtai** [comment]
Can you also add a regression test regarding https://github.com/flutter/flutter/issues/34215 ?

**Comment by justinmc** [comment]
Good call, I totally forgot to test those cases.  I will add a couple to make sure they're covered.

**Comment by justinmc** [comment]
@chunhtai Updated with the tests.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 5]
```diff
@@ -3228,5 +3228,28 @@ void main() {
         ),
       );
     });
+
+    testWidgets(
```
Comment (chunhtai) [inline packages/flutter/test/cupertino/text_field_test.dart]: This test is passing without the patch. Is the original issue already resolved?

Comment (justinmc) [reply packages/flutter/test/cupertino/text_field_test.dart]: After looking into this, the "single tap hides" test was passing because of strangeness with the tap location.  Using a direct `longPress(textFieldFinder)` made the test fail on master and pass in this branch.

For the other test, "long press on autofocused", I could not get it to fail on master no matter what I tried.  However, trying a sample app, the behavior looked as if the test should definitely fail.  I gave up trying to make it fail and instead wrote an integration test that fails on master and passes on this branch.

**Comment by justinmc** [comment]
@chunhtai Updated with tests that fail on master.

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 5 above)
Comment (chunhtai) [reply packages/flutter/test/cupertino/text_field_test.dart]: I think i know what is going on.
When you use longPressAt(textOffsetToPosition(tester, 0)), it will tap at the start of the text which is also part of the selection handle. this will trigger _handleSelectionHandleTapped which toggle the toolbar off. That is why it still passing in master.

As for long press on autofocused, add an additional pump after the pump widget will fail the test as the on focus callback will update the selection from the default (-1, -1) to (0,0) but it take one frame to propagate down to renderEditable. While the long press started, the renderEditable is still has selection(-1,-1) which allow it to update its selection

Comment (justinmc) [reply packages/flutter/test/cupertino/text_field_test.dart]: Brilliant, that did in fact make it fail on master.  Thanks so much.  I will make that change and then remove the e2e test (since it's much slower).

**Comment by justinmc** [comment]
@chunhtai Update with your fix for the test that wasn't failing on master, thanks!

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 6]
```diff
@@ -3228,5 +3228,28 @@ void main() {
...
+              child: ConstrainedBox(
+                constraints: BoxConstraints.loose(const Size(200, 200)),
+                child: const CupertinoTextField(
+                  autofocus: true,
+                ),
+              ),
+            ),
+          ),
+        );
+
```
Comment (chunhtai) [inline packages/flutter/test/cupertino/text_field_test.dart]: it requires a pump here

File: packages/flutter/test/material/text_field_test.dart [hunk 7]
```diff
@@ -5341,6 +5343,63 @@ void main() {
...
+            child: Center(
+              child: TextField(
+                autofocus: true,
+                controller: controller,
+              ),
+            ),
+          ),
+        ),
+      );
+
```
Comment (chunhtai) [inline packages/flutter/test/material/text_field_test.dart]: same here

**Comment by justinmc** [comment]
@chunhtai Whoops sorry, I think I lost the pumps I added when I was switching to master to try it out.  Fixed.

File: packages/flutter/test/material/text_field_test.dart [hunk 8]
```diff
@@ -5341,6 +5343,64 @@ void main() {
...
+            child: Center(
+              child: TextField(
+                autofocus: true,
+                controller: controller,
+              ),
+            ),
+          ),
+        ),
+      );
+      await tester.pump();
```
Comment (chunhtai) [inline packages/flutter/test/material/text_field_test.dart]: nit: It might be more clear to add a comment describe why we need a pump here

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 9]
```diff
@@ -3228,5 +3228,29 @@ void main() {
...
+              child: ConstrainedBox(
+                constraints: BoxConstraints.loose(const Size(200, 200)),
+                child: const CupertinoTextField(
+                  autofocus: true,
+                ),
+              ),
+            ),
+          ),
+        );
+        await tester.pump();
```
Comment (chunhtai) [inline packages/flutter/test/cupertino/text_field_test.dart]: nit: same as below.

**Review by chunhtai — APPROVED** [review]
LGTM with a minor suggestion
