### PR TITLE
[flutter_tools] support all engine debugging options with FLUTTER_ENGINE_SWITCH environment variables

### LINKED ISSUE #46005: Desktop/embedder shells need an affordance for enabling dart profiling
The switch [--enable-dart-profiling](https://github.com/flutter/engine/blob/096ba6892a435a9149b0406592eab7ba866bceb8/shell/common/switches.h#L86) is used to configure the dart vm to record profiles in the vmservice. Currently this option is off by default, but is forced on via the [launch intent](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L572) for Android/iOS devices. The desktop shells lack a similar affordance, and besides passing a string value through the FlutterViewController, currently have no way to enable profiling.

For example, in the macOS window code:

```switch
let arguments = [
   "--enable-dart-profiling"
]
let project = FlutterDartProject.init()
project.engineSwitches = arguments
return FlutterViewController.init(project: project)
```

We could enable profiling by default for debug and profile builds in the desktop shells in flutter/engine. This would require a way to detect the difference between "profile" AOT and "release" AOT. I'm not sure what happens if this flag is specified in a product build without a vmservice - maybe it is a no-op? I'm also not certain why it isn't enabled by default even for Android/iOS.

EDIT: This may need to also include `--trace-systrace` and `--trace-skia`

cc @chinmaygarde @stuartmorgan

### LINKED ISSUE #58882: --cache-sksl cannot be provided to desktop embedders
The tool cannot provide any runtime arguments to desktop embedders, and since --cache-sksl is not the default it cannot be enabled.

We need to either enable it by default for debug modes, or allow the dart vm service to enable it.

### LINKED ISSUE #66532: Most Debugging Options are discarded for desktop
Most debugging flags are discarded when targeting desktop. A complete list of such flags can be found [here](https://github.com/flutter/flutter/blob/51ededb92fd7ad9fb3c5cb8733d9c47417a9df5c/packages/flutter_tools/lib/src/commands/run.dart#L392-L428).

This makes it super annoying to debug low-level issues like those with Skia. The fact that no warning is emitted also wasted much of my time figuring out why the flags don't work.

In addition to the CLI discarding the flags, the engine also refuses to accept such flags, at least on Linux. Flutter engine already has a parser for command line option, so this shouldn't be too hard to fix.

Related: #52676

## Proposed fix

1. Make the Linux accept options related to Flutter, not only options for GTK. Same applies for other desktop platforms.
2. Add logic for passing the debugging options to [`DesktopDevice.startApp`](https://github.com/flutter/flutter/blob/1fef5912cf778f9b25767f14fd66875400e3e8b5/packages/flutter_tools/lib/src/desktop_device.dart#L107)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Configure application to run on Linux.
3. `flutter run --trace-skia -d linux`

**Expected results:** Skia Trace events should be emitted.

**Actual results:** No such events are actually emitted.

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Allow providing all debugging options to the desktop engine via the FLUTTER_ENGINE_SWITCH_ environment variables. 

Fixes https://github.com/flutter/flutter/issues/66532
Fixes https://github.com/flutter/flutter/issues/46005
Fixes https://github.com/flutter/flutter/issues/58882

The underling engine changes have already landed for Windows, macOS, but linux is still in progress

### CODE REVIEW

File: packages/flutter_tools/lib/src/desktop_device.dart [hunk 1]
```diff
@@ -137,6 +138,7 @@ abstract class DesktopDevice extends Device {
       <String>[
         executable,
       ],
+      environment: _computeEnvironment(debuggingOptions, traceStartup, route),
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/desktop_device.dart:141]: Do these options work in release mode on other platforms? Since they won't currently on desktop, maybe we should see if this is non-empty and if the build mode is release, output a warning that the options will be ignored and to file an issue describing their use case.

File: packages/flutter_tools/lib/src/desktop_device.dart [hunk 2]
```diff
@@ -202,6 +204,92 @@ abstract class DesktopDevice extends Device {
...
+
+  /// Computes a set of environment variables used to pass debugging information
+  /// to the engine without interfering with application level command line
+  /// arguments.
+  ///
+  /// The format of the environment variables is:
+  ///   * FLUTTER_ENGINE_SWITCHES to the number of switches.
+  ///   * FLUTTER_ENGINE_SWITCH_<N> (indexing from 1) to the individual switches.
+  Map<String, String> _computeEnvironment(DebuggingOptions debuggingOptions, bool traceStartup, String route) {
+    int flags = 1;
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/desktop_device.dart:216]: Wouldn't it be clearer to start this as zero, increment flags at the start of `addFlag` instead of the end, and not have to subtract in `finish`?

File: packages/flutter_tools/lib/src/desktop_device.dart [hunk 3]
```diff
@@ -202,6 +204,92 @@ abstract class DesktopDevice extends Device {
...
+    addFlag('enable-background-compilation=true');
+
+    if (traceStartup) {
+      addFlag('trace-startup=true');
+    }
+    if (route != null) {
+      addFlag('route=$route');
+    }
+    if (debuggingOptions.enableSoftwareRendering) {
+      addFlag('enable-software-rendering=true');
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/desktop_device.dart:237]: This won't actually work currently, but I guess it's harmless to pass anyway, and then it'll be in place already when implemented on the engine side.

File: packages/flutter_tools/lib/src/desktop_device.dart [hunk 4]
```diff
@@ -202,6 +204,92 @@ abstract class DesktopDevice extends Device {
...
+    }
+    if (debuggingOptions.cacheSkSL) {
+      addFlag('cache-sksl=true');
+    }
+    if (debuggingOptions.purgePersistentCache) {
+      addFlag('purge-persistent-cache=true');
+    }
+    if (!debuggingOptions.debuggingEnabled) {
+      finish();
+      return environment;
```
Comment (stuartmorgan) [inline packages/flutter_tools/lib/src/desktop_device.dart:265]: Skimming, I almost missed that this was an early return instead of just another flag. Maybe wrap all the rest in `if (debuggingOptions.debuggingEnabled) {...}` instead of early return so it's clearer?

(As a concrete issue, I think there's a good chance that if I were ever to add anything to the flags here as currently written, I would accidentally add it to the end of the function not realizing that it wouldn't always get there.)

File: packages/flutter_tools/lib/src/desktop_device.dart (hunk 3 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/desktop_device.dart:237]: Do we have an issue filled? I could add that in a comment

File: packages/flutter_tools/lib/src/desktop_device.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/desktop_device.dart]: done

File: packages/flutter_tools/lib/src/desktop_device.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/desktop_device.dart:141]: The tooling will already ignore the unsupported values when constructing the debugging options object:

https://github.com/flutter/flutter/blob/90bc7c64dd3c02922e4bad49f6001fe32b86ae54/packages/flutter_tools/lib/src/commands/run.dart#L374

That seems like a reasonable place to insert some logging to warn users if they are passing flags that have no effect.

Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/desktop_device.dart:141]: Filled https://github.com/flutter/flutter/issues/67315

File: packages/flutter_tools/lib/src/desktop_device.dart (hunk 4 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/desktop_device.dart]: Updated to only have a single return

File: packages/flutter_tools/lib/src/desktop_device.dart (hunk 3 above)
Comment (stuartmorgan) [reply packages/flutter_tools/lib/src/desktop_device.dart:237]: Actually, now that I look closer it might be that this is internal enough that it does work. I was thinking of the embedding using software mode at the embedder.h level, which may not be the same thing. Let's just leave this as-is.

**Review by stuartmorgan-g — APPROVED** [review]
LGTM!
