### PR TITLE
Make `TextSpan` hit testing precise.

### LINKED ISSUE #131435: InlineText's GestureDetector is always full-width
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

  1. Create a TextSpan with a `recognizer` property, or use the app below.
  2. Run the app on a platform with a mouse.
  3. Hover over the space to the right of the TextSpan.

### Expected results

Only "example.com" is tappable, as in a typical link on the web, for example.  Here I've highlighted the area I expect to be tappable in blue (with an image editor, not with Flutter).

Screenshot from 2023-07-27 12-59-33-small

### Actual results

The entire width, highlighted in blue, is tappable.

Screenshot from 2023-07-27 12-59-33

Related:
https://github.com/flutter/flutter/issues/27293
https://github.com/flutter/flutter/issues/13211
https://github.com/flutter/flutter/pull/125927

### Code sample

<details>

<summary>Example code</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RichText(
              text: TextSpan(
                style: const TextStyle(
                  color: Colors.black,
                ),
                text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. ',
                children: [
                  TextSpan(
                    text: 'example.com',
                    style: const TextStyle(
                      color: Colors.blue,
                    ),
                    recognizer: TapGestureRecognizer()..onTap = () {},
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</summary>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel master, 3.13.0-10.0.pre.49, on Debian GNU/Linux rodete 6.3.7-1rodete2-amd64, locale en_US.UTF-8)
    ! Upstream repository git@github.com:justinmc/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:justinmc/flutter.git to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2022.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/131435, #104594, #43400
Needs https://github.com/flutter/engine/pull/48774 (to fix the web test failure).

Currently the method we use for text span hit testing `TextPainter.getPositionForOffset` always returns the closest `TextPosition`, even when the given offset is far away from the text. 

The new TextPaintes method tells you the layout bounds (`width =  letterspacing / 2 + x_advance + letterspacing / 2`, `height = font ascent + font descent`) of a character, the PR changes the hit testing implementation such that a TextSpan is only considered hit if the point-down event landed in one of it's character's layout bounds.

Potential issues:

1. In theory since the text is baseline aligned, we should use the max ascent and max descent of each character to calculate the height of the text span's hit-test region, in case some characters in the span have to fall back to a different font, but that will be slower and it typically doesn't make a huge difference. 

This is a breaking change. It also introduces a new finder and a new method `WidgetTester.tapOnText`: `await tester.tapOnText('string to match')` for ease of migration.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 1]
```diff
@@ -50,6 +52,54 @@ enum TextOverflow {
...
 
+/// The measurements of a character (or a sequence of visually connected
+/// characters) within a paragraph.
+///
+/// See also:
+///
+///  * [TextPainter.getClosestGlyphForOffset], which finds the [GlyphInfo] of
+///    the glyph(s) onscreen that's closest to the given [Offset].
+@immutable
+final class GlyphInfo {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/painting/text_painter.dart:63]: Had to copy the code from dart:ui since I forgot to expose the constructor. I'll add the constructor there and remove this class.

File: packages/flutter/test/rendering/editable_test.dart [hunk 2]
```diff
@@ -1184,8 +1188,118 @@ void main() {
...
+          textSelectionDelegate: delegate,
+          selection: const TextSelection.collapsed(offset: 0),
+        );
+        layout(renderEditable, constraints:  BoxConstraints.tightFor(width: 100.0 + _caretMarginOf(renderEditable)));
+
+        BoxHitTestResult result;
+
+        // Hit-testing the first line
+        // First A
+        // ignore: invalid_use_of_protected_member
```
Comment (goderbauer) [inline packages/flutter/test/rendering/editable_test.dart:1219]: Not super excited about these ignores. Any way to restructure the test to avoid this? Can you just test the public hit test entry point? If not, potentially create a test subclass of RenderEditable to expose them as a last resort.

Also: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#comment-all-ignores

(here and everywhere else in the PR)

File: packages/flutter/test/rendering/editable_test.dart [hunk 3]
```diff
@@ -1184,8 +1188,118 @@ void main() {
...
+
+        // Not even remotely close.
+        // ignore: invalid_use_of_protected_member
+        expect(renderEditable.hitTestChildren(result = BoxHitTestResult(), position: const Offset(9999.0, 9999.0)), isFalse);
+        expect(result.path.map((HitTestEntry<HitTestTarget> entry) => entry.target as TextSpan), <TextSpan>[]);
+      });
+
+      test('TextSpan Hit testing with text justification', () {
+        const TextSpan textSpanA = TextSpan(text: 'A ');      // The space is a word break.
+        const TextSpan textSpanB = TextSpan(text: 'B\u200B'); // The ZWS is used as a line break.
```
Comment (goderbauer) [inline packages/flutter/test/rendering/editable_test.dart:1260]: ZWS = https://en.wikipedia.org/wiki/Zero-width_space ?

Maybe spell it out?

File: packages/flutter/test/widgets/slivers_padding_test.dart [hunk 4]
```diff
@@ -618,7 +618,15 @@ void main() {
...
+void hitsText(HitTestResult hitTestResult, String text) {
+  switch (hitTestResult.path.first.target) {
+    case final TextSpan span:
+      expect(span.text, text);
+    case final RenderParagraph paragraph:
+      final InlineSpan span = paragraph.text;
+      expect(span, isA<TextSpan>());
+      expect((span as TextSpan).text, text);
+    case final HitTestTarget target:
+      expect(target, anyOf(isA<TextSpan>(), isA<RenderParagraph>()));
```
Comment (goderbauer) [inline packages/flutter/test/widgets/slivers_padding_test.dart:630]: Shouldn't this case somehow use the `text` parameter? Otherwise, the method is kinda misleading if things can pass without verifying the `text` was hit.

File: packages/flutter_test/lib/src/finders.dart [hunk 5]
```diff
@@ -677,6 +700,23 @@ class CommonSemanticsFinders {
...
+final class CommonTextRangeFinders {
+  const CommonTextRangeFinders._();
+
+  /// Finds all occurrances of the given `substring` in the static text and
+  /// returns the [TextRange]s.
+  ///
+  /// If the `skipOffstage` argument is true (the default), then this skips
+  /// static text inside widgets that are [Offstage], or that are from inactive
+  /// [Route]s.
+  FinderBase<TextRangeContext> of(String substring, { bool skipOffstage = true }) {
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/finders.dart:715]: nit: `of` feels awfully generic as a finder name if the plan is to eventually add more TextRange finders here.

File: packages/flutter_test/lib/src/finders.dart [hunk 6]
```diff
@@ -1026,6 +1066,69 @@ abstract class SemanticsFinder extends FinderBase<SemanticsNode> {
   }
 }
 
+/// A base class for creating finders that search for static text rendered by a
+/// [RenderParagraph].
+class _StaticTextRangeFinder extends _MapFinder<TextRangeContext, Element> {
+  /// Creates a new [SemanticsFinder] that will search starting at the given
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/finders.dart:1072]: SemanticsFinder? :P

File: packages/flutter_test/lib/src/finders.dart [hunk 7]
```diff
@@ -1026,6 +1066,69 @@ abstract class SemanticsFinder extends FinderBase<SemanticsNode> {
...
+  @override
+  String describeMatch(Plurality plurality) {
+    return switch (plurality) {
+      Plurality.zero || Plurality.many => 'non-overlapping TextRanges that match the Pattern "${_parent.pattern}"',
+      Plurality.one => 'non-overlapping TextRange that matches the Pattern "${_parent.pattern}"',
+    };
+  }
+}
+
+abstract class _MapFinder<To, From> extends FinderBase<To> {
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/finders.dart:1119]: this only has one usage. Is it worthwhile to extract this abstraction as a concept right now or could this just be inlined in the only class that uses it?

File: packages/flutter_test/test/controller_test.dart [hunk 8]
```diff
@@ -1482,6 +1482,171 @@ void main() {
...
+        ),
+      );
+
+      await expectLater(
+        () => tester.tapOnText(find.textRange.of('match')),
+        throwsA(isFlutterError.having(
+          (FlutterError error) => error.message,
+          'message',
+          stringContainsInOrder(<String>[
+            'A finder that searches for non-overlapping TextRanges that match the Pattern "match". found a matching substring in a static text widget, within TextRange(start: 0, end: 5).',
```
Comment (goderbauer) [inline packages/flutter_test/test/controller_test.dart:1643]: Should "found" be capitalized here since it is at the beginning of a sentence?

File: packages/flutter_test/lib/src/controller.dart [hunk 9]
```diff
@@ -24,6 +25,33 @@ const double kDragSlopDefault = 20.0;
...
+/// Helper function that returns 3 special Offsets within the given `box`, to
+/// try performing hit-testing at.
+Iterable<Offset> _testOffsetsForEachTextBox(TextBox box) {
+  final Rect rect = box.toRect();
+  return rect.isEmpty
+    ? const Iterable<Offset>.empty()
+    : <Offset>[rect.center, rect.centerLeft, rect.centerRight];
+}
+
+
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:54]: nit: remove one blank line

File: packages/flutter_test/lib/src/controller.dart [hunk 10]
```diff
@@ -24,6 +25,33 @@ const double kDragSlopDefault = 20.0;
...
+  }
+  int i = startIndex + 1;
+  while (i < endIndex && rootSpan.getSpanForPosition(TextPosition(offset: i)) == subspan) {
+    i += 1;
+  }
+  return (subspan, i);
+}
+
+/// Helper function that returns 3 special Offsets within the given `box`, to
+/// try performing hit-testing at.
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:46]: My question: what makes these three offsets so special that they were chosen here? Why not any other offsets?

File: packages/flutter_test/lib/src/controller.dart [hunk 11]
```diff
@@ -991,6 +1019,48 @@ abstract class WidgetController {
...
+  /// Dispatch a pointer down / pointer up sequence at the first hit-testable
+  /// [InlineSpan] (typically a [TextSpan]) within the given text range.
+  ///
+  /// This method performs a more spatially precise tap action on a piece of
+  /// static text, than the widget-based [tap] method.
+  ///
+  /// The given [Finder] must find one and only one matching substring, and the
+  /// substring must be hit-testable (meaning, it must not be off-screen, or be
+  /// obscured by other widgets, or in a disabled widget). Otherwise this method
+  /// throws a [FlutterError].
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:1031]: Please check, but I believe we typically return StateError for these kind of problems in other test methods?

File: packages/flutter_test/lib/src/controller.dart [hunk 12]
```diff
@@ -991,6 +1019,48 @@ abstract class WidgetController {
...
+  ///
+  /// If the target substring contains more than one hit-testable [InlineSpan]s,
+  /// [tapOnText] taps on one of them, but does not guarantee which.
+  ///
+  /// This method currently only works on static text widgets ([Text] or
+  /// [RichText] for example) that use [RenderParagraph] under the hood. It
+  /// currently does not support finding substrings in [TextField]s or
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:1038]: Remove the "currently"s in these two sentences? 

"does not support" => will it throw if it find the substring in TextFields? Will it just not see that text at all? Maybe be a little more specific what "not supported" means.

File: packages/flutter_test/lib/src/controller.dart [hunk 13]
```diff
@@ -991,6 +1019,48 @@ abstract class WidgetController {
...
+  /// This method performs a more spatially precise tap action on a piece of
+  /// static text, than the widget-based [tap] method.
+  ///
+  /// The given [Finder] must find one and only one matching substring, and the
+  /// substring must be hit-testable (meaning, it must not be off-screen, or be
+  /// obscured by other widgets, or in a disabled widget). Otherwise this method
+  /// throws a [FlutterError].
+  ///
+  /// If the target substring contains more than one hit-testable [InlineSpan]s,
+  /// [tapOnText] taps on one of them, but does not guarantee which.
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:1034]: Huh? The first paragraph said it would hit the first one. This one says it doesn't guarantee which one. Can you unify these two statements? Also, if the "no guarantee" statement is the correct one: Why can we not guarantee which one gets hit? If we cannot define which one gets hit, should we instead throw in this case and make that illegal? Is it at least deterministic which gets hit?

File: packages/flutter_test/lib/src/controller.dart [hunk 14]
```diff
@@ -991,6 +1019,48 @@ abstract class WidgetController {
...
+  ///
+  /// This method currently only works on static text widgets ([Text] or
+  /// [RichText] for example) that use [RenderParagraph] under the hood. It
+  /// currently does not support finding substrings in [TextField]s or
+  /// [SelectableText].
+  Future<void> tapOnText(finders.FinderBase<finders.TextRangeContext> textRangeFinder, {int? pointer, int buttons = kPrimaryButton }) {
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:1040]: Document the other parameters

File: packages/flutter_test/lib/src/controller.dart [hunk 15]
```diff
@@ -991,6 +1019,48 @@ abstract class WidgetController {
...
+    if (ranges.length > 1) {
+      throw FlutterError(
+        '$textRangeFinder. The "tapOnText" method needs a single non-empty TextRange.',
+      );
+    }
+    final Offset? tapLocation = _findHitTestableOffsetIn(ranges.single);
+    if (tapLocation == null) {
+      final finders.TextRangeContext found = textRangeFinder.evaluate().single;
+      throw FlutterError.fromParts(<DiagnosticsNode>[
+          ErrorSummary('Finder specifies a TextRange that would not receive pointer events.'),
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:1054]: would not -> cannot? Maybe?

File: packages/flutter_test/test/controller_test.dart (hunk 8 above)
Comment (goderbauer) [reply packages/flutter_test/test/controller_test.dart:1643]: Overall, these sentences are a little garbled. The first one seem to be missing a verb?

File: packages/flutter_test/lib/src/controller.dart [hunk 16]
```diff
@@ -1724,6 +1794,44 @@ abstract class WidgetController {
   /// in the documentation for the [flutter_test] library.
   static bool hitTestWarningShouldBeFatal = false;
 
+  /// Finds one hit-testable Offset in the given `renderParagraph` that resides
+  /// in the given `view`.
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:1798]: comment seems outdated as no renderParagraph or view is given directly.

File: packages/flutter/test/widgets/slivers_padding_test.dart (hunk 4 above)
Comment (LongCatIsLooong) [reply packages/flutter/test/widgets/slivers_padding_test.dart:630]: It's bound to fail once it reaches this case. Added a code comment.

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 17]
```diff
@@ -1492,8 +1494,24 @@ class TextPainter {
       ? boxes
       : boxes.map((TextBox box) => _shiftTextBox(box, offset)).toList(growable: false);
   }
+  /// Returns the [GlyphInfo] of the glyph closest to the given `offset` in the
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/text_painter.dart:1497]: nit: add blank line before this line?

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 18]
```diff
@@ -1492,8 +1494,24 @@ class TextPainter {
...
+  /// paragraph coordinate system, or null if if the text is empty, or is
```
Comment (goderbauer) [inline packages/flutter/lib/src/painting/text_painter.dart:1498]: remove one of the "if"s?

File: packages/flutter/test/widgets/slivers_padding_test.dart [hunk 19]
```diff
@@ -618,7 +618,16 @@ void main() {
...
+  switch (hitTestResult.path.first.target) {
+    case final TextSpan span:
+      expect(span.text, text);
+    case final RenderParagraph paragraph:
+      final InlineSpan span = paragraph.text;
+      expect(span, isA<TextSpan>());
+      expect((span as TextSpan).text, text);
+    case final HitTestTarget target:
+      // This expect always fails.
+      expect(target, anyOf(isA<TextSpan>(), isA<RenderParagraph>()));
```
Comment (goderbauer) [inline packages/flutter/test/widgets/slivers_padding_test.dart:631]: Why not use `fail` then to make it explicit that this is a failure case and provide a failure message?

https://main-api.flutter.dev/flutter/package-matcher_expect/fail.html

File: packages/flutter_test/lib/src/finders.dart (hunk 7 above)
Comment (LongCatIsLooong) [reply packages/flutter_test/lib/src/finders.dart:1126]: (I forgot to address this one I'll push a new commit in a minute).

File: packages/flutter_test/lib/src/controller.dart [hunk 20]
```diff
@@ -24,6 +24,32 @@ const double kDragSlopDefault = 20.0;
...
+  int i = startIndex + 1;
+  while (i < endIndex && rootSpan.getSpanForPosition(TextPosition(offset: i)) == subspan) {
+    i += 1;
+  }
+  return (subspan, i);
+}
+
+/// Helper function that returns 3 special Offsets within the given `box`, to
+/// try performing hit-testing at.
+Iterable<Offset> _testOffsetsForEachTextBox(TextBox box) {
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart]: Could we just hit test the center, similar to https://main-api.flutter.dev/flutter/flutter_test/WidgetController/tap.html?

If we do this, let's also mention it in the docs.

File: packages/flutter_test/lib/src/finders.dart [hunk 21]
```diff
@@ -677,6 +700,29 @@ class CommonSemanticsFinders {
...
+final class CommonTextRangeFinders {
+  const CommonTextRangeFinders._();
+
+  /// Finds all occurrances of the given `substring` in the static text widgets
+  /// and returns the [TextRange]s.
+  ///
+  /// If the `skipOffstage` argument is true (the default), then this skips
+  /// static text inside widgets that are [Offstage], or that are from inactive
+  /// [Route]s.
+  ///
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/finders.dart:715]: Maybe document how overlapping substrings are handled.

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter_test/lib/src/controller.dart (hunk 20 above)
Comment (LongCatIsLooong) [reply packages/flutter_test/lib/src/controller.dart]: I think it's a bit hard to explain how the glyphs are grouped into boxes, if we want to mention hit testing the center of TextBoxes? If the specified font doesn't have glyphs for some characters in the substring then these glyphs will usually be in separate TextBoxes. The 3rd paragraph says the substring must not be obstructed or offscreen, does that work?

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 22]
```diff
@@ -1493,7 +1495,24 @@ class TextPainter {
...
+    final _TextPainterLayoutCacheWithOffset cachedLayout = _layoutCache!;
+    final ui.GlyphInfo? rawGlyphInfo = cachedLayout.paragraph.getClosestGlyphInfoForOffset(offset - cachedLayout.paintOffset);
+    if (rawGlyphInfo == null || cachedLayout.paintOffset == Offset.zero) {
+      return rawGlyphInfo;
+    }
+    return ui.GlyphInfo(rawGlyphInfo.graphemeClusterLayoutBounds.shift(cachedLayout.paintOffset), rawGlyphInfo.graphemeClusterCodeUnitRange, rawGlyphInfo.writingDirection);
+  }
+
+  /// Returns the closest position within the text for the given pixel offset.
   TextPosition getPositionForOffset(Offset offset) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/painting/text_painter.dart:1516]: Can this be replaced by getClosestGlyphForOffset?

File: packages/flutter/lib/src/rendering/editable.dart [hunk 23]
```diff
@@ -1941,8 +1941,14 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
   @protected
   bool hitTestChildren(BoxHitTestResult result, { required Offset position }) {
     final Offset effectivePosition = position - _paintOffset;
-    final InlineSpan? textSpan = _textPainter.text;
-    switch (textSpan?.getSpanForPosition(_textPainter.getPositionForOffset(effectivePosition))) {
+    final GlyphInfo? glyph = _textPainter.getClosestGlyphForOffset(effectivePosition);
+    // This works even with large letter-spacing and text justification, as
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/editable.dart:1945]: reading this i am not sure what `works` mean. Do you mean it will missed when click in between character? or it would still hit the span. I think it is the latter, but would be good to be more clear

File: packages/flutter/lib/src/rendering/editable.dart [hunk 24]
```diff
@@ -1941,8 +1941,14 @@ class RenderEditable extends RenderBox with RelayoutWhenSystemFontsChangeMixin,
...
+    // graphemeClusterLayoutBounds.width is the x layout advance to the next
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/editable.dart:1946]: I can guess what x layout advance mean, is it a term that commonly used?

**Review by chunhtai — APPROVED** [review]
LGTM, just some questions

File: packages/flutter/lib/src/rendering/editable.dart (hunk 23 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:1945]: It would still hit the span (same behavior as `getSpanForPosition` ). I'll update the comment.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 24 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/editable.dart:1946]: In https://freetype.org/freetype2/docs/glyphs/glyphs-3.html it's called advance width. I can change to that if you prefer it over x layout advance?

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 22 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/painting/text_painter.dart:1516]: I believe so.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 24 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/editable.dart:1946]: TIL, yes I think using advance width may be more clear

**Comment by LongCatIsLooong** [comment]
Passing TGP: OCL:592353811:BASE:592365935:1703029674505:124de1d9
