### PR TITLE
[flutter_tools] Handle disk device not found

### LINKED ISSUE #75607: [tool_crash] FileSystemException: flush failed, OS Error: A device which does not exist was specified., errno = 433
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=P8B4C18512002612 --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: flush failed, OS Error: A device which does not exist was specified.
, errno = 433
```
#0      _RandomAccessFile.flushSync (dart:io/file_impl.dart:974:7)
#1      _File.writeAsBytesSync (dart:io/file_impl.dart:607:25)
#2      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#3      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147:16)
#4      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:259:22)
#5      _runSync (package:flutter_tools/src/base/error_handling_io.dart:560:14)
#6      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:258:5)
#7      _writeFlutterPluginsListLegacy (package:flutter_tools/src/plugins.dart:523:15)
#8      refreshPluginsList (package:flutter_tools/src/plugins.dart:1149:30)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:275:5)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1142:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1011:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#13     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:280:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
```
```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.91, on Microsoft Windows [Version 10.0.19042.789], locale en-US)
    • Flutter version 1.26.0-18.0.pre.91 at C:\src\flutter
    • Framework revision cb14df5659 (7 days ago), 2021-02-01 06:17:38 -0500
    • Engine revision ce14c8a841
    • Dart version 2.12.0 (build 2.12.0-276.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Suraj\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (4 available)
    • LLD AL10 (mobile)           • P8B4C18512002612 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554    • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome           • web-javascript • Google Chrome 88.0.4324.146
    • Edge (web)                  • edge             • web-javascript • Microsoft Edge 88.0.705.63

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: cb14df565977e23e021d8b22c0bc8870a5a6dac4
### Plugins
external_app_launcher-0.0.1

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/75607 and https://github.com/flutter/flutter/issues/90925

### CODE REVIEW

File: packages/flutter_tools/lib/src/base/error_handling_io.dart [hunk 1]
```diff
@@ -796,6 +797,12 @@ void _handleWindowsException(Exception e, String? message, int errorCode) {
         '$message. There is a problem with the device driver '
         'that this file or directory is stored on.';
       break;
+    case kDeviceDoesNotExist:
+      errorMessage =
+        '$message. The file device was not found.'
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/base/error_handling_io.dart:802]:
```suggestion
        '$message. The device was not found.'
```

**Review by zanderso — APPROVED** [review]
lgtm w/ nit
