### PR TITLE
Better separation between app and plugin main.dart and fix plugin main.dart issues.

### LINKED ISSUE #9458: Clean up main.dart.tmpl
Recent changes to the main.dart `flutter create` template need some cleanup for style and correctness.
See comments from me in https://github.com/flutter/flutter/pull/9076.

### PR DESCRIPTION
**Pull request by mit-mit**
Clearly separate the main part of the main.dart into regular app and plugin app.

Fix mounted bug in plugin.

Simplify plugin app to not have counter logic, and instructional comments that are plugin specific.

Fixes https://github.com/flutter/flutter/issues/9458

### CODE REVIEW

File: packages/flutter_tools/templates/create/lib/main.dart.tmpl [hunk 1]
```diff
@@ -124,3 +101,46 @@ class _MyHomePageState extends State<MyHomePage> {
...
+    super.initState();
+    initPlatformState();
+  }
+
+  // Platform messages are asynchronous, so we initialize in an async method.
+  initPlatformState() async {
+    String platformVersion;
+    // Platform messages may fail, so we use a try/catch PlatformException.
+    try {
+      platformVersion = await Testplugin.platformVersion;
```
Comment (jakobr-google) [inline packages/flutter_tools/templates/create/lib/main.dart.tmpl]: You'll want to use `{{pluginDartClass}}` instead of `Testplugin` here.

File: packages/flutter_tools/templates/create/lib/main.dart.tmpl [hunk 2]
```diff
@@ -3,6 +3,7 @@ import 'package:flutter/material.dart';
 import 'package:flutter_driver/driver_extension.dart';
 {{/withDriverTest}}
 {{#withPluginHook}}
+import 'package:flutter/services.dart';
```
Comment (jakobr-google) [inline packages/flutter_tools/templates/create/lib/main.dart.tmpl]: What do we need this one for?

**Review by jakobr-google — CHANGES_REQUESTED** [review]
Almost LGTM. :)

File: packages/flutter_tools/templates/create/lib/main.dart.tmpl (hunk 2 above)
Comment (mit-mit) [inline packages/flutter_tools/templates/create/lib/main.dart.tmpl]: For the try/catch; that's where `PlatformException` is defined

File: packages/flutter_tools/templates/create/lib/main.dart.tmpl (hunk 1 above)
Comment (mit-mit) [inline packages/flutter_tools/templates/create/lib/main.dart.tmpl]: Thanks, fixed

**Review by jakobr-google — APPROVED** [review]
LGTM

File: packages/flutter_tools/templates/create/lib/main.dart.tmpl [hunk 3]
```diff
@@ -124,3 +101,45 @@ class _MyHomePageState extends State<MyHomePage> {
...
+    super.initState();
+    initPlatformState();
+  }
+
+  // Platform messages are asynchronous, so we initialize in an async method.
+  initPlatformState() async {
+    String platformVersion;
+    // Platform messages may fail, so we use a try/catch PlatformException.
+    try {
+      platformVersion = await {{pluginDartClass}}.platformVersion;
```
Comment (Hixie) [inline packages/flutter_tools/templates/create/lib/main.dart.tmpl]: It's unfortunate that there's no way to cancel the platformVersion call. Imagine if the call did a lot of computation, but the user triggered it then left the page that cares about the result. The work would still get done, but the result would then be thrown away.

Anyway that's an issue for another bug.

File: packages/flutter_tools/templates/create/lib/main.dart.tmpl [hunk 4]
```diff
@@ -124,3 +101,45 @@ class _MyHomePageState extends State<MyHomePage> {
...
+    } on PlatformException {
+      platformVersion = "Failed to get platform version";
+    }
+
+    // If the widget was removed from the tree while the asynchronous platform
+    // message was in flight, we want to discard the reply rather than calling
+    // setState to update our non-existent appearance.
+    if (!mounted) return;
```
Comment (Hixie) [inline packages/flutter_tools/templates/create/lib/main.dart.tmpl]: newline before return

**Comment by Hixie** [comment]
LGTM but why not a FutureBuilder?

**Comment by mit-mit** [comment]
Merging. The broken flutter-build appears to be a flake as it passed in a re-run.

**Comment by mit-mit** [comment]
RE FutureBuilder: As I think it's hard to motivate and explain that concept in a sample where the widget tree is entirely fixed. I think we need to have a more complete example for it to be meaningful, for example add something to gallery.

**Comment by Hixie** [comment]
I don't understand. It would simplify this code, no? Isn't the motivation just that you wouldn't have to do the setState/mounted dance?
