### PR TITLE
Fix cut button creation in 'buttonItemsForToolbarOptions'

### LINKED ISSUE #119820: [iOS, Android] The 'Cut' context menu button won't appear in text fields when `toolbarOptions` are passed
### Steps to Reproduce
1. Execute `flutter run` on the code sample;
2. Type text on any of the fields;
3. Select typed text;
4. You will see the `Select All`, `Copy`, and `Paste` buttons. On the `Select All` button's place should be `Cut`, because the `selectAll` property is set to `false` in the provided `ToolbarOptions`;
5. Comment `toolbarOptions` of that field and the `Cut` button will be available.

#### Actual results
https://user-images.githubusercontent.com/30288967/215864804-9b428e63-fe47-4abe-8e50-939106e9bf78.mov

#### Expected results
https://user-images.githubusercontent.com/30288967/215864824-695a2390-c554-42b3-b662-d330086cbce5.mov

The `toolbarOptions` were deprecated after v3.3.0-0.5.pre, but many users can still use them and be affected by this bug. 
This bug is reproducible in stable (v3.7.0) and master (3.7.0-30.0.pre).

### Fix

The root of this issue is located in the `flutter/lib/src/widgets/editable_text.dart` in the method `buttonItemsForToolbarOptions`

```dart
List<ContextMenuButtonItem>? buttonItemsForToolbarOptions([TargetPlatform? targetPlatform]) {
    final ToolbarOptions toolbarOptions = widget.toolbarOptions;
    if (toolbarOptions == ToolbarOptions.empty) {
      return null;
    }
    return <ContextMenuButtonItem>[
      if (toolbarOptions.cut && cutEnabled)
        ContextMenuButtonItem(
          onPressed: () {
            selectAll(SelectionChangedCause.toolbar);
          },
          type: ContextMenuButtonType.selectAll,
        ),
      if (toolbarOptions.copy && copyEnabled)
        ContextMenuButtonItem(
          onPressed: () {
            copySelection(SelectionChangedCause.toolbar);
          },
          type: ContextMenuButtonType.copy,
        ),
      if (toolbarOptions.paste && clipboardStatus != null && pasteEnabled)
        ContextMenuButtonItem(
          onPressed: () {
            pasteText(SelectionChangedCause.toolbar);
          },
          type: ContextMenuButtonType.paste,
        ),
      if (toolbarOptions.selectAll && selectAllEnabled)
        ContextMenuButtonItem(
          onPressed: () {
            selectAll(SelectionChangedCause.toolbar);
          },
          type: ContextMenuButtonType.selectAll,
        ),
    ];
  }
```

As you can see we have wrong `ContextMenuButtonItem` insertion after the `if (toolbarOptions.cut && cutEnabled)` condition. 
It seems to be a copy-paste from the `if (toolbarOptions.selectAll && selectAllEnabled)` condition.

<details>
  <summary>Code sample</summary>

   ### main.dart
  ```dart
// ignore_for_file: deprecated_member_use

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: false,
      ),
      home: Scaffold(
        backgroundColor: Colors.grey[100],
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Text('TextField'),
                const TextField(
                  toolbarOptions: ToolbarOptions(
                    cut: true,
                    copy: true,
                    paste: true,
                    selectAll: false,
                  ),
                ),
                const SizedBox(height: 15),
                const Text('TextFormField'),
                TextFormField(
                  toolbarOptions: const ToolbarOptions(
                    cut: true,
                    copy: true,
                    paste: true,
                    selectAll: false,
                  ),
                ),
                const SizedBox(height: 15),
                const Text('CupertinoTextField'),
                const CupertinoTextField(
                  toolbarOptions: ToolbarOptions(
                    cut: true,
                    copy: true,
                    paste: true,
                    selectAll: false,
                  ),
                ),
                const SizedBox(height: 15),
                const Text('CupertinoTextFormFieldRow'),
                CupertinoTextFormFieldRow(
                  toolbarOptions: const ToolbarOptions(
                    cut: true,
                    copy: true,
                    paste: true,
                    selectAll: false,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

  ```
</details>

<details>
  <summary>flutter doctor -v</summary>

  #### Stable
  ```
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.7.0 on channel stable at /Users/ksokolovskyi/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (8 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • 6E277068-11E0-4342-B066-0D4EF7A599EB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 13.0.1 22A400
      darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome
      108.0.5359.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
  ```

#### Master
  ```
[✓] Flutter (Channel master, 3.8.0-1.0.pre.32, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.8.0-1.0.pre.32 on channel master at /Users/ksokolovskyi/dev/flutter_master
    • Upstream repository git@github.com:ksokolovskyi/flutter.git
    • FLUTTER_GIT_URL = git@github.com:ksokolovskyi/flutter.git
    • Framework revision f9daa9aac4 (7 hours ago), 2023-02-01 22:59:24 -0500
    • Engine revision 679c4b42e2
    • Dart version 3.0.0 (build 3.0.0-192.0.dev)
    • DevTools version 2.21.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
  ```
</details>

### PR DESCRIPTION
**Pull request by ksokolovskyi**
This PR fixes the bug in `buttonItemsForToolbarOptions` method of `EditableTextState`. 
Because of this bug, the cut button in the text field's context menu is not created when a user passes only `toolbarOptions` without the `contextMenuBuilder`.

Fixes #119820 

#### Before
https://user-images.githubusercontent.com/30288967/216338640-b1f9ae21-98bd-461f-a6d4-fc17654c4b49.mov

#### After
https://user-images.githubusercontent.com/30288967/216338647-762f42c0-5039-4f68-99ff-541074bcfa44.mov

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 1]
```diff
@@ -2157,6 +2157,310 @@ void main() {
...
+
+      final List<ContextMenuButtonItem>? items = state.buttonItemsForToolbarOptions();
+
+      if (items == null) {
+        fail('Copy button was not returned');
+      }
+
+      if (items.length > 1) {
+        fail('Not only the copy button was returned');
+      }
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:2314]: Nit: I think there's nothing actually wrong with this if/fail approach, but I think using `expect` is more common in the framework tests and provides a bit more info.  So you could replace these with something like:

```dart
expect(items, isNotNull);
expect(items, hasLength(1));
```

Here and elsewhere.

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 2]
```diff
@@ -2157,6 +2157,310 @@ void main() {
...
+            backgroundCursorColor: Colors.grey,
+          ),
+        ),
+      );
+
+      final EditableTextState state = tester.state<EditableTextState>(
+        find.byType(EditableText),
+      );
+
+      // Moving caret to the end
```
Comment (justinmc) [inline packages/flutter/test/widgets/editable_text_test.dart:2372]: Period at the end of the comment, here and below.

**Review by justinmc — APPROVED** [review]
LGTM with nits.

Thanks for fixing this and for the great tests!  Totally a mistake on my part in putting the select all button where paste should be 😬

**Comment by ksokolovskyi** [comment]
Hi @justinmc, thanks for the review! 
I made changes to the tests according to your comments.

**Comment by justinmc** [comment]
Thank you, looks great!  We need one more reviewer, I'll find somebody.

**Review by reidbaker — APPROVED** [review]

**Comment by ksokolovskyi** [comment]
@justinmc @reidbaker Is this ok that 'Google testing' is in pending status for a few days?

**Comment by reidbaker** [comment]
> 

I think this is an issue with pull requests that have backticks in the name. I cant seem to find the bug which has the workaround.

**Comment by XilaiZhang** [comment]
@ksokolovskyi can you try rebasing the PR to see if google testing passes? Thank you!

**Comment by justinmc** [comment]
Something is wrong with these Linux smoke tests right now.  I've asked about it on Discord: https://discord.com/channels/608014603317936148/608021351567065092/1072285684913688676

**Comment by ksokolovskyi** [comment]
@justinmc @reidbaker seems now everything is fine

**Comment by reidbaker** [comment]
@camsim99 can you take a look
