### PR TITLE
[flutter_tools] Add timeout duration to error and handle exceptions for HttpHostValidator.

### LINKED ISSUE #98286: Doctor host validator is missing the timeout duration
## Steps to Reproduce

Running `flutter doctor -v` on a spotty network connection might display the following message:
```
[!] HTTP Host Availability
    ✗ HTTP host https://cloud.google.com/ is not reachable. Reason: Failed to connect to https://cloud.google.com/ in seconds
```

Seems like the error message is missing the timeout duration:
<pre>
Failed to connect to https://cloud.google.com/ in <b>5</b> seconds
</pre>

### LINKED ISSUE #98328: [tool]: Proposal to show specific error message when invalid environment variables are set for HTTP validation
The doctor HTTP validation can be configured through environment variables by providing a custom timeout `FLUTTER_DOCTOR_HOST_TIMEOUT` or hosts `PUB_HOSTED_URL` and `FLUTTER_STORAGE_BASE_URL`. However, setting any of them to a invalid value crashes the doctor validation.

## Steps to Reproduce
Run these commands:
```
$ FLUTTER_STORAGE_BASE_URL='::Not valid URI::' flutter doctor -v
$ PUB_HOSTED_URL='' flutter doctor -v
$ FLUTTER_DOCTOR_HOST_TIMEOUT='deadbeef' flutter doctor -v
```

**Expected results:** 
The doctor flow completes normally, displaying errors when appropriate.

**Actual results:** 
Tool crashes, listed below:
<details>
  <summary>Invalid URI</summary>

```
[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Invalid empty scheme (at character 1)
      ::Not valid URI::
      ^

    • #0      _Uri._fail (dart:core/uri.dart:1754:5)
      #1      new _Uri.notSimple (dart:core/uri.dart:1587:9)
      #2      Uri.parse (dart:core/uri.dart:1123:17)
      #3      HttpHostValidator._checkHostAvailability (package:flutter_tools/src/http_host_validator.dart:62:67)
      #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
      #5      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
      #6      Future.wait (dart:async/future.dart:471:26)
      #7      HttpHostValidator.validate (package:flutter_tools/src/http_host_validator.dart:88:19)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #9      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #10     _rootRun (dart:async/zone.dart:1426:13)
      #11     _CustomZone.run (dart:async/zone.dart:1328:19)
      #12     _runZoned (dart:async/zone.dart:1861:10)
      #13     runZonedGuarded (dart:async/zone.dart:1849:12)
      #14     runZoned (dart:async/zone.dart:1780:12)
      #15     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #16     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:206:9)
      #17     Doctor.diagnose (package:flutter_tools/src/doctor.dart:316:72)
      #18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1324:12)
      <asynchronous suspension>
      #20     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
      <asynchronous suspension>
      #21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #22     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #23     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #28     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>

```
</details>

<details>
  <summary>Invalid host</summary>

```
[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Invalid argument(s): No host specified in URI 
    • #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2667:9)
      #1      _HttpClient.headUrl (dart:_http/http_impl.dart:2595:49)
      #2      HttpHostValidator._checkHostAvailability (package:flutter_tools/src/http_host_validator.dart:62:55)
      #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
      #4      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
      #5      Future.wait (dart:async/future.dart:471:26)
      #6      HttpHostValidator.validate (package:flutter_tools/src/http_host_validator.dart:88:19)
      #7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #9      _rootRun (dart:async/zone.dart:1426:13)
      #10     _CustomZone.run (dart:async/zone.dart:1328:19)
      #11     _runZoned (dart:async/zone.dart:1861:10)
      #12     runZonedGuarded (dart:async/zone.dart:1849:12)
      #13     runZoned (dart:async/zone.dart:1780:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:206:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:316:72)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1324:12)
      <asynchronous suspension>
      #19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
      <asynchronous suspension>
      #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #21     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>
```
</details>
<details>
<summary>Invalid timeout duration</summary>

```
[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Invalid radix-10 number (at character 1)
      deadbeef
      ^

    • #0      int._handleFormatError (dart:core-patch/integers_patch.dart:131:5)
      #1      int._parseRadix (dart:core-patch/integers_patch.dart:142:16)
      #2      int._parse (dart:core-patch/integers_patch.dart:103:12)
      #3      int.parse (dart:core-patch/integers_patch.dart:65:12)
      #4      HttpHostValidator._checkHostAvailability (package:flutter_tools/src/http_host_validator.dart:61:11)
      #5      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
      #6      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
      #7      Future.wait (dart:async/future.dart:471:26)
      #8      HttpHostValidator.validate (package:flutter_tools/src/http_host_validator.dart:88:19)
      #9      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #11     _rootRun (dart:async/zone.dart:1426:13)
      #12     _CustomZone.run (dart:async/zone.dart:1328:19)
      #13     _runZoned (dart:async/zone.dart:1861:10)
      #14     runZonedGuarded (dart:async/zone.dart:1849:12)
      #15     runZoned (dart:async/zone.dart:1780:12)
      #16     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #17     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:206:9)
      #18     Doctor.diagnose (package:flutter_tools/src/doctor.dart:316:72)
      #19     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #20     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1324:12)
      <asynchronous suspension>
      #21     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
      <asynchronous suspension>
      #22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #23     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #27     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #29     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>
```

</details>

***
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.11.0-0.0.pre.521, on Artix Linux 5.16.7-artix1-1, locale en_IN.UTF-8)
    • Flutter version 2.11.0-0.0.pre.521 at /home/rarg/.local/src/flutter_sdk_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 81b9c35274 (18 hours ago), 2022-02-11 09:30:51 -0800
    • Engine revision bed591d394
    • Dart version 2.17.0 (build 2.17.0-87.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/android-sdk
    • Platform android-31, build-tools 29.0.2
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+8)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.22.2
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Artix Linux 5.16.7-artix1-1
    • Chrome (web)    • chrome • web-javascript • Chromium 98.0.4758.80 Artix Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

### PR DESCRIPTION
**Pull request by royarg02**
Includes the timeout duration, handles exceptions for invalid `FLUTTER_DOCTOR_HOST_TIMEOUT`, `PUB_HOSTED_URL` or `FLUTTER_STORAGE_BASE_URL` environment variables of `HttpHostValidator`.

Also includes some code hand-formatting/cleanup for readability.

Adds tests to make sure the timeout is being displayed and exceptions are handled accordingly.

Fixes #98286.
Fixes #98328.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/http_host_validator.dart [hunk 1]
```diff
@@ -56,69 +55,57 @@ class HttpHostValidator extends DoctorValidator {
 
   /// Make a head request to the HTTP host. HTTP Host is available if no exception happened
   Future<_HostValidationResult> _checkHostAvailability(String host) async {
+    final int timeout = int.tryParse(_platform.environment[kDoctorHostTimeout] ?? '10') ?? 10;
```
Comment (RoyARG02) [inline packages/flutter_tools/lib/src/http_host_validator.dart:58]: Used tryParse instead to avoid crash

File: packages/flutter_tools/lib/src/http_host_validator.dart [hunk 2]
```diff
@@ -56,69 +55,57 @@ class HttpHostValidator extends DoctorValidator {
...
 
   @override
   Future<ValidationResult> validate() async {
     final List<ValidationMessage> messages = <ValidationMessage>[];
-    final Iterable<Future<_HostValidationResult>> availabilityResultFutures =
-    _requiredHosts.map(_checkHostAvailability);
 
-    final List<_HostValidationResult> availabilityResults =
-    (await Future.wait(availabilityResultFutures)).toList();
+    final List<_HostValidationResult> availabilityResults = await Future.wait(_requiredHosts.map(_checkHostAvailability));
```
Comment (RoyARG02) [inline packages/flutter_tools/lib/src/http_host_validator.dart:79]: Not sure why the `.toList` was needed here

File: packages/flutter_tools/lib/src/http_host_validator.dart [hunk 3]
```diff
@@ -54,71 +53,60 @@ class HttpHostValidator extends DoctorValidator {
...
-      int.parse(_platform.environment[kDoctorHostTimeout] ?? '10');
+      timeout = int.parse(_platform.environment[kDoctorHostTimeout] ?? '10');
       final HttpClientRequest req = await _httpClient.headUrl(Uri.parse(host));
       await req.close().timeout(Duration(seconds: timeout));
-      // HTTP Host is available if no exception happened
+      // HTTP host is available if no exception happened
       return _HostValidationResult.success(host);
     } on TimeoutException {
-      return _HostValidationResult.fail(
-          host, 'Failed to connect to $host in seconds');
```
Comment (RoyARG02) [inline packages/flutter_tools/lib/src/http_host_validator.dart:68]: We already mention `$host` before this message, no need to mention it again.

File: packages/flutter_tools/lib/src/http_host_validator.dart [hunk 4]
```diff
@@ -54,71 +53,60 @@ class HttpHostValidator extends DoctorValidator {
...
+      return _HostValidationResult.fail(host, 'Failed to connect to host in $timeout second${timeout == 1 ? '': 's'}');
     } on SocketException catch (e) {
-      return _HostValidationResult.fail(
-          host, 'An error occurred while checking the HTTP host: ${e.message}');
+      return _HostValidationResult.fail(host, 'An error occurred while checking the HTTP host: ${e.message}');
     } on HttpException catch (e) {
-      return _HostValidationResult.fail(host,
-          'An error occurred while checking the HTTP host: ${e.toString()}');
+      return _HostValidationResult.fail(host, 'An error occurred while checking the HTTP host: ${e.message}');
```
Comment (RoyARG02) [inline packages/flutter_tools/lib/src/http_host_validator.dart:70]: `e.toString() => e.message`

File: packages/flutter_tools/test/commands.shard/hermetic/http_host_validator_test.dart [hunk 5]
```diff
@@ -62,34 +63,12 @@ void main() {
           // Run the validation check and get the results
           final ValidationResult result = await httpHostValidator.validate();
 
-          // Check for a ValidationType.installed result
+          // Check for a ValidationType.notAvailable result
           expect(result.type, equals(ValidationType.notAvailable));
         }
       });
 
-      testWithoutContext('one http hosts are not available', () async {
```
Comment (RoyARG02) [inline packages/flutter_tools/test/commands.shard/hermetic/http_host_validator_test.dart:70]: Duplicate test

File: packages/flutter_tools/test/commands.shard/hermetic/http_host_validator_test.dart [hunk 6]
```diff
@@ -171,29 +150,7 @@ void main() {
           // Run the validation check and get the results
           final ValidationResult result = await httpHostValidator.validate();
 
-          // Check for a ValidationType.installed result
-          expect(result.type, equals(ValidationType.partial));
-        }
-      });
-
-      testWithoutContext('one http hosts are not available', () async {
```
Comment (RoyARG02) [inline packages/flutter_tools/test/commands.shard/hermetic/http_host_validator_test.dart:179]: Duplicate test

File: packages/flutter_tools/lib/src/http_host_validator.dart [hunk 7]
```diff
@@ -32,25 +32,23 @@ List<String> androidRequiredHttpHosts(Platform platform) {
...
-        required FeatureFlags featureFlags,
-        required HttpClient httpClient})
-      : _platform = platform,
-        _featureFlags = featureFlags,
-        _httpClient = httpClient,
-        super('HTTP Host Availability');
+  HttpHostValidator({
+    required Platform platform,
+    required FeatureFlags featureFlags,
+    required HttpClient httpClient
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/http_host_validator.dart:40]: nit, can you add a trailing comma

File: packages/flutter_tools/lib/src/http_host_validator.dart [hunk 8]
```diff
@@ -59,71 +57,60 @@ class HttpHostValidator extends DoctorValidator {
...
   ];
 
-  /// Make a head request to the HTTP host. HTTP Host is available if no exception happened
+  /// Make a head request to the HTTP host for checking availability
   Future<_HostValidationResult> _checkHostAvailability(String host) async {
+    late final int timeout;
     try {
-      final int timeout =
-      int.parse(_platform.environment[kDoctorHostTimeout] ?? '10');
+      timeout = int.parse(_platform.environment[kDoctorHostTimeout] ?? '10');
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/http_host_validator.dart:64]: can this also be lifted outside of the try block?

File: packages/flutter_tools/lib/src/http_host_validator.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/http_host_validator.dart:84]: Why did you condense lines 89-92 into one? I feel like it is more difficult to read as a one-liner.

File: packages/flutter_tools/test/commands.shard/hermetic/http_host_validator_test.dart (hunk 5 above)
Comment (christopherfujino) [reply packages/flutter_tools/test/commands.shard/hermetic/http_host_validator_test.dart:71]: yikes, good catch

File: packages/flutter_tools/lib/src/http_host_validator.dart (hunk 8 above)
Comment (RoyARG02) [reply packages/flutter_tools/lib/src/http_host_validator.dart:64]: See #98328.

File: packages/flutter_tools/lib/src/http_host_validator.dart (hunk 2 above)
Comment (RoyARG02) [reply packages/flutter_tools/lib/src/http_host_validator.dart:84]: So should I reintroduce `availabilityResultFutures`?

File: packages/flutter_tools/lib/src/http_host_validator.dart (hunk 8 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/http_host_validator.dart:64]: Are you catching `FormatException`?

File: packages/flutter_tools/lib/src/http_host_validator.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/http_host_validator.dart:84]: If it was just a style refactor, I would prefer having `availabilityResultFutures`

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/http_host_validator.dart:84]: I agree that `.toList()` was redundant

File: packages/flutter_tools/lib/src/http_host_validator.dart (hunk 8 above)
Comment (RoyARG02) [reply packages/flutter_tools/lib/src/http_host_validator.dart:64]: Not in this PR, but in the PR that fixes that issue, and I see no point in moving this line when eventually it has to be moved back.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/http_host_validator.dart:64]: any reason not to catch and toolexit on formatexception in this PR?

Comment (RoyARG02) [reply packages/flutter_tools/lib/src/http_host_validator.dart:64]: Nothing specific, thought it would be better to land separate PRs to fix separate issues, but I can include all in one if you are okay with that.

Comment (christopherfujino) [reply packages/flutter_tools/lib/src/http_host_validator.dart:64]: Sounds good to me as long as it's not a lot more code, which I imagine it wouldn't be?

Comment (RoyARG02) [reply packages/flutter_tools/lib/src/http_host_validator.dart:64]: @christopherfujino I've pushed a commit that handles all possible exceptions, PTAL.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
@Jasguerrero can you give another review on this one?

**Review by Jasguerrero — APPROVED** [review]
LGTM
