### PR TITLE
MinimumTapTargetGuideline skips nodes at scrollable boundaries

### LINKED ISSUE #107615: MinimumTapTargetGuideline doesn't work if items are scrolled out of the viewport and the viewport doesn't touch the edge of the screen
b/238879865

MinimumTapTargetGuideline has logic to detect and skip elements that are scrolled partially off screen. However, this logic is flawed. It only checks for widgets that are at the edge of the physical screen, which omits the common case where the Scrollable container itself doesn't touch the edge of the screen.

Consider a screen with an AppBar and a long scrollable widget beneath it. Something like

```
Scaffold(
  appBar: AppBar(title: Text('Foo')),
  body: ListView(children: buildChildren()),
)
```

If a widget is partially visible at the top of the ListView, it will still be beneath the AppBar, not at the edge of the device screen, therefore it may fail the MinimumTapTargetGuideline erroneously.

### PR DESCRIPTION
**Pull request by chunhtai**
fixes https://github.com/flutter/flutter/issues/107615

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_test/lib/src/accessibility.dart [hunk 1]
```diff
@@ -121,6 +121,13 @@ class MinimumTapTargetGuideline extends AccessibilityGuideline {
   /// A link describing the tap target guidelines for a platform.
   final String link;
 
+  /// The gap between targets to their parent scrollables to be consider as valid
```
Comment (chunhtai) [inline packages/flutter_test/lib/src/accessibility.dart:124]:
```suggestion
  /// The gap between targets to their parent scrollables to be considered as valid
```

File: packages/flutter_test/lib/src/accessibility.dart [hunk 2]
```diff
@@ -149,27 +156,30 @@ class MinimumTapTargetGuideline extends AccessibilityGuideline {
     }
     Rect paintBounds = node.rect;
     SemanticsNode? current = node;
+
     while (current != null) {
       final Matrix4? transform = current.transform;
       if (transform != null) {
         paintBounds = MatrixUtils.transformRect(transform, paintBounds);
       }
+      // skip node if it is touching the edge scrollable, since it might
```
Comment (chunhtai) [inline packages/flutter_test/lib/src/accessibility.dart:165]:
```suggestion
      // Skipping node if it is touching the edge scrollable, since it might
```

**Review by pdblasi-google — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
g3fix 
cl/525216354
