### PR TITLE
Standardize build system environment defines derived from build info

### LINKED ISSUE #64730: flutter build ios-framework does not generate obfuscation symbols
## Steps to Reproduce

1. Run `flutter build ios-framework --no-debug --no-profile --xcframework --no-universal --cocoapods --obfuscate --split-debug-info=<a_path>`.

**Expected results:** 

<a_path> containing ios-framework symbol map files

**Actual results:** 

<a_path> is empty

<details>
  <summary>Logs</summary>

```
Building frameworks for com.[app] in release mode...
 ├─Populating Flutter.framework...                                  3,4s
 ├─Building App.framework...                                       24,7s
 ├─Building plugins...                                             71,3s
 └─Moving to build/ios/framework/Release                            0,1s
Frameworks written to
/Users/timoteoholanda/repos/[app]/build/ios/framework.
```

```
Analyzing next_flutter...

   info • Unused import: 'package:flutter/material.dart' •
          test/widget_test.dart:8:8 • unused_import
   info • Unused import: 'package:[app]/main.dart' •
          test/widget_test.dart:10:8 • unused_import

2 issues found. (ran in 6.6s)
```

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.5 19F96, locale pt-BR)
    • Flutter version 1.20.2 at /Users/timoteoholanda/development/flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/timoteoholanda/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)

• No issues found!
```

</details>

Android builds using `flutter build aar --obfuscate --split-debug-info=<a_path>` does work as intended, but ios-frameworks is not.

### PR DESCRIPTION
**Pull request by jmagman**
1. Create `BuildInfo.toBuildSystemEnvironment()` to standardize how the `Environment.defines` map is constructed from build info. 
2. Adopt `toBuildSystemEnvironment()` in web compilation, ios-frameworks, and bundle.
3. Move relevant defines constants into `build_info.dart` since it can't import null unsafe `assets.dart` and `common.dart`. Update other imports.

Fixes https://github.com/flutter/flutter/issues/64730

### CODE REVIEW

File: packages/flutter_tools/lib/src/build_info.dart [hunk 1]
```diff
@@ -69,7 +70,7 @@ class BuildInfo {
   /// file. If not provided, defaults to `.packages`.
   final String packagesPath;
 
-  final List<String>? fileSystemRoots;
+  final List<String> fileSystemRoots;
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/build_info.dart:73]: Make this nonnull.

**Comment by jmagman** [comment]
Windows tests are failing #81837.  I'll retry the tests once that's resolved, putting out for review in the meantime.

**Review by jonahwilliams — APPROVED** [review]
LGTM!

This is a great clean up
