### PR TITLE
TextField enabled fix

### LINKED ISSUE #55632: enabled property of InputDecoration does not work
The `enabled` property of `InputDecoration` should have the following behaviour as described in in the documentation: 

> If false [helperText],[errorText], and [counterText] are not displayed, and the opacity of the remaining visual elements is reduced.

By settings this property to `false` the expected behaviour does not occur. A small example:

``` dart
TextFormField(
    decoration: InputDecoration(
        labelText: 'IP Address',
        enabled: false,
    ),
    validator: (text) => ValidationHelper.ipValidation(text),
)
```

After the validation returns a `String` the `errorText` is being displayed even though I have set `enabled: false`. Additionally

> opacity of the remaining visual elements is reduced

does not apply either. Therefore this property is most likely not  being used internally.

Additional note: `TextFormField` does have its own `enabled` property. Setting this property to `false` does work, but if a user does not set the `enabled` property on `TextFormField` or `TextField` the `enabled` property of `InputDecoration` should override the default `true` value

---

Flutter doctor output:

```
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.18.0-8.0.pre at /Users/kounex/Documents/Development/libs/flutter
    • Framework revision e0c63cd35e (33 hours ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/kounex/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 35F520AD-8820-4F03-9E70-D8A5F56B92A4 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
```

### PR DESCRIPTION
**Pull request by justinmc**
## Description

In [InputDecoration's docs for enabled](https://master-api.flutter.dev/flutter/material/InputDecoration/enabled.html), it says that setting it to false should hide helper/error and counter.  However, that was getting overridden and not working when passed as part of InputDecoration for a TextFormField.

## Related Issues

Closes https://github.com/flutter/flutter/issues/55632

For the record, enabled and its docs were originally added in https://github.com/flutter/flutter/pull/13734.

## Tests

I added a test that sets and unsets enabled and asserts the visibility of helper/error and counter are correct.

### CODE REVIEW

File: packages/flutter/test/material/text_field_test.dart [hunk 1]
```diff
@@ -3597,6 +3597,41 @@ void main() {
...
+                counterText: counterText,
+                enabled: enabled,
+              ),
+            ),
+          ),
+        ),
+      );
+    }
+
+    // When enabled is true, the helper and counter are visible.
```
Comment (HansMuller) [inline packages/flutter/test/material/text_field_test.dart:3620]: Shouldn't we be checking the errorText as well? https://api.flutter.dev/flutter/material/InputDecoration/enabled.html

Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart:3620]: I tried to be lazy and just check one because they're the same widget under the hood.  I'll add a check for both though :)

Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart]: Done.

**Review by HansMuller — APPROVED** [review]
LGTM. Nice fix!

**Comment by justinmc** [comment]
I ran this against Google's test suite and saw no related failures.
