### PR TITLE
Make Material/CupertinoLocalizations non-nullable

### LINKED ISSUE #43050: The getter 'cutButtonLabel' was called on null
when trying to paste on iOS simulator, using material library

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#8b81f](dirty, dependencies: [MediaQuery, _LocalizationsScope-[GlobalKey#0f48a]], state: _OverlayEntryState#b55de):
The getter 'cutButtonLabel' was called on null.
Receiver: null
Tried calling: cutButtonLabel
```

I think it happens only since last flutter upgrade, and it was working before

Screenshot 2019-10-19 at 08 20 45

Screenshot 2019-10-19 at 08 20 26

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A583, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.39.1)
[✓] Connected device (2 available)
```

### PR DESCRIPTION
**Pull request by goderbauer**
## Description

Throughout our code base we are assuming that `MaterialLocalizations.of` and `CupertinoLocalizations.of` return a non-null value. Let's make that explicit in the API by actually returning a non-nullable type and throwing a descriptive exception in case no Localizations could be found.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/43050.

## Tests

I added the following tests:

* tests for new methods added

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 1]
```diff
@@ -848,17 +848,16 @@ Future<T?> showMenu<T>({
   assert(captureInheritedThemes != null);
   assert(debugCheckHasMaterialLocalizations(context));
 
-  String? label;
+  String? label = semanticLabel;
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/popup_menu.dart:851]: Why can't we just use `semanticLabel` directly? i.e. remove this line and just use `semanticLabel` instead of `label` below?

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

File: packages/flutter/lib/src/material/popup_menu.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/material/popup_menu.dart]: We can! Changed it.

**Review by HansMuller — COMMENTED** [review]
This looks OK to me. Shi Hao should check it was well.

**Review by shihaohong — APPROVED** [review]
LGTM. This is great because the error message will now be much clearer than before and help users debug issues when Material/CupertinoLocalizations is not provided when it's needed.
