### PR TITLE
Fix: Submenu anchor misaligned with child panel in web (Resolved #151081)

### LINKED ISSUE #151081: [material/menu_anchor.dart] Submenu anchor misaligned with child panel
### Steps to reproduce

1. Run sample
2. Open menus

### Expected results

SubmenuButton and MenuItemButton should have the same vertical offset.

### Actual results

First MenuItemButton is above Submenu button text. It appears to be an offset of 8px. This may be because the menu is supposed to have 8px vertical padding applied to each menu panel.

I would normally do a PR, but I wasn't sure if this would need to be handled using Material 3 tokens.

### Code sample

<details open><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(const Bug());

class Bug extends StatelessWidget {
  const Bug({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorSchemeSeed: Colors.blue,
        brightness: Brightness.dark,
      ),
      home: const BugApp(),
    );
  }
}

class BugApp extends StatefulWidget {
  const BugApp({
    super.key,
  });

  @override
  State<BugApp> createState() => _BugAppState();
}

class _BugAppState extends State<BugApp> {
  FocusNode focusNode = FocusNode();
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            MenuBar(children: <Widget>[
              SubmenuButton(menuChildren: <Widget>[
                SubmenuButton(menuChildren: <Widget>[
                  MenuItemButton(
                    style: ButtonStyle(
                      backgroundColor: MaterialStateProperty.all(
                          Colors.white.withOpacity(0.1)),
                    ),
                    child: const Text('Item 1.1.1'),
                    onPressed: () {},
                  ),
                  MenuItemButton(
                    child: const Text('Item 1.1.2'),
                    onPressed: () {},
                  ),
                  MenuItemButton(
                    child: const Text('Item 1.1.3'),
                    onPressed: () {},
                  ),
                ], child: const Text('Submenu 1.1')),
              ], child: const Text('Submenu 1')),
            ])
          ],
        ),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Expected (from Angular Material):
image

Current: 
image

With 8px vertical offset applied: 
image

image

</details>

### Logs

<details open><summary>Logs</summary>

```console
None applicable
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.23.0-14.0.pre.50, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.23.0-14.0.pre.50 on channel master at /Users/davidhicks/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9a673175ab (4 days ago), 2024-06-27 09:42:21 +0200
    • Engine revision a9194f0f01
    • Dart version 3.5.0 (build 3.5.0-304.0.dev)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/davidhicks/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/davidhicks/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 126.0.6478.127
    ! Error: Browsing on the local area network for David’s iPhone. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Holly’s iPad. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

### PR DESCRIPTION
**Pull request by Vi-debug**
Fix: Submenu anchor misaligned with child panel in web (Resolved #151081)

- The issue comes from different in calculating the position of the menu in web and mobile.
- The calculation is currently base on function `getPositionForChild()` inside `_MenuLayout` in `menu_anchor.dart`, which base on the `anchorRect`
- The calculation of `anchorRect` is from `upperLeft` and `bottomRight`
- `upperLeft` is result of `localToGlobal()` function, which take the `point` arguments to be the base line. Right now, `point` is refer to `Offset.zero`, but it should not be Offset.zero since we having `densityAdjustment`, which is different between web and mobile
- Change `point` from `Offset.zero` to `Offset(dx, -dy)` should fix the error. Use `dx` instead of `-dx` since `dx` already be recalculated refer to the above comment on `densityAdjustment`.
Before:
Screenshot 2024-07-03 at 10 28 51
After:
Screenshot 2024-07-03 at 10 28 21

Issue: https://github.com/flutter/flutter/issues/151081

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by nate-thegrate — COMMENTED** [review]
You can see the output from failing tests by going to
**details** → **View more details on flutter-dashboard** → **stdout [raw]**

<details> <summary>I'll copy-paste the failing tests from <code>Linux framework_tests_libraries</code> (click to expand). Can you update these tests to reflect the new behavior?</summary>

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: [
            Rect:Rect.fromLTRB(161.0, 0.0, 639.0, 40.0),
            Rect:Rect.fromLTRB(265.0, 40.0, 467.0, 160.0),
            Rect:Rect.fromLTRB(467.0, 72.0, 707.0, 232.0)
          ]
  Actual: [
            Rect:Rect.fromLTRB(161.0, 0.0, 639.0, 40.0),
            Rect:Rect.fromLTRB(265.0, 40.0, 467.0, 160.0),
            Rect:Rect.fromLTRB(467.0, 80.0, 707.0, 240.0)
          ]
   Which: at location [2] is Rect:<Rect.fromLTRB(467.0, 80.0, 707.0, 240.0)> instead of
Rect:<Rect.fromLTRB(467.0, 72.0, 707.0, 232.0)>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (…/flutter/test/material/menu_anchor_test.dart:3179:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///b/s/w/ir/x/w/flutter/packages/flutter/test/material/menu_anchor_test.dart line 3179
The test description was:
  submenus account for compact menu density in LTR
════════════════════════════════════════════════════════════════════════════════════════════════════

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: [
            Rect:Rect.fromLTRB(161.0, 0.0, 639.0, 40.0),
            Rect:Rect.fromLTRB(333.0, 40.0, 535.0, 160.0),
            Rect:Rect.fromLTRB(93.0, 72.0, 333.0, 232.0)
          ]
  Actual: [
            Rect:Rect.fromLTRB(161.0, 0.0, 639.0, 40.0),
            Rect:Rect.fromLTRB(333.0, 40.0, 535.0, 160.0),
            Rect:Rect.fromLTRB(93.0, 80.0, 333.0, 240.0)
          ]
   Which: at location [2] is Rect:<Rect.fromLTRB(93.0, 80.0, 333.0, 240.0)> instead of
Rect:<Rect.fromLTRB(93.0, 72.0, 333.0, 232.0)>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (…/flutter/test/material/menu_anchor_test.dart:3195:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///b/s/w/ir/x/w/flutter/packages/flutter/test/material/menu_anchor_test.dart line 3195
The test description was:
  submenus account for compact menu density in RTL
════════════════════════════════════════════════════════════════════════════════════════════════════

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: Rect:<Rect.fromLTRB(249.0, 80.0, 483.0, 136.0)>
  Actual: Rect:<Rect.fromLTRB(257.0, 80.0, 491.0, 136.0)>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (…/flutter/test/material/menu_anchor_test.dart:257:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///b/s/w/ir/x/w/flutter/packages/flutter/test/material/menu_anchor_test.dart line 257
The test description was:
  Menu responds to density changes
════════════════════════════════════════════════════════════════════════════════════════════════════

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: Rect:<Rect.fromLTRB(366.0, 68.0, 559.0, 82.0)>
  Actual: Rect:<Rect.fromLTRB(372.0, 68.0, 565.0, 82.0)>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (…/flutter/test/material/menu_style_test.dart:281:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///b/s/w/ir/x/w/flutter/packages/flutter/test/material/menu_style_test.dart line 281
The test description was:
  visual density
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

File: packages/flutter/lib/src/material/menu_anchor.dart [hunk 1]
```diff
@@ -3547,6 +3540,12 @@ class _Submenu extends StatelessWidget {
     final EdgeInsetsGeometry resolvedPadding = padding
         .add(EdgeInsets.fromLTRB(dx, dy, dx, dy))
         .clamp(EdgeInsets.zero, EdgeInsetsGeometry.infinity);
+    final BuildContext anchorContext = anchor._anchorKey.currentContext!;
+    final RenderBox overlay = Overlay.of(anchorContext).context.findRenderObject()! as RenderBox;
+    final RenderBox anchorBox = anchorContext.findRenderObject()! as RenderBox;
+    final Offset upperLeft = anchorBox.localToGlobal(Offset(dx, -dy), ancestor: overlay);
```
[the remark this answers is not in the document]
Comment (Vi-debug) [reply packages/flutter/lib/src/material/menu_anchor.dart:3547]: Thanks. Hope to be merge

**Review by nate-thegrate — APPROVED** [review]
LGTM, thanks for making those test updates!

We'll be ready to merge once we get 1 more review 🙂

File: packages/flutter/test/material/menu_anchor_test.dart [hunk 2]
```diff
@@ -3181,7 +3181,7 @@ void main() {
         equals(const <Rect>[
           Rect.fromLTRB(161.0, 0.0, 639.0, 40.0),
           Rect.fromLTRB(265.0, 40.0, 467.0, 160.0),
-          Rect.fromLTRB(467.0, 72.0, 707.0, 232.0),
+          Rect.fromLTRB(467.0, 80.0, 707.0, 240.0)
```
Comment (bleroux) [inline packages/flutter/test/material/menu_anchor_test.dart:3184]:
```suggestion
          Rect.fromLTRB(467.0, 80.0, 707.0, 240.0),
```

Comment (Vi-debug) [reply packages/flutter/test/material/menu_anchor_test.dart]: Thank you a lot!

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d
