### PR TITLE
Make gallery tests more robust

### LINKED ISSUE #15809: transitions_perf_test in flutter/examples/gallery/flutter is timing out
transitions_perf_test in flutter/examples/gallery/flutter is timing out
This was noticed while doing a google3 roll of flutter.

```
00:02 +0: flutter gallery transitions all demos                                                                                                                                                        
00:02 +0: flutter gallery transitions all demos                                                                                                                                                        
Testing "Shrine" demo
Success
Testing "Contact profile" demo
Success
Testing "Animation" demo
Success
Testing "Bottom navigation" demo

00:12 +0 -1: flutter gallery transitions all demos [E]                                                                                                                                                 
  DriverError: Error in Flutter application: Timeout while executing scrollIntoView: TimeoutException after 0:00:05.000000: Future not completed
  #0      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:168)
  <asynchronous suspension>
  #1      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:370)
  <asynchronous suspension>
  #2      _runExtension (dart:developer-patch/dart:developer/developer.dart:85)
  
  Original error: null
  Original stack trace:
  null
      
  package:flutter_driver/src/driver/driver.dart 342:7                                                                 FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async                                                                                                          _Completer.completeError
  package:flutter_driver/src/driver/driver.dart                                                                       FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async                                                                                                          _asyncThenWrapperHelper
  package:flutter_driver/src/driver/driver.dart 319:68                                                                FlutterDriver._sendCommand
  package:flutter_driver/src/driver/driver.dart 413:18                                                                FlutterDriver.scrollIntoView
  ===== asynchronous gap ===========================
  dart:async                                                                                                          new Future.microtask
  package:flutter_driver/src/driver/driver.dart 412:109                                                               FlutterDriver.scrollIntoView
  ../../tmp/archives/third_party/dart/flutter/examples/gallery/flutter/test_driver/transitions_perf_test.dart 163:18  runDemos
  ===== asynchronous gap ===========================
  dart:async                                                                                                          _asyncThenWrapperHelper
  ../../tmp/archives/third_party/dart/flutter/examples/gallery/flutter/test_driver/transitions_perf_test.dart 159:73  runDemos
  ../../tmp/archives/third_party/dart/flutter/examples/gallery/flutter/test_driver/transitions_perf_test.dart 203:15  main.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                                                                          new Future.microtask
  ../../tmp/archives/third_party/dart/flutter/examples/gallery/flutter/test_driver/transitions_perf_test.dart 201:67  main.<fn>.<fn>.<fn>
  package:flutter_driver/src/driver/driver.dart 619:17                                                                FlutterDriver.traceAction
  ===== asynchronous gap ===========================
  dart:async                                                                                                          _asyncThenWrapperHelper
  package:flutter_driver/src/driver/driver.dart 614:12                                                                FlutterDriver.traceAction
  ../../tmp/archives/third_party/dart/flutter/examples/gallery/flutter/test_driver/transitions_perf_test.dart 201:46  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                                                                          new Future.microtask
  ../../tmp/archives/third_party/dart/flutter/examples/gallery/flutter/test_driver/transitions_perf_test.dart 199:32  main.<fn>.<fn>
  

```

### PR DESCRIPTION
**Pull request by HansMuller**
Added FlutterDriver.scrollUntilVisible() which repeatedly scrolls until a widget can be found before scrolling it into a particular alignment. This is useful when the scrolling container lazily creates its children.

The list of demos to be run (smoke_test, live_smoketest, transitions_perf) is now always based on kAllGalleryItems from examples/flutter_gallery/lib/gallery/item.dart.

Scrolling in transitions_perf.dart, which makes two passes through the gallery home page, now uses FlutterDriver.scrollUntilVisible().

Driver test uses of `await new Future<Null>.delayed(kWaitBetweenActions);` have been removed since FlutterDriver waits for things to settle down before issuing a new command.

For the moment backing out of the Backdrop demo is a special case. Likewise for the Cupertino "Pull to refresh" demo, but only for live_smoketest.dart.

Fixes https://github.com/flutter/flutter/issues/15809

### CODE REVIEW

File: examples/flutter_gallery/test/live_smoketest.dart [hunk 1]
```diff
@@ -11,30 +11,53 @@ import 'package:flutter/scheduler.dart';
...
+  'Pull to refresh',
+];
+
 Future<Null> main() async {
   try {
-    runApp(const GalleryApp());
+    // Verify that _kUnsynchronizedDemos and _kSkippedDemos identify
+    // demos that actually exist.
+    assert(new Set<String>.from(_kAllDemos).containsAll(_kUnsynchronizedDemos));
+    assert(new Set<String>.from(_kAllDemos).containsAll(_kSkippedDemos));
```
Comment (yjbanov) [inline examples/flutter_gallery/test/live_smoketest.dart]: There's no guarantee that this test will always with assertions. Because this is on-device test, it can run in profile or production mode. Can you make these just normal `if` checks with explicit call to `fail`?

File: examples/flutter_gallery/test_driver/transitions_perf_test.dart [hunk 2]
```diff
@@ -214,9 +187,12 @@ void main([List<String> args = const <String>[]]) {
       final String histogramPath = path.join(testOutputsDirectory, 'transition_durations.timeline.json');
       await saveDurationsHistogram(timeline.json['traceEvents'], histogramPath);
 
+      // Scroll back to the top
+      await driver.scroll(find.byType('CustomScrollView'), 0.0, 1000.0, const Duration(milliseconds: 100));
```
Comment (yjbanov) [inline examples/flutter_gallery/test_driver/transitions_perf_test.dart]: Maybe do `scrollUntilVisible` passing it the first item in the list? This way we don't have to use magic numbers, such as 1000.0.

File: packages/flutter_driver/lib/src/driver/driver.dart [hunk 3]
```diff
@@ -409,10 +409,70 @@ class FlutterDriver {
...
+  ///
+  /// If [item] is to the right of the the currently visible items, then
+  /// specify a negative value for [dxScroll] that's a small enough increment to
+  /// expose [item] without potentially scrolling it up and completely out of
+  /// view. Similarly if [item] is to the left, then specify a positve value
+  /// for [dyScroll].
+  ///
+  /// The [timeout] value should be long enough to accomodate as many scrolls
+  /// as needed to bring an item into view. The default is 10 seconds.
+  Future<Null> scrollUntilVisible (SerializableFinder scroller, SerializableFinder item, {
```
Comment (yjbanov) [inline packages/flutter_driver/lib/src/driver/driver.dart]: nit: for consistency let's refer to the scroller as "scrollable"
nit: remove space before `(`

File: packages/flutter_driver/lib/src/driver/driver.dart [hunk 4]
```diff
@@ -409,10 +409,70 @@ class FlutterDriver {
...
+  ///
+  /// If the widget located by [finder] is contained by a scrolling widget
+  /// that lazily creates its children, like [ListView] or [CustomScrollView],
+  /// then this method may fail because [finder] doesn't actually exist.
+  /// The [scrollUntilVisible] method can be used in this case.
   Future<Null> scrollIntoView(SerializableFinder finder, { double alignment: 0.0, Duration timeout }) async {
     return await _sendCommand(new ScrollIntoView(finder, alignment: alignment, timeout: timeout)).then((Map<String, dynamic> _) => null);
   }
 
+  /// If widget located by [item] is not visible then repeatedly [scroll] the
```
Comment (yjbanov) [inline packages/flutter_driver/lib/src/driver/driver.dart]: It's strange to begin a doc comment with a special condition. I'd just start with "Repeatedly"

File: packages/flutter_driver/lib/src/driver/driver.dart [hunk 5]
```diff
@@ -409,10 +409,70 @@ class FlutterDriver {
...
+  /// expose [item] without potentially scrolling it up and completely out of
+  /// view. Similarly if [item] is to the left, then specify a positve value
+  /// for [dyScroll].
+  ///
+  /// The [timeout] value should be long enough to accomodate as many scrolls
+  /// as needed to bring an item into view. The default is 10 seconds.
+  Future<Null> scrollUntilVisible (SerializableFinder scroller, SerializableFinder item, {
+    double alignment: 0.0,
+    double dxScroll: 0.0,
+    double dyScroll: -48.0,
```
Comment (yjbanov) [inline packages/flutter_driver/lib/src/driver/driver.dart]: You may not need to have the user specify these values if you implement the logic for this method in `extension.dart`. There you will have access to `RenderObject`s and their dimensions, and will be able to compute optimal `dx`/`dy` values. All we need to specify here is `AxisDirection`.

File: packages/flutter_driver/lib/src/driver/driver.dart [hunk 6]
```diff
@@ -409,10 +409,70 @@ class FlutterDriver {
...
+  /// without potentially scrolling it up and completely out of view. Similarly
+  /// if [item] is above, then specify a positve value for [dyScroll].
+  ///
+  /// If [item] is to the right of the the currently visible items, then
+  /// specify a negative value for [dxScroll] that's a small enough increment to
+  /// expose [item] without potentially scrolling it up and completely out of
+  /// view. Similarly if [item] is to the left, then specify a positve value
+  /// for [dyScroll].
+  ///
+  /// The [timeout] value should be long enough to accomodate as many scrolls
```
Comment (yjbanov) [inline packages/flutter_driver/lib/src/driver/driver.dart]: typo: accommodate

File: packages/flutter_driver/lib/src/driver/driver.dart [hunk 7]
```diff
@@ -409,10 +409,70 @@ class FlutterDriver {
...
+    assert(dyScroll != null);
+    assert(dxScroll != 0.0 || dyScroll != 0.0);
+    assert(timeout != null);
+
+    // If the item is already visible then we're done.
+    bool isVisible = false;
+    try {
+      await waitFor(item, timeout: const Duration(milliseconds: 100));
+      isVisible = true;
+    } on DriverError {
```
Comment (yjbanov) [inline packages/flutter_driver/lib/src/driver/driver.dart]: You also wouldn't need to do this if you implemented it in the extension.

File: examples/flutter_gallery/test_driver/transitions_perf_test.dart (hunk 2 above)
Comment (HansMuller) [reply examples/flutter_gallery/test_driver/transitions_perf_test.dart]: Done.

File: packages/flutter_driver/lib/src/driver/driver.dart (hunk 4 above)
Comment (HansMuller) [reply packages/flutter_driver/lib/src/driver/driver.dart]: Good point!

File: packages/flutter_driver/lib/src/driver/driver.dart (hunk 5 above)
Comment (HansMuller) [reply packages/flutter_driver/lib/src/driver/driver.dart]: Currently the scrollable is just a widget that contains the widget that will respond to scroll gestures. Locating the actual parent of the children that can be scrolled and inferring how they'll behave under scrolling (will they move at all? maybe just change size?) is a taller order than I think this PR warrants.

File: packages/flutter_driver/lib/src/driver/driver.dart (hunk 3 above)
Comment (HansMuller) [reply packages/flutter_driver/lib/src/driver/driver.dart]: Done

File: packages/flutter_driver/lib/src/driver/driver.dart (hunk 6 above)
Comment (HansMuller) [reply packages/flutter_driver/lib/src/driver/driver.dart]: Fxied

File: packages/flutter_driver/lib/src/driver/driver.dart (hunk 5 above)
Comment (yjbanov) [reply packages/flutter_driver/lib/src/driver/driver.dart]: Ok, if we expect the user to know how much they want to scroll, how about we default `dyScroll` to 0.0? It's strange that we pick a random number for Y but not X. If I want to scroll along the X axis, I will have to zero out `dyScroll` explicitly in the test script, but not when I want to scroll along Y.

Comment (HansMuller) [reply packages/flutter_driver/lib/src/driver/driver.dart]: Good point, I'll change that.

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
lgtm
