### PR TITLE
Fix InputDecorator suffix and prefix IconButtons ignore `IconButtonTheme`

### LINKED ISSUE #145081: DropdownMenu TrailingIcon can't be styled through providing an IconButtonTheme
### Steps to reproduce

The issue is that I want to style the `trailingIcon` of a `DropdownMenu` to not have a hover effect or splash factory. The `Icon` is internally represented by an `IconButton`. Therefore I want to wrap my DropdownMenu with an `IconButtonTheme` and provide the style this way. 
 
1. Create a `DropdownMenu` and wrap it with a `IconButtonTheme`
2. Observe that the properties set in the `IconButtonTheme` are not used to style the `trailingIcon`

### Expected results

I expect that the `IconButton` within the `DropdownMenu` finds the Theme in the widget tree and uses the provided values.
The same behavior which is displayed when just wrapping an `IconButton` in an `IconButtonTheme`. (as seen in the Example)

### Actual results

The `IconButton` which is wrapping the trailingIcon of the `DropdownMenu` is ignoring the properties provided by the `IconButtonTheme`.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            IconButtonTheme(
              data: IconButtonThemeData(
                style: ButtonStyle(
                  splashFactory: NoSplash.splashFactory,
                  overlayColor: MaterialStateProperty.all(Colors.transparent),
                ),
              ),
              child: IconButton(
                onPressed: () {
                  print('');
                },
                icon: const Icon(Icons.ac_unit),
              ),
            ),
            IconButtonTheme(
              data: IconButtonThemeData(
                style: ButtonStyle(
                  splashFactory: NoSplash.splashFactory,
                  overlayColor: MaterialStateProperty.all(Colors.transparent),
                ),
              ),
              child: DropdownMenu(
                dropdownMenuEntries: [
                  const DropdownMenuEntry(label: 'Item 1', value: 'Item 1'),

                ],
                trailingIcon: const Icon(Icons.arrow_drop_down),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/11629987/ca5f7b02-1fda-4e04-872a-1c7aa4dae91c

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale
    en-US)
    • Flutter version 3.19.3 on channel stable at
      /Users/felix/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/felix/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2023.3.4)
    • IntelliJ at /Users/felix/Applications/IntelliJ IDEA Community Edition.app
    • Flutter plugin version 78.3.1
    • Dart plugin version 233.13763.5

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.129

[✓] Network resources
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [DropdownMenu TrailingIcon can't be styled through providing an IconButtonTheme](https://github.com/flutter/flutter/issues/145081)

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: IconButtonTheme(
            data: IconButtonThemeData(
              style: IconButton.styleFrom(
                foregroundColor: const Color(0xffff0000),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10.0),
                ),
              ),
            ),
            child: SizedBox(
              width: 300,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Text('IconButton'),
                  IconButton(onPressed: () {}, icon: const Icon(Icons.search)),
                  const Text('TextField'),
                  TextField(
                    decoration: InputDecoration(
                      prefixIcon: IconButton(
                        onPressed: () {},
                        icon: const Icon(Icons.search),
                      ),
                      suffixIcon: IconButton(
                        onPressed: () {},
                        icon: const Icon(Icons.search),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Review by justinmc — APPROVED** [review]
LGTM :+1:  Thanks Taha glad you're back!

**Review by Piinks — COMMENTED** [review]
There are some customers that are broken by this. It looks like they'll need to update their code before we can land this.

Unless, could it be overriding a color value unexpectedly? Would an empty (null valued) theme here override the widget value?

Here is an example of one of the failures, the left is expected, the right is the result with this change:

Screenshot 2024-03-22 at 11 17 58 AM

**Comment by TahaTesser** [comment]
@justinmc @Piinks 

Parent `iconButtonTheme` isn't passed to `IconButton` in the prefix and suffix icons in the input decorator.

If this is a disruptive change, i could instead introduce `iconButtonTheme` to `DropdownMenuTheme` only and address the issue https://github.com/flutter/flutter/issues/145081. This shouldn't break the customer tests as it is not currently supported. 

https://github.com/flutter/flutter/blob/859eb2eda9818e408df046f5ff790cc9d5c28754/packages/flutter/lib/src/material/dropdown_menu_theme.dart#L31-L35

**Review by Piinks — COMMENTED** [review]
The affected customers may just be expecting the incorrect behavior, if so it should be relatively easy for them to be updated. We'll need to take a look at their code first. I think it make sense to inherit the theme in this way, rather than creating a special scenario for just DropdownMenu, but I'll defer to @justinmc. :)

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -2325,9 +2326,11 @@ class _InputDecoratorState extends State<InputDecorator> with TickerProviderStat
               ),
               child: IconButtonTheme(
                 data: IconButtonThemeData(
-                style: IconButton.styleFrom(
-                  foregroundColor: _getPrefixIconColor(themeData, defaults),
-                  iconSize: iconSize,
+                  style: iconButtonTheme.style?.merge(
```
Comment (justinmc) [inline packages/flutter/lib/src/material/input_decorator.dart:2329]: Sorry for the late response here!

I think maybe there is actually a problem that is being exposed by the Google test failures. The MaterialStateProperty colors in the iconButtonTheme here are not having the [materialState of the InputDecorator](https://github.com/flutter/flutter/blob/29ed214e7ffbf9a0aff94d31a691ee12ac07c253/packages/flutter/lib/src/material/input_decorator.dart#L2139) applied to them. See the example below.

<details>

<summary>I would expect the icon to be purple in this example, but it's lime</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        iconButtonTheme: IconButtonThemeData(
          style: ButtonStyle(
            foregroundColor: WidgetStateProperty.resolveWith((Set<WidgetState> states) {
              if (states.contains(WidgetState.error)) {
                return Colors.deepPurple;
              }
              return Colors.limeAccent;
            }),
          ),
        ),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              decoration: InputDecoration(
                errorText: 'error state',
                suffixIcon: IconButton(
                  onPressed: () {
                  },
                  icon: const Icon(Icons.phonelink_erase),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

Comment (TahaTesser) [reply packages/flutter/lib/src/material/input_decorator.dart]: Thanks so much for the details!

It turns out the inherited `IconButtonTheme.style.foreground` couldn't be overridden by `_getPrefixIconColor` & `_getPrefixIconColor` and resolve input decoration states.

I've updated both `_getPrefixIconColor` & `_getSuffixIconColor` to inherit the `IconButtonTheme.style.foreground` and resolve the state while placing in the order it can be superseded by `inputDecorationTheme` and `decoration.suffixIconColor`.

> I think maybe there is actually a problem that is being exposed by the Google test failures

Add two new tests to verify ``IconButtonTheme.style.foreground` color respects input decoration states  in the `input_decorator_test.dart`.

File: packages/flutter/test/material/input_decorator_test.dart [hunk 2]
```diff
@@ -4965,6 +4967,148 @@ void main() {
...
+    expect(material.color, backgroundColor);
+    expect(material.shape, shape);
+
+    expect(getIconStyle(tester, prefixIcon)?.color, foregroundColor);
+    expect(getIconStyle(tester, suffixIcon)?.color, foregroundColor);
+  });
+
+  testWidgets('Prefix IconButton color respects IconButtonTheme foreground color states', (WidgetTester tester) async {
+    const IconData prefixIcon = Icons.person;
+    const Color IconErrorColor = Color(0xffff0000);
```
Comment (justinmc) [inline packages/flutter/test/material/input_decorator_test.dart:5023]: Nit: This should be lower case right? iconErrorColor.

**Review by justinmc — APPROVED** [review]
LGTM with a nit :+1: 

Thanks for fixing that! That fixes my use case, and it looks like it fixed the Google tests too. Thanks for testing those cases as well.

File: packages/flutter/test/material/input_decorator_test.dart (hunk 2 above)
Comment (TahaTesser) [reply packages/flutter/test/material/input_decorator_test.dart:5023]: ooops... good catch!

**Comment by felixwoestmann** [comment]
@TahaTesser Thank you for taking on the issue I created!

However, I believe my complaint wasn't entirely fixed. 
I can confirm that by using the `foreground` color property I can now change the color of the Icon using the `IconButtonThemeData`. However I am not able to modify the `overlayColor`. The reason I want to do this is to get rid of the hover effect on the trailing Icon in favor of a hover effect on the whole component.

Is this just not intended for the Material DropdownMenu or am I using the properties wrongly?

**Comment by TahaTesser** [comment]
@felixwoestmann 
Thanks for the comment. I expected the `overlay` to work since we're merging the `iconButtonTheme.style`
```dart
  ).merge(iconButtonTheme.style),
```

I'll address this soon and add test that checks all `iconButtonTheme.style` properties.
