### PR TITLE
Fix date picker calendar tap targets (portrait mode)

### LINKED ISSUE #158325: DateTimePicker date buttons fail touch target size accessibility checks
### Steps to reproduce

1. Write some UI that invokes `showDatePicker`
2. Use an accessibility checker on the resulting UI, such as 
    ```dart
    await expectLater(
      tester,
      meetsGuideline(androidTapTargetGuideline),
    );
    ```

### Expected results

All user-interactable elements should have a minimum touch target size of at least 48dp x 48dp, as described at https://support.google.com/accessibility/android/answer/7101858.

### Actual results

The size of the individual day buttons is less than 48x48

### Code sample

<details open><summary>Code sample</summary>

App code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.light(useMaterial3: true),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(child: Text('Body')),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showDatePicker(
            context: context,
            initialDate: DateTime.now(),
            firstDate: DateTime(2024),
            lastDate: DateTime(2026),
          );
        },
        tooltip: 'Increment',
      ),
    );
  }
}
```

Test code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
// Import for file above
import 'package:hello_flutter.app/main.dart';

void main() {
  testWidgets('test', (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());

    final button = find.byType(FloatingActionButton);

    await tester.tap(button);

    await tester.pumpAndSettle();

    expect(find.byType(DatePickerDialog), findsOneWidget);
    await expectLater(
      tester,
      meetsGuideline(androidTapTargetGuideline),
    );
  });
}
```

</details>

### Screenshots or Video

Screenshots / Video demonstration: N/A

### Logs

Logs: N/A

### Flutter Doctor output

<details open><summary>Doctor output</summary>

N/A, Google internal client

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR fixes the touch target (and Semantic bounds) for day buttons shown in the date picker calendar mode.
To do so it changes the dialog size and buttons padding to conform to the M3 spec, see https://m3.material.io/components/date-pickers/specs#2d53890e-a08f-4c63-a0d9-abd9e95b4245

### Before

image

### After

image

## Related Issue

Fixes [DateTimePicker date buttons fail touch target size accessibility checks](https://github.com/flutter/flutter/issues/158325)

## Tests

Adds 1 test.

## Implementation choice

This PR targets only M3 and portrait mode:
- M3 because M2 dialog picker was not designed to be accessible (day buttons are 40 pixels).
- Portrait mode only, because there are no specification for the landscape mode and existing implementations (Google Calendar, Compose) vary. I will open a separate issue to discuss a possible solution for landscape mode.

### CODE REVIEW

**Comment by dkwingsmt** [comment]
Is this PR somehow related to https://github.com/flutter/flutter/pull/168284?

**Comment by bleroux** [comment]
> Is this PR somehow related to #168284?

While this PR main goal is to fix the accessibility issue it also fixes the button padding to make it compliant with the M3 spec, so yes this PR includes a change similar to #168284 (Adding a 4 pixels padding).

#168284 adds the padding unconditionnaly so it will be wrong on M2 (on M2 spec, there is no padding for buttons and buttons size was 40 pixels). On M3 the button size is 48 with 4.0 padding.

I also did not include a fix for landscape because the solution will need more discussions (I have a fix ready). The difficulty with landscape mode are:
- there are no spec to refer too.
- all the day buttons won't fit vertically on the screen (so my fix will introduce a SingleChildScrollView) to scroll vertically (similarly to Google Calendar).
- One remaining question will be to decide if we want to enforce the 48x48 tap area on landscape mode (Google Calendar doesn't: it uses 40x40 buttons on landscape mode and 48x48 on portrait).

Because of those complexities for landscape, I prefer to separate the PRs as the second one is more complex and might lead to some revert.

**Review by dkwingsmt — APPROVED** [review]

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 1]
```diff
@@ -27,11 +27,14 @@ import 'theme.dart';
 
 const Duration _monthScrollDuration = Duration(milliseconds: 200);
 
-const double _dayPickerRowHeight = 42.0;
+const double _dayPickerRowHeightM2 = 42.0;
+const double _dayPickerRowHeightM3 = 48.0;
```
[the remark this answers is not in the document]
Comment (bleroux) [reply packages/flutter/lib/src/material/calendar_date_picker.dart:31]: I had the same question.
It turned out that current implementation is not compliant with M2 spec neither. Instead of a 42 pixels row height it should have been 40 (and I just noticed that in M2 spec there was a 2 pixels padding), see:

image

Do you think it is worth updating the M2 implementation? I'm not at ease with reducing even more the touch target for M2 and I would prefer focusing on M3.

[the remark this answers is not in the document]
Comment (dkwingsmt) [reply packages/flutter/lib/src/material/calendar_date_picker.dart:31]: Yeah I agree. Can you somehow document this?

[the remark this answers is not in the document]
Comment (bleroux) [reply packages/flutter/lib/src/material/calendar_date_picker.dart:36]: I added some documentation, including links to the M2 and M3 specification.

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 2]
```diff
@@ -27,11 +27,20 @@ import 'theme.dart';
 
 const Duration _monthScrollDuration = Duration(milliseconds: 200);
 
-const double _dayPickerRowHeight = 42.0;
+// Current M2 implementation is not compliant with the M2 specification.
+// Instead of a 42 pixels row height it should be 40 with a 2 pixels inner padding.
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/calendar_date_picker.dart:31]:
```suggestion
// Instead of a 42 pixels row height it should be 40 with a 2 pixels inner padding.
// There is no plan to fix this since M2 is being deprecated.
```

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 3]
```diff
@@ -1191,6 +1202,12 @@ class _DayState extends State<_Day> {
       ),
     );
 
+    // Conform to M3 spec in portrait mode (landscape mode is not specified).
```
[the remark this answers is not in the document]
Comment (dkwingsmt) [reply packages/flutter/lib/src/material/calendar_date_picker.dart:1211]: Did you forget to push the change for this one?

File: packages/flutter/lib/src/material/calendar_date_picker.dart (hunk 2 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/material/calendar_date_picker.dart:31]: (Is it correct to call M2 being deprecated? I did not participate in the decision making.)

Comment (bleroux) [reply packages/flutter/lib/src/material/calendar_date_picker.dart:31]: AFAIK, there was no decision to deprecate M2. We usually focus on M3, but many PRs also fix M2 issues when possible.

File: packages/flutter/lib/src/material/calendar_date_picker.dart (hunk 3 above)
[the remark this answers is not in the document]
Comment (bleroux) [reply packages/flutter/lib/src/material/calendar_date_picker.dart]: Oh, good catch! I previously used the 'Commit suggestion' button but forgot to pull this change and erase it with a force push 😅

**Comment by dkwingsmt** [comment]
@bleroux I've checked the google testing failures. All failures are related to the the branded calendar widget's tap targets in landscape mode, which to my understanding is unexpected. In the failures the buttons are spread further apart horizontally. I'll take a look and see if I can find the cause.

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 4]
```diff
@@ -27,11 +27,20 @@ import 'theme.dart';
...
+const double _dayPickerRowHeightM3 = 48.0;
+
 const int _maxDayPickerRowCount = 6; // A 31 day month that starts on Saturday.
 // One extra row for the day-of-week header.
-const double _maxDayPickerHeight = _dayPickerRowHeight * (_maxDayPickerRowCount + 1);
-const double _monthPickerHorizontalPadding = 8.0;
+const double _maxDayPickerHeightM2 = _dayPickerRowHeightM2 * (_maxDayPickerRowCount + 1);
+const double _maxDayPickerHeightM3 = _dayPickerRowHeightM3 * (_maxDayPickerRowCount + 1);
+
+const double _monthPickerHorizontalPadding = 12.0;
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/calendar_date_picker.dart]: It seems to me that this line caused the google failures, as reverting this line alone makes the tests pass. I guess that this line affects both the portrait mode and the landscape mode. What surprises me is that the public golden tests don't contain any failures for landscape mode. Do you have an idea?

Comment (bleroux) [reply packages/flutter/lib/src/material/calendar_date_picker.dart]: Thanks for isolating this line :pray: 
I pushed a commit to apply the new value only when M3 and portrait (initially this PR contained both portrait and landscape fixes, I missed this line when I split this PR). 

> What surprises me is that the public golden tests don't contain any failures for landscape mode. Do you have an idea?

Oh, I checked and there are no golden test for landscape mode.
I will add one in my next PR which will target landscape only.

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 5]
```diff
@@ -27,11 +27,21 @@ import 'theme.dart';
...
+
 const int _maxDayPickerRowCount = 6; // A 31 day month that starts on Saturday.
 // One extra row for the day-of-week header.
-const double _maxDayPickerHeight = _dayPickerRowHeight * (_maxDayPickerRowCount + 1);
-const double _monthPickerHorizontalPadding = 8.0;
+const double _maxDayPickerHeightM2 = _dayPickerRowHeightM2 * (_maxDayPickerRowCount + 1);
+const double _maxDayPickerHeightM3 = _dayPickerRowHeightM3 * (_maxDayPickerRowCount + 1);
+
+const double _monthPickerHorizontalPaddingPortraitM3 = 12.0;
+const double _monthPickerHorizontalPaddingM2 = 8.0;
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/material/calendar_date_picker.dart]: The name is not correct. Maybe either of the following? (Or if you have better ideas)
```suggestion
const double _monthPickerHorizontalPaddingLandscapeM3 = 8.0;
const double _monthPickerHorizontalPaddingM2 = 8.0;
```
```suggestion
const double _monthPickerHorizontalPaddingOther = 8.0;
```

**Comment by bleroux** [comment]
@dkwingsmt Google testing are ok now. Can you have a last look to this PR?

**Review by dkwingsmt — APPROVED** [review]
LGTM, thank you!

**Comment by bleroux** [comment]
Now that the fix for the portait mode landed, I would like to discuss a solution for the landscape mode.

Some context:
- There is no specification for the date picker landscape mode.
- Currently the Flutter implementation makes sure that all days are visible (no scrolling). In landscape mode this means the height of each day does not meet a11y guidelines, see:
Screenshot 2025-06-17 at 13 32 02


I have a fix ready which:
- sets the minimum height for each day button to 48px
- makes it possible to scroll (needed because all day buttons won't fit if their height is set to 48px).
- Screen recording with the fix:

https://github.com/user-attachments/assets/51385f32-2c29-4657-8b2f-cde1c1f6b0dc

While meeting a11y guidelines, I'm not sure this is a solution we want as it makes few days visible without scrolling.

I tried to compare with other implementations:
- Compose does not implement a landscape mode for Date picker, so we can't get inspiration there.
- Google Calendar implements a landscape mode which show all days similarly to the Flutter date picker. The touch targets does not comply to a11y guideline. The motivation for this seems to be that, as soon as TalkBack is activated, the calendar view is automatically replaced by an input view where the user can enter the view:

https://github.com/user-attachments/assets/3c883d3c-f69d-4884-a01f-4395b41e67e3

@dkwingsmt @chunhtai 
For insights on choosing a solution for this a11y issue where we can't rely on a specification.

**Comment by dkwingsmt** [comment]
@bleroux Thanks for the write up. Before I share my 2 cents, can you repost it in a separate issue so that the discussion can be better tracked?
