### PR TITLE
fix: Inconsistency of SelectionArea when scrolling

### LINKED ISSUE #120892: Inconsistency of `SelectionArea` when scrolling
## Steps to Reproduce

There seems to be an inconsistency how selection is handled in combination within a scrollable. When performing a scroll on a `SelectionArea`, the selection is cleared. When performing a scroll on any other element, the selection remains.

### Case 1:

1. Execute `flutter run` on the code sample
2. Select text in the **"Selectable"** text block
3. Scroll on the **"Selectable"** text block

**Result:** The selection is cleared as soon as a scroll on text is done

### Case 2:

1. Execute `flutter run` on the code sample
2. Select text in the **"Selectable"** text block
3. Scroll on the **"Not Selectable"** text block

**Result:** The selection remains, and the selection handles can display outside the scroll viewport when scrolled.

https://user-images.githubusercontent.com/1659532/219412055-5f53a2d8-70be-400e-b2f7-d43694b917a3.mov

### Expected result

I am not 100% sure what the expected result here would be. For native applications, the selection remains when scrolled, and the selection handles are either removed or clipped when the selection is outside the scroll viewport.

For Flutter, it seems to bring some unintended issues which can be seen when doing **Case 2**. The selection handles can display outside the scroll viewport, which seems like a case not handled in the current implementation of selection.

To summarise: I would at least expect that selection handles do not display outside the scroll viewport, since this looks like a visual bug to the end user.

image

<details><summary>Code Sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(),
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.red,
          title: const Text("Selection Inconsistency"),
        ),
        body: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Column(
            children: [
              Text(
                "Selectable",
                style: Theme.of(context).textTheme.headline5,
              ),
              SelectionArea(child: Text("Lorem Ipsum " * 75)),
              const SizedBox(height: 100),
              Text(
                "Not Selectable",
                style: Theme.of(context).textTheme.headline5,
              ),
              Text("Lorem Ipsum " * 75),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>Flutter Doctor</summary>

```
[!] Flutter (Channel master, 3.8.0-13.0.pre.54, on macOS 12.2 21D49 darwin-arm64, locale en-DE)
    ! Upstream repository https://github.com/jankuss/flutter is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/jankuss/flutter to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

### PR DESCRIPTION
**Pull request by paurakhsharma**
This PR fixes inconsistency of SelectionArea when scrolling by removing the `_clearSelection` on `longPressUpdate` gesture. This in turn makes the selection UX much better.

*List which issues are fixed by this PR. You must list at least one issue.*
Fixes: https://github.com/flutter/flutter/issues/120892

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Renzo-Olivares** [comment]
Hi @paurakhsharma, thank you for your contribution! Can you explain how this pull request fixes the issue listed, i'm not sure I understand.

**Comment by paurakhsharma** [comment]
As mentioned by @gnprice in https://github.com/flutter/flutter/issues/120892#issuecomment-1596294084 I have updated the test to make sure `touchLongPressCancel` doesn't trigger any event. I am not sure if this is a valid way to trigger `toucnLongPressCancel`. Please let me know if there is a better way to test this.

**Comment by paurakhsharma** [comment]
For some reason I am unable to run tests locally, I am getting this error.

```
00:04 +0: ... /Users/paurakh/OpenSource-Contrib/flutter/packages/flutter/test/widgets/selectable_region_test.dart         ../../../../dev/flutter/packages/flutter_test/lib/src/_matchers_io.dart:27:39: Error: A value of type 'AbstractNode' can't
be assigned to a variable of type 'RenderObject'.
 - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('lib/src/foundation/node.dart').
 - 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('lib/src/rendering/object.dart').
    renderObject = renderObject.parent!;
                                      ^
../../../../dev/flutter/packages/flutter_test/lib/src/controller.dart:90:35: Error: A value of type 'AbstractNode?' can't
be assigned to a variable of type 'RenderObject?'.
 - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('lib/src/foundation/node.dart').
 - 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('lib/src/rendering/object.dart').
      renderObject = renderObject.parent;
                                  ^
../../../../dev/flutter/packages/flutter_test/lib/src/controller.dart:369:31: Error: A value of type 'AbstractNode' can't
be assigned to a variable of type 'RenderObject'.
 - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('lib/src/foundation/node.dart').
 - 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('lib/src/rendering/object.dart').
      current = current.parent!;
                              ^
00:13 +0 -1: loading /Users/paurakh/OpenSource-Contrib/flutter/packages/flutter/test/widgets/selectable_region_test.dart [E]
  Failed to load "/Users/paurakh/OpenSource-Contrib/flutter/packages/flutter/test/widgets/selectable_region_test.dart": Compilation failed for testPath=/Users/paurakh/OpenSource-Contrib/flutter/packages/flutter/test/widgets/selectable_region_test.dart
```

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 1]
```diff
@@ -310,6 +310,36 @@ void main() {
       expect(edgeEvent.globalPosition, const Offset(200.0, 50.0));
     });
 
+  testWidgets(
+    "touch long press cancel doesn't send ClearSelectionEvent",
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart:314]: nit: `doesn't` -> `does not`.

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 2]
```diff
@@ -310,6 +310,36 @@ void main() {
...
+      final RenderSelectionSpy renderSelectionSpy =
+          tester.renderObject<RenderSelectionSpy>(find.byKey(spy));
+      renderSelectionSpy.events.clear();
+      final TestGesture gesture =
+          await tester.startGesture(const Offset(200.0, 200.0));
+
+      addTearDown(gesture.removePointer);
+
+      await tester.pump(const Duration(milliseconds: 500));
+      await gesture.cancel();
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart:335]: This seems like a reasonable way of testing the cancel. I think we should also test the specific situation of the cancel in a scrollable as a regression test. Something like long press to select a word in a scrollable. Then try scrolling. The selection should be retained after the scroll.

Also add a regression test comment at the top of the test. Something like
`// Regression test for https://github.com/flutter/flutter/issues/128765`

**Review by Renzo-Olivares — CHANGES_REQUESTED** [review]

**Comment by Renzo-Olivares** [comment]
@chunhtai if you had any thoughts regarding this change.

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 3]
```diff
@@ -310,6 +310,86 @@ void main() {
...
+    'touch long press cancel does not send ClearSelectionEvent',
+    (WidgetTester tester) async {
+      final UniqueKey spy = UniqueKey();
+      await tester.pumpWidget(MaterialApp(
+        home: SelectableRegion(
+          focusNode: FocusNode(),
+          selectionControls: materialTextSelectionControls,
+          child: SelectionSpy(key: spy),
+        ),
+      ));
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart:323]: nit formatting: move trailing parentheses to their own line and separate with a comma.

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 4]
```diff
@@ -310,6 +310,86 @@ void main() {
...
+        );
+        await tester.pumpAndSettle();
+
+        final RenderSelectionSpy renderSelectionSpy =
+            tester.renderObject<RenderSelectionSpy>(find.byKey(spy));
+        final TestGesture selectGesture =
+            await tester.startGesture(const Offset(200.0, 200.0));
+        addTearDown(selectGesture.removePointer);
+        await tester.pump(const Duration(milliseconds: 500));
+
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/selectable_region_test.dart:373]: Maybe here instead of moving immediately after the long press we should just do `selectGesture.up()` and check for the `SelectWordSelectionEvent`. Then clear the events list with `renderSelectionSpy.events.clear()`. Then try a scroll gesture to see that `ClearSelectionEvent` is not sent. This would simulate taking our finger off the screen and then initiating a scroll.

**Review by Renzo-Olivares — COMMENTED** [review]
Thanks for all the changes! I had a few nits but overall the new test looks good.

File: packages/flutter/test/widgets/selectable_region_test.dart (hunk 4 above)
Comment (paurakhsharma) [reply packages/flutter/test/widgets/selectable_region_test.dart]: Thank you @Renzo-Olivares I have updated the PR accordingly.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM with one small nit. Thanks for the contribution!

File: packages/flutter/test/widgets/selectable_region_test.dart [hunk 5]
```diff
@@ -310,6 +310,82 @@ void main() {
...
+      final UniqueKey spy = UniqueKey();
+      await tester.pumpWidget(
+          MaterialApp(
+            home: SelectableRegion(
+              focusNode: FocusNode(),
+              selectionControls: materialTextSelectionControls,
+              child: SelectionSpy(key: spy),
+            ),
+          ),
+        );
```
[the remark this answers is not in the document]
Comment (paurakhsharma) [reply packages/flutter/test/widgets/selectable_region_test.dart]: Thank you, Done!

**Review by chunhtai — APPROVED** [review]
LGTM
