### PR TITLE
Fix InkRipple.cancel animation race

### LINKED ISSUE #14391: TextField's InkRipple.cancel can be called before InkRipple is built
Details filed internally.

@HansMuller

### PR DESCRIPTION
**Pull request by HansMuller**
Although difficult to reproduce interactively, it was possible for the `..value` part of this innocuous statement to cause _fadeOutController to be disposed before the `..animateTo` was reached.
```
      _fadeOutController
       ..value = 1.0 - _fadeInController.value // DISPOSE
       ..animateTo(1.0, duration: _kCancelDuration);
```

Fixes https://github.com/flutter/flutter/issues/14391

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM, but travis is angry.

File: packages/flutter/lib/src/material/ink_ripple.dart [hunk 1]
```diff
@@ -199,9 +199,14 @@ class InkRipple extends InteractiveInkFeature {
...
     _fadeInController.stop();
-    _fadeOutController
-      ..value = 1.0 - _fadeInController.value
-      ..animateTo(1.0, duration: _kCancelDuration);
+    // Watch out: setting _fadeOutController's value to 1.0 would
+    // trigger a call to _handleAlphaStatusChanged() which would
+    // dispose _fadeOutController.
+    if (_fadeInController.value > 0.0) {
+      _fadeOutController
+        ..value = 1.0 - _fadeInController.value
```
Comment (Hixie) [inline packages/flutter/lib/src/material/ink_ripple.dart]: for improved readability you may wish to factor out `1.0 - _fadeInController.value` and then in the if statement test that the factored out value is `< 1.0`, then the comment would be clearer

**Comment by HansMuller** [comment]
Oops - I forgot to include the change you suggested. I'll mix it in with https://github.com/flutter/flutter/pull/14410
