### PR TITLE
Provide an initial rotation of the ExpansionIcon if isExpanded = true on initState

### LINKED ISSUE #15650: When an ExpansionPanel is initialized with isExpanded: true, the arrow points down instead of up
## Steps to Reproduce

Minimal example in `lib/main.dart`:

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
        title: "Test",
        home: new Scaffold(
            appBar: new AppBar(
                title: new Text("Test"),
            ),
            body: new ListView(
                children: <Widget>[
                  new ExpansionPanelList(
                    children: <ExpansionPanel>[
                      new ExpansionPanel(
                          headerBuilder: (BuildContext context, bool isExpanded) => const Text("Test"),
                          body: const Text("Test"),
                          isExpanded: true,
                      ),
                    ],
                  ),
                ],
            ),
        ),
    );
  }
}
```

Result (on a real Nexus 6P running Android 8.1.0):

example_android

On an iPhone X simulator:

example_ios

Here I've just initialized the panel to expanded, but if I do that and provide a callback, in this manner:

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _isExpanded = true;

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
        title: "Test",
        home: new Scaffold(
            appBar: new AppBar(
                title: new Text("Test"),
            ),
            body: new ListView(
                children: <Widget>[
                  new ExpansionPanelList(
                    expansionCallback: (int panelIndex, bool isExpanded) {
                      setState(() {
                        _isExpanded = !isExpanded;
                      });
                    },
                    children: <ExpansionPanel>[
                      new ExpansionPanel(
                          headerBuilder: (BuildContext context, bool isExpanded) => const Text("Test"),
                          body: const Text("Test"),
                          isExpanded: _isExpanded,
                      ),
                    ],
                  ),
                ],
            ),
        ),
    );
  }
}
```

Then I get this behaviour: https://vimeo.com/260555109

## Logs

Run your application with `flutter run` and attach all the log output:

Real Nexus 6P:

```
Launching lib/main.dart on Nexus 6P in debug mode...
Initializing gradle...                                       0.9s
Resolving dependencies...                                    1.4s
Running 'gradlew assembleDebug'...                          16.9s
Built build/app/outputs/apk/debug/app-debug.apk (25.6MB).
Installing build/app/outputs/apk/app.apk...                  6.3s
I/FlutterActivityDelegate(21572): onResume setting current activity to this
Syncing files to device Nexus 6P...                          3.1s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Nexus 6P is available at: http://127.0.0.1:8101/
For a more detailed help message, press "h". To quit, press "q".

Taking screenshot for Nexus 6P...                           1,303ms
Screenshot written to flutter_01.png (75kB).
Lost connection to device.
```

iPhone X simulator:

```
Launching lib/main.dart on iPhone X in debug mode...
Running Xcode clean...                                       1.3s
Starting Xcode build...
 ├─Assembling Flutter resources...                    5.9s
 └─Compiling, linking and signing...                 16.6s
Xcode build done                                            25.8s
Syncing files to device iPhone X...                          2.5s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".

Taking screenshot for iPhone X...                           1,676ms
Screenshot written to flutter_01.png (70kB).
Lost connection to device.
```

Run `flutter analyze` and attach any output of that command also:

```
Analyzing /Users/eshan/Desktop/Projects/testapp...
No issues found!
Ran in 6.3s
```

## Flutter Doctor

Paste the output of running `flutter doctor -v` here:

```
[✓] Flutter (Channel dev, v0.2.2, on Mac OS X 10.13.1 17B1003, locale en-IN)
    • Flutter version 0.2.2 at /usr/local/flutter
    • Framework revision b9bd51cc36 (4 days ago), 2018-03-13 12:42:29 -0700
    • Engine revision e44cd55fc4
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/eshan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/eshan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (1 available)
    • Nexus 6P • CVH7N15B05005351 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes #15650

If an ExpansionIcon state is initially created with `isExpanded = true` it will not rotate the icon correctly.  Sets the initial value of the animation controller to `pi` radians if `isExpanded` is true in `initState()`, to rotate the icon without animating it.

### With fix
Top expansion icon is correctly pointed up when isExpanded is initially set to true.

### CODE REVIEW

File: packages/flutter/lib/src/material/expand_icon.dart [hunk 1]
```diff
@@ -1,6 +1,7 @@
 // Copyright 2015 The Chromium Authors. All rights reserved.
 // Use of this source code is governed by a BSD-style license that can be
 // found in the LICENSE file.
+import 'dart:math';
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/expand_icon.dart]: Flutter standard is to import math like so:

import 'dart:math' as math;

(Just because some of the values in math have very short names, like pi and e, that might conflict.)

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d
(modulo minor nit)

File: packages/flutter/lib/src/material/expand_icon.dart (hunk 1 above)
Comment (jonahwilliams) [reply packages/flutter/lib/src/material/expand_icon.dart]: Done!
