### PR TITLE
[Impeller] Fix fail to render pixel buffer texture on Linux

### LINKED ISSUE #181483: [Impeller] Fail to render pixel buffer texture on Linux
### Steps to reproduce

1.Down load pixel buffer sample code(https://github.com/xiaowei-guan/pixel_buffer_test)
2.flutter run --enable-impeller on ubuntu 20.04

### Expected results

Can render a image successful by texture.

### Actual results

No image to show

### Code sample

<details open><summary>Code sample</summary>

https://github.com/xiaowei-guan/pixel_buffer_test.git

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console

guanxw@samsung10022:~/linux/pixel_buffer_test/example$ ~/linux/flutter/bin/flutter run --enable-impeller
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
✓ Built build/linux/x64/debug/bundle/pixel_buffer_test_example
[IMPORTANT:flutter/shell/platform/embedder/embedder_surface_gl_impeller.cc(99)] Using the Impeller rendering backend (OpenGL).

** (com.example.pixel_buffer_test:2255040): CRITICAL **: 01:36:48.868: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (com.example.pixel_buffer_test:2255040): CRITICAL **: 01:36:48.869: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
textureId ::::::::::::::::::::::::::::::::::-1
Syncing files to device Linux...                                    38ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Linux is available at: http://127.0.0.1:36925/16O6sO2S0K0=/
The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:36925/16O6sO2S0K0=/devtools/?uri=ws://127.0.0.1:36925/16O6sO2S0K0=/ws
register_pixel_buffer method called
Image path: assets/texture.jpg
register_pixel_buffer started
Attempting to load image: assets/texture.jpg
Executable directory: /home/guanxw/linux/pixel_buffer_test/example/build/linux/x64/debug/bundle
Constructed asset path: /home/guanxw/linux/pixel_buffer_test/example/build/linux/x64/debug/bundle/data/flutter_assets/assets/texture.jpg
Full path: /home/guanxw/linux/pixel_buffer_test/example/build/linux/x64/debug/bundle/data/flutter_assets/assets/texture.jpg
create_texture_from_image returned
Successfully loaded image, registering texture
Successfully registered texture
About to get texture ID
Got texture ID: 64198912
About to store texture
Stored texture
Texture ID: 64198912
About to create result
Created result with texture ID: 64198912
About to create response
Created response
register_pixel_buffer returned
textureId ::::::::::::::::::::::::::::::::::64198912
[ERROR:flutter/impeller/renderer/backend/gles/texture_gles.cc(220)] Break on 'ImpellerValidationBreak' to inspect point of failure: Invalid texture descriptor.
[ERROR:flutter/shell/platform/embedder/embedder_external_texture_gl.cc(157)] Could not create external texture
[ERROR:flutter/impeller/renderer/backend/gles/texture_gles.cc(220)] Break on 'ImpellerValidationBreak' to inspect point of failure: Invalid texture descriptor.
[ERROR:flutter/shell/platform/embedder/embedder_external_texture_gl.cc(157)] Could not create external texture
[ERROR:flutter/impeller/renderer/backend/gles/texture_gles.cc(220)] Break on 'ImpellerValidationBreak' to inspect point of failure: Invalid texture descriptor.
[ERROR:flutter/shell/platform/embedder/embedder_external_texture_gl.cc(157)] Could not create external texture
[ERROR:flutter/impeller/renderer/backend/gles/texture_gles.cc(220)] Break on 'ImpellerValidationBreak' to inspect point of failure: Invalid texture descriptor.
[ERROR:flutter/shell/platform/embedder/embedder_external_texture_gl.cc(157)] Could not create external texture

Application finished.

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
guanxw@samsung10022:~/linux/pixel_buffer_test/example$ ~/linux/flutter/bin/flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.41.0-1.0.pre-206, on Ubuntu 20.04.5 LTS 5.15.0-139-generic, locale en_US.UTF-8)
    ! Flutter version 3.41.0-1.0.pre-206 on channel [user-branch] at /home/guanxw/linux/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Warning: `flutter` on your path resolves to /home/guanxw/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/guanxw/linux/flutter. Consider adding /home/guanxw/linux/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /home/guanxw/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /home/guanxw/linux/flutter. Consider adding /home/guanxw/linux/flutter/bin to the front of your path.
    ! Upstream repository https://github.com/xiaowei-guan/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/xiaowei-guan/flutter.git to dismiss this error.
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
    ! Unable to access driver information using 'eglinfo'.
      It is likely available from your distribution (e.g.: apt install mesa-utils)
[!] Proxy Configuration
    ! NO_PROXY does not contain ::1
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 3 categories.

```

</details>

### PR DESCRIPTION
**Pull request by xiaowei-guan**
Fix https://github.com/flutter/flutter/issues/181483

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/embedder/embedder_external_texture_gl.cc [hunk 1]
```diff
@@ -140,11 +140,12 @@ sk_sp<DlImage> EmbedderExternalTextureGL::ResolveTextureImpeller(
 
   impeller::TextureDescriptor desc;
   desc.size = impeller::ISize(texture->width, texture->height);
+  desc.format = impeller::PixelFormat::kR8G8B8A8UNormInt;
```
[the remark this answers is not in the document]
Comment (xiaowei-guan) [reply engine/src/flutter/shell/platform/embedder/embedder_external_texture_gl.cc:148]: impeller/renderer/backend/gles/formats_gles.h doesn't have ToPixelFormat method.

**Review by gaaclarke — COMMENTED** [review]
@xiaowei-guan this PR doesn't have a test, unfortunately I'm not that familiar with this code so I can't give you a pointer on the best way to test it and I'm not readily seeing unit testing set up here.  I cannot approve it without some sort of test though.

**Comment by xiaowei-guan** [comment]
> @xiaowei-guan this PR doesn't have a test, unfortunately I'm not that familiar with this code so I can't give you a pointer on the best way to test it and I'm not readily seeing unit testing set up here. I cannot approve it without some sort of test though.

OK, I will add unit test later.

File: engine/src/flutter/shell/platform/embedder/embedder_external_texture_gl.cc [hunk 2]
```diff
@@ -165,6 +166,8 @@ sk_sp<DlImage> EmbedderExternalTextureGL::ResolveTextureImpeller(
     FML_LOG(ERROR) << "Could not register destruction callback";
     return nullptr;
   }
+  image->SetCoordinateSystem(
+      impeller::TextureCoordinateSystem::kUploadFromHost);
```
Comment (gaaclarke) [inline engine/src/flutter/shell/platform/embedder/embedder_external_texture_gl.cc:175]: Because the texture we are rendering is a flat red color, we aren't testing that this call is orienting the texture correctly.

I know the metal test just makes a flat color, but if we made the texture red on the top half and blue on the bottom half we could assert that the orientation is correct.

**Review by gaaclarke — CHANGES_REQUESTED** [review]
This is awesome, thanks.  Can you make one change though please, can you make the texture sensitive to orientation so we can assert your change to the images coordinate system?

File: engine/src/flutter/shell/platform/embedder/embedder_external_texture_gl.cc (hunk 2 above)
Comment (xiaowei-guan) [reply engine/src/flutter/shell/platform/embedder/embedder_external_texture_gl.cc:175]: Done

**Review by gaaclarke — APPROVED** [review]
lgtm! thanks

File: engine/src/flutter/shell/platform/embedder/embedder_external_texture_gl.cc (hunk 1 above)
[the remark this answers is not in the document]
Comment (jason-simmons) [reply engine/src/flutter/shell/platform/embedder/embedder_external_texture_gl.cc:148]: Add a check that logs an error and returns null if `texture->format` is not `GL_RGBA8`.

(We could also add an Impeller helper function that maps GL formats to Impeller formats.  But for now I think it's sufficient to only support `GL_RGBA8`)

File: engine/src/flutter/shell/platform/embedder/tests/embedder_gl_unittests.cc [hunk 3]
```diff
@@ -4829,6 +4829,87 @@ TEST_F(EmbedderTest, CanRenderWithImpellerOpenGL) {
...
+    }
+
+    GLuint gl_texture;
+    glGenTextures(1, &gl_texture);
+    glBindTexture(GL_TEXTURE_2D, gl_texture);
+    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, 800, 600, 0, GL_RGBA,
+                 GL_UNSIGNED_BYTE, buffer.data());
+    texture->target = GL_TEXTURE_2D;
+    texture->name = gl_texture;
+    texture->format = GL_RGBA;
```
Comment (jason-simmons) [inline engine/src/flutter/shell/platform/embedder/tests/embedder_gl_unittests.cc]: Set `texture->format` to `GL_RGBA8` here.

**Review by jason-simmons — COMMENTED** [review]
Thanks for fixing this!

File: engine/src/flutter/shell/platform/embedder/tests/embedder_gl_unittests.cc (hunk 3 above)
Comment (xiaowei-guan) [reply engine/src/flutter/shell/platform/embedder/tests/embedder_gl_unittests.cc]: Done

File: engine/src/flutter/shell/platform/embedder/embedder_external_texture_gl.cc (hunk 1 above)
[the remark this answers is not in the document]
Comment (xiaowei-guan) [reply engine/src/flutter/shell/platform/embedder/embedder_external_texture_gl.cc:148]: Done

**Review by jason-simmons — APPROVED** [review]

**Comment by xiaowei-guan** [comment]
Rebase again

**Comment by gaaclarke** [comment]
It's reporting a merge conflict, I tried to hit the button to attempt again but no luck.  There is zero feedback about where the merge conflict is happening.  I'll try reaching out to someone that works on this tool.
