### PR TITLE
Fix selection not deselected when TextField loses focus

### LINKED ISSUE #103341: Textfield selection is not deselected after it loses focus
**sample :**
```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: const [
              TextField(),
              TextField(),
            ],
          ),
        ),
      ),
    );
  }
}
```

just type anything in two textfield and select text

image

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.13.0-0.0.pre.986, on macOS 12.3.1 21E258 darwin-arm, locale en-IR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.2)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
## Description
The original issue was introduced by #101954 because the `selectionColor` on `EditableText` was never null. Previously null was passed to `EditableText` to paint no selection when it did not have focus. https://github.com/flutter/flutter/blob/5464c5bac742001448fe4fc0597be939379f88ea/packages/flutter/lib/src/material/text_field.dart#L1244 This change allows the selectionColor on `EditableText` to be null again by only taking `widget.selectionColor` and not inheriting `DefaultSelectionStyle.of(context)`.

## Related Issues
Fixes #103341

## Tests
Added tests to ensure selectionColor is dropped when focus is lost on TextField, and add regression test.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/widgets/editable_text_test.dart [hunk 1]
```diff
@@ -660,7 +660,8 @@ void main() {
     expect(focusNode.hasFocus, isFalse);
   });
 
-  testWidgets('use DefaultSelectionStyle for selection color', (WidgetTester tester) async {
+  testWidgets('selection color can be null with DefaultSelectionStyle as parent', (WidgetTester tester) async {
```
Comment (chunhtai) [inline packages/flutter/test/widgets/editable_text_test.dart:663]: Maybe rename to `EditableText does not derive selection color from DefaultSelectionStyle`

**Review by chunhtai — APPROVED** [review]
LGTM

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 2]
```diff
@@ -433,6 +433,62 @@ void main() {
     },
   );
 
+  testWidgets('Text field drops selection color when losing focus', (WidgetTester tester) async {
```
Comment (justinmc) [inline packages/flutter/test/cupertino/text_field_test.dart:436]: Nit: Is it relevant to say "Regression test for https://github.com/flutter/flutter/issues/103341" here and elsewhere?

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

Just as a thought, what if we passed a transparent Color as selectionColor instead of null?

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/test/cupertino/text_field_test.dart:436]: > LGTM 👍
> 
> Just as a thought, what if we passed a transparent Color as selectionColor instead of null?

That works too. Though if someone explicitly passes `null` as `selectionColor` to `EditableText`. I think they would expect no selection to be painted, where as now it defaults to the color defined by `DefaultSelectionStyle.of(context)`.

Comment (chunhtai) [reply packages/flutter/test/cupertino/text_field_test.dart:436]: I don't have a strong opinion on this, but if I were to redesign this again, passing null as color means disabling the selection seems to be a weird API

Comment (Renzo-Olivares) [reply packages/flutter/test/cupertino/text_field_test.dart:436]: I agree, though another small difference between `null` and `Colors.transparent` is that the TextHighlightPainter skips painting all together when the `selectionColor` is null vs when it is `Colors.transparent` it will still paint some values. https://github.com/flutter/flutter/blob/df7111a848cb0cc076a9c89d48332f0ec2700c45/packages/flutter/lib/src/rendering/editable.dart#L2726
