### PR TITLE
Address frame policy benchmark flakes

### LINKED ISSUE #150542: Microbenchmarks flaky; "Null check operator used on a null value"
When I run the venerable `stocks/build_bench.dart` microbenchmark, it sometimes prints an error with a stack trace. On my Pixel 8, I tried it in a loop just now and it happened on the 8th try; so the failure rate seems like something in the neighborhood of 10-15%.

I noticed this because I was getting a similar error while developing the new benchmarks I just sent as #150539. I debugged a little and it didn't seem related to anything specific to my code, so I was curious whether an existing benchmark had the same symptom. Turns out it does.

I don't know how many different benchmarks are affected. I picked `stocks/build_bench.dart` because it seemed the most similar to what I was doing; in particular it's one of three that use `WidgetTester.pumpBenchmark`.

Curiously it does still print results. The results are even consistent with the results I saw on non-error runs.

Full output:
```
$ time flutter run --release lib/stocks/build_bench.dart 
Launching lib/stocks/build_bench.dart on Pixel 8 in release mode...
Warning: unable to detect project KGP version. Skipping version checking. 
This may be because you have applied KGP after the Flutter Gradle Plugin.
Running Gradle task 'assembleRelease'...                         1,172ms
✓ Built build/app/outputs/flutter-apk/app-release.apk (35.3MB)

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter (10573): (The following exception is now available via WidgetTester.takeException:)
I/flutter (10573): Null check operator used on a null value
I/flutter (10573): #0      WidgetTester.pumpBenchmark (package:flutter_test/src/widget_tester.dart:688)
I/flutter (10573): <asynchronous suspension>
I/flutter (10573): #1      runBuildBenchmark.<anonymous closure> (package:microbenchmarks/stocks/build_bench.dart:48)
I/flutter (10573): <asynchronous suspension>
I/flutter (10573): #2      benchmarkWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:451)
I/flutter (10573): <asynchronous suspension>
I/flutter (10573): #3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1025)
I/flutter (10573): <asynchronous suspension>
I/flutter (10573): #4      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:817)
I/flutter (10573): <asynchronous suspension>
I/flutter (10573): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
I/flutter (10573): Null check operator used on a null value
I/flutter (10573): #0      WidgetTester.pumpBenchmark (package:flutter_test/src/widget_tester.dart:688)
I/flutter (10573): <asynchronous suspension>
I/flutter (10573): #1      runBuildBenchmark.<anonymous closure> (package:microbenchmarks/stocks/build_bench.dart:48)
I/flutter (10573): <asynchronous suspension>
I/flutter (10573): #2      benchmarkWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:451)
I/flutter (10573): <asynchronous suspension>
I/flutter (10573): #3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1025)
I/flutter (10573): <asynchronous suspension>
I/flutter (10573): #4      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:817)
I/flutter (10573): <asynchronous suspension>
E/flutter (10573): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Test failed. See exception logs above.
E/flutter (10573): 
I/flutter (10573): ================ RESULTS ================
I/flutter (10573): :::JSON::: {"stock_build_iteration":535.2731213872833,"stock_build_iteration_probability_5pct":0.034504185823212435}
I/flutter (10573): ================ FORMATTED ==============
I/flutter (10573): Stock build: 535.3 µs per iteration
I/flutter (10573): Stock build - probability margin of error 0.05: 0.0 percent

Application finished.

time: 17.312s wall (2.835s u, 0.461s s)
```

### LINKED ISSUE #150543: pumpBenchmark loses stack trace from caught exceptions
In `WidgetTester.pumpBenchmark`, if the calls to either `handleBeginFrame` or `handleDrawFrame` throw an exception, the exception is caught and rethrown.

One effect of this is that the whole stack trace from the original `throw` up to `pumpBenchmark` gets erased; the only stack trace that's printed is the one from `pumpBenchmark` outward.

That can make it hard to debug an issue. For example in #150542 (or #148845) the exception output looks like this:
```
Null check operator used on a null value
#0      WidgetTester.pumpBenchmark (package:flutter_test/src/widget_tester.dart:688)
<asynchronous suspension>
#1      runBuildBenchmark.<anonymous closure> (package:microbenchmarks/stocks/build_bench.dart:48)
[… then more frames out from there …]
```

There's no null-check operator on that line `widget_tester.dart:688` — all it does is:
```dart
      throw caughtException as Object;
```
So the null-check operator in question could be practically anywhere in the codebase.

I think the main ingredient for fixing this is [`Error.throwWithStackTrace`](https://api.dart.dev/stable/3.4.4/dart-core/Error/throwWithStackTrace.html). That feature was new in Dart 2.16.

### PR DESCRIPTION
**Pull request by jtmcdole**
Recently the microbenchmarks were flakey, but from an older bug. Turns out, `LiveTestWidgetsFlutterBindingFramePolicy` is defaulted to `fadePointers` with this fun note:

> This can result in additional frames being pumped beyond those that
the test itself requests, which can cause differences in behavior

Both `text_intrinsic_bench` and `build_bench` use a similar pattern:
* Load stocks app
* Open the menu
* Switch to `benchmark` frame policy

What happens, rarely, is that
`LiveTestWidgetsFlutterBinding.pumpBenchmark()` will call (async) `handleBeginFrame` and `handleDrawFrame`. `handleDrawFrame` juggles a tri-state boolean (null, false, true). This boolean is only reset to `null` when handleDrawFrame is called back to back, say, from an extra frame that was scheduled.

1. Switch tri-state boolean to an enum, its easier to read
2. remove asserts that compile away in benchmarks (`--profile`)
3. use `Error.throwWithStackTrace` to keep stack traces.

I've been running this test on device lab hardware for hundreds of runs and have not hit a failure yet.

Fixes #150542
Fixes #150543 - throw stack!

### CODE REVIEW

**Comment by Hixie** [comment]
Generally pumpAndSettle is a red flag because it means the test is not going to be sensitive to changes in behaviour (e.g. if we start pumping more frames than expected, it'll just be silently accepted). In this case this isn't really a test so it's probably fine? It'd be good to know why we're getting these extra frames sometimes and fix that, though. I would only expect `fadePointers` to pump more frames when the user touches the screen, which shouldn't happen in a benchmark like this in theory...

Also, can we switch to benchmark mode earlier maybe?

Either way, LGTM.

**Review by Hixie — APPROVED** [review]
LGTM

File: packages/flutter_test/lib/src/widget_tester.dart [hunk 1]
```diff
@@ -683,15 +683,19 @@ class WidgetTester extends WidgetController implements HitTestDispatcher, Ticker
...
+    }
 
     await Future<void>.microtask(() { binding.handleBeginFrame(duration); }).catchError(handleError);
     await idle();
     await Future<void>.microtask(() { binding.handleDrawFrame(); }).catchError(handleError);
     await idle();
 
     if (caughtException != null) {
-      throw caughtException as Object; // ignore: only_throw_errors, rethrowing caught exception.
+      Error.throwWithStackTrace(caughtException as Object, stackTrace!);
```
Comment (Hixie) [inline packages/flutter_test/lib/src/widget_tester.dart:698]: nice, is this api new? there's probably other places we could do this

Comment (gnprice) [reply packages/flutter_test/lib/src/widget_tester.dart:698]: It was new in Dart 2.16:
https://api.dart.dev/stable/3.4.4/dart-core/Error/throwWithStackTrace.html

It is indeed a nice feature!

Comment (jtmcdole) [reply packages/flutter_test/lib/src/widget_tester.dart:698]: I was scratching my head looking at this saying "there's got to be another way" and then I found the bug you filed, @Hixie, wanting exactly this. The VM team has the suggestion there to use this new API.

Comment (jtmcdole) [reply packages/flutter_test/lib/src/widget_tester.dart:698]: breadcrumbs: https://github.com/dart-lang/sdk/issues/35494 -> https://github.com/dart-lang/sdk/issues/30741#issuecomment-1127514020
