### PR TITLE
Fix hit-testing order in semantics

### LINKED ISSUE #163576: [Web] SemanticsBinding.instance.ensureSemantics() is propagating click on overlapping widgets
As title says. 

I'm using **Autocomplete** and **ListTile** to exemplify.

### Steps to reproduce

1. Create a app with SemanticsBinding.instance.ensureSemantics() in the main method;
2. Add the Autocomplete and ListTile with onTap();
3. Use Autocomplete and tap an option.

### Expected results

Since the Autocomplete is being used, so the option item should get the user's click.

### Actual results

But what happen is that the click "leaks" to the ListTile under it. The Autocomplete doesn’t identified the click, but the ListTile does.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SemanticsBinding.instance.ensureSemantics();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          SearchWidget(),
          for (int i = 0; i < 10; i++)
            ListTile(
              onTap: () {
                debugPrint('You just tapped on item $i');
              },
              title: Text('Item $i'),
            ),
        ],
      ),
    );
  }
}

class SearchWidget extends StatelessWidget {
  const SearchWidget({super.key});

  @override
  Widget build(BuildContext context) {
    const List<String> kOptions = <String>[
      'Apple',
      'Banana',
      'Cherry',
      'Date',
      'Fig',
      'Grape',
      'Kiwi',
      'Lemon',
      'Mango',
      'Nectarine',
      'Orange',
      'Peach',
      'Pear',
      'Quince',
      'Raspberry',
      'Strawberry',
      'Tangerine',
      'Ugli fruit',
      'Watermelon',
    ];

    return Autocomplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) async {
        if (textEditingValue.text.isEmpty) {
          return const Iterable<String>.empty();
        }
        return kOptions.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      onSelected: (item) {
        debugPrint('You just selected $item');
      },
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Without SemanticsBinding:

https://github.com/user-attachments/assets/5fba7b13-ffd1-4bfb-891d-9eb91c811bdf

With SemanticsBinding:

https://github.com/user-attachments/assets/6ae3945a-3b4d-4c9e-9410-219c2e42cf74

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.3.1 24D70 darwin-x64, locale pt-BR) [721ms]
    • Flutter version 3.29.0 on channel stable at /Users/ion/workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (8 days ago), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [2,6s]
    • Android SDK at /Users/ion/Library/Android/sdk
    • Platform android-35, build-tools 35.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2) [1.521ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [70ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [69ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] IntelliJ IDEA Community Edition (version 2024.3.3) [66ms]
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.97.2) [30ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.104.0

[✓] Connected device (2 available) [6,8s]
    • macOS (desktop) • macos  • darwin-x64     • macOS 15.3.1 24D70 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 133.0.6943.99

[✓] Network resources [469ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by QuncCccccc**
Fixes https://github.com/flutter/flutter/issues/163576

In `updateWith()` method, `_replaceChildren()` is called to generate `_children` list. `_children` list is used to generate the hit test order (`childrenInHitTestOrder`).

In `_replaceChildren()`, `childrenIn**Inverse**PaintOrder` is directly assigned to _children, so _children itself follows hit test order. So when we generate the `childrenInHitTestOrder`, we don't need to reverse the children again.

https://github.com/user-attachments/assets/df9d852f-231e-4480-8d8b-10c1d406f120

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 1]
```diff
@@ -3480,11 +3480,11 @@ class SemanticsNode with DiagnosticableTreeMixin {
...
         childrenInTraversalOrder[i] = sortedChildren[i].id;
       }
-      // _children is sorted in paint order, so we invert it to get the hit test
+      // _children is sorted in inversed paint order, so we use it to get the hit test
       // order.
       childrenInHitTestOrder = Int32List(childCount);
-      for (int i = childCount - 1; i >= 0; i -= 1) {
-        childrenInHitTestOrder[i] = _children![childCount - i - 1].id;
+      for (int i = 0; i < childCount; i += 1) {
+        childrenInHitTestOrder[i] = _children![i].id;
```
Comment (chunhtai) [inline packages/flutter/lib/src/semantics/semantics.dart:3487]: This is surprising, does this mean we always get it wrong?

Comment (chunhtai) [reply packages/flutter/lib/src/semantics/semantics.dart:3487]: after reading the code more I think the original documentation may be wrong

_children is assigned with the `childrenInInversePaintOrder` in `SemanticsNode.updateWith`.

which is called in `_buildSemanticsSubtree` where the children is the same as `_childrenAndElevationAdjustments` order and I think by default the _childrenAndElevationAdjustments order is insertion order which will be RenderObject.visitChildForSemantics, which is the paint order.

so the the original code should be current but just bad name.

Comment (QuncCccccc) [reply packages/flutter/lib/src/semantics/semantics.dart:3479]: Just an update. Talked with @chunhtai offline. It seems the hit test order was incorrect all the time. But previously when we haven't applied `OverlayPortal` to any widgets, if we push a new route, the items underneath the new route will be thrown away so the hit test only need to handle one "layer" of items and everything is okay. After `OverlayPortal` is applied to `Autocomplete`,  the items underneath the popup still stay in the tree, and the hit test order starts show problems.

**Review by chunhtai — APPROVED** [review]
ＬＧＴＭ

**Comment by edeetee** [comment]
Thanks for the semantics fix, the attention to a11y is appreciated.
