### PR TITLE
[flutter_tools] support run -d chrome test scripts

### LINKED ISSUE #49838: Can't run `flutter run -d chrome test/foo_test.dart`
From DevTools, I run this:

```
$ flutter run -d chrome test/flutter/table_test.dart                  
Launching test/flutter/table_test.dart on Chrome in debug mode...
Configuring `build_web_compilers:entrypoint` in target `devtools_app:devtools_app` but this is not a known Builder
Building application for the web...                                15.0s
Attempting to connect to browser instance...   
```

And nothing happens.  Chrome starts and the logs show this error

```
main.dart.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

I suspect that the tool needs to adjust the index.html file opened in Chrome to run the test script.

---Doctor---
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.14.7-pre.27, on Mac OS X 10.14.6 18G2022, locale en-US)
 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] Connected device (3 available)
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes https://github.com/flutter/flutter/issues/49838

Allow debug mode web applications to run test scripts and other files not under `lib/`. Adds an integration test for this, as well as for conditional imports.

### CODE REVIEW

File: dev/integration_tests/web/test/test.dart [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+void main() {
+  String message;
+  if (message1.message == 'a' && message2.message == 'd')  {
+    message = '--- TEST SUCCEEDED ---';
+  } else {
+    message = '--- TEST FAILED ---';
+  }
+  print(message);
+  html.HttpRequest.request(
```
Comment (yjbanov) [inline dev/integration_tests/web/test/test.dart]: Since you don't have a specialized `localhost` server that understands this protocol, this is not needed. I only needed this in the other test because for release and profile mode I didn't (couldn't) use `flutter run`.

**Review by yjbanov — APPROVED** [review]

File: dev/integration_tests/web/test/test.dart (hunk 1 above)
Comment (jonahwilliams) [reply dev/integration_tests/web/test/test.dart]: Ahh, perfect!
