### PR TITLE
Fix `frameworkVersionFor` for flutter doctor and usage

### LINKED ISSUE #54160: Beta channel should report version including dev version and dev patch
In the following `flutter doctor -v` output, revision `d3ed9ec945` is reported as 1.17.0, while it is tagged as `1.17.0-dev.3.1`.

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.17.0 at /Users/fujino/git/flutter
    • Framework revision d3ed9ec945 (5 hours ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fujino/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Users/fujino/Downloads/Xcode-beta.app/Contents/Developer
    • Xcode 11.2, Build version 11B44
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

~/git/flutter$ git name-rev HEAD
HEAD tags/1.17.0-dev.3.1
```

This is a follow-up to https://github.com/flutter/flutter/pull/53715. In that PR I parsed the git tag correctly, but did not surface the information in the `frameworkRevision` getter.

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

With the new release tag format, the Flutter tool failed to detect the new tags https://github.com/flutter/flutter/issues/53688. Tag **parsing** was fixed in https://github.com/flutter/flutter/pull/53715, however, version **reporting** was not updated, so flutter doctor and usage reporting would only include `x.y.z`, and not the additional `m.n` in pre-stable releases.

This PR fixes `frameworkVersionFor()` **AND** accounts for another modification to the release tag format (`1.2.3-dev.4.5 -> 1.2.3-4.5.pre`). Parsing of the `x.y.z-dev.m.n` format is being moved to the `parseLegacyVersion()` method, and we are dropping support for `vx.y.z+hotfix.m`. This parsing logic is only for the nearest tagged parent, thus we can drop parsing support for old formats once the new format has been published on that channel.

## Related Issues

fixes https://github.com/flutter/flutter/issues/54160, https://github.com/flutter/flutter/issues/53688

## Tests

I extended the existing test to verify more permutations are correctly being parsed.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

### CODE REVIEW

File: dev/bots/test.dart [hunk 1]
```diff
@@ -1121,7 +1121,9 @@ String get gitHash {
 /// Returns null if the contents are good. Returns a string if they are bad.
 /// The string is an error message.
 Future<String> verifyVersion(File file) async {
-  final RegExp pattern = RegExp(r'^\d+\.\d+\.\d+(\+hotfix\.\d+)?(-pre\.\d+)?$');
+  // 1.18.0-5.0-pre.8
+  final RegExp pattern = RegExp(
+    r'^(\d+)\.(\d+)\.(\d+)(-\d+\.\d+)?(-pre\.\d+)?$');
```
Comment (tvolkert) [inline dev/bots/test.dart:1126]: `.pre` (dot, not hyphen).

And elsewhere.

File: packages/flutter_tools/lib/src/version.dart [hunk 2]
```diff
@@ -752,38 +757,50 @@ class GitTagVersion {
   }
 
   // TODO(fujino): Deprecate this https://github.com/flutter/flutter/issues/53850
-  /// Check for the release tag format pre-v1.17.0
+  /// Check for the release tag format of the form x.y.z-dev.m.n
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/version.dart:760]: No longer `-dev`

File: packages/flutter_tools/lib/src/version.dart [hunk 3]
```diff
@@ -752,38 +757,50 @@ class GitTagVersion {
...
     final List<String> parts = versionPattern.matchAsPrefix(version)?.groups(<int>[1, 2, 3, 4, 5, 6]);
     if (parts == null) {
       return const GitTagVersion.unknown();
     }
-    final List<int> parsedParts = parts.take(5).map<int>((String source) => source == null ? null : int.tryParse(source)).toList();
+    final List<int> parsedParts = parts.take(5).map<int>(
+      (String source) => source == null ? null : int.tryParse(source)).toList();
+    List<int> devParts = <int>[null, null];
+    if (parts[3] != null) {
+      devParts = RegExp(r'^-dev\.(\d+)\.(\d+)')
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/version.dart:772]: No longer `-dev`

File: packages/flutter_tools/lib/src/version.dart [hunk 4]
```diff
@@ -821,14 +839,15 @@ class GitTagVersion {
...
-      }
-      return '$x.$y.$z';
+      return gitTag;
     }
     if (hotfix != null) {
+      // This is an unexpected state where untagged commits exist past a hotfix
       return '$x.$y.$z+hotfix.${hotfix + 1}-pre.$commits';
     }
+    if (devPatch != null && devVersion != null) {
+      return '$x.$y.$z-${devVersion + 1}.0-pre.$commits';
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/version.dart:849]: `.pre`

File: packages/flutter_tools/lib/src/version.dart [hunk 5]
```diff
@@ -821,14 +839,15 @@ class GitTagVersion {
...
     if (commits == 0) {
-      if (hotfix != null) {
-        return '$x.$y.$z+hotfix.$hotfix';
-      }
-      return '$x.$y.$z';
+      return gitTag;
     }
     if (hotfix != null) {
+      // This is an unexpected state where untagged commits exist past a hotfix
       return '$x.$y.$z+hotfix.${hotfix + 1}-pre.$commits';
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/version.dart:846]: `.pre`

**Comment by christopherfujino** [comment]
I'm looking at the failure to `test/commands.shard/hermetic/version_test.dart`

File: packages/flutter_tools/lib/src/version.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/version.dart:760]: I had to support the `-dev` tag or else when I land this (before there are the new tags) the tool will be in a bad state (and pre-submit was failing because it couldn't parse the current version)

File: dev/bots/test.dart (hunk 1 above)
Comment (christopherfujino) [reply dev/bots/test.dart:1126]: I can make that change, but to clarify, this is just for reporting commits past last tagged version, and not the git tag format itself, and is a break from how we used to do it.

```
// old way, 4 commits past 1.2.3
1.2.4-pre.4

// this PR, 4 commits past 1.2.3-0.0.pre
1.2.3-1.0-pre.4

// proposed change, 4 commits past 1.2.3-0.0.pre
1.2.3-1.0.pre.4
```

File: packages/flutter_tools/lib/src/version.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/version.dart:760]: It was either support the `-dev` tag, or change the `git describe --match` glob, and I figured if I support the `-dev` tag here, I can safely remove it after the next dev release with the new tag format.

File: dev/bots/test.dart (hunk 1 above)
Comment (christopherfujino) [reply dev/bots/test.dart:1126]: and also, if you are 4 commits past version 1.2.3? Should that be `1.2.3-pre.4` or `1.2.3.pre.4`?

File: packages/flutter_tools/lib/src/version.dart (hunk 2 above)
Comment (zanderso) [reply packages/flutter_tools/lib/src/version.dart:760]: If possible, can you split out the -dev parsing code to more clearly delineate what logic can be removed after the next dev?

File: packages/flutter_tools/test/general.shard/version_test.dart [hunk 6]
```diff
@@ -394,29 +394,44 @@ void main() {
     const String hash = 'abcdef';
     GitTagVersion gitTagVersion;
 
-    // legacy tag release format
-    gitTagVersion = GitTagVersion.parse('v1.2.3-4-g$hash');
-    expect(gitTagVersion.frameworkVersionFor(hash), '1.2.4-pre.4');
+    // legacy tag format (x.y.z-dev.m.n), master channel
```
Comment (zanderso) [inline packages/flutter_tools/test/general.shard/version_test.dart:397]: Would a regression test of the doctor also be useful?

File: packages/flutter_tools/lib/src/version.dart (hunk 2 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/version.dart:760]: This entire method can be removed in the next dev.

File: packages/flutter_tools/test/general.shard/version_test.dart (hunk 6 above)
Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/version_test.dart:397]: The diff in this PR for `dev/bots/test.dart` was because changing the output of `frameworkVersionFor` caused the `verifyVersion` integration test to fail. I think between that integration test and this unit test, we're covering any territory a doctor test would assert. What do you think?

**Review by zanderso — APPROVED** [review]
