### PR TITLE
Considers large title height in CupertinoNavigationBar's preferred size

### LINKED ISSUE #173721: CupertinoNavigationBar.large doesn't consider large title in preferred size
### Steps to reproduce

1. Run the code sample

### Expected results

All numbers should be visibles like on this image :

Image

### Actual results

First numbers are hidden behind the CupertinoNavigationBar. It's because the rendered size is different from the preferred size which doesn't include the large title height.

Image

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      theme: CupertinoThemeData(brightness: Brightness.dark),
      home: CupertinoPageScaffold(
        navigationBar: CupertinoNavigationBar.large(
          largeTitle: Text("Title"),
          backgroundColor: CupertinoColors.black,
        ),
        child: Center(
          child: Column(children: [for (var i = 0; i < 10; i++) Text('$i')]),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.32.8, on macOS 15.6 24G84 darwin-arm64, locale fr-FR) [373ms]
    • Flutter version 3.32.8 on channel stable at
      /Users/romanojw10/Documents/developpement/flutter_arm
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision edada7c56e (3 weeks ago), 2025-07-25 14:08:03 +0000
    • Engine revision ef0cd00091
    • Dart version 3.8.1
    • DevTools version 2.45.1

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [1 198ms]
    • Android SDK at /Users/romanojw10/Library/Android/sdk
    • Platform android-36, build-tools 35.0.0
    • ANDROID_HOME = /Users/romanojw10/Library/Android/sdk
    • Java binary at: /Users/romanojw10/Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [671ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome) [35ms]
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.3) [34ms]
    • Android Studio at /Users/romanojw10/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-13047016-b750.29)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3.5) [32ms]
    • IntelliJ at /Users/romanojw10/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.101.2) [14ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.114.0

[✓] Connected device (2 available) [5,9s]
    • iPhone 16 Pro (mobile)                     • E425CEE5-C0CE-4D48-B1D8-7CE37C00A125 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-18-5 (simulator)
    • macOS (desktop)                            • macos                                •
      darwin-arm64 • macOS 15.6 24G84 darwin-arm64

[✓] Network resources [275ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by romaingyh**
Fixes #173721 

The `CupertinoNavigationBar` was not considering large title height extension.

I added 4 tests to ensure correct heights for possible variants :

- _CupertinoNavigationBar has correct height_
- _CupertinoNavigationBar with bottom widget has correct height_
- _CupertinoNavigationBar.large has correct height_
- _CupertinoNavigationBar.large with bottom widget has correct height_

| Master branch | PR |
|--------|--------|
| Simulator Screenshot - iPhone 16 Plus - 2025-07-07 at 11 18 50 | Simulator Screenshot - iPhone 16 Plus - 2025-07-07 at 11 19 00 | 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/nav_bar.dart [hunk 1]
```diff
@@ -644,7 +644,11 @@ class CupertinoNavigationBar extends StatefulWidget implements ObstructingPrefer
   @override
   Size get preferredSize {
     final double heightForDrawer = bottom?.preferredSize.height ?? 0.0;
-    return Size.fromHeight(_kNavBarPersistentHeight + heightForDrawer);
+
+    final double effectiveLargeHeight =
+        largeTitle != null ? _kNavBarLargeTitleHeightExtension : 0.0;
+
+    return Size.fromHeight(_kNavBarPersistentHeight + heightForDrawer + effectiveLargeHeight);
```
Comment (victorsanni) [inline packages/flutter/lib/src/cupertino/nav_bar.dart]: Side note: can you remove the heightForDrawer var and just use `bottom?.preferredSize.height` directly here?

**Review by victorsanni — COMMENTED** [review]
Thanks for the PR. Are the numbers still hidden if the body is wrapped in a `SafeArea`?

**Comment by romaingyh** [comment]
> Thanks for the PR. Are the numbers still hidden if the body is wrapped in a `SafeArea`?

Yes still not visible with SafeArea on content

File: packages/flutter/lib/src/cupertino/nav_bar.dart (hunk 1 above)
Comment (romaingyh) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: Something like this ?

```suggestion
    return Size.fromHeight(
      _kNavBarPersistentHeight + (bottom?.preferredSize.height ?? 0.0) + effectiveLargeHeight,
    );
```

Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: Or rename heightForDrawer to bottomHeight or something similar

Comment (romaingyh) [reply packages/flutter/lib/src/cupertino/nav_bar.dart]: Done :)

**Review by victorsanni — APPROVED** [review]
LGTM. Thanks for the other regression tests.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM as well!
