### PR TITLE
fix: Add enabled property for search anchor named constructor

### LINKED ISSUE #161063: Add enabled property to searchanchor.bar
### Use case

Currently its possible to enable/disable SearchBar and searchAnchor, but not searchAnchor.bar

### Proposal

Add this property to searchAnchor.bar()

Latest PR made for searchAnchor - https://github.com/flutter/flutter/pull/153256

### PR DESCRIPTION
**Pull request by rkishan516**
fix: Add enabled property for search anchor named constructor
Fixes: #161063 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/test/material/search_anchor_test.dart [hunk 1]
```diff
@@ -3200,6 +3200,33 @@ void main() {
     expect(controller.value.text, initValue);
   });
 
+  testWidgets('Block entering text on disabled widget with named constructors', (
```
Comment (QuncCccccc) [inline packages/flutter/test/material/search_anchor_test.dart:3203]: nit: 
```suggestion
  testWidgets('Block entering text on disabled widget with SearchAnchor.bar', (
```

**Review by QuncCccccc — APPROVED** [review]
LGTM:) Thanks for the improvement!

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by MitchellGoodwin — APPROVED** [review]
LGTM!
