### PR TITLE
Dismiss Autocomplete with ESC

### LINKED ISSUE #84416: [Web][Desktop]: The dropdown of an AutoComplete widget should be dismissed by an ESC hit or by clicking outside area.
The default behavior of this component is to shows the dropdown right after it get focus(e.g, you clicked in the inputfield). It covered the (important) thing underneath.  The problem is the dropdown cannot be dissmissed by any clicking other place or an ESC hit, it stay there until you deliberately input some wrong words or click an item which leads to unwanted result. 

You can check the result by the [demo](https://dartpad.dev/7cb153e960dbb167e19862506b3de374?null_safety=true) on dartpad which is just a copy-paste from the offical document.

BTW, dartpad itself has problem to show the demo correctly. You have to click the `run` button at least twice to show all the stuff on screen. I don't know why.

### PR DESCRIPTION
**Pull request by markusaksli-nc**
Allows the `Autocomplete` options to be hidden by pressing ESC. As for revealing the options again here's how it should work:
* When the text is edited (but not when moving the caret around or selecting text)
* When the field is re-focused
* When up or down arrows are pressed for navigating autocomplete options

This is mostly based off of [the angular implementation of material autocomplete](https://material.angular.io/components/autocomplete/overview#adding-a-custom-filter) but there are some discrepancies:

* Due to `_selection == null` in
https://github.com/flutter/flutter/blob/fd8d035921574d69a789201f5f707f94971b6edc/packages/flutter/lib/src/widgets/autocomplete.dart#L294
once a selection has been made the autocomplete options will not appear to show the only completed option.
* Options will not be shown on empty input by default (well it's up to `optionsBuilder`).

Another interesting detail is that in the angular material implementation the highlighted selection index gets reset when the options are hidden. This is different from something like the search bar in YouTube, where the highlighted option remains the same when the options are shown again by pressing the up or down arrow. The latter is how it works [in the current version of the PR](https://github.com/flutter/flutter/pull/97790/files#diff-4b6f96f28cfdafbb04b797dab70576f40d7866a6291f2981bc7832b475f22355R339-R340).

<details>
 <summary>Basic autocomplete sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const AutocompleteExampleApp());

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Autocomplete Basic'),
        ),
        body: const Center(
          child: AutocompleteBasicExample(),
        ),
      ),
    );
  }
}

class AutocompleteBasicExample extends StatelessWidget {
  const AutocompleteBasicExample({Key? key}) : super(key: key);

  static const List<String> _kOptions = <String>[
    'aardvark',
    'bobcat',
    'chameleon',
  ];

  @override
  Widget build(BuildContext context) {
    return Autocomplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) {
        if (textEditingValue.text == '') {
          return const Iterable<String>.empty();
        }
        return _kOptions.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      onSelected: (String selection) {
        debugPrint('You just selected $selection');
      },
    );
  }
}
```
</details>

Fixes https://github.com/flutter/flutter/issues/84416

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by markusaksli-nc** [comment]
cc @jonahwilliams @gspencergoog

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 1]
```diff
@@ -279,6 +279,8 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
   late final _AutocompleteCallbackAction<AutocompleteNextOptionIntent> _nextOptionAction;
   Iterable<T> _options = Iterable<T>.empty();
   T? _selection;
+  bool _hidden = false;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/autocomplete.dart:282]: Nit: I feel like this _hidden piece of state can be implemented in a way that's more clear.  My problems with it are:

  1. It's called `_hidden`, but it's not a direct indication of whether the options are currently hidden or not.  It's possible that _hidden is false but the options are not shown.
  2. It encompasses both whether the user has recently pressed escape and the current focus, which is already used elsewhere as `_focusNode.hasFocus`.  

What if we call it something like _userHidOptions and don't change it in _onChangedFocus?  Just use `_focusNode.hasFocus` when you need to know that.

Then we know what it means when it's true (the user hid the options recently and that hasn't yet been reset) and we have a better idea of what implications it has (the options may be hidden, but check _shouldShowOptions to be sure).

**Review by justinmc — COMMENTED** [review]
Thanks for taking this on, I have multiple times been using an Autocomplete and instinctively tried to dismiss the options with escape, only to be disappointed.  We should support this feature.

The biggest point that I brought up in my comments is that we might be able to use Shortcuts instead of onKeyDown.  Otherwise my comments are pretty minor and I like the approach.

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 1 above)
Comment (markusaksli-nc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: The fact that this piece of state also encompasses if the field has focus is just a byproduct of the fact that it needs to be reset when the field is un-focused and re-focused. It might be more clear if the bit in `_onChangedFocus` is changed to something like
```dart
  // Called when the field's FocusNode changes.
  void _onChangedFocus() {
    // Options should no longer be hidden when the field is re-focused.
    if(_userHidOptions && _focusNode.hasFocus) {
      _userHidOptions = false;
    }
    _updateOverlay();
  }
```
but I just figured this is more concise. If you think it would help readability I'm not against this change.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 2]
```diff
@@ -291,36 +293,57 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
-      _textEditingController.value,
+      value,
     );
     _options = options;
     _updateHighlight(_highlightedOptionIndex.value);
     if (_selection != null
         && _textEditingController.text != widget.displayStringForOption(_selection!)) {
       _selection = null;
     }
+    if(_hidden && value.text != _lastText) {
```
[the remark this answers is not in the document]
Comment (markusaksli-nc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: You understood correctly but I decided to remove the check for `_hidden` here to remove any doubts about this being checked against an outdated value.

**Comment by markusaksli-nc** [comment]
Thanks for the fast review. I think the Shortcuts solution also makes a lot more sense because the `_focusNode` can refer to `widget.focusNode` so it might be unexpectedly overriding `onKeyEvent`.

One slight snag I ran into was that shortcuts need to be disabled and enabled according to the old `_shouldShowOptions` without `!_userHidOptions`. This left me with this silly choice of copying everything from there to `_setActionsEnabled` in `_updateOverlay` or changing its definition to something like `_canShowOptions` and having `_canShowOptions && !_userHidOptions` in `_updateOverlay`.

Either way it looks a bit silly with `_shouldShowOptions` now being used in just one spot.

**Comment by markusaksli-nc** [comment]
Just noticed that this could be using the DismissIntent instead of a custom one (not sure which is preferable).

**Comment by gspencergoog** [comment]
I'd say `DismissIntent` is preferable.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 3]
```diff
@@ -523,6 +557,12 @@ class AutocompleteNextOptionIntent extends Intent {
   const AutocompleteNextOptionIntent();
 }
 
+/// An [Intent] to hide the autocomplete options list.
+class AutocompleteHideOptionsIntent extends Intent {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/autocomplete.dart:561]: +1 to @gspencergoog's suggestion to use DismissIntent instead of this new one.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 4]
```diff
@@ -277,45 +277,59 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
 
   // True iff the state indicates that the options should be visible.
   bool get _shouldShowOptions {
-    return _focusNode.hasFocus && _selection == null && _options.isNotEmpty;
+    return !_userHidOptions && _focusNode.hasFocus && _selection == null && _options.isNotEmpty;
   }
 
   // Called when _textEditingController changes.
   Future<void> _onChangedField() async {
+    final TextEditingValue value = _textEditingController.value;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/autocomplete.dart:303]: Good call saving this value locally, I guess it could change after the `await`.

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 5]
```diff
@@ -277,45 +277,59 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
...
     _options = options;
     _updateHighlight(_highlightedOptionIndex.value);
     if (_selection != null
-        && _textEditingController.text != widget.displayStringForOption(_selection!)) {
+        && value.text != widget.displayStringForOption(_selection!)) {
       _selection = null;
     }
+
+    // We need to make sure the options are no longer hidden if the content of
+    // the field gets changes (we want to ignore selection changes for this).
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/autocomplete.dart:315]: Nit: "gets changes" => "gets changed" or "changes"?  Or maybe I'm reading that wrong...

Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart:315]: Nit: The styleguide says [never use "we"](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#use-the-passive-voice-recommend-do-not-require) (though that's mainly for public docs).

File: packages/flutter/test/widgets/autocomplete_test.dart [hunk 6]
```diff
@@ -793,6 +793,96 @@ void main() {
...
+    await tester.enterText(find.byKey(fieldKey), 'elep');
+    await tester.pump();
+    expect(find.byKey(optionsKey), findsOneWidget);
+    await tester.sendKeyEvent(LogicalKeyboardKey.escape);
+    await tester.pump();
+    expect(find.byKey(optionsKey), findsNothing);
+    textEditingController.selection = TextSelection.fromPosition(const TextPosition(offset: 3));
+    await tester.pump();
+    expect(find.byKey(optionsKey), findsNothing);
+  });
```
Comment (justinmc) [inline packages/flutter/test/widgets/autocomplete_test.dart:884]: This test is super thorough and easy to follow 👍

**Review by justinmc — APPROVED** [review]
LGTM 👍 

Just nits otherwise (DismissIntent and a few other small things).

File: packages/flutter/lib/src/widgets/autocomplete.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: I see you went with my idea, it's not perfect as you pointed out but hopefully it helps improve readability a bit.  I'll try to keep an eye out in case anyone is confused by this and we can reconsider.

**Comment by markusaksli-nc** [comment]
Update: they did not play nice together at all
