### PR TITLE
Record `flutter run` success/fail, build mode, platform, start time in analytics

### LINKED ISSUE #9498: Run user timing analytic should measure time to connect
The `flutter run` user timing currently measures the duration of the entire resident session which isn't very interesting. Measure time to execution instead of entire connection duration.

### LINKED ISSUE #9499: Record flutter run success/failure

### LINKED ISSUE #9500: Record flutter run debug/profile/release

### PR DESCRIPTION
**Pull request by xster**
- Create a generic FlutterCommandResult plumbing for FlutterCommand subclasses to pipe back analytics messages
- Instead of recording the entire resident runner session, record the app speed of `flutter run` to the app start
- Record `flutter run` success/fail, build mode, hot/cold, platform, emulator.

Fixes #9500 
Fixes #9499
Fixes #9498

### CODE REVIEW

**Comment by xster** [comment]
Added a clock to the testing context

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 1]
```diff
@@ -111,18 +144,35 @@ abstract class FlutterCommand extends Command<Null> {
...
-      final int ms = stopwatch.elapsedMilliseconds;
-      printTrace("'flutter $name' took ${ms}ms.");
-      analyticsTimer?.finish();
-    });
+    final FlutterCommandResult commandResult = await verifyThenRunCommand();
+
+    final DateTime endTime = clock.now();
+    printTrace("'flutter $name' took ${endTime.difference(startTime).inMilliseconds}ms.");
+    if (usagePath != null) {
+      final String label = (
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: The following phrasing is a little bit more plain, and it allow you to get rid of `_getNullableExitCodeName()` altogether.

```
final List<String> labels = <String>[];
if (commandResult?.exitCode != null)
  labels.add(getEnumName(commandResult.exitCode));
if (commandResult?.analyticsParameters?.isNotEmpty ?? false)
  labels.addAll(commandResult.analyticsParameters);
final String label = labels.join('-');
```

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 2]
```diff
@@ -22,6 +23,38 @@ import 'flutter_command_runner.dart';
...
+  /// Optional dimension data that can be appended to the timing event.
+  /// https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#timingLabel
+  /// Do not add PII.
+  List<String> analyticsParameters;
+  /// Optional epoch time when the command's non-interactive wait time is 
+  /// complete during the command's execution. Use to measure user perceivable
+  /// latency without measuring user interaction time. 
+  /// 
+  /// Will automatically measure the command's complete time if not provided. 
+  DateTime exitTime;
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Is there a use case for commands providing their own entry time as well?

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 3]
```diff
@@ -111,18 +144,35 @@ abstract class FlutterCommand extends Command<Null> {
   /// and [runCommand] to execute the command
   /// so that this method can record and report the overall time to analytics.
   @override
-  Future<Null> run() {
-    final Stopwatch stopwatch = new Stopwatch()..start();
-    final UsageTimer analyticsTimer = usagePath == null ? null : flutterUsage.startTimer(name);
+  Future<Null> run() async {
+    final DateTime startTime = clock.now();
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: By starting this here, we'll record the time it takes to update the cache if needed (which is done in `verifyThenRunCommand()`), which will mess with the analytics results...

File: packages/flutter_tools/lib/src/usage.dart [hunk 4]
```diff
@@ -80,8 +80,19 @@ class Usage {
...
+    }) {
+    _analytics.sendTiming(
+      variableName, 
+      duration.inMilliseconds, 
+      category: category,
+      label: label,
+    );
   }
 
   UsageTimer startTimer(String event) {
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/usage.dart]: Is this used anymore?  It looks like `UsageTimer` can be nuked.

File: packages/flutter_tools/test/src/context.dart [hunk 5]
```diff
@@ -55,7 +56,8 @@ void _defaultInitializeContext(AppContext testContext) {
     })
     ..putIfAbsent(SimControl, () => new MockSimControl())
     ..putIfAbsent(Usage, () => new MockUsage())
-    ..putIfAbsent(FlutterVersion, () => new MockFlutterVersion());
+    ..putIfAbsent(FlutterVersion, () => new MockFlutterVersion())
+    ..putIfAbsent(Clock, () => new Clock());
```
Comment (tvolkert) [inline packages/flutter_tools/test/src/context.dart]: Do you mean `MockClock` (or `FakeClock` given my comment below)?

File: packages/flutter_tools/test/src/context.dart [hunk 6]
```diff
@@ -234,3 +236,5 @@ class _MockUsageTimer implements UsageTimer {
 }
 
 class MockFlutterVersion extends Mock implements FlutterVersion {}
+
+class MockClock extends Mock implements Clock {}
```
Comment (tvolkert) [inline packages/flutter_tools/test/src/context.dart]: It's such a simple interface, it may be worth writing a `FakeClock` and saving your tests the effort of mocking...  It could have a setter for setting the current time, and it'd increment the value every time `now()` was called.

**Review by tvolkert — CHANGES_REQUESTED** [review]
Travis and AppVeyor seem unhappy.

File: packages/flutter_tools/lib/src/commands/run.dart [hunk 7]
```diff
@@ -288,11 +292,30 @@ class RunCommand extends RunCommandBase {
       );
     }
 
+    DateTime appStartedTime;
+    // Sync completer so the completing agent attaching to the resident doesn't 
+    // need to know about analytics. 
+    //
+    // Do not add more operations to the future.
+    final Completer<Null> appStartedTimeRecorder = new Completer<Null>.sync()
+        ..future.then((Null _) { appStartedTime = clock.now(); });
```
Comment (xster) [inline packages/flutter_tools/lib/src/commands/run.dart]: Done

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 8]
```diff
@@ -22,6 +23,38 @@ import 'flutter_command_runner.dart';
 
 typedef void Validator();
 
+enum ExitCode {
```
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Done

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 9]
```diff
@@ -22,6 +23,38 @@ import 'flutter_command_runner.dart';
...
+  success,
+  warning,
+  fail,
+}
+
+String _getNullableExitCodeName(ExitCode code) {
+  return code == null ? null : getEnumName(code);
+}
+
+class FlutterCommandResult {
```
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Done

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 10]
```diff
@@ -22,6 +23,38 @@ import 'flutter_command_runner.dart';
...
+  FlutterCommandResult(
+    this.exitCode,
```
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Ok

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 11]
```diff
@@ -22,6 +23,38 @@ import 'flutter_command_runner.dart';
...
+    {
+      this.analyticsParameters,
+      this.exitTime,
+    }
+  ) { assert(exitCode != null); }
+
+  ExitCode exitCode;
```
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Done

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 12]
```diff
@@ -22,6 +23,38 @@ import 'flutter_command_runner.dart';
...
+  /// Optional dimension data that can be appended to the timing event.
```
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Done

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 13]
```diff
@@ -22,6 +23,38 @@ import 'flutter_command_runner.dart';
...
+  /// https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#timingLabel
+  /// Do not add PII.
+  List<String> analyticsParameters;
+  /// Optional epoch time when the command's non-interactive wait time is 
+  /// complete during the command's execution. Use to measure user perceivable
+  /// latency without measuring user interaction time. 
+  /// 
+  /// Will automatically measure the command's complete time if not provided.
```
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Done

File: packages/flutter_tools/lib/src/runner/flutter_command.dart (hunk 2 above)
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: No. I think we should measure user perceivable time. That latency measurement should start as early as possible.

File: packages/flutter_tools/lib/src/runner/flutter_command.dart (hunk 3 above)
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Ditto. I think that's fine as a metric to optimize for.

File: packages/flutter_tools/lib/src/runner/flutter_command.dart (hunk 1 above)
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Thanks for the tweak.

File: packages/flutter_tools/lib/src/usage.dart (hunk 4 above)
Comment (xster) [inline packages/flutter_tools/lib/src/usage.dart]: Done. Love deleting code

File: packages/flutter_tools/test/src/context.dart (hunk 5 above)
Comment (xster) [inline packages/flutter_tools/test/src/context.dart]: Ah ya. I was gonna switch everything without breaking the existing tests but there were too many. Done. We can swap the others as needed.

File: packages/flutter_tools/test/src/context.dart (hunk 6 above)
Comment (xster) [inline packages/flutter_tools/test/src/context.dart]: I think it's ok for the test to be verbose wrt the input/output near the assertions.

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 14]
```diff
@@ -22,6 +23,40 @@ import 'flutter_command_runner.dart';
...
+  /// Do not add PII.
+  final List<String> analyticsParameters;
+
+  /// Optional epoch time when the command's non-interactive wait time is 
+  /// complete during the command's execution. Use to measure user perceivable
+  /// latency without measuring user interaction time. 
+  /// 
+  /// [FlutterCommand] will automatically measure and report the command's
+  /// complete time if not provided.
+  final DateTime exitTime;
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: `endTime`? `endTimeOverride`?

File: packages/flutter_tools/lib/src/commands/run.dart [hunk 15]
```diff
@@ -243,10 +242,15 @@ class RunCommand extends RunCommandBase {
...
         throwToolExit(error.toString());
       }
+      final DateTime appStartedTime = clock.now();
       final int result = await app.runner.waitForAppToFinish();
       if (result != 0)
         throwToolExit(null, exitCode: result);
-      return null;
+      return new FlutterCommandResult(
+        ExitStatus.success,
+        analyticsParameters: <String>["daemon"],
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/commands/run.dart]: nit: I think flutter style would want single quotes here

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 16]
```diff
@@ -111,18 +146,37 @@ abstract class FlutterCommand extends Command<Null> {
...
 
-    return verifyThenRunCommand().whenComplete(() {
-      final int ms = stopwatch.elapsedMilliseconds;
-      printTrace("'flutter $name' took ${ms}ms.");
-      analyticsTimer?.finish();
-    });
+    final FlutterCommandResult commandResult = await verifyThenRunCommand();
+
+    final DateTime endTime = clock.now();
+    printTrace("'flutter $name' took ${endTime.difference(startTime).inMilliseconds}ms.");
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: There's a utility to print ms - `getElapsedAsMilliseconds(Duration)`. Generally used for user facing output (non-trace output), but perhap useful here.

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 17]
```diff
@@ -148,11 +202,13 @@ abstract class FlutterCommand extends Command<Null> {
     if (commandPath != null)
       flutterUsage.sendCommand(usagePath);
 
-    await runCommand();
+    return await runCommand();
```
Comment (devoncarew) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: you don't need the await here, since you're now returning the Future

Comment (tvolkert) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: I've heard that while the VM unwraps futures in these cases, it's bad style, but then I've also heard it's fiiiine.  @abarth or @Hixie, is there a definitive answer?

File: packages/flutter_tools/lib/src/commands/run.dart [hunk 18]
```diff
@@ -288,11 +292,32 @@ class RunCommand extends RunCommandBase {
...
     }
 
+    DateTime appStartedTime;
+    // Sync completer so the completing agent attaching to the resident doesn't 
+    // need to know about analytics. 
+    //
+    // Do not add more operations to the future.
+    final Completer<Null> appStartedTimeRecorder = new Completer<Null>.sync();
+    appStartedTimeRecorder.future.then(
+      (Null _) { appStartedTime = clock.now(); }
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/commands/run.dart]: Nit: for `_` parameters, you can omit the type.

File: packages/flutter_tools/lib/src/commands/run.dart [hunk 19]
```diff
@@ -288,11 +292,32 @@ class RunCommand extends RunCommandBase {
...
       shouldBuild: !runningWithPrebuiltApplication && argResults['build'],
     );
     if (result != 0)
       throwToolExit(null, exitCode: result);
+    return new FlutterCommandResult(
+      ExitStatus.success,
+      analyticsParameters: <String>[
+        hotMode ? 'hot' : 'cold',
+        getModeName(getBuildMode()),
+        getNameForTargetPlatform(device.targetPlatform),
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/commands/run.dart]: If you're synced to tip-of-tree, this now needs to be `await device.targetPlatform`

File: packages/flutter_tools/lib/src/commands/run.dart [hunk 20]
```diff
@@ -288,11 +292,32 @@ class RunCommand extends RunCommandBase {
...
+        device.isLocalEmulator ? 'emulator' : null,
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/commands/run.dart]: Likewise, `await device.isLocalEmulator`

File: packages/flutter_tools/lib/src/runner/flutter_command.dart [hunk 21]
```diff
@@ -111,18 +146,37 @@ abstract class FlutterCommand extends Command<Null> {
...
+    final FlutterCommandResult commandResult = await verifyThenRunCommand();
+
+    final DateTime endTime = clock.now();
+    printTrace("'flutter $name' took ${endTime.difference(startTime).inMilliseconds}ms.");
+    if (usagePath != null) {
+      final List<String> labels = <String>[];
+      if (commandResult?.exitStatus != null)
+        labels.add(getEnumName(commandResult.exitStatus));
+      if (commandResult?.analyticsParameters?.isNotEmpty ?? false)
+        labels.addAll(commandResult?.analyticsParameters);
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: No need for the `?` here

File: packages/flutter_tools/lib/src/usage.dart [hunk 22]
```diff
@@ -80,15 +80,19 @@ class Usage {
...
-  UsageTimer startTimer(String event) {
-    if (suppressAnalytics)
-      return new _MockUsageTimer();
-    else
-      return new UsageTimer._(event, _analytics.startTimer(event, category: 'flutter'));
+  void sendTiming(
+    String category, 
+    String variableName, 
+    Duration duration,
+    {
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/usage.dart]: Similar formatting comment here:

```
  Duration duration, {
  String label,
```

File: packages/flutter_tools/lib/src/usage.dart [hunk 23]
```diff
@@ -80,15 +80,19 @@ class Usage {
...
+      String label,
+    }) {
+    _analytics.sendTiming(
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/usage.dart]: We used to check for `suppressAnalytics`...

File: packages/flutter_tools/test/src/runner/flutter_command_test.dart [hunk 24]
```diff
@@ -38,12 +44,93 @@ void main() {
...
+      await flutterCommand.run();
+      verify(clock.now()).called(2);
+
+      expect(
+        verify(usage.sendTiming(captureAny, captureAny, captureAny, label: captureAny)).captured, 
+        <dynamic>['flutter', 'dummy', const Duration(milliseconds: 1000), null]
+      );
+    },
+    overrides: <Type, Generator>{
+      Clock: () => clock,
```
Comment (tvolkert) [inline packages/flutter_tools/test/src/runner/flutter_command_test.dart]: `MockUsage` and `MockClock` are seeded in the context for tests by default, so you don't need to instantiate and override them here. (same comment in the tests below)

**Comment by xster** [comment]
Ah, I was wondering why travis was failing. Rebased. 

Also TIL quiver. Removed Clock since there already is one and used some of the string functions

File: packages/flutter_tools/lib/src/runner/flutter_command.dart (hunk 14 above)
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: Sure. Renamed to endTimeOverride

File: packages/flutter_tools/lib/src/commands/run.dart (hunk 15 above)
Comment (xster) [inline packages/flutter_tools/lib/src/commands/run.dart]: ah thanks

File: packages/flutter_tools/lib/src/commands/run.dart (hunk 18 above)
Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/run.dart]: I'm confused as to what this is trying to do. Wouldn't `scheduleMicrotask` do the same thing cleanly? Or `Future.sync`?

File: packages/flutter_tools/lib/src/runner/flutter_command.dart (hunk 16 above)
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: oh cool, thanks

File: packages/flutter_tools/lib/src/runner/flutter_command.dart (hunk 17 above)
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: I think semantically, we don't need to await here

File: packages/flutter_tools/lib/src/commands/run.dart (hunk 18 above)
Comment (xster) [inline packages/flutter_tools/lib/src/commands/run.dart]: oh cool, thanks

File: packages/flutter_tools/lib/src/commands/run.dart (hunk 19 above)
Comment (xster) [inline packages/flutter_tools/lib/src/commands/run.dart]: thanks

File: packages/flutter_tools/lib/src/commands/run.dart (hunk 20 above)
Comment (xster) [inline packages/flutter_tools/lib/src/commands/run.dart]: done

File: packages/flutter_tools/lib/src/runner/flutter_command.dart (hunk 21 above)
Comment (xster) [inline packages/flutter_tools/lib/src/runner/flutter_command.dart]: done

File: packages/flutter_tools/lib/src/usage.dart (hunk 22 above)
Comment (xster) [inline packages/flutter_tools/lib/src/usage.dart]: done

File: packages/flutter_tools/lib/src/usage.dart (hunk 23 above)
Comment (xster) [inline packages/flutter_tools/lib/src/usage.dart]: nice catch, thanks!

File: packages/flutter_tools/test/src/runner/flutter_command_test.dart (hunk 24 above)
Comment (xster) [inline packages/flutter_tools/test/src/runner/flutter_command_test.dart]: so I ended up defaulting back to a real clock. I think it's more convenient as we move more and more stuff to Clock for tests that don't really care to keep working without null handling and not get an arbitrary value.

File: packages/flutter_tools/lib/src/commands/run.dart (hunk 18 above)
Comment (xster) [inline packages/flutter_tools/lib/src/commands/run.dart]: oops, our comments crossed paths midair. 

I didn't really understand the references to Future in the Completer's dartdoc either. It seems to be written for the perspective of the Completer's reader rather than the Completer's supplier. 

I'm trying to supply a Completer such that a piece of code runs synchronously when the owner of the Completer, a few layers deeper, calls complete() on it.

Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/run.dart]: I'm not sure what "supply a completer" means. Normally a completer is private to the person who creates it, and you hand out its future.

Comment (tvolkert) [inline packages/flutter_tools/lib/src/commands/run.dart]: @Hixie I had the same reaction, but it looks like it's an existing API in tools.  I plan to remedy this in a separate PR by having the caller pass a callback instead of a completer.

Comment (xster) [inline packages/flutter_tools/lib/src/commands/run.dart]: cool neat. It doesn't actually seem heavily used in the codebase. A simpler callback would indeed be easier to parse.

File: packages/flutter_tools/lib/src/usage.dart [hunk 25]
```diff
@@ -81,15 +81,20 @@ class Usage {
...
-    else
-      return new UsageTimer._(event, _analytics.startTimer(event, category: 'flutter'));
+  void sendTiming(
+    String category, 
+    String variableName, 
+    Duration duration, {
+    String label,
+    }) {
+    if (!suppressAnalytics) {
+    _analytics.sendTiming(
```
Comment (tvolkert) [inline packages/flutter_tools/lib/src/usage.dart]: Nit: indent

**Review by tvolkert — APPROVED** [review]
