### PR TITLE
Catch cases in tests where people try to tap on widgets that aren't reachable

### LINKED ISSUE #505: Test framework should report when taps, flings don't hit the element
I keep having the problem where I try to tap an element in a test, only to find after much debugging that the reason it's not working is that the node isn't actually getting tapped, usually because it's off-screen (though it could also just not be hit by the hit testing).

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/505

...and the tests that have had issues since then because we missed
that they were hitting the wrong thing. Oops. Luckily nothing seems to
have actually been missed because of that.

A bunch of places intentionally try to miss the target; these have to
be flagged as such. Where it was unclear to me why it was happening at
first, I added a comment.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
I didn't really add any new tests, but... it's pretty thoroughly tested by the tests...

File: packages/flutter/test/cupertino/date_picker_test.dart [hunk 1]
```diff
@@ -253,9 +253,9 @@ void main() {
       ),
     );
 
-    await tester.drag(find.text('40'), _kRowOffset);
+    await tester.drag(find.text('40'), _kRowOffset, warnIfMissed: false);
```
Comment (goderbauer) [inline packages/flutter/test/cupertino/date_picker_test.dart:255]: Why is it ok to miss here?

Comment (goderbauer) [reply packages/flutter/test/cupertino/date_picker_test.dart:255]: I guess, I have that question for most of the tests where missing is ok...

File: packages/flutter_test/lib/src/controller.dart [hunk 2]
```diff
@@ -252,9 +253,12 @@ abstract class WidgetController {
   /// the given widget, assuming it is exposed.
   ///
   /// If the center of the widget is not exposed, this might send events to
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:255]: This paragraph could be a macro since its repeated so often?

File: packages/flutter_test/lib/src/controller.dart [hunk 3]
```diff
@@ -779,41 +810,142 @@ abstract class WidgetController {
...
+  /// the specified element, and if not, a warning is printed to the
+  /// console.
+  Offset getCenter(Finder finder, { bool warnIfMissed = false, String callee = 'getCenter' }) {
+    return _getElementPoint(finder, (Size size) => size.center(Offset.zero), warnIfMissed: warnIfMissed, callee: callee);
   }
 
   /// Returns the point at the top left of the given widget.
-  Offset getTopLeft(Finder finder) {
-    return _getElementPoint(finder, (Size size) => Offset.zero);
+  Offset getTopLeft(Finder finder, { bool warnIfMissed = false, String callee = 'getTopLeft' }) {
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:836]: `warnIfMissed` should also be documented on this method and the other ones below - maybe with a macro?

File: packages/flutter_test/lib/src/controller.dart [hunk 4]
```diff
@@ -779,41 +810,142 @@ abstract class WidgetController {
...
   // GEOMETRY
 
   /// Returns the point at the center of the given widget.
-  Offset getCenter(Finder finder) {
-    return _getElementPoint(finder, (Size size) => size.center(Offset.zero));
+  ///
+  /// If `warnIfMissed` is true (the default is false), then the
+  /// returned coordinate is checked to see if it would actually hit
+  /// the specified element, and if not, a warning is printed to the
+  /// console.
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:830]: document `callee`?

File: packages/flutter_test/lib/src/controller.dart [hunk 5]
```diff
@@ -779,41 +810,142 @@ abstract class WidgetController {
...
-    return _getElementPoint(finder, (Size size) => size.bottomRight(Offset.zero));
+  Offset getBottomRight(Finder finder, { bool warnIfMissed = false, String callee = 'getBottomRight' }) {
+    return _getElementPoint(finder, (Size size) => size.bottomRight(Offset.zero), warnIfMissed: warnIfMissed, callee: callee);
   }
 
-  Offset _getElementPoint(Finder finder, Offset sizeToPoint(Size size)) {
+  /// Whether warnings relating to hit tests not hitting their mark should be
+  /// fatal (cause the test to fail).
+  ///
+  /// Some methods, e.g. [tap], have an argument `warnIfMissed` which causes a
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:861]: I find the explanation in this paragraph of what warnIfMissed much cleared than what's documented on `tap` and friends. Unfortunately, most people will not read this here, but the paragraph on `tap` and friends. Maybe use this explanation in the other locations?

File: packages/flutter_test/lib/src/controller.dart [hunk 6]
```diff
@@ -779,41 +810,142 @@ abstract class WidgetController {
...
+            ErrorHint('Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.'),
+            if (outOfBounds)
+              ErrorHint('Indeed, $location is outside the bounds of the root of the render tree, ${binding.renderView.size}.'),
+            box.toDiagnosticsNode(name: 'The finder corresponds to this RenderBox', style: DiagnosticsTreeStyle.singleLine),
+            ErrorDescription('The hit test result at that offset is: $result'),
+            ErrorDescription('If you expected this target not to be able to receive pointer events, pass "warnIfMissed: false" to "$callee()".'),
+            ErrorDescription('To make this error into a non-fatal warning, set WidgetController.hitTestWarningShouldBeFatal to false.'),
+          ]);
+        }
+        printToConsole(
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:934]: Isn't this going to be spammy for existing apps? Why not just fail if the framework was configured to fail on this condition and otherwise be silent? (Would be cool if we could opt new apps/packages into the fatal mode, though...)

File: packages/flutter_test/lib/src/controller.dart [hunk 7]
```diff
@@ -779,41 +810,142 @@ abstract class WidgetController {
...
+  }
+
   // GEOMETRY
 
   /// Returns the point at the center of the given widget.
-  Offset getCenter(Finder finder) {
-    return _getElementPoint(finder, (Size size) => size.center(Offset.zero));
+  ///
+  /// If `warnIfMissed` is true (the default is false), then the
+  /// returned coordinate is checked to see if it would actually hit
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:828]: This doc is confusing. getCenter doesn't actually hit anything?

Maybe the parameter name is even confusing? What is there to miss when you get the center of a thing?

File: packages/flutter_test/lib/src/controller.dart [hunk 8]
```diff
@@ -252,9 +253,12 @@ abstract class WidgetController {
   /// the given widget, assuming it is exposed.
   ///
   /// If the center of the widget is not exposed, this might send events to
-  /// another object.
-  Future<void> tap(Finder finder, {int? pointer, int buttons = kPrimaryButton}) {
-    return tapAt(getCenter(finder), pointer: pointer, buttons: buttons);
+  /// another object. If `warnIfMissed` is true (the default), then a warning
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/controller.dart:256]: I find the explanation given on hitTestWarningShouldBeFatal better than this one here (especially, the example given there of what a miss could mean is helpful). Unfortunately, most people will probably read this doc over hitTestWarningShouldBeFatal. Maybe move some of that stuff into these docs?

**Comment by goderbauer** [comment]
Overall, I like this feature. I am concerned whether auto-opting people into this feature is going to be too spammy. The more warnings we print, the less attention people will pay over time...

Also, I find the tests that specify `warnIfMissed: false` and then the tap clearly had an effect confusing. I know that's because a different object than the one specified in the finder got the hit, but it reads strange. I always kinda want an explanation in those situations as to where the hit went or why it was ok to miss the finder...

File: packages/flutter_test/lib/src/controller.dart (hunk 7 above)
Comment (goderbauer) [reply packages/flutter_test/lib/src/controller.dart:828]: Maybe the public getCenter, getTopLeft and friends methods shouldn't expose these new parameters? Instead tap and friends and getCenter could both call to a private _getCenterWithWarning method?

File: packages/flutter/test/cupertino/date_picker_test.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/test/cupertino/date_picker_test.dart:255]: The way the Cupertino pickers are built, the text isn't what actually gets hit at the location where the text renders. (The actual construction is non-trivial and I'm not really sure I could accurately describe what's being hit exactly. I spent some time trying to debug it but there's just too many nodes there for me to figure it out.)

Comment (Hixie) [reply packages/flutter/test/cupertino/date_picker_test.dart:255]: added a note to this file

File: packages/flutter_test/lib/src/controller.dart (hunk 2 above)
Comment (Hixie) [reply packages/flutter_test/lib/src/controller.dart:255]: done

File: packages/flutter_test/lib/src/controller.dart (hunk 3 above)
Comment (Hixie) [reply packages/flutter_test/lib/src/controller.dart:836]: done

File: packages/flutter_test/lib/src/controller.dart (hunk 4 above)
Comment (Hixie) [reply packages/flutter_test/lib/src/controller.dart:830]: done

File: packages/flutter_test/lib/src/controller.dart (hunk 5 above)
Comment (Hixie) [reply packages/flutter_test/lib/src/controller.dart:861]: i've tried to use text more similar to this text in the other locations

File: packages/flutter_test/lib/src/controller.dart (hunk 6 above)
Comment (Hixie) [reply packages/flutter_test/lib/src/controller.dart:934]: Yes, it will be spammy. I think that being silent by default makes this largely worthless. I considered making it fatal by default but that's too much, I think. The warning is actionable, so it doesn't violate our guidelines. I think it's a reasonable compromise. In practice, it does find bugs (at least if my experience with our own tests is any indication), so I think it's useful to print for existing tests.

File: packages/flutter_test/lib/src/controller.dart (hunk 7 above)
Comment (Hixie) [reply packages/flutter_test/lib/src/controller.dart:828]: Adjusted the documentation to be clearer.

I do use the new argument on some calls to getCenter, and probably should also do so on some calls to the others, but I got tired of porting tests over. :-)

**Comment by Hixie** [comment]
> The more warnings we print, the less attention people will pay over time...

That's why we have a rule that every warning must be actionable, and why this warning clearly says what to do to silence it if it's bogus.




> Also, I find the tests that specify `warnIfMissed: false` and then the tap clearly had an effect confusing. I know that's because a different object than the one specified in the finder got the hit, but it reads strange. I always kinda want an explanation in those situations as to where the hit went or why it was ok to miss the finder...

I tried to document them all (in the version you reviewed), but in some cases (like CupertinoPicker) I really couldn't figure it out and I wanted to timebox the porting effort. :-) If there are cases where it's not obvious and you'd like me to add more comments please don't hesitate to call them out, I can look in more detail to try to understand them better and document them.

**Comment by Hixie** [comment]
@goderbauer PTAL

**Review by goderbauer — APPROVED** [review]
LGTM
