### PR TITLE
Reland ensure visible fix for nested viewports

### LINKED ISSUE #65100: Scrollable.ensureVisible does not work with nested SingleChildScrollViews on both axes
## Steps to Reproduce

1. Run the sample app below. It creates a grid of cells using a `Column` of `Row`s and two `SingleChildScrollView`s--one for `Axis.horizontal` and the other for `Axis.vertical`.

image

**Expected results:** 
Tapping any cell should center that cell in the viewport via `ensureVisible`.

```dart
         Scrollable.ensureVisible(context,
            alignment: .5,
            duration: Duration(
              milliseconds: 500,
            ));
```

**Actual results:** 
Cells are not centered as expected. This works correctly when using just a single `SingleChildScrollView` but not with two.

`ensureVisible` does traverse all the `Scrollable`s in the context:

https://github.com/flutter/flutter/blob/a8281e31afa9dddfa0764f59128c3a2360c48f49/packages/flutter/lib/src/widgets/scrollable.dart#L312-L323

But something about nesting the scrollviews will yield different values here:

https://github.com/flutter/flutter/blob/a8281e31afa9dddfa0764f59128c3a2360c48f49/packages/flutter/lib/src/widgets/single_child_scroll_view.dart#L628

This behavior has been present since 2019 and is reproducible on the latest beta branch on both iOS and Android.

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Grid(),
      ),
    ),
  );
}

class Grid extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    List<Row> rows = List.generate(
      15,
      (y) => Row(
        children: List.generate(
          12,
          (x) => Cell(
            child: Text("$x,$y"),
          ),
        ),
      ),
    );

    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Column(
          children: rows,
        ),
      ),
    );
  }
}

class Cell extends StatelessWidget {
  final Widget child;

  const Cell({
    this.child,
  });

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: () {
        Scrollable.ensureVisible(context,
            alignment: .5,
            duration: Duration(
              milliseconds: 500,
            ));
      },
      child: Container(
        width: 100,
        height: 100,
        color: Colors.grey.withOpacity(.2),
        margin: EdgeInsets.all(3),
        child: Center(
          child: child,
        ),
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by dnfield**
This relands https://github.com/flutter/flutter/pull/65226, which was reverted in https://github.com/flutter/flutter/pull/66918 because it caused regressions in google3 for tests involving page views that used ensureVisible.

A test was added in https://github.com/flutter/flutter/pull/67021 which covers it.

The changes between this and the original change are in https://github.com/flutter/flutter/commit/b840a8a7ef96b708b8f6ba223e32f8edb50ea224, which does the following:

- Minor optimization to avoid calculating a rect when `targetRenderObject == renderObject`
- Override `ensureVisible` in `_PagePosition` to discard the `targetRendreObject`. As explained in the comment, this prevents further attempts to "center" the target render object, which could result in changing which page is used.

@xu-baolin 

Fixes https://github.com/flutter/flutter/issues/65100

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 1]
```diff
@@ -647,6 +647,12 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
   /// Animates the position such that the given object is as visible as possible
   /// by just scrolling this position.
   ///
+  /// The optional `targetRenderObject` parameter is used to determine which area
+  /// of that object should be as visible as possible. If `targetRenderObject` is null,
+  /// the entire [RenderObject] (as defined by its [RenderObject.paintBounds])
+  /// will be as visible as possible. If `targetRenderObject` is provided it should be
```
[the remark this answers is not in the document]
Comment (dnfield) [reply packages/flutter/lib/src/widgets/scroll_position.dart:653]: Changing to must.

File: packages/flutter/lib/src/widgets/scroll_position.dart [hunk 2]
```diff
@@ -657,25 +663,34 @@ abstract class ScrollPosition extends ViewportOffset with ScrollMetrics {
...
+    RenderObject? targetRenderObject,
   }) {
     assert(alignmentPolicy != null);
     assert(object.attached);
     final RenderAbstractViewport viewport = RenderAbstractViewport.of(object)!;
     assert(viewport != null);
 
+    Rect? targetRect;
+    if (targetRenderObject != null && targetRenderObject != object) {
+      targetRect = MatrixUtils.transformRect(
```
Comment (gspencergoog) [inline packages/flutter/lib/src/widgets/scroll_position.dart:675]: Is it possible to add an assert to make sure that `targetRenderObject` is a descendant?

Comment (dnfield) [reply packages/flutter/lib/src/widgets/scroll_position.dart:675]: `getTransformTo` asserts it.

**Comment by dnfield** [comment]
Internal failure appears to be a flake. Looking into it.

**Comment by dnfield** [comment]
Yup, flake.

**Comment by xu-baolin** [comment]
Does `_TabBarScrollPosition` need to override the `ensureVisible` function?

**Comment by dnfield** [comment]
Hmm.  Probably. It might be ok because tabview uses pageview under the hood.  Will have to check.
