### PR TITLE
Fix `Drawer` prematurely snapping

### LINKED ISSUE #153851: Drawer is snapping into place while dragging half way
### Steps to reproduce

1. Slowly drag the Drawer to open/close
2. Do not swipe or release, keep dragging until fully closed/open

### Expected results

Drawer will follow the position of my finger while dragging

### Actual results

Drawer will snap to fully closed or fully open position while my finger is still dragging half way.

### Code sample

<details open><summary>Code sample</summary>

```dart
 Scaffold(
      drawer: Drawer(),
    );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.4037], locale en-US)
    • Flutter version 3.24.0 on channel stable at C:\DEV\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\DEV\Android\SDK
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] Connected device (4 available)
    • 21051182G (mobile) • 17c8c276 • android-arm64  • Android 13 (API 33)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows [Version 10.0.22631.4037]
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 127.0.6533.120
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 127.0.2651.105

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by nate-thegrate**
This regression is due to the fact that `animationController.isAnimating` and `animationController.status.isAnimating` sometimes return opposite values.

This PR implements & tests the bugfix, and also adds documentation to explain this behavior.

<br>

fixes https://github.com/flutter/flutter/issues/153851

cc @azeunkn0wn @huycozy

### CODE REVIEW

File: packages/flutter/test/material/drawer_test.dart [hunk 1]
```diff
@@ -259,6 +259,60 @@ void main() {
     expect(state.isEndDrawerOpen, equals(false));
   });
 
+  testWidgets('Open/close drawer by dragging', (WidgetTester tester) async {
+    final ThemeData draggable = ThemeData(platform: TargetPlatform.android);
```
Comment (bleroux) [inline packages/flutter/test/material/drawer_test.dart:263]: Is setting the platform explicitly needed? (Default platform for test is already Android).

File: packages/flutter/lib/src/material/drawer.dart [hunk 2]
```diff
@@ -501,8 +501,9 @@ class DrawerControllerState extends State<DrawerController> with SingleTickerPro
     if (widget.scrimColor != oldWidget.scrimColor) {
       _scrimColorTween = _buildScrimColorTween();
     }
-    if (widget.isDrawerOpen != oldWidget.isDrawerOpen && !_controller.isAnimating) {
-      _controller.value = widget.isDrawerOpen ? 1.0 : 0.0;
+    final bool drawerOpen = widget.isDrawerOpen;
```
Comment (bleroux) [inline packages/flutter/lib/src/material/drawer.dart:504]: I usually like introducing variables to make code more understandable and readable. But in that case `widget.idDrawerOpen` is already readable and `widget.isDrawerOpen != oldWidget.isDrawerOpen` seems more understandable than `drawerOpen != oldWidget.isDrawerOpen`

File: packages/flutter/test/material/drawer_test.dart [hunk 3]
```diff
@@ -259,6 +259,60 @@ void main() {
...
+    final TestGesture gesture = await tester.createGesture();
+    final Finder finder = find.byType(Drawer);
+
+    double drawerPosition() {
+      expect(finder, findsOneWidget);
+      final RenderBox renderBox = tester.renderObject(finder);
+      return renderBox.localToGlobal(Offset.zero).dx;
+    }
+
+    // pointer down (drawer is closed)
```
Comment (bleroux) [inline packages/flutter/test/material/drawer_test.dart:280]: Very minor, consider capitalizing the first letter and adding a period at the end (same for the other comments).
```suggestion
    // Pointer down (drawer is closed).
```

File: packages/flutter/lib/src/animation/animation_controller.dart [hunk 4]
```diff
@@ -448,6 +448,10 @@ class AnimationController extends Animation<double>
   /// controller's ticker might get muted, in which case the animation
   /// controller's callbacks will no longer fire even though time is continuing
   /// to pass. See [Ticker.muted] and [TickerMode].
+  ///
+  /// If the animation was stopped (e.g. with [stop] or by setting a new [value]),
+  /// [isAnimating] will return `false` but the [status] will not change,
+  /// so the value of [AnimationStatus.isAnimating] might still be `true`.
```
Comment (bleroux) [inline packages/flutter/lib/src/animation/animation_controller.dart:454]: I probably miss something, it feels weird that one can't rely on this getter?
As it seemed to work before https://github.com/flutter/flutter/pull/148570 maybe there is a more generic way to fix it?

**Review by bleroux — COMMENTED** [review]
Thanks for the fix and the nice test.
I made some comments to help there and I will let someone with a deeper understanding on animation logic to do the final review.

File: packages/flutter/lib/src/animation/animation_controller.dart (hunk 4 above)
Comment (nate-thegrate) [reply packages/flutter/lib/src/animation/animation_controller.dart:454]: The code in drawer.dart didn't rely on this getter before #148570; both this PR and the original code used the `_controller.status`.

At the time, `AnimationStatus` didn't have any "enhanced enum" features, so it just used a switch statement:

```dart
    if (widget.isDrawerOpen != oldWidget.isDrawerOpen) {
      switch (_controller.status) {
        case AnimationStatus.completed:
        case AnimationStatus.dismissed:
          _controller.value = widget.isDrawerOpen ? 1.0 : 0.0;
        case AnimationStatus.forward:
        case AnimationStatus.reverse:
          break;
      }
    }
```

File: packages/flutter/test/material/drawer_test.dart (hunk 1 above)
Comment (nate-thegrate) [reply packages/flutter/test/material/drawer_test.dart:263]: If a desktop platform is being targeted, the drawer can't be opened with a swipe gesture.

Even if it's not explicitly necessary, IMO it's probably a good idea to keep it, in the spirit of "self-documenting code".

File: packages/flutter/lib/src/material/drawer.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/material/drawer.dart:504]: For the first one, it doesn't have to be `late` does it?

I vote for 1 or 2, but really I think any way works.

File: packages/flutter/lib/src/animation/animation_controller.dart (hunk 4 above)
Comment (justinmc) [inline packages/flutter/lib/src/animation/animation_controller.dart:454]: That's tricky. Would there be any benefit to documenting this difference on AnimationStatus.isAnimating as well?

**Review by justinmc — APPROVED** [review]
LGTM :+1:

File: packages/flutter/lib/src/material/drawer.dart (hunk 2 above)
Comment (nate-thegrate) [reply packages/flutter/lib/src/material/drawer.dart]: Just had another idea that I really like!

```dart
if (_controller.status.isAnimating) {
  return; // Don't snap the drawer open or shut while the user is dragging.
}
if (widget.isDrawerOpen != oldWidget.isDrawerOpen) {
  _controller.value = widget.isDrawerOpen ? 1.0 : 0.0;
}

```

File: packages/flutter/lib/src/animation/animation_controller.dart (hunk 4 above)
Comment (nate-thegrate) [reply packages/flutter/lib/src/animation/animation_controller.dart:454]: Ooh, hadn't thought of that!

I think the ideal place would be in the parent `Animation` class… I'll do that now.

**Comment by nate-thegrate** [comment]
Looks like back-to-back flaking… hopefully a rebase can fix it!
