### PR TITLE
Set cacheExtent for SliverFillRemaining widget

### LINKED ISSUE #142065: [iOS] [a11y] Unable to navigate to bottom sliver in CustomScrollView with VoiceOver
Internal: b/321855070

### Steps to reproduce

1. Run the sample code.
2. Enable VoiceOver.
3. Swipe right to focus successive Flutter icon buttons.
4. Continue to swipe right until you reach the end of the list (a larger Flutter icon).

### Expected results

You should be able to reach the larger Flutter icon button by swiping right.

### Actual results

You cannot reach the bottom of the list.

Note: This is iOS-only. I tested Android and web (Chrome on macOS) and you can reach the end of the list with voice assist enabled there.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const SliverFillRemainingExampleApp());

class SliverFillRemainingExampleApp extends StatelessWidget {
  const SliverFillRemainingExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('SliverFillRemaining Sample')),
        body: const SliverFillRemainingExample(),
      ),
    );
  }
}

class SliverFillRemainingExample extends StatelessWidget {
  const SliverFillRemainingExample({super.key});

  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      cacheExtent: 9999,
      slivers: [
        SliverList(
          delegate: SliverChildListDelegate([
            const SizedBox(height: 12),
            ElevatedButton(
              onPressed: () {},
              child: FlutterLogo(
                size: 100,
              ),
            ),
            const SizedBox(height: 12),
            ElevatedButton(
              onPressed: () {},
              child: FlutterLogo(
                size: 100,
              ),
            ),
            const SizedBox(height: 8),
            ElevatedButton(
              onPressed: () {},
              child: FlutterLogo(
                size: 100,
              ),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () {},
              child: FlutterLogo(
                size: 100,
              ),
            ),
            const SizedBox(height: 16),
            ElevatedButton(
              onPressed: () {},
              child: FlutterLogo(
                size: 100,
              ),
            ),
            const SizedBox(height: 16),
            ElevatedButton(
              onPressed: () {},
              child: FlutterLogo(
                size: 100,
              ),
            ),
            const SizedBox(height: 16),
            ElevatedButton(
              onPressed: () {},
              child: FlutterLogo(
                size: 100,
              ),
            ),
            const SizedBox(height: 16),
            ElevatedButton(
              onPressed: () {},
              child: FlutterLogo(
                size: 100,
              ),
            ),
            // Add more buttons to the list if the button below is initially
            // in the viewport.
          ]),
        ),
        SliverFillRemaining(
          hasScrollBody: false,
          child: ElevatedButton(
            onPressed: () {},
            child: FlutterLogo(
              size: 300,
            ),
          ),
        ),
      ],
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel google3, on macOS 14.2.1 23C71 darwin-x64, locale en)
    • Framework revision 1997bec685 (4 days ago), 2024-01-18T00:00:00.000
    • Engine revision b75d6d80d8
    • Dart version d6c08fa9bb

[✓] Android toolchain - develop for Android devices (Android SDK version Stable)
    • Android SDK at google3
    • Platform Stable, build-tools Stable
    • Java binary at: /Applications/Android Studio with
      Blaze.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d

[✓] Connected device (1 available)
    • Pixel 4 (mobile) • xx • android-arm64 • Android 13 (API 33)
```

</details>

### PR DESCRIPTION
**Pull request by vashworth**
When a Sliver with items is outside of the Viewport, but within the Viewport's `cacheExtent`, the framework should create SemanticNodes for the items even though they are out of view. However, for this to work, the Sliver's geometry must have a `cacheExtent` (how much space the sliver took up of the Viewport's `cacheExtent`) greater than 0, otherwise it is [excluded](https://github.com/flutter/flutter/blob/f01ce9f4cb41beff7b85122b5fcf1228bb655a87/packages/flutter/lib/src/rendering/viewport.dart#L311-L315).

`SliverFillRemaining` widgets that fall outside the viewport did not have this set and therefore were being excluded when SemanticNodes were created, even if they were within the Viewport's `cacheExtent`. This PR sets the `cacheExtent` for `SliverFillRemaining` widgets.

In addition, `RenderSliverFillRemainingWithScrollable` would get dropped from the semantic tree because it's child had a size of 0 when outside the remaining paint extent. To fix, we give the child a `maxExtent` of the sliver's `cacheExtent` if it's outside the remaining paint extent but within the viewport's cacheExtent.

Fixes https://github.com/flutter/flutter/issues/142065.

Definitions:
* `RenderViewport.cacheExtent`:
  ```dart
  /// The viewport has an area before and after the visible area to cache items
  /// that are about to become visible when the user scrolls.
  ///
  /// Items that fall in this cache area are laid out even though they are not
  /// (yet) visible on screen. The [cacheExtent] describes how many pixels
  /// the cache area extends before the leading edge and after the trailing edge
  /// of the viewport.
  ///
  /// The total extent, which the viewport will try to cover with children, is
  /// [cacheExtent] before the leading edge + extent of the main axis +
  /// [cacheExtent] after the trailing edge.
  ///
  /// The cache area is also used to implement implicit accessibility scrolling
  /// on iOS: When the accessibility focus moves from an item in the visible
  /// viewport to an invisible item in the cache area, the framework will bring
  /// that item into view with an (implicit) scroll action.
  ```
* `SliverGeometry.cacheExtent`:
  ```dart
  /// How many pixels the sliver has consumed in the
  /// [SliverConstraints.remainingCacheExtent].
  ```
* `SliverContraints.remainingCacheExtent`:
  ```dart
  /// Describes how much content the sliver should provide starting from the
  /// [cacheOrigin].
  ///
  /// Not all content in the [remainingCacheExtent] will be visible as some
  /// of it might fall into the cache area of the viewport.
  ///
  /// Each sliver should start laying out content at the [cacheOrigin] and
  /// try to provide as much content as the [remainingCacheExtent] allows.
  ```
  
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by vashworth** [comment]
I'm aware of the Google testing failures. They're failing because of semantics golden text comparisons, which I think is expected and just needs to updated since this PR creates more semantic nodes than previously. @ChristianEdwardPadilla perhaps you could advise on that

**Comment by Piinks** [comment]
Yeah, the google failures all look expected and normal. They can be fixed and set up to roll in with this change by creating a g3 fix in the frob tool.

File: packages/flutter/lib/src/rendering/sliver_fill.dart [hunk 1]
```diff
@@ -83,21 +83,36 @@ class RenderSliverFillRemainingWithScrollable extends RenderSliverSingleBoxAdapt
     final SliverConstraints constraints = this.constraints;
     final double extent = constraints.remainingPaintExtent - math.min(constraints.overlap, 0.0);
 
+    final double cacheExtent = calculateCacheOffset(
+      constraints,
+      from: 0.0,
+      to: constraints.viewportMainAxisExtent,
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/sliver_fill.dart:89]: Should this be `contraints.remainingCacheExtent`?

File: packages/flutter/lib/src/rendering/sliver_fill.dart [hunk 2]
```diff
@@ -83,21 +83,36 @@ class RenderSliverFillRemainingWithScrollable extends RenderSliverSingleBoxAdapt
...
+    );
     if (child != null) {
+      double maxExtent = extent;
+
+      // If sliver has no extent, but is within viewport's cacheExtent, use the
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/sliver_fill.dart:94]: This is really clever!

File: packages/flutter/lib/src/rendering/sliver_fill.dart [hunk 3]
```diff
@@ -83,21 +83,36 @@ class RenderSliverFillRemainingWithScrollable extends RenderSliverSingleBoxAdapt
...
     final double paintedChildSize = calculatePaintOffset(constraints, from: 0.0, to: extent);
     assert(paintedChildSize.isFinite);
     assert(paintedChildSize >= 0.0);
+
     geometry = SliverGeometry(
       scrollExtent: constraints.viewportMainAxisExtent,
       paintExtent: paintedChildSize,
       maxPaintExtent: paintedChildSize,
       hasVisualOverflow: extent > constraints.remainingPaintExtent || constraints.scrollOffset > 0.0,
+      cacheExtent: cacheExtent,
```
Comment (Piinks) [inline packages/flutter/lib/src/rendering/sliver_fill.dart:115]: Should `cacheExtent` be updated to reflect what extent the child ended up being after laying out?

File: packages/flutter/lib/src/rendering/sliver_fill.dart (hunk 1 above)
Comment (vashworth) [reply packages/flutter/lib/src/rendering/sliver_fill.dart:89]: So `calculateCacheOffset` will use whichever is smaller - either the `constraints.viewportMainAxisExtent` or the `contraints.remainingCacheExtent`. The reason I use `constraints.viewportMainAxisExtent` is because that's the sliver's `scrollExtent`.

So the way I thought about it is that the `RenderSliverFillRemainingWithScrollable` widget has the max potential size of the `viewportMainAxisExtent`, even when part of it isn't visible and the child is the size of the remaining space in the viewport. So it's always taking up that much of the cacheExtent (or whatever is left of it). Also, `remainingCacheExtent` could be larger than the `viewportMainAxisExtent`, so it wouldn't make sense for it to use more cacheExtent than it's max potential size.

Does that make sense?

File: packages/flutter/lib/src/rendering/sliver_fill.dart (hunk 3 above)
Comment (vashworth) [reply packages/flutter/lib/src/rendering/sliver_fill.dart:115]: See comment above: https://github.com/flutter/flutter/pull/143612/files#r1502876031

File: packages/flutter/lib/src/rendering/sliver_fill.dart (hunk 1 above)
Comment (Piinks) [reply packages/flutter/lib/src/rendering/sliver_fill.dart:89]: Right! Yes, thank you for explaining that. I forget SliverFillRemaining is trickier then other slivers because it never actually extends into the cache extent, since it only fills the remaining space and no more than that. Gotcha. 👍

**Review by Piinks — COMMENTED** [review]
Flutter_LGTM

**Comment by vashworth** [comment]
@Piinks I made a g3fix and tests are passing now, could you approve the PR?

**Comment by Piinks** [comment]
Oh yeah, sorry, this is the second PR that didn't actually process as approved. So strange.

**Review by Piinks — APPROVED** [review]

**Comment by vashworth** [comment]
Approval given, merging.
