### PR TITLE
ICU Message Syntax Parser

### LINKED ISSUE #86906: Add support for multiple/nested plurals and selects in gen_l10n tool
## Use case
Hi!

Internationalization of Flutter apps is getting more and more convenient thanks to the enhancements implemented during the last months. More recently, #86167 allowed to use plural and select in the middle of a string which is super useful.

However while internationalizing this app on top of this recent change, I noted a few cases for which it didn't produce the expected result:

```json
"pluralThenString": "Indeed, {count, plural, =1 {she likes} other {they like}} {framework} a lot!",
"@pluralThenString": {
    "placeholders": {
        "count": {},
        "framework": {
            "type": "String"
        }
    }
},
"multiplePlurals": "There {count, plural, =1{is} other{are}} {count} world{count, plural, =1{} other{s}}.",
"@multiplePlurals": {
    "placeholders": {
        "count": {}
    }
},
"pluralInSelect": "I can see {fruit, select, apple{{count, plural, =0{no apple} =1{one apple} other{some apples}}} banana{{count, plural, =0{no banana} =1{one banana} other{{count} bananas}}}}.",
"@pluralInSelect": {
    "placeholders": {
        "count": {
            "type": "int"
        },
        "fruit": {}
    }
},
```
```dart
@override
String pluralThenString(int count, String framework) {
  final String pluralString = intl.Intl.pluralLogic(
    count,
    locale: localeName,
    one: 'she likes',
    other: 'they like',
  );

  return 'Indeed, $pluralString a lot!';
}

@override
String multiplePlurals(int count) {
  final String pluralString = intl.Intl.pluralLogic(
    count,
    locale: localeName,
    one: 'is',
    other: 'are',
  );

  return 'There ${pluralString}.';
}

@override
String pluralInSelect(int count, Object fruit) {
  final String pluralString = intl.Intl.pluralLogic(
    count,
    locale: localeName,
    zero: 'no apple',
    one: 'one apple',
    other: 'some apples',
  );

  return 'I can see ${pluralString}.';
}
```

## Proposal
I would like to keep developing the l10n support to make it more powerful and reduce the risk of misuse (I personally have been surprised by the first use case).

I understand that Flutter is not intended to implement the ICU format in its entirety. I think it could improve the user experience to support these use cases though. My only references are the following, where we see that multiple plurals are being used:
* [Formatting Messages - ICU Documentation](https://unicode-org.github.io/icu/userguide/format_parse/messages/)
* [The Missing Guide to the ICU Message Format](https://phrase.com/blog/posts/guide-to-the-icu-message-format/)
* [ICU message editor](https://devpal.co/icu-message-editor/)

I had started working on this improvement, but it requires some refactoring. I will open a PR so that it can be discussed.

### LINKED ISSUE #113495: Flutter Localization - Can't use datetime placeholder in select placeholder
If using a DateTime placeholder inside a select placeholder the generation tool forgets to format the text.

## Steps to Reproduce

1. Generate translations using the following configuration:
```json
"couponExpirationDate": "{expirationDate, select, none{No expiration date} today{Expires today} tomorrow{Expires tomorrow} other{Expires on: {date}}}",
"@couponExpirationDate": {
  "placeholders": {
    "expirationDate": {
      "type": "String",
    },
    "date": {
      "type": "DateTime",
      "format": "MMMd",
    }
  }
}
```

**Expected results:**
```dart
String couponExpirationDate(String expirationDate, DateTime date) {
  final DateFormat dateFormat = DateFormat.MMMd(_localeName);
  final String dateString = dateFormat.format(date);
  return intl.Intl.select(
      expirationDate,
      {
        'none': 'No expiration date',
        'today': 'Expires today',
        'tomorrow': 'Expires tomorrow',
        'other': 'Expires on: ${dateString}'
      },
  );
}
```

**Actual generated code:** 
```dart
String couponExpirationDate(String expirationDate, DateTime date) {
  return intl.Intl.select(
      expirationDate,
      {
        'none': 'No expiration date',
        'today': 'Expires today',
        'tomorrow': 'Expires tomorrow',
        'other': 'Expires on: ${dateString}'
      },
  );
}
```

<details>
<summary>Code sample</summary>

```json
{
  "couponExpirationDate": "{expirationDate, select, none{No expiration date} today{Expires today} tomorrow{Expires tomorrow} other{Expires on: {date}}}",
  "@couponExpirationDate": {
    "description": "Text for date expiration. Select the type and then insert the date if it others",
    "placeholders": {
      "expirationDate": {
        "type": "String",
        "description": "When it expires"
      },
      "date": {
        "type": "DateTime",
        "format": "d MMM",
        "isCustomDateFormat": "true",
        "example": "14 dec",
        "description": "Expiration date"
      }
    }
  },
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
[✓] Flutter (Channel beta, 3.4.0-17.2.pre, on Pop!_OS 22.04 LTS 5.19.0-76051900-generic, locale en_GB.UTF-8)
    • Flutter version 3.4.0-17.2.pre on channel beta at /home/rares/.apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d6260f127f (4 weeks ago), 2022-09-21 13:33:49 -0500
    • Engine revision 3950c6140a
    • Dart version 2.19.0 (build 2.19.0-146.2.beta)
    • DevTools version 2.16.0

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/rares/.apps/android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/rares/.apps/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/rares/.apps/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /home/rares/.apps/apps/IDEA-C/ch-0/222.3345.118
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 22.04 LTS 5.19.0-76051900-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by thkim1011**
## Description
This PR implements the new parser for ICU message format. The current implementation involves doing a lot of hacky RegEx string replacements (i.e. replace placeholders to use a different syntax, RegEx match plurals and selects) and making assumptions about the messages (e.g. the original implementation assumes that messages may have at most one plural). This has a lot of limitations which include
1. Not able to recursively use plural and select syntax.
2. Incorrect behavior when placeholders, plurals, selects are mixed.
3. Cannot return a syntax error if the RegEx is not matched.
4. Hard to verify correctness of code.

We provide a new approach. The high level idea is to divide up the whole process into three steps:
1. Lexing the message into tokens. This is done via using RegEx to determine what the next token is. See `message_parser.dart:Parser.lexIntoTokens`.
3. Parsing the tokens into a syntax tree according to a grammar. This is done using the [LL parsing algorithm](https://en.wikipedia.org/wiki/LL_parser). See `message_parser.dart:Parser.parseIntoTree`.
5. Code generation via tree traversal through the syntax tree. This is done using code templates in `gen_l10n_templates.dart` and implemented in `gen_l10n.dart:LocalizationsGenerator._generateMethod`.

Another feature of separating the parsing and code generation process is better error messages. For example, if there is an unexpected token, then we should see the error message
```
ICU Syntax Error: Expected "identifier" but found ",".
{ , plural , = }
  ^
```

## Design Doc
[Link to design doc](https://docs.google.com/document/d/1wj5rBbuz1bXM1lvt0s0d35F5JRtIPmYUs1UDk1G3HLc/edit#).

## Testing
1. Created a new `message_parser_test.dart` file which includes tests for up to parsing.
2. Ensured that all existing code generation tests in `generate_localizations_test.dart` succeed.
3. Added a nested plural/select test case to the E2E test in `gen_l10n_test.dart`.

## Follow up work
There's a little more work left, which is a bit outside the scope of this PR. Essentially, the placeholder type inference for placeholders for plurals and selects were done by assuming that there is a unique count placeholder per message. Since we no longer make this assumption, we need to refactor the `Message` class to include all messages, parse all of these messages at the same time, then attempt to infer the correct type for each placeholder. This PR doesn't modify the old placeholder type inference logic, so it may not work properly if there are multiple plurals.

We're also setting aside escaping for a separate PR but that's lower priority than above.

## Related Issue
Fixes #86906. Fixes #113495.

## Future Work
* Message Refactor #112709.
* Add escaping syntax #113455.

### CODE REVIEW

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 1]
```diff
@@ -1152,20 +907,20 @@ class LocalizationsGenerator {
...
-              'Check to see if the plural message is in the proper ICU syntax format '
-              'and ensure that placeholders are properly specified.');
-        }
-        final Placeholder countPlaceholder = message.getCountPlaceholder();
-        if (countPlaceholder.type != null && countPlaceholder.type != 'num') {
-          logger.printWarning("Placeholders for plurals are automatically converted to type 'num' for the message: ${message.resourceId}.");
-        }
-      }
-    }
+    // for (final Message message in messages) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/localizations/gen_l10n.dart:910]: can this be deleted?

File: packages/flutter_tools/lib/src/localizations/message_parser.dart [hunk 2]
```diff
@@ -0,0 +1,519 @@
...
+  pluralExpr,
+  pluralParts,
+  pluralPart,
+
+  selectExpr,
+  selectParts,
+  selectPart,
+}
+
+final List<ST> nonterminals = <ST>[
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/localizations/message_parser.dart:35]: Doesn't looks like this is referenced, can we delete? If not, let's make it `const`.

File: packages/flutter_tools/lib/src/localizations/message_parser.dart [hunk 3]
```diff
@@ -0,0 +1,519 @@
...
+  ST.number: numeric,
+  ST.comma: comma,
+  ST.equalSign: equalSign,
+  ST.identifier: alphanumeric,
+};
+
+class Parser {
+  Parser(this.message);
+
+  String message;
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/localizations/message_parser.dart:188]: can this be `final`?

File: packages/flutter_tools/lib/src/localizations/message_parser.dart [hunk 4]
```diff
@@ -0,0 +1,519 @@
...
+          // This should only happen when there are special characters we are unable to match.
+          throw L10nException('''
+ICU Lexing Error: Unexpected character.
+$message
+${indentForError(startIndex)}''');
+        } else if (matchedType == ST.empty) {
+          // Do not add whitespace as a token.
+          startIndex = match.end;
+          continue;
+        }else {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/localizations/message_parser.dart:270]:
```suggestion
        } else {
```

File: packages/flutter_tools/lib/src/localizations/message_parser.dart [hunk 5]
```diff
@@ -0,0 +1,519 @@
...
+    final List<Node> tokens = lexIntoTokens();
+    final List<ST> parsingStack = <ST>[ST.message];
+    final Node syntaxTree = Node(ST.empty, 0, expectedSymbolCount: 1);
+    final List<Node> treeTraversalStack = <Node>[syntaxTree];
+
+    // Helper function for parsing and constructing tree.
+    void parseAndConstructNode(ST nonterminal, int ruleIndex) {
+      final Node parent = treeTraversalStack.last;
+      final List<ST> grammarRule = grammar[nonterminal]![ruleIndex];
+      final Node node = Node(nonterminal, tokens.isNotEmpty ? tokens[0].positionInMessage : -1, expectedSymbolCount: grammarRule.length);
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/localizations/message_parser.dart:290]: This is a little more readable:
```suggestion
      final int positionInMessage = tokens.isNotEmpty ? tokens.first.positionInMessage : -1;
      final Node node = Node(nonterminal, positionInMessage, expectedSymbolCount: grammarRule.length);
```

Also can you add a comment explaining what -1 means?

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart [hunk 6]
```diff
@@ -2142,7 +2175,11 @@ import 'output-localization-file_en.dart' deferred as output-localization-file_e
           throwsA(isA<L10nException>().having(
             (L10nException e) => e.message,
             'message',
-            contains('Resource attribute "@genderSelect" was not found'),
+//             contains('''
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/generate_localizations_test.dart:2178]: delete comment?

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart [hunk 7]
```diff
@@ -1965,7 +2018,11 @@ import 'output-localization-file_en.dart' deferred as output-localization-file_e
           throwsA(isA<L10nException>().having(
             (L10nException e) => e.message,
             'message',
-            contains('Resource attribute "@helloWorlds" was not found'),
+//             contains('''
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/generate_localizations_test.dart:2021]: delete comment?

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart [hunk 8]
```diff
@@ -1932,7 +1981,11 @@ import 'output-localization-file_en.dart' deferred as output-localization-file_e
           throwsA(isA<L10nException>().having(
             (L10nException e) => e.message,
             'message',
-            contains('Check to see if the plural message is in the proper ICU syntax format'),
+//             contains('''
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1984]: delete comment?

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart [hunk 9]
```diff
@@ -1895,7 +1940,11 @@ import 'output-localization-file_en.dart' deferred as output-localization-file_e
...
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1943]: delete comment?

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 10]
```diff
@@ -178,279 +187,23 @@ String generateNumberFormattingLogic(Message message) {
...
-      .replaceAll('@(name)', message.resourceId)
-      .replaceAll('@(parameters)', generateMethodParameters(message).join(', '))
-      .replaceAll('@(message)', generateMessage());
-  }
-
-  return getterTemplate
-    .replaceAll('@(name)', message.resourceId)
-    .replaceAll('@(message)', generateMessage());
-}
+Map<String, String> pluralCases = <String, String>{
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/localizations/gen_l10n.dart:190]: can you add a dartdoc to this map?

**Comment by christopherfujino** [comment]
I don't see anything wrong with this PR, but will defer to Hans for final approval.

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart (hunk 1 above)
Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/gen_l10n.dart]: yes, fixed!

File: packages/flutter_tools/lib/src/localizations/message_parser.dart (hunk 4 above)
Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/message_parser.dart]: fixed!

File: packages/flutter_tools/lib/src/localizations/message_parser.dart (hunk 5 above)
Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/message_parser.dart]: I made the change you suggested and added a comment as well.

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart (hunk 6 above)
Comment (thkim1011) [reply packages/flutter_tools/test/general.shard/generate_localizations_test.dart:2180]: Whoops, forgot to put a todo there. I'll need the change in an upcoming PR.

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart (hunk 7 above)
Comment (thkim1011) [reply packages/flutter_tools/test/general.shard/generate_localizations_test.dart:2027]: Added a todo for the comment for upcoming work.

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart (hunk 8 above)
Comment (thkim1011) [reply packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1988]: Added a todo for the comment for upcoming work.

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart (hunk 9 above)
Comment (thkim1011) [reply packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1945]: Added a todo for the comment for upcoming work.

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart (hunk 10 above)
Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/gen_l10n.dart:191]: Done!

File: packages/flutter_tools/test/general.shard/generate_localizations_test.dart (hunk 6 above)
Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/generate_localizations_test.dart:2186]: We generally do not allow commented code, and prefer using git to track work we intend to land later.

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 11]
```diff
@@ -806,6 +560,10 @@ class LocalizationsGenerator {
   /// ['es', 'en'] is passed in, the 'es' locale will take priority over 'en'.
   final List<LocaleInfo> preferredSupportedLocales;
 
+  // Whether we need to import intl or not. This is populated only after parsing
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/localizations/gen_l10n.dart:563]:
```suggestion
  // Whether we need to import intl or not. This flag is updated after parsing
```

File: packages/flutter_tools/lib/src/localizations/message_parser.dart [hunk 12]
```diff
@@ -0,0 +1,510 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/localizations/message_parser.dart:4]: It be helpful to include a comment that links to the source of the syntax definition.

File: packages/flutter_tools/lib/src/localizations/message_parser.dart [hunk 13]
```diff
@@ -0,0 +1,510 @@
...
+  Node.openBrace(this.positionInMessage): type = ST.openBrace, value = '{';
+  Node.closeBrace(this.positionInMessage): type = ST.closeBrace, value = '}';
+  Node.brace(this.positionInMessage, String this.value) {
+    if (value == '{') {
+      type = ST.openBrace;
+    } else if (value == '}') {
+      type = ST.closeBrace;
+    } else {
+      // We should never arrive here.
+      throw L10nException('Provided value is not a brace.');
```
Comment (HansMuller) [inline packages/flutter_tools/lib/src/localizations/message_parser.dart:86]: Could include the value in the message. Less confusing in case this ever comes up.

**Review by HansMuller — APPROVED** [review]
LGTM, this is a huge improvement over the original. 

There are a handful of commented-out code blocks that anticipate follow on PRs. We don't usually include TBD code like that, however if the follow on PR is coming hot on the heels of this one...

File: packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart [hunk 14]
```diff
@@ -769,3 +776,43 @@ final Set<String> _iso639Languages = <String>{
   'zh',
   'zu',
 };
+
+// Used in LocalizationsGenerator._generateMethod.generateHelperMethod.
+class HelperMethod {
+  HelperMethod(this.dependentPlaceholders, {this.helper, this.placeholder, this.string }): assert((helper != null) ^ (placeholder != null) ^ (string != null));
```
[the remark this answers is not in the document]
Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:782]: From what I understand, this is dart's exclusive or? However, I don't think "a xor b xor c" is equivalent to "exactly one of a, b, c is true", so I'll need to rethink how to write this.

[the remark this answers is not in the document]
Comment (HansMuller) [reply packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:782]: According to https://dart.dev/guides/language/language-tour#operators it's "bitwise XOR".

[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:782]: an assert can take a callback in which you can break this into separate statements.

[the remark this answers is not in the document]
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:782]: oh, I guess I was wrong; however you can do an immediately invoked function expression, like:

```dart
assert((() {
  int count = 0;
  if (helper != null)
    count += 1;
  if (placeholder != null)
    count += 1;
  if (string != null)
    count += 1;
  return count == 1;
})());
```

File: packages/flutter_tools/lib/src/localizations/message_parser.dart (hunk 12 above)
Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/message_parser.dart:4]: Fixed!

File: packages/flutter_tools/lib/src/localizations/message_parser.dart (hunk 13 above)
Comment (thkim1011) [reply packages/flutter_tools/lib/src/localizations/message_parser.dart]: Fixed!

File: packages/flutter_tools/lib/src/localizations/gen_l10n.dart [hunk 15]
```diff
@@ -1337,11 +1079,207 @@ class LocalizationsGenerator {
...
+              pluralCase = pluralPart.children[0].value!;
+              pluralMessage = pluralPart.children[2];
+            }
+            if (!pluralLogicArgs.containsKey(pluralCases[pluralCase])) {
+              final HelperMethod pluralPartHelper = generateHelperMethods(pluralMessage);
+              pluralLogicArgs[pluralCases[pluralCase]!] = '      ${pluralCases[pluralCase]}: ${pluralPartHelper.helperOrPlaceholder},';
+              dependentPlaceholders.addAll(pluralPartHelper.dependentPlaceholders);
+            } else {
+              logger.printWarning('''
+The plural part specified below is overrided by a later plural part.
```
Comment (florian-obernberger) [inline packages/flutter_tools/lib/src/localizations/gen_l10n.dart:1218]: I think "overrided" is a typo? shouldn't it be "overridden"?

**Comment by edeuss** [comment]
Any idea when this will be brought to stable or beta? We are currently running into some issues that this pull fixes for us.

**Comment by christopherfujino** [comment]
> Any idea when this will be brought to stable or beta? We are currently running into some issues that this pull fixes for us.

I believe it's already in beta: https://github.com/flutter/flutter/tree/beta/packages/flutter_tools/lib/src/localizations
