### PR TITLE
Adds a fade in and out, rounds corners, fixes offset and fixes height of cursor on iOS

### LINKED ISSUE #22879: iOS caret fidelity
Compared to native iOS 12
- [x] blink speed is a bit faster than it should
- [x] blink opacity actually should fade in and fade out
- [x] the caret height should extend as far down as the lowest descenders and higher than the highest ascenders
- [x] caret corners should be rounded
- [x] the caret position horizontally is a bit off. We're too far into the previous glyph.

### PR DESCRIPTION
**Pull request by jslavitz**
Fixes #22879.

### CODE REVIEW

File: packages/flutter/lib/src/rendering/editable.dart [hunk 1]
```diff
@@ -18,6 +18,7 @@ import 'viewport_offset.dart';
 
 const double _kCaretGap = 1.0; // pixels
 const double _kCaretHeightOffset = 2.0; // pixels
+const double _kIOSCursorRadius = 1.0; // pixels
```
Comment (xster) [inline packages/flutter/lib/src/rendering/editable.dart]: Try to keep platform specific aesthetic things out of the rendering and widget layers as much as possible. Have this passed in from TextField and CupertinoTextField. There are construction args on the editable.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 2]
```diff
@@ -179,6 +180,12 @@ class RenderEditable extends RenderBox {
       ..onTap = _handleTap;
     _longPress = LongPressGestureRecognizer(debugOwner: this)
       ..onLongPress = _handleLongPress;
+    // If the user has not specified a custom cursor, we will render a native
```
Comment (xster) [inline packages/flutter/lib/src/rendering/editable.dart]: The 'user' is the material/cupertino layers which are still us :) and those layers should specify

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -30,6 +32,7 @@ export 'package:flutter/rendering.dart' show SelectionChangedCause;
 typedef SelectionChangedCallback = void Function(TextSelection selection, SelectionChangedCause cause);
 
 const Duration _kCursorBlinkHalfPeriod = Duration(milliseconds: 500);
+const Duration _kCursorBlinkWaitForStart = Duration(milliseconds: 150);
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: I'm not sure I could figure out what this is from the name. Add comments.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -500,12 +503,19 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
   TextSelectionOverlay _selectionOverlay;
 
   final ScrollController _scrollController = ScrollController();
+  AnimationController _cursorController;
+
   final LayerLink _layerLink = LayerLink();
   bool _didAutoFocus = false;
 
+  static const Duration _fadeDuration = Duration(milliseconds: 250);
+  final bool _platformIsIOS = defaultTargetPlatform == TargetPlatform.iOS;
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: This is still in the widgets layer. Instead of self-determining this, its widget's constructor should just have a bool arg that asks should the cursor blink be animated.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 5]
```diff
@@ -514,6 +524,11 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     widget.controller.addListener(_didChangeTextEditingValue);
     widget.focusNode.addListener(_handleFocusChanged);
     _scrollController.addListener(() { _selectionOverlay?.updateForScroll(); });
+    _cursorController = AnimationController(vsync: this);
+    _cursorColorTicker = Ticker(_onCursorColorTick);
+    if (_platformIsIOS) {
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: this shouldn't be here right?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 6]
```diff
@@ -842,21 +861,43 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
 
   void _cursorTick(Timer timer) {
     _showCursor.value = !_showCursor.value;
+
+    if (_platformIsIOS) {
+      final double toValue = _showCursor.value ? 1.0 : 0.0;
+      _cursorController.animateTo(toValue, duration: _fadeDuration, curve: Curves.easeOut);
+    } else
+      _cursorController.value = _showCursor.value ? 1.0 : 0.0;
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: nit if you have brackets on if, have them on else too

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 7]
```diff
@@ -842,21 +861,43 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+  void _cursorWaitForStart(Timer timer) {
+    _cursorTimer?.cancel();
+    _cursorTimer = Timer.periodic(_kCursorBlinkHalfPeriod, _cursorTick);
+  }
+
   void _startCursorTimer() {
     _showCursor.value = true;
-    _cursorTimer = Timer.periodic(_kCursorBlinkHalfPeriod, _cursorTick);
+    if (_platformIsIOS) {
+      _cursorColorTicker.start();
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: you don't need both this an an animation controller right. You just want your _onCursorColorTick to listen to the animation controller instead.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 8]
```diff
@@ -842,21 +861,43 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
 
   void _cursorTick(Timer timer) {
     _showCursor.value = !_showCursor.value;
+
+    if (_platformIsIOS) {
+      final double toValue = _showCursor.value ? 1.0 : 0.0;
+      _cursorController.animateTo(toValue, duration: _fadeDuration, curve: Curves.easeOut);
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Describe your methodology (as to inform the next maintainer's confidence when they look at this and decide how much scrutiny they should go through first before changing it).

**Review by xster — COMMENTED** [review]
Awesome work. General feedback is move aesthetic things out of widgets and rendering layers.

**Comment by xster** [comment]
Let me know if you're ready for another look

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 9]
```diff
@@ -34,6 +34,7 @@ const BoxDecoration _kDefaultRoundedBorderDecoration = BoxDecoration(
 const Color _kSelectionHighlightColor = Color(0x667FAACF);
 const Color _kInactiveTextColor = Color(0xFFC2C2C2);
 const Color _kDisabledBackground = Color(0xFFFAFAFA);
+const int _iOSHorizontalCursorOffsetPixels = -2;
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/text_field.dart]: Add comment describing why it needs to be specified per platform, and how it's derived.

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 10]
```diff
@@ -621,6 +623,9 @@ class _CupertinoTextFieldState extends State<CupertinoTextField> with AutomaticK
           cursorWidth: widget.cursorWidth,
           cursorRadius: widget.cursorRadius,
           cursorColor: widget.cursorColor,
+          cursorOpacityAnimates: true,
+          cursorOffset: cursorOffset,
+          paintCursorOnTop: true,
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/text_field.dart]: maybe paintCursorAboveText

File: packages/flutter/lib/src/material/text_field.dart [hunk 11]
```diff
@@ -418,6 +420,14 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
     && widget.decoration != null
     && widget.decoration.counterText == null;
 
+  Radius get _cursorRadius {
+    if (widget.cursorRadius != null)
+      return widget.cursorRadius;
+    if (defaultTargetPlatform == TargetPlatform.iOS)
```
Comment (xster) [inline packages/flutter/lib/src/material/text_field.dart]: do Theme.of(context).platform instead of defaultTargetPlatform

File: packages/flutter/lib/src/material/text_field.dart [hunk 12]
```diff
@@ -600,6 +610,8 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
   @override
   bool get wantKeepAlive => _splashes != null && _splashes.isNotEmpty;
 
+  bool get cursorOpacityAnimates => defaultTargetPlatform == TargetPlatform.iOS ? true : false;
```
Comment (xster) [inline packages/flutter/lib/src/material/text_field.dart]: same here

File: packages/flutter/lib/src/material/text_field.dart [hunk 13]
```diff
@@ -663,8 +675,11 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
         inputFormatters: formatters,
         rendererIgnoresPointer: true,
         cursorWidth: widget.cursorWidth,
-        cursorRadius: widget.cursorRadius,
-        cursorColor: widget.cursorColor ?? themeData.cursorColor,
+        cursorRadius: _cursorRadius,
+        cursorColor: widget.cursorColor ?? Theme.of(context).cursorColor,
+        cursorOpacityAnimates: cursorOpacityAnimates,
```
Comment (xster) [inline packages/flutter/lib/src/material/text_field.dart]: be consistent with private or public getters

File: packages/flutter/lib/src/material/text_field.dart [hunk 14]
```diff
@@ -663,8 +675,11 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
         inputFormatters: formatters,
         rendererIgnoresPointer: true,
         cursorWidth: widget.cursorWidth,
-        cursorRadius: widget.cursorRadius,
-        cursorColor: widget.cursorColor ?? themeData.cursorColor,
+        cursorRadius: _cursorRadius,
+        cursorColor: widget.cursorColor ?? Theme.of(context).cursorColor,
```
Comment (xster) [inline packages/flutter/lib/src/material/text_field.dart]: Feel free to file a bug for later but the Material Theme default cursor color on iOS can arguably be the stock iOS color

File: packages/flutter/lib/src/rendering/editable.dart [hunk 15]
```diff
@@ -149,6 +149,9 @@ class RenderEditable extends RenderBox {
     Locale locale,
     double cursorWidth = 1.0,
     Radius cursorRadius,
+    bool paintCursorOnTop = false,
+    Offset cursorOffset,
+    double devicePixelRatio = 1.0,
```
Comment (xster) [inline packages/flutter/lib/src/rendering/editable.dart]: check null

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 16]
```diff
@@ -1233,6 +1310,7 @@ class _Editable extends LeafRenderObjectWidget {
       ..obscureText = obscureText
       ..cursorWidth = cursorWidth
       ..cursorRadius = cursorRadius
+      ..cursorOffset = cursorOffset
       ..textSelectionDelegate = textSelectionDelegate;
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: The constructor ones should all be in the update and make sure they have setters in the render object

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Is it the same amount of time it waits before animating to become opaque as well? While you're here, document the 500ms above too and how they relate.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 17]
```diff
@@ -458,6 +468,19 @@ class EditableText extends StatefulWidget {
   /// {@endtemplate}
   final Radius cursorRadius;
 
+  /// Whether the cursor will animate from fully transparent to fully opaque
+  /// during each cursor blink.
+  ///
+  /// By default, the cursor opacity will animate on iOS platforms and will not
+  /// animate on Android platforms.
+  final bool cursorOpacityAnimates;
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Random thought: could we just have the composer pass in a Curve instead of a bool? This way, Android passes a step function, iOS passes something linear (or some such. I don't really know). But then fuchsia can pass in something else and our users can pass in whatever they like too.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 18]
```diff
@@ -530,9 +553,12 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
   TextSelectionOverlay _selectionOverlay;
 
   final ScrollController _scrollController = ScrollController();
+  AnimationController _cursorController;
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: _cursorBlinkOpacityController?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 19]
```diff
@@ -530,9 +553,12 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+
   final LayerLink _layerLink = LayerLink();
   bool _didAutoFocus = false;
 
+  static const Duration _fadeDuration = Duration(milliseconds: 250);
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Describe how the number is derived

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 8 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/editable_text.dart]: If _fadeDuration is const, I think you can just pass it into the animationcontroller and not specify it here each time.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 20]
```diff
@@ -946,21 +984,51 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
-      setState(() { _obscureShowCharTicksPending--; });
+      setState(() {
+        _obscureShowCharTicksPending--;
+      });
     }
   }
 
+  void _cursorWaitForStart(Timer timer) {
+    _cursorTimer?.cancel();
+    _cursorTimer = Timer.periodic(_kCursorBlinkHalfPeriod, _cursorTick);
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: There should be some assert somewhere in the constructor or here that compares the values of _kCursorBlinkHalfPeriod and _fadeDuration to make sure someone changing this value in the future doesn't mess up.

Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Oh, I get what _kCursorBlinkHalfPeriod is now. 

I think when it's hard to describe, let's stick to industry terms with prior art. Like signal processing or something https://goo.gl/images/n99F1c. Since it's private, let's rename it.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 21]
```diff
@@ -946,21 +984,51 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
+  }
+
   void _startCursorTimer() {
     _showCursor.value = true;
-    _cursorTimer = Timer.periodic(_kCursorBlinkHalfPeriod, _cursorTick);
+    if (widget.cursorOpacityAnimates) {
+      _cursorController.value = 1.0;
+      _cursorController.addListener(_onCursorColorTick);
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Not sure if you need to keep adding/removing the listener. Since it never really changes and it's the same controller. You just need to stop and start the controller which you're already doing.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 22]
```diff
@@ -1401,6 +1459,12 @@ class RenderEditable extends RenderBox {
   void _paintContents(PaintingContext context, Offset offset) {
     assert(_textLayoutLastWidth == constraints.maxWidth);
     final Offset effectiveOffset = offset + _paintOffset;
+
+    // On iOS, the cursor is painted over the text, on android, it's painted
```
[the remark this answers is not in the document]
Comment (jslavitz) [reply packages/flutter/lib/src/rendering/editable.dart]: No, this is correct? Android cursor is painted underneath the text, iOS cursor is painted over it.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 17 above)
Comment (jslavitz) [reply packages/flutter/lib/src/widgets/editable_text.dart]: The way things are set up right now, doing this would be non trivial... But if there's a need for it in the future, we could definitely add that.

File: packages/flutter/lib/src/rendering/editable.dart (hunk 22 above)
[the remark this answers is not in the document]
Comment (xster) [reply packages/flutter/lib/src/rendering/editable.dart]: I just meant capitalize Android :D

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 17 above)
Comment (xster) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Sure. Just try to account letting it be non-API-breaking when leaving room for it.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 23]
```diff
@@ -1239,10 +1279,18 @@ class RenderEditable extends RenderBox {
     _textLayoutLastWidth = constraintWidth;
   }
 
+  Rect get _getCaretPrototype {
+    switch(defaultTargetPlatform){
+      case TargetPlatform.iOS:
+        return Rect.fromLTWH(0.0, -_kCaretHeightOffset, cursorWidth, preferredLineHeight + 3.0);
```
[the remark this answers is not in the document]
Comment (jslavitz) [reply packages/flutter/lib/src/rendering/editable.dart]: Is checking for platform here ok or should this is also be abstracted into the text_field classes?

[the remark this answers is not in the document]
Comment (xster) [reply packages/flutter/lib/src/rendering/editable.dart]: Not ideal but it'd be pretty hard to extract. Since it's private we can optimize this later I think to be pragmatic.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 21 above)
Comment (jslavitz) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Do I ever need to remove the listener?

Comment (xster) [reply packages/flutter/lib/src/widgets/editable_text.dart]: When you dispose

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 24]
```diff
@@ -35,6 +35,11 @@ const Color _kSelectionHighlightColor = Color(0x667FAACF);
 const Color _kInactiveTextColor = Color(0xFFC2C2C2);
 const Color _kDisabledBackground = Color(0xFFFAFAFA);
 
+// An eyeballed value that moves the cursor slightly left of where it is
+// rendered by default so its positioning more accurately matches the native
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/text_field.dart]: Describe where "where it is rendered by default" is. (presumably that position is a simpler/more useful position, thus answering the question of "why don't we just move the default rendering position to the current one -2 instead of doing something special for iOS")

File: packages/flutter/lib/src/cupertino/text_field.dart [hunk 25]
```diff
@@ -35,6 +35,11 @@ const Color _kSelectionHighlightColor = Color(0x667FAACF);
...
+// iOS cursor positioning.
+const int _iOSHorizontalCursorOffsetPixels = -2;
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/text_field.dart]: Since we conventionally use "pixels" to refer to logical pixels in most of the codebase, specify that it's physical pixels either in the name or in the comments.

File: packages/flutter/lib/src/material/text_field.dart [hunk 26]
```diff
@@ -606,6 +615,18 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
   @override
   bool get wantKeepAlive => _splashes != null && _splashes.isNotEmpty;
 
+  bool get _cursorOpacityAnimates => Theme.of(context).platform == TargetPlatform.iOS ? true : false;
+
+  Color get _cursorColor {
+    if (widget.cursorColor == null) {
+      if (Theme.of(context).platform == TargetPlatform.iOS)
+        return CupertinoColors.activeBlue;
```
Comment (xster) [inline packages/flutter/lib/src/material/text_field.dart]: While you're here :D
This is actually theme dependent (see the dark themed clock app or the red themed calendar app).

In other words, this is actually `CupertinoTheme.of(context).primaryColor`.

File: packages/flutter/lib/src/material/text_field.dart [hunk 27]
```diff
@@ -669,8 +690,11 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
         inputFormatters: formatters,
         rendererIgnoresPointer: true,
         cursorWidth: widget.cursorWidth,
-        cursorRadius: widget.cursorRadius,
-        cursorColor: widget.cursorColor ?? themeData.cursorColor,
+        cursorRadius: _cursorRadius,
+        cursorColor: _cursorColor,
+        cursorOpacityAnimates: _cursorOpacityAnimates,
+        cursorOffset: const Offset(0, 0),
```
Comment (xster) [inline packages/flutter/lib/src/material/text_field.dart]: Should these 2 be platform dependent too? If so, make sure there's tests for these.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 28]
```diff
@@ -713,6 +733,38 @@ class RenderEditable extends RenderBox {
...
+    if (_paintCursorOnTop == value)
+      return;
+    _paintCursorOnTop = value;
+    markNeedsLayout();
+  }
+
+  /// {@template flutter.rendering.editable.cursorOffset}
+  /// The offset that is used, in pixels, when painting the cursor on screen.
+  ///
+  /// By default, the cursor will be painted on with an offset of
```
Comment (xster) [inline packages/flutter/lib/src/rendering/editable.dart]: Saying "will" makes it sound like this render object is doing it, which it isn't as far as I can tell. If you meant "should be set to" then say that. Tweak the doc templating as needed.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 29]
```diff
@@ -31,7 +32,14 @@ export 'package:flutter/rendering.dart' show SelectionChangedCause;
 /// (including the cursor location).
 typedef SelectionChangedCallback = void Function(TextSelection selection, SelectionChangedCause cause);
 
-const Duration _kCursorBlinkHalfPeriod = Duration(milliseconds: 500);
+// The time it takes for the cursor to fade from fully opaque to fully
+// transparent and vice versa. A full cursor blink, from transparent to opaque
+// to transparent, is twice this duration.
+const Duration _kCursorFadeInAndOutTime = Duration(milliseconds: 500);
```
Comment (xster) [inline packages/flutter/lib/src/widgets/editable_text.dart]: We're using this even if we don't "fade" strictly right? I don't have anything better to suggest, let's just leave this name as is.

File: packages/flutter/test/cupertino/text_field_test.dart [hunk 30]
```diff
@@ -143,6 +144,76 @@ void main() {
...
+    final Finder textFinder = find.byType(CupertinoTextField);
+    await tester.tap(textFinder);
+    await tester.pump();
+
+    final EditableTextState editableTextState = tester.firstState(find.byType(EditableText));
+    final RenderEditable renderEditable = editableTextState.renderEditable;
+
+    expect(renderEditable.cursorColor.alpha, 255);
+
+    await tester.pump(const Duration(milliseconds: 100));
```
Comment (xster) [inline packages/flutter/test/cupertino/text_field_test.dart]: what are all these for?

File: packages/flutter/test/material/search_test.dart [hunk 31]
```diff
@@ -574,7 +574,13 @@ void main() {
       ));
 
       await tester.tap(find.byTooltip('Search'));
-      await tester.pumpAndSettle();
+      await tester.pump(const Duration(milliseconds: 100));
```
Comment (xster) [inline packages/flutter/test/material/search_test.dart]: some here

File: packages/flutter/test/cupertino/text_field_test.dart (hunk 30 above)
Comment (jslavitz) [reply packages/flutter/test/cupertino/text_field_test.dart]: Because the animation needs multiple 'frames' for the tests to work correctly. But it really only needs two. Should I condense these?

Comment (xster) [reply packages/flutter/test/cupertino/text_field_test.dart]: Yes, it should only need to pump each time you trigger an animateTo on the animation controller via some time elapse. Reduce it to what's needed for the test to pass and add comments in the various places that does more than one pump.

Comment (jslavitz) [reply packages/flutter/test/cupertino/text_field_test.dart]: ok

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 29 above)
Comment (jslavitz) [reply packages/flutter/lib/src/widgets/editable_text.dart]: yah, should I change the name back?

Comment (xster) [reply packages/flutter/lib/src/widgets/editable_text.dart]: ya, go ahead. Sorry

**Comment by xster** [comment]
LGTM. cc @HansMuller FYI

File: packages/flutter/lib/src/rendering/editable.dart [hunk 32]
```diff
@@ -1283,15 +1351,30 @@ class RenderEditable extends RenderBox {
     offset.applyContentDimensions(0.0, _maxScrollExtent);
   }
 
+  Offset _getPixelPerfectCursorOffset(Rect caretRect) {
+    final Offset caretPosition = localToGlobal(caretRect.topLeft);
+    final double pixelMultiple = 1.0 / _devicePixelRatio;
```
Comment (xster) [inline packages/flutter/lib/src/rendering/editable.dart]: these divisions are a bit hard to read. Why not just

```dart
final Offset logicalCaretPosition = localToGlobal(caretRect.topLeft);
final int physicalCaretX = (caretPosition.dx * _devicePixelRatio).round();
final int physicalCaretY = (caretPosition.dy * _devicePixelRatio).round();
final double pixelPerfectLogicalX = globalToLocal(physicalCaretX / _devicePixelRatio); // I'm not sure what the - caretPosition.dx was for
final double pixelPerfectLogicalY = globalToLocal(physicalCaretY / _devicePixelRatio);
```

Otherwise, aliasing around the edge seems like 'working as intended'. Just have your test not land on .499999999-.5.

File: packages/flutter/lib/src/material/text_field.dart [hunk 33]
```diff
@@ -682,6 +699,22 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
   @override
   bool get wantKeepAlive => _splashes != null && _splashes.isNotEmpty;
 
+  bool get _cursorOpacityAnimates => Theme.of(context).platform == TargetPlatform.iOS ? true : false;
+
+  Offset get _getCursorOffset => Offset(_iOSHorizontalCursorOffsetPixels / MediaQuery.of(context).devicePixelRatio, 0);
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/text_field.dart]: This appears to be used unconditionally. It should only be used if the platform is iOS.

File: packages/flutter/lib/src/cupertino/button.dart [hunk 34]
```diff
@@ -110,6 +110,11 @@ class CupertinoButton extends StatefulWidget {
   /// Defaults to round corners of 8 logical pixels.
   final BorderRadius borderRadius;
 
+  /// The shape of the button.
+  ///
+  /// Defaults to a super ellipse with
+//  final ShapeBorder shape;
+
```
Comment (Hixie) [inline packages/flutter/lib/src/cupertino/button.dart]: @jslavitz looks like this bit was checked in by mistake -- please take a moment to clean it. Thanks!
