### PR TITLE
Fix mouse hover to not schedule a frame for every mouse move.

### LINKED ISSUE #40600: Flutter renders a frame on every mouse move
Repro steps:
Run example from the flutter-desktop-embedding repo in debug mode.
https://github.com/google/flutter-desktop-embedding/tree/master/example

The open the devtools timeline page and verify that frames are drawn every time the mouse is moved. 
Interestingly, the https://giphy.com/apps/giphycapture screen recording tool does further odd things to the flutter desktop app resulting in frames showing up in bunches. Without screen recording, devtools updates one frame at a time and all the frames are shown as rendering quickly but with screen recording some of the frames are very slow.
desktop_demo

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This fixes the mouse hover code to not schedule frames with every mouse move.

Before this, it would schedule a post frame callback, and then schedule a frame immediately, even if there was nothing that needed to be updated. Now it will schedule checks for mouse position updates synchronously, unless there's a new annotation, and skip scheduling a new frame in all cases. It has to be async in the case of a new annotation (i.e. a new `MouseRegion` is added), since when the annotation is added, it hasn't yet painted, and it can't hit test against the new layer until after the paint, so in that case it schedules a post frame callback, but since it's already building a frame when it does that, it doesn't need to schedule a frame.

The code also used to do mouse position checks for all mice if only one mouse changed position.  I fixed this part too, so that it will only check position for the mouse that changed.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/40600

## Tests

- I updated tests for MouseRegion and MouseTracker to match new behavior, and in the process found that those tests weren't actually expecting the right output (and so fixed that).
- Also added some pump() calls to a couple of tests that were relying on the mouse tracker to schedule frames.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.
- [X] I checked all the boxes!

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/gestures/mouse_tracking.dart [hunk 1]
```diff
@@ -92,12 +92,23 @@ class MouseTracker extends ChangeNotifier {
...
-      : assert(router != null),
+  MouseTracker(this._router, this.annotationFinder)
+      : assert(_router != null),
         assert(annotationFinder != null) {
-    router.addGlobalRoute(_handleEvent);
+    _router.addGlobalRoute(_handleEvent);
   }
 
+  /// A disposal method that must be called when the MouseTracker is no longer
+  /// needed.
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/mouse_tracking.dart]: superclass docs seem adequate, no need to provide an alternative definition here

File: packages/flutter/lib/src/gestures/mouse_tracking.dart [hunk 2]
```diff
@@ -111,9 +122,12 @@ class MouseTracker extends ChangeNotifier {
   /// annotation has been added to the layer tree.
   void attachAnnotation(MouseTrackerAnnotation annotation) {
     _trackedAnnotations[annotation] = _TrackedAnnotation(annotation);
-    // Schedule a check so that we test this new annotation to see if the mouse
-    // is currently inside its region.
-    _scheduleMousePositionCheck();
+    // Schedule a check so that we test this new annotation to see if any mouse
+    // is currently inside its region. It has to happen after the frame is
+    // complete so that the annotation layer has been added before the check.
+    if (_lastMouseEvent.isNotEmpty) {
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/mouse_tracking.dart]: use `mouseIsConnected` to make it clearer why this is conditional

File: packages/flutter/lib/src/gestures/mouse_tracking.dart [hunk 3]
```diff
@@ -133,18 +147,18 @@ class MouseTracker extends ChangeNotifier {
     _trackedAnnotations.remove(annotation);
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/mouse_tracking.dart]: seems sketchy for detachAnnotation to do things synchronously

Comment (Hixie) [reply packages/flutter/lib/src/gestures/mouse_tracking.dart]: (e.g. is this going to fire the notifications during composition?)

File: packages/flutter/lib/src/gestures/mouse_tracking.dart [hunk 4]
```diff
@@ -133,18 +147,18 @@ class MouseTracker extends ChangeNotifier {
...
   }
 
-  bool _postFrameCheckScheduled = false;
-  void _scheduleMousePositionCheck() {
+  final Set<int> _postFrameCheckDeviceIds = <int>{};
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/mouse_tracking.dart]: use a HashSet unless you care about order

File: packages/flutter/lib/src/gestures/mouse_tracking.dart [hunk 5]
```diff
@@ -133,18 +147,18 @@ class MouseTracker extends ChangeNotifier {
...
+  // Schedules a position check at the end of this frame.
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/mouse_tracking.dart]: docs should say what the argument is

File: packages/flutter/lib/src/gestures/mouse_tracking.dart [hunk 6]
```diff
@@ -133,18 +147,18 @@ class MouseTracker extends ChangeNotifier {
...
+  void _scheduleMousePositionCheck(Set<int> ids) {
     // If we're not tracking anything, then there is no point in registering a
     // frame callback or scheduling a frame. By definition there are no active
     // annotations that need exiting, either.
-    if (_trackedAnnotations.isNotEmpty && !_postFrameCheckScheduled) {
-      _postFrameCheckScheduled = true;
+    if (_trackedAnnotations.isNotEmpty && ids.difference(_postFrameCheckDeviceIds).isNotEmpty) {
+      _postFrameCheckDeviceIds.addAll(ids);
       SchedulerBinding.instance.addPostFrameCallback((Duration _) {
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/mouse_tracking.dart]: (prefer explicit names rather than `_`)

File: packages/flutter/lib/src/gestures/mouse_tracking.dart [hunk 7]
```diff
@@ -206,14 +223,18 @@ class MouseTracker extends ChangeNotifier {
   /// This function is only public to allow for proper testing of the
   /// MouseTracker. Do not call in other contexts.
   @visibleForTesting
-  void collectMousePositions() {
+  void collectMousePositions(Iterable<int> deviceIds) {
```
Comment (Hixie) [inline packages/flutter/lib/src/gestures/mouse_tracking.dart]: we should name this something that more clearly describes what it does, like "sendMouseNotifications" or something.

File: packages/flutter/test/gestures/mouse_tracking_test.dart [hunk 8]
```diff
@@ -63,21 +63,25 @@ void main() {
...
-            (Offset _) sync* {
-          if (isInHitRegionOne)
-            yield annotation;
-          else if (isInHitRegionTwo)
-            yield partialAnnotation;
-        },
+      RendererBinding.instance.initMouseTracker(
+        MouseTracker(
+          GestureBinding.instance.pointerRouter,
+          (Offset _) sync* {
```
Comment (Hixie) [inline packages/flutter/test/gestures/mouse_tracking_test.dart]: prefer not `_`

File: packages/flutter/lib/src/gestures/mouse_tracking.dart (hunk 3 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/gestures/mouse_tracking.dart]: Well, it happens just before we deactivate the `Element` (in `RenderMouseRegion.preDeactivate`), and if we did it post frame then it calls `onExit` on something that has already been deactivated, and if that thing calls its `setState` (which is common), it will assert.

File: packages/flutter/lib/src/gestures/mouse_tracking.dart (hunk 4 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/gestures/mouse_tracking.dart]: Actually, now that I'm only doing this for all the device IDs, I don't think I even need the set: a bool will do.

File: packages/flutter/lib/src/gestures/mouse_tracking.dart (hunk 7 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/gestures/mouse_tracking.dart]: Yeah, what the function now does has changed to not match its name anymore. Done.  I worry a little that the class is also a `ChangeNotifier` because of the mouseIsConnected state change notification, and so someone reading this might think it'll call `notifyListeners`, but I couldn't think of a better name.  Maybe `callAnnotationCallbacks`?

File: packages/flutter/test/gestures/mouse_tracking_test.dart (hunk 8 above)
Comment (gspencergoog) [reply packages/flutter/test/gestures/mouse_tracking_test.dart]: Done.

File: packages/flutter/lib/src/gestures/mouse_tracking.dart (hunk 6 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/gestures/mouse_tracking.dart]: Done.

File: packages/flutter/lib/src/gestures/mouse_tracking.dart (hunk 5 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/gestures/mouse_tracking.dart]: Turns out I don't need the argument.

File: packages/flutter_test/lib/src/test_pointer.dart [hunk 9]
```diff
@@ -373,16 +373,16 @@ class TestGesture {
   }
 
   /// In a test, send a pointer add event for this pointer.
-  Future<void> addPointer({ Duration timeStamp = Duration.zero }) {
```
[the remark this answers is not in the document]
Comment (dkwingsmt) [reply packages/flutter_test/lib/src/test_pointer.dart]: Also I'm not a fan of the fact that the implementation of this new parameter requires all uses to explicitly declare `location: Offset.zero`, which is counter-intuitive as a default argument and breaking. I suggest that we add `position` to the constructor of `TestGesture` instead and let the internal value to be the source of truth. In the case that this does not suffice, we can always turn to `moveTo`.

File: packages/flutter/lib/src/gestures/mouse_tracking.dart [hunk 10]
```diff
@@ -133,18 +145,19 @@ class MouseTracker extends ChangeNotifier {
...
     // annotations that need exiting, either.
-    if (_trackedAnnotations.isNotEmpty && !_postFrameCheckScheduled) {
-      _postFrameCheckScheduled = true;
-      SchedulerBinding.instance.addPostFrameCallback((Duration _) {
-        _postFrameCheckScheduled = false;
-        collectMousePositions();
+    if (_trackedAnnotations.isNotEmpty && !_scheduledPostFramePositionCheck) {
+      _scheduledPostFramePositionCheck = true;
+      SchedulerBinding.instance.addPostFrameCallback((Duration duration) {
+        sendMouseNotifications(_lastMouseEvent.keys.toSet());
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/gestures/mouse_tracking.dart]: nit: we might not need `toSet` here since `keys` should have guaranteed uniqueness

File: packages/flutter/lib/src/gestures/mouse_tracking.dart [hunk 11]
```diff
@@ -133,18 +145,19 @@ class MouseTracker extends ChangeNotifier {
...
+        _scheduledPostFramePositionCheck = false;
       });
-      SchedulerBinding.instance.scheduleFrame();
```
Comment (dkwingsmt) [inline packages/flutter/lib/src/gestures/mouse_tracking.dart]: Is this removal safe? Does this properly schedule a frame when an annotation is attached?

**Review by dkwingsmt — CHANGES_REQUESTED** [review]
Besides comments, is it possible to have tests for the following cases?
- When a mouse moves in a way that incurs no state changes, no frame is scheduled.
- When a new annotation is attached, exactly one frame is scheduled.

File: packages/flutter/lib/src/gestures/mouse_tracking.dart (hunk 11 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/gestures/mouse_tracking.dart]: This is actually the point of the PR.  We have to remove this because it schedules frames every time the mouse moves.  We don't need to do this, because when adding annotations we're already rendering a frame, so it's sufficient to just schedule a post frame callback. For other cases, it is now synchronous, so no new frame is needed.

File: packages/flutter/lib/src/gestures/mouse_tracking.dart (hunk 10 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/gestures/mouse_tracking.dart]: Good point. Removed.

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 12]
```diff
@@ -2632,10 +2632,6 @@ class RenderMouseRegion extends RenderProxyBox {
     }
   }
   PointerEnterEventListener _onEnter;
-  void _handleEnter(PointerEnterEvent event) {
```
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/lib/src/rendering/proxy_box.dart]: OK, but with it, the annotations are unable to skip work if there is no callback set, for instance: it always has to convert the pointer event and call the annotation callback, even if the widget's callback is null.

Thanks for the test!  I added it.

File: packages/flutter/test/widgets/listener_deprecated_test.dart [hunk 13]
```diff
@@ -430,8 +438,8 @@ void main() {
       expect(bottomLeft.dy - topLeft.dy, scaleFactor * localHeight);
 
       final TestGesture gesture = await tester.createGesture(kind: PointerDeviceKind.mouse);
-      await gesture.addPointer();
       addTearDown(gesture.removePointer);
+      await gesture.addPointer(location: Offset.zero);
```
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/test/widgets/listener_deprecated_test.dart]: No, that was a mistake.  Thanks.

File: packages/flutter/test/widgets/listener_deprecated_test.dart [hunk 14]
```diff
@@ -430,8 +438,8 @@ void main() {
...
       await gesture.moveTo(topLeft - const Offset(1, 1));
```
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/test/widgets/listener_deprecated_test.dart]: No, because sometimes we want to add a pointer without moving.
I mostly added the addPointer calls because that more closely represents what happens in a real interaction.

File: packages/flutter_test/lib/src/test_pointer.dart (hunk 9 above)
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter_test/lib/src/test_pointer.dart]: It's not breaking: it's an optional argument. They're not required to set it, and the reason I'm setting it to `Offset.zero` is to make sure that I know where the pointer is starting off: if I leave it as using the current pointer location, then the test could succeed when it wasn't meant to.  I need to know where the pointer starts when it is added to know that it passed into or out of a widget.

File: packages/flutter_test/lib/src/test_pointer.dart [hunk 15]
```diff
@@ -373,16 +373,16 @@ class TestGesture {
...
+  Future<void> addPointer({ Duration timeStamp = Duration.zero, Offset location}) {
     return TestAsyncUtils.guard<void>(() {
-      return _dispatcher(_pointer.addPointer(timeStamp: timeStamp, location: _pointer.location), null);
+      return _dispatcher(_pointer.addPointer(timeStamp: timeStamp, location: location ?? _pointer.location), null);
     });
   }
 
   /// In a test, send a pointer remove event for this pointer.
-  Future<void> removePointer({ Duration timeStamp = Duration.zero}) {
```
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter_test/lib/src/test_pointer.dart]: Thanks, fixed.

**Comment by gspencergoog** [comment]
> Besides comments, is it possible to have tests for the following cases?
> 
> * When a mouse moves in a way that incurs no state changes, no frame is scheduled.

Sure, I'll add that.

> * When a new annotation is attached, exactly one frame is scheduled.

Actually, I think it should verify that no new frames are scheduled, and that it did attach the annotation.  We don't want any new frames scheduled unless the events we called on the widgets call setState to change something in the widget.

File: packages/flutter/test/widgets/listener_deprecated_test.dart (hunk 14 above)
[the remark this answers is not in the document]
Comment (dkwingsmt) [reply packages/flutter/test/widgets/listener_deprecated_test.dart]: I mean to merge this statement, not the entire API :)

File: packages/flutter/lib/src/gestures/mouse_tracking.dart (hunk 11 above)
Comment (dkwingsmt) [reply packages/flutter/lib/src/gestures/mouse_tracking.dart]: `_scheduleMousePositionCheck` is only called when an annotation is added now so we don't have to remove it I suppose. But it's ok too if adding annotations already means rendering a frame.

File: packages/flutter/test/widgets/listener_deprecated_test.dart (hunk 14 above)
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/test/widgets/listener_deprecated_test.dart]: Oh, duh. :-) Yes, I'll fix that.

File: packages/flutter/lib/src/rendering/proxy_box.dart (hunk 12 above)
[the remark this answers is not in the document]
Comment (dkwingsmt) [reply packages/flutter/lib/src/rendering/proxy_box.dart]: Good point. I'll keep it in mind and think about how we can solve it.

**Comment by gspencergoog** [comment]
OK, I think I've addressed all the comments. PTAL.

**Review by dkwingsmt — COMMENTED** [review]
One concerning issue as well as a few small ones

File: packages/flutter/test/material/floating_action_button_test.dart [hunk 16]
```diff
@@ -110,15 +110,16 @@ void main() {
...
     await gesture.moveTo(tester.getCenter(find.byType(FloatingActionButton)));
     await tester.pumpAndSettle();
 
     expect(find.text('Add'), findsOneWidget);
 
     await gesture.moveTo(Offset.zero);
     await gesture.removePointer();
-    gesture = null;
     await tester.pumpAndSettle();
+    gesture = null;
```
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/test/material/floating_action_button_test.dart]: Yes, unintentional.  I had a crazy screwed up rebase situation, and this is probably a result of that merge.  Reverted.

File: packages/flutter/test/material/floating_action_button_test.dart [hunk 17]
```diff
@@ -110,15 +110,16 @@ void main() {
     TestGesture gesture = await tester.createGesture(kind: PointerDeviceKind.mouse);
     await gesture.addPointer();
     addTearDown(() => gesture?.removePointer());
+    await tester.pumpAndSettle();
```
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/test/material/floating_action_button_test.dart]: Removed.  They still pass.  I think I originally added this when I was still trying to make everything work without it being synchronous.

File: packages/flutter/test/widgets/mouse_region_test.dart [hunk 18]
```diff
@@ -27,18 +26,15 @@ class HoverClient extends StatefulWidget {
 }
 
 class HoverClientState extends State<HoverClient> {
-
   void _onExit(PointerExitEvent details) {
-    if (widget.onExit != null)
-      widget.onExit();
+    if (widget.onExit != null) widget.onExit();
```
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/test/widgets/mouse_region_test.dart]: Ahh, this was a result of dartfmt "helping" me. Fixed.

File: packages/flutter/test/widgets/mouse_region_test.dart [hunk 19]
```diff
@@ -769,8 +853,7 @@ class _PaintCallbackObject extends RenderProxyBox {
 
   @override
   void paint(PaintingContext context, Offset offset) {
-    if (onPaint != null)
-      onPaint();
+    if (onPaint != null) onPaint();
```
[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/test/widgets/mouse_region_test.dart]: Done.

**Review by dkwingsmt — APPROVED** [review]
LGTM
