### PR TITLE
Only show devtools deep links for render overflow errors

### LINKED ISSUE #74911: Only show DevTools deep links in error messages for overflow errors
Showing for all widget-related errors will lead to pointing users to DevTools even when the tree is "broken". The inspector does not handle this case very well, so we want to limit deep links to only overflow errors.

cc @jacob314

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Fixes https://github.com/flutter/flutter/issues/74911

### CODE REVIEW

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 1]
```diff
@@ -2912,20 +2918,41 @@ Iterable<DiagnosticsNode> _describeRelevantUserCode(Element element) {
       ErrorSpacer(),
     ];
   }
+
+  bool isOverflowError() {
+    for (final DiagnosticsNode node in properties) {
+      if (node is ErrorSummary) {
+        if (node.value.isNotEmpty
+            && node.value.first is String
+            && (node.value.first as String).contains('A RenderFlex overflowed by')) {
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2927]: nit: contains --> startsWith

avoid `as` by creating a final variable
final Object first = node.value.first;
if (first is String && fist.contains(...))
will then type check.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 2]
```diff
@@ -2912,20 +2918,41 @@ Iterable<DiagnosticsNode> _describeRelevantUserCode(Element element) {
...
-          WidgetInspectorService.instance._devToolsInspectorUriForElement(target);
-      if (devToolsInspectorUri != null) {
-        devToolsDiagnostic = DevToolsDeepLinkProperty(
-          'To inspect this widget in Flutter DevTools, visit: $devToolsInspectorUri',
-          devToolsInspectorUri,
-        );
+
+      // TODO(kenz): once the inspector is better at dealing with broken trees,
+      // we can enable deep links for more errors than just RenderFlex overflow
+      // errors.
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2946]: file a bug for this. Filtering to only show one error is probably ok for now to incrementally roll out this feature but it would be a problem if this code stays in place long term.

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 3]
```diff
@@ -2893,15 +2893,21 @@ Iterable<DiagnosticsNode> transformDebugCreator(Iterable<DiagnosticsNode> proper
 /// Transform the input [DiagnosticsNode].
 ///
 /// Return null if input [DiagnosticsNode] is not applicable.
-Iterable<DiagnosticsNode>? _parseDiagnosticsNode(DiagnosticsNode node) {
+Iterable<DiagnosticsNode>? _parseDiagnosticsNode(
+  DiagnosticsNode node,
+  Iterable<DiagnosticsNode> properties,
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2898]: rather than passing in all the properties which is confusing how about we just pass in the ErrorSummary for the error.
it would be cheap enough to extract that in the previous method that I'm not worried about extracting it for all errors.

**Review by jacob314 — COMMENTED** [review]
done with a round of comments

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 3 above)
Comment (kenzieschmoll) [reply packages/flutter/lib/src/widgets/widget_inspector.dart]: done

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 1 above)
Comment (kenzieschmoll) [reply packages/flutter/lib/src/widgets/widget_inspector.dart]: done

File: packages/flutter/lib/src/widgets/widget_inspector.dart (hunk 2 above)
Comment (kenzieschmoll) [reply packages/flutter/lib/src/widgets/widget_inspector.dart]: done

File: packages/flutter/lib/src/widgets/widget_inspector.dart [hunk 4]
```diff
@@ -2878,7 +2878,14 @@ Iterable<DiagnosticsNode> transformDebugCreator(Iterable<DiagnosticsNode> proper
     if (!foundStackTrace && node is DiagnosticsStackTrace)
       foundStackTrace = true;
     if (_isDebugCreator(node)) {
-      yield* _parseDiagnosticsNode(node)!;
+      ErrorSummary? errorSummary;
```
Comment (jacob314) [inline packages/flutter/lib/src/widgets/widget_inspector.dart:2881]: move this as a separate for loop above the outer loop over the properties.

**Review by jacob314 — APPROVED** [review]
lgtm
with a nit.

**Comment by pcsosinski** [comment]
removing cp label in favor of the issue
