### PR TITLE
Fix bottom sheet assertion on switching with multiple controllers

### LINKED ISSUE #93717: Getting `Assertion Error` while switching in between `Bottom Sheets`
## Steps to Reproduce

1. Run code sample & quickly switch Bottom Sheet by clicking to the buttons

**Expected results:** 
no error

**Actual results:** 
```dart
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/material/scaffold.dart': Failed assertion: line 2715 pos 14: '_currentBottomSheet!._widget == bottomSheet': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScaffoldState._buildBottomSheet._removeCurrentBottomSheet (package:flutter/src/material/scaffold.dart:2715:14)
#3      ScaffoldState._buildBottomSheet.<anonymous closure> (package:flutter/src/material/scaffold.dart:2734:13)
#4      LocalHistoryEntry._notifyRemoved (package:flutter/src/widgets/routes.dart:454:15)
#5      LocalHistoryRoute.removeLocalHistoryEntry (package:flutter/src/widgets/routes.dart:619:11)
#6      LocalHistoryEntry.remove (package:flutter/src/widgets/routes.dart:449:13)
#7      _SheetButtonState._closeSheet (package:sheet_bug/main.dart:85:29)
#8      _SheetButtonState._showInfoSheet (package:sheet_bug/main.dart:48:5)
#9      _SheetButtonState.build.<anonymous closure> (package:sheet_bug/main.dart:42:24)
#10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#14     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:558:9)
#16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#23     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#24     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#25     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#31     _invoke1 (dart:ui/hooks.dart:185:10)
#32     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#33     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#dc201
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(58.3, 43.0)
  finalLocalPosition: Offset(58.3, 13.0)
  button: 1
  sent tap down
```

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  PersistentBottomSheetController? sheetController1;
  PersistentBottomSheetController? sheetController2;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Builder(builder: (context) {
          return SafeArea(
            child: Column(
              children: [
                ElevatedButton(
                  child: const Text('show 1'),
                  onPressed: () {
                    if (sheetController1 != null) {
                      sheetController1!.close();
                      sheetController1 = null;
                    }
                    sheetController1 =
                        Scaffold.of(context).showBottomSheet<void>(
                      (BuildContext context) => const Text('BottomSheet 1'),
                    );
                  },
                ),
                ElevatedButton(
                  child: const Text('show 2'),
                  onPressed: () {
                    if (sheetController2 != null) {
                      sheetController2!.close();
                      sheetController2 = null;
                    }
                    sheetController2 =
                        Scaffold.of(context).showBottomSheet<void>(
                      (BuildContext context) => const Text('BottomSheet 2'),
                    );
                  },
                ),
              ],
            ),
          );
        }),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale cs-CZ)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] Connected device (4 available)

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by markusaksli-nc**
Makes sure the bottom sheet matches the current bottom sheet when adding the `onRemove` `LocalHistoryEntry` in `_buildBottomSheet` so it isn't incorrectly called multiple times with multiple controllers.

Fixes https://github.com/flutter/flutter/issues/93717

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/93922

**Comment by markusaksli-nc** [comment]
Idk why the bot is saying this stuff when I didn't touch InputDecorator?

Same as https://github.com/flutter/flutter/pull/92086#issuecomment-974095217

**Review by chunhtai — COMMENTED** [review]
I replied to the original issue. we should figure it out before we proceed with the fix

**Comment by markusaksli-nc** [comment]
It should probably only occur due to user error but does that mean this safeguard isn't relevant? Or should it just fail and have a better assertion message?

**Comment by chunhtai** [comment]
Hi @markusaksli-nc  sorry, I think I was wrong, this is indeed an issue

File: packages/flutter/test/material/bottom_sheet_test.dart [hunk 1]
```diff
@@ -1060,6 +1060,62 @@ void main() {
...
+    await tester.pumpWidget(MaterialApp(
+      home: Scaffold(
+        body: Builder(builder: (BuildContext context) {
+          return Center(
+            child: Column(
+              children: <Widget>[
+                ElevatedButton(
+                  child: const Text('show 1'),
+                  onPressed: () {
+                    if (sheetController1 != null) {
```
Comment (chunhtai) [inline packages/flutter/test/material/bottom_sheet_test.dart:1076]: The set up is overly complex, something like this may be simpler
```dart
 Scaffold(
        body: Builder(builder: (context) {
          return SafeArea(
            child: Column(
              children: [
                ElevatedButton(
                  child: const Text('show 1'),
                  onPressed: () {

                    sheetController1 =
                        Scaffold.of(context).showBottomSheet<void>(
                              (BuildContext context) => const Text('BottomSheet 1'),
                        );
                  },
                ),
                ElevatedButton(
                  child: const Text('show 2'),
                  onPressed: ()  {
                    sheetController2 =
                        Scaffold.of(context).showBottomSheet<void>(
                              (BuildContext context) => const Text('BottomSheet 2'),
                        );
                  },
                ),
                ElevatedButton(
                  child: const Text('close 1'),
                  onPressed: ()  {
                    sheetController1!.close();
                  },
                ),
              ],
            ),
          );
        }),
      )
      ```
      press show1 -> show 2 -> close 1 will cause the same crash

File: packages/flutter/test/material/bottom_sheet_test.dart [hunk 2]
```diff
@@ -1060,6 +1060,62 @@ void main() {
     expect(tester.takeException(), isNull);
   });
 
+  testWidgets('Bottom sheet onRemove LocalHistoryEntry only added for current bottom sheet', (WidgetTester tester) async {
```
Comment (chunhtai) [inline packages/flutter/test/material/bottom_sheet_test.dart:1063]: the name is a bit miss leading maybe
```
Calling PersistentBottomSheetController.close does not crash when it is not the current bottom sheet
```

**Review by chunhtai — COMMENTED** [review]
I think there are some more issue with the persistent bottom sheet but this is a good improvement over previous behavior. I left some comment on the test

**Comment by markusaksli-nc** [comment]
Committed feedback and rebased. I think the changes made the test much more readable.

File: packages/flutter/test/material/bottom_sheet_test.dart [hunk 3]
```diff
@@ -1204,6 +1204,58 @@ void main() {
...
+    expect(find.text('BottomSheet 1'), findsOneWidget);
+
+    await tester.tap(find.text('show 2'));
+    await tester.pumpAndSettle();
+    expect(find.text('BottomSheet 2'), findsOneWidget);
+
+    // This will throw an assertion if regressed
+    await tester.tap(find.text('close 1'));
+    await tester.pumpAndSettle();
+    expect(find.text('BottomSheet 1'), findsOneWidget);
```
Comment (chunhtai) [inline packages/flutter/test/material/bottom_sheet_test.dart:1256]: should check for bottomsheet 2?

**Review by chunhtai — COMMENTED** [review]
builds are failing, they need to pass before this pr can merge

**Review by chunhtai — APPROVED** [review]
LGTM
