### PR TITLE
[web] Fix errors when using image filters with default values.

### LINKED ISSUE #174583: Zero-sigma blur causes crash in Skwasm
### Steps to reproduce

Create and use an `ImageFilter.blur(sigmaX: 0, sigmaY: 0)`.

### Expected results

It should work without crashing.

### Actual results

Skwasm crashes.

### Code sample

See the code in `engine/src/flutter/lib/web_ui/test/ui/filters_test.dart` under the test `'does not throw for both sigmaX and sigmaY set to 0'`.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by ksokolovskyi**
Fixes https://github.com/flutter/flutter/issues/174583

- Fix WASM crash when image filter is null
- Adds support for dilate and erode image filters with default values to CanvasKit
- Adds new tests to verify that image filters with default values can be used without any issues/crashes

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/skwasm/filters.cpp [hunk 1]
```diff
@@ -68,8 +67,12 @@ SKWASM_EXPORT void imageFilter_dispose(sp_wrapper<DlImageFilter>* filter) {
 SKWASM_EXPORT void imageFilter_getFilterBounds(
     sp_wrapper<DlImageFilter>* filter,
     DlIRect* inOutBounds) {
+  auto dlFilter = filter->shared();
+  if (dlFilter == nullptr) {
```
Comment (harryterkelsen) [inline engine/src/flutter/lib/web_ui/skwasm/filters.cpp:71]: nit: add a comment saying that returning early here means the out bounds are equal to the in bounds

**Review by harryterkelsen — APPROVED** [review]
LGTM with nit

**Comment by ksokolovskyi** [comment]
@harryterkelsen, thanks a lot for your review!
I've added a requested comment in the latest commit. Could you please take another look at this PR and confirm the new goldens?

**Review by mdebbar — APPROVED** [review]
PR and goldens look good to me! Thanks for the fix!

**Comment by ksokolovskyi** [comment]
@mdebbar, thanks a lot for the review!
