### PR TITLE
Observe logging from VM service on iOS 13

### LINKED ISSUE #41133: No exceptions or logs shown in flutter run on physical iOS 13 phone
Everything is at latest update. Device is an iPhone X on iOS 13.

The only thing that ever appears is the following:

```
Launching lib/main.dart on Virgo in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: [...]
Xcode build done.                                           31.6s
Checking for advertised Dart observatories...
Checking for available port on [...]
Checking for authentication code for [...]
```

Tried `flutter clean` + `rm -rf Podfile.lock Pods/`, rebooting, etc.

Can't move to non-master Flutter channels to test due to active iOS 13/Xcode 11 build bugs.

```
[✓] Flutter (Channel master, v1.10.6-pre.33, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.10.6-pre.33 at /Users/james/Development/flutter
    • Framework revision 961f1b746d (2 hours ago), 2019-09-23 10:09:38 -0700
    • Engine revision b875c7a5ff
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 7c1821c4aa)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/james/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Virgo • b01937a10ffe8461ea409b3bd137ac0bf8ecc921 • ios • iOS 13.0

• No issues found!
```

### PR DESCRIPTION
**Pull request by jmagman**
## Description

IOSDeviceLogReader observes Stdout stream from VMService if version is iOS 13+ to print dart and engine logs.  Keep using syslog on older versions since that will additionally provide logs if the app crashes.

Similar to resident_web_runner behavior:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_runner/resident_web_runner.dart#L295

## Related Issues

Fixes https://github.com/flutter/flutter/issues/41133.

## Tests

New resident_runner_test and devices_test.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 1]
```diff
@@ -553,25 +562,67 @@ class IOSDeviceLogReader extends DeviceLogReader {
...
+
+  @override
+  set connectedVMServices(List<VMService> connectedVMServices) {
+    _listenToLoggingEvents(connectedVMServices);
+    _connectedVMServices = connectedVMServices;
+  }
+
+  static const int _minimumUniversalLoggingSdkVersion = 13;
+
+  Future<void> _listenToLoggingEvents(List<VMService> vmServices) async {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/devices.dart]: This needs a test, working on it...

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 2]
```diff
@@ -553,25 +562,67 @@ class IOSDeviceLogReader extends DeviceLogReader {
...
+    if (device.majorSdkVersion < _minimumUniversalLoggingSdkVersion) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/ios/devices.dart]: won't this fail if `device.majorSdkVersion == null`?

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 3]
```diff
@@ -553,25 +562,67 @@ class IOSDeviceLogReader extends DeviceLogReader {
...
+      return;
+    }
+    for (VMService vmService in vmServices) {
+      // The VM service will not publish logging events unless the debug stream is being listened to.
+      // onDebugEvent listens to this stream as a side-effect.
+      if (_linesController.hasListener) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/ios/devices.dart]: This part is a little over-engineered in the dance between `_linesController` starting and setting connectedVMServices.  I'll simplify.

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 4]
```diff
@@ -553,25 +562,67 @@ class IOSDeviceLogReader extends DeviceLogReader {
...
         if (_linesController.hasListener) {
           _linesController.close();
         }
       });
       assert(_idevicesyslogProcess == null);
       _idevicesyslogProcess = process;
-    });
+    }));
+
+    if (connectedVMServices == null || device.majorSdkVersion < _minimumUniversalLoggingSdkVersion) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/ios/devices.dart]: same concern about if `device.majorSdkVersion == null`

File: packages/flutter_tools/lib/src/ios/devices.dart (hunk 2 above)
Comment (jmagman) [reply packages/flutter_tools/lib/src/ios/devices.dart]: 🤦‍♀

File: packages/flutter_tools/test/general.shard/resident_runner_test.dart [hunk 5]
```diff
@@ -626,6 +627,23 @@ void main() {
...
+    when(mockDevice.getLogReader(app: anyNamed('app'))).thenReturn(mockLogReader);
+
+    final TestFlutterDevice flutterDevice = TestFlutterDevice(
+      mockDevice,
+      <FlutterView>[],
+      observatoryUris: <Uri>[ testUri ]
+    );
+
+    await flutterDevice.connect();
+    verify(mockLogReader.connectedVMServices = <VMService>[ mockVMService ]);
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/resident_runner_test.dart]: wow, does this verify that an assignment happened? I didn't know you could do that.

File: packages/flutter_tools/lib/src/ios/devices.dart (hunk 2 above)
Comment (jonahwilliams) [reply packages/flutter_tools/lib/src/ios/devices.dart]: NNBD soon!

File: packages/flutter_tools/test/general.shard/resident_runner_test.dart (hunk 5 above)
Comment (jmagman) [reply packages/flutter_tools/test/general.shard/resident_runner_test.dart]: Seems to.  From the mockito docs:
```
// You can verify setters.
cat.lives = 9;
verify(cat.lives=9);
```

Comment (christopherfujino) [reply packages/flutter_tools/test/general.shard/resident_runner_test.dart]: I've skimmed that README many times and yet seem to have missed that. Cool.

**Comment by jmagman** [comment]
This doesn't fix the driver tests, that's a DIFFERENT VM service interface.
☹️

**Review by christopherfujino — APPROVED** [review]
LGTM
