### PR TITLE
Fix transparent `dividerColor` breaks `TabBar.tabAlignment`

### LINKED ISSUE #150316: `TabBar.tabAlignment` property does't work when `dividerColor` is transparent
### Steps to reproduce

I what tabs to be align at start and dividerColor is to be transparent. 

```
TabBar(
            dividerColor: Colors.transparent,
            tabAlignment: TabAlignment.start,
            isScrollable: true,
            tabs: [Tab(text: "a"), Tab(text: "b")])
```

But tabs are always at center, the property `tabAlignment ` does't work

### Expected results

I want tabs to be at start. It works when dividerColor is not set or set to any value but transparent

```
TabBar(
           dividerColor: Colors.red,
           tabAlignment: TabAlignment.start,
           isScrollable: true,
           tabs: [Tab(text: "a"), Tab(text: "b")])
```

bug2

### Actual results

you can see tabAlignment is set, but it does't work

```
 TabBar(
            dividerColor: Colors.transparent,
            tabAlignment: TabAlignment.start,
            isScrollable: true,
            tabs: [Tab(text: "a"), Tab(text: "b")])
```

bug1

### Code sample

<details open><summary>Full code sample.</summary>

```dart
class Sample extends StatefulWidget {
  @override
  _State createState() => _State();
}

class _State extends State<Sample> with TickerProviderStateMixin {

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length: 2,
        child: Scaffold(
            appBar: AppBar(
                bottom: TabBar(
                    dividerColor: Colors.transparent,
                    tabAlignment: TabAlignment.start,
                    isScrollable: true,
                    tabs: [Tab(text: "a"), Tab(text: "b")])),
            body: TabBarView(children: [
              Container(color: Colors.green),
              Container(color: Colors.blue)
            ])));
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19045.4529], locale ru-RU)
    • Flutter version 3.22.1 on channel stable at C:\flutter
    ! The flutter binary is not on your path. Consider adding C:\flutter\bin to
      your path.
    ! The dart binary is not on your path. Consider adding C:\flutter\bin to your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (4 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [`TabBar.tabAlignment` property does't work when `dividerColor` is transparent](https://github.com/flutter/flutter/issues/150316)

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: DefaultTabController(
        length: 2,
        child: Scaffold(
          appBar: AppBar(
            title: const Text('TabBar'),
            bottom: const TabBar(
              dividerColor: Colors.transparent,
              tabAlignment: TabAlignment.start,
              isScrollable: true,
              tabs: <Widget>[
                Tab(text: 'TAB 1'),
                Tab(text: 'TAB 2'),
              ],
            ),
          ),
          body: const TabBarView(
            children: <Widget>[
              SizedBox.expand(),
              SizedBox.expand(),
            ],
          ),
          floatingActionButton: FloatingActionButton(
            onPressed: () {},
            child: const Icon(Icons.add),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Before (`dividerColor: Colors.transparent`, `tabAlignment: TabAlignment.start`)

Screenshot 2024-06-17 at 15 44 33

### After (`dividerColor: Colors.transparent`, `tabAlignment: TabAlignment.start`)

Screenshot 2024-06-17 at 15 44 55

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

File: packages/flutter/lib/src/material/tabs.dart [hunk 1]
```diff
@@ -1814,7 +1818,7 @@ class _TabBarState extends State<TabBar> {
 
         final Color dividerColor = widget.dividerColor ?? tabBarTheme.dividerColor ?? _defaults.dividerColor!;
         final double dividerHeight = widget.dividerHeight ?? tabBarTheme.dividerHeight ?? _defaults.dividerHeight!;
-        final bool showDivider = dividerColor != Colors.transparent && dividerHeight > 0;
+        final bool showDivider = dividerHeight > 0;
```
Comment (justinmc) [inline packages/flutter/lib/src/material/tabs.dart:1821]: Then the first comment you added above is not true, right? The divider will still be drawn even when it is transparent.

**Review by justinmc — APPROVED** [review]
LGTM with a question about a comment you added.

**Comment by TahaTesser** [comment]
Resolved test class conflict from another of my `TabBar` PR https://github.com/flutter/flutter/pull/150041
