### PR TITLE
Closing search with system back button works

### LINKED ISSUE #18145: showSearch cannot be reopened after closing with OS back button
## Steps to Reproduce

1. call `showSearch()`
2. hit the OS back button on Android
3. try to call `showSearch()` again.

Everything works fine as long as you call `close(context, null)` inside your `SearchDelegate`, which is done when tapping the back arrow in the example.

## Logs

```
I/flutter (15760): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (15760): The following assertion was thrown while handling a gesture:
I/flutter (15760): 'package:flutter/src/material/search.dart': Failed assertion: line 55 pos 10: 'delegate._result ==
I/flutter (15760): null || delegate._result.isCompleted': is not true.
I/flutter (15760):
I/flutter (15760): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15760): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15760): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15760):   https://github.com/flutter/flutter/issues/new
I/flutter (15760):
I/flutter (15760): When the exception was thrown, this was the stack:
I/flutter (15760): #2      showSearch (package:flutter/src/material/search.dart)
I/flutter (15760): #3      _HomePageState.build.<anonymous closure> (file:///home/westy92/Source/checkiday-mobile/lib/main.dart:316:15)
I/flutter (15760): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
I/flutter (15760): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
I/flutter (15760): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (15760): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter (15760): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
I/flutter (15760): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (15760): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
I/flutter (15760): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (15760): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (15760): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (15760): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (15760): #15     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter (15760): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter (15760): (elided 2 frames from class _AssertionError)
I/flutter (15760):
I/flutter (15760): Handler: onTap
I/flutter (15760): Recognizer:
I/flutter (15760):   TapGestureRecognizer#25139(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter (15760):   Offset(357.0, 54.1), sent tap down)
```

```
Analyzing checkiday-mobile...                                    
No issues found! (ran in 16.0s)
```

```
[✓] Flutter (Channel dev, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at /home/westy92/Source/flutter
    • Framework revision c7ea3ca377 (4 days ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/westy92/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/westy92/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /home/westy92/android-studio
    • Flutter plugin version 21.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] VS Code (version 1.23.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Pixel • FA74C0300048 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/18145.

/cc @HansMuller

### CODE REVIEW

File: packages/flutter/lib/src/material/search.dart [hunk 1]
```diff
@@ -27,7 +27,8 @@ import 'theme.dart';
 /// be used as the initial query.
 ///
 /// The method returns the selected search result, which can be set in the
-/// [SearchDelegate.close] call.
+/// [SearchDelegate.close] call. If the search page is closed with the system
+/// back button it returns null.
```
Comment (Hixie) [inline packages/flutter/lib/src/material/search.dart]: comma before "it"

File: packages/flutter/lib/src/material/search.dart [hunk 2]
```diff
@@ -327,6 +328,12 @@ class _SearchPageRoute<T> extends PageRoute<void> {
     super.didComplete(result);
     assert(delegate._route == this);
     delegate._route = null;
+    // Ensure that [showSearch] future completes when the search route is
+    // removed by other means than calling [SearchDelegate.close].
```
Comment (Hixie) [inline packages/flutter/lib/src/material/search.dart]: "means other than"

File: packages/flutter/lib/src/material/search.dart [hunk 3]
```diff
@@ -327,6 +328,12 @@ class _SearchPageRoute<T> extends PageRoute<void> {
...
+    if (!delegate._result.isCompleted) {
+      delegate._result.complete(null);
```
Comment (Hixie) [inline packages/flutter/lib/src/material/search.dart]: why is this not completing with "result"?

Comment (Hixie) [reply packages/flutter/lib/src/material/search.dart]: or even better, why is it not just the route's future?

Comment (goderbauer) [reply packages/flutter/lib/src/material/search.dart]: I refactored it to use the route's future

(In a previous iteration we weren't able to do that because the search page consisted of two page routes, but that's no longer true and the completer was just a no-longer-needed artifact of that implementation)

File: packages/flutter/lib/src/material/search.dart [hunk 4]
```diff
@@ -27,7 +27,8 @@ import 'theme.dart';
 /// be used as the initial query.
 ///
 /// The method returns the selected search result, which can be set in the
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/search.dart]: This method

File: packages/flutter/test/material/search_test.dart [hunk 5]
```diff
@@ -42,6 +43,51 @@ void main() {
...
+    // Open search
+    await tester.tap(find.byTooltip('Search'));
+    await tester.pumpAndSettle();
+
+    expect(find.text('HomeBody'), findsNothing);
+    expect(find.text('HomeTitle'), findsNothing);
+    expect(find.text('Suggestions'), findsOneWidget);
+
+    // Simulate system back button
+    final ByteData message = const JSONMethodCodec().encodeMethodCall(const MethodCall('popRoute'));
```
Comment (HansMuller) [inline packages/flutter/test/material/search_test.dart]: Wow. Someday this should be a test utility.

**Review by HansMuller — APPROVED** [review]
LGTM
