### PR TITLE
Fix: Flicker when reorderable list doesn't change its position

### LINKED ISSUE #150843: ReorderableList - incorrect newIndex when dragging an item down and returning it to its original position
### Steps to reproduce

dragging an item down and without releasing return it to its original position

### Expected results

The item should return to its original position without a jump. with smooth animation 
see video below 

### Actual results

Since when returning to the original position the newIndex is not equal to the start index, it equals startIndex + 1, which leads to a jump in the animation.

### Code sample

code sample from https://api.flutter.dev/flutter/material/ReorderableListView-class.html
<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [ReorderableListView].

void main() => runApp(const ReorderableApp());

class ReorderableApp extends StatelessWidget {
  const ReorderableApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('ReorderableListView Sample')),
        body: const ReorderableExample(),
      ),
    );
  }
}

class ReorderableExample extends StatefulWidget {
  const ReorderableExample({super.key});

  @override
  State<ReorderableExample> createState() => _ReorderableListViewExampleState();
}

class _ReorderableListViewExampleState extends State<ReorderableExample> {
  final List<int> _items = List<int>.generate(50, (int index) => index);

  @override
  Widget build(BuildContext context) {
    final ColorScheme colorScheme = Theme.of(context).colorScheme;
    final Color oddItemColor = colorScheme.primary.withOpacity(0.05);
    final Color evenItemColor = colorScheme.primary.withOpacity(0.15);

    return ReorderableListView(
      padding: const EdgeInsets.symmetric(horizontal: 40),
      children: <Widget>[
        for (int index = 0; index < _items.length; index += 1)
          ListTile(
            key: Key('$index'),
            tileColor: _items[index].isOdd ? oddItemColor : evenItemColor,
            title: Text('Item ${_items[index]}'),
          ),
      ],
      onReorder: (int oldIndex, int newIndex) {
        setState(() {
          if (oldIndex < newIndex) {
            newIndex -= 1;
          }
          final int item = _items.removeAt(oldIndex);
          _items.insert(newIndex, item);
        });
      },
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
Actual result

https://github.com/flutter/flutter/assets/23139753/aa24a740-5552-4e8d-9fbe-ef596ee28987

 
Expected

https://github.com/flutter/flutter/assets/23139753/c768b4e7-6efc-4d6b-b55f-e7c3e5dc1b25

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale ru-UZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.90.0)
[✓] Connected device (5 available)
[✓] Network resources
```

</details>

### PR DESCRIPTION
**Pull request by rkishan516**
Fix: Flicker when no update in index of dragged item

Resolves #150843

This PR ensures that even if we move dragged item anywhere in list and comeback to initial position, we smoothly adjust to that position.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by goderbauer** [comment]
@rkishan516 Thank you for the contribution. It looks like it is failing some checks. Can you please take a look? Also, as per the bot message above: Can you add a test for this so we never regress this in the future? Thank you.

**Comment by rkishan516** [comment]
@goderbauer Sure, I will check failing checks and add tests.

**Comment by rkishan516** [comment]
@goderbauer I have added regression test for this, but need some help with other failing test.

**Comment by goderbauer** [comment]
Here are some resources that may be of help: https://github.com/flutter/flutter/blob/master/docs/contributing/testing/Running-and-writing-tests.md

**Comment by rkishan516** [comment]
@goderbauer I have fixed the tests, But I might have messed up in code quality. Can you please review ?

**Comment by chunhtai** [comment]
Hi @Piinks Can you take a look at this pr? feel free to reassign if not.

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 1]
```diff
@@ -903,7 +903,13 @@ class SliverReorderableListState extends State<SliverReorderableList> with Ticke
           newIndex = item.index;
         }
       } else {
-        if (itemStart <= proxyItemStart && proxyItemStart <= itemMiddle) {
+        if (item.index == _dragIndex!) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/reorderable_list.dart:906]: Would we not reach here based on the `continue` above?

Comment (rkishan516) [reply packages/flutter/lib/src/widgets/reorderable_list.dart:906]: No, because that will only `continue` if `_reverse` is true.

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 2]
```diff
@@ -717,6 +717,37 @@ void main() {
     expect(tester.getTopLeft(find.text('item 0')), const Offset(0, 500));
   });
 
+  testWidgets('SliverReorderableList - properly animates the drop at starting position', (WidgetTester tester) async {
```
Comment (Piinks) [inline packages/flutter/test/widgets/reorderable_list_test.dart:720]: Can you add a similar test where `reverse: true`?

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 3]
```diff
@@ -872,7 +872,7 @@ class SliverReorderableListState extends State<SliverReorderableList> with Ticke
     // Find the new index for inserting the item being dragged.
     int newIndex = _insertIndex!;
     for (final _ReorderableItemState item in _items.values) {
-      if (item.index == _dragIndex! || !item.mounted) {
+      if ((_reverse && item.index == _dragIndex!) || !item.mounted) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/reorderable_list.dart:875]: We should add a test in reverse as well to cover this case.

File: packages/flutter/test/widgets/reorderable_list_test.dart (hunk 2 above)
Comment (rkishan516) [reply packages/flutter/test/widgets/reorderable_list_test.dart:720]: @Piinks  I have pushed the required test.

File: packages/flutter/lib/src/material/dropdown_menu.dart [hunk 4]
```diff
@@ -613,8 +613,8 @@ class _DropdownMenuState<T> extends State<DropdownMenu<T>> {
       .toList();
   }
 
-  int? search(List<DropdownMenuEntry<T>> entries, TextEditingController textEditingController) {
-    final String searchText = textEditingController.value.text.toLowerCase();
+  int? search(List<DropdownMenuEntry<T>> entries) {
+    final String searchText = _localTextEditingController!.value.text.toLowerCase();
```
Comment (Piinks) [inline packages/flutter/lib/src/material/dropdown_menu.dart:617]: @rkishan516 should these changes be here? They appear unrelated.

**Review by Piinks — COMMENTED** [review]
@rkishan516 this looks just about ready to land, can you check the changes in the dropdown menu file? Maybe they were pulled in accidentally from a merge.

File: packages/flutter/lib/src/material/dropdown_menu.dart (hunk 4 above)
Comment (rkishan516) [reply packages/flutter/lib/src/material/dropdown_menu.dart]: Sorry, I don't know, How I messed it up today. I have fixed and pushed.

**Review by Piinks — APPROVED** [review]
LGTM, thank you!

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 5]
```diff
@@ -902,7 +902,13 @@ class SliverReorderableListState extends State<SliverReorderableList> with Ticke
           newIndex = item.index;
         }
       } else {
-        if (itemStart <= proxyItemStart && proxyItemStart <= itemMiddle) {
+        if (item.index == _dragIndex!) {
+          // If end of the proxy is in not in ending half of item
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/widgets/reorderable_list.dart:906]: Typo?
```suggestion
          // If end of the proxy is not in ending half of item,
```

File: packages/flutter/lib/src/widgets/reorderable_list.dart [hunk 6]
```diff
@@ -902,7 +902,13 @@ class SliverReorderableListState extends State<SliverReorderableList> with Ticke
...
+          // We don't process, because its drag item index
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/widgets/reorderable_list.dart:907]:
```suggestion
          // we don't process, because its drag item index.
```
This comment looks a little bit confusing, could you help double check? "because it's the original dragged item"?

**Review by QuncCccccc — APPROVED** [review]
LGTM with nits:) Thanks for the contribution!

File: packages/flutter/lib/src/widgets/reorderable_list.dart (hunk 6 above)
Comment (rkishan516) [reply packages/flutter/lib/src/widgets/reorderable_list.dart]: @QuncCccccc I have pushed the required changes.
