### PR TITLE
Remove package:flutter/foundation.dart import

### LINKED ISSUE #47700: devicelab flutter_driver_screenshot_test_ios test is failing 100%
## Steps to Reproduce

```terminal
$ cd dev/devicelab
$ dart bin/run.dart -t flutter_driver_screenshot_test_ios
```

## Logs
```
2019-12-23T13:28:19.931393: stdout: [   +1 ms] Running driver tests.
2019-12-23T13:28:19.932339: stdout: [        ] executing: /Users/flutter/.cocoon/flutter/bin/cache/dart-sdk/bin/dart /Users/flutter/.cocoon/flutter/dev/integration_tests/flutter_driver_screenshot_test/test_driver/main_test.dart --packages=/Users/flutter/.cocoon/flutter/dev/integration_tests/flutter_driver_screenshot_test/.packages -rexpanded
2019-12-23T13:28:22.541329: stderr: [+2608 ms] ../../../packages/flutter/lib/src/foundation/basic_types.dart:10:1: Error: Not found: 'dart:ui'
2019-12-23T13:28:22.541615: stderr: [        ] export 'dart:ui' show VoidCallback;
stderr: [        ] ^
2019-12-23T13:28:22.541762: stderr: [        ] ../../../packages/flutter/lib/src/foundation/binding.dart:9:8: Error: Not found: 'dart:ui'
2019-12-23T13:28:22.542022: stderr: [        ] import 'dart:ui' as ui show saveCompilationTrace, Window, window;
2019-12-23T13:28:22.542194: stderr: [        ]        ^
2019-12-23T13:28:22.542399: stderr: [        ] ../../../packages/flutter/lib/src/foundation/key.dart:5:8: Error: Not found: 'dart:ui'
2019-12-23T13:28:22.542589: stderr: [        ] import 'dart:ui' show hashValues;
2019-12-23T13:28:22.542819: stderr: [        ]        ^
2019-12-23T13:28:22.542974: stderr: [        ] ../../../packages/flutter/lib/src/foundation/binding.dart:87:3: Error: Type 'ui.Window' not found.
2019-12-23T13:28:22.543166: stderr: [        ]   ui.Window get window => ui.window;
2019-12-23T13:28:22.543353: stderr: [        ]   ^^^^^^^^^
2019-12-23T13:28:22.543552: stderr: [        ] ../../../packages/flutter/lib/src/foundation/change_notifier.dart:68:20: Error: Type 'VoidCallback' not found.
2019-12-23T13:28:22.543704: stderr: [        ]   void addListener(VoidCallback listener);
2019-12-23T13:28:22.544077: stderr: [        ]                    ^^^^^^^^^^^^
stderr: [        ] ../../../packages/flutter/lib/src/foundation/change_notifier.dart:72:23: Error: Type 'VoidCallback' not found.
2019-12-23T13:28:22.544383: stderr: [        ]   void removeListener(VoidCallback listener);
2019-12-23T13:28:22.544616: stderr: [        ]                       ^^^^^^^^^^^^
2019-12-23T13:28:22.544893: stderr: [        ] ../../../packages/flutter/lib/src/foundation/change_notifier.dart:100:16: Error: Type 'VoidCallback' not found.
2019-12-23T13:28:22.545029: stderr: [        ]   ObserverList<VoidCallback> _listeners = ObserverList<VoidCallback>();
2019-12-23T13:28:22.545210: stderr: [        ]                ^^^^^^^^^^^^
2019-12-23T13:28:22.545410: stderr: [        ] ../../../packages/flutter/lib/src/foundation/change_notifier.dart:140:20: Error: Type 'VoidCallback' not found.
2019-12-23T13:28:22.545617: stderr: [        ]   void addListener(VoidCallback listener) {
2019-12-23T13:28:22.545765: stderr: [        ]                    ^^^^^^^^^^^^
2019-12-23T13:28:22.545944: stderr: [        ] ../../../packages/flutter/lib/src/foundation/change_notifier.dart:165:23: Error: Type 'VoidCallback' not found.
2019-12-23T13:28:22.546128: stderr: [        ]   void removeListener(VoidCallback listener) {
2019-12-23T13:28:22.546326: stderr: [        ]                       ^^^^^^^^^^^^
2019-12-23T13:28:22.546492: stderr: [        ] ../../../packages/flutter/lib/src/foundation/change_notifier.dart:233:20: Error: Type 'VoidCallback' not found.
2019-12-23T13:28:22.546672: stderr: [        ]   void addListener(VoidCallback listener) {
2019-12-23T13:28:22.546860: stderr: [        ]                    ^^^^^^^^^^^^
2019-12-23T13:28:22.585044: stdout: [  +38 ms] Stopping application instance.
```

### PR DESCRIPTION
**Pull request by jmagman**
## Description

foundation [was imported](
https://github.com/flutter/flutter/blob/master/dev/integration_tests/flutter_driver_screenshot_test/test_driver/driver_screenshot_tester.dart#L8) into `driver_screenshot_tester` https://github.com/flutter/flutter/pull/47199 to be able to use `listEquals`.  However, foundation depends on `dart:ui` which isn't allowed in a driver test (AFAIK - https://github.com/flutter/flutter/issues/27826)

Change this to just import the utility file instead of the whole package.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/47700.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

File: dev/integration_tests/flutter_driver_screenshot_test/test_driver/driver_screenshot_tester.dart [hunk 1]
```diff
@@ -5,7 +5,7 @@
 import 'dart:async';
 import 'dart:io' show File;
 
-import 'package:flutter/foundation.dart';
+import 'package:flutter/src/foundation/collections.dart';
```
Comment (jmagman) [inline dev/integration_tests/flutter_driver_screenshot_test/test_driver/driver_screenshot_tester.dart]: Is this a terrible idea, @dnfield?  Would it better to copy this helper similar to `_deepEqualsList`?

Comment (dnfield) [reply dev/integration_tests/flutter_driver_screenshot_test/test_driver/driver_screenshot_tester.dart]: Hm. @goderbauer or @jonahwilliams is this expected?

I don't think we want to do an implementation import here.  What got changed that caused this?

Comment (dnfield) [reply dev/integration_tests/flutter_driver_screenshot_test/test_driver/driver_screenshot_tester.dart]: I see now.  

I'm not sure whether it's better to copy the implementation or use an impelemntation import here.  We should generally avoid both.

Comment (jmagman) [reply dev/integration_tests/flutter_driver_screenshot_test/test_driver/driver_screenshot_tester.dart]: You're saying you wouldn't expect foundation to implicitly require the dart:ui package?
The `dart:ui` imports/exports in the foundation package are years old.
```
foundation/basic_types.dart:10:1: Error: Not found: 'dart:ui'
export 'dart:ui' show 

foundation/binding.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show saveCompilationTrace, Window, window;

foundation/key.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show hashValues;\

foundation/binding.dart:87:3: Error: Type 'ui.Window' not found.
ui.Window get window => ui.window;

foundation/change_notifier.dart:68:20: Error: Type 'VoidCallback' not found.
void addListener(VoidCallback listener);

foundation/change_notifier.dart:72:23: Error: Type 'VoidCallback' not found.
void removeListener(VoidCallback listener);
```
see https://github.com/flutter/flutter/issues/47700 for full list.

**Review by dnfield — APPROVED** [review]
LGTM.  Thanks for digging into this.

File: dev/integration_tests/flutter_driver_screenshot_test/test_driver/driver_screenshot_tester.dart (hunk 1 above)
Comment (dnfield) [reply dev/integration_tests/flutter_driver_screenshot_test/test_driver/driver_screenshot_tester.dart]: We talked offline.  Driver shouldn't depend on foundation, agreed just writing function to do comparison is better.

**Comment by jmagman** [comment]
Merging on red build, looks like infra flakes.  Going to poke it.
