### PR TITLE
Registering multiple transformed events should work

### LINKED ISSUE #44037: [web] pointer_signal_resolver error
~/utd/a191020FlutterRecipe/recipes_app>flutter run -d chrome 
Launching lib/main.dart on Chrome in debug mode...
Building application for the web...                                14.1s
Attempting to connect to browser instance..                         4.5s

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
For a more detailed help message, press "h". To quit, press "q".
Debug service listening on ws://127.0.0.1:52386/EjKME3FVeJI=
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
Assertion failed:
org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
_currentEvent == null || _currentEvent == event
is not true

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 194:49      throw_
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3        assertFailed
package:flutter/src/gestures/pointer_signal_resolver.dart 32:59                           register
package:flutter/src/widgets/scrollable.dart 549:55                                        [_receivedPointerSignal]
package:flutter/src/rendering/proxy_box.dart 2574:14                                      handleEvent
package:flutter/src/gestures/binding.dart 198:14                                          dispatchEvent
package:flutter/src/gestures/binding.dart 156:7                                           [_handlePointerEvent]
package:flutter/src/gestures/binding.dart 102:7                                           [_flushPointerEventQueue]
package:flutter/src/gestures/binding.dart 86:32                                           [_handlePointerDataPacket]
package:build_web_compilers/lib/_engine/engine/pointer_binding.dart 89:15                 [_onPointerData]
package:build_web_compilers/lib/_engine/engine/pointer_binding.dart 277:7                 <fn>
package:build_web_compilers/lib/_engine/engine/pointer_binding.dart 573:56                <fn>
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall

Event:
PointerScrollEvent#74f2a(position: Offset(554.0, 725.0), timeStamp: 0:00:17.357674, pointer: 0,
kind: mouse, device: -1, down: false, scrollDelta: Offset(12.0, 154.0))
Target:
RenderPointerListener#29574 relayoutBoundary=up6
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12

Application finished.
~/utd/a191020FlutterRecipe/recipes_app>

### PR DESCRIPTION
**Pull request by mdebbar**
## Description

In some apps (e.g. Shrine in the flutter gallery) using the mouse wheel to scroll causes an assertion to be thrown.

This probably started happening when we started dispatching transformed events. If two hit targets receive a `PointerSignalEvent`, they both try to call `PointerSignalResolver.register()` but they pass different events (each target receives its own transformed event).

To fix this, we now compare `original` events. This way, multiple transformed events derived from the same original event work just fine.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/44037

## Tests

I added the following tests:
* `gestures/pointer_signal_resolver_test.dart`

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/gestures/pointer_signal_resolver.dart [hunk 1]
```diff
@@ -47,7 +51,7 @@ class PointerSignalResolver {
       assert(_currentEvent == null);
       return;
     }
-    assert((_currentEvent.original ?? _currentEvent) == event);
+    assert(_isSameEvent(_currentEvent, event));
```
Comment (mdebbar) [inline packages/flutter/lib/src/gestures/pointer_signal_resolver.dart]: @goderbauer @stuartmorgan is `resolve()` supposed to be called only with the original event?

Comment (stuartmorgan) [reply packages/flutter/lib/src/gestures/pointer_signal_resolver.dart]: This assertion is here because pointer signals are resolved synchronously, and thus there was no expectation that there would be more than one event being processed at any one time. After discussion with Hixie, the decision was to use a single event rather than a set, and assert that nothing was violating that invariant.

> If two hit targets receive a PointerSignalEvent, they both try to call `PointerSignalResolver.register()` but they pass different events (each target receives its own transformed event).

I'm not familiar with transformed events, is it just local coordinates per target or something along those lines? I.e., are they still a single conceptual event, which only one item should be claiming? If so, then this change should be fine. If there are multiple conceptual events at once then a more substantial change is required.

Comment (mdebbar) [reply packages/flutter/lib/src/gestures/pointer_signal_resolver.dart]: > is it just local coordinates per target or something along those lines?

That's exactly right.

Michael made a change few months ago so each hit target receives a "transformed" event. The transformer event keeps track of the original event it was created from. What I'm doing here is checking if the events have the `original` event (I.e. they were created from the same event).

Comment (mdebbar) [reply packages/flutter/lib/src/gestures/pointer_signal_resolver.dart]: IOW, yes the two events are generated from the same conceptual event.

Comment (goderbauer) [reply packages/flutter/lib/src/gestures/pointer_signal_resolver.dart]: > yes the two events are generated from the same conceptual event.

This is correct. And for the intents of the SignalRessolver they should be treated as the same event.

They way "resolve" is currently called grantees that it will always get the untransformed original event. However, I think it's fine to loosen that constraint as is done in this PR.

**Review by goderbauer — APPROVED** [review]
LGTM
