### PR TITLE
filter an assertiond log message from ios

### LINKED ISSUE #1989: assertiond assertion failed when running from Atom into iOS simulator
[iPhone 6] assertiond: assertion failed: 15D21 13A340: assertiond + 12188 [93893311-6962-33A7-A734-E36F946D8EBA]: 0x1

Full log:
https://gist.github.com/eseidelGoogle/3325fb4b24f05274e3db

Do I care? @chinmaygarde 

```
%flutter doctor                                                                                                [~]
Flutter root: /src/flutter.

[✓] iOS toolchain - develop for iOS devices (installed)
  [✓] XCode - enable development for iOS devices (installed)
  [✓] brew - install additional development packages (installed)
    [✓] ideviceinstaller - discover connected iOS devices (installed)
    [✓] ios-deploy - deploy to connected iOS devices (installed)

[✓] Android toolchain - develop for Android devices (installed)
  [✓] Android SDK - enable development for Android devices (installed)

Flutter from git@github.com:flutter/flutter.git (on master)
flutter revision: d93a87ee126071ddba26433db5255fc12d6297ca (18 hours ago)
```

### PR DESCRIPTION
**Pull request by devoncarew**
Filter an assertiond log message from the ios simulator (fix https://github.com/flutter/flutter/issues/1989).

@tvolkert @chinmaygarde

### CODE REVIEW

**Comment by chinmaygarde** [comment]
lgtm

File: packages/flutter_tools/lib/src/ios/simulators.dart [hunk 1]
```diff
@@ -731,6 +731,11 @@ class _IOSSimulatorLogReader extends DeviceLogReader {
           category == 'searchd')
         return null;
 
+      // assertiond: assertion failed: 15E65 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
```
Comment (eseidelGoogle) [inline packages/flutter_tools/lib/src/ios/simulators.dart]: @chinmaygarde what are the numbers in that message?  When I search google it shows me results after autocorrecting the long UUID.  Is that something relating to our signing?

Comment (eseidelGoogle) [inline packages/flutter_tools/lib/src/ios/simulators.dart]: Another one: http://stackoverflow.com/questions/34876146/unidentified-assertion-in-ios
