### PR TITLE
The `PopupMenuButton` should not steal focus from the TextField when it appears.

### LINKED ISSUE #24843: How to pin keyboard when Popupmenu appears
How can I hold the keyboard when click `PopupMenuButton`.
I have noticed that why the keyboard will disappear is  `PopupMenu` using `Navigation.push `
So, is there a workaournd to implement my require?

```dart
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: 150.0,
              child: TextField(
                autofocus: false,
                decoration: new InputDecoration(
                  hintStyle:
                      TextStyle(color: const Color(0xFFAAAAAA), fontSize: 15.0),
                  border: OutlineInputBorder(),
                ),
              ),
            ),
            PopupMenuButton<String>(
              onSelected: (String r) {},
              itemBuilder: (BuildContext context) => <PopupMenuEntry<String>>[
                    const PopupMenuItem<String>(
                      value: "text",
                      child: const Text('Popup'),
                    ),
                  ],
            ),
          ],
        ),
      ),
    );
  }
```

Here is the `flutter doctor -v`
```
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.14.1 18B75, locale en-HK)
    • Flutter version 0.10.2 at /usr/local/flutter
    • Framework revision d8cbb80206 (5 weeks ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME
      to that location.
      You may also want to add it to your PATH environment variable.


[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • iPhone 7 • 463B2CA4-5966-4EC8-B0BE-6A174EA45B7B • ios • iOS 12.1
      (simulator)

! Doctor found issues in 2 categories.
```

### LINKED ISSUE #50567: Popup menu floating with keyboard opened
If there's 2 Scaffold one inside the other when you tap on the 3-dots menu when the keyboard is open the keyboard will be closed and the menu will float.

I'm using the latest flutter stable release (1.12.13+hotfix.7)

Here's all the code to reproduce the error

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    List<Choice> choices = <Choice>[
      Choice(title: "Menu 1", icon: Icons.reorder),
    ];

    return Scaffold(
        body: Scaffold(
      bottomNavigationBar: BottomAppBar(
          color: Colors.red,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: <Widget>[
              PopupMenuButton<Choice>(
                icon: Icon(
                  Icons.more_vert,
                  color: Colors.white,
                ),
                itemBuilder: (BuildContext context) {
                  return choices.map((Choice choice) {
                    return PopupMenuItem<Choice>(
                      value: choice,
                      child: Text(choice.title),
                    );
                  }).toList();
                },
              ),
            ],
          )),
      body: Center(
        child: TextFormField(
          decoration: InputDecoration(labelText: "TFF1"),
        ),
      ),
    ));
  }
}

class Choice {
  const Choice({this.title, this.icon});

  final String title;
  final IconData icon;
}
```
</details>

### PR DESCRIPTION
**Pull request by yiiim**
Fixes: #24843
Fixes: #50567 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/popup_menu_test.dart [hunk 1]
```diff
@@ -4165,6 +4165,38 @@ void main() {
     ));
     expect(iconText.text.style?.color, Colors.red);
   });
+
+  testWidgets('The menu should not steal focus from the TextField when it appears.', (WidgetTester tester) async {
+    final FocusNode focusNode = FocusNode();
```
Comment (justinmc) [inline packages/flutter/test/material/popup_menu_test.dart:4170]: I would name this `fieldFocusNode` or something like that so it's clear what it's for when it's used below in expectations.

File: packages/flutter/test/material/popup_menu_test.dart [hunk 2]
```diff
@@ -4165,6 +4165,38 @@ void main() {
...
+                  ];
+                },
+                child: const Text('click here'),
+              )
+            ],
+          ),
+        ),
+      ),
+    );
+    await tester.tap(find.text('click here'));
```
Comment (justinmc) [inline packages/flutter/test/material/popup_menu_test.dart:4196]: Nit: I would also expect focusNode to have focus before that tap, just for completeness.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 3]
```diff
@@ -161,6 +161,11 @@ abstract class Route<T> extends _RoutePlaceholder {
     }
   }
 
+  /// When the route state is updated, request focus if the current route is at the top.
+  ///
+  /// Defaults to true.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/navigator.dart:166]: Can you mention Navigator.requestFocus here and explain how they relate?

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 4]
```diff
@@ -859,6 +859,7 @@ class _PopupMenuRoute<T> extends PopupRoute<T> {
     required this.clipBehavior,
     super.settings,
     this.popUpAnimationStyle,
+    this.requestFocus = false,
```
Comment (justinmc) [inline packages/flutter/lib/src/material/popup_menu.dart:862]: Are we sure that this is the behavior that most people want by default?

Comment (justinmc) [reply packages/flutter/lib/src/material/popup_menu.dart:862]: Also, am I right that this parameter will never be passed in since it's private, and it will always be false?

**Review by justinmc — COMMENTED** [review]
Thanks for the PR! I'm still trying to decide if this is the best approach here.

I wonder @chunhtai have you encountered this sort of thing before? Is there any other workaround?

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 3 above)
Comment (yiiim) [reply packages/flutter/lib/src/widgets/navigator.dart]: I made it default to `Navigator.requestFocus`, so it avoids needing two values to control whether to request focus.

File: packages/flutter/lib/src/material/popup_menu.dart (hunk 4 above)
Comment (yiiim) [reply packages/flutter/lib/src/material/popup_menu.dart]: I've made changes here, now it defaults to the same behavior as before.

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 5]
```diff
@@ -879,6 +880,9 @@ class _PopupMenuRoute<T> extends PopupRoute<T> {
   final BoxConstraints? constraints;
   final Clip clipBehavior;
   final AnimationStyle? popUpAnimationStyle;
+  final bool? _requestFocus;
+  @override
+  bool get requestFocus => _requestFocus ?? super.requestFocus;
```
Comment (justinmc) [inline packages/flutter/lib/src/material/popup_menu.dart:885]: What do you think about instead adding a requestFocus parameter to Route and then just piping the requestFocus parameter here in _PopupMenuRoute through to `super`? I think that would be a more typical Flutter pattern and it would probably be easier to reason about why requestFocus has a certain value.

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 6]
```diff
@@ -1419,6 +1426,11 @@ class PopupMenuButton<T> extends StatefulWidget {
   /// Null by default.
   final ButtonStyle? style;
 
+  /// Whether to request focus for it when the menu appears.
+  ///
+  /// Defaults is [Navigator.requestFocus].
```
Comment (justinmc) [inline packages/flutter/lib/src/material/popup_menu.dart:1431]: This is not strictly true. Instead maybe say: "If null, [Navigator.requestFocus] will be used instead."

Here and in a few other places where you document requestFocus.

**Review by justinmc — COMMENTED** [review]
Alright I briefly talked this over with @chunhtai and he doesn't see any reason not to take this approach. I'm on board as well; it makes sense that we should have a per-Route way to do what we already can do with Navigator.requestFocus.

Most of my comments are nits, except for one idea I had for putting this parameter on Route. I think it will clean up the code but I'd like your thoughts!

**Comment by saif-ellafi** [comment]
Looking forward to this. Thank you

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 7]
```diff
@@ -162,7 +162,11 @@ abstract class Route<T> extends _RoutePlaceholder {
   ///
   /// If the [settings] are not provided, an empty [RouteSettings] object is
   /// used instead.
-  Route({ RouteSettings? settings }) : _settings = settings ?? const RouteSettings() {
+  ///
+  /// If [requestFocus] is not provided, the value of [Navigator.requestFocus] is
+  /// used instead.
+  Route({ RouteSettings? settings, bool? requestFocus }) : _settings = settings ?? const RouteSettings(),
+  _requestFocus = requestFocus {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/navigator.dart:169]: Formatting nit:

```suggestion
  Route({
    RouteSettings? settings,
    bool? requestFocus,
  }) : _settings = settings ?? const RouteSettings(),
       _requestFocus = requestFocus {
```

**Review by justinmc — APPROVED** [review]
LGTM with a small formatting nit :+1:

File: packages/flutter/lib/src/material/popup_menu.dart [hunk 8]
```diff
@@ -1049,6 +1050,7 @@ Future<T?> showMenu<T>({
   Clip clipBehavior = Clip.none,
   RouteSettings? routeSettings,
   AnimationStyle? popUpAnimationStyle,
+  bool? requestFocus,
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/popup_menu.dart:1053]: some where in the showMenu doc should mention the behavior of this parameter

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by TahaTesser** [comment]
Hello everyone!

I somehow stumbled on this PR and I noticed this PR adds `requestFocus` parameter to classes/widgets other than related to PopupMenuButton such as bottom sheet, dialog, transition route, overlay route but doesn't test them.

It makes it possible to remove some of the `requestFocus` parameters  from this PR without failing any tests in the framework.

If anyone is interested in writing tests, please let me know. If not, I'd be happy to write those missing tests.

**Comment by yiiim** [comment]
@TahaTesser I'm sorry I didn't write enough tests. It would be great if you could write the tests.

**Comment by justinmc** [comment]
@TahaTesser Good catch, I missed that!

**Comment by TahaTesser** [comment]
Filed a PR with the missing tests https://github.com/flutter/flutter/pull/154005
