### PR TITLE
[web] Don't crash on `const HtmlElementView()`

### LINKED ISSUE #43532: const HtmlElementView prevents me from compiling non-web platforms
Using `const HtmlElementView()`, I get compilation errors when building for desktop.

The `assert(!kIsWeb)` in HtmlElementView fails at compile time even though the widget will never be built.

Doctor:

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.222, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2019.2)
[✓] VS Code (version 1.39.2)
[✓] Connected device (4 available)
```

### PR DESCRIPTION
**Pull request by mdebbar**
Previously, when the code contained `const HtmlElementView()` it would break even if it's guarded by `if (kIsWeb)`.

This PR makes it such that `const HtmlElementView()` is allowed but it still throws if it gets inserted into the widget tree by mistake on non-web platforms.

One improvement we can make in the future is to have a conditional import:
- `_html_element_view_web.dart` that contains the real `HtmlElementView` that can only be instantiated on web.
- `_html_element_view_io.dart` that contains a stub with an unimplemented `build()` method.

Fixes https://github.com/flutter/flutter/issues/43532

### CODE REVIEW

File: packages/flutter/test/widgets/platform_view_test.dart [hunk 1]
```diff
@@ -3168,4 +3168,28 @@ void main() {
...
+          width: 100,
+          height: 100,
+          child: htmlElementView,
+        ),
+      )
+    );
+    await tester.pumpAndSettle();
+
+    // This file runs on non-web platforms, so we expect `HtmlElementView` to
+    // fail.
```
Comment (ditman) [inline packages/flutter/test/widgets/platform_view_test.dart:3190]: Instead of this, why not `skip: kIsWeb` on the test? That way we know for sure this is a non-web test only?

**Review by ditman — APPROVED** [review]
LGTM, minor comment about skipping the new test when kIsWeb.

File: packages/flutter/test/widgets/platform_view_test.dart (hunk 1 above)
Comment (mdebbar) [reply packages/flutter/test/widgets/platform_view_test.dart:3190]: The entire file is not supposed to run on web (it has `@TestOn('!chrome')`). I bet all tests will fail, including the new one, if we accidentally run this file on web.

The comment is just to clarify for anyone who jumps directly to this test without looking at the entire file.

Comment (ditman) [reply packages/flutter/test/widgets/platform_view_test.dart:3190]: Ah, if there's a `@TestOn('!chrome')`, ship it (`dart-vm` would be better, though, this test would attempt to run in `firefox` if [I'm understanding this right](https://pub.dev/packages/test#platform-selectors))

Comment (mdebbar) [reply packages/flutter/test/widgets/platform_view_test.dart:3190]: Oh interesting. Yeah we definitely need to fix that. I'll create an issue so we don't forget.
