### PR TITLE
Exclude `Tooltip`'s overlay child from SelectableRegion

### LINKED ISSUE #129969: Application crash when dragging mouse over Tooltip while selecting text in SelectionArea
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Write an app with `SelectionArea`, add some text and some widget that show tooltips
2. Keep drag the mouse cursor to select the text, try to move the mouse over a tooltip
3. Crash in desktop debug mode (macOS in my case)

### Expected results

Should be able to select the text

### Actual results

```
Exception has occurred.
_AssertionError ('package:flutter/src/rendering/object.dart': Failed assertion: line 3263 pos 14: 'renderer.parent != null': is not true.)
```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: CrashTest(),
    );
  }
}

class CrashTest extends StatelessWidget {
  const CrashTest({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SelectionArea(
        child: Center(
          child: Column(
            children: [
              const Text("Select me"),
              const Text("Select me"),
              Tooltip(
                showDuration: const Duration(seconds: 30),
                message: 'Drag your mouse over me to crash your app',
                child: Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                ),
              ),
              const Text("Select me"),
              const Text("Select me"),
              const Text("Select me"),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
crash

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.12.0-12.0.pre.40, on macOS 13.2.1 22D68 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
[✓] VS Code (version 1.79.2)
[✓] VS Code (version 1.80.0-insider)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/129969 by making tooltip text unselectable (for now). 
Also fixes some other issues uncovered when I was writing the tests.

Currently `getTransformTo` only works on ancestors. I'll try to add a new method that computes the transform from 2 arbitrary render objects in the same render tree in a follow-up PR and make `Selectable` use that method instead.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/tooltip.dart [hunk 1]
```diff
@@ -755,13 +758,21 @@ class TooltipState extends State<Tooltip> with SingleTickerProviderStateMixin {
...
+      : SelectionContainer.disabled(child: overlayChild);
   }
 
   @override
   void dispose() {
     GestureBinding.instance.pointerRouter.removeGlobalRoute(_handleGlobalPointerEvent);
     Tooltip._openedTooltips.remove(this);
+    // Remove the onCancel callbacks to prevent the registered callbacks from
+    // triggering unnecessary sideeffects (such as animation).
+    _longPressRecognizer?.onLongPressCancel = null;
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/tooltip.dart:773]: This is surprising, why would it still fire if `_longPressRecognizer` is disposed?

Comment (chunhtai) [reply packages/flutter/lib/src/material/tooltip.dart:773]: This seems weird to me, the on cancel usually used for cleaning up the state in the owner when gesture is in progress. The owner won't expect the on cancel to be called if it is actively disposing the recognizer. it would be the owner's responsibility to clean up and state left behind when disposing the resource. WDYT?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/tooltip.dart:773]: From the gesture recognizer's perspective I guess that's expected? When there's an `onGestureStart`  someone would expect either an `onGestureUp` or `onGestureCancel`. The owner of the gesture recognizer may not be the owner of the gesture callbacks ?

e.g. `SomeWidgetWhoseElementOwnsALongPressGestureRecognizer(this.onLongPress, this.onLongPressCancel)`, when this widget unmounts the parent widget may appreciate that they're getting an `onLongPressCancel` to pair up with the `onLongPress` they received previously?

**Review by chunhtai — APPROVED** [review]
LGTM.
