### PR TITLE
Follow up scroll semantics update with documentation fixes

### LINKED ISSUE #23342: ListView constructor's addSemanticIndexes argument is undocumented

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/23342

### CODE REVIEW

File: packages/flutter/lib/src/widgets/sliver.dart [hunk 1]
```diff
@@ -301,8 +301,9 @@ class SliverChildBuilderDelegate extends SliverChildDelegate {
   /// Creates a delegate that supplies children for slivers using the given
   /// builder callback.
   ///
-  /// The [builder], [addAutomaticKeepAlives], and [addRepaintBoundaries]
-  /// arguments must not be null.
+  /// The [builder], [addAutomaticKeepAlives], [addRepaintBoundaries],
+  /// [addSemanticIndexes], and [semanticIndexCallback], arguments must not be
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/sliver.dart]: nit: remove comma before arguments?

File: packages/flutter/lib/src/widgets/sliver.dart [hunk 2]
```diff
@@ -461,8 +467,9 @@ class SliverChildListDelegate extends SliverChildDelegate {
   /// Creates a delegate that supplies children for slivers using the given
   /// list.
   ///
-  /// The [children], [addAutomaticKeepAlives], and [addRepaintBoundaries]
-  /// arguments must not be null.
+  /// The [children], [addAutomaticKeepAlives], [addRepaintBoundaries],
+  /// [addSemanticIndexes], and [semanticIndexCallback], arguments must not be
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/sliver.dart]: nit: same comma.

**Review by goderbauer — APPROVED** [review]
LGTM
