### PR TITLE
Fix user gesture in CupertinoPageRoute

### LINKED ISSUE #38183: HorizontalDragGestureRecognizer causes failed assertion when double tapping with Cupertino widgets
## Steps to Reproduce

Minimal example:

This example simply replaces the example in [flutter navigation basics](https://flutter.dev/docs/cookbook/navigation/navigation-basics) with Cupertino widgets.

```
import 'package:flutter/cupertino.dart';

void main() {
  runApp(CupertinoApp(
    title: 'Navigation Basics',
    home: FirstRoute(),
  ));
}

class FirstRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('First Route'),
      ),
      child: Center(
        child: CupertinoButton(
          child: Text('Open route'),
          onPressed: () {
            Navigator.push(
              context,
              CupertinoPageRoute(builder: (context) => SecondRoute()),
            );
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text("Second Route"),
      ),
      child: Center(
        child: CupertinoButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

1. Click the "Open route" button
2. Double tap anywhere on the left edge under the navigation bar.

## Logs

```
[  +24 ms] executing: [/Users/caleb.fung/flutter/] git log -n 1 --pretty=format:%H
[  +38 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 20e59316b8b8474554b38493b8ca888794b0234a
[        ] executing: [/Users/caleb.fung/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +16 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.7.8+hotfix.4-0-g20e59316b
[  +10 ms] executing: [/Users/caleb.fung/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/caleb.fung/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +44 ms] executing: [/Users/caleb.fung/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +193 ms] executing: /Users/caleb.fung/Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /Users/caleb.fung/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +4 ms] executing: idevice_id -h
[  +31 ms] /usr/bin/xcrun simctl list --json devices
[ +201 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +155 ms] Launching lib/main.dart on iPhone 7 in debug mode...
[   +4 ms] executing: /usr/bin/defaults read /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner/Info CFBundleIdentifier
[  +46 ms] Exit code 0 from: /usr/bin/defaults read /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner/Info CFBundleIdentifier
[   +2 ms] $(PRODUCT_BUNDLE_IDENTIFIER)
[  +12 ms] Building Runner.app for 6D90B229-9D1B-4238-88C0-BE32AF457121.
[  +18 ms] executing: script /dev/null /usr/bin/log stream --style syslog --predicate processImagePath CONTAINS "6D90B229-9D1B-4238-88C0-BE32AF457121"
[  +29 ms] [DEVICE LOG] Filtering the log data using "processImagePath CONTAINS "6D90B229-9D1B-4238-88C0-BE32AF457121""
[ +220 ms] Skipping kernel compilation. Fingerprint match.
[  +69 ms] Building bundle
[        ] Writing asset files to build/flutter_assets
[  +43 ms] Wrote build/flutter_assets
[  +10 ms] executing: [/Users/caleb.fung/Documents/flutter_app_accelerator/ios/] /usr/bin/xcodebuild -list
[ +864 ms] Information about project "Runner":
               Targets:
                   Runner

               Build Configurations:
                   Debug
                   Release
                   Profile

               If no build configuration is specified and -scheme is not passed then "Release" is used.

               Schemes:
                   Runner
[   +2 ms] Trying to resolve native pub services.
[   +1 ms] Looking for YAML at 'pubspec.yaml'
[   +2 ms] No services specified in the manifest
[        ] Found 0 service definition(s).
[   +1 ms] Copying service frameworks to '/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Frameworks'.
[        ] Creating service definitions manifest at '/Users/caleb.fung/Documents/flutter_app_accelerator/ios/ServiceDefinitions.json'
[  +31 ms] Running Xcode build...
[        ] executing: [/Users/caleb.fung/Documents/flutter_app_accelerator/ios/] /usr/bin/env xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios -sdk iphonesimulator -arch x86_64 FLUTTER_SUPPRESS_ANALYTICS=true
[+4447 ms] Build settings from command line:
               ARCHS = x86_64
               BUILD_DIR = /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios
               FLUTTER_SUPPRESS_ANALYTICS = true
               SDKROOT = iphonesimulator12.4
               VERBOSE_SCRIPT_LOGGING = YES

           note: Using new build system
           note: Planning build
           note: Constructing build description
           Build system information
           warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.4.99. (in target 'Flutter')

           ProcessProductPackaging "" /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios


           Entitlements:

           {
               "application-identifier" = "9Y3L2AFH84.com.example.flutterAppAccelerator";
               "keychain-access-groups" =     (
                   "9Y3L2AFH84.com.example.flutterAppAccelerator"
               );
           }


               builtin-productPackagingUtility -entitlements -format xml -o /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent

           ProcessProductPackaging "" /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app.xcent (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios


           Entitlements:

           {
               "com.apple.security.get-task-allow" = 1;
           }


               builtin-productPackagingUtility -entitlements -format xml -o /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app.xcent

           PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-D0A7EFD2148E0E755B608961.sh (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               /bin/sh -c /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-D0A7EFD2148E0E755B608961.sh

           PhaseScriptExecution Run\ Script /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export ACTION=build
               export AD_HOC_CODE_SIGNING_ALLOWED=YES
               export ALTERNATE_GROUP=staff
               export ALTERNATE_MODE=u+w,go-w,a+rX
               export ALTERNATE_OWNER=caleb.fung
               export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
               export ALWAYS_SEARCH_USER_PATHS=NO
               export ALWAYS_USE_SEPARATE_HEADERMAPS=NO
               export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
               export APPLE_INTERNAL_DIR=/AppleInternal
               export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
               export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
               export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
               export APPLICATION_EXTENSION_API_ONLY=NO
               export APPLY_RULES_IN_COPY_FILES=NO
               export ARCHS=x86_64
               export ARCHS_STANDARD=x86_64
               export ARCHS_STANDARD_32_64_BIT="i386 x86_64"
               export ARCHS_STANDARD_32_BIT=i386
               export ARCHS_STANDARD_64_BIT=x86_64
               export ARCHS_STANDARD_INCLUDING_64_BIT=x86_64
               export ARCHS_UNIVERSAL_IPHONE_OS="i386 x86_64"
               export ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon
               export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
               export AppIdentifierPrefix=9Y3L2AFH84.
               export BITCODE_GENERATION_MODE=marker
               export BUILD_ACTIVE_RESOURCES_ONLY=YES
               export BUILD_COMPONENTS="headers build"
               export BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios
               export BUILD_ROOT=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Products
               export BUILD_STYLE=
               export BUILD_VARIANTS=normal
               export BUILT_PRODUCTS_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               export CACHE_ROOT=/var/folders/y1/hbx4v2s16rd2qb95g2thpms80000gn/C/com.apple.DeveloperTools/10.3-10G8/Xcode
               export CCHROOT=/var/folders/y1/hbx4v2s16rd2qb95g2thpms80000gn/C/com.apple.DeveloperTools/10.3-10G8/Xcode
               export CHMOD=/bin/chmod
               export CHOWN=/usr/sbin/chown
               export CLANG_ANALYZER_NONNULL=YES
               export CLANG_CXX_LANGUAGE_STANDARD=gnu++0x
               export CLANG_CXX_LIBRARY=libc++
               export CLANG_ENABLE_MODULES=YES
               export CLANG_ENABLE_OBJC_ARC=YES
               export CLANG_MODULES_BUILD_SESSION_FILE=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation
               export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING=YES
               export CLANG_WARN_BOOL_CONVERSION=YES
               export CLANG_WARN_COMMA=YES
               export CLANG_WARN_CONSTANT_CONVERSION=YES
               export CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS=YES
               export CLANG_WARN_DIRECT_OBJC_ISA_USAGE=YES_ERROR
               export CLANG_WARN_EMPTY_BODY=YES
               export CLANG_WARN_ENUM_CONVERSION=YES
               export CLANG_WARN_INFINITE_RECURSION=YES
               export CLANG_WARN_INT_CONVERSION=YES
               export CLANG_WARN_NON_LITERAL_NULL_CONVERSION=YES
               export CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF=YES
               export CLANG_WARN_OBJC_LITERAL_CONVERSION=YES
               export CLANG_WARN_OBJC_ROOT_CLASS=YES_ERROR
               export CLANG_WARN_RANGE_LOOP_ANALYSIS=YES
               export CLANG_WARN_STRICT_PROTOTYPES=YES
               export CLANG_WARN_SUSPICIOUS_MOVE=YES
               export CLANG_WARN_UNREACHABLE_CODE=YES
               export CLANG_WARN__DUPLICATE_METHOD_MATCH=YES
               export CLASS_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/JavaClasses
               export CLEAN_PRECOMPS=YES
               export CLONE_HEADERS=NO
               export CODESIGNING_FOLDER_PATH=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app
               export CODE_SIGNING_ALLOWED=YES
               export CODE_SIGNING_REQUIRED=YES
               export CODE_SIGN_CONTEXT_CLASS=XCiPhoneSimulatorCodeSignContext
               export CODE_SIGN_IDENTITY=-
               export CODE_SIGN_INJECT_BASE_ENTITLEMENTS=YES
               export CODE_SIGN_STYLE=Manual
               export COLOR_DIAGNOSTICS=NO
               export COMBINE_HIDPI_IMAGES=NO
               export COMPILER_INDEX_STORE_ENABLE=Default
               export COMPOSITE_SDK_DIRS=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/CompositeSDKs
               export COMPRESS_PNG_FILES=YES
               export CONFIGURATION=Debug
               export CONFIGURATION_BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               export CONFIGURATION_TEMP_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator
               export CONTENTS_FOLDER_PATH=Runner.app
               export COPYING_PRESERVES_HFS_DATA=NO
               export COPY_HEADERS_RUN_UNIFDEF=NO
               export COPY_PHASE_STRIP=NO
               export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS=YES
               export CORRESPONDING_DEVICE_PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               export CORRESPONDING_DEVICE_PLATFORM_NAME=iphoneos
               export CORRESPONDING_DEVICE_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk
               export CORRESPONDING_DEVICE_SDK_NAME=iphoneos12.4
               export CP=/bin/cp
               export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
               export CURRENT_ARCH=undefined_arch
               export CURRENT_PROJECT_VERSION=1
               export CURRENT_VARIANT=normal
               export DEAD_CODE_STRIPPING=YES
               export DEBUGGING_SYMBOLS=YES
               export DEBUG_INFORMATION_FORMAT=dwarf
               export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
               export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
               export DEFINES_MODULE=NO
               export DEPLOYMENT_LOCATION=NO
               export DEPLOYMENT_POSTPROCESSING=NO
               export DEPLOYMENT_TARGET_CLANG_ENV_NAME=IPHONEOS_DEPLOYMENT_TARGET
               export DEPLOYMENT_TARGET_CLANG_FLAG_NAME=mios-simulator-version-min
               export DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX=-mios-simulator-version-min=
               export DEPLOYMENT_TARGET_LD_ENV_NAME=IPHONEOS_DEPLOYMENT_TARGET
               export DEPLOYMENT_TARGET_LD_FLAG_NAME=ios_simulator_version_min
               export DEPLOYMENT_TARGET_SETTING_NAME=IPHONEOS_DEPLOYMENT_TARGET
               export DEPLOYMENT_TARGET_SUGGESTED_VALUES="8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4"
               export DERIVED_FILES_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               export DERIVED_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               export DERIVED_SOURCES_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
               export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
               export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
               export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
               export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
               export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
               export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
               export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
               export DEVELOPMENT_LANGUAGE=en
               export DEVELOPMENT_TEAM=9Y3L2AFH84
               export DOCUMENTATION_FOLDER_PATH=Runner.app/en.lproj/Documentation
               export DO_HEADER_SCANNING_IN_JAM=NO
               export DSTROOT=/tmp/Runner.dst
               export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               export DWARF_DSYM_FILE_NAME=Runner.app.dSYM
               export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
               export DWARF_DSYM_FOLDER_PATH=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               export EFFECTIVE_PLATFORM_NAME=-iphonesimulator
               export EMBEDDED_CONTENT_CONTAINS_SWIFT=NO
               export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
               export ENABLE_BITCODE=NO
               export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES
               export ENABLE_HEADER_DEPENDENCIES=YES
               export ENABLE_ON_DEMAND_RESOURCES=YES
               export ENABLE_STRICT_OBJC_MSGSEND=YES
               export ENABLE_TESTABILITY=YES
               export ENTITLEMENTS_DESTINATION=__entitlements
               export ENTITLEMENTS_REQUIRED=YES
               export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
               export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
               export EXECUTABLES_FOLDER_PATH=Runner.app/Executables
               export EXECUTABLE_FOLDER_PATH=Runner.app
               export EXECUTABLE_NAME=Runner
               export EXECUTABLE_PATH=Runner.app/Runner
               export EXPANDED_CODE_SIGN_IDENTITY=-
               export EXPANDED_CODE_SIGN_IDENTITY_NAME=-
               export FILE_LIST=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects/LinkFileList
               export FIXED_FILES_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/FixedFiles
               export FLUTTER_APPLICATION_PATH=/Users/caleb.fung/Documents/flutter_app_accelerator
               export FLUTTER_BUILD_DIR=build
               export FLUTTER_BUILD_NAME=1.0.0
               export FLUTTER_BUILD_NUMBER=1
               export FLUTTER_FRAMEWORK_DIR=/Users/caleb.fung/flutter/bin/cache/artifacts/engine/ios
               export FLUTTER_ROOT=/Users/caleb.fung/flutter
               export FLUTTER_SUPPRESS_ANALYTICS=true
               export FLUTTER_TARGET=/Users/caleb.fung/Documents/flutter_app_accelerator/lib/main.dart
               export FRAMEWORKS_FOLDER_PATH=Runner.app/Frameworks
               export FRAMEWORK_FLAG_PREFIX=-framework
               export FRAMEWORK_SEARCH_PATHS="/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator  "/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Pods/../.symlinks/flutter/ios" "/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Pods/../.symlinks/flutter/ios" /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter"
               export FRAMEWORK_VERSION=A
               export FULL_PRODUCT_NAME=Runner.app
               export GCC3_VERSION=3.3
               export GCC_C_LANGUAGE_STANDARD=gnu99
               export GCC_DYNAMIC_NO_PIC=NO
               export GCC_INLINES_ARE_PRIVATE_EXTERN=YES
               export GCC_NO_COMMON_BLOCKS=YES
               export GCC_OBJC_LEGACY_DISPATCH=YES
               export GCC_OPTIMIZATION_LEVEL=0
               export GCC_PFE_FILE_C_DIALECTS="c objective-c c++ objective-c++"
               export GCC_PREPROCESSOR_DEFINITIONS="DEBUG=1  COCOAPODS=1 COCOAPODS=1"
               export GCC_SYMBOLS_PRIVATE_EXTERN=NO
               export GCC_TREAT_WARNINGS_AS_ERRORS=NO
               export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
               export GCC_VERSION_IDENTIFIER=com_apple_compilers_llvm_clang_1_0
               export GCC_WARN_64_TO_32_BIT_CONVERSION=YES
               export GCC_WARN_ABOUT_RETURN_TYPE=YES_ERROR
               export GCC_WARN_UNDECLARED_SELECTOR=YES
               export GCC_WARN_UNINITIALIZED_AUTOS=YES_AGGRESSIVE
               export GCC_WARN_UNUSED_FUNCTION=YES
               export GCC_WARN_UNUSED_VARIABLE=YES
               export GENERATE_MASTER_OBJECT_FILE=NO
               export GENERATE_PKGINFO_FILE=YES
               export GENERATE_PROFILING_CODE=NO
               export GENERATE_TEXT_BASED_STUBS=NO
               export GID=20
               export GROUP=staff
               export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
               export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
               export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
               export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
               export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
               export HEADERMAP_USES_VFS=NO
               export HEADER_SEARCH_PATHS="/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/include "
               export HIDE_BITCODE_SYMBOLS=YES
               export HOME=/Users/caleb.fung
               export ICONV=/usr/bin/iconv
               export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
               export INFOPLIST_FILE=Runner/Info.plist
               export INFOPLIST_OUTPUT_FORMAT=binary
               export INFOPLIST_PATH=Runner.app/Info.plist
               export INFOPLIST_PREPROCESS=NO
               export INFOSTRINGS_PATH=Runner.app/en.lproj/InfoPlist.strings
               export INLINE_PRIVATE_FRAMEWORKS=NO
               export INSTALLHDRS_COPY_PHASE=NO
               export INSTALLHDRS_SCRIPT_PHASE=NO
               export INSTALL_DIR=/tmp/Runner.dst/Applications
               export INSTALL_GROUP=staff
               export INSTALL_MODE_FLAG=u+w,go-w,a+rX
               export INSTALL_OWNER=caleb.fung
               export INSTALL_PATH=/Applications
               export INSTALL_ROOT=/tmp/Runner.dst
               export IPHONEOS_DEPLOYMENT_TARGET=12.4
               export JAVAC_DEFAULT_FLAGS="-J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8"
               export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               export JAVA_ARCHIVE_CLASSES=YES
               export JAVA_ARCHIVE_TYPE=JAR
               export JAVA_COMPILER=/usr/bin/javac
               export JAVA_FOLDER_PATH=Runner.app/Java
               export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
               export JAVA_JAR_FLAGS=cv
               export JAVA_SOURCE_SUBDIR=.
               export JAVA_USE_DEPENDENCIES=YES
               export JAVA_ZIP_FLAGS=-urg
               export JIKES_DEFAULT_FLAGS="+E +OLDCSO"
               export KEEP_PRIVATE_EXTERNS=NO
               export LD_DEPENDENCY_INFO_FILE=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/undefined_arch/Runner_dependency_info.dat
               export LD_ENTITLEMENTS_SECTION=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent
               export LD_GENERATE_MAP_FILE=NO
               export LD_MAP_FILE_PATH=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-LinkMap-normal-undefined_arch.txt
               export LD_NO_PIE=NO
               export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
               export LD_RUNPATH_SEARCH_PATHS=" '@executable_path/Frameworks' '@loader_path/Frameworks' '@executable_path/Frameworks' '@loader_path/Frameworks' @executable_path/Frameworks"
               export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               export LEX=lex
               export LIBRARY_FLAG_NOSPACE=YES
               export LIBRARY_FLAG_PREFIX=-l
               export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
               export LIBRARY_SEARCH_PATHS="/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator  /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter"
               export LINKER_DISPLAYS_MANGLED_NAMES=NO
               export LINK_FILE_LIST_normal_x86_64=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.LinkFileList
               export LINK_WITH_STANDARD_LIBRARIES=YES
               export LLVM_TARGET_TRIPLE_SUFFIX=-simulator
               export LOCALIZED_RESOURCES_FOLDER_PATH=Runner.app/en.lproj
               export LOCALIZED_STRING_MACRO_NAMES="NSLocalizedString CFLocalizedString"
               export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
               export LOCAL_APPS_DIR=/Applications
               export LOCAL_DEVELOPER_DIR=/Library/Developer
               export LOCAL_LIBRARY_DIR=/Library
               export LOCROOT=/Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export LOCSYMROOT=/Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export MACH_O_TYPE=mh_execute
               export MAC_OS_X_PRODUCT_BUILD_VERSION=18G87
               export MAC_OS_X_VERSION_ACTUAL=101406
               export MAC_OS_X_VERSION_MAJOR=101400
               export MAC_OS_X_VERSION_MINOR=1406
               export METAL_LIBRARY_FILE_BASE=default
               export METAL_LIBRARY_OUTPUT_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app
               export MODULE_CACHE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               export MTL_ENABLE_DEBUG_INFO=YES
               export NATIVE_ARCH=i386
               export NATIVE_ARCH_32_BIT=i386
               export NATIVE_ARCH_64_BIT=x86_64
               export NATIVE_ARCH_ACTUAL=x86_64
               export NO_COMMON=YES
               export OBJC_ABI_VERSION=2
               export OBJECT_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects
               export OBJECT_FILE_DIR_normal=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
               export OBJROOT=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex
               export ONLY_ACTIVE_ARCH=YES
               export OS=MACOS
               export OSAC=/usr/bin/osacompile
               export OTHER_LDFLAGS=" -ObjC -framework "Flutter" -ObjC -framework "Flutter""
               export PACKAGE_TYPE=com.apple.package-type.wrapper.application
               export PASCAL_STRINGS=YES
               export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Users/caleb.fung/Library/Android/sdk/emulator:/Users/caleb.fung/Library/Android/sdk/tools:/Users/caleb.fung/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/caleb.fung/flutter/bin"
               export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
               export PBDEVELOPMENTPLIST_PATH=Runner.app/pbdevelopment.plist
               export PER_ARCH_OBJECT_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/undefined_arch
               export PER_VARIANT_OBJECT_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
               export PKGINFO_FILE_PATH=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PkgInfo
               export PKGINFO_PATH=Runner.app/PkgInfo
               export PLATFORM_DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
               export PLATFORM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
               export PLATFORM_DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library
               export PLATFORM_DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
               export PLATFORM_DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
               export PLATFORM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
               export PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               export PLATFORM_DISPLAY_NAME="iOS Simulator"
               export PLATFORM_NAME=iphonesimulator
               export PLATFORM_PREFERRED_ARCH=x86_64
               export PLATFORM_PRODUCT_BUILD_VERSION=10G8
               export PLIST_FILE_OUTPUT_FORMAT=binary
               export PLUGINS_FOLDER_PATH=Runner.app/PlugIns
               export PODS_BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios
               export PODS_CONFIGURATION_BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               export PODS_PODFILE_DIR_PATH=/Users/caleb.fung/Documents/flutter_app_accelerator/ios/.
               export PODS_ROOT=/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Pods
               export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
               export PRECOMP_DESTINATION_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PrefixHeaders
               export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
               export PRIVATE_HEADERS_FOLDER_PATH=Runner.app/PrivateHeaders
               export PRODUCT_BUNDLE_IDENTIFIER=com.example.flutterAppAccelerator
               export PRODUCT_MODULE_NAME=Runner
               export PRODUCT_NAME=Runner
               export PRODUCT_SETTINGS_PATH=/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner/Info.plist
               export PRODUCT_TYPE=com.apple.product-type.application
               export PROFILING_CODE=NO
               export PROJECT=Runner
               export PROJECT_DERIVED_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/DerivedSources
               export PROJECT_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export PROJECT_FILE_PATH=/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner.xcodeproj
               export PROJECT_NAME=Runner
               export PROJECT_TEMP_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build
               export PROJECT_TEMP_ROOT=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex
               export PROVISIONING_PROFILE_SPECIFIER=Wildcard
               export PUBLIC_HEADERS_FOLDER_PATH=Runner.app/Headers
               export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS=YES
               export REMOVE_CVS_FROM_RESOURCES=YES
               export REMOVE_GIT_FROM_RESOURCES=YES
               export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
               export REMOVE_HG_FROM_RESOURCES=YES
               export REMOVE_SVN_FROM_RESOURCES=YES
               export REZ_COLLECTOR_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources
               export REZ_OBJECTS_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources/Objects
               export REZ_SEARCH_PATHS="/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator "
               export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
               export SCRIPTS_FOLDER_PATH=Runner.app/Scripts
               export SCRIPT_INPUT_FILE_COUNT=0
               export SCRIPT_INPUT_FILE_LIST_COUNT=0
               export SCRIPT_OUTPUT_FILE_COUNT=0
               export SCRIPT_OUTPUT_FILE_LIST_COUNT=0
               export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk
               export SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk
               export SDK_DIR_iphonesimulator12_4=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk
               export SDK_NAME=iphonesimulator12.4
               export SDK_NAMES=iphonesimulator12.4
               export SDK_PRODUCT_BUILD_VERSION=16G73
               export SDK_VERSION=12.4
               export SDK_VERSION_ACTUAL=120400
               export SDK_VERSION_MAJOR=120000
               export SDK_VERSION_MINOR=400
               export SED=/usr/bin/sed
               export SEPARATE_STRIP=NO
               export SEPARATE_SYMBOL_EDIT=NO
               export SET_DIR_MODE_OWNER_GROUP=YES
               export SET_FILE_MODE_OWNER_GROUP=NO
               export SHALLOW_BUNDLE=YES
               export SHARED_DERIVED_FILE_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/DerivedSources
               export SHARED_FRAMEWORKS_FOLDER_PATH=Runner.app/SharedFrameworks
               export SHARED_PRECOMPS_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/PrecompiledHeaders
               export SHARED_SUPPORT_FOLDER_PATH=Runner.app/SharedSupport
               export SKIP_INSTALL=NO
               export SOURCE_ROOT=/Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export SRCROOT=/Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export STRINGS_FILE_OUTPUT_ENCODING=binary
               export STRIP_BITCODE_FROM_COPIED_FILES=NO
               export STRIP_INSTALLED_PRODUCT=YES
               export STRIP_STYLE=all
               export STRIP_SWIFT_SYMBOLS=YES
               export SUPPORTED_DEVICE_FAMILIES=1,2
               export SUPPORTED_PLATFORMS="iphoneos iphonesimulator"
               export SUPPORTS_TEXT_BASED_API=NO
               export SWIFT_PLATFORM_TARGET_PREFIX=ios
               export SYMROOT=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Products
               export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
               export SYSTEM_APPS_DIR=/Applications
               export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
               export SYSTEM_DEMOS_DIR=/Applications/Extras
               export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
               export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
               export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
               export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
               export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
               export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
               export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
               export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
               export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
               export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
               export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
               export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
               export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
               export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
               export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
               export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
               export SYSTEM_LIBRARY_DIR=/System/Library
               export TAPI_VERIFY_MODE=ErrorsOnly
               export TARGETED_DEVICE_FAMILY=1,2
               export TARGETNAME=Runner
               export TARGET_BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               export TARGET_DEVICE_IDENTIFIER=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder
               export TARGET_NAME=Runner
               export TARGET_TEMP_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_FILES_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_ROOT=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex
               export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
               export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
               export TeamIdentifierPrefix=9Y3L2AFH84.
               export UID=501
               export UNLOCALIZED_RESOURCES_FOLDER_PATH=Runner.app
               export UNSTRIPPED_PRODUCT=NO
               export USER=caleb.fung
               export USER_APPS_DIR=/Users/caleb.fung/Applications
               export USER_LIBRARY_DIR=/Users/caleb.fung/Library
               export USE_DYNAMIC_NO_PIC=YES
               export USE_HEADERMAP=YES
               export USE_HEADER_SYMLINKS=NO
               export VALIDATE_PRODUCT=NO
               export VALID_ARCHS="i386 x86_64"
               export VERBOSE_PBXCP=NO
               export VERBOSE_SCRIPT_LOGGING=YES
               export VERSIONING_SYSTEM=apple-generic
               export VERSIONPLIST_PATH=Runner.app/version.plist
               export VERSION_INFO_BUILDER=caleb.fung
               export VERSION_INFO_FILE=Runner_vers.c
               export VERSION_INFO_STRING=""@(#)PROGRAM:Runner  PROJECT:Runner-1""
               export WRAPPER_EXTENSION=app
               export WRAPPER_NAME=Runner.app
               export WRAPPER_SUFFIX=.app
               export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
               export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
               export XCODE_PRODUCT_BUILD_VERSION=10G8
               export XCODE_VERSION_ACTUAL=1030
               export XCODE_VERSION_MAJOR=1000
               export XCODE_VERSION_MINOR=1030
               export XPCSERVICES_FOLDER_PATH=Runner.app/XPCServices
               export YACC=yacc
               export arch=undefined_arch
               export variant=normal
               /bin/sh -c /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh
           ♦ mkdir -p -- /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter
           ♦ rm -rf -- /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/App.framework
           ♦ rm -rf -- /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/Flutter.framework
           ♦ cp -r -- /Users/caleb.fung/flutter/bin/cache/artifacts/engine/ios/Flutter.framework /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter
           ♦ find /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/Flutter.framework -type f -exec chmod a-w {} ;
           ♦ mkdir -p -- /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/App.framework
           ♦ eval 
           ♦ cp -- /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/AppFrameworkInfo.plist /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/App.framework/Info.plist
           ♦ /Users/caleb.fung/flutter/bin/flutter --verbose build bundle --target-platform=ios --target=/Users/caleb.fung/Documents/flutter_app_accelerator/lib/main.dart --debug --depfile=build/snapshot_blob.bin.d --asset-dir=/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/App.framework/flutter_assets
           [  +18 ms] executing: [/Users/caleb.fung/flutter/] git log -n 1 --pretty=format:%H
           [  +28 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
           [        ] 20e59316b8b8474554b38493b8ca888794b0234a
           [        ] executing: [/Users/caleb.fung/flutter/] git describe --match v*.*.* --first-parent --long --tags
           [   +7 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
           [        ] v1.7.8+hotfix.4-0-g20e59316b
           [  +14 ms] executing: [/Users/caleb.fung/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
           [   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
           [        ] origin/stable
           [        ] executing: [/Users/caleb.fung/flutter/] git ls-remote --get-url origin
           [   +6 ms] Exit code 0 from: git ls-remote --get-url origin
           [        ] https://github.com/flutter/flutter.git
           [  +36 ms] executing: [/Users/caleb.fung/flutter/] git rev-parse --abbrev-ref HEAD
           [   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
           [        ] stable
           [  +76 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
           [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
           [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
           [ +276 ms] Skipping kernel compilation. Fingerprint match.
           [  +56 ms] Building bundle
           [        ] Writing asset files to /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/App.framework/flutter_assets
           [  +37 ms] Wrote /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/App.framework/flutter_assets
           [   +9 ms] "flutter bundle" took 450ms.
           [        ] "flutter bundle" took 450ms.
           Project /Users/caleb.fung/Documents/flutter_app_accelerator built and packaged successfully.

           CompileC /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.o /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner/GeneratedPluginRegistrant.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export LANG=en_US.US-ASCII
               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DCOCOAPODS=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=12.4 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Index/DataStore -iquote /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-generated-files.hmap -I/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-own-target-headers.hmap -I/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-all-target-headers.hmap -iquote /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-project-headers.hmap -I/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/include -I/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources-normal/x86_64 -I/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64 -I/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -F/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator -F/Users/caleb.fung/Documents/flutter_app_accelerator/ios/.symlinks/flutter/ios -F/Users/caleb.fung/Documents/flutter_app_accelerator/ios/.symlinks/flutter/ios -F/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter -MMD -MT dependencies -MF /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.d --serialize-diagnostics /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.dia -c /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner/GeneratedPluginRegistrant.m -o /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/GeneratedPluginRegistrant.o

           CompileC /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.o /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export LANG=en_US.US-ASCII
               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DCOCOAPODS=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=12.4 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Index/DataStore -iquote /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-generated-files.hmap -I/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-own-target-headers.hmap -I/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-all-target-headers.hmap -iquote /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-project-headers.hmap -I/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/include -I/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources-normal/x86_64 -I/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64 -I/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -F/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator -F/Users/caleb.fung/Documents/flutter_app_accelerator/ios/.symlinks/flutter/ios -F/Users/caleb.fung/Documents/flutter_app_accelerator/ios/.symlinks/flutter/ios -F/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter -MMD -MT dependencies -MF /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.d --serialize-diagnostics /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.dia -c /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner/AppDelegate.m -o /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/AppDelegate.o

           Ld /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Runner normal x86_64 (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export IPHONEOS_DEPLOYMENT_TARGET=12.4
               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk -L/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator -L/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter -F/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator -F/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Pods/../.symlinks/flutter/ios -F/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Pods/../.symlinks/flutter/ios -F/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter -filelist /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=12.4 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -framework Flutter -ObjC -framework Flutter -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent -framework Flutter -framework App -lPods-Runner -Xlinker -dependency_info -Xlinker /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat -o /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Runner

           ProcessInfoPlistFile /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Info.plist /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner/Info.plist (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               builtin-infoPlistUtility /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner/Info.plist -producttype com.apple.product-type.application -genpkginfo /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/PkgInfo -expandbuildsettings -format binary -platform iphonesimulator -additionalcontentfile /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Base.lproj/LaunchScreen-SBPartialInfo.plist -additionalcontentfile /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Base.lproj/Main-SBPartialInfo.plist -additionalcontentfile /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/assetcatalog_generated_info.plist -o /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Info.plist

           PBXCp /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/Flutter.framework /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -exclude Headers -exclude PrivateHeaders -exclude Modules -exclude \*.tbd -resolve-src-symlinks /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/Flutter.framework /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks

           PBXCp /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/App.framework /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/App.framework (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -exclude Headers -exclude PrivateHeaders -exclude Modules -exclude \*.tbd -resolve-src-symlinks /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter/App.framework /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks

           CodeSign /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/App.framework (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate

           Signing Identity:     "-"

               /usr/bin/codesign --force --sign - --timestamp=none --preserve-metadata=identifier,entitlements,flags /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/App.framework

           CodeSign /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate

           Signing Identity:     "-"

               /usr/bin/codesign --force --sign - --timestamp=none --preserve-metadata=identifier,entitlements,flags /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework

           PhaseScriptExecution Thin\ Binary /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export ACTION=build
               export AD_HOC_CODE_SIGNING_ALLOWED=YES
               export ALTERNATE_GROUP=staff
               export ALTERNATE_MODE=u+w,go-w,a+rX
               export ALTERNATE_OWNER=caleb.fung
               export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
               export ALWAYS_SEARCH_USER_PATHS=NO
               export ALWAYS_USE_SEPARATE_HEADERMAPS=NO
               export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
               export APPLE_INTERNAL_DIR=/AppleInternal
               export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
               export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
               export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
               export APPLICATION_EXTENSION_API_ONLY=NO
               export APPLY_RULES_IN_COPY_FILES=NO
               export ARCHS=x86_64
               export ARCHS_STANDARD=x86_64
               export ARCHS_STANDARD_32_64_BIT="i386 x86_64"
               export ARCHS_STANDARD_32_BIT=i386
               export ARCHS_STANDARD_64_BIT=x86_64
               export ARCHS_STANDARD_INCLUDING_64_BIT=x86_64
               export ARCHS_UNIVERSAL_IPHONE_OS="i386 x86_64"
               export ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon
               export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
               export AppIdentifierPrefix=9Y3L2AFH84.
               export BITCODE_GENERATION_MODE=marker
               export BUILD_ACTIVE_RESOURCES_ONLY=YES
               export BUILD_COMPONENTS="headers build"
               export BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios
               export BUILD_ROOT=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Products
               export BUILD_STYLE=
               export BUILD_VARIANTS=normal
               export BUILT_PRODUCTS_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               export CACHE_ROOT=/var/folders/y1/hbx4v2s16rd2qb95g2thpms80000gn/C/com.apple.DeveloperTools/10.3-10G8/Xcode
               export CCHROOT=/var/folders/y1/hbx4v2s16rd2qb95g2thpms80000gn/C/com.apple.DeveloperTools/10.3-10G8/Xcode
               export CHMOD=/bin/chmod
               export CHOWN=/usr/sbin/chown
               export CLANG_ANALYZER_NONNULL=YES
               export CLANG_CXX_LANGUAGE_STANDARD=gnu++0x
               export CLANG_CXX_LIBRARY=libc++
               export CLANG_ENABLE_MODULES=YES
               export CLANG_ENABLE_OBJC_ARC=YES
               export CLANG_MODULES_BUILD_SESSION_FILE=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation
               export CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING=YES
               export CLANG_WARN_BOOL_CONVERSION=YES
               export CLANG_WARN_COMMA=YES
               export CLANG_WARN_CONSTANT_CONVERSION=YES
               export CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS=YES
               export CLANG_WARN_DIRECT_OBJC_ISA_USAGE=YES_ERROR
               export CLANG_WARN_EMPTY_BODY=YES
               export CLANG_WARN_ENUM_CONVERSION=YES
               export CLANG_WARN_INFINITE_RECURSION=YES
               export CLANG_WARN_INT_CONVERSION=YES
               export CLANG_WARN_NON_LITERAL_NULL_CONVERSION=YES
               export CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF=YES
               export CLANG_WARN_OBJC_LITERAL_CONVERSION=YES
               export CLANG_WARN_OBJC_ROOT_CLASS=YES_ERROR
               export CLANG_WARN_RANGE_LOOP_ANALYSIS=YES
               export CLANG_WARN_STRICT_PROTOTYPES=YES
               export CLANG_WARN_SUSPICIOUS_MOVE=YES
               export CLANG_WARN_UNREACHABLE_CODE=YES
               export CLANG_WARN__DUPLICATE_METHOD_MATCH=YES
               export CLASS_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/JavaClasses
               export CLEAN_PRECOMPS=YES
               export CLONE_HEADERS=NO
               export CODESIGNING_FOLDER_PATH=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app
               export CODE_SIGNING_ALLOWED=YES
               export CODE_SIGNING_REQUIRED=YES
               export CODE_SIGN_CONTEXT_CLASS=XCiPhoneSimulatorCodeSignContext
               export CODE_SIGN_IDENTITY=-
               export CODE_SIGN_INJECT_BASE_ENTITLEMENTS=YES
               export CODE_SIGN_STYLE=Manual
               export COLOR_DIAGNOSTICS=NO
               export COMBINE_HIDPI_IMAGES=NO
               export COMPILER_INDEX_STORE_ENABLE=Default
               export COMPOSITE_SDK_DIRS=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/CompositeSDKs
               export COMPRESS_PNG_FILES=YES
               export CONFIGURATION=Debug
               export CONFIGURATION_BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               export CONFIGURATION_TEMP_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator
               export CONTENTS_FOLDER_PATH=Runner.app
               export COPYING_PRESERVES_HFS_DATA=NO
               export COPY_HEADERS_RUN_UNIFDEF=NO
               export COPY_PHASE_STRIP=NO
               export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS=YES
               export CORRESPONDING_DEVICE_PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               export CORRESPONDING_DEVICE_PLATFORM_NAME=iphoneos
               export CORRESPONDING_DEVICE_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk
               export CORRESPONDING_DEVICE_SDK_NAME=iphoneos12.4
               export CP=/bin/cp
               export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
               export CURRENT_ARCH=undefined_arch
               export CURRENT_PROJECT_VERSION=1
               export CURRENT_VARIANT=normal
               export DEAD_CODE_STRIPPING=YES
               export DEBUGGING_SYMBOLS=YES
               export DEBUG_INFORMATION_FORMAT=dwarf
               export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
               export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions
               export DEFINES_MODULE=NO
               export DEPLOYMENT_LOCATION=NO
               export DEPLOYMENT_POSTPROCESSING=NO
               export DEPLOYMENT_TARGET_CLANG_ENV_NAME=IPHONEOS_DEPLOYMENT_TARGET
               export DEPLOYMENT_TARGET_CLANG_FLAG_NAME=mios-simulator-version-min
               export DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX=-mios-simulator-version-min=
               export DEPLOYMENT_TARGET_LD_ENV_NAME=IPHONEOS_DEPLOYMENT_TARGET
               export DEPLOYMENT_TARGET_LD_FLAG_NAME=ios_simulator_version_min
               export DEPLOYMENT_TARGET_SETTING_NAME=IPHONEOS_DEPLOYMENT_TARGET
               export DEPLOYMENT_TARGET_SUGGESTED_VALUES="8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4"
               export DERIVED_FILES_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               export DERIVED_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               export DERIVED_SOURCES_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
               export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
               export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
               export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
               export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
               export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
               export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
               export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
               export DEVELOPMENT_LANGUAGE=en
               export DEVELOPMENT_TEAM=9Y3L2AFH84
               export DOCUMENTATION_FOLDER_PATH=Runner.app/en.lproj/Documentation
               export DO_HEADER_SCANNING_IN_JAM=NO
               export DSTROOT=/tmp/Runner.dst
               export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               export DWARF_DSYM_FILE_NAME=Runner.app.dSYM
               export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
               export DWARF_DSYM_FOLDER_PATH=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               export EFFECTIVE_PLATFORM_NAME=-iphonesimulator
               export EMBEDDED_CONTENT_CONTAINS_SWIFT=NO
               export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
               export ENABLE_BITCODE=NO
               export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES
               export ENABLE_HEADER_DEPENDENCIES=YES
               export ENABLE_ON_DEMAND_RESOURCES=YES
               export ENABLE_STRICT_OBJC_MSGSEND=YES
               export ENABLE_TESTABILITY=YES
               export ENTITLEMENTS_DESTINATION=__entitlements
               export ENTITLEMENTS_REQUIRED=YES
               export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
               export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
               export EXECUTABLES_FOLDER_PATH=Runner.app/Executables
               export EXECUTABLE_FOLDER_PATH=Runner.app
               export EXECUTABLE_NAME=Runner
               export EXECUTABLE_PATH=Runner.app/Runner
               export EXPANDED_CODE_SIGN_IDENTITY=-
               export EXPANDED_CODE_SIGN_IDENTITY_NAME=-
               export FILE_LIST=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects/LinkFileList
               export FIXED_FILES_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/FixedFiles
               export FLUTTER_APPLICATION_PATH=/Users/caleb.fung/Documents/flutter_app_accelerator
               export FLUTTER_BUILD_DIR=build
               export FLUTTER_BUILD_NAME=1.0.0
               export FLUTTER_BUILD_NUMBER=1
               export FLUTTER_FRAMEWORK_DIR=/Users/caleb.fung/flutter/bin/cache/artifacts/engine/ios
               export FLUTTER_ROOT=/Users/caleb.fung/flutter
               export FLUTTER_SUPPRESS_ANALYTICS=true
               export FLUTTER_TARGET=/Users/caleb.fung/Documents/flutter_app_accelerator/lib/main.dart
               export FRAMEWORKS_FOLDER_PATH=Runner.app/Frameworks
               export FRAMEWORK_FLAG_PREFIX=-framework
               export FRAMEWORK_SEARCH_PATHS="/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator  "/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Pods/../.symlinks/flutter/ios" "/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Pods/../.symlinks/flutter/ios" /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter"
               export FRAMEWORK_VERSION=A
               export FULL_PRODUCT_NAME=Runner.app
               export GCC3_VERSION=3.3
               export GCC_C_LANGUAGE_STANDARD=gnu99
               export GCC_DYNAMIC_NO_PIC=NO
               export GCC_INLINES_ARE_PRIVATE_EXTERN=YES
               export GCC_NO_COMMON_BLOCKS=YES
               export GCC_OBJC_LEGACY_DISPATCH=YES
               export GCC_OPTIMIZATION_LEVEL=0
               export GCC_PFE_FILE_C_DIALECTS="c objective-c c++ objective-c++"
               export GCC_PREPROCESSOR_DEFINITIONS="DEBUG=1  COCOAPODS=1 COCOAPODS=1"
               export GCC_SYMBOLS_PRIVATE_EXTERN=NO
               export GCC_TREAT_WARNINGS_AS_ERRORS=NO
               export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
               export GCC_VERSION_IDENTIFIER=com_apple_compilers_llvm_clang_1_0
               export GCC_WARN_64_TO_32_BIT_CONVERSION=YES
               export GCC_WARN_ABOUT_RETURN_TYPE=YES_ERROR
               export GCC_WARN_UNDECLARED_SELECTOR=YES
               export GCC_WARN_UNINITIALIZED_AUTOS=YES_AGGRESSIVE
               export GCC_WARN_UNUSED_FUNCTION=YES
               export GCC_WARN_UNUSED_VARIABLE=YES
               export GENERATE_MASTER_OBJECT_FILE=NO
               export GENERATE_PKGINFO_FILE=YES
               export GENERATE_PROFILING_CODE=NO
               export GENERATE_TEXT_BASED_STUBS=NO
               export GID=20
               export GROUP=staff
               export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
               export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
               export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
               export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
               export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
               export HEADERMAP_USES_VFS=NO
               export HEADER_SEARCH_PATHS="/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/include "
               export HIDE_BITCODE_SYMBOLS=YES
               export HOME=/Users/caleb.fung
               export ICONV=/usr/bin/iconv
               export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
               export INFOPLIST_FILE=Runner/Info.plist
               export INFOPLIST_OUTPUT_FORMAT=binary
               export INFOPLIST_PATH=Runner.app/Info.plist
               export INFOPLIST_PREPROCESS=NO
               export INFOSTRINGS_PATH=Runner.app/en.lproj/InfoPlist.strings
               export INLINE_PRIVATE_FRAMEWORKS=NO
               export INSTALLHDRS_COPY_PHASE=NO
               export INSTALLHDRS_SCRIPT_PHASE=NO
               export INSTALL_DIR=/tmp/Runner.dst/Applications
               export INSTALL_GROUP=staff
               export INSTALL_MODE_FLAG=u+w,go-w,a+rX
               export INSTALL_OWNER=caleb.fung
               export INSTALL_PATH=/Applications
               export INSTALL_ROOT=/tmp/Runner.dst
               export IPHONEOS_DEPLOYMENT_TARGET=12.4
               export JAVAC_DEFAULT_FLAGS="-J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8"
               export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               export JAVA_ARCHIVE_CLASSES=YES
               export JAVA_ARCHIVE_TYPE=JAR
               export JAVA_COMPILER=/usr/bin/javac
               export JAVA_FOLDER_PATH=Runner.app/Java
               export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
               export JAVA_JAR_FLAGS=cv
               export JAVA_SOURCE_SUBDIR=.
               export JAVA_USE_DEPENDENCIES=YES
               export JAVA_ZIP_FLAGS=-urg
               export JIKES_DEFAULT_FLAGS="+E +OLDCSO"
               export KEEP_PRIVATE_EXTERNS=NO
               export LD_DEPENDENCY_INFO_FILE=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/undefined_arch/Runner_dependency_info.dat
               export LD_ENTITLEMENTS_SECTION=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent
               export LD_GENERATE_MAP_FILE=NO
               export LD_MAP_FILE_PATH=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-LinkMap-normal-undefined_arch.txt
               export LD_NO_PIE=NO
               export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
               export LD_RUNPATH_SEARCH_PATHS=" '@executable_path/Frameworks' '@loader_path/Frameworks' '@executable_path/Frameworks' '@loader_path/Frameworks' @executable_path/Frameworks"
               export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               export LEX=lex
               export LIBRARY_FLAG_NOSPACE=YES
               export LIBRARY_FLAG_PREFIX=-l
               export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
               export LIBRARY_SEARCH_PATHS="/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator  /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter"
               export LINKER_DISPLAYS_MANGLED_NAMES=NO
               export LINK_FILE_LIST_normal_x86_64=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.LinkFileList
               export LINK_WITH_STANDARD_LIBRARIES=YES
               export LLVM_TARGET_TRIPLE_SUFFIX=-simulator
               export LOCALIZED_RESOURCES_FOLDER_PATH=Runner.app/en.lproj
               export LOCALIZED_STRING_MACRO_NAMES="NSLocalizedString CFLocalizedString"
               export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
               export LOCAL_APPS_DIR=/Applications
               export LOCAL_DEVELOPER_DIR=/Library/Developer
               export LOCAL_LIBRARY_DIR=/Library
               export LOCROOT=/Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export LOCSYMROOT=/Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export MACH_O_TYPE=mh_execute
               export MAC_OS_X_PRODUCT_BUILD_VERSION=18G87
               export MAC_OS_X_VERSION_ACTUAL=101406
               export MAC_OS_X_VERSION_MAJOR=101400
               export MAC_OS_X_VERSION_MINOR=1406
               export METAL_LIBRARY_FILE_BASE=default
               export METAL_LIBRARY_OUTPUT_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app
               export MODULE_CACHE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               export MTL_ENABLE_DEBUG_INFO=YES
               export NATIVE_ARCH=i386
               export NATIVE_ARCH_32_BIT=i386
               export NATIVE_ARCH_64_BIT=x86_64
               export NATIVE_ARCH_ACTUAL=x86_64
               export NO_COMMON=YES
               export OBJC_ABI_VERSION=2
               export OBJECT_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects
               export OBJECT_FILE_DIR_normal=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
               export OBJROOT=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex
               export ONLY_ACTIVE_ARCH=YES
               export OS=MACOS
               export OSAC=/usr/bin/osacompile
               export OTHER_LDFLAGS=" -ObjC -framework "Flutter" -ObjC -framework "Flutter""
               export PACKAGE_TYPE=com.apple.package-type.wrapper.application
               export PASCAL_STRINGS=YES
               export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Users/caleb.fung/Library/Android/sdk/emulator:/Users/caleb.fung/Library/Android/sdk/tools:/Users/caleb.fung/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/caleb.fung/flutter/bin"
               export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
               export PBDEVELOPMENTPLIST_PATH=Runner.app/pbdevelopment.plist
               export PER_ARCH_OBJECT_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/undefined_arch
               export PER_VARIANT_OBJECT_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
               export PKGINFO_FILE_PATH=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PkgInfo
               export PKGINFO_PATH=Runner.app/PkgInfo
               export PLATFORM_DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
               export PLATFORM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
               export PLATFORM_DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library
               export PLATFORM_DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
               export PLATFORM_DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
               export PLATFORM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
               export PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               export PLATFORM_DISPLAY_NAME="iOS Simulator"
               export PLATFORM_NAME=iphonesimulator
               export PLATFORM_PREFERRED_ARCH=x86_64
               export PLATFORM_PRODUCT_BUILD_VERSION=10G8
               export PLIST_FILE_OUTPUT_FORMAT=binary
               export PLUGINS_FOLDER_PATH=Runner.app/PlugIns
               export PODS_BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios
               export PODS_CONFIGURATION_BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               export PODS_PODFILE_DIR_PATH=/Users/caleb.fung/Documents/flutter_app_accelerator/ios/.
               export PODS_ROOT=/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Pods
               export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
               export PRECOMP_DESTINATION_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PrefixHeaders
               export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
               export PRIVATE_HEADERS_FOLDER_PATH=Runner.app/PrivateHeaders
               export PRODUCT_BUNDLE_IDENTIFIER=com.example.flutterAppAccelerator
               export PRODUCT_MODULE_NAME=Runner
               export PRODUCT_NAME=Runner
               export PRODUCT_SETTINGS_PATH=/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner/Info.plist
               export PRODUCT_TYPE=com.apple.product-type.application
               export PROFILING_CODE=NO
               export PROJECT=Runner
               export PROJECT_DERIVED_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/DerivedSources
               export PROJECT_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export PROJECT_FILE_PATH=/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner.xcodeproj
               export PROJECT_NAME=Runner
               export PROJECT_TEMP_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build
               export PROJECT_TEMP_ROOT=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex
               export PROVISIONING_PROFILE_SPECIFIER=Wildcard
               export PUBLIC_HEADERS_FOLDER_PATH=Runner.app/Headers
               export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS=YES
               export REMOVE_CVS_FROM_RESOURCES=YES
               export REMOVE_GIT_FROM_RESOURCES=YES
               export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
               export REMOVE_HG_FROM_RESOURCES=YES
               export REMOVE_SVN_FROM_RESOURCES=YES
               export REZ_COLLECTOR_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources
               export REZ_OBJECTS_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources/Objects
               export REZ_SEARCH_PATHS="/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator "
               export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
               export SCRIPTS_FOLDER_PATH=Runner.app/Scripts
               export SCRIPT_INPUT_FILE_COUNT=0
               export SCRIPT_INPUT_FILE_LIST_COUNT=0
               export SCRIPT_OUTPUT_FILE_COUNT=0
               export SCRIPT_OUTPUT_FILE_LIST_COUNT=0
               export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk
               export SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk
               export SDK_DIR_iphonesimulator12_4=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk
               export SDK_NAME=iphonesimulator12.4
               export SDK_NAMES=iphonesimulator12.4
               export SDK_PRODUCT_BUILD_VERSION=16G73
               export SDK_VERSION=12.4
               export SDK_VERSION_ACTUAL=120400
               export SDK_VERSION_MAJOR=120000
               export SDK_VERSION_MINOR=400
               export SED=/usr/bin/sed
               export SEPARATE_STRIP=NO
               export SEPARATE_SYMBOL_EDIT=NO
               export SET_DIR_MODE_OWNER_GROUP=YES
               export SET_FILE_MODE_OWNER_GROUP=NO
               export SHALLOW_BUNDLE=YES
               export SHARED_DERIVED_FILE_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/DerivedSources
               export SHARED_FRAMEWORKS_FOLDER_PATH=Runner.app/SharedFrameworks
               export SHARED_PRECOMPS_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/PrecompiledHeaders
               export SHARED_SUPPORT_FOLDER_PATH=Runner.app/SharedSupport
               export SKIP_INSTALL=NO
               export SOURCE_ROOT=/Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export SRCROOT=/Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export STRINGS_FILE_OUTPUT_ENCODING=binary
               export STRIP_BITCODE_FROM_COPIED_FILES=NO
               export STRIP_INSTALLED_PRODUCT=YES
               export STRIP_STYLE=all
               export STRIP_SWIFT_SYMBOLS=YES
               export SUPPORTED_DEVICE_FAMILIES=1,2
               export SUPPORTED_PLATFORMS="iphoneos iphonesimulator"
               export SUPPORTS_TEXT_BASED_API=NO
               export SWIFT_PLATFORM_TARGET_PREFIX=ios
               export SYMROOT=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Products
               export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
               export SYSTEM_APPS_DIR=/Applications
               export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
               export SYSTEM_DEMOS_DIR=/Applications/Extras
               export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
               export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
               export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
               export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
               export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
               export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
               export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
               export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
               export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
               export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
               export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
               export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
               export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
               export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
               export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
               export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
               export SYSTEM_LIBRARY_DIR=/System/Library
               export TAPI_VERIFY_MODE=ErrorsOnly
               export TARGETED_DEVICE_FAMILY=1,2
               export TARGETNAME=Runner
               export TARGET_BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               export TARGET_DEVICE_IDENTIFIER=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder
               export TARGET_NAME=Runner
               export TARGET_TEMP_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_FILES_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_FILE_DIR=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               export TEMP_ROOT=/Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex
               export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
               export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
               export TeamIdentifierPrefix=9Y3L2AFH84.
               export UID=501
               export UNLOCALIZED_RESOURCES_FOLDER_PATH=Runner.app
               export UNSTRIPPED_PRODUCT=NO
               export USER=caleb.fung
               export USER_APPS_DIR=/Users/caleb.fung/Applications
               export USER_LIBRARY_DIR=/Users/caleb.fung/Library
               export USE_DYNAMIC_NO_PIC=YES
               export USE_HEADERMAP=YES
               export USE_HEADER_SYMLINKS=NO
               export VALIDATE_PRODUCT=NO
               export VALID_ARCHS="i386 x86_64"
               export VERBOSE_PBXCP=NO
               export VERBOSE_SCRIPT_LOGGING=YES
               export VERSIONING_SYSTEM=apple-generic
               export VERSIONPLIST_PATH=Runner.app/version.plist
               export VERSION_INFO_BUILDER=caleb.fung
               export VERSION_INFO_FILE=Runner_vers.c
               export VERSION_INFO_STRING=""@(#)PROGRAM:Runner  PROJECT:Runner-1""
               export WRAPPER_EXTENSION=app
               export WRAPPER_NAME=Runner.app
               export WRAPPER_SUFFIX=.app
               export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
               export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
               export XCODE_PRODUCT_BUILD_VERSION=10G8
               export XCODE_VERSION_ACTUAL=1030
               export XCODE_VERSION_MAJOR=1000
               export XCODE_VERSION_MINOR=1030
               export XPCSERVICES_FOLDER_PATH=Runner.app/XPCServices
               export YACC=yacc
               export arch=undefined_arch
               export variant=normal
               /bin/sh -c /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh

           PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-A1D212E31E5F8A69222C40D7.sh (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               /bin/sh -c /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-A1D212E31E5F8A69222C40D7.sh
           mkdir -p /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks
           rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Pods/../.symlinks/flutter/ios/Flutter.framework" "/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks"
           building file list ... 
           done
           deleting Flutter.framework/_CodeSignature/CodeResources
           deleting Flutter.framework/_CodeSignature/
           Flutter.framework/
           Flutter.framework/Flutter
           Flutter.framework/Info.plist
           Flutter.framework/icudtl.dat

           sent 90790203 bytes  received 92 bytes  60526863.33 bytes/sec
           total size is 90778817  speedup is 1.00
           Stripped /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework/Flutter of architectures: armv7 arm64
           Code Signing /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework with Identity -
           /usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements '/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework'

           CodeSign /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app (in target: Runner)
               cd /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate

           Signing Identity:     "-"

               /usr/bin/codesign --force --sign - --timestamp=none /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app

           ** BUILD SUCCEEDED **
[  +18 ms] Running Xcode build... (completed in 4,458ms, longer than expected)
[   +1 ms] Xcode build done.                                            4.5s
[        ] executing: [/Users/caleb.fung/Documents/flutter_app_accelerator/ios/] /usr/bin/env xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios -sdk iphonesimulator -arch x86_64 FLUTTER_SUPPRESS_ANALYTICS=true -showBuildSettings
[+1038 ms] Exit code 0 from: /usr/bin/env xcrun xcodebuild -configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/caleb.fung/Documents/flutter_app_accelerator/build/ios -sdk iphonesimulator -arch x86_64 FLUTTER_SUPPRESS_ANALYTICS=true -showBuildSettings
[        ] Build settings from command line:
               ARCHS = x86_64
               BUILD_DIR = /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios
               FLUTTER_SUPPRESS_ANALYTICS = true
               SDKROOT = iphonesimulator12.4
               VERBOSE_SCRIPT_LOGGING = YES

           Build settings for action build and target Runner:
               ACTION = build
               AD_HOC_CODE_SIGNING_ALLOWED = YES
               ALTERNATE_GROUP = staff
               ALTERNATE_MODE = u+w,go-w,a+rX
               ALTERNATE_OWNER = caleb.fung
               ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO
               ALWAYS_SEARCH_USER_PATHS = NO
               ALWAYS_USE_SEPARATE_HEADERMAPS = NO
               APPLE_INTERNAL_DEVELOPER_DIR = /AppleInternal/Developer
               APPLE_INTERNAL_DIR = /AppleInternal
               APPLE_INTERNAL_DOCUMENTATION_DIR = /AppleInternal/Documentation
               APPLE_INTERNAL_LIBRARY_DIR = /AppleInternal/Library
               APPLE_INTERNAL_TOOLS = /AppleInternal/Developer/Tools
               APPLICATION_EXTENSION_API_ONLY = NO
               APPLY_RULES_IN_COPY_FILES = NO
               ARCHS = x86_64
               ARCHS_STANDARD = x86_64
               ARCHS_STANDARD_32_64_BIT = i386 x86_64
               ARCHS_STANDARD_32_BIT = i386
               ARCHS_STANDARD_64_BIT = x86_64
               ARCHS_STANDARD_INCLUDING_64_BIT = x86_64
               ARCHS_UNIVERSAL_IPHONE_OS = i386 x86_64
               ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
               AVAILABLE_PLATFORMS = appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator
               BITCODE_GENERATION_MODE = marker
               BUILD_ACTIVE_RESOURCES_ONLY = NO
               BUILD_COMPONENTS = headers build
               BUILD_DIR = /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios
               BUILD_ROOT = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Products
               BUILD_STYLE = 
               BUILD_VARIANTS = normal
               BUILT_PRODUCTS_DIR = /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               CACHE_ROOT = /var/folders/y1/hbx4v2s16rd2qb95g2thpms80000gn/C/com.apple.DeveloperTools/10.3-10G8/Xcode
               CCHROOT = /var/folders/y1/hbx4v2s16rd2qb95g2thpms80000gn/C/com.apple.DeveloperTools/10.3-10G8/Xcode
               CHMOD = /bin/chmod
               CHOWN = /usr/sbin/chown
               CLANG_ANALYZER_NONNULL = YES
               CLANG_CXX_LANGUAGE_STANDARD = gnu++0x
               CLANG_CXX_LIBRARY = libc++
               CLANG_ENABLE_MODULES = YES
               CLANG_ENABLE_OBJC_ARC = YES
               CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES
               CLANG_WARN_BOOL_CONVERSION = YES
               CLANG_WARN_COMMA = YES
               CLANG_WARN_CONSTANT_CONVERSION = YES
               CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES
               CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR
               CLANG_WARN_EMPTY_BODY = YES
               CLANG_WARN_ENUM_CONVERSION = YES
               CLANG_WARN_INFINITE_RECURSION = YES
               CLANG_WARN_INT_CONVERSION = YES
               CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES
               CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES
               CLANG_WARN_OBJC_LITERAL_CONVERSION = YES
               CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR
               CLANG_WARN_RANGE_LOOP_ANALYSIS = YES
               CLANG_WARN_STRICT_PROTOTYPES = YES
               CLANG_WARN_SUSPICIOUS_MOVE = YES
               CLANG_WARN_UNREACHABLE_CODE = YES
               CLANG_WARN__DUPLICATE_METHOD_MATCH = YES
               CLASS_FILE_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/JavaClasses
               CLEAN_PRECOMPS = YES
               CLONE_HEADERS = NO
               CODESIGNING_FOLDER_PATH = /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app
               CODE_SIGNING_ALLOWED = YES
               CODE_SIGNING_REQUIRED = YES
               CODE_SIGN_CONTEXT_CLASS = XCiPhoneSimulatorCodeSignContext
               CODE_SIGN_IDENTITY = -
               CODE_SIGN_INJECT_BASE_ENTITLEMENTS = YES
               CODE_SIGN_STYLE = Manual
               COLOR_DIAGNOSTICS = NO
               COMBINE_HIDPI_IMAGES = NO
               COMPILER_INDEX_STORE_ENABLE = Default
               COMPOSITE_SDK_DIRS = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/CompositeSDKs
               COMPRESS_PNG_FILES = YES
               CONFIGURATION = Debug
               CONFIGURATION_BUILD_DIR = /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               CONFIGURATION_TEMP_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator
               CONTENTS_FOLDER_PATH = Runner.app
               COPYING_PRESERVES_HFS_DATA = NO
               COPY_HEADERS_RUN_UNIFDEF = NO
               COPY_PHASE_STRIP = NO
               COPY_RESOURCES_FROM_STATIC_FRAMEWORKS = YES
               CORRESPONDING_DEVICE_PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
               CORRESPONDING_DEVICE_PLATFORM_NAME = iphoneos
               CORRESPONDING_DEVICE_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk
               CORRESPONDING_DEVICE_SDK_NAME = iphoneos12.4
               CP = /bin/cp
               CREATE_INFOPLIST_SECTION_IN_BINARY = NO
               CURRENT_ARCH = x86_64
               CURRENT_PROJECT_VERSION = 1
               CURRENT_VARIANT = normal
               DEAD_CODE_STRIPPING = YES
               DEBUGGING_SYMBOLS = YES
               DEBUG_INFORMATION_FORMAT = dwarf
               DEFAULT_COMPILER = com.apple.compilers.llvm.clang.1_0
               DEFAULT_KEXT_INSTALL_PATH = /System/Library/Extensions
               DEFINES_MODULE = NO
               DEPLOYMENT_LOCATION = NO
               DEPLOYMENT_POSTPROCESSING = NO
               DEPLOYMENT_TARGET_CLANG_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_CLANG_FLAG_NAME = mios-simulator-version-min
               DEPLOYMENT_TARGET_CLANG_FLAG_PREFIX = -mios-simulator-version-min=
               DEPLOYMENT_TARGET_LD_ENV_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_LD_FLAG_NAME = ios_simulator_version_min
               DEPLOYMENT_TARGET_SETTING_NAME = IPHONEOS_DEPLOYMENT_TARGET
               DEPLOYMENT_TARGET_SUGGESTED_VALUES = 8.0 8.1 8.2 8.3 8.4 9.0 9.1 9.2 9.3 10.0 10.1 10.2 10.3 11.0 11.1 11.2 11.3 11.4 12.0 12.1 12.2 12.3 12.4
               DERIVED_FILES_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               DERIVED_FILE_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               DERIVED_SOURCES_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources
               DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               DEVELOPER_FRAMEWORKS_DIR = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_FRAMEWORKS_DIR_QUOTED = /Applications/Xcode.app/Contents/Developer/Library/Frameworks
               DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/Developer/Library
               DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
               DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Tools
               DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               DEVELOPMENT_LANGUAGE = en
               DEVELOPMENT_TEAM = 9Y3L2AFH84
               DOCUMENTATION_FOLDER_PATH = Runner.app/en.lproj/Documentation
               DO_HEADER_SCANNING_IN_JAM = NO
               DSTROOT = /tmp/Runner.dst
               DT_TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               DWARF_DSYM_FILE_NAME = Runner.app.dSYM
               DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT = NO
               DWARF_DSYM_FOLDER_PATH = /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               EFFECTIVE_PLATFORM_NAME = -iphonesimulator
               EMBEDDED_CONTENT_CONTAINS_SWIFT = NO
               EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE = NO
               ENABLE_BITCODE = NO
               ENABLE_DEFAULT_HEADER_SEARCH_PATHS = YES
               ENABLE_HEADER_DEPENDENCIES = YES
               ENABLE_ON_DEMAND_RESOURCES = YES
               ENABLE_STRICT_OBJC_MSGSEND = YES
               ENABLE_TESTABILITY = YES
               ENTITLEMENTS_DESTINATION = __entitlements
               ENTITLEMENTS_REQUIRED = YES
               EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS = .DS_Store .svn .git .hg CVS
               EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES = *.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj
               EXECUTABLES_FOLDER_PATH = Runner.app/Executables
               EXECUTABLE_FOLDER_PATH = Runner.app
               EXECUTABLE_NAME = Runner
               EXECUTABLE_PATH = Runner.app/Runner
               EXPANDED_CODE_SIGN_IDENTITY = 
               EXPANDED_CODE_SIGN_IDENTITY_NAME = 
               EXPANDED_PROVISIONING_PROFILE = 
               FILE_LIST = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects/LinkFileList
               FIXED_FILES_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/FixedFiles
               FLUTTER_APPLICATION_PATH = /Users/caleb.fung/Documents/flutter_app_accelerator
               FLUTTER_BUILD_DIR = build
               FLUTTER_BUILD_NAME = 1.0.0
               FLUTTER_BUILD_NUMBER = 1
               FLUTTER_FRAMEWORK_DIR = /Users/caleb.fung/flutter/bin/cache/artifacts/engine/ios
               FLUTTER_ROOT = /Users/caleb.fung/flutter
               FLUTTER_SUPPRESS_ANALYTICS = true
               FLUTTER_TARGET = /Users/caleb.fung/Documents/flutter_app_accelerator/lib/main.dart
               FRAMEWORKS_FOLDER_PATH = Runner.app/Frameworks
               FRAMEWORK_FLAG_PREFIX = -framework
               FRAMEWORK_SEARCH_PATHS =  "/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Pods/../.symlinks/flutter/ios" "/Users/caleb.fung/Documents/flutter_app_accelerator/ios/Pods/../.symlinks/flutter/ios" /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter
               FRAMEWORK_VERSION = A
               FULL_PRODUCT_NAME = Runner.app
               GCC3_VERSION = 3.3
               GCC_C_LANGUAGE_STANDARD = gnu99
               GCC_DYNAMIC_NO_PIC = NO
               GCC_INLINES_ARE_PRIVATE_EXTERN = YES
               GCC_NO_COMMON_BLOCKS = YES
               GCC_OBJC_LEGACY_DISPATCH = YES
               GCC_OPTIMIZATION_LEVEL = 0
               GCC_PFE_FILE_C_DIALECTS = c objective-c c++ objective-c++
               GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1  COCOAPODS=1 COCOAPODS=1
               GCC_SYMBOLS_PRIVATE_EXTERN = NO
               GCC_TREAT_WARNINGS_AS_ERRORS = NO
               GCC_VERSION = com.apple.compilers.llvm.clang.1_0
               GCC_VERSION_IDENTIFIER = com_apple_compilers_llvm_clang_1_0
               GCC_WARN_64_TO_32_BIT_CONVERSION = YES
               GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR
               GCC_WARN_UNDECLARED_SELECTOR = YES
               GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE
               GCC_WARN_UNUSED_FUNCTION = YES
               GCC_WARN_UNUSED_VARIABLE = YES
               GENERATE_MASTER_OBJECT_FILE = NO
               GENERATE_PKGINFO_FILE = YES
               GENERATE_PROFILING_CODE = NO
               GENERATE_TEXT_BASED_STUBS = NO
               GID = 20
               GROUP = staff
               HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT = YES
               HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES = YES
               HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS = YES
               HEADERMAP_INCLUDES_PROJECT_HEADERS = YES
               HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES = YES
               HEADERMAP_USES_VFS = NO
               HIDE_BITCODE_SYMBOLS = YES
               HOME = /Users/caleb.fung
               ICONV = /usr/bin/iconv
               INFOPLIST_EXPAND_BUILD_SETTINGS = YES
               INFOPLIST_FILE = Runner/Info.plist
               INFOPLIST_OUTPUT_FORMAT = binary
               INFOPLIST_PATH = Runner.app/Info.plist
               INFOPLIST_PREPROCESS = NO
               INFOSTRINGS_PATH = Runner.app/en.lproj/InfoPlist.strings
               INLINE_PRIVATE_FRAMEWORKS = NO
               INSTALLHDRS_COPY_PHASE = NO
               INSTALLHDRS_SCRIPT_PHASE = NO
               INSTALL_DIR = /tmp/Runner.dst/Applications
               INSTALL_GROUP = staff
               INSTALL_MODE_FLAG = u+w,go-w,a+rX
               INSTALL_OWNER = caleb.fung
               INSTALL_PATH = /Applications
               INSTALL_ROOT = /tmp/Runner.dst
               IPHONEOS_DEPLOYMENT_TARGET = 12.4
               JAVAC_DEFAULT_FLAGS = -J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8
               JAVA_APP_STUB = /System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
               JAVA_ARCHIVE_CLASSES = YES
               JAVA_ARCHIVE_TYPE = JAR
               JAVA_COMPILER = /usr/bin/javac
               JAVA_FOLDER_PATH = Runner.app/Java
               JAVA_FRAMEWORK_RESOURCES_DIRS = Resources
               JAVA_JAR_FLAGS = cv
               JAVA_SOURCE_SUBDIR = .
               JAVA_USE_DEPENDENCIES = YES
               JAVA_ZIP_FLAGS = -urg
               JIKES_DEFAULT_FLAGS = +E +OLDCSO
               KEEP_PRIVATE_EXTERNS = NO
               LD_DEPENDENCY_INFO_FILE = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat
               LD_GENERATE_MAP_FILE = NO
               LD_MAP_FILE_PATH = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner-LinkMap-normal-x86_64.txt
               LD_NO_PIE = NO
               LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER = YES
               LD_RUNPATH_SEARCH_PATHS =  '@executable_path/Frameworks' '@loader_path/Frameworks' '@executable_path/Frameworks' '@loader_path/Frameworks' @executable_path/Frameworks
               LEGACY_DEVELOPER_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
               LEX = lex
               LIBRARY_FLAG_NOSPACE = YES
               LIBRARY_FLAG_PREFIX = -l
               LIBRARY_KEXT_INSTALL_PATH = /Library/Extensions
               LIBRARY_SEARCH_PATHS =  /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Flutter
               LINKER_DISPLAYS_MANGLED_NAMES = NO
               LINK_FILE_LIST_normal_x86_64 = 
               LINK_WITH_STANDARD_LIBRARIES = YES
               LLVM_TARGET_TRIPLE_SUFFIX = -simulator
               LOCALIZABLE_CONTENT_DIR = 
               LOCALIZED_RESOURCES_FOLDER_PATH = Runner.app/en.lproj
               LOCALIZED_STRING_MACRO_NAMES = NSLocalizedString CFLocalizedString
               LOCAL_ADMIN_APPS_DIR = /Applications/Utilities
               LOCAL_APPS_DIR = /Applications
               LOCAL_DEVELOPER_DIR = /Library/Developer
               LOCAL_LIBRARY_DIR = /Library
               LOCROOT = 
               LOCSYMROOT = 
               MACH_O_TYPE = mh_execute
               MAC_OS_X_PRODUCT_BUILD_VERSION = 18G87
               MAC_OS_X_VERSION_ACTUAL = 101406
               MAC_OS_X_VERSION_MAJOR = 101400
               MAC_OS_X_VERSION_MINOR = 1406
               METAL_LIBRARY_FILE_BASE = default
               METAL_LIBRARY_OUTPUT_DIR = /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/Runner.app
               MODULE_CACHE_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
               MTL_ENABLE_DEBUG_INFO = YES
               NATIVE_ARCH = i386
               NATIVE_ARCH_32_BIT = i386
               NATIVE_ARCH_64_BIT = x86_64
               NATIVE_ARCH_ACTUAL = x86_64
               NO_COMMON = YES
               OBJC_ABI_VERSION = 2
               OBJECT_FILE_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects
               OBJECT_FILE_DIR_normal = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal
               OBJROOT = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex
               ONLY_ACTIVE_ARCH = YES
               OS = MACOS
               OSAC = /usr/bin/osacompile
               OTHER_LDFLAGS =  -ObjC -framework "Flutter" -ObjC -framework "Flutter"
               PACKAGE_TYPE = com.apple.package-type.wrapper.application
               PASCAL_STRINGS = YES
               PATH = /Applications/Xcode.app/Contents/Developer/usr/bin:/Users/caleb.fung/Library/Android/sdk/emulator:/Users/caleb.fung/Library/Android/sdk/tools:/Users/caleb.fung/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/caleb.fung/Library/Android/sdk/emulator:/Users/caleb.fung/Library/Android/sdk/tools:/Users/caleb.fung/.npm-global/bin:/Users/caleb.fung/flutter/bin:/Users/caleb.fung/flutter/bin
               PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES = /usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms
               PBDEVELOPMENTPLIST_PATH = Runner.app/pbdevelopment.plist
               PFE_FILE_C_DIALECTS = objective-c
               PKGINFO_FILE_PATH = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PkgInfo
               PKGINFO_PATH = Runner.app/PkgInfo
               PLATFORM_DEVELOPER_APPLICATIONS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications
               PLATFORM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin
               PLATFORM_DEVELOPER_LIBRARY_DIR = /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library
               PLATFORM_DEVELOPER_SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs
               PLATFORM_DEVELOPER_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Tools
               PLATFORM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr
               PLATFORM_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
               PLATFORM_DISPLAY_NAME = iOS Simulator
               PLATFORM_NAME = iphonesimulator
               PLATFORM_PREFERRED_ARCH = x86_64
               PLIST_FILE_OUTPUT_FORMAT = binary
               PLUGINS_FOLDER_PATH = Runner.app/PlugIns
               PODS_BUILD_DIR = /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios
               PODS_CONFIGURATION_BUILD_DIR = /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               PODS_PODFILE_DIR_PATH = /Users/caleb.fung/Documents/flutter_app_accelerator/ios/.
               PODS_ROOT = /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Pods
               PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR = YES
               PRECOMP_DESTINATION_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/PrefixHeaders
               PRESERVE_DEAD_CODE_INITS_AND_TERMS = NO
               PRIVATE_HEADERS_FOLDER_PATH = Runner.app/PrivateHeaders
               PRODUCT_BUNDLE_IDENTIFIER = com.example.flutterAppAccelerator
               PRODUCT_MODULE_NAME = Runner
               PRODUCT_NAME = Runner
               PRODUCT_SETTINGS_PATH = /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner/Info.plist
               PRODUCT_TYPE = com.apple.product-type.application
               PROFILING_CODE = NO
               PROJECT = Runner
               PROJECT_DERIVED_FILE_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/DerivedSources
               PROJECT_DIR = /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               PROJECT_FILE_PATH = /Users/caleb.fung/Documents/flutter_app_accelerator/ios/Runner.xcodeproj
               PROJECT_NAME = Runner
               PROJECT_TEMP_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build
               PROJECT_TEMP_ROOT = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex
               PROVISIONING_PROFILE_SPECIFIER = Wildcard
               PUBLIC_HEADERS_FOLDER_PATH = Runner.app/Headers
               RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS = YES
               REMOVE_CVS_FROM_RESOURCES = YES
               REMOVE_GIT_FROM_RESOURCES = YES
               REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES = YES
               REMOVE_HG_FROM_RESOURCES = YES
               REMOVE_SVN_FROM_RESOURCES = YES
               REZ_COLLECTOR_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources
               REZ_OBJECTS_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/ResourceManagerResources/Objects
               SCAN_ALL_SOURCE_FILES_FOR_INCLUDES = NO
               SCRIPTS_FOLDER_PATH = Runner.app/Scripts
               SDKROOT = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk
               SDK_DIR = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk
               SDK_DIR_iphonesimulator12_4 = /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.4.sdk
               SDK_NAME = iphonesimulator12.4
               SDK_NAMES = iphonesimulator12.4
               SDK_PRODUCT_BUILD_VERSION = 16G73
               SDK_VERSION = 12.4
               SDK_VERSION_ACTUAL = 120400
               SDK_VERSION_MAJOR = 120000
               SDK_VERSION_MINOR = 400
               SED = /usr/bin/sed
               SEPARATE_STRIP = NO
               SEPARATE_SYMBOL_EDIT = NO
               SET_DIR_MODE_OWNER_GROUP = YES
               SET_FILE_MODE_OWNER_GROUP = NO
               SHALLOW_BUNDLE = YES
               SHARED_DERIVED_FILE_DIR = /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator/DerivedSources
               SHARED_FRAMEWORKS_FOLDER_PATH = Runner.app/SharedFrameworks
               SHARED_PRECOMPS_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/PrecompiledHeaders
               SHARED_SUPPORT_FOLDER_PATH = Runner.app/SharedSupport
               SKIP_INSTALL = NO
               SOURCE_ROOT = /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               SRCROOT = /Users/caleb.fung/Documents/flutter_app_accelerator/ios
               STRINGS_FILE_OUTPUT_ENCODING = binary
               STRIP_BITCODE_FROM_COPIED_FILES = NO
               STRIP_INSTALLED_PRODUCT = YES
               STRIP_STYLE = all
               STRIP_SWIFT_SYMBOLS = YES
               SUPPORTED_DEVICE_FAMILIES = 1,2
               SUPPORTED_PLATFORMS = iphonesimulator iphoneos
               SUPPORTS_TEXT_BASED_API = NO
               SWIFT_PLATFORM_TARGET_PREFIX = ios
               SYMROOT = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Products
               SYSTEM_ADMIN_APPS_DIR = /Applications/Utilities
               SYSTEM_APPS_DIR = /Applications
               SYSTEM_CORE_SERVICES_DIR = /System/Library/CoreServices
               SYSTEM_DEMOS_DIR = /Applications/Extras
               SYSTEM_DEVELOPER_APPS_DIR = /Applications/Xcode.app/Contents/Developer/Applications
               SYSTEM_DEVELOPER_BIN_DIR = /Applications/Xcode.app/Contents/Developer/usr/bin
               SYSTEM_DEVELOPER_DEMOS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples
               SYSTEM_DEVELOPER_DIR = /Applications/Xcode.app/Contents/Developer
               SYSTEM_DEVELOPER_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library
               SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools
               SYSTEM_DEVELOPER_JAVA_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Java Tools
               SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Performance Tools
               SYSTEM_DEVELOPER_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes
               SYSTEM_DEVELOPER_TOOLS = /Applications/Xcode.app/Contents/Developer/Tools
               SYSTEM_DEVELOPER_TOOLS_DOC_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools
               SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR = /Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools
               SYSTEM_DEVELOPER_USR_DIR = /Applications/Xcode.app/Contents/Developer/usr
               SYSTEM_DEVELOPER_UTILITIES_DIR = /Applications/Xcode.app/Contents/Developer/Applications/Utilities
               SYSTEM_DOCUMENTATION_DIR = /Library/Documentation
               SYSTEM_KEXT_INSTALL_PATH = /System/Library/Extensions
               SYSTEM_LIBRARY_DIR = /System/Library
               TAPI_VERIFY_MODE = ErrorsOnly
               TARGETED_DEVICE_FAMILY = 1,2
               TARGETNAME = Runner
               TARGET_BUILD_DIR = /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/Debug-iphonesimulator
               TARGET_NAME = Runner
               TARGET_TEMP_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               TEMP_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               TEMP_FILES_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               TEMP_FILE_DIR = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build
               TEMP_ROOT = /Users/caleb.fung/Library/Developer/Xcode/DerivedData/Runner-fimioyuyxxrvnwarhluevwmnofmn/Build/Intermediates.noindex
               TOOLCHAIN_DIR = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
               TREAT_MISSING_BASELINES_AS_TEST_FAILURES = NO
               UID = 501
               UNLOCALIZED_RESOURCES_FOLDER_PATH = Runner.app
               UNSTRIPPED_PRODUCT = NO
               USER = caleb.fung
               USER_APPS_DIR = /Users/caleb.fung/Applications
               USER_LIBRARY_DIR = /Users/caleb.fung/Library
               USE_DYNAMIC_NO_PIC = YES
               USE_HEADERMAP = YES
               USE_HEADER_SYMLINKS = NO
               VALIDATE_PRODUCT = NO
               VALID_ARCHS = i386 x86_64
               VERBOSE_PBXCP = NO
               VERBOSE_SCRIPT_LOGGING = YES
               VERSIONING_SYSTEM = apple-generic
               VERSIONPLIST_PATH = Runner.app/version.plist
               VERSION_INFO_BUILDER = caleb.fung
               VERSION_INFO_FILE = Runner_vers.c
               VERSION_INFO_STRING = "@(#)PROGRAM:Runner  PROJECT:Runner-1"
               WRAPPER_EXTENSION = app
               WRAPPER_NAME = Runner.app
               WRAPPER_SUFFIX = .app
               WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES = NO
               XCODE_APP_SUPPORT_DIR = /Applications/Xcode.app/Contents/Developer/Library/Xcode
               XCODE_PRODUCT_BUILD_VERSION = 10G8
               XCODE_VERSION_ACTUAL = 1030
               XCODE_VERSION_MAJOR = 1000
               XCODE_VERSION_MINOR = 1030
               XPCSERVICES_FOLDER_PATH = Runner.app/XPCServices
               YACC = yacc
               arch = x86_64
               variant = normal
[ +134 ms] executing: /usr/bin/xcrun simctl install 6D90B229-9D1B-4238-88C0-BE32AF457121 /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/iphonesimulator/Runner.app
[ +445 ms] executing: /usr/bin/defaults read /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/iphonesimulator/Runner.app/Info CFBundleIdentifier
[  +68 ms] Exit code 0 from: /usr/bin/defaults read /Users/caleb.fung/Documents/flutter_app_accelerator/build/ios/iphonesimulator/Runner.app/Info CFBundleIdentifier
[        ] com.example.flutterAppAccelerator
[        ] executing: /usr/bin/xcrun simctl launch 6D90B229-9D1B-4238-88C0-BE32AF457121 com.example.flutterAppAccelerator --enable-dart-profiling --enable-checked-mode --verify-entry-points --observatory-port=0
[+1407 ms] com.example.flutterAppAccelerator: 13060
[        ] Waiting for observatory port to be available...
[ +319 ms] [DEVICE LOG] Timestamp                       (process)[PID]    
[        ] [DEVICE LOG] 2019-08-11 08:31:51.103939-0500  localhost Runner[13060]: (libMobileGestalt.dylib) libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.
[        ] [DEVICE LOG] 2019-08-11 08:31:51.104002-0500  localhost Runner[13060]: (libMobileGestalt.dylib) MGIsDeviceOneOfType is not supported on this platform.
[        ] [DEVICE LOG] 2019-08-11 08:31:51.105553-0500  localhost Runner[13060]: (libAccessibility.dylib) [com.apple.Accessibility:AccessibilitySupport] Retrieving resting unlock: 0
[ +157 ms] [DEVICE LOG] 2019-08-11 08:31:51.262652-0500  localhost Runner[13060]: (Flutter) flutter: Observatory listening on http://127.0.0.1:59224/tl1QKkUqszE=/
[   +3 ms] Observatory URL on device: http://127.0.0.1:59224/tl1QKkUqszE=/
[   +4 ms] Connecting to service protocol: http://127.0.0.1:59224/tl1QKkUqszE=/
[ +150 ms] Successfully connected to service protocol: http://127.0.0.1:59224/tl1QKkUqszE=/
[   +2 ms] Sending to VM service: getVM({})
[   +3 ms] Result: {type: VM, name: vm, architectureBits: 64, targetCPU: x64, hostCPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz, version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "ios_x64", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 13060, startTime: 156553...
[   +3 ms] Sending to VM service: getIsolate({isolateId: isolates/639445046})
[   +4 ms] Sending to VM service: _flutter.listViews({})
[   +1 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7fd6de80ca20, isolate: {type: @Isolate, fixedId: true, id: isolates/639445046, name: main.dart$main-639445046, number: 639445046}}]}
[   +5 ms] DevFS: Creating new filesystem on the device (null)
[        ] Sending to VM service: _createDevFS({fsName: flutter_app_accelerator})
[  +12 ms] Result: {type: Isolate, id: isolates/639445046, name: main, number: 639445046, _originNumber: 639445046, startTime: 1565530311167, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis: 0.0, used: 524288, ...
[   +9 ms] Result: {type: FileSystem, name: flutter_app_accelerator, uri: file:///Users/caleb.fung/Library/Developer/CoreSimulator/Devices/6D90B229-9D1B-4238-88C0-BE32AF457121/data/Containers/Data/Application/65BCE31A-0203-4549-8174-850B2525EFB5/tmp/flutter_app_acce...
[        ] DevFS: Created new filesystem on the device (file:///Users/caleb.fung/Library/Developer/CoreSimulator/Devices/6D90B229-9D1B-4238-88C0-BE32AF457121/data/Containers/Data/Application/65BCE31A-0203-4549-8174-850B2525EFB5/tmp/flutter_app_acceleratordluADJ/flutter_app_accelerator/)
[   +1 ms] Updating assets
[  +44 ms] Scanned through 0 files in 0ms
[   +1 ms] Syncing files to device iPhone 7...
[   +1 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +6 ms] /Users/caleb.fung/flutter/bin/cache/dart-sdk/bin/dart /Users/caleb.fung/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/caleb.fung/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build/app.dill --packages /Users/caleb.fung/Documents/flutter_app_accelerator/.packages --filesystem-scheme org-dartlang-root
[   +4 ms] <- compile package:flutter_app_accelerator/main.dart
[ +102 ms] -> result 257eb06d-caff-4920-92f1-0c008b84497b
[ +765 ms] -> 257eb06d-caff-4920-92f1-0c008b84497b
[        ] -> +file:///Users/caleb.fung/Documents/flutter_app_accelerator/lib/main.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/collection.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/algorithms.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/canonicalized_map.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/combined_wrappers/combined_iterable.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/combined_wrappers/combined_list.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/combined_wrappers/combined_map.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/comparators.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/empty_unmodifiable_set.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/wrappers.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/equality.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/equality_map.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/equality_set.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/functions.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/iterable_zip.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/priority_queue.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/queue_list.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/union_set.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/unmodifiable_wrappers.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/union_set_controller.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.14.11/lib/src/utils.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.1.6/lib/meta.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/typed_data-1.1.6/lib/typed_buffers.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/hash.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/vector_math_64.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/aabb2.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/aabb3.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/colors.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/frustum.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/intersection_result.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/matrix2.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/matrix3.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/matrix4.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/obb3.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/plane.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/quad.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/quaternion.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/ray.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/sphere.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/third_party/noise.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/triangle.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/vector.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/vector2.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/vector3.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/vector4.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/constants.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/error_helpers.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/opengl.dart
[        ] -> +file:///Users/caleb.fung/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/src/vector_math_64/utilities.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/animation.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/cupertino.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/foundation.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/gestures.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/painting.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/physics.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/rendering.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/scheduler.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/semantics.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/services.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/animation/animation.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/animation/animation_controller.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/animation/listener_helpers.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/animation/animations.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/animation/curves.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/animation/tween.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/animation/tween_sequence.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/action_sheet.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/object.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/box.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/activity_indicator.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/ticker_provider.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/app.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/bottom_tab_bar.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/button.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/colors.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/date_picker.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/dialog.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/icons.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/localizations.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/nav_bar.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/diagnostics.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/page_scaffold.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/picker.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/refresh.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/route.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/scrollbar.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/segmented_control.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/slider.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/switch.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/tab_scaffold.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/tab_view.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/text_field.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/automatic_keep_alive.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/text_selection.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/text_theme.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/theme.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/cupertino/thumb_painter.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/_bitfield_io.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/_isolates_io.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/_platform_io.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/annotations.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/assertions.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/basic_types.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/binding.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/bitfield.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/change_notifier.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/collections.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/consolidate_response.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/constants.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/debug.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/isolates.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/key.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/licenses.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/node.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/observer_list.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/platform.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/print.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/profile.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/serialization.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/synchronous_future.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/foundation/unicode.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/arena.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/binding.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/constants.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/converter.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/debug.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/drag.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/drag_details.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/eager.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/events.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/force_press.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/hit_test.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/long_press.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/lsq_solver.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/monodrag.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/mouse_tracking.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/multidrag.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/multitap.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/pointer_router.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/pointer_signal_resolver.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/recognizer.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/scale.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/tap.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/team.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/gestures/velocity_tracker.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/_network_image_io.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/alignment.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/basic_types.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/beveled_rectangle_border.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/binding.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/border_radius.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/borders.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/box_border.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/box_decoration.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/box_fit.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/box_shadow.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/circle_border.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/clip.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/colors.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/continuous_rectangle_border.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/debug.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/decoration.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/decoration_image.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/edge_insets.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/flutter_logo.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/fractional_offset.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/geometry.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/gradient.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/image_cache.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/image_decoder.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/image_provider.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/image_resolution.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/image_stream.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/inline_span.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/matrix_utils.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/notched_shapes.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/paint_utilities.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/placeholder_span.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/rounded_rectangle_border.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/shader_warm_up.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/shape_decoration.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/stadium_border.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/strut_style.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/text_painter.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/text_span.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/painting/text_style.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/physics/clamped_simulation.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/physics/friction_simulation.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/physics/gravity_simulation.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/physics/simulation.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/physics/spring_simulation.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/physics/tolerance.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/physics/utils.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/animated_size.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/binding.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/binding.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/scheduler/binding.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/semantics/binding.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/custom_layout.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/custom_paint.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/debug.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/debug_overflow_indicator.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/editable.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/error.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/flex.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/flow.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/image.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/layer.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/list_body.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/list_wheel_viewport.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/paragraph.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/performance_overlay.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/platform_view.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/proxy_box.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/rotated_box.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/shifted_box.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/sliver.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/sliver_fill.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/sliver_grid.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/sliver_list.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/sliver_padding.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/sliver_persistent_header.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/stack.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/table.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/table_border.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/texture.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/tweens.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/view.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/viewport.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/viewport_offset.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/rendering/wrap.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/scheduler/debug.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/scheduler/priority.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/scheduler/ticker.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/semantics/debug.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/semantics/semantics.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/semantics/semantics_event.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/semantics/semantics_service.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/asset_bundle.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/binary_messenger.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/clipboard.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/font_loader.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/haptic_feedback.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/keyboard_key.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/keyboard_maps.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/message_codec.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/message_codecs.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/platform_channel.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/platform_messages.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/platform_views.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/raw_keyboard.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/raw_keyboard_android.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/raw_keyboard_fuchsia.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/raw_keyboard_linux.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/raw_keyboard_macos.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/system_channels.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/system_chrome.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/system_navigator.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/system_sound.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/text_editing.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/text_formatter.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/services/text_input.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/actions.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/animated_cross_fade.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/animated_list.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/animated_size.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/animated_switcher.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/annotated_region.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/app.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/async.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/banner.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/basic.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/binding.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/bottom_navigation_bar_item.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/container.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/debug.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/dismissible.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/drag_target.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scroll_notification.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/editable_text.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/fade_in_image.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/focus_manager.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/focus_scope.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/focus_traversal.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/form.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/framework.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/gesture_detector.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/grid_paper.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/heroes.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/icon.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/icon_data.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/icon_theme.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/icon_theme_data.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/image.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/image_icon.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/implicit_animations.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/inherited_model.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/inherited_notifier.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/layout_builder.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/list_wheel_scroll_view.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/localizations.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/media_query.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/modal_barrier.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/navigation_toolbar.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/navigator.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/nested_scroll_view.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/notification_listener.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/orientation_builder.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/overlay.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/overscroll_indicator.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/page_storage.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/page_view.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/pages.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/performance_overlay.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/placeholder.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/platform_view.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/preferred_size.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/primary_scroll_controller.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/raw_keyboard_listener.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/routes.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/safe_area.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scroll_activity.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scroll_configuration.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scroll_context.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scroll_controller.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scroll_metrics.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scroll_physics.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scroll_position.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scroll_position_with_single_context.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scroll_simulation.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scroll_view.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scrollable.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/scrollbar.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/semantics_debugger.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/shortcuts.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/single_child_scroll_view.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/size_changed_layout_notifier.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/sliver.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/sliver_persistent_header.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/sliver_prototype_extent_list.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/spacer.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/status_transitions.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/table.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/text.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/text_selection.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/texture.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/title.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/transitions.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/unique_widget.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/value_listenable_builder.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/viewport.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/visibility.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/widget_inspector.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/widget_span.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/src/widgets/will_pop_scope.dart
[        ] -> +file:///Users/caleb.fung/flutter/packages/flutter/lib/widgets.dart
[        ] -> 257eb06d-caff-4920-92f1-0c008b84497b build/app.dill 0
[        ] Updating files
[  +50 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 7... (completed in 962ms)
[        ] Synced 0.9MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +1 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7fd6de80ca20, isolate: {type: @Isolate, fixedId: true, id: isolates/639445046, name: main.dart$main-639445046, number: 639445046}}]}
[        ] <- accept
[        ] Connected to _flutterView/0x7fd6de80ca20.
[   +1 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[        ] An Observatory debugger and profiler on iPhone 7 is available at: http://127.0.0.1:59224/tl1QKkUqszE=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+2566 ms] [DEVICE LOG] 2019-08-11 08:31:55.049651-0500  localhost Runner[13060]: (AggregateDictionary) AggregateDictionary is not supported on this platform
[+2207 ms] [DEVICE LOG] 2019-08-11 08:31:57.257062-0500  localhost Runner[13060]: (Flutter) flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
[   +7 ms] [DEVICE LOG] 2019-08-11 08:31:57.257166-0500  localhost Runner[13060]: (Flutter) flutter: The following assertion was thrown while handling a gesture:
[        ] flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
[        ] flutter: The following assertion was thrown while handling a gesture:
[        ] [DEVICE LOG] 2019-08-11 08:31:57.257259-0500  localhost Runner[13060]: (Flutter) flutter: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 619 pos 14: 'manifest.fromHero !=
[        ] [DEVICE LOG] 2019-08-11 08:31:57.257370-0500  localhost Runner[13060]: (Flutter) flutter: newManifest.fromHero': is not true.
[        ] [DEVICE LOG] 2019-08-11 08:31:57.257459-0500  localhost Runner[13060]: (Flutter) flutter:
[        ] [DEVICE LOG] 2019-08-11 08:31:57.257531-0500  localhost Runner[13060]: (Flutter) flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] [DEVICE LOG] 2019-08-11 08:31:57.257637-0500  localhost Runner[13060]: (Flutter) flutter: more information in this error message to help you determine and fix the underlying cause.
[        ] [DEVICE LOG] 2019-08-11 08:31:57.257718-0500  localhost Runner[13060]: (Flutter) flutter: In either case, please report this assertion by filing a bug on GitHub:
[        ] [DEVICE LOG] 2019-08-11 08:31:57.257817-0500  localhost Runner[13060]: (Flutter) flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] [DEVICE LOG] 2019-08-11 08:31:57.257893-0500  localhost Runner[13060]: (Flutter) flutter:
[        ] [DEVICE LOG] 2019-08-11 08:31:57.257987-0500  localhost Runner[13060]: (Flutter) flutter: When the exception was thrown, this was the stack:
[        ] [DEVICE LOG] 2019-08-11 08:31:57.258091-0500  localhost Runner[13060]: (Flutter) flutter: #2      _HeroFlight.divert (package:flutter/src/widgets/heroes.dart:619:14)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.258208-0500  localhost Runner[13060]: (Flutter) flutter: #3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:809:25)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.258273-0500  localhost Runner[13060]: (Flutter) flutter: #4      HeroController._maybeStartHeroTransition (package:flutter/src/widgets/heroes.dart:746:9)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.258333-0500  localhost Runner[13060]: (Flutter) flutter: #5      HeroController.didStartUserGesture (package:flutter/src/widgets/heroes.dart:712:5)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.258410-0500  localhost Runner[13060]: (Flutter) flutter: #6      NavigatorState.didStartUserGesture (package:flutter/src/widgets/navigator.dart:2171:18)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.258506-0500  localhost Runner[13060]: (Flutter) flutter: #7      new _CupertinoBackGestureController (package:flutter/src/cupertino/route.dart:593:15)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.258638-0500  localhost Runner[13060]: (Flutter) flutter: #8      CupertinoPageRoute._startPopGesture (package:flutter/src/cupertino/route.dart:273:12)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.258720-0500  localhost Runner[13060]: (Flutter) flutter: #9      CupertinoPageRoute.buildPageTransitions.<anonymous closure> (package:flutter/src/cupertino/route.dart:317:36)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.258820-0500  localhost Runner[13060]: (Flutter) flutter: #10     _CupertinoBackGestureDetectorState._handleDragStart (package:flutter/src/cupertino/route.dart:505:37)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.258942-0500  localhost Runner[13060]: (Flutter) flutter: #11     DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:364:45)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.259031-0500  localhost Runner[13060]: (Flutter) flutter: #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.259106-0500  localhost Runner[13060]: (Flutter) flutter: #13     DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:364:7)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.259193-0500  localhost Runner[13060]: (Flutter) flutter: #14     DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:298:7)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.259262-0500  localhost Runner[13060]: (Flutter) flutter: #15     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:250:25)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.259361-0500  localhost Runner[13060]: (Flutter) flutter: #16     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:231:31)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.259440-0500  localhost Runner[13060]: (Flutter) flutter: (elided 12 frames from class _AssertionError and package dart:async)
[        ] [DEVICE LOG] 2019-08-11 08:31:57.259523-0500  localhost Runner[13060]: (Flutter) flutter:
[        ] [DEVICE LOG] 2019-08-11 08:31:57.260202-0500  localhost Runner[13060]: (Flutter) flutter: Handler: "onStart"
[        ] [DEVICE LOG] 2019-08-11 08:31:57.260292-0500  localhost Runner[13060]: (Flutter) flutter: Recognizer:
[        ] [DEVICE LOG] 2019-08-11 08:31:57.260375-0500  localhost Runner[13060]: (Flutter) flutter:   HorizontalDragGestureRecognizer#c8e70
[        ] [DEVICE LOG] 2019-08-11 08:31:57.260457-0500  localhost Runner[13060]: (Flutter) flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] [DEVICE LOG] 2019-08-11 08:31:57.261775-0500  localhost Runner[13060]: (Flutter) flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] [DEVICE LOG] 2019-08-11 08:31:57.262105-0500  localhost Runner[13060]: (Flutter) flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] [DEVICE LOG] 2019-08-11 08:31:57.262396-0500  localhost Runner[13060]: (Flutter) flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] [DEVICE LOG] 2019-08-11 08:31:57.262657-0500  localhost Runner[13060]: (Flutter) flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] flutter: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 619 pos 14: 'manifest.fromHero !=
[        ] flutter: newManifest.fromHero': is not true.
[        ] flutter:
[        ] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] flutter: more information in this error message to help you determine and fix the underlying cause.
[        ] flutter: In either case, please report this assertion by filing a bug on GitHub:
[        ] flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #2      _HeroFlight.divert (package:flutter/src/widgets/heroes.dart:619:14)
[        ] flutter: #3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:809:25)
[        ] flutter: #4      HeroController._maybeStartHeroTransition (package:flutter/src/widgets/heroes.dart:746:9)
[        ] flutter: #5      HeroController.didStartUserGesture (package:flutter/src/widgets/heroes.dart:712:5)
[        ] flutter: #6      NavigatorState.didStartUserGesture (package:flutter/src/widgets/navigator.dart:2171:18)
[        ] flutter: #7      new _CupertinoBackGestureController (package:flutter/src/cupertino/route.dart:593:15)
[        ] flutter: #8      CupertinoPageRoute._startPopGesture (package:flutter/src/cupertino/route.dart:273:12)
[        ] flutter: #9      CupertinoPageRoute.buildPageTransitions.<anonymous closure> (package:flutter/src/cupertino/route.dart:317:36)
[        ] flutter: #10     _CupertinoBackGestureDetectorState._handleDragStart (package:flutter/src/cupertino/route.dart:505:37)
[        ] flutter: #11     DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:364:45)
[        ] flutter: #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] flutter: #13     DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:364:7)
[        ] flutter: #14     DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:298:7)
[        ] flutter: #15     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:250:25)
[        ] flutter: #16     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:231:31)
[        ] flutter: (elided 12 frames from class _AssertionError and package dart:async)
[        ] flutter:
[        ] flutter: Handler: "onStart"
[        ] flutter: Recognizer:
[        ] flutter:   HorizontalDragGestureRecognizer#c8e70
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] [DEVICE LOG] 2019-08-11 08:31:57.266288-0500  localhost Runner[13060]: (Flutter) flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[   +1 ms] [DEVICE LOG] 2019-08-11 08:31:57.274163-0500  localhost Runner[13060]: (Flutter) flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[   +7 ms] [DEVICE LOG] 2019-08-11 08:31:57.282182-0500  localhost Runner[13060]: (Flutter) flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[   +7 ms] [DEVICE LOG] 2019-08-11 08:31:57.290232-0500  localhost Runner[13060]: (Flutter) flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[   +7 ms] [DEVICE LOG] 2019-08-11 08:31:57.298122-0500  localhost Runner[13060]: (Flutter) flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[   +8 ms] [DEVICE LOG] 2019-08-11 08:31:57.306499-0500  localhost Runner[13060]: (Flutter) flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.
[  +12 ms] [DEVICE LOG] 2019-08-11 08:31:57.320126-0500  localhost Runner[13060]: (Flutter) flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 516 pos 12: '_backGestureController != null': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 516 pos 12: '_backGestureController != null': is not true.
```

```
Analyzing flutter_app_accelerator...                                    
No issues found! (ran in 1.3s)
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/caleb.fung/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/caleb.fung/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone 7 • 6D90B229-9D1B-4238-88C0-BE32AF457121 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4
      (simulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

`CupertinoPageRoute` has a `HorizontalDragGestureRecognizer` placed at the starting edge of the screen, to capture swipe back gestures that are intended to pop the current view from the navigation stack. When there's no other competing gesture recognizers, the drag gesture recognizer is the default winner of the gesture area, unless it explicitly rejects itself. For this reason, all taps and vertical drags land in that area are accepted by this `HorizontalDragGestureRecognizer` and subsequently trigger hero transition. However taps and vertical drags often times lack the horizontal movement required to start the transition animation, leaving the hero in a `started` state but will never finish since the animation status will not update. 

This PR validates all the flights and cancels the ones that are cause by such gestures.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/38183

## Tests

I added the following tests:

- invalidate user gesture driven flights when the gesture is invalid.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by pakyo-pan** [comment]
Hope this PR will merge soon !

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 1]
```diff
@@ -727,6 +727,28 @@ class HeroController extends NavigatorObserver {
...
+  @override
+  void didStopUserGesture() {
+    if (navigator.userGestureInProgress)
+      return;
+
+    bool isStaleGesture(_HeroFlight flight) {
+      return flight.manifest.isUserGestureTransition
+          && flight.manifest.type == HeroFlightDirection.pop
+          && flight._proxyAnimation.value == 0
+          && flight._proxyAnimation.status == AnimationStatus.dismissed;
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/heroes.dart]: Isn't this redundant with `flight._proxyAnimation.value == 0`?

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 2]
```diff
@@ -727,6 +727,28 @@ class HeroController extends NavigatorObserver {
     _maybeStartHeroTransition(route, previousRoute, HeroFlightDirection.pop, true);
   }
 
+  @override
+  void didStopUserGesture() {
+    if (navigator.userGestureInProgress)
+      return;
+
+    bool isStaleGesture(_HeroFlight flight) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/heroes.dart]: This would be a good place to explain what a stale gesture is and why we care about them.

File: packages/flutter/lib/src/widgets/heroes.dart [hunk 3]
```diff
@@ -727,6 +727,28 @@ class HeroController extends NavigatorObserver {
...
+          && flight.manifest.type == HeroFlightDirection.pop
+          && flight._proxyAnimation.value == 0
+          && flight._proxyAnimation.status == AnimationStatus.dismissed;
+    }
+
+    final List<_HeroFlight> invalidFlights = _flights.values
+      .where(isStaleGesture)
+      .toList(growable: false);
+
+    // Treat these invalidated flights as dismissed.
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/heroes.dart]: Assuming that _handleAnimationUpdate() removes each invalid flight from _flights. Helpful to say as much here (it also explains why we applied toList() to `_flights.values.where...`

File: packages/flutter/test/widgets/heroes_test.dart [hunk 4]
```diff
@@ -2255,4 +2274,36 @@ Future<void> main() async {
       moreOrLessEquals(tester.getTopLeft(find.text('1')).dx, epsilon: 0.01)
     );
   });
+
+  // Regression test for https://github.com/flutter/flutter/issues/38183.
+  testWidgets('invalidate user gesture driven flights when the gesture is invalid', (WidgetTester tester) async {
```
Comment (HansMuller) [inline packages/flutter/test/widgets/heroes_test.dart]: To help connect this test with the code, maybe: "remove user gesture driven flights with the gesture goes stale"

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by LongCatIsLooong** [comment]
@HansMuller updated per your comments. Replaced `staleGesture` with `invalidFlight`. 
Is there anything we need to fix on the `DragGestureRecognizer` side? `onCancel` needs to be call because the recognizer mistook a tap for a drag?
