### PR TITLE
Use "gradle tasks --all" to query build variants

### LINKED ISSUE #20781: latest gradle com.android.tools.build:gradle:3.3.0-alpha06 breaks flutter, (buildtype is null)
```
 flutter run --debug                                                                            ✔  2534  18:23:09 
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       1.5s
Resolving dependencies...                                    3.4s

The Gradle project does not define a task suitable for the requested build.
Review the android/app/build.gradle file and ensure it defines a debug build type.
Running 'gradlew null'...                                        
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'null' not found in root project 'android'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s                                                                                                                                                                                                               2.4s
Gradle build failed: 1
```

however, if i do change gradle version back to 3.3.0-alpha05 such error is gone

### PR DESCRIPTION
**Pull request by jason-simmons**
Previously flutter_tools had used "gradle properties" to find the build types
and flavors supported by the Gradle project.  Tasks should work more reliably
across different versions of the Android Gradle plugin.

Fixes https://github.com/flutter/flutter/issues/20781

### CODE REVIEW

**Comment by jason-simmons** [comment]
@cbracken

File: packages/flutter_tools/lib/src/android/gradle.dart [hunk 1]
```diff
@@ -24,7 +24,7 @@ import 'android_sdk.dart';
 import 'android_studio.dart';
 
 const String gradleVersion = '4.4';
-final RegExp _assembleTaskPattern = RegExp(r'assemble([^:]+): task ');
+final RegExp _assembleTaskPattern = RegExp(r'assemble(\S+)');
```
Comment (cbracken) [inline packages/flutter_tools/lib/src/android/gradle.dart]: Would `\w` do? I assume the odds of a greedy over-match of another close bracket is roughly nil?

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

File: packages/flutter_tools/lib/src/android/gradle.dart (hunk 1 above)
Comment (jason-simmons) [reply packages/flutter_tools/lib/src/android/gradle.dart]: The intent is to match any task name that starts with "assemble".  I'm not sure exactly what characters are valid in a Gradle task name, but I suspect there are valid characters besides alphanumerics and underscores.

File: packages/flutter_tools/lib/src/android/gradle.dart [hunk 2]
```diff
@@ -97,18 +97,22 @@ Future<GradleProject> _readGradleProject() async {
...
       workingDirectory: flutterProject.android.hostAppGradleRoot.path,
       environment: _gradleEnv,
     );
-    final String properties = runResult.stdout.trim();
-    project = GradleProject.fromAppProperties(properties);
+    final RunResult tasksRunResult = await runCheckedAsync(
+      <String>[gradle, 'app:tasks', '--all'],
+      workingDirectory: flutterProject.android.hostAppGradleRoot.path,
+      environment: _gradleEnv,
+    );
```
Comment (cbracken) [inline packages/flutter_tools/lib/src/android/gradle.dart]: I'm not familiar enough with Gradle's history, but I assume `app:tasks --all` support goes back to whatever older versions we've previously supported? Otherwise we could add a doctor check.

Comment (jason-simmons) [reply packages/flutter_tools/lib/src/android/gradle.dart]: It looks like `tasks --all` has been supported for several years.

I tried implementing a version of this that invokes `app:properties` and `app:tasks --all` in one invocation to avoid the cost of launching two Gradle processes.  I did notice that the output format used when running multiple targets in one command is inconsistent across Gradle versions.

**Comment by 1and1get2** [comment]
https://github.com/flutter/flutter/issues/20781#issuecomment-427195598
