### PR TITLE
Make FlutterGeneratedPluginSwiftPackage an Xcode root package

### LINKED ISSUE #162399: [SwiftPM] Plugin not found right after adding
### Steps to reproduce

Using Flutter 3.27.1, Xcode 16.2, iOS Simulator 18.2:

1. Create a SwiftPM plugin:

   ```
   flutter config --enable-swift-package-manager
   flutter create --template=plugin --platforms=ios plugin_a
   ```

2. Create a SwiftPM app:

   ```
   flutter config --enable-swift-package-manager
   flutter create my_app
   cd my_app
   flutter build ios --config-only
   ```

3. Open project in Xcode

   1. Open the app's `ios/Runner.xcworkspace` using Xcode

4. Modify `my_app/pubspec.yaml` to depend on the plugin:

   ```diff
     dependencies:
   +   plugin_a:
   +     path: ../plugin_a
   ```

5. Start iOS simulator 18.2
6. Run the app:

```
flutter run
```

### Expected results

I expect plugin_a to be found. I suspect this is a caching issue that's cause by having the project open in Xcode while also running from the command line, but we should look into it more.

### Actual results

```
           ComputeTargetDependencyGraph
           note: Building targets in dependency order
           note: Target dependency graph (3 targets)
               Target 'Runner' in project 'Runner'
                   ➜ Explicit dependency on target 'FlutterGeneratedPluginSwiftPackage' in project 'FlutterGeneratedPluginSwiftPackage'
               Target 'FlutterGeneratedPluginSwiftPackage' in project 'FlutterGeneratedPluginSwiftPackage'
                   ➜ Explicit dependency on target 'FlutterGeneratedPluginSwiftPackage' in project 'FlutterGeneratedPluginSwiftPackage'
               Target 'FlutterGeneratedPluginSwiftPackage' in project 'FlutterGeneratedPluginSwiftPackage' (no dependencies)

...

GeneratedPluginRegistrant.m:12:9: error: Module 'plugin_a' not found (in target 'Runner' from project 'Runner')
```

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by vashworth**
This PR makes the `FlutterGeneratedPluginSwiftPackage` swift package an Xcode root package. A root package is one that is within the Xcode project as a file reference. See image below:

Screenshot 2025-05-14 at 2 54 28 PM

This change makes it so that when the `FlutterGeneratedPluginSwiftPackage` changes, if Xcode is also open, Xcode will automatically re-resolve the package. This makes Xcode use the new version instead of whatever it had cached. 

Fixes https://github.com/flutter/flutter/issues/162399 and incremental change towards https://github.com/flutter/flutter/issues/166489.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/macos/swift_package_manager.dart [hunk 1]
```diff
@@ -10,6 +10,8 @@ import '../plugins.dart';
 import '../project.dart';
 import 'swift_packages.dart';
 
+const String kFlutterGeneratedPluginSwiftPackageName = 'FlutterGeneratedPluginSwiftPackage';
```
Comment (loic-sharma) [inline packages/flutter_tools/lib/src/macos/swift_package_manager.dart:13]: Consider adding a quick comment explaining what this is. Something like "The Swift package generated by the Flutter tool to inject Swift packages into the Flutter iOS app's build"

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 2]
```diff
@@ -165,7 +165,6 @@ Future<XcodeBuildResult> buildXcodeProject({
       logger: globals.logger,
       fileSystem: globals.fs,
       plistParser: globals.plistParser,
-      features: featureFlags,
```
Comment (loic-sharma) [inline packages/flutter_tools/lib/src/ios/mac.dart:168]: FYI, this was added so that we could split the SPM app migration into its own feature. This would let us turn on SPM by default for new apps/plugins while keeping the migration opt-in until we had higher confidence in it.

For details, see: https://github.com/flutter/flutter/issues/151567#issuecomment-2455941279

File: packages/flutter_tools/test/general.shard/migrations/swift_package_manager_integration_migration_test.dart [hunk 3]
```diff
@@ -2825,6 +3352,10 @@ String _projectIdentifier(SupportedPlatform platform) {
       : '33CC10E52044A3C60003C045';
 }
 
+String _relativeEphemeralPath(SupportedPlatform platform) {
+  return platform == SupportedPlatform.ios ? 'Flutter/ephemeral' : 'ephemeral';
```
Comment (loic-sharma) [inline packages/flutter_tools/test/general.shard/migrations/swift_package_manager_integration_migration_test.dart:3356]: Would it be possible to use `XcodeBasedProject.ephemeralDirectory` instead and then convert that to a relative path? That'll make sure this logic doesn't break in the unlikely event we move the ephemeral directory. I don't feel strongly about this at all since this seems unlikely, just a thought.

Comment (loic-sharma) [reply packages/flutter_tools/test/general.shard/migrations/swift_package_manager_integration_migration_test.dart:3356]: Whoops, I commented in the wrong code location. Let me move this...

File: packages/flutter_tools/lib/src/migrations/swift_package_manager_integration_migration.dart [hunk 4]
```diff
@@ -95,6 +101,16 @@ class SwiftPackageManagerIntegrationMigration extends ProjectMigrator {
...
   }
 
+  String get _flutterGroupIdentifier {
+    return _platform == SupportedPlatform.ios
+        ? _iosFlutterGroupIdentifier
+        : _macosFlutterGroupIdentifier;
+  }
+
+  String get _relativeEphemeralPath {
+    return _platform == SupportedPlatform.ios ? 'Flutter/ephemeral' : 'ephemeral';
```
Comment (loic-sharma) [inline packages/flutter_tools/lib/src/migrations/swift_package_manager_integration_migration.dart:111]: Would it be possible to use `XcodeBasedProject.ephemeralDirectory` instead and then convert that to a relative path? That'll make sure this logic doesn't break in the unlikely event we move the ephemeral directory. I don't feel strongly about this at all since this seems unlikely, just a thought, feel free to skip.

Comment (loic-sharma) [reply packages/flutter_tools/lib/src/migrations/swift_package_manager_integration_migration.dart:111]: Side note: it looks like the doc's path to the generated package is incorrect for macOS: https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-app-developers#step-1-add-fluttergeneratedpluginswiftpackage-package-dependency-1

image

My bad 😅

Comment (loic-sharma) [reply packages/flutter_tools/lib/src/migrations/swift_package_manager_integration_migration.dart:111]: Hm, I'm a bit confused. Could you expand why the paths different for iOS and macOS? From what I can tell the relative paths should be the same for iOS and macOS:

* `app/ios/Runner.xcodeproj/project.pbxproj`
* `app/macos/Runner.xcodeproj/project.pbxproj`
* `app/ios/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage/Package.swift`
* `app/macos/Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage/Package.swift`

Consider adding a comment here to clarify.

**Comment by loic-sharma** [comment]
As part of this change, don't forget to also update the doc's [Add SwiftPM to app manually](https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-app-developers#add-to-a-flutter-app-manually) guide too :)

File: packages/flutter_tools/lib/src/migrations/swift_package_manager_integration_migration.dart (hunk 4 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/migrations/swift_package_manager_integration_migration.dart:117]: > Hm, I'm a bit confused. Could you expand why the paths different for iOS and macOS?

I don't completely understand why either. My guess is that because the iOS Flutter `PBXGroup` uses `name` and the macOS Flutter `PBXGroup` uses path. Again, just an educated guess, though

https://github.com/flutter/flutter/blob/6f7ac047ad920c30c0173778b7a492708741c43e/packages/flutter_tools/templates/app/ios-swift.tmpl/Runner.xcodeproj/project.pbxproj.tmpl#L99

https://github.com/flutter/flutter/blob/6f7ac047ad920c30c0173778b7a492708741c43e/packages/flutter_tools/templates/app/macos.tmpl/Runner.xcodeproj/project.pbxproj.tmpl#L171

I added a comment

Comment (loic-sharma) [reply packages/flutter_tools/lib/src/migrations/swift_package_manager_integration_migration.dart:117]: Ahh interesting, thanks for the excellent comment!

File: packages/flutter_tools/lib/src/migrations/swift_package_manager_integration_migration.dart [hunk 5]
```diff
@@ -365,10 +401,21 @@ $newContent
       projectInfo,
       logErrorIfNotMigrated: logErrorIfNotMigrated,
     );
+    final bool pacakgeFileReferenceMigrated = _isFileReferenceMigrated(
```
Comment (loic-sharma) [inline packages/flutter_tools/lib/src/migrations/swift_package_manager_integration_migration.dart:404]:
```suggestion
    final bool packageFileReferenceMigrated = _isFileReferenceMigrated(
```

**Review by loic-sharma — APPROVED** [review]
Looks great, excellent tests!
