### PR TITLE
Provide default method call handler for SystemChannels.textInput

### LINKED ISSUE #101016: [iOS] Apple Pencil cannot slide and scribble normally after the system's Scribble is turned on
## Steps to Reproduce

1. Open the system [Settings] [Apple Pencil] [Scribble] [Enable]
2. List swipe or doodle is not normal

--- 
If I turn off step 1 everything works fine

**Expected results:** 
1. The list can slide normally
2. Graffiti is normal

**Actual results:**
1. The list does not scroll properly
2. The sliding event cannot be accepted normally

|turn off event | turn on event|
|--|--|
|关闭随手写|开启随手写|

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemBuilder: (context, index) {
          return ListTile(
            title: Text('Item $index'),
          );
        },
        itemCount: 100,
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.1 21C52 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.10.4 at /Users/zero/fvm/versions/2.10.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/zero/sdk/android-sdk-macosx
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/zero/sdk/android-sdk-macosx
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (4 available)
    • iisimpler (mobile) • 00008027-000561E234E2402E            • ios
      • iOS 15.1 19B74
    • iPhone 13 (mobile) • 465F1905-FC7E-4B57-87B0-2F9910F10A8E • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 12.1 21C52 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 99.0.4844.83
    ! Error: XGJiPad is not connected. Xcode will continue when XGJiPad is
      connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

https://user-images.githubusercontent.com/8764899/160759748-89347017-f396-4dfd-85d3-8514c24aa5f5.MP4

https://user-images.githubusercontent.com/8764899/160759832-ffe3d735-9f2c-4cc6-9849-9f53fa1f91d1.MP4

### PR DESCRIPTION
**Pull request by fbcouch**
On the iPad, starting with flutter 2.10, the engine sets up a `UIIndirectScribbleInteraction` and attempts to communicate with the framework over the `flutter/textinput` channel when a Scribble interaction begins (see https://github.com/flutter/engine/pull/24224). However, before that channel has a method call handler, the engine does not get a reply, so iPadOS continues sending pencil input to the Scribble feature, rather than allowing flutter to capture the input.

Adding a default method call handler allows the engine to get a `null` reply immediately, so that iPadOS can finish the Scribble interaction and allow input to flow back to flutter. `TextInput` will set it's own handler once instantiated, so this does not appear to interfere with normal text input.

Fixes https://github.com/flutter/flutter/issues/101016

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/services/binding.dart [hunk 1]
```diff
@@ -37,6 +37,7 @@ mixin ServicesBinding on BindingBase, SchedulerBinding {
     SystemChannels.system.setMessageHandler((dynamic message) => handleSystemMessage(message as Object));
     SystemChannels.lifecycle.setMessageHandler(_handleLifecycleMessage);
     SystemChannels.platform.setMethodCallHandler(_handlePlatformMessage);
+    SystemChannels.textInput.setMethodCallHandler((MethodCall call) => Future<void>.value());
```
Comment (goderbauer) [inline packages/flutter/lib/src/services/binding.dart:40]: This looks very odd - and hopefully isn't the real fix here. If it is, this will need a comment explaining what's going on.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/services/binding.dart:40]: With Scribble I think one will be able to enter text when `TextInput._instance` isn't initialized, so the text input plugin now may start the communication (before that the communication starts when a text field gains focus). So I guess we can do this, or use a separate method channel for Scribble.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/services/binding.dart:40]: Also I suspect flutter iPad Scribble does not work until the first text field gains focus, because `TextInput._instance` is lazily initialized?

Comment (fbcouch) [reply packages/flutter/lib/src/services/binding.dart:40]: So the issue is that the indirect scribble interaction is set up on the engine side, but with nothing on the framework side handling messages on the textinput channel yet, there are a few moments where iPadOS isn't sure whether a scribble interaction is going to happen or not, so it swallows the inputs and shows a little pencil streak.

If there's a default handler on the method channel, as here, then that doesn't happen because the engine gets a very fast reply over the channel and can let iPadOS know that there won't be a scribble interaction occurring.

I suppose an alternative solution might be to wait to add the UIIndirectScribbleInteraction until we get a message from the framework over the channel...I think that might work in 2.12, since it no longer waits for focus to set up the `TextInput._instance`.

If this is acceptable, though, I can try to distill that down into something appropriate for a comment.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/services/binding.dart:40]: > I think that might work in 2.12, since it no longer waits for focus to set up the `TextInput._instance`.

Ah I see `TextInput` is accessed in `initState`. 

I would slightly prefer setting up the method handler eagerly over waiting for the first incoming message in the engine. @goderbauer suggestions for making it less odd? Maybe we can expose a `TextInput.ensureInitialized` method and call that?

Comment (goderbauer) [reply packages/flutter/lib/src/services/binding.dart:40]: I don't fully understand how the scribble feature works, but it is odd that the engine sends us a message and we just drop it on the floor. We should either set up the correct message handler here and handle the message or change the engine side to not send these over the channel until the framework can actually handle them.

**Comment by goderbauer** [comment]
(Triage) @fbcouch Do you still have plans to follow up on this PR?

**Comment by fbcouch** [comment]
> (Triage) @fbcouch Do you still have plans to follow up on this PR?

Yes, thank you for the reminder! I updated the above to add a `TextInput.ensureInitialized()` call as @LongCatIsLooong  suggested, that way we have the proper method channel set up. I suppose it's possible that there could be cases where ScribbleClients get registered without a proper text input on the screen (yet), so I think that's the better way to go, actually.

**Review by justinmc — COMMENTED** [review]
This solution looks nice to me compared to the original one, but @LongCatIsLooong should get a final look.

File: packages/flutter/lib/src/services/binding.dart [hunk 2]
```diff
@@ -36,6 +37,7 @@ mixin ServicesBinding on BindingBase, SchedulerBinding {
     SystemChannels.system.setMessageHandler((dynamic message) => handleSystemMessage(message as Object));
     SystemChannels.lifecycle.setMessageHandler(_handleLifecycleMessage);
     SystemChannels.platform.setMethodCallHandler(_handlePlatformMessage);
+    TextInput.ensureInitialized();
```
[the remark this answers is not in the document]
Comment (fbcouch) [reply packages/flutter/lib/src/services/binding.dart:40]: I think the only negative would be whatever small amount of memory the TextInput instance consumes

**Review by LongCatIsLooong — APPROVED** [review]

**Review by cbracken — APPROVED** [review]

**Review by justinmc — APPROVED** [review]
LGTM 👍

**Comment by p-kuen** [comment]
When does this PR land in stable? It is very frustrating having no clue when this critical issue would be solved in stable. I have no chance to use the stable version right now and have to roll back to an earlier version of flutter to just make it work..
The fix with just a few code line changes is not even available in beta channel.
