### PR TITLE
remove the flutter view cache; fix the ability to quit the app after a full restart

### LINKED ISSUE #11409: quiting the flutter run process no longer stops the app on the device
To repro:

- flutter run
- issue a restart
- type 'q' (for quit)

The app doesn't quit. The restart above is necessary for this to repro, so I'm guessing that we're losing track of the isolate to send messages to after the full restart.

### PR DESCRIPTION
**Pull request by devoncarew**
- remove a secondary cache of FlutterViews (instead, just gather info from the cache on the VMService objects)
- fix https://github.com/flutter/flutter/issues/11409
- add a test to validate that we can quit the app after a full restart

@Hixie

### CODE REVIEW

File: dev/devicelab/bin/tasks/commands_test.dart [hunk 1]
```diff
@@ -59,10 +65,18 @@ void main() {
       print('test: pressing "P" again...');
       run.stdin.write('P');
       await drive('none');
+      print('test: pressing "r" to perform a hot reload...');
+      run.stdin.write('r');
+      await drive('none');
```
Comment (Hixie) [inline dev/devicelab/bin/tasks/commands_test.dart]: you may have to await the hot reload having completed (maybe by reading the output from stdout until you get notified, that'd be the most useful way in terms of testing things) otherwise it's possible the drive will race and connect before the hot reload has started.

**Comment by Hixie** [comment]
I don't really understand the changes to flutter_tools proper.

**Comment by devoncarew** [comment]
I don't know the specific break, but I think that the secondary cache (`_viewsCache`) was not being maintained properly. I believe @zanderso has worked in this area recently, so could likely also review.

File: packages/flutter_tools/lib/src/resident_runner.dart [hunk 2]
```diff
@@ -67,29 +62,15 @@ class FlutterDevice {
       return;
     for (VMService service in vmServices)
       await service.vm.refreshViews();
-    _viewsCache = null;
   }
 
-  List<FlutterView> _viewsCache;
   List<FlutterView> get views {
-    if (_viewsCache == null) {
-      if ((vmServices == null) || vmServices.isEmpty)
```
Comment (zanderso) [inline packages/flutter_tools/lib/src/resident_runner.dart]: I'd recommend retaining this behavior.

Comment (devoncarew) [inline packages/flutter_tools/lib/src/resident_runner.dart]: Ah, the null check; will do.

File: dev/devicelab/bin/tasks/commands_test.dart (hunk 1 above)
Comment (devoncarew) [inline dev/devicelab/bin/tasks/commands_test.dart]: OK, I awaited the starting messages for the hot reload and restart commands.

**Review by zanderso — APPROVED** [review]
lgtm
