### PR TITLE
AutomaticKeepAlive now keeps alive

### LINKED ISSUE #16346: Automatic Keep Alive not work
## Steps to R
I use the AutomaticKeepAliveClientMixin in my widget , but it does not work ,when the widget scroll out the viewport , the widget doesn't keep alive 

this is my demo code,  my purpose is keeping DetailCommentListHeader widget alive when DetailCommentListHeader scroll out the viewport,  but when DetailCommentListHeader scorll out, DetailCommentHeaderState dispose was call , pls see the log

```dart
import 'package:flutter/material.dart';


class DetailCommentListHeader extends StatefulWidget{
  DetailCommentListHeader({Key key}):super(key:key);

  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return new DetailCommentHeaderState();
  }
}

class DetailCommentHeaderState extends State<DetailCommentListHeader> with AutomaticKeepAliveClientMixin<DetailCommentListHeader> {
  @override
  // TODO: implement wantKeepAlive
  bool get wantKeepAlive => true;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    print('DetailCommentHeaderState initState');
  }

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    print("DetailCommentListHeader dispose");
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    String text = 'need keep alive';

    // TODO: implement build
    return new Container(
      color: Colors.white,
      height: 48.0,
      child: new Padding(padding: new EdgeInsets.fromLTRB(16.0, 14.0, 0.0 , 14.0,),
        child: new Text(text, style: new TextStyle(fontSize: 16.0, fontWeight: FontWeight.bold),),
      ),
    );
  }
}

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Keep Alive Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new ListView.builder(
          itemCount: 50,
          itemBuilder: (BuildContext context, int index){
            if (index == 0){
              return new DetailCommentListHeader();
            }
            return new Container(
              height: 44.0,
              child: new Text('just padding'),
              color: Colors.yellow.shade300,
            );
          },
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

## Logs

DetailCommentListHeader dispose
DetailCommentHeaderState initState
DetailCommentListHeader dispose
DetailCommentHeaderState initState
DetailCommentListHeader dispose
DetailCommentHeaderState initState

## Flutter Doctor

[✓] Flutter (Channel beta, v0.2.8, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
    • Flutter version 0.2.8 at /Users/chaokong/flutterSDK
    • Framework revision b397406561 (7 days ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/chaokong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 173.4548.30

[✓] Connected devices (2 available)
    • 张伟平的 iPhone • fb87fda18a77f01197d25047bed12a782b21e01f • ios • iOS 11.2.2
    • iPhone X    • E1F86F6C-535C-4691-9C4F-1D90F5A7668C     • ios • iOS 11.3 (simulator)

! Doctor found issues in 1 category.

• No issues found!

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/16346.

See https://github.com/flutter/flutter/issues/16346#issuecomment-380255095 for detailed explanation of what was going wrong before this fix.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/automatic_keep_alive.dart [hunk 1]
```diff
@@ -80,29 +80,61 @@ class _AutomaticKeepAliveState extends State<AutomaticKeepAlive> {
...
+    // just received a notification, which we wouldn't be able to do if we
+    // hadn't built our child and its child -- our build method always builds
+    // the same subtree and it always includes the node we're looking for
+    // (KeepAlive) as the parent of the node that reports the notifications
+    // (NotificationListener).
+    //
+    // If we are called during the first build of this subtree the links to the
+    // children will not be hooked up yet. In that case this method returns
+    // null despite the fact that we will have a child after the build
+    // completes. It's the callers responsibility to deal with this case.
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/automatic_keep_alive.dart]: caller's

File: packages/flutter/lib/src/widgets/automatic_keep_alive.dart [hunk 2]
```diff
@@ -80,29 +80,61 @@ class _AutomaticKeepAliveState extends State<AutomaticKeepAlive> {
...
-      });
+      final ParentDataElement<SliverMultiBoxAdaptorWidget> childElement = _getChildElement();
+      if (childElement != null) {
+        // If the child already exists, update it synchronously.
+        _updateParentDataOfChild(childElement);
+      } else {
+        // If the child doesn't exist yet, we got called during the very first
+        // build of this subtree. Wait until the end of the frame to update
+        // the child when the child is guaranteed to be present.
+        SchedulerBinding.instance.addPostFrameCallback((_) {
```
Comment (Hixie) [inline packages/flutter/lib/src/widgets/automatic_keep_alive.dart]: we should be explicit about argument names and types even if we don't use them, that way people editing or copying the code don't have to look up what it is

File: packages/flutter/test/widgets/automatic_keep_alive_test.dart [hunk 3]
```diff
@@ -443,4 +443,50 @@ void main() {
...
+
+    expect(find.byKey(const GlobalObjectKey<_AlwaysKeepAliveState>(0)), findsOneWidget);
+    await tester.drag(find.byType(ListView), const Offset(0.0, -1000.0)); // move to bottom
+    await tester.pump();
+    expect(find.byKey(const GlobalObjectKey<_AlwaysKeepAliveState>(0)), findsOneWidget);
+  });
+}
+
+class _AlwaysKeepAlive extends StatefulWidget{
+  const _AlwaysKeepAlive({Key key}):super(key:key);
```
Comment (Hixie) [inline packages/flutter/test/widgets/automatic_keep_alive_test.dart]: trivial nits: space before `{` on the class line, spaces around first `:` and space after second `:` on the constructor line.

File: packages/flutter/test/widgets/automatic_keep_alive_test.dart [hunk 4]
```diff
@@ -443,4 +443,50 @@ void main() {
...
+            child: const Text('FooBar'),
+          );
+        },
+      ),
+    ));
+
+    expect(find.byKey(const GlobalObjectKey<_AlwaysKeepAliveState>(0)), findsOneWidget);
+    await tester.drag(find.byType(ListView), const Offset(0.0, -1000.0)); // move to bottom
+    await tester.pump();
+    expect(find.byKey(const GlobalObjectKey<_AlwaysKeepAliveState>(0)), findsOneWidget);
```
Comment (Hixie) [inline packages/flutter/test/widgets/automatic_keep_alive_test.dart]: maybe also verify that "keep me alive" is present but "FooBar" is not?

**Comment by Hixie** [comment]
LGTM

File: packages/flutter/test/widgets/automatic_keep_alive_test.dart (hunk 3 above)
Comment (jukbot) [reply packages/flutter/test/widgets/automatic_keep_alive_test.dart]: in the future, maybe it's a good idea to integrate pre-commit hook of dart prettifier which automatically formats code style to the branch.
