### PR TITLE
Fix `flutter create` warning regarding Java compatibility

### LINKED ISSUE #152460: `flutter create` warning regarding Java compatibility needs a bit of cleanup for consistency
I ran `flutter create` and got:
```
$ flutter create skiazoom
Creating project skiazoom...
Resolving dependencies in `skiazoom`...
Downloading packages...
Got dependencies in `skiazoom`.
Wrote 129 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd skiazoom
  $ flutter run

Your application code is in skiazoom/lib/main.dart.

The configured version of Java detected may conflict with the Android Gradle Plugin (AGP) version in your new Flutter app.

[RECOMMENDED] If so, to keep the default AGP version 8.1.0, make
sure to download a compatible Java version
(Java 17 <= compatible Java version < Java 21).
You may configure this compatible Java version by running:
`flutter config --jdk-dir=<JDK_DIRECTORY>`
Note that this is a global configuration for Flutter.


Alternatively, to continue using your configured Java version, update the AGP
version specified in the following files to a compatible AGP
version (minimum compatible AGP version: 7.0) as necessary:
    -  /home/ianh/dev/skiazoom/android/build.gradle

See
https://developer.android.com/build/releases/gradle-plugin for details on
compatible Java/AGP versions.
```

Some things we could improve:

* The wrapping is inconsistent throughout. Lines within paragraphs should all be roughly the same length, and paragraphs should have a blank line between them. ("See" on its own line, 

* We don't generally do `[RECOMMENDED]`, that's not normal English grammar. Just use a normal English sentence like "The recommended action is..." or whatever. 

* We use inconsistent style regarding how to execute commands. The top part uses indented paragraphs with `$ cd bla` whereas the recommended section uses backticks on an unindented line in a paragraph.

* "Note that" is redundant text and our style guide says to just not have it.

* There's one paragraph that ends with an indented line with hyphens as a bullet and two spaces. This is unusual for our output in the tool as well.

### PR DESCRIPTION
**Pull request by shashwatpathak98**
This PR modifies the warning message regarding Java compatibility to make it consistent with the Flutter style guide.

**Current message looks like this**
```
[RECOMMENDED] If so, to keep the default AGP version 8.1.0, make
sure to download a compatible Java version
(Java 17 <= compatible Java version < Java 21).
You may configure this compatible Java version by running:
`flutter config --jdk-dir=<JDK_DIRECTORY>`
Note that this is a global configuration for Flutter.

Alternatively, to continue using your configured Java version, update the AGP
version specified in the following files to a compatible AGP
version (minimum compatible AGP version: 7.0) as necessary:
    -   /home/user/project/testproj/android/build.gradle

See
https://developer.android.com/build/releases/gradle-plugin for details on
compatible Java/AGP versions.
```

**After Modification**

```
To keep the default AGP version 8.1.0, download a compatible Java version 
(Java 17 <= compatible Java version < Java 21). Configure this Java version 
globally for Flutter by running:

  flutter config --jdk-dir=<JDK_DIRECTORY>

Alternatively, to continue using your current Java version, update the AGP 
version in the following file(s) to a compatible version (minimum AGP version: 7.0):

  /home/user/project/testproj/android/build.gradle

For details on compatible Java and AGP versions, see
https://developer.android.com/build/releases/gradle-plugin
```

Fixes #152460 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/create.dart [hunk 1]
```diff
@@ -959,19 +959,18 @@ used.
   // AGP template version incompatible with Java version.
   final gradle.JavaAgpCompat? minimumCompatibleAgpVersion = gradle.getMinimumAgpVersionForJavaVersion(globals.logger, javaV: javaVersion);
   final String compatibleAgpVersionMessage = minimumCompatibleAgpVersion == null ? '' : ' (minimum compatible AGP version: ${minimumCompatibleAgpVersion.agpMin})';
-  final String gradleBuildFilePaths = '    -  ${_getBuildGradleConfigurationFilePaths(projectType, projectDirPath)!.join('\n    - ')}';
+  final String gradleBuildFilePaths = '    - ${_getBuildGradleConfigurationFilePaths(projectType, projectDirPath)!.join('\n    - ')}';
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/commands/create.dart:962]: let's remove the `-` here too since we don't have it where we give the url later

Comment (shashwatpathak98) [reply packages/flutter_tools/lib/src/commands/create.dart]: Sure, I removed it.

**Comment by Hixie** [comment]
change looks good to me, but as the bot says, it will need tests to make sure we don't break it again :-)

the test could just be something like, check that each line is less than the max line length, and check that each line is more than half the line length unless the next line is empty. or something like that.

**Comment by shashwatpathak98** [comment]
Thanks @Hixie Sure , working on the test.

**Comment by ishon19** [comment]
Hi @Hixie! Thanks for the review, I added a test, which seems to be functional, but a couple of `Mac framework_tests` are failing, not exactly sure how to deal with them.

File: packages/flutter_tools/lib/src/commands/create.dart [hunk 2]
```diff
@@ -959,19 +959,18 @@ used.
...
 
   globals.printWarning('''
 $incompatibleVersionsAndRecommendedOptionMessage
 
-Alternatively, to continue using your configured Java version, update the AGP
-version specified in the following files to a compatible AGP
-version$compatibleAgpVersionMessage as necessary:
+Alternatively, to continue using your current Java version, update the AGP
+version in the following file to a compatible version$compatibleAgpVersionMessage:
+
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/commands/create.dart:969]: Could multiple files be listed here? In case do we want to use `file(s)` instead of changing `files` to `file`?

```suggestion
version in the following file(s) to a compatible version$compatibleAgpVersionMessage:
```

File: packages/flutter_tools/lib/src/commands/create.dart [hunk 3]
```diff
@@ -959,19 +959,18 @@ used.
...
 $gradleBuildFilePaths
 
-See
-https://developer.android.com/build/releases/gradle-plugin for details on
-compatible Java/AGP versions.
+For details on compatible Java and AGP versions, see:
+https://developer.android.com/build/releases/gradle-plugin
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/commands/create.dart:973]:
```suggestion
For details on compatible Java and AGP versions, see
https://developer.android.com/build/releases/gradle-plugin
```

The semicolon feels unnecessary here. What do you think?

File: packages/flutter_tools/lib/src/commands/create.dart (hunk 2 above)
Comment (ishon19) [reply packages/flutter_tools/lib/src/commands/create.dart:969]: Nice catch, thanks @andrewkolos! Yes, since we are listing `$gradleBuildFilePaths` there could be multiple files, so this suggestion makes sense.

File: packages/flutter_tools/lib/src/commands/create.dart (hunk 3 above)
Comment (ishon19) [reply packages/flutter_tools/lib/src/commands/create.dart:972]: I agree, since we already have a line break here the semicolon doesn't really add much value, updating.

**Review by andrewkolos — APPROVED** [review]
LGTM! This will need another approval from a flutter contributor to land. I will wait to see if @Hixie has any more thoughts. Otherwise, I'll look for another reviewer in a week or so.

**Comment by ishon19** [comment]
> LGTM! This will need another approval from a flutter contributor to land. I will wait to see if @Hixie has any more thoughts. Otherwise, I'll look for another reviewer in a week or so.

Awesome, thanks a lot for the review @andrewkolos!

**Review by christopherfujino — APPROVED** [review]
LGTM
