### PR TITLE
Fix refresh control in the gallery demo, update comments 

### LINKED ISSUE #21820: CupertinoSliverRefreshControll not work on Android
## Steps to Reproduce

CupertinoSliverRefreshControll not work on Android. On iOS works perfectly
```dart
new CustomScrollView(
          slivers: <Widget>[
            new  CupertinoSliverRefreshControl(
              onRefresh: ,
            ),
            new SliverSafeArea(
              top: true, 
              sliver: new SliverPadding(
                sliver: new SliverList(
                  delegate: new SliverChildBuilderDelegate(
                        (context, index) => ,
                    childCount: ....,
                  ),
                ),
              ),
            ),
          ],
        );
```

screenshot_1536847924 2 2
simulator screen shot - iphone x - 2018-09-13 at 17 12 26 2

```
[✓] Flutter (Channel master, v0.8.3-pre.24, on Mac OS X 10.13.6 17G2307, locale ru-RU)
    • Flutter version 0.8.3-pre.24 at /users/tencar/development/flutter
    • Framework revision 387948a239 (2 days ago), 2018-09-11 08:51:42 +0200
    • Engine revision e65beb89da
    • Dart version 2.1.0-dev.4.0.flutter-ef72098353

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/tencar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 8.0.0 (API 26) (emulator)
    • iPhone (Андрей)           • e09c97faece05a08ba4dad424760438835e7aa4b • ios         • iOS 11.4.1
    • iPhone X                  • 7C386461-A480-4EAA-B478-26142C473ED0     • ios         • iOS 11.4 (simulator)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

- Fixed the bug where `CupertinoRefreshControl` doesn't work in the gallery demo on Android.
- Updated documentation on `CupertinoRefreshControl`
- Added comments to the gallery demo  
- Added concrete examples to `ScrollPhysics`

## Related Issues

Fixes #21820 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/refresh.dart [hunk 1]
```diff
@@ -249,7 +249,10 @@ typedef RefreshCallback = Future<void> Function();
 ///
 /// Can only be used in downward-scrolling vertical lists that overscrolls. In
 /// other words, refreshes can't be triggered with lists using
-/// [ClampingScrollPhysics].
+/// [ClampingScrollPhysics]. In order for [CupertinoSliverRefreshControl] to work properly
+/// on Android (which uses [ClampingScrollPhysics] by default), be sure to override
```
Comment (xster) [inline packages/flutter/lib/src/cupertino/refresh.dart]: Be direct in documentations and avoid 'editorializing'. Just 'override' instead of 'be sure to override'.

They can override physics or insert different ScrollConfiguration in the tree above it as well. 

Add a see also to ScrollConfiguration in the doc list below too.

File: packages/flutter/lib/src/widgets/scroll_physics.dart [hunk 2]
```diff
@@ -34,7 +39,14 @@ class ScrollPhysics {
   /// If a subclass of [ScrollPhysics] does not override a method, that subclass
   /// will inherit an implementation from this base class that defers to
   /// [parent]. This mechanism lets you assemble novel combinations of
-  /// [ScrollPhysics] subclasses at runtime.
+  /// [ScrollPhysics] subclasses at runtime. For example:
+  ///
+  /// ```dart
+  /// BouncingScrollPhysics(parent: AlwaysScrollPhysics())
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scroll_physics.dart]: All doc sample codes need to be compilable. This line's missing a ;

File: packages/flutter/lib/src/widgets/scroll_physics.dart [hunk 3]
```diff
@@ -34,7 +39,14 @@ class ScrollPhysics {
...
+  ///
+  /// ```
+  /// will result in a [ScrollPhysics] that has the combined behavior
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scroll_physics.dart]: Just saying 'combined' is a bit oversimplifying it. We should say something to the effect of 'behaviors not specified by BouncingScrollPhysics will defer to AlwaysScrollPhysics'.

File: packages/flutter/lib/src/widgets/scroll_physics.dart [hunk 4]
```diff
@@ -57,6 +69,20 @@ class ScrollPhysics {
   /// is applied recursively and ancestor will appear at the end of the
   /// existing chain of parents.
   ///
+  /// {@tool sample}
+  ///
+  /// In the following example, the [applyTo] method is used to combine two existing [ScrollPhysics] instances,
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scroll_physics.dart]: The below seems right but I'm not sure what question are we answering for the users. It's a bit academic. What is the concrete practical question the user is likely asking that we're answering here?

File: packages/flutter/lib/src/widgets/scroll_physics.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/scroll_physics.dart]: The sample code analyzer doesn't expect the trailing `;` if it's a constructor iirc.

**Comment by LongCatIsLooong** [comment]
@xster the workaround seems to be working.

**Comment by xster** [comment]
Is this ready for review?

**Comment by LongCatIsLooong** [comment]
> Is this ready for review?

yep

**Review by xster — COMMENTED** [review]
Sorry I started reviewing but forgot to press submit

File: packages/flutter/lib/src/widgets/scroll_physics.dart [hunk 5]
```diff
@@ -24,6 +32,13 @@ export 'package:flutter/physics.dart' show Simulation, ScrollSpringSimulation, T
 /// velocity are used as the initial conditions for the particle in the
 /// simulation. The movement of the particle in the simulation is then used to
 /// determine the scroll position for the widget.
+///
+/// Instead of creating your own subclasses, [parent] can be used to combine
+/// [ScrollPhysics] objects of differnt types to get the desired scroll physics.
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scroll_physics.dart]: different

File: packages/flutter/lib/src/widgets/scroll_physics.dart [hunk 6]
```diff
@@ -24,6 +32,13 @@ export 'package:flutter/physics.dart' show Simulation, ScrollSpringSimulation, T
...
+///
+/// See also:
+///  * [parent], the parent [ScrollPhysics] that determines the default
```
Comment (xster) [inline packages/flutter/lib/src/widgets/scroll_physics.dart]: Don't add fields in the class as see also links.

**Review by xster — COMMENTED** [review]
LGTM

**Comment by xster** [comment]
LGTM
