### PR TITLE
Make `FittedBox` not throw when child has zero size.

### LINKED ISSUE #135082: `SizedBox` with zero size throws `Failed assertion: ... 'width > 0.0': is not true`, Proposal to improve error message if `SizedBox` has zero size
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Write the following
  ```dart
    const Row(
        children: [
          FittedBox(
            child: SizedBox(
              height: 0,
              width: 0,
            ),
          ),
        ],
      ),
```

2. Run

### Expected results

Nothing to be displayed as the widget is effectively zero sized.

### Actual results

```
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 320 pos 12: 'width > 0.0': is not true.
box.dart:320

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml
```

If I change the SizedBox to have a non-zero size, or take the FittedBox out of the Row, then the assertion goes away. I'm only filing this to improve the error message / handling of zero width elements.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const Row(
        children: [
          FittedBox(
            child: SizedBox(
              height: 0,
              width: 0,
            ),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-GB)
    • Flutter version 3.13.4 on channel stable at /opt/homebrew/Caskroom/flutter/3.13.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (7 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bramp/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.73.20230904

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #139539: When wrapping a network image with BoxFit.scaleDown in Flutter, an error occur
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

i will show all source code

### Expected results

can render the image

### Actual results

received some errors

The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 320 pos 12: 'width > 0.0': is not true.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [FittedBox].

void main() => runApp(const FittedBoxApp());

class FittedBoxApp extends StatelessWidget {
  const FittedBoxApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('FittedBox Sample')),
        body: const Center(
          child: FittedBoxExample(),
        ),
      ),
    );
  }
}

class FittedBoxExample extends StatelessWidget {
  const FittedBoxExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 400,
      width: 300,
      color: Colors.blue,
      child: FittedBox(
          // TRY THIS: Try changing the fit types to see how they change the way
          // the placeholder fits into the container.
          fit: BoxFit.scaleDown,
          clipBehavior: Clip.hardEdge,
          alignment: Alignment.bottomRight,
          // case1: work well
          // child: Placeholder(),

          // case2: received some errors
          child: Image.network(
            'https://oss-media.cdn.bcebos.com/content_square/33d57650-8078-9ae5-5f93-7dc50285b4bf.jpg',
            fit: BoxFit.scaleDown,
          )

          // case3: work well
          // child: Container(
          //   width: 200,
          //   height: 200,
          //   child: Image.network(
          //     'https://oss-media.cdn.bcebos.com/content_square/33d57650-8078-9ae5-5f93-7dc50285b4bf.jpg',
          //     fit: BoxFit.scaleDown,
          //   )
          // ),
          ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
image

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.1.1 23B81 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 3 categories.

```

</details>

### LINKED ISSUE #142910: Assertion error when using FittedBox (BoxFit.scaleDown,) inside AspectRatio within a Container with fixed width
### Steps to reproduce

1. in a scaffold body> center > column: add a container with width: MediaQuery.sizeOf(context).width * 0.3,
2. add child AspectRatio with aspectRatio: 16 / 9,
3. ad child FittedBox with fit: BoxFit.scaleDown, (error only happens on scaleDown)
4. add child Image with any image (for me it was network image)

### Expected results

as per the documentation: Align the source within the target box (by default, centering) and, if necessary, scale the source down to ensure that the source fits within the box.
it should fit the image within the box

### Actual results

image disappears and the following error is thrown:

```
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 320 pos 12: 'width > 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml
```

### Code sample

<details open><summary>Code sample</summary>

```dart
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Column(
          children: [
            Container(
                width: MediaQuery.sizeOf(context).width * 0.3,
                child: AspectRatio(
                    aspectRatio: 16 / 9,
                    child: FittedBox(
                      fit: BoxFit.scaleDown,
                      child: Image(
                          image: NetworkImage(
                              'https://www.figma.com/file/8WJqutydnwMKD9P1K2o0sQ/image/8af266d840515558d8a8420841ad055b07310ae4')),
                    ))),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Screenshot_1707134131

</details>

### Logs

<details open><summary>Logs</summary>

```console
Restarted application in 1,016ms.
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Localization initialized
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Start
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Init state
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Build
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Init Localization Delegate
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Init provider
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Build
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Init Localization Delegate
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Init provider
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Load Localization Delegate
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Load asset from assets/langs
D/EGL_emulation(10987): app_time_stats: avg=3787.98ms min=3787.98ms max=3787.98ms count=1

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 320 pos 12: 'width > 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    FittedBox FittedBox:file:///home/osama/projects/flutter/meet-mobile/lib/pages/home_page.dart:18:28

When the exception was thrown, this was the stack:
#2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio (package:flutter/src/rendering/box.dart:320:12)
#3      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2722:58)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#5      RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#6      RenderAspectRatio.performLayout (package:flutter/src/rendering/proxy_box.dart:576:14)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#8      RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#9      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:279:14)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#11     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#12     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#13     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#14     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#16     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#17     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:434:14)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#19     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#20     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#21     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062:7)
#22     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#23     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#25     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#28     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#30     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434:11)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#32     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#35     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#38     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#41     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#47     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#50     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#53     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#56     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#59     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#61     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3714:13)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#63     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#66     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#67     _RenderTheaterMixin.performLayout (package:flutter/src/widgets/overlay.dart:884:15)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#69     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#72     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#75     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#77     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569:11)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#79     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#82     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#85     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#88     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#91     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#94     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#96     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#97     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#98     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#99     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:581:43)
#100    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:608:12)
#101    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
#102    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
#103    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
#104    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
#105    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#106    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#107    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#108    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#109    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#110    _invoke (dart:ui/hooks.dart:312:13)
#111    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#112    _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)

The following RenderObject was being processed when the exception was fired: RenderFittedBox#25f26 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: <none>
    constraints: BoxConstraints(w=128.4, h=72.2)
    size: MISSING
    fit: scaleDown
    alignment: Alignment.center
    textDirection: ltr
    child: RenderSemanticsAnnotations#9f173 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: <none> (can use size)
        constraints: BoxConstraints(unconstrained)
        size: Size(0.0, 0.0)
        child: RenderImage#ff43f relayoutBoundary=up2 NEEDS-PAINT
            parentData: <none> (can use size)
            constraints: BoxConstraints(unconstrained)
            size: Size(0.0, 0.0)
            image: null
            alignment: Alignment.center
            invertColors: false
            filterQuality: low
RenderObject: RenderFittedBox#25f26 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: <none>
    constraints: BoxConstraints(w=128.4, h=72.2)
    size: MISSING
    fit: scaleDown
    alignment: Alignment.center
    textDirection: ltr
    child: RenderSemanticsAnnotations#9f173 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: <none> (can use size)
        constraints: BoxConstraints(unconstrained)
        size: Size(0.0, 0.0)
        child: RenderImage#ff43f relayoutBoundary=up2 NEEDS-PAINT
            parentData: <none> (can use size)
            constraints: BoxConstraints(unconstrained)
            size: Size(0.0, 0.0)
            image: null
            alignment: Alignment.center
            invertColors: false
            filterQuality: low
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderFittedBox#25f26
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1972 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Start
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Build
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Init Localization Delegate
I/flutter (10987): [🌎 Easy Localization] [DEBUG] Init provider

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 320 pos 12: 'width > 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    FittedBox FittedBox:file:///home/osama/projects/flutter/meet-mobile/lib/pages/home_page.dart:18:28

When the exception was thrown, this was the stack:
#2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio (package:flutter/src/rendering/box.dart:320:12)
#3      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2722:58)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#5      RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#6      RenderAspectRatio.performLayout (package:flutter/src/rendering/proxy_box.dart:576:14)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#8      RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#9      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:279:14)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#11     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#12     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#13     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:808:43)
#14     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903:32)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#16     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#17     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:434:14)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#19     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#20     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#21     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062:7)
#22     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#23     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#25     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#28     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#30     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434:11)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#32     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#35     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#38     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#41     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#47     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#50     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#53     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#56     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#59     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#61     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3714:13)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#63     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#66     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#67     _RenderTheaterMixin.performLayout (package:flutter/src/widgets/overlay.dart:884:15)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#69     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#72     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#75     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#77     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:569:11)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#79     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#82     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#85     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#88     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#91     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#94     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#96     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#97     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#98     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#99     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:581:43)
#100    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:608:12)
#101    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#102    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#103    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:310:14)
#104    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#105    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#106    RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:516:11)
#107    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:621:30)
#108    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#109    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#110    RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:279:14)
#111    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#112    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#113    RenderRotatedBox.performLayout (package:flutter/src/rendering/rotated_box.dart:89:14)
#114    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#115    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#116    RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2718:14)
#117    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#118    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#119    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#120    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434:11)
#121    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#122    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#123    RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:516:11)
#124    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:621:30)
#125    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#126    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#127    RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:279:14)
#128    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#129    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#130    RenderRotatedBox.performLayout (package:flutter/src/rendering/rotated_box.dart:89:14)
#131    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#132    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#133    RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2718:14)
#134    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#135    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#136    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#137    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#138    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#139    RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2718:14)
#140    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#141    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#142    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#143    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#144    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#145    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#146    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#147    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#148    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#149    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1434:11)
#150    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#151    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#152    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#153    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#154    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#155    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#156    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#157    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#158    RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:516:11)
#159    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:621:30)
#160    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#161    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#162    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:310:14)
#163    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#164    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#165    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#166    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#167    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#168    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#169    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#170    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#171    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#172    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:581:43)
#173    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:608:12)
#174    RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
#175    RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
#176    RenderView.performLayout (package:flutter/src/rendering/view.dart:195:14)
#177    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
#178    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
#179    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
#180    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
#181    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#182    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#183    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#184    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#185    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:978:7)
#189    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: RenderFittedBox#25f26 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: <none>
    constraints: BoxConstraints(w=128.4, h=72.2)
    size: MISSING
    fit: scaleDown
    alignment: Alignment.center
    textDirection: ltr
    child: RenderSemanticsAnnotations#9f173 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: <none> (can use size)
        constraints: BoxConstraints(unconstrained)
        size: Size(0.0, 0.0)
        child: RenderImage#ff43f relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: <none> (can use size)
            constraints: BoxConstraints(unconstrained)
            size: Size(0.0, 0.0)
            image: null
            alignment: Alignment.center
            invertColors: false
            filterQuality: low
RenderObject: RenderFittedBox#25f26 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: <none>
    constraints: BoxConstraints(w=128.4, h=72.2)
    size: MISSING
    fit: scaleDown
    alignment: Alignment.center
    textDirection: ltr
    child: RenderSemanticsAnnotations#9f173 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: <none> (can use size)
        constraints: BoxConstraints(unconstrained)
        size: Size(0.0, 0.0)
        child: RenderImage#ff43f relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: <none> (can use size)
            constraints: BoxConstraints(unconstrained)
            size: Size(0.0, 0.0)
            image: null
            alignment: Alignment.center
            invertColors: false
            filterQuality: low
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderFittedBox#25f26
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1972 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderFittedBox#25f26
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1972 pos 12: 'hasSize'
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════
D/EGL_emulation(10987): app_time_stats: avg=225.72ms min=104.12ms max=427.43ms count=5

════════ Exception caught by rendering library ═════════════════════════════════
Tried to paint a RenderObject reentrantly.
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════
D/EGL_emulation(10987): app_time_stats: avg=1836.72ms min=210.98ms max=5070.19ms count=3

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.9, on Ubuntu 22.04.3 LTS 6.5.0-15-generic, locale
    en_US.UTF-8)
    • Flutter version 3.16.9 on channel stable at
      /home/osama/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (11 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/osama/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /usr/local/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2023.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 77.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API
      34) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 22.04.3
      LTS 6.5.0-15-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome
      121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by PurplePolyhedron**
fix https://github.com/flutter/flutter/issues/135082 , fix https://github.com/flutter/flutter/issues/139539 , fix https://github.com/flutter/flutter/issues/142910

Before, `FittedBox` would throw when child size is zero, unless the constraint is tight and fit is not `BoxFit.scaleDown`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 1]
```diff
@@ -2729,18 +2729,23 @@ class RenderFittedBox extends RenderProxyBox {
...
-          size = constraints.constrain(unconstrainedSize);
-        case BoxFit.contain:
-        case BoxFit.cover:
-        case BoxFit.fill:
-        case BoxFit.fitHeight:
-        case BoxFit.fitWidth:
-        case BoxFit.none:
-          size = constraints.constrainSizeAndAttemptToPreserveAspectRatio(child!.size);
+      if (child!.size.isEmpty) {
+        size = constraints.biggest;
```
Comment (goderbauer) [inline packages/flutter/lib/src/rendering/proxy_box.dart:2733]: Our default is usually `constraints.smallest` for these cases (see also the else branch bellow). Was there a good reason to use biggest here? Or should this also be smallest?

**Review by goderbauer — COMMENTED** [review]
Thank you for the fix and sorry for the delay in reviewing it.

File: packages/flutter/lib/src/rendering/proxy_box.dart (hunk 1 above)
Comment (PurplePolyhedron) [reply packages/flutter/lib/src/rendering/proxy_box.dart:2733]: My bad, I made some mistake in previous testing and thought the default behaviour is `constraints.smallest`

Comment (PurplePolyhedron) [reply packages/flutter/lib/src/rendering/proxy_box.dart]: I've changed it to smallest. And I updated `computeDryLayout` to match `performLayout` since I forgot about `computeDryLayout` perviously.

**Review by goderbauer — APPROVED** [review]
LGTM!

File: packages/flutter/lib/src/rendering/proxy_box.dart [hunk 2]
```diff
@@ -2729,18 +2715,23 @@ class RenderFittedBox extends RenderProxyBox {
...
-          size = constraints.constrain(unconstrainedSize);
-        case BoxFit.contain:
-        case BoxFit.cover:
-        case BoxFit.fill:
-        case BoxFit.fitHeight:
-        case BoxFit.fitWidth:
-        case BoxFit.none:
-          size = constraints.constrainSizeAndAttemptToPreserveAspectRatio(child!.size);
+      if (child!.size.isEmpty) {
+        size = constraints.smallest;
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/rendering/proxy_box.dart:2719]: The assertion was in `BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio`. I think we should try to fix that method so it can handle an empty size as input?

Comment (PurplePolyhedron) [reply packages/flutter/lib/src/rendering/proxy_box.dart:2719]: I am not sure how it should behave when only one side of the target size is 0.  For example if `height` is finite while `width` is 0, Do you think `BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio` should trying to match the height(only constrain size since the aspect ratio is 0 and cannot be Preserved), or return `constraints.smallest` regardless(treat any zero size as empty)?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/rendering/proxy_box.dart:2719]: Yeah I think in your example the method should return `constrainSize(inputSize)`, instead of returning `smallest` and ignoring the input size.

The reason for that is I think returning `smallest` when the child size is empty feels like a special case, one that feels a bit artificial (if we do that then the documentation needs to be updated). 
Say the input `BoxConstraints` is loose and unbounded (i.e., `BoxConstraints()`), then `RenderFittedBox` always takes the same size as its child when the child size is not empty, so ideally we don't have the special case it when the child size is empty, and always return the child size regardless if it's empty.

**Comment by LongCatIsLooong** [comment]
@goderbauer would you like to take another look and see if the updated version makes sense to you?

**Review by goderbauer — APPROVED** [review]
Still LGTM

**Review by LongCatIsLooong — APPROVED** [review]
Thank you for contributing!
