### PR TITLE
Close CupertinoContextMenu overlay if the widget is disposed or a new route is pushed

### LINKED ISSUE #131471: [CupertinoContextMenu] Potential unremoved overlay entry
## Details
According to  https://github.com/flutter/flutter/blob/0ff68b8c610d54dd88585d0f97531208988f80b3/packages/flutter/lib/src/cupertino/context_menu.dart#L560C1-L583C1

`_lastOverlayEntry` is only removed when animation is dismissed or completed. 

What if  the overlayEntry is inserted, and then the `CupertinoContextMenu` is disposed and removed from widgets tree? So the entry will never be removed.

Temporary solution is add `_lastOverlayEntry?.remove()` to

https://github.com/flutter/flutter/blob/0ff68b8c610d54dd88585d0f97531208988f80b3/packages/flutter/lib/src/cupertino/context_menu.dart#L683C1-L687C4

But this is not enough, because there will be no animation, and it will be abrupt for it to suddenly disappear.

## Steps to reproduce

1. Add a `CupertinoContextMenu` to any visible widget.
2. Press it to insert the overlayEntry (the `_DecoyChild`) , while remove the `CupertinoContextMenu` from the widgets tree.
3. The entry never dismissed.

### LINKED ISSUE #169911: CupertinoContextMenu onTap gesture interferes with child widget with onTap GestureRecognizer
### Steps to reproduce

1. Tap on the widget for a bit longer than a "normal" tap, but not long enough to trigger the long press

### Expected results

Either the CupertinoContextMenu long press animation completes, or the child widget's onTap is triggered and the animation is cancelled

### Actual results

The child widget's onTap is triggered and the CupertinoContextMenu animation with the OverlayEntry remains 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final colorScheme = ColorScheme.fromSeed(seedColor: Colors.orange);
    return MaterialApp(
      theme: ThemeData(
        colorScheme: colorScheme,
        appBarTheme: AppBarTheme(backgroundColor: colorScheme.secondaryContainer),
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          title: Text('Home'),
        ),
        body: Center(
          child: CupertinoContextMenu(
            actions: [
              CupertinoContextMenuAction(
                child: Text('Test'),
              ),
            ],
            child: GestureDetector(
              onTap: () {
                Navigator.of(context).push(
                  MaterialPageRoute(builder: (context) => _OtherPage()),
                );
              },
              child: Container(
                color: Colors.orange,
                height: 100,
                width: 100,
              ),
            ),
          ),
        ),
      );
}

class _OtherPage extends StatelessWidget {
  const _OtherPage({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          title: Text('Other'),
        ),
      );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/e2869b2c-8fe6-4acd-9ce8-d5f23820762c

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.2, on macOS 15.5 24F74 darwin-arm64, locale en-IT) [408ms]
    • Flutter version 3.29.2 on channel stable at /Users/lortos/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c236373904 (3 months ago), 2025-03-13 16:17:06 -0400
    • Engine revision 18b71d647a
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [1,695ms]
    • Android SDK at /Users/lortos/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1) [776ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [104ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2) [103ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.4+-12422083-b607.1)

[✓] IntelliJ IDEA Community Edition (version 2024.3.5) [102ms]
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 83.0.4
    • Dart plugin version 243.26053.17

[✓] VS Code (version 1.100.2) [10ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (4 available) [6.1s]
    • iPhone 16 Pro (mobile)            • 91805BB8-7975-444F-BF08-00324D08B649 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-1 (simulator)
    • macOS (desktop)                   • macos                                • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Mac Designed for iPad (desktop)   • mac-designed-for-ipad                • darwin         • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)                      • chrome                               • web-javascript • Google Chrome 137.0.7151.55

[✓] Network resources [681ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by victorsanni**
Fixes [CupertinoContextMenu potential unremoved overlay entry](https://github.com/flutter/flutter/issues/131471)
Fixes [CupertinoContextMenu onTap gesture interferes with child widget with onTap GestureRecognizer](https://github.com/flutter/flutter/issues/169911)

<details>
<summary>Sample code</summary>

```dart

import 'dart:async';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

bool ctxMenuRemoved = false;

class ContextMenuApp extends StatelessWidget {
  const ContextMenuApp({super.key});

  @override
  Widget build(BuildContext context) {
    final colorScheme = ColorScheme.fromSeed(seedColor: Colors.orange);
    return MaterialApp(
      theme: ThemeData(
        colorScheme: colorScheme,
        appBarTheme:
            AppBarTheme(backgroundColor: colorScheme.secondaryContainer),
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          title: Text('Home'),
        ),
        body: Center(
          child: CupertinoContextMenu(
            actions: [
              CupertinoContextMenuAction(
                child: Text('Test'),
              ),
            ],
            child: GestureDetector(
              onTap: () {
                Navigator.of(context).push(
                  MaterialPageRoute(builder: (context) => _OtherPage()),
                );
              },
              child: Container(
                color: Colors.orange,
                height: 100,
                width: 100,
              ),
            ),
          ),
        ),
      );
}

class _OtherPage extends StatelessWidget {
  const _OtherPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Align(
        child: Builder(builder: (context) {
          return Listener(
            onPointerDown: (_) {
              Timer(const Duration(milliseconds: 480), () {
                ctxMenuRemoved = true;
                (context as Element).markNeedsBuild();
              });
            },
            child: ctxMenuRemoved
                ? const SizedBox()
                : CupertinoContextMenu(
                    actions: [
                      CupertinoContextMenuAction(
                        child: const Text('Action one'),
                        onPressed: () {},
                      ),
                    ],
                    child: Container(
                      height: 100,
                      width: 100,
                      color: Colors.black45,
                    ),
                  ),
          );
        }),
      ),
    );
  }
}


```

</details>

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/context_menu.dart [hunk 1]
```diff
@@ -488,6 +488,23 @@ class _CupertinoContextMenuState extends State<CupertinoContextMenu> with Ticker
     _route!.animation!.addStatusListener(_routeAnimationStatusListener);
   }
 
+  void _removeContextMenuDecoy() {
+    // Keep the decoy on the screen for one extra frame. We have to do this
+    // because _ContextMenuRoute renders its first frame offscreen.
+    // Otherwise there would be a visible flash when nothing is rendered for
+    // one frame.
+    SchedulerBinding.instance.addPostFrameCallback((Duration _) {
+      _closeContextMenu();
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/context_menu.dart]: Not strictly related to this PR, but should there be a `mounted` check here?

File: packages/flutter/test/cupertino/context_menu_test.dart [hunk 2]
```diff
@@ -1145,4 +1145,100 @@ void main() {
...
+    await tester.pump();
+    await tester.pump(const Duration(milliseconds: 300));
+    expect(find.text(page), findsNothing);
+
+    await tester.pump(const Duration(milliseconds: 300));
+    await gesture.up();
+
+    // Kickstart the route transition.
+    await tester.pump();
+    await tester.pump(const Duration(milliseconds: 300));
```
Comment (justinmc) [inline packages/flutter/test/cupertino/context_menu_test.dart:1193]: Is this duration dependent on the duration of the route transition? FYI I am working on figuring out a way to dynamically get this value in tests, see https://github.com/flutter/flutter/pull/165832#issuecomment-2923689858. Probably no action to take on this PR, but just a heads up.

**Review by justinmc — APPROVED** [review]
LGTM :+1:

File: packages/flutter/test/cupertino/context_menu_test.dart (hunk 2 above)
Comment (victorsanni) [reply packages/flutter/test/cupertino/context_menu_test.dart:1193]: No, but 👍
