### PR TITLE
Generate syntax for plugin registration that works both with and without null safety.

### LINKED ISSUE #109160: Building web without null safety fails in 3.3.0
## Steps to Reproduce

1. Create a flutter application without any null safe code and set the sdk constraints as `sdk: ">=2.11.0 <3.0.0"` to disable null safety features
2. Using Flutter 3.3.0 from the beta channel, run `flutter build web --release`
3. The build should fail

## Logs

Of special note below is use of an optional on `Registrar` in the web_plugin_registrant which causes an error since the requested Dart version doesn't support it. I believe this change was made in the following commit: https://github.com/flutter/flutter/commit/1af8cc118390f3b0e53164b150ccc69339e9329c

<details>
<summary>Logs</summary>

```
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Compiling lib/main.dart for the Web...                          
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
.dart_tool/flutter_build/572d7750549a8327067a38f83ec01c02/web_plugin_registrant.dart:31:38:
Error: Null safety features are disabled for this library.
void registerPlugins([final Registrar? pluginRegistrar]) {
                                     ^
Error: Compilation failed.

Compiling lib/main.dart for the Web...                             29.4s
Exception: Failed to compile application for the Web.


Build failed :|
Failed to build for Web
```

```
[✓] Flutter (Channel beta, 3.3.0-0.2.pre, on macOS 12.4 21F79 darwin-arm, locale en-CA)
    • Flutter version 3.3.0-0.2.pre on channel beta at /Users/matthewpatience/fluttersdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7ac27ac8e6 (6 days ago), 2022-08-02 14:35:08 -0700
    • Engine revision d1e7dc18bf
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/matthewpatience/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by eyebrowsoffire**
Add a language header to specify we can use null safety in the generated plugin registrant file.

This fixes https://github.com/flutter/flutter/issues/109160

### CODE REVIEW

File: packages/flutter_tools/lib/src/flutter_plugins.dart [hunk 1]
```diff
@@ -574,8 +574,11 @@ import 'package:{{name}}/{{file}}';
 {{/methodChannelPlugins}}
 import 'package:flutter_web_plugins/flutter_web_plugins.dart';
 
-void registerPlugins([final Registrar? pluginRegistrar]) {
-  final Registrar registrar = pluginRegistrar ?? webPluginRegistrar;
+void registerPlugins() {
+  registerPluginsWithRegistrar(webPluginRegistrar);
+}
+
+void registerPluginsWithRegistrar(final Registrar registrar) {
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/flutter_plugins.dart:581]: Do we know if we're building in null safe mode or not when we process this template? If we do, can we conditionally include/exclude the `?` depending on the mode?

Comment (eyebrowsoffire) [reply packages/flutter_tools/lib/src/flutter_plugins.dart:581]: I couldn't find a simple and robust way to do so. Whether or not null safety is used is dependent on the environment.sdk range specified in the pubspec file, which is how I actually exercise this path for the unit test. This seems fine for a unit test, but it feels flimsy for the actual codegen that end users will run in production. Is it important that we do it as a single function call with an optional parameter rather than what I've done here?

File: packages/flutter_tools/test/integration.shard/web_plugin_registrant_test.dart [hunk 2]
```diff
@@ -255,32 +306,76 @@ Future<void> _createProject(Directory dir, List<String> createArgs) async {
...
-    final String line = lines[i];
-    if (line.startsWith('dependencies:')) {
-      lines.insert(
-          i + 1,
-          '  $package: ${version ?? '\n'
-              '    path: $path'}');
-      break;
+PubspecEditor _composeEditors(Iterable<PubspecEditor> editors) {
+  void editor(List<String> lines) {
+    for (final PubspecEditor e in editors) {
```
Comment (yjbanov) [inline packages/flutter_tools/test/integration.shard/web_plugin_registrant_test.dart:374]: nit: avoid abbreviations: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-abbreviations

File: packages/flutter_tools/lib/src/flutter_plugins.dart [hunk 3]
```diff
@@ -567,13 +567,15 @@ const String _dartPluginRegistryTemplate = '''
...
 
+// @dart = 2.13
 // ignore_for_file: type=lint
 
 {{#methodChannelPlugins}}
 import 'package:{{name}}/{{file}}';
 {{/methodChannelPlugins}}
 import 'package:flutter_web_plugins/flutter_web_plugins.dart';
 
+
```
Comment (yjbanov) [inline packages/flutter_tools/lib/src/flutter_plugins.dart:578]: nit: undo this new line?

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by eyebrowsoffire** [comment]
Blocked by https://github.com/flutter/flutter/issues/109797 currently
