### PR TITLE
Fix race condition causing crash when interacting with an animating scrollable

### LINKED ISSUE #14452: Dragging a list that is currently handling an animateTo animation throws exception
## Steps to Reproduce

The end goal is to create a scrolling list that automatically "snaps" to a given location based on the actual scroll position at which the user stops scrolling. This may not be the best solution (I'm new to Flutter), but here's the process by which I get the crash:

Wrap a ListView within a NotificationListener. Upon receiving a `UserScrollNotification` with `ScrollDirection.idle`, call the ScrollController's `animateTo()` method to scroll to another location (in the example here, I arbitrarily scroll to 10000.0 pixels).

### Sample code
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Scroller issue',
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final _controller = new ScrollController();

  bool _didGetNotification(ScrollNotification notification) {
    if (notification is UserScrollNotification) {
      if (notification.direction.toString() == "ScrollDirection.idle") {
        // We've stopped scrolling... now animate automatically to the 10000-pixel spot
        _controller.animateTo(10000.0, duration: const Duration(seconds: 2), curve: Curves.elasticOut);

        /* Above works great... unless the user tries to interact with the list WHILE it's
        // animating. In this case, you end up with:
        **********************************************************************************
        Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart':
          Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
        ********************************************************************************** */
      }
    }
    return true;
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new NotificationListener(
        onNotification: _didGetNotification,
        child: new ListView.builder(
          padding: new EdgeInsets.all(8.0),
          controller: _controller,
          itemExtent: 60.0,
          itemBuilder: (BuildContext context, int index) {
            return new Text('Item No. $index');
          },
        ),
      ),
    );
  }
}
```

It works great as long as the user only interacts with the ListView when it is idle, but if the user attempts to scroll/drag/touch the list _during_ the animateTo() process, the following exception is raised within the Flutter Scrollable package:

```
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
```

After this, the ListView becomes unresponsive.

I'm sure there's a better way to achieve what I'm trying to do, but the platform itself doesn't seem to recover from this. Figured I'd make a note of it. 

Thanks!

## Logs

Run your application with `flutter run` and attach all the log output.

```
    CADisplay.name = LCD;
    CADisplay.deviceName = PurpleMain;
    CADisplay.seed = 1;
    tags = 0;
    currentMode = <FBSDisplayMode: 0x604000097430; 375x667@2x (750x1334/2) 60Hz sRGB SDR>;
    safeOverscanRatio = {0.89999997615814209, 0.89999997615814209};
    nativeCenter = {375, 667};
    pixelSize = {750, 1334};
    bounds = {{0, 0}, {375, 667}};
    CADisplay = <CADisplay:LCD PurpleMain>;
}
Syncing files to device iPhone 6s...                  1.9s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone 6s is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 467 pos 12: '_hold == null':
is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      ScrollableState._handleDragStart (package:flutter/src/widgets/scrollable.dart:467:12)
#3      DragGestureRecognizer.acceptGesture.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:169:54)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#5      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:169:9)
#6      GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:250:25)
#7      GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:231:31)
(elided 4 frames from class _AssertionError and package dart:async)

Handler: onStart
Recognizer:
VerticalDragGestureRecognizer#6eafd
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 472 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 455 pos 12: '_drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 464 pos 12: '_drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_hold == null || _drag == null': is not true.

```

Run `flutter analyze` and attach any output of that command also.

```
Analyzing /Users/mfahy/Apps/list_view_attempts...
No issues found!
Ran in 6.5s
```

## Flutter Doctor
```
[  +21 ms] [/Users/mfahy/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/alpha
[        ] [/Users/mfahy/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] alpha
[        ] [/Users/mfahy/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/mfahy/flutter/] git log -n 1 --pretty=format:%H
[  +28 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 2e449f06f0a3be076e336ad6b30b0e9ec99dbdfe
[        ] [/Users/mfahy/flutter/] git log -n 1 --pretty=format:%ar
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 5 days ago
[        ] [/Users/mfahy/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +44 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.0.21-0-g2e449f06f
[ +473 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[+1263 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.0
[ +452 ms] [✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-US, channel alpha)
[   +1 ms]     • Flutter version 0.0.21 at /Users/mfahy/flutter
[        ]     • Framework revision 2e449f06f0 (5 days ago), 2018-01-29 14:26:51 -0800
[        ]     • Engine revision 6921873c71
[        ]     • Tools Dart version 2.0.0-dev.16.0
[        ]     • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a
[ +130 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[ +218 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.0
[  +98 ms] java -version
[  +87 ms] [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[        ]     • Android SDK at /Users/mfahy/Library/Android/sdk
[        ]     • Android NDK location not configured (optional; useful for native profiling support)
[        ]     • Platform android-27, build-tools 27.0.3
[        ]     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
[+1189 ms] DevToolsSecurity -status
[  +49 ms] Developer mode is currently enabled.
[        ] python -c import six
[ +126 ms] idevice_id -h
[  +10 ms] idevice_id -h
[   +9 ms] idevice_id -l
[  +28 ms] 5a62f0e8de345b9794b9a61c9bfcd02026c68a86
[   +1 ms] idevicename
[  +44 ms] ios-deploy --version
[  +54 ms] ios-deploy --version
[  +16 ms] 1.9.2
[   +1 ms] ios-deploy --version
[  +33 ms] ios-deploy --version
[  +21 ms] 1.9.2
[   +2 ms] pod --version
[ +905 ms] pod --version
[ +605 ms] 1.3.1
[   +2 ms] pod --version
[ +533 ms] 1.3.1
[   +1 ms] [-] iOS toolchain - develop for iOS devices (Xcode 9.2)
[        ]     • Xcode at /Applications/Xcode.app/Contents/Developer
[        ]     • Xcode 9.2, Build version 9C40b
[        ]     ✗ Verify that all connected devices have been paired with this computer in Xcode.
                 If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
                 To update, run:
                   brew uninstall --ignore-dependencies libimobiledevice
                   brew install --HEAD libimobiledevice
                   brew install ideviceinstaller
[        ]     • ios-deploy 1.9.2
[        ]     • CocoaPods version 1.3.1
[   +2 ms] [✓] Android Studio (version 3.0)
[        ]     • Android Studio at /Applications/Android Studio.app/Contents
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
[   +6 ms] /usr/bin/defaults read /Applications/IntelliJ IDEA.app/Contents/Info CFBundleShortVersionString
[ +249 ms] Exit code 0 from: /usr/bin/defaults read /Applications/IntelliJ IDEA.app/Contents/Info CFBundleShortVersionString
[        ] 2017.3.4
[  +79 ms] [✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
[        ]     • Flutter plugin version 21.2.3
[        ]     • Dart plugin version 173.4548.30
[   +4 ms] /Users/mfahy/Library/Android/sdk/platform-tools/adb devices -l
[  +17 ms] Exit code 0 from: /Users/mfahy/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +8 ms] idevice_id -h
[  +82 ms] which ideviceinstaller
[   +5 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] which iproxy
[   +4 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[ +218 ms] [✓] Connected devices
[        ]     • ViPhone 6S • 5a62f0e8de345b9794b9a61c9bfcd02026c68a86 • ios • iOS 11.3
[        ]     • iPhone 6s  • 6F36E8FD-E570-453E-B943-8243E4FAEDD6     • ios • iOS 11.2 (simulator)
[  +21 ms] "flutter doctor" took 6,972ms.
[  +42 ms] ensureAnalyticsSent: 38ms
[   +2 ms] exiting with code 0
```

Hope this helps! Thanks!

### LINKED ISSUE #163297: Assertion Error using CustomScrollView with CupertinoSliverNavigationBar (Flutter 3.29)
### Steps to reproduce

When scrolling on the CupertinoSliverNavigationBar, an assertion error occurs randomly. The issue arises after performing multiple scroll gestures on the navigation bar in both directions. The following assertion errors are thrown:

```dart
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 875 pos 12: '_hold == null': is not true.
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 880 pos 12: '_hold == null || _drag == null': is not true.
```

Steps to Reproduce:

1. Run the provided code.
2. Scroll up or down on the navigation bar multiple times.
3. Observe the assertion errors in the debug console.
4. Attempt to scroll again—scrolling is now completely broken.

Code:
```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: Scaffold(
        body: CustomScrollView(
          slivers: [
            CupertinoSliverNavigationBar(
                largeTitle: Text("Example"),
            ),
          ],
        ),
      ),
    );
  }
}
```

### Expected results

Regardless of the scrolling movement, no errors should be thrown.

### Actual results

Assertion errors occur, and the scrolling state becomes unresponsive.

### Code sample

<details open><summary>Example</summary>

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: Scaffold(
        body: CustomScrollView(
          slivers: [
            CupertinoSliverNavigationBar(
                largeTitle: Text("Example"),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/0a181cef-1cfd-4276-8e6c-620d695cc5b8

</details>

### Logs

<details open><summary>Logs</summary>

```console
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 875 pos 12: '_hold == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragStart (package:flutter/src/widgets/scrollable.dart:875:12)
#3      DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:849:53)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:357:24)
#5      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:849:7)
#6      DragGestureRecognizer._checkDrag (package:flutter/src/gestures/monodrag.dart:815:5)
#7      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:743:7)
#8      GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:275:25)
#9      GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:255:31)
(elided 4 frames from class _AssertionError and dart:async)
Handler: "onStart"
Recognizer: VerticalDragGestureRecognizer#42451
  start behavior: start
====================================================================================================

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 880 pos 12: '_hold == null || _drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:880:12)
#3      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:868:55)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:357:24)
#5      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:868:7)
#6      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:714:11)
#7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:97:12)
#8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#9      _LinkedHashMapMixin.forEach (dart:_compact_hash:763:13)
#10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:131:7)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:530:19)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:499:22)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:460:11)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:437:7)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:394:5)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:341:7)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:308:9)
#19     _invoke1 (dart:ui/hooks.dart:332:13)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:451:7)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:267:31)
(elided 2 frames from class _AssertionError)
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#42451
  start behavior: start
====================================================================================================
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.3 24D60 darwin-arm64, locale de-DE) [1.836ms]
    • Flutter version 3.29.0 on channel stable at /Users/***
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35c388afb5 (4 days ago), 2025-02-10 12:48:41 -0800
    • Engine revision f73bfc4522
    • Dart version 3.7.0
    • DevTools version 2.42.2
```

</details>

### PR DESCRIPTION
**Pull request by victorsanni**
Fix https://github.com/flutter/flutter/issues/163297
Fix https://github.com/flutter/flutter/issues/14452

Partial patch: https://github.com/flutter/flutter/pull/37267

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 1]
```diff
@@ -861,7 +861,10 @@ class ScrollableState extends State<Scrollable>
 
   void _handleDragDown(DragDownDetails details) {
     assert(_drag == null);
-    assert(_hold == null);
+    // _hold might be non-null if the scroll position is currently animating.
+    if (_hold != null) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scrollable.dart:865]: This should be null. Do we have a scenario where it crashes here?

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 2]
```diff
@@ -872,18 +875,27 @@ class ScrollableState extends State<Scrollable>
     assert(_drag == null);
     _drag = position.drag(details, _disposeDrag);
     assert(_drag != null);
-    assert(_hold == null);
+    // _hold might be non-null if the scroll position is currently animating.
+    if (_hold != null) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scrollable.dart:879]: I thought `_handleDragStart` was the only place we needed to correct this? Since the race condition is (as I understand it)...

(1) _handleDragDown --> code path that eventually disposes of _hold
(2) _handleDragStart --> code path that asserts _hold is null

These methods can be called either simultaneously based on the drag start behavior, or in very quick succession, leading to the crash if the second code path reaches that assertion before the first code path finishes.

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 3]
```diff
@@ -872,18 +875,27 @@ class ScrollableState extends State<Scrollable>
...
+    }
   }
 
   void _handleDragUpdate(DragUpdateDetails details) {
+    // _hold might be non-null if the scroll position is currently animating.
+    if (_hold != null) {
+      _disposeHold();
+    }
     // _drag might be null if the drag activity ended and called _disposeDrag.
-    assert(_hold == null || _drag == null);
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scrollable.dart:880]: Why remove this assertion? Do we have a crash here when the one in `_handleDragStart` is addressed? This assertion is not just about the _hold, which gives me some pause here.

File: packages/flutter/lib/src/widgets/scrollable.dart [hunk 4]
```diff
@@ -872,18 +875,27 @@ class ScrollableState extends State<Scrollable>
...
     _drag?.update(details);
   }
 
   void _handleDragEnd(DragEndDetails details) {
+    // _hold might be non-null if the scroll position is currently animating.
+    if (_hold != null) {
+      _disposeHold();
+    }
     // _drag might be null if the drag activity ended and called _disposeDrag.
-    assert(_hold == null || _drag == null);
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/scrollable.dart:886]: Same here

**Review by Piinks — COMMENTED** [review]
Google testing failures are unrelated. 👍

File: packages/flutter/lib/src/widgets/scrollable.dart (hunk 1 above)
Comment (chunhtai) [reply packages/flutter/lib/src/widgets/scrollable.dart:865]: @victorsanni , I am also curious what the sequence of event that causes this to be none null. My suspicion is that the previous event was cancelled before starting a new one, but would be good to have confirmation.

File: packages/flutter/lib/src/widgets/scrollable.dart (hunk 2 above)
Comment (victorsanni) [reply packages/flutter/lib/src/widgets/scrollable.dart:879]: Yes, this is correct. My mistake.

**Comment by RubenNunez** [comment]
`'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 880 pos 12: '_hold == null || _drag == null' is not true.`

I'm also facing this issue, which makes working with a simple setup consisting of a [CustomScrollView] containing slivers: [CupertinoSliverNavigationBar, SliverList] nearly impossible in Flutter 3.29.0.

Will it be addressed in a minor release? 3.29.(?) 

Thank you

File: packages/flutter/test/widgets/scrollable_animations_test.dart [hunk 5]
```diff
@@ -103,6 +104,80 @@ void main() {
       reason: 'Expected an animation.',
     );
   });
+
+  testWidgets('HoldActivity can interrupt ScrollPosition.animateTo', (WidgetTester tester) async {
```
Comment (victorsanni) [inline packages/flutter/test/widgets/scrollable_animations_test.dart:108]: I can't seem to make the tests fail on master/ reproduce the crash with the test framework.

Comment (victorsanni) [reply packages/flutter/test/widgets/scrollable_animations_test.dart:108]: Fixed thanks to help from @Renzo-Olivares! Just needed to wrap the scroll view in a `NotificationListener` and call position.animateTo when the scroll view is interacted with.

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by bobekos** [comment]
@victorsanni 
Great to see that this is fixed. Any chance we can cherry pick this into the next HotFix version?
