### PR TITLE
Fixes `DragTarget` crash if `Draggable.data` is `null`

### LINKED ISSUE #84816: DragTarget crash  if Draggable data field is not set, but data is not required.
### DragTarget crashes if Draggable data field is not set, but data is not required. 

image

Specifically the issue is in `didDrop` in `drag_target.dart` which asserts `data` is not null:
image

### Suggestion
Make `data` field required.

### PR DESCRIPTION
**Pull request by ValentinVignal**
Makes the `data` parameter of `Draggable` non-nullable.

Fixes https://github.com/flutter/flutter/issues/84816

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by ValentinVignal** [comment]
@Piinks @chinmoy12c I created the PR to continue the discussion from https://github.com/flutter/flutter/issues/84816

I made `Draggable.data` non nullable and dummy fixed the lints for now. Should I do anything else or should I make the code support `null`?

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 1]
```diff
@@ -18,7 +18,7 @@ import 'view.dart';
 /// Signature for determining whether the given data will be accepted by a [DragTarget].
 ///
 /// Used by [DragTarget.onWillAccept].
-typedef DragTargetWillAccept<T> = bool Function(T? data);
+typedef DragTargetWillAccept<T> = bool Function(T data);
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/drag_target.dart:21]: This would break customers by requiring them to change the function signature and then they would need to update their implementations to handle when data is null.

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 2]
```diff
@@ -38,7 +38,7 @@ typedef DragTargetAcceptWithDetails<T> = void Function(DragTargetDetails<T> deta
 /// this [DragTarget] and that will not be accepted by the [DragTarget].
 ///
 /// Used by [DragTarget.builder].
-typedef DragTargetBuilder<T> = Widget Function(BuildContext context, List<T?> candidateData, List<dynamic> rejectedData);
+typedef DragTargetBuilder<T> = Widget Function(BuildContext context, List<T> candidateData, List<dynamic> rejectedData);
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/drag_target.dart:41]: Same here, this would break customers by requiring them to change the function signature and then they would need to update their implementations to handle when candidateData is null.

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 3]
```diff
@@ -62,7 +62,7 @@ typedef DragEndCallback = void Function(DraggableDetails details);
 /// Signature for when a [Draggable] leaves a [DragTarget].
 ///
 /// Used by [DragTarget.onLeave].
-typedef DragTargetLeave<T> = void Function(T? data);
+typedef DragTargetLeave<T> = void Function(T data);
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/drag_target.dart:65]: Same here

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 4]
```diff
@@ -164,7 +164,7 @@ class Draggable<T extends Object> extends StatefulWidget {
     super.key,
     required this.child,
     required this.feedback,
-    this.data,
+    required this.data,
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/drag_target.dart:167]: Similarly here..

**Review by Piinks — COMMENTED** [review]
This looks like a pretty big breaking change. Can we address the crash in DragTarget without changing data?  It looks like it crashes because of a bad assumption it will not be null, can we check for that and change the code path where the crash occurs?

**Comment by ValentinVignal** [comment]
@Piinks I'm okay to change the code to not make `data` a `required T` but a `T?`. That would also induce some breaking changes though. 

For example

https://github.com/flutter/flutter/blob/cd3aeef3a826463eac8d9e09a5b504bea3cd7011/packages/flutter/lib/src/widgets/drag_target.dart#L742-L751

would become something like

```dart
widget.onAccept?.call(avatar.data as T?); 
widget.onAcceptWithDetails?.call(DragTargetDetails<T?>(data: avatar.data as T?, offset: avatar._lastOffset!)); 
```

which will force me to change the signature of `onAccept` and `onAcceptWithDetails`.

Also, I might need to change `DragTargetDetails` to make its field `data` nullable and non-required.

Are you fine with it or do you see a better approach?

**Review by Piinks — COMMENTED** [review]
I don't think that we'd be able to land a change that makes it nullable, since all customers will need to change their function signature and then add handling for when it is null.

I am not sure I understand the issue this is trying to resolve, can you speak more to that? Maybe from there we can find a way to make a non breaking-change.

**Comment by ValentinVignal** [comment]
The issue is that `Draggable<T>` accepts a nullable/non-required `T? data`:

https://github.com/flutter/flutter/blob/c67e6df16bcbb904b5a820e574b49caeafeb0422/packages/flutter/lib/src/widgets/drag_target.dart#L169-L193

So `data` can be `null`.

But `DragTarget` assumes `data` is never `null` and uses `data! as T`. For example in `didDrop`: 

https://github.com/flutter/flutter/blob/c67e6df16bcbb904b5a820e574b49caeafeb0422/packages/flutter/lib/src/widgets/drag_target.dart#L742-L752

which throws a `Null check operator used on a null value` exception when `data` is actually `null`.

---

An alternative which could dodge breaking changes would be to do something like:

```dart
if (avatar.data != null) {
  widget.onAccept?.call(avatar.data! as T); 
  widget.onAcceptWithDetails?.call(DragTargetDetails<T>(data: avatar.data! as T, offset: avatar._lastOffset!));
}
```

It would not require us to change any fucntion signature.

What do you think?

**Comment by Piinks** [comment]
> It would not require us to change any function signature.

That sounds reasonable to me. :) Thanks!

**Comment by ValentinVignal** [comment]
@Piinks What do you think of [fix: Don't call .data! when it is null](https://github.com/flutter/flutter/pull/133136/commits/c1a2b42bba2ccde8bc3ab21c33e945a32e2e583d) ?

(Sorry I forced pushed, it was simpler than reverting my changes that were conflicting with `main`)

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 5]
```diff
@@ -713,6 +713,7 @@ class _DragTargetState<T extends Object> extends State<DragTarget<T>> {
                                     (widget.onWillAccept != null &&
                                     widget.onWillAccept!(avatar.data as T?)) ||
                                     (widget.onWillAcceptWithDetails != null &&
+                                    avatar.data != null &&
                                     widget.onWillAcceptWithDetails!(DragTargetDetails<T>(data: avatar.data! as T, offset: avatar._lastOffset!)));
```
Comment (ValentinVignal) [inline packages/flutter/lib/src/widgets/drag_target.dart:717]: I thought of doing the same check of `onWillAccept` for consistency

```suggestion
                                    (widget.onWillAccept != null &&
                                    avatar.data != null &&
                                    widget.onWillAccept!(avatar.data as T?)) ||
                                    (widget.onWillAcceptWithDetails != null &&
                                    avatar.data != null &&
                                    widget.onWillAcceptWithDetails!(DragTargetDetails<T>(data: avatar.data! as T, offset: avatar._lastOffset!)));
```

But doing so would force me to update this test: 

https://github.com/flutter/flutter/blob/127c76b91bef46c6baffaaee8873870c3054ea02/packages/flutter/test/widgets/draggable_test.dart#L3051-L3092

The last line would become:

```diff
-    expect(isReceiveNullDataForCheck, true);
+    expect(isReceiveNullDataForCheck, false); 
```

**Comment by ValentinVignal** [comment]
@Piinks is there something else I should do on this PR or does it look good to you ?

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 6]
```diff
@@ -747,12 +748,14 @@ class _DragTargetState<T extends Object> extends State<DragTarget<T>> {
...
-    widget.onAcceptWithDetails?.call(DragTargetDetails<T>(data: avatar.data! as T, offset: avatar._lastOffset!));
+    if (avatar.data != null)  {
+      widget.onAccept?.call(avatar.data! as T);
+      widget.onAcceptWithDetails?.call(DragTargetDetails<T>(data: avatar.data! as T, offset: avatar._lastOffset!));
+    }
   }
 
   void didMove(_DragAvatar<Object> avatar) {
-    if (!mounted) {
+    if (!mounted || avatar.data == null) {
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/drag_target.dart:758]: Why this change here? Is it covered by a test?

File: packages/flutter/lib/src/widgets/drag_target.dart (hunk 5 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/drag_target.dart:717]: I traced that test back to https://github.com/flutter/flutter/pull/72512

From your suggested code above:
```dart
// ...
avatar.data != null &&
widget.onWillAccept!(avatar.data as T?)) ||
// ...
```

^ This makes me wonder why would it then be cast as nullable `T?` if it is not null?

Having data be nullable appears to be intentional for onWillAccept, but that is being deprecated in https://github.com/flutter/flutter/pull/133691 so I think it makes sense to focus this change on onWillAcceptWithDetails.

**Comment by Piinks** [comment]
> is there something else I should do on this PR or does it look good to you ?

This is still marked as a draft, can you mark it ready for review? :)

File: packages/flutter/lib/src/widgets/drag_target.dart (hunk 6 above)
Comment (ValentinVignal) [reply packages/flutter/lib/src/widgets/drag_target.dart:752]: Same as in `didDrop`, `avatar.data` can be `null` so it cannot be blindly casted as `avatar.data! as T`

I added a test in [test: Add a test to verify onMove is not called when data is null](https://github.com/flutter/flutter/pull/133136/commits/8ad5dc832f977be1cbc6033d120fc1ec8f238c60) to cover this change

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 7]
```diff
@@ -741,12 +742,14 @@ class _DragTargetState<T extends Object> extends State<DragTarget<T>> {
     setState(() {
       _candidateAvatars.remove(avatar);
     });
-    widget.onAccept?.call(avatar.data! as T);
-    widget.onAcceptWithDetails?.call(DragTargetDetails<T>(data: avatar.data! as T, offset: avatar._lastOffset!));
+    if (avatar.data != null)  {
+      widget.onAccept?.call(avatar.data! as T);
+      widget.onAcceptWithDetails?.call(DragTargetDetails<T>(data: avatar.data! as T, offset: avatar._lastOffset!));
+    }
```
Comment (chinmoy12c) [inline packages/flutter/lib/src/widgets/drag_target.dart:748]: IMO this particular change has the potential to cause some bugs as well as some frustration during debugging code. Imagine you have a function A which you have defined inside these callbacks that are expected to be triggered when a Draggable is accepted. Now what this will do is entirely skip that trigger if your data is null. As a developer, it would be very difficult to pinpoint why this is exactly happening because it will not show any "info"/"warning" that these callbacks have not been triggered "because" data was null.

What are your views on this @Piinks ?

Comment (ValentinVignal) [reply packages/flutter/lib/src/widgets/drag_target.dart:748]: @chinmoy12c For what it's worth, this change won't _"break"_ anything.
If this is merged as it is, `onAccept` and `onAcceptWithDetails` won't be called if `data` is `null`. And you might be right, it might not be the expected behavior.
However, as of today, it crashes when `data` is `null`, and therefore, `onAccept` and `onAcceptWithDetails` won't be called either.

So this _"will not make things worse"_. If we want to call `onAccept` and `onAcceptWithDetails` when `data` is `null`, I would have to change the method signatures and this would be a breaking change.

**Comment by ValentinVignal** [comment]
@Piinks Do you have any more feedback on this PR?

File: packages/flutter/lib/src/widgets/drag_target.dart (hunk 7 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/drag_target.dart:748]: > will not make things worse

I think embracing the yak shave is best in this case (https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#lazy-programming)
In the linked PR (https://github.com/flutter/flutter/pull/133691) we're going to see if we can fix this inconsistency in the API

Comment (Piinks) [reply packages/flutter/lib/src/widgets/drag_target.dart:748]: Can you add documentation to the onAccept callback that mentions it will not be called if `data` null?
Then the `*WithDetails` variants can be called regardless of data being null once https://github.com/flutter/flutter/pull/133691 is finished.

Comment (ValentinVignal) [reply packages/flutter/lib/src/widgets/drag_target.dart:750]: Sure, I added a sentence in [doc: Detail that onWillAccept and onWillAcceptWithDetails won't be called if data is null](https://github.com/flutter/flutter/pull/133136/commits/17581cc2b43c0bffa4c2cf1dcd112e2dee10605d)

**Comment by chinmoy12c** [comment]
Hey @Piinks, found a similar issue with `onMove` as well. Apparently, `onMove` also treats `data` as non null
```
widget.onMove?.call(DragTargetDetails<T>(data: avatar.data! as T, offset: avatar._lastOffset!));
```

This also seems to be a part of the code since a long time, which makes me wonder if changing `DragTargetDetails` as discussed [here](https://github.com/flutter/flutter/pull/133691#pullrequestreview-1668720955) would be a good idea or not 🤔 . For the newer callbacks these changes would not be breaking too many code bases since they are new but `onMove` might pose a big breaking problem 🥲.

File: packages/flutter/test/widgets/draggable_test.dart [hunk 8]
```diff
@@ -2392,6 +2433,68 @@ void main() {
     expect(find.text('Target'), findsOneWidget);
   });
 
+  testWidgetsWithLeakTracking('Drag and drop - onAccept no called if dropped with null data', (WidgetTester tester) async {
```
Comment (chinmoy12c) [inline packages/flutter/test/widgets/draggable_test.dart:2436]: `onAccept no called` -> `onAccept is not called`

File: packages/flutter/lib/src/widgets/drag_target.dart [hunk 9]
```diff
@@ -741,12 +744,14 @@ class _DragTargetState<T extends Object> extends State<DragTarget<T>> {
     setState(() {
       _candidateAvatars.remove(avatar);
     });
-    widget.onAccept?.call(avatar.data! as T);
-    widget.onAcceptWithDetails?.call(DragTargetDetails<T>(data: avatar.data! as T, offset: avatar._lastOffset!));
+    if (avatar.data != null)  {
+      widget.onAccept?.call(avatar.data! as T);
+      widget.onAcceptWithDetails?.call(DragTargetDetails<T>(data: avatar.data! as T, offset: avatar._lastOffset!));
```
Comment (chinmoy12c) [inline packages/flutter/lib/src/widgets/drag_target.dart:749]: This should not be included inside the `if` clause since we're planning to make `data` nullable in the newer API.

**Review by chinmoy12c — COMMENTED** [review]
We should also add the line saying that this method will not be called if `data` is null to `onMove`.

File: packages/flutter/lib/src/widgets/drag_target.dart (hunk 9 above)
Comment (ValentinVignal) [reply packages/flutter/lib/src/widgets/drag_target.dart:749]: If `data` becomes `nullable` in the new API, then yes it can be moved out of the `if`. But right now, `data!` would crash if `data` is `null`. So it should remain inside the `if` as long as `data` of `onAcceptWithDetails` is not nullable?

File: packages/flutter/test/widgets/draggable_test.dart (hunk 8 above)
Comment (ValentinVignal) [reply packages/flutter/test/widgets/draggable_test.dart]: Ooops, sorry about that. I changed it in [test: Fix test description](https://github.com/flutter/flutter/pull/133136/commits/41f065a95b90aff07b5b6f9f91289c6f14b894fe)

**Comment by Piinks** [comment]
> Hey @Piinks, found a similar issue with `onMove` as well. Apparently, `onMove` also treats `data` as non null
> 
> ```
> widget.onMove?.call(DragTargetDetails<T>(data: avatar.data! as T, offset: avatar._lastOffset!));
> ```
> 
> This also seems to be a part of the code since a long time, which makes me wonder if changing `DragTargetDetails` as discussed [here](https://github.com/flutter/flutter/pull/133691#pullrequestreview-1668720955) would be a good idea or not 🤔 . For the newer callbacks these changes would not be breaking too many code bases since they are new but `onMove` might pose a big breaking problem 🥲.

Yeah, this is definitely tricky. One change over a another could have massive implications as far as breaking existing code.

For this PR, AFAICT right now this is pending https://github.com/flutter/flutter/pull/136413 and https://github.com/flutter/flutter/pull/133691

**Comment by ValentinVignal** [comment]
> For this PR, AFAICT right now this is pending #136413 and #133691

Are you saying this PR should wait for #136413 and #133691? Or #136413 and #133691 should wait for this PR?

**Comment by Piinks** [comment]
I think this PR should wait since it affects how those callbacks are called. Once we settle on how those callbacks might change we can update appropriately here.

**Comment by Piinks** [comment]
After investigating, https://github.com/flutter/flutter/pull/136413 is currently blocked, so I think we can land this now ahead of it.

**Comment by Piinks** [comment]
@ValentinVignal can you rebase this PR with the tip of tree so we can finally merge it? Thanks for your patience while we looked into the related API change!

**Comment by ValentinVignal** [comment]
Thanks for the update @Piinks . I merged `master` in my branch as it was easier than a rebase. Tell me if it is and issue, if it is, I'll work on rebasing it

**Comment by Piinks** [comment]
Looks like merging went just fine! :)

**Review by Piinks — APPROVED** [review]
LGTM

**Review by MitchellGoodwin — APPROVED** [review]
LGTM
