### PR TITLE
Always relies on floatingLabelStyle when FloatingLabelBehavior.always

### LINKED ISSUE #147231: TextField labelText doesn't use floatingLabelStyle when unfocused
### Steps to reproduce

Hello,

I've been trying to force my TextField to always use a floating label, by setting `InputDecoration`'s `floatingLabelBehavior` to `FloatingLabelBehavior.always`.

However, when the field is not focused, or is empty, `labelStyle` is used.
By digging through the code, I found this [line](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/input_decorator.dart#L2160C1-L2162C26) in `InputDecorator`.

Looking at the definition of `_labelShouldWithdraw` explains why I get this behavior. I then tried to set the same style for both `labelStyle` and `floatingLabelStyle`, but there is a very small animation when I focus/unfocus the text field.

By using `FloatingLabelBehavior.always`, I expected the label to stick to its position no matter in which state the `TextField` was.
Have I missed something?

### Expected results

The label always stays in place, only applying `floatingLabelStyle`.

### Actual results

The label alternates between `floatingLabelStyle` and `labelStyle`, even though `FloatingLabelBehavior.always` is used.

### Code sample

<details open><summary>Code sample</summary>

```dart
  TextField(
        decoration: InputDecoration(
          floatingLabelBehavior: FloatingLabelBehavior.always,
          labelText: "label",
          floatingLabelStyle: Theme.of(context).textTheme.labelLarge!,
         )
)
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/15652306/a2e8d32d-cfb4-4f36-b94f-839cfab2c40c

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.2.1 23C71 darwin-arm64, locale en-FR)
    • Flutter version 3.19.6 on channel stable at /Users/theo/.local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (6 days ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/theo/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = /Users/theo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (3 available)
    • iPhone 15 (mobile) • BCE05AEF-41E7-48DF-BE31-969DE94790C4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 124.0.6367.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

With this PR, when `InputDecorator.floatingLabelBehavior` is set to `FloatingLabelBehavior.always` the label style is always set to `InputDecorator.floatingLabelStyle`, previously `InputDecorator.labelStyle` was used when the field was not focused or was empty.  

## Related Issue

Fixes https://github.com/flutter/flutter/issues/147231

## Tests

Adds 1 test for this particular issue and several missing tests.

### CODE REVIEW

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 1]
```diff
@@ -2155,7 +2155,7 @@ class _InputDecoratorState extends State<InputDecorator> with TickerProviderStat
         child: AnimatedDefaultTextStyle(
           duration:_kTransitionDuration,
           curve: _kTransitionCurve,
-          style: widget._labelShouldWithdraw
+          style: widget._labelShouldWithdraw || decoration.floatingLabelBehavior == FloatingLabelBehavior.always
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/material/input_decorator.dart:2158]: I wonder if `_labelShouldWithdraw` should just take into account `decoration.floatingLabelBehavior == FloatingLabelBehavior.always`. I looked through the usages in this file and it is almost always used along with `decoration.floatingLabelBehavior == FloatingLabelBehavior.always` so it seems reasonable. What do you think?

**Review by Renzo-Olivares — COMMENTED** [review]
Thank you for the contribution @bleroux, and for all the tests!

File: packages/flutter/lib/src/material/input_decorator.dart [hunk 2]
```diff
@@ -1789,8 +1789,11 @@ class InputDecorator extends StatefulWidget {
   /// Whether the label needs to get out of the way of the input, either by
   /// floating or disappearing.
   ///
-  /// Will withdraw when not empty, or when focused while enabled.
-  bool get _labelShouldWithdraw => !isEmpty || (isFocused && decoration.enabled);
+  /// Will withdraw when not empty, or when focused while enabled, or when
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/material/input_decorator.dart:1792]: nit: I think you can get rid of the first `or` in this sentence.

File: packages/flutter/lib/src/material/input_decorator.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/material/input_decorator.dart]: Yeah I think it makes sense to change this even in the semantics case, since its depending on whether the label is floating. I'll keep an eye out if this causes any issues.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM w/ small nit. Thanks for the contribution!

**Comment by Renzo-Olivares** [comment]
I'll check on the google testing issues @bleroux.

**Comment by Renzo-Olivares** [comment]
@bleroux There is one test failure that i'm not too sure is expected or not. Before this change the `prefix`/`prefixText` would not show when the `floatingLabelBehavior` is set to `FloatingLabelBehavior.always`, and we unfocus the `TextField`. After this change the `prefix`/`prefixText` always shows when `floatingLabelBehavior` is set to `FloatingLabelBehavior.always`. Something similar also happens with `suffix`/`suffixText`. The main culprit is this block of code that builds the `prefix` and `suffix` https://github.com/flutter/flutter/blob/3b2bfc740f0dab7e8652bff80a9eadc87338c030/packages/flutter/lib/src/material/input_decorator.dart#L2178-L2198 . `_AffixText` depends on whether the label is floating to decide whether or not to visually show the prefix/suffix. Should the prefix/suffix always be displayed in this case? Let me know if this explanation was clear enough or if I can provide more context.

**Comment by bleroux** [comment]
@Renzo-Olivares Many thanks for the detailed information. 

> I'm leaning towards the new behavior being the correct one, since I don't see a reason not to show the prefix if the label is floating.

I agree with you. I'm currently working on the M3 tests migration for prefix/suffix, I started looking closer at this behavior and I will post an update tomorrow to let you if I found anything that we missed.

**Comment by bleroux** [comment]
@Renzo-Olivares
I had a closer look and I still fully agree with you on "since I don't see a reason not to show the prefix if the label is floating."

I have updated the PR with two tests related to that behavior (and I will probably add more on the PR I'm working on which goals is to migrate M3 tests related to prefix/suffix).
