### PR TITLE
Null TextWidthBasis docs

### LINKED ISSUE #39640: TextPainter.textWidthBasis docs are broken
The `TextPainter.textWidthBasis` docs just say `null`.

cc @GaryQian

### PR DESCRIPTION
**Pull request by justinmc**
## Description

Some pages in the docs for `textWidthBasis` properties were showing up as `null` (i.e. [RenderParagraph.textWidthBasis](https://api.flutter.dev/flutter/rendering/RenderParagraph/textWidthBasis.html)).  I think this was due to not capitalizing `text` in my macro?

## Related Issues

Closes https://github.com/flutter/flutter/issues/39640

## Tests

None, just a docs fix.

### CODE REVIEW

**Comment by justinmc** [comment]
@HansMuller Is this a proper docs macro, or is there some way I can verify that it is?

```
{@macro flutter.dart:ui.Text.TextWidthBasis}
```

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 1]
```diff
@@ -323,7 +323,7 @@ class TextPainter {
     _needsLayout = true;
   }
 
-  /// {@macro flutter.dart:ui.text.TextWidthBasis}
```
Comment (chunhtai) [inline packages/flutter/lib/src/painting/text_painter.dart]: I didn't see the declaration of flutter.dart:ui.text.TextWidthBasis, so I think this will still be null. I checked the code, and it seems like TextWidthBasis does not passed to dart ui/text.dart, so I think we will probably provide the full documentation here.

**Comment by HansMuller** [comment]
An `@macro` needs to refer to text defined within an `@template`, see https://pub.dev/packages/dartdoc#macros.

I don't see a template here. In fact it seems like the references should just link to the TextWidthBasis enum with `[TextWidthBasis]`.

File: packages/flutter/lib/src/material/selectable_text.dart [hunk 2]
```diff
@@ -374,7 +374,7 @@ class SelectableText extends StatefulWidget {
   /// {@macro flutter.widgets.edtiableText.scrollPhysics}
   final ScrollPhysics scrollPhysics;
 
-  /// {@macro flutter.dart:ui.Text.TextWidthBasis}
+  /// Defines how to consider the width of the rendered text.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/selectable_text.dart]: consider => measure

I think the TextWidthBasis docs also use "consider"; doesn't seem like the right word to me.

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 3]
```diff
@@ -81,7 +81,7 @@ class PlaceholderDimensions {
 
 /// The different ways of considering the width of one or more lines of text.
```
Comment (HansMuller) [inline packages/flutter/lib/src/painting/text_painter.dart]: considering => measuring

Here and elsewhere.

**Comment by justinmc** [comment]
Thanks @chunhtai @HansMuller, I totally messed up that macro and that's exactly why it was showing `null`.  I've removed the macro altogether as suggested.

**Review by HansMuller — APPROVED** [review]
LGTM except for using "measure" instead of "consider".

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 4]
```diff
@@ -323,7 +323,7 @@ class TextPainter {
     _needsLayout = true;
   }
 
-  /// {@macro flutter.dart:ui.text.TextWidthBasis}
+  /// Defines how to measure the width of the rendered text.
```
Comment (chunhtai) [inline packages/flutter/lib/src/painting/text_painter.dart]: Since we are repeating the the same documentation across text_painter selectable_text and text, I think we can define the template here and use macro for selectable_text and text?

Comment (justinmc) [reply packages/flutter/lib/src/painting/text_painter.dart]: Good call, will do.

**Review by chunhtai — APPROVED** [review]
LGTM
