### PR TITLE
Selection area right click behavior should match native

### LINKED ISSUE #117561: [web] Right click in SelectionArea incorrectly selects text (on Windows)
## Steps to Reproduce

Right clicking in a SelectionArea in a Flutter web environment (using either web renderer) results in the word under the cursor being selected when nothing is selected. This differs from the standard browser behavior (at least on Chrome / Windows) and can inhibit the standard context menu from being displayed if the user happens to right click in the wrong area. Note that while this report is specific to web, this behavior also differs from standard Windows behavior for most applications; right click should not select text.

https://user-images.githubusercontent.com/686/209240032-96c9a944-bde4-4a8e-9fb8-d890d3e99d02.mp4

**Expected results:** 

No text should be selected when right clicking.

**Actual results:** 

Text is selected.

<details>
<summary>Code sample</summary>

Wrap any widget in `SelectionArea`:

https://dartpad.dev/?id=c806dc92e4761b0ce3953f6cd198009a

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.7.0-1.2.pre, on Microsoft Windows [Version 10.0.22000.1335], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
[✓] Android Studio (version 2021.3)
[✓] VS Code, 64-bit edition (version 1.74.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
This change updates `SelectableRegion`s right-click gesture to match native platform behavior.

Before: Right-click gesture selects word at position and opens context menu (All Platforms)
After: 
- Linux, toggles context menu on/off, and collapses selection when click was not on an active selection (uncollapsed).
- Windows, Android, Fuchsia, shows context menu at right-clicked position (unless the click is at an active selection).
- macOS, toggles the context menu if right click was at the same position as the previous / or selects word at position and opens context menu.
- iOS, selects word at position and opens context menu.

This change also prevents the `copy` menu button from being shown when there is a collapsed selection (nothing to copy).

Fixes #117561

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 1]
```diff
@@ -263,7 +263,7 @@ class SelectableRegion extends StatefulWidget {
     required final VoidCallback onCopy,
     required final VoidCallback onSelectAll,
   }) {
-    final bool canCopy = selectionGeometry.hasSelection;
+    final bool canCopy = selectionGeometry.hasSelection && selectionGeometry.startSelectionPoint?.localPosition != selectionGeometry.endSelectionPoint?.localPosition;
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:266]: should this check for selectionGeometry.status == SelectionStatus.uncollapsed

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 2]
```diff
@@ -490,11 +490,40 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
...
     lastSecondaryTapDownPosition = details.globalPosition;
     widget.focusNode.requestFocus();
-    _selectWordAt(offset: details.globalPosition);
-    _showHandles();
-    _showToolbar(location: details.globalPosition);
+    switch (defaultTargetPlatform) {
+      case TargetPlatform.android:
+      case TargetPlatform.fuchsia:
+      case TargetPlatform.windows:
+        _selectStartTo(offset: details.globalPosition);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:501]: they don't select word? does the intention to collapse the selection at this globalPosition?

also this can be lastSecondaryTapDownPosition to be more readable

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 3]
```diff
@@ -490,11 +490,40 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
...
+        _selectEndTo(offset: details.globalPosition);
+        _showHandles();
+        _showToolbar(location: details.globalPosition);
+      case TargetPlatform.iOS:
+        _selectWordAt(offset: details.globalPosition);
+        _showHandles();
+        _showToolbar(location: details.globalPosition);
+      case TargetPlatform.macOS:
+        if (previousSecondaryTapDownPosition == lastSecondaryTapDownPosition && toolbarIsVisible) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:510]: This seems weird. of user click a slightly different place but still in the same word. will they be able to toggle the toolbar?

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 4]
```diff
@@ -490,11 +490,40 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
...
+          hideToolbar();
+          return;
+        }
+        _selectWordAt(offset: details.globalPosition);
+        _showHandles();
+        _showToolbar(location: details.globalPosition);
+      case TargetPlatform.linux:
+        if (toolbarIsVisible) {
+          hideToolbar();
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:519]: is this true even if user click out side of the current selection?

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 5]
```diff
@@ -490,11 +490,40 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
...
+          return;
+        }
+        _selectStartTo(offset: details.globalPosition);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:522]: same here, should this collapse the selection?

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 3 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:510]: In that case the toolbar should not be able to be toggled. Only if it is in the same place will it be toggled. If it is anywhere else the toolbar is re-shown at the new position. I tested this in the native notes app, as well as on the web.

Comment (chunhtai) [reply packages/flutter/lib/src/widgets/selectable_region.dart:510]: sounds good then

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:501]: Yeah they do not, tested on chrome and wordpad/notepad. But good point about collapsing the selection, they only collapse the selection when right click happens outside of the currently active selection.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 4 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:519]: Yes, and it maintains the current selection.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 5 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/selectable_region.dart:522]: Good point, only when the right-click happens outside of the current selection.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 6]
```diff
@@ -490,11 +490,40 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
...
 
   void _handleRightClickDown(TapDownDetails details) {
+    final Offset? previousSecondaryTapDownPosition = lastSecondaryTapDownPosition;
+    final bool toolbarIsVisible = _selectionOverlay?.toolbarIsVisible ?? false;
     lastSecondaryTapDownPosition = details.globalPosition;
     widget.focusNode.requestFocus();
-    _selectWordAt(offset: details.globalPosition);
-    _showHandles();
-    _showToolbar(location: details.globalPosition);
+    switch (defaultTargetPlatform) {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/selectable_region.dart:497]: Is there logic here that should be deduplicated with EditableText (maybe [here](https://github.com/flutter/flutter/blob/ceeaf98e64703a50cf3cfcf0bd103de98b979a45/packages/flutter/lib/src/widgets/text_selection.dart#L2419))?  Or maybe just in the long run.

**Review by justinmc — APPROVED** [review]
LGTM :+1:  Just one thought below about possible duplicate logic.

Thanks for trying all the niche native behaviors to get them right.  I think there are a lot of physical mouse behaviors on Android and iOS that we don't do correctly right now.

File: packages/flutter/lib/src/widgets/selectable_region.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/selectable_region.dart:497]: We talked offline.  Deduplication with EditableText will be a long term thing.

**Review by justinmc — APPROVED** [review]
Renewing my LGTM with the changes :+1:

File: packages/flutter/lib/src/rendering/selection.dart [hunk 7]
```diff
@@ -627,6 +628,9 @@ class SelectionGeometry {
   /// The status of ongoing selection in the [Selectable] or [SelectionHandler].
   final SelectionStatus status;
 
+  /// The rects that represent the selection if there is any.
+  final List<Rect>? selectionRects;
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/selection.dart:632]: what coordinates are these rects in?

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 8]
```diff
@@ -1770,9 +1827,20 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
       }
     }
 
+    // Need to collect selection rects from selectables ranging from the
+    // currentSelectionStartIndex to the currentSelectionEndIndex.
+    final List<Rect> selectionRects = <Rect>[];
+    for (int index = currentSelectionStartIndex; index <= currentSelectionEndIndex; index++) {
+      final List<Rect>? currSelectableSelectionRects = selectables[index].value.selectionRects;
+      if (currSelectableSelectionRects != null) {
+        selectionRects.addAll(currSelectableSelectionRects);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1836]: are they in global coordinates? otherwise, don we need to do transformation?

File: packages/flutter/lib/src/rendering/selection.dart (hunk 7 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/selection.dart:632]: These should be in the local coordinates of the Selectable. I'll update the docs.

File: packages/flutter/lib/src/rendering/paragraph.dart [hunk 9]
```diff
@@ -1335,6 +1335,14 @@ class _SelectableFragment with Selectable, ChangeNotifier implements TextLayoutM
       : paragraph._getOffsetForPosition(TextPosition(offset: selectionEnd));
     final bool flipHandles = isReversed != (TextDirection.rtl == paragraph.textDirection);
     final Matrix4 paragraphToFragmentTransform = getTransformToParagraph()..invert();
+    final TextSelection selection = TextSelection(
+      baseOffset: selectionStart,
+      extentOffset: selectionEnd,
+    );
+    final List<Rect> selectionRects = <Rect>[];
+    for (final TextBox textBox in paragraph.getBoxesForSelection(selection)) {
+      selectionRects.add(textBox.toRect());
```
[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/paragraph.dart:1344]: Do you mean if I click in the overlap between the selections?

Screenshot 2023-06-15 at 11 28 44 AM

[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/paragraph.dart:1344]: I mean if it is possible the line height is large that each line does not overlap. I am not sure if that is possible though.

[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/paragraph.dart:1344]: I think it is possible given the current implementation.

Screenshot 2023-06-15 at 12 02 51 PM

This is due to `getBoxesForSelection` defaulting to `SelectionHeightStyle.tight`.

```dart
  List<ui.TextBox> getBoxesForSelection(
    TextSelection selection, {
    ui.BoxHeightStyle boxHeightStyle = ui.BoxHeightStyle.tight,
    ui.BoxWidthStyle boxWidthStyle = ui.BoxWidthStyle.tight,
  }) {
    assert(!debugNeedsLayout);
    _layoutTextWithConstraints(constraints);
    return _textPainter.getBoxesForSelection(
      selection,
      boxHeightStyle: boxHeightStyle,
      boxWidthStyle: boxWidthStyle,
    );
  }
```

In `SelectableText` and `TextField` these values are customizable. Setting to `SelectionHeightStyle.max` would result in this instead.

Screenshot 2023-06-15 at 12 04 59 PM

What I see on WordPad for windows is that it looks like they use `SelectionHeightStyle.max`.

[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/paragraph.dart:1344]: >  I think if the line do not overlap it might be reasonable to expect that the gap is not within the selection?

I don't have an answer for this, since I am not sure if there is a native app that does SelectionHeightStyle.tight?

I am ok as-is, just want to make sure we are aware of this.

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 10]
```diff
@@ -263,7 +263,7 @@ class SelectableRegion extends StatefulWidget {
     required final VoidCallback onCopy,
     required final VoidCallback onSelectAll,
   }) {
-    final bool canCopy = selectionGeometry.hasSelection;
+    final bool canCopy = selectionGeometry.hasSelection && selectionGeometry.status == SelectionStatus.uncollapsed;
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:266]:
```suggestion
    final bool canCopy = selectionGeometry.status == SelectionStatus.uncollapsed;
```
it guarantee to hasSelection if it is uncollapsed

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 11]
```diff
@@ -489,12 +489,62 @@ class SelectableRegionState extends State<SelectableRegion> with TextSelectionDe
...
+        _showToolbar(location: lastSecondaryTapDownPosition);
+      case TargetPlatform.linux:
+        if (toolbarIsVisible) {
+          hideToolbar();
+          return;
+        }
+        // If lastSecondaryTapDownPosition is within the current selection then
+        // keep the current selection, if not then collapse it.
+        final bool uncollapsedSelectionExists = _selectionDelegate.value.hasSelection && _selectionDelegate.value.status == SelectionStatus.uncollapsed;
+        final bool lastSecondaryTapDownPositionWasOnActiveSelection = uncollapsedSelectionExists && _positionIsOnActiveSelection(globalPosition: details.globalPosition);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:540]: You can just check _positionIsOnActiveSelection directly if the selectionRects is not nullable?

File: packages/flutter/lib/src/widgets/selectable_region.dart [hunk 12]
```diff
@@ -1770,9 +1820,24 @@ abstract class MultiSelectableSelectionContainerDelegate extends SelectionContai
...
     }
 
+    // Need to collect selection rects from selectables ranging from the
+    // currentSelectionStartIndex to the currentSelectionEndIndex.
+    final List<Rect> selectionRects = <Rect>[];
+    for (int index = currentSelectionStartIndex; index <= currentSelectionEndIndex; index++) {
+      final List<Rect>? currSelectableSelectionRects = selectables[index].value.selectionRects;
+      if (currSelectableSelectionRects != null) {
+        selectionRects.addAll(currSelectableSelectionRects.map((Rect selectionRect) {
+          final Matrix4 transform = selectables[index].getTransformTo(null);
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/selectable_region.dart:1830]: This should not be stored in global coordinates, but in local coordinates of `SelectionContainer`. 

Either everything is stored in global coordinates starting from the selectionGeomery of _SelectableFragment, or everything is stored in local coordinates of the `Selectable` including the SelectionContainer.

Since other properties in SelectionGeometry are in local coordinate, this should too. Use getTransformFrom(selectables[index]) instead.

File: packages/flutter/lib/src/rendering/selection.dart (hunk 7 above)
Comment (chunhtai) [reply packages/flutter/lib/src/rendering/selection.dart:633]: you can give it a default value of `const <Rect>[]` and make it not nullable.

**Comment by Renzo-Olivares** [comment]
@chunhtai Would it be helpful to have an assertion in the constructor of `SelectionGeometry` that asserts if `SelectionStatus.uncollapsed` then `selectionRects` should be non-empty? Though this wouldn't be possible with a const constructor.

The closest we could get with a const constructor is making `selectionRects` nullable, and checking if it is non-null when `SelectionStatus.uncollapsed`.

What do you think?

**Comment by chunhtai** [comment]
> @chunhtai Would it be helpful to have an assertion in the constructor of `SelectionGeometry` that asserts if `SelectionStatus.uncollapsed` then `selectionRects` should be non-empty? Though this wouldn't be possible with a const constructor.
> 
> The closest we could get with a const constructor is making `selectionRects` nullable, and checking if it is non-null when `SelectionStatus.uncollapsed`.
> 
> What do you think?

I think you can have SelectionStatus.uncollapsed, but selectionRects empty if you scroll the selection off screen in a scrollable

**Comment by chunhtai** [comment]
> > @chunhtai Would it be helpful to have an assertion in the constructor of `SelectionGeometry` that asserts if `SelectionStatus.uncollapsed` then `selectionRects` should be non-empty? Though this wouldn't be possible with a const constructor.
> > The closest we could get with a const constructor is making `selectionRects` nullable, and checking if it is non-null when `SelectionStatus.uncollapsed`.
> > What do you think?
> 
> I think you can have SelectionStatus.uncollapsed, but selectionRects empty if you scroll the selection off screen in a scrollable

that remind me we should probably clip the selection rects in scrollable.

**Review by chunhtai — APPROVED** [review]
LGTM
