### PR TITLE
[flutter_tools] Add support for URI formats like ?line=x for "flutter test"

### LINKED ISSUE #114968: Support running multiple tests by line/col (as package:test does)
`dart test`/`package:test` can now run tests [by line/column numbers](https://github.com/dart-lang/test/pull/1604) with query strings on the test files:

```
dart test -r json "test/line_test.dart?line=4" "test/line_test.dart?line=5"
```

This is something I'd like to adopt in VS Code instead of using `--name` because that's error-prone when names are dynamic (which comes up more than you'd expect):

```
test('foo bar', () {});
[1, 2].forEach((i) {
  test('foo $i', () { // At analysis time, we don't have a reliable name for running this test
  });
});
```

This is not currently supported by Flutter. When trying to run one, it says there are no tests:

```
danny@Dannys-MacBook-Pro dartcode_flutter_4021 % flutter test "test/widget_test.dart?line=31"
No tests ran.                                                                                                                                                                     
No tests were found.
```

And when trying to run two, it prints an error and never completes:

```
danny@Dannys-MacBook-Pro dartcode_flutter_4021 % flutter test "test/widget_test.dart?line=31" "test/widget_test.dart?line=32" 
00:01 +0: loading /Users/danny/Desktop/dart_samples/dartcode_flutter_4021/test/widget_test.dart                                                                                  Shell: [ERROR:flutter/runtime/dart_isolate.cc(144)] Could not prepare isolate.
Shell: [ERROR:flutter/runtime/runtime_controller.cc(390)] Could not create root isolate.
Shell: [ERROR:flutter/shell/common/shell.cc(606)] Could not launch engine with configuration.
00:44 +0: loading /Users/danny/Desktop/dart_samples/dartcode_flutter_4021/test/widget_test.dart                                 
```

Importantly, for VS code this needs to also work when using `--machine` and `--start-paused`. There are some existing complications with running multiple suites with these flags but supporting just a single suite (and multiple tests within it) would be sufficient for VS Code (although whether it's possible to support that without also "fixing" funning multiple suites, I'm not sure).

### PR DESCRIPTION
**Pull request by DanTup**
This allows tests to be filtered by name/line/col using a URI format passed to `flutter test`, as `dart test` now does (https://github.com/dart-lang/test/pull/1604).

```
flutter test test/foo_test.dart
flutter test "test/foo_test.dart?full-name=bar"
flutter test "test/foo_test.dart?line=15"
```

Mostly it's just changing some `String`s to `URI`s, which are then passed on to `package:test`.

The motivation here is to be able to run tests by the line they appear on from IDE UIs, because currently they have to use `--name` which doesn't handle overlapping or dynamic names very well (or test names with characters that are [complicated to escape](https://github.com/Dart-Code/Dart-Code/issues/4042) when using shell-execute).

Fixes #114968.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/test.dart [hunk 1]
```diff
@@ -256,37 +256,43 @@ class TestCommand extends FlutterCommand with DeviceBasedDevelopmentArtifacts {
...
+    if (testUris.isEmpty) {
       // We don't scan the entire package, only the test/ subdirectory, so that
       // files with names like "hit_test.dart" don't get run.
       final Directory testDir = globals.fs.directory('test');
       if (!testDir.existsSync()) {
         throwToolExit('Test directory "${testDir.path}" not found.');
       }
-      _testFiles = _findTests(testDir).toList();
-      if (_testFiles.isEmpty) {
+      _testFileUris..clear()..addAll(_findTests(testDir).map(Uri.file));
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/commands/test.dart:267]: why do we have to clear `_testFileUris`?

Comment (DanTup) [reply packages/flutter_tools/lib/src/commands/test.dart:267]: We shouldn't. I guess I did this to preserve the original semantics (the original `_testFiles` was overwritten). Unless this `verifyThenRunCommand` method is being called multiple times on a single instance, it shouldn't make a difference.

(I've removed it now).

**Review by christopherfujino — APPROVED** [review]
LGTM
