### PR TITLE
InputDecorator M3 tests migration - Step5 - Helper/Counter/Error

### LINKED ISSUE #138213: InputDecorator helper text color does not default to hint color with M3 (it did with M2)
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run the provided code sample.

### Expected results

As with Material 2, the expected helper text color should defaults to the hint color.

Capture d’écran du 2023-11-10 11-03-05

### Actual results

With Material 3, the helper text color defaults to `onSurfaceVariant`, as a result the hint and the helper does not have the same color.

Capture d’écran du 2023-11-10 11-01-08

The `InputDecorator` M3 migration was done in https://github.com/flutter/flutter/pull/107943

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final ThemeData theme =
        ThemeData(hintColor: Colors.blue[500], useMaterial3: true);
    return MaterialApp(
      theme: theme,
      home: const Scaffold(
        body: TextField(
          decoration: InputDecoration(
            hintText: 'Hint',
            helperText: 'helper text',
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.14.0-6.0.pre.1585, on Ubuntu 23.04 6.2.0-36-generic, locale fr_FR.UTF-8)
    ! Flutter version 3.14.0-6.0.pre.1585 on channel [user-branch] at /home/bruno/Nevercode/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Upstream repository git@github.com:NevercodeHQ/flutter.git
    • FLUTTER_GIT_URL = git@github.com:NevercodeHQ/flutter.git
    • Framework revision 19b034a964 (il y a 4 jours), 2023-11-06 15:07:09 +0100
    • Engine revision b020893cba
    • Dart version 3.3.0 (build 3.3.0-113.0.dev)
    • DevTools version 2.30.0-dev.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform
      update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /media/oldhome/Android/Sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • ANDROID_HOME = /media/oldhome/Android/Sdk
    • Java binary at: /media/oldhome/Produits/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.7
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /media/oldhome/Produits/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.76.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.04 6.2.0-36-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.88

[✓] Network resources
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR migrates `InputDecorator` helper/counter/error related tests to M3 and adds some missing tests.

It is the fifth step for the M3 test migration for `InputDecorator`.
Step 1: https://github.com/flutter/flutter/pull/142981
Step 2: https://github.com/flutter/flutter/pull/143369
Step 3: https://github.com/flutter/flutter/pull/143520
Step 4: https://github.com/flutter/flutter/pull/144169

## Related Issue

Related to https://github.com/flutter/flutter/issues/139076
fixes https://github.com/flutter/flutter/issues/138213

### CODE REVIEW

**Comment by bleroux** [comment]
@justinmc
Unfortunately, the diff is not as readable as I had expected (this is because I moved some tests around, the main part for this PR starts at line 1506).
I organized the helper/counter/error tests using a hierarchy of groups that mimics M3 spec, see https://m3.material.io/components/text-fields/specs#f967d3f6-0139-43f7-8336-510022684fd1). I will probably use this same structure for future PRs and apply it to the tests I added in my previous PRs. I think it makes easier to see if we have full coverage for the M3 spec.

I added some TODO for values that are not compliant with the M3 spec. I will focus on fixing those values for my next PRs (these might be breaking changes so I did not bundle those changes with this test only PR).

File: packages/flutter/test/material/input_decorator_test.dart [hunk 1]
```diff
@@ -1175,98 +1405,765 @@ void main() {
...
+    //    8 - bottom padding
+    //    8 - gap above supporting text
+    //   16 - helper/counter (font size = 12, line height is 1.5)
+    const double topPadding = 8.0;
+    const double floatingLabelHeight = 12.0;
+    const double labelInputGap = 4.0;
+    const double inputHeight = 24.0;
+    const double bottomPadding = 8.0;
+    // TODO(bleroux): make the InputDecorator implementation compliant with M3 spec by changing
+    // the helperGap to 4.0 instead of 8.0.
```
Comment (justinmc) [inline packages/flutter/test/material/input_decorator_test.dart:1521]: Nit: Is there an issue you could link for this?

File: packages/flutter/test/material/input_decorator_test.dart [hunk 2]
```diff
@@ -1175,98 +1405,765 @@ void main() {
...
+          final TextStyle expectedStyle = theme.textTheme.bodySmall!.copyWith(color: expectedColor);
+          expect(getErrorStyle(tester), expectedStyle);
+          final Color expectedCounterColor = theme.colorScheme.onSurfaceVariant;
+          final TextStyle expectedCounterStyle = theme.textTheme.bodySmall!.copyWith(color: expectedCounterColor);
+          expect(getCounterStyle(tester), expectedCounterStyle);
+        });
+      });
+    });
+
+    group('Multilines error/helper', () {
```
Comment (justinmc) [inline packages/flutter/test/material/input_decorator_test.dart:2030]: Super nit: I would just say "Multiline" with no "s".

**Review by justinmc — APPROVED** [review]
LGTM :+1: No worries about the diff, it wasn't too bad. Thanks for another step in this project.

File: packages/flutter/test/material/input_decorator_test.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/test/material/input_decorator_test.dart:1521]: Add a link to https://github.com/flutter/flutter/issues/144984, and currently working on a PR for it.
