### PR TITLE
Fix tappable area for `DropdownButtonFormField` & add `InkWell` to `DropdownButton`

### LINKED ISSUE #31641: DropdownButton has no splash effect
Tapping on a DropdownButton has no splash/ink effect or any touch feedback.

Potential simple fix would be to replace `GestureDetector` with `InkWell` here:
https://github.com/flutter/flutter/blob/db096cdfd84851ccbd39f57f4af44d36ea28729e/packages/flutter/lib/src/material/dropdown.dart#L919-L923

Would be nice to add custom padding as well.

### LINKED ISSUE #53634: DropDownButtonFormField is not easily clickable when OutlineInputBorder is used.
## Steps to Reproduce

https://dartpad.dev/8d23531aa97397f2e032870cd9a7f73b

DropDownButtonFormField will not open menu items when clicking near the border.
Clicking only works if it is done close to the area that labelText is shown.

**Expected results:** DropDownButtonFormField should be clickable wherever you click inside the borders.

**Actual results:** DropDownButtonFormField is clickable only close to the labelText.

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/53634
fixes https://github.com/flutter/flutter/issues/31641

This PR moves Input decoration for `DropdownButtonFormField` to `DropdownButton`, which is accessed by a private constructor for `DropdownButtonFormField` (this avoids this hack https://github.com/flutter/flutter/issues/53634#issuecomment-889227826, it can be really expensive to find layouts using this kinda hack to find inner gesture detector from DropdowButton) and adds `InkWell` to `DropdownButton` to match Material Design specs and most importantly fixes the tapping area fixes 

The main reason for moving inputDecorator so inkWell size is equal to inputDecorator size
Adding InkWell to `DropdownButton ` is required so `DropdownButtonFormField` has a bigger tappable area just like native Android.

Here is a native Android dropdown for reference 

Flutter with this PR

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/dropdown.dart [hunk 1]
```diff
@@ -906,6 +906,64 @@ class DropdownButton<T> extends StatefulWidget {
...
+    this.focusNode,
+    this.autofocus = false,
+    this.dropdownColor,
+    this.menuMaxHeight,
+    this.enableFeedback,
+    this.alignment = AlignmentDirectional.centerStart,
+    this.borderRadius,
+    InputDecoration? inputDecoration,
+    bool? isEmpty,
+    bool? isFocused,
```
Comment (werainkhatri) [inline packages/flutter/lib/src/material/dropdown.dart:943]: Nit.
These can be non-nullable, making the assertions redundant.

File: packages/flutter/lib/src/material/dropdown.dart [hunk 2]
```diff
@@ -1473,13 +1537,20 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
...
+            canRequestFocus: false,
+            child: widget._inputDecoration != null ?
+              InputDecorator(
+                decoration: widget._inputDecoration!,
+                isEmpty: widget._isEmpty!,
+                isFocused: widget._isFocused!,
+                child: result,
+              ) :
+              result,
           ),
```
Comment (werainkhatri) [inline packages/flutter/lib/src/material/dropdown.dart:1554]: Nit.
Update `result` to `InputDecorator(..., child: result)` if `widget._inputDecoration != null` before returning. Hence, child can be set to `result` directly.

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 3]
```diff
@@ -576,25 +576,29 @@ void main() {
...
-            items: menuItems.map<DropdownMenuItem<String>>((String item) {
-              return DropdownMenuItem<String>(
-                key: ValueKey<String>(item),
-                value: item,
-                child: Text(item, key: ValueKey<String>('${item}Text')),
-              );
-            }).toList(),
+        child: Align(
+          widthFactor: 1.0,
+          heightFactor: 1.0,
```
Comment (werainkhatri) [inline packages/flutter/test/material/dropdown_form_field_test.dart:581]: What's the reason for this `Align`? Seems unrelated to the PR.

File: packages/flutter/test/material/dropdown_test.dart [hunk 4]
```diff
@@ -1290,9 +1290,8 @@ void main() {
     // By default the hint contributes the label.
     expect(tester.getSemantics(find.byKey(key)), matchesSemantics(
       isButton: true,
-      label: 'test',
```
Comment (werainkhatri) [inline packages/flutter/test/material/dropdown_test.dart:1293]: The label semantic should be tested here and below.

File: packages/flutter/test/material/dropdown_test.dart [hunk 5]
```diff
@@ -1290,9 +1290,8 @@ void main() {
...
-      hasTapAction: true,
```
Comment (werainkhatri) [inline packages/flutter/test/material/dropdown_test.dart:1294]: Why does the semantics return empty actions instead of `[SemanticsAction:SemanticsAction.tap]`?

**Review by werainkhatri — CHANGES_REQUESTED** [review]
Just a few nits and queries.

File: packages/flutter/lib/src/material/dropdown.dart [hunk 6]
```diff
@@ -906,6 +906,64 @@ class DropdownButton<T> extends StatefulWidget {
        assert(isExpanded != null),
        assert(autofocus != null),
        assert(itemHeight == null || itemHeight >=  kMinInteractiveDimension),
+       _inputDecoration = null,
+       _isEmpty = null,
+       _isFocused = null,
+       super(key: key);
+
+  DropdownButton._({
```
[the remark this answers is not in the document]
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dropdown.dart:914]: Sure

File: packages/flutter/test/material/dropdown_form_field_test.dart (hunk 3 above)
Comment (TahaTesser) [reply packages/flutter/test/material/dropdown_form_field_test.dart:581]: This is required to constrain `Material` size to the child widget's size to get the actual height `DropdownButtonFormField`.

File: packages/flutter/test/material/dropdown_test.dart (hunk 4 above)
Comment (TahaTesser) [reply packages/flutter/test/material/dropdown_test.dart:1293]: Return semantics have changed after wrapping InkWell, will update after the team review this private constructor approach

File: packages/flutter/test/material/dropdown_test.dart (hunk 5 above)
Comment (TahaTesser) [reply packages/flutter/test/material/dropdown_test.dart:1294]: Return semantics have changed after wrapping InkWell, will update after the team review this private constructor approach

File: packages/flutter/lib/src/material/dropdown.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dropdown.dart:943]: Thanks!

File: packages/flutter/lib/src/material/dropdown.dart (hunk 2 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dropdown.dart:1554]: Makes sense

File: packages/flutter/test/material/dropdown_form_field_test.dart (hunk 3 above)
Comment (nt4f04uNd) [inline packages/flutter/test/material/dropdown_form_field_test.dart:581]: I think you don't need the factors here

File: packages/flutter/lib/src/material/dropdown.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dropdown.dart:943]: Actually, these have to be nullable so the public constructor doesn't have to override them as all final parameters have to be overridden and I don't wanna make variable mutable since it has other side affects

Comment (werainkhatri) [reply packages/flutter/lib/src/material/dropdown.dart:943]: I suppose I explained incorrectly. I meant doing something like below, as to begin nullable by type and non-nullable by assertion seems inconsistent. These won't be overridden in the public constructor and its private counterparts will remain unchanged. wdyt?

```suggestion
    required InputDecoration inputDecoration,
    required bool isEmpty,
    required bool isFocused,
```

File: packages/flutter/test/material/dropdown_form_field_test.dart (hunk 3 above)
Comment (TahaTesser) [reply packages/flutter/test/material/dropdown_form_field_test.dart]: Thanks, added out of habit

**Comment by TahaTesser** [comment]
cc; @gspencergoog 
Can you please let me know If the private constructor is approach is the way, I will update the PR for conflicts and fix semantics

File: packages/flutter/lib/src/material/dropdown.dart (hunk 1 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/material/dropdown.dart:943]: Actually, I mostly agree with @werainkhatri: the bools here should be required, and the public constructor can just explicitly set them to false (they'll be ignored anyhow if `inputDecoration` is null).

You would still have `inputDecoration` be nullable, since that indicates whether or not to apply the input decorator.

Having a nullable boolean usually means a tristate value, and these are not used as tristate values.

File: packages/flutter/test/material/dropdown_form_field_test.dart [hunk 7]
```diff
@@ -576,25 +576,27 @@ void main() {
...
-            value: value,
-            onChanged: onChanged,
-            items: menuItems.map<DropdownMenuItem<String>>((String item) {
-              return DropdownMenuItem<String>(
-                key: ValueKey<String>(item),
-                value: item,
-                child: Text(item, key: ValueKey<String>('${item}Text')),
-              );
-            }).toList(),
+        child: Align(
```
Comment (gspencergoog) [inline packages/flutter/test/material/dropdown_form_field_test.dart:579]: What's the reason for adding the `Align` (and why not use `Center` instead)?

If the test won't pass without it, it makes me wonder if this isn't a more breaking change that we should consider more carefully.

**Review by gspencergoog — CHANGES_REQUESTED** [review]

**Comment by TahaTesser** [comment]
@werainkhatri 
I just pushed a couple of updates, can you please take a look?

File: packages/flutter/lib/src/material/dropdown.dart [hunk 8]
```diff
@@ -1465,22 +1528,27 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
...
+        child: result,
+      );
+    }
+
     return Semantics(
       button: true,
       child: Actions(
         actions: _actionMap,
-        child: Focus(
+        child: InkWell(
```
Comment (werainkhatri) [inline packages/flutter/lib/src/material/dropdown.dart:1544]: I looked into how other widgets use `InkWell` and noticed that `ButtonStyleButton` uses `ConstrainedBox` and `Material` along with `InkWell`. I don't fully understand how `MaterialStateProperty` works, but I think this is how `InkWell` is supposed to be used.

https://github.com/flutter/flutter/blob/4e468f0122a9b814720d2a09176dd1bbaeeb8bc8/packages/flutter/lib/src/material/button_style_button.dart#L338-L349

File: packages/flutter/lib/src/material/dropdown.dart [hunk 9]
```diff
@@ -1465,22 +1528,27 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
...
     );
 
+    if (widget._inputDecoration != null) {
+      result = InputDecorator(
+        decoration: widget._inputDecoration!,
+        isEmpty: widget._isEmpty,
+        isFocused: widget._isFocused,
+        child: result,
+      );
+    }
```
Comment (werainkhatri) [inline packages/flutter/lib/src/material/dropdown.dart:1538]: I think we should move `DropdownButtonHideUnderline` to `DropdownButton` too, to maintains the tree order as before: `InputDecorator` -> `DropdownButtonHideUnderline` -> `DropdownButton`.

```suggestion
    if (widget._inputDecoration != null) {
      result = InputDecorator(
        decoration: widget._inputDecoration!,
        isEmpty: widget._isEmpty,
        isFocused: widget._isFocused,
        child: DropdownButtonHideUnderline(
          child: result,
        ),
      );
    }
```

File: packages/flutter/test/material/dropdown_form_field_test.dart (hunk 7 above)
Comment (werainkhatri) [reply packages/flutter/test/material/dropdown_form_field_test.dart]: I suppose this is similar to why `ElevatedButton` (which uses `InkWell`) needs a `Center`/`SizedBox` widget as its parent in almost all of its tests. Although I am unsure if this is a breaking change or not.

File: packages/flutter/lib/src/material/dropdown.dart [hunk 10]
```diff
@@ -1465,22 +1528,27 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
...
+
     return Semantics(
       button: true,
       child: Actions(
```
Comment (werainkhatri) [inline packages/flutter/lib/src/material/dropdown.dart:1542]: I am not much familiar with `Actions`, but since `InkWell` already implements it, I suppose we can skip it here.

**Review by werainkhatri — CHANGES_REQUESTED** [review]

File: packages/flutter/lib/src/material/dropdown.dart (hunk 10 above)
Comment (gspencergoog) [reply packages/flutter/lib/src/material/dropdown.dart:1542]: No, it needs to be here: it's using a different action map than InkWell, and needs to handle the activate actions differently.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 1 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dropdown.dart]: Thanks, made these as required, assign false in pubic constructor

File: packages/flutter/test/material/dropdown_form_field_test.dart (hunk 7 above)
Comment (TahaTesser) [reply packages/flutter/test/material/dropdown_form_field_test.dart]: That's a good example, yes. You will need constraints anywhere `Material` is implemented otherwise, widgets that depend on Material expanded to Material unconstrained size such InkWell here

File: packages/flutter/lib/src/material/dropdown.dart (hunk 9 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dropdown.dart:1538]: I don't wanna make too many changes that are not necessary to fix the issues unless it provides some benefit or the team says it could be required.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 8 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dropdown.dart:1544]: `ButtonStyleButton` buttons have fixed initial size that's the reason `ButtonStyleButton` uses `ConstrainedBox`

Such as `TextButton`
https://github.com/flutter/flutter/blob/8017883a5dfd13d709c4bd04d617f54a6cb2271f/packages/flutter/lib/src/material/text_button.dart#L287

Material is not required to be wrapped for InkWell, as long as you have a Material ancestor such as Scaffold, it is enough for InkWell and Material modifies those properties based on button requirements too
https://github.com/flutter/flutter/blob/8017883a5dfd13d709c4bd04d617f54a6cb2271f/packages/flutter/lib/src/material/list_tile.dart#L1214


I am not sure either is required here

Comment (werainkhatri) [reply packages/flutter/lib/src/material/dropdown.dart:1544]: If that's the case, it needs to be mentioned that `DropdownButton` needs Material as its ancestor.

https://github.com/flutter/flutter/blob/8017883a5dfd13d709c4bd04d617f54a6cb2271f/packages/flutter/lib/src/material/list_tile.dart#L552-L553

File: packages/flutter/lib/src/material/dropdown.dart (hunk 9 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dropdown.dart:1538]: > by "under", you meant to do InkWell(child: InputDecorator(...), ...)?

Yes, so InkWell size is equal to inputDecorator size which is the same in the native video in the description

File: packages/flutter/lib/src/material/dropdown.dart (hunk 8 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dropdown.dart:1544]: Good catch, I will add that

File: packages/flutter/lib/src/material/dropdown.dart (hunk 9 above)
Comment (werainkhatri) [reply packages/flutter/lib/src/material/dropdown.dart:1541]: Oh right, obviously! Idk why misunderstood the code 😵‍💫

**Comment by werainkhatri** [comment]
Another issue I found:

`DropdownButton` used `BoxDecoration` to highlight when it had focus. Now that is handled by `InkWell` itself, so it should be removed, as the highlights overlap now.

Screenshot from 2022-01-19 16-00-33

https://github.com/flutter/flutter/blob/571a0708aaa00cc72332639459cb798e1965991b/packages/flutter/lib/src/material/dropdown.dart#L1474-L1479

File: packages/flutter/test/material/dropdown_form_field_test.dart (hunk 7 above)
Comment (gspencergoog) [reply packages/flutter/test/material/dropdown_form_field_test.dart]: OK, thanks, that makes sense.

File: packages/flutter/test/material/dropdown_test.dart [hunk 11]
```diff
@@ -3413,7 +3413,7 @@ void main() {
 
       await tester.tap(find.text('One'));
       await tester.pumpAndSettle();
-      await tester.tap(find.widgetWithText(InkWell, 'One'));
+      await tester.tap(find.widgetWithText(InkWell, 'One').last);
```
[the remark this answers is not in the document]
Comment (werainkhatri) [reply packages/flutter/test/material/dropdown_test.dart:3416]: Those aren't nested `InkWell`s. One is on the `DropdownButton`, other is on a popup route on `DropdownMenuItem`.

[the remark this answers is not in the document]
Comment (TahaTesser) [reply packages/flutter/test/material/dropdown_test.dart:3416]: @werainkhatri is correct

[the remark this answers is not in the document]
Comment (gspencergoog) [reply packages/flutter/test/material/dropdown_test.dart:3416]: OK, great, this is fine then.  Just checking!

**Comment by TahaTesser** [comment]
@gspencergoog @werainkhatri 
Is there anything else we need to do to land this please?

File: packages/flutter/lib/src/material/dropdown.dart [hunk 12]
```diff
@@ -892,6 +895,63 @@ class DropdownButton<T> extends StatefulWidget {
...
+    this.dropdownColor,
+    this.menuMaxHeight,
+    this.enableFeedback,
+    this.alignment = AlignmentDirectional.centerStart,
+    this.borderRadius,
+    required InputDecoration? inputDecoration,
+    required bool isEmpty,
+    required bool isFocused,
+    // When adding new arguments, consider adding similar arguments to
+    // DropdownButtonFormField.
```
Comment (werainkhatri) [inline packages/flutter/lib/src/material/dropdown.dart:934]: Nit. This seems unnecessary now (same in the public constructor).

File: packages/flutter/lib/src/material/dropdown.dart [hunk 13]
```diff
@@ -892,6 +895,63 @@ class DropdownButton<T> extends StatefulWidget {
...
+  }) : assert(items == null || items.isEmpty || value == null ||
+              items.where((DropdownMenuItem<T> item) {
+                return item.value == value;
+              }).length == 1,
+                "There should be exactly one item with [DropdownButton]'s value: "
```
Comment (werainkhatri) [inline packages/flutter/lib/src/material/dropdown.dart:939]: Nit.

```suggestion
                "There should be exactly one item with [DropdownButtonFormField]'s value: "
```

File: packages/flutter/lib/src/material/dropdown.dart [hunk 14]
```diff
@@ -892,6 +895,63 @@ class DropdownButton<T> extends StatefulWidget {
...
+    this.itemHeight = kMinInteractiveDimension,
+    this.focusColor,
+    this.focusNode,
+    this.autofocus = false,
+    this.dropdownColor,
+    this.menuMaxHeight,
+    this.enableFeedback,
+    this.alignment = AlignmentDirectional.centerStart,
+    this.borderRadius,
+    required InputDecoration? inputDecoration,
```
Comment (werainkhatri) [inline packages/flutter/lib/src/material/dropdown.dart:930]: I still feel like this can be non-nullable (maybe I'm missing something badly). `_inputDecoration` will remain nullable, and will take a null value for the public constructor and *this* non-null value for the private constructor. Anyway, in the state widget, we'll be using `widget._inputDecoration` which has a different null and non-null meaning.

File: packages/flutter/test/material/dropdown_test.dart [hunk 15]
```diff
@@ -2395,27 +2395,27 @@ void main() {
     final UniqueKey buttonKey = UniqueKey();
     final FocusNode focusNode = FocusNode(debugLabel: 'DropdownButton');
     await tester.pumpWidget(buildFrame(buttonKey: buttonKey, onChanged: onChanged, focusNode: focusNode, autofocus: true));
-    await tester.pump(); // Pump a frame for autofocus to take effect.
+    await tester.pumpAndSettle(); // Pump a frame for autofocus to take effect.
     expect(focusNode.hasPrimaryFocus, isTrue);
-    final Finder buttonFinder = find.byKey(buttonKey);
-    expect(buttonFinder, paints ..rrect(rrect: const RRect.fromLTRBXY(0.0, 0.0, 104.0, 48.0, 4.0, 4.0), color: const Color(0x1f000000)));
+    expect(find.byType(Material), paints ..rect(rect: const Rect.fromLTRB(348.0, 276.0, 452.0, 324.0), color: const Color(0x1f000000)));
```
Comment (werainkhatri) [inline packages/flutter/test/material/dropdown_test.dart:2400]: Nit.
here and on lines 2404, 2414, and 2418.

```suggestion
    expect(find.byType(Material), paints..rect(rect: const Rect.fromLTRB(348.0, 276.0, 452.0, 324.0), color: const Color(0x1f000000)));
```

**Review by werainkhatri — APPROVED** [review]
This LGTM and sorry about the delay. Just a few minor nit fixes.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

File: packages/flutter/lib/src/material/dropdown.dart (hunk 14 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dropdown.dart]: I was meaning removing it, forgot , thanks

File: packages/flutter/test/material/dropdown_test.dart (hunk 15 above)
Comment (TahaTesser) [reply packages/flutter/test/material/dropdown_test.dart]: Good catch

File: packages/flutter/lib/src/material/dropdown.dart (hunk 12 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dropdown.dart]: I am removing it for the private constructor which I added to this PR
For the public constructor, I think it is nice to have more documentation than less, in case somebody needs to know why they need to add those arguments, why it is "forced" by the analyzer.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 13 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/dropdown.dart]: I will need to pay more attention to small changes, thanks

**Comment by iqfareez** [comment]
Hi. When can we expect this pr make its way to stable?
