### PR TITLE
Recognize offline status in adb

### LINKED ISSUE #858: Failed to recognize offline device
If an attached device is offline, `flutter start` will fail with this:

```
$ flutter start
Downloading linux-x64 artifacts from the cloud, one moment please...
Downloading android-arm artifacts from the cloud, one moment please...
warning: Unexpected failure parsing device information from adb output:
04032ab809ef3131       offline usb:3-4
Please report a bug at https://github.com/flutter/flutter/issues/new
severe: Unable to run application - no connected devices.
```

### PR DESCRIPTION
**Pull request by abarth**
Fixes #858

### CODE REVIEW

File: packages/flutter_tools/lib/src/device.dart [hunk 1]
```diff
@@ -556,6 +556,10 @@ class AndroidDevice extends Device {
           'Device $deviceID is not authorized.\n'
           'You might need to check your device for an authorization dialog.'
         );
+      } else if (offlineRegex.hasMatch(line)) {
+        Match match = offlineRegex.firstMatch(line);
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/device.dart]: not that it matters here but in general hasMatch() followed by firstMatch() is duplication of potentially significant effort.

**Comment by Hixie** [comment]
LGTM

File: packages/flutter_tools/lib/src/device.dart (hunk 1 above)
Comment (abarth) [inline packages/flutter_tools/lib/src/device.dart]: Yeah, these regexps are also pretty redundant.  We could probably match them at once.
