### PR TITLE
Fix disallowIndicator for RefreshIndicator

### LINKED ISSUE #106832: RefreshIndicator does not disallow stretch indicator
RefreshIndicator calls `disallowGlow`, this is an old deprecated method that has been replaced with `disallowIndicator` to account for more than one type of overscroll indicator.

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/106832

This updates the RefreshIndicator to call disallowIndicator instead of disallowGlow, in order to account for more than one indicator (like the Material3 stretch indicator).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by TahaTesser — APPROVED** [review]
LGTM with nit.

File: packages/flutter/test/material/refresh_indicator_test.dart [hunk 1]
```diff
@@ -902,4 +902,106 @@ void main() {
     await tester.pump(const Duration(seconds: 1)); // finish the indicator hide animation
     expect(refreshCalled, true);
   });
+
+  testWidgets('RefreshIndicator disallows indicator - glow', (WidgetTester tester) async {
+    refreshCalled = false;
+    bool glowAccepted = true;
+    ScrollNotification? lastNotification;
+    await tester.pumpWidget(
```
Comment (Piinks) [inline packages/flutter/test/material/refresh_indicator_test.dart:910]:
```suggestion

    await tester.pumpWidget(
```
