### PR TITLE
Fix Android Studio detection and plugins on Linux

### LINKED ISSUE #75590: flutter doctor doesn't detect Android Studio installed with Jetbrains toolbox
[Jetbrains toolbox ](https://www.jetbrains.com/toolbox-app/) allows you to install/upgrade/uninstall their differents IDE (+ Android Studio). But `flutter doctor` doesn't detect it (at least on Linux)
The .desktop is located  inside the standard directory for that :  ```$HOME/.local/share/applications```

Screenshot_20210207_164905

```
$ cat .local/share/applications/jetbrains-studio.desktop
[Desktop Entry]
Name=Android Studio
Icon=/home/william/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/.icon.svg
StartupWMClass=jetbrains-studio
Comment=Everything you need to build on Android
Exec="/home/william/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/bin/studio.sh" %f
Version=1.0
Type=Application
Categories=Development;IDE;
Terminal=false
StartupNotify=true%
```

```
[✓] Flutter (Channel dev, 1.26.0-17.2.pre, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.26.0-17.2.pre at /home/william/Documents/flutter
    • Framework revision 79b49b9e10 (il y a 4 jours), 2021-02-03 15:33:39 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/william/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.0.0 (Fedora 11.0.0-2.fc33)
    • cmake version 3.18.4
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.53.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 2 categories.
```

### PR DESCRIPTION
**Pull request by woprandi**
This fixes the Android Studio installation detection on Linux since the plugins/config location has been changed since v4.1

Fixes https://github.com/flutter/flutter/issues/75590

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
We shouldn't change the android studio detector to remove old version detectors. Instead, lets add the new 4.1 paths to the search

**Comment by woprandi** [comment]
@jonahwilliams I'll update that

**Comment by woprandi** [comment]
@jonahwilliams I have updated my PR

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 1]
```diff
@@ -161,6 +169,23 @@ class AndroidStudio implements Comparable<AndroidStudio> {
...
       }
     } else {
+      // JetBrains Toolbox write plugins here
+      final String toolboxPluginsPath = '$directory.plugins';
+
+      if (globals.fs.directory(toolboxPluginsPath).existsSync()) {
+        return toolboxPluginsPath;
+      }
+
+      if (major >= 4 && minor >= 1 && globals.platform.isLinux) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/android_studio.dart:179]: major and minor can both be null

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 2]
```diff
@@ -259,7 +285,7 @@ class AndroidStudio implements Comparable<AndroidStudio> {
   static List<AndroidStudio> _allLinuxOrWindows() {
     final List<AndroidStudio> studios = <AndroidStudio>[];
 
-    bool _hasStudioAt(String path, { Version newerThan }) {
+    bool _hasStudioAt(String path, {Version newerThan}) {
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/android_studio.dart:288]: nit: revert unrelated change

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 3]
```diff
@@ -271,22 +297,48 @@ class AndroidStudio implements Comparable<AndroidStudio> {
       });
     }
 
-    // Read all $HOME/.AndroidStudio*/system/.home files. There may be several
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/android_studio.dart:274]: nit: revert unrelated change

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 4]
```diff
@@ -271,22 +297,48 @@ class AndroidStudio implements Comparable<AndroidStudio> {
...
-    // pointing to the same installation, so we grab only the latest one.
-    if (globals.fsUtils.homeDirPath != null &&
-        globals.fs.directory(globals.fsUtils.homeDirPath).existsSync()) {
-      final Directory homeDir = globals.fs.directory(globals.fsUtils.homeDirPath);
-      for (final Directory entity in homeDir.listSync(followLinks: false).whereType<Directory>()) {
-        if (!entity.basename.startsWith('.AndroidStudio')) {
-          continue;
-        }
+    // Read all $HOME/.AndroidStudio*/system/.home
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/android_studio.dart:300]: Because you reformatted this significantly, it is difficult to tell what is existing logic and what is new. For future PRs, you should try to keep your diff as small as possible

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 5]
```diff
@@ -271,22 +297,48 @@ class AndroidStudio implements Comparable<AndroidStudio> {
...
+    // so we grab only the latest one.
+    final String homeDirPath = globals.fsUtils.homeDirPath;
+
+    if (homeDirPath != null && globals.fs.directory(homeDirPath).existsSync()) {
+      final Directory homeDir = globals.fs.directory(homeDirPath);
+
+      // List of directories to search an installation
+      final List<Directory> directoriesToSearch = <Directory>[homeDir];
+
+      // >=4.1 has new install location at $HOME/.cache/Google
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/android_studio.dart:312]: This is a good comment

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 6]
```diff
@@ -110,13 +111,20 @@ class AndroidStudio implements Comparable<AndroidStudio> {
           .file(globals.fs.path.join(homeDotDir.path, 'system', '.home'))
           .readAsStringSync();
     } on Exception {
-      // ignored, installPath will be null, which is handled below
+      try {
+        installPath = globals.fs
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/android_studio.dart:115]: Can you explain this change?

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 7]
```diff
@@ -19,13 +19,14 @@ AndroidStudio get androidStudio => context.get<AndroidStudio>();
...
 // $HOME/.AndroidStudioX.Y/system/.home
+// $HOME/.cache/Google/AndroidStudioX.Y/.home
 
 // macOS:
 // /Applications/Android Studio.app/Contents/
 // $HOME/Applications/Android Studio.app/Contents/
 
 final RegExp _dotHomeStudioVersionMatcher =
-    RegExp(r'^\.(AndroidStudio[^\d]*)([\d.]+)');
+    RegExp(r'^\.?(AndroidStudio[^\d]*)([\d.]+)');
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/android_studio.dart:29]: What else are you trying to match with this regex, could you document that?

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 8]
```diff
@@ -271,22 +297,48 @@ class AndroidStudio implements Comparable<AndroidStudio> {
...
+    // Read all $HOME/.AndroidStudio*/system/.home
+    // or $HOME/.cache/Google/AndroidStudio*/.home files.
+    // There may be several pointing to the same installation,
+    // so we grab only the latest one.
+    final String homeDirPath = globals.fsUtils.homeDirPath;
+
+    if (homeDirPath != null && globals.fs.directory(homeDirPath).existsSync()) {
+      final Directory homeDir = globals.fs.directory(homeDirPath);
+
+      // List of directories to search an installation
```
Comment (jonahwilliams) [inline packages/flutter_tools/lib/src/android/android_studio.dart:309]: Avoid adding comments that describe what the code is doing exactly, also on L316 + L321

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 6 above)
Comment (woprandi) [reply packages/flutter_tools/lib/src/android/android_studio.dart]: I reworked this block, it's clearer now

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 4 above)
Comment (woprandi) [reply packages/flutter_tools/lib/src/android/android_studio.dart:311]: The base directory location, it name and the location of the `.home` text file has changed. I had to adapt the code to work on both cases without duplication.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Thank you for the fix, and sorry for the delay in reviewing!

**Comment by woprandi** [comment]
@jonahwilliams No problem, thank you for the merge

**Comment by brent-stone** [comment]
For anyone else coming here from the top google result and having issues with Android Studio installed using **Jetbrains Toolbox on Windows**, the command (or something very similar) needed to get` flutter doctor` to detect your install is:

`flutter config --android-studio-dir "D:\Program Files (x86)\JetBrains\apps\AndroidStudio"`
