### PR TITLE
Document how to hide counter in TextField.maxLength

### LINKED ISSUE #99914: #26343 is back. TextField hint and input text vertically outside constraints.
## Steps to Reproduce

Use a TextField as shown below, without including a String for the counterText.

To see the problem get fixed, uncomment the counterText in the sample code below.
```

import 'package:flutter/material.dart';

main() {
  runApp(
    const MaterialApp(
      home: Material(
        child: SizedBox.expand(
          child: ColoredBox(
            color: Color(0xFF000000),
            child: Center(
              child: SearchBox(),
            ),
          ),
        ),
      ),
    ),
  );
}

/// A decorated TextField that allows the user to enter a search term.
class SearchBox extends StatefulWidget {
  /// Constructor for the SearchBox.
  const SearchBox({
    Key? key,
  }) : super(key: key);

  @override
  _SearchBoxState createState() => _SearchBoxState();
}

class _SearchBoxState extends State<SearchBox> {
  final TextEditingController emailController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SizedBox(
        height: 46.0,
        width: 425.0,
        child: DecoratedBox(
          decoration: BoxDecoration(
            color: const Color(0xFF2c3e57),
            borderRadius: BorderRadius.circular(23.0),
          ),
          child: Row(
            children: [
              const SizedBox(width: 16.0),
              const Padding(
                padding: EdgeInsets.only(top: 4.0),
                child: Icon(
                  Icons.search,
                  color: Color(0xFFDDDDDD),
                  size: 32.0,
                ),
              ),
              const SizedBox(width: 8.0),
              Expanded(
                child: TextField(
                  maxLength: 44,
                  maxLines: 1,
                  autocorrect: false,
                  enableSuggestions: false,
                  style: Theme.of(context).textTheme.headlineSmall!.copyWith(
                        color: const Color(0xFFDDDDDD),
                      ),
                  decoration: InputDecoration(
                    // TODO Uncomment the counter text parameter to solve the issue.
                    // counterText: '',
                    border: InputBorder.none,
                    enabledBorder: InputBorder.none,
                    focusedBorder: InputBorder.none,
                    focusedErrorBorder: InputBorder.none,
                    filled: false,
                    hintText: 'Issue: Hint & input text too high.',
                    hintStyle: Theme.of(context).textTheme.headlineSmall!.copyWith(
                          color: const Color(0xFFDDDDDD),
                        ),
                  ),
                  controller: TextEditingController(),
                  // TODO implement on(Something) here.
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

image

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR adds some documentation to TextField.maxLength mentionning how to remove the counter.
See https://github.com/flutter/flutter/issues/99914#issuecomment-2871088451 for context.

## Related Issue

Fixes [TextField hint and input text go outside of given constraints](https://github.com/flutter/flutter/issues/99914)  

## Tests

Documentation only.

### CODE REVIEW

File: packages/flutter/lib/src/material/text_field.dart [hunk 1]
```diff
@@ -548,6 +548,7 @@ class TextField extends StatefulWidget {
   /// field showing how many characters have been entered. If set to a number
   /// greater than 0, it will also display the maximum number allowed. If set
   /// to [TextField.noMaxLength] then only the current character count is displayed.
+  /// To remove the counter, set [InputDecoration.counterText] to an empty string.
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_field.dart]: Would it be worth it to also mention that you can return null from buildCounter or is that overkill here?

**Review by justinmc — APPROVED** [review]
LGTM 👍 . Good call, we should definitely mention this.

File: packages/flutter/lib/src/material/text_field.dart (hunk 1 above)
Comment (bleroux) [reply packages/flutter/lib/src/material/text_field.dart]: Great! I think it makes sense to mention buildCounter. I will update the PR.
