### PR TITLE
Call `markNeedsPaint` when adding overlayChild to `Overlay`

### LINKED ISSUE #134656: Tooltip doesn't disappear when wrapped inside MouseRegion (Web)
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am using MouseRegion to show an IconButton when the mouse enters the region and hides the button when the mouse exits the region. The IconButton has a tooltip and shows correctly, however, the tooltip doesn't disappear when moving the mouse vertically away from the tooltip.

flutter_tooltip_bug_aNvhh8aklk

### Expected results

The tooltip disappears when moving the mouse vertically.

### Actual results

The tooltip sticks until the same tooltip is shown again.

### Code sample

<details><summary>Code sample</summary>

```dart
class TooltipExamplePage extends StatefulWidget {
  const TooltipExamplePage({super.key});

  @override
  State<TooltipExamplePage> createState() => _TooltipExamplePageState();
}

class _TooltipExamplePageState extends State<TooltipExamplePage> {
  bool showButton = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.blueGrey,
        child: Center(
          child: MouseRegion(
              onEnter: (event) => _showButton(true),
              onExit: (event) => _showButton(false),
              child: Container(
                  color: Colors.white,
                  height: 50,
                  width: 100,
                  child: Stack(
                    children: [
                      const Center(child: Text('HOVER HERE')),
                      if (showButton)
                        Positioned(
                          top: 0,
                          right: 0,
                          child: IconButton(
                            onPressed: () {},
                            icon: const Icon(Icons.delete),
                            tooltip: 'Tooltip Example',
                          ),
                        )
                    ],
                  ))),
        ),
      ),
    );
  }

  void _showButton(bool show) {
    setState(() {
      showButton = show;
    });
  }
}
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.22621.2283], locale en-US)
    • Flutter version 3.13.3 on channel stable at C:\Users\User\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (7 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33723.286
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.82.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.188
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.76

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/134656

`_skipMarkNeesLayout` was meant to only skip `markNeedsLayout` calls. Re-painting is still needed when a child gets added/removed from the `Overlay`.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/tooltip_theme_test.dart [hunk 1]
```diff
@@ -13,23 +13,6 @@ import '../widgets/semantics_tester.dart';
 const String tooltipText = 'TIP';
 const double _customPaddingValue = 10.0;
 
-void _ensureTooltipVisible(GlobalKey key) {
```
Comment (goderbauer) [inline packages/flutter/test/material/tooltip_theme_test.dart:16]: nice clean-up!

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by HeinrichJanzing** [comment]
@LongCatIsLooong apologies if this is not the right way, but would you not consider backporting the fix for 3.16 (and maybe even 3.13)? We cannot yet upgrade to Flutter 3.19. Apparently creating a [CP] issue is the prerogative of the "contributor" - I guess that would be you. 

Both 3.13 and 3.16 include the broken OverlayPortal implementation. Unrelated to tooltips, we ran into a similar problem when using a conditionally built OverlayPortal directly: when the OverlayPortal is removed from the tree its overlay remains visible until something forces the right repaint (like a window size change).

**Comment by LongCatIsLooong** [comment]
@HeinrichJanzing according to https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process#what-if-the-issue-is-on-a-previous-stable it seems such process does exist. But the wiki also says the anyone can create CP requests. Could you follow https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process#flutter-cherry-pick-process and see if you hit any obstacles?
