### PR TITLE
Navigator pushAndRemoveUntil Fix

### LINKED ISSUE #22025: 'package:flutter/src/widgets/heroes.dart': Failed assertion
```
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate(15224): onResume setting current activity to this
Syncing files to device Pixel XL...
I/flutter (15224): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (15224): The following assertion was thrown during a scheduler callback:
I/flutter (15224): 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 322 pos 12: '() {
I/flutter (15224):       final Animation<double> initial = initialManifest.animation;
I/flutter (15224):       switch (initialManifest.type) {
I/flutter (15224):         case _HeroFlightType.pop:
I/flutter (15224):           return initial.value == 1.0 && initial.status == AnimationStatus.reverse;
I/flutter (15224):         case _HeroFlightType.push:
I/flutter (15224):           return initial.value == 0.0 && initial.status == AnimationStatus.forward;
I/flutter (15224):       }
I/flutter (15224):     }()': is not true.
I/flutter (15224):
I/flutter (15224): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15224): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15224): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15224):   https://github.com/flutter/flutter/issues/new
I/flutter (15224):
I/flutter (15224): When the exception was thrown, this was the stack:
I/flutter (15224): #2      _HeroFlight.start (package:flutter/src/widgets/heroes.dart)
I/flutter (15224): #3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:532:64)
I/flutter (15224): #4      HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:492:9)
I/flutter (15224): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (15224): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:938:9)
I/flutter (15224): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (15224): #9      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (15224): #10     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (15224): #11     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (15224): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (15224): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/FlutterActivityDelegate(15224): onResume setting current activity to this
```

### LINKED ISSUE #25080: pushAndRemoveUntil not play push animation if remove all except the first route
## Steps to Reproduce

1. run example
2. tap "push" button 
3. tap "pushAndRemoveUntil" button
4. push animation not played

example:
```dart
import 'package:flutter/material.dart';
import 'dart:math';

void main() {
  runApp(MaterialApp(
    home: Page(),
  ));
}

class Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color((Random().nextDouble() * 0xFFFFFF).toInt() << 0)
          .withOpacity(1.0),
      appBar: AppBar(
        title: Text(new DateTime.now().millisecondsSinceEpoch.toString()),
      ),
      body: Column(
        children: <Widget>[
          RaisedButton(
            child: Text('pushAndRemoveUntil'),
            onPressed: () {
              var navigator = Navigator.of(context);

              var route = MaterialPageRoute(
                  builder: ((BuildContext context) => Page()));
              navigator.pushAndRemoveUntil(route, (Route<dynamic> route) {
                print(route);
                return route.isFirst;
              });
            },
          ),
          RaisedButton(
            child: Text('push'),
            onPressed: () {
              var navigator = Navigator.of(context);

              navigator.push(
                  MaterialPageRoute(
                      builder: (BuildContext context) => Page()));
            },
          ),
        ],
      ),
    );
  }
}
```

not_animation_route

doctor

```
Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale ru-RU)
    • Flutter version 1.0.0 at /Users/ik/Repositories/flutter
    • Framework revision 5391447fae (7 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/ik/Library/Android/sdk
    • Android NDK at /Users/ik/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] Connected device (2 available)
    • iPhone 6  • D0700405-7A5D-498F-A980-BC6D4F1E9E46 • ios • iOS 12.0
      (simulator)
    • iPhone SE • 91A75C13-5F1C-4551-9917-5848E90CF772 • ios • iOS 12.0
      (simulator)
```

### LINKED ISSUE #28980: Heroes Failed assertion: line 248 pos 12: 'box != null && box.hasSize': is not true.
## Steps to Reproduce
https://gist.github.com/ToxicAlex/28819a330a3f9888e011bb5a61574fc2

When navigating back two or more routes using pushAndRemoveUntil with a common Hero across all three pages, an assertion error is thrown.

In the given gist: 
1. Click on the box two times to navigate to the third page.
2. Click once more to call Navigator.pushAndRemoveUntil

## Logs

```
                    generateDynamicProfileFeatureMetadata: task ':app:generateDynamicProfileFeatureMetadata'
                    generateDynamicProfileFeatureTransitiveDeps: task ':app:generateDynamicProfileFeatureTransitiveDeps'
                    generateDynamicProfileResValues: task ':app:generateDynamicProfileResValues'
                    generateDynamicProfileResources: task ':app:generateDynamicProfileResources'
                    generateDynamicProfileSources: task ':app:generateDynamicProfileSources'
                    generateDynamicProfileUnitTestAssets: task ':app:generateDynamicProfileUnitTestAssets'
                    generateDynamicProfileUnitTestResources: task ':app:generateDynamicProfileUnitTestResources'
                    generateDynamicProfileUnitTestSources: task ':app:generateDynamicProfileUnitTestSources'
                    generateDynamicReleaseAssets: task ':app:generateDynamicReleaseAssets'
                    generateDynamicReleaseBuildConfig: task ':app:generateDynamicReleaseBuildConfig'
                    generateDynamicReleaseFeatureMetadata: task ':app:generateDynamicReleaseFeatureMetadata'
                    generateDynamicReleaseFeatureTransitiveDeps: task ':app:generateDynamicReleaseFeatureTransitiveDeps'
                    generateDynamicReleaseResValues: task ':app:generateDynamicReleaseResValues'
                    generateDynamicReleaseResources: task ':app:generateDynamicReleaseResources'
                    generateDynamicReleaseSources: task ':app:generateDynamicReleaseSources'
                    generateDynamicReleaseUnitTestAssets: task ':app:generateDynamicReleaseUnitTestAssets'
                    generateDynamicReleaseUnitTestResources: task ':app:generateDynamicReleaseUnitTestResources'
                    generateDynamicReleaseUnitTestSources: task ':app:generateDynamicReleaseUnitTestSources'
                    generateProfileAssets: task ':app:generateProfileAssets'
                    generateProfileBuildConfig: task ':app:generateProfileBuildConfig'
                    generateProfileFeatureMetadata: task ':app:generateProfileFeatureMetadata'
                    generateProfileFeatureTransitiveDeps: task ':app:generateProfileFeatureTransitiveDeps'
                    generateProfileResValues: task ':app:generateProfileResValues'
                    generateProfileResources: task ':app:generateProfileResources'
                    generateProfileSources: task ':app:generateProfileSources'
                    generateProfileUnitTestAssets: task ':app:generateProfileUnitTestAssets'
                    generateProfileUnitTestResources: task ':app:generateProfileUnitTestResources'
                    generateProfileUnitTestSources: task ':app:generateProfileUnitTestSources'
                    generateReleaseAssets: task ':app:generateReleaseAssets'
                    generateReleaseBuildConfig: task ':app:generateReleaseBuildConfig'
                    generateReleaseFeatureMetadata: task ':app:generateReleaseFeatureMetadata'
                    generateReleaseFeatureTransitiveDeps: task ':app:generateReleaseFeatureTransitiveDeps'
                    generateReleaseResValues: task ':app:generateReleaseResValues'
                    generateReleaseResources: task ':app:generateReleaseResources'
                    generateReleaseSources: task ':app:generateReleaseSources'
                    generateReleaseUnitTestAssets: task ':app:generateReleaseUnitTestAssets'
                    generateReleaseUnitTestResources: task ':app:generateReleaseUnitTestResources'
                    generateReleaseUnitTestSources: task ':app:generateReleaseUnitTestSources'
                    gradle: build 'android'
                    group: android
                    identityPath: :app
                    inheritedScope: org.gradle.api.internal.ExtensibleDynamicObject$InheritedDynamicObject@2f993173
                    installDebug: task ':app:installDebug'
                    installDebugAndroidTest: task ':app:installDebugAndroidTest'
                    installDynamicProfile: task ':app:installDynamicProfile'
                    installDynamicRelease: task ':app:installDynamicRelease'
                    installProfile: task ':app:installProfile'
                    installRelease: task ':app:installRelease'
                    java: org.gradle.api.plugins.internal.DefaultJavaPluginExtension_Decorated@1a642f07
                    javaPreCompileDebug: task ':app:javaPreCompileDebug'
                    javaPreCompileDebugAndroidTest: task ':app:javaPreCompileDebugAndroidTest'
                    javaPreCompileDebugUnitTest: task ':app:javaPreCompileDebugUnitTest'
                    javaPreCompileDynamicProfile: task ':app:javaPreCompileDynamicProfile'
                    javaPreCompileDynamicProfileUnitTest: task ':app:javaPreCompileDynamicProfileUnitTest'
                    javaPreCompileDynamicRelease: task ':app:javaPreCompileDynamicRelease'
                    javaPreCompileDynamicReleaseUnitTest: task ':app:javaPreCompileDynamicReleaseUnitTest'
                    javaPreCompileProfile: task ':app:javaPreCompileProfile'
                    javaPreCompileProfileUnitTest: task ':app:javaPreCompileProfileUnitTest'
                    javaPreCompileRelease: task ':app:javaPreCompileRelease'
                    javaPreCompileReleaseUnitTest: task ':app:javaPreCompileReleaseUnitTest'
                    layout: org.gradle.api.internal.file.DefaultProjectLayout@11b7c4e9
                    libsDir: C:\Users\Admin\Documents\flutter\hero_bug\build\app\libs
                    libsDirName: libs
                    lint: task ':app:lint'
                    lintDebug: task ':app:lintDebug'
                    lintDynamicProfile: task ':app:lintDynamicProfile'
                    lintDynamicRelease: task ':app:lintDynamicRelease'
                    lintFix: task ':app:lintFix'
                    lintProfile: task ':app:lintProfile'
                    lintRelease: task ':app:lintRelease'
                    lintVitalRelease: task ':app:lintVitalRelease'
                    listenerBuildOperationDecorator: org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator@72421568
                    logger: org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger@2051ac91
                    logging: org.gradle.internal.logging.services.DefaultLoggingManager@1436a0fa
                    mainApkListPersistenceDebug: task ':app:mainApkListPersistenceDebug'
                    mainApkListPersistenceDebugAndroidTest: task ':app:mainApkListPersistenceDebugAndroidTest'
                    mainApkListPersistenceDynamicProfile: task ':app:mainApkListPersistenceDynamicProfile'
                    mainApkListPersistenceDynamicRelease: task ':app:mainApkListPersistenceDynamicRelease'
                    mainApkListPersistenceProfile: task ':app:mainApkListPersistenceProfile'
                    mainApkListPersistenceRelease: task ':app:mainApkListPersistenceRelease'
                    makeApkFromBundleForDebug: task ':app:makeApkFromBundleForDebug'
                    makeApkFromBundleForDynamicProfile: task ':app:makeApkFromBundleForDynamicProfile'
                    makeApkFromBundleForDynamicRelease: task ':app:makeApkFromBundleForDynamicRelease'
                    makeApkFromBundleForProfile: task ':app:makeApkFromBundleForProfile'
                    makeApkFromBundleForRelease: task ':app:makeApkFromBundleForRelease'
                    mergeDebugAndroidTestAssets: task ':app:mergeDebugAndroidTestAssets'
                    mergeDebugAndroidTestJniLibFolders: task ':app:mergeDebugAndroidTestJniLibFolders'
                    mergeDebugAndroidTestResources: task ':app:mergeDebugAndroidTestResources'
                    mergeDebugAndroidTestShaders: task ':app:mergeDebugAndroidTestShaders'
                    mergeDebugAssets: task ':app:mergeDebugAssets'
                    mergeDebugJniLibFolders: task ':app:mergeDebugJniLibFolders'
                    mergeDebugResources: task ':app:mergeDebugResources'
                    mergeDebugShaders: task ':app:mergeDebugShaders'
                    mergeDynamicProfileAssets: task ':app:mergeDynamicProfileAssets'
                    mergeDynamicProfileJniLibFolders: task ':app:mergeDynamicProfileJniLibFolders'
                    mergeDynamicProfileResources: task ':app:mergeDynamicProfileResources'
                    mergeDynamicProfileShaders: task ':app:mergeDynamicProfileShaders'
                    mergeDynamicReleaseAssets: task ':app:mergeDynamicReleaseAssets'
                    mergeDynamicReleaseJniLibFolders: task ':app:mergeDynamicReleaseJniLibFolders'
                    mergeDynamicReleaseResources: task ':app:mergeDynamicReleaseResources'
                    mergeDynamicReleaseShaders: task ':app:mergeDynamicReleaseShaders'
                    mergeProfileAssets: task ':app:mergeProfileAssets'
                    mergeProfileJniLibFolders: task ':app:mergeProfileJniLibFolders'
                    mergeProfileResources: task ':app:mergeProfileResources'
                    mergeProfileShaders: task ':app:mergeProfileShaders'
                    mergeReleaseAssets: task ':app:mergeReleaseAssets'
                    mergeReleaseJniLibFolders: task ':app:mergeReleaseJniLibFolders'
                    mergeReleaseResources: task ':app:mergeReleaseResources'
                    mergeReleaseShaders: task ':app:mergeReleaseShaders'
                    modelRegistry: org.gradle.model.internal.registry.DefaultModelRegistry@2f11a96c
                    modelSchemaStore: org.gradle.model.internal.manage.schema.extract.DefaultModelSchemaStore@4147051b
                    module: org.gradle.api.internal.artifacts.ProjectBackedModule@cf2f21f
                    name: app
                    normalization: org.gradle.normalization.internal.DefaultInputNormalizationHandler_Decorated@2eb0eb
                    objects: org.gradle.api.internal.model.DefaultObjectFactory@62a51cd3
                    org.gradle.jvmargs: -Xmx1536M
                    packageAppClassesDebug: task ':app:packageAppClassesDebug'
                    packageAppClassesDebugAndroidTest: task ':app:packageAppClassesDebugAndroidTest'
                    packageAppClassesDebugUnitTest: task ':app:packageAppClassesDebugUnitTest'
                    packageAppClassesDynamicProfile: task ':app:packageAppClassesDynamicProfile'
                    packageAppClassesDynamicProfileUnitTest: task ':app:packageAppClassesDynamicProfileUnitTest'
                    packageAppClassesDynamicRelease: task ':app:packageAppClassesDynamicRelease'
                    packageAppClassesDynamicReleaseUnitTest: task ':app:packageAppClassesDynamicReleaseUnitTest'
                    packageAppClassesProfile: task ':app:packageAppClassesProfile'
                    packageAppClassesProfileUnitTest: task ':app:packageAppClassesProfileUnitTest'
                    packageAppClassesRelease: task ':app:packageAppClassesRelease'
                    packageAppClassesReleaseUnitTest: task ':app:packageAppClassesReleaseUnitTest'
                    packageDebug: task ':app:packageDebug'
                    packageDebugAndroidTest: task ':app:packageDebugAndroidTest'
                    packageDebugBundle: task ':app:packageDebugBundle'
                    packageDebugUniversalApk: task ':app:packageDebugUniversalApk'
                    packageDynamicProfile: task ':app:packageDynamicProfile'
                    packageDynamicProfileBundle: task ':app:packageDynamicProfileBundle'
                    packageDynamicProfileUniversalApk: task ':app:packageDynamicProfileUniversalApk'
                    packageDynamicRelease: task ':app:packageDynamicRelease'
                    packageDynamicReleaseBundle: task ':app:packageDynamicReleaseBundle'
                    packageDynamicReleaseUniversalApk: task ':app:packageDynamicReleaseUniversalApk'
                    packageProfile: task ':app:packageProfile'
                    packageProfileBundle: task ':app:packageProfileBundle'
                    packageProfileUniversalApk: task ':app:packageProfileUniversalApk'
                    packageRelease: task ':app:packageRelease'
                    packageReleaseBundle: task ':app:packageReleaseBundle'
                    packageReleaseUniversalApk: task ':app:packageReleaseUniversalApk'
                    parent: root project 'android'
                    parentIdentifier: root project 'android'
                    path: :app
                    pluginManager: org.gradle.api.internal.plugins.DefaultPluginManager_Decorated@4335410d
                    plugins: [org.gradle.api.plugins.HelpTasksPlugin@61cddace, com.android.build.gradle.api.AndroidBasePlugin@149187f4, org.gradle.language.base.plugins.LifecycleBasePlugin@5e184231, org.gradle.api.plugins.BasePlugin@37cc4dd6, org.gradle.api.plugins.ReportingBasePlugin@3858fa4b,
                    org.gradle.api.plugins.JavaBasePlugin@206e6493, com.android.build.gradle.AppPlugin@3c7ba365, FlutterPlugin@698cfbc1]
                    preBuild: task ':app:preBuild'
                    preDebugAndroidTestBuild: task ':app:preDebugAndroidTestBuild'
                    preDebugBuild: task ':app:preDebugBuild'
                    preDebugUnitTestBuild: task ':app:preDebugUnitTestBuild'
                    preDynamicProfileBuild: task ':app:preDynamicProfileBuild'
                    preDynamicProfileUnitTestBuild: task ':app:preDynamicProfileUnitTestBuild'
                    preDynamicReleaseBuild: task ':app:preDynamicReleaseBuild'
                    preDynamicReleaseUnitTestBuild: task ':app:preDynamicReleaseUnitTestBuild'
                    preProfileBuild: task ':app:preProfileBuild'
                    preProfileUnitTestBuild: task ':app:preProfileUnitTestBuild'
                    preReleaseBuild: task ':app:preReleaseBuild'
                    preReleaseUnitTestBuild: task ':app:preReleaseUnitTestBuild'
                    prepareLintJar: task ':app:prepareLintJar'
                    processDebugAndroidTestJavaRes: task ':app:processDebugAndroidTestJavaRes'
                    processDebugAndroidTestManifest: task ':app:processDebugAndroidTestManifest'
                    processDebugAndroidTestResources: task ':app:processDebugAndroidTestResources'
                    processDebugJavaRes: task ':app:processDebugJavaRes'
                    processDebugManifest: task ':app:processDebugManifest'
                    processDebugResources: task ':app:processDebugResources'
                    processDebugUnitTestJavaRes: task ':app:processDebugUnitTestJavaRes'
                    processDynamicProfileJavaRes: task ':app:processDynamicProfileJavaRes'
                    processDynamicProfileManifest: task ':app:processDynamicProfileManifest'
                    processDynamicProfileResources: task ':app:processDynamicProfileResources'
                    processDynamicProfileUnitTestJavaRes: task ':app:processDynamicProfileUnitTestJavaRes'
                    processDynamicReleaseJavaRes: task ':app:processDynamicReleaseJavaRes'
                    processDynamicReleaseManifest: task ':app:processDynamicReleaseManifest'
                    processDynamicReleaseResources: task ':app:processDynamicReleaseResources'
                    processDynamicReleaseUnitTestJavaRes: task ':app:processDynamicReleaseUnitTestJavaRes'
                    processOperations: org.gradle.api.internal.file.DefaultFileOperations@65663c4
                    processProfileJavaRes: task ':app:processProfileJavaRes'
                    processProfileManifest: task ':app:processProfileManifest'
                    processProfileResources: task ':app:processProfileResources'
                    processProfileUnitTestJavaRes: task ':app:processProfileUnitTestJavaRes'
                    processReleaseJavaRes: task ':app:processReleaseJavaRes'
                    processReleaseManifest: task ':app:processReleaseManifest'
                    processReleaseResources: task ':app:processReleaseResources'
                    processReleaseUnitTestJavaRes: task ':app:processReleaseUnitTestJavaRes'
                    project: project ':app'
                    projectConfigurator: org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator@1679de19
                    projectDir: C:\Users\Admin\Documents\flutter\hero_bug\android\app
                    projectEvaluationBroadcaster: ProjectEvaluationListener broadcast
                    projectEvaluator: org.gradle.configuration.project.LifecycleProjectEvaluator@45606ab9
                    projectPath: :app
                    projectRegistry: org.gradle.api.internal.project.DefaultProjectRegistry@24e189fb
                    properties: {...}
                    providers: org.gradle.api.internal.provider.DefaultProviderFactory@7d29b5a1
                    reportBuildArtifactsDebug: task ':app:reportBuildArtifactsDebug'
                    reportBuildArtifactsDynamicProfile: task ':app:reportBuildArtifactsDynamicProfile'
                    reportBuildArtifactsDynamicRelease: task ':app:reportBuildArtifactsDynamicRelease'
                    reportBuildArtifactsProfile: task ':app:reportBuildArtifactsProfile'
                    reportBuildArtifactsRelease: task ':app:reportBuildArtifactsRelease'
                    reportSourceSetTransformAndroidTest: task ':app:reportSourceSetTransformAndroidTest'
                    reportSourceSetTransformAndroidTestDebug: task ':app:reportSourceSetTransformAndroidTestDebug'
                    reportSourceSetTransformDebug: task ':app:reportSourceSetTransformDebug'
                    reportSourceSetTransformDynamicProfile: task ':app:reportSourceSetTransformDynamicProfile'
                    reportSourceSetTransformDynamicRelease: task ':app:reportSourceSetTransformDynamicRelease'
                    reportSourceSetTransformMain: task ':app:reportSourceSetTransformMain'
                    reportSourceSetTransformProfile: task ':app:reportSourceSetTransformProfile'
                    reportSourceSetTransformRelease: task ':app:reportSourceSetTransformRelease'
                    reportSourceSetTransformTest: task ':app:reportSourceSetTransformTest'
                    reportSourceSetTransformTestDebug: task ':app:reportSourceSetTransformTestDebug'
                    reportSourceSetTransformTestDynamicProfile: task ':app:reportSourceSetTransformTestDynamicProfile'
                    reportSourceSetTransformTestDynamicRelease: task ':app:reportSourceSetTransformTestDynamicRelease'
                    reportSourceSetTransformTestProfile: task ':app:reportSourceSetTransformTestProfile'
                    reportSourceSetTransformTestRelease: task ':app:reportSourceSetTransformTestRelease'
                    reporting: org.gradle.api.reporting.ReportingExtension_Decorated@2abd3c55
                    reportsDir: C:\Users\Admin\Documents\flutter\hero_bug\build\app\reports
                    repositories: repository container
                    resolveConfigAttr: task ':app:resolveConfigAttr'
                    resourceLoader: org.gradle.internal.resource.transfer.DefaultUriTextResourceLoader@72ecb60d
                    resources: org.gradle.api.internal.resources.DefaultResourceHandler@349f2f4b
                    rootDir: C:\Users\Admin\Documents\flutter\hero_bug\android
                    rootProject: root project 'android'
                    script: false
                    scriptHandlerFactory: org.gradle.api.internal.initialization.DefaultScriptHandlerFactory@1c99d672
                    scriptPluginFactory: org.gradle.configuration.ScriptPluginFactorySelector@5f850e20
                    serviceRegistryFactory: org.gradle.internal.service.scopes.ProjectScopeServices$4@48ce9703
                    services: ProjectScopeServices
                    signingReport: task ':app:signingReport'
                    sourceCompatibility: 1.8
                    sourceSets: SourceSet container
                    splitsDiscoveryTaskDebug: task ':app:splitsDiscoveryTaskDebug'
                    splitsDiscoveryTaskDynamicProfile: task ':app:splitsDiscoveryTaskDynamicProfile'
                    splitsDiscoveryTaskDynamicRelease: task ':app:splitsDiscoveryTaskDynamicRelease'
                    splitsDiscoveryTaskProfile: task ':app:splitsDiscoveryTaskProfile'
                    splitsDiscoveryTaskRelease: task ':app:splitsDiscoveryTaskRelease'
                    standardOutputCapture: org.gradle.internal.logging.services.DefaultLoggingManager@1436a0fa
                    state: project state 'EXECUTED'
                    status: integration
                    subprojects: []
                    targetCompatibility: 1.8
                    tasks: task set
                    test: task ':app:test'
                    testDebugUnitTest: task ':app:testDebugUnitTest'
                    testDynamicProfileUnitTest: task ':app:testDynamicProfileUnitTest'
                    testDynamicReleaseUnitTest: task ':app:testDynamicReleaseUnitTest'
                    testProfileUnitTest: task ':app:testProfileUnitTest'
                    testReleaseUnitTest: task ':app:testReleaseUnitTest'
                    testReportDir: C:\Users\Admin\Documents\flutter\hero_bug\build\app\reports\tests
                    testReportDirName: tests
                    testResultsDir: C:\Users\Admin\Documents\flutter\hero_bug\build\app\test-results
                    testResultsDirName: test-results
                    transformClassesWithDexBuilderForDebug: task ':app:transformClassesWithDexBuilderForDebug'
                    transformClassesWithDexBuilderForDebugAndroidTest: task ':app:transformClassesWithDexBuilderForDebugAndroidTest'
                    transformClassesWithDexBuilderForDynamicProfile: task ':app:transformClassesWithDexBuilderForDynamicProfile'
                    transformClassesWithDexBuilderForDynamicRelease: task ':app:transformClassesWithDexBuilderForDynamicRelease'
                    transformClassesWithDexBuilderForProfile: task ':app:transformClassesWithDexBuilderForProfile'
                    transformClassesWithDexBuilderForRelease: task ':app:transformClassesWithDexBuilderForRelease'
                    transformDexArchiveWithDexMergerForDebug: task ':app:transformDexArchiveWithDexMergerForDebug'
                    transformDexArchiveWithDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithDexMergerForDebugAndroidTest'
                    transformDexArchiveWithDexMergerForDynamicProfile: task ':app:transformDexArchiveWithDexMergerForDynamicProfile'
                    transformDexArchiveWithDexMergerForDynamicRelease: task ':app:transformDexArchiveWithDexMergerForDynamicRelease'
                    transformDexArchiveWithDexMergerForProfile: task ':app:transformDexArchiveWithDexMergerForProfile'
                    transformDexArchiveWithDexMergerForRelease: task ':app:transformDexArchiveWithDexMergerForRelease'
                    transformDexArchiveWithExternalLibsDexMergerForDebug: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'
                    transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'
                    transformDexArchiveWithExternalLibsDexMergerForDynamicProfile: task ':app:transformDexArchiveWithExternalLibsDexMergerForDynamicProfile'
                    transformDexArchiveWithExternalLibsDexMergerForDynamicRelease: task ':app:transformDexArchiveWithExternalLibsDexMergerForDynamicRelease'
                    transformDexArchiveWithExternalLibsDexMergerForProfile: task ':app:transformDexArchiveWithExternalLibsDexMergerForProfile'
                    transformDexArchiveWithExternalLibsDexMergerForRelease: task ':app:transformDexArchiveWithExternalLibsDexMergerForRelease'
                    transformNativeLibsWithMergeJniLibsForDebug: task ':app:transformNativeLibsWithMergeJniLibsForDebug'
                    transformNativeLibsWithMergeJniLibsForDebugAndroidTest: task ':app:transformNativeLibsWithMergeJniLibsForDebugAndroidTest'
                    transformNativeLibsWithMergeJniLibsForDynamicProfile: task ':app:transformNativeLibsWithMergeJniLibsForDynamicProfile'
                    transformNativeLibsWithMergeJniLibsForDynamicRelease: task ':app:transformNativeLibsWithMergeJniLibsForDynamicRelease'
                    transformNativeLibsWithMergeJniLibsForProfile: task ':app:transformNativeLibsWithMergeJniLibsForProfile'
                    transformNativeLibsWithMergeJniLibsForRelease: task ':app:transformNativeLibsWithMergeJniLibsForRelease'
                    transformResourcesWithMergeJavaResForDebug: task ':app:transformResourcesWithMergeJavaResForDebug'
                    transformResourcesWithMergeJavaResForDebugAndroidTest: task ':app:transformResourcesWithMergeJavaResForDebugAndroidTest'
                    transformResourcesWithMergeJavaResForDebugUnitTest: task ':app:transformResourcesWithMergeJavaResForDebugUnitTest'
                    transformResourcesWithMergeJavaResForDynamicProfile: task ':app:transformResourcesWithMergeJavaResForDynamicProfile'
                    transformResourcesWithMergeJavaResForDynamicProfileUnitTest: task ':app:transformResourcesWithMergeJavaResForDynamicProfileUnitTest'
                    transformResourcesWithMergeJavaResForDynamicRelease: task ':app:transformResourcesWithMergeJavaResForDynamicRelease'
                    transformResourcesWithMergeJavaResForDynamicReleaseUnitTest: task ':app:transformResourcesWithMergeJavaResForDynamicReleaseUnitTest'
                    transformResourcesWithMergeJavaResForProfile: task ':app:transformResourcesWithMergeJavaResForProfile'
                    transformResourcesWithMergeJavaResForProfileUnitTest: task ':app:transformResourcesWithMergeJavaResForProfileUnitTest'
                    transformResourcesWithMergeJavaResForRelease: task ':app:transformResourcesWithMergeJavaResForRelease'
                    transformResourcesWithMergeJavaResForReleaseUnitTest: task ':app:transformResourcesWithMergeJavaResForReleaseUnitTest'
                    uninstallAll: task ':app:uninstallAll'
                    uninstallDebug: task ':app:uninstallDebug'
                    uninstallDebugAndroidTest: task ':app:uninstallDebugAndroidTest'
                    uninstallDynamicProfile: task ':app:uninstallDynamicProfile'
                    uninstallDynamicRelease: task ':app:uninstallDynamicRelease'
                    uninstallProfile: task ':app:uninstallProfile'
                    uninstallRelease: task ':app:uninstallRelease'
                    validateSigningDebug: task ':app:validateSigningDebug'
                    validateSigningDebugAndroidTest: task ':app:validateSigningDebugAndroidTest'
                    validateSigningDynamicProfile: task ':app:validateSigningDynamicProfile'
                    validateSigningDynamicRelease: task ':app:validateSigningDynamicRelease'
                    validateSigningProfile: task ':app:validateSigningProfile'
                    validateSigningRelease: task ':app:validateSigningRelease'
                    version: unspecified
                    writeDebugApplicationId: task ':app:writeDebugApplicationId'
                    writeDynamicProfileApplicationId: task ':app:writeDynamicProfileApplicationId'
                    writeDynamicReleaseApplicationId: task ':app:writeDynamicReleaseApplicationId'
                    writeProfileApplicationId: task ':app:writeProfileApplicationId'
                    writeReleaseApplicationId: task ':app:writeReleaseApplicationId'
                    1 actionable task: 1 executed
[   +9 ms] executing: [C:\Users\Admin\Documents\flutter\hero_bug\android\] C:\Users\Admin\Documents\flutter\hero_bug\android\gradlew.bat app:tasks --all --console=auto
[+1041 ms]
                    > Task :app:tasks

                    ------------------------------------------------------------
                    All tasks runnable from project :app
                    ------------------------------------------------------------

                    Android tasks
                    -------------
                    androidDependencies - Displays the Android dependencies of the project.
                    signingReport - Displays the signing info for each variant.
                    sourceSets - Prints out all the source sets defined in this project.

                    Build tasks
                    -----------
                    assemble - Assembles all variants of all applications and secondary packages.
                    assembleAndroidTest - Assembles all the Test applications.
                    assembleDebug - Assembles all Debug builds.
                    assembleDynamicProfile - Assembles all DynamicProfile builds.
                    assembleDynamicRelease - Assembles all DynamicRelease builds.
                    assembleProfile - Assembles all Profile builds.
                    assembleRelease - Assembles all Release builds.
                    build - Assembles and tests this project.
                    buildDependents - Assembles and tests this project and all projects that depend on it.
                    buildNeeded - Assembles and tests this project and all projects it depends on.
                    bundleDebug - Creates all Debug bundles.
                    bundleDynamicProfile - Creates all DynamicProfile bundles.
                    bundleDynamicRelease - Creates all DynamicRelease bundles.
                    bundleProfile - Creates all Profile bundles.
                    bundleRelease - Creates all Release bundles.
                    clean - Deletes the build directory.
                    cleanBuildCache - Deletes the build cache directory.
                    compileDebugAndroidTestSources
                    compileDebugSources
                    compileDebugUnitTestSources
                    compileDynamicProfileSources
                    compileDynamicProfileUnitTestSources
                    compileDynamicReleaseSources
                    compileDynamicReleaseUnitTestSources
                    compileProfileSources
                    compileProfileUnitTestSources
                    compileReleaseSources
                    compileReleaseUnitTestSources

                    Cleanup tasks
                    -------------
                    lintFix - Runs lint on all variants and applies any safe suggestions to the source code.

                    Help tasks
                    ----------
                    buildEnvironment - Displays all buildscript dependencies declared in project ':app'.
                    components - Displays the components produced by project ':app'. [incubating]
                    dependencies - Displays all dependencies declared in project ':app'.
                    dependencyInsight - Displays the insight into a specific dependency in project ':app'.
                    dependentComponents - Displays the dependent components of components in project ':app'. [incubating]
                    help - Displays a help message.
                    model - Displays the configuration model of project ':app'. [incubating]
                    projects - Displays the sub-projects of project ':app'.
                    properties - Displays the properties of project ':app'.
                    tasks - Displays the tasks runnable from project ':app'.

                    Install tasks
                    -------------
                    installDebug - Installs the Debug build.
                    installDebugAndroidTest - Installs the android (on device) tests for the Debug build.
                    installDynamicProfile - Installs the DynamicProfile build.
                    installDynamicRelease - Installs the DynamicRelease build.
                    installProfile - Installs the Profile build.
                    installRelease - Installs the Release build.
                    uninstallAll - Uninstall all applications.
                    uninstallDebug - Uninstalls the Debug build.
                    uninstallDebugAndroidTest - Uninstalls the android (on device) tests for the Debug build.
                    uninstallDynamicProfile - Uninstalls the DynamicProfile build.
                    uninstallDynamicRelease - Uninstalls the DynamicRelease build.
                    uninstallProfile - Uninstalls the Profile build.
                    uninstallRelease - Uninstalls the Release build.

                    Verification tasks
                    ------------------
                    check - Runs all checks.
                    connectedAndroidTest - Installs and runs instrumentation tests for all flavors on connected devices.
                    connectedCheck - Runs all device checks on currently connected devices.
                    connectedDebugAndroidTest - Installs and runs the tests for debug on connected devices.
                    deviceAndroidTest - Installs and runs instrumentation tests using all Device Providers.
                    deviceCheck - Runs all device checks using Device Providers and Test Servers.
                    lint - Runs lint on all variants.
                    lintDebug - Runs lint on the Debug build.
                    lintDynamicProfile - Runs lint on the DynamicProfile build.
                    lintDynamicRelease - Runs lint on the DynamicRelease build.
                    lintProfile - Runs lint on the Profile build.
                    lintRelease - Runs lint on the Release build.
                    lintVitalRelease - Runs lint on just the fatal issues in the release build.
                    test - Run unit tests for all variants.
                    testDebugUnitTest - Run unit tests for the debug build.
                    testDynamicProfileUnitTest - Run unit tests for the dynamicProfile build.
                    testDynamicReleaseUnitTest - Run unit tests for the dynamicRelease build.
                    testProfileUnitTest - Run unit tests for the profile build.
                    testReleaseUnitTest - Run unit tests for the release build.

                    Other tasks
                    -----------
                    assembleDebugAndroidTest
                    assembleDebugUnitTest
                    assembleDynamicProfileUnitTest
                    assembleDynamicReleaseUnitTest
                    assembleProfileUnitTest
                    assembleReleaseUnitTest
                    buildDebugPreBundle
                    buildDynamicProfilePreBundle
                    buildDynamicReleasePreBundle
                    buildProfilePreBundle
                    buildReleasePreBundle
                    bundle
                    bundleDebugAndroidTestResources
                    bundleDebugResources
                    bundleDynamicProfileResources
                    bundleDynamicReleaseResources
                    bundleProfileResources
                    bundleReleaseResources
                    checkDebugAndroidTestClasspath
                    checkDebugClasspath
                    checkDebugLibraries
                    checkDebugManifest
                    checkDynamicProfileClasspath
                    checkDynamicProfileLibraries
                    checkDynamicProfileManifest
                    checkDynamicReleaseClasspath
                    checkDynamicReleaseLibraries
                    checkDynamicReleaseManifest
                    checkProfileClasspath
                    checkProfileLibraries
                    checkProfileManifest
                    checkReleaseClasspath
                    checkReleaseLibraries
                    checkReleaseManifest
                    compileDebugAidl
                    compileDebugAndroidTestAidl
                    compileDebugAndroidTestJavaWithJavac
                    compileDebugAndroidTestNdk
                    compileDebugAndroidTestRenderscript
                    compileDebugAndroidTestShaders
                    compileDebugJavaWithJavac
                    compileDebugNdk
                    compileDebugRenderscript
                    compileDebugShaders
                    compileDebugUnitTestJavaWithJavac
                    compileDynamicProfileAidl
                    compileDynamicProfileJavaWithJavac
                    compileDynamicProfileNdk
                    compileDynamicProfileRenderscript
                    compileDynamicProfileShaders
                    compileDynamicProfileUnitTestJavaWithJavac
                    compileDynamicReleaseAidl
                    compileDynamicReleaseJavaWithJavac
                    compileDynamicReleaseNdk
                    compileDynamicReleaseRenderscript
                    compileDynamicReleaseShaders
                    compileDynamicReleaseUnitTestJavaWithJavac
                    compileLint
                    compileProfileAidl
                    compileProfileJavaWithJavac
                    compileProfileNdk
                    compileProfileRenderscript
                    compileProfileShaders
                    compileProfileUnitTestJavaWithJavac
                    compileReleaseAidl
                    compileReleaseJavaWithJavac
                    compileReleaseNdk
                    compileReleaseRenderscript
                    compileReleaseShaders
                    compileReleaseUnitTestJavaWithJavac
                    consumeConfigAttr
                    copyFlutterAssetsDebug
                    copyFlutterAssetsDynamicProfile
                    copyFlutterAssetsDynamicRelease
                    copyFlutterAssetsProfile
                    copyFlutterAssetsRelease
                    createDebugCompatibleScreenManifests
                    createDynamicProfileCompatibleScreenManifests
                    createDynamicReleaseCompatibleScreenManifests
                    createMockableJar
                    createProfileCompatibleScreenManifests
                    createReleaseCompatibleScreenManifests
                    extractApksForDebug
                    extractApksForDynamicProfile
                    extractApksForDynamicRelease
                    extractApksForProfile
                    extractApksForRelease
                    extractProguardFiles
                    flutterBuildDebug
                    flutterBuildDynamicProfile
                    flutterBuildDynamicRelease
                    flutterBuildProfile
                    flutterBuildRelease
                    flutterBuildX86Jar
                    generateDebugAndroidTestAssets
                    generateDebugAndroidTestBuildConfig
                    generateDebugAndroidTestResources
                    generateDebugAndroidTestResValues
                    generateDebugAndroidTestSources
                    generateDebugAssets
                    generateDebugBuildConfig
                    generateDebugFeatureMetadata
                    generateDebugFeatureTransitiveDeps
                    generateDebugResources
                    generateDebugResValues
                    generateDebugSources
                    generateDebugUnitTestAssets
                    generateDebugUnitTestResources
                    generateDebugUnitTestSources
                    generateDynamicProfileAssets
                    generateDynamicProfileBuildConfig
                    generateDynamicProfileFeatureMetadata
                    generateDynamicProfileFeatureTransitiveDeps
                    generateDynamicProfileResources
                    generateDynamicProfileResValues
                    generateDynamicProfileSources
                    generateDynamicProfileUnitTestAssets
                    generateDynamicProfileUnitTestResources
                    generateDynamicProfileUnitTestSources
                    generateDynamicReleaseAssets
                    generateDynamicReleaseBuildConfig
                    generateDynamicReleaseFeatureMetadata
                    generateDynamicReleaseFeatureTransitiveDeps
                    generateDynamicReleaseResources
                    generateDynamicReleaseResValues
                    generateDynamicReleaseSources
                    generateDynamicReleaseUnitTestAssets
                    generateDynamicReleaseUnitTestResources
                    generateDynamicReleaseUnitTestSources
                    generateProfileAssets
                    generateProfileBuildConfig
                    generateProfileFeatureMetadata
                    generateProfileFeatureTransitiveDeps
                    generateProfileResources
                    generateProfileResValues
                    generateProfileSources
                    generateProfileUnitTestAssets
                    generateProfileUnitTestResources
                    generateProfileUnitTestSources
                    generateReleaseAssets
                    generateReleaseBuildConfig
                    generateReleaseFeatureMetadata
                    generateReleaseFeatureTransitiveDeps
                    generateReleaseResources
                    generateReleaseResValues
                    generateReleaseSources
                    generateReleaseUnitTestAssets
                    generateReleaseUnitTestResources
                    generateReleaseUnitTestSources
                    javaPreCompileDebug
                    javaPreCompileDebugAndroidTest
                    javaPreCompileDebugUnitTest
                    javaPreCompileDynamicProfile
                    javaPreCompileDynamicProfileUnitTest
                    javaPreCompileDynamicRelease
                    javaPreCompileDynamicReleaseUnitTest
                    javaPreCompileProfile
                    javaPreCompileProfileUnitTest
                    javaPreCompileRelease
                    javaPreCompileReleaseUnitTest
                    mainApkListPersistenceDebug
                    mainApkListPersistenceDebugAndroidTest
                    mainApkListPersistenceDynamicProfile
                    mainApkListPersistenceDynamicRelease
                    mainApkListPersistenceProfile
                    mainApkListPersistenceRelease
                    makeApkFromBundleForDebug
                    makeApkFromBundleForDynamicProfile
                    makeApkFromBundleForDynamicRelease
                    makeApkFromBundleForProfile
                    makeApkFromBundleForRelease
                    mergeDebugAndroidTestAssets
                    mergeDebugAndroidTestJniLibFolders
                    mergeDebugAndroidTestResources
                    mergeDebugAndroidTestShaders
                    mergeDebugAssets
                    mergeDebugJniLibFolders
                    mergeDebugResources
                    mergeDebugShaders
                    mergeDynamicProfileAssets
                    mergeDynamicProfileJniLibFolders
                    mergeDynamicProfileResources
                    mergeDynamicProfileShaders
                    mergeDynamicReleaseAssets
                    mergeDynamicReleaseJniLibFolders
                    mergeDynamicReleaseResources
                    mergeDynamicReleaseShaders
                    mergeProfileAssets
                    mergeProfileJniLibFolders
                    mergeProfileResources
                    mergeProfileShaders
                    mergeReleaseAssets
                    mergeReleaseJniLibFolders
                    mergeReleaseResources
                    mergeReleaseShaders
                    packageAppClassesDebug
                    packageAppClassesDebugAndroidTest
                    packageAppClassesDebugUnitTest
                    packageAppClassesDynamicProfile
                    packageAppClassesDynamicProfileUnitTest
                    packageAppClassesDynamicRelease
                    packageAppClassesDynamicReleaseUnitTest
                    packageAppClassesProfile
                    packageAppClassesProfileUnitTest
                    packageAppClassesRelease
                    packageAppClassesReleaseUnitTest
                    packageDebug
                    packageDebugAndroidTest
                    packageDebugBundle
                    packageDebugUniversalApk
                    packageDynamicProfile
                    packageDynamicProfileBundle
                    packageDynamicProfileUniversalApk
                    packageDynamicRelease
                    packageDynamicReleaseBundle
                    packageDynamicReleaseUniversalApk
                    packageProfile
                    packageProfileBundle
                    packageProfileUniversalApk
                    packageRelease
                    packageReleaseBundle
                    packageReleaseUniversalApk
                    preBuild
                    preDebugAndroidTestBuild
                    preDebugBuild
                    preDebugUnitTestBuild
                    preDynamicProfileBuild
                    preDynamicProfileUnitTestBuild
                    preDynamicReleaseBuild
                    preDynamicReleaseUnitTestBuild
                    prepareLintJar
                    preProfileBuild
                    preProfileUnitTestBuild
                    preReleaseBuild
                    preReleaseUnitTestBuild
                    processDebugAndroidTestJavaRes
                    processDebugAndroidTestManifest
                    processDebugAndroidTestResources
                    processDebugJavaRes
                    processDebugManifest
                    processDebugResources
                    processDebugUnitTestJavaRes
                    processDynamicProfileJavaRes
                    processDynamicProfileManifest
                    processDynamicProfileResources
                    processDynamicProfileUnitTestJavaRes
                    processDynamicReleaseJavaRes
                    processDynamicReleaseManifest
                    processDynamicReleaseResources
                    processDynamicReleaseUnitTestJavaRes
                    processProfileJavaRes
                    processProfileManifest
                    processProfileResources
                    processProfileUnitTestJavaRes
                    processReleaseJavaRes
                    processReleaseManifest
                    processReleaseResources
                    processReleaseUnitTestJavaRes
                    reportBuildArtifactsDebug
                    reportBuildArtifactsDynamicProfile
                    reportBuildArtifactsDynamicRelease
                    reportBuildArtifactsProfile
                    reportBuildArtifactsRelease
                    reportSourceSetTransformAndroidTest
                    reportSourceSetTransformAndroidTestDebug
                    reportSourceSetTransformDebug
                    reportSourceSetTransformDynamicProfile
                    reportSourceSetTransformDynamicRelease
                    reportSourceSetTransformMain
                    reportSourceSetTransformProfile
                    reportSourceSetTransformRelease
                    reportSourceSetTransformTest
                    reportSourceSetTransformTestDebug
                    reportSourceSetTransformTestDynamicProfile
                    reportSourceSetTransformTestDynamicRelease
                    reportSourceSetTransformTestProfile
                    reportSourceSetTransformTestRelease
                    resolveConfigAttr
                    splitsDiscoveryTaskDebug
                    splitsDiscoveryTaskDynamicProfile
                    splitsDiscoveryTaskDynamicRelease
                    splitsDiscoveryTaskProfile
                    splitsDiscoveryTaskRelease
                    transformClassesWithDexBuilderForDebug
                    transformClassesWithDexBuilderForDebugAndroidTest
                    transformClassesWithDexBuilderForDynamicProfile
                    transformClassesWithDexBuilderForDynamicRelease
                    transformClassesWithDexBuilderForProfile
                    transformClassesWithDexBuilderForRelease
                    transformDexArchiveWithDexMergerForDebug
                    transformDexArchiveWithDexMergerForDebugAndroidTest
                    transformDexArchiveWithDexMergerForDynamicProfile
                    transformDexArchiveWithDexMergerForDynamicRelease
                    transformDexArchiveWithDexMergerForProfile
                    transformDexArchiveWithDexMergerForRelease
                    transformDexArchiveWithExternalLibsDexMergerForDebug
                    transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest
                    transformDexArchiveWithExternalLibsDexMergerForDynamicProfile
                    transformDexArchiveWithExternalLibsDexMergerForDynamicRelease
                    transformDexArchiveWithExternalLibsDexMergerForProfile
                    transformDexArchiveWithExternalLibsDexMergerForRelease
                    transformNativeLibsWithMergeJniLibsForDebug
                    transformNativeLibsWithMergeJniLibsForDebugAndroidTest
                    transformNativeLibsWithMergeJniLibsForDynamicProfile
                    transformNativeLibsWithMergeJniLibsForDynamicRelease
                    transformNativeLibsWithMergeJniLibsForProfile
                    transformNativeLibsWithMergeJniLibsForRelease
                    transformResourcesWithMergeJavaResForDebug
                    transformResourcesWithMergeJavaResForDebugAndroidTest
                    transformResourcesWithMergeJavaResForDebugUnitTest
                    transformResourcesWithMergeJavaResForDynamicProfile
                    transformResourcesWithMergeJavaResForDynamicProfileUnitTest
                    transformResourcesWithMergeJavaResForDynamicRelease
                    transformResourcesWithMergeJavaResForDynamicReleaseUnitTest
                    transformResourcesWithMergeJavaResForProfile
                    transformResourcesWithMergeJavaResForProfileUnitTest
                    transformResourcesWithMergeJavaResForRelease
                    transformResourcesWithMergeJavaResForReleaseUnitTest
                    validateSigningDebug
                    validateSigningDebugAndroidTest
                    validateSigningDynamicProfile
                    validateSigningDynamicRelease
                    validateSigningProfile
                    validateSigningRelease
                    writeDebugApplicationId
                    writeDynamicProfileApplicationId
                    writeDynamicReleaseApplicationId
                    writeProfileApplicationId
                    writeReleaseApplicationId

                    Rules
                    -----
                    Pattern: clean<TaskName>: Cleans the output files of a task.
                    Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
                    Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.
                    1 actionable task: 1 executed
[   +6 ms] Resolving dependencies... (completed in 2.2s)
[   +1 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree C:\Users\Admin\Documents\flutter\hero_bug\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +10 ms] Exit code 0 from: C:\Users\Admin\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree C:\Users\Admin\Documents\flutter\hero_bug\build\app\outputs\apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.hero_bug" (Raw: "com.example.hero_bug")
               A: platformBuildVersionCode=(type 0x10)0x1
               A: platformBuildVersionName="1.0.0" (Raw: "1.0.0")
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="hero_bug" (Raw: "hero_bug")
                 A: android:icon(0x01010002)=@0x7f020000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 E: activity (line=27)
                   A: android:theme(0x01010000)=@0x7f030000
                   A: android:name(0x01010003)="com.example.hero_bug.MainActivity" (Raw: "com.example.hero_bug.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400037b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=41)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=45)
                     E: action (line=46)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=48)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
[   +6 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell -x logcat -v time -t 1
[  +43 ms] Exit code 0 from: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           03-07 16:44:22.488 I/GnssLocationProvider( 1893): WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@876ca2a)
[   +3 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell -x logcat -v time
[ +368 ms] DependencyChecker: C:\Users\Admin\Documents\flutter\hero_bug\lib\main.dart is newer than 2019-03-07 16:36:11.000
[   +3 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb version
[  +20 ms] Android Debug Bridge version 1.0.40
           Version 4986621
           Installed as C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.EXE
[   +2 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb start-server
[  +21 ms] Building APK
[  +20 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] executing: [C:\Users\Admin\Documents\flutter\hero_bug\android\] C:\Users\Admin\Documents\flutter\hero_bug\android\gradlew.bat -Pverbose=true -Ptarget=C:\Users\Admin\Documents\flutter\hero_bug\lib/main.dart -Ptrack-widget-creation=false -Pcompilation-trace-file=compilation.txt
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1054 ms] > Task :app:flutterBuildX86Jar UP-TO-DATE
[        ] > Task :app:checkDebugClasspath UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[  +86 ms] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript UP-TO-DATE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:prepareLintJar UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[+1998 ms] > Task :app:flutterBuildDebug
[        ] [  +10 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[        ] [  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[        ] [  +28 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [        ] executing: [C:\src\flutter\] git log -n 1 --pretty=format:%H
[        ] [  +38 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] [        ] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[        ] [        ] executing: [C:\src\flutter\] git log -n 1 --pretty=format:%ar
[        ] [  +37 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] [        ] 3 weeks ago
[        ] [        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[        ] [  +49 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.2.1-0-g8661d8aec
[        ] [ +612 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --strong --target=flutter --no-link-platform --incremental --packages
C:\Users\Admin\Documents\flutter\hero_bug\.packages --output-dill build\app.dill --depfile C:\Users\Admin\Documents\flutter\hero_bug\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --filesystem-scheme org-dartlang-root package:hero_bug/main.dart
[+4189 ms] [+4789 ms] Building bundle
[        ] [   +1 ms] Writing asset files to C:\Users\Admin\Documents\flutter\hero_bug\build\app\intermediates\flutter\debug/flutter_assets
[        ] [  +50 ms] Wrote C:\Users\Admin\Documents\flutter\hero_bug\build\app\intermediates\flutter\debug/flutter_assets
[        ] [   +8 ms] "flutter bundle" took 5,337ms.
[        ] [        ] "flutter bundle" took 5,337ms.
[  +98 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +197 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:splitsDiscoveryTaskDebug UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:generateDebugSources UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugNdk NO-SOURCE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
[        ] > Task :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
[        ] > Task :app:checkDebugLibraries UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[+2047 ms] > Task :app:packageDebug
[        ] > Task :app:assembleDebug
[        ] 31 actionable tasks: 5 executed, 26 up-to-date
[ +346 ms] Running Gradle task 'assembleDebug'... (completed in 10.1s)
[  +23 ms] calculateSha: LocalDirectory: 'C:\Users\Admin\Documents\flutter\hero_bug\build\app\outputs\apk'/app.apk
[ +343 ms] Built build\app\outputs\apk\debug\app-debug.apk.
[   +1 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree C:\Users\Admin\Documents\flutter\hero_bug\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +27 ms] Exit code 0 from: C:\Users\Admin\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree C:\Users\Admin\Documents\flutter\hero_bug\build\app\outputs\apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.hero_bug" (Raw: "com.example.hero_bug")
               A: platformBuildVersionCode=(type 0x10)0x1
               A: platformBuildVersionName="1.0.0" (Raw: "1.0.0")
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="hero_bug" (Raw: "hero_bug")
                 A: android:icon(0x01010002)=@0x7f020000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 E: activity (line=27)
                   A: android:theme(0x01010000)=@0x7f030000
                   A: android:name(0x01010003)="com.example.hero_bug.MainActivity" (Raw: "com.example.hero_bug.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400037b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=41)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=45)
                     E: action (line=46)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=48)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
[        ] Stopping app 'app.apk' on Android SDK built for x86.
[        ] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell am force-stop com.example.hero_bug
[  +54 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell pm list packages com.example.hero_bug
[  +53 ms] package:com.example.hero_bug
[   +2 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell cat /data/local/tmp/sky.com.example.hero_bug.sha1
[  +33 ms] fc55513ae9c21379960ae8a0771f3bc0fb5af10e
[        ] Installing APK.
[   +1 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb version
[  +18 ms] Android Debug Bridge version 1.0.40
           Version 4986621
           Installed as C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb.EXE
[        ] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb start-server
[  +20 ms] Installing build\app\outputs\apk\app.apk...
[        ] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 install -t -r C:\Users\Admin\Documents\flutter\hero_bug\build\app\outputs\apk\app.apk
[+2291 ms] Success
[        ] Installing build\app\outputs\apk\app.apk... (completed in 2.3s)
[   +1 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell echo -n 9f0ddaca8aff44220de018c0ee108cd81dbe549b > /data/local/tmp/sky.com.example.hero_bug.sha1
[  +54 ms] Android SDK built for x86 startApp
[   +1 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.hero_bug/com.example.hero_bug.MainActivity
[ +173 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.hero_bug/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+1202 ms] Observatory URL on device: http://127.0.0.1:37205/
[   +1 ms] executing: C:\Users\Admin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 forward tcp:0 tcp:37205
[  +21 ms] 53848
[        ] Forwarded host port 53848 to device port 37205 for Observatory
[   +4 ms] Connecting to service protocol: http://127.0.0.1:53848/
[ +321 ms] Successfully connected to service protocol: http://127.0.0.1:53848/
[   +3 ms] Sending to VM service: getVM({})
[  +11 ms] Result: {type: VM, name: vm, architectureBits: 32, targetCPU: ia32, hostCPU: AMD Ryzen 7 1700 Eight-Core Processor, version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "android_ia32", _profilerMode: VM, _nativeZoneMemoryUsage: 0,...
[   +4 ms] Sending to VM service: _flutter.listViews({})
[  +10 ms] Result: {type: FlutterViewList, views: []}
[  +53 ms] Sending to VM service: getVM({})
[   +6 ms] Result: {type: VM, name: vm, architectureBits: 32, targetCPU: ia32, hostCPU: AMD Ryzen 7 1700 Eight-Core Processor, version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "android_ia32", _profilerMode: VM, _nativeZoneMemoryUsage: 0,...
[        ] Sending to VM service: _flutter.listViews({})
[   +5 ms] Result: {type: FlutterViewList, views: []}
[  +52 ms] Sending to VM service: getVM({})
[   +7 ms] Result: {type: VM, name: vm, architectureBits: 32, targetCPU: ia32, hostCPU: AMD Ryzen 7 1700 Eight-Core Processor, version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "android_ia32", _profilerMode: VM, _nativeZoneMemoryUsage: 0,...
[        ] Sending to VM service: _flutter.listViews({})
[   +8 ms] Result: {type: FlutterViewList, views: []}
[  +51 ms] Sending to VM service: getVM({})
[  +17 ms] Result: {type: VM, name: vm, architectureBits: 32, targetCPU: ia32, hostCPU: AMD Ryzen 7 1700 Eight-Core Processor, version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "android_ia32", _profilerMode: VM, _nativeZoneMemoryUsage: 0,...
[        ] Sending to VM service: _flutter.listViews({})
[  +20 ms] Result: {type: FlutterViewList, views: []}
[  +51 ms] Sending to VM service: getVM({})
[  +10 ms] Result: {type: VM, name: vm, architectureBits: 32, targetCPU: ia32, hostCPU: AMD Ryzen 7 1700 Eight-Core Processor, version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "android_ia32", _profilerMode: VM, _nativeZoneMemoryUsage: 0,...
[   +2 ms] Sending to VM service: getIsolate({isolateId: isolates/197168524})
[   +1 ms] Sending to VM service: _flutter.listViews({})
[  +17 ms] Result: {type: Isolate, fixedId: true, id: isolates/197168524, name: main.dart:main(), number: 197168524, _originNumber: 197168524, startTime: 1551941078835, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 2, avgCollectionPeriod...
[   +3 ms] Result: {type: FlutterViewList, views: []}
[   +1 ms] Flutter is taking longer than expected to report its views. Still trying...
[  +51 ms] Sending to VM service: getVM({})
[  +12 ms] Result: {type: VM, name: vm, architectureBits: 32, targetCPU: ia32, hostCPU: AMD Ryzen 7 1700 Eight-Core Processor, version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "android_ia32", _profilerMode: VM, _nativeZoneMemoryUsage: 0,...
[        ] Sending to VM service: _flutter.listViews({})
[  +19 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xc912848c, isolate: {type: @Isolate, fixedId: true, id: isolates/197168524, name: main.dart$main-197168524, number: 197168524}}]}
[   +5 ms] DevFS: Creating new filesystem on the device (null)
[   +1 ms] Sending to VM service: _createDevFS({fsName: hero_bug})
[  +46 ms] E/eglCodecCommon(31622): glUtilsParamSize: unknow param 0x000082da
[  +18 ms] Result: {type: FileSystem, name: hero_bug, uri: file:///data/user/0/com.example.hero_bug/cache/hero_bugRUYSHV/hero_bug/}
[        ] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.hero_bug/cache/hero_bugRUYSHV/hero_bug/)
[   +1 ms] Updating assets
[ +119 ms] Syncing files to device Android SDK built for x86...
[   +2 ms] DevFS: Starting sync from LocalDirectory: 'C:\Users\Admin\Documents\flutter\hero_bug'
[        ] Scanning project files
[   +4 ms] Scanning package files
[  +67 ms] Scanning asset files
[   +1 ms] Scanning for deleted files
[  +40 ms] Compiling dart to kernel with 456 updated files
[   +7 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build\app.dill --packages
C:\Users\Admin\Documents\flutter\hero_bug\.packages --filesystem-scheme org-dartlang-root
[   +1 ms] I/OpenGLRenderer(31622): Initialized EGL, version 1.4
[        ] D/OpenGLRenderer(31622): Swap behavior 1
[   +4 ms] D/        (31622): HostConnection::get() New Host Connection established 0xdd4fd300, tid 31662
[        ] W/OpenGLRenderer(31622): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
[        ] D/OpenGLRenderer(31622): Swap behavior 0
[        ] D/EGL_emulation(31622): eglCreateContext: 0xdc817120: maj 3 min 1 rcv 4
[ +314 ms] D/EGL_emulation(31622): eglMakeCurrent: 0xdc817120: ver 3 1 (tinfo 0xdd4fc680)
[        ] E/eglCodecCommon(31622): glUtilsParamSize: unknow param 0x000082da
[        ] E/eglCodecCommon(31622): glUtilsParamSize: unknow param 0x000082da
[  +24 ms] D/EGL_emulation(31622): eglCreateContext: 0xdda90e80: maj 3 min 1 rcv 4
[  +66 ms] D/EGL_emulation(31622): eglMakeCurrent: 0xdda90e80: ver 3 1 (tinfo 0xdd4fc000)
[  +16 ms] E/eglCodecCommon(31622): glUtilsParamSize: unknow param 0x000082da
[  +32 ms] E/eglCodecCommon(31622): glUtilsParamSize: unknow param 0x000082da
[ +447 ms] I/Choreographer(31622): Skipped 64 frames!  The application may be doing too much work on its main thread.
[  +22 ms] D/EGL_emulation(31622): eglMakeCurrent: 0xdc817120: ver 3 1 (tinfo 0xdd4fc680)
[ +241 ms] I/OpenGLRenderer(31622): Davey! duration=1325ms; Flags=1, IntendedVsync=54911232110604, Vsync=54912298777228, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=54912303359600, AnimationStart=54912303461800, PerformTraversalsStart=54912304169200,
DrawStart=54912313456200, SyncQueued=54912316499400, SyncStart=54912323743100, IssueDrawCommandsStart=54912324277700, SwapBuffers=54912378729100, FrameCompleted=54912564683700, DequeueBufferDuration=84721000, QueueBufferDuration=3030000,
[ +144 ms] D/        (31622): HostConnection::get() New Host Connection established 0xdd4fd500, tid 31653
[ +125 ms] Updating files
[ +173 ms] DevFS: Sync finished
[   +2 ms] Syncing files to device Android SDK built for x86... (completed in 1,743ms)
[        ] Synced 0.8MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[  +16 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xc912848c, isolate: {type: @Isolate, fixedId: true, id: isolates/197168524, name: main.dart$main-197168524, number: 197168524}}]}
[   +1 ms] Connected to _flutterView/0xc912848c.
[   +3 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:53848/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[  +80 ms] D/EGL_emulation(31622): eglMakeCurrent: 0xdda90e80: ver 3 1 (tinfo 0xdd4fc350)
[  +60 ms] D/skia    (31622): Program linking failed.
[ +431 ms] D/skia    (31622): Program linking failed.
[ +153 ms] I/chatty  (31622): uid=10091(com.example.hero_bug) 1.gpu identical 5 lines
[        ] D/skia    (31622): Program linking failed.
[+3374 ms] D/skia    (31622): Program linking failed.
[+3403 ms] I/flutter (31622): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
[  +13 ms] I/flutter (31622): The following assertion was thrown during a scheduler callback:
[        ] I/flutter (31622): 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 248 pos 12: 'box != null &&
[        ] I/flutter (31622): box.hasSize': is not true.
[        ] I/flutter (31622):
[        ] I/flutter (31622): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (31622): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (31622): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (31622):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (31622):
[        ] I/flutter (31622): When the exception was thrown, this was the stack:
[  +19 ms] I/flutter (31622): #2      _HeroState.startFlight (package:flutter/src/widgets/heroes.dart:248:12)
[   +1 ms] I/flutter (31622): #3      _HeroFlight.start (package:flutter/src/widgets/heroes.dart:451:21)
[        ] I/flutter (31622): #4      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:684:60)
[        ] I/flutter (31622): #5      HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:630:11)
[        ] I/flutter (31622): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
[        ] I/flutter (31622): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:936:9)
[        ] I/flutter (31622): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
[        ] I/flutter (31622): #12     _invoke (dart:ui/hooks.dart:209:10)
[        ] I/flutter (31622): #13     _drawFrame (dart:ui/hooks.dart:168:3)
[        ] I/flutter (31622): (elided 5 frames from class _AssertionError and package dart:async)
[        ] I/flutter (31622): ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +236 ms] I/flutter (31622): Another exception was thrown: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 411 pos 14: 'overlayEntry != null': is not true.
```

```
flutter analyze
Analyzing hero_bug...
No issues found! (ran in 3.8s)
```

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale en-AU)
    • Flutter version 1.2.1 at C:\src\flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.30.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by Piinks**
## Description

Re-work of the `pushAndRemoveUntil` method within the `Navigator` class.
The prior implementation was notifying observers incorrectly, and moving routes out of the order that is specified in the documentation. 
This fixes assertions being thrown by Heroes that are attempting to animate after being notified incorrectly, and observers also not being notified correctly of removals. Finally, this also fixes page transition animations not taking place for the newly pushed route.

## Related Issues

Fixes #22025 
Fixes #25080 
Fixes #28980
Maybe #16547, since it corrects observer notification

## Tests

- pushAndRemoveUntil works & notifies properly
- pushAndRemoveUntil triggers page animation transition for pushed route
- Heroes animate when appropriate
- Heroes do not animate when appropriate

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 1]
```diff
@@ -1154,14 +1154,16 @@ class Navigator extends StatefulWidget {
...
+  /// notified for [Route.didPush]. The new route and its new antecedent, (the
+  /// route below the bottommost removed route) are notified through
+  /// [Route.didChangeNext]). If the [Navigator] has any [Navigator.observers],
+  /// they will be notified as well (see [NavigatorObservers.didPush] and
+  /// [NavigatorObservers.didRemove]). The removed routes are disposed without
+  /// being notified, with the exception of the aforementioned original
+  /// antecedent to the new route, once the new route has finished animating.
+  /// The futures that had been returned from pushing those routes will not
+  /// complete.
   ///
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/navigator.dart]: The wording here is a bit strange, may re-work.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 2]
```diff
@@ -1881,33 +1883,46 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
+    }
+
     newRoute.didPush().whenCompleteOrCancel(() {
       if (mounted) {
-        for (Route<dynamic> route in removedRoutes)
-          route.dispose();
+        // Notify for newRoute
+        newRoute.didChangeNext(null);
+        for (NavigatorObserver observer in widget.observers)
+          observer.didPush(newRoute, precedingRoute);
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/navigator.dart]: This may be a breaking change. This changes which route is considered the 'previous route' when pushed.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 3]
```diff
@@ -1881,33 +1883,47 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
+        oldRoute = route;
+        removalIndex = _history.indexOf(route) + 1;
+        break;
+      }
+    }
+
+    // Notify for newRoute
+    newRoute.didChangeNext(null);
+    for (NavigatorObserver observer in widget.observers)
+      observer.didPush(newRoute, precedingRoute);
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/navigator.dart]: This changes which route is notified of having been pushed on top of - not sure if this would then be a breaking change.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 4]
```diff
@@ -1881,33 +1883,47 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
-        for (Route<dynamic> route in removedRoutes)
-          route.dispose();
+
+        // Complete remove until predicate & notify
+        while (_history[removalIndex] != newRoute) {
+          final Route<dynamic> removedRoute = _history.removeAt(removalIndex);
+          assert(removedRoute != null && removedRoute._navigator == this);
+          assert(removedRoute.overlayEntries.isNotEmpty);
+          for (NavigatorObserver observer in widget.observers)
+            observer.didRemove(removedRoute, oldRoute);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart]: This seems to be calling didRemove on the bottommost route first and then going up to the topmost. I beleive this breaks the contract for didRemove:

> If multiple routes are being removed, [...] this method will be called once for each removed route, from the topmost route to the bottommost route.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 5]
```diff
@@ -1881,33 +1883,47 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
     assert(newRoute.overlayEntries.isEmpty);
-    final Route<dynamic> oldRoute = _history.isNotEmpty ? _history.last : null;
     newRoute._navigator = this;
     newRoute.install(_currentOverlayEntry);
     _history.add(newRoute);
+
+    Route<dynamic> oldRoute;
+    int removalIndex = 0;
+
+    for (Route<dynamic> route in _history) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/navigator.dart]: you can use [firstWhere](https://api.dartlang.org/stable/2.4.0/dart-core/Iterable/firstWhere.html)

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 6]
```diff
@@ -1881,33 +1883,47 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
   Future<T> pushAndRemoveUntil<T extends Object>(Route<T> newRoute, RoutePredicate predicate) {
     assert(!_debugLocked);
     assert(() { _debugLocked = true; return true; }());
-    final List<Route<dynamic>> removedRoutes = <Route<dynamic>>[];
-    while (_history.isNotEmpty && !predicate(_history.last)) {
-      final Route<dynamic> removedRoute = _history.removeLast();
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart]: Is there any reason to no longer collect the to-be-removed routes before-hand? Seems like that would simplify matters a little bit.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 7]
```diff
@@ -1881,33 +1883,47 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
-      removedRoutes.add(removedRoute);
-    }
+    final Route<dynamic> precedingRoute = _history.last;
     assert(newRoute._navigator == null);
     assert(newRoute.overlayEntries.isEmpty);
-    final Route<dynamic> oldRoute = _history.isNotEmpty ? _history.last : null;
     newRoute._navigator = this;
     newRoute.install(_currentOverlayEntry);
     _history.add(newRoute);
+
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/navigator.dart]: I might be missing something, but It seems like we just need to make sure observer.didPush is called with  precedingRoute. Is the refactoring below necessary?

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 8]
```diff
@@ -1881,33 +1883,47 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
+    // Notify for newRoute
+    newRoute.didChangeNext(null);
+    for (NavigatorObserver observer in widget.observers)
+      observer.didPush(newRoute, precedingRoute);
+
     newRoute.didPush().whenCompleteOrCancel(() {
       if (mounted) {
-        for (Route<dynamic> route in removedRoutes)
-          route.dispose();
+
```
Comment (chunhtai) [inline packages/flutter/lib/src/widgets/navigator.dart]: nit extra bank line

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 9]
```diff
@@ -1881,33 +1883,47 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
-    }
+    final Route<dynamic> precedingRoute = _history.last;
     assert(newRoute._navigator == null);
     assert(newRoute.overlayEntries.isEmpty);
-    final Route<dynamic> oldRoute = _history.isNotEmpty ? _history.last : null;
     newRoute._navigator = this;
     newRoute.install(_currentOverlayEntry);
     _history.add(newRoute);
+
+    Route<dynamic> oldRoute;
```
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/widgets/navigator.dart]: (I guess that name was there before...)

File: packages/flutter/test/widgets/observer_tester.dart [hunk 10]
```diff
@@ -0,0 +1,48 @@
...
+    if (onReplaced != null)
+      onReplaced(newRoute, oldRoute);
+  }
+
+  @override
+  void didStartUserGesture(Route<dynamic> route, Route<dynamic> previousRoute) {
+    if (onStartUserGesture != null)
+      onStartUserGesture(route, previousRoute);
+  }
+}
```
Comment (goderbauer) [inline packages/flutter/test/widgets/observer_tester.dart]: nit: add a line break.

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 11]
```diff
@@ -39,42 +42,202 @@ void main() {
...
+
+      final NavigatorState navigator = tester.state(find.byType(Navigator));
+      navigator.pushNamed('/a');
+      await tester.pumpAndSettle();
+
+      expect(find.text('home', skipOffstage: false), findsOneWidget);
+      expect(find.text('a', skipOffstage: false), findsOneWidget);
+      expect(find.text('b', skipOffstage: false), findsNothing);
+
+      bool isPushed = false;
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: This test may be a little easier to understand by just having a `List<String> log = <String>[]` and on Pushed, onRemoved just add strings like `/a pushed, previousRoute: /` or `/ removed, previousRoute: /a` to that log. You can then assert that the log contains the expected messages.

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 12]
```diff
@@ -39,42 +42,202 @@ void main() {
...
+      expect(find.text('home', skipOffstage: false), findsNothing);
+      expect(find.text('a', skipOffstage: false), findsOneWidget);
+      expect(find.text('b', skipOffstage: false), findsOneWidget);
+      expect(isPushed, isTrue);
+      expect(homeIsRemoved, isTrue);
+    });
+
+    testWidgets('triggers page transition animation for pushed route', (WidgetTester tester) async {
+
+      observer
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: Looks like there's state leaking from one test to another? Either avoid the global state (preferred) or do the clean-up in the test that sets the global state.

Comment (goderbauer) [reply packages/flutter/test/widgets/navigator_replacement_test.dart]: (I would probably just remove the global myApp and observer and instead instantiate those in the tests directly.

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 13]
```diff
@@ -39,42 +42,202 @@ void main() {
...
-    await tester.pumpWidget(MaterialApp(
+  group('pushAndRemoveUntil', () {
+
+    final TestObserver observer = TestObserver();
+    final Widget myApp = MaterialApp(
       home: const Material(child: Text('home')),
       routes: <String, WidgetBuilder>{
         '/a': (BuildContext context) => const Material(child: Text('a')),
         '/b': (BuildContext context) => const Material(child: Text('b')),
+        '/c': (BuildContext context) => const Material(child: Text('c')),
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: Is `/c` actually used anywhere? (If we don't have it, it would probably be good to have a test that removes more than just one route...)

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 14]
```diff
@@ -39,42 +42,202 @@ void main() {
...
+      navigator.pushNamed('/a');
+      await tester.pumpAndSettle();
+
+      navigator.pushNamedAndRemoveUntil('/b', ModalRoute.withName('/'));
+      await tester.pump();
+      await tester.pump(const Duration(milliseconds: 16));
+
+      expect(find.text('b'), isOnstage);
+
+      // 'b' text is sliding in from the right, no hero transition
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: Wait, we don't want a Hero transition? Why not?

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 6 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/navigator.dart]: Fixed.

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 9 above)
[the remark this answers is not in the document]
Comment (Piinks) [reply packages/flutter/lib/src/widgets/navigator.dart]: I made it newPrecedingRoute? Not sure if that is clearer...

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 4 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/navigator.dart]: Fixed.

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 15]
```diff
@@ -1154,14 +1154,16 @@ class Navigator extends StatefulWidget {
...
   ///
-  /// The new route and the route below the bottommost removed route (which
-  /// becomes the route below the new route) are notified (see [Route.didPush]
-  /// and [Route.didChangeNext]). If the [Navigator] has any
-  /// [Navigator.observers], they will be notified as well (see
-  /// [NavigatorObservers.didPush] and [NavigatorObservers.didRemove]). The
-  /// removed routes are disposed, without being notified, once the new route
-  /// has finished animating. The futures that had been returned from pushing
-  /// those routes will not complete.
+  /// The new route and its previous antecedent (which has been removed) are
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart]: Not sure what's meant by the first sentence. The "previous antecedent" does not get a didPush call?

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 16]
```diff
@@ -1154,14 +1154,16 @@ class Navigator extends StatefulWidget {
...
+  /// notified for [Route.didPush]. The new route and its new antecedent, (the
+  /// route below the bottommost removed route) are notified through
+  /// [Route.didChangeNext]). If the [Navigator] has any [Navigator.observers],
+  /// they will be notified as well (see [NavigatorObservers.didPush] and
+  /// [NavigatorObservers.didRemove]). The removed routes are disposed without
+  /// being notified, with the exception of the aforementioned original
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart]: Should this maybe mention that all removed routes are reported to any NavigatorObservers?

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 17]
```diff
@@ -1881,33 +1883,47 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
     assert(newRoute.overlayEntries.isEmpty);
-    final Route<dynamic> oldRoute = _history.isNotEmpty ? _history.last : null;
+    final Route<dynamic> newPrecedingRoute = _history.isNotEmpty ? _history.last : null;
     newRoute._navigator = this;
-    newRoute.install(_currentOverlayEntry);
+    newRoute.install(precedingRouteOverlay);
     _history.add(newRoute);
+
+    // Notify for newRoute
+    newRoute.didChangeNext(null);
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart]: I believe we usually call newRoute.didPush before newRoute.didChangeNext and before notifying observers (see NavigatorState.push for an example). Any reason we need to do it in different order here?

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 18]
```diff
@@ -1881,33 +1883,47 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
...
+    for (NavigatorObserver observer in widget.observers)
+      observer.didPush(newRoute, precedingRoute);
+
     newRoute.didPush().whenCompleteOrCancel(() {
       if (mounted) {
-        for (Route<dynamic> route in removedRoutes)
-          route.dispose();
+        // Complete remove until predicate & notify
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart]: This comment seems outdated?

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 19]
```diff
@@ -5,7 +5,10 @@
 import 'package:flutter_test/flutter_test.dart';
 import 'package:flutter/material.dart';
 
+import 'observer_tester.dart';
+
 void main() {
+
```
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/test/widgets/navigator_replacement_test.dart]: Looks like this is still there.

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 20]
```diff
@@ -39,42 +42,202 @@ void main() {
     expect(find.text('home'), findsOneWidget);
   });
 
-  testWidgets('pushAndRemoveUntil', (WidgetTester tester) async {
-    await tester.pumpWidget(MaterialApp(
+  group('pushAndRemoveUntil', () {
+
```
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/test/widgets/navigator_replacement_test.dart]: And here.

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 21]
```diff
@@ -39,42 +42,205 @@ void main() {
...
+      await tester.pumpAndSettle();
+
+      expect(find.text('home', skipOffstage: false), findsOneWidget);
+      expect(find.text('a', skipOffstage: false), findsOneWidget);
+      expect(find.text('b', skipOffstage: false), findsNothing);
+
+      final List<String> log = <String>[];
+      observer
+        ..onPushed = (Route<dynamic> route, Route<dynamic> previousRoute) {
+          expectSync(route is PageRoute && route.settings.name == '/b', isTrue);
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: Instead of having the expects in here you could just call `log.add('${route.settings.name} pushed, previous route: ${previousRoute.settings.name}')` and then verify everything at the end.

Comment (goderbauer) [reply packages/flutter/test/widgets/navigator_replacement_test.dart]: Same for the onRemoved

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 22]
```diff
@@ -39,42 +42,205 @@ void main() {
...
+        };
+
+      // Remove all routes below
+      navigator.pushNamedAndRemoveUntil('/b', (Route<dynamic> route) => false);
+      await tester.pumpAndSettle();
+
+      expect(find.text('home', skipOffstage: false), findsNothing);
+      expect(find.text('a', skipOffstage: false), findsNothing);
+      expect(find.text('b', skipOffstage: false), findsOneWidget);
+      expect(log, contains('/b pushed, previous route: /a'));
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: expect(log, equals(<String>[
 '/b pushed, previous route: /a',
 '/a removed, previous route: null',
 ...
]);

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 23]
```diff
@@ -39,42 +42,205 @@ void main() {
...
+      expect(log, contains('/a removed, previous route: null'));
+      expect(log, contains('/ removed, previous route: null'));
+
+      observer.onPushed = null;
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: Why do we need to rest onPushed? why not onRemoved? Or neither of them?

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 24]
```diff
@@ -39,42 +42,205 @@ void main() {
...
+
+
+      navigator.pushNamed('/');
+      await tester.pumpAndSettle();
+
+      expect(find.text('home', skipOffstage: false), findsOneWidget);
+      expect(find.text('a', skipOffstage: false), findsNothing);
+      expect(find.text('b', skipOffstage: false), findsOneWidget);
+
+      observer
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: If we do the callback registration generically as suggested above, we don't have to repeat it here...

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 25]
```diff
@@ -39,42 +42,205 @@ void main() {
...
+        };
+
+      // Remove only some routes below
+      navigator.pushNamedAndRemoveUntil('/a', ModalRoute.withName('/b'));
+      await tester.pumpAndSettle();
+
+      expect(find.text('home', skipOffstage: false), findsNothing);
+      expect(find.text('a', skipOffstage: false), findsOneWidget);
+      expect(find.text('b', skipOffstage: false), findsOneWidget);
+      expect(log, contains('/a pushed, previous route: /'));
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: same comment as above.

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 26]
```diff
@@ -39,42 +42,205 @@ void main() {
...
+      expect(log, contains('/ removed, previous route: /b'));
+
+      observer.onPushed = null;
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: Why this?

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 27]
```diff
@@ -39,42 +42,205 @@ void main() {
...
+      log.clear();
+    });
+
+    testWidgets('triggers page transition animation for pushed route', (WidgetTester tester) async {
+
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: nit: Remove this blank line.

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 28]
```diff
@@ -39,42 +42,205 @@ void main() {
...
+      expect(find.text('a'), findsOneWidget);
+      expect(find.text('b'), findsOneWidget);
+
+      // Complete transition
+      await tester.pumpAndSettle();
+      expect(find.text('a'), findsNothing);
+      expect(find.text('b'), findsOneWidget);
+    });
+
+    testWidgets('Hero transition triggers when appropriate', (WidgetTester tester) async {
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: instead of "when appropriate" maybe state the condition that this is testing where the hero should fly.

File: packages/flutter/test/widgets/navigator_replacement_test.dart [hunk 29]
```diff
@@ -39,42 +42,205 @@ void main() {
...
+      expect(bOffset.dy, greaterThan(0.0));
+      expect(bOffset.dy, lessThan(100.0));
+
+      await tester.pump(const Duration(seconds: 1));
+
+      expect(find.text('a'), findsNothing);
+      expect(find.text('b'), isOnstage);
+    });
+
+    testWidgets('Hero transition does not trigger when appropriate', (WidgetTester tester) async {
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_replacement_test.dart]: Same here.

File: packages/flutter/test/widgets/navigator_replacement_test.dart (hunk 14 above)
Comment (goderbauer) [reply packages/flutter/test/widgets/navigator_replacement_test.dart]: Makes sense! Maybe update the name of the test to contain a little more context about the tested scenario.

File: packages/flutter/test/widgets/navigator_replacement_test.dart (hunk 21 above)
Comment (Piinks) [reply packages/flutter/test/widgets/navigator_replacement_test.dart]: Pretty slick!

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 17 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/navigator.dart]: Fixed.

File: packages/flutter/test/widgets/navigator_replacement_test.dart (hunk 22 above)
Comment (Piinks) [reply packages/flutter/test/widgets/navigator_replacement_test.dart]: Done!

File: packages/flutter/test/widgets/navigator_replacement_test.dart (hunk 21 above)
Comment (Piinks) [reply packages/flutter/test/widgets/navigator_replacement_test.dart]: Pretty slick! :)

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 17 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/navigator.dart]: Fixed!

**Review by Piinks — COMMENTED** [review]
Ready for another look! Thanks for the feedback!

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 30]
```diff
@@ -1154,14 +1154,14 @@ class Navigator extends StatefulWidget {
...
-  /// removed routes are disposed, without being notified, once the new route
-  /// has finished animating. The futures that had been returned from pushing
-  /// those routes will not complete.
+  /// The newly pushed route and its preceding route are notified for
+  /// [Route.didPush]. After removal, the new route and its new preceding route,
+  /// (the route below the bottommost removed route) are notified through
+  /// [Route.didChangeNext]). If the [Navigator] has any [Navigator.observers],
+  /// they will be notified as well (see [NavigatorObservers.didPush] and
+  /// [NavigatorObservers.didRemove]). The removed routes are disposed of and
+  /// notified, once the new route has finished animating. The futures that had\
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart]: remove trailing \?

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/navigator.dart (hunk 30 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/navigator.dart]: Nice catch! Fixed.
