### PR TITLE
Suppress Flutter update check if `--machine` is present at all.

### LINKED ISSUE #145158: flutter devices --machine prints upgrade banner breaking machine parsing
Running 'et run' failed with the following error. When flutter is invoked with --machine we shouldn't print out the human upgrade banner.

```
[2024-03-14 09:06:20.309447] ERROR: Failed to parse flutter devices output: FormatException: Unexpected character (at line 2, character 1)
┌─────────────────────────────────────────────────────────┐
^



┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
[
  {
    "name": "sdk gphone64 arm64",
    "id": "emulator-5554",
    "isSupported": true,
    "targetPlatform": "android-arm64",
    "emulator": true,
    "sdk": "Android 14 (API 34)",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": true,
      "fastStart": true,
      "flutterExit": true,
      "hardwareRendering": true,
      "startPaused": true
    }
  },
  {
    "name": "macOS",
    "id": "macos",
    "isSupported": true,
    "targetPlatform": "darwin",
    "emulator": false,
    "sdk": "macOS 14.4 23E214 darwin-arm64",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": true,
      "hardwareRendering": false,
      "startPaused": true
    }
  },
  {
    "name": "Mac Designed for iPad",
    "id": "mac-designed-for-ipad",
    "isSupported": true,
    "targetPlatform": "darwin",
    "emulator": false,
    "sdk": "macOS 14.4 23E214 darwin-arm64",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": true,
      "hardwareRendering": false,
      "startPaused": true
    }
  },
  {
    "name": "Chrome",
    "id": "chrome",
    "isSupported": true,
    "targetPlatform": "web-javascript",
    "emulator": false,
    "sdk": "Google Chrome 123.0.6312.46",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": false,
      "hardwareRendering": false,
      "startPaused": true
    }
  }
]
```

### PR DESCRIPTION
**Pull request by matanlurey**
Fixes https://github.com/flutter/flutter/issues/145158.

In an ideal world, the `--machine` flag would be strictly a global flag which sub-commands can choose to use (or perhaps just to report a `toolExit` that they don't have a `--machine` supported-mode if not. However currently, there is both a global flag, and command-specific flags.

This leads to the confusing scenario where:
```sh
flutter devices --machine
```

... still checks for a Flutter update, printing a banner and breaking the JSON output.

This PR "fixes" that by allowing `--machine` _anywhere_ in the command-line arguments to suppress the check.

/cc @johnmccutchan.

### CODE REVIEW

File: packages/flutter_tools/lib/src/runner/flutter_command_runner.dart [hunk 1]
```diff
@@ -242,9 +245,59 @@ class FlutterCommandRunner extends CommandRunner<void> {
       }
     }
 
+    _machineFlagPresentInAnyCliArg = args.contains('--${FlutterGlobalOptions.kMachineFlag}');
     return super.run(args);
   }
 
+  /// Whether to perform a flutter version check, which prints a warning if old.
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/runner/flutter_command_runner.dart:252]: Nit: Should a function's doc string explain (and thus be coupled to) what the caller(s) plan to do with it? (Not a big deal here since this comment is unlikely to become incorrect)

File: packages/flutter_tools/lib/src/runner/flutter_command_runner.dart [hunk 2]
```diff
@@ -242,9 +245,59 @@ class FlutterCommandRunner extends CommandRunner<void> {
...
+    // 1. We are not attached to a terminal.
+    // 2. The top level command appears to be related to bash/zsh completion.
+    // 3. We are running in a known CI environment.
+    final bool notAttachedToTerminal = !globals.stdio.hasTerminal;
+    final bool redirectedCompletion = (topLevelResults.command?.name ?? '').endsWith('-completion');
+    if (notAttachedToTerminal ||
+        redirectedCompletion ||
+        await globals.botDetector.isRunningOnBot) {
+      return false;
+    }
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/runner/flutter_command_runner.dart:295]: Nit: does this comment provide value? To me, it seems redundant with the code (though `redirectedCompletion` seems like an odd name to me.
```suggestion
    final bool notAttachedToTerminal = !globals.stdio.hasTerminal;
    // e.g. `flutter bash-completion` or `flutter zsh-completion`
    final bool isShellCompletionCommand = (topLevelResults.command?.name ?? '').endsWith('-completion');
    if (notAttachedToTerminal ||
        isShellCompletionCommand ||
        await globals.botDetector.isRunningOnBot) {
      return false;
    }
```

**Review by andrewkolos — APPROVED** [review]
LGTM with uber-nits

File: packages/flutter_tools/lib/src/runner/flutter_command_runner.dart (hunk 1 above)
Comment (matanlurey) [reply packages/flutter_tools/lib/src/runner/flutter_command_runner.dart:252]: Done
