### PR TITLE
Generate RawKeyEvents for iOS 13.4+

### LINKED ISSUE #31945: Keyboard events should be implemented on iOS
RawKeyboardListener works for Android and other platforms, but not on iOS, because it isn't implemented in the [engine](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/system_channels.dart#L158)

See also #2601, and discussion on flutter/engine#8606

### LINKED ISSUE #68741: Framework does not handle key events sent by iOS simulator ( Xcode 12.2 )
Currently it looks like the framework does not handle iOS key events (https://github.com/flutter/flutter/blob/eefcff900c3cdf4aff43751c1b32a3aa65c91a4d/packages/flutter/lib/src/services/raw_keyboard.dart#L346). This causes the terminal to fill up with errors when trying to hot reload/restart.

```
An Observatory debugger and profiler on iPhone SE (2nd generation) is available at: http://127.0.0.1:59659/-Rhr2AmeKQM=/
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: Unknown keymap for key events: ios
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      new RawKeyEvent.fromMessage (package:flutter/src/services/raw_keyboard.dart:346:9)
flutter: #1      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:595:43)
flutter: #2      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
flutter: #3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:47)
flutter: #4      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283:33)
flutter: #5      _invoke3.<anonymous closure> (dart:ui/hooks.dart:274:15)
flutter: #9      _invoke3 (dart:ui/hooks.dart:273:10)
flutter: #10     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Unknown keymap for key events: ios
flutter: Another exception was thrown: Unknown keymap for key events: ios
```

### PR DESCRIPTION
**Pull request by KammererTob**
This is based on the UIKey introduction in 13.4 and this PR: https://github.com/flutter/engine/pull/20972

## Description

This PR generates `RawKeyEventData` for iOS and in turn `RawKeyDownEvent` and `RawKeyUpEvent` appropriately. 
The mapping for the keyCodes to `PhysicalKeyboardKeys` was done based on this documentation: https://developer.apple.com/documentation/uikit/uikeyboardhidusage?language=objc, which seems to be a complete copy of the usage table found here: https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf
I have not included every key listed there since they seemed to be very hardware specific, but i can add them if desired.

I also noticed that the `RawKeyDownEvent` has a `character` property which is filled with `message['character']`. This does not work for MacOs and iOS since it is called "characters" for both of them. I was not sure if this was intentional or an oversight. Should this be changed to "character" for iOS and MacOS?

This PR depends on an engine PR: https://github.com/flutter/engine/pull/20972, although it should not be breaking even without this.

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/31945
- Fixes https://github.com/flutter/flutter/issues/68741

## Tests

I added iOS as a platform to the already excellent tests for the other platforms. I also added specific tests for iOS in the style of other tests already existing for other platforms.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Comment by KammererTob** [comment]
I have now made the iOS key code mapping generatable and collectable from the chromium files. This works since the key codes used for iOS are bascially the usbHidCodes (which only very few missing). 
Few notes:
- The `gen_keycodes.dart` also generates header (.h) files inside the engine/src/shell/platform/.../keycodes folder. I did not find any usage for those files and they also do not appear to be checked in. I am mentioning this since i had to split the darwin file into two: keyboard_map_ios.h and keyboard_map_macos.h
- I removed the `// @dart = 2.8` comment on top of the keyboard_maps.tmpl file since this lead to errors when importing the generated file
- The `raw_keyboard_ios.dart` file contains a `_kiOSToLogicalMap` map, which defines a mapping for special non-visible keys in iOS: https://developer.apple.com/documentation/uikit/uikeycommand/input_strings_for_special_keys?language=objc. I was unsure if this is the right place for the mapping, but i felt like it would be wrong to put this very specific use-case in the `keyboard_maps.dart` file.

**Comment by gspencergoog** [comment]
@KammererTob Thanks SO MUCH for this PR.  This is clearly a lot of work, and we have needed keyboard support on iOS for quite a while now.

I'll be looking over this PR and sending you some feedback soon, but I just wanted to say "thank you" first.

File: packages/flutter/lib/src/services/keyboard_maps.dart [hunk 1]
```diff
@@ -1176,6 +1177,196 @@ const Map<int, LogicalKeyboardKey> kMacOsFunctionKeyMap = <int, LogicalKeyboardK
   0x0000005a: LogicalKeyboardKey.f20,
 };
 
+/// Maps iOS-specific key code values representing [PhysicalKeyboardKey].
+///
+/// iOS doesn't provide a scan code, but a virtual keycode to represent a physical key.
+const Map<int, PhysicalKeyboardKey> kIOSToPhysicalKey = <int, PhysicalKeyboardKey>{
```
Comment (gspencergoog) [inline packages/flutter/lib/src/services/keyboard_maps.dart:1183]: Naming conventions say this should be called `kIosToPhysicalKey`. (The style guide actually recommends not starting class names with iOS, and using "Cupertino" or "UiKit" in order to avoid the weird capitalization, but in this case, we're referring to the platform itself, not the UI toolkit or widget set, so I think it is unavoidable. It still needs to be named consistent with other constants, though.)

File: packages/flutter/lib/src/services/keyboard_maps.dart [hunk 2]
```diff
@@ -1176,6 +1177,196 @@ const Map<int, LogicalKeyboardKey> kMacOsFunctionKeyMap = <int, LogicalKeyboardK
...
+  0x000000e4: PhysicalKeyboardKey.controlRight,
+  0x000000e5: PhysicalKeyboardKey.shiftRight,
+  0x000000e6: PhysicalKeyboardKey.altRight,
+  0x000000e7: PhysicalKeyboardKey.metaRight,
+};
+
+/// A map of iOS key codes which have printable representations, but appear
+/// on the number pad. Used to provide different key objects for keys like
+/// KEY_EQUALS and NUMPAD_EQUALS.
+const Map<int, LogicalKeyboardKey> kIOSNumPadMap = <int, LogicalKeyboardKey>{
```
Comment (gspencergoog) [inline packages/flutter/lib/src/services/keyboard_maps.dart:1348]: Use `kIosNumPadMap` instead.

File: packages/flutter/lib/src/services/raw_keyboard.dart [hunk 3]
```diff
@@ -299,6 +300,13 @@ abstract class RawKeyEvent with Diagnosticable {
             keyCode: message['keyCode'] as int? ?? 0,
             modifiers: message['modifiers'] as int? ?? 0);
         break;
+      case 'ios':
+        data = RawKeyEventDataIOS(
```
Comment (gspencergoog) [inline packages/flutter/lib/src/services/raw_keyboard.dart:304]: Should be called `RawKeyEventDataIos`.

File: packages/flutter/lib/src/services/raw_keyboard.dart [hunk 4]
```diff
@@ -324,7 +332,7 @@ abstract class RawKeyEvent with Diagnosticable {
         );
         break;
       default:
-        // Raw key events are not yet implemented  on iOS or other platforms,
+        // Raw key events are not yet implemented on other platforms,
```
Comment (gspencergoog) [inline packages/flutter/lib/src/services/raw_keyboard.dart:335]: Actually, iOS is the last platform that needs to have raw key events implemented.  You can change out this comment block for something like:

```dart
/// This exception would only be hit on platforms that haven't yet
/// implemented raw key events, but will only be triggered if the
/// engine for those platforms sends raw key event messages in the
/// first place.
```

File: packages/flutter/lib/src/services/raw_keyboard.dart [hunk 5]
```diff
@@ -333,7 +341,7 @@ abstract class RawKeyEvent with Diagnosticable {
     final String type = message['type'] as String;
     switch (type) {
       case 'keydown':
-        return RawKeyDownEvent(data: data, character: message['character'] as String);
+        return RawKeyDownEvent(data: data, character: message['character'] as String); // Missing for Mac/iOS?
```
Comment (gspencergoog) [inline packages/flutter/lib/src/services/raw_keyboard.dart:344]: Hmm. I actually think this is missing for all platforms except Android. Nice find: I can't believe I didn't see that earlier.

Don't bother fixing it here, this PR is big enough as it is. I captured this in [this issue](https://github.com/flutter/flutter/issues/65401).

(do remove the comment though)

File: packages/flutter/lib/src/services/raw_keyboard_ios.dart [hunk 6]
```diff
@@ -0,0 +1,370 @@
...
+import 'package:flutter/foundation.dart';
+
+import 'keyboard_key.dart';
+import 'keyboard_maps.dart';
+import 'raw_keyboard.dart';
+
+/// Maps iOS specific string values of nonvisible keys to logical keys
+///
+/// See: https://developer.apple.com/documentation/uikit/uikeycommand/input_strings_for_special_keys?language=objc
+const Map<String, LogicalKeyboardKey> _kiOSToLogicalMap = <String, LogicalKeyboardKey>{
```
Comment (gspencergoog) [inline packages/flutter/lib/src/services/raw_keyboard_ios.dart:14]: Should be named `_kIosToLogicalMap`

File: packages/flutter/lib/src/services/raw_keyboard_ios.dart [hunk 7]
```diff
@@ -0,0 +1,370 @@
...
+      return LogicalKeyboardKey.findKeyByKeyId(keyId) ?? LogicalKeyboardKey(
+        keyId,
+        keyLabel: physicalKey.debugName ?? '',
+        debugName: physicalKey.debugName,
+      );
+    }
+
+    // This is a non-printable key that is unrecognized, so a new code is minted
+    // with the autogenerated bit set.
+    const int iOSKeyIdPlane = 0x00400000000;
```
Comment (gspencergoog) [inline packages/flutter/lib/src/services/raw_keyboard_ios.dart:153]: This should be named as `iosKeyIdPlane`.

File: packages/flutter/lib/src/services/raw_keyboard_ios.dart [hunk 8]
```diff
@@ -0,0 +1,370 @@
...
+  /// event coalescing information.
+  static const int deviceIndependentMask = 0xffff0000;
+
+  @override
+  String toString() {
+    return '${objectRuntimeType(this, 'RawKeyEventDataIOS')}(keyLabel: $keyLabel, keyCode: $keyCode, characters: $characters,'
+        ' unmodifiedCharacters: $charactersIgnoringModifiers, modifiers: $modifiers, '
+        'modifiers down: $modifiersPressed)';
+  }
+}
```
Comment (gspencergoog) [inline packages/flutter/lib/src/services/raw_keyboard_ios.dart:370]: Add newline at EOF.

**Review by gspencergoog — CHANGES_REQUESTED** [review]
Overall, this looks quite good, just some naming issues.

**Comment by gspencergoog** [comment]
> - The `gen_keycodes.dart` also generates header (.h) files inside the engine/src/shell/platform/.../keycodes folder. I did not find any usage for those files and they also do not appear to be checked in. I am mentioning this since i had to split the darwin file into two: keyboard_map_ios.h and keyboard_map_macos.h

They aren't actually used yet, but are part of our (currently underway) effort to migrate all of this platform specific code into the engine. (see https://flutter.dev/go/platform-based-key-events)

> - I removed the `// @dart = 2.8` comment on top of the keyboard_maps.tmpl file since this lead to errors when importing the generated file

Thanks, this should have been removed as part of our non-nullable-by-default migration which is currently in progress.

> - The `raw_keyboard_ios.dart` file contains a `_kiOSToLogicalMap` map, which defines a mapping for special non-visible keys in iOS: https://developer.apple.com/documentation/uikit/uikeycommand/input_strings_for_special_keys?language=objc. I was unsure if this is the right place for the mapping, but i felt like it would be wrong to put this very specific use-case in the `keyboard_maps.dart` file.

That seems like the right place to put it to me.

**Comment by gspencergoog** [comment]
FYI @dkwingsmt, who is doing the platform based key event migration.

**Comment by dkwingsmt** [comment]
@gspencergoog Thanks! I can't find any issues that gspencergoog hasn't. (There is yet another case of `IOS` that probably should be changed to `Ios`).
Also great PR!

**Comment by KammererTob** [comment]
Thanks for the review and explanations! I have made the requested changes, and also renamed some more variables to be more in line with the requested naming scheme (if this went too far, then i will revert it if needed).

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

I could merge this, but until you land the engine change, it obviously won't do anything, so I'd like to wait until you're close to landing the engine change, and land them about the same time so that people don't get confused as to why it looks like we have iOS key support, but it doesn't work.

**Comment by gspencergoog** [comment]
@KammererTob looks like this needs to have a conflict resolved, but once that happens, I can land it, since the corresponding engine change has landed now.

**Comment by KammererTob** [comment]
@gspencergoog I resolved the merge conflict so it should be g2g
