### PR TITLE
Calendar font factor

### LINKED ISSUE #61334: [showDatePicker]  RenderFlex overflow exception with orientation of Axis.vertical and setting the text size to smallest from device settings.
## Steps to Reproduce

1. Open _DatePickerDialog (via showDatePicker method).
2. Click edit icon top Enter Date.
3. Enter an invalid date (1/1/1) in this case.

This is only occurring on my iPhone 7 right now. Also despite what the doctor says I do have both dart and flutter plugins installed and up to date (another issues I will have to look into).

**Expected results:** 

Expect to see error message "Out of Range", not overflow message in flutter.

**Actual results:** 

See attached image.

image

<details>
  <summary>Logs</summary>

```
   +1 ms] flutter: The following assertion was thrown during layout:
[        ] flutter: A RenderFlex overflowed by 4.9 pixels on the bottom.
[        ] flutter:
[        ] flutter: The relevant error-causing widget was:
[        ] flutter:   Theme
[        ] flutter:   file:///Users/cory.ingram/Documents/Development/accuro-mobile/lib/widgets/acc_calendar/acc_calendar.dart:402:18
[        ] flutter:
[        ] flutter: The overflowing RenderFlex has an orientation of Axis.vertical.
[        ] flutter: The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
[        ] flutter: black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
[        ] flutter: Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
[        ] flutter: RenderFlex to fit within the available space instead of being sized to their natural size.
[        ] flutter: This is considered an error condition because it indicates that there is content that cannot be
[        ] flutter: seen. If the content is legitimately bigger than the available space, consider clipping it with a
[        ] flutter: ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
[        ] flutter: like a ListView.
[        ] flutter: The specific RenderFlex in question is: RenderFlex#d5884 OVERFLOWING:
[        ] flutter:   needs compositing
[        ] flutter:   creator: Column ← ConstrainedBox ← Container ← LayoutBuilder ← OrientationBuilder ←
[        ] flutter:     InputDatePickerFormField ← _FormScope ← WillPopScope ← Form-[LabeledGlobalKey<FormState>#748fa] ←
[        ] flutter:     Expanded ← Column ← Builder ← ⋯
[        ] flutter:   parentData: <none> (can use size)
[        ] flutter:   constraints: BoxConstraints(w=291.2, h=66.2)
[        ] flutter:   size: Size(291.2, 66.2)
[        ] flutter:   direction: vertical
[        ] flutter:   mainAxisAlignment: start
[        ] flutter:   mainAxisSize: max
[        ] flutter:   crossAxisAlignment: center
[        ] flutter:   verticalDirection: down
[        ] flutter: ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```

```

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G103, locale en-CA)
    • Flutter version 1.17.5 at /Users/cory.ingram/Documents/Development/SDK/flutter
    • Framework revision 8af6b2f038 (12 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/cory.ingram/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (3 available)
    • 9024O                        • de3d4e87                                 • android-arm • Android 7.1.1 (API 25)
    • Android SDK built for x86 64 • emulator-5554                            • android-x64 • Android 10 (API 29)
      (emulator)

```

</details>

### PR DESCRIPTION
**Pull request by MitchellGoodwin**
Increases the max text can be scaled for the date picker in calendar mode and input mode. Previously the max across the whole widget was 1.3. Due to the size of the widget, this was increased as much as possible with different values used in different places. Testing and screenshots where taken on the iPhone SE 3rd generation simulator, set at max font size, which is a value of 3.0. Android has a lower max font scale value of 2.0, and the iPhone SE is about the smallest phone with a lower pixel density ratio.

Fixes internal issues b/316958515 and b/316959677 
Also fixes #61334

Comparison for calendar mode in portrait and landscape:

| Before    | After |
| -------- | ------- |
| Old-SE-Portrait-DayPicker | Screenshot 2024-07-25 at 1 25 41 PM |
| Old-SE-Portrait-YearPicker | Screenshot 2024-07-25 at 1 26 38 PM |
| Old-SE-Landscape-DayPicker | Screenshot 2024-07-25 at 1 25 52 PM |
| Old-SE-Landscape-YearPicker | Screenshot 2024-07-25 at 1 26 47 PM |

The title text is smaller when the entry mode button is available:
Screenshot 2024-07-25 at 1 24 52 PM

Adjustments were made to input mode as well, but they are simpler

Screenshot 2024-07-25 at 1 43 39 PM
Screenshot 2024-07-25 at 1 43 48 PM

Date range picker was not adjusted with this PR. It still has a max of 1.3.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by chunhtai** [comment]
Does the 3 font scale limit covers all the possible font scaling set by the android and ios phone? otherwise, It would seem weird the widget stop scaling suddenly compare to other widgets in the app.

**Comment by MitchellGoodwin** [comment]
> Does the 3 font scale limit covers all the possible font scaling set by the android and ios phone? otherwise, It would seem weird the widget stop scaling suddenly compare to other widgets in the app.

Yes, 3.0 is the highest iOS phones can go, currently. Android has a lower max of 2.0, so 3.0 will cover both.

In different sections of the widget, I used a lower max somewhat strategically. Having a max of 3.0 globally caused a lot of overflow and clipping errors. So the header text doesn't scale as much up, because it already has large text compared to the rest of the widget.

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 1]
```diff
@@ -315,20 +315,28 @@ class _CalendarDatePickerState extends State<CalendarDatePicker> {
     assert(debugCheckHasMaterial(context));
     assert(debugCheckHasMaterialLocalizations(context));
     assert(debugCheckHasDirectionality(context));
+    const double fontSizeToScale = 14.0;
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/calendar_date_picker.dart:318]: Where does this int come from? Should we get this value from DefaultTextStyle instead?

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 2]
```diff
@@ -315,20 +315,28 @@ class _CalendarDatePickerState extends State<CalendarDatePicker> {
...
+    final double textScaleFactor = MediaQuery.textScalerOf(context).clamp(maxScaleFactor: 3.0).scale(fontSizeToScale) / fontSizeToScale;
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/calendar_date_picker.dart:319]: Can you create a const for 3.0 and name it something like maxScalingFromMobileDevice and add some comment to explain how this value come from?

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 3]
```diff
@@ -315,20 +315,28 @@ class _CalendarDatePickerState extends State<CalendarDatePicker> {
...
+    // Scale the height of the picker area up with larger text.
+    final double scaledMaxDayPickerHeight =
+      textScaleFactor > 1.3 ? _maxDayPickerHeight + ((_maxDayPickerRowCount + 1) * ((textScaleFactor - 1) * 8)) : _maxDayPickerHeight;
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/calendar_date_picker.dart:322]: any reason we set the height flat before 1.3 scaling? If there is a reason, can you add some comment or use const with name for readability?

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 4]
```diff
@@ -986,12 +997,15 @@ class _DayPickerState extends State<_DayPicker> {
...
         horizontal: _monthPickerHorizontalPadding,
       ),
-      child: GridView.custom(
-        physics: const ClampingScrollPhysics(),
-        gridDelegate: _dayPickerGridDelegate,
-        childrenDelegate: SliverChildListDelegate(
-          dayItems,
-          addRepaintBoundaries: false,
+      child: MediaQuery.withClampedTextScaling(
+        maxScaleFactor: isLandscapeOrientation ? 1.5 : 2.0,
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/calendar_date_picker.dart:1001]: same here, instead of some inline magic number, we should define a const with reasonable name for readability

File: packages/flutter/lib/src/material/calendar_date_picker.dart [hunk 5]
```diff
@@ -1116,14 +1130,20 @@ class _DayState extends State<_Day> {
...
 
 class _DayPickerGridDelegate extends SliverGridDelegate {
-  const _DayPickerGridDelegate();
+  const _DayPickerGridDelegate(this.context);
+
+  final BuildContext context;
 
   @override
   SliverGridLayout getLayout(SliverConstraints constraints) {
+    const double fontSizeToScale = 14.0;
```
Comment (chunhtai) [inline packages/flutter/lib/src/material/calendar_date_picker.dart:1139]: same, should we get this from defaulttextstyle?

**Comment by MitchellGoodwin** [comment]
@chunhtai I put all of the magic numbers into constants at the top of the files with documentation. Maybe of note is that the `14.0` was only used to get the ratio of the text scaling, so it's not too important what the size actually is, as long as it's consistent.

**Comment by chunhtai** [comment]
> @chunhtai I put all of the magic numbers into constants at the top of the files with documentation. Maybe of note is that the `14.0` was only used to get the ratio of the text scaling, so it's not too important what the size actually is, as long as it's consistent.

Android has non linear scaling for font size, that is. The larger the font size it is, the less scaling it will receive. Although I think this is probably ok since there shouldn't be extreme font size in datepicker.

**Review by chunhtai — APPROVED** [review]
LGTM
