### PR TITLE
Prevents infinite loop in Table._computeColumnWidths

### LINKED ISSUE #36256: Infinite loop in Table._computeColumnWidths
## Steps to Reproduce

This is probably hard to reproduce exactly, as the bug depends on multiple values. For me, what triggers the bug is the following combination of column widths passed to Table constructor:
```dart
columnWidths: const <int, TableColumnWidth>{
  0: const FlexColumnWidth(0.15),
  1: const FlexColumnWidth(1),
  2: const FlexColumnWidth(0.1),
  3: const FlexColumnWidth(0.1),
  4: const FlexColumnWidth(0.1),
  5: const FlexColumnWidth(0.1),
  6: const FlexColumnWidth(0.1),
},
``` 

This causes my application to freeze.

The problematic part is the following [code fragment in `lib/src/rendering/table.dart`](https://github.com/flutter/flutter/blob/ad507723ec65f7b0e67d587475eff3829bc91cf8/packages/flutter/lib/src/rendering/table.dart#L946-L970):

```dart
      if (deficit > 0.0) {
        // Now we have to take out the remaining space from the
        // columns that aren't minimum sized.
        // To make this fair, we repeatedly remove equal amounts from
        // each column, clamped to the minimum width, until we run out
        // of columns that aren't at their minWidth.
        do {
          final double delta = deficit / availableColumns;
          int newAvailableColumns = 0;
          for (int x = 0; x < columns; x += 1) {
            final double availableDelta = widths[x] - minWidths[x];
            if (availableDelta > 0.0) {
              if (availableDelta <= delta) {
                // shrank to minimum
                deficit -= widths[x] - minWidths[x];
                widths[x] = minWidths[x];
              } else {
                deficit -= delta;
                widths[x] -= delta;
                newAvailableColumns += 1;
              }
            }
          }
          availableColumns = newAvailableColumns;
        } while (deficit > 0.0 && availableColumns > 0);
```

What happens, is that for very small values of `deficit`, `delta` becomes 0, and the loop continues forever.

This is a similar issue to the #27083, and I'm going to resolve it in a similar manner.

## Logs

`flutter doctor -v`

```
[✓] Flutter (Channel beta, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-PL)
    • Flutter version 1.7.8+hotfix.3 at /Users/krzysztofsroka/Library/Flutter
    • Framework revision b712a172f9 (7 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/krzysztofsroka/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/krzysztofsroka/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPhone 8 • 6134FBD2-BDD7-413F-AABA-99D89982112F • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

### PR DESCRIPTION
**Pull request by kpsroka**
## Description

Fixes infinite loop in Table._computeColumnWidths occurring in cases redistributed deficit is so small that the result of dividing it by number of columns available results in `0.0`. 

This infinite loop resulted in application freezing.

## Related Issues

Closes #36256, which is similar to #27083.

## Tests

I added the following tests:

Added a regression test in `packages/flutter/test/widgets/table_test.dart`.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/widgets/table_test.dart [hunk 1]
```diff
@@ -376,6 +376,32 @@ void main() {
     // If the above bug is present this test will never terminate.
   });
 
+    testWidgets('Really small deficit double precision error (redistributing deficit)', (WidgetTester tester) async {
+    // Regression test for https://github.com/flutter/flutter/issues/36256
```
Comment (Piinks) [inline packages/flutter/test/widgets/table_test.dart]: Nit: Unnecessary comment.

File: packages/flutter/test/widgets/table_test.dart [hunk 2]
```diff
@@ -376,6 +376,32 @@ void main() {
...
+            6: FlexColumnWidth(0.123),
+          },
+          children: <TableRow>[
+            TableRow(children: List<Widget>.filled(7, cell)),
+            TableRow(children: List<Widget>.filled(7, cell)),
+          ],
+        ),
+      ),
+    );
+    // If the above bug is present this test will never terminate.
```
Comment (Piinks) [inline packages/flutter/test/widgets/table_test.dart]: Is there a way we can make this test pass/fail instead of pass/hang?

Comment (kpsroka) [reply packages/flutter/test/widgets/table_test.dart]: I've tried some approaches, but to no avail, since the main thread is stuck in an endless loop, it never allows interruptions to finish the test early. I thought running `pumpWidget` in a separate isolate (via `compute`) would work, but I got the following error when attempting that (seems to be partial?):
```
../../third_party/dart/runtime/vm/raw_object_snapshot.cc: 523: error: unreachable code
Shell: version=2.5.0-dev.1.0.flutter-24725a8559 (Thu Jul 11 11:40:03 2019 +0000) on "linux_x64"
Shell: thread=20327, isolate=main(0x5023370)
Shell:   pc 0x0000000002e8e92c fp 0x00007ffd578277b0
/home/kps/Workspace/flutter/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester+0x2c8e92c
Shell: -- End of DumpStackTrace
```

Comment (kpsroka) [reply packages/flutter/test/widgets/table_test.dart]: (It's probably me misusing the `compute` method, though)

**Comment by kpsroka** [comment]
@Piinks could you take another look?

File: packages/flutter/test/widgets/table_test.dart (hunk 2 above)
Comment (Piinks) [reply packages/flutter/test/widgets/table_test.dart]: Perhaps instead of trying to stop an infinite loop in the test, you could assert in the computeColumnWidths method that the deficit or minimumDeficit is never a value that would lead to this hanging process?

Comment (Piinks) [reply packages/flutter/test/widgets/table_test.dart]: I noticed that the fix for the similar issue you referenced (#27083) utilized a similar test (#27112), so this may actually be ok. 
cc/ @jonahwilliams

**Review by Piinks — COMMENTED** [review]
I think this is ok after seeing a similar issue fixed in a similar way. I would like to see how someone who is a little more familiar with this area feels.
cc/ @dnfield and @chunhtai who appear to have done work here recently around precision errors.

File: packages/flutter/lib/src/rendering/table.dart [hunk 3]
```diff
@@ -943,7 +943,7 @@ class RenderTable extends RenderBox {
         }
         totalFlex = newTotalFlex;
       }
-      if (deficit > 0.0) {
+      if (deficit > minimumDeficit) {
```
Comment (dnfield) [inline packages/flutter/lib/src/rendering/table.dart]: I'm not sure about the history here, but maybe we can just directly use precisionErrorTolerance instead of creating a copy of it in minimum deficit (here and above).

Comment (dnfield) [reply packages/flutter/lib/src/rendering/table.dart]: Could we just convert this whole `if /do  /while` block to a regular `while`?

File: packages/flutter/test/widgets/table_test.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter/test/widgets/table_test.dart]: You can't invoke dart UI methods from a separate isolate unfortunately.

The problem is that it becomes very hard to tell the difference between a test that never terminates and a test that's just running more slowly and timing out.  That said, I can't think of a betterw ay to test this.  Maybe we can just move this comment up to the top of the test method and clarify that a timeout on this test may indicate a regression on a never-terminating loop in the framework.

Comment (dnfield) [reply packages/flutter/test/widgets/table_test.dart]: @kpsroka do you think it would make more sense to test against the rendering layer e.g. `computeMinIntrinsicHeight` and `performLayout`?  And we should probably name the test something like `Computing small widths can terminate`.  That should make it a bit clearer what we're testing and where the bug is.

Comment (dnfield) [reply packages/flutter/test/widgets/table_test.dart]: (that test would be in `test/rendering/table_test.dart`)

I still wouldn't use an isolate to check it, because that will be prone to flakiness as much as just letting the test timeout.

Comment (kpsroka) [reply packages/flutter/test/widgets/table_test.dart]: @dnfield I've now added a similar test in `rendering/table_test.dart`. Please let me know which one seems more adequate to you. The one in `rendering` is obviously doing less work, as it just triggers layout(), but readability-wise they are very similar.

For the timeout, I introduced `assert(delta != 0)` in the while loop, that should fail when the erroneous condition happens again.

As for the test name, it's not necessarily 'small widths' that are the problem, but minuscule difference between calculated flex width and constraints. I'll think about a better name.

File: packages/flutter/test/rendering/table_test.dart [hunk 4]
```diff
@@ -217,4 +217,29 @@ void main() {
...
+        1: FlexColumnWidth(0.123),
+        2: FlexColumnWidth(0.123),
+        3: FlexColumnWidth(0.123),
+        4: FlexColumnWidth(0.123),
+        5: FlexColumnWidth(0.123),
+        6: FlexColumnWidth(0.123),
+      },
+    );
+
+    layout(table, constraints: BoxConstraints.tight(const Size(800.0, 600.0)));
```
Comment (dnfield) [inline packages/flutter/test/rendering/table_test.dart]: I think we probably want to `expect` something about the size after this

File: packages/flutter/test/widgets/table_test.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter/test/widgets/table_test.dart]: Having both is good - if they fail it will be a little more obvious about what is causing the problem now.

**Review by dnfield — APPROVED** [review]
LGTM with an expectationin the layout test

File: packages/flutter/test/rendering/table_test.dart (hunk 4 above)
Comment (kpsroka) [reply packages/flutter/test/rendering/table_test.dart]: I added `expect(table.hasSize, true)`.

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
Thank you for the contribution!

File: packages/flutter/test/widgets/table_test.dart [hunk 5]
```diff
@@ -376,6 +376,33 @@ void main() {
...
+              6: FlexColumnWidth(0.123),
+            },
+            children: <TableRow>[
+              TableRow(children: List<Widget>.filled(7, cell)),
+              TableRow(children: List<Widget>.filled(7, cell)),
+            ],
+          ),
+        ),
+      ),
+    );
```
Comment (chunhtai) [inline packages/flutter/test/widgets/table_test.dart]: Let's expect something here as well. Also, can you add a comment that indicate the behavior of this test? Something like it will be stuck in an infinite loop.

**Review by chunhtai — APPROVED** [review]
LGTM with a minor suggestion

File: packages/flutter/test/widgets/table_test.dart (hunk 5 above)
Comment (kpsroka) [reply packages/flutter/test/widgets/table_test.dart]: I'm not sure what can be expected here. With my changes, `pumpWidget` is going to fail, since performLayout() will get interrupted. If `pumpWidget` was synchronous, I could add something like `expect(() => pumpWidget..., returnsNormally)`, but I don't know how to apply that to async tests.
I've added a comment that an assertion failure should be expected if the error occurs.

Comment (chunhtai) [reply packages/flutter/test/widgets/table_test.dart]: you can do expect(tester.takeException(), null);

Comment (kpsroka) [reply packages/flutter/test/widgets/table_test.dart]: Done.

**Comment by dnfield** [comment]
We can ignore the testing-windows failure, that's a known flake.  Once flutter-build is green this can land.
