### PR TITLE
Check for watch companion in build settings

### LINKED ISSUE #92294: Flutter build error after adding WatchOS target in Xcode Project
After adding watch Extention in ios/Runner.xcworkspace flutter run fails with below build error

### Steps to reproduce 

1. `flutter create watch_test`
2. `cd watch_test` & `flutter run` - App successfully launches in iOS simulator
3. Now open ios/Runner.xcworkspace and add new target as watch app extension for iOS app
4. `flutter run` will give error 

### Error log
note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphonesimulator' (in target 'watch WatchKit
    Extension' from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphonesimulator' (in target 'watch WatchKit
    Extension' from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphonesimulator' (in target 'watch' from project
    'Runner')
    error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphonesimulator' (in target 'watch' from project
    'Runner')
    warning: duplicate output file '' on task: RegisterExecutionPolicyException /Users/raeeskattali/Downloads/w_test2/build/ios/Debug-iphonesimulator (in
    target 'watch' from project 'Runner

### Other details

- Tried on both stable & master branch
- WatchOS targets Supported Platforms is watchOS & Build Active Arch only YES
- Trying from M1 Macbook

Screen Shot 2021-10-21 at 4 53 27 PM

### PR DESCRIPTION
**Pull request by vashworth**
Add an additional check for watch companion by checking build settings of different schemes. 

Fixes https://github.com/flutter/flutter/issues/92294.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 1]
```diff
@@ -357,6 +364,28 @@ class IosProject extends XcodeBasedProject {
...
     }
+
+    // The build settings of the watchOS companion app's scheme 
+    // may contain the key INFOPLIST_KEY_WKCompanionAppBundleIdentifier
+    final bool watchIdentifierFound = firstMatchInFile(xcodeProjectInfoFile, _watchAppCompanionAppIdPattern) != null;
+    if (watchIdentifierFound == false) {
+      return false;
+    }
+    for (final String scheme in schemes) {
+      final Map<String, String>? allBuildSettings = await buildSettingsForBuildInfo(buildInfo, deviceId: deviceId, scheme: scheme, isWatch: true);
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/xcode_project.dart:375]: This line is a little long.
```suggestion
      final Map<String, String>? allBuildSettings = await buildSettingsForBuildInfo(
        buildInfo, 
        deviceId: deviceId, 
        scheme: scheme, 
        isWatch: true,
      );
```

File: packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart [hunk 2]
```diff
@@ -395,6 +395,40 @@ void main() {
...
+      kWhichSysctlCommand,
+      kx64CheckCommand,
+      FakeCommand(
+        command: <String>[
+          'xcrun',
+          'xcodebuild',
+          '-project',
+          '/',
+          '-destination',
+          'generic/platform=watchOS',
```
Comment (jmagman) [inline packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart:411]: Add test for the `generic/platform=watchOS Simulator` case.

**Review by jmagman — COMMENTED** [review]
```
/b/s/w/ir/x/w/flutter sdk/packages/flutter_tools/test/general.shard/project_test.dart:792: trailing U+0020 space character
/b/s/w/ir/x/w/flutter sdk/packages/flutter_tools/test/general.shard/project_test.dart:814: trailing U+0020 space character
/b/s/w/ir/x/w/flutter sdk/packages/flutter_tools/lib/src/xcode_project.dart:368: trailing U+0020 space character
```

Your IDE should have a "remove trailing spaces" editor option.
Screen Shot 2022-10-24 at 11 55 47 AM

Also update the https://github.com/flutter/flutter/tree/master/dev/integration_tests/ios_app_with_extensions integration test to use `INFOPLIST_KEY_WKCompanionAppBundleIdentifier` instead.  Ideally we would have 2 integration tests that tested both the Info.plist and build settings paths respectively, but I think just testing the current default pattern with the build setting would be enough.

File: packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart (hunk 2 above)
Comment (vashworth) [reply packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart:411]: Added in new commit https://github.com/flutter/flutter/pull/113956/commits/44f124ac48ee4cfeedb3bd889897359176302331.

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 1 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: Changed in new commit https://github.com/flutter/flutter/pull/113956/commits/44f124ac48ee4cfeedb3bd889897359176302331.

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 3]
```diff
@@ -327,7 +334,7 @@ class IosProject extends XcodeBasedProject {
   }
 
   /// Check if one the [targets] of the project is a watchOS companion app target.
-  Future<bool> containsWatchCompanion(List<String> targets, BuildInfo buildInfo, String? deviceId) async {
+  Future<bool> containsWatchCompanion(List<String> targets, List<String> schemes, BuildInfo buildInfo, String? deviceId) async {
```
[the remark this answers is not in the document]
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: Changed in new commit https://github.com/flutter/flutter/pull/113956/commits/44f124ac48ee4cfeedb3bd889897359176302331.

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 4]
```diff
@@ -357,6 +369,33 @@ class IosProject extends XcodeBasedProject {
         }
       }
     }
+
+    // The build settings of the watchOS companion app's scheme
+    // may contain the key INFOPLIST_KEY_WKCompanionAppBundleIdentifier
+    final bool watchIdentifierFound = firstMatchInFile(xcodeProjectInfoFile, _watchAppCompanionAppIdPattern) != null;
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/xcode_project.dart:375]: I don't think this needs to be a regex, you're just checking if the file contains this string at all.  You can also remove `_watchAppCompanionAppIdPattern`.
```suggestion
    final bool watchIdentifierFound = xcodeProjectInfoFile.readAsStringSync().contains('WKCompanionAppBundleIdentifier');
```

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 5]
```diff
@@ -357,6 +369,33 @@ class IosProject extends XcodeBasedProject {
         }
       }
     }
+
+    // The build settings of the watchOS companion app's scheme
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/xcode_project.dart:373]: Can you update the "The Info.plist file of a target contains the key WKCompanionAppBundleIdentifier" comment above to explain why the Info.plist is checked first, then with a fallback to the more expensive build setting check?

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 6]
```diff
@@ -357,6 +369,33 @@ class IosProject extends XcodeBasedProject {
...
+        deviceId: deviceId,
+        scheme: scheme,
+        isWatch: true,
+      );
+      if (allBuildSettings != null) {
+        final String? fromBuild = allBuildSettings['INFOPLIST_KEY_WKCompanionAppBundleIdentifier'];
+        if (bundleIdentifier == fromBuild) {
+          return true;
+        }
+        if (fromBuild != null && fromBuild.contains(r'$')) {
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/xcode_project.dart:391]:
```suggestion
        if (fromBuild != null && fromBuild.contains('$')) {
```

**Review by jmagman — COMMENTED** [review]
Can this be marked ready for review?  Looks pretty good to me.

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 5 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: Updated in https://github.com/flutter/flutter/pull/113956/commits/25df5b631ab3acaffc8d9bfe63658fb3231f128b.

File: packages/flutter_tools/lib/src/xcode_project.dart (hunk 6 above)
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart:390]: I found that removing the `r` caused an error, because it expects an identifier or expression. If I escaped it, like `'\$'`, the linter suggests to use a raw string instead of escaping https://dart-lang.github.io/linter/lints/use_raw_strings.html. So I left it as is.

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 7]
```diff
@@ -348,8 +346,8 @@ class IosProject extends XcodeBasedProject {
     for (final String target in targets) {
       // Create Info.plist file of the target.
       final File infoFile = hostAppRoot.childDirectory(target).childFile('Info.plist');
-      // The Info.plist file of a target contains the key WKCompanionAppBundleIdentifier,
-      // if it is a watchOS companion app.
+      // In older versions of XCode, if the target was a watchOS companion app,
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/xcode_project.dart:349]:
```suggestion
      // In older versions of Xcode, if the target was a watchOS companion app,
```

**Comment by jmagman** [comment]
@vashworth can you mark this Ready for review?  Generally as soon as it _is_ ready for review it's good to make it not a draft to indicate to the reviewers that it's not a work in progress. 🙂 
Screen Shot 2022-10-25 at 8 45 25 AM

File: packages/flutter_tools/lib/src/xcode_project.dart [hunk 8]
```diff
@@ -357,6 +367,34 @@ class IosProject extends XcodeBasedProject {
...
+        deviceId: deviceId,
+        scheme: scheme,
+        isWatch: true,
+      );
+      if (allBuildSettings != null) {
+        final String? fromBuild = allBuildSettings['INFOPLIST_KEY_WKCompanionAppBundleIdentifier'];
+        if (bundleIdentifier == fromBuild) {
+          return true;
+        }
+        if (fromBuild != null && fromBuild.contains('\$')) {
```
[the remark this answers is not in the document]
Comment (vashworth) [reply packages/flutter_tools/lib/src/xcode_project.dart]: Whoops, I had been experimenting with it and forgot to change it back. I'll be more careful in the future!

[the remark this answers is not in the document]
Comment (jmagman) [reply packages/flutter_tools/lib/src/xcode_project.dart]: No worries at all, was checking if we needed to tune your IDE 🙂

**Review by jmagman — APPROVED** [review]
This looks great, a mighty first PR!  🎉  Thank you for working on this!

**Comment by jmagman** [comment]
Also, this PR satisfies these three checks.

> * [ ]  I signed the [CLA](https://cla.developers.google.com/).
> * [ ]  I updated/added relevant documentation (doc comments with `///`).
> * [ ]  All existing and new tests are passing.

**Review by christopherfujino — APPROVED** [review]
LGTM, good work!
