### PR TITLE
DismissDirection.none will not prevent scrolling

### LINKED ISSUE #84962: DismissDirection.none prevents scrolling in ListView
## Steps to Reproduce

1. Create a list view
2. For each item in list view add a dismissible widget
3. Set dismissible direction to DismissDirection.none 

**Expected results:** 
I think DismissDirection.none should not prevent scrolling 

**Actual results:** 
I could not scroll a ListView with Dismissible widgets that have the direction: DismissDirection.none 

<details>
  <summary>Logs</summary>

There are no errors for me, I sent a project that has the problem to my github. [A project that shows the problem](https://github.com/postpasspost/dis)

Any way to solve the problem would be helpful. Thank you.

```
The problem does not show any errors
```

```
The problem does not show any errors
```

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4  darwin-x64, locale en-FR)
    • Flutter version 2.2.1 at /Users/flutter
    • Framework revision 02c026b03c (4 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users//Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • iPhone SE (1st generation) (mobile) • • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome




```

</details>

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/84962

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/dismissible.dart [hunk 1]
```diff
@@ -610,6 +610,12 @@ class _DismissibleState extends State<Dismissible> with TickerProviderStateMixin
         content,
       ]);
     }
+
+    // If the DismissDirection is none, we do not add drag gestures as it cannot
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/dismissible.dart:614]: Maybe: ... gestures because the content cannot be dragged.

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/widgets/dismissible.dart [hunk 2]
```diff
@@ -610,6 +610,12 @@ class _DismissibleState extends State<Dismissible> with TickerProviderStateMixin
...
+    // be dragged.
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/dismissible.dart:615]:
```suggestion
    // If the DismissDirection is none, we do not add drag gestures because the content
    // cannot be dragged.
```

**Comment by large** [comment]
I see the fix of ListView scrolling with DismissDirection.none has been merged.
When will it be available in a official release?

Version that I tested it on: 
> [√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1202], locale nb-NO)
>     • Flutter version 2.2.3 at C:\src\flutter
>     • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
>     • Engine revision 241c87ad80
>     • Dart version 2.13.4
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at C:\Users\lars\AppData\Local\Android\sdk
>     • Platform android-S, build-tools 30.0.2
>     • Java binary at: c:\src\AndroidStudio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio
>     • Android Studio at c:\src\AndroidStudio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • android-studio-dir = c:\src\AndroidStudio
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [√] Connected device (3 available)
>     • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
>     • Chrome (web)                       • chrome        • web-javascript • Google Chrome 93.0.4577.63
>     • Edge (web)                         • edge          • web-javascript • Microsoft Edge 93.0.961.38
> 
> • No issues found!
