### PR TITLE
iOS Text Selection Menu Overflow

### LINKED ISSUE #35826: text selection toolbar over flow !
A problem happens in **TextFormField** Widget when trying to select part of the input text the **Selection toolbar** show up but not normally it overflow by 3.0 pixels from the right!!!
The funny part that it left more than 3.0 pixels from the left side of screen which its not centered!!

## Picture for the problem
https://ibb.co/k9Rk13M

## Logs

```
`Container(
                                height:
                                    MediaQuery.of(context).size.height * 0.25,
                                margin: EdgeInsets.fromLTRB(marginFixed * 0.5,
                                    0.0, marginFixed * 0.5, marginFixed * 0.5),
                                child: TextField(
                                  enableInteractiveSelection: true,
                                  expands: true,
                                  controller: _noteController,
                                  style: TextStyle(
                                      color: StyleCustom.txtPrimary,
                                      fontSize: 16.0),
                                  maxLines: null,
                                  minLines: null,
                                  decoration: InputDecoration(
                                    hintStyle: TextStyle(
                                        color: StyleCustom.txtSecondry),
                                    border: InputBorder.none,
                                    hintText: 'write your note here',
                                  ),
                                  onChanged: (String value) {
                                    debugPrint(value);
                                  },
                                ),
                              ),`
```

```
`
I/flutter ( 5019): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 5019): The following assertion was thrown during layout:
I/flutter ( 5019): A RenderFlex overflowed by 3.0 pixels on the right.
I/flutter ( 5019):
I/flutter ( 5019): The overflowing RenderFlex has an orientation of Axis.horizontal.
I/flutter ( 5019): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter ( 5019): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter ( 5019): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter ( 5019): RenderFlex to fit within the available space instead of being sized to their natural size.
I/flutter ( 5019): This is considered an error condition because it indicates that there is content that cannot be
I/flutter ( 5019): seen. If the content is legitimately bigger than the available space, consider clipping it with a
I/flutter ( 5019): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
I/flutter ( 5019): like a ListView.
I/flutter ( 5019): The specific RenderFlex in question is: RenderFlex#70842 relayoutBoundary=up4 OVERFLOWING:
I/flutter ( 5019):   creator: Row ← ConstrainedBox ← Container ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter ( 5019):     _InkFeatures-[GlobalKey#e7167 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter ( 5019):     PhysicalModel ← AnimatedPhysicalModel ← Material ← _TextSelectionToolbar ← CustomSingleChildLayout
I/flutter ( 5019):     ← ⋯
I/flutter ( 5019):   parentData: <none> (can use size)
I/flutter ( 5019):   constraints: BoxConstraints(0.0<=w<=360.0, h=44.0)
I/flutter ( 5019):   size: Size(360.0, 44.0)
I/flutter ( 5019):   direction: horizontal
I/flutter ( 5019):   mainAxisAlignment: start
I/flutter ( 5019):   mainAxisSize: min
I/flutter ( 5019):   crossAxisAlignment: center
I/flutter ( 5019):   textDirection: ltr
I/flutter ( 5019):   verticalDirection: down
I/flutter ( 5019): ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
I/flutter ( 5019): ════════════════════════════════════════════════════════════════════════════════════════════════════`
```

```
`[√] Flutter (Channel stable, v1.7.8+hotfix.2, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
    • Flutter version 1.7.8+hotfix.2 at C:\src\flutter
    • Framework revision 2e540931f7 (7 days ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\midos\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Java\jdk1.8.0_211\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.3
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7479.14

[√] VS Code, 64-bit edition (version 1.36.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • COR L29 • XTX7N18A31001552 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.`
```

### PR DESCRIPTION
**Pull request by justinmc**
## Description

If the selection menu buttons are too wide for their available space, they will cause an overflow error.  This PR implements the native iOS solution for this problem, which paginates overflowing items.

## Related Issues

Closes https://github.com/flutter/flutter/issues/35826
Android solution: https://github.com/flutter/flutter/pull/49391
Reopened from https://github.com/flutter/flutter/pull/52852 to fix weird versioning test failures.

## Tests

  * When all buttons fit on one page.
  * When the screen is narrow enough that only two buttons fit on each page.
  * When the screen is narrow enough that only one button fits on each page.
  * When the locale strings are so long that only one button fits on each page and must be ellided.

## Breaking Change

None.

### CODE REVIEW

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 1]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
 }
 
+// Renders the content of the selection menu and maintains the page state.
+class _CupertinoTextSelectionToolbarContent extends StatefulWidget {
+  const _CupertinoTextSelectionToolbarContent({
+    Key key,
+    @required this.children,
+    @required this.isArrowPointingDown,
+  }) : assert(children != null),
+       assert(children.length > 0), // ignore: prefer_is_empty
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/text_selection.dart:462]: Is this to get around the const?

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 2]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+  void _handlePreviousPage() {
+    _controller.reverse();
+    _controller.addListener(_listener);
+    setState(() {
+      _nextPage = _page - 1;
+    });
+  }
+
+  void _listener() {
+    if (_controller.value != 0.0) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/text_selection.dart:494]: If this only trigger when animation finishes, you can use addStatusListener

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 3]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+    _controller.addListener(_listener);
+    setState(() {
+      _nextPage = _page + 1;
+    });
+  }
+
+  void _handlePreviousPage() {
+    _controller.reverse();
+    _controller.addListener(_listener);
+    setState(() {
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/text_selection.dart:488]: do we need setstate here? it seems the the only _page is used in building the widget

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 4]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+
+class _CupertinoTextSelectionToolbarContentState extends State<_CupertinoTextSelectionToolbarContent> with TickerProviderStateMixin {
+  AnimationController _controller;
+  int _page = 0;
+  int _nextPage;
+
+  void _handleNextPage() {
+    _controller.reverse();
+    _controller.addListener(_listener);
+    setState(() {
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/text_selection.dart:480]: same here

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 5]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+    });
+    _controller.forward();
+    _controller.removeListener(_listener);
+  }
+
+  @override
+  void didUpdateWidget(_CupertinoTextSelectionToolbarContent oldWidget) {
+    // If the children are changing, the current page should be reset.
+    if (widget.children != oldWidget.children) {
+      _page = 0;
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/text_selection.dart:510]: I wonder if we need to worry about if the animation is on going

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 6]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+
+  @override
+  void initState() {
+    _controller = AnimationController(
+      value: 1.0,
+      vsync: this,
+      // This was eyeballed on a physical iOS device running iOS 13.
+      duration: const Duration(milliseconds: 150),
+    );
+    super.initState();
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/text_selection.dart:529]: nit: this should be at the start of the method.

**Review by chunhtai — COMMENTED** [review]
I only review the widget part of it. will review the renderobject later

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 7]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+      performResize();
+      return;
+    }
+
+    // Layout slotted children.
+    _backButton.layout(constraints.loosen(), parentUsesSize: true);
+    _nextButton.layout(constraints.loosen(), parentUsesSize: true);
+    _nextButtonDisabled.layout(constraints.loosen(), parentUsesSize: true);
+
+    double buttonPosition = 0.0;
```
Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/text_selection.dart:882]: When first reading through this code I was a little confused by the variable naming of buttonPosition and buttonsWidth. buttonsWidth only includes the width of the forward/back button, where-as buttonPosition is for all buttons.

Not super-sure how to make this better. Maybe call this one nextButtonPostition? And maybe the other paginationButtonWidth?

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 8]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+    double parentWidth = constraints.maxWidth; // The width of the whole widget.
```
Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/text_selection.dart:883]: maybe: toolbarWidth?

Comment (goderbauer) [reply packages/flutter/lib/src/cupertino/text_selection.dart:883]: Why does it start out as the max width possible instead of zero?

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 9]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+      return true;
+    }
+
+    return false;
+  }
+
+  @override
+  void attach(PipelineOwner owner) {
+    super.attach(owner);
+    visitChildren((RenderObject renderObjectChild) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/text_selection.dart:1049]: Will this not attach the list children twice? From the supercall and here again?

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 10]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+    });
+  }
+
+  @override
+  void detach() {
+    // Detach list children.
+    super.detach();
+
+    // Detach slot children.
+    visitChildren((RenderObject renderObjectChild) {
```
Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/text_selection.dart:1061]: Instead of iterating over all children, couldn't you just iterate over the slot children in childToSlot?

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 1 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:462]: Yes, `.isNotEmpty` isn't const.  I'll add a comment about it.

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:494]: That should be more performant, thanks for the tip 👍

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 5 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:510]: That's a great catch, it would be potentially possible for the animation to navigate to a non-existent page.  I'll fix this by resetting the animation here.

File: packages/flutter/test/material/text_field_test.dart [hunk 11]
```diff
@@ -16,9 +16,9 @@ import 'package:flutter/foundation.dart';
 import 'package:flutter/gestures.dart' show DragStartBehavior, PointerDeviceKind;
 
 import '../rendering/mock_canvas.dart';
+import '../text.dart' show findRenderEditable, globalize, textOffsetToPosition;
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart:19]: Yeah good call.  It's also likely that some tests in cupertino/ or widgets/ will end up needing this file anyway.

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 12]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+            onPressed: _handleNextPage,
+            padding: arrowPadding,
+            pressedOpacity: 0.7,
+            child: const Text('▶', style: _kToolbarButtonFontStyle),
+          ),
+          nextButtonDisabled: CupertinoButton(
+            borderRadius: null,
+            color: _kToolbarBackgroundColor,
+            minSize: _kToolbarHeight,
+            onPressed: () {},
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:567]: Ah, I did this because the default disabled background color didn't look right.  I can fix this with disabledColor though, so I'll remove this onPressed.

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 13]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+          nextButton: CupertinoButton(
+            borderRadius: null,
+            color: _kToolbarBackgroundColor,
+            minSize: _kToolbarHeight,
+            onPressed: _handleNextPage,
+            padding: arrowPadding,
+            pressedOpacity: 0.7,
+            child: const Text('▶', style: _kToolbarButtonFontStyle),
+          ),
+          nextButtonDisabled: CupertinoButton(
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:563]: From my experimentation, the only time it won't show a next button is if there is only one page.  Otherwise there is always a next button, and on the last page it's disabled.

Screen Shot 2020-04-10 at 11 06 03 AM

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 14]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+  @override
+  void dispose() {
+    _controller.dispose();
+    super.dispose();
+  }
+
+  @override
+  void initState() {
+    _controller = AnimationController(
+      value: 1.0,
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:524]: Initially the entire toolbar fades in.  This controller handles the fading of the buttons within the toolbar.  During page changes, the toolbar background stays visible, but the buttons fade in/out inside of it. There is another existing widget that handles fading the entire toolbar when it shows/hides.

I'll add a comment to the declaration of _controller about what it does.

I also noticed there's a slight existing bug with transitioning between states that's somewhat related to this.  I opened a new issue: https://github.com/flutter/flutter/issues/54470

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 15]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+
+  @override
+  Widget build(BuildContext context) {
+    final EdgeInsets arrowPadding = widget.isArrowPointingDown
+      ? EdgeInsets.only(bottom: _kToolbarArrowSize.height)
+      : EdgeInsets.only(top: _kToolbarArrowSize.height);
+
+    return DecoratedBox(
+      decoration: const BoxDecoration(color: _kToolbarDividerColor),
+      child: FadeTransition(
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:540]: I played around with AnimatedSwitcher when I was doing this for Android, but I think I went straight for FadeTransition here.  Looks like AnimatedSwitcher probably would work though.

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 16]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+  _CupertinoTextSelectionToolbarItemsRenderBox createRenderObject(BuildContext context) {
+    return _CupertinoTextSelectionToolbarItemsRenderBox(
+      dividerWidth: dividerWidth,
+      page: page,
+    );
+  }
+
+  @override
+  void updateRenderObject(BuildContext context, _CupertinoTextSelectionToolbarItemsRenderBox renderObject) {
+    renderObject.page = page;
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:617]: Good catch!

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 17]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+
+      double buttonsWidth = 0.0;
+      if (currentPage == 0) {
+        // If this is the last child, it's ok to fit without a forward button.
+        buttonsWidth = i == childCount - 1 ? 0.0 : _nextButton.size.width;
+      } else {
+        buttonsWidth = _backButton.size.width + _nextButton.size.width;
+      }
+
+      // The width of the menu is set by the first page.
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:906]: My conclusion after playing around with native iOS is that it tries to keep the width of the menu constant:

width

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 18]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+    }
+    if (slot is IndexedSlot) {
+      assert(renderObject.debugValidateChild(child));
+      renderObject.insert(child as RenderBox, after: slot?.value?.renderObject as RenderBox);
+      return;
+    }
+    assert(false, 'slot must be _CupertinoTextSelectionToolbarItemsSlot or IndexedSlot');
+  }
+
+  // This is not reachable for slotted children.
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:676]: Right, I'll rephrase this.

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 19]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+
+  @override
+  void removeChildRenderObject(RenderObject child) {
+    // Check if the child is in a slot.
+    if (renderObject.childToSlot.containsKey(child)) {
+      assert(child is RenderBox);
+      assert(renderObject.childToSlot.keys.contains(child));
+      _updateRenderObject(null, renderObject.childToSlot[child]);
+      assert(!renderObject.childToSlot.keys.contains(child));
+      assert(!renderObject.slotToChild.keys.contains(slot));
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:695]: Yes, good catch!  That could be causing a real tricky bug somewhere...

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 20]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+      visitor(child);
+    });
+    // Visit list children.
+    _children
+        .where((Element child) => !_forgottenChildren.contains(child) && _shouldPaint(child))
+        .forEach(visitor);
+  }
+
+  // Update slotted child.
+  void _updateChild(Widget widget, _CupertinoTextSelectionToolbarItemsSlot slot) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:775]: Yes, I'll deduplicate that.

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 21]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+  void updateRenderObject(BuildContext context, _CupertinoTextSelectionToolbarItemsRenderBox renderObject) {
+    renderObject.page = page;
+  }
+
+  @override
+  _CupertinoTextSelectionToolbarItemsElement createElement() => _CupertinoTextSelectionToolbarItemsElement(this);
+}
+
+// The custom RenderObjectElement that helps paginate the menu items.
+class _CupertinoTextSelectionToolbarItemsElement extends RenderObjectElement {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:625]: I tried extending MultiChildRenderObjectElement when I wrote this and the reason I decided to do it this way instead was that I sometimes needed to call the super method on RenderObjectElement without going through MultiChildRenderObjectElement.

An example is `forgetChild`.  For a child that exists in `slotToChild`, I need to remove the child, then I need to call RenderObjectElement's forgetChild without calling MultiChildRenderObjectElement's forgetChild.  Let me know if I'm wrong, but I thought that was a showstopper since I can't do `super.super.forgetChild`.

Maybe a mixin will work though!  I'll try that right now.

[the remark this answers is not in the document]
Comment (chunhtai) [reply packages/flutter/lib/src/cupertino/text_selection.dart:625]: What is wrong if  we call MultiChildRenderObjectElement's forgetchild?

[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:625]: I experimented a bit and I think it would work if I did something like this.  Let me know what you think.

```dart
mixin ContainerRenderObjectMixin on RenderObjectElement {
  List<Element> _children;
  final Set<Element> _forgottenChildren = HashSet<Element>();

  ...

  // Rather than overriding forgetChild, I give it a new name.
  void forgetListChild(Element child) {
    assert(_children.contains(child));
    assert(!_forgottenChildren.contains(child));
    _forgottenChildren.add(child);
    super.forgetChild(child);
  }

  ...

}

// Then I use the mixin here in my code.
class _CupertinoTextSelectionToolbarItemsElement extends RenderObjectElement with ContainerRenderObjectMixin {

  ...

  @override
  void forgetChild(Element child) {
    // Handle children in slots like normal.
    if (childToSlot.containsKey(child)) {
      final _CupertinoTextSelectionToolbarItemsSlot slot = childToSlot[child];
      childToSlot.remove(child);
      slotToChild.remove(slot);
      // Super calls to RenderObjectElement.forgetChild as desired.
      super.forgetChild(child);

    // Handle list children with the mixin, which can also call to RenderObjectElement.forgetChild.
    } else {
      forgetListChild(child);
    }
  }

  ...

}

// And we can also use the mixin in MultiChildRenderObjectElement to deduplicate code.
class MultiChildRenderObjectElement extends RenderObjectElement with ContainerRenderObjectMixin {

  ...

  @override
  void forgetChild(Element child) {
    forgetListChild(child);
  }

  ...

}
```

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 22]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+    _backButton.layout(constraints.loosen(), parentUsesSize: true);
+    _nextButton.layout(constraints.loosen(), parentUsesSize: true);
+    _nextButtonDisabled.layout(constraints.loosen(), parentUsesSize: true);
+
+    double buttonPosition = 0.0;
+    double parentWidth = constraints.maxWidth; // The width of the whole widget.
+    double firstPageWidth;
+    int currentPage = 0;
+    int i = -1;
+    visitChildren((RenderObject renderObjectChild) {
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:887]: No, you're right.  I tried making this optimization earlier but got console errors about children that weren't laid out.  I just had to implement visitChildrenForSemantics and it fixed it though.

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 23]
```diff
@@ -446,5 +452,675 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+      i++;
+      final RenderBox child = renderObjectChild as RenderBox;
+      final ToolbarItemsParentData childParentData = child.parentData as ToolbarItemsParentData;
+      childParentData.shouldPaint = false;
```
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:891]: Now it is!  Since I made the optimization above where I don't layout all children, line 931 doesn't get run on all children.

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 7 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:882]: I struggled with coming up with good names when writing this.  I'm going to go with currentButtonPosition since nextButtonPosition could be interpreted as the position of the right arrow.  paginationButtonsWidth sounds good.

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 8 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:883]: I think I was using it as a constraint earlier and then I changed my code, good call.

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 9 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:1049]: Yes, good catch.

**Comment by justinmc** [comment]
@chunhtai @goderbauer Thank you guys!  It's ready for re-review when you have time.

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 24]
```diff
@@ -446,5 +452,685 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+  }
+
+  @override
+  void dispose() {
+    _controller.dispose();
+    super.dispose();
+  }
+
+  @override
+  void initState() {
```
Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/text_selection.dart:522]: nit: order-wise it would be nice to place initState before dispose and didUpdateWidget.

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 25]
```diff
@@ -446,5 +452,685 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+    });
+    _controller.forward();
+    _controller.removeStatusListener(_statusListener);
+  }
+
+  @override
+  void didUpdateWidget(_CupertinoTextSelectionToolbarContent oldWidget) {
+    // If the children are changing, the current page should be reset.
+    if (widget.children != oldWidget.children) {
+      _page = 0;
```
Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/text_selection.dart:508]: Maybe also reset _nextPage to null? (I don't think this is a visual bug, but it may be strange during debugging if this is set to something that's no longer valid.)

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 13 above)
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/cupertino/text_selection.dart:563]: Interesting. I never noticed that. Thanks for the explanation.

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 26]
```diff
@@ -446,5 +452,685 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+      return;
+    }
+
+    // Layout slotted children.
+    _backButton.layout(constraints.loosen(), parentUsesSize: true);
+    _nextButton.layout(constraints.loosen(), parentUsesSize: true);
+    _nextButtonDisabled.layout(constraints.loosen(), parentUsesSize: true);
+
+    final double subsequentPageButtonsWidth =
+      _backButton.size.width + _nextButton.size.width;
```
Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/text_selection.dart:873]: nit: either leave this on the previous line or indent by 4

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 17 above)
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/cupertino/text_selection.dart:900]: Interesting observation. Thanks for the gif.

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 27]
```diff
@@ -446,5 +452,685 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
+      if (currentPage == page) {
+        toolbarWidth = currentButtonPosition;
+      }
+    });
+
+    // It shouldn't be possible to navigate beyond the last page.
+    assert(page <= currentPage);
+
+    // Position page nav buttons.
+    final ToolbarItemsParentData nextButtonParentData =
```
Comment (goderbauer) [inline packages/flutter/lib/src/cupertino/text_selection.dart:941]: nit: these three vars could all be declared inside the `if (currentPage > 0) {`, no?

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/cupertino/text_selection.dart [hunk 28]
```diff
@@ -347,12 +353,12 @@ class _CupertinoTextSelectionControls extends TextSelectionControls {
...
 
-      if (items.isNotEmpty) {
-        items.add(onePhysicalPixelVerticalDivider);
-      }
-
       items.add(CupertinoButton(
-        child: Text(text, style: _kToolbarButtonFontStyle),
+        child: Text(
+          text,
+          overflow: TextOverflow.ellipsis,
```
Comment (chunhtai) [inline packages/flutter/lib/src/cupertino/text_selection.dart:359]: Just a FYI, this currently only work with word boundary. If for some reason the space is not enough, copy -> ... Paste -> ...    select all -> select ...

**Review by chunhtai — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 21 above)
[the remark this answers is not in the document]
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:628]: @chunhtai Sorry, I missed your question because I didn't refresh.  Calling MultiChildRenderObjectElement's forgetChild with a slotted child will add it to _forgottenChildren, which is only used for list children.

I did work around this in the mixin I pasted above, though.

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 27 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:941]: Good catch 👍

File: packages/flutter/lib/src/cupertino/text_selection.dart (hunk 28 above)
Comment (justinmc) [reply packages/flutter/lib/src/cupertino/text_selection.dart:359]: I think somehow it's working ok, see this screenshot if I add a bunch of A's to Paste.  Is that what you mean?

Screen Shot 2020-04-14 at 8 58 14 AM

Comment (chunhtai) [reply packages/flutter/lib/src/cupertino/text_selection.dart:359]: oh nvm it seems you are right.
