### PR TITLE
Fix cursor position when Unicode Zs category is entered in TextField

### LINKED ISSUE #149099: Cursor does not move on entering full-width space in TextField (3.22.0)
### Steps to reproduce

1. Add TextField
2. Enter full-width space using the keyboard

### Expected results

that the cursor moves

### Actual results

The cursor does not move when entering full-width spaces on iOS as shown in the attached video.
It worked in 3.19.6.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('TextField Example'),
        ),
        body: TextField(),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/103257145/b55d3ece-d3c7-4975-8422-0ff3d12ddff1

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studioのコピー2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • xxxxのiPhone (mobile)            • 00008120-000675C21E33401E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 125.0.6422.77

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by koji-1009**
Changed the cursor position to be the same as before flutter 3.22.0 when 17 character codes in the Unicode Zs category are entered into a TextField.

Extend the support for https://github.com/flutter/flutter/pull/149698. As a result, https://github.com/flutter/flutter/issues/149099 is resolved.

The code for the Unicode-Zs category is based on the following page.
https://www.compart.com/en/unicode/category/Zs

Fixes https://github.com/flutter/flutter/issues/149099

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 1]
```diff
@@ -359,6 +359,20 @@ class _TextLayout {
...
+      0x2003 ||     // em space
+      0x2004 ||     // three-per-em space
+      0x2005 ||     // four-per-em space
+      0x2006 ||     // six-per-em space
+      0x2007 ||     // figure space
+      0x2008 ||     // punctuation space
+      0x2009 ||     // thin space
+      0x200A ||     // hair space
+      0x202F ||     // narrow no-break space(NNBSP)
+      0x205F ||     // medium mathematical space(MMSP)
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/painting/text_painter.dart:375]: FTR, this is how SkParagraph determines whether if a cluster is a space (or break). 
https://github.com/google/skia/blob/8b2f189cfa59d0c69b700bbe8587f52f5bd2ad5c/modules/skparagraph/src/ParagraphImpl.cpp#L357-L381

With the ICU backend, `::kPartOfWhiteSpaceBreak` is
https://github.com/unicode-org/icu/blob/23d9628f88a2d0127c564ad98297061c36d3ce77/icu4c/source/common/unicode/uchar.h#L3388-L3425

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/painting/text_painter.dart:375]: Also you could use regex for matching unicode properties, e.g.: `RegExp(r'\p{Space_Separator}', unicode: true)`

File: packages/flutter/test/painting/text_painter_test.dart [hunk 2]
```diff
@@ -145,17 +145,73 @@ void main() {
       caretOffset = painter.getOffsetForCaret(ui.TextPosition(offset: text.length), ui.Rect.zero);
       expect(caretOffset.dx, painter.width);
 
-      // Test with trailing full-width space
-      const String textWithFullWidthSpace = 'A\u{3000}';
-      checkCaretOffsetsLtr(textWithFullWidthSpace);
-      painter.text = const TextSpan(text: textWithFullWidthSpace);
+      text = 'A';
```
Comment (LongCatIsLooong) [inline packages/flutter/test/painting/text_painter_test.dart:148]: These 3 lines are no longer needed it seems?

Comment (LongCatIsLooong) [reply packages/flutter/test/painting/text_painter_test.dart:148]: Ah I see you needed `A`'s horizontal advance. It's `14.0`.

File: packages/flutter/test/painting/text_painter_test.dart [hunk 3]
```diff
@@ -145,17 +145,73 @@ void main() {
...
+      painter.text = TextSpan(text: text);
       painter.layout();
-      caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 0), ui.Rect.zero);
-      expect(caretOffset.dx, 0);
-      caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 1), ui.Rect.zero);
-      expect(caretOffset.dx, painter.width / 2);
-      caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: textWithFullWidthSpace.length), ui.Rect.zero);
-      expect(caretOffset.dx, painter.width);
+      final double textAWidth = painter.width;
+      void checkUnicodeZsCategory(String charset) {
```
Comment (LongCatIsLooong) [inline packages/flutter/test/painting/text_painter_test.dart:152]: nit: `charset` -> `character`

File: packages/flutter/test/painting/text_painter_test.dart [hunk 4]
```diff
@@ -145,17 +145,73 @@ void main() {
...
+        text = 'A$charset';
+        checkCaretOffsetsLtr(text);
+        painter.text = TextSpan(text: text);
+        painter.layout();
+        caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 0), ui.Rect.zero);
```
Comment (LongCatIsLooong) [inline packages/flutter/test/painting/text_painter_test.dart:157]: Can you also verify that each input character is indeed a space, by laying out the painter at `maxWidth = 14`, and checks if there's only one line, and the line width is exactly 14? If one of the characters is not considered a trailing space then there will be 2 lines (or lineWidth would be greater than 14 if the character is not a line breaker).

**Review by LongCatIsLooong — COMMENTED** [review]
It's a bit unfortunate that we have to maintain this to match SkParagraph's definition of trailing spaces. The less hacky solution is exposing the line width (including trailing spaces) from SkParagraph, but that's probably going to take more effort.

File: packages/flutter/test/painting/text_painter_test.dart (hunk 2 above)
Comment (koji-1009) [reply packages/flutter/test/painting/text_painter_test.dart:148]: Yes. I checked the value at runtime and found it to be 14.0, but since it depends on the style of the painter, I calculated it.

File: packages/flutter/test/painting/text_painter_test.dart (hunk 3 above)
Comment (koji-1009) [reply packages/flutter/test/painting/text_painter_test.dart]: Thanks, I fixed at [1e1d000](https://github.com/flutter/flutter/pull/152215/commits/1e1d000afa3c909b37285b130bee6d35de64fec1).

File: packages/flutter/test/painting/text_painter_test.dart (hunk 4 above)
Comment (koji-1009) [reply packages/flutter/test/painting/text_painter_test.dart:158]: I added test case at [9c37308](https://github.com/flutter/flutter/pull/152215/commits/9c373083b9a0c1979e3992348224b80c79308571).

File: packages/flutter/test/painting/text_painter_test.dart [hunk 5]
```diff
@@ -145,17 +145,79 @@ void main() {
...
+        expect(caretOffset.dx, 0);
+        caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 1), ui.Rect.zero);
+        expect(caretOffset.dx, textAWidth);
+        caretOffset = painter.getOffsetForCaret(ui.TextPosition(offset: text.length), ui.Rect.zero);
+        expect(caretOffset.dx, painter.width);
+
+        painter.layout(maxWidth: textAWidth);
+        expect(painter.width, textAWidth);
```
Comment (LongCatIsLooong) [inline packages/flutter/test/painting/text_painter_test.dart:166]: `painter.width` is not the line width. I think this should be:
```dart
final lines = painter.computeLineMetrics();
expect(lines.length, 1);
expect(lines.width, 14.0);
```

Comment (koji-1009) [reply packages/flutter/test/painting/text_painter_test.dart]: I added test case at [86adcc1](https://github.com/flutter/flutter/pull/152215/commits/86adcc1f8e9652df3f7a054c1258529f5d6fd15e).

File: packages/flutter/test/painting/text_painter_test.dart [hunk 6]
```diff
@@ -145,17 +145,77 @@ void main() {
...
+        caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 0), ui.Rect.zero);
+        expect(caretOffset.dx, 0.0, reason: reason);
+        caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 1), ui.Rect.zero);
+        expect(caretOffset.dx, 14.0, reason: reason);
+        caretOffset = painter.getOffsetForCaret(ui.TextPosition(offset: text.length), ui.Rect.zero);
+        expect(caretOffset.dx, painter.width, reason: reason);
+
+        painter.layout(maxWidth: 14.0);
+        final List<ui.LineMetrics> lines = painter.computeLineMetrics();
+        // If charactor is non-breaking space, the height should be 2 lines. Otherwise, it should be 1 line.
```
Comment (LongCatIsLooong) [inline packages/flutter/test/painting/text_painter_test.dart:164]: All of these **should be** 1-line. If it is not then the character is not considered a space (during line-breaking) by SkParagraph, so the character must be excluded from the list.

Comment (LongCatIsLooong) [reply packages/flutter/test/painting/text_painter_test.dart:164]: nit: "character"

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 7]
```diff
@@ -356,11 +356,10 @@ class _TextLayout {
     // Luckily they have the same bidi embedding level as the paragraph as per
     // https://unicode.org/reports/tr9/#L1, so we can anchor the caret to the
     // last logical trailing space.
-    final bool hasTrailingSpaces = switch (rawString.codeUnitAt(rawString.length - 1)) {
-      0x9 ||        // horizontal tab
-      0x3000 ||     // ideographic space
-      0x20 => true, // space
-      _ => false,
+    final String lastCharactor = rawString[rawString.length - 1];
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/painting/text_painter.dart:359]: This is still checking the last code unit. What's the difference between this and the expression before the change?

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 8]
```diff
@@ -356,11 +356,10 @@ class _TextLayout {
...
+    final bool hasTrailingSpaces = switch (lastCharactor.codeUnitAt(0)) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/painting/text_painter.dart:360]: There's little point in using a switch expression now I think? This could just be an `||`.

**Review by LongCatIsLooong — COMMENTED** [review]
Some of these space characters are actually not considered "space" by SkParagraph (see [this comment](https://github.com/flutter/flutter/pull/152215#discussion_r1690222601))

I think you may want to exclude the characters that are not included in `u_isWhitespace` (or the test will fail), and also exclude the characters that would force a line break (so basically you don't have to include `Zl` and `Zp`).

If the web test keeps failing (looks like it will) and other tests are passing then I think we should add `, skip: isBrowser && !isSkiaWeb` to the test.

File: packages/flutter/lib/src/painting/text_painter.dart (hunk 7 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/painting/text_painter.dart:359]: Also I'm curious how the regexp fares with surrogate pairs, could you also test a surrogate pair ("\uD801\uDC37" for example)?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/painting/text_painter.dart:359]: Ah I tested locally and it didn't throw. So up to you if you want to skip adding that test.

**Comment by LongCatIsLooong** [comment]
re:
> If the web test keeps failing (looks like it will) and other tests are passing then I think we should add , skip: isBrowser && !isSkiaWeb to the test.

That is because the HTML renderer (`isBrowser && !isSkiaWeb`) uses a different text layout library, while everything else uses `SkParagraph` under the hood.

**Comment by koji-1009** [comment]
@LongCatIsLooong 
Thanks for your patient review. Let me ask you one question.

> All of these should be 1-line. If it is not then the character is not considered a space (during line-breaking) by SkParagraph, so the character must be excluded from the list.

Is there a problem with the current implementation where `computeLineMetrics` returns 2 lines when `u{00A0}` is set? Running the following test code against the `flutter:master` branch will fail.

```dart
void verifyCharacterIsConsideredTrailingSpaceBySkParagraphAndTextPainter(String character) {
  final String reason = 'character: ${character.codeUnitAt(0).toRadixString(16)}';

  text = 'A$character';
  checkCaretOffsetsLtr(text);
  painter.text = TextSpan(text: text);
  painter.layout();
  caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 0), ui.Rect.zero);
  expect(caretOffset.dx, 0.0, reason: reason);
  caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 1), ui.Rect.zero);
  expect(caretOffset.dx, 14.0, reason: reason);
  caretOffset = painter.getOffsetForCaret(ui.TextPosition(offset: text.length), ui.Rect.zero);
  expect(caretOffset.dx, painter.width, reason: reason);

  painter.layout(maxWidth: 14.0);
  final List<ui.LineMetrics> lines = painter.computeLineMetrics();
  expect(lines.length, 1, reason: reason);
  expect(lines.first.width, 14.0, reason: reason);
}

// Test with trailing space
verifyCharacterIsConsideredTrailingSpaceBySkParagraphAndTextPainter('\u{0020}');

// Test with trailing no-break space
verifyCharacterIsConsideredTrailingSpaceBySkParagraphAndTextPainter('\u{00A0}');

// Test with trailing full-width space
verifyCharacterIsConsideredTrailingSpaceBySkParagraphAndTextPainter('\u{3000}');
```

**Comment by LongCatIsLooong** [comment]
> @LongCatIsLooong Thanks for your patient review. Let me ask you one question.
> 
> > All of these should be 1-line. If it is not then the character is not considered a space (during line-breaking) by SkParagraph, so the character must be excluded from the list.
> 
> Is there a problem with the current implementation where `computeLineMetrics` returns 2 lines when `u{00A0}` is set? Running the following test code against the `flutter:master` branch will fail.
> 
> ```dart
> void verifyCharacterIsConsideredTrailingSpaceBySkParagraphAndTextPainter(String character) {
>   final String reason = 'character: ${character.codeUnitAt(0).toRadixString(16)}';
> 
>   text = 'A$character';
>   checkCaretOffsetsLtr(text);
>   painter.text = TextSpan(text: text);
>   painter.layout();
>   caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 0), ui.Rect.zero);
>   expect(caretOffset.dx, 0.0, reason: reason);
>   caretOffset = painter.getOffsetForCaret(const ui.TextPosition(offset: 1), ui.Rect.zero);
>   expect(caretOffset.dx, 14.0, reason: reason);
>   caretOffset = painter.getOffsetForCaret(ui.TextPosition(offset: text.length), ui.Rect.zero);
>   expect(caretOffset.dx, painter.width, reason: reason);
> 
>   painter.layout(maxWidth: 14.0);
>   final List<ui.LineMetrics> lines = painter.computeLineMetrics();
>   expect(lines.length, 1, reason: reason);
>   expect(lines.first.width, 14.0, reason: reason);
> }
> 
> // Test with trailing space
> verifyCharacterIsConsideredTrailingSpaceBySkParagraphAndTextPainter('\u{0020}');
> 
> // Test with trailing no-break space
> verifyCharacterIsConsideredTrailingSpaceBySkParagraphAndTextPainter('\u{00A0}');
> 
> // Test with trailing full-width space
> verifyCharacterIsConsideredTrailingSpaceBySkParagraphAndTextPainter('\u{3000}');
> ```

I think that's because `U+00A0` is not considered a whitespace character by skparagraph. see https://github.com/flutter/flutter/pull/152215#discussion_r1690222601

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 9]
```diff
@@ -356,12 +356,10 @@ class _TextLayout {
     // Luckily they have the same bidi embedding level as the paragraph as per
     // https://unicode.org/reports/tr9/#L1, so we can anchor the caret to the
     // last logical trailing space.
-    final bool hasTrailingSpaces = switch (rawString.codeUnitAt(rawString.length - 1)) {
-      0x9 ||        // horizontal tab
-      0x3000 ||     // ideographic space
-      0x20 => true, // space
-      _ => false,
-    };
+    final bool hasTrailingSpaces = RegExp(
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/painting/text_painter.dart:359]: could you link https://github.com/unicode-org/icu/blob/23d9628f88a2d0127c564ad98297061c36d3ce77/icu4c/source/common/unicode/uchar.h#L3388-L3425 in the comment for provenance?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/painting/text_painter.dart:359]: I believe this still includes every codepoint from `Zs`? Also I think we only care about the last code unit.

 Maybe:

```dart
final String lastCodeUnit = rawString[rawString.length - 1];
final bool hasTrailingSpaces = switch(lastCodeUnit.codeUnitAt(0)) { 
   0x0009 => true,
   0x00A0 || 0x2007 || 0x202F => false,
   _ => RegExp(r'p{Space_Separator}', unicode: true).hasMatch(lastCodeUnit),
};
```

Comment (koji-1009) [reply packages/flutter/lib/src/painting/text_painter.dart]: I updated code and comments at [953ec78](https://github.com/flutter/flutter/pull/152215/commits/953ec780ee50c62fd8b2081b1538ba23abb1a8d0).

**Review by LongCatIsLooong — APPROVED** [review]
LGTM, thank you for contributing!

**Comment by koji-1009** [comment]
Thank you!

File: packages/flutter/test/painting/text_painter_test.dart [hunk 10]
```diff
@@ -145,20 +145,77 @@ void main() {
...
+        caretOffset = painter.getOffsetForCaret(ui.TextPosition(offset: text.length), ui.Rect.zero);
+        expect(caretOffset.dx, painter.width, reason: reason);
+
+        painter.layout(maxWidth: 14.0);
+        final List<ui.LineMetrics> lines = painter.computeLineMetrics();
+        expect(lines.length, 1, reason: reason);
+        expect(lines.first.width, 14.0, reason: reason);
+      }
+
+      // Test with trailing space
```
Comment (justinmc) [inline packages/flutter/test/painting/text_painter_test.dart:175]: Nit: I think there should be a period at the end of each of these comments here and below.

File: packages/flutter/test/painting/text_painter_test.dart [hunk 11]
```diff
@@ -145,20 +145,77 @@ void main() {
       caretOffset = painter.getOffsetForCaret(ui.TextPosition(offset: text.length), ui.Rect.zero);
       expect(caretOffset.dx, painter.width);
 
+      /// Verify the handling of spaces by SkParagraph and TextPainter
```
Comment (justinmc) [inline packages/flutter/test/painting/text_painter_test.dart:148]: Period at the end of this sentence.

**Review by justinmc — APPROVED** [review]
LGTM with nits :+1: 

Thank you for helping us get this right!

File: packages/flutter/lib/src/painting/text_painter.dart [hunk 12]
```diff
@@ -356,11 +356,15 @@ class _TextLayout {
...
-      _ => false,
+    // Whitespace character definitions refer to Java/ICU, not Unicode-Zs.
+    // https://github.com/unicode-org/icu/blob/23d9628f88a2d0127c564ad98297061c36d3ce77/icu4c/source/common/unicode/uchar.h#L3388-L3425
+    final String lastCodeUnit = rawString[rawString.length - 1];
+    final bool hasTrailingSpaces = switch (lastCodeUnit.codeUnitAt(0)) {
+      0x0009 => true,   // horizontal tab
+      0x00A0 ||         // no-break space
+      0x2007 ||         // figure space
+      0x202F => false,  // narrow no-break space
+      _ => RegExp(r'\p{Space_Separator}', unicode: true).hasMatch(lastCodeUnit),
```
Comment (kevmoo) [inline packages/flutter/lib/src/painting/text_painter.dart:367]: Aren't we going to allocate a NEW `RegExp` every time through this function (in the fall-through case).

Not sure if that's desirable...
