### PR TITLE
Fix Text selection handler disappear when dragged to new words

### LINKED ISSUE #84849: Input connection reinitiated when handles are dragged
## Steps to Reproduce

1. Write something down in textfield
2. Drag input handle
3. Observe it lags, handles disappear and in console there are logs that input connection was reinitiated

Reproduced on Android 9 Redmi Note 5 and Android 11 emulator

<details>
  <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final appTitle = 'Form Styling Demo';
    return MaterialApp(
      title: appTitle,
      home: Scaffold(
        appBar: AppBar(
          title: Text(appTitle),
        ),
        body: MyCustomForm(),
      ),
    );
  }
}

class MyCustomForm extends StatefulWidget {
  @override
  MyCustomFormState createState() {
    return MyCustomFormState();
  }
}

class MyCustomFormState extends State<MyCustomForm> {
  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Padding(
          padding: EdgeInsets.symmetric(horizontal: 8, vertical: 16),
          child: TextField(
            decoration: InputDecoration(
              border: OutlineInputBorder(),
              hintText: 'Enter a search term',
            ),
          ),
        ),
        Padding(
          padding: EdgeInsets.symmetric(horizontal: 8, vertical: 16),
          child: TextFormField(
            decoration: InputDecoration(
              border: UnderlineInputBorder(),
              labelText: 'Enter your username',
            ),
          ),
        ),
      ],
    );
  }
}
```
</details>

<details>
  <summary>Logs</summary>

```
I/TextInputPlugin( 1609): Composing region changed by the framework. Restarting the input method.
W/IInputConnectionWrapper( 1609): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 1609): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 1609): getTextAfterCursor on inactive InputConnection
```

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.375, on Microsoft Windows [Version 10.0.19041.1052], locale ru-RU)
    • Flutter version 2.3.0-17.0.pre.375 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • Framework revision 57a565c706 (2 days ago), 2021-06-15 18:44:02 -0700
    • Engine revision e0011fa561
    • Dart version 2.14.0 (build 2.14.0-211.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (5 available)
    • Redmi Note 5 (mobile)   • 40c9f14       • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1052]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 91.0.4472.106
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 91.0.864.41

! Doctor found issues in 1 category.
```

</details>

### LINKED ISSUE #108673: Text selection handler disappear when dragged to new words
## Steps to Reproduce

This only happen when user has autocorrect/suggestion/any kind of text correction enabled on keyboard.
It doesn't reproduce for any TextField that doesn't use any text correction feature, like for password or TextField with keyboardType TextInputType.visiblePassword.
It only affect Android afaik, can't reproduce this on iOS

1. Run example code
2. Tap on textfield twice to show the handler
3. Drag handler across to start/end
4. Handler stop and disappear abruptly

**Expected results:** Handler should not stop/disappear

**Actual results:** Handler stop and disapper

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        platform: TargetPlatform.android,
      ),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  late final TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController(text: 'Hello World');
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: Center(
            child: TextField(
              controller: _controller,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-ID)
    • Flutter version 3.0.5 at /Users/s21/Documents/GitHub/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (2 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/s21/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (4 available)
    • SM G991B (mobile)        • RRCR2003SSA               • android-arm64  • Android 12 (API 31)
    • Andree’s iPhone (mobile) • 00008030-000314393443802E • ios            • iOS 15.6 19G71
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 103.0.5060.134
    ! Error: Andree’s iPhone is busy: Fetching debug symbols for Andree’s iPhone. Xcode will continue when Andree’s iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

https://user-images.githubusercontent.com/1574722/181920531-a3295129-a115-4167-b450-f930301ffc0e.mp4

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes #108673
Fixes #84849 

## Issue 1 - Tap the word the handler appear randomly
1, Tap on the middle of 'Hello'
2, Local value update to
```dart
TextEditingValue(text: ┤Hello World├, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.upstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
```
3, Send the new local value to remote, and then, the auto correction will update the composing back to framework
```dart
TextEditingValue(text: ┤Hello World├, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 0, end: 2))
```
But the affinity will mutate randomly. I'm not sure if this is a problem with the engine, but I understand that in this scenario, affinity is meaningless.

If the affinity was mutate, the handle will be hide by `_TextFieldState._handleSelectionChanged` because the cause is keyboard.

## Issue 2 - The handler can not drag to a new word

https://github.com/flutter/flutter/blob/2d771d4966b6a8562bd026807fccbbddecf42e2e/packages/flutter/lib/src/widgets/editable_text.dart#L2148-L2149
This is because we remove the handler overlay during drag because the engine update the composing during drag.

I found that we can remove the line, the handler's visibility will be updated by `_TextFieldState._handleSelectionChanged` CC @LongCatIsLooong

### CODE REVIEW

File: packages/flutter/lib/src/material/text_field.dart [hunk 1]
```diff
@@ -1067,9 +1067,23 @@ class _TextFieldState extends State<TextField> with RestorationMixin implements
...
+    bool onlyAffinityChanged = false;
+    if (_lastSelection != null) {
+      onlyAffinityChanged = _isOnlyAffinityChanged(_lastSelection!, selection);
+     }
+    _lastSelection = selection;
+
     final bool willShowSelectionHandles = _shouldShowSelectionHandles(cause);
-    if (willShowSelectionHandles != _showSelectionHandles) {
+    if (willShowSelectionHandles != _showSelectionHandles &&
+        !(onlyAffinityChanged && cause == SelectionChangedCause.keyboard)) {
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/text_field.dart:1086]: I know this a little hack.
 If we can figure out why the engine change the affinity maybe we have a better solution.
CC @LongCatIsLooong

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/material/text_field.dart:1086]: The engine doesn't know/care about text affinity I believe. It always sets it to downstream.

Comment (xu-baolin) [reply packages/flutter/lib/src/material/text_field.dart]: I have correct the value when receive the remote value. WDYT?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -2145,7 +2150,6 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
       // `selection` is the only change.
       _handleSelectionChanged(value.selection, (_textInputConnection?.scribbleInProgress ?? false) ? SelectionChangedCause.scribble : SelectionChangedCause.keyboard);
     } else {
-      hideToolbar();
```
Comment (xu-baolin) [inline packages/flutter/lib/src/widgets/editable_text.dart:2148]: Could you double check deleting this is safety? @LongCatIsLooong THX : )

**Comment by xu-baolin** [comment]
@LongCatIsLooong @justinmc Hi, guys, I think this is ready for review :)

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -2127,6 +2127,11 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
       return;
     }
 
+    if (value.selection.isCollapsed && value.selection.affinity != _value.selection.affinity) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:2130]: Do you still want to revert the affinity change if the user actually typed something?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2148]: In UIKit/Android apps, the text edit menu should go away once the user starts typing. Would this change that behavior?

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:2148]: Will add a test to cover this.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:2130]: As you point out that the input server never know the actually affinity and can not change the affinity by key board.
Currently we can only change the affinity by tap the text string and change the selection.
Additional, the affinity is only valid when line breaks cause by render wrapping, not explicit newline characters.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2139]: Ah sorry I misspoke, the engine doesn't care but the framework does (for rendering the caret at the right place).

As far as I can tell on iOS/Android when the user types using a virtual/hardware keyboard the affinity is always set to `TextAffinity.downstream`. `TextAffinity.upstream` is only used when the selection is change by certain gestures when the caret position is located at a soft-wrap line boundary, or bidi boundary. For example when the text field needs to show 
```
aa|
bb
```
instead of 
```
aa
|bb
```

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:2139]: Absolutely correct, so we can override the affinity from engine, right?
Otherwise, the only affinity change will trigger selection change and dismiss the handler by mistake.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2139]: Say the line can only accommodate 2 characters, and the text editing state was initially 
`(text: 'a', textSelection.collapsed(1, affinity: upstream))`, when the user types another `a` the affinity should be changed to downstream?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2157]: Ah `_handleSelectionChanged` is called in `_formatAndSave` too, that seems to be a messy callpath. Do you mind adding a comment to explain why we're not hiding the handles here (or link the issue)?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:2139]: 1,Type the second 'a', the engine will send a wrong affinity, but it does not affect the caret render.
`TextPainter._computeCaretMetrics` will find the real position.
```dart
I/flutter ( 7996): updateEditingValue old: TextEditingValue(text: ┤a├, selection: TextSelection.collapsed(offset: 1, affinity: TextAffinity.upstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I/flutter ( 7996): updateEditingValue new form engine: TextEditingValue(text: ┤aa├, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
```


2,Type the 3rd 'a' 
```dart
I/flutter ( 7996): updateEditingValue old: TextEditingValue(text: ┤aa├, selection: TextSelection.collapsed(offset: 2, affinity: TextAffinity.upstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I/flutter ( 7996): updateEditingValue new form engine: TextEditingValue(text: ┤aaa├, selection: TextSelection.collapsed(offset: 3, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
```

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:2157]: done

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2139]: > the engine will send a wrong affinity

`downstream` is the correct text affinity here when a second `a` is entered

File: packages/flutter/test/material/text_field_test.dart [hunk 4]
```diff
@@ -212,6 +212,151 @@ void main() {
...
 
+  testWidgets('text field selection toolbar should hide when the user starts typing', (WidgetTester tester) async {
+    await tester.pumpWidget(
+      const MaterialApp(
+        home: Scaffold(
+          body: Center(
+            child: SizedBox(
+              width: 100,
+              height: 100,
+              child: Opacity(
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:223]: Why are you including this Opacity widget?

File: packages/flutter/test/material/text_field_test.dart [hunk 5]
```diff
@@ -212,6 +212,151 @@ void main() {
...
+    // The selectWordsInRange with SelectionChangedCause.tap seems to be needed to show the toolbar.
+    // (This is true even if we provide selection parameter to the TextEditingValue above.)
+    final EditableTextState state = tester.state<EditableTextState>(find.byType(EditableText));
+    state.renderEditable.selectWordsInRange(from: Offset.zero, cause: SelectionChangedCause.tap);
+
+    expect(state.showToolbar(), true);
+
+    // This is needed for the AnimatedOpacity to turn from 0 to 1 so the toolbar is visible.
+    await tester.pumpAndSettle();
+    await tester.pump(const Duration(seconds: 1));
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart:254]: You shouldn't need this `tester.pump`, only the `tester.pumpAndSettle`.  Does it not work without it?  I think there are many other tests in this file that show the toolbar without needing a pump like this.

**Review by justinmc — COMMENTED** [review]
Thanks for the PR!  I was thinking this might have needed a tricky engine fix, I'm happy if that's not true.

Can you check if this fixes/improves https://github.com/flutter/flutter/issues/84849?

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:2139]: > `downstream` is the correct text affinity here when a second `a` is entered

Ah, Yes, currently, the cursor at the end of the line and the text did not render wrapping, so the affinity is invalid or meaningless.

In summary, all from engine's affinity is meaningless and we can override it, right?

**Comment by xu-baolin** [comment]
> Can you check if this fixes/improves #84849?

Yes, this indeed fixes #84849 too.

File: packages/flutter/test/material/text_field_test.dart (hunk 4 above)
Comment (xu-baolin) [reply packages/flutter/test/material/text_field_test.dart]: Oh, indeed unnecessary, just copy from another test.

File: packages/flutter/test/material/text_field_test.dart (hunk 5 above)
Comment (xu-baolin) [reply packages/flutter/test/material/text_field_test.dart]: Removed.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2145]: If the engine change actually contains text change or selection change then it should typically be downstream.

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:2145]: Could you explain why? The documentation says that affinity only makes sense when there is ambiguity in the visual location, and is used to paint the caret. Am I miss something?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2145]: When the user types something, or changes the selection using a keyboard, the caret typically shouldn't be painted using the `upstream` affinity. In other words it should be
```
aa
|bb
```
instead of
```
aa|
bb
```

Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart:2145]: I almost understand what you mean.
Another case, if the `aa` is composed, and I wanna to type `aaa` with composed, it should be painted using upstream affinity?

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2145]: That I'm not sure. On Android it's behaving like it's upstream. But I vaguely remember there's no cursor affinity on Android.

**Comment by alexmercerind** [comment]
> > Can you check if this fixes/improves #84849?
> 
> Yes, this indeed fixes #84849 too.

Thanks a lot for your work!

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Done.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 6]
```diff
@@ -2186,6 +2192,17 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
 
+  bool _checkNeedsAdjustAffinity(TextEditingValue value) {
+    // Trust the engine affinity if the text changes or selection changes.
+    if (value.text == _value.text &&
+        value.selection.isCollapsed == _value.selection.isCollapsed &&
+        value.selection.start == _value.selection.start &&
+        value.selection.affinity != _value.selection.affinity) {
+      return true;
+    }
+    return false;
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:2203]: Could you get rid of the `if` and just return the condition directly?

**Review by justinmc — APPROVED** [review]
LGTM :+1:  Thanks again!

I tried running this locally and it does indeed appear to fix both of those issues!
