### PR TITLE
[shell] Fix engineId not being set after hot restart

### LINKED ISSUE #173474: `PlatformDispatcher.instance.engineId` returns `null` after hot restart
The first time we run the app `engineId` is populated with an integer when running on Android but hot restarting causes it to return `null`.

```dart
class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    print('engineId: ${PlatformDispatcher.instance.engineId}');
  }
  // ...
}
```

cc @knopp

### PR DESCRIPTION
**Pull request by knopp**
Fixes #173474

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by knopp** [comment]
@chinmaygarde, any ideas about the test here? It seems that there are no tests for `Shell::OnServiceProtocolRunInView`, and I'm not even sure how to make it work with kernel mappings from `DartFixture`.

**Comment by chinmaygarde** [comment]
You could simulate that a `Shell::RunEngine` call with a configuration that sets the engine ID to a known value is propagated as the return of `Engine::GetLastEngineID` after `Engine::RunStatus::Success`. There are plenty of tests in `shell_unittests` that work this way.

`Shell::OnServiceProtocolRunInView` should calls `Engine::Restart` that in turn calls run.

The behavior you are modifying is that updating the run configuration of an engine updates the engine ID. That its all initiated via the service protocol is incidental and more of an integration test concern. A unit-test focused on just Engine::Run should suffice.

File: engine/src/flutter/shell/common/shell_unittests.cc [hunk 1]
```diff
@@ -4946,6 +4946,8 @@ TEST_F(ShellTest, ProvidesNullEngineId) {
   configuration.SetEntrypoint("providesEngineId");
   RunEngine(shell.get(), std::move(configuration));
 
+  ASSERT_EQ(shell->GetEngine()->GetLastEngineId(), 99);
```
Comment (chinmaygarde) [inline engine/src/flutter/shell/common/shell_unittests.cc]: 99 seems like a magic number here. `RunConfiguration::SetEngineId` to something else and assert that instead?

Also, run it again with a different ID to see that it stick? That way, this test should fail without your patch. As it stands, this test should work with or without your patch right?

Comment (HosseinYousefi) [reply engine/src/flutter/shell/common/shell_unittests.cc]: It seems that this test is dependent on the previous test setting the ID to 99. Can we make the test more standalone as Chinmay suggests?

**Review by HosseinYousefi — COMMENTED** [review]
As I don't have the domain expertise here, I don't have anything to add in terms of the actual code review. Could you please land this faster @knopp?

@chinmaygarde is it possible to add this patch to a hotfix version? The issue with `cronet_http` package is blocked on this.

File: engine/src/flutter/shell/common/shell_unittests.cc (hunk 1 above)
Comment (knopp) [reply engine/src/flutter/shell/common/shell_unittests.cc]: Ouch, that statement should be in different test. Hence the 99 magical value. The test tests for `LastEngineId()`. There is no `LastEngineId` without the patch, it was introduced in the PR.

**Comment by knopp** [comment]
Apologies for the delay. I missed @chinmaygarde feedback and only got pinged now. The assert should be part of another test (once that sets the value 99). I'll move it.

**Review by chinmaygarde — APPROVED** [review]
