### PR TITLE
Text field style merge

### LINKED ISSUE #23994: TextFormField/TextField's style doesn't inherit color
## Steps to Reproduce

1. Run `flutter create bar`
2. Replace main function's content on
 
```dart
void main() => runApp(MaterialApp(
      home: Material(
        child: Center(
          child: Builder(
            builder: (BuildContext context) {
              return TextFormField(
                style: TextStyle(fontSize: 24.0),
              );
            },
          ),
        ),
      ),
    ));
```
3. Start app
4. Type something in input

AR: Color is white
ER: Color from material theme (black)

## Logs

```
Analyzing bar...
No issues found! (ran in 1.1s)
```

```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14.1 18B75, locale en-RU)
    • Flutter version 0.9.4 at /www/dart/flutter
    • Framework revision f37c235c32 (6 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /usr/local/opt/android-sdk
      but Android SDK not found at this location.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2018.3 EAP)
    • IntelliJ at //Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • iPhone XR • 28E7063A-3409-43F9-AB68-CDD9218CF571 • ios • iOS 12.1 (simulator)

! Doctor found issues in 3 categories.
```

I have investigated the problem and found that if you pass custom style without color then the color will be equal to null when building TextSpan in EditableText.
As a solution - use `DefaultTextStyle.of` to fulfill null values in style object

```diff
diff --git a/packages/flutter/lib/src/widgets/editable_text.dart b/packages/flutter/lib/src/widgets/editable_text.dart
index 3c79cc6ac..0389fe235 100644
--- a/packages/flutter/lib/src/widgets/editable_text.dart
+++ b/packages/flutter/lib/src/widgets/editable_text.dart
@@ -21,6 +21,7 @@ import 'scroll_controller.dart';
 import 'scroll_physics.dart';
 import 'scrollable.dart';
 import 'text_selection.dart';
+import 'text.dart';

 export 'package:flutter/services.dart' show TextEditingValue, TextSelection, TextInputType;
 export 'package:flutter/rendering.dart' show SelectionChangedCause;
@@ -917,13 +918,15 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
   /// By default makes text in composing range appear as underlined.
   /// Descendants can override this method to customize appearance of text.
   TextSpan buildTextSpan() {
+    final style = DefaultTextStyle.of(context).style.merge(widget.style);
+
     if (!widget.obscureText && _value.composing.isValid) {
-      final TextStyle composingStyle = widget.style.merge(
+      final TextStyle composingStyle = style.merge(
         const TextStyle(decoration: TextDecoration.underline),
       );

       return TextSpan(
-        style: widget.style,
+        style: style,
         children: <TextSpan>[
           TextSpan(text: _value.composing.textBefore(_value.text)),
           TextSpan(
@@ -942,7 +945,8 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
       if (o != null && o >= 0 && o < text.length)
         text = text.replaceRange(o, o + 1, _value.text.substring(o, o + 1));
     }
-    return TextSpan(style: widget.style, text: text);
+
+    return TextSpan(style: style, text: text);
   }
 }
```

### LINKED ISSUE #24610: TextField should respect text color & fontFamily
This example below displaying a `Text` and a `TextField` side by side using the same `TextStyle` should look similar. However, I think, the `TextField` ignores the inherited `fontFamily` and `color`. Using the `ThemData`, I globally changed text to use OpenSans.

```dart
class Problem extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final style = TextStyle(
      fontSize: 48,
      fontWeight: FontWeight.w100,
    );
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        Text("1234", style: style),
        IntrinsicWidth(
          child: TextField(
            style: style,
            controller: TextEditingController(text: "1234"),
          ),
        ),
      ],
    );
  }
}
```

Here is my result on iOS:

image

Here is my result on Android:

image

Please notice that the font is different and also white instead of black – I changed the scaffold background to make it visible. I find it quite irritating that on iOS the `Text` font is smaller and on Android, actually bigger than the `TextField` font.

Workaround for both platforms is to specify the `fontFamily` as part of the style.

## Output of Flutter doctor:

```
[✓] Flutter (Channel master, v0.11.10-pre.1, on Mac OS X 10.14.1 18B75, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] VS Code (version 1.29.1)
[✓] Connected device (2 available)
```

### PR DESCRIPTION
**Pull request by justinmc**
Closes https://github.com/flutter/flutter/issues/23994
Closes https://github.com/flutter/flutter/issues/24610

TextField's style inherits from the theme where not specified.

### CODE REVIEW

File: packages/flutter/lib/src/material/text_field.dart [hunk 1]
```diff
@@ -508,7 +508,9 @@ class _TextFieldState extends State<TextField> with AutomaticKeepAliveClientMixi
     // assert(debugCheckHasMaterialLocalizations(context));
     assert(debugCheckHasDirectionality(context));
     final ThemeData themeData = Theme.of(context);
-    final TextStyle style = widget.style ?? themeData.textTheme.subhead;
+    final TextStyle style = widget.style != null
+      ? themeData.textTheme.subhead.merge(widget.style)
+      : themeData.textTheme.subhead;
```
Comment (justinmc) [inline packages/flutter/lib/src/material/text_field.dart]: @HansMuller This seems to fix the issue and does not cause any tests to fail.  Do you think it's safe then?

Comment (HansMuller) [reply packages/flutter/lib/src/material/text_field.dart]: I think it should be safe, yes. TextStyle.merge() can handle a null parameter so this can be a one-liner.

File: packages/flutter/test/material/text_field_test.dart [hunk 2]
```diff
@@ -3341,4 +3341,38 @@ void main() {
...
+                );
+              },
+            ),
+          ),
+        ),
+      );
+    }
+
+    await tester.pumpWidget(buildFrame());
+    await tester.pumpAndSettle();
```
Comment (HansMuller) [inline packages/flutter/test/material/text_field_test.dart]: This shouldn't be needed, since there's no animation to wait for here.

File: packages/flutter/test/material/text_field_test.dart [hunk 3]
```diff
@@ -3341,4 +3341,38 @@ void main() {
...
+
+    final ThemeData themeData = ThemeData(
+      textTheme: TextTheme(
+        subhead: TextStyle(
+          color: Colors.blue[500],
+        ),
+      ),
+    );
+
+    Widget buildFrame() {
```
Comment (HansMuller) [inline packages/flutter/test/material/text_field_test.dart]: It would be good to test this version and one where the TextStyle overrides many properties and then one where the TextField's textStyle has inherit:true, which is a special case for merge: see https://docs.flutter.io/flutter/painting/TextStyle/merge.html

File: packages/flutter/test/material/text_field_test.dart [hunk 4]
```diff
@@ -3341,4 +3341,38 @@ void main() {
...
+            ),
+          ),
+        ),
+      );
+    }
+
+    await tester.pumpWidget(buildFrame());
+    await tester.pumpAndSettle();
+    final EditableText editableText = tester.widget(find.byType(EditableText));
+    expect(editableText.style.color, themeData.textTheme.subhead.color);
```
Comment (HansMuller) [inline packages/flutter/test/material/text_field_test.dart]: TextStyle overrides `operator ==` so you can compare editableText.style with ...subhead

File: packages/flutter/test/material/text_field_test.dart [hunk 5]
```diff
@@ -3341,4 +3341,38 @@ void main() {
...
+      ),
+    );
+
+    Widget buildFrame() {
+      return MaterialApp(
+        theme: themeData,
+        home: Material(
+          child: Center(
+            child: Builder(
+              builder: (BuildContext context) {
```
Comment (HansMuller) [inline packages/flutter/test/material/text_field_test.dart]: This builder shouldn't be needed

File: packages/flutter/test/material/text_field_test.dart (hunk 2 above)
Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart]: I was wondering about that one.

**Comment by HansMuller** [comment]
This PR addresses the TextField aspect of https://github.com/flutter/flutter/issues/12681

File: packages/flutter/test/material/text_field_test.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart]: This seems to fail when I try it.  It looks like the editableText style is having some properties changed somewhere along the way so it's no longer equal to the theme.

File: packages/flutter/test/material/text_field_test.dart (hunk 5 above)
Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart]: Whoops I think I was copying that from the issue...

File: packages/flutter/test/material/text_field_test.dart [hunk 6]
```diff
@@ -3341,4 +3341,49 @@ void main() {
...
+    // Properties set on TextStyle override theme
+    const Color setColor = Colors.red;
+    await tester.pumpWidget(buildFrame(const TextStyle(color: setColor)));
+    editableText = tester.widget(find.byType(EditableText));
+    expect(editableText.style.color, setColor);
+
+    // inherit: false causes nothing to be merged in from theme
+    await tester.pumpWidget(buildFrame(TextStyle(
+      fontSize: 24.0,
+      textBaseline: TextBaseline.alphabetic,
```
Comment (justinmc) [inline packages/flutter/test/material/text_field_test.dart]: @HansMuller I found that I got errors when I used a TextStyle with `inherited: false` and didn't also provide these two parameters `fontSize` and `textBaseline`.  I'm sure they're being merged onto this somewhere internally, but `inherited: false` prevents it.  Is that anything to be concerned about?

**Comment by justinmc** [comment]
@HansMuller Updated with your suggestions!

File: packages/flutter/test/material/text_field_test.dart (hunk 4 above)
Comment (HansMuller) [reply packages/flutter/test/material/text_field_test.dart]: That's probably because the theme's TextStyles are localized when the app's theme looked up with `ThemeData.of()'.  See https://docs.flutter.io/flutter/material/ThemeData/localize.html and https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/theme.dart#L137

That's why the value of `Theme.of(context).textTheme.subhead` isn't the same as the textstyle created by the test and to the MaterialApp's theme (ThemeData) parameter.

File: packages/flutter/test/material/text_field_test.dart (hunk 6 above)
Comment (justinmc) [reply packages/flutter/test/material/text_field_test.dart]: Maybe related to this crash? https://github.com/flutter/flutter/issues/8728

That crash doesn't happen for me (with `inherited: true`), but does look similar to this.

**Comment by justinmc** [comment]
@HansMuller This needs a final code review.  I'll improve the error message in another PR.

**Review by HansMuller — APPROVED** [review]
LGTM
