### PR TITLE
Make plugins work in Swift projects

### LINKED ISSUE #15099: "Made Podfiles use symlinks to local pods" not working
## Steps to Reproduce
```shell
set -x

mkdir -p Made_Podfiles_use_symlinks_to_local_pods_NOT_WORKING/
pushd  Made_Podfiles_use_symlinks_to_local_pods_NOT_WORKING/

flutter create -t plugin -i swift --org com.failed failed > /dev/null
pushd failed/example
flutter build ios --debug 
popd

flutter create -t plugin -i swift --org com.success success > /dev/null
pushd success/example
wget -q https://raw.githubusercontent.com/mravn-google/flutter/3723ec0383f79420486bb4ee5acf06ebd190b5cf/packages/flutter_tools/templates/cocoapods/Podfile-swift
cp Podfile-swift ios/Podfile
flutter build ios --debug
popd

popd
```

## Flutter Doctor

➜  ~ flutter doctor -v
[✓] Flutter (Channel master, v0.1.8-pre.43, on Mac OS X 10.13.3 17D102, locale en-KR)
    • Flutter version 0.1.8-pre.43 at /Users/?????/flutter
    • Framework revision fe334e1652 (3 hours ago), 2018-03-02 17:54:51 -0800
    • Engine revision 97b22348c8
    • Dart version 2.0.0-dev.32.0.flutter-ee15c8eb68

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/?????/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/?????/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 22.1.2
    • Dart plugin version 173.4548.30

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.8.0

[✓] Connected devices (1 available)
    • ????????????????????????????????????? • ios • iOS 11.2.6

• No issues found!

### PR DESCRIPTION
**Pull request by mravn-google**
Enabling plugins in Swift iOS projects (https://github.com/flutter/flutter/pull/14667) and making Podfiles use symlinks (https://github.com/flutter/flutter/pull/14748) collided due to https://github.com/CocoaPods/CocoaPods/issues/7463 which affects Swift projects with plugins only.

This PR adds a workaround for the CocoaPods issue to the project template's Swift Podfile.

Fixes #15099

### CODE REVIEW

File: dev/devicelab/lib/tasks/plugin_tests.dart [hunk 1]
```diff
@@ -46,11 +57,19 @@ class FlutterProject {
   final Directory parent;
   final String name;
 
-  static Future<FlutterProject> create(Directory directory) async {
+  static Future<FlutterProject> create(Directory directory, String buildTarget, String language) async {
     await inDirectory(directory, () async {
-      await flutter('create', options: <String>['--org', 'io.flutter.devicelab', 'plugintest']);
+      await flutter('create', options: <String>[
+        '--org', 'io.flutter.devicelab',
+        '-${buildTarget[0]}', language,
```
Comment (jakobr-google) [inline dev/devicelab/lib/tasks/plugin_tests.dart]: Correct, but slightly magical - just so happens that the abbreviation of `--android-language` (`-a`) is also the first letter of the build target 'apk'... :)

**Review by jakobr-google — APPROVED** [review]
LGTM

**Review by jakobr-google — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
This commit seems to have made plugin_test_win significantly flakier and made plugin_test_ios fail (that test has since been disabled). Do we know why? Are we planning on fixing the broken test any time soon or is it just wrong and we should just remove it?

**Comment by mravn-google** [comment]
The failing test should turn green once CocoaPods is upgraded to v 1.4.0 on the device lab machines. (cf https://github.com/flutter/flutter/pull/15446 @yjbanov)

I'll have a look at `plugin_test_win`. There may be two tests racing for access to the same tmp files.

**Comment by yjbanov** [comment]
I upgraded cocoapods to 1.4.0 just now.

**Comment by jpgilchrist** [comment]
When will this get to the beta channel?

**Comment by 0916174** [comment]
I get a similar error when trying to build a project that includes the `image_picker` package:

```
Launching lib/main.dart on iPhone van Jeroen Meijer in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: [REMOVED]
Running Xcode clean...                                       1,0s
Starting Xcode build...
Xcode build done                                             1,4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from /Users/jeroen/.pub-cache/hosted/pub.dartlang.org/image_picker-0.1.1/ios/Classes/ImagePickerPlugin.m:7:
    /Users/jeroen/.pub-cache/hosted/pub.dartlang.org/image_picker-0.1.1/ios/Classes/ImagePickerPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the precompiled application for the device.

Error launching application on iPhone van Jeroen Meijer.
```

**Comment by zoechi** [comment]
@mikeashelby I wouldn't expect anyone reading comments on closed PRs.
I'd suggest to create a new issue (you can link to this PR by adding `#15437`)
with full information (`flutter doctor` output, info required to reproduce, ...)
