### PR TITLE
Request focus in `onTap` callback from `DropdownButton`

### LINKED ISSUE #47128: TextField regains focus when dropdown is opened and closed
## Steps to Reproduce
1. Focus a TextField by tapping it
2. Open a dropdown menu by tapping DropdownButton, keyboard closes and the TextField looks unfocused (border color changes)
3. Close the menu by either selecting an option, or by tapping outside the menu's area
4. Now the focus returns to the TextField and the keyboard opens

I would expect that after closing the dropdown menu, the previously focused TextField would not regain focus. If this is actually normal and expected behaviour I would at least appreciate help in finding a workaround for this behaviour.

<details>
<summary>Minimal code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _State createState() => _State();
}

class _State extends State<MyHomePage> {
  int dropdownValue;
  @override
  Widget build(BuildContext context) {
    final items = [1, 2, 3]
        .map((i) => DropdownMenuItem(child: Text(i.toString()), value: i))
        .toList();
    return Scaffold(
      appBar: AppBar(
        title: Text('Title'),
      ),
      body: Column(
        children: <Widget>[
          TextField(),
          DropdownButton(
            items: items,
            value: dropdownValue,
            onChanged: (value) => setState(() => dropdownValue = value),
          ),
        ],
      ),
    );
  }
}
```
</details>

**Target Platform: Android, iOS**
**Target OS version/browser: doesn't seem to be bound to a specific version**
**Devices: tested with Android emulator and tablet, iPad**

## Logs
```
[√] Flutter (Channel beta, v1.12.13+hotfix.4, on Microsoft Windows [Version 10.0.18362.535], locale lt-LT)
    • Flutter version 1.12.13+hotfix.4 at C:\Users\Rokas\FlutterSDK\flutter
    • Framework revision fb60324e6f (7 days ago), 2019-12-09 15:58:15 -0800
    • Engine revision ac9391978e
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Rokas\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Rokas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/47128 https://github.com/flutter/flutter/issues/24680

Here I added a request for focus on when calling the `onTap` callback, this will prevent focus from moving back to TextField when Dropdown Button is opened while TextField is still focused and resulting keyboard being open again.

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  _State createState() => _State();
}

class _State extends State<MyHomePage> {
  int? dropdownValue = 1;
  final List<int> hugeMenuItems = List<int>.generate(100, (int index) => index);
  late FocusNode focusNode;

  @override
  void initState() {
    super.initState();
    focusNode = FocusNode();
  }

  @override
  void dispose() {
    focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Title'),
      ),
      body: Column(
        children: <Widget>[
          const TextField(),
          DropdownButton(
              focusNode: focusNode,
              value: dropdownValue,
              onTap: () {
                print('FocusNode has focus: ${focusNode.hasPrimaryFocus}');
              },
              items: hugeMenuItems.map<DropdownMenuItem<int>>((int item) {
                return DropdownMenuItem<int>(
                  key: ValueKey<int>(item),
                  value: item,
                  child: Text(item.toString(),
                      key: ValueKey<String>('Text $item')),
                );
              }).toList(),
              onChanged: (int? value) {
                setState(() => dropdownValue = value);
              }),
        ],
      ),
    );
  }
}
``` 
	
</details>

### Before

https://user-images.githubusercontent.com/48603081/142007698-9f9a5b3e-8b1a-4049-85ea-9da93842cf58.mov

### After

https://user-images.githubusercontent.com/48603081/142007691-abf7f983-d087-41c0-91fe-b183b2c92048.mov

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jambestwick — COMMENTED** [review]
commit

File: packages/flutter/lib/src/material/dropdown.dart [hunk 1]
```diff
@@ -1276,6 +1276,9 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
       borderRadius: widget.borderRadius,
     );
 
+    if (!_hasPrimaryFocus) {
```
Comment (gspencergoog) [inline packages/flutter/lib/src/material/dropdown.dart:1279]: It is safe to call `requestFocus` without checking to make sure it has focus first, so you can just remove this conditional.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

...After removing the extra conditional.

**Comment by TahaTesser** [comment]
@gspencergoog 
For some reason,  Google testing just gets stuck at pending...

**Comment by AhmedLSayed9** [comment]
This works fine with DropdownButton but with DropdownButtonFormField it doesn't work well.When you tap on the button it remove the textfield

**Comment by TahaTesser** [comment]
@AhmedLSayed9 
Thanks for the comment, I'm aware of this issue, let me file an issue to track this and fix will be coming soon

**Comment by TahaTesser** [comment]
Filed https://github.com/flutter/flutter/issues/94605

**Comment by AhmedLSayed9** [comment]
Thanks Taha! It's not just stays highlighted, It's start being highlighted after closing the menu. so if we can also have the dropdown button to be highlighted when tapped would be perfect! Thanks again

**Comment by TahaTesser** [comment]
AhmedLSayed9
Good catch, the reason for this is the dropdown pop route, focus moves from the button to the popup immediately when taping on it. I will look into this as wlel

**Comment by TahaTesser** [comment]
AhmedLSayed9
Good catch, the reason for this is the dropdown pop route, focus moves from the button to the popup immediately when taping on it. I will look into this as wlel
