### PR TITLE
SliverEnsureSemantics

### LINKED ISSUE #160217: Screen readers cannot list or move focus to elements outside of the current viewport
### Steps to reproduce

<p>NVDA, JAWS, and VoiceOver Screen readers cannot list or move focus to elements outside of the current viewport. Any elements that have scrolled out of view or haven't yet been scrolled into view will NOT be reachable via screen reader basic keyboard commands for reading and navigating web content.</p>
<p>Examples:</p>
<div class="table-wrap">

Function | JAWS Shortcut | NVDA Shortcut | VoiceOver Shortcut
-- | -- | -- | --
Next Heading | H, 1-6 for heading level | H, 1-6 for heading level | Control Option Command H
List Headings | Insert F6 | Insert F7 to open Elements list, Select the "Headings" radio button | Control Option U, Press left/right arrow keys until the "Heading" menu is displayed
Next Link | U for unvisited link, V for visited link | K for link, U for unvisited, link V for visited link | Control Option Command L for link, Control Option Command V for visited link
List Links | Insert F7 | Insert F7 to open Elements list, Select the "Links" radio button | Control Option U, Press left/right arrow keys until the "Links" menu is displayed
Next Button | B | B | N/A
List Buttons | Control Insert B | Insert F7 to open Elements list, Select the "Buttons" radio button | Control Option U, Press left/right arrow keys until the "Form Controls" menu is displayed
Next Form Control | F | F | Control Option Command J
Next Table | T | T | Control Option Command T
Next Landmark | R | D | N/A
Next List | L | L | Control Option Command X

</div>

### Expected results

- The "Next" keyboard shortcuts should move the screen reader focus to the next element of that type which exists on the page, not just the elements displayed in the current viewport
- The lists should contain all elements of that type which exist on the page, not just the elements displayed in the current viewport

### Actual results

- The "Next" keyboard shortcuts only move the screen reader focus to the next element of that type which is displayed in the current viewport
- The lists only contain elements of that type which are displayed in the current viewport

### Code sample

N/A

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

`Flutter (Channel beta, 3.27.0-0.1.pre, on macOS 14.5 23F79 darwin-arm64, locale en-US)`

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Currently when using a `CustomScrollView`, screen readers cannot list or move focus to elements that are outside the current Viewport and cache extent because we do not create semantic nodes for these elements.

This change introduces `SliverEnsureSemantics` which ensures its sliver child is included in the semantics tree, whether or not it is currently visible on the screen or within the cache extent. This way screen readers are aware the elements are there and can navigate to them / create accessibility traversal menus with this information.
* Under the hood a new flag has been added to `RenderSliver` called `ensureSemantics`. `RenderViewportBase` uses this in its `visitChildrenForSemantics` to ensure a sliver is visited when creating the semantics tree. Previously a sliver was not visited if it was not visible or within the cache extent. `RenderViewportBase` also uses this in `describeSemanticsClip` and `describeApproximatePaintClip` to ensure a sliver child that wants to "ensure semantics" is not clipped out if it is not currently visible in the viewport or outside the cache extent.
* `RenderSliverMultiBoxAdaptor.semanticBounds` now leverages its first child as an anchor for assistive technologies to be able to reach it if the Sliver is a child of `SliverEnsureSemantics`. If not it will still be dropped from the semantics tree.
* `RenderProxySliver` now considers child overrides of `semanticBounds`.

On the engine side we move from using a joystick method to scroll with `SemanticsAction.scrollUp` and `SemanticsAction.scrollDown` to using `SemanticsAction.scrollToOffset` completely letting the browser drive the scrolling with its current dom scroll position "scrollTop" or "scrollLeft". This is possible by calculating the total quantity of content under the scrollable and sizing the scroll element based on that.

<details open><summary>Code sample</summary>

```dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

/// Flutter code sample for [SliverEnsureSemantics].

void main() => runApp(const SliverEnsureSemanticsExampleApp());

class SliverEnsureSemanticsExampleApp extends StatelessWidget {
  const SliverEnsureSemanticsExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: SliverEnsureSemanticsExample());
  }
}

class SliverEnsureSemanticsExample extends StatefulWidget {
  const SliverEnsureSemanticsExample({super.key});

  @override
  State<SliverEnsureSemanticsExample> createState() =>
      _SliverEnsureSemanticsExampleState();
}

class _SliverEnsureSemanticsExampleState
    extends State<SliverEnsureSemanticsExample> {
  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        backgroundColor: theme.colorScheme.inversePrimary,
        title: const Text('SliverEnsureSemantics Demo'),
      ),
      body: Center(
        child: CustomScrollView(
          semanticChildCount: 106,
          slivers: <Widget>[
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 0,
                  child: Card(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          Semantics(
                            header: true,
                            headingLevel: 3,
                            child: Text(
                              'Steps to reproduce',
                              style: theme.textTheme.headlineSmall,
                            ),
                          ),
                          const Text('Issue description'),
                          Semantics(
                            header: true,
                            headingLevel: 3,
                            child: Text(
                              'Expected Results',
                              style: theme.textTheme.headlineSmall,
                            ),
                          ),
                          Semantics(
                            header: true,
                            headingLevel: 3,
                            child: Text(
                              'Actual Results',
                              style: theme.textTheme.headlineSmall,
                            ),
                          ),
                          Semantics(
                            header: true,
                            headingLevel: 3,
                            child: Text(
                              'Code Sample',
                              style: theme.textTheme.headlineSmall,
                            ),
                          ),
                          Semantics(
                            header: true,
                            headingLevel: 3,
                            child: Text(
                              'Screenshots',
                              style: theme.textTheme.headlineSmall,
                            ),
                          ),
                          Semantics(
                            header: true,
                            headingLevel: 3,
                            child: Text(
                              'Logs',
                              style: theme.textTheme.headlineSmall,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
            SliverFixedExtentList(
              itemExtent: 44.0,
              delegate: SliverChildBuilderDelegate(
                (BuildContext context, int index) {
                  return Card(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Text('Item $index'),
                    ),
                  );
                },
                childCount: 50,
                semanticIndexOffset: 1,
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 51,
                  child: Card(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Semantics(
                        header: true,
                        child: const Text('Footer 1'),
                      ),
                    ),
                  ),
                ),
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 52,
                  child: Card(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Semantics(
                        header: true,
                        child: const Text('Footer 2'),
                      ),
                    ),
                  ),
                ),
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 53,
                  child: Semantics(link: true, child: const Text('Link #1')),
                ),
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 54,
                  child: OverflowBar(
                    children: <Widget>[
                      TextButton(
                        onPressed: () {},
                        child: const Text('Button 1'),
                      ),
                      TextButton(
                        onPressed: () {},
                        child: const Text('Button 2'),
                      ),
                    ],
                  ),
                ),
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 55,
                  child: Semantics(link: true, child: const Text('Link #2')),
                ),
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverSemanticsList(
                sliver: SliverFixedExtentList(
                  itemExtent: 44.0,
                  delegate: SliverChildBuilderDelegate(
                    (BuildContext context, int index) {
                      return Semantics(
                        role: SemanticsRole.listItem,
                        child: Card(
                          child: Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: Text('Second List Item $index'),
                          ),
                        ),
                      );
                    },
                    childCount: 50,
                    semanticIndexOffset: 56,
                  ),
                ),
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 107,
                  child: Semantics(link: true, child: const Text('Link #3')),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// A sliver that assigns the role of SemanticsRole.list to its sliver child.
class SliverSemanticsList extends SingleChildRenderObjectWidget {
  const SliverSemanticsList({super.key, required Widget sliver})
    : super(child: sliver);

  @override
  RenderSliverSemanticsList createRenderObject(BuildContext context) =>
      RenderSliverSemanticsList();
}

class RenderSliverSemanticsList extends RenderProxySliver {
  @override
  void describeSemanticsConfiguration(SemanticsConfiguration config) {
    super.describeSemanticsConfiguration(config);
    config.role = SemanticsRole.list;
  }
}
```
</details>

Fixes: #160217

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by Renzo-Olivares** [comment]
The framework portion of this is ready for an initial review, i'm still making sure the web engine part of this is correct.

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 1]
```diff
@@ -878,6 +879,14 @@ class SemanticsData with Diagnosticable {
   ///  * [ScrollPosition.pixels], from where this value is usually taken.
   final double? scrollPosition;
 
+  /// Indicates the total quantity of available content if the node is
+  /// scrollable.
+  ///
+  /// See also:
+  ///
+  ///  * [ScrollPosition.extentTotal], from where this value is usually taken.
+  final double? scrollExtentTotal;
```
Comment (chunhtai) [inline packages/flutter/lib/src/semantics/semantics.dart:888]: I think you can get this by scrollExtentMax- scrollExtentMin + rect.height( or width). Do we really need a new property?

File: packages/flutter/lib/src/rendering/sliver.dart [hunk 2]
```diff
@@ -1306,6 +1306,17 @@ List<DiagnosticsNode> _debugCompareFloats(
 /// than zero, then it should override [childCrossAxisPosition]. For example
 /// [RenderSliverGrid] overrides this method.
 abstract class RenderSliver extends RenderObject {
+  /// Whether this sliver should be included in the semantics tree.
+  ///
+  /// This value is used by [RenderViewportBase.visitChildrenForSemantics]
+  /// to ensure a sliver is included in the semantics tree regardless of its geometry.
+  bool get ensureSemantics => _ensureSemantics;
+  bool _ensureSemantics = false;
+  set ensureSemantics(bool value) {
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/sliver.dart:1315]: Is this setter used any where? it is also a bit weird to implement setter for a property that is going to be override by subclass

File: packages/flutter/lib/src/rendering/viewport.dart [hunk 3]
```diff
@@ -314,7 +314,10 @@ abstract class RenderViewportBase<ParentDataClass extends ContainerParentDataMix
   void visitChildrenForSemantics(RenderObjectVisitor visitor) {
     childrenInPaintOrder
         .where(
-          (RenderSliver sliver) => sliver.geometry!.visible || sliver.geometry!.cacheExtent > 0.0,
+          (RenderSliver sliver) =>
+              sliver.geometry!.visible ||
+              sliver.geometry!.cacheExtent > 0.0 ||
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/viewport.dart:319]: looks like there as long as the sliver has cacheExtent they will also be preserved. can the SliverEnsureSemantics sets a cacheExtent in itself to avoid adding ensureSemantics?

File: packages/flutter/lib/src/rendering/sliver.dart [hunk 4]
```diff
@@ -2010,6 +2021,16 @@ class RenderSliverToBoxAdapter extends RenderSliverSingleBoxAdapter {
   /// Creates a [RenderSliver] that wraps a [RenderBox].
   RenderSliverToBoxAdapter({super.child});
 
+  @override
+  Rect get semanticBounds {
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/sliver.dart:2025]: is this needed?

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 1 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/semantics/semantics.dart:888]: Thanks for pointing this out, I don't think we need a new parameter then.

File: packages/flutter/lib/src/rendering/sliver.dart (hunk 2 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/sliver.dart]: Removed this setter.

File: packages/flutter/lib/src/rendering/viewport.dart (hunk 3 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/viewport.dart:319]: I think relying on the slivers `cacheExtent` wouldn't work for the `describeApproximatePaintClip` and `describeSemanticsClip` case either since we wouldn't be able to differentiate between an item that is invisible but does not want to be clipped vs an item that is invisible but should be clipped, maybe if we use a magic number but not sure how stable that would be (would a normal sliver ever reach this magic number).

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/viewport.dart:319]: agree, if it has other implication then we better off implement a new api for this

File: packages/flutter/lib/src/rendering/proxy_sliver.dart [hunk 5]
```diff
@@ -473,3 +473,9 @@ class RenderSliverConstrainedCrossAxis extends RenderProxySliver {
     );
   }
 }
+
+/// Ensures its sliver child is included in the semantics tree.
+class RenderSliverEnsureSemantics extends RenderProxySliver {
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/proxy_sliver.dart:478]: consider moving this to widget layer and keep this private

Comment (chunhtai) [reply packages/flutter/lib/src/rendering/proxy_sliver.dart:478]: It has been a while since i looked at the sliver code. Can we assume this child will some how gets laid out even if it is offscreen? my understand is that to get the correct gemoetry (to calculate paint extend) this has to be laid out by the parent. If so, can you point me to the code that this happens?

File: packages/flutter/lib/src/rendering/sliver.dart [hunk 6]
```diff
@@ -1306,6 +1307,17 @@ List<DiagnosticsNode> _debugCompareFloats(
 /// than zero, then it should override [childCrossAxisPosition]. For example
 /// [RenderSliverGrid] overrides this method.
 abstract class RenderSliver extends RenderObject {
+  /// Whether this sliver should be included in the semantics tree.
+  ///
+  /// This value is used by [RenderViewportBase.visitChildrenForSemantics]
+  /// to ensure a sliver is included in the semantics tree regardless of its geometry.
+  ///
+  /// [RenderSliverEnsureSemantics] overrides this value to `true` to ensure
+  /// its sliver child is included in the semantics tree.
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/sliver.dart:1316]: somewhere in the doc should explain the following

1. the difference between this and off screen rendersliver that was laid out due to cache extent
2. A typical example why someone may want to override this getter to return true.

File: packages/flutter/lib/src/rendering/sliver.dart [hunk 7]
```diff
@@ -1306,6 +1307,17 @@ List<DiagnosticsNode> _debugCompareFloats(
 /// than zero, then it should override [childCrossAxisPosition]. For example
 /// [RenderSliverGrid] overrides this method.
 abstract class RenderSliver extends RenderObject {
+  /// Whether this sliver should be included in the semantics tree.
+  ///
+  /// This value is used by [RenderViewportBase.visitChildrenForSemantics]
+  /// to ensure a sliver is included in the semantics tree regardless of its geometry.
```
Comment (chunhtai) [inline packages/flutter/lib/src/rendering/sliver.dart:1313]: > regardless of its geometry

does this mean the geometry may not be accurate?

I was assuming the geometry must be accurate, at least the scroll extent. Otherwise, how would the engine calculate the amount it needs to scroll to review this item?

**Review by chunhtai — COMMENTED** [review]
I think the API surface looks good to me, but i left some question about the geometry

File: packages/flutter/lib/src/rendering/proxy_sliver.dart (hunk 5 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/proxy_sliver.dart:478]: We can't necessarily assume that. For the case of my examples where a single item is wrapped with a `SliverToBoxAdapter`, this works because `SliverToBoxAdapter` always lays its child out.

The code is mainly here

https://github.com/flutter/flutter/blob/dafbc0e1c077be49b8b54f5689015ef598a76910/packages/flutter/lib/src/rendering/viewport.dart#L572-L670

From my understanding `RenderViewportBase` will call `layout` on all its children, but its up to the child to actually lay itself out. Lazily created slivers like `RenderSliverList` will not layout all their children, so this approach actually doesn't work for that case, even if wrapped with an `SliverEnsureSemantics` because the geometry will have an empty rect. I wonder if we can leverage that `RenderSliverList` always lays out its first child in order to calculate the total scroll extent, and use that as the semantic bounds while the lazy sliver is off screen.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/proxy_sliver.dart:478]: Oops how I explained it above is how it actually works by default right now. Since the RenderSliverList always builds its first child those are its current bounds, if you wrap a SliverList with SliverEnsureSemantics, this ensures that `RenderViewportBase` still visits its in `visitChildrenForSemantics` and ensures that it doesn't get clipped out in the `describeSemanticsClip` or `describeApproximateClipRect`.

So for example

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const MyApp());
  SemanticsBinding.instance.ensureSemantics();
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        backgroundColor: theme.colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: CustomScrollView(
          semanticChildCount: 52,
          slivers: <Widget>[
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 0,
                  child: Card(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          Semantics(
                            header: true,
                            headingLevel: 3,
                            child: Text(
                              'Steps to reproduce',
                              style: theme.textTheme.headlineSmall,
                            ),
                          ),
                          Text('Issue description'),
                          Semantics(
                            header: true,
                            headingLevel: 3,
                            child: Text(
                              'Expected Results',
                              style: theme.textTheme.headlineSmall,
                            ),
                          ),
                          Semantics(
                            header: true,
                            headingLevel: 3,
                            child: Text(
                              'Actual Results',
                              style: theme.textTheme.headlineSmall,
                            ),
                          ),
                          Semantics(
                            header: true,
                            headingLevel: 3,
                            child: Text(
                              'Code Sample',
                              style: theme.textTheme.headlineSmall,
                            ),
                          ),
                          Semantics(
                            header: true,
                            headingLevel: 3,
                            child: Text(
                              'Screenshots',
                              style: theme.textTheme.headlineSmall,
                            ),
                          ),
                          Semantics(
                            header: true,
                            headingLevel: 3,
                            child: Text(
                              'Logs',
                              style: theme.textTheme.headlineSmall,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (BuildContext context, int index) {
                  return Card(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Text('Item $index'),
                    ),
                  );
                },
                childCount: 50,
                semanticIndexOffset: 1,
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 52,
                  child: Card(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Semantics(header: true, child: Text('Footer 1')),
                    ),
                  ),
                ),
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 53,
                  child: Card(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Semantics(header: true, child: Text('Footer 2')),
                    ),
                  ),
                ),
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 54,
                  child: Semantics(link: true, child: Text('Link #1')),
                ),
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 55,
                  child: OverflowBar(
                    children: <Widget>[
                      TextButton(onPressed: () {}, child: Text('Button 1')),
                      TextButton(onPressed: () {}, child: Text('Button 2')),
                    ],
                  ),
                ),
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 56,
                  child: Semantics(link: true, child: Text('Link #2')),
                ),
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverList(
                delegate: SliverChildBuilderDelegate(
                  (BuildContext context, int index) {
                    return Semantics(
                      role: SemanticsRole.listItem,
                      child: Card(
                        child: Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: Text('Second List Item $index'),
                        ),
                      ),
                    );
                  },
                  childCount: 50,
                  semanticIndexOffset: 56,
                ),
              ),
            ),
            SliverEnsureSemantics(
              sliver: SliverToBoxAdapter(
                child: IndexedSemantics(
                  index: 107,
                  child: Semantics(link: true, child: Text('Link #3')),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

this works because the second list still lays out its first child, so the browser has this information and can jump to it.

File: packages/flutter/lib/src/rendering/sliver.dart (hunk 7 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/sliver.dart:1313]: Yeah the geometry may not be accurate for example for lazy slivers, but for lazy slivers like `SliverList`, we always lay out at least the first child so we can estimate the total scroll extent. The first childs rect should be enough information to move the list into view.

Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/sliver.dart:1313]: Yeah the geometry may not be accurate for example for lazy slivers, but for lazy slivers like `SliverList`, we always lay out at least the first child so we can estimate the total scroll extent. The first childs rect should be enough information to move the list into view.

File: packages/flutter/lib/src/rendering/proxy_sliver.dart (hunk 5 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/proxy_sliver.dart]: Talked offline, concluded it is reasonable to use the first child bounds as the semantic bounds while the sliver is off screen.

File: packages/flutter/lib/src/rendering/sliver.dart (hunk 7 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/rendering/sliver.dart]: For lazy slivers like SliverList, this PR now leverages the fact that the first child is always laid out as an anchor for semantics to bring the list into view.

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart [hunk 8]
```diff
@@ -122,6 +90,18 @@ class SemanticScrollable extends SemanticRole {
     // Scrolling is controlled by setting overflow-y/overflow-x to 'scroll`. The
     // default overflow = "visible" needs to be unset.
     semanticsObject.element.style.overflow = '';
```
[the remark this answers is not in the document]
Comment (yjbanov) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:95]: Could you elaborate? I imagine using a behavior would make it _easier_ to assign a role. Scrollability seems to be an orthogonal concept to list. You can have scrollable and non-scrollable lists, and you can have scrollables that are not lists (although most often they are a list). For example, you can have scrollable tables, lists, and menus. But you can also have non-scrollable variants of those. To express that you can set the role independently of using the scrollable behavior.

[the remark this answers is not in the document]
Comment (yjbanov) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:95]: Also, right now `SemanticScrollable` is a `SemanticRole`. I'd argue that we should change that.

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart [hunk 9]
```diff
@@ -9,20 +10,10 @@ import 'package:ui/ui.dart' as ui;
...
-/// by the framework and we receive a [ui.SemanticsUpdate] containing the new
-/// [scrollPosition] and child positions.
-///
-/// "scrollTop" or "scrollLeft" is always reset to an arbitrarily chosen non-
-/// zero "neutral" scroll position value. This is done so we have a
-/// predictable range of DOM scroll position values. When the amount of
-/// contents is less than the size of the viewport the browser snaps
-/// "scrollTop" back to zero. If there is more content than available in the
-/// viewport "scrollTop" may take positive values.
+/// Scrolling is controlled by sending the current dom scroll position in a
```
Comment (yjbanov) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:13]: nit: s/dom/DOM/

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart [hunk 10]
```diff
@@ -39,81 +30,61 @@ class SemanticScrollable extends SemanticRole {
...
-  /// When the assistive technology gets to the last element of the scrollable
-  /// list, the browser thinks the scrollable area doesn't have any more content,
-  /// so it overrides the value of "scrollTop"/"scrollLeft" with zero. As a result,
-  /// the user can't scroll back up/left.
-  ///
-  /// As a workaround, we add this DOM element and set its size to
-  /// [canonicalNeutralScrollPosition] so the browser believes
-  /// that the scrollable area still has some more content, and doesn't override
-  /// scrollTop/scrollLetf with zero.
+  /// Dom element used to indicate to the browser the total quantity of available
```
Comment (yjbanov) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:33]: nit: s/Dom/DOM/

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart [hunk 11]
```diff
@@ -39,81 +30,61 @@ class SemanticScrollable extends SemanticRole {
...
+  /// content under this scrollable area. This element is sized based on the
+  /// total scroll extent calculated by scrollExtentMax - scrollExtentMin + rect.height
+  /// of the [SemanticsObject] managed by this scrollable.
   final DomElement _scrollOverflowElement = createDomElement('flt-semantics-scroll-overflow');
 
   /// Listens to HTML "scroll" gestures detected by the browser.
   ///
-  /// This gesture is converted to [ui.SemanticsAction.scrollUp] or
-  /// [ui.SemanticsAction.scrollDown], depending on the direction.
+  /// When we detect a "scroll" gesture we send the updated dom scroll position
```
Comment (yjbanov) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:41]: nit: s/dom/DOM/
nit: [avoid "we"](https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#use-the-passive-voice-recommend-do-not-require-never-say-things-are-simple) (in this case I think "we" refers to the "engine")

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart [hunk 12]
```diff
@@ -122,6 +93,18 @@ class SemanticScrollable extends SemanticRole {
...
+    // mouse or keyboard is plugged in. This causes the clientHeight or clientWidth
+    // of the scrollable dom element to be offset by the width of the scrollbar.
+    // This causes issues in the vertical scrolling context because the max scroll
+    // extent is calculated by the element's scrollHeight - clientHeight, so when
+    // the clientHeight is offset by scrollbar width the browser may think we have
+    // a greater scroll extent then what is actually available.
+    //
+    // We already make the scrollbar transparent so here we set scrollbar-width
+    // to "none" to prevent it from affecting the max scroll extent.
+    semanticsObject.element.style.scrollbarWidth = 'none';
```
Comment (yjbanov) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:107]: It might be worth noting that this only works in Safari 18.2+ (https://caniuse.com/?search=scrollbar-width). Older Safari version may continue to struggle (I imagine they already struggle today even without your change?).

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart [hunk 13]
```diff
@@ -183,64 +172,51 @@ class SemanticScrollable extends SemanticRole {
...
-  /// referred to as "neutral scroll position".
-  ///
-  /// We always set the scroll position to a non-zero value in order to
-  /// be able to scroll in the negative direction. When scrollTop/scrollLeft is
-  /// zero the browser will refuse to scroll back even when there is more
-  /// content available.
-  void _neutralizeDomScrollPosition() {
+  /// Updates the scrollable state of the semantics object.
+  void _updateScrollableState() {
     // This value is arbitrary.
```
Comment (yjbanov) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:177]: This comment in no longer needed

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart [hunk 14]
```diff
@@ -183,64 +172,51 @@ class SemanticScrollable extends SemanticRole {
...
-      // it doesn't scroll into the visible area.
-      final int verticalOffset = rect.height.ceil() + canonicalNeutralScrollPosition;
+      // Place the _scrollOverflowElement at the beginning of the content
+      // and size it based on the total scroll extent so the browser
+      // knows how much scrollable content there is.
+      final double? scrollExtentMax = semanticsObject.scrollExtentMax;
+      final double? scrollExtentMin = semanticsObject.scrollExtentMin;
+      assert(scrollExtentMax != null);
+      assert(scrollExtentMin != null);
+      final double scrollExtentTotal = scrollExtentMax! - scrollExtentMin! + rect.height.round();
```
Comment (yjbanov) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:191]: Should we `round()` after adding all the doubles? I.e. `(a + b + c).round()` instead of `a + b + c.round()`

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart [hunk 15]
```diff
@@ -183,64 +172,51 @@ class SemanticScrollable extends SemanticRole {
...
       _scrollOverflowElement.style
-        ..transform = 'translate(0px,${verticalOffset}px)'
         ..width = '${rect.width.round()}px'
```
Comment (yjbanov) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:193]: Does this need to span the width of the contains? Can it be something static, like `1px`? Or even `0` if that's still enough to communicate the total height?

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart [hunk 16]
```diff
@@ -183,64 +172,51 @@ class SemanticScrollable extends SemanticRole {
...
-      // it doesn't scroll into the visible area.
-      final int horizontalOffset = rect.width.ceil() + canonicalNeutralScrollPosition;
+      // Place the _scrollOverflowElement at the beginning of the content
+      // and size it based on the total scroll extent so the browser
+      // knows how much scrollable content there is.
+      final double? scrollExtentMax = semanticsObject.scrollExtentMax;
+      final double? scrollExtentMin = semanticsObject.scrollExtentMin;
+      assert(scrollExtentMax != null);
+      assert(scrollExtentMin != null);
+      final double scrollExtentTotal = scrollExtentMax! - scrollExtentMin! + rect.width.round();
```
Comment (yjbanov) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:206]: Looks like the 5 lines above can be moved out of the `if` block and shared by both `if` and `else`.

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart [hunk 17]
```diff
@@ -183,64 +172,51 @@ class SemanticScrollable extends SemanticRole {
...
       _scrollOverflowElement.style
-        ..transform = 'translate(${horizontalOffset}px,0px)'
-        ..width = '${canonicalNeutralScrollPosition}px'
+        ..width = '${scrollExtentTotal}px'
         ..height = '${rect.height.round()}px';
```
Comment (yjbanov) [inline engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:209]: Ditto re height value, can it be something static?

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart (hunk 12 above)
Comment (Renzo-Olivares) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:107]: Yeah the issue is also present without my changes (accessibility focus gets misaligned when reaching the end of the scrollable).

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart (hunk 15 above)
Comment (Renzo-Olivares) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:196]: Tried both 0 and 1 and they don't seem to cause any issues. Updated PR to have '0px'.

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart (hunk 17 above)
Comment (Renzo-Olivares) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:212]: https://github.com/flutter/flutter/pull/165589#discussion_r2032001147

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart (hunk 14 above)
Comment (Renzo-Olivares) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart:194]: Maybe we shouldn't round here at all since we want to match the frameworks calculation of total scroll extent https://github.com/flutter/flutter/blob/110b07835ab17e6aea29c6d192649b6fa48e4092/packages/flutter/lib/src/widgets/scroll_metrics.dart#L154. What do you think?

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart (hunk 16 above)
Comment (Renzo-Olivares) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart]: It's not used by the trailing `else` block, should we keep it as is or is that an over-optimization?

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart (hunk 14 above)
Comment (Piinks) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart]: Are we trying to account for a precision error?

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart (hunk 16 above)
Comment (yjbanov) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart]: Ah, yeah, I'm not worried about the `else` case because we only hit it when there's too little content to scroll in any direction. In that case we don't actually produce any updates to the scroll position, so there's no performance penalty. Sharing this code will make it less bug-prone (e.g. someone updates one but not the other in a future update), and will save a few bytes in download size.

File: packages/flutter/lib/src/widgets/sliver.dart [hunk 18]
```diff
@@ -1771,3 +1771,42 @@ class _SliverMainAxisGroupElement extends MultiChildRenderObjectElement {
...
+/// not provide a valid [RenderSliver.semanticBounds]. This sliver does not guarantee its
+/// child sliver is laid out.
+///
+/// When using this sliver consider that if this sliver is placed after a lazy sliver like
+/// [SliverList] or [SliverGrid], the estimated total scroll extent may not be accurate. This
+/// can lead to assistive technologies failing to accurately scroll to [SliverEnsureSemantics]
+/// because the total scroll extent is underestimated. In this case you can use a [SliverFixedExtentList],
+/// [SliverVariedExtentList], or [SliverPrototypeExtentList] instead so that the total scroll
+/// extent before [SliverEnsureSemantics] is calculated accurately. For [SliverGrid]s you can
+/// provide a [SliverGridDelegateWithFixedCrossAxisCount], or [SliverGridDelegateWithMaxCrossAxisExtent].
```
Comment (Piinks) [inline packages/flutter/lib/src/widgets/sliver.dart:1791]:
```suggestion
/// Be mindful when positioning [SliverEnsureSemantics] in a [CustomScrollView] after slivers that build
/// their children lazily, like [SliverList]. Lazy slivers might underestimate the total scrollable size (scroll
/// extent) before the [SliverEnsureSemantics] widget. This inaccuracy can cause problems for assistive
/// technologies (e.g., screen readers), which rely on a correct scroll extent to navigate properly; they
/// might fail to scroll accurately to the content wrapped by [SliverEnsureSemantics].

/// To avoid this potential issue and ensure the scroll extent is calculated accurately up to this sliver,
/// it's recommended to use slivers that can determine their extent precisely beforehand. Instead of
/// [SliverList], consider using [SliverFixedExtentList], [SliverVariedExtentList], or
/// [SliverPrototypeExtentList]. If using [SliverGrid], ensure it employs a delegate such as
/// [SliverGridDelegateWithFixedCrossAxisCount] or [SliverGridDelegateWithMaxCrossAxisExtent].
/// Using these alternatives guarantees that the scrollable area's size is known accurately, allowing
/// assistive technologies to function correctly with [SliverEnsureSemantics].
```

File: engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart (hunk 14 above)
Comment (yjbanov) [reply engine/src/flutter/lib/web_ui/lib/src/engine/semantics/scrollable.dart]: I don't know enough to say if precision matters here. However, since this is stringified into `'${scrollExtentTotal}px'`, I'd run it through `toStringAsFixed`, e.g. `'${scrollExtentTotal.toStringAsFixed(1)}px'`.

File: packages/flutter/lib/src/widgets/sliver.dart (hunk 18 above)
Comment (Piinks) [reply packages/flutter/lib/src/widgets/sliver.dart:1791]: Took a stab at tweaking these docs. Slivers can be really hard for folks to wrap their head around at this lower level.

**Review by Piinks — COMMENTED** [review]
Overall this LGTM, although I wonder if some of the questions in https://github.com/flutter/flutter/issues/166703 should have answers before we land this. If a sliver always builds its first child, and we want to ensure we can scroll it into view accurately, does that mean ensureVisible is a viable option again? I know the issue mentions showOnScreen too.

File: packages/flutter/lib/src/widgets/sliver.dart (hunk 18 above)
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/sliver.dart:1791]: Thank you Kate this sounds great, i'll add this in!

**Comment by Renzo-Olivares** [comment]
> Overall this LGTM, although I wonder if some of the questions in #166703 should have answers before we land this. If a sliver always builds its first child, and we want to ensure we can scroll it into view accurately, does that mean ensureVisible is a viable option again? I know the issue mentions showOnScreen too.

Talked offline and decided this change was still beneficial to land since the potential follow up solution would still rely on `SliverEnsureSemantics` since we need to have some method of ensuring the browser receives the semantic information from the framework for off-screen items.

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Comment by Renzo-Olivares** [comment]
Reason for revert: breaking internal tests
