### PR TITLE
Correct position for an open CupertinoContextMenu

### LINKED ISSUE #60334: iOS Context Menus incorrectly moves to the center between screens
The current context menu will always move to the center between the screens, so it is difficult to use it in lists or other places.

like: 

https://github.com/user-attachments/assets/e4a8ade7-b970-43e9-957e-34c02237e35d

### PR DESCRIPTION
**Pull request by victorsanni**
### Flutter
https://github.com/user-attachments/assets/e120bdda-4236-480d-a85f-183b176bc2a9

### Native

https://github.com/user-attachments/assets/7577b0a0-9111-47e0-ad5d-f533a14310ea

### Flutter
https://github.com/user-attachments/assets/98ba9ffe-715f-4ec6-8d33-e10a8ae69d7d

### Native

https://github.com/user-attachments/assets/b6dbc891-5e01-4ac5-a362-d714328e46d3

### Flutter
https://github.com/user-attachments/assets/9191b8ba-e80a-4d88-b6c4-75876704c2aa

### Native

https://github.com/user-attachments/assets/bb7dfe21-a87b-4eab-a2d2-fab35a7a4c70

<details>
<summary>Flutter sample code</summary>

```dart

import 'package:flutter/cupertino.dart';

void main() => runApp(const ContextMenuApp());

class ContextMenuApp extends StatelessWidget {
  const ContextMenuApp({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: MyStatelessWidget(),
    );
  }
}

/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({super.key});

  List<String> getDataList() {
    List<String> list = [];
    for (int i = 0; i < 15; i++) {
      list.add(i.toString());
    }
    return list;
  }

  List<Widget> getWidgetList(BuildContext context) {
    return getDataList()
        .map((item) => getItemContainer(context, item))
        .toList();
  }

  Widget getItemContainer(BuildContext context, String item) {
    return CupertinoContextMenu(
      actions: List<Widget>.generate(
        4,
        (index) {
          return CupertinoContextMenuAction(
            child: Text('Action ${index + 1}'),
            onPressed: () {
              Navigator.pop(context);
            },
          );
        },
      ),
      child: SizedBox.square(
        dimension:
            350, // Change to increase the size of the context menu's child.
        child: ColoredBox(
          color: CupertinoColors.destructiveRed,
          child: Align(
            alignment: Alignment.center,
            child: Text(
              item,
              style: TextStyle(color: CupertinoColors.white, fontSize: 20),
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('Context Menu Demo'),
      ),
      child: SafeArea(
        child: GridView.count(
          crossAxisSpacing: 5.0,
          mainAxisSpacing: 5.0,
          padding: EdgeInsets.all(10.0),
          crossAxisCount: 3,
          childAspectRatio: 1.0,
          children: getWidgetList(context),
        ),
      ),
    );
  }
}


```

</details>

<details>
<summary>Native sample code</summary>

```swift
import SwiftUI

struct ContentView: View {
    let colors: [Color] = [.red, .orange, .blue, .green]
    
    var body: some View {
        NavigationView {
            ScrollView {
                LazyVGrid(columns: Array(repeating: GridItem(.flexible()), count: 3), spacing: 5) {
                    ForEach(0..<15) { index in
                        ContextMenuItem(item: "\(index)", color: colors.randomElement()!)
                    }
                }
                .padding(10)
            }
            .navigationTitle("Context Menu Demo")
            .navigationBarTitleDisplayMode(.inline)
        }
    }
}

struct ContextMenuItem: View {
    let item: String
    let color: Color
    
    var body: some View {
        
        Text(item)
            .font(.system(size: 20))
            .foregroundColor(.white)
            .frame(width: 220, height: 220)
            .background(color)
            .cornerRadius(8)
            .contextMenu {
                ForEach(1..<5) { i in
                    Button("Action \(i)") {
                        print("Action \(i) tapped for item: \(item)")
                    }
                }
            } preview: {
                Text(item)
                    .font(.system(size: 20))
                    .foregroundColor(.white)
                    .frame(width: 250, height: 500)
                    .background(color)
                    .cornerRadius(8)
                    
            }
    }
}

```

</details>

Fixes [iOS Context Menus incorrectly moves to the center between screens](https://github.com/flutter/flutter/issues/60334)

### CODE REVIEW

**Comment by MaherSafadii** [comment]
good improvements, here are some other notes:

- increase the blur sigma to something 30+
- the animation seems fast and aggressive and not smooth

**Comment by victorsanni** [comment]
> good improvements, here are some other notes:
> 
> * increase the blur sigma to something 30+
> * the animation seems fast and aggressive and not smooth

These sound like valid changes. To make it easier to review, this PR can focus on positioning/layout, and we can focus on the animation and visual fidelity in a subsequent PR.

File: packages/flutter/lib/src/cupertino/context_menu.dart [hunk 1]
```diff
@@ -551,17 +554,11 @@ class _CupertinoContextMenuState extends State<CupertinoContextMenu> with Ticker
   }
 
   void _onTapCancel() {
-    _openController.removeListener(_listenerCallback);
-    if (_openController.isAnimating && _openController.value < _midpoint) {
-      _openController.reverse();
-    }
+    _onTap();
   }
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/context_menu.dart]: Nit: I have a slight worry that someone will modify _onTap without realizing that it's also the handler for tap cancel and tap up. I don't have a good solution to that though, and I think it's fine as-is. Naming is hard.

File: packages/flutter/lib/src/cupertino/context_menu.dart [hunk 2]
```diff
@@ -1406,27 +1402,141 @@ class _ContextMenuSheetState extends State<_ContextMenuSheet> {
...
       ],
-      _ContextMenuLocation.center => <Widget>[menu, const Spacer()],
-      _ContextMenuLocation.right => <Widget>[const Spacer(), menu],
-      _ContextMenuLocation.left => <Widget>[menu, const Spacer()],
-    };
+    );
   }
+}
+
+class _ContextMenuAlignedChildrenDelegate extends MultiChildLayoutDelegate {
```
Comment (justinmc) [inline packages/flutter/lib/src/cupertino/context_menu.dart:1447]: Good use of MultiChildLayoutDelegate, CupertinoContextMenu probably should have used it from the start.

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

Can you make sure the points made in https://github.com/flutter/flutter/pull/170943#issuecomment-2999415483 get captured as an issue before we forget?

Besides those small differences it looks pretty good to me. The layout seems identical now by my eye. Thanks for polishing this up.

File: packages/flutter/lib/src/cupertino/context_menu.dart (hunk 1 above)
Comment (victorsanni) [reply packages/flutter/lib/src/cupertino/context_menu.dart]: Ah... prefer revert or leave as-is?

Comment (MitchellGoodwin) [reply packages/flutter/lib/src/cupertino/context_menu.dart]: Could be really verbose and add a `_onTapCompleted` method, and have `_onTap` and the other methods call it instead. I don't have a strong opinion though, the code is all close together.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Awesome change!
