### PR TITLE
Fixes `flutter build ipa` failure: Command line name "app-store" is deprecated. Use "app-store-connect" 

### LINKED ISSUE #149369: `flutter build ipa` fails: Command line name "app-store" is deprecated. Use "app-store-connect"
```
Command line name "app-store" is deprecated. Use "app-store-connect"
```
```
[        ] executing: /usr/bin/arch -arm64e xcrun xcodebuild -exportArchive -allowProvisioningDeviceRegistration -allowProvisioningUpdates -archivePath
/Users/myuser/Documents/build/ios/archive/Runner.xcarchive -exportPath
/Users/myuser/Documents/build/ios/ipa -exportOptionsPlist
/var/folders/61/j5p5_mf17zq5lhj_dzm15s6h0000gn/T/flutter_tools.8J75rW/flutter_build_ios.TnrnSn/ExportOptions.plist
[+3686 ms] 2024-05-31 09:54:13.239 xcodebuild[19083:304649] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path
"/var/folders/61/j5p5_mf17zq5lhj_dzm15s6h0000gn/T/Runner_2024-05-31_09-54-13.239.xcdistributionlogs".
                    2024-05-31 09:54:13.343 xcodebuild[19083:304649] [MT] IDEDistribution: Command line name "app-store" is deprecated. Use "app-store-connect"
                    instead.
[        ] Building App Store IPA... (completed in 3.7s)
[        ] Encountered error while creating the IPA:
[        ] Try distributing the app in Xcode: "open /Users/weilunchen/Documents/build/ios/archive/Runner.xcarchive"
[        ] "flutter ipa" took 48,621ms.
[ +215 ms] ensureAnalyticsSent: 213ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

_Originally posted by @MarcusWlc92 in https://github.com/flutter/flutter/issues/106612#issuecomment-2141017794_

### PR DESCRIPTION
**Pull request by LouiseHsu**
Fixes https://github.com/flutter/flutter/issues/149369

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter_tools/lib/src/commands/build_ios.dart [hunk 1]
```diff
@@ -104,13 +105,17 @@ class BuildIOSArchiveCommand extends _BuildIOSSubCommand {
     argParser.addOption(
       'export-method',
       defaultsTo: 'app-store',
-      allowed: <String>['app-store', 'ad-hoc', 'development', 'enterprise'],
+      allowed: <String>['app-store', 'app-store-connect', 'ad-hoc', 'release-testing', 'development', 'debugging', 'enterprise'],
       help: 'Specify how the IPA will be distributed.',
       allowedHelp: <String, String>{
-        'app-store': 'Upload to the App Store.',
+        'app-store': 'Upload to the App Store. For XCode <= 15.3.',
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/build_ios.dart:111]: XCode is cased "Xcode". Someday I'm going to make a linter for this...
```suggestion
        'app-store': 'Upload to the App Store. For Xcode <= 15.3.',
```

File: packages/flutter_tools/lib/src/commands/build_ios.dart [hunk 2]
```diff
@@ -104,13 +105,17 @@ class BuildIOSArchiveCommand extends _BuildIOSSubCommand {
...
+        'app-store-connect': 'Upload to the App Store. For XCode > 15.3',
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/build_ios.dart:112]: Let's leave off the >15.3.

```suggestion
        'app-store-connect': 'Upload to the App Store.',
```

File: packages/flutter_tools/lib/src/commands/build_ios.dart [hunk 3]
```diff
@@ -104,13 +105,17 @@ class BuildIOSArchiveCommand extends _BuildIOSSubCommand {
     argParser.addOption(
       'export-method',
       defaultsTo: 'app-store',
-      allowed: <String>['app-store', 'ad-hoc', 'development', 'enterprise'],
+      allowed: <String>['app-store', 'app-store-connect', 'ad-hoc', 'release-testing', 'development', 'debugging', 'enterprise'],
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/build_ios.dart:108]: This pile is really confusing.  Can we keep the old allowed list as-is, but pass the right thing into Xcode based on the version?

Comment (LouiseHsu) [reply packages/flutter_tools/lib/src/commands/build_ios.dart]: makes sense, done!

File: packages/flutter_tools/lib/src/commands/build_ios.dart (hunk 2 above)
Comment (LouiseHsu) [reply packages/flutter_tools/lib/src/commands/build_ios.dart]: removed the other options so i also removed the xcode part of the help, since not relevant anymore

File: packages/flutter_tools/lib/src/commands/build_ios.dart [hunk 4]
```diff
@@ -577,6 +578,29 @@ class BuildIOSArchiveCommand extends _BuildIOSSubCommand {
...
+  // and 'debugging'.
+  String _getVersionAppropriateExportMethod(String method) {
+    final Version? currVersion = globals.xcode!.currentVersion;
+    if (currVersion != null) {
+      if (currVersion.major >= 16 || (currVersion.major == 15 && currVersion.minor > 3)) {
+        switch (method) {
+          case 'app-store':
+            return 'app-store-connect';
+          case 'ad-hoc':
+            return 'release-testing';
```
Comment (jmagman) [inline packages/flutter_tools/lib/src/commands/build_ios.dart:593]: Can you add tests for this?
https://github.com/flutter/flutter/blob/d4cffa25402d9a26d4eeee7704e69b0cda4a7da8/packages/flutter_tools/test/commands.shard/hermetic/build_ipa_test.dart#L618-L619

File: packages/flutter_tools/test/commands.shard/hermetic/build_ipa_test.dart [hunk 5]
```diff
@@ -46,6 +46,15 @@ class FakeXcodeProjectInterpreterWithBuildSettings extends FakeXcodeProjectInter
       'DEVELOPMENT_TEAM': 'abc',
     };
   }
+
+  Version _version = Version(14, 0, 0);
```
Comment (jmagman) [inline packages/flutter_tools/test/commands.shard/hermetic/build_ipa_test.dart:50]: I think it would be cleaner to add to the constructor:
```dart
  FakeXcodeProjectInterpreterWithBuildSettings({
    this.overrides = const <String, String>{},
    Version? version,
  }) : version = version ?? Version(14, 0, 0);
...
  @override
  final Version version;
```

**Comment by saumon** [comment]
🙏

File: packages/flutter_tools/lib/src/commands/build_ios.dart [hunk 6]
```diff
@@ -577,6 +578,29 @@ class BuildIOSArchiveCommand extends _BuildIOSSubCommand {
...
     return tempPlist;
   }
+
+  // As of Xcode 15.4, the old export methods 'app-store', 'ad-hoc', and 'development'
+  // are now deprecated. The new equivalents are 'app-store-connect', 'release-testing',
+  // and 'debugging'.
+  String _getVersionAppropriateExportMethod(String method) {
+    final Version? currVersion = globals.xcode!.currentVersion;
+    if (currVersion != null) {
+      if (currVersion.major >= 16 || (currVersion.major == 15 && currVersion.minor > 3)) {
```
[the remark this answers is not in the document]
Comment (LouiseHsu) [reply packages/flutter_tools/lib/src/commands/build_ios.dart]: ooh i missed that

File: packages/flutter_tools/test/commands.shard/hermetic/build_ipa_test.dart (hunk 5 above)
Comment (LouiseHsu) [reply packages/flutter_tools/test/commands.shard/hermetic/build_ipa_test.dart]: done

File: packages/flutter_tools/lib/src/commands/build_ios.dart (hunk 4 above)
Comment (LouiseHsu) [reply packages/flutter_tools/lib/src/commands/build_ios.dart:593]: done

**Review by jmagman — APPROVED** [review]

**Comment by jmagman** [comment]
Took the liberty to rebase on main since there shouldn't be golden changes on this PR.

**Comment by LouiseHsu** [comment]
> Golden file changes have been found for this pull request. Click [here to view and triage](https://flutter-gold.skia.org/cl/github/150407) (e.g. because this is an intentional change).
> 
> If you are still iterating on this change and are not ready to resolve the images on the Flutter Gold dashboard, consider marking this PR as a draft pull request above. You will still be able to view image results on the dashboard, commenting will be silenced, and the check will not try to resolve itself until marked ready for review.
> 
> For more guidance, visit [Writing a golden file test for `package:flutter`](https://github.com/flutter/flutter/blob/master/docs/contributing/testing/Writing-a-golden-file-test-for-package-flutter.md).
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.
> 
> _Changes reported for pull request #150407 at sha [d9fb228](https://github.com/flutter/flutter/commit/d9fb22825835b16b58537b2dca19a42214e8eef8)_

@jmagman what

> Took the liberty to rebase on main since there shouldn't be golden changes on this PR.

thank youuuuuuuu

**Comment by jmagman** [comment]
> auto label is removed for flutter/flutter/150407, due to - The status or check suite [Linux analyze](https://cr-buildbucket.appspot.com/build/8744032390138579057) has failed. Please fix the issues identified (or deflake) before re-applying this label.

Rebased onto https://github.com/flutter/flutter/pull/150882
