### PR TITLE
Fix GTK redraw call being called from non-GTK thread.

### LINKED ISSUE #173447: Linux desktop app just stops updating its window after a while
### Steps to reproduce

Run the code below using `flutter run -d linux` and wait up to 15 minutes (usually a lot less, sometimes less than 10 seconds). All the code does is show a timer on the screen.

### Expected results

There should be a counter that increases forever.

### Actual results

The timer eventually just appears to hang.

In practice (as tested via debugger), the Dart part of the application is continuing to work fine. It's just the window that isn't updating.

### Code sample

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final DateTime _start = DateTime.now();
  
  @override
  Widget build(BuildContext context) {
    scheduleMicrotask(() { setState(() { /* rebuild */ }); });
    return Center(
      child: Text(
        '${DateTime.now().millisecondsSinceEpoch - _start.millisecondsSinceEpoch}ms',
        textDirection: TextDirection.ltr,
      ),
    );
  }
}
```

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.33.0-1.0.pre-1324, on Ubuntu 24.04.1 LTS 6.8.0-58-generic, locale C.UTF-8) [61ms]
    ! Flutter version 3.33.0-1.0.pre-1324 on channel [user-branch] at /home/ianh/dev/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 796c62bd76 (2 hours ago), 2025-08-07 15:42:16 -0700
    • Engine revision 9264b70f24
    • Dart version 3.10.0 (build 3.10.0-75.1.beta)
    • DevTools version 2.49.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [1,762ms]
    • Android SDK at /home/ianh/Android/Sdk
    • Emulator version 31.3.13.0 (build_id 9189900) (CL:N/A)
    ✗ Flutter requires Android SDK 36 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/to/linux-android-setup for detailed instructions.
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web [16ms]
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop [529ms]
    • Ubuntu clang version 18.1.3 (1ubuntu1)
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 1.8.1
    • OpenGL core renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 (X11)
    • OpenGL core version: 4.6.0 NVIDIA 550.120 (X11)
    • OpenGL core shading language version: 4.60 NVIDIA (X11)
    • OpenGL ES renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 (X11)
    • OpenGL ES version: OpenGL ES 3.2 NVIDIA 550.120 (X11)
    • OpenGL ES shading language version: OpenGL ES GLSL ES 3.20 (X11)
    • GL_EXT_framebuffer_blit: yes (X11)
    • GL_EXT_texture_format_BGRA8888: yes (X11)

[✓] Connected device (2 available) [151ms]
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 24.04.1 LTS 6.8.0-58-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 136.0.7103.59

[✓] Network resources [196ms]
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

While I'm at it:
```
ianh@burmese:~$ sudo X -version
X.Org X Server 1.21.1.11
X Protocol Version 11, Revision 0
Current Operating System: Linux burmese 6.8.0-58-generic #60-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 14 18:29:48 UTC 2025 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.8.0-58-generic root=UUID=dc31e344-a73b-4584-9bbb-d412fe845c85 ro
xorg-server 2:21.1.12-1ubuntu1.4 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.42.2
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
```

</details>

### PR DESCRIPTION
**Pull request by robert-ancell**
gtk_widget_queue_draw is not thread-safe, call it from an idle callback.

Fixes https://github.com/flutter/flutter/issues/173447

### CODE REVIEW

**Comment by robert-ancell** [comment]
The fix was found by enabling tsan in the Flutter engine build. It also showed some potential issues coming from the Linux task runner, which I will investigate in the future.

File: engine/src/flutter/shell/platform/linux/fl_view.cc [hunk 1]
```diff
@@ -247,14 +251,7 @@ static void fl_view_present_layers(FlRenderable* renderable,
...
 
-  gtk_widget_queue_draw(GTK_WIDGET(self->render_area));
-
-  if (!self->have_first_frame) {
-    self->have_first_frame = TRUE;
-    // This is not the main thread, so the signal needs to be done via an idle
-    // callback.
-    g_idle_add(first_frame_idle_cb, self);
-  }
+  g_idle_add(redraw_cb, self);
```
Comment (mattkae) [inline engine/src/flutter/shell/platform/linux/fl_view.cc:256]: Nit: Consider leaving a comment here explaining why this is necessary. This would look like a weird bit of indirection to me :)

**Review by mattkae — APPROVED** [review]
Just a thought, but feel free to merge!

File: engine/src/flutter/shell/platform/linux/fl_view.cc (hunk 1 above)
Comment (jtmcdole) [reply engine/src/flutter/shell/platform/linux/fl_view.cc:256]: +1  - it would be bad to have this changed back.

Do we have a test that can verify this is called?

**Comment by mattkae** [comment]
Also - I tested and it works well for me!

CC: @loic-sharma

**Comment by stuartmorgan-g** [comment]
test-exempt: unblocks enabling tooling that catches it

File: engine/src/flutter/shell/platform/linux/fl_view.cc (hunk 1 above)
Comment (robert-ancell) [reply engine/src/flutter/shell/platform/linux/fl_view.cc:256]: We don't currently have a test, I've opened https://github.com/flutter/flutter/issues/173660 to add tests for this and all other GTK cases.

**Comment by camsim99** [comment]
@robert-ancell @loic-sharma We'll need to manually CP this to https://github.com/flutter/flutter/tree/flutter-3.35-candidate.0. Can one of you help out here? Thanks!

**Comment by robert-ancell** [comment]
@camsim99 - cherry pick in https://github.com/flutter/flutter/pull/173667

**Comment by robert-ancell** [comment]
And cherry pick for 3.36 branch as requested by @loic-sharma in https://github.com/flutter/flutter/pull/173669
