### PR TITLE
Fixed XiaoMi statusBar Bug

### LINKED ISSUE #132831: A bug about statusbar‘s height  in the multi window on Xiaomi phone
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

on Xiaomi Phone

1.change from full screen to multi screen

### Expected results

statusbar’s height is not 0

on Xiaomi phone，when app in multi window，the [captionBar](https://developer.android.com/reference/android/view/WindowInsets.Type?hl=en#captionBar()).top is not 0 and statusbar.top is 0，but FlutterView only used [statusBar](https://github.com/flutter/engine/blob/2f9a4ef0370afe9452abc927be75a904c0cddc56/shell/platform/android/io/flutter/view/FlutterView.java#L591C59-L591C59)，this may cause bugs！

from full screen to multi screen
app in multi window

### Actual results

statusbar’s height is 0，the line in statusbar shade appbar

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
        appBarTheme: const AppBarTheme(
          centerTitle: true
        )
      ),
      home: const MyHomePage(title: 'Flutter示例'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/18473359/c31842ed-0242-422e-bd01-8feaadacc75e

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.6, on macOS 12.6.1 21G217 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.10.6 on channel stable at /Users/bin_ren/.fvm/versions/3.10.6
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/bin_ren/.fvm/versions/3.10.6. Consider adding /Users/bin_ren/.fvm/versions/3.10.6/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/bin_ren/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/bin_ren/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • M2101K9C (mobile) • a0f0e393 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos    • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm64
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 115.0.5790.170
```

</details>

### PR DESCRIPTION
**Pull request by jesswrd**
Updated usages of statusBar() to systemBar() to fix XiaoMi statusBar bug. 

Fixes #132831 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java [hunk 1]
```diff
@@ -694,7 +694,7 @@ public final WindowInsets onApplyWindowInsets(@NonNull WindowInsets insets) {
         mask = mask | android.view.WindowInsets.Type.navigationBars();
       }
       if (statusBarVisible) {
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java:696]: Consider renaming this variable

File: engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java [hunk 2]
```diff
@@ -319,7 +319,7 @@ public void reportSystemInsetWhenNotFullscreen() {
         new WindowInsets.Builder()
             .setInsets(
                 android.view.WindowInsets.Type.navigationBars()
-                    | android.view.WindowInsets.Type.statusBars(),
+                    | android.view.WindowInsets.Type.systemBars(),
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java:322]: Should we  add a test that sets the statusbars insets to something other than 100. To make sure we are using systemBars instead of status bars?

**Comment by reidbaker** [comment]
Looking at this documentation here again the difference is that systemBars does not include ime https://developer.android.com/reference/android/view/WindowInsets.Type#ime()

I think our code might actually be correct in that we want input types as well. Is it possible to verify that this change actually fixes the issue the XiaoMi user was seeing? My first past on the documentation makes me think this cant add any inset that would allow us to inset correctly.

**Review by reidbaker — CHANGES_REQUESTED** [review]

**Comment by reidbaker** [comment]
> Looking at this documentation here again the difference is that systemBars does not include ime https://developer.android.com/reference/android/view/WindowInsets.Type#ime()
> 
> I think our code might actually be correct in that we want input types as well. Is it possible to verify that this change actually fixes the issue the XiaoMi user was seeing? My first past on the documentation makes me think this cant add any inset that would allow us to inset correctly.

@jesswrd and I looked at this yesterday. An internal doc states that to support edge to edge we need to move usage of statusBars to systemBars so that is what we will do. There is code that handles status bars only if they are visible and a straight replacement would invalidate some of that code so @jesswrd is going to add tests for that behavior and we are going to make sure we dont regress a non full screen inset logic when we fix the support for xiaomi (which is a broader bug impacting more devices but this gave us an easy to reproduce case). 

I believe the actual code level issue is not including systemOverlays.

File: engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java [hunk 3]
```diff
@@ -330,6 +330,86 @@ public void reportSystemInsetWhenNotFullscreen() {
     validateViewportMetricPadding(viewportMetricsCaptor, 100, 100, 100, 100);
   }
 
+  @SuppressWarnings("deprecation")
+  // getSystemUiVisibility
+  // This test uses the API 30+ Algorithm for window insets. This test requires API 34 or
+  // higher to use the systemOverlays inset. The legacy algorithm is
+  // set to -1 values, so it is clear if the wrong algorithm is used.
```
Comment (reidbaker) [inline engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java:337]: Great comment helping explain the test!

File: engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java [hunk 4]
```diff
@@ -330,6 +330,86 @@ public void reportSystemInsetWhenNotFullscreen() {
...
+  @Test
+  @TargetApi(34)
+  @Config(sdk = 34)
```
[the remark this answers is not in the document]
Comment (jesswrd) [reply engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java:340]: done

File: engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java [hunk 5]
```diff
@@ -330,6 +330,86 @@ public void reportSystemInsetWhenNotFullscreen() {
...
+  public void reportSystemInsetWhenNotFullscreenForSystemBar() {
+    // Without custom shadows, the default system ui visibility flags is 0.
+    FlutterView flutterView = new FlutterView(ctx);
+    assertEquals(0, flutterView.getSystemUiVisibility());
+
+    FlutterEngine flutterEngine = spy(new FlutterEngine(ctx, mockFlutterLoader, mockFlutterJni));
+    FlutterRenderer flutterRenderer = spy(new FlutterRenderer(mockFlutterJni));
+    when(flutterEngine.getRenderer()).thenReturn(flutterRenderer);
+
+    // When we attach a new FlutterView to the engine without any system insets, the viewport
```
[the remark this answers is not in the document]
Comment (jesswrd) [reply engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java:350]: done

File: engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java [hunk 6]
```diff
@@ -330,6 +330,86 @@ public void reportSystemInsetWhenNotFullscreen() {
...
+    WindowInsets statusBarwindowInsets =
+        new WindowInsets.Builder()
+            .setInsets(android.view.WindowInsets.Type.captionBar(), Insets.of(0, 50, 0, 0))
+            .setInsets(android.view.WindowInsets.Type.statusBars(), Insets.of(0, 100, 0, 0))
+            .build();
+    flutterView.onApplyWindowInsets(statusBarwindowInsets);
+
+    // Verify.
+    verify(flutterRenderer, times(3)).setViewportMetrics(viewportMetricsCaptor.capture());
+    // Confirm that the statusBar inset is used because it is greater.
```
[the remark this answers is not in the document]
Comment (jesswrd) [reply engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java:369]: done

File: engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java [hunk 7]
```diff
@@ -330,6 +330,86 @@ public void reportSystemInsetWhenNotFullscreen() {
...
+    validateViewportMetricPadding(viewportMetricsCaptor, 0, 100, 0, 0);
+    clearInvocations(flutterRenderer);
+
+    // Then we simulate the system applying a window inset.
```
[the remark this answers is not in the document]
Comment (jesswrd) [reply engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java:373]: done

**Review by reidbaker — APPROVED** [review]

File: engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java (hunk 1 above)
Comment (jesswrd) [reply engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java]: deleted the masking code and using systemBars instead

File: engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java (hunk 2 above)
Comment (jesswrd) [reply engine/src/flutter/shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java]: done
