### PR TITLE
Started bridging the scene delegate to the lifecycle delegate for shortcuts

### LINKED ISSUE #169928: [iOS] Quick Actions Not Triggered When App is in Background
### Steps to reproduce

❗ Description
On iOS, when the app is in the background, tapping on a registered Quick Action does not execute the expected logic. However, the same Quick Action works correctly when:

- The app is terminated
- The app is in any state on Android

To reproduce: 

1. Install and configure quick_actions package
2. Register Quick Actions in main()
3. Run app on iOS
4. Put app in background (press home button or swipe)
5. Trigger a Quick Action from the home screen icon
6. Observe: app resumes, but no logic is executed

### Expected results

Quick Actions should trigger the registered handler and perform the corresponding action even when the app is in the background.

### Actual results

On iOS:

App resumes (comes to foreground) but the Quick Action callback is not invoked.

No navigation or logic tied to the action is triggered.

On Android:

Quick Actions work perfectly regardless of app state (background, foreground, or terminated).

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:quick_actions/quick_actions.dart';

import 'src/presentation/features/auth/pages/login_screen.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late final QuickActions actions;

  @override
  void initState() {
    actions = QuickActions();
    actions.initialize((type) {
      switch (type) {
        case 'action_one':
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Action One Triggered')),
          );
          break;
        case 'action_two':
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Action Two Triggered')),
          );
          break;
        default:
          break;
      }
    });
    actions.setShortcutItems([
      const ShortcutItem(type: 'action_one', localizedTitle: 'Action One', icon: 'icon_one'),
      const ShortcutItem(type: 'action_two', localizedTitle: 'Action Two', icon: 'icon_two'),
    ]);
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.red),
        useMaterial3: true,
      ),
      home: const LoginScreen(),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.24.5, on macOS 15.4.1 24E263 darwin-arm64, locale fr-MG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Android Studio (version 2024.3)
[✓] VS Code (version 1.100.2)```

</details>

### PR DESCRIPTION
**Pull request by gaaclarke**
testing: There integration tests in the plugins repo.
fixes: https://github.com/flutter/flutter/issues/169928

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate_Internal.h [hunk 1]
```diff
@@ -6,9 +6,12 @@
 #define FLUTTER_SHELL_PLATFORM_DARWIN_IOS_FRAMEWORK_SOURCE_FLUTTERAPPDELEGATE_INTERNAL_H_
 
 #import "flutter/shell/platform/darwin/ios/framework/Headers/FlutterAppDelegate.h"
+#import "flutter/shell/platform/darwin/ios/framework/Headers/FlutterEngine.h"
+#import "flutter/shell/platform/darwin/ios/framework/Headers/FlutterPluginAppLifeCycleDelegate.h"
 
 @interface FlutterAppDelegate ()
 
+@property(nonatomic, strong, nullable) FlutterPluginAppLifeCycleDelegate* lifeCycleDelegate;
```
Comment (jmagman) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate_Internal.h]: keep the readwrite implementation property as-is, add `readonly` to this.

Comment (gaaclarke) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate_Internal.h]: I removed the direct usage of the lifecycle delegate and instead started calling directly into the app delegate as we discussed in our meeting.  That's a bit more scary but I think it technically is the safer thing to do.

**Comment by gaaclarke** [comment]
quick actions tested locally (since the test won't run as part of presubmit), it works:

Screenshot 2025-06-06 at 3 16 22 PM

**Review by hellohuanlin — COMMENTED** [review]
looks reasonable. can we add some unit tests?

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate_Internal.h (hunk 1 above)
Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate_Internal.h]: could you share a bit more details (for me and future readers) on app delegate vs life cycle delegate decision? Thx!

**Comment by gaaclarke** [comment]
> looks reasonable. can we add some unit tests?

We have integration tests.  We can't add unit tests because it relies on the application delegate being a FlutterAppDelegate which we don't support in our unit test harness.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate_Internal.h (hunk 1 above)
Comment (gaaclarke) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate_Internal.h]: Jenn pointed out that users could be subclassing FlutterAppDelegate and override `application:performActionForShortcutItem:completionHandler:` and be performing their own logic, like say analytics for the usage of shortcuts.

Talking directly the the lifecycle delegate would break them, but fix the plugin problems.  So, I decided to call the delegate directly.

**Comment by hellohuanlin** [comment]
> We can't add unit tests because it relies on the application delegate being a FlutterAppDelegate which we don't support in our unit test harness.

Could you explain more? `OCMock` should be able to mock the app delegate (I may misunderstand the problem tho). 

```
id mockApplication = OCMClassMock([UIApplication class]);
OCMStub([mockApplication shared]).andReturn(mockApplication);
id mockAppDelegate = OCMClassMock([FlutterAppDelegate class]);
OCMStub([mockApplication delegate]).andReturn(mockApplication)
```

**Comment by gaaclarke** [comment]
> Could you explain more? `OCMock` should be able to mock the app delegate (I may misunderstand the problem tho).

Thanks, I forgot you could mock like that.  Done.

**Comment by gaaclarke** [comment]
rerunning [Linux gradle_plugin_fat_apk_test](https://cr-buildbucket.appspot.com/build/8712506355503276049), issue filed

**Comment by gaaclarke** [comment]
@hellohuanlin friendly ping

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m [hunk 2]
```diff
@@ -29,4 +30,15 @@ - (void)scene:(UIScene*)scene
...
 }
 
+- (void)windowScene:(UIWindowScene*)windowScene
+    performActionForShortcutItem:(UIApplicationShortcutItem*)shortcutItem
+               completionHandler:(void (^)(BOOL succeeded))completionHandler {
+  NSObject<UIApplicationDelegate>* appDelegate = FlutterSharedApplication.application.delegate;
+  if ([appDelegate isKindOfClass:[FlutterAppDelegate class]]) {
+    [appDelegate application:FlutterSharedApplication.application
+        performActionForShortcutItem:shortcutItem
+                   completionHandler:completionHandler];
```
Comment (hellohuanlin) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:41]: If we do it for one method, we should probably do it for all methods for minimal surprise.

**Review by hellohuanlin — COMMENTED** [review]
I have some concerns around relaying scene delegate calls to app delegate, mainly the fact that we are changing Apple's behavior that may surprise us in the future. See more details here: https://github.com/flutter/flutter/issues/170037#issuecomment-2954475534

If there's no other way around, I'm fine with relaying the calls, but just wanna hear your thoughts on it first.

**Comment by AquaGeek** [comment]
> I have some concerns around relaying scene delegate calls to app delegate, mainly the fact that we are changing Apple's behavior that may surprise us in the future. See more details here: [#170037 (comment)](https://github.com/flutter/flutter/issues/170037#issuecomment-2954475534)
> 
> If there's no other way around, I'm fine with relaying the calls, but just wanna hear your thoughts on it first.

I agree. This feels like the kind of thing that addresses the short-term pain of everyone having to move their code to the scene delegate (or add the relay to their own code) but will create headaches long-term. I would much rather see Flutter take the stance that code should be moved to align with platform expectations.

Another approach would be to spin up a subclass that does the relaying. Teams that _don't want_ that functionality would simply use the superclass instead.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m (hunk 2 above)
Comment (gaaclarke) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:41]: This method is special where apple has specifically called out that they will not call the old app delegate method.  Things like "will resign active" are still called.  The goal of this PR is to fix broken behavior.

**Comment by gaaclarke** [comment]
> but will create headaches long-term.

@AquaGeek what headaches are you thinking of?  Can you explain further?

**Comment by gaaclarke** [comment]
> I have some concerns around relaying scene delegate calls to app delegate, mainly the fact that we are changing Apple's behavior that may surprise us in the future. See more details here: [#170037 (comment)](https://github.com/flutter/flutter/issues/170037#issuecomment-2954475534)
> 
> If there's no other way around, I'm fine with relaying the calls, but just wanna hear your thoughts on it first.

@hellohuanlin What do you see the alternative being?

Here's the options I see:
1) Update the migration guide
1) Bridge FlutterSceneDelegate to FlutterAppDelegate (current state of PR)
1) Duplicate the logic from FlutterAppDelegate in FlutterSceneDelegate (original state of PR)

We chose to do 2 because 3 could end up breaking users without any runtime help.  I'm not quite sure what the problem we are trying to avoid is.  I think there is just a general sense that maybe something bad can happen, but I couldn't think of one.  All of this happens under the hood and we can swap it around if we want.

**Comment by hellohuanlin** [comment]
> I think there is just a general sense that maybe something bad can happen, but I couldn't think of one. 

This resonate with my last paragraph in https://github.com/flutter/flutter/issues/170037#issuecomment-2954475534

> Here's the options I see...

Maybe it is the **least worst** option we have (unless we can think of a better option?)

I'm not against this. I just wanna make sure we are aware of this departure of apple's practice, and get it well documented if we do so.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m (hunk 2 above)
Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:41]: > Things like "will resign active" are still called. 

IIRC from my experiment a few days ago, "will resign active" are not called

Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:41]: Same as "background/foreground" callbacks (there are some discussions around it a few days ago in the chat channel)

Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:41]: Related: https://github.com/flutter/flutter/issues/170178

Comment (gaaclarke) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:41]: I think we should be test driven.  I don't think we have any failing tests related to resign active.  We should double check, but I think that should be addressed in a different PR.

Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:41]: also reported in https://github.com/flutter/flutter/issues/170037

Comment (hellohuanlin) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterSceneDelegate.m:41]: > I think that should be addressed in a different PR.

Either way sounds good to me. I just wanna have a consistent behavior - if we relay 1 call, we should relay all similar calls.

**Comment by gaaclarke** [comment]
I switched back to talking the the lifecycle delegate directly.  While I think in general we should make our decisions based on concrete concerns and tests, not calling the FlutterAppDelegate isn't technically a breaking change even if it can break some customers.  So, I'm fine doing the more reserved solution of talking to the delegate directly.

Keeping the logic inline with Apple's will be more understandable at least for the odd scenarios where it may matter.

**Comment by hellohuanlin** [comment]
What do you think about we firstly start with relaying the calls, and adding the warning in tooling against app delegate usage (apple's deprecation warning isn't sufficient as we discussed yesterday), and then remove the relay in the future? This allows a smoother transition for developers.

**Comment by gaaclarke** [comment]
> What do you think about we firstly start with relaying the calls, and adding the warning in tooling against app delegate usage (apple's deprecation warning isn't sufficient as we discussed yesterday), and then remove the relay in the future? This allows a smoother transition for developers.

I don't think it's necessary.  The people this effects is low, there is no longer an automatic migration and and it's not a Breaking Change.  I think that will just complicate the migration.  Who knows what decision will be made in the future but migrating may never be an automatic thing considering the events of the last few days.  I plan on filing an issue for the static warning like we discussed yesterday as part of resolving this PR, so that idea doesn't get lost.

**Comment by hellohuanlin** [comment]
Sounds good. I think i'm comfortable with this. Before stamping this, @jmagman FYI this reverts to the original implementation that you had concerns: https://github.com/flutter/flutter/pull/170180#discussion_r2133075625

**Review by hellohuanlin — APPROVED** [review]
LGTM!
