### PR TITLE
fix ReorderableList not passing in item extent builder

### LINKED ISSUE #155936: ReorderableList does not pass itemExtentBuilder to underlying SliverReorderableList
### Steps to reproduce

1. Use `ReorderableList` widget similar to how you would use `ListView.builder`, utilizing the `itemExtentBuilder` parameter to set item extent.
2. Observe that `itemExtentBuilder` is ignored and the list does not behave as expected when compared to `ListView.builder` or when using `prototypeItem` or `itemExtent`.

### Expected results

The `ReorderableList` should pass the `itemExtentBuilder` parameter to the underlying `SliverReorderableList`, similar to how `itemExtent` and `prototypeItem` are already handled.

### Actual results

Currently, `itemExtentBuilder` is not passed to the `SliverReorderableList` in `ReorderableListState`'s build method, which causes it to be ignored.

### Code sample

<details open><summary>Code sample</summary>

```dart

class MyScrollList extends StatelessWidget {
  const MyScrollList({super.key});

  @override
  Widget build(BuildContext context) {
    return ReorderableList(
      // This works
      // itemExtent: 50,

      // This works
      // prototypeItem: const SizedBox(height: 50),

      // This does not work
      itemExtentBuilder: (index, dimensions) {
        return 50;
      },
      onReorder: (oldIndex, newIndex) {
        // ...
      },
      itemCount: 5,
      itemBuilder: (context, index) {
        return Container(
          key: ValueKey('item$index'),
          child: Text('Item $index'),
        );
      },
    );
  }
}
```

</details>

<details open><summary>Proposed fix sample</summary>

```dart

class ReorderableListState extends State<ReorderableList> {

// ...

@override
  Widget build(BuildContext context) {
    return CustomScrollView(
      scrollDirection: widget.scrollDirection,
      reverse: widget.reverse,
      controller: widget.controller,
      primary: widget.primary,
      physics: widget.physics,
      shrinkWrap: widget.shrinkWrap,
      anchor: widget.anchor,
      cacheExtent: widget.cacheExtent,
      dragStartBehavior: widget.dragStartBehavior,
      keyboardDismissBehavior: widget.keyboardDismissBehavior,
      restorationId: widget.restorationId,
      clipBehavior: widget.clipBehavior,
      slivers: <Widget>[
        SliverPadding(
          padding: widget.padding ?? EdgeInsets.zero,
          sliver: SliverReorderableList(
            key: _sliverReorderableListKey,
            itemExtent: widget.itemExtent,
            prototypeItem: widget.prototypeItem,
            // Add this line:
            itemExtentBuilder: widget.itemExtentBuilder,
            itemBuilder: widget.itemBuilder,
            itemCount: widget.itemCount,
            onReorder: widget.onReorder,
            onReorderStart: widget.onReorderStart,
            onReorderEnd: widget.onReorderEnd,
            proxyDecorator: widget.proxyDecorator,
            autoScrollerVelocityScalar: widget.autoScrollerVelocityScalar,
          ),
        ),
      ],
    );
  }

// ...

}
```
</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-BR)
    • Flutter version 3.24.3 on channel stable at /Users/andrelbc/Dev/Flutter/Sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc4)
    • Android SDK at /Users/andrelbc/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] VS Code (version 1.89.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPad mini (6th generation) (mobile) • 17517532-9DFB-46FA-AA12-4DA1BC650870 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    • Mac Designed for iPad (desktop)     • mac-designed-for-ipad                • darwin         • macOS 14.6.1 23G93 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 129.0.6668.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by navaronbracke**
This PR fixes the `ReorderableList` in `flutter/widgets.dart` not passing the item extent builder to the underlying SliverReorderableList. I double checked and the material equivalent is working as intended.

Fixes https://github.com/flutter/flutter/issues/155936

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by QuncCccccc — COMMENTED** [review]
Thanks a lot for the contribution! Just have one comment in the unit test:)

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 1]
```diff
@@ -923,6 +923,52 @@ void main() {
...
+    );
+
+    const Map<int, double> expectedExtents = <int, double>{
+      0: 10.0,
+      1: 20.0,
+      2: 30.0,
+      3: 40.0,
+      4: 50.0,
+    };
+
```
Comment (QuncCccccc) [inline packages/flutter/test/widgets/reorderable_list_test.dart:968]: I think getting the size for each child and comparing them would be more straightforward:) Like this(I modified your test a little bit):

```dart
testWidgets('ReorderableList passes itemExtentBuilder to SliverReorderableList', (WidgetTester tester) async {
    // Regression test for https://github.com/flutter/flutter/issues/155936
    const int itemCount = 5;
    const List<double> items = <double>[10.0, 20.0, 30.0, 40.0, 50.0];
    final Map<int, double> itemExtents = <int, double>{};

    void handleReorder(int fromIndex, int toIndex) {
      if (toIndex > fromIndex) {
        toIndex -= 1;
      }
      items.insert(toIndex, items.removeAt(fromIndex));
    }

    // The list has five elements, that indicate the extent for the item at the given index.
    await tester.pumpWidget(
      MaterialApp(
        home: ReorderableList(
          itemBuilder: (BuildContext context, int index) => SizedBox(
            key: ValueKey<double>(items[index]),
            child: Text('Item $index'),
          ),
          itemCount: itemCount,
          onReorder: handleReorder,
          itemExtentBuilder: (int index, SliverLayoutDimensions dimensions) {
            return items[index];
          },
        ),
      ),
    );

    const Map<int, double> expectedExtents = <int, double>{
      0: 10.0,
      1: 20.0,
      2: 30.0,
      3: 40.0,
      4: 50.0,
    };

    for (int i = 0; i < itemCount; i++) {
      itemExtents[i] = tester.getSize(find.text('Item $i')).height;
    }
    expect(const MapEquality<int, double>().equals(itemExtents, expectedExtents), isTrue);
  });
```

Comment (navaronbracke) [reply packages/flutter/test/widgets/reorderable_list_test.dart:962]: Done. I also moved the declaration of `itemExtents` to just before the expect, as we can initialize it using a for-literal, using your suggestion as the body for the literal :)

**Review by QuncCccccc — APPROVED** [review]
LGTM:)! Thanks for the contribution!

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 2]
```diff
@@ -923,6 +923,51 @@ void main() {
...
+    const List<double> items = <double>[10.0, 20.0, 30.0, 40.0, 50.0];
+
+    void handleReorder(int fromIndex, int toIndex) {
+      if (toIndex > fromIndex) {
+        toIndex -= 1;
+      }
+      items.insert(toIndex, items.removeAt(fromIndex));
+    }
+
+    // The list has five elements, that indicate the extent for the item at the given index.
```
Comment (dkwingsmt) [inline packages/flutter/test/widgets/reorderable_list_test.dart:938]: I suggest removing this comment (it seems to have some grammar issues as well) and rename `items` to something more readable such as `itemExtents`.

**Review by dkwingsmt — APPROVED** [review]
LGTM except for the readability suggestion
