### PR TITLE
Rebuilding BottomNavigationBar when items.length changes

### LINKED ISSUE #10322: BottomNavigationBar can't handle the number of items changing dynamically
## Steps to Reproduce

Take the following app:
``` dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(title: const Text("Door Manager")),
      bottomNavigationBar: new BottomNavigationBar(
          items: new List.generate(2, (i) {  // <================== 2 to 3
            return new BottomNavigationBarItem(
                icon: new Icon(Icons.bug_report), title: new Text("$i"));
          }),
          currentIndex: _currentIndex,
          onTap: (int index) {
            setState(() {
              _currentIndex = index;
            });
          }),
      body: const Text("foo"),
    );
  }
}
```

1. Start the app on the phone.
2. Change the marked line from 2 to 3
3. Press hot reload.

The app crashes. No hot-reload will fix the issue. From a user's perspective it looks like there is a bug in the code.

## Logs
```
$ flutter run
Launching lib/main.dart on Pixel in debug mode...
Running 'gradle assembleDebug'...                     8.8s
Built build/app/outputs/apk/app-debug.apk (21.5MB).
Installing build/app/outputs/apk/app.apk...           6.5s
Syncing files to device Pixel...                      4.7s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Pixel is available at: http://127.0.0.1:8108/
For a more detailed help message, press "h". To quit, press "q".

Initializing hot reload...                                
I/flutter ( 2938): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 2938): The following RangeError was thrown building BottomNavigationBar(dirty; state:
I/flutter ( 2938): _BottomNavigationBarState#321338430(tracking 2 tickers)):
I/flutter ( 2938): RangeError (index): Invalid value: Not in range 0..1, inclusive: 2
I/flutter ( 2938): 
I/flutter ( 2938): When the exception was thrown, this was the stack:
I/flutter ( 2938): #0      List.[] (dart:core-patch/growable_array.dart:151)
I/flutter ( 2938): #1      _BottomNavigationBarState.build (package:flutter/src/material/bottom_navigation_bar.dart:336:49)
I/flutter ( 2938): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3241:27)
I/flutter ( 2938): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3151:15)
I/flutter ( 2938): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #5      StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #9      ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #11     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3826:32)
I/flutter ( 2938): #12     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4208:17)
I/flutter ( 2938): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #16     ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #20     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #26     StatelessElement.update (package:flutter/src/widgets/framework.dart:3213:5)
I/flutter ( 2938): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #40     ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #44     ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #48     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #52     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #60     StatelessElement.update (package:flutter/src/widgets/framework.dart:3213:5)
I/flutter ( 2938): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #68     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #72     StatelessElement.update (package:flutter/src/widgets/framework.dart:3213:5)
I/flutter ( 2938): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #76     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #80     ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #86     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #90     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #94     StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #96     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3826:32)
I/flutter ( 2938): #97     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4208:17)
I/flutter ( 2938): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #99     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 2938): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #103    StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #107    ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #113    StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #117    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #121    StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #125    StatelessElement.update (package:flutter/src/widgets/framework.dart:3213:5)
I/flutter ( 2938): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #128    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #129    ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #133    ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #137    ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #139    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4100:14)
I/flutter ( 2938): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #143    StatelessElement.update (package:flutter/src/widgets/framework.dart:3213:5)
I/flutter ( 2938): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #147    StatelessElement.update (package:flutter/src/widgets/framework.dart:3213:5)
I/flutter ( 2938): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #150    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #151    StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #155    ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #159    StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #163    ProxyElement.update (package:flutter/src/widgets/framework.dart:3399:5)
I/flutter ( 2938): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #167    StatefulElement.update (package:flutter/src/widgets/framework.dart:3288:5)
I/flutter ( 2938): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2305:15)
I/flutter ( 2938): #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163:16)
I/flutter ( 2938): #170    Element.rebuild (package:flutter/src/widgets/framework.dart:3052:5)
I/flutter ( 2938): #171    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1905:33)
I/flutter ( 2938): #172    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:360:20)
I/flutter ( 2938): #173    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170:5)
I/flutter ( 2938): #174    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:685:15)
I/flutter ( 2938): #175    BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:633:9)
I/flutter ( 2938): #176    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/rendering/binding.dart:247:20)
I/flutter ( 2938): #178    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
I/flutter ( 2938): #179    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
I/flutter ( 2938): #180    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
I/flutter ( 2938): (elided one frame from package dart:async-patch)
I/flutter ( 2938): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 410 of 425 libraries in 3,687ms.

```

## Flutter Doctor
```
$ flutter doctor
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /mnt/ssd/floitsch/code/flutter_apps/flutter
    • Framework revision 973304d5fb (7 days ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /usr/local/google/home/floitsch/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio-with-blaze-2.3/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-with-blaze-2.3
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[-] IntelliJ IDEA Community Edition (version 2016.2)
    • Dart plugin version 162.2485
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[-] IntelliJ IDEA Community Edition (version 2016.1)
    • Dart plugin version 145.971.7
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 14.0

[✓] Connected devices
    • Pixel • FA6B90302512 • android-arm • Android 7.1.2 (API 25)
```

### LINKED ISSUE #14466: BottomNavigationBar breaks when increasing number of items it contains
I believe that the cause is that the bar's state allocates animation controllers for each item when the state is first constructed, but it doesn't create new controllers when the state updates with more items.

## Steps to Reproduce

Create a nav bar with 3 items.

Increase the number of items to 4.

```
RangeError(index): invalid value: not in range 0..2, inclusive: 3.
```

## Logs
I/flutter (27323): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (27323): The following RangeError was thrown building BottomNavigationBar(dirty, state:
I/flutter (27323): _BottomNavigationBarState#68e58(tickers: tracking 3 tickers)):
I/flutter (27323): RangeError (index): Invalid value: Not in range 0..2, inclusive: 3
I/flutter (27323): 
I/flutter (27323): When the exception was thrown, this was the stack:
I/flutter (27323): #0      List.[] (dart:core-patch/dart:core/growable_array.dart:141)
I/flutter (27323): #1      _BottomNavigationBarState._createTiles (package:flutter/src/material/bottom_navigation_bar.dart:411:26)
I/flutter (27323): #2      _BottomNavigationBarState.build (package:flutter/src/material/bottom_navigation_bar.dart:477:45)
I/flutter (27323): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3690:27)
I/flutter (27323): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3602:15)
I/flutter (27323): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (27323): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
I/flutter (27323): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
I/flutter (27323): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4317:32)
I/flutter (27323): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4703:17)
I/flutter (27323): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #21     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
I/flutter (27323): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (27323): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
I/flutter (27323): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #31     StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
I/flutter (27323): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
I/flutter (27323): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #37     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (27323): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (27323): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #45     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
I/flutter (27323): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #49     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
I/flutter (27323): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
I/flutter (27323): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
I/flutter (27323): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
I/flutter (27323): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
I/flutter (27323): #57     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2210:33)
I/flutter (27323): #58     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
I/flutter (27323): #59     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (27323): #60     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (27323): #61     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (27323): #62     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (27323): #63     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:120)
I/flutter (27323): #64     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:109)
I/flutter (27323): ════════════════════════════════════════════════════════════════════════════════════════════════════

## Doctor
Version of Flutter is the current g3 version.

### LINKED ISSUE #19125: RangeError while adding Item to BottomNavigationBar
## Steps to Reproduce

https://gist.github.com/marius-h/3f4a8541b012ba7455a438150948d978

1. Add a BottomNavigationBar widget to a Scaffold
2. Add two Items to it and hit hot reload
3. Add a third Item to it and hot reload
4. RangeError showing up on screen

## Logs

```
[  +39 ms] [D:\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +64 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [D:\Flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [D:\Flutter\flutter\] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [D:\Flutter\flutter\] git log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] f9bb4289e9fd861d70ae78bcc3a042ef1b35cc9d
[        ] [D:\Flutter\flutter\] git log -n 1 --pretty=format:%ar
[  +28 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 8 weeks ago
[   +1 ms] [D:\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +35 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.4.4-0-gf9bb4289e
[ +300 ms] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +18 ms] Exit code 0 from: D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb devices -l
[        ] List of devices attached
           192.168.0.101:5555     device product:gts210vewifixx model:SM_T813 device:gts210vewifi transport_id:6
[ +202 ms] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb -s 192.168.0.101:5555 shell getprop
[ +298 ms] ro.hardware = qcom
[ +617 ms] Launching lib/main.dart on SM T813 in debug mode...
[   +7 ms] Initializing gradle...
[        ] Using gradle from D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\android\gradlew.bat.
[   +3 ms] D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\android\gradlew.bat -v
[ +586 ms]
                   ------------------------------------------------------------
                   Gradle 4.1
                   ------------------------------------------------------------

                   Build time:   2017-08-07 14:38:48 UTC
                   Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

                   Groovy:       2.4.11
                   Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
                   JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
                   OS:           Windows 10 10.0 amd64
[   +2 ms] Resolving dependencies...
[        ] [android\] D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\android\gradlew.bat app:properties
[ +992 ms] :app:properties

                   ------------------------------------------------------------
                   Project :app
                   ------------------------------------------------------------

                   allprojects: [project ':app']
                   android: com.android.build.gradle.AppExtension_Decorated@28b4db88
                   androidDependencies: task ':app:androidDependencies'
                   ant: org.gradle.api.internal.project.DefaultAntBuilder@75b89447
                   antBuilderFactory: org.gradle.api.internal.project.DefaultAntBuilderFactory@50d0000c
                   archivesBaseName: app
                   artifacts: org.gradle.api.internal.artifacts.dsl.DefaultArtifactHandler_Decorated@2419ee26
                   asDynamicObject: DynamicObject for project ':app'
                   assemble: task ':app:assemble'
                   assembleAndroidTest: task ':app:assembleAndroidTest'
                   assembleDebug: task ':app:assembleDebug'
                   assembleDebugAndroidTest: task ':app:assembleDebugAndroidTest'
                   assembleDebugUnitTest: task ':app:assembleDebugUnitTest'
                   assembleProfile: task ':app:assembleProfile'
                   assembleProfileUnitTest: task ':app:assembleProfileUnitTest'
                   assembleRelease: task ':app:assembleRelease'
                   assembleReleaseUnitTest: task ':app:assembleReleaseUnitTest'
                   baseClassLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@2a7f19b6
                   buildDependents: task ':app:buildDependents'
                   buildDir: D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\build\app
                   buildFile: D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\android\app\build.gradle
                   buildNeeded: task ':app:buildNeeded'
                   buildOutputs: BaseVariantOutput container
                   buildScriptSource: org.gradle.groovy.scripts.UriScriptSource@1bd4aa12
                   buildscript: org.gradle.api.internal.initialization.DefaultScriptHandler@4bd40904
                   bundleAppClassesDebug: task ':app:bundleAppClassesDebug'
                   bundleAppClassesDebugAndroidTest: task ':app:bundleAppClassesDebugAndroidTest'
                   bundleAppClassesDebugUnitTest: task ':app:bundleAppClassesDebugUnitTest'
                   bundleAppClassesProfile: task ':app:bundleAppClassesProfile'
                   bundleAppClassesProfileUnitTest: task ':app:bundleAppClassesProfileUnitTest'
                   bundleAppClassesRelease: task ':app:bundleAppClassesRelease'
                   bundleAppClassesReleaseUnitTest: task ':app:bundleAppClassesReleaseUnitTest'
                   check: task ':app:check'
                   checkDebugManifest: task ':app:checkDebugManifest'
                   checkProfileManifest: task ':app:checkProfileManifest'
                   checkReleaseManifest: task ':app:checkReleaseManifest'
                   childProjects: {}
                   class: class org.gradle.api.internal.project.DefaultProject_Decorated
                   classLoaderScope: org.gradle.api.internal.initialization.DefaultClassLoaderScope@2057b686
                   cleanBuildCache: task ':app:cleanBuildCache'
                   compileDebugAidl: task ':app:compileDebugAidl'
                   compileDebugAndroidTestAidl: task ':app:compileDebugAndroidTestAidl'
                   compileDebugAndroidTestJavaWithJavac: task ':app:compileDebugAndroidTestJavaWithJavac'
                   compileDebugAndroidTestNdk: task ':app:compileDebugAndroidTestNdk'
                   compileDebugAndroidTestRenderscript: task ':app:compileDebugAndroidTestRenderscript'
                   compileDebugAndroidTestShaders: task ':app:compileDebugAndroidTestShaders'
                   compileDebugAndroidTestSources: task ':app:compileDebugAndroidTestSources'
                   compileDebugJavaWithJavac: task ':app:compileDebugJavaWithJavac'
                   compileDebugNdk: task ':app:compileDebugNdk'
                   compileDebugRenderscript: task ':app:compileDebugRenderscript'
                   compileDebugShaders: task ':app:compileDebugShaders'
                   compileDebugSources: task ':app:compileDebugSources'
                   compileDebugUnitTestJavaWithJavac: task ':app:compileDebugUnitTestJavaWithJavac'
                   compileDebugUnitTestSources: task ':app:compileDebugUnitTestSources'
                   compileLint: task ':app:compileLint'
                   compileProfileAidl: task ':app:compileProfileAidl'
                   compileProfileJavaWithJavac: task ':app:compileProfileJavaWithJavac'
                   compileProfileNdk: task ':app:compileProfileNdk'
                   compileProfileRenderscript: task ':app:compileProfileRenderscript'
                   compileProfileShaders: task ':app:compileProfileShaders'
                   compileProfileSources: task ':app:compileProfileSources'
                   compileProfileUnitTestJavaWithJavac: task ':app:compileProfileUnitTestJavaWithJavac'
                   compileProfileUnitTestSources: task ':app:compileProfileUnitTestSources'
                   compileReleaseAidl: task ':app:compileReleaseAidl'
                   compileReleaseJavaWithJavac: task ':app:compileReleaseJavaWithJavac'
                   compileReleaseNdk: task ':app:compileReleaseNdk'
                   compileReleaseRenderscript: task ':app:compileReleaseRenderscript'
                   compileReleaseShaders: task ':app:compileReleaseShaders'
                   compileReleaseSources: task ':app:compileReleaseSources'
                   compileReleaseUnitTestJavaWithJavac: task ':app:compileReleaseUnitTestJavaWithJavac'
                   compileReleaseUnitTestSources: task ':app:compileReleaseUnitTestSources'
                   components: SoftwareComponentInternal set
                   configurationActions: org.gradle.configuration.project.DefaultProjectConfigurationActionContainer@7237b993
                   configurationTargetIdentifier: org.gradle.configuration.ConfigurationTargetIdentifier$1@4c8d09fd
                   configurations: configuration container
                   connectedAndroidTest: task ':app:connectedAndroidTest'
                   connectedCheck: task ':app:connectedCheck'
                   connectedDebugAndroidTest: task ':app:connectedDebugAndroidTest'
                   consumeConfigAttr: task ':app:consumeConfigAttr'
                   convention: org.gradle.api.internal.plugins.DefaultConvention@27fab541
                   copyFlutterAssetsDebug: task ':app:copyFlutterAssetsDebug'
                   copyFlutterAssetsProfile: task ':app:copyFlutterAssetsProfile'
                   copyFlutterAssetsRelease: task ':app:copyFlutterAssetsRelease'
                   createDebugCompatibleScreenManifests: task ':app:createDebugCompatibleScreenManifests'
                   createProfileCompatibleScreenManifests: task ':app:createProfileCompatibleScreenManifests'
                   createReleaseCompatibleScreenManifests: task ':app:createReleaseCompatibleScreenManifests'
                   defaultArtifacts: org.gradle.api.internal.plugins.DefaultArtifactPublicationSet_Decorated@3a04c4be
                   defaultTasks: []
                   deferredProjectConfiguration: org.gradle.api.internal.project.DeferredProjectConfiguration@7530094c
                   dependencies: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@51d624f6
                   depth: 1
                   description: null
                   deviceAndroidTest: task ':app:deviceAndroidTest'
                   deviceCheck: task ':app:deviceCheck'
                   displayName: project ':app'
                   distsDir: D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\build\app\distributions
                   distsDirName: distributions
                   docsDir: D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\build\app\docs
                   docsDirName: docs
                   ext: org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension@23f4c330
                   extensions: org.gradle.api.internal.plugins.DefaultConvention@27fab541
                   extractProguardFiles: task ':app:extractProguardFiles'
                   fileOperations: org.gradle.api.internal.file.DefaultFileOperations@3f49d2c4
                   fileResolver: org.gradle.api.internal.file.BaseDirFileResolver@4ac6d608
                   flutter: FlutterExtension_Decorated@2ad7ba32
                   flutterBuildDebug: task ':app:flutterBuildDebug'
                   flutterBuildProfile: task ':app:flutterBuildProfile'
                   flutterBuildRelease: task ':app:flutterBuildRelease'
                   flutterBuildX86Jar: task ':app:flutterBuildX86Jar'
                   generateDebugAndroidTestAssets: task ':app:generateDebugAndroidTestAssets'
                   generateDebugAndroidTestBuildConfig: task ':app:generateDebugAndroidTestBuildConfig'
                   generateDebugAndroidTestResValues: task ':app:generateDebugAndroidTestResValues'
                   generateDebugAndroidTestResources: task ':app:generateDebugAndroidTestResources'
                   generateDebugAndroidTestSources: task ':app:generateDebugAndroidTestSources'
                   generateDebugAssets: task ':app:generateDebugAssets'
                   generateDebugBuildConfig: task ':app:generateDebugBuildConfig'
                   generateDebugResValues: task ':app:generateDebugResValues'
                   generateDebugResources: task ':app:generateDebugResources'
                   generateDebugSources: task ':app:generateDebugSources'
                   generateProfileAssets: task ':app:generateProfileAssets'
                   generateProfileBuildConfig: task ':app:generateProfileBuildConfig'
                   generateProfileResValues: task ':app:generateProfileResValues'
                   generateProfileResources: task ':app:generateProfileResources'
                   generateProfileSources: task ':app:generateProfileSources'
                   generateReleaseAssets: task ':app:generateReleaseAssets'
                   generateReleaseBuildConfig: task ':app:generateReleaseBuildConfig'
                   generateReleaseResValues: task ':app:generateReleaseResValues'
                   generateReleaseResources: task ':app:generateReleaseResources'
                   generateReleaseSources: task ':app:generateReleaseSources'
                   gradle: build 'android'
                   group: android
                   identityPath: :app
                   inheritedScope: org.gradle.api.internal.ExtensibleDynamicObject$InheritedDynamicObject@2fbf011b
                   installDebug: task ':app:installDebug'
                   installDebugAndroidTest: task ':app:installDebugAndroidTest'
                   installProfile: task ':app:installProfile'
                   installRelease: task ':app:installRelease'
                   javaPreCompileDebug: task ':app:javaPreCompileDebug'
                   javaPreCompileDebugAndroidTest: task ':app:javaPreCompileDebugAndroidTest'
                   javaPreCompileDebugUnitTest: task ':app:javaPreCompileDebugUnitTest'
                   javaPreCompileProfile: task ':app:javaPreCompileProfile'
                   javaPreCompileProfileUnitTest: task ':app:javaPreCompileProfileUnitTest'
                   javaPreCompileRelease: task ':app:javaPreCompileRelease'
                   javaPreCompileReleaseUnitTest: task ':app:javaPreCompileReleaseUnitTest'
                   layout: org.gradle.api.internal.file.DefaultProjectLayout@5e9129da
                   libsDir: D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\build\app\libs
                   libsDirName: libs
                   lint: task ':app:lint'
                   lintDebug: task ':app:lintDebug'
                   lintProfile: task ':app:lintProfile'
                   lintRelease: task ':app:lintRelease'
                   lintVitalRelease: task ':app:lintVitalRelease'
                   logger: org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger@35d9fd55
                   logging: org.gradle.internal.logging.services.DefaultLoggingManager@229bd296
                   mergeDebugAndroidTestAssets: task ':app:mergeDebugAndroidTestAssets'
                   mergeDebugAndroidTestJniLibFolders: task ':app:mergeDebugAndroidTestJniLibFolders'
                   mergeDebugAndroidTestResources: task ':app:mergeDebugAndroidTestResources'
                   mergeDebugAndroidTestShaders: task ':app:mergeDebugAndroidTestShaders'
                   mergeDebugAssets: task ':app:mergeDebugAssets'
                   mergeDebugJniLibFolders: task ':app:mergeDebugJniLibFolders'
                   mergeDebugResources: task ':app:mergeDebugResources'
                   mergeDebugShaders: task ':app:mergeDebugShaders'
                   mergeProfileAssets: task ':app:mergeProfileAssets'
                   mergeProfileJniLibFolders: task ':app:mergeProfileJniLibFolders'
                   mergeProfileResources: task ':app:mergeProfileResources'
                   mergeProfileShaders: task ':app:mergeProfileShaders'
                   mergeReleaseAssets: task ':app:mergeReleaseAssets'
                   mergeReleaseJniLibFolders: task ':app:mergeReleaseJniLibFolders'
                   mergeReleaseResources: task ':app:mergeReleaseResources'
                   mergeReleaseShaders: task ':app:mergeReleaseShaders'
                   mockableAndroidJar: task ':app:mockableAndroidJar'
                   modelRegistry: org.gradle.model.internal.registry.DefaultModelRegistry@358aeadd
                   modelSchemaStore: org.gradle.model.internal.manage.schema.extract.DefaultModelSchemaStore@1265142f
                   module: org.gradle.api.internal.artifacts.ProjectBackedModule@5fc05e03
                   name: app
                   normalization: org.gradle.normalization.internal.DefaultInputNormalizationHandler_Decorated@62ea92ae
                   objects: org.gradle.api.internal.model.DefaultObjectFactory@69ca5d65
                   org.gradle.jvmargs: -Xmx1536M
                   packageDebug: task ':app:packageDebug'
                   packageDebugAndroidTest: task ':app:packageDebugAndroidTest'
                   packageProfile: task ':app:packageProfile'
                   packageRelease: task ':app:packageRelease'
                   parent: root project 'android'
                   parentIdentifier: root project 'android'
                   path: :app
                   platformAttrExtractor: task ':app:platformAttrExtractor'
                   pluginManager: org.gradle.api.internal.plugins.DefaultPluginManager_Decorated@3562b8d0
                   plugins: [org.gradle.api.plugins.HelpTasksPlugin@78dc636d, com.android.build.gradle.api.AndroidBasePlugin@2f252fc0, org.gradle.language.base.plugins.LifecycleBasePlugin@22ef67d2, o
rg.gradle.api.plugins.BasePlugin@19e9a9ca, org.gradle.api.plugins.ReportingBasePlugin@1aba609f, org.gradle.platform.base.plugins.ComponentBasePlugin@3d35a7b3, org.gradle.language.base.plugins.Languag
eBasePlugin@74c28612, org.gradle.platform.base.plugins.BinaryBasePlugin@83fe16c, org.gradle.api.plugins.JavaBasePlugin@717b1bc9, com.android.build.gradle.internal.coverage.JacocoPlugin@5887f6f, com.a
ndroid.build.gradle.AppPlugin@35601d48, FlutterPlugin@163cf7ed]
                   preBuild: task ':app:preBuild'
                   preDebugAndroidTestBuild: task ':app:preDebugAndroidTestBuild'
                   preDebugBuild: task ':app:preDebugBuild'
                   preDebugUnitTestBuild: task ':app:preDebugUnitTestBuild'
                   preProfileBuild: task ':app:preProfileBuild'
                   preProfileUnitTestBuild: task ':app:preProfileUnitTestBuild'
                   preReleaseBuild: task ':app:preReleaseBuild'
                   preReleaseUnitTestBuild: task ':app:preReleaseUnitTestBuild'
                   prepareLintJar: task ':app:prepareLintJar'
                   processDebugAndroidTestJavaRes: task ':app:processDebugAndroidTestJavaRes'
                   processDebugAndroidTestManifest: task ':app:processDebugAndroidTestManifest'
                   processDebugAndroidTestResources: task ':app:processDebugAndroidTestResources'
                   processDebugJavaRes: task ':app:processDebugJavaRes'
                   processDebugManifest: task ':app:processDebugManifest'
                   processDebugResources: task ':app:processDebugResources'
                   processDebugUnitTestJavaRes: task ':app:processDebugUnitTestJavaRes'
                   processOperations: org.gradle.api.internal.file.DefaultFileOperations@3f49d2c4
                   processProfileJavaRes: task ':app:processProfileJavaRes'
                   processProfileManifest: task ':app:processProfileManifest'
                   processProfileResources: task ':app:processProfileResources'
                   processProfileUnitTestJavaRes: task ':app:processProfileUnitTestJavaRes'
                   processReleaseJavaRes: task ':app:processReleaseJavaRes'
                   processReleaseManifest: task ':app:processReleaseManifest'
                   processReleaseResources: task ':app:processReleaseResources'
                   processReleaseUnitTestJavaRes: task ':app:processReleaseUnitTestJavaRes'
                   project: project ':app'
                   projectConfigurator: org.gradle.api.internal.project.BuildOperationCrossProjectConfigurator@4911d388
                   projectDir: D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\android\app
                   projectEvaluationBroadcaster: ProjectEvaluationListener broadcast
                   projectEvaluator: org.gradle.configuration.project.LifecycleProjectEvaluator@2b2f0475
                   projectPath: :app
                   projectRegistry: org.gradle.api.internal.project.DefaultProjectRegistry@1d668c5c
                   properties: {...}
                   providers: org.gradle.api.internal.provider.DefaultProviderFactory@75a53b6a
                   reporting: org.gradle.api.reporting.ReportingExtension_Decorated@3de20318
                   reportsDir: D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\build\app\reports
                   repositories: repository container
                   resolveConfigAttr: task ':app:resolveConfigAttr'
                   resources: org.gradle.api.internal.resources.DefaultResourceHandler@7aa80abf
                   rootDir: D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\android
                   rootProject: root project 'android'
                   scriptHandlerFactory: org.gradle.api.internal.initialization.DefaultScriptHandlerFactory@2977a533
                   scriptPluginFactory: org.gradle.configuration.ScriptPluginFactorySelector@dad82d
                   serviceRegistryFactory: org.gradle.internal.service.scopes.ProjectScopeServices$4@2d8de1ed
                   services: ProjectScopeServices
                   signingReport: task ':app:signingReport'
                   sourceCompatibility: 1.8
                   sourceSets: SourceSet container
                   splitsDiscoveryTaskDebug: task ':app:splitsDiscoveryTaskDebug'
                   splitsDiscoveryTaskDebugAndroidTest: task ':app:splitsDiscoveryTaskDebugAndroidTest'
                   splitsDiscoveryTaskProfile: task ':app:splitsDiscoveryTaskProfile'
                   splitsDiscoveryTaskRelease: task ':app:splitsDiscoveryTaskRelease'
                   standardOutputCapture: org.gradle.internal.logging.services.DefaultLoggingManager@229bd296
                   state: project state 'EXECUTED'
                   status: integration
                   subprojects: []
                   targetCompatibility: 1.8
                   tasks: task set
                   test: task ':app:test'
                   testDebugUnitTest: task ':app:testDebugUnitTest'
                   testProfileUnitTest: task ':app:testProfileUnitTest'
                   testReleaseUnitTest: task ':app:testReleaseUnitTest'
                   testReportDir: D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\build\app\reports\tests
                   testReportDirName: tests
                   testResultsDir: D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\build\app\test-results
                   testResultsDirName: test-results
                   transformClassesWithDexBuilderForDebug: task ':app:transformClassesWithDexBuilderForDebug'
                   transformClassesWithDexBuilderForDebugAndroidTest: task ':app:transformClassesWithDexBuilderForDebugAndroidTest'
                   transformClassesWithDexBuilderForProfile: task ':app:transformClassesWithDexBuilderForProfile'
                   transformClassesWithPreDexForRelease: task ':app:transformClassesWithPreDexForRelease'
                   transformDexArchiveWithDexMergerForDebug: task ':app:transformDexArchiveWithDexMergerForDebug'
                   transformDexArchiveWithDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithDexMergerForDebugAndroidTest'
                   transformDexArchiveWithDexMergerForProfile: task ':app:transformDexArchiveWithDexMergerForProfile'
                   transformDexArchiveWithExternalLibsDexMergerForDebug: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'
                   transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest: task ':app:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'
                   transformDexArchiveWithExternalLibsDexMergerForProfile: task ':app:transformDexArchiveWithExternalLibsDexMergerForProfile'
                   transformDexWithDexForRelease: task ':app:transformDexWithDexForRelease'
                   transformNativeLibsWithMergeJniLibsForDebug: task ':app:transformNativeLibsWithMergeJniLibsForDebug'
                   transformNativeLibsWithMergeJniLibsForDebugAndroidTest: task ':app:transformNativeLibsWithMergeJniLibsForDebugAndroidTest'
                   transformNativeLibsWithMergeJniLibsForProfile: task ':app:transformNativeLibsWithMergeJniLibsForProfile'
                   transformNativeLibsWithMergeJniLibsForRelease: task ':app:transformNativeLibsWithMergeJniLibsForRelease'
                   transformResourcesWithMergeJavaResForDebug: task ':app:transformResourcesWithMergeJavaResForDebug'
                   transformResourcesWithMergeJavaResForDebugAndroidTest: task ':app:transformResourcesWithMergeJavaResForDebugAndroidTest'
                   transformResourcesWithMergeJavaResForDebugUnitTest: task ':app:transformResourcesWithMergeJavaResForDebugUnitTest'
                   transformResourcesWithMergeJavaResForProfile: task ':app:transformResourcesWithMergeJavaResForProfile'
                   transformResourcesWithMergeJavaResForProfileUnitTest: task ':app:transformResourcesWithMergeJavaResForProfileUnitTest'
                   transformResourcesWithMergeJavaResForRelease: task ':app:transformResourcesWithMergeJavaResForRelease'
                   transformResourcesWithMergeJavaResForReleaseUnitTest: task ':app:transformResourcesWithMergeJavaResForReleaseUnitTest'
                   uninstallAll: task ':app:uninstallAll'
                   uninstallDebug: task ':app:uninstallDebug'
                   uninstallDebugAndroidTest: task ':app:uninstallDebugAndroidTest'
                   uninstallProfile: task ':app:uninstallProfile'
                   uninstallRelease: task ':app:uninstallRelease'
                   validateSigningDebug: task ':app:validateSigningDebug'
                   validateSigningDebugAndroidTest: task ':app:validateSigningDebugAndroidTest'
                   validateSigningProfile: task ':app:validateSigningProfile'
                   validateSigningRelease: task ':app:validateSigningRelease'
                   version: unspecified
                   writeDebugApplicationId: task ':app:writeDebugApplicationId'
                   writeProfileApplicationId: task ':app:writeProfileApplicationId'
                   writeReleaseApplicationId: task ':app:writeReleaseApplicationId'

                   BUILD SUCCESSFUL in 0s
                   1 actionable task: 1 executed
[   +9 ms] D:\Users\Marius\AppData\Local\Android\sdk\build-tools\27.0.3\aapt dump badging build\app\outputs\apk\app.apk
[  +16 ms] Exit code 0 from: D:\Users\Marius\AppData\Local\Android\sdk\build-tools\27.0.3\aapt dump badging build\app\outputs\apk\app.apk
[        ] package: name='com.example.schuleeinfachapp' versionCode='1' versionName='1.0' platformBuildVersionName=''
           sdkVersion:'16'
           targetSdkVersion:'27'
           uses-permission: name='android.permission.INTERNET'
           application-label:'schule_einfach_app'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='schule_einfach_app' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.example.schuleeinfachapp.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales: '--_--'
           densities: '160' '240' '320' '480' '640'
           native-code: 'arm64-v8a' 'x86' 'x86_64'
[   +7 ms] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb -s 192.168.0.101:5555 logcat -v time -t 1
[ +208 ms] Exit code 0 from: D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb -s 192.168.0.101:5555 logcat -v time -t 1
[        ] --------- beginning of main
           07-06 23:28:09.301 D/WifiStateMachine( 1237): not enough dual-band rssi, bail out...
[   +3 ms] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb -s 192.168.0.101:5555 logcat -v time
[ +322 ms] DependencyChecker: D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\lib\pages\home.dart is newer than 2018-07-06 23:27:32.000
[   +6 ms] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb version
[  +17 ms] Android Debug Bridge version 1.0.39
           Version 0.0.1-4500957
           Installed as D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb.EXE
[   +2 ms] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb start-server
[  +22 ms] Building APK
[   +6 ms] Running 'gradlew assembleDebug'...
[   +2 ms] [android\] D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\android\gradlew.bat -Ptarget=D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\lib/main.dart -Ppreview-dart-2=true -Ptarget-platfor
m=android-arm64 assembleDebug
[ +911 ms] :app:preBuild UP-TO-DATE
[  +17 ms] :app:preDebugBuild UP-TO-DATE
[        ] :app:compileDebugAidl UP-TO-DATE
[  +10 ms] :app:compileDebugRenderscript UP-TO-DATE
[        ] :app:flutterBuildX86Jar UP-TO-DATE
[        ] :app:checkDebugManifest UP-TO-DATE
[   +9 ms] :app:generateDebugBuildConfig UP-TO-DATE
[        ] :app:prepareLintJar UP-TO-DATE
[  +53 ms] :app:cleanMergeDebugAssets
[+3687 ms] :app:flutterBuildDebug
[  +11 ms] :app:mergeDebugShaders UP-TO-DATE
[        ] :app:compileDebugShaders UP-TO-DATE
[        ] :app:generateDebugAssets UP-TO-DATE
[  +10 ms] :app:mergeDebugAssets
[ +256 ms] :app:copyFlutterAssetsDebug
[        ] :app:generateDebugResValues UP-TO-DATE
[        ] :app:generateDebugResources UP-TO-DATE
[  +10 ms] :app:mergeDebugResources UP-TO-DATE
[        ] :app:createDebugCompatibleScreenManifests UP-TO-DATE
[  +10 ms] :app:processDebugManifest UP-TO-DATE
[        ] :app:splitsDiscoveryTaskDebug UP-TO-DATE
[  +10 ms] :app:processDebugResources UP-TO-DATE
[        ] :app:generateDebugSources UP-TO-DATE
[        ] :app:javaPreCompileDebug UP-TO-DATE
[  +10 ms] :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] :app:compileDebugNdk NO-SOURCE
[        ] :app:compileDebugSources UP-TO-DATE
[  +10 ms] :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[  +10 ms] :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
[        ] :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
[        ] :app:mergeDebugJniLibFolders UP-TO-DATE
[   +9 ms] :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
[        ] :app:processDebugJavaRes NO-SOURCE
[  +10 ms] :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
[        ] :app:validateSigningDebug
[+2202 ms] :app:packageDebug
[        ] :app:assembleDebug
[        ] BUILD SUCCESSFUL in 7s
[        ] 29 actionable tasks: 6 executed, 23 up-to-date
[ +464 ms] calculateSha: D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\build\app\outputs\apk/app.apk
[ +416 ms] Built build\app\outputs\apk\debug\app-debug.apk.
[   +1 ms] D:\Users\Marius\AppData\Local\Android\sdk\build-tools\27.0.3\aapt dump badging build\app\outputs\apk\app.apk
[  +13 ms] Exit code 0 from: D:\Users\Marius\AppData\Local\Android\sdk\build-tools\27.0.3\aapt dump badging build\app\outputs\apk\app.apk
[        ] package: name='com.example.schuleeinfachapp' versionCode='1' versionName='1.0' platformBuildVersionName=''
           sdkVersion:'16'
           targetSdkVersion:'27'
           uses-permission: name='android.permission.INTERNET'
           application-label:'schule_einfach_app'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='schule_einfach_app' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.example.schuleeinfachapp.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales: '--_--'
           densities: '160' '240' '320' '480' '640'
           native-code: 'arm64-v8a' 'x86' 'x86_64'
[        ] Stopping app 'app.apk' on SM T813.
[        ] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb -s 192.168.0.101:5555 shell am force-stop com.example.schuleeinfachapp
[ +996 ms] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb -s 192.168.0.101:5555 shell pm list packages com.example.schuleeinfachapp
[+1032 ms] package:com.example.schuleeinfachapp
[   +7 ms] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb -s 192.168.0.101:5555 shell cat /data/local/tmp/sky.com.example.schuleeinfachapp.sha1
[  +52 ms] 161997c49d0c66906734d93e1d5739d8e7bdf94f
[        ] Installing APK.
[   +1 ms] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb version
[  +14 ms] Android Debug Bridge version 1.0.39
           Version 0.0.1-4500957
           Installed as D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb.EXE
[        ] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb start-server
[  +15 ms] Installing build\app\outputs\apk\app.apk...
[        ] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb -s 192.168.0.101:5555 install -r build\app\outputs\apk\app.apk
[+10650 ms] Success
[   +2 ms] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb -s 192.168.0.101:5555 shell echo -n 240e4123e0b791abb71396a2f85db9f2b947b739 > /data/local/tmp/sky.com.example.schuleeinfachapp
.sha1
[  +53 ms] SM T813 startApp
[   +2 ms] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb -s 192.168.0.101:5555 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez en
able-dart-profiling true --ez enable-checked-mode true com.example.schuleeinfachapp/com.example.schuleeinfachapp.MainActivity
[ +756 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.schuleeinfachapp/.MainActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }
[        ] Waiting for observatory port to be available...
[ +903 ms] I/FlutterActivityDelegate(24606): onResume setting current activity to this
[  +74 ms] Observatory URL on device: http://127.0.0.1:40611/
[   +7 ms] D:\Users\Marius\AppData\Local\Android\sdk\platform-tools\adb -s 192.168.0.101:5555 forward tcp:8104 tcp:40611
[  +18 ms] Forwarded host port 8104 to device port 40611 for Observatory
[   +6 ms] Connecting to service protocol: http://127.0.0.1:8104/
[ +364 ms] Successfully connected to service protocol: http://127.0.0.1:8104/
[   +4 ms] getVM: {}
[  +46 ms] getIsolate: {isolateId: isolates/353164405}
[   +2 ms] _flutter.listViews: {}
[ +666 ms] DevFS: Creating new filesystem on the device (null)
[   +1 ms] _createDevFS: {fsName: Schule.Einfach.App}
[  +16 ms] D/ViewRootImpl@a2552e2[MainActivity](24606): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1536, 2048) ci=Rect(0, 48 - 0, 0) vi=Rect(0, 48 - 0, 0) or=1
[        ] D/ViewRootImpl@a2552e2[MainActivity](24606): MSG_WINDOW_FOCUS_CHANGED 1
[        ] D/ViewRootImpl@a2552e2[MainActivity](24606): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 547975702016}
[        ] V/InputMethodManager(24606): Starting input: tba=android.view.inputmethod.EditorInfo@49fb9a9 nm : com.example.schuleeinfachapp ic=null
[        ] I/InputMethodManager(24606): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
[   +1 ms] D/InputTransport(24606): Input channel constructed: fd=85
[   +4 ms] V/InputMethodManager(24606): Starting input: tba=android.view.inputmethod.EditorInfo@449bb2e nm : com.example.schuleeinfachapp ic=null
[  +62 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.schuleeinfachapp/cache/Schule.Einfach.AppWPXMEW/Schule.Einfach.App/)
[   +1 ms] Updating assets
[ +225 ms] Syncing files to device SM T813...
[   +3 ms] DevFS: Starting sync from LocalDirectory: 'D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App'
[        ] Scanning project files
[   +4 ms] Scanning package files
[  +59 ms] Scanning asset files
[   +1 ms] Scanning for deleted files
[  +46 ms] Compiling dart to kernel with 423 updated files
[   +3 ms] D:\Flutter\flutter\bin\cache\dart-sdk\bin\dart D:\Flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root D:\Flutter\flutter\bin\cache\artifacts\eng
ine\common\flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill build\app.dill --packages D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App\.packages --filesystem-scheme org-dartl
ang-root
[+1272 ms] Updating files
[ +995 ms] DevFS: Sync finished
[   +1 ms] Synced 1.4MB.
[   +1 ms] _flutter.listViews: {}
[  +40 ms] Connected to _flutterView/0x7f896dfb98.
[   +1 ms] 🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
[        ] An Observatory debugger and profiler on SM T813 is available at: http://127.0.0.1:8104/
[        ] For a more detailed help message, press "h". To quit, press "q".
[+14239 ms] Initializing hot reload...
[   +7 ms] Refreshing active FlutterViews before reloading.
[        ] _flutter.listViews: {}
[ +453 ms] Syncing files to device SM T813...
[        ] DevFS: Starting sync from LocalDirectory: 'D:\Dokumente\Coding\IntelliJ\Schule.Einfach.App'
[        ] Scanning project files
[   +1 ms] Scanning package files
[  +29 ms] Scanning asset files
[        ] Scanning for deleted files
[  +34 ms] Compiling dart to kernel with 1 updated files
[ +114 ms] Updating files
[  +88 ms] DevFS: Sync finished
[        ] Synced 0.0MB.
[   +2 ms] _flutter.setAssetBundlePath: {viewId: _flutterView/0x7f896dfb98, assetDirectory: /data/user/0/com.example.schuleeinfachapp/cache/Schule.Einfach.AppWPXMEW/Schule.Einfach.App/build/flutter_a
ssets}
[  +76 ms] _reloadSources: {pause: false, rootLibUri: /data/user/0/com.example.schuleeinfachapp/cache/Schule.Einfach.AppWPXMEW/Schule.Einfach.App/lib/main.dart.dill, packagesUri: /data/user/0/com.exa
mple.schuleeinfachapp/cache/Schule.Einfach.AppWPXMEW/Schule.Einfach.App/.packages, isolateId: isolates/353164405}
[ +324 ms] reloaded 6 of 399 libraries
[   +1 ms] Sending reload events to SM T813
[   +1 ms] Sending reload event to "main.dart$main-353164405"
[   +2 ms] getIsolate: {isolateId: isolates/353164405}
[ +129 ms] _flutter.listViews: {}
[  +40 ms] Evicting dirty assets
[   +2 ms] ext.flutter.evict: {value: AssetManifest.json, isolateId: isolates/353164405}
[ +102 ms] ext.flutter.evict: {value: FontManifest.json, isolateId: isolates/353164405}
[  +30 ms] ext.flutter.evict: {value: LICENSE, isolateId: isolates/353164405}
[  +62 ms] Reassembling application
[   +1 ms] ext.flutter.reassemble: {isolateId: isolates/353164405}
[ +225 ms] I/flutter (24606): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[   +6 ms] I/flutter (24606): The following RangeError was thrown building BottomNavigationBar(dirty, state:
[        ] I/flutter (24606): _BottomNavigationBarState#f1a12(tickers: tracking 2 tickers)):
[        ] I/flutter (24606): RangeError (index): Invalid value: Not in range 0..1, inclusive: 2
[   +6 ms] I/flutter (24606): 
[        ] I/flutter (24606): When the exception was thrown, this was the stack:
[  +19 ms] I/flutter (24606): #0      List.[] (dart:core/runtime/libgrowable_array.dart:141:60)
[        ] I/flutter (24606): #1      _BottomNavigationBarState._createTiles (package:flutter/src/material/bottom_navigation_bar.dart:427:26)
[        ] I/flutter (24606): #2      _BottomNavigationBarState.build (package:flutter/src/material/bottom_navigation_bar.dart:517:47)
[        ] I/flutter (24606): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
[        ] I/flutter (24606): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
[        ] I/flutter (24606): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
[        ] I/flutter (24606): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
[  +14 ms] I/flutter (24606): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
[        ] I/flutter (24606): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4379:32)
[        ] I/flutter (24606): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4769:17)
[   +1 ms] I/flutter (24606): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter (24606): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
[        ] I/flutter (24606): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[   +1 ms] I/flutter (24606): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter (24606): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter (24606): #25     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
[        ] I/flutter (24606): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[   +1 ms] I/flutter (24606): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter (24606): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter (24606): #29     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
[   +1 ms] I/flutter (24606): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[   +2 ms] I/flutter (24606): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
[        ] I/flutter (24606): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[   +2 ms] I/flutter (24606): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter (24606): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +2 ms] I/flutter (24606): #35     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
[   +7 ms] I/flutter (24606): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
[        ] I/flutter (24606): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
[        ] I/flutter (24606): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
[        ] I/flutter (24606): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +1 ms] I/flutter (24606): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #49     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
[        ] I/flutter (24606): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #53     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
[        ] I/flutter (24606): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #57     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
[   +1 ms] I/flutter (24606): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[   +1 ms] I/flutter (24606): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[   +2 ms] I/flutter (24606): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +2 ms] I/flutter (24606): #61     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
[        ] I/flutter (24606): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
[        ] I/flutter (24606): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #67     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
[        ] I/flutter (24606): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #69     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
[        ] I/flutter (24606): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
[        ] I/flutter (24606): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
[        ] I/flutter (24606): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
[        ] I/flutter (24606): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #79     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
[        ] I/flutter (24606): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[   +1 ms] I/flutter (24606): #83     StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
[        ] I/flutter (24606): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #87     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
[        ] I/flutter (24606): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #89     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
[        ] I/flutter (24606): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #93     ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
[        ] I/flutter (24606): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #95     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
[        ] I/flutter (24606): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #99     StatefulElement.update (package:flutter/src/widgets/framework.dart:3799:5)
[        ] I/flutter (24606): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #103    StatelessElement.update (package:flutter/src/widgets/framework.dart:3702:5)
[        ] I/flutter (24606): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #105    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4661:14)
[        ] I/flutter (24606): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #109    ProxyElement.update (package:flutter/src/widgets/framework.dart:3909:5)
[        ] I/flutter (24606): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2699:15)
[        ] I/flutter (24606): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
[        ] I/flutter (24606): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
[        ] I/flutter (24606): #113    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
[        ] I/flutter (24606): #114    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/
widgets/binding.dart:626:20)
[        ] I/flutter (24606): #115    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutte
r/src/rendering/binding.dart:208:5)
[        ] I/flutter (24606): #116    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
[        ] I/flutter (24606): #117    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
[        ] I/flutter (24606): #118    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding
.dart:751:7)
[        ] I/flutter (24606): #120    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
[        ] I/flutter (24606): #121    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
[        ] I/flutter (24606): #122    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
[        ] I/flutter (24606): (elided one frame from package dart:async)
[        ] I/flutter (24606): ════════════════════════════════════════════════════════════════════════════════════════════════════
[   +7 ms] ext.ui.window.scheduleFrame: {isolateId: isolates/353164405}
[  +52 ms] Hot reload performed in 1.746ms.
[        ] Reloaded 6 of 399 libraries in 1.920ms.
```

```
Analyzing Schule.Einfach.App...

   info - Unused import: 'package:schule_einfach_app/pages/login-page.dart' - out\production\Schule.Einfach.App\main.dart:3:8
   info - Unused import: 'package:flutter/material.dart' - out\production\Schule.Einfach.App\pages\login.dart:1:8

2 issues found. (ran in 1.9s)
```

```
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.17134.112], locale de-DE)
    • Flutter version 0.4.4 at D:\Flutter\flutter
    • Framework revision f9bb4289e9 (8 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Users\Marius\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\Marius\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_101\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
    • All Android licenses accepted.

[X] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at D:\Users\Marius\AppData\Local\JetBrains\apps\IDEA-U\ch-0\181.5087.20
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[√] Connected devices (1 available)
    • SM T813 • 192.168.0.101:5555 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by HansMuller**
If the length of the items list changes, just reset the navigation bar's internal state. 

Fixes: https://github.com/flutter/flutter/issues/14466
Fixes: https://github.com/flutter/flutter/issues/19125
Fixes: https://github.com/flutter/flutter/issues/10322

### CODE REVIEW

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart [hunk 1]
```diff
@@ -303,8 +303,8 @@ class _BottomNavigationTile extends StatelessWidget {
 }
 
 class _BottomNavigationBarState extends State<BottomNavigationBar> with TickerProviderStateMixin {
-  List<AnimationController> _controllers;
-  List<CurvedAnimation> _animations;
+  List<AnimationController> _controllers = <AnimationController>[];
+  List<CurvedAnimation> _animations = <CurvedAnimation>[];
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/bottom_navigation_bar.dart]: Looks like the initial value for `_animations` is never used?

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/bottom_navigation_bar.dart (hunk 1 above)
Comment (HansMuller) [reply packages/flutter/lib/src/material/bottom_navigation_bar.dart]: Good point, I've removed the initial value.
