### PR TITLE
Fixes a NestedScrollView UserScrollNotification issue

### LINKED ISSUE #107101: NestedScrollView with UserScrollNotification direction value is not right
## Steps to Reproduce
listener `UserScrollNotification`,and print direction.

when i fling,i get

log is:
I/flutter ( 5729): update scroll direction ScrollDirection.idle
I/flutter ( 5729): update scroll direction ScrollDirection.reverse
I/flutter ( 5729): update scroll direction ScrollDirection.idle

in this case ,when i begin drage,i get first update state is idle

or

I/flutter ( 5729): update scroll direction ScrollDirection.forward

in this case, when i drage end,i not get idle

**Expected results:** 

when i begin drage,i can get update state is `reverse` or `forward`
when NestedScrollView scroll end,i can get  update state is `idle`

**Actual results:** 

I/flutter ( 5729): update scroll direction ScrollDirection.idle
I/flutter ( 5729): update scroll direction ScrollDirection.reverse
I/flutter ( 5729): update scroll direction ScrollDirection.idle

or

I/flutter ( 5729): update scroll direction ScrollDirection.forward

<details>
<summary>Code sample</summary>

```dart
NotificationListener<UserScrollNotification>(
        onNotification: (notification) {
          print(' update scroll direction ScrollDirection.${notification.direction.toString()}');
          return true;
        },
        child: NestedScrollView(
                headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
                  return <Widget>[
                    SliverAppBar(
                      title: const Text('ListView'),
                      pinned: true, 
                      forceElevated: innerBoxIsScrolled,
                    ),
                  ];
                },
                body: ListView.builder(
                  padding: const EdgeInsets.all(8),
                  physics: const ClampingScrollPhysics(), 
                  itemCount: 30,
                  itemBuilder: (BuildContext context, int index) {
                    return SizedBox(
                      height: 50,
                      child: Center(child: Text('Item $index')),
                    );
                  },
                ),
              ),
            )
        ),
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes https://github.com/flutter/flutter/issues/107101

We do not notify the idle state if ending the drag with a velocity.

We only notify the idle state if no scrolling occurs when the drag ends.
https://github.com/flutter/flutter/blob/5a5d021e51ca9a16fdfc64b34a8d64c75be1b500/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L656-L658

### CODE REVIEW

File: packages/flutter/test/widgets/nested_scroll_view_test.dart [hunk 1]
```diff
@@ -120,6 +120,59 @@ Widget buildTest({
 }
 
 void main() {
+  testWidgets('ScrollDirection test', (WidgetTester tester) async {
+    // Regression test for https://github.com/flutter/flutter/issues/107101
+    final List<ScrollDirection> receivedResult = <ScrollDirection>[];
+    const List<ScrollDirection> expectedReverseResult = <ScrollDirection>[ScrollDirection.reverse, ScrollDirection.idle];
+    const List<ScrollDirection> expectedFrowardResult = <ScrollDirection>[ScrollDirection.forward, ScrollDirection.idle];
```
Comment (Piinks) [inline packages/flutter/test/widgets/nested_scroll_view_test.dart:127]: Typo nit: 
```suggestion
    const List<ScrollDirection> expectedForwardResult = <ScrollDirection>[ScrollDirection.forward, ScrollDirection.idle];
```

**Review by Piinks — APPROVED** [review]
LGTM!

**Comment by xu-baolin** [comment]
@Piinks Hi, Could you help restart the G-test?

**Comment by goderbauer** [comment]
@xu-baolin For some reason the "Google testing" check didn't trigger correctly. Could you rebase this PR with the latest master and push it up again? That will re-trigger the check. Sorry about this...

**Comment by xu-baolin** [comment]
> * The status or check suite [Linux web_long_running_tests_4_5](https://ci.chromium.org/b/8807438392150391329) has failed. Please fix the issues identified (or deflake) before re-applying this label.

Test flakes issue -> https://github.com/flutter/flutter/issues/97316
