### PR TITLE
fix resampling leads to Hard to tap

### LINKED ISSUE #73286: Hard to tap when resampling enabled on Samsung Galaxy S20 Ultra
## Steps to Reproduce

1. Enable resampling by `GestureBinding.instance.resamplingEnabled = true;`
2. run app
3. every inkwell or button hard to tap.

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
Last login: Mon Jan  4 17:06:17 on ttys147
ekasetiawans@MacBookPro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-2.0.pre.168, on macOS 11.1 20C69 darwin-x64,
    locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)
    ! Error: Errors were encountered while preparing your device for
      development. Please check the Devices and Simulators Window.  (code -1)

• No issues found!
ekasetiawans@MacBookPro ~ % 
```

</details>

Note:
I don't have the device, but this is based on the incoming reports from my app users. The app currently runs smoothly if I disable resampling.

### PR DESCRIPTION
**Pull request by LinXiaoTao**
*On Flutter 2.0, enabling resampling will result in hard to tap on Android devices.*

fixes #73286

I think it was caused by this commit https://github.com/flutter/flutter/pull/67080.
When converting PointerUpEvent to PointerMoveEvent(**see code 1**), `buttons` are 0(**see code 2**), so the `stopTrackingPointer` method is executed(**see code 3**) and the tap callback is cancelled.
``` dart
// src/gestures/resampler.dart
if (event is! PointerMoveEvent && event is! PointerHoverEvent) {                                    
  // Add synthetics `move` or `hover` event if position has changed.                                
  // Note: Devices without `hover` events are expected to always have                               
  // `add` and `down` events with the same position and this logic will                             
  // therefor never produce `hover` events.                                                         
  if (position != _position) {                                                                      
    final Offset delta = position - _position; 
    // code 1                                                     
    callback(_toMoveOrHoverEvent(event, position, delta, _pointerIdentifier, sampleTime, wasDown)); 
    _position = position;                                                                           
  }                                                                                                 
  callback(event.copyWith(                                                                          
    position: position,                                                                             
    delta: Offset.zero,                                                                             
    pointer: pointerIdentifier,                                                                     
    timeStamp: sampleTime,                                                                          
  ));                                                                                               
} 

PointerEvent _toMoveEvent(                     
  PointerEvent event,                          
  Offset position,                             
  Offset delta,                                
  int pointerIdentifier,                       
  Duration timeStamp,                          
) { 
  // code 2                                           
  return PointerMoveEvent(                     
    timeStamp: timeStamp,                      
    pointer: pointerIdentifier,                
    kind: event.kind,                          
    device: event.device,                      
    position: position,                        
    delta: delta,                              
    buttons: event.buttons,                    
    obscured: event.obscured,                  
    pressure: event.pressure,                  
    pressureMin: event.pressureMin,            
    pressureMax: event.pressureMax,            
    distanceMax: event.distanceMax,            
    size: event.size,                          
    radiusMajor: event.radiusMajor,            
    radiusMinor: event.radiusMinor,            
    radiusMin: event.radiusMin,                
    radiusMax: event.radiusMax,                
    orientation: event.orientation,            
    tilt: event.tilt,                          
    platformData: event.platformData,          
    synthesized: event.synthesized,            
    embedderId: event.embedderId,              
  );                                           
}                                                                                                                                                
```
                                                      
``` dart
// src/gestures/tap.dart
@override                                                
void handlePrimaryPointer(PointerEvent event) {          
  if (event is PointerUpEvent) {                         
    _up = event;                                         
    _checkUp();                                          
  } else if (event is PointerCancelEvent) {              
    resolve(GestureDisposition.rejected);                
    if (_sentTapDown) {                                  
      _checkCancel(event, '');                           
    }                                                    
    _reset();                                            
  } else if (event.buttons != _down!.buttons) {          
    resolve(GestureDisposition.rejected); 
    // code 3          
    stopTrackingPointer(primaryPointer!);                
  }                                                      
}  
```

### CODE REVIEW

**Comment by LinXiaoTao** [comment]
@googlebot I signed it!

**Comment by LinXiaoTao** [comment]
@googlebot I signed it!

**Comment by xu-baolin** [comment]
> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need an exemption to this rule, contact Hixie on the #hackers channel in [Chat](https://github.com/flutter/flutter/wiki/Chat).
> 
> If you are not sure if you need tests, consider this rule of thumb: the purpose of a test is to make sure someone doesn't accidentally revert the fix. Ask yourself, is there anything in your PR that you feel it is important we not accidentally revert back to how it was before your fix?
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

@LinXiaoTao Hi, This needs a test.

**Comment by LinXiaoTao** [comment]
> > It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need an exemption to this rule, contact Hixie on the #hackers channel in [Chat](https://github.com/flutter/flutter/wiki/Chat).
> > If you are not sure if you need tests, consider this rule of thumb: the purpose of a test is to make sure someone doesn't accidentally revert the fix. Ask yourself, is there anything in your PR that you feel it is important we not accidentally revert back to how it was before your fix?
> > **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.
> 
> @LinXiaoTao Hi, This needs a test.

Hi，Does it mean writing test cases?

**Comment by xu-baolin** [comment]
Yes.

**Comment by LinXiaoTao** [comment]
@xu-baolin Hi,Can you help me review the code again.

**Comment by LinXiaoTao** [comment]
@dreveman Hi,Can you help me review the code.

File: packages/flutter/test/gestures/resampler_test.dart [hunk 1]
```diff
@@ -153,6 +153,8 @@ void main() {
     expect(result[4].position.dy, 15.0);
     expect(result[4].delta.dx, 10.0);
     expect(result[4].delta.dy, -10.0);
+    // buttons field needs to be a valid value
+    expect(result[4].buttons != 0, true);
```
Comment (dreveman) [inline packages/flutter/test/gestures/resampler_test.dart:157]:
```suggestion
    expect(result[4].buttons, kPrimaryButton);
```

File: packages/flutter/test/gestures/resampler_test.dart [hunk 2]
```diff
@@ -153,6 +153,8 @@ void main() {
     expect(result[4].position.dy, 15.0);
     expect(result[4].delta.dx, 10.0);
     expect(result[4].delta.dy, -10.0);
+    // buttons field needs to be a valid value
```
Comment (dreveman) [inline packages/flutter/test/gestures/resampler_test.dart:156]: you can remove this line after changing the line below to the suggestion

**Review by dreveman — CHANGES_REQUESTED** [review]
Good catch!

File: packages/flutter/lib/src/gestures/resampler.dart [hunk 3]
```diff
@@ -87,7 +87,7 @@ class PointerEventResampler {
       device: event.device,
       position: position,
       delta: delta,
-      buttons: event.buttons,
+      buttons: event.buttons | kPrimaryButton,
```
[the remark this answers is not in the document]
Comment (LinXiaoTao) [reply packages/flutter/lib/src/gestures/resampler.dart:90]: `event.buttons | kPrimaryButton `just make sure to have at least the default value kPrimaryButton.
The values ​​of kPrimaryButton, kSecondaryButton and kTertiaryButton are all greater than 0.
``` dart
const int kPrimaryButton = 0x01;
const int kSecondaryButton = 0x02;
const int kTertiaryButton = 0x04;
```

[the remark this answers is not in the document]
Comment (LinXiaoTao) [reply packages/flutter/lib/src/gestures/resampler.dart:90]: > I don't think we should be changing this here as it would result in incorrect behavior if kSecondaryButton was pressed.
> 
> Can we instead introduce a _hasButtons field (`int _hasButtons = 0;` after line 43) that is updated from event.buttons just after line 211, add `final int hadButtons = _hasButtons;` just after line 207, and then pass the hadButtons value to _toMoveOrHoverEvent at line 238?
> 
> You'll have to update _toMoveOrHoverEvent, _toMoveEvent and _toHoverEvent to take a `int buttons` argument in addition to the existing arguments for this.

`event.buttons | kPrimaryButton `just make sure to have at least the default value kPrimaryButton.
The values ​​of kPrimaryButton, kSecondaryButton and kTertiaryButton are all greater than 0.
``` dart
const int kPrimaryButton = 0x01;
const int kSecondaryButton = 0x02;
const int kTertiaryButton = 0x04;
```

File: packages/flutter/test/gestures/resampler_test.dart (hunk 1 above)
Comment (LinXiaoTao) [reply packages/flutter/test/gestures/resampler_test.dart:157]: Maybe I can change it to
``` dart
expect(result[4].buttons > 0, true);
```
or
``` dart
expect(result[4].buttons == kPrimaryButton || result[4].buttons == kSecondaryButton || result[4].buttons == kTertiaryButton, true);
```
Because PointerUpEvent.buttons may not be kPrimaryButton.

File: packages/flutter/lib/src/gestures/resampler.dart (hunk 3 above)
[the remark this answers is not in the document]
Comment (LinXiaoTao) [reply packages/flutter/lib/src/gestures/resampler.dart]: > I don't think we should be changing this here as it would result in incorrect behavior if kSecondaryButton was pressed.
> 
> Can we instead introduce a _hasButtons field (`int _hasButtons = 0;` after line 43) that is updated from event.buttons just after line 211, add `final int hadButtons = _hasButtons;` just after line 207, and then pass the hadButtons value to _toMoveOrHoverEvent at line 238?
> 
> You'll have to update _toMoveOrHoverEvent, _toMoveEvent and _toHoverEvent to take a `int buttons` argument in addition to the existing arguments for this.

Hi, please help me to review again.

File: packages/flutter/lib/src/gestures/resampler.dart [hunk 4]
```diff
@@ -42,12 +42,14 @@ class PointerEventResampler {
...
   bool _isDown = false;
   int _pointerIdentifier = 0;
+  int _hasButtons = 0;
 
   PointerEvent _toHoverEvent(
     PointerEvent event,
     Offset position,
     Offset delta,
     Duration timeStamp,
+    int hadButtons,
```
Comment (dreveman) [inline packages/flutter/lib/src/gestures/resampler.dart:52]:
```suggestion
    int buttons,
```

File: packages/flutter/lib/src/gestures/resampler.dart [hunk 5]
```diff
@@ -79,6 +81,7 @@ class PointerEventResampler {
     Offset delta,
     int pointerIdentifier,
     Duration timeStamp,
+    int hadButtons,
```
Comment (dreveman) [inline packages/flutter/lib/src/gestures/resampler.dart:84]:
```suggestion
    int buttons,
```

File: packages/flutter/lib/src/gestures/resampler.dart [hunk 6]
```diff
@@ -87,7 +90,7 @@ class PointerEventResampler {
       device: event.device,
       position: position,
       delta: delta,
-      buttons: event.buttons,
+      buttons: hadButtons,
```
Comment (dreveman) [inline packages/flutter/lib/src/gestures/resampler.dart:93]:
```suggestion
      buttons: buttons,
```

File: packages/flutter/lib/src/gestures/resampler.dart [hunk 7]
```diff
@@ -113,9 +116,12 @@ class PointerEventResampler {
     int pointerIdentifier,
     Duration timeStamp,
     bool isDown,
+    int hadButtons,
```
Comment (dreveman) [inline packages/flutter/lib/src/gestures/resampler.dart:119]:
```suggestion
    int buttons,
```

File: packages/flutter/lib/src/gestures/resampler.dart [hunk 8]
```diff
@@ -113,9 +116,12 @@ class PointerEventResampler {
...
   ) {
-    return isDown ? _toMoveEvent(event, position, delta, pointerIdentifier, timeStamp)
-                  : _toHoverEvent(event, position, delta, timeStamp);
+    return isDown
+        ? _toMoveEvent(
+            event, position, delta, pointerIdentifier, timeStamp, hadButtons)
```
Comment (dreveman) [inline packages/flutter/lib/src/gestures/resampler.dart:123]:
```suggestion
            event, position, delta, pointerIdentifier, timeStamp, buttons)
```

File: packages/flutter/lib/src/gestures/resampler.dart [hunk 9]
```diff
@@ -113,9 +116,12 @@ class PointerEventResampler {
...
+        : _toHoverEvent(event, position, delta, timeStamp, hadButtons);
```
Comment (dreveman) [inline packages/flutter/lib/src/gestures/resampler.dart:124]:
```suggestion
        : _toHoverEvent(event, position, delta, timeStamp, buttons);
```

**Review by dreveman — CHANGES_REQUESTED** [review]
thanks! looks good after making suggested changes

**Review by dreveman — APPROVED** [review]

**Comment by dreveman** [comment]
Please go ahead and merge this after signing the cla.

**Comment by LinXiaoTao** [comment]
> Please go ahead and merge this after signing the cla.

Hi, I have signed cla. Could it be because of your email address in the submission?

**Comment by LinXiaoTao** [comment]
@googlebot I fixed it.

**Comment by dreveman** [comment]
Yes, my alternative email was causing problems. I merged this for you. Thanks for your contribution!
