### PR TITLE
Drawer edge drag width improvements

### LINKED ISSUE #36929: Scaffold drawer start drag point too much near the edge
I'm receiving a lot of bug reports saying that scaffold drawer doesn't work, but actually it is working just the start point for dragging is too much near the edge. I'm unsure for android users, but iOS users consider starting point to be too much near the edge and because of this many users are not aware that drawer exists in the app. They try the gesture but it fails. Solution would be to either increase offset from the edge for starting the gesture or to allow developer to insert his own offset value. 
This is same for both left and right scaffold drawers.

```
 Flutter (Channel beta, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

### LINKED ISSUE #38313: Drawer area width does not properly account for notched devices
Currently, when a Drawer is implemented on a notched device, the draggable edge area width to open the drawer is set to the size of the notch itself, when it should be set to the area of the notch _plus_ the default width of 20.0.

To reproduce, use a notched iPhone and rotate to landscape. Note that the Drawer can only be dragged open if done so within the area surrounding the notch.

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

The current edge width to open a drawer when dragged is set to 20.0. However, with a notched device, the edge width is set to `MediaQuery.of(context).padding` value. This PR addresses two issues:

1) Fix padding for notched devices
Since the edge width is set to `MediaQuery.of(context).padding`, the area to drag is obscured by the notch, and the only way to open the drawer would be to drag from within the non obscured areas of the screen around the notch. This fix increases that draggable area to `MediaQuery.of(context).padding` + 20.0.

2) Custom edge drag width for drawers
This new property, `Scaffold.drawerEdgeDragWidth` allows developers to set their own custom drag widths to open drawers in the event that they need to increase sensitivity for their users. 

## Related Issues

Fixes https://github.com/flutter/flutter/issues/36929
Fixes https://github.com/flutter/flutter/issues/38313

## Tests

I added the following tests:
- A test verifying that the custom edge drag width is used.

I modified the following tests:
- The RTL and LTR tests for drawers with MediaQuery.padding values

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/drawer.dart [hunk 1]
```diff
@@ -228,6 +229,17 @@ class DrawerController extends StatefulWidget {
   /// By default, the color used is [Colors.black54]
   final Color scrimColor;
 
+  /// The horizontal width from the edge of the screen that will respond to a
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/drawer.dart]: Maybe: 

The width of the area within which a horizontal swipe will open the drawer is the larger of this value and the corresponding [MediaQuery] padding inset.

File: packages/flutter/lib/src/material/drawer.dart [hunk 2]
```diff
@@ -228,6 +229,17 @@ class DrawerController extends StatefulWidget {
...
+  /// drag gesture to open the drawer.
+  ///
+  /// By default, the value used is 20.0.
+  ///
+  /// If `MediaQuery.of(context).padding` is larger than the default drawer
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/drawer.dart]: It's good to make this all a bit more specific here however `MediaQuery.of(context).padding`  isn't a value that can be compared with 20. And "properly acommodate..." doesn't really explain why we're doing this. In fact it's not clear to me why we factor in the padding. If the padding is only as big as the display notches, doesn't that just guarantee that the drag area will be obscured by the notch? 

I realize that you're just documenting the way things were written already.

Comment (shihaohong) [reply packages/flutter/lib/src/material/drawer.dart]: It seems that this is a bug. I think the implementation should be to set it to the padding + 20.0 to account for the notch. I filed https://github.com/flutter/flutter/issues/38313 to track the issue, but will attempt to resolve this in this PR as well.

File: packages/flutter/lib/src/material/drawer.dart [hunk 3]
```diff
@@ -228,6 +227,14 @@ class DrawerController extends StatefulWidget {
   /// By default, the color used is [Colors.black54]
   final Color scrimColor;
 
+  /// The width of the area within which a horizontal swipe will open the
+  /// drawer.
+  ///
+  /// By default, the value used is 20.0 added to the value of
+  /// `MediaQuery.of(context).padding`. This ensures that the drag area for
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/drawer.dart]: You're adding 20 to the padding edge that corresponds to [alignment], not to the padding itself.

File: packages/flutter/lib/src/material/drawer.dart [hunk 4]
```diff
@@ -427,12 +434,17 @@ class DrawerControllerState extends State<DrawerController> with SingleTickerPro
...
     final EdgeInsets padding = MediaQuery.of(context).padding;
-    double dragAreaWidth = drawerIsStart ? padding.left : padding.right;
-
-    if (Directionality.of(context) == TextDirection.rtl)
-      dragAreaWidth = drawerIsStart ? padding.right : padding.left;
+    final TextDirection textDirection = Directionality.of(context);
+
+    double dragAreaWidth = widget.edgeDragWidth;
+    if (widget.edgeDragWidth == null) {
+      if (drawerIsStart && textDirection == TextDirection.ltr || !drawerIsStart && textDirection == TextDirection.rtl) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/drawer.dart]: Although it may not make things clearer, flutter style is to use a switch for textDirection.

File: packages/flutter/lib/src/material/scaffold.dart [hunk 5]
```diff
@@ -1140,6 +1141,17 @@ class Scaffold extends StatefulWidget {
   /// {@macro flutter.material.drawer.dragStartBehavior}
   final DragStartBehavior drawerDragStartBehavior;
 
+  /// The horizontal width from the edge of the screen that will respond to a
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/scaffold.dart]: It looks like this comment still needs to be updated.

File: packages/flutter/lib/src/material/drawer.dart [hunk 6]
```diff
@@ -427,12 +437,30 @@ class DrawerControllerState extends State<DrawerController> with SingleTickerPro
...
-
-    if (Directionality.of(context) == TextDirection.rtl)
-      dragAreaWidth = drawerIsStart ? padding.right : padding.left;
+    final TextDirection textDirection = Directionality.of(context);
+
+    double dragAreaWidth = widget.edgeDragWidth;
+    if (widget.edgeDragWidth == null) {
+      switch (textDirection) {
+        case TextDirection.ltr: {
+          if (drawerIsStart) {
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/drawer.dart]: Or
```
dragAreaWidth = _kEdgeDragWidth + (drawerIsStart ? padding.left : padding.right);
```

File: packages/flutter/lib/src/material/drawer.dart [hunk 7]
```diff
@@ -228,6 +227,17 @@ class DrawerController extends StatefulWidget {
   /// By default, the color used is [Colors.black54]
   final Color scrimColor;
 
+  /// The width of the area within which a horizontal swipe will open the
+  /// drawer.
+  ///
+  /// By default, the value used is 20.0 added to the padding edge of
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/drawer.dart]: NICE

**Review by HansMuller — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/drawer.dart (hunk 6 above)
Comment (shihaohong) [reply packages/flutter/lib/src/material/drawer.dart]: This looks much better :)
