### PR TITLE
fix route annoucement for first route and last route

### LINKED ISSUE #57133: CupertinoTabView cannot read previous tile when show a new dialog
I use a `CupertinoTabView` , and use `showCupertinoDialog` to let the user enter something. But when the dialog is shown, when I try to close it ` Navigator.pop(context);` is hows me the error below.

I tried to replace `CupertinoTabView` , it works.  Maybe a bug of `CupertinoTabView`?

```dart
class HomePage extends StatefulWidget {
  HomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {


  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      tabBar: bottomNavigationBar(),
      tabBuilder: (context, i) {
        return CupertinoTabView(
          builder:(context) => Scaffold(
              floatingActionButton: FloatingEditor(),
              floatingActionButtonLocation:
                  FloatingActionButtonLocation.centerFloat,
              body: _pageOptions[i]),
        );
      },
    );
  }
}


```

```dart

class TodobookEntryPageProvider extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) =>
          TodobooksEntriesBloc()..add(TodobookEntriesLoadSuccess()),
      child: CupertinoPageScaffold(
          navigationBar: _navigationBar(context),
          child: TodobookEntryPage()),
    );
  }

  Widget _navigationBar(BuildContext context) {
    return CupertinoNavigationBar(

        middle: Text("Todobook"),
        trailing: Builder(
          builder: (context) => Wrap(
            children: <Widget>[
              NavigationBarButton(
                barIcon: Icons.add_circle,
                onPressed: () {
                  _showNewTodobookDialog(context);
                },
              ),
              SizedBox(width: 20.0),
              NavigationBarButton(
                barIcon: Icons.more_horizontal,
                onPressed: () {
                  //todo: do something.
                },
              ),
              SizedBox(width: 5.0),
            ],
          ),
        ));
  }

  void _showNewTodobookDialog(BuildContext context) {
    showCupertinoDialog(
        context: context,
        builder: (_) => PromptTextDialog(
              title: Text("New Todobook"),
              subtitle: Text("Enter the name of new Todobook"),
              onCancel: (val) {
                print(val);
                Navigator.pop(context);
              },
              onSave: (val) {
                print(val);
                Todobook newNb = Todobook.generateNew(title: val, userId: 1);
                BlocProvider.of<TodobooksEntriesBloc>(context)
                    .add(TodobookEntryAdded(newNb));
                Navigator.pop(context);
              },
            ));
  }
}
```

```
The following assertion was thrown building _BackLabel(dirty):
Cannot read the previousTitle for a route that has not yet been installed
'package:flutter/src/cupertino/route.dart':
Failed assertion: line 147 pos 7: '_previousTitle != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  CupertinoNavigationBar file:///Users/alex/AndroidStudioProjects/todoprac/lib/views/todobook_entries_page.dart:39:12
When the exception was thrown, this was the stack: 
#2      CupertinoPageRoute.previousTitle (package:flutter/src/cupertino/route.dart:147:7)
#3      _BackLabel.build (package:flutter/src/cupertino/nav_bar.dart:1457:41)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
...
```

and some time it throws
```
The following assertion was thrown while handling a gesture:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

```

### PR DESCRIPTION
**Pull request by chunhtai**
## Description

The navigator refactor updates how we detect a previous or next route has changed. We keep track of the last announced previous and next route, and calls didChangePrevious or didChangeNext when it changes. However, the initial value of the cache is null which cause the first route stop reporting the didChangePrev because previous route of the first route is null. Same thing for the didChangeNext.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/57133

## Tests

I added the following tests:

See files

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/widgets/navigator_test.dart [hunk 1]
```diff
@@ -1813,6 +1813,57 @@ void main() {
...
+          );
+          return secondRoute;
+        },
+      ),
+    );
+    await tester.pumpAndSettle();
+
+    expect(previousOfFirst, isNull);
+    expect(nextOfFirst, secondRoute);
+    expect(popNextOfFirst is NotAnnounced, isTrue);
```
Comment (goderbauer) [inline packages/flutter/test/widgets/navigator_test.dart:1857]: Here and elsewhere: use the isA matcher: https://api.flutter.dev/flutter/package-matcher_matcher/isA.html

**Review by goderbauer — APPROVED** [review]
LGTM
