### PR TITLE
Fix semantics_tester

### LINKED ISSUE #34363: SemanticsTester doesn't match correctly on last child
The following test should not pass, but does:

```dart
testWidgets('recognizers split semantic node', (WidgetTester tester) async {
    final SemanticsTester semantics = SemanticsTester(tester);
    const TextStyle textStyle = TextStyle(fontFamily: 'Ahem');
    await tester.pumpWidget(
      Text.rich(
        TextSpan(
          children: <TextSpan>[
            const TextSpan(text: 'hello'),
            TextSpan(text: 'world', recognizer: TapGestureRecognizer()..onTap = () { }),
          ],
          style: textStyle,
        ),
        textDirection: TextDirection.ltr,
        maxLines: 1,
      ),
    );
    final TestSemantics expectedSemantics = TestSemantics.root(
      children: <TestSemantics>[
        TestSemantics.rootChild(
          children: <TestSemantics>[
            TestSemantics(
              label: 'hello',
              textDirection: TextDirection.ltr,
            ),
            TestSemantics(),
          ],
        ),
      ],
    );
    expect(semantics, hasSemantics(expectedSemantics, ignoreTransform: true, ignoreId: true, ignoreRect: true));
    semantics.dispose();
  });
```

### PR DESCRIPTION
**Pull request by dnfield**
## Description

Semantics_tester was broken.  If a node had multiple children, it was checking the first and then bailing.

Fixing that has revealed other bugs.

I talked with @GaryQian and I think the test_text tests now have the correct fixes applied in paragraph.dart.  Gary to review.

I'm not as confident on the other changes - DatePicker seems like it may be right now, ~~but not sure why we get all those empty nodes. /cc @goderbauer and/or @darrenaustin~~ we get them because there are empty container placeholders there.

Sliver tests I think are right - they were just missing implicit scrolling flags and not caught previously due to this bug.

Semantics traversal test seems like it may be a different bug.  It's possible the 64 bit rect stuff impacted this and we didn't catch it because of the brokeness of the tester.

This regression was introduced in #16253, where a `return true` that used to live in a closure was moved to a `for` loop.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/34363

## Tests

I added the following tests:

Added a sanity check for the tester.  This test fails without these changes.  This is similar to a test I was trying to write, and I was confused about why it was passing when it was so clearly wrong.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/test/widgets/semantics_tester_test.dart [hunk 1]
```diff
@@ -0,0 +1,42 @@
+
```
Comment (jonahwilliams) [inline packages/flutter/test/widgets/semantics_tester_test.dart]: Nit: missing license header

File: packages/flutter/test/widgets/semantics_traversal_test.dart [hunk 2]
```diff
@@ -202,13 +202,13 @@ void main() {
     await tester.test(
       textDirection: TextDirection.ltr,
       children: children,
-      expectedTraversal: 'A B C D E F G H I J K L M',
+      expectedTraversal: 'A B C D E G H F I J K L M',
```
Comment (jonahwilliams) [inline packages/flutter/test/widgets/semantics_traversal_test.dart]: This is ... odd

Comment (dnfield) [reply packages/flutter/test/widgets/semantics_traversal_test.dart]: Yes, I think something's wrong here.

Unfortunately, the regression in semantics_tester was introduced in the same commit where these tests were added.  I tried checking out d35409629994769a8ce26cad4651e20ab07280d7 and modifying the tester so that it's closer to the state in this PR and those tests still pass.  I'll try to figure out what's going on here, unless @yjbanov might know.

Comment (dnfield) [reply packages/flutter/test/widgets/semantics_traversal_test.dart]: Looks like this regressed in https://github.com/flutter/flutter/commit/f2442b8a13b4100a0734aa4cbf30bf0ff89ce5fd, which was part of v0.8.0 tag.

Comment (dnfield) [reply packages/flutter/test/widgets/semantics_traversal_test.dart]: (And wasn't caught because the tester was broken)

Comment (jonahwilliams) [reply packages/flutter/test/widgets/semantics_traversal_test.dart]: 🤕

File: packages/flutter/test/material/search_test.dart [hunk 3]
```diff
@@ -496,6 +496,17 @@ void main() {
                 label: routeName,
                 textDirection: TextDirection.ltr,
                 children: <TestSemantics>[
+                  TestSemantics(
```
Comment (dnfield) [inline packages/flutter/test/material/search_test.dart]: If this isn't correct, we have to put a sort key on it I think.

File: packages/flutter/test/widgets/text_test.dart [hunk 4]
```diff
@@ -414,7 +414,7 @@ void main() {
             TestSemantics(
               label: 'INTERRUPTION',
               textDirection: TextDirection.rtl,
-              rect: const Rect.fromLTRB(448.0, 0.0, 488.0, 80.0),
+              rect: const Rect.fromLTRB(0.0, 0.0, 40.0, 80.0),
```
Comment (dnfield) [inline packages/flutter/test/widgets/text_test.dart]: @GaryQian is this expected?

File: packages/flutter/test/widgets/semantics_traversal_test.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter/test/widgets/semantics_traversal_test.dart]: Got this sorted out - changed the deflate constant from 0.1 to 1e-15.  Anything bigger than 1e-15 was failing.

**Review by jonahwilliams — APPROVED** [review]
LGTM for changes to rect deflate

**Comment by yjbanov** [comment]
Good catch! Thanks for fixing!

**Review by yjbanov — APPROVED** [review]
lgtm

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 5]
```diff
@@ -2230,7 +2230,7 @@ class _SemanticsSortGroup extends Comparable<_SemanticsSortGroup> {
     final List<_BoxEdge> edges = <_BoxEdge>[];
     for (SemanticsNode child in nodes) {
       // Using a small delta to shrink child rects removes overlapping cases.
-      final Rect childRect = child.rect.deflate(0.1);
+      final Rect childRect = child.rect.deflate(1e-15);
```
[the remark this answers is not in the document]
Comment (dnfield) [reply packages/flutter/lib/src/semantics/semantics.dart]: My thought with this is that removing a trivially small amount like this should still make them not evaluate as overlapping.

File: packages/flutter/test/material/date_picker_test.dart [hunk 6]
```diff
@@ -449,14 +449,29 @@ void _tests() {
...
                     children: <TestSemantics>[
                       TestSemantics(
                         children: <TestSemantics>[
                           TestSemantics(
                             children: <TestSemantics>[
                               TestSemantics(
+                                id: 11,
+                                flags: <SemanticsFlag>[SemanticsFlag.hasImplicitScrolling],
                                 children: <TestSemantics>[
+                                  TestSemantics(),
```
Comment (goderbauer) [inline packages/flutter/test/material/date_picker_test.dart]: Why do we have all these extra empty nodes? They really shouldn't be here...

File: packages/flutter/test/material/search_test.dart (hunk 3 above)
Comment (goderbauer) [reply packages/flutter/test/material/search_test.dart]: This seems wrong if things are dumped in traversal order (which I think they are).

I am surprised that it would need a sort key, though. The suggestions come physically after the back button and the text field.

(We should verify that talkback and voiceover do the right thing here on device)

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 5 above)
[the remark this answers is not in the document]
Comment (goderbauer) [reply packages/flutter/lib/src/semantics/semantics.dart]: Our original thought here was that even when things are overlapping visibly, if the overlap is smallish, it shouldn't count as overlapping...

File: packages/flutter/test/widgets/semantics_tester_test.dart [hunk 7]
```diff
@@ -0,0 +1,44 @@
+// Copyright 2019 The Flutter Authors. All rights reserved.
```
Comment (goderbauer) [inline packages/flutter/test/widgets/semantics_tester_test.dart]: +1 for adding these tests! Thank you!

**Comment by goderbauer** [comment]
> we get them because there are empty container placeholders there.

What does this mean? Empty containers should not produce a semantics node?

File: packages/flutter/test/material/date_picker_test.dart (hunk 6 above)
Comment (dnfield) [reply packages/flutter/test/material/date_picker_test.dart]: I believe they're containers/placeholders to make the calendar day fall under the right slot.

Comment (goderbauer) [reply packages/flutter/test/material/date_picker_test.dart]: Empty placeholders should not have a semantics node, though. I thought we filter those out...

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 5 above)
[the remark this answers is not in the document]
Comment (dnfield) [reply packages/flutter/lib/src/semantics/semantics.dart]: That ends up breaking traversal order :(

**Comment by GaryQian** [comment]
Paragraph changes LGTM!

File: packages/flutter/test/material/date_picker_test.dart (hunk 6 above)
Comment (dnfield) [reply packages/flutter/test/material/date_picker_test.dart]: They're from the `ExcludeSemantics` around the weekday header and more empty nodes for the containers for placeholders.

So 7 weekday headers + 5 placeholder containers = 12 empty semantics nodes.

Comment (dnfield) [reply packages/flutter/test/material/date_picker_test.dart]: I'm fine with changing that but I think if we do it should be in a separate PR.

File: packages/flutter/test/widgets/text_test.dart (hunk 4 above)
Comment (GaryQian) [reply packages/flutter/test/widgets/text_test.dart]: This may actually be a bug, but I'll look at that separately. I think in practice the rects still show up in the right place after transforms, but it may be better to make sure the values are rolled into here too. I think we can go ahead with this for now in the context of your semantics fix and ill fix this when I take a deeper look.

File: packages/flutter/test/material/date_picker_test.dart (hunk 6 above)
Comment (goderbauer) [reply packages/flutter/test/material/date_picker_test.dart]: OK, Can you add a TODO and file an issue so it doesn't get lost?

File: packages/flutter/test/widgets/text_test.dart (hunk 4 above)
Comment (goderbauer) [reply packages/flutter/test/widgets/text_test.dart]: If we don't fix this here, we should at least file an issue and link it from here.

File: packages/flutter/test/material/date_picker_test.dart (hunk 6 above)
Comment (dnfield) [reply packages/flutter/test/material/date_picker_test.dart]: https://github.com/flutter/flutter/issues/34431

File: packages/flutter/test/widgets/text_test.dart (hunk 4 above)
Comment (GaryQian) [reply packages/flutter/test/widgets/text_test.dart]: https://github.com/flutter/flutter/issues/34433

File: packages/flutter/test/material/search_test.dart (hunk 3 above)
Comment (dnfield) [reply packages/flutter/test/material/search_test.dart]: This is actually how things are ordered today.  It's not very clear to me why that's the case - even without any changes here.  Filed https://github.com/flutter/flutter/issues/34432 and added a TODO.

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 5 above)
[the remark this answers is not in the document]
Comment (dnfield) [reply packages/flutter/lib/src/semantics/semantics.dart]: So what's the vote here?  Add the very small deflate, or remove it entirely and add a TODO?

File: packages/flutter/test/widgets/text_test.dart (hunk 4 above)
Comment (dnfield) [reply packages/flutter/test/widgets/text_test.dart]: I believe I have a fix for this that I'll be landing separately.  I have a patch ready to go that will be changing this again, but don't want to fiddle with it or risk having yet another piece to worry about as this patch is blcoking the google3 roll now.

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 5 above)
[the remark this answers is not in the document]
Comment (jonahwilliams) [reply packages/flutter/lib/src/semantics/semantics.dart]: The canonical example is the categories on the flutter gallery home page. It should go left to right, but before it was going top to bottom.

If it still goes left to right with this change I'm okay with it. If it doesn't, we might as well remove the deflate and go back to the drawing board

File: packages/flutter/test/widgets/semantics_traversal_test.dart (hunk 2 above)
Comment (dnfield) [reply packages/flutter/test/widgets/semantics_traversal_test.dart]: Pushed this back to .1.  The right fix is to update the traversal logic.

File: packages/flutter/test/material/search_test.dart (hunk 3 above)
Comment (dnfield) [reply packages/flutter/test/material/search_test.dart]: Talked offline - will close the other bug.  Traversal order test was broken and needed to be updated.

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 5 above)
[the remark this answers is not in the document]
Comment (dnfield) [reply packages/flutter/lib/src/semantics/semantics.dart]: The categories sample still worked with this change, but it's actually the traversal order we want to change (which was going top to bottom instead of left to right).  I've updated that test to go left to right and put back the deflate to 0.1.

**Review by goderbauer — APPROVED** [review]
LGTM

Thank you!
