### PR TITLE
[flutter_tools] fix RangeError in gen-l10n by checking for empty string

### LINKED ISSUE #107593: [flutter_tools] RangeError during generateLocalizationsSyntheticPackage
On `beta/3.1.0-9.0.pre`
with command: `flutter run --machine --start-paused --no-sound-null-safety -d 1BB38FA9-F01A-4336-BD1E-BB25E51AF94E --devtools-server-address http://127.0.0.1:9100/ --target lib/main.dart`

```
RangeError: RangeError (index): Invalid value: Valid value range is empty: 0
at _StringBase.[](string_patch.dart:260)
at LocalizationsGenerator._isValidGetterAndMethodName(gen_l10n.dart:1048)
at LocalizationsGenerator.loadResources(gen_l10n.dart:1073)
at generateLocalizations(gen_l10n.dart:68)
at GenerateLocalizationsTarget.build(localizations.dart:56)
at _BuildInstance._invokeInternal(build_system.dart:839)
at <asynchronous gap>(async)
at FlutterBuildSystem.build(build_system.dart:606)
at <asynchronous gap>(async)
at generateLocalizationsSyntheticPackage(generate_synthetic_packages.dart:58)
at <asynchronous gap>(async)
at FlutterCommand.verifyThenRunCommand(flutter_command.dart:1336)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1195)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:209)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:281)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:229)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:62)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:94)
at <asynchronous gap>(async)
```

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/107593

### CODE REVIEW

File: packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart [hunk 1]
```diff
@@ -124,6 +124,9 @@ class L10nException implements Exception {
   L10nException(this.message);
 
   final String message;
+
+  @override
+  String toString() => message;
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart:129]: Without a toString() implementation, it was difficult to debug test failures

**Review by Jasguerrero — APPROVED** [review]
LGTM
