### PR TITLE
Dismiss text selection toolbar with ESC

### LINKED ISSUE #98163: The escape key should close the right click menu on desktop
When the right click menu is open, pressing the escape key should close it.  I confirmed that this is the native behavior on Mac and Windows.  I assume Linux is the same but I haven't tried.

### Steps to reproduce

 1. Run any Flutter app with a text field on a desktop platform (example given below).
 2. Right click on the text field.  The context menu shows.
 3. Press the escape key.

Expected: The context menu closes.
Actual: Nothing happens and the context menu remains on the screen.

### Solution
We could add a text editing shortcut for this and it should work for now, but if we allow context menus outside of EditableText (as mentioned in https://github.com/flutter/flutter/issues/90563), then the Shortcuts widget won't receive the escape when nothing is focused and it won't always work.

@gspencergoog Is it possible to receive a Shortcut when nothing is focused?

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter Demo'),
        ),
        body: const Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by markusaksli-nc**
Dismiss the EditableText selection controls toolbar by pressing ESC using the DismissIntent. @justinmc since this is a global shortcut in `app.dart` it should circumvent the concern about not always dismissing the menu? 

This does come with side-effects like no longer being able to dismiss something like a `DialogueRoute` with ESC when it contains a text field that is focused. Maybe that makes more sense if you can unfocus EditableText by pressing ESC as well.

Fixes https://github.com/flutter/flutter/issues/98163

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -3150,6 +3150,7 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     ReplaceTextIntent: _replaceTextAction,
     UpdateSelectionIntent: _updateSelectionAction,
     DirectionalFocusIntent: DirectionalFocusAction.forTextField(),
+    DismissIntent: CallbackAction<DismissIntent>(onInvoke: (_) => hideToolbar(false)),
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:3153]: I just tried this on a native iOS app on iPad with a physical keyboard, and pressing escape did nothing.  Maybe do a switch statement here and don't hide the toolbar on iOS?  And try to figure out what happens on Android if you can.

You can just merge this PR now if you want though since it's otherwise good to go.  Maybe open a separate PR to do the switch statement or open an issue for it.  Up to you.

**Review by justinmc — APPROVED** [review]
LGTM 👍 

One comment below about iOS/Android with a native keyboard, but I realize that's probably pretty niche.

**Comment by markusaksli-nc** [comment]
Merging this for now, it seems like it isn't supposed to dismiss the menu on both Android and iOS but for some reason, it already doesn't? Looking into this more tomorrow.

**Comment by justinmc** [comment]
Sounds good, interesting that the menu isn't dismissed already...
