### PR TITLE
Fix: Magnifier appears and won't dismiss

### LINKED ISSUE #128321: Android, TextFormField: when onTapOutside at left bottom corner magnification appears and doesn't disappear
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create `TextFormField` widget;
2. field `enableInteractiveSelection` set to `true`;
3. set field onTapOutside: `onTapOutside: (event) => FocusManager.instance.primaryFocus?.unfocus()`;
4. tap on `TextFormField` to get focused on it;
5. tap outside of `TextFormField` near of left bottom corner (about 10px from corner).

### Expected results

When tap outside of `TextFormField` widget becomes unfocused.

### Actual results

`TextFormField` becomes unfocused, but sometimes magnification appears and doesn't disappear. 

At video demonstration you can see, that I got this effect only at second attempt. Same for apk. 
If `enableInteractiveSelection` set to `false` effect is not reproduced.

On IOS this effect is not reproduced.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Builder(builder: (context) {
            return ElevatedButton(
              onPressed: () {
                Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (context) => const Screen(),
                  ),
                );
              },
              child: const Text('Navigate'),
            );
          }),
        ),
      ),
    );
  }
}

class Screen extends StatelessWidget {
  const Screen({super.key});

  @override
  Widget build(BuildContext context) {
    final list = List.generate(30, (index) => index);
    return Scaffold(
      appBar: AppBar(),
      body: Padding(
        padding: const EdgeInsets.all(20),
        child: ListView(
          children: [
            TextFormField(
              enableInteractiveSelection: true,
              onTapOutside: (event) =>
                  FocusManager.instance.primaryFocus?.unfocus(),
            ),
            ...list.map(
              (e) => ListTile(
                title: Text(e.toString()),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/65972347/a1e15692-d5e1-457c-b6e0-205876a07939

</details>

### Logs

_No response_

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4 22F66 darwin-arm64, locale ru-BY)
    • Flutter version 3.10.3 on channel stable at /Users/oleg/fvm/versions/3.7.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (4 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/oleg/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
When tapping just outside of a TextField that unfocuses itself, the magnifier appears and cannot be dismissed.

It seems like the selection handles are being built with opacity 0.0 but are still receiving the tap (as a drag start).  In the image below, the GestureDetector is given in yellow, which includes the area you need to tap to reproduce this bug:

Screenshot from 2023-06-13 10-52-56

Furthermore, I noticed that some drag event callbacks were being called even after the `_handles` had been removed by the tap.  This seems to have been caused by `OverlayEntry.remove` happening in the following frame instead of immediately.  In the meantime, the handle was still able to receive the drag gesture.

Fixes https://github.com/flutter/flutter/issues/128321

### CODE REVIEW

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 1]
```diff
@@ -1752,7 +1790,7 @@ class _SelectionHandleOverlayState extends State<_SelectionHandleOverlay> with S
 
     // Make sure the GestureDetector is big enough to be easily interactive.
     final Rect interactiveRect = handleRect.expandToInclude(
-      Rect.fromCircle(center: handleRect.center, radius: kMinInteractiveDimension/ 2),
+      Rect.fromCircle(center: handleRect.center, radius: kMinInteractiveDimension / 2),
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/text_selection.dart:1793]: Nice!

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 2]
```diff
@@ -1087,11 +1087,25 @@ class SelectionOverlay {
   final ValueChanged<DragStartDetails>? onStartHandleDragStart;
 
   void _handleStartHandleDragStart(DragStartDetails details) {
+    // Calling OverlayEntry.remove may not happen until the following frame, so
```
Comment (Renzo-Olivares) [inline packages/flutter/lib/src/widgets/text_selection.dart:1090]: Good catch! This seems like a safe fix to me.

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

File: packages/flutter/test/material/text_field_test.dart [hunk 3]
```diff
@@ -15986,6 +15986,54 @@ void main() {
...
+      // Regression test for https://github.com/flutter/flutter/issues/128321
+      await tester.pumpWidget(
+        MaterialApp(
+          home: Scaffold(
+            body: Padding(
+              padding: const EdgeInsets.all(20),
+              child: TextField(
+                magnifierConfiguration: TextMagnifierConfiguration(
+                  magnifierBuilder: (
+                      _,
```
Comment (LongCatIsLooong) [inline packages/flutter/test/material/text_field_test.dart:16000]: nit: [avoid anonymous parameter names](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-anonymous-parameter-names).

Comment (LongCatIsLooong) [reply packages/flutter/test/material/text_field_test.dart:16000]: On a side note, Github stopped syntax highlighting the file for me. Maybe that's a sign we should break this file down...

File: packages/flutter/lib/src/widgets/text_selection.dart [hunk 4]
```diff
@@ -1100,6 +1114,11 @@ class SelectionOverlay {
   final ValueChanged<DragEndDetails>? onStartHandleDragEnd;
 
   void _handleStartHandleDragEnd(DragEndDetails details) {
+    // Calling OverlayEntry.remove may not happen until the following frame, so
+    // it's possible for the handles to receive a gesture after calling remove.
+    if (_handles == null) {
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/text_selection.dart:1119]: Would this result in a unbalanced call? You're handling a handle drag event and expects an end event at some point,  but you never receives an end event because the handle being dragged becomes invisible?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart:1119]: That's true, but it's the same as the current behavior.  _handleStart/EndHandleDragEnd is never called when the bug is reproduced.

I just tried it and it looks like the same thing will happen if you suddenly remove a GestureDetector from the Widget tree:

<details>

<summary>Example of removing a GestureDetector while it's detecting a drag. Drag end is never called.</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            DisappearingWidget(),
          ],
        ),
      ),
    );
  }
}

class DisappearingWidget extends StatefulWidget {
  const DisappearingWidget({super.key});

  @override
  State<DisappearingWidget> createState() => _DisappearingWidgetState();
}

class _DisappearingWidgetState extends State<DisappearingWidget> {
  bool detecting = true;

  @override
  Widget build(BuildContext context) {
    const Text child = Text('Drag me');
    if (!detecting) {
      return child;
    }
    return GestureDetector(
      onHorizontalDragStart: (DragStartDetails details) {
        print('justin drag');
        Future<void>.delayed(const Duration(seconds: 2)).then((_) {
          print('justin turning off detection');
          setState(() {
            detecting = false;
          });
        });
      },
      onHorizontalDragUpdate: (DragUpdateDetails details) {
        print('justin drag update');
      },
      onHorizontalDragEnd: (DragEndDetails details) {
        print('justin drag end');
      },
      child: child,
    );
  }
}
```

</details>

I did just change things around so that _isDraggingStart/EndHandle are always updated though, even if this `if` is tripped.

Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/text_selection.dart:1122]: You'll get a drag cancel I think?

Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart:1122]: I just tried it again with a cancel handler and it was never called.  I've edited my previous comment with the example code to include the cancel handler.

I wonder if that's a bug and we should be calling cancel in the `dispose` method...

For completeness I also tried reproducing the bug on master with a cancel handler and the cancel handler also was not called, as expected.

**Comment by justinmc** [comment]
The Google testing failure seems to show nothing failing, even though it's red here...  Maybe I'm reading it wrong.  Pushing a merge commit to see if that fixes it.

**Comment by Renzo-Olivares** [comment]
@justinmc I think there has been problems with Google testing failing this week. I also have similar failure on my PRs.

File: packages/flutter/lib/src/widgets/text_selection.dart (hunk 4 above)
Comment (justinmc) [reply packages/flutter/lib/src/widgets/text_selection.dart:1122]: I'm merging this but I'm happy to revisit anything if you want.
