### PR TITLE
Flutter web add support for NetworkImage headers

### LINKED ISSUE #57187: [Web] add HTTP headers support for NetworkImage
Image loading on Android and iOS Application but in web version not working.

### PR DESCRIPTION
**Pull request by jonas-martinez**
This PR adds support for headers in the NetworkImage widget for Flutter Web. The [documentation](https://api.flutter.dev/flutter/painting/NetworkImage/headers.html) for the `headers` property mentions `When running flutter on the web, headers are not used.` which should not be the case or at least this property should be removed as it can be confusing.
Our specific use case was that we needed to pass an `Authorization` header using the `Image.network` component which was not possible using Flutter Web.

Fixes [57187](https://github.com/flutter/flutter/issues/57187)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/painting/_network_image_web.dart [hunk 1]
```diff
@@ -80,18 +82,24 @@ class NetworkImage
...
-    return ui.webOnlyInstantiateImageCodecFromUrl(// ignore: undefined_function, avoid_dynamic_calls
-      resolved,
-      chunkCallback: (int bytes, int total) {
-        chunkEvents.add(ImageChunkEvent(cumulativeBytesLoaded: bytes, expectedTotalBytes: total));
-      },
-    ) as Future<ui.Codec>;
+
+    final HttpRequest response = await HttpRequest.request(key.url, method: 'GET', requestHeaders: key.headers, responseType: 'arraybuffer');
+
+    if(response.status != HttpStatus.ok) {
```
Comment (asashour) [inline packages/flutter/lib/src/painting/_network_image_web.dart:92]: Shouldn't we have a space after `if`?

**Comment by goderbauer** [comment]
@jonas-martinez Can you please add a test for this?

/cc @yjbanov @GaryQian Can one of you take a look at this?

**Comment by jonas-martinez** [comment]
@googlebot I fixed it.

**Comment by jonas-martinez** [comment]
@googlebot I consent.

**Comment by jonas-martinez-lenra** [comment]
@googlebot I consent.

File: packages/flutter/lib/src/painting/_network_image_web.dart [hunk 2]
```diff
@@ -80,18 +82,24 @@ class NetworkImage
...
     image_provider.DecoderCallback decode,
     StreamController<ImageChunkEvent> chunkEvents,
-  ) {
+  ) async {
     assert(key == this);
 
     final Uri resolved = Uri.base.resolve(key.url);
-    // This API only exists in the web engine implementation and is not
-    // contained in the analyzer summary for Flutter.
-    return ui.webOnlyInstantiateImageCodecFromUrl(// ignore: undefined_function, avoid_dynamic_calls
```
Comment (yjbanov) [inline packages/flutter/lib/src/painting/_network_image_web.dart:89]: We probably want to use `webOnlyInstantiateImageCodecFromUrl` when there are no HTTP headers specified. This would allow the engine to use the plain `` element which is a better optimized method for rendering images. In particular `` supports cross-origin images (at least for now; later it will depend on COOP/COEP trends).

File: packages/flutter/lib/src/painting/_network_image_web.dart [hunk 3]
```diff
@@ -4,6 +4,8 @@
 
 
 import 'dart:async';
+import 'dart:html';
```
Comment (yjbanov) [inline packages/flutter/lib/src/painting/_network_image_web.dart:7]: Let's import this `as html`. This library has classes whose names clash with Flutter, e.g. `Element`.

File: packages/flutter/lib/src/painting/_network_image_web.dart [hunk 4]
```diff
@@ -80,18 +82,24 @@ class NetworkImage
...
-    return ui.webOnlyInstantiateImageCodecFromUrl(// ignore: undefined_function, avoid_dynamic_calls
-      resolved,
-      chunkCallback: (int bytes, int total) {
-        chunkEvents.add(ImageChunkEvent(cumulativeBytesLoaded: bytes, expectedTotalBytes: total));
-      },
-    ) as Future<ui.Codec>;
+
+    final HttpRequest response = await HttpRequest.request(key.url, method: 'GET', requestHeaders: key.headers, responseType: 'arraybuffer');
+
+    if (response.status != HttpStatus.ok) {
```
Comment (yjbanov) [inline packages/flutter/lib/src/painting/_network_image_web.dart:92]: I image more than just HTTP 200 would be acceptable here. Check out how an image request is made in the engine code: https://github.com/flutter/engine/blob/9d7bd5a6bb6ed4614c9011f373b310bb24e7ddaf/lib/web_ui/lib/src/engine/canvaskit/image.dart#L43

File: packages/flutter/lib/src/painting/_network_image_web.dart [hunk 5]
```diff
@@ -80,18 +82,24 @@ class NetworkImage
...
-    // This API only exists in the web engine implementation and is not
-    // contained in the analyzer summary for Flutter.
-    return ui.webOnlyInstantiateImageCodecFromUrl(// ignore: undefined_function, avoid_dynamic_calls
-      resolved,
-      chunkCallback: (int bytes, int total) {
-        chunkEvents.add(ImageChunkEvent(cumulativeBytesLoaded: bytes, expectedTotalBytes: total));
-      },
-    ) as Future<ui.Codec>;
+
+    final HttpRequest response = await HttpRequest.request(key.url, method: 'GET', requestHeaders: key.headers, responseType: 'arraybuffer');
```
Comment (yjbanov) [inline packages/flutter/lib/src/painting/_network_image_web.dart:90]: In order for this code to be testable, instead of calling `HttpRequest.request` directly we should call an abstraction that can be mocked out in a test. For example, the engine uses an overridable factory function: https://github.com/flutter/engine/blob/9d7bd5a6bb6ed4614c9011f373b310bb24e7ddaf/lib/web_ui/lib/src/engine/canvaskit/image.dart#L36

If the framework doesn't already have an abstraction, we might want to create one.

File: packages/flutter/lib/src/painting/_network_image_web.dart [hunk 6]
```diff
@@ -80,18 +82,24 @@ class NetworkImage
...
+
+    if (response.status != HttpStatus.ok) {
+      response.abort();
+      throw image_provider.NetworkImageLoadException(statusCode: response.status ?? 400, uri: resolved);
+    }
+
+    final Uint8List bytes = (response.response as ByteBuffer).asUint8List();
+
+    if (bytes.lengthInBytes == 0)
+        throw Exception('NetworkImage is an empty file: $resolved');
```
Comment (yjbanov) [inline packages/flutter/lib/src/painting/_network_image_web.dart:100]: Should this also be a `NetworkImageLoadException`?

**Comment by yjbanov** [comment]
This PR needs a test.

**Comment by goderbauer** [comment]
(PR triage): @jonas-martinez do you still have plans to come back to this PR to add some tests?

**Comment by jonas-martinez** [comment]
> (PR triage): @jonas-martinez do you still have plans to come back to this PR to add some tests?

I recently tried to add some tests, I could not figure out a way to make them work properly. I will not be able to work on that for 2 weeks so during this time any idea or implementation about how to add good tests to this PR would be welcomed.

Sorry for the delay

**Comment by yjbanov** [comment]
We'd probably need a test that's similar to [the engine variant](https://github.com/flutter/engine/blob/6185ae9005ca7dfce3622ce1e4688c729d342b56/lib/web_ui/test/canvaskit/image_test.dart) (the first interesting test there is probably "skiaInstantiateWebImageCodec loads an image from the network"). Since the test would be testing web-specific functionality, I would suggest to also use conditional imports in the test and import `dart:html` directly. I believe the conditional import will also allow the test to import `_network_image_web.dart` directly and mock out the network API.

When using conditional imports you need to provide both a web version and a mobile version. Since there's nothing to test for the mobile version, you can make it a noop, just an empty function that doesn't test anything ([example](https://github.com/flutter/flutter/blob/92d2856ddafbed2145d2792613256e13903aac2f/packages/integration_test/lib/integration_test.dart#L18)).

Here's a rough sketch:

```dart
// network_image_web_test.dart
import '_network_image_web_io_test.dart' if (dart.library.html) '_network_image_web_test.dart';
void main() {
  runTests();
}

// _network_image_web_io_test.dart
void runTests() {
  // This is a web-specific test. Nothing to do for AOT engine.
}

// _network_image_web_test.dart
void runTests() {
  test('loads an image from the network', () {
    ...
  });
}
```

**Comment by skia-gold** [comment]
Gold has detected about 30 new digest(s) on patchset 9.
View them at https://flutter-gold.skia.org/cl/github/85954

**Comment by goderbauer** [comment]
@jonas-martinez Looks like some checks are failing now. Can you take a look at those failures and update the PR?

**Comment by goderbauer** [comment]
Looks like there are still failures.

**Comment by jonas-martinez** [comment]
I am having some difficulties getting the two new tests to work, they work when they are run individually but not when the whole test file is run. It may have something to do with the fact that these tests are run asynchronously and that the `httpRequestFactory` is replaced in each test, causing .
I will spend more time on that later this week.

**Comment by goderbauer** [comment]
From triage: @jonas-martinez did you have some time to look at these again?

**Comment by jonas-martinez** [comment]
Yes i took some time to look at these tests but still could not find a working solution. I tried to regroup these 3 tests into one big test so that the httpServer mock would be overwritten synchronously between each step but it triggered the same problems as when they were split into 3 different tests.
I am wondering if there is something I am missing to properly mock the httpServer or if it comes from somewhere else.

**Comment by yjbanov** [comment]
I'll try running the test locally and see what I can find.

**Comment by yjbanov** [comment]
The reason the test behaves differently when running all tests at once is because the tests are fetching from the same URL, so the first test fetches and caches the image, and subsequent tests get the cached version. To fix this add the following line to `tearDown`:

```dart
PaintingBinding.instance!.imageCache!.clear();
```

**Comment by jonas-martinez** [comment]
Thank you @yjbanov ! 

Using the `PaintingBinding.instance!.imageCache!.clear();` did not work as expected so I just changed the URLs for each test.

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by Piinks** [comment]
(triage) Hey @jonas-martinez can you update your PR with the latest from master? It looks like the test failure here is unrelated to your change.
#94949 and #94948 are currently tracking this customer testing shard issue.

**Comment by jonas-martinez** [comment]
@Piinks Sure ! 
I did it but it seems that the problem did not go away.

**Comment by nt4f04uNd** [comment]
@jonas-martinez can you try doing a `git rebase` instead? It usually solves this kind of problem with custom_testing

**Comment by jonas-martinez** [comment]
I'm sorry for the review requests, I did a bad force push which added the requests automatically.

**Comment by jonas-martinez** [comment]
> @jonas-martinez can you try doing a `git rebase` instead? It usually solves this kind of problem with customer_testing

Thank you @nt4f04uNd ! Problem solved

**Comment by goderbauer** [comment]
(triage) Looks like all this needs is a secondary review now. I've asked on discord if somebody is up for it.

**Comment by tstarasinic** [comment]
What is the state with this feature ?

**Review by dnfield — APPROVED** [review]
