### PR TITLE
[tool] when writing to openssl as a part of macOS/iOS code-signing, flush the stdin stream before closing it

### LINKED ISSUE #100584: [flutter_tools] "SocketException: Write failed (OS Error: Broken pipe, errno = 32)" during `flutter create`
On [beta/2.12.0-4.1.pre](https://github.com/flutter/flutter/tree/2.12.0-4.1.pre)
Command `flutter create app`

```
Thread 0 main threadSocketException: SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
at _NativeSocket.write(socket_patch.dart:1190)
at _RawSocket.write(socket_patch.dart:1906)
at _Socket._write(socket_patch.dart:2346)
at _SocketStreamConsumer.write(socket_patch.dart:2094)
at _SocketStreamConsumer.addStream.<anonymous closure>(socket_patch.dart:2068)
at _rootRunUnary(zone.dart:1434)
at _CustomZone.runUnary(zone.dart:1335)
at _CustomZone.runUnaryGuarded(zone.dart:1244)
at _BufferingStreamSubscription._sendData(stream_impl.dart:341)
at _BufferingStreamSubscription._add(stream_impl.dart:271)
at _SyncStreamControllerDispatch._sendData(stream_controller.dart:774)
at _StreamController._add(stream_controller.dart:648)
at _StreamController.add(stream_controller.dart:596)
at _StreamSinkImpl.add(io_sink.dart:136)
at _IOSinkImpl.write(io_sink.dart:269)
at _Socket.write(socket_patch.dart:2184)
at _StdSink.write(stdio.dart:315)
at _getCodeSigningIdentityDevelopmentTeam(code_signing.dart:236)
at <asynchronous gap>(async)
at CreateCommand.runCommand(create.dart:263)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1165)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:209)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:281)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:229)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:62)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:94)
at <asynchronous gap>(async)
```

### PR DESCRIPTION
**Pull request by andrewkolos**
Fixes https://github.com/flutter/flutter/issues/100584. Might help https://github.com/flutter/flutter/issues/137184.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by jmagman** [comment]
> [WIP]

Can you convert this to a draft instead so it doesn't show up in PR triage, and we know when it's ready to review?  Thank you!

**Comment by andrewkolos** [comment]
From failing test logs:

```txt
00:24 +1074 -1: test/general.shard/ios/code_signing_test.dart: Auto signing handles stdin pipe breaking on openssl process [E]
  Error: Failed to write to openssl process. Error: SocketException: Bad pipe
  package:flutter_tools/src/base/common.dart 10:3        throwToolExit
  package:flutter_tools/src/ios/code_signing.dart 239:7  _getCodeSigningIdentityDevelopmentTeam.<fn>
  package:flutter_tools/src/base/process.dart 295:16     ProcessUtils.writeToStdinGuarded.<fn>
```

It looks like my implementation isn't catching the `SocketException`. @christopherfujino, would you mind doing a brief review pass to see if I'm missing something obvious here?

File: packages/flutter_tools/lib/src/base/process.dart [hunk 1]
```diff
@@ -271,6 +271,35 @@ abstract class ProcessUtils {
     );
     return completer.future;
   }
+
+  /// See [writelnToStdinGuarded]. This calls `stdin.write` instead of `stdin.writeln`.
+  static Future<void> writeToStdinGuarded({
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/base/process.dart:276]: should we just have `writelnToStdinGuarded` take an optional bool of whether to add a newline at the end? In which case it would make sense to rename it to writeToStdinGuarded.

File: packages/flutter_tools/lib/src/ios/code_signing.dart [hunk 2]
```diff
@@ -231,7 +231,15 @@ Future<String?> _getCodeSigningIdentityDevelopmentTeam({
 
   final Process opensslProcess = await processUtils.start(
     const <String>['openssl', 'x509', '-subject']);
-  await (opensslProcess.stdin..write(signingCertificateStdout)).close();
+
+  await ProcessUtils.writeToStdinGuarded(
+    stdin: opensslProcess.stdin,
+    line: signingCertificateStdout,
+    onError: (Object? error, _) {
+      throwToolExit('Failed to write to openssl process. Error: $error');
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/ios/code_signing.dart:239]: Is this actionable by the user? We usually throw a tool exit if either the user provided invalid inputs or the state of their machine is in some bad state. This might legitimately be a bug in tool assumptions though, right?

Also, I wonder if the fact that we were synchronously closing this after we call `.write()` (but maybe before the write happened) is why this was crashing in the first place.

File: packages/flutter_tools/lib/src/base/process.dart [hunk 3]
```diff
@@ -249,50 +249,58 @@ abstract class ProcessUtils {
...
     }
 
     runZonedGuarded(
       writeFlushAndComplete,
       (Object error, StackTrace stackTrace) {
-        onError(error, stackTrace);
+        try {
+          onError(error, stackTrace);
+        }
+        on Exception catch (e) {
```
Comment (christopherfujino) [inline packages/flutter_tools/lib/src/base/process.dart:299]: nit. put this on previous line after close curly bracket

File: packages/flutter_tools/lib/src/ios/code_signing.dart [hunk 4]
```diff
@@ -231,7 +231,15 @@ Future<String?> _getCodeSigningIdentityDevelopmentTeam({
...
   final Process opensslProcess = await processUtils.start(
     const <String>['openssl', 'x509', '-subject']);
-  await (opensslProcess.stdin..write(signingCertificateStdout)).close();
+
+  await ProcessUtils.writeToStdinGuarded(
+    stdin: opensslProcess.stdin,
+    content: signingCertificateStdout,
+    onError: (Object? error, _) {
+      throw Exception('Unexpected error when writing to openssl: $error');
+    },
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/ios/code_signing.dart:240]: If this ends up becoming a pattern (it very much probably will), we may want to consider creating like a `writeToStdinUnsafe` method that accepts something like a `message` or `taskDescription`. This new method would then throw a custom exception type from that.

File: packages/flutter_tools/lib/src/base/process.dart (hunk 1 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/base/process.dart:261]: My goal here was to preserve the user ergonomics of `IOSink` by having separate methods for `write` and `writeln`.

However, I do feel that the implementation of these are pretty complex and is probably worth sharing. In the commit [have writeToStdinGuarded share implementation with writelnToStdinGuarded](https://github.com/flutter/flutter/pull/150120/commits/848bbc58feb4cacc12bf5a287d0b7a35add6a760), I've refactored these to accomplish this. Let me know what you think.

File: packages/flutter_tools/lib/src/base/process.dart (hunk 3 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/base/process.dart]: Thanks! Addressed in [nits](https://github.com/flutter/flutter/pull/150120/commits/f728c1562a00285b05432a61fd8a4d7eb1bfa329)

File: packages/flutter_tools/lib/src/ios/code_signing.dart (hunk 2 above)
Comment (andrewkolos) [reply packages/flutter_tools/lib/src/ios/code_signing.dart]: > Is this actionable by the user? We usually throw a tool exit if either the user provided invalid inputs or the state of their machine is in some bad state. This might legitimately be a bug in tool assumptions though, right?

Great catch. I think I went on autopilot here. I've since replaced this with an `Exception` ([code](https://github.com/flutter/flutter/pull/150120/commits/69452eb6a34cf5f2f12e9d6698959608cff9e429#diff-e24013dd662b438105ef0c1d965a955e4344a6481bc2e6cbe87a30357314fb69R239)).

> Also, I wonder if the fact that we were synchronously closing this after we call .write() (but maybe before the write happened) is why this was crashing in the first place. If that is the case, this change should solve that.

This is certainly possible. As you pointed out, `Process.writeToStdinGuarded` should protect us from this going forward.

File: packages/flutter_tools/lib/src/base/process.dart (hunk 1 above)
Comment (christopherfujino) [reply packages/flutter_tools/lib/src/base/process.dart:268]: lgtm

File: packages/flutter_tools/test/general.shard/ios/code_signing_test.dart [hunk 5]
```diff
@@ -581,6 +582,59 @@ void main() {
...
+        FakeCommand(
+          command: const <String>['openssl', 'x509', '-subject'],
+          stdin: IOSink(stdinSink),
+          stdout: 'subject= /CN=iPhone Developer: Profile 1 (1111AAAA11)/OU=3333CCCC33/O=My Team/C=US',
+          completer: completer,
+        ),
+      ]);
+
+      Future<Map<String, String>?> getCodeSigningIdentities() => getCodeSigningIdentityDevelopmentTeamBuildSetting(
+        buildSettings: <String, String>{
```
Comment (christopherfujino) [inline packages/flutter_tools/test/general.shard/ios/code_signing_test.dart:617]: nit const

**Review by christopherfujino — DISMISSED** [review]
a few nits, but LGTM

File: packages/flutter_tools/lib/src/base/process.dart [hunk 6]
```diff
@@ -244,26 +244,69 @@ abstract class ProcessUtils {
...
-          completer.complete();
-        }
+      if (isLine) {
+        stdin.writeln(content);
+      } else {
+        stdin.write(content);
+      }
+      stdin.flush().then((_) {
+        completer.complete();
       });
```
Comment (andrewkolos) [inline packages/flutter_tools/lib/src/base/process.dart:297]: Not merging this yet because we probably should have a `.onError` call here.

**Comment by andrewkolos** [comment]
Heya @christopherfujino, I've reset your review since I've made some non-trivial changes since then. For your convenience, here's [the diff of what has changed](https://github.com/flutter/flutter/pull/150120/files/515a5c9d9b161653409f2b693adf4a4642cf18e5..6d106017a60ea079110cfce4fd17ce203eed9e80).

**Review by christopherfujino — APPROVED** [review]
LGTM
