### PR TITLE
Fix warnings in FGP 

### LINKED ISSUE #162695: `flutter.groovy` uses `project.exec` which is scheduled for removal in Gradle `9.0`
Noticed in a gradle build scan

```
The Project.exec(Closure) method has been deprecated. |  
  | This is scheduled to be removed in Gradle 9.0. |  
  | Use ExecOperations.exec(Action) or ProviderFactory.exec(Action) instead.
```

Used in https://github.com/flutter/flutter/blob/015cfa88d4d592aa33d3cec6de1329cd06661d70/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L1698

Gradle 9.0 is coming in Q2 2025
https://gradle.org/whats-new/gradle-9/

### PR DESCRIPTION
**Pull request by gmackall**
Fixes/suppresses all warnings:

1. Fixes https://github.com/flutter/flutter/issues/162695
2. Suppresses warnings about the various `*Variant*` imports that we use being deprecated, with comments linking to https://github.com/flutter/flutter/issues/166550 to migrate to the variant api.
3. Fixes some unused elvis operators and unneeded types provided for declarations that AGP complains about, e.g. `val fooString: String = "a string"`, and use of deprecated string related methods.
4. Follows up on https://github.com/flutter/flutter/pull/166277, as we were getting a warning mentioned in this comment https://github.com/flutter/flutter/pull/166277#issuecomment-2780184486.
5. Suppresses some warnings about unused code where the analysis couldn't properly detect it being used (i.e., it isn't unused)

(4) is more opinionated, let me know if you think it should be done in a follow up.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt [hunk 1]
```diff
@@ -342,11 +339,18 @@ class FlutterPlugin : Plugin<Project> {
                 }
                 val copyFlutterAssetsTask: Task =
                     addFlutterDeps(variant, flutterPlugin, targetPlatforms)
-                val variantOutput: BaseVariantOutput = variant.outputs.first()
+
+                // TODO(gmackall): Migrate to AGPs variant api.
+                //    https://github.com/flutter/flutter/issues/166550
+                @Suppress("DEPRECATION")
+                val variantOutput: com.android.build.gradle.api.BaseVariantOutput = variant.outputs.first()
```
Comment (gmackall) [inline packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt:346]: I could not put annotations on the imports, so I'm instead removing the imports and using the fully qualified class name (otherwise we would still get deprecation warnings for the imports)

File: dev/devicelab/bin/tasks/gradle_plugin_fat_apk_test.dart [hunk 2]
```diff
@@ -157,14 +157,7 @@ Future<void> main() async {
...
 
-        final String modifiedPath = path.join(
-          project.rootPath,
-          'build',
-          'app',
-          'intermediates',
-          'flutter',
-          '.cxx',
-        );
+        final String modifiedPath = path.join(project.rootPath, 'build', '.cxx');
```
Comment (gmackall) [inline dev/devicelab/bin/tasks/gradle_plugin_fat_apk_test.dart:160]: @bkonyi I specifically wanted to ask your opinion about this part of the PR, as my understanding is that the tool makes this directory.

This line makes us output a `.cxx` build directory artifact in `<project_root>/build/.cxx`, where before it was in `<project_root>/build/app/intermediates/flutter/.cxx`. The previous path seemed like a better place, but AGP prints warnings if we put it there (see https://github.com/flutter/flutter/pull/166277#issuecomment-2780184486).

This new location is still within the `build/` directory, but no longer within what AGP recognizes as a build directory, so it doesn't warn.

Comment (bkonyi) [reply dev/devicelab/bin/tasks/gradle_plugin_fat_apk_test.dart:160]: I'll be honest, I don't know exactly what this is or what the implications of moving it are... 😅

I can't think of any obvious reason why this _wouldn't_ be okay, so I'd have to leave final judgement to the Android subteam.

File: packages/flutter_tools/gradle/src/main/scripts/native_plugin_loader.gradle.kts [hunk 3]
```diff
@@ -59,7 +59,10 @@ class NativePluginLoader {
             // of a federated plugin).
             val needsBuild = androidPlugin[NATIVE_BUILD_KEY] as? Boolean ?: true
             if (needsBuild) {
-                nativePlugins.add(androidPlugin as Map<String, Any>) // Safe cast when adding, assuming type is now validated
+                // Suppress the unchecked cast warning as we define the structure of the JSON in
+                // the tool and we have already mostly validated the structure.
+                @Suppress("UNCHECKED_CAST")
+                nativePlugins.add(androidPlugin as Map<String, Any>)
```
Comment (reidbaker) [inline packages/flutter_tools/gradle/src/main/scripts/native_plugin_loader.gradle.kts:65]: What does the compiler think the type is here? 
We define nativePlugins as `val nativePlugins = mutableListOf<Map<String, Any>>()` Which I expect should not need a cast

**Review by reidbaker — APPROVED** [review]

File: packages/flutter_tools/gradle/src/main/kotlin/FlutterAppPluginLoaderPlugin.kt [hunk 4]
```diff
@@ -22,6 +22,7 @@ private const val FLUTTER_SDK_PATH = "flutterSdkPath"
  * This plugin applies the native plugin loader plugin (../scripts/native_plugin_loader.gradle.kts)
  * and then configures the main project to `include` each of the loaded flutter plugins.
  */
+@Suppress("unused") // This class is used by ../../../build.gradle.kts.
```
[the remark this answers is not in the document]
Comment (johnmccutchan) [reply packages/flutter_tools/gradle/src/main/kotlin/FlutterAppPluginLoaderPlugin.kt:25]: +1

File: packages/flutter_tools/gradle/src/main/kotlin/FlutterPluginUtils.kt [hunk 5]
```diff
@@ -800,18 +812,21 @@ object FlutterPluginUtils {
      * @param BaseVariantOutput The output of a specific build variant (e.g., debug, release).
      * @param variant The application variant being processed.
      */
+    @Suppress("KDocUnresolvedReference")
```
[the remark this answers is not in the document]
Comment (gmackall) [reply packages/flutter_tools/gradle/src/main/kotlin/FlutterPluginUtils.kt:815]: It looks like it to me. I can't have the import at the top, or we get a warning. And I can't have a fully qualified import due to the issue

File: packages/flutter_tools/gradle/src/main/kotlin/VersionUtils.kt [hunk 6]
```diff
@@ -42,7 +42,7 @@ object VersionUtils {
                     return version1 // v1 is a number, v2 is not, so v1 is newer.
                 v1Num == null && v2Num != null ->
                     return version2 // v1 is not a number, v2 is, so v2 is newer.
-                v1Num == null && v2Num == null -> { // Both are not numbers (pre-release identifiers)
+                else -> { // Both are not numbers (pre-release identifiers)
```
[the remark this answers is not in the document]
Comment (gmackall) [reply packages/flutter_tools/gradle/src/main/kotlin/VersionUtils.kt:45]: Hmm would you prefer I suppress this warning? I personally think the `else` along with the comment is clearer

File: packages/flutter_tools/gradle/src/main/scripts/native_plugin_loader.gradle.kts (hunk 3 above)
Comment (gmackall) [reply packages/flutter_tools/gradle/src/main/scripts/native_plugin_loader.gradle.kts:65]: The cast is for `androidPlugin`, not `nativePlugins`. 

We have verified that it contains a number of `String` keys, with `Any` values. But it could potentially have more key value pairs we don't know about, and this cast casts all of the map which is why it complains. I don't think this is worth worrying about though. We have already verified it contains the structure we think it does, and if it is getting more key value pairs it means someone has modified the tool code that generates the structure and I'm happy for that to cause a class cast exception (on the presubmits on their PR).

File: packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt [hunk 7]
```diff
@@ -472,7 +483,7 @@ class FlutterPlugin : Plugin<Project> {
                     val mergeAssets =
                         projectToAddTasksTo
                             .tasks
-                            .findByPath(":$hostAppProjectName:merge${appProjectVariant.name.capitalize()}Assets")
+                            .findByPath(":$hostAppProjectName:merge${FlutterPluginUtils.capitalize(appProjectVariant.name)}Assets")
```
[the remark this answers is not in the document]
Comment (gmackall) [reply packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt:486]: I agree this is one of the places we should replace, but I was only adding that TODO in places where suppressions of warnings was required (so that there isn't an unexplained suppression).

I can add a comment, but this PR is more about warning fixing and I'm not going to hit every place that needs a comment probably

[the remark this answers is not in the document]
Comment (gmackall) [reply packages/flutter_tools/gradle/src/main/kotlin/FlutterPlugin.kt:488]: Added

File: dev/devicelab/bin/tasks/gradle_plugin_fat_apk_test.dart (hunk 2 above)
Comment (gmackall) [reply dev/devicelab/bin/tasks/gradle_plugin_fat_apk_test.dart:160]: Sounds good! This directory doesn't actually _do_ anything. It is just an artifact of the way we are tricking AGP into downloading the NDK. So as long as it isn't violating some principle of the way the tool structures this directory, I'm happy to put it there.

Comment (bkonyi) [reply dev/devicelab/bin/tasks/gradle_plugin_fat_apk_test.dart:160]: Nope, I'm not aware of any principle being violated! If the tests are passing, I'm happy 😄

File: packages/flutter_tools/gradle/src/main/kotlin/VersionUtils.kt (hunk 6 above)
[the remark this answers is not in the document]
Comment (reidbaker) [reply packages/flutter_tools/gradle/src/main/kotlin/VersionUtils.kt:45]: if you think it is clearer then lets go with the else.

**Review by reidbaker — APPROVED** [review]
