### PR TITLE
[gen_l10n] Update the arb filename parsing logic

### LINKED ISSUE #58271: [l10n] fatal error when template-arb-file has multiple underscores
## Steps to Reproduce

When the template-arb-file is something like `template_name_en.arb`, then an exception is thrown during build and the localisation class is not (re-)generated.

**Expected results:** 
Build succeeds and localisation class is generated

**Actual results:** 
```
fatal: Arb file for a fallback, name, does not exist, even though 
the following locale(s) exist: [name_en]. 
When locales specify a script code or country code, a 
base locale (without the script code or country code) should 
exist as the fallback. Please create a {fileName}_name.arb 
file.

Exception
```

<details>
  <summary>Logs</summary>

```
 % flutter doctor -v
[✓] Flutter (Channel master, 1.19.0-2.0.pre.197, on Mac OS X 10.15.4 19E287, locale en-NL)
    • Flutter version 1.19.0-2.0.pre.197 at /Users/user/IdeaProjects/hue_blue/dev/flutter
    • Framework revision d9144bf8fc (2 hours ago), 2020-05-29 11:55:02 -0700
    • Engine revision c19459ab7d
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc3)
    • Android SDK at /Users/user/Library/Android/sdk/
    • Platform android-R, build-tools 29.0.0-rc3
    • ANDROID_HOME = /Users/user/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.43

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.15.4 19E287

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

This PR updates the arb filename parsing logic to account for two cases: One a bug, and one an improvement to the previous behavior:

### Update 1
Updates the arb filename parsing logic to account for underscores that do not separate out the root filename from the rest of the locale. 

This issue first popped up when a user wanted to name their arb files something like `foo_bar_en.arb`. The current state of the tool treats the first underscore as the start of where locale parsing should begin, so it thinks that the locale for this particular arb file is `bar_en`, which is incorrect. This updated parsing looks for the first subsection (after splitting the filename by underscores) of the filename that matches a ISO 639-1 language code, and uses the filename from that subsection onwards as the locale.

An issue that can occur with this type of parsing is when a developer names their arb file something like `app_en_en.arb`, or `en_app_en.arb`, it will confuse the tool (but then again, this PR is already an improvement from before). I also considered looking for the language code starting from the end of the filename, but there are locales such as `es_ES` that will also confuse the tool.

I'm also open to other ideas as well, this was just the best one I could come up with for now.

### Update 2
The l10n tool currently infers that if @@locale and filename are both specified, @@locale will be prioritized over the filename extension. Instead of prioritizing the value in @@locale, the tool will now expect that both values match. While this is a breaking change, it will be confusing to the developer to have non-matching @@locale and filename suffixes. 

## Related Issues

Fixes https://github.com/flutter/flutter/issues/58271

## Tests

I added the following tests:

- A test to ensure that `foo_bar_en.arb` can be properly parsed.
- A test to make sure that the @@locale and filename suffixes match

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: dev/tools/localization/gen_l10n_types.dart [hunk 1]
```diff
@@ -374,19 +374,37 @@ class AppResourceBundle {
...
 
     String localeString = resources['@@locale'] as String;
+
+    // If the locale string was not defined in @@locale, look for the first
+    // instance of an ISO 639-1 language code, matching exactly.
     if (localeString == null) {
-      final RegExp filenameRE = RegExp(r'^[^_]*_(\w+)\.arb$');
-      final RegExpMatch match = filenameRE.firstMatch(file.path);
-      localeString = match == null ? null : match[1];
+      final String fileName = file.path
```
Comment (HansMuller) [inline dev/tools/localization/gen_l10n_types.dart:381]: This will not work on Windows. Best to use the path package https://pub.dev/documentation/path/latest/path/basenameWithoutExtension.html

File: dev/tools/localization/gen_l10n_types.dart [hunk 2]
```diff
@@ -374,19 +374,37 @@ class AppResourceBundle {
...
+        // Clean out the path to only contain the filename.
+        .split('/').last
+        // Remove the file type suffix.
+        .split('.')[0];
+
+      // Separate out the filename by the underscores in the string.
+      final List<String> fileNameSeparatedByUnderscores = fileName.split('_');
+
+      for (int index = 0; index < fileNameSeparatedByUnderscores.length; index += 1) {
```
Comment (HansMuller) [inline dev/tools/localization/gen_l10n_types.dart:390]: This a nice improvement over what we have. The generalization of the idea might be a little better: match filenames with a suffix that matches a legitimate locale string preceded by an underscore. You can use https://pub.dev/documentation/intl/latest/locale/Locale/tryParse.html to check each possible suffix.

**Review by HansMuller — COMMENTED** [review]
Do we claim to fail if the filename seems to indicate a locale that doesn't match the @@locale string?

File: dev/tools/localization/gen_l10n_types.dart [hunk 3]
```diff
@@ -374,19 +377,55 @@ class AppResourceBundle {
     }
 
     String localeString = resources['@@locale'] as String;
-    if (localeString == null) {
-      final RegExp filenameRE = RegExp(r'^[^_]*_(\w+)\.arb$');
-      final RegExpMatch match = filenameRE.firstMatch(file.path);
-      localeString = match == null ? null : match[1];
+
+    // If the locale string was not defined in @@locale, look for the first
```
Comment (HansMuller) [inline dev/tools/localization/gen_l10n_types.dart:381]: We're looking for the language code in the filename unconditionally now

File: dev/tools/localization/gen_l10n_types.dart [hunk 4]
```diff
@@ -374,19 +377,55 @@ class AppResourceBundle {
...
+    // instance of an ISO 639-1 language code, matching exactly.
+    final String fileName = path.basenameWithoutExtension(file.path);
+
+    for (int index = 0; index < fileName.length; index += 1) {
+      // If an underscore was found, check if locale string follows.
+      if (fileName[index] == '_' && fileName[index + 1] != null) {
+        // If Locale.tryParse fails, it returns the String 'null'.
```
Comment (HansMuller) [inline dev/tools/localization/gen_l10n_types.dart:388]: It returns null not "null", right?

File: dev/tools/test/localization/gen_l10n_test.dart [hunk 5]
```diff
@@ -308,6 +308,35 @@ void main() {
     expect(generator.header, '/// Sample header in a text file');
   });
 
+  test('sets templateArbFileName with more than one underscore correctly', () {
+    final Directory l10nDirectory = fs.currentDirectory.childDirectory('lib').childDirectory('l10n')
+      ..createSync(recursive: true);
+    l10nDirectory.childFile('app_localizations_en.arb')
```
Comment (HansMuller) [inline dev/tools/test/localization/gen_l10n_test.dart:314]: It would be usefulto verify that ap_localizations_en_CA is recognized as en_CA but app_localizations_en_CA_foo is not.

**Review by HansMuller — APPROVED** [review]
Nice fix! LGTM

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

**Comment by flutter-github-sync** [comment]
Google testing passed!

File: dev/tools/localization/gen_l10n_types.dart (hunk 4 above)
Comment (shihaohong) [reply dev/tools/localization/gen_l10n_types.dart:388]: You're right. In one my previous changes it was returning null because I used `toString()` incorrectly. I'll update the comment

File: dev/tools/test/localization/gen_l10n_test.dart (hunk 5 above)
Comment (shihaohong) [reply dev/tools/test/localization/gen_l10n_test.dart:314]: I just tried `en_CA_foo` and it somehow parses the locale as `foo`. It seems that `Locale.tryParse` checks for the format of the locale identifier, so it would still be helpful to validate that the language is a valid one.

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

**Comment by flutter-github-sync** [comment]
Google testing passed!
