### PR TITLE
Patch to fix builds with custom targets on iOS simulator.

### LINKED ISSUE #16787: Attempt to run entrypoint other than lib/main.dart fails on iOS simulator
with iOS simulator
in $FH/flutter/examples/flutter_gallery
`mv lib/main.dart to lib/main1.dart`
`$FH/flutter/bin/flutter run -v -t lib/main1.dart`

fails with
```
[ +983 ms] Launching lib/main1.dart on iPhone X in debug mode...
...
[  +18 ms] Building Runner.app for xxx.
[   +9 ms] $FH/flutter/bin/cache/dart-sdk/bin/dart $FH/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root $FH/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --strong --target=flutter --no-link-platform --incremental --packages $FH/flutter/examples/flutter_gallery/.packages --output-dill build/app.dill --depfile build/snapshot_blob.bin.d $FH/flutter/examples/flutter_gallery/lib/main.dart
[   +2 ms] script /dev/null /usr/bin/log stream --style syslog --predicate processImagePath CONTAINS "EA2E716D-F4F4-45BE-97A3-4F638958C55D"
[  +41 ms] [DEVICE LOG] Filtering the log data using "processImagePath CONTAINS "xxx""
[  +10 ms] [DEVICE LOG] Timestamp                       (process)[PID]    
[ +226 ms] compiler message: lib/main.dart: Error: No such file or directory
[  +31 ms] Compiler failed on lib/main.dart
[        ] Error launching application on iPhone X.
[  +22 ms] "flutter run" took 4,649ms.
```
Note `lib/main.dart` in parameters to the compiler.

Running the same app(with the same command) on Android Emulator works fine.

### PR DESCRIPTION
**Pull request by slightfoot**
Fixes #16787

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/mac.dart [hunk 1]
```diff
@@ -189,7 +188,7 @@ class Xcode {
 Future<XcodeBuildResult> buildXcodeProject({
   BuildableIOSApp app,
   BuildInfo buildInfo,
-  String target: bundle.defaultMainPath,
+  String target,
```
Comment (xster) [inline packages/flutter_tools/lib/src/ios/mac.dart]: This is good. Though I think reading the flow downstream, there might be some issues since xcodeproject.dart's updateGeneratedXcodeProperties always writes a line FLUTTER_TARGET which will be 'null'. In xcode_backend.sh, the variable $FLUTTER_TARGET will exist and turn off the default value of 'lib/main.dart' I think. 

Maybe we can make these names more explicit to avoid issues for future maintainers. 

Let's rename `target` to `targetOverride` here in the `buildXcodeProject`'s signature and in `updateGeneratedXcodeProperties`. Let `updateGeneratedXcodeProperties` not write anything into the generated file if `targetOverride` is null. 

Let's add a dartdoc for this method to say that targetOverride is optional and if it's null, the value default file taken by xcode_backend.sh is lib/main.dart.

**Review by xster — APPROVED** [review]
This is great! Thanks for your contribution. Just a small cleanup suggestion for the naming but the general approach looks good.

File: packages/flutter_tools/lib/src/ios/mac.dart (hunk 1 above)
Comment (slightfoot) [reply packages/flutter_tools/lib/src/ios/mac.dart]: @xster My reason for removing this was that it was cause of the bug in the first place, the default parameter masked the need for it to be specified. I've applied the suggested changes.

But this leads to another place in the flutter tool where it is used as a default parameter. That might also want to be cleared up. https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/bundle.dart#L32

Even though we have other sane defaults there. It is a case that the upstream always supplies the default value down for the mainPath parameter and nowhere in the code is it not currently specified (once this PR get's merged).

**Comment by slightfoot** [comment]
@xster @Hixie what do we do next? does someone post a LGTM?

**Comment by xster** [comment]
Thanks for the update. LGTM. Merging

**Comment by tvolkert** [comment]
This also fixed https://github.com/flutter/flutter/issues/17120 - thanks!
