### PR TITLE
Fix `ReorderableList` items jumping when drag direction reverses mid-animation

### LINKED ISSUE #173243: `ReorderableList`: Items jump when drag direction reverses mid-animation
When dragging in `ReorderableListView`, the items that shift to make room exhibit jumping behavior if drag direction is reversed before their animations complete.

<p align="center">
  demo2
</p>

**Steps to Reproduce:**
1. Create a `ReorderableListView` with items
2. Drag an item over others (causing them to animate out of the way)
3. Before those animations complete, drag back in the opposite direction
4. The shifting items jump instead of smoothly reversing

**Expected:**
Items making room should smoothly transition from their current animated position when drag direction changes.

**Actual:**
Items snap back to their original positions before animating to new targets, causing visual jumps.

**Environment:**
- Flutter version: stable channel
- Platform: all platforms

### PR DESCRIPTION
**Pull request by lukemmtt**
When rapidly dragging items in a ReorderableList before animations complete, items would jump to their expected positions rather than smoothly transitioning.

## Problem

<p align="center">
  demo2
</p>

The issue occurs when a reorder animation is interrupted by starting a new drag operation. The interrupted animation would reset to the starting position of the original animation rather than capturing the current animated position, causing a visual jump.

## Solution

This PR fixes the issue by:
1. Storing the previous target offset before updating to a new target
2. When an animation is interrupted, calculating the actual current position based on the animation's progress
3. Using this calculated position as the new starting point for the next animation

<p align="center">
  demo2
</p>

This PR is part of a series of `ReorderableList` enhancements I've developed for [TimeFinder](https://timefinder.app):
- #172740
- #172380
- #172739
- #172738

Fixes #173243

## Code Changes

```dart
// Before
_startOffset = offset;

// After  
final double currentAnimValue = Curves.easeInOut.transform(_offsetAnimation\!.value);
final Offset currentPosition = Offset.lerp(_startOffset, previousTarget, currentAnimValue)\!;
_startOffset = currentPosition;
```

This ensures smooth transitions without visual jumping, making rapid reordering gestures feel more responsive and natural.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [migration guide] as needed.
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

[Contributor Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[migration guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#create-a-migration-guide

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hey @lukemmtt thanks for sending another PR! Really appreciate the changes you are putting into this widget. 🙌 
It looks like there are some failing tests here currently, can you take a look?

**Comment by lukemmtt** [comment]
@Piinks Glad to help! And for sure, checking these now actually. Thanks for the attention to these PRs!

**Comment by lukemmtt** [comment]
Lints fixed 👍🏻

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 1]
```diff
@@ -798,6 +798,58 @@ void main() {
...
+    await tester.pump(const Duration(milliseconds: 50));
+
+    // Check for animation jumping immediately after crossing the threshold
+    final double item1Y = tester.getCenter(find.text('item 1')).dy;
+
+    // At this moment, Item1 should have just started animating from ~Y=150
+    // If it jumps due to the bug, it will be at Y=108
+    // With correct behavior, it should still be close to its starting position
+    if (item1Y < 120 && item1Y > 90) {
+      fail('Animation jumping detected! Item1 jumped to Y=$item1Y when crossing threshold');
```
Comment (Piinks) [inline packages/flutter/test/widgets/reorderable_list_test.dart]: It looks like this is currently failing.

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 2]
```diff
@@ -798,6 +798,58 @@ void main() {
...
+      await tester.pump(const Duration(milliseconds: 50));
+    }
+
+    // Release and watch the animation
+    await drag.up();
+    
+    // Pump multiple times to see the animation
+    for (int i = 0; i < 20; i++) {
+      await tester.pump(const Duration(milliseconds: 50));
+    }
```
[the remark this answers is not in the document]
Comment (Piinks) [reply packages/flutter/test/widgets/reorderable_list_test.dart]: Yes, I am not sure why we pump out the rest of the animation like this, unless we are testing for something?

**Comment by Piinks** [comment]
Hey @lukemmtt do you have plans to return to this change?

**Comment by lukemmtt** [comment]
@Piinks Thanks for the follow-up, and yes—happy to revisit this one!

I've just done some edits, seems to be passing now locally, but I'll keep an eye on the CI checks in case my environment isn't set up perfectly.

File: packages/flutter/test/widgets/reorderable_list_test.dart (hunk 1 above)
Comment (lukemmtt) [reply packages/flutter/test/widgets/reorderable_list_test.dart]: Should be resolved now, I think

File: packages/flutter/test/widgets/reorderable_list_test.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (lukemmtt) [reply packages/flutter/test/widgets/reorderable_list_test.dart]: Thanks for the feedback—nope, this was just a remnant from when I was evaluating the test visually as an integration test. Removed now 👍🏻

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 3]
```diff
@@ -798,6 +798,58 @@ void main() {
...
+    
+    // Check for animation jumping immediately after crossing the threshold
+    final double item1Y = tester.getCenter(find.text('item 1')).dy;
+    
+    // At this moment, Item1 should have just started animating from ~Y=150
+    // If it jumps due to the bug, it will be at Y=108
+    // With correct behavior, it should still be close to its starting position
+    if (item1Y < 120 && item1Y > 90) {
+      fail('Animation jumping detected! Item1 jumped to Y=$item1Y when crossing threshold');
+    }
```
[the remark this answers is not in the document]
Comment (lukemmtt) [reply packages/flutter/test/widgets/reorderable_list_test.dart]: Fixed; now using relative position comparison with `closeTo` matcher as suggested. Test properly detects the bug and is more robust.

**Comment by Piinks** [comment]
It looks like the failure was resolved, thank you!
Can you rebase with the tip of tree to resolve the conflicts? I think we are ready to get this in! 🎊

**Comment by lukemmtt** [comment]
@Piinks Should be good now, let me know, thank you!

**Review by Piinks — APPROVED** [review]
LGTM! Thank you!

File: packages/flutter/test/widgets/reorderable_list_test.dart [hunk 4]
```diff
@@ -870,6 +870,51 @@ void main() {
...
+    await tester.pumpWidget(TestList(items: items));
+    await tester.pumpAndSettle();
+
+    expect(tester.getTopLeft(find.text('item 0')), Offset.zero);
+    expect(tester.getTopLeft(find.text('item 1')), const Offset(0, 100));
+
+    final TestGesture drag = await tester.startGesture(tester.getCenter(find.text('item 0')));
+    await tester.pump(kPressTimeout);
+
+    // Drag item 0 down past the swap threshold at 50px
```
Comment (justinmc) [inline packages/flutter/test/widgets/reorderable_list_test.dart]: Nit: Periods at the end of these comments.

**Review by justinmc — APPROVED** [review]
LGTM 👍 

@Piinks Can you try adding this to the Google tests via the FROB UI? I don't see any option to add a new PR. Maybe the UI changed or maybe I'm not signed in somewhere...

File: packages/flutter/test/widgets/reorderable_list_test.dart (hunk 4 above)
Comment (lukemmtt) [reply packages/flutter/test/widgets/reorderable_list_test.dart]: Fixed [here](https://github.com/flutter/flutter/pull/173241/commits/49c8c78194b8c30ef0af93ba703792b1adee9c0a), thanks @justinmc!
