### PR TITLE
A bunch of error detection for iOS onboarding flow

### LINKED ISSUE #10886: flutter run fails when device is screen locked: bad error msg
## Steps to Reproduce

- On MacOS with iPod plugged, no simulators.
- `$ flutter create hello`
- `$ cd hello`
- `$ flutter run`
- Setup code signing in Xcode. Meanwhile, device goes to sleep.
- `$ flutter run`

## Logs

```shell
$ flutter run
Launching lib/main.dart on Mikkel's iPod touch in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: AQ7UHDBEXJ
Running Xcode build...                                9.3s
2017-06-21 14:02:46.222 ios-deploy[48109:4506952] [ !! ] Unable to mount developer disk image. (e80000e2)
Could not install build/ios/Release-iphoneos/Runner.app on c1bddaa8c422f9125dcc14b53af91e62aa7036d1.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Mikkel's iPod touch.
$ 
```

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/mravn/github/flutter
    • Framework revision ceb814aa64 (7 hours ago), 2017-06-20 22:14:59 -0700
    • Engine revision fffe502d43
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/mravn/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Mikkel's iPod touch • c1bddaa8c422f9125dcc14b53af91e62aa7036d1 • ios • iOS 10.3.1

### LINKED ISSUE #12892: Better error message when phone is not registered with Apple Developer Account
Error message

```
2017-11-04 18:51:54.815 ios-deploy[75050:1892997] [ !! ] Error 0xe8008015: A valid provisioning profile for this executable was not found. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Could not install build/ios/iphoneos/Runner.app on 7233072bb988fb4c64429a4d9a092295f9423892.
```

### PR DESCRIPTION
**Pull request by xster**
Fixes #10886
Fixes #12892

Partly reverts and moves #12911 because it was in the wrong place.

- Check for locked phone
- Check for incompatible Xcode
- Check for unregistered phone
- Check for conflicting certificates

Unfortunately tests needs a much bigger refactor in the installation flow.

### CODE REVIEW

File: packages/flutter_tools/lib/src/ios/devices.dart [hunk 1]
```diff
@@ -331,6 +340,33 @@ class IOSDevice extends Device {
...
   Future<Null> takeScreenshot(File outputFile) => iMobileDevice.takeScreenshot(outputFile);
+
+  // Maps stdout line stream. Must return original line.
+  String monitorInstallationFailure(String stdout) {
+    // Installation issues.
+    if (stdout.contains('Error 0xe8008015') || stdout.contains('Error 0xe8000067')) {
+      printError(noProvisioningProfileInstruction, emphasis: true);
+
+    // Launch issues.
+    } else if (stdout.contains('e80000e2')) {
```
Comment (gspencergoog) [inline packages/flutter_tools/lib/src/ios/devices.dart]: Maybe add the '0x'?

**Review by gspencergoog — APPROVED** [review]
Nice improvement in documentation.  It did seem a little minimal before.

**Comment by gspencergoog** [comment]
lgtm

File: packages/flutter_tools/lib/src/ios/devices.dart (hunk 1 above)
Comment (xster) [reply packages/flutter_tools/lib/src/ios/devices.dart]: ios_deploy is pretty inconsistent. In this case, it doesn't actually print the 0x
