### PR TITLE
Fix update_engine_version_test in presence of FLUTTER_PREBUILT_ENGINE_VERSION env vars.

### LINKED ISSUE #162260: dev/tools/update_engine_version_test fails when running from the shell with FLUTTER_PREBUILT_ENGINE_VERSION set
This happens on flutter hh bot https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8724577479429174593/+/u/Run_framework_tests_misc_tests/stdout

The test is expected to ignore FLUTTER_PREBUILD_ENGINE_VERSION set up in parent environment.

```
╰─➤  FLUTTER_PREBUILT_ENGINE_VERSION=cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1 ../../bin/dart test/update_engine_version_test.dart
[Unstable] Override: Setting engine SHA to cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1
00:00 +0: if FLUTTER_PREBUILT_ENGINE_VERSION is set writes it to engine.version with no git interaction

Running "/tmp/update_engine_version_test.DBUOMV/flutter/bin/internal/update_engine_version.sh" in /tmp/update_engine_version_test.DBUOMV/flutter.
[Unstable] Override: Setting engine SHA to 123abc
00:00 +1: writes nothing, even if files are set, if we are on "stable"

Running "git init --initial-branch master" in /tmp/update_engine_version_test.YAAZUV/flutter.
Initialized empty Git repository in /tmp/update_engine_version_test.YAAZUV/flutter/.git/
Running "git add ." in /tmp/update_engine_version_test.YAAZUV/flutter.
Running "git commit -m Initial commit" in /tmp/update_engine_version_test.YAAZUV/flutter.
[master (root-commit) cb6bc88] Initial commit
 3 files changed, 66 insertions(+)
 create mode 100644 DEPS
 create mode 100755 bin/internal/update_engine_version.sh
 create mode 100644 engine/src/.gn
Running "git checkout -b stable" in /tmp/update_engine_version_test.YAAZUV/flutter.
Switched to a new branch 'stable'
Running "git remote add upstream /tmp/update_engine_version_test.YAAZUV/flutter" in /tmp/update_engine_version_test.YAAZUV/flutter.
Running "git fetch upstream" in /tmp/update_engine_version_test.YAAZUV/flutter.
From /tmp/update_engine_version_test.YAAZUV/flutter
 * [new branch]      master     -> upstream/master
 * [new branch]      stable     -> upstream/stable
Running "/tmp/update_engine_version_test.YAAZUV/flutter/bin/internal/update_engine_version.sh" in /tmp/update_engine_version_test.YAAZUV/flutter.
[Unstable] Override: Setting engine SHA to cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1
00:00 +1 -1: writes nothing, even if files are set, if we are on "stable" [E]

  Expected: not a file system entity that exists
    Actual: LocalFile:<LocalFile: '/tmp/update_engine_version_test.YAAZUV/flutter/bin/internal/engine.version'>
  

  package:matcher/src/expect/expect.dart 149:31     fail
  package:matcher/src/expect/expect.dart 144:3      _expect
  package:matcher/src/expect/expect.dart 56:3       expect
  test/update_engine_version_test.dart 105:5        main.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 229:9  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 227:7  Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9   Invoker._waitForOutstandingCallbacks.<fn>
  

00:00 +1 -1: writes nothing, even if files are set, if we are on "beta"

Running "git init --initial-branch master" in /tmp/update_engine_version_test.WHPARY/flutter.
Initialized empty Git repository in /tmp/update_engine_version_test.WHPARY/flutter/.git/
Running "git add ." in /tmp/update_engine_version_test.WHPARY/flutter.
Running "git commit -m Initial commit" in /tmp/update_engine_version_test.WHPARY/flutter.
[master (root-commit) 453d90e] Initial commit
 3 files changed, 66 insertions(+)
 create mode 100644 DEPS
 create mode 100755 bin/internal/update_engine_version.sh
 create mode 100644 engine/src/.gn
Running "git checkout -b beta" in /tmp/update_engine_version_test.WHPARY/flutter.
Switched to a new branch 'beta'
Running "git remote add upstream /tmp/update_engine_version_test.WHPARY/flutter" in /tmp/update_engine_version_test.WHPARY/flutter.
Running "git fetch upstream" in /tmp/update_engine_version_test.WHPARY/flutter.
From /tmp/update_engine_version_test.WHPARY/flutter
 * [new branch]      beta       -> upstream/beta
 * [new branch]      master     -> upstream/master
Running "/tmp/update_engine_version_test.WHPARY/flutter/bin/internal/update_engine_version.sh" in /tmp/update_engine_version_test.WHPARY/flutter.
[Unstable] Override: Setting engine SHA to cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1
00:01 +1 -2: writes nothing, even if files are set, if we are on "beta" [E]

  Expected: not a file system entity that exists
    Actual: LocalFile:<LocalFile: '/tmp/update_engine_version_test.WHPARY/flutter/bin/internal/engine.version'>
  

  package:matcher/src/expect/expect.dart 149:31     fail
  package:matcher/src/expect/expect.dart 144:3      _expect
  package:matcher/src/expect/expect.dart 56:3       expect
  test/update_engine_version_test.dart 114:5        main.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 229:9  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 227:7  Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9   Invoker._waitForOutstandingCallbacks.<fn>
  

00:01 +1 -2: if DEPS and engine/src/.gn are present, engine.version is derived from merge-base HEAD upstream/master on non-LUCI when upstream is set

Running "git init --initial-branch master" in /tmp/update_engine_version_test.ZGPOBY/flutter.
Initialized empty Git repository in /tmp/update_engine_version_test.ZGPOBY/flutter/.git/
Running "git add ." in /tmp/update_engine_version_test.ZGPOBY/flutter.
Running "git commit -m Initial commit" in /tmp/update_engine_version_test.ZGPOBY/flutter.
[master (root-commit) 453d90e] Initial commit
 3 files changed, 66 insertions(+)
 create mode 100644 DEPS
 create mode 100755 bin/internal/update_engine_version.sh
 create mode 100644 engine/src/.gn
Running "git remote add upstream /tmp/update_engine_version_test.ZGPOBY/flutter" in /tmp/update_engine_version_test.ZGPOBY/flutter.
Running "git fetch upstream" in /tmp/update_engine_version_test.ZGPOBY/flutter.
From /tmp/update_engine_version_test.ZGPOBY/flutter
 * [new branch]      master     -> upstream/master
Running "git merge-base HEAD upstream/master" in /tmp/update_engine_version_test.ZGPOBY/flutter.
453d90e6c766d6995353e131b3dc2da9a7fa107d
Running "/tmp/update_engine_version_test.ZGPOBY/flutter/bin/internal/update_engine_version.sh" in /tmp/update_engine_version_test.ZGPOBY/flutter.
[Unstable] Override: Setting engine SHA to cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1
00:02 +1 -3: if DEPS and engine/src/.gn are present, engine.version is derived from merge-base HEAD upstream/master on non-LUCI when upstream is set [E]

  Expected: '453d90e6c766d6995353e131b3dc2da9a7fa107d' ignoring whitespace
    Actual: 'cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1\n'
              ''
     Which: is 'cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1' with whitespace compressed
  

  package:matcher/src/expect/expect.dart 149:31     fail
  package:matcher/src/expect/expect.dart 144:3      _expect
  package:matcher/src/expect/expect.dart 56:3       expect
  test/update_engine_version_test.dart 134:7        main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 229:9  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 227:7  Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9   Invoker._waitForOutstandingCallbacks.<fn>
  

00:02 +1 -3: if DEPS and engine/src/.gn are present, engine.version is derived from merge-base HEAD origin/master on non-LUCI when upstream is not set

Running "git init --initial-branch master" in /tmp/update_engine_version_test.GEMBWM/flutter.
Initialized empty Git repository in /tmp/update_engine_version_test.GEMBWM/flutter/.git/
Running "git add ." in /tmp/update_engine_version_test.GEMBWM/flutter.
Running "git commit -m Initial commit" in /tmp/update_engine_version_test.GEMBWM/flutter.
[master (root-commit) 29c737a] Initial commit
 3 files changed, 66 insertions(+)
 create mode 100644 DEPS
 create mode 100755 bin/internal/update_engine_version.sh
 create mode 100644 engine/src/.gn
Running "git remote add origin /tmp/update_engine_version_test.GEMBWM/flutter" in /tmp/update_engine_version_test.GEMBWM/flutter.
Running "git fetch origin" in /tmp/update_engine_version_test.GEMBWM/flutter.
From /tmp/update_engine_version_test.GEMBWM/flutter
 * [new branch]      master     -> origin/master
Running "git merge-base HEAD origin/master" in /tmp/update_engine_version_test.GEMBWM/flutter.
29c737add10fa507ea95792bfda402f44e3470f8
Running "/tmp/update_engine_version_test.GEMBWM/flutter/bin/internal/update_engine_version.sh" in /tmp/update_engine_version_test.GEMBWM/flutter.
[Unstable] Override: Setting engine SHA to cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1
00:02 +1 -4: if DEPS and engine/src/.gn are present, engine.version is derived from merge-base HEAD origin/master on non-LUCI when upstream is not set [E]

  Expected: '29c737add10fa507ea95792bfda402f44e3470f8' ignoring whitespace
    Actual: 'cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1\n'
              ''
     Which: is 'cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1' with whitespace compressed
  

  package:matcher/src/expect/expect.dart 149:31     fail
  package:matcher/src/expect/expect.dart 144:3      _expect
  package:matcher/src/expect/expect.dart 56:3       expect
  test/update_engine_version_test.dart 152:7        main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 229:9  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 227:7  Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9   Invoker._waitForOutstandingCallbacks.<fn>
  

00:02 +1 -4: if DEPS and engine/src/.gn are present, engine.version is derived from rev-parse HEAD when running on LUCI

Running "git init --initial-branch master" in /tmp/update_engine_version_test.GGGMGU/flutter.
Initialized empty Git repository in /tmp/update_engine_version_test.GGGMGU/flutter/.git/
Running "git add ." in /tmp/update_engine_version_test.GGGMGU/flutter.
Running "git commit -m Initial commit" in /tmp/update_engine_version_test.GGGMGU/flutter.
[master (root-commit) 8159958] Initial commit
 3 files changed, 66 insertions(+)
 create mode 100644 DEPS
 create mode 100755 bin/internal/update_engine_version.sh
 create mode 100644 engine/src/.gn
Running "/tmp/update_engine_version_test.GGGMGU/flutter/bin/internal/update_engine_version.sh" in /tmp/update_engine_version_test.GGGMGU/flutter.
[Unstable] Override: Setting engine SHA to cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1
Running "git rev-parse HEAD" in /tmp/update_engine_version_test.GGGMGU/flutter.
81599581757a4fa5704573a56b7026b80bab8ddd
00:03 +1 -5: if DEPS and engine/src/.gn are present, engine.version is derived from rev-parse HEAD when running on LUCI [E]

  Expected: '81599581757a4fa5704573a56b7026b80bab8ddd' ignoring whitespace
    Actual: 'cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1\n'
              ''
     Which: is 'cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1' with whitespace compressed
  

  package:matcher/src/expect/expect.dart 149:31     fail
  package:matcher/src/expect/expect.dart 144:3      _expect
  package:matcher/src/expect/expect.dart 56:3       expect
  test/update_engine_version_test.dart 168:7        main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 229:9  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 227:7  Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9   Invoker._waitForOutstandingCallbacks.<fn>
  

00:03 +1 -5: if DEPS or engine/src/.gn are omitted [DEPS] engine.version is blank

Running "/tmp/update_engine_version_test.UATZWQ/flutter/bin/internal/update_engine_version.sh" in /tmp/update_engine_version_test.UATZWQ/flutter.
[Unstable] Override: Setting engine SHA to cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1
00:03 +1 -6: if DEPS or engine/src/.gn are omitted [DEPS] engine.version is blank [E]

  Expected: '' ignoring whitespace
    Actual: 'cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1\n'
              ''
     Which: is 'cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1' with whitespace compressed
  

  package:matcher/src/expect/expect.dart 149:31     fail
  package:matcher/src/expect/expect.dart 144:3      _expect
  package:matcher/src/expect/expect.dart 56:3       expect
  test/update_engine_version_test.dart 188:7        main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 229:9  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 227:7  Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9   Invoker._waitForOutstandingCallbacks.<fn>
  

00:03 +1 -6: if DEPS or engine/src/.gn are omitted [engine/src/.gn] engine.version is blank

Running "/tmp/update_engine_version_test.AJEPHY/flutter/bin/internal/update_engine_version.sh" in /tmp/update_engine_version_test.AJEPHY/flutter.
[Unstable] Override: Setting engine SHA to cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1
00:03 +1 -7: if DEPS or engine/src/.gn are omitted [engine/src/.gn] engine.version is blank [E]

  Expected: '' ignoring whitespace
    Actual: 'cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1\n'
              ''
     Which: is 'cd20d9b9ac87787b3f0bf61a94a93c5e05eb69e1' with whitespace compressed
  

  package:matcher/src/expect/expect.dart 149:31     fail
  package:matcher/src/expect/expect.dart 144:3      _expect
  package:matcher/src/expect/expect.dart 56:3       expect
  test/update_engine_version_test.dart 197:7        main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 229:9  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 227:7  Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9   Invoker._waitForOutstandingCallbacks.<fn>
  

00:03 +1 -7: Some tests failed.



Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.


Unhandled exception:
Dummy exception to set exit code.
```

cc @matanlurey

### PR DESCRIPTION
**Pull request by aam**
Fixes https://github.com/flutter/flutter/issues/162260

### CODE REVIEW

File: dev/tools/test/update_engine_version_test.dart [hunk 1]
```diff
@@ -19,47 +20,57 @@ void main() {
   late Directory tmpDir;
   late _FlutterRootUnderTest testRoot;
   late Map<String, String> environment;
-  late ProcessRunner processRunner;
+  // late ProcessRunner processRunner;
```
Comment (matanlurey) [inline dev/tools/test/update_engine_version_test.dart:23]: Remove?

File: dev/tools/test/update_engine_version_test.dart [hunk 2]
```diff
@@ -19,47 +20,57 @@ void main() {
...
     tmpDir = localFs.systemTempDirectory.createTempSync('update_engine_version_test.');
     testRoot = _FlutterRootUnderTest.fromPath(tmpDir.childDirectory('flutter').path);
 
     environment = <String, String>{};
-    processRunner = ProcessRunner(
-      defaultWorkingDirectory: testRoot.root,
-      environment: environment,
-      printOutputDefault: true,
-    );
+    environment.addAll(io.Platform.environment);
```
Comment (matanlurey) [inline dev/tools/test/update_engine_version_test.dart:55]: I think you _didn't_ want this?

Comment (aam) [reply dev/tools/test/update_engine_version_test.dart:55]: > I thought you _didn't_ want this?

I construct environment manually: I use parent's one, but then remove `FLUTTER_PREBUILT_ENGINE_VERSION` explicitly below.
Running with completely blank environment fails to run powershell scripts for some reason.

File: dev/tools/test/update_engine_version_test.dart (hunk 1 above)
Comment (aam) [reply dev/tools/test/update_engine_version_test.dart]: > Remove?

Thanks, done.

**Review by matanlurey — APPROVED** [review]
