### PR TITLE
Fix PinnedHeaderSliver semantics focus capture

### LINKED ISSUE #179022: [Accessibility] PinnedHeaderSliver captures semantic focus before list is fully scrolled
### Steps to reproduce

1. Enable accessibility services (TalkBack or VoiceOver) on the device.
2. Open a screen containing a CustomScrollView with a PinnedHeaderSliver and a list of items (e.g., SliverList).
3. Scroll down the list so that the top items are off-screen.
4. Navigate backwards (swipe left / previous item gesture) to scroll up toward the top of the list.

### Expected results

The list should be **fully scrolled to the top** (displaying the very first item) before the semantic focus moves to the widget preceding the list or the pinned header. The user should be able to navigate through all remaining list items before leaving the list context.

### Actual results

The PinnedHeaderSliver takes the semantic focus immediately when navigating up, effectively "skipping" the remaining items at the top of the list or preventing the list from scrolling all the way back to the start.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: AccessibilityTestPage()));
}

class AccessibilityTestPage extends StatelessWidget {
  const AccessibilityTestPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          const SliverAppBar(
            pinned: true,
            expandedHeight: 100.0,
            title: Text('Pinned Semantic Focus'),
            backgroundColor: Colors.blue,
          ),
          // The Pinned Header
          const PinnedHeaderSliver(
            child: ColoredBox(
              color: Colors.amber,
              child: ListTile(title: Text('Pinned Semantic Focus')),
            ),
          ),
          // The List
          SliverList(
            delegate: SliverChildBuilderDelegate((BuildContext context, int index) {
              return ListTile(
                title: Text('Item $index'),
                subtitle: const Text('Scroll down then navigate back up'),
              );
            }, childCount: 50),
          ),
        ],
      ),
    );
  }
}
```

https://github.com/user-attachments/assets/6c2b1fbe-066c-4371-9291-d3eda82dd4ea

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.39.0-1.0.pre-261, on macOS 15.7.2 24G325 darwin-arm64, locale fr-FR) [1 826ms]
    • Flutter version 3.39.0-1.0.pre-261 on channel master at /Users/emmanuel_lefebvre/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12b5c1cfdf (3 days ago), 2025-11-22 03:12:08 +0200
    • Engine revision 216e5124a0
    • Dart version 3.11.0 (build 3.11.0-162.0.dev)
    • DevTools version 2.52.0
    • Pub download mirror https://artifact.socrate.vsct.fr/artifactory/api/pub/all-pub
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations, enable-native-assets, omit-legacy-version-file,
      enable-lldb-debugging, enable-uiscene-migration

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.1) [1 816ms]
    • Android SDK at /Users/emmanuel_lefebvre/Library/Android/sdk
    • Emulator version 36.2.12.0 (build_id 14214601) (CL:N/A)
    • Platform android-36, build-tools 35.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.8+-14196175-b1038.72)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.1.1) [1 598ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17B100
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (4 available) [6,8s]
    • Pixel 7 Pro (mobile)        • 35061FDH30024V • android-arm64  • Android 16 (API 36)
    • sdk gphone64 arm64 (mobile) • emulator-5554  • android-arm64  • Android 15 (API 35) (emulator)
    • macOS (desktop)             • macos          • darwin-arm64   • macOS 15.7.2 24G325 darwin-arm64
    • Chrome (web)                • chrome         • web-javascript • Google Chrome 142.0.7444.176
    ! Error: Browsing on the local area network for iPhone XS. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [547ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by manu-sncf**
Fix #179022

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by justinmc** [comment]
@manu-sncf Would you be able to add a test for this?

File: packages/flutter/lib/src/widgets/pinned_header_sliver.dart [hunk 1]
```diff
@@ -106,4 +106,10 @@ class _RenderPinnedHeaderSliver extends RenderSliverSingleBoxAdapter {
       hasVisualOverflow: true, // Conservatively say we do have overflow to avoid complexity.
     );
   }
+
+  @override
```
[the remark this answers is not in the document]
Comment (manu-sncf) [reply packages/flutter/lib/src/widgets/pinned_header_sliver.dart:127]: I'm not sure the comment is necessary for an overridden method.

[the remark this answers is not in the document]
Comment (Renzo-Olivares) [reply packages/flutter/lib/src/widgets/pinned_header_sliver.dart:127]: I think its fine without this additional comment.

**Comment by zemanux** [comment]
> Thank you for the contribution @manu-sncf! This change looks reasonable to me and is the same approach we used to solve a similar issue in `SliverAppBar` #60331. However trying this out change out locally on my pixel 10 pro fold and I am still experiencing this issue. Is there a specific device you tested on?
> 
>  screen-20251203-165938-1764809950067.mp4

Thank you for your time on this review

I tested on a Pixel 9 Pro emulator and a Pixel 7 Pro real device. I recorded these two videos with the Pixel 7 Pro :

**Without fix :** 

https://github.com/user-attachments/assets/a7148d6c-890b-47b6-aba7-b6dfe78eabb7

**With fix :**

https://github.com/user-attachments/assets/ac5ec216-36d8-4c76-8b88-4844c090e0dd

**Comment by manu-sncf** [comment]
FYI: Migrating authorship from @manu-sncf to @zemanux in this push ([b1c2289](https://github.com/flutter/flutter/commit/b1c2289f495bad7503a93b57e30fa5f2aae42e1b))

**Comment by zemanux** [comment]
`git bisect` points to d18ab0e8542ddd17e975ce521c01442c0b5cf82b Fix for PR #174374 - TalkBack does not announce list information

**Comment by zemanux** [comment]
@Renzo-Olivares  I confirm the fix works following PR #179480.

I added a new commit (b45a655) to handle an edge case involving a `PinnedHeaderSliver` positioned in the middle of a list (e.g., a nested list within a `SliverMainAxisGroup` for a sticky header effect).

**Without this fix, `config.addTagForChildren(RenderViewport.excludeFromScrolling)` add two issues:**
* **Focus jumping:** The semantics focus skips elements after the `PinnedHeaderSliver` (resolved via overlap control).
* **Inconsistent traversal:** The inner focus order of `PinnedHeaderSliver` is inconsistent (resolved by using `Semantics(container: true, explicitChildNodes: true)`).

https://github.com/user-attachments/assets/0e8903d9-ad00-4444-9989-7f664e9a2712

Both are now resolved :

https://github.com/user-attachments/assets/627fcf43-2082-4ae0-a4d3-7c10a7c8bb91


<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: MyApp()));

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          const SliverAppBar(
            pinned: true,
            expandedHeight: 100.0,
            title: Text('Pinned Semantic Focus'),
            backgroundColor: Colors.blue,
          ),
          SliverList(
            delegate: SliverChildBuilderDelegate((BuildContext context, int index) {
              return ListTile(title: Text('Item $index'), subtitle: const Text('Scroll down then navigate back up'));
            }, childCount: 5),
          ),
          PinnedHeaderSliver(
            child: Semantics(
              child: ColoredBox(
                color: Colors.amber,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      spacing: 8,
                      children: [
                        Padding(padding: const EdgeInsets.only(left: 8.0), child: Text('Pinned Header')),
                        IconButton(onPressed: () {}, icon: Icon(Icons.info)),
                      ],
                    ),
                    Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Semantics(container: true, child: Text('Element')),
                    ),
                  ],
                ),
              ),
            ),
          ),
          // The List
          SliverList(
            delegate: SliverChildBuilderDelegate((BuildContext context, int index) {
              return ListTile(title: Text('Item $index'), subtitle: const Text('Scroll down then navigate back up'));
            }, childCount: 50),
          ),
        ],
      ),
    );
  }
}
```
</details>

File: packages/flutter/test/widgets/pinned_header_sliver_test.dart [hunk 2]
```diff
@@ -248,4 +251,59 @@ void main() {
     expect(tester.getRect(find.text('PinnedHeaderSliver 1')), rect1);
     expect(tester.getRect(find.text('PinnedHeaderSliver 2')), rect2);
   });
+
+  testWidgets('PinnedHeaderSliver: presence of RenderViewport.excludeFromScrolling tag', (
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/pinned_header_sliver_test.dart]: Can we also have a tests that verifies that inclusion of `container:true`, and `explicitChildNodes: true`.

Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/pinned_header_sliver_test.dart]: Maybe re-name `PinnedHeaderSliver: presence of RenderViewport.excludeFromScrolling tag when pinned`.

File: packages/flutter/test/widgets/pinned_header_sliver_test.dart [hunk 3]
```diff
@@ -248,4 +251,59 @@ void main() {
...
+
+    expect(
+      semantics,
+      isNot(
+        includesNodeWith(
+          tags: {RenderViewport.excludeFromScrolling, RenderViewport.useTwoPaneSemantics},
+        ),
+      ),
+    );
+
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/pinned_header_sliver_test.dart:288]: We should verify that before the drag the sliver is not pinned and the exclude tag is not present and after the drag that it is pinned.

**Review by Renzo-Olivares — COMMENTED** [review]
Thank you for your patience on this one @manu-sncf! I was also able to reproduce the traversal issue when the sliver was pinned as you described. Mostly LGTM with a few comments about testing.

File: packages/flutter/test/widgets/pinned_header_sliver_test.dart (hunk 2 above)
Comment (zemanux) [reply packages/flutter/test/widgets/pinned_header_sliver_test.dart]: I replaced 
```dart
      expect(
        semantics,
        includesNodeWith(
          tags: {RenderViewport.excludeFromScrolling, RenderViewport.useTwoPaneSemantics},
        ),
      );
```

by

```dart
      final SemanticsNode? semanticNode = semantics
          .nodesWith(label: 'PinnedHeaderSliver')
          .firstOrNull;
      expect(semanticNode?.parent?.tags, {
        RenderViewport.excludeFromScrolling,
        RenderViewport.useTwoPaneSemantics,
      });
```

Without a wrapping (`Semantics(container:true, explicitChildNodes: true, child ...)`, the test fail.

Comment (zemanux) [reply packages/flutter/test/widgets/pinned_header_sliver_test.dart]: Done.

File: packages/flutter/test/widgets/pinned_header_sliver_test.dart (hunk 3 above)
Comment (zemanux) [reply packages/flutter/test/widgets/pinned_header_sliver_test.dart:288]: Done.

File: packages/flutter/test/widgets/pinned_header_sliver_test.dart [hunk 4]
```diff
@@ -248,4 +251,76 @@ void main() {
...
+                      itemBuilder: (BuildContext context, int index) => Text('Item $index'),
+                    ),
+                  ],
+                ),
+              ),
+            ),
+          ),
+        ),
+      );
+
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/pinned_header_sliver_test.dart:270]: Maybe we should verify if the sliver actually gets pinned after the drag similar to other tests in this file.  

```dart
Rect getHeaderRect() => tester.getRect(find.text('PinnedHeaderSliver'));
Rect getFirstChildRect() => tester.getRect(find.text('First child'));

// Pinned header appears after first child initially.
final Rect firstChildRect = getFirstChildRect();
expect(firstChildRect.top, 0.0);
expect(firstChildRect.height, 100.0);
expect(getHeaderRect().top, 100.0);

.....
....
...
..
. after drag....

// Pinned header should be pinned to the top after drag.
expect(getHeaderRect().top, 0.0);
```

**Review by Renzo-Olivares — APPROVED** [review]
LGTM, w/ one last comment on the test. Thank you for your patience and contribution!

File: packages/flutter/test/widgets/pinned_header_sliver_test.dart [hunk 5]
```diff
@@ -248,4 +251,76 @@ void main() {
     expect(tester.getRect(find.text('PinnedHeaderSliver 1')), rect1);
     expect(tester.getRect(find.text('PinnedHeaderSliver 2')), rect2);
   });
+
+  testWidgets(
+    'PinnedHeaderSliver: presence of RenderViewport.excludeFromScrolling tag when pinned',
+    (WidgetTester tester) async {
+      final semantics = SemanticsTester(tester);
```
Comment (Renzo-Olivares) [inline packages/flutter/test/widgets/pinned_header_sliver_test.dart:254]: I would add the following to the top of this test.

```
// Regression test for https://github.com/flutter/flutter/issues/179022.
```

File: packages/flutter/test/widgets/pinned_header_sliver_test.dart (hunk 4 above)
Comment (zemanux) [reply packages/flutter/test/widgets/pinned_header_sliver_test.dart:270]: Hi @Renzo-Olivares, I'm back from holidays 😄 ⛷️ 

Done.

File: packages/flutter/test/widgets/pinned_header_sliver_test.dart (hunk 5 above)
Comment (zemanux) [reply packages/flutter/test/widgets/pinned_header_sliver_test.dart:254]: Done.

**Review by Renzo-Olivares — DISMISSED** [review]
LGTM, thank you for the contribution @zemanux! This will just need a secondary approval before it lands.

**Review by Piinks — DISMISSED** [review]
LGTM to me as well! Thank you!

**Comment by zemanux** [comment]
@Renzo-Olivares, I don't know why all reviews have been dismissed (I might have accidentally used my other account @manu-sncf to reply?)

**Review by Piinks — APPROVED** [review]
LGTM

**Review by Renzo-Olivares — APPROVED** [review]
Re-LGTM
