### PR TITLE
Run pub get post-processing for each package in workspace

### LINKED ISSUE #161927: Native folders (.android, .ios, etc.) are not created for add-to-app module when run "pub get" in workspace
Native folders (.android, .ios, etc.) are not created for add-to-app module when run "pub get" in workspace.

### Steps to reproduce

1. `git clone git@github.com:mit-73/flutter_workspace_bug.git`
2. `cd flutter_workspace_bug`
3. run `flutter pub get` in root folder
4. run `cd module/.ios` or `cd module/.android`

### Expected results

Folders have appeared and you can navigate to them.

### Actual results

We get `cd: no such file or directory: module/.ios` or `cd: no such file or directory: module/.android`

### Code sample

https://github.com/mit-73/flutter_workspace_bug

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.2, on macOS 14.2.1 23C71 darwin-arm64, locale ru-RU)
    • Flutter version 3.27.2 on channel stable at /Users/itmiftah10/SDK/flutter/versions/3.27.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68415ad1d9 (8 days ago), 2025-01-13 10:22:03 -0800
    • Engine revision e672b006cb
    • Dart version 3.6.1
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/itmiftah10/SDK/android_studio
    • Platform android-35, build-tools 33.0.2
    • ANDROID_HOME = /Users/itmiftah10/SDK/android_studio
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.96.4)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (1 available)
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by sigurdm**
Fixes https://github.com/flutter/flutter/issues/161927

### CODE REVIEW

File: packages/flutter_tools/lib/src/dart/pub.dart [hunk 1]
```diff
@@ -474,7 +474,7 @@ class _DefaultPub implements Pub {
           'See https://github.com/flutter/flutter/blob/main/docs/contributing/Setting-up-the-Framework-development-environment.md#set-up-your-environment.',
         );
       }
-      throwToolExit('Failed to update packages.', exitCode: code);
+      throwToolExit('Failed to update packages. $pubStderr $buffer', exitCode: code);
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/dart/pub.dart]: I'm not sure we should be adding these details to the tool exit exception. If anything, we should just be logging them to the console.

File: packages/flutter_tools/lib/src/package_graph.dart [hunk 2]
```diff
@@ -149,27 +136,51 @@ class _PackageGraph {
...
+  final List<String> roots;
   final Map<String, List<String>> dependencies;
   final Map<String, List<String>> devDependencies;
+
+  static List<String> _parseList(Map<String, Object?> map, String section) {
+    final Object? list = map[section];
+    if (list == null) {
+      return <String>[];
+    }
+    if (list is! List<Object?>) {
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/package_graph.dart]: I think this function can just be if `section` not being present is an error:

```dart
if (map case {section: final List<String>? list when map.containsKey(section)) {
  return list ?? <String>[];
}
throw FormatException('Expected `$section` to be `List<String>?`, got `${map[section]}');
```

File: packages/flutter_tools/lib/src/commands/packages.dart [hunk 3]
```diff
@@ -363,25 +335,72 @@ class PackagesGetCommand extends FlutterCommand {
...
+          logger: globals.logger,
+          cacheDir: globals.cache.getRoot(),
+          engineVersion: globals.flutterVersion.engineRevision,
+          fileSystem: globals.fs,
+          flutterRootDir: globals.fs.directory(Cache.flutterRoot),
+          outputDir: globals.fs.directory(getBuildDirectory()),
+          processManager: globals.processManager,
+          platform: globals.platform,
+          analytics: analytics,
+          projectDir: project.directory,
```
Comment (bkonyi) [inline packages/flutter_tools/lib/src/commands/packages.dart:365]: I really wish `Environment` had a `copyWith(...)` method so it would be more clear that we're only changing the `projectDir` here.

File: packages/flutter_tools/lib/src/dart/pub.dart (hunk 1 above)
Comment (sigurdm) [reply packages/flutter_tools/lib/src/dart/pub.dart]: Sorry, this was debug code that got committed.

When `pub get` fails in a test it is rather hard to figure out what goes wrong, but that should not be fixed in this PR, and not in this way. Removed.

File: packages/flutter_tools/lib/src/commands/packages.dart (hunk 3 above)
Comment (sigurdm) [reply packages/flutter_tools/lib/src/commands/packages.dart:365]: Well - we don't really have an environment to copy yet.

But yes - some kind of more organized construction of the environment would be nice

File: packages/flutter_tools/lib/src/package_graph.dart (hunk 2 above)
Comment (sigurdm) [reply packages/flutter_tools/lib/src/package_graph.dart]: When trying that i get: Key expressions in map patterns must be constants.

Comment (bkonyi) [reply packages/flutter_tools/lib/src/package_graph.dart]: Oh that's annoying... Honestly, I'd remove this helper and just use the pattern above in its place with the constant keys. This helper function is doing a lot of unnecessary checks.

**Review by matanlurey — COMMENTED** [review]
LGTM, but defer final approval to Ben.

**Comment by bkonyi** [comment]
Once we remove `_parseList`, this will LGTM.

File: packages/flutter_tools/lib/src/package_graph.dart (hunk 2 above)
Comment (sigurdm) [reply packages/flutter_tools/lib/src/package_graph.dart]: One more thing. When you read json the List doesn't become a `List<String>` it is a `List<Object?>`, and you need to validate each item separately and cast the list. I don't think that can be done with pattern matching...

Comment (bkonyi) [reply packages/flutter_tools/lib/src/package_graph.dart]: This definitely works with pattern matching:

```dart
final json = <String, Object?>{
  'foo': <String>['bar', 'baz'],
};

final jsonWithNull = <String, Object?>{
  'foo': <String?>['bar', 'baz', null],
};
void main() {
  if (json case {'foo': final List<String> list}) {
    print('Destructured JSON list: $list Runtime type: ${list.runtimeType}');
  } else {
    print('Failed to destructure $json');
  }

  if (jsonWithNull case {'foo': final List<String> list}) {
    print('Destructured JSON list: $list Runtime type: ${list.runtimeType}');
  } else {
    print('Failed to destructure $jsonWithNull');
  }

  if (jsonWithNull case {'foo': final List<String?> list}) {
    print('Destructured JSON list: $list Runtime type: ${list.runtimeType}');
  } else {
    print('Failed to destructure $jsonWithNull');
  }
}
```

Outputs:

```
Destructured JSON list: [bar, baz] Runtime type: List<String>
Failed to destructure {foo: [bar, baz, null]}
Destructured JSON list: [bar, baz, null] Runtime type: List<String?>
```

Comment (sigurdm) [reply packages/flutter_tools/lib/src/package_graph.dart]: Yes, but when you read json, it doesn't type the lists as `<String>[]`. but `List<dynamic>` (which matches `List<Object?>`).

```
import 'dart:convert';

main() {
  switch (jsonDecode('["A", "B", "C"]')) {
    case final List<String> a:
      print('List of String');
    case final List<Object?> a:
      print('List of Object');
    case final a:
      print('Something else ${a.runtimeType}');
  }
}
```

Comment (bkonyi) [reply packages/flutter_tools/lib/src/package_graph.dart]: Ah, good point... that's really annoying behavior since map patterns are supposed to be most useful for JSON destructuring...

Anyway, this approach would be less verbose than the current one:

```dart
List<String> _parseList(Map<String, Object?> map, String section) {
  final Object? result = map[section];
  try {
    return (result as List<Object?>?)?.cast<String>() ?? <String>[];
  } on TypeError {
    throw FormatException(
      'Expected `$section` to be `List<String>`, got ${result.runtimeType}',
    );
  }
}
```

**Review by bkonyi — APPROVED** [review]
Thanks for humoring me 😅 LGTM!

**Comment by sigurdm** [comment]
@bkonyi thanks! Yeah - async code review is tough sometimes. But thanks for being insistent on code quality!
