### PR TITLE
Fix `showSearch` query text field doesn't show toolbar initially when field is empty.

### LINKED ISSUE #95588: Toolbar not showing on double tap when using showSearch
When using showSearch a double tap on the empty TextField does not show the Toolbar. This only happens on the initial empty state. After changing the TextField's value and reverting back to empty, the Toolbar is able to show up.

The current implementation uses the query setter also on initialization. The empty TextSelection prevents a proper handling of Toolbar on double tap.

## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Click the button
3. Double tap the TextField

**Expected results:** Toolbar shows up

**Actual results:** Toolbar not showing up

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextButton(
                onPressed: () {
                  showSearch(context: context, delegate: Foo());
                },
                child: const Text('showSearch')),
          ],
        ),
      ),
    );
  }
}

class Foo extends SearchDelegate {
  @override
  List<Widget>? buildActions(BuildContext context) {
    return null;
  }

  @override
  Widget? buildLeading(BuildContext context) {
    return null;
  }

  @override
  Widget buildResults(BuildContext context) {
    return Container();
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    return Container();
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.129, on Ubuntu 21.10 5.13.0-22-generic, locale en_US.UTF-8)
    • Flutter version 2.9.0-1.0.pre.129 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ba2f526a4 (3 days ago), 2021-12-17 18:09:14 -0800
    • Engine revision 1db3b8333f
    • Dart version 2.16.0 (build 2.16.0-120.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/virtual/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 13.0.0-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • 192.168.188.39:5585 • android-x64    • Android 12 (API 31) (emulator)
    • Linux (desktop)              • linux               • linux-x64      • Ubuntu 21.10 5.13.0-22-generic
    • Chrome (web)                 • chrome              • web-javascript • Google Chrome 96.0.4664.110
    ! Device 192.168.188.39:5586 is offline.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/95588

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/test/material/search_test.dart [hunk 1]
```diff
@@ -883,6 +883,42 @@ void main() {
...
+
+    final _TestSearchDelegate delegate = _TestSearchDelegate();
+    final List<String> selectedResults = <String>[];
+
+    await tester.pumpWidget(TestHomePage(
+      delegate: delegate,
+      results: selectedResults,
+    ));
+
+    // Open search
```
Comment (justinmc) [inline packages/flutter/test/material/search_test.dart:898]: Period at the end here.

**Review by justinmc — APPROVED** [review]
LGTM 👍
