### PR TITLE
Embed Flutter and App frameworks for add-to-app on iOS

### LINKED ISSUE #101979: [iOS]Flutter which is integrated into iOS projects as a Flutter Module, does not take effect when the code is modified.
I have integrated Flutter into my iOS project as a Flutter Module, and every time I change the Flutter code and then re-run it in Xcode, the code does not take effect.
I have to remove the stuff inside Xcode->DerivedData and then re-run it for it to take effect.
I have created a new iOS project and a new Flutter Module project and have the same problem.
This problem does not exist in 2.2.0.

```
Podfile
target 'flutter_test' do

     flutter_application_path ='../f_f'
     load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
     install_all_flutter_pods(flutter_application_path)

  # Pods for flutter_test

end
```
<details>
<summary>flutter doctor</summary>
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 2.10.3 at /Users/choikarl/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (6 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/choikarl/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle
      (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString
      (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read
      (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer
      (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes
      (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml
      (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion
      (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage
      (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate
      (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand
      (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure>
      (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 13 Pro (mobile) • 9EF2F616-DB7E-4813-BB9B-BC3C3139B3B7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.88
    ! Error: 林夕 is not connected. Xcode will continue when 林夕 is connected. (code -13)

[!] HTTP Host Availability
    ✗ HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host: Operation timed out

! Doctor found issues in 4 categories.

</details>

### PR DESCRIPTION
**Pull request by jmagman**
Previously, the iOS Flutter module copied the Flutter.xcframework and created a dummy version of App.framework in the the ephemeral `.ios` directory, as well as two corresponding `podspec`s that pointed at these frameworks.  On every compilation of the host app, `flutter assemble` would create the real App.framework and copy the right Flutter.framework variant into the Xcode `BUILT_PRODUCTS_DIR`.  On the first build, CocoaPods would then copy/re-codesign/re-strip the frameworks and embed them into the app.

However, since `flutter assemble` updates the frameworks in `BUILT_PRODUCTS_DIR` and not the dummy frameworks in the ephemeral directory, on incremental builds CocoaPods would not run its copy script because the timestamp of the dummy ephemeral frameworks did not change.  So the compiled dart code embedded in the app would not be updated, and would be stale until a hot reload.

1. Stop creating the dummy ephemeral directory frameworks so CocoaPods can find them.  Instead, use the existing tool `podhelper` scripts that embed the frameworks into the app.  `assemble` already codesigns, bitcode strips, and debug symbol strips the frameworks, so all that's left it to `rsync` them to the right place in the app.
2. Deduplicate engine/plugins logic in the add-to-app `podhelper.rb` ruby script to use the [Flutter SDK `flutter_tools/bin/podhelper.rb` version of this file](https://github.com/flutter/flutter/blob/f15295cc91dfa1b9705d318edca27cf9605e1f73/packages/flutter_tools/bin/podhelper.rb#L1) to push as much logic as possible into the SDK instead of the module project.
3. Update the SDK ruby script to use relative paths in places where it had assumed relative location from the Podfile (since now it's being called from host apps, which are located outside the Flutter module).

Fixes https://github.com/flutter/flutter/issues/101979
Probably would have resolved parts of https://github.com/flutter/flutter/issues/94481
Follow-up to https://github.com/flutter/flutter/pull/101943

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: dev/devicelab/bin/tasks/module_test_ios.dart [hunk 1]
```diff
@@ -79,32 +80,6 @@ Future<void> main() async {
         );
       }
 
-      section('Build ephemeral host app when SDK is on external disk');
-
-      // Pretend the SDK was on an external drive with stray "._" files in the xcframework
```
Comment (jmagman) [inline dev/devicelab/bin/tasks/module_test_ios.dart:84]: `.ios/Flutter/engine` no longer exists

File: packages/flutter_tools/bin/podhelper.rb [hunk 2]
```diff
@@ -190,7 +191,7 @@ def flutter_install_ios_engine_pod(ios_application_path = nil)
   }
 
   # Keep pod path relative so it can be checked into Podfile.lock.
-  pod 'Flutter', :path => 'Flutter'
+  pod 'Flutter', :path => flutter_relative_path_from_podfile(podspec_directory)
```
Comment (jmagman) [inline packages/flutter_tools/bin/podhelper.rb:194]: This is now called from the host app Podfile script, and the fake podspec is in the Flutter module, so don't assume they are siblings.

File: packages/flutter_tools/bin/xcode_backend.dart [hunk 3]
```diff
@@ -321,28 +321,7 @@ class Context {
       targetPath = environment['FLUTTER_TARGET']!;
     }
 
-    String derivedDir = '$sourceRoot/Flutter}';
-    if (existsDir('$projectPath/.ios')) {
-      derivedDir = '$projectPath/.ios/Flutter';
-    }
-
-    // Use FLUTTER_BUILD_MODE if it's set, otherwise use the Xcode build configuration name
```
Comment (jmagman) [inline packages/flutter_tools/bin/xcode_backend.dart:329]: This comment is already in `parseFlutterBuildMode` we don't need it twice.

File: packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb.tmpl [hunk 4]
```diff
@@ -42,30 +42,12 @@ end
...
-  # defined_in_file is a Pathname to the Podfile set by CocoaPods.
-  project_directory_pathname = defined_in_file.dirname
-  relative = engine_pathname.relative_path_from project_directory_pathname
+def install_flutter_engine_pod(flutter_application_path = nil)
+  flutter_application_path ||= File.join('..', '..')
+  ios_application_path = File.join(flutter_application_path, '.ios')
 
-  pod 'Flutter', :path => relative.to_s, :inhibit_warnings => true
+  # flutter_install_ios_engine_pod is in Flutter root podhelper.rb
+  flutter_install_ios_engine_pod(ios_application_path)
```
Comment (jmagman) [inline packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb.tmpl:50]: Instead of duplicating logic, call the ruby script in the tool 
https://github.com/flutter/flutter/blob/aa5d7b6972ee5be596c15b83d39f7d3dde6ad939/packages/flutter_tools/bin/podhelper.rb#L159

File: packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb.tmpl [hunk 5]
```diff
@@ -79,33 +61,13 @@ end
 #                                          MyApp/my_flutter/.ios/Flutter/../..
 def install_flutter_plugin_pods(flutter_application_path)
   flutter_application_path ||= File.join('..', '..')
+  ios_application_path = File.join(flutter_application_path, '.ios')
+  # flutter_install_plugin_pods is in Flutter root podhelper.rb
+  flutter_install_plugin_pods(ios_application_path, '.symlinks', 'ios')
```
Comment (jmagman) [inline packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb.tmpl:66]: Remove duplicated logic, call https://github.com/flutter/flutter/blob/aa5d7b6972ee5be596c15b83d39f7d3dde6ad939/packages/flutter_tools/bin/podhelper.rb#L238

File: packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb.tmpl [hunk 6]
```diff
@@ -118,30 +80,24 @@ end
...
-  current_directory_pathname = Pathname.new File.expand_path('..', __FILE__)
-  app_framework_dir = File.expand_path('App.framework', current_directory_pathname.to_path)
-  app_framework_dylib = File.join(app_framework_dir, 'App')
-  if !File.exist?(app_framework_dylib)
-    # Fake an App.framework to have something to link against if the xcode backend script has not run yet.
-    # CocoaPods will not embed the framework on pod install (before any build phases can run) if the dylib does not exist.
-    # Create a dummy dylib.
-    FileUtils.mkdir_p(app_framework_dir)
-    sdk_path = `xcrun --sdk iphoneos --show-sdk-path`.strip
-    `echo "static const int Moo = 88;" | xcrun clang -x c -arch arm64 -dynamiclib -miphoneos-version-min=11.0 -isysroot "#{sdk_path}" -o "#{app_framework_dylib}" -`
```
Comment (jmagman) [inline packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb.tmpl:130]: Stop making the dummy App.framework in the ephemeral module directory.
🐮

File: packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb.tmpl [hunk 7]
```diff
@@ -42,30 +42,12 @@ end
 #   target 'MyApp' do
 #     install_flutter_engine_pod
 #   end
-def install_flutter_engine_pod
-  current_directory = File.expand_path('..', __FILE__)
-  engine_dir = File.expand_path('engine', current_directory)
-  framework_name = 'Flutter.xcframework'
-  copied_engine = File.expand_path(framework_name, engine_dir)
```
Comment (jmagman) [inline packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb.tmpl:49]: Stop copying the engine into the module ephemeral directory.  Let the tool handle copying the right version where it needs to go when `assemble` is called.

File: packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb.tmpl [hunk 8]
```diff
@@ -118,30 +80,24 @@ end
...
   flutter_export_environment_path = File.join('${SRCROOT}', relative, 'flutter_export_environment.sh');
+
+  # Compile App.framework and move it and Flutter.framework to "BUILT_PRODUCTS_DIR"
   script_phase :name => 'Run Flutter Build {{projectName}} Script',
     :script => "set -e\nset -u\nsource \"#{flutter_export_environment_path}\"\nexport VERBOSE_SCRIPT_LOGGING=1 && \"$FLUTTER_ROOT\"/packages/flutter_tools/bin/xcode_backend.sh build",
     :execution_position => :before_compile
+
+  # Embed App.framework AND Flutter.framework.
+  script_phase :name => 'Embed Flutter Build {{projectName}} Script',
+    :script => "set -e\nset -u\nsource \"#{flutter_export_environment_path}\"\nexport VERBOSE_SCRIPT_LOGGING=1 && \"$FLUTTER_ROOT\"/packages/flutter_tools/bin/xcode_backend.sh embed_and_thin",
```
Comment (jmagman) [inline packages/flutter_tools/templates/module/ios/library/Flutter.tmpl/podhelper.rb.tmpl:99]: Instead of letting CocoaPods copy/re-codesign/strip the frameworks from the ephemeral directory, instead let the tool copy it via `embed_and_thin` after the rest of the app has compiled.  The tool already codesigned/stripped it during `assemble`.

**Review by cyanglaz — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
friendly ping @christopherfujino

**Review by christopherfujino — APPROVED** [review]
Sorry, thought I approved this, LGTM
