### PR TITLE
Clarify that inputFormatters don't run on programmatical changes

### LINKED ISSUE #106821: Setting text through TextEditingController.text doesn't apply the TextInputFormatters
## Steps to Reproduce

1. Build a basic flutter app with a single textfield/textformfield and a TextEditingController
2. Add an inputFormatter 
3. Have a button to trigger setting the TextEditingController '.text' property and the input formatters are not triggered/applied.

**Expected results:** The inputFormatters get applied instead of just ignoring them entirely. My specific use case is building an onscreen keyboard and inputting keystrokes manually to a TextEditingController. 

**Actual results:** The value is set no matter what the inputFormatters are.

I am not sure why but there was another issue(https://github.com/flutter/flutter/issues/30369) posted for this exact same reason and it was closed due to operating "as designed"? Not sure how that's supposed to be the designed way but would love more of an explanation.

**Flutter version:** 
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c860cba910 (3 months ago) • 2022-03-25 00:23:12 -0500
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Closes https://github.com/flutter/flutter/issues/106821
Also updated the default font size in the documentation to be 14.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/painting/text_style.dart [hunk 1]
```diff
@@ -504,7 +504,7 @@ class TextStyle with Diagnosticable {
   /// style (e.g., in a [TextSpan] tree).
   ///
   /// If this is false, properties that don't have explicit values will revert
-  /// to the defaults: white in color, a font size of 10 pixels, in a sans-serif
+  /// to the defaults: white in color, a font size of 14 pixels, in a sans-serif
```
Comment (justinmc) [inline packages/flutter/lib/src/painting/text_style.dart:507]: Good catch.

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

Thanks for updating these docs, hopefully that clears up the confusion.
