### PR TITLE
Fix DropdownButton bug

### LINKED ISSUE #65748: DropdownButton throws exception when hint and selectedItemBuilder is provided
This issue already was posted before in [#42340](https://github.com/flutter/flutter/issues/42340) but still occurs on master.

## Steps to Reproduce

1. Create a `DropdownButton` with `hint` and `selectedItemBuilder`

**Expected results:** 
Button should work

**Actual results:**
Exception is thrown:

<details><summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building DropdownButton<String>(dirty, dependencies:
[Directionality, _InheritedTheme, MediaQuery, _LocalizationsScope-[GlobalKey#2b9e0]], state:
_DropdownButtonState<String>#f399a):
type 'DefaultTextStyle' is not a subtype of type 'Center' of 'value'
The relevant error-causing widget was:
  DropdownButton<String>
  file:///D:/dev/flutter/project/lib/screens/enter_details_screen.dart:60:20
When the exception was thrown, this was the stack:
#0      List.add (dart:core-patch/growable_array.dart)
#1      _DropdownButtonState.build (package:flutter/src/material/dropdown.dart:1327:13)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#9      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#11     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#17     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#21     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#25     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#29     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#33     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#37     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#41     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#43     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
#44     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#52     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#64     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#71     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#77     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#81     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#85     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#87     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#89     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#93     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#96     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#98     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#101    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#103    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#107    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#111    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#114    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#116    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#122    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#124    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#129    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#131    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#133    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#135    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#138    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#140    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#144    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#147    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#148    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#149    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#151    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#155    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#156    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#158    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#161    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#162    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#163    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#164    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#167    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#168    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#170    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#171    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#172    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#175    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#176    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#177    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#178    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#179    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#182    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#185    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#186    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#187    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
#188    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
#189    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#190    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#191    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#192    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
Flutter 1.22.0-10.0.pre.161 • channel master • https://github.com/flutter/flutter.git
Framework • revision cba91c97d0 (8 hours ago) • 2020-09-13 18:57:03 -0400
Engine • revision 2fc054147e
Tools • Dart 2.10.0 (build 2.10.0-121.0.dev)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.22.0-10.0.pre.161, on Microsoft Windows [Version 10.0.18363.1082], locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Android Studio (version 4.0)

```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
## Description

@shihaohong Please review.

This is a fix of the regression of #42340.
This regression should have been intercepted by the test case. Unfortunately, the original test case did not cover the real issue scenario.

## Related Issues

Fixes #65748 

## Tests

See files.

### CODE REVIEW

File: packages/flutter/test/material/dropdown_test.dart [hunk 1]
```diff
@@ -1942,7 +1942,7 @@ void main() {
                   selectedItem = string;
                 }),
                 selectedItemBuilder: (BuildContext context) {
-                  return items.map<Widget>((String item) {
```
Comment (HansMuller) [inline packages/flutter/test/material/dropdown_test.dart:1945]: Why remove the type parameter here?

File: packages/flutter/lib/src/material/dropdown.dart [hunk 2]
```diff
@@ -1306,16 +1306,9 @@ class _DropdownButtonState<T> extends State<DropdownButton<T>> with WidgetsBindi
...
-    if (_enabled) {
-      items = widget.selectedItemBuilder == null
-        ? List<Widget>.from(widget.items)
-        : widget.selectedItemBuilder(context);
-    } else {
-      items = widget.selectedItemBuilder == null
-        ? <Widget>[]
-        : widget.selectedItemBuilder(context);
-    }
+    final List<Widget> items = widget.selectedItemBuilder == null
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/dropdown.dart:1309]: This appears to just be a compact rewrite of the previous, although I'll be pleased to hear that I'm missing something :-). 

What is the flaw that we're correcting in this PR?

**Review by HansMuller — DISMISSED** [review]
This will need a regression test and the PR's description needs a brief explanation of the analysis and the fix.

File: packages/flutter/lib/src/material/dropdown.dart (hunk 2 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/dropdown.dart:1309]: We should explicit the type of the specified list so that different types of elements can be added again later.

File: packages/flutter/test/material/dropdown_test.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/test/material/dropdown_test.dart:1945]: This is not the real issue situation.

**Comment by xu-baolin** [comment]
@HansMuller Sorry for the unclear description, I have update it now.

**Comment by HansMuller** [comment]
> @HansMuller Sorry for the unclear description, I have updated it now.
> I have a suggestion. Can our CI check our new submission regress test expect failed before the fix was merged?

You'll have to do that. Just stash your changes before running the test to ensure that it fails.

**Comment by xu-baolin** [comment]
> > @HansMuller Sorry for the unclear description, I have updated it now.
> > I have a suggestion. Can our CI check our new submission regress test expect failed before the fix was merged?
> 
> You'll have to do that. Just stash your changes before running the test to ensure that it fails.

Yes, we must do that before post a PR.
But sometimes robots are more reliable than humans, just a suggestion for improvement ：）

**Comment by xu-baolin** [comment]
@HansMuller Ready for review, thanks :)

**Comment by HansMuller** [comment]
I apologize for not having time to really dig in here. My initial reaction was that we need to find a way to enable simpler extensions of RectangularSliderTrackShape (or something like it) that would make it easy to introduce a visualization of a secondaryValue - but not just a secondaryValue. So far, I haven't had time make a concrete proposal though.

**Comment by xu-baolin** [comment]
> I apologize for not having time to really dig in here. My initial reaction was that we need to find a way to enable simpler extensions of RectangularSliderTrackShape (or something like it) that would make it easy to introduce a visualization of a secondaryValue - but not just a secondaryValue. So far, I haven't had time make a concrete proposal though.

OK, I will continue to follow this line of thinking to find the best solution.
But you seem to be confused with #64452

**Comment by HansMuller** [comment]
Yes, sorry about that. I was just looking at #64452 and was wondering where my comment had gone..

**Comment by xu-baolin** [comment]
@HansMuller Hi, Easy fixed bugs and simpler modifications, please review.

File: packages/flutter/test/material/dropdown_test.dart (hunk 1 above)
Comment (shihaohong) [reply packages/flutter/test/material/dropdown_test.dart:1945]: Right -- Basically, what @xu-baolin means here is that we should explicitly require `selectedItemBuilder` to return a list of `Widgets` internally. Before his change, this test would have failed if `<Widget>` was not specified. With his change, not explicitly adding the type parameter does not trigger the crash/failure.

Maybe we could add a comment above [the selectedItemBuilder code](https://github.com/flutter/flutter/blob/89a7bd05bdb7445d4815bde4300a7115a563c182/packages/flutter/lib/src/material/dropdown.dart#L1306) describing this? It might help future contributors/readers understand this requirement.

**Review by shihaohong — APPROVED** [review]
LGTM. We should add a comment to the code describing why we explicitly return a List of Widgets.

**Review by shihaohong — APPROVED** [review]
