### PR TITLE
Unfocus search anchor bar when the view is closed

### LINKED ISSUE #178719: `SearchAnchor.bar`, `onSubmit`, doesn't lose focus, leading to a unintended `.pop`
Follows #177454

### Steps to reproduce

1. Click the search bar (by tapping it, you focus it)
2. See the suggestions appear: `Example 1` and `Example 2` appear
3. Type `exa` in the search bar
4. Press `Enter` (submit)
5. You'll see focus **is not** lost, and indeed
6. Press `Enter` again

### Expected results

Pressing enter loses focus, thus pressing `Enter` again (step 6) is not allowed; therefore, there should be no side effects.

### Actual results

The current view is popped, meaning that `_controller.closeView(value)` is evaluated again; probably, such evaluation leads to a `context.pop`.

### Code sample

<details open><summary>Code sample</summary>

```dart
import "package:flutter/material.dart";
import "package:flutter_riverpod/flutter_riverpod.dart";

void main() {
  runApp(const ProviderScope(child: MySearchBarPage()));
}

class MySearchBarPage extends ConsumerWidget {
  const MySearchBarPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text("My Search Bar Page"),
        ),
        body: const Center(
          child: MySearchAnchorBar(),
        ),
      ),
    );
  }
}

class MySearchAnchorBar extends StatefulWidget {
  const MySearchAnchorBar({super.key});

  @override
  State<MySearchAnchorBar> createState() => _MySearchAnchorBarState();
}

class _MySearchAnchorBarState extends State<MySearchAnchorBar> {
  late final SearchController _controller;

  @override
  void initState() {
    super.initState();
    _controller = SearchController();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SearchAnchor.bar(
      searchController: _controller,
      barElevation: WidgetStateProperty.all(2),
      barPadding: const WidgetStatePropertyAll(
        EdgeInsets.symmetric(horizontal: 12),
      ),

      viewHeaderTextStyle: const TextStyle(fontSize: 14),
      barTextStyle: WidgetStateProperty.all(
        const TextStyle(fontSize: 14),
      ),
      viewLeading: const Icon(Icons.search),
      viewBarPadding: const EdgeInsets.symmetric(horizontal: 12),
      scrollPadding: EdgeInsets.zero,
      viewPadding: EdgeInsets.zero,
      onSubmitted: (value) {
        _controller.closeView(value);
        // focus is kept on the bar.
      },
      suggestionsBuilder: (context, controller) async {
        final results = await Future.value(<String>["Example1", "Example2"]);

        return [
          for (final element in results)
            ListTile(
              title: Text(
                element,
              ),
              onTap: () {
                print("Selected: $element");
                controller.closeView(element);
              },
            ),
        ];
      },
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/606aa4b8-f4d1-44ec-b451-5c25028d1b34

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
lutter doctor -v
[✓] Flutter (Channel stable, 3.38.1, on macOS 15.6.1 24G90 darwin-arm64, locale en-IT) [201ms]
    • Flutter version 3.38.1 on channel stable at /Users/venir/.local/share/mise/installs/flutter/3.38.1-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b45fa18946 (5 days ago), 2025-11-12 22:09:06 -0600
    • Engine revision b5990e5ccc
    • Dart version 3.10.0
    • DevTools version 2.51.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios, cli-animations,
      enable-native-assets, omit-legacy-version-file, enable-lldb-debugging

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0-rc1) [2.2s]
    • Android SDK at /Users/venir/Library/Android/sdk
    • Emulator version 35.2.10.0 (build_id 12414864) (CL:N/A)
    • Platform android-36, build-tools 36.0.0-rc1
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 26.1.1) [464ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 17B100
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [4ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (2 available) [5.7s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.6.1 24G90 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 142.0.7444.162

[✓] Network resources [223ms]
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by huycozy**
- Fix https://github.com/flutter/flutter/issues/178719
- See https://github.com/flutter/flutter/issues/178719#issuecomment-3561809294 for details of debugging and proposal.

<details open>
<summary>Demo (after the fix)</summary>

https://github.com/user-attachments/assets/cecb470f-d98c-47b0-a34d-fc858cfb0dd4
</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

**Note**: The Flutter team is currently trialing the use of [Gemini Code Assist for GitHub](https://developers.google.com/gemini-code-assist/docs/review-github-code). Comments from the `gemini-code-assist` bot should not be taken as authoritative feedback from the Flutter team. If you find its comments useful you can update your code accordingly, but if you are unsure or disagree with the feedback, please feel free to wait for a Flutter team member's review for guidance on which automated comments should be addressed.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter/test/material/search_anchor_test.dart [hunk 1]
```diff
@@ -995,9 +995,75 @@ void main() {
     await tester.testTextInput.receiveAction(TextInputAction.done);
     expect(onSubmittedCalled, 1);
     expect(controller.isOpen, false);
+  });
 
+  // Regression test for https://github.com/flutter/flutter/issues/178719.
+  testWidgets('SearchAnchor.bar anchor loses focus after view closes', (WidgetTester tester) async {
```
Comment (QuncCccccc) [inline packages/flutter/test/material/search_anchor_test.dart:1001]: Nice test!

**Review by QuncCccccc — COMMENTED** [review]
LGTM:) Thanks for the fix. I also checked some real app like Google maps, it seems when the search view is closed by typing "done", the search bar lose focus. So this behavior matches the native behavior.

**Review by QuncCccccc — APPROVED** [review]
