### PR TITLE
Reattempt: Restores surface size and view configuration in the postTest of test binding

### LINKED ISSUE #87194: widget_tester_live_device_test.dart: Should print message on pointer events Failing consistently
Starting on the Engine roll here https://github.com/flutter/flutter/pull/87159

However that Engine roll only contained Skia commits that couldn't have affected Flutter due to containing only changes related to Skia infrastructure.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_misc/1685/overview

```
The following TestFailure object was thrown running a test:
  Expected: <400.0>
  Actual: <1000.0>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///b/s/w/ir/x/w/flutter/packages/flutter_test/test/widget_tester_live_device_test.dart:44:5)
```

/cc @HansMuller @goderbauer

### PR DESCRIPTION
**Pull request by dkwingsmt**
This is a reattempt to fix #87194. 

The previous attempt https://github.com/flutter/flutter/pull/87240 was reverted because many internal tests was written in a way that sets the view configuration at the beginning of a file and expect to use it throughout the file, which was broken by the previous method.

```dart
void main() {
  binding.renderView.configuration = TestViewConfiguration(size: const Size(900, 900));
  testWidget('test1', ...);
  testWidget('test2', ...);
}
```

This PR restores the surface size and the view configuration in the following strategy:
- The surface size is always reset to null at `postTest`, since the surface size can not be changed out of tests.
- The view configuration is recorded at `reset` (the pre-test hook), and is restored to that value at `postTest`.

I tested this change against some previously failing tests and they have been passing.

This PR also removes the temporary teardown cleanup in `viewport_test.dart`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter_test/lib/src/binding.dart [hunk 1]
```diff
@@ -163,17 +163,27 @@ abstract class TestWidgetsFlutterBinding extends BindingBase
...
   /// the [testTextInput] is configured to simulate the keyboard.
   void reset() {
+    assert(_surfaceSize == null);
+    _preTestViewConfiguration = renderView.configuration;
     _restorationManager = null;
     resetGestureBinding();
     testTextInput.reset();
     if (registerTestTextInput)
       _testTextInput.register();
+
```
Comment (goderbauer) [inline packages/flutter_test/lib/src/binding.dart:186]: nit: remove this blank line?

File: packages/flutter_test/test/bindings_reset_configuration_test.dart [hunk 2]
```diff
@@ -0,0 +1,29 @@
+// Copyright 2014 The Flutter Authors. All rights reserved.
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+import 'package:flutter/widgets.dart';
+import 'package:flutter_test/flutter_test.dart';
+
+
```
Comment (goderbauer) [inline packages/flutter_test/test/bindings_reset_configuration_test.dart:8]: nit: remove a blank line?

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM

(Probably needs a rebase to make the check happy)
