### PR TITLE
Constrain RawAutocomplete options by soft keyboard

### LINKED ISSUE #157664: Autocomplete options overlay should automatically moves up when soft keyboard is visible
### Steps to reproduce

When soft keyboard is visible, unless options widget is constrained or set to a specific height, part of the options overlay will be hidden behind the keyboard. This is a dealbreaker especially in mobile, since we would prefer not to set a specific height value.

### Expected results

https://github.com/user-attachments/assets/9d3bdf77-3474-48fc-9631-cea09470ed73

### Actual results

https://github.com/user-attachments/assets/ce09822d-c6a9-4681-a84a-2103cda1a31e

### Code sample

```dart
import "package:flutter/material.dart";
import "package:tokowijaya/features/widgets/custom_autocomplete.dart";

/// Flutter code sample for [RawAutocomplete].

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        resizeToAvoidBottomInset: false,
        appBar: AppBar(
          title: const Text("RawAutocomplete Basic"),
        ),
        body: const Center(
          child: AutocompleteBasicExample(),
        ),
      ),
    );
  }
}

class AutocompleteBasicExample extends StatelessWidget {
  const AutocompleteBasicExample({super.key});

  static const List<String> _options = <String>[
    "aardvark",
    "bobcat",
    "chameleon",
    "chameleon",
    "chameleon",
    "chameleon",
    "chameleon",
    "chameleon",
    "chameleon",
  ];

  @override
  Widget build(BuildContext context) {
    return CustomAutocomplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) {
        return _options.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      fieldViewBuilder: (
        BuildContext context,
        TextEditingController textEditingController,
        FocusNode focusNode,
        VoidCallback onFieldSubmitted,
      ) {
        return TextFormField(
          controller: textEditingController,
          focusNode: focusNode,
          onFieldSubmitted: (String value) {
            onFieldSubmitted();
          },
        );
      },
      optionsViewBuilder: (
        BuildContext context,
        AutocompleteOnSelected<String> onSelected,
        Iterable<String> options,
      ) {
        return Material(
          elevation: 4,
          child: ListView.builder(
            padding: const EdgeInsets.all(8),
            itemCount: options.length,
            itemBuilder: (BuildContext context, int index) {
              final option = options.elementAt(index);
              return GestureDetector(
                onTap: () {
                  onSelected(option);
                },
                child: ListTile(
                  title: Text(option),
                ),
              );
            },
          ),
        );
      },
    );
  }
}
```

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

```
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-ID)
    • Flutter version 3.24.3 on channel stable at /Users/dikatok/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dikatok/Library/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/dikatok/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.94.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.99.20240930

[✓] Connected device (4 available)
    • 2201117TG (mobile)              • cb0b36bc              • android-arm64  • Android 13 (API 33)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 130.0.6723.70

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by victorsanni**
Fixes [Autocomplete options overlay should automatically moves up when soft keyboard is visible](https://github.com/flutter/flutter/issues/157664)
Fixes b/317115348

Unblocked by https://github.com/flutter/flutter/pull/181579.

## Before

https://github.com/user-attachments/assets/586944be-6ff1-4817-980e-334bfefb6c62

## After

https://github.com/user-attachments/assets/086f4be9-0ebc-43af-b85b-3435d4144920

<details>
<summary>Sample code</summary>

```dart

import "package:flutter/material.dart";

void main() => runApp(const AutocompleteExampleApp());

/// Flutter code sample for [RawAutocomplete].

class AutocompleteExampleApp extends StatelessWidget {
  const AutocompleteExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text("RawAutocomplete Basic"),
        ),
        body: const CustomScrollView(
          slivers: [
            SliverPadding(padding: EdgeInsets.symmetric(vertical: 300)),
            SliverToBoxAdapter(child: AutocompleteBasicExample()),
            SliverPadding(padding: EdgeInsets.symmetric(vertical: 700)),
          ],
        ),
      ),
    );
  }
}

class AutocompleteBasicExample extends StatelessWidget {
  const AutocompleteBasicExample({super.key});

  static const List<String> _options = <String>[
    "aardvark",
    "bobcat",
    "chameleon",
    "chameleon",
  ];

  @override
  Widget build(BuildContext context) {
    return RawAutocomplete<String>(
      optionsBuilder: (TextEditingValue textEditingValue) {
        return _options.where((String option) {
          return option.contains(textEditingValue.text.toLowerCase());
        });
      },
      fieldViewBuilder: (
        BuildContext context,
        TextEditingController textEditingController,
        FocusNode focusNode,
        VoidCallback onFieldSubmitted,
      ) {
        return TextFormField(
          controller: textEditingController,
          focusNode: focusNode,
          onFieldSubmitted: (String value) {
            onFieldSubmitted();
          },
        );
      },
      optionsViewBuilder: (
        BuildContext context,
        AutocompleteOnSelected<String> onSelected,
        Iterable<String> options,
      ) {
        return const Column(
          children: <Widget>[Expanded(child: Placeholder())],
        );
      },
    );
  }
}

```
</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by victorsanni** [comment]
Continuation of https://github.com/flutter/flutter/pull/163868

File: packages/flutter/lib/src/widgets/autocomplete.dart [hunk 1]
```diff
@@ -584,13 +584,15 @@ class _RawAutocompleteState<T extends Object> extends State<RawAutocomplete<T>>
     final Size fieldSize = layoutInfo.childSize;
     final Matrix4 invertTransform = layoutInfo.childPaintTransform.clone()..invert();
 
+    final MediaQueryData mediaQueryData = MediaQuery.of(context);
```
Comment (navaronbracke) [inline packages/flutter/lib/src/widgets/autocomplete.dart]:
```suggestion
final EdgeInsets mediaQueryPadding = MediaQuery.paddingOf(context);
final EdgeInsets viewInsets = MediaQuery.viewInsetsOf(context);

final Rect overlayRect = mediaQueryPadding.deflateRect(
  viewInsets.deflateRect(Offset.zero & layoutInfo.overlaySize),
);
```

Comment (justinmc) [reply packages/flutter/lib/src/widgets/autocomplete.dart]: +1 to this, so that it only rebuilds when padding changes. See https://main-api.flutter.dev/flutter/widgets/InheritedModel-class.html.

**Review by justinmc — APPROVED** [review]
LGTM :+1:. Thanks for following up on this! What was the change that made this possible, out of curiosity?

Is there any reason to allow users to opt into the old behavior, or is it definitely not desirable behavior?

**Review by Piinks — APPROVED** [review]
This also LGTM with the nit regarding paddingOf

**Comment by victorsanni** [comment]
> Thanks for following up on this! What was the change that made this possible, out of curiosity?

https://github.com/flutter/flutter/pull/181579, adding to PR description.

> Is there any reason to allow users to opt into the old behavior, or is it definitely not desirable behavior?

Definitely not desirable, currently options can't be tapped when hidden behind the keyboard, this PR fixes that.

File: packages/flutter/test/widgets/autocomplete_test.dart [hunk 2]
```diff
@@ -3670,4 +3670,132 @@ void main() {
...
+
+  testWidgets('Options view is constrained by MediaQuery bottom padding and view insets', (
+    WidgetTester tester,
+  ) async {
+    const padding = 50.0;
+    const bottomInsets = 70.0;
+    tester.view.devicePixelRatio = 1.0;
+    addTearDown(tester.view.reset);
+    await tester.pumpWidget(
+      MaterialApp(
```
Comment (navaronbracke) [inline packages/flutter/test/widgets/autocomplete_test.dart]: Can you use non-material widgets in this test? I.e. TestWidgetsApp and TestTextField?

RawAutocomplete is not material specific. We're in the process of trying to avoid Material imports in flutter/widgets.

While there are Material imports for the other tests in this file, I'd like to avoid introducing new Material widgets, for the clean up efforts, once someone gets to this file.

**Review by LongCatIsLooong — APPROVED** [review]

**Comment by victorsanni** [comment]
Scuba changes are expected.
