### PR TITLE
obscureText and enableInteractiveSelection defaults

### LINKED ISSUE #24100: Obscured text field content is copy-able
## Steps to Reproduce (tested on iOS only)

1. Create a TextField widget with obscureText set to true
2. Write some text in there and long-press it
3. Press copy and paste it anywhere else

## What Was Expected

Copy option not to even appear, and not to reveal any of the data

## What Happened

I could copy the obscured text

### PR DESCRIPTION
**Pull request by justinmc**
Closes https://github.com/flutter/flutter/issues/24100

### CODE REVIEW

**Comment by justinmc** [comment]
@HansMuller Ready for review whenever you get a chance.  I added docs and tests.

File: packages/flutter/lib/src/material/text_field.dart [hunk 1]
```diff
@@ -298,6 +297,12 @@ class TextField extends StatefulWidget {
   /// {@macro flutter.widgets.editableText.enableInteractiveSelection}
   final bool enableInteractiveSelection;
 
+  /// Whether or not this field allows text selection.
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/text_field.dart]: This isn't quite right, since it's about interactive text selection; you can still programmatically change the selection with the controller.

Sadly, I think it will be necessary to exhaustively explain what this getter means vis. enableInteractiveSelection and obscureText.

Similarly, enabledInteractiveSelection will need to explain its (new) default value, etc.

**Comment by justinmc** [comment]
@HansMuller I improved the documentation with your comment.  I'm a little bit worried about the relationship between TextField's `enableInteractiveSelection` and EditableText's property of the same name.  They do the same thing but have different defaults.  I copied most of the docs but changed the default.  Does that look ok to you or is there a better way?

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -469,6 +459,11 @@ class EditableText extends StatefulWidget {
   /// Defaults to false, resulting in a typical blinking cursor.
   static bool debugDeterministicCursor = false;
 
+  /// {@macro flutter.widgets.editable.selectionEnabled}
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart]: Did I set up this macro correctly?

**Comment by justinmc** [comment]
@HansMuller Updated according to the refactor we talked about.

File: packages/flutter/lib/src/rendering/editable.dart [hunk 3]
```diff
@@ -715,6 +712,19 @@ class RenderEditable extends RenderBox {
     markNeedsSemanticsUpdate();
   }
 
+  /// {@template flutter.widgets.editable.selectionEnabled}
+  /// Decides if selection is enabled based on [enableInteractiveSelection] and
+  /// [obscureText] to make the common use case of password fields simple while
+  /// still allowing selection of obscured text.
+  ///
+  /// Just setting [obscureText] to true will create a typical Material password
```
Comment (HansMuller) [inline packages/flutter/lib/src/rendering/editable.dart]: Don't refer to Material here, RenderEditable and EditableText are used elsewhere.  The simplest way to define this method's value might be to do the case analysis:

- By default [enableInteractiveSelection] is null, obscureText is false, and this method returns true.
- If [enableInteractiveSelection] is null, obscureText is true, then this method returns false. This is the common case for password fields.
- If  [enableInteractiveSelection] is non-null then its value is returned.  An app might set it to true to enable interactive selection for a password field, or to false to unconditionally disable interactive selection.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 2 above)
Comment (HansMuller) [reply packages/flutter/lib/src/widgets/editable_text.dart]: Yes. The template appears in RenderEditable, so the macro tag should be `flutter.rendering.editable.selectionEnabled`.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 4]
```diff
@@ -452,15 +450,7 @@ class EditableText extends StatefulWidget {
...
-  /// {@template flutter.widgets.editableText.enableInteractiveSelection}
-  /// If true, then long-pressing this TextField will select text and show the
-  /// cut/copy/paste menu, and tapping will move the text caret.
-  ///
-  /// True by default.
-  ///
-  /// If false, most of the accessibility support for selecting text, copy
-  /// and paste, and moving the caret will be disabled.
-  /// {@endtemplate}
+  /// {@macro flutter.widgets.editableText.enableInteractiveSelection}
```
Comment (HansMuller) [inline packages/flutter/lib/src/widgets/editable_text.dart]: The `@template` definition of this macro should appear in rendering/editable.dart.

At the moment it does appear to be defined anywhere.

**Comment by justinmc** [comment]
@HansMuller Updated to address your comments.  Let me know if I got everything.

**Review by HansMuller — APPROVED** [review]
LGTM
