### PR TITLE
Animate TextStyle.fontVariations

### LINKED ISSUE #105120: `fontVariations` property is not animatable within `AnimatedDefaultTextStyle`
## Steps to Reproduce

1. Switch Flutter framework to `master` channel (3.1.0-0.0.pre.1037, at the moment)
2. Add the variable font **Roboto Flex** TTF file to your project (download page: https://fonts.google.com/specimen/Roboto+Flex)
```
/
│
└── fonts/
    └── RobotoFlex-VariableFont_GRAD,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf
```
3. Update **pubspec.yaml** file
```yaml
  fonts:
    - family: 'Roboto Flex'
      fonts:
        - asset: 'fonts/RobotoFlex-VariableFont_GRAD,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf'

```
4. Execute `flutter run` on the code sample
5. Click on **Color** or **Font size** button and see how the changes for the sample text above (_þΩ_) of those properties take place over a period of time (2 seconds)
6. Click now on **Weight (wght)** or **Width (wdth)** or **Slant (slnt)** (some of **font axes** of Roboto Flex) and see how the changes for the text (_þΩ_) take place immediately

**Expected results:** 
When a `FontVariation` value changes for the `fontVariations` property, that change should take place over a period of time.

**Actual results:** 
The `fontVariations` changes take place immediately.

<details>
<summary>Code sample</summary>

```dart
import 'dart:math';
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Animated Default Text Style'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _console = '—';

  double getRandomValue(List<double> range) {
    double value = range[0] + Random().nextDouble() * (range[1] - range[0]);
    return value;
  }

  final List<Color> _textColorList = [
    Colors.grey,
    Colors.red,
    Colors.green,
    Colors.blue,
    Colors.yellow,
    Colors.purple,
    Colors.indigo,
    Colors.orange,
  ];
  Color _textColor = Colors.black;
  final List<double> _fontSizeRange = [36.0, 190];
  double _fontSize = 190.0;
  final List<double> _weightRange = [100.0, 1000];
  double _weight = 1000.0;
  final List<double> _widthRange = [25.0, 151];
  double _width = 151.0;
  final List<double> _slantRange = [-10.0, 0.0];
  double _slant = 0.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      backgroundColor: Colors.grey.shade50,
      body: SafeArea(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const SizedBox(
              height: 32.0,
            ),
            Text(
              _console,
              style: const TextStyle(
                fontFamily: 'Menlo',
                fontFamilyFallback: ['monospace'],
              ),
            ),
            Expanded(
              child: Center(
                child: AnimatedDefaultTextStyle(
                  duration: const Duration(seconds: 2),
                  curve: Curves.elasticOut,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontFamily: 'Roboto Flex',
                    color: _textColor,
                    fontSize: _fontSize,
                    fontVariations: [
                      FontVariation('wght', _weight),
                      FontVariation('wdth', _width),
                      FontVariation('slnt', _slant),
                    ],
                  ),
                  child: const Text(
                    'þΩ',
                  ),
                ),
              ),
            ),
            const SizedBox(
              height: 64.0,
            ),
            const Divider(
              thickness: 4,
            ),
            const Text('Animatable properties'),
            Wrap(
              spacing: 16.0,
              alignment: WrapAlignment.center,
              children: [
                ElevatedButton(
                    onPressed: () {
                      setState(() {
                        _textColor = _textColorList[
                            Random().nextInt(_textColorList.length)];
                        _console =
                            'Color: ${_textColor.value.toRadixString(16).toUpperCase()}';
                      });
                    },
                    child: const Text('Color')),
                ElevatedButton(
                    onPressed: () {
                      setState(() {
                        _fontSize = getRandomValue(_fontSizeRange);
                        _console = 'Font size: ${_fontSize.toStringAsFixed(1)}';
                      });
                    },
                    child: const Text('Font size')),
              ],
            ),
            const Divider(
              thickness: 4,
            ),
            const Text('Font variations (non animatable properties)'),
            Wrap(
              spacing: 16.0,
              alignment: WrapAlignment.center,
              children: [
                ElevatedButton(
                    onPressed: () {
                      setState(() {
                        _weight = getRandomValue(_weightRange);
                        _console = 'Weight: ${_weight.toStringAsFixed(1)}';
                      });
                    },
                    child: const Text('Weight (wght)')),
                ElevatedButton(
                    onPressed: () {
                      setState(() {
                        _width = getRandomValue(_widthRange);
                        _console = 'Width: ${_width.toStringAsFixed(1)}';
                      });
                    },
                    child: const Text('Width (wdth)')),
                ElevatedButton(
                    onPressed: () {
                      setState(() {
                        _slant = getRandomValue(_slantRange);
                        _console = 'Slant: ${_slant.toStringAsFixed(1)}';
                      });
                    },
                    child: const Text('Slant (slnt)')),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Demo video</summary>

https://user-images.githubusercontent.com/27135013/171407272-ce815d1e-be49-4a68-b6a6-7ca1371d0e9d.mp4

</details>

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/105120

I also exposed the relevant dart:ui types which had the effect of removing a large number of dart:ui imports from examples.

### CODE REVIEW

**Comment by Hixie** [comment]
https://github.com/flutter/packages/pull/5471 should address the flutter_plugins issue

File: packages/flutter/lib/src/painting/text_style.dart [hunk 1]
```diff
@@ -1567,3 +1577,83 @@ class TextStyle with Diagnosticable {
...
+      break;
+    }
+    result.add(FontVariation.lerp(a[index], b[index], t)!);
+  }
+  final int maxLength = a.length > b.length ? a.length : b.length;
+  if (index < maxLength) {
+    // If we get here, we have found some case where we cannot
+    // use the efficient approach.
+    final Set<String> axes = HashSet<String>();
+    final Map<String, FontVariation> aVariations = HashMap<String, FontVariation>();
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/painting/text_style.dart:1641]: Looking at the spec it looks like currently there're only 5 registered axes. Wouldn't it be faster to use regular element look up in a nested loop (or even sort the 2 lists), than doing the allocations ?

File: packages/flutter/lib/src/painting/text_style.dart [hunk 2]
```diff
@@ -1567,3 +1577,83 @@ class TextStyle with Diagnosticable {
...
+/// made to detect or remove duplicates in this process.
+///
+/// When the order of items in the two input lists vary, the constant factor
+/// increases substantially, as it involves creating two maps and a set,
+/// inserting every variation in both lists into the maps and the set, and then
+/// iterating over them to recreate the list.
+///
+/// In this case, the resulting order is arbitrary. Duplicates are dropped; in
+/// each list, the last [FontVariation] for any particular axis is the one used
+/// to compute the value for that axis. Values that only appear on one side are
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/painting/text_style.dart:1598]: Does it make sense to have a default value for each axis then? Like the weight defaults to 400 if one side is null? Or the developer should always make sure the axis pairs match if the lerp function is used for an animated transition?

File: packages/flutter/lib/src/painting/text_style.dart [hunk 3]
```diff
@@ -812,10 +814,18 @@ class TextStyle with Diagnosticable {
...
   /// ```
-  final List<ui.FontVariation>? fontVariations;
+  ///
+  /// Font variations can be interpolated via [lerp]. This is fastest when the
+  /// same font variation axes are specified, in the same order, in both
+  /// [TextStyle] objects. See [lerpFontVariations].
+  ///
+  /// See also:
+  ///
+  ///  * [fontFeatures], for font variations that discrete values.
```
[the remark this answers is not in the document]
Comment (Hixie) [reply packages/flutter/lib/src/painting/text_style.dart:827]: oops, good catch. fixed.

File: packages/flutter/lib/src/painting/text_style.dart [hunk 4]
```diff
@@ -1567,3 +1577,83 @@ class TextStyle with Diagnosticable {
...
+/// It is fastest when the lists contain the same axes ([FontVariation.axis]) in
+/// the same order. The result is again in the same order, and no attempt is
+/// made to detect or remove duplicates in this process.
+///
+/// When the order of items in the two input lists vary, the constant factor
+/// increases substantially, as it involves creating two maps and a set,
+/// inserting every variation in both lists into the maps and the set, and then
+/// iterating over them to recreate the list.
+///
+/// In this case, the resulting order is arbitrary. Duplicates are dropped; in
```
[the remark this answers is not in the document]
Comment (Hixie) [reply packages/flutter/lib/src/painting/text_style.dart:1596]: If we want to assert on duplicates, that's probably something for the engine side. It would be weird to assert here, since there's nothing about the API today that disallows asserts.

I don't have a strong opinion on whether duplicates should be allowed or not.

File: packages/flutter/lib/src/painting/text_style.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/painting/text_style.dart:1641]: Allocations are very cheap in Dart (it just bumps a pointer on the new generation heap).
I think if we expect this codepath to be used frequently enough that we care about performance, we should probably benchmark the various options, though. I don't know what the optimal path is. (I spent some time trying to figure it out, but nothing obvious came to mind.) In practice, I expect most cases will be either empty on one side and not the other (which has a fast path already), or the same order on both sides (which also has a fast path). There's not much benefit to lerping between two different lists (they would just step-function at t=0.5), and if the lists are the same, then it'd be much better for the values to be sorted by the developer than here.

File: packages/flutter/lib/src/painting/text_style.dart (hunk 2 above)
Comment (Hixie) [reply packages/flutter/lib/src/painting/text_style.dart:1598]: Fonts have a default value, but we have no way to find out what it is (because, for one, we don't know what font is going to be used, and it could be a different font for each character in the string, due to font fallbacks).

If the developer wants to animate something, they'll specify both ends, in practice.

**Review by LongCatIsLooong — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/painting/text_style.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (Hixie) [reply packages/flutter/lib/src/painting/text_style.dart:1591]: yeah that's probably the reason we went with this design

File: packages/flutter/lib/src/painting/text_style.dart (hunk 1 above)
Comment (Hixie) [reply packages/flutter/lib/src/painting/text_style.dart:1636]: yeah it's not trivial (hence the paragraph in the documentation about it). I agree that the constant factors are probably much more important here than the scaling factor. I'll add some more text to that effect to the docs.
