### PR TITLE
fix navigator observer announcement order

### LINKED ISSUE #57407: NavigatorObserver.didPush called in reverse order when using Navigator.initialRoute
Since the `Navigator` refactoring, when using `Navigator.initialRoute`, observers are notified of the initial route components being pushed from the deepest route to the top (`/`), which is the opposite order from what one would expect and from the previous behavior. This breaks any code that updates state depending on the most recent route pushed.

## Steps to Reproduce

1. Run `flutter create navigator-didpush-bug`.
2. Update `main.dart` as follows: 

```
import 'dart:developer';

import 'package:flutter/material.dart';

class MyNavigatorObserver extends NavigatorObserver {
  @override
  void didPush(Route<dynamic> route, Route<dynamic> previousRoute) {
    log('didPush route=${route?.settings?.name} previousRoute=${previousRoute?.settings?.name}');
  }
}

void main() {
  runApp(MaterialApp(
    title: 'Navigator Bug Demo',
    initialRoute: '/second',
    routes: {
      '/': (context) => FirstScreen(),
      '/second': (context) => SecondScreen(),
    },
    navigatorObservers: [ MyNavigatorObserver() ],
  ));
}

class FirstScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Screen'),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Screen"),
      ),
    );
  }
}
```

**Expected results:**

As of Flutter v1.12.13+hotfix.5, and as expected, the observer is notified of the routes pushed in logical order, as if navigating from the top to the tip of the tree, with the last call to `didPush` being for the deepest route:

```
[log] didPush route=/ previousRoute=null
[log] didPush route=/second previousRoute=/
```

**Actual results:**

As of Flutter 1.17.1, the calls are in the wrong (reverse) order, with the last call being for the top-level route:

```
[log] didPush route=/second previousRoute=/
[log] didPush route=/ previousRoute=null
```

<details>

```
[✓] Flutter: is fully installed. (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.3)
[✓] Android Studio: is fully installed. (version 3.5)
[!] IntelliJ IDEA Ultimate Edition: is partially installed; more components are available. (version 2020.1.1)
[✓] Connected device: is fully installed. (1 available)
```

</details>

### PR DESCRIPTION
**Pull request by chunhtai**
## Description

The navigator refactor accidentally changes the contract of navigator observer. If there are multiple route added in one history update (for example adding initial routes), the observer will receive the notifications from top-most route to bottm-most routes. It is the opposite of the order before the navigator observation.

This pr fixes it.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/57407#issuecomment-630384782

## Tests

I added the following tests:

See files

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by chunhtai** [comment]
@goderbauer This is somehow blocking the hero refactor since it touches the navigator observer

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 1]
```diff
@@ -3071,6 +3096,10 @@ class NavigatorState extends State<Navigator> with TickerProviderStateMixin {
       entry = previous;
       previous = index > 0 ? _history[index - 1] : null;
     }
+
+    // Inform navigator observers about route changes.
+    _informObservers();
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:3101]: nit: maybe call this flushObserverNotifications? (similarly to the _flushRouteAnnouncement below).

File: packages/flutter/lib/src/widgets/navigator.dart [hunk 2]
```diff
@@ -2571,10 +2577,30 @@ class _RouteEntry extends RouteTransitionRecord {
   }
 }
 
+enum _ObservedAction {
```
Comment (goderbauer) [inline packages/flutter/lib/src/widgets/navigator.dart:2580]: As an idea: maybe use a polymorphic approach: 

* remove this enum
* have an abstract `void notify(List<Observers> observers)` on _NavigatorObservation
* have subclasses for the various actions that implement the correct notification dispatch for the observation.

That also avoids the big switch below

**Comment by chunhtai** [comment]
ready for another look

**Review by goderbauer — APPROVED** [review]
LGTM
