### PR TITLE
Fix regression with ModalBottomSheets not responding to changes in theme

### LINKED ISSUE #42128: ModalBottomSheet does not pay attention to bottomSheetTheme after ThemeMode changed
## Steps to Reproduce

Here is minimal app which represents a issue: https://gist.github.com/orteney/1698b347d0e9f37a0ea00349babb2f4b

1. Setup MaterialApp with ThemeData with bottomSheetTheme
2. showModalBottomSheet with ThemeMode toggles
3. Toggle from light to dark or vice versa

**Expected**: BottomSheet's change background according to theme.
**Actual**: BottomSheet's background are not repainted.

P.S. Looks like the issue appeared from 1.10.0 version, because on 1.9.7 it's works as expected...

Screenshot_1570472276

## Logs

```
[√] Flutter (Channel dev, v1.10.12, on Microsoft Windows [Version 10.0.18362.388], locale ru-RU)
    • Flutter version 1.10.12 at S:\Soft\Flutter
    • Framework revision 0e605cc4dd (3 days ago), 2019-10-04 07:52:15 -0700
    • Engine revision 759d3dba25
    • Dart version 2.6.0 (build 2.6.0-dev.5.0 7a7dcd1ed9)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at S:\Soft\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: S:\Soft\JetBrains\apps\AndroidStudio\ch-1\192.5871855\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at S:\Soft\JetBrains\apps\AndroidStudio\ch-0\191.5791312
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 3.6)
    • Android Studio at S:\Soft\JetBrains\apps\AndroidStudio\ch-1\192.5871855
    • Flutter plugin version 40.0.3
    • Dart plugin version 192.6262.58
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at S:\Soft\JetBrains\apps\IDEA-C\ch-0\192.6603.28
    • Flutter plugin version 38.1.4
    • Dart plugin version 192.5728.98

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)
```

### PR DESCRIPTION
**Pull request by darrenaustin**
## Description

#39333 introduced a regression where `ModalBottomSheets` no longer responded to changes in the theme after they were shown. The fix was to move the color and elevation theme resolution out of the `showModalBottomSheet` function and into the the widget's build method. That way colors and elevation changes in the theme will be picked up when the widget is rebuilt.

## Related Issues

Fixes: #42128

## Tests

I added a new test that checks that color and elevation changes in the surrounding theme are picked up by the visible modal bottom sheet.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by rami-a — APPROVED** [review]
LGTM

File: packages/flutter/lib/src/material/bottom_sheet.dart [hunk 1]
```diff
@@ -380,15 +380,16 @@ class _ModalBottomSheetRoute<T> extends PopupRoute<T> {
 
   @override
   Widget buildPage(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation) {
+    final BottomSheetThemeData sheetTheme = theme?.bottomSheetTheme ?? Theme.of(context).bottomSheetTheme;
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/bottom_sheet.dart]: Could this be handled with InheritedTheme.captureAll() instead?

Comment (darrenaustin) [reply packages/flutter/lib/src/material/bottom_sheet.dart]: Not sure exactly what you are thinking of here, but `theme` is a passed in parameter that wouldn't necessarily be in a `Theme` widget, so its values wouldn't be seen by `captureAll()`.  Or am I misunderstanding what you suggesting?

Comment (HansMuller) [reply packages/flutter/lib/src/material/bottom_sheet.dart]: What I was suggesting would have required adding a Builder around the new page, so that you could bind a variable to Theme.of(context).bottomSheetTheme, which doesn't seem to be worth trouble. Never mind :-).

**Review by HansMuller — APPROVED** [review]
LGTM
