### PR TITLE
Fix `OutlinedButton`, `TextButton`, and `IconButton`  throw exception when passing only one cursor to `styleFrom`

### LINKED ISSUE #118071: The OutlinedButton mouse cursor code would throw exception if only one is given
The `OutlinedButton.styleFrom` is declared as:

https://github.com/flutter/flutter/blob/ccfd14b05f4d6e64871ba5309517a7fd26f2968d/packages/flutter/lib/src/material/outlined_button.dart#L142-L175

where `disabledMouseCursor` and `enabledMouseCursor` are nullable, and have no restriction around it.

But later it is used as:

https://github.com/flutter/flutter/blob/ccfd14b05f4d6e64871ba5309517a7fd26f2968d/packages/flutter/lib/src/material/outlined_button.dart#L189-L191

Both has `!` but the condition only excluded the case that both values are `null`. 

So if only one value is given, the code gonna throw.

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/118071

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/material/text_button.dart [hunk 1]
```diff
@@ -200,9 +200,9 @@ class TextButton extends ButtonStyleButton {
       : disabledIconColor == null
         ? ButtonStyleButton.allOrNull<Color?>(iconColor)
         : _TextButtonDefaultIconColor(iconColor, disabledIconColor);
-    final MaterialStateProperty<MouseCursor>? mouseCursor = (enabledMouseCursor == null && disabledMouseCursor == null)
+    final MaterialStateProperty<MouseCursor?>? mouseCursor = (enabledMouseCursor == null && disabledMouseCursor == null)
```
Comment (HansMuller) [inline packages/flutter/lib/src/material/text_button.dart:203]: This fix looks fine however maybe it would be sufficient to just have
```dart
final MaterialStateProperty<MouseCursor?> = _TextButtonDefaultMouseCursor(enabledMouseCursor, disabledMouseCursor);
```
This extra special case doesn't seem to be worth the trouble.

Comment (TahaTesser) [reply packages/flutter/lib/src/material/text_button.dart:203]: Right! I totally missed that. Thank you

Comment (TahaTesser) [reply packages/flutter/lib/src/material/text_button.dart]: For the sake of consistency, I've also this line other material buttons. For bother buttons it's just a code restructure.

**Review by HansMuller — APPROVED** [review]
Thanks for spreading the fix around; this looks great.

LGTM

File: packages/flutter/test/material/outlined_button_test.dart [hunk 2]
```diff
@@ -1947,6 +1947,24 @@ void main() {
     expect(controller.value, <MaterialState>{MaterialState.disabled});
     expect(count, 1);
   });
+
+  testWidgets("OutlinedButton.styleFrom doesn't throw exception on passing only one cursor", (WidgetTester tester) async {
+    // This is a regression test for https://github.com/flutter/flutter/issues/118071.
+    await tester.pumpWidget(
+      Directionality(
```
Comment (QuncCccccc) [inline packages/flutter/test/material/outlined_button_test.dart:1954]: nit: maybe we don't need to specify the Directionality here?

**Review by QuncCccccc — APPROVED** [review]
Nice fix! Thanks a lot!

Also noticed that the `IconButton` has the same problem. Do you mind to add one more fix for IconButton? Or I can add it later after this PR:)

File: packages/flutter/test/material/outlined_button_test.dart (hunk 2 above)
Comment (TahaTesser) [reply packages/flutter/test/material/outlined_button_test.dart:1954]: This is required for `_InkResponseStateWidget` 
```consple
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: null
  Actual: FlutterError:<No Directionality widget found.
          _InkResponseStateWidget widgets require a Directionality widget ancestor.
          The specific widget that could not find a Directionality ancestor was:
            _InkResponseStateWidget
          The ownership chain for the affected widget is: "_InkResponseStateWidget ← InkWell ←
DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#df43a ink renderer] ←
NotificationListener<LayoutChangedNotification> ← CustomPaint ← _ShapeBorderPaint ← PhysicalShape ←
_MaterialInterior ← ⋯"
          Typically, the Directionality widget is introduced by the MaterialApp or WidgetsApp widget
at the top of your application widget tree. It determines the ambient reading direction and is used,
for example, to determine how to lay out text, how to interpret "start" and "end" values, and to
resolve EdgeInsetsDirectional, AlignmentDirectional, and other *Directional objects.>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/tahatesser/Code/flutter/packages/flutter/test/material/outlined_button_test.dart:1963:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/tahatesser/Code/flutter/packages/flutter/test/material/outlined_button_test.dart line 1963
The test description was:
  OutlinedButton.styleFrom doesn't throw exception on passing only one cursor
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: OutlinedButton.styleFrom doesn't throw exception on passing only one cursor

✖ OutlinedButton.styleFrom doesn't throw exception on passing only one cursor

```

Comment (TahaTesser) [reply packages/flutter/test/material/outlined_button_test.dart:1954]: @QuncCccccc 
Just Fixed `IconButton` and added a new test to check exceptions. Please take a look.

**Comment by TahaTesser** [comment]
This is unrelated to PR but I just noticed an empty code exists in the `icon_button_test.dart` class, while adding a test for my fix.

https://github.com/flutter/flutter/blob/3b4ac4d5cc59344170833b93a968ace003f184f0/packages/flutter/test/material/icon_button_test.dart#L2482-L2484

File: packages/flutter/lib/src/material/icon_button.dart [hunk 3]
```diff
@@ -638,9 +638,7 @@ class IconButton extends StatelessWidget {
     final MaterialStateProperty<Color?>? overlayColor = (foregroundColor == null && hoverColor == null && focusColor == null && highlightColor == null)
         ? null
         : _IconButtonDefaultOverlay(foregroundColor, focusColor, hoverColor, highlightColor);
-    final MaterialStateProperty<MouseCursor>? mouseCursor = (enabledMouseCursor == null && disabledMouseCursor == null)
-        ? null
-        : _IconButtonDefaultMouseCursor(enabledMouseCursor!, disabledMouseCursor!);
+    final MaterialStateProperty<MouseCursor?> mouseCursor = _IconButtonDefaultMouseCursor(enabledMouseCursor!, disabledMouseCursor!);
```
Comment (QuncCccccc) [inline packages/flutter/lib/src/material/icon_button.dart:641]: Should we remove `!` here? because enabledMouseCursor and disabledMouseCursor are nullable.

File: packages/flutter/test/material/outlined_button_test.dart (hunk 2 above)
Comment (QuncCccccc) [reply packages/flutter/test/material/outlined_button_test.dart:1954]: Ah that‘s right. Thanks for the explanation!

File: packages/flutter/lib/src/material/icon_button.dart (hunk 3 above)
Comment (TahaTesser) [reply packages/flutter/lib/src/material/icon_button.dart:641]: oops

**Review by QuncCccccc — APPROVED** [review]
LGTM:)
