### PR TITLE
Started querying the app state for the gpu disabled sync switch

### LINKED ISSUE #166668: [Google3 Bug]: iOS, Images replaced with pink fill when coming out of background
### Help us understand the severity of this issue

- [x] causing severe production issues e.g. malfunctions or data loss
- [ ] blocking next binary release
- [ ] blocking a client feature launch within a quarter
- [ ] nice-to-have but does not block a launch within the next quarter

### Steps to reproduce

b/408379305

This is the same issue as https://github.com/flutter/flutter/issues/126878. So far, we've reproduced it on iPhone 15 Pro and iPhone 12 mini, not reproduced on iPhone 13 and SE. 

1. Background or kill the app
2. Trigger a notification to be sent to the app
3. Reopen the app from the notification

### Expected results

Images are displayed as usual.

### Actual results

Images are all replaced with a pink fill.

### Code sample

Not adding a minimal repro, as this bug has been previously investigated in https://github.com/flutter/flutter/issues/126878.

### Screenshots or Video

Image

### Logs

_No response_

### Flutter Doctor output

Could not reproduce in a dev environment yet.

### PR DESCRIPTION
**Pull request by gaaclarke**
Started querying the app state for the gpu disabled sync switch when starting an engine without a view controller

fixes https://github.com/flutter/flutter/issues/166668

Testing: Integration test is not possible since it would require manipulation of the operating system and killing / restoring the app.  Unit tests would require executing in the background or mocking out background detection which is pretty contrived and will complicate engine initialization.  The simple cases will be covered with integration tests like the wide gamut devicelab tests which loads an image at startup and grabs a screenshot of it.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by gaaclarke** [comment]
This PR was tested manually with the following setup.  The issue doesn't have reproduction code so I'm not sure this covers all cases:

Steps:
1) Launch the app (profile or release)
1) Background the app
1) Kill the app
1) Click on the notification to relaunch the app
1) Verify the image is not magenta

I can't reproduce the original bug.  I've tried variations where I lock the screen too as suggested in https://github.com/flutter/flutter/issues/166668#issuecomment-2929043496 but I can't get it.  According to https://github.com/flutter/flutter/issues/166668#issuecomment-2938562297 the problem is non-deterministic though.

```swift
import Flutter
import UIKit
import UserNotifications
import OSLog

@main
@objc class AppDelegate: FlutterAppDelegate, FlutterPluginRegistrant {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    pluginRegistrant = self
    UNUserNotificationCenter.current().delegate = self
    UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .badge, .sound]) { (granted, error) in
        if granted {
            print("Notification permission granted.")
        } else {
            print("Notification permission denied.")
        }
    }
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  override func applicationDidEnterBackground(_ application: UIApplication) {
    let content = UNMutableNotificationContent()
    content.title = "Counter App"
    content.body = "You have been away for 10 seconds."
    content.sound = UNNotificationSound.default

    let trigger = UNTimeIntervalNotificationTrigger(timeInterval: 10, repeats: false)
    let request = UNNotificationRequest(identifier: "backgroundNotification", content: content, trigger: trigger)

    UNUserNotificationCenter.current().add(request) { (error) in
        if let error = error {
            print("Error scheduling notification: \(error)")
        }
    }
  }

  override func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
    completionHandler([.alert, .badge, .sound])
  }

  func register(with registry: any FlutterPluginRegistry) {
    GeneratedPluginRegistrant.register(with: registry)
  }
}
```

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm [hunk 1]
```diff
@@ -848,7 +848,11 @@ - (BOOL)createShell:(NSString*)entrypoint
   );
 
   // Disable GPU if the app or scene is running in the background.
-  self.isGpuDisabled = self.viewController.stateIsBackground;
+  self.isGpuDisabled = self.viewController
+                           ? self.viewController.stateIsBackground
+                           : FlutterSharedApplication.application &&
+                                 FlutterSharedApplication.application.applicationState ==
+                                     UIApplicationStateBackground;
```
Comment (gaaclarke) [inline engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm:855]: Maintains existing behavior for app extensions.

**Comment by mraleph** [comment]
I actually managed to reproduce this today, after struggling through different variations yesterday. The key here is that the app (at least on iOS26 which I have installed on both available to me iOS devices) even when started in background due to notification arriving seems to _initially_ have GPU access but then looses it after some delay. So any tests which submit GPU work fast enough will actually succeed. 

<details>
<summary>Device log with some additional debug printing added
</summary>

```
error	09:21:00.286984+0200	Runner	[IMPORTANT:flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm(852)] self.viewController is nil: true)
error	09:21:00.287022+0200	Runner	[IMPORTANT:flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm(854)] is_background = false
error	09:21:00.287046+0200	Runner	[IMPORTANT:flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm(856)] self.isGpuDisabled = false
error	09:21:00.287067+0200	Runner	[IMPORTANT:flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm(857)] _isGpuDisabled = false
error	09:21:00.290009+0200	Runner	[IMPORTANT:flutter/shell/common/shell.cc(484)] Shell(0x10253de00) is created: is_gpu_disabled=false
error	09:21:00.308737+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(104)] ImageDecoderImpeller
error	09:21:00.310656+0200	Runner	[IMPORTANT:flutter/shell/common/shell.cc(2277)] Shell::SetGpuAvailability(kAvailable)
default	09:21:00.321254+0200	Runner	didFinishLaunchingWithOptions
default	09:21:00.329514+0200	Runner	Notification permissions granted.
error	09:21:00.347043+0200	Runner	application.applicationState: BACKGROUND
error	09:21:00.352838+0200	Runner	application.applicationState: BACKGROUND
default	09:21:14.537918+0200	Runner	From Flutter: main start
default	09:21:14.540038+0200	Runner	From Flutter: after sleep
default	09:21:14.540108+0200	Runner	From Flutter: main
error	09:21:14.584093+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(450)] GPU IS ENABLED: uploading
error	09:21:14.584254+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(450)] GPU IS ENABLED: uploading
error	09:21:14.584322+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(314)] UnsafeUploadTextureToPrivate
error	09:21:14.584374+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(314)] UnsafeUploadTextureToPrivate
error	09:21:14.586091+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(450)] GPU IS ENABLED: uploading
error	09:21:14.586180+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(314)] UnsafeUploadTextureToPrivate
error	09:21:14.589119+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(450)] GPU IS ENABLED: uploading
error	09:21:14.589180+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(314)] UnsafeUploadTextureToPrivate
error	09:21:14.590120+0200	Runner	[ERROR:flutter/impeller/renderer/backend/metal/command_buffer_mtl.mm(113)] Impeller validation: >>>>>>>
Impeller command buffer could not be committed!
Insufficient Permission (to submit GPU work from background) (00000006:kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted)
Domain: MTLCommandBufferErrorDomain Code: not permitted
<<<<<<<
error	09:21:14.590229+0200	Runner	[ERROR:flutter/lib/ui/painting/image_decoder_impeller.cc(403)] GPU Error submitting image decoding command buffer.
error	09:21:14.590557+0200	Runner	[ERROR:flutter/impeller/renderer/backend/metal/command_buffer_mtl.mm(113)] Impeller validation: >>>>>>>
Impeller command buffer could not be committed!
Insufficient Permission (to submit GPU work from background) (00000006:kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted)
Domain: MTLCommandBufferErrorDomain Code: not permitted
<<<<<<<
error	09:21:14.590682+0200	Runner	[ERROR:flutter/lib/ui/painting/image_decoder_impeller.cc(403)] GPU Error submitting image decoding command buffer.
error	09:21:14.590842+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(450)] GPU IS ENABLED: uploading
error	09:21:14.590897+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(314)] UnsafeUploadTextureToPrivate
error	09:21:14.591265+0200	Runner	[ERROR:flutter/impeller/renderer/backend/metal/command_buffer_mtl.mm(113)] Impeller validation: >>>>>>>
Impeller command buffer could not be committed!
Insufficient Permission (to submit GPU work from background) (00000006:kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted)
Domain: MTLCommandBufferErrorDomain Code: not permitted
<<<<<<<
error	09:21:14.591329+0200	Runner	[ERROR:flutter/lib/ui/painting/image_decoder_impeller.cc(403)] GPU Error submitting image decoding command buffer.
error	09:21:14.591761+0200	Runner	[ERROR:flutter/impeller/renderer/backend/metal/command_buffer_mtl.mm(113)] Impeller validation: >>>>>>>
Impeller command buffer could not be committed!
Insufficient Permission (to submit GPU work from background) (00000006:kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted)
Domain: MTLCommandBufferErrorDomain Code: not permitted
<<<<<<<
error	09:21:14.591819+0200	Runner	[ERROR:flutter/lib/ui/painting/image_decoder_impeller.cc(403)] GPU Error submitting image decoding command buffer.
error	09:21:14.592096+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(450)] GPU IS ENABLED: uploading
error	09:21:14.592189+0200	Runner	[IMPORTANT:flutter/lib/ui/painting/image_decoder_impeller.cc(314)] UnsafeUploadTextureToPrivate
error	09:21:14.592294+0200	Runner	[ERROR:flutter/impeller/renderer/backend/metal/command_buffer_mtl.mm(113)] Impeller validation: >>>>>>>
Impeller command buffer could not be committed!
Insufficient Permission (to submit GPU work from background) (00000006:kIOGPUCommandBufferCallbackErrorBackgroundExecutionNotPermitted)
Domain: MTLCommandBufferErrorDomain Code: not permitted
<<<<<<<
error	09:21:14.592354+0200	Runner	[ERROR:flutter/lib/ui/painting/image_decoder_impeller.cc(403)] GPU Error submitting image decoding command buffer.

```

</details>

Here is the setup that eventually allowed me to reproduce it:

* Make an iOS app which can receive background notifications. In Signing & Capabilities give the app **Background fetch**, **Background processing** and **Remote notifications** in **Background Modes** as well as **Push notifications**. Follow official Apple guidelines:
  * [Asking permission to use notifications](https://developer.apple.com/documentation/usernotifications/asking-permission-to-use-notifications)
  * [Registering your app with APNs](https://developer.apple.com/documentation/usernotifications/registering-your-app-with-apns)
  * [Pushing background updates to your App](https://developer.apple.com/documentation/usernotifications/pushing-background-updates-to-your-app)
* Add a bunch of logging using `os_log`, so that it is easy to see in the `Console` in real time when things go south.
* Make a simple app which just shows 11 simple PNG images in a column
* **IMPORTANT**: put a 1 second delay in `main` using `dart:io` `sleep`

```dart
void main() {
  sleep(const Duration(seconds: 1));
  runApp(
    Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          for (var i = 0; i <= 10; i++)
            Image(image: AssetImage('assets/icon$i.png')),
        ],
      ),
    ),
  );
}
```

Once you have the app, you do the following:

- Run `Console` on the side and start streaming device logs.
- Build and run the app on real device in release mode. Remember device token (which you get in `application(_:didRegisterForRemoteNotificationsWithDeviceToken:)` after you call `registerForRemoteNotifications`). You will need this token to send notifications to the app using [Push Notification Console](https://developer.apple.com/documentation/usernotifications/testing-notifications-using-the-push-notification-console).
- Move away from the app and kill it using App Switcher. If you are building custom engine you can add `os_log` to `Shell::~Shell` and make sure that the app is dead (you will see log in `Console`).
- Send notification to the app. **Important**: it must be _background_ notification (i.e. `{"aps":{"content-available": 1}, ...}`). If it not a background notification (e.g. the one that presents a badge) the app is not woken up by the OS until you click on the notification banner itself (at least that what I see in the logs).

That's it: if you have enough logging you will see in `Console` that the app starts, initializes Flutter engine with incorrect value for `is_gpu_disabled`, runs Dart `main` and starts submitting GPU work. If you don't have `sleep` in `main` it will actually succeed to submit all the work and all will be great. But with `sleep` some of those tasks will actually fail and reproduce our elusive bug. 

I have tested this code and it seems to do the trick. Now we correctly detect that we are running in background.

File: engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm (hunk 1 above)
Comment (vashworth) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm:855]: In app extensions, the `FlutterSharedApplication.application` is unavailable and you have to use the Scene instead. Should this attempt to use the Scene if the application is unavailable?

https://github.com/flutter/flutter/blob/43657f3baa17bc1df6cc15da8b0fea2290c2c4fd/engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L765

Comment (gaaclarke) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm:855]: > In app extensions, the `FlutterSharedApplication.application` is unavailable and you have to use the Scene instead. Should this attempt to use the Scene if the application is unavailable?

It does check for the scene in `self.viewController.stateIsBackground`.  So the question is really, "Can you have an app extension that is in a background state with an engine that doesn't have an associated view controller, which needs GPU access?"  For that situation we can say for this PR that we do whatever we used to do, there is no change.  I don't know if that situation is practical or possible.  For example, I know memory requirements for app extensions is tight so you may not even be able to fit a second engine.

Comment (mraleph) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm:855]: Here is a question: is there actually a code path to this code which sets `viewController`? I am trying to figure this out by looking at the code and I can't - I am starting to suspect it is always `nil` and can't be used at this point

e.g. `ShareViewController` calls `[engine run]` (which calls `createShell`) before it calls `[self initWithEngine:...]` which sets `viewController`.

Comment (gaaclarke) [reply engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm:855]: > Here is a question: is there actually a code path to this code which sets `viewController`?

These API's are hard to reason about because they are public.  Anyone could be doing anything with them (eg add-to-app).  For the simple case of loading a FlutterViewController from a storyboard, it looks like the view controller will be nil: https://github.com/flutter/flutter/blob/94265c52b38f8c3d11be52a42c02b9996588b9a6/engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L817

The FlutterViewController can be created before the FlutterEngine ( https://github.com/flutter/flutter/blob/94265c52b38f8c3d11be52a42c02b9996588b9a6/engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L250 ), but there is nothing that forces that.

What that means to me is that it's safest to construct the PR like this so we don't break any add-to-app cases and we have a workaround for people if it becomes problematic.  For app extensions, I'm skeptical that app extensions can be initialized while an app is in the background.  I think the more prudent thing is to keep the existing behavior for that.

**Review by vashworth — APPROVED** [review]
LGTM

**Comment by jtmcdole** [comment]
Is there a way to generate a notification for iOS through tooling and if so, should we add a test to the device lab to make sure we don't regress?

**Comment by gaaclarke** [comment]
> Is there a way to generate a notification for iOS through tooling and if so, should we add a test to the device lab to make sure we don't regress?

I don't think we have a mechanism that can kill processes.  In our reproduction we are using the app switcher to kill the process.

**Comment by mraleph** [comment]
Regarding automatically testing this... We should be able to terminate the app via the debugger connection or via test automation e.g. [XCUIApplication.terminate()](https://developer.apple.com/documentation/xctest/xcuiapplication/terminate()) - I don't think that's the hardest part. 

I think setting up notifications is probably more challenging infrastructurally (because it requires APN authentication, these secrets need to be stored somewhere). Maybe setting up using background tasks is more viable.

**Comment by gaaclarke** [comment]
> I think setting up notifications is probably more challenging infrastructurally (because it requires APN authentication, these secrets need to be stored somewhere). Maybe setting up using background tasks is more viable.

My reproduction attempts used local notifications which doesn't require any authentication.  Even if you did get them, how would you click on them to relaunch the app though and get a connection to the new process in order to grab the screenshot.

**Comment by mraleph** [comment]
I am not sure local notifications (those you click on) would do that - AFAIK they don't start the app in background, but in foreground. It is prerequisite for the reproduction that the app must be completely dead and it should start from scratch in background. 

I also think we can probably avoid screenshotting. Just kick off decoding of images into `ui.Image` and listen for errors - there should be none.
