### PR TITLE
[native_assets] Find more `CCompilerConfig` on Linux

### LINKED ISSUE #175311: C Compiler dependencies for `code_assets` cannot always be found on all Linux systems in current implementation
> I just created this issue so I can link to it in an upcoming PR. I am working on a fix for this locally.

### Steps to reproduce

Try to build a package utilizing native code assets on a Linux system where `clang`, `llvm-ar`, or `ld.lld` are not beside `clang++` in the same directory.

### Expected results

Flutter build tool should be able to find these executables.

### Actual results

`flutter` tool throws an error when attempting to build.

### Logs

<details>

<summary>Logs</summary>

```console
ERROR: Failed to find llvm-ar relative to LocalFile: '/nix/store/v79bl5xhqjh0r5518gihcykx2861imd3-clang-wrapper-20.1.6/bin/clang++': LocalFile: '/nix/store/v79bl5xhqjh0r5518gihcykx2861imd3-clang-wrapper-20.1.6/bin/llvm-ar' doesn't exist.
```

</details>

### PR DESCRIPTION
**Pull request by GregoryConrad**
Sometimes the necessary binaries `code_assets` expects alongside `clang++` have differing names than the current code expects (e.g., `ld` instead of `ld.lld`) on Linux. This change is necessary on some systems with atypical installs, such as NixOS.

These binaries are gathered by the flutter tool and are eventually sent to the build hook for native code assets as the `CCompilerConfig`.

Note that the only other reference to `clang`/`clang++` in the linux build system is where it is used to invoke `cmake`, where they are set as the values of the `CC`/`CXX` environment variables.

Fixes #175311

CC @dcharkes, this is take two of #175312

> This PR also fixes my CI using only the `llvmPackages_20.clangUseLLVM` Nix package, for reference

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: packages/flutter_tools/lib/src/isolated/native_assets/linux/native_assets.dart [hunk 1]
```diff
@@ -14,9 +14,9 @@ import '../../../globals.dart' as globals;
 /// Search for the accompanying `clang`, `ar`, and `ld`.
 Future<CCompilerConfig> cCompilerConfigLinux() async {
   const kClangPlusPlusBinary = 'clang++';
-  const kClangBinary = 'clang';
-  const kArBinary = 'llvm-ar';
-  const kLdBinary = 'ld.lld';
+  const kClangBinaryOptions = ['clang'];
+  const kArBinaryOptions = ['llvm-ar', 'ar'];
```
Comment (dcharkes) [inline packages/flutter_tools/lib/src/isolated/native_assets/linux/native_assets.dart:20]: Maybe add comments what is the default name, and where the alternative names occur.

**Review by dcharkes — APPROVED** [review]
> Sometimes the necessary `code_assets` binaries alongside `clang++` have differing names than the current code expects.

Nit: Maybe be explicit about "`CCompilerConfig` binaries in `package:code_assets` passed into build hooks". (The flutter tools passes in the config, but the code assets package defines what the possible config is.)

(Also the PR title could be something like [native_assets] Find more `CCompilerConfig` on Linux.)

> This change is necessary on some systems with atypical installs, such as NixOS.

Maybe repeat precisely what is different. The explicit executable names.

> This PR also fixes my CI using only the `llvmPackages_20.clangUseLLVM` Nix package, for reference

Sweet! 👍 

One question that should be answered in the PR description is:

* Where in flutter tools is clang used? And does flutter tools use only clang or does it also use ld and ar? And if so, is it consistent in all places. (I think it's basically only clang and clang++ from PATH: packages/flutter_tools/lib/src/linux/build_linux.dart.)

Maybe add comments there and here to say that these should be kept consistent.

**Review by bkonyi — APPROVED** [review]

File: packages/flutter_tools/lib/src/isolated/native_assets/linux/native_assets.dart (hunk 1 above)
Comment (GregoryConrad) [reply packages/flutter_tools/lib/src/isolated/native_assets/linux/native_assets.dart:20]: I:  
- Updated PR title
- Updated PR description
- Added code comment here to address concern

@dcharkes @bkonyi can I please get a re-review (and if all looks good, queue this to merge?)

**Comment by dcharkes** [comment]
> One question that should be answered in the PR description is:
> 
> * Where in flutter tools is clang used? And does flutter tools use only clang or does it also use ld and ar? And if so, is it consistent in all places. (I think it's basically only clang and clang++ from PATH: packages/flutter_tools/lib/src/linux/build_linux.dart.)
> 
> Maybe add comments there and here to say that these should be kept consistent.

**Review by dcharkes — APPROVED** [review]
LGTM once the comment of how `flutter_tools` uses `clang` and friends outside of native assets is answered and cross-linked with comments so that it stays consistent.

**Comment by GregoryConrad** [comment]
> LGTM once the comment of how `flutter_tools` uses `clang` and friends outside of native assets is answered and cross-linked with comments so that it stays consistent.

Ahh, gotcha now--will add another commit for that later today/tomorrow

**Comment by GregoryConrad** [comment]
@dcharkes the only relevant reference I could find to building with `clang`/`clang++` was in the file you mentioned, but the reference is just here where `CC`/`CXX` environment variable are set to `clang`/`clang++`:

https://github.com/flutter/flutter/blob/2d20356c2a21254d7b333c8b177efc17df173e2d/packages/flutter_tools/lib/src/linux/build_linux.dart#L170-L190

That doesn't _seem_ like it needs a comment linking it to where it's used in Native Assets, as it won't get out of sync? Also didn't see any references to `ld` or `ar` at first glance (for Linux).
