### PR TITLE
Teach flutter tools to find gradle

### LINKED ISSUE #8131: Flutter tool should be able to tell me if I don't have gradle installed
Following the guide for setting Flutter up on a linux laptop, I get the following error without gradle installed.

It would be nice to get a pointer on how to set it up, similar to what we do with the Android SDK.  From what I can see, the extra step is reasonably simple -- add `{AndroidStudio install dir}/gradle/gradle-2.14.1/bin/` to the PATH.

Error below:
➜  flutter urn
Launching lib/main.dart on Nexus 5X in debug mode...
Exception from flutter run: Exception: Unable to locate gradle. Please configure the path to gradle using 'flutter config --gradle-dir'.
package:flutter_tools/src/base/common.dart 29              throwToolExit
package:flutter_tools/src/android/gradle.dart 141          ensureGradlew.<async>
===== asynchronous gap ===========================
dart:async                                                 _Completer.completeError
package:flutter_tools/src/android/gradle.dart 184          ensureGradlew.<async>
===== asynchronous gap ===========================
dart:async                                                 Future.Future.microtask
package:flutter_tools/src/android/gradle.dart              ensureGradlew
package:flutter_tools/src/android/gradle.dart 202          buildGradleProject.<async>
===== asynchronous gap ===========================
dart:async                                                 Future.Future.microtask
package:flutter_tools/src/android/gradle.dart              buildGradleProject
package:flutter_tools/src/commands/build_apk.dart 610      buildAndroidWithGradle.<async>
===== asynchronous gap ===========================
dart:async                                                 Future.Future.microtask
package:flutter_tools/src/commands/build_apk.dart          buildAndroidWithGradle
package:flutter_tools/src/commands/build_apk.dart 620      buildApk.<async>
===== asynchronous gap ===========================
dart:async                                                 Future.Future.microtask
package:flutter_tools/src/commands/build_apk.dart          buildApk
package:flutter_tools/src/android/android_device.dart 287  AndroidDevice.startApp.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 113            runCommandAndStreamOutput.<async>
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_tools/src/android/android_device.dart      AndroidDevice.startApp
package:flutter_tools/src/run_hot.dart 160                 HotRunner._run.<async>
dart:async                                                 _SyncCompleter.complete
package:flutter_tools/src/resident_runner.dart 184         ResidentRunner.startEchoingDeviceLog.<async>
===== asynchronous gap ===========================
dart:async                                                 _asyncThenWrapperHelper
package:flutter_tools/src/run_hot.dart                     HotRunner._run
package:flutter_tools/src/run_hot.dart 77                  HotRunner.run.<fn>
package:stack_trace                                        Chain.capture
package:flutter_tools/src/run_hot.dart 76                  HotRunner.run
package:flutter_tools/src/commands/run.dart 278            RunCommand.runCommand.<async>

^C

### PR DESCRIPTION
**Pull request by jakobr-google**
Flutter tools will now use Gradle from Android Studio, which is now found automatically.

`flutter doctor` will verify that Android Studio has been installed, and that the included Gradle is at least version 2.14.1.

It is still possible to manually configure the path to Android Studio (`flutter config --android-studio-dir=XXX`) or Gradle (`flutter config --gradle-dir=XXX`), but this *should* only be necessary if they're installed somewhere non-standard.

Only tested on Linux and macOS for now.

Fixes #8131

### CODE REVIEW

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 1]
```diff
@@ -0,0 +1,255 @@
...
+// $STUDIO_HOME/gradle/gradle-X.Y.Z/bin/gradle
+
+final Version minGradleVersion = new Version(2, 14, 1);
+
+/// Locate Gradle.
+String get gradleExecutable {
+  // See if the user has explicitly configured gradle-dir.
+  String gradleDir = config.getValue('gradle-dir');
+  if (gradleDir != null) {
+    if (fs.isFileSync(gradleDir)) return gradleDir;
```
Comment (abarth) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: Our goofy Dart style guide requires a newline before `return`

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 2]
```diff
@@ -0,0 +1,255 @@
...
+  bool get isValid => _isValid;
+
+  List<String> get validationMessages => _validationMessages;
+
+  @override
+  int compareTo(AndroidStudio other) {
+    int result = version.compareTo(other.version);
+    if (result == 0) {
+      return directory.compareTo(other.directory);
+    }
```
Comment (abarth) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: No `{` for single-line if statements.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 3]
```diff
@@ -0,0 +1,255 @@
...
+    return result;
+  }
+
+  /// Locates the newest, valid version of Android Studio.
+  static AndroidStudio latestValid() {
+    String cfgStudio = config.getValue('android-studio-dir');
```
Comment (abarth) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: cfg -> configured?   please use complete words in variable names.

**Comment by abarth** [comment]
LGTM

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 1 above)
Comment (jakobr-google) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: Which doesn't really make sense, given that you also have the 'no braces for single-line if statements' rule. Together, those make the code less readable, at least to me.

But seriously, isn't it time to ditch the Special Snowflake style rules, and just embrace dartfmt? Makes life so much simpler! ;)

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 3 above)
Comment (jakobr-google) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: Done.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 4]
```diff
@@ -0,0 +1,257 @@
...
+import '../base/common.dart';
+import '../base/context.dart';
+import '../base/file_system.dart';
+import '../base/os.dart';
+import '../base/platform.dart';
+import '../base/process_manager.dart';
+import '../globals.dart';
+import '../ios/plist_utils.dart';
+
+AndroidStudio get androidStudio =>
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: no line break in statements that use =>. Either put it on one line or put it in a block with a wrapped return statement.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 5]
```diff
@@ -0,0 +1,257 @@
...
+  if (gradleDir != null) {
+    if (fs.isFileSync(gradleDir))
+      return gradleDir;
+    return fs.path.join(gradleDir, 'bin', 'gradle');
+  }
+  return androidStudio?.gradleExecutable ?? os.which('gradle')?.path;
+}
+
+class AndroidStudio implements Comparable<AndroidStudio> {
+  AndroidStudio(this.directory, {this.version = '0.0', this.configured}) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: flutter style requires spaces around named argument declarations

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 6]
```diff
@@ -0,0 +1,257 @@
...
+
+  factory AndroidStudio.fromHomeDot(Directory homeDotDir) {
+    String version = homeDotDir.basename.substring('.AndroidStudio'.length);
+    String installPath;
+    try {
+      installPath = fs
+          .file(fs.path.join(homeDotDir.path, 'system', '.home'))
+          .readAsStringSync();
+    } catch (e) {
+      // ignored
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: what error specifically are we ignoring here? We shouldn't blank-ignore all errors, only the harmless ones we know we're expecting.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 7]
```diff
@@ -0,0 +1,257 @@
...
+    }
+    if (installPath != null && fs.isDirectorySync(installPath)) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: braces

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 8]
```diff
@@ -0,0 +1,257 @@
...
+      String configuredStudioPath = configuredStudio;
+      if (os.isMacOS && !configuredStudioPath.endsWith('Contents'))
+        configuredStudioPath = fs.path.join(configuredStudioPath, 'Contents');
+      return new AndroidStudio(configuredStudioPath,
+          configured: configuredStudio);
+    }
+
+    // Find all available Studio installations.
+    List<AndroidStudio> studios = allInstalled();
+    if (studios.isEmpty) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: no braces

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 9]
```diff
@@ -0,0 +1,257 @@
...
+      return null;
+    }
+    studios.sort();
+    return studios.lastWhere((AndroidStudio s) => s.isValid,
+        orElse: () => null);
+  }
+
+  static List<AndroidStudio> allInstalled() =>
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: no newline in =>

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 10]
```diff
@@ -0,0 +1,257 @@
...
+      }
+    }
+
+    _checkForStudio('/Applications');
+    _checkForStudio(fs.path.join(homeDirPath, 'Applications'));
+
+    String configuredStudioDir = config.getValue('android-studio-dir');
+    if (configuredStudioDir != null) {
+      FileSystemEntity configuredStudio = fs.file(configuredStudioDir);
+      if (configuredStudio.basename == 'Contents') {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: braces

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 11]
```diff
@@ -0,0 +1,257 @@
...
+        configuredStudio = configuredStudio.parent;
+      }
+      if (!candidatePaths
+          .any((FileSystemEntity e) => e.path == configuredStudio.path)) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: your vertical alignment of the `.` is weird. I'd probably just put this all on one line, or wrap after the `any(` and before the matching `)` to make the structure clearer.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 12]
```diff
@@ -0,0 +1,257 @@
...
+        candidatePaths.add(configuredStudio);
+      }
+    }
+
+    return candidatePaths
+        .map((FileSystemEntity e) => new AndroidStudio.fromMacOSBundle(e.path))
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: similar here, your vertical alignment for the `.`s are off.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 13]
```diff
@@ -0,0 +1,257 @@
...
+        .toList();
+  }
+
+  static List<AndroidStudio> _allLinuxOrWindows() {
+    List<AndroidStudio> studios = <AndroidStudio>[];
+
+    bool _hasStudioAt(String path, {String newerThan}) {
+      return studios.any((AndroidStudio studio) {
+        if (studio.directory != path) return false;
+        if (newerThan != null) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: braces

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 14]
```diff
@@ -0,0 +1,257 @@
...
+
+    // Read all $HOME/AndroidStudio*/system/.home files. There may be several
+    // pointing to the same installation, so we grab only the latest one.
+    for (FileSystemEntity entity in fs.directory(homeDirPath).listSync()) {
+      if (entity is Directory && entity.basename.startsWith('.AndroidStudio')) {
+        AndroidStudio studio = new AndroidStudio.fromHomeDot(entity);
+        if (studio != null &&
+            !_hasStudioAt(studio.directory, newerThan: studio.version)) {
+          studios.removeWhere(
+              (AndroidStudio other) => other.directory == studio.directory);
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: if you put a line break after a `(`, there should be a matching one after the `)`.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 15]
```diff
@@ -0,0 +1,257 @@
...
+
+    String configuredStudioDir = config.getValue('android-studio-dir');
+    if (configuredStudioDir != null && !_hasStudioAt(configuredStudioDir)) {
+      studios.add(new AndroidStudio(configuredStudioDir,
+          configured: configuredStudioDir));
+    }
+
+    if (platform.isLinux) {
+      void _checkWellKnownPath(String path) {
+        if (fs.isDirectorySync(path) && !_hasStudioAt(path)) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: braces

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 16]
```diff
@@ -0,0 +1,257 @@
...
+      _checkWellKnownPath('$homeDirPath/android-studio');
+    }
+    return studios;
+  }
+
+  void _init() {
+    _isValid = false;
+    _validationMessages.clear();
+
+    if (configured != null) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: braces

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 17]
```diff
@@ -0,0 +1,257 @@
...
+      return;
+    }
+
+    Version latestGradleVersion;
+
+    List<FileSystemEntity> gradlePaths;
+    try {
+      gradlePaths = fs.directory(fs.path.join(directory, 'gradle')).listSync();
+      for (FileSystemEntity entry in gradlePaths.where((FileSystemEntity e) =>
+          e.basename.startsWith('gradle-') && e is Directory)) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: the wrapping here is off (the second line starts before the expression on the first line). also, `=>` with newline.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 18]
```diff
@@ -0,0 +1,257 @@
...
+        Version version =
+            new Version.parse(entry.basename.substring('gradle-'.length));
+        if (latestGradleVersion == null || version > latestGradleVersion) {
+          latestGradleVersion = version;
+          if (version >= minGradleVersion) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: brace

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 19]
```diff
@@ -0,0 +1,257 @@
...
+            _gradlePath = entry.path;
+          }
+        }
+      }
+    } catch (e) {
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: we shouldn't catch all exceptions here, only those we expect. otherwise we'll swallow bugs.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 20]
```diff
@@ -0,0 +1,257 @@
...
+      printTrace('Unable to determine Gradle version: $e');
+    }
+
+    if (latestGradleVersion == null) {
+      _validationMessages.add('Gradle not found.');
+    } else if (_gradlePath == null) {
+      _validationMessages.add('Gradle version $minGradleVersion required. '
+          'Found version $latestGradleVersion.');
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: it's more readable if the parts of a multi-part string are vertically aligned.

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 21]
```diff
@@ -0,0 +1,257 @@
...
+    } else if (processManager.canRun(gradleExecutable)) {
+      _isValid = true;
+      _validationMessages.add('Gradle version $latestGradleVersion');
+    } else {
+      _validationMessages.add(
+          'Gradle version $latestGradleVersion at $_gradlePath is not executable.');
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: unsymmetric parens

File: packages/flutter_tools/lib/src/android/android_studio.dart [hunk 22]
```diff
@@ -0,0 +1,257 @@
...
+    }
+  }
+
+  @override
+  String toString() =>
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: nit: newline and `=>`

File: packages/flutter_tools/lib/src/android/android_studio_validator.dart [hunk 23]
```diff
@@ -0,0 +1,136 @@
+// Copyright 2017 The Chromium Authors. All rights reserved.
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio_validator.dart]: nits: there's more style nits in subsequent files but hopefully you can extrapolate from the earlier comments. Please use Flutter style throughout. Thanks.

File: packages/flutter_tools/lib/src/android/gradle.dart [hunk 24]
```diff
@@ -190,48 +119,48 @@ Future<Null> buildGradleProject(BuildMode buildMode) async {
...
+      return buildGradleProjectV1(gradle);
     case FlutterPluginVersion.managed:
       // Fall through. Managed plugin builds the same way as plugin v2.
     case FlutterPluginVersion.v2:
-      return buildGradleProjectV2(gradlew, buildModeName);
+      return buildGradleProjectV2(gradle, buildModeName);
   }
 }
 
 String _escapePath(String path) => platform.isWindows ? path.replaceAll('\\', '\\\\') : path;
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/gradle.dart]: nit: this might be more readable with raw strings

File: packages/flutter_tools/lib/src/android/gradle.dart [hunk 25]
```diff
@@ -190,48 +119,48 @@ Future<Null> buildGradleProject(BuildMode buildMode) async {
...
 
-Future<Null> buildGradleProjectV1(String gradlew) async {
-  // Run 'gradlew build'.
-  Status status = logger.startProgress('Running \'gradlew build\'...', expectSlowOperation: true);
+Future<Null> buildGradleProjectV1(String gradle) async {
+  // Run 'gradle build'.
+  Status status = logger.startProgress('Running \'gradle build\'...', expectSlowOperation: true);
```
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/gradle.dart]: we should maybe check how consistent we are about this, but generally we use `"` quotes for strings in output

File: packages/flutter_tools/lib/src/android/android_studio.dart (hunk 1 above)
Comment (Hixie) [inline packages/flutter_tools/lib/src/android/android_studio.dart]: The point here is to make it trivial to read the code flow by scanning the left margin. By having returns indented, you quickly spot where the code flow is non-linear. By avoiding excessive braces, you avoid noise in the left margin.

dartfmt style is significantly less readable than we want for a project like this. We expect people to learn how to use Flutter by examining our code (it happens all the time, just look at the bugs we get filed or the discussion in the gitter channel), so our code is essentially as important as our documentation in terms of teaching our platform to our developers.
