### PR TITLE
Fix painting material toggle (#78733)

### LINKED ISSUE #78733: Switch toggle doesn't resize properly
Execute this code snippet on flutter beta channel:
```dart
class _ToggleDemoState extends State<ToggleDemo> {
  bool state = true;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 120,
      child: Switch(
        value: state,
        onChanged: (bool s) {
          setState(() {
            state = s;
          });
        },
      ),
    );
  }
}
```
Full example here (**it uses stable channel, on which this bug isn't present**): https://dartpad.dev/7e27528467695e7e439fe3a31b349aed?null_safety=true

I have also reproduced the issue on flutter web. This is how it will look like:
image

```
$ flutter --version
Flutter 2.1.0-12.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5bedb7b1d5 (4 days ago) • 2021-03-17 17:06:30 -0700
Engine • revision 711ab3fda0
Tools • Dart 2.13.0 (build 2.13.0-116.0.dev)
```

### PR DESCRIPTION
**Pull request by eEQK**
This PR fixes painting material toggle, as it was a bit weird.

Fixes  #78733

This is how it looks like on stable branch: https://www.dartpad.dev/ec2251e3d3f653f144cf5ac20a0c9a55?null_safety=true

Current master: 
image
image

With my changes:
image
image

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by eEQK** [comment]
Updated the PR with goldens.
`switch_test.big.on.png`:
switch_test big on
`switch_test.small.on.png`:
switch_test small on

File: packages/flutter/lib/src/material/switch.dart [hunk 1]
```diff
@@ -915,18 +915,23 @@ class _SwitchPainter extends ToggleablePainter {
     // Paint the track
     final Paint paint = Paint()
       ..color = trackColor;
+
     const double trackHorizontalPadding = kRadialReactionRadius - _kTrackRadius;
+    const double trackWidth = _kSwitchWidth - 2.0 * trackHorizontalPadding;
+    const double radiusAdditionalOffset = _kTrackRadius / 2;
+    final double parentWidthOffset = size.width / 2 - trackWidth + radiusAdditionalOffset;
```
Comment (goderbauer) [inline packages/flutter/lib/src/material/switch.dart:922]: I am not fully following along how the parentWidthOffset has been determined, can you explain that?

I thought it would just be `(size.width - _kSwitchWidth) / 2.0`.

Comment (eEQK) [reply packages/flutter/lib/src/material/switch.dart]: I've refactored the implementation a bit to make it easier to follow, hope that helps

**Comment by skia-gold** [comment]
Gold has detected about 2 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/78744

File: packages/flutter/lib/src/material/switch.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/material/switch.dart]: This makes it .. more confusing to follow along. I think the previous implementation was easier to understand. Can you just give a verbal explanation of why the `parentWidthOffset` has to be `size.width / 2 - trackWidth + radiusAdditionalOffset` over just `(size.width - _kSwitchWidth) / 2.0`.

Comment (eEQK) [reply packages/flutter/lib/src/material/switch.dart]: do you mind pointing out what's more confusing? 

Also, while refactoring I've found that my previous implementation was wrong as I was confused due to the amount of informations. I read the material design switch spec which made things clearer and so I believe the current solution to be correct.

Comment (eEQK) [reply packages/flutter/lib/src/material/switch.dart]: @goderbauer perhaps I could add some comments? I think it's really hard to assign meaningful names to the variables I'm modifying, 1-2 comment lines per logic block would probably explain a lot

Comment (goderbauer) [reply packages/flutter/lib/src/material/switch.dart]: Some comments would probably help.

Comment (eEQK) [reply packages/flutter/lib/src/material/switch.dart]: @goderbauer do you mind having a look? I hope it's better now

**Comment by Piinks** [comment]
(triage) Hi @eEQK, it looks like this PR has not been updated in a while, and several test are failing. Do you plan to return to this change?

**Comment by eEQK** [comment]
I didn't receive any response since my last commit, so I just assumed someone has yet to look at the updated PR. I believe the tests were failing on all PRs at the time, although I'm not sure why goldens are still pending. I'll sync my code with master and let's see whether they're fixed.

**Comment by skia-gold** [comment]
Gold has detected about 27 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/78744

**Comment by skia-gold** [comment]
Gold has detected about 29 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/78744

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/78744

**Comment by Piinks** [comment]
FYI @kjlubick, can you confirm if the skia bot is confused here?

**Comment by eEQK** [comment]
@Piinks looks like it's working now :tada:

**Comment by Piinks** [comment]
Thank you for the updates! I need to confirm the golden file changes before this moves forward. It looks like there may be a bug there (not on your end), this should not be all green since you are adding new golden images. I'll see what's going on there and circe back here. Thanks for your patience!

**Comment by kjlubick** [comment]
Something certainly appears confused on my end @Piinks; I'll look into it.

**Review by Piinks — APPROVED** [review]
LGTM! Golden files are all good. Thanks for your patience! Can you update your branch again? It looks like there is a merge conflict.

**Comment by eEQK** [comment]
Amazing, thanks. I've resolved the conflict
