### PR TITLE
Fixed translated text's subpixel alignment.

### LINKED ISSUE #149652: [Impeller] Jittery glyphs when animating text transformation
### Steps to reproduce

1. Run the sample code (wraps a Text widget within an animation-controlled Transform widget).

2. Tap the text to trigger the scale animation and reproduce the issue.

Note: The issue can also reproduced with other Transfom type such as X/Y position. It can be reproduced with packages such as [marquee](https://pub.dev/packages/marquee) (position animation) or [bounce](https://pub.dev/packages/bounce) (scale and rotation animation).

### Expected results

Spacing between glyphs should be constant across the entire animation, like when using Skia. 

### Actual results

Glyphs are jittering throughout the animation, making the spacing between glyphs inconsistent when animated.

The video recordings were taken on a physical iPhone XR because the issue was very noticeable on it.

@jonahwilliams IMHO, this looks very similar to some other typography issues (#140475, #138386 or #127815), which were fixed by flutter/engine#53042 a few days ago. Although static text now looks great, unfortunately it did not fix this specific issue during animations. Maybe some kind of rounding error is remaining ?

@chinmaygarde This is the last issue preventing us from opting in to Impeller for our production apps — should it be part of Slimpeller's last blockers before opt-out is no longer supported ? (xref #144739, #144439)

Issues aside, Impeller is truly incredible and performance improvements are outstanding compared to the previous engine. It really does feel native, now. Thanks and congratulations to the Flutter teams for this amazing project!

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with SingleTickerProviderStateMixin {
  late final controller = AnimationController(vsync: this, duration: const Duration(seconds: 2));

  TextStyle? get textStyle =>
      Theme.of(context).textTheme.headlineLarge?.copyWith(fontSize: 50.0, fontWeight: FontWeight.bold);

  bool isScaled = false;

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xffffffff))),
        home: Scaffold(
          body: GestureDetector(
            onTap: _onTap,
            child: Center(
              child: AnimatedBuilder(
                  animation: controller,
                  builder: (_, child) => Transform.scale(
                        scale: 0.7 + (CurvedAnimation(parent: controller, curve: Curves.easeInOutCubic).value * 0.3),
                        child: child,
                      ),
                  child: Center(child: Text('Large headline', style: textStyle))),
            ),
          ),
        ),
      );

  void _onTap() => setState(() {
        isScaled = !isScaled;
        if (isScaled) {
          controller.forward();
        } else {
          controller.reverse();
        }
      });
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<br>

**IMPORTANT NOTE**: Please watch the videos in fullscreen, as the small web viewport causes an overall aliasing effect which makes the difference almost un-noticeable. Ideally, you can open it in your native video player.

| Skia ✅                 | Impeller ⛔ |
| :----------------: | :----------: |
| <video src="https://github.com/flutter/flutter/assets/1833271/8ec218f8-b6b4-4188-ad79-2b5688b2e2ab">  |   <video src="https://github.com/flutter/flutter/assets/1833271/be79d790-c570-4590-92a1-4702922517e8"> |

</details>

### Logs

<details open><summary>Logs</summary>
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.23.0-13.0.pre.87, on macOS 14.5 23F79 darwin-arm64, locale en)
    • Flutter version 3.23.0-13.0.pre.87 on channel master at /Users/redacted/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c246ecdf8e (8 hours ago), 2024-06-03 18:06:22 -0700
    • Engine revision a6aa5d8266
    • Dart version 3.5.0 (build 3.5.0-218.0.dev)
    • DevTools version 2.36.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/redacted/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/redacted/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (5 available)            
    • iPhone de Dev (mobile)          • redacted • ios            • iOS 17.4.1 21E236
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 125.0.6422.141

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### LINKED ISSUE #162776: Subpixel fonts getting different results when translated versus offset
## reproduction

```c++
TEST_P(AiksTest, SubpixelScaled) {
  DisplayListBuilder builder;

  builder.Scale(0.75, 0.75);

  DlPaint paint;
  paint.setColor(DlColor::ARGB(1, 0.1, 0.1, 0.1));
  builder.DrawPaint(paint);
  Scalar offset = 0.25 / 0.75;
  for (int i = 0; i < 5; ++i) {
    RenderTextInCanvasSkia(
        GetContext(), builder, "ui", "Roboto-Regular.ttf",
        TextRenderOptions{
            .font_size = 200,
            .position = DlPoint(100 + offset * i, 150 + i * 150),
            .is_subpixel = true,
        });
  }
  DlPaint line_paint;
  line_paint.setColor(DlColor::kBlue());
  builder.DrawLine(DlPoint(111, 0), DlPoint(111, 800), line_paint);
  ASSERT_TRUE(OpenPlaygroundHere(builder.Build()));
}

TEST_P(AiksTest, SubpixelScaledTranslated) {
  DisplayListBuilder builder;

  builder.Scale(0.75, 0.75);

  DlPaint paint;
  paint.setColor(DlColor::ARGB(1, 0.1, 0.1, 0.1));
  builder.DrawPaint(paint);
  Scalar offset = 0.25 / 0.75;
  for (int i = 0; i < 5; ++i) {
    builder.Save();
    builder.Translate(100 + offset * i, 150 + i * 150);
    RenderTextInCanvasSkia(GetContext(), builder, "ui", "Roboto-Regular.ttf",
                           TextRenderOptions{
                               .font_size = 200,
                               .position = DlPoint(0, 0),
                               .is_subpixel = true,
                           });
    builder.Restore();
  }
  DlPaint line_paint;
  line_paint.setColor(DlColor::kBlue());
  builder.DrawLine(DlPoint(111, 0), DlPoint(111, 800), line_paint);
  ASSERT_TRUE(OpenPlaygroundHere(builder.Build()));
}
```

## with offset (correct)

(you have to zoom in to verify this)

Image

## with translation (incorrect)

Image

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/162776
fixes https://github.com/flutter/flutter/issues/149652

Previously we weren't calculating the subpixel offset correctly.  We weren't using the transform of the object being drawn to get global coordinates, now we are.

## Video of https://github.com/flutter/flutter/issues/149652 after PR

https://github.com/user-attachments/assets/3e9063d5-f70c-46d0-a7a4-892819b247b8

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by gaaclarke** [comment]
There is some cleanup that needs to come to the font rendering code.  I'm not happy with how this is all laid out but this is the minimal change to fix the issue.  We can consider refactors later.

1) I want to remove scale and offset from TextFrame and just rely on the transform
1) I don't like the text frame "per frame data", that should just come in the arguments instead of getting stored on the text frame

File: engine/src/flutter/impeller/display_list/dl_golden_unittests.cc [hunk 1]
```diff
@@ -452,5 +452,155 @@ TEST_P(DlGoldenTest, MaintainsSpace) {
...
+  for (int i = 1; i < 5; ++i) {
+    EXPECT_TRUE(intensity[i].x - intensity[i - 1].x == 1 ||
+                intensity[i].value < intensity[i - 1].value)
+        << i;
+  }
+}
+
+// Checks that the left most edge of the glyph is fading out as we push
+// it to the right by fractional pixels.
+TEST_P(DlGoldenTest, SubpixelScaledTranslated) {
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/display_list/dl_golden_unittests.cc:566]: This is the test that would actually fail before this change, the other passed.

File: engine/src/flutter/impeller/typographer/backends/skia/typographer_context_skia.cc [hunk 2]
```diff
@@ -452,7 +452,8 @@ TypographerContextSkia::CollectNewGlyphs(
       for (const auto& glyph_position : run.GetGlyphPositions()) {
         Point subpixel = TextFrame::ComputeSubpixelPosition(
             glyph_position, scaled_font.font.GetAxisAlignment(),
-            frame->GetOffset(), frame->GetScale());
+            frame->GetTransform() *
+                Matrix::MakeTranslation(frame->GetOffset()));
```
Comment (gaaclarke) [inline engine/src/flutter/impeller/typographer/backends/skia/typographer_context_skia.cc:456]: This is annoying, the transform here doesn't include the offset, but when you go to render it in TextContents it has the offset included.

File: engine/src/flutter/impeller/display_list/dl_golden_unittests.cc [hunk 3]
```diff
@@ -452,5 +452,158 @@ TEST_P(DlGoldenTest, MaintainsSpace) {
...
+/// Returns the highest value in the blue channel for leftmost column that isn't
+/// all black.
+LeftmostIntensity CalculateLeftmostIntensity(
+    const impeller::testing::Screenshot* img) {
+  LeftmostIntensity result = {.x = static_cast<int32_t>(img->GetWidth()),
+                              .value = 0};
+  const uint32_t* ptr = reinterpret_cast<const uint32_t*>(img->GetBytes());
+  for (size_t i = 0; i < img->GetHeight(); ++i) {
+    for (int32_t j = 0; j < static_cast<int32_t>(img->GetWidth()); ++j) {
+      if (((*ptr & 0x00ffffff) != 0)) {
```
Comment (jonahwilliams) [inline engine/src/flutter/impeller/display_list/dl_golden_unittests.cc:471]: yes, of course

**Review by jonahwilliams — APPROVED** [review]
LGTM!

File: engine/src/flutter/impeller/display_list/dl_golden_unittests.cc (hunk 3 above)
Comment (gaaclarke) [reply engine/src/flutter/impeller/display_list/dl_golden_unittests.cc:471]: indeed, sir

**Comment by gaaclarke** [comment]
Weird, something is going on with the vulkan renderer where we are getting zero values in the blue channel.  We should look into that.  For now I switched to the green channel which works as expected locally.
