### PR TITLE
Fixes issue, ReorderableListView destroys children even if their key-type wasn't changed

### LINKED ISSUE #58364: ReorderableListView destroys children even if Key-Type of children wasn't changed
Hi,
I noticed ReorderableListView rebuilds children every time even if Key-Type of children wasn't changed.

demo: https://dartpad.dartlang.org/d5cdcdbd79081a06f0b5bdacfeb55c33
(https://gist.github.com/MariaMelnik/d5cdcdbd79081a06f0b5bdacfeb55c33)

**Steps to reproduce:**

- Create new flutter project with main.dart copied from example above.
- Run on device (I used Chrome(web) and simulator iPhone 11 Pro max).
- Hit refresh icon button at the AppBar.

**What do I expect:**
Nothing changed. Because keys which I set to widget didn't changed (I used ValueKey with int inside. int will always be equal same int). So I expect my _MyListTileState keeps ms values but not drops it.

In this demo case I use empty setState just to demonstrate issue. In real world it is supposed to be meaningfull update. And ms changes in real world could be animation changes.

**What is happening:**
Every child of the ReorderableListView was destroyed and created again with new state. They lost all states.

**Why it is happening (imho):**
Reordable list under the hood wraps children I gave with new widget and assign new keys to that widget. That keys is GlobalObjectKey that use children's I gave keys as inner value.
To check if two GlobalObjectKey object is equal identical is used. And because ValueKey I assign to my tiles every time is new object (with same int inside though) GlobalObjectKey that stores them every time fail equal checks. And flutter destroy my MyListTile widget with state and create new one with initial state.

reorderable_list.dart
```
  // Wraps one of the widget's children in a DragTarget and Draggable.
  // Handles up the logic for dragging and reordering items in the list.
  Widget _wrap(Widget toWrap, int index, BoxConstraints constraints) {
    assert(toWrap.key != null);
    final GlobalObjectKey keyIndexGlobalKey = GlobalObjectKey(toWrap.key);
    // We pass the toWrapWithGlobalKey into the Draggable so that when a list
    // item gets dragged, the accessibility framework can preserve the selected
    // state of the dragging item.
   ...
    // We pass toWrap with a GlobalKey into the Draggable so that when a list
    // item gets dragged, the accessibility framework can preserve the selected
    // state of the dragging item.
    //
    // We also apply the relevant custom accessibility actions for moving the item
    // up, down, to the start, and to the end of the list.
    return KeyedSubtree(
      key: keyIndexGlobalKey,
      child: MergeSemantics(
        child: Semantics(
            customSemanticsActions: semanticsActions,
            child: toWrap,
         ),
       ),
     );
  }
```

framework.dart
```
@optionalTypeArgs
class GlobalObjectKey<T extends State<StatefulWidget>> extends GlobalKey<T> {
  /// Creates a global key that uses [identical] on [value] for its [operator==].
  const GlobalObjectKey(this.value) : super.constructor();

  /// The object whose identity is used by this key's [operator==].
  final Object value;

  @override
  bool operator ==(Object other) {
    if (other.runtimeType != runtimeType)
      return false;
    return other is GlobalObjectKey<T>
        && identical(other.value, value);
  }

  @override
  int get hashCode => identityHashCode(value);

...
}

```

flutter doctor output:
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G4032, locale en-RU)
    • Flutter version 1.17.1 at {$pathToFlutter}
    • Framework revision f7a6a7906b (12 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at {$pathToAndroidSdk}
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 112D9763-364B-48C1-9B0F-BA92AEE6B5F8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)

```

### PR DESCRIPTION
**Pull request by haeseoklee**
## Description

GlobalObjectKey used in the child of ReorderableListView does not work well for key comparison.

I solved the problem by assigning a new Key called GlobalObjectValueKey.

It compares values within Objects rather than using identical.

<details><summary>example code</summary>

```Dart

import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(title: 'ReorderableListView issue demo',),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  MyHomePage({Key key, this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<int> data = List.generate(10, (index) => index);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: [_buildRefreshBtn()],
      ),
      body: Center(
          child: ReorderableListView(
            children: _buildTiles(),
            onReorder: (_, __) {},
          )
      ),
    );
  }

  Widget _buildRefreshBtn() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20.0),
      child: IconButton(
          icon: Icon(Icons.refresh),
          onPressed: (){setState(() {});}
      ),
    );
  }

  List<Widget> _buildTiles() {
    List<Widget> tiles = data.map((int val) {

      return MyListTile(
        key: ValueKey(val),
        data: val,
        title: "tile $val",
      );
    }).toList();
    return tiles;
  }
}


class MyListTile extends StatefulWidget {
  final int data;
  final String title;


  MyListTile({this.data, this.title, Key key}): super(key: key);

  @override
  _MyListTileState createState() => _MyListTileState();
}


class _MyListTileState extends State<MyListTile> {
  Stream<int> _msStream;
  int _curMs;

  @override
  void initState() {
    super.initState();

    print("init: ${widget.title}");
    _curMs = 0;
    _msStream = Stream.periodic(const Duration(milliseconds: 100), (ms) => ms);

  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(vertical: 20.0, horizontal: 30.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text("${widget.title}"),
          StreamBuilder<int>(
              stream: _msStream,
              initialData: _curMs,
              builder: (_, AsyncSnapshot<int> snapshot) {
                if (!snapshot.hasData) return Center(child: CircularProgressIndicator());

                String ms = "${snapshot.data} ms";
                return Text(ms);
              }
          )
        ],
      ),
    );
  }

  void dispose(){
    print("dispose: ${widget.title}");
    super.dispose();
  }
}

```

</details>

Here is a simplified reproduction written by @Hixie 

<details><summary>example code2</summary>

```Dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: OuterTest()));
}

class OuterTest extends StatelessWidget {
  OuterTest({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ReorderableListView(
      children: <Widget>[ InnerTest(key: ValueKey(0)) ],
      onReorder: (_, __) {},
    );
  }
}

class InnerTest extends StatefulWidget {
  InnerTest({ Key key }): super(key: key);

  @override
  _InnerTestState createState() => _InnerTestState();
}

class _InnerTestState extends State<InnerTest> {
  @override
  Widget build(BuildContext context) {
    return Text('$hashCode - should not change in hot reload');
  }
}
```

</details>

## Related Issues

Fixes https://github.com/flutter/flutter/issues/58364

## Tests

I added the following tests:

https://github.com/flutter/flutter/pull/64855/commits/348475cd0380236f6cc2cbb3fdc4ae3e2dbd0801

I referred to the code in the issue written by PixelToast. Thanks to @PixelToast. 

This test can check whether the child key has changed when the widget is rebuilt.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

File: packages/flutter/lib/src/material/reorderable_list.dart [hunk 1]
```diff
@@ -596,3 +596,27 @@ class _ReorderableListContentState extends State<_ReorderableListContent> with T
...
+  bool operator ==(Object other) {
+    if (other.runtimeType != runtimeType)
+      return false;
+    return other is _GlobalObjectValueKey<T>
+        && other.value == value;
+  }
+
+  @override
+  int get hashCode => super.hashCode;
+}
```
Comment (Hixie) [inline packages/flutter/lib/src/material/reorderable_list.dart:622]: The problem with this approach is it'll fail if there's _two_ `ReorderableListView`s with items that have the same local keys. I think the solution is that `_GlobalObjectValueKey` should have two values, one is the key we're proxying to, and the other is the _ReorderableListContentState to which they belong. We can probably rename it to `_ReorderableListChildGlobalKey` or something, with arguments `final Key subkey` and `final _ReorderableListContentState state` or something like that, to make it clearer what is going on.

**Comment by Hixie** [comment]
Nice work on the tests!

File: packages/flutter/lib/src/material/reorderable_list.dart (hunk 1 above)
Comment (haeseoklee) [reply packages/flutter/lib/src/material/reorderable_list.dart:622]: @Hixie 
That's a great idea! Thanks for the comment. I will apply it immediately.

**Comment by haeseoklee** [comment]
@Hixie 
I found a fatal bug before updating my code. 

When ReorderableListView was first built, the order could be changed, but an error occurred after pressing the refresh button.

After a bug occurs, the order cannot be changed and the state is initialized.

I would like to ask your advice.

<details><summary>example code</summary>

```Dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(title: 'ReorderableListView issue demo',),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  MyHomePage({Key key, this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<int> data = List.generate(10, (index) => index);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: [_buildRefreshBtn()],
      ),
      body: Center(
          child: ReorderableListView(
            children: _buildTiles(),
            onReorder: (_, __) {},
          )
      ),
    );
  }

  Widget _buildRefreshBtn() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20.0),
      child: IconButton(
          icon: Icon(Icons.refresh),
          onPressed: (){setState(() {});}
      ),
    );
  }

  List<Widget> _buildTiles() {
    List<Widget> tiles = data.map((int val) {

      return MyListTile(
        key: ValueKey(val),
        data: val,
        title: "tile $val",
      );
    }).toList();
    return tiles;
  }
}


class MyListTile extends StatefulWidget {
  final int data;
  final String title;


  MyListTile({this.data, this.title, Key key}): super(key: key);

  @override
  _MyListTileState createState() => _MyListTileState();
}


class _MyListTileState extends State<MyListTile> {
  Stream<int> _msStream;
  int _curMs;

  @override
  void initState() {
    super.initState();

    print("init: ${widget.title}");
    _curMs = 0;
    _msStream = Stream.periodic(const Duration(milliseconds: 100), (ms) => ms);

  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(vertical: 20.0, horizontal: 30.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text("${widget.title}"),
          StreamBuilder<int>(
              stream: _msStream,
              initialData: _curMs,
              builder: (_, AsyncSnapshot<int> snapshot) {
                if (!snapshot.hasData) return Center(child: CircularProgressIndicator());

                String ms = "${snapshot.data} ms";
                return Text(ms);
              }
          )
        ],
      ),
    );
  }

  void dispose(){
    print("dispose: ${widget.title}");
    super.dispose();
  }
}
```

</details>

<details><summary>log</summary>

```Console
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Running Xcode build...
Xcode build done.                                            9.4s
Waiting for iPhone SE (2nd generation) to report its views...
Debug service listening on ws://127.0.0.1:50703/IbMyf_8lHco=/ws
Syncing files to device iPhone SE (2nd generation)...
flutter: init: tile 0
flutter: init: tile 1
flutter: init: tile 2
flutter: init: tile 3
flutter: init: tile 4
flutter: init: tile 5
flutter: init: tile 6
flutter: init: tile 7
flutter: init: tile 8
flutter: init: tile 9

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'size' was called on null.
Receiver: null
Tried calling: size

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _ReorderableListContentState._wrap.onDragStarted.<anonymous closure> (package:flutter/src/material/reorderable_list.dart:379:66)
#2      State.setState (package:flutter/src/widgets/framework.dart:1244:30)
#3      _ReorderableListContentState._wrap.onDragStarted (package:flutter/src/material/reorderable_list.dart:373:7)
#4      _DraggableState._startDrag (package:flutter/src/widgets/drag_target.dart:425:27)
...
Handler: "onStart"
Recognizer: DelayedMultiDragGestureRecognizer#96287
════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: init: tile 0
flutter: dispose: tile 0

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 175 pos 16: 'element.widget.runtimeType != _registry[this].widget.runtimeType': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'size' was called on null.
Receiver: null
Tried calling: size

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _ReorderableListContentState._wrap.onDragStarted.<anonymous closure> (package:flutter/src/material/reorderable_list.dart:379:66)
#2      State.setState (package:flutter/src/widgets/framework.dart:1244:30)
#3      _ReorderableListContentState._wrap.onDragStarted (package:flutter/src/material/reorderable_list.dart:373:7)
#4      _DraggableState._startDrag (package:flutter/src/widgets/drag_target.dart:425:27)
...
Handler: "onStart"
Recognizer: DelayedMultiDragGestureRecognizer#b9436
════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: init: tile 2
flutter: dispose: tile 2

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 175 pos 16: 'element.widget.runtimeType != _registry[this].widget.runtimeType': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
Duplicate GlobalKey detected in widget tree.
════════════════════════════════════════════════════════════════════════════════════════════════════

```

</details>

**Comment by Hixie** [comment]
> After a bug occurs, the order cannot be changed and the state is initialized.

If the exception occurs during build then you're probably ending up with this widget in an inconsistent state. The solution is to make the code not throw the first exception (it wasn't clear to me if the first exception you're seeing is from the framework/this widget or if it's from user code).

**Comment by haeseoklee** [comment]
@Hixie 
I can't come up with a clear solution, but I'll try again. Thank you very much :)

**Comment by haeseoklee** [comment]
@Hixie 
As a result I solved this problem. I guess the example code was wrong.

In the example, each time ```setState()``` is called, ```ValueKey(index)``` is reassigned.

Here's how I did it.

```Dart
final List<Key> keyValues = List.generate(10, (index) => ValueKey(index));
```

```Dart
List<Widget> _buildTiles() {
    List<Widget> tiles = data.map((int val) {

      return MyListTile(
        key: keyValues[val],
        data: val,
        title: "tile $val",
      );
    }).toList();
    return tiles;
  }
```

No other problems occurred after I tested it.

I would be grateful if you could review my PR again.

**Comment by Hixie** [comment]
Patch looks good, we should get a second reviewer just to double check, but otherwise I think it's good. Which example was it you said had problems?

File: packages/flutter/lib/src/material/reorderable_list.dart [hunk 2]
```diff
@@ -596,3 +596,30 @@ class _ReorderableListContentState extends State<_ReorderableListContent> with T
...
   }
 }
+
+/// A global key that takes its identity from the object and uses a value of a
+/// particular type to identify itself.
+///
+/// The difference with GlobalObjectKey is that it uses [==] instead of [identical]
+/// of the objects used to generate widgets.
+@optionalTypeArgs
+class _ReorderableListViewChildGlobalKey<T extends State<StatefulWidget>> extends GlobalObjectKey<T> {
```
[the remark this answers is not in the document]
Comment (haeseoklee) [reply packages/flutter/lib/src/material/reorderable_list.dart:606]: Thank you! I updated the code.

**Comment by haeseoklee** [comment]
Here is the example code.

I agree. It's a good idea to find a second reviewer and check the code.

<details><summary>example code</summary>

```Dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(title: 'ReorderableListView issue demo',),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  MyHomePage({Key key, this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final List<int> data = List.generate(10, (index) => index);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: [_buildRefreshBtn()],
      ),
      body: Center(
          child: ReorderableListView(
            children: _buildTiles(),
            onReorder: (_, __) {},
          )
      ),
    );
  }

  Widget _buildRefreshBtn() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20.0),
      child: IconButton(
          icon: Icon(Icons.refresh),
          onPressed: (){setState(() {});}
      ),
    );
  }

  List<Widget> _buildTiles() {
    List<Widget> tiles = data.map((int val) {

      return MyListTile(
        key: ValueKey(val),
        data: val,
        title: "tile $val",
      );
    }).toList();
    return tiles;
  }
}


class MyListTile extends StatefulWidget {
  final int data;
  final String title;


  MyListTile({this.data, this.title, Key key}): super(key: key);

  @override
  _MyListTileState createState() => _MyListTileState();
}


class _MyListTileState extends State<MyListTile> {
  Stream<int> _msStream;
  int _curMs;

  @override
  void initState() {
    super.initState();

    print("init: ${widget.title}");
    _curMs = 0;
    _msStream = Stream.periodic(const Duration(milliseconds: 100), (ms) => ms);

  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(vertical: 20.0, horizontal: 30.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text("${widget.title}"),
          StreamBuilder<int>(
              stream: _msStream,
              initialData: _curMs,
              builder: (_, AsyncSnapshot<int> snapshot) {
                if (!snapshot.hasData) return Center(child: CircularProgressIndicator());

                String ms = "${snapshot.data} ms";
                return Text(ms);
              }
          )
        ],
      ),
    );
  }

  void dispose(){
    print("dispose: ${widget.title}");
    super.dispose();
  }
}
```

</details>

**Comment by haeseoklee** [comment]
@chunhtai 
I would appreciate it if you could review the code.
It seems to be related to other PRs.
https://github.com/flutter/flutter/pull/41338
https://github.com/flutter/flutter/pull/41931

File: packages/flutter/lib/src/material/reorderable_list.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/reorderable_list.dart:625]: @Hixie Add `_ReorderableListContentState` as a value of the key can not solve the situation where multiple items use the same local key, which will lead to Multiple widgets used the same GlobalKey, such as:
```
  @override
  Widget build(BuildContext context) {
    return ReorderableListView(
      children: <Widget>[ InnerTest(key: ValueKey(0)), InnerTest(key: ValueKey(0)) ],
      onReorder: (_, __) {},
    );
  }
```
The reason why there is no problem here is its wrong implementation of `int get hashCode => identityHashCode(subKey);`

File: packages/flutter/lib/src/material/reorderable_list.dart [hunk 3]
```diff
@@ -596,3 +596,30 @@ class _ReorderableListContentState extends State<_ReorderableListContent> with T
...
+  bool operator ==(Object other) {
+    if (other.runtimeType != runtimeType)
+      return false;
+    return other is _ReorderableListViewChildGlobalKey
+        && other.subKey == subKey
+        && other.state == state;
+  }
+
+  @override
+  int get hashCode => identityHashCode(subKey);
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/reorderable_list.dart:624]:
```
    If [operator ==] is overridden to use the object state instead,
    the hash code must also be changed to represent that state.
```

File: packages/flutter/lib/src/material/reorderable_list.dart (hunk 1 above)
Comment (xu-baolin) [reply packages/flutter/lib/src/material/reorderable_list.dart:625]: Probably we could add the `index` into the values together.

File: packages/flutter/lib/src/material/reorderable_list.dart [hunk 4]
```diff
@@ -596,3 +596,30 @@ class _ReorderableListContentState extends State<_ReorderableListContent> with T
     });
   }
 }
+
+/// A global key that takes its identity from the object and uses a value of a
+/// particular type to identify itself.
+///
+/// The difference with GlobalObjectKey is that it uses [==] instead of [identical]
+/// of the objects used to generate widgets.
```
Comment (xu-baolin) [inline packages/flutter/lib/src/material/reorderable_list.dart:604]: Comments whit `//` .

Comment (haeseoklee) [reply packages/flutter/lib/src/material/reorderable_list.dart:604]: I don't know much about the hash in the key. Would you explain with an example?

Comment (xu-baolin) [reply packages/flutter/lib/src/material/reorderable_list.dart:604]: Also see
```
/**
   * The equality operator.
   *
   * The default behavior for all [Object]s is to return true if and
   * only if `this` and [other] are the same object.
   *
   * Override this method to specify a different equality relation on
   * a class. The overriding method must still be an equivalence relation.
   * That is, it must be:
   *
   *  * Total: It must return a boolean for all arguments. It should never throw
   *    or return `null`.
   *
   *  * Reflexive: For all objects `o`, `o == o` must be true.
   *
   *  * Symmetric: For all objects `o1` and `o2`, `o1 == o2` and `o2 == o1` must
   *    either both be true, or both be false.
   *
   *  * Transitive: For all objects `o1`, `o2`, and `o3`, if `o1 == o2` and
   *    `o2 == o3` are true, then `o1 == o3` must be true.
   *
   * The method should also be consistent over time,
   * so whether two objects are equal should only change
   * if at least one of the objects was modified.
   *
   * If a subclass overrides the equality operator it should override
   * the [hashCode] method as well to maintain consistency.
   */
  external bool operator ==(Object other);

  /**
   * The hash code for this object.
   *
   * A hash code is a single integer which represents the state of the object
   * that affects [operator ==] comparisons.
   *
   * All objects have hash codes.
   * The default hash code represents only the identity of the object,
   * the same way as the default [operator ==] implementation only considers objects
   * equal if they are identical (see [identityHashCode]).
   *
   * If [operator ==] is overridden to use the object state instead,
   * the hash code must also be changed to represent that state.
   *
   * Hash codes must be the same for objects that are equal to each other
   * according to [operator ==].
   * The hash code of an object should only change if the object changes
   * in a way that affects equality.
   * There are no further requirements for the hash codes.
   * They need not be consistent between executions of the same program
   * and there are no distribution guarantees.
   *
   * Objects that are not equal are allowed to have the same hash code,
   * it is even technically allowed that all instances have the same hash code,
   * but if clashes happen too often, it may reduce the efficiency of hash-based
   * data structures like [HashSet] or [HashMap].
   *
   * If a subclass overrides [hashCode], it should override the
   * [operator ==] operator as well to maintain consistency.
   */
  external int get hashCode;
```

File: packages/flutter/lib/src/material/reorderable_list.dart (hunk 3 above)
Comment (haeseoklee) [reply packages/flutter/lib/src/material/reorderable_list.dart:624]: How about this way?

```Dart
@override
int get hashCode => hashValues(subKey.hashCode, identityHashCode(state));
```

File: packages/flutter/lib/src/material/reorderable_list.dart (hunk 4 above)
Comment (haeseoklee) [reply packages/flutter/lib/src/material/reorderable_list.dart:604]: Thank you very much 👍

File: packages/flutter/lib/src/material/reorderable_list.dart (hunk 3 above)
Comment (haeseoklee) [reply packages/flutter/lib/src/material/reorderable_list.dart:624]: The new hash seems to work fine :)

Comment (xu-baolin) [reply packages/flutter/lib/src/material/reorderable_list.dart:624]:
```dart
@override
int get hashCode => hashValues(subKey, state, index);
```

Comment (haeseoklee) [reply packages/flutter/lib/src/material/reorderable_list.dart:624]: Do we need an index? ValueKey already has a value for the index.

Comment (xu-baolin) [reply packages/flutter/lib/src/material/reorderable_list.dart:624]: See https://github.com/flutter/flutter/pull/64855#discussion_r484312001

File: packages/flutter/lib/src/material/reorderable_list.dart (hunk 1 above)
Comment (PixelToast) [reply packages/flutter/lib/src/material/reorderable_list.dart:625]: @xu-baolin Two children can never have the same key, so the current behavior is correct

Comment (PixelToast) [reply packages/flutter/lib/src/material/reorderable_list.dart:625]: See: https://api.flutter.dev/flutter/foundation/Key-class.html

"Keys must be unique amongst the Elements with the same parent."

Comment (xu-baolin) [reply packages/flutter/lib/src/material/reorderable_list.dart:625]: I see, thank you.

Comment (xu-baolin) [reply packages/flutter/lib/src/material/reorderable_list.dart:625]: @PixelToast However, this change not an equivalent modification, and maybe cause ` Multiple widgets used the same GlobalKey` during layout phase. See https://github.com/flutter/flutter/pull/41338#issuecomment-538082979

Comment (PixelToast) [reply packages/flutter/lib/src/material/reorderable_list.dart:625]: @xu-baolin No problem!

This PR is for fixing a specific bug and not extending functionality though, you are welcome to open a new issue to discuss any changes to functionality that would be nice to have.

File: packages/flutter/lib/src/material/reorderable_list.dart (hunk 4 above)
Comment (PixelToast) [reply packages/flutter/lib/src/material/reorderable_list.dart:604]: @xu-baolin @haeseoklee 
This repo uses the triple slash for documentation comments, see the style guide: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#use-for-public-quality-private-documentation

File: packages/flutter/test/material/reorderable_list_test.dart [hunk 5]
```diff
@@ -771,6 +798,33 @@ void main() {
         expect(findState(const Key('A')).checked, true);
       });
 
+      testWidgets('Preserves children states when rebuilt', (WidgetTester tester) async {
```
Comment (chunhtai) [inline packages/flutter/test/material/reorderable_list_test.dart:801]: Is this the same test as previous one?

**Review by chunhtai — COMMENTED** [review]
Change looks reasonable. Added a comment about test

File: packages/flutter/test/material/reorderable_list_test.dart (hunk 5 above)
Comment (haeseoklee) [reply packages/flutter/test/material/reorderable_list_test.dart:801]: Yes. One is for''vertical mode" and the other is for "horizontal mode"

Comment (chunhtai) [reply packages/flutter/test/material/reorderable_list_test.dart:801]: I see, but then you will need to set scrollDirection to vertical in this test, right?

**Comment by haeseoklee** [comment]
@chunhtai 
I added comments about test.

**Comment by chunhtai** [comment]
> @chunhtai
> I added comments about test.

I think we need to set the scrollDirection to the test, I also replied to the comment

File: packages/flutter/test/material/reorderable_list_test.dart (hunk 5 above)
Comment (haeseoklee) [reply packages/flutter/test/material/reorderable_list_test.dart:802]: That's right. I'll apply it right away. 👍

**Comment by haeseoklee** [comment]
@chunhtai 
Thank you for your comment. I applied it.

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by awhitford** [comment]
I'm looking forward to this.  Which Flutter version will contain this fix?
