### PR TITLE
Remove bottom padding in SliverAppBar

### LINKED ISSUE #13458: [Regression] Material leading button scrolls in slivers
https://streamable.com/mri1t

Tentatively marking as today. It looks visually pretty jarring.

### PR DESCRIPTION
**Pull request by cbracken**
Removes bottom padding from the child AppBar in SliverAppBar. Scaffold
already does this for its own app bars, but sliver app bars in the body
should also apply the bottom padding removal.

Fixes flutter/flutter#13458

### CODE REVIEW

File: packages/flutter/lib/src/material/app_bar.dart [hunk 1]
```diff
@@ -601,23 +601,27 @@ class _SliverAppBarDelegate extends SliverPersistentHeaderDelegate {
...
-        backgroundColor: backgroundColor,
-        brightness: brightness,
-        iconTheme: iconTheme,
-        textTheme: textTheme,
-        primary: primary,
-        centerTitle: centerTitle,
-        titleSpacing: titleSpacing,
-        toolbarOpacity: toolbarOpacity,
-        bottomOpacity: pinned ? 1.0 : (visibleMainHeight / _bottomHeight).clamp(0.0, 1.0),
+      child: new MediaQuery.removePadding(
```
Comment (xster) [inline packages/flutter/lib/src/material/app_bar.dart]: Discussed offline, move this to line 961

**Review by xster — APPROVED** [review]
LG

File: packages/flutter/lib/src/material/app_bar.dart (hunk 1 above)
Comment (cbracken) [reply packages/flutter/lib/src/material/app_bar.dart]: Done.

**Comment by xster** [comment]
Still LG
