### PR TITLE
Identify CheckBox and RadioButton as such

### LINKED ISSUE #14071: Android A11Y: Radio button is not recognized by screen reader
## Steps to Reproduce

once focus moves on to radio button, captions are read out but no reference to radio button selection / deselection is being read out

### PR DESCRIPTION
**Pull request by goderbauer**
Also fixes problems with duplicated nodes for Radio and properly identifies these elements as enabled/disabled.

Fixes https://github.com/flutter/flutter/issues/14071.

### CODE REVIEW

File: packages/flutter/lib/src/semantics/semantics.dart [hunk 1]
```diff
@@ -1774,6 +1775,15 @@ class SemanticsConfiguration {
     _setFlag(SemanticsFlag.isChecked, value);
   }
 
+  /// Whether the owning [RenderObject] is in a mutally exclusive group.
```
Comment (yjbanov) [inline packages/flutter/lib/src/semantics/semantics.dart]: nit: typo "mutally". Also this sentence just repeats the name of the field. Could you expand the description? For example, you could say that the owning RenderObject corresponds to UI that allows the user to pick one of several mutually exclusive options. The example below would back it up perfectly.

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
lgtm

File: packages/flutter/lib/src/semantics/semantics.dart (hunk 1 above)
Comment (goderbauer) [reply packages/flutter/lib/src/semantics/semantics.dart]: Good idea. Done.
