### PR TITLE
Don't call onChanged callbacks when formatter rejects the change & handle text input formatter exceptions.

### LINKED ISSUE #44979: TextField calls onChange even when the value hasn't changed
CODE:
```
TextField(
              inputFormatters: [LengthLimitingTextInputFormatter(2)],
              onChanged: (value){
                print(value);
              },
            )
```

`他会不停的触发打印的方法，但是Value没有变`
He keeps printing, but the value doesn't change

### LINKED ISSUE #73179: TextInputFormatter silently fails when invalid index access of newValue.text
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(50.0),
          child: TextField(
            controller: TextEditingController()..text = 'initial value',
            inputFormatters: [DoNothingFormatter()],
          ),
        ),
      ),
    );
  }
}

class DoNothingFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    final char = newValue.text[2];
    return newValue;
  }
}
```

3. Run with `flutter run --no-sound-null-safety --verbose`
4. Backspace until invalid access of character from `newValue.text`:

**Expected results:** 

1. This creates a formatter that invalidly accesses `newValue.text[2]` (sometimes it can be null).
2. There should be an exception or error message on out of bounds access

**Actual results:** 

1. No indication that something has failed in the logs

backspace

Pressing backspace does not do anything when there is no index `2` (accessed in `newValue.text[2]`), the text just remains in TextInputFormatter and no error is thrown in the console.

<details>
  <summary>Logs</summary>

```
No logs after running app.
```

```
Analyzing text_formatter_issue...                                       

   info • The value of the local variable 'char' isn't used •
          lib/main.dart:31:11 • unused_local_variable

1 issue found. (ran in 7.6s)
```

```
→ flutter doctor -v
[✓] Flutter (Channel master, 1.26.0-2.0.pre.167, on macOS 11.1 20C69
    darwin-x64, locale en-US)
    • Flutter version 1.26.0-2.0.pre.167 at /Users/droidery/flutter
    • Framework revision d3a2259541 (5 hours ago), 2020-12-31 15:14:03 -0500
    • Engine revision 82b4ae86d6
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/droidery/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6803

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (3 available)
```

</details>

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes https://github.com/flutter/flutter/issues/44979
Fixes https://github.com/flutter/flutter/issues/73179

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 1]
```diff
@@ -2254,29 +2254,30 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     // current composing region) is very infinite-loop-prone: the formatters
     // will keep trying to modify the composing region while Gboard will keep
     // trying to restore the original composing region.
-    final bool textChanged = _value.text != value.text
-                          || (!_value.composing.isCollapsed && value.composing.isCollapsed);
-    final bool selectionChanged = _value.selection != value.selection;
+    final bool preformattedTextChanged = _value.text != newTextEditingValue.text
+                                      || (!_value.composing.isCollapsed && newTextEditingValue.composing.isCollapsed);
```
Comment (LongCatIsLooong) [inline packages/flutter/lib/src/widgets/editable_text.dart:2258]: changed the parameter name because it was making this expression kinda confusing.

**Comment by magnito777** [comment]
I like flutter

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 2]
```diff
@@ -2234,7 +2234,10 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
     _lastBottomViewInset = WidgetsBinding.instance!.window.viewInsets.bottom;
   }
 
-  void _formatAndSetValue(TextEditingValue value, SelectionChangedCause? cause, {bool userInteraction = false}) {
+  // This method is often called by platform message handlers that catch and
+  // send unrecognized exceptions to the engine/platform. Make sure the
+  // exceptions user callbacks throw are handled within this method.
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:2239]: Nit:

```diff
- exceptions user callbacks throw
+ exceptions that user callbacks throw
```

That just makes it slightly easier to read IMO.

Comment (justinmc) [reply packages/flutter/lib/src/widgets/editable_text.dart:2239]: This swallowing of errors has bit me before and is hard to notice.

File: packages/flutter/lib/src/widgets/editable_text.dart [hunk 3]
```diff
@@ -2243,21 +2246,33 @@ class EditableTextState extends State<EditableText> with AutomaticKeepAliveClien
...
-        value,
-        (TextEditingValue newValue, TextInputFormatter formatter) => formatter.formatEditUpdate(_value, newValue),
-      ) ?? value;
+    final bool preformatTextChanged = _value.text != newTextEditingValue.text
+                                      || (!_value.composing.isCollapsed && newTextEditingValue.composing.isCollapsed);
+
+    final List<TextInputFormatter>? formatters = widget.inputFormatters;
+    if (preformatTextChanged && formatters != null && formatters.isNotEmpty) {
+      for (final TextInputFormatter formatter in formatters) {
+        try {
```
Comment (justinmc) [inline packages/flutter/lib/src/widgets/editable_text.dart:2255]: So if an error is thrown by a formatter, then that formatter will not be applied, but it will continue on to applying subsequent formatters.  Is that desired or should it die right there?

**Review by justinmc — APPROVED** [review]
LGTM 👍 

One docs nit and one question.

File: packages/flutter/lib/src/widgets/editable_text.dart (hunk 3 above)
Comment (LongCatIsLooong) [reply packages/flutter/lib/src/widgets/editable_text.dart:2255]: Good point. I wanted to get the type of the formatter but stopping the iteration makes more sense.
