### PR TITLE
[web] Allow shift + left/right keyboard shortcuts to be handled by framework on web

### LINKED ISSUE #117165: [web] Selection highlighting should be disabled via keyboard shortcuts when `enableInteractiveSelection: false` for TextFields
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Click into TextField and enter some text
3. Use shift + left or shift + right to highlight text.

**Expected results:** Text selection/highlighting is possible.

**Actual results:** The cursor should just move left/right without highlighting. 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: const Center(
        child: TextField(
          enableInteractiveSelection: false, // selection disabled
          onChanged: print,
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 3.7.0-9.0.pre.18, on macOS 12.6.1 21G217 darwin-arm64, locale en-US)
    • Flutter version 3.7.0-9.0.pre.18 on channel master at /Users/hassantoor/Desktop/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision b122200d4c (2 hours ago), 2022-12-15 13:56:06 -0500
    • Engine revision 29196519c1
    • Dart version 3.0.0 (build 3.0.0-21.0.dev)
    • DevTools version 2.20.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/hassantoor/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Users/hassantoor/Desktop/../Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

Web:

https://user-images.githubusercontent.com/110993981/207962600-28aac82d-d379-485f-a1f3-a429c6af67da.mov

MacOS (doesn't highlight selection on keyboard shortcuts):

https://user-images.githubusercontent.com/110993981/207962482-359c52b6-2dba-42ca-a753-f10c7b83fe0a.mov

### PR DESCRIPTION
**Pull request by htoor3**
When `enableInteractiveSelection` is set to `false`, users shouldn't be able to highlight/expand text selection in the given TextFields.  This currently works as expected with pointer events, but keyboard shortcuts still allow text selection to be expanded on the web.  This is inconsistent with how it behaves on other platforms where keyboard shortcuts come into play such as Desktop. 

Fixes https://github.com/flutter/flutter/issues/117165

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart [hunk 1]
```diff
@@ -420,8 +420,6 @@ class DefaultTextEditingShortcuts extends StatelessWidget {
     SingleActivator(LogicalKeyboardKey.arrowUp, meta: true): DoNothingAndStopPropagationTextIntent(),
     SingleActivator(LogicalKeyboardKey.arrowLeft, shift: true, meta: true): DoNothingAndStopPropagationTextIntent(),
     SingleActivator(LogicalKeyboardKey.arrowRight, shift: true, meta: true): DoNothingAndStopPropagationTextIntent(),
-    SingleActivator(LogicalKeyboardKey.arrowLeft, shift: true): DoNothingAndStopPropagationTextIntent(),
-    SingleActivator(LogicalKeyboardKey.arrowRight, shift: true): DoNothingAndStopPropagationTextIntent(),
```
Comment (mdebbar) [inline packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:424]: Should we also remove the other related ones? (e.g. `shift+alt+arrow`, `shift+meta+arrow`, etc).

**Review by chunhtai — APPROVED** [review]
changes looks good as long as comments from others are addressed

File: packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart (hunk 1 above)
Comment (htoor3) [reply packages/flutter/lib/src/widgets/default_text_editing_shortcuts.dart:424]: Added these below + tests

**Review by mdebbar — APPROVED** [review]
