### PR TITLE
[web] Fix loading of fragment shader with space in name.

### LINKED ISSUE #180862: Flutter Web fails to load shader assets containing spaces in file names
### Steps to reproduce

1. Clone the repository: `git clone https://github.com/nightmare-space/shader_graph`
2. Change to version tag v0.1.0: `git checkout v0.1.0`
3. Run the example project on web: `cd shader_graph/example && flutter run -d chrome`

### Expected results

Shader assets with spaces in file names should load successfully on Flutter Web, just as they do on other platforms (iOS, Android, desktop).

### Actual results

```javascript
[log] Error loading shader program from shaders/wrap/Wrap Debug.frag: Flutter Web engine failed to fetch "assets/shaders/wrap/Wrap%20Debug.frag". HTTP request succeeded, but the server responded with HTTP status 404.
```

### Code sample

See [example](https://github.com/nightmare-space/shader_graph/blob/v0.1.0/example/lib/main.dart)

### Logs

<details open><summary>Logs</summary>

```console
Restarted application in 100ms.
3
[log] Error loading shader program from shaders/wrap/Wrap Debug.frag: Flutter Web engine failed to fetch "assets/shaders/wrap/Wrap%20Debug.frag". HTTP request succeeded, but the server responded with HTTP status 404.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
➜  shader_graph git:(main) ✗ flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.38.4, on macOS 26.2 25C56 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 26.1.1)
[✓] Chrome - develop for the web
[✓] Proxy Configuration
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

## Additional notes

1. The issue appears to be specific to Flutter Web. The same shader assets load correctly on other platforms (iOS, Android, macOS, Windows, Linux).
2. The problem occurs with `ui.FragmentProgram.fromAsset()` when loading shader assets.
3. Workaround: Rename shader files to use underscores or hyphens instead of spaces (e.g., "Wrap_Debug.frag" or "Wrap-Debug.frag").
4. This issue only affects shader files whose filenames contain spaces, rather than all assets with spaces in their names.

### PR DESCRIPTION
**Pull request by ksokolovskyi**
Fixes https://github.com/flutter/flutter/issues/180862

### Description

- Adds `assetKey` encoding in `FragmentProgram.fromAsset` in `web_ui` to be consistent with the implementation in `ui`
https://github.com/flutter/flutter/blob/7e176f8c3fde96342b2c61e5b4043d53113a2b31/engine/src/flutter/lib/ui/painting.dart#L5354-L5369
- Adds test

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

File: engine/src/flutter/lib/web_ui/lib/painting.dart [hunk 1]
```diff
@@ -1004,7 +1004,12 @@ class ImageDescriptor {
 
 abstract class FragmentProgram {
   static Future<FragmentProgram> fromAsset(String assetKey) {
```
[the remark this answers is not in the document]
Comment (ksokolovskyi) [reply engine/src/flutter/lib/web_ui/lib/painting.dart:1006]: Those comment duplications are not common in `web_ui `.

File: engine/src/flutter/lib/web_ui/lib/painting.dart [hunk 2]
```diff
@@ -1004,7 +1004,12 @@ class ImageDescriptor {
...
-    return engine.renderer.createFragmentProgram(assetKey);
+    // The flutter tool converts all asset keys with spaces into URI
+    // encoded paths (replacing ' ' with '%20', for example). We perform
+    // the same encoding here so that users can load assets with the same
+    // key they have written in the pubspec.
+    final String encodedKey = Uri(path: Uri.encodeFull(assetKey)).path;
```
Comment (harryterkelsen) [inline engine/src/flutter/lib/web_ui/lib/painting.dart:1011]: I'm curious why this is needed since the `assetManager` also does the `Uri.encodeFull` encoding before sending the request for the asset. It seems we are double-encoding the URI now.

From the `AssetManager` code (`createFragmentProgram` eventually calls `assetManager.load(...)`)

```dart
  String getAssetUrl(String asset) {
    if (Uri.parse(asset).hasScheme) {
      return Uri.encodeFull(asset);
    }
    return Uri.encodeFull('$_baseUrl$assetsDir/$asset');
  }

  Future<ByteData> load(String asset) async {
    final String url = getAssetUrl(asset);
    final HttpFetchResponse response = await httpFetch(url);
    ...
  }
```

Comment (harryterkelsen) [reply engine/src/flutter/lib/web_ui/lib/painting.dart:1011]: I see. It looks like the double encoding is necessary because the Flutter tool encodes the path, so we need to request the encoded path name and therefore it needs to be double encoded.

**Review by harryterkelsen — APPROVED** [review]
LGTM

File: engine/src/flutter/lib/web_ui/lib/painting.dart (hunk 2 above)
Comment (ksokolovskyi) [reply engine/src/flutter/lib/web_ui/lib/painting.dart:1011]: Indeed, this was exactly the reason. Thanks a lot for your review!
